{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"intersects","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forArea"},{"text":" ","kind":"text"},{"text":"area","kind":"internalParam"},{"kind":"text","text":": "},{"text":"CoordinateBounds","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMCoordinateBounds"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"wrappedCoordinates"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"area","content":[{"type":"paragraph","inlineContent":[{"text":"The area to be checked against the bounds.","type":"text"}]}]},{"name":"wrappedCoordinates","content":[{"inlineContent":[{"text":"Whether to wrap the coordinate or not.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"inlineContent":[{"type":"codeVoice","code":"true"},{"type":"text","text":" if the bounds intersects "},{"code":"area","type":"codeVoice"},{"text":", ","type":"text"},{"type":"codeVoice","code":"false"},{"type":"text","text":" otherwise."}],"type":"paragraph"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds"]]},"variants":[{"paths":["\/documentation\/mapboxmaps\/coordinatebounds\/intersects(forarea:wrappedcoordinates:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/coordinatebounds\/intersects(forarea:wrappedcoordinates:)"]}],"metadata":{"role":"symbol","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"intersects","kind":"identifier"},{"kind":"text","text":"("},{"text":"forArea","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMCoordinateBounds","text":"CoordinateBounds"},{"text":", ","kind":"text"},{"text":"wrappedCoordinates","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"externalID":"c:objc(cs)MBMCoordinateBounds(im)intersectsForArea:wrappedCoordinates:","roleHeading":"Instance Method","modules":[{"name":"MapboxMaps"}],"navigatorTitle":[{"kind":"identifier","text":"intersectsForArea:wrappedCoordinates:"}],"title":"intersects(forArea:wrappedCoordinates:)"},"sections":[],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds\/intersects(forArea:wrappedCoordinates:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"Returns whether the bounds intersects ","type":"text"},{"type":"codeVoice","code":"area"},{"type":"text","text":" or not."}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateBounds/intersects(forArea:wrappedCoordinates:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"intersects"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forArea"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMCoordinateBounds","kind":"typeIdentifier","text":"CoordinateBounds"},{"text":", ","kind":"text"},{"text":"wrappedCoordinates","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"abstract":[{"text":"Returns whether the bounds intersects ","type":"text"},{"type":"codeVoice","code":"area"},{"type":"text","text":" or not."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds\/intersects(forArea:wrappedCoordinates:)","type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/coordinatebounds\/intersects(forarea:wrappedcoordinates:)","navigatorTitle":[{"text":"intersectsForArea:wrappedCoordinates:","kind":"identifier"}],"title":"intersects(forArea:wrappedCoordinates:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateBounds":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoordinateBounds"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds","kind":"symbol","title":"CoordinateBounds","type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/coordinatebounds","abstract":[{"type":"text","text":"A rectangular area as measured on a two-dimensional map projection."}],"navigatorTitle":[{"kind":"identifier","text":"CoordinateBounds"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","kind":"symbol","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"kind":"article","type":"topic","title":"MapboxMap","abstract":[],"url":"\/documentation\/mapboxmaps\/mapboxmap-apis","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","url":"\/documentation\/overview","kind":"article","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"intersectsForArea:wrappedCoordinates:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"intersectsForArea:wrappedCoordinates:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"identifier","text":"intersectsForArea:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds","text":"MBMCoordinateBounds","preciseIdentifier":"c:objc(cs)MBMCoordinateBounds","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"area","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"wrappedCoordinates:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"wrappedCoordinates"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The area to be checked against the bounds."}],"type":"paragraph"}],"name":"area"},{"content":[{"inlineContent":[{"type":"text","text":"Whether to wrap the coordinate or not."}],"type":"paragraph"}],"name":"wrappedCoordinates"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"op":"replace","value":{"kind":"content","content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"code":"true","type":"codeVoice"},{"type":"text","text":" if the bounds intersects "},{"code":"area","type":"codeVoice"},{"text":", ","type":"text"},{"code":"false","type":"codeVoice"},{"type":"text","text":" otherwise."}]}]},"path":"\/primaryContentSections\/2"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds~1intersects(forArea:wrappedCoordinates:)\/title","value":"intersectsForArea:wrappedCoordinates:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"intersectsForArea:wrappedCoordinates:"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds~1intersects(forArea:wrappedCoordinates:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds\/title","value":"MBMCoordinateBounds"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds\/fragments","value":[{"kind":"identifier","text":"MBMCoordinateBounds"}]},{"value":[{"kind":"identifier","text":"MBMCoordinateBounds"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}