{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"latLngToMercatorXY"},{"kind":"text","text":"("},{"kind":"externalParam","text":"coordinate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MercatorCoordinate","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MercatorCoordinate","preciseIdentifier":"c:objc(cs)MBMMercatorCoordinate"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"coordinate","content":[{"inlineContent":[{"type":"text","text":"The geographic coordinate to convert."}],"type":"paragraph"}]}]},{"content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"inlineContent":[{"text":"A ","type":"text"},{"code":"Vec2","type":"codeVoice"},{"text":" representing the X and Y coordinates in the Mercator projection.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Projection\/latLngToMercatorXY(coordinate:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/projection\/latlngtomercatorxy(coordinate:)"]}],"metadata":{"role":"symbol","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"latLngToMercatorXY"},{"kind":"text","text":"("},{"kind":"externalParam","text":"coordinate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MercatorCoordinate","preciseIdentifier":"c:objc(cs)MBMMercatorCoordinate"}],"modules":[{"name":"MapboxMaps"}],"title":"latLngToMercatorXY(coordinate:)","externalID":"s:10MapboxMaps10ProjectionC18latLngToMercatorXY10coordinateSo21MBMMercatorCoordinateCSo22CLLocationCoordinate2DV_tFZ","symbolKind":"method"},"abstract":[{"text":"Converts a geographic coordinate to its corresponding","type":"text"},{"text":" ","type":"text"},{"text":"Mercator projection coordinates (X, Y).","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Projection"]]},"sections":[],"kind":"symbol","references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Projection":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Projection","navigatorTitle":[{"text":"Projection","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Projection","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"Projection","url":"\/documentation\/mapboxmaps\/projection","abstract":[{"type":"text","text":"A collection of "},{"identifier":"https:\/\/en.wikipedia.org\/wiki\/Web_Mercator_projection","isActive":true,"type":"reference"},{"type":"text","text":" projection methods."}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","role":"collection","type":"topic","abstract":[],"title":"MapboxMaps Documentation","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"type":"topic","url":"\/documentation\/mapboxmaps\/mapboxmap-apis","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","role":"collectionGroup","title":"MapboxMap","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","url":"\/documentation\/mapboxmaps","title":"MapboxMaps","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"https://en.wikipedia.org/wiki/Web_Mercator_projection":{"titleInlineContent":[{"text":"Spherical Mercator","type":"text"}],"title":"Spherical Mercator","identifier":"https:\/\/en.wikipedia.org\/wiki\/Web_Mercator_projection","type":"link","url":"https:\/\/en.wikipedia.org\/wiki\/Web_Mercator_projection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MercatorCoordinate":{"abstract":[{"type":"text","text":"Describes a point on the map in Mercator projection."}],"url":"\/documentation\/mapboxmaps\/mercatorcoordinate","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MercatorCoordinate","navigatorTitle":[{"kind":"identifier","text":"MercatorCoordinate"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MercatorCoordinate"}],"title":"MercatorCoordinate"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Projection/latLngToMercatorXY(coordinate:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Projection\/latLngToMercatorXY(coordinate:)","kind":"symbol","abstract":[{"text":"Converts a geographic coordinate to its corresponding","type":"text"},{"text":" ","type":"text"},{"text":"Mercator projection coordinates (X, Y).","type":"text"}],"title":"latLngToMercatorXY(coordinate:)","role":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/projection\/latlngtomercatorxy(coordinate:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"latLngToMercatorXY"},{"kind":"text","text":"("},{"kind":"externalParam","text":"coordinate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MercatorCoordinate","preciseIdentifier":"c:objc(cs)MBMMercatorCoordinate"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"MBMMercatorCoordinate","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MercatorCoordinate\/title"},{"op":"replace","value":[{"text":"MBMMercatorCoordinate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MercatorCoordinate\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MercatorCoordinate\/navigatorTitle","op":"replace","value":[{"text":"MBMMercatorCoordinate","kind":"identifier"}]}]}]}