{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"notReady","kind":"identifier"}]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Not ready for the requested operation."}],"metadata":{"title":"LocationErrorCode.notReady","externalID":"c:@E@MBXLocationErrorCode@MBXLocationErrorCodeNotReady","role":"symbol","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"notReady","kind":"identifier"}],"navigatorTitle":[{"text":"MBXLocationErrorCodeNotReady","kind":"identifier"}],"roleHeading":"Case","modules":[{"name":"MapboxCommon"}]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode\/notReady"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode"]]},"variants":[{"paths":["\/documentation\/mapboxcommon\/locationerrorcode\/notready"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxcommon\/locationerrorcode\/notready"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Location-APIs":{"url":"\/documentation\/mapboxmaps\/location-apis","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","role":"collectionGroup","abstract":[],"type":"topic","title":"Location"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","title":"MapboxMaps Documentation","url":"\/documentation\/overview","type":"topic","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationErrorCode/notReady":{"kind":"symbol","url":"\/documentation\/mapboxcommon\/locationerrorcode\/notready","abstract":[{"type":"text","text":"Not ready for the requested operation."}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"notReady","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MBXLocationErrorCodeNotReady"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode\/notReady","title":"LocationErrorCode.notReady","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationErrorCode":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"LocationErrorCode","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/locationerrorcode","navigatorTitle":[{"text":"LocationErrorCode","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode","role":"symbol","abstract":[{"text":"Codes of location errors.","type":"text"}],"type":"topic","title":"LocationErrorCode"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","role":"collection","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"MBXLocationErrorCodeNotReady"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MBXLocationErrorCodeNotReady"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"MBXLocationErrorCodeNotReady","kind":"identifier"}]}],"kind":"declarations"}},{"op":"replace","value":"MBXLocationErrorCodeNotReady","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode~1notReady\/title"},{"value":[{"text":"MBXLocationErrorCodeNotReady","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode~1notReady\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/title","op":"replace","value":"MBXLocationErrorCode"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/fragments","value":[{"text":"MBXLocationErrorCode","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"MBXLocationErrorCode"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}