{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TilesetDescriptorOptions\/init(styleURI:minZoom:maxZoom:tilesets:stylePackOptions:extraOptions:)","interfaceLanguage":"swift"},"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"styleURI","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"minZoom","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5UInt8V","text":"UInt8","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"maxZoom","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt8","preciseIdentifier":"s:s5UInt8V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tilesets"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"]?, ","kind":"text"},{"text":"stylePackOptions","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"StylePackLoadOptions","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMStylePackLoadOptions"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"extraOptions"},{"kind":"text","text":": "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?)"}],"platforms":[],"role":"symbol","title":"init(styleURI:minZoom:maxZoom:tilesets:stylePackOptions:extraOptions:)","externalID":"c:objc(cs)MBMTilesetDescriptorOptions(im)initWithStyleURI:minZoom:maxZoom:tilesets:stylePackOptions:extraOptions:::SYNTHESIZED::c:objc(cs)MBMTilesetDescriptorOptions","roleHeading":"Initializer","symbolKind":"init","modules":[{"name":"MapboxMaps"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"styleURI","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"minZoom"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt8","preciseIdentifier":"s:s5UInt8V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"maxZoom"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt8","preciseIdentifier":"s:s5UInt8V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tilesets"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"stylePackOptions"},{"kind":"text","text":": "},{"text":"StylePackLoadOptions","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadOptions","preciseIdentifier":"c:objc(cs)MBMStylePackLoadOptions"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"extraOptions"},{"kind":"text","text":": "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?)"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/tilesetdescriptoroptions\/init(styleuri:minzoom:maxzoom:tilesets:stylepackoptions:extraoptions:)"]}],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"TilesetDescriptorOptions.init(styleURI:minZoom:maxZoom:tilesets:stylePackOptions:extraOptions:)","type":"codeVoice"},{"type":"text","text":"."}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TilesetDescriptorOptions"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","type":"topic","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"title":"MapboxMaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePackLoadOptions":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"StylePackLoadOptions"}],"abstract":[{"type":"text","text":"Describes the style package load option values."}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadOptions","title":"StylePackLoadOptions","url":"\/documentation\/mapboxmaps\/stylepackloadoptions","navigatorTitle":[{"kind":"identifier","text":"StylePackLoadOptions"}],"role":"symbol","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TilesetDescriptorOptions":{"abstract":[{"type":"text","text":"Describes the tileset descriptor option values."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TilesetDescriptorOptions","kind":"identifier"}],"navigatorTitle":[{"text":"TilesetDescriptorOptions","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/mapboxmaps\/tilesetdescriptoroptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TilesetDescriptorOptions","title":"TilesetDescriptorOptions","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","url":"\/documentation\/mapboxmaps\/tilestore-apis","title":"TileStore APIs","abstract":[],"kind":"article","type":"topic","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","url":"\/documentation\/overview","title":"MapboxMaps Documentation","type":"topic","role":"collection","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TilesetDescriptorOptions/init(styleURI:minZoom:maxZoom:tilesets:stylePackOptions:extraOptions:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"styleURI","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"minZoom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt8","preciseIdentifier":"s:s5UInt8V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"maxZoom"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt8","preciseIdentifier":"s:s5UInt8V"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"tilesets"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"]?, ","kind":"text"},{"text":"stylePackOptions","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MBMStylePackLoadOptions","text":"StylePackLoadOptions","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"extraOptions","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TilesetDescriptorOptions\/init(styleURI:minZoom:maxZoom:tilesets:stylePackOptions:extraOptions:)","role":"symbol","title":"init(styleURI:minZoom:maxZoom:tilesets:stylePackOptions:extraOptions:)","abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/tilesetdescriptoroptions\/init(styleuri:minzoom:maxzoom:tilesets:stylepackoptions:extraoptions:)"}},"variantOverrides":[{"patch":[{"op":"replace","value":"MBMStylePackLoadOptions","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadOptions\/title"},{"op":"replace","value":[{"text":"MBMStylePackLoadOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadOptions\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadOptions\/navigatorTitle","value":[{"text":"MBMStylePackLoadOptions","kind":"identifier"}]},{"op":"replace","value":"MBMTilesetDescriptorOptions","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions\/fragments","value":[{"kind":"identifier","text":"MBMTilesetDescriptorOptions"}],"op":"replace"},{"op":"replace","value":[{"text":"MBMTilesetDescriptorOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}