{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"samplingDurationMillis","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"Setting ","type":"text"},{"code":"samplingDurationMillis","type":"codeVoice"},{"text":" to 0 forces the collection of performance statistics every frame.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"A negative sampling duration is an error and results in no operation.","type":"text"}]}],"kind":"content"}],"metadata":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"samplingDurationMillis"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"navigatorTitle":[{"kind":"identifier","text":"samplingDurationMillis"}],"modules":[{"name":"MapboxMaps"}],"roleHeading":"Instance Property","title":"samplingDurationMillis","symbolKind":"property","externalID":"c:objc(cs)MBMPerformanceStatisticsOptions(py)samplingDurationMillis"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/mbmperformancestatisticsoptions\/samplingdurationmillis"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/mbmperformancestatisticsoptions\/samplingdurationmillis"]}],"abstract":[{"type":"text","text":"The minimum elapsed time required before performance statistics become available. It’s important to note that the actual"},{"type":"text","text":" "},{"type":"text","text":"collection interval may exceed this duration since statistics are aggregated during render calls. The effective collection"},{"type":"text","text":" "},{"text":"interval can be observed through the ","type":"text"},{"code":"PerformanceStatistics","type":"codeVoice"},{"text":" instance.","type":"text"}],"sections":[],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMPerformanceStatisticsOptions\/samplingDurationMillis","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatisticsOptions"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Performance":{"title":"Performance and investigations","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","kind":"article","url":"\/documentation\/mapboxmaps\/performance","type":"topic","abstract":[],"role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMPerformanceStatisticsOptions/samplingDurationMillis":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"samplingDurationMillis"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMPerformanceStatisticsOptions\/samplingDurationMillis","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"samplingDurationMillis"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"title":"samplingDurationMillis","type":"topic","url":"\/documentation\/mapboxmaps\/mbmperformancestatisticsoptions\/samplingdurationmillis","abstract":[{"type":"text","text":"The minimum elapsed time required before performance statistics become available. It’s important to note that the actual"},{"text":" ","type":"text"},{"type":"text","text":"collection interval may exceed this duration since statistics are aggregated during render calls. The effective collection"},{"text":" ","type":"text"},{"type":"text","text":"interval can be observed through the "},{"type":"codeVoice","code":"PerformanceStatistics"},{"text":" instance.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PerformanceStatisticsOptions":{"type":"topic","url":"\/documentation\/mapboxmaps\/performancestatisticsoptions","abstract":[{"text":"Options for the following statistics collection behaviors:","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"PerformanceStatisticsOptions","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatisticsOptions","title":"PerformanceStatisticsOptions","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PerformanceStatisticsOptions","kind":"identifier"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"samplingDurationMillis"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"samplingDurationMillis","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":" ","kind":"text"},{"text":"samplingDurationMillis","kind":"identifier"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMPerformanceStatisticsOptions~1samplingDurationMillis\/title","op":"replace","value":"samplingDurationMillis"},{"value":[{"text":"samplingDurationMillis","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMPerformanceStatisticsOptions~1samplingDurationMillis\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatisticsOptions\/title","value":"MBMPerformanceStatisticsOptions","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatisticsOptions\/fragments","value":[{"kind":"identifier","text":"MBMPerformanceStatisticsOptions"}],"op":"replace"}]}]}