{"abstract":[{"type":"text","text":"The amount of vertex memory (array and index buffer memory) in use at the end of the collection window."}],"variants":[{"paths":["\/documentation\/mapboxmaps\/mbmcumulativerenderingstatistics\/vertexbytes"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCumulativeRenderingStatistics\/vertexBytes"},"kind":"symbol","metadata":{"symbolKind":"property","fragments":[{"kind":"identifier","text":"vertexBytes"}],"roleHeading":"Instance Property","externalID":"c:objc(cs)MBMCumulativeRenderingStatistics(py)vertexBytes","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"vertexBytes"}],"title":"vertexBytes","modules":[{"name":"MapboxMaps"}]},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CumulativeRenderingStatistics"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":" * "},{"text":"vertexBytes","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","kind":"article","abstract":[],"url":"\/documentation\/overview","type":"topic","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CumulativeRenderingStatistics":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CumulativeRenderingStatistics","type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/cumulativerenderingstatistics","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CumulativeRenderingStatistics"}],"abstract":[],"role":"symbol","navigatorTitle":[{"text":"CumulativeRenderingStatistics","kind":"identifier"}],"title":"CumulativeRenderingStatistics"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"role":"collection","url":"\/documentation\/mapboxmaps","title":"MapboxMaps","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMCumulativeRenderingStatistics/vertexBytes":{"url":"\/documentation\/mapboxmaps\/mbmcumulativerenderingstatistics\/vertexbytes","role":"symbol","kind":"symbol","title":"vertexBytes","abstract":[{"text":"The amount of vertex memory (array and index buffer memory) in use at the end of the collection window.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCumulativeRenderingStatistics\/vertexBytes","fragments":[{"kind":"identifier","text":"vertexBytes"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Performance":{"type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","title":"Performance and investigations","kind":"article","url":"\/documentation\/mapboxmaps\/performance","role":"collectionGroup"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CumulativeRenderingStatistics\/title","op":"replace","value":"MBMCumulativeRenderingStatistics"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CumulativeRenderingStatistics\/fragments","value":[{"text":"MBMCumulativeRenderingStatistics","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CumulativeRenderingStatistics\/navigatorTitle","op":"replace","value":[{"text":"MBMCumulativeRenderingStatistics","kind":"identifier"}]}]}]}