{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Update the state map of an individual feature."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@discardableResult","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setFeatureState","kind":"identifier"},{"text":"<","kind":"text"},{"text":"T","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"feature","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"T","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"state","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"T"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps21FeaturesetFeatureTypeP5StateQa","text":"State"},{"kind":"text","text":", "},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": (((any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":")?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")? = nil) -> any ","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Cancelable","kind":"typeIdentifier","text":"Cancelable","preciseIdentifier":"c:objc(pl)MBXCancelable"},{"kind":"text","text":" "},{"text":"where","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"T"},{"kind":"text","text":" : "},{"text":"FeaturesetFeatureType","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps21FeaturesetFeatureTypeP","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeaturesetFeatureType"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The feature to update."}]}],"name":"feature"},{"name":"state","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Map of entries to update with their respective new values"}]}]},{"name":"callback","content":[{"inlineContent":[{"type":"text","text":"The "},{"code":"feature state operation callback","type":"codeVoice"},{"type":"text","text":" called when the operation completes or ends."}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"text":"Return Value","type":"heading","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"Cancelable"},{"type":"text","text":" object  that could be used to cancel the pending operation."}]}]},{"content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"The feature should have a non-nil ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeaturesetFeatureType\/id","type":"reference","isActive":true},{"text":". Otherwise,","type":"text"},{"type":"text","text":" "},{"text":"the operation will be no-op and callback will receive an error.","type":"text"}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/mapboxmaps\/mapboxmap\/setfeaturestate(_:state:callback:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap"]]},"metadata":{"role":"symbol","externalID":"s:10MapboxMaps0A3MapC15setFeatureState_5state8callbackSo13MBXCancelable_px_0F0Qzys5Error_pSgcSgtAA010FeaturesetE4TypeRzlF","symbolKind":"method","modules":[{"name":"MapboxMaps"}],"roleHeading":"Instance Method","title":"setFeatureState(_:state:callback:)","extendedModule":"MapboxMaps","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setFeatureState"},{"kind":"text","text":"<"},{"text":"T","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"T","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"T"},{"text":".","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps21FeaturesetFeatureTypeP5StateQa","text":"State","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"callback"},{"text":": (((any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?) -> any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)MBXCancelable","text":"Cancelable","kind":"typeIdentifier"}],"tags":[{"text":"SPI","type":"spi"}]},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/setFeatureState(_:state:callback:)","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FeaturesetFeatureType/id":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps19FeaturesetFeatureIdV","text":"FeaturesetFeatureId"},{"kind":"text","text":"?"}],"kind":"symbol","required":true,"tags":[{"text":"SPI","type":"spi"}],"type":"topic","title":"id","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeaturesetFeatureType\/id","abstract":[{"type":"text","text":"An identifier of the feature."}],"url":"\/documentation\/mapboxmaps\/featuresetfeaturetype\/id"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","title":"MapboxMaps Documentation","kind":"article","url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/setFeatureState(_:state:callback:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/setFeatureState(_:state:callback:)","role":"symbol","tags":[{"type":"spi","text":"SPI"}],"abstract":[{"text":"Update the state map of an individual feature.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setFeatureState"},{"kind":"text","text":"<"},{"text":"T","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"T","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"state","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"T","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps21FeaturesetFeatureTypeP5StateQa","text":"State","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"callback","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?) -> any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MBXCancelable","text":"Cancelable"}],"title":"setFeatureState(_:state:callback:)","type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/setfeaturestate(_:state:callback:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"role":"collectionGroup","kind":"article","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","type":"topic","title":"MapboxMap","url":"\/documentation\/mapboxmaps\/mapboxmap-apis"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","title":"MapboxMaps","kind":"symbol","url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Cancelable":{"abstract":[{"type":"text","text":"Allows to cancel the associated asynchronous operation"}],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Cancelable"}],"title":"Cancelable","navigatorTitle":[{"text":"Cancelable","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Cancelable","url":"\/documentation\/mapboxcommon\/cancelable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MapboxMap"}],"role":"symbol","title":"MapboxMap","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapboxMap"}],"url":"\/documentation\/mapboxmaps\/mapboxmap","abstract":[{"type":"text","text":"Provides access to the map model, including the camera, style, observable map events,"},{"type":"text","text":" "},{"type":"text","text":"and querying rendered features."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FeaturesetFeatureType":{"navigatorTitle":[{"text":"FeaturesetFeatureType","kind":"identifier"}],"tags":[{"type":"spi","text":"SPI"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FeaturesetFeatureType"}],"type":"topic","abstract":[{"text":"A type constraint for a generic featureset feature.","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeaturesetFeatureType","title":"FeaturesetFeatureType","url":"\/documentation\/mapboxmaps\/featuresetfeaturetype"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MBXCancelable","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/fragments","value":[{"text":"MBXCancelable","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBXCancelable"}]}]}]}