{"variants":[{"paths":["\/documentation\/mapboxcommon\/accuracylevel\/high"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/accuracylevel\/high"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel\/high"},"abstract":[{"text":"High accuracy requirement.","type":"text"}],"kind":"symbol","metadata":{"title":"AccuracyLevel.high","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"high","kind":"identifier"}],"modules":[{"name":"MapboxCommon"}],"externalID":"c:@E@MBXAccuracyLevel@MBXAccuracyLevelHigh","navigatorTitle":[{"text":"MBXAccuracyLevelHigh","kind":"identifier"}],"role":"symbol","symbolKind":"case"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"high"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","title":"MapboxMaps Documentation","kind":"article","url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/AccuracyLevel":{"url":"\/documentation\/mapboxcommon\/accuracylevel","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AccuracyLevel"}],"type":"topic","abstract":[{"type":"text","text":"The accuracy of the observed location"}],"role":"symbol","title":"AccuracyLevel","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AccuracyLevel","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Location-APIs":{"type":"topic","kind":"article","abstract":[],"url":"\/documentation\/mapboxmaps\/location-apis","role":"collectionGroup","title":"Location","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","title":"MapboxMaps","kind":"symbol","url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/AccuracyLevel/high":{"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"High accuracy requirement."}],"url":"\/documentation\/mapboxcommon\/accuracylevel\/high","title":"AccuracyLevel.high","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"high","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel\/high","navigatorTitle":[{"kind":"identifier","text":"MBXAccuracyLevelHigh"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"MBXAccuracyLevelHigh","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MBXAccuracyLevelHigh"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"MBXAccuracyLevelHigh","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":"MBXAccuracyLevel","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel\/title"},{"value":[{"text":"MBXAccuracyLevel","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel\/fragments","op":"replace"},{"value":[{"text":"MBXAccuracyLevel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel~1high\/title","value":"MBXAccuracyLevelHigh"},{"value":[{"text":"MBXAccuracyLevelHigh","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel~1high\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}