{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Heading"},"topicSections":[{"title":"Initializers","anchor":"Initializers","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Heading\/init(direction:accuracy:timestamp:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Heading\/init(from:)"]},{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Heading\/accuracy","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Heading\/direction","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Heading\/timestamp"]},{"title":"Default Implementations","anchor":"Default-Implementations","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Heading\/Equatable-Implementations"]}],"metadata":{"roleHeading":"Structure","symbolKind":"struct","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Heading","kind":"identifier"}],"navigatorTitle":[{"text":"Heading","kind":"identifier"}],"role":"symbol","externalID":"s:10MapboxMaps7HeadingV","modules":[{"name":"MapboxMaps"}],"title":"Heading"},"sections":[],"relationshipsSections":[{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"],"type":"conformsTo"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Heading","kind":"identifier"}]}]}],"variants":[{"paths":["\/documentation\/mapboxmaps\/heading"],"traits":[{"interfaceLanguage":"swift"}]}],"seeAlsoSections":[{"title":"Location","anchor":"Location","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationManager","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck2DConfiguration","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Model","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckBearing","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProviderDelegate","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Coordinate2D","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationExtraKeys","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProviderRequest","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceFactory","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/DeviceLocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckRenderingData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/IntervalSettings"]}],"abstract":[{"text":"The azimuth (orientation) of the user’s device, relative to true or magnetic north.","type":"text"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Coordinate2D":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Coordinate2D","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Coordinate2D","kind":"identifier"}],"kind":"symbol","title":"Coordinate2D","abstract":[{"text":"Boxed version of CLLocationCoordinate2D","type":"text"}],"url":"\/documentation\/mapboxcommon\/coordinate2d","navigatorTitle":[{"text":"Coordinate2D","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Model":{"kind":"symbol","abstract":[{"text":"A structure represeting a Model","type":"text"}],"url":"\/documentation\/mapboxmaps\/model","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Model"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Model","navigatorTitle":[{"kind":"identifier","text":"Model"}],"title":"Model","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LocationManager":{"kind":"symbol","abstract":[{"type":"text","text":"An object responsible for managing user location Puck."}],"url":"\/documentation\/mapboxmaps\/locationmanager","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationManager"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationManager","navigatorTitle":[{"kind":"identifier","text":"LocationManager"}],"title":"LocationManager","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/AccuracyLevel":{"type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AccuracyLevel","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel","title":"AccuracyLevel","abstract":[{"type":"text","text":"The accuracy of the observed location"}],"kind":"symbol","url":"\/documentation\/mapboxcommon\/accuracylevel","navigatorTitle":[{"text":"AccuracyLevel","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PuckType":{"title":"PuckType","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PuckType","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/pucktype","abstract":[{"text":"Represents the different types of pucks","type":"text"}],"navigatorTitle":[{"text":"PuckType","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckType","type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Heading/Equatable-Implementations":{"title":"Equatable Implementations","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/heading\/equatable-implementations","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Heading\/Equatable-Implementations","type":"topic","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Puck3DConfiguration":{"abstract":[],"kind":"symbol","url":"\/documentation\/mapboxmaps\/puck3dconfiguration","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Puck3DConfiguration","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration","navigatorTitle":[{"text":"Puck3DConfiguration","kind":"identifier"}],"title":"Puck3DConfiguration","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PuckBearing":{"abstract":[{"type":"text","text":"Controls how the puck is oriented"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PuckBearing","kind":"identifier"}],"type":"topic","title":"PuckBearing","url":"\/documentation\/mapboxmaps\/puckbearing","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckBearing","role":"symbol","navigatorTitle":[{"text":"PuckBearing","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationError":{"title":"LocationError","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationError","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"LocationError","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationError","url":"\/documentation\/mapboxcommon\/locationerror","abstract":[{"text":"Error code with brief explanation.","type":"text"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"url":"\/documentation\/mapboxmaps","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","title":"MapboxMaps","kind":"symbol","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationServiceFactory":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceFactory","url":"\/documentation\/mapboxcommon\/locationservicefactory","title":"LocationServiceFactory","abstract":[{"text":"Location service factory.","type":"text"}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationServiceFactory","kind":"identifier"}],"navigatorTitle":[{"text":"LocationServiceFactory","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"url":"\/documentation\/overview","kind":"article","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationProviderRequest":{"url":"\/documentation\/mapboxcommon\/locationproviderrequest","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProviderRequest","title":"LocationProviderRequest","abstract":[{"type":"text","text":"Data model that contains parameters for location requests."}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationProviderRequest","kind":"identifier"}],"navigatorTitle":[{"text":"LocationProviderRequest","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AppleLocationProvider":{"url":"\/documentation\/mapboxmaps\/applelocationprovider","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProvider","kind":"symbol","navigatorTitle":[{"text":"AppleLocationProvider","kind":"identifier"}],"title":"AppleLocationProvider","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AppleLocationProvider","kind":"identifier"}],"abstract":[{"type":"text","text":"A location provider based on CoreLocation’s "},{"type":"codeVoice","code":"CLLocationManager"},{"type":"text","text":"."}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeadingObserver":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HeadingObserver","kind":"identifier"}],"abstract":[{"text":"Listens to ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingProvider","type":"reference","isActive":true},{"text":"’s updates.","type":"text"}],"url":"\/documentation\/mapboxmaps\/headingobserver","navigatorTitle":[{"text":"HeadingObserver","kind":"identifier"}],"title":"HeadingObserver","kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingObserver","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Heading/direction":{"abstract":[{"type":"text","text":"The heading direction (measured in degrees) relative to true or magnetic north."}],"kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"direction","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CLLocationDirection","text":"CLLocationDirection","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Heading\/direction","role":"symbol","title":"direction","url":"\/documentation\/mapboxmaps\/heading\/direction"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Location-APIs":{"kind":"article","role":"collectionGroup","title":"Location","url":"\/documentation\/mapboxmaps\/location-apis","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","abstract":[],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Puck2DConfiguration":{"navigatorTitle":[{"text":"Puck2DConfiguration","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"Puck2DConfiguration","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Puck2DConfiguration","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/puck2dconfiguration","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck2DConfiguration","abstract":[],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/AccuracyAuthorization":{"title":"AccuracyAuthorization","type":"topic","role":"symbol","navigatorTitle":[{"text":"AccuracyAuthorization","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization","abstract":[{"text":"Accuracy authorization granted by user to the app.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AccuracyAuthorization","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapboxcommon\/accuracyauthorization"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeadingProvider":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HeadingProvider","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingProvider","role":"symbol","title":"HeadingProvider","abstract":[{"text":"Provides heading data to drive the location puck.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"HeadingProvider","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/headingprovider"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationProvider":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider","title":"LocationProvider","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationProvider","kind":"identifier"}],"abstract":[{"type":"text","text":"Location provider that provides locations"}],"navigatorTitle":[{"text":"LocationProvider","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/mapboxcommon\/locationprovider"},"doc://com.mapbox.MapboxMaps/s8SendableP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Location":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location","title":"Location","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Location","kind":"identifier"}],"abstract":[{"text":"Location information.","type":"text"}],"navigatorTitle":[{"text":"Location","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/mapboxcommon\/location"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationServiceObserver":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationServiceObserver","kind":"identifier"}],"navigatorTitle":[{"text":"LocationServiceObserver","kind":"identifier"}],"abstract":[{"type":"text","text":"Observers for getting updates from LocationService."}],"type":"topic","title":"LocationServiceObserver","url":"\/documentation\/mapboxcommon\/locationserviceobserver","role":"symbol","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PuckRenderingData":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckRenderingData","title":"PuckRenderingData","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PuckRenderingData","kind":"identifier"}],"abstract":[{"type":"text","text":"Represents the interpolated data ready to render the user location puck."}],"navigatorTitle":[{"text":"PuckRenderingData","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/mapboxmaps\/puckrenderingdata"},"doc://com.mapbox.MapboxMaps/SQ":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Heading":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Heading","title":"Heading","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Heading","kind":"identifier"}],"abstract":[{"text":"The azimuth (orientation) of the user’s device, relative to true or magnetic north.","type":"text"}],"navigatorTitle":[{"text":"Heading","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/mapboxmaps\/heading"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/IntervalSettings":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/IntervalSettings","abstract":[{"type":"text","text":"The interval for active location updates"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IntervalSettings","kind":"identifier"}],"kind":"symbol","type":"topic","title":"IntervalSettings","url":"\/documentation\/mapboxcommon\/intervalsettings","role":"symbol","navigatorTitle":[{"text":"IntervalSettings","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationObserver":{"url":"\/documentation\/mapboxcommon\/locationobserver","abstract":[{"text":"Observer for getting updates from a LocationProvider.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationObserver","navigatorTitle":[{"text":"LocationObserver","kind":"identifier"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationObserver","kind":"identifier"}],"title":"LocationObserver","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Heading/accuracy":{"url":"\/documentation\/mapboxmaps\/heading\/accuracy","abstract":[{"type":"text","text":"The maximum deviation (measured in degrees) between the reported heading and the true geomagnetic heading."}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Heading\/accuracy","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accuracy","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CLLocationDirection","text":"CLLocationDirection","kind":"typeIdentifier"}],"title":"accuracy","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Heading/timestamp":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Heading\/timestamp","title":"timestamp","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timestamp","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The time at which this heading was determined."}],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/mapboxmaps\/heading\/timestamp"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Heading/init(direction:accuracy:timestamp:)":{"title":"init(direction:accuracy:timestamp:)","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Heading\/init(direction:accuracy:timestamp:)","type":"topic","abstract":[{"text":"Creates a heading.","type":"text"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/heading\/init(direction:accuracy:timestamp:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"direction","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CLLocationDirection","text":"CLLocationDirection","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"accuracy","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CLLocationDirection","text":"CLLocationDirection","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"timestamp","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationExtraKeys":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationExtraKeys","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationExtraKeys","title":"LocationExtraKeys","navigatorTitle":[{"text":"LocationExtraKeys","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/locationextrakeys","kind":"symbol","abstract":[{"text":"Keys for additional information (extra) in Location.","type":"text"}],"type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Heading/init(from:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)CLHeading","text":"CLHeading","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Creates a heading from CLHeading."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Heading\/init(from:)","title":"init(from:)","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/heading\/init(from:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/DeviceLocationProvider":{"abstract":[{"text":"Location provider specialisation that provides real-time locations generated from the device","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/DeviceLocationProvider","title":"DeviceLocationProvider","navigatorTitle":[{"text":"DeviceLocationProvider","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/devicelocationprovider","kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DeviceLocationProvider","kind":"identifier"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LocationOptions":{"navigatorTitle":[{"text":"LocationOptions","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/locationoptions","type":"topic","title":"LocationOptions","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationOptions","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationOptions","kind":"identifier"}],"abstract":[{"text":"A struct to configure a ","type":"text"},{"type":"codeVoice","code":"LocationManager"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AppleLocationProviderDelegate":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AppleLocationProviderDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"The "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProviderDelegate","type":"reference","isActive":true},{"type":"text","text":" protocol defines a set of optional methods that you"},{"type":"text","text":" "},{"type":"text","text":"can use to receive events from an associated location provider object."}],"type":"topic","url":"\/documentation\/mapboxmaps\/applelocationproviderdelegate","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProviderDelegate","title":"AppleLocationProviderDelegate","role":"symbol","navigatorTitle":[{"text":"AppleLocationProviderDelegate","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationErrorCode":{"type":"topic","kind":"symbol","abstract":[{"text":"Codes of location errors.","type":"text"}],"navigatorTitle":[{"text":"LocationErrorCode","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/locationerrorcode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationErrorCode","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode","title":"LocationErrorCode"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PermissionStatus":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PermissionStatus","kind":"identifier"}],"navigatorTitle":[{"text":"PermissionStatus","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/permissionstatus","title":"PermissionStatus","abstract":[{"text":"Location permissions granted by user to the app.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MBXCoordinate2D","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Coordinate2D\/title"},{"value":[{"kind":"identifier","text":"MBXCoordinate2D"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Coordinate2D\/fragments"},{"value":[{"kind":"identifier","text":"MBXCoordinate2D"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Coordinate2D\/navigatorTitle"},{"value":"MBXAccuracyLevel","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel\/title"},{"value":[{"kind":"identifier","text":"MBXAccuracyLevel"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel\/fragments"},{"value":[{"text":"MBXAccuracyLevel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel\/navigatorTitle"},{"value":"MBXLocationError","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationError\/title"},{"value":[{"text":"MBXLocationError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationError\/fragments"},{"value":[{"text":"MBXLocationError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationError\/navigatorTitle"},{"value":"MBXLocationServiceFactory","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceFactory\/title"},{"value":[{"text":"MBXLocationServiceFactory","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceFactory\/fragments"},{"value":[{"text":"MBXLocationServiceFactory","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceFactory\/navigatorTitle"},{"value":"MBXLocationProviderRequest","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProviderRequest\/title"},{"value":[{"text":"MBXLocationProviderRequest","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProviderRequest\/fragments"},{"value":[{"text":"MBXLocationProviderRequest","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProviderRequest\/navigatorTitle"},{"value":"MBXAccuracyAuthorization","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization\/title"},{"value":[{"text":"MBXAccuracyAuthorization","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization\/fragments"},{"value":[{"kind":"identifier","text":"MBXAccuracyAuthorization"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization\/navigatorTitle"},{"value":"MBXLocationProvider","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/title"},{"value":[{"text":"MBXLocationProvider","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/fragments"},{"value":[{"text":"MBXLocationProvider","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/navigatorTitle"},{"value":"MBXLocation","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/title"},{"value":[{"text":"MBXLocation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/fragments"},{"value":[{"text":"MBXLocation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/navigatorTitle"},{"value":"MBXLocationServiceObserver","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver\/title"},{"value":[{"text":"MBXLocationServiceObserver","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver\/fragments"},{"value":[{"text":"MBXLocationServiceObserver","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver\/navigatorTitle"},{"value":"MBXIntervalSettings","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1IntervalSettings\/title"},{"value":[{"text":"MBXIntervalSettings","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1IntervalSettings\/fragments"},{"value":[{"kind":"identifier","text":"MBXIntervalSettings"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1IntervalSettings\/navigatorTitle"},{"value":"MBXLocationObserver","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/title"},{"value":[{"kind":"identifier","text":"MBXLocationObserver"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/fragments"},{"value":[{"text":"MBXLocationObserver","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/navigatorTitle"},{"value":"MBXLocationExtraKeys","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationExtraKeys\/title"},{"value":[{"kind":"identifier","text":"MBXLocationExtraKeys"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationExtraKeys\/fragments"},{"value":[{"kind":"identifier","text":"MBXLocationExtraKeys"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationExtraKeys\/navigatorTitle"},{"value":"MBXDeviceLocationProvider","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1DeviceLocationProvider\/title"},{"value":[{"kind":"identifier","text":"MBXDeviceLocationProvider"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1DeviceLocationProvider\/fragments"},{"value":[{"text":"MBXDeviceLocationProvider","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1DeviceLocationProvider\/navigatorTitle"},{"value":"MBXLocationErrorCode","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/title"},{"value":[{"text":"MBXLocationErrorCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/fragments"},{"value":[{"text":"MBXLocationErrorCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/navigatorTitle"},{"value":"MBXPermissionStatus","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/title"},{"value":[{"text":"MBXPermissionStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/fragments"},{"value":[{"kind":"identifier","text":"MBXPermissionStatus"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/navigatorTitle"}]}]}