{"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"article","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus"]]},"metadata":{"role":"collectionGroup","roleHeading":"API Collection","title":"RawRepresentable Implementations","modules":[{"name":"MapboxCommon"},{"name":"MapboxMaps"}]},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus\/RawRepresentable-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus\/hashValue"]},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus\/hash(into:)"]}],"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PermissionStatus/hashValue":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"hashValue","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"role":"symbol","type":"topic","kind":"symbol","abstract":[],"url":"\/documentation\/mapboxcommon\/permissionstatus\/hashvalue","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus\/hashValue","title":"hashValue","conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}]}},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PermissionStatus":{"title":"PermissionStatus","abstract":[{"text":"Location permissions granted by user to the app.","type":"text"}],"navigatorTitle":[{"text":"PermissionStatus","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapboxcommon\/permissionstatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PermissionStatus"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"title":"MapboxMaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Location-APIs":{"url":"\/documentation\/mapboxmaps\/location-apis","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","abstract":[],"title":"Location","kind":"article","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","kind":"article","role":"collection","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PermissionStatus/hash(into:)":{"abstract":[],"kind":"symbol","title":"hash(into:)","role":"symbol","url":"\/documentation\/mapboxcommon\/permissionstatus\/hash(into:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV","text":"Hasher"},{"text":")","kind":"text"}],"conformance":{"conformancePrefix":[{"text":"Conforms when","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}]},"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus\/hash(into:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/title","value":"MBXPermissionStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/fragments","value":[{"kind":"identifier","text":"MBXPermissionStatus"}]},{"value":[{"kind":"identifier","text":"MBXPermissionStatus"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}