{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions\/init(clientCallback:minZoom:maxZoom:tileSize:)"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"clientCallback","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient","text":"CustomRasterSourceClient","preciseIdentifier":"c:objc(cs)MBMCustomRasterSourceClient","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"minZoom"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5UInt8V","text":"UInt8","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"maxZoom","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V","text":"UInt8"},{"text":", ","kind":"text"},{"text":"tileSize","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt16","preciseIdentifier":"s:s6UInt16V"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/mapboxmaps\/customrastersourceoptions\/init(clientcallback:minzoom:maxzoom:tilesize:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/customrastersourceoptions\/init(clientcallback:minzoom:maxzoom:tilesize:)"]}],"kind":"symbol","metadata":{"navigatorTitle":[{"text":"initWithClientCallback:minZoom:maxZoom:tileSize:","kind":"identifier"}],"externalID":"c:objc(cs)MBMCustomRasterSourceOptions(im)initWithClientCallback:minZoom:maxZoom:tileSize:","modules":[{"name":"MapboxMaps"}],"roleHeading":"Initializer","title":"init(clientCallback:minZoom:maxZoom:tileSize:)","symbolKind":"init","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"clientCallback"},{"kind":"text","text":": "},{"text":"CustomRasterSourceClient","preciseIdentifier":"c:objc(cs)MBMCustomRasterSourceClient","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"minZoom"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5UInt8V","kind":"typeIdentifier","text":"UInt8"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"maxZoom"},{"kind":"text","text":": "},{"text":"UInt8","kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V"},{"kind":"text","text":", "},{"text":"tileSize","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt16","preciseIdentifier":"s:s6UInt16V"},{"kind":"text","text":")"}]},"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"type":"topic","role":"collection","url":"\/documentation\/mapboxmaps","title":"MapboxMaps","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Sources":{"title":"Sources","role":"collectionGroup","kind":"article","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources","abstract":[],"url":"\/documentation\/mapboxmaps\/sources"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceOptions":{"type":"topic","url":"\/documentation\/mapboxmaps\/customrastersourceoptions","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CustomRasterSourceOptions","kind":"identifier"}],"abstract":[{"type":"text","text":"Options for custom raster source."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions","role":"symbol","title":"CustomRasterSourceOptions","navigatorTitle":[{"text":"CustomRasterSourceOptions","kind":"identifier"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceClient":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"CustomRasterSourceClient","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient","url":"\/documentation\/mapboxmaps\/customrastersourceclient","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomRasterSourceClient"}],"abstract":[],"title":"CustomRasterSourceClient","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","role":"collection","kind":"article","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceOptions/init(clientCallback:minZoom:maxZoom:tileSize:)":{"type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"clientCallback"},{"text":": ","kind":"text"},{"text":"CustomRasterSourceClient","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMCustomRasterSourceClient"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"minZoom"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5UInt8V","text":"UInt8","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"maxZoom"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt8","preciseIdentifier":"s:s5UInt8V"},{"text":", ","kind":"text"},{"text":"tileSize","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt16","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt16V"},{"text":")","kind":"text"}],"role":"symbol","kind":"symbol","title":"init(clientCallback:minZoom:maxZoom:tileSize:)","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions\/init(clientCallback:minZoom:maxZoom:tileSize:)","url":"\/documentation\/mapboxmaps\/customrastersourceoptions\/init(clientcallback:minzoom:maxzoom:tilesize:)","navigatorTitle":[{"text":"initWithClientCallback:minZoom:maxZoom:tileSize:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithClientCallback:minZoom:maxZoom:tileSize:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"initWithClientCallback:minZoom:maxZoom:tileSize:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithClientCallback:"},{"kind":"text","text":"("},{"text":"MBMCustomRasterSourceClient","preciseIdentifier":"c:objc(cs)MBMCustomRasterSourceClient","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"clientCallback","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"minZoom:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@uint8_t","text":"uint8_t"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"minZoom"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxZoom:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@uint8_t","text":"uint8_t","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"maxZoom"},{"kind":"text","text":" "},{"text":"tileSize:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"uint16_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@uint16_t"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"tileSize"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/title","op":"replace","value":"MBMCustomRasterSourceOptions"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/fragments","value":[{"text":"MBMCustomRasterSourceOptions","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBMCustomRasterSourceOptions"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient\/title","value":"MBMCustomRasterSourceClient"},{"value":[{"text":"MBMCustomRasterSourceClient","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient\/navigatorTitle","value":[{"text":"MBMCustomRasterSourceClient","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"initWithClientCallback:minZoom:maxZoom:tileSize:","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions~1init(clientCallback:minZoom:maxZoom:tileSize:)\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions~1init(clientCallback:minZoom:maxZoom:tileSize:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithClientCallback:minZoom:maxZoom:tileSize:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}