{"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions"]]},"variants":[{"paths":["\/documentation\/mapboxmaps\/customrastersourceoptions\/maxzoom"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/customrastersourceoptions\/maxzoom"]}],"kind":"symbol","abstract":[{"text":"A maximum zoom level, at which to create vector tiles.","type":"text"}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions\/maxZoom","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxZoom","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt8","preciseIdentifier":"s:s5UInt8V","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","level":2,"type":"heading"},{"inlineContent":[{"text":"A higher maximum zoom level provides greater details at high map zoom levels.","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"The default value is ","type":"text"},{"code":"18","type":"codeVoice"},{"text":".","type":"text"}]}]}],"metadata":{"role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"text":"maxZoom","kind":"identifier"}],"modules":[{"name":"MapboxMaps"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"maxZoom","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5UInt8V","kind":"typeIdentifier","text":"UInt8"}],"title":"maxZoom","symbolKind":"property","externalID":"c:objc(cs)MBMCustomRasterSourceOptions(py)maxZoom"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceOptions/maxZoom":{"navigatorTitle":[{"kind":"identifier","text":"maxZoom"}],"url":"\/documentation\/mapboxmaps\/customrastersourceoptions\/maxzoom","abstract":[{"text":"A maximum zoom level, at which to create vector tiles.","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"maxZoom","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5UInt8V","text":"UInt8","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions\/maxZoom","type":"topic","title":"maxZoom"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceOptions":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceOptions"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions","type":"topic","abstract":[{"type":"text","text":"Options for custom raster source."}],"role":"symbol","title":"CustomRasterSourceOptions","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomRasterSourceOptions","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/customrastersourceoptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Sources":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources","role":"collectionGroup","title":"Sources","kind":"article","url":"\/documentation\/mapboxmaps\/sources","abstract":[],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","title":"MapboxMaps Documentation","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","role":"collection","url":"\/documentation\/mapboxmaps","kind":"symbol","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"maxZoom"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"maxZoom","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@uint8_t","text":"uint8_t","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"maxZoom","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"maxZoom","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions~1maxZoom\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions~1maxZoom\/fragments","value":[{"text":"maxZoom","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/title","value":"MBMCustomRasterSourceOptions"},{"value":[{"text":"MBMCustomRasterSourceOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/navigatorTitle","value":[{"kind":"identifier","text":"MBMCustomRasterSourceOptions"}],"op":"replace"}]}]}