{"metadata":{"role":"symbol","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"message"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"title":"message","externalID":"c:objc(cs)MBMStylePackError(py)message","symbolKind":"property","modules":[{"name":"MapboxMaps"}],"navigatorTitle":[{"kind":"identifier","text":"message"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackError-swift.class\/message"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/mapboxmaps\/stylepackerror-swift.class\/message"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/stylepackerror-swift.class\/message"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMapsInternal","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackError-swift.class"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"text":"An error message.","type":"text"}],"kind":"symbol","references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","type":"topic","title":"MapboxMaps Documentation","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePackError-swift.class":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"StylePackError","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"StylePackError"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/stylepackerror-swift.class","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackError-swift.class","kind":"symbol","abstract":[{"text":"Describes a style package load request error.","type":"text"}],"title":"StylePackError","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMapsInternal":{"role":"collectionGroup","url":"\/documentation\/mapboxmaps\/coremapsinternal","kind":"article","type":"topic","title":"CoreMaps - Internal","abstract":[{"text":"Maps rendering SDK also known as GL-Native. These are for internal use only.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMapsInternal"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePackError-swift.class/message":{"role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"message","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"message"}],"title":"message","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackError-swift.class\/message","abstract":[{"type":"text","text":"An error message."}],"url":"\/documentation\/mapboxmaps\/stylepackerror-swift.class\/message"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","title":"MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"message","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"message","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"text":"message","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackError-swift.class\/title","value":"MBMStylePackError"},{"value":[{"text":"MBMStylePackError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackError-swift.class\/fragments"},{"value":[{"kind":"identifier","text":"MBMStylePackError"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackError-swift.class\/navigatorTitle"},{"value":"message","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackError-swift.class~1message\/title","op":"replace"},{"value":[{"text":"message","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackError-swift.class~1message\/fragments"}]}]}