{"abstract":[{"type":"text","text":"Set access token to be used by all Mapbox SDK."}],"variants":[{"paths":["\/documentation\/mapboxcommon\/mbxmapboxoptions\/setaccesstokenfortoken:"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:objc(cs)MBXMapboxOptions(cm)setAccessTokenForToken:","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setAccessTokenForToken:"}],"navigatorTitle":[{"text":"setAccessTokenForToken:","kind":"identifier"}],"role":"symbol","title":"setAccessTokenForToken:","symbolKind":"method","roleHeading":"Type Method","modules":[{"name":"MapboxCommon"}]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXMapboxOptions\/setAccessTokenForToken:"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Settings-and-Constants","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MapboxOptions"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"setAccessTokenForToken:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"token"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"token","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Token string to set."}]}]}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","role":"collection","type":"topic","abstract":[],"title":"MapboxMaps Documentation","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Settings-and-Constants":{"kind":"article","title":"Settings and Constants","role":"collectionGroup","type":"topic","url":"\/documentation\/mapboxmaps\/settings-and-constants","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Settings-and-Constants","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXMapboxOptions/setAccessTokenForToken:":{"kind":"symbol","role":"symbol","fragments":[{"text":"+ ","kind":"text"},{"text":"setAccessTokenForToken:","kind":"identifier"}],"title":"setAccessTokenForToken:","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXMapboxOptions\/setAccessTokenForToken:","abstract":[{"type":"text","text":"Set access token to be used by all Mapbox SDK."}],"type":"topic","navigatorTitle":[{"text":"setAccessTokenForToken:","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/mbxmapboxoptions\/setaccesstokenfortoken:"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MapboxOptions":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapboxOptions","kind":"identifier"}],"navigatorTitle":[{"text":"MapboxOptions","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"MapboxOptions","url":"\/documentation\/mapboxcommon\/mapboxoptions","abstract":[{"text":"Class for Mapbox SDK settings management","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MapboxOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","role":"collection","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","type":"topic","title":"MapboxMaps"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MBXMapboxOptions","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MapboxOptions\/title","op":"replace"},{"value":[{"text":"MBXMapboxOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MapboxOptions\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MBXMapboxOptions"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MapboxOptions\/navigatorTitle","op":"replace"}]}]}