{"kind":"article","sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"topicSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType\/hashValue"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType\/hash(into:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}],"metadata":{"modules":[{"name":"MapboxMaps"},{"name":"MapboxCommon"}],"role":"collectionGroup","title":"RawRepresentable Implementations","roleHeading":"API Collection"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TurfAPI","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType"]]},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType\/RawRepresentable-Implementations","interfaceLanguage":"swift"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","role":"collection","url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"title":"MapboxMaps","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/GeometryType/hash(into:)":{"kind":"symbol","type":"topic","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"text":"into","kind":"externalParam"},{"kind":"text","text":": "},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:s6HasherV","text":"Hasher","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType\/hash(into:)","role":"symbol","conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}]},"url":"\/documentation\/mapboxcommon\/geometrytype\/hash(into:)","title":"hash(into:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TurfAPI":{"abstract":[{"type":"text","text":"Describes "},{"code":"turf-swift","type":"codeVoice"},{"type":"text","text":" dependency objects"}],"kind":"article","title":"Turf","url":"\/documentation\/mapboxmaps\/turfapi","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TurfAPI","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/GeometryType":{"type":"topic","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GeometryType","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType","navigatorTitle":[{"kind":"identifier","text":"GeometryType"}],"abstract":[],"url":"\/documentation\/mapboxcommon\/geometrytype","title":"GeometryType","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","abstract":[],"kind":"article","url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/GeometryType/hashValue":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType\/hashValue","kind":"symbol","url":"\/documentation\/mapboxcommon\/geometrytype\/hashvalue","abstract":[],"role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"conformancePrefix":[{"text":"Conforms when","type":"text"}]},"title":"hashValue"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType\/title","value":"MBXGeometryType"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType\/fragments","value":[{"kind":"identifier","text":"MBXGeometryType"}],"op":"replace"},{"op":"replace","value":[{"text":"MBXGeometryType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}