{"abstract":[{"text":"Minimum zoom level for the offline region","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minZoom","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"minZoom"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"minZoom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"title":"minZoom","externalID":"c:objc(cs)MBMOfflineRegionGeometryDefinition(py)minZoom","symbolKind":"property","roleHeading":"Instance Property","role":"symbol","platforms":[],"modules":[{"name":"MapboxMaps"}]},"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/offlineregiongeometrydefinition\/minzoom"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/offlineregiongeometrydefinition\/minzoom"]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionGeometryDefinition\/minZoom","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionGeometryDefinition"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"url":"\/documentation\/mapboxmaps","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","title":"MapboxMaps","kind":"symbol","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionGeometryDefinition":{"role":"symbol","url":"\/documentation\/mapboxmaps\/offlineregiongeometrydefinition","navigatorTitle":[{"kind":"identifier","text":"OfflineRegionGeometryDefinition"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionGeometryDefinition","abstract":[{"type":"text","text":"An offline region definition is a geographic region defined by a style URL,"},{"type":"text","text":" "},{"type":"text","text":"a geometry, zoom range, and device pixel ratio. Both "},{"code":"minZoom","type":"codeVoice"},{"type":"text","text":" and "},{"code":"maxZoom","type":"codeVoice"},{"type":"text","text":" must be ≥ 0,"},{"type":"text","text":" "},{"type":"text","text":"and "},{"code":"maxZoom","type":"codeVoice"},{"type":"text","text":" must be ≥ "},{"code":"minZoom","type":"codeVoice"},{"type":"text","text":". The "},{"code":"maxZoom","type":"codeVoice"},{"type":"text","text":" may be ∞, in which case for each tile source,"},{"type":"text","text":" "},{"type":"text","text":"the region will include tiles from "},{"code":"minZoom","type":"codeVoice"},{"type":"text","text":" up to the maximum zoom level provided by that source."},{"type":"text","text":" "},{"type":"text","text":"The "},{"code":"pixelRatio","type":"codeVoice"},{"type":"text","text":" must be ≥ 0 and should typically be 1.0 or 2.0."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OfflineRegionGeometryDefinition"}],"kind":"symbol","deprecated":true,"title":"OfflineRegionGeometryDefinition"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"url":"\/documentation\/overview","kind":"article","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Offline":{"type":"topic","title":"Offline Support","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","url":"\/documentation\/mapboxmaps\/offline","abstract":[],"kind":"article","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","url":"\/documentation\/mapboxmaps\/coremaps","type":"topic","abstract":[{"type":"text","text":"Maps rendering SDK also known as GL-Native"}],"role":"collectionGroup","kind":"article","title":"Core Maps API"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionGeometryDefinition/minZoom":{"url":"\/documentation\/mapboxmaps\/offlineregiongeometrydefinition\/minzoom","type":"topic","title":"minZoom","role":"symbol","deprecated":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionGeometryDefinition\/minZoom","abstract":[{"type":"text","text":"Minimum zoom level for the offline region"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minZoom","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"text":"minZoom","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"minZoom","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"minZoom","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":" "},{"kind":"identifier","text":"minZoom"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionGeometryDefinition\/title","value":"MBMOfflineRegionGeometryDefinition","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionGeometryDefinition\/fragments","value":[{"kind":"identifier","text":"MBMOfflineRegionGeometryDefinition"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionGeometryDefinition\/navigatorTitle","value":[{"text":"MBMOfflineRegionGeometryDefinition","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionGeometryDefinition~1minZoom\/title","value":"minZoom","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionGeometryDefinition~1minZoom\/fragments","value":[{"text":"minZoom","kind":"identifier"}],"op":"replace"}]}]}