{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"]]},"metadata":{"title":"Settings and Constants","modules":[{"name":"MapboxMaps"}],"roleHeading":"API Collection","role":"collectionGroup"},"kind":"article","seeAlsoSections":[{"anchor":"Other","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Camera-and-coordinates","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Ornaments","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Gestures"],"title":"Other"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"title":"Settings","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MapboxCommonSettings","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MapboxOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMapsOptions"],"anchor":"Settings"},{"title":"Common Settings","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsService","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceFactory","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceStorageType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SdkInformation"],"anchor":"Common-Settings"},{"title":"Constants","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapConstants"],"anchor":"Constants"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Settings-and-Constants"},"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsService":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsService","abstract":[{"text":"Platform independent settings service. Settings service is a key\/value storage (persistent or non","type":"text"},{"text":" ","type":"text"},{"text":"persistent), that also allows to register observers to get notifications when values are updated.","type":"text"}],"title":"SettingsService","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SettingsService"}],"navigatorTitle":[{"kind":"identifier","text":"SettingsService"}],"url":"\/documentation\/mapboxcommon\/settingsservice","type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SdkInformation":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SdkInformation","url":"\/documentation\/mapboxcommon\/sdkinformation","kind":"symbol","title":"SdkInformation","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Provides information about a given Mapbox SDK. This information is then used to populate the “User-Agent” HTTP header"},{"type":"text","text":" "},{"type":"text","text":"of HTTP requests generated from within Mapbox SDKs. Mapbox SDKs include Maps, Navigation, Search, and others."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SdkInformation","kind":"identifier"}],"navigatorTitle":[{"text":"SdkInformation","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","abstract":[],"url":"\/documentation\/overview","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Gestures":{"url":"\/documentation\/mapboxmaps\/gestures","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Gestures","kind":"article","abstract":[],"role":"collectionGroup","title":"Gestures","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsServiceStorageType":{"type":"topic","role":"symbol","title":"SettingsServiceStorageType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SettingsServiceStorageType"}],"navigatorTitle":[{"kind":"identifier","text":"SettingsServiceStorageType"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceStorageType","abstract":[{"type":"text","text":"Enum that contains possible storage types that can be used for settings service."}],"url":"\/documentation\/mapboxcommon\/settingsservicestoragetype"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Ornaments":{"abstract":[],"type":"topic","title":"Ornaments","url":"\/documentation\/mapboxmaps\/ornaments","role":"collectionGroup","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Ornaments"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"url":"\/documentation\/mapboxmaps","role":"collection","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapConstants":{"url":"\/documentation\/mapboxmaps\/mapconstants","navigatorTitle":[{"kind":"identifier","text":"MapConstants"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapConstants"}],"role":"symbol","abstract":[{"type":"text","text":"Collection of useful constants."}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapConstants","title":"MapConstants"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMapsOptions":{"navigatorTitle":[{"kind":"identifier","text":"MapboxMapsOptions"}],"title":"MapboxMapsOptions","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMapsOptions","url":"\/documentation\/mapboxmaps\/mapboxmapsoptions","kind":"symbol","role":"symbol","abstract":[{"text":"Configurations for the external resources that are used by Maps API object,","type":"text"},{"text":" ","type":"text"},{"text":"such as maps data directory and base URL.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapboxMapsOptions"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MapboxCommonSettings":{"kind":"symbol","url":"\/documentation\/mapboxcommon\/mapboxcommonsettings","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapboxCommonSettings","kind":"identifier"}],"abstract":[{"type":"text","text":"Set of common keys that can be used to configure all Mapbox SDKs."}],"title":"MapboxCommonSettings","navigatorTitle":[{"text":"MapboxCommonSettings","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MapboxCommonSettings"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Location-APIs":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","type":"topic","url":"\/documentation\/mapboxmaps\/location-apis","abstract":[],"title":"Location","kind":"article","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MapboxOptions":{"role":"symbol","title":"MapboxOptions","abstract":[{"type":"text","text":"Class for Mapbox SDK settings management"}],"kind":"symbol","url":"\/documentation\/mapboxcommon\/mapboxoptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapboxOptions"}],"navigatorTitle":[{"kind":"identifier","text":"MapboxOptions"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MapboxOptions","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsServiceFactory":{"kind":"symbol","type":"topic","title":"SettingsServiceFactory","role":"symbol","abstract":[{"type":"text","text":"Factory that allows to create settings service instance."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceFactory","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SettingsServiceFactory","kind":"identifier"}],"navigatorTitle":[{"text":"SettingsServiceFactory","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/settingsservicefactory"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsServiceError":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SettingsServiceError"}],"url":"\/documentation\/mapboxcommon\/settingsserviceerror","title":"SettingsServiceError","abstract":[{"text":"Structure for keeping an information about errors that can happen when using Settings service","type":"text"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SettingsServiceError"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Camera-and-coordinates":{"kind":"article","title":"Camera and coordinates","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Camera-and-coordinates","type":"topic","url":"\/documentation\/mapboxmaps\/camera-and-coordinates","role":"collectionGroup"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsService\/title","value":"MBXSettingsService","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsService\/fragments","value":[{"kind":"identifier","text":"MBXSettingsService"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsService\/navigatorTitle","value":[{"text":"MBXSettingsService","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SdkInformation\/title","value":"MBXSdkInformation","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SdkInformation\/fragments","value":[{"text":"MBXSdkInformation","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SdkInformation\/navigatorTitle","value":[{"kind":"identifier","text":"MBXSdkInformation"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceStorageType\/title","value":"MBXSettingsServiceStorageType","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceStorageType\/fragments","value":[{"kind":"identifier","text":"MBXSettingsServiceStorageType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceStorageType\/navigatorTitle","value":[{"text":"MBXSettingsServiceStorageType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapConstants\/title","value":"MBMMapConstants","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapConstants\/fragments","value":[{"kind":"identifier","text":"MBMMapConstants"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapConstants\/navigatorTitle","value":[{"kind":"identifier","text":"MBMMapConstants"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MapboxCommonSettings\/title","value":"MBXMapboxCommonSettings","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MapboxCommonSettings\/fragments","value":[{"text":"MBXMapboxCommonSettings","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MapboxCommonSettings\/navigatorTitle","value":[{"text":"MBXMapboxCommonSettings","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MapboxOptions\/title","value":"MBXMapboxOptions","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MapboxOptions\/fragments","value":[{"kind":"identifier","text":"MBXMapboxOptions"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MapboxOptions\/navigatorTitle","value":[{"text":"MBXMapboxOptions","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceFactory\/title","value":"MBXSettingsServiceFactory","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceFactory\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXSettingsServiceFactory"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceFactory\/navigatorTitle","op":"replace","value":[{"text":"MBXSettingsServiceFactory","kind":"identifier"}]}]}]}