{"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH"],"type":"conformsTo","kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoaded","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"SourceDataLoaded"},{"type":"text","text":" event is emitted when source data is loaded."}],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoaded\/dataId","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoaded\/sourceId","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoaded\/tileId","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoaded\/timeInterval","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoaded\/type"],"generated":true,"anchor":"Instance-Properties"}],"variants":[{"paths":["\/documentation\/mapboxmaps\/sourcedataloaded"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/sourcedataloaded"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"title":"Events","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraChanged","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapIdle","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceAdded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceRemoved","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageMissing","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnused","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameStarted","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinished","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequest","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GenericEvent"],"generated":true,"anchor":"Events"}],"metadata":{"title":"SourceDataLoaded","symbolKind":"class","roleHeading":"Class","modules":[{"name":"MapboxMaps"}],"role":"symbol","externalID":"c:objc(cs)MBMSourceDataLoaded","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SourceDataLoaded","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SourceDataLoaded"}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SourceDataLoaded","kind":"identifier"}]}]},{"content":[{"level":2,"anchor":"overview","text":"Overview","type":"heading"},{"inlineContent":[{"type":"text","text":"Note: The event will be emitted synchronously in cases when the source’s metadata is available when a source is added to the style."}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","abstract":[],"url":"\/documentation\/overview","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoaded":{"navigatorTitle":[{"text":"MapLoaded","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"text":"The style has been fully loaded, and the ","type":"text"},{"type":"codeVoice","code":"map"},{"text":" has rendered all visible tiles.","type":"text"},{"text":" ","type":"text"},{"text":"The event will be emitted only once for the current style. If it is required to","type":"text"},{"text":" ","type":"text"},{"text":"observe an event where all required resources are loaded or rendered, please","type":"text"},{"text":" ","type":"text"},{"text":"check the following events: ","type":"text"},{"type":"codeVoice","code":"MapIdle"},{"text":", ","type":"text"},{"type":"codeVoice","code":"StyleDataLoaded"},{"text":", and ","type":"text"},{"type":"codeVoice","code":"RenderFrameFinished"},{"text":".","type":"text"}],"url":"\/documentation\/mapboxmaps\/maploaded","title":"MapLoaded","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapLoaded","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoaded"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GenericEvent":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GenericEvent","type":"topic","kind":"symbol","title":"GenericEvent","abstract":[{"text":"The generic event type.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GenericEvent"}],"navigatorTitle":[{"kind":"identifier","text":"GenericEvent"}],"url":"\/documentation\/mapboxmaps\/genericevent"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceDataLoaded/sourceId":{"abstract":[{"type":"text","text":"The identifier of a source."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sourceId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/sourcedataloaded\/sourceid","navigatorTitle":[{"kind":"identifier","text":"sourceId"}],"type":"topic","title":"sourceId","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoaded\/sourceId"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMSourceDataLoaded/initWithSourceId:type:loaded:tileId:dataId:timeInterval:":{"fragments":[{"text":"- ","kind":"text"},{"text":"initWithSourceId:type:loaded:tileId:dataId:timeInterval:","kind":"identifier"}],"title":"initWithSourceId:type:loaded:tileId:dataId:timeInterval:","navigatorTitle":[{"text":"initWithSourceId:type:loaded:tileId:dataId:timeInterval:","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/mbmsourcedataloaded\/initwithsourceid:type:loaded:tileid:dataid:timeinterval:","abstract":[],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMSourceDataLoaded\/initWithSourceId:type:loaded:tileId:dataId:timeInterval:","kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/SH":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceAdded":{"kind":"symbol","abstract":[{"text":"The source has been added with ","type":"text"},{"code":"addStyleSource","type":"codeVoice"},{"text":" method.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceAdded"}],"navigatorTitle":[{"kind":"identifier","text":"SourceAdded"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceAdded","type":"topic","url":"\/documentation\/mapboxmaps\/sourceadded","role":"symbol","title":"SourceAdded"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceDataLoaded":{"abstract":[{"text":"The ","type":"text"},{"code":"SourceDataLoaded","type":"codeVoice"},{"text":" event is emitted when source data is loaded.","type":"text"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/sourcedataloaded","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoaded","title":"SourceDataLoaded","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SourceDataLoaded","kind":"identifier"}],"navigatorTitle":[{"text":"SourceDataLoaded","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapIdle":{"abstract":[{"text":"The ","type":"text"},{"code":"map","type":"codeVoice"},{"text":" has entered the idle state. The ","type":"text"},{"code":"map","type":"codeVoice"},{"text":" is idle when there are no ongoing","type":"text"},{"text":" ","type":"text"},{"text":"animations, transitions and the ","type":"text"},{"code":"map","type":"codeVoice"},{"text":" has rendered all requested non-volatile tiles","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"(e.g., live traffic tiles). The event will not be emitted if "},{"type":"codeVoice","code":"setUserAnimationInProgress"},{"type":"text","text":" "},{"type":"text","text":"and \/ or "},{"type":"codeVoice","code":"setGestureInProgress"},{"type":"text","text":" is set to "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"kind":"symbol","type":"topic","title":"MapIdle","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapIdle","url":"\/documentation\/mapboxmaps\/mapidle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapIdle"}],"navigatorTitle":[{"kind":"identifier","text":"MapIdle"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceDataLoaded/dataId":{"kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/sourcedataloaded\/dataid","title":"dataId","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dataId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoaded\/dataId","role":"symbol","navigatorTitle":[{"text":"dataId","kind":"identifier"}],"abstract":[{"text":"When the ","type":"text"},{"code":"type","type":"codeVoice"},{"text":" of an event is ","type":"text"},{"code":"SourceDataLoadedType.Metadata","type":"codeVoice"},{"text":" and the","type":"text"},{"text":" ","type":"text"},{"text":"data identifier was provided to the ","type":"text"},{"code":"setStyleGeoJSONSourceData","type":"codeVoice"},{"text":" method,","type":"text"},{"text":" ","type":"text"},{"text":"this property can be used to determine what data was loaded by the ","type":"text"},{"type":"codeVoice","code":"GeoJSON"},{"type":"text","text":" source."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"url":"\/documentation\/mapboxmaps","role":"collection","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResourceRequest":{"navigatorTitle":[{"text":"ResourceRequest","kind":"identifier"}],"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"ResourceRequest"},{"text":" event allows the application to observe resource requests made by a ","type":"text"},{"type":"codeVoice","code":"map"},{"text":" or ","type":"text"},{"type":"codeVoice","code":"map snapshotter"},{"text":" object.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequest","title":"ResourceRequest","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ResourceRequest","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/resourcerequest","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleLoaded":{"abstract":[{"text":"The requested style has been fully loaded, including specified sprite, and sources’ metadata.","type":"text"}],"title":"StyleLoaded","navigatorTitle":[{"kind":"identifier","text":"StyleLoaded"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleLoaded","role":"symbol","url":"\/documentation\/mapboxmaps\/styleloaded","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StyleLoaded"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMSourceDataLoaded/loaded":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMSourceDataLoaded\/loaded","kind":"symbol","fragments":[{"kind":"identifier","text":"loaded"}],"abstract":[{"text":"When the ","type":"text"},{"type":"codeVoice","code":"type"},{"type":"text","text":" of an event is "},{"type":"codeVoice","code":"SourceDataLoadedType.Tile"},{"type":"text","text":", the "},{"type":"codeVoice","code":"loaded"},{"type":"text","text":" "},{"type":"text","text":"property will be set to "},{"type":"codeVoice","code":"true"},{"type":"text","text":" if all source data required for the visible"},{"type":"text","text":" "},{"text":"viewport of the ","type":"text"},{"code":"map","type":"codeVoice"},{"text":" are loaded.","type":"text"}],"url":"\/documentation\/mapboxmaps\/mbmsourcedataloaded\/loaded","type":"topic","role":"symbol","title":"loaded"},"doc://com.mapbox.MapboxMaps/objc(pl)NSObject":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.mapbox.MapboxMaps/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleImageRemoveUnused":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnused","type":"topic","kind":"symbol","title":"StyleImageRemoveUnused","abstract":[{"text":"An image requested by the ","type":"text"},{"code":"map","type":"codeVoice"},{"text":" through the ","type":"text"},{"code":"StyleImageMissing","type":"codeVoice"},{"text":" event is no longer","type":"text"},{"text":" ","type":"text"},{"text":"needed and can be removed using the ","type":"text"},{"code":"removeStyleImage","type":"codeVoice"},{"text":" method. The application can","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"decide whether the image should be kept or removed."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StyleImageRemoveUnused"}],"navigatorTitle":[{"kind":"identifier","text":"StyleImageRemoveUnused"}],"url":"\/documentation\/mapboxmaps\/styleimageremoveunused"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceDataLoaded/tileId":{"navigatorTitle":[{"kind":"identifier","text":"tileId"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tileId"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MBMCanonicalTileID","kind":"typeIdentifier","text":"CanonicalTileID"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoaded\/tileId","type":"topic","url":"\/documentation\/mapboxmaps\/sourcedataloaded\/tileid","role":"symbol","kind":"symbol","title":"tileId","abstract":[{"type":"text","text":"When the "},{"type":"codeVoice","code":"type"},{"type":"text","text":" of an event is "},{"type":"codeVoice","code":"SourceDataLoadedType.Tile"},{"type":"text","text":" the "},{"type":"codeVoice","code":"tileId"},{"type":"text","text":" "},{"type":"text","text":"property defines the tile coordinate."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderFrameStarted":{"title":"RenderFrameStarted","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameStarted","navigatorTitle":[{"kind":"identifier","text":"RenderFrameStarted"}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RenderFrameStarted"}],"url":"\/documentation\/mapboxmaps\/renderframestarted","abstract":[{"text":"The ","type":"text"},{"code":"map","type":"codeVoice"},{"text":" started rendering a frame.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderFrameFinished":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinished","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RenderFrameFinished"}],"kind":"symbol","title":"RenderFrameFinished","url":"\/documentation\/mapboxmaps\/renderframefinished","role":"symbol","abstract":[{"text":"The ","type":"text"},{"code":"map","type":"codeVoice"},{"text":" finished rendering a frame.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"RenderFrameFinished"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoadingError":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingError","abstract":[{"type":"text","text":"Describes an error that has occurred while loading the "},{"type":"codeVoice","code":"map"},{"type":"text","text":". The "},{"type":"codeVoice","code":"type"},{"type":"text","text":" property"},{"type":"text","text":" "},{"type":"text","text":"defines what resource could not be loaded, and the "},{"type":"codeVoice","code":"message"},{"type":"text","text":" property will contain"},{"type":"text","text":" "},{"type":"text","text":"a descriptive error message."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapLoadingError","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MapLoadingError"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/maploadingerror","title":"MapLoadingError"},"doc://com.mapbox.MapboxMaps/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceDataLoaded/timeInterval":{"type":"topic","url":"\/documentation\/mapboxmaps\/sourcedataloaded\/timeinterval","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoaded\/timeInterval","abstract":[{"text":"The ","type":"text"},{"code":"timeInterval.begin","type":"codeVoice"},{"text":" is when source data begins loading, and the ","type":"text"},{"code":"timeInterval.end","type":"codeVoice"},{"text":" is when source data is loaded.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"timeInterval"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MBMEventTimeInterval","kind":"typeIdentifier","text":"EventTimeInterval"}],"title":"timeInterval","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"timeInterval"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleImageMissing":{"abstract":[{"text":"A style needs an image that is missing from the sprite sheet. This event is","type":"text"},{"text":" ","type":"text"},{"text":"emitted when the ","type":"text"},{"code":"map","type":"codeVoice"},{"text":" renders visible tiles, and one of the required images","type":"text"},{"text":" ","type":"text"},{"text":"is missing in the sprite sheet. The event observer has to provide the missing","type":"text"},{"text":" ","type":"text"},{"text":"image by calling the ","type":"text"},{"code":"addStyleImage","type":"codeVoice"},{"text":" method.","type":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/styleimagemissing","title":"StyleImageMissing","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StyleImageMissing","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"StyleImageMissing"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageMissing","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","kind":"article","title":"Map events","url":"\/documentation\/mapboxmaps\/events","type":"topic","role":"collectionGroup","abstract":[{"type":"text","text":"The simplified diagram of the events emitted by the map is displayed below."}]},"doc://com.mapbox.MapboxMaps/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject","title":"NSObject"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceDataLoaded/type":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoaded\/type","role":"symbol","title":"type","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SourceDataLoadedType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMSourceDataLoadedType"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"type","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/sourcedataloaded\/type","abstract":[{"type":"text","text":"The type of a loaded data."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraChanged":{"title":"CameraChanged","navigatorTitle":[{"kind":"identifier","text":"CameraChanged"}],"url":"\/documentation\/mapboxmaps\/camerachanged","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraChanged"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraChanged","type":"topic","abstract":[{"text":"This event is emitted whenever the visible viewport changes its size","type":"text"},{"text":" ","type":"text"},{"text":"due to the invocation of the ","type":"text"},{"code":"setSize","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"setBounds","type":"codeVoice"},{"text":" methods or when","type":"text"},{"text":" ","type":"text"},{"text":"the camera is modified by calling camera methods. The event is emitted","type":"text"},{"text":" ","type":"text"},{"text":"synchronously so that an updated camera state can be read immediately.","type":"text"}]},"doc://com.mapbox.MapboxMaps/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","title":"Swift.Equatable"},"doc://com.mapbox.MapboxMaps/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleDataLoaded":{"title":"StyleDataLoaded","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoaded","url":"\/documentation\/mapboxmaps\/styledataloaded","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StyleDataLoaded"}],"abstract":[{"text":"The style data has been loaded. The event will be emitted once for each ","type":"text"},{"code":"StyleDataLoadedType","type":"codeVoice"},{"text":" ","type":"text"},{"text":"type during style loading. If a new style is set, events will be emitted again for the newly set style.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"StyleDataLoaded"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceRemoved":{"abstract":[{"text":"The source has been removed with ","type":"text"},{"code":"removeStyleSource","type":"codeVoice"},{"text":" method.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceRemoved","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SourceRemoved"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceRemoved"}],"url":"\/documentation\/mapboxmaps\/sourceremoved","title":"SourceRemoved","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"MBMSourceDataLoaded","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"MBMSourceDataLoaded"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"MBMSourceDataLoaded"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMSourceDataLoaded\/loaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoaded\/dataId","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoaded\/sourceId","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoaded\/tileId","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoaded\/timeInterval","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoaded\/type"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMSourceDataLoaded\/initWithSourceId:type:loaded:tileId:dataId:timeInterval:"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true}],"op":"replace","path":"\/topicSections"},{"value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"value":[{"title":"Events","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraChanged","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapIdle","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceAdded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceRemoved","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageMissing","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnused","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameStarted","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinished","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequest","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GenericEvent"],"generated":true,"anchor":"Events"}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBMSourceDataLoaded","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MBMMapLoaded","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoaded\/title"},{"value":[{"text":"MBMMapLoaded","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoaded\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoaded\/navigatorTitle","value":[{"kind":"identifier","text":"MBMMapLoaded"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEvent\/title","value":"MBMGenericEvent","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEvent\/fragments","value":[{"text":"MBMGenericEvent","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEvent\/navigatorTitle","value":[{"text":"MBMGenericEvent","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoaded~1sourceId\/title","value":"sourceId","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoaded~1sourceId\/fragments","value":[{"text":"sourceId","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAdded\/title","value":"MBMSourceAdded","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAdded\/fragments","value":[{"kind":"identifier","text":"MBMSourceAdded"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAdded\/navigatorTitle","value":[{"text":"MBMSourceAdded","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoaded\/title","value":"MBMSourceDataLoaded","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoaded\/fragments","value":[{"text":"MBMSourceDataLoaded","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoaded\/navigatorTitle","value":[{"text":"MBMSourceDataLoaded","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdle\/title","value":"MBMMapIdle","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdle\/fragments","value":[{"kind":"identifier","text":"MBMMapIdle"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdle\/navigatorTitle","value":[{"kind":"identifier","text":"MBMMapIdle"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoaded~1dataId\/title","value":"dataId","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoaded~1dataId\/fragments","value":[{"kind":"identifier","text":"dataId"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequest\/title","value":"MBMResourceRequest","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequest\/fragments","value":[{"kind":"identifier","text":"MBMResourceRequest"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequest\/navigatorTitle","value":[{"text":"MBMResourceRequest","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoaded\/title","value":"MBMStyleLoaded","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoaded\/fragments","value":[{"kind":"identifier","text":"MBMStyleLoaded"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoaded\/navigatorTitle","value":[{"text":"MBMStyleLoaded","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnused\/title","value":"MBMStyleImageRemoveUnused","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnused\/fragments","value":[{"kind":"identifier","text":"MBMStyleImageRemoveUnused"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnused\/navigatorTitle","value":[{"kind":"identifier","text":"MBMStyleImageRemoveUnused"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoaded~1tileId\/title","value":"tileId","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoaded~1tileId\/fragments","value":[{"text":"tileId","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameStarted\/title","value":"MBMRenderFrameStarted","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameStarted\/fragments","value":[{"kind":"identifier","text":"MBMRenderFrameStarted"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameStarted\/navigatorTitle","value":[{"kind":"identifier","text":"MBMRenderFrameStarted"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinished\/title","value":"MBMRenderFrameFinished","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinished\/fragments","value":[{"kind":"identifier","text":"MBMRenderFrameFinished"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinished\/navigatorTitle","value":[{"kind":"identifier","text":"MBMRenderFrameFinished"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingError\/title","value":"MBMMapLoadingError","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingError\/fragments","value":[{"text":"MBMMapLoadingError","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingError\/navigatorTitle","value":[{"kind":"identifier","text":"MBMMapLoadingError"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoaded~1timeInterval\/title","value":"timeInterval"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoaded~1timeInterval\/fragments","op":"replace","value":[{"text":"timeInterval","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageMissing\/title","op":"replace","value":"MBMStyleImageMissing"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageMissing\/fragments","op":"replace","value":[{"text":"MBMStyleImageMissing","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageMissing\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMStyleImageMissing"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoaded~1type\/title","op":"replace","value":"type"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoaded~1type\/fragments","op":"replace","value":[{"text":"type","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChanged\/title","op":"replace","value":"MBMCameraChanged"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChanged\/fragments","op":"replace","value":[{"text":"MBMCameraChanged","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChanged\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMCameraChanged"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoaded\/title","op":"replace","value":"MBMStyleDataLoaded"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoaded\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMStyleDataLoaded"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoaded\/navigatorTitle","op":"replace","value":[{"text":"MBMStyleDataLoaded","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceRemoved\/title","op":"replace","value":"MBMSourceRemoved"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceRemoved\/fragments","op":"replace","value":[{"text":"MBMSourceRemoved","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceRemoved\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMSourceRemoved"}]}]}]}