{"metadata":{"role":"symbol","externalID":"c:objc(cs)MBXHttpRequestOrResponse","navigatorTitle":[{"kind":"identifier","text":"HttpRequestOrResponse"}],"modules":[{"name":"MapboxCommon"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HttpRequestOrResponse"}],"roleHeading":"Class","symbolKind":"class","title":"HttpRequestOrResponse"},"sections":[],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestOrResponse","interfaceLanguage":"swift"},"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"]},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH"]}],"topicSections":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestOrResponse\/type"]},{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestOrResponse\/getHttpRequest()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestOrResponse\/getHttpResponse()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestOrResponse\/isHttpRequest()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestOrResponse\/isHttpResponse()"]},{"title":"Type Methods","anchor":"Type-Methods","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestOrResponse\/fromHttpRequest(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestOrResponse\/fromHttpResponse(_:)"]}],"abstract":[{"type":"text","text":"Contains either an HttpRequest or an HttpResponse."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HttpRequestOrResponse"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/httprequestorresponse"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/httprequestorresponse"]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestOrResponse/isHttpRequest()":{"url":"\/documentation\/mapboxcommon\/httprequestorresponse\/ishttprequest()","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"isHttpRequest"}],"role":"symbol","title":"isHttpRequest()","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestOrResponse\/isHttpRequest()","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isHttpRequest"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://com.mapbox.MapboxMaps/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestOrResponse/fromHttpResponse(_:)":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestOrResponse\/fromHttpResponse(_:)","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"fromHttpResponse:"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fromHttpResponse"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXHttpResponse","text":"HttpResponse"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"}],"url":"\/documentation\/mapboxcommon\/httprequestorresponse\/fromhttpresponse(_:)","title":"fromHttpResponse(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestOrResponse/fromHttpRequest(_:)":{"url":"\/documentation\/mapboxcommon\/httprequestorresponse\/fromhttprequest(_:)","navigatorTitle":[{"text":"fromHttpRequest:","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[],"type":"topic","title":"fromHttpRequest(_:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fromHttpRequest","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBXHttpRequest","text":"HttpRequest","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestOrResponse\/fromHttpRequest(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestOrResponse/type":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestOrResponse\/type","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@MBXHttpRequestOrResponseType","kind":"typeIdentifier","text":"HttpRequestOrResponseType"}],"type":"topic","title":"type","url":"\/documentation\/mapboxcommon\/httprequestorresponse\/type","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"type"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestOrResponse/isHttpResponse()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isHttpResponse","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestOrResponse\/isHttpResponse()","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"isHttpResponse","kind":"identifier"}],"abstract":[],"title":"isHttpResponse()","type":"topic","url":"\/documentation\/mapboxcommon\/httprequestorresponse\/ishttpresponse()"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"kind":"article","role":"collection","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/SH":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestOrResponse/getHttpResponse()":{"title":"getHttpResponse()","navigatorTitle":[{"text":"getHttpResponse","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestOrResponse\/getHttpResponse()","url":"\/documentation\/mapboxcommon\/httprequestorresponse\/gethttpresponse()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getHttpResponse","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"HttpResponse","preciseIdentifier":"c:objc(cs)MBXHttpResponse","kind":"typeIdentifier"}],"abstract":[],"type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/s7CVarArgP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"kind":"symbol","title":"MapboxCommon","type":"topic","abstract":[],"role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","url":"\/documentation\/mapboxcommon"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestOrResponse":{"navigatorTitle":[{"kind":"identifier","text":"HttpRequestOrResponse"}],"abstract":[{"text":"Contains either an HttpRequest or an HttpResponse.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HttpRequestOrResponse"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestOrResponse","url":"\/documentation\/mapboxcommon\/httprequestorresponse","role":"symbol","kind":"symbol","title":"HttpRequestOrResponse","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestOrResponse/getHttpRequest()":{"url":"\/documentation\/mapboxcommon\/httprequestorresponse\/gethttprequest()","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getHttpRequest","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"HttpRequest","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXHttpRequest"}],"title":"getHttpRequest()","abstract":[],"navigatorTitle":[{"text":"getHttpRequest","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestOrResponse\/getHttpRequest()","type":"topic"},"doc://com.mapbox.MapboxMaps/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","type":"unresolvable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"MBXHttpRequestOrResponse","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"MBXHttpRequestOrResponse"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"MBXHttpRequestOrResponse"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestOrResponse\/type"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestOrResponse\/getHttpRequest()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestOrResponse\/getHttpResponse()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestOrResponse\/isHttpRequest()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestOrResponse\/isHttpResponse()"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestOrResponse\/fromHttpRequest(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestOrResponse\/fromHttpResponse(_:)"],"title":"Type Methods","anchor":"Type-Methods","generated":true}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBXHttpRequestOrResponse","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestOrResponse~1isHttpRequest()\/title","value":"isHttpRequest"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestOrResponse~1isHttpRequest()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"isHttpRequest","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestOrResponse~1fromHttpResponse(_:)\/title","value":"fromHttpResponse:"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestOrResponse~1fromHttpResponse(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"fromHttpResponse:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestOrResponse~1fromHttpRequest(_:)\/title","value":"fromHttpRequest:"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestOrResponse~1fromHttpRequest(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"fromHttpRequest:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestOrResponse~1type\/title","value":"type"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestOrResponse~1type\/fragments","value":[{"text":"type","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestOrResponse~1isHttpResponse()\/title","value":"isHttpResponse"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestOrResponse~1isHttpResponse()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isHttpResponse"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestOrResponse~1getHttpResponse()\/title","value":"getHttpResponse"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestOrResponse~1getHttpResponse()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"getHttpResponse","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestOrResponse\/title","value":"MBXHttpRequestOrResponse"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestOrResponse\/fragments","value":[{"text":"MBXHttpRequestOrResponse","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestOrResponse\/navigatorTitle","value":[{"kind":"identifier","text":"MBXHttpRequestOrResponse"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestOrResponse~1getHttpRequest()\/title","value":"getHttpRequest"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestOrResponse~1getHttpRequest()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getHttpRequest"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}