{"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBXCacheClearingErrorTypeToString","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CacheClearingErrorType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBXCacheClearingErrorType"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}],"symbolKind":"func","externalID":"c:@F@MBXCacheClearingErrorTypeToString","title":"MBXCacheClearingErrorTypeToString(_:)","roleHeading":"Function","navigatorTitle":[{"text":"MBXCacheClearingErrorTypeToString","kind":"identifier"}],"modules":[{"name":"MapboxCommon"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBXCacheClearingErrorTypeToString","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"cache_clearing_error_type","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"CacheClearingErrorType","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingErrorType","preciseIdentifier":"c:@E@MBXCacheClearingErrorType","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/mbxcacheclearingerrortypetostring(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/mbxcacheclearingerrortypetostring(_:)"]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXCacheClearingErrorTypeToString(_:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"kind":"symbol","title":"MapboxCommon","type":"topic","abstract":[],"role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","url":"\/documentation\/mapboxcommon"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"kind":"article","role":"collection","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXCacheClearingErrorTypeToString(_:)":{"role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBXCacheClearingErrorTypeToString","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CacheClearingErrorType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBXCacheClearingErrorType"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}],"navigatorTitle":[{"text":"MBXCacheClearingErrorTypeToString","kind":"identifier"}],"kind":"symbol","title":"MBXCacheClearingErrorTypeToString(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXCacheClearingErrorTypeToString(_:)","url":"\/documentation\/mapboxcommon\/mbxcacheclearingerrortypetostring(_:)","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/CacheClearingErrorType":{"abstract":[{"text":"Describes the reason for a cache clearing failure.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingErrorType","navigatorTitle":[{"text":"CacheClearingErrorType","kind":"identifier"}],"title":"CacheClearingErrorType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CacheClearingErrorType","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/mapboxcommon\/cacheclearingerrortype","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Function","op":"replace","path":"\/metadata\/roleHeading"},{"value":"MBXCacheClearingErrorTypeToString","op":"replace","path":"\/metadata\/title"},{"value":"func","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"MBXCacheClearingErrorTypeToString"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"MBXCacheClearingErrorTypeToString"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBXCacheClearingErrorType","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingErrorType","text":"MBXCacheClearingErrorType"},{"kind":"text","text":" "},{"kind":"internalParam","text":"cache_clearing_error_type"},{"kind":"text","text":");"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MBXCacheClearingErrorTypeToString","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MBXCacheClearingErrorTypeToString(_:)\/title"},{"value":[{"kind":"identifier","text":"MBXCacheClearingErrorTypeToString"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MBXCacheClearingErrorTypeToString(_:)\/fragments"},{"value":"MBXCacheClearingErrorType","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingErrorType\/title"},{"value":[{"text":"MBXCacheClearingErrorType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingErrorType\/fragments"},{"value":[{"text":"MBXCacheClearingErrorType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingErrorType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}