{"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsService","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Settings-and-Constants"]]},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH"],"type":"conformsTo"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"SettingsService","roleHeading":"Class","modules":[{"name":"MapboxCommon"}],"symbolKind":"class","externalID":"c:objc(cs)MBXSettingsService","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SettingsService","kind":"identifier"}],"navigatorTitle":[{"text":"SettingsService","kind":"identifier"}],"role":"symbol"},"variants":[{"paths":["\/documentation\/mapboxcommon\/settingsservice"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxcommon\/settingsservice"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Platform independent settings service. Settings service is a key\/value storage (persistent or non","type":"text"},{"text":" ","type":"text"},{"text":"persistent), that also allows to register observers to get notifications when values are updated.","type":"text"}],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsService\/erase(key:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsService\/get(key:type:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsService\/get(key:type:defaultValue:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsService\/has(key:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsService\/set(key:value:)"],"generated":true,"anchor":"Instance-Methods"}],"seeAlsoSections":[{"title":"Common Settings","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceFactory","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceStorageType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SdkInformation"],"generated":true,"anchor":"Common-Settings"}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SettingsService","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsService/get(key:type:defaultValue:)":{"title":"get(key:type:defaultValue:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsService\/get(key:type:defaultValue:)","url":"\/documentation\/mapboxcommon\/settingsservice\/get(key:type:defaultvalue:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"get","kind":"identifier"},{"text":"<","kind":"text"},{"text":"T","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"key","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"T","kind":"typeIdentifier"},{"text":".Type, ","kind":"text"},{"text":"defaultValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"T","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Result","preciseIdentifier":"s:s6ResultO","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"T","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"SettingsServiceError","preciseIdentifier":"s:12MapboxCommon20SettingsServiceErrorV","kind":"typeIdentifier"},{"text":">","kind":"text"}],"abstract":[],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SdkInformation":{"role":"symbol","kind":"symbol","type":"topic","title":"SdkInformation","abstract":[{"type":"text","text":"Provides information about a given Mapbox SDK. This information is then used to populate the “User-Agent” HTTP header"},{"type":"text","text":" "},{"type":"text","text":"of HTTP requests generated from within Mapbox SDKs. Mapbox SDKs include Maps, Navigation, Search, and others."}],"url":"\/documentation\/mapboxcommon\/sdkinformation","navigatorTitle":[{"text":"SdkInformation","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SdkInformation","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SdkInformation"},"doc://com.mapbox.MapboxMaps/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH"},"doc://com.mapbox.MapboxMaps/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsServiceStorageType":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceStorageType","url":"\/documentation\/mapboxcommon\/settingsservicestoragetype","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SettingsServiceStorageType"}],"abstract":[{"type":"text","text":"Enum that contains possible storage types that can be used for settings service."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SettingsServiceStorageType"}],"title":"SettingsServiceStorageType","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsService/get(key:type:)":{"url":"\/documentation\/mapboxcommon\/settingsservice\/get(key:type:)","abstract":[],"title":"get(key:type:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"get"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"T"},{"kind":"text","text":">("},{"kind":"externalParam","text":"key"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"T"},{"kind":"text","text":".Type) -> "},{"preciseIdentifier":"s:s6ResultO","kind":"typeIdentifier","text":"Result"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"T"},{"kind":"text","text":", "},{"preciseIdentifier":"s:12MapboxCommon20SettingsServiceErrorV","kind":"typeIdentifier","text":"SettingsServiceError"},{"kind":"text","text":">"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsService\/get(key:type:)","kind":"symbol","type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"},"doc://com.mapbox.MapboxMaps/SQ":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsServiceError":{"title":"SettingsServiceError","role":"symbol","abstract":[{"type":"text","text":"Structure for keeping an information about errors that can happen when using Settings service"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceError","url":"\/documentation\/mapboxcommon\/settingsserviceerror","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SettingsServiceError","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"SettingsServiceError","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsService":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsService","role":"symbol","navigatorTitle":[{"text":"SettingsService","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Platform independent settings service. Settings service is a key\/value storage (persistent or non"},{"type":"text","text":" "},{"type":"text","text":"persistent), that also allows to register observers to get notifications when values are updated."}],"url":"\/documentation\/mapboxcommon\/settingsservice","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SettingsService","kind":"identifier"}],"title":"SettingsService","type":"topic"},"doc://com.mapbox.MapboxMaps/s7CVarArgP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Settings-and-Constants":{"abstract":[],"role":"collectionGroup","url":"\/documentation\/mapboxmaps\/settings-and-constants","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Settings-and-Constants","kind":"article","title":"Settings and Constants"},"doc://com.mapbox.MapboxMaps/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsService/erase(key:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"erase"},{"kind":"text","text":"("},{"kind":"externalParam","text":"key"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"SettingsServiceError","preciseIdentifier":"s:12MapboxCommon20SettingsServiceErrorV"},{"kind":"text","text":">"}],"title":"erase(key:)","type":"topic","kind":"symbol","url":"\/documentation\/mapboxcommon\/settingsservice\/erase(key:)","abstract":[],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsService\/erase(key:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsService/has(key:)":{"kind":"symbol","abstract":[],"type":"topic","url":"\/documentation\/mapboxcommon\/settingsservice\/has(key:)","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsService\/has(key:)","title":"has(key:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"has"},{"kind":"text","text":"("},{"kind":"externalParam","text":"key"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s6ResultO","kind":"typeIdentifier","text":"Result"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"preciseIdentifier":"s:12MapboxCommon20SettingsServiceErrorV","kind":"typeIdentifier","text":"SettingsServiceError"},{"kind":"text","text":">"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsServiceFactory":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SettingsServiceFactory","kind":"identifier"}],"navigatorTitle":[{"text":"SettingsServiceFactory","kind":"identifier"}],"abstract":[{"type":"text","text":"Factory that allows to create settings service instance."}],"role":"symbol","url":"\/documentation\/mapboxcommon\/settingsservicefactory","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceFactory","kind":"symbol","title":"SettingsServiceFactory"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"kind":"article","role":"collection","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsService/set(key:value:)":{"url":"\/documentation\/mapboxcommon\/settingsservice\/set(key:value:)","title":"set(key:value:)","kind":"symbol","type":"topic","role":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"identifier"},{"text":"<","kind":"text"},{"text":"T","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"key","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"T","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"text":"<","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":", ","kind":"text"},{"text":"SettingsServiceError","kind":"typeIdentifier","preciseIdentifier":"s:12MapboxCommon20SettingsServiceErrorV"},{"text":">","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsService\/set(key:value:)"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"MBXSettingsService","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"MBXSettingsService","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"MBXSettingsService","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":null,"path":"\/topicSections","op":"replace"},{"value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"}],"path":"\/relationshipsSections","op":"replace"},{"value":[{"title":"Common Settings","generated":true,"anchor":"Common-Settings","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceFactory","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceStorageType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SdkInformation"]}],"path":"\/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBXSettingsService","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"MBXSdkInformation","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SdkInformation\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MBXSdkInformation"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SdkInformation\/fragments"},{"value":[{"text":"MBXSdkInformation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SdkInformation\/navigatorTitle"},{"value":"MBXSettingsServiceStorageType","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceStorageType\/title"},{"value":[{"text":"MBXSettingsServiceStorageType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceStorageType\/fragments"},{"value":[{"text":"MBXSettingsServiceStorageType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceStorageType\/navigatorTitle"},{"value":"MBXSettingsService","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsService\/title"},{"value":[{"kind":"identifier","text":"MBXSettingsService"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsService\/fragments"},{"value":[{"text":"MBXSettingsService","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsService\/navigatorTitle"},{"value":"MBXSettingsServiceFactory","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceFactory\/title"},{"value":[{"kind":"identifier","text":"MBXSettingsServiceFactory"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceFactory\/fragments"},{"value":[{"text":"MBXSettingsServiceFactory","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceFactory\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}