{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudget\/isTileCacheBudgetInTiles()"},"metadata":{"roleHeading":"Instance Method","modules":[{"name":"MapboxMaps"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isTileCacheBudgetInTiles"}],"title":"isTileCacheBudgetInTiles()","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isTileCacheBudgetInTiles"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"externalID":"c:objc(cs)MBMTileCacheBudget(im)isTileCacheBudgetInTiles"},"sections":[],"variants":[{"paths":["\/documentation\/mapboxmaps\/tilecachebudget\/istilecachebudgetintiles()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/tilecachebudget\/istilecachebudgetintiles()"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isTileCacheBudgetInTiles","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudget"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"url":"\/documentation\/mapboxmaps\/tilestore-apis","title":"TileStore APIs","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","kind":"article","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","title":"MapboxMaps","kind":"symbol","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudget":{"navigatorTitle":[{"text":"TileCacheBudget","kind":"identifier"}],"kind":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TileCacheBudget","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxmaps\/tilecachebudget","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudget","role":"symbol","title":"TileCacheBudget"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudget/isTileCacheBudgetInTiles()":{"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudget\/isTileCacheBudgetInTiles()","type":"topic","role":"symbol","navigatorTitle":[{"text":"isTileCacheBudgetInTiles","kind":"identifier"}],"title":"isTileCacheBudgetInTiles()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isTileCacheBudgetInTiles","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/tilecachebudget\/istilecachebudgetintiles()"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","type":"topic","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","abstract":[],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"isTileCacheBudgetInTiles","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isTileCacheBudgetInTiles"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"text":"isTileCacheBudgetInTiles","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"value":"MBMTileCacheBudget","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudget\/title"},{"op":"replace","value":[{"text":"MBMTileCacheBudget","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudget\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudget\/navigatorTitle","op":"replace","value":[{"text":"MBMTileCacheBudget","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudget~1isTileCacheBudgetInTiles()\/title","value":"isTileCacheBudgetInTiles","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudget~1isTileCacheBudgetInTiles()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isTileCacheBudgetInTiles"}]}]}]}