{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapSnapshotOptions\/init(size:pixelRatio:glyphsRasterizationOptions:showsLogo:showsAttribution:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"size","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pixelRatio"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"glyphsRasterizationOptions"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationOptions","preciseIdentifier":"c:objc(cs)MBMGlyphsRasterizationOptions","text":"GlyphsRasterizationOptions"},{"text":" = GlyphsRasterizationOptions(), ","kind":"text"},{"kind":"externalParam","text":"showsLogo"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = true, "},{"text":"showsAttribution","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":" = true)","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"size","content":[{"inlineContent":[{"text":"Dimensions of the snapshot in points","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Ratio of device-independent and screen pixels."}],"type":"paragraph"}],"name":"pixelRatio"},{"content":[{"inlineContent":[{"type":"text","text":"Glyphs rasterization options to use for"},{"type":"text","text":" "},{"text":"client-side text rendering. Default mode is","type":"text"},{"text":" ","type":"text"},{"code":".ideographsRasterizedLocally","type":"codeVoice"}],"type":"paragraph"}],"name":"glyphsRasterizationOptions"},{"content":[{"inlineContent":[{"type":"text","text":"Flag that determines if the logo should be shown on the snapshot"}],"type":"paragraph"}],"name":"showsLogo"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Flag that determines if attribution should be shown on the snapshot"}]}],"name":"showsAttribution"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapSnapshotOptions"]]},"metadata":{"role":"symbol","modules":[{"name":"MapboxMaps"}],"title":"init(size:pixelRatio:glyphsRasterizationOptions:showsLogo:showsAttribution:)","externalID":"s:10MapboxMaps18MapSnapshotOptionsV4size10pixelRatio019glyphsRasterizationE09showsLogo0K11AttributionACSo6CGSizeV_14CoreFoundation7CGFloatVSo09MBMGlyphsjE0CS2btcfc","symbolKind":"init","roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"size","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"pixelRatio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"glyphsRasterizationOptions"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMGlyphsRasterizationOptions","text":"GlyphsRasterizationOptions","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"showsLogo"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"text":"showsAttribution","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"sections":[],"kind":"symbol","abstract":[{"text":"Initializes a ","type":"text"},{"code":"MapSnapshotOptions","type":"codeVoice"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/mapsnapshotoptions\/init(size:pixelratio:glyphsrasterizationoptions:showslogo:showsattribution:)"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapSnapshotOptions":{"title":"MapSnapshotOptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapSnapshotOptions","navigatorTitle":[{"kind":"identifier","text":"MapSnapshotOptions"}],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapSnapshotOptions","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/mapsnapshotoptions","abstract":[{"type":"text","text":"Set of options for taking map snapshot with Snapshotter."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GlyphsRasterizationOptions":{"abstract":[{"text":"Describes the glyphs rasterization option values.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GlyphsRasterizationOptions"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationOptions","title":"GlyphsRasterizationOptions","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GlyphsRasterizationOptions","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/glyphsrasterizationoptions"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","url":"\/documentation\/overview","abstract":[],"type":"topic","role":"collection","title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Snapshotter-APIs":{"title":"Snapshotter","abstract":[],"url":"\/documentation\/mapboxmaps\/snapshotter-apis","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter-APIs","role":"collectionGroup","type":"topic","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapSnapshotOptions/init(size:pixelRatio:glyphsRasterizationOptions:showsLogo:showsAttribution:)":{"abstract":[{"type":"text","text":"Initializes a "},{"code":"MapSnapshotOptions","type":"codeVoice"}],"type":"topic","url":"\/documentation\/mapboxmaps\/mapsnapshotoptions\/init(size:pixelratio:glyphsrasterizationoptions:showslogo:showsattribution:)","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapSnapshotOptions\/init(size:pixelRatio:glyphsRasterizationOptions:showsLogo:showsAttribution:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"size","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"text":", ","kind":"text"},{"text":"pixelRatio","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"text":"glyphsRasterizationOptions","kind":"externalParam"},{"kind":"text","text":": "},{"text":"GlyphsRasterizationOptions","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMGlyphsRasterizationOptions"},{"kind":"text","text":", "},{"text":"showsLogo","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"text":"showsAttribution","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"title":"init(size:pixelRatio:glyphsRasterizationOptions:showsLogo:showsAttribution:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MBMGlyphsRasterizationOptions","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationOptions\/title"},{"op":"replace","value":[{"text":"MBMGlyphsRasterizationOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationOptions\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationOptions\/navigatorTitle","value":[{"text":"MBMGlyphsRasterizationOptions","kind":"identifier"}],"op":"replace"}]}]}