{"abstract":[{"type":"text","text":"Reset logging level for category to default logging level."}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogConfiguration\/resetLoggingLevel(forCategory:)","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Type Method","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"resetLoggingLevel","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forCategory"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"externalID":"c:objc(cs)MBXLogConfiguration(cm)resetLoggingLevelForCategory:","modules":[{"name":"MapboxCommon"}],"symbolKind":"method","title":"resetLoggingLevel(forCategory:)","navigatorTitle":[{"kind":"identifier","text":"resetLoggingLevelForCategory:"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"resetLoggingLevel","kind":"identifier"},{"kind":"text","text":"("},{"text":"forCategory","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"category"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Category that can be used for filtering."}]}],"name":"category"}],"kind":"parameters"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogConfiguration"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/logconfiguration\/resetlogginglevel(forcategory:)"]},{"paths":["\/documentation\/mapboxcommon\/logconfiguration\/resetlogginglevel(forcategory:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LogConfiguration":{"title":"LogConfiguration","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"LogConfiguration"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LogConfiguration"}],"url":"\/documentation\/mapboxcommon\/logconfiguration","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogConfiguration","abstract":[{"type":"text","text":"Class that allows to configure Mapbox SDKs logging per application."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"title":"MapboxMaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","kind":"article","role":"collection","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LogConfiguration/resetLoggingLevel(forCategory:)":{"abstract":[{"type":"text","text":"Reset logging level for category to default logging level."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogConfiguration\/resetLoggingLevel(forCategory:)","navigatorTitle":[{"kind":"identifier","text":"resetLoggingLevelForCategory:"}],"url":"\/documentation\/mapboxcommon\/logconfiguration\/resetlogginglevel(forcategory:)","title":"resetLoggingLevel(forCategory:)","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"resetLoggingLevel","kind":"identifier"},{"kind":"text","text":"("},{"text":"forCategory","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Performance":{"type":"topic","title":"Performance and investigations","abstract":[],"role":"collectionGroup","kind":"article","url":"\/documentation\/mapboxmaps\/performance","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"value":"resetLoggingLevelForCategory:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"resetLoggingLevelForCategory:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"resetLoggingLevelForCategory:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"category","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"name":"category","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Category that can be used for filtering."}]}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"MBXLogConfiguration","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogConfiguration\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXLogConfiguration"}]},{"op":"replace","value":[{"kind":"identifier","text":"MBXLogConfiguration"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogConfiguration\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogConfiguration~1resetLoggingLevel(forCategory:)\/title","op":"replace","value":"resetLoggingLevelForCategory:"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"resetLoggingLevelForCategory:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogConfiguration~1resetLoggingLevel(forCategory:)\/fragments"}]}]}