{"sections":[],"variants":[{"paths":["\/documentation\/mapboxcommon\/httpserviceinterceptorinterface\/onresponse(for:continuation:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxcommon\/httpserviceinterceptorinterface\/onresponse(for:continuation:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onResponse","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"response"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBXHttpResponse","text":"HttpResponse","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpResponse","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"continuation"},{"kind":"text","text":": "},{"text":"@escaping","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:MBXHttpServiceInterceptorResponseContinuation.h@T@MBXHttpServiceInterceptorResponseContinuation","text":"HttpServiceInterceptorResponseContinuation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceInterceptorResponseContinuation"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"response","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The original HttpResponse object to be modified. Note: certain requests have their response body"},{"type":"text","text":" "},{"text":"written to disk. In that case, the field HttpResponseData.body will be empty.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Callback to be invoked once the interceptor has finished processing the response."}]}],"name":"continuation"}]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceInterceptorInterface\/onResponse(for:continuation:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","abstract":[{"text":"The function to intercept HTTP responses with.","type":"text"}],"metadata":{"title":"onResponse(for:continuation:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onResponse","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"HttpResponse","preciseIdentifier":"c:objc(cs)MBXHttpResponse"},{"kind":"text","text":", "},{"kind":"externalParam","text":"continuation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:MBXHttpServiceInterceptorResponseContinuation.h@T@MBXHttpServiceInterceptorResponseContinuation","text":"HttpServiceInterceptorResponseContinuation"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"onResponseForResponse:continuation:","kind":"identifier"}],"modules":[{"name":"MapboxCommon"}],"externalID":"c:objc(pl)MBXHttpServiceInterceptorInterface(im)onResponseForResponse:continuation:","roleHeading":"Instance Method","role":"symbol","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceInterceptorInterface"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpServiceInterceptorInterface/onResponse(for:continuation:)":{"kind":"symbol","type":"topic","required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onResponse"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"text":"HttpResponse","preciseIdentifier":"c:objc(cs)MBXHttpResponse","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"continuation"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:MBXHttpServiceInterceptorResponseContinuation.h@T@MBXHttpServiceInterceptorResponseContinuation","text":"HttpServiceInterceptorResponseContinuation"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"The function to intercept HTTP responses with."}],"url":"\/documentation\/mapboxcommon\/httpserviceinterceptorinterface\/onresponse(for:continuation:)","title":"onResponse(for:continuation:)","navigatorTitle":[{"kind":"identifier","text":"onResponseForResponse:continuation:"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceInterceptorInterface\/onResponse(for:continuation:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpResponse":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpResponse","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"HttpResponse"}],"navigatorTitle":[{"text":"HttpResponse","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/httpresponse","title":"HttpResponse","abstract":[{"type":"text","text":"Record which is used to report HTTP response to the caller."}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpServiceInterceptorResponseContinuation":{"kind":"symbol","title":"HttpServiceInterceptorResponseContinuation","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"HttpServiceInterceptorResponseContinuation"}],"abstract":[{"text":"Continuation to be invoked once the interceptor is done processing a request’s response.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"HttpServiceInterceptorResponseContinuation"}],"url":"\/documentation\/mapboxcommon\/httpserviceinterceptorresponsecontinuation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceInterceptorResponseContinuation","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","title":"MapboxCommon","kind":"symbol","role":"collection","url":"\/documentation\/mapboxcommon","type":"topic","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"kind":"article","url":"\/documentation\/overview","role":"collection","title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpServiceInterceptorInterface":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HttpServiceInterceptorInterface","kind":"identifier"}],"type":"topic","abstract":[{"text":"Interface for intercepting and modifying HttpService function calls.","type":"text"}],"kind":"symbol","role":"symbol","title":"HttpServiceInterceptorInterface","navigatorTitle":[{"text":"HttpServiceInterceptorInterface","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceInterceptorInterface","url":"\/documentation\/mapboxcommon\/httpserviceinterceptorinterface"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"onResponseForResponse:continuation:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"onResponseForResponse:continuation:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"onResponseForResponse:"},{"text":"(","kind":"text"},{"text":"MBXHttpResponse","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpResponse","preciseIdentifier":"c:objc(cs)MBXHttpResponse","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"response","kind":"internalParam"},{"kind":"text","text":" "},{"text":"continuation:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$objc(cs)MBXHttpResponse)","text":"void (^)(MBXHttpResponse *)"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"continuation"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"name":"response","content":[{"inlineContent":[{"type":"text","text":"The original HttpResponse object to be modified. Note: certain requests have their response body"},{"type":"text","text":" "},{"type":"text","text":"written to disk. In that case, the field HttpResponseData.body will be empty."}],"type":"paragraph"}]},{"name":"continuation","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Callback to be invoked once the interceptor has finished processing the response."}]}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"onResponseForResponse:continuation:","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceInterceptorInterface~1onResponse(for:continuation:)\/title","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"onResponseForResponse:continuation:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceInterceptorInterface~1onResponse(for:continuation:)\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpResponse\/title","value":"MBXHttpResponse","op":"replace"},{"value":[{"text":"MBXHttpResponse","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpResponse\/fragments","op":"replace"},{"value":[{"text":"MBXHttpResponse","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpResponse\/navigatorTitle"},{"value":"MBXHttpServiceInterceptorResponseContinuation","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceInterceptorResponseContinuation\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBXHttpServiceInterceptorResponseContinuation"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceInterceptorResponseContinuation\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceInterceptorResponseContinuation\/navigatorTitle","value":[{"text":"MBXHttpServiceInterceptorResponseContinuation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceInterceptorInterface\/title","value":"MBXHttpServiceInterceptorInterface"},{"value":[{"kind":"identifier","text":"MBXHttpServiceInterceptorInterface"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceInterceptorInterface\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceInterceptorInterface\/navigatorTitle","value":[{"text":"MBXHttpServiceInterceptorInterface","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}