{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location\/init(CLLocation:extra:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"CLLocation"},{"text":" ","kind":"text"},{"text":"location","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)CLLocation","text":"CLLocation","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"extra","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"platforms":["iOS"]},{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"clLocation"},{"text":" ","kind":"text"},{"text":"location","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)CLLocation","kind":"typeIdentifier","text":"CLLocation"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"extra"},{"text":": ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location"]]},"metadata":{"role":"symbol","roleHeading":"Initializer","modules":[{"name":"MapboxCommon"}],"externalID":"c:objc(cs)MBXLocation(im)initWithCLLocation:extra:","title":"init(CLLocation:extra:)","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"CLLocation","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CLLocation","preciseIdentifier":"c:objc(cs)CLLocation","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"extra"},{"text":": ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"initWithCLLocation:extra:","kind":"identifier"}],"extendedModule":"MapboxCommon","platforms":[]},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/location\/init(cllocation:extra:)"]},{"paths":["\/documentation\/mapboxcommon\/location\/init(cllocation:extra:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","title":"MapboxMaps","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Location/init(CLLocation:extra:)":{"title":"init(CLLocation:extra:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"CLLocation","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CLLocation","text":"CLLocation"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"extra"},{"text":": ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"initWithCLLocation:extra:","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/mapboxcommon\/location\/init(cllocation:extra:)","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location\/init(CLLocation:extra:)","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Location":{"type":"topic","title":"Location","abstract":[{"text":"Location information.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Location"}],"navigatorTitle":[{"text":"Location","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapboxcommon\/location","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Location-APIs":{"title":"Location","url":"\/documentation\/mapboxmaps\/location-apis","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","kind":"article","type":"topic","role":"collectionGroup","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","url":"\/documentation\/overview","title":"MapboxMaps Documentation","abstract":[],"kind":"article","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"initWithCLLocation:extra:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithCLLocation:extra:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"text":") ","kind":"text"},{"text":"initWithCLLocation:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)CLLocation","kind":"typeIdentifier","text":"CLLocation"},{"kind":"text","text":" *) "},{"text":"location","kind":"internalParam"},{"kind":"text","text":" "},{"text":"extra:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"extra","kind":"internalParam"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location~1init(CLLocation:extra:)\/title","value":"initWithCLLocation:extra:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCLLocation:extra:"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location~1init(CLLocation:extra:)\/fragments"},{"op":"replace","value":"MBXLocation","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/fragments","value":[{"text":"MBXLocation","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/navigatorTitle","value":[{"text":"MBXLocation","kind":"identifier"}]}]}]}