{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-View","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapOptions"]]},"variants":[{"paths":["\/documentation\/mapboxmaps\/mbmmapoptions\/orientation"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":" * ","kind":"text"},{"text":"orientation","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"sections":[],"abstract":[{"text":"The orientation of the Map. By default, it is set to","type":"text"},{"text":" ","type":"text"},{"code":"Upwards","type":"codeVoice"},{"text":".","type":"text"}],"metadata":{"symbolKind":"property","role":"symbol","modules":[{"name":"MapboxMaps"}],"roleHeading":"Instance Property","title":"orientation","navigatorTitle":[{"kind":"identifier","text":"orientation"}],"fragments":[{"kind":"identifier","text":"orientation"}],"externalID":"c:objc(cs)MBMMapOptions(py)orientation"},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapOptions\/orientation","interfaceLanguage":"occ"},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMMapOptions/orientation":{"abstract":[{"type":"text","text":"The orientation of the Map. By default, it is set to"},{"type":"text","text":" "},{"code":"Upwards","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapOptions\/orientation","title":"orientation","type":"topic","kind":"symbol","fragments":[{"kind":"identifier","text":"orientation"}],"url":"\/documentation\/mapboxmaps\/mbmmapoptions\/orientation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapOptions":{"url":"\/documentation\/mapboxmaps\/mapoptions","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapOptions","kind":"identifier"}],"title":"MapOptions","navigatorTitle":[{"text":"MapOptions","kind":"identifier"}],"abstract":[{"text":"Describes the map option values.","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"url":"\/documentation\/mapboxmaps","title":"MapboxMaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article","type":"topic","title":"MapboxMaps Documentation","abstract":[],"url":"\/documentation\/overview","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map-View":{"abstract":[],"role":"collectionGroup","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-View","url":"\/documentation\/mapboxmaps\/map-view","title":"MapView","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MBMMapOptions","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapOptions\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBMMapOptions"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapOptions\/fragments"},{"op":"replace","value":[{"text":"MBMMapOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapOptions\/navigatorTitle"}]}]}