{"kind":"article","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode\/Equatable-Implementations"},"metadata":{"roleHeading":"API Collection","role":"collectionGroup","title":"Equatable Implementations","modules":[{"name":"MapboxCommon"},{"name":"MapboxMaps"}]},"topicSections":[{"generated":true,"title":"Operators","anchor":"Operators","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode\/!=(_:_:)"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Location-APIs":{"kind":"article","url":"\/documentation\/mapboxmaps\/location-apis","role":"collectionGroup","title":"Location","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationErrorCode":{"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LocationErrorCode"}],"abstract":[{"text":"Codes of location errors.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"LocationErrorCode"}],"kind":"symbol","url":"\/documentation\/mapboxcommon\/locationerrorcode","title":"LocationErrorCode","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationErrorCode/!=(_:_:)":{"role":"symbol","title":"!=(_:_:)","url":"\/documentation\/mapboxcommon\/locationerrorcode\/!=(_:_:)","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode\/!=(_:_:)","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","abstract":[],"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","kind":"article","role":"collection"}},"variantOverrides":[{"patch":[{"value":"MBXLocationErrorCode","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/title"},{"value":[{"kind":"identifier","text":"MBXLocationErrorCode"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/fragments"},{"value":[{"text":"MBXLocationErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}