{"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/subscript(_:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/mapboxmaps\/mapboxmap\/subscript(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap"]]},"abstract":[{"type":"text","text":"Returns a "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Signal","isActive":true,"type":"reference"},{"type":"text","text":" that allows to subscribe to the event with specified string name."},{"type":"text","text":" "},{"text":"This method is reserved for the future use.","type":"text"}],"metadata":{"roleHeading":"Instance Subscript","externalID":"s:10MapboxMaps0A3MapCyAA6SignalVySo15MBMGenericEventCGSScip","extendedModule":"MapboxMaps","title":"subscript(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"subscript"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Signal","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"kind":"text","text":"<"},{"text":"GenericEvent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMGenericEvent"},{"text":">","kind":"text"}],"symbolKind":"subscript","tags":[{"type":"spi","text":"SPI"}],"modules":[{"name":"MapboxMaps"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"subscript"},{"text":"(","kind":"text"},{"text":"eventName","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Signal","text":"Signal","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"text":"<","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GenericEvent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMGenericEvent","text":"GenericEvent"},{"text":"> { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Signal":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Signal","kind":"identifier"}],"type":"topic","title":"Signal","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"Signal","kind":"identifier"}],"abstract":[{"type":"text","text":"Signal is a typed interface for observing arbitrary values over time."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Signal","url":"\/documentation\/mapboxmaps\/signal"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"abstract":[],"role":"collectionGroup","title":"MapboxMap","url":"\/documentation\/mapboxmaps\/mapboxmap-apis","kind":"article","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article","role":"collection","type":"topic","abstract":[],"url":"\/documentation\/overview","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/subscript(_:)":{"url":"\/documentation\/mapboxmaps\/mapboxmap\/subscript(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/subscript(_:)","tags":[{"text":"SPI","type":"spi"}],"abstract":[{"text":"Returns a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Signal","isActive":true},{"text":" that allows to subscribe to the event with specified string name.","type":"text"},{"type":"text","text":" "},{"text":"This method is reserved for the future use.","type":"text"}],"fragments":[{"text":"subscript","kind":"keyword"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Signal","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMGenericEvent","text":"GenericEvent"},{"kind":"text","text":">"}],"kind":"symbol","role":"symbol","title":"subscript(_:)","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","role":"symbol","abstract":[{"text":"Provides access to the map model, including the camera, style, observable map events,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"and querying rendered features."}],"title":"MapboxMap","navigatorTitle":[{"text":"MapboxMap","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapboxMap"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","title":"MapboxMaps","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GenericEvent":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GenericEvent","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GenericEvent"}],"navigatorTitle":[{"kind":"identifier","text":"GenericEvent"}],"abstract":[{"text":"The generic event type.","type":"text"}],"url":"\/documentation\/mapboxmaps\/genericevent","role":"symbol","title":"GenericEvent"}},"variantOverrides":[{"patch":[{"value":"MBMGenericEvent","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEvent\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEvent\/fragments","value":[{"text":"MBMGenericEvent","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEvent\/navigatorTitle","value":[{"text":"MBMGenericEvent","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}