{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"kind"}],"role":"symbol","externalID":"c:objc(cs)MBMStylePropertyValue(py)kind","symbolKind":"property","roleHeading":"Instance Property","title":"kind","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"kind","kind":"identifier"},{"text":": ","kind":"text"},{"text":"StylePropertyValueKind","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMStylePropertyValueKind"}],"modules":[{"name":"MapboxMaps"}]},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStylePropertyValue\/kind","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/mapboxmaps\/mbmstylepropertyvalue\/kind"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/mbmstylepropertyvalue\/kind"]}],"kind":"symbol","abstract":[{"type":"text","text":"The kind of the property value."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kind","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValueKind","preciseIdentifier":"c:@E@MBMStylePropertyValueKind","kind":"typeIdentifier","text":"StylePropertyValueKind"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer-Property-Values","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValue"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMStylePropertyValue/kind":{"url":"\/documentation\/mapboxmaps\/mbmstylepropertyvalue\/kind","type":"topic","title":"kind","abstract":[{"text":"The kind of the property value.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStylePropertyValue\/kind","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"kind","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@MBMStylePropertyValueKind","text":"StylePropertyValueKind","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"kind","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePropertyValue":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"StylePropertyValue","kind":"identifier"}],"abstract":[{"text":"Holds a style property value with meta data.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValue","navigatorTitle":[{"text":"StylePropertyValue","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/stylepropertyvalue","type":"topic","title":"StylePropertyValue","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePropertyValueKind":{"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StylePropertyValueKind"}],"abstract":[{"type":"text","text":"Describes the kind of a style property value."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValueKind","navigatorTitle":[{"kind":"identifier","text":"StylePropertyValueKind"}],"url":"\/documentation\/mapboxmaps\/stylepropertyvaluekind","type":"topic","title":"StylePropertyValueKind","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layer-Property-Values":{"type":"topic","url":"\/documentation\/mapboxmaps\/layer-property-values","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer-Property-Values","kind":"article","title":"Layer Property Values","role":"collectionGroup","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"kind","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"kind"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"MBMStylePropertyValueKind","preciseIdentifier":"c:@E@MBMStylePropertyValueKind","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValueKind"},{"kind":"text","text":" "},{"kind":"identifier","text":"kind"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","value":"kind","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMStylePropertyValue~1kind\/title"},{"op":"replace","value":[{"kind":"identifier","text":"kind"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMStylePropertyValue~1kind\/fragments"},{"value":"MBMStylePropertyValue","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValue\/title"},{"value":[{"text":"MBMStylePropertyValue","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValue\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValueKind\/title","value":"MBMStylePropertyValueKind","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValueKind\/fragments","value":[{"kind":"identifier","text":"MBMStylePropertyValueKind"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}