{"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"shadowMapDurationStatistics"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/DurationStatistics","preciseIdentifier":"c:objc(cs)MBMDurationStatistics","kind":"typeIdentifier","text":"DurationStatistics"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"The CPU timeline duration of the shadowmap render pass."}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerFrameRenderingStatistics\/shadowMapDurationStatistics"},"variants":[{"paths":["\/documentation\/mapboxmaps\/perframerenderingstatistics\/shadowmapdurationstatistics"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/perframerenderingstatistics\/shadowmapdurationstatistics"]}],"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shadowMapDurationStatistics"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMDurationStatistics","text":"DurationStatistics"}],"roleHeading":"Instance Property","role":"symbol","externalID":"c:objc(cs)MBMPerFrameRenderingStatistics(py)shadowMapDurationStatistics","symbolKind":"property","title":"shadowMapDurationStatistics","modules":[{"name":"MapboxMaps"}],"navigatorTitle":[{"kind":"identifier","text":"shadowMapDurationStatistics"}]},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerFrameRenderingStatistics"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"title":"MapboxMaps Documentation","role":"collection","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PerFrameRenderingStatistics":{"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PerFrameRenderingStatistics","kind":"identifier"}],"navigatorTitle":[{"text":"PerFrameRenderingStatistics","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/perframerenderingstatistics","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerFrameRenderingStatistics","type":"topic","title":"PerFrameRenderingStatistics","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Performance":{"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","title":"Performance and investigations","abstract":[],"type":"topic","url":"\/documentation\/mapboxmaps\/performance","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/DurationStatistics":{"url":"\/documentation\/mapboxmaps\/durationstatistics","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DurationStatistics","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/DurationStatistics","title":"DurationStatistics","navigatorTitle":[{"text":"DurationStatistics","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PerFrameRenderingStatistics/shadowMapDurationStatistics":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"shadowMapDurationStatistics","kind":"identifier"},{"kind":"text","text":": "},{"text":"DurationStatistics","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMDurationStatistics"}],"role":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/perframerenderingstatistics\/shadowmapdurationstatistics","title":"shadowMapDurationStatistics","navigatorTitle":[{"kind":"identifier","text":"shadowMapDurationStatistics"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerFrameRenderingStatistics\/shadowMapDurationStatistics","kind":"symbol","abstract":[{"type":"text","text":"The CPU timeline duration of the shadowmap render pass."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","title":"MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"url":"\/documentation\/mapboxmaps","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"shadowMapDurationStatistics"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"shadowMapDurationStatistics"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/DurationStatistics","preciseIdentifier":"c:objc(cs)MBMDurationStatistics","kind":"typeIdentifier","text":"MBMDurationStatistics"},{"kind":"text","text":" * "},{"kind":"identifier","text":"shadowMapDurationStatistics"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerFrameRenderingStatistics\/title","value":"MBMPerFrameRenderingStatistics"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerFrameRenderingStatistics\/fragments","value":[{"text":"MBMPerFrameRenderingStatistics","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerFrameRenderingStatistics\/navigatorTitle","value":[{"text":"MBMPerFrameRenderingStatistics","kind":"identifier"}]},{"value":"MBMDurationStatistics","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1DurationStatistics\/title"},{"value":[{"text":"MBMDurationStatistics","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1DurationStatistics\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1DurationStatistics\/navigatorTitle","value":[{"text":"MBMDurationStatistics","kind":"identifier"}]},{"op":"replace","value":"shadowMapDurationStatistics","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerFrameRenderingStatistics~1shadowMapDurationStatistics\/title"},{"op":"replace","value":[{"kind":"identifier","text":"shadowMapDurationStatistics"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerFrameRenderingStatistics~1shadowMapDurationStatistics\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}