{"kind":"symbol","relationshipsSections":[{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH"],"title":"Conforms To"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraBoundsOptions"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBoundsOptions","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"MapboxMaps"}],"role":"symbol","roleHeading":"Structure","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraBoundsOptions"}],"navigatorTitle":[{"kind":"identifier","text":"CameraBoundsOptions"}],"symbolKind":"struct","externalID":"s:10MapboxMaps19CameraBoundsOptionsV","title":"CameraBoundsOptions"},"topicSections":[{"anchor":"Operators","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBoundsOptions\/==(_:_:)"],"title":"Operators"},{"anchor":"Initializers","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBoundsOptions\/init(bounds:maxZoom:minZoom:maxPitch:minPitch:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBoundsOptions\/init(cameraBounds:)"],"title":"Initializers"},{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBoundsOptions\/bounds","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBoundsOptions\/maxPitch","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBoundsOptions\/maxZoom","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBoundsOptions\/minPitch","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBoundsOptions\/minZoom"],"title":"Instance Properties"},{"anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBoundsOptions\/hash(into:)"],"title":"Instance Methods"},{"anchor":"Default-Implementations","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBoundsOptions\/Equatable-Implementations"],"title":"Default Implementations"}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Holds options to be used for setting camera bounds."}],"seeAlsoSections":[{"anchor":"MapboxMap","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraState","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBounds","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Projection","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBoundsZoom","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateInfo","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ContextMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapCenterAltitudeMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometry","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometryConvertible"],"title":"MapboxMap"}],"variants":[{"paths":["\/documentation\/mapboxmaps\/cameraboundsoptions"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderedQueryGeometryConvertible":{"navigatorTitle":[{"kind":"identifier","text":"RenderedQueryGeometryConvertible"}],"url":"\/documentation\/mapboxmaps\/renderedquerygeometryconvertible","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometryConvertible","abstract":[{"type":"text","text":"A convenience protocol for automatic conversion to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometry"},{"type":"text","text":"."}],"title":"RenderedQueryGeometryConvertible","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RenderedQueryGeometryConvertible"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraBoundsOptions/minPitch":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBoundsOptions\/minPitch","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"minPitch"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"kind":"text","text":"?"}],"url":"\/documentation\/mapboxmaps\/cameraboundsoptions\/minpitch","type":"topic","abstract":[{"text":"The minimum allowed pitch value degrees.","type":"text"},{"text":" ","type":"text"},{"text":"Defaults to 0.","type":"text"}],"role":"symbol","kind":"symbol","title":"minPitch"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","role":"collection","type":"topic","abstract":[],"title":"MapboxMaps Documentation","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ContextMode":{"title":"ContextMode","url":"\/documentation\/mapboxmaps\/contextmode","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ContextMode","type":"topic","abstract":[{"type":"text","text":"Describes the map context mode."},{"type":"text","text":" "},{"type":"text","text":"We can make some optimizations if we know that the drawing context is not shared with other code."}],"role":"symbol","navigatorTitle":[{"text":"ContextMode","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContextMode","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Projection":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Projection","navigatorTitle":[{"text":"Projection","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Projection","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"Projection","url":"\/documentation\/mapboxmaps\/projection","abstract":[{"type":"text","text":"A collection of "},{"identifier":"https:\/\/en.wikipedia.org\/wiki\/Web_Mercator_projection","isActive":true,"type":"reference"},{"type":"text","text":" projection methods."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraBoundsOptions/bounds":{"title":"bounds","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBoundsOptions\/bounds","type":"topic","url":"\/documentation\/mapboxmaps\/cameraboundsoptions\/bounds","abstract":[{"text":"The latitude and longitude bounds to which the camera center is constrained.","type":"text"},{"text":" ","type":"text"},{"text":"Defaults to: Southwest: (-90, -180) and Northeast: (90, 180).","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bounds"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMCoordinateBounds","text":"CoordinateBounds"},{"kind":"text","text":"?"}],"kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapCenterAltitudeMode":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapCenterAltitudeMode"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/mapcenteraltitudemode","abstract":[{"type":"text","text":"Defines how the map center point should react to terrain elevation changes."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapCenterAltitudeMode","title":"MapCenterAltitudeMode","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MapCenterAltitudeMode"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraBoundsOptions":{"navigatorTitle":[{"text":"CameraBoundsOptions","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraBoundsOptions","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"text":"Holds options to be used for setting camera bounds.","type":"text"}],"title":"CameraBoundsOptions","role":"symbol","url":"\/documentation\/mapboxmaps\/cameraboundsoptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBoundsOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraBoundsOptions/Equatable-Implementations":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBoundsOptions\/Equatable-Implementations","role":"collectionGroup","kind":"article","type":"topic","abstract":[],"url":"\/documentation\/mapboxmaps\/cameraboundsoptions\/equatable-implementations","title":"Equatable Implementations"},"doc://com.mapbox.MapboxMaps/SH":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","title":"Swift.Hashable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateBounds":{"url":"\/documentation\/mapboxmaps\/coordinatebounds","navigatorTitle":[{"text":"CoordinateBounds","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoordinateBounds","kind":"identifier"}],"kind":"symbol","title":"CoordinateBounds","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds","role":"symbol","type":"topic","abstract":[{"text":"A rectangular area as measured on a two-dimensional map projection.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapError":{"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapError","kind":"identifier"}],"abstract":[{"type":"text","text":"Type of errors thrown by the "},{"type":"codeVoice","code":"MapboxMap"},{"text":" APIs.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"MapError","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/maperror","title":"MapError","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapError"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraBoundsOptions/hash(into:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBoundsOptions\/hash(into:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hasher","kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV"},{"text":")","kind":"text"}],"role":"symbol","kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/mapboxmaps\/cameraboundsoptions\/hash(into:)","title":"hash(into:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateInfo":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoordinateInfo","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/coordinateinfo","kind":"symbol","navigatorTitle":[{"text":"CoordinateInfo","kind":"identifier"}],"abstract":[{"type":"text","text":"Represents the coordinate information returned by the "},{"type":"codeVoice","code":"coordinateInfoForPixel"},{"type":"text","text":" or "},{"type":"codeVoice","code":"coordinatesInfoForPixels"},{"type":"text","text":" methods."}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateInfo","title":"CoordinateInfo"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateBoundsZoom":{"url":"\/documentation\/mapboxmaps\/coordinateboundszoom","navigatorTitle":[{"text":"CoordinateBoundsZoom","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoordinateBoundsZoom","kind":"identifier"}],"kind":"symbol","title":"CoordinateBoundsZoom","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBoundsZoom","role":"symbol","abstract":[{"text":"A coordinate bounds and zoom.","type":"text"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraBoundsOptions/init(cameraBounds:)":{"url":"\/documentation\/mapboxmaps\/cameraboundsoptions\/init(camerabounds:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cameraBounds","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CameraBounds","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps12CameraBoundsV"},{"text":")","kind":"text"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBoundsOptions\/init(cameraBounds:)","kind":"symbol","title":"init(cameraBounds:)","abstract":[{"type":"text","text":"Initialize a "},{"code":"CameraBoundsOptions","type":"codeVoice"},{"type":"text","text":" from the immutable "},{"code":"CameraBounds","type":"codeVoice"},{"type":"text","text":" type"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraBoundsOptions/maxPitch":{"title":"maxPitch","abstract":[{"type":"text","text":"The maximum allowed pitch value in degrees."},{"type":"text","text":" "},{"type":"text","text":"Defaults to 85."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxPitch","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":"?","kind":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBoundsOptions\/maxPitch","url":"\/documentation\/mapboxmaps\/cameraboundsoptions\/maxpitch","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraOptions":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraOptions"}],"abstract":[],"url":"\/documentation\/mapboxmaps\/cameraoptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraOptions","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraOptions"}],"role":"symbol","title":"CameraOptions","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraBoundsOptions/==(_:_:)":{"title":"==(_:_:)","role":"symbol","url":"\/documentation\/mapboxmaps\/cameraboundsoptions\/==(_:_:)","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBoundsOptions\/==(_:_:)","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"==","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"CameraBoundsOptions","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps19CameraBoundsOptionsV"},{"text":", ","kind":"text"},{"text":"CameraBoundsOptions","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps19CameraBoundsOptionsV"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"type":"topic","url":"\/documentation\/mapboxmaps\/mapboxmap-apis","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","role":"collectionGroup","title":"MapboxMap","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderedQueryGeometry":{"abstract":[{"text":"A geometry to define a portion of screen that should be queried for rendered features.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"RenderedQueryGeometry"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"RenderedQueryGeometry"}],"kind":"symbol","type":"topic","title":"RenderedQueryGeometry","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometry","url":"\/documentation\/mapboxmaps\/renderedquerygeometry"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","url":"\/documentation\/mapboxmaps","title":"MapboxMaps","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraBoundsOptions/maxZoom":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBoundsOptions\/maxZoom","url":"\/documentation\/mapboxmaps\/cameraboundsoptions\/maxzoom","title":"maxZoom","type":"topic","abstract":[{"type":"text","text":"The maximum zoom level, in mapbox zoom levels 0-25.5. At low zoom levels,"},{"type":"text","text":" "},{"type":"text","text":"a small set of map tiles covers a large geographical area. At higher"},{"type":"text","text":" "},{"type":"text","text":"zoom levels, a larger number of tiles cover a smaller geographical area."},{"type":"text","text":" "},{"type":"text","text":"Defaults to 22."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxZoom","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":"?","kind":"text"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraState":{"role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraState"}],"title":"CameraState","type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/camerastate","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraState","navigatorTitle":[{"kind":"identifier","text":"CameraState"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraBounds":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraBounds"}],"navigatorTitle":[{"kind":"identifier","text":"CameraBounds"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBounds","url":"\/documentation\/mapboxmaps\/camerabounds","type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Holds information about camera bounds."}],"title":"CameraBounds"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapboxMap"}],"type":"topic","title":"MapboxMap","abstract":[{"type":"text","text":"Provides access to the map model, including the camera, style, observable map events,"},{"type":"text","text":" "},{"type":"text","text":"and querying rendered features."}],"navigatorTitle":[{"kind":"identifier","text":"MapboxMap"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","url":"\/documentation\/mapboxmaps\/mapboxmap","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GlyphsRasterizationMode":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GlyphsRasterizationMode","kind":"identifier"}],"abstract":[{"type":"text","text":"Describes glyphs rasterization modes."}],"navigatorTitle":[{"text":"GlyphsRasterizationMode","kind":"identifier"}],"type":"topic","title":"GlyphsRasterizationMode","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode","url":"\/documentation\/mapboxmaps\/glyphsrasterizationmode"},"doc://com.mapbox.MapboxMaps/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","title":"Swift.Equatable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraBoundsOptions/init(bounds:maxZoom:minZoom:maxPitch:minPitch:)":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/cameraboundsoptions\/init(bounds:maxzoom:minzoom:maxpitch:minpitch:)","role":"symbol","title":"init(bounds:maxZoom:minZoom:maxPitch:minPitch:)","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBoundsOptions\/init(bounds:maxZoom:minZoom:maxPitch:minPitch:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bounds"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MBMCoordinateBounds","kind":"typeIdentifier","text":"CoordinateBounds"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"maxZoom"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"kind":"text","text":"?, "},{"text":"minZoom","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":"?, ","kind":"text"},{"text":"maxPitch","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":"?, ","kind":"text"},{"text":"minPitch","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":"?)","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraBoundsOptions/minZoom":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBoundsOptions\/minZoom","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minZoom","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":"?","kind":"text"}],"kind":"symbol","title":"minZoom","type":"topic","url":"\/documentation\/mapboxmaps\/cameraboundsoptions\/minzoom","abstract":[{"type":"text","text":"The minimum zoom level, in mapbox zoom levels 0-25.5."},{"type":"text","text":" "},{"type":"text","text":"Defaults to 0."}]},"https://en.wikipedia.org/wiki/Web_Mercator_projection":{"type":"link","identifier":"https:\/\/en.wikipedia.org\/wiki\/Web_Mercator_projection","title":"Spherical Mercator","titleInlineContent":[{"type":"text","text":"Spherical Mercator"}],"url":"https:\/\/en.wikipedia.org\/wiki\/Web_Mercator_projection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"MBMContextMode","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ContextMode\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBMContextMode"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ContextMode\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MBMContextMode"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ContextMode\/navigatorTitle"},{"value":"MBMMapCenterAltitudeMode","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapCenterAltitudeMode\/title"},{"value":[{"kind":"identifier","text":"MBMMapCenterAltitudeMode"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapCenterAltitudeMode\/fragments"},{"value":[{"text":"MBMMapCenterAltitudeMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapCenterAltitudeMode\/navigatorTitle"},{"value":"MBMCoordinateBounds","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds\/title"},{"value":[{"text":"MBMCoordinateBounds","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds\/fragments"},{"value":[{"text":"MBMCoordinateBounds","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds\/navigatorTitle"},{"value":"MBMCoordinateInfo","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateInfo\/title"},{"value":[{"kind":"identifier","text":"MBMCoordinateInfo"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateInfo\/fragments"},{"value":[{"kind":"identifier","text":"MBMCoordinateInfo"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateInfo\/navigatorTitle"},{"value":"MBMCoordinateBoundsZoom","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBoundsZoom\/title"},{"value":[{"text":"MBMCoordinateBoundsZoom","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBoundsZoom\/fragments"},{"value":[{"text":"MBMCoordinateBoundsZoom","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBoundsZoom\/navigatorTitle"},{"value":"MBMGlyphsRasterizationMode","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/title"},{"value":[{"text":"MBMGlyphsRasterizationMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/fragments"},{"value":[{"text":"MBMGlyphsRasterizationMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/navigatorTitle"}]}]}