{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomLayerMapProjection"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/mapboxmaps\/customlayermapprojection"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/customlayermapprojection"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers"]]},"metadata":{"symbolKind":"protocol","title":"CustomLayerMapProjection","role":"symbol","roleHeading":"Protocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomLayerMapProjection"}],"navigatorTitle":[{"kind":"identifier","text":"CustomLayerMapProjection"}],"modules":[{"name":"MapboxMaps"}],"externalID":"c:objc(pl)MBMCustomLayerMapProjection"},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerMapProjection","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerMapProjection\/convertMercatorModelMatrix(forMatrix:ignoreDistortion:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerMapProjection\/getModelMatrix()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerMapProjection\/getTransitionMatrix()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerMapProjection\/getTransitionPhase()"],"anchor":"Instance-Methods","generated":true}],"seeAlsoSections":[{"title":"Layers","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerInfo","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/BackgroundLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CircleLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillExtrusionLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationIndicatorLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterParticleLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SkyLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderConfiguration","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerHost","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ElevationData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Slot","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SlotLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerAtPosition","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClipLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClipLayerTypes"],"anchor":"Layers","generated":true}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerMapProjection/getTransitionPhase()":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getTransitionPhase"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"}],"required":true,"abstract":[{"type":"text","text":"Returns normalized value [0, 1] describing phase of the transition between the currently active projection and"},{"type":"text","text":" "},{"type":"text","text":"mercator projection. This value is 1 when the projection is active and transitions towards the value 0 (mercator projection)"},{"type":"text","text":" "},{"type":"text","text":"as the map is zoomed."}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/customlayermapprojection\/gettransitionphase()","type":"topic","title":"getTransitionPhase()","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerMapProjection\/getTransitionPhase()","navigatorTitle":[{"kind":"identifier","text":"getTransitionPhase"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","url":"\/documentation\/mapboxmaps","title":"MapboxMaps","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerMapProjection/getTransitionMatrix()":{"url":"\/documentation\/mapboxmaps\/customlayermapprojection\/gettransitionmatrix()","navigatorTitle":[{"text":"getTransitionMatrix","kind":"identifier"}],"abstract":[{"type":"text","text":"Returns a specialized model matrix for supporting rendering of custom geometry during transition between"},{"type":"text","text":" "},{"type":"text","text":"the active projection and mercator projection. Transition matrix prepares points on web mercator coordinate space"},{"type":"text","text":" "},{"type":"text","text":"to be used as destination points of the interpolation operation towards mercator projection."}],"kind":"symbol","title":"getTransitionMatrix()","required":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerMapProjection\/getTransitionMatrix()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getTransitionMatrix","kind":"identifier"},{"text":"() -> [","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layer":{"type":"topic","abstract":[],"title":"Layer","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Layer"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Layer"}],"url":"\/documentation\/mapboxmaps\/layer"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterParticleLayer":{"tags":[{"text":"SPI","type":"spi"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/rasterparticlelayer","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RasterParticleLayer","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterParticleLayer","title":"RasterParticleLayer","navigatorTitle":[{"text":"RasterParticleLayer","kind":"identifier"}],"type":"topic","abstract":[{"text":"Particle animation driven by textures such as wind maps.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ClipLayer":{"role":"symbol","url":"\/documentation\/mapboxmaps\/cliplayer","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ClipLayer","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Layer that removes 3D content from map.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClipLayer","title":"ClipLayer","navigatorTitle":[{"text":"ClipLayer","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelLayer":{"type":"topic","navigatorTitle":[{"text":"ModelLayer","kind":"identifier"}],"title":"ModelLayer","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ModelLayer","kind":"identifier"}],"role":"symbol","abstract":[{"text":"A layer to render 3D Models.","type":"text"}],"url":"\/documentation\/mapboxmaps\/modellayer","kind":"symbol","tags":[{"text":"SPI","type":"spi"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CircleLayer":{"navigatorTitle":[{"text":"CircleLayer","kind":"identifier"}],"title":"CircleLayer","abstract":[{"type":"text","text":"A filled circle."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CircleLayer","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/circlelayer","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CircleLayer","type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerAtPosition":{"navigatorTitle":[{"text":"LayerAtPosition","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerAtPosition","abstract":[],"title":"LayerAtPosition","type":"topic","url":"\/documentation\/mapboxmaps\/layeratposition","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LayerAtPosition","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerRenderConfiguration":{"abstract":[{"type":"text","text":"Note! This is an experimental feature. It can be changed or removed in future versions."}],"title":"CustomLayerRenderConfiguration","type":"topic","url":"\/documentation\/mapboxmaps\/customlayerrenderconfiguration","navigatorTitle":[{"text":"CustomLayerRenderConfiguration","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomLayerRenderConfiguration","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderConfiguration","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerInfo":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LayerInfo"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerInfo","kind":"symbol","role":"symbol","title":"LayerInfo","navigatorTitle":[{"kind":"identifier","text":"LayerInfo"}],"type":"topic","abstract":[{"type":"text","text":"Information about a layer"}],"url":"\/documentation\/mapboxmaps\/layerinfo"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayer":{"navigatorTitle":[{"text":"CustomLayer","kind":"identifier"}],"role":"symbol","tags":[{"text":"SPI","type":"spi"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/customlayer","abstract":[{"text":"Layer with custom rendering implementation","type":"text"}],"type":"topic","title":"CustomLayer","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomLayer","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayer"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SkyLayer":{"navigatorTitle":[{"text":"SkyLayer","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SkyLayer","kind":"identifier"}],"abstract":[{"text":"A spherical dome around the map that is always rendered behind all other layers.","type":"text"},{"text":" ","type":"text"},{"text":"Warning: As of v10.6.0, ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Atmosphere","isActive":true,"type":"reference"},{"text":" is the preferred method for atmospheric styling. Sky layer is not supported by the globe projection, and will be phased out in future major release.","type":"text"}],"type":"topic","title":"SkyLayer","kind":"symbol","url":"\/documentation\/mapboxmaps\/skylayer","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SkyLayer","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FillExtrusionLayer":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillExtrusionLayer","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FillExtrusionLayer"}],"type":"topic","abstract":[{"text":"An extruded (3D) polygon.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"FillExtrusionLayer"}],"url":"\/documentation\/mapboxmaps\/fillextrusionlayer","title":"FillExtrusionLayer"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerMapProjection":{"url":"\/documentation\/mapboxmaps\/customlayermapprojection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerMapProjection","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CustomLayerMapProjection"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomLayerMapProjection"}],"kind":"symbol","type":"topic","title":"CustomLayerMapProjection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerRenderParameters":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"CustomLayerRenderParameters"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomLayerRenderParameters"}],"url":"\/documentation\/mapboxmaps\/customlayerrenderparameters","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters","abstract":[{"text":"Parameters that define the current camera position for a ","type":"text"},{"code":"CustomLayerHost::render()","type":"codeVoice"},{"text":" function.","type":"text"}],"kind":"symbol","role":"symbol","title":"CustomLayerRenderParameters"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/BackgroundLayer":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"BackgroundLayer"}],"abstract":[{"type":"text","text":"The background color or pattern of the map."}],"url":"\/documentation\/mapboxmaps\/backgroundlayer","type":"topic","title":"BackgroundLayer","navigatorTitle":[{"kind":"identifier","text":"BackgroundLayer"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/BackgroundLayer"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SlotLayer":{"type":"topic","navigatorTitle":[{"text":"SlotLayer","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SlotLayer","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/slotlayer","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SlotLayer","abstract":[{"text":"Marks the position of a slot.","type":"text"}],"kind":"symbol","role":"symbol","title":"SlotLayer"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeatmapLayer":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer","navigatorTitle":[{"text":"HeatmapLayer","kind":"identifier"}],"title":"HeatmapLayer","abstract":[{"text":"A heatmap.","type":"text"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HeatmapLayer","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/heatmaplayer"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LineLayer":{"title":"LineLayer","navigatorTitle":[{"text":"LineLayer","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineLayer","type":"topic","url":"\/documentation\/mapboxmaps\/linelayer","abstract":[{"text":"A stroked line.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LineLayer","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ClipLayerTypes":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClipLayerTypes","type":"topic","url":"\/documentation\/mapboxmaps\/cliplayertypes","abstract":[{"type":"text","text":"Layer types that will also be removed if fallen below this clip layer."}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ClipLayerTypes","kind":"identifier"}],"title":"ClipLayerTypes","kind":"symbol","navigatorTitle":[{"text":"ClipLayerTypes","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Atmosphere":{"title":"Atmosphere","role":"symbol","kind":"symbol","abstract":[{"text":"A style’s fog property is a global effect that improves depth perception by fading out distant objects.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"Atmosphere"}],"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Atmosphere"}],"url":"\/documentation\/mapboxmaps\/atmosphere","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Atmosphere"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layers":{"abstract":[],"url":"\/documentation\/mapboxmaps\/layers","kind":"article","type":"topic","role":"collectionGroup","title":"Layers","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterLayer":{"title":"RasterLayer","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterLayer","navigatorTitle":[{"kind":"identifier","text":"RasterLayer"}],"abstract":[{"type":"text","text":"Raster map textures such as satellite imagery."}],"role":"symbol","url":"\/documentation\/mapboxmaps\/rasterlayer","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"RasterLayer"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerType":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LayerType"}],"url":"\/documentation\/mapboxmaps\/layertype","navigatorTitle":[{"kind":"identifier","text":"LayerType"}],"type":"topic","role":"symbol","title":"LayerType","abstract":[{"type":"text","text":"Struct of supported Layer rendering types"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerMapProjection/getModelMatrix()":{"required":true,"abstract":[{"text":"Returns a model matrix for transforming coordinates from the local coordinate space of the active projection","type":"text"},{"text":" ","type":"text"},{"text":"into the world coordinate space. For example with globe projection the returned matrix will transform ECEF points","type":"text"},{"text":" ","type":"text"},{"text":"into world coordinates for rendering.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getModelMatrix"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"]"}],"title":"getModelMatrix()","navigatorTitle":[{"kind":"identifier","text":"getModelMatrix"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerMapProjection\/getModelMatrix()","url":"\/documentation\/mapboxmaps\/customlayermapprojection\/getmodelmatrix()","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Slot":{"navigatorTitle":[{"text":"Slot","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/slot","kind":"symbol","abstract":[{"type":"text","text":"A pre-specified location in the style where layer will be added to"},{"type":"text","text":" "},{"type":"text","text":"(such as on top of existing land layers, but below all labels)."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Slot","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Slot","type":"topic","role":"symbol","title":"Slot"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FillLayer":{"type":"topic","title":"FillLayer","url":"\/documentation\/mapboxmaps\/filllayer","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FillLayer"}],"abstract":[{"type":"text","text":"A filled polygon with an optional stroked border."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FillLayer"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillLayer","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SymbolLayer":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolLayer","title":"SymbolLayer","abstract":[{"text":"An icon or a text label.","type":"text"}],"type":"topic","url":"\/documentation\/mapboxmaps\/symbollayer","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SymbolLayer"}],"navigatorTitle":[{"kind":"identifier","text":"SymbolLayer"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","role":"collection","type":"topic","abstract":[],"title":"MapboxMaps Documentation","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LocationIndicatorLayer":{"title":"LocationIndicatorLayer","kind":"symbol","abstract":[{"type":"text","text":"Location Indicator layer."}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationIndicatorLayer","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"LocationIndicatorLayer","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationIndicatorLayer","url":"\/documentation\/mapboxmaps\/locationindicatorlayer"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerMapProjection/convertMercatorModelMatrix(forMatrix:ignoreDistortion:)":{"role":"symbol","title":"convertMercatorModelMatrix(forMatrix:ignoreDistortion:)","url":"\/documentation\/mapboxmaps\/customlayermapprojection\/convertmercatormodelmatrix(formatrix:ignoredistortion:)","type":"topic","abstract":[{"type":"text","text":"Convert a model matrix to be usable with the currently active projection."},{"type":"text","text":" "},{"type":"text","text":"The input matrix is expected to transform coordinates from a local coordinate space"},{"type":"text","text":" "},{"type":"text","text":"into web mercator coordinate space where x & y axes are defined in pixels and z in meters."},{"type":"text","text":" "},{"type":"text","text":"The output matrix will transform local coordinates and align them correctly"},{"type":"text","text":" "},{"type":"text","text":"on the world coordinate space."}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerMapProjection\/convertMercatorModelMatrix(forMatrix:ignoreDistortion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"convertMercatorModelMatrix","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forMatrix","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"ignoreDistortion","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":") -> [","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"required":true,"navigatorTitle":[{"text":"convertMercatorModelMatrixForMatrix:ignoreDistortion:","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer","role":"symbol","url":"\/documentation\/mapboxmaps\/hillshadelayer","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"HillshadeLayer"}],"abstract":[{"type":"text","text":"Client-side hillshading visualization based on DEM data. Currently, the implementation only supports Mapbox Terrain RGB and Mapzen Terrarium tiles."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"HillshadeLayer"}],"title":"HillshadeLayer","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerHost":{"abstract":[{"text":"Interface for hosting a custom map style layer.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomLayerHost"}],"url":"\/documentation\/mapboxmaps\/customlayerhost","kind":"symbol","title":"CustomLayerHost","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerHost","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CustomLayerHost"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ElevationData":{"role":"symbol","url":"\/documentation\/mapboxmaps\/elevationdata","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ElevationData"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ElevationData"}],"title":"ElevationData","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ElevationData","type":"topic","abstract":[{"type":"text","text":"Interface that provides access to elevation data."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"MBMCustomLayerMapProjection"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MBMCustomLayerMapProjection","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"MBMCustomLayerMapProjection","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerMapProjection\/convertMercatorModelMatrix(forMatrix:ignoreDistortion:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerMapProjection\/getModelMatrix()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerMapProjection\/getTransitionMatrix()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerMapProjection\/getTransitionPhase()"],"generated":true}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderConfiguration","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerHost","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ElevationData"],"anchor":"Layers","title":"Layers","generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBMCustomLayerMapProjection"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerMapProjection~1getTransitionPhase()\/title","value":"getTransitionPhase"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerMapProjection~1getTransitionPhase()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getTransitionPhase"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerMapProjection~1getTransitionMatrix()\/title","value":"getTransitionMatrix"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerMapProjection~1getTransitionMatrix()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"getTransitionMatrix","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderConfiguration\/title","value":"MBMCustomLayerRenderConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderConfiguration\/fragments","value":[{"kind":"identifier","text":"MBMCustomLayerRenderConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"MBMCustomLayerRenderConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerMapProjection\/title","value":"MBMCustomLayerMapProjection"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerMapProjection\/fragments","value":[{"text":"MBMCustomLayerMapProjection","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerMapProjection\/navigatorTitle","value":[{"text":"MBMCustomLayerMapProjection","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/title","value":"MBMCustomLayerRenderParameters"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/fragments","value":[{"kind":"identifier","text":"MBMCustomLayerRenderParameters"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/navigatorTitle","value":[{"kind":"identifier","text":"MBMCustomLayerRenderParameters"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerMapProjection~1getModelMatrix()\/title","value":"getModelMatrix"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerMapProjection~1getModelMatrix()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"getModelMatrix","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerMapProjection~1convertMercatorModelMatrix(forMatrix:ignoreDistortion:)\/title","value":"convertMercatorModelMatrixForMatrix:ignoreDistortion:"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerMapProjection~1convertMercatorModelMatrix(forMatrix:ignoreDistortion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"convertMercatorModelMatrixForMatrix:ignoreDistortion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost\/title","value":"MBMCustomLayerHost"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost\/fragments","value":[{"kind":"identifier","text":"MBMCustomLayerHost"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost\/navigatorTitle","value":[{"kind":"identifier","text":"MBMCustomLayerHost"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ElevationData\/title","value":"MBMElevationData"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ElevationData\/fragments","value":[{"text":"MBMElevationData","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ElevationData\/navigatorTitle","value":[{"text":"MBMElevationData","kind":"identifier"}]}]}]}