{"kind":"symbol","abstract":[{"text":"An animator that evokes powered flight and an optional transition duration and timing function.","type":"text"},{"text":" ","type":"text"},{"text":"It seamlessly incorporates zooming and panning to help the user find their bearings even after","type":"text"},{"text":" ","type":"text"},{"text":"traversing a great distance.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FlyToCameraAnimator"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"level":2,"anchor":"overview","text":"Overview","type":"heading"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraAnimationsManager\/fly(to:duration:curve:completion:)"}]}],"style":"note","name":"See Also","type":"aside"}],"kind":"content"}],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FlyToCameraAnimator","kind":"identifier"}],"title":"FlyToCameraAnimator","navigatorTitle":[{"text":"FlyToCameraAnimator","kind":"identifier"}],"role":"symbol","roleHeading":"Class","symbolKind":"class","externalID":"s:10MapboxMaps19FlyToCameraAnimatorC","modules":[{"name":"MapboxMaps"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Camera-and-coordinates"],["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Camera-and-coordinates"]]},"sections":[],"relationshipsSections":[{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraAnimator","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Cancelable"]}],"seeAlsoSections":[{"generated":true,"anchor":"Camera-Animations","title":"Camera Animations","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraAnimationsManager","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraAnimator","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/BasicCameraAnimator","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraTransition","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AnimationCompletion","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AnimationOwner","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TimingCurve"]}],"variants":[{"paths":["\/documentation\/mapboxmaps\/flytocameraanimator"],"traits":[{"interfaceLanguage":"swift"}]}],"topicSections":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FlyToCameraAnimator\/duration","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FlyToCameraAnimator\/onCancelled","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FlyToCameraAnimator\/onFinished","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FlyToCameraAnimator\/onStarted","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FlyToCameraAnimator\/owner","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FlyToCameraAnimator\/state"]},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FlyToCameraAnimator\/cancel()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FlyToCameraAnimator\/stopAnimation()"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FlyToCameraAnimator"},"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"type":"topic","url":"\/documentation\/overview","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"kind":"article","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","type":"topic","title":"MapboxMap","abstract":[],"url":"\/documentation\/mapboxmaps\/mapboxmap-apis"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FlyToCameraAnimator/state":{"kind":"symbol","type":"topic","title":"state","url":"\/documentation\/mapboxmaps\/flytocameraanimator\/state","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"state","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIViewAnimatingState","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIViewAnimatingState"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FlyToCameraAnimator\/state","abstract":[{"type":"text","text":"The animator’s state"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AnimationCompletion":{"title":"AnimationCompletion","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AnimationCompletion","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AnimationCompletion","kind":"identifier"}],"abstract":[{"text":"A block object to be executed when the animation sequence ends.","type":"text"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"AnimationCompletion","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/animationcompletion"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FlyToCameraAnimator/onCancelled":{"type":"topic","abstract":[{"type":"text","text":"Emits a signal when this animator is cancelled."}],"url":"\/documentation\/mapboxmaps\/flytocameraanimator\/oncancelled","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FlyToCameraAnimator\/onCancelled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onCancelled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps6SignalV","text":"Signal","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":">","kind":"text"}],"title":"onCancelled","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FlyToCameraAnimator/stopAnimation()":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/flytocameraanimator\/stopanimation()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopAnimation","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FlyToCameraAnimator\/stopAnimation()","type":"topic","role":"symbol","title":"stopAnimation()","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FlyToCameraAnimator/onFinished":{"url":"\/documentation\/mapboxmaps\/flytocameraanimator\/onfinished","abstract":[{"type":"text","text":"Emits a signal when this animator has finished."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onFinished"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV","text":"Signal"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":">"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FlyToCameraAnimator\/onFinished","title":"onFinished"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FlyToCameraAnimator/duration":{"title":"duration","kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/flytocameraanimator\/duration","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FlyToCameraAnimator\/duration","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"duration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}],"abstract":[{"type":"text","text":"The animator’s duration"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Camera-and-coordinates":{"role":"collectionGroup","title":"Camera and coordinates","type":"topic","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Camera-and-coordinates","url":"\/documentation\/mapboxmaps\/camera-and-coordinates","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","type":"topic","title":"MapboxMaps","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TimingCurve":{"role":"symbol","url":"\/documentation\/mapboxmaps\/timingcurve","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TimingCurve","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TimingCurve","kind":"identifier"}],"navigatorTitle":[{"text":"TimingCurve","kind":"identifier"}],"abstract":[{"text":"Timing curve to use in animator.","type":"text"}],"title":"TimingCurve","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FlyToCameraAnimator/cancel()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancel"},{"kind":"text","text":"()"}],"kind":"symbol","title":"cancel()","url":"\/documentation\/mapboxmaps\/flytocameraanimator\/cancel()","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FlyToCameraAnimator\/cancel()","type":"topic","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraAnimator":{"url":"\/documentation\/mapboxmaps\/cameraanimator","title":"CameraAnimator","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraAnimator","type":"topic","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraAnimator","kind":"identifier"}],"navigatorTitle":[{"text":"CameraAnimator","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraAnimationsManager/fly(to:duration:curve:completion:)":{"abstract":[{"type":"text","text":"Moves the viewpoint to a different location using a transition animation that"},{"type":"text","text":" "},{"type":"text","text":"evokes powered flight and an optional transition duration and timing function."},{"type":"text","text":" "},{"type":"text","text":"It seamlessly incorporates zooming and panning to help"},{"type":"text","text":" "},{"type":"text","text":"the user find his or her bearings even after traversing a great distance."}],"title":"fly(to:duration:curve:completion:)","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fly"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10MapboxMaps13CameraOptionsV","kind":"typeIdentifier","text":"CameraOptions"},{"kind":"text","text":", "},{"kind":"externalParam","text":"duration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"curve"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10MapboxMaps11TimingCurveV","kind":"typeIdentifier","text":"TimingCurve"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10MapboxMaps19AnimationCompletiona","kind":"typeIdentifier","text":"AnimationCompletion"},{"kind":"text","text":"?) -> any "},{"preciseIdentifier":"c:objc(pl)MBXCancelable","kind":"typeIdentifier","text":"Cancelable"}],"url":"\/documentation\/mapboxmaps\/cameraanimationsmanager\/fly(to:duration:curve:completion:)","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraAnimationsManager\/fly(to:duration:curve:completion:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AnimationOwner":{"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnimationOwner"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AnimationOwner","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"AnimationOwner"}],"title":"AnimationOwner","role":"symbol","url":"\/documentation\/mapboxmaps\/animationowner"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraAnimationsManager":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraAnimationsManager","url":"\/documentation\/mapboxmaps\/cameraanimationsmanager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraAnimationsManager","kind":"identifier"}],"navigatorTitle":[{"text":"CameraAnimationsManager","kind":"identifier"}],"role":"symbol","title":"CameraAnimationsManager","abstract":[{"text":"APIs for animating the camera.","type":"text"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraTransition":{"abstract":[{"type":"text","text":"Structure used to represent a desired change to the map’s camera"}],"url":"\/documentation\/mapboxmaps\/cameratransition","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraTransition","kind":"symbol","role":"symbol","title":"CameraTransition","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraTransition"}],"navigatorTitle":[{"kind":"identifier","text":"CameraTransition"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FlyToCameraAnimator":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FlyToCameraAnimator","abstract":[{"type":"text","text":"An animator that evokes powered flight and an optional transition duration and timing function."},{"type":"text","text":" "},{"type":"text","text":"It seamlessly incorporates zooming and panning to help the user find their bearings even after"},{"type":"text","text":" "},{"type":"text","text":"traversing a great distance."}],"navigatorTitle":[{"kind":"identifier","text":"FlyToCameraAnimator"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/flytocameraanimator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FlyToCameraAnimator"}],"title":"FlyToCameraAnimator"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FlyToCameraAnimator/owner":{"role":"symbol","kind":"symbol","url":"\/documentation\/mapboxmaps\/flytocameraanimator\/owner","abstract":[{"text":"The animator’s owner","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FlyToCameraAnimator\/owner","title":"owner","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"owner"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10MapboxMaps14AnimationOwnerV","kind":"typeIdentifier","text":"AnimationOwner"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/BasicCameraAnimator":{"title":"BasicCameraAnimator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BasicCameraAnimator","kind":"identifier"}],"navigatorTitle":[{"text":"BasicCameraAnimator","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/BasicCameraAnimator","type":"topic","url":"\/documentation\/mapboxmaps\/basiccameraanimator","role":"symbol","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Cancelable":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Cancelable","kind":"symbol","url":"\/documentation\/mapboxcommon\/cancelable","navigatorTitle":[{"kind":"identifier","text":"Cancelable"}],"abstract":[{"type":"text","text":"Allows to cancel the associated asynchronous operation"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Cancelable"}],"type":"topic","title":"Cancelable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FlyToCameraAnimator/onStarted":{"type":"topic","abstract":[{"type":"text","text":"Emits a signal when this animator has started."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onStarted"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV","text":"Signal"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":">"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FlyToCameraAnimator\/onStarted","url":"\/documentation\/mapboxmaps\/flytocameraanimator\/onstarted","title":"onStarted"}},"variantOverrides":[{"patch":[{"value":"MBXCancelable","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/title","op":"replace"},{"value":[{"text":"MBXCancelable","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MBXCancelable"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}