{"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionGeometryDefinition","interfaceLanguage":"swift"},"seeAlsoSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegion","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionManager","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionTilePyramidDefinition","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionStatus","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadProgressCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionDownloadState","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionErrorType"],"generated":true,"anchor":"Deprecated","title":"Deprecated"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionGeometryDefinition\/glyphsRasterizationMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionGeometryDefinition\/maxZoom","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionGeometryDefinition\/minZoom","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionGeometryDefinition\/pixelRatio","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionGeometryDefinition\/styleURL"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"}],"kind":"symbol","metadata":{"symbolKind":"class","modules":[{"name":"MapboxMaps"}],"role":"symbol","externalID":"c:objc(cs)MBMOfflineRegionGeometryDefinition","navigatorTitle":[{"text":"OfflineRegionGeometryDefinition","kind":"identifier"}],"roleHeading":"Class","title":"OfflineRegionGeometryDefinition","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OfflineRegionGeometryDefinition","kind":"identifier"}],"platforms":[]},"variants":[{"paths":["\/documentation\/mapboxmaps\/offlineregiongeometrydefinition"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/offlineregiongeometrydefinition"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline"]]},"abstract":[{"text":"An offline region definition is a geographic region defined by a style URL,","type":"text"},{"text":" ","type":"text"},{"text":"a geometry, zoom range, and device pixel ratio. Both ","type":"text"},{"code":"minZoom","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"maxZoom","type":"codeVoice"},{"text":" must be ≥ 0,","type":"text"},{"text":" ","type":"text"},{"text":"and ","type":"text"},{"code":"maxZoom","type":"codeVoice"},{"text":" must be ≥ ","type":"text"},{"code":"minZoom","type":"codeVoice"},{"text":". The ","type":"text"},{"code":"maxZoom","type":"codeVoice"},{"text":" may be ∞, in which case for each tile source,","type":"text"},{"text":" ","type":"text"},{"text":"the region will include tiles from ","type":"text"},{"code":"minZoom","type":"codeVoice"},{"text":" up to the maximum zoom level provided by that source.","type":"text"},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"code":"pixelRatio","type":"codeVoice"},{"text":" must be ≥ 0 and should typically be 1.0 or 2.0.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OfflineRegionGeometryDefinition","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.mapbox.MapboxMaps/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.mapbox.MapboxMaps/SH":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","title":"Swift.Hashable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionGeometryDefinition/styleURL":{"navigatorTitle":[{"kind":"identifier","text":"styleURL"}],"title":"styleURL","type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/offlineregiongeometrydefinition\/styleurl","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"styleURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionGeometryDefinition\/styleURL","deprecated":true,"abstract":[{"text":"The style associated with the offline region","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMOfflineRegionGeometryDefinition/geometry":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMOfflineRegionGeometryDefinition\/geometry","url":"\/documentation\/mapboxmaps\/mbmofflineregiongeometrydefinition\/geometry","fragments":[{"kind":"identifier","text":"geometry"}],"kind":"symbol","title":"geometry","role":"symbol","type":"topic","abstract":[{"text":"The geometry that defines the boundary of the offline region","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionError":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OfflineRegionError","kind":"identifier"}],"navigatorTitle":[{"text":"OfflineRegionError","kind":"identifier"}],"deprecated":true,"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionError","abstract":[{"type":"text","text":"Describes an offline request response error."}],"url":"\/documentation\/mapboxmaps\/offlineregionerror","role":"symbol","title":"OfflineRegionError"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMaps":{"abstract":[{"type":"text","text":"Maps rendering SDK also known as GL-Native"}],"role":"collectionGroup","title":"Core Maps API","url":"\/documentation\/mapboxmaps\/coremaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","type":"topic","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionGeometryDefinition/maxZoom":{"url":"\/documentation\/mapboxmaps\/offlineregiongeometrydefinition\/maxzoom","abstract":[{"type":"text","text":"Maximum zoom level for the offline region"}],"role":"symbol","deprecated":true,"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxZoom","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionGeometryDefinition\/maxZoom","type":"topic","navigatorTitle":[{"text":"maxZoom","kind":"identifier"}],"title":"maxZoom"},"doc://com.mapbox.MapboxMaps/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","title":"Swift.Equatable"},"doc://com.mapbox.MapboxMaps/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionGeometryDefinition/pixelRatio":{"role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pixelRatio","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"}],"url":"\/documentation\/mapboxmaps\/offlineregiongeometrydefinition\/pixelratio","navigatorTitle":[{"text":"pixelRatio","kind":"identifier"}],"deprecated":true,"title":"pixelRatio","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionGeometryDefinition\/pixelRatio","abstract":[{"text":"Pixel ratio to be accounted for when downloading assets","type":"text"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","url":"\/documentation\/mapboxmaps","title":"MapboxMaps","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionGeometryDefinition":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OfflineRegionGeometryDefinition","kind":"identifier"}],"navigatorTitle":[{"text":"OfflineRegionGeometryDefinition","kind":"identifier"}],"title":"OfflineRegionGeometryDefinition","deprecated":true,"abstract":[{"text":"An offline region definition is a geographic region defined by a style URL,","type":"text"},{"text":" ","type":"text"},{"text":"a geometry, zoom range, and device pixel ratio. Both ","type":"text"},{"code":"minZoom","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"maxZoom","type":"codeVoice"},{"text":" must be ≥ 0,","type":"text"},{"text":" ","type":"text"},{"text":"and ","type":"text"},{"code":"maxZoom","type":"codeVoice"},{"text":" must be ≥ ","type":"text"},{"code":"minZoom","type":"codeVoice"},{"text":". The ","type":"text"},{"code":"maxZoom","type":"codeVoice"},{"text":" may be ∞, in which case for each tile source,","type":"text"},{"text":" ","type":"text"},{"text":"the region will include tiles from ","type":"text"},{"code":"minZoom","type":"codeVoice"},{"text":" up to the maximum zoom level provided by that source.","type":"text"},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"code":"pixelRatio","type":"codeVoice"},{"text":" must be ≥ 0 and should typically be 1.0 or 2.0.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionGeometryDefinition","type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/offlineregiongeometrydefinition","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionTilePyramidDefinition":{"abstract":[{"type":"text","text":"An offline region definition is a geographic region defined by a style URL,"},{"type":"text","text":" "},{"type":"text","text":"geographic bounding box, zoom range, and device pixel ratio. Both "},{"type":"codeVoice","code":"minZoom"},{"type":"text","text":" and "},{"type":"codeVoice","code":"maxZoom"},{"text":" must be ≥ 0,","type":"text"},{"text":" ","type":"text"},{"text":"and ","type":"text"},{"type":"codeVoice","code":"maxZoom"},{"text":" must be ≥ ","type":"text"},{"type":"codeVoice","code":"minZoom"},{"text":". The ","type":"text"},{"type":"codeVoice","code":"maxZoom"},{"text":" may be ∞, in which case for each tile source,","type":"text"},{"text":" ","type":"text"},{"text":"the region will include tiles from ","type":"text"},{"type":"codeVoice","code":"minZoom"},{"text":" up to the maximum zoom level provided by that source.","type":"text"},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"type":"codeVoice","code":"pixelRatio"},{"text":" must be ≥ 0 and should typically be 1.0 or 2.0.","type":"text"}],"url":"\/documentation\/mapboxmaps\/offlineregiontilepyramiddefinition","kind":"symbol","role":"symbol","deprecated":true,"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OfflineRegionTilePyramidDefinition","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionTilePyramidDefinition","title":"OfflineRegionTilePyramidDefinition","navigatorTitle":[{"text":"OfflineRegionTilePyramidDefinition","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionManager":{"navigatorTitle":[{"kind":"identifier","text":"OfflineRegionManager"}],"type":"topic","title":"OfflineRegionManager","url":"\/documentation\/mapboxmaps\/offlineregionmanager","role":"symbol","kind":"symbol","deprecated":true,"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"offline region manager"},{"type":"text","text":" that manages offline packs. All of the class’s instance methods are asynchronous"},{"type":"text","text":" "},{"type":"text","text":"reflecting the fact that offline resources are stored in a database. The offline manager maintains a canonical"},{"type":"text","text":" "},{"type":"text","text":"collection of offline packs."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OfflineRegionManager"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionStatus":{"url":"\/documentation\/mapboxmaps\/offlineregionstatus","type":"topic","title":"OfflineRegionStatus","kind":"symbol","deprecated":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionStatus","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OfflineRegionStatus","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"A region’s status includes its active\/inactive state as well as counts"},{"type":"text","text":" "},{"type":"text","text":"of the number of resources that have completed downloading, their total"},{"type":"text","text":" "},{"type":"text","text":"size in bytes, and the total number of resources that are required."}],"navigatorTitle":[{"text":"OfflineRegionStatus","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionErrorType":{"abstract":[{"type":"text","text":"Describes the reason for an offline request response error."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OfflineRegionErrorType","kind":"identifier"}],"navigatorTitle":[{"text":"OfflineRegionErrorType","kind":"identifier"}],"role":"symbol","title":"OfflineRegionErrorType","url":"\/documentation\/mapboxmaps\/offlineregionerrortype","deprecated":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionErrorType","type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegion":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OfflineRegion","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegion","navigatorTitle":[{"text":"OfflineRegion","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/offlineregion","deprecated":true,"kind":"symbol","role":"symbol","abstract":[{"text":"An offline region represents an identifiable geographic region with optional metadata.","type":"text"}],"title":"OfflineRegion"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePackLoadProgressCallback":{"navigatorTitle":[{"text":"StylePackLoadProgressCallback","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Callback Invoked to report the progess of the style package loading operation."}],"url":"\/documentation\/mapboxmaps\/stylepackloadprogresscallback","kind":"symbol","title":"StylePackLoadProgressCallback","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadProgressCallback","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StylePackLoadProgressCallback","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Offline":{"abstract":[],"role":"collectionGroup","title":"Offline Support","url":"\/documentation\/mapboxmaps\/offline","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","type":"topic","kind":"article"},"doc://com.mapbox.MapboxMaps/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject","title":"NSObject"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","role":"collection","type":"topic","abstract":[],"title":"MapboxMaps Documentation","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionObserver":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionObserver","url":"\/documentation\/mapboxmaps\/offlineregionobserver","navigatorTitle":[{"kind":"identifier","text":"OfflineRegionObserver"}],"abstract":[{"type":"text","text":"A region can have a single observer, which gets notified whenever a change"},{"type":"text","text":" "},{"type":"text","text":"to the region’s status occurs."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"OfflineRegionObserver"}],"type":"topic","deprecated":true,"title":"OfflineRegionObserver"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionDownloadState":{"url":"\/documentation\/mapboxmaps\/offlineregiondownloadstate","navigatorTitle":[{"kind":"identifier","text":"OfflineRegionDownloadState"}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OfflineRegionDownloadState"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionDownloadState","deprecated":true,"abstract":[{"text":"Describes the download state of a region.","type":"text"}],"title":"OfflineRegionDownloadState"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionGeometryDefinition/glyphsRasterizationMode":{"url":"\/documentation\/mapboxmaps\/offlineregiongeometrydefinition\/glyphsrasterizationmode","type":"topic","title":"glyphsRasterizationMode","navigatorTitle":[{"kind":"identifier","text":"glyphsRasterizationMode"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"glyphsRasterizationMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMGlyphsRasterizationMode","text":"GlyphsRasterizationMode"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionGeometryDefinition\/glyphsRasterizationMode","kind":"symbol","deprecated":true,"abstract":[{"type":"text","text":"Specifies glyphs rasterization mode. It defines which glyphs will be loaded from the server"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionGeometryDefinition/minZoom":{"kind":"symbol","abstract":[{"type":"text","text":"Minimum zoom level for the offline region"}],"type":"topic","role":"symbol","deprecated":true,"title":"minZoom","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionGeometryDefinition\/minZoom","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"minZoom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"url":"\/documentation\/mapboxmaps\/offlineregiongeometrydefinition\/minzoom","navigatorTitle":[{"kind":"identifier","text":"minZoom"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMOfflineRegionGeometryDefinition/initWithStyleURL:geometry:minZoom:maxZoom:pixelRatio:glyphsRasterizationMode:":{"fragments":[{"text":"- ","kind":"text"},{"text":"initWithStyleURL:geometry:minZoom:maxZoom:pixelRatio:glyphsRasterizationMode:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithStyleURL:geometry:minZoom:maxZoom:pixelRatio:glyphsRasterizationMode:","kind":"identifier"}],"title":"initWithStyleURL:geometry:minZoom:maxZoom:pixelRatio:glyphsRasterizationMode:","abstract":[],"url":"\/documentation\/mapboxmaps\/mbmofflineregiongeometrydefinition\/initwithstyleurl:geometry:minzoom:maxzoom:pixelratio:glyphsrasterizationmode:","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMOfflineRegionGeometryDefinition\/initWithStyleURL:geometry:minZoom:maxZoom:pixelRatio:glyphsRasterizationMode:","role":"symbol","kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/objc(pl)NSObject":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MBMOfflineRegionGeometryDefinition"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MBMOfflineRegionGeometryDefinition"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MBMOfflineRegionGeometryDefinition"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMOfflineRegionGeometryDefinition\/geometry","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionGeometryDefinition\/glyphsRasterizationMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionGeometryDefinition\/maxZoom","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionGeometryDefinition\/minZoom","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionGeometryDefinition\/pixelRatio","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionGeometryDefinition\/styleURL"]},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMOfflineRegionGeometryDefinition\/initWithStyleURL:geometry:minZoom:maxZoom:pixelRatio:glyphsRasterizationMode:"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"type":"inheritsFrom"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegion","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionManager","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionTilePyramidDefinition","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionStatus","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadProgressCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionDownloadState","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionErrorType"],"generated":true,"anchor":"Deprecated","title":"Deprecated"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBMOfflineRegionGeometryDefinition"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionGeometryDefinition~1styleURL\/title","value":"styleURL"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionGeometryDefinition~1styleURL\/fragments","value":[{"text":"styleURL","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionError\/title","value":"MBMOfflineRegionError"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionError\/fragments","value":[{"text":"MBMOfflineRegionError","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionError\/navigatorTitle","value":[{"kind":"identifier","text":"MBMOfflineRegionError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionGeometryDefinition~1maxZoom\/title","value":"maxZoom"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionGeometryDefinition~1maxZoom\/fragments","value":[{"text":"maxZoom","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionGeometryDefinition~1pixelRatio\/title","value":"pixelRatio"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionGeometryDefinition~1pixelRatio\/fragments","value":[{"text":"pixelRatio","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionGeometryDefinition\/title","value":"MBMOfflineRegionGeometryDefinition"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionGeometryDefinition\/fragments","value":[{"kind":"identifier","text":"MBMOfflineRegionGeometryDefinition"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionGeometryDefinition\/navigatorTitle","value":[{"text":"MBMOfflineRegionGeometryDefinition","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionTilePyramidDefinition\/title","value":"MBMOfflineRegionTilePyramidDefinition"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionTilePyramidDefinition\/fragments","value":[{"text":"MBMOfflineRegionTilePyramidDefinition","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionTilePyramidDefinition\/navigatorTitle","value":[{"kind":"identifier","text":"MBMOfflineRegionTilePyramidDefinition"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionManager\/title","value":"MBMOfflineRegionManager"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionManager\/fragments","value":[{"kind":"identifier","text":"MBMOfflineRegionManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionManager\/navigatorTitle","value":[{"text":"MBMOfflineRegionManager","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionStatus\/title","value":"MBMOfflineRegionStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionStatus\/fragments","value":[{"kind":"identifier","text":"MBMOfflineRegionStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionStatus\/navigatorTitle","value":[{"kind":"identifier","text":"MBMOfflineRegionStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionErrorType\/title","value":"MBMOfflineRegionErrorType"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionErrorType\/fragments","value":[{"text":"MBMOfflineRegionErrorType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionErrorType\/navigatorTitle","value":[{"kind":"identifier","text":"MBMOfflineRegionErrorType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegion\/title","value":"MBMOfflineRegion"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegion\/fragments","value":[{"text":"MBMOfflineRegion","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegion\/navigatorTitle","value":[{"text":"MBMOfflineRegion","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadProgressCallback\/title","value":"MBMStylePackLoadProgressCallback"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadProgressCallback\/fragments","value":[{"text":"MBMStylePackLoadProgressCallback","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadProgressCallback\/navigatorTitle","value":[{"text":"MBMStylePackLoadProgressCallback","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionObserver\/title","value":"MBMOfflineRegionObserver"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionObserver\/fragments","value":[{"kind":"identifier","text":"MBMOfflineRegionObserver"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionObserver\/navigatorTitle","value":[{"text":"MBMOfflineRegionObserver","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionDownloadState\/title","value":"MBMOfflineRegionDownloadState"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionDownloadState\/fragments","value":[{"kind":"identifier","text":"MBMOfflineRegionDownloadState"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionDownloadState\/navigatorTitle","value":[{"kind":"identifier","text":"MBMOfflineRegionDownloadState"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionGeometryDefinition~1glyphsRasterizationMode\/title","value":"glyphsRasterizationMode"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionGeometryDefinition~1glyphsRasterizationMode\/fragments","value":[{"kind":"identifier","text":"glyphsRasterizationMode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionGeometryDefinition~1minZoom\/title","value":"minZoom"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionGeometryDefinition~1minZoom\/fragments","value":[{"kind":"identifier","text":"minZoom"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}