{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinished\/timeInterval"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"timeInterval","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMEventTimeInterval","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/EventTimeInterval","kind":"typeIdentifier","text":"EventTimeInterval"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinished"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"timeInterval.begin"},{"text":" is when the ","type":"text"},{"code":"map","type":"codeVoice"},{"type":"text","text":" started rendering the frame, and"},{"type":"text","text":" "},{"type":"codeVoice","code":"timeInterval.end"},{"text":" is when the frame was rendered.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/renderframefinished\/timeinterval"]},{"paths":["\/documentation\/mapboxmaps\/renderframefinished\/timeinterval"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"metadata":{"role":"symbol","externalID":"c:objc(cs)MBMRenderFrameFinished(py)timeInterval","modules":[{"name":"MapboxMaps"}],"title":"timeInterval","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"timeInterval"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"timeInterval","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMEventTimeInterval","kind":"typeIdentifier","text":"EventTimeInterval"}]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderFrameFinished/timeInterval":{"kind":"symbol","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"timeInterval.begin"},{"text":" is when the ","type":"text"},{"type":"codeVoice","code":"map"},{"type":"text","text":" started rendering the frame, and"},{"type":"text","text":" "},{"type":"codeVoice","code":"timeInterval.end"},{"text":" is when the frame was rendered.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"timeInterval"},{"text":": ","kind":"text"},{"text":"EventTimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMEventTimeInterval"}],"type":"topic","url":"\/documentation\/mapboxmaps\/renderframefinished\/timeinterval","role":"symbol","title":"timeInterval","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinished\/timeInterval","navigatorTitle":[{"kind":"identifier","text":"timeInterval"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderFrameFinished":{"navigatorTitle":[{"text":"RenderFrameFinished","kind":"identifier"}],"type":"topic","title":"RenderFrameFinished","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinished","url":"\/documentation\/mapboxmaps\/renderframefinished","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RenderFrameFinished","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The "},{"code":"map","type":"codeVoice"},{"type":"text","text":" finished rendering a frame."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","kind":"symbol","title":"MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/EventTimeInterval":{"abstract":[{"type":"text","text":"The time interval of an event. The "},{"type":"codeVoice","code":"begin"},{"text":" property represents the time","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"origin of an event, and the "},{"type":"codeVoice","code":"end"},{"type":"text","text":" property represents the time when the particular"},{"type":"text","text":" "},{"type":"text","text":"operation is complete. The timestamps are sampled at the origin and do not include"},{"text":" ","type":"text"},{"type":"text","text":"the time required to dispatch an event."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EventTimeInterval"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/EventTimeInterval","url":"\/documentation\/mapboxmaps\/eventtimeinterval","kind":"symbol","navigatorTitle":[{"text":"EventTimeInterval","kind":"identifier"}],"title":"EventTimeInterval"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"type":"topic","abstract":[{"type":"text","text":"The simplified diagram of the events emitted by the map is displayed below."}],"role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","kind":"article","url":"\/documentation\/mapboxmaps\/events","title":"Map events"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","url":"\/documentation\/overview","abstract":[],"kind":"article","title":"MapboxMaps Documentation","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"timeInterval","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"timeInterval","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)MBMEventTimeInterval","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/EventTimeInterval","kind":"typeIdentifier","text":"MBMEventTimeInterval"},{"kind":"text","text":" * "},{"kind":"identifier","text":"timeInterval"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinished~1timeInterval\/title","op":"replace","value":"timeInterval"},{"value":[{"text":"timeInterval","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinished~1timeInterval\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinished\/title","value":"MBMRenderFrameFinished","op":"replace"},{"op":"replace","value":[{"text":"MBMRenderFrameFinished","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinished\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinished\/navigatorTitle","value":[{"kind":"identifier","text":"MBMRenderFrameFinished"}]},{"op":"replace","value":"MBMEventTimeInterval","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1EventTimeInterval\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1EventTimeInterval\/fragments","value":[{"text":"MBMEventTimeInterval","kind":"identifier"}]},{"value":[{"text":"MBMEventTimeInterval","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1EventTimeInterval\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}