{"variants":[{"paths":["\/documentation\/mapboxmaps\/mbmmapoptions\/initwithcontextmode:constrainmode:viewportmode:orientation:crosssourcecollisions:size:pixelratio:glyphsrasterizationoptions:"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-View","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapOptions"]]},"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"initWithContextMode:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"contextMode"},{"kind":"text","text":" "},{"text":"constrainMode:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"constrainMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewportMode:"},{"text":"(","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"viewportMode"},{"text":" ","kind":"text"},{"text":"orientation:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"orientation","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"crossSourceCollisions:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"crossSourceCollisions"},{"kind":"text","text":" "},{"kind":"identifier","text":"size:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMSize","text":"MBMSize","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Size"},{"kind":"text","text":" *) "},{"text":"size","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pixelRatio:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"float","preciseIdentifier":"c:f"},{"kind":"text","text":") "},{"kind":"internalParam","text":"pixelRatio"},{"text":" ","kind":"text"},{"kind":"identifier","text":"glyphsRasterizationOptions:"},{"text":"(","kind":"text"},{"text":"MBMGlyphsRasterizationOptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationOptions","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMGlyphsRasterizationOptions"},{"kind":"text","text":" *) "},{"text":"glyphsRasterizationOptions","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapOptions\/initWithContextMode:constrainMode:viewportMode:orientation:crossSourceCollisions:size:pixelRatio:glyphsRasterizationOptions:","interfaceLanguage":"occ"},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"text":"initWithContextMode:constrainMode:viewportMode:orientation:crossSourceCollisions:size:pixelRatio:glyphsRasterizationOptions:","kind":"identifier"}],"externalID":"c:objc(cs)MBMMapOptions(im)initWithContextMode:constrainMode:viewportMode:orientation:crossSourceCollisions:size:pixelRatio:glyphsRasterizationOptions:","navigatorTitle":[{"text":"initWithContextMode:constrainMode:viewportMode:orientation:crossSourceCollisions:size:pixelRatio:glyphsRasterizationOptions:","kind":"identifier"}],"title":"initWithContextMode:constrainMode:viewportMode:orientation:crossSourceCollisions:size:pixelRatio:glyphsRasterizationOptions:","modules":[{"name":"MapboxMaps"}],"role":"symbol","roleHeading":"Instance Method"},"kind":"symbol","sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapOptions":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapOptions"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MapOptions"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Describes the map option values."}],"url":"\/documentation\/mapboxmaps\/mapoptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapOptions","title":"MapOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"title":"MapboxMaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMMapOptions/initWithContextMode:constrainMode:viewportMode:orientation:crossSourceCollisions:size:pixelRatio:glyphsRasterizationOptions:":{"type":"topic","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithContextMode:constrainMode:viewportMode:orientation:crossSourceCollisions:size:pixelRatio:glyphsRasterizationOptions:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithContextMode:constrainMode:viewportMode:orientation:crossSourceCollisions:size:pixelRatio:glyphsRasterizationOptions:","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapOptions\/initWithContextMode:constrainMode:viewportMode:orientation:crossSourceCollisions:size:pixelRatio:glyphsRasterizationOptions:","url":"\/documentation\/mapboxmaps\/mbmmapoptions\/initwithcontextmode:constrainmode:viewportmode:orientation:crosssourcecollisions:size:pixelratio:glyphsrasterizationoptions:","title":"initWithContextMode:constrainMode:viewportMode:orientation:crossSourceCollisions:size:pixelRatio:glyphsRasterizationOptions:","kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","kind":"article","role":"collection","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map-View":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-View","url":"\/documentation\/mapboxmaps\/map-view","role":"collectionGroup","type":"topic","abstract":[],"kind":"article","title":"MapView"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GlyphsRasterizationOptions":{"title":"GlyphsRasterizationOptions","navigatorTitle":[{"text":"GlyphsRasterizationOptions","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationOptions","url":"\/documentation\/mapboxmaps\/glyphsrasterizationoptions","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GlyphsRasterizationOptions","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Describes the glyphs rasterization option values."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Size":{"title":"Size","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Size","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"Size","kind":"identifier"}],"type":"topic","abstract":[{"text":"Size type.","type":"text"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/size","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Size"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapOptions\/title","value":"MBMMapOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapOptions\/fragments","value":[{"text":"MBMMapOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapOptions\/navigatorTitle","value":[{"text":"MBMMapOptions","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationOptions\/title","op":"replace","value":"MBMGlyphsRasterizationOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationOptions\/fragments","value":[{"kind":"identifier","text":"MBMGlyphsRasterizationOptions"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationOptions\/navigatorTitle","value":[{"kind":"identifier","text":"MBMGlyphsRasterizationOptions"}],"op":"replace"},{"value":"MBMSize","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Size\/title","op":"replace"},{"value":[{"text":"MBMSize","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Size\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Size\/navigatorTitle","value":[{"kind":"identifier","text":"MBMSize"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}