{"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fromCustomRasterSourceTileRenderer"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"value"},{"text":": any ","kind":"text"},{"text":"CustomRasterSourceTileRenderer","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MBMCustomRasterSourceTileRenderer"},{"text":") -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/customrastersourceclient\/fromcustomrastersourcetilerenderer(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/customrastersourceclient\/fromcustomrastersourcetilerenderer(_:)"]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient\/fromCustomRasterSourceTileRenderer(_:)","interfaceLanguage":"swift"},"metadata":{"title":"fromCustomRasterSourceTileRenderer(_:)","symbolKind":"method","externalID":"c:objc(cs)MBMCustomRasterSourceClient(cm)fromCustomRasterSourceTileRenderer:","roleHeading":"Type Method","modules":[{"name":"MapboxMaps"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fromCustomRasterSourceTileRenderer","kind":"identifier"},{"kind":"text","text":"(any "},{"text":"CustomRasterSourceTileRenderer","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MBMCustomRasterSourceTileRenderer"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Self"}],"navigatorTitle":[{"text":"fromCustomRasterSourceTileRenderer:","kind":"identifier"}],"role":"symbol"},"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileRenderer":{"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"CustomRasterSourceTileRenderer","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"CustomRasterSourceTileRenderer","kind":"identifier"}],"title":"CustomRasterSourceTileRenderer","abstract":[{"text":"Interface for the direct rendering into the custom raster tiles.","type":"text"}],"url":"\/documentation\/mapboxmaps\/customrastersourcetilerenderer","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceClient":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient","type":"topic","url":"\/documentation\/mapboxmaps\/customrastersourceclient","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomRasterSourceClient"}],"navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceClient"}],"kind":"symbol","abstract":[],"role":"symbol","title":"CustomRasterSourceClient"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Sources":{"kind":"article","type":"topic","abstract":[],"url":"\/documentation\/mapboxmaps\/sources","title":"Sources","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceClient/fromCustomRasterSourceTileRenderer(_:)":{"url":"\/documentation\/mapboxmaps\/customrastersourceclient\/fromcustomrastersourcetilerenderer(_:)","kind":"symbol","abstract":[],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient\/fromCustomRasterSourceTileRenderer(_:)","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fromCustomRasterSourceTileRenderer","kind":"identifier"},{"text":"(any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)MBMCustomRasterSourceTileRenderer","text":"CustomRasterSourceTileRenderer","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Self","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"fromCustomRasterSourceTileRenderer:","kind":"identifier"}],"title":"fromCustomRasterSourceTileRenderer(_:)"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","abstract":[],"kind":"article","role":"collection","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/mapboxmaps","title":"MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"fromCustomRasterSourceTileRenderer:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"fromCustomRasterSourceTileRenderer:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"fromCustomRasterSourceTileRenderer:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)MBMCustomRasterSourceTileRenderer","text":"id<MBMCustomRasterSourceTileRenderer>"},{"kind":"text","text":") "},{"text":"value","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"MBMCustomRasterSourceTileRenderer","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer\/fragments","value":[{"text":"MBMCustomRasterSourceTileRenderer","kind":"identifier"}]},{"op":"replace","value":[{"text":"MBMCustomRasterSourceTileRenderer","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient\/title","value":"MBMCustomRasterSourceClient"},{"value":[{"text":"MBMCustomRasterSourceClient","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient\/fragments"},{"value":[{"kind":"identifier","text":"MBMCustomRasterSourceClient"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient~1fromCustomRasterSourceTileRenderer(_:)\/title","value":"fromCustomRasterSourceTileRenderer:"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient~1fromCustomRasterSourceTileRenderer(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"fromCustomRasterSourceTileRenderer:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}