{"kind":"symbol","variants":[{"paths":["\/documentation\/mapboxcommon\/httpservicefactory\/setmaxrequestsperhostformax(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxcommon\/httpservicefactory\/setmaxrequestsperhostformax(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"text":"Set maximum number of requests to a single host for the current HTTP service instance.","type":"text"}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceFactory\/setMaxRequestsPerHostForMax(_:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceFactory"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMaxRequestsPerHostForMax"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"max"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V","text":"UInt8"},{"kind":"text","text":")"}]}]},{"kind":"parameters","parameters":[{"name":"max","content":[{"inlineContent":[{"text":"Maximum number of requests.","type":"text"}],"type":"paragraph"}]}]},{"content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Default value for cURL is 0 (which means unlimited)"},{"type":"text","text":" "},{"type":"text","text":"Default value for OkHttp is unspecified"},{"type":"text","text":" "},{"type":"text","text":"Default value for NSURLSession is 8"}]}],"kind":"content"}],"metadata":{"modules":[{"name":"MapboxCommon"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setMaxRequestsPerHostForMax","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UInt8","kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"setMaxRequestsPerHostForMax:","kind":"identifier"}],"roleHeading":"Type Method","externalID":"c:objc(cs)MBXHttpServiceFactory(cm)setMaxRequestsPerHostForMax:","symbolKind":"method","title":"setMaxRequestsPerHostForMax(_:)","role":"symbol"},"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","abstract":[],"type":"topic","title":"MapboxMaps Documentation","kind":"article","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpServiceFactory/setMaxRequestsPerHostForMax(_:)":{"navigatorTitle":[{"text":"setMaxRequestsPerHostForMax:","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Set maximum number of requests to a single host for the current HTTP service instance.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceFactory\/setMaxRequestsPerHostForMax(_:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setMaxRequestsPerHostForMax","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UInt8","kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","title":"setMaxRequestsPerHostForMax(_:)","url":"\/documentation\/mapboxcommon\/httpservicefactory\/setmaxrequestsperhostformax(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpServiceFactory":{"role":"symbol","navigatorTitle":[{"text":"HttpServiceFactory","kind":"identifier"}],"abstract":[{"type":"text","text":"HTTP service factory."}],"url":"\/documentation\/mapboxcommon\/httpservicefactory","title":"HttpServiceFactory","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceFactory","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HttpServiceFactory","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"url":"\/documentation\/mapboxcommon","role":"collection","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","type":"topic","abstract":[],"title":"MapboxCommon"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"setMaxRequestsPerHostForMax:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setMaxRequestsPerHostForMax:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"setMaxRequestsPerHostForMax:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"uint8_t","preciseIdentifier":"c:@T@uint8_t"},{"kind":"text","text":") "},{"kind":"internalParam","text":"max"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"max","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Maximum number of requests."}]}]}]},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"setMaxRequestsPerHostForMax:","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceFactory~1setMaxRequestsPerHostForMax(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceFactory~1setMaxRequestsPerHostForMax(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"setMaxRequestsPerHostForMax:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceFactory\/title","value":"MBXHttpServiceFactory"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceFactory\/fragments","value":[{"kind":"identifier","text":"MBXHttpServiceFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceFactory\/navigatorTitle","value":[{"kind":"identifier","text":"MBXHttpServiceFactory"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}