{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/offlineregiontilepyramiddefinition\/glyphsrasterizationmode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/offlineregiontilepyramiddefinition\/glyphsrasterizationmode"]}],"metadata":{"modules":[{"name":"MapboxMaps"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"glyphsRasterizationMode","kind":"identifier"}],"platforms":[],"role":"symbol","title":"glyphsRasterizationMode","externalID":"c:objc(cs)MBMOfflineRegionTilePyramidDefinition(py)glyphsRasterizationMode","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"glyphsRasterizationMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GlyphsRasterizationMode","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMGlyphsRasterizationMode"}]},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionTilePyramidDefinition\/glyphsRasterizationMode","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionTilePyramidDefinition"]]},"abstract":[{"text":"Specifies glyphs download mode.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"glyphsRasterizationMode","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode","preciseIdentifier":"c:@E@MBMGlyphsRasterizationMode","text":"GlyphsRasterizationMode","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMaps":{"type":"topic","kind":"article","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","title":"Core Maps API","url":"\/documentation\/mapboxmaps\/coremaps","abstract":[{"type":"text","text":"Maps rendering SDK also known as GL-Native"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Offline":{"url":"\/documentation\/mapboxmaps\/offline","type":"topic","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","title":"Offline Support","kind":"article","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionTilePyramidDefinition/glyphsRasterizationMode":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionTilePyramidDefinition\/glyphsRasterizationMode","title":"glyphsRasterizationMode","navigatorTitle":[{"kind":"identifier","text":"glyphsRasterizationMode"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"glyphsRasterizationMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMGlyphsRasterizationMode","text":"GlyphsRasterizationMode"}],"abstract":[{"text":"Specifies glyphs download mode.","type":"text"}],"type":"topic","deprecated":true,"url":"\/documentation\/mapboxmaps\/offlineregiontilepyramiddefinition\/glyphsrasterizationmode","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionTilePyramidDefinition":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OfflineRegionTilePyramidDefinition"}],"type":"topic","kind":"symbol","role":"symbol","title":"OfflineRegionTilePyramidDefinition","deprecated":true,"url":"\/documentation\/mapboxmaps\/offlineregiontilepyramiddefinition","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionTilePyramidDefinition","navigatorTitle":[{"kind":"identifier","text":"OfflineRegionTilePyramidDefinition"}],"abstract":[{"type":"text","text":"An offline region definition is a geographic region defined by a style URL,"},{"type":"text","text":" "},{"type":"text","text":"geographic bounding box, zoom range, and device pixel ratio. Both "},{"type":"codeVoice","code":"minZoom"},{"type":"text","text":" and "},{"code":"maxZoom","type":"codeVoice"},{"text":" must be ≥ 0,","type":"text"},{"text":" ","type":"text"},{"text":"and ","type":"text"},{"code":"maxZoom","type":"codeVoice"},{"text":" must be ≥ ","type":"text"},{"code":"minZoom","type":"codeVoice"},{"text":". The ","type":"text"},{"code":"maxZoom","type":"codeVoice"},{"text":" may be ∞, in which case for each tile source,","type":"text"},{"text":" ","type":"text"},{"text":"the region will include tiles from ","type":"text"},{"code":"minZoom","type":"codeVoice"},{"text":" up to the maximum zoom level provided by that source.","type":"text"},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"code":"pixelRatio","type":"codeVoice"},{"text":" must be ≥ 0 and should typically be 1.0 or 2.0.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GlyphsRasterizationMode":{"navigatorTitle":[{"text":"GlyphsRasterizationMode","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode","title":"GlyphsRasterizationMode","role":"symbol","url":"\/documentation\/mapboxmaps\/glyphsrasterizationmode","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GlyphsRasterizationMode","kind":"identifier"}],"abstract":[{"type":"text","text":"Describes glyphs rasterization modes."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","kind":"symbol","type":"topic","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","type":"topic","abstract":[],"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","url":"\/documentation\/overview"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"glyphsRasterizationMode","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"glyphsRasterizationMode","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"MBMGlyphsRasterizationMode","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMGlyphsRasterizationMode"},{"text":" ","kind":"text"},{"text":"glyphsRasterizationMode","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionTilePyramidDefinition~1glyphsRasterizationMode\/title","value":"glyphsRasterizationMode","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionTilePyramidDefinition~1glyphsRasterizationMode\/fragments","value":[{"kind":"identifier","text":"glyphsRasterizationMode"}],"op":"replace"},{"value":"MBMOfflineRegionTilePyramidDefinition","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionTilePyramidDefinition\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MBMOfflineRegionTilePyramidDefinition"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionTilePyramidDefinition\/fragments","op":"replace"},{"value":[{"text":"MBMOfflineRegionTilePyramidDefinition","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionTilePyramidDefinition\/navigatorTitle","op":"replace"},{"value":"MBMGlyphsRasterizationMode","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MBMGlyphsRasterizationMode"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MBMGlyphsRasterizationMode"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}