{"metadata":{"role":"symbol","symbolKind":"case","externalID":"c:@E@MBMMapDebugOptions@MBMMapDebugOptionsDepthBuffer","modules":[{"name":"MapboxMaps"}],"title":"MapDebugOptions.depthBuffer","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"depthBuffer","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MBMMapDebugOptionsDepthBuffer"}]},"sections":[],"variants":[{"paths":["\/documentation\/mapboxmaps\/mapdebugoptions\/depthbuffer"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/mapdebugoptions\/depthbuffer"]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/depthBuffer","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"depthBuffer","kind":"identifier"}]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"The depth buffer is shown instead of the color buffer."}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Performance":{"abstract":[],"kind":"article","url":"\/documentation\/mapboxmaps\/performance","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","role":"collectionGroup","type":"topic","title":"Performance and investigations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapDebugOptions/depthBuffer":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"depthBuffer"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/depthBuffer","navigatorTitle":[{"text":"MBMMapDebugOptionsDepthBuffer","kind":"identifier"}],"title":"MapDebugOptions.depthBuffer","kind":"symbol","url":"\/documentation\/mapboxmaps\/mapdebugoptions\/depthbuffer","type":"topic","abstract":[{"type":"text","text":"The depth buffer is shown instead of the color buffer."}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","url":"\/documentation\/overview","title":"MapboxMaps Documentation","abstract":[],"kind":"article","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","title":"MapboxMaps","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapDebugOptions":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapDebugOptions","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions","title":"MapDebugOptions","abstract":[{"text":"Options for enabling debugging features in a map.","type":"text"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"MapDebugOptions","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/mapdebugoptions"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MBMMapDebugOptionsDepthBuffer"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MBMMapDebugOptionsDepthBuffer"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"MBMMapDebugOptionsDepthBuffer"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions~1depthBuffer\/title","value":"MBMMapDebugOptionsDepthBuffer","op":"replace"},{"value":[{"kind":"identifier","text":"MBMMapDebugOptionsDepthBuffer"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions~1depthBuffer\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions\/title","value":"MBMMapDebugOptions"},{"op":"replace","value":[{"text":"MBMMapDebugOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMMapDebugOptions"}]}]}]}