{"metadata":{"role":"symbol","symbolKind":"typealias","title":"TileRegionEstimateProgressCallback","roleHeading":"Type Alias","modules":[{"name":"MapboxCommon"}],"externalID":"c:MBXTileRegionEstimateProgressCallback.h@T@MBXTileRegionEstimateProgressCallback","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileRegionEstimateProgressCallback","kind":"identifier"}],"navigatorTitle":[{"text":"TileRegionEstimateProgressCallback","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgressCallback"},"variants":[{"paths":["\/documentation\/mapboxcommon\/tileregionestimateprogresscallback"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxcommon\/tileregionestimateprogresscallback"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs"]]},"seeAlsoSections":[{"title":"TileStore","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStoreOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudget","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInMegabytes","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInTiles","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCoverOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegion","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileRegionError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgress","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TilesetDescriptor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TilesetDescriptorOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgressCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreUsageMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileRegionError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileDataDomain","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgress","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateResult","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingErrorType"],"anchor":"TileStore","generated":true}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TileRegionEstimateProgressCallback"},{"kind":"text","text":" = ("},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgress","text":"TileRegionEstimateProgress","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXTileRegionEstimateProgress"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegion":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegion","url":"\/documentation\/mapboxcommon\/tileregion","navigatorTitle":[{"text":"TileRegion","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileRegion","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"TileRegion represents an identifiable geographic tile region with metadata","type":"text"}],"title":"TileRegion"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudgetInTiles":{"url":"\/documentation\/mapboxmaps\/tilecachebudgetintiles","type":"topic","role":"symbol","abstract":[{"text":"Tile cache budget in tiles.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileCacheBudgetInTiles","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"TileCacheBudgetInTiles"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInTiles","title":"TileCacheBudgetInTiles","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileStoreOptions":{"url":"\/documentation\/mapboxcommon\/tilestoreoptions","type":"topic","role":"symbol","abstract":[{"type":"text","text":"These constants can be used as keys for TileStore::setOption to configure further aspects of a TileStore instance."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TileStoreOptions","kind":"identifier"}],"navigatorTitle":[{"text":"TileStoreOptions","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStoreOptions","title":"TileStoreOptions","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudgetType":{"url":"\/documentation\/mapboxmaps\/tilecachebudgettype","type":"topic","role":"symbol","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileCacheBudgetType","kind":"identifier"}],"navigatorTitle":[{"text":"TileCacheBudgetType","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetType","title":"TileCacheBudgetType","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileRegionError":{"type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/tileregionerror","navigatorTitle":[{"text":"TileRegionError","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Describes the reason for a tile region download request failure.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TileRegionError","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileRegionError","title":"TileRegionError"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileStore":{"url":"\/documentation\/mapboxcommon\/tilestore","type":"topic","role":"symbol","abstract":[{"type":"text","text":"TileStore manages downloads and storage for requests to tile-related API endpoints, enforcing a disk usage"},{"type":"text","text":" "},{"text":"quota: tiles available on disk may be deleted to make room for a new download. This interface can be used by an","type":"text"},{"type":"text","text":" "},{"type":"text","text":"app developer to set the disk quota. The rest of TileStore API is intended for native SDK consumption only."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TileStore","kind":"identifier"}],"navigatorTitle":[{"text":"TileStore","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore","title":"TileStore","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadProgressCallback":{"url":"\/documentation\/mapboxcommon\/tileregionloadprogresscallback","type":"topic","role":"symbol","abstract":[{"text":"Callback Invoked to report the progess of the tile region loading operation.","type":"text"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileRegionLoadProgressCallback","kind":"identifier"}],"navigatorTitle":[{"text":"TileRegionLoadProgressCallback","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgressCallback","title":"TileRegionLoadProgressCallback","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateProgress":{"abstract":[{"type":"text","text":"A tile region’s estimate progress includes counts of the number of resources that have"},{"text":" ","type":"text"},{"type":"text","text":"been estimated and the total number of resources as well as a partial result with the"},{"text":" ","type":"text"},{"text":"current estimate, calculated using the data available at the moment.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"TileRegionEstimateProgress","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgress","title":"TileRegionEstimateProgress","url":"\/documentation\/mapboxcommon\/tileregionestimateprogress","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TileRegionEstimateProgress","kind":"identifier"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","role":"collection","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","kind":"symbol","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudgetInMegabytes":{"url":"\/documentation\/mapboxmaps\/tilecachebudgetinmegabytes","type":"topic","role":"symbol","abstract":[{"text":"Tile cache budget in megabytes.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileCacheBudgetInMegabytes","kind":"identifier"}],"navigatorTitle":[{"text":"TileCacheBudgetInMegabytes","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInMegabytes","title":"TileCacheBudgetInMegabytes","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"role":"collection","type":"topic","title":"MapboxMaps Documentation","url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"url":"\/documentation\/mapboxmaps\/tilestore-apis","kind":"article","title":"TileStore APIs","role":"collectionGroup","abstract":[],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStoreUsageMode":{"url":"\/documentation\/mapboxmaps\/tilestoreusagemode","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Describes tile store usage modes."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"TileStoreUsageMode","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"TileStoreUsageMode"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreUsageMode","title":"TileStoreUsageMode","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCoverOptions":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCoverOptions","tags":[{"text":"SPI","type":"spi"}],"url":"\/documentation\/mapboxmaps\/tilecoveroptions","navigatorTitle":[{"text":"TileCoverOptions","kind":"identifier"}],"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileCoverOptions","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Various options needed for tile cover.","type":"text"}],"title":"TileCoverOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadProgress":{"abstract":[{"text":"A tile region’s load progress includes counts","type":"text"},{"text":" ","type":"text"},{"text":"of the number of resources that have completed downloading","type":"text"},{"type":"text","text":" "},{"text":"and the total number of resources that are required.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TileRegionLoadProgress","kind":"identifier"}],"title":"TileRegionLoadProgress","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgress","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TileRegionLoadProgress"}],"role":"symbol","url":"\/documentation\/mapboxcommon\/tileregionloadprogress"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateOptions":{"type":"topic","role":"symbol","url":"\/documentation\/mapboxcommon\/tileregionestimateoptions","navigatorTitle":[{"kind":"identifier","text":"TileRegionEstimateOptions"}],"kind":"symbol","abstract":[{"text":"Holds options for the tile region estimation operation.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TileRegionEstimateOptions","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateOptions","title":"TileRegionEstimateOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadOptions":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions","url":"\/documentation\/mapboxcommon\/tileregionloadoptions","navigatorTitle":[{"text":"TileRegionLoadOptions","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileRegionLoadOptions","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Describes the tile region load option values.","type":"text"}],"title":"TileRegionLoadOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileOptions":{"url":"\/documentation\/mapboxmaps\/tileoptions","type":"topic","role":"symbol","abstract":[{"text":"Options for custom geometry tiles.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileOptions","kind":"identifier"}],"navigatorTitle":[{"text":"TileOptions","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileOptions","title":"TileOptions","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TilesetDescriptor":{"type":"topic","role":"symbol","url":"\/documentation\/mapboxcommon\/tilesetdescriptor","navigatorTitle":[{"text":"TilesetDescriptor","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"A bundle that encapsulates tilesets creation for the tile store implementation."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TilesetDescriptor"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TilesetDescriptor","title":"TilesetDescriptor"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileDataDomain":{"type":"topic","role":"symbol","url":"\/documentation\/mapboxcommon\/tiledatadomain","navigatorTitle":[{"text":"TileDataDomain","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Describes the tiles data domain.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileDataDomain","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileDataDomain","title":"TileDataDomain"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStoreObserver":{"type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/tilestoreobserver","navigatorTitle":[{"text":"TileStoreObserver","kind":"identifier"}],"kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"TileStoreObserver","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreObserver","title":"TileStoreObserver"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateProgressCallback":{"url":"\/documentation\/mapboxcommon\/tileregionestimateprogresscallback","type":"topic","role":"symbol","abstract":[],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileRegionEstimateProgressCallback","kind":"identifier"}],"navigatorTitle":[{"text":"TileRegionEstimateProgressCallback","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgressCallback","title":"TileRegionEstimateProgressCallback","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CanonicalTileID":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Represents a tile coordinate."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID","navigatorTitle":[{"kind":"identifier","text":"CanonicalTileID"}],"title":"CanonicalTileID","role":"symbol","url":"\/documentation\/mapboxmaps\/canonicaltileid","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CanonicalTileID"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateResult":{"abstract":[{"text":"The result of tile region estim","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"TileRegionEstimateResult","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateResult","title":"TileRegionEstimateResult","url":"\/documentation\/mapboxcommon\/tileregionestimateresult","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TileRegionEstimateResult"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/CacheClearingError":{"url":"\/documentation\/mapboxcommon\/cacheclearingerror","type":"topic","role":"symbol","abstract":[{"text":"Describes a cache clearing error.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CacheClearingError","kind":"identifier"}],"navigatorTitle":[{"text":"CacheClearingError","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingError","title":"CacheClearingError","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudget":{"type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/tilecachebudget","navigatorTitle":[{"text":"TileCacheBudget","kind":"identifier"}],"kind":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileCacheBudget","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudget","title":"TileCacheBudget"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/CacheClearingErrorType":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingErrorType","url":"\/documentation\/mapboxcommon\/cacheclearingerrortype","navigatorTitle":[{"text":"CacheClearingErrorType","kind":"identifier"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CacheClearingErrorType","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Describes the reason for a cache clearing failure.","type":"text"}],"title":"CacheClearingErrorType"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TilesetDescriptorOptions":{"type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/tilesetdescriptoroptions","navigatorTitle":[{"text":"TilesetDescriptorOptions","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Describes the tileset descriptor option values.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TilesetDescriptorOptions","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TilesetDescriptorOptions","title":"TilesetDescriptorOptions"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Alias","op":"replace"},{"path":"\/metadata\/title","value":"MBXTileRegionEstimateProgressCallback","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"typealias"},{"value":[{"kind":"identifier","text":"MBXTileRegionEstimateProgressCallback"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"MBXTileRegionEstimateProgressCallback","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStoreOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudget","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInMegabytes","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInTiles","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegion","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgress","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TilesetDescriptor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TilesetDescriptorOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgressCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreUsageMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileDataDomain","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgress","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateResult","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingErrorType"],"generated":true,"anchor":"TileStore","title":"TileStore"}],"path":"\/seeAlsoSections","op":"replace"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"text":"void (^)(MBXTileRegionEstimateProgress *)","kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$objc(cs)MBXTileRegionEstimateProgress)"},{"text":" ","kind":"text"},{"text":"MBXTileRegionEstimateProgressCallback","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegion\/title","value":"MBXTileRegion","op":"replace"},{"op":"replace","value":[{"text":"MBXTileRegion","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegion\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegion\/navigatorTitle","op":"replace","value":[{"text":"MBXTileRegion","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInTiles\/title","value":"MBMTileCacheBudgetInTiles"},{"value":[{"kind":"identifier","text":"MBMTileCacheBudgetInTiles"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInTiles\/fragments","op":"replace"},{"value":[{"text":"MBMTileCacheBudgetInTiles","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInTiles\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStoreOptions\/title","value":"MBXTileStoreOptions","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStoreOptions\/fragments","value":[{"kind":"identifier","text":"MBXTileStoreOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStoreOptions\/navigatorTitle","value":[{"kind":"identifier","text":"MBXTileStoreOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetType\/title","value":"MBMTileCacheBudgetType"},{"value":[{"kind":"identifier","text":"MBMTileCacheBudgetType"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetType\/navigatorTitle","value":[{"kind":"identifier","text":"MBMTileCacheBudgetType"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/title","op":"replace","value":"MBXTileStore"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/fragments","op":"replace","value":[{"text":"MBXTileStore","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/navigatorTitle","op":"replace","value":[{"text":"MBXTileStore","kind":"identifier"}]},{"op":"replace","value":"MBXTileRegionLoadProgressCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgressCallback\/title"},{"value":[{"text":"MBXTileRegionLoadProgressCallback","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgressCallback\/fragments"},{"op":"replace","value":[{"text":"MBXTileRegionLoadProgressCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgressCallback\/navigatorTitle"},{"op":"replace","value":"MBXTileRegionEstimateProgress","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgress\/title"},{"op":"replace","value":[{"text":"MBXTileRegionEstimateProgress","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgress\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgress\/navigatorTitle","value":[{"text":"MBXTileRegionEstimateProgress","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInMegabytes\/title","op":"replace","value":"MBMTileCacheBudgetInMegabytes"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInMegabytes\/fragments","op":"replace","value":[{"text":"MBMTileCacheBudgetInMegabytes","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInMegabytes\/navigatorTitle","value":[{"kind":"identifier","text":"MBMTileCacheBudgetInMegabytes"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileStoreUsageMode\/title","value":"MBMTileStoreUsageMode","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileStoreUsageMode\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMTileStoreUsageMode"}]},{"op":"replace","value":[{"text":"MBMTileStoreUsageMode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileStoreUsageMode\/navigatorTitle"},{"value":"MBXTileRegionLoadProgress","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgress\/title"},{"value":[{"kind":"identifier","text":"MBXTileRegionLoadProgress"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgress\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgress\/navigatorTitle","value":[{"text":"MBXTileRegionLoadProgress","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateOptions\/title","value":"MBXTileRegionEstimateOptions","op":"replace"},{"value":[{"text":"MBXTileRegionEstimateOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateOptions\/fragments"},{"op":"replace","value":[{"text":"MBXTileRegionEstimateOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateOptions\/navigatorTitle"},{"value":"MBXTileRegionLoadOptions","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/fragments","value":[{"kind":"identifier","text":"MBXTileRegionLoadOptions"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/navigatorTitle","value":[{"text":"MBXTileRegionLoadOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileOptions\/title","value":"MBMTileOptions","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileOptions\/fragments","op":"replace","value":[{"text":"MBMTileOptions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileOptions\/navigatorTitle","value":[{"kind":"identifier","text":"MBMTileOptions"}]},{"value":"MBXTilesetDescriptor","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TilesetDescriptor\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TilesetDescriptor\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXTilesetDescriptor"}]},{"op":"replace","value":[{"text":"MBXTilesetDescriptor","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TilesetDescriptor\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileDataDomain\/title","value":"MBXTileDataDomain"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileDataDomain\/fragments","value":[{"kind":"identifier","text":"MBXTileDataDomain"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileDataDomain\/navigatorTitle","value":[{"kind":"identifier","text":"MBXTileDataDomain"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgressCallback\/title","value":"MBXTileRegionEstimateProgressCallback","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgressCallback\/fragments","value":[{"kind":"identifier","text":"MBXTileRegionEstimateProgressCallback"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgressCallback\/navigatorTitle","value":[{"text":"MBXTileRegionEstimateProgressCallback","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/title","value":"MBMCanonicalTileID"},{"value":[{"text":"MBMCanonicalTileID","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/navigatorTitle","value":[{"text":"MBMCanonicalTileID","kind":"identifier"}]},{"op":"replace","value":"MBXTileRegionEstimateResult","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateResult\/title"},{"value":[{"kind":"identifier","text":"MBXTileRegionEstimateResult"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateResult\/fragments"},{"value":[{"text":"MBXTileRegionEstimateResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateResult\/navigatorTitle"},{"value":"MBXCacheClearingError","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingError\/title"},{"value":[{"kind":"identifier","text":"MBXCacheClearingError"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingError\/fragments","op":"replace"},{"value":[{"text":"MBXCacheClearingError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingError\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudget\/title","value":"MBMTileCacheBudget","op":"replace"},{"op":"replace","value":[{"text":"MBMTileCacheBudget","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudget\/fragments"},{"value":[{"text":"MBMTileCacheBudget","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudget\/navigatorTitle","op":"replace"},{"value":"MBXCacheClearingErrorType","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingErrorType\/title"},{"value":[{"kind":"identifier","text":"MBXCacheClearingErrorType"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingErrorType\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingErrorType\/navigatorTitle","value":[{"text":"MBXCacheClearingErrorType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions\/title","op":"replace","value":"MBMTilesetDescriptorOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions\/fragments","value":[{"text":"MBMTilesetDescriptorOptions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions\/navigatorTitle","value":[{"kind":"identifier","text":"MBMTilesetDescriptorOptions"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}