{"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingError","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"MapboxCommon"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CacheClearingError"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CacheClearingError","kind":"identifier"}],"externalID":"c:objc(cs)MBXCacheClearingError","symbolKind":"class","title":"CacheClearingError","roleHeading":"Class"},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH"],"type":"conformsTo","kind":"relationships"}],"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStoreOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudget","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInMegabytes","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInTiles","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCoverOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegion","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileRegionError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgress","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TilesetDescriptor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TilesetDescriptorOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgressCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreUsageMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileRegionError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileDataDomain","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgress","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateResult","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgressCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingErrorType"],"anchor":"TileStore","title":"TileStore"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CacheClearingError"}],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"Describes a cache clearing error."}],"topicSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingError\/init(type:message:)"],"generated":true,"anchor":"Initializers","title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingError\/message","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingError\/type"],"anchor":"Instance-Properties","generated":true}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs"]]},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/cacheclearingerror"]},{"paths":["\/documentation\/mapboxcommon\/cacheclearingerror"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadProgress":{"title":"TileRegionLoadProgress","kind":"symbol","url":"\/documentation\/mapboxcommon\/tileregionloadprogress","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgress","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TileRegionLoadProgress"}],"navigatorTitle":[{"kind":"identifier","text":"TileRegionLoadProgress"}],"abstract":[{"text":"A tile region’s load progress includes counts","type":"text"},{"type":"text","text":" "},{"text":"of the number of resources that have completed downloading","type":"text"},{"type":"text","text":" "},{"type":"text","text":"and the total number of resources that are required."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CanonicalTileID":{"navigatorTitle":[{"text":"CanonicalTileID","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Represents a tile coordinate.","type":"text"}],"type":"topic","title":"CanonicalTileID","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CanonicalTileID"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID","url":"\/documentation\/mapboxmaps\/canonicaltileid"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/CacheClearingError/message":{"title":"message","role":"symbol","abstract":[{"text":"An error message","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingError\/message","type":"topic","navigatorTitle":[{"text":"message","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"message","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"url":"\/documentation\/mapboxcommon\/cacheclearingerror\/message","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileRegionError":{"type":"topic","title":"TileRegionError","url":"\/documentation\/mapboxmaps\/tileregionerror","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileRegionError","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TileRegionError"}],"abstract":[{"text":"Describes the reason for a tile region download request failure.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileRegionError"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TilesetDescriptor":{"type":"topic","title":"TilesetDescriptor","url":"\/documentation\/mapboxcommon\/tilesetdescriptor","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TilesetDescriptor","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TilesetDescriptor"}],"abstract":[{"type":"text","text":"A bundle that encapsulates tilesets creation for the tile store implementation."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TilesetDescriptor"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateResult":{"title":"TileRegionEstimateResult","kind":"symbol","url":"\/documentation\/mapboxcommon\/tileregionestimateresult","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateResult","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileRegionEstimateResult"}],"navigatorTitle":[{"text":"TileRegionEstimateResult","kind":"identifier"}],"abstract":[{"type":"text","text":"The result of tile region estim"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegion":{"abstract":[{"type":"text","text":"TileRegion represents an identifiable geographic tile region with metadata"}],"type":"topic","url":"\/documentation\/mapboxcommon\/tileregion","title":"TileRegion","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TileRegion","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegion","navigatorTitle":[{"kind":"identifier","text":"TileRegion"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadOptions":{"title":"TileRegionLoadOptions","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileRegionLoadOptions"}],"navigatorTitle":[{"kind":"identifier","text":"TileRegionLoadOptions"}],"url":"\/documentation\/mapboxcommon\/tileregionloadoptions","type":"topic","abstract":[{"text":"Describes the tile region load option values.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileStoreOptions":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStoreOptions","abstract":[{"type":"text","text":"These constants can be used as keys for TileStore::setOption to configure further aspects of a TileStore instance."}],"role":"symbol","url":"\/documentation\/mapboxcommon\/tilestoreoptions","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TileStoreOptions"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TileStoreOptions"}],"title":"TileStoreOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileOptions":{"type":"topic","title":"TileOptions","url":"\/documentation\/mapboxmaps\/tileoptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileOptions","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TileOptions"}],"abstract":[{"text":"Options for custom geometry tiles.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileOptions"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudgetType":{"title":"TileCacheBudgetType","kind":"symbol","url":"\/documentation\/mapboxmaps\/tilecachebudgettype","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetType","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"TileCacheBudgetType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"TileCacheBudgetType"}],"abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"abstract":[],"title":"TileStore APIs","kind":"article","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","type":"topic","url":"\/documentation\/mapboxmaps\/tilestore-apis"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadProgressCallback":{"title":"TileRegionLoadProgressCallback","kind":"symbol","url":"\/documentation\/mapboxcommon\/tileregionloadprogresscallback","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgressCallback","type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileRegionLoadProgressCallback"}],"navigatorTitle":[{"kind":"identifier","text":"TileRegionLoadProgressCallback"}],"abstract":[{"type":"text","text":"Callback Invoked to report the progess of the tile region loading operation."}]},"doc://com.mapbox.MapboxMaps/SH":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","title":"Swift.Hashable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/CacheClearingError/type":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingError\/type","url":"\/documentation\/mapboxcommon\/cacheclearingerror\/type","abstract":[{"type":"text","text":"The reason for the response error."}],"title":"type","type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"type"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBXCacheClearingErrorType","text":"CacheClearingErrorType"}],"navigatorTitle":[{"text":"type","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","kind":"article","type":"topic","url":"\/documentation\/overview","title":"MapboxMaps Documentation","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateProgress":{"type":"topic","title":"TileRegionEstimateProgress","url":"\/documentation\/mapboxcommon\/tileregionestimateprogress","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgress","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TileRegionEstimateProgress"}],"abstract":[{"type":"text","text":"A tile region’s estimate progress includes counts of the number of resources that have"},{"text":" ","type":"text"},{"type":"text","text":"been estimated and the total number of resources as well as a partial result with the"},{"type":"text","text":" "},{"text":"current estimate, calculated using the data available at the moment.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TileRegionEstimateProgress","kind":"identifier"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject","title":"NSObject"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudgetInTiles":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInTiles","abstract":[{"type":"text","text":"Tile cache budget in tiles."}],"role":"symbol","url":"\/documentation\/mapboxmaps\/tilecachebudgetintiles","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TileCacheBudgetInTiles"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileCacheBudgetInTiles"}],"title":"TileCacheBudgetInTiles"},"doc://com.mapbox.MapboxMaps/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateOptions":{"type":"topic","title":"TileRegionEstimateOptions","url":"\/documentation\/mapboxcommon\/tileregionestimateoptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateOptions","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TileRegionEstimateOptions"}],"abstract":[{"type":"text","text":"Holds options for the tile region estimation operation."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TileRegionEstimateOptions","kind":"identifier"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudgetInMegabytes":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInMegabytes","abstract":[{"text":"Tile cache budget in megabytes.","type":"text"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/tilecachebudgetinmegabytes","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TileCacheBudgetInMegabytes"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileCacheBudgetInMegabytes"}],"title":"TileCacheBudgetInMegabytes"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCoverOptions":{"type":"topic","title":"TileCoverOptions","url":"\/documentation\/mapboxmaps\/tilecoveroptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCoverOptions","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TileCoverOptions"}],"abstract":[{"type":"text","text":"Various options needed for tile cover."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"TileCoverOptions","kind":"identifier"}],"tags":[{"text":"SPI","type":"spi"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateProgressCallback":{"title":"TileRegionEstimateProgressCallback","kind":"symbol","url":"\/documentation\/mapboxcommon\/tileregionestimateprogresscallback","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgressCallback","type":"topic","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"TileRegionEstimateProgressCallback","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"TileRegionEstimateProgressCallback"}],"abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStoreObserver":{"title":"TileStoreObserver","kind":"symbol","url":"\/documentation\/mapboxmaps\/tilestoreobserver","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreObserver","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileStoreObserver"}],"navigatorTitle":[{"text":"TileStoreObserver","kind":"identifier"}],"abstract":[]},"doc://com.mapbox.MapboxMaps/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/CacheClearingError/init(type:message:)":{"type":"topic","url":"\/documentation\/mapboxcommon\/cacheclearingerror\/init(type:message:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingError\/init(type:message:)","title":"init(type:message:)","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithType:message:"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CacheClearingErrorType","preciseIdentifier":"c:@E@MBXCacheClearingErrorType"},{"kind":"text","text":", "},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TilesetDescriptorOptions":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TilesetDescriptorOptions"}],"abstract":[{"text":"Describes the tileset descriptor option values.","type":"text"}],"url":"\/documentation\/mapboxmaps\/tilesetdescriptoroptions","type":"topic","title":"TilesetDescriptorOptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TilesetDescriptorOptions","role":"symbol","navigatorTitle":[{"text":"TilesetDescriptorOptions","kind":"identifier"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStoreUsageMode":{"title":"TileStoreUsageMode","kind":"symbol","url":"\/documentation\/mapboxmaps\/tilestoreusagemode","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreUsageMode","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileStoreUsageMode"}],"navigatorTitle":[{"kind":"identifier","text":"TileStoreUsageMode"}],"abstract":[{"type":"text","text":"Describes tile store usage modes."}]},"doc://com.mapbox.MapboxMaps/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/CacheClearingErrorType":{"title":"CacheClearingErrorType","kind":"symbol","url":"\/documentation\/mapboxcommon\/cacheclearingerrortype","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingErrorType","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CacheClearingErrorType"}],"navigatorTitle":[{"kind":"identifier","text":"CacheClearingErrorType"}],"abstract":[{"text":"Describes the reason for a cache clearing failure.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","role":"collection","title":"MapboxMaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps"},"doc://com.mapbox.MapboxMaps/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","title":"Swift.Equatable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileStore":{"abstract":[{"text":"TileStore manages downloads and storage for requests to tile-related API endpoints, enforcing a disk usage","type":"text"},{"text":" ","type":"text"},{"text":"quota: tiles available on disk may be deleted to make room for a new download. This interface can be used by an","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"app developer to set the disk quota. The rest of TileStore API is intended for native SDK consumption only."}],"type":"topic","url":"\/documentation\/mapboxcommon\/tilestore","title":"TileStore","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileStore","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore","navigatorTitle":[{"text":"TileStore","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/CacheClearingError":{"title":"CacheClearingError","kind":"symbol","url":"\/documentation\/mapboxcommon\/cacheclearingerror","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingError","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CacheClearingError"}],"navigatorTitle":[{"text":"CacheClearingError","kind":"identifier"}],"abstract":[{"type":"text","text":"Describes a cache clearing error."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudget":{"type":"topic","title":"TileCacheBudget","url":"\/documentation\/mapboxmaps\/tilecachebudget","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudget","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TileCacheBudget"}],"abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TileCacheBudget"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileDataDomain":{"title":"TileDataDomain","kind":"symbol","url":"\/documentation\/mapboxcommon\/tiledatadomain","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileDataDomain","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileDataDomain"}],"navigatorTitle":[{"kind":"identifier","text":"TileDataDomain"}],"abstract":[{"type":"text","text":"Describes the tiles data domain."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MBXCacheClearingError"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"value":[{"kind":"identifier","text":"MBXCacheClearingError"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBXCacheClearingError"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingError\/message","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingError\/type"]},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingError\/init(type:message:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}]},{"value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}],"op":"replace","path":"\/relationshipsSections"},{"value":[{"title":"TileStore","generated":true,"anchor":"TileStore","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStoreOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudget","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInMegabytes","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInTiles","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegion","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgress","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TilesetDescriptor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TilesetDescriptorOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgressCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreUsageMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileDataDomain","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgress","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateResult","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgressCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingErrorType"]}],"op":"replace","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBXCacheClearingError","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgress\/title","value":"MBXTileRegionLoadProgress"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgress\/fragments","value":[{"kind":"identifier","text":"MBXTileRegionLoadProgress"}]},{"value":[{"text":"MBXTileRegionLoadProgress","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgress\/navigatorTitle"},{"value":"MBMCanonicalTileID","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/fragments","op":"replace","value":[{"text":"MBMCanonicalTileID","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/navigatorTitle","value":[{"text":"MBMCanonicalTileID","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingError~1message\/title","value":"message"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingError~1message\/fragments","value":[{"kind":"identifier","text":"message"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TilesetDescriptor\/title","op":"replace","value":"MBXTilesetDescriptor"},{"value":[{"kind":"identifier","text":"MBXTilesetDescriptor"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TilesetDescriptor\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TilesetDescriptor\/navigatorTitle","value":[{"kind":"identifier","text":"MBXTilesetDescriptor"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateResult\/title","op":"replace","value":"MBXTileRegionEstimateResult"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateResult\/fragments","op":"replace","value":[{"text":"MBXTileRegionEstimateResult","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MBXTileRegionEstimateResult"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateResult\/navigatorTitle","op":"replace"},{"value":"MBXTileRegion","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegion\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegion\/fragments","value":[{"kind":"identifier","text":"MBXTileRegion"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegion\/navigatorTitle","op":"replace","value":[{"text":"MBXTileRegion","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/title","value":"MBXTileRegionLoadOptions"},{"value":[{"kind":"identifier","text":"MBXTileRegionLoadOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/fragments"},{"value":[{"text":"MBXTileRegionLoadOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStoreOptions\/title","op":"replace","value":"MBXTileStoreOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStoreOptions\/fragments","value":[{"text":"MBXTileStoreOptions","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MBXTileStoreOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStoreOptions\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileOptions\/title","value":"MBMTileOptions"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileOptions\/fragments","value":[{"text":"MBMTileOptions","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileOptions\/navigatorTitle","value":[{"text":"MBMTileOptions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetType\/title","value":"MBMTileCacheBudgetType"},{"op":"replace","value":[{"kind":"identifier","text":"MBMTileCacheBudgetType"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetType\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetType\/navigatorTitle","value":[{"kind":"identifier","text":"MBMTileCacheBudgetType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgressCallback\/title","value":"MBXTileRegionLoadProgressCallback","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgressCallback\/fragments","value":[{"kind":"identifier","text":"MBXTileRegionLoadProgressCallback"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgressCallback\/navigatorTitle","op":"replace","value":[{"text":"MBXTileRegionLoadProgressCallback","kind":"identifier"}]},{"value":"type","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingError~1type\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingError~1type\/fragments","op":"replace","value":[{"kind":"identifier","text":"type"}]},{"value":"MBXTileRegionEstimateProgress","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgress\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgress\/fragments","value":[{"text":"MBXTileRegionEstimateProgress","kind":"identifier"}]},{"value":[{"text":"MBXTileRegionEstimateProgress","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgress\/navigatorTitle"},{"value":"MBMTileCacheBudgetInTiles","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInTiles\/title"},{"value":[{"kind":"identifier","text":"MBMTileCacheBudgetInTiles"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInTiles\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInTiles\/navigatorTitle","value":[{"kind":"identifier","text":"MBMTileCacheBudgetInTiles"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateOptions\/title","value":"MBXTileRegionEstimateOptions"},{"value":[{"text":"MBXTileRegionEstimateOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateOptions\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateOptions\/navigatorTitle","op":"replace","value":[{"text":"MBXTileRegionEstimateOptions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInMegabytes\/title","value":"MBMTileCacheBudgetInMegabytes"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInMegabytes\/fragments","op":"replace","value":[{"text":"MBMTileCacheBudgetInMegabytes","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInMegabytes\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMTileCacheBudgetInMegabytes"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgressCallback\/title","op":"replace","value":"MBXTileRegionEstimateProgressCallback"},{"op":"replace","value":[{"kind":"identifier","text":"MBXTileRegionEstimateProgressCallback"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgressCallback\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgressCallback\/navigatorTitle","op":"replace","value":[{"text":"MBXTileRegionEstimateProgressCallback","kind":"identifier"}]},{"op":"replace","value":"initWithType:message:","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingError~1init(type:message:)\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingError~1init(type:message:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithType:message:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions\/title","value":"MBMTilesetDescriptorOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions\/fragments","value":[{"kind":"identifier","text":"MBMTilesetDescriptorOptions"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions\/navigatorTitle","op":"replace","value":[{"text":"MBMTilesetDescriptorOptions","kind":"identifier"}]},{"value":"MBMTileStoreUsageMode","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileStoreUsageMode\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileStoreUsageMode\/fragments","value":[{"kind":"identifier","text":"MBMTileStoreUsageMode"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileStoreUsageMode\/navigatorTitle","value":[{"text":"MBMTileStoreUsageMode","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"MBXCacheClearingErrorType","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingErrorType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingErrorType\/fragments","value":[{"text":"MBXCacheClearingErrorType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingErrorType\/navigatorTitle","value":[{"text":"MBXCacheClearingErrorType","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/title","value":"MBXTileStore"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/fragments","value":[{"kind":"identifier","text":"MBXTileStore"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBXTileStore"}]},{"op":"replace","value":"MBXCacheClearingError","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingError\/title"},{"value":[{"text":"MBXCacheClearingError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingError\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingError\/navigatorTitle","value":[{"kind":"identifier","text":"MBXCacheClearingError"}],"op":"replace"},{"value":"MBMTileCacheBudget","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudget\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudget\/fragments","value":[{"text":"MBMTileCacheBudget","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudget\/navigatorTitle","value":[{"kind":"identifier","text":"MBMTileCacheBudget"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileDataDomain\/title","op":"replace","value":"MBXTileDataDomain"},{"value":[{"kind":"identifier","text":"MBXTileDataDomain"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileDataDomain\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileDataDomain\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBXTileDataDomain"}]}]}]}