{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events"]]},"sections":[],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Cancelable","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Allows to cancel the associated asynchronous operation"}],"topicSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Cancelable\/cancel()"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/cancelable"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/cancelable"]}],"metadata":{"role":"symbol","externalID":"c:objc(pl)MBXCancelable","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Cancelable"}],"roleHeading":"Protocol","navigatorTitle":[{"kind":"identifier","text":"Cancelable"}],"modules":[{"name":"MapboxCommon"}],"title":"Cancelable","symbolKind":"protocol"},"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Signal","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AnyCancelable","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/EventTimeInterval"],"anchor":"Foundation","title":"Foundation"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"Cancelable","kind":"identifier"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"type":"heading","text":"Overview","anchor":"overview","level":2},{"type":"paragraph","inlineContent":[{"text":"The associated asynchronous operation is not automatically canceled if this","type":"text"},{"type":"text","text":" "},{"type":"text","text":"object goes out of scope."}]}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraAnimator"],"kind":"relationships","type":"inheritedBy","title":"Inherited By"},{"title":"Conforming Types","kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AnyCancelable","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/BasicCameraAnimator","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FlyToCameraAnimator"],"type":"conformingTypes"}],"kind":"symbol","references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Signal":{"abstract":[{"type":"text","text":"Signal is a typed interface for observing arbitrary values over time."}],"url":"\/documentation\/mapboxmaps\/signal","kind":"symbol","navigatorTitle":[{"text":"Signal","kind":"identifier"}],"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Signal"}],"role":"symbol","title":"Signal","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Signal"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/EventTimeInterval":{"kind":"symbol","navigatorTitle":[{"text":"EventTimeInterval","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"EventTimeInterval","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/EventTimeInterval","title":"EventTimeInterval","type":"topic","url":"\/documentation\/mapboxmaps\/eventtimeinterval","abstract":[{"type":"text","text":"The time interval of an event. The "},{"type":"codeVoice","code":"begin"},{"type":"text","text":" property represents the time"},{"type":"text","text":" "},{"type":"text","text":"origin of an event, and the "},{"type":"codeVoice","code":"end"},{"type":"text","text":" property represents the time when the particular"},{"text":" ","type":"text"},{"type":"text","text":"operation is complete. The timestamps are sampled at the origin and do not include"},{"type":"text","text":" "},{"text":"the time required to dispatch an event.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/BasicCameraAnimator":{"navigatorTitle":[{"text":"BasicCameraAnimator","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/BasicCameraAnimator","kind":"symbol","title":"BasicCameraAnimator","abstract":[],"role":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/basiccameraanimator","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BasicCameraAnimator","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Cancelable":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Cancelable","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Cancelable","url":"\/documentation\/mapboxcommon\/cancelable","kind":"symbol","type":"topic","navigatorTitle":[{"text":"Cancelable","kind":"identifier"}],"abstract":[{"type":"text","text":"Allows to cancel the associated asynchronous operation"}],"title":"Cancelable","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraAnimator":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraAnimator","title":"CameraAnimator","url":"\/documentation\/mapboxmaps\/cameraanimator","role":"symbol","type":"topic","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"CameraAnimator","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraAnimator","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FlyToCameraAnimator":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FlyToCameraAnimator"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FlyToCameraAnimator","title":"FlyToCameraAnimator","role":"symbol","url":"\/documentation\/mapboxmaps\/flytocameraanimator","navigatorTitle":[{"kind":"identifier","text":"FlyToCameraAnimator"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"An animator that evokes powered flight and an optional transition duration and timing function."},{"type":"text","text":" "},{"type":"text","text":"It seamlessly incorporates zooming and panning to help the user find their bearings even after"},{"text":" ","type":"text"},{"text":"traversing a great distance.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"url":"\/documentation\/mapboxmaps\/events","kind":"article","role":"collectionGroup","title":"Map events","abstract":[{"type":"text","text":"The simplified diagram of the events emitted by the map is displayed below."}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","role":"collection","url":"\/documentation\/overview","kind":"article","abstract":[],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AnyCancelable":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"AnyCancelable"}],"role":"symbol","abstract":[{"text":"A Cancellable object that automatically cancels on deinit.","type":"text"}],"title":"AnyCancelable","url":"\/documentation\/mapboxmaps\/anycancelable","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AnyCancelable","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AnyCancelable","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"title":"MapboxMaps","kind":"symbol","role":"collection","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Cancelable/cancel()":{"url":"\/documentation\/mapboxcommon\/cancelable\/cancel()","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"cancel","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","title":"cancel()","navigatorTitle":[{"text":"cancel","kind":"identifier"}],"required":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Cancelable\/cancel()","type":"topic","abstract":[{"type":"text","text":"Cancels the associated asynchronous operation"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"MBXCancelable","op":"replace","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXCancelable"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"MBXCancelable","kind":"identifier"}]},{"value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Cancelable\/cancel()"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"op":"replace","path":"\/seeAlsoSections","value":[{"anchor":"Foundation","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/EventTimeInterval"],"title":"Foundation"}]},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"text":"MBXCancelable","kind":"identifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"MBMEventTimeInterval","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1EventTimeInterval\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1EventTimeInterval\/fragments","op":"replace","value":[{"text":"MBMEventTimeInterval","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MBMEventTimeInterval"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1EventTimeInterval\/navigatorTitle","op":"replace"},{"value":"MBXCancelable","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/title"},{"value":[{"kind":"identifier","text":"MBXCancelable"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MBXCancelable"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/navigatorTitle"},{"value":"cancel","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable~1cancel()\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable~1cancel()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"cancel","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}