{"metadata":{"externalID":"c:objc(cs)MBXFeature","role":"symbol","modules":[{"name":"MapboxCommon"}],"roleHeading":"Class","title":"Feature","symbolKind":"class","navigatorTitle":[{"text":"Feature","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Feature"}]},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Feature","interfaceLanguage":"swift"},"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"kind":"relationships"},{"type":"conformsTo","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH"],"kind":"relationships","title":"Conforms To"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Feature","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon"]]},"sections":[],"kind":"symbol","topicSections":[{"anchor":"Initializers","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Feature\/init(identifier:geometry:properties:)"],"title":"Initializers"},{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Feature\/geometry","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Feature\/identifier","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Feature\/properties"],"title":"Instance Properties"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/feature"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/feature"]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","type":"topic","title":"MapboxMaps Documentation","url":"\/documentation\/overview","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"title":"MapboxCommon","url":"\/documentation\/mapboxcommon","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","abstract":[],"kind":"symbol","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Feature/properties":{"type":"topic","abstract":[],"url":"\/documentation\/mapboxcommon\/feature\/properties","title":"properties","role":"symbol","navigatorTitle":[{"text":"properties","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"properties"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Feature\/properties"},"doc://com.mapbox.MapboxMaps/SQ":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/objc(pl)NSObject":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Feature/identifier":{"type":"topic","kind":"symbol","role":"symbol","abstract":[],"title":"identifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Feature\/identifier","navigatorTitle":[{"kind":"identifier","text":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"identifier","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"url":"\/documentation\/mapboxcommon\/feature\/identifier"},"doc://com.mapbox.MapboxMaps/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Feature/init(identifier:geometry:properties:)":{"kind":"symbol","type":"topic","role":"symbol","abstract":[],"title":"init(identifier:geometry:properties:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Feature\/init(identifier:geometry:properties:)","navigatorTitle":[{"text":"initWithIdentifier:geometry:properties:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"},{"kind":"text","text":", "},{"text":"geometry","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MBXGeometry","text":"Geometry","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"properties"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"},{"text":"])","kind":"text"}],"url":"\/documentation\/mapboxcommon\/feature\/init(identifier:geometry:properties:)"},"doc://com.mapbox.MapboxMaps/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject","title":"NSObject"},"doc://com.mapbox.MapboxMaps/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.mapbox.MapboxMaps/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.mapbox.MapboxMaps/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Feature/geometry":{"type":"topic","abstract":[],"url":"\/documentation\/mapboxcommon\/feature\/geometry","title":"geometry","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"geometry"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"geometry","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Geometry","preciseIdentifier":"c:objc(cs)MBXGeometry"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Feature\/geometry"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Feature":{"title":"Feature","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Feature"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Feature","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/feature","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Feature","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"MBXFeature","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXFeature"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"MBXFeature","kind":"identifier"}]},{"value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Feature\/geometry","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Feature\/identifier","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Feature\/properties"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true},{"anchor":"Instance-Methods","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Feature\/init(identifier:geometry:properties:)"],"generated":true,"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"title":"Inherits From"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBXFeature","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"properties","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Feature~1properties\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Feature~1properties\/fragments","op":"replace","value":[{"kind":"identifier","text":"properties"}]},{"value":"identifier","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Feature~1identifier\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Feature~1identifier\/fragments","value":[{"text":"identifier","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Feature~1init(identifier:geometry:properties:)\/title","value":"initWithIdentifier:geometry:properties:","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Feature~1init(identifier:geometry:properties:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithIdentifier:geometry:properties:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Feature~1geometry\/title","value":"geometry"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Feature~1geometry\/fragments","value":[{"kind":"identifier","text":"geometry"}]},{"value":"MBXFeature","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Feature\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Feature\/fragments","value":[{"text":"MBXFeature","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MBXFeature"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Feature\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}