{"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/geometrytype_empty"]},{"paths":["\/documentation\/mapboxcommon\/geometrytype_empty"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon"],["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TurfAPI","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType_Empty"},"metadata":{"title":"GeometryType_Empty","role":"symbol","navigatorTitle":[{"text":"MBXGeometryType_Empty","kind":"identifier"}],"modules":[{"name":"MapboxCommon"}],"externalID":"c:@EA@MBXGeometryType@MBXGeometryType_Empty","roleHeading":"Global Variable","symbolKind":"var","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GeometryType_Empty","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GeometryType","preciseIdentifier":"c:@EA@MBXGeometryType"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GeometryType_Empty"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType","text":"GeometryType","preciseIdentifier":"c:@EA@MBXGeometryType"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"sections":[],"kind":"symbol","references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"role":"collection","url":"\/documentation\/mapboxcommon","kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","title":"MapboxCommon","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","title":"MapboxMaps","type":"topic","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article","title":"MapboxMaps Documentation","abstract":[],"url":"\/documentation\/overview","role":"collection","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TurfAPI":{"url":"\/documentation\/mapboxmaps\/turfapi","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TurfAPI","type":"topic","abstract":[{"type":"text","text":"Describes "},{"code":"turf-swift","type":"codeVoice"},{"text":" dependency objects","type":"text"}],"title":"Turf","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/GeometryType":{"title":"GeometryType","abstract":[],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/mapboxcommon\/geometrytype","navigatorTitle":[{"text":"GeometryType","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GeometryType"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/GeometryType_Empty":{"title":"GeometryType_Empty","abstract":[],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/mapboxcommon\/geometrytype_empty","navigatorTitle":[{"text":"MBXGeometryType_Empty","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType_Empty","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GeometryType_Empty","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GeometryType","preciseIdentifier":"c:@EA@MBXGeometryType"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"MBXGeometryType_Empty","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"MBXGeometryType_Empty","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"MBXGeometryType_Empty","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"MBXGeometryType","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType\/fragments","value":[{"text":"","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"MBXGeometryType"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType\/navigatorTitle"},{"value":"MBXGeometryType_Empty","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType_Empty\/title"},{"value":[{"text":"MBXGeometryType_Empty","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType_Empty\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}