{"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpResponse\/init(identifier:request:result:)"],"generated":true,"anchor":"Initializers"},{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpResponse\/request","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpResponse\/requestId","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpResponse\/result"],"generated":true}],"variants":[{"paths":["\/documentation\/mapboxcommon\/httpresponse"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/httpresponse"]}],"abstract":[{"text":"Record which is used to report HTTP response to the caller.","type":"text"}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpResponse","interfaceLanguage":"swift"},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH"],"type":"conformsTo"}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"HttpResponse"}]}]}],"metadata":{"symbolKind":"class","navigatorTitle":[{"text":"HttpResponse","kind":"identifier"}],"modules":[{"name":"MapboxCommon"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"HttpResponse","kind":"identifier"}],"title":"HttpResponse","roleHeading":"Class","role":"symbol","externalID":"c:objc(cs)MBXHttpResponse"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"role":"collection","url":"\/documentation\/mapboxcommon","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","abstract":[],"title":"MapboxCommon","kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP"},"doc://com.mapbox.MapboxMaps/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject"},"doc://com.mapbox.MapboxMaps/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpResponse/requestId":{"title":"requestId","url":"\/documentation\/mapboxcommon\/httpresponse\/requestid","navigatorTitle":[{"text":"requestId","kind":"identifier"}],"type":"topic","abstract":[{"text":"The id of the request that resulted in this response. Matches the return value of HttpServiceInterface::request.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpResponse\/requestId","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"requestId","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V","text":"UInt64"}]},"doc://com.mapbox.MapboxMaps/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"},"doc://com.mapbox.MapboxMaps/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpResponse/result":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpResponse\/result","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"result"},{"text":": ","kind":"text"},{"text":"Result","preciseIdentifier":"s:s6ResultO","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"HttpResponseData","preciseIdentifier":"c:objc(cs)MBXHttpResponseData"},{"kind":"text","text":", "},{"preciseIdentifier":"c:objc(cs)MBXHttpRequestError","text":"HttpRequestError","kind":"typeIdentifier"},{"kind":"text","text":">"}],"kind":"symbol","url":"\/documentation\/mapboxcommon\/httpresponse\/result","title":"result","abstract":[{"type":"text","text":"Result of HTTP request call."}],"role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpResponse/init(identifier:request:result:)":{"title":"init(identifier:request:result:)","url":"\/documentation\/mapboxcommon\/httpresponse\/init(identifier:request:result:)","type":"topic","abstract":[{"type":"text","text":"Initialize a response given the initial request and "},{"type":"codeVoice","code":"HttpResponseData"},{"text":" or","type":"text"},{"type":"text","text":" "},{"code":"HttpRequestError","type":"codeVoice"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpResponse\/init(identifier:request:result:)","kind":"symbol","fragments":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s6UInt64V","text":"UInt64","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"request"},{"kind":"text","text":": "},{"text":"HttpRequest","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXHttpRequest"},{"kind":"text","text":", "},{"text":"result","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBXHttpResponseData","text":"HttpResponseData","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBXHttpRequestError","kind":"typeIdentifier","text":"HttpRequestError"},{"text":">)","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpResponse":{"navigatorTitle":[{"text":"HttpResponse","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"text":"Record which is used to report HTTP response to the caller.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HttpResponse"}],"url":"\/documentation\/mapboxcommon\/httpresponse","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpResponse","title":"HttpResponse","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpResponse/request":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpResponse\/request","navigatorTitle":[{"kind":"identifier","text":"request"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"request","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"HttpRequest","preciseIdentifier":"c:objc(cs)MBXHttpRequest"}],"kind":"symbol","title":"request","url":"\/documentation\/mapboxcommon\/httpresponse\/request","abstract":[{"text":"HTTP request data which was use to send HTTP request.","type":"text"}],"role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH"},"doc://com.mapbox.MapboxMaps/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","type":"topic","kind":"article","abstract":[],"role":"collection","title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"MBXHttpResponse"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MBXHttpResponse"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"MBXHttpResponse","kind":"identifier"}]},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpResponse\/request","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpResponse\/requestId"],"anchor":"Instance-Properties","generated":true}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"MBXHttpResponse","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpResponse~1requestId\/title","value":"requestId"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpResponse~1requestId\/fragments","op":"replace","value":[{"kind":"identifier","text":"requestId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpResponse\/title","value":"MBXHttpResponse"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpResponse\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXHttpResponse"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpResponse\/navigatorTitle","op":"replace","value":[{"text":"MBXHttpResponse","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpResponse~1request\/title","value":"request","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpResponse~1request\/fragments","value":[{"kind":"identifier","text":"request"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}