{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationServiceFactory"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Overview","anchor":"overview","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"This class is used to instantiate a platform-specific implementation"},{"text":" ","type":"text"},{"text":"of location service.","type":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs"]]},"metadata":{"externalID":"c:objc(cs)MBXLocationServiceFactory","symbolKind":"class","title":"LocationServiceFactory","navigatorTitle":[{"text":"LocationServiceFactory","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"LocationServiceFactory","kind":"identifier"}],"modules":[{"name":"MapboxCommon"}],"roleHeading":"Class","role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceFactory"},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Location service factory."}],"relationshipsSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH"],"title":"Conforms To"}],"seeAlsoSections":[{"title":"Location","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationManager","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck2DConfiguration","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Model","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckBearing","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProviderDelegate","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Coordinate2D","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationExtraKeys","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProviderRequest","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/DeviceLocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Heading","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckRenderingData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/IntervalSettings"],"generated":true,"anchor":"Location"}],"variants":[{"paths":["\/documentation\/mapboxcommon\/locationservicefactory"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxcommon\/locationservicefactory"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PermissionStatus":{"type":"topic","kind":"symbol","title":"PermissionStatus","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus","abstract":[{"type":"text","text":"Location permissions granted by user to the app."}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PermissionStatus","kind":"identifier"}],"navigatorTitle":[{"text":"PermissionStatus","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/permissionstatus"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Location-APIs":{"role":"collectionGroup","abstract":[],"url":"\/documentation\/mapboxmaps\/location-apis","kind":"article","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","title":"Location"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PuckRenderingData":{"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PuckRenderingData"}],"navigatorTitle":[{"text":"PuckRenderingData","kind":"identifier"}],"kind":"symbol","title":"PuckRenderingData","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckRenderingData","url":"\/documentation\/mapboxmaps\/puckrenderingdata","type":"topic","abstract":[{"type":"text","text":"Represents the interpolated data ready to render the user location puck."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationObserver":{"url":"\/documentation\/mapboxcommon\/locationobserver","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocationObserver"}],"title":"LocationObserver","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationObserver","abstract":[{"type":"text","text":"Observer for getting updates from a LocationProvider."}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LocationObserver"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/AccuracyAuthorization":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AccuracyAuthorization"}],"title":"AccuracyAuthorization","type":"topic","url":"\/documentation\/mapboxcommon\/accuracyauthorization","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AccuracyAuthorization","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Accuracy authorization granted by user to the app.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationServiceFactory":{"navigatorTitle":[{"kind":"identifier","text":"LocationServiceFactory"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"LocationServiceFactory","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/locationservicefactory","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceFactory","abstract":[{"text":"Location service factory.","type":"text"}],"role":"symbol","title":"LocationServiceFactory","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/DeviceLocationProvider":{"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DeviceLocationProvider"}],"navigatorTitle":[{"text":"DeviceLocationProvider","kind":"identifier"}],"kind":"symbol","title":"DeviceLocationProvider","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/DeviceLocationProvider","url":"\/documentation\/mapboxcommon\/devicelocationprovider","type":"topic","abstract":[{"text":"Location provider specialisation that provides real-time locations generated from the device","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationErrorCode":{"navigatorTitle":[{"kind":"identifier","text":"LocationErrorCode"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LocationErrorCode"}],"url":"\/documentation\/mapboxcommon\/locationerrorcode","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode","abstract":[{"text":"Codes of location errors.","type":"text"}],"role":"symbol","title":"LocationErrorCode","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PuckBearing":{"navigatorTitle":[{"kind":"identifier","text":"PuckBearing"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PuckBearing","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/puckbearing","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckBearing","abstract":[{"type":"text","text":"Controls how the puck is oriented"}],"role":"symbol","title":"PuckBearing","kind":"symbol"},"doc://com.mapbox.MapboxMaps/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP"},"doc://com.mapbox.MapboxMaps/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Location":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Location information."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location","url":"\/documentation\/mapboxcommon\/location","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Location"}],"title":"Location","navigatorTitle":[{"text":"Location","kind":"identifier"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationServiceObserver":{"navigatorTitle":[{"kind":"identifier","text":"LocationServiceObserver"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver","url":"\/documentation\/mapboxcommon\/locationserviceobserver","kind":"symbol","title":"LocationServiceObserver","type":"topic","role":"symbol","abstract":[{"text":"Observers for getting updates from LocationService.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LocationServiceObserver"}]},"doc://com.mapbox.MapboxMaps/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationProviderRequest":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LocationProviderRequest"}],"title":"LocationProviderRequest","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProviderRequest","type":"topic","abstract":[{"type":"text","text":"Data model that contains parameters for location requests."}],"kind":"symbol","navigatorTitle":[{"text":"LocationProviderRequest","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/locationproviderrequest"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/AccuracyLevel":{"navigatorTitle":[{"kind":"identifier","text":"AccuracyLevel"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel","url":"\/documentation\/mapboxcommon\/accuracylevel","kind":"symbol","title":"AccuracyLevel","type":"topic","role":"symbol","abstract":[{"text":"The accuracy of the observed location","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"AccuracyLevel","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationError":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"LocationError","kind":"identifier"}],"title":"LocationError","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationError","type":"topic","abstract":[{"type":"text","text":"Error code with brief explanation."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"LocationError"}],"url":"\/documentation\/mapboxcommon\/locationerror"},"doc://com.mapbox.MapboxMaps/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeadingProvider":{"url":"\/documentation\/mapboxmaps\/headingprovider","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HeadingProvider"}],"title":"HeadingProvider","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingProvider","abstract":[{"type":"text","text":"Provides heading data to drive the location puck."}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HeadingProvider"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Heading":{"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"Heading","kind":"identifier"}],"title":"Heading","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Heading","type":"topic","abstract":[{"text":"The azimuth (orientation) of the user’s device, relative to true or magnetic north.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Heading"}],"url":"\/documentation\/mapboxmaps\/heading"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","role":"collection","url":"\/documentation\/mapboxmaps","kind":"symbol","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LocationManager":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"LocationManager","kind":"identifier"}],"title":"LocationManager","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationManager","type":"topic","abstract":[{"type":"text","text":"An object responsible for managing user location Puck."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"LocationManager"}],"url":"\/documentation\/mapboxmaps\/locationmanager"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Coordinate2D":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Coordinate2D"}],"title":"Coordinate2D","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Coordinate2D","type":"topic","abstract":[{"type":"text","text":"Boxed version of CLLocationCoordinate2D"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Coordinate2D"}],"url":"\/documentation\/mapboxcommon\/coordinate2d"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Puck3DConfiguration":{"navigatorTitle":[{"text":"Puck3DConfiguration","kind":"identifier"}],"title":"Puck3DConfiguration","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Puck3DConfiguration"}],"kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/puck3dconfiguration"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationProvider":{"navigatorTitle":[{"kind":"identifier","text":"LocationProvider"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider","url":"\/documentation\/mapboxcommon\/locationprovider","title":"LocationProvider","kind":"symbol","type":"topic","role":"symbol","abstract":[{"text":"Location provider that provides locations","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LocationProvider"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/IntervalSettings":{"navigatorTitle":[{"kind":"identifier","text":"IntervalSettings"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/IntervalSettings","url":"\/documentation\/mapboxcommon\/intervalsettings","kind":"symbol","title":"IntervalSettings","type":"topic","role":"symbol","abstract":[{"type":"text","text":"The interval for active location updates"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"IntervalSettings","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Puck2DConfiguration":{"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Puck2DConfiguration"}],"title":"Puck2DConfiguration","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck2DConfiguration","type":"topic","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"Puck2DConfiguration","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/puck2dconfiguration"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","title":"MapboxMaps Documentation","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationExtraKeys":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"LocationExtraKeys","kind":"identifier"}],"title":"LocationExtraKeys","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationExtraKeys","type":"topic","abstract":[{"text":"Keys for additional information (extra) in Location.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"LocationExtraKeys","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/locationextrakeys"},"doc://com.mapbox.MapboxMaps/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AppleLocationProviderDelegate":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AppleLocationProviderDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"AppleLocationProviderDelegate"}],"kind":"symbol","title":"AppleLocationProviderDelegate","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProviderDelegate","url":"\/documentation\/mapboxmaps\/applelocationproviderdelegate","type":"topic","abstract":[{"type":"text","text":"The "},{"isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProviderDelegate","type":"reference"},{"type":"text","text":" protocol defines a set of optional methods that you"},{"type":"text","text":" "},{"text":"can use to receive events from an associated location provider object.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Model":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Model","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Model"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Model"}],"type":"topic","abstract":[{"type":"text","text":"A structure represeting a Model"}],"title":"Model","url":"\/documentation\/mapboxmaps\/model","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AppleLocationProvider":{"navigatorTitle":[{"kind":"identifier","text":"AppleLocationProvider"}],"role":"symbol","abstract":[{"text":"A location provider based on CoreLocation’s ","type":"text"},{"type":"codeVoice","code":"CLLocationManager"},{"text":".","type":"text"}],"url":"\/documentation\/mapboxmaps\/applelocationprovider","kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProvider","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AppleLocationProvider"}],"title":"AppleLocationProvider"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LocationOptions":{"navigatorTitle":[{"kind":"identifier","text":"LocationOptions"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationOptions","url":"\/documentation\/mapboxmaps\/locationoptions","kind":"symbol","title":"LocationOptions","type":"topic","role":"symbol","abstract":[{"text":"A struct to configure a ","type":"text"},{"type":"codeVoice","code":"LocationManager"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationOptions"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PuckType":{"navigatorTitle":[{"kind":"identifier","text":"PuckType"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PuckType","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/pucktype","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckType","abstract":[{"text":"Represents the different types of pucks","type":"text"}],"role":"symbol","title":"PuckType","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeadingObserver":{"navigatorTitle":[{"kind":"identifier","text":"HeadingObserver"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingObserver","url":"\/documentation\/mapboxmaps\/headingobserver","kind":"symbol","title":"HeadingObserver","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Listens to "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingProvider","isActive":true,"type":"reference"},{"type":"text","text":"’s updates."}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HeadingObserver"}]},"doc://com.mapbox.MapboxMaps/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"MBXLocationServiceFactory","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"MBXLocationServiceFactory","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":[{"text":"MBXLocationServiceFactory","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}]},{"op":"replace","value":[{"title":"Location","generated":true,"anchor":"Location","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Coordinate2D","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationExtraKeys","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProviderRequest","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/DeviceLocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/IntervalSettings"]}],"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"MBXLocationServiceFactory","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"MBXPermissionStatus","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/fragments","op":"replace","value":[{"text":"MBXPermissionStatus","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/navigatorTitle","value":[{"kind":"identifier","text":"MBXPermissionStatus"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/title","op":"replace","value":"MBXLocationObserver"},{"value":[{"text":"MBXLocationObserver","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/navigatorTitle","value":[{"kind":"identifier","text":"MBXLocationObserver"}],"op":"replace"},{"value":"MBXAccuracyAuthorization","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization\/fragments","value":[{"text":"MBXAccuracyAuthorization","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization\/navigatorTitle","value":[{"kind":"identifier","text":"MBXAccuracyAuthorization"}]},{"value":"MBXLocationServiceFactory","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceFactory\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBXLocationServiceFactory"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceFactory\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MBXLocationServiceFactory"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceFactory\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1DeviceLocationProvider\/title","value":"MBXDeviceLocationProvider"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1DeviceLocationProvider\/fragments","value":[{"text":"MBXDeviceLocationProvider","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1DeviceLocationProvider\/navigatorTitle","value":[{"text":"MBXDeviceLocationProvider","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/title","value":"MBXLocationErrorCode"},{"value":[{"text":"MBXLocationErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/fragments","op":"replace"},{"value":[{"text":"MBXLocationErrorCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/title","value":"MBXLocation","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/fragments","value":[{"kind":"identifier","text":"MBXLocation"}],"op":"replace"},{"op":"replace","value":[{"text":"MBXLocation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/navigatorTitle"},{"value":"MBXLocationServiceObserver","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver\/fragments","value":[{"text":"MBXLocationServiceObserver","kind":"identifier"}],"op":"replace"},{"value":[{"text":"MBXLocationServiceObserver","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProviderRequest\/title","value":"MBXLocationProviderRequest"},{"value":[{"kind":"identifier","text":"MBXLocationProviderRequest"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProviderRequest\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProviderRequest\/navigatorTitle","value":[{"kind":"identifier","text":"MBXLocationProviderRequest"}]},{"value":"MBXAccuracyLevel","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel\/fragments","value":[{"text":"MBXAccuracyLevel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel\/navigatorTitle","op":"replace","value":[{"text":"MBXAccuracyLevel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationError\/title","value":"MBXLocationError","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationError\/fragments","value":[{"text":"MBXLocationError","kind":"identifier"}],"op":"replace"},{"value":[{"text":"MBXLocationError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationError\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Coordinate2D\/title","value":"MBXCoordinate2D","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Coordinate2D\/fragments","value":[{"text":"MBXCoordinate2D","kind":"identifier"}],"op":"replace"},{"value":[{"text":"MBXCoordinate2D","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Coordinate2D\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/title","value":"MBXLocationProvider"},{"value":[{"kind":"identifier","text":"MBXLocationProvider"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/navigatorTitle","value":[{"text":"MBXLocationProvider","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1IntervalSettings\/title","value":"MBXIntervalSettings"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1IntervalSettings\/fragments","op":"replace","value":[{"text":"MBXIntervalSettings","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"MBXIntervalSettings"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1IntervalSettings\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationExtraKeys\/title","value":"MBXLocationExtraKeys"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationExtraKeys\/fragments","value":[{"text":"MBXLocationExtraKeys","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MBXLocationExtraKeys"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationExtraKeys\/navigatorTitle"}]}]}