{"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"type":"conformsTo","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH"],"title":"Conforms To","kind":"relationships"}],"variants":[{"paths":["\/documentation\/mapboxcommon\/location"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/location"]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Class","externalID":"c:objc(cs)MBXLocation","role":"symbol","modules":[{"name":"MapboxCommon"}],"symbolKind":"class","title":"Location","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Location","kind":"identifier"}],"navigatorTitle":[{"text":"Location","kind":"identifier"}]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","topicSections":[{"title":"Initializers","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location\/init(CLLocation:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location\/init(CLLocation:extra:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location\/init(coordinate:timestamp:altitude:horizontalAccuracy:verticalAccuracy:speed:speedAccuracy:bearing:bearingAccuracy:floor:source:extra:)"],"anchor":"Initializers"},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location\/altitude","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location\/bearing","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location\/bearingAccuracy","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location\/coordinate","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location\/extra","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location\/floor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location\/horizontalAccuracy","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location\/source","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location\/speed","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location\/speedAccuracy","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location\/timestamp","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location\/verticalAccuracy"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location\/isEqual(to:)"],"generated":true,"anchor":"Instance-Methods"}],"abstract":[{"type":"text","text":"Location information."}],"seeAlsoSections":[{"generated":true,"title":"Location","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationManager","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck2DConfiguration","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Model","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckBearing","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProviderDelegate","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Coordinate2D","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationExtraKeys","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProviderRequest","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceFactory","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/DeviceLocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Heading","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckRenderingData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/IntervalSettings"],"anchor":"Location"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Location"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXLocation/bearing":{"abstract":[{"type":"text","text":"The GNSS bearing, in degrees."}],"role":"symbol","kind":"symbol","url":"\/documentation\/mapboxcommon\/mbxlocation\/bearing","fragments":[{"text":"bearing","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXLocation\/bearing","title":"bearing","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Location/init(CLLocation:extra:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithCLLocation:extra:"}],"title":"init(CLLocation:extra:)","abstract":[],"url":"\/documentation\/mapboxcommon\/location\/init(cllocation:extra:)","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location\/init(CLLocation:extra:)","role":"symbol","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"CLLocation"},{"kind":"text","text":": "},{"text":"CLLocation","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CLLocation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"extra"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXLocation/verticalAccuracy":{"abstract":[{"text":"The estimated vertical accuracy of this location, in meters.","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/mapboxcommon\/mbxlocation\/verticalaccuracy","fragments":[{"text":"verticalAccuracy","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXLocation\/verticalAccuracy","title":"verticalAccuracy","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Coordinate2D":{"title":"Coordinate2D","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Coordinate2D","abstract":[{"type":"text","text":"Boxed version of CLLocationCoordinate2D"}],"url":"\/documentation\/mapboxcommon\/coordinate2d","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Coordinate2D","kind":"identifier"}],"navigatorTitle":[{"text":"Coordinate2D","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PuckType":{"title":"PuckType","kind":"symbol","abstract":[{"text":"Represents the different types of pucks","type":"text"}],"type":"topic","url":"\/documentation\/mapboxmaps\/pucktype","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PuckType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PuckType"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckType"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXLocation/monotonicTimestamp":{"url":"\/documentation\/mapboxcommon\/mbxlocation\/monotonictimestamp","abstract":[{"type":"text","text":"The monotonic timestamp, in nanoseconds."}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXLocation\/monotonicTimestamp","kind":"symbol","fragments":[{"kind":"identifier","text":"monotonicTimestamp"}],"title":"monotonicTimestamp","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationProvider":{"title":"LocationProvider","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocationProvider"}],"kind":"symbol","url":"\/documentation\/mapboxcommon\/locationprovider","abstract":[{"text":"Location provider that provides locations","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"LocationProvider","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeadingProvider":{"title":"HeadingProvider","type":"topic","navigatorTitle":[{"text":"HeadingProvider","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/headingprovider","abstract":[{"type":"text","text":"Provides heading data to drive the location puck."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingProvider","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeadingProvider"}]},"doc://com.mapbox.MapboxMaps/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXLocation/latitude":{"abstract":[{"text":"The north–south position of a point on the Earth’s surface, in decimal degrees (WGS84).","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/mapboxcommon\/mbxlocation\/latitude","fragments":[{"text":"latitude","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXLocation\/latitude","title":"latitude","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Location/bearing":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"bearing","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CLLocationDirection","preciseIdentifier":"c:@T@CLLocationDirection","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"role":"symbol","type":"topic","kind":"symbol","title":"bearing","url":"\/documentation\/mapboxcommon\/location\/bearing","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location\/bearing","abstract":[{"text":"The GNSS bearing, in degrees.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Location-APIs":{"kind":"article","abstract":[],"type":"topic","title":"Location","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/location-apis","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Location/extra":{"url":"\/documentation\/mapboxcommon\/location\/extra","kind":"symbol","navigatorTitle":[{"text":"extra","kind":"identifier"}],"type":"topic","title":"extra","abstract":[{"type":"text","text":"Additional information"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"extra"},{"text":": ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location\/extra"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationExtraKeys":{"title":"LocationExtraKeys","kind":"symbol","abstract":[{"type":"text","text":"Keys for additional information (extra) in Location."}],"type":"topic","url":"\/documentation\/mapboxcommon\/locationextrakeys","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationExtraKeys"}],"navigatorTitle":[{"text":"LocationExtraKeys","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationExtraKeys"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXLocation/bearingAccuracy":{"title":"bearingAccuracy","abstract":[{"text":"The estimated bearing accuracy of this location, in degrees.","type":"text"}],"url":"\/documentation\/mapboxcommon\/mbxlocation\/bearingaccuracy","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXLocation\/bearingAccuracy","role":"symbol","kind":"symbol","fragments":[{"text":"bearingAccuracy","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Location/isEqual(to:)":{"abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/mapboxcommon\/location\/isequal(to:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Location","preciseIdentifier":"c:objc(cs)MBXLocation"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location\/isEqual(to:)","title":"isEqual(to:)","type":"topic","navigatorTitle":[{"text":"isEqualToLocation:","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/AccuracyLevel":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AccuracyLevel"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel","abstract":[{"type":"text","text":"The accuracy of the observed location"}],"role":"symbol","type":"topic","url":"\/documentation\/mapboxcommon\/accuracylevel","kind":"symbol","title":"AccuracyLevel","navigatorTitle":[{"kind":"identifier","text":"AccuracyLevel"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Location/speedAccuracy":{"title":"speedAccuracy","abstract":[{"text":"The estimated speed accuracy of this location, in meters\/second.","type":"text"}],"url":"\/documentation\/mapboxcommon\/location\/speedaccuracy","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location\/speedAccuracy","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"speedAccuracy"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CLLocationSpeedAccuracy","kind":"typeIdentifier","text":"CLLocationSpeedAccuracy"},{"kind":"text","text":"?"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PermissionStatus":{"title":"PermissionStatus","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus","abstract":[{"type":"text","text":"Location permissions granted by user to the app."}],"url":"\/documentation\/mapboxcommon\/permissionstatus","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PermissionStatus","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PermissionStatus"}],"type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Location/floor":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"floor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location\/floor","url":"\/documentation\/mapboxcommon\/location\/floor","role":"symbol","abstract":[{"text":"The logical floor of the building.","type":"text"}],"title":"floor"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXLocation/timestamp":{"url":"\/documentation\/mapboxcommon\/mbxlocation\/timestamp","kind":"symbol","title":"timestamp","fragments":[{"kind":"identifier","text":"timestamp"}],"abstract":[{"type":"text","text":"The UTC time of this location fix, in milliseconds since epoch (January 1, 1970)."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXLocation\/timestamp","type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Puck3DConfiguration":{"abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Puck3DConfiguration"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration","navigatorTitle":[{"text":"Puck3DConfiguration","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/puck3dconfiguration","title":"Puck3DConfiguration","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Location/horizontalAccuracy":{"kind":"symbol","role":"symbol","title":"horizontalAccuracy","url":"\/documentation\/mapboxcommon\/location\/horizontalaccuracy","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"horizontalAccuracy","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@CLLocationAccuracy","text":"CLLocationAccuracy","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"type":"topic","abstract":[{"text":"The estimated horizontal accuracy of this location, radial, in meters.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location\/horizontalAccuracy"},"doc://com.mapbox.MapboxMaps/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Location/speed":{"title":"speed","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"speed"},{"kind":"text","text":": "},{"text":"CLLocationSpeed","preciseIdentifier":"c:@T@CLLocationSpeed","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"The instantaneous speed of the device, measured in meters\/second over ground."}],"kind":"symbol","url":"\/documentation\/mapboxcommon\/location\/speed","role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location\/speed"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationErrorCode":{"title":"LocationErrorCode","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode","abstract":[{"type":"text","text":"Codes of location errors."}],"url":"\/documentation\/mapboxcommon\/locationerrorcode","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"LocationErrorCode","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"LocationErrorCode"}],"type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PuckBearing":{"title":"PuckBearing","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckBearing","abstract":[{"text":"Controls how the puck is oriented","type":"text"}],"url":"\/documentation\/mapboxmaps\/puckbearing","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PuckBearing"}],"navigatorTitle":[{"kind":"identifier","text":"PuckBearing"}],"type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationServiceFactory":{"title":"LocationServiceFactory","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceFactory","abstract":[{"type":"text","text":"Location service factory."}],"url":"\/documentation\/mapboxcommon\/locationservicefactory","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"LocationServiceFactory","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"LocationServiceFactory"}],"type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Model":{"title":"Model","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Model","abstract":[{"type":"text","text":"A structure represeting a Model"}],"url":"\/documentation\/mapboxmaps\/model","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Model"}],"navigatorTitle":[{"text":"Model","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Location/altitude":{"type":"topic","title":"altitude","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location\/altitude","abstract":[{"type":"text","text":"The altitude of the location in meters above the WGS84 reference ellipsoid."}],"role":"symbol","url":"\/documentation\/mapboxcommon\/location\/altitude","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"altitude"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationDistance","preciseIdentifier":"c:@T@CLLocationDistance"},{"text":"?","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","role":"collection","title":"MapboxMaps","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXLocation/horizontalAccuracy":{"url":"\/documentation\/mapboxcommon\/mbxlocation\/horizontalaccuracy","kind":"symbol","title":"horizontalAccuracy","fragments":[{"kind":"identifier","text":"horizontalAccuracy"}],"abstract":[{"text":"The estimated horizontal accuracy of this location, radial, in meters.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXLocation\/horizontalAccuracy","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationObserver":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationObserver","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationObserver"}],"url":"\/documentation\/mapboxcommon\/locationobserver","role":"symbol","title":"LocationObserver","navigatorTitle":[{"text":"LocationObserver","kind":"identifier"}],"abstract":[{"type":"text","text":"Observer for getting updates from a LocationProvider."}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Location/verticalAccuracy":{"url":"\/documentation\/mapboxcommon\/location\/verticalaccuracy","kind":"symbol","title":"verticalAccuracy","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"verticalAccuracy"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CLLocationAccuracy","kind":"typeIdentifier","text":"CLLocationAccuracy"},{"kind":"text","text":"?"}],"type":"topic","abstract":[{"text":"The estimated vertical accuracy of this location, in meters.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location\/verticalAccuracy","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXLocation/longitude":{"url":"\/documentation\/mapboxcommon\/mbxlocation\/longitude","kind":"symbol","title":"longitude","fragments":[{"kind":"identifier","text":"longitude"}],"abstract":[{"text":"The east–west position of a point on the Earth’s surface, in decimal degrees (WGS84).","type":"text"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXLocation\/longitude","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PuckRenderingData":{"title":"PuckRenderingData","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckRenderingData","abstract":[{"type":"text","text":"Represents the interpolated data ready to render the user location puck."}],"url":"\/documentation\/mapboxmaps\/puckrenderingdata","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PuckRenderingData"}],"navigatorTitle":[{"text":"PuckRenderingData","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Location/source":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"source","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"role":"symbol","abstract":[{"text":"The source that provides this location","type":"text"}],"navigatorTitle":[{"text":"source","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location\/source","url":"\/documentation\/mapboxcommon\/location\/source","kind":"symbol","title":"source"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/DeviceLocationProvider":{"title":"DeviceLocationProvider","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/DeviceLocationProvider","abstract":[{"text":"Location provider specialisation that provides real-time locations generated from the device","type":"text"}],"url":"\/documentation\/mapboxcommon\/devicelocationprovider","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"DeviceLocationProvider","kind":"identifier"}],"navigatorTitle":[{"text":"DeviceLocationProvider","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/AccuracyAuthorization":{"title":"AccuracyAuthorization","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization","abstract":[{"type":"text","text":"Accuracy authorization granted by user to the app."}],"kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AccuracyAuthorization","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxcommon\/accuracyauthorization","navigatorTitle":[{"text":"AccuracyAuthorization","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LocationManager":{"title":"LocationManager","kind":"symbol","abstract":[{"type":"text","text":"An object responsible for managing user location Puck."}],"type":"topic","url":"\/documentation\/mapboxmaps\/locationmanager","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationManager"}],"navigatorTitle":[{"text":"LocationManager","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationManager"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXLocation/speed":{"url":"\/documentation\/mapboxcommon\/mbxlocation\/speed","kind":"symbol","title":"speed","fragments":[{"kind":"identifier","text":"speed"}],"abstract":[{"text":"The instantaneous speed of the device, measured in meters\/second over ground.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXLocation\/speed","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AppleLocationProviderDelegate":{"url":"\/documentation\/mapboxmaps\/applelocationproviderdelegate","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProviderDelegate","kind":"symbol","abstract":[{"type":"text","text":"The "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProviderDelegate","isActive":true,"type":"reference"},{"text":" protocol defines a set of optional methods that you","type":"text"},{"type":"text","text":" "},{"type":"text","text":"can use to receive events from an associated location provider object."}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"AppleLocationProviderDelegate","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"AppleLocationProviderDelegate","kind":"identifier"}],"title":"AppleLocationProviderDelegate"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXLocation/floor":{"role":"symbol","abstract":[{"type":"text","text":"The logical floor of the building."}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXLocation\/floor","fragments":[{"kind":"identifier","text":"floor"}],"title":"floor","type":"topic","url":"\/documentation\/mapboxcommon\/mbxlocation\/floor"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Location/timestamp":{"url":"\/documentation\/mapboxcommon\/location\/timestamp","kind":"symbol","title":"timestamp","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"timestamp","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"}],"type":"topic","abstract":[{"text":"The time at which this location was determined.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location\/timestamp","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXLocation/altitude":{"url":"\/documentation\/mapboxcommon\/mbxlocation\/altitude","kind":"symbol","title":"altitude","fragments":[{"kind":"identifier","text":"altitude"}],"abstract":[{"text":"The altitude of the location in meters above the WGS84 reference ellipsoid.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXLocation\/altitude","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXLocation/speedAccuracy":{"url":"\/documentation\/mapboxcommon\/mbxlocation\/speedaccuracy","kind":"symbol","title":"speedAccuracy","fragments":[{"kind":"identifier","text":"speedAccuracy"}],"type":"topic","abstract":[{"text":"The estimated speed accuracy of this location, in meters\/second.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXLocation\/speedAccuracy","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeadingObserver":{"title":"HeadingObserver","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingObserver","abstract":[{"type":"text","text":"Listens to "},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingProvider","isActive":true},{"text":"’s updates.","type":"text"}],"url":"\/documentation\/mapboxmaps\/headingobserver","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeadingObserver"}],"navigatorTitle":[{"text":"HeadingObserver","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationError":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationError","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"LocationError","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/locationerror","role":"symbol","title":"LocationError","navigatorTitle":[{"kind":"identifier","text":"LocationError"}],"abstract":[{"type":"text","text":"Error code with brief explanation."}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","type":"topic","kind":"article","abstract":[],"role":"collection","title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Location/init(CLLocation:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithCLLocation:"}],"title":"init(CLLocation:)","abstract":[],"url":"\/documentation\/mapboxcommon\/location\/init(cllocation:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location\/init(CLLocation:)","type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"CLLocation"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)CLLocation","kind":"typeIdentifier","text":"CLLocation"},{"kind":"text","text":")"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Puck2DConfiguration":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck2DConfiguration","type":"topic","title":"Puck2DConfiguration","url":"\/documentation\/mapboxmaps\/puck2dconfiguration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Puck2DConfiguration"}],"abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Puck2DConfiguration","kind":"identifier"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/IntervalSettings":{"title":"IntervalSettings","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/IntervalSettings","abstract":[{"type":"text","text":"The interval for active location updates"}],"url":"\/documentation\/mapboxcommon\/intervalsettings","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"IntervalSettings","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"IntervalSettings"}],"type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Location/init(coordinate:timestamp:altitude:horizontalAccuracy:verticalAccuracy:speed:speedAccuracy:bearing:bearingAccuracy:floor:source:extra:)":{"url":"\/documentation\/mapboxcommon\/location\/init(coordinate:timestamp:altitude:horizontalaccuracy:verticalaccuracy:speed:speedaccuracy:bearing:bearingaccuracy:floor:source:extra:)","title":"init(coordinate:timestamp:altitude:horizontalAccuracy:verticalAccuracy:speed:speedAccuracy:bearing:bearingAccuracy:floor:source:extra:)","role":"symbol","fragments":[{"text":"convenience","kind":"keyword"},{"kind":"text","text":" "},{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"coordinate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":", "},{"text":"timestamp","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"altitude"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CLLocationDistance","text":"CLLocationDistance","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"horizontalAccuracy","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CLLocationAccuracy","kind":"typeIdentifier","preciseIdentifier":"c:@T@CLLocationAccuracy"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"verticalAccuracy"},{"kind":"text","text":": "},{"text":"CLLocationAccuracy","preciseIdentifier":"c:@T@CLLocationAccuracy","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"speed","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CLLocationSpeed","kind":"typeIdentifier","text":"CLLocationSpeed"},{"text":"?, ","kind":"text"},{"text":"speedAccuracy","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CLLocationSpeedAccuracy","kind":"typeIdentifier","preciseIdentifier":"c:@T@CLLocationSpeedAccuracy"},{"text":"?, ","kind":"text"},{"text":"bearing","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CLLocationDirection","text":"CLLocationDirection"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"bearingAccuracy"},{"text":": ","kind":"text"},{"text":"CLLocationDirectionAccuracy","kind":"typeIdentifier","preciseIdentifier":"c:@T@CLLocationDirectionAccuracy"},{"text":"?, ","kind":"text"},{"text":"floor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":"?, "},{"text":"source","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"text":"extra","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?)"}],"abstract":[{"text":"Creates location.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location\/init(coordinate:timestamp:altitude:horizontalAccuracy:verticalAccuracy:speed:speedAccuracy:bearing:bearingAccuracy:floor:source:extra:)","type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LocationOptions":{"title":"LocationOptions","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocationOptions"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/locationoptions","abstract":[{"type":"text","text":"A struct to configure a "},{"type":"codeVoice","code":"LocationManager"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationOptions","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"LocationOptions","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AppleLocationProvider":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppleLocationProvider"}],"url":"\/documentation\/mapboxmaps\/applelocationprovider","kind":"symbol","role":"symbol","title":"AppleLocationProvider","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProvider","navigatorTitle":[{"text":"AppleLocationProvider","kind":"identifier"}],"abstract":[{"type":"text","text":"A location provider based on CoreLocation’s "},{"type":"codeVoice","code":"CLLocationManager"},{"type":"text","text":"."}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXLocation/initWithLatitude:longitude:timestamp:monotonicTimestamp:altitude:horizontalAccuracy:verticalAccuracy:speed:speedAccuracy:bearing:bearingAccuracy:floor:source:extra:":{"title":"initWithLatitude:longitude:timestamp:monotonicTimestamp:altitude:horizontalAccuracy:verticalAccuracy:speed:speedAccuracy:bearing:bearingAccuracy:floor:source:extra:","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXLocation\/initWithLatitude:longitude:timestamp:monotonicTimestamp:altitude:horizontalAccuracy:verticalAccuracy:speed:speedAccuracy:bearing:bearingAccuracy:floor:source:extra:","fragments":[{"kind":"text","text":"- "},{"text":"initWithLatitude:longitude:timestamp:monotonicTimestamp:altitude:horizontalAccuracy:verticalAccuracy:speed:speedAccuracy:bearing:bearingAccuracy:floor:source:extra:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapboxcommon\/mbxlocation\/initwithlatitude:longitude:timestamp:monotonictimestamp:altitude:horizontalaccuracy:verticalaccuracy:speed:speedaccuracy:bearing:bearingaccuracy:floor:source:extra:","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithLatitude:longitude:timestamp:monotonicTimestamp:altitude:horizontalAccuracy:verticalAccuracy:speed:speedAccuracy:bearing:bearingAccuracy:floor:source:extra:"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ"},"doc://com.mapbox.MapboxMaps/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Heading":{"abstract":[{"text":"The azimuth (orientation) of the user’s device, relative to true or magnetic north.","type":"text"}],"type":"topic","url":"\/documentation\/mapboxmaps\/heading","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Heading","kind":"identifier"}],"kind":"symbol","title":"Heading","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Heading"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Heading"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationServiceObserver":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LocationServiceObserver"}],"url":"\/documentation\/mapboxcommon\/locationserviceobserver","role":"symbol","title":"LocationServiceObserver","navigatorTitle":[{"text":"LocationServiceObserver","kind":"identifier"}],"abstract":[{"type":"text","text":"Observers for getting updates from LocationService."}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Location":{"title":"Location","type":"topic","navigatorTitle":[{"text":"Location","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapboxcommon\/location","abstract":[{"text":"Location information.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Location","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Location/bearingAccuracy":{"role":"symbol","url":"\/documentation\/mapboxcommon\/location\/bearingaccuracy","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location\/bearingAccuracy","abstract":[{"text":"The estimated bearing accuracy of this location, in degrees.","type":"text"}],"type":"topic","kind":"symbol","title":"bearingAccuracy","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bearingAccuracy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CLLocationDirectionAccuracy","text":"CLLocationDirectionAccuracy"},{"text":"?","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Location/coordinate":{"abstract":[{"type":"text","text":"The geographical coordinate information."}],"type":"topic","role":"symbol","title":"coordinate","url":"\/documentation\/mapboxcommon\/location\/coordinate","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location\/coordinate","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"coordinate","kind":"identifier"},{"kind":"text","text":": "},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationProviderRequest":{"title":"LocationProviderRequest","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProviderRequest","abstract":[{"type":"text","text":"Data model that contains parameters for location requests."}],"url":"\/documentation\/mapboxcommon\/locationproviderrequest","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LocationProviderRequest"}],"navigatorTitle":[{"text":"LocationProviderRequest","kind":"identifier"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MBXLocation"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MBXLocation"}]},{"value":[{"text":"MBXLocation","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location\/extra","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location\/source","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXLocation\/altitude","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXLocation\/bearing","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXLocation\/bearingAccuracy","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXLocation\/floor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXLocation\/horizontalAccuracy","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXLocation\/latitude","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXLocation\/longitude","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXLocation\/monotonicTimestamp","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXLocation\/speed","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXLocation\/speedAccuracy","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXLocation\/timestamp","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXLocation\/verticalAccuracy"],"generated":true,"title":"Instance Properties"},{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location\/init(CLLocation:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location\/init(CLLocation:extra:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location\/isEqual(to:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXLocation\/initWithLatitude:longitude:timestamp:monotonicTimestamp:altitude:horizontalAccuracy:verticalAccuracy:speed:speedAccuracy:bearing:bearingAccuracy:floor:source:extra:"],"generated":true}]},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"]}],"op":"replace"},{"op":"replace","value":[{"title":"Location","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Coordinate2D","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationExtraKeys","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProviderRequest","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceFactory","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/DeviceLocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/IntervalSettings"],"anchor":"Location"}],"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBXLocation","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location~1init(CLLocation:extra:)\/title","value":"initWithCLLocation:extra:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location~1init(CLLocation:extra:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCLLocation:extra:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Coordinate2D\/title","value":"MBXCoordinate2D"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Coordinate2D\/fragments","value":[{"text":"MBXCoordinate2D","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Coordinate2D\/navigatorTitle","value":[{"text":"MBXCoordinate2D","kind":"identifier"}],"op":"replace"},{"value":"MBXLocationProvider","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/fragments","value":[{"text":"MBXLocationProvider","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/navigatorTitle","value":[{"text":"MBXLocationProvider","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location~1extra\/title","value":"extra"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location~1extra\/fragments","value":[{"kind":"identifier","text":"extra"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationExtraKeys\/title","value":"MBXLocationExtraKeys","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationExtraKeys\/fragments","value":[{"text":"MBXLocationExtraKeys","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationExtraKeys\/navigatorTitle","value":[{"kind":"identifier","text":"MBXLocationExtraKeys"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location~1isEqual(to:)\/title","op":"replace","value":"isEqualToLocation:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqualToLocation:"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location~1isEqual(to:)\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel\/title","value":"MBXAccuracyLevel","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel\/fragments","op":"replace","value":[{"text":"MBXAccuracyLevel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel\/navigatorTitle","op":"replace","value":[{"text":"MBXAccuracyLevel","kind":"identifier"}]},{"op":"replace","value":"MBXPermissionStatus","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/fragments","value":[{"text":"MBXPermissionStatus","kind":"identifier"}]},{"value":[{"text":"MBXPermissionStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/title","value":"MBXLocationErrorCode","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBXLocationErrorCode"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/fragments"},{"value":[{"kind":"identifier","text":"MBXLocationErrorCode"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/navigatorTitle"},{"value":"MBXLocationServiceFactory","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceFactory\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceFactory\/fragments","value":[{"text":"MBXLocationServiceFactory","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceFactory\/navigatorTitle","value":[{"text":"MBXLocationServiceFactory","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/title","value":"MBXLocationObserver"},{"op":"replace","value":[{"text":"MBXLocationObserver","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/fragments"},{"value":[{"text":"MBXLocationObserver","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/navigatorTitle"},{"op":"replace","value":"source","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location~1source\/title"},{"value":[{"text":"source","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location~1source\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1DeviceLocationProvider\/title","value":"MBXDeviceLocationProvider"},{"value":[{"text":"MBXDeviceLocationProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1DeviceLocationProvider\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1DeviceLocationProvider\/navigatorTitle","value":[{"text":"MBXDeviceLocationProvider","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization\/title","op":"replace","value":"MBXAccuracyAuthorization"},{"value":[{"kind":"identifier","text":"MBXAccuracyAuthorization"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization\/fragments","op":"replace"},{"value":[{"text":"MBXAccuracyAuthorization","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationError\/title","value":"MBXLocationError","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationError\/fragments","value":[{"kind":"identifier","text":"MBXLocationError"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationError\/navigatorTitle","op":"replace","value":[{"text":"MBXLocationError","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location~1init(CLLocation:)\/title","value":"initWithCLLocation:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location~1init(CLLocation:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithCLLocation:","kind":"identifier"}]},{"value":"MBXIntervalSettings","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1IntervalSettings\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1IntervalSettings\/fragments","op":"replace","value":[{"text":"MBXIntervalSettings","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1IntervalSettings\/navigatorTitle","value":[{"text":"MBXIntervalSettings","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver\/title","value":"MBXLocationServiceObserver"},{"value":[{"kind":"identifier","text":"MBXLocationServiceObserver"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver\/fragments"},{"value":[{"text":"MBXLocationServiceObserver","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/title","value":"MBXLocation"},{"op":"replace","value":[{"text":"MBXLocation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/fragments"},{"value":[{"text":"MBXLocation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProviderRequest\/title","value":"MBXLocationProviderRequest","op":"replace"},{"value":[{"kind":"identifier","text":"MBXLocationProviderRequest"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProviderRequest\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProviderRequest\/navigatorTitle","value":[{"kind":"identifier","text":"MBXLocationProviderRequest"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}