{"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","sections":[],"seeAlsoSections":[{"anchor":"Location","title":"Location","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationManager","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck2DConfiguration","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Model","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckBearing","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProviderDelegate","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Coordinate2D","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationExtraKeys","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProviderRequest","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceFactory","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/DeviceLocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Heading","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckRenderingData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/IntervalSettings"],"generated":true}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs"]]},"metadata":{"title":"LocationObserver","role":"symbol","externalID":"c:objc(pl)MBXLocationObserver","roleHeading":"Protocol","modules":[{"name":"MapboxCommon"}],"symbolKind":"protocol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"LocationObserver","kind":"identifier"}],"navigatorTitle":[{"text":"LocationObserver","kind":"identifier"}]},"topicSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationObserver\/onLocationUpdateReceived(for:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationObserver","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Observer for getting updates from a LocationProvider."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationObserver","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/locationobserver"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/locationobserver"]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationErrorCode":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"LocationErrorCode","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapboxcommon\/locationerrorcode","abstract":[{"text":"Codes of location errors.","type":"text"}],"title":"LocationErrorCode","navigatorTitle":[{"kind":"identifier","text":"LocationErrorCode"}],"type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/AccuracyAuthorization":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization","role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/mapboxcommon\/accuracyauthorization","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AccuracyAuthorization"}],"navigatorTitle":[{"text":"AccuracyAuthorization","kind":"identifier"}],"abstract":[{"type":"text","text":"Accuracy authorization granted by user to the app."}],"title":"AccuracyAuthorization"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Model":{"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Model"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Model","title":"Model","type":"topic","url":"\/documentation\/mapboxmaps\/model","abstract":[{"type":"text","text":"A structure represeting a Model"}],"navigatorTitle":[{"kind":"identifier","text":"Model"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","role":"collection","url":"\/documentation\/overview","kind":"article","abstract":[],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PuckBearing":{"abstract":[{"type":"text","text":"Controls how the puck is oriented"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PuckBearing","kind":"identifier"}],"title":"PuckBearing","type":"topic","url":"\/documentation\/mapboxmaps\/puckbearing","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckBearing","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PuckBearing"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PuckRenderingData":{"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"PuckRenderingData"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckRenderingData","title":"PuckRenderingData","type":"topic","url":"\/documentation\/mapboxmaps\/puckrenderingdata","abstract":[{"text":"Represents the interpolated data ready to render the user location puck.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"PuckRenderingData"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Location":{"title":"Location","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Location"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Location","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxcommon\/location","abstract":[{"type":"text","text":"Location information."}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeadingProvider":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingProvider","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"HeadingProvider","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/headingprovider","abstract":[{"text":"Provides heading data to drive the location puck.","type":"text"}],"title":"HeadingProvider","navigatorTitle":[{"text":"HeadingProvider","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationServiceFactory":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationServiceFactory","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"LocationServiceFactory"}],"url":"\/documentation\/mapboxcommon\/locationservicefactory","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceFactory","title":"LocationServiceFactory","abstract":[{"type":"text","text":"Location service factory."}],"kind":"symbol","type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PermissionStatus":{"url":"\/documentation\/mapboxcommon\/permissionstatus","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PermissionStatus","kind":"identifier"}],"abstract":[{"text":"Location permissions granted by user to the app.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"PermissionStatus"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus","role":"symbol","kind":"symbol","type":"topic","title":"PermissionStatus"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Heading":{"abstract":[{"type":"text","text":"The azimuth (orientation) of the user’s device, relative to true or magnetic north."}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"Heading","kind":"identifier"}],"title":"Heading","type":"topic","url":"\/documentation\/mapboxmaps\/heading","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Heading","role":"symbol","navigatorTitle":[{"text":"Heading","kind":"identifier"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LocationOptions":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationOptions","url":"\/documentation\/mapboxmaps\/locationoptions","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LocationOptions"}],"abstract":[{"type":"text","text":"A struct to configure a "},{"code":"LocationManager","type":"codeVoice"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"LocationOptions"}],"title":"LocationOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"title":"MapboxMaps","kind":"symbol","role":"collection","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AppleLocationProviderDelegate":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProviderDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"AppleLocationProviderDelegate","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/applelocationproviderdelegate","abstract":[{"type":"text","text":"The "},{"isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProviderDelegate","type":"reference"},{"type":"text","text":" protocol defines a set of optional methods that you"},{"type":"text","text":" "},{"text":"can use to receive events from an associated location provider object.","type":"text"}],"title":"AppleLocationProviderDelegate","navigatorTitle":[{"kind":"identifier","text":"AppleLocationProviderDelegate"}],"type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationProviderRequest":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationProviderRequest"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProviderRequest","title":"LocationProviderRequest","url":"\/documentation\/mapboxcommon\/locationproviderrequest","abstract":[{"text":"Data model that contains parameters for location requests.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"LocationProviderRequest"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Location-APIs":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","type":"topic","kind":"article","abstract":[],"url":"\/documentation\/mapboxmaps\/location-apis","title":"Location","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PuckType":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PuckType"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/pucktype","abstract":[{"text":"Represents the different types of pucks","type":"text"}],"title":"PuckType","navigatorTitle":[{"kind":"identifier","text":"PuckType"}],"type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Puck2DConfiguration":{"title":"Puck2DConfiguration","kind":"symbol","navigatorTitle":[{"text":"Puck2DConfiguration","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck2DConfiguration","abstract":[],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Puck2DConfiguration"}],"type":"topic","url":"\/documentation\/mapboxmaps\/puck2dconfiguration"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/IntervalSettings":{"abstract":[{"text":"The interval for active location updates","type":"text"}],"url":"\/documentation\/mapboxcommon\/intervalsettings","kind":"symbol","navigatorTitle":[{"text":"IntervalSettings","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"IntervalSettings","kind":"identifier"}],"role":"symbol","title":"IntervalSettings","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/IntervalSettings"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeadingObserver":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingObserver","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HeadingObserver"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/headingobserver","abstract":[{"type":"text","text":"Listens to "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingProvider"},{"text":"’s updates.","type":"text"}],"title":"HeadingObserver","navigatorTitle":[{"kind":"identifier","text":"HeadingObserver"}],"type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationProvider":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationProvider"}],"role":"symbol","url":"\/documentation\/mapboxcommon\/locationprovider","abstract":[{"text":"Location provider that provides locations","type":"text"}],"title":"LocationProvider","navigatorTitle":[{"kind":"identifier","text":"LocationProvider"}],"type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationExtraKeys":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationExtraKeys","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationExtraKeys"}],"role":"symbol","url":"\/documentation\/mapboxcommon\/locationextrakeys","abstract":[{"text":"Keys for additional information (extra) in Location.","type":"text"}],"title":"LocationExtraKeys","navigatorTitle":[{"kind":"identifier","text":"LocationExtraKeys"}],"type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationObserver/onLocationUpdateReceived(for:)":{"url":"\/documentation\/mapboxcommon\/locationobserver\/onlocationupdatereceived(for:)","abstract":[{"type":"text","text":"Report when location has changed."}],"required":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationObserver\/onLocationUpdateReceived(for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onLocationUpdateReceived"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBXLocation","text":"Location","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"role":"symbol","title":"onLocationUpdateReceived(for:)","navigatorTitle":[{"text":"onLocationUpdateReceivedForLocations:","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Coordinate2D":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Coordinate2D"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Coordinate2D","title":"Coordinate2D","url":"\/documentation\/mapboxcommon\/coordinate2d","abstract":[{"type":"text","text":"Boxed version of CLLocationCoordinate2D"}],"navigatorTitle":[{"kind":"identifier","text":"Coordinate2D"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationError":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationError","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationError"}],"role":"symbol","url":"\/documentation\/mapboxcommon\/locationerror","abstract":[{"text":"Error code with brief explanation.","type":"text"}],"title":"LocationError","navigatorTitle":[{"kind":"identifier","text":"LocationError"}],"type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AppleLocationProvider":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppleLocationProvider"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/applelocationprovider","abstract":[{"type":"text","text":"A location provider based on CoreLocation’s "},{"code":"CLLocationManager","type":"codeVoice"},{"type":"text","text":"."}],"title":"AppleLocationProvider","navigatorTitle":[{"text":"AppleLocationProvider","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationServiceObserver":{"abstract":[{"type":"text","text":"Observers for getting updates from LocationService."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LocationServiceObserver"}],"title":"LocationServiceObserver","type":"topic","url":"\/documentation\/mapboxcommon\/locationserviceobserver","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver","role":"symbol","navigatorTitle":[{"text":"LocationServiceObserver","kind":"identifier"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Puck3DConfiguration":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Puck3DConfiguration","kind":"identifier"}],"type":"topic","title":"Puck3DConfiguration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Puck3DConfiguration"}],"url":"\/documentation\/mapboxmaps\/puck3dconfiguration"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/DeviceLocationProvider":{"abstract":[{"type":"text","text":"Location provider specialisation that provides real-time locations generated from the device"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/DeviceLocationProvider","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"DeviceLocationProvider","kind":"identifier"}],"title":"DeviceLocationProvider","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DeviceLocationProvider"}],"url":"\/documentation\/mapboxcommon\/devicelocationprovider"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationObserver":{"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationObserver"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationObserver","title":"LocationObserver","type":"topic","url":"\/documentation\/mapboxcommon\/locationobserver","abstract":[{"type":"text","text":"Observer for getting updates from a LocationProvider."}],"navigatorTitle":[{"kind":"identifier","text":"LocationObserver"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/AccuracyLevel":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AccuracyLevel"}],"role":"symbol","url":"\/documentation\/mapboxcommon\/accuracylevel","abstract":[{"text":"The accuracy of the observed location","type":"text"}],"title":"AccuracyLevel","navigatorTitle":[{"kind":"identifier","text":"AccuracyLevel"}],"type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LocationManager":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationManager"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationManager","title":"LocationManager","url":"\/documentation\/mapboxmaps\/locationmanager","abstract":[{"type":"text","text":"An object responsible for managing user location Puck."}],"navigatorTitle":[{"kind":"identifier","text":"LocationManager"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"op":"replace","value":"MBXLocationObserver","path":"\/metadata\/title"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MBXLocationObserver","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MBXLocationObserver"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationObserver\/onLocationUpdateReceived(for:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}]},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Coordinate2D","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationExtraKeys","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProviderRequest","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceFactory","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/DeviceLocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/IntervalSettings"],"anchor":"Location","title":"Location"}]},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MBXLocationObserver","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/title","value":"MBXLocationErrorCode"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/fragments","value":[{"kind":"identifier","text":"MBXLocationErrorCode"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/navigatorTitle","value":[{"kind":"identifier","text":"MBXLocationErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization\/title","value":"MBXAccuracyAuthorization"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization\/fragments","value":[{"text":"MBXAccuracyAuthorization","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization\/navigatorTitle","value":[{"kind":"identifier","text":"MBXAccuracyAuthorization"}]},{"value":"MBXLocation","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/title","op":"replace"},{"value":[{"text":"MBXLocation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/fragments"},{"value":[{"kind":"identifier","text":"MBXLocation"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceFactory\/title","value":"MBXLocationServiceFactory","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceFactory\/fragments","value":[{"text":"MBXLocationServiceFactory","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceFactory\/navigatorTitle","value":[{"text":"MBXLocationServiceFactory","kind":"identifier"}],"op":"replace"},{"value":"MBXPermissionStatus","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/fragments","value":[{"kind":"identifier","text":"MBXPermissionStatus"}],"op":"replace"},{"value":[{"text":"MBXPermissionStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProviderRequest\/title","op":"replace","value":"MBXLocationProviderRequest"},{"op":"replace","value":[{"kind":"identifier","text":"MBXLocationProviderRequest"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProviderRequest\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProviderRequest\/navigatorTitle","value":[{"text":"MBXLocationProviderRequest","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1IntervalSettings\/title","value":"MBXIntervalSettings"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1IntervalSettings\/fragments","value":[{"text":"MBXIntervalSettings","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1IntervalSettings\/navigatorTitle","value":[{"text":"MBXIntervalSettings","kind":"identifier"}]},{"op":"replace","value":"MBXLocationProvider","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/title"},{"value":[{"text":"MBXLocationProvider","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/navigatorTitle","value":[{"text":"MBXLocationProvider","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationExtraKeys\/title","value":"MBXLocationExtraKeys"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationExtraKeys\/fragments","value":[{"text":"MBXLocationExtraKeys","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationExtraKeys\/navigatorTitle","value":[{"text":"MBXLocationExtraKeys","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver~1onLocationUpdateReceived(for:)\/title","value":"onLocationUpdateReceivedForLocations:"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver~1onLocationUpdateReceived(for:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onLocationUpdateReceivedForLocations:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Coordinate2D\/title","value":"MBXCoordinate2D","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Coordinate2D\/fragments","value":[{"kind":"identifier","text":"MBXCoordinate2D"}]},{"value":[{"text":"MBXCoordinate2D","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Coordinate2D\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationError\/title","value":"MBXLocationError"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationError\/fragments","value":[{"text":"MBXLocationError","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MBXLocationError"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationError\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver\/title","value":"MBXLocationServiceObserver"},{"op":"replace","value":[{"kind":"identifier","text":"MBXLocationServiceObserver"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver\/navigatorTitle","op":"replace","value":[{"text":"MBXLocationServiceObserver","kind":"identifier"}]},{"value":"MBXDeviceLocationProvider","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1DeviceLocationProvider\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1DeviceLocationProvider\/fragments","value":[{"kind":"identifier","text":"MBXDeviceLocationProvider"}],"op":"replace"},{"value":[{"kind":"identifier","text":"MBXDeviceLocationProvider"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1DeviceLocationProvider\/navigatorTitle","op":"replace"},{"value":"MBXLocationObserver","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/title","op":"replace"},{"value":[{"text":"MBXLocationObserver","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/navigatorTitle","value":[{"kind":"identifier","text":"MBXLocationObserver"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel\/title","value":"MBXAccuracyLevel"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel\/fragments","value":[{"kind":"identifier","text":"MBXAccuracyLevel"}]},{"value":[{"kind":"identifier","text":"MBXAccuracyLevel"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel\/navigatorTitle","op":"replace"}]}]}