{"schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LoggingLevel\/debug","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LoggingLevel\/error","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LoggingLevel\/info","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LoggingLevel\/warning"],"anchor":"Enumeration-Cases","title":"Enumeration Cases"},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LoggingLevel\/init(rawValue:)"],"title":"Initializers","anchor":"Initializers","generated":true},{"generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LoggingLevel\/Equatable-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LoggingLevel\/RawRepresentable-Implementations"],"title":"Default Implementations","anchor":"Default-Implementations"}],"abstract":[{"text":"State level of a log message.","type":"text"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/s15BitwiseCopyableP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH","doc:\/\/com.mapbox.MapboxMaps\/SY","doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"LoggingLevel","kind":"identifier"}],"languages":["swift"]}]}],"seeAlsoSections":[{"title":"Logs","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogConfiguration","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogWriterBackend"],"anchor":"Logs","generated":true}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LoggingLevel","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/mapboxcommon\/logginglevel"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/logginglevel"]}],"metadata":{"title":"LoggingLevel","role":"symbol","externalID":"c:@E@MBXLoggingLevel","symbolKind":"enum","roleHeading":"Enumeration","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LoggingLevel"}],"navigatorTitle":[{"text":"LoggingLevel","kind":"identifier"}],"modules":[{"name":"MapboxCommon"}]},"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","abstract":[],"type":"topic","kind":"article","title":"MapboxMaps Documentation","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LogConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogConfiguration"}],"kind":"symbol","abstract":[{"text":"Class that allows to configure Mapbox SDKs logging per application.","type":"text"}],"url":"\/documentation\/mapboxcommon\/logconfiguration","type":"topic","role":"symbol","title":"LogConfiguration","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogConfiguration","navigatorTitle":[{"text":"LogConfiguration","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LoggingLevel/info":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"info"}],"title":"LoggingLevel.info","url":"\/documentation\/mapboxcommon\/logginglevel\/info","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LoggingLevel\/info","type":"topic","abstract":[{"text":"Normal application behavior.","type":"text"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"MBXLoggingLevelInfo","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LoggingLevel/RawRepresentable-Implementations":{"role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LoggingLevel\/RawRepresentable-Implementations","kind":"article","url":"\/documentation\/mapboxcommon\/logginglevel\/rawrepresentable-implementations","abstract":[],"title":"RawRepresentable Implementations","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LoggingLevel/init(rawValue:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LoggingLevel\/init(rawValue:)","role":"symbol","abstract":[],"url":"\/documentation\/mapboxcommon\/logginglevel\/init(rawvalue:)","kind":"symbol","title":"init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Performance":{"abstract":[],"role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","title":"Performance and investigations","url":"\/documentation\/mapboxmaps\/performance","kind":"article","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LogWriterBackend":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogWriterBackend"}],"kind":"symbol","abstract":[{"type":"text","text":"Interface for implementing log writing backends, e.g. for using platform specific log backends or logging to a notification service."}],"url":"\/documentation\/mapboxcommon\/logwriterbackend","type":"topic","role":"symbol","title":"LogWriterBackend","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogWriterBackend","navigatorTitle":[{"text":"LogWriterBackend","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"},"doc://com.mapbox.MapboxMaps/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LoggingLevel/error":{"navigatorTitle":[{"kind":"identifier","text":"MBXLoggingLevelError"}],"url":"\/documentation\/mapboxcommon\/logginglevel\/error","abstract":[{"type":"text","text":"A log message providing information when a significant error occurred."}],"title":"LoggingLevel.error","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LoggingLevel\/error","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SY"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LoggingLevel":{"kind":"symbol","title":"LoggingLevel","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"LoggingLevel","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"LoggingLevel"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LoggingLevel","abstract":[{"type":"text","text":"State level of a log message."}],"role":"symbol","url":"\/documentation\/mapboxcommon\/logginglevel"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LoggingLevel/debug":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"debug"}],"title":"LoggingLevel.debug","url":"\/documentation\/mapboxcommon\/logginglevel\/debug","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LoggingLevel\/debug","abstract":[{"type":"text","text":"Verbose log data to understand how the code executes."}],"type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"MBXLoggingLevelDebug","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LoggingLevel/Equatable-Implementations":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LoggingLevel\/Equatable-Implementations","role":"collectionGroup","abstract":[],"kind":"article","url":"\/documentation\/mapboxcommon\/logginglevel\/equatable-implementations","title":"Equatable Implementations","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","url":"\/documentation\/mapboxmaps","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"title":"MapboxMaps","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LoggingLevel/warning":{"url":"\/documentation\/mapboxcommon\/logginglevel\/warning","kind":"symbol","navigatorTitle":[{"text":"MBXLoggingLevelWarning","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LoggingLevel\/warning","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"warning"}],"title":"LoggingLevel.warning","type":"topic","abstract":[{"text":"To log a situation that might be a problem, or an unusual situation.","type":"text"}]},"doc://com.mapbox.MapboxMaps/s15BitwiseCopyableP":{"title":"Swift.BitwiseCopyable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s15BitwiseCopyableP"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"MBXLoggingLevel"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"MBXLoggingLevel","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBXLoggingLevel"}]},{"value":[{"generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LoggingLevel\/debug","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LoggingLevel\/error","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LoggingLevel\/info","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LoggingLevel\/warning"],"anchor":"Enumeration-Cases","title":"Enumeration Cases"}],"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","op":"replace","value":[{"title":"Logs","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogConfiguration","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogWriterBackend"],"generated":true,"anchor":"Logs"}]},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBXLoggingLevel"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogConfiguration\/title","op":"replace","value":"MBXLogConfiguration"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogConfiguration\/fragments","value":[{"kind":"identifier","text":"MBXLogConfiguration"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogConfiguration\/navigatorTitle","value":[{"text":"MBXLogConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LoggingLevel~1info\/title","op":"replace","value":"MBXLoggingLevelInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LoggingLevel~1info\/fragments","value":[{"kind":"identifier","text":"MBXLoggingLevelInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogWriterBackend\/title","value":"MBXLogWriterBackend"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogWriterBackend\/fragments","value":[{"text":"MBXLogWriterBackend","kind":"identifier"}]},{"op":"replace","value":[{"text":"MBXLogWriterBackend","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogWriterBackend\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LoggingLevel~1error\/title","op":"replace","value":"MBXLoggingLevelError"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LoggingLevel~1error\/fragments","value":[{"kind":"identifier","text":"MBXLoggingLevelError"}],"op":"replace"},{"value":"MBXLoggingLevel","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LoggingLevel\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBXLoggingLevel"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LoggingLevel\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LoggingLevel\/navigatorTitle","value":[{"kind":"identifier","text":"MBXLoggingLevel"}]},{"value":"MBXLoggingLevelDebug","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LoggingLevel~1debug\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LoggingLevel~1debug\/fragments","value":[{"kind":"identifier","text":"MBXLoggingLevelDebug"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LoggingLevel~1warning\/title","value":"MBXLoggingLevelWarning"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LoggingLevel~1warning\/fragments","value":[{"kind":"identifier","text":"MBXLoggingLevelWarning"}],"op":"replace"}]}]}