{"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXAccuracyAuthorizationToString(_:)","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/mapboxcommon\/mbxaccuracyauthorizationtostring(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/mbxaccuracyauthorizationtostring(_:)"]}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"MBXAccuracyAuthorizationToString","kind":"identifier"},{"kind":"text","text":"("},{"text":"AccuracyAuthorization","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBXAccuracyAuthorization"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"!","kind":"text"}],"navigatorTitle":[{"text":"MBXAccuracyAuthorizationToString","kind":"identifier"}],"symbolKind":"func","role":"symbol","modules":[{"name":"MapboxCommon"}],"roleHeading":"Function","title":"MBXAccuracyAuthorizationToString(_:)","externalID":"c:@F@MBXAccuracyAuthorizationToString"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon"]]},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBXAccuracyAuthorizationToString"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"accuracy_authorization","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@MBXAccuracyAuthorization","text":"AccuracyAuthorization","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXAccuracyAuthorizationToString(_:)":{"type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBXAccuracyAuthorizationToString"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@MBXAccuracyAuthorization","kind":"typeIdentifier","text":"AccuracyAuthorization"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"title":"MBXAccuracyAuthorizationToString(_:)","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXAccuracyAuthorizationToString(_:)","url":"\/documentation\/mapboxcommon\/mbxaccuracyauthorizationtostring(_:)","navigatorTitle":[{"text":"MBXAccuracyAuthorizationToString","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/AccuracyAuthorization":{"url":"\/documentation\/mapboxcommon\/accuracyauthorization","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization","kind":"symbol","type":"topic","navigatorTitle":[{"text":"AccuracyAuthorization","kind":"identifier"}],"title":"AccuracyAuthorization","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AccuracyAuthorization","kind":"identifier"}],"abstract":[{"text":"Accuracy authorization granted by user to the app.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","url":"\/documentation\/mapboxcommon","kind":"symbol","abstract":[],"title":"MapboxCommon","role":"collection","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","role":"collection","abstract":[],"type":"topic","kind":"article"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Function"},{"op":"replace","path":"\/metadata\/title","value":"MBXAccuracyAuthorizationToString"},{"op":"replace","path":"\/metadata\/symbolKind","value":"func"},{"value":[{"text":"MBXAccuracyAuthorizationToString","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"text":"MBXAccuracyAuthorizationToString","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@MBXAccuracyAuthorization","text":"MBXAccuracyAuthorization","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"accuracy_authorization","kind":"internalParam"},{"text":");","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MBXAccuracyAuthorizationToString(_:)\/title","value":"MBXAccuracyAuthorizationToString"},{"op":"replace","value":[{"text":"MBXAccuracyAuthorizationToString","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MBXAccuracyAuthorizationToString(_:)\/fragments"},{"value":"MBXAccuracyAuthorization","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization\/title"},{"value":[{"kind":"identifier","text":"MBXAccuracyAuthorization"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization\/navigatorTitle","value":[{"kind":"identifier","text":"MBXAccuracyAuthorization"}]}]}]}