{"metadata":{"role":"symbol","roleHeading":"Function","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBXTileDataDomainToString"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBXTileDataDomain","text":"TileDataDomain"},{"kind":"text","text":") -> "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"modules":[{"name":"MapboxCommon"}],"externalID":"c:@F@MBXTileDataDomainToString","symbolKind":"func","title":"MBXTileDataDomainToString(_:)","navigatorTitle":[{"text":"MBXTileDataDomainToString","kind":"identifier"}]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXTileDataDomainToString(_:)"},"variants":[{"paths":["\/documentation\/mapboxcommon\/mbxtiledatadomaintostring(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxcommon\/mbxtiledatadomaintostring(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"MBXTileDataDomainToString","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"tile_data_domain","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"TileDataDomain","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileDataDomain","preciseIdentifier":"c:@E@MBXTileDataDomain"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileDataDomain":{"role":"symbol","kind":"symbol","url":"\/documentation\/mapboxcommon\/tiledatadomain","navigatorTitle":[{"text":"TileDataDomain","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileDataDomain","title":"TileDataDomain","abstract":[{"type":"text","text":"Describes the tiles data domain."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"TileDataDomain","kind":"identifier"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","kind":"symbol","title":"MapboxCommon","type":"topic","url":"\/documentation\/mapboxcommon","role":"collection","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","role":"collection","kind":"article","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXTileDataDomainToString(_:)":{"title":"MBXTileDataDomainToString(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXTileDataDomainToString(_:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBXTileDataDomainToString"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBXTileDataDomainToString","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@MBXTileDataDomain","text":"TileDataDomain","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"!"}],"type":"topic","role":"symbol","abstract":[],"url":"\/documentation\/mapboxcommon\/mbxtiledatadomaintostring(_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Function"},{"op":"replace","value":"MBXTileDataDomainToString","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"func"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MBXTileDataDomainToString"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"MBXTileDataDomainToString","kind":"identifier"},{"kind":"text","text":"("},{"text":"MBXTileDataDomain","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileDataDomain","preciseIdentifier":"c:@E@MBXTileDataDomain"},{"text":" ","kind":"text"},{"text":"tile_data_domain","kind":"internalParam"},{"kind":"text","text":");"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileDataDomain\/title","value":"MBXTileDataDomain"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileDataDomain\/fragments","value":[{"kind":"identifier","text":"MBXTileDataDomain"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileDataDomain\/navigatorTitle","op":"replace","value":[{"text":"MBXTileDataDomain","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MBXTileDataDomainToString(_:)\/title","value":"MBXTileDataDomainToString","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MBXTileDataDomainToString(_:)\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXTileDataDomainToString"}]}]}]}