{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/networkrestriction"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/networkrestriction"]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon"]]},"sections":[],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NetworkRestriction","interfaceLanguage":"swift"},"abstract":[{"text":"Classify network types based on cost.","type":"text"}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NetworkRestriction\/disallowAll","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NetworkRestriction\/disallowExpensive","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NetworkRestriction\/none"],"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases"},{"title":"Initializers","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NetworkRestriction\/init(rawValue:)"],"anchor":"Initializers"},{"title":"Default Implementations","anchor":"Default-Implementations","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NetworkRestriction\/Equatable-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NetworkRestriction\/RawRepresentable-Implementations"],"generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"NetworkRestriction","kind":"identifier"}]}]}],"metadata":{"roleHeading":"Enumeration","modules":[{"name":"MapboxCommon"}],"role":"symbol","navigatorTitle":[{"text":"NetworkRestriction","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NetworkRestriction"}],"symbolKind":"enum","title":"NetworkRestriction","externalID":"c:@E@MBXNetworkRestriction"},"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/s15BitwiseCopyableP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH","doc:\/\/com.mapbox.MapboxMaps\/SY","doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"],"kind":"relationships","type":"conformsTo"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/NetworkRestriction/RawRepresentable-Implementations":{"role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NetworkRestriction\/RawRepresentable-Implementations","type":"topic","abstract":[],"title":"RawRepresentable Implementations","kind":"article","url":"\/documentation\/mapboxcommon\/networkrestriction\/rawrepresentable-implementations"},"doc://com.mapbox.MapboxMaps/s15BitwiseCopyableP":{"title":"Swift.BitwiseCopyable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s15BitwiseCopyableP","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/NetworkRestriction/none":{"navigatorTitle":[{"text":"MBXNetworkRestrictionNone","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NetworkRestriction\/none","abstract":[{"text":"Allow access to all network types.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxcommon\/networkrestriction\/none","kind":"symbol","role":"symbol","title":"NetworkRestriction.none"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/NetworkRestriction/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","type":"topic","abstract":[],"url":"\/documentation\/mapboxcommon\/networkrestriction\/equatable-implementations","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NetworkRestriction\/Equatable-Implementations"},"doc://com.mapbox.MapboxMaps/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s8SendableP","title":"Swift.Sendable"},"doc://com.mapbox.MapboxMaps/SH":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","title":"Swift.Hashable"},"doc://com.mapbox.MapboxMaps/SY":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SY","title":"Swift.RawRepresentable"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","type":"topic","kind":"article","abstract":[],"role":"collection","title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"role":"collection","url":"\/documentation\/mapboxcommon","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","abstract":[],"title":"MapboxCommon","kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/NetworkRestriction/init(rawValue:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NetworkRestriction\/init(rawValue:)","title":"init(rawValue:)","abstract":[],"url":"\/documentation\/mapboxcommon\/networkrestriction\/init(rawvalue:)","type":"topic","kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/NetworkRestriction":{"abstract":[{"type":"text","text":"Classify network types based on cost."}],"title":"NetworkRestriction","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NetworkRestriction","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetworkRestriction"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NetworkRestriction"}],"url":"\/documentation\/mapboxcommon\/networkrestriction"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/NetworkRestriction/disallowAll":{"navigatorTitle":[{"text":"MBXNetworkRestrictionDisallowAll","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NetworkRestriction\/disallowAll","abstract":[{"type":"text","text":"Forbid access to all network types."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"disallowAll"}],"type":"topic","url":"\/documentation\/mapboxcommon\/networkrestriction\/disallowall","kind":"symbol","role":"symbol","title":"NetworkRestriction.disallowAll"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/NetworkRestriction/disallowExpensive":{"title":"NetworkRestriction.disallowExpensive","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"disallowExpensive","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NetworkRestriction\/disallowExpensive","url":"\/documentation\/mapboxcommon\/networkrestriction\/disallowexpensive","abstract":[{"text":"Forbid network access to expensive networks, such as cellular.","type":"text"}],"navigatorTitle":[{"text":"MBXNetworkRestrictionDisallowExpensive","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"MBXNetworkRestriction"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MBXNetworkRestriction","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MBXNetworkRestriction"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"anchor":"Enumeration-Cases","generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NetworkRestriction\/disallowAll","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NetworkRestriction\/disallowExpensive","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NetworkRestriction\/none"]}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MBXNetworkRestriction","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1NetworkRestriction~1none\/title","value":"MBXNetworkRestrictionNone"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1NetworkRestriction~1none\/fragments","value":[{"text":"MBXNetworkRestrictionNone","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1NetworkRestriction\/title","op":"replace","value":"MBXNetworkRestriction"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1NetworkRestriction\/fragments","value":[{"text":"MBXNetworkRestriction","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1NetworkRestriction\/navigatorTitle","op":"replace","value":[{"text":"MBXNetworkRestriction","kind":"identifier"}]},{"value":"MBXNetworkRestrictionDisallowAll","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1NetworkRestriction~1disallowAll\/title","op":"replace"},{"value":[{"text":"MBXNetworkRestrictionDisallowAll","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1NetworkRestriction~1disallowAll\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1NetworkRestriction~1disallowExpensive\/title","value":"MBXNetworkRestrictionDisallowExpensive"},{"op":"replace","value":[{"text":"MBXNetworkRestrictionDisallowExpensive","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1NetworkRestriction~1disallowExpensive\/fragments"}]}]}