{"metadata":{"modules":[{"name":"MapboxCommon"}],"externalID":"c:objc(cs)MBXExceptionHandler","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSExceptionHandler"}],"navigatorTitle":[{"kind":"identifier","text":"NSExceptionHandler"}],"roleHeading":"Class","title":"NSExceptionHandler","role":"symbol"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance"]]},"relationshipsSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH"]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NSExceptionHandler","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/nsexceptionhandler"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/nsexceptionhandler"]}],"kind":"symbol","topicSections":[{"title":"Type Methods","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NSExceptionHandler\/try(callback:)"],"generated":true,"anchor":"Type-Methods"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NSExceptionHandler"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"title":"MapboxMaps","kind":"symbol","role":"collection","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","role":"collection","url":"\/documentation\/overview","kind":"article","abstract":[],"type":"topic"},"doc://com.mapbox.MapboxMaps/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP"},"doc://com.mapbox.MapboxMaps/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH"},"doc://com.mapbox.MapboxMaps/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"},"doc://com.mapbox.MapboxMaps/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject"},"doc://com.mapbox.MapboxMaps/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ"},"doc://com.mapbox.MapboxMaps/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/NSExceptionHandler/try(callback:)":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NSExceptionHandler\/try(callback:)","type":"topic","title":"try(callback:)","url":"\/documentation\/mapboxcommon\/nsexceptionhandler\/try(callback:)","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"`try`"},{"text":"<","kind":"text"},{"kind":"genericParameter","text":"T"},{"text":">(","kind":"text"},{"text":"callback","kind":"externalParam"},{"kind":"text","text":": () "},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"T"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"kind":"typeIdentifier","text":"T"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXExceptionHandler/tryWithCallback:error:":{"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXExceptionHandler\/tryWithCallback:error:","fragments":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"tryWithCallback:error:"}],"title":"tryWithCallback:error:","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"tryWithCallback:error:"}],"url":"\/documentation\/mapboxcommon\/mbxexceptionhandler\/trywithcallback:error:","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Performance":{"role":"collectionGroup","abstract":[],"type":"topic","title":"Performance and investigations","url":"\/documentation\/mapboxmaps\/performance","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/NSExceptionHandler":{"abstract":[],"kind":"symbol","title":"NSExceptionHandler","url":"\/documentation\/mapboxcommon\/nsexceptionhandler","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"NSExceptionHandler","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NSExceptionHandler","type":"topic","navigatorTitle":[{"text":"NSExceptionHandler","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MBXExceptionHandler"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MBXExceptionHandler","kind":"identifier"}]},{"op":"replace","value":[{"text":"MBXExceptionHandler","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"anchor":"Type-Methods","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXExceptionHandler\/tryWithCallback:error:"],"generated":true,"title":"Type Methods"}],"op":"replace"},{"value":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"]}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"MBXExceptionHandler","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"MBXExceptionHandler","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1NSExceptionHandler\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1NSExceptionHandler\/fragments","value":[{"text":"MBXExceptionHandler","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1NSExceptionHandler\/navigatorTitle","value":[{"text":"MBXExceptionHandler","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}