{"variants":[{"paths":["\/documentation\/mapboxcommon\/tilesetdescriptor"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/tilesetdescriptor"]}],"abstract":[{"text":"A bundle that encapsulates tilesets creation for the tile store implementation.","type":"text"}],"sections":[],"metadata":{"symbolKind":"class","modules":[{"name":"MapboxCommon"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TilesetDescriptor","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TilesetDescriptor"}],"roleHeading":"Class","externalID":"c:objc(cs)MBXTilesetDescriptor","title":"TilesetDescriptor"},"relationshipsSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TilesetDescriptor","interfaceLanguage":"swift"},"kind":"symbol","seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStoreOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudget","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInMegabytes","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInTiles","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCoverOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegion","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileRegionError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgress","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TilesetDescriptorOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgressCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreUsageMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileRegionError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileDataDomain","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgress","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateResult","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgressCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingErrorType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClearCacheError"],"title":"TileStore","anchor":"TileStore"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TilesetDescriptor","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"type":"heading","anchor":"overview","text":"Overview","level":2},{"inlineContent":[{"text":"Tileset descriptors describe the type of data that should be part of the Offline Region, like the routing profile for Navigation and the Tilesets of the Map style.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://com.mapbox.MapboxMaps/SH":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","title":"Swift.Hashable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudgetType":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileCacheBudgetType"}],"type":"topic","kind":"symbol","title":"TileCacheBudgetType","url":"\/documentation\/mapboxmaps\/tilecachebudgettype","role":"symbol","navigatorTitle":[{"text":"TileCacheBudgetType","kind":"identifier"}],"abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStoreObserver":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreObserver","title":"TileStoreObserver","abstract":[],"type":"topic","url":"\/documentation\/mapboxmaps\/tilestoreobserver","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"TileStoreObserver","kind":"identifier"}],"navigatorTitle":[{"text":"TileStoreObserver","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadProgress":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgress","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TileRegionLoadProgress"}],"type":"topic","kind":"symbol","title":"TileRegionLoadProgress","url":"\/documentation\/mapboxcommon\/tileregionloadprogress","role":"symbol","navigatorTitle":[{"text":"TileRegionLoadProgress","kind":"identifier"}],"abstract":[{"text":"A tile region’s load progress includes counts","type":"text"},{"type":"text","text":" "},{"type":"text","text":"of the number of resources that have completed downloading"},{"type":"text","text":" "},{"type":"text","text":"and the total number of resources that are required."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadOptions":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions","abstract":[{"type":"text","text":"Describes the tile region load option values."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TileRegionLoadOptions"}],"type":"topic","url":"\/documentation\/mapboxcommon\/tileregionloadoptions","title":"TileRegionLoadOptions","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileRegionLoadOptions"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudgetInMegabytes":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInMegabytes","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TileCacheBudgetInMegabytes","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/tilecachebudgetinmegabytes","title":"TileCacheBudgetInMegabytes","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TileCacheBudgetInMegabytes"}],"abstract":[{"type":"text","text":"Tile cache budget in megabytes."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/CacheClearingErrorType":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingErrorType","title":"CacheClearingErrorType","abstract":[{"type":"text","text":"Describes the reason for a cache clearing failure."}],"type":"topic","url":"\/documentation\/mapboxcommon\/cacheclearingerrortype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CacheClearingErrorType"}],"navigatorTitle":[{"kind":"identifier","text":"CacheClearingErrorType"}]},"doc://com.mapbox.MapboxMaps/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","title":"Swift.Equatable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"type":"topic","role":"collection","url":"\/documentation\/mapboxmaps","title":"MapboxMaps","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateResult":{"kind":"symbol","role":"symbol","title":"TileRegionEstimateResult","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateResult","abstract":[{"type":"text","text":"The result of tile region estim"}],"type":"topic","url":"\/documentation\/mapboxcommon\/tileregionestimateresult","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileRegionEstimateResult"}],"navigatorTitle":[{"kind":"identifier","text":"TileRegionEstimateResult"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStoreUsageMode":{"type":"topic","url":"\/documentation\/mapboxmaps\/tilestoreusagemode","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TileStoreUsageMode"}],"role":"symbol","abstract":[{"type":"text","text":"Describes tile store usage modes."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreUsageMode","title":"TileStoreUsageMode","navigatorTitle":[{"text":"TileStoreUsageMode","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudget":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TileCacheBudget"}],"url":"\/documentation\/mapboxmaps\/tilecachebudget","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudget","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileCacheBudget"}],"abstract":[],"title":"TileCacheBudget","role":"symbol"},"doc://com.mapbox.MapboxMaps/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileRegionError":{"type":"topic","abstract":[{"text":"Describes the reason for a tile region download request failure.","type":"text"}],"title":"TileRegionError","kind":"symbol","url":"\/documentation\/mapboxmaps\/tileregionerror","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileRegionError"}],"navigatorTitle":[{"text":"TileRegionError","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileRegionError"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCoverOptions":{"abstract":[{"text":"Various options needed for tile cover.","type":"text"}],"url":"\/documentation\/mapboxmaps\/tilecoveroptions","kind":"symbol","tags":[{"type":"spi","text":"SPI"}],"role":"symbol","type":"topic","title":"TileCoverOptions","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"TileCoverOptions","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCoverOptions","navigatorTitle":[{"text":"TileCoverOptions","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateOptions":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateOptions","kind":"symbol","navigatorTitle":[{"text":"TileRegionEstimateOptions","kind":"identifier"}],"abstract":[{"type":"text","text":"Holds options for the tile region estimation operation."}],"title":"TileRegionEstimateOptions","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TileRegionEstimateOptions","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/mapboxcommon\/tileregionestimateoptions"},"doc://com.mapbox.MapboxMaps/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TilesetDescriptor":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TilesetDescriptor","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TilesetDescriptor"}],"type":"topic","kind":"symbol","url":"\/documentation\/mapboxcommon\/tilesetdescriptor","title":"TilesetDescriptor","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TilesetDescriptor"}],"abstract":[{"type":"text","text":"A bundle that encapsulates tilesets creation for the tile store implementation."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"type":"topic","role":"collectionGroup","kind":"article","title":"TileStore APIs","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","url":"\/documentation\/mapboxmaps\/tilestore-apis"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateProgressCallback":{"title":"TileRegionEstimateProgressCallback","navigatorTitle":[{"kind":"identifier","text":"TileRegionEstimateProgressCallback"}],"abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"TileRegionEstimateProgressCallback","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgressCallback","type":"topic","url":"\/documentation\/mapboxcommon\/tileregionestimateprogresscallback","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TilesetDescriptorOptions":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TilesetDescriptorOptions","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TilesetDescriptorOptions"}],"type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/tilesetdescriptoroptions","title":"TilesetDescriptorOptions","role":"symbol","navigatorTitle":[{"text":"TilesetDescriptorOptions","kind":"identifier"}],"abstract":[{"text":"Describes the tileset descriptor option values.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileDataDomain":{"role":"symbol","kind":"symbol","url":"\/documentation\/mapboxcommon\/tiledatadomain","navigatorTitle":[{"text":"TileDataDomain","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileDataDomain","title":"TileDataDomain","abstract":[{"type":"text","text":"Describes the tiles data domain."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"TileDataDomain","kind":"identifier"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject","title":"NSObject"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadProgressCallback":{"abstract":[{"text":"Callback Invoked to report the progess of the tile region loading operation.","type":"text"}],"url":"\/documentation\/mapboxcommon\/tileregionloadprogresscallback","kind":"symbol","role":"symbol","type":"topic","title":"TileRegionLoadProgressCallback","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileRegionLoadProgressCallback"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgressCallback","navigatorTitle":[{"text":"TileRegionLoadProgressCallback","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateProgress":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgress","title":"TileRegionEstimateProgress","abstract":[{"text":"A tile region’s estimate progress includes counts of the number of resources that have","type":"text"},{"type":"text","text":" "},{"type":"text","text":"been estimated and the total number of resources as well as a partial result with the"},{"type":"text","text":" "},{"text":"current estimate, calculated using the data available at the moment.","type":"text"}],"type":"topic","url":"\/documentation\/mapboxcommon\/tileregionestimateprogress","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileRegionEstimateProgress"}],"navigatorTitle":[{"kind":"identifier","text":"TileRegionEstimateProgress"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileStore":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TileStore","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/mapboxcommon\/tilestore","title":"TileStore","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TileStore"}],"abstract":[{"type":"text","text":"TileStore manages downloads and storage for requests to tile-related API endpoints, enforcing a disk usage"},{"text":" ","type":"text"},{"type":"text","text":"quota: tiles available on disk may be deleted to make room for a new download. This interface can be used by an"},{"type":"text","text":" "},{"text":"app developer to set the disk quota. The rest of TileStore API is intended for native SDK consumption only.","type":"text"}]},"doc://com.mapbox.MapboxMaps/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileOptions":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileOptions","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TileOptions","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/tileoptions","title":"TileOptions","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TileOptions"}],"abstract":[{"type":"text","text":"Options for custom geometry tiles."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileStoreOptions":{"abstract":[{"type":"text","text":"These constants can be used as keys for TileStore::setOption to configure further aspects of a TileStore instance."}],"url":"\/documentation\/mapboxcommon\/tilestoreoptions","kind":"symbol","role":"symbol","type":"topic","title":"TileStoreOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileStoreOptions"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStoreOptions","navigatorTitle":[{"text":"TileStoreOptions","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudgetInTiles":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInTiles","title":"TileCacheBudgetInTiles","abstract":[{"type":"text","text":"Tile cache budget in tiles."}],"type":"topic","url":"\/documentation\/mapboxmaps\/tilecachebudgetintiles","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TileCacheBudgetInTiles"}],"navigatorTitle":[{"kind":"identifier","text":"TileCacheBudgetInTiles"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/CacheClearingError":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingError","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CacheClearingError"}],"type":"topic","kind":"symbol","title":"CacheClearingError","url":"\/documentation\/mapboxcommon\/cacheclearingerror","role":"symbol","navigatorTitle":[{"text":"CacheClearingError","kind":"identifier"}],"abstract":[{"type":"text","text":"Describes a cache clearing error."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegion":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegion","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileRegion"}],"type":"topic","kind":"symbol","url":"\/documentation\/mapboxcommon\/tileregion","title":"TileRegion","role":"symbol","navigatorTitle":[{"text":"TileRegion","kind":"identifier"}],"abstract":[{"type":"text","text":"TileRegion represents an identifiable geographic tile region with metadata"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","role":"collection","kind":"article","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ClearCacheError":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClearCacheError","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ClearCacheError"}],"abstract":[{"type":"text","text":"Describes the reason for a cache clearing failure."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ClearCacheError","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/clearcacheerror","kind":"symbol","title":"ClearCacheError"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CanonicalTileID":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CanonicalTileID","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID","title":"CanonicalTileID","abstract":[{"type":"text","text":"Represents a tile coordinate."}],"url":"\/documentation\/mapboxmaps\/canonicaltileid","navigatorTitle":[{"kind":"identifier","text":"CanonicalTileID"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","value":"MBXTilesetDescriptor","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MBXTilesetDescriptor","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"MBXTilesetDescriptor","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"]}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"generated":true,"title":"TileStore","anchor":"TileStore","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStoreOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudget","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInMegabytes","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInTiles","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegion","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgress","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TilesetDescriptorOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgressCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreUsageMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileDataDomain","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgress","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateResult","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgressCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingErrorType"]}]},{"value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"MBXTilesetDescriptor","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetType\/title","value":"MBMTileCacheBudgetType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetType\/fragments","value":[{"kind":"identifier","text":"MBMTileCacheBudgetType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetType\/navigatorTitle","value":[{"kind":"identifier","text":"MBMTileCacheBudgetType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgress\/title","value":"MBXTileRegionLoadProgress"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgress\/fragments","value":[{"kind":"identifier","text":"MBXTileRegionLoadProgress"}]},{"op":"replace","value":[{"kind":"identifier","text":"MBXTileRegionLoadProgress"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgress\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/title","value":"MBXTileRegionLoadOptions","op":"replace"},{"op":"replace","value":[{"text":"MBXTileRegionLoadOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/navigatorTitle","value":[{"kind":"identifier","text":"MBXTileRegionLoadOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInMegabytes\/title","value":"MBMTileCacheBudgetInMegabytes"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInMegabytes\/fragments","value":[{"text":"MBMTileCacheBudgetInMegabytes","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MBMTileCacheBudgetInMegabytes"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInMegabytes\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingErrorType\/title","value":"MBXCacheClearingErrorType","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingErrorType\/fragments","value":[{"text":"MBXCacheClearingErrorType","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingErrorType\/navigatorTitle","value":[{"kind":"identifier","text":"MBXCacheClearingErrorType"}]},{"value":"MBXTileRegionEstimateResult","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateResult\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateResult\/fragments","op":"replace","value":[{"text":"MBXTileRegionEstimateResult","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateResult\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBXTileRegionEstimateResult"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileStoreUsageMode\/title","value":"MBMTileStoreUsageMode","op":"replace"},{"op":"replace","value":[{"text":"MBMTileStoreUsageMode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileStoreUsageMode\/fragments"},{"op":"replace","value":[{"text":"MBMTileStoreUsageMode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileStoreUsageMode\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudget\/title","op":"replace","value":"MBMTileCacheBudget"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudget\/fragments","op":"replace","value":[{"text":"MBMTileCacheBudget","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudget\/navigatorTitle","op":"replace","value":[{"text":"MBMTileCacheBudget","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateOptions\/title","op":"replace","value":"MBXTileRegionEstimateOptions"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateOptions\/fragments","op":"replace","value":[{"text":"MBXTileRegionEstimateOptions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateOptions\/navigatorTitle","value":[{"kind":"identifier","text":"MBXTileRegionEstimateOptions"}]},{"value":"MBXTilesetDescriptor","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TilesetDescriptor\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TilesetDescriptor\/fragments","value":[{"text":"MBXTilesetDescriptor","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TilesetDescriptor\/navigatorTitle","value":[{"text":"MBXTilesetDescriptor","kind":"identifier"}]},{"op":"replace","value":"MBXTileRegionEstimateProgressCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgressCallback\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgressCallback\/fragments","value":[{"text":"MBXTileRegionEstimateProgressCallback","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgressCallback\/navigatorTitle","value":[{"kind":"identifier","text":"MBXTileRegionEstimateProgressCallback"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions\/title","value":"MBMTilesetDescriptorOptions","op":"replace"},{"value":[{"kind":"identifier","text":"MBMTilesetDescriptorOptions"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions\/navigatorTitle","value":[{"text":"MBMTilesetDescriptorOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileDataDomain\/title","op":"replace","value":"MBXTileDataDomain"},{"op":"replace","value":[{"text":"MBXTileDataDomain","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileDataDomain\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileDataDomain\/navigatorTitle","value":[{"text":"MBXTileDataDomain","kind":"identifier"}]},{"value":"MBXTileRegionLoadProgressCallback","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgressCallback\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgressCallback\/fragments","value":[{"kind":"identifier","text":"MBXTileRegionLoadProgressCallback"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgressCallback\/navigatorTitle","value":[{"kind":"identifier","text":"MBXTileRegionLoadProgressCallback"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgress\/title","value":"MBXTileRegionEstimateProgress"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgress\/fragments","value":[{"kind":"identifier","text":"MBXTileRegionEstimateProgress"}]},{"value":[{"text":"MBXTileRegionEstimateProgress","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgress\/navigatorTitle"},{"op":"replace","value":"MBXTileStore","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/title"},{"value":[{"text":"MBXTileStore","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/navigatorTitle","value":[{"text":"MBXTileStore","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileOptions\/title","op":"replace","value":"MBMTileOptions"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileOptions\/fragments","op":"replace","value":[{"text":"MBMTileOptions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileOptions\/navigatorTitle","value":[{"text":"MBMTileOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStoreOptions\/title","op":"replace","value":"MBXTileStoreOptions"},{"value":[{"kind":"identifier","text":"MBXTileStoreOptions"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStoreOptions\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStoreOptions\/navigatorTitle","value":[{"text":"MBXTileStoreOptions","kind":"identifier"}]},{"value":"MBMTileCacheBudgetInTiles","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInTiles\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInTiles\/fragments","value":[{"text":"MBMTileCacheBudgetInTiles","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInTiles\/navigatorTitle","value":[{"kind":"identifier","text":"MBMTileCacheBudgetInTiles"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingError\/title","op":"replace","value":"MBXCacheClearingError"},{"op":"replace","value":[{"kind":"identifier","text":"MBXCacheClearingError"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingError\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingError\/navigatorTitle","value":[{"text":"MBXCacheClearingError","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"MBXTileRegion","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegion\/title"},{"value":[{"kind":"identifier","text":"MBXTileRegion"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegion\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegion\/navigatorTitle","op":"replace","value":[{"text":"MBXTileRegion","kind":"identifier"}]},{"value":"MBMCanonicalTileID","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/fragments","op":"replace","value":[{"text":"MBMCanonicalTileID","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MBMCanonicalTileID"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/navigatorTitle"}]}]}