{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tile","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType\/tile","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@E@MBMRequestResourceType@MBMRequestResourceTypeTile","title":"RequestResourceType.tile","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tile"}],"navigatorTitle":[{"kind":"identifier","text":"MBMRequestResourceTypeTile"}],"role":"symbol","symbolKind":"case","modules":[{"name":"MapboxMaps"}],"roleHeading":"Case"},"sections":[],"abstract":[{"type":"text","text":"The resource type is a tile, for example, a vector or raster tile."}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType"]]},"variants":[{"paths":["\/documentation\/mapboxmaps\/requestresourcetype\/tile"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/requestresourcetype\/tile"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"url":"\/documentation\/mapboxmaps","title":"MapboxMaps","type":"topic","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestResourceType":{"title":"RequestResourceType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RequestResourceType"}],"abstract":[{"text":"The enumeration defines the type of resource requested by the ","type":"text"},{"code":"map","type":"codeVoice"},{"text":".","type":"text"}],"url":"\/documentation\/mapboxmaps\/requestresourcetype","navigatorTitle":[{"kind":"identifier","text":"RequestResourceType"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"type":"topic","role":"collectionGroup","kind":"article","url":"\/documentation\/mapboxmaps\/events","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","title":"Map events","abstract":[{"type":"text","text":"The simplified diagram of the events emitted by the map is displayed below."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestResourceType/tile":{"title":"RequestResourceType.tile","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"tile","kind":"identifier"}],"navigatorTitle":[{"text":"MBMRequestResourceTypeTile","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/requestresourcetype\/tile","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType\/tile","abstract":[{"text":"The resource type is a tile, for example, a vector or raster tile.","type":"text"}],"type":"topic","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"MBMRequestResourceTypeTile","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"kind":"identifier","text":"MBMRequestResourceTypeTile"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"MBMRequestResourceTypeTile","kind":"identifier"}],"languages":["occ"]}]}},{"value":"MBMRequestResourceType","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestResourceType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestResourceType\/fragments","value":[{"text":"MBMRequestResourceType","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MBMRequestResourceType"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestResourceType\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestResourceType~1tile\/title","value":"MBMRequestResourceTypeTile"},{"op":"replace","value":[{"text":"MBMRequestResourceTypeTile","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestResourceType~1tile\/fragments"}]}]}