{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileDataDomain"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileDataDomain\/Equatable-Implementations"},"metadata":{"title":"Equatable Implementations","modules":[{"name":"MapboxCommon"},{"name":"MapboxMaps"}],"role":"collectionGroup","roleHeading":"API Collection"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"kind":"article","topicSections":[{"title":"Operators","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileDataDomain\/!=(_:_:)"],"anchor":"Operators","generated":true}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileDataDomain/!=(_:_:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[],"title":"!=(_:_:)","kind":"symbol","type":"topic","url":"\/documentation\/mapboxcommon\/tiledatadomain\/!=(_:_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileDataDomain\/!=(_:_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileDataDomain":{"navigatorTitle":[{"text":"TileDataDomain","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileDataDomain","type":"topic","kind":"symbol","url":"\/documentation\/mapboxcommon\/tiledatadomain","abstract":[{"text":"Describes the tiles data domain.","type":"text"}],"title":"TileDataDomain","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TileDataDomain","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","kind":"symbol","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","role":"collection","title":"MapboxMaps Documentation","abstract":[],"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"kind":"article","type":"topic","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","abstract":[],"url":"\/documentation\/mapboxmaps\/tilestore-apis","title":"TileStore APIs"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileDataDomain\/title","op":"replace","value":"MBXTileDataDomain"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileDataDomain\/fragments","value":[{"kind":"identifier","text":"MBXTileDataDomain"}]},{"value":[{"text":"MBXTileDataDomain","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileDataDomain\/navigatorTitle","op":"replace"}]}]}