{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon"],["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TurfAPI","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GeometryType_GeometryCollection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@EA@MBXGeometryType","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType","text":"GeometryType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GeometryType_GeometryCollection","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GeometryType","kind":"typeIdentifier","preciseIdentifier":"c:@EA@MBXGeometryType"}],"roleHeading":"Global Variable","role":"symbol","navigatorTitle":[{"text":"MBXGeometryType_GeometryCollection","kind":"identifier"}],"modules":[{"name":"MapboxCommon"}],"symbolKind":"var","title":"GeometryType_GeometryCollection","externalID":"c:@EA@MBXGeometryType@MBXGeometryType_GeometryCollection"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/geometrytype_geometrycollection"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/geometrytype_geometrycollection"]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType_GeometryCollection","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TurfAPI":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TurfAPI","abstract":[{"type":"text","text":"Describes "},{"code":"turf-swift","type":"codeVoice"},{"type":"text","text":" dependency objects"}],"kind":"article","role":"collectionGroup","title":"Turf","type":"topic","url":"\/documentation\/mapboxmaps\/turfapi"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"role":"collection","abstract":[],"kind":"symbol","title":"MapboxCommon","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","type":"topic","url":"\/documentation\/mapboxcommon"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/GeometryType":{"type":"topic","title":"GeometryType","url":"\/documentation\/mapboxcommon\/geometrytype","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GeometryType","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType","role":"symbol","navigatorTitle":[{"text":"GeometryType","kind":"identifier"}],"abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/GeometryType_GeometryCollection":{"role":"symbol","navigatorTitle":[{"text":"MBXGeometryType_GeometryCollection","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GeometryType_GeometryCollection","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GeometryType","preciseIdentifier":"c:@EA@MBXGeometryType","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType_GeometryCollection","url":"\/documentation\/mapboxcommon\/geometrytype_geometrycollection","title":"GeometryType_GeometryCollection","type":"topic","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","url":"\/documentation\/overview","kind":"article","abstract":[],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","url":"\/documentation\/mapboxmaps","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","role":"collection","title":"MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MBXGeometryType_GeometryCollection"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MBXGeometryType_GeometryCollection","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"MBXGeometryType_GeometryCollection","kind":"identifier"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType\/title","value":"MBXGeometryType"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType\/fragments","value":[{"text":"","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType\/navigatorTitle","value":[{"text":"MBXGeometryType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType_GeometryCollection\/title","value":"MBXGeometryType_GeometryCollection"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType_GeometryCollection\/fragments","value":[{"kind":"identifier","text":"MBXGeometryType_GeometryCollection"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}