{"topicSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceError\/==(_:_:)"],"generated":true,"title":"Operators","anchor":"Operators"},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceError\/init(description:)"],"generated":true,"title":"Initializers","anchor":"Initializers"},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceError\/Equatable-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceError\/Error-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceError\/LocalizedError-Implementations"],"generated":true,"title":"Default Implementations","anchor":"Default-Implementations"}],"kind":"symbol","abstract":[{"type":"text","text":"Structure for keeping an information about errors that can happen when using Settings service"}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsService","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceFactory","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceStorageType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SdkInformation"],"generated":true,"title":"Common Settings","anchor":"Common-Settings"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SettingsServiceError","kind":"identifier"}],"role":"symbol","title":"SettingsServiceError","roleHeading":"Structure","modules":[{"name":"MapboxCommon"}],"externalID":"s:12MapboxCommon20SettingsServiceErrorV","symbolKind":"struct","navigatorTitle":[{"text":"SettingsServiceError","kind":"identifier"}]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceError"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Settings-and-Constants"]]},"relationshipsSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/10Foundation14LocalizedErrorP","doc:\/\/com.mapbox.MapboxMaps\/s8CopyableP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/s5ErrorP","doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SettingsServiceError","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/mapboxcommon\/settingsserviceerror"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsServiceError/Equatable-Implementations":{"title":"Equatable Implementations","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceError\/Equatable-Implementations","role":"collectionGroup","url":"\/documentation\/mapboxcommon\/settingsserviceerror\/equatable-implementations","type":"topic","kind":"article","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsServiceError/LocalizedError-Implementations":{"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceError\/LocalizedError-Implementations","type":"topic","kind":"article","role":"collectionGroup","title":"LocalizedError Implementations","url":"\/documentation\/mapboxcommon\/settingsserviceerror\/localizederror-implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SdkInformation":{"abstract":[{"text":"Provides information about a given Mapbox SDK. This information is then used to populate the “User-Agent” HTTP header","type":"text"},{"text":" ","type":"text"},{"text":"of HTTP requests generated from within Mapbox SDKs. Mapbox SDKs include Maps, Navigation, Search, and others.","type":"text"}],"title":"SdkInformation","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SdkInformation"}],"url":"\/documentation\/mapboxcommon\/sdkinformation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SdkInformation"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SdkInformation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Settings-and-Constants":{"abstract":[],"url":"\/documentation\/mapboxmaps\/settings-and-constants","type":"topic","title":"Settings and Constants","role":"collectionGroup","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Settings-and-Constants"},"doc://com.mapbox.MapboxMaps/s8CopyableP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s8CopyableP","type":"unresolvable","title":"Swift.Copyable"},"doc://com.mapbox.MapboxMaps/s5ErrorP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s5ErrorP","title":"Swift.Error"},"doc://com.mapbox.MapboxMaps/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s8SendableP","title":"Swift.Sendable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsServiceError/init(description:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceError\/init(description:)","role":"symbol","url":"\/documentation\/mapboxcommon\/settingsserviceerror\/init(description:)","kind":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"description","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"title":"init(description:)","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","url":"\/documentation\/mapboxmaps","title":"MapboxMaps","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsServiceError/==(_:_:)":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"==","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"SettingsServiceError","preciseIdentifier":"s:12MapboxCommon20SettingsServiceErrorV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"SettingsServiceError","preciseIdentifier":"s:12MapboxCommon20SettingsServiceErrorV","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"title":"==(_:_:)","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceError\/==(_:_:)","role":"symbol","type":"topic","url":"\/documentation\/mapboxcommon\/settingsserviceerror\/==(_:_:)","abstract":[]},"doc://com.mapbox.MapboxMaps/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsServiceFactory":{"url":"\/documentation\/mapboxcommon\/settingsservicefactory","navigatorTitle":[{"text":"SettingsServiceFactory","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceFactory","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SettingsServiceFactory","kind":"identifier"}],"role":"symbol","title":"SettingsServiceFactory","abstract":[{"text":"Factory that allows to create settings service instance.","type":"text"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","role":"collection","type":"topic","abstract":[],"title":"MapboxMaps Documentation","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsServiceError/Error-Implementations":{"kind":"article","url":"\/documentation\/mapboxcommon\/settingsserviceerror\/error-implementations","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceError\/Error-Implementations","type":"topic","title":"Error Implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsServiceStorageType":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceStorageType","url":"\/documentation\/mapboxcommon\/settingsservicestoragetype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SettingsServiceStorageType","kind":"identifier"}],"navigatorTitle":[{"text":"SettingsServiceStorageType","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Enum that contains possible storage types that can be used for settings service.","type":"text"}],"type":"topic","title":"SettingsServiceStorageType"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsServiceError":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SettingsServiceError","kind":"identifier"}],"abstract":[{"type":"text","text":"Structure for keeping an information about errors that can happen when using Settings service"}],"url":"\/documentation\/mapboxcommon\/settingsserviceerror","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SettingsServiceError","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceError","type":"topic","title":"SettingsServiceError"},"doc://com.mapbox.MapboxMaps/10Foundation14LocalizedErrorP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/10Foundation14LocalizedErrorP","title":"Foundation.LocalizedError"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsService":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SettingsService"}],"abstract":[{"type":"text","text":"Platform independent settings service. Settings service is a key\/value storage (persistent or non"},{"type":"text","text":" "},{"type":"text","text":"persistent), that also allows to register observers to get notifications when values are updated."}],"url":"\/documentation\/mapboxcommon\/settingsservice","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SettingsService"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsService","type":"topic","title":"SettingsService"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SdkInformation\/title","value":"MBXSdkInformation"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SdkInformation\/fragments","value":[{"kind":"identifier","text":"MBXSdkInformation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SdkInformation\/navigatorTitle","value":[{"text":"MBXSdkInformation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceFactory\/title","value":"MBXSettingsServiceFactory"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceFactory\/fragments","value":[{"text":"MBXSettingsServiceFactory","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceFactory\/navigatorTitle","value":[{"text":"MBXSettingsServiceFactory","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceStorageType\/title","value":"MBXSettingsServiceStorageType"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceStorageType\/fragments","value":[{"text":"MBXSettingsServiceStorageType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceStorageType\/navigatorTitle","value":[{"text":"MBXSettingsServiceStorageType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsService\/title","value":"MBXSettingsService"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsService\/fragments","value":[{"kind":"identifier","text":"MBXSettingsService"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsService\/navigatorTitle","value":[{"kind":"identifier","text":"MBXSettingsService"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}