{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ElevationData"},"variants":[{"paths":["\/documentation\/mapboxmaps\/elevationdata"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/elevationdata"]}],"abstract":[{"text":"Interface that provides access to elevation data.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers"]]},"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerInfo","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/BackgroundLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CircleLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillExtrusionLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationIndicatorLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterParticleLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SkyLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderConfiguration","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerHost","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Slot","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SlotLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerAtPosition","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClipLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClipLayerTypes"],"title":"Layers","anchor":"Layers"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"topicSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ElevationData\/getElevationFor(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ElevationData\/getTerrainExaggeration()"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"metadata":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ElevationData"}],"title":"ElevationData","roleHeading":"Protocol","symbolKind":"protocol","modules":[{"name":"MapboxMaps"}],"externalID":"c:objc(pl)MBMElevationData","navigatorTitle":[{"kind":"identifier","text":"ElevationData"}],"role":"symbol"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ElevationData"}]}],"kind":"declarations"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerRenderParameters":{"navigatorTitle":[{"text":"CustomLayerRenderParameters","kind":"identifier"}],"role":"symbol","title":"CustomLayerRenderParameters","abstract":[{"text":"Parameters that define the current camera position for a ","type":"text"},{"type":"codeVoice","code":"CustomLayerHost::render()"},{"type":"text","text":" function."}],"url":"\/documentation\/mapboxmaps\/customlayerrenderparameters","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CustomLayerRenderParameters"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"kind":"article","url":"\/documentation\/overview","role":"collection","title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ClipLayerTypes":{"abstract":[{"text":"Layer types that will also be removed if fallen below this clip layer.","type":"text"}],"title":"ClipLayerTypes","url":"\/documentation\/mapboxmaps\/cliplayertypes","navigatorTitle":[{"text":"ClipLayerTypes","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClipLayerTypes","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ClipLayerTypes","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Atmosphere":{"url":"\/documentation\/mapboxmaps\/atmosphere","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Atmosphere","kind":"symbol","navigatorTitle":[{"text":"Atmosphere","kind":"identifier"}],"role":"symbol","type":"topic","title":"Atmosphere","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Atmosphere"}],"abstract":[{"text":"A style’s fog property is a global effect that improves depth perception by fading out distant objects.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerInfo":{"type":"topic","navigatorTitle":[{"text":"LayerInfo","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerInfo","url":"\/documentation\/mapboxmaps\/layerinfo","abstract":[{"type":"text","text":"Information about a layer"}],"title":"LayerInfo","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LayerInfo","kind":"identifier"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ElevationData/getElevationFor(_:)":{"kind":"symbol","title":"getElevationFor(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"getElevationFor"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","kind":"typeIdentifier","text":"CLLocationCoordinate2D"},{"kind":"text","text":") -> "},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"required":true,"abstract":[{"text":"Get elevation for given coordinate. Value is available only for the visible region on the screen, if terrain (DEM) tile is available.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"getElevationForCoordinate:","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/elevationdata\/getelevationfor(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ElevationData\/getElevationFor(_:)","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ClipLayer":{"type":"topic","title":"ClipLayer","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClipLayer","abstract":[{"type":"text","text":"Layer that removes 3D content from map."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ClipLayer"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/cliplayer","navigatorTitle":[{"kind":"identifier","text":"ClipLayer"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layers":{"kind":"article","url":"\/documentation\/mapboxmaps\/layers","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers","abstract":[],"role":"collectionGroup","title":"Layers","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FillExtrusionLayer":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillExtrusionLayer","kind":"symbol","title":"FillExtrusionLayer","role":"symbol","url":"\/documentation\/mapboxmaps\/fillextrusionlayer","abstract":[{"text":"An extruded (3D) polygon.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"FillExtrusionLayer","kind":"identifier"}],"navigatorTitle":[{"text":"FillExtrusionLayer","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerType":{"title":"LayerType","kind":"symbol","url":"\/documentation\/mapboxmaps\/layertype","role":"symbol","navigatorTitle":[{"text":"LayerType","kind":"identifier"}],"abstract":[{"text":"Struct of supported Layer rendering types","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LayerType"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelLayer":{"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ModelLayer"}],"url":"\/documentation\/mapboxmaps\/modellayer","abstract":[{"text":"A layer to render 3D Models.","type":"text"}],"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ModelLayer"}],"title":"ModelLayer","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer","tags":[{"type":"spi","text":"SPI"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeatmapLayer":{"abstract":[{"text":"A heatmap.","type":"text"}],"title":"HeatmapLayer","url":"\/documentation\/mapboxmaps\/heatmaplayer","navigatorTitle":[{"text":"HeatmapLayer","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HeatmapLayer","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerRenderConfiguration":{"abstract":[{"text":"Note! This is an experimental feature. It can be changed or removed in future versions.","type":"text"}],"title":"CustomLayerRenderConfiguration","url":"\/documentation\/mapboxmaps\/customlayerrenderconfiguration","navigatorTitle":[{"text":"CustomLayerRenderConfiguration","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomLayerRenderConfiguration","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerAtPosition":{"abstract":[],"title":"LayerAtPosition","url":"\/documentation\/mapboxmaps\/layeratposition","navigatorTitle":[{"text":"LayerAtPosition","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerAtPosition","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"LayerAtPosition","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterLayer":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterLayer","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RasterLayer","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/rasterlayer","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"RasterLayer"}],"title":"RasterLayer","abstract":[{"type":"text","text":"Raster map textures such as satellite imagery."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/BackgroundLayer":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BackgroundLayer"}],"abstract":[{"type":"text","text":"The background color or pattern of the map."}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/backgroundlayer","type":"topic","navigatorTitle":[{"text":"BackgroundLayer","kind":"identifier"}],"role":"symbol","title":"BackgroundLayer","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/BackgroundLayer"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayer":{"url":"\/documentation\/mapboxmaps\/customlayer","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CustomLayer"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayer","tags":[{"type":"spi","text":"SPI"}],"navigatorTitle":[{"text":"CustomLayer","kind":"identifier"}],"title":"CustomLayer","abstract":[{"text":"Layer with custom rendering implementation","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SkyLayer":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"A spherical dome around the map that is always rendered behind all other layers."},{"type":"text","text":" "},{"text":"Warning: As of v10.6.0, ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Atmosphere","isActive":true},{"type":"text","text":" is the preferred method for atmospheric styling. Sky layer is not supported by the globe projection, and will be phased out in future major release."}],"title":"SkyLayer","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"SkyLayer","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SkyLayer"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SkyLayer","url":"\/documentation\/mapboxmaps\/skylayer"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ElevationData/getTerrainExaggeration()":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ElevationData\/getTerrainExaggeration()","abstract":[{"text":"Current value of terrain exaggeration.","type":"text"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getTerrainExaggeration","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"kind":"symbol","role":"symbol","title":"getTerrainExaggeration()","navigatorTitle":[{"text":"getTerrainExaggeration","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/elevationdata\/getterrainexaggeration()","required":true},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer":{"abstract":[{"text":"Client-side hillshading visualization based on DEM data. Currently, the implementation only supports Mapbox Terrain RGB and Mapzen Terrarium tiles.","type":"text"}],"title":"HillshadeLayer","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"HillshadeLayer","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/hillshadelayer","navigatorTitle":[{"kind":"identifier","text":"HillshadeLayer"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FillLayer":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FillLayer"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillLayer","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"FillLayer","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"A filled polygon with an optional stroked border.","type":"text"}],"title":"FillLayer","url":"\/documentation\/mapboxmaps\/filllayer"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layer":{"title":"Layer","kind":"symbol","url":"\/documentation\/mapboxmaps\/layer","role":"symbol","navigatorTitle":[{"text":"Layer","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"Layer","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SlotLayer":{"url":"\/documentation\/mapboxmaps\/slotlayer","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SlotLayer","kind":"identifier"}],"kind":"symbol","title":"SlotLayer","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SlotLayer"}],"abstract":[{"text":"Marks the position of a slot.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SlotLayer"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ElevationData":{"url":"\/documentation\/mapboxmaps\/elevationdata","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ElevationData"}],"kind":"symbol","title":"ElevationData","role":"symbol","navigatorTitle":[{"text":"ElevationData","kind":"identifier"}],"abstract":[{"type":"text","text":"Interface that provides access to elevation data."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ElevationData"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LocationIndicatorLayer":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationIndicatorLayer","kind":"identifier"}],"abstract":[{"type":"text","text":"Location Indicator layer."}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/locationindicatorlayer","type":"topic","navigatorTitle":[{"text":"LocationIndicatorLayer","kind":"identifier"}],"role":"symbol","title":"LocationIndicatorLayer","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationIndicatorLayer"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SymbolLayer":{"navigatorTitle":[{"text":"SymbolLayer","kind":"identifier"}],"title":"SymbolLayer","url":"\/documentation\/mapboxmaps\/symbollayer","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"SymbolLayer","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolLayer","abstract":[{"text":"An icon or a text label.","type":"text"}],"role":"symbol","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CircleLayer":{"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CircleLayer","navigatorTitle":[{"text":"CircleLayer","kind":"identifier"}],"title":"CircleLayer","url":"\/documentation\/mapboxmaps\/circlelayer","abstract":[{"type":"text","text":"A filled circle."}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CircleLayer"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LineLayer":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineLayer","abstract":[{"type":"text","text":"A stroked line."}],"url":"\/documentation\/mapboxmaps\/linelayer","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"LineLayer","kind":"identifier"}],"role":"symbol","title":"LineLayer","kind":"symbol","navigatorTitle":[{"text":"LineLayer","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Slot":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Slot","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"A pre-specified location in the style where layer will be added to"},{"type":"text","text":" "},{"text":"(such as on top of existing land layers, but below all labels).","type":"text"}],"title":"Slot","url":"\/documentation\/mapboxmaps\/slot","navigatorTitle":[{"text":"Slot","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Slot"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","title":"MapboxMaps","type":"topic","url":"\/documentation\/mapboxmaps","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterParticleLayer":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterParticleLayer","type":"topic","abstract":[{"type":"text","text":"Particle animation driven by textures such as wind maps."}],"role":"symbol","url":"\/documentation\/mapboxmaps\/rasterparticlelayer","navigatorTitle":[{"text":"RasterParticleLayer","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"RasterParticleLayer","kind":"identifier"}],"tags":[{"text":"SPI","type":"spi"}],"title":"RasterParticleLayer"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerHost":{"navigatorTitle":[{"kind":"identifier","text":"CustomLayerHost"}],"type":"topic","title":"CustomLayerHost","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerHost","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CustomLayerHost"}],"url":"\/documentation\/mapboxmaps\/customlayerhost","kind":"symbol","abstract":[{"text":"Interface for hosting a custom map style layer.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","value":"MBMElevationData","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MBMElevationData","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MBMElevationData"}]},{"value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ElevationData\/getElevationFor(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ElevationData\/getTerrainExaggeration()"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"op":"replace","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Layers","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderConfiguration","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerHost"],"anchor":"Layers","generated":true}]},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MBMElevationData","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/title","value":"MBMCustomLayerRenderParameters","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/fragments","op":"replace","value":[{"text":"MBMCustomLayerRenderParameters","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/navigatorTitle","value":[{"text":"MBMCustomLayerRenderParameters","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ElevationData~1getElevationFor(_:)\/title","value":"getElevationForCoordinate:","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ElevationData~1getElevationFor(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"getElevationForCoordinate:","kind":"identifier"}]},{"value":"MBMCustomLayerRenderConfiguration","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderConfiguration\/fragments","value":[{"text":"MBMCustomLayerRenderConfiguration","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MBMCustomLayerRenderConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderConfiguration\/navigatorTitle"},{"value":"getTerrainExaggeration","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ElevationData~1getTerrainExaggeration()\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ElevationData~1getTerrainExaggeration()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"getTerrainExaggeration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ElevationData\/title","op":"replace","value":"MBMElevationData"},{"value":[{"text":"MBMElevationData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ElevationData\/fragments"},{"op":"replace","value":[{"text":"MBMElevationData","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ElevationData\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost\/title","value":"MBMCustomLayerHost"},{"value":[{"text":"MBMCustomLayerHost","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost\/navigatorTitle","value":[{"text":"MBMCustomLayerHost","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}