{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Settings-and-Constants"]]},"topicSections":[{"anchor":"Type-Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapConstants\/defaultTransitionDuration","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapConstants\/maxPitch","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapConstants\/maxZoom","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapConstants\/minPitch","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapConstants\/minZoom"],"title":"Type Properties","generated":true}],"sections":[],"metadata":{"roleHeading":"Class","modules":[{"name":"MapboxMaps"}],"navigatorTitle":[{"text":"MapConstants","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapConstants"}],"role":"symbol","externalID":"c:objc(cs)MBMMapConstants","title":"MapConstants","symbolKind":"class"},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapConstants","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Collection of useful constants."}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapConstants","kind":"identifier"}]}]}],"variants":[{"paths":["\/documentation\/mapboxmaps\/mapconstants"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/mapconstants"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.mapbox.MapboxMaps/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapConstants/minPitch":{"navigatorTitle":[{"kind":"identifier","text":"MinPitch"}],"url":"\/documentation\/mapboxmaps\/mapconstants\/minpitch","kind":"symbol","abstract":[{"type":"text","text":"The map view’s minimum pitch in degrees."}],"type":"topic","role":"symbol","title":"minPitch","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minPitch","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapConstants\/minPitch"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapConstants":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MapConstants","kind":"identifier"}],"title":"MapConstants","role":"symbol","abstract":[{"text":"Collection of useful constants.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapConstants","type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/mapconstants","navigatorTitle":[{"kind":"identifier","text":"MapConstants"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","title":"MapboxMaps","type":"topic","url":"\/documentation\/mapboxmaps","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}]},"doc://com.mapbox.MapboxMaps/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Settings-and-Constants":{"url":"\/documentation\/mapboxmaps\/settings-and-constants","kind":"article","title":"Settings and Constants","type":"topic","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Settings-and-Constants","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapConstants/defaultTransitionDuration":{"url":"\/documentation\/mapboxmaps\/mapconstants\/defaulttransitionduration","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapConstants\/defaultTransitionDuration","abstract":[{"text":"Default transition duration in milliseconds.","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultTransitionDuration"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s6UInt64V","text":"UInt64","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"DefaultTransitionDuration"}],"kind":"symbol","title":"defaultTransitionDuration","role":"symbol"},"doc://com.mapbox.MapboxMaps/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject"},"doc://com.mapbox.MapboxMaps/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"kind":"article","url":"\/documentation\/overview","role":"collection","title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic"},"doc://com.mapbox.MapboxMaps/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP"},"doc://com.mapbox.MapboxMaps/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapConstants/minZoom":{"url":"\/documentation\/mapboxmaps\/mapconstants\/minzoom","title":"minZoom","abstract":[{"type":"text","text":"The map view’s minimum zoom."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapConstants\/minZoom","navigatorTitle":[{"text":"MinZoom","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"minZoom"},{"kind":"text","text":": "},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapConstants/maxZoom":{"title":"maxZoom","role":"symbol","abstract":[{"type":"text","text":"The map view’s maximum zoom."}],"navigatorTitle":[{"text":"MaxZoom","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxZoom","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapConstants\/maxZoom","url":"\/documentation\/mapboxmaps\/mapconstants\/maxzoom"},"doc://com.mapbox.MapboxMaps/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapConstants/maxPitch":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maxPitch"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"type":"topic","abstract":[{"type":"text","text":"The map view’s maximum pitch in degrees."}],"kind":"symbol","role":"symbol","title":"maxPitch","navigatorTitle":[{"text":"MaxPitch","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapConstants\/maxPitch","url":"\/documentation\/mapboxmaps\/mapconstants\/maxpitch"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"MBMMapConstants","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MBMMapConstants","kind":"identifier"}]},{"value":[{"text":"MBMMapConstants","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Type-Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapConstants\/defaultTransitionDuration","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapConstants\/maxPitch","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapConstants\/maxZoom","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapConstants\/minPitch","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapConstants\/minZoom"],"title":"Type Properties","generated":true}]},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}],"op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBMMapConstants","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapConstants~1minPitch\/title","value":"MinPitch","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapConstants~1minPitch\/fragments","value":[{"text":"MinPitch","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapConstants\/title","value":"MBMMapConstants"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapConstants\/fragments","value":[{"kind":"identifier","text":"MBMMapConstants"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapConstants\/navigatorTitle","value":[{"kind":"identifier","text":"MBMMapConstants"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapConstants~1defaultTransitionDuration\/title","value":"DefaultTransitionDuration"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapConstants~1defaultTransitionDuration\/fragments","op":"replace","value":[{"kind":"identifier","text":"DefaultTransitionDuration"}]},{"op":"replace","value":"MinZoom","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapConstants~1minZoom\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapConstants~1minZoom\/fragments","value":[{"text":"MinZoom","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapConstants~1maxZoom\/title","value":"MaxZoom","op":"replace"},{"value":[{"kind":"identifier","text":"MaxZoom"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapConstants~1maxZoom\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapConstants~1maxPitch\/title","value":"MaxPitch","op":"replace"},{"value":[{"text":"MaxPitch","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapConstants~1maxPitch\/fragments","op":"replace"}]}]}