{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/tilefunctioncallback"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/tilefunctioncallback"]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileFunctionCallback","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Callback to do various operations for tile."},{"type":"text","text":" "},{"text":"For example, fetching a tile or cancelling a tile request.","type":"text"}],"seeAlsoSections":[{"anchor":"Sources","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Source","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceInfo","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSourceData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterArraySource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/VectorSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PromoteId","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Scheme","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Encoding","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatusChangedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatus","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetSize"],"generated":true,"title":"Sources"}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources"]]},"sections":[],"metadata":{"modules":[{"name":"MapboxMaps"}],"title":"TileFunctionCallback","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileFunctionCallback","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"TileFunctionCallback","kind":"identifier"}],"roleHeading":"Type Alias","externalID":"c:MBMTileFunctionCallback.h@T@MBMTileFunctionCallback","symbolKind":"typealias"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileFunctionCallback"},{"text":" = (","kind":"text"},{"text":"CanonicalTileID","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID","preciseIdentifier":"c:objc(cs)MBMCanonicalTileID"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"A ","type":"text"},{"code":"canonical tile id","type":"codeVoice"},{"type":"text","text":" of the tile."}]}],"name":"tileId"}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterArraySource":{"navigatorTitle":[{"text":"RasterArraySource","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/rasterarraysource","title":"RasterArraySource","tags":[{"type":"spi","text":"SPI"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RasterArraySource","kind":"identifier"}],"abstract":[{"text":"A raster array source","type":"text"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterArraySource"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"role":"collection","title":"MapboxMaps","type":"topic","url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudgetSize":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileCacheBudgetSize"}],"title":"TileCacheBudgetSize","type":"topic","abstract":[{"type":"text","text":"Defines a TileCacheBudgetSize, which can be set as either a megabyte or tile count limit."},{"text":" ","type":"text"},{"text":"Whenever tile cache goes over the defined limit","type":"text"},{"type":"text","text":" "},{"type":"text","text":"the least recently used tile will be evicted from the in-memory cache"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetSize","url":"\/documentation\/mapboxmaps\/tilecachebudgetsize","navigatorTitle":[{"kind":"identifier","text":"TileCacheBudgetSize"}],"kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileRenderer":{"type":"topic","title":"CustomRasterSourceTileRenderer","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceTileRenderer"}],"url":"\/documentation\/mapboxmaps\/customrastersourcetilerenderer","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomRasterSourceTileRenderer","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer","abstract":[{"text":"Interface for the direct rendering into the custom raster tiles.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/VectorSource":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"VectorSource","kind":"identifier"}],"title":"VectorSource","type":"topic","abstract":[{"text":"A vector tile source.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/VectorSource","url":"\/documentation\/mapboxmaps\/vectorsource","navigatorTitle":[{"kind":"identifier","text":"VectorSource"}],"kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSource":{"type":"topic","url":"\/documentation\/mapboxmaps\/customrastersource","kind":"symbol","abstract":[{"text":"Describes a Custom Raster Source to be used in the style.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSource","title":"CustomRasterSource","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CustomRasterSource"}],"tags":[{"type":"spi","text":"SPI"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"CustomRasterSource","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceClient":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CustomRasterSourceClient"}],"title":"CustomRasterSourceClient","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient","url":"\/documentation\/mapboxmaps\/customrastersourceclient","navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceClient"}],"kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomGeometrySourceOptions":{"type":"topic","title":"CustomGeometrySourceOptions","role":"symbol","navigatorTitle":[{"text":"CustomGeometrySourceOptions","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/customgeometrysourceoptions","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomGeometrySourceOptions","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions","abstract":[{"text":"Options for custom geometry source.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GeoJSONSource":{"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GeoJSONSource"}],"title":"GeoJSONSource","type":"topic","abstract":[{"type":"text","text":"A GeoJSON data source."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSource","url":"\/documentation\/mapboxmaps\/geojsonsource","navigatorTitle":[{"text":"GeoJSONSource","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CanonicalTileID":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID","navigatorTitle":[{"text":"CanonicalTileID","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/canonicaltileid","kind":"symbol","type":"topic","title":"CanonicalTileID","abstract":[{"text":"Represents a tile coordinate.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CanonicalTileID"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileStatus":{"type":"topic","title":"CustomRasterSourceTileStatus","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceTileStatus"}],"url":"\/documentation\/mapboxmaps\/customrastersourcetilestatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomRasterSourceTileStatus","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatus","abstract":[{"text":"CustomRasterSource tile status.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceType":{"type":"topic","url":"\/documentation\/mapboxmaps\/sourcetype","kind":"symbol","abstract":[{"type":"text","text":"Struct of supported Source Types"},{"type":"text","text":" "},{"type":"text","text":"Docs : https:\/\/docs.mapbox.com\/mapbox-gl-js\/style-spec\/sources\/"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceType","title":"SourceType","role":"symbol","navigatorTitle":[{"text":"SourceType","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"SourceType","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GeoJSONSourceData":{"type":"topic","url":"\/documentation\/mapboxmaps\/geojsonsourcedata","kind":"symbol","abstract":[{"text":"Captures potential values of the ","type":"text"},{"code":"data","type":"codeVoice"},{"type":"text","text":" property of a GeoJSONSource."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSourceData","title":"GeoJSONSourceData","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GeoJSONSourceData"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GeoJSONSourceData"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PromoteId":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PromoteId"}],"title":"PromoteId","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PromoteId","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PromoteId","kind":"symbol","role":"symbol","abstract":[],"url":"\/documentation\/mapboxmaps\/promoteid"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceInfo":{"type":"topic","url":"\/documentation\/mapboxmaps\/sourceinfo","kind":"symbol","abstract":[{"type":"text","text":"Information about a Source"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceInfo","title":"SourceInfo","role":"symbol","navigatorTitle":[{"text":"SourceInfo","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SourceInfo","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomGeometrySource":{"type":"topic","title":"CustomGeometrySource","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CustomGeometrySource"}],"url":"\/documentation\/mapboxmaps\/customgeometrysource","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomGeometrySource","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySource","abstract":[{"text":"Describes a Custom Geometry Source to be used in the style","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileStatusChangedCallback":{"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"CustomRasterSourceTileStatusChangedCallback","kind":"identifier"}],"title":"CustomRasterSourceTileStatusChangedCallback","type":"topic","abstract":[{"text":"Callback for changing a CustomRasterSource tile status.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatusChangedCallback","url":"\/documentation\/mapboxmaps\/customrastersourcetilestatuschangedcallback","navigatorTitle":[{"text":"CustomRasterSourceTileStatusChangedCallback","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ImageSource":{"type":"topic","title":"ImageSource","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ImageSource"}],"url":"\/documentation\/mapboxmaps\/imagesource","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageSource","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageSource","abstract":[{"text":"An image data source.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceOptions":{"type":"topic","url":"\/documentation\/mapboxmaps\/customrastersourceoptions","kind":"symbol","abstract":[{"text":"Options for custom raster source.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions","title":"CustomRasterSourceOptions","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceOptions"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"CustomRasterSourceOptions","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","url":"\/documentation\/overview","role":"collection","kind":"article","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceClientType":{"navigatorTitle":[{"text":"CustomRasterSourceClientType","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/customrastersourceclienttype","title":"CustomRasterSourceClientType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomRasterSourceClientType","kind":"identifier"}],"abstract":[],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterDemSource":{"type":"topic","title":"RasterDemSource","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"RasterDemSource"}],"url":"\/documentation\/mapboxmaps\/rasterdemsource","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RasterDemSource","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource","abstract":[{"text":"A RGB-encoded raster DEM source","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileFunctionCallback":{"navigatorTitle":[{"text":"TileFunctionCallback","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/tilefunctioncallback","title":"TileFunctionCallback","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"TileFunctionCallback","kind":"identifier"}],"abstract":[{"text":"Callback to do various operations for tile.","type":"text"},{"type":"text","text":" "},{"text":"For example, fetching a tile or cancelling a tile request.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileFunctionCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Sources":{"type":"topic","url":"\/documentation\/mapboxmaps\/sources","kind":"article","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources","title":"Sources","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Scheme":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Scheme"}],"title":"Scheme","type":"topic","abstract":[{"text":"Influences the y direction of the tile coordinates. The global-mercator (aka Spherical Mercator) profile is assumed.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Scheme","url":"\/documentation\/mapboxmaps\/scheme","navigatorTitle":[{"text":"Scheme","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileData":{"type":"topic","url":"\/documentation\/mapboxmaps\/customrastersourcetiledata","kind":"symbol","abstract":[{"text":"Data for a specific CustomRasterSource tile.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileData","title":"CustomRasterSourceTileData","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceTileData"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomRasterSourceTileData"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Encoding":{"url":"\/documentation\/mapboxmaps\/encoding","kind":"symbol","abstract":[{"type":"text","text":"The encoding used by this source. Mapbox Terrain RGB is used by default"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Encoding","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Encoding"}],"role":"symbol","navigatorTitle":[{"text":"Encoding","kind":"identifier"}],"type":"topic","title":"Encoding"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterSource":{"navigatorTitle":[{"kind":"identifier","text":"RasterSource"}],"url":"\/documentation\/mapboxmaps\/rastersource","title":"RasterSource","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RasterSource","kind":"identifier"}],"abstract":[{"text":"A raster tile source.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterSource"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Source":{"type":"topic","url":"\/documentation\/mapboxmaps\/source","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Source","title":"Source","role":"symbol","navigatorTitle":[{"text":"Source","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Source","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Alias","path":"\/metadata\/roleHeading","op":"replace"},{"value":"MBMTileFunctionCallback","path":"\/metadata\/title","op":"replace"},{"value":"typealias","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"MBMTileFunctionCallback","kind":"identifier"}],"op":"replace"},{"value":[{"text":"MBMTileFunctionCallback","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"replace","value":[{"title":"Sources","generated":true,"anchor":"Sources","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatusChangedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatus","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType"]}],"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"preciseIdentifier":"c:BFv(#*$objc(cs)MBMCanonicalTileID)","text":"void (^)(MBMCanonicalTileID *)","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBMTileFunctionCallback"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","value":"MBMCustomRasterSourceTileRenderer","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileRenderer"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer\/navigatorTitle","value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileRenderer"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient\/title","op":"replace","value":"MBMCustomRasterSourceClient"},{"value":[{"text":"MBMCustomRasterSourceClient","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient\/navigatorTitle","value":[{"kind":"identifier","text":"MBMCustomRasterSourceClient"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions\/title","value":"MBMCustomGeometrySourceOptions"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions\/fragments","value":[{"kind":"identifier","text":"MBMCustomGeometrySourceOptions"}],"op":"replace"},{"value":[{"text":"MBMCustomGeometrySourceOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions\/navigatorTitle","op":"replace"},{"op":"replace","value":"MBMCanonicalTileID","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/fragments","value":[{"text":"MBMCanonicalTileID","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/navigatorTitle","op":"replace","value":[{"text":"MBMCanonicalTileID","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatus\/title","op":"replace","value":"MBMCustomRasterSourceTileStatus"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatus\/fragments","op":"replace","value":[{"text":"MBMCustomRasterSourceTileStatus","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileStatus"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatus\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatusChangedCallback\/title","value":"MBMCustomRasterSourceTileStatusChangedCallback"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatusChangedCallback\/fragments","value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileStatusChangedCallback"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatusChangedCallback\/navigatorTitle","value":[{"text":"MBMCustomRasterSourceTileStatusChangedCallback","kind":"identifier"}]},{"value":"MBMCustomRasterSourceOptions","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/title"},{"value":[{"text":"MBMCustomRasterSourceOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/navigatorTitle","value":[{"kind":"identifier","text":"MBMCustomRasterSourceOptions"}]},{"value":"MBMCustomRasterSourceClientType","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType\/fragments","value":[{"kind":"identifier","text":"MBMCustomRasterSourceClientType"}]},{"value":[{"text":"MBMCustomRasterSourceClientType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileFunctionCallback\/title","value":"MBMTileFunctionCallback","op":"replace"},{"value":[{"text":"MBMTileFunctionCallback","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileFunctionCallback\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileFunctionCallback\/navigatorTitle","op":"replace","value":[{"text":"MBMTileFunctionCallback","kind":"identifier"}]},{"value":"MBMCustomRasterSourceTileData","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileData\/title","op":"replace"},{"value":[{"text":"MBMCustomRasterSourceTileData","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileData\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileData\/navigatorTitle","value":[{"text":"MBMCustomRasterSourceTileData","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}