{"sections":[],"abstract":[{"type":"text","text":"The canonical tile id of a tile."},{"text":" ","type":"text"},{"text":"Non-null when the type is ","type":"text"},{"code":"MapLoadingErrorType.Tile","type":"codeVoice"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingError"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"tileId","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CanonicalTileID","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID","preciseIdentifier":"c:objc(cs)MBMCanonicalTileID"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingError\/tileId"},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tileId"},{"text":": ","kind":"text"},{"text":"CanonicalTileID","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMCanonicalTileID"},{"kind":"text","text":"?"}],"title":"tileId","modules":[{"name":"MapboxMaps"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"tileId"}],"roleHeading":"Instance Property","externalID":"c:objc(cs)MBMMapLoadingError(py)tileId","symbolKind":"property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/maploadingerror\/tileid"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/maploadingerror\/tileid"]}],"kind":"symbol","references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoadingError/tileId":{"url":"\/documentation\/mapboxmaps\/maploadingerror\/tileid","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"tileId"}],"role":"symbol","title":"tileId","type":"topic","abstract":[{"text":"The canonical tile id of a tile.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Non-null when the type is "},{"code":"MapLoadingErrorType.Tile","type":"codeVoice"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingError\/tileId","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"tileId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CanonicalTileID","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMCanonicalTileID"},{"text":"?","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoadingError":{"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingError","abstract":[{"text":"Describes an error that has occurred while loading the ","type":"text"},{"code":"map","type":"codeVoice"},{"text":". The ","type":"text"},{"type":"codeVoice","code":"type"},{"text":" property","type":"text"},{"text":" ","type":"text"},{"text":"defines what resource could not be loaded, and the ","type":"text"},{"type":"codeVoice","code":"message"},{"text":" property will contain","type":"text"},{"type":"text","text":" "},{"type":"text","text":"a descriptive error message."}],"navigatorTitle":[{"kind":"identifier","text":"MapLoadingError"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapLoadingError"}],"title":"MapLoadingError","kind":"symbol","url":"\/documentation\/mapboxmaps\/maploadingerror"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","type":"topic","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","kind":"article","title":"Map events","abstract":[{"type":"text","text":"The simplified diagram of the events emitted by the map is displayed below."}],"url":"\/documentation\/mapboxmaps\/events","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","title":"MapboxMaps Documentation","type":"topic","kind":"article","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CanonicalTileID":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID","abstract":[{"text":"Represents a tile coordinate.","type":"text"}],"title":"CanonicalTileID","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"CanonicalTileID","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/canonicaltileid","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CanonicalTileID","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"tileId","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"text":"tileId","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID","text":"MBMCanonicalTileID","preciseIdentifier":"c:objc(cs)MBMCanonicalTileID","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"tileId","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"value":"tileId","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingError~1tileId\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingError~1tileId\/fragments","op":"replace","value":[{"text":"tileId","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingError\/title","value":"MBMMapLoadingError"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingError\/fragments","value":[{"text":"MBMMapLoadingError","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingError\/navigatorTitle","value":[{"kind":"identifier","text":"MBMMapLoadingError"}]},{"op":"replace","value":"MBMCanonicalTileID","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMCanonicalTileID"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/navigatorTitle","value":[{"text":"MBMCanonicalTileID","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}