{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/map\/onmaploaded(action:)"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onMapLoaded","kind":"identifier"},{"text":"(","kind":"text"},{"text":"action","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"keyword"},{"text":" (","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoaded","text":"MapLoaded","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMMapLoaded"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":") -> ","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map","text":"Map","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps3MapV"}]}],"kind":"declarations"}],"metadata":{"role":"symbol","externalID":"s:10MapboxMaps3MapV02onC6Loaded6actionACySo06MBMMapE0Cc_tF","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onMapLoaded","kind":"identifier"},{"text":"(","kind":"text"},{"text":"action","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"MapLoaded","preciseIdentifier":"c:objc(cs)MBMMapLoaded","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Map","preciseIdentifier":"s:10MapboxMaps3MapV","kind":"typeIdentifier"}],"modules":[{"name":"MapboxMaps"}],"roleHeading":"Instance Method","title":"onMapLoaded(action:)","extendedModule":"MapboxMaps"},"abstract":[{"type":"text","text":"Adds an action to perform when the map is loaded."}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SwiftUI","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onMapLoaded(action:)"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map","url":"\/documentation\/mapboxmaps\/map","role":"symbol","type":"topic","title":"Map","kind":"symbol","abstract":[{"type":"text","text":"A SwiftUI view that displays a Mapbox Map."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Map"}],"navigatorTitle":[{"text":"Map","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoaded":{"abstract":[{"text":"The style has been fully loaded, and the ","type":"text"},{"code":"map","type":"codeVoice"},{"text":" has rendered all visible tiles.","type":"text"},{"text":" ","type":"text"},{"text":"The event will be emitted only once for the current style. If it is required to","type":"text"},{"text":" ","type":"text"},{"text":"observe an event where all required resources are loaded or rendered, please","type":"text"},{"text":" ","type":"text"},{"text":"check the following events: ","type":"text"},{"code":"MapIdle","type":"codeVoice"},{"text":", ","type":"text"},{"code":"StyleDataLoaded","type":"codeVoice"},{"text":", and ","type":"text"},{"code":"RenderFrameFinished","type":"codeVoice"},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapLoaded"}],"role":"symbol","title":"MapLoaded","kind":"symbol","url":"\/documentation\/mapboxmaps\/maploaded","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MapLoaded"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoaded"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/onMapLoaded(action:)":{"title":"onMapLoaded(action:)","url":"\/documentation\/mapboxmaps\/map\/onmaploaded(action:)","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onMapLoaded(action:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onMapLoaded","kind":"identifier"},{"text":"(","kind":"text"},{"text":"action","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMMapLoaded","text":"MapLoaded","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps3MapV","text":"Map","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Adds an action to perform when the map is loaded."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","role":"collection","title":"MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","abstract":[],"type":"topic","title":"MapboxMaps Documentation","kind":"article","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SwiftUI":{"kind":"article","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/swiftui","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SwiftUI","type":"topic","title":"SwiftUI"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoaded\/title","op":"replace","value":"MBMMapLoaded"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoaded\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMMapLoaded"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoaded\/navigatorTitle","op":"replace","value":[{"text":"MBMMapLoaded","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}