{"topicSections":[{"title":"Initializers","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderConfiguration\/init()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderConfiguration\/init(isRenderToTileSupported:shouldRerenderTiles:)"],"anchor":"Initializers"},{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderConfiguration\/isRenderToTileSupported","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderConfiguration\/shouldRerenderTiles"],"anchor":"Instance-Properties"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"title":"CustomLayerRenderConfiguration","modules":[{"name":"MapboxMaps"}],"symbolKind":"class","externalID":"c:objc(cs)MBMCustomLayerRenderConfiguration","navigatorTitle":[{"text":"CustomLayerRenderConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomLayerRenderConfiguration","kind":"identifier"}],"role":"symbol","roleHeading":"Class"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomLayerRenderConfiguration"}]}]},{"kind":"content","content":[{"type":"heading","text":"Overview","anchor":"overview","level":2},{"type":"paragraph","inlineContent":[{"text":"CustomLayerHost declares, by returning this from CustomLayerHost’s prerender, what kind of rendering it intends to do in the very next frame.","type":"text"},{"text":" ","type":"text"},{"text":"If there is need for rendering to tile textures, declare if all tiles need to be re-rendered because e.g. underlying data changed.","type":"text"}]}]}],"abstract":[{"type":"text","text":"Note! This is an experimental feature. It can be changed or removed in future versions."}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderConfiguration","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/mapboxmaps\/customlayerrenderconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/customlayerrenderconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers"]]},"sections":[],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"]},{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH"]}],"seeAlsoSections":[{"title":"Layers","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerInfo","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/BackgroundLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CircleLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillExtrusionLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationIndicatorLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterParticleLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SkyLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerHost","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ElevationData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Slot","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SlotLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerAtPosition","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClipLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClipLayerTypes"],"anchor":"Layers"}],"references":{"doc://com.mapbox.MapboxMaps/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SlotLayer":{"navigatorTitle":[{"text":"SlotLayer","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Marks the position of a slot."}],"title":"SlotLayer","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SlotLayer","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SlotLayer","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/slotlayer","type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CircleLayer":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CircleLayer","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CircleLayer"}],"navigatorTitle":[{"kind":"identifier","text":"CircleLayer"}],"title":"CircleLayer","url":"\/documentation\/mapboxmaps\/circlelayer","abstract":[{"text":"A filled circle.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FillExtrusionLayer":{"navigatorTitle":[{"kind":"identifier","text":"FillExtrusionLayer"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillExtrusionLayer","kind":"symbol","abstract":[{"type":"text","text":"An extruded (3D) polygon."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FillExtrusionLayer"}],"type":"topic","title":"FillExtrusionLayer","url":"\/documentation\/mapboxmaps\/fillextrusionlayer","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeatmapLayer":{"abstract":[{"type":"text","text":"A heatmap."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeatmapLayer"}],"title":"HeatmapLayer","url":"\/documentation\/mapboxmaps\/heatmaplayer","navigatorTitle":[{"kind":"identifier","text":"HeatmapLayer"}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerRenderConfiguration/init()":{"role":"symbol","title":"init()","navigatorTitle":[{"text":"init","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/customlayerrenderconfiguration\/init()","type":"topic","abstract":[],"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderConfiguration\/init()"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LineLayer":{"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"LineLayer","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"LineLayer","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/linelayer","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineLayer","abstract":[{"text":"A stroked line.","type":"text"}],"title":"LineLayer"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterLayer":{"navigatorTitle":[{"kind":"identifier","text":"RasterLayer"}],"kind":"symbol","title":"RasterLayer","type":"topic","url":"\/documentation\/mapboxmaps\/rasterlayer","abstract":[{"type":"text","text":"Raster map textures such as satellite imagery."}],"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"RasterLayer"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterLayer"},"doc://com.mapbox.MapboxMaps/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layer":{"title":"Layer","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Layer","kind":"identifier"}],"navigatorTitle":[{"text":"Layer","kind":"identifier"}],"abstract":[],"type":"topic","url":"\/documentation\/mapboxmaps\/layer"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerRenderConfiguration/isRenderToTileSupported":{"title":"isRenderToTileSupported","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderConfiguration\/isRenderToTileSupported","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isRenderToTileSupported"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"isRenderToTileSupported"}],"type":"topic","url":"\/documentation\/mapboxmaps\/customlayerrenderconfiguration\/isrendertotilesupported","role":"symbol","abstract":[{"type":"text","text":"If this value is true and there’s need for draping (globe or terrain are enabled), then renderToTile will be called to enable"},{"type":"text","text":" "},{"type":"text","text":"the rendering of the custom layer into the texture of a tile."},{"type":"text","text":" "},{"type":"text","text":"If this value is set, and terrain or globe are active, only render to tile render call for this layer is called,"},{"type":"text","text":" "},{"type":"text","text":"and “immediate mode” render is not called. A custom layer is, at one frame, either rendered to tile or rendered"},{"type":"text","text":" "},{"type":"text","text":"directly."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerType":{"title":"LayerType","navigatorTitle":[{"kind":"identifier","text":"LayerType"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Struct of supported Layer rendering types"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LayerType"}],"url":"\/documentation\/mapboxmaps\/layertype","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType"},"doc://com.mapbox.MapboxMaps/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject","title":"NSObject"},"doc://com.mapbox.MapboxMaps/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerAtPosition":{"url":"\/documentation\/mapboxmaps\/layeratposition","kind":"symbol","type":"topic","title":"LayerAtPosition","abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LayerAtPosition"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"LayerAtPosition"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerAtPosition"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/BackgroundLayer":{"title":"BackgroundLayer","navigatorTitle":[{"text":"BackgroundLayer","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/BackgroundLayer","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BackgroundLayer","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/backgroundlayer","kind":"symbol","abstract":[{"text":"The background color or pattern of the map.","type":"text"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SymbolLayer":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolLayer","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SymbolLayer","kind":"identifier"}],"title":"SymbolLayer","url":"\/documentation\/mapboxmaps\/symbollayer","abstract":[{"text":"An icon or a text label.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"SymbolLayer","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Slot":{"role":"symbol","navigatorTitle":[{"text":"Slot","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/slot","abstract":[{"text":"A pre-specified location in the style where layer will be added to","type":"text"},{"text":" ","type":"text"},{"text":"(such as on top of existing land layers, but below all labels).","type":"text"}],"title":"Slot","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Slot","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Slot","kind":"identifier"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SkyLayer":{"url":"\/documentation\/mapboxmaps\/skylayer","type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SkyLayer","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SkyLayer"}],"navigatorTitle":[{"kind":"identifier","text":"SkyLayer"}],"abstract":[{"type":"text","text":"A spherical dome around the map that is always rendered behind all other layers."},{"type":"text","text":" "},{"type":"text","text":"Warning: As of v10.6.0, "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Atmosphere"},{"type":"text","text":" is the preferred method for atmospheric styling. Sky layer is not supported by the globe projection, and will be phased out in future major release."}],"title":"SkyLayer"},"doc://com.mapbox.MapboxMaps/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layers":{"url":"\/documentation\/mapboxmaps\/layers","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers","abstract":[],"kind":"article","type":"topic","title":"Layers"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Atmosphere":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Atmosphere","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Atmosphere"}],"url":"\/documentation\/mapboxmaps\/atmosphere","navigatorTitle":[{"kind":"identifier","text":"Atmosphere"}],"type":"topic","abstract":[{"type":"text","text":"A style’s fog property is a global effect that improves depth perception by fading out distant objects."}],"title":"Atmosphere"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayer":{"navigatorTitle":[{"text":"CustomLayer","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"Layer with custom rendering implementation","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomLayer","kind":"identifier"}],"tags":[{"text":"SPI","type":"spi"}],"title":"CustomLayer","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayer","url":"\/documentation\/mapboxmaps\/customlayer","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","url":"\/documentation\/overview","kind":"article","type":"topic","role":"collection","abstract":[]},"doc://com.mapbox.MapboxMaps/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerRenderConfiguration/init(isRenderToTileSupported:shouldRerenderTiles:)":{"role":"symbol","title":"init(isRenderToTileSupported:shouldRerenderTiles:)","navigatorTitle":[{"text":"initWithIsRenderToTileSupported:shouldRerenderTiles:","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/customlayerrenderconfiguration\/init(isrendertotilesupported:shouldrerendertiles:)","type":"topic","abstract":[],"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"isRenderToTileSupported","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"shouldRerenderTiles","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderConfiguration\/init(isRenderToTileSupported:shouldRerenderTiles:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerRenderConfiguration/shouldRerenderTiles":{"kind":"symbol","type":"topic","role":"symbol","title":"shouldRerenderTiles","abstract":[{"text":"Set to true only for frame when content has changed - when set to true,","type":"text"},{"text":" ","type":"text"},{"text":"all the terrain render cache would get invalidated and redrawn, causing a drop in performance if invoked on every frame.","type":"text"}],"url":"\/documentation\/mapboxmaps\/customlayerrenderconfiguration\/shouldrerendertiles","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldRerenderTiles"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderConfiguration\/shouldRerenderTiles","navigatorTitle":[{"kind":"identifier","text":"shouldRerenderTiles"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerHost":{"title":"CustomLayerHost","navigatorTitle":[{"text":"CustomLayerHost","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/customlayerhost","role":"symbol","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Interface for hosting a custom map style layer."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerHost","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomLayerHost","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerRenderConfiguration":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomLayerRenderConfiguration"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderConfiguration","kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/customlayerrenderconfiguration","abstract":[{"text":"Note! This is an experimental feature. It can be changed or removed in future versions.","type":"text"}],"title":"CustomLayerRenderConfiguration","navigatorTitle":[{"kind":"identifier","text":"CustomLayerRenderConfiguration"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LocationIndicatorLayer":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationIndicatorLayer","navigatorTitle":[{"text":"LocationIndicatorLayer","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/locationindicatorlayer","abstract":[{"text":"Location Indicator layer.","type":"text"}],"role":"symbol","type":"topic","title":"LocationIndicatorLayer","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationIndicatorLayer","kind":"identifier"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerInfo":{"url":"\/documentation\/mapboxmaps\/layerinfo","navigatorTitle":[{"text":"LayerInfo","kind":"identifier"}],"abstract":[{"type":"text","text":"Information about a layer"}],"title":"LayerInfo","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerInfo","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LayerInfo","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ElevationData":{"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ElevationData","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ElevationData","abstract":[{"type":"text","text":"Interface that provides access to elevation data."}],"title":"ElevationData","url":"\/documentation\/mapboxmaps\/elevationdata","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"ElevationData","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","url":"\/documentation\/mapboxmaps","title":"MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ClipLayer":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClipLayer","role":"symbol","navigatorTitle":[{"text":"ClipLayer","kind":"identifier"}],"abstract":[{"type":"text","text":"Layer that removes 3D content from map."}],"url":"\/documentation\/mapboxmaps\/cliplayer","title":"ClipLayer","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ClipLayer","kind":"identifier"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FillLayer":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillLayer","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FillLayer"}],"url":"\/documentation\/mapboxmaps\/filllayer","navigatorTitle":[{"kind":"identifier","text":"FillLayer"}],"abstract":[{"type":"text","text":"A filled polygon with an optional stroked border."}],"title":"FillLayer","kind":"symbol","role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelLayer":{"title":"ModelLayer","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer","url":"\/documentation\/mapboxmaps\/modellayer","navigatorTitle":[{"kind":"identifier","text":"ModelLayer"}],"tags":[{"type":"spi","text":"SPI"}],"abstract":[{"text":"A layer to render 3D Models.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ModelLayer"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerRenderParameters":{"title":"CustomLayerRenderParameters","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomLayerRenderParameters"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CustomLayerRenderParameters"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/customlayerrenderparameters","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters","abstract":[{"type":"text","text":"Parameters that define the current camera position for a "},{"code":"CustomLayerHost::render()","type":"codeVoice"},{"type":"text","text":" function."}]},"doc://com.mapbox.MapboxMaps/SH":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","title":"Swift.Hashable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ClipLayerTypes":{"kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ClipLayerTypes","kind":"identifier"}],"navigatorTitle":[{"text":"ClipLayerTypes","kind":"identifier"}],"abstract":[{"type":"text","text":"Layer types that will also be removed if fallen below this clip layer."}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClipLayerTypes","title":"ClipLayerTypes","url":"\/documentation\/mapboxmaps\/cliplayertypes"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterParticleLayer":{"kind":"symbol","type":"topic","role":"symbol","title":"RasterParticleLayer","url":"\/documentation\/mapboxmaps\/rasterparticlelayer","abstract":[{"type":"text","text":"Particle animation driven by textures such as wind maps."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"RasterParticleLayer"}],"navigatorTitle":[{"kind":"identifier","text":"RasterParticleLayer"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterParticleLayer","tags":[{"text":"SPI","type":"spi"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer":{"url":"\/documentation\/mapboxmaps\/hillshadelayer","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer","role":"symbol","title":"HillshadeLayer","abstract":[{"text":"Client-side hillshading visualization based on DEM data. Currently, the implementation only supports Mapbox Terrain RGB and Mapzen Terrarium tiles.","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"HillshadeLayer"}],"navigatorTitle":[{"kind":"identifier","text":"HillshadeLayer"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"MBMCustomLayerRenderConfiguration","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"MBMCustomLayerRenderConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"MBMCustomLayerRenderConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderConfiguration\/isRenderToTileSupported","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderConfiguration\/shouldRerenderTiles"],"anchor":"Instance-Properties","generated":true},{"title":"Instance Methods","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderConfiguration\/init()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderConfiguration\/init(isRenderToTileSupported:shouldRerenderTiles:)"],"anchor":"Instance-Methods","generated":true}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"}],"op":"replace"},{"path":"\/seeAlsoSections","value":[{"generated":true,"anchor":"Layers","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerHost","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ElevationData"],"title":"Layers"}],"op":"replace"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBMCustomLayerRenderConfiguration","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderConfiguration~1init()\/title","value":"init","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderConfiguration~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderConfiguration~1isRenderToTileSupported\/title","value":"isRenderToTileSupported","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderConfiguration~1isRenderToTileSupported\/fragments","value":[{"kind":"identifier","text":"isRenderToTileSupported"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderConfiguration~1init(isRenderToTileSupported:shouldRerenderTiles:)\/title","value":"initWithIsRenderToTileSupported:shouldRerenderTiles:","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderConfiguration~1init(isRenderToTileSupported:shouldRerenderTiles:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithIsRenderToTileSupported:shouldRerenderTiles:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderConfiguration~1shouldRerenderTiles\/title","value":"shouldRerenderTiles","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderConfiguration~1shouldRerenderTiles\/fragments","value":[{"kind":"identifier","text":"shouldRerenderTiles"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost\/title","value":"MBMCustomLayerHost","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost\/fragments","value":[{"text":"MBMCustomLayerHost","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost\/navigatorTitle","value":[{"text":"MBMCustomLayerHost","kind":"identifier"}],"op":"replace"},{"value":"MBMCustomLayerRenderConfiguration","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MBMCustomLayerRenderConfiguration"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MBMCustomLayerRenderConfiguration"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderConfiguration\/navigatorTitle","op":"replace"},{"value":"MBMElevationData","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ElevationData\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MBMElevationData"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ElevationData\/fragments","op":"replace"},{"value":[{"text":"MBMElevationData","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ElevationData\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/title","value":"MBMCustomLayerRenderParameters"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/fragments","value":[{"text":"MBMCustomLayerRenderParameters","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/navigatorTitle","value":[{"text":"MBMCustomLayerRenderParameters","kind":"identifier"}]}]}]}