{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline"]]},"topicSections":[{"title":"Initializers","anchor":"Initializers","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineManager\/init()"]},{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineManager\/createTilesetDescriptor(for:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineManager\/removeStylePack(forStyleURI:)"]}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH"],"type":"conformsTo"}],"metadata":{"roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"OfflineManager"}],"role":"symbol","symbolKind":"class","title":"OfflineManager","externalID":"c:objc(cs)MBMOfflineManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OfflineManager"}],"modules":[{"name":"MapboxMaps"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OfflineManager"}]}]},{"kind":"content","content":[{"text":"Overview","type":"heading","level":2,"anchor":"overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"All the asynchronous methods calls complete even if the "},{"code":"offline manager","type":"codeVoice"},{"type":"text","text":" instance gets out of scope before."}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/offlinemanager"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/offlinemanager"]}],"abstract":[{"text":"An ","type":"text"},{"code":"offline manager","type":"codeVoice"},{"text":" manages downloads and storage for style packages and also produces tileset descriptors for the ","type":"text"},{"code":"tile store","type":"codeVoice"},{"text":".","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineManager"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"references":{"doc://com.mapbox.MapboxMaps/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP"},"doc://com.mapbox.MapboxMaps/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Offline":{"title":"Offline Support","role":"collectionGroup","abstract":[],"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","url":"\/documentation\/mapboxmaps\/offline","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineManager":{"type":"topic","title":"OfflineManager","abstract":[{"text":"An ","type":"text"},{"code":"offline manager","type":"codeVoice"},{"text":" manages downloads and storage for style packages and also produces tileset descriptors for the ","type":"text"},{"code":"tile store","type":"codeVoice"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineManager","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"OfflineManager"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OfflineManager"}],"url":"\/documentation\/mapboxmaps\/offlinemanager"},"doc://com.mapbox.MapboxMaps/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineManager/init()":{"kind":"symbol","type":"topic","title":"init()","navigatorTitle":[{"kind":"identifier","text":"init"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[{"text":"Construct a new ","type":"text"},{"code":"offline manager","type":"codeVoice"},{"text":".","type":"text"}],"url":"\/documentation\/mapboxmaps\/offlinemanager\/init()","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineManager\/init()","role":"symbol"},"doc://com.mapbox.MapboxMaps/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMaps":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","url":"\/documentation\/mapboxmaps\/coremaps","role":"collectionGroup","abstract":[{"text":"Maps rendering SDK also known as GL-Native","type":"text"}],"kind":"article","title":"Core Maps API"},"doc://com.mapbox.MapboxMaps/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineManager/removeStylePack(forStyleURI:)":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/offlinemanager\/removestylepack(forstyleuri:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeStylePack","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forStyleURI","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"abstract":[{"text":"Removes a style package.","type":"text"}],"title":"removeStylePack(forStyleURI:)","navigatorTitle":[{"text":"removeStylePackForStyleURI:","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineManager\/removeStylePack(forStyleURI:)","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","url":"\/documentation\/overview","kind":"article","type":"topic","role":"collection","abstract":[]},"doc://com.mapbox.MapboxMaps/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","url":"\/documentation\/mapboxmaps","title":"MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineManager/createTilesetDescriptor(for:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineManager\/createTilesetDescriptor(for:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createTilesetDescriptor","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TilesetDescriptorOptions","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMTilesetDescriptorOptions"},{"text":") -> ","kind":"text"},{"text":"TilesetDescriptor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXTilesetDescriptor"}],"type":"topic","url":"\/documentation\/mapboxmaps\/offlinemanager\/createtilesetdescriptor(for:)","kind":"symbol","abstract":[{"text":"Construct a new ","type":"text"},{"type":"codeVoice","code":"tileset descriptor"},{"text":" for the ","type":"text"},{"type":"codeVoice","code":"tile store"},{"text":".","type":"text"}],"title":"createTilesetDescriptor(for:)","navigatorTitle":[{"text":"createTilesetDescriptorForTilesetDescriptorOptions:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"MBMOfflineManager"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"MBMOfflineManager","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMOfflineManager"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineManager\/createTilesetDescriptor(for:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineManager\/init()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineManager\/removeStylePack(forStyleURI:)"],"anchor":"Instance-Methods","generated":true}]},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBMOfflineManager"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineManager\/title","op":"replace","value":"MBMOfflineManager"},{"value":[{"kind":"identifier","text":"MBMOfflineManager"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineManager\/fragments"},{"value":[{"kind":"identifier","text":"MBMOfflineManager"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineManager\/navigatorTitle"},{"value":"init","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineManager~1init()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineManager~1init()\/fragments"},{"value":"removeStylePackForStyleURI:","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineManager~1removeStylePack(forStyleURI:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeStylePackForStyleURI:"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineManager~1removeStylePack(forStyleURI:)\/fragments"},{"value":"createTilesetDescriptorForTilesetDescriptorOptions:","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineManager~1createTilesetDescriptor(for:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"createTilesetDescriptorForTilesetDescriptorOptions:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineManager~1createTilesetDescriptor(for:)\/fragments"}]}]}