{"abstract":[{"type":"text","text":"The structure defines the information about the resource request."}],"topicSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestInfo\/init(url:resource:priority:loadingMethod:)"],"generated":true,"anchor":"Initializers","title":"Initializers"},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestInfo\/priority","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestInfo\/resource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestInfo\/url"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestInfo"},"metadata":{"title":"RequestInfo","symbolKind":"class","externalID":"c:objc(cs)MBMRequestInfo","modules":[{"name":"MapboxMaps"}],"roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RequestInfo"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"RequestInfo"}]},"relationshipsSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequestError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResponseInfo"],"generated":true,"anchor":"Extras","title":"Extras"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RequestInfo","kind":"identifier"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"variants":[{"paths":["\/documentation\/mapboxmaps\/requestinfo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/requestinfo"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events"]]},"references":{"doc://com.mapbox.MapboxMaps/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRequestInfo/loadingMethod":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestInfo\/loadingMethod","type":"topic","role":"symbol","abstract":[{"type":"text","text":"The loading methods for the resource request."}],"title":"loadingMethod","url":"\/documentation\/mapboxmaps\/mbmrequestinfo\/loadingmethod","kind":"symbol","fragments":[{"kind":"identifier","text":"loadingMethod"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResourceRequestError":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResourceRequestError"}],"url":"\/documentation\/mapboxmaps\/resourcerequesterror","role":"symbol","title":"ResourceRequestError","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequestError","navigatorTitle":[{"kind":"identifier","text":"ResourceRequestError"}],"abstract":[{"text":"The structure defines the information about errors that may occur during a resource request.","type":"text"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResponseInfo":{"title":"ResponseInfo","type":"topic","navigatorTitle":[{"text":"ResponseInfo","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/responseinfo","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResponseInfo","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ResponseInfo","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The structure defines the information about the response for the resource request."}]},"doc://com.mapbox.MapboxMaps/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject","title":"NSObject"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","url":"\/documentation\/mapboxmaps","title":"MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestInfo":{"title":"RequestInfo","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RequestInfo","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/requestinfo","abstract":[{"type":"text","text":"The structure defines the information about the resource request."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestInfo","navigatorTitle":[{"text":"RequestInfo","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestInfo/init(url:resource:priority:loadingMethod:)":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithUrl:resource:priority:loadingMethod:"}],"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"url","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"resource","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"RequestResourceType","preciseIdentifier":"c:@E@MBMRequestResourceType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"priority","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@MBMRequestPriorityType","kind":"typeIdentifier","text":"RequestPriorityType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"loadingMethod"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":"])"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestInfo\/init(url:resource:priority:loadingMethod:)","type":"topic","title":"init(url:resource:priority:loadingMethod:)","url":"\/documentation\/mapboxmaps\/requestinfo\/init(url:resource:priority:loadingmethod:)"},"doc://com.mapbox.MapboxMaps/SH":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.mapbox.MapboxMaps/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestInfo/url":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestInfo\/url","navigatorTitle":[{"kind":"identifier","text":"url"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"url"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"type":"topic","title":"url","kind":"symbol","abstract":[{"type":"text","text":"The URL of a requested resource."}],"url":"\/documentation\/mapboxmaps\/requestinfo\/url"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","title":"Map events","type":"topic","role":"collectionGroup","abstract":[{"text":"The simplified diagram of the events emitted by the map is displayed below.","type":"text"}],"url":"\/documentation\/mapboxmaps\/events"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","url":"\/documentation\/overview","kind":"article","type":"topic","role":"collection","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestInfo/priority":{"navigatorTitle":[{"text":"priority","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestInfo\/priority","type":"topic","abstract":[{"text":"The priority of a resource request.","type":"text"}],"url":"\/documentation\/mapboxmaps\/requestinfo\/priority","title":"priority","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"priority","kind":"identifier"},{"text":": ","kind":"text"},{"text":"RequestPriorityType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMRequestPriorityType"}]},"doc://com.mapbox.MapboxMaps/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestInfo/resource":{"title":"resource","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"resource"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RequestResourceType","preciseIdentifier":"c:@E@MBMRequestResourceType"}],"navigatorTitle":[{"kind":"identifier","text":"resource"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/requestinfo\/resource","abstract":[{"type":"text","text":"The type of a requested resource."}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestInfo\/resource"},"doc://com.mapbox.MapboxMaps/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","title":"Swift.Equatable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"MBMRequestInfo","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"MBMRequestInfo","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"MBMRequestInfo","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestInfo\/loadingMethod","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestInfo\/priority","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestInfo\/resource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestInfo\/url"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestInfo\/init(url:resource:priority:loadingMethod:)"],"generated":true,"anchor":"Instance-Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}],"op":"replace"},{"path":"\/seeAlsoSections","value":[{"title":"Extras","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequestError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResponseInfo"],"generated":true,"anchor":"Extras"}],"op":"replace"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBMRequestInfo"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequestError\/title","value":"MBMResourceRequestError","op":"replace"},{"value":[{"kind":"identifier","text":"MBMResourceRequestError"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequestError\/fragments"},{"value":[{"text":"MBMResourceRequestError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequestError\/navigatorTitle"},{"value":"MBMResponseInfo","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResponseInfo\/title"},{"value":[{"kind":"identifier","text":"MBMResponseInfo"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResponseInfo\/fragments"},{"value":[{"kind":"identifier","text":"MBMResponseInfo"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResponseInfo\/navigatorTitle"},{"value":"MBMRequestInfo","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestInfo\/title"},{"value":[{"text":"MBMRequestInfo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestInfo\/fragments"},{"value":[{"kind":"identifier","text":"MBMRequestInfo"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestInfo\/navigatorTitle"},{"value":"initWithUrl:resource:priority:loadingMethod:","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestInfo~1init(url:resource:priority:loadingMethod:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithUrl:resource:priority:loadingMethod:"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestInfo~1init(url:resource:priority:loadingMethod:)\/fragments"},{"value":"url","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestInfo~1url\/title"},{"value":[{"kind":"identifier","text":"url"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestInfo~1url\/fragments"},{"value":"priority","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestInfo~1priority\/title"},{"value":[{"kind":"identifier","text":"priority"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestInfo~1priority\/fragments"},{"value":"resource","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestInfo~1resource\/title"},{"value":[{"kind":"identifier","text":"resource"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestInfo~1resource\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}