{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events"]]},"seeAlsoSections":[{"title":"Foundation","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AnyCancelable","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Cancelable","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/EventTimeInterval"],"generated":true,"anchor":"Foundation"}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Signal is a typed interface for observing arbitrary values over time.","type":"text"}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Signal\/init(just:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Signal\/init(observeImpl:)"],"generated":true,"anchor":"Initializers"},{"title":"Instance Methods","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Signal\/observe(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Signal\/observeNext(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Signal\/owned(by:)"],"generated":true,"anchor":"Instance-Methods"},{"title":"Type Aliases","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Signal\/Handler","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Signal\/ObserveImpl"],"generated":true,"anchor":"Type-Aliases"},{"title":"Default Implementations","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Signal\/Publisher-Implementations"],"generated":true,"anchor":"Default-Implementations"}],"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Signal","kind":"identifier"},{"text":"<","kind":"text"},{"text":"Payload","kind":"genericParameter"},{"text":">","kind":"text"}]}],"kind":"declarations"},{"content":[{"anchor":"overview","text":"Overview","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"Signal delegates observers managing logic to the "},{"type":"codeVoice","code":"observeImpl"},{"type":"text","text":" closure, but provides flexible interface for observing."}],"type":"paragraph"},{"name":"Note","style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"code":"Signal","type":"codeVoice"},{"type":"text","text":" is iOS12-compatible simplified alternative to "},{"code":"Combine.Publisher","type":"codeVoice"},{"type":"text","text":". It’s behavior is"},{"type":"text","text":" "},{"type":"text","text":"aligned with Publisher for easier future migration to Combine. If your app supports iOS >= 13.0, use "},{"code":"Signal","type":"codeVoice"},{"type":"text","text":" as "},{"code":"Combine.Publisher","type":"codeVoice"},{"type":"text","text":" ."}]}],"type":"aside"}],"kind":"content"}],"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/7Combine9PublisherP","doc:\/\/com.mapbox.MapboxMaps\/s8CopyableP"],"type":"conformsTo","kind":"relationships"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/signal"]}],"metadata":{"roleHeading":"Structure","symbolKind":"struct","modules":[{"name":"MapboxMaps"}],"navigatorTitle":[{"text":"Signal","kind":"identifier"}],"title":"Signal","externalID":"s:10MapboxMaps6SignalV","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Signal"}],"role":"symbol"},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Signal","interfaceLanguage":"swift"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Signal/observeNext(_:)":{"title":"observeNext(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"observeNext","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Signal","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"text":"<","kind":"text"},{"text":"Payload","kind":"typeIdentifier"},{"text":">.","kind":"text"},{"text":"Handler","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV7Handlera"},{"text":") -> ","kind":"text"},{"text":"AnyCancelable","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps13AnyCancelableC"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Signal\/observeNext(_:)","url":"\/documentation\/mapboxmaps\/signal\/observenext(_:)","role":"symbol","abstract":[{"type":"text","text":"Adds an observer closure that will be triggered only once."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Signal/observe(_:)":{"role":"symbol","url":"\/documentation\/mapboxmaps\/signal\/observe(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"observe","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Signal","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"text":"<","kind":"text"},{"text":"Payload","kind":"typeIdentifier"},{"text":">.","kind":"text"},{"text":"Handler","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV7Handlera"},{"text":") -> ","kind":"text"},{"text":"AnyCancelable","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps13AnyCancelableC"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Signal\/observe(_:)","abstract":[{"text":"Adds an observer closure that will be called every time signal is triggered.","type":"text"}],"type":"topic","title":"observe(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","role":"collectionGroup","title":"Map events","kind":"article","type":"topic","abstract":[{"type":"text","text":"The simplified diagram of the events emitted by the map is displayed below."}],"url":"\/documentation\/mapboxmaps\/events"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraAnimator":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraAnimator","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraAnimator"}],"navigatorTitle":[{"kind":"identifier","text":"CameraAnimator"}],"url":"\/documentation\/mapboxmaps\/cameraanimator","kind":"symbol","type":"topic","title":"CameraAnimator"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Cancelable":{"title":"Cancelable","abstract":[{"type":"text","text":"Allows to cancel the associated asynchronous operation"}],"kind":"symbol","type":"topic","url":"\/documentation\/mapboxcommon\/cancelable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Cancelable","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"Cancelable","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Cancelable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/EventTimeInterval":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/EventTimeInterval","kind":"symbol","url":"\/documentation\/mapboxmaps\/eventtimeinterval","type":"topic","title":"EventTimeInterval","abstract":[{"type":"text","text":"The time interval of an event. The "},{"code":"begin","type":"codeVoice"},{"type":"text","text":" property represents the time"},{"type":"text","text":" "},{"type":"text","text":"origin of an event, and the "},{"code":"end","type":"codeVoice"},{"type":"text","text":" property represents the time when the particular"},{"type":"text","text":" "},{"type":"text","text":"operation is complete. The timestamps are sampled at the origin and do not include"},{"type":"text","text":" "},{"type":"text","text":"the time required to dispatch an event."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EventTimeInterval","kind":"identifier"}],"navigatorTitle":[{"text":"EventTimeInterval","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Signal/owned(by:)":{"title":"owned(by:)","kind":"symbol","conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"code":"Payload","type":"codeVoice"},{"type":"text","text":" is "},{"code":"any CameraAnimator","type":"codeVoice"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}]},"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"owned"},{"kind":"text","text":"("},{"kind":"externalParam","text":"by"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnimationOwner","preciseIdentifier":"s:10MapboxMaps14AnimationOwnerV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Signal","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Payload"},{"kind":"text","text":">"}],"type":"topic","abstract":[{"text":"Creates new Signal from upstream filtering out ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraAnimator"},{"text":" that is not owned by the given ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AnimationOwner"},{"text":".","type":"text"}],"url":"\/documentation\/mapboxmaps\/signal\/owned(by:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Signal\/owned(by:)","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Signal/init(just:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"just"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Payload"},{"kind":"text","text":")"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Signal\/init(just:)","role":"symbol","url":"\/documentation\/mapboxmaps\/signal\/init(just:)","abstract":[{"type":"text","text":"Creates a signal that sends payload once to every subscribed."}],"kind":"symbol","title":"init(just:)"},"doc://com.mapbox.MapboxMaps/7Combine9PublisherP":{"title":"Combine.Publisher","identifier":"doc:\/\/com.mapbox.MapboxMaps\/7Combine9PublisherP","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/s8CopyableP":{"title":"Swift.Copyable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s8CopyableP","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Signal/init(observeImpl:)":{"title":"init(observeImpl:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Signal\/init(observeImpl:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"observeImpl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Signal","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Payload"},{"kind":"text","text":">."},{"kind":"typeIdentifier","text":"ObserveImpl","preciseIdentifier":"s:10MapboxMaps6SignalV11ObserveImpla"},{"kind":"text","text":")"}],"abstract":[{"text":"Creates a signal.","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/signal\/init(observeimpl:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Signal":{"abstract":[{"type":"text","text":"Signal is a typed interface for observing arbitrary values over time."}],"kind":"symbol","navigatorTitle":[{"text":"Signal","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxmaps\/signal","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Signal","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Signal","role":"symbol","title":"Signal"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Signal/Publisher-Implementations":{"type":"topic","role":"collectionGroup","title":"Publisher Implementations","url":"\/documentation\/mapboxmaps\/signal\/publisher-implementations","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Signal\/Publisher-Implementations","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Signal/Handler":{"abstract":[{"type":"text","text":"Handles received payloads."}],"url":"\/documentation\/mapboxmaps\/signal\/handler","type":"topic","title":"Signal.Handler","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Handler","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Signal\/Handler","role":"symbol","navigatorTitle":[{"text":"Handler","kind":"identifier"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AnimationOwner":{"type":"topic","navigatorTitle":[{"text":"AnimationOwner","kind":"identifier"}],"kind":"symbol","title":"AnimationOwner","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AnimationOwner","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AnimationOwner","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/animationowner","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Signal/ObserveImpl":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Signal\/ObserveImpl","kind":"symbol","title":"Signal.ObserveImpl","abstract":[{"text":"A closure that implements observing.","type":"text"}],"navigatorTitle":[{"text":"ObserveImpl","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/signal\/observeimpl","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ObserveImpl","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article","url":"\/documentation\/overview","role":"collection","abstract":[],"title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AnyCancelable":{"url":"\/documentation\/mapboxmaps\/anycancelable","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AnyCancelable","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AnyCancelable","abstract":[{"text":"A Cancellable object that automatically cancels on deinit.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"AnyCancelable","kind":"identifier"}],"title":"AnyCancelable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/title","op":"replace","value":"MBXCancelable"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXCancelable"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBXCancelable"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1EventTimeInterval\/title","op":"replace","value":"MBMEventTimeInterval"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1EventTimeInterval\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMEventTimeInterval"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1EventTimeInterval\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMEventTimeInterval"}]}]}]}