{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"offsetX","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"title":"offsetX","modules":[{"name":"MapboxMaps"}],"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"offsetX"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"offsetX","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"symbolKind":"property","externalID":"c:objc(cs)MBMViewAnnotationAnchorConfig(py)offsetX"},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchorConfig\/offsetX","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/View-Annotations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchorConfig"]]},"sections":[],"abstract":[{"text":"Extra X offset in ","type":"text"},{"type":"codeVoice","code":"platform pixels"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Providing positive value moves view annotation to the right while negative moves it to the left."},{"type":"text","text":" "},{"text":"The default value is 0.","type":"text"}],"variants":[{"paths":["\/documentation\/mapboxmaps\/viewannotationanchorconfig\/offsetx"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/viewannotationanchorconfig\/offsetx"]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationAnchorConfig/offsetX":{"kind":"symbol","title":"offsetX","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchorConfig\/offsetX","navigatorTitle":[{"text":"offsetX","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/viewannotationanchorconfig\/offsetx","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"offsetX","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"Extra X offset in "},{"code":"platform pixels","type":"codeVoice"},{"text":".","type":"text"},{"type":"text","text":" "},{"text":"Providing positive value moves view annotation to the right while negative moves it to the left.","type":"text"},{"type":"text","text":" "},{"text":"The default value is 0.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationAnchorConfig":{"abstract":[{"text":"Represents a specific setting for a view annotation anchor.","type":"text"}],"title":"ViewAnnotationAnchorConfig","role":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/viewannotationanchorconfig","navigatorTitle":[{"text":"ViewAnnotationAnchorConfig","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchorConfig","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ViewAnnotationAnchorConfig"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","title":"MapboxMaps","type":"topic","url":"\/documentation\/mapboxmaps","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/View-Annotations":{"role":"collectionGroup","type":"topic","url":"\/documentation\/mapboxmaps\/view-annotations","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/View-Annotations","abstract":[],"title":"View Annotations"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"kind":"article","url":"\/documentation\/overview","role":"collection","title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"offsetX"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"kind":"identifier","text":"offsetX"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"offsetX","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"value":"offsetX","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchorConfig~1offsetX\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchorConfig~1offsetX\/fragments","op":"replace","value":[{"kind":"identifier","text":"offsetX"}]},{"value":"MBMViewAnnotationAnchorConfig","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchorConfig\/title","op":"replace"},{"value":[{"text":"MBMViewAnnotationAnchorConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchorConfig\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchorConfig\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMViewAnnotationAnchorConfig"}]}]}]}