{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer-Property-Values","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValueKind"]]},"kind":"article","topicSections":[{"title":"Operators","anchor":"Operators","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValueKind\/!=(_:_:)"],"generated":true}],"metadata":{"role":"collectionGroup","title":"Equatable Implementations","modules":[{"name":"MapboxMaps"}],"roleHeading":"API Collection"},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValueKind\/Equatable-Implementations"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePropertyValueKind":{"kind":"symbol","title":"StylePropertyValueKind","type":"topic","url":"\/documentation\/mapboxmaps\/stylepropertyvaluekind","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StylePropertyValueKind"}],"role":"symbol","navigatorTitle":[{"text":"StylePropertyValueKind","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValueKind","abstract":[{"type":"text","text":"Describes the kind of a style property value."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layer-Property-Values":{"kind":"article","title":"Layer Property Values","type":"topic","url":"\/documentation\/mapboxmaps\/layer-property-values","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer-Property-Values","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","url":"\/documentation\/overview","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"role":"collection","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePropertyValueKind/!=(_:_:)":{"title":"!=(_:_:)","kind":"symbol","url":"\/documentation\/mapboxmaps\/stylepropertyvaluekind\/!=(_:_:)","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValueKind\/!=(_:_:)","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"kind":"text","text":" "},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValueKind\/title","op":"replace","value":"MBMStylePropertyValueKind"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValueKind\/fragments","value":[{"kind":"identifier","text":"MBMStylePropertyValueKind"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValueKind\/navigatorTitle","op":"replace","value":[{"text":"MBMStylePropertyValueKind","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}