{"topicSections":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpMethod\/hashValue"]},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpMethod\/hash(into:)"],"anchor":"Instance-Methods"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"kind":"article","metadata":{"roleHeading":"API Collection","modules":[{"name":"MapboxCommon"}],"title":"RawRepresentable Implementations","role":"collectionGroup"},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpMethod\/RawRepresentable-Implementations","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpMethod"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","abstract":[],"kind":"article","url":"\/documentation\/overview","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","title":"MapboxCommon","kind":"symbol","abstract":[],"url":"\/documentation\/mapboxcommon","role":"collection","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpMethod":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"HttpMethod"}],"kind":"symbol","role":"symbol","title":"HttpMethod","url":"\/documentation\/mapboxcommon\/httpmethod","abstract":[{"type":"text","text":"HTTP defines a set of request methods to indicate the desired action to be performed for a given resource."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpMethod","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HttpMethod"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpMethod/hash(into:)":{"abstract":[],"type":"topic","title":"hash(into:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpMethod\/hash(into:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":": "},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hasher","kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV"},{"kind":"text","text":")"}],"role":"symbol","conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"type":"codeVoice","code":"Self"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}]},"kind":"symbol","url":"\/documentation\/mapboxcommon\/httpmethod\/hash(into:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpMethod/hashValue":{"conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"abstract":[],"url":"\/documentation\/mapboxcommon\/httpmethod\/hashvalue","kind":"symbol","title":"hashValue","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpMethod\/hashValue","type":"topic"}},"variantOverrides":[{"patch":[{"value":"MBXHttpMethod","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpMethod\/title"},{"value":[{"text":"MBXHttpMethod","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpMethod\/fragments","op":"replace"},{"value":[{"text":"MBXHttpMethod","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpMethod\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}