{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"variants":[{"paths":["\/documentation\/mapboxmaps\/styleimageremoveunused\/imageid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/styleimageremoveunused\/imageid"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:objc(cs)MBMStyleImageRemoveUnused(py)imageId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"role":"symbol","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"MapboxMaps"}],"title":"imageId","navigatorTitle":[{"kind":"identifier","text":"imageId"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnused"]]},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnused\/imageId","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"The identifier of an image that is not used by the "},{"type":"codeVoice","code":"map"},{"type":"text","text":"."}],"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"kind":"article","role":"collection","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleImageRemoveUnused":{"url":"\/documentation\/mapboxmaps\/styleimageremoveunused","abstract":[{"type":"text","text":"An image requested by the "},{"type":"codeVoice","code":"map"},{"type":"text","text":" through the "},{"type":"codeVoice","code":"StyleImageMissing"},{"type":"text","text":" event is no longer"},{"type":"text","text":" "},{"type":"text","text":"needed and can be removed using the "},{"type":"codeVoice","code":"removeStyleImage"},{"type":"text","text":" method. The application can"},{"type":"text","text":" "},{"type":"text","text":"decide whether the image should be kept or removed."}],"navigatorTitle":[{"text":"StyleImageRemoveUnused","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StyleImageRemoveUnused","kind":"identifier"}],"title":"StyleImageRemoveUnused","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnused"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleImageRemoveUnused/imageId":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/styleimageremoveunused\/imageid","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnused\/imageId","title":"imageId","navigatorTitle":[{"text":"imageId","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"The identifier of an image that is not used by the "},{"type":"codeVoice","code":"map"},{"type":"text","text":"."}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"role":"collectionGroup","kind":"article","type":"topic","url":"\/documentation\/mapboxmaps\/events","title":"Map events","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","abstract":[{"text":"The simplified diagram of the events emitted by the map is displayed below.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"imageId","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"imageId","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"imageId","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MBMStyleImageRemoveUnused","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnused\/title"},{"value":[{"kind":"identifier","text":"MBMStyleImageRemoveUnused"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnused\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MBMStyleImageRemoveUnused"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnused\/navigatorTitle"},{"op":"replace","value":"imageId","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnused~1imageId\/title"},{"op":"replace","value":[{"kind":"identifier","text":"imageId"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnused~1imageId\/fragments"}]}]}