{"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/mapboxcommon\/nsexceptionhandler\/try(callback:)"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@discardableResult","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"`try`"},{"kind":"text","text":"<"},{"text":"T","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"callback","kind":"externalParam"},{"text":": () ","kind":"text"},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"T"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"kind":"typeIdentifier","text":"T"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NSExceptionHandler"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NSExceptionHandler\/try(callback:)","interfaceLanguage":"swift"},"metadata":{"title":"try(callback:)","role":"symbol","roleHeading":"Type Method","symbolKind":"method","externalID":"s:So19MBXExceptionHandlerC12MapboxCommonE3try8callbackxxyKXE_tKlFZ","extendedModule":"MapboxCommon","modules":[{"name":"MapboxCommon"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"`try`"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"T"},{"text":">(","kind":"text"},{"text":"callback","kind":"externalParam"},{"text":": () ","kind":"text"},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"text":"T","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"},{"text":" -> ","kind":"text"},{"text":"T","kind":"typeIdentifier"}]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Performance":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","title":"Performance and investigations","type":"topic","abstract":[],"kind":"article","url":"\/documentation\/mapboxmaps\/performance","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","type":"topic","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","abstract":[],"role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/NSExceptionHandler/try(callback:)":{"url":"\/documentation\/mapboxcommon\/nsexceptionhandler\/try(callback:)","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NSExceptionHandler\/try(callback:)","title":"try(callback:)","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"`try`","kind":"identifier"},{"text":"<","kind":"text"},{"text":"T","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"callback","kind":"externalParam"},{"text":": () ","kind":"text"},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"T"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"T"}],"role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","title":"MapboxMaps","kind":"symbol","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/NSExceptionHandler":{"kind":"symbol","type":"topic","url":"\/documentation\/mapboxcommon\/nsexceptionhandler","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"NSExceptionHandler"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NSExceptionHandler"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NSExceptionHandler","title":"NSExceptionHandler","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1NSExceptionHandler\/title","value":"MBXExceptionHandler"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1NSExceptionHandler\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXExceptionHandler"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1NSExceptionHandler\/navigatorTitle","value":[{"text":"MBXExceptionHandler","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}