{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"databaseError"}]}]}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"MBXCacheClearingErrorTypeDatabaseError"}],"modules":[{"name":"MapboxCommon"}],"roleHeading":"Case","externalID":"c:@E@MBXCacheClearingErrorType@MBXCacheClearingErrorTypeDatabaseError","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"databaseError","kind":"identifier"}],"role":"symbol","symbolKind":"case","title":"CacheClearingErrorType.databaseError"},"variants":[{"paths":["\/documentation\/mapboxcommon\/cacheclearingerrortype\/databaseerror"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/cacheclearingerrortype\/databaseerror"]}],"sections":[],"abstract":[{"text":"There was an issue accessing the database","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingErrorType"]]},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingErrorType\/databaseError","interfaceLanguage":"swift"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/CacheClearingErrorType/databaseError":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingErrorType\/databaseError","title":"CacheClearingErrorType.databaseError","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"databaseError"}],"type":"topic","url":"\/documentation\/mapboxcommon\/cacheclearingerrortype\/databaseerror","abstract":[{"type":"text","text":"There was an issue accessing the database"}],"navigatorTitle":[{"text":"MBXCacheClearingErrorTypeDatabaseError","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"type":"topic","role":"collection","url":"\/documentation\/mapboxmaps","title":"MapboxMaps","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"type":"topic","role":"collectionGroup","kind":"article","title":"TileStore APIs","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","url":"\/documentation\/mapboxmaps\/tilestore-apis"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","role":"collection","kind":"article","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/CacheClearingErrorType":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingErrorType","title":"CacheClearingErrorType","abstract":[{"type":"text","text":"Describes the reason for a cache clearing failure."}],"type":"topic","url":"\/documentation\/mapboxcommon\/cacheclearingerrortype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CacheClearingErrorType"}],"navigatorTitle":[{"kind":"identifier","text":"CacheClearingErrorType"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"MBXCacheClearingErrorTypeDatabaseError"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"MBXCacheClearingErrorTypeDatabaseError","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"MBXCacheClearingErrorTypeDatabaseError"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"MBXCacheClearingErrorTypeDatabaseError","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingErrorType~1databaseError\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingErrorType~1databaseError\/fragments","value":[{"text":"MBXCacheClearingErrorTypeDatabaseError","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingErrorType\/title","value":"MBXCacheClearingErrorType"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingErrorType\/fragments","value":[{"text":"MBXCacheClearingErrorType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingErrorType\/navigatorTitle","value":[{"kind":"identifier","text":"MBXCacheClearingErrorType"}],"op":"replace"}]}]}