{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"metadata"},{"text":": ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"inlineContent":[{"text":"If provided, the custom value value will be stored alongside the tile region. Previous values will","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"be replaced with the new value."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"Developers can use this field to store custom metadata associated with a tile region. This value","type":"text"},{"type":"text","text":" "},{"text":"can be retrieved with getTileRegionMetadata().","type":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/tileregionloadoptions\/metadata"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/tileregionloadoptions\/metadata"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions\/metadata"},"abstract":[{"type":"text","text":"A custom Mapbox Value associated with this tile region for storing metadata."}],"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"metadata","kind":"identifier"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"text":"?","kind":"text"}],"externalID":"c:objc(cs)MBXTileRegionLoadOptions(py)metadata","navigatorTitle":[{"text":"metadata","kind":"identifier"}],"modules":[{"name":"MapboxCommon"}],"roleHeading":"Instance Property","symbolKind":"property","title":"metadata"},"kind":"symbol","sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadOptions":{"navigatorTitle":[{"kind":"identifier","text":"TileRegionLoadOptions"}],"type":"topic","abstract":[{"type":"text","text":"Describes the tile region load option values."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TileRegionLoadOptions"}],"url":"\/documentation\/mapboxcommon\/tileregionloadoptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions","title":"TileRegionLoadOptions","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"title":"TileStore APIs","abstract":[],"kind":"article","url":"\/documentation\/mapboxmaps\/tilestore-apis","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","role":"collectionGroup","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadOptions/metadata":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions\/metadata","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"metadata","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?","kind":"text"}],"url":"\/documentation\/mapboxcommon\/tileregionloadoptions\/metadata","navigatorTitle":[{"text":"metadata","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"A custom Mapbox Value associated with this tile region for storing metadata.","type":"text"}],"title":"metadata"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","url":"\/documentation\/mapboxmaps","type":"topic","kind":"symbol","title":"MapboxMaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"type":"topic","title":"MapboxMaps Documentation","url":"\/documentation\/overview"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"metadata"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"metadata","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":" "},{"text":"metadata","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/title","value":"MBXTileRegionLoadOptions"},{"value":[{"kind":"identifier","text":"MBXTileRegionLoadOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/navigatorTitle","value":[{"text":"MBXTileRegionLoadOptions","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions~1metadata\/title","value":"metadata"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions~1metadata\/fragments","op":"replace","value":[{"text":"metadata","kind":"identifier"}]}]}]}