{"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accuracy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"displacement"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"interval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXIntervalSettings","text":"IntervalSettings","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/IntervalSettings"},{"kind":"text","text":"?)"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"symbolKind":"init","title":"init(accuracy:displacement:interval:)","roleHeading":"Initializer","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accuracy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"displacement"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"interval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IntervalSettings","preciseIdentifier":"c:objc(cs)MBXIntervalSettings"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"text":"initWithAccuracy:displacement:interval:","kind":"identifier"}],"modules":[{"name":"MapboxCommon"}],"externalID":"c:objc(cs)MBXLocationProviderRequest(im)initWithAccuracy:displacement:interval:"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProviderRequest"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/locationproviderrequest\/init(accuracy:displacement:interval:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/locationproviderrequest\/init(accuracy:displacement:interval:)"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProviderRequest\/init(accuracy:displacement:interval:)"},"kind":"symbol","references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Location-APIs":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","title":"Location","abstract":[],"url":"\/documentation\/mapboxmaps\/location-apis","type":"topic","role":"collectionGroup","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","role":"collection","url":"\/documentation\/overview","title":"MapboxMaps Documentation","kind":"article","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/IntervalSettings":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntervalSettings"}],"abstract":[{"type":"text","text":"The interval for active location updates"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/IntervalSettings","title":"IntervalSettings","navigatorTitle":[{"kind":"identifier","text":"IntervalSettings"}],"role":"symbol","url":"\/documentation\/mapboxcommon\/intervalsettings","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationProviderRequest":{"title":"LocationProviderRequest","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationProviderRequest"}],"navigatorTitle":[{"kind":"identifier","text":"LocationProviderRequest"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProviderRequest","abstract":[{"type":"text","text":"Data model that contains parameters for location requests."}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/mapboxcommon\/locationproviderrequest"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationProviderRequest/init(accuracy:displacement:interval:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"accuracy","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"displacement","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"interval","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"IntervalSettings","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXIntervalSettings"},{"text":"?)","kind":"text"}],"type":"topic","url":"\/documentation\/mapboxcommon\/locationproviderrequest\/init(accuracy:displacement:interval:)","abstract":[],"title":"init(accuracy:displacement:interval:)","kind":"symbol","navigatorTitle":[{"text":"initWithAccuracy:displacement:interval:","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProviderRequest\/init(accuracy:displacement:interval:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","title":"MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"initWithAccuracy:displacement:interval:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithAccuracy:displacement:interval:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithAccuracy:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accuracy"},{"kind":"text","text":" "},{"kind":"identifier","text":"displacement:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"displacement"},{"kind":"text","text":" "},{"kind":"identifier","text":"interval:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MBXIntervalSettings","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/IntervalSettings","preciseIdentifier":"c:objc(cs)MBXIntervalSettings"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"interval"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"MBXIntervalSettings","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1IntervalSettings\/title"},{"op":"replace","value":[{"text":"MBXIntervalSettings","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1IntervalSettings\/fragments"},{"op":"replace","value":[{"text":"MBXIntervalSettings","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1IntervalSettings\/navigatorTitle"},{"op":"replace","value":"MBXLocationProviderRequest","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProviderRequest\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBXLocationProviderRequest"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProviderRequest\/fragments"},{"op":"replace","value":[{"text":"MBXLocationProviderRequest","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProviderRequest\/navigatorTitle"},{"op":"replace","value":"initWithAccuracy:displacement:interval:","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProviderRequest~1init(accuracy:displacement:interval:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAccuracy:displacement:interval:"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProviderRequest~1init(accuracy:displacement:interval:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}