{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Constrain to height only","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"heightOnly"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/constrainmode\/heightonly"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/constrainmode\/heightonly"]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ConstrainMode\/heightOnly","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"MapboxMaps"}],"roleHeading":"Case","externalID":"c:@E@MBMConstrainMode@MBMConstrainModeHeightOnly","navigatorTitle":[{"kind":"identifier","text":"MBMConstrainModeHeightOnly"}],"role":"symbol","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"heightOnly"}],"title":"ConstrainMode.heightOnly"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-View","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ConstrainMode"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map-View":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-View","url":"\/documentation\/mapboxmaps\/map-view","abstract":[],"role":"collectionGroup","kind":"article","title":"MapView","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ConstrainMode":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ConstrainMode","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ConstrainMode","role":"symbol","kind":"symbol","url":"\/documentation\/mapboxmaps\/constrainmode","title":"ConstrainMode","abstract":[{"type":"text","text":"Describes whether to constrain the map in both axes or only vertically e.g. while panning."}],"navigatorTitle":[{"text":"ConstrainMode","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ConstrainMode/heightOnly":{"kind":"symbol","abstract":[{"type":"text","text":"Constrain to height only"}],"navigatorTitle":[{"text":"MBMConstrainModeHeightOnly","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ConstrainMode\/heightOnly","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"heightOnly"}],"title":"ConstrainMode.heightOnly","url":"\/documentation\/mapboxmaps\/constrainmode\/heightonly","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"url":"\/documentation\/mapboxmaps","type":"topic","title":"MapboxMaps","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article","title":"MapboxMaps Documentation","url":"\/documentation\/overview","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"value":"MBMConstrainModeHeightOnly","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MBMConstrainModeHeightOnly","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"MBMConstrainModeHeightOnly","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"MBMConstrainMode","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ConstrainMode\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ConstrainMode\/fragments","value":[{"text":"MBMConstrainMode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ConstrainMode\/navigatorTitle","value":[{"kind":"identifier","text":"MBMConstrainMode"}]},{"value":"MBMConstrainModeHeightOnly","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ConstrainMode~1heightOnly\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ConstrainMode~1heightOnly\/fragments","value":[{"text":"MBMConstrainModeHeightOnly","kind":"identifier"}]}]}]}