{"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchor\/topLeft","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/viewannotationanchor\/topleft"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/viewannotationanchor\/topleft"]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/View-Annotations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchor"]]},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"symbolKind":"case","externalID":"c:@E@MBMViewAnnotationAnchor@MBMViewAnnotationAnchorTopLeft","navigatorTitle":[{"kind":"identifier","text":"MBMViewAnnotationAnchorTopLeft"}],"role":"symbol","title":"ViewAnnotationAnchor.topLeft","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"topLeft","kind":"identifier"}],"roleHeading":"Case","modules":[{"name":"MapboxMaps"}]},"abstract":[{"text":"The top-left corner of the view annotation is placed closest to the geometry.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"topLeft","kind":"identifier"}],"languages":["swift"]}]}],"kind":"symbol","references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationAnchor/topLeft":{"abstract":[{"type":"text","text":"The top-left corner of the view annotation is placed closest to the geometry."}],"title":"ViewAnnotationAnchor.topLeft","type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"topLeft","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/viewannotationanchor\/topleft","navigatorTitle":[{"text":"MBMViewAnnotationAnchorTopLeft","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchor\/topLeft","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/View-Annotations":{"type":"topic","kind":"article","abstract":[],"title":"View Annotations","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/View-Annotations","url":"\/documentation\/mapboxmaps\/view-annotations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationAnchor":{"title":"ViewAnnotationAnchor","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchor","role":"symbol","abstract":[{"type":"text","text":"Enum describing how to place view annotation relatively to geometry."}],"navigatorTitle":[{"text":"ViewAnnotationAnchor","kind":"identifier"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ViewAnnotationAnchor"}],"url":"\/documentation\/mapboxmaps\/viewannotationanchor","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","kind":"article","title":"MapboxMaps Documentation","abstract":[],"role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"MBMViewAnnotationAnchorTopLeft"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMViewAnnotationAnchorTopLeft"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"MBMViewAnnotationAnchorTopLeft"}],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchor~1topLeft\/title","value":"MBMViewAnnotationAnchorTopLeft"},{"value":[{"text":"MBMViewAnnotationAnchorTopLeft","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchor~1topLeft\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchor\/title","op":"replace","value":"MBMViewAnnotationAnchor"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchor\/fragments","value":[{"text":"MBMViewAnnotationAnchor","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchor\/navigatorTitle","value":[{"text":"MBMViewAnnotationAnchor","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}