{"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType\/requestTimedOut","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@E@MBXHttpRequestErrorType@MBXHttpRequestErrorTypeRequestTimedOut","modules":[{"name":"MapboxCommon"}],"title":"HttpRequestErrorType.requestTimedOut","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"MBXHttpRequestErrorTypeRequestTimedOut"}],"role":"symbol","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"requestTimedOut","kind":"identifier"}]},"kind":"symbol","abstract":[{"text":"Timeout error.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestTimedOut"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/httprequesterrortype\/requesttimedout"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/httprequesterrortype\/requesttimedout"]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"title":"MapboxCommon","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/mapboxcommon","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestErrorType":{"role":"symbol","title":"HttpRequestErrorType","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HttpRequestErrorType"}],"abstract":[{"text":"Enum which describes possible error types which could happen during HTTP request\/download calls.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"HttpRequestErrorType"}],"url":"\/documentation\/mapboxcommon\/httprequesterrortype","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","abstract":[],"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","kind":"article","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestErrorType/requestTimedOut":{"role":"symbol","title":"HttpRequestErrorType.requestTimedOut","url":"\/documentation\/mapboxcommon\/httprequesterrortype\/requesttimedout","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType\/requestTimedOut","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestTimedOut"}],"navigatorTitle":[{"kind":"identifier","text":"MBXHttpRequestErrorTypeRequestTimedOut"}],"abstract":[{"type":"text","text":"Timeout error."}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"MBXHttpRequestErrorTypeRequestTimedOut","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MBXHttpRequestErrorTypeRequestTimedOut"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"MBXHttpRequestErrorTypeRequestTimedOut"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestErrorType\/title","value":"MBXHttpRequestErrorType","op":"replace"},{"value":[{"text":"MBXHttpRequestErrorType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestErrorType\/fragments"},{"value":[{"text":"MBXHttpRequestErrorType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestErrorType\/navigatorTitle"},{"value":"MBXHttpRequestErrorTypeRequestTimedOut","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestErrorType~1requestTimedOut\/title"},{"value":[{"text":"MBXHttpRequestErrorTypeRequestTimedOut","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestErrorType~1requestTimedOut\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}