{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType\/Equatable-Implementations"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"lhs","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":", ","kind":"text"},{"text":"rhs","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]}]}],"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/requestresourcetype\/!=(_:_:)"]}],"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"Equatable.!=(_:_:)"},{"text":".","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType\/!=(_:_:)","interfaceLanguage":"swift"},"metadata":{"title":"!=(_:_:)","externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::c:@E@MBMRequestResourceType","symbolKind":"op","roleHeading":"Operator","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"kind":"text","text":" "},{"kind":"text","text":"("},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"modules":[{"name":"MapboxMaps","relatedModules":["Swift"]}],"extendedModule":"Swift","role":"symbol"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestResourceType/!=(_:_:)":{"title":"!=(_:_:)","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType\/!=(_:_:)","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"text":" ","kind":"text"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"url":"\/documentation\/mapboxmaps\/requestresourcetype\/!=(_:_:)","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","url":"\/documentation\/mapboxmaps","type":"topic","role":"collection","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","role":"collection","abstract":[],"kind":"article","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestResourceType":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType","role":"symbol","title":"RequestResourceType","url":"\/documentation\/mapboxmaps\/requestresourcetype","type":"topic","navigatorTitle":[{"text":"RequestResourceType","kind":"identifier"}],"abstract":[{"text":"The enumeration defines the type of resource requested by the ","type":"text"},{"type":"codeVoice","code":"map"},{"type":"text","text":"."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RequestResourceType"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestResourceType/Equatable-Implementations":{"url":"\/documentation\/mapboxmaps\/requestresourcetype\/equatable-implementations","abstract":[],"role":"collectionGroup","kind":"article","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType\/Equatable-Implementations","title":"Equatable Implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"url":"\/documentation\/mapboxmaps\/events","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","kind":"article","abstract":[{"text":"The simplified diagram of the events emitted by the map is displayed below.","type":"text"}],"type":"topic","title":"Map events"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestResourceType\/title","value":"MBMRequestResourceType","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestResourceType\/fragments","op":"replace","value":[{"text":"MBMRequestResourceType","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MBMRequestResourceType"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestResourceType\/navigatorTitle"}]}]}