{"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer\/deinitialize()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Destroy any GL state needed by the custom renderer, and deallocate context, if necessary. This"},{"type":"text","text":" "},{"type":"text","text":"method is called once, at a point when the GL context is active."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/customrastersourcetilerenderer\/deinitialize()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/customrastersourcetilerenderer\/deinitialize()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deinitialize"},{"kind":"text","text":"()"}],"title":"deinitialize()","modules":[{"name":"MapboxMaps"}],"required":true,"roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"deinitialize"}],"role":"symbol","externalID":"c:objc(pl)MBMCustomRasterSourceTileRenderer(im)deinitialize"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deinitialize"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"Note that it may be called even when the ","type":"text"},{"type":"codeVoice","code":"initialize"},{"text":" function has not been called.","type":"text"}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Sources":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources","abstract":[],"role":"collectionGroup","type":"topic","kind":"article","title":"Sources","url":"\/documentation\/mapboxmaps\/sources"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileRenderer/deinitialize()":{"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer\/deinitialize()","navigatorTitle":[{"kind":"identifier","text":"deinitialize"}],"title":"deinitialize()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deinitialize"},{"kind":"text","text":"()"}],"url":"\/documentation\/mapboxmaps\/customrastersourcetilerenderer\/deinitialize()","abstract":[{"type":"text","text":"Destroy any GL state needed by the custom renderer, and deallocate context, if necessary. This"},{"type":"text","text":" "},{"type":"text","text":"method is called once, at a point when the GL context is active."}],"required":true},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","title":"MapboxMaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"url":"\/documentation\/mapboxmaps","kind":"symbol","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"title":"MapboxMaps Documentation","type":"topic","kind":"article","role":"collection","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileRenderer":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomRasterSourceTileRenderer","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/customrastersourcetilerenderer","role":"symbol","title":"CustomRasterSourceTileRenderer","navigatorTitle":[{"text":"CustomRasterSourceTileRenderer","kind":"identifier"}],"abstract":[{"text":"Interface for the direct rendering into the custom raster tiles.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"deinitialize","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deinitialize"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"deinitialize"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"deinitialize","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer~1deinitialize()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"deinitialize","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer~1deinitialize()\/fragments"},{"op":"replace","value":"MBMCustomRasterSourceTileRenderer","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileRenderer"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileRenderer"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer\/navigatorTitle"}]}]}