{"kind":"symbol","metadata":{"roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StyleDataLoaded","kind":"identifier"}],"externalID":"c:objc(cs)MBMStyleDataLoaded","modules":[{"name":"MapboxMaps"}],"role":"symbol","symbolKind":"class","title":"StyleDataLoaded","navigatorTitle":[{"text":"StyleDataLoaded","kind":"identifier"}]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoaded"},"seeAlsoSections":[{"title":"Events","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraChanged","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapIdle","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceAdded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceRemoved","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageMissing","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnused","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameStarted","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinished","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequest","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GenericEvent"],"anchor":"Events","generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StyleDataLoaded","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"anchor":"overview","type":"heading","level":2,"text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Note: The event may be emitted synchronously, for example, when "},{"type":"codeVoice","code":"setStyleJSON"},{"type":"text","text":" "},{"type":"text","text":"is used to load style."}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/mapboxmaps\/styledataloaded"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/styledataloaded"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoaded\/init(type:timeInterval:)"],"anchor":"Initializers","generated":true},{"title":"Instance Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoaded\/timeInterval","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoaded\/type"],"anchor":"Instance-Properties","generated":true}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH"],"type":"conformsTo","kind":"relationships"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"The style data has been loaded. The event will be emitted once for each ","type":"text"},{"type":"codeVoice","code":"StyleDataLoadedType"},{"text":" ","type":"text"},{"text":"type during style loading. If a new style is set, events will be emitted again for the newly set style.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","role":"collection","title":"MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/SH":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","title":"Swift.Hashable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleDataLoaded/type":{"role":"symbol","url":"\/documentation\/mapboxmaps\/styledataloaded\/type","abstract":[{"type":"text","text":"The type of loaded style data."}],"navigatorTitle":[{"kind":"identifier","text":"type"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMStyleDataLoadedType","text":"StyleDataLoadedType"}],"title":"type","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoaded\/type","type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.mapbox.MapboxMaps/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleDataLoaded":{"url":"\/documentation\/mapboxmaps\/styledataloaded","title":"StyleDataLoaded","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoaded","kind":"symbol","type":"topic","abstract":[{"text":"The style data has been loaded. The event will be emitted once for each ","type":"text"},{"code":"StyleDataLoadedType","type":"codeVoice"},{"text":" ","type":"text"},{"text":"type during style loading. If a new style is set, events will be emitted again for the newly set style.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"StyleDataLoaded"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StyleDataLoaded"}]},"doc://com.mapbox.MapboxMaps/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapIdle":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapIdle","title":"MapIdle","url":"\/documentation\/mapboxmaps\/mapidle","kind":"symbol","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"map"},{"type":"text","text":" has entered the idle state. The "},{"type":"codeVoice","code":"map"},{"type":"text","text":" is idle when there are no ongoing"},{"type":"text","text":" "},{"type":"text","text":"animations, transitions and the "},{"type":"codeVoice","code":"map"},{"type":"text","text":" has rendered all requested non-volatile tiles"},{"type":"text","text":" "},{"type":"text","text":"(e.g., live traffic tiles). The event will not be emitted if "},{"type":"codeVoice","code":"setUserAnimationInProgress"},{"type":"text","text":" "},{"type":"text","text":"and \/ or "},{"type":"codeVoice","code":"setGestureInProgress"},{"type":"text","text":" is set to "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"navigatorTitle":[{"kind":"identifier","text":"MapIdle"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapIdle"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GenericEvent":{"navigatorTitle":[{"kind":"identifier","text":"GenericEvent"}],"title":"GenericEvent","type":"topic","abstract":[{"type":"text","text":"The generic event type."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GenericEvent"}],"url":"\/documentation\/mapboxmaps\/genericevent","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GenericEvent","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","url":"\/documentation\/overview","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","kind":"article","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraChanged":{"abstract":[{"text":"This event is emitted whenever the visible viewport changes its size","type":"text"},{"text":" ","type":"text"},{"text":"due to the invocation of the ","type":"text"},{"code":"setSize","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"setBounds","type":"codeVoice"},{"text":" methods or when","type":"text"},{"text":" ","type":"text"},{"text":"the camera is modified by calling camera methods. The event is emitted","type":"text"},{"text":" ","type":"text"},{"text":"synchronously so that an updated camera state can be read immediately.","type":"text"}],"url":"\/documentation\/mapboxmaps\/camerachanged","title":"CameraChanged","role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraChanged","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraChanged"}],"navigatorTitle":[{"kind":"identifier","text":"CameraChanged"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderFrameStarted":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameStarted","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RenderFrameStarted"}],"url":"\/documentation\/mapboxmaps\/renderframestarted","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"map"},{"type":"text","text":" started rendering a frame."}],"kind":"symbol","title":"RenderFrameStarted","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RenderFrameStarted"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleDataLoaded/init(type:timeInterval:)":{"role":"symbol","url":"\/documentation\/mapboxmaps\/styledataloaded\/init(type:timeinterval:)","abstract":[],"navigatorTitle":[{"text":"initWithType:timeInterval:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"StyleDataLoadedType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMStyleDataLoadedType"},{"text":", ","kind":"text"},{"text":"timeInterval","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"EventTimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMEventTimeInterval"},{"text":")","kind":"text"}],"title":"init(type:timeInterval:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoaded\/init(type:timeInterval:)","type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceAdded":{"abstract":[{"text":"The source has been added with ","type":"text"},{"code":"addStyleSource","type":"codeVoice"},{"text":" method.","type":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/sourceadded","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceAdded","navigatorTitle":[{"kind":"identifier","text":"SourceAdded"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceAdded"}],"title":"SourceAdded"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoadingError":{"title":"MapLoadingError","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"MapLoadingError","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingError","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapLoadingError","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/maploadingerror","abstract":[{"text":"Describes an error that has occurred while loading the ","type":"text"},{"code":"map","type":"codeVoice"},{"text":". The ","type":"text"},{"code":"type","type":"codeVoice"},{"text":" property","type":"text"},{"text":" ","type":"text"},{"text":"defines what resource could not be loaded, and the ","type":"text"},{"code":"message","type":"codeVoice"},{"text":" property will contain","type":"text"},{"text":" ","type":"text"},{"text":"a descriptive error message.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceRemoved":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SourceRemoved"}],"title":"SourceRemoved","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceRemoved","url":"\/documentation\/mapboxmaps\/sourceremoved","abstract":[{"type":"text","text":"The source has been removed with "},{"code":"removeStyleSource","type":"codeVoice"},{"type":"text","text":" method."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceRemoved"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"url":"\/documentation\/mapboxmaps\/events","type":"topic","kind":"article","title":"Map events","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","abstract":[{"text":"The simplified diagram of the events emitted by the map is displayed below.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleLoaded":{"url":"\/documentation\/mapboxmaps\/styleloaded","kind":"symbol","abstract":[{"type":"text","text":"The requested style has been fully loaded, including specified sprite, and sources’ metadata."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"StyleLoaded"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleLoaded","role":"symbol","title":"StyleLoaded","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StyleLoaded"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleDataLoaded/timeInterval":{"kind":"symbol","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"timeInterval.begin"},{"type":"text","text":" is when style data begins loading, and the "},{"type":"codeVoice","code":"timeInterval.end"},{"type":"text","text":" is when style data is loaded."}],"navigatorTitle":[{"text":"timeInterval","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timeInterval","kind":"identifier"},{"text":": ","kind":"text"},{"text":"EventTimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMEventTimeInterval"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoaded\/timeInterval","url":"\/documentation\/mapboxmaps\/styledataloaded\/timeinterval","type":"topic","role":"symbol","title":"timeInterval"},"doc://com.mapbox.MapboxMaps/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject","title":"NSObject"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoaded":{"abstract":[{"text":"The style has been fully loaded, and the ","type":"text"},{"code":"map","type":"codeVoice"},{"text":" has rendered all visible tiles.","type":"text"},{"text":" ","type":"text"},{"text":"The event will be emitted only once for the current style. If it is required to","type":"text"},{"text":" ","type":"text"},{"text":"observe an event where all required resources are loaded or rendered, please","type":"text"},{"text":" ","type":"text"},{"text":"check the following events: ","type":"text"},{"code":"MapIdle","type":"codeVoice"},{"text":", ","type":"text"},{"code":"StyleDataLoaded","type":"codeVoice"},{"text":", and ","type":"text"},{"code":"RenderFrameFinished","type":"codeVoice"},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapLoaded"}],"navigatorTitle":[{"kind":"identifier","text":"MapLoaded"}],"url":"\/documentation\/mapboxmaps\/maploaded","role":"symbol","title":"MapLoaded","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoaded","kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResourceRequest":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/resourcerequest","type":"topic","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ResourceRequest"},{"type":"text","text":" event allows the application to observe resource requests made by a "},{"type":"codeVoice","code":"map"},{"type":"text","text":" or "},{"type":"codeVoice","code":"map snapshotter"},{"type":"text","text":" object."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResourceRequest"}],"title":"ResourceRequest","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequest","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ResourceRequest"}]},"doc://com.mapbox.MapboxMaps/SQ":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleImageRemoveUnused":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnused","abstract":[{"text":"An image requested by the ","type":"text"},{"code":"map","type":"codeVoice"},{"text":" through the ","type":"text"},{"code":"StyleImageMissing","type":"codeVoice"},{"text":" event is no longer","type":"text"},{"text":" ","type":"text"},{"text":"needed and can be removed using the ","type":"text"},{"code":"removeStyleImage","type":"codeVoice"},{"text":" method. The application can","type":"text"},{"text":" ","type":"text"},{"text":"decide whether the image should be kept or removed.","type":"text"}],"url":"\/documentation\/mapboxmaps\/styleimageremoveunused","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"StyleImageRemoveUnused"}],"kind":"symbol","type":"topic","title":"StyleImageRemoveUnused","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StyleImageRemoveUnused"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceDataLoaded":{"title":"SourceDataLoaded","kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/sourcedataloaded","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoaded","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceDataLoaded"}],"navigatorTitle":[{"kind":"identifier","text":"SourceDataLoaded"}],"abstract":[{"text":"The ","type":"text"},{"code":"SourceDataLoaded","type":"codeVoice"},{"text":" event is emitted when source data is loaded.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleImageMissing":{"title":"StyleImageMissing","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageMissing","url":"\/documentation\/mapboxmaps\/styleimagemissing","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StyleImageMissing"}],"abstract":[{"text":"A style needs an image that is missing from the sprite sheet. This event is","type":"text"},{"text":" ","type":"text"},{"text":"emitted when the ","type":"text"},{"type":"codeVoice","code":"map"},{"text":" renders visible tiles, and one of the required images","type":"text"},{"text":" ","type":"text"},{"text":"is missing in the sprite sheet. The event observer has to provide the missing","type":"text"},{"text":" ","type":"text"},{"text":"image by calling the ","type":"text"},{"type":"codeVoice","code":"addStyleImage"},{"text":" method.","type":"text"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"StyleImageMissing"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderFrameFinished":{"url":"\/documentation\/mapboxmaps\/renderframefinished","kind":"symbol","navigatorTitle":[{"text":"RenderFrameFinished","kind":"identifier"}],"title":"RenderFrameFinished","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RenderFrameFinished","kind":"identifier"}],"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"map"},{"text":" finished rendering a frame.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinished","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"MBMStyleDataLoaded","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"MBMStyleDataLoaded","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"MBMStyleDataLoaded","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoaded\/timeInterval","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoaded\/type"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoaded\/init(type:timeInterval:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"}],"op":"replace","path":"\/relationshipsSections"},{"value":[{"anchor":"Events","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraChanged","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapIdle","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceAdded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceRemoved","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageMissing","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnused","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameStarted","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinished","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequest","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GenericEvent"],"generated":true,"title":"Events"}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBMStyleDataLoaded","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"type","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoaded~1type\/title"},{"value":[{"kind":"identifier","text":"type"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoaded~1type\/fragments"},{"value":"MBMStyleDataLoaded","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoaded\/title"},{"value":[{"kind":"identifier","text":"MBMStyleDataLoaded"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoaded\/fragments"},{"value":[{"text":"MBMStyleDataLoaded","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoaded\/navigatorTitle"},{"value":"MBMMapIdle","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdle\/title"},{"value":[{"text":"MBMMapIdle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdle\/fragments"},{"value":[{"kind":"identifier","text":"MBMMapIdle"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdle\/navigatorTitle"},{"value":"MBMGenericEvent","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEvent\/title"},{"value":[{"text":"MBMGenericEvent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEvent\/fragments"},{"value":[{"text":"MBMGenericEvent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEvent\/navigatorTitle"},{"value":"MBMCameraChanged","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChanged\/title"},{"value":[{"kind":"identifier","text":"MBMCameraChanged"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChanged\/fragments"},{"value":[{"text":"MBMCameraChanged","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChanged\/navigatorTitle"},{"value":"MBMRenderFrameStarted","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameStarted\/title"},{"value":[{"kind":"identifier","text":"MBMRenderFrameStarted"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameStarted\/fragments"},{"value":[{"text":"MBMRenderFrameStarted","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameStarted\/navigatorTitle"},{"value":"initWithType:timeInterval:","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoaded~1init(type:timeInterval:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithType:timeInterval:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoaded~1init(type:timeInterval:)\/fragments"},{"value":"MBMSourceAdded","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAdded\/title"},{"value":[{"kind":"identifier","text":"MBMSourceAdded"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAdded\/fragments"},{"value":[{"kind":"identifier","text":"MBMSourceAdded"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAdded\/navigatorTitle"},{"value":"MBMMapLoadingError","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingError\/title"},{"value":[{"kind":"identifier","text":"MBMMapLoadingError"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingError\/fragments"},{"value":[{"text":"MBMMapLoadingError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingError\/navigatorTitle"},{"value":"MBMSourceRemoved","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceRemoved\/title"},{"value":[{"text":"MBMSourceRemoved","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceRemoved\/fragments"},{"value":[{"kind":"identifier","text":"MBMSourceRemoved"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceRemoved\/navigatorTitle"},{"value":"MBMStyleLoaded","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoaded\/title"},{"value":[{"text":"MBMStyleLoaded","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoaded\/fragments"},{"value":[{"text":"MBMStyleLoaded","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoaded\/navigatorTitle"},{"value":"timeInterval","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoaded~1timeInterval\/title"},{"value":[{"kind":"identifier","text":"timeInterval"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoaded~1timeInterval\/fragments"},{"value":"MBMMapLoaded","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoaded\/title"},{"value":[{"text":"MBMMapLoaded","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoaded\/fragments"},{"value":[{"text":"MBMMapLoaded","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoaded\/navigatorTitle"},{"value":"MBMResourceRequest","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequest\/title"},{"value":[{"kind":"identifier","text":"MBMResourceRequest"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequest\/fragments"},{"value":[{"kind":"identifier","text":"MBMResourceRequest"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequest\/navigatorTitle"},{"value":"MBMStyleImageRemoveUnused","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnused\/title"},{"value":[{"kind":"identifier","text":"MBMStyleImageRemoveUnused"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnused\/fragments"},{"value":[{"kind":"identifier","text":"MBMStyleImageRemoveUnused"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnused\/navigatorTitle"},{"value":"MBMSourceDataLoaded","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoaded\/title"},{"value":[{"text":"MBMSourceDataLoaded","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoaded\/fragments"},{"value":[{"kind":"identifier","text":"MBMSourceDataLoaded"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoaded\/navigatorTitle"},{"value":"MBMStyleImageMissing","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageMissing\/title"},{"value":[{"kind":"identifier","text":"MBMStyleImageMissing"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageMissing\/fragments"},{"value":[{"kind":"identifier","text":"MBMStyleImageMissing"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageMissing\/navigatorTitle"},{"value":"MBMRenderFrameFinished","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinished\/title"},{"value":[{"text":"MBMRenderFrameFinished","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinished\/fragments"},{"value":[{"kind":"identifier","text":"MBMRenderFrameFinished"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinished\/navigatorTitle"}]}]}