{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManager"},"schemaVersion":{"major":0,"patch":0,"minor":3},"seeAlsoSections":[{"generated":true,"anchor":"View-Annotations","title":"View Annotations","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManagerError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchorConfig","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationPositionDescriptor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationUpdateObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchor"]}],"abstract":[{"text":"Manager API to control View Annotations.","type":"text"}],"topicSections":[{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManager\/allAnnotations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManager\/annotations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManager\/validatesViews","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManager\/viewAnnotationAvoidLayers"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManager\/add(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManager\/add(_:id:options:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManager\/add(_:options:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManager\/addViewAnnotationUpdateObserver(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManager\/camera(forAnnotations:padding:bearing:pitch:)-5oqrz","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManager\/camera(forAnnotations:padding:bearing:pitch:)-6gqyr","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManager\/options(for:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManager\/remove(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManager\/removeAll()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManager\/removeViewAnnotationUpdateObserver(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManager\/update(_:options:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManager\/view(forId:)"],"anchor":"Instance-Methods","generated":true}],"variants":[{"paths":["\/documentation\/mapboxmaps\/viewannotationmanager"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/View-Annotations"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ViewAnnotationManager"}]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"type":"heading","text":"Overview","anchor":"overview"},{"inlineContent":[{"type":"text","text":"View annotations are "},{"code":"UIView","type":"codeVoice"},{"type":"text","text":" instances that are drawn on top of the "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapView","isActive":true,"type":"reference"},{"type":"text","text":" and bound to an arbitrary "},{"type":"codeVoice","code":"Geometry"},{"type":"text","text":" such as "},{"type":"codeVoice","code":"Point"},{"type":"text","text":", or a "},{"code":"Feature","type":"codeVoice"},{"type":"text","text":" rendered on a layer."},{"text":" ","type":"text"},{"type":"text","text":"In case some view annotations intersect on the screen Z-index is based on addition order."}],"type":"paragraph"},{"inlineContent":[{"text":"View annotations are invariant to map camera transformations however such properties as size, visibility etc","type":"text"},{"text":" ","type":"text"},{"text":"could be controlled by the user using update operation.","type":"text"}],"type":"paragraph"}]}],"kind":"symbol","metadata":{"symbolKind":"class","externalID":"s:10MapboxMaps21ViewAnnotationManagerC","navigatorTitle":[{"text":"ViewAnnotationManager","kind":"identifier"}],"role":"symbol","modules":[{"name":"MapboxMaps"}],"title":"ViewAnnotationManager","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ViewAnnotationManager","kind":"identifier"}],"roleHeading":"Class"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationManager/options(for:)":{"role":"symbol","url":"\/documentation\/mapboxmaps\/viewannotationmanager\/options(for:)","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManager\/options(for:)","title":"options(for:)","abstract":[{"type":"text","text":"Get current "},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationOptions","isActive":true},{"text":" for given ","type":"text"},{"type":"codeVoice","code":"UIView"},{"type":"text","text":"."}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"options","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps21ViewAnnotationOptionsV","text":"ViewAnnotationOptions"},{"text":"?","kind":"text"}],"deprecated":true},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationManager/camera(forAnnotations:padding:bearing:pitch:)-5oqrz":{"title":"camera(forAnnotations:padding:bearing:pitch:)","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManager\/camera(forAnnotations:padding:bearing:pitch:)-5oqrz","url":"\/documentation\/mapboxmaps\/viewannotationmanager\/camera(forannotations:padding:bearing:pitch:)-5oqrz","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"camera"},{"text":"(","kind":"text"},{"text":"forAnnotations","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"ViewAnnotation","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps14ViewAnnotationC"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"padding"},{"kind":"text","text":": "},{"text":"UIEdgeInsets","kind":"typeIdentifier","preciseIdentifier":"c:@S@UIEdgeInsets"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"bearing"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"pitch"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:10MapboxMaps13CameraOptionsV","text":"CameraOptions","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"text":"Calculates ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraOptions","isActive":true,"type":"reference"},{"type":"text","text":" to fit the list of view annotations."}],"kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationManager/update(_:options:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"update","kind":"identifier"},{"kind":"text","text":"("},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"options","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ViewAnnotationOptions","preciseIdentifier":"s:10MapboxMaps21ViewAnnotationOptionsV"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"deprecated":true,"title":"update(_:options:)","role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManager\/update(_:options:)","kind":"symbol","abstract":[{"type":"text","text":"Update given "},{"code":"UIView","type":"codeVoice"},{"text":" with ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationOptions"},{"type":"text","text":"."},{"text":" ","type":"text"},{"text":"Important thing to keep in mind that only properties present in ","type":"text"},{"code":"options","type":"codeVoice"},{"type":"text","text":" will be updated,"},{"text":" ","type":"text"},{"type":"text","text":"all other will remain the same as specified before."}],"url":"\/documentation\/mapboxmaps\/viewannotationmanager\/update(_:options:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationPositionDescriptor":{"kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/viewannotationpositiondescriptor","abstract":[{"text":"Read-only data that is needed to correctly position the single view annotation on screen.","type":"text"},{"type":"text","text":" "},{"text":"Used inside ViewAnnotationPositionsUpdateListener callback to notify the listener about the visible view annotations’ position updates.","type":"text"}],"navigatorTitle":[{"text":"ViewAnnotationPositionDescriptor","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ViewAnnotationPositionDescriptor","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationPositionDescriptor","title":"ViewAnnotationPositionDescriptor","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationManager/validatesViews":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManager\/validatesViews","abstract":[{"text":"If the superview or the ","type":"text"},{"type":"codeVoice","code":"UIView.isHidden"},{"type":"text","text":" property of a custom view annotation is changed manually by the users"},{"text":" ","type":"text"},{"text":"the SDK prints a warning and reverts the changes, as the view is still considered for layout calculation.","type":"text"},{"type":"text","text":" "},{"text":"The default value is true, and setting this value to false will disable the validation.","type":"text"}],"title":"validatesViews","url":"\/documentation\/mapboxmaps\/viewannotationmanager\/validatesviews","role":"symbol","deprecated":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"validatesViews"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationOptions":{"kind":"symbol","type":"topic","abstract":[{"text":"Stores layout and visibility settings for a view annotation.","type":"text"}],"title":"ViewAnnotationOptions","role":"symbol","url":"\/documentation\/mapboxmaps\/viewannotationoptions","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ViewAnnotationOptions"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationOptions","navigatorTitle":[{"kind":"identifier","text":"ViewAnnotationOptions"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationOptions/width":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"width"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationOptions\/width","url":"\/documentation\/mapboxmaps\/viewannotationoptions\/width","title":"width","abstract":[{"text":"View annotation width in pixels.","type":"text"}],"role":"symbol","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraOptions":{"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"CameraOptions","kind":"identifier"}],"type":"topic","abstract":[],"url":"\/documentation\/mapboxmaps\/cameraoptions","title":"CameraOptions","navigatorTitle":[{"text":"CameraOptions","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraOptions","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationManager/removeViewAnnotationUpdateObserver(_:)":{"title":"removeViewAnnotationUpdateObserver(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManager\/removeViewAnnotationUpdateObserver(_:)","type":"topic","url":"\/documentation\/mapboxmaps\/viewannotationmanager\/removeviewannotationupdateobserver(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"removeViewAnnotationUpdateObserver","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"ViewAnnotationUpdateObserver","preciseIdentifier":"s:10MapboxMaps28ViewAnnotationUpdateObserverP","kind":"typeIdentifier"},{"kind":"text","text":")"}],"deprecated":true,"abstract":[{"text":"Remove an observer for annotation views updates.","type":"text"}],"kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","title":"MapboxMaps","kind":"symbol","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationUpdateObserver":{"type":"topic","abstract":[{"type":"text","text":"An interface you use to detect when the map view lays out or updates visibility of annotation views."}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ViewAnnotationUpdateObserver"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/viewannotationupdateobserver","title":"ViewAnnotationUpdateObserver","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationUpdateObserver","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ViewAnnotationUpdateObserver"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationManagerError":{"url":"\/documentation\/mapboxmaps\/viewannotationmanagererror","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManagerError","title":"ViewAnnotationManagerError","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ViewAnnotationManagerError"}],"abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"ViewAnnotationManagerError","kind":"identifier"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationManager/allAnnotations":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManager\/allAnnotations","abstract":[{"text":"The list of view annotations added to the manager.","type":"text"}],"title":"allAnnotations","url":"\/documentation\/mapboxmaps\/viewannotationmanager\/allannotations","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"allAnnotations","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"ViewAnnotation","preciseIdentifier":"s:10MapboxMaps14ViewAnnotationC"},{"text":"]","kind":"text"}],"type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationManager/add(_:options:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"add","kind":"identifier"},{"kind":"text","text":"("},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ViewAnnotationOptions","preciseIdentifier":"s:10MapboxMaps21ViewAnnotationOptionsV"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"url":"\/documentation\/mapboxmaps\/viewannotationmanager\/add(_:options:)","type":"topic","title":"add(_:options:)","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManager\/add(_:options:)","deprecated":true,"abstract":[{"text":"Add a ","type":"text"},{"code":"UIView","type":"codeVoice"},{"type":"text","text":" instance which will be displayed as an annotation."},{"type":"text","text":" "},{"text":"View dimensions will be taken as width \/ height from the bounds of the view","type":"text"},{"type":"text","text":" "},{"text":"unless they are not specified explicitly with ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationOptions\/width","type":"reference","isActive":true},{"type":"text","text":" and "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationOptions\/height"},{"type":"text","text":"."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationManager/view(forId:)":{"title":"view(forId:)","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManager\/view(forId:)","url":"\/documentation\/mapboxmaps\/viewannotationmanager\/view(forid:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"view"},{"text":"(","kind":"text"},{"text":"forId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"deprecated":true,"abstract":[{"type":"text","text":"Find view annotation by the given "},{"code":"id","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationManager/add(_:id:options:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManager\/add(_:id:options:)","abstract":[{"text":"Add a ","type":"text"},{"code":"UIView","type":"codeVoice"},{"type":"text","text":" instance which will be displayed as an annotation."},{"text":" ","type":"text"},{"text":"View dimensions will be taken as width \/ height from the bounds of the view","type":"text"},{"type":"text","text":" "},{"type":"text","text":"unless they are not specified explicitly with "},{"isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationOptions\/width","type":"reference"},{"text":" and ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationOptions\/height","type":"reference"},{"type":"text","text":"."}],"title":"add(_:id:options:)","url":"\/documentation\/mapboxmaps\/viewannotationmanager\/add(_:id:options:)","role":"symbol","deprecated":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"add"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", "},{"text":"id","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ViewAnnotationOptions","preciseIdentifier":"s:10MapboxMaps21ViewAnnotationOptionsV","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/View-Annotations":{"abstract":[],"url":"\/documentation\/mapboxmaps\/view-annotations","kind":"article","role":"collectionGroup","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/View-Annotations","title":"View Annotations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationManager/add(_:)":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManager\/add(_:)","url":"\/documentation\/mapboxmaps\/viewannotationmanager\/add(_:)","title":"add(_:)","role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"add"},{"kind":"text","text":"("},{"text":"ViewAnnotation","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps14ViewAnnotationC"},{"text":")","kind":"text"}],"abstract":[{"text":"Add a ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation"},{"text":" to the map.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationAnchorConfig":{"title":"ViewAnnotationAnchorConfig","abstract":[{"text":"Represents a specific setting for a view annotation anchor.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ViewAnnotationAnchorConfig"}],"url":"\/documentation\/mapboxmaps\/viewannotationanchorconfig","navigatorTitle":[{"kind":"identifier","text":"ViewAnnotationAnchorConfig"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchorConfig","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","type":"topic","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","abstract":[],"role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationManager/camera(forAnnotations:padding:bearing:pitch:)-6gqyr":{"kind":"symbol","abstract":[{"text":"Calculates ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraOptions"},{"text":" to fit the list of view annotations.","type":"text"}],"role":"symbol","deprecated":true,"type":"topic","url":"\/documentation\/mapboxmaps\/viewannotationmanager\/camera(forannotations:padding:bearing:pitch:)-6gqyr","title":"camera(forAnnotations:padding:bearing:pitch:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"camera","kind":"identifier"},{"kind":"text","text":"("},{"text":"forAnnotations","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"], "},{"text":"padding","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIEdgeInsets","preciseIdentifier":"c:@S@UIEdgeInsets"},{"text":", ","kind":"text"},{"text":"bearing","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"kind":"text","text":"?, "},{"text":"pitch","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"text":"?) -> ","kind":"text"},{"text":"CameraOptions","preciseIdentifier":"s:10MapboxMaps13CameraOptionsV","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManager\/camera(forAnnotations:padding:bearing:pitch:)-6gqyr"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotation":{"abstract":[{"text":"Creates a view annotation.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation","url":"\/documentation\/mapboxmaps\/viewannotation","role":"symbol","title":"ViewAnnotation","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ViewAnnotation"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"ViewAnnotation","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationManager":{"url":"\/documentation\/mapboxmaps\/viewannotationmanager","abstract":[{"text":"Manager API to control View Annotations.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManager","title":"ViewAnnotationManager","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ViewAnnotationManager"}],"type":"topic","navigatorTitle":[{"text":"ViewAnnotationManager","kind":"identifier"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationManager/remove(_:)":{"url":"\/documentation\/mapboxmaps\/viewannotationmanager\/remove(_:)","deprecated":true,"type":"topic","abstract":[{"text":"Remove given ","type":"text"},{"code":"UIView","type":"codeVoice"},{"text":" from the map if it was present.","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManager\/remove(_:)","title":"remove(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"remove"},{"text":"(","kind":"text"},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationOptions/height":{"abstract":[{"type":"text","text":"View annotation height in pixels."}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationOptions\/height","url":"\/documentation\/mapboxmaps\/viewannotationoptions\/height","role":"symbol","kind":"symbol","title":"height","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"height"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":"?","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapView":{"title":"MapView","type":"topic","kind":"symbol","role":"symbol","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapView","url":"\/documentation\/mapboxmaps\/mapview","navigatorTitle":[{"text":"MapView","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapView"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationManager/addViewAnnotationUpdateObserver(_:)":{"title":"addViewAnnotationUpdateObserver(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManager\/addViewAnnotationUpdateObserver(_:)","type":"topic","url":"\/documentation\/mapboxmaps\/viewannotationmanager\/addviewannotationupdateobserver(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addViewAnnotationUpdateObserver"},{"text":"(any ","kind":"text"},{"kind":"typeIdentifier","text":"ViewAnnotationUpdateObserver","preciseIdentifier":"s:10MapboxMaps28ViewAnnotationUpdateObserverP"},{"text":")","kind":"text"}],"deprecated":true,"abstract":[{"text":"Add an observer for annotation views updates","type":"text"}],"kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationManager/removeAll()":{"url":"\/documentation\/mapboxmaps\/viewannotationmanager\/removeall()","type":"topic","abstract":[{"type":"text","text":"Removes all annotations views from the map."}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManager\/removeAll()","title":"removeAll()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"removeAll"},{"text":"()","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationManager/annotations":{"kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/viewannotationmanager\/annotations","abstract":[{"type":"text","text":"The complete list of annotations associated with the receiver."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"annotations","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps21ViewAnnotationOptionsV","text":"ViewAnnotationOptions"},{"text":"]","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManager\/annotations","deprecated":true,"title":"annotations","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationManager/viewAnnotationAvoidLayers":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManager\/viewAnnotationAvoidLayers","abstract":[{"text":"Specify layers that view annotations should avoid. This applies to ALL view annotations associated to any layer.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The API currently only supports line layers."}],"title":"viewAnnotationAvoidLayers","url":"\/documentation\/mapboxmaps\/viewannotationmanager\/viewannotationavoidlayers","role":"symbol","tags":[{"text":"SPI","type":"spi"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewAnnotationAvoidLayers","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sh","text":"Set"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":">","kind":"text"}],"type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationAnchor":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchor","navigatorTitle":[{"kind":"identifier","text":"ViewAnnotationAnchor"}],"type":"topic","abstract":[{"type":"text","text":"Enum describing how to place view annotation relatively to geometry."}],"title":"ViewAnnotationAnchor","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ViewAnnotationAnchor","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/viewannotationanchor"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationPositionDescriptor\/title","op":"replace","value":"MBMViewAnnotationPositionDescriptor"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationPositionDescriptor\/fragments","value":[{"text":"MBMViewAnnotationPositionDescriptor","kind":"identifier"}]},{"value":[{"text":"MBMViewAnnotationPositionDescriptor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationPositionDescriptor\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchorConfig\/title","op":"replace","value":"MBMViewAnnotationAnchorConfig"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchorConfig\/fragments","value":[{"text":"MBMViewAnnotationAnchorConfig","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBMViewAnnotationAnchorConfig"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchorConfig\/navigatorTitle"},{"op":"replace","value":"MBMViewAnnotationAnchor","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchor\/title"},{"op":"replace","value":[{"text":"MBMViewAnnotationAnchor","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchor\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchor\/navigatorTitle","value":[{"kind":"identifier","text":"MBMViewAnnotationAnchor"}]}]}]}