{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/customlayerrenderparameters\/elevationdata"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/customlayerrenderparameters\/elevationdata"]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"elevationData"},{"kind":"text","text":": (any "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ElevationData","text":"ElevationData","preciseIdentifier":"c:objc(pl)MBMElevationData","kind":"typeIdentifier"},{"text":")? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"If terrain is enabled, provides value to elevation data from render thread. Empty if terrain is not enabled."}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters\/elevationData","interfaceLanguage":"swift"},"metadata":{"externalID":"c:objc(cs)MBMCustomLayerRenderParameters(py)elevationData","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"elevationData","kind":"identifier"},{"kind":"text","text":": (any "},{"text":"ElevationData","preciseIdentifier":"c:objc(pl)MBMElevationData","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"navigatorTitle":[{"text":"elevationData","kind":"identifier"}],"modules":[{"name":"MapboxMaps"}],"title":"elevationData","roleHeading":"Instance Property","role":"symbol"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerRenderParameters/elevationData":{"role":"symbol","abstract":[{"text":"If terrain is enabled, provides value to elevation data from render thread. Empty if terrain is not enabled.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"elevationData","kind":"identifier"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:objc(pl)MBMElevationData","text":"ElevationData","kind":"typeIdentifier"},{"kind":"text","text":")?"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters\/elevationData","navigatorTitle":[{"text":"elevationData","kind":"identifier"}],"title":"elevationData","url":"\/documentation\/mapboxmaps\/customlayerrenderparameters\/elevationdata","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layers":{"kind":"article","url":"\/documentation\/mapboxmaps\/layers","title":"Layers","abstract":[],"type":"topic","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ElevationData":{"navigatorTitle":[{"text":"ElevationData","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ElevationData","kind":"identifier"}],"kind":"symbol","title":"ElevationData","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ElevationData","url":"\/documentation\/mapboxmaps\/elevationdata","role":"symbol","abstract":[{"type":"text","text":"Interface that provides access to elevation data."}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerRenderParameters":{"navigatorTitle":[{"text":"CustomLayerRenderParameters","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CustomLayerRenderParameters","kind":"identifier"}],"kind":"symbol","title":"CustomLayerRenderParameters","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters","url":"\/documentation\/mapboxmaps\/customlayerrenderparameters","role":"symbol","abstract":[{"type":"text","text":"Parameters that define the current camera position for a "},{"type":"codeVoice","code":"CustomLayerHost::render()"},{"type":"text","text":" function."}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","url":"\/documentation\/overview","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"role":"collection","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"elevationData","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","value":[{"text":"elevationData","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)MBMElevationData","text":"id<MBMElevationData>"},{"text":" ","kind":"text"},{"text":"elevationData","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters~1elevationData\/title","op":"replace","value":"elevationData"},{"value":[{"text":"elevationData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters~1elevationData\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ElevationData\/title","value":"MBMElevationData"},{"value":[{"text":"MBMElevationData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ElevationData\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ElevationData\/navigatorTitle","value":[{"text":"MBMElevationData","kind":"identifier"}]},{"op":"replace","value":"MBMCustomLayerRenderParameters","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMCustomLayerRenderParameters"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/navigatorTitle","value":[{"text":"MBMCustomLayerRenderParameters","kind":"identifier"}]}]}]}