{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"initWithSourceId:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"sourceId"},{"text":" ","kind":"text"},{"text":"type:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedType","text":"MBMSourceDataLoadedType","preciseIdentifier":"c:@E@MBMSourceDataLoadedType"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"type"},{"kind":"text","text":" "},{"kind":"identifier","text":"loaded:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"loaded"},{"kind":"text","text":" "},{"kind":"identifier","text":"tileId:"},{"text":"(","kind":"text"},{"text":"MBMCanonicalTileID","preciseIdentifier":"c:objc(cs)MBMCanonicalTileID","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"tileId"},{"kind":"text","text":" "},{"text":"dataId:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"text":"dataId","kind":"internalParam"},{"kind":"text","text":" "},{"text":"timeInterval:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/EventTimeInterval","text":"MBMEventTimeInterval","preciseIdentifier":"c:objc(cs)MBMEventTimeInterval","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"timeInterval","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoaded"]]},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMSourceDataLoaded\/initWithSourceId:type:loaded:tileId:dataId:timeInterval:","interfaceLanguage":"occ"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/mbmsourcedataloaded\/initwithsourceid:type:loaded:tileid:dataid:timeinterval:"]}],"metadata":{"externalID":"c:objc(cs)MBMSourceDataLoaded(im)initWithSourceId:type:loaded:tileId:dataId:timeInterval:","roleHeading":"Instance Method","modules":[{"name":"MapboxMaps"}],"title":"initWithSourceId:type:loaded:tileId:dataId:timeInterval:","symbolKind":"method","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithSourceId:type:loaded:tileId:dataId:timeInterval:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithSourceId:type:loaded:tileId:dataId:timeInterval:","kind":"identifier"}]},"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","role":"collection","kind":"article","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMSourceDataLoaded/initWithSourceId:type:loaded:tileId:dataId:timeInterval:":{"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMSourceDataLoaded\/initWithSourceId:type:loaded:tileId:dataId:timeInterval:","navigatorTitle":[{"text":"initWithSourceId:type:loaded:tileId:dataId:timeInterval:","kind":"identifier"}],"title":"initWithSourceId:type:loaded:tileId:dataId:timeInterval:","kind":"symbol","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithSourceId:type:loaded:tileId:dataId:timeInterval:","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxmaps\/mbmsourcedataloaded\/initwithsourceid:type:loaded:tileid:dataid:timeinterval:"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CanonicalTileID":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CanonicalTileID","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID","title":"CanonicalTileID","abstract":[{"type":"text","text":"Represents a tile coordinate."}],"url":"\/documentation\/mapboxmaps\/canonicaltileid","navigatorTitle":[{"kind":"identifier","text":"CanonicalTileID"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/EventTimeInterval":{"kind":"symbol","role":"symbol","title":"EventTimeInterval","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/EventTimeInterval","abstract":[{"text":"The time interval of an event. The ","type":"text"},{"type":"codeVoice","code":"begin"},{"type":"text","text":" property represents the time"},{"type":"text","text":" "},{"type":"text","text":"origin of an event, and the "},{"type":"codeVoice","code":"end"},{"text":" property represents the time when the particular","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"operation is complete. The timestamps are sampled at the origin and do not include"},{"type":"text","text":" "},{"type":"text","text":"the time required to dispatch an event."}],"type":"topic","url":"\/documentation\/mapboxmaps\/eventtimeinterval","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EventTimeInterval"}],"navigatorTitle":[{"text":"EventTimeInterval","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"type":"topic","role":"collection","url":"\/documentation\/mapboxmaps","title":"MapboxMaps","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceDataLoaded":{"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"SourceDataLoaded"},{"type":"text","text":" event is emitted when source data is loaded."}],"type":"topic","kind":"symbol","title":"SourceDataLoaded","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SourceDataLoaded"}],"navigatorTitle":[{"kind":"identifier","text":"SourceDataLoaded"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoaded","role":"symbol","url":"\/documentation\/mapboxmaps\/sourcedataloaded"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceDataLoadedType":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SourceDataLoadedType"}],"url":"\/documentation\/mapboxmaps\/sourcedataloadedtype","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedType","title":"SourceDataLoadedType","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The enumeration defines the type of loaded source data."}],"navigatorTitle":[{"kind":"identifier","text":"SourceDataLoadedType"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","abstract":[{"type":"text","text":"The simplified diagram of the events emitted by the map is displayed below."}],"type":"topic","title":"Map events","url":"\/documentation\/mapboxmaps\/events","role":"collectionGroup"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MBMCanonicalTileID","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/fragments","value":[{"text":"MBMCanonicalTileID","kind":"identifier"}]},{"op":"replace","value":[{"text":"MBMCanonicalTileID","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/navigatorTitle"},{"value":"MBMEventTimeInterval","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1EventTimeInterval\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1EventTimeInterval\/fragments","value":[{"kind":"identifier","text":"MBMEventTimeInterval"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1EventTimeInterval\/navigatorTitle","value":[{"kind":"identifier","text":"MBMEventTimeInterval"}]},{"value":"MBMSourceDataLoaded","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoaded\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MBMSourceDataLoaded"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoaded\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBMSourceDataLoaded"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoaded\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedType\/title","value":"MBMSourceDataLoadedType"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedType\/fragments","value":[{"text":"MBMSourceDataLoadedType","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MBMSourceDataLoadedType"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedType\/navigatorTitle","op":"replace"}]}]}