{"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedType\/style","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedType"]]},"variants":[{"paths":["\/documentation\/mapboxmaps\/styledataloadedtype\/style"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/styledataloadedtype\/style"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"The style document is loaded and parsed. Style properties can be read and"},{"type":"text","text":" "},{"type":"text","text":"modified, and style layers and sources can be added or removed before rendering is started."}],"sections":[],"metadata":{"title":"StyleDataLoadedType.style","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"style"}],"roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"MBMStyleDataLoadedTypeStyle"}],"externalID":"c:@E@MBMStyleDataLoadedType@MBMStyleDataLoadedTypeStyle","symbolKind":"case","role":"symbol","modules":[{"name":"MapboxMaps"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"style"}],"languages":["swift"]}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","url":"\/documentation\/overview","kind":"article","type":"topic","role":"collection","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleDataLoadedType/style":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedType\/style","url":"\/documentation\/mapboxmaps\/styledataloadedtype\/style","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"style"}],"navigatorTitle":[{"kind":"identifier","text":"MBMStyleDataLoadedTypeStyle"}],"kind":"symbol","title":"StyleDataLoadedType.style","abstract":[{"type":"text","text":"The style document is loaded and parsed. Style properties can be read and"},{"type":"text","text":" "},{"type":"text","text":"modified, and style layers and sources can be added or removed before rendering is started."}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleDataLoadedType":{"title":"StyleDataLoadedType","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedType","type":"topic","url":"\/documentation\/mapboxmaps\/styledataloadedtype","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"StyleDataLoadedType"}],"abstract":[{"text":"The enumeration defines the type of loaded style data.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"StyleDataLoadedType"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","title":"Map events","type":"topic","role":"collectionGroup","abstract":[{"text":"The simplified diagram of the events emitted by the map is displayed below.","type":"text"}],"url":"\/documentation\/mapboxmaps\/events"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","url":"\/documentation\/mapboxmaps","title":"MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"MBMStyleDataLoadedTypeStyle","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"MBMStyleDataLoadedTypeStyle"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"MBMStyleDataLoadedTypeStyle"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MBMStyleDataLoadedTypeStyle","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedType~1style\/title"},{"value":[{"kind":"identifier","text":"MBMStyleDataLoadedTypeStyle"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedType~1style\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedType\/title","value":"MBMStyleDataLoadedType"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedType\/fragments","value":[{"kind":"identifier","text":"MBMStyleDataLoadedType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedType\/navigatorTitle","value":[{"text":"MBMStyleDataLoadedType","kind":"identifier"}]}]}]}