{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXGeometry\/geometry"},"kind":"symbol","metadata":{"modules":[{"name":"MapboxCommon"}],"title":"geometry","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"geometry","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sv","text":"UnsafeMutableRawPointer","kind":"typeIdentifier"}],"symbolKind":"property","role":"symbol","externalID":"c:objc(cs)MBXGeometry(py)geometry","roleHeading":"Instance Property","navigatorTitle":[{"text":"geometry","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"geometry"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sv","kind":"typeIdentifier","text":"UnsafeMutableRawPointer"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/mbxgeometry\/geometry"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/mbxgeometry\/geometry"]}],"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Geometry":{"title":"Geometry","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Geometry"}],"url":"\/documentation\/mapboxcommon\/geometry","abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Geometry"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXGeometry/geometry":{"title":"geometry","url":"\/documentation\/mapboxcommon\/mbxgeometry\/geometry","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXGeometry\/geometry","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"geometry","kind":"identifier"},{"kind":"text","text":": "},{"text":"UnsafeMutableRawPointer","preciseIdentifier":"s:Sv","kind":"typeIdentifier"}],"type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"geometry"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"title":"MapboxCommon","role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","abstract":[],"url":"\/documentation\/mapboxcommon"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"geometry"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"geometry","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"assign","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":" * ","kind":"text"},{"text":"geometry","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"MBXGeometry","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry\/fragments","op":"replace","value":[{"text":"MBXGeometry","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MBXGeometry~1geometry\/title","value":"geometry"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MBXGeometry~1geometry\/fragments","op":"replace","value":[{"kind":"identifier","text":"geometry"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}