{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeStylePack","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forStyleURI","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"styleURI","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"styleURI","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The URI of the style package’s associated style"}]}]}],"kind":"parameters"},{"content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"Removes a style package from the existing packages list. The actual resources"},{"type":"text","text":" "},{"type":"text","text":"eviction from the Tile Store might be deferred (see the Tile Store disk quota API)."}],"type":"paragraph"},{"inlineContent":[{"text":"All pending loading operations for the style package with the given id will","type":"text"},{"text":" ","type":"text"},{"text":"fail with ","type":"text"},{"type":"codeVoice","code":"Canceled"},{"text":" error.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/offlinemanager\/removestylepack(forstyleuri:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/offlinemanager\/removestylepack(forstyleuri:)"]}],"sections":[],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineManager\/removeStylePack(forStyleURI:)","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineManager"]]},"metadata":{"navigatorTitle":[{"text":"removeStylePackForStyleURI:","kind":"identifier"}],"roleHeading":"Instance Method","externalID":"c:objc(cs)MBMOfflineManager(im)removeStylePackForStyleURI:","title":"removeStylePack(forStyleURI:)","modules":[{"name":"MapboxMaps"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeStylePack","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forStyleURI","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"symbolKind":"method"},"abstract":[{"text":"Removes a style package.","type":"text"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineManager":{"navigatorTitle":[{"text":"OfflineManager","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OfflineManager","kind":"identifier"}],"type":"topic","title":"OfflineManager","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineManager","role":"symbol","url":"\/documentation\/mapboxmaps\/offlinemanager","abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"offline manager"},{"type":"text","text":" manages downloads and storage for style packages and also produces tileset descriptors for the "},{"type":"codeVoice","code":"tile store"},{"type":"text","text":"."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Offline":{"role":"collectionGroup","title":"Offline Support","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","url":"\/documentation\/mapboxmaps\/offline","abstract":[],"kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"type":"topic","url":"\/documentation\/mapboxmaps","role":"collection","kind":"symbol","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","url":"\/documentation\/overview","role":"collection","abstract":[],"kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMaps":{"type":"topic","title":"Core Maps API","abstract":[{"type":"text","text":"Maps rendering SDK also known as GL-Native"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","kind":"article","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/coremaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineManager/removeStylePack(forStyleURI:)":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineManager\/removeStylePack(forStyleURI:)","abstract":[{"type":"text","text":"Removes a style package."}],"role":"symbol","title":"removeStylePack(forStyleURI:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"removeStylePackForStyleURI:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeStylePack"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forStyleURI"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"url":"\/documentation\/mapboxmaps\/offlinemanager\/removestylepack(forstyleuri:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"removeStylePackForStyleURI:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"removeStylePackForStyleURI:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"removeStylePackForStyleURI:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"styleURI","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"name":"styleURI","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The URI of the style package’s associated style"}]}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"MBMOfflineManager","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineManager\/title"},{"value":[{"kind":"identifier","text":"MBMOfflineManager"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineManager\/fragments"},{"value":[{"text":"MBMOfflineManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineManager\/navigatorTitle"},{"value":"removeStylePackForStyleURI:","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineManager~1removeStylePack(forStyleURI:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeStylePackForStyleURI:"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineManager~1removeStylePack(forStyleURI:)\/fragments"}]}]}