{"metadata":{"symbolKind":"method","modules":[{"name":"MapboxMaps"}],"externalID":"s:10MapboxMaps10ProjectionC15projectedMeters3forSo012MBMProjectedE0CSo22CLLocationCoordinate2DV_tFZ","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"projectedMeters","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMProjectedMeters","text":"ProjectedMeters","kind":"typeIdentifier"}],"title":"projectedMeters(for:)","roleHeading":"Type Method","role":"symbol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"variants":[{"paths":["\/documentation\/mapboxmaps\/projection\/projectedmeters(for:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Projection\/projectedMeters(for:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Camera-and-coordinates"],["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Camera-and-coordinates"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"projectedMeters","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"coordinate","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ProjectedMeters","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ProjectedMeters","preciseIdentifier":"c:objc(cs)MBMProjectedMeters"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"coordinate","content":[{"inlineContent":[{"text":"Coordinate at which to calculate the projected","type":"text"},{"text":" ","type":"text"},{"text":"meters","type":"text"}],"type":"paragraph"}]}]},{"content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"inlineContent":[{"type":"text","text":"Spherical Mercator ProjectedMeters coordinates"}],"type":"paragraph"}],"kind":"content"}],"seeAlsoSections":[{"generated":true,"title":"Projection","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ProjectedMeters"],"anchor":"Projection"}],"abstract":[{"text":"Calculate Spherical Mercator ProjectedMeters coordinates.","type":"text"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ProjectedMeters":{"abstract":[{"type":"text","text":"ProjectedMeters is a coordinate in a specific"},{"type":"text","text":" "},{"type":"reference","identifier":"http:\/\/docs.openlayers.org\/library\/spherical_mercator.html","isActive":true},{"type":"text","text":" projection."}],"navigatorTitle":[{"text":"ProjectedMeters","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/projectedmeters","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ProjectedMeters","title":"ProjectedMeters","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ProjectedMeters","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"title":"MapboxMap","type":"topic","url":"\/documentation\/mapboxmaps\/mapboxmap-apis","kind":"article","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","url":"\/documentation\/overview","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","kind":"article","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Projection/projectedMeters(for:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"projectedMeters"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ProjectedMeters","preciseIdentifier":"c:objc(cs)MBMProjectedMeters"}],"role":"symbol","title":"projectedMeters(for:)","type":"topic","url":"\/documentation\/mapboxmaps\/projection\/projectedmeters(for:)","abstract":[{"type":"text","text":"Calculate Spherical Mercator ProjectedMeters coordinates."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Projection\/projectedMeters(for:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","role":"collection","title":"MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Camera-and-coordinates":{"type":"topic","title":"Camera and coordinates","url":"\/documentation\/mapboxmaps\/camera-and-coordinates","kind":"article","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Camera-and-coordinates"},"http://docs.openlayers.org/library/spherical_mercator.html":{"titleInlineContent":[{"text":"Spherical Mercator","type":"text"}],"identifier":"http:\/\/docs.openlayers.org\/library\/spherical_mercator.html","title":"Spherical Mercator","type":"link","url":"http:\/\/docs.openlayers.org\/library\/spherical_mercator.html"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ProjectedMeters\/title","value":"MBMProjectedMeters"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ProjectedMeters\/fragments","value":[{"text":"MBMProjectedMeters","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ProjectedMeters\/navigatorTitle","value":[{"text":"MBMProjectedMeters","kind":"identifier"}]}]}]}