{"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestErrorType\/connection","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMapsInternal","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestErrorType"]]},"variants":[{"paths":["\/documentation\/mapboxmaps\/requesterrortype\/connection"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/requesterrortype\/connection"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"The connection error has occured.","type":"text"}],"metadata":{"modules":[{"name":"MapboxMaps"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connection","kind":"identifier"}],"symbolKind":"case","navigatorTitle":[{"text":"MBMRequestErrorTypeConnection","kind":"identifier"}],"roleHeading":"Case","role":"symbol","externalID":"c:@E@MBMRequestErrorType@MBMRequestErrorTypeConnection","title":"RequestErrorType.connection"},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connection"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestErrorType":{"title":"RequestErrorType","type":"topic","kind":"symbol","abstract":[{"text":"The enumeration defines the error type that may occur during a resource request.","type":"text"}],"url":"\/documentation\/mapboxmaps\/requesterrortype","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestErrorType","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"RequestErrorType"}],"navigatorTitle":[{"kind":"identifier","text":"RequestErrorType"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","type":"topic","abstract":[],"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","kind":"symbol","type":"topic","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestErrorType/connection":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/requesterrortype\/connection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestErrorType\/connection","navigatorTitle":[{"kind":"identifier","text":"MBMRequestErrorTypeConnection"}],"type":"topic","abstract":[{"text":"The connection error has occured.","type":"text"}],"role":"symbol","title":"RequestErrorType.connection","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connection"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMapsInternal":{"role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMapsInternal","kind":"article","url":"\/documentation\/mapboxmaps\/coremapsinternal","title":"CoreMaps - Internal","type":"topic","abstract":[{"text":"Maps rendering SDK also known as GL-Native. These are for internal use only.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MBMRequestErrorTypeConnection"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MBMRequestErrorTypeConnection","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"MBMRequestErrorTypeConnection"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestErrorType\/title","value":"MBMRequestErrorType"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestErrorType\/fragments","value":[{"text":"MBMRequestErrorType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestErrorType\/navigatorTitle","value":[{"kind":"identifier","text":"MBMRequestErrorType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestErrorType~1connection\/title","value":"MBMRequestErrorTypeConnection"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestErrorType~1connection\/fragments","value":[{"text":"MBMRequestErrorTypeConnection","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}