---
manifests:
  - type: Package.swift
  - type: Package.resolved
  - type: Package.resolved
    path: Apps/Apps.xcworkspace/xcshareddata/swiftpm/Package.resolved
  - type: Package.resolved
    path: Mapbox/MapboxMaps.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  - type: Podspec
    path: MapboxMaps.podspec
  - type: JSON
    path: scripts/release/packager/versions.json
dependencies:
  - name: MapboxCoreMaps
    variations:
      Carthage: MapboxCoreMaps-dynamic
  - name: MapboxCommon
    variations:
      Carthage: MapboxCommon-ios
  - name: Turf
    variations:
      Carthage: turf-swift
  - name: MapboxMobileEvents
    variations:
      Carthage: mapbox-events-ios
