---
manifests:
  - type: Package.swift
  - type: Package.resolved
  - type: Package.resolved
    path: Apps/Apps.xcworkspace/xcshareddata/swiftpm/Package.resolved
  - type: Podspec
  - type: packager
dependencies:
  - name: MapboxCoreMaps
    variations:
      Package.swift: mapbox-core-maps-ios
  - name: MapboxCommon
    variations:
      Package.swift: mapbox-common-ios
  - name: Turf
    variations:
      Package.swift: turf-swift
  - name: MapboxMobileEvents
    variations:
      Package.swift: mapbox-events-ios
manifest_definitions:
  - name: packager
    type: SemanticVersion
    default_path: scripts/release/packager/versions.json
    command: jq -r ".$DEPSVALIDATOR_DEPENDENCY_NAME" "$DEPSVALIDATOR_MANIFEST_PATH"
