# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    - id: trailing-whitespace
      exclude: |
          (?x)^(
              .*LICENSE.md|
              .*\.swiftinterface
          )$
    - id: end-of-file-fixer
      exclude: ".*.list"
    - id: check-yaml
    - id: check-json
      exclude: .vscode/.*.json
    - id: check-byte-order-marker
    - id: check-merge-conflict
- repo: "https://github.com/realm/SwiftLint"
  rev: 0.58.2
  hooks:
    - id: swiftlint
      entry: swiftlint --fix --strict
- repo: https://github.com/psf/black
  rev: 25.1.0
  hooks:
    - id: black
      language_version: python3.12
- repo: https://github.com/gitleaks/gitleaks
  rev: v8.24.0
  hooks:
    - id: gitleaks
