---
allow_zero_lintable_files: true
included:
  - Sources
  - Tests
excluded:
  - "**/Generated"
disabled_rules:
  - comment_spacing
  - computed_accessors_order
  - force_try
  - identifier_name
  - line_length
  - shorthand_operator
  - todo
  - trailing_comma
  - type_name
custom_rules:
  trojan_source:
    regex: "[\u202A\u202B\u202D\u202E\u2066\u2067\u2068\u202C\u2069]"
    severity: error
    message: "Source should not contain characters that may be used in reordering attacks. See https://trojansource.codes/trojan-source.pdf"
