allow_zero_lintable_files: true
excluded:
  - Carthage
  - Pods
  - Sources/MapboxMaps/Style/Generated
  - Tests/MapboxMapsTests/Style/Generated
disabled_rules:
  - comment_spacing
  - computed_accessors_order
  - force_try
  - function_body_length
  - identifier_name
  - line_length
  - shorthand_operator
  - todo
  - trailing_comma
