allow_zero_lintable_files: true
excluded:
  - Carthage
  - Pods
  - MapboxMapsStyle/Generated
reporter: "xcode"
opt_in_rules:
  - explicit_top_level_acl
disabled_rules:
  - comment_spacing
  - computed_accessors_order
  - force_try
  - function_body_length
  - identifier_name
  - line_length
  - shorthand_operator
  - todo
