codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: false
ignore:
  - "Examples/"
  - "Mapbox/*Tests/"
  - "docs"
  - "DebugApp"
  - "StressTest/"
  - "PCVD/"
  - "Mapbox/Test*"
coverage:
  status:
    project:
      default:
        threshold: 2
      patch: off
comment:
  require_changes: true
  layout: "reach, diff, flags, files"
# Flags - does this help?
# flag_management:
#   default_rules:
#     carryforward: boolean?
#     ignore: [path]?
#     paths: [path]?
#     statuses: [ #note, statuses are an array
#       name_prefix: string (r"^[\w\-\.]+$")
#       type: OR("project", "patch", "changes")
#       target: OR("auto", percent)?
#       include_changes: OR("auto", percent)?
#       threshold: percent?
#       **normal status attributes
#     ]?

# Explicit list of flags
flags:
  MapboxMaps:  
    paths:
      - Mapbox/
     carryforward: false
  MapboxMapsTestsWithHost:
    paths:
      - Mapbox/
     carryforward: false
  MapboxMapsTestsWithHost:
    paths:
      - Mapbox/
     carryforward: false
