---
codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: false
ignore:
  - "Apps"
  - "PCVD"
  - "Tests"
coverage:
  status:
    project:
      default:
        threshold: 2%
    patch:
      default:
        target: 90%
comment:
  require_changes: true
  layout: "reach, diff, flags, files"

flag_management:
  default_rules: # the rules that will be followed for any flag added, generally
    statuses:
      - type: project
        threshold: 2%
      - type: patch
        target: 90%
    individual_flags: # exceptions to the default rules above, stated flag by flag
    - name: unit
    - name: integration
