ignore:
  - "Example/"
  - "Mapbox/*Tests/"
  - "docs"
  - "DebugApp"
  - "Mapbox/MapboxMapsStyle/Generated"
  - "StressTest/"
  - "PCVD/"
  - "TestHelpers"
coverage:
  status:
    project:
      default:
        threshold: 2
      patch: off