codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: false
ignore:
  - "Examples/"
  - "Mapbox/*Tests/"
  - "docs"
  - "DebugApp"
  - "StressTest/"
  - "PCVD/"
  - "Mapbox/Test*"
coverage:
  status:
    project:
      default:
        threshold: 2
      patch: off
comment:
  require_changes: true
  layout: "reach, diff, flags, files"
