{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestError"]]},"metadata":{"modules":[{"name":"MapboxCommon"}],"symbolKind":"init","navigatorTitle":[{"kind":"identifier","text":"initWithType:message:"}],"externalID":"c:objc(cs)MBXHttpRequestError(im)initWithType:message:","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"type"},{"text":": ","kind":"text"},{"text":"HttpRequestErrorType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBXHttpRequestErrorType"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"message"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"roleHeading":"Initializer","role":"symbol","title":"init(type:message:)"},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType","preciseIdentifier":"c:@E@MBXHttpRequestErrorType","text":"HttpRequestErrorType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"message"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/httprequesterror\/init(type:message:)"]},{"paths":["\/documentation\/mapboxcommon\/httprequesterror\/init(type:message:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestError\/init(type:message:)","interfaceLanguage":"swift"},"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article","role":"collection","title":"MapboxMaps Documentation","type":"topic","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"abstract":[],"title":"MapboxCommon","type":"topic","url":"\/documentation\/mapboxcommon","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestErrorType":{"kind":"symbol","url":"\/documentation\/mapboxcommon\/httprequesterrortype","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"HttpRequestErrorType","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType","title":"HttpRequestErrorType","navigatorTitle":[{"kind":"identifier","text":"HttpRequestErrorType"}],"abstract":[{"type":"text","text":"Enum which describes possible error types which could happen during HTTP request\/download calls."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestError":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestError","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"HttpRequestError"}],"url":"\/documentation\/mapboxcommon\/httprequesterror","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Record which contains detailed information about HTTP error happened during request\/download call."}],"navigatorTitle":[{"text":"HttpRequestError","kind":"identifier"}],"title":"HttpRequestError","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestError/init(type:message:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithType:message:"}],"abstract":[],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestError\/init(type:message:)","type":"topic","title":"init(type:message:)","url":"\/documentation\/mapboxcommon\/httprequesterror\/init(type:message:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBXHttpRequestErrorType","text":"HttpRequestErrorType"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"message"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"initWithType:message:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithType:message:"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithType:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType","preciseIdentifier":"c:@E@MBXHttpRequestErrorType","kind":"typeIdentifier","text":"MBXHttpRequestErrorType"},{"kind":"text","text":") "},{"text":"type","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"message:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"message","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestErrorType\/title","value":"MBXHttpRequestErrorType","op":"replace"},{"value":[{"kind":"identifier","text":"MBXHttpRequestErrorType"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestErrorType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestErrorType\/navigatorTitle","value":[{"text":"MBXHttpRequestErrorType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestError\/title","value":"MBXHttpRequestError","op":"replace"},{"op":"replace","value":[{"text":"MBXHttpRequestError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestError\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestError\/navigatorTitle","value":[{"text":"MBXHttpRequestError","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestError~1init(type:message:)\/title","value":"initWithType:message:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithType:message:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestError~1init(type:message:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}