{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionDownloadState"]]},"metadata":{"title":"Equatable Implementations","modules":[{"name":"MapboxMaps"}],"role":"collectionGroup","roleHeading":"API Collection"},"topicSections":[{"anchor":"Operators","generated":true,"title":"Operators","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionDownloadState\/!=(_:_:)"]}],"sections":[],"kind":"article","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionDownloadState\/Equatable-Implementations"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionDownloadState/!=(_:_:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionDownloadState\/!=(_:_:)","title":"!=(_:_:)","kind":"symbol","url":"\/documentation\/mapboxmaps\/offlineregiondownloadstate\/!=(_:_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","abstract":[{"text":"Maps rendering SDK also known as GL-Native","type":"text"}],"role":"collectionGroup","kind":"article","type":"topic","url":"\/documentation\/mapboxmaps\/coremaps","title":"Core Maps API"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Offline":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","abstract":[],"role":"collectionGroup","kind":"article","type":"topic","url":"\/documentation\/mapboxmaps\/offline","title":"Offline Support"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionDownloadState":{"navigatorTitle":[{"text":"OfflineRegionDownloadState","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionDownloadState","url":"\/documentation\/mapboxmaps\/offlineregiondownloadstate","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"OfflineRegionDownloadState","kind":"identifier"}],"title":"OfflineRegionDownloadState","type":"topic","abstract":[{"type":"text","text":"Describes the download state of a region."}],"deprecated":true,"role":"symbol","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"title":"MapboxMaps","role":"collection","url":"\/documentation\/mapboxmaps","type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"title":"MapboxMaps Documentation","role":"collection","url":"\/documentation\/overview","type":"topic","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionDownloadState\/title","value":"MBMOfflineRegionDownloadState","op":"replace"},{"value":[{"text":"MBMOfflineRegionDownloadState","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionDownloadState\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionDownloadState\/navigatorTitle","op":"replace","value":[{"text":"MBMOfflineRegionDownloadState","kind":"identifier"}]}]}]}