{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionDownloadState"]]},"metadata":{"title":"OfflineRegionDownloadState.inactive","roleHeading":"Case","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBMOfflineRegionDownloadStateInactive"}],"platforms":[],"externalID":"c:@E@MBMOfflineRegionDownloadState@MBMOfflineRegionDownloadStateInactive","symbolKind":"case","modules":[{"name":"MapboxMaps"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"inactive","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionDownloadState\/inactive"},"abstract":[{"type":"text","text":"Indicates downloading is inactive."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/offlineregiondownloadstate\/inactive"]},{"paths":["\/documentation\/mapboxmaps\/offlineregiondownloadstate\/inactive"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"inactive","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionDownloadState":{"navigatorTitle":[{"text":"OfflineRegionDownloadState","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionDownloadState","url":"\/documentation\/mapboxmaps\/offlineregiondownloadstate","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"OfflineRegionDownloadState","kind":"identifier"}],"title":"OfflineRegionDownloadState","type":"topic","abstract":[{"type":"text","text":"Describes the download state of a region."}],"deprecated":true,"role":"symbol","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"title":"MapboxMaps","role":"collection","url":"\/documentation\/mapboxmaps","type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionDownloadState/inactive":{"navigatorTitle":[{"kind":"identifier","text":"MBMOfflineRegionDownloadStateInactive"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"inactive","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/offlineregiondownloadstate\/inactive","kind":"symbol","role":"symbol","deprecated":true,"abstract":[{"text":"Indicates downloading is inactive.","type":"text"}],"type":"topic","title":"OfflineRegionDownloadState.inactive","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionDownloadState\/inactive"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Offline":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","abstract":[],"role":"collectionGroup","kind":"article","type":"topic","url":"\/documentation\/mapboxmaps\/offline","title":"Offline Support"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"title":"MapboxMaps Documentation","role":"collection","url":"\/documentation\/overview","type":"topic","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","abstract":[{"text":"Maps rendering SDK also known as GL-Native","type":"text"}],"role":"collectionGroup","kind":"article","type":"topic","url":"\/documentation\/mapboxmaps\/coremaps","title":"Core Maps API"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"MBMOfflineRegionDownloadStateInactive","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"text":"MBMOfflineRegionDownloadStateInactive","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"MBMOfflineRegionDownloadStateInactive","kind":"identifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionDownloadState\/title","value":"MBMOfflineRegionDownloadState"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionDownloadState\/fragments","value":[{"text":"MBMOfflineRegionDownloadState","kind":"identifier"}],"op":"replace"},{"value":[{"text":"MBMOfflineRegionDownloadState","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionDownloadState\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionDownloadState~1inactive\/title","value":"MBMOfflineRegionDownloadStateInactive","op":"replace"},{"value":[{"text":"MBMOfflineRegionDownloadStateInactive","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionDownloadState~1inactive\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}