{"metadata":{"title":"GlyphsRasterizationMode.ideographsRasterizedLocally","navigatorTitle":[{"text":"MBMGlyphsRasterizationModeIdeographsRasterizedLocally","kind":"identifier"}],"roleHeading":"Case","externalID":"c:@E@MBMGlyphsRasterizationMode@MBMGlyphsRasterizationModeIdeographsRasterizedLocally","role":"symbol","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"ideographsRasterizedLocally","kind":"identifier"}],"modules":[{"name":"MapboxMaps"}]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode\/ideographsRasterizedLocally","interfaceLanguage":"swift"},"abstract":[{"text":"Ideographs are rasterized locally, and they are not loaded from the server.","type":"text"}],"variants":[{"paths":["\/documentation\/mapboxmaps\/glyphsrasterizationmode\/ideographsrasterizedlocally"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/glyphsrasterizationmode\/ideographsrasterizedlocally"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ideographsRasterizedLocally"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-View","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode"],["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GlyphsRasterizationMode":{"type":"topic","title":"GlyphsRasterizationMode","url":"\/documentation\/mapboxmaps\/glyphsrasterizationmode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GlyphsRasterizationMode","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode","navigatorTitle":[{"kind":"identifier","text":"GlyphsRasterizationMode"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Describes glyphs rasterization modes.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"url":"\/documentation\/mapboxmaps\/mapboxmap-apis","abstract":[],"title":"MapboxMap","kind":"article","type":"topic","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GlyphsRasterizationMode/ideographsRasterizedLocally":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode\/ideographsRasterizedLocally","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ideographsRasterizedLocally"}],"navigatorTitle":[{"kind":"identifier","text":"MBMGlyphsRasterizationModeIdeographsRasterizedLocally"}],"title":"GlyphsRasterizationMode.ideographsRasterizedLocally","url":"\/documentation\/mapboxmaps\/glyphsrasterizationmode\/ideographsrasterizedlocally","role":"symbol","type":"topic","abstract":[{"text":"Ideographs are rasterized locally, and they are not loaded from the server.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","url":"\/documentation\/overview","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map-View":{"abstract":[],"title":"MapView","kind":"article","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-View","url":"\/documentation\/mapboxmaps\/map-view","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"title":"MapboxMaps","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MBMGlyphsRasterizationModeIdeographsRasterizedLocally"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MBMGlyphsRasterizationModeIdeographsRasterizedLocally"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"MBMGlyphsRasterizationModeIdeographsRasterizedLocally","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/title","value":"MBMGlyphsRasterizationMode"},{"value":[{"kind":"identifier","text":"MBMGlyphsRasterizationMode"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/fragments","op":"replace"},{"op":"replace","value":[{"text":"MBMGlyphsRasterizationMode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/navigatorTitle"},{"value":"MBMGlyphsRasterizationModeIdeographsRasterizedLocally","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode~1ideographsRasterizedLocally\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode~1ideographsRasterizedLocally\/fragments","value":[{"text":"MBMGlyphsRasterizationModeIdeographsRasterizedLocally","kind":"identifier"}]}]}]}