{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"httpResponse","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/httprequestorresponsetype\/httpresponse"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/httprequestorresponsetype\/httpresponse"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestOrResponseType\/httpResponse","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"symbolKind":"case","roleHeading":"Case","navigatorTitle":[{"text":"MBXHttpRequestOrResponseTypeHttpResponse","kind":"identifier"}],"externalID":"c:@E@MBXHttpRequestOrResponseType@MBXHttpRequestOrResponseTypeHttpResponse","modules":[{"name":"MapboxCommon"}],"role":"symbol","title":"HttpRequestOrResponseType.httpResponse","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"httpResponse"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestOrResponseType"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"title":"MapboxMaps Documentation","role":"collection","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"title":"MapboxCommon","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/mapboxcommon","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestOrResponseType/httpResponse":{"kind":"symbol","role":"symbol","url":"\/documentation\/mapboxcommon\/httprequestorresponsetype\/httpresponse","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestOrResponseType\/httpResponse","abstract":[],"title":"HttpRequestOrResponseType.httpResponse","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"httpResponse","kind":"identifier"}],"navigatorTitle":[{"text":"MBXHttpRequestOrResponseTypeHttpResponse","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestOrResponseType":{"title":"HttpRequestOrResponseType","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HttpRequestOrResponseType"}],"navigatorTitle":[{"text":"HttpRequestOrResponseType","kind":"identifier"}],"type":"topic","abstract":[],"url":"\/documentation\/mapboxcommon\/httprequestorresponsetype","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestOrResponseType","kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"MBXHttpRequestOrResponseTypeHttpResponse","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"text":"MBXHttpRequestOrResponseTypeHttpResponse","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"MBXHttpRequestOrResponseTypeHttpResponse","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestOrResponseType~1httpResponse\/title","value":"MBXHttpRequestOrResponseTypeHttpResponse","op":"replace"},{"value":[{"kind":"identifier","text":"MBXHttpRequestOrResponseTypeHttpResponse"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestOrResponseType~1httpResponse\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestOrResponseType\/title","value":"MBXHttpRequestOrResponseType","op":"replace"},{"value":[{"text":"MBXHttpRequestOrResponseType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestOrResponseType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestOrResponseType\/navigatorTitle","value":[{"kind":"identifier","text":"MBXHttpRequestOrResponseType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}