{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Style","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Adds an image to be used in the style."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/stylemanager\/addimage(_:id:sdf:stretchx:stretchy:content:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addImage","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"image","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":", ","kind":"text"},{"text":"id","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"sdf","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = false, ","kind":"text"},{"kind":"externalParam","text":"stretchX"},{"kind":"text","text":": ["},{"text":"ImageStretches","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageStretches","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMImageStretches"},{"kind":"text","text":"], "},{"text":"stretchY","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMImageStretches","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageStretches","text":"ImageStretches"},{"kind":"text","text":"], "},{"text":"content","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageContent","kind":"typeIdentifier","text":"ImageContent","preciseIdentifier":"c:objc(cs)MBMImageContent"},{"kind":"text","text":"? = nil) "},{"text":"throws","kind":"keyword"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"image","content":[{"type":"paragraph","inlineContent":[{"text":"Image to add.","type":"text"}]}]},{"name":"id","content":[{"inlineContent":[{"type":"text","text":"ID of the image."}],"type":"paragraph"}]},{"name":"sdf","content":[{"inlineContent":[{"type":"text","text":"Option to treat whether image is SDF(signed distance field) or not."},{"text":" ","type":"text"},{"type":"text","text":"Setting this to "},{"code":"true","type":"codeVoice"},{"text":" allows template images to be recolored. The","type":"text"},{"type":"text","text":" "},{"text":"default value is ","type":"text"},{"code":"false","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An array of two-element arrays, consisting of two numbers"},{"text":" ","type":"text"},{"text":"that represent the from position and the to position of areas","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"that can be stretched horizontally."}]}],"name":"stretchX"},{"name":"stretchY","content":[{"type":"paragraph","inlineContent":[{"text":"An array of two-element arrays, consisting of two numbers","type":"text"},{"type":"text","text":" "},{"type":"text","text":"that represent the from position and the to position of areas"},{"text":" ","type":"text"},{"text":"that can be stretched vertically.","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"An array of four numbers, with the first two specifying the","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"left, top corner, and the last two specifying the right, bottom"},{"type":"text","text":" "},{"text":"corner. If present, and if the icon uses icon-text-fit, the","type":"text"},{"type":"text","text":" "},{"text":"symbol’s text will be fit inside the content box.","type":"text"}],"type":"paragraph"}],"name":"content"}]},{"content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This API can also be used for"},{"text":" ","type":"text"},{"text":"updating an image. If the image id was already added, it gets replaced","type":"text"},{"type":"text","text":" "},{"text":"by the new image.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The image can be used in"},{"type":"text","text":" "},{"identifier":"https:\/\/www.mapbox.com\/mapbox-gl-js\/style-spec\/#layout-symbol-icon-image","isActive":true,"type":"reference"},{"type":"text","text":","},{"text":" ","type":"text"},{"isActive":true,"type":"reference","identifier":"https:\/\/www.mapbox.com\/mapbox-gl-js\/style-spec\/#paint-fill-fill-pattern"},{"type":"text","text":", and"},{"type":"text","text":" "},{"type":"reference","identifier":"https:\/\/www.mapbox.com\/mapbox-gl-js\/style-spec\/#paint-line-line-pattern","isActive":true},{"type":"text","text":"."}]},{"inlineContent":[{"type":"text","text":"For more information on how "},{"code":"stretchX","type":"codeVoice"},{"type":"text","text":" and "},{"type":"codeVoice","code":"stretchY"},{"type":"text","text":" parameters affect image stretching"},{"type":"text","text":" "},{"type":"text","text":"see "},{"isActive":true,"type":"reference","identifier":"https:\/\/docs.mapbox.com\/mapbox-gl-js\/example\/add-image-stretchable"},{"text":".","type":"text"}],"type":"paragraph"}],"kind":"content"}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addImage","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":", ","kind":"text"},{"text":"id","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sdf"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"stretchX"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMImageStretches","kind":"typeIdentifier","text":"ImageStretches"},{"text":"], ","kind":"text"},{"text":"stretchY","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMImageStretches","text":"ImageStretches","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"text":"content","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMImageContent","kind":"typeIdentifier","text":"ImageContent"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"}],"role":"symbol","modules":[{"name":"MapboxMaps"}],"symbolKind":"method","roleHeading":"Instance Method","title":"addImage(_:id:sdf:stretchX:stretchY:content:)","externalID":"s:10MapboxMaps12StyleManagerC8addImage_2id3sdf8stretchX0I1Y7contentySo7UIImageC_SSSbSaySo17MBMImageStretchesCGANSo0L7ContentCSgtKF"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addImage(_:id:sdf:stretchX:stretchY:content:)"},"kind":"symbol","sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ImageContent":{"abstract":[{"text":"Describes the image content, e.g. where text can be fit into an image.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ImageContent","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ImageContent"}],"role":"symbol","kind":"symbol","title":"ImageContent","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageContent","url":"\/documentation\/mapboxmaps\/imagecontent"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","role":"collection","abstract":[],"type":"topic","kind":"article"},"https://docs.mapbox.com/mapbox-gl-js/example/add-image-stretchable":{"identifier":"https:\/\/docs.mapbox.com\/mapbox-gl-js\/example\/add-image-stretchable","type":"link","title":"this Mapbox GL-JS example","titleInlineContent":[{"text":"this Mapbox GL-JS example","type":"text"}],"url":"https:\/\/docs.mapbox.com\/mapbox-gl-js\/example\/add-image-stretchable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ImageStretches":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ImageStretches","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageStretches","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageStretches"}],"abstract":[{"text":"Describes the image stretch areas.","type":"text"}],"role":"symbol","kind":"symbol","title":"ImageStretches","url":"\/documentation\/mapboxmaps\/imagestretches"},"https://www.mapbox.com/mapbox-gl-js/style-spec/#layout-symbol-icon-image":{"identifier":"https:\/\/www.mapbox.com\/mapbox-gl-js\/style-spec\/#layout-symbol-icon-image","type":"link","title":"icon-image","titleInlineContent":[{"code":"icon-image","type":"codeVoice"}],"url":"https:\/\/www.mapbox.com\/mapbox-gl-js\/style-spec\/#layout-symbol-icon-image"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Snapshotter":{"navigatorTitle":[{"text":"Snapshotter","kind":"identifier"}],"abstract":[{"type":"text","text":"A utility class for capturing styled map snapshots."}],"type":"topic","url":"\/documentation\/mapboxmaps\/snapshotter","title":"Snapshotter","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Snapshotter"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter","kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/addImage(_:id:sdf:stretchX:stretchY:content:)":{"type":"topic","url":"\/documentation\/mapboxmaps\/stylemanager\/addimage(_:id:sdf:stretchx:stretchy:content:)","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addImage(_:id:sdf:stretchX:stretchY:content:)","title":"addImage(_:id:sdf:stretchX:stretchY:content:)","abstract":[{"type":"text","text":"Adds an image to be used in the style."}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"addImage","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":", "},{"text":"id","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"sdf","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"stretchX","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMImageStretches","text":"ImageStretches","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"text":"stretchY","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"ImageStretches","preciseIdentifier":"c:objc(cs)MBMImageStretches","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"content"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MBMImageContent","text":"ImageContent","kind":"typeIdentifier"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager":{"navigatorTitle":[{"kind":"identifier","text":"StyleManager"}],"abstract":[{"type":"text","text":"Style manager is a base class for "},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","isActive":true},{"text":" and ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter","isActive":true},{"text":" that provides provides methods to manipulate Map Style at runtime.","type":"text"}],"type":"topic","url":"\/documentation\/mapboxmaps\/stylemanager","title":"StyleManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StyleManager"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager","kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap":{"kind":"symbol","title":"MapboxMap","role":"symbol","navigatorTitle":[{"text":"MapboxMap","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapboxMap"}],"abstract":[{"text":"Provides access to the map model, including the camera, style, observable map events,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"and querying rendered features."}],"url":"\/documentation\/mapboxmaps\/mapboxmap"},"https://www.mapbox.com/mapbox-gl-js/style-spec/#paint-line-line-pattern":{"identifier":"https:\/\/www.mapbox.com\/mapbox-gl-js\/style-spec\/#paint-line-line-pattern","type":"link","title":"line-pattern","titleInlineContent":[{"code":"line-pattern","type":"codeVoice"}],"url":"https:\/\/www.mapbox.com\/mapbox-gl-js\/style-spec\/#paint-line-line-pattern"},"https://www.mapbox.com/mapbox-gl-js/style-spec/#paint-fill-fill-pattern":{"identifier":"https:\/\/www.mapbox.com\/mapbox-gl-js\/style-spec\/#paint-fill-fill-pattern","type":"link","title":"fill-pattern","titleInlineContent":[{"code":"fill-pattern","type":"codeVoice"}],"url":"https:\/\/www.mapbox.com\/mapbox-gl-js\/style-spec\/#paint-fill-fill-pattern"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Style":{"url":"\/documentation\/mapboxmaps\/style","title":"Style","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Style","kind":"article","type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"MBMImageContent","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ImageContent\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ImageContent\/fragments","value":[{"kind":"identifier","text":"MBMImageContent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ImageContent\/navigatorTitle","value":[{"text":"MBMImageContent","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ImageStretches\/title","value":"MBMImageStretches"},{"value":[{"text":"MBMImageStretches","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ImageStretches\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ImageStretches\/navigatorTitle","value":[{"kind":"identifier","text":"MBMImageStretches"}]}]}]}