{"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/httprequesterrortype\/init(rawvalue:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType\/init(rawValue:)"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"externalID":"s:So23MBXHttpRequestErrorTypeV8rawValueABSgSi_tcfc","title":"init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"symbolKind":"init","role":"symbol","roleHeading":"Initializer","modules":[{"name":"MapboxCommon"}]},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType"]]},"kind":"symbol","references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","title":"MapboxCommon","kind":"symbol","abstract":[],"url":"\/documentation\/mapboxcommon","role":"collection","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestErrorType":{"type":"topic","role":"symbol","title":"HttpRequestErrorType","url":"\/documentation\/mapboxcommon\/httprequesterrortype","abstract":[{"type":"text","text":"Enum which describes possible error types which could happen during HTTP request\/download calls."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HttpRequestErrorType"}],"navigatorTitle":[{"kind":"identifier","text":"HttpRequestErrorType"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestErrorType/init(rawValue:)":{"fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType\/init(rawValue:)","type":"topic","url":"\/documentation\/mapboxcommon\/httprequesterrortype\/init(rawvalue:)","role":"symbol","abstract":[],"title":"init(rawValue:)","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","abstract":[],"kind":"article","url":"\/documentation\/overview","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MBXHttpRequestErrorType","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestErrorType\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestErrorType\/fragments","value":[{"kind":"identifier","text":"MBXHttpRequestErrorType"}],"op":"replace"},{"value":[{"text":"MBXHttpRequestErrorType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestErrorType\/navigatorTitle"}]}]}