{"metadata":{"symbolKind":"property","title":"networkRestriction","modules":[{"name":"MapboxCommon"}],"externalID":"c:objc(cs)MBXHttpRequest(py)networkRestriction","roleHeading":"Instance Property","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"networkRestriction","kind":"identifier"},{"kind":"text","text":": "},{"text":"NetworkRestriction","preciseIdentifier":"c:@E@MBXNetworkRestriction","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"networkRestriction","kind":"identifier"}]},"abstract":[{"type":"text","text":"Restrict the request to the specified network types. If none of the specified network types is available, the"},{"type":"text","text":" "},{"type":"text","text":"download fails with a connection error."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"networkRestriction","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NetworkRestriction","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NetworkRestriction","preciseIdentifier":"c:@E@MBXNetworkRestriction"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Default is allowed to all network types","type":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/httprequest\/networkrestriction"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/httprequest\/networkrestriction"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest\/networkRestriction"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/NetworkRestriction":{"navigatorTitle":[{"text":"NetworkRestriction","kind":"identifier"}],"abstract":[{"type":"text","text":"Classify network types based on cost."}],"role":"symbol","title":"NetworkRestriction","url":"\/documentation\/mapboxcommon\/networkrestriction","type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NetworkRestriction","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NetworkRestriction"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequest/networkRestriction":{"title":"networkRestriction","url":"\/documentation\/mapboxcommon\/httprequest\/networkrestriction","kind":"symbol","abstract":[{"text":"Restrict the request to the specified network types. If none of the specified network types is available, the","type":"text"},{"type":"text","text":" "},{"type":"text","text":"download fails with a connection error."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"networkRestriction","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@MBXNetworkRestriction","text":"NetworkRestriction","kind":"typeIdentifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"networkRestriction"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest\/networkRestriction"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"role":"collection","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","url":"\/documentation\/mapboxcommon","kind":"symbol","type":"topic","title":"MapboxCommon"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","url":"\/documentation\/overview","role":"collection","kind":"article","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequest":{"title":"HttpRequest","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"HttpRequest","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/mapboxcommon\/httprequest","navigatorTitle":[{"kind":"identifier","text":"HttpRequest"}],"abstract":[{"type":"text","text":"HttpRequest holds basic information for construction of an HTTP request"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"networkRestriction","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"networkRestriction","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"MBXNetworkRestriction","preciseIdentifier":"c:@E@MBXNetworkRestriction","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NetworkRestriction"},{"kind":"text","text":" "},{"text":"networkRestriction","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"MBXNetworkRestriction","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1NetworkRestriction\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1NetworkRestriction\/fragments","value":[{"text":"MBXNetworkRestriction","kind":"identifier"}],"op":"replace"},{"value":[{"text":"MBXNetworkRestriction","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1NetworkRestriction\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest~1networkRestriction\/title","value":"networkRestriction","op":"replace"},{"value":[{"text":"networkRestriction","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest~1networkRestriction\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest\/title","value":"MBXHttpRequest","op":"replace"},{"value":[{"kind":"identifier","text":"MBXHttpRequest"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest\/fragments"},{"op":"replace","value":[{"text":"MBXHttpRequest","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest\/navigatorTitle"}]}]}