{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@discardableResult","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onEvery","kind":"identifier"},{"text":"<","kind":"text"},{"text":"Payload","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"event","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MapEventType","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapEventType","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps12MapEventTypeV"},{"text":"<","kind":"text"},{"text":"Payload","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"text":"handler","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"keyword"},{"text":" (","kind":"text"},{"text":"Payload","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":") -> any ","kind":"text"},{"text":"Cancelable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Cancelable","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MBXCancelable"}],"platforms":["iOS"]}]},{"parameters":[{"name":"event","content":[{"type":"paragraph","inlineContent":[{"text":"The event type to listen to.","type":"text"}]}]},{"name":"handler","content":[{"inlineContent":[{"text":"The closure to execute when the event occurs.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"A "},{"type":"codeVoice","code":"Cancelable"},{"type":"text","text":" object that you can use to stop listening for"},{"type":"text","text":" "},{"type":"text","text":"events. This is especially important if you have a retain cycle in"},{"type":"text","text":" "},{"type":"text","text":"the handler."}],"type":"paragraph"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/snapshotter\/onevery(event:handler:)"]}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use snapshotter.on<eventType>.observe instead.","type":"text"}]}],"metadata":{"roleHeading":"Instance Method","role":"symbol","platforms":[],"externalID":"s:10MapboxMaps11SnapshotterC7onEvery5event7handlerSo13MBXCancelable_pAA12MapEventTypeVyxG_yxctlF","extendedModule":"MapboxMaps","symbolKind":"method","modules":[{"name":"MapboxMaps"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onEvery"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"Payload"},{"kind":"text","text":">("},{"kind":"externalParam","text":"event"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps12MapEventTypeV","text":"MapEventType"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Payload"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"handler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Payload"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":") -> any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MBXCancelable","text":"Cancelable"}],"title":"onEvery(event:handler:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter\/onEvery(event:handler:)"},"sections":[],"abstract":[{"type":"text","text":"Listen to multiple occurrences of a Map event."}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapEventType":{"url":"\/documentation\/mapboxmaps\/mapeventtype","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapEventType"}],"title":"MapEventType","abstract":[{"type":"text","text":"A shim that makes it possible to subscribe to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap"},{"type":"text","text":" and "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter"},{"type":"text","text":" events via the old "},{"code":"onNext","type":"codeVoice"},{"type":"text","text":" and  "},{"code":"onEvery","type":"codeVoice"},{"type":"text","text":" methods."},{"type":"text","text":" "},{"type":"text","text":"It is here to simplify migration from v10 to v11, but will be removed in v12."}],"deprecated":true,"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapEventType","navigatorTitle":[{"kind":"identifier","text":"MapEventType"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Snapshotter":{"title":"Snapshotter","role":"symbol","navigatorTitle":[{"text":"Snapshotter","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter","kind":"symbol","url":"\/documentation\/mapboxmaps\/snapshotter","type":"topic","abstract":[{"text":"A utility class for capturing styled map snapshots.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Snapshotter","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Snapshotter/onEvery(event:handler:)":{"kind":"symbol","title":"onEvery(event:handler:)","url":"\/documentation\/mapboxmaps\/snapshotter\/onevery(event:handler:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter\/onEvery(event:handler:)","role":"symbol","type":"topic","deprecated":true,"abstract":[{"type":"text","text":"Listen to multiple occurrences of a Map event."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onEvery"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"Payload"},{"kind":"text","text":">("},{"kind":"externalParam","text":"event"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MapEventType","preciseIdentifier":"s:10MapboxMaps12MapEventTypeV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Payload"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"handler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Payload"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> any "},{"kind":"typeIdentifier","text":"Cancelable","preciseIdentifier":"c:objc(pl)MBXCancelable"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Snapshotter-APIs":{"type":"topic","title":"Snapshotter","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter-APIs","kind":"article","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/snapshotter-apis"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Cancelable":{"abstract":[{"text":"Allows to cancel the associated asynchronous operation","type":"text"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Cancelable","kind":"identifier"}],"kind":"symbol","title":"Cancelable","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Cancelable","navigatorTitle":[{"text":"Cancelable","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/cancelable"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"kind":"article","role":"collection","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","type":"topic","title":"MapboxMap","url":"\/documentation\/mapboxmaps\/mapboxmap","abstract":[{"text":"Provides access to the map model, including the camera, style, observable map events,","type":"text"},{"text":" ","type":"text"},{"text":"and querying rendered features.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapboxMap","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"MapboxMap","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/title","value":"MBXCancelable","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/fragments","value":[{"text":"MBXCancelable","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/navigatorTitle","value":[{"kind":"identifier","text":"MBXCancelable"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}