{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestErrorType\/Equatable-Implementations"},"schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"title":"Operators","anchor":"Operators","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestErrorType\/!=(_:_:)"],"generated":true}],"sections":[],"metadata":{"roleHeading":"API Collection","title":"Equatable Implementations","modules":[{"name":"MapboxMaps"}],"role":"collectionGroup"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMapsInternal","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestErrorType"]]},"kind":"article","references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMapsInternal":{"type":"topic","abstract":[{"type":"text","text":"Maps rendering SDK also known as GL-Native. These are for internal use only."}],"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMapsInternal","title":"CoreMaps - Internal","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/coremapsinternal"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","url":"\/documentation\/mapboxmaps","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestErrorType/!=(_:_:)":{"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"type":"topic","abstract":[],"url":"\/documentation\/mapboxmaps\/requesterrortype\/!=(_:_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestErrorType\/!=(_:_:)","role":"symbol","title":"!=(_:_:)"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"title":"MapboxMaps Documentation","type":"topic","kind":"article","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestErrorType":{"url":"\/documentation\/mapboxmaps\/requesterrortype","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestErrorType","abstract":[{"text":"The enumeration defines the error type that may occur during a resource request.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"RequestErrorType"}],"navigatorTitle":[{"kind":"identifier","text":"RequestErrorType"}],"title":"RequestErrorType","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestErrorType\/title","value":"MBMRequestErrorType"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestErrorType\/fragments","value":[{"text":"MBMRequestErrorType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestErrorType\/navigatorTitle","value":[{"text":"MBMRequestErrorType","kind":"identifier"}]}]}]}