{"topicSections":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NetworkRestriction\/hashValue"],"title":"Instance Properties"},{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NetworkRestriction\/hash(into:)"],"title":"Instance Methods"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NetworkRestriction\/RawRepresentable-Implementations"},"sections":[],"kind":"article","metadata":{"title":"RawRepresentable Implementations","modules":[{"name":"MapboxCommon"}],"role":"collectionGroup","roleHeading":"API Collection"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NetworkRestriction"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/NetworkRestriction":{"abstract":[{"type":"text","text":"Classify network types based on cost."}],"title":"NetworkRestriction","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NetworkRestriction","url":"\/documentation\/mapboxcommon\/networkrestriction","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetworkRestriction"}],"navigatorTitle":[{"kind":"identifier","text":"NetworkRestriction"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/NetworkRestriction/hashValue":{"conformance":{"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":"."}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"availabilityPrefix":[{"type":"text","text":"Available when"}]},"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"kind":"symbol","role":"symbol","abstract":[],"title":"hashValue","url":"\/documentation\/mapboxcommon\/networkrestriction\/hashvalue","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NetworkRestriction\/hashValue"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/NetworkRestriction/hash(into:)":{"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NetworkRestriction\/hash(into:)","title":"hash(into:)","url":"\/documentation\/mapboxcommon\/networkrestriction\/hash(into:)","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"preciseIdentifier":"s:s6HasherV","kind":"typeIdentifier","text":"Hasher"},{"kind":"text","text":")"}],"conformance":{"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}]}},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"url":"\/documentation\/mapboxcommon","role":"collection","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","type":"topic","abstract":[],"title":"MapboxCommon"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","abstract":[],"type":"topic","title":"MapboxMaps Documentation","kind":"article","url":"\/documentation\/overview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1NetworkRestriction\/title","value":"MBXNetworkRestriction"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1NetworkRestriction\/fragments","value":[{"text":"MBXNetworkRestriction","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1NetworkRestriction\/navigatorTitle","value":[{"kind":"identifier","text":"MBXNetworkRestriction"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}