{"sections":[],"variants":[{"paths":["\/documentation\/mapboxmaps\/customlayerhost\/prerender(_:mtlcommandbuffer:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/customlayerhost\/prerender(_:mtlcommandbuffer:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerHost"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerHost\/prerender(_:mtlCommandBuffer:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"prerender"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"parameters"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MBMCustomLayerRenderParameters","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters","text":"CustomLayerRenderParameters"},{"text":", ","kind":"text"},{"text":"mtlCommandBuffer","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"MTLCommandBuffer","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MTLCommandBuffer"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMCustomLayerRenderConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderConfiguration","text":"CustomLayerRenderConfiguration"}],"platforms":["iOS"]}]}],"metadata":{"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"prerender:mtlCommandBuffer:"}],"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"prerender","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMCustomLayerRenderParameters","text":"CustomLayerRenderParameters","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"mtlCommandBuffer","kind":"externalParam"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MTLCommandBuffer","text":"MTLCommandBuffer"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CustomLayerRenderConfiguration","preciseIdentifier":"c:objc(cs)MBMCustomLayerRenderConfiguration"}],"role":"symbol","roleHeading":"Instance Method","title":"prerender(_:mtlCommandBuffer:)","externalID":"c:objc(pl)MBMCustomLayerHost(im)prerender:mtlCommandBuffer:","modules":[{"name":"MapboxMaps"}]},"abstract":[{"text":"Note! This selector is an experimental feature. It can be changed or removed in future versions.","type":"text"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"type":"topic","role":"collection","kind":"symbol","title":"MapboxMaps","url":"\/documentation\/mapboxmaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerHost/prerender(_:mtlCommandBuffer:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerHost\/prerender(_:mtlCommandBuffer:)","abstract":[{"type":"text","text":"Note! This selector is an experimental feature. It can be changed or removed in future versions."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"prerender:mtlCommandBuffer:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"prerender"},{"text":"(","kind":"text"},{"text":"CustomLayerRenderParameters","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMCustomLayerRenderParameters"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mtlCommandBuffer"},{"text":": any ","kind":"text"},{"text":"MTLCommandBuffer","preciseIdentifier":"c:objc(pl)MTLCommandBuffer","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"CustomLayerRenderConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMCustomLayerRenderConfiguration"}],"type":"topic","kind":"symbol","required":true,"url":"\/documentation\/mapboxmaps\/customlayerhost\/prerender(_:mtlcommandbuffer:)","title":"prerender(_:mtlCommandBuffer:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerRenderConfiguration":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/customlayerrenderconfiguration","navigatorTitle":[{"text":"CustomLayerRenderConfiguration","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderConfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CustomLayerRenderConfiguration","kind":"identifier"}],"abstract":[{"text":"Note! This is an experimental feature. It can be changed or removed in future versions.","type":"text"}],"title":"CustomLayerRenderConfiguration","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerHost":{"type":"topic","title":"CustomLayerHost","navigatorTitle":[{"text":"CustomLayerHost","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomLayerHost","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/customlayerhost","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerHost","abstract":[{"text":"Interface for hosting a custom map style layer.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerRenderParameters":{"url":"\/documentation\/mapboxmaps\/customlayerrenderparameters","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CustomLayerRenderParameters"}],"abstract":[{"type":"text","text":"Parameters that define the current camera position for a "},{"type":"codeVoice","code":"CustomLayerHost::render()"},{"type":"text","text":" function."}],"kind":"symbol","title":"CustomLayerRenderParameters","navigatorTitle":[{"text":"CustomLayerRenderParameters","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layers":{"kind":"article","url":"\/documentation\/mapboxmaps\/layers","title":"Layers","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers","abstract":[],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"type":"topic","role":"collection","kind":"article","title":"MapboxMaps Documentation","url":"\/documentation\/overview"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"prerender:mtlCommandBuffer:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"prerender:mtlCommandBuffer:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMCustomLayerRenderConfiguration","kind":"typeIdentifier","text":"MBMCustomLayerRenderConfiguration","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderConfiguration"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"prerender:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)MBMCustomLayerRenderParameters","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters","text":"MBMCustomLayerRenderParameters"},{"text":" *) ","kind":"text"},{"text":"parameters","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"mtlCommandBuffer:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qoobjc(pl)MTLCommandBuffer","kind":"typeIdentifier","text":"id<MTLCommandBuffer>"},{"kind":"text","text":") "},{"text":"mtlCommandBuffer","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"prerender:mtlCommandBuffer:","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost~1prerender(_:mtlCommandBuffer:)\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost~1prerender(_:mtlCommandBuffer:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"prerender:mtlCommandBuffer:","kind":"identifier"}],"op":"replace"},{"value":"MBMCustomLayerRenderConfiguration","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderConfiguration\/title"},{"value":[{"kind":"identifier","text":"MBMCustomLayerRenderConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"MBMCustomLayerRenderConfiguration"}]},{"op":"replace","value":"MBMCustomLayerHost","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMCustomLayerHost"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost\/navigatorTitle","value":[{"text":"MBMCustomLayerHost","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/title","op":"replace","value":"MBMCustomLayerRenderParameters"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/fragments","value":[{"kind":"identifier","text":"MBMCustomLayerRenderParameters"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMCustomLayerRenderParameters"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}