{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/mapboxcommon\/permissionstatus\/init(rawvalue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus\/init(rawValue:)"},"metadata":{"role":"symbol","externalID":"s:So19MBXPermissionStatusV8rawValueABSgSi_tcfc","title":"init(rawValue:)","symbolKind":"init","modules":[{"name":"MapboxCommon"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"roleHeading":"Initializer"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus"]]},"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PermissionStatus/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","abstract":[],"url":"\/documentation\/mapboxcommon\/permissionstatus\/init(rawvalue:)","kind":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus\/init(rawValue:)"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"type":"topic","url":"\/documentation\/overview","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Location-APIs":{"kind":"article","role":"collectionGroup","abstract":[],"title":"Location","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","type":"topic","url":"\/documentation\/mapboxmaps\/location-apis"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PermissionStatus":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus","abstract":[{"type":"text","text":"Location permissions granted by user to the app."}],"title":"PermissionStatus","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PermissionStatus"}],"type":"topic","url":"\/documentation\/mapboxcommon\/permissionstatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PermissionStatus"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","type":"topic","title":"MapboxMaps","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"MBXPermissionStatus","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBXPermissionStatus"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MBXPermissionStatus"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}