{"metadata":{"roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"HttpRequest"}],"modules":[{"name":"MapboxCommon"}],"title":"HttpRequest","externalID":"c:objc(cs)MBXHttpRequest","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HttpRequest","kind":"identifier"}],"symbolKind":"class","role":"symbol"},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest\/init(method:url:headers:timeout:networkRestriction:sdkInformation:body:flags:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest\/init(url:headers:sdkInformation:body:)"],"generated":true,"anchor":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest\/body","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest\/flags","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest\/headers","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest\/method","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest\/networkRestriction","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest\/sdkInformation","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest\/timeout","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest\/url"],"generated":true,"anchor":"Instance-Properties"}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon"]]},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH"],"type":"conformsTo"}],"sections":[],"kind":"symbol","abstract":[{"text":"HttpRequest holds basic information for construction of an HTTP request","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HttpRequest"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/mapboxcommon\/httprequest"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxcommon\/httprequest"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequest/networkRestriction":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest\/networkRestriction","navigatorTitle":[{"kind":"identifier","text":"networkRestriction"}],"abstract":[{"type":"text","text":"Restrict the request to the specified network types. If none of the specified network types is available, the"},{"type":"text","text":" "},{"type":"text","text":"download fails with a connection error."}],"title":"networkRestriction","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkRestriction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBXNetworkRestriction","text":"NetworkRestriction"}],"type":"topic","url":"\/documentation\/mapboxcommon\/httprequest\/networkrestriction","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequest/body":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"body","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"body"}],"title":"body","abstract":[{"type":"text","text":"HTTP Body data transmitted in an HTTP transaction message immediately following the headers if there is any."},{"type":"text","text":" "},{"type":"text","text":"Body data is used by POST HTTP methods."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest\/body","role":"symbol","type":"topic","url":"\/documentation\/mapboxcommon\/httprequest\/body","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequest/method":{"navigatorTitle":[{"text":"method","kind":"identifier"}],"abstract":[{"type":"text","text":"HTTP defines a set of request methods to indicate the desired action to be performed for a given resource."},{"type":"text","text":" "},{"type":"text","text":"Specify desired method using this parameter."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest\/method","title":"method","kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"method","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@MBXHttpMethod","text":"HttpMethod","kind":"typeIdentifier"}],"role":"symbol","url":"\/documentation\/mapboxcommon\/httprequest\/method"},"doc://com.mapbox.MapboxMaps/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequest/init(url:headers:sdkInformation:body:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"url"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"headers"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"sdkInformation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SdkInformation","preciseIdentifier":"c:objc(cs)MBXSdkInformation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"body"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?)"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithUrl:headers:sdkInformation:body:"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest\/init(url:headers:sdkInformation:body:)","abstract":[],"url":"\/documentation\/mapboxcommon\/httprequest\/init(url:headers:sdkinformation:body:)","kind":"symbol","title":"init(url:headers:sdkInformation:body:)","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequest/flags":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"flags"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s6UInt32V","kind":"typeIdentifier","text":"UInt32"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest\/flags","url":"\/documentation\/mapboxcommon\/httprequest\/flags","type":"topic","title":"flags","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"flags"}],"abstract":[{"type":"text","text":"Various flags that control HttpRequest processing."}]},"doc://com.mapbox.MapboxMaps/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequest/init(method:url:headers:timeout:networkRestriction:sdkInformation:body:flags:)":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest\/init(method:url:headers:timeout:networkRestriction:sdkInformation:body:flags:)","kind":"symbol","title":"init(method:url:headers:timeout:networkRestriction:sdkInformation:body:flags:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"method","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@MBXHttpMethod","text":"HttpMethod","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"url","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"headers","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"timeout","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s6UInt64V","text":"UInt64","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"networkRestriction","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NetworkRestriction","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBXNetworkRestriction"},{"text":", ","kind":"text"},{"text":"sdkInformation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SdkInformation","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXSdkInformation"},{"text":", ","kind":"text"},{"text":"body","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":"?, ","kind":"text"},{"text":"flags","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt32","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt32V"},{"text":")","kind":"text"}],"type":"topic","abstract":[],"url":"\/documentation\/mapboxcommon\/httprequest\/init(method:url:headers:timeout:networkrestriction:sdkinformation:body:flags:)","navigatorTitle":[{"text":"initWithMethod:url:headers:timeout:networkRestriction:sdkInformation:body:flags:","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","kind":"article","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequest/headers":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"headers"}],"url":"\/documentation\/mapboxcommon\/httprequest\/headers","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"headers"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"]"}],"abstract":[{"text":"HTTP headers to include.","type":"text"},{"text":" ","type":"text"},{"text":"If you provide ","type":"text"},{"code":"User-Agent","type":"codeVoice"},{"text":" header using this ","type":"text"},{"code":"headers","type":"codeVoice"},{"text":" field, then resulting ","type":"text"},{"code":"User-Agent","type":"codeVoice"},{"text":" will also contain","type":"text"},{"text":" ","type":"text"},{"text":"information about application, platform, device, and Common SDK’s version.","type":"text"},{"text":" ","type":"text"},{"text":"If you provide duplicate headers then ","type":"text"},{"code":"request","type":"codeVoice"},{"text":" call will be immediately failed.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest\/headers","type":"topic","title":"headers"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequest/sdkInformation":{"url":"\/documentation\/mapboxcommon\/httprequest\/sdkinformation","abstract":[{"text":"SDK Information to be appended to the User-Agent string.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest\/sdkInformation","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sdkInformation","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SdkInformation","preciseIdentifier":"c:objc(cs)MBXSdkInformation","kind":"typeIdentifier"}],"type":"topic","title":"sdkInformation","role":"symbol","navigatorTitle":[{"text":"sdkInformation","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","url":"\/documentation\/mapboxcommon","type":"topic","role":"collection","title":"MapboxCommon"},"doc://com.mapbox.MapboxMaps/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject","title":"NSObject"},"doc://com.mapbox.MapboxMaps/SH":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.mapbox.MapboxMaps/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.mapbox.MapboxMaps/SQ":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.mapbox.MapboxMaps/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequest/url":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"url"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"url"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest\/url","abstract":[{"text":"URL the request should be sent to","type":"text"}],"url":"\/documentation\/mapboxcommon\/httprequest\/url","kind":"symbol","title":"url","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequest":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HttpRequest","kind":"identifier"}],"navigatorTitle":[{"text":"HttpRequest","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest","title":"HttpRequest","type":"topic","abstract":[{"text":"HttpRequest holds basic information for construction of an HTTP request","type":"text"}],"kind":"symbol","url":"\/documentation\/mapboxcommon\/httprequest"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequest/timeout":{"title":"timeout","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timeout","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt64","preciseIdentifier":"s:s6UInt64V","kind":"typeIdentifier"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Timeout defines how long, in seconds, the request is allowed to take in total (including connecting to the host)."},{"type":"text","text":" "},{"type":"text","text":"Default is 0, meaning no timeout."}],"navigatorTitle":[{"text":"timeout","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest\/timeout","kind":"symbol","url":"\/documentation\/mapboxcommon\/httprequest\/timeout"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MBXHttpRequest"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MBXHttpRequest","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"MBXHttpRequest","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest\/body","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest\/flags","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest\/headers","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest\/method","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest\/networkRestriction","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest\/sdkInformation","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest\/timeout","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest\/url"]},{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest\/init(method:url:headers:timeout:networkRestriction:sdkInformation:body:flags:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest\/init(url:headers:sdkInformation:body:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"]}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBXHttpRequest","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest~1networkRestriction\/title","value":"networkRestriction"},{"value":[{"kind":"identifier","text":"networkRestriction"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest~1networkRestriction\/fragments","op":"replace"},{"value":"body","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest~1body\/title","op":"replace"},{"value":[{"kind":"identifier","text":"body"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest~1body\/fragments","op":"replace"},{"value":"method","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest~1method\/title","op":"replace"},{"value":[{"kind":"identifier","text":"method"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest~1method\/fragments","op":"replace"},{"value":"initWithUrl:headers:sdkInformation:body:","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest~1init(url:headers:sdkInformation:body:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithUrl:headers:sdkInformation:body:"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest~1init(url:headers:sdkInformation:body:)\/fragments","op":"replace"},{"value":"flags","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest~1flags\/title","op":"replace"},{"value":[{"text":"flags","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest~1flags\/fragments","op":"replace"},{"value":"initWithMethod:url:headers:timeout:networkRestriction:sdkInformation:body:flags:","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest~1init(method:url:headers:timeout:networkRestriction:sdkInformation:body:flags:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMethod:url:headers:timeout:networkRestriction:sdkInformation:body:flags:"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest~1init(method:url:headers:timeout:networkRestriction:sdkInformation:body:flags:)\/fragments","op":"replace"},{"value":"headers","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest~1headers\/title","op":"replace"},{"value":[{"text":"headers","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest~1headers\/fragments","op":"replace"},{"value":"sdkInformation","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest~1sdkInformation\/title","op":"replace"},{"value":[{"text":"sdkInformation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest~1sdkInformation\/fragments","op":"replace"},{"value":"url","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest~1url\/title","op":"replace"},{"value":[{"kind":"identifier","text":"url"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest~1url\/fragments","op":"replace"},{"value":"MBXHttpRequest","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MBXHttpRequest"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MBXHttpRequest"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest\/navigatorTitle","op":"replace"},{"value":"timeout","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest~1timeout\/title","op":"replace"},{"value":[{"kind":"identifier","text":"timeout"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest~1timeout\/fragments","op":"replace"}]}]}