{"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXExceptionHandler\/tryWithCallback:error:","interfaceLanguage":"occ"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"tryWithCallback:","kind":"identifier"},{"kind":"text","text":"("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":" (^"},{"kind":"text","text":")()) "},{"text":"callback","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"text":" * *) ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"MapboxCommon"}],"navigatorTitle":[{"kind":"identifier","text":"tryWithCallback:error:"}],"externalID":"c:objc(cs)MBXExceptionHandler(cm)tryWithCallback:error:","symbolKind":"method","title":"tryWithCallback:error:","fragments":[{"text":"+ ","kind":"text"},{"text":"tryWithCallback:error:","kind":"identifier"}],"role":"symbol","roleHeading":"Type Method"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NSExceptionHandler"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/mbxexceptionhandler\/trywithcallback:error:"]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Performance":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/performance","type":"topic","abstract":[],"title":"Performance and investigations","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article","role":"collection","type":"topic","abstract":[],"url":"\/documentation\/overview","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","title":"MapboxMaps","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXExceptionHandler/tryWithCallback:error:":{"url":"\/documentation\/mapboxcommon\/mbxexceptionhandler\/trywithcallback:error:","abstract":[],"fragments":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"tryWithCallback:error:"}],"type":"topic","title":"tryWithCallback:error:","kind":"symbol","navigatorTitle":[{"text":"tryWithCallback:error:","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXExceptionHandler\/tryWithCallback:error:"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/NSExceptionHandler":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSExceptionHandler"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"NSExceptionHandler"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NSExceptionHandler","title":"NSExceptionHandler","role":"symbol","url":"\/documentation\/mapboxcommon\/nsexceptionhandler","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MBXExceptionHandler","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1NSExceptionHandler\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1NSExceptionHandler\/fragments","value":[{"text":"MBXExceptionHandler","kind":"identifier"}],"op":"replace"},{"value":[{"text":"MBXExceptionHandler","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1NSExceptionHandler\/navigatorTitle"}]}]}