{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpResponse\/request"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpResponse"]]},"variants":[{"paths":["\/documentation\/mapboxcommon\/httpresponse\/request"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxcommon\/httpresponse\/request"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"request","kind":"identifier"},{"text":": ","kind":"text"},{"text":"HttpRequest","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest","preciseIdentifier":"c:objc(cs)MBXHttpRequest","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"request"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBXHttpRequest","text":"HttpRequest","kind":"typeIdentifier"}],"symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"MapboxCommon"}],"externalID":"c:objc(cs)MBXHttpResponse(py)request","navigatorTitle":[{"text":"request","kind":"identifier"}],"role":"symbol","title":"request"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"abstract":[{"type":"text","text":"HTTP request data which was use to send HTTP request."}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpResponse":{"navigatorTitle":[{"kind":"identifier","text":"HttpResponse"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpResponse","type":"topic","abstract":[{"type":"text","text":"Record which is used to report HTTP response to the caller."}],"title":"HttpResponse","kind":"symbol","url":"\/documentation\/mapboxcommon\/httpresponse","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HttpResponse"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","title":"MapboxCommon","type":"topic","url":"\/documentation\/mapboxcommon","abstract":[],"kind":"symbol","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","abstract":[],"type":"topic","kind":"article","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpResponse/request":{"navigatorTitle":[{"kind":"identifier","text":"request"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpResponse\/request","type":"topic","abstract":[{"type":"text","text":"HTTP request data which was use to send HTTP request."}],"title":"request","kind":"symbol","url":"\/documentation\/mapboxcommon\/httpresponse\/request","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"request","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MBXHttpRequest","text":"HttpRequest","kind":"typeIdentifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequest":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest","title":"HttpRequest","type":"topic","url":"\/documentation\/mapboxcommon\/httprequest","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"HttpRequest"}],"abstract":[{"type":"text","text":"HttpRequest holds basic information for construction of an HTTP request"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"HttpRequest","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"request","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"request"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"MBXHttpRequest","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest","preciseIdentifier":"c:objc(cs)MBXHttpRequest","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"request","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"MBXHttpResponse","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpResponse\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpResponse\/fragments","value":[{"kind":"identifier","text":"MBXHttpResponse"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpResponse\/navigatorTitle","value":[{"text":"MBXHttpResponse","kind":"identifier"}],"op":"replace"},{"value":"request","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpResponse~1request\/title"},{"op":"replace","value":[{"text":"request","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpResponse~1request\/fragments"},{"op":"replace","value":"MBXHttpRequest","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest\/fragments","value":[{"text":"MBXHttpRequest","kind":"identifier"}]},{"op":"replace","value":[{"text":"MBXHttpRequest","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest\/navigatorTitle"}]}]}