{"sections":[],"variants":[{"paths":["\/documentation\/mapboxmaps\/responsesourcetype\/network"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/responsesourcetype\/network"]}],"kind":"symbol","metadata":{"roleHeading":"Case","role":"symbol","title":"ResponseSourceType.network","symbolKind":"case","modules":[{"name":"MapboxMaps"}],"navigatorTitle":[{"kind":"identifier","text":"MBMResponseSourceTypeNetwork"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"network","kind":"identifier"}],"externalID":"c:@E@MBMResponseSourceType@MBMResponseSourceTypeNetwork"},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResponseSourceType\/network","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResponseSourceType"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"network"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"The source of the response is a network."}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResponseSourceType/network":{"navigatorTitle":[{"text":"MBMResponseSourceTypeNetwork","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResponseSourceType\/network","type":"topic","role":"symbol","abstract":[{"type":"text","text":"The source of the response is a network."}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"network"}],"url":"\/documentation\/mapboxmaps\/responsesourcetype\/network","kind":"symbol","title":"ResponseSourceType.network"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","type":"topic","title":"MapboxMaps","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResponseSourceType":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ResponseSourceType","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/responsesourcetype","abstract":[{"text":"The enumeration defines the source type that provides the requested resource.","type":"text"}],"navigatorTitle":[{"text":"ResponseSourceType","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResponseSourceType","title":"ResponseSourceType","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","abstract":[],"url":"\/documentation\/overview","role":"collection","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"abstract":[{"text":"The simplified diagram of the events emitted by the map is displayed below.","type":"text"}],"url":"\/documentation\/mapboxmaps\/events","kind":"article","title":"Map events","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","type":"topic","role":"collectionGroup"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"MBMResponseSourceTypeNetwork"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MBMResponseSourceTypeNetwork"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"MBMResponseSourceTypeNetwork","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResponseSourceType~1network\/title","op":"replace","value":"MBMResponseSourceTypeNetwork"},{"value":[{"text":"MBMResponseSourceTypeNetwork","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResponseSourceType~1network\/fragments","op":"replace"},{"value":"MBMResponseSourceType","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResponseSourceType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResponseSourceType\/fragments","value":[{"kind":"identifier","text":"MBMResponseSourceType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResponseSourceType\/navigatorTitle","value":[{"kind":"identifier","text":"MBMResponseSourceType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}