name: ValidateLatestMaps
options:
  bundleIdPrefix: com.mapbox
settings:
  DEVELOPMENT_TEAM: GJZR2MEM28
packages:
  MapboxMaps:
    url: git@github.com:mapbox/${REPOSITORY_NAME}
    ${MAPS_VERSION_RULE}: ${MAPS_VERSION}
targets:
  SwiftPackageManagerIntegration:
    templates:
      - Application
    dependencies:
      - package: MapboxMaps
  SwiftPackageManagerIntegrationUITest:
    templates:
      - UITest
    dependencies:
      - target: SwiftPackageManagerIntegration
  CocoaPodsIntegration:
    templates:
      - Application
  CocoaPodsIntegrationUITest:
    templates:
      - UITest
    dependencies:
      - target: CocoaPodsIntegration
  DirectDynamicDownload:
    templates:
      - Application
    dependencies:
      - framework: ${DYNAMIC_ARTIFACTS_PATH}/MapboxMaps.xcframework
      - framework: ${DYNAMIC_ARTIFACTS_PATH}/MapboxCoreMaps.xcframework
      - framework: ${DYNAMIC_ARTIFACTS_PATH}/MapboxCommon.xcframework
      - framework: ${DYNAMIC_ARTIFACTS_PATH}/Turf.xcframework
  DirectDynamicDownloadUITest:
    templates:
      - UITest
    dependencies:
      - target: DirectDynamicDownload
targetTemplates:
  Application:
    sources: [ViewController.swift]
    platform: iOS
    deploymentTarget:
      iOS: 11.0
    type: application
    info:
      path: Info.plist
      properties:
        MBXAccessToken: ${MBX_TOKEN}
        UILaunchStoryboardName: LaunchScreen
    scheme:
      testTargets:
        - ${target_name}UITest
  UITest:
    type: bundle.ui-testing
    platform: iOS
    sources: MapLoadingUITest.swift
    info:
      path: Info-tests.plist
