{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType"]]},"sections":[],"metadata":{"modules":[{"name":"MapboxCommon"}],"symbolKind":"case","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tileCountExceeded","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MBXTileRegionErrorTypeTileCountExceeded"}],"role":"symbol","title":"TileRegionErrorType.tileCountExceeded","externalID":"c:@E@MBXTileRegionErrorType@MBXTileRegionErrorTypeTileCountExceeded"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType\/tileCountExceeded"},"kind":"symbol","variants":[{"paths":["\/documentation\/mapboxcommon\/tileregionerrortype\/tilecountexceeded"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxcommon\/tileregionerrortype\/tilecountexceeded"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"The region contains more tiles than allowed."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tileCountExceeded","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","kind":"article","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionErrorType/tileCountExceeded":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType\/tileCountExceeded","url":"\/documentation\/mapboxcommon\/tileregionerrortype\/tilecountexceeded","type":"topic","abstract":[{"type":"text","text":"The region contains more tiles than allowed."}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tileCountExceeded"}],"navigatorTitle":[{"kind":"identifier","text":"MBXTileRegionErrorTypeTileCountExceeded"}],"title":"TileRegionErrorType.tileCountExceeded","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionErrorType":{"title":"TileRegionErrorType","url":"\/documentation\/mapboxcommon\/tileregionerrortype","role":"symbol","abstract":[{"text":"Describes the reason for a tile region download request failure.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileRegionErrorType"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TileRegionErrorType"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","url":"\/documentation\/mapboxcommon","type":"topic","role":"collection","title":"MapboxCommon"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"MBXTileRegionErrorTypeTileCountExceeded","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"MBXTileRegionErrorTypeTileCountExceeded"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"MBXTileRegionErrorTypeTileCountExceeded"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionErrorType~1tileCountExceeded\/title","value":"MBXTileRegionErrorTypeTileCountExceeded"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionErrorType~1tileCountExceeded\/fragments","value":[{"text":"MBXTileRegionErrorTypeTileCountExceeded","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionErrorType\/title","value":"MBXTileRegionErrorType"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionErrorType\/fragments","value":[{"text":"MBXTileRegionErrorType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionErrorType\/navigatorTitle","value":[{"text":"MBXTileRegionErrorType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}