{"metadata":{"title":"timestamp","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"timestamp","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"}],"modules":[{"name":"MapboxMaps"}],"externalID":"c:objc(cs)MBMSourceAdded(py)timestamp","roleHeading":"Instance Property","navigatorTitle":[{"text":"timestamp","kind":"identifier"}],"role":"symbol","symbolKind":"property"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceAdded"]]},"abstract":[{"type":"text","text":"The timestamp of source addition."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"timestamp","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/mapboxmaps\/sourceadded\/timestamp"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/sourceadded\/timestamp"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceAdded\/timestamp","interfaceLanguage":"swift"},"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","url":"\/documentation\/overview","title":"MapboxMaps Documentation","type":"topic","role":"collection","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"kind":"article","title":"Map events","abstract":[{"type":"text","text":"The simplified diagram of the events emitted by the map is displayed below."}],"type":"topic","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/events","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceAdded/timestamp":{"title":"timestamp","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"timestamp","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceAdded\/timestamp","url":"\/documentation\/mapboxmaps\/sourceadded\/timestamp","abstract":[{"text":"The timestamp of source addition.","type":"text"}],"navigatorTitle":[{"text":"timestamp","kind":"identifier"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceAdded":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceAdded","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceAdded"}],"title":"SourceAdded","navigatorTitle":[{"kind":"identifier","text":"SourceAdded"}],"kind":"symbol","abstract":[{"text":"The source has been added with ","type":"text"},{"type":"codeVoice","code":"addStyleSource"},{"type":"text","text":" method."}],"url":"\/documentation\/mapboxmaps\/sourceadded"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","type":"topic","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"title":"MapboxMaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"timestamp","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"timestamp","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSDate","text":"NSDate","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"timestamp","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"timestamp","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAdded~1timestamp\/title","op":"replace"},{"value":[{"text":"timestamp","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAdded~1timestamp\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAdded\/title","value":"MBMSourceAdded"},{"value":[{"text":"MBMSourceAdded","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAdded\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAdded\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMSourceAdded"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}