{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/View-Annotations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationOptions"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"annotatedFeature","kind":"externalParam"},{"kind":"text","text":": "},{"text":"AnnotatedFeature","preciseIdentifier":"s:10MapboxMaps16AnnotatedFeatureV","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"width","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"text":"?, ","kind":"text"},{"text":"height","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"allowOverlap","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"allowOverlapWithPuck","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":"?, ","kind":"text"},{"text":"visible","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"priority","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"variableAnchors"},{"text":": [","kind":"text"},{"text":"ViewAnnotationAnchorConfig","preciseIdentifier":"c:objc(cs)MBMViewAnnotationAnchorConfig","kind":"typeIdentifier"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"ignoreCameraPadding"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"minZoom"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"maxZoom"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"symbolKind":"init","title":"init(annotatedFeature:width:height:allowOverlap:allowOverlapWithPuck:visible:priority:variableAnchors:ignoreCameraPadding:minZoom:maxZoom:)","externalID":"s:10MapboxMaps21ViewAnnotationOptionsV16annotatedFeature5width6height12allowOverlap0jK8WithPuck7visible8priority15variableAnchors19ignoreCameraPadding7minZoom03maxV0AcA09AnnotatedG0VSg_14CoreFoundation7CGFloatVSgAUSbSgA2VSiSgSaySo07MBMViewD12AnchorConfigCGSgAVSdSgA0_tcfc","roleHeading":"Initializer","modules":[{"name":"MapboxMaps"}],"role":"symbol"},"abstract":[{"type":"text","text":"Initializes a "},{"code":"ViewAnnotationOptions","type":"codeVoice"}],"variants":[{"paths":["\/documentation\/mapboxmaps\/viewannotationoptions\/init(annotatedfeature:width:height:allowoverlap:allowoverlapwithpuck:visible:priority:variableanchors:ignorecamerapadding:minzoom:maxzoom:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationOptions\/init(annotatedFeature:width:height:allowOverlap:allowOverlapWithPuck:visible:priority:variableAnchors:ignoreCameraPadding:minZoom:maxZoom:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"annotatedFeature"},{"kind":"text","text":": "},{"text":"AnnotatedFeature","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AnnotatedFeature","preciseIdentifier":"s:10MapboxMaps16AnnotatedFeatureV"},{"text":"? = nil, ","kind":"text"},{"text":"width","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"text":"height","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"kind":"text","text":"? = nil, "},{"text":"allowOverlap","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"allowOverlapWithPuck"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"text":"visible","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"priority"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"variableAnchors"},{"kind":"text","text":": ["},{"text":"ViewAnnotationAnchorConfig","preciseIdentifier":"c:objc(cs)MBMViewAnnotationAnchorConfig","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchorConfig"},{"text":"]? = nil, ","kind":"text"},{"kind":"externalParam","text":"ignoreCameraPadding"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":"? = nil, ","kind":"text"},{"text":"minZoom","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"maxZoom"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"kind":"text","text":"? = nil)"}]}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationOptions":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationOptions","url":"\/documentation\/mapboxmaps\/viewannotationoptions","role":"symbol","title":"ViewAnnotationOptions","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"ViewAnnotationOptions","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ViewAnnotationOptions"}],"abstract":[{"text":"Stores layout and visibility settings for a view annotation.","type":"text"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationAnchorConfig":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ViewAnnotationAnchorConfig"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/viewannotationanchorconfig","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchorConfig","abstract":[{"type":"text","text":"Represents a specific setting for a view annotation anchor."}],"role":"symbol","title":"ViewAnnotationAnchorConfig","navigatorTitle":[{"text":"ViewAnnotationAnchorConfig","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AnnotatedFeature":{"title":"AnnotatedFeature","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"AnnotatedFeature","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/annotatedfeature","role":"symbol","abstract":[{"type":"text","text":"Represents either a GeoJSON geometry or an annotated layer feature."}],"navigatorTitle":[{"kind":"identifier","text":"AnnotatedFeature"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AnnotatedFeature","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/View-Annotations":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/View-Annotations","title":"View Annotations","url":"\/documentation\/mapboxmaps\/view-annotations","kind":"article","type":"topic","abstract":[],"role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationOptions/init(annotatedFeature:width:height:allowOverlap:allowOverlapWithPuck:visible:priority:variableAnchors:ignoreCameraPadding:minZoom:maxZoom:)":{"url":"\/documentation\/mapboxmaps\/viewannotationoptions\/init(annotatedfeature:width:height:allowoverlap:allowoverlapwithpuck:visible:priority:variableanchors:ignorecamerapadding:minzoom:maxzoom:)","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationOptions\/init(annotatedFeature:width:height:allowOverlap:allowOverlapWithPuck:visible:priority:variableAnchors:ignoreCameraPadding:minZoom:maxZoom:)","abstract":[{"type":"text","text":"Initializes a "},{"type":"codeVoice","code":"ViewAnnotationOptions"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"annotatedFeature","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps16AnnotatedFeatureV","text":"AnnotatedFeature","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"width","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":"?, "},{"text":"height","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"allowOverlap"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"allowOverlapWithPuck","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":"?, ","kind":"text"},{"text":"visible","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"priority","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"variableAnchors"},{"kind":"text","text":": ["},{"text":"ViewAnnotationAnchorConfig","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMViewAnnotationAnchorConfig"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"ignoreCameraPadding"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"minZoom"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":"?, ","kind":"text"},{"text":"maxZoom","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":"?)","kind":"text"}],"type":"topic","title":"init(annotatedFeature:width:height:allowOverlap:allowOverlapWithPuck:visible:priority:variableAnchors:ignoreCameraPadding:minZoom:maxZoom:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","url":"\/documentation\/mapboxmaps","type":"topic","kind":"symbol","title":"MapboxMaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"type":"topic","title":"MapboxMaps Documentation","url":"\/documentation\/overview"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MBMViewAnnotationAnchorConfig","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchorConfig\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchorConfig\/fragments","value":[{"kind":"identifier","text":"MBMViewAnnotationAnchorConfig"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchorConfig\/navigatorTitle","value":[{"text":"MBMViewAnnotationAnchorConfig","kind":"identifier"}],"op":"replace"}]}]}