{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestDataSourceType\/asset"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestDataSourceType"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"The resource is requested from the asset management subsystem."}],"kind":"symbol","variants":[{"paths":["\/documentation\/mapboxmaps\/requestdatasourcetype\/asset"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/requestdatasourcetype\/asset"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"asset"}],"title":"RequestDataSourceType.asset","modules":[{"name":"MapboxMaps"}],"roleHeading":"Case","externalID":"c:@E@MBMRequestDataSourceType@MBMRequestDataSourceTypeAsset","symbolKind":"case","role":"symbol","navigatorTitle":[{"text":"MBMRequestDataSourceTypeAsset","kind":"identifier"}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"asset","kind":"identifier"}]}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"url":"\/documentation\/mapboxmaps\/events","role":"collectionGroup","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","abstract":[{"type":"text","text":"The simplified diagram of the events emitted by the map is displayed below."}],"type":"topic","title":"Map events"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","abstract":[],"kind":"article","url":"\/documentation\/overview","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","role":"collection","kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestDataSourceType/asset":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"asset","kind":"identifier"}],"title":"RequestDataSourceType.asset","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBMRequestDataSourceTypeAsset"}],"type":"topic","url":"\/documentation\/mapboxmaps\/requestdatasourcetype\/asset","abstract":[{"text":"The resource is requested from the asset management subsystem.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestDataSourceType\/asset","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestDataSourceType":{"role":"symbol","kind":"symbol","url":"\/documentation\/mapboxmaps\/requestdatasourcetype","type":"topic","title":"RequestDataSourceType","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestDataSourceType","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"RequestDataSourceType","kind":"identifier"}],"navigatorTitle":[{"text":"RequestDataSourceType","kind":"identifier"}],"abstract":[{"type":"text","text":"The enumeration defines the type of data source."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"MBMRequestDataSourceTypeAsset","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"MBMRequestDataSourceTypeAsset","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"MBMRequestDataSourceTypeAsset"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestDataSourceType~1asset\/title","value":"MBMRequestDataSourceTypeAsset","op":"replace"},{"value":[{"text":"MBMRequestDataSourceTypeAsset","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestDataSourceType~1asset\/fragments","op":"replace"},{"value":"MBMRequestDataSourceType","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestDataSourceType\/title","op":"replace"},{"value":[{"text":"MBMRequestDataSourceType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestDataSourceType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestDataSourceType\/navigatorTitle","value":[{"text":"MBMRequestDataSourceType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}