{"kind":"symbol","metadata":{"modules":[{"name":"MapboxMaps"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"centerAltitudeMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MapCenterAltitudeMode","preciseIdentifier":"c:@E@MBMMapCenterAltitudeMode"}],"symbolKind":"property","title":"centerAltitudeMode","role":"symbol","externalID":"s:10MapboxMaps0A3MapC18centerAltitudeModeSo012MBMMapCentereF0Vvp","roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/centerAltitudeMode"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"centerAltitudeMode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@MBMMapCenterAltitudeMode","text":"MapCenterAltitudeMode","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapCenterAltitudeMode"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"abstract":[{"text":"Get\/set the map centerAltitudeMode that defines how the map center point should react to terrain elevation changes.","type":"text"},{"text":" ","type":"text"},{"text":"See ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapCenterAltitudeMode","type":"reference","isActive":true},{"text":" for options.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/mapboxmap\/centeraltitudemode"]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap":{"navigatorTitle":[{"text":"MapboxMap","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Provides access to the map model, including the camera, style, observable map events,"},{"type":"text","text":" "},{"type":"text","text":"and querying rendered features."}],"title":"MapboxMap","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapboxMap","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"title":"MapboxMap","type":"topic","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","abstract":[],"url":"\/documentation\/mapboxmaps\/mapboxmap-apis","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapCenterAltitudeMode":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapCenterAltitudeMode","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapCenterAltitudeMode"}],"abstract":[{"text":"Defines how the map center point should react to terrain elevation changes.","type":"text"}],"url":"\/documentation\/mapboxmaps\/mapcenteraltitudemode","navigatorTitle":[{"kind":"identifier","text":"MapCenterAltitudeMode"}],"title":"MapCenterAltitudeMode"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"type":"topic","url":"\/documentation\/mapboxmaps","role":"collection","kind":"symbol","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/centerAltitudeMode":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"centerAltitudeMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMMapCenterAltitudeMode","text":"MapCenterAltitudeMode"}],"url":"\/documentation\/mapboxmaps\/mapboxmap\/centeraltitudemode","title":"centerAltitudeMode","type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/centerAltitudeMode","abstract":[{"text":"Get\/set the map centerAltitudeMode that defines how the map center point should react to terrain elevation changes.","type":"text"},{"text":" ","type":"text"},{"text":"See ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapCenterAltitudeMode","isActive":true,"type":"reference"},{"text":" for options.","type":"text"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","url":"\/documentation\/overview","role":"collection","abstract":[],"kind":"article"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapCenterAltitudeMode\/title","value":"MBMMapCenterAltitudeMode","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapCenterAltitudeMode\/fragments","value":[{"kind":"identifier","text":"MBMMapCenterAltitudeMode"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapCenterAltitudeMode\/navigatorTitle","value":[{"text":"MBMMapCenterAltitudeMode","kind":"identifier"}],"op":"replace"}]}]}