{"abstract":[{"text":"The ","type":"text"},{"code":"ResourceRequest","type":"codeVoice"},{"text":" event allows client to observe resource requests made by a","type":"text"},{"text":" ","type":"text"},{"text":"map or snapshotter.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onResourceRequest","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps6SignalV","text":"Signal","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Signal","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMResourceRequest","text":"ResourceRequest","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequest","kind":"typeIdentifier"},{"text":"> { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onResourceRequest","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"MapboxMaps"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onResourceRequest"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Signal","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"ResourceRequest","preciseIdentifier":"c:objc(cs)MBMResourceRequest"},{"kind":"text","text":">"}],"role":"symbol","extendedModule":"MapboxMaps","externalID":"s:10MapboxMaps0A3MapC17onResourceRequestAA6SignalVySo011MBMResourceF0CGvp","roleHeading":"Instance Property","title":"onResourceRequest"},"seeAlsoSections":[{"anchor":"Map-events","title":"Map events","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onMapLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onMapLoadingError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleDataLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onCameraChanged","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onMapIdle","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onSourceAdded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onSourceRemoved","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onSourceDataLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleImageMissing","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleImageRemoveUnused","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onRenderFrameStarted","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onRenderFrameFinished"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/mapboxmap\/onresourcerequest"]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap"],["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/MapboxMapProtocol-Implementations"]]},"kind":"symbol","references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"kind":"article","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","url":"\/documentation\/overview","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/MapboxMapProtocol-Implementations":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/MapboxMapProtocol-Implementations","abstract":[],"type":"topic","kind":"article","title":"MapboxMapProtocol Implementations","url":"\/documentation\/mapboxmaps\/mapboxmap\/mapboxmapprotocol-implementations","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onSourceDataLoaded":{"title":"onSourceDataLoaded","role":"symbol","abstract":[{"text":"A source data has been loaded.","type":"text"},{"text":" ","type":"text"},{"text":"Event may be emitted synchronously in cases when source’s metadata is available when source is added to the style.","type":"text"}],"url":"\/documentation\/mapboxmaps\/mapboxmap\/onsourcedataloaded","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSourceDataLoaded"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10MapboxMaps6SignalV","kind":"typeIdentifier","text":"Signal"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)MBMSourceDataLoaded","kind":"typeIdentifier","text":"SourceDataLoaded"},{"kind":"text","text":">"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onSourceDataLoaded"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onCameraChanged":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onCameraChanged","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Signal","preciseIdentifier":"s:10MapboxMaps6SignalV","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"CameraChanged","preciseIdentifier":"c:objc(cs)MBMCameraChanged","kind":"typeIdentifier"},{"text":">","kind":"text"}],"type":"topic","abstract":[{"text":"The camera has changed. This event is emitted whenever the visible viewport","type":"text"},{"text":" ","type":"text"},{"text":"changes due to the MapView’s size changing or when the camera","type":"text"},{"text":" ","type":"text"},{"text":"is modified by calling camera methods. The event is emitted synchronously,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"so that an updated camera state can be fetched immediately."}],"title":"onCameraChanged","url":"\/documentation\/mapboxmaps\/mapboxmap\/oncamerachanged","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onCameraChanged"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onSourceAdded":{"type":"topic","role":"symbol","abstract":[{"text":"The source has been added with ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addSource(_:dataId:)","type":"reference"},{"text":"  or ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addSource(withId:properties:)","type":"reference"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"The event is emitted synchronously, therefore, it is possible to immediately","type":"text"},{"text":" ","type":"text"},{"text":"read added source’s properties.","type":"text"}],"url":"\/documentation\/mapboxmaps\/mapboxmap\/onsourceadded","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onSourceAdded","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSourceAdded"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10MapboxMaps6SignalV","kind":"typeIdentifier","text":"Signal"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)MBMSourceAdded","kind":"typeIdentifier","text":"SourceAdded"},{"kind":"text","text":">"}],"title":"onSourceAdded"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/beginGesture()":{"url":"\/documentation\/mapboxmaps\/mapboxmap\/begingesture()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"beginGesture"},{"kind":"text","text":"()"}],"type":"topic","title":"beginGesture()","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/beginGesture()","abstract":[{"text":"If implementing a custom gesture, call this method when the gesture begins.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onStyleImageRemoveUnused":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleImageRemoveUnused","abstract":[{"type":"text","text":"An image added to the style is no longer needed and can be removed using "},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/removeImage(withId:)","isActive":true},{"type":"text","text":"."}],"type":"topic","title":"onStyleImageRemoveUnused","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onStyleImageRemoveUnused","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Signal","preciseIdentifier":"s:10MapboxMaps6SignalV","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"StyleImageRemoveUnused","preciseIdentifier":"c:objc(cs)MBMStyleImageRemoveUnused","kind":"typeIdentifier"},{"text":">","kind":"text"}],"url":"\/documentation\/mapboxmaps\/mapboxmap\/onstyleimageremoveunused"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/removeSource(withId:)":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/stylemanager\/removesource(withid:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/removeSource(withId:)","role":"symbol","title":"removeSource(withId:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeSource"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Removes an existing style source."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/removeImage(withId:)":{"type":"topic","url":"\/documentation\/mapboxmaps\/stylemanager\/removeimage(withid:)","abstract":[{"type":"text","text":"Removes an image from the style."}],"kind":"symbol","role":"symbol","title":"removeImage(withId:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/removeImage(withId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/endAnimation()":{"url":"\/documentation\/mapboxmaps\/mapboxmap\/endanimation()","abstract":[{"text":"If implementing a custom animation mechanism, call this method when the animation ends.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/endAnimation()","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"endAnimation","kind":"identifier"},{"text":"()","kind":"text"}],"title":"endAnimation()"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onMapLoadingError":{"abstract":[{"text":"An error that has occurred while loading the Map. The ","type":"text"},{"code":"type","type":"codeVoice"},{"text":" property defines what resource could","type":"text"},{"text":" ","type":"text"},{"text":"not be loaded and the ","type":"text"},{"code":"message","type":"codeVoice"},{"text":" property will contain a descriptive error message.","type":"text"},{"text":" ","type":"text"},{"text":"In case of ","type":"text"},{"code":"source","type":"codeVoice"},{"text":" or ","type":"text"},{"code":"tile","type":"codeVoice"},{"text":" loading errors, ","type":"text"},{"code":"sourceID","type":"codeVoice"},{"text":" or ","type":"text"},{"code":"tileID","type":"codeVoice"},{"text":" will contain the identifier of the source failing.","type":"text"}],"url":"\/documentation\/mapboxmaps\/mapboxmap\/onmaploadingerror","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onMapLoadingError","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMapLoadingError"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10MapboxMaps6SignalV","kind":"typeIdentifier","text":"Signal"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)MBMMapLoadingError","kind":"typeIdentifier","text":"MapLoadingError"},{"kind":"text","text":">"}],"kind":"symbol","title":"onMapLoadingError"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/loadStyle(_:transition:completion:)-1ilz1":{"title":"loadStyle(_:transition:completion:)","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/loadstyle(_:transition:completion:)-1ilz1","abstract":[{"type":"text","text":"Loads a "},{"type":"codeVoice","code":"style"},{"type":"text","text":" from a StyleURI, calling a completion closure when the"},{"type":"text","text":" "},{"type":"text","text":"style is fully loaded or there has been an error during load."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadStyle","kind":"identifier"},{"text":"(","kind":"text"},{"text":"StyleURI","preciseIdentifier":"s:10MapboxMaps8StyleURIV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"transition","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TransitionOptions","preciseIdentifier":"s:10MapboxMaps17TransitionOptionsV","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/loadStyle(_:transition:completion:)-1ilz1"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","kind":"symbol","title":"MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/addSource(withId:properties:)":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Adds a new style source."}],"url":"\/documentation\/mapboxmaps\/stylemanager\/addsource(withid:properties:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addSource(withId:properties:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addSource","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"properties","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]) ","kind":"text"},{"text":"throws","kind":"keyword"}],"title":"addSource(withId:properties:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/addSource(_:dataId:)":{"url":"\/documentation\/mapboxmaps\/stylemanager\/addsource(_:dataid:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addSource(_:dataId:)","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Adds a "},{"type":"codeVoice","code":"source"},{"type":"text","text":" to the map"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addSource","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"Source","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SourceP"},{"text":", ","kind":"text"},{"text":"dataId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"}],"title":"addSource(_:dataId:)","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap":{"title":"MapboxMap","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapboxMap"}],"navigatorTitle":[{"kind":"identifier","text":"MapboxMap"}],"abstract":[{"text":"Provides access to the map model, including the camera, style, observable map events,","type":"text"},{"text":" ","type":"text"},{"text":"and querying rendered features.","type":"text"}],"type":"topic","url":"\/documentation\/mapboxmaps\/mapboxmap"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onStyleDataLoaded":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleDataLoaded","title":"onStyleDataLoaded","abstract":[{"type":"text","text":"The requested style data has been loaded. The "},{"type":"codeVoice","code":"type"},{"type":"text","text":" property defines what kind of style data has been loaded."},{"type":"text","text":" "},{"type":"text","text":"Event may be emitted synchronously, for example, when "},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/loadStyle(_:transition:completion:)-1ilz1","isActive":true},{"type":"text","text":" is used to load style."}],"url":"\/documentation\/mapboxmaps\/mapboxmap\/onstyledataloaded","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onStyleDataLoaded","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Signal","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"text":"<","kind":"text"},{"text":"StyleDataLoaded","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMStyleDataLoaded"},{"text":">","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onStyleImageMissing":{"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onStyleImageMissing","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Signal","preciseIdentifier":"s:10MapboxMaps6SignalV","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"StyleImageMissing","preciseIdentifier":"c:objc(cs)MBMStyleImageMissing","kind":"typeIdentifier"},{"text":">","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleImageMissing","abstract":[{"text":"A style has a missing image. This event is emitted when the map renders visible tiles and","type":"text"},{"text":" ","type":"text"},{"text":"one of the required images is missing in the sprite sheet. Subscriber has to provide the missing image","type":"text"},{"text":" ","type":"text"},{"text":"by calling ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addImage(_:id:sdf:contentInsets:)","type":"reference"},{"text":".","type":"text"}],"title":"onStyleImageMissing","type":"topic","url":"\/documentation\/mapboxmaps\/mapboxmap\/onstyleimagemissing"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/endGesture()":{"role":"symbol","type":"topic","abstract":[{"text":"If implementing a custom gesture, call this method when the gesture ends.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"endGesture","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/endGesture()","kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/endgesture()","title":"endGesture()"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onRenderFrameStarted":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onRenderFrameStarted"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10MapboxMaps6SignalV","kind":"typeIdentifier","text":"Signal"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)MBMRenderFrameStarted","kind":"typeIdentifier","text":"RenderFrameStarted"},{"kind":"text","text":">"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onRenderFrameStarted","abstract":[{"text":"The map started rendering a frame.","type":"text"}],"title":"onRenderFrameStarted","type":"topic","url":"\/documentation\/mapboxmaps\/mapboxmap\/onrenderframestarted"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/allSourceIdentifiers":{"url":"\/documentation\/mapboxmaps\/stylemanager\/allsourceidentifiers","abstract":[{"text":"The ordered list of the current style sources’ identifiers and types.","type":"text"}],"role":"symbol","type":"topic","kind":"symbol","title":"allSourceIdentifiers","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allSourceIdentifiers","kind":"identifier"},{"text":": [","kind":"text"},{"text":"SourceInfo","preciseIdentifier":"s:10MapboxMaps10SourceInfoV","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/allSourceIdentifiers"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onMapLoaded":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onMapLoaded","kind":"symbol","abstract":[{"type":"text","text":"The style has been fully loaded, and the map has rendered all visible tiles."}],"title":"onMapLoaded","role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onMapLoaded","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Signal","preciseIdentifier":"s:10MapboxMaps6SignalV","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"MapLoaded","preciseIdentifier":"c:objc(cs)MBMMapLoaded","kind":"typeIdentifier"},{"text":">","kind":"text"}],"url":"\/documentation\/mapboxmaps\/mapboxmap\/onmaploaded"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onSourceRemoved":{"kind":"symbol","role":"symbol","title":"onSourceRemoved","abstract":[{"text":"The source has been removed with ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/removeSource(withId:)","type":"reference"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"The event is emitted synchronously, thus, ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/allSourceIdentifiers","type":"reference"},{"text":" will be","type":"text"},{"text":" ","type":"text"},{"text":"in sync when the observer receives the notification.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSourceRemoved"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10MapboxMaps6SignalV","kind":"typeIdentifier","text":"Signal"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)MBMSourceRemoved","kind":"typeIdentifier","text":"SourceRemoved"},{"kind":"text","text":">"}],"url":"\/documentation\/mapboxmaps\/mapboxmap\/onsourceremoved","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onSourceRemoved"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onMapIdle":{"url":"\/documentation\/mapboxmaps\/mapboxmap\/onmapidle","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onMapIdle","abstract":[{"type":"text","text":"The map has entered the idle state. The map is in the idle state when there are no ongoing transitions"},{"type":"text","text":" "},{"type":"text","text":"and the map has rendered all requested non-volatile tiles. The event will not be emitted if animation is in progress (see "},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/beginAnimation()","isActive":true},{"type":"text","text":", "},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/endAnimation()","isActive":true},{"type":"text","text":")"},{"type":"text","text":" "},{"type":"text","text":"and \/ or gesture is in progress (see "},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/beginGesture()","isActive":true},{"type":"text","text":", "},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/endGesture()","isActive":true},{"type":"text","text":")."}],"type":"topic","title":"onMapIdle","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onMapIdle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Signal","preciseIdentifier":"s:10MapboxMaps6SignalV","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"MapIdle","preciseIdentifier":"c:objc(cs)MBMMapIdle","kind":"typeIdentifier"},{"text":">","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Signal":{"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Signal"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Signal","title":"Signal","url":"\/documentation\/mapboxmaps\/signal","navigatorTitle":[{"kind":"identifier","text":"Signal"}],"type":"topic","abstract":[{"type":"text","text":"Signal is a typed interface for observing arbitrary values over time."}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onResourceRequest":{"type":"topic","title":"onResourceRequest","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onResourceRequest","kind":"symbol","abstract":[{"text":"The ","type":"text"},{"code":"ResourceRequest","type":"codeVoice"},{"text":" event allows client to observe resource requests made by a","type":"text"},{"text":" ","type":"text"},{"text":"map or snapshotter.","type":"text"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/onresourcerequest","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onResourceRequest","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Signal","preciseIdentifier":"s:10MapboxMaps6SignalV","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"ResourceRequest","preciseIdentifier":"c:objc(cs)MBMResourceRequest","kind":"typeIdentifier"},{"text":">","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","title":"MapboxMap","kind":"article","type":"topic","abstract":[],"role":"collectionGroup","url":"\/documentation\/mapboxmaps\/mapboxmap-apis"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/beginAnimation()":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/beginAnimation()","url":"\/documentation\/mapboxmaps\/mapboxmap\/beginanimation()","type":"topic","title":"beginAnimation()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"beginAnimation","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","abstract":[{"text":"If implementing a custom animation mechanism, call this method when the animation begins.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onStyleLoaded":{"url":"\/documentation\/mapboxmaps\/mapboxmap\/onstyleloaded","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleLoaded","role":"symbol","kind":"symbol","abstract":[{"text":"The requested style has been fully loaded, including the style, specified sprite and sources’ metadata.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onStyleLoaded","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Signal","preciseIdentifier":"s:10MapboxMaps6SignalV","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"StyleLoaded","preciseIdentifier":"c:objc(cs)MBMStyleLoaded","kind":"typeIdentifier"},{"text":">","kind":"text"}],"title":"onStyleLoaded","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResourceRequest":{"title":"ResourceRequest","kind":"symbol","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ResourceRequest"},{"type":"text","text":" event allows the application to observe resource requests made by a "},{"type":"codeVoice","code":"map"},{"type":"text","text":" or "},{"type":"codeVoice","code":"map snapshotter"},{"type":"text","text":" object."}],"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ResourceRequest","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequest","url":"\/documentation\/mapboxmaps\/resourcerequest","navigatorTitle":[{"text":"ResourceRequest","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onRenderFrameFinished":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onRenderFrameFinished","abstract":[{"type":"text","text":"The map finished rendering a frame."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"renderMode"},{"type":"text","text":" property tells whether the map has all data ("},{"type":"codeVoice","code":"full"},{"type":"text","text":") required to render the visible viewport."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"needsRepaint"},{"type":"text","text":" property provides information about ongoing transitions that trigger map repaint."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"placementChanged"},{"type":"text","text":" property tells if the symbol placement has been changed in the visible viewport."}],"title":"onRenderFrameFinished","url":"\/documentation\/mapboxmaps\/mapboxmap\/onrenderframefinished","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onRenderFrameFinished","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Signal","preciseIdentifier":"s:10MapboxMaps6SignalV","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"RenderFrameFinished","preciseIdentifier":"c:objc(cs)MBMRenderFrameFinished","kind":"typeIdentifier"},{"text":">","kind":"text"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/addImage(_:id:sdf:contentInsets:)":{"url":"\/documentation\/mapboxmaps\/stylemanager\/addimage(_:id:sdf:contentinsets:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addImage(_:id:sdf:contentInsets:)","role":"symbol","abstract":[{"text":"Adds an image to be used in the style.","type":"text"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"id","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"sdf","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"contentInsets","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIEdgeInsets","preciseIdentifier":"c:@S@UIEdgeInsets","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"title":"addImage(_:id:sdf:contentInsets:)","type":"topic"}},"variantOverrides":[{"patch":[{"value":"MBMResourceRequest","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequest\/title"},{"value":[{"text":"MBMResourceRequest","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequest\/fragments"},{"value":[{"kind":"identifier","text":"MBMResourceRequest"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequest\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}