{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/mapcenteraltitudemode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/mapcenteraltitudemode"]}],"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapCenterAltitudeMode"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs"]]},"metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapCenterAltitudeMode"}],"symbolKind":"enum","modules":[{"name":"MapboxMaps"}],"externalID":"c:@E@MBMMapCenterAltitudeMode","role":"symbol","roleHeading":"Enumeration","title":"MapCenterAltitudeMode","navigatorTitle":[{"text":"MapCenterAltitudeMode","kind":"identifier"}]},"abstract":[{"text":"Defines how the map center point should react to terrain elevation changes.","type":"text"}],"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/s15BitwiseCopyableP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH","doc:\/\/com.mapbox.MapboxMaps\/SY","doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"],"kind":"relationships","type":"conformsTo"}],"topicSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapCenterAltitudeMode\/sea","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapCenterAltitudeMode\/terrain"],"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases"},{"title":"Initializers","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapCenterAltitudeMode\/init(rawValue:)"],"generated":true,"anchor":"Initializers"},{"title":"Default Implementations","generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapCenterAltitudeMode\/Equatable-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapCenterAltitudeMode\/RawRepresentable-Implementations"]}],"seeAlsoSections":[{"anchor":"MapboxMap","generated":true,"title":"MapboxMap","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraState","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBounds","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBoundsOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Projection","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBoundsZoom","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateInfo","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ContextMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometry","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometryConvertible"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapCenterAltitudeMode"}]}],"kind":"declarations"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapError":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapError","kind":"symbol","title":"MapError","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapError"}],"abstract":[{"text":"Type of errors thrown by the ","type":"text"},{"type":"codeVoice","code":"MapboxMap"},{"text":" APIs.","type":"text"}],"url":"\/documentation\/mapboxmaps\/maperror","role":"symbol","navigatorTitle":[{"text":"MapError","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapCenterAltitudeMode/Equatable-Implementations":{"role":"collectionGroup","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapCenterAltitudeMode\/Equatable-Implementations","url":"\/documentation\/mapboxmaps\/mapcenteraltitudemode\/equatable-implementations","type":"topic","title":"Equatable Implementations","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GlyphsRasterizationMode":{"abstract":[{"text":"Describes glyphs rasterization modes.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"GlyphsRasterizationMode","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/glyphsrasterizationmode","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GlyphsRasterizationMode"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode","title":"GlyphsRasterizationMode"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapboxMap"}],"title":"MapboxMap","url":"\/documentation\/mapboxmaps\/mapboxmap","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MapboxMap"}],"abstract":[{"type":"text","text":"Provides access to the map model, including the camera, style, observable map events,"},{"type":"text","text":" "},{"type":"text","text":"and querying rendered features."}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapCenterAltitudeMode/sea":{"title":"MapCenterAltitudeMode.sea","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapCenterAltitudeMode\/sea","url":"\/documentation\/mapboxmaps\/mapcenteraltitudemode\/sea","abstract":[{"type":"text","text":"Center altitude should disregard the underlying terrain elevation"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sea"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"MBMMapCenterAltitudeModeSea","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"kind":"article","url":"\/documentation\/mapboxmaps\/mapboxmap-apis","title":"MapboxMap","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","type":"topic","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapCenterAltitudeMode":{"type":"topic","title":"MapCenterAltitudeMode","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapCenterAltitudeMode","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapCenterAltitudeMode"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/mapcenteraltitudemode","navigatorTitle":[{"text":"MapCenterAltitudeMode","kind":"identifier"}],"abstract":[{"type":"text","text":"Defines how the map center point should react to terrain elevation changes."}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapCenterAltitudeMode/init(rawValue:)":{"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapCenterAltitudeMode\/init(rawValue:)","url":"\/documentation\/mapboxmaps\/mapcenteraltitudemode\/init(rawvalue:)","title":"init(rawValue:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"abstract":[]},"https://en.wikipedia.org/wiki/Web_Mercator_projection":{"type":"link","title":"Spherical Mercator","url":"https:\/\/en.wikipedia.org\/wiki\/Web_Mercator_projection","titleInlineContent":[{"type":"text","text":"Spherical Mercator"}],"identifier":"https:\/\/en.wikipedia.org\/wiki\/Web_Mercator_projection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateBoundsZoom":{"type":"topic","title":"CoordinateBoundsZoom","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBoundsZoom","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"CoordinateBoundsZoom","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/coordinateboundszoom","navigatorTitle":[{"kind":"identifier","text":"CoordinateBoundsZoom"}],"abstract":[{"text":"A coordinate bounds and zoom.","type":"text"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ContextMode":{"type":"topic","title":"ContextMode","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ContextMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ContextMode","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/contextmode","navigatorTitle":[{"kind":"identifier","text":"ContextMode"}],"abstract":[{"text":"Describes the map context mode.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"We can make some optimizations if we know that the drawing context is not shared with other code."}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapCenterAltitudeMode/RawRepresentable-Implementations":{"abstract":[],"role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapCenterAltitudeMode\/RawRepresentable-Implementations","type":"topic","title":"RawRepresentable Implementations","kind":"article","url":"\/documentation\/mapboxmaps\/mapcenteraltitudemode\/rawrepresentable-implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraBoundsOptions":{"title":"CameraBoundsOptions","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"CameraBoundsOptions","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Holds options to be used for setting camera bounds."}],"navigatorTitle":[{"kind":"identifier","text":"CameraBoundsOptions"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBoundsOptions","type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/cameraboundsoptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Projection":{"type":"topic","title":"Projection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Projection","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Projection","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/projection","navigatorTitle":[{"kind":"identifier","text":"Projection"}],"abstract":[{"type":"text","text":"A collection of "},{"identifier":"https:\/\/en.wikipedia.org\/wiki\/Web_Mercator_projection","type":"reference","isActive":true},{"text":" projection methods.","type":"text"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"url":"\/documentation\/mapboxmaps","kind":"symbol","title":"MapboxMaps","role":"collection","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateBounds":{"type":"topic","title":"CoordinateBounds","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CoordinateBounds"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/coordinatebounds","navigatorTitle":[{"kind":"identifier","text":"CoordinateBounds"}],"abstract":[{"text":"A rectangular area as measured on a two-dimensional map projection.","type":"text"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateInfo":{"type":"topic","title":"CoordinateInfo","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoordinateInfo"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/coordinateinfo","navigatorTitle":[{"kind":"identifier","text":"CoordinateInfo"}],"abstract":[{"type":"text","text":"Represents the coordinate information returned by the "},{"type":"codeVoice","code":"coordinateInfoForPixel"},{"text":" or ","type":"text"},{"code":"coordinatesInfoForPixels","type":"codeVoice"},{"text":" methods.","type":"text"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraState":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraState","kind":"symbol","title":"CameraState","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraState","kind":"identifier"}],"abstract":[],"url":"\/documentation\/mapboxmaps\/camerastate","role":"symbol","navigatorTitle":[{"text":"CameraState","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/SQ":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.mapbox.MapboxMaps/s15BitwiseCopyableP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s15BitwiseCopyableP","type":"unresolvable","title":"Swift.BitwiseCopyable"},"doc://com.mapbox.MapboxMaps/SH":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","kind":"article","url":"\/documentation\/overview","role":"collection"},"doc://com.mapbox.MapboxMaps/s8SendableP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraBounds":{"title":"CameraBounds","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CameraBounds"}],"role":"symbol","abstract":[{"text":"Holds information about camera bounds.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"CameraBounds"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBounds","type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/camerabounds"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderedQueryGeometry":{"title":"RenderedQueryGeometry","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"RenderedQueryGeometry","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"A geometry to define a portion of screen that should be queried for rendered features."}],"navigatorTitle":[{"kind":"identifier","text":"RenderedQueryGeometry"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometry","type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/renderedquerygeometry"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapCenterAltitudeMode/terrain":{"navigatorTitle":[{"text":"MBMMapCenterAltitudeModeTerrain","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapCenterAltitudeMode\/terrain","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"terrain","kind":"identifier"}],"role":"symbol","title":"MapCenterAltitudeMode.terrain","abstract":[{"type":"text","text":"Default, center altitude should match the terrain elevation"}],"type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/mapcenteraltitudemode\/terrain"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderedQueryGeometryConvertible":{"title":"RenderedQueryGeometryConvertible","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RenderedQueryGeometryConvertible"}],"role":"symbol","abstract":[{"type":"text","text":"A convenience protocol for automatic conversion to "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometry"},{"type":"text","text":"."}],"navigatorTitle":[{"text":"RenderedQueryGeometryConvertible","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometryConvertible","url":"\/documentation\/mapboxmaps\/renderedquerygeometryconvertible"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraOptions":{"title":"CameraOptions","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraOptions"}],"role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"CameraOptions"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraOptions","type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/cameraoptions"},"doc://com.mapbox.MapboxMaps/SY":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SY","type":"unresolvable","title":"Swift.RawRepresentable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"MBMMapCenterAltitudeMode"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"value":[{"text":"MBMMapCenterAltitudeMode","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MBMMapCenterAltitudeMode"}],"op":"replace"},{"path":"\/topicSections","value":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapCenterAltitudeMode\/sea","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapCenterAltitudeMode\/terrain"]}],"op":"replace"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBoundsZoom","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateInfo","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ContextMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode"],"generated":true,"anchor":"MapboxMap","title":"MapboxMap"}],"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBMMapCenterAltitudeMode"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/title","value":"MBMGlyphsRasterizationMode","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/fragments","value":[{"kind":"identifier","text":"MBMGlyphsRasterizationMode"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/navigatorTitle","value":[{"text":"MBMGlyphsRasterizationMode","kind":"identifier"}],"op":"replace"},{"value":"MBMMapCenterAltitudeModeSea","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapCenterAltitudeMode~1sea\/title"},{"value":[{"text":"MBMMapCenterAltitudeModeSea","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapCenterAltitudeMode~1sea\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapCenterAltitudeMode\/title","value":"MBMMapCenterAltitudeMode"},{"value":[{"text":"MBMMapCenterAltitudeMode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapCenterAltitudeMode\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapCenterAltitudeMode\/navigatorTitle","value":[{"text":"MBMMapCenterAltitudeMode","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBoundsZoom\/title","value":"MBMCoordinateBoundsZoom"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBoundsZoom\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMCoordinateBoundsZoom"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBoundsZoom\/navigatorTitle","value":[{"text":"MBMCoordinateBoundsZoom","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ContextMode\/title","value":"MBMContextMode"},{"value":[{"kind":"identifier","text":"MBMContextMode"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ContextMode\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBMContextMode"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ContextMode\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds\/title","value":"MBMCoordinateBounds"},{"value":[{"text":"MBMCoordinateBounds","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMCoordinateBounds"}]},{"op":"replace","value":"MBMCoordinateInfo","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateInfo\/title"},{"value":[{"text":"MBMCoordinateInfo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateInfo\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateInfo\/navigatorTitle","value":[{"text":"MBMCoordinateInfo","kind":"identifier"}]},{"value":"MBMMapCenterAltitudeModeTerrain","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapCenterAltitudeMode~1terrain\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapCenterAltitudeMode~1terrain\/fragments","value":[{"text":"MBMMapCenterAltitudeModeTerrain","kind":"identifier"}]}]}]}