{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithBytesNoCopy:","kind":"identifier"},{"kind":"text","text":"("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"bytesNoCopy"},{"text":" ","kind":"text"},{"kind":"identifier","text":"count:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":") ","kind":"text"},{"text":"count","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"deallocator:"},{"text":"(","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":" (^"},{"kind":"text","text":")("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":" "},{"kind":"internalParam","text":""},{"kind":"text","text":")) "},{"text":"deallocator","kind":"internalParam"},{"kind":"text","text":";"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/mbxdataref\/initwithbytesnocopy:count:deallocator:"]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXDataRef\/initWithBytesNoCopy:count:deallocator:"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/DataRef"]]},"metadata":{"externalID":"c:@M@MapboxCommon@objc(cs)MBXDataRef(im)initWithBytesNoCopy:count:deallocator:","navigatorTitle":[{"text":"initWithBytesNoCopy:count:deallocator:","kind":"identifier"}],"title":"initWithBytesNoCopy:count:deallocator:","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithBytesNoCopy:count:deallocator:"}],"roleHeading":"Instance Method","modules":[{"name":"MapboxCommon"}],"symbolKind":"method","role":"symbol"},"kind":"symbol","references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/DataRef":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DataRef"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/DataRef","url":"\/documentation\/mapboxcommon\/dataref","title":"DataRef","abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DataRef","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article","title":"MapboxMaps Documentation","url":"\/documentation\/overview","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXDataRef/initWithBytesNoCopy:count:deallocator:":{"url":"\/documentation\/mapboxcommon\/mbxdataref\/initwithbytesnocopy:count:deallocator:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithBytesNoCopy:count:deallocator:","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXDataRef\/initWithBytesNoCopy:count:deallocator:","type":"topic","navigatorTitle":[{"text":"initWithBytesNoCopy:count:deallocator:","kind":"identifier"}],"title":"initWithBytesNoCopy:count:deallocator:","role":"symbol","abstract":[],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"title":"MapboxCommon","kind":"symbol","url":"\/documentation\/mapboxcommon","abstract":[],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon"}},"variantOverrides":[{"patch":[{"value":"MBXDataRef","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1DataRef\/title"},{"value":[{"text":"MBXDataRef","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1DataRef\/fragments"},{"op":"replace","value":[{"text":"MBXDataRef","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1DataRef\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}