{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest"]]},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"HTTP defines a set of request methods to indicate the desired action to be performed for a given resource.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Specify desired method using this parameter."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"method"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@MBXHttpMethod","text":"HttpMethod","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpMethod"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/mapboxcommon\/httprequest\/method"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxcommon\/httprequest\/method"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"text":"method","kind":"identifier"}],"modules":[{"name":"MapboxCommon"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"method","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@MBXHttpMethod","kind":"typeIdentifier","text":"HttpMethod"}],"title":"method","symbolKind":"property","externalID":"c:objc(cs)MBXHttpRequest(py)method"},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest\/method","interfaceLanguage":"swift"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpMethod":{"navigatorTitle":[{"kind":"identifier","text":"HttpMethod"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpMethod","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"HttpMethod"}],"title":"HttpMethod","type":"topic","role":"symbol","abstract":[{"text":"HTTP defines a set of request methods to indicate the desired action to be performed for a given resource.","type":"text"}],"url":"\/documentation\/mapboxcommon\/httpmethod"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","type":"topic","title":"MapboxCommon","kind":"symbol","role":"collection","abstract":[],"url":"\/documentation\/mapboxcommon"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequest/method":{"type":"topic","abstract":[{"type":"text","text":"HTTP defines a set of request methods to indicate the desired action to be performed for a given resource."},{"text":" ","type":"text"},{"type":"text","text":"Specify desired method using this parameter."}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest\/method","url":"\/documentation\/mapboxcommon\/httprequest\/method","kind":"symbol","title":"method","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"method"},{"kind":"text","text":": "},{"text":"HttpMethod","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBXHttpMethod"}],"navigatorTitle":[{"kind":"identifier","text":"method"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","title":"MapboxMaps Documentation","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequest":{"url":"\/documentation\/mapboxcommon\/httprequest","abstract":[{"type":"text","text":"HttpRequest holds basic information for construction of an HTTP request"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"HttpRequest"}],"role":"symbol","title":"HttpRequest","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"HttpRequest","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"method","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"method"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"text":"MBXHttpMethod","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpMethod","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBXHttpMethod"},{"text":" ","kind":"text"},{"text":"method","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpMethod\/title","value":"MBXHttpMethod","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpMethod\/fragments","value":[{"kind":"identifier","text":"MBXHttpMethod"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpMethod\/navigatorTitle","value":[{"kind":"identifier","text":"MBXHttpMethod"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest~1method\/title","value":"method","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest~1method\/fragments","value":[{"text":"method","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest\/title","value":"MBXHttpRequest","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest\/fragments","value":[{"text":"MBXHttpRequest","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"MBXHttpRequest","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest\/navigatorTitle"}]}]}