{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegion"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegion\/setOfflineRegionDownloadStateFor(_:)","interfaceLanguage":"swift"},"abstract":[{"text":"Sets the download state of an offline region","type":"text"},{"type":"text","text":" "},{"text":"A region is either inactive (not downloading, but previously-downloaded","type":"text"},{"type":"text","text":" "},{"type":"text","text":"resources are available for use), or active (resources are being downloaded"},{"type":"text","text":" "},{"type":"text","text":"or will be downloaded, if necessary, when network access is available)."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setOfflineRegionDownloadStateFor"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"state","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionDownloadState","text":"OfflineRegionDownloadState","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMOfflineRegionDownloadState"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The new state to set."}],"type":"paragraph"}],"name":"state"}]},{"content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"If the region is already in the given state, this call is ignored."}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/mapboxmaps\/offlineregion\/setofflineregiondownloadstatefor(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/offlineregion\/setofflineregiondownloadstatefor(_:)"]}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setOfflineRegionDownloadStateFor","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"OfflineRegionDownloadState","preciseIdentifier":"c:@E@MBMOfflineRegionDownloadState"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"setOfflineRegionDownloadStateForState:","kind":"identifier"}],"title":"setOfflineRegionDownloadStateFor(_:)","modules":[{"name":"MapboxMaps"}],"symbolKind":"method","role":"symbol","platforms":[],"externalID":"c:objc(cs)MBMOfflineRegion(im)setOfflineRegionDownloadStateForState:"},"kind":"symbol","references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","title":"Core Maps API","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/coremaps","kind":"article","type":"topic","abstract":[{"text":"Maps rendering SDK also known as GL-Native","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","url":"\/documentation\/overview","title":"MapboxMaps Documentation","abstract":[],"kind":"article","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegion":{"deprecated":true,"kind":"symbol","title":"OfflineRegion","role":"symbol","abstract":[{"text":"An offline region represents an identifiable geographic region with optional metadata.","type":"text"}],"url":"\/documentation\/mapboxmaps\/offlineregion","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegion","navigatorTitle":[{"text":"OfflineRegion","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OfflineRegion","kind":"identifier"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","title":"MapboxMaps","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegion/setOfflineRegionDownloadStateFor(_:)":{"role":"symbol","navigatorTitle":[{"text":"setOfflineRegionDownloadStateForState:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setOfflineRegionDownloadStateFor","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@MBMOfflineRegionDownloadState","kind":"typeIdentifier","text":"OfflineRegionDownloadState"},{"text":")","kind":"text"}],"title":"setOfflineRegionDownloadStateFor(_:)","url":"\/documentation\/mapboxmaps\/offlineregion\/setofflineregiondownloadstatefor(_:)","type":"topic","deprecated":true,"abstract":[{"text":"Sets the download state of an offline region","type":"text"},{"type":"text","text":" "},{"type":"text","text":"A region is either inactive (not downloading, but previously-downloaded"},{"text":" ","type":"text"},{"text":"resources are available for use), or active (resources are being downloaded","type":"text"},{"text":" ","type":"text"},{"text":"or will be downloaded, if necessary, when network access is available).","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegion\/setOfflineRegionDownloadStateFor(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Offline":{"abstract":[],"role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","title":"Offline Support","type":"topic","kind":"article","url":"\/documentation\/mapboxmaps\/offline"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionDownloadState":{"deprecated":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionDownloadState","title":"OfflineRegionDownloadState","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OfflineRegionDownloadState"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"OfflineRegionDownloadState","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/offlineregiondownloadstate","kind":"symbol","type":"topic","abstract":[{"text":"Describes the download state of a region.","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"setOfflineRegionDownloadStateForState:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setOfflineRegionDownloadStateForState:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"text":"setOfflineRegionDownloadStateForState:","kind":"identifier"},{"kind":"text","text":"("},{"text":"MBMOfflineRegionDownloadState","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionDownloadState","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMOfflineRegionDownloadState"},{"text":") ","kind":"text"},{"text":"state","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"state","content":[{"type":"paragraph","inlineContent":[{"text":"The new state to set.","type":"text"}]}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegion\/title","op":"replace","value":"MBMOfflineRegion"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegion\/fragments","op":"replace","value":[{"text":"MBMOfflineRegion","kind":"identifier"}]},{"value":[{"text":"MBMOfflineRegion","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegion\/navigatorTitle","op":"replace"},{"value":"setOfflineRegionDownloadStateForState:","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegion~1setOfflineRegionDownloadStateFor(_:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegion~1setOfflineRegionDownloadStateFor(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setOfflineRegionDownloadStateForState:","kind":"identifier"}],"op":"replace"},{"value":"MBMOfflineRegionDownloadState","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionDownloadState\/title","op":"replace"},{"op":"replace","value":[{"text":"MBMOfflineRegionDownloadState","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionDownloadState\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionDownloadState\/navigatorTitle","value":[{"kind":"identifier","text":"MBMOfflineRegionDownloadState"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}