{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap"]]},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/collectPerformanceStatistics(_:callback:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Collects CPU and GPU resource usage, as well as timings of layers and rendering groups, over a user-configurable sampling duration."},{"type":"text","text":" "},{"text":"Use the collected information to identify layers or rendering groups that may be performing poorly.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"collectPerformanceStatistics","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PerformanceStatisticsOptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatisticsOptions","preciseIdentifier":"c:objc(cs)MBMPerformanceStatisticsOptions"},{"kind":"text","text":", "},{"text":"callback","kind":"externalParam"},{"kind":"text","text":": "},{"text":"@escaping","kind":"keyword"},{"kind":"text","text":" ("},{"preciseIdentifier":"c:objc(cs)MBMPerformanceStatistics","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatistics","text":"PerformanceStatistics","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":") -> ","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AnyCancelable","text":"AnyCancelable","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps13AnyCancelableC"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AnyCancelable","type":"reference","isActive":true},{"text":" object that can be used to cancel performance statistics collection.","type":"text"}]}]},{"content":[{"text":"Discussion","level":2,"anchor":"discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"Use "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatisticsOptions","isActive":true,"type":"reference"},{"type":"text","text":" to configure the following collection behaviours:"},{"text":" ","type":"text"},{"text":"- Which types of sampling to perform, whether cumulative, per-frame, or both.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"- Duration of sampling in milliseconds. A value of 0 forces the collection of performance statistics every frame."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The statistics collection can be canceled using the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AnyCancelable"},{"type":"text","text":" object returned by this function, note that if the token goes out of the scope it’s deinitialized and thus canceled. Canceling collection will prevent the"},{"text":" ","type":"text"},{"text":"callback from being called. Collection can be restarted by calling ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/collectPerformanceStatistics(_:callback:)","isActive":true},{"text":" again to obtain a new ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AnyCancelable","type":"reference"},{"type":"text","text":" object."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The callback function will be called every time the configured sampling duration "},{"isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatisticsOptions\/samplingDurationMillis","type":"reference"},{"text":" has elapsed.","type":"text"}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/mapboxmap\/collectperformancestatistics(_:callback:)"]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"title":"collectPerformanceStatistics(_:callback:)","role":"symbol","symbolKind":"method","roleHeading":"Instance Method","tags":[{"text":"SPI","type":"spi"}],"modules":[{"name":"MapboxMaps"}],"externalID":"s:10MapboxMaps0A3MapC28collectPerformanceStatistics_8callbackAA13AnyCancelableCSo014MBMPerformanceF7OptionsC_ySo0jF0CctF","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"collectPerformanceStatistics","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PerformanceStatisticsOptions","preciseIdentifier":"c:objc(cs)MBMPerformanceStatisticsOptions","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"callback","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMPerformanceStatistics","text":"PerformanceStatistics"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":") -> ","kind":"text"},{"text":"AnyCancelable","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps13AnyCancelableC"}]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AnyCancelable":{"title":"AnyCancelable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AnyCancelable","abstract":[{"type":"text","text":"A Cancellable object that automatically cancels on deinit."}],"navigatorTitle":[{"text":"AnyCancelable","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/anycancelable","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AnyCancelable","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/collectPerformanceStatistics(_:callback:)":{"type":"topic","url":"\/documentation\/mapboxmaps\/mapboxmap\/collectperformancestatistics(_:callback:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"collectPerformanceStatistics"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMPerformanceStatisticsOptions","text":"PerformanceStatisticsOptions"},{"text":", ","kind":"text"},{"text":"callback","kind":"externalParam"},{"kind":"text","text":": ("},{"preciseIdentifier":"c:objc(cs)MBMPerformanceStatistics","kind":"typeIdentifier","text":"PerformanceStatistics"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps13AnyCancelableC","text":"AnyCancelable"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/collectPerformanceStatistics(_:callback:)","role":"symbol","abstract":[{"text":"Collects CPU and GPU resource usage, as well as timings of layers and rendering groups, over a user-configurable sampling duration.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Use the collected information to identify layers or rendering groups that may be performing poorly."}],"tags":[{"text":"SPI","type":"spi"}],"kind":"symbol","title":"collectPerformanceStatistics(_:callback:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PerformanceStatistics":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatistics","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PerformanceStatistics","kind":"identifier"}],"title":"PerformanceStatistics","type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/performancestatistics","abstract":[{"text":"The performance statistics collected at the end of the sampling duration.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"PerformanceStatistics"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"url":"\/documentation\/mapboxmaps\/mapboxmap-apis","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","abstract":[],"title":"MapboxMap","kind":"article","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PerformanceStatisticsOptions/samplingDurationMillis":{"navigatorTitle":[{"text":"samplingDurationMillis","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"samplingDurationMillis","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"url":"\/documentation\/mapboxmaps\/performancestatisticsoptions\/samplingdurationmillis","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatisticsOptions\/samplingDurationMillis","kind":"symbol","abstract":[{"type":"text","text":"The minimum elapsed time required before performance statistics become available. It’s important to note that the actual"},{"type":"text","text":" "},{"text":"collection interval may exceed this duration since statistics are aggregated during render calls. The effective collection","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"interval can be observed through the "},{"type":"codeVoice","code":"PerformanceStatistics"},{"text":" instance.","type":"text"}],"title":"samplingDurationMillis","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"url":"\/documentation\/mapboxmaps","title":"MapboxMaps","type":"topic","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap":{"kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/mapboxmap","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapboxMap"}],"title":"MapboxMap","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MapboxMap"}],"abstract":[{"text":"Provides access to the map model, including the camera, style, observable map events,","type":"text"},{"text":" ","type":"text"},{"text":"and querying rendered features.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PerformanceStatisticsOptions":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatisticsOptions","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PerformanceStatisticsOptions"}],"title":"PerformanceStatisticsOptions","type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/performancestatisticsoptions","abstract":[{"text":"Options for the following statistics collection behaviors:","type":"text"}],"navigatorTitle":[{"text":"PerformanceStatisticsOptions","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatistics\/title","value":"MBMPerformanceStatistics","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatistics\/fragments","value":[{"text":"MBMPerformanceStatistics","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatistics\/navigatorTitle","value":[{"text":"MBMPerformanceStatistics","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatisticsOptions~1samplingDurationMillis\/title","op":"replace","value":"samplingDurationMillis"},{"value":[{"text":"samplingDurationMillis","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatisticsOptions~1samplingDurationMillis\/fragments","op":"replace"},{"op":"replace","value":"MBMPerformanceStatisticsOptions","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatisticsOptions\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatisticsOptions\/fragments","value":[{"kind":"identifier","text":"MBMPerformanceStatisticsOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatisticsOptions\/navigatorTitle","value":[{"text":"MBMPerformanceStatisticsOptions","kind":"identifier"}]}]}]}