{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@discardableResult","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getGeoJsonClusterChildren"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forSourceId"},{"kind":"text","text":" "},{"kind":"internalParam","text":"sourceId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"feature"},{"kind":"text","text":": "},{"text":"Feature","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Feature","preciseIdentifier":"s:10MapboxMaps7Featurea"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"keyword","text":"@escaping"},{"kind":"text","text":" ("},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMFeatureExtensionValue","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeatureExtensionValue","kind":"typeIdentifier","text":"FeatureExtensionValue"},{"text":", any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":">) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":") -> any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)MBXCancelable","text":"Cancelable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Cancelable","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"sourceId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The identifier of the source to query."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Feature to look for in the query.","type":"text"}]}],"name":"feature"},{"name":"completion","content":[{"inlineContent":[{"text":"The result could be a feature extension value containing","type":"text"},{"type":"text","text":" "},{"type":"text","text":"either a value (expansion-zoom) or a feature collection (children"},{"type":"text","text":" "},{"type":"text","text":"or leaves). An error is passed if the operation was not successful."}],"type":"paragraph"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap"],["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/MapFeatureQueryable-Implementations"]]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","abstract":[{"text":"Returns the children (original points or clusters) of a cluster (on the next zoom level)","type":"text"},{"type":"text","text":" "},{"text":"given its id (cluster_id value from feature properties) from a GeoJSON source.","type":"text"}],"metadata":{"roleHeading":"Instance Method","modules":[{"name":"MapboxMaps"}],"title":"getGeoJsonClusterChildren(forSourceId:feature:completion:)","symbolKind":"method","extendedModule":"MapboxMaps","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getGeoJsonClusterChildren","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forSourceId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"feature","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Feature","preciseIdentifier":"s:10MapboxMaps7Featurea"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"preciseIdentifier":"s:s6ResultO","text":"Result","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)MBMFeatureExtensionValue","text":"FeatureExtensionValue","kind":"typeIdentifier"},{"text":", any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":") -> any "},{"preciseIdentifier":"c:objc(pl)MBXCancelable","text":"Cancelable","kind":"typeIdentifier"}],"externalID":"s:10MapboxMaps0A3MapC25getGeoJsonClusterChildren11forSourceId7feature10completionSo13MBXCancelable_pSS_4Turf7FeatureVys6ResultOySo24MBMFeatureExtensionValueCs5Error_pGctF","role":"symbol"},"variants":[{"paths":["\/documentation\/mapboxmaps\/mapboxmap\/getgeojsonclusterchildren(forsourceid:feature:completion:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/getGeoJsonClusterChildren(forSourceId:feature:completion:)","interfaceLanguage":"swift"},"seeAlsoSections":[{"generated":true,"anchor":"Querying-map-features","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/queryRenderedFeatures(with:options:completion:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/getGeoJsonClusterLeaves(forSourceId:feature:limit:offset:completion:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/getGeoJsonClusterExpansionZoom(forSourceId:feature:completion:)"],"title":"Querying map features"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/queryRenderedFeatures(with:options:completion:)":{"title":"queryRenderedFeatures(with:options:completion:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/queryRenderedFeatures(with:options:completion:)","url":"\/documentation\/mapboxmaps\/mapboxmap\/queryrenderedfeatures(with:options:completion:)","abstract":[{"text":"Queries the map for rendered features.","type":"text"}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"queryRenderedFeatures","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"text":": some ","kind":"text"},{"text":"RenderedQueryGeometryConvertible","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps32RenderedQueryGeometryConvertibleP"},{"text":", ","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMRenderedQueryOptions","text":"RenderedQueryOptions","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"text":"<[","kind":"text"},{"kind":"typeIdentifier","text":"QueriedRenderedFeature","preciseIdentifier":"c:objc(cs)MBMQueriedRenderedFeature"},{"text":"], any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":">) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":") -> any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)MBXCancelable","text":"Cancelable","kind":"typeIdentifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/MapFeatureQueryable-Implementations":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/MapFeatureQueryable-Implementations","url":"\/documentation\/mapboxmaps\/mapboxmap\/mapfeaturequeryable-implementations","kind":"article","type":"topic","abstract":[],"role":"collectionGroup","title":"MapFeatureQueryable Implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/getGeoJsonClusterLeaves(forSourceId:feature:limit:offset:completion:)":{"title":"getGeoJsonClusterLeaves(forSourceId:feature:limit:offset:completion:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/getGeoJsonClusterLeaves(forSourceId:feature:limit:offset:completion:)","url":"\/documentation\/mapboxmaps\/mapboxmap\/getgeojsonclusterleaves(forsourceid:feature:limit:offset:completion:)","abstract":[{"type":"text","text":"Returns all the leaves (original points) of a cluster (given its cluster_id) from a GeoJSON source, with pagination support: limit is the number of leaves"},{"text":" ","type":"text"},{"type":"text","text":"to return (set to Infinity for all points), and offset is the amount of points to skip (for pagination)."}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getGeoJsonClusterLeaves","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forSourceId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"feature","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps7Featurea","text":"Feature","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"limit","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt64","preciseIdentifier":"s:s6UInt64V"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"offset"},{"text":": ","kind":"text"},{"text":"UInt64","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:s6ResultO","text":"Result","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"text":"FeatureExtensionValue","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMFeatureExtensionValue"},{"text":", any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":">) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":") -> any ","kind":"text"},{"text":"Cancelable","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MBXCancelable"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"url":"\/documentation\/mapboxmaps\/mapboxmap-apis","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","abstract":[],"title":"MapboxMap","kind":"article","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/getGeoJsonClusterExpansionZoom(forSourceId:feature:completion:)":{"title":"getGeoJsonClusterExpansionZoom(forSourceId:feature:completion:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/getGeoJsonClusterExpansionZoom(forSourceId:feature:completion:)","url":"\/documentation\/mapboxmaps\/mapboxmap\/getgeojsonclusterexpansionzoom(forsourceid:feature:completion:)","abstract":[{"type":"text","text":"Returns the zoom on which the cluster expands into several children (useful for “click to zoom” feature)"},{"text":" ","type":"text"},{"type":"text","text":"given the cluster’s cluster_id (cluster_id value from feature properties) from a GeoJSON source."}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getGeoJsonClusterExpansionZoom","kind":"identifier"},{"kind":"text","text":"("},{"text":"forSourceId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"feature"},{"text":": ","kind":"text"},{"text":"Feature","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps7Featurea"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)MBMFeatureExtensionValue","kind":"typeIdentifier","text":"FeatureExtensionValue"},{"text":", any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":">) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":") -> any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)MBXCancelable","kind":"typeIdentifier","text":"Cancelable"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FeatureExtensionValue":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeatureExtensionValue","url":"\/documentation\/mapboxmaps\/featureextensionvalue","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FeatureExtensionValue"}],"abstract":[{"text":"A value or a collection of a feature extension.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"FeatureExtensionValue","kind":"identifier"}],"title":"FeatureExtensionValue"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/getGeoJsonClusterChildren(forSourceId:feature:completion:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/getGeoJsonClusterChildren(forSourceId:feature:completion:)","url":"\/documentation\/mapboxmaps\/mapboxmap\/getgeojsonclusterchildren(forsourceid:feature:completion:)","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getGeoJsonClusterChildren","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forSourceId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"feature"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Feature","preciseIdentifier":"s:10MapboxMaps7Featurea"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"preciseIdentifier":"s:s6ResultO","text":"Result","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"FeatureExtensionValue","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMFeatureExtensionValue"},{"text":", any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":">) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":") -> any "},{"preciseIdentifier":"c:objc(pl)MBXCancelable","text":"Cancelable","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Returns the children (original points or clusters) of a cluster (on the next zoom level)"},{"type":"text","text":" "},{"text":"given its id (cluster_id value from feature properties) from a GeoJSON source.","type":"text"}],"role":"symbol","title":"getGeoJsonClusterChildren(forSourceId:feature:completion:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap":{"kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/mapboxmap","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapboxMap"}],"title":"MapboxMap","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MapboxMap"}],"abstract":[{"text":"Provides access to the map model, including the camera, style, observable map events,","type":"text"},{"text":" ","type":"text"},{"text":"and querying rendered features.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Feature":{"title":"Feature","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Feature","url":"\/documentation\/mapboxmaps\/feature","abstract":[{"text":"An object representing a spatially bounded geometry.","type":"text"}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Feature"}],"navigatorTitle":[{"text":"Feature","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Cancelable":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Cancelable","url":"\/documentation\/mapboxcommon\/cancelable","kind":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"Cancelable","kind":"identifier"}],"abstract":[{"text":"Allows to cancel the associated asynchronous operation","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"Cancelable","kind":"identifier"}],"title":"Cancelable"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"url":"\/documentation\/mapboxmaps","title":"MapboxMaps","type":"topic","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"MBMFeatureExtensionValue","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeatureExtensionValue\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeatureExtensionValue\/fragments","value":[{"text":"MBMFeatureExtensionValue","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeatureExtensionValue\/navigatorTitle","value":[{"kind":"identifier","text":"MBMFeatureExtensionValue"}],"op":"replace"},{"op":"replace","value":"MBXCancelable","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/title"},{"op":"replace","value":[{"text":"MBXCancelable","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/navigatorTitle","value":[{"kind":"identifier","text":"MBXCancelable"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}