{"metadata":{"modules":[{"name":"MapboxMaps"}],"symbolKind":"property","roleHeading":"Instance Property","fragments":[{"kind":"identifier","text":"graphicsProgramsCreationTimeMillis"}],"navigatorTitle":[{"kind":"identifier","text":"graphicsProgramsCreationTimeMillis"}],"externalID":"c:objc(cs)MBMCumulativeRenderingStatistics(py)graphicsProgramsCreationTimeMillis","title":"graphicsProgramsCreationTimeMillis","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CumulativeRenderingStatistics"]]},"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"The total amount of time spent on all graphics pipeline program creation, in milliseconds."}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/mbmcumulativerenderingstatistics\/graphicsprogramscreationtimemillis"]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCumulativeRenderingStatistics\/graphicsProgramsCreationTimeMillis","interfaceLanguage":"occ"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"graphicsProgramsCreationTimeMillis","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","abstract":[],"kind":"article","role":"collection","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMCumulativeRenderingStatistics/graphicsProgramsCreationTimeMillis":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCumulativeRenderingStatistics\/graphicsProgramsCreationTimeMillis","title":"graphicsProgramsCreationTimeMillis","type":"topic","url":"\/documentation\/mapboxmaps\/mbmcumulativerenderingstatistics\/graphicsprogramscreationtimemillis","role":"symbol","kind":"symbol","abstract":[{"text":"The total amount of time spent on all graphics pipeline program creation, in milliseconds.","type":"text"}],"fragments":[{"kind":"identifier","text":"graphicsProgramsCreationTimeMillis"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Performance":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","type":"topic","url":"\/documentation\/mapboxmaps\/performance","title":"Performance and investigations","kind":"article","role":"collectionGroup","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CumulativeRenderingStatistics":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CumulativeRenderingStatistics","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CumulativeRenderingStatistics","kind":"identifier"}],"abstract":[],"title":"CumulativeRenderingStatistics","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CumulativeRenderingStatistics"}],"url":"\/documentation\/mapboxmaps\/cumulativerenderingstatistics","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MBMCumulativeRenderingStatistics","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CumulativeRenderingStatistics\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CumulativeRenderingStatistics\/fragments","op":"replace","value":[{"text":"MBMCumulativeRenderingStatistics","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"MBMCumulativeRenderingStatistics"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CumulativeRenderingStatistics\/navigatorTitle"}]}]}