{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/locationprovider\/addlocationobserver(for:)"]},{"paths":["\/documentation\/mapboxcommon\/locationprovider\/addlocationobserver(for:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"type":"text","text":"Registers an observer in this instance of LocationProvider."},{"text":" ","type":"text"},{"type":"text","text":"One instance of LocationProvider can have more than one observer."},{"type":"text","text":" "},{"text":"It is expected that LocationProvider will not start until an","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"observer is added."}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"addLocationObserver","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"text":"observer","kind":"internalParam"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:objc(pl)MBXLocationObserver","kind":"typeIdentifier","text":"LocationObserver","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationObserver"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"An observer to add.","type":"text"}]}],"name":"observer"}],"kind":"parameters"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"addLocationObserverForObserver:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addLocationObserver"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"for"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","text":"LocationObserver","preciseIdentifier":"c:objc(pl)MBXLocationObserver"},{"text":")","kind":"text"}],"role":"symbol","modules":[{"name":"MapboxCommon"}],"externalID":"c:objc(pl)MBXLocationProvider(im)addLocationObserverForObserver:","roleHeading":"Instance Method","required":true,"symbolKind":"method","title":"addLocationObserver(for:)"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider\/addLocationObserver(for:)"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","abstract":[],"kind":"article","url":"\/documentation\/overview","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","role":"collection","kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationObserver":{"url":"\/documentation\/mapboxcommon\/locationobserver","role":"symbol","abstract":[{"text":"Observer for getting updates from a LocationProvider.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationObserver","kind":"symbol","navigatorTitle":[{"text":"LocationObserver","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"LocationObserver","kind":"identifier"}],"title":"LocationObserver","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationProvider":{"navigatorTitle":[{"text":"LocationProvider","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationProvider","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Location provider that provides locations"}],"title":"LocationProvider","url":"\/documentation\/mapboxcommon\/locationprovider"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationProvider/addLocationObserver(for:)":{"title":"addLocationObserver(for:)","abstract":[{"type":"text","text":"Registers an observer in this instance of LocationProvider."},{"text":" ","type":"text"},{"type":"text","text":"One instance of LocationProvider can have more than one observer."},{"type":"text","text":" "},{"text":"It is expected that LocationProvider will not start until an","type":"text"},{"type":"text","text":" "},{"text":"observer is added.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider\/addLocationObserver(for:)","required":true,"url":"\/documentation\/mapboxcommon\/locationprovider\/addlocationobserver(for:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addLocationObserver"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MBXLocationObserver","text":"LocationObserver"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"addLocationObserverForObserver:","kind":"identifier"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Location-APIs":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","title":"Location","kind":"article","url":"\/documentation\/mapboxmaps\/location-apis","type":"topic","role":"collectionGroup","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"addLocationObserverForObserver:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addLocationObserverForObserver:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"addLocationObserverForObserver:","kind":"identifier"},{"kind":"text","text":"("},{"text":"id<MBXLocationObserver>","preciseIdentifier":"c:Qoobjc(pl)MBXLocationObserver","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"observer"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":{"kind":"parameters","parameters":[{"name":"observer","content":[{"type":"paragraph","inlineContent":[{"text":"An observer to add.","type":"text"}]}]}]},"path":"\/primaryContentSections\/1","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/title","value":"MBXLocationObserver"},{"value":[{"text":"MBXLocationObserver","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/navigatorTitle","value":[{"text":"MBXLocationObserver","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/title","op":"replace","value":"MBXLocationProvider"},{"op":"replace","value":[{"text":"MBXLocationProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/navigatorTitle","value":[{"text":"MBXLocationProvider","kind":"identifier"}]},{"value":"addLocationObserverForObserver:","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider~1addLocationObserver(for:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider~1addLocationObserver(for:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"addLocationObserverForObserver:","kind":"identifier"}]}]}]}