{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"anchorConfig","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ViewAnnotationAnchorConfig","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMViewAnnotationAnchorConfig","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchorConfig"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"sections":[],"metadata":{"symbolKind":"property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"anchorConfig"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMViewAnnotationAnchorConfig","text":"ViewAnnotationAnchorConfig"},{"text":"?","kind":"text"}],"title":"anchorConfig","externalID":"s:10MapboxMaps14ViewAnnotationC12anchorConfigSo07MBMViewd6AnchorF0CSgvp","modules":[{"name":"MapboxMaps"}],"roleHeading":"Instance Property"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Currently selected anchor configuration."}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/anchorConfig","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/viewannotation\/anchorconfig"]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationAnchorConfig":{"url":"\/documentation\/mapboxmaps\/viewannotationanchorconfig","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ViewAnnotationAnchorConfig"}],"navigatorTitle":[{"kind":"identifier","text":"ViewAnnotationAnchorConfig"}],"abstract":[{"type":"text","text":"Represents a specific setting for a view annotation anchor."}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchorConfig","title":"ViewAnnotationAnchorConfig","type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotation/anchorConfig":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/anchorConfig","title":"anchorConfig","abstract":[{"type":"text","text":"Currently selected anchor configuration."}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"anchorConfig"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMViewAnnotationAnchorConfig","text":"ViewAnnotationAnchorConfig"},{"kind":"text","text":"?"}],"url":"\/documentation\/mapboxmaps\/viewannotation\/anchorconfig","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","role":"collection","url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"title":"MapboxMaps","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotation":{"navigatorTitle":[{"kind":"identifier","text":"ViewAnnotation"}],"title":"ViewAnnotation","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ViewAnnotation","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/viewannotation","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Creates a view annotation."}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchorConfig\/title","op":"replace","value":"MBMViewAnnotationAnchorConfig"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchorConfig\/fragments","value":[{"text":"MBMViewAnnotationAnchorConfig","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchorConfig\/navigatorTitle","value":[{"kind":"identifier","text":"MBMViewAnnotationAnchorConfig"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}