{"abstract":[{"text":"A list of anchor configurations available.","type":"text"}],"sections":[],"variants":[{"paths":["\/documentation\/mapboxmaps\/viewannotation\/variableanchors"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"variableAnchors","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchorConfig","preciseIdentifier":"c:objc(cs)MBMViewAnnotationAnchorConfig","text":"ViewAnnotationAnchorConfig"},{"text":"] { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"anchor":"discussion","text":"Discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"The annotation will automatically pick the first best anchor position depending on position"},{"text":" ","type":"text"},{"text":"relative to other elements on the map.","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"If not specified, the annotation will be placed in center."}]},{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/onAnchorChanged","type":"reference"},{"text":" is called when the effective position is updated:","type":"text"}]},{"syntax":"swift","type":"codeListing","code":["let view = CustomView()","let annotation = ViewAnnotation(","    annotatedFeature: .layerFeature(layerId: \"route-line\", featureId: \"sf-la\"),","    view: view)","","\/\/ Allow top and bottom anchor directions.","annotation.variableAnchors = [","  ViewAnnotationAnchorConfig(anchor: .top),","  ViewAnnotationAnchorConfig(anchor: .bottom)","]","","annotation.onAnchorChanged = { config in","    \/\/ Update the view's anchor to the newly picked one.","    view.anchor = config.anchor","}"]}]}],"metadata":{"title":"variableAnchors","modules":[{"name":"MapboxMaps"}],"roleHeading":"Instance Property","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"variableAnchors","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)MBMViewAnnotationAnchorConfig","text":"ViewAnnotationAnchorConfig","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"symbolKind":"property","externalID":"s:10MapboxMaps14ViewAnnotationC15variableAnchorsSaySo07MBMViewD12AnchorConfigCGvp"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/variableAnchors"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/View-Annotations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotation/anchorConfig":{"title":"anchorConfig","type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/viewannotation\/anchorconfig","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/anchorConfig","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"anchorConfig","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ViewAnnotationAnchorConfig","preciseIdentifier":"c:objc(cs)MBMViewAnnotationAnchorConfig"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Currently selected anchor configuration."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotation/onAnchorChanged":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onAnchorChanged","kind":"identifier"},{"kind":"text","text":": (("},{"preciseIdentifier":"c:objc(cs)MBMViewAnnotationAnchorConfig","kind":"typeIdentifier","text":"ViewAnnotationAnchorConfig"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?","kind":"text"}],"url":"\/documentation\/mapboxmaps\/viewannotation\/onanchorchanged","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/onAnchorChanged","abstract":[{"type":"text","text":"Called when "},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/anchorConfig","isActive":true},{"type":"text","text":" is changed."}],"title":"onAnchorChanged"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotation/variableAnchors":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/variableAnchors","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"variableAnchors","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMViewAnnotationAnchorConfig","text":"ViewAnnotationAnchorConfig","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"url":"\/documentation\/mapboxmaps\/viewannotation\/variableanchors","role":"symbol","kind":"symbol","title":"variableAnchors","abstract":[{"type":"text","text":"A list of anchor configurations available."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationAnchorConfig":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ViewAnnotationAnchorConfig"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchorConfig","url":"\/documentation\/mapboxmaps\/viewannotationanchorconfig","title":"ViewAnnotationAnchorConfig","role":"symbol","abstract":[{"type":"text","text":"Represents a specific setting for a view annotation anchor."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ViewAnnotationAnchorConfig"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotation":{"abstract":[{"type":"text","text":"Creates a view annotation."}],"type":"topic","title":"ViewAnnotation","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ViewAnnotation","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation","navigatorTitle":[{"text":"ViewAnnotation","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/viewannotation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/View-Annotations":{"title":"View Annotations","url":"\/documentation\/mapboxmaps\/view-annotations","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/View-Annotations","abstract":[],"kind":"article","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/mapboxmaps","title":"MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","abstract":[],"kind":"article","role":"collection","url":"\/documentation\/overview"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"MBMViewAnnotationAnchorConfig","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchorConfig\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBMViewAnnotationAnchorConfig"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchorConfig\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchorConfig\/navigatorTitle","value":[{"kind":"identifier","text":"MBMViewAnnotationAnchorConfig"}]}]}]}