{"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"The "},{"code":"SourceDataLoaded","type":"codeVoice"},{"text":" event is emitted when source data is loaded.","type":"text"}],"metadata":{"modules":[{"name":"MapboxMaps"}],"role":"symbol","symbolKind":"typealias","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceDataLoadedCallback"}],"roleHeading":"Type Alias","navigatorTitle":[{"kind":"identifier","text":"SourceDataLoadedCallback"}],"externalID":"c:MBMSourceDataLoadedCallback.h@T@MBMSourceDataLoadedCallback","title":"SourceDataLoadedCallback"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedCallback"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMapsInternal"]]},"variants":[{"paths":["\/documentation\/mapboxmaps\/sourcedataloadedcallback"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/sourcedataloadedcallback"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SourceDataLoadedCallback","kind":"identifier"},{"kind":"text","text":" = ("},{"text":"SourceDataLoaded","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoaded","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMSourceDataLoaded"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapRecorder","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeatureExtensionValue","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Size","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackError-swift.class","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestErrorType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapLoadingErrorTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRenderModeTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestDataSourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestErrorTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestLoadingMethodTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestPriorityTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestPriorityTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestResourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMResponseSourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMSourceDataLoadedTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStyleDataLoadedTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMTileStoreUsageModeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraChangedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GenericEventCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinishedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameStartedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequestCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceAddedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceRemovedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageMissingCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapIdleCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnusedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TransitionOptions-swift.class"],"anchor":"Symbols","generated":true,"title":"Symbols"}],"kind":"symbol","references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRequestDataSourceTypeToString(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"MBMRequestDataSourceTypeToString","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@MBMRequestDataSourceType","kind":"typeIdentifier","text":"RequestDataSourceType"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"navigatorTitle":[{"text":"MBMRequestDataSourceTypeToString","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/mbmrequestdatasourcetypetostring(_:)","role":"symbol","abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestDataSourceTypeToString(_:)","title":"MBMRequestDataSourceTypeToString(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapRecorder":{"url":"\/documentation\/mapboxmaps\/maprecorder","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapRecorder","kind":"identifier"}],"title":"MapRecorder","navigatorTitle":[{"kind":"identifier","text":"MapRecorder"}],"abstract":[{"text":"MapRecorder provides functions to record and replay API calls of a Map instance.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"These recordings can be used to debug issues which requie multiple steps to reproduce."},{"type":"text","text":" "},{"type":"text","text":"Additionaly, playbacks can be used for performance testing custom scenarios."}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapRecorder","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRequestPriorityTypeToString(_:)":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"MBMRequestPriorityTypeToString","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMRequestPriorityType","text":"RequestPriorityType"},{"kind":"text","text":") -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}],"navigatorTitle":[{"text":"MBMRequestPriorityTypeToString","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestPriorityTypeToString(_:)","url":"\/documentation\/mapboxmaps\/mbmrequestprioritytypetostring(_:)","title":"MBMRequestPriorityTypeToString(_:)","type":"topic","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","title":"MapboxMaps Documentation","type":"topic","kind":"article","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraChangedCallback":{"abstract":[{"text":"This event is emitted whenever the visible viewport changes its size","type":"text"},{"type":"text","text":" "},{"type":"text","text":"due to the invocation of the "},{"type":"codeVoice","code":"setSize"},{"type":"text","text":" and "},{"code":"setBounds","type":"codeVoice"},{"text":" methods or when","type":"text"},{"type":"text","text":" "},{"type":"text","text":"the camera is modified by calling camera methods. The event is emitted"},{"type":"text","text":" "},{"text":"synchronously so that an updated camera state can be fetched immediately.","type":"text"}],"type":"topic","title":"CameraChangedCallback","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CameraChangedCallback"}],"kind":"symbol","navigatorTitle":[{"text":"CameraChangedCallback","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraChangedCallback","url":"\/documentation\/mapboxmaps\/camerachangedcallback","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GenericEventCallback":{"url":"\/documentation\/mapboxmaps\/genericeventcallback","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GenericEventCallback"}],"title":"GenericEventCallback","navigatorTitle":[{"text":"GenericEventCallback","kind":"identifier"}],"abstract":[{"text":"Generic event for experimental events.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GenericEventCallback","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FeatureExtensionValue":{"abstract":[{"text":"A value or a collection of a feature extension.","type":"text"}],"type":"topic","title":"FeatureExtensionValue","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FeatureExtensionValue"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FeatureExtensionValue"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeatureExtensionValue","url":"\/documentation\/mapboxmaps\/featureextensionvalue","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleLoadedCallback":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"StyleLoadedCallback","kind":"identifier"}],"navigatorTitle":[{"text":"StyleLoadedCallback","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleLoadedCallback","url":"\/documentation\/mapboxmaps\/styleloadedcallback","title":"StyleLoadedCallback","type":"topic","abstract":[{"text":"The requested style has been fully loaded, including specified sprite, and sources’ metadata.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMapsInternal":{"abstract":[{"text":"Maps rendering SDK also known as GL-Native. These are for internal use only.","type":"text"}],"type":"topic","title":"CoreMaps - Internal","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMapsInternal","url":"\/documentation\/mapboxmaps\/coremapsinternal","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceDataLoadedCallback":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"SourceDataLoadedCallback","kind":"identifier"}],"navigatorTitle":[{"text":"SourceDataLoadedCallback","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/sourcedataloadedcallback","role":"symbol","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"SourceDataLoaded"},{"type":"text","text":" event is emitted when source data is loaded."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedCallback","title":"SourceDataLoadedCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoadingErrorCallback":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"MapLoadingErrorCallback","kind":"identifier"}],"navigatorTitle":[{"text":"MapLoadingErrorCallback","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/maploadingerrorcallback","role":"symbol","abstract":[{"text":"Describes an error that has occurred while loading the ","type":"text"},{"type":"codeVoice","code":"map"},{"type":"text","text":"."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorCallback","title":"MapLoadingErrorCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePackError-swift.class":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StylePackError"}],"navigatorTitle":[{"kind":"identifier","text":"StylePackError"}],"url":"\/documentation\/mapboxmaps\/stylepackerror-swift.class","role":"symbol","abstract":[{"text":"Describes a style package load request error.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackError-swift.class","title":"StylePackError"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceAddedCallback":{"kind":"symbol","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SourceAddedCallback","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SourceAddedCallback"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceAddedCallback","url":"\/documentation\/mapboxmaps\/sourceaddedcallback","title":"SourceAddedCallback","type":"topic","abstract":[{"text":"The source has been added with ","type":"text"},{"code":"addStyleSource","type":"codeVoice"},{"type":"text","text":" method."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRenderModeTypeToString(_:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBMRenderModeTypeToString"}],"kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/mbmrendermodetypetostring(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBMRenderModeTypeToString","kind":"identifier"},{"kind":"text","text":"("},{"text":"RenderModeType","preciseIdentifier":"c:@E@MBMRenderModeType","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"title":"MBMRenderModeTypeToString(_:)","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRenderModeTypeToString(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","type":"topic","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRequestErrorTypeToString(_:)":{"url":"\/documentation\/mapboxmaps\/mbmrequesterrortypetostring(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBMRequestErrorTypeToString","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMRequestErrorType","text":"RequestErrorType"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}],"title":"MBMRequestErrorTypeToString(_:)","navigatorTitle":[{"kind":"identifier","text":"MBMRequestErrorTypeToString"}],"abstract":[],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestErrorTypeToString(_:)","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestErrorType":{"url":"\/documentation\/mapboxmaps\/requesterrortype","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"RequestErrorType","kind":"identifier"}],"title":"RequestErrorType","navigatorTitle":[{"text":"RequestErrorType","kind":"identifier"}],"abstract":[{"text":"The enumeration defines the error type that may occur during a resource request.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestErrorType","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleImageRemoveUnusedCallback":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StyleImageRemoveUnusedCallback"}],"navigatorTitle":[{"text":"StyleImageRemoveUnusedCallback","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/styleimageremoveunusedcallback","role":"symbol","abstract":[{"text":"An image requested by the ","type":"text"},{"type":"codeVoice","code":"map"},{"type":"text","text":" through the "},{"type":"codeVoice","code":"StyleImageMissing"},{"type":"text","text":" event is no longer"},{"type":"text","text":" "},{"text":"needed and can be removed using the ","type":"text"},{"type":"codeVoice","code":"removeStyleImage"},{"type":"text","text":" method. The application can"},{"type":"text","text":" "},{"text":"decide whether the image should be kept or removed.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnusedCallback","title":"StyleImageRemoveUnusedCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRequestLoadingMethodTypeToString(_:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBMRequestLoadingMethodTypeToString"}],"kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/mbmrequestloadingmethodtypetostring(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"MBMRequestLoadingMethodTypeToString","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMRequestLoadingMethodType","text":"RequestLoadingMethodType"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}],"title":"MBMRequestLoadingMethodTypeToString(_:)","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestLoadingMethodTypeToString(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TransitionOptions-swift.class":{"url":"\/documentation\/mapboxmaps\/transitionoptions-swift.class","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TransitionOptions"}],"title":"TransitionOptions","navigatorTitle":[{"text":"TransitionOptions","kind":"identifier"}],"abstract":[{"type":"text","text":"The "},{"code":"transition options","type":"codeVoice"},{"text":" controls timing for the interpolation between a transitionable style","type":"text"},{"text":" ","type":"text"},{"text":"property’s previous value and new value. These can be used to define the style default property","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"transition behavior. Also, any transitionable style property may also have its own "},{"type":"codeVoice","code":"-transition"},{"type":"text","text":" "},{"type":"text","text":"property that defines specific transition timing for that specific layer property, overriding"},{"type":"text","text":" "},{"text":"the global transition values.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TransitionOptions-swift.class","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Size":{"abstract":[{"text":"Size type.","type":"text"}],"type":"topic","title":"Size","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Size"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Size"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Size","url":"\/documentation\/mapboxmaps\/size","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResourceRequestCallback":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ResourceRequestCallback"}],"navigatorTitle":[{"text":"ResourceRequestCallback","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequestCallback","url":"\/documentation\/mapboxmaps\/resourcerequestcallback","title":"ResourceRequestCallback","type":"topic","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ResourceRequest"},{"type":"text","text":" event allows the application to observe resourcerequests"},{"type":"text","text":" "},{"text":"made by a ","type":"text"},{"code":"map","type":"codeVoice"},{"text":" or ","type":"text"},{"type":"codeVoice","code":"map snapshotter"},{"type":"text","text":" object."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMMapLoadingErrorTypeToString(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"MBMMapLoadingErrorTypeToString","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@MBMMapLoadingErrorType","kind":"typeIdentifier","text":"MapLoadingErrorType"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"navigatorTitle":[{"text":"MBMMapLoadingErrorTypeToString","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/mbmmaploadingerrortypetostring(_:)","role":"symbol","abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapLoadingErrorTypeToString(_:)","title":"MBMMapLoadingErrorTypeToString(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderFrameStartedCallback":{"url":"\/documentation\/mapboxmaps\/renderframestartedcallback","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"RenderFrameStartedCallback","kind":"identifier"}],"title":"RenderFrameStartedCallback","navigatorTitle":[{"text":"RenderFrameStartedCallback","kind":"identifier"}],"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"map"},{"type":"text","text":" started rendering a frame."}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameStartedCallback","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleImageMissingCallback":{"abstract":[{"text":"A style needs an image that is missing from the sprite sheet. This event is","type":"text"},{"type":"text","text":" "},{"type":"text","text":"emitted when the "},{"type":"codeVoice","code":"map"},{"type":"text","text":" renders visible tiles, and one of the required images"},{"type":"text","text":" "},{"text":"is missing in the sprite sheet. The event observer has to provide the missing","type":"text"},{"type":"text","text":" "},{"type":"text","text":"image by calling the "},{"type":"codeVoice","code":"addStyleImage"},{"text":" method.","type":"text"}],"type":"topic","title":"StyleImageMissingCallback","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StyleImageMissingCallback"}],"kind":"symbol","navigatorTitle":[{"text":"StyleImageMissingCallback","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageMissingCallback","url":"\/documentation\/mapboxmaps\/styleimagemissingcallback","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderFrameFinishedCallback":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"RenderFrameFinishedCallback","kind":"identifier"}],"navigatorTitle":[{"text":"RenderFrameFinishedCallback","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/renderframefinishedcallback","role":"symbol","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"map"},{"type":"text","text":" finished rendering a frame."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinishedCallback","title":"RenderFrameFinishedCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMResponseSourceTypeToString(_:)":{"abstract":[],"type":"topic","title":"MBMResponseSourceTypeToString(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"MBMResponseSourceTypeToString","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@MBMResponseSourceType","kind":"typeIdentifier","text":"ResponseSourceType"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"kind":"symbol","navigatorTitle":[{"text":"MBMResponseSourceTypeToString","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMResponseSourceTypeToString(_:)","url":"\/documentation\/mapboxmaps\/mbmresponsesourcetypetostring(_:)","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMStyleDataLoadedTypeToString(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"MBMStyleDataLoadedTypeToString","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@MBMStyleDataLoadedType","kind":"typeIdentifier","text":"StyleDataLoadedType"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"navigatorTitle":[{"text":"MBMStyleDataLoadedTypeToString","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/mbmstyledataloadedtypetostring(_:)","role":"symbol","abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStyleDataLoadedTypeToString(_:)","title":"MBMStyleDataLoadedTypeToString(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMSourceDataLoadedTypeToString(_:)":{"abstract":[],"type":"topic","title":"MBMSourceDataLoadedTypeToString(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"MBMSourceDataLoadedTypeToString","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@MBMSourceDataLoadedType","kind":"typeIdentifier","text":"SourceDataLoadedType"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"kind":"symbol","navigatorTitle":[{"text":"MBMSourceDataLoadedTypeToString","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMSourceDataLoadedTypeToString(_:)","url":"\/documentation\/mapboxmaps\/mbmsourcedataloadedtypetostring(_:)","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleDataLoadedCallback":{"kind":"symbol","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StyleDataLoadedCallback","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"StyleDataLoadedCallback"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedCallback","url":"\/documentation\/mapboxmaps\/styledataloadedcallback","title":"StyleDataLoadedCallback","type":"topic","abstract":[{"text":"The style data has been loaded.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMTileStoreUsageModeToString(_:)":{"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBMTileStoreUsageModeToString"},{"text":"(","kind":"text"},{"text":"TileStoreUsageMode","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMTileStoreUsageMode"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MBMTileStoreUsageModeToString"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMTileStoreUsageModeToString(_:)","url":"\/documentation\/mapboxmaps\/mbmtilestoreusagemodetostring(_:)","title":"MBMTileStoreUsageModeToString(_:)","type":"topic","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceDataLoaded":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoaded","navigatorTitle":[{"text":"SourceDataLoaded","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SourceDataLoaded","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/sourcedataloaded","abstract":[{"type":"text","text":"The "},{"code":"SourceDataLoaded","type":"codeVoice"},{"text":" event is emitted when source data is loaded.","type":"text"}],"type":"topic","title":"SourceDataLoaded"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapIdleCallback":{"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"map"},{"type":"text","text":" has entered the idle state. The "},{"type":"codeVoice","code":"map"},{"type":"text","text":" is idle when there are no ongoing"},{"type":"text","text":" "},{"text":"animations, transitions and the ","type":"text"},{"type":"codeVoice","code":"map"},{"type":"text","text":" has rendered all requested non-volatile tiles"},{"type":"text","text":" "},{"text":"(e.g., live traffic tiles). The event will not be emitted if ","type":"text"},{"code":"setUserAnimationInProgress","type":"codeVoice"},{"type":"text","text":" "},{"type":"text","text":"and \/ or "},{"type":"codeVoice","code":"setGestureInProgress"},{"type":"text","text":" is set to "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"type":"topic","title":"MapIdleCallback","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapIdleCallback"}],"kind":"symbol","navigatorTitle":[{"text":"MapIdleCallback","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapIdleCallback","url":"\/documentation\/mapboxmaps\/mapidlecallback","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceRemovedCallback":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"SourceRemovedCallback","kind":"identifier"}],"navigatorTitle":[{"text":"SourceRemovedCallback","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/sourceremovedcallback","role":"symbol","abstract":[{"text":"The source has been removed with ","type":"text"},{"type":"codeVoice","code":"removeStyleSource"},{"type":"text","text":" method."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceRemovedCallback","title":"SourceRemovedCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoadedCallback":{"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapLoadedCallback"}],"navigatorTitle":[{"text":"MapLoadedCallback","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/maploadedcallback","role":"symbol","abstract":[{"text":"The style has been fully loaded, and the ","type":"text"},{"type":"codeVoice","code":"map"},{"type":"text","text":" has rendered all visible tiles."},{"type":"text","text":" "},{"type":"text","text":"The event will be emitted only once for the current style. If it is required to"},{"type":"text","text":" "},{"text":"continuously observe an event where all the necessary resources are loaded or rendered,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"please check the following events: "},{"type":"codeVoice","code":"MapIdle"},{"text":", ","type":"text"},{"code":"StyleDataLoaded","type":"codeVoice"},{"type":"text","text":", and "},{"code":"RenderFrameFinished","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadedCallback","title":"MapLoadedCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRequestResourceTypeToString(_:)":{"abstract":[],"type":"topic","title":"MBMRequestResourceTypeToString(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"MBMRequestResourceTypeToString","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@MBMRequestResourceType","kind":"typeIdentifier","text":"RequestResourceType"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"kind":"symbol","navigatorTitle":[{"text":"MBMRequestResourceTypeToString","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestResourceTypeToString(_:)","url":"\/documentation\/mapboxmaps\/mbmrequestresourcetypetostring(_:)","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Alias"},{"op":"replace","path":"\/metadata\/title","value":"MBMSourceDataLoadedCallback"},{"path":"\/metadata\/symbolKind","value":"typealias","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"MBMSourceDataLoadedCallback","kind":"identifier"}],"op":"replace"},{"value":[{"text":"MBMSourceDataLoadedCallback","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"replace","value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapRecorder","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeatureExtensionValue","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Size","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackError-swift.class","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestErrorType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapLoadingErrorTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRenderModeTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestDataSourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestErrorTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestLoadingMethodTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestPriorityTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestPriorityTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestResourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMResponseSourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMSourceDataLoadedTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStyleDataLoadedTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMTileStoreUsageModeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraChangedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GenericEventCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinishedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameStartedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequestCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceAddedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceRemovedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageMissingCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapIdleCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnusedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TransitionOptions-swift.class"],"anchor":"Symbols","generated":true,"title":"Symbols"}],"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"preciseIdentifier":"c:BFv(#*$objc(cs)MBMSourceDataLoaded)","kind":"typeIdentifier","text":"void (^)(MBMSourceDataLoaded *)"},{"text":" ","kind":"text"},{"text":"MBMSourceDataLoadedCallback","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"value":"MBMRequestDataSourceTypeToString","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestDataSourceTypeToString(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestDataSourceTypeToString(_:)\/fragments","value":[{"kind":"identifier","text":"MBMRequestDataSourceTypeToString"}]},{"op":"replace","value":"MBMMapRecorder","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapRecorder\/title"},{"value":[{"text":"MBMMapRecorder","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapRecorder\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapRecorder\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMMapRecorder"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestPriorityTypeToString(_:)\/title","value":"MBMRequestPriorityTypeToString","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestPriorityTypeToString(_:)\/fragments","value":[{"text":"MBMRequestPriorityTypeToString","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChangedCallback\/title","value":"MBMCameraChangedCallback","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChangedCallback\/fragments","value":[{"kind":"identifier","text":"MBMCameraChangedCallback"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChangedCallback\/navigatorTitle","value":[{"kind":"identifier","text":"MBMCameraChangedCallback"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEventCallback\/title","value":"MBMGenericEventCallback"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEventCallback\/fragments","value":[{"kind":"identifier","text":"MBMGenericEventCallback"}]},{"value":[{"kind":"identifier","text":"MBMGenericEventCallback"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEventCallback\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeatureExtensionValue\/title","value":"MBMFeatureExtensionValue"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeatureExtensionValue\/fragments","value":[{"text":"MBMFeatureExtensionValue","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeatureExtensionValue\/navigatorTitle","value":[{"kind":"identifier","text":"MBMFeatureExtensionValue"}],"op":"replace"},{"op":"replace","value":"MBMStyleLoadedCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoadedCallback\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoadedCallback\/fragments","value":[{"text":"MBMStyleLoadedCallback","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MBMStyleLoadedCallback"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoadedCallback\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedCallback\/title","value":"MBMSourceDataLoadedCallback"},{"value":[{"text":"MBMSourceDataLoadedCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedCallback\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedCallback\/navigatorTitle","value":[{"text":"MBMSourceDataLoadedCallback","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorCallback\/title","value":"MBMMapLoadingErrorCallback","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorCallback\/fragments","op":"replace","value":[{"text":"MBMMapLoadingErrorCallback","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MBMMapLoadingErrorCallback"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorCallback\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackError-swift.class\/title","value":"MBMStylePackError","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackError-swift.class\/fragments","op":"replace","value":[{"text":"MBMStylePackError","kind":"identifier"}]},{"value":[{"text":"MBMStylePackError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackError-swift.class\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAddedCallback\/title","value":"MBMSourceAddedCallback"},{"value":[{"kind":"identifier","text":"MBMSourceAddedCallback"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAddedCallback\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBMSourceAddedCallback"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAddedCallback\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRenderModeTypeToString(_:)\/title","value":"MBMRenderModeTypeToString"},{"value":[{"kind":"identifier","text":"MBMRenderModeTypeToString"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRenderModeTypeToString(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestErrorTypeToString(_:)\/title","value":"MBMRequestErrorTypeToString"},{"value":[{"text":"MBMRequestErrorTypeToString","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestErrorTypeToString(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestErrorType\/title","value":"MBMRequestErrorType","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestErrorType\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMRequestErrorType"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestErrorType\/navigatorTitle","op":"replace","value":[{"text":"MBMRequestErrorType","kind":"identifier"}]},{"value":"MBMStyleImageRemoveUnusedCallback","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnusedCallback\/title"},{"value":[{"text":"MBMStyleImageRemoveUnusedCallback","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnusedCallback\/fragments"},{"op":"replace","value":[{"text":"MBMStyleImageRemoveUnusedCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnusedCallback\/navigatorTitle"},{"op":"replace","value":"MBMRequestLoadingMethodTypeToString","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestLoadingMethodTypeToString(_:)\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestLoadingMethodTypeToString(_:)\/fragments","value":[{"text":"MBMRequestLoadingMethodTypeToString","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TransitionOptions-swift.class\/title","value":"MBMTransitionOptions"},{"op":"replace","value":[{"text":"MBMTransitionOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TransitionOptions-swift.class\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TransitionOptions-swift.class\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMTransitionOptions"}]},{"value":"MBMSize","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Size\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MBMSize"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Size\/fragments"},{"value":[{"text":"MBMSize","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Size\/navigatorTitle"},{"op":"replace","value":"MBMResourceRequestCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequestCallback\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequestCallback\/fragments","value":[{"text":"MBMResourceRequestCallback","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequestCallback\/navigatorTitle","value":[{"text":"MBMResourceRequestCallback","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMMapLoadingErrorTypeToString(_:)\/title","value":"MBMMapLoadingErrorTypeToString","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMMapLoadingErrorTypeToString(_:)\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMMapLoadingErrorTypeToString"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameStartedCallback\/title","op":"replace","value":"MBMRenderFrameStartedCallback"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameStartedCallback\/fragments","value":[{"text":"MBMRenderFrameStartedCallback","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameStartedCallback\/navigatorTitle","value":[{"kind":"identifier","text":"MBMRenderFrameStartedCallback"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageMissingCallback\/title","value":"MBMStyleImageMissingCallback","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageMissingCallback\/fragments","value":[{"text":"MBMStyleImageMissingCallback","kind":"identifier"}]},{"value":[{"text":"MBMStyleImageMissingCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageMissingCallback\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinishedCallback\/title","value":"MBMRenderFrameFinishedCallback","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinishedCallback\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMRenderFrameFinishedCallback"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinishedCallback\/navigatorTitle","value":[{"text":"MBMRenderFrameFinishedCallback","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMResponseSourceTypeToString(_:)\/title","value":"MBMResponseSourceTypeToString","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMResponseSourceTypeToString(_:)\/fragments","value":[{"text":"MBMResponseSourceTypeToString","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMStyleDataLoadedTypeToString(_:)\/title","value":"MBMStyleDataLoadedTypeToString","op":"replace"},{"value":[{"text":"MBMStyleDataLoadedTypeToString","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMStyleDataLoadedTypeToString(_:)\/fragments","op":"replace"},{"value":"MBMSourceDataLoadedTypeToString","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMSourceDataLoadedTypeToString(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMSourceDataLoadedTypeToString(_:)\/fragments","value":[{"text":"MBMSourceDataLoadedTypeToString","kind":"identifier"}]},{"value":"MBMStyleDataLoadedCallback","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedCallback\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBMStyleDataLoadedCallback"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedCallback\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedCallback\/navigatorTitle","value":[{"text":"MBMStyleDataLoadedCallback","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMTileStoreUsageModeToString(_:)\/title","value":"MBMTileStoreUsageModeToString","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMTileStoreUsageModeToString(_:)\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMTileStoreUsageModeToString"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoaded\/title","op":"replace","value":"MBMSourceDataLoaded"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoaded\/fragments","value":[{"kind":"identifier","text":"MBMSourceDataLoaded"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoaded\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMSourceDataLoaded"}]},{"op":"replace","value":"MBMMapIdleCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdleCallback\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBMMapIdleCallback"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdleCallback\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdleCallback\/navigatorTitle","value":[{"kind":"identifier","text":"MBMMapIdleCallback"}]},{"op":"replace","value":"MBMSourceRemovedCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceRemovedCallback\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceRemovedCallback\/fragments","op":"replace","value":[{"text":"MBMSourceRemovedCallback","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceRemovedCallback\/navigatorTitle","value":[{"text":"MBMSourceRemovedCallback","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadedCallback\/title","op":"replace","value":"MBMMapLoadedCallback"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadedCallback\/fragments","value":[{"text":"MBMMapLoadedCallback","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadedCallback\/navigatorTitle","value":[{"text":"MBMMapLoadedCallback","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestResourceTypeToString(_:)\/title","op":"replace","value":"MBMRequestResourceTypeToString"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestResourceTypeToString(_:)\/fragments","value":[{"kind":"identifier","text":"MBMRequestResourceTypeToString"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}