{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/httprequest\/init(method:url:headers:timeout:networkrestriction:sdkinformation:body:flags:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/httprequest\/init(method:url:headers:timeout:networkrestriction:sdkinformation:body:flags:)"]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest\/init(method:url:headers:timeout:networkRestriction:sdkInformation:body:flags:)","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"method"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"HttpMethod","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpMethod","preciseIdentifier":"c:@E@MBXHttpMethod"},{"text":", ","kind":"text"},{"text":"url","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"headers"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"], ","kind":"text"},{"text":"timeout","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V","text":"UInt64"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"networkRestriction"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NetworkRestriction","text":"NetworkRestriction","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBXNetworkRestriction"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"sdkInformation"},{"kind":"text","text":": "},{"text":"SdkInformation","preciseIdentifier":"c:objc(cs)MBXSdkInformation","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SdkInformation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"body"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"text":"?, ","kind":"text"},{"text":"flags","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt32","preciseIdentifier":"s:s6UInt32V","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"metadata":{"symbolKind":"init","roleHeading":"Initializer","externalID":"c:objc(cs)MBXHttpRequest(im)initWithMethod:url:headers:timeout:networkRestriction:sdkInformation:body:flags:","navigatorTitle":[{"text":"initWithMethod:url:headers:timeout:networkRestriction:sdkInformation:body:flags:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"method"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@MBXHttpMethod","kind":"typeIdentifier","text":"HttpMethod"},{"kind":"text","text":", "},{"text":"url","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"headers","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"timeout"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s6UInt64V","kind":"typeIdentifier","text":"UInt64"},{"text":", ","kind":"text"},{"text":"networkRestriction","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NetworkRestriction","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBXNetworkRestriction"},{"text":", ","kind":"text"},{"text":"sdkInformation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SdkInformation","preciseIdentifier":"c:objc(cs)MBXSdkInformation","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"body","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?, "},{"text":"flags","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UInt32","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt32V"},{"text":")","kind":"text"}],"modules":[{"name":"MapboxCommon"}],"role":"symbol","title":"init(method:url:headers:timeout:networkRestriction:sdkInformation:body:flags:)"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequest":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest","navigatorTitle":[{"text":"HttpRequest","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/httprequest","role":"symbol","abstract":[{"text":"HttpRequest holds basic information for construction of an HTTP request","type":"text"}],"title":"HttpRequest","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"HttpRequest","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpMethod":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpMethod","navigatorTitle":[{"text":"HttpMethod","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/httpmethod","role":"symbol","abstract":[{"text":"HTTP defines a set of request methods to indicate the desired action to be performed for a given resource.","type":"text"}],"title":"HttpMethod","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"HttpMethod","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"kind":"symbol","url":"\/documentation\/mapboxcommon","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","title":"MapboxCommon","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/NetworkRestriction":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NetworkRestriction"}],"navigatorTitle":[{"text":"NetworkRestriction","kind":"identifier"}],"abstract":[{"text":"Classify network types based on cost.","type":"text"}],"role":"symbol","title":"NetworkRestriction","type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NetworkRestriction","url":"\/documentation\/mapboxcommon\/networkrestriction"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequest/init(method:url:headers:timeout:networkRestriction:sdkInformation:body:flags:)":{"navigatorTitle":[{"text":"initWithMethod:url:headers:timeout:networkRestriction:sdkInformation:body:flags:","kind":"identifier"}],"title":"init(method:url:headers:timeout:networkRestriction:sdkInformation:body:flags:)","type":"topic","abstract":[],"url":"\/documentation\/mapboxcommon\/httprequest\/init(method:url:headers:timeout:networkrestriction:sdkinformation:body:flags:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"method","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBXHttpMethod","text":"HttpMethod"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"url"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"headers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"timeout"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s6UInt64V","text":"UInt64","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"networkRestriction"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@MBXNetworkRestriction","text":"NetworkRestriction","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"sdkInformation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SdkInformation","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXSdkInformation"},{"kind":"text","text":", "},{"text":"body","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":"?, "},{"text":"flags","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s6UInt32V","text":"UInt32","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest\/init(method:url:headers:timeout:networkRestriction:sdkInformation:body:flags:)"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","url":"\/documentation\/overview","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"role":"collection","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SdkInformation":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SdkInformation"}],"navigatorTitle":[{"text":"SdkInformation","kind":"identifier"}],"abstract":[{"type":"text","text":"Provides information about a given Mapbox SDK. This information is then used to populate the “User-Agent” HTTP header"},{"text":" ","type":"text"},{"type":"text","text":"of HTTP requests generated from within Mapbox SDKs. Mapbox SDKs include Maps, Navigation, Search, and others."}],"title":"SdkInformation","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SdkInformation","type":"topic","url":"\/documentation\/mapboxcommon\/sdkinformation","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"initWithMethod:url:headers:timeout:networkRestriction:sdkInformation:body:flags:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithMethod:url:headers:timeout:networkRestriction:sdkInformation:body:flags:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"text":"initWithMethod:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpMethod","text":"MBXHttpMethod","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBXHttpMethod"},{"text":") ","kind":"text"},{"text":"method","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"url:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"url"},{"text":" ","kind":"text"},{"text":"headers:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<NSString *,NSString *>"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"headers"},{"text":" ","kind":"text"},{"text":"timeout:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@uint64_t","text":"uint64_t"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"timeout"},{"kind":"text","text":" "},{"text":"networkRestriction:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MBXNetworkRestriction","preciseIdentifier":"c:@E@MBXNetworkRestriction","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NetworkRestriction"},{"kind":"text","text":") "},{"kind":"internalParam","text":"networkRestriction"},{"text":" ","kind":"text"},{"text":"sdkInformation:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MBXSdkInformation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SdkInformation","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXSdkInformation"},{"text":" *) ","kind":"text"},{"text":"sdkInformation","kind":"internalParam"},{"kind":"text","text":" "},{"text":"body:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData","text":"NSData"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"body"},{"text":" ","kind":"text"},{"text":"flags:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"uint32_t","preciseIdentifier":"c:@T@uint32_t","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"flags"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"MBXHttpRequest","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest\/fragments","value":[{"kind":"identifier","text":"MBXHttpRequest"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest\/navigatorTitle","value":[{"text":"MBXHttpRequest","kind":"identifier"}],"op":"replace"},{"value":"MBXHttpMethod","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpMethod\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpMethod\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXHttpMethod"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpMethod\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBXHttpMethod"}]},{"op":"replace","value":"MBXNetworkRestriction","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1NetworkRestriction\/title"},{"value":[{"text":"MBXNetworkRestriction","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1NetworkRestriction\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1NetworkRestriction\/navigatorTitle","value":[{"text":"MBXNetworkRestriction","kind":"identifier"}],"op":"replace"},{"value":"initWithMethod:url:headers:timeout:networkRestriction:sdkInformation:body:flags:","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest~1init(method:url:headers:timeout:networkRestriction:sdkInformation:body:flags:)\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest~1init(method:url:headers:timeout:networkRestriction:sdkInformation:body:flags:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithMethod:url:headers:timeout:networkRestriction:sdkInformation:body:flags:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SdkInformation\/title","op":"replace","value":"MBXSdkInformation"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SdkInformation\/fragments","op":"replace","value":[{"text":"MBXSdkInformation","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MBXSdkInformation"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SdkInformation\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}