{"sections":[],"kind":"symbol","metadata":{"role":"symbol","navigatorTitle":[{"text":"initWithType:message:sourceId:tileId:timestamp:","kind":"identifier"}],"roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@MBMMapLoadingErrorType","text":"MapLoadingErrorType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"sourceId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"tileId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMCanonicalTileID","text":"CanonicalTileID","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"timestamp","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"MapboxMaps"}],"title":"init(type:message:sourceId:tileId:timestamp:)","externalID":"c:objc(cs)MBMMapLoadingError(im)initWithType:message:sourceId:tileId:timestamp:","symbolKind":"init"},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingError\/init(type:message:sourceId:tileId:timestamp:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorType","preciseIdentifier":"c:@E@MBMMapLoadingErrorType","text":"MapLoadingErrorType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"sourceId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"tileId","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID","preciseIdentifier":"c:objc(cs)MBMCanonicalTileID","text":"CanonicalTileID","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"timestamp","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingError"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/maploadingerror\/init(type:message:sourceid:tileid:timestamp:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/maploadingerror\/init(type:message:sourceid:tileid:timestamp:)"]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoadingError/init(type:message:sourceId:tileId:timestamp:)":{"title":"init(type:message:sourceId:tileId:timestamp:)","navigatorTitle":[{"kind":"identifier","text":"initWithType:message:sourceId:tileId:timestamp:"}],"kind":"symbol","type":"topic","abstract":[],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MapLoadingErrorType","preciseIdentifier":"c:@E@MBMMapLoadingErrorType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sourceId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"tileId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CanonicalTileID","preciseIdentifier":"c:objc(cs)MBMCanonicalTileID"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":")"}],"url":"\/documentation\/mapboxmaps\/maploadingerror\/init(type:message:sourceid:tileid:timestamp:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingError\/init(type:message:sourceId:tileId:timestamp:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"url":"\/documentation\/mapboxmaps\/events","type":"topic","kind":"article","title":"Map events","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","abstract":[{"text":"The simplified diagram of the events emitted by the map is displayed below.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","url":"\/documentation\/overview","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","kind":"article","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoadingErrorType":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorType","kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/maploadingerrortype","abstract":[{"type":"text","text":"The enumeration defines map loading errors."}],"navigatorTitle":[{"text":"MapLoadingErrorType","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapLoadingErrorType","kind":"identifier"}],"title":"MapLoadingErrorType"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CanonicalTileID":{"title":"CanonicalTileID","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CanonicalTileID"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CanonicalTileID"}],"url":"\/documentation\/mapboxmaps\/canonicaltileid","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID","type":"topic","abstract":[{"type":"text","text":"Represents a tile coordinate."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","role":"collection","title":"MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoadingError":{"title":"MapLoadingError","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"MapLoadingError","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingError","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapLoadingError","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/maploadingerror","abstract":[{"text":"Describes an error that has occurred while loading the ","type":"text"},{"code":"map","type":"codeVoice"},{"text":". The ","type":"text"},{"code":"type","type":"codeVoice"},{"text":" property","type":"text"},{"text":" ","type":"text"},{"text":"defines what resource could not be loaded, and the ","type":"text"},{"code":"message","type":"codeVoice"},{"text":" property will contain","type":"text"},{"text":" ","type":"text"},{"text":"a descriptive error message.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithType:message:sourceId:tileId:timestamp:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"initWithType:message:sourceId:tileId:timestamp:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithType:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMMapLoadingErrorType","text":"MBMMapLoadingErrorType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"type"},{"kind":"text","text":" "},{"kind":"identifier","text":"message:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"message"},{"kind":"text","text":" "},{"kind":"identifier","text":"sourceId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"sourceId"},{"kind":"text","text":" "},{"kind":"identifier","text":"tileId:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMCanonicalTileID","text":"MBMCanonicalTileID"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"tileId"},{"kind":"text","text":" "},{"kind":"identifier","text":"timestamp:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDate","text":"NSDate"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"timestamp"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingError~1init(type:message:sourceId:tileId:timestamp:)\/title","value":"initWithType:message:sourceId:tileId:timestamp:"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingError~1init(type:message:sourceId:tileId:timestamp:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithType:message:sourceId:tileId:timestamp:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorType\/title","value":"MBMMapLoadingErrorType"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorType\/fragments","value":[{"kind":"identifier","text":"MBMMapLoadingErrorType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorType\/navigatorTitle","value":[{"kind":"identifier","text":"MBMMapLoadingErrorType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/title","value":"MBMCanonicalTileID"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/fragments","value":[{"kind":"identifier","text":"MBMCanonicalTileID"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/navigatorTitle","value":[{"text":"MBMCanonicalTileID","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingError\/title","value":"MBMMapLoadingError"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingError\/fragments","value":[{"text":"MBMMapLoadingError","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingError\/navigatorTitle","value":[{"kind":"identifier","text":"MBMMapLoadingError"}]}]}]}