{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/geometrytype\/init(rawvalue:)"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"text":"UInt32","preciseIdentifier":"s:s6UInt32V","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType\/init(rawValue:)"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TurfAPI","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType"]]},"metadata":{"roleHeading":"Initializer","title":"init(rawValue:)","modules":[{"name":"MapboxCommon"}],"role":"symbol","symbolKind":"init","externalID":"s:So15MBXGeometryTypea8rawValueABs6UInt32V_tcfc","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"text":"UInt32","preciseIdentifier":"s:s6UInt32V","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/GeometryType/init(rawValue:)":{"url":"\/documentation\/mapboxcommon\/geometrytype\/init(rawvalue:)","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType\/init(rawValue:)","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt32V","text":"UInt32"},{"kind":"text","text":")"}],"title":"init(rawValue:)","role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TurfAPI":{"abstract":[{"type":"text","text":"Describes "},{"code":"turf-swift","type":"codeVoice"},{"text":" dependency objects","type":"text"}],"url":"\/documentation\/mapboxmaps\/turfapi","type":"topic","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TurfAPI","title":"Turf","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/GeometryType":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType","type":"topic","abstract":[],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GeometryType","kind":"identifier"}],"navigatorTitle":[{"text":"GeometryType","kind":"identifier"}],"title":"GeometryType","url":"\/documentation\/mapboxcommon\/geometrytype","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","url":"\/documentation\/overview","title":"MapboxMaps Documentation","abstract":[],"kind":"article","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","title":"MapboxMaps","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MBXGeometryType","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType\/title","op":"replace"},{"op":"replace","value":[{"text":"","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType\/navigatorTitle","value":[{"kind":"identifier","text":"MBXGeometryType"}],"op":"replace"}]}]}