{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap"]]},"metadata":{"roleHeading":"Instance Method","role":"symbol","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setNorthOrientation","kind":"identifier"},{"kind":"text","text":"("},{"text":"NorthOrientation","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMNorthOrientation"},{"kind":"text","text":")"}],"modules":[{"name":"MapboxMaps"}],"externalID":"s:10MapboxMaps0A3MapC19setNorthOrientationyySo08MBMNorthF0VF","title":"setNorthOrientation(_:)"},"abstract":[{"type":"text","text":"Set the map north orientation"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/setNorthOrientation(_:)"},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setNorthOrientation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"northOrientation"},{"kind":"text","text":": "},{"text":"NorthOrientation","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMNorthOrientation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/NorthOrientation"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"The map north orientation to set","type":"text"}],"type":"paragraph"}],"name":"northOrientation"}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/mapboxmaps\/mapboxmap\/setnorthorientation(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","type":"topic","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"title":"MapboxMaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/NorthOrientation":{"title":"NorthOrientation","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/NorthOrientation","kind":"symbol","abstract":[{"text":"Describes the map orientation.","type":"text"}],"url":"\/documentation\/mapboxmaps\/northorientation","navigatorTitle":[{"kind":"identifier","text":"NorthOrientation"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NorthOrientation"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"url":"\/documentation\/mapboxmaps\/mapboxmap-apis","role":"collectionGroup","type":"topic","abstract":[],"kind":"article","title":"MapboxMap","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","url":"\/documentation\/overview","title":"MapboxMaps Documentation","type":"topic","role":"collection","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap":{"title":"MapboxMap","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MapboxMap","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MapboxMap"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","role":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap","abstract":[{"text":"Provides access to the map model, including the camera, style, observable map events,","type":"text"},{"text":" ","type":"text"},{"text":"and querying rendered features.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/setNorthOrientation(_:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/setNorthOrientation(_:)","type":"topic","role":"symbol","kind":"symbol","title":"setNorthOrientation(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setNorthOrientation","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@MBMNorthOrientation","kind":"typeIdentifier","text":"NorthOrientation"},{"kind":"text","text":")"}],"url":"\/documentation\/mapboxmaps\/mapboxmap\/setnorthorientation(_:)","abstract":[{"type":"text","text":"Set the map north orientation"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1NorthOrientation\/title","value":"MBMNorthOrientation","op":"replace"},{"value":[{"text":"MBMNorthOrientation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1NorthOrientation\/fragments"},{"op":"replace","value":[{"text":"MBMNorthOrientation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1NorthOrientation\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}