{"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"timeInterval.begin"},{"type":"text","text":" represents the time when a style is set, and the"},{"type":"text","text":" "},{"type":"codeVoice","code":"timeInterval.end"},{"type":"text","text":" is taken when the "},{"type":"codeVoice","code":"map"},{"type":"text","text":" is fully loaded."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"timeInterval"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/EventTimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMEventTimeInterval","text":"EventTimeInterval"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/mapboxmaps\/maploaded\/timeinterval"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/maploaded\/timeinterval"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoaded\/timeInterval"},"kind":"symbol","sections":[],"metadata":{"role":"symbol","modules":[{"name":"MapboxMaps"}],"symbolKind":"property","externalID":"c:objc(cs)MBMMapLoaded(py)timeInterval","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"timeInterval"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MBMEventTimeInterval","kind":"typeIdentifier","text":"EventTimeInterval"}],"navigatorTitle":[{"kind":"identifier","text":"timeInterval"}],"roleHeading":"Instance Property","title":"timeInterval"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoaded"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","url":"\/documentation\/mapboxmaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","kind":"article","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"abstract":[{"text":"The simplified diagram of the events emitted by the map is displayed below.","type":"text"}],"role":"collectionGroup","title":"Map events","url":"\/documentation\/mapboxmaps\/events","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/EventTimeInterval":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/EventTimeInterval","type":"topic","title":"EventTimeInterval","role":"symbol","navigatorTitle":[{"text":"EventTimeInterval","kind":"identifier"}],"abstract":[{"type":"text","text":"The time interval of an event. The "},{"type":"codeVoice","code":"begin"},{"type":"text","text":" property represents the time"},{"type":"text","text":" "},{"type":"text","text":"origin of an event, and the "},{"type":"codeVoice","code":"end"},{"type":"text","text":" property represents the time when the particular"},{"type":"text","text":" "},{"type":"text","text":"operation is complete. The timestamps are sampled at the origin and do not include"},{"type":"text","text":" "},{"type":"text","text":"the time required to dispatch an event."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EventTimeInterval","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/eventtimeinterval"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoaded/timeInterval":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"timeInterval"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"timeInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMEventTimeInterval","text":"EventTimeInterval"}],"url":"\/documentation\/mapboxmaps\/maploaded\/timeinterval","kind":"symbol","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"timeInterval.begin"},{"type":"text","text":" represents the time when a style is set, and the"},{"type":"text","text":" "},{"code":"timeInterval.end","type":"codeVoice"},{"type":"text","text":" is taken when the "},{"code":"map","type":"codeVoice"},{"type":"text","text":" is fully loaded."}],"title":"timeInterval","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoaded\/timeInterval"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoaded":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoaded","type":"topic","abstract":[{"type":"text","text":"The style has been fully loaded, and the "},{"type":"codeVoice","code":"map"},{"type":"text","text":" has rendered all visible tiles."},{"type":"text","text":" "},{"type":"text","text":"The event will be emitted only once for the current style. If it is required to"},{"type":"text","text":" "},{"type":"text","text":"observe an event where all required resources are loaded or rendered, please"},{"type":"text","text":" "},{"type":"text","text":"check the following events: "},{"type":"codeVoice","code":"MapIdle"},{"type":"text","text":", "},{"type":"codeVoice","code":"StyleDataLoaded"},{"type":"text","text":", and "},{"type":"codeVoice","code":"RenderFrameFinished"},{"type":"text","text":"."}],"url":"\/documentation\/mapboxmaps\/maploaded","navigatorTitle":[{"text":"MapLoaded","kind":"identifier"}],"title":"MapLoaded","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapLoaded","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"timeInterval"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"timeInterval","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMEventTimeInterval","text":"MBMEventTimeInterval","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/EventTimeInterval","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"timeInterval","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1EventTimeInterval\/title","value":"MBMEventTimeInterval"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1EventTimeInterval\/fragments","value":[{"kind":"identifier","text":"MBMEventTimeInterval"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1EventTimeInterval\/navigatorTitle","value":[{"kind":"identifier","text":"MBMEventTimeInterval"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoaded~1timeInterval\/title","value":"timeInterval"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoaded~1timeInterval\/fragments","value":[{"kind":"identifier","text":"timeInterval"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoaded\/title","value":"MBMMapLoaded"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoaded\/fragments","value":[{"kind":"identifier","text":"MBMMapLoaded"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoaded\/navigatorTitle","value":[{"text":"MBMMapLoaded","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}