{"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"title":"Operators","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus\/!=(_:_:)"],"anchor":"Operators"}],"metadata":{"title":"Equatable Implementations","roleHeading":"API Collection","modules":[{"name":"MapboxMaps"},{"name":"MapboxCommon"}],"role":"collectionGroup"},"kind":"article","sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus"]]},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus\/Equatable-Implementations","interfaceLanguage":"swift"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","type":"topic","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PermissionStatus":{"url":"\/documentation\/mapboxcommon\/permissionstatus","abstract":[{"type":"text","text":"Location permissions granted by user to the app."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus","kind":"symbol","type":"topic","title":"PermissionStatus","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PermissionStatus","kind":"identifier"}],"navigatorTitle":[{"text":"PermissionStatus","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Location-APIs":{"url":"\/documentation\/mapboxmaps\/location-apis","role":"collectionGroup","kind":"article","title":"Location","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","type":"topic","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PermissionStatus/!=(_:_:)":{"url":"\/documentation\/mapboxcommon\/permissionstatus\/!=(_:_:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"text":" ","kind":"text"},{"kind":"text","text":"("},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus\/!=(_:_:)","title":"!=(_:_:)","role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","title":"MapboxMaps Documentation","type":"topic","kind":"article","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/title","value":"MBXPermissionStatus"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/fragments","value":[{"kind":"identifier","text":"MBXPermissionStatus"}],"op":"replace"},{"op":"replace","value":[{"text":"MBXPermissionStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}