{"metadata":{"symbolKind":"method","roleHeading":"Type Method","navigatorTitle":[{"text":"fromHttpRequest:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fromHttpRequest","kind":"identifier"},{"kind":"text","text":"("},{"text":"HttpRequest","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXHttpRequest"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Self"}],"role":"symbol","externalID":"c:objc(cs)MBXHttpRequestOrResponse(cm)fromHttpRequest:","modules":[{"name":"MapboxCommon"}],"title":"fromHttpRequest(_:)"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fromHttpRequest"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"value","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"HttpRequest","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest","preciseIdentifier":"c:objc(cs)MBXHttpRequest"},{"text":") -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/httprequestorresponse\/fromhttprequest(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/httprequestorresponse\/fromhttprequest(_:)"]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestOrResponse\/fromHttpRequest(_:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestOrResponse"]]},"kind":"symbol","references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestOrResponse/fromHttpRequest(_:)":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"fromHttpRequest:"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fromHttpRequest"},{"text":"(","kind":"text"},{"text":"HttpRequest","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXHttpRequest"},{"kind":"text","text":") -> "},{"text":"Self","kind":"typeIdentifier"}],"kind":"symbol","title":"fromHttpRequest(_:)","url":"\/documentation\/mapboxcommon\/httprequestorresponse\/fromhttprequest(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestOrResponse\/fromHttpRequest(_:)","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","title":"MapboxCommon","kind":"symbol","role":"collection","url":"\/documentation\/mapboxcommon","type":"topic","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"kind":"article","url":"\/documentation\/overview","role":"collection","title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequest":{"abstract":[{"text":"HttpRequest holds basic information for construction of an HTTP request","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"HttpRequest","kind":"identifier"}],"navigatorTitle":[{"text":"HttpRequest","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest","kind":"symbol","title":"HttpRequest","url":"\/documentation\/mapboxcommon\/httprequest"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestOrResponse":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestOrResponse","title":"HttpRequestOrResponse","kind":"symbol","role":"symbol","url":"\/documentation\/mapboxcommon\/httprequestorresponse","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"HttpRequestOrResponse","kind":"identifier"}],"navigatorTitle":[{"text":"HttpRequestOrResponse","kind":"identifier"}],"abstract":[{"text":"Contains either an HttpRequest or an HttpResponse.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"value":"fromHttpRequest:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"+ ","kind":"text"},{"text":"fromHttpRequest:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"fromHttpRequest:"},{"text":"(","kind":"text"},{"text":"MBXHttpRequest","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest","preciseIdentifier":"c:objc(cs)MBXHttpRequest"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"value"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"fromHttpRequest:","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestOrResponse~1fromHttpRequest(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestOrResponse~1fromHttpRequest(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"fromHttpRequest:","kind":"identifier"}]},{"value":"MBXHttpRequest","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest\/fragments","value":[{"kind":"identifier","text":"MBXHttpRequest"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest\/navigatorTitle","value":[{"text":"MBXHttpRequest","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestOrResponse\/title","value":"MBXHttpRequestOrResponse","op":"replace"},{"value":[{"text":"MBXHttpRequestOrResponse","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestOrResponse\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestOrResponse\/navigatorTitle","value":[{"text":"MBXHttpRequestOrResponse","kind":"identifier"}],"op":"replace"}]}]}