{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"removeRegion"},{"kind":"text","text":"("},{"text":"forId","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"id"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"kind":"keyword","text":"@escaping"},{"text":" (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO","text":"Result"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXTileRegion","text":"TileRegion","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegion"},{"text":", any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":">) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}]}]},{"parameters":[{"content":[{"inlineContent":[{"text":"The tile region identifier.","type":"text"}],"type":"paragraph"}],"name":"id"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A callback to be invoked when a tile region was removed."}]}],"name":"completion"}],"kind":"parameters"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore\/removeRegion(forId:completion:)"},"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"removeRegion","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO","text":"Result"},{"kind":"text","text":"<"},{"text":"TileRegion","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXTileRegion"},{"kind":"text","text":", any "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":">) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","extendedModule":"MapboxCommon","modules":[{"name":"MapboxCommon"}],"title":"removeRegion(forId:completion:)","symbolKind":"method","externalID":"s:So12MBXTileStoreC10MapboxMapsE12removeRegion5forId10completionySS_ys6ResultOySo0aF0Cs5Error_pGctF"},"sections":[],"abstract":[{"type":"text","text":"An overloaded version of "},{"code":"removeTileRegion(forId:)","type":"codeVoice"},{"type":"text","text":" with a callback for feedback."},{"type":"text","text":" "},{"text":"On successful tile region removal, the given callback is invoked with the removed tile region.","type":"text"},{"text":" ","type":"text"},{"text":"Otherwise, the given callback is invoked with an error.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/tilestore\/removeregion(forid:completion:)"]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegion":{"navigatorTitle":[{"text":"TileRegion","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxcommon\/tileregion","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegion","role":"symbol","abstract":[{"type":"text","text":"TileRegion represents an identifiable geographic tile region with metadata"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TileRegion","kind":"identifier"}],"title":"TileRegion","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileStore":{"abstract":[{"type":"text","text":"TileStore manages downloads and storage for requests to tile-related API endpoints, enforcing a disk usage"},{"type":"text","text":" "},{"type":"text","text":"quota: tiles available on disk may be deleted to make room for a new download. This interface can be used by an"},{"type":"text","text":" "},{"type":"text","text":"app developer to set the disk quota. The rest of TileStore API is intended for native SDK consumption only."}],"kind":"symbol","role":"symbol","type":"topic","title":"TileStore","url":"\/documentation\/mapboxcommon\/tilestore","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore","navigatorTitle":[{"text":"TileStore","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TileStore","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","url":"\/documentation\/mapboxmaps\/tilestore-apis","kind":"article","title":"TileStore APIs","abstract":[],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"url":"\/documentation\/mapboxmaps","title":"MapboxMaps","type":"topic","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileStore/removeRegion(forId:completion:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore\/removeRegion(forId:completion:)","role":"symbol","url":"\/documentation\/mapboxcommon\/tilestore\/removeregion(forid:completion:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"removeRegion","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)MBXTileRegion","text":"TileRegion","kind":"typeIdentifier"},{"text":", any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"An overloaded version of "},{"code":"removeTileRegion(forId:)","type":"codeVoice"},{"text":" with a callback for feedback.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"On successful tile region removal, the given callback is invoked with the removed tile region."},{"type":"text","text":" "},{"text":"Otherwise, the given callback is invoked with an error.","type":"text"}],"title":"removeRegion(forId:completion:)","kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/overview"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegion\/title","value":"MBXTileRegion","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegion\/fragments","op":"replace","value":[{"text":"MBXTileRegion","kind":"identifier"}]},{"value":[{"text":"MBXTileRegion","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegion\/navigatorTitle"},{"value":"MBXTileStore","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXTileStore"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/navigatorTitle","op":"replace","value":[{"text":"MBXTileStore","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}