{"variants":[{"paths":["\/documentation\/mapboxmaps\/map"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SwiftUI"]]},"abstract":[{"type":"text","text":"A SwiftUI view that displays a Mapbox Map."}],"metadata":{"roleHeading":"Structure","title":"Map","symbolKind":"struct","role":"symbol","modules":[{"name":"MapboxMaps"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Map","kind":"identifier"}],"navigatorTitle":[{"text":"Map","kind":"identifier"}],"externalID":"s:10MapboxMaps3MapV"},"topicSections":[{"anchor":"Initializers","title":"Initializers","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/init(initialViewport:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/init(initialViewport:content:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/init(initialViewport:urlOpener:content:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/init(viewport:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/init(viewport:content:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/init(viewport:urlOpener:content:)"]},{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/additionalSafeAreaInsets(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/additionalSafeAreaInsets(_:_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/cameraBounds(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/collectPerformanceStatistics(_:callback:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/constrainMode(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/debugOptions(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/frameRate(range:preferred:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/gestureHandlers(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/gestureOptions(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/makeCoordinator()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/makeUIViewController(context:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/mapStyle(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/northOrientation(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onCameraChanged(action:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onLayerLongPressGesture(_:perform:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onLayerTapGesture(_:perform:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onMapIdle(action:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onMapLoaded(action:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onMapLoadingError(action:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onMapLongPressGesture(perform:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onMapTapGesture(perform:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onRenderFrameFinished(action:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onRenderFrameStarted(action:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onResourceRequest(action:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onSourceAdded(action:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onSourceDataLoaded(action:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onSourceRemoved(action:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onStyleDataLoaded(action:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onStyleImageMissing(action:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onStyleImageRemoveUnused(action:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onStyleLoaded(action:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/opaque(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/ornamentOptions(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/presentationTransactionMode(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/screenCullingShape(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/transitionsToIdleUponUserInteraction(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/updateUIViewController(_:context:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/usesSafeAreaInsetsAsPadding(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/viewportMode(_:)"]},{"anchor":"Default-Implementations","title":"Default Implementations","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/UIViewControllerRepresentable-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/View-Implementations"]}],"seeAlsoSections":[{"anchor":"SwiftUI","title":"SwiftUI","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapContent","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ConditionalMapContent","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/EmptyMapContent","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OptionalMapContent","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TupleMapContent","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapContentBuilder","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapStyle","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Viewport","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportAnimation","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/withViewportAnimation(_:body:completion:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapViewAnnotation","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PointAnnotationGroup","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CircleAnnotationGroup","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PolygonAnnotationGroup","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PolylineAnnotationGroup","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck2D","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3D","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapReader","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapProxy","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeatureState","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Viewport\/FollowPuckOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Viewport\/OverviewOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapGestureHandlers","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapURLOpener","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ForEvery","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ArrayBuilder"]}],"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Map"}]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","level":2,"text":"Overview","anchor":"overview"},{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"Map"},{"text":" is an entry point to display Mapbox Map in a SwiftUI Application. Typically, you create a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map"},{"text":" in the ","type":"text"},{"type":"codeVoice","code":"body"},{"text":" variable of your view. Then you can use","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Viewport","type":"reference"},{"type":"text","text":" and "},{"isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportAnimation","type":"reference"},{"type":"text","text":" to manage map camera state and animations."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"Map"},{"type":"text","text":"’s modifier functions such as "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/mapStyle(_:)"},{"type":"text","text":",  "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onTapGesture(count:perform:)"},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onLayerTapGesture(_:perform:)"},{"type":"text","text":" and many others to configure the map appearance and behavior."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Map Content objects, such as ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck2D"},{"text":", ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3D"},{"text":", ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PointAnnotation"},{"text":", ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PolylineAnnotation"},{"text":", ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PolygonAnnotation"},{"text":", ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapViewAnnotation"},{"text":" and others, to display your content on the map.","type":"text"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"In the example below the "},{"code":"ContentView","type":"codeVoice"},{"type":"text","text":" displays a map with "},{"identifier":"https:\/\/www.mapbox.com\/blog\/standard-core-style","type":"reference","isActive":true},{"type":"text","text":" style in the dusk light preset, shows the user location indicator (Puck), displays a view annotation with a SwiftUI View inside, draws a polygon, and focuses camera on that polygon."}]},{"type":"codeListing","syntax":"swift","code":["struct ContentView: View {","    static let polygon = Polygon(...)","","    \/\/ Configures the map camera to overview the given polygon.","    @State var viewport = Viewport.overview(geometry: Self.polygon)","","    var body: some View {","        Map(viewport: $viewport) {","            \/\/ Displays the user location.","            Puck2D(heading: bearing)","","            \/\/ Displays a view annotation.","            MapViewAnnotation(CLLocationCoordinate(...))","                Text(\"🚀\")","                    .background(Circle().fill(.red))","            }","","            \/\/ Displays a polygon annotation.","            PolygonAnnotation(polygon: Self.polygon)","                .fillColor(StyleColor(.systemBlue))","                .fillOpacity(0.5)","                .fillOutlineColor(StyleColor(.black))","                .onTapGesture {","                    print(\"Polygon is tapped\")","                }","         }","         \/\/ Uses Mapbox Standard style in the dusk light preset.","         .mapStyle(.standard(lightPreset: .dusk))","    }","}"]},{"type":"paragraph","inlineContent":[{"text":"Check out the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SwiftUI-User-Guide"},{"text":" for more information about ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map"},{"text":" capabilities, and the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-Content-Gestures-User-Guide"},{"text":" for more information about gesture handling.","type":"text"}]}]}],"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/s8SendableP","doc:\/\/com.mapbox.MapboxMaps\/7SwiftUI29UIViewControllerRepresentableP","doc:\/\/com.mapbox.MapboxMaps\/7SwiftUI4ViewP"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map"},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/cameraBounds(_:)":{"abstract":[{"text":"Sets camera bounds.","type":"text"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/map\/camerabounds(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/cameraBounds(_:)","kind":"symbol","title":"cameraBounds(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraBounds","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps19CameraBoundsOptionsV","text":"CameraBoundsOptions","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps3MapV","text":"Map","kind":"typeIdentifier"}]},"doc://com.mapbox.MapboxMaps/7SwiftUI29UIViewControllerRepresentableP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/7SwiftUI29UIViewControllerRepresentableP","title":"SwiftUI.UIViewControllerRepresentable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/onMapTapGesture(perform:)":{"role":"symbol","deprecated":true,"url":"\/documentation\/mapboxmaps\/map\/onmaptapgesture(perform:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onMapTapGesture(perform:)","title":"onMapTapGesture(perform:)","type":"topic","abstract":[{"type":"text","text":"Adds a tap gesture handler to the map."}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onMapTapGesture","kind":"identifier"},{"text":"(","kind":"text"},{"text":"perform","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps18InteractionContextV","text":"InteractionContext","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps3MapV","text":"Map","kind":"typeIdentifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/ornamentOptions(_:)":{"abstract":[{"text":"Sets ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OrnamentOptions","type":"reference"},{"type":"text","text":" to the map."}],"title":"ornamentOptions(_:)","url":"\/documentation\/mapboxmaps\/map\/ornamentoptions(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ornamentOptions","kind":"identifier"},{"text":"(","kind":"text"},{"text":"OrnamentOptions","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps15OrnamentOptionsV"},{"text":") -> ","kind":"text"},{"text":"Map","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps3MapV"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/ornamentOptions(_:)","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","abstract":[],"type":"topic","title":"MapboxMaps Documentation","kind":"article","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PolygonAnnotationGroup":{"title":"PolygonAnnotationGroup","navigatorTitle":[{"text":"PolygonAnnotationGroup","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PolygonAnnotationGroup","kind":"identifier"}],"abstract":[],"url":"\/documentation\/mapboxmaps\/polygonannotationgroup","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PolygonAnnotationGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/onStyleDataLoaded(action:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onStyleDataLoaded(action:)","type":"topic","title":"onStyleDataLoaded(action:)","abstract":[{"text":"Adds an action to perform when the requested style data is loaded.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onStyleDataLoaded"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"StyleDataLoaded","preciseIdentifier":"c:objc(cs)MBMStyleDataLoaded"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Map","preciseIdentifier":"s:10MapboxMaps3MapV"}],"url":"\/documentation\/mapboxmaps\/map\/onstyledataloaded(action:)","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OptionalMapContent":{"url":"\/documentation\/mapboxmaps\/optionalmapcontent","navigatorTitle":[{"kind":"identifier","text":"OptionalMapContent"}],"type":"topic","title":"OptionalMapContent","abstract":[],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OptionalMapContent","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"OptionalMapContent"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/frameRate(range:preferred:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/frameRate(range:preferred:)","title":"frameRate(range:preferred:)","url":"\/documentation\/mapboxmaps\/map\/framerate(range:preferred:)","role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"frameRate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"range"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SN","kind":"typeIdentifier","text":"ClosedRange"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"},{"kind":"text","text":">?, "},{"kind":"externalParam","text":"preferred"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:10MapboxMaps3MapV","kind":"typeIdentifier","text":"Map"}],"abstract":[{"type":"text","text":"The preferred frames per second used for map rendering."},{"type":"text","text":" "},{"type":"text","text":"The system can change the available range of frame rates because of factors in system policies and a person’s preferences."},{"type":"text","text":" "},{"type":"text","text":"Changing this setting maybe beneficial to get smoother experience on devices which support 120 FPS."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Puck2D":{"role":"symbol","url":"\/documentation\/mapboxmaps\/puck2d","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Puck2D"}],"kind":"symbol","title":"Puck2D","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck2D","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Puck2D"}],"abstract":[{"text":"Displays user location via 2D Puck.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/makeUIViewController(context:)":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/makeUIViewController(context:)","url":"\/documentation\/mapboxmaps\/map\/makeuiviewcontroller(context:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"makeUIViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10MapboxMaps3MapV","kind":"typeIdentifier","text":"Map"},{"kind":"text","text":"."},{"preciseIdentifier":"s:7SwiftUI29UIViewControllerRepresentableP7Contexta","kind":"typeIdentifier","text":"Context"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"}],"kind":"symbol","role":"symbol","title":"makeUIViewController(context:)","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map-Content-Gestures-User-Guide":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-Content-Gestures-User-Guide","role":"article","kind":"article","url":"\/documentation\/mapboxmaps\/map-content-gestures-user-guide","abstract":[{"text":"Handle Tap and Long Press gestures on Map, Annotations, and Layers.","type":"text"}],"title":"Map Content Gestures User Guide","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/onRenderFrameStarted(action:)":{"url":"\/documentation\/mapboxmaps\/map\/onrenderframestarted(action:)","abstract":[{"text":"Adds an action to perform when the map started rendering a frame.","type":"text"}],"type":"topic","kind":"symbol","title":"onRenderFrameStarted(action:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onRenderFrameStarted(action:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onRenderFrameStarted","kind":"identifier"},{"text":"(","kind":"text"},{"text":"action","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMRenderFrameStarted","text":"RenderFrameStarted","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps3MapV","text":"Map","kind":"typeIdentifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/northOrientation(_:)":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/northOrientation(_:)","type":"topic","abstract":[{"text":"Sets ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/NorthOrientation"},{"text":" to the map. If not set, ","type":"text"},{"code":"upwards","type":"codeVoice"},{"text":" will be in use.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"northOrientation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NorthOrientation","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMNorthOrientation"},{"text":") -> ","kind":"text"},{"text":"Map","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps3MapV"}],"url":"\/documentation\/mapboxmaps\/map\/northorientation(_:)","kind":"symbol","title":"northOrientation(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/onStyleImageMissing(action:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onStyleImageMissing"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"StyleImageMissing","preciseIdentifier":"c:objc(cs)MBMStyleImageMissing"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Map","preciseIdentifier":"s:10MapboxMaps3MapV"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onStyleImageMissing(action:)","role":"symbol","title":"onStyleImageMissing(action:)","url":"\/documentation\/mapboxmaps\/map\/onstyleimagemissing(action:)","abstract":[{"type":"text","text":"Adds an action to perform when the style image is missing."}],"kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/presentationTransactionMode(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"presentationTransactionMode","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PresentationTransactionMode","preciseIdentifier":"s:10MapboxMaps27PresentationTransactionModeO","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Map","preciseIdentifier":"s:10MapboxMaps3MapV","kind":"typeIdentifier"}],"url":"\/documentation\/mapboxmaps\/map\/presentationtransactionmode(_:)","title":"presentationTransactionMode(_:)","type":"topic","abstract":[{"type":"text","text":"Defines the map presentation mode."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/presentationTransactionMode(_:)","role":"symbol","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/init(initialViewport:content:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/init(initialViewport:content:)","abstract":[{"text":"Creates a map that displays annotations.","type":"text"}],"title":"init(initialViewport:content:)","url":"\/documentation\/mapboxmaps\/map\/init(initialviewport:content:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"initialViewport"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps8ViewportV","text":"Viewport"},{"kind":"text","text":", "},{"kind":"externalParam","text":"content"},{"kind":"text","text":": () -> some "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps10MapContentP","text":"MapContent"},{"kind":"text","text":")"}],"kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/onStyleImageRemoveUnused(action:)":{"url":"\/documentation\/mapboxmaps\/map\/onstyleimageremoveunused(action:)","title":"onStyleImageRemoveUnused(action:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onStyleImageRemoveUnused(action:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onStyleImageRemoveUnused"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"StyleImageRemoveUnused","preciseIdentifier":"c:objc(cs)MBMStyleImageRemoveUnused"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Map","preciseIdentifier":"s:10MapboxMaps3MapV"}],"type":"topic","abstract":[{"type":"text","text":"An image added to the style is no longer needed and can be removed using "},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/removeImage(withId:)","isActive":true},{"type":"text","text":"."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapContent":{"type":"topic","url":"\/documentation\/mapboxmaps\/mapcontent","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapContent","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"A protocol used to create any type of "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map","isActive":true,"type":"reference"},{"type":"text","text":" content, such as annotations, location indicator, layers, sources, lights, and more."}],"title":"MapContent","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapContent","kind":"identifier"}],"navigatorTitle":[{"text":"MapContent","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapReader":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapReader","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapReader","kind":"identifier"}],"abstract":[{"text":"Provides access to the underlying ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapView","isActive":true},{"text":" map via proxy.","type":"text"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"MapReader","kind":"identifier"}],"title":"MapReader","type":"topic","url":"\/documentation\/mapboxmaps\/mapreader"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/constrainMode(_:)":{"abstract":[{"text":"Sets constraint mode to the map. If not set, ","type":"text"},{"code":"heightOnly","type":"codeVoice"},{"type":"text","text":" will be in use."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/constrainMode(_:)","title":"constrainMode(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"constrainMode"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMConstrainMode","text":"ConstrainMode"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps3MapV","text":"Map"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/map\/constrainmode(_:)","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/opaque(_:)":{"abstract":[{"text":"A boolean value that determines whether the view is opaque. Default is true.","type":"text"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"opaque","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"text":"Map","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps3MapV"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/map\/opaque(_:)","title":"opaque(_:)","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/opaque(_:)"},"doc://com.mapbox.MapboxMaps/7SwiftUI4ViewP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/7SwiftUI4ViewP","title":"SwiftUICore.View"},"doc://com.mapbox.MapboxMaps/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s8SendableP","title":"Swift.Sendable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/onMapLongPressGesture(perform:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onMapLongPressGesture","kind":"identifier"},{"text":"(","kind":"text"},{"text":"perform","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps18InteractionContextV","text":"InteractionContext","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps3MapV","text":"Map","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Adds a long press gesture handler to the map."}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onMapLongPressGesture(perform:)","role":"symbol","title":"onMapLongPressGesture(perform:)","kind":"symbol","url":"\/documentation\/mapboxmaps\/map\/onmaplongpressgesture(perform:)","deprecated":true},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/makeCoordinator()":{"abstract":[],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/makeCoordinator()","type":"topic","title":"makeCoordinator()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"makeCoordinator"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps3MapV","text":"Map"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps3MapV11CoordinatorC","text":"Coordinator"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/map\/makecoordinator()"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapURLOpener":{"navigatorTitle":[{"kind":"identifier","text":"MapURLOpener"}],"title":"MapURLOpener","kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Handles url opening."}],"url":"\/documentation\/mapboxmaps\/mapurlopener","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapURLOpener","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapURLOpener"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PolylineAnnotationGroup":{"navigatorTitle":[{"kind":"identifier","text":"PolylineAnnotationGroup"}],"title":"PolylineAnnotationGroup","kind":"symbol","url":"\/documentation\/mapboxmaps\/polylineannotationgroup","abstract":[],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PolylineAnnotationGroup","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"PolylineAnnotationGroup"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/View-Implementations":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/View-Implementations","title":"View Implementations","url":"\/documentation\/mapboxmaps\/map\/view-implementations","role":"collectionGroup","kind":"article","abstract":[],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/updateUIViewController(_:context:)":{"type":"topic","url":"\/documentation\/mapboxmaps\/map\/updateuiviewcontroller(_:context:)","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateUIViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Map","preciseIdentifier":"s:10MapboxMaps3MapV"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Context","preciseIdentifier":"s:7SwiftUI29UIViewControllerRepresentableP7Contexta"},{"kind":"text","text":")"}],"title":"updateUIViewController(_:context:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/updateUIViewController(_:context:)","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/mapStyle(_:)":{"abstract":[{"type":"text","text":"Sets style to the map."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mapStyle"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MapStyle","preciseIdentifier":"s:10MapboxMaps8MapStyleV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Map","preciseIdentifier":"s:10MapboxMaps3MapV"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/map\/mapstyle(_:)","title":"mapStyle(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/mapStyle(_:)","kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/onSourceDataLoaded(action:)":{"kind":"symbol","title":"onSourceDataLoaded(action:)","url":"\/documentation\/mapboxmaps\/map\/onsourcedataloaded(action:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onSourceDataLoaded(action:)","role":"symbol","abstract":[{"text":"Adds an action to perform when the source data is loaded.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSourceDataLoaded"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMSourceDataLoaded","text":"SourceDataLoaded"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps3MapV","text":"Map"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/gestureOptions(_:)":{"url":"\/documentation\/mapboxmaps\/map\/gestureoptions(_:)","title":"gestureOptions(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gestureOptions","kind":"identifier"},{"text":"(","kind":"text"},{"text":"GestureOptions","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps14GestureOptionsV"},{"text":") -> ","kind":"text"},{"text":"Map","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps3MapV"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Configures gesture options."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/gestureOptions(_:)"},"https://www.mapbox.com/blog/standard-core-style":{"url":"https:\/\/www.mapbox.com\/blog\/standard-core-style","type":"link","identifier":"https:\/\/www.mapbox.com\/blog\/standard-core-style","title":"Mapbox Standard","titleInlineContent":[{"type":"text","text":"Mapbox Standard"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/viewportMode(_:)":{"type":"topic","abstract":[{"text":"Sets viewport mode to the map.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/viewportMode(_:)","title":"viewportMode(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewportMode","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ViewportMode","preciseIdentifier":"c:@E@MBMViewportMode","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Map","preciseIdentifier":"s:10MapboxMaps3MapV","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/map\/viewportmode(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewportAnimation":{"navigatorTitle":[{"kind":"identifier","text":"ViewportAnimation"}],"title":"ViewportAnimation","role":"symbol","url":"\/documentation\/mapboxmaps\/viewportanimation","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ViewportAnimation"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportAnimation","abstract":[{"text":"Specifies the animation for the map ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Viewport","type":"reference"},{"text":".","type":"text"}],"kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapViewDebugOptions":{"url":"\/documentation\/mapboxmaps\/mapviewdebugoptions","navigatorTitle":[{"text":"MapViewDebugOptions","kind":"identifier"}],"type":"topic","kind":"symbol","title":"MapViewDebugOptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapViewDebugOptions","abstract":[{"type":"text","text":"Options for enabling debugging features in a map."}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapViewDebugOptions","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Declarative-Map-Styling":{"url":"\/documentation\/mapboxmaps\/declarative-map-styling","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Declarative-Map-Styling","title":"Declarative Map Styling","role":"article","kind":"article","abstract":[{"type":"text","text":"Simplify runtime style manipulation with declarative syntax."}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/UIViewControllerRepresentable-Implementations":{"url":"\/documentation\/mapboxmaps\/map\/uiviewcontrollerrepresentable-implementations","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/UIViewControllerRepresentable-Implementations","abstract":[],"role":"collectionGroup","title":"UIViewControllerRepresentable Implementations","type":"topic","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/additionalSafeAreaInsets(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"additionalSafeAreaInsets"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"EdgeInsets","preciseIdentifier":"s:7SwiftUI10EdgeInsetsV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Map","preciseIdentifier":"s:10MapboxMaps3MapV"}],"role":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/map\/additionalsafeareainsets(_:)","title":"additionalSafeAreaInsets(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/additionalSafeAreaInsets(_:)","kind":"symbol","abstract":[{"type":"text","text":"Amount of additional safe area insets."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapGestureHandlers":{"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapGestureHandlers"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapGestureHandlers","title":"MapGestureHandlers","abstract":[{"text":"Creates handlers that will be called when the map gestures such as Pan, Pinch, Rotate, Zoom and others happen.","type":"text"}],"url":"\/documentation\/mapboxmaps\/mapgesturehandlers","navigatorTitle":[{"kind":"identifier","text":"MapGestureHandlers"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapProxy":{"type":"topic","kind":"symbol","title":"MapProxy","abstract":[{"text":"A proxy for access map interfaces on underlying Mapbox Map.","type":"text"}],"url":"\/documentation\/mapboxmaps\/mapproxy","navigatorTitle":[{"text":"MapProxy","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapProxy","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapProxy","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/screenCullingShape(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"screenCullingShape","kind":"identifier"},{"text":"([","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"},{"text":"]) -> ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps3MapV","text":"Map","kind":"typeIdentifier"}],"tags":[{"type":"spi","text":"SPI"}],"type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/map\/screencullingshape(_:)","title":"screenCullingShape(_:)","abstract":[{"text":"A convex polygon that describes the shape of the screen in case it is non-rectangular.","type":"text"},{"text":" ","type":"text"},{"text":"Every coordinate is in 0 to 1 range, with (0, 0) being the map view top-left and (1, 1) the bottom-right.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The points have to be given in clockwise winding order. The polygon will be closed automatically, so for a rectangular shape, pass in 4 points."},{"type":"text","text":" "},{"type":"text","text":"Use this if the visible screen area is obscured enough that using a custom shape improves performance."}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/screenCullingShape(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/onRenderFrameFinished(action:)":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/map\/onrenderframefinished(action:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onRenderFrameFinished(action:)","title":"onRenderFrameFinished(action:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onRenderFrameFinished"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMRenderFrameFinished","text":"RenderFrameFinished"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps3MapV","text":"Map"}],"role":"symbol","abstract":[{"type":"text","text":"Adds an action to perform when the map finished rendering a frame."}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/withViewportAnimation(_:body:completion:)":{"title":"withViewportAnimation(_:body:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"withViewportAnimation","kind":"identifier"},{"text":"<","kind":"text"},{"text":"Result","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"ViewportAnimation","preciseIdentifier":"s:10MapboxMaps17ViewportAnimationV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"body","kind":"externalParam"},{"text":": () ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"Result","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?) ","kind":"text"},{"text":"rethrows","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"Result","kind":"typeIdentifier"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/withviewportanimation(_:body:completion:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/withViewportAnimation(_:body:completion:)","kind":"symbol","abstract":[{"type":"text","text":"Applies the animation to the map viewport."}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/init(initialViewport:)":{"abstract":[{"text":"Creates a map an initial viewport.","type":"text"}],"url":"\/documentation\/mapboxmaps\/map\/init(initialviewport:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/init(initialViewport:)","type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"initialViewport","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Viewport","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps8ViewportV"},{"text":")","kind":"text"}],"title":"init(initialViewport:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapContentBuilder":{"url":"\/documentation\/mapboxmaps\/mapcontentbuilder","title":"MapContentBuilder","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapContentBuilder"}],"role":"symbol","abstract":[{"type":"text","text":"A result builder that creates map and style content from closures you provide."},{"type":"text","text":" "},{"type":"text","text":"Allows to mix content which is used in  StyleDSL API "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Declarative-Map-Styling","isActive":true,"type":"reference"},{"type":"text","text":" and in SwiftUI API "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SwiftUI-User-Guide","isActive":true,"type":"reference"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapContentBuilder","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MapContentBuilder"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ConditionalMapContent":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConditionalMapContent","kind":"identifier"}],"kind":"symbol","type":"topic","title":"ConditionalMapContent","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ConditionalMapContent","navigatorTitle":[{"text":"ConditionalMapContent","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/conditionalmapcontent","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/transitionsToIdleUponUserInteraction(_:)":{"title":"transitionsToIdleUponUserInteraction(_:)","url":"\/documentation\/mapboxmaps\/map\/transitionstoidleuponuserinteraction(_:)","abstract":[{"text":"Indicates whether the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Viewport"},{"text":" should idle when map receives pan touch input.","type":"text"}],"kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transitionsToIdleUponUserInteraction","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"text":"Map","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps3MapV"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/transitionsToIdleUponUserInteraction(_:)","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/additionalSafeAreaInsets(_:_:)":{"title":"additionalSafeAreaInsets(_:_:)","abstract":[{"type":"text","text":"Sets the amount of additional safe area insets for the given edges."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/additionalSafeAreaInsets(_:_:)","type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/map\/additionalsafeareainsets(_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"additionalSafeAreaInsets"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Edge","preciseIdentifier":"s:7SwiftUI4EdgeO"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:7SwiftUI4EdgeO3SetV"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Map","preciseIdentifier":"s:10MapboxMaps3MapV"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/onSourceRemoved(action:)":{"kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Adds an action to perform when a source is removed."}],"title":"onSourceRemoved(action:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onSourceRemoved(action:)","url":"\/documentation\/mapboxmaps\/map\/onsourceremoved(action:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSourceRemoved"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMSourceRemoved","text":"SourceRemoved"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps3MapV","text":"Map"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/init(viewport:)":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/init(viewport:)","title":"init(viewport:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"viewport"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Binding","preciseIdentifier":"s:7SwiftUI7BindingV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Viewport","preciseIdentifier":"s:10MapboxMaps8ViewportV"},{"kind":"text","text":">)"}],"abstract":[{"type":"text","text":"Creates a map with a viewport binding."}],"kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/map\/init(viewport:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapStyle":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapStyle"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/mapstyle","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapStyle","role":"symbol","abstract":[{"type":"text","text":"Map style configuration."}],"navigatorTitle":[{"kind":"identifier","text":"MapStyle"}],"type":"topic","title":"MapStyle"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/gestureHandlers(_:)":{"title":"gestureHandlers(_:)","kind":"symbol","abstract":[{"type":"text","text":"Sets handlers for common map gestures such as Pan, Pinch, Rotate, Zoom and others."}],"role":"symbol","url":"\/documentation\/mapboxmaps\/map\/gesturehandlers(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/gestureHandlers(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gestureHandlers","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps18MapGestureHandlersV","text":"MapGestureHandlers","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps3MapV","text":"Map","kind":"typeIdentifier"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PolygonAnnotation":{"title":"PolygonAnnotation","url":"\/documentation\/mapboxmaps\/polygonannotation","role":"symbol","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"PolygonAnnotation"}],"navigatorTitle":[{"kind":"identifier","text":"PolygonAnnotation"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PolygonAnnotation","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/onCameraChanged(action:)":{"type":"topic","title":"onCameraChanged(action:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onCameraChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"kind":"text","text":": ("},{"preciseIdentifier":"c:objc(cs)MBMCameraChanged","kind":"typeIdentifier","text":"CameraChanged"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:10MapboxMaps3MapV","kind":"typeIdentifier","text":"Map"}],"abstract":[{"text":"Adds an action to perform when the camera is changed.","type":"text"}],"url":"\/documentation\/mapboxmaps\/map\/oncamerachanged(action:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onCameraChanged(action:)","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapView":{"url":"\/documentation\/mapboxmaps\/mapview","type":"topic","navigatorTitle":[{"text":"MapView","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapView","kind":"identifier"}],"abstract":[],"title":"MapView","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/onResourceRequest(action:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onResourceRequest(action:)","abstract":[{"type":"text","text":"Adds an action to perform when a resource request is performed."}],"url":"\/documentation\/mapboxmaps\/map\/onresourcerequest(action:)","kind":"symbol","type":"topic","title":"onResourceRequest(action:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onResourceRequest"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"kind":"text","text":": ("},{"preciseIdentifier":"c:objc(cs)MBMResourceRequest","kind":"typeIdentifier","text":"ResourceRequest"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:10MapboxMaps3MapV","kind":"typeIdentifier","text":"Map"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map","url":"\/documentation\/mapboxmaps\/map","role":"symbol","type":"topic","title":"Map","kind":"symbol","abstract":[{"type":"text","text":"A SwiftUI view that displays a Mapbox Map."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Map"}],"navigatorTitle":[{"text":"Map","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Puck3D":{"navigatorTitle":[{"kind":"identifier","text":"Puck3D"}],"url":"\/documentation\/mapboxmaps\/puck3d","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Puck3D"}],"type":"topic","role":"symbol","kind":"symbol","title":"Puck3D","abstract":[{"type":"text","text":"Displays user location via 3D Puck."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3D"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/EmptyMapContent":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/EmptyMapContent","url":"\/documentation\/mapboxmaps\/emptymapcontent","role":"symbol","type":"topic","title":"EmptyMapContent","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"EmptyMapContent"}],"navigatorTitle":[{"kind":"identifier","text":"EmptyMapContent"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/onMapIdle(action:)":{"type":"topic","title":"onMapIdle(action:)","url":"\/documentation\/mapboxmaps\/map\/onmapidle(action:)","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onMapIdle(action:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMapIdle"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"MapIdle","preciseIdentifier":"c:objc(cs)MBMMapIdle"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Map","preciseIdentifier":"s:10MapboxMaps3MapV"}],"abstract":[{"type":"text","text":"Adds an action to perform when the map has entered the idle state."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Viewport/FollowPuckOptions":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Viewport\/FollowPuckOptions","navigatorTitle":[{"text":"FollowPuckOptions","kind":"identifier"}],"title":"Viewport.FollowPuckOptions","type":"topic","abstract":[{"text":"Options for the follow puck viewport.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FollowPuckOptions","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/viewport\/followpuckoptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SwiftUI":{"kind":"article","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/swiftui","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SwiftUI","type":"topic","title":"SwiftUI"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PointAnnotation":{"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"PointAnnotation"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PointAnnotation","navigatorTitle":[{"kind":"identifier","text":"PointAnnotation"}],"abstract":[],"url":"\/documentation\/mapboxmaps\/pointannotation","kind":"symbol","title":"PointAnnotation","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/onTapGesture(count:perform:)":{"url":"\/documentation\/mapboxmaps\/map\/ontapgesture(count:perform:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onTapGesture"},{"kind":"text","text":"("},{"kind":"externalParam","text":"count"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"perform"},{"kind":"text","text":": () -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"preciseIdentifier":"s:7SwiftUI4ViewP","kind":"typeIdentifier","text":"View"}],"title":"onTapGesture(count:perform:)","role":"symbol","kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onTapGesture(count:perform:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/onMapLoadingError(action:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onMapLoadingError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"action","kind":"externalParam"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"MapLoadingError","preciseIdentifier":"c:objc(cs)MBMMapLoadingError"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Map","preciseIdentifier":"s:10MapboxMaps3MapV"}],"kind":"symbol","type":"topic","title":"onMapLoadingError(action:)","role":"symbol","abstract":[{"text":"Adds an action to perform when there is an error occurred while loading the map.","type":"text"}],"url":"\/documentation\/mapboxmaps\/map\/onmaploadingerror(action:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onMapLoadingError(action:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapViewAnnotation":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapViewAnnotation"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapViewAnnotation","url":"\/documentation\/mapboxmaps\/mapviewannotation","abstract":[{"type":"text","text":"Displays a view annotation."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MapViewAnnotation"}],"title":"MapViewAnnotation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OrnamentOptions":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OrnamentOptions","role":"symbol","abstract":[{"type":"text","text":"Used to configure Ornament-specific capabilities of the map"}],"url":"\/documentation\/mapboxmaps\/ornamentoptions","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OrnamentOptions","kind":"identifier"}],"navigatorTitle":[{"text":"OrnamentOptions","kind":"identifier"}],"title":"OrnamentOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/onLayerTapGesture(_:perform:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onLayerTapGesture","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"perform","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MapLayerGestureHandler","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps22MapLayerGestureHandlera"},{"text":") -> ","kind":"text"},{"text":"Map","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps3MapV"}],"title":"onLayerTapGesture(_:perform:)","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onLayerTapGesture(_:perform:)","role":"symbol","url":"\/documentation\/mapboxmaps\/map\/onlayertapgesture(_:perform:)","abstract":[{"text":"Adds a tap action to the specified layer.","type":"text"}],"deprecated":true},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/init(initialViewport:urlOpener:content:)":{"abstract":[{"type":"text","text":"Creates a map an initial viewport."}],"url":"\/documentation\/mapboxmaps\/map\/init(initialviewport:urlopener:content:)","title":"init(initialViewport:urlOpener:content:)","type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"initialViewport"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Viewport","preciseIdentifier":"s:10MapboxMaps8ViewportV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"urlOpener"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MapURLOpener","preciseIdentifier":"s:10MapboxMaps12MapURLOpenera"},{"kind":"text","text":", "},{"kind":"externalParam","text":"content"},{"kind":"text","text":": () -> some "},{"kind":"typeIdentifier","text":"MapContent","preciseIdentifier":"s:10MapboxMaps10MapContentP"},{"kind":"text","text":")"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/init(initialViewport:urlOpener:content:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/init(viewport:content:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/init(viewport:content:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"viewport"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Binding","preciseIdentifier":"s:7SwiftUI7BindingV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Viewport","preciseIdentifier":"s:10MapboxMaps8ViewportV"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"content"},{"kind":"text","text":": () -> some "},{"kind":"typeIdentifier","text":"MapContent","preciseIdentifier":"s:10MapboxMaps10MapContentP"},{"kind":"text","text":")"}],"type":"topic","title":"init(viewport:content:)","abstract":[{"type":"text","text":"Creates a map that displays annotations."}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/map\/init(viewport:content:)","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/onStyleLoaded(action:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onStyleLoaded"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"StyleLoaded","preciseIdentifier":"c:objc(cs)MBMStyleLoaded"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Map","preciseIdentifier":"s:10MapboxMaps3MapV"}],"abstract":[{"type":"text","text":"Adds an action to perform when the requested style is fully loaded."}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onStyleLoaded(action:)","url":"\/documentation\/mapboxmaps\/map\/onstyleloaded(action:)","role":"symbol","title":"onStyleLoaded(action:)","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/onLayerLongPressGesture(_:perform:)":{"abstract":[{"text":"Adds a long-press action to the specified layer.","type":"text"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onLayerLongPressGesture","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"perform","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MapLayerGestureHandler","preciseIdentifier":"s:10MapboxMaps22MapLayerGestureHandlera","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Map","preciseIdentifier":"s:10MapboxMaps3MapV","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onLayerLongPressGesture(_:perform:)","deprecated":true,"url":"\/documentation\/mapboxmaps\/map\/onlayerlongpressgesture(_:perform:)","title":"onLayerLongPressGesture(_:perform:)","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ArrayBuilder":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ArrayBuilder","url":"\/documentation\/mapboxmaps\/arraybuilder","role":"symbol","type":"topic","title":"ArrayBuilder","kind":"symbol","abstract":[{"type":"text","text":"A result builder that creates array of homogenous elements."},{"type":"text","text":" "},{"type":"text","text":"If element is missing, the resulting array leaves nil gaps."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ArrayBuilder","kind":"identifier"}],"navigatorTitle":[{"text":"ArrayBuilder","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ForEvery":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ForEvery"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/forevery","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ForEvery","title":"ForEvery","navigatorTitle":[{"kind":"identifier","text":"ForEvery"}],"abstract":[{"type":"text","text":"A structure that creates map content from an underlying collection of identified data."}],"role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TupleMapContent":{"type":"topic","kind":"symbol","title":"TupleMapContent","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TupleMapContent","url":"\/documentation\/mapboxmaps\/tuplemapcontent","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TupleMapContent","kind":"identifier"}],"navigatorTitle":[{"text":"TupleMapContent","kind":"identifier"}],"abstract":[],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PointAnnotationGroup":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PointAnnotationGroup","url":"\/documentation\/mapboxmaps\/pointannotationgroup","role":"symbol","abstract":[],"navigatorTitle":[{"text":"PointAnnotationGroup","kind":"identifier"}],"title":"PointAnnotationGroup","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PointAnnotationGroup","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PolylineAnnotation":{"url":"\/documentation\/mapboxmaps\/polylineannotation","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PolylineAnnotation","kind":"identifier"}],"title":"PolylineAnnotation","navigatorTitle":[{"text":"PolylineAnnotation","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PolylineAnnotation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Viewport":{"navigatorTitle":[{"kind":"identifier","text":"Viewport"}],"role":"symbol","abstract":[{"type":"text","text":"Viewport represents the ways to position camera."}],"kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/viewport","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Viewport","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Viewport"}],"title":"Viewport"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/init(viewport:urlOpener:content:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"viewport"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Binding","preciseIdentifier":"s:7SwiftUI7BindingV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Viewport","preciseIdentifier":"s:10MapboxMaps8ViewportV"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"urlOpener"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MapURLOpener","preciseIdentifier":"s:10MapboxMaps12MapURLOpenera"},{"kind":"text","text":", "},{"kind":"externalParam","text":"content"},{"kind":"text","text":": () -> some "},{"kind":"typeIdentifier","text":"MapContent","preciseIdentifier":"s:10MapboxMaps10MapContentP"},{"kind":"text","text":")"}],"role":"symbol","abstract":[{"text":"Creates a map with a viewport binding.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/init(viewport:urlOpener:content:)","title":"init(viewport:urlOpener:content:)","kind":"symbol","url":"\/documentation\/mapboxmaps\/map\/init(viewport:urlopener:content:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/usesSafeAreaInsetsAsPadding(_:)":{"title":"usesSafeAreaInsetsAsPadding(_:)","role":"symbol","url":"\/documentation\/mapboxmaps\/map\/usessafeareainsetsaspadding(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"usesSafeAreaInsetsAsPadding"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Map","preciseIdentifier":"s:10MapboxMaps3MapV"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/usesSafeAreaInsetsAsPadding(_:)","type":"topic","abstract":[{"text":"When ","type":"text"},{"code":"true","type":"codeVoice"},{"text":", all viewport states increase the camera padding by the amount of the safe area insets.","type":"text"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","role":"collection","title":"MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/onSourceAdded(action:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onSourceAdded(action:)","role":"symbol","abstract":[{"text":"Adds an action to perform when a source is added.","type":"text"}],"type":"topic","title":"onSourceAdded(action:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onSourceAdded","kind":"identifier"},{"text":"(","kind":"text"},{"text":"action","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"SourceAdded","preciseIdentifier":"c:objc(cs)MBMSourceAdded","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Map","preciseIdentifier":"s:10MapboxMaps3MapV","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/map\/onsourceadded(action:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/NorthOrientation":{"url":"\/documentation\/mapboxmaps\/northorientation","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NorthOrientation"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/NorthOrientation","kind":"symbol","abstract":[{"type":"text","text":"Describes the map orientation."}],"title":"NorthOrientation","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"NorthOrientation"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/onMapLoaded(action:)":{"title":"onMapLoaded(action:)","url":"\/documentation\/mapboxmaps\/map\/onmaploaded(action:)","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onMapLoaded(action:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onMapLoaded","kind":"identifier"},{"text":"(","kind":"text"},{"text":"action","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMMapLoaded","text":"MapLoaded","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps3MapV","text":"Map","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Adds an action to perform when the map is loaded."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Viewport/OverviewOptions":{"abstract":[{"text":"Options for the overview viewport.","type":"text"}],"url":"\/documentation\/mapboxmaps\/viewport\/overviewoptions","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Viewport\/OverviewOptions","navigatorTitle":[{"kind":"identifier","text":"OverviewOptions"}],"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"OverviewOptions"}],"type":"topic","title":"Viewport.OverviewOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CircleAnnotationGroup":{"navigatorTitle":[{"text":"CircleAnnotationGroup","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CircleAnnotationGroup","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/circleannotationgroup","kind":"symbol","role":"symbol","type":"topic","title":"CircleAnnotationGroup","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CircleAnnotationGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/debugOptions(_:)":{"url":"\/documentation\/mapboxmaps\/map\/debugoptions(_:)","abstract":[{"type":"text","text":"Sets "},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapViewDebugOptions","isActive":true},{"type":"text","text":" to the map."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"debugOptions"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MapViewDebugOptions","preciseIdentifier":"s:10MapboxMaps19MapViewDebugOptionsV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Map","preciseIdentifier":"s:10MapboxMaps3MapV"}],"type":"topic","role":"symbol","title":"debugOptions(_:)","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/debugOptions(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SwiftUI-User-Guide":{"role":"article","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SwiftUI-User-Guide","abstract":[{"text":"Use Mapbox Maps in SwiftUI applications.","type":"text"}],"url":"\/documentation\/mapboxmaps\/swiftui-user-guide","title":"SwiftUI User Guide","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FeatureState":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FeatureState"}],"navigatorTitle":[{"kind":"identifier","text":"FeatureState"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeatureState","abstract":[{"text":"Sets the feature state to a feature in the SwiftUI  ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map","isActive":true,"type":"reference"},{"text":".","type":"text"}],"type":"topic","role":"symbol","title":"FeatureState","kind":"symbol","url":"\/documentation\/mapboxmaps\/featurestate"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/removeImage(withId:)":{"url":"\/documentation\/mapboxmaps\/stylemanager\/removeimage(withid:)","kind":"symbol","type":"topic","title":"removeImage(withId:)","abstract":[{"type":"text","text":"Removes an image from the style."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/removeImage(withId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/collectPerformanceStatistics(_:callback:)":{"title":"collectPerformanceStatistics(_:callback:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/collectPerformanceStatistics(_:callback:)","role":"symbol","kind":"symbol","url":"\/documentation\/mapboxmaps\/map\/collectperformancestatistics(_:callback:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"collectPerformanceStatistics","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PerformanceStatisticsOptions","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMPerformanceStatisticsOptions"},{"text":"?, ","kind":"text"},{"text":"callback","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"PerformanceStatistics","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMPerformanceStatistics"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":") -> ","kind":"text"},{"text":"Map","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps3MapV"}],"type":"topic","abstract":[{"type":"text","text":"Collects CPU, GPU resource usage and timings of layers and rendering groups over a user-configurable sampling duration."},{"type":"text","text":" "},{"type":"text","text":"Use the collected information to find which layers or rendering groups might be performing poorly."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MBMNorthOrientation","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1NorthOrientation\/title"},{"value":[{"kind":"identifier","text":"MBMNorthOrientation"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1NorthOrientation\/fragments"},{"value":[{"text":"MBMNorthOrientation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1NorthOrientation\/navigatorTitle"}]}]}