{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/styleobjectinfo"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/styleobjectinfo"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleObjectInfo"},"metadata":{"role":"symbol","externalID":"c:objc(cs)MBMStyleObjectInfo","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StyleObjectInfo","kind":"identifier"}],"title":"StyleObjectInfo","roleHeading":"Class","symbolKind":"class","modules":[{"name":"MapboxMaps"}],"navigatorTitle":[{"text":"StyleObjectInfo","kind":"identifier"}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StyleObjectInfo","kind":"identifier"}],"languages":["swift"]}]}],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"]},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH"]}],"topicSections":[{"anchor":"Initializers","generated":true,"title":"Initializers","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleObjectInfo\/init(id:type:)"]},{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleObjectInfo\/id","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleObjectInfo\/type"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs"]]},"abstract":[{"text":"The information about style object (source or layer or light).","type":"text"}],"seeAlsoSections":[{"anchor":"Style-pack","generated":true,"title":"Style pack","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePack","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackError-swift.enum","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadProgress"]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePackLoadProgress":{"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"style pack load"},{"type":"text","text":" progress includes information about"},{"type":"text","text":" "},{"type":"text","text":"the number of resources that have completed downloading"},{"type":"text","text":" "},{"type":"text","text":"and the total number of resources that are required."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadProgress","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StylePackLoadProgress","kind":"identifier"}],"title":"StylePackLoadProgress","navigatorTitle":[{"text":"StylePackLoadProgress","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/stylepackloadprogress"},"doc://com.mapbox.MapboxMaps/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","abstract":[],"type":"topic","title":"MapboxMaps Documentation","kind":"article","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleObjectInfo/init(id:type:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleObjectInfo\/init(id:type:)","title":"init(id:type:)","type":"topic","abstract":[],"role":"symbol","navigatorTitle":[{"text":"initWithId:type:","kind":"identifier"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/styleobjectinfo\/init(id:type:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePackLoadOptions":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StylePackLoadOptions"}],"navigatorTitle":[{"kind":"identifier","text":"StylePackLoadOptions"}],"title":"StylePackLoadOptions","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadOptions","url":"\/documentation\/mapboxmaps\/stylepackloadoptions","kind":"symbol","type":"topic","abstract":[{"text":"Describes the style package load option values.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePackError-swift.enum":{"role":"symbol","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StylePackError","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackError-swift.enum","title":"StylePackError","abstract":[{"type":"text","text":"Describes the reason for a style package download request failure."}],"url":"\/documentation\/mapboxmaps\/stylepackerror-swift.enum","navigatorTitle":[{"text":"StylePackError","kind":"identifier"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","role":"collection","title":"MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH"},"doc://com.mapbox.MapboxMaps/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP"},"doc://com.mapbox.MapboxMaps/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleObjectInfo":{"kind":"symbol","role":"symbol","abstract":[{"text":"The information about style object (source or layer or light).","type":"text"}],"url":"\/documentation\/mapboxmaps\/styleobjectinfo","type":"topic","title":"StyleObjectInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StyleObjectInfo"}],"navigatorTitle":[{"kind":"identifier","text":"StyleObjectInfo"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleObjectInfo"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePack":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StylePack"}],"title":"StylePack","url":"\/documentation\/mapboxmaps\/stylepack","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StylePack"}],"abstract":[{"type":"text","text":"The "},{"code":"style pack","type":"codeVoice"},{"type":"text","text":" represents a stored style package."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePack"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleObjectInfo/id":{"title":"id","url":"\/documentation\/mapboxmaps\/styleobjectinfo\/id","role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"id"}],"abstract":[{"text":"The object’s identifier.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleObjectInfo\/id","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","type":"topic","kind":"article","title":"TileStore APIs","role":"collectionGroup","abstract":[],"url":"\/documentation\/mapboxmaps\/tilestore-apis"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleObjectInfo/type":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"abstract":[{"type":"text","text":"The object’s type."}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleObjectInfo\/type","title":"type","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"type"}],"url":"\/documentation\/mapboxmaps\/styleobjectinfo\/type"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MBMStyleObjectInfo"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MBMStyleObjectInfo","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"MBMStyleObjectInfo","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleObjectInfo\/id","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleObjectInfo\/type"],"title":"Instance Properties"},{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleObjectInfo\/init(id:type:)"],"title":"Instance Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"generated":true,"title":"Style pack","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePack","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadProgress"],"anchor":"Style-pack"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBMStyleObjectInfo","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadProgress\/title","value":"MBMStylePackLoadProgress"},{"value":[{"text":"MBMStylePackLoadProgress","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadProgress\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MBMStylePackLoadProgress"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadProgress\/navigatorTitle","op":"replace"},{"value":"initWithId:type:","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleObjectInfo~1init(id:type:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithId:type:"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleObjectInfo~1init(id:type:)\/fragments","op":"replace"},{"value":"MBMStylePackLoadOptions","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadOptions\/title","op":"replace"},{"value":[{"text":"MBMStylePackLoadOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadOptions\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MBMStylePackLoadOptions"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadOptions\/navigatorTitle","op":"replace"},{"value":"MBMStyleObjectInfo","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleObjectInfo\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MBMStyleObjectInfo"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleObjectInfo\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MBMStyleObjectInfo"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleObjectInfo\/navigatorTitle","op":"replace"},{"value":"MBMStylePack","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePack\/title","op":"replace"},{"value":[{"text":"MBMStylePack","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePack\/fragments","op":"replace"},{"value":[{"text":"MBMStylePack","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePack\/navigatorTitle","op":"replace"},{"value":"id","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleObjectInfo~1id\/title","op":"replace"},{"value":[{"kind":"identifier","text":"id"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleObjectInfo~1id\/fragments","op":"replace"},{"value":"type","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleObjectInfo~1type\/title","op":"replace"},{"value":[{"kind":"identifier","text":"type"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleObjectInfo~1type\/fragments","op":"replace"}]}]}