{"kind":"symbol","metadata":{"role":"symbol","roleHeading":"Class","externalID":"c:objc(cs)MBMStyleImageRemoveUnused","modules":[{"name":"MapboxMaps"}],"navigatorTitle":[{"kind":"identifier","text":"StyleImageRemoveUnused"}],"title":"StyleImageRemoveUnused","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StyleImageRemoveUnused"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"generated":true,"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnused\/init(imageId:timestamp:)"]},{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnused\/imageId","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnused\/timestamp"]}],"seeAlsoSections":[{"generated":true,"anchor":"Events","title":"Events","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraChanged","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapIdle","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceAdded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceRemoved","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageMissing","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameStarted","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinished","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequest","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GenericEvent"]}],"abstract":[{"text":"An image requested by the ","type":"text"},{"type":"codeVoice","code":"map"},{"type":"text","text":" through the "},{"type":"codeVoice","code":"StyleImageMissing"},{"type":"text","text":" event is no longer"},{"type":"text","text":" "},{"type":"text","text":"needed and can be removed using the "},{"type":"codeVoice","code":"removeStyleImage"},{"type":"text","text":" method. The application can"},{"type":"text","text":" "},{"type":"text","text":"decide whether the image should be kept or removed."}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnused","interfaceLanguage":"swift"},"sections":[],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"]},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StyleImageRemoveUnused","kind":"identifier"}]}]},{"content":[{"type":"heading","level":2,"text":"Overview","anchor":"overview"},{"type":"paragraph","inlineContent":[{"text":"Note: If there are no subscribers for the ","type":"text"},{"code":"StyleImageRemoveUnused","type":"codeVoice"},{"text":" event, the ","type":"text"},{"code":"map","type":"codeVoice"},{"text":" ","type":"text"},{"text":"will automatically remove the unused image.","type":"text"}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/mapboxmaps\/styleimageremoveunused"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/styleimageremoveunused"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceDataLoaded":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoaded","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceDataLoaded"}],"url":"\/documentation\/mapboxmaps\/sourcedataloaded","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SourceDataLoaded"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"SourceDataLoaded"},{"type":"text","text":" event is emitted when source data is loaded."}],"title":"SourceDataLoaded"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","type":"topic","url":"\/documentation\/mapboxmaps\/events","kind":"article","role":"collectionGroup","title":"Map events","abstract":[{"type":"text","text":"The simplified diagram of the events emitted by the map is displayed below."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleLoaded":{"abstract":[{"text":"The requested style has been fully loaded, including specified sprite, and sources’ metadata.","type":"text"}],"title":"StyleLoaded","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleLoaded","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StyleLoaded","kind":"identifier"}],"navigatorTitle":[{"text":"StyleLoaded","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/styleloaded"},"doc://com.mapbox.MapboxMaps/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleImageMissing":{"kind":"symbol","title":"StyleImageMissing","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageMissing","url":"\/documentation\/mapboxmaps\/styleimagemissing","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StyleImageMissing","kind":"identifier"}],"abstract":[{"text":"A style needs an image that is missing from the sprite sheet. This event is","type":"text"},{"text":" ","type":"text"},{"text":"emitted when the ","type":"text"},{"code":"map","type":"codeVoice"},{"text":" renders visible tiles, and one of the required images","type":"text"},{"text":" ","type":"text"},{"text":"is missing in the sprite sheet. The event observer has to provide the missing","type":"text"},{"text":" ","type":"text"},{"text":"image by calling the ","type":"text"},{"code":"addStyleImage","type":"codeVoice"},{"text":" method.","type":"text"}],"navigatorTitle":[{"text":"StyleImageMissing","kind":"identifier"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleImageRemoveUnused/imageId":{"type":"topic","title":"imageId","navigatorTitle":[{"text":"imageId","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnused\/imageId","role":"symbol","url":"\/documentation\/mapboxmaps\/styleimageremoveunused\/imageid","abstract":[{"type":"text","text":"The identifier of an image that is not used by the "},{"type":"codeVoice","code":"map"},{"type":"text","text":"."}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderFrameStarted":{"title":"RenderFrameStarted","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RenderFrameStarted"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RenderFrameStarted"}],"abstract":[{"type":"text","text":"The "},{"code":"map","type":"codeVoice"},{"type":"text","text":" started rendering a frame."}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameStarted","url":"\/documentation\/mapboxmaps\/renderframestarted"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceRemoved":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceRemoved","url":"\/documentation\/mapboxmaps\/sourceremoved","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceRemoved"}],"navigatorTitle":[{"kind":"identifier","text":"SourceRemoved"}],"abstract":[{"type":"text","text":"The source has been removed with "},{"type":"codeVoice","code":"removeStyleSource"},{"type":"text","text":" method."}],"kind":"symbol","title":"SourceRemoved","type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleImageRemoveUnused/init(imageId:timestamp:)":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/styleimageremoveunused\/init(imageid:timestamp:)","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnused\/init(imageId:timestamp:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"imageId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"timestamp","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithImageId:timestamp:","kind":"identifier"}],"abstract":[],"title":"init(imageId:timestamp:)","role":"symbol"},"doc://com.mapbox.MapboxMaps/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResourceRequest":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequest","type":"topic","abstract":[{"type":"text","text":"The "},{"code":"ResourceRequest","type":"codeVoice"},{"type":"text","text":" event allows the application to observe resource requests made by a "},{"code":"map","type":"codeVoice"},{"type":"text","text":" or "},{"code":"map snapshotter","type":"codeVoice"},{"type":"text","text":" object."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ResourceRequest","kind":"identifier"}],"navigatorTitle":[{"text":"ResourceRequest","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/resourcerequest","kind":"symbol","title":"ResourceRequest","role":"symbol"},"doc://com.mapbox.MapboxMaps/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject"},"doc://com.mapbox.MapboxMaps/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleImageRemoveUnused/timestamp":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnused\/timestamp","kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"The timestamp of an event when the ","type":"text"},{"code":"map","type":"codeVoice"},{"text":" no longer needs a previously added image.","type":"text"}],"title":"timestamp","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timestamp","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"timestamp","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/styleimageremoveunused\/timestamp"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleDataLoaded":{"type":"topic","url":"\/documentation\/mapboxmaps\/styledataloaded","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StyleDataLoaded"}],"abstract":[{"type":"text","text":"The style data has been loaded. The event will be emitted once for each "},{"type":"codeVoice","code":"StyleDataLoadedType"},{"type":"text","text":" "},{"type":"text","text":"type during style loading. If a new style is set, events will be emitted again for the newly set style."}],"navigatorTitle":[{"kind":"identifier","text":"StyleDataLoaded"}],"title":"StyleDataLoaded","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoaded"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","role":"collection","title":"MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoadingError":{"role":"symbol","title":"MapLoadingError","navigatorTitle":[{"kind":"identifier","text":"MapLoadingError"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapLoadingError"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingError","abstract":[{"text":"Describes an error that has occurred while loading the ","type":"text"},{"code":"map","type":"codeVoice"},{"text":". The ","type":"text"},{"code":"type","type":"codeVoice"},{"text":" property","type":"text"},{"text":" ","type":"text"},{"text":"defines what resource could not be loaded, and the ","type":"text"},{"code":"message","type":"codeVoice"},{"text":" property will contain","type":"text"},{"text":" ","type":"text"},{"text":"a descriptive error message.","type":"text"}],"url":"\/documentation\/mapboxmaps\/maploadingerror"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GenericEvent":{"url":"\/documentation\/mapboxmaps\/genericevent","abstract":[{"type":"text","text":"The generic event type."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GenericEvent"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GenericEvent"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GenericEvent","title":"GenericEvent"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderFrameFinished":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"RenderFrameFinished"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/renderframefinished","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RenderFrameFinished"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"map"},{"type":"text","text":" finished rendering a frame."}],"title":"RenderFrameFinished","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinished"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraChanged":{"title":"CameraChanged","abstract":[{"type":"text","text":"This event is emitted whenever the visible viewport changes its size"},{"type":"text","text":" "},{"type":"text","text":"due to the invocation of the "},{"code":"setSize","type":"codeVoice"},{"type":"text","text":" and "},{"code":"setBounds","type":"codeVoice"},{"type":"text","text":" methods or when"},{"type":"text","text":" "},{"type":"text","text":"the camera is modified by calling camera methods. The event is emitted"},{"type":"text","text":" "},{"type":"text","text":"synchronously so that an updated camera state can be read immediately."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraChanged","url":"\/documentation\/mapboxmaps\/camerachanged","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraChanged","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"CameraChanged","kind":"identifier"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoaded":{"abstract":[{"text":"The style has been fully loaded, and the ","type":"text"},{"code":"map","type":"codeVoice"},{"text":" has rendered all visible tiles.","type":"text"},{"text":" ","type":"text"},{"text":"The event will be emitted only once for the current style. If it is required to","type":"text"},{"text":" ","type":"text"},{"text":"observe an event where all required resources are loaded or rendered, please","type":"text"},{"text":" ","type":"text"},{"text":"check the following events: ","type":"text"},{"code":"MapIdle","type":"codeVoice"},{"text":", ","type":"text"},{"code":"StyleDataLoaded","type":"codeVoice"},{"text":", and ","type":"text"},{"code":"RenderFrameFinished","type":"codeVoice"},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapLoaded"}],"role":"symbol","title":"MapLoaded","kind":"symbol","url":"\/documentation\/mapboxmaps\/maploaded","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MapLoaded"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoaded"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapIdle":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/mapidle","type":"topic","role":"symbol","title":"MapIdle","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MapIdle","kind":"identifier"}],"navigatorTitle":[{"text":"MapIdle","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapIdle","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"map"},{"text":" has entered the idle state. The ","type":"text"},{"type":"codeVoice","code":"map"},{"text":" is idle when there are no ongoing","type":"text"},{"text":" ","type":"text"},{"text":"animations, transitions and the ","type":"text"},{"type":"codeVoice","code":"map"},{"text":" has rendered all requested non-volatile tiles","type":"text"},{"text":" ","type":"text"},{"text":"(e.g., live traffic tiles). The event will not be emitted if ","type":"text"},{"type":"codeVoice","code":"setUserAnimationInProgress"},{"text":" ","type":"text"},{"text":"and \/ or ","type":"text"},{"type":"codeVoice","code":"setGestureInProgress"},{"text":" is set to ","type":"text"},{"type":"codeVoice","code":"true"},{"text":".","type":"text"}]},"doc://com.mapbox.MapboxMaps/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"},"doc://com.mapbox.MapboxMaps/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceAdded":{"role":"symbol","title":"SourceAdded","navigatorTitle":[{"kind":"identifier","text":"SourceAdded"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceAdded"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceAdded","abstract":[{"text":"The source has been added with ","type":"text"},{"type":"codeVoice","code":"addStyleSource"},{"text":" method.","type":"text"}],"url":"\/documentation\/mapboxmaps\/sourceadded"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","abstract":[],"type":"topic","title":"MapboxMaps Documentation","kind":"article","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleImageRemoveUnused":{"abstract":[{"type":"text","text":"An image requested by the "},{"type":"codeVoice","code":"map"},{"type":"text","text":" through the "},{"type":"codeVoice","code":"StyleImageMissing"},{"type":"text","text":" event is no longer"},{"type":"text","text":" "},{"type":"text","text":"needed and can be removed using the "},{"type":"codeVoice","code":"removeStyleImage"},{"type":"text","text":" method. The application can"},{"type":"text","text":" "},{"type":"text","text":"decide whether the image should be kept or removed."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnused","url":"\/documentation\/mapboxmaps\/styleimageremoveunused","title":"StyleImageRemoveUnused","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"StyleImageRemoveUnused"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StyleImageRemoveUnused"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MBMStyleImageRemoveUnused"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MBMStyleImageRemoveUnused","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"MBMStyleImageRemoveUnused","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnused\/imageId","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnused\/timestamp"],"title":"Instance Properties","generated":true},{"anchor":"Instance-Methods","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnused\/init(imageId:timestamp:)"],"title":"Instance Methods","generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"generated":true,"anchor":"Events","title":"Events","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraChanged","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapIdle","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceAdded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceRemoved","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageMissing","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameStarted","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinished","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequest","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GenericEvent"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBMStyleImageRemoveUnused","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoaded\/title","value":"MBMSourceDataLoaded"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoaded\/fragments","value":[{"kind":"identifier","text":"MBMSourceDataLoaded"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoaded\/navigatorTitle","value":[{"text":"MBMSourceDataLoaded","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoaded\/title","value":"MBMStyleLoaded"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoaded\/fragments","value":[{"text":"MBMStyleLoaded","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoaded\/navigatorTitle","value":[{"kind":"identifier","text":"MBMStyleLoaded"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageMissing\/title","value":"MBMStyleImageMissing"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageMissing\/fragments","value":[{"text":"MBMStyleImageMissing","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageMissing\/navigatorTitle","value":[{"text":"MBMStyleImageMissing","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnused~1imageId\/title","value":"imageId"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnused~1imageId\/fragments","value":[{"text":"imageId","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameStarted\/title","value":"MBMRenderFrameStarted"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameStarted\/fragments","value":[{"text":"MBMRenderFrameStarted","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameStarted\/navigatorTitle","value":[{"text":"MBMRenderFrameStarted","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceRemoved\/title","value":"MBMSourceRemoved"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceRemoved\/fragments","value":[{"kind":"identifier","text":"MBMSourceRemoved"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceRemoved\/navigatorTitle","value":[{"kind":"identifier","text":"MBMSourceRemoved"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnused~1init(imageId:timestamp:)\/title","value":"initWithImageId:timestamp:"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnused~1init(imageId:timestamp:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithImageId:timestamp:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequest\/title","value":"MBMResourceRequest"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequest\/fragments","value":[{"text":"MBMResourceRequest","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequest\/navigatorTitle","value":[{"text":"MBMResourceRequest","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnused~1timestamp\/title","value":"timestamp"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnused~1timestamp\/fragments","value":[{"kind":"identifier","text":"timestamp"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoaded\/title","value":"MBMStyleDataLoaded"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoaded\/fragments","value":[{"kind":"identifier","text":"MBMStyleDataLoaded"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoaded\/navigatorTitle","value":[{"text":"MBMStyleDataLoaded","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingError\/title","value":"MBMMapLoadingError"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingError\/fragments","value":[{"text":"MBMMapLoadingError","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingError\/navigatorTitle","value":[{"text":"MBMMapLoadingError","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEvent\/title","value":"MBMGenericEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEvent\/fragments","value":[{"kind":"identifier","text":"MBMGenericEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEvent\/navigatorTitle","value":[{"kind":"identifier","text":"MBMGenericEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinished\/title","value":"MBMRenderFrameFinished"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinished\/fragments","value":[{"text":"MBMRenderFrameFinished","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinished\/navigatorTitle","value":[{"text":"MBMRenderFrameFinished","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChanged\/title","value":"MBMCameraChanged"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChanged\/fragments","value":[{"text":"MBMCameraChanged","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChanged\/navigatorTitle","value":[{"text":"MBMCameraChanged","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoaded\/title","value":"MBMMapLoaded"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoaded\/fragments","value":[{"kind":"identifier","text":"MBMMapLoaded"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoaded\/navigatorTitle","value":[{"text":"MBMMapLoaded","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdle\/title","value":"MBMMapIdle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdle\/fragments","value":[{"text":"MBMMapIdle","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdle\/navigatorTitle","value":[{"text":"MBMMapIdle","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAdded\/title","value":"MBMSourceAdded"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAdded\/fragments","value":[{"kind":"identifier","text":"MBMSourceAdded"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAdded\/navigatorTitle","value":[{"text":"MBMSourceAdded","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnused\/title","value":"MBMStyleImageRemoveUnused"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnused\/fragments","value":[{"text":"MBMStyleImageRemoveUnused","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnused\/navigatorTitle","value":[{"text":"MBMStyleImageRemoveUnused","kind":"identifier"}]}]}]}