{"metadata":{"roleHeading":"API Collection","title":"Equatable Implementations","modules":[{"name":"MapboxMaps"}],"role":"collectionGroup"},"topicSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportMode\/!=(_:_:)"],"title":"Operators","generated":true,"anchor":"Operators"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"article","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportMode\/Equatable-Implementations"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-View","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportMode"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","role":"collection","title":"MapboxMaps","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map-View":{"kind":"article","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/map-view","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-View","abstract":[],"type":"topic","title":"MapView"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","kind":"article","abstract":[],"title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewportMode":{"title":"ViewportMode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ViewportMode","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportMode","type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/viewportmode","navigatorTitle":[{"kind":"identifier","text":"ViewportMode"}],"abstract":[{"type":"text","text":"Satisfies embedding platforms that requires the viewport coordinate systems to be set according to its standards."}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewportMode/!=(_:_:)":{"title":"!=(_:_:)","url":"\/documentation\/mapboxmaps\/viewportmode\/!=(_:_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"kind":"text","text":"("},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportMode\/!=(_:_:)","type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewportMode\/title","value":"MBMViewportMode","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewportMode\/fragments","value":[{"text":"MBMViewportMode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewportMode\/navigatorTitle","op":"replace","value":[{"text":"MBMViewportMode","kind":"identifier"}]}]}]}