{"metadata":{"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"navigation","kind":"identifier"}],"roleHeading":"Case","navigatorTitle":[{"text":"MBXTileDataDomainNavigation","kind":"identifier"}],"role":"symbol","modules":[{"name":"MapboxCommon"}],"externalID":"c:@E@MBXTileDataDomain@MBXTileDataDomainNavigation","title":"TileDataDomain.navigation"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileDataDomain"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileDataDomain\/navigation"},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Data for Navigation."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"navigation","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/mapboxcommon\/tiledatadomain\/navigation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxcommon\/tiledatadomain\/navigation"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","abstract":[],"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","type":"topic","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileDataDomain":{"role":"symbol","kind":"symbol","url":"\/documentation\/mapboxcommon\/tiledatadomain","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileDataDomain","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"TileDataDomain","kind":"identifier"}],"title":"TileDataDomain","abstract":[{"text":"Describes the tiles data domain.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileDataDomain"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"url":"\/documentation\/mapboxmaps\/tilestore-apis","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","abstract":[],"kind":"article","title":"TileStore APIs","type":"topic","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","role":"collection","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileDataDomain/navigation":{"role":"symbol","abstract":[{"text":"Data for Navigation.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileDataDomain\/navigation","url":"\/documentation\/mapboxcommon\/tiledatadomain\/navigation","title":"TileDataDomain.navigation","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"navigation","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"MBXTileDataDomainNavigation","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"MBXTileDataDomainNavigation","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"MBXTileDataDomainNavigation","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"MBXTileDataDomainNavigation","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MBXTileDataDomain","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileDataDomain\/title"},{"value":[{"text":"MBXTileDataDomain","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileDataDomain\/fragments"},{"value":[{"kind":"identifier","text":"MBXTileDataDomain"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileDataDomain\/navigatorTitle"},{"value":"MBXTileDataDomainNavigation","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileDataDomain~1navigation\/title"},{"value":[{"text":"MBXTileDataDomainNavigation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileDataDomain~1navigation\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}