{"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fontFamily","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Note: "},{"code":"GlyphsRasterizationMode","type":"codeVoice"},{"text":" has precedence over font family. If ","type":"text"},{"code":"AllGlyphsRasterizedLocally","type":"codeVoice"},{"type":"text","text":" "},{"text":"or ","type":"text"},{"type":"codeVoice","code":"IdeographsRasterizedLocally"},{"type":"text","text":" is set, local glyphs will be generated based on the provided font family. If no"},{"type":"text","text":" "},{"text":"font family is provided, the map will fall back to use the system default font. The mechanisms of choosing the","type":"text"},{"type":"text","text":" "},{"text":"default font are varied in platforms:","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"For darwin(iOS\/macOS) platform, the default font family is created from the "},{"text":"systemFont","type":"text"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"If provided fonts are not supported on darwin platform, the map will fall back to use the first available font from the global fallback list."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"For Android platform: the default font "},{"type":"text","text":"Typeface.DEFAULT"},{"type":"text","text":" will be used."}]}]}]},{"inlineContent":[{"type":"text","text":"Besides, the font family will be discarded if it is provided along with "},{"code":"NoGlyphsRasterizedLocally","type":"codeVoice"},{"text":" mode.","type":"text"}],"type":"paragraph"}]}],"metadata":{"modules":[{"name":"MapboxMaps"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fontFamily"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"title":"fontFamily","roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"text":"fontFamily","kind":"identifier"}],"externalID":"c:objc(cs)MBMGlyphsRasterizationOptions(py)fontFamily","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-View","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationOptions"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/glyphsrasterizationoptions\/fontfamily"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/glyphsrasterizationoptions\/fontfamily"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationOptions\/fontFamily"},"abstract":[{"type":"text","text":"Font family to use as font fallback for client-side text renderings."}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GlyphsRasterizationOptions/fontFamily":{"abstract":[{"type":"text","text":"Font family to use as font fallback for client-side text renderings."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"fontFamily","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"fontFamily","url":"\/documentation\/mapboxmaps\/glyphsrasterizationoptions\/fontfamily","kind":"symbol","navigatorTitle":[{"text":"fontFamily","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationOptions\/fontFamily","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map-View":{"url":"\/documentation\/mapboxmaps\/map-view","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-View","title":"MapView","type":"topic","role":"collectionGroup","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","abstract":[],"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","kind":"article","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GlyphsRasterizationOptions":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GlyphsRasterizationOptions","kind":"identifier"}],"navigatorTitle":[{"text":"GlyphsRasterizationOptions","kind":"identifier"}],"title":"GlyphsRasterizationOptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationOptions","kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/glyphsrasterizationoptions","abstract":[{"type":"text","text":"Describes the glyphs rasterization option values."}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"fontFamily"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"fontFamily","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"fontFamily"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationOptions~1fontFamily\/title","value":"fontFamily","op":"replace"},{"value":[{"text":"fontFamily","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationOptions~1fontFamily\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationOptions\/title","value":"MBMGlyphsRasterizationOptions","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationOptions\/fragments","op":"replace","value":[{"text":"MBMGlyphsRasterizationOptions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationOptions\/navigatorTitle","value":[{"kind":"identifier","text":"MBMGlyphsRasterizationOptions"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}