{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap"],["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/MapFeatureQueryable-Implementations"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/getGeoJsonClusterLeaves(forSourceId:feature:limit:offset:completion:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@discardableResult"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getGeoJsonClusterLeaves","kind":"identifier"},{"kind":"text","text":"("},{"text":"forSourceId","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"sourceId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"feature","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Feature","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps7Featurea","text":"Feature"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"limit"},{"text":": ","kind":"text"},{"text":"UInt64","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V"},{"kind":"text","text":" = 10, "},{"kind":"externalParam","text":"offset"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V","text":"UInt64"},{"text":" = 0, ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"text":"@escaping","kind":"keyword"},{"kind":"text","text":" ("},{"preciseIdentifier":"s:s6ResultO","text":"Result","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)MBMFeatureExtensionValue","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeatureExtensionValue","kind":"typeIdentifier","text":"FeatureExtensionValue"},{"kind":"text","text":", any "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":">) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> any "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Cancelable","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MBXCancelable","text":"Cancelable"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"sourceId","content":[{"inlineContent":[{"type":"text","text":"The identifier of the source to query."}],"type":"paragraph"}]},{"name":"feature","content":[{"inlineContent":[{"type":"text","text":"Feature to look for in the query."}],"type":"paragraph"}]},{"name":"limit","content":[{"inlineContent":[{"text":"The number of points to return from the query, default to 10","type":"text"}],"type":"paragraph"}]},{"name":"offset","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The amount of points to skip, default to 0"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The result could be a feature extension value containing"},{"type":"text","text":" "},{"type":"text","text":"either a value (expansion-zoom) or a feature collection (children"},{"text":" ","type":"text"},{"text":"or leaves). An error is passed if the operation was not successful.","type":"text"}]}],"name":"completion"}]}],"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/mapboxmap\/getgeojsonclusterleaves(forsourceid:feature:limit:offset:completion:)"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Returns all the leaves (original points) of a cluster (given its cluster_id) from a GeoJSON source, with pagination support: limit is the number of leaves"},{"text":" ","type":"text"},{"type":"text","text":"to return (set to Infinity for all points), and offset is the amount of points to skip (for pagination)."}],"seeAlsoSections":[{"title":"Querying map features","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/queryRenderedFeatures(with:options:completion:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/getGeoJsonClusterChildren(forSourceId:feature:completion:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/getGeoJsonClusterExpansionZoom(forSourceId:feature:completion:)"],"generated":true,"anchor":"Querying-map-features"}],"metadata":{"externalID":"s:10MapboxMaps0A3MapC23getGeoJsonClusterLeaves11forSourceId7feature5limit6offset10completionSo13MBXCancelable_pSS_4Turf7FeatureVs6UInt64VAOys6ResultOySo24MBMFeatureExtensionValueCs5Error_pGctF","extendedModule":"MapboxMaps","symbolKind":"method","roleHeading":"Instance Method","role":"symbol","title":"getGeoJsonClusterLeaves(forSourceId:feature:limit:offset:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getGeoJsonClusterLeaves","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forSourceId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"feature","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Feature","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps7Featurea"},{"kind":"text","text":", "},{"text":"limit","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt64","preciseIdentifier":"s:s6UInt64V"},{"kind":"text","text":", "},{"text":"offset","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V","text":"UInt64"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"preciseIdentifier":"s:s6ResultO","text":"Result","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)MBMFeatureExtensionValue","text":"FeatureExtensionValue","kind":"typeIdentifier"},{"kind":"text","text":", any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":">) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":") -> any ","kind":"text"},{"text":"Cancelable","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MBXCancelable"}],"modules":[{"name":"MapboxMaps"}]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/queryRenderedFeatures(with:options:completion:)":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/queryRenderedFeatures(with:options:completion:)","url":"\/documentation\/mapboxmaps\/mapboxmap\/queryrenderedfeatures(with:options:completion:)","kind":"symbol","role":"symbol","title":"queryRenderedFeatures(with:options:completion:)","abstract":[{"type":"text","text":"Queries the map for rendered features."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"queryRenderedFeatures","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"kind":"text","text":": some "},{"kind":"typeIdentifier","text":"RenderedQueryGeometryConvertible","preciseIdentifier":"s:10MapboxMaps32RenderedQueryGeometryConvertibleP"},{"kind":"text","text":", "},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMRenderedQueryOptions","kind":"typeIdentifier","text":"RenderedQueryOptions"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:s6ResultO","text":"Result","kind":"typeIdentifier"},{"text":"<[","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMQueriedRenderedFeature","text":"QueriedRenderedFeature"},{"text":"], any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":">) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":") -> any "},{"preciseIdentifier":"c:objc(pl)MBXCancelable","text":"Cancelable","kind":"typeIdentifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","kind":"symbol","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/getGeoJsonClusterLeaves(forSourceId:feature:limit:offset:completion:)":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/getGeoJsonClusterLeaves(forSourceId:feature:limit:offset:completion:)","url":"\/documentation\/mapboxmaps\/mapboxmap\/getgeojsonclusterleaves(forsourceid:feature:limit:offset:completion:)","kind":"symbol","role":"symbol","title":"getGeoJsonClusterLeaves(forSourceId:feature:limit:offset:completion:)","abstract":[{"text":"Returns all the leaves (original points) of a cluster (given its cluster_id) from a GeoJSON source, with pagination support: limit is the number of leaves","type":"text"},{"text":" ","type":"text"},{"text":"to return (set to Infinity for all points), and offset is the amount of points to skip (for pagination).","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getGeoJsonClusterLeaves"},{"kind":"text","text":"("},{"text":"forSourceId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"feature"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps7Featurea","text":"Feature"},{"text":", ","kind":"text"},{"text":"limit","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UInt64","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V"},{"kind":"text","text":", "},{"text":"offset","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt64","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"Result","preciseIdentifier":"s:s6ResultO","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"FeatureExtensionValue","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMFeatureExtensionValue"},{"kind":"text","text":", any "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":") -> any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MBXCancelable","text":"Cancelable"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Cancelable":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Cancelable"}],"abstract":[{"text":"Allows to cancel the associated asynchronous operation","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/mapboxcommon\/cancelable","navigatorTitle":[{"text":"Cancelable","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Cancelable","title":"Cancelable","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FeatureExtensionValue":{"role":"symbol","title":"FeatureExtensionValue","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FeatureExtensionValue","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeatureExtensionValue","kind":"symbol","type":"topic","navigatorTitle":[{"text":"FeatureExtensionValue","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/featureextensionvalue","abstract":[{"text":"A value or a collection of a feature extension.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/getGeoJsonClusterExpansionZoom(forSourceId:feature:completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getGeoJsonClusterExpansionZoom","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forSourceId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"feature"},{"text":": ","kind":"text"},{"text":"Feature","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps7Featurea"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"preciseIdentifier":"s:s6ResultO","kind":"typeIdentifier","text":"Result"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMFeatureExtensionValue","kind":"typeIdentifier","text":"FeatureExtensionValue"},{"kind":"text","text":", any "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":") -> any ","kind":"text"},{"text":"Cancelable","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MBXCancelable"}],"abstract":[{"text":"Returns the zoom on which the cluster expands into several children (useful for “click to zoom” feature)","type":"text"},{"text":" ","type":"text"},{"text":"given the cluster’s cluster_id (cluster_id value from feature properties) from a GeoJSON source.","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/getgeojsonclusterexpansionzoom(forsourceid:feature:completion:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/getGeoJsonClusterExpansionZoom(forSourceId:feature:completion:)","title":"getGeoJsonClusterExpansionZoom(forSourceId:feature:completion:)","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap":{"type":"topic","title":"MapboxMap","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapboxMap"}],"navigatorTitle":[{"kind":"identifier","text":"MapboxMap"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","url":"\/documentation\/mapboxmaps\/mapboxmap","kind":"symbol","abstract":[{"type":"text","text":"Provides access to the map model, including the camera, style, observable map events,"},{"text":" ","type":"text"},{"text":"and querying rendered features.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"kind":"article","type":"topic","title":"MapboxMap","abstract":[],"url":"\/documentation\/mapboxmaps\/mapboxmap-apis","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Feature":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Feature","url":"\/documentation\/mapboxmaps\/feature","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"Feature","kind":"identifier"}],"title":"Feature","abstract":[{"text":"An object representing a spatially bounded geometry.","type":"text"}],"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Feature"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","url":"\/documentation\/overview","kind":"article","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/MapFeatureQueryable-Implementations":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/MapFeatureQueryable-Implementations","url":"\/documentation\/mapboxmaps\/mapboxmap\/mapfeaturequeryable-implementations","kind":"article","role":"collectionGroup","title":"MapFeatureQueryable Implementations","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/getGeoJsonClusterChildren(forSourceId:feature:completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getGeoJsonClusterChildren","kind":"identifier"},{"kind":"text","text":"("},{"text":"forSourceId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"feature","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10MapboxMaps7Featurea","text":"Feature","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"preciseIdentifier":"s:s6ResultO","kind":"typeIdentifier","text":"Result"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"FeatureExtensionValue","preciseIdentifier":"c:objc(cs)MBMFeatureExtensionValue"},{"text":", any ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":">) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":") -> any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MBXCancelable","text":"Cancelable"}],"abstract":[{"text":"Returns the children (original points or clusters) of a cluster (on the next zoom level)","type":"text"},{"text":" ","type":"text"},{"text":"given its id (cluster_id value from feature properties) from a GeoJSON source.","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/getgeojsonclusterchildren(forsourceid:feature:completion:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/getGeoJsonClusterChildren(forSourceId:feature:completion:)","title":"getGeoJsonClusterChildren(forSourceId:feature:completion:)","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/title","value":"MBXCancelable","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/fragments","value":[{"text":"MBXCancelable","kind":"identifier"}],"op":"replace"},{"value":[{"text":"MBXCancelable","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeatureExtensionValue\/title","value":"MBMFeatureExtensionValue","op":"replace"},{"value":[{"kind":"identifier","text":"MBMFeatureExtensionValue"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeatureExtensionValue\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeatureExtensionValue\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMFeatureExtensionValue"}]}]}]}