{"sections":[],"metadata":{"externalID":"c:objc(cs)MBMFeaturesetDescriptor(im)isEqualToFeaturesetDescriptor:","role":"symbol","symbolKind":"method","title":"isEqual(to:)","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"isEqualToFeaturesetDescriptor:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"kind":"text","text":"("},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"FeaturesetDescriptor","preciseIdentifier":"c:objc(cs)MBMFeaturesetDescriptor"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"modules":[{"name":"MapboxMaps"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"other"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeaturesetDescriptor-swift.class","text":"FeaturesetDescriptor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMFeaturesetDescriptor"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/mapboxmaps\/featuresetdescriptor-swift.class\/isequal(to:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/featuresetdescriptor-swift.class\/isequal(to:)"]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeaturesetDescriptor-swift.class"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeaturesetDescriptor-swift.class\/isEqual(to:)"},"kind":"symbol","references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"role":"collection","type":"topic","title":"MapboxMaps Documentation","url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","role":"collection","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","kind":"symbol","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"abstract":[],"kind":"article","type":"topic","title":"MapboxMap","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/mapboxmap-apis","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FeaturesetDescriptor-swift.class":{"type":"topic","title":"FeaturesetDescriptor","url":"\/documentation\/mapboxmaps\/featuresetdescriptor-swift.class","abstract":[{"text":"Represents an identifier for a single exported featureset or a layer.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeaturesetDescriptor-swift.class","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FeaturesetDescriptor","kind":"identifier"}],"navigatorTitle":[{"text":"FeaturesetDescriptor","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FeaturesetDescriptor-swift.class/isEqual(to:)":{"type":"topic","title":"isEqual(to:)","url":"\/documentation\/mapboxmaps\/featuresetdescriptor-swift.class\/isequal(to:)","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeaturesetDescriptor-swift.class\/isEqual(to:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"kind":"text","text":"("},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMFeaturesetDescriptor","text":"FeaturesetDescriptor"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"isEqualToFeaturesetDescriptor:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"isEqualToFeaturesetDescriptor:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"isEqualToFeaturesetDescriptor:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"text":"isEqualToFeaturesetDescriptor:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeaturesetDescriptor-swift.class","text":"MBMFeaturesetDescriptor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMFeaturesetDescriptor"},{"kind":"text","text":" *) "},{"text":"other","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeaturesetDescriptor-swift.class\/title","value":"MBMFeaturesetDescriptor"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeaturesetDescriptor-swift.class\/fragments","op":"replace","value":[{"text":"MBMFeaturesetDescriptor","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeaturesetDescriptor-swift.class\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMFeaturesetDescriptor"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeaturesetDescriptor-swift.class~1isEqual(to:)\/title","value":"isEqualToFeaturesetDescriptor:","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeaturesetDescriptor-swift.class~1isEqual(to:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"isEqualToFeaturesetDescriptor:","kind":"identifier"}],"op":"replace"}]}]}