{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionGeometryDefinition"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"MBXGeometry","preciseIdentifier":"c:objc(cs)MBXGeometry","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry"},{"text":" * ","kind":"text"},{"text":"geometry","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMOfflineRegionGeometryDefinition\/geometry-bg48","interfaceLanguage":"occ"},"variants":[{"paths":["\/documentation\/mapboxmaps\/mbmofflineregiongeometrydefinition\/geometry-bg48"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"text":"The geometry that defines the boundary of the offline region","type":"text"}],"metadata":{"title":"geometry","externalID":"c:objc(cs)MBMOfflineRegionGeometryDefinition(py)geometry","navigatorTitle":[{"kind":"identifier","text":"geometry"}],"role":"symbol","symbolKind":"property","roleHeading":"Instance Property","fragments":[{"kind":"identifier","text":"geometry"}],"modules":[{"name":"MapboxMaps"}]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMaps":{"title":"Core Maps API","url":"\/documentation\/mapboxmaps\/coremaps","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","type":"topic","abstract":[{"type":"text","text":"Maps rendering SDK also known as GL-Native"}],"role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMOfflineRegionGeometryDefinition/geometry-bg48":{"title":"geometry","type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/mbmofflineregiongeometrydefinition\/geometry-bg48","abstract":[{"text":"The geometry that defines the boundary of the offline region","type":"text"}],"role":"symbol","fragments":[{"kind":"identifier","text":"geometry"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMOfflineRegionGeometryDefinition\/geometry-bg48"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionGeometryDefinition":{"title":"OfflineRegionGeometryDefinition","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OfflineRegionGeometryDefinition"}],"deprecated":true,"url":"\/documentation\/mapboxmaps\/offlineregiongeometrydefinition","abstract":[{"type":"text","text":"An offline region definition is a geographic region defined by a style URL,"},{"text":" ","type":"text"},{"type":"text","text":"a geometry, zoom range, and device pixel ratio. Both "},{"type":"codeVoice","code":"minZoom"},{"type":"text","text":" and "},{"type":"codeVoice","code":"maxZoom"},{"type":"text","text":" must be ≥ 0,"},{"type":"text","text":" "},{"type":"text","text":"and "},{"code":"maxZoom","type":"codeVoice"},{"type":"text","text":" must be ≥ "},{"code":"minZoom","type":"codeVoice"},{"text":". The ","type":"text"},{"type":"codeVoice","code":"maxZoom"},{"text":" may be ∞, in which case for each tile source,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"the region will include tiles from "},{"code":"minZoom","type":"codeVoice"},{"type":"text","text":" up to the maximum zoom level provided by that source."},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"code":"pixelRatio","type":"codeVoice"},{"text":" must be ≥ 0 and should typically be 1.0 or 2.0.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OfflineRegionGeometryDefinition","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionGeometryDefinition"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Geometry":{"title":"Geometry","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Geometry"}],"url":"\/documentation\/mapboxcommon\/geometry","abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Geometry"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Offline":{"title":"Offline Support","url":"\/documentation\/mapboxmaps\/offline","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","abstract":[],"type":"topic","role":"collectionGroup"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MBMOfflineRegionGeometryDefinition","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionGeometryDefinition\/title"},{"op":"replace","value":[{"text":"MBMOfflineRegionGeometryDefinition","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionGeometryDefinition\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry\/title","op":"replace","value":"MBXGeometry"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry\/fragments","value":[{"text":"MBXGeometry","kind":"identifier"}]}]}]}