{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getGeometryDefinition","kind":"identifier"},{"kind":"text","text":"() -> "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionGeometryDefinition","kind":"typeIdentifier","text":"OfflineRegionGeometryDefinition","preciseIdentifier":"c:objc(cs)MBMOfflineRegionGeometryDefinition"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"inlineContent":[{"text":"A definition describing the geometry including attributes, otherwise empty.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegion\/getGeometryDefinition()","interfaceLanguage":"swift"},"metadata":{"platforms":[],"role":"symbol","modules":[{"name":"MapboxMaps"}],"externalID":"c:objc(cs)MBMOfflineRegion(im)getGeometryDefinition","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getGeometryDefinition","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"OfflineRegionGeometryDefinition","preciseIdentifier":"c:objc(cs)MBMOfflineRegionGeometryDefinition","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"getGeometryDefinition()","roleHeading":"Instance Method","navigatorTitle":[{"text":"getGeometryDefinition","kind":"identifier"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegion"]]},"abstract":[{"type":"text","text":"The geometry defining the region. Geometry and tile pyramid definitions are"},{"text":" ","type":"text"},{"type":"text","text":"mutually exclusive."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/offlineregion\/getgeometrydefinition()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/offlineregion\/getgeometrydefinition()"]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","abstract":[],"kind":"article","url":"\/documentation\/overview","type":"topic","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMaps":{"title":"Core Maps API","abstract":[{"text":"Maps rendering SDK also known as GL-Native","type":"text"}],"kind":"article","type":"topic","url":"\/documentation\/mapboxmaps\/coremaps","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegion":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegion","abstract":[{"type":"text","text":"An offline region represents an identifiable geographic region with optional metadata."}],"title":"OfflineRegion","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"OfflineRegion","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/offlineregion","navigatorTitle":[{"kind":"identifier","text":"OfflineRegion"}],"deprecated":true},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","url":"\/documentation\/mapboxmaps","role":"collection","title":"MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionGeometryDefinition":{"navigatorTitle":[{"kind":"identifier","text":"OfflineRegionGeometryDefinition"}],"type":"topic","url":"\/documentation\/mapboxmaps\/offlineregiongeometrydefinition","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"OfflineRegionGeometryDefinition","kind":"identifier"}],"title":"OfflineRegionGeometryDefinition","kind":"symbol","deprecated":true,"abstract":[{"text":"An offline region definition is a geographic region defined by a style URL,","type":"text"},{"type":"text","text":" "},{"text":"a geometry, zoom range, and device pixel ratio. Both ","type":"text"},{"type":"codeVoice","code":"minZoom"},{"type":"text","text":" and "},{"code":"maxZoom","type":"codeVoice"},{"type":"text","text":" must be ≥ 0,"},{"text":" ","type":"text"},{"text":"and ","type":"text"},{"type":"codeVoice","code":"maxZoom"},{"type":"text","text":" must be ≥ "},{"code":"minZoom","type":"codeVoice"},{"type":"text","text":". The "},{"code":"maxZoom","type":"codeVoice"},{"text":" may be ∞, in which case for each tile source,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"the region will include tiles from "},{"code":"minZoom","type":"codeVoice"},{"type":"text","text":" up to the maximum zoom level provided by that source."},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"code":"pixelRatio","type":"codeVoice"},{"text":" must be ≥ 0 and should typically be 1.0 or 2.0.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionGeometryDefinition"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Offline":{"url":"\/documentation\/mapboxmaps\/offline","kind":"article","role":"collectionGroup","title":"Offline Support","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","abstract":[],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegion/getGeometryDefinition()":{"kind":"symbol","deprecated":true,"role":"symbol","title":"getGeometryDefinition()","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegion\/getGeometryDefinition()","url":"\/documentation\/mapboxmaps\/offlineregion\/getgeometrydefinition()","abstract":[{"text":"The geometry defining the region. Geometry and tile pyramid definitions are","type":"text"},{"text":" ","type":"text"},{"text":"mutually exclusive.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"getGeometryDefinition","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"OfflineRegionGeometryDefinition","preciseIdentifier":"c:objc(cs)MBMOfflineRegionGeometryDefinition","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"getGeometryDefinition","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"getGeometryDefinition","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getGeometryDefinition"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"MBMOfflineRegionGeometryDefinition","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionGeometryDefinition","preciseIdentifier":"c:objc(cs)MBMOfflineRegionGeometryDefinition"},{"text":" *) ","kind":"text"},{"text":"getGeometryDefinition","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"inlineContent":[{"type":"text","text":"A definition describing the geometry including attributes, otherwise empty."}],"type":"paragraph"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegion\/title","value":"MBMOfflineRegion","op":"replace"},{"value":[{"text":"MBMOfflineRegion","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegion\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegion\/navigatorTitle","value":[{"text":"MBMOfflineRegion","kind":"identifier"}]},{"value":"MBMOfflineRegionGeometryDefinition","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionGeometryDefinition\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionGeometryDefinition\/fragments","value":[{"kind":"identifier","text":"MBMOfflineRegionGeometryDefinition"}]},{"value":[{"text":"MBMOfflineRegionGeometryDefinition","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionGeometryDefinition\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegion~1getGeometryDefinition()\/title","op":"replace","value":"getGeometryDefinition"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getGeometryDefinition"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegion~1getGeometryDefinition()\/fragments"}]}]}