{"metadata":{"role":"symbol","title":"init(first:second:)","modules":[{"name":"MapboxMaps"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"first"},{"text":": ","kind":"text"},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"second"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithFirst:second:"}],"roleHeading":"Initializer","externalID":"c:objc(cs)MBMImageStretches(im)initWithFirst:second:","symbolKind":"init"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"first","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"kind":"text","text":", "},{"kind":"externalParam","text":"second"},{"text":": ","kind":"text"},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer-Property-Values","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageStretches"]]},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageStretches\/init(first:second:)","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/imagestretches\/init(first:second:)"]},{"paths":["\/documentation\/mapboxmaps\/imagestretches\/init(first:second:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ImageStretches/init(first:second:)":{"type":"topic","url":"\/documentation\/mapboxmaps\/imagestretches\/init(first:second:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"first"},{"kind":"text","text":": "},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"second"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"initWithFirst:second:","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageStretches\/init(first:second:)","title":"init(first:second:)","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","abstract":[],"kind":"article","role":"collection","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ImageStretches":{"abstract":[{"text":"Describes the image stretch areas.","type":"text"}],"title":"ImageStretches","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageStretches","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ImageStretches"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageStretches","url":"\/documentation\/mapboxmaps\/imagestretches"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layer-Property-Values":{"abstract":[],"role":"collectionGroup","url":"\/documentation\/mapboxmaps\/layer-property-values","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer-Property-Values","title":"Layer Property Values","type":"topic","kind":"article"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"initWithFirst:second:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"initWithFirst:second:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithFirst:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:f","text":"float"},{"text":") ","kind":"text"},{"text":"first","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"second:"},{"text":"(","kind":"text"},{"text":"float","preciseIdentifier":"c:f","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"second"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ImageStretches~1init(first:second:)\/title","op":"replace","value":"initWithFirst:second:"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ImageStretches~1init(first:second:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFirst:second:"}]},{"value":"MBMImageStretches","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ImageStretches\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ImageStretches\/fragments","op":"replace","value":[{"text":"MBMImageStretches","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ImageStretches\/navigatorTitle","value":[{"text":"MBMImageStretches","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}