{"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpMethod\/head"},"metadata":{"role":"symbol","title":"HttpMethod.head","symbolKind":"case","modules":[{"name":"MapboxCommon"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"head","kind":"identifier"}],"navigatorTitle":[{"text":"MBXHttpMethodHead","kind":"identifier"}],"roleHeading":"Case","externalID":"c:@E@MBXHttpMethod@MBXHttpMethodHead"},"abstract":[{"type":"text","text":"The HEAD method asks for a response identical to that of a GET request, but without the response body."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"head","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpMethod"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/httpmethod\/head"]},{"paths":["\/documentation\/mapboxcommon\/httpmethod\/head"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"url":"\/documentation\/mapboxcommon","title":"MapboxCommon","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","abstract":[],"url":"\/documentation\/overview","role":"collection","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpMethod":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpMethod","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HttpMethod","kind":"identifier"}],"title":"HttpMethod","abstract":[{"text":"HTTP defines a set of request methods to indicate the desired action to be performed for a given resource.","type":"text"}],"url":"\/documentation\/mapboxcommon\/httpmethod","navigatorTitle":[{"text":"HttpMethod","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpMethod/head":{"abstract":[{"text":"The HEAD method asks for a response identical to that of a GET request, but without the response body.","type":"text"}],"title":"HttpMethod.head","url":"\/documentation\/mapboxcommon\/httpmethod\/head","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpMethod\/head","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"head","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"MBXHttpMethodHead","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"MBXHttpMethodHead","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"MBXHttpMethodHead","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"MBXHttpMethodHead","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"MBXHttpMethod","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpMethod\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpMethod\/fragments","value":[{"kind":"identifier","text":"MBXHttpMethod"}]},{"op":"replace","value":[{"text":"MBXHttpMethod","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpMethod\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpMethod~1head\/title","op":"replace","value":"MBXHttpMethodHead"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpMethod~1head\/fragments","value":[{"kind":"identifier","text":"MBXHttpMethodHead"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}