{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"readOnly","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The implementation first checks tile store when requesting a tile."},{"type":"text","text":" "},{"type":"text","text":"If a tile pack is already loaded, the tile will be extracted and returned. Otherwise, the implementation"},{"type":"text","text":" "},{"type":"text","text":"falls back to requesting the individual tile and storing it in the disk cache."}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreUsageMode\/readOnly"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreUsageMode"]]},"abstract":[{"text":"Tile store enabled for accessing loaded tile packs.","type":"text"}],"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"readOnly"}],"roleHeading":"Case","role":"symbol","symbolKind":"case","modules":[{"name":"MapboxMaps"}],"navigatorTitle":[{"kind":"identifier","text":"MBMTileStoreUsageModeReadOnly"}],"title":"TileStoreUsageMode.readOnly","externalID":"c:@E@MBMTileStoreUsageMode@MBMTileStoreUsageModeReadOnly"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/tilestoreusagemode\/readonly"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/tilestoreusagemode\/readonly"]}],"kind":"symbol","sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStoreUsageMode/readOnly":{"abstract":[{"text":"Tile store enabled for accessing loaded tile packs.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreUsageMode\/readOnly","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"readOnly","kind":"identifier"}],"navigatorTitle":[{"text":"MBMTileStoreUsageModeReadOnly","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/tilestoreusagemode\/readonly","kind":"symbol","type":"topic","title":"TileStoreUsageMode.readOnly"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","url":"\/documentation\/overview","kind":"article","abstract":[],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"abstract":[],"title":"TileStore APIs","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/tilestore-apis","kind":"article","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","url":"\/documentation\/mapboxmaps","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","role":"collection","title":"MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStoreUsageMode":{"type":"topic","title":"TileStoreUsageMode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileStoreUsageMode","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreUsageMode","navigatorTitle":[{"text":"TileStoreUsageMode","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Describes tile store usage modes."}],"url":"\/documentation\/mapboxmaps\/tilestoreusagemode"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MBMTileStoreUsageModeReadOnly"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MBMTileStoreUsageModeReadOnly"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"MBMTileStoreUsageModeReadOnly","kind":"identifier"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileStoreUsageMode~1readOnly\/title","value":"MBMTileStoreUsageModeReadOnly"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileStoreUsageMode~1readOnly\/fragments","value":[{"kind":"identifier","text":"MBMTileStoreUsageModeReadOnly"}]},{"value":"MBMTileStoreUsageMode","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileStoreUsageMode\/title","op":"replace"},{"value":[{"text":"MBMTileStoreUsageMode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileStoreUsageMode\/fragments","op":"replace"},{"value":[{"text":"MBMTileStoreUsageMode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileStoreUsageMode\/navigatorTitle","op":"replace"}]}]}