{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":" * "},{"text":"glyphsRasterizationMode","kind":"identifier"},{"kind":"text","text":";"}]}]},{"kind":"content","content":[{"text":"Discussion","level":2,"anchor":"discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"If provided, updates the style package’s glyphs rasterization mode,"},{"text":" ","type":"text"},{"type":"text","text":"which defines which glyphs will be loaded from the server."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"By default, ideographs are rasterized locally and other glyphs are loaded"},{"type":"text","text":" "},{"text":"from network (i.e. ","type":"text"},{"type":"codeVoice","code":"IdeographsRasterizedLocally"},{"type":"text","text":" value is used)."}]}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadOptions"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/mapboxmaps\/mbmstylepackloadoptions\/glyphsrasterizationmode"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Specifies glyphs rasterization mode.","type":"text"}],"kind":"symbol","sections":[],"metadata":{"modules":[{"name":"MapboxMaps"}],"symbolKind":"property","roleHeading":"Instance Property","role":"symbol","externalID":"c:objc(cs)MBMStylePackLoadOptions(py)glyphsRasterizationMode","fragments":[{"kind":"identifier","text":"glyphsRasterizationMode"}],"title":"glyphsRasterizationMode","navigatorTitle":[{"kind":"identifier","text":"glyphsRasterizationMode"}]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStylePackLoadOptions\/glyphsRasterizationMode"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMStylePackLoadOptions/glyphsRasterizationMode":{"fragments":[{"kind":"identifier","text":"glyphsRasterizationMode"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/mbmstylepackloadoptions\/glyphsrasterizationmode","abstract":[{"type":"text","text":"Specifies glyphs rasterization mode."}],"type":"topic","kind":"symbol","title":"glyphsRasterizationMode","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStylePackLoadOptions\/glyphsRasterizationMode"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/mapboxmaps","title":"MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/tilestore-apis","abstract":[],"kind":"article","title":"TileStore APIs","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","abstract":[],"kind":"article","role":"collection","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePackLoadOptions":{"abstract":[{"text":"Describes the style package load option values.","type":"text"}],"type":"topic","title":"StylePackLoadOptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadOptions","navigatorTitle":[{"text":"StylePackLoadOptions","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StylePackLoadOptions"}],"url":"\/documentation\/mapboxmaps\/stylepackloadoptions","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"MBMStylePackLoadOptions","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadOptions\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBMStylePackLoadOptions"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadOptions\/fragments"},{"value":[{"text":"MBMStylePackLoadOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadOptions\/navigatorTitle"}]}]}