{"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStylePackLoadOptions\/initWithGlyphsRasterizationMode:metadata:acceptExpired:extraOptions:","interfaceLanguage":"occ"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/mbmstylepackloadoptions\/initwithglyphsrasterizationmode:metadata:acceptexpired:extraoptions:"]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadOptions"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithGlyphsRasterizationMode:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":" *) "},{"text":"glyphsRasterizationMode","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"metadata:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"text":") ","kind":"text"},{"text":"metadata","kind":"internalParam"},{"kind":"text","text":" "},{"text":"acceptExpired:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":") ","kind":"text"},{"text":"acceptExpired","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"extraOptions:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"extraOptions"},{"text":";","kind":"text"}]}]}],"metadata":{"navigatorTitle":[{"text":"initWithGlyphsRasterizationMode:metadata:acceptExpired:extraOptions:","kind":"identifier"}],"externalID":"c:objc(cs)MBMStylePackLoadOptions(im)initWithGlyphsRasterizationMode:metadata:acceptExpired:extraOptions:","roleHeading":"Instance Method","symbolKind":"method","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithGlyphsRasterizationMode:metadata:acceptExpired:extraOptions:"}],"title":"initWithGlyphsRasterizationMode:metadata:acceptExpired:extraOptions:","modules":[{"name":"MapboxMaps"}]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","role":"collection","url":"\/documentation\/mapboxmaps","kind":"symbol","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","kind":"article","url":"\/documentation\/mapboxmaps\/tilestore-apis","title":"TileStore APIs","role":"collectionGroup","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMStylePackLoadOptions/initWithGlyphsRasterizationMode:metadata:acceptExpired:extraOptions:":{"title":"initWithGlyphsRasterizationMode:metadata:acceptExpired:extraOptions:","url":"\/documentation\/mapboxmaps\/mbmstylepackloadoptions\/initwithglyphsrasterizationmode:metadata:acceptexpired:extraoptions:","type":"topic","role":"symbol","navigatorTitle":[{"text":"initWithGlyphsRasterizationMode:metadata:acceptExpired:extraOptions:","kind":"identifier"}],"abstract":[],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithGlyphsRasterizationMode:metadata:acceptExpired:extraOptions:"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStylePackLoadOptions\/initWithGlyphsRasterizationMode:metadata:acceptExpired:extraOptions:"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePackLoadOptions":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadOptions","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StylePackLoadOptions"}],"url":"\/documentation\/mapboxmaps\/stylepackloadoptions","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StylePackLoadOptions"}],"abstract":[{"type":"text","text":"Describes the style package load option values."}],"kind":"symbol","title":"StylePackLoadOptions"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","title":"MapboxMaps Documentation","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadOptions\/title","value":"MBMStylePackLoadOptions"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadOptions\/fragments","value":[{"text":"MBMStylePackLoadOptions","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadOptions\/navigatorTitle","value":[{"kind":"identifier","text":"MBMStylePackLoadOptions"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}