{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResponseSourceType"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"title":"Operators","anchor":"Operators","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResponseSourceType\/!=(_:_:)"]}],"kind":"article","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResponseSourceType\/Equatable-Implementations"},"metadata":{"modules":[{"name":"MapboxMaps"}],"roleHeading":"API Collection","title":"Equatable Implementations","role":"collectionGroup"},"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","kind":"symbol","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"type":"topic","abstract":[{"type":"text","text":"The simplified diagram of the events emitted by the map is displayed below."}],"kind":"article","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/events","title":"Map events","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","role":"collection","title":"MapboxMaps Documentation","abstract":[],"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResponseSourceType/!=(_:_:)":{"kind":"symbol","type":"topic","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"title":"!=(_:_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResponseSourceType\/!=(_:_:)","url":"\/documentation\/mapboxmaps\/responsesourcetype\/!=(_:_:)","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResponseSourceType":{"navigatorTitle":[{"kind":"identifier","text":"ResponseSourceType"}],"title":"ResponseSourceType","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResponseSourceType","type":"topic","url":"\/documentation\/mapboxmaps\/responsesourcetype","role":"symbol","abstract":[{"type":"text","text":"The enumeration defines the source type that provides the requested resource."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResponseSourceType"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MBMResponseSourceType","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResponseSourceType\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResponseSourceType\/fragments","value":[{"kind":"identifier","text":"MBMResponseSourceType"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResponseSourceType\/navigatorTitle","value":[{"kind":"identifier","text":"MBMResponseSourceType"}]}]}]}