{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpMethod","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpMethod\/RawRepresentable-Implementations"]]},"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"modules":[{"name":"MapboxCommon","relatedModules":["Swift"]}],"title":"hashValue","symbolKind":"property","role":"symbol","extendedModule":"Swift","externalID":"s:SYsSHRzSH8RawValueSYRpzrlE04hashB0Sivp::SYNTHESIZED::c:@E@MBXHttpMethod","roleHeading":"Instance Property","conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"availabilityPrefix":[{"text":"Available when","type":"text"}],"constraints":[{"type":"codeVoice","code":"Self"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}]}},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}]}]}],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"RawRepresentable.hashValue","type":"codeVoice"},{"type":"text","text":"."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpMethod\/hashValue"},"variants":[{"paths":["\/documentation\/mapboxcommon\/httpmethod\/hashvalue"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpMethod":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HttpMethod","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpMethod","navigatorTitle":[{"kind":"identifier","text":"HttpMethod"}],"url":"\/documentation\/mapboxcommon\/httpmethod","kind":"symbol","abstract":[{"text":"HTTP defines a set of request methods to indicate the desired action to be performed for a given resource.","type":"text"}],"role":"symbol","type":"topic","title":"HttpMethod"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpMethod/RawRepresentable-Implementations":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpMethod\/RawRepresentable-Implementations","url":"\/documentation\/mapboxcommon\/httpmethod\/rawrepresentable-implementations","kind":"article","abstract":[],"role":"collectionGroup","type":"topic","title":"RawRepresentable Implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpMethod/hashValue":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpMethod\/hashValue","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"hashValue","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"title":"hashValue","role":"symbol","url":"\/documentation\/mapboxcommon\/httpmethod\/hashvalue","conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}]}},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","title":"MapboxCommon","url":"\/documentation\/mapboxcommon","role":"collection","kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","kind":"article","abstract":[],"title":"MapboxMaps Documentation"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpMethod\/title","value":"MBXHttpMethod"},{"value":[{"text":"MBXHttpMethod","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpMethod\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpMethod\/navigatorTitle","value":[{"text":"MBXHttpMethod","kind":"identifier"}],"op":"replace"}]}]}