{"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapSnapshotOptions"]]},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapSnapshotOptions\/glyphsRasterizationOptions","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"glyphsRasterizationOptions","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MBMGlyphsRasterizationOptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationOptions","text":"GlyphsRasterizationOptions","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"Glyphs rasterization options to use for client-side text rendering."},{"text":" ","type":"text"},{"type":"text","text":"By default, "},{"type":"codeVoice","code":"GlyphsRasterizationOptions"},{"text":" will use ","type":"text"},{"type":"codeVoice","code":".ideographsRasterizedLocally"}],"metadata":{"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"glyphsRasterizationOptions","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMGlyphsRasterizationOptions","text":"GlyphsRasterizationOptions"}],"roleHeading":"Instance Property","title":"glyphsRasterizationOptions","externalID":"s:10MapboxMaps18MapSnapshotOptionsV019glyphsRasterizationE0So09MBMGlyphsgE0Cvp","modules":[{"name":"MapboxMaps"}],"role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/mapsnapshotoptions\/glyphsrasterizationoptions"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"title":"MapboxMaps","kind":"symbol","role":"collection","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GlyphsRasterizationOptions":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationOptions","title":"GlyphsRasterizationOptions","kind":"symbol","navigatorTitle":[{"text":"GlyphsRasterizationOptions","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GlyphsRasterizationOptions","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxmaps\/glyphsrasterizationoptions","abstract":[{"type":"text","text":"Describes the glyphs rasterization option values."}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapSnapshotOptions/glyphsRasterizationOptions":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"glyphsRasterizationOptions"},{"text":": ","kind":"text"},{"text":"GlyphsRasterizationOptions","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMGlyphsRasterizationOptions"}],"type":"topic","abstract":[{"text":"Glyphs rasterization options to use for client-side text rendering.","type":"text"},{"type":"text","text":" "},{"text":"By default, ","type":"text"},{"code":"GlyphsRasterizationOptions","type":"codeVoice"},{"type":"text","text":" will use "},{"type":"codeVoice","code":".ideographsRasterizedLocally"}],"title":"glyphsRasterizationOptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapSnapshotOptions\/glyphsRasterizationOptions","url":"\/documentation\/mapboxmaps\/mapsnapshotoptions\/glyphsrasterizationoptions","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapSnapshotOptions":{"navigatorTitle":[{"text":"MapSnapshotOptions","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"MapSnapshotOptions","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapSnapshotOptions","abstract":[{"text":"Set of options for taking map snapshot with Snapshotter.","type":"text"}],"title":"MapSnapshotOptions","url":"\/documentation\/mapboxmaps\/mapsnapshotoptions","kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","role":"collection","url":"\/documentation\/overview","kind":"article","abstract":[],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Snapshotter-APIs":{"abstract":[],"kind":"article","role":"collectionGroup","title":"Snapshotter","url":"\/documentation\/mapboxmaps\/snapshotter-apis","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter-APIs","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationOptions\/title","value":"MBMGlyphsRasterizationOptions"},{"value":[{"text":"MBMGlyphsRasterizationOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationOptions\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationOptions\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMGlyphsRasterizationOptions"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}