{"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions"]]},"abstract":[{"type":"text","text":"Each drawing operation is replaced by a translucent fill. Overlapping"},{"type":"text","text":" "},{"text":"drawing operations appear more prominent to help diagnose overdrawing.","type":"text"}],"metadata":{"role":"symbol","modules":[{"name":"MapboxMaps"}],"externalID":"c:@E@MBMMapDebugOptions@MBMMapDebugOptionsOverdraw","navigatorTitle":[{"kind":"identifier","text":"MBMMapDebugOptionsOverdraw"}],"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"overdraw","kind":"identifier"}],"roleHeading":"Case","title":"MapDebugOptions.overdraw"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"overdraw"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/mapdebugoptions\/overdraw"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/mapdebugoptions\/overdraw"]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/overdraw","interfaceLanguage":"swift"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapDebugOptions":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions","kind":"symbol","abstract":[{"text":"Options for enabling debugging features in a map.","type":"text"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/mapdebugoptions","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapDebugOptions"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"MapDebugOptions"}],"title":"MapDebugOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Performance":{"role":"collectionGroup","kind":"article","type":"topic","title":"Performance and investigations","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","url":"\/documentation\/mapboxmaps\/performance"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapDebugOptions/overdraw":{"abstract":[{"text":"Each drawing operation is replaced by a translucent fill. Overlapping","type":"text"},{"type":"text","text":" "},{"type":"text","text":"drawing operations appear more prominent to help diagnose overdrawing."}],"role":"symbol","navigatorTitle":[{"text":"MBMMapDebugOptionsOverdraw","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"overdraw","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/overdraw","type":"topic","url":"\/documentation\/mapboxmaps\/mapdebugoptions\/overdraw","kind":"symbol","title":"MapDebugOptions.overdraw"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","role":"collection","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","title":"MapboxMaps Documentation","url":"\/documentation\/overview","type":"topic","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"MBMMapDebugOptionsOverdraw","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"MBMMapDebugOptionsOverdraw","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"text":"MBMMapDebugOptionsOverdraw","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions\/title","value":"MBMMapDebugOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions\/fragments","value":[{"kind":"identifier","text":"MBMMapDebugOptions"}]},{"value":[{"kind":"identifier","text":"MBMMapDebugOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions~1overdraw\/title","op":"replace","value":"MBMMapDebugOptionsOverdraw"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions~1overdraw\/fragments","value":[{"kind":"identifier","text":"MBMMapDebugOptionsOverdraw"}]}]}]}