{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/freecameraoptions\/getposition()"]},{"paths":["\/documentation\/mapboxmaps\/freecameraoptions\/getposition()"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"text":"getPosition","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getPosition","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Vec3","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMVec3"},{"text":"?","kind":"text"}],"role":"symbol","modules":[{"name":"MapboxMaps"}],"symbolKind":"method","title":"getPosition()","externalID":"c:objc(cs)MBMFreeCameraOptions(im)getPosition","roleHeading":"Instance Method"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getPosition","kind":"identifier"},{"text":"() -> ","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Vec3","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMVec3","text":"Vec3"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"inlineContent":[{"type":"text","text":"The position if set."}],"type":"paragraph"}]},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","level":2,"type":"heading"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The size of 1 unit is the width of the projected world instead of the “mercator meter”.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Coordinate [0, 0, 0] is the north-west corner and [1, 1, 0] is the south-east corner."}]}]},{"content":[{"inlineContent":[{"text":"Z coordinate is conformal and must respect minimum and maximum zoom values.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Zoom is automatically computed from the altitude (z)","type":"text"}]}]}]}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions"]]},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions\/getPosition()","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"Get the position of the camera in slightly modified web mercator coordinates"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FreeCameraOptions":{"type":"topic","url":"\/documentation\/mapboxmaps\/freecameraoptions","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FreeCameraOptions"}],"title":"FreeCameraOptions","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FreeCameraOptions"}],"abstract":[{"type":"text","text":"Various options for accessing physical properties of the underlying camera entity."},{"type":"text","text":" "},{"type":"text","text":"A direct access to these properties allows more flexible and precise controlling"},{"type":"text","text":" "},{"text":"of the camera while also being fully compatible and interchangeable with CameraOptions.","type":"text"},{"type":"text","text":" "},{"text":"All fields are optional.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","url":"\/documentation\/overview","title":"MapboxMaps Documentation","abstract":[],"kind":"article","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Vec3":{"navigatorTitle":[{"kind":"identifier","text":"Vec3"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Vec3","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"3 component vector."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Vec3"}],"title":"Vec3","role":"symbol","url":"\/documentation\/mapboxmaps\/vec3"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"kind":"article","title":"MapboxMap","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","type":"topic","url":"\/documentation\/mapboxmaps\/mapboxmap-apis"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","title":"MapboxMaps","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FreeCameraOptions/getPosition()":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"getPosition"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:objc(cs)MBMVec3","text":"Vec3","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"getPosition()","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions\/getPosition()","type":"topic","abstract":[{"type":"text","text":"Get the position of the camera in slightly modified web mercator coordinates"}],"kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/freecameraoptions\/getposition()","navigatorTitle":[{"text":"getPosition","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"getPosition","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getPosition"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Vec3","preciseIdentifier":"c:objc(cs)MBMVec3","text":"MBMVec3"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"getPosition"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"content","content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The position if set."}]}]}},{"value":"MBMFreeCameraOptions","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions\/title","op":"replace"},{"value":[{"text":"MBMFreeCameraOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions\/fragments","op":"replace"},{"value":[{"text":"MBMFreeCameraOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Vec3\/title","value":"MBMVec3"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Vec3\/fragments","value":[{"text":"MBMVec3","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"MBMVec3","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Vec3\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions~1getPosition()\/title","value":"getPosition"},{"value":[{"kind":"text","text":"- "},{"text":"getPosition","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions~1getPosition()\/fragments"}]}]}