{"metadata":{"symbolKind":"class","roleHeading":"Class","role":"symbol","externalID":"s:10MapboxMaps13AnyCancelableC","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AnyCancelable","kind":"identifier"}],"title":"AnyCancelable","navigatorTitle":[{"text":"AnyCancelable","kind":"identifier"}],"modules":[{"name":"MapboxMaps"}]},"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AnyCancelable\/init(_:)-13kaj","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AnyCancelable\/init(_:)-24hfp","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AnyCancelable\/init(_:)-5to9x"],"anchor":"Initializers","title":"Initializers"},{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AnyCancelable\/cancel()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AnyCancelable\/store(in:)-3m1sp","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AnyCancelable\/store(in:)-7gtoz","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AnyCancelable\/store(in:)-84gyl","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AnyCancelable\/store(in:)-oh7e"]},{"title":"Default Implementations","anchor":"Default-Implementations","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AnyCancelable\/Equatable-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AnyCancelable\/Hashable-Implementations"],"generated":true}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AnyCancelable"},"sections":[],"relationshipsSections":[{"type":"conformsTo","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Cancelable","doc:\/\/com.mapbox.MapboxMaps\/s8CopyableP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH"],"kind":"relationships","title":"Conforms To"}],"abstract":[{"type":"text","text":"A Cancellable object that automatically cancels on deinit."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AnyCancelable","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"text":"Any resources referred by ","type":"text"},{"type":"codeVoice","code":"AnyCancelable"},{"type":"text","text":" will be released after cancellation."}]},{"inlineContent":[{"text":"This class has similar behavior to ","type":"text"},{"code":"Combine.AnyCancellable","type":"codeVoice"},{"type":"text","text":", but doesn’t require iOS 13."}],"type":"paragraph"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/anycancelable"]}],"kind":"symbol","seeAlsoSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Signal","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Cancelable","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/EventTimeInterval"],"title":"Foundation","anchor":"Foundation","generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events"]]},"references":{"doc://com.mapbox.MapboxMaps/s8CopyableP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s8CopyableP","type":"unresolvable","title":"Swift.Copyable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AnyCancelable/store(in:)-84gyl":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"store"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"C"},{"kind":"text","text":">("},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"text":"C","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AnyCancelable\/store(in:)-84gyl","url":"\/documentation\/mapboxmaps\/anycancelable\/store(in:)-84gyl","title":"store(in:)","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Stores cancellable object in collection of "},{"code":"Combine.AnyCancellable","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AnyCancelable/cancel()":{"url":"\/documentation\/mapboxmaps\/anycancelable\/cancel()","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AnyCancelable\/cancel()","title":"cancel()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cancel"},{"text":"()","kind":"text"}],"role":"symbol","type":"topic","abstract":[{"text":"Cancels the activity.","type":"text"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/EventTimeInterval":{"abstract":[{"text":"The time interval of an event. The ","type":"text"},{"code":"begin","type":"codeVoice"},{"text":" property represents the time","type":"text"},{"type":"text","text":" "},{"text":"origin of an event, and the ","type":"text"},{"code":"end","type":"codeVoice"},{"text":" property represents the time when the particular","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"operation is complete. The timestamps are sampled at the origin and do not include"},{"type":"text","text":" "},{"text":"the time required to dispatch an event.","type":"text"}],"type":"topic","title":"EventTimeInterval","kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/eventtimeinterval","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/EventTimeInterval","navigatorTitle":[{"text":"EventTimeInterval","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"EventTimeInterval","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AnyCancelable/Equatable-Implementations":{"role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AnyCancelable\/Equatable-Implementations","title":"Equatable Implementations","abstract":[],"url":"\/documentation\/mapboxmaps\/anycancelable\/equatable-implementations","kind":"article","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AnyCancelable/init(_:)-5to9x":{"abstract":[{"type":"text","text":"Creates AnyCancelable with the cancelling closure."}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AnyCancelable\/init(_:)-5to9x","kind":"symbol","title":"init(_:)","url":"\/documentation\/mapboxmaps\/anycancelable\/init(_:)-5to9x","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"(() -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AnyCancelable/store(in:)-7gtoz":{"kind":"symbol","role":"symbol","title":"store(in:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"store"},{"text":"(","kind":"text"},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"kind":"text","text":" "},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:7Combine14AnyCancellableC","text":"AnyCancellable"},{"kind":"text","text":">)"}],"abstract":[{"type":"text","text":"Stores cancellable object in set of "},{"code":"Combine.AnyCancellable","type":"codeVoice"},{"type":"text","text":"."}],"url":"\/documentation\/mapboxmaps\/anycancelable\/store(in:)-7gtoz","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AnyCancelable\/store(in:)-7gtoz"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AnyCancelable/Hashable-Implementations":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AnyCancelable\/Hashable-Implementations","url":"\/documentation\/mapboxmaps\/anycancelable\/hashable-implementations","title":"Hashable Implementations","role":"collectionGroup","type":"topic","abstract":[],"kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AnyCancelable/init(_:)-13kaj":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AnyCancelable\/init(_:)-13kaj","title":"init(_:)","abstract":[{"type":"text","text":"Creates AnyCancelable with the sequence of cancellables which will be canelled when AnyCancelable is cancelled."}],"url":"\/documentation\/mapboxmaps\/anycancelable\/init(_:)-13kaj","kind":"symbol","fragments":[{"text":"convenience","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"text":"<","kind":"text"},{"text":"S","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"S","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/SH":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AnyCancelable/store(in:)-oh7e":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AnyCancelable\/store(in:)-oh7e","title":"store(in:)","abstract":[{"text":"Stores cancellable object in a collection.","type":"text"}],"url":"\/documentation\/mapboxmaps\/anycancelable\/store(in:)-oh7e","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"store","kind":"identifier"},{"text":"<","kind":"text"},{"kind":"genericParameter","text":"C"},{"kind":"text","text":">("},{"text":"in","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"C"},{"kind":"text","text":")"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Cancelable":{"url":"\/documentation\/mapboxcommon\/cancelable","title":"Cancelable","role":"symbol","kind":"symbol","type":"topic","abstract":[{"text":"Allows to cancel the associated asynchronous operation","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"Cancelable"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Cancelable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Cancelable"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AnyCancelable":{"role":"symbol","navigatorTitle":[{"text":"AnyCancelable","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/anycancelable","abstract":[{"text":"A Cancellable object that automatically cancels on deinit.","type":"text"}],"type":"topic","title":"AnyCancelable","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AnyCancelable","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AnyCancelable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"abstract":[{"type":"text","text":"The simplified diagram of the events emitted by the map is displayed below."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","title":"Map events","url":"\/documentation\/mapboxmaps\/events","kind":"article","type":"topic","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","abstract":[],"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","kind":"article","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AnyCancelable/init(_:)-24hfp":{"fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"<"},{"text":"C","kind":"genericParameter"},{"kind":"text","text":">("},{"kind":"typeIdentifier","text":"C"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AnyCancelable\/init(_:)-24hfp","url":"\/documentation\/mapboxmaps\/anycancelable\/init(_:)-24hfp","title":"init(_:)","role":"symbol","type":"topic","abstract":[{"text":"Creates AnyCancelable with the canceler object.","type":"text"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AnyCancelable/store(in:)-3m1sp":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AnyCancelable\/store(in:)-3m1sp","title":"store(in:)","abstract":[{"text":"Stores cancellable object in a set.","type":"text"}],"url":"\/documentation\/mapboxmaps\/anycancelable\/store(in:)-3m1sp","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"store"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps13AnyCancelableC","text":"AnyCancelable","kind":"typeIdentifier"},{"text":">)","kind":"text"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Signal":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Signal","role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"Signal","kind":"identifier"}],"title":"Signal","navigatorTitle":[{"text":"Signal","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/signal","abstract":[{"type":"text","text":"Signal is a typed interface for observing arbitrary values over time."}]},"doc://com.mapbox.MapboxMaps/SQ":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","type":"unresolvable","title":"Swift.Equatable"}},"variantOverrides":[{"patch":[{"op":"replace","value":"MBMEventTimeInterval","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1EventTimeInterval\/title"},{"value":[{"text":"MBMEventTimeInterval","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1EventTimeInterval\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MBMEventTimeInterval"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1EventTimeInterval\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/title","value":"MBXCancelable","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/fragments","value":[{"kind":"identifier","text":"MBXCancelable"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/navigatorTitle","value":[{"kind":"identifier","text":"MBXCancelable"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}