{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePack"},"variants":[{"paths":["\/documentation\/mapboxmaps\/stylepack"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/stylepack"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"StylePack","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StylePack"}],"roleHeading":"Class","navigatorTitle":[{"text":"StylePack","kind":"identifier"}],"modules":[{"name":"MapboxMaps"}],"role":"symbol","externalID":"c:objc(cs)MBMStylePack"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs"]]},"sections":[],"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"style pack"},{"type":"text","text":" represents a stored style package."}],"seeAlsoSections":[{"title":"Style pack","anchor":"Style-pack","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleObjectInfo","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackError-swift.enum","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadProgress"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePack\/completedResourceCount","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePack\/completedResourceSize","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePack\/expires","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePack\/glyphsRasterizationMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePack\/requiredResourceCount","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePack\/styleURI"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true}],"relationshipsSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"StylePack","kind":"identifier"}]}],"kind":"declarations"}],"references":{"doc://com.mapbox.MapboxMaps/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePack":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePack","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"style pack"},{"text":" represents a stored style package.","type":"text"}],"kind":"symbol","title":"StylePack","role":"symbol","type":"topic","navigatorTitle":[{"text":"StylePack","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/stylepack","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"StylePack","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","abstract":[],"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","kind":"article","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePack/completedResourceSize":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePack\/completedResourceSize","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"completedResourceSize","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V","text":"UInt64"}],"url":"\/documentation\/mapboxmaps\/stylepack\/completedresourcesize","type":"topic","role":"symbol","kind":"symbol","abstract":[{"text":"The cumulative size, in bytes, of all resources that have","type":"text"},{"text":" ","type":"text"},{"text":"been fully downloaded.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"completedResourceSize"}],"title":"completedResourceSize"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePackError-swift.enum":{"kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StylePackError","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"StylePackError"}],"title":"StylePackError","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackError-swift.enum","type":"topic","url":"\/documentation\/mapboxmaps\/stylepackerror-swift.enum","abstract":[{"text":"Describes the reason for a style package download request failure.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePack/expires":{"title":"expires","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"expires"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"expires"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePack\/expires","abstract":[{"type":"text","text":"The earliest point in time when any of the style package resources gets expired."}],"url":"\/documentation\/mapboxmaps\/stylepack\/expires","type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleObjectInfo":{"url":"\/documentation\/mapboxmaps\/styleobjectinfo","abstract":[{"type":"text","text":"The information about style object (source or layer or light)."}],"type":"topic","role":"symbol","title":"StyleObjectInfo","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleObjectInfo","navigatorTitle":[{"text":"StyleObjectInfo","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"StyleObjectInfo","kind":"identifier"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePackLoadOptions":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadOptions","kind":"symbol","abstract":[{"type":"text","text":"Describes the style package load option values."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StylePackLoadOptions"}],"navigatorTitle":[{"text":"StylePackLoadOptions","kind":"identifier"}],"type":"topic","title":"StylePackLoadOptions","url":"\/documentation\/mapboxmaps\/stylepackloadoptions"},"doc://com.mapbox.MapboxMaps/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","title":"Swift.Equatable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"url":"\/documentation\/mapboxmaps\/tilestore-apis","title":"TileStore APIs","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","type":"topic","abstract":[],"role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePackLoadProgress":{"type":"topic","abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"style pack load"},{"text":" progress includes information about","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"the number of resources that have completed downloading"},{"type":"text","text":" "},{"type":"text","text":"and the total number of resources that are required."}],"navigatorTitle":[{"text":"StylePackLoadProgress","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/stylepackloadprogress","title":"StylePackLoadProgress","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadProgress","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StylePackLoadProgress"}]},"doc://com.mapbox.MapboxMaps/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject","title":"NSObject"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePack/requiredResourceCount":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePack\/requiredResourceCount","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The number of resources that are known to be required for this style package."}],"url":"\/documentation\/mapboxmaps\/stylepack\/requiredresourcecount","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"requiredResourceCount","kind":"identifier"},{"kind":"text","text":": "},{"text":"UInt64","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V"}],"type":"topic","title":"requiredResourceCount","navigatorTitle":[{"kind":"identifier","text":"requiredResourceCount"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePack/styleURI":{"title":"styleURI","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"styleURI","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"navigatorTitle":[{"text":"styleURI","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePack\/styleURI","abstract":[{"type":"text","text":"The style associated with the style package."}],"url":"\/documentation\/mapboxmaps\/stylepack\/styleuri","type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/SH":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","title":"Swift.Hashable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePack/glyphsRasterizationMode":{"title":"glyphsRasterizationMode","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"glyphsRasterizationMode"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@MBMGlyphsRasterizationMode","text":"GlyphsRasterizationMode","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"glyphsRasterizationMode"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePack\/glyphsRasterizationMode","abstract":[{"type":"text","text":"The glyphs rasterization mode of the style package."}],"url":"\/documentation\/mapboxmaps\/stylepack\/glyphsrasterizationmode","type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePack/completedResourceCount":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"completedResourceCount"},{"text":": ","kind":"text"},{"text":"UInt64","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePack\/completedResourceCount","abstract":[{"type":"text","text":"The number of resources that have been fully downloaded and are ready for"},{"type":"text","text":" "},{"type":"text","text":"offline access."}],"title":"completedResourceCount","url":"\/documentation\/mapboxmaps\/stylepack\/completedresourcecount","navigatorTitle":[{"text":"completedResourceCount","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"MBMStylePack","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","value":[{"text":"MBMStylePack","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MBMStylePack"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePack\/completedResourceCount","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePack\/completedResourceSize","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePack\/expires","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePack\/glyphsRasterizationMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePack\/requiredResourceCount","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePack\/styleURI"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true}]},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"]}],"op":"replace"},{"value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleObjectInfo","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadProgress"],"generated":true,"anchor":"Style-pack","title":"Style pack"}],"op":"replace","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBMStylePack"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePack\/title","op":"replace","value":"MBMStylePack"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePack\/fragments","value":[{"text":"MBMStylePack","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"MBMStylePack","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePack\/navigatorTitle"},{"op":"replace","value":"completedResourceSize","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePack~1completedResourceSize\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePack~1completedResourceSize\/fragments","op":"replace","value":[{"kind":"identifier","text":"completedResourceSize"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePack~1expires\/title","value":"expires"},{"value":[{"text":"expires","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePack~1expires\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleObjectInfo\/title","value":"MBMStyleObjectInfo","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBMStyleObjectInfo"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleObjectInfo\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleObjectInfo\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMStyleObjectInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadOptions\/title","value":"MBMStylePackLoadOptions"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadOptions\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMStylePackLoadOptions"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadOptions\/navigatorTitle","value":[{"kind":"identifier","text":"MBMStylePackLoadOptions"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadProgress\/title","op":"replace","value":"MBMStylePackLoadProgress"},{"value":[{"kind":"identifier","text":"MBMStylePackLoadProgress"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadProgress\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadProgress\/navigatorTitle","value":[{"text":"MBMStylePackLoadProgress","kind":"identifier"}],"op":"replace"},{"value":"requiredResourceCount","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePack~1requiredResourceCount\/title"},{"op":"replace","value":[{"kind":"identifier","text":"requiredResourceCount"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePack~1requiredResourceCount\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePack~1styleURI\/title","value":"styleURI"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePack~1styleURI\/fragments","value":[{"text":"styleURI","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePack~1glyphsRasterizationMode\/title","value":"glyphsRasterizationMode"},{"op":"replace","value":[{"kind":"identifier","text":"glyphsRasterizationMode"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePack~1glyphsRasterizationMode\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePack~1completedResourceCount\/title","op":"replace","value":"completedResourceCount"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePack~1completedResourceCount\/fragments","value":[{"text":"completedResourceCount","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}