{"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","seeAlsoSections":[{"anchor":"Layer-Property-Values","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Value","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Anchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CirclePitchAlignment","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CirclePitchScale","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CircleTranslateAnchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillExtrusionTranslateAnchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillTranslateAnchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeIlluminationAnchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconAnchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconPitchAlignment","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconRotationAlignment","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconTextFit","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconTranslateAnchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineCap","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineJoin","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineTranslateAnchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterResampling","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResolvedImage","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResolvedImageData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValue","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValueKind","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SkyType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleColor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleTransition","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolPlacement","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolZOrder","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextJustify","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextPitchAlignment","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextRotationAlignment","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextTransform","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextTranslateAnchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextWritingMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Visibility","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TransitionOptions-swift.struct","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelScaleMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolElevationReference","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/BackgroundPitchAlignment","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillExtrusionBaseAlignment","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillExtrusionHeightAlignment","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillElevationReference","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineElevationReference","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineWidthUnit","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelElevationReference","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageContent","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageStretches"],"title":"Layer Property Values","generated":true}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer-Property-Values"]]},"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/Se","doc:\/\/com.mapbox.MapboxMaps\/SE","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH","doc:\/\/com.mapbox.MapboxMaps\/SY","doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"],"kind":"relationships"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/textanchor"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TextAnchor"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"title":"TextAnchor","modules":[{"name":"MapboxMaps"}],"role":"symbol","externalID":"s:10MapboxMaps10TextAnchorV","symbolKind":"struct","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TextAnchor"}],"navigatorTitle":[{"text":"TextAnchor","kind":"identifier"}],"roleHeading":"Structure"},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextAnchor","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextAnchor\/init(rawValue:)"],"generated":true},{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextAnchor\/rawValue"]},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextAnchor\/bottom","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextAnchor\/bottomLeft","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextAnchor\/bottomRight","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextAnchor\/center","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextAnchor\/left","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextAnchor\/right","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextAnchor\/top","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextAnchor\/topLeft","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextAnchor\/topRight"],"anchor":"Type-Properties","title":"Type Properties","generated":true},{"generated":true,"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextAnchor\/Equatable-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextAnchor\/RawRepresentable-Implementations"]}],"abstract":[{"type":"text","text":"Part of the text placed closest to the anchor."}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TextAnchor/topRight":{"abstract":[{"type":"text","text":"The top right corner of the text is placed closest to the anchor."}],"url":"\/documentation\/mapboxmaps\/textanchor\/topright","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextAnchor\/topRight","title":"topRight","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"topRight","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TextAnchor","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps10TextAnchorV"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TextAnchor":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TextAnchor"}],"title":"TextAnchor","role":"symbol","abstract":[{"text":"Part of the text placed closest to the anchor.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"TextAnchor"}],"url":"\/documentation\/mapboxmaps\/textanchor","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextAnchor","kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeIlluminationAnchor":{"title":"HillshadeIlluminationAnchor","kind":"symbol","url":"\/documentation\/mapboxmaps\/hillshadeilluminationanchor","abstract":[{"type":"text","text":"Direction of light source when map is rotated."}],"type":"topic","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"HillshadeIlluminationAnchor","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeIlluminationAnchor","navigatorTitle":[{"text":"HillshadeIlluminationAnchor","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TextTransform":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"TextTransform","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Specifies how to capitalize text, similar to the CSS "},{"code":"text-transform","type":"codeVoice"},{"type":"text","text":" property."}],"type":"topic","kind":"symbol","title":"TextTransform","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextTransform","navigatorTitle":[{"text":"TextTransform","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/texttransform"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ImageContent":{"role":"symbol","url":"\/documentation\/mapboxmaps\/imagecontent","type":"topic","abstract":[{"type":"text","text":"Describes the image content, e.g. where text can be fit into an image."}],"kind":"symbol","title":"ImageContent","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageContent","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageContent","navigatorTitle":[{"text":"ImageContent","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","abstract":[],"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","kind":"article","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TextAnchor/left":{"title":"left","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextAnchor\/left","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"left","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps10TextAnchorV","text":"TextAnchor"}],"url":"\/documentation\/mapboxmaps\/textanchor\/left","abstract":[{"text":"The left side of the text is placed closest to the anchor.","type":"text"}],"type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LineJoin":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LineJoin"}],"role":"symbol","abstract":[{"text":"The display of lines when joining.","type":"text"}],"type":"topic","kind":"symbol","title":"LineJoin","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineJoin","navigatorTitle":[{"kind":"identifier","text":"LineJoin"}],"url":"\/documentation\/mapboxmaps\/linejoin"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TextAnchor/bottom":{"url":"\/documentation\/mapboxmaps\/textanchor\/bottom","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextAnchor\/bottom","title":"bottom","kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"The bottom of the text is placed closest to the anchor."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"bottom","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps10TextAnchorV","text":"TextAnchor"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/IconTranslateAnchor":{"url":"\/documentation\/mapboxmaps\/icontranslateanchor","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconTranslateAnchor","kind":"symbol","title":"IconTranslateAnchor","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IconTranslateAnchor"}],"role":"symbol","abstract":[{"text":"Controls the frame of reference for ","type":"text"},{"code":"icon-translate","type":"codeVoice"},{"text":".","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IconTranslateAnchor","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TransitionOptions-swift.struct":{"navigatorTitle":[{"kind":"identifier","text":"TransitionOptions"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/transitionoptions-swift.struct","type":"topic","title":"TransitionOptions","role":"symbol","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"TransitionOptions"},{"type":"text","text":" control timing for the interpolation between a transitionable style"},{"type":"text","text":" "},{"type":"text","text":"property’s previous value and new value. These can be used to define the style default property"},{"text":" ","type":"text"},{"type":"text","text":"transition behavior. Also, any transitionable style property may also have its own "},{"type":"codeVoice","code":"-transition"},{"type":"text","text":" "},{"text":"property that defines specific transition timing for that specific layer property, overriding","type":"text"},{"type":"text","text":" "},{"type":"text","text":"the global transition values."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TransitionOptions-swift.struct","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TransitionOptions","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FillExtrusionHeightAlignment":{"abstract":[{"text":"Controls the behavior of fill extrusion height over terrain","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FillExtrusionHeightAlignment"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillExtrusionHeightAlignment","navigatorTitle":[{"text":"FillExtrusionHeightAlignment","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxmaps\/fillextrusionheightalignment","title":"FillExtrusionHeightAlignment","role":"symbol","tags":[{"type":"spi","text":"SPI"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelScaleMode":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"ModelScaleMode","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Defines scaling mode. Only applies to location-indicator type layers.","type":"text"}],"type":"topic","kind":"symbol","tags":[{"type":"spi","text":"SPI"}],"title":"ModelScaleMode","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelScaleMode","navigatorTitle":[{"kind":"identifier","text":"ModelScaleMode"}],"url":"\/documentation\/mapboxmaps\/modelscalemode"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layer-Property-Values":{"abstract":[],"type":"topic","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/layer-property-values","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer-Property-Values","title":"Layer Property Values"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FillElevationReference":{"title":"FillElevationReference","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FillElevationReference"}],"tags":[{"text":"SPI","type":"spi"}],"navigatorTitle":[{"text":"FillElevationReference","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/fillelevationreference","abstract":[{"type":"text","text":"Selects the base of fill-elevation. Some modes might require precomputed elevation data in the tileset."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillElevationReference"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SymbolElevationReference":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SymbolElevationReference","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Selects the base of symbol-elevation."}],"type":"topic","kind":"symbol","tags":[{"type":"spi","text":"SPI"}],"title":"SymbolElevationReference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolElevationReference","navigatorTitle":[{"text":"SymbolElevationReference","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/symbolelevationreference"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TextAnchor/bottomLeft":{"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bottomLeft"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10MapboxMaps10TextAnchorV","kind":"typeIdentifier","text":"TextAnchor"}],"role":"symbol","kind":"symbol","url":"\/documentation\/mapboxmaps\/textanchor\/bottomleft","abstract":[{"type":"text","text":"The bottom left corner of the text is placed closest to the anchor."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextAnchor\/bottomLeft","title":"bottomLeft"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TextWritingMode":{"type":"topic","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"TextWritingMode","kind":"identifier"}],"navigatorTitle":[{"text":"TextWritingMode","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/textwritingmode","role":"symbol","title":"TextWritingMode","abstract":[{"type":"text","text":"The property allows control over a symbol’s orientation. Note that the property values act as a hint, so that a symbol whose language doesn’t support the provided orientation will be laid out in its natural orientation. Example: English point symbol will be rendered horizontally even if array value contains single ‘vertical’ enum value. For symbol with point placement, the order of elements in an array define priority order for the placement of an orientation variant. For symbol with line placement, the default text writing mode is either [‘horizontal’, ‘vertical’] or [‘vertical’, ‘horizontal’], the order doesn’t affect the placement."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextWritingMode"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TextAnchor/center":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"center","kind":"identifier"},{"kind":"text","text":": "},{"text":"TextAnchor","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps10TextAnchorV"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextAnchor\/center","title":"center","url":"\/documentation\/mapboxmaps\/textanchor\/center","type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"The center of the text is placed closest to the anchor.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TextAnchor/right":{"abstract":[{"text":"The right side of the text is placed closest to the anchor.","type":"text"}],"url":"\/documentation\/mapboxmaps\/textanchor\/right","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextAnchor\/right","title":"right","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"right","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps10TextAnchorV","text":"TextAnchor","kind":"typeIdentifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/IconRotationAlignment":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconRotationAlignment","title":"IconRotationAlignment","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"IconRotationAlignment","kind":"identifier"}],"abstract":[{"type":"text","text":"In combination with "},{"code":"symbol-placement","type":"codeVoice"},{"type":"text","text":", determines the rotation behavior of icons."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"IconRotationAlignment"}],"url":"\/documentation\/mapboxmaps\/iconrotationalignment","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResolvedImageData":{"abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ResolvedImageData"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResolvedImageData","navigatorTitle":[{"kind":"identifier","text":"ResolvedImageData"}],"type":"topic","url":"\/documentation\/mapboxmaps\/resolvedimagedata","title":"ResolvedImageData","role":"symbol"},"doc://com.mapbox.MapboxMaps/SE":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SE","title":"Swift.Encodable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LineWidthUnit":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"LineWidthUnit","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Selects the unit of line-width. The same unit is automatically used for line-blur and line-offset. Note: This is an experimental property and might be removed in a future release.","type":"text"}],"type":"topic","kind":"symbol","tags":[{"text":"SPI","type":"spi"}],"title":"LineWidthUnit","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineWidthUnit","navigatorTitle":[{"text":"LineWidthUnit","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/linewidthunit"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TextAnchor/topLeft":{"abstract":[{"type":"text","text":"The top left corner of the text is placed closest to the anchor."}],"url":"\/documentation\/mapboxmaps\/textanchor\/topleft","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextAnchor\/topLeft","title":"topLeft","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"topLeft"},{"kind":"text","text":": "},{"text":"TextAnchor","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps10TextAnchorV"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleTransition":{"title":"StyleTransition","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"StyleTransition","kind":"identifier"}],"abstract":[{"text":"The transition property for a layer.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"A transition property controls timing for the interpolation between a"},{"text":" ","type":"text"},{"type":"text","text":"transitionable style property’s previous value and new value."}],"url":"\/documentation\/mapboxmaps\/styletransition","navigatorTitle":[{"text":"StyleTransition","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleTransition","type":"topic","kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TextAnchor/RawRepresentable-Implementations":{"kind":"article","role":"collectionGroup","title":"RawRepresentable Implementations","type":"topic","url":"\/documentation\/mapboxmaps\/textanchor\/rawrepresentable-implementations","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextAnchor\/RawRepresentable-Implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TextPitchAlignment":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"TextPitchAlignment","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Orientation of text when map is pitched."}],"type":"topic","kind":"symbol","title":"TextPitchAlignment","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextPitchAlignment","navigatorTitle":[{"kind":"identifier","text":"TextPitchAlignment"}],"url":"\/documentation\/mapboxmaps\/textpitchalignment"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ImageStretches":{"abstract":[{"text":"Describes the image stretch areas.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ImageStretches"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageStretches","navigatorTitle":[{"kind":"identifier","text":"ImageStretches"}],"type":"topic","url":"\/documentation\/mapboxmaps\/imagestretches","title":"ImageStretches","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FillTranslateAnchor":{"abstract":[{"text":"Controls the frame of reference for ","type":"text"},{"code":"fill-translate","type":"codeVoice"},{"type":"text","text":"."}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FillTranslateAnchor"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillTranslateAnchor","navigatorTitle":[{"text":"FillTranslateAnchor","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxmaps\/filltranslateanchor","title":"FillTranslateAnchor","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LineTranslateAnchor":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"LineTranslateAnchor","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Controls the frame of reference for "},{"code":"line-translate","type":"codeVoice"},{"type":"text","text":"."}],"type":"topic","kind":"symbol","title":"LineTranslateAnchor","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineTranslateAnchor","navigatorTitle":[{"kind":"identifier","text":"LineTranslateAnchor"}],"url":"\/documentation\/mapboxmaps\/linetranslateanchor"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelType":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"ModelType","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Defines rendering behavior of model in respect to other 3D scene objects.","type":"text"}],"type":"topic","kind":"symbol","tags":[{"type":"spi","text":"SPI"}],"title":"ModelType","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelType","navigatorTitle":[{"text":"ModelType","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/modeltype"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterResampling":{"abstract":[{"type":"text","text":"The resampling\/interpolation method to use for overscaling, also known as texture magnification filter"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"RasterResampling","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterResampling","navigatorTitle":[{"text":"RasterResampling","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxmaps\/rasterresampling","title":"RasterResampling","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelElevationReference":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ModelElevationReference"}],"role":"symbol","abstract":[{"type":"text","text":"Selects the base of the model. Some modes might require precomputed elevation data in the tileset."}],"type":"topic","kind":"symbol","tags":[{"text":"SPI","type":"spi"}],"title":"ModelElevationReference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelElevationReference","navigatorTitle":[{"text":"ModelElevationReference","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/modelelevationreference"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TextTranslateAnchor":{"abstract":[{"type":"text","text":"Controls the frame of reference for "},{"type":"codeVoice","code":"text-translate"},{"text":".","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TextTranslateAnchor"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextTranslateAnchor","navigatorTitle":[{"text":"TextTranslateAnchor","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxmaps\/texttranslateanchor","title":"TextTranslateAnchor","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TextAnchor/Equatable-Implementations":{"title":"Equatable Implementations","kind":"article","abstract":[],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextAnchor\/Equatable-Implementations","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/textanchor\/equatable-implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FillExtrusionBaseAlignment":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FillExtrusionBaseAlignment","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Controls the behavior of fill extrusion base over terrain"}],"type":"topic","kind":"symbol","tags":[{"text":"SPI","type":"spi"}],"title":"FillExtrusionBaseAlignment","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillExtrusionBaseAlignment","navigatorTitle":[{"kind":"identifier","text":"FillExtrusionBaseAlignment"}],"url":"\/documentation\/mapboxmaps\/fillextrusionbasealignment"},"doc://com.mapbox.MapboxMaps/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Visibility":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Visibility","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Visibility"}],"url":"\/documentation\/mapboxmaps\/visibility","title":"Visibility","type":"topic","role":"symbol","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Visibility"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TextRotationAlignment":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"TextRotationAlignment","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/mapboxmaps\/textrotationalignment","abstract":[{"text":"In combination with ","type":"text"},{"type":"codeVoice","code":"symbol-placement"},{"text":", determines the rotation behavior of the individual glyphs forming the text.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"TextRotationAlignment"}],"title":"TextRotationAlignment","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextRotationAlignment"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SkyType":{"abstract":[{"type":"text","text":"The type of the sky"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SkyType"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SkyType","navigatorTitle":[{"text":"SkyType","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxmaps\/skytype","title":"SkyType","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TextAnchor/init(rawValue:)":{"title":"init(rawValue:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextAnchor\/init(rawValue:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"url":"\/documentation\/mapboxmaps\/textanchor\/init(rawvalue:)","abstract":[],"type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResolvedImage":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ResolvedImage","kind":"identifier"}],"role":"symbol","abstract":[],"type":"topic","kind":"symbol","title":"ResolvedImage","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResolvedImage","navigatorTitle":[{"text":"ResolvedImage","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/resolvedimage"},"doc://com.mapbox.MapboxMaps/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Anchor":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Anchor","kind":"symbol","abstract":[{"type":"text","text":"Whether extruded geometries are lit relative to the map or viewport."}],"type":"topic","role":"symbol","title":"Anchor","url":"\/documentation\/mapboxmaps\/anchor","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Anchor","kind":"identifier"}],"navigatorTitle":[{"text":"Anchor","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CirclePitchScale":{"navigatorTitle":[{"text":"CirclePitchScale","kind":"identifier"}],"abstract":[{"text":"Controls the scaling behavior of the circle when the map is pitched.","type":"text"}],"url":"\/documentation\/mapboxmaps\/circlepitchscale","type":"topic","kind":"symbol","title":"CirclePitchScale","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CirclePitchScale"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CirclePitchScale"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CircleTranslateAnchor":{"abstract":[{"type":"text","text":"Controls the frame of reference for "},{"type":"codeVoice","code":"circle-translate"},{"type":"text","text":"."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CircleTranslateAnchor","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CircleTranslateAnchor","navigatorTitle":[{"text":"CircleTranslateAnchor","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxmaps\/circletranslateanchor","title":"CircleTranslateAnchor","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SymbolPlacement":{"title":"SymbolPlacement","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolPlacement","kind":"symbol","abstract":[{"type":"text","text":"Label placement relative to its geometry."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SymbolPlacement","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/symbolplacement","navigatorTitle":[{"kind":"identifier","text":"SymbolPlacement"}],"role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Value":{"url":"\/documentation\/mapboxmaps\/value","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Value","title":"Value","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Value"}],"role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Value"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/IconTextFit":{"title":"IconTextFit","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconTextFit","kind":"symbol","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IconTextFit","kind":"identifier"}],"abstract":[{"type":"text","text":"Scales the icon to fit around the associated text."}],"url":"\/documentation\/mapboxmaps\/icontextfit","role":"symbol","navigatorTitle":[{"text":"IconTextFit","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LineElevationReference":{"abstract":[{"type":"text","text":"Selects the base of line-elevation. Some modes might require precomputed elevation data in the tileset."}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LineElevationReference"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineElevationReference","navigatorTitle":[{"text":"LineElevationReference","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxmaps\/lineelevationreference","title":"LineElevationReference","role":"symbol","tags":[{"text":"SPI","type":"spi"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePropertyValueKind":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"StylePropertyValueKind","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Describes the kind of a style property value.","type":"text"}],"type":"topic","kind":"symbol","title":"StylePropertyValueKind","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValueKind","navigatorTitle":[{"text":"StylePropertyValueKind","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/stylepropertyvaluekind"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/IconAnchor":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconAnchor","type":"topic","url":"\/documentation\/mapboxmaps\/iconanchor","title":"IconAnchor","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"IconAnchor"}],"abstract":[{"type":"text","text":"Part of the icon placed closest to the anchor."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"IconAnchor"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SymbolZOrder":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SymbolZOrder","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Determines whether overlapping symbols in the same layer are rendered in the order that they appear in the data source or by their y-position relative to the viewport. To control the order and prioritization of symbols otherwise, use "},{"type":"codeVoice","code":"symbol-sort-key"},{"type":"text","text":"."}],"type":"topic","kind":"symbol","title":"SymbolZOrder","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolZOrder","navigatorTitle":[{"text":"SymbolZOrder","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/symbolzorder"},"doc://com.mapbox.MapboxMaps/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SY"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TextJustify":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TextJustify"}],"role":"symbol","abstract":[{"type":"text","text":"Text justification options."}],"type":"topic","kind":"symbol","title":"TextJustify","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextJustify","navigatorTitle":[{"text":"TextJustify","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/textjustify"},"doc://com.mapbox.MapboxMaps/Se":{"title":"Swift.Decodable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/Se"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TextAnchor/bottomRight":{"url":"\/documentation\/mapboxmaps\/textanchor\/bottomright","title":"bottomRight","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"bottomRight","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TextAnchor","preciseIdentifier":"s:10MapboxMaps10TextAnchorV"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextAnchor\/bottomRight","type":"topic","abstract":[{"type":"text","text":"The bottom right corner of the text is placed closest to the anchor."}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CirclePitchAlignment":{"title":"CirclePitchAlignment","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CirclePitchAlignment"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"CirclePitchAlignment","kind":"identifier"}],"abstract":[{"type":"text","text":"Orientation of circle when map is pitched."}],"url":"\/documentation\/mapboxmaps\/circlepitchalignment","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CirclePitchAlignment"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LineCap":{"type":"topic","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LineCap"}],"url":"\/documentation\/mapboxmaps\/linecap","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineCap","abstract":[{"type":"text","text":"The display of line endings."}],"role":"symbol","navigatorTitle":[{"text":"LineCap","kind":"identifier"}],"title":"LineCap"},"https://docs.mapbox.com/style-spec/reference/types/#color":{"title":"Mapbox Style Spec","type":"link","url":"https:\/\/docs.mapbox.com\/style-spec\/reference\/types\/#color","titleInlineContent":[{"text":"Mapbox Style Spec","type":"text"}],"identifier":"https:\/\/docs.mapbox.com\/style-spec\/reference\/types\/#color"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TextAnchor/rawValue":{"type":"topic","url":"\/documentation\/mapboxmaps\/textanchor\/rawvalue","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rawValue"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextAnchor\/rawValue","role":"symbol","title":"rawValue","abstract":[],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/IconPitchAlignment":{"title":"IconPitchAlignment","kind":"symbol","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IconPitchAlignment","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"IconPitchAlignment"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/iconpitchalignment","abstract":[{"type":"text","text":"Orientation of icon when map is pitched."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconPitchAlignment"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FillExtrusionTranslateAnchor":{"navigatorTitle":[{"kind":"identifier","text":"FillExtrusionTranslateAnchor"}],"kind":"symbol","title":"FillExtrusionTranslateAnchor","abstract":[{"type":"text","text":"Controls the frame of reference for "},{"type":"codeVoice","code":"fill-extrusion-translate"},{"type":"text","text":"."}],"type":"topic","url":"\/documentation\/mapboxmaps\/fillextrusiontranslateanchor","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FillExtrusionTranslateAnchor"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillExtrusionTranslateAnchor"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TextAnchor/top":{"abstract":[{"text":"The top of the text is placed closest to the anchor.","type":"text"}],"url":"\/documentation\/mapboxmaps\/textanchor\/top","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextAnchor\/top","title":"top","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"top","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps10TextAnchorV","text":"TextAnchor","kind":"typeIdentifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/BackgroundPitchAlignment":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"BackgroundPitchAlignment","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Orientation of background layer."}],"type":"topic","kind":"symbol","tags":[{"text":"SPI","type":"spi"}],"title":"BackgroundPitchAlignment","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/BackgroundPitchAlignment","navigatorTitle":[{"text":"BackgroundPitchAlignment","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/backgroundpitchalignment"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleColor":{"url":"\/documentation\/mapboxmaps\/stylecolor","abstract":[{"type":"text","text":"Represents a color as defined by the "},{"type":"reference","isActive":true,"identifier":"https:\/\/docs.mapbox.com\/style-spec\/reference\/types\/#color"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleColor","navigatorTitle":[{"text":"StyleColor","kind":"identifier"}],"title":"StyleColor","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"StyleColor","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePropertyValue":{"abstract":[{"type":"text","text":"Holds a style property value with meta data."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StylePropertyValue"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValue","navigatorTitle":[{"kind":"identifier","text":"StylePropertyValue"}],"type":"topic","url":"\/documentation\/mapboxmaps\/stylepropertyvalue","title":"StylePropertyValue","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ImageContent\/title","value":"MBMImageContent"},{"op":"replace","value":[{"text":"MBMImageContent","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ImageContent\/fragments"},{"value":[{"kind":"identifier","text":"MBMImageContent"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ImageContent\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ImageStretches\/title","value":"MBMImageStretches","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ImageStretches\/fragments","value":[{"kind":"identifier","text":"MBMImageStretches"}]},{"value":[{"kind":"identifier","text":"MBMImageStretches"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ImageStretches\/navigatorTitle"},{"op":"replace","value":"MBMStylePropertyValueKind","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValueKind\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValueKind\/fragments","value":[{"text":"MBMStylePropertyValueKind","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValueKind\/navigatorTitle","value":[{"kind":"identifier","text":"MBMStylePropertyValueKind"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValue\/title","value":"MBMStylePropertyValue"},{"value":[{"kind":"identifier","text":"MBMStylePropertyValue"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValue\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValue\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMStylePropertyValue"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}