{"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GeometryType_MultiPoint","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType","text":"GeometryType","preciseIdentifier":"c:@EA@MBXGeometryType"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType_MultiPoint"},"metadata":{"symbolKind":"var","role":"symbol","roleHeading":"Global Variable","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GeometryType_MultiPoint"},{"text":": ","kind":"text"},{"text":"GeometryType","kind":"typeIdentifier","preciseIdentifier":"c:@EA@MBXGeometryType"}],"modules":[{"name":"MapboxCommon"}],"navigatorTitle":[{"kind":"identifier","text":"MBXGeometryType_MultiPoint"}],"externalID":"c:@EA@MBXGeometryType@MBXGeometryType_MultiPoint","title":"GeometryType_MultiPoint"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon"],["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TurfAPI","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/geometrytype_multipoint"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/geometrytype_multipoint"]}],"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TurfAPI":{"role":"collectionGroup","abstract":[{"text":"Describes ","type":"text"},{"code":"turf-swift","type":"codeVoice"},{"type":"text","text":" dependency objects"}],"kind":"article","title":"Turf","url":"\/documentation\/mapboxmaps\/turfapi","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TurfAPI"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","abstract":[],"title":"MapboxCommon","kind":"symbol","type":"topic","url":"\/documentation\/mapboxcommon","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","kind":"article","role":"collection","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"title":"MapboxMaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/GeometryType":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GeometryType"}],"url":"\/documentation\/mapboxcommon\/geometrytype","navigatorTitle":[{"kind":"identifier","text":"GeometryType"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType","title":"GeometryType","abstract":[],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/GeometryType_MultiPoint":{"abstract":[],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GeometryType_MultiPoint","kind":"identifier"},{"kind":"text","text":": "},{"text":"GeometryType","kind":"typeIdentifier","preciseIdentifier":"c:@EA@MBXGeometryType"}],"navigatorTitle":[{"text":"MBXGeometryType_MultiPoint","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxcommon\/geometrytype_multipoint","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType_MultiPoint","title":"GeometryType_MultiPoint","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"MBXGeometryType_MultiPoint"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MBXGeometryType_MultiPoint","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"MBXGeometryType_MultiPoint","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType\/title","value":"MBXGeometryType","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType\/fragments","op":"replace","value":[{"text":"","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType\/navigatorTitle","value":[{"text":"MBXGeometryType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType_MultiPoint\/title","value":"MBXGeometryType_MultiPoint","op":"replace"},{"value":[{"text":"MBXGeometryType_MultiPoint","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType_MultiPoint\/fragments","op":"replace"}]}]}