{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs"]]},"topicSections":[{"anchor":"Initializers","generated":true,"title":"Initializers","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateResult\/init(errorMargin:transferSize:storageSize:extraData:)"]},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateResult\/errorMargin","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateResult\/extraData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateResult\/storageSize","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateResult\/transferSize"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateResult\/isEqual(to:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH"],"type":"conformsTo","kind":"relationships"}],"abstract":[{"type":"text","text":"The result of tile region estim"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/tileregionestimateresult"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/tileregionestimateresult"]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateResult","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TileRegionEstimateResult"}],"platforms":["iOS"]}],"kind":"declarations"}],"seeAlsoSections":[{"title":"TileStore","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStoreOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudget","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInMegabytes","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInTiles","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCoverOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegion","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileRegionError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgress","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TilesetDescriptor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TilesetDescriptorOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgressCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreUsageMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileRegionError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileDataDomain","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgress","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgressCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingErrorType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClearCacheError"],"generated":true,"anchor":"TileStore"}],"metadata":{"roleHeading":"Class","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileRegionEstimateResult","kind":"identifier"}],"externalID":"c:objc(cs)MBXTileRegionEstimateResult","modules":[{"name":"MapboxCommon"}],"symbolKind":"class","title":"TileRegionEstimateResult","navigatorTitle":[{"text":"TileRegionEstimateResult","kind":"identifier"}]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/CacheClearingErrorType":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"CacheClearingErrorType","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/cacheclearingerrortype","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingErrorType","role":"symbol","abstract":[{"text":"Describes the reason for a cache clearing failure.","type":"text"}],"type":"topic","title":"CacheClearingErrorType","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CacheClearingErrorType"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ClearCacheError":{"navigatorTitle":[{"text":"ClearCacheError","kind":"identifier"}],"title":"ClearCacheError","role":"symbol","url":"\/documentation\/mapboxmaps\/clearcacheerror","abstract":[{"text":"Describes the reason for a cache clearing failure.","type":"text"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ClearCacheError","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClearCacheError"},"doc://com.mapbox.MapboxMaps/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","title":"Swift.Equatable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileRegionError":{"type":"topic","navigatorTitle":[{"text":"TileRegionError","kind":"identifier"}],"role":"symbol","title":"TileRegionError","abstract":[{"text":"Describes the reason for a tile region download request failure.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileRegionError"}],"url":"\/documentation\/mapboxmaps\/tileregionerror","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileRegionError","kind":"symbol"},"doc://com.mapbox.MapboxMaps/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileStoreOptions":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStoreOptions","title":"TileStoreOptions","abstract":[{"type":"text","text":"These constants can be used as keys for TileStore::setOption to configure further aspects of a TileStore instance."}],"role":"symbol","navigatorTitle":[{"text":"TileStoreOptions","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/tilestoreoptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileStoreOptions"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","kind":"article","role":"collection","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadProgressCallback":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileRegionLoadProgressCallback"}],"navigatorTitle":[{"kind":"identifier","text":"TileRegionLoadProgressCallback"}],"type":"topic","title":"TileRegionLoadProgressCallback","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgressCallback","url":"\/documentation\/mapboxcommon\/tileregionloadprogresscallback","role":"symbol","kind":"symbol","abstract":[{"text":"Callback Invoked to report the progess of the tile region loading operation.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateResult/extraData":{"url":"\/documentation\/mapboxcommon\/tileregionestimateresult\/extradata","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateResult\/extraData","abstract":[{"type":"text","text":"Reserved for future use."}],"type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"extraData"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"extraData"}],"role":"symbol","title":"extraData"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudgetInTiles":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"TileCacheBudgetInTiles"}],"role":"symbol","title":"TileCacheBudgetInTiles","abstract":[{"text":"Tile cache budget in tiles.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TileCacheBudgetInTiles","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/tilecachebudgetintiles","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInTiles","kind":"symbol"},"doc://com.mapbox.MapboxMaps/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateResult/errorMargin":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateResult\/errorMargin","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"errorMargin","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"abstract":[{"text":"Error margin of the estimate, given a fixed confidence level of 99.9%, represented by","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"a value between 0 and 1. There is a 99.9% probability that the real value is contained"},{"type":"text","text":" "},{"text":"in the interval [ (1 - errorMargin) * estimated value, (1 + errorMargin) * estimated value].","type":"text"}],"kind":"symbol","title":"errorMargin","navigatorTitle":[{"text":"errorMargin","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/tileregionestimateresult\/errormargin"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"url":"\/documentation\/mapboxmaps\/tilestore-apis","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","title":"TileStore APIs","abstract":[],"type":"topic","kind":"article","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CanonicalTileID":{"title":"CanonicalTileID","url":"\/documentation\/mapboxmaps\/canonicaltileid","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID","role":"symbol","type":"topic","navigatorTitle":[{"text":"CanonicalTileID","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CanonicalTileID","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Represents a tile coordinate.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateProgress":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgress","abstract":[{"type":"text","text":"A tile region’s estimate progress includes counts of the number of resources that have"},{"type":"text","text":" "},{"type":"text","text":"been estimated and the total number of resources as well as a partial result with the"},{"type":"text","text":" "},{"text":"current estimate, calculated using the data available at the moment.","type":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/mapboxcommon\/tileregionestimateprogress","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TileRegionEstimateProgress"}],"navigatorTitle":[{"text":"TileRegionEstimateProgress","kind":"identifier"}],"role":"symbol","title":"TileRegionEstimateProgress"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateResult":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateResult","abstract":[{"type":"text","text":"The result of tile region estim"}],"type":"topic","kind":"symbol","url":"\/documentation\/mapboxcommon\/tileregionestimateresult","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileRegionEstimateResult"}],"navigatorTitle":[{"kind":"identifier","text":"TileRegionEstimateResult"}],"role":"symbol","title":"TileRegionEstimateResult"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadOptions":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileRegionLoadOptions","kind":"identifier"}],"title":"TileRegionLoadOptions","role":"symbol","type":"topic","navigatorTitle":[{"text":"TileRegionLoadOptions","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Describes the tile region load option values."}],"url":"\/documentation\/mapboxcommon\/tileregionloadoptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileStore":{"role":"symbol","navigatorTitle":[{"text":"TileStore","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileStore"}],"kind":"symbol","url":"\/documentation\/mapboxcommon\/tilestore","type":"topic","title":"TileStore","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore","abstract":[{"text":"TileStore manages downloads and storage for requests to tile-related API endpoints, enforcing a disk usage","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"quota: tiles available on disk may be deleted to make room for a new download. This interface can be used by an"},{"type":"text","text":" "},{"text":"app developer to set the disk quota. The rest of TileStore API is intended for native SDK consumption only.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateOptions":{"navigatorTitle":[{"kind":"identifier","text":"TileRegionEstimateOptions"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateOptions","abstract":[{"type":"text","text":"Holds options for the tile region estimation operation."}],"url":"\/documentation\/mapboxcommon\/tileregionestimateoptions","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TileRegionEstimateOptions"}],"type":"topic","kind":"symbol","role":"symbol","title":"TileRegionEstimateOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStoreObserver":{"type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/tilestoreobserver","title":"TileStoreObserver","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"TileStoreObserver","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreObserver","navigatorTitle":[{"text":"TileStoreObserver","kind":"identifier"}],"abstract":[]},"doc://com.mapbox.MapboxMaps/objc(cs)NSObject":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TilesetDescriptor":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"TilesetDescriptor"}],"role":"symbol","title":"TilesetDescriptor","abstract":[{"text":"A bundle that encapsulates tilesets creation for the tile store implementation.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TilesetDescriptor","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/tilesetdescriptor","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TilesetDescriptor","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudgetInMegabytes":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"TileCacheBudgetInMegabytes"}],"role":"symbol","title":"TileCacheBudgetInMegabytes","abstract":[{"text":"Tile cache budget in megabytes.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileCacheBudgetInMegabytes"}],"url":"\/documentation\/mapboxmaps\/tilecachebudgetinmegabytes","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInMegabytes"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileOptions":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TileOptions","kind":"identifier"}],"title":"TileOptions","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TileOptions"}],"kind":"symbol","abstract":[{"type":"text","text":"Options for custom geometry tiles."}],"url":"\/documentation\/mapboxmaps\/tileoptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadProgress":{"role":"symbol","navigatorTitle":[{"text":"TileRegionLoadProgress","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TileRegionLoadProgress","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapboxcommon\/tileregionloadprogress","type":"topic","title":"TileRegionLoadProgress","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgress","abstract":[{"text":"A tile region’s load progress includes counts","type":"text"},{"type":"text","text":" "},{"type":"text","text":"of the number of resources that have completed downloading"},{"text":" ","type":"text"},{"text":"and the total number of resources that are required.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileDataDomain":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileDataDomain","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileDataDomain","url":"\/documentation\/mapboxcommon\/tiledatadomain","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Describes the tiles data domain."}],"title":"TileDataDomain","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TileDataDomain"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/CacheClearingError":{"kind":"symbol","url":"\/documentation\/mapboxcommon\/cacheclearingerror","role":"symbol","abstract":[{"type":"text","text":"Describes a cache clearing error."}],"title":"CacheClearingError","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CacheClearingError"}],"navigatorTitle":[{"kind":"identifier","text":"CacheClearingError"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingError","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateResult/init(errorMargin:transferSize:storageSize:extraData:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateResult\/init(errorMargin:transferSize:storageSize:extraData:)","type":"topic","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"errorMargin","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"text":"transferSize","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s6UInt64V","text":"UInt64","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"storageSize"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V","text":"UInt64"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"extraData"},{"text":": ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"abstract":[],"kind":"symbol","title":"init(errorMargin:transferSize:storageSize:extraData:)","navigatorTitle":[{"text":"initWithErrorMargin:transferSize:storageSize:extraData:","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/tileregionestimateresult\/init(errormargin:transfersize:storagesize:extradata:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegion":{"title":"TileRegion","role":"symbol","url":"\/documentation\/mapboxcommon\/tileregion","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TileRegion","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"TileRegion"}],"abstract":[{"text":"TileRegion represents an identifiable geographic tile region with metadata","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegion","type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateResult/storageSize":{"kind":"symbol","abstract":[{"type":"text","text":"Estimated number of bytes required to store the tile region on disk after the download"},{"type":"text","text":" "},{"text":"is complete.","type":"text"}],"role":"symbol","url":"\/documentation\/mapboxcommon\/tileregionestimateresult\/storagesize","title":"storageSize","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateResult\/storageSize","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"storageSize","kind":"identifier"},{"kind":"text","text":": "},{"text":"UInt64","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V"}],"navigatorTitle":[{"kind":"identifier","text":"storageSize"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudgetType":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetType","title":"TileCacheBudgetType","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileCacheBudgetType","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/tilecachebudgettype","type":"topic","abstract":[],"navigatorTitle":[{"text":"TileCacheBudgetType","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateResult/isEqual(to:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateResult\/isEqual(to:)","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isEqual"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"to"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBXTileRegionEstimateResult","kind":"typeIdentifier","text":"TileRegionEstimateResult"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[],"kind":"symbol","title":"isEqual(to:)","navigatorTitle":[{"kind":"identifier","text":"isEqualToTileRegionEstimateResult:"}],"url":"\/documentation\/mapboxcommon\/tileregionestimateresult\/isequal(to:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TilesetDescriptorOptions":{"navigatorTitle":[{"kind":"identifier","text":"TilesetDescriptorOptions"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TilesetDescriptorOptions","kind":"identifier"}],"type":"topic","title":"TilesetDescriptorOptions","kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/tilesetdescriptoroptions","abstract":[{"type":"text","text":"Describes the tileset descriptor option values."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TilesetDescriptorOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"title":"MapboxMaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateResult/transferSize":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateResult\/transferSize","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"transferSize"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s6UInt64V","text":"UInt64","kind":"typeIdentifier"}],"abstract":[{"text":"Estimated number of bytes that would have to be transferred from the network in order","type":"text"},{"type":"text","text":" "},{"type":"text","text":"to download the estimated tile region."}],"kind":"symbol","title":"transferSize","navigatorTitle":[{"text":"transferSize","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/tileregionestimateresult\/transfersize"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCoverOptions":{"title":"TileCoverOptions","url":"\/documentation\/mapboxmaps\/tilecoveroptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCoverOptions","role":"symbol","tags":[{"text":"SPI","type":"spi"}],"type":"topic","navigatorTitle":[{"text":"TileCoverOptions","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"TileCoverOptions","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Various options needed for tile cover."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStoreUsageMode":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreUsageMode","abstract":[{"text":"Describes tile store usage modes.","type":"text"}],"title":"TileStoreUsageMode","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TileStoreUsageMode"}],"url":"\/documentation\/mapboxmaps\/tilestoreusagemode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileStoreUsageMode"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudget":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TileCacheBudget"}],"navigatorTitle":[{"kind":"identifier","text":"TileCacheBudget"}],"type":"topic","title":"TileCacheBudget","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudget","url":"\/documentation\/mapboxmaps\/tilecachebudget","role":"symbol","kind":"symbol","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateProgressCallback":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"TileRegionEstimateProgressCallback"}],"role":"symbol","title":"TileRegionEstimateProgressCallback","abstract":[],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"TileRegionEstimateProgressCallback","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/tileregionestimateprogresscallback","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgressCallback"},"doc://com.mapbox.MapboxMaps/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","title":"Swift.CVarArg"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MBXTileRegionEstimateResult"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"kind":"identifier","text":"MBXTileRegionEstimateResult"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MBXTileRegionEstimateResult"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateResult\/errorMargin","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateResult\/extraData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateResult\/storageSize","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateResult\/transferSize"],"title":"Instance Properties","anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateResult\/init(errorMargin:transferSize:storageSize:extraData:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateResult\/isEqual(to:)"],"generated":true,"anchor":"Instance-Methods"}]},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"}],"op":"replace"},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"TileStore","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStoreOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudget","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInMegabytes","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInTiles","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegion","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgress","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TilesetDescriptor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TilesetDescriptorOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgressCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreUsageMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileDataDomain","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgress","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgressCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingErrorType"],"anchor":"TileStore","generated":true}]},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBXTileRegionEstimateResult","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}],"kind":"declarations"}},{"value":"MBXCacheClearingErrorType","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingErrorType\/title","op":"replace"},{"value":[{"text":"MBXCacheClearingErrorType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingErrorType\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingErrorType\/navigatorTitle","value":[{"kind":"identifier","text":"MBXCacheClearingErrorType"}],"op":"replace"},{"op":"replace","value":"MBXTileStoreOptions","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStoreOptions\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStoreOptions\/fragments","value":[{"kind":"identifier","text":"MBXTileStoreOptions"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStoreOptions\/navigatorTitle","value":[{"kind":"identifier","text":"MBXTileStoreOptions"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgressCallback\/title","value":"MBXTileRegionLoadProgressCallback","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgressCallback\/fragments","value":[{"text":"MBXTileRegionLoadProgressCallback","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"MBXTileRegionLoadProgressCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgressCallback\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateResult~1extraData\/title","value":"extraData"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateResult~1extraData\/fragments","value":[{"kind":"identifier","text":"extraData"}]},{"op":"replace","value":"MBMTileCacheBudgetInTiles","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInTiles\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInTiles\/fragments","value":[{"text":"MBMTileCacheBudgetInTiles","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"MBMTileCacheBudgetInTiles"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInTiles\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateResult~1errorMargin\/title","value":"errorMargin","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateResult~1errorMargin\/fragments","value":[{"text":"errorMargin","kind":"identifier"}],"op":"replace"},{"value":"MBMCanonicalTileID","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/fragments","value":[{"kind":"identifier","text":"MBMCanonicalTileID"}],"op":"replace"},{"value":[{"kind":"identifier","text":"MBMCanonicalTileID"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgress\/title","op":"replace","value":"MBXTileRegionEstimateProgress"},{"value":[{"kind":"identifier","text":"MBXTileRegionEstimateProgress"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgress\/fragments"},{"value":[{"text":"MBXTileRegionEstimateProgress","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgress\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateResult\/title","value":"MBXTileRegionEstimateResult"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateResult\/fragments","value":[{"text":"MBXTileRegionEstimateResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateResult\/navigatorTitle","value":[{"kind":"identifier","text":"MBXTileRegionEstimateResult"}]},{"op":"replace","value":"MBXTileRegionLoadOptions","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/fragments","value":[{"text":"MBXTileRegionLoadOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/navigatorTitle","value":[{"text":"MBXTileRegionLoadOptions","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/title","value":"MBXTileStore","op":"replace"},{"value":[{"text":"MBXTileStore","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/navigatorTitle","value":[{"kind":"identifier","text":"MBXTileStore"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateOptions\/title","value":"MBXTileRegionEstimateOptions"},{"op":"replace","value":[{"text":"MBXTileRegionEstimateOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateOptions\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateOptions\/navigatorTitle","value":[{"text":"MBXTileRegionEstimateOptions","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TilesetDescriptor\/title","value":"MBXTilesetDescriptor"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TilesetDescriptor\/fragments","value":[{"text":"MBXTilesetDescriptor","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TilesetDescriptor\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBXTilesetDescriptor"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInMegabytes\/title","value":"MBMTileCacheBudgetInMegabytes","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBMTileCacheBudgetInMegabytes"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInMegabytes\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInMegabytes\/navigatorTitle","value":[{"kind":"identifier","text":"MBMTileCacheBudgetInMegabytes"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileOptions\/title","value":"MBMTileOptions","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileOptions\/fragments","value":[{"text":"MBMTileOptions","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileOptions\/navigatorTitle","value":[{"text":"MBMTileOptions","kind":"identifier"}]},{"value":"MBXTileRegionLoadProgress","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgress\/title"},{"value":[{"text":"MBXTileRegionLoadProgress","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgress\/fragments","op":"replace"},{"value":[{"text":"MBXTileRegionLoadProgress","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgress\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileDataDomain\/title","value":"MBXTileDataDomain"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileDataDomain\/fragments","value":[{"text":"MBXTileDataDomain","kind":"identifier"}]},{"value":[{"text":"MBXTileDataDomain","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileDataDomain\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingError\/title","value":"MBXCacheClearingError","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBXCacheClearingError"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingError\/fragments"},{"value":[{"kind":"identifier","text":"MBXCacheClearingError"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingError\/navigatorTitle","op":"replace"},{"value":"initWithErrorMargin:transferSize:storageSize:extraData:","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateResult~1init(errorMargin:transferSize:storageSize:extraData:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateResult~1init(errorMargin:transferSize:storageSize:extraData:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithErrorMargin:transferSize:storageSize:extraData:"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegion\/title","value":"MBXTileRegion","op":"replace"},{"value":[{"kind":"identifier","text":"MBXTileRegion"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegion\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegion\/navigatorTitle","value":[{"kind":"identifier","text":"MBXTileRegion"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateResult~1storageSize\/title","op":"replace","value":"storageSize"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateResult~1storageSize\/fragments","op":"replace","value":[{"text":"storageSize","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetType\/title","value":"MBMTileCacheBudgetType","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetType\/fragments","value":[{"text":"MBMTileCacheBudgetType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMTileCacheBudgetType"}]},{"value":"isEqualToTileRegionEstimateResult:","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateResult~1isEqual(to:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqualToTileRegionEstimateResult:"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateResult~1isEqual(to:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions\/title","value":"MBMTilesetDescriptorOptions"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMTilesetDescriptorOptions"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMTilesetDescriptorOptions"}]},{"op":"replace","value":"transferSize","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateResult~1transferSize\/title"},{"value":[{"kind":"identifier","text":"transferSize"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateResult~1transferSize\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileStoreUsageMode\/title","value":"MBMTileStoreUsageMode"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileStoreUsageMode\/fragments","value":[{"kind":"identifier","text":"MBMTileStoreUsageMode"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileStoreUsageMode\/navigatorTitle","value":[{"kind":"identifier","text":"MBMTileStoreUsageMode"}]},{"value":"MBMTileCacheBudget","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudget\/title","op":"replace"},{"value":[{"text":"MBMTileCacheBudget","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudget\/fragments"},{"value":[{"kind":"identifier","text":"MBMTileCacheBudget"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudget\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgressCallback\/title","value":"MBXTileRegionEstimateProgressCallback"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgressCallback\/fragments","value":[{"kind":"identifier","text":"MBXTileRegionEstimateProgressCallback"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgressCallback\/navigatorTitle","value":[{"kind":"identifier","text":"MBXTileRegionEstimateProgressCallback"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}