{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/tilestore\/estimatetileregion(forid:loadoptions:estimateoptions:progress:completion:)"]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore\/estimateTileRegion(forId:loadOptions:estimateOptions:progress:completion:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","abstract":[{"type":"text","text":"Estimates the storage and transfer size of a tile region."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@discardableResult"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"estimateTileRegion"},{"kind":"text","text":"("},{"text":"forId","kind":"externalParam"},{"kind":"text","text":" "},{"text":"id","kind":"internalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"loadOptions"},{"text":": ","kind":"text"},{"text":"TileRegionLoadOptions","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions","preciseIdentifier":"c:objc(cs)MBXTileRegionLoadOptions"},{"kind":"text","text":", "},{"text":"estimateOptions","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MBXTileRegionEstimateOptions","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateOptions","text":"TileRegionEstimateOptions"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"progress"},{"text":": ","kind":"text"},{"kind":"keyword","text":"@escaping"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgressCallback","text":"TileRegionEstimateProgressCallback","preciseIdentifier":"c:MBXTileRegionEstimateProgressCallback.h@T@MBXTileRegionEstimateProgressCallback"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"text":"@escaping","kind":"keyword"},{"kind":"text","text":" ("},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)MBXTileRegionEstimateResult","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateResult","text":"TileRegionEstimateResult","kind":"typeIdentifier"},{"text":", any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":">) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> any "},{"text":"Cancelable","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Cancelable","preciseIdentifier":"c:objc(pl)MBXCancelable"}]}]},{"kind":"content","content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"inlineContent":[{"type":"text","text":"A "},{"code":"Cancelable","type":"codeVoice"},{"type":"text","text":" object to cancel the estimate request"}],"type":"paragraph"}]},{"kind":"content","content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"id The tile region identifier."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"loadOptions The tile region load options."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"estimateOptions The options for the estimate operation. Optional, default values will be aplied if nil."}]}]},{"content":[{"inlineContent":[{"text":"onProgress Invoked multiple times to report progess of the estimate operation.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"onFinished Invoked only once upon success, failure, or cancelation of the estimate operation."}],"type":"paragraph"}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"This can be used for estimating existing or new tile regions. For new tile"},{"text":" ","type":"text"},{"text":"regions, both geometry and tileset descriptors need to be provided to the","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"given load options.  If a tile region with the given id already exists, its"},{"text":" ","type":"text"},{"type":"text","text":"geometry and tileset descriptors are reused unless a different value is"},{"type":"text","text":" "},{"text":"provided in the region load options.","type":"text"}]},{"inlineContent":[{"type":"text","text":"Estimating a tile region does not mutate exising tile regions on the tile store."}],"type":"paragraph"}]}],"sections":[],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"estimateTileRegion"},{"text":"(","kind":"text"},{"text":"forId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"loadOptions","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TileRegionLoadOptions","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXTileRegionLoadOptions"},{"kind":"text","text":", "},{"text":"estimateOptions","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TileRegionEstimateOptions","preciseIdentifier":"c:objc(cs)MBXTileRegionEstimateOptions"},{"kind":"text","text":"?, "},{"text":"progress","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:MBXTileRegionEstimateProgressCallback.h@T@MBXTileRegionEstimateProgressCallback","kind":"typeIdentifier","text":"TileRegionEstimateProgressCallback"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"Result","preciseIdentifier":"s:s6ResultO","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXTileRegionEstimateResult","text":"TileRegionEstimateResult"},{"text":", any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":") -> any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)MBXCancelable","text":"Cancelable","kind":"typeIdentifier"}],"role":"symbol","roleHeading":"Instance Method","extendedModule":"MapboxCommon","title":"estimateTileRegion(forId:loadOptions:estimateOptions:progress:completion:)","externalID":"s:So12MBXTileStoreC10MapboxMapsE18estimateTileRegion5forId11loadOptions0eK08progress10completionSo13MBXCancelable_pSS_So0ag4LoadK0CSo0ag8EstimateK0CSgySo0agP8ProgressCcys6ResultOySo0agpR0Cs5Error_pGctF","symbolKind":"method","modules":[{"name":"MapboxCommon"}]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateOptions":{"kind":"symbol","url":"\/documentation\/mapboxcommon\/tileregionestimateoptions","role":"symbol","abstract":[{"text":"Holds options for the tile region estimation operation.","type":"text"}],"title":"TileRegionEstimateOptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateOptions","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TileRegionEstimateOptions","kind":"identifier"}],"navigatorTitle":[{"text":"TileRegionEstimateOptions","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateProgressCallback":{"abstract":[],"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"TileRegionEstimateProgressCallback","kind":"identifier"}],"title":"TileRegionEstimateProgressCallback","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TileRegionEstimateProgressCallback"}],"url":"\/documentation\/mapboxcommon\/tileregionestimateprogresscallback","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgressCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileStore":{"title":"TileStore","navigatorTitle":[{"kind":"identifier","text":"TileStore"}],"kind":"symbol","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TileStore","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/tilestore","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore","abstract":[{"type":"text","text":"TileStore manages downloads and storage for requests to tile-related API endpoints, enforcing a disk usage"},{"text":" ","type":"text"},{"type":"text","text":"quota: tiles available on disk may be deleted to make room for a new download. This interface can be used by an"},{"text":" ","type":"text"},{"text":"app developer to set the disk quota. The rest of TileStore API is intended for native SDK consumption only.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"kind":"article","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/tilestore-apis","type":"topic","title":"TileStore APIs"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","title":"MapboxMaps Documentation","kind":"article","url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileStore/estimateTileRegion(forId:loadOptions:estimateOptions:progress:completion:)":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore\/estimateTileRegion(forId:loadOptions:estimateOptions:progress:completion:)","kind":"symbol","abstract":[{"text":"Estimates the storage and transfer size of a tile region.","type":"text"}],"title":"estimateTileRegion(forId:loadOptions:estimateOptions:progress:completion:)","url":"\/documentation\/mapboxcommon\/tilestore\/estimatetileregion(forid:loadoptions:estimateoptions:progress:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"estimateTileRegion"},{"text":"(","kind":"text"},{"text":"forId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"loadOptions","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TileRegionLoadOptions","preciseIdentifier":"c:objc(cs)MBXTileRegionLoadOptions","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"estimateOptions","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TileRegionEstimateOptions","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXTileRegionEstimateOptions"},{"kind":"text","text":"?, "},{"text":"progress","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:MBXTileRegionEstimateProgressCallback.h@T@MBXTileRegionEstimateProgressCallback","text":"TileRegionEstimateProgressCallback","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)MBXTileRegionEstimateResult","text":"TileRegionEstimateResult","kind":"typeIdentifier"},{"text":", any ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MBXCancelable","text":"Cancelable"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Cancelable":{"abstract":[{"type":"text","text":"Allows to cancel the associated asynchronous operation"}],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Cancelable"}],"title":"Cancelable","navigatorTitle":[{"text":"Cancelable","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Cancelable","url":"\/documentation\/mapboxcommon\/cancelable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","title":"MapboxMaps","kind":"symbol","url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateResult":{"kind":"symbol","url":"\/documentation\/mapboxcommon\/tileregionestimateresult","role":"symbol","abstract":[{"text":"The result of tile region estim","type":"text"}],"title":"TileRegionEstimateResult","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateResult","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileRegionEstimateResult"}],"navigatorTitle":[{"text":"TileRegionEstimateResult","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadOptions":{"abstract":[{"type":"text","text":"Describes the tile region load option values."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TileRegionLoadOptions"}],"title":"TileRegionLoadOptions","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TileRegionLoadOptions"}],"url":"\/documentation\/mapboxcommon\/tileregionloadoptions","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateOptions\/title","value":"MBXTileRegionEstimateOptions","op":"replace"},{"op":"replace","value":[{"text":"MBXTileRegionEstimateOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateOptions\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateOptions\/navigatorTitle","value":[{"text":"MBXTileRegionEstimateOptions","kind":"identifier"}]},{"op":"replace","value":"MBXTileRegionEstimateProgressCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgressCallback\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgressCallback\/fragments","value":[{"text":"MBXTileRegionEstimateProgressCallback","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgressCallback\/navigatorTitle","value":[{"kind":"identifier","text":"MBXTileRegionEstimateProgressCallback"}],"op":"replace"},{"op":"replace","value":"MBXTileStore","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/title"},{"op":"replace","value":[{"text":"MBXTileStore","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/navigatorTitle","value":[{"text":"MBXTileStore","kind":"identifier"}],"op":"replace"},{"value":"MBXCancelable","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/title"},{"value":[{"text":"MBXCancelable","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/fragments"},{"value":[{"text":"MBXCancelable","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateResult\/title","op":"replace","value":"MBXTileRegionEstimateResult"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateResult\/fragments","op":"replace","value":[{"text":"MBXTileRegionEstimateResult","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"MBXTileRegionEstimateResult"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateResult\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/title","op":"replace","value":"MBXTileRegionLoadOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/fragments","value":[{"kind":"identifier","text":"MBXTileRegionLoadOptions"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/navigatorTitle","value":[{"text":"MBXTileRegionLoadOptions","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}