{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SdkInformationQuery"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/sdkinformationquery\/getsdkinformation()"]},{"paths":["\/documentation\/mapboxcommon\/sdkinformationquery\/getsdkinformation()"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"getSdkInformation()","role":"symbol","modules":[{"name":"MapboxCommon"}],"roleHeading":"Type Method","symbolKind":"method","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getSdkInformation"},{"text":"() -> [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXSdkInformation","text":"SdkInformation"},{"kind":"text","text":"]"}],"navigatorTitle":[{"text":"getSdkInformation","kind":"identifier"}],"externalID":"c:objc(cs)MBXSdkInformationQuery(cm)getSdkInformation"},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SdkInformationQuery\/getSdkInformation()"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getSdkInformation","kind":"identifier"},{"text":"() -> [","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SdkInformation","text":"SdkInformation","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXSdkInformation"},{"text":"]","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"List of SDK information.","type":"text"}]}],"kind":"content"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SdkInformationQuery":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SdkInformationQuery","abstract":[{"type":"text","text":"Provides an interface to query registered Mapbox SDKs. Mapbox SDKs include Maps, Navigation, Search, and others."}],"kind":"symbol","type":"topic","url":"\/documentation\/mapboxcommon\/sdkinformationquery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SdkInformationQuery"}],"navigatorTitle":[{"text":"SdkInformationQuery","kind":"identifier"}],"title":"SdkInformationQuery"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","abstract":[],"type":"topic","kind":"article","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SdkInformationQuery/getSdkInformation()":{"abstract":[],"role":"symbol","title":"getSdkInformation()","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"getSdkInformation","kind":"identifier"},{"text":"() -> [","kind":"text"},{"text":"SdkInformation","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXSdkInformation"},{"text":"]","kind":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"getSdkInformation"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SdkInformationQuery\/getSdkInformation()","url":"\/documentation\/mapboxcommon\/sdkinformationquery\/getsdkinformation()"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","title":"MapboxCommon","type":"topic","url":"\/documentation\/mapboxcommon","abstract":[],"kind":"symbol","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SdkInformation":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SdkInformation","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SdkInformation"}],"type":"topic","kind":"symbol","url":"\/documentation\/mapboxcommon\/sdkinformation","navigatorTitle":[{"text":"SdkInformation","kind":"identifier"}],"abstract":[{"type":"text","text":"Provides information about a given Mapbox SDK. This information is then used to populate the “User-Agent” HTTP header"},{"text":" ","type":"text"},{"text":"of HTTP requests generated from within Mapbox SDKs. Mapbox SDKs include Maps, Navigation, Search, and others.","type":"text"}],"title":"SdkInformation","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"getSdkInformation","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getSdkInformation"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<MBXSdkInformation *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"getSdkInformation","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"kind":"content","content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"inlineContent":[{"text":"List of SDK information.","type":"text"}],"type":"paragraph"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"MBXSdkInformationQuery","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SdkInformationQuery\/title"},{"value":[{"kind":"identifier","text":"MBXSdkInformationQuery"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SdkInformationQuery\/fragments"},{"value":[{"kind":"identifier","text":"MBXSdkInformationQuery"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SdkInformationQuery\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SdkInformationQuery~1getSdkInformation()\/title","value":"getSdkInformation"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SdkInformationQuery~1getSdkInformation()\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"getSdkInformation","kind":"identifier"}]},{"value":"MBXSdkInformation","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SdkInformation\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SdkInformation\/fragments","value":[{"kind":"identifier","text":"MBXSdkInformation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SdkInformation\/navigatorTitle","value":[{"kind":"identifier","text":"MBXSdkInformation"}]}]}]}