{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/mbxlocation\/extra"]},{"paths":["\/documentation\/mapboxcommon\/mbxlocation\/extra"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"property","externalID":"c:objc(cs)MBXLocation(py)extra","modules":[{"name":"MapboxCommon"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"extra"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?"}],"title":"extra","role":"symbol","navigatorTitle":[{"text":"extra","kind":"identifier"}],"roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXLocation\/extra","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"extra"},{"kind":"text","text":": "},{"text":"Any","kind":"keyword"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"Additional information"}],"kind":"symbol","sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Location":{"url":"\/documentation\/mapboxcommon\/location","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Location"}],"navigatorTitle":[{"kind":"identifier","text":"Location"}],"type":"topic","role":"symbol","title":"Location","abstract":[{"type":"text","text":"Location information."}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXLocation/extra":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"extra","kind":"identifier"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"extra"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXLocation\/extra","type":"topic","title":"extra","abstract":[{"type":"text","text":"Additional information"}],"role":"symbol","kind":"symbol","url":"\/documentation\/mapboxcommon\/mbxlocation\/extra"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Location-APIs":{"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","role":"collectionGroup","title":"Location","url":"\/documentation\/mapboxmaps\/location-apis","type":"topic","kind":"article"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"extra","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"extra","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"id"},{"text":" ","kind":"text"},{"text":"extra","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/title","value":"MBXLocation"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/fragments","value":[{"kind":"identifier","text":"MBXLocation"}],"op":"replace"},{"value":"extra","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MBXLocation~1extra\/title"},{"op":"replace","value":[{"kind":"identifier","text":"extra"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MBXLocation~1extra\/fragments"}]}]}