{"metadata":{"externalID":"c:objc(cs)MBMFreeCameraOptions(im)setLocationForLocation:altitude:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLocationForLocation"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","kind":"typeIdentifier","text":"CLLocationCoordinate2D"},{"text":", ","kind":"text"},{"text":"altitude","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":")","kind":"text"}],"role":"symbol","modules":[{"name":"MapboxMaps"}],"roleHeading":"Instance Method","title":"setLocationForLocation(_:altitude:)","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"setLocationForLocation:altitude:"}]},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions\/setLocationForLocation(_:altitude:)","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"Helper function for setting the mercator position as Lat&Lng and altitude in meters."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setLocationForLocation","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"location","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"text":", ","kind":"text"},{"text":"altitude","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"location","content":[{"inlineContent":[{"text":"The mercator ","type":"text"},{"code":"coordinate","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}]},{"name":"altitude","content":[{"type":"paragraph","inlineContent":[{"text":"The altitude in meters.","type":"text"}]}]}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions"]]},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/mapboxmaps\/freecameraoptions\/setlocationforlocation(_:altitude:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/freecameraoptions\/setlocationforlocation(_:altitude:)"]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"type":"topic","role":"collection","url":"\/documentation\/mapboxmaps","title":"MapboxMaps","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FreeCameraOptions/setLocationForLocation(_:altitude:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setLocationForLocation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"altitude"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"setLocationForLocation:altitude:"}],"kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/freecameraoptions\/setlocationforlocation(_:altitude:)","role":"symbol","title":"setLocationForLocation(_:altitude:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions\/setLocationForLocation(_:altitude:)","abstract":[{"text":"Helper function for setting the mercator position as Lat&Lng and altitude in meters.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FreeCameraOptions":{"kind":"symbol","title":"FreeCameraOptions","type":"topic","navigatorTitle":[{"text":"FreeCameraOptions","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/freecameraoptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FreeCameraOptions"}],"abstract":[{"type":"text","text":"Various options for accessing physical properties of the underlying camera entity."},{"text":" ","type":"text"},{"type":"text","text":"A direct access to these properties allows more flexible and precise controlling"},{"type":"text","text":" "},{"text":"of the camera while also being fully compatible and interchangeable with CameraOptions.","type":"text"},{"text":" ","type":"text"},{"text":"All fields are optional.","type":"text"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"title":"MapboxMap","abstract":[],"type":"topic","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","url":"\/documentation\/mapboxmaps\/mapboxmap-apis","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","role":"collection","kind":"article","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"setLocationForLocation:altitude:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"setLocationForLocation:altitude:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"setLocationForLocation:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"location"},{"text":" ","kind":"text"},{"kind":"identifier","text":"altitude:"},{"text":"(","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"altitude","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"kind":"parameters","parameters":[{"name":"location","content":[{"inlineContent":[{"type":"text","text":"The mercator "},{"type":"codeVoice","code":"coordinate"},{"type":"text","text":"."}],"type":"paragraph"}]},{"name":"altitude","content":[{"inlineContent":[{"type":"text","text":"The altitude in meters."}],"type":"paragraph"}]}]},"path":"\/primaryContentSections\/1","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions~1setLocationForLocation(_:altitude:)\/title","value":"setLocationForLocation:altitude:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions~1setLocationForLocation(_:altitude:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"setLocationForLocation:altitude:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions\/title","op":"replace","value":"MBMFreeCameraOptions"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions\/fragments","op":"replace","value":[{"text":"MBMFreeCameraOptions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions\/navigatorTitle","value":[{"kind":"identifier","text":"MBMFreeCameraOptions"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}