{"abstract":[{"type":"text","text":"Helper function for setting the orientation of the camera as a pitch and a bearing."}],"variants":[{"paths":["\/documentation\/mapboxmaps\/freecameraoptions\/setpitchbearingforpitch(_:bearing:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/freecameraoptions\/setpitchbearingforpitch(_:bearing:)"]}],"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions\/setPitchBearingForPitch(_:bearing:)"},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setPitchBearingForPitch","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"bearing"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"symbolKind":"method","role":"symbol","modules":[{"name":"MapboxMaps"}],"externalID":"c:objc(cs)MBMFreeCameraOptions(im)setPitchBearingForPitch:bearing:","roleHeading":"Instance Method","title":"setPitchBearingForPitch(_:bearing:)","navigatorTitle":[{"kind":"identifier","text":"setPitchBearingForPitch:bearing:"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPitchBearingForPitch"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"pitch","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":", ","kind":"text"},{"text":"bearing","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}]}]},{"parameters":[{"name":"pitch","content":[{"inlineContent":[{"text":"The pitch in degrees","type":"text"}],"type":"paragraph"}]},{"name":"bearing","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The bearing in degrees"}]}]}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"abstract":[],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","role":"collectionGroup","title":"MapboxMap","url":"\/documentation\/mapboxmaps\/mapboxmap-apis","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FreeCameraOptions/setPitchBearingForPitch(_:bearing:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setPitchBearingForPitch"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"bearing","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions\/setPitchBearingForPitch(_:bearing:)","type":"topic","abstract":[{"type":"text","text":"Helper function for setting the orientation of the camera as a pitch and a bearing."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"setPitchBearingForPitch:bearing:","kind":"identifier"}],"title":"setPitchBearingForPitch(_:bearing:)","url":"\/documentation\/mapboxmaps\/freecameraoptions\/setpitchbearingforpitch(_:bearing:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FreeCameraOptions":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FreeCameraOptions","kind":"identifier"}],"title":"FreeCameraOptions","role":"symbol","navigatorTitle":[{"text":"FreeCameraOptions","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/freecameraoptions","type":"topic","abstract":[{"text":"Various options for accessing physical properties of the underlying camera entity.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"A direct access to these properties allows more flexible and precise controlling"},{"text":" ","type":"text"},{"type":"text","text":"of the camera while also being fully compatible and interchangeable with CameraOptions."},{"text":" ","type":"text"},{"type":"text","text":"All fields are optional."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","abstract":[],"kind":"article","role":"collection","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/mapboxmaps","title":"MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"setPitchBearingForPitch:bearing:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setPitchBearingForPitch:bearing:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"setPitchBearingForPitch:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"pitch","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"bearing:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:d","kind":"typeIdentifier","text":"double"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"bearing"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"name":"pitch","content":[{"type":"paragraph","inlineContent":[{"text":"The pitch in degrees","type":"text"}]}]},{"name":"bearing","content":[{"inlineContent":[{"text":"The bearing in degrees","type":"text"}],"type":"paragraph"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions~1setPitchBearingForPitch(_:bearing:)\/title","value":"setPitchBearingForPitch:bearing:"},{"value":[{"text":"- ","kind":"text"},{"text":"setPitchBearingForPitch:bearing:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions~1setPitchBearingForPitch(_:bearing:)\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions\/title","value":"MBMFreeCameraOptions","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions\/fragments","value":[{"kind":"identifier","text":"MBMFreeCameraOptions"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions\/navigatorTitle","value":[{"text":"MBMFreeCameraOptions","kind":"identifier"}]}]}]}