{"metadata":{"roleHeading":"Enumeration","title":"AccuracyLevel","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AccuracyLevel"}],"navigatorTitle":[{"kind":"identifier","text":"AccuracyLevel"}],"role":"symbol","externalID":"c:@E@MBXAccuracyLevel","symbolKind":"enum","modules":[{"name":"MapboxCommon"}]},"seeAlsoSections":[{"anchor":"Location","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationManager","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck2DConfiguration","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Model","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckBearing","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProviderDelegate","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Coordinate2D","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationExtraKeys","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProviderRequest","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceFactory","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/DeviceLocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Heading","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckRenderingData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/IntervalSettings"],"generated":true,"title":"Location"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs"]]},"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/s15BitwiseCopyableP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH","doc:\/\/com.mapbox.MapboxMaps\/SY","doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"],"type":"conformsTo","kind":"relationships"}],"variants":[{"paths":["\/documentation\/mapboxcommon\/accuracylevel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxcommon\/accuracylevel"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"The accuracy of the observed location","type":"text"}],"topicSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel\/high","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel\/highest","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel\/low","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel\/medium","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel\/passive"],"generated":true,"title":"Enumeration Cases","anchor":"Enumeration-Cases"},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel\/init(rawValue:)"],"anchor":"Initializers","title":"Initializers","generated":true},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel\/Equatable-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel\/RawRepresentable-Implementations"],"generated":true,"anchor":"Default-Implementations","title":"Default Implementations"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"AccuracyLevel","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/AccuracyLevel/passive":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"MBXAccuracyLevelPassive"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel\/passive","title":"AccuracyLevel.passive","url":"\/documentation\/mapboxcommon\/accuracylevel\/passive","abstract":[{"type":"text","text":"Passive only accuracy request, not triggers any active locations or power usage itself,"},{"text":" ","type":"text"},{"text":"but may receive locations generated in response to other requests.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"passive"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/AccuracyLevel/highest":{"role":"symbol","title":"AccuracyLevel.highest","abstract":[{"type":"text","text":"The highest possible accuracy requirement that uses additional"},{"text":" ","type":"text"},{"text":"sensors (if possible) to facilitate navigation use case.","type":"text"}],"url":"\/documentation\/mapboxcommon\/accuracylevel\/highest","navigatorTitle":[{"text":"MBXAccuracyLevelHighest","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel\/highest","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"highest","kind":"identifier"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationError":{"role":"symbol","title":"LocationError","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationError","kind":"symbol","type":"topic","navigatorTitle":[{"text":"LocationError","kind":"identifier"}],"abstract":[{"type":"text","text":"Error code with brief explanation."}],"url":"\/documentation\/mapboxcommon\/locationerror","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"LocationError","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PermissionStatus":{"abstract":[{"type":"text","text":"Location permissions granted by user to the app."}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PermissionStatus","kind":"identifier"}],"title":"PermissionStatus","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus","url":"\/documentation\/mapboxcommon\/permissionstatus","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PermissionStatus"}]},"doc://com.mapbox.MapboxMaps/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Model":{"role":"symbol","type":"topic","navigatorTitle":[{"text":"Model","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"Model","kind":"identifier"}],"title":"Model","url":"\/documentation\/mapboxmaps\/model","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Model","kind":"symbol","abstract":[{"type":"text","text":"A structure represeting a Model"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PuckRenderingData":{"abstract":[{"type":"text","text":"Represents the interpolated data ready to render the user location puck."}],"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"PuckRenderingData"}],"title":"PuckRenderingData","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckRenderingData","url":"\/documentation\/mapboxmaps\/puckrenderingdata","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"PuckRenderingData","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Puck3DConfiguration":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration","abstract":[],"role":"symbol","navigatorTitle":[{"text":"Puck3DConfiguration","kind":"identifier"}],"kind":"symbol","title":"Puck3DConfiguration","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Puck3DConfiguration","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/puck3dconfiguration"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationObserver":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationObserver","abstract":[{"type":"text","text":"Observer for getting updates from a LocationProvider."}],"role":"symbol","navigatorTitle":[{"text":"LocationObserver","kind":"identifier"}],"kind":"symbol","title":"LocationObserver","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"LocationObserver","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/locationobserver"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PuckType":{"title":"PuckType","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PuckType"}],"type":"topic","navigatorTitle":[{"text":"PuckType","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/pucktype","abstract":[{"text":"Represents the different types of pucks","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckType"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Puck2DConfiguration":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Puck2DConfiguration","kind":"identifier"}],"kind":"symbol","title":"Puck2DConfiguration","abstract":[],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck2DConfiguration","url":"\/documentation\/mapboxmaps\/puck2dconfiguration","role":"symbol","navigatorTitle":[{"text":"Puck2DConfiguration","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeadingProvider":{"title":"HeadingProvider","kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"HeadingProvider","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"HeadingProvider"}],"url":"\/documentation\/mapboxmaps\/headingprovider","abstract":[{"type":"text","text":"Provides heading data to drive the location puck."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingProvider"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AppleLocationProviderDelegate":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProviderDelegate","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProviderDelegate","isActive":true,"type":"reference"},{"type":"text","text":" protocol defines a set of optional methods that you"},{"text":" ","type":"text"},{"type":"text","text":"can use to receive events from an associated location provider object."}],"url":"\/documentation\/mapboxmaps\/applelocationproviderdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AppleLocationProviderDelegate"}],"title":"AppleLocationProviderDelegate","navigatorTitle":[{"text":"AppleLocationProviderDelegate","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationServiceFactory":{"role":"symbol","title":"LocationServiceFactory","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceFactory","kind":"symbol","type":"topic","navigatorTitle":[{"text":"LocationServiceFactory","kind":"identifier"}],"abstract":[{"type":"text","text":"Location service factory."}],"url":"\/documentation\/mapboxcommon\/locationservicefactory","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LocationServiceFactory"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LocationOptions":{"role":"symbol","title":"LocationOptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationOptions","kind":"symbol","type":"topic","navigatorTitle":[{"text":"LocationOptions","kind":"identifier"}],"abstract":[{"text":"A struct to configure a ","type":"text"},{"code":"LocationManager","type":"codeVoice"}],"url":"\/documentation\/mapboxmaps\/locationoptions","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"LocationOptions","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","url":"\/documentation\/overview","abstract":[],"type":"topic","role":"collection","title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/AccuracyLevel/Equatable-Implementations":{"role":"collectionGroup","abstract":[],"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel\/Equatable-Implementations","title":"Equatable Implementations","type":"topic","url":"\/documentation\/mapboxcommon\/accuracylevel\/equatable-implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationProviderRequest":{"role":"symbol","kind":"symbol","url":"\/documentation\/mapboxcommon\/locationproviderrequest","abstract":[{"text":"Data model that contains parameters for location requests.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProviderRequest","title":"LocationProviderRequest","navigatorTitle":[{"kind":"identifier","text":"LocationProviderRequest"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationProviderRequest"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PuckBearing":{"kind":"symbol","title":"PuckBearing","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PuckBearing","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PuckBearing"}],"url":"\/documentation\/mapboxmaps\/puckbearing","abstract":[{"type":"text","text":"Controls how the puck is oriented"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckBearing"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationErrorCode":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"LocationErrorCode","kind":"identifier"}],"title":"LocationErrorCode","url":"\/documentation\/mapboxcommon\/locationerrorcode","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode","abstract":[{"type":"text","text":"Codes of location errors."}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"LocationErrorCode","kind":"identifier"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/AccuracyLevel/medium":{"abstract":[{"type":"text","text":"Medium accuracy requirement (typically between 100 and 500 meters)."}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"medium","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"MBXAccuracyLevelMedium","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel\/medium","title":"AccuracyLevel.medium","url":"\/documentation\/mapboxcommon\/accuracylevel\/medium"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/AccuracyLevel/init(rawValue:)":{"type":"topic","title":"init(rawValue:)","url":"\/documentation\/mapboxcommon\/accuracylevel\/init(rawvalue:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel\/init(rawValue:)","role":"symbol","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}],"abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/IntervalSettings":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/IntervalSettings","abstract":[{"text":"The interval for active location updates","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"IntervalSettings","kind":"identifier"}],"kind":"symbol","title":"IntervalSettings","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"IntervalSettings","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/intervalsettings"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/AccuracyLevel/RawRepresentable-Implementations":{"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel\/RawRepresentable-Implementations","type":"topic","title":"RawRepresentable Implementations","url":"\/documentation\/mapboxcommon\/accuracylevel\/rawrepresentable-implementations","role":"collectionGroup","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Heading":{"navigatorTitle":[{"kind":"identifier","text":"Heading"}],"abstract":[{"type":"text","text":"The azimuth (orientation) of the user’s device, relative to true or magnetic north."}],"url":"\/documentation\/mapboxmaps\/heading","role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Heading","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Heading","kind":"identifier"}],"title":"Heading"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationProvider":{"title":"LocationProvider","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider","kind":"symbol","type":"topic","url":"\/documentation\/mapboxcommon\/locationprovider","abstract":[{"type":"text","text":"Location provider that provides locations"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LocationProvider"}],"navigatorTitle":[{"kind":"identifier","text":"LocationProvider"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationServiceObserver":{"title":"LocationServiceObserver","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"LocationServiceObserver","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocationServiceObserver"}],"url":"\/documentation\/mapboxcommon\/locationserviceobserver","abstract":[{"type":"text","text":"Observers for getting updates from LocationService."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver"},"doc://com.mapbox.MapboxMaps/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Location":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Location"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Location","kind":"identifier"}],"title":"Location","abstract":[{"type":"text","text":"Location information."}],"url":"\/documentation\/mapboxcommon\/location","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Location-APIs":{"abstract":[],"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/location-apis","title":"Location","type":"topic"},"doc://com.mapbox.MapboxMaps/s15BitwiseCopyableP":{"title":"Swift.BitwiseCopyable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s15BitwiseCopyableP","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/AccuracyAuthorization":{"title":"AccuracyAuthorization","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AccuracyAuthorization","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"AccuracyAuthorization"}],"url":"\/documentation\/mapboxcommon\/accuracyauthorization","abstract":[{"type":"text","text":"Accuracy authorization granted by user to the app."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/AccuracyLevel/high":{"type":"topic","url":"\/documentation\/mapboxcommon\/accuracylevel\/high","title":"AccuracyLevel.high","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel\/high","abstract":[{"text":"High accuracy requirement.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MBXAccuracyLevelHigh"}],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"high","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SY","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/AccuracyLevel/low":{"abstract":[{"type":"text","text":"Low accuracy requirement (typically greater than 500 meters)."}],"type":"topic","url":"\/documentation\/mapboxcommon\/accuracylevel\/low","role":"symbol","navigatorTitle":[{"text":"MBXAccuracyLevelLow","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel\/low","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"low"}],"title":"AccuracyLevel.low"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Coordinate2D":{"type":"topic","abstract":[{"type":"text","text":"Boxed version of CLLocationCoordinate2D"}],"navigatorTitle":[{"text":"Coordinate2D","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Coordinate2D","title":"Coordinate2D","role":"symbol","url":"\/documentation\/mapboxcommon\/coordinate2d","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Coordinate2D","kind":"identifier"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationExtraKeys":{"role":"symbol","title":"LocationExtraKeys","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationExtraKeys","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocationExtraKeys"}],"abstract":[{"type":"text","text":"Keys for additional information (extra) in Location."}],"url":"\/documentation\/mapboxcommon\/locationextrakeys","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LocationExtraKeys"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/AccuracyLevel":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel","abstract":[{"text":"The accuracy of the observed location","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"AccuracyLevel","kind":"identifier"}],"kind":"symbol","title":"AccuracyLevel","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AccuracyLevel"}],"url":"\/documentation\/mapboxcommon\/accuracylevel"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeadingObserver":{"title":"HeadingObserver","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HeadingObserver"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"HeadingObserver"}],"url":"\/documentation\/mapboxmaps\/headingobserver","abstract":[{"text":"Listens to ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingProvider","type":"reference"},{"type":"text","text":"’s updates."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingObserver"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AppleLocationProvider":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProvider","title":"AppleLocationProvider","kind":"symbol","url":"\/documentation\/mapboxmaps\/applelocationprovider","abstract":[{"type":"text","text":"A location provider based on CoreLocation’s "},{"code":"CLLocationManager","type":"codeVoice"},{"type":"text","text":"."}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"AppleLocationProvider","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AppleLocationProvider"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LocationManager":{"title":"LocationManager","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LocationManager"}],"type":"topic","navigatorTitle":[{"text":"LocationManager","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/locationmanager","abstract":[{"type":"text","text":"An object responsible for managing user location Puck."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationManager"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/DeviceLocationProvider":{"role":"symbol","title":"DeviceLocationProvider","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/DeviceLocationProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DeviceLocationProvider"}],"abstract":[{"type":"text","text":"Location provider specialisation that provides real-time locations generated from the device"}],"url":"\/documentation\/mapboxcommon\/devicelocationprovider","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DeviceLocationProvider"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"path":"\/metadata\/title","value":"MBXAccuracyLevel","op":"replace"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"MBXAccuracyLevel"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MBXAccuracyLevel"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel\/high","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel\/highest","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel\/low","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel\/medium","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel\/passive"],"title":"Enumeration Cases","anchor":"Enumeration-Cases"}]},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Coordinate2D","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationExtraKeys","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProviderRequest","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceFactory","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/DeviceLocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/IntervalSettings"],"generated":true,"title":"Location","anchor":"Location"}],"op":"replace","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MBXAccuracyLevel","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel~1passive\/title","op":"replace","value":"MBXAccuracyLevelPassive"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel~1passive\/fragments","value":[{"text":"MBXAccuracyLevelPassive","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"MBXAccuracyLevelHighest","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel~1highest\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel~1highest\/fragments","value":[{"text":"MBXAccuracyLevelHighest","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationError\/title","value":"MBXLocationError"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationError\/fragments","value":[{"text":"MBXLocationError","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationError\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBXLocationError"}]},{"value":"MBXPermissionStatus","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXPermissionStatus"}]},{"op":"replace","value":[{"kind":"identifier","text":"MBXPermissionStatus"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/title","value":"MBXLocationObserver"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/fragments","value":[{"kind":"identifier","text":"MBXLocationObserver"}],"op":"replace"},{"value":[{"kind":"identifier","text":"MBXLocationObserver"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/navigatorTitle"},{"op":"replace","value":"MBXLocationServiceFactory","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceFactory\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceFactory\/fragments","op":"replace","value":[{"text":"MBXLocationServiceFactory","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceFactory\/navigatorTitle","value":[{"text":"MBXLocationServiceFactory","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProviderRequest\/title","value":"MBXLocationProviderRequest"},{"value":[{"text":"MBXLocationProviderRequest","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProviderRequest\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProviderRequest\/navigatorTitle","value":[{"kind":"identifier","text":"MBXLocationProviderRequest"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/title","op":"replace","value":"MBXLocationErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/fragments","value":[{"text":"MBXLocationErrorCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/navigatorTitle","value":[{"kind":"identifier","text":"MBXLocationErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel~1medium\/title","value":"MBXAccuracyLevelMedium"},{"value":[{"text":"MBXAccuracyLevelMedium","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel~1medium\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1IntervalSettings\/title","op":"replace","value":"MBXIntervalSettings"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1IntervalSettings\/fragments","op":"replace","value":[{"text":"MBXIntervalSettings","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1IntervalSettings\/navigatorTitle","value":[{"text":"MBXIntervalSettings","kind":"identifier"}],"op":"replace"},{"value":"MBXLocationProvider","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/fragments","value":[{"kind":"identifier","text":"MBXLocationProvider"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/navigatorTitle","value":[{"text":"MBXLocationProvider","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver\/title","op":"replace","value":"MBXLocationServiceObserver"},{"value":[{"text":"MBXLocationServiceObserver","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver\/fragments"},{"value":[{"text":"MBXLocationServiceObserver","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/title","op":"replace","value":"MBXLocation"},{"value":[{"text":"MBXLocation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/fragments"},{"value":[{"text":"MBXLocation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization\/title","value":"MBXAccuracyAuthorization"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization\/fragments","op":"replace","value":[{"text":"MBXAccuracyAuthorization","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization\/navigatorTitle","value":[{"text":"MBXAccuracyAuthorization","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel~1high\/title","value":"MBXAccuracyLevelHigh"},{"op":"replace","value":[{"text":"MBXAccuracyLevelHigh","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel~1high\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel~1low\/title","value":"MBXAccuracyLevelLow"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel~1low\/fragments","value":[{"kind":"identifier","text":"MBXAccuracyLevelLow"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Coordinate2D\/title","value":"MBXCoordinate2D","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Coordinate2D\/fragments","value":[{"text":"MBXCoordinate2D","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Coordinate2D\/navigatorTitle","value":[{"text":"MBXCoordinate2D","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationExtraKeys\/title","value":"MBXLocationExtraKeys"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationExtraKeys\/fragments","value":[{"kind":"identifier","text":"MBXLocationExtraKeys"}]},{"value":[{"kind":"identifier","text":"MBXLocationExtraKeys"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationExtraKeys\/navigatorTitle","op":"replace"},{"op":"replace","value":"MBXAccuracyLevel","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel\/title"},{"value":[{"kind":"identifier","text":"MBXAccuracyLevel"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel\/navigatorTitle","value":[{"kind":"identifier","text":"MBXAccuracyLevel"}],"op":"replace"},{"value":"MBXDeviceLocationProvider","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1DeviceLocationProvider\/title","op":"replace"},{"value":[{"text":"MBXDeviceLocationProvider","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1DeviceLocationProvider\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1DeviceLocationProvider\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBXDeviceLocationProvider"}]}]}]}