{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"LocationExtraKeys","kind":"identifier"}],"platforms":["iOS"]}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"LocationExtraKeys","symbolKind":"class","role":"symbol","navigatorTitle":[{"text":"LocationExtraKeys","kind":"identifier"}],"modules":[{"name":"MapboxCommon"}],"roleHeading":"Class","externalID":"c:objc(cs)MBXLocationExtraKeys","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"LocationExtraKeys","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationExtraKeys"},"sections":[],"abstract":[{"type":"text","text":"Keys for additional information (extra) in Location."}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"type":"inheritsFrom"},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH"]}],"seeAlsoSections":[{"generated":true,"anchor":"Location","title":"Location","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationManager","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck2DConfiguration","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Model","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckBearing","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProviderDelegate","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Coordinate2D","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProviderRequest","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceFactory","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/DeviceLocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Heading","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckRenderingData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/IntervalSettings"]}],"topicSections":[{"title":"Type Properties","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationExtraKeys\/isExternal","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationExtraKeys\/isMock"],"anchor":"Type-Properties"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/locationextrakeys"]},{"paths":["\/documentation\/mapboxcommon\/locationextrakeys"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeadingObserver":{"title":"HeadingObserver","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HeadingObserver"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"HeadingObserver"}],"url":"\/documentation\/mapboxmaps\/headingobserver","abstract":[{"text":"Listens to ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingProvider","type":"reference"},{"type":"text","text":"’s updates."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingObserver"},"doc://com.mapbox.MapboxMaps/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationServiceObserver":{"title":"LocationServiceObserver","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"LocationServiceObserver","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocationServiceObserver"}],"url":"\/documentation\/mapboxcommon\/locationserviceobserver","abstract":[{"type":"text","text":"Observers for getting updates from LocationService."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AppleLocationProviderDelegate":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProviderDelegate","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProviderDelegate","isActive":true,"type":"reference"},{"type":"text","text":" protocol defines a set of optional methods that you"},{"text":" ","type":"text"},{"type":"text","text":"can use to receive events from an associated location provider object."}],"url":"\/documentation\/mapboxmaps\/applelocationproviderdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AppleLocationProviderDelegate"}],"title":"AppleLocationProviderDelegate","navigatorTitle":[{"text":"AppleLocationProviderDelegate","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationObserver":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationObserver","abstract":[{"type":"text","text":"Observer for getting updates from a LocationProvider."}],"role":"symbol","navigatorTitle":[{"text":"LocationObserver","kind":"identifier"}],"kind":"symbol","title":"LocationObserver","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"LocationObserver","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/locationobserver"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationProvider":{"title":"LocationProvider","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider","kind":"symbol","type":"topic","url":"\/documentation\/mapboxcommon\/locationprovider","abstract":[{"type":"text","text":"Location provider that provides locations"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LocationProvider"}],"navigatorTitle":[{"kind":"identifier","text":"LocationProvider"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Coordinate2D":{"type":"topic","abstract":[{"type":"text","text":"Boxed version of CLLocationCoordinate2D"}],"navigatorTitle":[{"text":"Coordinate2D","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Coordinate2D","title":"Coordinate2D","role":"symbol","url":"\/documentation\/mapboxcommon\/coordinate2d","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Coordinate2D","kind":"identifier"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AppleLocationProvider":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProvider","title":"AppleLocationProvider","kind":"symbol","url":"\/documentation\/mapboxmaps\/applelocationprovider","abstract":[{"type":"text","text":"A location provider based on CoreLocation’s "},{"code":"CLLocationManager","type":"codeVoice"},{"type":"text","text":"."}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"AppleLocationProvider","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AppleLocationProvider"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/DeviceLocationProvider":{"role":"symbol","title":"DeviceLocationProvider","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/DeviceLocationProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DeviceLocationProvider"}],"abstract":[{"type":"text","text":"Location provider specialisation that provides real-time locations generated from the device"}],"url":"\/documentation\/mapboxcommon\/devicelocationprovider","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DeviceLocationProvider"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationErrorCode":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"LocationErrorCode","kind":"identifier"}],"title":"LocationErrorCode","url":"\/documentation\/mapboxcommon\/locationerrorcode","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode","abstract":[{"type":"text","text":"Codes of location errors."}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"LocationErrorCode","kind":"identifier"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LocationOptions":{"role":"symbol","title":"LocationOptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationOptions","kind":"symbol","type":"topic","navigatorTitle":[{"text":"LocationOptions","kind":"identifier"}],"abstract":[{"text":"A struct to configure a ","type":"text"},{"code":"LocationManager","type":"codeVoice"}],"url":"\/documentation\/mapboxmaps\/locationoptions","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"LocationOptions","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LocationManager":{"title":"LocationManager","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LocationManager"}],"type":"topic","navigatorTitle":[{"text":"LocationManager","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/locationmanager","abstract":[{"type":"text","text":"An object responsible for managing user location Puck."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationManager"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PuckBearing":{"kind":"symbol","title":"PuckBearing","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PuckBearing","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PuckBearing"}],"url":"\/documentation\/mapboxmaps\/puckbearing","abstract":[{"type":"text","text":"Controls how the puck is oriented"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckBearing"},"doc://com.mapbox.MapboxMaps/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject","title":"NSObject"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationServiceFactory":{"role":"symbol","title":"LocationServiceFactory","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceFactory","kind":"symbol","type":"topic","navigatorTitle":[{"text":"LocationServiceFactory","kind":"identifier"}],"abstract":[{"type":"text","text":"Location service factory."}],"url":"\/documentation\/mapboxcommon\/locationservicefactory","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LocationServiceFactory"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationExtraKeys/isMock":{"title":"isMock","abstract":[{"type":"text","text":"The key to indicate if this location fix is a mock."}],"navigatorTitle":[{"text":"IsMock","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationExtraKeys\/isMock","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isMock","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"url":"\/documentation\/mapboxcommon\/locationextrakeys\/ismock","kind":"symbol"},"doc://com.mapbox.MapboxMaps/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.mapbox.MapboxMaps/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.mapbox.MapboxMaps/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","title":"Swift.Equatable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeadingProvider":{"title":"HeadingProvider","kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"HeadingProvider","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"HeadingProvider"}],"url":"\/documentation\/mapboxmaps\/headingprovider","abstract":[{"type":"text","text":"Provides heading data to drive the location puck."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingProvider"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/IntervalSettings":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/IntervalSettings","abstract":[{"text":"The interval for active location updates","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"IntervalSettings","kind":"identifier"}],"kind":"symbol","title":"IntervalSettings","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"IntervalSettings","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/intervalsettings"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Location-APIs":{"abstract":[],"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/location-apis","title":"Location","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","url":"\/documentation\/overview","abstract":[],"type":"topic","role":"collection","title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Location":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Location"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Location","kind":"identifier"}],"title":"Location","abstract":[{"type":"text","text":"Location information."}],"url":"\/documentation\/mapboxcommon\/location","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Heading":{"navigatorTitle":[{"kind":"identifier","text":"Heading"}],"abstract":[{"type":"text","text":"The azimuth (orientation) of the user’s device, relative to true or magnetic north."}],"url":"\/documentation\/mapboxmaps\/heading","role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Heading","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Heading","kind":"identifier"}],"title":"Heading"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Puck3DConfiguration":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration","abstract":[],"role":"symbol","navigatorTitle":[{"text":"Puck3DConfiguration","kind":"identifier"}],"kind":"symbol","title":"Puck3DConfiguration","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Puck3DConfiguration","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/puck3dconfiguration"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PuckType":{"title":"PuckType","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PuckType"}],"type":"topic","navigatorTitle":[{"text":"PuckType","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/pucktype","abstract":[{"text":"Represents the different types of pucks","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckType"},"doc://com.mapbox.MapboxMaps/SH":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","title":"Swift.Hashable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Model":{"role":"symbol","type":"topic","navigatorTitle":[{"text":"Model","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"Model","kind":"identifier"}],"title":"Model","url":"\/documentation\/mapboxmaps\/model","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Model","kind":"symbol","abstract":[{"type":"text","text":"A structure represeting a Model"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationExtraKeys/isExternal":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"IsExternal"}],"abstract":[{"type":"text","text":"The key to indicate if this location fix is retrieved from an external"},{"text":" ","type":"text"},{"text":"accessory attached to the device such as GNSS dongle, CarPlay, etc.","type":"text"}],"title":"isExternal","type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationExtraKeys\/isExternal","url":"\/documentation\/mapboxcommon\/locationextrakeys\/isexternal","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isExternal","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!","kind":"text"}]},"doc://com.mapbox.MapboxMaps/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/AccuracyLevel":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel","abstract":[{"text":"The accuracy of the observed location","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"AccuracyLevel","kind":"identifier"}],"kind":"symbol","title":"AccuracyLevel","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AccuracyLevel"}],"url":"\/documentation\/mapboxcommon\/accuracylevel"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationExtraKeys":{"role":"symbol","title":"LocationExtraKeys","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationExtraKeys","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocationExtraKeys"}],"abstract":[{"type":"text","text":"Keys for additional information (extra) in Location."}],"url":"\/documentation\/mapboxcommon\/locationextrakeys","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LocationExtraKeys"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Puck2DConfiguration":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Puck2DConfiguration","kind":"identifier"}],"kind":"symbol","title":"Puck2DConfiguration","abstract":[],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck2DConfiguration","url":"\/documentation\/mapboxmaps\/puck2dconfiguration","role":"symbol","navigatorTitle":[{"text":"Puck2DConfiguration","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/AccuracyAuthorization":{"title":"AccuracyAuthorization","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AccuracyAuthorization","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"AccuracyAuthorization"}],"url":"\/documentation\/mapboxcommon\/accuracyauthorization","abstract":[{"type":"text","text":"Accuracy authorization granted by user to the app."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PuckRenderingData":{"abstract":[{"type":"text","text":"Represents the interpolated data ready to render the user location puck."}],"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"PuckRenderingData"}],"title":"PuckRenderingData","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckRenderingData","url":"\/documentation\/mapboxmaps\/puckrenderingdata","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"PuckRenderingData","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PermissionStatus":{"abstract":[{"type":"text","text":"Location permissions granted by user to the app."}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PermissionStatus","kind":"identifier"}],"title":"PermissionStatus","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus","url":"\/documentation\/mapboxcommon\/permissionstatus","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PermissionStatus"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationError":{"role":"symbol","title":"LocationError","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationError","kind":"symbol","type":"topic","navigatorTitle":[{"text":"LocationError","kind":"identifier"}],"abstract":[{"type":"text","text":"Error code with brief explanation."}],"url":"\/documentation\/mapboxcommon\/locationerror","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"LocationError","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationProviderRequest":{"role":"symbol","kind":"symbol","url":"\/documentation\/mapboxcommon\/locationproviderrequest","abstract":[{"text":"Data model that contains parameters for location requests.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProviderRequest","title":"LocationProviderRequest","navigatorTitle":[{"kind":"identifier","text":"LocationProviderRequest"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationProviderRequest"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"MBXLocationExtraKeys"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"MBXLocationExtraKeys","kind":"identifier"}]},{"value":[{"text":"MBXLocationExtraKeys","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationExtraKeys\/isExternal","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationExtraKeys\/isMock"],"title":"Type Properties","anchor":"Type-Properties"}],"path":"\/topicSections"},{"value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Location","anchor":"Location","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Coordinate2D","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProviderRequest","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceFactory","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/DeviceLocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/IntervalSettings"],"generated":true}]},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBXLocationExtraKeys"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"MBXLocationServiceObserver","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver\/fragments","op":"replace","value":[{"text":"MBXLocationServiceObserver","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver\/navigatorTitle","op":"replace","value":[{"text":"MBXLocationServiceObserver","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/title","value":"MBXLocationObserver","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBXLocationObserver"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/navigatorTitle","value":[{"kind":"identifier","text":"MBXLocationObserver"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/title","value":"MBXLocationProvider"},{"value":[{"kind":"identifier","text":"MBXLocationProvider"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/navigatorTitle","op":"replace","value":[{"text":"MBXLocationProvider","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Coordinate2D\/title","value":"MBXCoordinate2D"},{"value":[{"text":"MBXCoordinate2D","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Coordinate2D\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Coordinate2D\/navigatorTitle","value":[{"text":"MBXCoordinate2D","kind":"identifier"}],"op":"replace"},{"value":"MBXDeviceLocationProvider","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1DeviceLocationProvider\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1DeviceLocationProvider\/fragments","op":"replace","value":[{"text":"MBXDeviceLocationProvider","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1DeviceLocationProvider\/navigatorTitle","op":"replace","value":[{"text":"MBXDeviceLocationProvider","kind":"identifier"}]},{"value":"MBXLocationErrorCode","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/fragments","value":[{"kind":"identifier","text":"MBXLocationErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/navigatorTitle","value":[{"kind":"identifier","text":"MBXLocationErrorCode"}]},{"value":"MBXLocationServiceFactory","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceFactory\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceFactory\/fragments","value":[{"text":"MBXLocationServiceFactory","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceFactory\/navigatorTitle","op":"replace","value":[{"text":"MBXLocationServiceFactory","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationExtraKeys~1isMock\/title","op":"replace","value":"IsMock"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationExtraKeys~1isMock\/fragments","op":"replace","value":[{"text":"IsMock","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1IntervalSettings\/title","value":"MBXIntervalSettings"},{"value":[{"kind":"identifier","text":"MBXIntervalSettings"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1IntervalSettings\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1IntervalSettings\/navigatorTitle","value":[{"text":"MBXIntervalSettings","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/title","value":"MBXLocation"},{"op":"replace","value":[{"kind":"identifier","text":"MBXLocation"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/navigatorTitle","value":[{"kind":"identifier","text":"MBXLocation"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationExtraKeys~1isExternal\/title","value":"IsExternal","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationExtraKeys~1isExternal\/fragments","value":[{"text":"IsExternal","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel\/title","value":"MBXAccuracyLevel","op":"replace"},{"value":[{"text":"MBXAccuracyLevel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel\/navigatorTitle","value":[{"kind":"identifier","text":"MBXAccuracyLevel"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationExtraKeys\/title","value":"MBXLocationExtraKeys","op":"replace"},{"value":[{"text":"MBXLocationExtraKeys","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationExtraKeys\/fragments","op":"replace"},{"value":[{"text":"MBXLocationExtraKeys","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationExtraKeys\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization\/title","value":"MBXAccuracyAuthorization"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization\/fragments","value":[{"text":"MBXAccuracyAuthorization","kind":"identifier"}]},{"op":"replace","value":[{"text":"MBXAccuracyAuthorization","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization\/navigatorTitle"},{"value":"MBXPermissionStatus","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/title","op":"replace"},{"value":[{"text":"MBXPermissionStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/navigatorTitle","value":[{"kind":"identifier","text":"MBXPermissionStatus"}]},{"op":"replace","value":"MBXLocationError","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationError\/title"},{"value":[{"text":"MBXLocationError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationError\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationError\/navigatorTitle","op":"replace","value":[{"text":"MBXLocationError","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProviderRequest\/title","value":"MBXLocationProviderRequest","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProviderRequest\/fragments","value":[{"text":"MBXLocationProviderRequest","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProviderRequest\/navigatorTitle","op":"replace","value":[{"text":"MBXLocationProviderRequest","kind":"identifier"}]}]}]}