{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"CustomLayerRenderParameters","modules":[{"name":"MapboxMaps"}],"externalID":"c:objc(cs)MBMCustomLayerRenderParameters","role":"symbol","roleHeading":"Class","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomLayerRenderParameters"}],"navigatorTitle":[{"text":"CustomLayerRenderParameters","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters"},"kind":"symbol","seeAlsoSections":[{"anchor":"Layers","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerInfo","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/BackgroundLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CircleLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillExtrusionLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationIndicatorLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterParticleLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SkyLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderConfiguration","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerHost","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ElevationData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Slot","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SlotLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerAtPosition","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClipLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClipLayerTypes"],"title":"Layers","generated":true}],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"]},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH"],"kind":"relationships"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CustomLayerRenderParameters","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/mapboxmaps\/customlayerrenderparameters"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/customlayerrenderparameters"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Parameters that define the current camera position for a "},{"type":"codeVoice","code":"CustomLayerHost::render()"},{"type":"text","text":" function."}],"sections":[],"topicSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters\/init(width:height:latitude:longitude:zoom:bearing:pitch:fieldOfView:projectionMatrix:elevationData:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters\/init(width:height:latitude:longitude:zoom:bearing:pitch:fieldOfView:projectionMatrix:elevationData:renderToTilesIDs:)"],"anchor":"Initializers","title":"Initializers","generated":true},{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters\/bearing","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters\/elevationData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters\/fieldOfView","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters\/height","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters\/latitude","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters\/longitude","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters\/pitch","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters\/projectionMatrix","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters\/renderToTilesIDs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters\/width","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters\/zoom"]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerRenderParameters/projectionMatrix":{"kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/customlayerrenderparameters\/projectionmatrix","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"projectionMatrix","kind":"identifier"},{"text":": [","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"]"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters\/projectionMatrix","title":"projectionMatrix","navigatorTitle":[{"text":"projectionMatrix","kind":"identifier"}],"abstract":[{"type":"text","text":"The projection matrix used for rendering. It projects spherical mercator coordinates to gl coordinates."}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"title":"MapboxMaps Documentation","role":"collection","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerRenderParameters/init(width:height:latitude:longitude:zoom:bearing:pitch:fieldOfView:projectionMatrix:elevationData:)":{"abstract":[],"kind":"symbol","url":"\/documentation\/mapboxmaps\/customlayerrenderparameters\/init(width:height:latitude:longitude:zoom:bearing:pitch:fieldofview:projectionmatrix:elevationdata:)","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters\/init(width:height:latitude:longitude:zoom:bearing:pitch:fieldOfView:projectionMatrix:elevationData:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"width"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"height","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"text":"latitude","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"text":"longitude","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":", "},{"text":"zoom","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":", ","kind":"text"},{"text":"bearing","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"pitch"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"fieldOfView"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"projectionMatrix"},{"text":": [","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"text":"elevationData","kind":"externalParam"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MBMElevationData","text":"ElevationData"},{"text":")?)","kind":"text"}],"navigatorTitle":[{"text":"initWithWidth:height:latitude:longitude:zoom:bearing:pitch:fieldOfView:projectionMatrix:elevationData:","kind":"identifier"}],"title":"init(width:height:latitude:longitude:zoom:bearing:pitch:fieldOfView:projectionMatrix:elevationData:)","deprecated":true,"type":"topic"},"doc://com.mapbox.MapboxMaps/objc(pl)NSObject":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SlotLayer":{"url":"\/documentation\/mapboxmaps\/slotlayer","role":"symbol","type":"topic","title":"SlotLayer","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SlotLayer"}],"abstract":[{"text":"Marks the position of a slot.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SlotLayer","navigatorTitle":[{"kind":"identifier","text":"SlotLayer"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SkyLayer":{"navigatorTitle":[{"kind":"identifier","text":"SkyLayer"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SkyLayer","kind":"symbol","title":"SkyLayer","abstract":[{"type":"text","text":"A spherical dome around the map that is always rendered behind all other layers."},{"type":"text","text":" "},{"text":"Warning: As of v10.6.0, ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Atmosphere"},{"text":" is the preferred method for atmospheric styling. Sky layer is not supported by the globe projection, and will be phased out in future major release.","type":"text"}],"role":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/skylayer","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SkyLayer","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Slot":{"url":"\/documentation\/mapboxmaps\/slot","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Slot","kind":"identifier"}],"title":"Slot","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Slot","abstract":[{"type":"text","text":"A pre-specified location in the style where layer will be added to"},{"type":"text","text":" "},{"type":"text","text":"(such as on top of existing land layers, but below all labels)."}],"kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Slot"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerAtPosition":{"kind":"symbol","title":"LayerAtPosition","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerAtPosition","abstract":[],"role":"symbol","url":"\/documentation\/mapboxmaps\/layeratposition","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LayerAtPosition"}],"navigatorTitle":[{"text":"LayerAtPosition","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layer":{"type":"topic","abstract":[],"url":"\/documentation\/mapboxmaps\/layer","kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Layer","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer","navigatorTitle":[{"text":"Layer","kind":"identifier"}],"title":"Layer"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ClipLayerTypes":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"ClipLayerTypes","kind":"identifier"}],"title":"ClipLayerTypes","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Layer types that will also be removed if fallen below this clip layer."}],"type":"topic","url":"\/documentation\/mapboxmaps\/cliplayertypes","navigatorTitle":[{"kind":"identifier","text":"ClipLayerTypes"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClipLayerTypes"},"doc://com.mapbox.MapboxMaps/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","title":"MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"url":"\/documentation\/mapboxmaps","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LocationIndicatorLayer":{"role":"symbol","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationIndicatorLayer"}],"kind":"symbol","navigatorTitle":[{"text":"LocationIndicatorLayer","kind":"identifier"}],"title":"LocationIndicatorLayer","abstract":[{"type":"text","text":"Location Indicator layer."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationIndicatorLayer","url":"\/documentation\/mapboxmaps\/locationindicatorlayer"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerRenderParameters/bearing":{"kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/customlayerrenderparameters\/bearing","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters\/bearing","abstract":[{"type":"text","text":"The bearing (orientation) of the camera. In degrees clockwise from north, it describes the direction in which the camera points."}],"title":"bearing","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"bearing","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"navigatorTitle":[{"kind":"identifier","text":"bearing"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LineLayer":{"type":"topic","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LineLayer"}],"navigatorTitle":[{"kind":"identifier","text":"LineLayer"}],"url":"\/documentation\/mapboxmaps\/linelayer","title":"LineLayer","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineLayer","abstract":[{"text":"A stroked line.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerHost":{"type":"topic","abstract":[{"text":"Interface for hosting a custom map style layer.","type":"text"}],"url":"\/documentation\/mapboxmaps\/customlayerhost","kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CustomLayerHost"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerHost","navigatorTitle":[{"kind":"identifier","text":"CustomLayerHost"}],"title":"CustomLayerHost"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FillExtrusionLayer":{"type":"topic","abstract":[{"type":"text","text":"An extruded (3D) polygon."}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"FillExtrusionLayer","kind":"identifier"}],"title":"FillExtrusionLayer","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillExtrusionLayer","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"FillExtrusionLayer","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/fillextrusionlayer"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterLayer":{"title":"RasterLayer","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"RasterLayer","kind":"identifier"}],"navigatorTitle":[{"text":"RasterLayer","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Raster map textures such as satellite imagery.","type":"text"}],"url":"\/documentation\/mapboxmaps\/rasterlayer","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterLayer","role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerRenderParameters/latitude":{"url":"\/documentation\/mapboxmaps\/customlayerrenderparameters\/latitude","abstract":[{"text":"The latitude of camera position.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"latitude"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"latitude"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters\/latitude","title":"latitude","kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerRenderParameters/height":{"abstract":[{"type":"text","text":"The height."}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/customlayerrenderparameters\/height","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters\/height","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"height"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"height","kind":"identifier"}],"title":"height","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerRenderParameters/pitch":{"url":"\/documentation\/mapboxmaps\/customlayerrenderparameters\/pitch","abstract":[{"text":"The pitch of the camera, the angle of pitch applied to the camera around the x-axis.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pitch"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"pitch"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters\/pitch","title":"pitch","kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FillLayer":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillLayer","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"FillLayer","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/filllayer","title":"FillLayer","abstract":[{"type":"text","text":"A filled polygon with an optional stroked border."}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"FillLayer","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerRenderParameters/width":{"navigatorTitle":[{"text":"width","kind":"identifier"}],"role":"symbol","title":"width","kind":"symbol","abstract":[{"text":"The width.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters\/width","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"width"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"url":"\/documentation\/mapboxmaps\/customlayerrenderparameters\/width"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeatmapLayer":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"HeatmapLayer"}],"role":"symbol","title":"HeatmapLayer","url":"\/documentation\/mapboxmaps\/heatmaplayer","abstract":[{"type":"text","text":"A heatmap."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HeatmapLayer","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ElevationData":{"abstract":[{"type":"text","text":"Interface that provides access to elevation data."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ElevationData","kind":"identifier"}],"title":"ElevationData","url":"\/documentation\/mapboxmaps\/elevationdata","role":"symbol","navigatorTitle":[{"text":"ElevationData","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ElevationData"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerRenderParameters/fieldOfView":{"abstract":[{"type":"text","text":"The field of view of the camera in degrees"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/customlayerrenderparameters\/fieldofview","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters\/fieldOfView","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fieldOfView"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"fieldOfView","kind":"identifier"}],"title":"fieldOfView","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerRenderParameters/longitude":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"longitude"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"The longitude of camera position."}],"role":"symbol","type":"topic","title":"longitude","navigatorTitle":[{"kind":"identifier","text":"longitude"}],"url":"\/documentation\/mapboxmaps\/customlayerrenderparameters\/longitude","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters\/longitude"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layers":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers","type":"topic","url":"\/documentation\/mapboxmaps\/layers","title":"Layers","kind":"article","role":"collectionGroup","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerRenderParameters/renderToTilesIDs":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"renderToTilesIDs","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"CanonicalTileID","preciseIdentifier":"c:objc(cs)MBMCanonicalTileID"},{"kind":"text","text":"]?"}],"abstract":[{"text":"Note! This property is an experimental feature. It can be changed or removed in future versions.","type":"text"}],"role":"symbol","type":"topic","title":"renderToTilesIDs","navigatorTitle":[{"text":"renderToTilesIDs","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/customlayerrenderparameters\/rendertotilesids","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters\/renderToTilesIDs"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerRenderConfiguration":{"kind":"symbol","type":"topic","title":"CustomLayerRenderConfiguration","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderConfiguration","abstract":[{"type":"text","text":"Note! This is an experimental feature. It can be changed or removed in future versions."}],"role":"symbol","url":"\/documentation\/mapboxmaps\/customlayerrenderconfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CustomLayerRenderConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"CustomLayerRenderConfiguration","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer":{"url":"\/documentation\/mapboxmaps\/hillshadelayer","role":"symbol","type":"topic","title":"HillshadeLayer","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"HillshadeLayer","kind":"identifier"}],"abstract":[{"type":"text","text":"Client-side hillshading visualization based on DEM data. Currently, the implementation only supports Mapbox Terrain RGB and Mapzen Terrarium tiles."}],"navigatorTitle":[{"text":"HillshadeLayer","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/BackgroundLayer":{"url":"\/documentation\/mapboxmaps\/backgroundlayer","navigatorTitle":[{"text":"BackgroundLayer","kind":"identifier"}],"title":"BackgroundLayer","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/BackgroundLayer","type":"topic","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"BackgroundLayer","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The background color or pattern of the map."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerRenderParameters/elevationData":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"elevationData"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MBMElevationData","text":"ElevationData"},{"kind":"text","text":")?"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters\/elevationData","title":"elevationData","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"If terrain is enabled, provides value to elevation data from render thread. Empty if terrain is not enabled."}],"role":"symbol","url":"\/documentation\/mapboxmaps\/customlayerrenderparameters\/elevationdata","navigatorTitle":[{"text":"elevationData","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SymbolLayer":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SymbolLayer"}],"role":"symbol","title":"SymbolLayer","url":"\/documentation\/mapboxmaps\/symbollayer","abstract":[{"text":"An icon or a text label.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolLayer","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SymbolLayer","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterParticleLayer":{"kind":"symbol","title":"RasterParticleLayer","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterParticleLayer","abstract":[{"type":"text","text":"Particle animation driven by textures such as wind maps."}],"role":"symbol","url":"\/documentation\/mapboxmaps\/rasterparticlelayer","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RasterParticleLayer"}],"navigatorTitle":[{"kind":"identifier","text":"RasterParticleLayer"}],"tags":[{"type":"spi","text":"SPI"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerInfo":{"type":"topic","abstract":[{"type":"text","text":"Information about a layer"}],"url":"\/documentation\/mapboxmaps\/layerinfo","kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LayerInfo"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerInfo","navigatorTitle":[{"kind":"identifier","text":"LayerInfo"}],"title":"LayerInfo"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayer":{"kind":"symbol","title":"CustomLayer","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayer","abstract":[{"type":"text","text":"Layer with custom rendering implementation"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/customlayer","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomLayer"}],"navigatorTitle":[{"kind":"identifier","text":"CustomLayer"}],"tags":[{"type":"spi","text":"SPI"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerRenderParameters/init(width:height:latitude:longitude:zoom:bearing:pitch:fieldOfView:projectionMatrix:elevationData:renderToTilesIDs:)":{"url":"\/documentation\/mapboxmaps\/customlayerrenderparameters\/init(width:height:latitude:longitude:zoom:bearing:pitch:fieldofview:projectionmatrix:elevationdata:rendertotilesids:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"width","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"height"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"latitude"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"longitude"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"zoom","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"text":"bearing","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":", ","kind":"text"},{"text":"pitch","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fieldOfView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"projectionMatrix"},{"text":": [","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"elevationData"},{"kind":"text","text":": (any "},{"text":"ElevationData","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MBMElevationData"},{"text":")?, ","kind":"text"},{"kind":"externalParam","text":"renderToTilesIDs"},{"text":": [","kind":"text"},{"text":"CanonicalTileID","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMCanonicalTileID"},{"kind":"text","text":"]?)"}],"role":"symbol","navigatorTitle":[{"text":"initWithWidth:height:latitude:longitude:zoom:bearing:pitch:fieldOfView:projectionMatrix:elevationData:renderToTilesIDs:","kind":"identifier"}],"deprecated":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters\/init(width:height:latitude:longitude:zoom:bearing:pitch:fieldOfView:projectionMatrix:elevationData:renderToTilesIDs:)","title":"init(width:height:latitude:longitude:zoom:bearing:pitch:fieldOfView:projectionMatrix:elevationData:renderToTilesIDs:)","kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/s7CVarArgP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelLayer":{"title":"ModelLayer","tags":[{"text":"SPI","type":"spi"}],"url":"\/documentation\/mapboxmaps\/modellayer","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ModelLayer"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ModelLayer"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer","abstract":[{"text":"A layer to render 3D Models.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Atmosphere":{"kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Atmosphere","kind":"identifier"}],"type":"topic","title":"Atmosphere","abstract":[{"type":"text","text":"A style’s fog property is a global effect that improves depth perception by fading out distant objects."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Atmosphere","navigatorTitle":[{"text":"Atmosphere","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/atmosphere"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CircleLayer":{"navigatorTitle":[{"kind":"identifier","text":"CircleLayer"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CircleLayer","abstract":[{"type":"text","text":"A filled circle."}],"title":"CircleLayer","type":"topic","url":"\/documentation\/mapboxmaps\/circlelayer","kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"CircleLayer","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerType":{"title":"LayerType","navigatorTitle":[{"kind":"identifier","text":"LayerType"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LayerType"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType","kind":"symbol","abstract":[{"text":"Struct of supported Layer rendering types","type":"text"}],"url":"\/documentation\/mapboxmaps\/layertype","type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerRenderParameters":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters","abstract":[{"text":"Parameters that define the current camera position for a ","type":"text"},{"code":"CustomLayerHost::render()","type":"codeVoice"},{"type":"text","text":" function."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"CustomLayerRenderParameters","kind":"identifier"}],"title":"CustomLayerRenderParameters","url":"\/documentation\/mapboxmaps\/customlayerrenderparameters","role":"symbol","navigatorTitle":[{"text":"CustomLayerRenderParameters","kind":"identifier"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/SH":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ClipLayer":{"type":"topic","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ClipLayer","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ClipLayer"}],"url":"\/documentation\/mapboxmaps\/cliplayer","title":"ClipLayer","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClipLayer","abstract":[{"type":"text","text":"Layer that removes 3D content from map."}]},"doc://com.mapbox.MapboxMaps/objc(cs)NSObject":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.mapbox.MapboxMaps/SQ":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerRenderParameters/zoom":{"url":"\/documentation\/mapboxmaps\/customlayerrenderparameters\/zoom","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters\/zoom","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"zoom","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"type":"topic","title":"zoom","navigatorTitle":[{"kind":"identifier","text":"zoom"}],"kind":"symbol","abstract":[{"type":"text","text":"The zoom of the camera."}]},"doc://com.mapbox.MapboxMaps/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MBMCustomLayerRenderParameters"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"value":[{"text":"MBMCustomLayerRenderParameters","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"MBMCustomLayerRenderParameters","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters\/bearing","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters\/elevationData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters\/fieldOfView","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters\/height","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters\/latitude","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters\/longitude","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters\/pitch","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters\/projectionMatrix","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters\/renderToTilesIDs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters\/width","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters\/zoom"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters\/init(width:height:latitude:longitude:zoom:bearing:pitch:fieldOfView:projectionMatrix:elevationData:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters\/init(width:height:latitude:longitude:zoom:bearing:pitch:fieldOfView:projectionMatrix:elevationData:renderToTilesIDs:)"],"anchor":"Instance-Methods"}]},{"value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"]}],"op":"replace","path":"\/relationshipsSections"},{"op":"replace","path":"\/seeAlsoSections","value":[{"generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderConfiguration","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerHost","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ElevationData"],"anchor":"Layers","title":"Layers"}]},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBMCustomLayerRenderParameters"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"projectionMatrix","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters~1projectionMatrix\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters~1projectionMatrix\/fragments","value":[{"kind":"identifier","text":"projectionMatrix"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters~1init(width:height:latitude:longitude:zoom:bearing:pitch:fieldOfView:projectionMatrix:elevationData:)\/title","value":"initWithWidth:height:latitude:longitude:zoom:bearing:pitch:fieldOfView:projectionMatrix:elevationData:"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters~1init(width:height:latitude:longitude:zoom:bearing:pitch:fieldOfView:projectionMatrix:elevationData:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithWidth:height:latitude:longitude:zoom:bearing:pitch:fieldOfView:projectionMatrix:elevationData:"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters~1bearing\/title","op":"replace","value":"bearing"},{"op":"replace","value":[{"text":"bearing","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters~1bearing\/fragments"},{"value":"MBMCustomLayerHost","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost\/fragments","value":[{"kind":"identifier","text":"MBMCustomLayerHost"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost\/navigatorTitle","value":[{"text":"MBMCustomLayerHost","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters~1latitude\/title","value":"latitude","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters~1latitude\/fragments","value":[{"text":"latitude","kind":"identifier"}],"op":"replace"},{"value":"height","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters~1height\/title"},{"op":"replace","value":[{"text":"height","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters~1height\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters~1pitch\/title","value":"pitch","op":"replace"},{"value":[{"text":"pitch","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters~1pitch\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters~1width\/title","op":"replace","value":"width"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters~1width\/fragments","value":[{"kind":"identifier","text":"width"}],"op":"replace"},{"value":"MBMElevationData","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ElevationData\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ElevationData\/fragments","value":[{"kind":"identifier","text":"MBMElevationData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ElevationData\/navigatorTitle","value":[{"kind":"identifier","text":"MBMElevationData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters~1fieldOfView\/title","value":"fieldOfView"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters~1fieldOfView\/fragments","value":[{"kind":"identifier","text":"fieldOfView"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters~1longitude\/title","value":"longitude","op":"replace"},{"value":[{"kind":"identifier","text":"longitude"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters~1longitude\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters~1renderToTilesIDs\/title","value":"renderToTilesIDs","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters~1renderToTilesIDs\/fragments","value":[{"kind":"identifier","text":"renderToTilesIDs"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderConfiguration\/title","value":"MBMCustomLayerRenderConfiguration","op":"replace"},{"value":[{"text":"MBMCustomLayerRenderConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"MBMCustomLayerRenderConfiguration"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderConfiguration\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters~1elevationData\/title","value":"elevationData","op":"replace"},{"value":[{"kind":"identifier","text":"elevationData"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters~1elevationData\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters~1init(width:height:latitude:longitude:zoom:bearing:pitch:fieldOfView:projectionMatrix:elevationData:renderToTilesIDs:)\/title","value":"initWithWidth:height:latitude:longitude:zoom:bearing:pitch:fieldOfView:projectionMatrix:elevationData:renderToTilesIDs:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithWidth:height:latitude:longitude:zoom:bearing:pitch:fieldOfView:projectionMatrix:elevationData:renderToTilesIDs:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters~1init(width:height:latitude:longitude:zoom:bearing:pitch:fieldOfView:projectionMatrix:elevationData:renderToTilesIDs:)\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/title","op":"replace","value":"MBMCustomLayerRenderParameters"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/fragments","value":[{"kind":"identifier","text":"MBMCustomLayerRenderParameters"}]},{"value":[{"kind":"identifier","text":"MBMCustomLayerRenderParameters"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/navigatorTitle","op":"replace"},{"value":"zoom","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters~1zoom\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters~1zoom\/fragments","op":"replace","value":[{"text":"zoom","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}