{"seeAlsoSections":[{"title":"Symbols","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapRecorder","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeatureExtensionValue","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Size","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackError-swift.class","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestErrorType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapLoadingErrorTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRenderModeTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestDataSourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestErrorTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestLoadingMethodTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestPriorityTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestPriorityTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestResourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMResponseSourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMSourceDataLoadedTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStyleDataLoadedTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMTileStoreUsageModeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraChangedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GenericEventCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinishedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequestCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceAddedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceRemovedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageMissingCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapIdleCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnusedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TransitionOptions-swift.class"],"anchor":"Symbols"}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/renderframestartedcallback"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/renderframestartedcallback"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"RenderFrameStartedCallback","kind":"identifier"},{"kind":"text","text":" = ("},{"text":"RenderFrameStarted","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameStarted","preciseIdentifier":"c:objc(cs)MBMRenderFrameStarted","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"}]}]}],"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"map"},{"type":"text","text":" started rendering a frame."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameStartedCallback"},"metadata":{"modules":[{"name":"MapboxMaps"}],"symbolKind":"typealias","externalID":"c:MBMRenderFrameStartedCallback.h@T@MBMRenderFrameStartedCallback","roleHeading":"Type Alias","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"RenderFrameStartedCallback","kind":"identifier"}],"title":"RenderFrameStartedCallback","navigatorTitle":[{"text":"RenderFrameStartedCallback","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMapsInternal"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRequestPriorityTypeToString(_:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBMRequestPriorityTypeToString"}],"kind":"symbol","title":"MBMRequestPriorityTypeToString(_:)","type":"topic","url":"\/documentation\/mapboxmaps\/mbmrequestprioritytypetostring(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestPriorityTypeToString(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBMRequestPriorityTypeToString"},{"text":"(","kind":"text"},{"text":"RequestPriorityType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMRequestPriorityType"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"!"}],"abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoadingErrorCallback":{"title":"MapLoadingErrorCallback","type":"topic","url":"\/documentation\/mapboxmaps\/maploadingerrorcallback","navigatorTitle":[{"kind":"identifier","text":"MapLoadingErrorCallback"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Describes an error that has occurred while loading the "},{"type":"codeVoice","code":"map"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorCallback","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapLoadingErrorCallback"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GenericEventCallback":{"title":"GenericEventCallback","url":"\/documentation\/mapboxmaps\/genericeventcallback","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"GenericEventCallback","kind":"identifier"}],"navigatorTitle":[{"text":"GenericEventCallback","kind":"identifier"}],"abstract":[{"text":"Generic event for experimental events.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GenericEventCallback","role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FeatureExtensionValue":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeatureExtensionValue","title":"FeatureExtensionValue","abstract":[{"type":"text","text":"A value or a collection of a feature extension."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FeatureExtensionValue"}],"navigatorTitle":[{"text":"FeatureExtensionValue","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/featureextensionvalue","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Size":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Size"}],"kind":"symbol","title":"Size","type":"topic","url":"\/documentation\/mapboxmaps\/size","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Size","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Size","kind":"identifier"}],"abstract":[{"text":"Size type.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMTileStoreUsageModeToString(_:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBMTileStoreUsageModeToString"}],"kind":"symbol","title":"MBMTileStoreUsageModeToString(_:)","type":"topic","url":"\/documentation\/mapboxmaps\/mbmtilestoreusagemodetostring(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMTileStoreUsageModeToString(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBMTileStoreUsageModeToString"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMTileStoreUsageMode","text":"TileStoreUsageMode"},{"kind":"text","text":") -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePackError-swift.class":{"title":"StylePackError","type":"topic","url":"\/documentation\/mapboxmaps\/stylepackerror-swift.class","navigatorTitle":[{"text":"StylePackError","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Describes a style package load request error.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackError-swift.class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"StylePackError","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMStyleDataLoadedTypeToString(_:)":{"title":"MBMStyleDataLoadedTypeToString(_:)","type":"topic","url":"\/documentation\/mapboxmaps\/mbmstyledataloadedtypetostring(_:)","navigatorTitle":[{"kind":"identifier","text":"MBMStyleDataLoadedTypeToString"}],"role":"symbol","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStyleDataLoadedTypeToString(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBMStyleDataLoadedTypeToString"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"StyleDataLoadedType","preciseIdentifier":"c:@E@MBMStyleDataLoadedType"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRequestResourceTypeToString(_:)":{"title":"MBMRequestResourceTypeToString(_:)","type":"topic","url":"\/documentation\/mapboxmaps\/mbmrequestresourcetypetostring(_:)","navigatorTitle":[{"kind":"identifier","text":"MBMRequestResourceTypeToString"}],"role":"symbol","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestResourceTypeToString(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBMRequestResourceTypeToString"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMRequestResourceType","text":"RequestResourceType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"!","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRequestLoadingMethodTypeToString(_:)":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestLoadingMethodTypeToString(_:)","title":"MBMRequestLoadingMethodTypeToString(_:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBMRequestLoadingMethodTypeToString","kind":"identifier"},{"kind":"text","text":"("},{"text":"RequestLoadingMethodType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMRequestLoadingMethodType"},{"kind":"text","text":") -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"navigatorTitle":[{"text":"MBMRequestLoadingMethodTypeToString","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/mbmrequestloadingmethodtypetostring(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResourceRequestCallback":{"role":"symbol","navigatorTitle":[{"text":"ResourceRequestCallback","kind":"identifier"}],"kind":"symbol","title":"ResourceRequestCallback","type":"topic","url":"\/documentation\/mapboxmaps\/resourcerequestcallback","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequestCallback","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ResourceRequestCallback"}],"abstract":[{"type":"text","text":"The "},{"code":"ResourceRequest","type":"codeVoice"},{"type":"text","text":" event allows the application to observe resourcerequests"},{"type":"text","text":" "},{"type":"text","text":"made by a "},{"type":"codeVoice","code":"map"},{"type":"text","text":" or "},{"type":"codeVoice","code":"map snapshotter"},{"type":"text","text":" object."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraChangedCallback":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraChangedCallback"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CameraChangedCallback"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraChangedCallback","abstract":[{"text":"This event is emitted whenever the visible viewport changes its size","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"due to the invocation of the "},{"type":"codeVoice","code":"setSize"},{"type":"text","text":" and "},{"type":"codeVoice","code":"setBounds"},{"text":" methods or when","type":"text"},{"type":"text","text":" "},{"text":"the camera is modified by calling camera methods. The event is emitted","type":"text"},{"type":"text","text":" "},{"text":"synchronously so that an updated camera state can be fetched immediately.","type":"text"}],"title":"CameraChangedCallback","kind":"symbol","url":"\/documentation\/mapboxmaps\/camerachangedcallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRequestErrorTypeToString(_:)":{"title":"MBMRequestErrorTypeToString(_:)","type":"topic","url":"\/documentation\/mapboxmaps\/mbmrequesterrortypetostring(_:)","navigatorTitle":[{"kind":"identifier","text":"MBMRequestErrorTypeToString"}],"role":"symbol","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestErrorTypeToString(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBMRequestErrorTypeToString","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMRequestErrorType","text":"RequestErrorType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"!"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceRemovedCallback":{"kind":"symbol","navigatorTitle":[{"text":"SourceRemovedCallback","kind":"identifier"}],"abstract":[{"type":"text","text":"The source has been removed with "},{"type":"codeVoice","code":"removeStyleSource"},{"type":"text","text":" method."}],"type":"topic","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceRemovedCallback"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceRemovedCallback","title":"SourceRemovedCallback","url":"\/documentation\/mapboxmaps\/sourceremovedcallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRequestDataSourceTypeToString(_:)":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBMRequestDataSourceTypeToString"}],"abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBMRequestDataSourceTypeToString"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"RequestDataSourceType","preciseIdentifier":"c:@E@MBMRequestDataSourceType"},{"kind":"text","text":") -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestDataSourceTypeToString(_:)","title":"MBMRequestDataSourceTypeToString(_:)","url":"\/documentation\/mapboxmaps\/mbmrequestdatasourcetypetostring(_:)"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"title":"MapboxMaps Documentation","role":"collection","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMResponseSourceTypeToString(_:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBMResponseSourceTypeToString"}],"kind":"symbol","title":"MBMResponseSourceTypeToString(_:)","type":"topic","url":"\/documentation\/mapboxmaps\/mbmresponsesourcetypetostring(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMResponseSourceTypeToString(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBMResponseSourceTypeToString"},{"kind":"text","text":"("},{"text":"ResponseSourceType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMResponseSourceType"},{"kind":"text","text":") -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}],"abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMapsInternal":{"role":"collectionGroup","kind":"article","title":"CoreMaps - Internal","type":"topic","url":"\/documentation\/mapboxmaps\/coremapsinternal","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMapsInternal","abstract":[{"text":"Maps rendering SDK also known as GL-Native. These are for internal use only.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleLoadedCallback":{"kind":"symbol","navigatorTitle":[{"text":"StyleLoadedCallback","kind":"identifier"}],"abstract":[{"type":"text","text":"The requested style has been fully loaded, including specified sprite, and sources’ metadata."}],"type":"topic","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"StyleLoadedCallback","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleLoadedCallback","title":"StyleLoadedCallback","url":"\/documentation\/mapboxmaps\/styleloadedcallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceDataLoadedCallback":{"role":"symbol","navigatorTitle":[{"text":"SourceDataLoadedCallback","kind":"identifier"}],"kind":"symbol","title":"SourceDataLoadedCallback","type":"topic","url":"\/documentation\/mapboxmaps\/sourcedataloadedcallback","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedCallback","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceDataLoadedCallback"}],"abstract":[{"type":"text","text":"The "},{"code":"SourceDataLoaded","type":"codeVoice"},{"type":"text","text":" event is emitted when source data is loaded."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderFrameFinishedCallback":{"kind":"symbol","navigatorTitle":[{"text":"RenderFrameFinishedCallback","kind":"identifier"}],"abstract":[{"type":"text","text":"The "},{"code":"map","type":"codeVoice"},{"type":"text","text":" finished rendering a frame."}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"RenderFrameFinishedCallback"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinishedCallback","title":"RenderFrameFinishedCallback","url":"\/documentation\/mapboxmaps\/renderframefinishedcallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRenderModeTypeToString(_:)":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBMRenderModeTypeToString"}],"abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"MBMRenderModeTypeToString","kind":"identifier"},{"kind":"text","text":"("},{"text":"RenderModeType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMRenderModeType"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRenderModeTypeToString(_:)","title":"MBMRenderModeTypeToString(_:)","url":"\/documentation\/mapboxmaps\/mbmrendermodetypetostring(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoadedCallback":{"title":"MapLoadedCallback","type":"topic","url":"\/documentation\/mapboxmaps\/maploadedcallback","navigatorTitle":[{"text":"MapLoadedCallback","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The style has been fully loaded, and the "},{"code":"map","type":"codeVoice"},{"type":"text","text":" has rendered all visible tiles."},{"type":"text","text":" "},{"text":"The event will be emitted only once for the current style. If it is required to","type":"text"},{"text":" ","type":"text"},{"text":"continuously observe an event where all the necessary resources are loaded or rendered,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"please check the following events: "},{"code":"MapIdle","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"StyleDataLoaded"},{"type":"text","text":", and "},{"type":"codeVoice","code":"RenderFrameFinished"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadedCallback","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"MapLoadedCallback","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TransitionOptions-swift.class":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TransitionOptions"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"transition options"},{"type":"text","text":" controls timing for the interpolation between a transitionable style"},{"type":"text","text":" "},{"type":"text","text":"property’s previous value and new value. These can be used to define the style default property"},{"type":"text","text":" "},{"type":"text","text":"transition behavior. Also, any transitionable style property may also have its own "},{"code":"-transition","type":"codeVoice"},{"type":"text","text":" "},{"type":"text","text":"property that defines specific transition timing for that specific layer property, overriding"},{"text":" ","type":"text"},{"text":"the global transition values.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TransitionOptions"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TransitionOptions-swift.class","title":"TransitionOptions","url":"\/documentation\/mapboxmaps\/transitionoptions-swift.class"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","title":"MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"url":"\/documentation\/mapboxmaps","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderFrameStartedCallback":{"title":"RenderFrameStartedCallback","type":"topic","url":"\/documentation\/mapboxmaps\/renderframestartedcallback","navigatorTitle":[{"kind":"identifier","text":"RenderFrameStartedCallback"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"map"},{"type":"text","text":" started rendering a frame."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameStartedCallback","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RenderFrameStartedCallback"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapIdleCallback":{"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapIdleCallback"}],"navigatorTitle":[{"kind":"identifier","text":"MapIdleCallback"}],"title":"MapIdleCallback","url":"\/documentation\/mapboxmaps\/mapidlecallback","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The "},{"code":"map","type":"codeVoice"},{"type":"text","text":" has entered the idle state. The "},{"type":"codeVoice","code":"map"},{"type":"text","text":" is idle when there are no ongoing"},{"text":" ","type":"text"},{"text":"animations, transitions and the ","type":"text"},{"type":"codeVoice","code":"map"},{"type":"text","text":" has rendered all requested non-volatile tiles"},{"type":"text","text":" "},{"type":"text","text":"(e.g., live traffic tiles). The event will not be emitted if "},{"type":"codeVoice","code":"setUserAnimationInProgress"},{"type":"text","text":" "},{"type":"text","text":"and \/ or "},{"type":"codeVoice","code":"setGestureInProgress"},{"type":"text","text":" is set to "},{"code":"true","type":"codeVoice"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapIdleCallback","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleImageRemoveUnusedCallback":{"title":"StyleImageRemoveUnusedCallback","type":"topic","url":"\/documentation\/mapboxmaps\/styleimageremoveunusedcallback","navigatorTitle":[{"text":"StyleImageRemoveUnusedCallback","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"An image requested by the "},{"type":"codeVoice","code":"map"},{"type":"text","text":" through the "},{"code":"StyleImageMissing","type":"codeVoice"},{"type":"text","text":" event is no longer"},{"type":"text","text":" "},{"text":"needed and can be removed using the ","type":"text"},{"type":"codeVoice","code":"removeStyleImage"},{"text":" method. The application can","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"decide whether the image should be kept or removed."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnusedCallback","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StyleImageRemoveUnusedCallback"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapRecorder":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MapRecorder"}],"abstract":[{"text":"MapRecorder provides functions to record and replay API calls of a Map instance.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"These recordings can be used to debug issues which requie multiple steps to reproduce."},{"type":"text","text":" "},{"type":"text","text":"Additionaly, playbacks can be used for performance testing custom scenarios."}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapRecorder"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapRecorder","title":"MapRecorder","url":"\/documentation\/mapboxmaps\/maprecorder"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderFrameStarted":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"map"},{"type":"text","text":" started rendering a frame."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"RenderFrameStarted"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameStarted","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"RenderFrameStarted","kind":"identifier"}],"title":"RenderFrameStarted","url":"\/documentation\/mapboxmaps\/renderframestarted"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestErrorType":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"RequestErrorType"}],"abstract":[{"type":"text","text":"The enumeration defines the error type that may occur during a resource request."}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"RequestErrorType","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestErrorType","title":"RequestErrorType","url":"\/documentation\/mapboxmaps\/requesterrortype"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceAddedCallback":{"title":"SourceAddedCallback","type":"topic","url":"\/documentation\/mapboxmaps\/sourceaddedcallback","navigatorTitle":[{"text":"SourceAddedCallback","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"text":"The source has been added with ","type":"text"},{"type":"codeVoice","code":"addStyleSource"},{"type":"text","text":" method."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceAddedCallback","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SourceAddedCallback"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMSourceDataLoadedTypeToString(_:)":{"title":"MBMSourceDataLoadedTypeToString(_:)","type":"topic","url":"\/documentation\/mapboxmaps\/mbmsourcedataloadedtypetostring(_:)","navigatorTitle":[{"kind":"identifier","text":"MBMSourceDataLoadedTypeToString"}],"role":"symbol","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMSourceDataLoadedTypeToString(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBMSourceDataLoadedTypeToString"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMSourceDataLoadedType","text":"SourceDataLoadedType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"!","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleImageMissingCallback":{"role":"symbol","navigatorTitle":[{"text":"StyleImageMissingCallback","kind":"identifier"}],"kind":"symbol","title":"StyleImageMissingCallback","type":"topic","url":"\/documentation\/mapboxmaps\/styleimagemissingcallback","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageMissingCallback","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StyleImageMissingCallback"}],"abstract":[{"type":"text","text":"A style needs an image that is missing from the sprite sheet. This event is"},{"type":"text","text":" "},{"type":"text","text":"emitted when the "},{"type":"codeVoice","code":"map"},{"type":"text","text":" renders visible tiles, and one of the required images"},{"text":" ","type":"text"},{"type":"text","text":"is missing in the sprite sheet. The event observer has to provide the missing"},{"type":"text","text":" "},{"type":"text","text":"image by calling the "},{"code":"addStyleImage","type":"codeVoice"},{"text":" method.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMMapLoadingErrorTypeToString(_:)":{"title":"MBMMapLoadingErrorTypeToString(_:)","type":"topic","url":"\/documentation\/mapboxmaps\/mbmmaploadingerrortypetostring(_:)","navigatorTitle":[{"text":"MBMMapLoadingErrorTypeToString","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapLoadingErrorTypeToString(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"MBMMapLoadingErrorTypeToString","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMMapLoadingErrorType","text":"MapLoadingErrorType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleDataLoadedCallback":{"role":"symbol","navigatorTitle":[{"text":"StyleDataLoadedCallback","kind":"identifier"}],"kind":"symbol","title":"StyleDataLoadedCallback","type":"topic","url":"\/documentation\/mapboxmaps\/styledataloadedcallback","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedCallback","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"StyleDataLoadedCallback"}],"abstract":[{"text":"The style data has been loaded.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Alias","op":"replace"},{"path":"\/metadata\/title","value":"MBMRenderFrameStartedCallback","op":"replace"},{"value":"typealias","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBMRenderFrameStartedCallback"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"MBMRenderFrameStartedCallback","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Symbols","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapRecorder","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeatureExtensionValue","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Size","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackError-swift.class","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestErrorType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapLoadingErrorTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRenderModeTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestDataSourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestErrorTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestLoadingMethodTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestPriorityTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestPriorityTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestResourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMResponseSourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMSourceDataLoadedTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStyleDataLoadedTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMTileStoreUsageModeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraChangedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GenericEventCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinishedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequestCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceAddedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceRemovedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageMissingCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapIdleCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnusedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TransitionOptions-swift.class"],"anchor":"Symbols"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typedef"},{"text":" ","kind":"text"},{"text":"void (^)(MBMRenderFrameStarted *)","kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$objc(cs)MBMRenderFrameStarted)"},{"kind":"text","text":" "},{"text":"MBMRenderFrameStartedCallback","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"MBMRequestPriorityTypeToString","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestPriorityTypeToString(_:)\/title"},{"value":[{"text":"MBMRequestPriorityTypeToString","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestPriorityTypeToString(_:)\/fragments"},{"value":"MBMMapLoadingErrorCallback","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorCallback\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorCallback\/fragments","value":[{"text":"MBMMapLoadingErrorCallback","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorCallback\/navigatorTitle","value":[{"kind":"identifier","text":"MBMMapLoadingErrorCallback"}]},{"value":"MBMGenericEventCallback","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEventCallback\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEventCallback\/fragments","value":[{"text":"MBMGenericEventCallback","kind":"identifier"}]},{"op":"replace","value":[{"text":"MBMGenericEventCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEventCallback\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeatureExtensionValue\/title","value":"MBMFeatureExtensionValue"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeatureExtensionValue\/fragments","value":[{"kind":"identifier","text":"MBMFeatureExtensionValue"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeatureExtensionValue\/navigatorTitle","value":[{"text":"MBMFeatureExtensionValue","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Size\/title","value":"MBMSize","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Size\/fragments","op":"replace","value":[{"text":"MBMSize","kind":"identifier"}]},{"value":[{"text":"MBMSize","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Size\/navigatorTitle","op":"replace"},{"value":"MBMTileStoreUsageModeToString","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMTileStoreUsageModeToString(_:)\/title","op":"replace"},{"value":[{"text":"MBMTileStoreUsageModeToString","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMTileStoreUsageModeToString(_:)\/fragments","op":"replace"},{"value":"MBMStylePackError","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackError-swift.class\/title"},{"op":"replace","value":[{"text":"MBMStylePackError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackError-swift.class\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MBMStylePackError"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackError-swift.class\/navigatorTitle"},{"value":"MBMStyleDataLoadedTypeToString","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMStyleDataLoadedTypeToString(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMStyleDataLoadedTypeToString(_:)\/fragments","value":[{"text":"MBMStyleDataLoadedTypeToString","kind":"identifier"}]},{"value":"MBMRequestResourceTypeToString","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestResourceTypeToString(_:)\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestResourceTypeToString(_:)\/fragments","value":[{"text":"MBMRequestResourceTypeToString","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestLoadingMethodTypeToString(_:)\/title","value":"MBMRequestLoadingMethodTypeToString"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestLoadingMethodTypeToString(_:)\/fragments","value":[{"text":"MBMRequestLoadingMethodTypeToString","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequestCallback\/title","value":"MBMResourceRequestCallback","op":"replace"},{"value":[{"kind":"identifier","text":"MBMResourceRequestCallback"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequestCallback\/fragments","op":"replace"},{"value":[{"text":"MBMResourceRequestCallback","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequestCallback\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChangedCallback\/title","value":"MBMCameraChangedCallback","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChangedCallback\/fragments","value":[{"kind":"identifier","text":"MBMCameraChangedCallback"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChangedCallback\/navigatorTitle","op":"replace","value":[{"text":"MBMCameraChangedCallback","kind":"identifier"}]},{"op":"replace","value":"MBMRequestErrorTypeToString","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestErrorTypeToString(_:)\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestErrorTypeToString(_:)\/fragments","value":[{"text":"MBMRequestErrorTypeToString","kind":"identifier"}],"op":"replace"},{"value":"MBMSourceRemovedCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceRemovedCallback\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceRemovedCallback\/fragments","op":"replace","value":[{"text":"MBMSourceRemovedCallback","kind":"identifier"}]},{"value":[{"text":"MBMSourceRemovedCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceRemovedCallback\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestDataSourceTypeToString(_:)\/title","op":"replace","value":"MBMRequestDataSourceTypeToString"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestDataSourceTypeToString(_:)\/fragments","value":[{"text":"MBMRequestDataSourceTypeToString","kind":"identifier"}]},{"op":"replace","value":"MBMResponseSourceTypeToString","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMResponseSourceTypeToString(_:)\/title"},{"value":[{"text":"MBMResponseSourceTypeToString","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMResponseSourceTypeToString(_:)\/fragments"},{"value":"MBMStyleLoadedCallback","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoadedCallback\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoadedCallback\/fragments","value":[{"text":"MBMStyleLoadedCallback","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoadedCallback\/navigatorTitle","value":[{"kind":"identifier","text":"MBMStyleLoadedCallback"}]},{"value":"MBMSourceDataLoadedCallback","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedCallback\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedCallback\/fragments","value":[{"text":"MBMSourceDataLoadedCallback","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MBMSourceDataLoadedCallback"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedCallback\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinishedCallback\/title","value":"MBMRenderFrameFinishedCallback"},{"op":"replace","value":[{"text":"MBMRenderFrameFinishedCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinishedCallback\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinishedCallback\/navigatorTitle","value":[{"text":"MBMRenderFrameFinishedCallback","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRenderModeTypeToString(_:)\/title","value":"MBMRenderModeTypeToString"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRenderModeTypeToString(_:)\/fragments","value":[{"text":"MBMRenderModeTypeToString","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadedCallback\/title","value":"MBMMapLoadedCallback"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadedCallback\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMMapLoadedCallback"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadedCallback\/navigatorTitle","value":[{"kind":"identifier","text":"MBMMapLoadedCallback"}],"op":"replace"},{"op":"replace","value":"MBMTransitionOptions","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TransitionOptions-swift.class\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TransitionOptions-swift.class\/fragments","value":[{"kind":"identifier","text":"MBMTransitionOptions"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TransitionOptions-swift.class\/navigatorTitle","value":[{"kind":"identifier","text":"MBMTransitionOptions"}]},{"value":"MBMRenderFrameStartedCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameStartedCallback\/title","op":"replace"},{"value":[{"text":"MBMRenderFrameStartedCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameStartedCallback\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameStartedCallback\/navigatorTitle","value":[{"text":"MBMRenderFrameStartedCallback","kind":"identifier"}],"op":"replace"},{"value":"MBMMapIdleCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdleCallback\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBMMapIdleCallback"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdleCallback\/fragments"},{"value":[{"kind":"identifier","text":"MBMMapIdleCallback"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdleCallback\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnusedCallback\/title","op":"replace","value":"MBMStyleImageRemoveUnusedCallback"},{"op":"replace","value":[{"kind":"identifier","text":"MBMStyleImageRemoveUnusedCallback"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnusedCallback\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MBMStyleImageRemoveUnusedCallback"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnusedCallback\/navigatorTitle"},{"value":"MBMMapRecorder","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapRecorder\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapRecorder\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMMapRecorder"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapRecorder\/navigatorTitle","value":[{"text":"MBMMapRecorder","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameStarted\/title","value":"MBMRenderFrameStarted","op":"replace"},{"value":[{"kind":"identifier","text":"MBMRenderFrameStarted"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameStarted\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MBMRenderFrameStarted"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameStarted\/navigatorTitle","op":"replace"},{"value":"MBMRequestErrorType","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestErrorType\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestErrorType\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMRequestErrorType"}]},{"value":[{"kind":"identifier","text":"MBMRequestErrorType"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestErrorType\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAddedCallback\/title","value":"MBMSourceAddedCallback"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAddedCallback\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMSourceAddedCallback"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAddedCallback\/navigatorTitle","value":[{"text":"MBMSourceAddedCallback","kind":"identifier"}]},{"value":"MBMSourceDataLoadedTypeToString","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMSourceDataLoadedTypeToString(_:)\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBMSourceDataLoadedTypeToString"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMSourceDataLoadedTypeToString(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageMissingCallback\/title","value":"MBMStyleImageMissingCallback"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageMissingCallback\/fragments","value":[{"text":"MBMStyleImageMissingCallback","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageMissingCallback\/navigatorTitle","op":"replace","value":[{"text":"MBMStyleImageMissingCallback","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMMapLoadingErrorTypeToString(_:)\/title","op":"replace","value":"MBMMapLoadingErrorTypeToString"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMMapLoadingErrorTypeToString(_:)\/fragments","value":[{"kind":"identifier","text":"MBMMapLoadingErrorTypeToString"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedCallback\/title","value":"MBMStyleDataLoadedCallback","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedCallback\/fragments","value":[{"kind":"identifier","text":"MBMStyleDataLoadedCallback"}],"op":"replace"},{"op":"replace","value":[{"text":"MBMStyleDataLoadedCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedCallback\/navigatorTitle"}]}]}