{"variants":[{"paths":["\/documentation\/mapboxmaps\/requestresourcetype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/requestresourcetype"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events"]]},"sections":[],"seeAlsoSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderModeType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestLoadingMethodType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestPriorityType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestDataSourceType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResponseSourceType"],"title":"Event payload","generated":true,"anchor":"Event-payload"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"RequestResourceType","kind":"identifier"}],"title":"RequestResourceType","modules":[{"name":"MapboxMaps"}],"roleHeading":"Enumeration","navigatorTitle":[{"kind":"identifier","text":"RequestResourceType"}],"role":"symbol","externalID":"c:@E@MBMRequestResourceType","symbolKind":"enum"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"RequestResourceType","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The enumeration defines the type of resource requested by the "},{"code":"map","type":"codeVoice"},{"type":"text","text":"."}],"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/s15BitwiseCopyableP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH","doc:\/\/com.mapbox.MapboxMaps\/SY","doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"],"type":"conformsTo","kind":"relationships"}],"topicSections":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType\/glyphs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType\/image","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType\/model","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType\/source","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType\/spriteImage","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType\/spriteJSON","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType\/style","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType\/tile","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType\/unknown"],"generated":true},{"title":"Initializers","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType\/init(rawValue:)"],"generated":true,"anchor":"Initializers"},{"title":"Default Implementations","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType\/Equatable-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType\/RawRepresentable-Implementations"],"generated":true,"anchor":"Default-Implementations"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","title":"MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"url":"\/documentation\/mapboxmaps","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestResourceType/tile":{"kind":"symbol","abstract":[{"type":"text","text":"The resource type is a tile, for example, a vector or raster tile."}],"title":"RequestResourceType.tile","type":"topic","navigatorTitle":[{"text":"MBMRequestResourceTypeTile","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tile"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType\/tile","url":"\/documentation\/mapboxmaps\/requestresourcetype\/tile"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleDataLoadedType":{"url":"\/documentation\/mapboxmaps\/styledataloadedtype","abstract":[{"text":"The enumeration defines the type of loaded style data.","type":"text"}],"navigatorTitle":[{"text":"StyleDataLoadedType","kind":"identifier"}],"title":"StyleDataLoadedType","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StyleDataLoadedType"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceDataLoadedType":{"url":"\/documentation\/mapboxmaps\/sourcedataloadedtype","abstract":[{"type":"text","text":"The enumeration defines the type of loaded source data."}],"navigatorTitle":[{"kind":"identifier","text":"SourceDataLoadedType"}],"title":"SourceDataLoadedType","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SourceDataLoadedType","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoadingErrorType":{"navigatorTitle":[{"text":"MapLoadingErrorType","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorType","title":"MapLoadingErrorType","abstract":[{"text":"The enumeration defines map loading errors.","type":"text"}],"role":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/maploadingerrortype","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MapLoadingErrorType","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestPriorityType":{"url":"\/documentation\/mapboxmaps\/requestprioritytype","abstract":[{"type":"text","text":"The enumeration defines the priority of a resource request."}],"navigatorTitle":[{"kind":"identifier","text":"RequestPriorityType"}],"title":"RequestPriorityType","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestPriorityType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RequestPriorityType"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/SY":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SY","title":"Swift.RawRepresentable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestResourceType/source":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"source"}],"abstract":[{"type":"text","text":"The resource type is a source document, for example, TileJSON."}],"title":"RequestResourceType.source","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType\/source","url":"\/documentation\/mapboxmaps\/requestresourcetype\/source","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MBMRequestResourceTypeSource"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestResourceType/model":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"model"}],"navigatorTitle":[{"kind":"identifier","text":"MBMRequestResourceTypeModel"}],"kind":"symbol","abstract":[{"type":"text","text":"The resource type is a 3D model."}],"title":"RequestResourceType.model","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType\/model","url":"\/documentation\/mapboxmaps\/requestresourcetype\/model"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestResourceType/Equatable-Implementations":{"title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType\/Equatable-Implementations","type":"topic","role":"collectionGroup","kind":"article","url":"\/documentation\/mapboxmaps\/requestresourcetype\/equatable-implementations"},"doc://com.mapbox.MapboxMaps/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestResourceType/RawRepresentable-Implementations":{"role":"collectionGroup","kind":"article","abstract":[],"title":"RawRepresentable Implementations","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType\/RawRepresentable-Implementations","url":"\/documentation\/mapboxmaps\/requestresourcetype\/rawrepresentable-implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestLoadingMethodType":{"abstract":[{"type":"text","text":"The enumeration defines the method used to make a resource request."}],"role":"symbol","title":"RequestLoadingMethodType","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestLoadingMethodType","kind":"symbol","navigatorTitle":[{"text":"RequestLoadingMethodType","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/requestloadingmethodtype","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"RequestLoadingMethodType","kind":"identifier"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestDataSourceType":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"The enumeration defines the type of data source."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestDataSourceType","url":"\/documentation\/mapboxmaps\/requestdatasourcetype","navigatorTitle":[{"text":"RequestDataSourceType","kind":"identifier"}],"title":"RequestDataSourceType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RequestDataSourceType"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"type":"topic","abstract":[{"text":"The simplified diagram of the events emitted by the map is displayed below.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","kind":"article","url":"\/documentation\/mapboxmaps\/events","title":"Map events","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestResourceType/spriteJSON":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType\/spriteJSON","url":"\/documentation\/mapboxmaps\/requestresourcetype\/spritejson","abstract":[{"text":"The resource type is a sprite JSON metadata used to create a sprite sheet.","type":"text"}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"spriteJSON"}],"navigatorTitle":[{"kind":"identifier","text":"MBMRequestResourceTypeSpriteJSON"}],"title":"RequestResourceType.spriteJSON"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestResourceType/spriteImage":{"url":"\/documentation\/mapboxmaps\/requestresourcetype\/spriteimage","title":"RequestResourceType.spriteImage","abstract":[{"type":"text","text":"The resource type is a sprite image used together with the sprite JSON"},{"type":"text","text":" "},{"type":"text","text":"definition to create a sprite sheet."}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType\/spriteImage","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"spriteImage","kind":"identifier"}],"navigatorTitle":[{"text":"MBMRequestResourceTypeSpriteImage","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"title":"MapboxMaps Documentation","role":"collection","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"},"doc://com.mapbox.MapboxMaps/s15BitwiseCopyableP":{"title":"Swift.BitwiseCopyable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s15BitwiseCopyableP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestResourceType/glyphs":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"glyphs"}],"abstract":[{"type":"text","text":"The resource type is glyphs used to render text on the map."}],"title":"RequestResourceType.glyphs","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType\/glyphs","url":"\/documentation\/mapboxmaps\/requestresourcetype\/glyphs","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MBMRequestResourceTypeGlyphs"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderModeType":{"abstract":[{"type":"text","text":"The enumeration defines the rendering mode for the rendered frame."}],"role":"symbol","title":"RenderModeType","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderModeType","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"RenderModeType"}],"url":"\/documentation\/mapboxmaps\/rendermodetype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RenderModeType","kind":"identifier"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestResourceType":{"url":"\/documentation\/mapboxmaps\/requestresourcetype","abstract":[{"type":"text","text":"The enumeration defines the type of resource requested by the "},{"code":"map","type":"codeVoice"},{"type":"text","text":"."}],"navigatorTitle":[{"kind":"identifier","text":"RequestResourceType"}],"title":"RequestResourceType","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RequestResourceType","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestResourceType/unknown":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"navigatorTitle":[{"kind":"identifier","text":"MBMRequestResourceTypeUnknown"}],"kind":"symbol","abstract":[{"type":"text","text":"The resource type is unknown."}],"title":"RequestResourceType.unknown","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType\/unknown","url":"\/documentation\/mapboxmaps\/requestresourcetype\/unknown"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestResourceType/image":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"image","kind":"identifier"}],"abstract":[{"type":"text","text":"The resource type is an image, for example, image rendered by the "},{"code":"image","type":"codeVoice"},{"type":"text","text":" style source."}],"title":"RequestResourceType.image","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType\/image","url":"\/documentation\/mapboxmaps\/requestresourcetype\/image","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MBMRequestResourceTypeImage"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/SH":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","title":"Swift.Hashable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResponseSourceType":{"abstract":[{"type":"text","text":"The enumeration defines the source type that provides the requested resource."}],"role":"symbol","title":"ResponseSourceType","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResponseSourceType","kind":"symbol","navigatorTitle":[{"text":"ResponseSourceType","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/responsesourcetype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ResponseSourceType","kind":"identifier"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestResourceType/init(rawValue:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"title":"init(rawValue:)","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType\/init(rawValue:)","url":"\/documentation\/mapboxmaps\/requestresourcetype\/init(rawvalue:)","type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestResourceType/style":{"title":"RequestResourceType.style","type":"topic","url":"\/documentation\/mapboxmaps\/requestresourcetype\/style","navigatorTitle":[{"kind":"identifier","text":"MBMRequestResourceTypeStyle"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The resource type is a style document."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType\/style","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"style"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"MBMRequestResourceType","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MBMRequestResourceType"}]},{"op":"replace","value":[{"kind":"identifier","text":"MBMRequestResourceType"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType\/glyphs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType\/image","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType\/model","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType\/source","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType\/spriteImage","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType\/spriteJSON","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType\/style","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType\/tile","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType\/unknown"],"generated":true}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","value":[{"title":"Event payload","anchor":"Event-payload","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderModeType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestLoadingMethodType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestPriorityType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestDataSourceType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResponseSourceType"],"generated":true}],"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MBMRequestResourceType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestResourceType~1tile\/title","value":"MBMRequestResourceTypeTile"},{"value":[{"kind":"identifier","text":"MBMRequestResourceTypeTile"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestResourceType~1tile\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedType\/title","value":"MBMStyleDataLoadedType"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedType\/fragments","value":[{"text":"MBMStyleDataLoadedType","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"MBMStyleDataLoadedType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedType\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedType\/title","value":"MBMSourceDataLoadedType"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedType\/fragments","value":[{"text":"MBMSourceDataLoadedType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedType\/navigatorTitle","value":[{"kind":"identifier","text":"MBMSourceDataLoadedType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorType\/title","value":"MBMMapLoadingErrorType"},{"value":[{"kind":"identifier","text":"MBMMapLoadingErrorType"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorType\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorType\/navigatorTitle","value":[{"kind":"identifier","text":"MBMMapLoadingErrorType"}],"op":"replace"},{"value":"MBMRequestPriorityType","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestPriorityType\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestPriorityType\/fragments","value":[{"kind":"identifier","text":"MBMRequestPriorityType"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestPriorityType\/navigatorTitle","value":[{"text":"MBMRequestPriorityType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestResourceType~1source\/title","value":"MBMRequestResourceTypeSource","op":"replace"},{"value":[{"kind":"identifier","text":"MBMRequestResourceTypeSource"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestResourceType~1source\/fragments","op":"replace"},{"value":"MBMRequestResourceTypeModel","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestResourceType~1model\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestResourceType~1model\/fragments","value":[{"text":"MBMRequestResourceTypeModel","kind":"identifier"}]},{"value":"MBMRequestLoadingMethodType","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestLoadingMethodType\/title","op":"replace"},{"op":"replace","value":[{"text":"MBMRequestLoadingMethodType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestLoadingMethodType\/fragments"},{"value":[{"text":"MBMRequestLoadingMethodType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestLoadingMethodType\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestDataSourceType\/title","value":"MBMRequestDataSourceType","op":"replace"},{"value":[{"kind":"identifier","text":"MBMRequestDataSourceType"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestDataSourceType\/fragments"},{"value":[{"kind":"identifier","text":"MBMRequestDataSourceType"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestDataSourceType\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestResourceType~1spriteJSON\/title","value":"MBMRequestResourceTypeSpriteJSON","op":"replace"},{"value":[{"text":"MBMRequestResourceTypeSpriteJSON","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestResourceType~1spriteJSON\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestResourceType~1spriteImage\/title","value":"MBMRequestResourceTypeSpriteImage"},{"value":[{"kind":"identifier","text":"MBMRequestResourceTypeSpriteImage"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestResourceType~1spriteImage\/fragments"},{"value":"MBMRequestResourceTypeGlyphs","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestResourceType~1glyphs\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestResourceType~1glyphs\/fragments","value":[{"kind":"identifier","text":"MBMRequestResourceTypeGlyphs"}]},{"value":"MBMRenderModeType","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderModeType\/title"},{"value":[{"text":"MBMRenderModeType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderModeType\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderModeType\/navigatorTitle","op":"replace","value":[{"text":"MBMRenderModeType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestResourceType\/title","value":"MBMRequestResourceType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestResourceType\/fragments","value":[{"kind":"identifier","text":"MBMRequestResourceType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestResourceType\/navigatorTitle","value":[{"text":"MBMRequestResourceType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestResourceType~1unknown\/title","value":"MBMRequestResourceTypeUnknown","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestResourceType~1unknown\/fragments","value":[{"text":"MBMRequestResourceTypeUnknown","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestResourceType~1image\/title","value":"MBMRequestResourceTypeImage","op":"replace"},{"value":[{"text":"MBMRequestResourceTypeImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestResourceType~1image\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResponseSourceType\/title","op":"replace","value":"MBMResponseSourceType"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResponseSourceType\/fragments","value":[{"text":"MBMResponseSourceType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResponseSourceType\/navigatorTitle","value":[{"text":"MBMResponseSourceType","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestResourceType~1style\/title","value":"MBMRequestResourceTypeStyle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestResourceType~1style\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMRequestResourceTypeStyle"}]}]}]}