{"metadata":{"externalID":"c:objc(cs)MBXTileRegionLoadOptions(py)geometry","roleHeading":"Instance Property","modules":[{"name":"MapboxCommon"}],"fragments":[{"text":"geometry","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"geometry","kind":"identifier"}],"symbolKind":"property","title":"geometry"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXGeometry","text":"MBXGeometry"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"geometry"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"If provided, updates the tile region’s associated geometry i.e. geometry,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"which is used in the tile cover algorithm to find out a set of tiles to be loaded"},{"text":" ","type":"text"},{"text":"for the tile region.","type":"text"}]}],"kind":"content"}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXTileRegionLoadOptions\/geometry","interfaceLanguage":"occ"},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","abstract":[{"type":"text","text":"The tile region’s associated geometry."}],"variants":[{"paths":["\/documentation\/mapboxcommon\/mbxtileregionloadoptions\/geometry"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"type":"topic","kind":"article","abstract":[],"title":"TileStore APIs","url":"\/documentation\/mapboxmaps\/tilestore-apis","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","kind":"article","url":"\/documentation\/overview","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"url":"\/documentation\/mapboxmaps","kind":"symbol","title":"MapboxMaps","role":"collection","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Geometry":{"role":"symbol","url":"\/documentation\/mapboxcommon\/geometry","navigatorTitle":[{"text":"Geometry","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[],"title":"Geometry","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Geometry"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXTileRegionLoadOptions/geometry":{"type":"topic","title":"geometry","abstract":[{"text":"The tile region’s associated geometry.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXTileRegionLoadOptions\/geometry","fragments":[{"kind":"identifier","text":"geometry"}],"role":"symbol","kind":"symbol","url":"\/documentation\/mapboxcommon\/mbxtileregionloadoptions\/geometry"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadOptions":{"url":"\/documentation\/mapboxcommon\/tileregionloadoptions","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TileRegionLoadOptions"}],"navigatorTitle":[{"text":"TileRegionLoadOptions","kind":"identifier"}],"abstract":[{"text":"Describes the tile region load option values.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions","role":"symbol","kind":"symbol","title":"TileRegionLoadOptions","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry\/title","op":"replace","value":"MBXGeometry"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry\/fragments","value":[{"kind":"identifier","text":"MBXGeometry"}]},{"op":"replace","value":[{"text":"MBXGeometry","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry\/navigatorTitle"},{"value":"MBXTileRegionLoadOptions","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/title"},{"value":[{"text":"MBXTileRegionLoadOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/fragments","op":"replace"},{"op":"replace","value":[{"text":"MBXTileRegionLoadOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}