{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/setFilePathForPath(_:)"},"abstract":[{"type":"text","text":"Set the folder path for file logs."}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/persistentlogconfiguration\/setfilepathforpath(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/persistentlogconfiguration\/setfilepathforpath(_:)"]}],"metadata":{"modules":[{"name":"MapboxCommon"}],"navigatorTitle":[{"text":"setFilePathForPath:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setFilePathForPath","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"roleHeading":"Type Method","symbolKind":"method","title":"setFilePathForPath(_:)","externalID":"c:objc(cs)MBXPersistentLogConfiguration(cm)setFilePathForPath:"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setFilePathForPath","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"path","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"parameters":[{"name":"path","content":[{"inlineContent":[{"type":"text","text":"String path to the folder for storing the logs."},{"type":"text","text":" "},{"type":"text","text":"Default is “\/Logs\/mapbox.log” in application data path"}],"type":"paragraph"}]}],"kind":"parameters"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PersistentLogConfiguration/setFilePathForPath(_:)":{"title":"setFilePathForPath(_:)","type":"topic","url":"\/documentation\/mapboxcommon\/persistentlogconfiguration\/setfilepathforpath(_:)","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/setFilePathForPath(_:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setFilePathForPath","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"setFilePathForPath:","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Set the folder path for file logs.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","abstract":[],"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","type":"topic","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"type":"topic","title":"MapboxCommon","role":"collection","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","url":"\/documentation\/mapboxcommon","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PersistentLogConfiguration":{"kind":"symbol","role":"symbol","title":"PersistentLogConfiguration","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration","navigatorTitle":[{"text":"PersistentLogConfiguration","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/persistentlogconfiguration","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PersistentLogConfiguration","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"setFilePathForPath:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"setFilePathForPath:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"setFilePathForPath:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"path","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"String path to the folder for storing the logs."},{"type":"text","text":" "},{"type":"text","text":"Default is “\/Logs\/mapbox.log” in application data path"}]}],"name":"path"}]}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1setFilePathForPath(_:)\/title","value":"setFilePathForPath:"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1setFilePathForPath(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"setFilePathForPath:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration\/title","value":"MBXPersistentLogConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration\/fragments","value":[{"text":"MBXPersistentLogConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"MBXPersistentLogConfiguration"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}