{"abstract":[{"type":"text","text":"This event is emitted whenever the visible viewport changes its size"},{"type":"text","text":" "},{"text":"due to the invocation of the ","type":"text"},{"type":"codeVoice","code":"setSize"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"setBounds"},{"type":"text","text":" methods or when"},{"type":"text","text":" "},{"text":"the camera is modified by calling camera methods. The event is emitted","type":"text"},{"text":" ","type":"text"},{"text":"synchronously so that an updated camera state can be fetched immediately.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/camerachangedcallback"]},{"paths":["\/documentation\/mapboxmaps\/camerachangedcallback"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraChangedCallback"},{"kind":"text","text":" = ("},{"kind":"typeIdentifier","text":"CameraChanged","preciseIdentifier":"c:objc(cs)MBMCameraChanged","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraChanged"},{"kind":"text","text":") -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraChangedCallback","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMapsInternal"]]},"metadata":{"role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraChangedCallback","kind":"identifier"}],"roleHeading":"Type Alias","modules":[{"name":"MapboxMaps"}],"externalID":"c:MBMCameraChangedCallback.h@T@MBMCameraChangedCallback","symbolKind":"typealias","navigatorTitle":[{"kind":"identifier","text":"CameraChangedCallback"}],"title":"CameraChangedCallback"},"seeAlsoSections":[{"anchor":"Symbols","title":"Symbols","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapRecorder","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeatureExtensionValue","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Size","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackError-swift.class","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestErrorType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapLoadingErrorTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRenderModeTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestDataSourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestErrorTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestLoadingMethodTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestPriorityTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestPriorityTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestResourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMResponseSourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMSourceDataLoadedTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStyleDataLoadedTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMTileStoreUsageModeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GenericEventCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinishedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameStartedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequestCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceAddedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceRemovedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageMissingCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapIdleCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnusedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TransitionOptions-swift.class"]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleLoadedCallback":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleLoadedCallback","abstract":[{"type":"text","text":"The requested style has been fully loaded, including specified sprite, and sources’ metadata."}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/styleloadedcallback","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StyleLoadedCallback"}],"title":"StyleLoadedCallback","navigatorTitle":[{"text":"StyleLoadedCallback","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMResponseSourceTypeToString(_:)":{"title":"MBMResponseSourceTypeToString(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBMResponseSourceTypeToString"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@MBMResponseSourceType","text":"ResponseSourceType","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBMResponseSourceTypeToString"}],"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMResponseSourceTypeToString(_:)","type":"topic","url":"\/documentation\/mapboxmaps\/mbmresponsesourcetypetostring(_:)","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoadedCallback":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadedCallback","abstract":[{"text":"The style has been fully loaded, and the ","type":"text"},{"type":"codeVoice","code":"map"},{"type":"text","text":" has rendered all visible tiles."},{"text":" ","type":"text"},{"text":"The event will be emitted only once for the current style. If it is required to","type":"text"},{"text":" ","type":"text"},{"text":"continuously observe an event where all the necessary resources are loaded or rendered,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"please check the following events: "},{"code":"MapIdle","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"StyleDataLoaded"},{"text":", and ","type":"text"},{"code":"RenderFrameFinished","type":"codeVoice"},{"type":"text","text":"."}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/maploadedcallback","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"MapLoadedCallback","kind":"identifier"}],"title":"MapLoadedCallback","navigatorTitle":[{"kind":"identifier","text":"MapLoadedCallback"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMStyleDataLoadedTypeToString(_:)":{"title":"MBMStyleDataLoadedTypeToString(_:)","type":"topic","url":"\/documentation\/mapboxmaps\/mbmstyledataloadedtypetostring(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBMStyleDataLoadedTypeToString"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"StyleDataLoadedType","preciseIdentifier":"c:@E@MBMStyleDataLoadedType"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"!","kind":"text"}],"abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"MBMStyleDataLoadedTypeToString","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStyleDataLoadedTypeToString(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleDataLoadedCallback":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedCallback","title":"StyleDataLoadedCallback","role":"symbol","navigatorTitle":[{"text":"StyleDataLoadedCallback","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StyleDataLoadedCallback"}],"url":"\/documentation\/mapboxmaps\/styledataloadedcallback","type":"topic","abstract":[{"type":"text","text":"The style data has been loaded."}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRequestResourceTypeToString(_:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestResourceTypeToString(_:)","abstract":[],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/mbmrequestresourcetypetostring(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBMRequestResourceTypeToString"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMRequestResourceType","text":"RequestResourceType"},{"kind":"text","text":") -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}],"title":"MBMRequestResourceTypeToString(_:)","navigatorTitle":[{"kind":"identifier","text":"MBMRequestResourceTypeToString"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoadingErrorCallback":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorCallback","title":"MapLoadingErrorCallback","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MapLoadingErrorCallback"}],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"MapLoadingErrorCallback","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/maploadingerrorcallback","type":"topic","abstract":[{"type":"text","text":"Describes an error that has occurred while loading the "},{"code":"map","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraChanged":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraChanged"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraChanged","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CameraChanged"}],"role":"symbol","abstract":[{"type":"text","text":"This event is emitted whenever the visible viewport changes its size"},{"type":"text","text":" "},{"type":"text","text":"due to the invocation of the "},{"type":"codeVoice","code":"setSize"},{"type":"text","text":" and "},{"type":"codeVoice","code":"setBounds"},{"type":"text","text":" methods or when"},{"text":" ","type":"text"},{"text":"the camera is modified by calling camera methods. The event is emitted","type":"text"},{"type":"text","text":" "},{"text":"synchronously so that an updated camera state can be read immediately.","type":"text"}],"url":"\/documentation\/mapboxmaps\/camerachanged","title":"CameraChanged","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRequestDataSourceTypeToString(_:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestDataSourceTypeToString(_:)","abstract":[],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/mbmrequestdatasourcetypetostring(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"MBMRequestDataSourceTypeToString","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@MBMRequestDataSourceType","kind":"typeIdentifier","text":"RequestDataSourceType"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"title":"MBMRequestDataSourceTypeToString(_:)","navigatorTitle":[{"kind":"identifier","text":"MBMRequestDataSourceTypeToString"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestErrorType":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"RequestErrorType","kind":"identifier"}],"abstract":[{"text":"The enumeration defines the error type that may occur during a resource request.","type":"text"}],"title":"RequestErrorType","navigatorTitle":[{"kind":"identifier","text":"RequestErrorType"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestErrorType","url":"\/documentation\/mapboxmaps\/requesterrortype","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRenderModeTypeToString(_:)":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"MBMRenderModeTypeToString","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@MBMRenderModeType","text":"RenderModeType","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"title":"MBMRenderModeTypeToString(_:)","navigatorTitle":[{"kind":"identifier","text":"MBMRenderModeTypeToString"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRenderModeTypeToString(_:)","url":"\/documentation\/mapboxmaps\/mbmrendermodetypetostring(_:)","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceDataLoadedCallback":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedCallback","title":"SourceDataLoadedCallback","role":"symbol","navigatorTitle":[{"text":"SourceDataLoadedCallback","kind":"identifier"}],"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceDataLoadedCallback"}],"url":"\/documentation\/mapboxmaps\/sourcedataloadedcallback","type":"topic","abstract":[{"text":"The ","type":"text"},{"code":"SourceDataLoaded","type":"codeVoice"},{"text":" event is emitted when source data is loaded.","type":"text"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","title":"MapboxMaps","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FeatureExtensionValue":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeatureExtensionValue","title":"FeatureExtensionValue","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FeatureExtensionValue"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FeatureExtensionValue","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/featureextensionvalue","type":"topic","abstract":[{"text":"A value or a collection of a feature extension.","type":"text"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePackError-swift.class":{"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"StylePackError","kind":"identifier"}],"abstract":[{"text":"Describes a style package load request error.","type":"text"}],"title":"StylePackError","navigatorTitle":[{"kind":"identifier","text":"StylePackError"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackError-swift.class","url":"\/documentation\/mapboxmaps\/stylepackerror-swift.class","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceRemovedCallback":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceRemovedCallback"}],"abstract":[{"type":"text","text":"The source has been removed with "},{"type":"codeVoice","code":"removeStyleSource"},{"text":" method.","type":"text"}],"title":"SourceRemovedCallback","navigatorTitle":[{"text":"SourceRemovedCallback","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceRemovedCallback","url":"\/documentation\/mapboxmaps\/sourceremovedcallback","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapRecorder":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapRecorder","title":"MapRecorder","role":"symbol","navigatorTitle":[{"text":"MapRecorder","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapRecorder"}],"url":"\/documentation\/mapboxmaps\/maprecorder","type":"topic","abstract":[{"text":"MapRecorder provides functions to record and replay API calls of a Map instance.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"These recordings can be used to debug issues which requie multiple steps to reproduce."},{"text":" ","type":"text"},{"text":"Additionaly, playbacks can be used for performance testing custom scenarios.","type":"text"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraChangedCallback":{"navigatorTitle":[{"kind":"identifier","text":"CameraChangedCallback"}],"type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraChangedCallback","kind":"identifier"}],"title":"CameraChangedCallback","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"This event is emitted whenever the visible viewport changes its size"},{"text":" ","type":"text"},{"type":"text","text":"due to the invocation of the "},{"type":"codeVoice","code":"setSize"},{"text":" and ","type":"text"},{"code":"setBounds","type":"codeVoice"},{"text":" methods or when","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"the camera is modified by calling camera methods. The event is emitted"},{"type":"text","text":" "},{"type":"text","text":"synchronously so that an updated camera state can be fetched immediately."}],"url":"\/documentation\/mapboxmaps\/camerachangedcallback","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraChangedCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRequestPriorityTypeToString(_:)":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"MBMRequestPriorityTypeToString","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMRequestPriorityType","text":"RequestPriorityType"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"abstract":[],"title":"MBMRequestPriorityTypeToString(_:)","navigatorTitle":[{"kind":"identifier","text":"MBMRequestPriorityTypeToString"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestPriorityTypeToString(_:)","url":"\/documentation\/mapboxmaps\/mbmrequestprioritytypetostring(_:)","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderFrameFinishedCallback":{"type":"topic","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RenderFrameFinishedCallback"}],"abstract":[{"text":"The ","type":"text"},{"code":"map","type":"codeVoice"},{"type":"text","text":" finished rendering a frame."}],"title":"RenderFrameFinishedCallback","navigatorTitle":[{"kind":"identifier","text":"RenderFrameFinishedCallback"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinishedCallback","url":"\/documentation\/mapboxmaps\/renderframefinishedcallback","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderFrameStartedCallback":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameStartedCallback","abstract":[{"text":"The ","type":"text"},{"code":"map","type":"codeVoice"},{"text":" started rendering a frame.","type":"text"}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/renderframestartedcallback","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"RenderFrameStartedCallback","kind":"identifier"}],"title":"RenderFrameStartedCallback","navigatorTitle":[{"text":"RenderFrameStartedCallback","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMMapLoadingErrorTypeToString(_:)":{"navigatorTitle":[{"kind":"identifier","text":"MBMMapLoadingErrorTypeToString"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBMMapLoadingErrorTypeToString"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"MapLoadingErrorType","preciseIdentifier":"c:@E@MBMMapLoadingErrorType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"!","kind":"text"}],"title":"MBMMapLoadingErrorTypeToString(_:)","kind":"symbol","role":"symbol","abstract":[],"url":"\/documentation\/mapboxmaps\/mbmmaploadingerrortypetostring(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapLoadingErrorTypeToString(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRequestLoadingMethodTypeToString(_:)":{"title":"MBMRequestLoadingMethodTypeToString(_:)","type":"topic","url":"\/documentation\/mapboxmaps\/mbmrequestloadingmethodtypetostring(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBMRequestLoadingMethodTypeToString"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@MBMRequestLoadingMethodType","kind":"typeIdentifier","text":"RequestLoadingMethodType"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBMRequestLoadingMethodTypeToString"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestLoadingMethodTypeToString(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMTileStoreUsageModeToString(_:)":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"MBMTileStoreUsageModeToString","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@MBMTileStoreUsageMode","text":"TileStoreUsageMode","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"!"}],"abstract":[],"title":"MBMTileStoreUsageModeToString(_:)","navigatorTitle":[{"text":"MBMTileStoreUsageModeToString","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMTileStoreUsageModeToString(_:)","url":"\/documentation\/mapboxmaps\/mbmtilestoreusagemodetostring(_:)","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapIdleCallback":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapIdleCallback","kind":"symbol","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"map"},{"type":"text","text":" has entered the idle state. The "},{"code":"map","type":"codeVoice"},{"text":" is idle when there are no ongoing","type":"text"},{"type":"text","text":" "},{"text":"animations, transitions and the ","type":"text"},{"code":"map","type":"codeVoice"},{"type":"text","text":" has rendered all requested non-volatile tiles"},{"text":" ","type":"text"},{"text":"(e.g., live traffic tiles). The event will not be emitted if ","type":"text"},{"type":"codeVoice","code":"setUserAnimationInProgress"},{"type":"text","text":" "},{"text":"and \/ or ","type":"text"},{"code":"setGestureInProgress","type":"codeVoice"},{"text":" is set to ","type":"text"},{"type":"codeVoice","code":"true"},{"text":".","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MapIdleCallback"}],"url":"\/documentation\/mapboxmaps\/mapidlecallback","title":"MapIdleCallback","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapIdleCallback"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GenericEventCallback":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GenericEventCallback","title":"GenericEventCallback","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GenericEventCallback"}],"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GenericEventCallback"}],"url":"\/documentation\/mapboxmaps\/genericeventcallback","type":"topic","abstract":[{"type":"text","text":"Generic event for experimental events."}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleImageRemoveUnusedCallback":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnusedCallback","abstract":[{"type":"text","text":"An image requested by the "},{"code":"map","type":"codeVoice"},{"text":" through the ","type":"text"},{"type":"codeVoice","code":"StyleImageMissing"},{"type":"text","text":" event is no longer"},{"text":" ","type":"text"},{"type":"text","text":"needed and can be removed using the "},{"code":"removeStyleImage","type":"codeVoice"},{"text":" method. The application can","type":"text"},{"text":" ","type":"text"},{"text":"decide whether the image should be kept or removed.","type":"text"}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/styleimageremoveunusedcallback","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"StyleImageRemoveUnusedCallback","kind":"identifier"}],"title":"StyleImageRemoveUnusedCallback","navigatorTitle":[{"text":"StyleImageRemoveUnusedCallback","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRequestErrorTypeToString(_:)":{"type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBMRequestErrorTypeToString"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@MBMRequestErrorType","kind":"typeIdentifier","text":"RequestErrorType"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"abstract":[],"title":"MBMRequestErrorTypeToString(_:)","navigatorTitle":[{"text":"MBMRequestErrorTypeToString","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestErrorTypeToString(_:)","url":"\/documentation\/mapboxmaps\/mbmrequesterrortypetostring(_:)","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResourceRequestCallback":{"navigatorTitle":[{"text":"ResourceRequestCallback","kind":"identifier"}],"type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"ResourceRequestCallback","kind":"identifier"}],"title":"ResourceRequestCallback","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The "},{"code":"ResourceRequest","type":"codeVoice"},{"type":"text","text":" event allows the application to observe resourcerequests"},{"type":"text","text":" "},{"text":"made by a ","type":"text"},{"code":"map","type":"codeVoice"},{"text":" or ","type":"text"},{"code":"map snapshotter","type":"codeVoice"},{"type":"text","text":" object."}],"url":"\/documentation\/mapboxmaps\/resourcerequestcallback","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequestCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceAddedCallback":{"type":"topic","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceAddedCallback"}],"abstract":[{"text":"The source has been added with ","type":"text"},{"code":"addStyleSource","type":"codeVoice"},{"type":"text","text":" method."}],"title":"SourceAddedCallback","navigatorTitle":[{"kind":"identifier","text":"SourceAddedCallback"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceAddedCallback","url":"\/documentation\/mapboxmaps\/sourceaddedcallback","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TransitionOptions-swift.class":{"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TransitionOptions"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"transition options"},{"text":" controls timing for the interpolation between a transitionable style","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"property’s previous value and new value. These can be used to define the style default property"},{"text":" ","type":"text"},{"text":"transition behavior. Also, any transitionable style property may also have its own ","type":"text"},{"code":"-transition","type":"codeVoice"},{"text":" ","type":"text"},{"text":"property that defines specific transition timing for that specific layer property, overriding","type":"text"},{"type":"text","text":" "},{"type":"text","text":"the global transition values."}],"title":"TransitionOptions","navigatorTitle":[{"kind":"identifier","text":"TransitionOptions"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TransitionOptions-swift.class","url":"\/documentation\/mapboxmaps\/transitionoptions-swift.class","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMSourceDataLoadedTypeToString(_:)":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"MBMSourceDataLoadedTypeToString","kind":"identifier"},{"kind":"text","text":"("},{"text":"SourceDataLoadedType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMSourceDataLoadedType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"title":"MBMSourceDataLoadedTypeToString(_:)","navigatorTitle":[{"kind":"identifier","text":"MBMSourceDataLoadedTypeToString"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMSourceDataLoadedTypeToString(_:)","url":"\/documentation\/mapboxmaps\/mbmsourcedataloadedtypetostring(_:)","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleImageMissingCallback":{"title":"StyleImageMissingCallback","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StyleImageMissingCallback"}],"role":"symbol","navigatorTitle":[{"text":"StyleImageMissingCallback","kind":"identifier"}],"abstract":[{"text":"A style needs an image that is missing from the sprite sheet. This event is","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"emitted when the "},{"type":"codeVoice","code":"map"},{"text":" renders visible tiles, and one of the required images","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"is missing in the sprite sheet. The event observer has to provide the missing"},{"text":" ","type":"text"},{"type":"text","text":"image by calling the "},{"code":"addStyleImage","type":"codeVoice"},{"text":" method.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageMissingCallback","type":"topic","url":"\/documentation\/mapboxmaps\/styleimagemissingcallback","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMapsInternal":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMapsInternal","title":"CoreMaps - Internal","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/coremapsinternal","type":"topic","abstract":[{"text":"Maps rendering SDK also known as GL-Native. These are for internal use only.","type":"text"}],"kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","url":"\/documentation\/overview","title":"MapboxMaps Documentation","abstract":[],"kind":"article","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Size":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Size","abstract":[{"text":"Size type.","type":"text"}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/size","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Size"}],"title":"Size","navigatorTitle":[{"text":"Size","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Type Alias","op":"replace"},{"value":"MBMCameraChangedCallback","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"typealias"},{"op":"replace","value":[{"text":"MBMCameraChangedCallback","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"MBMCameraChangedCallback","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"replace","path":"\/seeAlsoSections","value":[{"anchor":"Symbols","generated":true,"title":"Symbols","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapRecorder","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeatureExtensionValue","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Size","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackError-swift.class","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestErrorType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapLoadingErrorTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRenderModeTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestDataSourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestErrorTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestLoadingMethodTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestPriorityTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestPriorityTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestResourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMResponseSourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMSourceDataLoadedTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStyleDataLoadedTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMTileStoreUsageModeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GenericEventCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinishedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameStartedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequestCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceAddedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceRemovedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageMissingCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapIdleCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnusedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TransitionOptions-swift.class"]}]},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"text":"void (^)(MBMCameraChanged *)","kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$objc(cs)MBMCameraChanged)"},{"text":" ","kind":"text"},{"text":"MBMCameraChangedCallback","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoadedCallback\/title","value":"MBMStyleLoadedCallback","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoadedCallback\/fragments","value":[{"text":"MBMStyleLoadedCallback","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoadedCallback\/navigatorTitle","value":[{"text":"MBMStyleLoadedCallback","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMResponseSourceTypeToString(_:)\/title","op":"replace","value":"MBMResponseSourceTypeToString"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMResponseSourceTypeToString(_:)\/fragments","value":[{"text":"MBMResponseSourceTypeToString","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"MBMMapLoadedCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadedCallback\/title"},{"value":[{"text":"MBMMapLoadedCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadedCallback\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadedCallback\/navigatorTitle","value":[{"text":"MBMMapLoadedCallback","kind":"identifier"}],"op":"replace"},{"value":"MBMStyleDataLoadedTypeToString","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMStyleDataLoadedTypeToString(_:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMStyleDataLoadedTypeToString(_:)\/fragments","value":[{"text":"MBMStyleDataLoadedTypeToString","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"MBMStyleDataLoadedCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedCallback\/title"},{"value":[{"kind":"identifier","text":"MBMStyleDataLoadedCallback"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedCallback\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedCallback\/navigatorTitle","value":[{"kind":"identifier","text":"MBMStyleDataLoadedCallback"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestResourceTypeToString(_:)\/title","value":"MBMRequestResourceTypeToString","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestResourceTypeToString(_:)\/fragments","value":[{"kind":"identifier","text":"MBMRequestResourceTypeToString"}],"op":"replace"},{"op":"replace","value":"MBMMapLoadingErrorCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorCallback\/title"},{"value":[{"text":"MBMMapLoadingErrorCallback","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorCallback\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorCallback\/navigatorTitle","op":"replace","value":[{"text":"MBMMapLoadingErrorCallback","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChanged\/title","value":"MBMCameraChanged"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChanged\/fragments","value":[{"text":"MBMCameraChanged","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChanged\/navigatorTitle","value":[{"kind":"identifier","text":"MBMCameraChanged"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestDataSourceTypeToString(_:)\/title","value":"MBMRequestDataSourceTypeToString"},{"value":[{"kind":"identifier","text":"MBMRequestDataSourceTypeToString"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestDataSourceTypeToString(_:)\/fragments"},{"op":"replace","value":"MBMRequestErrorType","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestErrorType\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestErrorType\/fragments","op":"replace","value":[{"text":"MBMRequestErrorType","kind":"identifier"}]},{"value":[{"text":"MBMRequestErrorType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestErrorType\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRenderModeTypeToString(_:)\/title","value":"MBMRenderModeTypeToString","op":"replace"},{"value":[{"text":"MBMRenderModeTypeToString","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRenderModeTypeToString(_:)\/fragments","op":"replace"},{"op":"replace","value":"MBMSourceDataLoadedCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedCallback\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedCallback\/fragments","value":[{"kind":"identifier","text":"MBMSourceDataLoadedCallback"}]},{"op":"replace","value":[{"text":"MBMSourceDataLoadedCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedCallback\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeatureExtensionValue\/title","value":"MBMFeatureExtensionValue","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBMFeatureExtensionValue"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeatureExtensionValue\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeatureExtensionValue\/navigatorTitle","value":[{"kind":"identifier","text":"MBMFeatureExtensionValue"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackError-swift.class\/title","value":"MBMStylePackError"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackError-swift.class\/fragments","op":"replace","value":[{"text":"MBMStylePackError","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"MBMStylePackError"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackError-swift.class\/navigatorTitle"},{"op":"replace","value":"MBMSourceRemovedCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceRemovedCallback\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceRemovedCallback\/fragments","value":[{"kind":"identifier","text":"MBMSourceRemovedCallback"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceRemovedCallback\/navigatorTitle","value":[{"kind":"identifier","text":"MBMSourceRemovedCallback"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapRecorder\/title","value":"MBMMapRecorder","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapRecorder\/fragments","value":[{"text":"MBMMapRecorder","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapRecorder\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMMapRecorder"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChangedCallback\/title","value":"MBMCameraChangedCallback"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChangedCallback\/fragments","op":"replace","value":[{"text":"MBMCameraChangedCallback","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChangedCallback\/navigatorTitle","value":[{"kind":"identifier","text":"MBMCameraChangedCallback"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestPriorityTypeToString(_:)\/title","op":"replace","value":"MBMRequestPriorityTypeToString"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestPriorityTypeToString(_:)\/fragments","op":"replace","value":[{"text":"MBMRequestPriorityTypeToString","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinishedCallback\/title","op":"replace","value":"MBMRenderFrameFinishedCallback"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinishedCallback\/fragments","value":[{"text":"MBMRenderFrameFinishedCallback","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinishedCallback\/navigatorTitle","value":[{"text":"MBMRenderFrameFinishedCallback","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameStartedCallback\/title","value":"MBMRenderFrameStartedCallback","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameStartedCallback\/fragments","value":[{"text":"MBMRenderFrameStartedCallback","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameStartedCallback\/navigatorTitle","value":[{"text":"MBMRenderFrameStartedCallback","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMMapLoadingErrorTypeToString(_:)\/title","value":"MBMMapLoadingErrorTypeToString"},{"value":[{"text":"MBMMapLoadingErrorTypeToString","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMMapLoadingErrorTypeToString(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestLoadingMethodTypeToString(_:)\/title","value":"MBMRequestLoadingMethodTypeToString"},{"op":"replace","value":[{"kind":"identifier","text":"MBMRequestLoadingMethodTypeToString"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestLoadingMethodTypeToString(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMTileStoreUsageModeToString(_:)\/title","op":"replace","value":"MBMTileStoreUsageModeToString"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMTileStoreUsageModeToString(_:)\/fragments","value":[{"kind":"identifier","text":"MBMTileStoreUsageModeToString"}],"op":"replace"},{"value":"MBMMapIdleCallback","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdleCallback\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdleCallback\/fragments","value":[{"text":"MBMMapIdleCallback","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdleCallback\/navigatorTitle","value":[{"text":"MBMMapIdleCallback","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEventCallback\/title","value":"MBMGenericEventCallback"},{"value":[{"text":"MBMGenericEventCallback","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEventCallback\/fragments"},{"value":[{"kind":"identifier","text":"MBMGenericEventCallback"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEventCallback\/navigatorTitle"},{"value":"MBMStyleImageRemoveUnusedCallback","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnusedCallback\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnusedCallback\/fragments","value":[{"text":"MBMStyleImageRemoveUnusedCallback","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnusedCallback\/navigatorTitle","value":[{"text":"MBMStyleImageRemoveUnusedCallback","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestErrorTypeToString(_:)\/title","value":"MBMRequestErrorTypeToString"},{"value":[{"text":"MBMRequestErrorTypeToString","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestErrorTypeToString(_:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequestCallback\/title","op":"replace","value":"MBMResourceRequestCallback"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequestCallback\/fragments","value":[{"text":"MBMResourceRequestCallback","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequestCallback\/navigatorTitle","op":"replace","value":[{"text":"MBMResourceRequestCallback","kind":"identifier"}]},{"value":"MBMSourceAddedCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAddedCallback\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAddedCallback\/fragments","value":[{"text":"MBMSourceAddedCallback","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAddedCallback\/navigatorTitle","value":[{"text":"MBMSourceAddedCallback","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TransitionOptions-swift.class\/title","value":"MBMTransitionOptions","op":"replace"},{"value":[{"kind":"identifier","text":"MBMTransitionOptions"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TransitionOptions-swift.class\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MBMTransitionOptions"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TransitionOptions-swift.class\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMSourceDataLoadedTypeToString(_:)\/title","op":"replace","value":"MBMSourceDataLoadedTypeToString"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMSourceDataLoadedTypeToString(_:)\/fragments","value":[{"kind":"identifier","text":"MBMSourceDataLoadedTypeToString"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageMissingCallback\/title","op":"replace","value":"MBMStyleImageMissingCallback"},{"value":[{"text":"MBMStyleImageMissingCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageMissingCallback\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageMissingCallback\/navigatorTitle","value":[{"text":"MBMStyleImageMissingCallback","kind":"identifier"}],"op":"replace"},{"value":"MBMSize","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Size\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Size\/fragments","value":[{"kind":"identifier","text":"MBMSize"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Size\/navigatorTitle","value":[{"text":"MBMSize","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}