{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"FreeCameraOptions"}],"title":"FreeCameraOptions","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FreeCameraOptions","kind":"identifier"}],"symbolKind":"class","externalID":"c:objc(cs)MBMFreeCameraOptions","modules":[{"name":"MapboxMaps"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs"]]},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions","interfaceLanguage":"swift"},"kind":"symbol","topicSections":[{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions\/getOrientation()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions\/getPosition()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions\/lookAtPoint(forLocation:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions\/lookAtPoint(forLocation:altitude:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions\/lookAtPoint(forLocation:altitude:upVector:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions\/setLocationForLocation(_:altitude:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions\/setOrientationForOrientation(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions\/setPitchBearingForPitch(_:bearing:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions\/setPositionForPosition(_:)"]}],"seeAlsoSections":[{"anchor":"Camera","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/freeCameraOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Camera-and-coordinates"],"title":"Camera"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FreeCameraOptions","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"abstract":[{"type":"text","text":"Various options for accessing physical properties of the underlying camera entity."},{"type":"text","text":" "},{"type":"text","text":"A direct access to these properties allows more flexible and precise controlling"},{"type":"text","text":" "},{"text":"of the camera while also being fully compatible and interchangeable with CameraOptions.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"All fields are optional."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/freecameraoptions"]},{"paths":["\/documentation\/mapboxmaps\/freecameraoptions"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FreeCameraOptions/setPositionForPosition(_:)":{"type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/freecameraoptions\/setpositionforposition(_:)","abstract":[{"type":"text","text":"Set the position of the camera in slightly modified web mercator coordinates"}],"title":"setPositionForPosition(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPositionForPosition"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Vec3","preciseIdentifier":"c:objc(cs)MBMVec3"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions\/setPositionForPosition(_:)","navigatorTitle":[{"text":"setPositionForPosition:","kind":"identifier"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMFreeCameraOptions/setLocationForLocation:":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMFreeCameraOptions\/setLocationForLocation:","navigatorTitle":[{"text":"setLocationForLocation:","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"setLocationForLocation:","kind":"identifier"}],"role":"symbol","title":"setLocationForLocation:","abstract":[{"text":"Helper function for setting the mercator position as Lat&Lng coordinate.","type":"text"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/mbmfreecameraoptions\/setlocationforlocation:","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMFreeCameraOptions/getLocation":{"navigatorTitle":[{"kind":"identifier","text":"getLocation"}],"fragments":[{"text":"- ","kind":"text"},{"text":"getLocation","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMFreeCameraOptions\/getLocation","abstract":[{"text":"Helper function for getting current mercator position as Lat&Lng coordinate.","type":"text"}],"url":"\/documentation\/mapboxmaps\/mbmfreecameraoptions\/getlocation","title":"getLocation","type":"topic"},"doc://com.mapbox.MapboxMaps/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"kind":"article","title":"MapboxMap","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","type":"topic","url":"\/documentation\/mapboxmaps\/mapboxmap-apis"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMFreeCameraOptions/getAltitude":{"fragments":[{"text":"- ","kind":"text"},{"text":"getAltitude","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMFreeCameraOptions\/getAltitude","url":"\/documentation\/mapboxmaps\/mbmfreecameraoptions\/getaltitude","navigatorTitle":[{"text":"getAltitude","kind":"identifier"}],"abstract":[{"type":"text","text":"Helper function for getting current altitude in meters"}],"role":"symbol","type":"topic","title":"getAltitude"},"doc://com.mapbox.MapboxMaps/s7CVarArgP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.mapbox.MapboxMaps/objc(pl)NSObject":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FreeCameraOptions/lookAtPoint(forLocation:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions\/lookAtPoint(forLocation:)","navigatorTitle":[{"kind":"identifier","text":"lookAtPointForLocation:"}],"url":"\/documentation\/mapboxmaps\/freecameraoptions\/lookatpoint(forlocation:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"lookAtPoint","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forLocation","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"text":")","kind":"text"}],"abstract":[{"text":"Helper function for setting orientation of the camera by defining a focus point.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Elevation of 0.0 is used and no up vector."}],"kind":"symbol","title":"lookAtPoint(forLocation:)","type":"topic"},"doc://com.mapbox.MapboxMaps/SQ":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.mapbox.MapboxMaps/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FreeCameraOptions/getOrientation()":{"type":"topic","url":"\/documentation\/mapboxmaps\/freecameraoptions\/getorientation()","abstract":[{"text":"Get the orientation of the camera represented as a unit quaternion [x, y, z, w].","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The default pose of the camera is such that the forward vector is looking up the -Z axis and"},{"text":" ","type":"text"},{"type":"text","text":"the up vector is aligned with north orientation of the map:"},{"type":"text","text":" "},{"text":"forward: [0, 0, -1]","type":"text"},{"type":"text","text":" "},{"type":"text","text":"up:      [0, -1, 0]"},{"type":"text","text":" "},{"type":"text","text":"right    [1, 0, 0]"}],"navigatorTitle":[{"kind":"identifier","text":"getOrientation"}],"title":"getOrientation()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getOrientation"},{"kind":"text","text":"() -> "},{"text":"Vec4","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMVec4"},{"text":"?","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions\/getOrientation()","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FreeCameraOptions/setOrientationForOrientation(_:)":{"navigatorTitle":[{"text":"setOrientationForOrientation:","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions\/setOrientationForOrientation(_:)","role":"symbol","abstract":[{"type":"text","text":"Set the orientation of the camera represented as a unit quaternion [x, y, z, w]."},{"type":"text","text":" "},{"text":"The default pose of the camera is such that the forward vector is looking up the -Z axis and","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"the up vector is aligned with north orientation of the map:"},{"text":" ","type":"text"},{"type":"text","text":"forward: [0, 0, -1]"},{"type":"text","text":" "},{"text":"up:      [0, -1, 0]","type":"text"},{"type":"text","text":" "},{"type":"text","text":"right    [1, 0, 0]"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setOrientationForOrientation","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Vec4","preciseIdentifier":"c:objc(cs)MBMVec4"},{"text":"?)","kind":"text"}],"url":"\/documentation\/mapboxmaps\/freecameraoptions\/setorientationfororientation(_:)","title":"setOrientationForOrientation(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FreeCameraOptions":{"type":"topic","url":"\/documentation\/mapboxmaps\/freecameraoptions","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FreeCameraOptions"}],"title":"FreeCameraOptions","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FreeCameraOptions"}],"abstract":[{"type":"text","text":"Various options for accessing physical properties of the underlying camera entity."},{"type":"text","text":" "},{"type":"text","text":"A direct access to these properties allows more flexible and precise controlling"},{"type":"text","text":" "},{"text":"of the camera while also being fully compatible and interchangeable with CameraOptions.","type":"text"},{"type":"text","text":" "},{"text":"All fields are optional.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/freeCameraOptions":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/freeCameraOptions","type":"topic","abstract":[{"type":"text","text":"Sets\/get the map view with the free camera options."}],"title":"freeCameraOptions","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"freeCameraOptions","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMFreeCameraOptions","kind":"typeIdentifier","text":"FreeCameraOptions"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/freecameraoptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Camera-and-coordinates":{"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Camera-and-coordinates","title":"Camera and coordinates","role":"collectionGroup","abstract":[],"type":"topic","url":"\/documentation\/mapboxmaps\/camera-and-coordinates"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","title":"MapboxMaps","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FreeCameraOptions/lookAtPoint(forLocation:altitude:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions\/lookAtPoint(forLocation:altitude:)","abstract":[{"text":"Helper function for setting orientation of the camera by defining a focus point.","type":"text"},{"type":"text","text":" "},{"text":"No up vector is used.","type":"text"}],"title":"lookAtPoint(forLocation:altitude:)","navigatorTitle":[{"text":"lookAtPointForLocation:altitude:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"lookAtPoint"},{"text":"(","kind":"text"},{"text":"forLocation","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"altitude"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/mapboxmaps\/freecameraoptions\/lookatpoint(forlocation:altitude:)","kind":"symbol","type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","url":"\/documentation\/overview","title":"MapboxMaps Documentation","abstract":[],"kind":"article","role":"collection"},"doc://com.mapbox.MapboxMaps/SH":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FreeCameraOptions/lookAtPoint(forLocation:altitude:upVector:)":{"abstract":[{"type":"text","text":"Helper function for setting orientation of the camera by defining a focus point."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions\/lookAtPoint(forLocation:altitude:upVector:)","role":"symbol","navigatorTitle":[{"text":"lookAtPointForLocation:altitude:upVector:","kind":"identifier"}],"type":"topic","title":"lookAtPoint(forLocation:altitude:upVector:)","url":"\/documentation\/mapboxmaps\/freecameraoptions\/lookatpoint(forlocation:altitude:upvector:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"lookAtPoint"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forLocation"},{"text":": ","kind":"text"},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"text":", ","kind":"text"},{"text":"altitude","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"upVector","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MBMVec3","kind":"typeIdentifier","text":"Vec3"},{"text":")","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMFreeCameraOptions/setAltitudeForAltitude:":{"url":"\/documentation\/mapboxmaps\/mbmfreecameraoptions\/setaltitudeforaltitude:","navigatorTitle":[{"text":"setAltitudeForAltitude:","kind":"identifier"}],"type":"topic","abstract":[{"text":"Helper function for setting the altitude in meters.","type":"text"}],"role":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"setAltitudeForAltitude:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMFreeCameraOptions\/setAltitudeForAltitude:","title":"setAltitudeForAltitude:"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FreeCameraOptions/setPitchBearingForPitch(_:bearing:)":{"kind":"symbol","title":"setPitchBearingForPitch(_:bearing:)","role":"symbol","abstract":[{"type":"text","text":"Helper function for setting the orientation of the camera as a pitch and a bearing."}],"url":"\/documentation\/mapboxmaps\/freecameraoptions\/setpitchbearingforpitch(_:bearing:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions\/setPitchBearingForPitch(_:bearing:)","navigatorTitle":[{"text":"setPitchBearingForPitch:bearing:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setPitchBearingForPitch","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"bearing"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":")","kind":"text"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FreeCameraOptions/setLocationForLocation(_:altitude:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions\/setLocationForLocation(_:altitude:)","abstract":[{"type":"text","text":"Helper function for setting the mercator position as Lat&Lng and altitude in meters."}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLocationForLocation"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":", "},{"text":"altitude","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":")","kind":"text"}],"title":"setLocationForLocation(_:altitude:)","navigatorTitle":[{"kind":"identifier","text":"setLocationForLocation:altitude:"}],"role":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/freecameraoptions\/setlocationforlocation(_:altitude:)"},"doc://com.mapbox.MapboxMaps/objc(cs)NSObject":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FreeCameraOptions/getPosition()":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"getPosition"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:objc(cs)MBMVec3","text":"Vec3","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"getPosition()","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions\/getPosition()","type":"topic","abstract":[{"type":"text","text":"Get the position of the camera in slightly modified web mercator coordinates"}],"kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/freecameraoptions\/getposition()","navigatorTitle":[{"text":"getPosition","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","value":"MBMFreeCameraOptions","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"value":[{"kind":"identifier","text":"MBMFreeCameraOptions"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"MBMFreeCameraOptions","kind":"identifier"}]},{"path":"\/topicSections","value":[{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions\/getOrientation()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions\/getPosition()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions\/lookAtPoint(forLocation:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions\/lookAtPoint(forLocation:altitude:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions\/lookAtPoint(forLocation:altitude:upVector:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions\/setLocationForLocation(_:altitude:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions\/setOrientationForOrientation(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions\/setPitchBearingForPitch(_:bearing:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions\/setPositionForPosition(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMFreeCameraOptions\/getAltitude","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMFreeCameraOptions\/getLocation","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMFreeCameraOptions\/setAltitudeForAltitude:","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMFreeCameraOptions\/setLocationForLocation:"],"generated":true}],"op":"replace"},{"value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"replace","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBMFreeCameraOptions"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"setPositionForPosition:","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions~1setPositionForPosition(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setPositionForPosition:"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions~1setPositionForPosition(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions~1lookAtPoint(forLocation:)\/title","value":"lookAtPointForLocation:"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions~1lookAtPoint(forLocation:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"lookAtPointForLocation:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions~1getOrientation()\/title","value":"getOrientation"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getOrientation"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions~1getOrientation()\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions~1setOrientationForOrientation(_:)\/title","value":"setOrientationForOrientation:","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions~1setOrientationForOrientation(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setOrientationForOrientation:","kind":"identifier"}]},{"op":"replace","value":"MBMFreeCameraOptions","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions\/title"},{"value":[{"kind":"identifier","text":"MBMFreeCameraOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions\/fragments"},{"value":[{"text":"MBMFreeCameraOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions~1lookAtPoint(forLocation:altitude:)\/title","op":"replace","value":"lookAtPointForLocation:altitude:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"lookAtPointForLocation:altitude:"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions~1lookAtPoint(forLocation:altitude:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions~1lookAtPoint(forLocation:altitude:upVector:)\/title","value":"lookAtPointForLocation:altitude:upVector:"},{"value":[{"text":"- ","kind":"text"},{"text":"lookAtPointForLocation:altitude:upVector:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions~1lookAtPoint(forLocation:altitude:upVector:)\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions~1setPitchBearingForPitch(_:bearing:)\/title","value":"setPitchBearingForPitch:bearing:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions~1setPitchBearingForPitch(_:bearing:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setPitchBearingForPitch:bearing:","kind":"identifier"}]},{"value":"setLocationForLocation:altitude:","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions~1setLocationForLocation(_:altitude:)\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions~1setLocationForLocation(_:altitude:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setLocationForLocation:altitude:"}],"op":"replace"},{"op":"replace","value":"getPosition","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions~1getPosition()\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions~1getPosition()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getPosition"}],"op":"replace"}]}]}