{"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-View"]]},"topicSections":[{"generated":true,"title":"Initializers","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationOptions\/init(rasterizationMode:fontFamily:)"],"anchor":"Initializers"},{"anchor":"Instance-Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationOptions\/fontFamily","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationOptions\/rasterizationMode"],"generated":true,"title":"Instance Properties"}],"sections":[],"seeAlsoSections":[{"generated":true,"anchor":"MapView","title":"MapView","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapView","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapInitOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapInitOptionsProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AttributionURLOpener","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ConstrainMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/NorthOrientation","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PresentationTransactionMode"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/glyphsrasterizationoptions"]},{"paths":["\/documentation\/mapboxmaps\/glyphsrasterizationoptions"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Describes the glyphs rasterization option values."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GlyphsRasterizationOptions"}]}]}],"metadata":{"roleHeading":"Class","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GlyphsRasterizationOptions"}],"navigatorTitle":[{"kind":"identifier","text":"GlyphsRasterizationOptions"}],"role":"symbol","title":"GlyphsRasterizationOptions","externalID":"c:objc(cs)MBMGlyphsRasterizationOptions","modules":[{"name":"MapboxMaps"}]},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH","doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"],"type":"conformsTo"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationOptions"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","title":"MapboxMaps","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GlyphsRasterizationMode":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GlyphsRasterizationMode"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GlyphsRasterizationMode"}],"url":"\/documentation\/mapboxmaps\/glyphsrasterizationmode","title":"GlyphsRasterizationMode","abstract":[{"text":"Describes glyphs rasterization modes.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapInitOptions":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapInitOptions","abstract":[{"text":"Options used when initializing ","type":"text"},{"type":"codeVoice","code":"MapView"},{"type":"text","text":"."}],"kind":"symbol","role":"symbol","title":"MapInitOptions","navigatorTitle":[{"kind":"identifier","text":"MapInitOptions"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapInitOptions","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/mapinitoptions"},"doc://com.mapbox.MapboxMaps/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GlyphsRasterizationOptions/rasterizationMode":{"url":"\/documentation\/mapboxmaps\/glyphsrasterizationoptions\/rasterizationmode","abstract":[{"text":"Glyphs rasterization mode for client-side text rendering.","type":"text"}],"title":"rasterizationMode","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"rasterizationMode","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GlyphsRasterizationMode","preciseIdentifier":"c:@E@MBMGlyphsRasterizationMode"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationOptions\/rasterizationMode","navigatorTitle":[{"kind":"identifier","text":"rasterizationMode"}],"type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/SH":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapView":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"MapView"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapView"}],"url":"\/documentation\/mapboxmaps\/mapview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapView","title":"MapView","kind":"symbol","abstract":[],"role":"symbol"},"doc://com.mapbox.MapboxMaps/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.mapbox.MapboxMaps/objc(pl)NSObject":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AttributionURLOpener":{"navigatorTitle":[{"text":"AttributionURLOpener","kind":"identifier"}],"abstract":[{"text":"A protocol to open attribution URLs.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"AttributionURLOpener","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AttributionURLOpener","type":"topic","title":"AttributionURLOpener","url":"\/documentation\/mapboxmaps\/attributionurlopener","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map-View":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-View","role":"collectionGroup","abstract":[],"title":"MapView","type":"topic","kind":"article","url":"\/documentation\/mapboxmaps\/map-view"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GlyphsRasterizationOptions/fontFamily":{"type":"topic","url":"\/documentation\/mapboxmaps\/glyphsrasterizationoptions\/fontfamily","title":"fontFamily","role":"symbol","abstract":[{"text":"Font family to use as font fallback for client-side text renderings.","type":"text"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fontFamily","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationOptions\/fontFamily","navigatorTitle":[{"text":"fontFamily","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PresentationTransactionMode":{"navigatorTitle":[{"kind":"identifier","text":"PresentationTransactionMode"}],"abstract":[{"text":"Determines if the underlying ","type":"text"},{"type":"codeVoice","code":"CAMetalLayer"},{"text":" rendering output should synchronize with the Core Animation transactions.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PresentationTransactionMode"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PresentationTransactionMode","url":"\/documentation\/mapboxmaps\/presentationtransactionmode","title":"PresentationTransactionMode"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapInitOptionsProvider":{"navigatorTitle":[{"text":"MapInitOptionsProvider","kind":"identifier"}],"abstract":[{"text":"A protocol used to provide ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapInitOptions","isActive":true},{"type":"text","text":" when initializing a "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapView","isActive":true,"type":"reference"},{"type":"text","text":" with a Storyboard or"},{"text":" ","type":"text"},{"type":"text","text":"a nib."}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MapInitOptionsProvider","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapInitOptionsProvider","type":"topic","title":"MapInitOptionsProvider","url":"\/documentation\/mapboxmaps\/mapinitoptionsprovider","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/NorthOrientation":{"url":"\/documentation\/mapboxmaps\/northorientation","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/NorthOrientation","navigatorTitle":[{"text":"NorthOrientation","kind":"identifier"}],"type":"topic","kind":"symbol","title":"NorthOrientation","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NorthOrientation"}],"abstract":[{"text":"Describes the map orientation.","type":"text"}]},"doc://com.mapbox.MapboxMaps/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.mapbox.MapboxMaps/SQ":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.mapbox.MapboxMaps/objc(cs)NSObject":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","url":"\/documentation\/overview","title":"MapboxMaps Documentation","abstract":[],"kind":"article","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewportMode":{"navigatorTitle":[{"kind":"identifier","text":"ViewportMode"}],"abstract":[{"type":"text","text":"Satisfies embedding platforms that requires the viewport coordinate systems to be set according to its standards."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ViewportMode"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportMode","type":"topic","title":"ViewportMode","url":"\/documentation\/mapboxmaps\/viewportmode","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GlyphsRasterizationOptions":{"url":"\/documentation\/mapboxmaps\/glyphsrasterizationoptions","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationOptions","navigatorTitle":[{"text":"GlyphsRasterizationOptions","kind":"identifier"}],"type":"topic","kind":"symbol","title":"GlyphsRasterizationOptions","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GlyphsRasterizationOptions","kind":"identifier"}],"abstract":[{"text":"Describes the glyphs rasterization option values.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GlyphsRasterizationOptions/init(rasterizationMode:fontFamily:)":{"type":"topic","kind":"symbol","title":"init(rasterizationMode:fontFamily:)","url":"\/documentation\/mapboxmaps\/glyphsrasterizationoptions\/init(rasterizationmode:fontfamily:)","abstract":[],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rasterizationMode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GlyphsRasterizationMode","preciseIdentifier":"c:@E@MBMGlyphsRasterizationMode"},{"kind":"text","text":", "},{"text":"fontFamily","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithRasterizationMode:fontFamily:"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationOptions\/init(rasterizationMode:fontFamily:)"},"doc://com.mapbox.MapboxMaps/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ConstrainMode":{"url":"\/documentation\/mapboxmaps\/constrainmode","kind":"symbol","navigatorTitle":[{"text":"ConstrainMode","kind":"identifier"}],"abstract":[{"text":"Describes whether to constrain the map in both axes or only vertically e.g. while panning.","type":"text"}],"title":"ConstrainMode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConstrainMode","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ConstrainMode","type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapOptions":{"navigatorTitle":[{"kind":"identifier","text":"MapOptions"}],"abstract":[{"type":"text","text":"Describes the map option values."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapOptions"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapOptions","type":"topic","title":"MapOptions","url":"\/documentation\/mapboxmaps\/mapoptions","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"MBMGlyphsRasterizationOptions"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"MBMGlyphsRasterizationOptions"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"MBMGlyphsRasterizationOptions","kind":"identifier"}],"op":"replace"},{"value":[{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationOptions\/fontFamily","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationOptions\/rasterizationMode"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationOptions\/init(rasterizationMode:fontFamily:)"],"generated":true,"anchor":"Instance-Methods"}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"}]},{"path":"\/seeAlsoSections","value":[{"anchor":"MapView","title":"MapView","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ConstrainMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/NorthOrientation","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportMode"],"generated":true}],"op":"replace"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"MBMGlyphsRasterizationOptions","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/title","value":"MBMGlyphsRasterizationMode"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/fragments","value":[{"text":"MBMGlyphsRasterizationMode","kind":"identifier"}],"op":"replace"},{"value":[{"text":"MBMGlyphsRasterizationMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/navigatorTitle"},{"value":"rasterizationMode","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationOptions~1rasterizationMode\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationOptions~1rasterizationMode\/fragments","value":[{"kind":"identifier","text":"rasterizationMode"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationOptions~1fontFamily\/title","value":"fontFamily","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationOptions~1fontFamily\/fragments","value":[{"text":"fontFamily","kind":"identifier"}]},{"value":"MBMNorthOrientation","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1NorthOrientation\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1NorthOrientation\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMNorthOrientation"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1NorthOrientation\/navigatorTitle","value":[{"text":"MBMNorthOrientation","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewportMode\/title","value":"MBMViewportMode"},{"value":[{"text":"MBMViewportMode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewportMode\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewportMode\/navigatorTitle","value":[{"kind":"identifier","text":"MBMViewportMode"}]},{"value":"MBMGlyphsRasterizationOptions","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationOptions\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationOptions\/fragments","value":[{"text":"MBMGlyphsRasterizationOptions","kind":"identifier"}]},{"value":[{"text":"MBMGlyphsRasterizationOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationOptions\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationOptions~1init(rasterizationMode:fontFamily:)\/title","value":"initWithRasterizationMode:fontFamily:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithRasterizationMode:fontFamily:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationOptions~1init(rasterizationMode:fontFamily:)\/fragments"},{"value":"MBMConstrainMode","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ConstrainMode\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBMConstrainMode"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ConstrainMode\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ConstrainMode\/navigatorTitle","op":"replace","value":[{"text":"MBMConstrainMode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapOptions\/title","value":"MBMMapOptions"},{"value":[{"text":"MBMMapOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapOptions\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapOptions\/navigatorTitle","value":[{"text":"MBMMapOptions","kind":"identifier"}],"op":"replace"}]}]}