{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HttpServiceFactory"}],"platforms":["iOS"]}]},{"content":[{"type":"heading","level":2,"text":"Overview","anchor":"overview"},{"inlineContent":[{"type":"text","text":"This class is used to get a pointer\/reference to HTTP service platform implementation."}],"type":"paragraph"}],"kind":"content"}],"topicSections":[{"generated":true,"anchor":"Type-Methods","title":"Type Methods","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceFactory\/setCancellationCallbackForCallback(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceFactory\/setHttpServiceInterceptorForInterceptor(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceFactory\/setMaxRequestsPerHostForMax(_:)"]}],"sections":[],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"HttpServiceFactory","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"HttpServiceFactory"}],"externalID":"c:objc(cs)MBXHttpServiceFactory","title":"HttpServiceFactory","symbolKind":"class","roleHeading":"Class","modules":[{"name":"MapboxCommon"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon"]]},"abstract":[{"text":"HTTP service factory.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/httpservicefactory"]},{"paths":["\/documentation\/mapboxcommon\/httpservicefactory"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceFactory"},"schemaVersion":{"minor":3,"patch":0,"major":0},"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpServiceFactory/setHttpServiceInterceptorForInterceptor(_:)":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setHttpServiceInterceptorForInterceptor"},{"kind":"text","text":"((any "},{"preciseIdentifier":"c:objc(pl)MBXHttpServiceInterceptorInterface","text":"HttpServiceInterceptorInterface","kind":"typeIdentifier"},{"kind":"text","text":")?)"}],"navigatorTitle":[{"kind":"identifier","text":"setHttpServiceInterceptorForInterceptor:"}],"type":"topic","title":"setHttpServiceInterceptorForInterceptor(_:)","kind":"symbol","url":"\/documentation\/mapboxcommon\/httpservicefactory\/sethttpserviceinterceptorforinterceptor(_:)","abstract":[{"text":"Sets an interceptor for the current HTTP service instance.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceFactory\/setHttpServiceInterceptorForInterceptor(_:)"},"doc://com.mapbox.MapboxMaps/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpServiceFactory":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"HttpServiceFactory","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"HttpServiceFactory"}],"type":"topic","title":"HttpServiceFactory","kind":"symbol","url":"\/documentation\/mapboxcommon\/httpservicefactory","abstract":[{"text":"HTTP service factory.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceFactory"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpServiceFactory/setMaxRequestsPerHostForMax(_:)":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMaxRequestsPerHostForMax"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:s5UInt8V","text":"UInt8","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"setMaxRequestsPerHostForMax(_:)","navigatorTitle":[{"kind":"identifier","text":"setMaxRequestsPerHostForMax:"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Set maximum number of requests to a single host for the current HTTP service instance.","type":"text"}],"url":"\/documentation\/mapboxcommon\/httpservicefactory\/setmaxrequestsperhostformax(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceFactory\/setMaxRequestsPerHostForMax(_:)","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpServiceFactory/setCancellationCallbackForCallback(_:)":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setCancellationCallbackForCallback"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:MBXHttpServiceCancellationCallback.h@T@MBXHttpServiceCancellationCallback","text":"HttpServiceCancellationCallback"},{"text":") -> any ","kind":"text"},{"kind":"typeIdentifier","text":"Cancelable","preciseIdentifier":"c:objc(pl)MBXCancelable"}],"navigatorTitle":[{"kind":"identifier","text":"setCancellationCallbackForCallback:"}],"type":"topic","title":"setCancellationCallbackForCallback(_:)","kind":"symbol","url":"\/documentation\/mapboxcommon\/httpservicefactory\/setcancellationcallbackforcallback(_:)","abstract":[{"text":"Sets the cancellation callback for HTTP request events","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceFactory\/setCancellationCallbackForCallback(_:)"},"doc://com.mapbox.MapboxMaps/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","title":"MapboxMaps Documentation","type":"topic","kind":"article","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection"},"doc://com.mapbox.MapboxMaps/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","type":"topic","url":"\/documentation\/mapboxcommon","title":"MapboxCommon","role":"collection","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"MBXHttpServiceFactory"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXHttpServiceFactory"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"MBXHttpServiceFactory","kind":"identifier"}],"op":"replace"},{"value":[{"generated":true,"anchor":"Type-Methods","title":"Type Methods","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceFactory\/setCancellationCallbackForCallback(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceFactory\/setHttpServiceInterceptorForInterceptor(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceFactory\/setMaxRequestsPerHostForMax(_:)"]}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"kind":"relationships"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"MBXHttpServiceFactory","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}]}},{"value":"setHttpServiceInterceptorForInterceptor:","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceFactory~1setHttpServiceInterceptorForInterceptor(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceFactory~1setHttpServiceInterceptorForInterceptor(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"setHttpServiceInterceptorForInterceptor:"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceFactory\/title","op":"replace","value":"MBXHttpServiceFactory"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceFactory\/fragments","op":"replace","value":[{"text":"MBXHttpServiceFactory","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceFactory\/navigatorTitle","value":[{"kind":"identifier","text":"MBXHttpServiceFactory"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceFactory~1setMaxRequestsPerHostForMax(_:)\/title","value":"setMaxRequestsPerHostForMax:","op":"replace"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"setMaxRequestsPerHostForMax:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceFactory~1setMaxRequestsPerHostForMax(_:)\/fragments"},{"op":"replace","value":"setCancellationCallbackForCallback:","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceFactory~1setCancellationCallbackForCallback(_:)\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceFactory~1setCancellationCallbackForCallback(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"setCancellationCallbackForCallback:","kind":"identifier"}],"op":"replace"}]}]}