{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestFlags"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HttpRequestFlags"}]}]}],"metadata":{"symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"HttpRequestFlags"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HttpRequestFlags","kind":"identifier"}],"externalID":"c:objc(cs)MBXHttpRequestFlags","title":"HttpRequestFlags","modules":[{"name":"MapboxCommon"}],"role":"symbol","roleHeading":"Class"},"sections":[],"topicSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestFlags\/keepCompression","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestFlags\/none","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestFlags\/pauseInBackground","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestFlags\/preventCoalescing"],"generated":true,"anchor":"Type-Properties","title":"Type Properties"}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH"],"title":"Conforms To","type":"conformsTo"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/httprequestflags"]},{"paths":["\/documentation\/mapboxcommon\/httprequestflags"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestFlags/pauseInBackground":{"role":"symbol","url":"\/documentation\/mapboxcommon\/httprequestflags\/pauseinbackground","abstract":[{"text":"Supported for Android only.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If set and application also has “com.mapbox.common.http.pause_requests_on_demand” setting in manifest"},{"text":" ","type":"text"},{"type":"text","text":"the request will be performed in the foreground only. In case application is in the background request will"},{"type":"text","text":" "},{"text":"be queued.","type":"text"}],"kind":"symbol","type":"topic","title":"pauseInBackground","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestFlags\/pauseInBackground","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pauseInBackground","kind":"identifier"},{"kind":"text","text":": "},{"text":"UInt32","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt32V"}],"navigatorTitle":[{"kind":"identifier","text":"PauseInBackground"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestFlags/preventCoalescing":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PreventCoalescing"}],"title":"preventCoalescing","abstract":[{"text":"Flag to prevent the HTTP request from being coalesced with other equivalent request(s) that are currently on","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"the fly. Setting this flag will ensure that the request made through the HTTP service interface results in"},{"type":"text","text":" "},{"text":"its own network request.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestFlags\/preventCoalescing","url":"\/documentation\/mapboxcommon\/httprequestflags\/preventcoalescing","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"preventCoalescing","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt32","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt32V"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestFlags/none":{"abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"None"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt32","preciseIdentifier":"s:s6UInt32V"}],"url":"\/documentation\/mapboxcommon\/httprequestflags\/none","title":"none","type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestFlags\/none"},"doc://com.mapbox.MapboxMaps/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP"},"doc://com.mapbox.MapboxMaps/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","title":"MapboxMaps Documentation","type":"topic","kind":"article","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","type":"topic","url":"\/documentation\/mapboxcommon","title":"MapboxCommon","role":"collection","abstract":[]},"doc://com.mapbox.MapboxMaps/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP"},"doc://com.mapbox.MapboxMaps/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestFlags/keepCompression":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestFlags\/keepCompression","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"keepCompression"},{"kind":"text","text":": "},{"text":"UInt32","preciseIdentifier":"s:s6UInt32V","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"KeepCompression"}],"url":"\/documentation\/mapboxcommon\/httprequestflags\/keepcompression","title":"keepCompression","abstract":[{"text":"Keep compression flag. If set, responses will not be automatically decompressed.","type":"text"},{"type":"text","text":" "},{"text":"Currently this mechanism is deprecated, for mapbox servers use custom X-Accept-Encoding.","type":"text"}],"role":"symbol","deprecated":true},"doc://com.mapbox.MapboxMaps/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject"},"doc://com.mapbox.MapboxMaps/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestFlags":{"abstract":[],"url":"\/documentation\/mapboxcommon\/httprequestflags","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"HttpRequestFlags","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"HttpRequestFlags"}],"type":"topic","role":"symbol","title":"HttpRequestFlags","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestFlags","kind":"symbol"},"doc://com.mapbox.MapboxMaps/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"MBXHttpRequestFlags","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"MBXHttpRequestFlags"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MBXHttpRequestFlags"}]},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestFlags\/keepCompression","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestFlags\/none","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestFlags\/pauseInBackground","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestFlags\/preventCoalescing"],"generated":true,"title":"Type Properties","anchor":"Type-Properties"}],"op":"replace"},{"value":[{"kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBXHttpRequestFlags"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}]}]}},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestFlags~1pauseInBackground\/title","value":"PauseInBackground","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestFlags~1pauseInBackground\/fragments","value":[{"kind":"identifier","text":"PauseInBackground"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestFlags~1preventCoalescing\/title","value":"PreventCoalescing","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestFlags~1preventCoalescing\/fragments","value":[{"text":"PreventCoalescing","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestFlags~1none\/title","value":"None"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestFlags~1none\/fragments","op":"replace","value":[{"kind":"identifier","text":"None"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestFlags~1keepCompression\/title","value":"KeepCompression"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestFlags~1keepCompression\/fragments","value":[{"text":"KeepCompression","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestFlags\/title","value":"MBXHttpRequestFlags"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestFlags\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXHttpRequestFlags"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestFlags\/navigatorTitle","value":[{"text":"MBXHttpRequestFlags","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}