{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onRequest","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"request","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest","preciseIdentifier":"c:objc(cs)MBXHttpRequest","text":"HttpRequest","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"continuation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceInterceptorRequestContinuation","preciseIdentifier":"c:MBXHttpServiceInterceptorRequestContinuation.h@T@MBXHttpServiceInterceptorRequestContinuation","text":"HttpServiceInterceptorRequestContinuation","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"request","content":[{"type":"paragraph","inlineContent":[{"text":"The original HttpRequest object to be modified.","type":"text"}]}]},{"name":"continuation","content":[{"type":"paragraph","inlineContent":[{"text":"Callback to be invoked once the interceptor has finished processing the request. Can also","type":"text"},{"text":" ","type":"text"},{"text":"be invoked with a HttpResponse, in which case the request completes immediately.","type":"text"}]}]}],"kind":"parameters"}],"kind":"symbol","metadata":{"role":"symbol","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"onRequestForRequest:continuation:"}],"title":"onRequest(for:continuation:)","modules":[{"name":"MapboxCommon"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onRequest"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXHttpRequest","text":"HttpRequest"},{"kind":"text","text":", "},{"kind":"externalParam","text":"continuation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:MBXHttpServiceInterceptorRequestContinuation.h@T@MBXHttpServiceInterceptorRequestContinuation","text":"HttpServiceInterceptorRequestContinuation"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","required":true,"externalID":"c:objc(pl)MBXHttpServiceInterceptorInterface(im)onRequestForRequest:continuation:"},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceInterceptorInterface\/onRequest(for:continuation:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceInterceptorInterface"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/httpserviceinterceptorinterface\/onrequest(for:continuation:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/httpserviceinterceptorinterface\/onrequest(for:continuation:)"]}],"abstract":[{"type":"text","text":"The function to intercept HTTP requests with."}],"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","kind":"article","title":"MapboxMaps Documentation","url":"\/documentation\/overview","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpServiceInterceptorInterface/onRequest(for:continuation:)":{"url":"\/documentation\/mapboxcommon\/httpserviceinterceptorinterface\/onrequest(for:continuation:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onRequestForRequest:continuation:"}],"kind":"symbol","title":"onRequest(for:continuation:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onRequest"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXHttpRequest","text":"HttpRequest"},{"kind":"text","text":", "},{"kind":"externalParam","text":"continuation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:MBXHttpServiceInterceptorRequestContinuation.h@T@MBXHttpServiceInterceptorRequestContinuation","text":"HttpServiceInterceptorRequestContinuation"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceInterceptorInterface\/onRequest(for:continuation:)","abstract":[{"text":"The function to intercept HTTP requests with.","type":"text"}],"required":true},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"url":"\/documentation\/mapboxcommon","type":"topic","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","role":"collection","title":"MapboxCommon"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequest":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HttpRequest"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest","abstract":[{"text":"HttpRequest holds basic information for construction of an HTTP request","type":"text"}],"url":"\/documentation\/mapboxcommon\/httprequest","navigatorTitle":[{"kind":"identifier","text":"HttpRequest"}],"title":"HttpRequest"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpServiceInterceptorInterface":{"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HttpServiceInterceptorInterface"}],"title":"HttpServiceInterceptorInterface","kind":"symbol","type":"topic","url":"\/documentation\/mapboxcommon\/httpserviceinterceptorinterface","abstract":[{"text":"Interface for intercepting and modifying HttpService function calls.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceInterceptorInterface","navigatorTitle":[{"text":"HttpServiceInterceptorInterface","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpServiceInterceptorRequestContinuation":{"title":"HttpServiceInterceptorRequestContinuation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceInterceptorRequestContinuation","abstract":[{"text":"Continuation to be invoked once the interceptor is done processing a request. If invoked with a HttpRequest, the","type":"text"},{"text":" ","type":"text"},{"text":"HTTP service will proceed to make a request via the network. Invoking the continuation with a HttpResponse bypasses","type":"text"},{"text":" ","type":"text"},{"text":"the network and causes the request to complete immediately with the specified response. The ID of the HttpResponse","type":"text"},{"text":" ","type":"text"},{"text":"is irrelevant in this case.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"HttpServiceInterceptorRequestContinuation"}],"navigatorTitle":[{"kind":"identifier","text":"HttpServiceInterceptorRequestContinuation"}],"url":"\/documentation\/mapboxcommon\/httpserviceinterceptorrequestcontinuation","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"onRequestForRequest:continuation:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"onRequestForRequest:continuation:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"onRequestForRequest:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MBXHttpRequest","preciseIdentifier":"c:objc(cs)MBXHttpRequest","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest"},{"text":" *) ","kind":"text"},{"text":"request","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"continuation:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void (^)(MBXHttpRequestOrResponse *)","preciseIdentifier":"c:BFv(#*$objc(cs)MBXHttpRequestOrResponse)","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"continuation","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"name":"request","content":[{"type":"paragraph","inlineContent":[{"text":"The original HttpRequest object to be modified.","type":"text"}]}]},{"name":"continuation","content":[{"inlineContent":[{"type":"text","text":"Callback to be invoked once the interceptor has finished processing the request. Can also"},{"type":"text","text":" "},{"type":"text","text":"be invoked with a HttpResponse, in which case the request completes immediately."}],"type":"paragraph"}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"onRequestForRequest:continuation:","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceInterceptorInterface~1onRequest(for:continuation:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"onRequestForRequest:continuation:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceInterceptorInterface~1onRequest(for:continuation:)\/fragments"},{"value":"MBXHttpRequest","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest\/title"},{"value":[{"text":"MBXHttpRequest","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest\/fragments"},{"value":[{"text":"MBXHttpRequest","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest\/navigatorTitle"},{"value":"MBXHttpServiceInterceptorInterface","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceInterceptorInterface\/title"},{"value":[{"kind":"identifier","text":"MBXHttpServiceInterceptorInterface"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceInterceptorInterface\/fragments"},{"value":[{"kind":"identifier","text":"MBXHttpServiceInterceptorInterface"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceInterceptorInterface\/navigatorTitle"},{"value":"MBXHttpServiceInterceptorRequestContinuation","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceInterceptorRequestContinuation\/title"},{"value":[{"kind":"identifier","text":"MBXHttpServiceInterceptorRequestContinuation"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceInterceptorRequestContinuation\/fragments"},{"value":[{"text":"MBXHttpServiceInterceptorRequestContinuation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceInterceptorRequestContinuation\/navigatorTitle"}]}]}