{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStylePackLoadOptions\/extraOptions"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"extraOptions","modules":[{"name":"MapboxMaps"}],"navigatorTitle":[{"kind":"identifier","text":"extraOptions"}],"roleHeading":"Instance Property","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"extraOptions"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?","kind":"text"}],"role":"symbol","externalID":"c:objc(cs)MBMStylePackLoadOptions(py)extraOptions"},"variants":[{"paths":["\/documentation\/mapboxmaps\/mbmstylepackloadoptions\/extraoptions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/mbmstylepackloadoptions\/extraoptions"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadOptions"]]},"abstract":[{"type":"text","text":"Extra style package load options."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"extraOptions"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"inlineContent":[{"type":"text","text":"Accepts the dictionary value with keys of string type."},{"text":" ","type":"text"},{"text":"Supported options:","type":"text"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"“keep-legacy-style-pack” -> boolean (false by default).","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Prior to Maps v11 the style packages were stored in the Disk cache, and starting from v11 they are stored in the Tile Store."},{"text":" ","type":"text"},{"type":"text","text":"By default, the implementation removes the style package from the legacy storage after the first successful loadStylePack()"},{"text":" ","type":"text"},{"text":"call when all the data gets into the Tile Store.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Setting this flag prevents from the style package removal from the legacy storage after the loadStylePack() call."}]}]}]}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMStylePackLoadOptions/extraOptions":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStylePackLoadOptions\/extraOptions","title":"extraOptions","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"extraOptions"}],"url":"\/documentation\/mapboxmaps\/mbmstylepackloadoptions\/extraoptions","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"extraOptions"},{"text":": ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Extra style package load options."}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"url":"\/documentation\/mapboxmaps\/tilestore-apis","kind":"article","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","type":"topic","title":"TileStore APIs"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePackLoadOptions":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StylePackLoadOptions"}],"url":"\/documentation\/mapboxmaps\/stylepackloadoptions","navigatorTitle":[{"kind":"identifier","text":"StylePackLoadOptions"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadOptions","type":"topic","title":"StylePackLoadOptions","abstract":[{"type":"text","text":"Describes the style package load option values."}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"extraOptions","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"extraOptions"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"id"},{"kind":"text","text":" "},{"text":"extraOptions","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMStylePackLoadOptions~1extraOptions\/title","value":"extraOptions","op":"replace"},{"value":[{"kind":"identifier","text":"extraOptions"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMStylePackLoadOptions~1extraOptions\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadOptions\/title","value":"MBMStylePackLoadOptions"},{"value":[{"text":"MBMStylePackLoadOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadOptions\/fragments","op":"replace"}]}]}