{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionErrorType"]]},"variants":[{"paths":["\/documentation\/mapboxmaps\/offlineregionerrortype\/init(rawvalue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionErrorType\/init(rawValue:)","interfaceLanguage":"swift"},"sections":[],"metadata":{"role":"symbol","title":"init(rawValue:)","platforms":[],"externalID":"s:So25MBMOfflineRegionErrorTypeV8rawValueABSgSi_tcfc","symbolKind":"init","modules":[{"name":"MapboxMaps"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Initializer"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionErrorType":{"title":"OfflineRegionErrorType","abstract":[{"type":"text","text":"Describes the reason for an offline request response error."}],"kind":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OfflineRegionErrorType","kind":"identifier"}],"navigatorTitle":[{"text":"OfflineRegionErrorType","kind":"identifier"}],"deprecated":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionErrorType","url":"\/documentation\/mapboxmaps\/offlineregionerrortype","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionErrorType/init(rawValue:)":{"type":"topic","url":"\/documentation\/mapboxmaps\/offlineregionerrortype\/init(rawvalue:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionErrorType\/init(rawValue:)","role":"symbol","kind":"symbol","deprecated":true,"abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"title":"init(rawValue:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Offline":{"role":"collectionGroup","title":"Offline Support","type":"topic","url":"\/documentation\/mapboxmaps\/offline","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","kind":"article","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMaps":{"type":"topic","abstract":[{"type":"text","text":"Maps rendering SDK also known as GL-Native"}],"url":"\/documentation\/mapboxmaps\/coremaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","title":"Core Maps API","kind":"article","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article","url":"\/documentation\/overview","role":"collection","abstract":[],"title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionErrorType\/title","op":"replace","value":"MBMOfflineRegionErrorType"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionErrorType\/fragments","op":"replace","value":[{"text":"MBMOfflineRegionErrorType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionErrorType\/navigatorTitle","op":"replace","value":[{"text":"MBMOfflineRegionErrorType","kind":"identifier"}]}]}]}