{"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Whether the fade in\/out symbol placement transition is enabled. Defaults to ","type":"text"},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"sections":[],"metadata":{"modules":[{"name":"MapboxMaps"}],"navigatorTitle":[{"text":"enablePlacementTransitions","kind":"identifier"}],"externalID":"c:objc(cs)MBMTransitionOptions(py)enablePlacementTransitions","title":"enablePlacementTransitions","roleHeading":"Instance Property","fragments":[{"kind":"identifier","text":"enablePlacementTransitions"}],"symbolKind":"property","role":"symbol"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMapsInternal","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TransitionOptions-swift.class"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"enablePlacementTransitions"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/mapboxmaps\/mbmtransitionoptions\/enableplacementtransitions"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMTransitionOptions\/enablePlacementTransitions"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMapsInternal":{"url":"\/documentation\/mapboxmaps\/coremapsinternal","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMapsInternal","type":"topic","kind":"article","title":"CoreMaps - Internal","abstract":[{"type":"text","text":"Maps rendering SDK also known as GL-Native. These are for internal use only."}],"role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","role":"collection","kind":"article","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TransitionOptions-swift.class":{"kind":"symbol","title":"TransitionOptions","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TransitionOptions"}],"url":"\/documentation\/mapboxmaps\/transitionoptions-swift.class","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TransitionOptions-swift.class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TransitionOptions","kind":"identifier"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"transition options"},{"type":"text","text":" controls timing for the interpolation between a transitionable style"},{"text":" ","type":"text"},{"type":"text","text":"property’s previous value and new value. These can be used to define the style default property"},{"type":"text","text":" "},{"text":"transition behavior. Also, any transitionable style property may also have its own ","type":"text"},{"type":"codeVoice","code":"-transition"},{"type":"text","text":" "},{"type":"text","text":"property that defines specific transition timing for that specific layer property, overriding"},{"text":" ","type":"text"},{"type":"text","text":"the global transition values."}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMTransitionOptions/enablePlacementTransitions":{"abstract":[{"text":"Whether the fade in\/out symbol placement transition is enabled. Defaults to ","type":"text"},{"type":"codeVoice","code":"true"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMTransitionOptions\/enablePlacementTransitions","title":"enablePlacementTransitions","kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"enablePlacementTransitions"}],"type":"topic","url":"\/documentation\/mapboxmaps\/mbmtransitionoptions\/enableplacementtransitions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"type":"topic","role":"collection","url":"\/documentation\/mapboxmaps","title":"MapboxMaps","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"}},"variantOverrides":[{"patch":[{"op":"replace","value":"MBMTransitionOptions","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TransitionOptions-swift.class\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TransitionOptions-swift.class\/fragments","value":[{"kind":"identifier","text":"MBMTransitionOptions"}]},{"op":"replace","value":[{"text":"MBMTransitionOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TransitionOptions-swift.class\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}