{"metadata":{"navigatorTitle":[{"text":"PresentationTransactionMode","kind":"identifier"}],"externalID":"s:10MapboxMaps27PresentationTransactionModeO","roleHeading":"Enumeration","title":"PresentationTransactionMode","symbolKind":"enum","modules":[{"name":"MapboxMaps"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PresentationTransactionMode","kind":"identifier"}],"role":"symbol"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-View"]]},"sections":[],"abstract":[{"type":"text","text":"Determines if the underlying "},{"type":"codeVoice","code":"CAMetalLayer"},{"type":"text","text":" rendering output should synchronize with the Core Animation transactions."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PresentationTransactionMode","kind":"identifier"}]}]},{"content":[{"level":2,"anchor":"overview","type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"text":"This property controls the ","type":"text"},{"code":"CAMetalLayer.presentsWithTransaction","type":"codeVoice"},{"text":" property, please refer to its documentation.","type":"text"}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/mapboxmaps\/presentationtransactionmode"],"traits":[{"interfaceLanguage":"swift"}]}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapView","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapInitOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapInitOptionsProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AttributionURLOpener","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ConstrainMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/NorthOrientation","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportMode"],"anchor":"MapView","title":"MapView","generated":true}],"schemaVersion":{"patch":0,"major":0,"minor":3},"relationshipsSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH","doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PresentationTransactionMode"},"topicSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PresentationTransactionMode\/async","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PresentationTransactionMode\/automatic","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PresentationTransactionMode\/sync"],"anchor":"Enumeration-Cases","title":"Enumeration Cases","generated":true},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PresentationTransactionMode\/Equatable-Implementations"],"anchor":"Default-Implementations","title":"Default Implementations","generated":true}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map-View":{"abstract":[],"role":"collectionGroup","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-View","url":"\/documentation\/mapboxmaps\/map-view","title":"MapView","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","url":"\/documentation\/mapboxmaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/SH":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","title":"Swift.Hashable"},"doc://com.mapbox.MapboxMaps/SQ":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapInitOptionsProvider":{"abstract":[{"text":"A protocol used to provide ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapInitOptions","isActive":true,"type":"reference"},{"type":"text","text":" when initializing a "},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapView","isActive":true},{"type":"text","text":" with a Storyboard or"},{"type":"text","text":" "},{"type":"text","text":"a nib."}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"MapInitOptionsProvider","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapInitOptionsProvider","url":"\/documentation\/mapboxmaps\/mapinitoptionsprovider","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapInitOptionsProvider","kind":"identifier"}],"title":"MapInitOptionsProvider"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewportMode":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ViewportMode"}],"kind":"symbol","title":"ViewportMode","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ViewportMode"}],"url":"\/documentation\/mapboxmaps\/viewportmode","type":"topic","abstract":[{"type":"text","text":"Satisfies embedding platforms that requires the viewport coordinate systems to be set according to its standards."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapInitOptions":{"abstract":[{"text":"Options used when initializing ","type":"text"},{"code":"MapView","type":"codeVoice"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapInitOptions","url":"\/documentation\/mapboxmaps\/mapinitoptions","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapInitOptions"}],"title":"MapInitOptions","navigatorTitle":[{"kind":"identifier","text":"MapInitOptions"}],"type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/NorthOrientation":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/NorthOrientation","title":"NorthOrientation","url":"\/documentation\/mapboxmaps\/northorientation","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"NorthOrientation"}],"navigatorTitle":[{"kind":"identifier","text":"NorthOrientation"}],"abstract":[{"type":"text","text":"Describes the map orientation."}],"role":"symbol","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PresentationTransactionMode/automatic":{"title":"PresentationTransactionMode.automatic","abstract":[{"type":"text","text":"In automatic mode, the value is calculated dynamically. Meaning, the  "},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PresentationTransactionMode\/sync","isActive":true},{"type":"text","text":" option is used when there are view annotation on the map. The "},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PresentationTransactionMode\/async","isActive":true},{"type":"text","text":" is used otherwise."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PresentationTransactionMode\/automatic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"automatic","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/presentationtransactionmode\/automatic","role":"symbol","kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PresentationTransactionMode/sync":{"role":"symbol","title":"PresentationTransactionMode.sync","type":"topic","url":"\/documentation\/mapboxmaps\/presentationtransactionmode\/sync","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"sync"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PresentationTransactionMode\/sync","abstract":[{"text":"The map render call is synchronized with Core Animation transaction (","type":"text"},{"type":"codeVoice","code":"presentsWithTransaction = true"},{"text":").","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapView":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapView","role":"symbol","navigatorTitle":[{"text":"MapView","kind":"identifier"}],"title":"MapView","url":"\/documentation\/mapboxmaps\/mapview","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapView","kind":"identifier"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","kind":"article","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapOptions":{"type":"topic","title":"MapOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapOptions"}],"role":"symbol","abstract":[{"type":"text","text":"Describes the map option values."}],"navigatorTitle":[{"kind":"identifier","text":"MapOptions"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapOptions","kind":"symbol","url":"\/documentation\/mapboxmaps\/mapoptions"},"doc://com.mapbox.MapboxMaps/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s8SendableP","title":"Swift.Sendable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GlyphsRasterizationOptions":{"title":"GlyphsRasterizationOptions","type":"topic","url":"\/documentation\/mapboxmaps\/glyphsrasterizationoptions","abstract":[{"type":"text","text":"Describes the glyphs rasterization option values."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationOptions","navigatorTitle":[{"text":"GlyphsRasterizationOptions","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GlyphsRasterizationOptions","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PresentationTransactionMode":{"abstract":[{"type":"text","text":"Determines if the underlying "},{"code":"CAMetalLayer","type":"codeVoice"},{"type":"text","text":" rendering output should synchronize with the Core Animation transactions."}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"PresentationTransactionMode","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PresentationTransactionMode","url":"\/documentation\/mapboxmaps\/presentationtransactionmode","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PresentationTransactionMode","kind":"identifier"}],"title":"PresentationTransactionMode"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PresentationTransactionMode/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","type":"topic","kind":"article","abstract":[],"url":"\/documentation\/mapboxmaps\/presentationtransactionmode\/equatable-implementations","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PresentationTransactionMode\/Equatable-Implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GlyphsRasterizationMode":{"url":"\/documentation\/mapboxmaps\/glyphsrasterizationmode","abstract":[{"type":"text","text":"Describes glyphs rasterization modes."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GlyphsRasterizationMode"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GlyphsRasterizationMode"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode","type":"topic","title":"GlyphsRasterizationMode"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PresentationTransactionMode/async":{"kind":"symbol","abstract":[{"type":"text","text":"The map render call is synchronized with Core Animation transaction ("},{"type":"codeVoice","code":"presentsWithTransaction = false"},{"type":"text","text":")."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PresentationTransactionMode\/async","role":"symbol","url":"\/documentation\/mapboxmaps\/presentationtransactionmode\/async","title":"PresentationTransactionMode.async","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"async","kind":"identifier"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AttributionURLOpener":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AttributionURLOpener","kind":"identifier"}],"navigatorTitle":[{"text":"AttributionURLOpener","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/attributionurlopener","title":"AttributionURLOpener","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AttributionURLOpener","kind":"symbol","abstract":[{"type":"text","text":"A protocol to open attribution URLs."}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ConstrainMode":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConstrainMode","kind":"identifier"}],"abstract":[{"text":"Describes whether to constrain the map in both axes or only vertically e.g. while panning.","type":"text"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/constrainmode","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ConstrainMode","navigatorTitle":[{"text":"ConstrainMode","kind":"identifier"}],"role":"symbol","title":"ConstrainMode"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MBMViewportMode","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewportMode\/title"},{"value":[{"text":"MBMViewportMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewportMode\/fragments"},{"value":[{"kind":"identifier","text":"MBMViewportMode"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewportMode\/navigatorTitle"},{"value":"MBMNorthOrientation","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1NorthOrientation\/title"},{"value":[{"text":"MBMNorthOrientation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1NorthOrientation\/fragments"},{"value":[{"kind":"identifier","text":"MBMNorthOrientation"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1NorthOrientation\/navigatorTitle"},{"value":"MBMMapOptions","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapOptions\/title"},{"value":[{"kind":"identifier","text":"MBMMapOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapOptions\/fragments"},{"value":[{"text":"MBMMapOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapOptions\/navigatorTitle"},{"value":"MBMGlyphsRasterizationOptions","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationOptions\/title"},{"value":[{"text":"MBMGlyphsRasterizationOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationOptions\/fragments"},{"value":[{"text":"MBMGlyphsRasterizationOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationOptions\/navigatorTitle"},{"value":"MBMGlyphsRasterizationMode","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/title"},{"value":[{"text":"MBMGlyphsRasterizationMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/fragments"},{"value":[{"text":"MBMGlyphsRasterizationMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/navigatorTitle"},{"value":"MBMConstrainMode","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ConstrainMode\/title"},{"value":[{"text":"MBMConstrainMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ConstrainMode\/fragments"},{"value":[{"text":"MBMConstrainMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ConstrainMode\/navigatorTitle"}]}]}