{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Projection"}],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"A collection of "},{"isActive":true,"type":"reference","identifier":"https:\/\/en.wikipedia.org\/wiki\/Web_Mercator_projection"},{"type":"text","text":" projection methods."}],"sections":[],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Projection"}],"navigatorTitle":[{"kind":"identifier","text":"Projection"}],"title":"Projection","externalID":"s:10MapboxMaps10ProjectionC","role":"symbol","symbolKind":"class","modules":[{"name":"MapboxMaps"}],"roleHeading":"Class"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs"]]},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Projection","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/mapboxmaps\/projection"],"traits":[{"interfaceLanguage":"swift"}]}],"topicSections":[{"generated":true,"title":"Type Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Projection\/latitudeMax","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Projection\/latitudeMin","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Projection\/latitudeRange"],"anchor":"Type-Properties"},{"generated":true,"title":"Type Methods","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Projection\/coordinate(for:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Projection\/metersPerPoint(for:zoom:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Projection\/project(_:zoomScale:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Projection\/unproject(_:zoomScale:)"],"anchor":"Type-Methods"}],"seeAlsoSections":[{"generated":true,"title":"MapboxMap","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraState","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBounds","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBoundsOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBoundsZoom","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateInfo","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ContextMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapCenterAltitudeMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometry","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometryConvertible"],"anchor":"MapboxMap"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Projection/latitudeMin":{"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"latitudeMin","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CLLocationDegrees","kind":"typeIdentifier","preciseIdentifier":"c:@T@CLLocationDegrees"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/projection\/latitudemin","abstract":[{"type":"text","text":"Minimum supported latitude value."}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Projection\/latitudeMin","title":"latitudeMin"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Projection/project(_:zoomScale:)":{"role":"symbol","abstract":[{"text":"Calculate a point on the map in Mercator Projection for a given","type":"text"},{"text":" ","type":"text"},{"text":"coordinate at the specified zoom scale.","type":"text"}],"type":"topic","title":"project(_:zoomScale:)","kind":"symbol","url":"\/documentation\/mapboxmaps\/projection\/project(_:zoomscale:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Projection\/project(_:zoomScale:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"project","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"text":", ","kind":"text"},{"text":"zoomScale","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":") -> ","kind":"text"},{"text":"MercatorCoordinate","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMMercatorCoordinate"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateBoundsZoom":{"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CoordinateBoundsZoom"}],"abstract":[{"type":"text","text":"A coordinate bounds and zoom."}],"url":"\/documentation\/mapboxmaps\/coordinateboundszoom","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoordinateBoundsZoom"}],"title":"CoordinateBoundsZoom","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBoundsZoom"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapCenterAltitudeMode":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapCenterAltitudeMode"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapCenterAltitudeMode","url":"\/documentation\/mapboxmaps\/mapcenteraltitudemode","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MapCenterAltitudeMode"}],"title":"MapCenterAltitudeMode","abstract":[{"type":"text","text":"Defines how the map center point should react to terrain elevation changes."}],"type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateInfo":{"title":"CoordinateInfo","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoordinateInfo","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateInfo","type":"topic","abstract":[{"type":"text","text":"Represents the coordinate information returned by the "},{"type":"codeVoice","code":"coordinateInfoForPixel"},{"type":"text","text":" or "},{"type":"codeVoice","code":"coordinatesInfoForPixels"},{"type":"text","text":" methods."}],"url":"\/documentation\/mapboxmaps\/coordinateinfo","navigatorTitle":[{"text":"CoordinateInfo","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","kind":"article","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Projection/latitudeMax":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Projection\/latitudeMax","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"latitudeMax","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CLLocationDegrees","kind":"typeIdentifier","preciseIdentifier":"c:@T@CLLocationDegrees"}],"title":"latitudeMax","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Maximum supported latitude value."}],"url":"\/documentation\/mapboxmaps\/projection\/latitudemax"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ContextMode":{"url":"\/documentation\/mapboxmaps\/contextmode","abstract":[{"text":"Describes the map context mode.","type":"text"},{"text":" ","type":"text"},{"text":"We can make some optimizations if we know that the drawing context is not shared with other code.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ContextMode","navigatorTitle":[{"text":"ContextMode","kind":"identifier"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContextMode","kind":"identifier"}],"kind":"symbol","type":"topic","title":"ContextMode"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Projection/latitudeRange":{"url":"\/documentation\/mapboxmaps\/projection\/latituderange","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"latitudeRange"},{"kind":"text","text":": ("},{"preciseIdentifier":"s:SN","kind":"typeIdentifier","text":"ClosedRange"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@T@CLLocationDegrees","kind":"typeIdentifier","text":"CLLocationDegrees"},{"kind":"text","text":">)"}],"title":"latitudeRange","type":"topic","abstract":[{"text":"Valid mercator latitude range.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Projection\/latitudeRange"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MapboxMap"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapboxMap"}],"title":"MapboxMap","abstract":[{"text":"Provides access to the map model, including the camera, style, observable map events,","type":"text"},{"text":" ","type":"text"},{"text":"and querying rendered features.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","role":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraBoundsOptions":{"abstract":[{"text":"Holds options to be used for setting camera bounds.","type":"text"}],"title":"CameraBoundsOptions","type":"topic","navigatorTitle":[{"text":"CameraBoundsOptions","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/cameraboundsoptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBoundsOptions","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraBoundsOptions","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","role":"collectionGroup","title":"MapboxMap","type":"topic","kind":"article","abstract":[],"url":"\/documentation\/mapboxmaps\/mapboxmap-apis"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateBounds":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoordinateBounds"}],"abstract":[{"type":"text","text":"A rectangular area as measured on a two-dimensional map projection."}],"url":"\/documentation\/mapboxmaps\/coordinatebounds","role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds","navigatorTitle":[{"kind":"identifier","text":"CoordinateBounds"}],"title":"CoordinateBounds","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Projection":{"title":"Projection","url":"\/documentation\/mapboxmaps\/projection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Projection"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Projection","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Projection"}],"abstract":[{"type":"text","text":"A collection of "},{"identifier":"https:\/\/en.wikipedia.org\/wiki\/Web_Mercator_projection","type":"reference","isActive":true},{"type":"text","text":" projection methods."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderedQueryGeometryConvertible":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RenderedQueryGeometryConvertible"}],"navigatorTitle":[{"kind":"identifier","text":"RenderedQueryGeometryConvertible"}],"role":"symbol","abstract":[{"text":"A convenience protocol for automatic conversion to ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometry","isActive":true,"type":"reference"},{"text":".","type":"text"}],"url":"\/documentation\/mapboxmaps\/renderedquerygeometryconvertible","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometryConvertible","kind":"symbol","type":"topic","title":"RenderedQueryGeometryConvertible"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GlyphsRasterizationMode":{"url":"\/documentation\/mapboxmaps\/glyphsrasterizationmode","abstract":[{"type":"text","text":"Describes glyphs rasterization modes."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GlyphsRasterizationMode"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GlyphsRasterizationMode"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode","type":"topic","title":"GlyphsRasterizationMode"},"https://en.wikipedia.org/wiki/Web_Mercator_projection":{"type":"link","title":"Spherical Mercator","titleInlineContent":[{"text":"Spherical Mercator","type":"text"}],"url":"https:\/\/en.wikipedia.org\/wiki\/Web_Mercator_projection","identifier":"https:\/\/en.wikipedia.org\/wiki\/Web_Mercator_projection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderedQueryGeometry":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/renderedquerygeometry","type":"topic","abstract":[{"text":"A geometry to define a portion of screen that should be queried for rendered features.","type":"text"}],"title":"RenderedQueryGeometry","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"RenderedQueryGeometry"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometry","navigatorTitle":[{"kind":"identifier","text":"RenderedQueryGeometry"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Projection/metersPerPoint(for:zoom:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Projection\/metersPerPoint(for:zoom:)","url":"\/documentation\/mapboxmaps\/projection\/metersperpoint(for:zoom:)","type":"topic","title":"metersPerPoint(for:zoom:)","abstract":[{"text":"Calculate distance spanned by one pixel at the specified latitude and","type":"text"},{"text":" ","type":"text"},{"text":"zoom level.","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"metersPerPoint","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CLLocationDegrees","kind":"typeIdentifier","preciseIdentifier":"c:@T@CLLocationDegrees"},{"text":", ","kind":"text"},{"text":"zoom","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":") -> ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraOptions":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraOptions","role":"symbol","title":"CameraOptions","url":"\/documentation\/mapboxmaps\/cameraoptions","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraOptions"}],"navigatorTitle":[{"kind":"identifier","text":"CameraOptions"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraBounds":{"role":"symbol","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraBounds","kind":"identifier"}],"abstract":[{"type":"text","text":"Holds information about camera bounds."}],"navigatorTitle":[{"text":"CameraBounds","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/camerabounds","type":"topic","title":"CameraBounds","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBounds"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Projection/coordinate(for:)":{"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"coordinate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ProjectedMeters","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMProjectedMeters"},{"text":") -> ","kind":"text"},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"}],"abstract":[{"text":"Calculate a coordinate for a Spherical Mercator projected","type":"text"},{"text":" ","type":"text"},{"text":"meters.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Projection\/coordinate(for:)","type":"topic","kind":"symbol","title":"coordinate(for:)","url":"\/documentation\/mapboxmaps\/projection\/coordinate(for:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraState":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/camerastate","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraState","abstract":[],"title":"CameraState","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraState"}],"navigatorTitle":[{"kind":"identifier","text":"CameraState"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapError":{"type":"topic","abstract":[{"text":"Type of errors thrown by the ","type":"text"},{"code":"MapboxMap","type":"codeVoice"},{"text":" APIs.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapError","role":"symbol","kind":"symbol","url":"\/documentation\/mapboxmaps\/maperror","navigatorTitle":[{"kind":"identifier","text":"MapError"}],"title":"MapError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapError"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Projection/unproject(_:zoomScale:)":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Projection\/unproject(_:zoomScale:)","type":"topic","abstract":[{"type":"text","text":"Calculate a coordinate for a given point on the map in Mercator Projection."}],"title":"unproject(_:zoomScale:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unproject","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MercatorCoordinate","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMMercatorCoordinate"},{"text":", ","kind":"text"},{"text":"zoomScale","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":") -> ","kind":"text"},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"}],"url":"\/documentation\/mapboxmaps\/projection\/unproject(_:zoomscale:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","url":"\/documentation\/mapboxmaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","title":"MapboxMaps"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBoundsZoom\/title","op":"replace","value":"MBMCoordinateBoundsZoom"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBoundsZoom\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMCoordinateBoundsZoom"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBoundsZoom\/navigatorTitle","op":"replace","value":[{"text":"MBMCoordinateBoundsZoom","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapCenterAltitudeMode\/title","op":"replace","value":"MBMMapCenterAltitudeMode"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapCenterAltitudeMode\/fragments","op":"replace","value":[{"text":"MBMMapCenterAltitudeMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapCenterAltitudeMode\/navigatorTitle","op":"replace","value":[{"text":"MBMMapCenterAltitudeMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateInfo\/title","op":"replace","value":"MBMCoordinateInfo"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateInfo\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMCoordinateInfo"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateInfo\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMCoordinateInfo"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ContextMode\/title","op":"replace","value":"MBMContextMode"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ContextMode\/fragments","op":"replace","value":[{"text":"MBMContextMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ContextMode\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMContextMode"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds\/title","op":"replace","value":"MBMCoordinateBounds"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds\/fragments","op":"replace","value":[{"text":"MBMCoordinateBounds","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMCoordinateBounds"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/title","op":"replace","value":"MBMGlyphsRasterizationMode"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/fragments","op":"replace","value":[{"text":"MBMGlyphsRasterizationMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/navigatorTitle","op":"replace","value":[{"text":"MBMGlyphsRasterizationMode","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}