{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources"]]},"kind":"symbol","topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceInfo\/init(id:type:)"],"anchor":"Initializers","generated":true},{"title":"Instance Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceInfo\/id","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceInfo\/type"],"anchor":"Instance-Properties","generated":true}],"metadata":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SourceInfo","kind":"identifier"}],"externalID":"s:10MapboxMaps10SourceInfoV","roleHeading":"Structure","role":"symbol","title":"SourceInfo","modules":[{"name":"MapboxMaps"}],"navigatorTitle":[{"text":"SourceInfo","kind":"identifier"}],"symbolKind":"struct"},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceInfo","interfaceLanguage":"swift"},"sections":[],"abstract":[{"text":"Information about a Source","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"seeAlsoSections":[{"title":"Sources","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Source","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSourceData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterArraySource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/VectorSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PromoteId","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Scheme","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Encoding","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatusChangedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatus","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileFunctionCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetSize"],"anchor":"Sources","generated":true}],"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"],"kind":"relationships","type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SourceInfo","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/sourceinfo"]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ImageSource":{"type":"topic","navigatorTitle":[{"text":"ImageSource","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageSource","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/imagesource","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageSource","abstract":[{"type":"text","text":"An image data source."}],"title":"ImageSource","kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GeoJSONSourceData":{"abstract":[{"text":"Captures potential values of the ","type":"text"},{"code":"data","type":"codeVoice"},{"text":" property of a GeoJSONSource.","type":"text"}],"type":"topic","url":"\/documentation\/mapboxmaps\/geojsonsourcedata","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GeoJSONSourceData","kind":"identifier"}],"title":"GeoJSONSourceData","navigatorTitle":[{"kind":"identifier","text":"GeoJSONSourceData"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSourceData"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterSource":{"abstract":[{"text":"A raster tile source.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"RasterSource","kind":"identifier"}],"title":"RasterSource","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterSource","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RasterSource","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/rastersource","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","url":"\/documentation\/mapboxmaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceOptions":{"abstract":[{"text":"Options for custom raster source.","type":"text"}],"type":"topic","url":"\/documentation\/mapboxmaps\/customrastersourceoptions","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomRasterSourceOptions","kind":"identifier"}],"navigatorTitle":[{"text":"CustomRasterSourceOptions","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions","title":"CustomRasterSourceOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceClient":{"url":"\/documentation\/mapboxmaps\/customrastersourceclient","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomRasterSourceClient"}],"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient","title":"CustomRasterSourceClient","navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceClient"}],"role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomGeometrySourceOptions":{"abstract":[{"text":"Options for custom geometry source.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions","role":"symbol","title":"CustomGeometrySourceOptions","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomGeometrySourceOptions","kind":"identifier"}],"navigatorTitle":[{"text":"CustomGeometrySourceOptions","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/customgeometrysourceoptions","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceClientType":{"url":"\/documentation\/mapboxmaps\/customrastersourceclienttype","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType","role":"symbol","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomRasterSourceClientType","kind":"identifier"}],"abstract":[],"type":"topic","title":"CustomRasterSourceClientType","navigatorTitle":[{"text":"CustomRasterSourceClientType","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudgetSize":{"navigatorTitle":[{"kind":"identifier","text":"TileCacheBudgetSize"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileCacheBudgetSize"}],"title":"TileCacheBudgetSize","role":"symbol","url":"\/documentation\/mapboxmaps\/tilecachebudgetsize","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetSize","type":"topic","abstract":[{"type":"text","text":"Defines a TileCacheBudgetSize, which can be set as either a megabyte or tile count limit."},{"type":"text","text":" "},{"type":"text","text":"Whenever tile cache goes over the defined limit"},{"type":"text","text":" "},{"type":"text","text":"the least recently used tile will be evicted from the in-memory cache"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Source":{"type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/source","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Source","abstract":[],"title":"Source","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Source","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"Source","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Encoding":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Encoding","kind":"identifier"}],"navigatorTitle":[{"text":"Encoding","kind":"identifier"}],"type":"topic","title":"Encoding","kind":"symbol","abstract":[{"type":"text","text":"The encoding used by this source. Mapbox Terrain RGB is used by default"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Encoding","url":"\/documentation\/mapboxmaps\/encoding"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomGeometrySource":{"abstract":[{"type":"text","text":"Describes a Custom Geometry Source to be used in the style"}],"kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/customgeometrysource","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomGeometrySource","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySource","navigatorTitle":[{"text":"CustomGeometrySource","kind":"identifier"}],"title":"CustomGeometrySource"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterDemSource":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource","url":"\/documentation\/mapboxmaps\/rasterdemsource","abstract":[{"type":"text","text":"A RGB-encoded raster DEM source"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"RasterDemSource"}],"title":"RasterDemSource","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"RasterDemSource"}],"kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceInfo/init(id:type:)":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/sourceinfo\/init(id:type:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps10SourceTypeV","text":"SourceType","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceInfo\/init(id:type:)","role":"symbol","abstract":[{"type":"text","text":"Create a "},{"code":"SourceInfo","type":"codeVoice"},{"type":"text","text":" value"}],"title":"init(id:type:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileStatusChangedCallback":{"navigatorTitle":[{"text":"CustomRasterSourceTileStatusChangedCallback","kind":"identifier"}],"title":"CustomRasterSourceTileStatusChangedCallback","url":"\/documentation\/mapboxmaps\/customrastersourcetilestatuschangedcallback","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomRasterSourceTileStatusChangedCallback","kind":"identifier"}],"abstract":[{"type":"text","text":"Callback for changing a CustomRasterSource tile status."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatusChangedCallback","role":"symbol","type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","kind":"article","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterArraySource":{"url":"\/documentation\/mapboxmaps\/rasterarraysource","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RasterArraySource","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterArraySource","abstract":[{"type":"text","text":"A raster array source"}],"type":"topic","title":"RasterArraySource","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"RasterArraySource"}],"kind":"symbol","tags":[{"type":"spi","text":"SPI"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceInfo":{"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceInfo"}],"kind":"symbol","role":"symbol","title":"SourceInfo","navigatorTitle":[{"kind":"identifier","text":"SourceInfo"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceInfo","abstract":[{"text":"Information about a Source","type":"text"}],"url":"\/documentation\/mapboxmaps\/sourceinfo"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileFunctionCallback":{"abstract":[{"text":"Callback to do various operations for tile.","type":"text"},{"text":" ","type":"text"},{"text":"For example, fetching a tile or cancelling a tile request.","type":"text"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileFunctionCallback","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"TileFunctionCallback","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileFunctionCallback","type":"topic","title":"TileFunctionCallback","url":"\/documentation\/mapboxmaps\/tilefunctioncallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceInfo/type":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps10SourceTypeV","text":"SourceType","kind":"typeIdentifier"}],"abstract":[{"text":"The type of the source","type":"text"}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/sourceinfo\/type","title":"type","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceInfo\/type"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSource":{"type":"topic","url":"\/documentation\/mapboxmaps\/customrastersource","abstract":[{"type":"text","text":"Describes a Custom Raster Source to be used in the style."}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSource","title":"CustomRasterSource","navigatorTitle":[{"text":"CustomRasterSource","kind":"identifier"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomRasterSource","kind":"identifier"}],"tags":[{"type":"spi","text":"SPI"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileRenderer":{"navigatorTitle":[{"text":"CustomRasterSourceTileRenderer","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomRasterSourceTileRenderer","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer","title":"CustomRasterSourceTileRenderer","url":"\/documentation\/mapboxmaps\/customrastersourcetilerenderer","kind":"symbol","role":"symbol","abstract":[{"text":"Interface for the direct rendering into the custom raster tiles.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PromoteId":{"url":"\/documentation\/mapboxmaps\/promoteid","kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PromoteId","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PromoteId","kind":"identifier"}],"title":"PromoteId","navigatorTitle":[{"text":"PromoteId","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileData":{"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomRasterSourceTileData","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileData","title":"CustomRasterSourceTileData","navigatorTitle":[{"text":"CustomRasterSourceTileData","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/customrastersourcetiledata","abstract":[{"type":"text","text":"Data for a specific CustomRasterSource tile."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceInfo/id":{"url":"\/documentation\/mapboxmaps\/sourceinfo\/id","kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceInfo\/id","abstract":[{"type":"text","text":"The identifier of the source"}],"role":"symbol","title":"id","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GeoJSONSource":{"type":"topic","url":"\/documentation\/mapboxmaps\/geojsonsource","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GeoJSONSource","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"A GeoJSON data source.","type":"text"}],"title":"GeoJSONSource","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSource","navigatorTitle":[{"text":"GeoJSONSource","kind":"identifier"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Sources":{"kind":"article","url":"\/documentation\/mapboxmaps\/sources","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources","abstract":[],"role":"collectionGroup","title":"Sources","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Scheme":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Scheme","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Scheme"}],"navigatorTitle":[{"kind":"identifier","text":"Scheme"}],"url":"\/documentation\/mapboxmaps\/scheme","type":"topic","title":"Scheme","abstract":[{"text":"Influences the y direction of the tile coordinates. The global-mercator (aka Spherical Mercator) profile is assumed.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/VectorSource":{"title":"VectorSource","role":"symbol","navigatorTitle":[{"text":"VectorSource","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/vectorsource","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/VectorSource","abstract":[{"type":"text","text":"A vector tile source."}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"VectorSource","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceType":{"title":"SourceType","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SourceType","kind":"identifier"}],"navigatorTitle":[{"text":"SourceType","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/sourcetype","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceType","abstract":[{"type":"text","text":"Struct of supported Source Types"},{"type":"text","text":" "},{"text":"Docs : https:\/\/docs.mapbox.com\/mapbox-gl-js\/style-spec\/sources\/","type":"text"}],"kind":"symbol","type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileStatus":{"url":"\/documentation\/mapboxmaps\/customrastersourcetilestatus","abstract":[{"text":"CustomRasterSource tile status.","type":"text"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomRasterSourceTileStatus","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"CustomRasterSourceTileStatus","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatus","title":"CustomRasterSourceTileStatus"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/title","op":"replace","value":"MBMCustomRasterSourceOptions"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/fragments","op":"replace","value":[{"text":"MBMCustomRasterSourceOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMCustomRasterSourceOptions"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient\/title","op":"replace","value":"MBMCustomRasterSourceClient"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient\/fragments","op":"replace","value":[{"text":"MBMCustomRasterSourceClient","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient\/navigatorTitle","op":"replace","value":[{"text":"MBMCustomRasterSourceClient","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions\/title","op":"replace","value":"MBMCustomGeometrySourceOptions"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMCustomGeometrySourceOptions"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions\/navigatorTitle","op":"replace","value":[{"text":"MBMCustomGeometrySourceOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType\/title","op":"replace","value":"MBMCustomRasterSourceClientType"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType\/fragments","op":"replace","value":[{"text":"MBMCustomRasterSourceClientType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType\/navigatorTitle","op":"replace","value":[{"text":"MBMCustomRasterSourceClientType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatusChangedCallback\/title","op":"replace","value":"MBMCustomRasterSourceTileStatusChangedCallback"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatusChangedCallback\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileStatusChangedCallback"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatusChangedCallback\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileStatusChangedCallback"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileFunctionCallback\/title","op":"replace","value":"MBMTileFunctionCallback"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileFunctionCallback\/fragments","op":"replace","value":[{"text":"MBMTileFunctionCallback","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileFunctionCallback\/navigatorTitle","op":"replace","value":[{"text":"MBMTileFunctionCallback","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer\/title","op":"replace","value":"MBMCustomRasterSourceTileRenderer"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileRenderer"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer\/navigatorTitle","op":"replace","value":[{"text":"MBMCustomRasterSourceTileRenderer","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileData\/title","op":"replace","value":"MBMCustomRasterSourceTileData"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileData\/fragments","op":"replace","value":[{"text":"MBMCustomRasterSourceTileData","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileData\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileData"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatus\/title","op":"replace","value":"MBMCustomRasterSourceTileStatus"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatus\/fragments","op":"replace","value":[{"text":"MBMCustomRasterSourceTileStatus","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatus\/navigatorTitle","op":"replace","value":[{"text":"MBMCustomRasterSourceTileStatus","kind":"identifier"}]}]}]}