{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ViewAnnotationManagerError"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/View-Annotations"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManagerError\/message"],"anchor":"Instance-Properties"},{"generated":true,"title":"Type Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManagerError\/annotatedFeatureMissing","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManagerError\/annotationNotFound","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManagerError\/viewIsAlreadyAdded"],"anchor":"Type-Properties"},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManagerError\/Equatable-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManagerError\/Error-Implementations"],"anchor":"Default-Implementations"}],"relationshipsSections":[{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/s5ErrorP","doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"]}],"seeAlsoSections":[{"generated":true,"title":"View Annotations","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManager","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchorConfig","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationPositionDescriptor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationUpdateObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchor"],"anchor":"View-Annotations"}],"metadata":{"title":"ViewAnnotationManagerError","externalID":"s:10MapboxMaps26ViewAnnotationManagerErrorV","symbolKind":"struct","navigatorTitle":[{"text":"ViewAnnotationManagerError","kind":"identifier"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ViewAnnotationManagerError","kind":"identifier"}],"roleHeading":"Structure","modules":[{"name":"MapboxMaps"}]},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManagerError","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/viewannotationmanagererror"]}],"sections":[],"kind":"symbol","references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationPositionDescriptor":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationPositionDescriptor","abstract":[{"type":"text","text":"Read-only data that is needed to correctly position the single view annotation on screen."},{"type":"text","text":" "},{"type":"text","text":"Used inside ViewAnnotationPositionsUpdateListener callback to notify the listener about the visible view annotations’ position updates."}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/viewannotationpositiondescriptor","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ViewAnnotationPositionDescriptor"}],"type":"topic","title":"ViewAnnotationPositionDescriptor","navigatorTitle":[{"kind":"identifier","text":"ViewAnnotationPositionDescriptor"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationManagerError/message":{"abstract":[],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"message","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"url":"\/documentation\/mapboxmaps\/viewannotationmanagererror\/message","title":"message","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManagerError\/message","type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationManagerError/annotationNotFound":{"type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/viewannotationmanagererror\/annotationnotfound","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManagerError\/annotationNotFound","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"annotationNotFound"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ViewAnnotationManagerError","preciseIdentifier":"s:10MapboxMaps26ViewAnnotationManagerErrorV"}],"abstract":[{"type":"text","text":"The specified annotation was not found"}],"title":"annotationNotFound"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationManagerError/annotatedFeatureMissing":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"annotatedFeatureMissing","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ViewAnnotationManagerError","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps26ViewAnnotationManagerErrorV"}],"url":"\/documentation\/mapboxmaps\/viewannotationmanagererror\/annotatedfeaturemissing","abstract":[{"type":"text","text":"The annotated feature is missing"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManagerError\/annotatedFeatureMissing","kind":"symbol","role":"symbol","title":"annotatedFeatureMissing","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationManager":{"url":"\/documentation\/mapboxmaps\/viewannotationmanager","title":"ViewAnnotationManager","abstract":[{"text":"Manager API to control View Annotations.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManager","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ViewAnnotationManager"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ViewAnnotationManager"}]},"doc://com.mapbox.MapboxMaps/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","kind":"article","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationManagerError/Error-Implementations":{"kind":"article","role":"collectionGroup","type":"topic","url":"\/documentation\/mapboxmaps\/viewannotationmanagererror\/error-implementations","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManagerError\/Error-Implementations","abstract":[],"title":"Error Implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationUpdateObserver":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationUpdateObserver","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ViewAnnotationUpdateObserver","kind":"identifier"}],"navigatorTitle":[{"text":"ViewAnnotationUpdateObserver","kind":"identifier"}],"type":"topic","abstract":[{"text":"An interface you use to detect when the map view lays out or updates visibility of annotation views.","type":"text"}],"title":"ViewAnnotationUpdateObserver","url":"\/documentation\/mapboxmaps\/viewannotationupdateobserver","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","url":"\/documentation\/mapboxmaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationOptions":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationOptions","navigatorTitle":[{"kind":"identifier","text":"ViewAnnotationOptions"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/viewannotationoptions","title":"ViewAnnotationOptions","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ViewAnnotationOptions"}],"abstract":[{"type":"text","text":"Stores layout and visibility settings for a view annotation."}],"type":"topic"},"doc://com.mapbox.MapboxMaps/s5ErrorP":{"type":"unresolvable","title":"Swift.Error","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s5ErrorP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationAnchor":{"abstract":[{"text":"Enum describing how to place view annotation relatively to geometry.","type":"text"}],"kind":"symbol","type":"topic","title":"ViewAnnotationAnchor","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchor","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ViewAnnotationAnchor"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ViewAnnotationAnchor"}],"url":"\/documentation\/mapboxmaps\/viewannotationanchor"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationAnchorConfig":{"role":"symbol","abstract":[{"type":"text","text":"Represents a specific setting for a view annotation anchor."}],"url":"\/documentation\/mapboxmaps\/viewannotationanchorconfig","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchorConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ViewAnnotationAnchorConfig"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ViewAnnotationAnchorConfig"}],"title":"ViewAnnotationAnchorConfig","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotation":{"abstract":[{"text":"Creates a view annotation.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ViewAnnotation"}],"title":"ViewAnnotation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation","type":"topic","url":"\/documentation\/mapboxmaps\/viewannotation","navigatorTitle":[{"kind":"identifier","text":"ViewAnnotation"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationManagerError/viewIsAlreadyAdded":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewIsAlreadyAdded"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ViewAnnotationManagerError","preciseIdentifier":"s:10MapboxMaps26ViewAnnotationManagerErrorV"}],"title":"viewIsAlreadyAdded","url":"\/documentation\/mapboxmaps\/viewannotationmanagererror\/viewisalreadyadded","role":"symbol","type":"topic","kind":"symbol","abstract":[{"text":"This view has alread been added","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManagerError\/viewIsAlreadyAdded"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationManagerError/Equatable-Implementations":{"url":"\/documentation\/mapboxmaps\/viewannotationmanagererror\/equatable-implementations","kind":"article","abstract":[],"type":"topic","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManagerError\/Equatable-Implementations","title":"Equatable Implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/View-Annotations":{"kind":"article","abstract":[],"type":"topic","url":"\/documentation\/mapboxmaps\/view-annotations","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/View-Annotations","title":"View Annotations","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationManagerError":{"role":"symbol","kind":"symbol","abstract":[],"title":"ViewAnnotationManagerError","url":"\/documentation\/mapboxmaps\/viewannotationmanagererror","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ViewAnnotationManagerError"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ViewAnnotationManagerError"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManagerError"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MBMViewAnnotationPositionDescriptor","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationPositionDescriptor\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MBMViewAnnotationPositionDescriptor"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationPositionDescriptor\/fragments","op":"replace"},{"value":[{"text":"MBMViewAnnotationPositionDescriptor","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationPositionDescriptor\/navigatorTitle","op":"replace"},{"value":"MBMViewAnnotationAnchor","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchor\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MBMViewAnnotationAnchor"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchor\/fragments","op":"replace"},{"value":[{"text":"MBMViewAnnotationAnchor","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchor\/navigatorTitle","op":"replace"},{"value":"MBMViewAnnotationAnchorConfig","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchorConfig\/title","op":"replace"},{"value":[{"text":"MBMViewAnnotationAnchorConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchorConfig\/fragments","op":"replace"},{"value":[{"text":"MBMViewAnnotationAnchorConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchorConfig\/navigatorTitle","op":"replace"}]}]}