{"metadata":{"roleHeading":"Class","role":"symbol","navigatorTitle":[{"text":"ViewAnnotationAnchorConfig","kind":"identifier"}],"title":"ViewAnnotationAnchorConfig","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ViewAnnotationAnchorConfig","kind":"identifier"}],"externalID":"c:objc(cs)MBMViewAnnotationAnchorConfig","modules":[{"name":"MapboxMaps"}]},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH"],"title":"Conforms To","type":"conformsTo"}],"abstract":[{"text":"Represents a specific setting for a view annotation anchor.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/View-Annotations"]]},"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchorConfig"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ViewAnnotationAnchorConfig","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/viewannotationanchorconfig"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/viewannotationanchorconfig"]}],"topicSections":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchorConfig\/anchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchorConfig\/offsetX","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchorConfig\/offsetY"],"title":"Instance Properties","generated":true},{"anchor":"Instance-Methods","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchorConfig\/isEqual(to:)"],"title":"Instance Methods","generated":true}],"seeAlsoSections":[{"anchor":"View-Annotations","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManager","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManagerError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationPositionDescriptor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationUpdateObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchor"],"title":"View Annotations","generated":true}],"references":{"doc://com.mapbox.MapboxMaps/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.mapbox.MapboxMaps/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotation":{"abstract":[{"text":"Creates a view annotation.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ViewAnnotation"}],"title":"ViewAnnotation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation","type":"topic","url":"\/documentation\/mapboxmaps\/viewannotation","navigatorTitle":[{"kind":"identifier","text":"ViewAnnotation"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationPositionDescriptor":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationPositionDescriptor","abstract":[{"type":"text","text":"Read-only data that is needed to correctly position the single view annotation on screen."},{"type":"text","text":" "},{"type":"text","text":"Used inside ViewAnnotationPositionsUpdateListener callback to notify the listener about the visible view annotations’ position updates."}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/viewannotationpositiondescriptor","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ViewAnnotationPositionDescriptor"}],"type":"topic","title":"ViewAnnotationPositionDescriptor","navigatorTitle":[{"kind":"identifier","text":"ViewAnnotationPositionDescriptor"}]},"doc://com.mapbox.MapboxMaps/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","url":"\/documentation\/mapboxmaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationAnchorConfig/offsetX":{"url":"\/documentation\/mapboxmaps\/viewannotationanchorconfig\/offsetx","navigatorTitle":[{"text":"offsetX","kind":"identifier"}],"abstract":[{"type":"text","text":"Extra X offset in "},{"code":"platform pixels","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"Providing positive value moves view annotation to the right while negative moves it to the left.","type":"text"},{"text":" ","type":"text"},{"text":"The default value is 0.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"offsetX","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"title":"offsetX","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchorConfig\/offsetX","kind":"symbol","role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationAnchorConfig/offsetY":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"offsetY","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"offsetY","kind":"identifier"}],"type":"topic","kind":"symbol","title":"offsetY","url":"\/documentation\/mapboxmaps\/viewannotationanchorconfig\/offsety","abstract":[{"text":"Extra Y offset in ","type":"text"},{"type":"codeVoice","code":"platform pixels"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"Providing positive value moves view annotation to the top while negative moves it to the bottom.","type":"text"},{"text":" ","type":"text"},{"text":"The default value is 0.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchorConfig\/offsetY"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationAnchorConfig/anchor":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchorConfig\/anchor","title":"anchor","type":"topic","abstract":[{"type":"text","text":"Anchor describing where the view annotation will be located relatively to given geometry."},{"type":"text","text":" "},{"type":"text","text":"The default value is "},{"type":"codeVoice","code":"CENTER"},{"type":"text","text":"."}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"anchor","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/viewannotationanchorconfig\/anchor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"anchor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ViewAnnotationAnchor","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMViewAnnotationAnchor"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationAnchorConfig/isEqual(to:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchorConfig\/isEqual(to:)","type":"topic","kind":"symbol","title":"isEqual(to:)","role":"symbol","abstract":[],"navigatorTitle":[{"text":"isEqualToViewAnnotationAnchorConfig:","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/viewannotationanchorconfig\/isequal(to:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ViewAnnotationAnchorConfig","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMViewAnnotationAnchorConfig"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationAnchor":{"abstract":[{"text":"Enum describing how to place view annotation relatively to geometry.","type":"text"}],"kind":"symbol","type":"topic","title":"ViewAnnotationAnchor","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchor","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ViewAnnotationAnchor"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ViewAnnotationAnchor"}],"url":"\/documentation\/mapboxmaps\/viewannotationanchor"},"doc://com.mapbox.MapboxMaps/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationAnchorConfig":{"role":"symbol","abstract":[{"type":"text","text":"Represents a specific setting for a view annotation anchor."}],"url":"\/documentation\/mapboxmaps\/viewannotationanchorconfig","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchorConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ViewAnnotationAnchorConfig"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ViewAnnotationAnchorConfig"}],"title":"ViewAnnotationAnchorConfig","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","kind":"article","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationManagerError":{"role":"symbol","kind":"symbol","abstract":[],"title":"ViewAnnotationManagerError","url":"\/documentation\/mapboxmaps\/viewannotationmanagererror","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ViewAnnotationManagerError"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ViewAnnotationManagerError"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManagerError"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationUpdateObserver":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationUpdateObserver","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ViewAnnotationUpdateObserver","kind":"identifier"}],"navigatorTitle":[{"text":"ViewAnnotationUpdateObserver","kind":"identifier"}],"type":"topic","abstract":[{"text":"An interface you use to detect when the map view lays out or updates visibility of annotation views.","type":"text"}],"title":"ViewAnnotationUpdateObserver","url":"\/documentation\/mapboxmaps\/viewannotationupdateobserver","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationOptions":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationOptions","navigatorTitle":[{"kind":"identifier","text":"ViewAnnotationOptions"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/viewannotationoptions","title":"ViewAnnotationOptions","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ViewAnnotationOptions"}],"abstract":[{"type":"text","text":"Stores layout and visibility settings for a view annotation."}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/View-Annotations":{"kind":"article","abstract":[],"type":"topic","url":"\/documentation\/mapboxmaps\/view-annotations","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/View-Annotations","title":"View Annotations","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject","title":"NSObject"},"doc://com.mapbox.MapboxMaps/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP"},"doc://com.mapbox.MapboxMaps/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","title":"Swift.Equatable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMViewAnnotationAnchorConfig/initWithAnchor:offsetX:offsetY:":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMViewAnnotationAnchorConfig\/initWithAnchor:offsetX:offsetY:","navigatorTitle":[{"text":"initWithAnchor:offsetX:offsetY:","kind":"identifier"}],"abstract":[],"kind":"symbol","type":"topic","title":"initWithAnchor:offsetX:offsetY:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithAnchor:offsetX:offsetY:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/mbmviewannotationanchorconfig\/initwithanchor:offsetx:offsety:"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationManager":{"url":"\/documentation\/mapboxmaps\/viewannotationmanager","title":"ViewAnnotationManager","abstract":[{"text":"Manager API to control View Annotations.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManager","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ViewAnnotationManager"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ViewAnnotationManager"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"MBMViewAnnotationAnchorConfig","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"MBMViewAnnotationAnchorConfig","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"MBMViewAnnotationAnchorConfig","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchorConfig\/anchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchorConfig\/offsetX","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchorConfig\/offsetY"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMViewAnnotationAnchorConfig\/initWithAnchor:offsetX:offsetY:","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchorConfig\/isEqual(to:)"],"generated":true,"anchor":"Instance-Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"]}],"op":"replace"},{"path":"\/seeAlsoSections","value":[{"title":"View Annotations","anchor":"View-Annotations","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationPositionDescriptor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchor"],"generated":true}],"op":"replace"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBMViewAnnotationAnchorConfig","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationPositionDescriptor\/title","value":"MBMViewAnnotationPositionDescriptor","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationPositionDescriptor\/fragments","value":[{"text":"MBMViewAnnotationPositionDescriptor","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationPositionDescriptor\/navigatorTitle","value":[{"text":"MBMViewAnnotationPositionDescriptor","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchorConfig~1offsetX\/title","value":"offsetX"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchorConfig~1offsetX\/fragments","value":[{"text":"offsetX","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchorConfig~1offsetY\/title","value":"offsetY"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchorConfig~1offsetY\/fragments","value":[{"text":"offsetY","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchorConfig~1anchor\/title","value":"anchor"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchorConfig~1anchor\/fragments","value":[{"text":"anchor","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchorConfig~1isEqual(to:)\/title","value":"isEqualToViewAnnotationAnchorConfig:"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchorConfig~1isEqual(to:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"isEqualToViewAnnotationAnchorConfig:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchor\/title","value":"MBMViewAnnotationAnchor"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchor\/fragments","value":[{"text":"MBMViewAnnotationAnchor","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchor\/navigatorTitle","value":[{"text":"MBMViewAnnotationAnchor","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchorConfig\/title","value":"MBMViewAnnotationAnchorConfig"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchorConfig\/fragments","value":[{"kind":"identifier","text":"MBMViewAnnotationAnchorConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchorConfig\/navigatorTitle","value":[{"kind":"identifier","text":"MBMViewAnnotationAnchorConfig"}]}]}]}