{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestError\/recoverySuggestion","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/httprequesterror\/recoverysuggestion"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"recoverySuggestion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestError\/LocalizedError-Implementations"]]},"abstract":[{"type":"text","text":"Inherited from "},{"code":"LocalizedError.recoverySuggestion","type":"codeVoice"},{"type":"text","text":"."}],"sections":[],"metadata":{"symbolKind":"property","extendedModule":"Foundation","roleHeading":"Instance Property","role":"symbol","modules":[{"name":"MapboxCommon","relatedModules":["Foundation"]}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"recoverySuggestion","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"externalID":"s:10Foundation14LocalizedErrorPAAE18recoverySuggestionSSSgvp::SYNTHESIZED::c:objc(cs)MBXHttpRequestError","platforms":[{"name":"iOS","introducedAt":"8.0","deprecated":false,"unavailable":false,"beta":false},{"name":"iPadOS","unavailable":false,"introducedAt":"8.0","beta":false,"deprecated":false},{"introducedAt":"8.0","unavailable":false,"beta":false,"deprecated":false,"name":"Mac Catalyst"},{"deprecated":false,"beta":false,"introducedAt":"10.10","name":"macOS","unavailable":false},{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"9.0","name":"tvOS"},{"name":"watchOS","deprecated":false,"introducedAt":"2.0","unavailable":false,"beta":false}],"title":"recoverySuggestion"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestError/recoverySuggestion":{"title":"recoverySuggestion","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestError\/recoverySuggestion","url":"\/documentation\/mapboxcommon\/httprequesterror\/recoverysuggestion","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"recoverySuggestion","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"abstract":[],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","url":"\/documentation\/overview","kind":"article","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestError":{"navigatorTitle":[{"kind":"identifier","text":"HttpRequestError"}],"abstract":[{"type":"text","text":"Record which contains detailed information about HTTP error happened during request\/download call."}],"title":"HttpRequestError","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestError","kind":"symbol","url":"\/documentation\/mapboxcommon\/httprequesterror","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HttpRequestError","kind":"identifier"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestError/LocalizedError-Implementations":{"abstract":[],"kind":"article","role":"collectionGroup","title":"LocalizedError Implementations","url":"\/documentation\/mapboxcommon\/httprequesterror\/localizederror-implementations","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestError\/LocalizedError-Implementations","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","kind":"symbol","url":"\/documentation\/mapboxcommon","type":"topic","role":"collection","abstract":[],"title":"MapboxCommon"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestError\/title","value":"MBXHttpRequestError"},{"op":"replace","value":[{"kind":"identifier","text":"MBXHttpRequestError"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestError\/fragments"},{"op":"replace","value":[{"text":"MBXHttpRequestError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestError\/navigatorTitle"}]}]}