{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onAvailabilityChanged","kind":"identifier"},{"kind":"text","text":"("},{"text":"forIsAvailable","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"isAvailable"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"True if available, false if it’s not."}]}],"name":"isAvailable"}],"kind":"parameters"}],"metadata":{"role":"symbol","symbolKind":"method","navigatorTitle":[{"text":"onAvailabilityChangedForIsAvailable:","kind":"identifier"}],"modules":[{"name":"MapboxCommon"}],"required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onAvailabilityChanged","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forIsAvailable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"title":"onAvailabilityChanged(forIsAvailable:)","externalID":"c:objc(pl)MBXLocationServiceObserver(im)onAvailabilityChangedForIsAvailable:","roleHeading":"Instance Method"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Called when an availability of location-based service on"},{"type":"text","text":" "},{"text":"the device has been changed. This happens when, for example,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"a user disables geolocation on the device."}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver\/onAvailabilityChanged(forIsAvailable:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/locationserviceobserver\/onavailabilitychanged(forisavailable:)"]},{"paths":["\/documentation\/mapboxcommon\/locationserviceobserver\/onavailabilitychanged(forisavailable:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Location-APIs":{"kind":"article","url":"\/documentation\/mapboxmaps\/location-apis","role":"collectionGroup","title":"Location","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationServiceObserver":{"role":"symbol","navigatorTitle":[{"text":"LocationServiceObserver","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver","url":"\/documentation\/mapboxcommon\/locationserviceobserver","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LocationServiceObserver"}],"type":"topic","title":"LocationServiceObserver","abstract":[{"type":"text","text":"Observers for getting updates from LocationService."}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","abstract":[],"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","kind":"article","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationServiceObserver/onAvailabilityChanged(forIsAvailable:)":{"type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onAvailabilityChanged"},{"text":"(","kind":"text"},{"text":"forIsAvailable","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"onAvailabilityChangedForIsAvailable:","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/locationserviceobserver\/onavailabilitychanged(forisavailable:)","required":true,"role":"symbol","title":"onAvailabilityChanged(forIsAvailable:)","abstract":[{"type":"text","text":"Called when an availability of location-based service on"},{"type":"text","text":" "},{"text":"the device has been changed. This happens when, for example,","type":"text"},{"text":" ","type":"text"},{"text":"a user disables geolocation on the device.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver\/onAvailabilityChanged(forIsAvailable:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"onAvailabilityChangedForIsAvailable:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onAvailabilityChangedForIsAvailable:"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"onAvailabilityChangedForIsAvailable:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"text":"isAvailable","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"name":"isAvailable","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"True if available, false if it’s not."}]}]}]}},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver\/title","op":"replace","value":"MBXLocationServiceObserver"},{"value":[{"text":"MBXLocationServiceObserver","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver\/fragments","op":"replace"},{"value":[{"text":"MBXLocationServiceObserver","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver\/navigatorTitle"},{"value":"onAvailabilityChangedForIsAvailable:","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver~1onAvailabilityChanged(forIsAvailable:)\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver~1onAvailabilityChanged(forIsAvailable:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onAvailabilityChangedForIsAvailable:"}],"op":"replace"}]}]}