{"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsService\/set(key:value:)","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Settings-and-Constants","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsService"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"set"},{"text":"<","kind":"text"},{"text":"T","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"key","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"value","kind":"externalParam"},{"kind":"text","text":": "},{"text":"T","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"text":"<","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":", "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceError","preciseIdentifier":"s:12MapboxCommon20SettingsServiceErrorV","kind":"typeIdentifier","text":"SettingsServiceError"},{"kind":"text","text":">"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/mapboxcommon\/settingsservice\/set(key:value:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"identifier"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"T"},{"text":">(","kind":"text"},{"text":"key","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"value"},{"text":": ","kind":"text"},{"text":"T","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:12MapboxCommon20SettingsServiceErrorV","text":"SettingsServiceError"},{"kind":"text","text":">"}],"externalID":"s:So18MBXSettingsServiceC12MapboxCommonE3set3key5values6ResultOyytAC08SettingsB5ErrorVGSS_xtlF","roleHeading":"Instance Method","symbolKind":"method","extendedModule":"MapboxCommon","title":"set(key:value:)","modules":[{"name":"MapboxCommon"}],"role":"symbol"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","role":"collection","url":"\/documentation\/mapboxmaps","kind":"symbol","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsService":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsService","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SettingsService","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"SettingsService","kind":"identifier"}],"type":"topic","abstract":[{"text":"Platform independent settings service. Settings service is a key\/value storage (persistent or non","type":"text"},{"type":"text","text":" "},{"text":"persistent), that also allows to register observers to get notifications when values are updated.","type":"text"}],"title":"SettingsService","url":"\/documentation\/mapboxcommon\/settingsservice","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsServiceError":{"title":"SettingsServiceError","role":"symbol","url":"\/documentation\/mapboxcommon\/settingsserviceerror","navigatorTitle":[{"text":"SettingsServiceError","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceError","abstract":[{"text":"Structure for keeping an information about errors that can happen when using Settings service","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"SettingsServiceError","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","title":"MapboxMaps Documentation","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Settings-and-Constants":{"title":"Settings and Constants","url":"\/documentation\/mapboxmaps\/settings-and-constants","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Settings-and-Constants","type":"topic","kind":"article","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsService/set(key:value:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsService\/set(key:value:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"set"},{"text":"<","kind":"text"},{"text":"T","kind":"genericParameter"},{"kind":"text","text":">("},{"text":"key","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"value","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"T"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s6ResultO","text":"Result","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":", ","kind":"text"},{"text":"SettingsServiceError","kind":"typeIdentifier","preciseIdentifier":"s:12MapboxCommon20SettingsServiceErrorV"},{"text":">","kind":"text"}],"kind":"symbol","type":"topic","abstract":[],"title":"set(key:value:)","url":"\/documentation\/mapboxcommon\/settingsservice\/set(key:value:)","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"MBXSettingsService","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsService\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsService\/fragments","value":[{"text":"MBXSettingsService","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsService\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBXSettingsService"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}