{"variants":[{"paths":["\/documentation\/mapboxmaps\/mapidle\/timestamp"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/mapidle\/timestamp"]}],"kind":"symbol","abstract":[{"text":"The timestamp of the ","type":"text"},{"code":"MapIdle","type":"codeVoice"},{"type":"text","text":" event."}],"metadata":{"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"timestamp"}],"roleHeading":"Instance Property","title":"timestamp","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"timestamp"},{"kind":"text","text":": "},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"}],"externalID":"c:objc(cs)MBMMapIdle(py)timestamp","role":"symbol","modules":[{"name":"MapboxMaps"}]},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapIdle"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapIdle\/timestamp"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"timestamp","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"url":"\/documentation\/mapboxmaps\/events","type":"topic","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","title":"Map events","abstract":[{"text":"The simplified diagram of the events emitted by the map is displayed below.","type":"text"}],"role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","abstract":[],"title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","kind":"article","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapIdle":{"navigatorTitle":[{"text":"MapIdle","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapIdle","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/mapidle","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The "},{"code":"map","type":"codeVoice"},{"text":" has entered the idle state. The ","type":"text"},{"type":"codeVoice","code":"map"},{"type":"text","text":" is idle when there are no ongoing"},{"text":" ","type":"text"},{"type":"text","text":"animations, transitions and the "},{"type":"codeVoice","code":"map"},{"text":" has rendered all requested non-volatile tiles","type":"text"},{"text":" ","type":"text"},{"text":"(e.g., live traffic tiles). The event will not be emitted if ","type":"text"},{"type":"codeVoice","code":"setUserAnimationInProgress"},{"type":"text","text":" "},{"type":"text","text":"and \/ or "},{"code":"setGestureInProgress","type":"codeVoice"},{"type":"text","text":" is set to "},{"code":"true","type":"codeVoice"},{"type":"text","text":"."}],"title":"MapIdle","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapIdle"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","title":"MapboxMaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"role":"collection","url":"\/documentation\/mapboxmaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapIdle/timestamp":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapIdle\/timestamp","role":"symbol","kind":"symbol","url":"\/documentation\/mapboxmaps\/mapidle\/timestamp","type":"topic","abstract":[{"text":"The timestamp of the ","type":"text"},{"code":"MapIdle","type":"codeVoice"},{"type":"text","text":" event."}],"navigatorTitle":[{"text":"timestamp","kind":"identifier"}],"title":"timestamp","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"timestamp"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"timestamp","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"timestamp","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSDate","preciseIdentifier":"c:objc(cs)NSDate"},{"kind":"text","text":" * "},{"text":"timestamp","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdle\/title","value":"MBMMapIdle","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdle\/fragments","op":"replace","value":[{"text":"MBMMapIdle","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdle\/navigatorTitle","op":"replace","value":[{"text":"MBMMapIdle","kind":"identifier"}]},{"op":"replace","value":"timestamp","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdle~1timestamp\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdle~1timestamp\/fragments","value":[{"kind":"identifier","text":"timestamp"}]}]}]}