{"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMFeaturesetDescriptor\/initWithFeaturesetId:importId:layerId:","interfaceLanguage":"occ"},"variants":[{"paths":["\/documentation\/mapboxmaps\/mbmfeaturesetdescriptor\/initwithfeaturesetid:importid:layerid:"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeaturesetDescriptor-swift.class"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"initWithFeaturesetId:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"featuresetId"},{"text":" ","kind":"text"},{"text":"importId:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"importId"},{"text":" ","kind":"text"},{"text":"layerId:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"layerId"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"metadata":{"externalID":"c:objc(cs)MBMFeaturesetDescriptor(im)initWithFeaturesetId:importId:layerId:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFeaturesetId:importId:layerId:"}],"navigatorTitle":[{"text":"initWithFeaturesetId:importId:layerId:","kind":"identifier"}],"modules":[{"name":"MapboxMaps"}],"role":"symbol","roleHeading":"Instance Method","title":"initWithFeaturesetId:importId:layerId:","symbolKind":"method"},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","abstract":[],"url":"\/documentation\/overview","role":"collection","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FeaturesetDescriptor-swift.class":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeaturesetDescriptor-swift.class","url":"\/documentation\/mapboxmaps\/featuresetdescriptor-swift.class","kind":"symbol","title":"FeaturesetDescriptor","type":"topic","abstract":[{"text":"Represents an identifier for a single exported featureset or a layer.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FeaturesetDescriptor"}],"navigatorTitle":[{"text":"FeaturesetDescriptor","kind":"identifier"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"title":"MapboxMap","type":"topic","role":"collectionGroup","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","url":"\/documentation\/mapboxmaps\/mapboxmap-apis","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMFeaturesetDescriptor/initWithFeaturesetId:importId:layerId:":{"kind":"symbol","abstract":[],"navigatorTitle":[{"text":"initWithFeaturesetId:importId:layerId:","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMFeaturesetDescriptor\/initWithFeaturesetId:importId:layerId:","role":"symbol","url":"\/documentation\/mapboxmaps\/mbmfeaturesetdescriptor\/initwithfeaturesetid:importid:layerid:","type":"topic","title":"initWithFeaturesetId:importId:layerId:","fragments":[{"kind":"text","text":"- "},{"text":"initWithFeaturesetId:importId:layerId:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeaturesetDescriptor-swift.class\/title","value":"MBMFeaturesetDescriptor"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeaturesetDescriptor-swift.class\/fragments","value":[{"kind":"identifier","text":"MBMFeaturesetDescriptor"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeaturesetDescriptor-swift.class\/navigatorTitle","value":[{"kind":"identifier","text":"MBMFeaturesetDescriptor"}],"op":"replace"}]}]}