{"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onSourceRemoved","interfaceLanguage":"swift"},"abstract":[{"text":"The source has been removed with ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/removeSource(withId:)"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The event is emitted synchronously, thus, "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/allSourceIdentifiers"},{"type":"text","text":" will be"},{"text":" ","type":"text"},{"type":"text","text":"in sync when the observer receives the notification."}],"seeAlsoSections":[{"anchor":"Map-events","title":"Map events","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onMapLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onMapLoadingError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleDataLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onCameraChanged","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onMapIdle","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onSourceAdded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onSourceDataLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleImageMissing","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleImageRemoveUnused","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onRenderFrameStarted","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onRenderFrameFinished","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onResourceRequest"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap"],["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/MapboxMapProtocol-Implementations"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSourceRemoved"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps6SignalV","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Signal","text":"Signal","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"SourceRemoved","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceRemoved","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMSourceRemoved"},{"kind":"text","text":"> { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"extendedModule":"MapboxMaps","symbolKind":"property","externalID":"s:10MapboxMaps0A3MapC15onSourceRemovedAA6SignalVySo09MBMSourceF0CGvp","title":"onSourceRemoved","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onSourceRemoved","kind":"identifier"},{"kind":"text","text":": "},{"text":"Signal","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMSourceRemoved","text":"SourceRemoved","kind":"typeIdentifier"},{"kind":"text","text":">"}],"modules":[{"name":"MapboxMaps"}],"role":"symbol","roleHeading":"Instance Property"},"sections":[],"variants":[{"paths":["\/documentation\/mapboxmaps\/mapboxmap\/onsourceremoved"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","title":"MapboxMaps","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/addSource(_:dataId:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addSource(_:dataId:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addSource","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"Source","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SourceP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dataId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?) ","kind":"text"},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Adds a "},{"type":"codeVoice","code":"source"},{"text":" to the map","type":"text"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/stylemanager\/addsource(_:dataid:)","title":"addSource(_:dataId:)","role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","url":"\/documentation\/mapboxmaps\/mapboxmap","role":"symbol","abstract":[{"text":"Provides access to the map model, including the camera, style, observable map events,","type":"text"},{"type":"text","text":" "},{"text":"and querying rendered features.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapboxMap","kind":"identifier"}],"navigatorTitle":[{"text":"MapboxMap","kind":"identifier"}],"kind":"symbol","type":"topic","title":"MapboxMap"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onSourceDataLoaded":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onSourceDataLoaded","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onSourceDataLoaded","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Signal","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"text":"<","kind":"text"},{"text":"SourceDataLoaded","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMSourceDataLoaded"},{"text":">","kind":"text"}],"abstract":[{"type":"text","text":"A source data has been loaded."},{"type":"text","text":" "},{"type":"text","text":"Event may be emitted synchronously in cases when source’s metadata is available when source is added to the style."}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/onsourcedataloaded","title":"onSourceDataLoaded","role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onCameraChanged":{"abstract":[{"text":"The camera has changed. This event is emitted whenever the visible viewport","type":"text"},{"type":"text","text":" "},{"text":"changes due to the MapView’s size changing or when the camera","type":"text"},{"text":" ","type":"text"},{"text":"is modified by calling camera methods. The event is emitted synchronously,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"so that an updated camera state can be fetched immediately."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onCameraChanged"},{"text":": ","kind":"text"},{"text":"Signal","preciseIdentifier":"s:10MapboxMaps6SignalV","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMCameraChanged","text":"CameraChanged","kind":"typeIdentifier"},{"text":">","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onCameraChanged","type":"topic","title":"onCameraChanged","role":"symbol","kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/oncamerachanged"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"kind":"article","title":"MapboxMap","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","type":"topic","url":"\/documentation\/mapboxmaps\/mapboxmap-apis"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/beginAnimation()":{"abstract":[{"type":"text","text":"If implementing a custom animation mechanism, call this method when the animation begins."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"beginAnimation","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/beginAnimation()","type":"topic","title":"beginAnimation()","role":"symbol","kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/beginanimation()"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onRenderFrameStarted":{"title":"onRenderFrameStarted","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onRenderFrameStarted","kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"text","text":"The map started rendering a frame."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onRenderFrameStarted","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Signal","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"kind":"text","text":"<"},{"text":"RenderFrameStarted","preciseIdentifier":"c:objc(cs)MBMRenderFrameStarted","kind":"typeIdentifier"},{"text":">","kind":"text"}],"url":"\/documentation\/mapboxmaps\/mapboxmap\/onrenderframestarted"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onSourceAdded":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onSourceAdded","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"onSourceAdded","kind":"identifier"},{"kind":"text","text":": "},{"text":"Signal","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"text":"<","kind":"text"},{"text":"SourceAdded","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMSourceAdded"},{"text":">","kind":"text"}],"abstract":[{"text":"The source has been added with ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addSource(_:dataId:)","isActive":true,"type":"reference"},{"type":"text","text":"  or "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addSource(withId:properties:)"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The event is emitted synchronously, therefore, it is possible to immediately"},{"type":"text","text":" "},{"type":"text","text":"read added source’s properties."}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/onsourceadded","title":"onSourceAdded","role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onStyleImageRemoveUnused":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleImageRemoveUnused","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"onStyleImageRemoveUnused","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps6SignalV","text":"Signal","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMStyleImageRemoveUnused","text":"StyleImageRemoveUnused","kind":"typeIdentifier"},{"text":">","kind":"text"}],"abstract":[{"type":"text","text":"An image added to the style is no longer needed and can be removed using "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/removeImage(withId:)","isActive":true,"type":"reference"},{"type":"text","text":"."}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/onstyleimageremoveunused","title":"onStyleImageRemoveUnused","role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onStyleLoaded":{"abstract":[{"type":"text","text":"The requested style has been fully loaded, including the style, specified sprite and sources’ metadata."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onStyleLoaded"},{"kind":"text","text":": "},{"text":"Signal","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"text":"<","kind":"text"},{"text":"StyleLoaded","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMStyleLoaded"},{"text":">","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleLoaded","type":"topic","title":"onStyleLoaded","role":"symbol","kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/onstyleloaded"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Signal":{"url":"\/documentation\/mapboxmaps\/signal","title":"Signal","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Signal","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Signal is a typed interface for observing arbitrary values over time."}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Signal"}],"navigatorTitle":[{"text":"Signal","kind":"identifier"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onMapLoadingError":{"abstract":[{"type":"text","text":"An error that has occurred while loading the Map. The "},{"type":"codeVoice","code":"type"},{"text":" property defines what resource could","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"not be loaded and the "},{"type":"codeVoice","code":"message"},{"text":" property will contain a descriptive error message.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"In case of "},{"code":"source","type":"codeVoice"},{"text":" or ","type":"text"},{"type":"codeVoice","code":"tile"},{"type":"text","text":" loading errors, "},{"type":"codeVoice","code":"sourceID"},{"type":"text","text":" or "},{"code":"tileID","type":"codeVoice"},{"type":"text","text":" will contain the identifier of the source failing."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onMapLoadingError","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps6SignalV","kind":"typeIdentifier","text":"Signal"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMMapLoadingError","text":"MapLoadingError"},{"kind":"text","text":">"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onMapLoadingError","type":"topic","title":"onMapLoadingError","role":"symbol","kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/onmaploadingerror"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/allSourceIdentifiers":{"abstract":[{"text":"The ordered list of the current style sources’ identifiers and types.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"allSourceIdentifiers"},{"text":": [","kind":"text"},{"text":"SourceInfo","preciseIdentifier":"s:10MapboxMaps10SourceInfoV","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/allSourceIdentifiers","type":"topic","title":"allSourceIdentifiers","role":"symbol","kind":"symbol","url":"\/documentation\/mapboxmaps\/stylemanager\/allsourceidentifiers"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onStyleDataLoaded":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleDataLoaded","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onStyleDataLoaded","kind":"identifier"},{"kind":"text","text":": "},{"text":"Signal","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"text":"<","kind":"text"},{"text":"StyleDataLoaded","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMStyleDataLoaded"},{"text":">","kind":"text"}],"abstract":[{"text":"The requested style data has been loaded. The ","type":"text"},{"type":"codeVoice","code":"type"},{"type":"text","text":" property defines what kind of style data has been loaded."},{"text":" ","type":"text"},{"type":"text","text":"Event may be emitted synchronously, for example, when "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/loadStyle(_:transition:completion:)-1ilz1"},{"type":"text","text":" is used to load style."}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/onstyledataloaded","title":"onStyleDataLoaded","role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/endAnimation()":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/endAnimation()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"endAnimation"},{"text":"()","kind":"text"}],"abstract":[{"type":"text","text":"If implementing a custom animation mechanism, call this method when the animation ends."}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/endanimation()","title":"endAnimation()","role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onRenderFrameFinished":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onRenderFrameFinished","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onRenderFrameFinished"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps6SignalV","text":"Signal","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMRenderFrameFinished","text":"RenderFrameFinished","kind":"typeIdentifier"},{"text":">","kind":"text"}],"abstract":[{"type":"text","text":"The map finished rendering a frame."},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"type":"codeVoice","code":"renderMode"},{"text":" property tells whether the map has all data (","type":"text"},{"type":"codeVoice","code":"full"},{"type":"text","text":") required to render the visible viewport."},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"type":"codeVoice","code":"needsRepaint"},{"type":"text","text":" property provides information about ongoing transitions that trigger map repaint."},{"text":" ","type":"text"},{"type":"text","text":"The "},{"code":"placementChanged","type":"codeVoice"},{"type":"text","text":" property tells if the symbol placement has been changed in the visible viewport."}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/onrenderframefinished","title":"onRenderFrameFinished","role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceRemoved":{"type":"topic","navigatorTitle":[{"text":"SourceRemoved","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceRemoved","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SourceRemoved","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"The source has been removed with "},{"code":"removeStyleSource","type":"codeVoice"},{"text":" method.","type":"text"}],"url":"\/documentation\/mapboxmaps\/sourceremoved","title":"SourceRemoved","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/endGesture()":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/endGesture()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"endGesture","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[{"type":"text","text":"If implementing a custom gesture, call this method when the gesture ends."}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/endgesture()","title":"endGesture()","role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/removeSource(withId:)":{"abstract":[{"type":"text","text":"Removes an existing style source."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"removeSource","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/removeSource(withId:)","type":"topic","title":"removeSource(withId:)","role":"symbol","kind":"symbol","url":"\/documentation\/mapboxmaps\/stylemanager\/removesource(withid:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onMapIdle":{"abstract":[{"text":"The map has entered the idle state. The map is in the idle state when there are no ongoing transitions","type":"text"},{"type":"text","text":" "},{"type":"text","text":"and the map has rendered all requested non-volatile tiles. The event will not be emitted if animation is in progress (see "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/beginAnimation()","isActive":true,"type":"reference"},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/endAnimation()"},{"text":")","type":"text"},{"text":" ","type":"text"},{"text":"and \/ or gesture is in progress (see ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/beginGesture()"},{"text":", ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/endGesture()"},{"type":"text","text":")."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onMapIdle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps6SignalV","text":"Signal","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMMapIdle","text":"MapIdle","kind":"typeIdentifier"},{"kind":"text","text":">"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onMapIdle","type":"topic","title":"onMapIdle","role":"symbol","kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/onmapidle"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/removeImage(withId:)":{"abstract":[{"type":"text","text":"Removes an image from the style."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"removeImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/removeImage(withId:)","type":"topic","title":"removeImage(withId:)","role":"symbol","kind":"symbol","url":"\/documentation\/mapboxmaps\/stylemanager\/removeimage(withid:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onSourceRemoved":{"abstract":[{"type":"text","text":"The source has been removed with "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/removeSource(withId:)"},{"type":"text","text":"."},{"type":"text","text":" "},{"text":"The event is emitted synchronously, thus, ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/allSourceIdentifiers"},{"type":"text","text":" will be"},{"text":" ","type":"text"},{"text":"in sync when the observer receives the notification.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onSourceRemoved","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Signal","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"text":"<","kind":"text"},{"text":"SourceRemoved","preciseIdentifier":"c:objc(cs)MBMSourceRemoved","kind":"typeIdentifier"},{"kind":"text","text":">"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onSourceRemoved","type":"topic","title":"onSourceRemoved","role":"symbol","kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/onsourceremoved"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/addSource(withId:properties:)":{"abstract":[{"type":"text","text":"Adds a new style source."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"addSource","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"properties","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]) "},{"text":"throws","kind":"keyword"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addSource(withId:properties:)","type":"topic","title":"addSource(withId:properties:)","role":"symbol","kind":"symbol","url":"\/documentation\/mapboxmaps\/stylemanager\/addsource(withid:properties:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/MapboxMapProtocol-Implementations":{"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/MapboxMapProtocol-Implementations","type":"topic","title":"MapboxMapProtocol Implementations","role":"collectionGroup","kind":"article","url":"\/documentation\/mapboxmaps\/mapboxmap\/mapboxmapprotocol-implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onMapLoaded":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onMapLoaded","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onMapLoaded"},{"text":": ","kind":"text"},{"text":"Signal","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMMapLoaded","text":"MapLoaded"},{"kind":"text","text":">"}],"abstract":[{"text":"The style has been fully loaded, and the map has rendered all visible tiles.","type":"text"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/onmaploaded","title":"onMapLoaded","role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","url":"\/documentation\/overview","title":"MapboxMaps Documentation","abstract":[],"kind":"article","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onResourceRequest":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onResourceRequest","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onResourceRequest","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Signal","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMResourceRequest","kind":"typeIdentifier","text":"ResourceRequest"},{"kind":"text","text":">"}],"abstract":[{"text":"The ","type":"text"},{"code":"ResourceRequest","type":"codeVoice"},{"text":" event allows client to observe resource requests made by a","type":"text"},{"type":"text","text":" "},{"text":"map or snapshotter.","type":"text"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/onresourcerequest","title":"onResourceRequest","role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/loadStyle(_:transition:completion:)-1ilz1":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"loadStyle","kind":"identifier"},{"text":"(","kind":"text"},{"text":"StyleURI","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps8StyleURIV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"transition"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps17TransitionOptionsV","text":"TransitionOptions"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": (((any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"title":"loadStyle(_:transition:completion:)","url":"\/documentation\/mapboxmaps\/mapboxmap\/loadstyle(_:transition:completion:)-1ilz1","abstract":[{"text":"Loads a ","type":"text"},{"code":"style","type":"codeVoice"},{"type":"text","text":" from a StyleURI, calling a completion closure when the"},{"type":"text","text":" "},{"text":"style is fully loaded or there has been an error during load.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/loadStyle(_:transition:completion:)-1ilz1","type":"topic","kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/beginGesture()":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/beginGesture()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"beginGesture"},{"text":"()","kind":"text"}],"abstract":[{"type":"text","text":"If implementing a custom gesture, call this method when the gesture begins."}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/begingesture()","title":"beginGesture()","role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/addImage(_:id:sdf:contentInsets:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addImage(_:id:sdf:contentInsets:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addImage","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"id","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"sdf","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"contentInsets","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@UIEdgeInsets","text":"UIEdgeInsets","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Adds an image to be used in the style."}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/stylemanager\/addimage(_:id:sdf:contentinsets:)","title":"addImage(_:id:sdf:contentInsets:)","role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onStyleImageMissing":{"abstract":[{"type":"text","text":"A style has a missing image. This event is emitted when the map renders visible tiles and"},{"type":"text","text":" "},{"type":"text","text":"one of the required images is missing in the sprite sheet. Subscriber has to provide the missing image"},{"text":" ","type":"text"},{"type":"text","text":"by calling "},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addImage(_:id:sdf:contentInsets:)","isActive":true},{"text":".","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onStyleImageMissing","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Signal","preciseIdentifier":"s:10MapboxMaps6SignalV","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"StyleImageMissing","preciseIdentifier":"c:objc(cs)MBMStyleImageMissing"},{"text":">","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleImageMissing","type":"topic","title":"onStyleImageMissing","role":"symbol","kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/onstyleimagemissing"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceRemoved\/title","value":"MBMSourceRemoved"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceRemoved\/fragments","value":[{"text":"MBMSourceRemoved","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"MBMSourceRemoved"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceRemoved\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}