{"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInTiles\/isEqualToTileCacheBudget(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqualToTileCacheBudget","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"other","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"TileCacheBudgetInTiles","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInTiles","preciseIdentifier":"c:objc(cs)MBMTileCacheBudgetInTiles"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"externalID":"c:objc(cs)MBMTileCacheBudgetInTiles(im)isEqualToTileCacheBudgetInTiles:","role":"symbol","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqualToTileCacheBudget","kind":"identifier"},{"text":"(","kind":"text"},{"text":"TileCacheBudgetInTiles","preciseIdentifier":"c:objc(cs)MBMTileCacheBudgetInTiles","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"isEqualToTileCacheBudgetInTiles:","kind":"identifier"}],"modules":[{"name":"MapboxMaps"}],"title":"isEqualToTileCacheBudget(_:)","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInTiles"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/tilecachebudgetintiles\/isequaltotilecachebudget(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/tilecachebudgetintiles\/isequaltotilecachebudget(_:)"]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","url":"\/documentation\/mapboxmaps","title":"MapboxMaps","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"abstract":[],"url":"\/documentation\/mapboxmaps\/tilestore-apis","role":"collectionGroup","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","type":"topic","title":"TileStore APIs"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudgetInTiles/isEqualToTileCacheBudget(_:)":{"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqualToTileCacheBudget","kind":"identifier"},{"text":"(","kind":"text"},{"text":"TileCacheBudgetInTiles","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMTileCacheBudgetInTiles"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInTiles\/isEqualToTileCacheBudget(_:)","url":"\/documentation\/mapboxmaps\/tilecachebudgetintiles\/isequaltotilecachebudget(_:)","navigatorTitle":[{"text":"isEqualToTileCacheBudgetInTiles:","kind":"identifier"}],"abstract":[],"title":"isEqualToTileCacheBudget(_:)"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","role":"collection","type":"topic","abstract":[],"title":"MapboxMaps Documentation","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudgetInTiles":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInTiles","role":"symbol","abstract":[{"text":"Tile cache budget in tiles.","type":"text"}],"kind":"symbol","title":"TileCacheBudgetInTiles","navigatorTitle":[{"kind":"identifier","text":"TileCacheBudgetInTiles"}],"url":"\/documentation\/mapboxmaps\/tilecachebudgetintiles","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileCacheBudgetInTiles"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"isEqualToTileCacheBudgetInTiles:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"isEqualToTileCacheBudgetInTiles:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isEqualToTileCacheBudgetInTiles:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MBMTileCacheBudgetInTiles","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInTiles","preciseIdentifier":"c:objc(cs)MBMTileCacheBudgetInTiles"},{"text":" *) ","kind":"text"},{"text":"other","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"isEqualToTileCacheBudgetInTiles:","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInTiles~1isEqualToTileCacheBudget(_:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqualToTileCacheBudgetInTiles:"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInTiles~1isEqualToTileCacheBudget(_:)\/fragments","op":"replace"},{"value":"MBMTileCacheBudgetInTiles","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInTiles\/title","op":"replace"},{"value":[{"text":"MBMTileCacheBudgetInTiles","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInTiles\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MBMTileCacheBudgetInTiles"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInTiles\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}