{"abstract":[{"text":"Font family to use as font fallback for client-side text renderings.","type":"text"}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMGlyphsRasterizationOptions\/fontFamily","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fontFamily","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}]},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"inlineContent":[{"text":"Note: ","type":"text"},{"type":"codeVoice","code":"GlyphsRasterizationMode"},{"type":"text","text":" has precedence over font family. If "},{"type":"codeVoice","code":"AllGlyphsRasterizedLocally"},{"text":" ","type":"text"},{"text":"or ","type":"text"},{"type":"codeVoice","code":"IdeographsRasterizedLocally"},{"text":" is set, local glyphs will be generated based on the provided font family. If no","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"font family is provided, the map will fall back to use the system default font. The mechanisms of choosing the"},{"type":"text","text":" "},{"type":"text","text":"default font are varied in platforms:"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"For darwin(iOS\/macOS) platform, the default font family is created from the "},{"type":"text","text":"systemFont"},{"text":".","type":"text"},{"type":"text","text":" "},{"text":"If provided fonts are not supported on darwin platform, the map will fall back to use the first available font from the global fallback list.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"For Android platform: the default font "},{"text":"Typeface.DEFAULT","type":"text"},{"type":"text","text":" will be used."}]}]}],"type":"unorderedList"},{"type":"paragraph","inlineContent":[{"text":"Besides, the font family will be discarded if it is provided along with ","type":"text"},{"code":"NoGlyphsRasterizedLocally","type":"codeVoice"},{"text":" mode.","type":"text"}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"modules":[{"name":"MapboxMaps"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"fontFamily","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"fontFamily"}],"symbolKind":"property","roleHeading":"Instance Property","role":"symbol","title":"fontFamily","externalID":"c:objc(cs)MBMGlyphsRasterizationOptions(py)fontFamily"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/mbmglyphsrasterizationoptions\/fontfamily"]},{"paths":["\/documentation\/mapboxmaps\/mbmglyphsrasterizationoptions\/fontfamily"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-View","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationOptions"]]},"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMGlyphsRasterizationOptions/fontFamily":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMGlyphsRasterizationOptions\/fontFamily","url":"\/documentation\/mapboxmaps\/mbmglyphsrasterizationoptions\/fontfamily","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"fontFamily","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"abstract":[{"text":"Font family to use as font fallback for client-side text renderings.","type":"text"}],"navigatorTitle":[{"text":"fontFamily","kind":"identifier"}],"title":"fontFamily","role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map-View":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-View","kind":"article","title":"MapView","url":"\/documentation\/mapboxmaps\/map-view","abstract":[],"type":"topic","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GlyphsRasterizationOptions":{"role":"symbol","type":"topic","title":"GlyphsRasterizationOptions","navigatorTitle":[{"text":"GlyphsRasterizationOptions","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationOptions","url":"\/documentation\/mapboxmaps\/glyphsrasterizationoptions","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GlyphsRasterizationOptions"}],"abstract":[{"text":"Describes the glyphs rasterization option values.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"fontFamily"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"fontFamily","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"fontFamily","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"fontFamily","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMGlyphsRasterizationOptions~1fontFamily\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMGlyphsRasterizationOptions~1fontFamily\/fragments","op":"replace","value":[{"text":"fontFamily","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationOptions\/title","value":"MBMGlyphsRasterizationOptions"},{"op":"replace","value":[{"text":"MBMGlyphsRasterizationOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationOptions\/fragments"}]}]}