{"metadata":{"title":"rasterizationMode","navigatorTitle":[{"text":"rasterizationMode","kind":"identifier"}],"symbolKind":"property","modules":[{"name":"MapboxMaps"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"rasterizationMode","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GlyphsRasterizationMode","preciseIdentifier":"c:@E@MBMGlyphsRasterizationMode"}],"externalID":"c:objc(cs)MBMGlyphsRasterizationOptions(py)rasterizationMode","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rasterizationMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GlyphsRasterizationMode","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode","preciseIdentifier":"c:@E@MBMGlyphsRasterizationMode","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-View","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationOptions"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMGlyphsRasterizationOptions\/rasterizationMode"},"kind":"symbol","abstract":[{"text":"Glyphs rasterization mode for client-side text rendering.","type":"text"}],"variants":[{"paths":["\/documentation\/mapboxmaps\/mbmglyphsrasterizationoptions\/rasterizationmode"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/mbmglyphsrasterizationoptions\/rasterizationmode"]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GlyphsRasterizationMode":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode","kind":"symbol","role":"symbol","title":"GlyphsRasterizationMode","type":"topic","url":"\/documentation\/mapboxmaps\/glyphsrasterizationmode","abstract":[{"text":"Describes glyphs rasterization modes.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"GlyphsRasterizationMode","kind":"identifier"}],"navigatorTitle":[{"text":"GlyphsRasterizationMode","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GlyphsRasterizationOptions":{"role":"symbol","type":"topic","title":"GlyphsRasterizationOptions","navigatorTitle":[{"text":"GlyphsRasterizationOptions","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationOptions","url":"\/documentation\/mapboxmaps\/glyphsrasterizationoptions","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GlyphsRasterizationOptions"}],"abstract":[{"text":"Describes the glyphs rasterization option values.","type":"text"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map-View":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-View","kind":"article","title":"MapView","url":"\/documentation\/mapboxmaps\/map-view","abstract":[],"type":"topic","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMGlyphsRasterizationOptions/rasterizationMode":{"role":"symbol","url":"\/documentation\/mapboxmaps\/mbmglyphsrasterizationoptions\/rasterizationmode","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"rasterizationMode","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@MBMGlyphsRasterizationMode","text":"GlyphsRasterizationMode","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMGlyphsRasterizationOptions\/rasterizationMode","abstract":[{"text":"Glyphs rasterization mode for client-side text rendering.","type":"text"}],"type":"topic","title":"rasterizationMode","navigatorTitle":[{"text":"rasterizationMode","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"rasterizationMode","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"rasterizationMode"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@E@MBMGlyphsRasterizationMode","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode","text":"MBMGlyphsRasterizationMode"},{"text":" ","kind":"text"},{"text":"rasterizationMode","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/title","value":"MBMGlyphsRasterizationMode"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/fragments","value":[{"text":"MBMGlyphsRasterizationMode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationOptions\/title","op":"replace","value":"MBMGlyphsRasterizationOptions"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationOptions\/fragments","op":"replace","value":[{"text":"MBMGlyphsRasterizationOptions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMGlyphsRasterizationOptions~1rasterizationMode\/title","value":"rasterizationMode"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMGlyphsRasterizationOptions~1rasterizationMode\/fragments","value":[{"text":"rasterizationMode","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}