{"metadata":{"roleHeading":"Case","modules":[{"name":"MapboxMaps"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"terrain"}],"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"MBMMapCenterAltitudeModeTerrain"}],"role":"symbol","title":"MapCenterAltitudeMode.terrain","externalID":"c:@E@MBMMapCenterAltitudeMode@MBMMapCenterAltitudeModeTerrain"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapCenterAltitudeMode\/terrain"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"terrain"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/mapboxmaps\/mapcenteraltitudemode\/terrain"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/mapcenteraltitudemode\/terrain"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Default, center altitude should match the terrain elevation"}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapCenterAltitudeMode"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapCenterAltitudeMode":{"abstract":[{"text":"Defines how the map center point should react to terrain elevation changes.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapCenterAltitudeMode"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapCenterAltitudeMode","navigatorTitle":[{"kind":"identifier","text":"MapCenterAltitudeMode"}],"title":"MapCenterAltitudeMode","role":"symbol","url":"\/documentation\/mapboxmaps\/mapcenteraltitudemode","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapCenterAltitudeMode/terrain":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapCenterAltitudeMode\/terrain","navigatorTitle":[{"kind":"identifier","text":"MBMMapCenterAltitudeModeTerrain"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Default, center altitude should match the terrain elevation","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"terrain"}],"title":"MapCenterAltitudeMode.terrain","url":"\/documentation\/mapboxmaps\/mapcenteraltitudemode\/terrain"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","url":"\/documentation\/mapboxmaps","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"abstract":[],"role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","title":"MapboxMap","url":"\/documentation\/mapboxmaps\/mapboxmap-apis","kind":"article","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"title":"MapboxMaps Documentation","type":"topic","kind":"article","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","value":"MBMMapCenterAltitudeModeTerrain","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"MBMMapCenterAltitudeModeTerrain","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"MBMMapCenterAltitudeModeTerrain","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"MBMMapCenterAltitudeMode","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapCenterAltitudeMode\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBMMapCenterAltitudeMode"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapCenterAltitudeMode\/fragments"},{"op":"replace","value":[{"text":"MBMMapCenterAltitudeMode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapCenterAltitudeMode\/navigatorTitle"},{"op":"replace","value":"MBMMapCenterAltitudeModeTerrain","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapCenterAltitudeMode~1terrain\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBMMapCenterAltitudeModeTerrain"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapCenterAltitudeMode~1terrain\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}