{"variants":[{"paths":["\/documentation\/mapboxcommon\/logginglevel\/hashvalue"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LoggingLevel","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LoggingLevel\/RawRepresentable-Implementations"]]},"sections":[],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LoggingLevel\/hashValue","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"role":"symbol","externalID":"s:SYsSHRzSH8RawValueSYRpzrlE04hashB0Sivp::SYNTHESIZED::c:@E@MBXLoggingLevel","extendedModule":"Swift","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"availabilityPrefix":[{"text":"Available when","type":"text"}]},"title":"hashValue","roleHeading":"Instance Property","modules":[{"name":"MapboxCommon","relatedModules":["Swift"]}]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.hashValue"},{"type":"text","text":"."}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LoggingLevel":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LoggingLevel","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"LoggingLevel"}],"abstract":[{"type":"text","text":"State level of a log message."}],"type":"topic","title":"LoggingLevel","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LoggingLevel","role":"symbol","kind":"symbol","url":"\/documentation\/mapboxcommon\/logginglevel"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","role":"collection","url":"\/documentation\/overview","kind":"article","abstract":[],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LoggingLevel/RawRepresentable-Implementations":{"type":"topic","url":"\/documentation\/mapboxcommon\/logginglevel\/rawrepresentable-implementations","abstract":[],"kind":"article","role":"collectionGroup","title":"RawRepresentable Implementations","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LoggingLevel\/RawRepresentable-Implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"title":"MapboxMaps","kind":"symbol","role":"collection","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LoggingLevel/hashValue":{"type":"topic","title":"hashValue","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LoggingLevel\/hashValue","role":"symbol","conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":".","type":"text"}]},"abstract":[],"url":"\/documentation\/mapboxcommon\/logginglevel\/hashvalue","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Performance":{"role":"collectionGroup","abstract":[],"type":"topic","title":"Performance and investigations","url":"\/documentation\/mapboxmaps\/performance","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LoggingLevel\/title","op":"replace","value":"MBXLoggingLevel"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LoggingLevel\/fragments","value":[{"text":"MBXLoggingLevel","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LoggingLevel\/navigatorTitle","op":"replace","value":[{"text":"MBXLoggingLevel","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}