{"metadata":{"platforms":[],"externalID":"c:objc(cs)MBMCustomLayerRenderParameters(im)initWithWidth:height:latitude:longitude:zoom:bearing:pitch:fieldOfView:projectionMatrix:elevationData:renderToTilesIDs:projection:","role":"symbol","roleHeading":"Initializer","title":"init(width:height:latitude:longitude:zoom:bearing:pitch:fieldOfView:projectionMatrix:elevationData:renderToTilesIDs:projection:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"width"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"height"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"latitude"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"longitude"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"zoom"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bearing"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pitch"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fieldOfView"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"projectionMatrix"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"elevationData"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:objc(pl)MBMElevationData","kind":"typeIdentifier","text":"ElevationData"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"renderToTilesIDs"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)MBMCanonicalTileID","kind":"typeIdentifier","text":"CanonicalTileID"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"projection"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:objc(pl)MBMCustomLayerMapProjection","kind":"typeIdentifier","text":"CustomLayerMapProjection"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithWidth:height:latitude:longitude:zoom:bearing:pitch:fieldOfView:projectionMatrix:elevationData:renderToTilesIDs:projection:"}],"modules":[{"name":"MapboxMaps"}],"symbolKind":"init"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"width","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"height","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"latitude","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"longitude"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"zoom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":", ","kind":"text"},{"text":"bearing","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"pitch","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"fieldOfView","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"projectionMatrix","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"elevationData","kind":"externalParam"},{"text":": (any ","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ElevationData","text":"ElevationData","preciseIdentifier":"c:objc(pl)MBMElevationData","kind":"typeIdentifier"},{"text":")?, ","kind":"text"},{"text":"renderToTilesIDs","kind":"externalParam"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID","text":"CanonicalTileID","preciseIdentifier":"c:objc(cs)MBMCanonicalTileID","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"text":"projection","kind":"externalParam"},{"text":": any ","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerMapProjection","text":"CustomLayerMapProjection","preciseIdentifier":"c:objc(pl)MBMCustomLayerMapProjection","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This constructor is internal and to be used from within Mapbox SDK only."}]}],"variants":[{"paths":["\/documentation\/mapboxmaps\/customlayerrenderparameters\/init(width:height:latitude:longitude:zoom:bearing:pitch:fieldofview:projectionmatrix:elevationdata:rendertotilesids:projection:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/customlayerrenderparameters\/init(width:height:latitude:longitude:zoom:bearing:pitch:fieldofview:projectionmatrix:elevationdata:rendertotilesids:projection:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters\/init(width:height:latitude:longitude:zoom:bearing:pitch:fieldOfView:projectionMatrix:elevationData:renderToTilesIDs:projection:)","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layers":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers","type":"topic","abstract":[],"url":"\/documentation\/mapboxmaps\/layers","kind":"article","role":"collectionGroup","title":"Layers"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerRenderParameters/init(width:height:latitude:longitude:zoom:bearing:pitch:fieldOfView:projectionMatrix:elevationData:renderToTilesIDs:projection:)":{"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters\/init(width:height:latitude:longitude:zoom:bearing:pitch:fieldOfView:projectionMatrix:elevationData:renderToTilesIDs:projection:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"width"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"height"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"latitude"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"longitude"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"zoom"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bearing"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pitch"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fieldOfView"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"projectionMatrix"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"elevationData"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:objc(pl)MBMElevationData","kind":"typeIdentifier","text":"ElevationData"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"renderToTilesIDs"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)MBMCanonicalTileID","kind":"typeIdentifier","text":"CanonicalTileID"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"projection"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:objc(pl)MBMCustomLayerMapProjection","kind":"typeIdentifier","text":"CustomLayerMapProjection"},{"kind":"text","text":")"}],"title":"init(width:height:latitude:longitude:zoom:bearing:pitch:fieldOfView:projectionMatrix:elevationData:renderToTilesIDs:projection:)","url":"\/documentation\/mapboxmaps\/customlayerrenderparameters\/init(width:height:latitude:longitude:zoom:bearing:pitch:fieldofview:projectionmatrix:elevationdata:rendertotilesids:projection:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithWidth:height:latitude:longitude:zoom:bearing:pitch:fieldOfView:projectionMatrix:elevationData:renderToTilesIDs:projection:"}],"type":"topic","deprecated":true,"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CanonicalTileID":{"type":"topic","abstract":[{"text":"Represents a tile coordinate.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CanonicalTileID","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/canonicaltileid","kind":"symbol","navigatorTitle":[{"text":"CanonicalTileID","kind":"identifier"}],"title":"CanonicalTileID"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerMapProjection":{"navigatorTitle":[{"text":"CustomLayerMapProjection","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerMapProjection","url":"\/documentation\/mapboxmaps\/customlayermapprojection","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomLayerMapProjection","kind":"identifier"}],"role":"symbol","title":"CustomLayerMapProjection"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","abstract":[],"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","type":"topic","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerRenderParameters":{"kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/customlayerrenderparameters","navigatorTitle":[{"kind":"identifier","text":"CustomLayerRenderParameters"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomLayerRenderParameters"}],"title":"CustomLayerRenderParameters","abstract":[{"type":"text","text":"Parameters that define the current camera position for a "},{"type":"codeVoice","code":"CustomLayerHost::render()"},{"type":"text","text":" function."}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ElevationData":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ElevationData","abstract":[{"type":"text","text":"Interface that provides access to elevation data."}],"title":"ElevationData","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ElevationData"}],"navigatorTitle":[{"kind":"identifier","text":"ElevationData"}],"role":"symbol","kind":"symbol","url":"\/documentation\/mapboxmaps\/elevationdata"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","role":"collection","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[],"op":"replace","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithWidth:height:latitude:longitude:zoom:bearing:pitch:fieldOfView:projectionMatrix:elevationData:renderToTilesIDs:projection:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithWidth:height:latitude:longitude:zoom:bearing:pitch:fieldOfView:projectionMatrix:elevationData:renderToTilesIDs:projection:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithWidth:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"width","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"height:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"height","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"latitude:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"latitude","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"longitude:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"longitude","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"zoom:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"zoom","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"bearing:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"bearing","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"pitch:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"pitch","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"fieldOfView:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"fieldOfView","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"projectionMatrix:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSNumber *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"projectionMatrix","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"elevationData:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qoobjc(pl)MBMElevationData","text":"id<MBMElevationData>","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"elevationData","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"renderToTilesIDs:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<MBMCanonicalTileID *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"renderToTilesIDs","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"projection:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qoobjc(pl)MBMCustomLayerMapProjection","text":"id<MBMCustomLayerMapProjection>","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"projection","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"initWithWidth:height:latitude:longitude:zoom:bearing:pitch:fieldOfView:projectionMatrix:elevationData:renderToTilesIDs:projection:","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters~1init(width:height:latitude:longitude:zoom:bearing:pitch:fieldOfView:projectionMatrix:elevationData:renderToTilesIDs:projection:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithWidth:height:latitude:longitude:zoom:bearing:pitch:fieldOfView:projectionMatrix:elevationData:renderToTilesIDs:projection:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters~1init(width:height:latitude:longitude:zoom:bearing:pitch:fieldOfView:projectionMatrix:elevationData:renderToTilesIDs:projection:)\/fragments"},{"value":"MBMCanonicalTileID","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/title"},{"value":[{"text":"MBMCanonicalTileID","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/fragments"},{"value":[{"text":"MBMCanonicalTileID","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/navigatorTitle"},{"value":"MBMCustomLayerMapProjection","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerMapProjection\/title"},{"value":[{"text":"MBMCustomLayerMapProjection","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerMapProjection\/fragments"},{"value":[{"text":"MBMCustomLayerMapProjection","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerMapProjection\/navigatorTitle"},{"value":"MBMCustomLayerRenderParameters","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/title"},{"value":[{"text":"MBMCustomLayerRenderParameters","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/fragments"},{"value":[{"text":"MBMCustomLayerRenderParameters","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/navigatorTitle"},{"value":"MBMElevationData","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ElevationData\/title"},{"value":[{"text":"MBMElevationData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ElevationData\/fragments"},{"value":[{"text":"MBMElevationData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ElevationData\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}