{"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"externalID":"c:objc(cs)MBXHttpRequest(py)headers","modules":[{"name":"MapboxCommon"}],"title":"headers","role":"symbol","symbolKind":"property","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"headers","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"headers","kind":"identifier"}]},"abstract":[{"text":"HTTP headers to include.","type":"text"},{"type":"text","text":" "},{"text":"If you provide ","type":"text"},{"code":"User-Agent","type":"codeVoice"},{"type":"text","text":" header using this "},{"type":"codeVoice","code":"headers"},{"type":"text","text":" field, then resulting "},{"type":"codeVoice","code":"User-Agent"},{"text":" will also contain","type":"text"},{"type":"text","text":" "},{"text":"information about application, platform, device, and Common SDK’s version.","type":"text"},{"type":"text","text":" "},{"text":"If you provide duplicate headers then ","type":"text"},{"type":"codeVoice","code":"request"},{"type":"text","text":" call will be immediately failed."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"headers","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"] { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/mbxhttprequest\/headers"]},{"paths":["\/documentation\/mapboxcommon\/mbxhttprequest\/headers"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest"]]},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXHttpRequest\/headers","interfaceLanguage":"swift"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequest":{"navigatorTitle":[{"text":"HttpRequest","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"HttpRequest"}],"title":"HttpRequest","type":"topic","abstract":[{"type":"text","text":"HttpRequest holds basic information for construction of an HTTP request"}],"url":"\/documentation\/mapboxcommon\/httprequest"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXHttpRequest/headers":{"url":"\/documentation\/mapboxcommon\/mbxhttprequest\/headers","type":"topic","title":"headers","abstract":[{"text":"HTTP headers to include.","type":"text"},{"type":"text","text":" "},{"text":"If you provide ","type":"text"},{"type":"codeVoice","code":"User-Agent"},{"text":" header using this ","type":"text"},{"code":"headers","type":"codeVoice"},{"text":" field, then resulting ","type":"text"},{"code":"User-Agent","type":"codeVoice"},{"type":"text","text":" will also contain"},{"text":" ","type":"text"},{"text":"information about application, platform, device, and Common SDK’s version.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"If you provide duplicate headers then "},{"type":"codeVoice","code":"request"},{"type":"text","text":" call will be immediately failed."}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXHttpRequest\/headers","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"headers","kind":"identifier"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"headers","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"title":"MapboxCommon","role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","abstract":[],"url":"\/documentation\/mapboxcommon"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"headers","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"kind":"identifier","text":"headers"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSDictionary","kind":"typeIdentifier","text":"NSDictionary<NSString *,NSString *>"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"headers"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"value":"MBXHttpRequest","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest\/title"},{"value":[{"text":"MBXHttpRequest","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MBXHttpRequest~1headers\/title","value":"headers"},{"value":[{"text":"headers","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MBXHttpRequest~1headers\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}