{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"method"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@MBXHttpMethod","kind":"typeIdentifier","text":"HttpMethod","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpMethod"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/mapboxcommon\/mbxhttprequest\/method"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxcommon\/mbxhttprequest\/method"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:objc(cs)MBXHttpRequest(py)method","role":"symbol","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"method","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HttpMethod","preciseIdentifier":"c:@E@MBXHttpMethod"}],"roleHeading":"Instance Property","modules":[{"name":"MapboxCommon"}],"title":"method","navigatorTitle":[{"text":"method","kind":"identifier"}]},"abstract":[{"type":"text","text":"HTTP defines a set of request methods to indicate the desired action to be performed for a given resource."},{"type":"text","text":" "},{"text":"Specify desired method using this parameter.","type":"text"}],"kind":"symbol","identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXHttpRequest\/method","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequest":{"navigatorTitle":[{"text":"HttpRequest","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"HttpRequest"}],"title":"HttpRequest","type":"topic","abstract":[{"type":"text","text":"HttpRequest holds basic information for construction of an HTTP request"}],"url":"\/documentation\/mapboxcommon\/httprequest"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpMethod":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpMethod","url":"\/documentation\/mapboxcommon\/httpmethod","kind":"symbol","title":"HttpMethod","abstract":[{"text":"HTTP defines a set of request methods to indicate the desired action to be performed for a given resource.","type":"text"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HttpMethod","kind":"identifier"}],"navigatorTitle":[{"text":"HttpMethod","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXHttpRequest/method":{"url":"\/documentation\/mapboxcommon\/mbxhttprequest\/method","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"method","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBXHttpMethod","text":"HttpMethod"}],"role":"symbol","kind":"symbol","title":"method","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXHttpRequest\/method","type":"topic","abstract":[{"text":"HTTP defines a set of request methods to indicate the desired action to be performed for a given resource.","type":"text"},{"text":" ","type":"text"},{"text":"Specify desired method using this parameter.","type":"text"}],"navigatorTitle":[{"text":"method","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"title":"MapboxCommon","role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","abstract":[],"url":"\/documentation\/mapboxcommon"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"method","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"method"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"text":"MBXHttpMethod","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpMethod","preciseIdentifier":"c:@E@MBXHttpMethod"},{"text":" ","kind":"text"},{"text":"method","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest\/title","value":"MBXHttpRequest"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest\/fragments","op":"replace","value":[{"text":"MBXHttpRequest","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpMethod\/title","value":"MBXHttpMethod"},{"value":[{"text":"MBXHttpMethod","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpMethod\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MBXHttpRequest~1method\/title","op":"replace","value":"method"},{"value":[{"text":"method","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MBXHttpRequest~1method\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}