{"metadata":{"role":"symbol","navigatorTitle":[{"text":"networkRestriction","kind":"identifier"}],"roleHeading":"Instance Property","modules":[{"name":"MapboxCommon"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"networkRestriction"},{"kind":"text","text":": "},{"text":"NetworkRestriction","preciseIdentifier":"c:@E@MBXNetworkRestriction","kind":"typeIdentifier"}],"title":"networkRestriction","externalID":"c:objc(cs)MBXHttpRequest(py)networkRestriction"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkRestriction"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NetworkRestriction","kind":"typeIdentifier","text":"NetworkRestriction","preciseIdentifier":"c:@E@MBXNetworkRestriction"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}]},{"kind":"content","content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"inlineContent":[{"type":"text","text":"Default is allowed to all network types"}],"type":"paragraph"}]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXHttpRequest\/networkRestriction","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","abstract":[{"type":"text","text":"Restrict the request to the specified network types. If none of the specified network types is available, the"},{"type":"text","text":" "},{"text":"download fails with a connection error.","type":"text"}],"sections":[],"variants":[{"paths":["\/documentation\/mapboxcommon\/mbxhttprequest\/networkrestriction"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/mbxhttprequest\/networkrestriction"]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"title":"MapboxCommon","role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","abstract":[],"url":"\/documentation\/mapboxcommon"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequest":{"navigatorTitle":[{"text":"HttpRequest","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"HttpRequest"}],"title":"HttpRequest","type":"topic","abstract":[{"type":"text","text":"HttpRequest holds basic information for construction of an HTTP request"}],"url":"\/documentation\/mapboxcommon\/httprequest"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXHttpRequest/networkRestriction":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"networkRestriction"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@MBXNetworkRestriction","text":"NetworkRestriction","kind":"typeIdentifier"}],"role":"symbol","url":"\/documentation\/mapboxcommon\/mbxhttprequest\/networkrestriction","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"networkRestriction"}],"title":"networkRestriction","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXHttpRequest\/networkRestriction","abstract":[{"type":"text","text":"Restrict the request to the specified network types. If none of the specified network types is available, the"},{"type":"text","text":" "},{"type":"text","text":"download fails with a connection error."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/NetworkRestriction":{"abstract":[{"type":"text","text":"Classify network types based on cost."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NetworkRestriction","role":"symbol","url":"\/documentation\/mapboxcommon\/networkrestriction","navigatorTitle":[{"text":"NetworkRestriction","kind":"identifier"}],"type":"topic","title":"NetworkRestriction","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"NetworkRestriction","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"networkRestriction","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"networkRestriction"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@E@MBXNetworkRestriction","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NetworkRestriction","text":"MBXNetworkRestriction"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkRestriction"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"MBXHttpRequest","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXHttpRequest"}]},{"value":"networkRestriction","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MBXHttpRequest~1networkRestriction\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MBXHttpRequest~1networkRestriction\/fragments","value":[{"text":"networkRestriction","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1NetworkRestriction\/title","value":"MBXNetworkRestriction"},{"value":[{"text":"MBXNetworkRestriction","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1NetworkRestriction\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}