{"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestError\/localizedDescription","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"MapboxCommon","relatedModules":["Swift"]}],"platforms":[{"unavailable":false,"beta":false,"introducedAt":"8.0","name":"iOS","deprecated":false},{"unavailable":false,"beta":false,"introducedAt":"8.0","name":"iPadOS","deprecated":false},{"unavailable":false,"beta":false,"introducedAt":"8.0","name":"Mac Catalyst","deprecated":false},{"unavailable":false,"beta":false,"introducedAt":"10.10","name":"macOS","deprecated":false},{"unavailable":false,"beta":false,"introducedAt":"9.0","name":"tvOS","deprecated":false},{"unavailable":false,"beta":false,"introducedAt":"2.0","name":"watchOS","deprecated":false}],"title":"localizedDescription","extendedModule":"Swift","externalID":"s:s5ErrorP10FoundationE20localizedDescriptionSSvp::SYNTHESIZED::c:objc(cs)MBXHttpRequestError","role":"symbol","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localizedDescription","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"localizedDescription"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestError\/Error-Implementations"]]},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"Error.localizedDescription"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/httprequesterror\/localizeddescription"]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestError":{"role":"symbol","type":"topic","title":"HttpRequestError","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestError","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HttpRequestError","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/httprequesterror","kind":"symbol","navigatorTitle":[{"text":"HttpRequestError","kind":"identifier"}],"abstract":[{"type":"text","text":"Record which contains detailed information about HTTP error happened during request\/download call."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"type":"topic","title":"MapboxCommon","role":"collection","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","url":"\/documentation\/mapboxcommon","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestError/Error-Implementations":{"abstract":[],"title":"Error Implementations","role":"collectionGroup","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestError\/Error-Implementations","url":"\/documentation\/mapboxcommon\/httprequesterror\/error-implementations","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","abstract":[],"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","type":"topic","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestError/localizedDescription":{"url":"\/documentation\/mapboxcommon\/httprequesterror\/localizeddescription","title":"localizedDescription","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestError\/localizedDescription","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"localizedDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestError\/title","op":"replace","value":"MBXHttpRequestError"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestError\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXHttpRequestError"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestError\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBXHttpRequestError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}