{"sections":[],"abstract":[{"text":"Accuracy authorization granted by user to the app.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/accuracyauthorization"]},{"paths":["\/documentation\/mapboxcommon\/accuracyauthorization"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"generated":true,"anchor":"Location","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationManager","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck2DConfiguration","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Model","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckBearing","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProviderDelegate","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Coordinate2D","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationExtraKeys","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProviderRequest","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceFactory","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/DeviceLocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Heading","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckRenderingData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/IntervalSettings"],"title":"Location"}],"kind":"symbol","topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization\/exact","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization\/inexact","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization\/none"],"generated":true,"anchor":"Enumeration-Cases"},{"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization\/init(rawValue:)"],"generated":true},{"title":"Default Implementations","anchor":"Default-Implementations","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization\/Equatable-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization\/RawRepresentable-Implementations"],"generated":true}],"metadata":{"externalID":"c:@E@MBXAccuracyAuthorization","navigatorTitle":[{"kind":"identifier","text":"AccuracyAuthorization"}],"modules":[{"name":"MapboxCommon"}],"role":"symbol","title":"AccuracyAuthorization","symbolKind":"enum","roleHeading":"Enumeration","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AccuracyAuthorization"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AccuracyAuthorization","kind":"identifier"}],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs"]]},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization","interfaceLanguage":"swift"},"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/s15BitwiseCopyableP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH","doc:\/\/com.mapbox.MapboxMaps\/SY","doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"],"kind":"relationships","type":"conformsTo"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PermissionStatus":{"abstract":[{"type":"text","text":"Location permissions granted by user to the app."}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/mapboxcommon\/permissionstatus","navigatorTitle":[{"text":"PermissionStatus","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PermissionStatus"}],"title":"PermissionStatus","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Puck3DConfiguration":{"type":"topic","kind":"symbol","title":"Puck3DConfiguration","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Puck3DConfiguration","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration","navigatorTitle":[{"text":"Puck3DConfiguration","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/puck3dconfiguration","abstract":[],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PuckRenderingData":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckRenderingData","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PuckRenderingData"}],"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"PuckRenderingData","kind":"identifier"}],"abstract":[{"text":"Represents the interpolated data ready to render the user location puck.","type":"text"}],"url":"\/documentation\/mapboxmaps\/puckrenderingdata","title":"PuckRenderingData"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/AccuracyAuthorization/none":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"title":"AccuracyAuthorization.none","url":"\/documentation\/mapboxcommon\/accuracyauthorization\/none","abstract":[{"text":"An app is not authorized to access location.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization\/none","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBXAccuracyAuthorizationNone"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PuckType":{"abstract":[{"text":"Represents the different types of pucks","type":"text"}],"type":"topic","role":"symbol","kind":"symbol","title":"PuckType","url":"\/documentation\/mapboxmaps\/pucktype","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckType","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PuckType"}],"navigatorTitle":[{"text":"PuckType","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Coordinate2D":{"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Coordinate2D"}],"navigatorTitle":[{"kind":"identifier","text":"Coordinate2D"}],"title":"Coordinate2D","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Coordinate2D","url":"\/documentation\/mapboxcommon\/coordinate2d","abstract":[{"type":"text","text":"Boxed version of CLLocationCoordinate2D"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/DeviceLocationProvider":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/DeviceLocationProvider","role":"symbol","navigatorTitle":[{"text":"DeviceLocationProvider","kind":"identifier"}],"type":"topic","abstract":[{"text":"Location provider specialisation that provides real-time locations generated from the device","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DeviceLocationProvider","kind":"identifier"}],"title":"DeviceLocationProvider","url":"\/documentation\/mapboxcommon\/devicelocationprovider"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationServiceFactory":{"url":"\/documentation\/mapboxcommon\/locationservicefactory","type":"topic","title":"LocationServiceFactory","abstract":[{"type":"text","text":"Location service factory."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"LocationServiceFactory","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceFactory","kind":"symbol","navigatorTitle":[{"text":"LocationServiceFactory","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Location":{"navigatorTitle":[{"kind":"identifier","text":"Location"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location","role":"symbol","abstract":[{"text":"Location information.","type":"text"}],"url":"\/documentation\/mapboxcommon\/location","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Location","kind":"identifier"}],"type":"topic","title":"Location"},"doc://com.mapbox.MapboxMaps/s15BitwiseCopyableP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s15BitwiseCopyableP","title":"Swift.BitwiseCopyable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationProviderRequest":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LocationProviderRequest"}],"navigatorTitle":[{"text":"LocationProviderRequest","kind":"identifier"}],"title":"LocationProviderRequest","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProviderRequest","url":"\/documentation\/mapboxcommon\/locationproviderrequest","abstract":[{"text":"Data model that contains parameters for location requests.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/IntervalSettings":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/IntervalSettings","role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/mapboxcommon\/intervalsettings","navigatorTitle":[{"text":"IntervalSettings","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IntervalSettings","kind":"identifier"}],"title":"IntervalSettings","abstract":[{"type":"text","text":"The interval for active location updates"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationObserver":{"url":"\/documentation\/mapboxcommon\/locationobserver","type":"topic","title":"LocationObserver","abstract":[{"text":"Observer for getting updates from a LocationProvider.","type":"text"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"LocationObserver","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationObserver","navigatorTitle":[{"kind":"identifier","text":"LocationObserver"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/AccuracyAuthorization/RawRepresentable-Implementations":{"abstract":[],"type":"topic","url":"\/documentation\/mapboxcommon\/accuracyauthorization\/rawrepresentable-implementations","kind":"article","role":"collectionGroup","title":"RawRepresentable Implementations","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization\/RawRepresentable-Implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LocationOptions":{"url":"\/documentation\/mapboxmaps\/locationoptions","type":"topic","title":"LocationOptions","abstract":[{"text":"A struct to configure a ","type":"text"},{"code":"LocationManager","type":"codeVoice"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationOptions"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationOptions","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"LocationOptions"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeadingObserver":{"abstract":[{"type":"text","text":"Listens to "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingProvider","type":"reference","isActive":true},{"text":"’s updates.","type":"text"}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/headingobserver","navigatorTitle":[{"kind":"identifier","text":"HeadingObserver"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HeadingObserver"}],"title":"HeadingObserver","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingObserver"},"doc://com.mapbox.MapboxMaps/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s8SendableP","title":"Swift.Sendable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/AccuracyAuthorization/exact":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"exact","kind":"identifier"}],"navigatorTitle":[{"text":"MBXAccuracyAuthorizationExact","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/accuracyauthorization\/exact","abstract":[{"text":"An app is authorized to received as precise as possible location.","type":"text"}],"role":"symbol","title":"AccuracyAuthorization.exact","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization\/exact","kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Model":{"type":"topic","kind":"symbol","title":"Model","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Model"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Model","navigatorTitle":[{"text":"Model","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/model","abstract":[{"text":"A structure represeting a Model","type":"text"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Location-APIs":{"type":"topic","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/location-apis","title":"Location","abstract":[],"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationErrorCode":{"type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LocationErrorCode"}],"url":"\/documentation\/mapboxcommon\/locationerrorcode","navigatorTitle":[{"kind":"identifier","text":"LocationErrorCode"}],"title":"LocationErrorCode","abstract":[{"type":"text","text":"Codes of location errors."}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode"},"doc://com.mapbox.MapboxMaps/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","title":"Swift.Equatable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationProvider":{"abstract":[{"type":"text","text":"Location provider that provides locations"}],"type":"topic","role":"symbol","kind":"symbol","title":"LocationProvider","url":"\/documentation\/mapboxcommon\/locationprovider","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationProvider"}],"navigatorTitle":[{"text":"LocationProvider","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AppleLocationProviderDelegate":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProviderDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AppleLocationProviderDelegate"}],"type":"topic","abstract":[{"type":"text","text":"The "},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProviderDelegate","isActive":true},{"type":"text","text":" protocol defines a set of optional methods that you"},{"text":" ","type":"text"},{"type":"text","text":"can use to receive events from an associated location provider object."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AppleLocationProviderDelegate"}],"title":"AppleLocationProviderDelegate","url":"\/documentation\/mapboxmaps\/applelocationproviderdelegate"},"doc://com.mapbox.MapboxMaps/SY":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SY","title":"Swift.RawRepresentable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/AccuracyLevel":{"abstract":[{"type":"text","text":"The accuracy of the observed location"}],"type":"topic","role":"symbol","kind":"symbol","title":"AccuracyLevel","url":"\/documentation\/mapboxcommon\/accuracylevel","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"AccuracyLevel","kind":"identifier"}],"navigatorTitle":[{"text":"AccuracyLevel","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LocationManager":{"url":"\/documentation\/mapboxmaps\/locationmanager","type":"topic","title":"LocationManager","abstract":[{"text":"An object responsible for managing user location Puck.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"LocationManager","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationManager","navigatorTitle":[{"text":"LocationManager","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/AccuracyAuthorization":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"AccuracyAuthorization","kind":"identifier"}],"navigatorTitle":[{"text":"AccuracyAuthorization","kind":"identifier"}],"type":"topic","abstract":[{"text":"Accuracy authorization granted by user to the app.","type":"text"}],"role":"symbol","url":"\/documentation\/mapboxcommon\/accuracyauthorization","kind":"symbol","title":"AccuracyAuthorization"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","abstract":[],"kind":"article","url":"\/documentation\/overview","type":"topic","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AppleLocationProvider":{"abstract":[{"type":"text","text":"A location provider based on CoreLocation’s "},{"type":"codeVoice","code":"CLLocationManager"},{"type":"text","text":"."}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/applelocationprovider","navigatorTitle":[{"text":"AppleLocationProvider","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AppleLocationProvider","kind":"identifier"}],"title":"AppleLocationProvider","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProvider"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Puck2DConfiguration":{"type":"topic","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Puck2DConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"Puck2DConfiguration"}],"title":"Puck2DConfiguration","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck2DConfiguration","kind":"symbol","url":"\/documentation\/mapboxmaps\/puck2dconfiguration","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Heading":{"abstract":[{"type":"text","text":"The azimuth (orientation) of the user’s device, relative to true or magnetic north."}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/heading","navigatorTitle":[{"kind":"identifier","text":"Heading"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Heading","kind":"identifier"}],"title":"Heading","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Heading"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","url":"\/documentation\/mapboxmaps","role":"collection","title":"MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeadingProvider":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingProvider","role":"symbol","navigatorTitle":[{"text":"HeadingProvider","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Provides heading data to drive the location puck."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HeadingProvider","kind":"identifier"}],"title":"HeadingProvider","url":"\/documentation\/mapboxmaps\/headingprovider"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PuckBearing":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckBearing","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PuckBearing","kind":"identifier"}],"navigatorTitle":[{"text":"PuckBearing","kind":"identifier"}],"type":"topic","abstract":[{"text":"Controls how the puck is oriented","type":"text"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/puckbearing","kind":"symbol","title":"PuckBearing"},"doc://com.mapbox.MapboxMaps/SH":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","title":"Swift.Hashable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/AccuracyAuthorization/inexact":{"title":"AccuracyAuthorization.inexact","type":"topic","role":"symbol","abstract":[{"text":"An app is authorized to receive rough location only.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"inexact","kind":"identifier"}],"navigatorTitle":[{"text":"MBXAccuracyAuthorizationInexact","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization\/inexact","kind":"symbol","url":"\/documentation\/mapboxcommon\/accuracyauthorization\/inexact"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/AccuracyAuthorization/Equatable-Implementations":{"abstract":[],"role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization\/Equatable-Implementations","url":"\/documentation\/mapboxcommon\/accuracyauthorization\/equatable-implementations","kind":"article","title":"Equatable Implementations","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationServiceObserver":{"type":"topic","kind":"symbol","title":"LocationServiceObserver","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LocationServiceObserver"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver","navigatorTitle":[{"text":"LocationServiceObserver","kind":"identifier"}],"abstract":[{"type":"text","text":"Observers for getting updates from LocationService."}],"url":"\/documentation\/mapboxcommon\/locationserviceobserver","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationExtraKeys":{"role":"symbol","navigatorTitle":[{"text":"LocationExtraKeys","kind":"identifier"}],"abstract":[{"text":"Keys for additional information (extra) in Location.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"LocationExtraKeys","kind":"identifier"}],"type":"topic","title":"LocationExtraKeys","url":"\/documentation\/mapboxcommon\/locationextrakeys","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationExtraKeys","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/AccuracyAuthorization/init(rawValue:)":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization\/init(rawValue:)","abstract":[],"role":"symbol","title":"init(rawValue:)","url":"\/documentation\/mapboxcommon\/accuracyauthorization\/init(rawvalue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationError":{"url":"\/documentation\/mapboxcommon\/locationerror","type":"topic","title":"LocationError","abstract":[{"text":"Error code with brief explanation.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LocationError"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationError","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"LocationError"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"path":"\/metadata\/title","value":"MBXAccuracyAuthorization","op":"replace"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MBXAccuracyAuthorization","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MBXAccuracyAuthorization"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization\/exact","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization\/inexact","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization\/none"]}]},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","value":[{"title":"Location","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Coordinate2D","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationExtraKeys","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProviderRequest","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceFactory","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/DeviceLocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/IntervalSettings"],"generated":true,"anchor":"Location"}],"op":"replace"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBXAccuracyAuthorization"},{"kind":"text","text":": "},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"MBXPermissionStatus","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/title"},{"value":[{"kind":"identifier","text":"MBXPermissionStatus"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/fragments","op":"replace"},{"value":[{"text":"MBXPermissionStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization~1none\/title","value":"MBXAccuracyAuthorizationNone"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization~1none\/fragments","value":[{"text":"MBXAccuracyAuthorizationNone","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Coordinate2D\/title","value":"MBXCoordinate2D"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Coordinate2D\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXCoordinate2D"}]},{"value":[{"text":"MBXCoordinate2D","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Coordinate2D\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1DeviceLocationProvider\/title","value":"MBXDeviceLocationProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1DeviceLocationProvider\/fragments","value":[{"text":"MBXDeviceLocationProvider","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1DeviceLocationProvider\/navigatorTitle","op":"replace","value":[{"text":"MBXDeviceLocationProvider","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceFactory\/title","op":"replace","value":"MBXLocationServiceFactory"},{"value":[{"text":"MBXLocationServiceFactory","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceFactory\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceFactory\/navigatorTitle","value":[{"kind":"identifier","text":"MBXLocationServiceFactory"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/title","value":"MBXLocation"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/fragments","value":[{"text":"MBXLocation","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/navigatorTitle","value":[{"text":"MBXLocation","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProviderRequest\/title","value":"MBXLocationProviderRequest"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProviderRequest\/fragments","value":[{"text":"MBXLocationProviderRequest","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MBXLocationProviderRequest"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProviderRequest\/navigatorTitle"},{"value":"MBXIntervalSettings","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1IntervalSettings\/title"},{"value":[{"text":"MBXIntervalSettings","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1IntervalSettings\/fragments"},{"op":"replace","value":[{"text":"MBXIntervalSettings","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1IntervalSettings\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/title","value":"MBXLocationObserver","op":"replace"},{"value":[{"kind":"identifier","text":"MBXLocationObserver"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/navigatorTitle","value":[{"kind":"identifier","text":"MBXLocationObserver"}],"op":"replace"},{"op":"replace","value":"MBXAccuracyAuthorizationExact","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization~1exact\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization~1exact\/fragments","value":[{"kind":"identifier","text":"MBXAccuracyAuthorizationExact"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/title","value":"MBXLocationErrorCode"},{"op":"replace","value":[{"text":"MBXLocationErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/fragments"},{"op":"replace","value":[{"text":"MBXLocationErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/navigatorTitle"},{"value":"MBXLocationProvider","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/title"},{"value":[{"kind":"identifier","text":"MBXLocationProvider"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/navigatorTitle","value":[{"text":"MBXLocationProvider","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel\/title","value":"MBXAccuracyLevel"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel\/fragments","value":[{"kind":"identifier","text":"MBXAccuracyLevel"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel\/navigatorTitle","value":[{"kind":"identifier","text":"MBXAccuracyLevel"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization\/title","value":"MBXAccuracyAuthorization"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization\/fragments","value":[{"kind":"identifier","text":"MBXAccuracyAuthorization"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization\/navigatorTitle","op":"replace","value":[{"text":"MBXAccuracyAuthorization","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization~1inexact\/title","op":"replace","value":"MBXAccuracyAuthorizationInexact"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization~1inexact\/fragments","op":"replace","value":[{"text":"MBXAccuracyAuthorizationInexact","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver\/title","value":"MBXLocationServiceObserver","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver\/fragments","value":[{"text":"MBXLocationServiceObserver","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver\/navigatorTitle","value":[{"text":"MBXLocationServiceObserver","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationExtraKeys\/title","value":"MBXLocationExtraKeys","op":"replace"},{"value":[{"text":"MBXLocationExtraKeys","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationExtraKeys\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationExtraKeys\/navigatorTitle","value":[{"text":"MBXLocationExtraKeys","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"MBXLocationError","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationError\/title"},{"value":[{"kind":"identifier","text":"MBXLocationError"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationError\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationError\/navigatorTitle","value":[{"kind":"identifier","text":"MBXLocationError"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}