{"abstract":[{"type":"text","text":"Releases the OfflineSwitch singleton instance."}],"metadata":{"externalID":"c:objc(cs)MBXOfflineSwitch(cm)reset","navigatorTitle":[{"text":"reset","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"MapboxCommon"}],"title":"reset()","roleHeading":"Type Method","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"reset","kind":"identifier"},{"kind":"text","text":"()"}]},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/OfflineSwitch"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"reset","kind":"identifier"},{"text":"()","kind":"text"}]}]},{"kind":"content","content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"inlineContent":[{"type":"text","text":"Users can call this method if they want to do manual cleanup of the resources allocated by Mapbox services."},{"type":"text","text":" "},{"type":"text","text":"If the user calls getInstance() after reset, a new instance of the OfflineSwitch singleton will be allocated."}],"type":"paragraph"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/OfflineSwitch\/reset()"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/offlineswitch\/reset()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/offlineswitch\/reset()"]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","url":"\/documentation\/overview","abstract":[],"kind":"article","title":"MapboxMaps Documentation","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"kind":"symbol","type":"topic","title":"MapboxCommon","role":"collection","url":"\/documentation\/mapboxcommon","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/OfflineSwitch/reset()":{"navigatorTitle":[{"text":"reset","kind":"identifier"}],"abstract":[{"type":"text","text":"Releases the OfflineSwitch singleton instance."}],"title":"reset()","url":"\/documentation\/mapboxcommon\/offlineswitch\/reset()","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/OfflineSwitch\/reset()","role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reset"},{"text":"()","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/OfflineSwitch":{"type":"topic","title":"OfflineSwitch","navigatorTitle":[{"kind":"identifier","text":"OfflineSwitch"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/OfflineSwitch","kind":"symbol","abstract":[{"text":"Instance that allows connecting or disconnecting the Mapbox stack to the network.","type":"text"}],"role":"symbol","url":"\/documentation\/mapboxcommon\/offlineswitch","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"OfflineSwitch","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","value":"reset","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"reset"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"reset"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"reset","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1OfflineSwitch~1reset()\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1OfflineSwitch~1reset()\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"reset"}]},{"value":"MBXOfflineSwitch","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1OfflineSwitch\/title"},{"value":[{"kind":"identifier","text":"MBXOfflineSwitch"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1OfflineSwitch\/fragments"},{"op":"replace","value":[{"text":"MBXOfflineSwitch","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1OfflineSwitch\/navigatorTitle"}]}]}