{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionTilePyramidDefinition"]]},"metadata":{"externalID":"c:objc(cs)MBMOfflineRegionTilePyramidDefinition(py)minZoom","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"minZoom"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"platforms":[],"navigatorTitle":[{"kind":"identifier","text":"minZoom"}],"role":"symbol","title":"minZoom","symbolKind":"property","modules":[{"name":"MapboxMaps"}],"roleHeading":"Instance Property"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionTilePyramidDefinition\/minZoom"},"variants":[{"paths":["\/documentation\/mapboxmaps\/offlineregiontilepyramiddefinition\/minzoom"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/offlineregiontilepyramiddefinition\/minzoom"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"minZoom","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","abstract":[{"type":"text","text":"Minimum zoom level for the offline region."}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Offline":{"abstract":[],"url":"\/documentation\/mapboxmaps\/offline","type":"topic","role":"collectionGroup","title":"Offline Support","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionTilePyramidDefinition/minZoom":{"navigatorTitle":[{"text":"minZoom","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"minZoom","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"type":"topic","abstract":[{"type":"text","text":"Minimum zoom level for the offline region."}],"url":"\/documentation\/mapboxmaps\/offlineregiontilepyramiddefinition\/minzoom","role":"symbol","title":"minZoom","deprecated":true,"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionTilePyramidDefinition\/minZoom"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","kind":"article","role":"collection","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMaps":{"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","role":"collectionGroup","type":"topic","title":"Core Maps API","url":"\/documentation\/mapboxmaps\/coremaps","abstract":[{"text":"Maps rendering SDK also known as GL-Native","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"title":"MapboxMaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionTilePyramidDefinition":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OfflineRegionTilePyramidDefinition"}],"title":"OfflineRegionTilePyramidDefinition","deprecated":true,"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionTilePyramidDefinition","url":"\/documentation\/mapboxmaps\/offlineregiontilepyramiddefinition","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OfflineRegionTilePyramidDefinition"}],"type":"topic","abstract":[{"text":"An offline region definition is a geographic region defined by a style URL,","type":"text"},{"type":"text","text":" "},{"text":"geographic bounding box, zoom range, and device pixel ratio. Both ","type":"text"},{"code":"minZoom","type":"codeVoice"},{"type":"text","text":" and "},{"type":"codeVoice","code":"maxZoom"},{"type":"text","text":" must be ≥ 0,"},{"type":"text","text":" "},{"text":"and ","type":"text"},{"type":"codeVoice","code":"maxZoom"},{"text":" must be ≥ ","type":"text"},{"code":"minZoom","type":"codeVoice"},{"type":"text","text":". The "},{"code":"maxZoom","type":"codeVoice"},{"type":"text","text":" may be ∞, in which case for each tile source,"},{"text":" ","type":"text"},{"text":"the region will include tiles from ","type":"text"},{"code":"minZoom","type":"codeVoice"},{"type":"text","text":" up to the maximum zoom level provided by that source."},{"type":"text","text":" "},{"text":"The ","type":"text"},{"type":"codeVoice","code":"pixelRatio"},{"type":"text","text":" must be ≥ 0 and should typically be 1.0 or 2.0."}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"minZoom","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"minZoom"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":" ","kind":"text"},{"kind":"identifier","text":"minZoom"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionTilePyramidDefinition~1minZoom\/title","value":"minZoom","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionTilePyramidDefinition~1minZoom\/fragments","value":[{"kind":"identifier","text":"minZoom"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionTilePyramidDefinition\/title","value":"MBMOfflineRegionTilePyramidDefinition"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionTilePyramidDefinition\/fragments","value":[{"kind":"identifier","text":"MBMOfflineRegionTilePyramidDefinition"}]},{"value":[{"text":"MBMOfflineRegionTilePyramidDefinition","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionTilePyramidDefinition\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}