{"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestInfo\/init(url:resource:priority:loadingMethod:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestInfo"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"url","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"resource","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMRequestResourceType","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType","text":"RequestResourceType"},{"kind":"text","text":", "},{"text":"priority","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@MBMRequestPriorityType","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestPriorityType","text":"RequestPriorityType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"loadingMethod"},{"text":": [","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"])"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"symbolKind":"init","roleHeading":"Initializer","navigatorTitle":[{"text":"initWithUrl:resource:priority:loadingMethod:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"url","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"resource","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@MBMRequestResourceType","text":"RequestResourceType","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"priority","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RequestPriorityType","preciseIdentifier":"c:@E@MBMRequestPriorityType"},{"kind":"text","text":", "},{"text":"loadingMethod","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"])"}],"modules":[{"name":"MapboxMaps"}],"role":"symbol","title":"init(url:resource:priority:loadingMethod:)","externalID":"c:objc(cs)MBMRequestInfo(im)initWithUrl:resource:priority:loadingMethod:"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/requestinfo\/init(url:resource:priority:loadingmethod:)"]},{"paths":["\/documentation\/mapboxmaps\/requestinfo\/init(url:resource:priority:loadingmethod:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestPriorityType":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"RequestPriorityType","kind":"identifier"}],"navigatorTitle":[{"text":"RequestPriorityType","kind":"identifier"}],"title":"RequestPriorityType","type":"topic","abstract":[{"type":"text","text":"The enumeration defines the priority of a resource request."}],"url":"\/documentation\/mapboxmaps\/requestprioritytype","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestPriorityType"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"url":"\/documentation\/mapboxmaps\/events","abstract":[{"type":"text","text":"The simplified diagram of the events emitted by the map is displayed below."}],"type":"topic","kind":"article","title":"Map events","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","url":"\/documentation\/mapboxmaps","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"title":"MapboxMaps","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestInfo":{"abstract":[{"type":"text","text":"The structure defines the information about the resource request."}],"role":"symbol","title":"RequestInfo","url":"\/documentation\/mapboxmaps\/requestinfo","type":"topic","kind":"symbol","navigatorTitle":[{"text":"RequestInfo","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestInfo","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RequestInfo"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestResourceType":{"abstract":[{"text":"The enumeration defines the type of resource requested by the ","type":"text"},{"type":"codeVoice","code":"map"},{"type":"text","text":"."}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"RequestResourceType","kind":"identifier"}],"title":"RequestResourceType","kind":"symbol","url":"\/documentation\/mapboxmaps\/requestresourcetype","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"RequestResourceType"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","abstract":[],"type":"topic","kind":"article","title":"MapboxMaps Documentation","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestInfo/init(url:resource:priority:loadingMethod:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestInfo\/init(url:resource:priority:loadingMethod:)","kind":"symbol","navigatorTitle":[{"text":"initWithUrl:resource:priority:loadingMethod:","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/requestinfo\/init(url:resource:priority:loadingmethod:)","type":"topic","abstract":[],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"url","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"resource","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"RequestResourceType","preciseIdentifier":"c:@E@MBMRequestResourceType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"priority","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"RequestPriorityType","preciseIdentifier":"c:@E@MBMRequestPriorityType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"loadingMethod"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"])"}],"title":"init(url:resource:priority:loadingMethod:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithUrl:resource:priority:loadingMethod:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithUrl:resource:priority:loadingMethod:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithUrl:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"url","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"resource:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"MBMRequestResourceType","preciseIdentifier":"c:@E@MBMRequestResourceType","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType"},{"text":") ","kind":"text"},{"text":"resource","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"priority:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@MBMRequestPriorityType","text":"MBMRequestPriorityType","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestPriorityType","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"priority"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadingMethod:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSNumber *>","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"loadingMethod"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestPriorityType\/title","value":"MBMRequestPriorityType","op":"replace"},{"op":"replace","value":[{"text":"MBMRequestPriorityType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestPriorityType\/fragments"},{"value":[{"kind":"identifier","text":"MBMRequestPriorityType"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestPriorityType\/navigatorTitle"},{"value":"MBMRequestInfo","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestInfo\/title"},{"value":[{"kind":"identifier","text":"MBMRequestInfo"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestInfo\/fragments","op":"replace"},{"op":"replace","value":[{"text":"MBMRequestInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestInfo\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestResourceType\/title","value":"MBMRequestResourceType"},{"op":"replace","value":[{"kind":"identifier","text":"MBMRequestResourceType"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestResourceType\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestResourceType\/navigatorTitle","value":[{"text":"MBMRequestResourceType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestInfo~1init(url:resource:priority:loadingMethod:)\/title","value":"initWithUrl:resource:priority:loadingMethod:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"initWithUrl:resource:priority:loadingMethod:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestInfo~1init(url:resource:priority:loadingMethod:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}