{"metadata":{"role":"symbol","externalID":"c:objc(cs)MBMRequestInfo(py)priority","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"priority"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@MBMRequestPriorityType","kind":"typeIdentifier","text":"RequestPriorityType"}],"symbolKind":"property","title":"priority","roleHeading":"Instance Property","navigatorTitle":[{"text":"priority","kind":"identifier"}],"modules":[{"name":"MapboxMaps"}]},"abstract":[{"type":"text","text":"The priority of a resource request."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"priority","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMRequestPriorityType","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestPriorityType","text":"RequestPriorityType"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/requestinfo\/priority"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/requestinfo\/priority"]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestInfo\/priority","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestInfo"]]},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","role":"collection","url":"\/documentation\/overview","kind":"article","abstract":[],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestInfo/priority":{"abstract":[{"text":"The priority of a resource request.","type":"text"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"priority"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@MBMRequestPriorityType","kind":"typeIdentifier","text":"RequestPriorityType"}],"title":"priority","type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/requestinfo\/priority","navigatorTitle":[{"text":"priority","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestInfo\/priority"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestPriorityType":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/requestprioritytype","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestPriorityType","abstract":[{"type":"text","text":"The enumeration defines the priority of a resource request."}],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RequestPriorityType"}],"title":"RequestPriorityType","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"RequestPriorityType"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"title":"MapboxMaps","kind":"symbol","role":"collection","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestInfo":{"abstract":[{"text":"The structure defines the information about the resource request.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestInfo","title":"RequestInfo","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"RequestInfo","kind":"identifier"}],"navigatorTitle":[{"text":"RequestInfo","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/requestinfo","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"url":"\/documentation\/mapboxmaps\/events","kind":"article","role":"collectionGroup","title":"Map events","abstract":[{"type":"text","text":"The simplified diagram of the events emitted by the map is displayed below."}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"priority"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"priority","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMRequestPriorityType","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestPriorityType","text":"MBMRequestPriorityType"},{"text":" ","kind":"text"},{"kind":"identifier","text":"priority"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestInfo~1priority\/title","value":"priority"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestInfo~1priority\/fragments","value":[{"kind":"identifier","text":"priority"}]},{"op":"replace","value":"MBMRequestPriorityType","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestPriorityType\/title"},{"value":[{"text":"MBMRequestPriorityType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestPriorityType\/fragments"},{"value":[{"kind":"identifier","text":"MBMRequestPriorityType"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestPriorityType\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestInfo\/title","value":"MBMRequestInfo","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestInfo\/fragments","value":[{"kind":"identifier","text":"MBMRequestInfo"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestInfo\/navigatorTitle","value":[{"text":"MBMRequestInfo","kind":"identifier"}],"op":"replace"}]}]}