{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestInfo"]]},"metadata":{"externalID":"c:objc(cs)MBMRequestInfo(py)resource","role":"symbol","navigatorTitle":[{"text":"resource","kind":"identifier"}],"modules":[{"name":"MapboxMaps"}],"roleHeading":"Instance Property","symbolKind":"property","title":"resource","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"resource","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMRequestResourceType","text":"RequestResourceType"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"The type of a requested resource."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestInfo\/resource"},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"resource"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType","text":"RequestResourceType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMRequestResourceType"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/requestinfo\/resource"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/requestinfo\/resource"]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestInfo":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestInfo","abstract":[{"type":"text","text":"The structure defines the information about the resource request."}],"role":"symbol","navigatorTitle":[{"text":"RequestInfo","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RequestInfo","kind":"identifier"}],"type":"topic","title":"RequestInfo","url":"\/documentation\/mapboxmaps\/requestinfo"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/mapboxmaps","title":"MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestInfo/resource":{"abstract":[{"type":"text","text":"The type of a requested resource."}],"url":"\/documentation\/mapboxmaps\/requestinfo\/resource","type":"topic","kind":"symbol","title":"resource","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestInfo\/resource","navigatorTitle":[{"text":"resource","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"resource"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"RequestResourceType","preciseIdentifier":"c:@E@MBMRequestResourceType"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"url":"\/documentation\/mapboxmaps\/events","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","type":"topic","title":"Map events","abstract":[{"text":"The simplified diagram of the events emitted by the map is displayed below.","type":"text"}],"role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestResourceType":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType","abstract":[{"text":"The enumeration defines the type of resource requested by the ","type":"text"},{"code":"map","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"RequestResourceType","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RequestResourceType"}],"type":"topic","title":"RequestResourceType","url":"\/documentation\/mapboxmaps\/requestresourcetype"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","abstract":[],"kind":"article","role":"collection","url":"\/documentation\/overview"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"resource"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"resource","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"MBMRequestResourceType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMRequestResourceType","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType"},{"text":" ","kind":"text"},{"kind":"identifier","text":"resource"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestInfo\/title","op":"replace","value":"MBMRequestInfo"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestInfo\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMRequestInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestInfo\/navigatorTitle","value":[{"kind":"identifier","text":"MBMRequestInfo"}]},{"value":"resource","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestInfo~1resource\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestInfo~1resource\/fragments","value":[{"text":"resource","kind":"identifier"}]},{"value":"MBMRequestResourceType","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestResourceType\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestResourceType\/fragments","value":[{"kind":"identifier","text":"MBMRequestResourceType"}],"op":"replace"},{"value":[{"kind":"identifier","text":"MBMRequestResourceType"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestResourceType\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}