{"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStylePackLoadOptions\/initWithGlyphsRasterizationMode:metadata:extraOptions:","interfaceLanguage":"occ"},"kind":"symbol","variants":[{"paths":["\/documentation\/mapboxmaps\/mbmstylepackloadoptions\/initwithglyphsrasterizationmode:metadata:extraoptions:"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"initWithGlyphsRasterizationMode:metadata:extraOptions:","symbolKind":"method","modules":[{"name":"MapboxMaps"}],"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithGlyphsRasterizationMode:metadata:extraOptions:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithGlyphsRasterizationMode:metadata:extraOptions:","kind":"identifier"}],"roleHeading":"Instance Method","externalID":"c:objc(cs)MBMStylePackLoadOptions(im)initWithGlyphsRasterizationMode:metadata:extraOptions:"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadOptions"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithGlyphsRasterizationMode:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"glyphsRasterizationMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"metadata:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"internalParam","text":"metadata"},{"kind":"text","text":" "},{"kind":"identifier","text":"extraOptions:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"internalParam","text":"extraOptions"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMStylePackLoadOptions/initWithGlyphsRasterizationMode:metadata:extraOptions:":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithGlyphsRasterizationMode:metadata:extraOptions:"}],"title":"initWithGlyphsRasterizationMode:metadata:extraOptions:","kind":"symbol","abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithGlyphsRasterizationMode:metadata:extraOptions:"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStylePackLoadOptions\/initWithGlyphsRasterizationMode:metadata:extraOptions:","url":"\/documentation\/mapboxmaps\/mbmstylepackloadoptions\/initwithglyphsrasterizationmode:metadata:extraoptions:"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePackLoadOptions":{"type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/stylepackloadoptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadOptions","title":"StylePackLoadOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StylePackLoadOptions"}],"navigatorTitle":[{"kind":"identifier","text":"StylePackLoadOptions"}],"abstract":[{"type":"text","text":"Describes the style package load option values."}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","type":"topic","abstract":[],"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","role":"collectionGroup","abstract":[],"kind":"article","url":"\/documentation\/mapboxmaps\/tilestore-apis","type":"topic","title":"TileStore APIs"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","kind":"symbol","type":"topic","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MBMStylePackLoadOptions","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadOptions\/title"},{"value":[{"text":"MBMStylePackLoadOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadOptions\/fragments"},{"value":[{"kind":"identifier","text":"MBMStylePackLoadOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadOptions\/navigatorTitle"}]}]}