{"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatisticsOptions"]]},"metadata":{"symbolKind":"method","roleHeading":"Instance Method","role":"symbol","externalID":"c:objc(cs)MBMPerformanceStatisticsOptions(im)isEqualToPerformanceStatisticsOptions:","title":"isEqual(to:)","modules":[{"name":"MapboxMaps"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"kind":"text","text":"("},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PerformanceStatisticsOptions","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMPerformanceStatisticsOptions"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"isEqualToPerformanceStatisticsOptions:","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/mapboxmaps\/performancestatisticsoptions\/isequal(to:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/performancestatisticsoptions\/isequal(to:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"text":"to","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"other"},{"text":": ","kind":"text"},{"text":"PerformanceStatisticsOptions","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMPerformanceStatisticsOptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatisticsOptions"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatisticsOptions\/isEqual(to:)"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PerformanceStatisticsOptions/isEqual(to:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatisticsOptions\/isEqual(to:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMPerformanceStatisticsOptions","text":"PerformanceStatisticsOptions"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"title":"isEqual(to:)","type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/performancestatisticsoptions\/isequal(to:)","abstract":[],"navigatorTitle":[{"text":"isEqualToPerformanceStatisticsOptions:","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PerformanceStatisticsOptions":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatisticsOptions","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PerformanceStatisticsOptions"}],"title":"PerformanceStatisticsOptions","type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/performancestatisticsoptions","abstract":[{"text":"Options for the following statistics collection behaviors:","type":"text"}],"navigatorTitle":[{"text":"PerformanceStatisticsOptions","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Performance":{"role":"collectionGroup","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","abstract":[],"kind":"article","title":"Performance and investigations","url":"\/documentation\/mapboxmaps\/performance"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"url":"\/documentation\/mapboxmaps","title":"MapboxMaps","type":"topic","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/overview"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"isEqualToPerformanceStatisticsOptions:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqualToPerformanceStatisticsOptions:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isEqualToPerformanceStatisticsOptions:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)MBMPerformanceStatisticsOptions","text":"MBMPerformanceStatisticsOptions","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatisticsOptions"},{"text":" *) ","kind":"text"},{"text":"other","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"isEqualToPerformanceStatisticsOptions:","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatisticsOptions~1isEqual(to:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"isEqualToPerformanceStatisticsOptions:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatisticsOptions~1isEqual(to:)\/fragments"},{"value":"MBMPerformanceStatisticsOptions","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatisticsOptions\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatisticsOptions\/fragments","value":[{"text":"MBMPerformanceStatisticsOptions","kind":"identifier"}],"op":"replace"},{"value":[{"text":"MBMPerformanceStatisticsOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatisticsOptions\/navigatorTitle"}]}]}