{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getInstanceFor"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"storageType"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceStorageType","kind":"typeIdentifier","text":"SettingsServiceStorageType","preciseIdentifier":"c:@E@MBXSettingsServiceStorageType"},{"kind":"text","text":") -> "},{"text":"SettingsService","preciseIdentifier":"c:objc(cs)MBXSettingsService","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsService","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"role":"symbol","modules":[{"name":"MapboxCommon"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getInstanceFor","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBXSettingsServiceStorageType","text":"SettingsServiceStorageType"},{"text":") -> ","kind":"text"},{"text":"SettingsService","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXSettingsService"}],"navigatorTitle":[{"kind":"identifier","text":"getInstanceForStorageType:"}],"roleHeading":"Type Method","externalID":"c:objc(cs)MBXSettingsServiceFactory(cm)getInstanceForStorageType:","title":"getInstanceFor(_:)","symbolKind":"method"},"abstract":[{"text":"Create a new instance of the settings service if it doesn’t exist already, or returns already created instance.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Settings-and-Constants","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceFactory"]]},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceFactory\/getInstanceFor(_:)","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/settingsservicefactory\/getinstancefor(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/settingsservicefactory\/getinstancefor(_:)"]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Settings-and-Constants":{"url":"\/documentation\/mapboxmaps\/settings-and-constants","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Settings-and-Constants","title":"Settings and Constants","kind":"article","type":"topic","role":"collectionGroup","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsServiceStorageType":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SettingsServiceStorageType","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/mapboxcommon\/settingsservicestoragetype","kind":"symbol","title":"SettingsServiceStorageType","abstract":[{"text":"Enum that contains possible storage types that can be used for settings service.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SettingsServiceStorageType"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceStorageType"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsServiceFactory/getInstanceFor(_:)":{"title":"getInstanceFor(_:)","navigatorTitle":[{"kind":"identifier","text":"getInstanceForStorageType:"}],"abstract":[{"text":"Create a new instance of the settings service if it doesn’t exist already, or returns already created instance.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getInstanceFor","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SettingsServiceStorageType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBXSettingsServiceStorageType"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBXSettingsService","kind":"typeIdentifier","text":"SettingsService"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceFactory\/getInstanceFor(_:)","url":"\/documentation\/mapboxcommon\/settingsservicefactory\/getinstancefor(_:)","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsServiceFactory":{"title":"SettingsServiceFactory","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceFactory","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SettingsServiceFactory","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/settingsservicefactory","abstract":[{"type":"text","text":"Factory that allows to create settings service instance."}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"SettingsServiceFactory","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsService":{"type":"topic","title":"SettingsService","url":"\/documentation\/mapboxcommon\/settingsservice","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsService","role":"symbol","navigatorTitle":[{"text":"SettingsService","kind":"identifier"}],"abstract":[{"type":"text","text":"Platform independent settings service. Settings service is a key\/value storage (persistent or non"},{"text":" ","type":"text"},{"text":"persistent), that also allows to register observers to get notifications when values are updated.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SettingsService","kind":"identifier"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","kind":"article","type":"topic","url":"\/documentation\/overview","title":"MapboxMaps Documentation","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","role":"collection","title":"MapboxMaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"value":"getInstanceForStorageType:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"text":"getInstanceForStorageType:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"MBXSettingsService","preciseIdentifier":"c:objc(cs)MBXSettingsService","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsService","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"getInstanceForStorageType:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MBXSettingsServiceStorageType","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceStorageType","preciseIdentifier":"c:@E@MBXSettingsServiceStorageType"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"storageType"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceStorageType\/title","value":"MBXSettingsServiceStorageType"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceStorageType\/fragments","value":[{"text":"MBXSettingsServiceStorageType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceStorageType\/navigatorTitle","value":[{"text":"MBXSettingsServiceStorageType","kind":"identifier"}],"op":"replace"},{"value":"getInstanceForStorageType:","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceFactory~1getInstanceFor(_:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceFactory~1getInstanceFor(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"getInstanceForStorageType:"}],"op":"replace"},{"value":"MBXSettingsServiceFactory","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceFactory\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceFactory\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXSettingsServiceFactory"}]},{"value":[{"kind":"identifier","text":"MBXSettingsServiceFactory"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceFactory\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsService\/title","value":"MBXSettingsService"},{"op":"replace","value":[{"kind":"identifier","text":"MBXSettingsService"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsService\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsService\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBXSettingsService"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}