{"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"openGLContextLost","kind":"identifier"},{"kind":"text","text":"()"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"As Apple is deprecating legacy OpenGL API, this method is optional and is called only if"},{"text":" ","type":"text"},{"type":"text","text":"underlying map rendering backend uses OpenGL graphic API."}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/customlayerhost\/openglcontextlost()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/customlayerhost\/openglcontextlost()"]}],"kind":"symbol","metadata":{"roleHeading":"Instance Method","modules":[{"name":"MapboxMaps"}],"symbolKind":"method","role":"symbol","title":"openGLContextLost()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openGLContextLost"},{"kind":"text","text":"()"}],"externalID":"c:objc(pl)MBMCustomLayerHost(im)openGLContextLost","navigatorTitle":[{"kind":"identifier","text":"openGLContextLost"}]},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerHost"]]},"sections":[],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerHost\/openGLContextLost()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when the system has destroyed the underlying OpenGL context. The"},{"text":" ","type":"text"},{"type":"codeVoice","code":"renderingWillEnd"},{"text":" function will not be called in this case, however","type":"text"},{"type":"text","text":" "},{"type":"codeVoice","code":"setupRendering"},{"text":" will be called instead to prepare for a new render.","type":"text"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layers":{"abstract":[],"role":"collectionGroup","title":"Layers","url":"\/documentation\/mapboxmaps\/layers","kind":"article","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","title":"MapboxMaps","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerHost":{"kind":"symbol","title":"CustomLayerHost","abstract":[{"text":"Interface for hosting a custom map style layer.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"CustomLayerHost","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"CustomLayerHost","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerHost","url":"\/documentation\/mapboxmaps\/customlayerhost"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article","role":"collection","type":"topic","abstract":[],"url":"\/documentation\/overview","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerHost/openGLContextLost()":{"title":"openGLContextLost()","navigatorTitle":[{"text":"openGLContextLost","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"openGLContextLost"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerHost\/openGLContextLost()","url":"\/documentation\/mapboxmaps\/customlayerhost\/openglcontextlost()","kind":"symbol","abstract":[{"text":"Called when the system has destroyed the underlying OpenGL context. The","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"renderingWillEnd"},{"type":"text","text":" function will not be called in this case, however"},{"type":"text","text":" "},{"type":"codeVoice","code":"setupRendering"},{"text":" will be called instead to prepare for a new render.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"openGLContextLost","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"openGLContextLost","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"openGLContextLost","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MBMCustomLayerHost","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBMCustomLayerHost"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost\/fragments"},{"value":[{"text":"MBMCustomLayerHost","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost~1openGLContextLost()\/title","value":"openGLContextLost"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost~1openGLContextLost()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"openGLContextLost","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}