{"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgress\/completedResourceCount","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/mapboxcommon\/tileregionloadprogress\/completedresourcecount"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/tileregionloadprogress\/completedresourcecount"]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgress"]]},"metadata":{"modules":[{"name":"MapboxCommon"}],"title":"completedResourceCount","externalID":"c:objc(cs)MBXTileRegionLoadProgress(py)completedResourceCount","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"completedResourceCount","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt64","preciseIdentifier":"s:s6UInt64V"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"completedResourceCount"}],"roleHeading":"Instance Property"},"abstract":[{"text":"The number of resources that are ready for offline access.","type":"text"}],"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"completedResourceCount","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V","text":"UInt64"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"type":"topic","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","url":"\/documentation\/mapboxmaps\/tilestore-apis","kind":"article","title":"TileStore APIs"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadProgress":{"navigatorTitle":[{"text":"TileRegionLoadProgress","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"A tile region’s load progress includes counts"},{"type":"text","text":" "},{"text":"of the number of resources that have completed downloading","type":"text"},{"type":"text","text":" "},{"type":"text","text":"and the total number of resources that are required."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TileRegionLoadProgress","kind":"identifier"}],"type":"topic","kind":"symbol","title":"TileRegionLoadProgress","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgress","url":"\/documentation\/mapboxcommon\/tileregionloadprogress"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadProgress/completedResourceCount":{"type":"topic","url":"\/documentation\/mapboxcommon\/tileregionloadprogress\/completedresourcecount","title":"completedResourceCount","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"completedResourceCount","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V","text":"UInt64"}],"navigatorTitle":[{"kind":"identifier","text":"completedResourceCount"}],"role":"symbol","kind":"symbol","abstract":[{"text":"The number of resources that are ready for offline access.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgress\/completedResourceCount"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","kind":"article","abstract":[],"title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","role":"collection","title":"MapboxMaps","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"completedResourceCount"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"completedResourceCount"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@uint64_t","text":"uint64_t","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completedResourceCount"},{"text":";","kind":"text"}]}]},"op":"replace"},{"value":"MBXTileRegionLoadProgress","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgress\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgress\/fragments","value":[{"text":"MBXTileRegionLoadProgress","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"MBXTileRegionLoadProgress"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgress\/navigatorTitle"},{"op":"replace","value":"completedResourceCount","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgress~1completedResourceCount\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgress~1completedResourceCount\/fragments","op":"replace","value":[{"text":"completedResourceCount","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}