{"kind":"symbol","metadata":{"roleHeading":"Type Method","role":"symbol","symbolKind":"method","title":"getInstance(storageType:)","externalID":"s:So25MBXSettingsServiceFactoryC12MapboxCommonE11getInstance11storageTypeSo0aB0CSo0ab7StorageI0V_tFZ","modules":[{"name":"MapboxCommon"}],"extendedModule":"MapboxCommon","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getInstance","kind":"identifier"},{"text":"(","kind":"text"},{"text":"storageType","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@MBXSettingsServiceStorageType","text":"SettingsServiceStorageType","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"SettingsService","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXSettingsService"}]},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Settings-and-Constants","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceFactory"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"getInstance","kind":"identifier"},{"text":"(","kind":"text"},{"text":"storageType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SettingsServiceStorageType","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceStorageType","preciseIdentifier":"c:@E@MBXSettingsServiceStorageType","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"SettingsService","preciseIdentifier":"c:objc(cs)MBXSettingsService","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsService"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceFactory\/getInstance(storageType:)","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/mapboxcommon\/settingsservicefactory\/getinstance(storagetype:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","abstract":[],"kind":"article","role":"collection","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsService":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsService","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SettingsService"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SettingsService","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/mapboxcommon\/settingsservice","abstract":[{"type":"text","text":"Platform independent settings service. Settings service is a key\/value storage (persistent or non"},{"type":"text","text":" "},{"text":"persistent), that also allows to register observers to get notifications when values are updated.","type":"text"}],"title":"SettingsService"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsServiceFactory":{"title":"SettingsServiceFactory","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceFactory","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SettingsServiceFactory"}],"role":"symbol","abstract":[{"text":"Factory that allows to create settings service instance.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SettingsServiceFactory"}],"url":"\/documentation\/mapboxcommon\/settingsservicefactory"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Settings-and-Constants":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Settings-and-Constants","kind":"article","role":"collectionGroup","type":"topic","url":"\/documentation\/mapboxmaps\/settings-and-constants","abstract":[],"title":"Settings and Constants"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsServiceFactory/getInstance(storageType:)":{"role":"symbol","abstract":[],"title":"getInstance(storageType:)","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceFactory\/getInstance(storageType:)","url":"\/documentation\/mapboxcommon\/settingsservicefactory\/getinstance(storagetype:)","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getInstance","kind":"identifier"},{"text":"(","kind":"text"},{"text":"storageType","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@MBXSettingsServiceStorageType","text":"SettingsServiceStorageType","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXSettingsService","text":"SettingsService"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsServiceStorageType":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceStorageType","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SettingsServiceStorageType","kind":"identifier"}],"abstract":[{"type":"text","text":"Enum that contains possible storage types that can be used for settings service."}],"title":"SettingsServiceStorageType","type":"topic","navigatorTitle":[{"text":"SettingsServiceStorageType","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/settingsservicestoragetype","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsService\/title","op":"replace","value":"MBXSettingsService"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsService\/fragments","value":[{"text":"MBXSettingsService","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsService\/navigatorTitle","value":[{"text":"MBXSettingsService","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceFactory\/title","value":"MBXSettingsServiceFactory","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceFactory\/fragments","op":"replace","value":[{"text":"MBXSettingsServiceFactory","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceFactory\/navigatorTitle","value":[{"kind":"identifier","text":"MBXSettingsServiceFactory"}],"op":"replace"},{"value":"MBXSettingsServiceStorageType","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceStorageType\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceStorageType\/fragments","op":"replace","value":[{"text":"MBXSettingsServiceStorageType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceStorageType\/navigatorTitle","op":"replace","value":[{"text":"MBXSettingsServiceStorageType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}