{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"multiLine","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"locations","kind":"internalParam"},{"kind":"text","text":": [["},{"kind":"typeIdentifier","text":"NSValue","preciseIdentifier":"c:objc(cs)NSValue"},{"kind":"text","text":"]])"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/mapboxcommon\/geometry\/init(multiline:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/geometry\/init(multiline:)"]}],"metadata":{"roleHeading":"Initializer","externalID":"c:objc(cs)MBXGeometry(im)initWithMultiLine:","modules":[{"name":"MapboxCommon"}],"symbolKind":"init","role":"symbol","title":"init(multiLine:)","navigatorTitle":[{"kind":"identifier","text":"initWithMultiLine:"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"multiLine"},{"text":": [[","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSValue","kind":"typeIdentifier","text":"NSValue"},{"kind":"text","text":"]])"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry\/init(multiLine:)"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"kind":"article","role":"collection","url":"\/documentation\/overview","title":"MapboxMaps Documentation","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Geometry":{"type":"topic","title":"Geometry","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Geometry","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/geometry","abstract":[],"navigatorTitle":[{"text":"Geometry","kind":"identifier"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"abstract":[],"url":"\/documentation\/mapboxcommon","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","type":"topic","role":"collection","title":"MapboxCommon","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Geometry/init(multiLine:)":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry\/init(multiLine:)","navigatorTitle":[{"kind":"identifier","text":"initWithMultiLine:"}],"url":"\/documentation\/mapboxcommon\/geometry\/init(multiline:)","title":"init(multiLine:)","abstract":[],"role":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"multiLine","kind":"externalParam"},{"kind":"text","text":": [["},{"text":"NSValue","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSValue"},{"text":"]])","kind":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithMultiLine:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithMultiLine:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithMultiLine:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSArray<NSValue *> *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"locations","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"MBXGeometry","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBXGeometry"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry\/navigatorTitle","value":[{"text":"MBXGeometry","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"initWithMultiLine:","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry~1init(multiLine:)\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry~1init(multiLine:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithMultiLine:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}