{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/mbmcoordinatebounds\/world"]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","text":"MBMCoordinateBounds","preciseIdentifier":"c:objc(cs)MBMCoordinateBounds","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"world"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},{"content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"inlineContent":[{"text":"The newly constructed record.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCoordinateBounds\/world"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"MapboxMaps"}],"role":"symbol","title":"world","externalID":"c:objc(cs)MBMCoordinateBounds(cm)world","navigatorTitle":[{"text":"world","kind":"identifier"}],"symbolKind":"method","roleHeading":"Type Method","fragments":[{"kind":"text","text":"+ "},{"text":"world","kind":"identifier"}]},"abstract":[{"type":"text","text":"Returns a bounds covering the entire (unwrapped) world."}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"url":"\/documentation\/mapboxmaps\/mapboxmap-apis","kind":"article","title":"MapboxMap","role":"collectionGroup","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateBounds":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds","type":"topic","url":"\/documentation\/mapboxmaps\/coordinatebounds","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CoordinateBounds"}],"abstract":[{"type":"text","text":"A rectangular area as measured on a two-dimensional map projection."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"CoordinateBounds","kind":"identifier"}],"title":"CoordinateBounds"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","url":"\/documentation\/overview","abstract":[],"type":"topic","role":"collection","title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMCoordinateBounds/world":{"url":"\/documentation\/mapboxmaps\/mbmcoordinatebounds\/world","abstract":[{"type":"text","text":"Returns a bounds covering the entire (unwrapped) world."}],"fragments":[{"text":"+ ","kind":"text"},{"text":"world","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"world","kind":"identifier"}],"kind":"symbol","title":"world","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCoordinateBounds\/world"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds\/title","value":"MBMCoordinateBounds"},{"op":"replace","value":[{"text":"MBMCoordinateBounds","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds\/fragments"},{"value":[{"kind":"identifier","text":"MBMCoordinateBounds"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds\/navigatorTitle","op":"replace"}]}]}