{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreObserver\/onRegionLoadProgress(forId:progress:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/tilestoreobserver\/onregionloadprogress(forid:progress:)"]}],"sections":[],"metadata":{"symbolKind":"method","modules":[{"name":"MapboxMaps"}],"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onRegionLoadProgress","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"progress","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TileRegionLoadProgress","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXTileRegionLoadProgress"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","title":"onRegionLoadProgress(forId:progress:)","role":"symbol","externalID":"s:10MapboxMaps17TileStoreObserverP20onRegionLoadProgress5forId8progressySS_So07MBXTileghI0CtF"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreObserver"]]},"abstract":[{"type":"text","text":"Called whenever the load progress of a "},{"type":"codeVoice","code":"TileRegion"},{"type":"text","text":" changes."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onRegionLoadProgress"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forId"},{"kind":"text","text":" "},{"kind":"internalParam","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"progress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TileRegionLoadProgress","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgress","preciseIdentifier":"c:objc(cs)MBXTileRegionLoadProgress"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStoreObserver/onRegionLoadProgress(forId:progress:)":{"abstract":[{"text":"Called whenever the load progress of a ","type":"text"},{"code":"TileRegion","type":"codeVoice"},{"text":" changes.","type":"text"}],"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onRegionLoadProgress","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"progress","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBXTileRegionLoadProgress","text":"TileRegionLoadProgress","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreObserver\/onRegionLoadProgress(forId:progress:)","title":"onRegionLoadProgress(forId:progress:)","url":"\/documentation\/mapboxmaps\/tilestoreobserver\/onregionloadprogress(forid:progress:)","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStoreObserver":{"url":"\/documentation\/mapboxmaps\/tilestoreobserver","title":"TileStoreObserver","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreObserver","abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileStoreObserver","kind":"identifier"}],"navigatorTitle":[{"text":"TileStoreObserver","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"kind":"article","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","url":"\/documentation\/overview","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","kind":"symbol","title":"MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"title":"TileStore APIs","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","url":"\/documentation\/mapboxmaps\/tilestore-apis","abstract":[],"role":"collectionGroup","type":"topic","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadProgress":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgress","abstract":[{"text":"A tile region’s load progress includes counts","type":"text"},{"text":" ","type":"text"},{"text":"of the number of resources that have completed downloading","type":"text"},{"text":" ","type":"text"},{"text":"and the total number of resources that are required.","type":"text"}],"kind":"symbol","role":"symbol","title":"TileRegionLoadProgress","type":"topic","url":"\/documentation\/mapboxcommon\/tileregionloadprogress","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileRegionLoadProgress"}],"navigatorTitle":[{"kind":"identifier","text":"TileRegionLoadProgress"}]}},"variantOverrides":[{"patch":[{"value":"MBXTileRegionLoadProgress","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgress\/title"},{"value":[{"text":"MBXTileRegionLoadProgress","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgress\/fragments"},{"value":[{"kind":"identifier","text":"MBXTileRegionLoadProgress"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgress\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}