{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"requiredResourceCount","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt64","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStylePack\/requiredResourceCount"},"abstract":[{"type":"text","text":"The number of resources that are known to be required for this style package."}],"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePack"]]},"variants":[{"paths":["\/documentation\/mapboxmaps\/mbmstylepack\/requiredresourcecount"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/mbmstylepack\/requiredresourcecount"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"requiredResourceCount","modules":[{"name":"MapboxMaps"}],"navigatorTitle":[{"kind":"identifier","text":"requiredResourceCount"}],"symbolKind":"property","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"requiredResourceCount","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt64","preciseIdentifier":"s:s6UInt64V","kind":"typeIdentifier"}],"role":"symbol","externalID":"c:objc(cs)MBMStylePack(py)requiredResourceCount"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"url":"\/documentation\/mapboxmaps\/tilestore-apis","kind":"article","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","type":"topic","title":"TileStore APIs"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePack":{"url":"\/documentation\/mapboxmaps\/stylepack","title":"StylePack","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StylePack"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePack","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"style pack"},{"text":" represents a stored style package.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"StylePack","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMStylePack/requiredResourceCount":{"title":"requiredResourceCount","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"requiredResourceCount"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStylePack\/requiredResourceCount","abstract":[{"text":"The number of resources that are known to be required for this style package.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"requiredResourceCount","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt64","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V"}],"url":"\/documentation\/mapboxmaps\/mbmstylepack\/requiredresourcecount","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"requiredResourceCount","path":"\/metadata\/title","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"requiredResourceCount"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"uint64_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@uint64_t"},{"text":" ","kind":"text"},{"text":"requiredResourceCount","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"value":"MBMStylePack","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePack\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePack\/fragments","value":[{"text":"MBMStylePack","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMStylePack~1requiredResourceCount\/title","value":"requiredResourceCount","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"requiredResourceCount"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMStylePack~1requiredResourceCount\/fragments"}]}]}