{"metadata":{"modules":[{"name":"MapboxMaps"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"override"},{"kind":"text","text":"("},{"kind":"externalParam","text":"provider"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MBXLocationProvider","text":"LocationProvider"},{"text":" & ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps15HeadingProviderP","text":"HeadingProvider"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","role":"symbol","title":"override(provider:)","externalID":"s:10MapboxMaps15LocationManagerC8override8providerySo19MBXLocationProvider_AA07HeadingH0p_tF"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationManager"]]},"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/mapboxmaps\/locationmanager\/override(provider:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationManager\/override(provider:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"override","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"provider"},{"text":": any ","kind":"text"},{"text":"LocationProvider","preciseIdentifier":"c:objc(pl)MBXLocationProvider","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider","kind":"typeIdentifier"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps15HeadingProviderP","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingProvider","text":"HeadingProvider"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An object that provides both location and heading data, such as "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProvider","type":"reference","isActive":true},{"text":".","type":"text"}]}],"name":"provider"}]},{"content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"name":"Note","content":[{"type":"paragraph","inlineContent":[{"text":"On visionOS, the ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProvider","isActive":true,"type":"reference"},{"text":" doesn’t implement ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingProvider"},{"type":"text","text":"."},{"text":" ","type":"text"},{"text":"If you are using a custom instance of a location provider, override it using the ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationManager\/override(locationProvider:headingProvider:)-8xcsf","type":"reference","isActive":true},{"type":"text","text":" ."}]}],"style":"note","type":"aside"}],"kind":"content"}],"abstract":[{"type":"text","text":"Sets the custom provider that supply puck with the location and heading data."}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Location-APIs":{"url":"\/documentation\/mapboxmaps\/location-apis","type":"topic","kind":"article","role":"collectionGroup","title":"Location","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AppleLocationProvider":{"abstract":[{"text":"A location provider based on CoreLocation’s ","type":"text"},{"type":"codeVoice","code":"CLLocationManager"},{"type":"text","text":"."}],"type":"topic","title":"AppleLocationProvider","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProvider","navigatorTitle":[{"text":"AppleLocationProvider","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AppleLocationProvider","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/applelocationprovider"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationProvider":{"abstract":[{"type":"text","text":"Location provider that provides locations"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LocationProvider"}],"role":"symbol","type":"topic","title":"LocationProvider","kind":"symbol","url":"\/documentation\/mapboxcommon\/locationprovider","navigatorTitle":[{"text":"LocationProvider","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LocationManager/override(provider:)":{"url":"\/documentation\/mapboxmaps\/locationmanager\/override(provider:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationManager\/override(provider:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"override","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"provider"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MBXLocationProvider","text":"LocationProvider"},{"text":" & ","kind":"text"},{"text":"HeadingProvider","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps15HeadingProviderP"},{"kind":"text","text":")"}],"type":"topic","abstract":[{"type":"text","text":"Sets the custom provider that supply puck with the location and heading data."}],"kind":"symbol","role":"symbol","title":"override(provider:)"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","abstract":[],"type":"topic","kind":"article","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LocationManager/override(locationProvider:headingProvider:)-8xcsf":{"url":"\/documentation\/mapboxmaps\/locationmanager\/override(locationprovider:headingprovider:)-8xcsf","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationManager\/override(locationProvider:headingProvider:)-8xcsf","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"override"},{"kind":"text","text":"("},{"text":"locationProvider","kind":"externalParam"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","text":"LocationProvider","preciseIdentifier":"c:objc(pl)MBXLocationProvider"},{"kind":"text","text":", "},{"kind":"externalParam","text":"headingProvider"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps15HeadingProviderP","text":"HeadingProvider"},{"text":")?)","kind":"text"}],"type":"topic","abstract":[{"text":"Sets the custom providers that supply puck with the location data.","type":"text"}],"kind":"symbol","role":"symbol","title":"override(locationProvider:headingProvider:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"role":"collection","url":"\/documentation\/mapboxmaps","title":"MapboxMaps","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LocationManager":{"type":"topic","kind":"symbol","abstract":[{"text":"An object responsible for managing user location Puck.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"LocationManager","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/locationmanager","title":"LocationManager","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationManager","navigatorTitle":[{"text":"LocationManager","kind":"identifier"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeadingProvider":{"abstract":[{"type":"text","text":"Provides heading data to drive the location puck."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HeadingProvider","kind":"identifier"}],"role":"symbol","type":"topic","title":"HeadingProvider","kind":"symbol","url":"\/documentation\/mapboxmaps\/headingprovider","navigatorTitle":[{"kind":"identifier","text":"HeadingProvider"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingProvider"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/title","op":"replace","value":"MBXLocationProvider"},{"op":"replace","value":[{"kind":"identifier","text":"MBXLocationProvider"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/navigatorTitle","value":[{"kind":"identifier","text":"MBXLocationProvider"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}