{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpMethod\/get"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"get"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/httpmethod\/get"]},{"paths":["\/documentation\/mapboxcommon\/httpmethod\/get"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpMethod"]]},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"get"}],"modules":[{"name":"MapboxCommon"}],"navigatorTitle":[{"kind":"identifier","text":"MBXHttpMethodGet"}],"externalID":"c:@E@MBXHttpMethod@MBXHttpMethodGet","role":"symbol","symbolKind":"case","title":"HttpMethod.get","roleHeading":"Case"},"abstract":[{"text":"The GET method requests a representation of the specified resource. Requests using GET should only retrieve data.","type":"text"}],"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpMethod":{"role":"symbol","title":"HttpMethod","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"HttpMethod"}],"navigatorTitle":[{"text":"HttpMethod","kind":"identifier"}],"abstract":[{"type":"text","text":"HTTP defines a set of request methods to indicate the desired action to be performed for a given resource."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpMethod","url":"\/documentation\/mapboxcommon\/httpmethod","kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","abstract":[],"kind":"article","role":"collection","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","kind":"symbol","type":"topic","title":"MapboxCommon","url":"\/documentation\/mapboxcommon","role":"collection","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpMethod/get":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"get","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpMethod\/get","url":"\/documentation\/mapboxcommon\/httpmethod\/get","abstract":[{"text":"The GET method requests a representation of the specified resource. Requests using GET should only retrieve data.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBXHttpMethodGet"}],"role":"symbol","type":"topic","title":"HttpMethod.get"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","value":"MBXHttpMethodGet","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MBXHttpMethodGet","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"MBXHttpMethodGet","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"MBXHttpMethod","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpMethod\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpMethod\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXHttpMethod"}]},{"value":[{"text":"MBXHttpMethod","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpMethod\/navigatorTitle"},{"value":"MBXHttpMethodGet","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpMethod~1get\/title"},{"value":[{"kind":"identifier","text":"MBXHttpMethodGet"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpMethod~1get\/fragments","op":"replace"}]}]}