{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode"},"seeAlsoSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapView","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapInitOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapInitOptionsProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AttributionURLOpener","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ConstrainMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/NorthOrientation","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PresentationTransactionMode"],"title":"MapView","generated":true,"anchor":"MapView"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GlyphsRasterizationMode","kind":"identifier"}]}]}],"abstract":[{"type":"text","text":"Describes glyphs rasterization modes."}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-View"],["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs"]]},"variants":[{"paths":["\/documentation\/mapboxmaps\/glyphsrasterizationmode"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/glyphsrasterizationmode"]}],"sections":[],"topicSections":[{"anchor":"Enumeration-Cases","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode\/allGlyphsRasterizedLocally","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode\/ideographsRasterizedLocally","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode\/noGlyphsRasterizedLocally"],"title":"Enumeration Cases"},{"anchor":"Initializers","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode\/init(rawValue:)"],"title":"Initializers"},{"generated":true,"title":"Default Implementations","anchor":"Default-Implementations","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode\/Equatable-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode\/RawRepresentable-Implementations"]}],"kind":"symbol","relationshipsSections":[{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/s15BitwiseCopyableP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH","doc:\/\/com.mapbox.MapboxMaps\/SY","doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"],"title":"Conforms To"}],"metadata":{"title":"GlyphsRasterizationMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"GlyphsRasterizationMode","kind":"identifier"}],"externalID":"c:@E@MBMGlyphsRasterizationMode","role":"symbol","roleHeading":"Enumeration","symbolKind":"enum","modules":[{"name":"MapboxMaps"}],"navigatorTitle":[{"text":"GlyphsRasterizationMode","kind":"identifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GlyphsRasterizationMode/init(rawValue:)":{"abstract":[],"type":"topic","title":"init(rawValue:)","url":"\/documentation\/mapboxmaps\/glyphsrasterizationmode\/init(rawvalue:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode\/init(rawValue:)","role":"symbol","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GlyphsRasterizationMode/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode\/RawRepresentable-Implementations","url":"\/documentation\/mapboxmaps\/glyphsrasterizationmode\/rawrepresentable-implementations","kind":"article","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","title":"MapboxMaps","role":"collection","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapView":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"MapView"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapView","url":"\/documentation\/mapboxmaps\/mapview","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MapView","kind":"identifier"}],"role":"symbol","type":"topic","title":"MapView"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PresentationTransactionMode":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PresentationTransactionMode"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Determines if the underlying "},{"code":"CAMetalLayer","type":"codeVoice"},{"type":"text","text":" rendering output should synchronize with the Core Animation transactions."}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PresentationTransactionMode","title":"PresentationTransactionMode","navigatorTitle":[{"text":"PresentationTransactionMode","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/presentationtransactionmode"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GlyphsRasterizationMode/noGlyphsRasterizedLocally":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBMGlyphsRasterizationModeNoGlyphsRasterizedLocally"}],"type":"topic","title":"GlyphsRasterizationMode.noGlyphsRasterizedLocally","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode\/noGlyphsRasterizedLocally","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"noGlyphsRasterizedLocally","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/glyphsrasterizationmode\/noglyphsrasterizedlocally","abstract":[{"type":"text","text":"No glyphs are rasterized locally. All glyphs are loaded from the server."}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapInitOptionsProvider":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapInitOptionsProvider","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"text":"A protocol used to provide ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapInitOptions","isActive":true},{"type":"text","text":" when initializing a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapView"},{"text":" with a Storyboard or","type":"text"},{"type":"text","text":" "},{"text":"a nib.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapInitOptionsProvider","title":"MapInitOptionsProvider","navigatorTitle":[{"text":"MapInitOptionsProvider","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/mapinitoptionsprovider"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewportMode":{"navigatorTitle":[{"text":"ViewportMode","kind":"identifier"}],"title":"ViewportMode","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportMode","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ViewportMode","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Satisfies embedding platforms that requires the viewport coordinate systems to be set according to its standards."}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/viewportmode"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GlyphsRasterizationMode/ideographsRasterizedLocally":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode\/ideographsRasterizedLocally","abstract":[{"text":"Ideographs are rasterized locally, and they are not loaded from the server.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MBMGlyphsRasterizationModeIdeographsRasterizedLocally"}],"title":"GlyphsRasterizationMode.ideographsRasterizedLocally","kind":"symbol","url":"\/documentation\/mapboxmaps\/glyphsrasterizationmode\/ideographsrasterizedlocally","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ideographsRasterizedLocally"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article","role":"collection","abstract":[],"type":"topic","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AttributionURLOpener":{"abstract":[{"type":"text","text":"A protocol to open attribution URLs."}],"title":"AttributionURLOpener","url":"\/documentation\/mapboxmaps\/attributionurlopener","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"AttributionURLOpener","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AttributionURLOpener"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AttributionURLOpener","type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ConstrainMode":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ConstrainMode","role":"symbol","navigatorTitle":[{"text":"ConstrainMode","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxmaps\/constrainmode","title":"ConstrainMode","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ConstrainMode","kind":"identifier"}],"abstract":[{"text":"Describes whether to constrain the map in both axes or only vertically e.g. while panning.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/NorthOrientation":{"abstract":[{"type":"text","text":"Describes the map orientation."}],"title":"NorthOrientation","url":"\/documentation\/mapboxmaps\/northorientation","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"NorthOrientation","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NorthOrientation"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/NorthOrientation","type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/SY":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapOptions":{"kind":"symbol","abstract":[{"type":"text","text":"Describes the map option values."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapOptions","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapOptions"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"MapOptions","kind":"identifier"}],"title":"MapOptions","url":"\/documentation\/mapboxmaps\/mapoptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map-View":{"title":"MapView","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-View","role":"collectionGroup","abstract":[],"kind":"article","url":"\/documentation\/mapboxmaps\/map-view"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GlyphsRasterizationMode/allGlyphsRasterizedLocally":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode\/allGlyphsRasterizedLocally","abstract":[{"type":"text","text":"All glyphs are rasterized locally. No glyphs are loaded from the server."}],"navigatorTitle":[{"kind":"identifier","text":"MBMGlyphsRasterizationModeAllGlyphsRasterizedLocally"}],"title":"GlyphsRasterizationMode.allGlyphsRasterizedLocally","kind":"symbol","url":"\/documentation\/mapboxmaps\/glyphsrasterizationmode\/allglyphsrasterizedlocally","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"allGlyphsRasterizedLocally"}]},"doc://com.mapbox.MapboxMaps/s15BitwiseCopyableP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s15BitwiseCopyableP","title":"Swift.BitwiseCopyable","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GlyphsRasterizationMode":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode","type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/glyphsrasterizationmode","title":"GlyphsRasterizationMode","abstract":[{"text":"Describes glyphs rasterization modes.","type":"text"}],"navigatorTitle":[{"text":"GlyphsRasterizationMode","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"GlyphsRasterizationMode","kind":"identifier"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapInitOptions":{"abstract":[{"text":"Options used when initializing ","type":"text"},{"type":"codeVoice","code":"MapView"},{"text":".","type":"text"}],"title":"MapInitOptions","url":"\/documentation\/mapboxmaps\/mapinitoptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MapInitOptions","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"MapInitOptions","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapInitOptions","type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GlyphsRasterizationOptions":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationOptions","navigatorTitle":[{"text":"GlyphsRasterizationOptions","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/glyphsrasterizationoptions","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GlyphsRasterizationOptions","kind":"identifier"}],"title":"GlyphsRasterizationOptions","abstract":[{"type":"text","text":"Describes the glyphs rasterization option values."}]},"doc://com.mapbox.MapboxMaps/SH":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/s8SendableP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/SQ":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"type":"topic","url":"\/documentation\/mapboxmaps\/mapboxmap-apis","abstract":[],"role":"collectionGroup","title":"MapboxMap","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GlyphsRasterizationMode/Equatable-Implementations":{"role":"collectionGroup","type":"topic","abstract":[],"title":"Equatable Implementations","url":"\/documentation\/mapboxmaps\/glyphsrasterizationmode\/equatable-implementations","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode\/Equatable-Implementations","kind":"article"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"MBMGlyphsRasterizationMode"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBMGlyphsRasterizationMode"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"MBMGlyphsRasterizationMode","kind":"identifier"}]},{"value":[{"anchor":"Enumeration-Cases","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode\/allGlyphsRasterizedLocally","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode\/ideographsRasterizedLocally","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode\/noGlyphsRasterizedLocally"],"title":"Enumeration Cases"}],"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"op":"replace","path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ConstrainMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/NorthOrientation","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportMode"],"title":"MapView","generated":true,"anchor":"MapView"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBMGlyphsRasterizationMode","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode~1noGlyphsRasterizedLocally\/title","value":"MBMGlyphsRasterizationModeNoGlyphsRasterizedLocally","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode~1noGlyphsRasterizedLocally\/fragments","value":[{"kind":"identifier","text":"MBMGlyphsRasterizationModeNoGlyphsRasterizedLocally"}],"op":"replace"},{"value":"MBMViewportMode","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewportMode\/title"},{"value":[{"text":"MBMViewportMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewportMode\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewportMode\/navigatorTitle","op":"replace","value":[{"text":"MBMViewportMode","kind":"identifier"}]},{"value":"MBMGlyphsRasterizationModeIdeographsRasterizedLocally","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode~1ideographsRasterizedLocally\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode~1ideographsRasterizedLocally\/fragments","value":[{"text":"MBMGlyphsRasterizationModeIdeographsRasterizedLocally","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ConstrainMode\/title","op":"replace","value":"MBMConstrainMode"},{"value":[{"text":"MBMConstrainMode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ConstrainMode\/fragments","op":"replace"},{"value":[{"text":"MBMConstrainMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ConstrainMode\/navigatorTitle"},{"op":"replace","value":"MBMNorthOrientation","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1NorthOrientation\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1NorthOrientation\/fragments","value":[{"text":"MBMNorthOrientation","kind":"identifier"}]},{"value":[{"text":"MBMNorthOrientation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1NorthOrientation\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapOptions\/title","op":"replace","value":"MBMMapOptions"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapOptions\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMMapOptions"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapOptions\/navigatorTitle","op":"replace","value":[{"text":"MBMMapOptions","kind":"identifier"}]},{"op":"replace","value":"MBMGlyphsRasterizationModeAllGlyphsRasterizedLocally","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode~1allGlyphsRasterizedLocally\/title"},{"value":[{"kind":"identifier","text":"MBMGlyphsRasterizationModeAllGlyphsRasterizedLocally"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode~1allGlyphsRasterizedLocally\/fragments","op":"replace"},{"op":"replace","value":"MBMGlyphsRasterizationMode","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/fragments","value":[{"kind":"identifier","text":"MBMGlyphsRasterizationMode"}],"op":"replace"},{"value":[{"kind":"identifier","text":"MBMGlyphsRasterizationMode"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationOptions\/title","value":"MBMGlyphsRasterizationOptions"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationOptions\/fragments","value":[{"text":"MBMGlyphsRasterizationOptions","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationOptions\/navigatorTitle","op":"replace","value":[{"text":"MBMGlyphsRasterizationOptions","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}