{"topicSections":[{"anchor":"Sources","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Source","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceInfo","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSourceData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterArraySource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/VectorSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PromoteId","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Scheme","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Encoding","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatusChangedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatus","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileFunctionCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetSize"],"title":"Sources"}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"]]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"article","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources"},"seeAlsoSections":[{"generated":true,"anchor":"Styling","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Style","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer-Property-Values","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Expressions"],"title":"Styling"}],"metadata":{"roleHeading":"API Collection","role":"collectionGroup","modules":[{"name":"MapboxMaps"}],"title":"Sources"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceClientType":{"navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceClientType"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType","type":"topic","url":"\/documentation\/mapboxmaps\/customrastersourceclienttype","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CustomRasterSourceClientType"}],"title":"CustomRasterSourceClientType","abstract":[],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/VectorSource":{"url":"\/documentation\/mapboxmaps\/vectorsource","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/VectorSource","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"VectorSource"}],"type":"topic","role":"symbol","title":"VectorSource","navigatorTitle":[{"kind":"identifier","text":"VectorSource"}],"abstract":[{"type":"text","text":"A vector tile source."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterArraySource":{"url":"\/documentation\/mapboxmaps\/rasterarraysource","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterArraySource","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RasterArraySource"}],"type":"topic","role":"symbol","title":"RasterArraySource","navigatorTitle":[{"text":"RasterArraySource","kind":"identifier"}],"tags":[{"type":"spi","text":"SPI"}],"abstract":[{"text":"A raster array source","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileFunctionCallback":{"url":"\/documentation\/mapboxmaps\/tilefunctioncallback","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileFunctionCallback","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"TileFunctionCallback","kind":"identifier"}],"type":"topic","role":"symbol","title":"TileFunctionCallback","navigatorTitle":[{"kind":"identifier","text":"TileFunctionCallback"}],"abstract":[{"type":"text","text":"Callback to do various operations for tile."},{"text":" ","type":"text"},{"type":"text","text":"For example, fetching a tile or cancelling a tile request."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GeoJSONSource":{"url":"\/documentation\/mapboxmaps\/geojsonsource","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSource","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GeoJSONSource"}],"type":"topic","role":"symbol","title":"GeoJSONSource","navigatorTitle":[{"kind":"identifier","text":"GeoJSONSource"}],"abstract":[{"text":"A GeoJSON data source.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceInfo":{"navigatorTitle":[{"kind":"identifier","text":"SourceInfo"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceInfo","type":"topic","url":"\/documentation\/mapboxmaps\/sourceinfo","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"SourceInfo","kind":"identifier"}],"title":"SourceInfo","abstract":[{"type":"text","text":"Information about a Source"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Scheme":{"url":"\/documentation\/mapboxmaps\/scheme","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Scheme","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Scheme"}],"type":"topic","role":"symbol","title":"Scheme","navigatorTitle":[{"kind":"identifier","text":"Scheme"}],"abstract":[{"type":"text","text":"Influences the y direction of the tile coordinates. The global-mercator (aka Spherical Mercator) profile is assumed."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","title":"MapboxMaps","role":"collection","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileStatusChangedCallback":{"navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceTileStatusChangedCallback"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatusChangedCallback","type":"topic","url":"\/documentation\/mapboxmaps\/customrastersourcetilestatuschangedcallback","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CustomRasterSourceTileStatusChangedCallback"}],"title":"CustomRasterSourceTileStatusChangedCallback","abstract":[{"text":"Callback for changing a CustomRasterSource tile status.","type":"text"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Encoding":{"navigatorTitle":[{"kind":"identifier","text":"Encoding"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Encoding","type":"topic","url":"\/documentation\/mapboxmaps\/encoding","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Encoding"}],"title":"Encoding","abstract":[{"type":"text","text":"The encoding used by this source. Mapbox Terrain RGB is used by default"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSource":{"url":"\/documentation\/mapboxmaps\/customrastersource","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSource","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomRasterSource"}],"type":"topic","role":"symbol","title":"CustomRasterSource","navigatorTitle":[{"kind":"identifier","text":"CustomRasterSource"}],"tags":[{"text":"SPI","type":"spi"}],"abstract":[{"type":"text","text":"Describes a Custom Raster Source to be used in the style."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileStatus":{"url":"\/documentation\/mapboxmaps\/customrastersourcetilestatus","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomRasterSourceTileStatus"}],"type":"topic","role":"symbol","title":"CustomRasterSourceTileStatus","navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceTileStatus"}],"abstract":[{"text":"CustomRasterSource tile status.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layers":{"title":"Layers","abstract":[],"url":"\/documentation\/mapboxmaps\/layers","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers","role":"collectionGroup","kind":"article","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Source":{"navigatorTitle":[{"kind":"identifier","text":"Source"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Source","type":"topic","url":"\/documentation\/mapboxmaps\/source","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Source"}],"title":"Source","abstract":[],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileData":{"url":"\/documentation\/mapboxmaps\/customrastersourcetiledata","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileData","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CustomRasterSourceTileData"}],"type":"topic","role":"symbol","title":"CustomRasterSourceTileData","navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceTileData"}],"abstract":[{"type":"text","text":"Data for a specific CustomRasterSource tile."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceType":{"abstract":[{"type":"text","text":"Struct of supported Source Types"},{"text":" ","type":"text"},{"text":"Docs : https:\/\/docs.mapbox.com\/mapbox-gl-js\/style-spec\/sources\/","type":"text"}],"url":"\/documentation\/mapboxmaps\/sourcetype","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"SourceType","kind":"identifier"}],"title":"SourceType","type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceType","role":"symbol","navigatorTitle":[{"text":"SourceType","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ImageSource":{"navigatorTitle":[{"kind":"identifier","text":"ImageSource"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageSource","type":"topic","url":"\/documentation\/mapboxmaps\/imagesource","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ImageSource"}],"title":"ImageSource","abstract":[{"type":"text","text":"An image data source."}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layer-Property-Values":{"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer-Property-Values","type":"topic","url":"\/documentation\/mapboxmaps\/layer-property-values","role":"collectionGroup","title":"Layer Property Values","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudgetSize":{"url":"\/documentation\/mapboxmaps\/tilecachebudgetsize","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetSize","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TileCacheBudgetSize"}],"type":"topic","role":"symbol","title":"TileCacheBudgetSize","navigatorTitle":[{"kind":"identifier","text":"TileCacheBudgetSize"}],"abstract":[{"text":"Defines a TileCacheBudgetSize, which can be set as either a megabyte or tile count limit.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Whenever tile cache goes over the defined limit"},{"type":"text","text":" "},{"type":"text","text":"the least recently used tile will be evicted from the in-memory cache"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileRenderer":{"url":"\/documentation\/mapboxmaps\/customrastersourcetilerenderer","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomRasterSourceTileRenderer"}],"type":"topic","role":"symbol","title":"CustomRasterSourceTileRenderer","navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceTileRenderer"}],"abstract":[{"type":"text","text":"Interface for the direct rendering into the custom raster tiles."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PromoteId":{"navigatorTitle":[{"kind":"identifier","text":"PromoteId"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PromoteId","type":"topic","url":"\/documentation\/mapboxmaps\/promoteid","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PromoteId"}],"title":"PromoteId","abstract":[],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterSource":{"navigatorTitle":[{"kind":"identifier","text":"RasterSource"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterSource","type":"topic","url":"\/documentation\/mapboxmaps\/rastersource","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"RasterSource"}],"title":"RasterSource","abstract":[{"type":"text","text":"A raster tile source."}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Style":{"kind":"article","type":"topic","url":"\/documentation\/mapboxmaps\/style","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Style","role":"collectionGroup","title":"Style"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomGeometrySource":{"navigatorTitle":[{"kind":"identifier","text":"CustomGeometrySource"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySource","type":"topic","url":"\/documentation\/mapboxmaps\/customgeometrysource","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomGeometrySource"}],"title":"CustomGeometrySource","abstract":[{"type":"text","text":"Describes a Custom Geometry Source to be used in the style"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceClient":{"url":"\/documentation\/mapboxmaps\/customrastersourceclient","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"CustomRasterSourceClient","kind":"identifier"}],"type":"topic","role":"symbol","title":"CustomRasterSourceClient","navigatorTitle":[{"text":"CustomRasterSourceClient","kind":"identifier"}],"abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceOptions":{"url":"\/documentation\/mapboxmaps\/customrastersourceoptions","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomRasterSourceOptions"}],"type":"topic","role":"symbol","title":"CustomRasterSourceOptions","navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceOptions"}],"abstract":[{"type":"text","text":"Options for custom raster source."}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article","role":"collection","abstract":[],"type":"topic","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterDemSource":{"navigatorTitle":[{"text":"RasterDemSource","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource","type":"topic","url":"\/documentation\/mapboxmaps\/rasterdemsource","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"RasterDemSource","kind":"identifier"}],"title":"RasterDemSource","abstract":[{"text":"A RGB-encoded raster DEM source","type":"text"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Expressions":{"url":"\/documentation\/mapboxmaps\/expressions","role":"collectionGroup","kind":"article","type":"topic","title":"Expressions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Expressions","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GeoJSONSourceData":{"title":"GeoJSONSourceData","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"GeoJSONSourceData","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GeoJSONSourceData"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSourceData","url":"\/documentation\/mapboxmaps\/geojsonsourcedata","abstract":[{"type":"text","text":"Captures potential values of the "},{"code":"data","type":"codeVoice"},{"text":" property of a GeoJSONSource.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomGeometrySourceOptions":{"navigatorTitle":[{"kind":"identifier","text":"CustomGeometrySourceOptions"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions","type":"topic","url":"\/documentation\/mapboxmaps\/customgeometrysourceoptions","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomGeometrySourceOptions"}],"title":"CustomGeometrySourceOptions","abstract":[{"type":"text","text":"Options for custom geometry source."}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"MBMCustomRasterSourceClientType","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType\/fragments","value":[{"kind":"identifier","text":"MBMCustomRasterSourceClientType"}]},{"value":[{"kind":"identifier","text":"MBMCustomRasterSourceClientType"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType\/navigatorTitle","op":"replace"},{"value":"MBMTileFunctionCallback","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileFunctionCallback\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileFunctionCallback\/fragments","value":[{"text":"MBMTileFunctionCallback","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileFunctionCallback\/navigatorTitle","value":[{"text":"MBMTileFunctionCallback","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatusChangedCallback\/title","value":"MBMCustomRasterSourceTileStatusChangedCallback","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatusChangedCallback\/fragments","value":[{"text":"MBMCustomRasterSourceTileStatusChangedCallback","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatusChangedCallback\/navigatorTitle","op":"replace","value":[{"text":"MBMCustomRasterSourceTileStatusChangedCallback","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatus\/title","op":"replace","value":"MBMCustomRasterSourceTileStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatus\/fragments","value":[{"text":"MBMCustomRasterSourceTileStatus","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileStatus"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatus\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileData\/title","value":"MBMCustomRasterSourceTileData","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileData\/fragments","value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileData"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileData\/navigatorTitle","value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileData"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer\/title","op":"replace","value":"MBMCustomRasterSourceTileRenderer"},{"op":"replace","value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileRenderer"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer\/fragments"},{"value":[{"text":"MBMCustomRasterSourceTileRenderer","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer\/navigatorTitle","op":"replace"},{"op":"replace","value":"MBMCustomRasterSourceClient","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient\/fragments","value":[{"text":"MBMCustomRasterSourceClient","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"MBMCustomRasterSourceClient"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/title","value":"MBMCustomRasterSourceOptions","op":"replace"},{"value":[{"text":"MBMCustomRasterSourceOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/navigatorTitle","op":"replace","value":[{"text":"MBMCustomRasterSourceOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions\/title","value":"MBMCustomGeometrySourceOptions","op":"replace"},{"value":[{"text":"MBMCustomGeometrySourceOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions\/navigatorTitle","value":[{"text":"MBMCustomGeometrySourceOptions","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}