{"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"addLocationObserver","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"text":": any ","kind":"text"},{"text":"LocationObserver","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MBXLocationObserver"},{"kind":"text","text":")"}],"symbolKind":"method","extendedModule":"MapboxMaps","externalID":"s:10MapboxMaps21AppleLocationProviderC03addD8Observer3forySo011MBXLocationG0_p_tF","modules":[{"name":"MapboxMaps"}],"role":"symbol","roleHeading":"Instance Method","title":"addLocationObserver(for:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addLocationObserver","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"observer","kind":"internalParam"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:objc(pl)MBXLocationObserver","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationObserver","text":"LocationObserver"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"inlineContent":[{"type":"text","text":"The observer will receive a cached value upon subscription."}],"type":"paragraph"},{"name":"Note","type":"aside","style":"note","content":[{"inlineContent":[{"type":"text","text":"When the first observer is added, the underlying "},{"type":"codeVoice","code":"CLLocationManager"},{"text":" instance will","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"ask for permissions (if needed) and start to produce the location updates."}],"type":"paragraph"}]}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProvider\/addLocationObserver(for:)","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Adds a location observer."}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProvider\/LocationProvider-Implementations"]]},"variants":[{"paths":["\/documentation\/mapboxmaps\/applelocationprovider\/addlocationobserver(for:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AppleLocationProvider/LocationProvider-Implementations":{"kind":"article","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProvider\/LocationProvider-Implementations","abstract":[],"type":"topic","url":"\/documentation\/mapboxmaps\/applelocationprovider\/locationprovider-implementations","title":"LocationProvider Implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Location-APIs":{"url":"\/documentation\/mapboxmaps\/location-apis","role":"collectionGroup","abstract":[],"kind":"article","type":"topic","title":"Location","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","role":"collection","title":"MapboxMaps","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AppleLocationProvider/addLocationObserver(for:)":{"abstract":[{"text":"Adds a location observer.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProvider\/addLocationObserver(for:)","url":"\/documentation\/mapboxmaps\/applelocationprovider\/addlocationobserver(for:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"addLocationObserver","kind":"identifier"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"kind":"text","text":": any "},{"text":"LocationObserver","preciseIdentifier":"c:objc(pl)MBXLocationObserver","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","title":"addLocationObserver(for:)"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","kind":"article","abstract":[],"title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AppleLocationProvider":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AppleLocationProvider"}],"abstract":[{"type":"text","text":"A location provider based on CoreLocation’s "},{"type":"codeVoice","code":"CLLocationManager"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AppleLocationProvider"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProvider","url":"\/documentation\/mapboxmaps\/applelocationprovider","title":"AppleLocationProvider"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationObserver":{"title":"LocationObserver","navigatorTitle":[{"text":"LocationObserver","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Observer for getting updates from a LocationProvider.","type":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/mapboxcommon\/locationobserver","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationObserver"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationObserver"}},"variantOverrides":[{"patch":[{"value":"MBXLocationObserver","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MBXLocationObserver"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBXLocationObserver"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}