{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode\/notAvailable"},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"notAvailable","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode"]]},"metadata":{"roleHeading":"Case","modules":[{"name":"MapboxCommon"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"notAvailable"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBXLocationErrorCodeNotAvailable"}],"title":"LocationErrorCode.notAvailable","externalID":"c:@E@MBXLocationErrorCode@MBXLocationErrorCodeNotAvailable","symbolKind":"case"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"The subject of the request is not available."}],"sections":[],"variants":[{"paths":["\/documentation\/mapboxcommon\/locationerrorcode\/notavailable"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/locationerrorcode\/notavailable"]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Location-APIs":{"abstract":[],"role":"collectionGroup","title":"Location","url":"\/documentation\/mapboxmaps\/location-apis","kind":"article","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","url":"\/documentation\/mapboxmaps","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"title":"MapboxMaps","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationErrorCode/notAvailable":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"notAvailable","kind":"identifier"}],"abstract":[{"type":"text","text":"The subject of the request is not available."}],"url":"\/documentation\/mapboxcommon\/locationerrorcode\/notavailable","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MBXLocationErrorCodeNotAvailable"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode\/notAvailable","title":"LocationErrorCode.notAvailable","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationErrorCode":{"abstract":[{"type":"text","text":"Codes of location errors."}],"role":"symbol","title":"LocationErrorCode","url":"\/documentation\/mapboxcommon\/locationerrorcode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocationErrorCode"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"LocationErrorCode","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","abstract":[],"type":"topic","kind":"article","title":"MapboxMaps Documentation","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"MBXLocationErrorCodeNotAvailable","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","value":[{"text":"MBXLocationErrorCodeNotAvailable","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"MBXLocationErrorCodeNotAvailable","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MBXLocationErrorCodeNotAvailable","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode~1notAvailable\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MBXLocationErrorCodeNotAvailable"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode~1notAvailable\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/title","value":"MBXLocationErrorCode","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/fragments","value":[{"text":"MBXLocationErrorCode","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"MBXLocationErrorCode"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/navigatorTitle"}]}]}