{"variants":[{"paths":["\/documentation\/mapboxcommon\/locationerrorcode\/notsupported"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/locationerrorcode\/notsupported"]}],"abstract":[{"type":"text","text":"Requested feature is not implemented or no supported by the device."}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode"]]},"sections":[],"metadata":{"title":"LocationErrorCode.notSupported","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"notSupported","kind":"identifier"}],"role":"symbol","roleHeading":"Case","externalID":"c:@E@MBXLocationErrorCode@MBXLocationErrorCodeNotSupported","symbolKind":"case","modules":[{"name":"MapboxCommon"}],"navigatorTitle":[{"text":"MBXLocationErrorCodeNotSupported","kind":"identifier"}]},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode\/notSupported","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"notSupported","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationErrorCode":{"role":"symbol","title":"LocationErrorCode","kind":"symbol","type":"topic","url":"\/documentation\/mapboxcommon\/locationerrorcode","abstract":[{"text":"Codes of location errors.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"LocationErrorCode","kind":"identifier"}],"navigatorTitle":[{"text":"LocationErrorCode","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","kind":"article","abstract":[],"title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Location-APIs":{"url":"\/documentation\/mapboxmaps\/location-apis","role":"collectionGroup","abstract":[],"kind":"article","type":"topic","title":"Location","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","role":"collection","title":"MapboxMaps","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationErrorCode/notSupported":{"kind":"symbol","url":"\/documentation\/mapboxcommon\/locationerrorcode\/notsupported","type":"topic","abstract":[{"text":"Requested feature is not implemented or no supported by the device.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBXLocationErrorCodeNotSupported"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notSupported","kind":"identifier"}],"title":"LocationErrorCode.notSupported","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode\/notSupported"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"MBXLocationErrorCodeNotSupported","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MBXLocationErrorCodeNotSupported","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"MBXLocationErrorCodeNotSupported","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MBXLocationErrorCode","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/fragments","value":[{"text":"MBXLocationErrorCode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBXLocationErrorCode"}]},{"op":"replace","value":"MBXLocationErrorCodeNotSupported","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode~1notSupported\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode~1notSupported\/fragments","value":[{"kind":"identifier","text":"MBXLocationErrorCodeNotSupported"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}