{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStylePackLoadProgress\/completedResourceSize"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"completedResourceSize","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s6UInt64V","kind":"typeIdentifier","text":"UInt64"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"The cumulative size, in bytes, of all resources that are ready for offline access."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/mbmstylepackloadprogress\/completedresourcesize"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/mbmstylepackloadprogress\/completedresourcesize"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"title":"completedResourceSize","modules":[{"name":"MapboxMaps"}],"navigatorTitle":[{"kind":"identifier","text":"completedResourceSize"}],"roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"completedResourceSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt64","preciseIdentifier":"s:s6UInt64V","kind":"typeIdentifier"}],"role":"symbol","externalID":"c:objc(cs)MBMStylePackLoadProgress(py)completedResourceSize"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadProgress"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePackLoadProgress":{"role":"symbol","abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"style pack load"},{"type":"text","text":" progress includes information about"},{"type":"text","text":" "},{"type":"text","text":"the number of resources that have completed downloading"},{"type":"text","text":" "},{"type":"text","text":"and the total number of resources that are required."}],"kind":"symbol","navigatorTitle":[{"text":"StylePackLoadProgress","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadProgress","url":"\/documentation\/mapboxmaps\/stylepackloadprogress","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StylePackLoadProgress","kind":"identifier"}],"title":"StylePackLoadProgress"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"url":"\/documentation\/mapboxmaps\/tilestore-apis","kind":"article","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","type":"topic","title":"TileStore APIs"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMStylePackLoadProgress/completedResourceSize":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/mbmstylepackloadprogress\/completedresourcesize","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStylePackLoadProgress\/completedResourceSize","abstract":[{"text":"The cumulative size, in bytes, of all resources that are ready for offline access.","type":"text"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completedResourceSize"},{"text":": ","kind":"text"},{"text":"UInt64","preciseIdentifier":"s:s6UInt64V","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"completedResourceSize"}],"title":"completedResourceSize"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"completedResourceSize"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"completedResourceSize"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@uint64_t","text":"uint64_t","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completedResourceSize"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadProgress\/title","value":"MBMStylePackLoadProgress"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadProgress\/fragments","value":[{"text":"MBMStylePackLoadProgress","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMStylePackLoadProgress~1completedResourceSize\/title","value":"completedResourceSize"},{"op":"replace","value":[{"kind":"identifier","text":"completedResourceSize"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMStylePackLoadProgress~1completedResourceSize\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}