{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"erroredResourceCount","kind":"identifier"},{"kind":"text","text":": "},{"text":"UInt64","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"abstract":[{"text":"The number of resources that have failed to download due to an error.","type":"text"}],"variants":[{"paths":["\/documentation\/mapboxmaps\/mbmstylepackloadprogress\/erroredresourcecount"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/mbmstylepackloadprogress\/erroredresourcecount"]}],"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStylePackLoadProgress\/erroredResourceCount"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadProgress"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"erroredResourceCount","modules":[{"name":"MapboxMaps"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"erroredResourceCount","kind":"identifier"}],"externalID":"c:objc(cs)MBMStylePackLoadProgress(py)erroredResourceCount","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"erroredResourceCount","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V","text":"UInt64"}],"role":"symbol","symbolKind":"property"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMStylePackLoadProgress/erroredResourceCount":{"title":"erroredResourceCount","navigatorTitle":[{"kind":"identifier","text":"erroredResourceCount"}],"url":"\/documentation\/mapboxmaps\/mbmstylepackloadprogress\/erroredresourcecount","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"erroredResourceCount","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s6UInt64V","text":"UInt64","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStylePackLoadProgress\/erroredResourceCount","role":"symbol","abstract":[{"type":"text","text":"The number of resources that have failed to download due to an error."}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePackLoadProgress":{"role":"symbol","abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"style pack load"},{"type":"text","text":" progress includes information about"},{"type":"text","text":" "},{"type":"text","text":"the number of resources that have completed downloading"},{"type":"text","text":" "},{"type":"text","text":"and the total number of resources that are required."}],"kind":"symbol","navigatorTitle":[{"text":"StylePackLoadProgress","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadProgress","url":"\/documentation\/mapboxmaps\/stylepackloadprogress","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StylePackLoadProgress","kind":"identifier"}],"title":"StylePackLoadProgress"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"url":"\/documentation\/mapboxmaps\/tilestore-apis","kind":"article","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","type":"topic","title":"TileStore APIs"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"erroredResourceCount"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"erroredResourceCount","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"uint64_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@uint64_t"},{"kind":"text","text":" "},{"text":"erroredResourceCount","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"erroredResourceCount","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMStylePackLoadProgress~1erroredResourceCount\/title"},{"value":[{"text":"erroredResourceCount","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMStylePackLoadProgress~1erroredResourceCount\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadProgress\/title","value":"MBMStylePackLoadProgress","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadProgress\/fragments","value":[{"text":"MBMStylePackLoadProgress","kind":"identifier"}]}]}]}