{"abstract":[{"type":"text","text":"The engine should try loading a resource from the cache."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cache"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/requestloadingmethodtype\/cache"]},{"paths":["\/documentation\/mapboxmaps\/requestloadingmethodtype\/cache"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestLoadingMethodType"]]},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestLoadingMethodType\/cache","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:@E@MBMRequestLoadingMethodType@MBMRequestLoadingMethodTypeCache","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cache"}],"title":"RequestLoadingMethodType.cache","navigatorTitle":[{"text":"MBMRequestLoadingMethodTypeCache","kind":"identifier"}],"roleHeading":"Case","modules":[{"name":"MapboxMaps"}],"symbolKind":"case"},"kind":"symbol","references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"type":"topic","abstract":[{"type":"text","text":"The simplified diagram of the events emitted by the map is displayed below."}],"role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","kind":"article","url":"\/documentation\/mapboxmaps\/events","title":"Map events"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","kind":"symbol","title":"MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","url":"\/documentation\/overview","abstract":[],"kind":"article","title":"MapboxMaps Documentation","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestLoadingMethodType/cache":{"title":"RequestLoadingMethodType.cache","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"cache","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestLoadingMethodType\/cache","role":"symbol","navigatorTitle":[{"text":"MBMRequestLoadingMethodTypeCache","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/requestloadingmethodtype\/cache","abstract":[{"text":"The engine should try loading a resource from the cache.","type":"text"}],"kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestLoadingMethodType":{"title":"RequestLoadingMethodType","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestLoadingMethodType","url":"\/documentation\/mapboxmaps\/requestloadingmethodtype","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"RequestLoadingMethodType","kind":"identifier"}],"abstract":[{"type":"text","text":"The enumeration defines the method used to make a resource request."}],"navigatorTitle":[{"text":"RequestLoadingMethodType","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"MBMRequestLoadingMethodTypeCache","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"MBMRequestLoadingMethodTypeCache","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"MBMRequestLoadingMethodTypeCache"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestLoadingMethodType~1cache\/title","op":"replace","value":"MBMRequestLoadingMethodTypeCache"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestLoadingMethodType~1cache\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMRequestLoadingMethodTypeCache"}]},{"op":"replace","value":"MBMRequestLoadingMethodType","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestLoadingMethodType\/title"},{"value":[{"text":"MBMRequestLoadingMethodType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestLoadingMethodType\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestLoadingMethodType\/navigatorTitle","value":[{"kind":"identifier","text":"MBMRequestLoadingMethodType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}