{"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/requestloadingmethodtype\/hashvalue"]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestLoadingMethodType\/hashValue","interfaceLanguage":"swift"},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"modules":[{"relatedModules":["Swift"],"name":"MapboxMaps"}],"symbolKind":"property","conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}],"availabilityPrefix":[{"type":"text","text":"Available when"}]},"extendedModule":"Swift","role":"symbol","roleHeading":"Instance Property","externalID":"s:SYsSHRzSH8RawValueSYRpzrlE04hashB0Sivp::SYNTHESIZED::c:@E@MBMRequestLoadingMethodType","title":"hashValue"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.hashValue"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestLoadingMethodType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestLoadingMethodType\/RawRepresentable-Implementations"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestLoadingMethodType/RawRepresentable-Implementations":{"role":"collectionGroup","abstract":[],"url":"\/documentation\/mapboxmaps\/requestloadingmethodtype\/rawrepresentable-implementations","title":"RawRepresentable Implementations","type":"topic","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestLoadingMethodType\/RawRepresentable-Implementations"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article","title":"MapboxMaps Documentation","abstract":[],"url":"\/documentation\/overview","role":"collection","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestLoadingMethodType":{"role":"symbol","abstract":[{"text":"The enumeration defines the method used to make a resource request.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"RequestLoadingMethodType"}],"navigatorTitle":[{"text":"RequestLoadingMethodType","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/requestloadingmethodtype","title":"RequestLoadingMethodType","type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestLoadingMethodType"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","title":"MapboxMaps","type":"topic","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestLoadingMethodType/hashValue":{"conformance":{"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":"."}],"availabilityPrefix":[{"text":"Available when","type":"text"}]},"abstract":[],"title":"hashValue","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestLoadingMethodType\/hashValue","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"url":"\/documentation\/mapboxmaps\/requestloadingmethodtype\/hashvalue","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"type":"topic","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","url":"\/documentation\/mapboxmaps\/events","title":"Map events","kind":"article","abstract":[{"type":"text","text":"The simplified diagram of the events emitted by the map is displayed below."}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestLoadingMethodType\/title","op":"replace","value":"MBMRequestLoadingMethodType"},{"op":"replace","value":[{"text":"MBMRequestLoadingMethodType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestLoadingMethodType\/fragments"},{"value":[{"text":"MBMRequestLoadingMethodType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestLoadingMethodType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}