{"kind":"symbol","sections":[],"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"init","title":"init(rawValue:)","modules":[{"name":"MapboxMaps"}],"externalID":"s:So27MBMRequestLoadingMethodTypeV8rawValueABSgSi_tcfc","role":"symbol","roleHeading":"Initializer"},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestLoadingMethodType\/init(rawValue:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/requestloadingmethodtype\/init(rawvalue:)"]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestLoadingMethodType"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","url":"\/documentation\/mapboxmaps","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"title":"MapboxMaps","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestLoadingMethodType/init(rawValue:)":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestLoadingMethodType\/init(rawValue:)","title":"init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}],"abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/requestloadingmethodtype\/init(rawvalue:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"url":"\/documentation\/mapboxmaps\/events","abstract":[{"type":"text","text":"The simplified diagram of the events emitted by the map is displayed below."}],"type":"topic","kind":"article","title":"Map events","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestLoadingMethodType":{"type":"topic","url":"\/documentation\/mapboxmaps\/requestloadingmethodtype","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"RequestLoadingMethodType"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestLoadingMethodType","abstract":[{"type":"text","text":"The enumeration defines the method used to make a resource request."}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"RequestLoadingMethodType","kind":"identifier"}],"title":"RequestLoadingMethodType","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","abstract":[],"type":"topic","kind":"article","title":"MapboxMaps Documentation","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestLoadingMethodType\/title","value":"MBMRequestLoadingMethodType","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestLoadingMethodType\/fragments","op":"replace","value":[{"text":"MBMRequestLoadingMethodType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestLoadingMethodType\/navigatorTitle","value":[{"text":"MBMRequestLoadingMethodType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}