{"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestLoadingMethodType"]]},"metadata":{"navigatorTitle":[{"text":"MBMRequestLoadingMethodTypeNetwork","kind":"identifier"}],"role":"symbol","externalID":"c:@E@MBMRequestLoadingMethodType@MBMRequestLoadingMethodTypeNetwork","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"network"}],"title":"RequestLoadingMethodType.network","modules":[{"name":"MapboxMaps"}],"roleHeading":"Case"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"network"}]}]}],"abstract":[{"type":"text","text":"The engine should try loading a resource from the network."}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestLoadingMethodType\/network","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/requestloadingmethodtype\/network"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/requestloadingmethodtype\/network"]}],"sections":[],"kind":"symbol","references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestLoadingMethodType/network":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestLoadingMethodType\/network","navigatorTitle":[{"text":"MBMRequestLoadingMethodTypeNetwork","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/requestloadingmethodtype\/network","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"network","kind":"identifier"}],"type":"topic","title":"RequestLoadingMethodType.network","kind":"symbol","abstract":[{"text":"The engine should try loading a resource from the network.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestLoadingMethodType":{"url":"\/documentation\/mapboxmaps\/requestloadingmethodtype","abstract":[{"type":"text","text":"The enumeration defines the method used to make a resource request."}],"navigatorTitle":[{"text":"RequestLoadingMethodType","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestLoadingMethodType","title":"RequestLoadingMethodType","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"RequestLoadingMethodType","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","role":"collection","url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"title":"MapboxMaps","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"MBMRequestLoadingMethodTypeNetwork"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBMRequestLoadingMethodTypeNetwork"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"MBMRequestLoadingMethodTypeNetwork"}]}]},"op":"replace"},{"value":"MBMRequestLoadingMethodTypeNetwork","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestLoadingMethodType~1network\/title"},{"value":[{"kind":"identifier","text":"MBMRequestLoadingMethodTypeNetwork"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestLoadingMethodType~1network\/fragments"},{"op":"replace","value":"MBMRequestLoadingMethodType","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestLoadingMethodType\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestLoadingMethodType\/fragments","op":"replace","value":[{"text":"MBMRequestLoadingMethodType","kind":"identifier"}]},{"value":[{"text":"MBMRequestLoadingMethodType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestLoadingMethodType\/navigatorTitle"}]}]}