{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequest"]]},"metadata":{"title":"request","modules":[{"name":"MapboxMaps"}],"externalID":"c:objc(cs)MBMResourceRequest(py)request","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"request","kind":"identifier"},{"text":": ","kind":"text"},{"text":"RequestInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMRequestInfo"}],"navigatorTitle":[{"text":"request","kind":"identifier"}],"roleHeading":"Instance Property","role":"symbol","symbolKind":"property"},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMResourceRequest\/request","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","abstract":[{"text":"The structure describes information about the resource request.","type":"text"}],"variants":[{"paths":["\/documentation\/mapboxmaps\/mbmresourcerequest\/request"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/mbmresourcerequest\/request"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"request","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestInfo","text":"RequestInfo","preciseIdentifier":"c:objc(cs)MBMRequestInfo"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMResourceRequest/request":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMResourceRequest\/request","url":"\/documentation\/mapboxmaps\/mbmresourcerequest\/request","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"request","kind":"identifier"},{"kind":"text","text":": "},{"text":"RequestInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMRequestInfo"}],"abstract":[{"text":"The structure describes information about the resource request.","type":"text"}],"navigatorTitle":[{"text":"request","kind":"identifier"}],"title":"request","role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestInfo":{"title":"RequestInfo","navigatorTitle":[{"text":"RequestInfo","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/requestinfo","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RequestInfo","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestInfo","role":"symbol","abstract":[{"type":"text","text":"The structure defines the information about the resource request."}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResourceRequest":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ResourceRequest","kind":"identifier"}],"title":"ResourceRequest","type":"topic","url":"\/documentation\/mapboxmaps\/resourcerequest","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ResourceRequest"},{"text":" event allows the application to observe resource requests made by a ","type":"text"},{"type":"codeVoice","code":"map"},{"type":"text","text":" or "},{"type":"codeVoice","code":"map snapshotter"},{"type":"text","text":" object."}],"navigatorTitle":[{"text":"ResourceRequest","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequest","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","title":"Map events","role":"collectionGroup","type":"topic","abstract":[{"type":"text","text":"The simplified diagram of the events emitted by the map is displayed below."}],"url":"\/documentation\/mapboxmaps\/events","kind":"article"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"request","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"kind":"identifier","text":"request"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestInfo","text":"MBMRequestInfo","preciseIdentifier":"c:objc(cs)MBMRequestInfo"},{"text":" * ","kind":"text"},{"text":"request","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"op":"replace","value":"request","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMResourceRequest~1request\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMResourceRequest~1request\/fragments","value":[{"kind":"identifier","text":"request"}]},{"value":"MBMRequestInfo","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestInfo\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestInfo\/fragments","value":[{"text":"MBMRequestInfo","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequest\/title","value":"MBMResourceRequest","op":"replace"},{"value":[{"text":"MBMResourceRequest","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequest\/fragments","op":"replace"}]}]}