{"abstract":[{"text":"The timestamps of the resource request event. The ","type":"text"},{"code":"timeInterval.begin","type":"codeVoice"},{"text":" is when","type":"text"},{"type":"text","text":" "},{"type":"text","text":"the resource request is made, and the "},{"type":"codeVoice","code":"timeInterval.end"},{"type":"text","text":" is when the request is completed."}],"kind":"symbol","identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMResourceRequest\/timeInterval","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"MapboxMaps"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"timeInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMEventTimeInterval","text":"EventTimeInterval"}],"navigatorTitle":[{"kind":"identifier","text":"timeInterval"}],"symbolKind":"property","title":"timeInterval","role":"symbol","roleHeading":"Instance Property","externalID":"c:objc(cs)MBMResourceRequest(py)timeInterval"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"timeInterval"},{"kind":"text","text":": "},{"text":"EventTimeInterval","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/EventTimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMEventTimeInterval"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/mbmresourcerequest\/timeinterval"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/mbmresourcerequest\/timeinterval"]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequest"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResourceRequest":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ResourceRequest","kind":"identifier"}],"title":"ResourceRequest","type":"topic","url":"\/documentation\/mapboxmaps\/resourcerequest","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ResourceRequest"},{"text":" event allows the application to observe resource requests made by a ","type":"text"},{"type":"codeVoice","code":"map"},{"type":"text","text":" or "},{"type":"codeVoice","code":"map snapshotter"},{"type":"text","text":" object."}],"navigatorTitle":[{"text":"ResourceRequest","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequest","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/EventTimeInterval":{"navigatorTitle":[{"kind":"identifier","text":"EventTimeInterval"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"EventTimeInterval"}],"type":"topic","title":"EventTimeInterval","abstract":[{"text":"The time interval of an event. The ","type":"text"},{"type":"codeVoice","code":"begin"},{"type":"text","text":" property represents the time"},{"type":"text","text":" "},{"type":"text","text":"origin of an event, and the "},{"type":"codeVoice","code":"end"},{"text":" property represents the time when the particular","type":"text"},{"text":" ","type":"text"},{"text":"operation is complete. The timestamps are sampled at the origin and do not include","type":"text"},{"type":"text","text":" "},{"type":"text","text":"the time required to dispatch an event."}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/EventTimeInterval","url":"\/documentation\/mapboxmaps\/eventtimeinterval","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","title":"Map events","role":"collectionGroup","type":"topic","abstract":[{"type":"text","text":"The simplified diagram of the events emitted by the map is displayed below."}],"url":"\/documentation\/mapboxmaps\/events","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMResourceRequest/timeInterval":{"abstract":[{"type":"text","text":"The timestamps of the resource request event. The "},{"code":"timeInterval.begin","type":"codeVoice"},{"text":" is when","type":"text"},{"type":"text","text":" "},{"text":"the resource request is made, and the ","type":"text"},{"code":"timeInterval.end","type":"codeVoice"},{"type":"text","text":" is when the request is completed."}],"navigatorTitle":[{"kind":"identifier","text":"timeInterval"}],"kind":"symbol","title":"timeInterval","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMResourceRequest\/timeInterval","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"timeInterval"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMEventTimeInterval","text":"EventTimeInterval","kind":"typeIdentifier"}],"url":"\/documentation\/mapboxmaps\/mbmresourcerequest\/timeinterval","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"timeInterval","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"timeInterval"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/EventTimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMEventTimeInterval","text":"MBMEventTimeInterval"},{"kind":"text","text":" * "},{"kind":"identifier","text":"timeInterval"},{"kind":"text","text":";"}]}]},"op":"replace"},{"value":"MBMResourceRequest","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequest\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequest\/fragments","value":[{"text":"MBMResourceRequest","kind":"identifier"}],"op":"replace"},{"value":"MBMEventTimeInterval","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1EventTimeInterval\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBMEventTimeInterval"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1EventTimeInterval\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMResourceRequest~1timeInterval\/title","value":"timeInterval"},{"op":"replace","value":[{"kind":"identifier","text":"timeInterval"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMResourceRequest~1timeInterval\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}