{"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMFeatureExtensionValue\/initWithValue:featureCollection:","interfaceLanguage":"occ"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMapsInternal","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeatureExtensionValue"]]},"metadata":{"title":"initWithValue:featureCollection:","roleHeading":"Instance Method","navigatorTitle":[{"text":"initWithValue:featureCollection:","kind":"identifier"}],"symbolKind":"method","role":"symbol","externalID":"c:objc(cs)MBMFeatureExtensionValue(im)initWithValue:featureCollection:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithValue:featureCollection:"}],"modules":[{"name":"MapboxMaps"}]},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithValue:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"internalParam","text":"value"},{"kind":"text","text":" "},{"kind":"identifier","text":"featureCollection:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<MBXFeature *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"featureCollection"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/mbmfeatureextensionvalue\/initwithvalue:featurecollection:"]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","title":"MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMapsInternal":{"url":"\/documentation\/mapboxmaps\/coremapsinternal","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMapsInternal","kind":"article","title":"CoreMaps - Internal","abstract":[{"type":"text","text":"Maps rendering SDK also known as GL-Native. These are for internal use only."}],"role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","role":"collection","url":"\/documentation\/overview","title":"MapboxMaps Documentation","kind":"article","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FeatureExtensionValue":{"navigatorTitle":[{"text":"FeatureExtensionValue","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/featureextensionvalue","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeatureExtensionValue","kind":"symbol","abstract":[{"type":"text","text":"A value or a collection of a feature extension."}],"title":"FeatureExtensionValue","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FeatureExtensionValue","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMFeatureExtensionValue/initWithValue:featureCollection:":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMFeatureExtensionValue\/initWithValue:featureCollection:","title":"initWithValue:featureCollection:","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithValue:featureCollection:"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithValue:featureCollection:"}],"url":"\/documentation\/mapboxmaps\/mbmfeatureextensionvalue\/initwithvalue:featurecollection:","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeatureExtensionValue\/title","op":"replace","value":"MBMFeatureExtensionValue"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeatureExtensionValue\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMFeatureExtensionValue"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeatureExtensionValue\/navigatorTitle","op":"replace","value":[{"text":"MBMFeatureExtensionValue","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}