{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Settings-and-Constants","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MapboxOptions"]]},"abstract":[{"type":"text","text":"Get Mapbox access token."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"getAccessToken","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},{"content":[{"anchor":"return-value","text":"Return Value","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Token string or empty string in case token is not set.","type":"text"}]}],"kind":"content"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","roleHeading":"Type Method","symbolKind":"method","modules":[{"name":"MapboxCommon"}],"externalID":"c:objc(cs)MBXMapboxOptions(cm)getAccessToken","title":"getAccessToken","navigatorTitle":[{"text":"getAccessToken","kind":"identifier"}],"fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getAccessToken"}]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/mbxmapboxoptions\/getaccesstoken"]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXMapboxOptions\/getAccessToken"},"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","url":"\/documentation\/mapboxmaps","role":"collection","title":"MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXMapboxOptions/getAccessToken":{"url":"\/documentation\/mapboxcommon\/mbxmapboxoptions\/getaccesstoken","abstract":[{"text":"Get Mapbox access token.","type":"text"}],"title":"getAccessToken","type":"topic","kind":"symbol","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getAccessToken"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"getAccessToken"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXMapboxOptions\/getAccessToken"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","abstract":[],"kind":"article","url":"\/documentation\/overview","type":"topic","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MapboxOptions":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapboxOptions","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/mapboxoptions","type":"topic","abstract":[{"type":"text","text":"Class for Mapbox SDK settings management"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MapboxOptions","kind":"symbol","role":"symbol","title":"MapboxOptions","navigatorTitle":[{"kind":"identifier","text":"MapboxOptions"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Settings-and-Constants":{"role":"collectionGroup","title":"Settings and Constants","url":"\/documentation\/mapboxmaps\/settings-and-constants","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Settings-and-Constants","kind":"article","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MapboxOptions\/title","op":"replace","value":"MBXMapboxOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MapboxOptions\/fragments","value":[{"kind":"identifier","text":"MBXMapboxOptions"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MapboxOptions\/navigatorTitle","value":[{"text":"MBXMapboxOptions","kind":"identifier"}],"op":"replace"}]}]}