{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadProgress"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completedResourceCount"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s6UInt64V","text":"UInt64","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completedResourceSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt64","preciseIdentifier":"s:s6UInt64V"},{"kind":"text","text":", "},{"text":"erroredResourceCount","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s6UInt64V","text":"UInt64","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"requiredResourceCount"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s6UInt64V","kind":"typeIdentifier","text":"UInt64"},{"kind":"text","text":", "},{"kind":"externalParam","text":"loadedResourceCount"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s6UInt64V","text":"UInt64","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"loadedResourceSize"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s6UInt64V","text":"UInt64","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadProgress\/init(completedResourceCount:completedResourceSize:erroredResourceCount:requiredResourceCount:loadedResourceCount:loadedResourceSize:)"},"variants":[{"paths":["\/documentation\/mapboxmaps\/stylepackloadprogress\/init(completedresourcecount:completedresourcesize:erroredresourcecount:requiredresourcecount:loadedresourcecount:loadedresourcesize:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/stylepackloadprogress\/init(completedresourcecount:completedresourcesize:erroredresourcecount:requiredresourcecount:loadedresourcecount:loadedresourcesize:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Initializer","symbolKind":"init","externalID":"c:objc(cs)MBMStylePackLoadProgress(im)initWithCompletedResourceCount:completedResourceSize:erroredResourceCount:requiredResourceCount:loadedResourceCount:loadedResourceSize:","role":"symbol","modules":[{"name":"MapboxMaps"}],"navigatorTitle":[{"text":"initWithCompletedResourceCount:completedResourceSize:erroredResourceCount:requiredResourceCount:loadedResourceCount:loadedResourceSize:","kind":"identifier"}],"title":"init(completedResourceCount:completedResourceSize:erroredResourceCount:requiredResourceCount:loadedResourceCount:loadedResourceSize:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completedResourceCount"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s6UInt64V","text":"UInt64","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completedResourceSize","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt64","preciseIdentifier":"s:s6UInt64V","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"erroredResourceCount"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt64","preciseIdentifier":"s:s6UInt64V"},{"kind":"text","text":", "},{"text":"requiredResourceCount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt64","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V"},{"kind":"text","text":", "},{"text":"loadedResourceCount","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UInt64","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"loadedResourceSize"},{"text":": ","kind":"text"},{"text":"UInt64","preciseIdentifier":"s:s6UInt64V","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"kind":"symbol","references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"kind":"article","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/tilestore-apis","type":"topic","title":"TileStore APIs"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","title":"MapboxMaps Documentation","kind":"article","url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePackLoadProgress":{"navigatorTitle":[{"text":"StylePackLoadProgress","kind":"identifier"}],"kind":"symbol","title":"StylePackLoadProgress","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadProgress","abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"style pack load"},{"type":"text","text":" progress includes information about"},{"text":" ","type":"text"},{"type":"text","text":"the number of resources that have completed downloading"},{"text":" ","type":"text"},{"type":"text","text":"and the total number of resources that are required."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StylePackLoadProgress"}],"url":"\/documentation\/mapboxmaps\/stylepackloadprogress","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePackLoadProgress/init(completedResourceCount:completedResourceSize:erroredResourceCount:requiredResourceCount:loadedResourceCount:loadedResourceSize:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"completedResourceCount","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s6UInt64V","kind":"typeIdentifier","text":"UInt64"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completedResourceSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V","text":"UInt64"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"erroredResourceCount"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s6UInt64V","text":"UInt64","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"requiredResourceCount"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s6UInt64V","kind":"typeIdentifier","text":"UInt64"},{"kind":"text","text":", "},{"text":"loadedResourceCount","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s6UInt64V","text":"UInt64","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"loadedResourceSize","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UInt64","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V"},{"kind":"text","text":")"}],"title":"init(completedResourceCount:completedResourceSize:erroredResourceCount:requiredResourceCount:loadedResourceCount:loadedResourceSize:)","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadProgress\/init(completedResourceCount:completedResourceSize:erroredResourceCount:requiredResourceCount:loadedResourceCount:loadedResourceSize:)","kind":"symbol","url":"\/documentation\/mapboxmaps\/stylepackloadprogress\/init(completedresourcecount:completedresourcesize:erroredresourcecount:requiredresourcecount:loadedresourcecount:loadedresourcesize:)","navigatorTitle":[{"text":"initWithCompletedResourceCount:completedResourceSize:erroredResourceCount:requiredResourceCount:loadedResourceCount:loadedResourceSize:","kind":"identifier"}],"role":"symbol","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","title":"MapboxMaps","kind":"symbol","url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"initWithCompletedResourceCount:completedResourceSize:erroredResourceCount:requiredResourceCount:loadedResourceCount:loadedResourceSize:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithCompletedResourceCount:completedResourceSize:erroredResourceCount:requiredResourceCount:loadedResourceCount:loadedResourceSize:","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"text":"initWithCompletedResourceCount:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"uint64_t","preciseIdentifier":"c:@T@uint64_t"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"completedResourceCount"},{"kind":"text","text":" "},{"kind":"identifier","text":"completedResourceSize:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@uint64_t","kind":"typeIdentifier","text":"uint64_t"},{"text":") ","kind":"text"},{"text":"completedResourceSize","kind":"internalParam"},{"kind":"text","text":" "},{"text":"erroredResourceCount:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@uint64_t","text":"uint64_t","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"erroredResourceCount"},{"text":" ","kind":"text"},{"text":"requiredResourceCount:","kind":"identifier"},{"kind":"text","text":"("},{"text":"uint64_t","preciseIdentifier":"c:@T@uint64_t","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"requiredResourceCount","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loadedResourceCount:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@uint64_t","text":"uint64_t"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"loadedResourceCount"},{"kind":"text","text":" "},{"text":"loadedResourceSize:","kind":"identifier"},{"kind":"text","text":"("},{"text":"uint64_t","preciseIdentifier":"c:@T@uint64_t","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"loadedResourceSize","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadProgress\/title","value":"MBMStylePackLoadProgress"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadProgress\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMStylePackLoadProgress"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadProgress\/navigatorTitle","value":[{"kind":"identifier","text":"MBMStylePackLoadProgress"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadProgress~1init(completedResourceCount:completedResourceSize:erroredResourceCount:requiredResourceCount:loadedResourceCount:loadedResourceSize:)\/title","value":"initWithCompletedResourceCount:completedResourceSize:erroredResourceCount:requiredResourceCount:loadedResourceCount:loadedResourceSize:"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadProgress~1init(completedResourceCount:completedResourceSize:erroredResourceCount:requiredResourceCount:loadedResourceCount:loadedResourceSize:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithCompletedResourceCount:completedResourceSize:erroredResourceCount:requiredResourceCount:loadedResourceCount:loadedResourceSize:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}