{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType\/init(rawValue:)"},"variants":[{"paths":["\/documentation\/mapboxmaps\/customrastersourceclienttype\/init(rawvalue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType"]]},"sections":[],"metadata":{"symbolKind":"init","title":"init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"role":"symbol","modules":[{"name":"MapboxMaps"}],"roleHeading":"Initializer","externalID":"s:So31MBMCustomRasterSourceClientTypeV8rawValueABSgSi_tcfc"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceClientType":{"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/customrastersourceclienttype","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"CustomRasterSourceClientType","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType","navigatorTitle":[{"text":"CustomRasterSourceClientType","kind":"identifier"}],"title":"CustomRasterSourceClientType"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Sources":{"title":"Sources","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources","kind":"article","abstract":[],"url":"\/documentation\/mapboxmaps\/sources","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceClientType/init(rawValue:)":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType\/init(rawValue:)","title":"init(rawValue:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}],"url":"\/documentation\/mapboxmaps\/customrastersourceclienttype\/init(rawvalue:)","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","abstract":[],"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","kind":"article","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"MBMCustomRasterSourceClientType","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType\/fragments","value":[{"kind":"identifier","text":"MBMCustomRasterSourceClientType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType\/navigatorTitle","value":[{"kind":"identifier","text":"MBMCustomRasterSourceClientType"}]}]}]}