{"relationshipsSections":[{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/s15BitwiseCopyableP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH","doc:\/\/com.mapbox.MapboxMaps\/SY","doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode"},"seeAlsoSections":[{"generated":true,"title":"Location","anchor":"Location","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationManager","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck2DConfiguration","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Model","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckBearing","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProviderDelegate","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Coordinate2D","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationExtraKeys","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProviderRequest","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceFactory","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/DeviceLocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Heading","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckRenderingData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/IntervalSettings"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationErrorCode","kind":"identifier"}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs"]]},"abstract":[{"type":"text","text":"Codes of location errors."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/locationerrorcode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/locationerrorcode"]}],"topicSections":[{"generated":true,"title":"Enumeration Cases","anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode\/accessDenied","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode\/cancelled","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode\/communicationFailure","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode\/failedToDetectLocation","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode\/invalidArgument","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode\/none","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode\/notAvailable","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode\/notReady","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode\/notSupported","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode\/unknown"]},{"generated":true,"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode\/init(rawValue:)"]},{"generated":true,"title":"Default Implementations","anchor":"Default-Implementations","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode\/Equatable-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode\/RawRepresentable-Implementations"]}],"metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationErrorCode"}],"modules":[{"name":"MapboxCommon"}],"navigatorTitle":[{"kind":"identifier","text":"LocationErrorCode"}],"externalID":"c:@E@MBXLocationErrorCode","roleHeading":"Enumeration","symbolKind":"enum","role":"symbol","title":"LocationErrorCode"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Coordinate2D":{"title":"Coordinate2D","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Coordinate2D","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Boxed version of CLLocationCoordinate2D"}],"type":"topic","url":"\/documentation\/mapboxcommon\/coordinate2d","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Coordinate2D","navigatorTitle":[{"text":"Coordinate2D","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Heading":{"url":"\/documentation\/mapboxmaps\/heading","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Heading","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"Heading","kind":"identifier"}],"type":"topic","kind":"symbol","title":"Heading","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Heading","abstract":[{"type":"text","text":"The azimuth (orientation) of the user’s device, relative to true or magnetic north."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"url":"\/documentation\/mapboxmaps","title":"MapboxMaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic"},"doc://com.mapbox.MapboxMaps/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SY"},"doc://com.mapbox.MapboxMaps/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationErrorCode/notReady":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notReady"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"MBXLocationErrorCodeNotReady"}],"title":"LocationErrorCode.notReady","url":"\/documentation\/mapboxcommon\/locationerrorcode\/notready","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode\/notReady","abstract":[{"type":"text","text":"Not ready for the requested operation."}],"role":"symbol","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PuckType":{"title":"PuckType","kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/pucktype","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PuckType","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckType","abstract":[{"type":"text","text":"Represents the different types of pucks"}],"navigatorTitle":[{"text":"PuckType","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Location":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Location"}],"title":"Location","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location","url":"\/documentation\/mapboxcommon\/location","abstract":[{"type":"text","text":"Location information."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"Location"}],"role":"symbol","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationErrorCode/notAvailable":{"type":"topic","abstract":[{"text":"The subject of the request is not available.","type":"text"}],"role":"symbol","title":"LocationErrorCode.notAvailable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode\/notAvailable","kind":"symbol","navigatorTitle":[{"text":"MBXLocationErrorCodeNotAvailable","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notAvailable","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/locationerrorcode\/notavailable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PermissionStatus":{"title":"PermissionStatus","role":"symbol","navigatorTitle":[{"text":"PermissionStatus","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus","kind":"symbol","abstract":[{"type":"text","text":"Location permissions granted by user to the app."}],"url":"\/documentation\/mapboxcommon\/permissionstatus","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PermissionStatus","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationErrorCode/notSupported":{"role":"symbol","title":"LocationErrorCode.notSupported","type":"topic","url":"\/documentation\/mapboxcommon\/locationerrorcode\/notsupported","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode\/notSupported","abstract":[{"type":"text","text":"Requested feature is not implemented or no supported by the device."}],"navigatorTitle":[{"text":"MBXLocationErrorCodeNotSupported","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notSupported","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationErrorCode/init(rawValue:)":{"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode\/init(rawValue:)","url":"\/documentation\/mapboxcommon\/locationerrorcode\/init(rawvalue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","title":"init(rawValue:)","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeadingObserver":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HeadingObserver","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/headingobserver","type":"topic","navigatorTitle":[{"text":"HeadingObserver","kind":"identifier"}],"title":"HeadingObserver","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingObserver","abstract":[{"type":"text","text":"Listens to "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingProvider"},{"type":"text","text":"’s updates."}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/s15BitwiseCopyableP":{"type":"unresolvable","title":"Swift.BitwiseCopyable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s15BitwiseCopyableP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationServiceObserver":{"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Observers for getting updates from LocationService."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationServiceObserver","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver","title":"LocationServiceObserver","role":"symbol","url":"\/documentation\/mapboxcommon\/locationserviceobserver","navigatorTitle":[{"text":"LocationServiceObserver","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationErrorCode/none":{"abstract":[{"type":"text","text":"No error occured."}],"navigatorTitle":[{"kind":"identifier","text":"MBXLocationErrorCodeNone"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode\/none","url":"\/documentation\/mapboxcommon\/locationerrorcode\/none","role":"symbol","title":"LocationErrorCode.none","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/DeviceLocationProvider":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DeviceLocationProvider","kind":"identifier"}],"navigatorTitle":[{"text":"DeviceLocationProvider","kind":"identifier"}],"abstract":[{"text":"Location provider specialisation that provides real-time locations generated from the device","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/DeviceLocationProvider","role":"symbol","type":"topic","title":"DeviceLocationProvider","url":"\/documentation\/mapboxcommon\/devicelocationprovider"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationErrorCode/invalidArgument":{"title":"LocationErrorCode.invalidArgument","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode\/invalidArgument","url":"\/documentation\/mapboxcommon\/locationerrorcode\/invalidargument","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBXLocationErrorCodeInvalidArgument"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidArgument"}],"abstract":[{"text":"Invalid argument.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationObserver":{"url":"\/documentation\/mapboxcommon\/locationobserver","abstract":[{"text":"Observer for getting updates from a LocationProvider.","type":"text"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationObserver","kind":"symbol","title":"LocationObserver","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationObserver","kind":"identifier"}],"navigatorTitle":[{"text":"LocationObserver","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationProviderRequest":{"abstract":[{"type":"text","text":"Data model that contains parameters for location requests."}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProviderRequest","role":"symbol","url":"\/documentation\/mapboxcommon\/locationproviderrequest","title":"LocationProviderRequest","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationProviderRequest"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"LocationProviderRequest"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Model":{"type":"topic","navigatorTitle":[{"text":"Model","kind":"identifier"}],"title":"Model","role":"symbol","url":"\/documentation\/mapboxmaps\/model","kind":"symbol","abstract":[{"type":"text","text":"A structure represeting a Model"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Model","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Model","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/IntervalSettings":{"title":"IntervalSettings","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntervalSettings"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/IntervalSettings","url":"\/documentation\/mapboxcommon\/intervalsettings","abstract":[{"text":"The interval for active location updates","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"IntervalSettings"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LocationManager":{"abstract":[{"text":"An object responsible for managing user location Puck.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"LocationManager"}],"url":"\/documentation\/mapboxmaps\/locationmanager","title":"LocationManager","role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationManager"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationExtraKeys":{"role":"symbol","url":"\/documentation\/mapboxcommon\/locationextrakeys","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationExtraKeys","navigatorTitle":[{"kind":"identifier","text":"LocationExtraKeys"}],"title":"LocationExtraKeys","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationExtraKeys"}],"kind":"symbol","abstract":[{"text":"Keys for additional information (extra) in Location.","type":"text"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationErrorCode/communicationFailure":{"abstract":[{"type":"text","text":"Failed to communicate with the platform service."}],"title":"LocationErrorCode.communicationFailure","type":"topic","url":"\/documentation\/mapboxcommon\/locationerrorcode\/communicationfailure","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode\/communicationFailure","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBXLocationErrorCodeCommunicationFailure"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"communicationFailure"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/AccuracyLevel":{"url":"\/documentation\/mapboxcommon\/accuracylevel","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AccuracyLevel","kind":"identifier"}],"navigatorTitle":[{"text":"AccuracyLevel","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel","type":"topic","abstract":[{"text":"The accuracy of the observed location","type":"text"}],"title":"AccuracyLevel"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationServiceFactory":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationServiceFactory","kind":"identifier"}],"navigatorTitle":[{"text":"LocationServiceFactory","kind":"identifier"}],"abstract":[{"text":"Location service factory.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceFactory","role":"symbol","type":"topic","title":"LocationServiceFactory","url":"\/documentation\/mapboxcommon\/locationservicefactory"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LocationOptions":{"title":"LocationOptions","url":"\/documentation\/mapboxmaps\/locationoptions","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationOptions","kind":"identifier"}],"navigatorTitle":[{"text":"LocationOptions","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationOptions","abstract":[{"type":"text","text":"A struct to configure a "},{"type":"codeVoice","code":"LocationManager"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PuckRenderingData":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PuckRenderingData","kind":"identifier"}],"role":"symbol","title":"PuckRenderingData","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckRenderingData","url":"\/documentation\/mapboxmaps\/puckrenderingdata","type":"topic","abstract":[{"type":"text","text":"Represents the interpolated data ready to render the user location puck."}],"kind":"symbol","navigatorTitle":[{"text":"PuckRenderingData","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeadingProvider":{"url":"\/documentation\/mapboxmaps\/headingprovider","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeadingProvider"}],"navigatorTitle":[{"kind":"identifier","text":"HeadingProvider"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingProvider","abstract":[{"type":"text","text":"Provides heading data to drive the location puck."}],"role":"symbol","type":"topic","title":"HeadingProvider"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Puck2DConfiguration":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Puck2DConfiguration"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Puck2DConfiguration"}],"kind":"symbol","title":"Puck2DConfiguration","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck2DConfiguration","url":"\/documentation\/mapboxmaps\/puck2dconfiguration"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/AccuracyAuthorization":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AccuracyAuthorization","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"AccuracyAuthorization","kind":"identifier"}],"abstract":[{"type":"text","text":"Accuracy authorization granted by user to the app."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization","url":"\/documentation\/mapboxcommon\/accuracyauthorization","kind":"symbol","title":"AccuracyAuthorization"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AppleLocationProvider":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AppleLocationProvider"}],"abstract":[{"text":"A location provider based on CoreLocation’s ","type":"text"},{"type":"codeVoice","code":"CLLocationManager"},{"text":".","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppleLocationProvider"}],"type":"topic","title":"AppleLocationProvider","url":"\/documentation\/mapboxmaps\/applelocationprovider"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationErrorCode/failedToDetectLocation":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode\/failedToDetectLocation","type":"topic","title":"LocationErrorCode.failedToDetectLocation","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failedToDetectLocation","kind":"identifier"}],"navigatorTitle":[{"text":"MBXLocationErrorCodeFailedToDetectLocation","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/locationerrorcode\/failedtodetectlocation","abstract":[{"text":"Failed to detect location.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AppleLocationProviderDelegate":{"navigatorTitle":[{"text":"AppleLocationProviderDelegate","kind":"identifier"}],"abstract":[{"text":"The ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProviderDelegate","type":"reference"},{"text":" protocol defines a set of optional methods that you","type":"text"},{"text":" ","type":"text"},{"text":"can use to receive events from an associated location provider object.","type":"text"}],"role":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/applelocationproviderdelegate","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProviderDelegate","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AppleLocationProviderDelegate","kind":"identifier"}],"title":"AppleLocationProviderDelegate"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article","type":"topic","title":"MapboxMaps Documentation","abstract":[],"url":"\/documentation\/overview","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationErrorCode/Equatable-Implementations":{"url":"\/documentation\/mapboxcommon\/locationerrorcode\/equatable-implementations","type":"topic","abstract":[],"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode\/Equatable-Implementations","role":"collectionGroup","title":"Equatable Implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Location-APIs":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","role":"collectionGroup","abstract":[],"kind":"article","title":"Location","url":"\/documentation\/mapboxmaps\/location-apis"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationErrorCode/accessDenied":{"kind":"symbol","url":"\/documentation\/mapboxcommon\/locationerrorcode\/accessdenied","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode\/accessDenied","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessDenied","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The app is not authorized to access location."}],"navigatorTitle":[{"text":"MBXLocationErrorCodeAccessDenied","kind":"identifier"}],"title":"LocationErrorCode.accessDenied","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationErrorCode":{"type":"topic","url":"\/documentation\/mapboxcommon\/locationerrorcode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationErrorCode","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"LocationErrorCode","kind":"identifier"}],"abstract":[{"type":"text","text":"Codes of location errors."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode","title":"LocationErrorCode","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Puck3DConfiguration":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration","role":"symbol","abstract":[],"url":"\/documentation\/mapboxmaps\/puck3dconfiguration","type":"topic","title":"Puck3DConfiguration","navigatorTitle":[{"text":"Puck3DConfiguration","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Puck3DConfiguration","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationErrorCode/RawRepresentable-Implementations":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode\/RawRepresentable-Implementations","kind":"article","title":"RawRepresentable Implementations","role":"collectionGroup","url":"\/documentation\/mapboxcommon\/locationerrorcode\/rawrepresentable-implementations","abstract":[],"type":"topic"},"doc://com.mapbox.MapboxMaps/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationProvider":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationProvider"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider","kind":"symbol","title":"LocationProvider","navigatorTitle":[{"kind":"identifier","text":"LocationProvider"}],"role":"symbol","url":"\/documentation\/mapboxcommon\/locationprovider","type":"topic","abstract":[{"text":"Location provider that provides locations","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationErrorCode/cancelled":{"type":"topic","kind":"symbol","abstract":[{"text":"Operation was cancelled.","type":"text"}],"role":"symbol","url":"\/documentation\/mapboxcommon\/locationerrorcode\/cancelled","title":"LocationErrorCode.cancelled","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode\/cancelled","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelled"}],"navigatorTitle":[{"kind":"identifier","text":"MBXLocationErrorCodeCancelled"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PuckBearing":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PuckBearing"}],"title":"PuckBearing","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckBearing","type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/mapboxmaps\/puckbearing","navigatorTitle":[{"kind":"identifier","text":"PuckBearing"}],"abstract":[{"type":"text","text":"Controls how the puck is oriented"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationErrorCode/unknown":{"url":"\/documentation\/mapboxcommon\/locationerrorcode\/unknown","navigatorTitle":[{"text":"MBXLocationErrorCodeUnknown","kind":"identifier"}],"title":"LocationErrorCode.unknown","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode\/unknown","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}],"abstract":[{"type":"text","text":"Reserved fallback for unclassified failures."}],"role":"symbol","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationError":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationError"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationError","title":"LocationError","navigatorTitle":[{"kind":"identifier","text":"LocationError"}],"type":"topic","url":"\/documentation\/mapboxcommon\/locationerror","abstract":[{"text":"Error code with brief explanation.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"MBXLocationErrorCode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MBXLocationErrorCode"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MBXLocationErrorCode"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode\/accessDenied","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode\/cancelled","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode\/communicationFailure","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode\/failedToDetectLocation","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode\/invalidArgument","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode\/none","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode\/notAvailable","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode\/notReady","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode\/notSupported","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode\/unknown"],"title":"Enumeration Cases","generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Coordinate2D","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationExtraKeys","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProviderRequest","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceFactory","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/DeviceLocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/IntervalSettings"],"title":"Location","generated":true,"anchor":"Location"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBXLocationErrorCode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Coordinate2D\/title","value":"MBXCoordinate2D"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Coordinate2D\/fragments","value":[{"kind":"identifier","text":"MBXCoordinate2D"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Coordinate2D\/navigatorTitle","value":[{"kind":"identifier","text":"MBXCoordinate2D"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode~1notReady\/title","value":"MBXLocationErrorCodeNotReady"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode~1notReady\/fragments","value":[{"text":"MBXLocationErrorCodeNotReady","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/title","value":"MBXLocation"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/fragments","value":[{"text":"MBXLocation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/navigatorTitle","value":[{"text":"MBXLocation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode~1notAvailable\/title","value":"MBXLocationErrorCodeNotAvailable"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode~1notAvailable\/fragments","value":[{"text":"MBXLocationErrorCodeNotAvailable","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/title","value":"MBXPermissionStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/fragments","value":[{"text":"MBXPermissionStatus","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/navigatorTitle","value":[{"kind":"identifier","text":"MBXPermissionStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode~1notSupported\/title","value":"MBXLocationErrorCodeNotSupported"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode~1notSupported\/fragments","value":[{"text":"MBXLocationErrorCodeNotSupported","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver\/title","value":"MBXLocationServiceObserver"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver\/fragments","value":[{"kind":"identifier","text":"MBXLocationServiceObserver"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver\/navigatorTitle","value":[{"kind":"identifier","text":"MBXLocationServiceObserver"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode~1none\/title","value":"MBXLocationErrorCodeNone"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode~1none\/fragments","value":[{"kind":"identifier","text":"MBXLocationErrorCodeNone"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1DeviceLocationProvider\/title","value":"MBXDeviceLocationProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1DeviceLocationProvider\/fragments","value":[{"kind":"identifier","text":"MBXDeviceLocationProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1DeviceLocationProvider\/navigatorTitle","value":[{"text":"MBXDeviceLocationProvider","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode~1invalidArgument\/title","value":"MBXLocationErrorCodeInvalidArgument"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode~1invalidArgument\/fragments","value":[{"text":"MBXLocationErrorCodeInvalidArgument","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/title","value":"MBXLocationObserver"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/fragments","value":[{"text":"MBXLocationObserver","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/navigatorTitle","value":[{"text":"MBXLocationObserver","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProviderRequest\/title","value":"MBXLocationProviderRequest"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProviderRequest\/fragments","value":[{"kind":"identifier","text":"MBXLocationProviderRequest"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProviderRequest\/navigatorTitle","value":[{"text":"MBXLocationProviderRequest","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1IntervalSettings\/title","value":"MBXIntervalSettings"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1IntervalSettings\/fragments","value":[{"kind":"identifier","text":"MBXIntervalSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1IntervalSettings\/navigatorTitle","value":[{"text":"MBXIntervalSettings","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationExtraKeys\/title","value":"MBXLocationExtraKeys"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationExtraKeys\/fragments","value":[{"kind":"identifier","text":"MBXLocationExtraKeys"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationExtraKeys\/navigatorTitle","value":[{"text":"MBXLocationExtraKeys","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode~1communicationFailure\/title","value":"MBXLocationErrorCodeCommunicationFailure"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode~1communicationFailure\/fragments","value":[{"kind":"identifier","text":"MBXLocationErrorCodeCommunicationFailure"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel\/title","value":"MBXAccuracyLevel"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXAccuracyLevel"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel\/navigatorTitle","op":"replace","value":[{"text":"MBXAccuracyLevel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceFactory\/title","op":"replace","value":"MBXLocationServiceFactory"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceFactory\/fragments","op":"replace","value":[{"text":"MBXLocationServiceFactory","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceFactory\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBXLocationServiceFactory"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization\/title","op":"replace","value":"MBXAccuracyAuthorization"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization\/fragments","op":"replace","value":[{"text":"MBXAccuracyAuthorization","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBXAccuracyAuthorization"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode~1failedToDetectLocation\/title","op":"replace","value":"MBXLocationErrorCodeFailedToDetectLocation"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode~1failedToDetectLocation\/fragments","op":"replace","value":[{"text":"MBXLocationErrorCodeFailedToDetectLocation","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode~1accessDenied\/title","op":"replace","value":"MBXLocationErrorCodeAccessDenied"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode~1accessDenied\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXLocationErrorCodeAccessDenied"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/title","op":"replace","value":"MBXLocationErrorCode"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXLocationErrorCode"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/navigatorTitle","op":"replace","value":[{"text":"MBXLocationErrorCode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/title","op":"replace","value":"MBXLocationProvider"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXLocationProvider"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/navigatorTitle","op":"replace","value":[{"text":"MBXLocationProvider","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode~1cancelled\/title","op":"replace","value":"MBXLocationErrorCodeCancelled"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode~1cancelled\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXLocationErrorCodeCancelled"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode~1unknown\/title","op":"replace","value":"MBXLocationErrorCodeUnknown"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode~1unknown\/fragments","op":"replace","value":[{"text":"MBXLocationErrorCodeUnknown","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationError\/title","op":"replace","value":"MBXLocationError"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationError\/fragments","op":"replace","value":[{"text":"MBXLocationError","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationError\/navigatorTitle","op":"replace","value":[{"text":"MBXLocationError","kind":"identifier"}]}]}]}