{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SwiftUI","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map"]]},"abstract":[{"text":"An image added to the style is no longer needed and can be removed using ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/removeImage(withId:)","isActive":true},{"text":".","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/map\/onstyleimageremoveunused(action:)"]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onStyleImageRemoveUnused(action:)","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"MapboxMaps"}],"externalID":"s:10MapboxMaps3MapV24onStyleImageRemoveUnused6actionACySo08MBMStylefgH0Cc_tF","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onStyleImageRemoveUnused"},{"kind":"text","text":"("},{"text":"action","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMStyleImageRemoveUnused","text":"StyleImageRemoveUnused"},{"kind":"text","text":") -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"text":"Map","preciseIdentifier":"s:10MapboxMaps3MapV","kind":"typeIdentifier"}],"role":"symbol","extendedModule":"MapboxMaps","platforms":[{"introducedAt":"13.0","beta":false,"name":"iOS","deprecated":false,"unavailable":false},{"unavailable":false,"deprecated":false,"name":"iPadOS","introducedAt":"13.0","beta":false},{"introducedAt":"13.0","beta":false,"unavailable":false,"deprecated":false,"name":"Mac Catalyst"}],"title":"onStyleImageRemoveUnused(action:)"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onStyleImageRemoveUnused"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"keyword","text":"@escaping"},{"kind":"text","text":" ("},{"preciseIdentifier":"c:objc(cs)MBMStyleImageRemoveUnused","kind":"typeIdentifier","text":"StyleImageRemoveUnused","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnused"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps3MapV","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map","text":"Map"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","abstract":[],"url":"\/documentation\/overview","role":"collection","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map":{"abstract":[{"type":"text","text":"A SwiftUI view that displays a Mapbox Map."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Map"}],"url":"\/documentation\/mapboxmaps\/map","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"Map","kind":"identifier"}],"title":"Map","type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SwiftUI":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SwiftUI","title":"SwiftUI","abstract":[],"kind":"article","type":"topic","url":"\/documentation\/mapboxmaps\/swiftui","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/removeImage(withId:)":{"role":"symbol","url":"\/documentation\/mapboxmaps\/stylemanager\/removeimage(withid:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"removeImage","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"abstract":[{"type":"text","text":"Removes an image from the style."}],"kind":"symbol","title":"removeImage(withId:)","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/removeImage(withId:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleImageRemoveUnused":{"navigatorTitle":[{"kind":"identifier","text":"StyleImageRemoveUnused"}],"abstract":[{"text":"An image requested by the ","type":"text"},{"type":"codeVoice","code":"map"},{"text":" through the ","type":"text"},{"code":"StyleImageMissing","type":"codeVoice"},{"type":"text","text":" event is no longer"},{"text":" ","type":"text"},{"text":"needed and can be removed using the ","type":"text"},{"type":"codeVoice","code":"removeStyleImage"},{"type":"text","text":" method. The application can"},{"text":" ","type":"text"},{"type":"text","text":"decide whether the image should be kept or removed."}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnused","kind":"symbol","title":"StyleImageRemoveUnused","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"StyleImageRemoveUnused"}],"url":"\/documentation\/mapboxmaps\/styleimageremoveunused"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/onStyleImageRemoveUnused(action:)":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/map\/onstyleimageremoveunused(action:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onStyleImageRemoveUnused"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"StyleImageRemoveUnused","preciseIdentifier":"c:objc(cs)MBMStyleImageRemoveUnused"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":") -> ","kind":"text"},{"text":"Map","preciseIdentifier":"s:10MapboxMaps3MapV","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onStyleImageRemoveUnused(action:)","role":"symbol","type":"topic","abstract":[{"text":"An image added to the style is no longer needed and can be removed using ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/removeImage(withId:)"},{"text":".","type":"text"}],"title":"onStyleImageRemoveUnused(action:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnused\/title","value":"MBMStyleImageRemoveUnused"},{"value":[{"kind":"identifier","text":"MBMStyleImageRemoveUnused"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnused\/fragments","op":"replace"},{"op":"replace","value":[{"text":"MBMStyleImageRemoveUnused","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnused\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}