{"abstract":[{"text":"A custom Mapbox value associated with this style package for storing metadata.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadOptions"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"metadata","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"},{"content":[{"anchor":"discussion","text":"Discussion","level":2,"type":"heading"},{"inlineContent":[{"text":"If provided, the custom value value will be stored alongside the style package. Previous values will","type":"text"},{"text":" ","type":"text"},{"text":"be replaced with the new value.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"Developers can use this field to store custom metadata associated with a style package.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadOptions\/metadata","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"MapboxMaps"}],"title":"metadata","navigatorTitle":[{"kind":"identifier","text":"metadata"}],"symbolKind":"property","externalID":"c:objc(cs)MBMStylePackLoadOptions(py)metadata","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"metadata"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property","role":"symbol"},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/stylepackloadoptions\/metadata"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/stylepackloadoptions\/metadata"]}],"sections":[],"kind":"symbol","references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePackLoadOptions/metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"metadata"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"metadata"}],"abstract":[{"type":"text","text":"A custom Mapbox value associated with this style package for storing metadata."}],"url":"\/documentation\/mapboxmaps\/stylepackloadoptions\/metadata","role":"symbol","type":"topic","kind":"symbol","title":"metadata","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadOptions\/metadata"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","role":"collection","title":"MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","url":"\/documentation\/overview","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","kind":"article","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePackLoadOptions":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadOptions","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"StylePackLoadOptions"}],"title":"StylePackLoadOptions","abstract":[{"text":"Describes the style package load option values.","type":"text"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StylePackLoadOptions"}],"url":"\/documentation\/mapboxmaps\/stylepackloadoptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"type":"topic","title":"TileStore APIs","url":"\/documentation\/mapboxmaps\/tilestore-apis","abstract":[],"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","role":"collectionGroup"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"metadata"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"metadata"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":" ","kind":"text"},{"text":"metadata","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadOptions~1metadata\/title","value":"metadata"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadOptions~1metadata\/fragments","value":[{"kind":"identifier","text":"metadata"}]},{"value":"MBMStylePackLoadOptions","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadOptions\/title","op":"replace"},{"value":[{"text":"MBMStylePackLoadOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadOptions\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MBMStylePackLoadOptions"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadOptions\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}