{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"renderingWillEnd","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"Note that it may be called even when the "},{"type":"codeVoice","code":"renderingWillStart"},{"type":"text","text":" function has not been called."}],"type":"paragraph"}]}],"kind":"symbol","metadata":{"modules":[{"name":"MapboxMaps"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"renderingWillEnd"}],"title":"renderingWillEnd()","required":true,"externalID":"c:objc(pl)MBMCustomLayerHost(im)renderingWillEnd","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"renderingWillEnd"},{"kind":"text","text":"()"}]},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerHost\/renderingWillEnd()","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/customlayerhost\/renderingwillend()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/customlayerhost\/renderingwillend()"]}],"abstract":[{"type":"text","text":"Destroy any state needed by the custom layer, and deallocate context, if necessary. This"},{"type":"text","text":" "},{"type":"text","text":"method is called once, from the main thread, at a point when Metal or OpenGL context is active."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerHost"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","role":"collection","type":"topic","abstract":[],"title":"MapboxMaps Documentation","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerHost/renderingWillEnd()":{"url":"\/documentation\/mapboxmaps\/customlayerhost\/renderingwillend()","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerHost\/renderingWillEnd()","navigatorTitle":[{"text":"renderingWillEnd","kind":"identifier"}],"title":"renderingWillEnd()","abstract":[{"text":"Destroy any state needed by the custom layer, and deallocate context, if necessary. This","type":"text"},{"text":" ","type":"text"},{"text":"method is called once, from the main thread, at a point when Metal or OpenGL context is active.","type":"text"}],"kind":"symbol","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"renderingWillEnd","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layers":{"role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers","type":"topic","abstract":[],"title":"Layers","url":"\/documentation\/mapboxmaps\/layers","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","role":"collection","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","type":"topic","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerHost":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomLayerHost"}],"navigatorTitle":[{"kind":"identifier","text":"CustomLayerHost"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerHost","role":"symbol","url":"\/documentation\/mapboxmaps\/customlayerhost","abstract":[{"text":"Interface for hosting a custom map style layer.","type":"text"}],"title":"CustomLayerHost","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"renderingWillEnd"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"renderingWillEnd"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"renderingWillEnd","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost~1renderingWillEnd()\/title","value":"renderingWillEnd"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost~1renderingWillEnd()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"renderingWillEnd"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost\/title","op":"replace","value":"MBMCustomLayerHost"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost\/fragments","op":"replace","value":[{"text":"MBMCustomLayerHost","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMCustomLayerHost"}]}]}]}