{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapEventType"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mapIdle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MapEventType","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapEventType","preciseIdentifier":"s:10MapboxMaps12MapEventTypeV"},{"text":"<","kind":"text"},{"text":"MapIdle","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapIdle","preciseIdentifier":"c:objc(cs)MBMMapIdle"},{"text":"> { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","abstract":[{"type":"text","text":"The map has entered the idle state."}],"metadata":{"title":"mapIdle","externalID":"s:10MapboxMaps12MapEventTypeV7mapIdleACySo06MBMMapG0CGvpZ","roleHeading":"Type Property","symbolKind":"property","platforms":[],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mapIdle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps12MapEventTypeV","text":"MapEventType"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMMapIdle","text":"MapIdle"},{"kind":"text","text":">"}],"role":"symbol","modules":[{"name":"MapboxMaps"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapEventType\/mapIdle"},"sections":[],"variants":[{"paths":["\/documentation\/mapboxmaps\/mapeventtype\/mapidle"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"abstract":[{"type":"text","text":"The simplified diagram of the events emitted by the map is displayed below."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","title":"Map events","role":"collectionGroup","kind":"article","url":"\/documentation\/mapboxmaps\/events","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Snapshotter":{"url":"\/documentation\/mapboxmaps\/snapshotter","title":"Snapshotter","abstract":[{"type":"text","text":"A utility class for capturing styled map snapshots."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Snapshotter"}],"navigatorTitle":[{"kind":"identifier","text":"Snapshotter"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapIdle":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MapIdle"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapIdle","url":"\/documentation\/mapboxmaps\/mapidle","title":"MapIdle","type":"topic","abstract":[{"text":"The ","type":"text"},{"code":"map","type":"codeVoice"},{"text":" has entered the idle state. The ","type":"text"},{"code":"map","type":"codeVoice"},{"text":" is idle when there are no ongoing","type":"text"},{"text":" ","type":"text"},{"text":"animations, transitions and the ","type":"text"},{"code":"map","type":"codeVoice"},{"text":" has rendered all requested non-volatile tiles","type":"text"},{"text":" ","type":"text"},{"text":"(e.g., live traffic tiles). The event will not be emitted if ","type":"text"},{"code":"setUserAnimationInProgress","type":"codeVoice"},{"text":" ","type":"text"},{"text":"and \/ or ","type":"text"},{"code":"setGestureInProgress","type":"codeVoice"},{"text":" is set to ","type":"text"},{"code":"true","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapIdle"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapboxMap"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","navigatorTitle":[{"kind":"identifier","text":"MapboxMap"}],"abstract":[{"type":"text","text":"Provides access to the map model, including the camera, style, observable map events,"},{"type":"text","text":" "},{"type":"text","text":"and querying rendered features."}],"role":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap","title":"MapboxMap","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","type":"topic","abstract":[],"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapEventType/mapIdle":{"abstract":[{"type":"text","text":"The map has entered the idle state."}],"title":"mapIdle","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapEventType\/mapIdle","type":"topic","url":"\/documentation\/mapboxmaps\/mapeventtype\/mapidle","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mapIdle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MapEventType","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps12MapEventTypeV"},{"text":"<","kind":"text"},{"text":"MapIdle","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMMapIdle"},{"text":">","kind":"text"}],"deprecated":true,"role":"symbol","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","kind":"symbol","type":"topic","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapEventType":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapEventType","abstract":[{"type":"text","text":"A shim that makes it possible to subscribe to "},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","isActive":true},{"type":"text","text":" and "},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter","isActive":true},{"type":"text","text":" events via the old "},{"type":"codeVoice","code":"onNext"},{"type":"text","text":" and  "},{"type":"codeVoice","code":"onEvery"},{"type":"text","text":" methods."},{"type":"text","text":" "},{"type":"text","text":"It is here to simplify migration from v10 to v11, but will be removed in v12."}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapEventType","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/mapeventtype","navigatorTitle":[{"text":"MapEventType","kind":"identifier"}],"deprecated":true,"type":"topic","kind":"symbol","title":"MapEventType"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MBMMapIdle","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdle\/title"},{"value":[{"text":"MBMMapIdle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdle\/fragments"},{"value":[{"text":"MBMMapIdle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdle\/navigatorTitle"}]}]}