{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/settingsservice\/has(key:)"]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","metadata":{"extendedModule":"MapboxCommon","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"has","kind":"identifier"},{"text":"(","kind":"text"},{"text":"key","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s6ResultO","text":"Result","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:12MapboxCommon20SettingsServiceErrorV","text":"SettingsServiceError","kind":"typeIdentifier"},{"text":">","kind":"text"}],"externalID":"s:So18MBXSettingsServiceC12MapboxCommonE3has3keys6ResultOySbAC08SettingsB5ErrorVGSS_tF","role":"symbol","title":"has(key:)","symbolKind":"method","modules":[{"name":"MapboxCommon"}],"roleHeading":"Instance Method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"has"},{"kind":"text","text":"("},{"kind":"externalParam","text":"key"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceError","preciseIdentifier":"s:12MapboxCommon20SettingsServiceErrorV","text":"SettingsServiceError"},{"kind":"text","text":">"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsService\/has(key:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Settings-and-Constants","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsService"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","role":"collection","title":"MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsService":{"title":"SettingsService","kind":"symbol","url":"\/documentation\/mapboxcommon\/settingsservice","abstract":[{"type":"text","text":"Platform independent settings service. Settings service is a key\/value storage (persistent or non"},{"type":"text","text":" "},{"type":"text","text":"persistent), that also allows to register observers to get notifications when values are updated."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SettingsService","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsService","role":"symbol","type":"topic","navigatorTitle":[{"text":"SettingsService","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Settings-and-Constants":{"title":"Settings and Constants","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Settings-and-Constants","role":"collectionGroup","kind":"article","abstract":[],"type":"topic","url":"\/documentation\/mapboxmaps\/settings-and-constants"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsService/has(key:)":{"title":"has(key:)","url":"\/documentation\/mapboxcommon\/settingsservice\/has(key:)","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"has"},{"kind":"text","text":"("},{"kind":"externalParam","text":"key"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO","text":"Result"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:12MapboxCommon20SettingsServiceErrorV","text":"SettingsServiceError"},{"kind":"text","text":">"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsService\/has(key:)","role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","type":"topic","abstract":[],"title":"MapboxMaps Documentation","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsServiceError":{"navigatorTitle":[{"kind":"identifier","text":"SettingsServiceError"}],"url":"\/documentation\/mapboxcommon\/settingsserviceerror","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SettingsServiceError"}],"role":"symbol","abstract":[{"text":"Structure for keeping an information about errors that can happen when using Settings service","type":"text"}],"kind":"symbol","title":"SettingsServiceError","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsService\/title","value":"MBXSettingsService"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsService\/fragments","value":[{"kind":"identifier","text":"MBXSettingsService"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsService\/navigatorTitle","value":[{"text":"MBXSettingsService","kind":"identifier"}]}]}]}