{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.hashValue"},{"text":".","type":"text"}],"variants":[{"paths":["\/documentation\/mapboxmaps\/offlineregiondownloadstate\/hashvalue"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionDownloadState\/hashValue","interfaceLanguage":"swift"},"metadata":{"extendedModule":"Swift","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"title":"hashValue","modules":[{"name":"MapboxMaps","relatedModules":["Swift"]}],"conformance":{"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"availabilityPrefix":[{"type":"text","text":"Available when"}]},"role":"symbol","externalID":"s:SYsSHRzSH8RawValueSYRpzrlE04hashB0Sivp::SYNTHESIZED::c:@E@MBMOfflineRegionDownloadState","roleHeading":"Instance Property"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionDownloadState","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionDownloadState\/RawRepresentable-Implementations"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionDownloadState/RawRepresentable-Implementations":{"type":"topic","role":"collectionGroup","title":"RawRepresentable Implementations","kind":"article","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionDownloadState\/RawRepresentable-Implementations","url":"\/documentation\/mapboxmaps\/offlineregiondownloadstate\/rawrepresentable-implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMaps":{"kind":"article","abstract":[{"text":"Maps rendering SDK also known as GL-Native","type":"text"}],"url":"\/documentation\/mapboxmaps\/coremaps","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","type":"topic","title":"Core Maps API"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Offline":{"url":"\/documentation\/mapboxmaps\/offline","kind":"article","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","abstract":[],"role":"collectionGroup","title":"Offline Support"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","role":"collection","abstract":[],"type":"topic","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionDownloadState/hashValue":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionDownloadState\/hashValue","type":"topic","abstract":[],"title":"hashValue","conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}]},"kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/offlineregiondownloadstate\/hashvalue","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionDownloadState":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionDownloadState","url":"\/documentation\/mapboxmaps\/offlineregiondownloadstate","type":"topic","title":"OfflineRegionDownloadState","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OfflineRegionDownloadState"}],"abstract":[{"type":"text","text":"Describes the download state of a region."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OfflineRegionDownloadState"}],"kind":"symbol","deprecated":true}},"variantOverrides":[{"patch":[{"value":"MBMOfflineRegionDownloadState","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionDownloadState\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBMOfflineRegionDownloadState"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionDownloadState\/fragments"},{"value":[{"kind":"identifier","text":"MBMOfflineRegionDownloadState"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionDownloadState\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}