{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/customrastersourcetilerenderer\/prerender(for:commandbuffer:)"]},{"paths":["\/documentation\/mapboxmaps\/customrastersourcetilerenderer\/prerender(for:commandbuffer:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer\/prerender(for:commandBuffer:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This method is called once per frame, before any layer is rendered."},{"type":"text","text":" "},{"text":"It is to be used to allow to prepare resources or render into a texture for the client","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"or initialize some varaibles and states shared across the tiles."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"prerender"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"text":" ","kind":"text"},{"text":"parameters","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMCustomLayerRenderParameters","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters","text":"CustomLayerRenderParameters"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"commandBuffer"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s6UInt64V","text":"UInt64","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]},{"parameters":[{"name":"parameters","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"code":"custom layer render parameters","type":"codeVoice"},{"text":".","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The default command buffer"}]}],"name":"commandBuffer"}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"The client should obtain the ","type":"text"},{"type":"codeVoice","code":"MTLCommandBuffer"},{"type":"text","text":" instance from the "},{"type":"codeVoice","code":"commandBuffer"},{"type":"text","text":" argument, using the"},{"type":"text","text":" "},{"type":"text","text":"following code:"}]},{"syntax":null,"code":["mtlCommandBuffer = (__bridge id<MTLCommandBuffer>)(void*)commandBuffer;"],"type":"codeListing"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer"]]},"metadata":{"symbolKind":"method","role":"symbol","externalID":"c:objc(pl)MBMCustomRasterSourceTileRenderer(im)prerenderForParameters:commandBuffer:","roleHeading":"Instance Method","navigatorTitle":[{"text":"prerenderForParameters:commandBuffer:","kind":"identifier"}],"modules":[{"name":"MapboxMaps"}],"title":"prerender(for:commandBuffer:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"prerender"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMCustomLayerRenderParameters","text":"CustomLayerRenderParameters"},{"text":", ","kind":"text"},{"text":"commandBuffer","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UInt64","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V"},{"kind":"text","text":")"}],"required":true},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerRenderParameters":{"abstract":[{"text":"Parameters that define the current camera position for a ","type":"text"},{"type":"codeVoice","code":"CustomLayerHost::render()"},{"type":"text","text":" function."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CustomLayerRenderParameters"}],"url":"\/documentation\/mapboxmaps\/customlayerrenderparameters","role":"symbol","type":"topic","title":"CustomLayerRenderParameters","navigatorTitle":[{"kind":"identifier","text":"CustomLayerRenderParameters"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Sources":{"role":"collectionGroup","type":"topic","abstract":[],"title":"Sources","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources","url":"\/documentation\/mapboxmaps\/sources","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileRenderer/prerender(for:commandBuffer:)":{"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/customrastersourcetilerenderer\/prerender(for:commandbuffer:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer\/prerender(for:commandBuffer:)","abstract":[{"type":"text","text":"This method is called once per frame, before any layer is rendered."},{"text":" ","type":"text"},{"type":"text","text":"It is to be used to allow to prepare resources or render into a texture for the client"},{"type":"text","text":" "},{"type":"text","text":"or initialize some varaibles and states shared across the tiles."}],"navigatorTitle":[{"text":"prerenderForParameters:commandBuffer:","kind":"identifier"}],"title":"prerender(for:commandBuffer:)","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prerender"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"text":"CustomLayerRenderParameters","preciseIdentifier":"c:objc(cs)MBMCustomLayerRenderParameters","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"commandBuffer","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s6UInt64V","text":"UInt64","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"role":"collection","url":"\/documentation\/mapboxmaps","title":"MapboxMaps","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","abstract":[],"type":"topic","kind":"article","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileRenderer":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer","type":"topic","title":"CustomRasterSourceTileRenderer","role":"symbol","kind":"symbol","url":"\/documentation\/mapboxmaps\/customrastersourcetilerenderer","navigatorTitle":[{"text":"CustomRasterSourceTileRenderer","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CustomRasterSourceTileRenderer"}],"abstract":[{"text":"Interface for the direct rendering into the custom raster tiles.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"prerenderForParameters:commandBuffer:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"prerenderForParameters:commandBuffer:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"prerenderForParameters:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMCustomLayerRenderParameters","text":"MBMCustomLayerRenderParameters"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"parameters"},{"kind":"text","text":" "},{"text":"commandBuffer:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"uint64_t","preciseIdentifier":"c:@T@uint64_t","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"commandBuffer","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"name":"parameters","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"custom layer render parameters"},{"text":".","type":"text"}]}]},{"name":"commandBuffer","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The default command buffer"}]}]}],"kind":"parameters"}},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/title","value":"MBMCustomLayerRenderParameters","op":"replace"},{"value":[{"text":"MBMCustomLayerRenderParameters","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/navigatorTitle","value":[{"text":"MBMCustomLayerRenderParameters","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer~1prerender(for:commandBuffer:)\/title","op":"replace","value":"prerenderForParameters:commandBuffer:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"prerenderForParameters:commandBuffer:"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer~1prerender(for:commandBuffer:)\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer\/title","op":"replace","value":"MBMCustomRasterSourceTileRenderer"},{"value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileRenderer"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer\/fragments"},{"value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileRenderer"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}