{"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"other","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Vec3","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMVec3","text":"Vec3"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Free-Camera","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Vec3"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/vec3\/isequal(to:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/vec3\/isequal(to:)"]}],"metadata":{"externalID":"c:objc(cs)MBMVec3(im)isEqualToVec3:","modules":[{"name":"MapboxMaps"}],"role":"symbol","symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"text":"isEqualToVec3:","kind":"identifier"}],"title":"isEqual(to:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isEqual","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMVec3","text":"Vec3"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Vec3\/isEqual(to:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Vec3/isEqual(to:)":{"abstract":[],"title":"isEqual(to:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Vec3\/isEqual(to:)","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/vec3\/isequal(to:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isEqual"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMVec3","kind":"typeIdentifier","text":"Vec3"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"isEqualToVec3:","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","role":"collection","abstract":[],"kind":"article","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","url":"\/documentation\/mapboxmaps","type":"topic","role":"collection","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMaps":{"kind":"article","abstract":[{"text":"Maps rendering SDK also known as GL-Native","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","type":"topic","url":"\/documentation\/mapboxmaps\/coremaps","role":"collectionGroup","title":"Core Maps API"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Free-Camera":{"abstract":[],"role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Free-Camera","kind":"article","url":"\/documentation\/mapboxmaps\/free-camera","title":"Free Camera","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Vec3":{"role":"symbol","abstract":[{"type":"text","text":"3 component vector."}],"url":"\/documentation\/mapboxmaps\/vec3","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Vec3","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Vec3","kind":"identifier"}],"title":"Vec3","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Vec3"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"isEqualToVec3:","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"isEqualToVec3:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isEqualToVec3:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Vec3","text":"MBMVec3","preciseIdentifier":"c:objc(cs)MBMVec3"},{"kind":"text","text":" *) "},{"text":"other","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Vec3~1isEqual(to:)\/title","value":"isEqualToVec3:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"isEqualToVec3:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Vec3~1isEqual(to:)\/fragments"},{"op":"replace","value":"MBMVec3","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Vec3\/title"},{"value":[{"text":"MBMVec3","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Vec3\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Vec3\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMVec3"}]}]}]}