{"variants":[{"paths":["\/documentation\/mapboxcommon\/location\/init(cllocation:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/location\/init(cllocation:)"]}],"metadata":{"extendedModule":"MapboxCommon","symbolKind":"init","modules":[{"name":"MapboxCommon"}],"externalID":"c:objc(cs)MBXLocation(im)initWithCLLocation:","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"CLLocation"},{"kind":"text","text":": "},{"text":"CLLocation","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CLLocation"},{"text":")","kind":"text"}],"title":"init(CLLocation:)","platforms":[],"navigatorTitle":[{"kind":"identifier","text":"initWithCLLocation:"}],"role":"symbol","roleHeading":"Initializer"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location\/init(CLLocation:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"CLLocation","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"location"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CLLocation","text":"CLLocation"},{"text":")","kind":"text"}]},{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"clLocation"},{"text":" ","kind":"text"},{"text":"location","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)CLLocation","kind":"typeIdentifier","text":"CLLocation"},{"text":")","kind":"text"}]}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Location":{"abstract":[{"type":"text","text":"Location information."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Location"}],"url":"\/documentation\/mapboxcommon\/location","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Location","kind":"identifier"}],"kind":"symbol","type":"topic","title":"Location","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","abstract":[],"kind":"article","role":"collection","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Location-APIs":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","url":"\/documentation\/mapboxmaps\/location-apis","type":"topic","kind":"article","role":"collectionGroup","abstract":[],"title":"Location"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Location/init(CLLocation:)":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"CLLocation","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocation","preciseIdentifier":"c:objc(cs)CLLocation"},{"text":")","kind":"text"}],"title":"init(CLLocation:)","abstract":[],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location\/init(CLLocation:)","url":"\/documentation\/mapboxcommon\/location\/init(cllocation:)","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"initWithCLLocation:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithCLLocation:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithCLLocation:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithCLLocation:"},{"kind":"text","text":"("},{"text":"CLLocation","preciseIdentifier":"c:objc(cs)CLLocation","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"location","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"op":"replace","value":"MBXLocation","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/fragments","value":[{"text":"MBXLocation","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MBXLocation"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location~1init(CLLocation:)\/title","value":"initWithCLLocation:","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location~1init(CLLocation:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCLLocation:"}]}]}]}