{"seeAlsoSections":[{"anchor":"Advanced","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs"],"title":"Advanced","generated":true}],"sections":[],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","interfaceLanguage":"swift"},"kind":"article","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"]]},"metadata":{"title":"Performance and investigations","role":"collectionGroup","roleHeading":"API Collection","modules":[{"name":"MapboxMaps"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Tracing"],"title":"Signpost","anchor":"Signpost"},{"title":"Map Recording","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapRecorderOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapPlayerOptions"],"anchor":"Map-Recording"},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatistics","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CumulativeRenderingStatistics","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/DurationStatistics","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GroupPerformanceStatistics","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerFrameRenderingStatistics","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatisticsOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatisticsCallback"],"anchor":"Performance-recording","title":"Performance recording"},{"anchor":"Logs","title":"Logs","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogConfiguration","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogWriterBackend","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LoggingLevel"]},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapViewDebugOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions"],"anchor":"Debug","title":"Debug"},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NSExceptionHandler"],"title":"Crashes","anchor":"Crashes"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CumulativeRenderingStatistics":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CumulativeRenderingStatistics","kind":"identifier"}],"abstract":[],"role":"symbol","kind":"symbol","title":"CumulativeRenderingStatistics","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CumulativeRenderingStatistics","type":"topic","url":"\/documentation\/mapboxmaps\/cumulativerenderingstatistics","navigatorTitle":[{"text":"CumulativeRenderingStatistics","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Tracing":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Tracing","kind":"symbol","title":"Tracing","navigatorTitle":[{"text":"Tracing","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxmaps\/tracing","abstract":[{"text":"Enable ","type":"text"},{"type":"codeVoice","code":"os_signpost"},{"type":"text","text":" generation in some components"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Tracing"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","type":"topic","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"title":"MapboxMaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PerFrameRenderingStatistics":{"url":"\/documentation\/mapboxmaps\/perframerenderingstatistics","type":"topic","navigatorTitle":[{"text":"PerFrameRenderingStatistics","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerFrameRenderingStatistics","role":"symbol","title":"PerFrameRenderingStatistics","kind":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PerFrameRenderingStatistics","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapRecorder":{"url":"\/documentation\/mapboxmaps\/maprecorder","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapRecorder"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"MapRecorder","kind":"identifier"}],"title":"MapRecorder","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapRecorder","abstract":[{"type":"text","text":"MapRecorder provides functions to record and replay API calls of a Map instance."},{"type":"text","text":" "},{"type":"text","text":"These recordings can be used to debug issues which requie multiple steps to reproduce."},{"type":"text","text":" "},{"text":"Additionaly, playbacks can be used for performance testing custom scenarios.","type":"text"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapViewDebugOptions":{"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MapViewDebugOptions"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"MapViewDebugOptions","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapViewDebugOptions","abstract":[{"type":"text","text":"Options for enabling debugging features in a map."}],"type":"topic","url":"\/documentation\/mapboxmaps\/mapviewdebugoptions","title":"MapViewDebugOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LogConfiguration":{"navigatorTitle":[{"text":"LogConfiguration","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/logconfiguration","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Class that allows to configure Mapbox SDKs logging per application."}],"kind":"symbol","title":"LogConfiguration","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LogConfiguration","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PerformanceStatisticsOptions":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatisticsOptions","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PerformanceStatisticsOptions"}],"url":"\/documentation\/mapboxmaps\/performancestatisticsoptions","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PerformanceStatisticsOptions","kind":"identifier"}],"title":"PerformanceStatisticsOptions","abstract":[{"type":"text","text":"Options for the following statistics collection behaviors:"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LogWriterBackend":{"title":"LogWriterBackend","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"LogWriterBackend","kind":"identifier"}],"navigatorTitle":[{"text":"LogWriterBackend","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogWriterBackend","type":"topic","url":"\/documentation\/mapboxcommon\/logwriterbackend","abstract":[{"type":"text","text":"Interface for implementing log writing backends, e.g. for using platform specific log backends or logging to a notification service."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapRecorderOptions":{"navigatorTitle":[{"kind":"identifier","text":"MapRecorderOptions"}],"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapRecorderOptions"}],"abstract":[{"type":"text","text":"Options for recording the map when using "},{"isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapRecorder","type":"reference"}],"kind":"symbol","title":"MapRecorderOptions","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapRecorderOptions","url":"\/documentation\/mapboxmaps\/maprecorderoptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapPlayerOptions":{"role":"symbol","type":"topic","abstract":[{"text":"Options for playback when using ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapRecorder","type":"reference"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapPlayerOptions","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"MapPlayerOptions","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/mapplayeroptions","navigatorTitle":[{"kind":"identifier","text":"MapPlayerOptions"}],"title":"MapPlayerOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/DurationStatistics":{"url":"\/documentation\/mapboxmaps\/durationstatistics","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/DurationStatistics","kind":"symbol","title":"DurationStatistics","role":"symbol","abstract":[],"navigatorTitle":[{"text":"DurationStatistics","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DurationStatistics"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PerformanceStatistics":{"role":"symbol","type":"topic","navigatorTitle":[{"text":"PerformanceStatistics","kind":"identifier"}],"abstract":[{"type":"text","text":"The performance statistics collected at the end of the sampling duration."}],"kind":"symbol","title":"PerformanceStatistics","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatistics","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PerformanceStatistics","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/performancestatistics"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","url":"\/documentation\/mapboxmaps\/tilestore-apis","title":"TileStore APIs","abstract":[],"kind":"article","type":"topic","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapDebugOptions":{"title":"MapDebugOptions","abstract":[{"text":"Options for enabling debugging features in a map.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions","role":"symbol","url":"\/documentation\/mapboxmaps\/mapdebugoptions","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapDebugOptions"}],"navigatorTitle":[{"kind":"identifier","text":"MapDebugOptions"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"url":"\/documentation\/mapboxmaps\/mapboxmap-apis","role":"collectionGroup","type":"topic","abstract":[],"kind":"article","title":"MapboxMap","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PerformanceStatisticsCallback":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatisticsCallback","role":"symbol","navigatorTitle":[{"text":"PerformanceStatisticsCallback","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/performancestatisticscallback","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"PerformanceStatisticsCallback"}],"title":"PerformanceStatisticsCallback","abstract":[{"type":"text","text":"Use this callback to observe the collected statistics. The callback is invoked at regular intervals determined by"},{"text":" ","type":"text"},{"text":"the sampling duration specified in the ","type":"text"},{"type":"codeVoice","code":"PerformanceStatisticsOptions"},{"type":"text","text":". The callback is invoked from the main thread."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/NSExceptionHandler":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NSExceptionHandler"}],"navigatorTitle":[{"kind":"identifier","text":"NSExceptionHandler"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NSExceptionHandler","title":"NSExceptionHandler","url":"\/documentation\/mapboxcommon\/nsexceptionhandler","kind":"symbol","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","url":"\/documentation\/overview","title":"MapboxMaps Documentation","type":"topic","role":"collection","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GroupPerformanceStatistics":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GroupPerformanceStatistics","navigatorTitle":[{"text":"GroupPerformanceStatistics","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupPerformanceStatistics"}],"url":"\/documentation\/mapboxmaps\/groupperformancestatistics","abstract":[],"title":"GroupPerformanceStatistics","kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LoggingLevel":{"title":"LoggingLevel","kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LoggingLevel","abstract":[{"type":"text","text":"State level of a log message."}],"url":"\/documentation\/mapboxcommon\/logginglevel","navigatorTitle":[{"kind":"identifier","text":"LoggingLevel"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"LoggingLevel","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"MBMCumulativeRenderingStatistics","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CumulativeRenderingStatistics\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CumulativeRenderingStatistics\/fragments","value":[{"kind":"identifier","text":"MBMCumulativeRenderingStatistics"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CumulativeRenderingStatistics\/navigatorTitle","value":[{"kind":"identifier","text":"MBMCumulativeRenderingStatistics"}]},{"value":"MBMPerFrameRenderingStatistics","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerFrameRenderingStatistics\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MBMPerFrameRenderingStatistics"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerFrameRenderingStatistics\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerFrameRenderingStatistics\/navigatorTitle","value":[{"text":"MBMPerFrameRenderingStatistics","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapRecorder\/title","value":"MBMMapRecorder"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapRecorder\/fragments","op":"replace","value":[{"text":"MBMMapRecorder","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapRecorder\/navigatorTitle","value":[{"text":"MBMMapRecorder","kind":"identifier"}],"op":"replace"},{"value":"MBXLogConfiguration","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogConfiguration\/title"},{"value":[{"kind":"identifier","text":"MBXLogConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogConfiguration\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBXLogConfiguration"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatisticsOptions\/title","op":"replace","value":"MBMPerformanceStatisticsOptions"},{"value":[{"text":"MBMPerformanceStatisticsOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatisticsOptions\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatisticsOptions\/navigatorTitle","value":[{"kind":"identifier","text":"MBMPerformanceStatisticsOptions"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogWriterBackend\/title","value":"MBXLogWriterBackend","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogWriterBackend\/fragments","value":[{"text":"MBXLogWriterBackend","kind":"identifier"}]},{"value":[{"text":"MBXLogWriterBackend","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogWriterBackend\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1DurationStatistics\/title","value":"MBMDurationStatistics"},{"value":[{"text":"MBMDurationStatistics","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1DurationStatistics\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1DurationStatistics\/navigatorTitle","value":[{"text":"MBMDurationStatistics","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"MBMPerformanceStatistics","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatistics\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatistics\/fragments","value":[{"text":"MBMPerformanceStatistics","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatistics\/navigatorTitle","value":[{"text":"MBMPerformanceStatistics","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions\/title","value":"MBMMapDebugOptions","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions\/fragments","value":[{"kind":"identifier","text":"MBMMapDebugOptions"}]},{"value":[{"text":"MBMMapDebugOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatisticsCallback\/title","value":"MBMPerformanceStatisticsCallback"},{"value":[{"text":"MBMPerformanceStatisticsCallback","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatisticsCallback\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatisticsCallback\/navigatorTitle","value":[{"kind":"identifier","text":"MBMPerformanceStatisticsCallback"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1NSExceptionHandler\/title","value":"MBXExceptionHandler","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1NSExceptionHandler\/fragments","value":[{"text":"MBXExceptionHandler","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"MBXExceptionHandler"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1NSExceptionHandler\/navigatorTitle"},{"value":"MBMGroupPerformanceStatistics","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GroupPerformanceStatistics\/title"},{"value":[{"kind":"identifier","text":"MBMGroupPerformanceStatistics"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GroupPerformanceStatistics\/fragments"},{"op":"replace","value":[{"text":"MBMGroupPerformanceStatistics","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GroupPerformanceStatistics\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LoggingLevel\/title","value":"MBXLoggingLevel"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LoggingLevel\/fragments","value":[{"text":"MBXLoggingLevel","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LoggingLevel\/navigatorTitle","value":[{"text":"MBXLoggingLevel","kind":"identifier"}]}]}]}