{"schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestLoadingMethodType\/cache","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestLoadingMethodType\/network"],"anchor":"Enumeration-Cases","title":"Enumeration Cases"},{"generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestLoadingMethodType\/init(rawValue:)"],"anchor":"Initializers","title":"Initializers"},{"title":"Default Implementations","anchor":"Default-Implementations","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestLoadingMethodType\/Equatable-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestLoadingMethodType\/RawRepresentable-Implementations"],"generated":true}],"variants":[{"paths":["\/documentation\/mapboxmaps\/requestloadingmethodtype"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/requestloadingmethodtype"]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events"]]},"abstract":[{"text":"The enumeration defines the method used to make a resource request.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestLoadingMethodType"},"seeAlsoSections":[{"title":"Event payload","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderModeType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestPriorityType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestDataSourceType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResponseSourceType"],"anchor":"Event-payload"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"RequestLoadingMethodType","kind":"identifier"}]}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/s15BitwiseCopyableP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH","doc:\/\/com.mapbox.MapboxMaps\/SY","doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"RequestLoadingMethodType"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"RequestLoadingMethodType"}],"roleHeading":"Enumeration","modules":[{"name":"MapboxMaps"}],"symbolKind":"enum","role":"symbol","externalID":"c:@E@MBMRequestLoadingMethodType","title":"RequestLoadingMethodType"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResponseSourceType":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResponseSourceType"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResponseSourceType","url":"\/documentation\/mapboxmaps\/responsesourcetype","navigatorTitle":[{"text":"ResponseSourceType","kind":"identifier"}],"title":"ResponseSourceType","kind":"symbol","type":"topic","abstract":[{"text":"The enumeration defines the source type that provides the requested resource.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestLoadingMethodType/RawRepresentable-Implementations":{"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestLoadingMethodType\/RawRepresentable-Implementations","url":"\/documentation\/mapboxmaps\/requestloadingmethodtype\/rawrepresentable-implementations","title":"RawRepresentable Implementations","abstract":[],"type":"topic","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s8SendableP","title":"Swift.Sendable"},"doc://com.mapbox.MapboxMaps/s15BitwiseCopyableP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s15BitwiseCopyableP","title":"Swift.BitwiseCopyable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestLoadingMethodType":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RequestLoadingMethodType"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestLoadingMethodType","url":"\/documentation\/mapboxmaps\/requestloadingmethodtype","navigatorTitle":[{"text":"RequestLoadingMethodType","kind":"identifier"}],"title":"RequestLoadingMethodType","kind":"symbol","type":"topic","abstract":[{"text":"The enumeration defines the method used to make a resource request.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestLoadingMethodType/Equatable-Implementations":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestLoadingMethodType\/Equatable-Implementations","role":"collectionGroup","type":"topic","abstract":[],"url":"\/documentation\/mapboxmaps\/requestloadingmethodtype\/equatable-implementations","kind":"article","title":"Equatable Implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestLoadingMethodType/network":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"network"}],"navigatorTitle":[{"text":"MBMRequestLoadingMethodTypeNetwork","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/requestloadingmethodtype\/network","type":"topic","title":"RequestLoadingMethodType.network","abstract":[{"type":"text","text":"The engine should try loading a resource from the network."}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestLoadingMethodType\/network"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleDataLoadedType":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"StyleDataLoadedType"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedType","url":"\/documentation\/mapboxmaps\/styledataloadedtype","navigatorTitle":[{"text":"StyleDataLoadedType","kind":"identifier"}],"title":"StyleDataLoadedType","kind":"symbol","type":"topic","abstract":[{"text":"The enumeration defines the type of loaded style data.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestLoadingMethodType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/requestloadingmethodtype\/init(rawvalue:)","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestLoadingMethodType\/init(rawValue:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestLoadingMethodType/cache":{"abstract":[{"type":"text","text":"The engine should try loading a resource from the cache."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestLoadingMethodType\/cache","url":"\/documentation\/mapboxmaps\/requestloadingmethodtype\/cache","kind":"symbol","type":"topic","title":"RequestLoadingMethodType.cache","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cache"}],"navigatorTitle":[{"kind":"identifier","text":"MBMRequestLoadingMethodTypeCache"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestResourceType":{"kind":"symbol","title":"RequestResourceType","navigatorTitle":[{"kind":"identifier","text":"RequestResourceType"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RequestResourceType"}],"url":"\/documentation\/mapboxmaps\/requestresourcetype","abstract":[{"text":"The enumeration defines the type of resource requested by the ","type":"text"},{"type":"codeVoice","code":"map"},{"type":"text","text":"."}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType","type":"topic"},"doc://com.mapbox.MapboxMaps/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceDataLoadedType":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SourceDataLoadedType","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/sourcedataloadedtype","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SourceDataLoadedType"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedType","kind":"symbol","title":"SourceDataLoadedType","type":"topic","abstract":[{"text":"The enumeration defines the type of loaded source data.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestDataSourceType":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"RequestDataSourceType","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/requestdatasourcetype","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"RequestDataSourceType"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestDataSourceType","kind":"symbol","title":"RequestDataSourceType","type":"topic","abstract":[{"text":"The enumeration defines the type of data source.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","type":"topic","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"title":"MapboxMaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"kind":"article","title":"Map events","abstract":[{"type":"text","text":"The simplified diagram of the events emitted by the map is displayed below."}],"type":"topic","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/events","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoadingErrorType":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/maploadingerrortype","title":"MapLoadingErrorType","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapLoadingErrorType","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"MapLoadingErrorType","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The enumeration defines map loading errors."}]},"doc://com.mapbox.MapboxMaps/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ"},"doc://com.mapbox.MapboxMaps/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SY"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestPriorityType":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RequestPriorityType"}],"url":"\/documentation\/mapboxmaps\/requestprioritytype","role":"symbol","navigatorTitle":[{"text":"RequestPriorityType","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestPriorityType","kind":"symbol","title":"RequestPriorityType","type":"topic","abstract":[{"text":"The enumeration defines the priority of a resource request.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","url":"\/documentation\/overview","title":"MapboxMaps Documentation","type":"topic","role":"collection","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderModeType":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RenderModeType"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderModeType","url":"\/documentation\/mapboxmaps\/rendermodetype","navigatorTitle":[{"text":"RenderModeType","kind":"identifier"}],"title":"RenderModeType","kind":"symbol","type":"topic","abstract":[{"text":"The enumeration defines the rendering mode for the rendered frame.","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"MBMRequestLoadingMethodType"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MBMRequestLoadingMethodType"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"MBMRequestLoadingMethodType","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestLoadingMethodType\/cache","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestLoadingMethodType\/network"],"anchor":"Enumeration-Cases","title":"Enumeration Cases"}]},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"value":[{"title":"Event payload","anchor":"Event-payload","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderModeType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestPriorityType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestDataSourceType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResponseSourceType"]}],"path":"\/seeAlsoSections","op":"replace"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MBMRequestLoadingMethodType","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"value":"MBMResponseSourceType","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResponseSourceType\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResponseSourceType\/fragments","value":[{"kind":"identifier","text":"MBMResponseSourceType"}],"op":"replace"},{"value":[{"kind":"identifier","text":"MBMResponseSourceType"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResponseSourceType\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestLoadingMethodType\/title","value":"MBMRequestLoadingMethodType","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestLoadingMethodType\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMRequestLoadingMethodType"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestLoadingMethodType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMRequestLoadingMethodType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestLoadingMethodType~1network\/title","value":"MBMRequestLoadingMethodTypeNetwork"},{"value":[{"text":"MBMRequestLoadingMethodTypeNetwork","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestLoadingMethodType~1network\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedType\/title","value":"MBMStyleDataLoadedType"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedType\/fragments","value":[{"text":"MBMStyleDataLoadedType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedType\/navigatorTitle","value":[{"text":"MBMStyleDataLoadedType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestLoadingMethodType~1cache\/title","value":"MBMRequestLoadingMethodTypeCache","op":"replace"},{"value":[{"text":"MBMRequestLoadingMethodTypeCache","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestLoadingMethodType~1cache\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestResourceType\/title","value":"MBMRequestResourceType"},{"value":[{"kind":"identifier","text":"MBMRequestResourceType"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestResourceType\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestResourceType\/navigatorTitle","value":[{"text":"MBMRequestResourceType","kind":"identifier"}],"op":"replace"},{"value":"MBMSourceDataLoadedType","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedType\/title"},{"value":[{"text":"MBMSourceDataLoadedType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedType\/fragments","op":"replace"},{"value":[{"text":"MBMSourceDataLoadedType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedType\/navigatorTitle","op":"replace"},{"value":"MBMRequestDataSourceType","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestDataSourceType\/title","op":"replace"},{"op":"replace","value":[{"text":"MBMRequestDataSourceType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestDataSourceType\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestDataSourceType\/navigatorTitle","value":[{"text":"MBMRequestDataSourceType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorType\/title","value":"MBMMapLoadingErrorType","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBMMapLoadingErrorType"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorType\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorType\/navigatorTitle","value":[{"text":"MBMMapLoadingErrorType","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestPriorityType\/title","value":"MBMRequestPriorityType"},{"value":[{"kind":"identifier","text":"MBMRequestPriorityType"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestPriorityType\/fragments"},{"op":"replace","value":[{"text":"MBMRequestPriorityType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestPriorityType\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderModeType\/title","value":"MBMRenderModeType","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderModeType\/fragments","value":[{"kind":"identifier","text":"MBMRenderModeType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderModeType\/navigatorTitle","value":[{"text":"MBMRenderModeType","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}