{"metadata":{"modules":[{"name":"MapboxMaps"}],"roleHeading":"Type Alias","navigatorTitle":[{"text":"StyleLoadedCallback","kind":"identifier"}],"symbolKind":"typealias","externalID":"c:MBMStyleLoadedCallback.h@T@MBMStyleLoadedCallback","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"StyleLoadedCallback","kind":"identifier"}],"title":"StyleLoadedCallback"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"seeAlsoSections":[{"anchor":"Symbols","title":"Symbols","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapRecorder","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeatureExtensionValue","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Size","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackError-swift.class","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestErrorType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapLoadingErrorTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRenderModeTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestDataSourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestErrorTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestLoadingMethodTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestPriorityTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestPriorityTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestResourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMResponseSourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMSourceDataLoadedTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStyleDataLoadedTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMTileStoreUsageModeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraChangedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GenericEventCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinishedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameStartedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequestCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceAddedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceRemovedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageMissingCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapIdleCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnusedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TransitionOptions-swift.class"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleLoadedCallback"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMapsInternal"]]},"abstract":[{"text":"The requested style has been fully loaded, including specified sprite, and sources’ metadata.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/styleloadedcallback"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/styleloadedcallback"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StyleLoadedCallback"},{"text":" = (","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleLoaded","text":"StyleLoaded","preciseIdentifier":"c:objc(cs)MBMStyleLoaded","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleLoaded":{"navigatorTitle":[{"text":"StyleLoaded","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StyleLoaded"}],"abstract":[{"text":"The requested style has been fully loaded, including specified sprite, and sources’ metadata.","type":"text"}],"title":"StyleLoaded","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleLoaded","kind":"symbol","url":"\/documentation\/mapboxmaps\/styleloaded"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRenderModeTypeToString(_:)":{"role":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRenderModeTypeToString(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"MBMRenderModeTypeToString","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@MBMRenderModeType","kind":"typeIdentifier","text":"RenderModeType"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"!","kind":"text"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/mbmrendermodetypetostring(_:)","navigatorTitle":[{"kind":"identifier","text":"MBMRenderModeTypeToString"}],"title":"MBMRenderModeTypeToString(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Size":{"title":"Size","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Size","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/size","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Size","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Size type."}],"navigatorTitle":[{"kind":"identifier","text":"Size"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMapsInternal":{"url":"\/documentation\/mapboxmaps\/coremapsinternal","type":"topic","role":"collectionGroup","title":"CoreMaps - Internal","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMapsInternal","abstract":[{"type":"text","text":"Maps rendering SDK also known as GL-Native. These are for internal use only."}],"kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleImageMissingCallback":{"url":"\/documentation\/mapboxmaps\/styleimagemissingcallback","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StyleImageMissingCallback","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"StyleImageMissingCallback","kind":"identifier"}],"title":"StyleImageMissingCallback","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageMissingCallback","abstract":[{"type":"text","text":"A style needs an image that is missing from the sprite sheet. This event is"},{"type":"text","text":" "},{"type":"text","text":"emitted when the "},{"code":"map","type":"codeVoice"},{"text":" renders visible tiles, and one of the required images","type":"text"},{"type":"text","text":" "},{"text":"is missing in the sprite sheet. The event observer has to provide the missing","type":"text"},{"type":"text","text":" "},{"type":"text","text":"image by calling the "},{"type":"codeVoice","code":"addStyleImage"},{"type":"text","text":" method."}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRequestResourceTypeToString(_:)":{"role":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestResourceTypeToString(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"MBMRequestResourceTypeToString","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@MBMRequestResourceType","text":"RequestResourceType","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"!"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/mbmrequestresourcetypetostring(_:)","navigatorTitle":[{"text":"MBMRequestResourceTypeToString","kind":"identifier"}],"title":"MBMRequestResourceTypeToString(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FeatureExtensionValue":{"url":"\/documentation\/mapboxmaps\/featureextensionvalue","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FeatureExtensionValue","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FeatureExtensionValue"}],"title":"FeatureExtensionValue","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeatureExtensionValue","abstract":[{"type":"text","text":"A value or a collection of a feature extension."}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRequestLoadingMethodTypeToString(_:)":{"role":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestLoadingMethodTypeToString(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBMRequestLoadingMethodTypeToString"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMRequestLoadingMethodType","text":"RequestLoadingMethodType"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/mbmrequestloadingmethodtypetostring(_:)","navigatorTitle":[{"text":"MBMRequestLoadingMethodTypeToString","kind":"identifier"}],"title":"MBMRequestLoadingMethodTypeToString(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceDataLoadedCallback":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"SourceDataLoaded"},{"type":"text","text":" event is emitted when source data is loaded."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedCallback","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SourceDataLoadedCallback","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/sourcedataloadedcallback","navigatorTitle":[{"text":"SourceDataLoadedCallback","kind":"identifier"}],"title":"SourceDataLoadedCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceRemovedCallback":{"url":"\/documentation\/mapboxmaps\/sourceremovedcallback","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"SourceRemovedCallback","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SourceRemovedCallback"}],"title":"SourceRemovedCallback","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceRemovedCallback","abstract":[{"type":"text","text":"The source has been removed with "},{"code":"removeStyleSource","type":"codeVoice"},{"type":"text","text":" method."}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GenericEventCallback":{"url":"\/documentation\/mapboxmaps\/genericeventcallback","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"GenericEventCallback","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GenericEventCallback"}],"title":"GenericEventCallback","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GenericEventCallback","abstract":[{"text":"Generic event for experimental events.","type":"text"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRequestPriorityTypeToString(_:)":{"url":"\/documentation\/mapboxmaps\/mbmrequestprioritytypetostring(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBMRequestPriorityTypeToString"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMRequestPriorityType","text":"RequestPriorityType"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"!"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"MBMRequestPriorityTypeToString","kind":"identifier"}],"title":"MBMRequestPriorityTypeToString(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestPriorityTypeToString(_:)","abstract":[],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMSourceDataLoadedTypeToString(_:)":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMSourceDataLoadedTypeToString(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"MBMSourceDataLoadedTypeToString","kind":"identifier"},{"kind":"text","text":"("},{"text":"SourceDataLoadedType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMSourceDataLoadedType"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"title":"MBMSourceDataLoadedTypeToString(_:)","abstract":[],"kind":"symbol","url":"\/documentation\/mapboxmaps\/mbmsourcedataloadedtypetostring(_:)","navigatorTitle":[{"kind":"identifier","text":"MBMSourceDataLoadedTypeToString"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleLoadedCallback":{"url":"\/documentation\/mapboxmaps\/styleloadedcallback","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"StyleLoadedCallback","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"StyleLoadedCallback","kind":"identifier"}],"title":"StyleLoadedCallback","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleLoadedCallback","abstract":[{"type":"text","text":"The requested style has been fully loaded, including specified sprite, and sources’ metadata."}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","url":"\/documentation\/overview","title":"MapboxMaps Documentation","type":"topic","role":"collection","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestErrorType":{"url":"\/documentation\/mapboxmaps\/requesterrortype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RequestErrorType","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"RequestErrorType","kind":"identifier"}],"title":"RequestErrorType","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestErrorType","abstract":[{"type":"text","text":"The enumeration defines the error type that may occur during a resource request."}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TransitionOptions-swift.class":{"navigatorTitle":[{"kind":"identifier","text":"TransitionOptions"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TransitionOptions","kind":"identifier"}],"title":"TransitionOptions","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"transition options"},{"text":" controls timing for the interpolation between a transitionable style","type":"text"},{"text":" ","type":"text"},{"text":"property’s previous value and new value. These can be used to define the style default property","type":"text"},{"type":"text","text":" "},{"type":"text","text":"transition behavior. Also, any transitionable style property may also have its own "},{"type":"codeVoice","code":"-transition"},{"type":"text","text":" "},{"type":"text","text":"property that defines specific transition timing for that specific layer property, overriding"},{"type":"text","text":" "},{"text":"the global transition values.","type":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/transitionoptions-swift.class","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TransitionOptions-swift.class","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRequestDataSourceTypeToString(_:)":{"role":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestDataSourceTypeToString(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBMRequestDataSourceTypeToString"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@MBMRequestDataSourceType","text":"RequestDataSourceType","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/mbmrequestdatasourcetypetostring(_:)","navigatorTitle":[{"kind":"identifier","text":"MBMRequestDataSourceTypeToString"}],"title":"MBMRequestDataSourceTypeToString(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceAddedCallback":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"The source has been added with "},{"type":"codeVoice","code":"addStyleSource"},{"type":"text","text":" method."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceAddedCallback","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SourceAddedCallback","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/sourceaddedcallback","navigatorTitle":[{"kind":"identifier","text":"SourceAddedCallback"}],"title":"SourceAddedCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMTileStoreUsageModeToString(_:)":{"url":"\/documentation\/mapboxmaps\/mbmtilestoreusagemodetostring(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBMTileStoreUsageModeToString"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@MBMTileStoreUsageMode","text":"TileStoreUsageMode","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"!","kind":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBMTileStoreUsageModeToString"}],"title":"MBMTileStoreUsageModeToString(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMTileStoreUsageModeToString(_:)","abstract":[],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapRecorder":{"url":"\/documentation\/mapboxmaps\/maprecorder","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapRecorder"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"MapRecorder","kind":"identifier"}],"title":"MapRecorder","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapRecorder","abstract":[{"type":"text","text":"MapRecorder provides functions to record and replay API calls of a Map instance."},{"type":"text","text":" "},{"type":"text","text":"These recordings can be used to debug issues which requie multiple steps to reproduce."},{"type":"text","text":" "},{"text":"Additionaly, playbacks can be used for performance testing custom scenarios.","type":"text"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleDataLoadedCallback":{"url":"\/documentation\/mapboxmaps\/styledataloadedcallback","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"StyleDataLoadedCallback","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"StyleDataLoadedCallback"}],"title":"StyleDataLoadedCallback","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedCallback","abstract":[{"type":"text","text":"The style data has been loaded."}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMStyleDataLoadedTypeToString(_:)":{"role":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStyleDataLoadedTypeToString(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"MBMStyleDataLoadedTypeToString","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"StyleDataLoadedType","preciseIdentifier":"c:@E@MBMStyleDataLoadedType"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"!"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/mbmstyledataloadedtypetostring(_:)","navigatorTitle":[{"kind":"identifier","text":"MBMStyleDataLoadedTypeToString"}],"title":"MBMStyleDataLoadedTypeToString(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","type":"topic","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"title":"MapboxMaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePackError-swift.class":{"role":"symbol","type":"topic","abstract":[{"text":"Describes a style package load request error.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackError-swift.class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StylePackError"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/stylepackerror-swift.class","navigatorTitle":[{"kind":"identifier","text":"StylePackError"}],"title":"StylePackError"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleImageRemoveUnusedCallback":{"url":"\/documentation\/mapboxmaps\/styleimageremoveunusedcallback","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"StyleImageRemoveUnusedCallback","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"StyleImageRemoveUnusedCallback","kind":"identifier"}],"title":"StyleImageRemoveUnusedCallback","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnusedCallback","abstract":[{"type":"text","text":"An image requested by the "},{"type":"codeVoice","code":"map"},{"type":"text","text":" through the "},{"code":"StyleImageMissing","type":"codeVoice"},{"type":"text","text":" event is no longer"},{"text":" ","type":"text"},{"text":"needed and can be removed using the ","type":"text"},{"code":"removeStyleImage","type":"codeVoice"},{"text":" method. The application can","type":"text"},{"type":"text","text":" "},{"type":"text","text":"decide whether the image should be kept or removed."}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMMapLoadingErrorTypeToString(_:)":{"role":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapLoadingErrorTypeToString(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"MBMMapLoadingErrorTypeToString","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MapLoadingErrorType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMMapLoadingErrorType"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"!"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/mbmmaploadingerrortypetostring(_:)","navigatorTitle":[{"text":"MBMMapLoadingErrorTypeToString","kind":"identifier"}],"title":"MBMMapLoadingErrorTypeToString(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRequestErrorTypeToString(_:)":{"navigatorTitle":[{"kind":"identifier","text":"MBMRequestErrorTypeToString"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestErrorTypeToString(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"MBMRequestErrorTypeToString","kind":"identifier"},{"text":"(","kind":"text"},{"text":"RequestErrorType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMRequestErrorType"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"!","kind":"text"}],"url":"\/documentation\/mapboxmaps\/mbmrequesterrortypetostring(_:)","type":"topic","title":"MBMRequestErrorTypeToString(_:)","abstract":[],"kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraChangedCallback":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"This event is emitted whenever the visible viewport changes its size"},{"type":"text","text":" "},{"text":"due to the invocation of the ","type":"text"},{"type":"codeVoice","code":"setSize"},{"type":"text","text":" and "},{"type":"codeVoice","code":"setBounds"},{"type":"text","text":" methods or when"},{"type":"text","text":" "},{"type":"text","text":"the camera is modified by calling camera methods. The event is emitted"},{"text":" ","type":"text"},{"text":"synchronously so that an updated camera state can be fetched immediately.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraChangedCallback","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CameraChangedCallback"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/camerachangedcallback","navigatorTitle":[{"text":"CameraChangedCallback","kind":"identifier"}],"title":"CameraChangedCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderFrameFinishedCallback":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"The "},{"code":"map","type":"codeVoice"},{"type":"text","text":" finished rendering a frame."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinishedCallback","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"RenderFrameFinishedCallback","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/renderframefinishedcallback","navigatorTitle":[{"text":"RenderFrameFinishedCallback","kind":"identifier"}],"title":"RenderFrameFinishedCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderFrameStartedCallback":{"url":"\/documentation\/mapboxmaps\/renderframestartedcallback","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RenderFrameStartedCallback","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"RenderFrameStartedCallback","kind":"identifier"}],"title":"RenderFrameStartedCallback","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameStartedCallback","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"map"},{"type":"text","text":" started rendering a frame."}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapIdleCallback":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapIdleCallback","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"MapIdleCallback","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"MapIdleCallback","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/mapidlecallback","role":"symbol","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"map"},{"text":" has entered the idle state. The ","type":"text"},{"type":"codeVoice","code":"map"},{"type":"text","text":" is idle when there are no ongoing"},{"type":"text","text":" "},{"text":"animations, transitions and the ","type":"text"},{"code":"map","type":"codeVoice"},{"text":" has rendered all requested non-volatile tiles","type":"text"},{"type":"text","text":" "},{"type":"text","text":"(e.g., live traffic tiles). The event will not be emitted if "},{"type":"codeVoice","code":"setUserAnimationInProgress"},{"type":"text","text":" "},{"type":"text","text":"and \/ or "},{"type":"codeVoice","code":"setGestureInProgress"},{"text":" is set to ","type":"text"},{"code":"true","type":"codeVoice"},{"type":"text","text":"."}],"title":"MapIdleCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoadedCallback":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadedCallback","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapLoadedCallback"}],"title":"MapLoadedCallback","abstract":[{"text":"The style has been fully loaded, and the ","type":"text"},{"type":"codeVoice","code":"map"},{"type":"text","text":" has rendered all visible tiles."},{"type":"text","text":" "},{"type":"text","text":"The event will be emitted only once for the current style. If it is required to"},{"type":"text","text":" "},{"type":"text","text":"continuously observe an event where all the necessary resources are loaded or rendered,"},{"text":" ","type":"text"},{"text":"please check the following events: ","type":"text"},{"code":"MapIdle","type":"codeVoice"},{"type":"text","text":", "},{"code":"StyleDataLoaded","type":"codeVoice"},{"type":"text","text":", and "},{"code":"RenderFrameFinished","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/maploadedcallback","navigatorTitle":[{"kind":"identifier","text":"MapLoadedCallback"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMResponseSourceTypeToString(_:)":{"url":"\/documentation\/mapboxmaps\/mbmresponsesourcetypetostring(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBMResponseSourceTypeToString"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@MBMResponseSourceType","kind":"typeIdentifier","text":"ResponseSourceType"},{"kind":"text","text":") -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"MBMResponseSourceTypeToString","kind":"identifier"}],"title":"MBMResponseSourceTypeToString(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMResponseSourceTypeToString(_:)","abstract":[],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResourceRequestCallback":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ResourceRequest"},{"type":"text","text":" event allows the application to observe resourcerequests"},{"type":"text","text":" "},{"text":"made by a ","type":"text"},{"code":"map","type":"codeVoice"},{"text":" or ","type":"text"},{"code":"map snapshotter","type":"codeVoice"},{"type":"text","text":" object."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequestCallback","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"ResourceRequestCallback","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/resourcerequestcallback","navigatorTitle":[{"text":"ResourceRequestCallback","kind":"identifier"}],"title":"ResourceRequestCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoadingErrorCallback":{"role":"symbol","type":"topic","abstract":[{"text":"Describes an error that has occurred while loading the ","type":"text"},{"type":"codeVoice","code":"map"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorCallback","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapLoadingErrorCallback"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/maploadingerrorcallback","navigatorTitle":[{"kind":"identifier","text":"MapLoadingErrorCallback"}],"title":"MapLoadingErrorCallback"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Alias"},{"path":"\/metadata\/title","value":"MBMStyleLoadedCallback","op":"replace"},{"value":"typealias","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MBMStyleLoadedCallback"}],"op":"replace"},{"value":[{"kind":"identifier","text":"MBMStyleLoadedCallback"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"replace","value":[{"anchor":"Symbols","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapRecorder","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeatureExtensionValue","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Size","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackError-swift.class","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestErrorType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapLoadingErrorTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRenderModeTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestDataSourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestErrorTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestLoadingMethodTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestPriorityTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestPriorityTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestResourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMResponseSourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMSourceDataLoadedTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStyleDataLoadedTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMTileStoreUsageModeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraChangedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GenericEventCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinishedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameStartedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequestCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceAddedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceRemovedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageMissingCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapIdleCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnusedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TransitionOptions-swift.class"],"generated":true,"title":"Symbols"}],"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"void (^)(MBMStyleLoaded *)","preciseIdentifier":"c:BFv(#*$objc(cs)MBMStyleLoaded)"},{"text":" ","kind":"text"},{"text":"MBMStyleLoadedCallback","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoaded\/title","value":"MBMStyleLoaded"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoaded\/fragments","value":[{"kind":"identifier","text":"MBMStyleLoaded"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoaded\/navigatorTitle","value":[{"text":"MBMStyleLoaded","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRenderModeTypeToString(_:)\/title","value":"MBMRenderModeTypeToString","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRenderModeTypeToString(_:)\/fragments","value":[{"kind":"identifier","text":"MBMRenderModeTypeToString"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Size\/title","value":"MBMSize","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Size\/fragments","value":[{"text":"MBMSize","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Size\/navigatorTitle","value":[{"text":"MBMSize","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageMissingCallback\/title","op":"replace","value":"MBMStyleImageMissingCallback"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageMissingCallback\/fragments","op":"replace","value":[{"text":"MBMStyleImageMissingCallback","kind":"identifier"}]},{"value":[{"text":"MBMStyleImageMissingCallback","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageMissingCallback\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestResourceTypeToString(_:)\/title","value":"MBMRequestResourceTypeToString","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestResourceTypeToString(_:)\/fragments","value":[{"text":"MBMRequestResourceTypeToString","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeatureExtensionValue\/title","op":"replace","value":"MBMFeatureExtensionValue"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeatureExtensionValue\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMFeatureExtensionValue"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeatureExtensionValue\/navigatorTitle","value":[{"text":"MBMFeatureExtensionValue","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestLoadingMethodTypeToString(_:)\/title","value":"MBMRequestLoadingMethodTypeToString"},{"value":[{"text":"MBMRequestLoadingMethodTypeToString","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestLoadingMethodTypeToString(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedCallback\/title","value":"MBMSourceDataLoadedCallback"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedCallback\/fragments","op":"replace","value":[{"text":"MBMSourceDataLoadedCallback","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedCallback\/navigatorTitle","op":"replace","value":[{"text":"MBMSourceDataLoadedCallback","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceRemovedCallback\/title","value":"MBMSourceRemovedCallback","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBMSourceRemovedCallback"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceRemovedCallback\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceRemovedCallback\/navigatorTitle","value":[{"text":"MBMSourceRemovedCallback","kind":"identifier"}],"op":"replace"},{"value":"MBMGenericEventCallback","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEventCallback\/title"},{"value":[{"text":"MBMGenericEventCallback","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEventCallback\/fragments"},{"value":[{"text":"MBMGenericEventCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEventCallback\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestPriorityTypeToString(_:)\/title","value":"MBMRequestPriorityTypeToString","op":"replace"},{"op":"replace","value":[{"text":"MBMRequestPriorityTypeToString","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestPriorityTypeToString(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMSourceDataLoadedTypeToString(_:)\/title","op":"replace","value":"MBMSourceDataLoadedTypeToString"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMSourceDataLoadedTypeToString(_:)\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMSourceDataLoadedTypeToString"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoadedCallback\/title","op":"replace","value":"MBMStyleLoadedCallback"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoadedCallback\/fragments","value":[{"text":"MBMStyleLoadedCallback","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoadedCallback\/navigatorTitle","value":[{"text":"MBMStyleLoadedCallback","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestErrorType\/title","value":"MBMRequestErrorType"},{"op":"replace","value":[{"text":"MBMRequestErrorType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestErrorType\/fragments"},{"value":[{"text":"MBMRequestErrorType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestErrorType\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TransitionOptions-swift.class\/title","value":"MBMTransitionOptions","op":"replace"},{"value":[{"kind":"identifier","text":"MBMTransitionOptions"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TransitionOptions-swift.class\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TransitionOptions-swift.class\/navigatorTitle","value":[{"text":"MBMTransitionOptions","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"MBMRequestDataSourceTypeToString","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestDataSourceTypeToString(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestDataSourceTypeToString(_:)\/fragments","value":[{"text":"MBMRequestDataSourceTypeToString","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAddedCallback\/title","op":"replace","value":"MBMSourceAddedCallback"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAddedCallback\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMSourceAddedCallback"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAddedCallback\/navigatorTitle","op":"replace","value":[{"text":"MBMSourceAddedCallback","kind":"identifier"}]},{"value":"MBMTileStoreUsageModeToString","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMTileStoreUsageModeToString(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMTileStoreUsageModeToString(_:)\/fragments","value":[{"kind":"identifier","text":"MBMTileStoreUsageModeToString"}]},{"value":"MBMMapRecorder","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapRecorder\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapRecorder\/fragments","value":[{"text":"MBMMapRecorder","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"MBMMapRecorder"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapRecorder\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedCallback\/title","value":"MBMStyleDataLoadedCallback","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedCallback\/fragments","value":[{"kind":"identifier","text":"MBMStyleDataLoadedCallback"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedCallback\/navigatorTitle","value":[{"text":"MBMStyleDataLoadedCallback","kind":"identifier"}],"op":"replace"},{"value":"MBMStyleDataLoadedTypeToString","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMStyleDataLoadedTypeToString(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMStyleDataLoadedTypeToString(_:)\/fragments","value":[{"kind":"identifier","text":"MBMStyleDataLoadedTypeToString"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackError-swift.class\/title","value":"MBMStylePackError"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackError-swift.class\/fragments","op":"replace","value":[{"text":"MBMStylePackError","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackError-swift.class\/navigatorTitle","value":[{"kind":"identifier","text":"MBMStylePackError"}],"op":"replace"},{"value":"MBMStyleImageRemoveUnusedCallback","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnusedCallback\/title"},{"value":[{"kind":"identifier","text":"MBMStyleImageRemoveUnusedCallback"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnusedCallback\/fragments"},{"op":"replace","value":[{"text":"MBMStyleImageRemoveUnusedCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnusedCallback\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMMapLoadingErrorTypeToString(_:)\/title","value":"MBMMapLoadingErrorTypeToString"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMMapLoadingErrorTypeToString(_:)\/fragments","op":"replace","value":[{"text":"MBMMapLoadingErrorTypeToString","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestErrorTypeToString(_:)\/title","value":"MBMRequestErrorTypeToString","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestErrorTypeToString(_:)\/fragments","value":[{"text":"MBMRequestErrorTypeToString","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChangedCallback\/title","op":"replace","value":"MBMCameraChangedCallback"},{"value":[{"text":"MBMCameraChangedCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChangedCallback\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBMCameraChangedCallback"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChangedCallback\/navigatorTitle"},{"value":"MBMRenderFrameFinishedCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinishedCallback\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinishedCallback\/fragments","value":[{"text":"MBMRenderFrameFinishedCallback","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBMRenderFrameFinishedCallback"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinishedCallback\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameStartedCallback\/title","value":"MBMRenderFrameStartedCallback"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameStartedCallback\/fragments","value":[{"kind":"identifier","text":"MBMRenderFrameStartedCallback"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameStartedCallback\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMRenderFrameStartedCallback"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdleCallback\/title","op":"replace","value":"MBMMapIdleCallback"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdleCallback\/fragments","op":"replace","value":[{"text":"MBMMapIdleCallback","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MBMMapIdleCallback"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdleCallback\/navigatorTitle"},{"value":"MBMMapLoadedCallback","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadedCallback\/title"},{"value":[{"kind":"identifier","text":"MBMMapLoadedCallback"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadedCallback\/fragments"},{"op":"replace","value":[{"text":"MBMMapLoadedCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadedCallback\/navigatorTitle"},{"op":"replace","value":"MBMResponseSourceTypeToString","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMResponseSourceTypeToString(_:)\/title"},{"value":[{"kind":"identifier","text":"MBMResponseSourceTypeToString"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMResponseSourceTypeToString(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequestCallback\/title","value":"MBMResourceRequestCallback","op":"replace"},{"value":[{"kind":"identifier","text":"MBMResourceRequestCallback"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequestCallback\/fragments","op":"replace"},{"value":[{"text":"MBMResourceRequestCallback","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequestCallback\/navigatorTitle"},{"op":"replace","value":"MBMMapLoadingErrorCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorCallback\/title"},{"value":[{"text":"MBMMapLoadingErrorCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorCallback\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBMMapLoadingErrorCallback"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorCallback\/navigatorTitle"}]}]}