{"seeAlsoSections":[{"title":"Style pack","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleObjectInfo","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePack","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackError-swift.enum","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadProgress"],"generated":true,"anchor":"Style-pack"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/stylepackloadoptions"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/stylepackloadoptions"]}],"topicSections":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadOptions\/acceptExpired","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadOptions\/extraOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadOptions\/metadata"],"generated":true}],"metadata":{"externalID":"c:objc(cs)MBMStylePackLoadOptions","title":"StylePackLoadOptions","symbolKind":"class","roleHeading":"Class","modules":[{"name":"MapboxMaps"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"StylePackLoadOptions"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StylePackLoadOptions"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Describes the style package load option values."}],"kind":"symbol","identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadOptions","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StylePackLoadOptions","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH"],"type":"conformsTo"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMStylePackLoadOptions/initWithGlyphsRasterizationMode:metadata:extraOptions:":{"abstract":[],"navigatorTitle":[{"text":"initWithGlyphsRasterizationMode:metadata:extraOptions:","kind":"identifier"}],"title":"initWithGlyphsRasterizationMode:metadata:extraOptions:","type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStylePackLoadOptions\/initWithGlyphsRasterizationMode:metadata:extraOptions:","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithGlyphsRasterizationMode:metadata:extraOptions:","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/mbmstylepackloadoptions\/initwithglyphsrasterizationmode:metadata:extraoptions:"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePackLoadOptions/acceptExpired":{"title":"acceptExpired","type":"topic","navigatorTitle":[{"kind":"identifier","text":"acceptExpired"}],"abstract":[{"text":"Accepts expired data when loading style resources.","type":"text"}],"url":"\/documentation\/mapboxmaps\/stylepackloadoptions\/acceptexpired","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadOptions\/acceptExpired","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"acceptExpired","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePackLoadOptions/metadata":{"abstract":[{"text":"A custom Mapbox value associated with this style package for storing metadata.","type":"text"}],"title":"metadata","type":"topic","url":"\/documentation\/mapboxmaps\/stylepackloadoptions\/metadata","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadOptions\/metadata","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"metadata"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"metadata"},{"kind":"text","text":": "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePackLoadOptions":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"StylePackLoadOptions"}],"abstract":[{"type":"text","text":"Describes the style package load option values."}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadOptions","title":"StylePackLoadOptions","url":"\/documentation\/mapboxmaps\/stylepackloadoptions","navigatorTitle":[{"kind":"identifier","text":"StylePackLoadOptions"}],"role":"symbol","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","type":"topic","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"title":"MapboxMaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject","title":"NSObject"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePack":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StylePack"}],"navigatorTitle":[{"kind":"identifier","text":"StylePack"}],"kind":"symbol","role":"symbol","abstract":[{"text":"The ","type":"text"},{"code":"style pack","type":"codeVoice"},{"type":"text","text":" represents a stored style package."}],"url":"\/documentation\/mapboxmaps\/stylepack","title":"StylePack"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePackLoadProgress":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StylePackLoadProgress"}],"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"style pack load"},{"type":"text","text":" progress includes information about"},{"text":" ","type":"text"},{"text":"the number of resources that have completed downloading","type":"text"},{"type":"text","text":" "},{"type":"text","text":"and the total number of resources that are required."}],"navigatorTitle":[{"text":"StylePackLoadProgress","kind":"identifier"}],"title":"StylePackLoadProgress","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadProgress","url":"\/documentation\/mapboxmaps\/stylepackloadprogress","role":"symbol","kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePackLoadOptions/extraOptions":{"title":"extraOptions","type":"topic","navigatorTitle":[{"text":"extraOptions","kind":"identifier"}],"abstract":[{"type":"text","text":"Extra style package load options."}],"url":"\/documentation\/mapboxmaps\/stylepackloadoptions\/extraoptions","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadOptions\/extraOptions","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"extraOptions","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePackError-swift.enum":{"url":"\/documentation\/mapboxmaps\/stylepackerror-swift.enum","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"StylePackError"}],"abstract":[{"text":"Describes the reason for a style package download request failure.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StylePackError"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackError-swift.enum","kind":"symbol","title":"StylePackError"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMStylePackLoadOptions/initWithGlyphsRasterizationMode:metadata:acceptExpired:extraOptions:":{"abstract":[],"navigatorTitle":[{"text":"initWithGlyphsRasterizationMode:metadata:acceptExpired:extraOptions:","kind":"identifier"}],"title":"initWithGlyphsRasterizationMode:metadata:acceptExpired:extraOptions:","type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStylePackLoadOptions\/initWithGlyphsRasterizationMode:metadata:acceptExpired:extraOptions:","role":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"initWithGlyphsRasterizationMode:metadata:acceptExpired:extraOptions:","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/mbmstylepackloadoptions\/initwithglyphsrasterizationmode:metadata:acceptexpired:extraoptions:"},"doc://com.mapbox.MapboxMaps/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/SH":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/objc(pl)NSObject":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/SQ":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","url":"\/documentation\/mapboxmaps\/tilestore-apis","title":"TileStore APIs","abstract":[],"kind":"article","type":"topic","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/s7CVarArgP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","url":"\/documentation\/overview","title":"MapboxMaps Documentation","type":"topic","role":"collection","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleObjectInfo":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StyleObjectInfo"}],"abstract":[{"type":"text","text":"The information about style object (source or layer or light)."}],"navigatorTitle":[{"text":"StyleObjectInfo","kind":"identifier"}],"title":"StyleObjectInfo","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleObjectInfo","url":"\/documentation\/mapboxmaps\/styleobjectinfo","role":"symbol","kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMStylePackLoadOptions/glyphsRasterizationMode":{"title":"glyphsRasterizationMode","type":"topic","abstract":[{"text":"Specifies glyphs rasterization mode.","type":"text"}],"url":"\/documentation\/mapboxmaps\/mbmstylepackloadoptions\/glyphsrasterizationmode","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStylePackLoadOptions\/glyphsRasterizationMode","role":"symbol","fragments":[{"kind":"identifier","text":"glyphsRasterizationMode"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","value":"MBMStylePackLoadOptions","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"value":[{"text":"MBMStylePackLoadOptions","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"MBMStylePackLoadOptions","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStylePackLoadOptions\/glyphsRasterizationMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadOptions\/acceptExpired","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadOptions\/extraOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadOptions\/metadata"],"generated":true},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStylePackLoadOptions\/initWithGlyphsRasterizationMode:metadata:acceptExpired:extraOptions:","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStylePackLoadOptions\/initWithGlyphsRasterizationMode:metadata:extraOptions:"]}]},{"path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"]}],"op":"replace"},{"value":[{"generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleObjectInfo","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePack","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadProgress"],"anchor":"Style-pack","title":"Style pack"}],"path":"\/seeAlsoSections","op":"replace"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBMStylePackLoadOptions"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadOptions~1acceptExpired\/title","op":"replace","value":"acceptExpired"},{"value":[{"text":"acceptExpired","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadOptions~1acceptExpired\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadOptions~1metadata\/title","value":"metadata"},{"value":[{"kind":"identifier","text":"metadata"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadOptions~1metadata\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadOptions\/title","value":"MBMStylePackLoadOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadOptions\/fragments","value":[{"kind":"identifier","text":"MBMStylePackLoadOptions"}]},{"value":[{"text":"MBMStylePackLoadOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadOptions\/navigatorTitle"},{"value":"MBMStylePack","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePack\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBMStylePack"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePack\/fragments"},{"value":[{"text":"MBMStylePack","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePack\/navigatorTitle"},{"value":"MBMStylePackLoadProgress","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadProgress\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadProgress\/fragments","value":[{"text":"MBMStylePackLoadProgress","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadProgress\/navigatorTitle","value":[{"kind":"identifier","text":"MBMStylePackLoadProgress"}],"op":"replace"},{"op":"replace","value":"extraOptions","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadOptions~1extraOptions\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadOptions~1extraOptions\/fragments","value":[{"kind":"identifier","text":"extraOptions"}]},{"op":"replace","value":"MBMStyleObjectInfo","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleObjectInfo\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleObjectInfo\/fragments","value":[{"text":"MBMStyleObjectInfo","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleObjectInfo\/navigatorTitle","value":[{"text":"MBMStyleObjectInfo","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}