{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs"]]},"abstract":[{"type":"text","text":"Describes the reason for a tile region download request failure."}],"variants":[{"paths":["\/documentation\/mapboxmaps\/tileregionerror"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileRegionError","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TileRegionError"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileRegionError"}],"symbolKind":"enum","externalID":"s:10MapboxMaps15TileRegionErrorO","title":"TileRegionError","modules":[{"name":"MapboxMaps"}],"navigatorTitle":[{"text":"TileRegionError","kind":"identifier"}],"role":"symbol","roleHeading":"Enumeration"},"seeAlsoSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStoreOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudget","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInMegabytes","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInTiles","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCoverOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegion","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgress","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TilesetDescriptor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TilesetDescriptorOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgressCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreUsageMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileDataDomain","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgress","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateResult","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgressCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingErrorType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClearCacheError"],"generated":true,"anchor":"TileStore","title":"TileStore"}],"sections":[],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileRegionError\/canceled(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileRegionError\/diskFull(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileRegionError\/doesNotExist(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileRegionError\/other(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileRegionError\/tileCountExceeded(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileRegionError\/tilesetDescriptor(_:)"],"generated":true,"anchor":"Enumeration-Cases"},{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileRegionError\/errorDescription"]},{"anchor":"Default-Implementations","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileRegionError\/Equatable-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileRegionError\/Error-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileRegionError\/LocalizedError-Implementations"],"generated":true,"title":"Default Implementations"}],"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/10Foundation14LocalizedErrorP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/s5ErrorP","doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"],"type":"conformsTo","kind":"relationships"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileRegionError/other(_:)":{"role":"symbol","abstract":[{"type":"text","text":"Some other failure reason."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileRegionError\/other(_:)","url":"\/documentation\/mapboxmaps\/tileregionerror\/other(_:)","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"other","kind":"identifier"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"TileRegionError.other(_:)","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateProgressCallback":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"TileRegionEstimateProgressCallback"}],"kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileRegionEstimateProgressCallback"}],"title":"TileRegionEstimateProgressCallback","role":"symbol","url":"\/documentation\/mapboxcommon\/tileregionestimateprogresscallback","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgressCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileRegionError/tileCountExceeded(_:)":{"abstract":[{"type":"text","text":"The region contains more tiles than allowed"}],"url":"\/documentation\/mapboxmaps\/tileregionerror\/tilecountexceeded(_:)","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"tileCountExceeded","kind":"identifier"},{"kind":"text","text":"("},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileRegionError\/tileCountExceeded(_:)","kind":"symbol","role":"symbol","title":"TileRegionError.tileCountExceeded(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileRegionError/diskFull(_:)":{"role":"symbol","abstract":[{"type":"text","text":"There is no available space to store the resources."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileRegionError\/diskFull(_:)","url":"\/documentation\/mapboxmaps\/tileregionerror\/diskfull(_:)","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"diskFull","kind":"identifier"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"TileRegionError.diskFull(_:)","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadOptions":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Describes the tile region load option values."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions","url":"\/documentation\/mapboxcommon\/tileregionloadoptions","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileRegionLoadOptions"}],"navigatorTitle":[{"text":"TileRegionLoadOptions","kind":"identifier"}],"title":"TileRegionLoadOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileRegionError/Equatable-Implementations":{"abstract":[],"title":"Equatable Implementations","type":"topic","url":"\/documentation\/mapboxmaps\/tileregionerror\/equatable-implementations","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileRegionError\/Equatable-Implementations","kind":"article","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TilesetDescriptor":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"A bundle that encapsulates tilesets creation for the tile store implementation."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TilesetDescriptor","url":"\/documentation\/mapboxcommon\/tilesetdescriptor","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TilesetDescriptor"}],"navigatorTitle":[{"text":"TilesetDescriptor","kind":"identifier"}],"title":"TilesetDescriptor"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileRegionError/canceled(_:)":{"role":"symbol","abstract":[{"type":"text","text":"The operation was canceled."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileRegionError\/canceled(_:)","url":"\/documentation\/mapboxmaps\/tileregionerror\/canceled(_:)","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"canceled"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"title":"TileRegionError.canceled(_:)","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileOptions":{"url":"\/documentation\/mapboxmaps\/tileoptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileOptions","navigatorTitle":[{"text":"TileOptions","kind":"identifier"}],"abstract":[{"type":"text","text":"Options for custom geometry tiles."}],"type":"topic","role":"symbol","title":"TileOptions","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TileOptions"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileStore":{"url":"\/documentation\/mapboxcommon\/tilestore","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore","navigatorTitle":[{"kind":"identifier","text":"TileStore"}],"abstract":[{"text":"TileStore manages downloads and storage for requests to tile-related API endpoints, enforcing a disk usage","type":"text"},{"type":"text","text":" "},{"text":"quota: tiles available on disk may be deleted to make room for a new download. This interface can be used by an","type":"text"},{"text":" ","type":"text"},{"text":"app developer to set the disk quota. The rest of TileStore API is intended for native SDK consumption only.","type":"text"}],"type":"topic","role":"symbol","title":"TileStore","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileStore","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegion":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegion","abstract":[{"text":"TileRegion represents an identifiable geographic tile region with metadata","type":"text"}],"type":"topic","kind":"symbol","title":"TileRegion","url":"\/documentation\/mapboxcommon\/tileregion","navigatorTitle":[{"kind":"identifier","text":"TileRegion"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileRegion","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileRegionError/LocalizedError-Implementations":{"title":"LocalizedError Implementations","url":"\/documentation\/mapboxmaps\/tileregionerror\/localizederror-implementations","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileRegionError\/LocalizedError-Implementations","role":"collectionGroup","type":"topic","kind":"article","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudgetInMegabytes":{"title":"TileCacheBudgetInMegabytes","kind":"symbol","abstract":[{"text":"Tile cache budget in megabytes.","type":"text"}],"type":"topic","url":"\/documentation\/mapboxmaps\/tilecachebudgetinmegabytes","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInMegabytes","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TileCacheBudgetInMegabytes"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TileCacheBudgetInMegabytes"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ClearCacheError":{"type":"topic","navigatorTitle":[{"text":"ClearCacheError","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClearCacheError"}],"title":"ClearCacheError","role":"symbol","url":"\/documentation\/mapboxmaps\/clearcacheerror","abstract":[{"type":"text","text":"Describes the reason for a cache clearing failure."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClearCacheError"},"doc://com.mapbox.MapboxMaps/10Foundation14LocalizedErrorP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/10Foundation14LocalizedErrorP","title":"Foundation.LocalizedError"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateProgress":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"A tile region’s estimate progress includes counts of the number of resources that have"},{"type":"text","text":" "},{"text":"been estimated and the total number of resources as well as a partial result with the","type":"text"},{"type":"text","text":" "},{"text":"current estimate, calculated using the data available at the moment.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgress","url":"\/documentation\/mapboxcommon\/tileregionestimateprogress","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileRegionEstimateProgress","kind":"identifier"}],"navigatorTitle":[{"text":"TileRegionEstimateProgress","kind":"identifier"}],"title":"TileRegionEstimateProgress"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileRegionError/doesNotExist(_:)":{"url":"\/documentation\/mapboxmaps\/tileregionerror\/doesnotexist(_:)","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"doesNotExist"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileRegionError\/doesNotExist(_:)","role":"symbol","title":"TileRegionError.doesNotExist(_:)","abstract":[{"type":"text","text":"The tile region does not exist."}],"type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s8SendableP","title":"Swift.Sendable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudgetInTiles":{"type":"topic","role":"symbol","abstract":[{"text":"Tile cache budget in tiles.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInTiles","url":"\/documentation\/mapboxmaps\/tilecachebudgetintiles","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileCacheBudgetInTiles"}],"navigatorTitle":[{"kind":"identifier","text":"TileCacheBudgetInTiles"}],"title":"TileCacheBudgetInTiles"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileRegionError":{"type":"topic","role":"symbol","abstract":[{"text":"Describes the reason for a tile region download request failure.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileRegionError","url":"\/documentation\/mapboxmaps\/tileregionerror","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"TileRegionError","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"TileRegionError"}],"title":"TileRegionError"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudgetType":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetType","url":"\/documentation\/mapboxmaps\/tilecachebudgettype","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TileCacheBudgetType"}],"abstract":[],"title":"TileCacheBudgetType","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TileCacheBudgetType"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TilesetDescriptorOptions":{"abstract":[{"type":"text","text":"Describes the tileset descriptor option values."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TilesetDescriptorOptions","kind":"identifier"}],"navigatorTitle":[{"text":"TilesetDescriptorOptions","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/mapboxmaps\/tilesetdescriptoroptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TilesetDescriptorOptions","title":"TilesetDescriptorOptions","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCoverOptions":{"title":"TileCoverOptions","tags":[{"type":"spi","text":"SPI"}],"url":"\/documentation\/mapboxmaps\/tilecoveroptions","type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCoverOptions","navigatorTitle":[{"text":"TileCoverOptions","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"TileCoverOptions","kind":"identifier"}],"abstract":[{"type":"text","text":"Various options needed for tile cover."}]},"doc://com.mapbox.MapboxMaps/s5ErrorP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s5ErrorP","title":"Swift.Error"},"doc://com.mapbox.MapboxMaps/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","title":"Swift.Equatable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","url":"\/documentation\/mapboxmaps\/tilestore-apis","title":"TileStore APIs","abstract":[],"kind":"article","type":"topic","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStoreObserver":{"type":"topic","navigatorTitle":[{"text":"TileStoreObserver","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileStoreObserver","kind":"identifier"}],"title":"TileStoreObserver","role":"symbol","url":"\/documentation\/mapboxmaps\/tilestoreobserver","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreObserver"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadProgress":{"url":"\/documentation\/mapboxcommon\/tileregionloadprogress","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TileRegionLoadProgress"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"TileRegionLoadProgress","kind":"identifier"}],"title":"TileRegionLoadProgress","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgress","abstract":[{"type":"text","text":"A tile region’s load progress includes counts"},{"type":"text","text":" "},{"text":"of the number of resources that have completed downloading","type":"text"},{"type":"text","text":" "},{"type":"text","text":"and the total number of resources that are required."}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudget":{"title":"TileCacheBudget","kind":"symbol","abstract":[],"url":"\/documentation\/mapboxmaps\/tilecachebudget","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudget","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TileCacheBudget","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"TileCacheBudget","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileStoreOptions":{"type":"topic","navigatorTitle":[{"text":"TileStoreOptions","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileStoreOptions"}],"title":"TileStoreOptions","role":"symbol","url":"\/documentation\/mapboxcommon\/tilestoreoptions","abstract":[{"type":"text","text":"These constants can be used as keys for TileStore::setOption to configure further aspects of a TileStore instance."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStoreOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadProgressCallback":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"TileRegionLoadProgressCallback"}],"kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileRegionLoadProgressCallback"}],"title":"TileRegionLoadProgressCallback","role":"symbol","url":"\/documentation\/mapboxcommon\/tileregionloadprogresscallback","abstract":[{"text":"Callback Invoked to report the progess of the tile region loading operation.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgressCallback"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","url":"\/documentation\/overview","title":"MapboxMaps Documentation","type":"topic","role":"collection","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/CacheClearingError":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Describes a cache clearing error."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingError","url":"\/documentation\/mapboxcommon\/cacheclearingerror","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"CacheClearingError","kind":"identifier"}],"navigatorTitle":[{"text":"CacheClearingError","kind":"identifier"}],"title":"CacheClearingError"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/CacheClearingErrorType":{"abstract":[{"text":"Describes the reason for a cache clearing failure.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingErrorType","kind":"symbol","type":"topic","navigatorTitle":[{"text":"CacheClearingErrorType","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/cacheclearingerrortype","title":"CacheClearingErrorType","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CacheClearingErrorType","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileDataDomain":{"abstract":[{"text":"Describes the tiles data domain.","type":"text"}],"type":"topic","url":"\/documentation\/mapboxcommon\/tiledatadomain","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileDataDomain","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileDataDomain","kind":"identifier"}],"navigatorTitle":[{"text":"TileDataDomain","kind":"identifier"}],"title":"TileDataDomain"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStoreUsageMode":{"type":"topic","role":"symbol","abstract":[{"text":"Describes tile store usage modes.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreUsageMode","url":"\/documentation\/mapboxmaps\/tilestoreusagemode","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileStoreUsageMode","kind":"identifier"}],"navigatorTitle":[{"text":"TileStoreUsageMode","kind":"identifier"}],"title":"TileStoreUsageMode"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileRegionError/errorDescription":{"abstract":[],"url":"\/documentation\/mapboxmaps\/tileregionerror\/errordescription","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"errorDescription"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileRegionError\/errorDescription","kind":"symbol","role":"symbol","title":"errorDescription"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileRegionError/tilesetDescriptor(_:)":{"kind":"symbol","abstract":[{"text":"Resolving the tileset descriptors failed.","type":"text"}],"title":"TileRegionError.tilesetDescriptor(_:)","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"tilesetDescriptor","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileRegionError\/tilesetDescriptor(_:)","url":"\/documentation\/mapboxmaps\/tileregionerror\/tilesetdescriptor(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileRegionError/Error-Implementations":{"abstract":[],"kind":"article","title":"Error Implementations","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileRegionError\/Error-Implementations","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/tileregionerror\/error-implementations","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateOptions":{"type":"topic","role":"symbol","abstract":[{"text":"Holds options for the tile region estimation operation.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateOptions","url":"\/documentation\/mapboxcommon\/tileregionestimateoptions","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TileRegionEstimateOptions","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"TileRegionEstimateOptions"}],"title":"TileRegionEstimateOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateResult":{"type":"topic","navigatorTitle":[{"text":"TileRegionEstimateResult","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TileRegionEstimateResult","kind":"identifier"}],"title":"TileRegionEstimateResult","role":"symbol","url":"\/documentation\/mapboxcommon\/tileregionestimateresult","abstract":[{"type":"text","text":"The result of tile region estim"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateResult"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CanonicalTileID":{"abstract":[{"text":"Represents a tile coordinate.","type":"text"}],"url":"\/documentation\/mapboxmaps\/canonicaltileid","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CanonicalTileID","kind":"identifier"}],"navigatorTitle":[{"text":"CanonicalTileID","kind":"identifier"}],"type":"topic","title":"CanonicalTileID","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID","kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","type":"topic","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"title":"MapboxMaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"}},"variantOverrides":[{"patch":[{"op":"replace","value":"MBXTileRegionEstimateProgressCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgressCallback\/title"},{"op":"replace","value":[{"text":"MBXTileRegionEstimateProgressCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgressCallback\/fragments"},{"value":[{"kind":"identifier","text":"MBXTileRegionEstimateProgressCallback"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgressCallback\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/title","value":"MBXTileRegionLoadOptions"},{"op":"replace","value":[{"text":"MBXTileRegionLoadOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/navigatorTitle","value":[{"text":"MBXTileRegionLoadOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TilesetDescriptor\/title","op":"replace","value":"MBXTilesetDescriptor"},{"op":"replace","value":[{"kind":"identifier","text":"MBXTilesetDescriptor"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TilesetDescriptor\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MBXTilesetDescriptor"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TilesetDescriptor\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileOptions\/title","value":"MBMTileOptions"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileOptions\/fragments","value":[{"text":"MBMTileOptions","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileOptions\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMTileOptions"}]},{"op":"replace","value":"MBXTileStore","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/fragments","value":[{"text":"MBXTileStore","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/navigatorTitle","value":[{"text":"MBXTileStore","kind":"identifier"}],"op":"replace"},{"value":"MBXTileRegion","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegion\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegion\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXTileRegion"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegion\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBXTileRegion"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInMegabytes\/title","value":"MBMTileCacheBudgetInMegabytes","op":"replace"},{"value":[{"text":"MBMTileCacheBudgetInMegabytes","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInMegabytes\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInMegabytes\/navigatorTitle","value":[{"text":"MBMTileCacheBudgetInMegabytes","kind":"identifier"}]},{"value":"MBXTileRegionEstimateProgress","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgress\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgress\/fragments","op":"replace","value":[{"text":"MBXTileRegionEstimateProgress","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MBXTileRegionEstimateProgress"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgress\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInTiles\/title","op":"replace","value":"MBMTileCacheBudgetInTiles"},{"value":[{"kind":"identifier","text":"MBMTileCacheBudgetInTiles"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInTiles\/fragments","op":"replace"},{"value":[{"text":"MBMTileCacheBudgetInTiles","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInTiles\/navigatorTitle","op":"replace"},{"value":"MBMTileCacheBudgetType","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetType\/fragments","value":[{"text":"MBMTileCacheBudgetType","kind":"identifier"}]},{"value":[{"text":"MBMTileCacheBudgetType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetType\/navigatorTitle"},{"value":"MBMTilesetDescriptorOptions","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMTilesetDescriptorOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions\/navigatorTitle","value":[{"kind":"identifier","text":"MBMTilesetDescriptorOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgress\/title","value":"MBXTileRegionLoadProgress"},{"value":[{"text":"MBXTileRegionLoadProgress","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgress\/fragments"},{"value":[{"text":"MBXTileRegionLoadProgress","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgress\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudget\/title","value":"MBMTileCacheBudget"},{"op":"replace","value":[{"text":"MBMTileCacheBudget","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudget\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudget\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMTileCacheBudget"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStoreOptions\/title","value":"MBXTileStoreOptions","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStoreOptions\/fragments","value":[{"kind":"identifier","text":"MBXTileStoreOptions"}],"op":"replace"},{"value":[{"kind":"identifier","text":"MBXTileStoreOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStoreOptions\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgressCallback\/title","value":"MBXTileRegionLoadProgressCallback"},{"op":"replace","value":[{"text":"MBXTileRegionLoadProgressCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgressCallback\/fragments"},{"value":[{"text":"MBXTileRegionLoadProgressCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgressCallback\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingError\/title","value":"MBXCacheClearingError","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingError\/fragments","value":[{"text":"MBXCacheClearingError","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingError\/navigatorTitle","value":[{"text":"MBXCacheClearingError","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingErrorType\/title","value":"MBXCacheClearingErrorType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingErrorType\/fragments","value":[{"text":"MBXCacheClearingErrorType","kind":"identifier"}]},{"op":"replace","value":[{"text":"MBXCacheClearingErrorType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingErrorType\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileDataDomain\/title","value":"MBXTileDataDomain","op":"replace"},{"value":[{"kind":"identifier","text":"MBXTileDataDomain"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileDataDomain\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MBXTileDataDomain"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileDataDomain\/navigatorTitle","op":"replace"},{"value":"MBMTileStoreUsageMode","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileStoreUsageMode\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileStoreUsageMode\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMTileStoreUsageMode"}]},{"op":"replace","value":[{"text":"MBMTileStoreUsageMode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileStoreUsageMode\/navigatorTitle"},{"value":"MBXTileRegionEstimateOptions","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateOptions\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateOptions\/fragments","value":[{"text":"MBXTileRegionEstimateOptions","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateOptions\/navigatorTitle","value":[{"kind":"identifier","text":"MBXTileRegionEstimateOptions"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateResult\/title","value":"MBXTileRegionEstimateResult","op":"replace"},{"value":[{"kind":"identifier","text":"MBXTileRegionEstimateResult"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateResult\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateResult\/navigatorTitle","value":[{"kind":"identifier","text":"MBXTileRegionEstimateResult"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/title","value":"MBMCanonicalTileID","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/fragments","value":[{"kind":"identifier","text":"MBMCanonicalTileID"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/navigatorTitle","value":[{"text":"MBMCanonicalTileID","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}