{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"Geometry"}],"title":"Geometry","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Geometry"}],"role":"symbol","roleHeading":"Class","externalID":"c:objc(cs)MBXGeometry","modules":[{"name":"MapboxCommon"}],"symbolKind":"class"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry\/init(geometryCollection:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry\/init(line:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry\/init(multiLine:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry\/init(multiPoint:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry\/init(multiPolygon:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry\/init(point:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry\/init(polygon:)"],"anchor":"Initializers","generated":true},{"title":"Instance Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry\/geometry","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry\/geometryType"],"anchor":"Instance-Properties","generated":true},{"title":"Instance Methods","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry\/extractGeometriesArray()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry\/extractLocations()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry\/extractLocations2DArray()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry\/extractLocations3DArray()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry\/extractLocationsArray()"],"anchor":"Instance-Methods","generated":true}],"relationshipsSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"variants":[{"paths":["\/documentation\/mapboxcommon\/geometry"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxcommon\/geometry"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Geometry","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Geometry/extractGeometriesArray()":{"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"extractGeometriesArray","kind":"identifier"},{"text":"() -> [","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBXGeometry","text":"Geometry","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"url":"\/documentation\/mapboxcommon\/geometry\/extractgeometriesarray()","title":"extractGeometriesArray()","type":"topic","navigatorTitle":[{"text":"extractGeometriesArray","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry\/extractGeometriesArray()","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Geometry/init(polygon:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithPolygon:"}],"url":"\/documentation\/mapboxcommon\/geometry\/init(polygon:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry\/init(polygon:)","title":"init(polygon:)","abstract":[],"kind":"symbol","role":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"polygon"},{"kind":"text","text":": [["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSValue","text":"NSValue"},{"kind":"text","text":"]])"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Geometry/extractLocationsArray()":{"url":"\/documentation\/mapboxcommon\/geometry\/extractlocationsarray()","title":"extractLocationsArray()","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry\/extractLocationsArray()","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"extractLocationsArray","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"extractLocationsArray","kind":"identifier"},{"text":"() -> [","kind":"text"},{"text":"NSValue","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSValue"},{"text":"]?","kind":"text"}],"abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","role":"collection","type":"topic","abstract":[],"title":"MapboxMaps Documentation","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.mapbox.MapboxMaps/objc(cs)NSObject":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"url":"\/documentation\/mapboxcommon","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","role":"collection","title":"MapboxCommon","type":"topic","kind":"symbol","abstract":[]},"doc://com.mapbox.MapboxMaps/SH":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Geometry/extractLocations()":{"navigatorTitle":[{"text":"extractLocations","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry\/extractLocations()","title":"extractLocations()","abstract":[],"url":"\/documentation\/mapboxcommon\/geometry\/extractlocations()","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"extractLocations","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"NSValue","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSValue"},{"text":"?","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Geometry/extractLocations3DArray()":{"navigatorTitle":[{"kind":"identifier","text":"extractLocations3DArray"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry\/extractLocations3DArray()","kind":"symbol","url":"\/documentation\/mapboxcommon\/geometry\/extractlocations3darray()","abstract":[],"title":"extractLocations3DArray()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"extractLocations3DArray"},{"kind":"text","text":"() -> [[["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSValue","text":"NSValue"},{"kind":"text","text":"]]]?"}],"role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Geometry/init(multiLine:)":{"kind":"symbol","title":"init(multiLine:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"multiLine"},{"kind":"text","text":": [["},{"kind":"typeIdentifier","text":"NSValue","preciseIdentifier":"c:objc(cs)NSValue"},{"kind":"text","text":"]])"}],"url":"\/documentation\/mapboxcommon\/geometry\/init(multiline:)","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry\/init(multiLine:)","navigatorTitle":[{"kind":"identifier","text":"initWithMultiLine:"}],"abstract":[],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Geometry/init(line:)":{"type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry\/init(line:)","url":"\/documentation\/mapboxcommon\/geometry\/init(line:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"line"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)NSValue","kind":"typeIdentifier","text":"NSValue"},{"kind":"text","text":"])"}],"navigatorTitle":[{"kind":"identifier","text":"initWithLine:"}],"title":"init(line:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Geometry/geometryType":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry\/geometryType","type":"topic","title":"geometryType","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"geometryType"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@EA@MBXGeometryType","kind":"typeIdentifier","text":"GeometryType"}],"kind":"symbol","url":"\/documentation\/mapboxcommon\/geometry\/geometrytype","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"geometryType"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Geometry/init(multiPoint:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithMultiPoint:"}],"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry\/init(multiPoint:)","url":"\/documentation\/mapboxcommon\/geometry\/init(multipoint:)","role":"symbol","title":"init(multiPoint:)","type":"topic","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"multiPoint"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSValue","text":"NSValue"},{"kind":"text","text":"])"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Geometry/init(multiPolygon:)":{"url":"\/documentation\/mapboxcommon\/geometry\/init(multipolygon:)","title":"init(multiPolygon:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry\/init(multiPolygon:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"multiPolygon"},{"kind":"text","text":": [[["},{"kind":"typeIdentifier","text":"NSValue","preciseIdentifier":"c:objc(cs)NSValue"},{"kind":"text","text":"]]])"}],"navigatorTitle":[{"kind":"identifier","text":"initWithMultiPolygon:"}],"type":"topic","kind":"symbol","role":"symbol","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Geometry/extractLocations2DArray()":{"type":"topic","role":"symbol","title":"extractLocations2DArray()","url":"\/documentation\/mapboxcommon\/geometry\/extractlocations2darray()","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry\/extractLocations2DArray()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"extractLocations2DArray"},{"kind":"text","text":"() -> [["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSValue","text":"NSValue"},{"kind":"text","text":"]]?"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"extractLocations2DArray"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Geometry/init(geometryCollection:)":{"type":"topic","title":"init(geometryCollection:)","url":"\/documentation\/mapboxcommon\/geometry\/init(geometrycollection:)","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithGeometryCollection:"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry\/init(geometryCollection:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"geometryCollection"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Geometry","preciseIdentifier":"c:objc(cs)MBXGeometry"},{"kind":"text","text":"])"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Geometry":{"navigatorTitle":[{"text":"Geometry","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Geometry","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/geometry","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry","role":"symbol","abstract":[],"title":"Geometry"},"doc://com.mapbox.MapboxMaps/s7CVarArgP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.mapbox.MapboxMaps/objc(pl)NSObject":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Geometry/geometry":{"navigatorTitle":[{"kind":"identifier","text":"geometry"}],"url":"\/documentation\/mapboxcommon\/geometry\/geometry","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry\/geometry","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"geometry"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeMutableRawPointer","preciseIdentifier":"s:Sv"}],"abstract":[],"type":"topic","title":"geometry"},"doc://com.mapbox.MapboxMaps/SQ":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Geometry/init(point:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithPoint:"}],"url":"\/documentation\/mapboxcommon\/geometry\/init(point:)","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry\/init(point:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"point"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSValue","preciseIdentifier":"c:objc(cs)NSValue"},{"kind":"text","text":")"}],"abstract":[],"type":"topic","title":"init(point:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"MBXGeometry"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"MBXGeometry","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"MBXGeometry","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry\/geometry","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry\/geometryType"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry\/extractGeometriesArray()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry\/extractLocations()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry\/extractLocations2DArray()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry\/extractLocations3DArray()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry\/extractLocationsArray()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry\/init(geometryCollection:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry\/init(line:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry\/init(multiLine:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry\/init(multiPoint:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry\/init(multiPolygon:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry\/init(point:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry\/init(polygon:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"]}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBXGeometry"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry~1extractGeometriesArray()\/title","op":"replace","value":"extractGeometriesArray"},{"value":[{"text":"- ","kind":"text"},{"text":"extractGeometriesArray","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry~1extractGeometriesArray()\/fragments","op":"replace"},{"value":"initWithPolygon:","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry~1init(polygon:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPolygon:"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry~1init(polygon:)\/fragments","op":"replace"},{"value":"extractLocationsArray","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry~1extractLocationsArray()\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"extractLocationsArray"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry~1extractLocationsArray()\/fragments","op":"replace"},{"value":"extractLocations","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry~1extractLocations()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"extractLocations","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry~1extractLocations()\/fragments","op":"replace"},{"value":"extractLocations3DArray","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry~1extractLocations3DArray()\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"extractLocations3DArray"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry~1extractLocations3DArray()\/fragments","op":"replace"},{"value":"initWithMultiLine:","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry~1init(multiLine:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMultiLine:"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry~1init(multiLine:)\/fragments","op":"replace"},{"value":"initWithLine:","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry~1init(line:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLine:"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry~1init(line:)\/fragments","op":"replace"},{"value":"geometryType","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry~1geometryType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"geometryType"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry~1geometryType\/fragments","op":"replace"},{"value":"initWithMultiPoint:","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry~1init(multiPoint:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithMultiPoint:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry~1init(multiPoint:)\/fragments","op":"replace"},{"value":"initWithMultiPolygon:","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry~1init(multiPolygon:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithMultiPolygon:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry~1init(multiPolygon:)\/fragments","op":"replace"},{"value":"extractLocations2DArray","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry~1extractLocations2DArray()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"extractLocations2DArray","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry~1extractLocations2DArray()\/fragments","op":"replace"},{"value":"initWithGeometryCollection:","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry~1init(geometryCollection:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithGeometryCollection:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry~1init(geometryCollection:)\/fragments","op":"replace"},{"value":"MBXGeometry","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MBXGeometry"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry\/fragments","op":"replace"},{"value":[{"text":"MBXGeometry","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry\/navigatorTitle","op":"replace"},{"value":"geometry","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry~1geometry\/title","op":"replace"},{"value":[{"text":"geometry","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry~1geometry\/fragments","op":"replace"},{"value":"initWithPoint:","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry~1init(point:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPoint:"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry~1init(point:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}