{"abstract":[{"type":"text","text":"Initialize a response given the initial request and "},{"type":"codeVoice","code":"HttpResponseData"},{"text":" or","type":"text"},{"type":"text","text":" "},{"type":"codeVoice","code":"HttpRequestError"}],"variants":[{"paths":["\/documentation\/mapboxcommon\/httpresponse\/init(identifier:request:result:)"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s6UInt64V","kind":"typeIdentifier","text":"UInt64"},{"text":", ","kind":"text"},{"text":"request","kind":"externalParam"},{"kind":"text","text":": "},{"text":"HttpRequest","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXHttpRequest","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"result"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"text":"HttpResponseData","preciseIdentifier":"c:objc(cs)MBXHttpResponseData","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpResponseData","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"HttpRequestError","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXHttpRequestError"},{"text":">)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The id of the request that resulted in this response.","type":"text"}],"type":"paragraph"}],"name":"identifier"},{"name":"request","content":[{"type":"paragraph","inlineContent":[{"text":"Original request","type":"text"}]}]},{"name":"result","content":[{"inlineContent":[{"text":"Result type encapsulating response or error","type":"text"}],"type":"paragraph"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpResponse"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpResponse\/init(identifier:request:result:)"},"metadata":{"symbolKind":"init","role":"symbol","title":"init(identifier:request:result:)","fragments":[{"text":"convenience","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt64","preciseIdentifier":"s:s6UInt64V","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"request"},{"kind":"text","text":": "},{"text":"HttpRequest","preciseIdentifier":"c:objc(cs)MBXHttpRequest","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"result"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s6ResultO","text":"Result","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"HttpResponseData","preciseIdentifier":"c:objc(cs)MBXHttpResponseData"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXHttpRequestError","text":"HttpRequestError"},{"kind":"text","text":">)"}],"roleHeading":"Initializer","externalID":"s:So15MBXHttpResponseC12MapboxCommonE10identifier7request6resultABs6UInt64V_So0A7RequestCs6ResultOySo0aB4DataCSo0aI5ErrorCGtcfc","modules":[{"name":"MapboxCommon"}],"extendedModule":"MapboxCommon"},"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestError":{"url":"\/documentation\/mapboxcommon\/httprequesterror","title":"HttpRequestError","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestError","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HttpRequestError"}],"navigatorTitle":[{"kind":"identifier","text":"HttpRequestError"}],"abstract":[{"text":"Record which contains detailed information about HTTP error happened during request\/download call.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","abstract":[],"title":"MapboxCommon","kind":"symbol","type":"topic","url":"\/documentation\/mapboxcommon","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpResponseData":{"kind":"symbol","abstract":[{"type":"text","text":"Record which contains data received in HTTP response."}],"title":"HttpResponseData","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpResponseData","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HttpResponseData"}],"url":"\/documentation\/mapboxcommon\/httpresponsedata","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HttpResponseData"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpResponse":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"HttpResponse","kind":"identifier"}],"title":"HttpResponse","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpResponse","url":"\/documentation\/mapboxcommon\/httpresponse","kind":"symbol","navigatorTitle":[{"text":"HttpResponse","kind":"identifier"}],"abstract":[{"text":"Record which is used to report HTTP response to the caller.","type":"text"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","kind":"article","role":"collection","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpResponse/init(identifier:request:result:)":{"title":"init(identifier:request:result:)","role":"symbol","url":"\/documentation\/mapboxcommon\/httpresponse\/init(identifier:request:result:)","abstract":[{"type":"text","text":"Initialize a response given the initial request and "},{"code":"HttpResponseData","type":"codeVoice"},{"type":"text","text":" or"},{"text":" ","type":"text"},{"type":"codeVoice","code":"HttpRequestError"}],"kind":"symbol","fragments":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"identifier","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt64","preciseIdentifier":"s:s6UInt64V"},{"kind":"text","text":", "},{"text":"request","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"HttpRequest","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXHttpRequest"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"result"},{"kind":"text","text":": "},{"text":"Result","preciseIdentifier":"s:s6ResultO","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXHttpResponseData","text":"HttpResponseData"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBXHttpRequestError","text":"HttpRequestError","kind":"typeIdentifier"},{"kind":"text","text":">)"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpResponse\/init(identifier:request:result:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequest":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HttpRequest","kind":"identifier"}],"title":"HttpRequest","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest","url":"\/documentation\/mapboxcommon\/httprequest","kind":"symbol","navigatorTitle":[{"text":"HttpRequest","kind":"identifier"}],"abstract":[{"text":"HttpRequest holds basic information for construction of an HTTP request","type":"text"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestError\/title","value":"MBXHttpRequestError","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestError\/fragments","value":[{"text":"MBXHttpRequestError","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MBXHttpRequestError"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestError\/navigatorTitle"},{"value":"MBXHttpResponseData","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpResponseData\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MBXHttpResponseData"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpResponseData\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpResponseData\/navigatorTitle","value":[{"text":"MBXHttpResponseData","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpResponse\/title","value":"MBXHttpResponse","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpResponse\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXHttpResponse"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpResponse\/navigatorTitle","value":[{"kind":"identifier","text":"MBXHttpResponse"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest\/title","op":"replace","value":"MBXHttpRequest"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest\/fragments","value":[{"kind":"identifier","text":"MBXHttpRequest"}],"op":"replace"},{"op":"replace","value":[{"text":"MBXHttpRequest","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest\/navigatorTitle"}]}]}