{"kind":"symbol","abstract":[{"text":"Called when ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/anchorConfig","isActive":true},{"text":" is changed.","type":"text"}],"variants":[{"paths":["\/documentation\/mapboxmaps\/viewannotation\/onanchorchanged"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/onAnchorChanged"},"metadata":{"title":"onAnchorChanged","roleHeading":"Instance Property","externalID":"s:10MapboxMaps14ViewAnnotationC15onAnchorChangedySo07MBMViewdF6ConfigCcSgvp","modules":[{"name":"MapboxMaps"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onAnchorChanged","kind":"identifier"},{"text":": ((","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMViewAnnotationAnchorConfig","text":"ViewAnnotationAnchorConfig","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/View-Annotations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onAnchorChanged","kind":"identifier"},{"text":": ((","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMViewAnnotationAnchorConfig","text":"ViewAnnotationAnchorConfig","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchorConfig"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"See ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/variableAnchors","isActive":true,"type":"reference"},{"text":".","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The callback takes the "},{"type":"codeVoice","code":"anchorConfig"},{"type":"text","text":" parameter which represents the selected anchor configuration."}]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotation/anchorConfig":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"anchorConfig"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMViewAnnotationAnchorConfig","text":"ViewAnnotationAnchorConfig"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/anchorConfig","kind":"symbol","title":"anchorConfig","url":"\/documentation\/mapboxmaps\/viewannotation\/anchorconfig","abstract":[{"type":"text","text":"Currently selected anchor configuration."}],"role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotation/variableAnchors":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"variableAnchors","kind":"identifier"},{"text":": [","kind":"text"},{"text":"ViewAnnotationAnchorConfig","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMViewAnnotationAnchorConfig"},{"text":"]","kind":"text"}],"title":"variableAnchors","type":"topic","abstract":[{"text":"A list of anchor configurations available.","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/variableAnchors","url":"\/documentation\/mapboxmaps\/viewannotation\/variableanchors"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotation/onAnchorChanged":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onAnchorChanged"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMViewAnnotationAnchorConfig","text":"ViewAnnotationAnchorConfig"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?"}],"url":"\/documentation\/mapboxmaps\/viewannotation\/onanchorchanged","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/onAnchorChanged","type":"topic","title":"onAnchorChanged","abstract":[{"type":"text","text":"Called when "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/anchorConfig","type":"reference","isActive":true},{"type":"text","text":" is changed."}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","abstract":[],"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","type":"topic","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotation":{"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ViewAnnotation","kind":"identifier"}],"title":"ViewAnnotation","abstract":[{"type":"text","text":"Creates a view annotation."}],"role":"symbol","url":"\/documentation\/mapboxmaps\/viewannotation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation","navigatorTitle":[{"text":"ViewAnnotation","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationAnchorConfig":{"type":"topic","url":"\/documentation\/mapboxmaps\/viewannotationanchorconfig","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchorConfig","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ViewAnnotationAnchorConfig","kind":"identifier"}],"navigatorTitle":[{"text":"ViewAnnotationAnchorConfig","kind":"identifier"}],"title":"ViewAnnotationAnchorConfig","abstract":[{"type":"text","text":"Represents a specific setting for a view annotation anchor."}],"role":"symbol","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/View-Annotations":{"url":"\/documentation\/mapboxmaps\/view-annotations","role":"collectionGroup","title":"View Annotations","type":"topic","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/View-Annotations","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","role":"collection","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"MBMViewAnnotationAnchorConfig","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchorConfig\/title"},{"value":[{"text":"MBMViewAnnotationAnchorConfig","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchorConfig\/fragments"},{"value":[{"text":"MBMViewAnnotationAnchorConfig","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchorConfig\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}