{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoordinateBounds"}],"platforms":["iOS"]}]}],"metadata":{"navigatorTitle":[{"text":"CoordinateBounds","kind":"identifier"}],"modules":[{"name":"MapboxMaps"}],"title":"CoordinateBounds","symbolKind":"class","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoordinateBounds","kind":"identifier"}],"roleHeading":"Class","externalID":"c:objc(cs)MBMCoordinateBounds"},"seeAlsoSections":[{"anchor":"MapboxMap","title":"MapboxMap","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraState","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBounds","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBoundsOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Projection","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBoundsZoom","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateInfo","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ContextMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapCenterAltitudeMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometry","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometryConvertible"]}],"variants":[{"paths":["\/documentation\/mapboxmaps\/coordinatebounds"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/coordinatebounds"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs"]]},"abstract":[{"text":"A rectangular area as measured on a two-dimensional map projection.","type":"text"}],"topicSections":[{"anchor":"Initializers","title":"Initializers","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds\/init(southwest:northeast:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds\/init(southwest:northeast:infiniteBounds:)"]},{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds\/infiniteBounds","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds\/northeast","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds\/southwest"]},{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds\/constrain(forPoint:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds\/contains(forArea:wrappedCoordinates:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds\/contains(forPoint:wrappedCoordinates:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds\/containsLatitude(forLatitude:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds\/containsLongitude(forLongitude:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds\/extend(forArea:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds\/extend(forPoint:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds\/intersects(forArea:wrappedCoordinates:)"]}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"]},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH","doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMCoordinateBounds/singletonForPoint:":{"type":"topic","url":"\/documentation\/mapboxmaps\/mbmcoordinatebounds\/singletonforpoint:","title":"singletonForPoint:","role":"symbol","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"singletonForPoint:"}],"kind":"symbol","abstract":[{"text":"Returns the bounds consisting of the single point.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCoordinateBounds\/singletonForPoint:","navigatorTitle":[{"kind":"identifier","text":"singletonForPoint:"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateBounds/contains(forPoint:wrappedCoordinates:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contains","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forPoint","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"wrappedCoordinates","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Returns whether the bounds contains "},{"type":"codeVoice","code":"point"},{"type":"text","text":" or not."}],"kind":"symbol","navigatorTitle":[{"text":"containsForPoint:wrappedCoordinates:","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/coordinatebounds\/contains(forpoint:wrappedcoordinates:)","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds\/contains(forPoint:wrappedCoordinates:)","title":"contains(forPoint:wrappedCoordinates:)","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraBounds":{"navigatorTitle":[{"text":"CameraBounds","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraBounds","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/camerabounds","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBounds","abstract":[{"type":"text","text":"Holds information about camera bounds."}],"title":"CameraBounds","role":"symbol"},"doc://com.mapbox.MapboxMaps/objc(pl)NSObject":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ContextMode":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ContextMode","navigatorTitle":[{"kind":"identifier","text":"ContextMode"}],"title":"ContextMode","type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/contextmode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContextMode"}],"role":"symbol","abstract":[{"text":"Describes the map context mode.","type":"text"},{"text":" ","type":"text"},{"text":"We can make some optimizations if we know that the drawing context is not shared with other code.","type":"text"}]},"doc://com.mapbox.MapboxMaps/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMCoordinateBounds/hullForA:b:":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCoordinateBounds\/hullForA:b:","navigatorTitle":[{"text":"hullForA:b:","kind":"identifier"}],"title":"hullForA:b:","type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/mbmcoordinatebounds\/hullfora:b:","fragments":[{"text":"+ ","kind":"text"},{"text":"hullForA:b:","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Returns the convex hull of two points; the smallest bounds that contains both.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"type":"topic","url":"\/documentation\/mapboxmaps\/mapboxmap-apis","abstract":[],"kind":"article","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","title":"MapboxMap"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateBounds/constrain(forPoint:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds\/constrain(forPoint:)","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"constrain"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forPoint"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","kind":"typeIdentifier","text":"CLLocationCoordinate2D"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","kind":"typeIdentifier","text":"CLLocationCoordinate2D"}],"url":"\/documentation\/mapboxmaps\/coordinatebounds\/constrain(forpoint:)","abstract":[{"text":"Constrains ","type":"text"},{"code":"point","type":"codeVoice"},{"text":" against the bounds.","type":"text"}],"title":"constrain(forPoint:)","navigatorTitle":[{"kind":"identifier","text":"constrainForPoint:"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","role":"collection","type":"topic","abstract":[],"title":"MapboxMaps Documentation","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap":{"abstract":[{"type":"text","text":"Provides access to the map model, including the camera, style, observable map events,"},{"type":"text","text":" "},{"type":"text","text":"and querying rendered features."}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","url":"\/documentation\/mapboxmaps\/mapboxmap","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"MapboxMap","kind":"identifier"}],"title":"MapboxMap","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapboxMap","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMCoordinateBounds/west":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCoordinateBounds\/west","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"west","kind":"identifier"}],"abstract":[{"type":"text","text":"Returns the western longitude of the bounds."}],"url":"\/documentation\/mapboxmaps\/mbmcoordinatebounds\/west","title":"west","navigatorTitle":[{"text":"west","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraBoundsOptions":{"navigatorTitle":[{"kind":"identifier","text":"CameraBoundsOptions"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBoundsOptions","abstract":[{"type":"text","text":"Holds options to be used for setting camera bounds."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraBoundsOptions"}],"title":"CameraBoundsOptions","url":"\/documentation\/mapboxmaps\/cameraboundsoptions","type":"topic","kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateBounds/containsLongitude(forLongitude:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"containsLongitude"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forLongitude"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"containsLongitude(forLongitude:)","abstract":[{"text":"Returns whether the bounds contains ","type":"text"},{"type":"codeVoice","code":"longitude"},{"text":" or not.","type":"text"}],"url":"\/documentation\/mapboxmaps\/coordinatebounds\/containslongitude(forlongitude:)","navigatorTitle":[{"kind":"identifier","text":"containsLongitudeForLongitude:"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds\/containsLongitude(forLongitude:)","type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateBounds":{"title":"CoordinateBounds","navigatorTitle":[{"text":"CoordinateBounds","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/coordinatebounds","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoordinateBounds","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"A rectangular area as measured on a two-dimensional map projection."}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMCoordinateBounds/center":{"title":"center","abstract":[{"type":"text","text":"Returns the center coordinate of the bounds."}],"url":"\/documentation\/mapboxmaps\/mbmcoordinatebounds\/center","role":"symbol","kind":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"center"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCoordinateBounds\/center","navigatorTitle":[{"kind":"identifier","text":"center"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateBounds/extend(forPoint:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds\/extend(forPoint:)","abstract":[{"type":"text","text":"Extends these bounds to include "},{"code":"point","type":"codeVoice"},{"type":"text","text":"."}],"navigatorTitle":[{"kind":"identifier","text":"extendForPoint:"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"extend"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forPoint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMCoordinateBounds","text":"CoordinateBounds"}],"type":"topic","title":"extend(forPoint:)","url":"\/documentation\/mapboxmaps\/coordinatebounds\/extend(forpoint:)","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GlyphsRasterizationMode":{"type":"topic","navigatorTitle":[{"text":"GlyphsRasterizationMode","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode","abstract":[{"type":"text","text":"Describes glyphs rasterization modes."}],"kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GlyphsRasterizationMode","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/glyphsrasterizationmode","title":"GlyphsRasterizationMode"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapError":{"url":"\/documentation\/mapboxmaps\/maperror","title":"MapError","navigatorTitle":[{"text":"MapError","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapError","role":"symbol","abstract":[{"type":"text","text":"Type of errors thrown by the "},{"code":"MapboxMap","type":"codeVoice"},{"type":"text","text":" APIs."}],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapError","kind":"identifier"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMCoordinateBounds/isBounded":{"url":"\/documentation\/mapboxmaps\/mbmcoordinatebounds\/isbounded","title":"isBounded","navigatorTitle":[{"text":"isBounded","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCoordinateBounds\/isBounded","role":"symbol","abstract":[{"type":"text","text":"Returns whether the bounds are infinite or bounded."}],"kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"isBounded","kind":"identifier"}],"type":"topic"},"https://en.wikipedia.org/wiki/Web_Mercator_projection":{"identifier":"https:\/\/en.wikipedia.org\/wiki\/Web_Mercator_projection","url":"https:\/\/en.wikipedia.org\/wiki\/Web_Mercator_projection","type":"link","title":"Spherical Mercator","titleInlineContent":[{"type":"text","text":"Spherical Mercator"}]},"doc://com.mapbox.MapboxMaps/SQ":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateBoundsZoom":{"abstract":[{"type":"text","text":"A coordinate bounds and zoom."}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBoundsZoom","title":"CoordinateBoundsZoom","kind":"symbol","url":"\/documentation\/mapboxmaps\/coordinateboundszoom","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoordinateBoundsZoom"}],"navigatorTitle":[{"kind":"identifier","text":"CoordinateBoundsZoom"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderedQueryGeometry":{"title":"RenderedQueryGeometry","navigatorTitle":[{"text":"RenderedQueryGeometry","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/renderedquerygeometry","abstract":[{"text":"A geometry to define a portion of screen that should be queried for rendered features.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometry","role":"symbol","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RenderedQueryGeometry","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/SH":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateBounds/northeast":{"kind":"symbol","navigatorTitle":[{"text":"northeast","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"northeast","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D","kind":"typeIdentifier"}],"abstract":[{"text":"Coordinate at the northeast corner.","type":"text"},{"text":" ","type":"text"},{"text":"Note: setting this field with invalid values (infinite, NaN) will crash the application.","type":"text"}],"url":"\/documentation\/mapboxmaps\/coordinatebounds\/northeast","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds\/northeast","title":"northeast","role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraOptions":{"navigatorTitle":[{"text":"CameraOptions","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxmaps\/cameraoptions","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraOptions","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraOptions","kind":"identifier"}],"kind":"symbol","title":"CameraOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMCoordinateBounds/northwest":{"url":"\/documentation\/mapboxmaps\/mbmcoordinatebounds\/northwest","fragments":[{"text":"- ","kind":"text"},{"text":"northwest","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCoordinateBounds\/northwest","type":"topic","role":"symbol","navigatorTitle":[{"text":"northwest","kind":"identifier"}],"abstract":[{"text":"Returns the northwest coordinate of the bounds.","type":"text"}],"title":"northwest","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMCoordinateBounds/latitudeSpan":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"latitudeSpan"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCoordinateBounds\/latitudeSpan","title":"latitudeSpan","type":"topic","navigatorTitle":[{"kind":"identifier","text":"latitudeSpan"}],"url":"\/documentation\/mapboxmaps\/mbmcoordinatebounds\/latitudespan","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Returns the absolute distance, in degrees, between the north and"},{"type":"text","text":" "},{"type":"text","text":"south boundaries of these bounds."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMCoordinateBounds/north":{"title":"north","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"north"}],"url":"\/documentation\/mapboxmaps\/mbmcoordinatebounds\/north","abstract":[{"type":"text","text":"Returns the northern latitude of the bounds."}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCoordinateBounds\/north","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"north"}]},"doc://com.mapbox.MapboxMaps/objc(cs)NSObject":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateBounds/contains(forArea:wrappedCoordinates:)":{"abstract":[{"type":"text","text":"Returns whether the bounds contains "},{"type":"codeVoice","code":"area"},{"type":"text","text":" or not."}],"navigatorTitle":[{"kind":"identifier","text":"containsForArea:wrappedCoordinates:"}],"url":"\/documentation\/mapboxmaps\/coordinatebounds\/contains(forarea:wrappedcoordinates:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contains","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forArea","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CoordinateBounds","preciseIdentifier":"c:objc(cs)MBMCoordinateBounds","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"wrappedCoordinates","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds\/contains(forArea:wrappedCoordinates:)","title":"contains(forArea:wrappedCoordinates:)","kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapCenterAltitudeMode":{"abstract":[{"type":"text","text":"Defines how the map center point should react to terrain elevation changes."}],"kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapCenterAltitudeMode","kind":"identifier"}],"navigatorTitle":[{"text":"MapCenterAltitudeMode","kind":"identifier"}],"type":"topic","title":"MapCenterAltitudeMode","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapCenterAltitudeMode","url":"\/documentation\/mapboxmaps\/mapcenteraltitudemode"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateBounds/intersects(forArea:wrappedCoordinates:)":{"role":"symbol","kind":"symbol","title":"intersects(forArea:wrappedCoordinates:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds\/intersects(forArea:wrappedCoordinates:)","url":"\/documentation\/mapboxmaps\/coordinatebounds\/intersects(forarea:wrappedcoordinates:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"intersects","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forArea","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMCoordinateBounds","text":"CoordinateBounds","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"wrappedCoordinates","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Returns whether the bounds intersects "},{"type":"codeVoice","code":"area"},{"type":"text","text":" or not."}],"type":"topic","navigatorTitle":[{"text":"intersectsForArea:wrappedCoordinates:","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateBounds/extend(forArea:)":{"role":"symbol","kind":"symbol","title":"extend(forArea:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds\/extend(forArea:)","url":"\/documentation\/mapboxmaps\/coordinatebounds\/extend(forarea:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"extend","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forArea","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMCoordinateBounds","text":"CoordinateBounds","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMCoordinateBounds","text":"CoordinateBounds","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Extends these bounds to include "},{"type":"codeVoice","code":"area"},{"type":"text","text":"."}],"type":"topic","navigatorTitle":[{"text":"extendForArea:","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateBounds/init(southwest:northeast:infiniteBounds:)":{"url":"\/documentation\/mapboxmaps\/coordinatebounds\/init(southwest:northeast:infinitebounds:)","title":"init(southwest:northeast:infiniteBounds:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds\/init(southwest:northeast:infiniteBounds:)","abstract":[],"kind":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"southwest","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"northeast","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"infiniteBounds","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithSouthwest:northeast:infiniteBounds:"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMCoordinateBounds/crossesAntimeridian":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCoordinateBounds\/crossesAntimeridian","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"crossesAntimeridian","kind":"identifier"}],"title":"crossesAntimeridian","kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/mbmcoordinatebounds\/crossesantimeridian","abstract":[{"type":"text","text":"Returns whether the bounds cross the date line or not."}],"navigatorTitle":[{"text":"crossesAntimeridian","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMCoordinateBounds/east":{"navigatorTitle":[{"text":"east","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/mbmcoordinatebounds\/east","title":"east","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"east","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCoordinateBounds\/east","abstract":[{"type":"text","text":"Returns the eastern longitude of the bounds."}],"type":"topic"},"doc://com.mapbox.MapboxMaps/s8SendableP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateBounds/init(southwest:northeast:)":{"type":"topic","title":"init(southwest:northeast:)","url":"\/documentation\/mapboxmaps\/coordinatebounds\/init(southwest:northeast:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds\/init(southwest:northeast:)","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"southwest","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"northeast","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithSouthwest:northeast:","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateBounds/containsLatitude(forLatitude:)":{"type":"topic","title":"containsLatitude(forLatitude:)","url":"\/documentation\/mapboxmaps\/coordinatebounds\/containslatitude(forlatitude:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds\/containsLatitude(forLatitude:)","abstract":[{"type":"text","text":"Returns whether the bounds contains "},{"type":"codeVoice","code":"latitude"},{"type":"text","text":" or not."}],"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"containsLatitude","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forLatitude","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"containsLatitudeForLatitude:","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMCoordinateBounds/world":{"kind":"symbol","navigatorTitle":[{"text":"world","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/mbmcoordinatebounds\/world","fragments":[{"text":"+ ","kind":"text"},{"text":"world","kind":"identifier"}],"title":"world","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Returns a bounds covering the entire (unwrapped) world."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCoordinateBounds\/world"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraState":{"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraState","kind":"identifier"}],"type":"topic","abstract":[],"navigatorTitle":[{"text":"CameraState","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraState","title":"CameraState","url":"\/documentation\/mapboxmaps\/camerastate"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMCoordinateBounds/southeast":{"abstract":[{"type":"text","text":"Returns the southeast coordinate of the bounds."}],"navigatorTitle":[{"text":"southeast","kind":"identifier"}],"title":"southeast","role":"symbol","url":"\/documentation\/mapboxmaps\/mbmcoordinatebounds\/southeast","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCoordinateBounds\/southeast","type":"topic","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"southeast","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderedQueryGeometryConvertible":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"RenderedQueryGeometryConvertible"}],"url":"\/documentation\/mapboxmaps\/renderedquerygeometryconvertible","kind":"symbol","title":"RenderedQueryGeometryConvertible","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RenderedQueryGeometryConvertible"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometryConvertible","abstract":[{"type":"text","text":"A convenience protocol for automatic conversion to "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometry","isActive":true,"type":"reference"},{"type":"text","text":"."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateInfo":{"title":"CoordinateInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoordinateInfo"}],"abstract":[{"type":"text","text":"Represents the coordinate information returned by the "},{"code":"coordinateInfoForPixel","type":"codeVoice"},{"type":"text","text":" or "},{"code":"coordinatesInfoForPixels","type":"codeVoice"},{"type":"text","text":" methods."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CoordinateInfo"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateInfo","type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/coordinateinfo"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Projection":{"url":"\/documentation\/mapboxmaps\/projection","abstract":[{"type":"text","text":"A collection of "},{"isActive":true,"type":"reference","identifier":"https:\/\/en.wikipedia.org\/wiki\/Web_Mercator_projection"},{"type":"text","text":" projection methods."}],"type":"topic","title":"Projection","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Projection","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"Projection","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Projection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMCoordinateBounds/longitudeSpan":{"navigatorTitle":[{"text":"longitudeSpan","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/mbmcoordinatebounds\/longitudespan","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCoordinateBounds\/longitudeSpan","abstract":[{"text":"Returns the absolute distance, in degrees, between the west and","type":"text"},{"text":" ","type":"text"},{"text":"east boundaries of these bounds.","type":"text"}],"role":"symbol","type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"longitudeSpan","kind":"identifier"}],"title":"longitudeSpan","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMCoordinateBounds/isEmpty":{"abstract":[{"text":"Returns whether the bounds are empty or not.","type":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isEmpty"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCoordinateBounds\/isEmpty","title":"isEmpty","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEmpty"}],"url":"\/documentation\/mapboxmaps\/mbmcoordinatebounds\/isempty"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateBounds/southwest":{"type":"topic","title":"southwest","abstract":[{"text":"Coordinate at the southwest corner.","type":"text"},{"text":" ","type":"text"},{"text":"Note: setting this field with invalid values (infinite, NaN) will crash the application.","type":"text"}],"navigatorTitle":[{"text":"southwest","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds\/southwest","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"southwest","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D","kind":"typeIdentifier"}],"url":"\/documentation\/mapboxmaps\/coordinatebounds\/southwest","role":"symbol","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","role":"collection","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","type":"topic","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateBounds/infiniteBounds":{"role":"symbol","title":"infiniteBounds","url":"\/documentation\/mapboxmaps\/coordinatebounds\/infinitebounds","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"infiniteBounds","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[{"text":"If set to ","type":"text"},{"type":"codeVoice","code":"true"},{"text":", an infinite (unconstrained) bounds covering the world coordinates would be used.","type":"text"},{"text":" ","type":"text"},{"text":"Coordinates provided in ","type":"text"},{"type":"codeVoice","code":"southwest"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"northeast"},{"text":" fields would be omitted and have no effect.","type":"text"}],"navigatorTitle":[{"text":"infiniteBounds","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds\/infiniteBounds","type":"topic"},"doc://com.mapbox.MapboxMaps/s7CVarArgP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMCoordinateBounds/south":{"kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/mbmcoordinatebounds\/south","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"south","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCoordinateBounds\/south","title":"south","abstract":[{"type":"text","text":"Returns the southern latitude of the bounds."}],"navigatorTitle":[{"text":"south","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMCoordinateBounds/isValid":{"kind":"symbol","type":"topic","abstract":[{"text":"Returns whether the bounds are valid or not.","type":"text"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isValid"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCoordinateBounds\/isValid","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isValid"}],"title":"isValid","url":"\/documentation\/mapboxmaps\/mbmcoordinatebounds\/isvalid"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"MBMCoordinateBounds"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"MBMCoordinateBounds","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMCoordinateBounds"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds\/infiniteBounds","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds\/northeast","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds\/southwest"]},{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds\/constrain(forPoint:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds\/contains(forArea:wrappedCoordinates:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds\/contains(forPoint:wrappedCoordinates:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds\/containsLatitude(forLatitude:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds\/containsLongitude(forLongitude:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds\/extend(forArea:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds\/extend(forPoint:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds\/init(southwest:northeast:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds\/init(southwest:northeast:infiniteBounds:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds\/intersects(forArea:wrappedCoordinates:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCoordinateBounds\/center","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCoordinateBounds\/crossesAntimeridian","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCoordinateBounds\/east","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCoordinateBounds\/isBounded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCoordinateBounds\/isEmpty","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCoordinateBounds\/isValid","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCoordinateBounds\/latitudeSpan","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCoordinateBounds\/longitudeSpan","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCoordinateBounds\/north","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCoordinateBounds\/northwest","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCoordinateBounds\/south","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCoordinateBounds\/southeast","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCoordinateBounds\/west"]},{"title":"Type Methods","anchor":"Type-Methods","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCoordinateBounds\/hullForA:b:","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCoordinateBounds\/singletonForPoint:","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCoordinateBounds\/world"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"]}]},{"path":"\/seeAlsoSections","op":"replace","value":[{"generated":true,"anchor":"MapboxMap","title":"MapboxMap","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBoundsZoom","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateInfo","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ContextMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapCenterAltitudeMode"]}]},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBMCoordinateBounds","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds~1contains(forPoint:wrappedCoordinates:)\/title","op":"replace","value":"containsForPoint:wrappedCoordinates:"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds~1contains(forPoint:wrappedCoordinates:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"containsForPoint:wrappedCoordinates:"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ContextMode\/title","op":"replace","value":"MBMContextMode"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ContextMode\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMContextMode"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ContextMode\/navigatorTitle","op":"replace","value":[{"text":"MBMContextMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds~1constrain(forPoint:)\/title","op":"replace","value":"constrainForPoint:"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds~1constrain(forPoint:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"constrainForPoint:"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds~1containsLongitude(forLongitude:)\/title","op":"replace","value":"containsLongitudeForLongitude:"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds~1containsLongitude(forLongitude:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"containsLongitudeForLongitude:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds\/title","op":"replace","value":"MBMCoordinateBounds"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds\/fragments","op":"replace","value":[{"text":"MBMCoordinateBounds","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMCoordinateBounds"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds~1extend(forPoint:)\/title","op":"replace","value":"extendForPoint:"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds~1extend(forPoint:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"extendForPoint:"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/title","op":"replace","value":"MBMGlyphsRasterizationMode"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMGlyphsRasterizationMode"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/navigatorTitle","op":"replace","value":[{"text":"MBMGlyphsRasterizationMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBoundsZoom\/title","op":"replace","value":"MBMCoordinateBoundsZoom"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBoundsZoom\/fragments","op":"replace","value":[{"text":"MBMCoordinateBoundsZoom","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBoundsZoom\/navigatorTitle","op":"replace","value":[{"text":"MBMCoordinateBoundsZoom","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds~1northeast\/title","op":"replace","value":"northeast"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds~1northeast\/fragments","op":"replace","value":[{"text":"northeast","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds~1contains(forArea:wrappedCoordinates:)\/title","op":"replace","value":"containsForArea:wrappedCoordinates:"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds~1contains(forArea:wrappedCoordinates:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"containsForArea:wrappedCoordinates:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapCenterAltitudeMode\/title","op":"replace","value":"MBMMapCenterAltitudeMode"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapCenterAltitudeMode\/fragments","op":"replace","value":[{"text":"MBMMapCenterAltitudeMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapCenterAltitudeMode\/navigatorTitle","op":"replace","value":[{"text":"MBMMapCenterAltitudeMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds~1intersects(forArea:wrappedCoordinates:)\/title","op":"replace","value":"intersectsForArea:wrappedCoordinates:"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds~1intersects(forArea:wrappedCoordinates:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"intersectsForArea:wrappedCoordinates:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds~1extend(forArea:)\/title","op":"replace","value":"extendForArea:"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds~1extend(forArea:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"extendForArea:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds~1init(southwest:northeast:infiniteBounds:)\/title","op":"replace","value":"initWithSouthwest:northeast:infiniteBounds:"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds~1init(southwest:northeast:infiniteBounds:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSouthwest:northeast:infiniteBounds:"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds~1init(southwest:northeast:)\/title","op":"replace","value":"initWithSouthwest:northeast:"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds~1init(southwest:northeast:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithSouthwest:northeast:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds~1containsLatitude(forLatitude:)\/title","op":"replace","value":"containsLatitudeForLatitude:"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds~1containsLatitude(forLatitude:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"containsLatitudeForLatitude:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateInfo\/title","op":"replace","value":"MBMCoordinateInfo"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateInfo\/fragments","op":"replace","value":[{"text":"MBMCoordinateInfo","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateInfo\/navigatorTitle","op":"replace","value":[{"text":"MBMCoordinateInfo","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds~1southwest\/title","op":"replace","value":"southwest"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds~1southwest\/fragments","op":"replace","value":[{"kind":"identifier","text":"southwest"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds~1infiniteBounds\/title","op":"replace","value":"infiniteBounds"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds~1infiniteBounds\/fragments","op":"replace","value":[{"kind":"identifier","text":"infiniteBounds"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}