{"kind":"symbol","abstract":[{"type":"text","text":"Callback for changing a CustomRasterSource tile status."}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources"]]},"seeAlsoSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Source","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceInfo","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSourceData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterArraySource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/VectorSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PromoteId","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/VectorSourcePromoteId","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Scheme","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Encoding","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatus","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileFunctionCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetSize"],"anchor":"Sources","title":"Sources","generated":true}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomRasterSourceTileStatusChangedCallback"},{"kind":"text","text":" = ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMCanonicalTileID","text":"CanonicalTileID","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMCustomRasterSourceTileStatus","text":"CustomRasterSourceTileStatus","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatus"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"tileId","content":[{"type":"paragraph","inlineContent":[{"text":"A ","type":"text"},{"code":"canonical tile id","type":"codeVoice"},{"text":" of the tile.","type":"text"}]}]},{"name":"status","content":[{"inlineContent":[{"type":"text","text":"A new status of the tile."}],"type":"paragraph"}]}],"kind":"parameters"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/customrastersourcetilestatuschangedcallback"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/customrastersourcetilestatuschangedcallback"]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatusChangedCallback","interfaceLanguage":"swift"},"metadata":{"symbolKind":"typealias","modules":[{"name":"MapboxMaps"}],"navigatorTitle":[{"text":"CustomRasterSourceTileStatusChangedCallback","kind":"identifier"}],"role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomRasterSourceTileStatusChangedCallback","kind":"identifier"}],"externalID":"c:MBMCustomRasterSourceTileStatusChangedCallback.h@T@MBMCustomRasterSourceTileStatusChangedCallback","roleHeading":"Type Alias","title":"CustomRasterSourceTileStatusChangedCallback"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileFunctionCallback":{"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/tilefunctioncallback","title":"TileFunctionCallback","navigatorTitle":[{"text":"TileFunctionCallback","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileFunctionCallback","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileFunctionCallback","kind":"identifier"}],"abstract":[{"text":"Callback to do various operations for tile.","type":"text"},{"text":" ","type":"text"},{"text":"For example, fetching a tile or cancelling a tile request.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceOptions":{"abstract":[{"type":"text","text":"Options for custom raster source."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions","url":"\/documentation\/mapboxmaps\/customrastersourceoptions","role":"symbol","navigatorTitle":[{"text":"CustomRasterSourceOptions","kind":"identifier"}],"title":"CustomRasterSourceOptions","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomRasterSourceOptions","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ImageSource":{"url":"\/documentation\/mapboxmaps\/imagesource","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageSource","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"ImageSource","kind":"identifier"}],"title":"ImageSource","role":"symbol","abstract":[{"type":"text","text":"An image data source."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageSource"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GeoJSONSource":{"navigatorTitle":[{"text":"GeoJSONSource","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSource","kind":"symbol","abstract":[{"type":"text","text":"A GeoJSON data source."}],"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GeoJSONSource","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/geojsonsource","title":"GeoJSONSource"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/VectorSource":{"url":"\/documentation\/mapboxmaps\/vectorsource","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/VectorSource","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"VectorSource"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"A vector tile source."}],"kind":"symbol","title":"VectorSource","navigatorTitle":[{"kind":"identifier","text":"VectorSource"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/VectorSourcePromoteId":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/vectorsourcepromoteid","role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VectorSourcePromoteId","kind":"identifier"}],"abstract":[{"text":"Denotes promote-id setting for ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/VectorSource","type":"reference"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/VectorSourcePromoteId","navigatorTitle":[{"text":"VectorSourcePromoteId","kind":"identifier"}],"title":"VectorSourcePromoteId"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileRenderer":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer","kind":"symbol","abstract":[{"type":"text","text":"Interface for the direct rendering into the custom raster tiles."}],"type":"topic","navigatorTitle":[{"text":"CustomRasterSourceTileRenderer","kind":"identifier"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomRasterSourceTileRenderer","kind":"identifier"}],"title":"CustomRasterSourceTileRenderer","url":"\/documentation\/mapboxmaps\/customrastersourcetilerenderer"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GeoJSONSourceData":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSourceData","kind":"symbol","url":"\/documentation\/mapboxmaps\/geojsonsourcedata","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GeoJSONSourceData"}],"title":"GeoJSONSourceData","navigatorTitle":[{"kind":"identifier","text":"GeoJSONSourceData"}],"abstract":[{"type":"text","text":"Captures potential values of the "},{"type":"codeVoice","code":"data"},{"type":"text","text":" property of a GeoJSONSource."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterSource":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"RasterSource"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterSource","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"RasterSource"}],"url":"\/documentation\/mapboxmaps\/rastersource","title":"RasterSource","abstract":[{"text":"A raster tile source.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomGeometrySourceOptions":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomGeometrySourceOptions"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions","url":"\/documentation\/mapboxmaps\/customgeometrysourceoptions","title":"CustomGeometrySourceOptions","role":"symbol","abstract":[{"type":"text","text":"Options for custom geometry source."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CustomGeometrySourceOptions"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSource":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/customrastersource","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomRasterSource","kind":"identifier"}],"tags":[{"text":"SPI","type":"spi"}],"type":"topic","abstract":[{"text":"Describes a Custom Raster Source to be used in the style.","type":"text"}],"role":"symbol","title":"CustomRasterSource","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSource","navigatorTitle":[{"text":"CustomRasterSource","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterArraySource":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterArraySource","title":"RasterArraySource","url":"\/documentation\/mapboxmaps\/rasterarraysource","abstract":[{"type":"text","text":"A raster array source"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"RasterArraySource","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RasterArraySource","kind":"identifier"}],"tags":[{"text":"SPI","type":"spi"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","role":"collection","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","type":"topic","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Source":{"role":"symbol","type":"topic","abstract":[],"title":"Source","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Source"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Source"}],"url":"\/documentation\/mapboxmaps\/source","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Source"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceClientType":{"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/customrastersourceclienttype","title":"CustomRasterSourceClientType","navigatorTitle":[{"text":"CustomRasterSourceClientType","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomRasterSourceClientType","kind":"identifier"}],"abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudgetSize":{"navigatorTitle":[{"text":"TileCacheBudgetSize","kind":"identifier"}],"title":"TileCacheBudgetSize","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetSize","abstract":[{"type":"text","text":"Defines a TileCacheBudgetSize, which can be set as either a megabyte or tile count limit."},{"type":"text","text":" "},{"type":"text","text":"Whenever tile cache goes over the defined limit"},{"type":"text","text":" "},{"type":"text","text":"the least recently used tile will be evicted from the in-memory cache"}],"type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/tilecachebudgetsize","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileCacheBudgetSize","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Sources":{"url":"\/documentation\/mapboxmaps\/sources","type":"topic","kind":"article","abstract":[],"title":"Sources","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","role":"collection","type":"topic","abstract":[],"title":"MapboxMaps Documentation","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileStatusChangedCallback":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatusChangedCallback","type":"topic","title":"CustomRasterSourceTileStatusChangedCallback","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomRasterSourceTileStatusChangedCallback"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceTileStatusChangedCallback"}],"url":"\/documentation\/mapboxmaps\/customrastersourcetilestatuschangedcallback","kind":"symbol","abstract":[{"type":"text","text":"Callback for changing a CustomRasterSource tile status."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Scheme":{"type":"topic","navigatorTitle":[{"text":"Scheme","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Scheme","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Scheme","url":"\/documentation\/mapboxmaps\/scheme","abstract":[{"type":"text","text":"Influences the y direction of the tile coordinates. The global-mercator (aka Spherical Mercator) profile is assumed."}],"title":"Scheme","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileStatus":{"url":"\/documentation\/mapboxmaps\/customrastersourcetilestatus","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatus","title":"CustomRasterSourceTileStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomRasterSourceTileStatus"}],"kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceTileStatus"}],"abstract":[{"type":"text","text":"CustomRasterSource tile status."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceClient":{"title":"CustomRasterSourceClient","url":"\/documentation\/mapboxmaps\/customrastersourceclient","role":"symbol","navigatorTitle":[{"text":"CustomRasterSourceClient","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomRasterSourceClient","kind":"identifier"}],"abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Encoding":{"kind":"symbol","title":"Encoding","type":"topic","navigatorTitle":[{"text":"Encoding","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/encoding","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Encoding","abstract":[{"text":"The encoding used by this source. Mapbox Terrain RGB is used by default","type":"text"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Encoding","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceType":{"role":"symbol","title":"SourceType","navigatorTitle":[{"text":"SourceType","kind":"identifier"}],"abstract":[{"text":"Struct of supported Source Types","type":"text"},{"text":" ","type":"text"},{"text":"Docs : https:\/\/docs.mapbox.com\/mapbox-gl-js\/style-spec\/sources\/","type":"text"}],"url":"\/documentation\/mapboxmaps\/sourcetype","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceType","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SourceType","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PromoteId":{"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/promoteid","title":"PromoteId","navigatorTitle":[{"text":"PromoteId","kind":"identifier"}],"deprecated":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PromoteId","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PromoteId","kind":"identifier"}],"abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomGeometrySource":{"title":"CustomGeometrySource","url":"\/documentation\/mapboxmaps\/customgeometrysource","abstract":[{"type":"text","text":"Describes a Custom Geometry Source to be used in the style"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySource","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CustomGeometrySource"}],"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomGeometrySource"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CanonicalTileID":{"type":"topic","abstract":[{"text":"Represents a tile coordinate.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID","kind":"symbol","url":"\/documentation\/mapboxmaps\/canonicaltileid","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CanonicalTileID"}],"navigatorTitle":[{"kind":"identifier","text":"CanonicalTileID"}],"title":"CanonicalTileID"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileData":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileData","url":"\/documentation\/mapboxmaps\/customrastersourcetiledata","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomRasterSourceTileData"}],"role":"symbol","kind":"symbol","title":"CustomRasterSourceTileData","abstract":[{"type":"text","text":"Data for a specific CustomRasterSource tile."}],"navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceTileData"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceInfo":{"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/sourceinfo","title":"SourceInfo","navigatorTitle":[{"text":"SourceInfo","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceInfo","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SourceInfo","kind":"identifier"}],"abstract":[{"text":"Information about a Source","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterDemSource":{"title":"RasterDemSource","role":"symbol","abstract":[{"type":"text","text":"A RGB-encoded raster DEM source"}],"navigatorTitle":[{"kind":"identifier","text":"RasterDemSource"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource","type":"topic","url":"\/documentation\/mapboxmaps\/rasterdemsource","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"RasterDemSource"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Alias","op":"replace","path":"\/metadata\/roleHeading"},{"value":"MBMCustomRasterSourceTileStatusChangedCallback","op":"replace","path":"\/metadata\/title"},{"value":"typealias","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileStatusChangedCallback"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileStatusChangedCallback"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatus","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileFunctionCallback"],"title":"Sources","anchor":"Sources","generated":true}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"text":"void (^)(MBMCanonicalTileID *, enum MBMCustomRasterSourceTileStatus)","preciseIdentifier":"c:BFv(#*$objc(cs)MBMCanonicalTileID#$@E@MBMCustomRasterSourceTileStatus)","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"MBMCustomRasterSourceTileStatusChangedCallback","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MBMTileFunctionCallback","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileFunctionCallback\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileFunctionCallback\/fragments","value":[{"text":"MBMTileFunctionCallback","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileFunctionCallback\/navigatorTitle","value":[{"text":"MBMTileFunctionCallback","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/title","value":"MBMCustomRasterSourceOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/fragments","value":[{"kind":"identifier","text":"MBMCustomRasterSourceOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/navigatorTitle","value":[{"text":"MBMCustomRasterSourceOptions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer\/title","value":"MBMCustomRasterSourceTileRenderer"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer\/fragments","value":[{"text":"MBMCustomRasterSourceTileRenderer","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer\/navigatorTitle","value":[{"text":"MBMCustomRasterSourceTileRenderer","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions\/title","value":"MBMCustomGeometrySourceOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions\/fragments","value":[{"kind":"identifier","text":"MBMCustomGeometrySourceOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions\/navigatorTitle","value":[{"text":"MBMCustomGeometrySourceOptions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType\/title","value":"MBMCustomRasterSourceClientType"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType\/fragments","value":[{"text":"MBMCustomRasterSourceClientType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType\/navigatorTitle","value":[{"kind":"identifier","text":"MBMCustomRasterSourceClientType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatusChangedCallback\/title","value":"MBMCustomRasterSourceTileStatusChangedCallback"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatusChangedCallback\/fragments","value":[{"text":"MBMCustomRasterSourceTileStatusChangedCallback","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatusChangedCallback\/navigatorTitle","value":[{"text":"MBMCustomRasterSourceTileStatusChangedCallback","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatus\/title","value":"MBMCustomRasterSourceTileStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatus\/fragments","value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatus\/navigatorTitle","value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient\/title","value":"MBMCustomRasterSourceClient"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient\/fragments","value":[{"kind":"identifier","text":"MBMCustomRasterSourceClient"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient\/navigatorTitle","value":[{"text":"MBMCustomRasterSourceClient","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/title","value":"MBMCanonicalTileID"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/fragments","value":[{"text":"MBMCanonicalTileID","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/navigatorTitle","value":[{"text":"MBMCanonicalTileID","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileData\/title","value":"MBMCustomRasterSourceTileData"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileData\/fragments","value":[{"text":"MBMCustomRasterSourceTileData","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileData\/navigatorTitle","value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileData"}]}]}]}