{"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH"],"type":"conformsTo"}],"abstract":[{"text":"Represents depth range (min & max) used to render 3D content.","type":"text"}],"seeAlsoSections":[{"title":"Layers","anchor":"Layers","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerInfo","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/BackgroundLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CircleLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillExtrusionLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationIndicatorLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterParticleLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SkyLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderConfiguration","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerHost","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerMapProjection","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ElevationData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Slot","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SlotLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerAtPosition","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClipLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClipLayerTypes"]}],"sections":[],"metadata":{"externalID":"c:objc(cs)MBMDepthRange","role":"symbol","modules":[{"name":"MapboxMaps"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DepthRange","kind":"identifier"}],"roleHeading":"Class","navigatorTitle":[{"text":"DepthRange","kind":"identifier"}],"title":"DepthRange","symbolKind":"class"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DepthRange","kind":"identifier"}],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/DepthRange"},"topicSections":[{"title":"Initializers","anchor":"Initializers","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/DepthRange\/init(min:max:)"]},{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/DepthRange\/max","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/DepthRange\/min"]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers"]]},"variants":[{"paths":["\/documentation\/mapboxmaps\/depthrange"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/depthrange"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.mapbox.MapboxMaps/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerRenderParameters":{"abstract":[{"type":"text","text":"Parameters that define the current camera position for a "},{"type":"codeVoice","code":"CustomLayerHost::render()"},{"type":"text","text":" function."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CustomLayerRenderParameters"}],"title":"CustomLayerRenderParameters","url":"\/documentation\/mapboxmaps\/customlayerrenderparameters","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomLayerRenderParameters"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","role":"collection","type":"topic","abstract":[],"title":"MapboxMaps Documentation","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LocationIndicatorLayer":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationIndicatorLayer","title":"LocationIndicatorLayer","role":"symbol","url":"\/documentation\/mapboxmaps\/locationindicatorlayer","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationIndicatorLayer"}],"abstract":[{"text":"Location Indicator layer.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"LocationIndicatorLayer"}],"kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","role":"collection","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","type":"topic","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterParticleLayer":{"kind":"symbol","abstract":[{"type":"text","text":"Particle animation driven by textures such as wind maps."}],"tags":[{"type":"spi","text":"SPI"}],"type":"topic","url":"\/documentation\/mapboxmaps\/rasterparticlelayer","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterParticleLayer","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"RasterParticleLayer"}],"title":"RasterParticleLayer","navigatorTitle":[{"kind":"identifier","text":"RasterParticleLayer"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ElevationData":{"title":"ElevationData","abstract":[{"text":"Interface that provides access to elevation data.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ElevationData","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"ElevationData","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/elevationdata","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ElevationData","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Slot":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/slot","abstract":[{"text":"A pre-specified location in the style where layer will be added to","type":"text"},{"text":" ","type":"text"},{"text":"(such as on top of existing land layers, but below all labels).","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Slot","type":"topic","navigatorTitle":[{"text":"Slot","kind":"identifier"}],"title":"Slot","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Slot","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerAtPosition":{"title":"LayerAtPosition","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LayerAtPosition","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"LayerAtPosition","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/layeratposition","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerAtPosition","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ClipLayer":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClipLayer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ClipLayer"}],"abstract":[{"type":"text","text":"Layer that removes 3D content from map."}],"title":"ClipLayer","url":"\/documentation\/mapboxmaps\/cliplayer","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClipLayer"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerMapProjection":{"title":"CustomLayerMapProjection","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomLayerMapProjection"}],"navigatorTitle":[{"kind":"identifier","text":"CustomLayerMapProjection"}],"kind":"symbol","role":"symbol","abstract":[],"url":"\/documentation\/mapboxmaps\/customlayermapprojection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerMapProjection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerHost":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomLayerHost"}],"navigatorTitle":[{"kind":"identifier","text":"CustomLayerHost"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerHost","role":"symbol","url":"\/documentation\/mapboxmaps\/customlayerhost","abstract":[{"text":"Interface for hosting a custom map style layer.","type":"text"}],"title":"CustomLayerHost","type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SkyLayer":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SkyLayer","title":"SkyLayer","type":"topic","url":"\/documentation\/mapboxmaps\/skylayer","abstract":[{"text":"A spherical dome around the map that is always rendered behind all other layers.","type":"text"},{"text":" ","type":"text"},{"text":"Warning: As of v10.6.0, ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Atmosphere"},{"text":" is the preferred method for atmospheric styling. Sky layer is not supported by the globe projection, and will be phased out in future major release.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SkyLayer"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SkyLayer"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/DepthRange":{"navigatorTitle":[{"text":"DepthRange","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DepthRange","kind":"identifier"}],"title":"DepthRange","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/depthrange","abstract":[{"text":"Represents depth range (min & max) used to render 3D content.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/DepthRange"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/DepthRange/max":{"abstract":[{"type":"text","text":"Maximum depth value. Ranges between 0 and 1."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"max"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/DepthRange\/max","url":"\/documentation\/mapboxmaps\/depthrange\/max","role":"symbol","title":"max","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"max"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FillExtrusionLayer":{"navigatorTitle":[{"text":"FillExtrusionLayer","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/fillextrusionlayer","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillExtrusionLayer","title":"FillExtrusionLayer","kind":"symbol","abstract":[{"type":"text","text":"An extruded (3D) polygon."}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FillExtrusionLayer","kind":"identifier"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/BackgroundLayer":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"BackgroundLayer"}],"url":"\/documentation\/mapboxmaps\/backgroundlayer","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/BackgroundLayer","role":"symbol","title":"BackgroundLayer","type":"topic","abstract":[{"text":"The background color or pattern of the map.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"BackgroundLayer"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/DepthRange/init(min:max:)":{"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"min","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":", ","kind":"text"},{"text":"max","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/DepthRange\/init(min:max:)","title":"init(min:max:)","url":"\/documentation\/mapboxmaps\/depthrange\/init(min:max:)","navigatorTitle":[{"text":"initWithMin:max:","kind":"identifier"}],"kind":"symbol","abstract":[],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SymbolLayer":{"title":"SymbolLayer","navigatorTitle":[{"text":"SymbolLayer","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"An icon or a text label."}],"kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/symbollayer","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolLayer","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SymbolLayer","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FillLayer":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FillLayer","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillLayer","role":"symbol","type":"topic","kind":"symbol","title":"FillLayer","navigatorTitle":[{"text":"FillLayer","kind":"identifier"}],"abstract":[{"text":"A filled polygon with an optional stroked border.","type":"text"}],"url":"\/documentation\/mapboxmaps\/filllayer"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerType":{"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LayerType","kind":"identifier"}],"title":"LayerType","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType","abstract":[{"type":"text","text":"Struct of supported Layer rendering types"}],"navigatorTitle":[{"text":"LayerType","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/layertype","kind":"symbol"},"doc://com.mapbox.MapboxMaps/SH":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerRenderConfiguration":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderConfiguration","type":"topic","abstract":[{"type":"text","text":"Note! This is an experimental feature. It can be changed or removed in future versions."}],"title":"CustomLayerRenderConfiguration","url":"\/documentation\/mapboxmaps\/customlayerrenderconfiguration","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomLayerRenderConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"CustomLayerRenderConfiguration"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelLayer":{"title":"ModelLayer","abstract":[{"text":"A layer to render 3D Models.","type":"text"}],"tags":[{"text":"SPI","type":"spi"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ModelLayer"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ModelLayer"}],"url":"\/documentation\/mapboxmaps\/modellayer","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LineLayer":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineLayer","abstract":[{"text":"A stroked line.","type":"text"}],"url":"\/documentation\/mapboxmaps\/linelayer","title":"LineLayer","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LineLayer"}],"navigatorTitle":[{"kind":"identifier","text":"LineLayer"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayer":{"navigatorTitle":[{"text":"CustomLayer","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayer","tags":[{"text":"SPI","type":"spi"}],"kind":"symbol","abstract":[{"type":"text","text":"Layer with custom rendering implementation"}],"title":"CustomLayer","type":"topic","url":"\/documentation\/mapboxmaps\/customlayer","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomLayer","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layer":{"navigatorTitle":[{"kind":"identifier","text":"Layer"}],"title":"Layer","url":"\/documentation\/mapboxmaps\/layer","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Layer"}]},"doc://com.mapbox.MapboxMaps/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Atmosphere":{"url":"\/documentation\/mapboxmaps\/atmosphere","abstract":[{"text":"A style’s fog property is a global effect that improves depth perception by fading out distant objects.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Atmosphere","role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Atmosphere"}],"title":"Atmosphere","navigatorTitle":[{"kind":"identifier","text":"Atmosphere"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SlotLayer":{"navigatorTitle":[{"kind":"identifier","text":"SlotLayer"}],"abstract":[{"text":"Marks the position of a slot.","type":"text"}],"title":"SlotLayer","url":"\/documentation\/mapboxmaps\/slotlayer","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SlotLayer"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SlotLayer","type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterLayer":{"role":"symbol","title":"RasterLayer","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterLayer","navigatorTitle":[{"kind":"identifier","text":"RasterLayer"}],"url":"\/documentation\/mapboxmaps\/rasterlayer","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"RasterLayer"}],"kind":"symbol","abstract":[{"type":"text","text":"Raster map textures such as satellite imagery."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer":{"navigatorTitle":[{"kind":"identifier","text":"HillshadeLayer"}],"kind":"symbol","title":"HillshadeLayer","abstract":[{"text":"Client-side hillshading visualization based on DEM data. Currently, the implementation only supports Mapbox Terrain RGB and Mapzen Terrarium tiles.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer","url":"\/documentation\/mapboxmaps\/hillshadelayer","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"HillshadeLayer"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layers":{"role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers","type":"topic","abstract":[],"title":"Layers","url":"\/documentation\/mapboxmaps\/layers","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeatmapLayer":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"A heatmap."}],"title":"HeatmapLayer","url":"\/documentation\/mapboxmaps\/heatmaplayer","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HeatmapLayer"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeatmapLayer"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/DepthRange/min":{"role":"symbol","title":"min","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"min"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"}],"url":"\/documentation\/mapboxmaps\/depthrange\/min","kind":"symbol","abstract":[{"type":"text","text":"Minimum depth value. Ranges between 0 and 1."}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/DepthRange\/min","navigatorTitle":[{"text":"min","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CircleLayer":{"role":"symbol","abstract":[{"text":"A filled circle.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CircleLayer","url":"\/documentation\/mapboxmaps\/circlelayer","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CircleLayer","kind":"identifier"}],"navigatorTitle":[{"text":"CircleLayer","kind":"identifier"}],"title":"CircleLayer","type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ClipLayerTypes":{"navigatorTitle":[{"text":"ClipLayerTypes","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClipLayerTypes","url":"\/documentation\/mapboxmaps\/cliplayertypes","role":"symbol","abstract":[{"type":"text","text":"Layer types that will also be removed if fallen below this clip layer."}],"title":"ClipLayerTypes","kind":"symbol","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ClipLayerTypes","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerInfo":{"url":"\/documentation\/mapboxmaps\/layerinfo","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LayerInfo"}],"navigatorTitle":[{"kind":"identifier","text":"LayerInfo"}],"title":"LayerInfo","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerInfo","abstract":[{"type":"text","text":"Information about a layer"}]},"doc://com.mapbox.MapboxMaps/objc(cs)NSObject":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.mapbox.MapboxMaps/SQ":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MBMDepthRange"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MBMDepthRange","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"MBMDepthRange","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/DepthRange\/max","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/DepthRange\/min"]},{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/DepthRange\/init(min:max:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"]}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Layers","anchor":"Layers","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderConfiguration","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerHost","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerMapProjection","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ElevationData"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBMDepthRange"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/title","value":"MBMCustomLayerRenderParameters"},{"op":"replace","value":[{"kind":"identifier","text":"MBMCustomLayerRenderParameters"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/fragments"},{"op":"replace","value":[{"text":"MBMCustomLayerRenderParameters","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/navigatorTitle"},{"op":"replace","value":"MBMElevationData","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ElevationData\/title"},{"op":"replace","value":[{"text":"MBMElevationData","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ElevationData\/fragments"},{"op":"replace","value":[{"text":"MBMElevationData","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ElevationData\/navigatorTitle"},{"op":"replace","value":"MBMCustomLayerMapProjection","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerMapProjection\/title"},{"op":"replace","value":[{"text":"MBMCustomLayerMapProjection","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerMapProjection\/fragments"},{"op":"replace","value":[{"text":"MBMCustomLayerMapProjection","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerMapProjection\/navigatorTitle"},{"op":"replace","value":"MBMCustomLayerHost","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBMCustomLayerHost"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost\/fragments"},{"op":"replace","value":[{"text":"MBMCustomLayerHost","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost\/navigatorTitle"},{"op":"replace","value":"MBMDepthRange","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1DepthRange\/title"},{"op":"replace","value":[{"text":"MBMDepthRange","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1DepthRange\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MBMDepthRange"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1DepthRange\/navigatorTitle"},{"op":"replace","value":"max","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1DepthRange~1max\/title"},{"op":"replace","value":[{"text":"max","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1DepthRange~1max\/fragments"},{"op":"replace","value":"initWithMin:max:","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1DepthRange~1init(min:max:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithMin:max:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1DepthRange~1init(min:max:)\/fragments"},{"op":"replace","value":"MBMCustomLayerRenderConfiguration","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderConfiguration\/title"},{"op":"replace","value":[{"text":"MBMCustomLayerRenderConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MBMCustomLayerRenderConfiguration"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderConfiguration\/navigatorTitle"},{"op":"replace","value":"min","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1DepthRange~1min\/title"},{"op":"replace","value":[{"text":"min","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1DepthRange~1min\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}