{"topicSections":[{"title":"Initializers","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineWidthUnit\/init(rawValue:)"],"anchor":"Initializers"},{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineWidthUnit\/rawValue"],"anchor":"Instance-Properties"},{"title":"Type Properties","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineWidthUnit\/meters","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineWidthUnit\/pixels"],"anchor":"Type-Properties"},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineWidthUnit\/Equatable-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineWidthUnit\/RawRepresentable-Implementations"],"anchor":"Default-Implementations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"seeAlsoSections":[{"title":"Layer Property Values","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Value","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Anchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CirclePitchAlignment","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CirclePitchScale","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CircleTranslateAnchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillExtrusionTranslateAnchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillTranslateAnchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeIlluminationAnchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconAnchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconPitchAlignment","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconRotationAlignment","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconTextFit","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconTranslateAnchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineCap","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineJoin","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineTranslateAnchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterResampling","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResolvedImage","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResolvedImageData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValue","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValueKind","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SkyType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleColor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleTransition","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolPlacement","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolZOrder","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextAnchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextJustify","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextPitchAlignment","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextRotationAlignment","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextTransform","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextTranslateAnchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextWritingMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Visibility","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TransitionOptions-swift.struct","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelScaleMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolElevationReference","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/BackgroundPitchAlignment","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillExtrusionBaseAlignment","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillExtrusionHeightAlignment","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillElevationReference","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineElevationReference","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelElevationReference","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CircleElevationReference","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageContent","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageStretches"],"anchor":"Layer-Property-Values"}],"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/Se","doc:\/\/com.mapbox.MapboxMaps\/SE","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH","doc:\/\/com.mapbox.MapboxMaps\/SY","doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"],"type":"conformsTo","kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer-Property-Values"]]},"variants":[{"paths":["\/documentation\/mapboxmaps\/linewidthunit"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Selects the unit of line-width. The same unit is automatically used for line-blur and line-offset. Note: This is an experimental property and might be removed in a future release."}],"metadata":{"navigatorTitle":[{"text":"LineWidthUnit","kind":"identifier"}],"title":"LineWidthUnit","role":"symbol","externalID":"s:10MapboxMaps13LineWidthUnitV","roleHeading":"Structure","tags":[{"type":"spi","text":"SPI"}],"symbolKind":"struct","modules":[{"name":"MapboxMaps"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LineWidthUnit","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LineWidthUnit","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineWidthUnit","interfaceLanguage":"swift"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SymbolElevationReference":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SymbolElevationReference","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/symbolelevationreference","navigatorTitle":[{"text":"SymbolElevationReference","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Selects the base of symbol-elevation."}],"title":"SymbolElevationReference","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolElevationReference","tags":[{"text":"SPI","type":"spi"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LineWidthUnit":{"kind":"symbol","abstract":[{"type":"text","text":"Selects the unit of line-width. The same unit is automatically used for line-blur and line-offset. Note: This is an experimental property and might be removed in a future release."}],"url":"\/documentation\/mapboxmaps\/linewidthunit","title":"LineWidthUnit","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"LineWidthUnit"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineWidthUnit","tags":[{"type":"spi","text":"SPI"}],"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LineWidthUnit"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/BackgroundPitchAlignment":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/BackgroundPitchAlignment","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BackgroundPitchAlignment"}],"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"BackgroundPitchAlignment"}],"abstract":[{"text":"Orientation of background layer.","type":"text"}],"tags":[{"type":"spi","text":"SPI"}],"title":"BackgroundPitchAlignment","kind":"symbol","url":"\/documentation\/mapboxmaps\/backgroundpitchalignment"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CirclePitchAlignment":{"url":"\/documentation\/mapboxmaps\/circlepitchalignment","kind":"symbol","type":"topic","navigatorTitle":[{"text":"CirclePitchAlignment","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CirclePitchAlignment","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CirclePitchAlignment","role":"symbol","abstract":[{"type":"text","text":"Orientation of circle when map is pitched."}],"title":"CirclePitchAlignment"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layer-Property-Values":{"kind":"article","url":"\/documentation\/mapboxmaps\/layer-property-values","type":"topic","abstract":[],"title":"Layer Property Values","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer-Property-Values"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CircleTranslateAnchor":{"navigatorTitle":[{"text":"CircleTranslateAnchor","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CircleTranslateAnchor","kind":"identifier"}],"type":"topic","title":"CircleTranslateAnchor","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CircleTranslateAnchor","url":"\/documentation\/mapboxmaps\/circletranslateanchor","abstract":[{"text":"Controls the frame of reference for ","type":"text"},{"type":"codeVoice","code":"circle-translate"},{"text":".","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelType":{"navigatorTitle":[{"text":"ModelType","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Defines rendering behavior of model in respect to other 3D scene objects."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ModelType","kind":"identifier"}],"tags":[{"text":"SPI","type":"spi"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelType","title":"ModelType","kind":"symbol","url":"\/documentation\/mapboxmaps\/modeltype"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LineWidthUnit/pixels":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"pixels"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10MapboxMaps13LineWidthUnitV","kind":"typeIdentifier","text":"LineWidthUnit"}],"kind":"symbol","title":"pixels","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineWidthUnit\/pixels","tags":[{"type":"spi","text":"SPI"}],"role":"symbol","abstract":[{"type":"text","text":"Width is rendered in pixels."}],"type":"topic","url":"\/documentation\/mapboxmaps\/linewidthunit\/pixels"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","role":"collection","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","type":"topic","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePropertyValue":{"role":"symbol","abstract":[{"text":"Holds a style property value with meta data.","type":"text"}],"title":"StylePropertyValue","url":"\/documentation\/mapboxmaps\/stylepropertyvalue","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValue","navigatorTitle":[{"kind":"identifier","text":"StylePropertyValue"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StylePropertyValue"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelElevationReference":{"url":"\/documentation\/mapboxmaps\/modelelevationreference","abstract":[{"type":"text","text":"Selects the base of the model. Some modes might require precomputed elevation data in the tileset."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ModelElevationReference"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelElevationReference","navigatorTitle":[{"kind":"identifier","text":"ModelElevationReference"}],"kind":"symbol","type":"topic","role":"symbol","title":"ModelElevationReference","tags":[{"type":"spi","text":"SPI"}]},"doc://com.mapbox.MapboxMaps/s8SendableP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CircleElevationReference":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CircleElevationReference","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CircleElevationReference"}],"abstract":[{"type":"text","text":"Selects the base of circle-elevation. Some modes might require precomputed elevation data in the tileset."}],"navigatorTitle":[{"kind":"identifier","text":"CircleElevationReference"}],"tags":[{"type":"spi","text":"SPI"}],"url":"\/documentation\/mapboxmaps\/circleelevationreference","title":"CircleElevationReference","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FillExtrusionHeightAlignment":{"abstract":[{"type":"text","text":"Controls the behavior of fill extrusion height over terrain"}],"role":"symbol","title":"FillExtrusionHeightAlignment","type":"topic","tags":[{"text":"SPI","type":"spi"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FillExtrusionHeightAlignment"}],"url":"\/documentation\/mapboxmaps\/fillextrusionheightalignment","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillExtrusionHeightAlignment","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FillExtrusionHeightAlignment"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SymbolZOrder":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolZOrder","title":"SymbolZOrder","role":"symbol","url":"\/documentation\/mapboxmaps\/symbolzorder","type":"topic","abstract":[{"type":"text","text":"Determines whether overlapping symbols in the same layer are rendered in the order that they appear in the data source or by their y-position relative to the viewport. To control the order and prioritization of symbols otherwise, use "},{"type":"codeVoice","code":"symbol-sort-key"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SymbolZOrder"}],"navigatorTitle":[{"kind":"identifier","text":"SymbolZOrder"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FillExtrusionTranslateAnchor":{"url":"\/documentation\/mapboxmaps\/fillextrusiontranslateanchor","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FillExtrusionTranslateAnchor","kind":"identifier"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"FillExtrusionTranslateAnchor","kind":"identifier"}],"abstract":[{"text":"Controls the frame of reference for ","type":"text"},{"code":"fill-extrusion-translate","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillExtrusionTranslateAnchor","title":"FillExtrusionTranslateAnchor"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TextTransform":{"navigatorTitle":[{"kind":"identifier","text":"TextTransform"}],"type":"topic","kind":"symbol","title":"TextTransform","abstract":[{"type":"text","text":"Specifies how to capitalize text, similar to the CSS "},{"type":"codeVoice","code":"text-transform"},{"type":"text","text":" property."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextTransform","url":"\/documentation\/mapboxmaps\/texttransform","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TextTransform"}]},"doc://com.mapbox.MapboxMaps/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LineWidthUnit/Equatable-Implementations":{"title":"Equatable Implementations","abstract":[],"type":"topic","role":"collectionGroup","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineWidthUnit\/Equatable-Implementations","url":"\/documentation\/mapboxmaps\/linewidthunit\/equatable-implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LineCap":{"abstract":[{"text":"The display of line endings.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineCap","role":"symbol","url":"\/documentation\/mapboxmaps\/linecap","navigatorTitle":[{"text":"LineCap","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LineCap","kind":"identifier"}],"title":"LineCap"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Anchor":{"navigatorTitle":[{"kind":"identifier","text":"Anchor"}],"type":"topic","title":"Anchor","abstract":[{"type":"text","text":"Whether extruded geometries are lit relative to the map or viewport."}],"url":"\/documentation\/mapboxmaps\/anchor","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Anchor"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Anchor"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LineWidthUnit/RawRepresentable-Implementations":{"url":"\/documentation\/mapboxmaps\/linewidthunit\/rawrepresentable-implementations","title":"RawRepresentable Implementations","type":"topic","role":"collectionGroup","kind":"article","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineWidthUnit\/RawRepresentable-Implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResolvedImageData":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResolvedImageData"}],"type":"topic","title":"ResolvedImageData","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"ResolvedImageData"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResolvedImageData","url":"\/documentation\/mapboxmaps\/resolvedimagedata","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CirclePitchScale":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CirclePitchScale","kind":"identifier"}],"role":"symbol","type":"topic","title":"CirclePitchScale","kind":"symbol","url":"\/documentation\/mapboxmaps\/circlepitchscale","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CirclePitchScale","abstract":[{"type":"text","text":"Controls the scaling behavior of the circle when the map is pitched."}],"navigatorTitle":[{"text":"CirclePitchScale","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TextPitchAlignment":{"url":"\/documentation\/mapboxmaps\/textpitchalignment","title":"TextPitchAlignment","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TextPitchAlignment"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TextPitchAlignment"}],"abstract":[{"text":"Orientation of text when map is pitched.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextPitchAlignment"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TextTranslateAnchor":{"type":"topic","abstract":[{"text":"Controls the frame of reference for ","type":"text"},{"type":"codeVoice","code":"text-translate"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextTranslateAnchor","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TextTranslateAnchor"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TextTranslateAnchor"}],"kind":"symbol","title":"TextTranslateAnchor","url":"\/documentation\/mapboxmaps\/texttranslateanchor"},"doc://com.mapbox.MapboxMaps/SE":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SE","title":"Swift.Encodable","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/IconPitchAlignment":{"url":"\/documentation\/mapboxmaps\/iconpitchalignment","type":"topic","title":"IconPitchAlignment","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IconPitchAlignment"}],"navigatorTitle":[{"kind":"identifier","text":"IconPitchAlignment"}],"abstract":[{"type":"text","text":"Orientation of icon when map is pitched."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconPitchAlignment","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TextRotationAlignment":{"kind":"symbol","title":"TextRotationAlignment","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TextRotationAlignment","kind":"identifier"}],"navigatorTitle":[{"text":"TextRotationAlignment","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/textrotationalignment","role":"symbol","abstract":[{"type":"text","text":"In combination with "},{"type":"codeVoice","code":"symbol-placement"},{"type":"text","text":", determines the rotation behavior of the individual glyphs forming the text."}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextRotationAlignment"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeIlluminationAnchor":{"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"HillshadeIlluminationAnchor"}],"type":"topic","url":"\/documentation\/mapboxmaps\/hillshadeilluminationanchor","title":"HillshadeIlluminationAnchor","abstract":[{"type":"text","text":"Direction of light source when map is rotated."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeIlluminationAnchor","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HillshadeIlluminationAnchor"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/IconTranslateAnchor":{"type":"topic","title":"IconTranslateAnchor","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconTranslateAnchor","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IconTranslateAnchor"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"IconTranslateAnchor"}],"url":"\/documentation\/mapboxmaps\/icontranslateanchor","abstract":[{"type":"text","text":"Controls the frame of reference for "},{"type":"codeVoice","code":"icon-translate"},{"type":"text","text":"."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleTransition":{"role":"symbol","title":"StyleTransition","navigatorTitle":[{"kind":"identifier","text":"StyleTransition"}],"type":"topic","abstract":[{"text":"The transition property for a layer.","type":"text"},{"text":" ","type":"text"},{"text":"A transition property controls timing for the interpolation between a","type":"text"},{"text":" ","type":"text"},{"text":"transitionable style property’s previous value and new value.","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"StyleTransition"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleTransition","url":"\/documentation\/mapboxmaps\/styletransition"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TextWritingMode":{"navigatorTitle":[{"text":"TextWritingMode","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/textwritingmode","kind":"symbol","title":"TextWritingMode","abstract":[{"text":"The property allows control over a symbol’s orientation. Note that the property values act as a hint, so that a symbol whose language doesn’t support the provided orientation will be laid out in its natural orientation. Example: English point symbol will be rendered horizontally even if array value contains single ‘vertical’ enum value. For symbol with point placement, the order of elements in an array define priority order for the placement of an orientation variant. For symbol with line placement, the default text writing mode is either [‘horizontal’, ‘vertical’] or [‘vertical’, ‘horizontal’], the order doesn’t affect the placement.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TextWritingMode","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextWritingMode"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FillTranslateAnchor":{"abstract":[{"type":"text","text":"Controls the frame of reference for "},{"type":"codeVoice","code":"fill-translate"},{"type":"text","text":"."}],"url":"\/documentation\/mapboxmaps\/filltranslateanchor","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FillTranslateAnchor"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FillTranslateAnchor"}],"title":"FillTranslateAnchor","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillTranslateAnchor"},"doc://com.mapbox.MapboxMaps/Se":{"title":"Swift.Decodable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/Se"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SymbolPlacement":{"title":"SymbolPlacement","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SymbolPlacement","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"SymbolPlacement","kind":"identifier"}],"abstract":[{"text":"Label placement relative to its geometry.","type":"text"}],"url":"\/documentation\/mapboxmaps\/symbolplacement","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolPlacement","role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LineWidthUnit/rawValue":{"abstract":[],"role":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/linewidthunit\/rawvalue","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"kind":"symbol","title":"rawValue","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineWidthUnit\/rawValue","tags":[{"text":"SPI","type":"spi"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleColor":{"title":"StyleColor","abstract":[{"type":"text","text":"Represents a color as defined by the "},{"type":"reference","isActive":true,"identifier":"https:\/\/docs.mapbox.com\/style-spec\/reference\/types\/#color"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StyleColor","kind":"identifier"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"StyleColor","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleColor","url":"\/documentation\/mapboxmaps\/stylecolor","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","role":"collection","type":"topic","abstract":[],"title":"MapboxMaps Documentation","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterResampling":{"abstract":[{"type":"text","text":"The resampling\/interpolation method to use for overscaling, also known as texture magnification filter"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterResampling","role":"symbol","url":"\/documentation\/mapboxmaps\/rasterresampling","navigatorTitle":[{"text":"RasterResampling","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RasterResampling","kind":"identifier"}],"title":"RasterResampling"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LineWidthUnit/init(rawValue:)":{"type":"topic","role":"symbol","tags":[{"text":"SPI","type":"spi"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineWidthUnit\/init(rawValue:)","url":"\/documentation\/mapboxmaps\/linewidthunit\/init(rawvalue:)","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FillElevationReference":{"navigatorTitle":[{"kind":"identifier","text":"FillElevationReference"}],"url":"\/documentation\/mapboxmaps\/fillelevationreference","type":"topic","kind":"symbol","title":"FillElevationReference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillElevationReference","tags":[{"type":"spi","text":"SPI"}],"role":"symbol","abstract":[{"text":"Selects the base of fill-elevation. Some modes might require precomputed elevation data in the tileset.","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FillElevationReference"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/IconAnchor":{"url":"\/documentation\/mapboxmaps\/iconanchor","abstract":[{"type":"text","text":"Part of the icon placed closest to the anchor."}],"type":"topic","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IconAnchor","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconAnchor","navigatorTitle":[{"text":"IconAnchor","kind":"identifier"}],"title":"IconAnchor","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelScaleMode":{"kind":"symbol","tags":[{"type":"spi","text":"SPI"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ModelScaleMode"}],"title":"ModelScaleMode","url":"\/documentation\/mapboxmaps\/modelscalemode","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelScaleMode","abstract":[{"type":"text","text":"Defines scaling mode. Only applies to location-indicator type layers."}],"navigatorTitle":[{"kind":"identifier","text":"ModelScaleMode"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LineJoin":{"kind":"symbol","title":"LineJoin","abstract":[{"text":"The display of lines when joining.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"LineJoin"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LineJoin"}],"url":"\/documentation\/mapboxmaps\/linejoin","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineJoin","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePropertyValueKind":{"title":"StylePropertyValueKind","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"StylePropertyValueKind"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"StylePropertyValueKind"}],"abstract":[{"type":"text","text":"Describes the kind of a style property value."}],"url":"\/documentation\/mapboxmaps\/stylepropertyvaluekind","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValueKind"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FillExtrusionBaseAlignment":{"type":"topic","title":"FillExtrusionBaseAlignment","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillExtrusionBaseAlignment","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FillExtrusionBaseAlignment"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FillExtrusionBaseAlignment"}],"url":"\/documentation\/mapboxmaps\/fillextrusionbasealignment","abstract":[{"text":"Controls the behavior of fill extrusion base over terrain","type":"text"}],"tags":[{"type":"spi","text":"SPI"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Value":{"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Value"}],"url":"\/documentation\/mapboxmaps\/value","navigatorTitle":[{"kind":"identifier","text":"Value"}],"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Value","title":"Value","role":"symbol","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SkyType":{"url":"\/documentation\/mapboxmaps\/skytype","navigatorTitle":[{"text":"SkyType","kind":"identifier"}],"type":"topic","kind":"symbol","title":"SkyType","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SkyType","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SkyType","kind":"identifier"}],"abstract":[{"type":"text","text":"The type of the sky"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TextJustify":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TextJustify","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextJustify","title":"TextJustify","url":"\/documentation\/mapboxmaps\/textjustify","kind":"symbol","type":"topic","navigatorTitle":[{"text":"TextJustify","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Text justification options.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/IconTextFit":{"url":"\/documentation\/mapboxmaps\/icontextfit","kind":"symbol","type":"topic","navigatorTitle":[{"text":"IconTextFit","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IconTextFit","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconTextFit","role":"symbol","abstract":[{"type":"text","text":"Scales the icon to fit around the associated text."}],"title":"IconTextFit"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TransitionOptions-swift.struct":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TransitionOptions-swift.struct","kind":"symbol","type":"topic","title":"TransitionOptions","url":"\/documentation\/mapboxmaps\/transitionoptions-swift.struct","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TransitionOptions","kind":"identifier"}],"navigatorTitle":[{"text":"TransitionOptions","kind":"identifier"}],"abstract":[{"text":"The ","type":"text"},{"code":"TransitionOptions","type":"codeVoice"},{"text":" control timing for the interpolation between a transitionable style","type":"text"},{"text":" ","type":"text"},{"text":"property’s previous value and new value. These can be used to define the style default property","type":"text"},{"text":" ","type":"text"},{"text":"transition behavior. Also, any transitionable style property may also have its own ","type":"text"},{"code":"-transition","type":"codeVoice"},{"text":" ","type":"text"},{"text":"property that defines specific transition timing for that specific layer property, overriding","type":"text"},{"text":" ","type":"text"},{"text":"the global transition values.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LineTranslateAnchor":{"abstract":[{"type":"text","text":"Controls the frame of reference for "},{"code":"line-translate","type":"codeVoice"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineTranslateAnchor","role":"symbol","url":"\/documentation\/mapboxmaps\/linetranslateanchor","navigatorTitle":[{"text":"LineTranslateAnchor","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LineTranslateAnchor","kind":"identifier"}],"title":"LineTranslateAnchor"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ImageStretches":{"kind":"symbol","title":"ImageStretches","abstract":[{"type":"text","text":"Describes the image stretch areas."}],"navigatorTitle":[{"kind":"identifier","text":"ImageStretches"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageStretches"}],"url":"\/documentation\/mapboxmaps\/imagestretches","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageStretches","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LineWidthUnit/meters":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineWidthUnit\/meters","title":"meters","role":"symbol","abstract":[{"type":"text","text":"Width is rendered in meters."}],"tags":[{"text":"SPI","type":"spi"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"meters"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps13LineWidthUnitV","text":"LineWidthUnit"}],"type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/linewidthunit\/meters"},"https://docs.mapbox.com/style-spec/reference/types/#color":{"title":"Mapbox Style Spec","url":"https:\/\/docs.mapbox.com\/style-spec\/reference\/types\/#color","type":"link","identifier":"https:\/\/docs.mapbox.com\/style-spec\/reference\/types\/#color","titleInlineContent":[{"type":"text","text":"Mapbox Style Spec"}]},"doc://com.mapbox.MapboxMaps/SY":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/IconRotationAlignment":{"url":"\/documentation\/mapboxmaps\/iconrotationalignment","abstract":[{"type":"text","text":"In combination with "},{"type":"codeVoice","code":"symbol-placement"},{"type":"text","text":", determines the rotation behavior of icons."}],"role":"symbol","title":"IconRotationAlignment","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IconRotationAlignment"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconRotationAlignment","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"IconRotationAlignment"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ImageContent":{"abstract":[{"text":"Describes the image content, e.g. where text can be fit into an image.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageContent","role":"symbol","url":"\/documentation\/mapboxmaps\/imagecontent","navigatorTitle":[{"text":"ImageContent","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageContent","kind":"identifier"}],"title":"ImageContent"},"doc://com.mapbox.MapboxMaps/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LineElevationReference":{"type":"topic","abstract":[{"text":"Selects the base of line-elevation. Some modes might require precomputed elevation data in the tileset.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LineElevationReference"}],"navigatorTitle":[{"kind":"identifier","text":"LineElevationReference"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/lineelevationreference","tags":[{"type":"spi","text":"SPI"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineElevationReference","title":"LineElevationReference"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TextAnchor":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TextAnchor"}],"abstract":[{"type":"text","text":"Part of the text placed closest to the anchor."}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextAnchor","url":"\/documentation\/mapboxmaps\/textanchor","title":"TextAnchor","navigatorTitle":[{"kind":"identifier","text":"TextAnchor"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResolvedImage":{"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResolvedImage","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ResolvedImage","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/resolvedimage","role":"symbol","title":"ResolvedImage","navigatorTitle":[{"kind":"identifier","text":"ResolvedImage"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Visibility":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Visibility","kind":"identifier"}],"type":"topic","title":"Visibility","role":"symbol","abstract":[],"navigatorTitle":[{"text":"Visibility","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/visibility","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Visibility","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValue\/title","value":"MBMStylePropertyValue"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValue\/fragments","value":[{"kind":"identifier","text":"MBMStylePropertyValue"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValue\/navigatorTitle","value":[{"kind":"identifier","text":"MBMStylePropertyValue"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValueKind\/title","value":"MBMStylePropertyValueKind"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValueKind\/fragments","value":[{"kind":"identifier","text":"MBMStylePropertyValueKind"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValueKind\/navigatorTitle","value":[{"text":"MBMStylePropertyValueKind","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ImageStretches\/title","value":"MBMImageStretches"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ImageStretches\/fragments","value":[{"text":"MBMImageStretches","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ImageStretches\/navigatorTitle","value":[{"kind":"identifier","text":"MBMImageStretches"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ImageContent\/title","value":"MBMImageContent"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ImageContent\/fragments","value":[{"text":"MBMImageContent","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ImageContent\/navigatorTitle","value":[{"text":"MBMImageContent","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}