{"relationshipsSections":[{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/s15BitwiseCopyableP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH","doc:\/\/com.mapbox.MapboxMaps\/SY","doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions","interfaceLanguage":"swift"},"seeAlsoSections":[{"anchor":"Debug","generated":true,"title":"Debug","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapViewDebugOptions"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapDebugOptions"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance"]]},"abstract":[{"type":"text","text":"Options for enabling debugging features in a map."}],"metadata":{"roleHeading":"Enumeration","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapDebugOptions","kind":"identifier"}],"navigatorTitle":[{"text":"MapDebugOptions","kind":"identifier"}],"symbolKind":"enum","modules":[{"name":"MapboxMaps"}],"title":"MapDebugOptions","externalID":"c:@E@MBMMapDebugOptions"},"sections":[],"topicSections":[{"anchor":"Enumeration-Cases","generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/collision","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/depthBuffer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/layers2DWireframe","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/layers3DWireframe","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/light","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/modelBounds","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/overdraw","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/parseStatus","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/stencilClip","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/terrainWireframe","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/tileBorders","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/timestamps"]},{"anchor":"Initializers","generated":true,"title":"Initializers","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/init(rawValue:)"]},{"anchor":"Default-Implementations","generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/Equatable-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/RawRepresentable-Implementations"]}],"variants":[{"paths":["\/documentation\/mapboxmaps\/mapdebugoptions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/mapdebugoptions"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Performance":{"kind":"article","type":"topic","title":"Performance and investigations","url":"\/documentation\/mapboxmaps\/performance","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapDebugOptions/timestamps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/timestamps","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timestamps","kind":"identifier"}],"navigatorTitle":[{"text":"MBMMapDebugOptionsTimestamps","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/mapdebugoptions\/timestamps","abstract":[{"text":"Each tile shows a timestamps with modified and expires dates or n\/a if","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"timestamp is not available."}],"type":"topic","title":"MapDebugOptions.timestamps","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapViewDebugOptions":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapViewDebugOptions","abstract":[{"type":"text","text":"Options for enabling debugging features in a map."}],"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapViewDebugOptions","kind":"identifier"}],"navigatorTitle":[{"text":"MapViewDebugOptions","kind":"identifier"}],"title":"MapViewDebugOptions","kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/mapviewdebugoptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapDebugOptions/modelBounds":{"abstract":[{"text":"Show 3D model bounding boxes.","type":"text"}],"url":"\/documentation\/mapboxmaps\/mapdebugoptions\/modelbounds","kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/modelBounds","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"modelBounds","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"MBMMapDebugOptionsModelBounds","kind":"identifier"}],"title":"MapDebugOptions.modelBounds"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapDebugOptions/init(rawValue:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"title":"init(rawValue:)","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/init(rawValue:)","url":"\/documentation\/mapboxmaps\/mapdebugoptions\/init(rawvalue:)","role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapDebugOptions/stencilClip":{"type":"topic","url":"\/documentation\/mapboxmaps\/mapdebugoptions\/stencilclip","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"stencilClip"}],"navigatorTitle":[{"kind":"identifier","text":"MBMMapDebugOptionsStencilClip"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/stencilClip","title":"MapDebugOptions.stencilClip","abstract":[{"text":"The stencil buffer is shown instead of the color buffer.","type":"text"}],"role":"symbol","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapDebugOptions/tileBorders":{"url":"\/documentation\/mapboxmaps\/mapdebugoptions\/tileborders","type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/tileBorders","role":"symbol","abstract":[{"type":"text","text":"Edges of tile boundaries are shown as thick, red lines to help diagnose"},{"type":"text","text":" "},{"type":"text","text":"tile clipping issues."}],"title":"MapDebugOptions.tileBorders","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tileBorders"}],"navigatorTitle":[{"kind":"identifier","text":"MBMMapDebugOptionsTileBorders"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapDebugOptions":{"role":"symbol","title":"MapDebugOptions","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapDebugOptions","kind":"identifier"}],"navigatorTitle":[{"text":"MapDebugOptions","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"Options for enabling debugging features in a map.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions","url":"\/documentation\/mapboxmaps\/mapdebugoptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapDebugOptions/parseStatus":{"abstract":[{"type":"text","text":"Each tile shows its tile coordinate (x\/y\/z) in the upper-left corner."}],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"parseStatus"}],"role":"symbol","kind":"symbol","url":"\/documentation\/mapboxmaps\/mapdebugoptions\/parsestatus","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/parseStatus","title":"MapDebugOptions.parseStatus","navigatorTitle":[{"kind":"identifier","text":"MBMMapDebugOptionsParseStatus"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapDebugOptions/depthBuffer":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"depthBuffer","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/depthBuffer","type":"topic","title":"MapDebugOptions.depthBuffer","role":"symbol","url":"\/documentation\/mapboxmaps\/mapdebugoptions\/depthbuffer","abstract":[{"text":"The depth buffer is shown instead of the color buffer.","type":"text"}],"navigatorTitle":[{"text":"MBMMapDebugOptionsDepthBuffer","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapDebugOptions/layers2DWireframe":{"abstract":[{"text":"Show a wireframe for 2d layers. Currently supported for GL backend only.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MBMMapDebugOptionsLayers2DWireframe"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/layers2DWireframe","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"layers2DWireframe"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/mapdebugoptions\/layers2dwireframe","title":"MapDebugOptions.layers2DWireframe"},"doc://com.mapbox.MapboxMaps/s15BitwiseCopyableP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s15BitwiseCopyableP","title":"Swift.BitwiseCopyable","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapDebugOptions/RawRepresentable-Implementations":{"kind":"article","title":"RawRepresentable Implementations","abstract":[],"url":"\/documentation\/mapboxmaps\/mapdebugoptions\/rawrepresentable-implementations","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/RawRepresentable-Implementations","type":"topic","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","role":"collection","type":"topic","abstract":[],"title":"MapboxMaps Documentation","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","role":"collection","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","type":"topic","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapDebugOptions/collision":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/collision","kind":"symbol","abstract":[{"type":"text","text":"Edges of glyphs and symbols are shown as faint, green lines to help"},{"type":"text","text":" "},{"type":"text","text":"diagnose collision and label placement issues."}],"title":"MapDebugOptions.collision","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"collision"}],"url":"\/documentation\/mapboxmaps\/mapdebugoptions\/collision","navigatorTitle":[{"kind":"identifier","text":"MBMMapDebugOptionsCollision"}],"role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapDebugOptions/light":{"title":"MapDebugOptions.light","abstract":[{"type":"text","text":"Each tile shows its local lighting conditions in the upper-left corner. (If "},{"type":"codeVoice","code":"lights"},{"type":"text","text":" properties are used, otherwise they show zero.)"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBMMapDebugOptionsLight"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"light"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/light","url":"\/documentation\/mapboxmaps\/mapdebugoptions\/light"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapDebugOptions/layers3DWireframe":{"abstract":[{"text":"Show a wireframe for 3d layers. Currently supported for GL backend only.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"layers3DWireframe","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/mapdebugoptions\/layers3dwireframe","type":"topic","title":"MapDebugOptions.layers3DWireframe","kind":"symbol","navigatorTitle":[{"text":"MBMMapDebugOptionsLayers3DWireframe","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/layers3DWireframe"},"doc://com.mapbox.MapboxMaps/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s8SendableP","title":"Swift.Sendable"},"doc://com.mapbox.MapboxMaps/SQ":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapDebugOptions/overdraw":{"url":"\/documentation\/mapboxmaps\/mapdebugoptions\/overdraw","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/overdraw","title":"MapDebugOptions.overdraw","navigatorTitle":[{"text":"MBMMapDebugOptionsOverdraw","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"overdraw","kind":"identifier"}],"abstract":[{"text":"Each drawing operation is replaced by a translucent fill. Overlapping","type":"text"},{"text":" ","type":"text"},{"text":"drawing operations appear more prominent to help diagnose overdrawing.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapDebugOptions/Equatable-Implementations":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/Equatable-Implementations","kind":"article","title":"Equatable Implementations","abstract":[],"role":"collectionGroup","type":"topic","url":"\/documentation\/mapboxmaps\/mapdebugoptions\/equatable-implementations"},"doc://com.mapbox.MapboxMaps/SH":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/SY":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SY","title":"Swift.RawRepresentable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapDebugOptions/terrainWireframe":{"url":"\/documentation\/mapboxmaps\/mapdebugoptions\/terrainwireframe","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBMMapDebugOptionsTerrainWireframe"}],"abstract":[{"text":"Show a wireframe for terrain. Currently supported for GL backend only.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/terrainWireframe","title":"MapDebugOptions.terrainWireframe","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"terrainWireframe"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"MBMMapDebugOptions"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMMapDebugOptions"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMMapDebugOptions"}]},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/collision","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/depthBuffer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/layers2DWireframe","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/layers3DWireframe","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/light","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/modelBounds","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/overdraw","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/parseStatus","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/stencilClip","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/terrainWireframe","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/tileBorders","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/timestamps"],"anchor":"Enumeration-Cases"}]},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","op":"replace","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBMMapDebugOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions~1timestamps\/title","op":"replace","value":"MBMMapDebugOptionsTimestamps"},{"value":[{"kind":"identifier","text":"MBMMapDebugOptionsTimestamps"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions~1timestamps\/fragments"},{"value":"MBMMapDebugOptionsModelBounds","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions~1modelBounds\/title"},{"value":[{"kind":"identifier","text":"MBMMapDebugOptionsModelBounds"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions~1modelBounds\/fragments"},{"value":"MBMMapDebugOptionsStencilClip","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions~1stencilClip\/title"},{"value":[{"text":"MBMMapDebugOptionsStencilClip","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions~1stencilClip\/fragments"},{"value":"MBMMapDebugOptionsTileBorders","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions~1tileBorders\/title"},{"value":[{"text":"MBMMapDebugOptionsTileBorders","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions~1tileBorders\/fragments"},{"value":"MBMMapDebugOptions","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions\/title"},{"value":[{"kind":"identifier","text":"MBMMapDebugOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions\/fragments"},{"value":[{"kind":"identifier","text":"MBMMapDebugOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions\/navigatorTitle"},{"value":"MBMMapDebugOptionsParseStatus","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions~1parseStatus\/title"},{"value":[{"text":"MBMMapDebugOptionsParseStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions~1parseStatus\/fragments"},{"value":"MBMMapDebugOptionsDepthBuffer","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions~1depthBuffer\/title"},{"value":[{"kind":"identifier","text":"MBMMapDebugOptionsDepthBuffer"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions~1depthBuffer\/fragments"},{"value":"MBMMapDebugOptionsLayers2DWireframe","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions~1layers2DWireframe\/title"},{"value":[{"kind":"identifier","text":"MBMMapDebugOptionsLayers2DWireframe"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions~1layers2DWireframe\/fragments"},{"value":"MBMMapDebugOptionsCollision","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions~1collision\/title"},{"value":[{"text":"MBMMapDebugOptionsCollision","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions~1collision\/fragments"},{"value":"MBMMapDebugOptionsLight","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions~1light\/title"},{"value":[{"text":"MBMMapDebugOptionsLight","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions~1light\/fragments"},{"value":"MBMMapDebugOptionsLayers3DWireframe","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions~1layers3DWireframe\/title"},{"value":[{"kind":"identifier","text":"MBMMapDebugOptionsLayers3DWireframe"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions~1layers3DWireframe\/fragments"},{"value":"MBMMapDebugOptionsOverdraw","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions~1overdraw\/title"},{"value":[{"text":"MBMMapDebugOptionsOverdraw","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions~1overdraw\/fragments"},{"value":"MBMMapDebugOptionsTerrainWireframe","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions~1terrainWireframe\/title"},{"value":[{"kind":"identifier","text":"MBMMapDebugOptionsTerrainWireframe"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions~1terrainWireframe\/fragments"}]}]}