{"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Access to location is allowed.","type":"text"}],"metadata":{"title":"PermissionStatus.granted","navigatorTitle":[{"kind":"identifier","text":"MBXPermissionStatusGranted"}],"externalID":"c:@E@MBXPermissionStatus@MBXPermissionStatusGranted","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"granted"}],"role":"symbol","modules":[{"name":"MapboxCommon"}],"symbolKind":"case","roleHeading":"Case"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/permissionstatus\/granted"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/permissionstatus\/granted"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"granted","kind":"identifier"}],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"inlineContent":[{"text":"This type of permission is defined for platforms that do not have foreground\/background access granularity.","type":"text"},{"text":" ","type":"text"},{"text":"If you use Android version 28 or older and need a background location access it can be configured with","type":"text"},{"text":" ","type":"text"},{"code":"com.mapbox.common.location.sdk28_use_background_permissions","type":"codeVoice"},{"text":" setting.","type":"text"},{"text":" ","type":"text"},{"text":"To set ","type":"text"},{"code":"com.mapbox.common.location.sdk28_use_background_permissions","type":"codeVoice"},{"text":" add an mapbox-location-config.xml file with","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"the following content:"}],"type":"paragraph"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus\/granted"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","type":"topic","abstract":[],"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PermissionStatus/granted":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus\/granted","role":"symbol","abstract":[{"text":"Access to location is allowed.","type":"text"}],"kind":"symbol","url":"\/documentation\/mapboxcommon\/permissionstatus\/granted","title":"PermissionStatus.granted","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"granted","kind":"identifier"}],"navigatorTitle":[{"text":"MBXPermissionStatusGranted","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","kind":"symbol","type":"topic","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Location-APIs":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","role":"collectionGroup","abstract":[],"kind":"article","url":"\/documentation\/mapboxmaps\/location-apis","title":"Location","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PermissionStatus":{"abstract":[{"text":"Location permissions granted by user to the app.","type":"text"}],"title":"PermissionStatus","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/mapboxcommon\/permissionstatus","navigatorTitle":[{"text":"PermissionStatus","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PermissionStatus","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"MBXPermissionStatusGranted","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"MBXPermissionStatusGranted","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"MBXPermissionStatusGranted","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"MBXPermissionStatusGranted","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus~1granted\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBXPermissionStatusGranted"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus~1granted\/fragments"},{"op":"replace","value":"MBXPermissionStatus","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/title"},{"op":"replace","value":[{"text":"MBXPermissionStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MBXPermissionStatus"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/navigatorTitle"}]}]}