{"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"errorOccurred","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forError","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMOfflineRegionError","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionError","text":"OfflineRegionError"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/offlineregionobserver\/erroroccurred(forerror:)"]},{"paths":["\/documentation\/mapboxmaps\/offlineregionobserver\/erroroccurred(forerror:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionObserver"]]},"kind":"symbol","metadata":{"platforms":[],"externalID":"c:objc(pl)MBMOfflineRegionObserver(im)errorOccurredForError:","required":true,"modules":[{"name":"MapboxMaps"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorOccurred"},{"text":"(","kind":"text"},{"text":"forError","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OfflineRegionError","preciseIdentifier":"c:objc(cs)MBMOfflineRegionError"},{"text":")","kind":"text"}],"title":"errorOccurred(forError:)","role":"symbol","symbolKind":"method","navigatorTitle":[{"text":"errorOccurredForError:","kind":"identifier"}]},"abstract":[{"text":"Implement this method to be notified of errors encountered while downloading","type":"text"},{"type":"text","text":" "},{"text":"regional resources. Such errors may be recoverable; for example the implementation","type":"text"},{"type":"text","text":" "},{"text":"will attempt to re-request failed resources based on an exponential backoff","type":"text"},{"type":"text","text":" "},{"type":"text","text":"algorithm, or when it detects that network access has been restored."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionObserver\/errorOccurred(forError:)"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionError":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"OfflineRegionError"}],"abstract":[{"type":"text","text":"Describes an offline request response error."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionError","url":"\/documentation\/mapboxmaps\/offlineregionerror","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"OfflineRegionError"}],"role":"symbol","title":"OfflineRegionError","deprecated":true},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","role":"collection","abstract":[],"kind":"article","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMaps":{"kind":"article","abstract":[{"text":"Maps rendering SDK also known as GL-Native","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","type":"topic","url":"\/documentation\/mapboxmaps\/coremaps","role":"collectionGroup","title":"Core Maps API"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Offline":{"kind":"article","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","type":"topic","url":"\/documentation\/mapboxmaps\/offline","role":"collectionGroup","title":"Offline Support"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","url":"\/documentation\/mapboxmaps","type":"topic","role":"collection","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionObserver":{"kind":"symbol","navigatorTitle":[{"text":"OfflineRegionObserver","kind":"identifier"}],"abstract":[{"text":"A region can have a single observer, which gets notified whenever a change","type":"text"},{"text":" ","type":"text"},{"text":"to the region’s status occurs.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionObserver","type":"topic","url":"\/documentation\/mapboxmaps\/offlineregionobserver","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OfflineRegionObserver"}],"role":"symbol","title":"OfflineRegionObserver","deprecated":true},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionObserver/errorOccurred(forError:)":{"url":"\/documentation\/mapboxmaps\/offlineregionobserver\/erroroccurred(forerror:)","title":"errorOccurred(forError:)","kind":"symbol","navigatorTitle":[{"text":"errorOccurredForError:","kind":"identifier"}],"deprecated":true,"required":true,"abstract":[{"type":"text","text":"Implement this method to be notified of errors encountered while downloading"},{"type":"text","text":" "},{"type":"text","text":"regional resources. Such errors may be recoverable; for example the implementation"},{"type":"text","text":" "},{"type":"text","text":"will attempt to re-request failed resources based on an exponential backoff"},{"type":"text","text":" "},{"type":"text","text":"algorithm, or when it detects that network access has been restored."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorOccurred"},{"kind":"text","text":"("},{"text":"forError","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"OfflineRegionError","preciseIdentifier":"c:objc(cs)MBMOfflineRegionError"},{"text":")","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionObserver\/errorOccurred(forError:)","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"errorOccurredForError:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"errorOccurredForError:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"errorOccurredForError:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMOfflineRegionError","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionError","text":"MBMOfflineRegionError"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionError\/title","op":"replace","value":"MBMOfflineRegionError"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionError\/fragments","value":[{"text":"MBMOfflineRegionError","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"MBMOfflineRegionError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionError\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionObserver\/title","value":"MBMOfflineRegionObserver"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionObserver\/fragments","value":[{"kind":"identifier","text":"MBMOfflineRegionObserver"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionObserver\/navigatorTitle","op":"replace","value":[{"text":"MBMOfflineRegionObserver","kind":"identifier"}]},{"value":"errorOccurredForError:","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionObserver~1errorOccurred(forError:)\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionObserver~1errorOccurred(forError:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"errorOccurredForError:","kind":"identifier"}],"op":"replace"}]}]}