{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/httpservicefactory\/setcancellationcallbackforcallback(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/httpservicefactory\/setcancellationcallbackforcallback(_:)"]}],"abstract":[{"type":"text","text":"Sets the cancellation callback for HTTP request events"}],"metadata":{"role":"symbol","modules":[{"name":"MapboxCommon"}],"title":"setCancellationCallbackForCallback(_:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setCancellationCallbackForCallback"},{"kind":"text","text":"("},{"text":"HttpServiceCancellationCallback","preciseIdentifier":"c:MBXHttpServiceCancellationCallback.h@T@MBXHttpServiceCancellationCallback","kind":"typeIdentifier"},{"text":") -> any ","kind":"text"},{"text":"Cancelable","preciseIdentifier":"c:objc(pl)MBXCancelable","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"setCancellationCallbackForCallback:","kind":"identifier"}],"roleHeading":"Type Method","symbolKind":"method","externalID":"c:objc(cs)MBXHttpServiceFactory(cm)setCancellationCallbackForCallback:"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceFactory\/setCancellationCallbackForCallback(_:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setCancellationCallbackForCallback"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"callback"},{"text":": ","kind":"text"},{"kind":"keyword","text":"@escaping"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:MBXHttpServiceCancellationCallback.h@T@MBXHttpServiceCancellationCallback","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceCancellationCallback","text":"HttpServiceCancellationCallback","kind":"typeIdentifier"},{"text":") -> any ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Cancelable","preciseIdentifier":"c:objc(pl)MBXCancelable","text":"Cancelable"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"callback","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The callback for cancellations to be set."}]}]}]},{"kind":"content","content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"inlineContent":[{"text":"An automatic cancellation object. You should not get notifications","type":"text"},{"type":"text","text":" "},{"type":"text","text":"after you call cancel on this object. Setting a new callback will invalidate old Cancelable objects."}],"type":"paragraph"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceFactory"]]},"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpServiceFactory":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceFactory","kind":"symbol","navigatorTitle":[{"text":"HttpServiceFactory","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"HttpServiceFactory","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/mapboxcommon\/httpservicefactory","abstract":[{"text":"HTTP service factory.","type":"text"}],"title":"HttpServiceFactory"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpServiceCancellationCallback":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HttpServiceCancellationCallback"}],"type":"topic","url":"\/documentation\/mapboxcommon\/httpservicecancellationcallback","abstract":[{"text":"Callback for the HTTP request cancelled event.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceCancellationCallback","navigatorTitle":[{"text":"HttpServiceCancellationCallback","kind":"identifier"}],"title":"HttpServiceCancellationCallback","kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Cancelable":{"url":"\/documentation\/mapboxcommon\/cancelable","abstract":[{"type":"text","text":"Allows to cancel the associated asynchronous operation"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"Cancelable","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Cancelable","navigatorTitle":[{"text":"Cancelable","kind":"identifier"}],"title":"Cancelable","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpServiceFactory/setCancellationCallbackForCallback(_:)":{"url":"\/documentation\/mapboxcommon\/httpservicefactory\/setcancellationcallbackforcallback(_:)","role":"symbol","type":"topic","title":"setCancellationCallbackForCallback(_:)","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setCancellationCallbackForCallback","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:MBXHttpServiceCancellationCallback.h@T@MBXHttpServiceCancellationCallback","kind":"typeIdentifier","text":"HttpServiceCancellationCallback"},{"text":") -> any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MBXCancelable","text":"Cancelable"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"setCancellationCallbackForCallback:"}],"abstract":[{"text":"Sets the cancellation callback for HTTP request events","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceFactory\/setCancellationCallbackForCallback(_:)"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","abstract":[],"kind":"article","role":"collection","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","kind":"symbol","type":"topic","title":"MapboxCommon","url":"\/documentation\/mapboxcommon","role":"collection","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"setCancellationCallbackForCallback:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"setCancellationCallbackForCallback:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:Qoobjc(pl)MBXCancelable","text":"id<MBXCancelable>","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"setCancellationCallbackForCallback:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:BFv(#k#*$objc(cs)MBXHttpRequest)","text":"void (^)(unsigned long long, MBXHttpRequest *)","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"callback"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"callback","content":[{"type":"paragraph","inlineContent":[{"text":"The callback for cancellations to be set.","type":"text"}]}]}]}},{"op":"replace","path":"\/primaryContentSections\/2","value":{"content":[{"text":"Return Value","anchor":"return-value","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"An automatic cancellation object. You should not get notifications"},{"text":" ","type":"text"},{"type":"text","text":"after you call cancel on this object. Setting a new callback will invalidate old Cancelable objects."}],"type":"paragraph"}],"kind":"content"}},{"value":"MBXHttpServiceFactory","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceFactory\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceFactory\/fragments","value":[{"text":"MBXHttpServiceFactory","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceFactory\/navigatorTitle","op":"replace","value":[{"text":"MBXHttpServiceFactory","kind":"identifier"}]},{"op":"replace","value":"MBXHttpServiceCancellationCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceCancellationCallback\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceCancellationCallback\/fragments","value":[{"kind":"identifier","text":"MBXHttpServiceCancellationCallback"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceCancellationCallback\/navigatorTitle","op":"replace","value":[{"text":"MBXHttpServiceCancellationCallback","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/title","op":"replace","value":"MBXCancelable"},{"value":[{"kind":"identifier","text":"MBXCancelable"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/navigatorTitle","value":[{"text":"MBXCancelable","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceFactory~1setCancellationCallbackForCallback(_:)\/title","value":"setCancellationCallbackForCallback:","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceFactory~1setCancellationCallbackForCallback(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"setCancellationCallbackForCallback:","kind":"identifier"}],"op":"replace"}]}]}