{"abstract":[{"text":"Obtains the geographical coordinate information that corresponds to given points.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The points must exist in the coordinate space of the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapView"},{"type":"text","text":"."}],"variants":[{"paths":["\/documentation\/mapboxmaps\/mapboxmap\/coordinatesinfo(for:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"metadata":{"symbolKind":"method","role":"symbol","externalID":"s:10MapboxMaps0A3MapC15coordinatesInfo3forSaySo013MBMCoordinateE0CGSaySo7CGPointVG_tF","roleHeading":"Instance Method","modules":[{"name":"MapboxMaps"}],"title":"coordinatesInfo(for:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"coordinatesInfo","kind":"identifier"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"},{"kind":"text","text":"]) -> ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMCoordinateInfo","text":"CoordinateInfo"},{"kind":"text","text":"]"}]},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/coordinatesInfo(for:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"coordinatesInfo","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"points"},{"text":": [","kind":"text"},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"text":"]) -> [","kind":"text"},{"text":"CoordinateInfo","preciseIdentifier":"c:objc(cs)MBMCoordinateInfo","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateInfo"},{"kind":"text","text":"]"}],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The array of points to convert. Points must exist in the coordinate space"},{"text":" ","type":"text"},{"type":"text","text":"of the "},{"type":"codeVoice","code":"MapView"},{"text":".","type":"text"}]}],"name":"points"}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"inlineContent":[{"type":"text","text":"An array of "},{"type":"codeVoice","code":"CoordinateInfo"},{"type":"text","text":" records containing information about the geographical coordinates corresponding to the given points, including whether they are on the map surface."}],"type":"paragraph"}]},{"content":[{"text":"Discussion","level":2,"anchor":"discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The returned coordinate will be the closest position projected onto the map surface,"},{"type":"text","text":" "},{"type":"text","text":"in case the screen coordinate does not intersect with the map surface."}]}],"kind":"content"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","role":"collectionGroup","type":"topic","kind":"article","url":"\/documentation\/mapboxmaps\/mapboxmap-apis","title":"MapboxMap","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","url":"\/documentation\/mapboxmaps","type":"topic","role":"collection","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","navigatorTitle":[{"text":"MapboxMap","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap","title":"MapboxMap","abstract":[{"type":"text","text":"Provides access to the map model, including the camera, style, observable map events,"},{"type":"text","text":" "},{"type":"text","text":"and querying rendered features."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapboxMap"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/coordinatesInfo(for:)":{"role":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/coordinatesinfo(for:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"coordinatesInfo"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"text":"]) -> [","kind":"text"},{"text":"CoordinateInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMCoordinateInfo"},{"kind":"text","text":"]"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/coordinatesInfo(for:)","type":"topic","title":"coordinatesInfo(for:)","kind":"symbol","abstract":[{"type":"text","text":"Obtains the geographical coordinate information that corresponds to given points."},{"text":" ","type":"text"},{"text":"The points must exist in the coordinate space of the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapView"},{"text":".","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapView":{"title":"MapView","kind":"symbol","navigatorTitle":[{"text":"MapView","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MapView","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/mapview","abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapView"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","role":"collection","abstract":[],"kind":"article","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateInfo":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"CoordinateInfo"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CoordinateInfo"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateInfo","url":"\/documentation\/mapboxmaps\/coordinateinfo","abstract":[{"type":"text","text":"Represents the coordinate information returned by the "},{"type":"codeVoice","code":"coordinateInfoForPixel"},{"type":"text","text":" or "},{"code":"coordinatesInfoForPixels","type":"codeVoice"},{"text":" methods.","type":"text"}],"title":"CoordinateInfo","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateInfo\/title","value":"MBMCoordinateInfo","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateInfo\/fragments","value":[{"text":"MBMCoordinateInfo","kind":"identifier"}]},{"value":[{"text":"MBMCoordinateInfo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateInfo\/navigatorTitle"}]}]}