{"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCoordinateBounds\/hullForA:b:","interfaceLanguage":"occ"},"sections":[],"variants":[{"paths":["\/documentation\/mapboxmaps\/mbmcoordinatebounds\/hullfora:b:"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds","text":"MBMCoordinateBounds","preciseIdentifier":"c:objc(cs)MBMCoordinateBounds"},{"kind":"text","text":" *) "},{"text":"hullForA:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"text":") ","kind":"text"},{"text":"a","kind":"internalParam"},{"kind":"text","text":" "},{"text":"b:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":") "},{"text":"b","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"a","content":[{"inlineContent":[{"text":"The first of the two coordinates to fit.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"The second of the two coordinates to fit."}],"type":"paragraph"}],"name":"b"}]},{"content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"inlineContent":[{"type":"text","text":"The newly constructed record."}],"type":"paragraph"}],"kind":"content"}],"metadata":{"symbolKind":"method","modules":[{"name":"MapboxMaps"}],"externalID":"c:objc(cs)MBMCoordinateBounds(cm)hullForA:b:","fragments":[{"text":"+ ","kind":"text"},{"text":"hullForA:b:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"hullForA:b:"}],"role":"symbol","title":"hullForA:b:","roleHeading":"Type Method"},"kind":"symbol","abstract":[{"text":"Returns the convex hull of two points; the smallest bounds that contains both.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"url":"\/documentation\/mapboxmaps\/mapboxmap-apis","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","title":"MapboxMap","type":"topic","role":"collectionGroup","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateBounds":{"url":"\/documentation\/mapboxmaps\/coordinatebounds","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CoordinateBounds","kind":"identifier"}],"navigatorTitle":[{"text":"CoordinateBounds","kind":"identifier"}],"title":"CoordinateBounds","abstract":[{"type":"text","text":"A rectangular area as measured on a two-dimensional map projection."}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article","title":"MapboxMaps Documentation","abstract":[],"url":"\/documentation\/overview","role":"collection","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","title":"MapboxMaps","type":"topic","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMCoordinateBounds/hullForA:b:":{"navigatorTitle":[{"kind":"identifier","text":"hullForA:b:"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCoordinateBounds\/hullForA:b:","type":"topic","kind":"symbol","abstract":[{"text":"Returns the convex hull of two points; the smallest bounds that contains both.","type":"text"}],"title":"hullForA:b:","url":"\/documentation\/mapboxmaps\/mbmcoordinatebounds\/hullfora:b:","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"hullForA:b:"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds\/title","value":"MBMCoordinateBounds"},{"value":[{"kind":"identifier","text":"MBMCoordinateBounds"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds\/navigatorTitle","value":[{"kind":"identifier","text":"MBMCoordinateBounds"}]}]}]}