{"schemaVersion":{"patch":0,"major":0,"minor":3},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH"],"kind":"relationships"}],"seeAlsoSections":[{"title":"TileStore","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStoreOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudget","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInMegabytes","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInTiles","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCoverOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegion","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileRegionError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgress","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TilesetDescriptor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TilesetDescriptorOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgressCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreUsageMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileRegionError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileDataDomain","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateResult","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgressCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingErrorType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClearCacheError"],"generated":true,"anchor":"TileStore"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TileRegionEstimateProgress"}],"languages":["swift"]}]}],"abstract":[{"text":"A tile region’s estimate progress includes counts of the number of resources that have","type":"text"},{"type":"text","text":" "},{"text":"been estimated and the total number of resources as well as a partial result with the","type":"text"},{"type":"text","text":" "},{"type":"text","text":"current estimate, calculated using the data available at the moment."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/tileregionestimateprogress"]},{"paths":["\/documentation\/mapboxcommon\/tileregionestimateprogress"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs"]]},"topicSections":[{"generated":true,"title":"Initializers","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgress\/init(requiredResourceCount:erroredResourceCount:completedResourceCount:partialResult:)"],"anchor":"Initializers"},{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgress\/completedResourceCount","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgress\/erroredResourceCount","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgress\/partialResult","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgress\/requiredResourceCount"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgress\/isEqual(to:)"],"anchor":"Instance-Methods","generated":true}],"metadata":{"symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileRegionEstimateProgress","kind":"identifier"}],"title":"TileRegionEstimateProgress","navigatorTitle":[{"kind":"identifier","text":"TileRegionEstimateProgress"}],"modules":[{"name":"MapboxCommon"}],"externalID":"c:objc(cs)MBXTileRegionEstimateProgress","role":"symbol","roleHeading":"Class"},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgress","interfaceLanguage":"swift"},"references":{"doc://com.mapbox.MapboxMaps/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","title":"Swift.Equatable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TilesetDescriptorOptions":{"abstract":[{"type":"text","text":"Describes the tileset descriptor option values."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TilesetDescriptorOptions","kind":"identifier"}],"navigatorTitle":[{"text":"TilesetDescriptorOptions","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/mapboxmaps\/tilesetdescriptoroptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TilesetDescriptorOptions","title":"TilesetDescriptorOptions","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","url":"\/documentation\/overview","title":"MapboxMaps Documentation","type":"topic","role":"collection","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","url":"\/documentation\/mapboxmaps\/tilestore-apis","title":"TileStore APIs","abstract":[],"kind":"article","type":"topic","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudgetType":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetType","url":"\/documentation\/mapboxmaps\/tilecachebudgettype","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TileCacheBudgetType"}],"abstract":[],"title":"TileCacheBudgetType","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TileCacheBudgetType"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStoreObserver":{"type":"topic","navigatorTitle":[{"text":"TileStoreObserver","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileStoreObserver","kind":"identifier"}],"title":"TileStoreObserver","role":"symbol","url":"\/documentation\/mapboxmaps\/tilestoreobserver","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreObserver"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileRegionError":{"type":"topic","role":"symbol","abstract":[{"text":"Describes the reason for a tile region download request failure.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileRegionError","url":"\/documentation\/mapboxmaps\/tileregionerror","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"TileRegionError","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"TileRegionError"}],"title":"TileRegionError"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileOptions":{"url":"\/documentation\/mapboxmaps\/tileoptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileOptions","navigatorTitle":[{"text":"TileOptions","kind":"identifier"}],"abstract":[{"type":"text","text":"Options for custom geometry tiles."}],"type":"topic","role":"symbol","title":"TileOptions","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TileOptions"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateProgress/completedResourceCount":{"abstract":[{"type":"text","text":"The number of resources that have been estimated."}],"url":"\/documentation\/mapboxcommon\/tileregionestimateprogress\/completedresourcecount","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"completedResourceCount"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V","text":"UInt64"}],"navigatorTitle":[{"kind":"identifier","text":"completedResourceCount"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgress\/completedResourceCount","kind":"symbol","role":"symbol","title":"completedResourceCount"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudget":{"title":"TileCacheBudget","kind":"symbol","abstract":[],"url":"\/documentation\/mapboxmaps\/tilecachebudget","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudget","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TileCacheBudget","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"TileCacheBudget","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStoreUsageMode":{"type":"topic","role":"symbol","abstract":[{"text":"Describes tile store usage modes.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreUsageMode","url":"\/documentation\/mapboxmaps\/tilestoreusagemode","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileStoreUsageMode","kind":"identifier"}],"navigatorTitle":[{"text":"TileStoreUsageMode","kind":"identifier"}],"title":"TileStoreUsageMode"},"doc://com.mapbox.MapboxMaps/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileStoreOptions":{"type":"topic","navigatorTitle":[{"text":"TileStoreOptions","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileStoreOptions"}],"title":"TileStoreOptions","role":"symbol","url":"\/documentation\/mapboxcommon\/tilestoreoptions","abstract":[{"type":"text","text":"These constants can be used as keys for TileStore::setOption to configure further aspects of a TileStore instance."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStoreOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TilesetDescriptor":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"A bundle that encapsulates tilesets creation for the tile store implementation."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TilesetDescriptor","url":"\/documentation\/mapboxcommon\/tilesetdescriptor","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TilesetDescriptor"}],"navigatorTitle":[{"text":"TilesetDescriptor","kind":"identifier"}],"title":"TilesetDescriptor"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateResult":{"type":"topic","navigatorTitle":[{"text":"TileRegionEstimateResult","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TileRegionEstimateResult","kind":"identifier"}],"title":"TileRegionEstimateResult","role":"symbol","url":"\/documentation\/mapboxcommon\/tileregionestimateresult","abstract":[{"type":"text","text":"The result of tile region estim"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateResult"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateProgressCallback":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"TileRegionEstimateProgressCallback"}],"kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileRegionEstimateProgressCallback"}],"title":"TileRegionEstimateProgressCallback","role":"symbol","url":"\/documentation\/mapboxcommon\/tileregionestimateprogresscallback","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgressCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateOptions":{"type":"topic","role":"symbol","abstract":[{"text":"Holds options for the tile region estimation operation.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateOptions","url":"\/documentation\/mapboxcommon\/tileregionestimateoptions","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TileRegionEstimateOptions","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"TileRegionEstimateOptions"}],"title":"TileRegionEstimateOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateProgress":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"A tile region’s estimate progress includes counts of the number of resources that have"},{"type":"text","text":" "},{"text":"been estimated and the total number of resources as well as a partial result with the","type":"text"},{"type":"text","text":" "},{"text":"current estimate, calculated using the data available at the moment.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgress","url":"\/documentation\/mapboxcommon\/tileregionestimateprogress","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileRegionEstimateProgress","kind":"identifier"}],"navigatorTitle":[{"text":"TileRegionEstimateProgress","kind":"identifier"}],"title":"TileRegionEstimateProgress"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/CacheClearingError":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Describes a cache clearing error."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingError","url":"\/documentation\/mapboxcommon\/cacheclearingerror","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"CacheClearingError","kind":"identifier"}],"navigatorTitle":[{"text":"CacheClearingError","kind":"identifier"}],"title":"CacheClearingError"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateProgress/init(requiredResourceCount:erroredResourceCount:completedResourceCount:partialResult:)":{"title":"init(requiredResourceCount:erroredResourceCount:completedResourceCount:partialResult:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"requiredResourceCount"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s6UInt64V","text":"UInt64","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"erroredResourceCount","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UInt64","preciseIdentifier":"s:s6UInt64V","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completedResourceCount"},{"kind":"text","text":": "},{"text":"UInt64","preciseIdentifier":"s:s6UInt64V","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"partialResult","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TileRegionEstimateResult","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXTileRegionEstimateResult"},{"kind":"text","text":")"}],"role":"symbol","abstract":[],"navigatorTitle":[{"text":"initWithRequiredResourceCount:erroredResourceCount:completedResourceCount:partialResult:","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgress\/init(requiredResourceCount:erroredResourceCount:completedResourceCount:partialResult:)","url":"\/documentation\/mapboxcommon\/tileregionestimateprogress\/init(requiredresourcecount:erroredresourcecount:completedresourcecount:partialresult:)","type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadProgressCallback":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"TileRegionLoadProgressCallback"}],"kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileRegionLoadProgressCallback"}],"title":"TileRegionLoadProgressCallback","role":"symbol","url":"\/documentation\/mapboxcommon\/tileregionloadprogresscallback","abstract":[{"text":"Callback Invoked to report the progess of the tile region loading operation.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgressCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateProgress/isEqual(to:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"to"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TileRegionEstimateProgress","preciseIdentifier":"c:objc(cs)MBXTileRegionEstimateProgress"},{"kind":"text","text":") -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"isEqualToTileRegionEstimateProgress:","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgress\/isEqual(to:)","title":"isEqual(to:)","url":"\/documentation\/mapboxcommon\/tileregionestimateprogress\/isequal(to:)"},"doc://com.mapbox.MapboxMaps/SH":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","title":"Swift.Hashable"},"doc://com.mapbox.MapboxMaps/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","type":"topic","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"title":"MapboxMaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadOptions":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Describes the tile region load option values."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions","url":"\/documentation\/mapboxcommon\/tileregionloadoptions","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileRegionLoadOptions"}],"navigatorTitle":[{"text":"TileRegionLoadOptions","kind":"identifier"}],"title":"TileRegionLoadOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileDataDomain":{"abstract":[{"text":"Describes the tiles data domain.","type":"text"}],"type":"topic","url":"\/documentation\/mapboxcommon\/tiledatadomain","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileDataDomain","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileDataDomain","kind":"identifier"}],"navigatorTitle":[{"text":"TileDataDomain","kind":"identifier"}],"title":"TileDataDomain"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadProgress":{"url":"\/documentation\/mapboxcommon\/tileregionloadprogress","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TileRegionLoadProgress"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"TileRegionLoadProgress","kind":"identifier"}],"title":"TileRegionLoadProgress","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgress","abstract":[{"type":"text","text":"A tile region’s load progress includes counts"},{"type":"text","text":" "},{"text":"of the number of resources that have completed downloading","type":"text"},{"type":"text","text":" "},{"type":"text","text":"and the total number of resources that are required."}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CanonicalTileID":{"abstract":[{"text":"Represents a tile coordinate.","type":"text"}],"url":"\/documentation\/mapboxmaps\/canonicaltileid","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CanonicalTileID","kind":"identifier"}],"navigatorTitle":[{"text":"CanonicalTileID","kind":"identifier"}],"type":"topic","title":"CanonicalTileID","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID","kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject","title":"NSObject"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudgetInMegabytes":{"title":"TileCacheBudgetInMegabytes","kind":"symbol","abstract":[{"text":"Tile cache budget in megabytes.","type":"text"}],"type":"topic","url":"\/documentation\/mapboxmaps\/tilecachebudgetinmegabytes","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInMegabytes","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TileCacheBudgetInMegabytes"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TileCacheBudgetInMegabytes"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/CacheClearingErrorType":{"abstract":[{"text":"Describes the reason for a cache clearing failure.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingErrorType","kind":"symbol","type":"topic","navigatorTitle":[{"text":"CacheClearingErrorType","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/cacheclearingerrortype","title":"CacheClearingErrorType","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CacheClearingErrorType","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ClearCacheError":{"type":"topic","navigatorTitle":[{"text":"ClearCacheError","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClearCacheError"}],"title":"ClearCacheError","role":"symbol","url":"\/documentation\/mapboxmaps\/clearcacheerror","abstract":[{"type":"text","text":"Describes the reason for a cache clearing failure."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClearCacheError"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateProgress/partialResult":{"navigatorTitle":[{"kind":"identifier","text":"partialResult"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgress\/partialResult","url":"\/documentation\/mapboxcommon\/tileregionestimateprogress\/partialresult","title":"partialResult","abstract":[{"text":"Partial result with the current estimate, calculated using the data available at","type":"text"},{"type":"text","text":" "},{"text":"the moment.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"partialResult"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXTileRegionEstimateResult","text":"TileRegionEstimateResult"}],"type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileStore":{"url":"\/documentation\/mapboxcommon\/tilestore","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore","navigatorTitle":[{"kind":"identifier","text":"TileStore"}],"abstract":[{"text":"TileStore manages downloads and storage for requests to tile-related API endpoints, enforcing a disk usage","type":"text"},{"type":"text","text":" "},{"text":"quota: tiles available on disk may be deleted to make room for a new download. This interface can be used by an","type":"text"},{"text":" ","type":"text"},{"text":"app developer to set the disk quota. The rest of TileStore API is intended for native SDK consumption only.","type":"text"}],"type":"topic","role":"symbol","title":"TileStore","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileStore","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateProgress/requiredResourceCount":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiredResourceCount"},{"kind":"text","text":": "},{"text":"UInt64","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V"}],"abstract":[{"text":"The number of resources that are known to be required for this tile region.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"requiredResourceCount"}],"title":"requiredResourceCount","role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/mapboxcommon\/tileregionestimateprogress\/requiredresourcecount","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgress\/requiredResourceCount"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudgetInTiles":{"type":"topic","role":"symbol","abstract":[{"text":"Tile cache budget in tiles.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInTiles","url":"\/documentation\/mapboxmaps\/tilecachebudgetintiles","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileCacheBudgetInTiles"}],"navigatorTitle":[{"kind":"identifier","text":"TileCacheBudgetInTiles"}],"title":"TileCacheBudgetInTiles"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateProgress/erroredResourceCount":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"erroredResourceCount","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s6UInt64V","text":"UInt64","kind":"typeIdentifier"}],"abstract":[{"text":"The number of resources that have failed to be estimated due to an error.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"erroredResourceCount"}],"kind":"symbol","role":"symbol","title":"erroredResourceCount","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgress\/erroredResourceCount","url":"\/documentation\/mapboxcommon\/tileregionestimateprogress\/erroredresourcecount"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegion":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegion","abstract":[{"text":"TileRegion represents an identifiable geographic tile region with metadata","type":"text"}],"type":"topic","kind":"symbol","title":"TileRegion","url":"\/documentation\/mapboxcommon\/tileregion","navigatorTitle":[{"kind":"identifier","text":"TileRegion"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileRegion","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCoverOptions":{"title":"TileCoverOptions","tags":[{"type":"spi","text":"SPI"}],"url":"\/documentation\/mapboxmaps\/tilecoveroptions","type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCoverOptions","navigatorTitle":[{"text":"TileCoverOptions","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"TileCoverOptions","kind":"identifier"}],"abstract":[{"type":"text","text":"Various options needed for tile cover."}]},"doc://com.mapbox.MapboxMaps/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","title":"Swift.CVarArg"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"MBXTileRegionEstimateProgress"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","value":[{"kind":"identifier","text":"MBXTileRegionEstimateProgress"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"MBXTileRegionEstimateProgress","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgress\/completedResourceCount","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgress\/erroredResourceCount","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgress\/partialResult","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgress\/requiredResourceCount"],"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgress\/init(requiredResourceCount:erroredResourceCount:completedResourceCount:partialResult:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgress\/isEqual(to:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}]},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"type":"inheritsFrom"}],"op":"replace"},{"value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStoreOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudget","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInMegabytes","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInTiles","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegion","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgress","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TilesetDescriptor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TilesetDescriptorOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgressCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreUsageMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileDataDomain","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateResult","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgressCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingErrorType"],"anchor":"TileStore","title":"TileStore","generated":true}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBXTileRegionEstimateProgress"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions\/title","value":"MBMTilesetDescriptorOptions"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions\/fragments","value":[{"text":"MBMTilesetDescriptorOptions","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions\/navigatorTitle","value":[{"text":"MBMTilesetDescriptorOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetType\/title","op":"replace","value":"MBMTileCacheBudgetType"},{"op":"replace","value":[{"kind":"identifier","text":"MBMTileCacheBudgetType"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetType\/navigatorTitle","value":[{"text":"MBMTileCacheBudgetType","kind":"identifier"}]},{"value":"MBMTileOptions","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileOptions\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileOptions\/fragments","value":[{"text":"MBMTileOptions","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"MBMTileOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileOptions\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgress~1completedResourceCount\/title","value":"completedResourceCount"},{"value":[{"text":"completedResourceCount","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgress~1completedResourceCount\/fragments"},{"op":"replace","value":"MBMTileCacheBudget","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudget\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudget\/fragments","value":[{"kind":"identifier","text":"MBMTileCacheBudget"}],"op":"replace"},{"value":[{"text":"MBMTileCacheBudget","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudget\/navigatorTitle"},{"value":"MBMTileStoreUsageMode","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileStoreUsageMode\/title"},{"value":[{"kind":"identifier","text":"MBMTileStoreUsageMode"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileStoreUsageMode\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MBMTileStoreUsageMode"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileStoreUsageMode\/navigatorTitle","op":"replace"},{"value":"MBXTileStoreOptions","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStoreOptions\/title"},{"value":[{"kind":"identifier","text":"MBXTileStoreOptions"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStoreOptions\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStoreOptions\/navigatorTitle","value":[{"text":"MBXTileStoreOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TilesetDescriptor\/title","value":"MBXTilesetDescriptor","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TilesetDescriptor\/fragments","value":[{"text":"MBXTilesetDescriptor","kind":"identifier"}]},{"value":[{"text":"MBXTilesetDescriptor","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TilesetDescriptor\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateResult\/title","op":"replace","value":"MBXTileRegionEstimateResult"},{"value":[{"text":"MBXTileRegionEstimateResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateResult\/fragments"},{"value":[{"kind":"identifier","text":"MBXTileRegionEstimateResult"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateResult\/navigatorTitle","op":"replace"},{"op":"replace","value":"MBXTileRegionEstimateProgressCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgressCallback\/title"},{"value":[{"kind":"identifier","text":"MBXTileRegionEstimateProgressCallback"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgressCallback\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgressCallback\/navigatorTitle","value":[{"kind":"identifier","text":"MBXTileRegionEstimateProgressCallback"}],"op":"replace"},{"op":"replace","value":"MBXTileRegionEstimateOptions","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateOptions\/title"},{"value":[{"text":"MBXTileRegionEstimateOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateOptions\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateOptions\/navigatorTitle","value":[{"kind":"identifier","text":"MBXTileRegionEstimateOptions"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgress\/title","value":"MBXTileRegionEstimateProgress"},{"op":"replace","value":[{"kind":"identifier","text":"MBXTileRegionEstimateProgress"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgress\/fragments"},{"value":[{"kind":"identifier","text":"MBXTileRegionEstimateProgress"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgress\/navigatorTitle"},{"value":"MBXCacheClearingError","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingError\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBXCacheClearingError"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingError\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingError\/navigatorTitle","value":[{"text":"MBXCacheClearingError","kind":"identifier"}]},{"value":"initWithRequiredResourceCount:erroredResourceCount:completedResourceCount:partialResult:","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgress~1init(requiredResourceCount:erroredResourceCount:completedResourceCount:partialResult:)\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgress~1init(requiredResourceCount:erroredResourceCount:completedResourceCount:partialResult:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithRequiredResourceCount:erroredResourceCount:completedResourceCount:partialResult:","kind":"identifier"}],"op":"replace"},{"value":"MBXTileRegionLoadProgressCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgressCallback\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MBXTileRegionLoadProgressCallback"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgressCallback\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgressCallback\/navigatorTitle","value":[{"kind":"identifier","text":"MBXTileRegionLoadProgressCallback"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgress~1isEqual(to:)\/title","op":"replace","value":"isEqualToTileRegionEstimateProgress:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isEqualToTileRegionEstimateProgress:"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgress~1isEqual(to:)\/fragments"},{"value":"MBXTileRegionLoadOptions","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/fragments","value":[{"kind":"identifier","text":"MBXTileRegionLoadOptions"}]},{"value":[{"kind":"identifier","text":"MBXTileRegionLoadOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileDataDomain\/title","value":"MBXTileDataDomain","op":"replace"},{"value":[{"text":"MBXTileDataDomain","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileDataDomain\/fragments"},{"value":[{"kind":"identifier","text":"MBXTileDataDomain"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileDataDomain\/navigatorTitle"},{"op":"replace","value":"MBXTileRegionLoadProgress","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgress\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgress\/fragments","value":[{"text":"MBXTileRegionLoadProgress","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgress\/navigatorTitle","value":[{"text":"MBXTileRegionLoadProgress","kind":"identifier"}]},{"op":"replace","value":"MBMCanonicalTileID","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/title"},{"value":[{"kind":"identifier","text":"MBMCanonicalTileID"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/fragments","op":"replace"},{"op":"replace","value":[{"text":"MBMCanonicalTileID","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/navigatorTitle"},{"op":"replace","value":"MBMTileCacheBudgetInMegabytes","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInMegabytes\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInMegabytes\/fragments","value":[{"text":"MBMTileCacheBudgetInMegabytes","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInMegabytes\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMTileCacheBudgetInMegabytes"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingErrorType\/title","op":"replace","value":"MBXCacheClearingErrorType"},{"value":[{"text":"MBXCacheClearingErrorType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingErrorType\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingErrorType\/navigatorTitle","value":[{"kind":"identifier","text":"MBXCacheClearingErrorType"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgress~1partialResult\/title","value":"partialResult","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgress~1partialResult\/fragments","value":[{"text":"partialResult","kind":"identifier"}]},{"op":"replace","value":"MBXTileStore","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBXTileStore"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/fragments"},{"value":[{"kind":"identifier","text":"MBXTileStore"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgress~1requiredResourceCount\/title","value":"requiredResourceCount","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgress~1requiredResourceCount\/fragments","value":[{"text":"requiredResourceCount","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInTiles\/title","value":"MBMTileCacheBudgetInTiles","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBMTileCacheBudgetInTiles"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInTiles\/fragments"},{"value":[{"text":"MBMTileCacheBudgetInTiles","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInTiles\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgress~1erroredResourceCount\/title","value":"erroredResourceCount"},{"value":[{"kind":"identifier","text":"erroredResourceCount"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgress~1erroredResourceCount\/fragments","op":"replace"},{"value":"MBXTileRegion","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegion\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegion\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXTileRegion"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegion\/navigatorTitle","value":[{"text":"MBXTileRegion","kind":"identifier"}],"op":"replace"}]}]}