{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"timeInterval"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/EventTimeInterval","text":"EventTimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMEventTimeInterval"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"title":"init(timeInterval:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"timeInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMEventTimeInterval","text":"EventTimeInterval"},{"text":")","kind":"text"}],"modules":[{"name":"MapboxMaps"}],"symbolKind":"init","role":"symbol","navigatorTitle":[{"text":"initWithTimeInterval:","kind":"identifier"}],"roleHeading":"Initializer","externalID":"c:objc(cs)MBMStyleLoaded(im)initWithTimeInterval:"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/styleloaded\/init(timeinterval:)"]},{"paths":["\/documentation\/mapboxmaps\/styleloaded\/init(timeinterval:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleLoaded\/init(timeInterval:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleLoaded"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","url":"\/documentation\/overview","role":"collection","kind":"article","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleLoaded/init(timeInterval:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithTimeInterval:"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleLoaded\/init(timeInterval:)","title":"init(timeInterval:)","type":"topic","url":"\/documentation\/mapboxmaps\/styleloaded\/init(timeinterval:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"timeInterval","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMEventTimeInterval","text":"EventTimeInterval"},{"text":")","kind":"text"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/EventTimeInterval":{"navigatorTitle":[{"kind":"identifier","text":"EventTimeInterval"}],"url":"\/documentation\/mapboxmaps\/eventtimeinterval","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EventTimeInterval"}],"abstract":[{"type":"text","text":"The time interval of an event. The "},{"type":"codeVoice","code":"begin"},{"text":" property represents the time","type":"text"},{"text":" ","type":"text"},{"text":"origin of an event, and the ","type":"text"},{"code":"end","type":"codeVoice"},{"type":"text","text":" property represents the time when the particular"},{"text":" ","type":"text"},{"text":"operation is complete. The timestamps are sampled at the origin and do not include","type":"text"},{"type":"text","text":" "},{"type":"text","text":"the time required to dispatch an event."}],"kind":"symbol","title":"EventTimeInterval","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/EventTimeInterval"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"role":"collection","title":"MapboxMaps","type":"topic","url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"url":"\/documentation\/mapboxmaps\/events","role":"collectionGroup","title":"Map events","kind":"article","abstract":[{"type":"text","text":"The simplified diagram of the events emitted by the map is displayed below."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleLoaded":{"title":"StyleLoaded","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleLoaded","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StyleLoaded","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/styleloaded","navigatorTitle":[{"kind":"identifier","text":"StyleLoaded"}],"abstract":[{"type":"text","text":"The requested style has been fully loaded, including specified sprite, and sources’ metadata."}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"initWithTimeInterval:","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithTimeInterval:"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithTimeInterval:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)MBMEventTimeInterval","kind":"typeIdentifier","text":"MBMEventTimeInterval","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/EventTimeInterval"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"timeInterval"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","value":"initWithTimeInterval:","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoaded~1init(timeInterval:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithTimeInterval:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoaded~1init(timeInterval:)\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1EventTimeInterval\/title","op":"replace","value":"MBMEventTimeInterval"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1EventTimeInterval\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMEventTimeInterval"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1EventTimeInterval\/navigatorTitle","value":[{"text":"MBMEventTimeInterval","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoaded\/title","value":"MBMStyleLoaded"},{"value":[{"kind":"identifier","text":"MBMStyleLoaded"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoaded\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoaded\/navigatorTitle","value":[{"text":"MBMStyleLoaded","kind":"identifier"}],"op":"replace"}]}]}