{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TilesetDescriptorOptions"]]},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"abstract":[{"type":"text","text":"Style package load options, associated with the tileset descriptor."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stylePackOptions","kind":"identifier"},{"text":": ","kind":"text"},{"text":"StylePackLoadOptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadOptions","preciseIdentifier":"c:objc(cs)MBMStylePackLoadOptions","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"anchor":"discussion","text":"Discussion","type":"heading"},{"inlineContent":[{"text":"If provided, ","type":"text"},{"code":"offline manager","type":"codeVoice"},{"text":" will create a style package while resolving the corresponding","type":"text"},{"text":" ","type":"text"},{"text":"tileset descriptor and load all the resources as defined in the provided style package options,","type":"text"},{"text":" ","type":"text"},{"text":"i.e. resolving of corresponding the tileset descriptor will be equivalent to calling the ","type":"text"},{"code":"loadStylePack","type":"codeVoice"},{"text":" ","type":"text"},{"text":"method of ","type":"text"},{"code":"offline manager","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"If not provided, resolving of the corresponding tileset descriptor will not cause creating of a new style","type":"text"},{"text":" ","type":"text"},{"text":"package but the loaded resources will be stored in the disk cache.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Style package creation requires nonempty "},{"type":"codeVoice","code":"styleURL"},{"type":"text","text":", which will be the created style package identifier."}],"type":"paragraph"}]}],"variants":[{"paths":["\/documentation\/mapboxmaps\/tilesetdescriptoroptions\/stylepackoptions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/tilesetdescriptoroptions\/stylepackoptions"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TilesetDescriptorOptions\/stylePackOptions"},"metadata":{"navigatorTitle":[{"text":"stylePackOptions","kind":"identifier"}],"title":"stylePackOptions","role":"symbol","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"MapboxMaps"}],"externalID":"c:objc(cs)MBMTilesetDescriptorOptions(py)stylePackOptions","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stylePackOptions","kind":"identifier"},{"text":": ","kind":"text"},{"text":"StylePackLoadOptions","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMStylePackLoadOptions"},{"text":"?","kind":"text"}]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePackLoadOptions":{"type":"topic","abstract":[{"text":"Describes the style package load option values.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadOptions","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StylePackLoadOptions","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/stylepackloadoptions","title":"StylePackLoadOptions","navigatorTitle":[{"text":"StylePackLoadOptions","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","kind":"symbol","title":"MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TilesetDescriptorOptions/stylePackOptions":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stylePackOptions","kind":"identifier"},{"text":": ","kind":"text"},{"text":"StylePackLoadOptions","preciseIdentifier":"c:objc(cs)MBMStylePackLoadOptions","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"stylePackOptions","kind":"identifier"}],"title":"stylePackOptions","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TilesetDescriptorOptions\/stylePackOptions","url":"\/documentation\/mapboxmaps\/tilesetdescriptoroptions\/stylepackoptions","abstract":[{"type":"text","text":"Style package load options, associated with the tileset descriptor."}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"title":"TileStore APIs","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","url":"\/documentation\/mapboxmaps\/tilestore-apis","abstract":[],"role":"collectionGroup","type":"topic","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"kind":"article","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","url":"\/documentation\/overview","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TilesetDescriptorOptions":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TilesetDescriptorOptions"}],"navigatorTitle":[{"kind":"identifier","text":"TilesetDescriptorOptions"}],"url":"\/documentation\/mapboxmaps\/tilesetdescriptoroptions","abstract":[{"type":"text","text":"Describes the tileset descriptor option values."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TilesetDescriptorOptions","title":"TilesetDescriptorOptions","type":"topic","kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"stylePackOptions","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"stylePackOptions"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMStylePackLoadOptions","text":"MBMStylePackLoadOptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadOptions"},{"kind":"text","text":" * "},{"kind":"identifier","text":"stylePackOptions"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MBMStylePackLoadOptions","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadOptions\/title"},{"value":[{"text":"MBMStylePackLoadOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadOptions\/fragments"},{"value":[{"kind":"identifier","text":"MBMStylePackLoadOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadOptions\/navigatorTitle"},{"value":"stylePackOptions","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions~1stylePackOptions\/title"},{"value":[{"kind":"identifier","text":"stylePackOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions~1stylePackOptions\/fragments"},{"value":"MBMTilesetDescriptorOptions","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions\/title"},{"value":[{"kind":"identifier","text":"MBMTilesetDescriptorOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions\/fragments"},{"value":[{"kind":"identifier","text":"MBMTilesetDescriptorOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}