{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps"]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"topicSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Migrate-to-v11","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SwiftUI-User-Guide","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Declarative-Map-Styling","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-Content-Gestures-User-Guide","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Work-with-visionOS"],"anchor":"Articles","title":"Articles"},{"title":"Essentials","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-View","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SwiftUI","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Featuresets-and-Interactions"],"anchor":"Essentials"},{"title":"Styling","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Style","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer-Property-Values","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Expressions"],"anchor":"Styling"},{"anchor":"Annotations","title":"Annotations","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer-Annotations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/View-Annotations"]},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs"],"anchor":"Advanced","title":"Advanced"},{"title":"Other","anchor":"Other","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Camera-and-coordinates","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Ornaments","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Gestures","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Settings-and-Constants"]},{"title":"Dependencies","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TurfAPI"],"anchor":"Dependencies"},{"anchor":"Internal","title":"Internal","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMapsInternal"]}],"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/Turf"]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","interfaceLanguage":"swift"},"sections":[],"abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"]]},"metadata":{"modules":[{"name":"MapboxMaps"}],"title":"MapboxMaps","symbolKind":"module","externalID":"MapboxMaps","roleHeading":"Framework","role":"collection"},"primaryContentSections":[{"kind":"content","content":[{"text":"Overview","type":"heading","level":2,"anchor":"Overview"},{"inlineContent":[{"type":"text","text":"The Mapbox Maps SDK for iOS is a public library for displaying interactive, thoroughly customizable maps in native iOS. It takes map styles that conform to the "},{"isActive":true,"identifier":"https:\/\/docs.mapbox.com\/mapbox-gl-js\/style-spec\/","type":"reference"},{"text":", applies them to vector tiles that conform to the ","type":"text"},{"isActive":true,"identifier":"https:\/\/github.com\/mapbox\/vector-tile-spec","type":"reference"},{"type":"text","text":", and renders them using Metal."}],"type":"paragraph"}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layer-Property-Values":{"kind":"article","type":"topic","url":"\/documentation\/mapboxmaps\/layer-property-values","title":"Layer Property Values","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer-Property-Values"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","title":"MapboxMaps","kind":"symbol","url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Location-APIs":{"type":"topic","kind":"article","abstract":[],"url":"\/documentation\/mapboxmaps\/location-apis","role":"collectionGroup","title":"Location","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"kind":"article","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/tilestore-apis","type":"topic","title":"TileStore APIs"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map-View":{"title":"MapView","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-View","abstract":[],"url":"\/documentation\/mapboxmaps\/map-view","kind":"article","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Camera-and-coordinates":{"abstract":[],"kind":"article","role":"collectionGroup","title":"Camera and coordinates","type":"topic","url":"\/documentation\/mapboxmaps\/camera-and-coordinates","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Camera-and-coordinates"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Featuresets-and-Interactions":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Featuresets-and-Interactions","kind":"article","role":"collectionGroup","type":"topic","abstract":[{"text":"The experimental Interactions API.","type":"text"}],"url":"\/documentation\/mapboxmaps\/featuresets-and-interactions","title":"Featuresets and Interactions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Work-with-visionOS":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Work-with-visionOS","role":"article","url":"\/documentation\/mapboxmaps\/work-with-visionos","abstract":[{"text":"Use Mapbox Maps in native applications for Apple Vision Pro.","type":"text"}],"kind":"article","title":"Work with visionOS"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Gestures":{"kind":"article","type":"topic","abstract":[],"url":"\/documentation\/mapboxmaps\/gestures","title":"Gestures","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Gestures"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"role":"collectionGroup","kind":"article","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","type":"topic","title":"MapboxMap","url":"\/documentation\/mapboxmaps\/mapboxmap-apis"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","title":"MapboxMaps Documentation","kind":"article","url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Migrate-to-v11":{"kind":"article","role":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Migrate-to-v11","url":"\/documentation\/mapboxmaps\/migrate-to-v11","type":"topic","title":"Migrate to v11 from v10","abstract":[{"type":"text","text":"The Mapbox Maps SDK v11 introduces improvements to how Mapbox works on iOS platforms, as well as changes to how developers use the SDK. This document summarizes the most important changes - such as new features, deprecated APIs, and breaking changes - and walks you through how to upgrade an application using v10 of the Mapbox Maps SDK to v11."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layer-Annotations":{"abstract":[],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer-Annotations","kind":"article","role":"collectionGroup","title":"Layer Annotations","url":"\/documentation\/mapboxmaps\/layer-annotations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"title":"Map events","role":"collectionGroup","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","url":"\/documentation\/mapboxmaps\/events","abstract":[{"type":"text","text":"The simplified diagram of the events emitted by the map is displayed below."}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMaps":{"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","role":"collectionGroup","type":"topic","abstract":[{"type":"text","text":"Maps rendering SDK also known as GL-Native"}],"url":"\/documentation\/mapboxmaps\/coremaps","title":"Core Maps API"},"doc://com.mapbox.MapboxMaps/documentation/Turf":{"role":"collection","type":"topic","url":"\/documentation\/turf","title":"Turf","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Turf","kind":"symbol","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Ornaments":{"role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Ornaments","title":"Ornaments","kind":"article","type":"topic","url":"\/documentation\/mapboxmaps\/ornaments","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"role":"collection","title":"MapboxCommon","kind":"symbol","url":"\/documentation\/mapboxcommon","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","type":"topic","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Snapshotter-APIs":{"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter-APIs","title":"Snapshotter","kind":"article","type":"topic","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/snapshotter-apis"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layers":{"type":"topic","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers","url":"\/documentation\/mapboxmaps\/layers","abstract":[],"title":"Layers","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Performance":{"role":"collectionGroup","kind":"article","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","title":"Performance and investigations","type":"topic","url":"\/documentation\/mapboxmaps\/performance"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SwiftUI":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SwiftUI","kind":"article","role":"collectionGroup","type":"topic","url":"\/documentation\/mapboxmaps\/swiftui","abstract":[],"title":"SwiftUI"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Settings-and-Constants":{"url":"\/documentation\/mapboxmaps\/settings-and-constants","type":"topic","abstract":[],"kind":"article","title":"Settings and Constants","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Settings-and-Constants","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Style":{"type":"topic","title":"Style","url":"\/documentation\/mapboxmaps\/style","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Style","abstract":[],"role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMapsInternal":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMapsInternal","url":"\/documentation\/mapboxmaps\/coremapsinternal","role":"collectionGroup","title":"CoreMaps - Internal","kind":"article","type":"topic","abstract":[{"type":"text","text":"Maps rendering SDK also known as GL-Native. These are for internal use only."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SwiftUI-User-Guide":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SwiftUI-User-Guide","kind":"article","type":"topic","abstract":[{"text":"Use Mapbox Maps in SwiftUI applications.","type":"text"}],"role":"article","url":"\/documentation\/mapboxmaps\/swiftui-user-guide","title":"SwiftUI User Guide"},"https://docs.mapbox.com/mapbox-gl-js/style-spec/":{"type":"link","identifier":"https:\/\/docs.mapbox.com\/mapbox-gl-js\/style-spec\/","title":"Mapbox Style Specification","titleInlineContent":[{"text":"Mapbox Style Specification","type":"text"}],"url":"https:\/\/docs.mapbox.com\/mapbox-gl-js\/style-spec\/"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Declarative-Map-Styling":{"abstract":[{"text":"Simplify runtime style manipulation with declarative syntax.","type":"text"}],"title":"Declarative Map Styling","url":"\/documentation\/mapboxmaps\/declarative-map-styling","kind":"article","role":"article","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Declarative-Map-Styling"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/View-Annotations":{"title":"View Annotations","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/View-Annotations","role":"collectionGroup","kind":"article","url":"\/documentation\/mapboxmaps\/view-annotations","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Expressions":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Expressions","role":"collectionGroup","abstract":[],"type":"topic","title":"Expressions","url":"\/documentation\/mapboxmaps\/expressions","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Sources":{"abstract":[],"kind":"article","title":"Sources","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources","type":"topic","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/sources"},"https://github.com/mapbox/vector-tile-spec":{"type":"link","identifier":"https:\/\/github.com\/mapbox\/vector-tile-spec","title":"Mapbox Vector Tile Specification","titleInlineContent":[{"type":"text","text":"Mapbox Vector Tile Specification"}],"url":"https:\/\/github.com\/mapbox\/vector-tile-spec"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TurfAPI":{"role":"collectionGroup","type":"topic","url":"\/documentation\/mapboxmaps\/turfapi","title":"Turf","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TurfAPI","kind":"article","abstract":[{"text":"Describes ","type":"text"},{"type":"codeVoice","code":"turf-swift"},{"type":"text","text":" dependency objects"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map-Content-Gestures-User-Guide":{"kind":"article","role":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-Content-Gestures-User-Guide","url":"\/documentation\/mapboxmaps\/map-content-gestures-user-guide","type":"topic","title":"Map Content Gestures User Guide","abstract":[{"text":"Handle Tap and Long Press gestures on Map, Annotations, and Layers.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Articles","title":"Articles","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Migrate-to-v11","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SwiftUI-User-Guide","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Declarative-Map-Styling","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-Content-Gestures-User-Guide","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Work-with-visionOS"]},{"anchor":"Essentials","title":"Essentials","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-View","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SwiftUI","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Featuresets-and-Interactions"]},{"anchor":"Styling","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Style","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer-Property-Values","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Expressions"],"title":"Styling"},{"title":"Annotations","anchor":"Annotations","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer-Annotations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/View-Annotations"]},{"anchor":"Advanced","title":"Advanced","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs"]},{"title":"Other","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Camera-and-coordinates","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Ornaments","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Gestures","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Settings-and-Constants"],"anchor":"Other"},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TurfAPI"],"anchor":"Dependencies","title":"Dependencies"},{"anchor":"Internal","title":"Internal","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMapsInternal"]}]},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon"],"generated":true}],"path":"\/seeAlsoSections","op":"replace"}]}]}