{"variants":[{"paths":["\/documentation\/mapboxcommon\/locationerrorcode\/failedtodetectlocation"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/locationerrorcode\/failedtodetectlocation"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"failedToDetectLocation","kind":"identifier"}]}],"kind":"declarations"}],"metadata":{"role":"symbol","modules":[{"name":"MapboxCommon"}],"symbolKind":"case","externalID":"c:@E@MBXLocationErrorCode@MBXLocationErrorCodeFailedToDetectLocation","title":"LocationErrorCode.failedToDetectLocation","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failedToDetectLocation","kind":"identifier"}],"navigatorTitle":[{"text":"MBXLocationErrorCodeFailedToDetectLocation","kind":"identifier"}],"roleHeading":"Case"},"abstract":[{"text":"Failed to detect location.","type":"text"}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode\/failedToDetectLocation","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode"]]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Location-APIs":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","url":"\/documentation\/mapboxmaps\/location-apis","type":"topic","kind":"article","role":"collectionGroup","abstract":[],"title":"Location"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationErrorCode/failedToDetectLocation":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode\/failedToDetectLocation","role":"symbol","kind":"symbol","title":"LocationErrorCode.failedToDetectLocation","url":"\/documentation\/mapboxcommon\/locationerrorcode\/failedtodetectlocation","abstract":[{"text":"Failed to detect location.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"failedToDetectLocation","kind":"identifier"}],"navigatorTitle":[{"text":"MBXLocationErrorCodeFailedToDetectLocation","kind":"identifier"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","abstract":[],"kind":"article","role":"collection","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationErrorCode":{"title":"LocationErrorCode","kind":"symbol","url":"\/documentation\/mapboxcommon\/locationerrorcode","navigatorTitle":[{"text":"LocationErrorCode","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"LocationErrorCode","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Codes of location errors."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"MBXLocationErrorCodeFailedToDetectLocation"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","value":[{"text":"MBXLocationErrorCodeFailedToDetectLocation","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"MBXLocationErrorCodeFailedToDetectLocation","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode~1failedToDetectLocation\/title","value":"MBXLocationErrorCodeFailedToDetectLocation","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode~1failedToDetectLocation\/fragments","op":"replace","value":[{"text":"MBXLocationErrorCodeFailedToDetectLocation","kind":"identifier"}]},{"op":"replace","value":"MBXLocationErrorCode","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/title"},{"value":[{"kind":"identifier","text":"MBXLocationErrorCode"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MBXLocationErrorCode"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}