{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"code"},{"text":": ","kind":"text"},{"text":"LocationErrorCode","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode","preciseIdentifier":"c:@E@MBXLocationErrorCode"},{"text":", ","kind":"text"},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/locationerror\/init(code:message:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/locationerror\/init(code:message:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationError\/init(code:message:)"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationError"]]},"metadata":{"roleHeading":"Initializer","externalID":"c:objc(cs)MBXLocationError(im)initWithCode:message:","role":"symbol","navigatorTitle":[{"text":"initWithCode:message:","kind":"identifier"}],"modules":[{"name":"MapboxCommon"}],"symbolKind":"init","title":"init(code:message:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"code"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@MBXLocationErrorCode","kind":"typeIdentifier","text":"LocationErrorCode"},{"text":", ","kind":"text"},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Location-APIs":{"url":"\/documentation\/mapboxmaps\/location-apis","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","type":"topic","abstract":[],"title":"Location","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationError/init(code:message:)":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"code","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBXLocationErrorCode","text":"LocationErrorCode"},{"text":", ","kind":"text"},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"title":"init(code:message:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithCode:message:"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationError\/init(code:message:)","url":"\/documentation\/mapboxcommon\/locationerror\/init(code:message:)","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","url":"\/documentation\/overview","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"role":"collection","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationErrorCode":{"type":"topic","title":"LocationErrorCode","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode","url":"\/documentation\/mapboxcommon\/locationerrorcode","abstract":[{"type":"text","text":"Codes of location errors."}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"LocationErrorCode","kind":"identifier"}],"navigatorTitle":[{"text":"LocationErrorCode","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationError":{"type":"topic","url":"\/documentation\/mapboxcommon\/locationerror","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationError","title":"LocationError","abstract":[{"type":"text","text":"Error code with brief explanation."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationError","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"LocationError"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithCode:message:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCode:message:"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithCode:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@MBXLocationErrorCode","text":"MBXLocationErrorCode","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"code","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"message:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"message","kind":"internalParam"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"initWithCode:message:","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationError~1init(code:message:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationError~1init(code:message:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithCode:message:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/title","value":"MBXLocationErrorCode","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/fragments","op":"replace","value":[{"text":"MBXLocationErrorCode","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MBXLocationErrorCode"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/navigatorTitle"},{"value":"MBXLocationError","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationError\/title","op":"replace"},{"value":[{"text":"MBXLocationError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationError\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationError\/navigatorTitle","value":[{"text":"MBXLocationError","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}