{"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStyleImageRemoveUnused\/imageId","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"imageId","modules":[{"name":"MapboxMaps"}],"navigatorTitle":[{"kind":"identifier","text":"imageId"}],"roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"imageId","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol","externalID":"c:objc(cs)MBMStyleImageRemoveUnused(py)imageId"},"variants":[{"paths":["\/documentation\/mapboxmaps\/mbmstyleimageremoveunused\/imageid"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/mbmstyleimageremoveunused\/imageid"]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnused"]]},"abstract":[{"type":"text","text":"The identifier of an image that is not used by the "},{"code":"map","type":"codeVoice"},{"text":".","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleImageRemoveUnused":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnused","title":"StyleImageRemoveUnused","kind":"symbol","navigatorTitle":[{"text":"StyleImageRemoveUnused","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/styleimageremoveunused","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StyleImageRemoveUnused","kind":"identifier"}],"abstract":[{"type":"text","text":"An image requested by the "},{"type":"codeVoice","code":"map"},{"text":" through the ","type":"text"},{"type":"codeVoice","code":"StyleImageMissing"},{"type":"text","text":" event is no longer"},{"type":"text","text":" "},{"type":"text","text":"needed and can be removed using the "},{"code":"removeStyleImage","type":"codeVoice"},{"text":" method. The application can","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"decide whether the image should be kept or removed."}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMStyleImageRemoveUnused/imageId":{"url":"\/documentation\/mapboxmaps\/mbmstyleimageremoveunused\/imageid","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStyleImageRemoveUnused\/imageId","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageId","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The identifier of an image that is not used by the "},{"type":"codeVoice","code":"map"},{"type":"text","text":"."}],"navigatorTitle":[{"text":"imageId","kind":"identifier"}],"title":"imageId","role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","title":"Map events","role":"collectionGroup","type":"topic","abstract":[{"type":"text","text":"The simplified diagram of the events emitted by the map is displayed below."}],"url":"\/documentation\/mapboxmaps\/events","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"imageId","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"imageId"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"imageId"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnused\/title","value":"MBMStyleImageRemoveUnused","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnused\/fragments","value":[{"kind":"identifier","text":"MBMStyleImageRemoveUnused"}]},{"value":"imageId","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMStyleImageRemoveUnused~1imageId\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMStyleImageRemoveUnused~1imageId\/fragments","value":[{"text":"imageId","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}