{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"maxZoom","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionTilePyramidDefinition\/maxZoom"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/offlineregiontilepyramiddefinition\/maxzoom"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/offlineregiontilepyramiddefinition\/maxzoom"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionTilePyramidDefinition"]]},"abstract":[{"type":"text","text":"Maximum zoom level for the offline region."}],"metadata":{"symbolKind":"property","title":"maxZoom","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"maxZoom","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"role":"symbol","externalID":"c:objc(cs)MBMOfflineRegionTilePyramidDefinition(py)maxZoom","platforms":[],"roleHeading":"Instance Property","modules":[{"name":"MapboxMaps"}],"navigatorTitle":[{"text":"maxZoom","kind":"identifier"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"type":"topic","role":"collection","kind":"article","title":"MapboxMaps Documentation","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","type":"topic","url":"\/documentation\/mapboxmaps\/coremaps","kind":"article","role":"collectionGroup","abstract":[{"text":"Maps rendering SDK also known as GL-Native","type":"text"}],"title":"Core Maps API"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Offline":{"title":"Offline Support","url":"\/documentation\/mapboxmaps\/offline","abstract":[],"kind":"article","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionTilePyramidDefinition/maxZoom":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionTilePyramidDefinition\/maxZoom","title":"maxZoom","url":"\/documentation\/mapboxmaps\/offlineregiontilepyramiddefinition\/maxzoom","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Maximum zoom level for the offline region."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxZoom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"kind":"symbol","deprecated":true,"navigatorTitle":[{"text":"maxZoom","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"type":"topic","role":"collection","kind":"symbol","title":"MapboxMaps","url":"\/documentation\/mapboxmaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionTilePyramidDefinition":{"kind":"symbol","abstract":[{"type":"text","text":"An offline region definition is a geographic region defined by a style URL,"},{"text":" ","type":"text"},{"text":"geographic bounding box, zoom range, and device pixel ratio. Both ","type":"text"},{"code":"minZoom","type":"codeVoice"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"maxZoom"},{"text":" must be ≥ 0,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"and "},{"type":"codeVoice","code":"maxZoom"},{"text":" must be ≥ ","type":"text"},{"type":"codeVoice","code":"minZoom"},{"text":". The ","type":"text"},{"type":"codeVoice","code":"maxZoom"},{"text":" may be ∞, in which case for each tile source,","type":"text"},{"type":"text","text":" "},{"text":"the region will include tiles from ","type":"text"},{"code":"minZoom","type":"codeVoice"},{"type":"text","text":" up to the maximum zoom level provided by that source."},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"type":"codeVoice","code":"pixelRatio"},{"type":"text","text":" must be ≥ 0 and should typically be 1.0 or 2.0."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"OfflineRegionTilePyramidDefinition","kind":"identifier"}],"title":"OfflineRegionTilePyramidDefinition","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionTilePyramidDefinition","navigatorTitle":[{"text":"OfflineRegionTilePyramidDefinition","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/offlineregiontilepyramiddefinition","type":"topic","deprecated":true}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"maxZoom","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"maxZoom","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"text":" ","kind":"text"},{"text":"maxZoom","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"maxZoom","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionTilePyramidDefinition~1maxZoom\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionTilePyramidDefinition~1maxZoom\/fragments","value":[{"kind":"identifier","text":"maxZoom"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionTilePyramidDefinition\/title","value":"MBMOfflineRegionTilePyramidDefinition","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionTilePyramidDefinition\/fragments","value":[{"kind":"identifier","text":"MBMOfflineRegionTilePyramidDefinition"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionTilePyramidDefinition\/navigatorTitle","value":[{"kind":"identifier","text":"MBMOfflineRegionTilePyramidDefinition"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}