{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onMapLoadingError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"action","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"keyword"},{"kind":"text","text":" ("},{"preciseIdentifier":"c:objc(cs)MBMMapLoadingError","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingError","text":"MapLoadingError","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":") -> ","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map","kind":"typeIdentifier","text":"Map","preciseIdentifier":"s:10MapboxMaps3MapV"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onMapLoadingError(action:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SwiftUI","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"abstract":[{"type":"text","text":"Adds an action to perform when there is an error occurred while loading the map."}],"metadata":{"modules":[{"name":"MapboxMaps"}],"title":"onMapLoadingError(action:)","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMapLoadingError"},{"text":"(","kind":"text"},{"text":"action","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"MapLoadingError","preciseIdentifier":"c:objc(cs)MBMMapLoadingError","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Map","preciseIdentifier":"s:10MapboxMaps3MapV","kind":"typeIdentifier"}],"role":"symbol","extendedModule":"MapboxMaps","platforms":[{"name":"iOS","beta":false,"unavailable":false,"deprecated":false,"introducedAt":"13.0"},{"name":"iPadOS","unavailable":false,"introducedAt":"13.0","beta":false,"deprecated":false},{"deprecated":false,"unavailable":false,"introducedAt":"13.0","beta":false,"name":"Mac Catalyst"}],"externalID":"s:10MapboxMaps3MapV02onC12LoadingError6actionACySo06MBMMapeF0Cc_tF","roleHeading":"Instance Method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/map\/onmaploadingerror(action:)"]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/onMapLoadingError(action:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onMapLoadingError","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"text":": (","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMMapLoadingError","kind":"typeIdentifier","text":"MapLoadingError"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Map","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps3MapV"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onMapLoadingError(action:)","kind":"symbol","title":"onMapLoadingError(action:)","abstract":[{"text":"Adds an action to perform when there is an error occurred while loading the map.","type":"text"}],"url":"\/documentation\/mapboxmaps\/map\/onmaploadingerror(action:)","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map":{"url":"\/documentation\/mapboxmaps\/map","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map","navigatorTitle":[{"text":"Map","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"Map","kind":"identifier"}],"title":"Map","abstract":[{"type":"text","text":"A SwiftUI view that displays a Mapbox Map."}],"kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoadingError":{"url":"\/documentation\/mapboxmaps\/maploadingerror","abstract":[{"text":"Describes an error that has occurred while loading the ","type":"text"},{"type":"codeVoice","code":"map"},{"text":". The ","type":"text"},{"code":"type","type":"codeVoice"},{"type":"text","text":" property"},{"type":"text","text":" "},{"text":"defines what resource could not be loaded, and the ","type":"text"},{"type":"codeVoice","code":"message"},{"type":"text","text":" property will contain"},{"type":"text","text":" "},{"text":"a descriptive error message.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MapLoadingError","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MapLoadingError"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingError","title":"MapLoadingError","kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SwiftUI":{"role":"collectionGroup","kind":"article","title":"SwiftUI","type":"topic","url":"\/documentation\/mapboxmaps\/swiftui","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SwiftUI","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","url":"\/documentation\/overview","title":"MapboxMaps Documentation","abstract":[],"kind":"article","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","title":"MapboxMaps","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingError\/title","value":"MBMMapLoadingError"},{"value":[{"kind":"identifier","text":"MBMMapLoadingError"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingError\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingError\/navigatorTitle","value":[{"text":"MBMMapLoadingError","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}