{"metadata":{"navigatorTitle":[{"text":"id","kind":"identifier"}],"title":"id","roleHeading":"Instance Property","externalID":"c:objc(cs)MBMStyleObjectInfo(py)id","role":"symbol","symbolKind":"property","modules":[{"name":"MapboxMaps"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleObjectInfo"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleObjectInfo\/id"},"abstract":[{"text":"The object’s identifier.","type":"text"}],"kind":"symbol","variants":[{"paths":["\/documentation\/mapboxmaps\/styleobjectinfo\/id"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/styleobjectinfo\/id"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleObjectInfo/id":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"id","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxmaps\/styleobjectinfo\/id","title":"id","abstract":[{"type":"text","text":"The object’s identifier."}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleObjectInfo\/id"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"kind":"article","role":"collection","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleObjectInfo":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/styleobjectinfo","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleObjectInfo","role":"symbol","abstract":[{"type":"text","text":"The information about style object (source or layer or light)."}],"type":"topic","title":"StyleObjectInfo","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StyleObjectInfo","kind":"identifier"}],"navigatorTitle":[{"text":"StyleObjectInfo","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"abstract":[],"kind":"article","type":"topic","role":"collectionGroup","title":"TileStore APIs","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","url":"\/documentation\/mapboxmaps\/tilestore-apis"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"id","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"id"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"id","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"id","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleObjectInfo~1id\/title"},{"op":"replace","value":[{"kind":"identifier","text":"id"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleObjectInfo~1id\/fragments"},{"op":"replace","value":"MBMStyleObjectInfo","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleObjectInfo\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBMStyleObjectInfo"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleObjectInfo\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MBMStyleObjectInfo"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleObjectInfo\/navigatorTitle"}]}]}