{"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"render","kind":"identifier"},{"kind":"text","text":"("},{"text":"toTile","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CanonicalTileID","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMCanonicalTileID"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mtlRenderCommandEncoder"},{"text":": any ","kind":"text"},{"text":"MTLRenderCommandEncoder","preciseIdentifier":"c:objc(pl)MTLRenderCommandEncoder","kind":"typeIdentifier"},{"text":")","kind":"text"}],"required":true,"role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"renderToTile:mtlRenderCommandEncoder:"}],"symbolKind":"method","modules":[{"name":"MapboxMaps"}],"title":"render(toTile:mtlRenderCommandEncoder:)","externalID":"c:objc(pl)MBMCustomLayerHost(im)renderToTile:mtlRenderCommandEncoder:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"render"},{"kind":"text","text":"("},{"text":"toTile","kind":"externalParam"},{"kind":"text","text":" "},{"text":"tileID","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID","preciseIdentifier":"c:objc(cs)MBMCanonicalTileID","kind":"typeIdentifier","text":"CanonicalTileID"},{"kind":"text","text":", "},{"text":"mtlRenderCommandEncoder","kind":"externalParam"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","text":"MTLRenderCommandEncoder","preciseIdentifier":"c:objc(pl)MTLRenderCommandEncoder"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerHost"]]},"abstract":[{"type":"text","text":"Note! This selector is an experimental feature. It can be changed or removed in future versions."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/customlayerhost\/render(totile:mtlrendercommandencoder:)"]},{"paths":["\/documentation\/mapboxmaps\/customlayerhost\/render(totile:mtlrendercommandencoder:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerHost\/render(toTile:mtlRenderCommandEncoder:)"},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","role":"collection","url":"\/documentation\/mapboxmaps","kind":"symbol","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layers":{"role":"collectionGroup","url":"\/documentation\/mapboxmaps\/layers","abstract":[],"title":"Layers","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers","type":"topic","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerHost":{"navigatorTitle":[{"text":"CustomLayerHost","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CustomLayerHost"}],"url":"\/documentation\/mapboxmaps\/customlayerhost","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerHost","title":"CustomLayerHost","role":"symbol","abstract":[{"text":"Interface for hosting a custom map style layer.","type":"text"}],"type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","title":"MapboxMaps Documentation","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CanonicalTileID":{"navigatorTitle":[{"text":"CanonicalTileID","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Represents a tile coordinate."}],"url":"\/documentation\/mapboxmaps\/canonicaltileid","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CanonicalTileID"}],"title":"CanonicalTileID"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerHost/render(toTile:mtlRenderCommandEncoder:)":{"navigatorTitle":[{"text":"renderToTile:mtlRenderCommandEncoder:","kind":"identifier"}],"title":"render(toTile:mtlRenderCommandEncoder:)","kind":"symbol","url":"\/documentation\/mapboxmaps\/customlayerhost\/render(totile:mtlrendercommandencoder:)","required":true,"abstract":[{"text":"Note! This selector is an experimental feature. It can be changed or removed in future versions.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerHost\/render(toTile:mtlRenderCommandEncoder:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"render"},{"kind":"text","text":"("},{"text":"toTile","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CanonicalTileID","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMCanonicalTileID"},{"kind":"text","text":", "},{"text":"mtlRenderCommandEncoder","kind":"externalParam"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MTLRenderCommandEncoder","text":"MTLRenderCommandEncoder"},{"kind":"text","text":")"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"renderToTile:mtlRenderCommandEncoder:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"renderToTile:mtlRenderCommandEncoder:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"renderToTile:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMCanonicalTileID","text":"MBMCanonicalTileID","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"tileID"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mtlRenderCommandEncoder:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qoobjc(pl)MTLRenderCommandEncoder","kind":"typeIdentifier","text":"id<MTLRenderCommandEncoder>"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"mtlRenderCommandEncoder"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"MBMCustomLayerHost","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost\/fragments","value":[{"kind":"identifier","text":"MBMCustomLayerHost"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost\/navigatorTitle","value":[{"text":"MBMCustomLayerHost","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/title","value":"MBMCanonicalTileID"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/fragments","value":[{"text":"MBMCanonicalTileID","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"MBMCanonicalTileID"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/navigatorTitle"},{"value":"renderToTile:mtlRenderCommandEncoder:","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost~1render(toTile:mtlRenderCommandEncoder:)\/title","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"renderToTile:mtlRenderCommandEncoder:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost~1render(toTile:mtlRenderCommandEncoder:)\/fragments"}]}]}