{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerHost"]]},"variants":[{"paths":["\/documentation\/mapboxmaps\/customlayerhost\/renderopengl(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/customlayerhost\/renderopengl(_:)"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"renderOpenGL","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"parameters","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters","text":"CustomLayerRenderParameters","preciseIdentifier":"c:objc(cs)MBMCustomLayerRenderParameters"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"As Apple is deprecating legacy OpenGL API, this method is optional and is called only if"},{"text":" ","type":"text"},{"text":"underlying map rendering backend uses OpenGL graphic API.","type":"text"}]}],"kind":"content"}],"metadata":{"navigatorTitle":[{"text":"renderOpenGL:","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"renderOpenGL","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMCustomLayerRenderParameters","text":"CustomLayerRenderParameters","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"renderOpenGL(_:)","modules":[{"name":"MapboxMaps"}],"symbolKind":"method","externalID":"c:objc(pl)MBMCustomLayerHost(im)renderOpenGL:"},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerHost\/renderOpenGL(_:)","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"Render the layer. This method is called once per frame. The implementation should not make"},{"type":"text","text":" "},{"type":"text","text":"any assumptions about the GL state (other than that the correct context is active). It may"},{"text":" ","type":"text"},{"type":"text","text":"make changes to the state, and is not required to reset values such as the depth mask, stencil"},{"text":" ","type":"text"},{"type":"text","text":"mask, and corresponding test flags to their original values."},{"type":"text","text":" "},{"type":"text","text":"Make sure that you are drawing your fragments with a z value of 1 to take advantage of the"},{"text":" ","type":"text"},{"text":"opaque fragment culling in case there are opaque layers above your custom layer.","type":"text"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerHost":{"navigatorTitle":[{"kind":"identifier","text":"CustomLayerHost"}],"role":"symbol","abstract":[{"type":"text","text":"Interface for hosting a custom map style layer."}],"title":"CustomLayerHost","type":"topic","url":"\/documentation\/mapboxmaps\/customlayerhost","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerHost","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomLayerHost","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","kind":"symbol","title":"MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","url":"\/documentation\/overview","abstract":[],"kind":"article","title":"MapboxMaps Documentation","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerRenderParameters":{"type":"topic","kind":"symbol","abstract":[{"text":"Parameters that define the current camera position for a ","type":"text"},{"code":"CustomLayerHost::render()","type":"codeVoice"},{"type":"text","text":" function."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters","title":"CustomLayerRenderParameters","role":"symbol","url":"\/documentation\/mapboxmaps\/customlayerrenderparameters","navigatorTitle":[{"text":"CustomLayerRenderParameters","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CustomLayerRenderParameters","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layers":{"url":"\/documentation\/mapboxmaps\/layers","abstract":[],"role":"collectionGroup","kind":"article","type":"topic","title":"Layers","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerHost/renderOpenGL(_:)":{"navigatorTitle":[{"kind":"identifier","text":"renderOpenGL:"}],"url":"\/documentation\/mapboxmaps\/customlayerhost\/renderopengl(_:)","role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerHost\/renderOpenGL(_:)","abstract":[{"text":"Render the layer. This method is called once per frame. The implementation should not make","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"any assumptions about the GL state (other than that the correct context is active). It may"},{"type":"text","text":" "},{"type":"text","text":"make changes to the state, and is not required to reset values such as the depth mask, stencil"},{"text":" ","type":"text"},{"type":"text","text":"mask, and corresponding test flags to their original values."},{"text":" ","type":"text"},{"type":"text","text":"Make sure that you are drawing your fragments with a z value of 1 to take advantage of the"},{"type":"text","text":" "},{"type":"text","text":"opaque fragment culling in case there are opaque layers above your custom layer."}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"renderOpenGL"},{"text":"(","kind":"text"},{"text":"CustomLayerRenderParameters","preciseIdentifier":"c:objc(cs)MBMCustomLayerRenderParameters","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"renderOpenGL(_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"renderOpenGL:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"renderOpenGL:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"renderOpenGL:"},{"text":"(","kind":"text"},{"text":"MBMCustomLayerRenderParameters","preciseIdentifier":"c:objc(cs)MBMCustomLayerRenderParameters","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"parameters"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost\/title","value":"MBMCustomLayerHost","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost\/fragments","value":[{"text":"MBMCustomLayerHost","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost\/navigatorTitle","value":[{"text":"MBMCustomLayerHost","kind":"identifier"}]},{"value":"MBMCustomLayerRenderParameters","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/fragments","value":[{"kind":"identifier","text":"MBMCustomLayerRenderParameters"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/navigatorTitle","value":[{"kind":"identifier","text":"MBMCustomLayerRenderParameters"}]},{"op":"replace","value":"renderOpenGL:","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost~1renderOpenGL(_:)\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost~1renderOpenGL(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"renderOpenGL:","kind":"identifier"}],"op":"replace"}]}]}