{"metadata":{"title":"setAltitudeForAltitude:","symbolKind":"method","roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"text":"setAltitudeForAltitude:","kind":"identifier"}],"modules":[{"name":"MapboxMaps"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setAltitudeForAltitude:"}],"externalID":"c:objc(cs)MBMFreeCameraOptions(im)setAltitudeForAltitude:"},"kind":"symbol","identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMFreeCameraOptions\/setAltitudeForAltitude:","interfaceLanguage":"occ"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/mbmfreecameraoptions\/setaltitudeforaltitude:"]}],"abstract":[{"text":"Helper function for setting the altitude in meters.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"text":"setAltitudeForAltitude:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"altitude","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The altitude in meters.","type":"text"}]}],"name":"altitude"}],"kind":"parameters"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMFreeCameraOptions/setAltitudeForAltitude:":{"role":"symbol","abstract":[{"type":"text","text":"Helper function for setting the altitude in meters."}],"navigatorTitle":[{"text":"setAltitudeForAltitude:","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMFreeCameraOptions\/setAltitudeForAltitude:","url":"\/documentation\/mapboxmaps\/mbmfreecameraoptions\/setaltitudeforaltitude:","kind":"symbol","type":"topic","fragments":[{"kind":"text","text":"- "},{"text":"setAltitudeForAltitude:","kind":"identifier"}],"title":"setAltitudeForAltitude:"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FreeCameraOptions":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FreeCameraOptions","kind":"identifier"}],"type":"topic","title":"FreeCameraOptions","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FreeCameraOptions"}],"url":"\/documentation\/mapboxmaps\/freecameraoptions","abstract":[{"type":"text","text":"Various options for accessing physical properties of the underlying camera entity."},{"text":" ","type":"text"},{"text":"A direct access to these properties allows more flexible and precise controlling","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"of the camera while also being fully compatible and interchangeable with CameraOptions."},{"text":" ","type":"text"},{"text":"All fields are optional.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","kind":"article","title":"MapboxMaps Documentation","abstract":[],"role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"kind":"article","abstract":[],"url":"\/documentation\/mapboxmaps\/mapboxmap-apis","type":"topic","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","title":"MapboxMap"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions\/title","value":"MBMFreeCameraOptions","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions\/fragments","value":[{"kind":"identifier","text":"MBMFreeCameraOptions"}]},{"op":"replace","value":[{"kind":"identifier","text":"MBMFreeCameraOptions"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}