{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient\/fromCustomRasterSourceTileStatusChangedCallback(_:)"},"kind":"symbol","sections":[],"metadata":{"role":"symbol","navigatorTitle":[{"text":"fromCustomRasterSourceTileStatusChangedCallback:","kind":"identifier"}],"roleHeading":"Type Method","title":"fromCustomRasterSourceTileStatusChangedCallback(_:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fromCustomRasterSourceTileStatusChangedCallback","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:MBMCustomRasterSourceTileStatusChangedCallback.h@T@MBMCustomRasterSourceTileStatusChangedCallback","text":"CustomRasterSourceTileStatusChangedCallback","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"}],"symbolKind":"method","modules":[{"name":"MapboxMaps"}],"externalID":"c:objc(cs)MBMCustomRasterSourceClient(cm)fromCustomRasterSourceTileStatusChangedCallback:"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fromCustomRasterSourceTileStatusChangedCallback","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"value","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomRasterSourceTileStatusChangedCallback","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatusChangedCallback","preciseIdentifier":"c:MBMCustomRasterSourceTileStatusChangedCallback.h@T@MBMCustomRasterSourceTileStatusChangedCallback"},{"text":") -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/customrastersourceclient\/fromcustomrastersourcetilestatuschangedcallback(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/customrastersourceclient\/fromcustomrastersourcetilestatuschangedcallback(_:)"]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceClient":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomRasterSourceClient","kind":"identifier"}],"role":"symbol","abstract":[],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"CustomRasterSourceClient","kind":"identifier"}],"title":"CustomRasterSourceClient","url":"\/documentation\/mapboxmaps\/customrastersourceclient","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileStatusChangedCallback":{"abstract":[{"text":"Callback for changing a CustomRasterSource tile status.","type":"text"}],"title":"CustomRasterSourceTileStatusChangedCallback","url":"\/documentation\/mapboxmaps\/customrastersourcetilestatuschangedcallback","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"CustomRasterSourceTileStatusChangedCallback","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatusChangedCallback","type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomRasterSourceTileStatusChangedCallback","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"role":"collection","kind":"symbol","url":"\/documentation\/mapboxmaps","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceClient/fromCustomRasterSourceTileStatusChangedCallback(_:)":{"navigatorTitle":[{"text":"fromCustomRasterSourceTileStatusChangedCallback:","kind":"identifier"}],"abstract":[],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient\/fromCustomRasterSourceTileStatusChangedCallback(_:)","title":"fromCustomRasterSourceTileStatusChangedCallback(_:)","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fromCustomRasterSourceTileStatusChangedCallback","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:MBMCustomRasterSourceTileStatusChangedCallback.h@T@MBMCustomRasterSourceTileStatusChangedCallback","text":"CustomRasterSourceTileStatusChangedCallback","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/customrastersourceclient\/fromcustomrastersourcetilestatuschangedcallback(_:)"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","kind":"article","title":"MapboxMaps Documentation","url":"\/documentation\/overview","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Sources":{"role":"collectionGroup","url":"\/documentation\/mapboxmaps\/sources","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources","kind":"article","title":"Sources","type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"fromCustomRasterSourceTileStatusChangedCallback:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"fromCustomRasterSourceTileStatusChangedCallback:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"fromCustomRasterSourceTileStatusChangedCallback:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(MBMCanonicalTileID *, enum MBMCustomRasterSourceTileStatus)","preciseIdentifier":"c:BFv(#*$objc(cs)MBMCanonicalTileID#$@E@MBMCustomRasterSourceTileStatus)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"value"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient\/title","value":"MBMCustomRasterSourceClient"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient\/fragments","value":[{"text":"MBMCustomRasterSourceClient","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient\/navigatorTitle","value":[{"text":"MBMCustomRasterSourceClient","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatusChangedCallback\/title","value":"MBMCustomRasterSourceTileStatusChangedCallback"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatusChangedCallback\/fragments","value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileStatusChangedCallback"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatusChangedCallback\/navigatorTitle","value":[{"text":"MBMCustomRasterSourceTileStatusChangedCallback","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient~1fromCustomRasterSourceTileStatusChangedCallback(_:)\/title","value":"fromCustomRasterSourceTileStatusChangedCallback:"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient~1fromCustomRasterSourceTileStatusChangedCallback(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"fromCustomRasterSourceTileStatusChangedCallback:","kind":"identifier"}]}]}]}