{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType"]]},"kind":"article","sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType\/Equatable-Implementations"},"metadata":{"modules":[{"name":"MapboxCommon"}],"roleHeading":"API Collection","role":"collectionGroup","title":"Equatable Implementations"},"topicSections":[{"anchor":"Operators","title":"Operators","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType\/!=(_:_:)"],"generated":true}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionErrorType/!=(_:_:)":{"abstract":[],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType\/!=(_:_:)","url":"\/documentation\/mapboxcommon\/tileregionerrortype\/!=(_:_:)","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"!=(_:_:)","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionErrorType":{"title":"TileRegionErrorType","type":"topic","abstract":[{"type":"text","text":"Describes the reason for a tile region download request failure."}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileRegionErrorType"}],"role":"symbol","url":"\/documentation\/mapboxcommon\/tileregionerrortype","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType","navigatorTitle":[{"kind":"identifier","text":"TileRegionErrorType"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"kind":"symbol","type":"topic","title":"MapboxCommon","role":"collection","url":"\/documentation\/mapboxcommon","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","url":"\/documentation\/overview","abstract":[],"kind":"article","title":"MapboxMaps Documentation","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"MBXTileRegionErrorType","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionErrorType\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionErrorType\/fragments","value":[{"text":"MBXTileRegionErrorType","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"MBXTileRegionErrorType"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionErrorType\/navigatorTitle"}]}]}