{"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@discardableResult","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"querySourceFeatures"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"target"},{"kind":"text","text":": "},{"text":"FeaturesetQueryTarget","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeaturesetQueryTarget","preciseIdentifier":"s:10MapboxMaps21FeaturesetQueryTargetV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"keyword"},{"kind":"text","text":" ("},{"preciseIdentifier":"s:s6ResultO","text":"Result","kind":"typeIdentifier"},{"text":"<[","kind":"text"},{"text":"QueriedSourceFeature","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedSourceFeature","preciseIdentifier":"c:objc(cs)MBMQueriedSourceFeature"},{"kind":"text","text":"], any "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> any "},{"preciseIdentifier":"c:objc(pl)MBXCancelable","text":"Cancelable","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Cancelable"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"target","content":[{"inlineContent":[{"text":"A featureset query target.","type":"text"}],"type":"paragraph"}]},{"name":"completion","content":[{"inlineContent":[{"text":"Callback called when the query completes.","type":"text"}],"type":"paragraph"}]}]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/querySourceFeatures(for:completion:)","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"Queries  the source features for a given featureset.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap"]]},"seeAlsoSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/queryRenderedFeatures(with:options:completion:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/queryRenderedFeatures(with:targets:completion:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/querySourceFeatures(for:options:completion:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/getGeoJsonClusterLeaves(forSourceId:feature:limit:offset:completion:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/getGeoJsonClusterChildren(forSourceId:feature:completion:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/getGeoJsonClusterExpansionZoom(forSourceId:feature:completion:)"],"generated":true,"title":"Quering map features","anchor":"Quering-map-features"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/mapboxmap\/querysourcefeatures(for:completion:)"]}],"metadata":{"role":"symbol","extendedModule":"MapboxMaps","symbolKind":"method","roleHeading":"Instance Method","tags":[{"type":"spi","text":"SPI"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"querySourceFeatures"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps21FeaturesetQueryTargetV","text":"FeaturesetQueryTarget"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"preciseIdentifier":"s:s6ResultO","text":"Result","kind":"typeIdentifier"},{"kind":"text","text":"<["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMQueriedSourceFeature","text":"QueriedSourceFeature"},{"kind":"text","text":"], any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":">) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":") -> any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MBXCancelable","text":"Cancelable"}],"externalID":"s:10MapboxMaps0A3MapC19querySourceFeatures3for10completionSo13MBXCancelable_pAA21FeaturesetQueryTargetV_ys6ResultOySaySo010MBMQueriedE7FeatureCGs5Error_pGctF","title":"querySourceFeatures(for:completion:)","modules":[{"name":"MapboxMaps"}]},"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/getGeoJsonClusterChildren(forSourceId:feature:completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getGeoJsonClusterChildren","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forSourceId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"feature","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Feature","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps7Featurea"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO","text":"Result"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMFeatureExtensionValue","kind":"typeIdentifier","text":"FeatureExtensionValue"},{"kind":"text","text":", any "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":">) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":") -> any ","kind":"text"},{"text":"Cancelable","preciseIdentifier":"c:objc(pl)MBXCancelable","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/getGeoJsonClusterChildren(forSourceId:feature:completion:)","type":"topic","title":"getGeoJsonClusterChildren(forSourceId:feature:completion:)","role":"symbol","abstract":[{"text":"Returns the children (original points or clusters) of a cluster (on the next zoom level)","type":"text"},{"type":"text","text":" "},{"text":"given its id (cluster_id value from feature properties) from a GeoJSON source.","type":"text"}],"url":"\/documentation\/mapboxmaps\/mapboxmap\/getgeojsonclusterchildren(forsourceid:feature:completion:)","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"url":"\/documentation\/mapboxmaps\/mapboxmap-apis","kind":"article","title":"MapboxMap","role":"collectionGroup","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/getGeoJsonClusterExpansionZoom(forSourceId:feature:completion:)":{"url":"\/documentation\/mapboxmaps\/mapboxmap\/getgeojsonclusterexpansionzoom(forsourceid:feature:completion:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getGeoJsonClusterExpansionZoom","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forSourceId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"feature","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps7Featurea","kind":"typeIdentifier","text":"Feature"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"Result","preciseIdentifier":"s:s6ResultO","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMFeatureExtensionValue","kind":"typeIdentifier","text":"FeatureExtensionValue"},{"kind":"text","text":", any "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":">) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":") -> any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MBXCancelable","text":"Cancelable"}],"abstract":[{"type":"text","text":"Returns the zoom on which the cluster expands into several children (useful for “click to zoom” feature)"},{"text":" ","type":"text"},{"text":"given the cluster’s cluster_id (cluster_id value from feature properties) from a GeoJSON source.","type":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/getGeoJsonClusterExpansionZoom(forSourceId:feature:completion:)","title":"getGeoJsonClusterExpansionZoom(forSourceId:feature:completion:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap":{"url":"\/documentation\/mapboxmaps\/mapboxmap","kind":"symbol","title":"MapboxMap","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapboxMap"}],"navigatorTitle":[{"text":"MapboxMap","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","abstract":[{"text":"Provides access to the map model, including the camera, style, observable map events,","type":"text"},{"text":" ","type":"text"},{"text":"and querying rendered features.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FeaturesetQueryTarget":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeaturesetQueryTarget","navigatorTitle":[{"text":"FeaturesetQueryTarget","kind":"identifier"}],"title":"FeaturesetQueryTarget","url":"\/documentation\/mapboxmaps\/featuresetquerytarget","type":"topic","tags":[{"text":"SPI","type":"spi"}],"abstract":[{"type":"text","text":"Defines the parameters for querying features from a Featureset with an optional filter and id."}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"FeaturesetQueryTarget","kind":"identifier"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/getGeoJsonClusterLeaves(forSourceId:feature:limit:offset:completion:)":{"url":"\/documentation\/mapboxmaps\/mapboxmap\/getgeojsonclusterleaves(forsourceid:feature:limit:offset:completion:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getGeoJsonClusterLeaves"},{"kind":"text","text":"("},{"text":"forSourceId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"feature","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Feature","preciseIdentifier":"s:10MapboxMaps7Featurea","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"limit"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s6UInt64V","kind":"typeIdentifier","text":"UInt64"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"offset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V","text":"UInt64"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"text":"<","kind":"text"},{"text":"FeatureExtensionValue","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMFeatureExtensionValue"},{"text":", any ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":") -> any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MBXCancelable","text":"Cancelable"}],"abstract":[{"text":"Returns all the leaves (original points) of a cluster (given its cluster_id) from a GeoJSON source, with pagination support: limit is the number of leaves","type":"text"},{"type":"text","text":" "},{"text":"to return (set to Infinity for all points), and offset is the amount of points to skip (for pagination).","type":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/getGeoJsonClusterLeaves(forSourceId:feature:limit:offset:completion:)","title":"getGeoJsonClusterLeaves(forSourceId:feature:limit:offset:completion:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/querySourceFeatures(for:completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"querySourceFeatures","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps21FeaturesetQueryTargetV","kind":"typeIdentifier","text":"FeaturesetQueryTarget"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO","text":"Result"},{"kind":"text","text":"<["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMQueriedSourceFeature","text":"QueriedSourceFeature"},{"text":"], any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":">) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":") -> any ","kind":"text"},{"text":"Cancelable","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MBXCancelable"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/querySourceFeatures(for:completion:)","type":"topic","title":"querySourceFeatures(for:completion:)","role":"symbol","tags":[{"text":"SPI","type":"spi"}],"abstract":[{"text":"Queries  the source features for a given featureset.","type":"text"}],"url":"\/documentation\/mapboxmaps\/mapboxmap\/querysourcefeatures(for:completion:)","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/queryRenderedFeatures(with:targets:completion:)":{"tags":[{"type":"spi","text":"SPI"}],"url":"\/documentation\/mapboxmaps\/mapboxmap\/queryrenderedfeatures(with:targets:completion:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"queryRenderedFeatures","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": some ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps32RenderedQueryGeometryConvertibleP","kind":"typeIdentifier","text":"RenderedQueryGeometryConvertible"},{"kind":"text","text":", "},{"kind":"externalParam","text":"targets"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps21FeaturesetQueryTargetV","text":"FeaturesetQueryTarget"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<["},{"text":"QueriedRenderedFeature","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMQueriedRenderedFeature"},{"text":"], any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":">) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":") -> any ","kind":"text"},{"text":"Cancelable","preciseIdentifier":"c:objc(pl)MBXCancelable","kind":"typeIdentifier"}],"abstract":[{"text":"Queries the map for rendered features using featureset descriptors.","type":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/queryRenderedFeatures(with:targets:completion:)","title":"queryRenderedFeatures(with:targets:completion:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/QueriedSourceFeature":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Represents query result that is returned in QuerySourceFeaturesCallback."}],"kind":"symbol","navigatorTitle":[{"text":"QueriedSourceFeature","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedSourceFeature","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"QueriedSourceFeature","kind":"identifier"}],"title":"QueriedSourceFeature","url":"\/documentation\/mapboxmaps\/queriedsourcefeature"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","url":"\/documentation\/overview","abstract":[],"type":"topic","role":"collection","title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/querySourceFeatures(for:options:completion:)":{"url":"\/documentation\/mapboxmaps\/mapboxmap\/querysourcefeatures(for:options:completion:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"querySourceFeatures","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMSourceQueryOptions","text":"SourceQueryOptions"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:s6ResultO","kind":"typeIdentifier","text":"Result"},{"kind":"text","text":"<["},{"preciseIdentifier":"c:objc(cs)MBMQueriedSourceFeature","kind":"typeIdentifier","text":"QueriedSourceFeature"},{"text":"], any ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":") -> any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)MBXCancelable","text":"Cancelable","kind":"typeIdentifier"}],"abstract":[{"text":"Queries the map for source features.","type":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/querySourceFeatures(for:options:completion:)","title":"querySourceFeatures(for:options:completion:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/queryRenderedFeatures(with:options:completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"queryRenderedFeatures"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"text":": some ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps32RenderedQueryGeometryConvertibleP","kind":"typeIdentifier","text":"RenderedQueryGeometryConvertible"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"text":": ","kind":"text"},{"text":"RenderedQueryOptions","preciseIdentifier":"c:objc(cs)MBMRenderedQueryOptions","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:s6ResultO","kind":"typeIdentifier","text":"Result"},{"text":"<[","kind":"text"},{"text":"QueriedRenderedFeature","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMQueriedRenderedFeature"},{"kind":"text","text":"], any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":">) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":") -> any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)MBXCancelable","text":"Cancelable","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/queryRenderedFeatures(with:options:completion:)","type":"topic","title":"queryRenderedFeatures(with:options:completion:)","role":"symbol","abstract":[{"text":"Queries the map for rendered features.","type":"text"}],"url":"\/documentation\/mapboxmaps\/mapboxmap\/queryrenderedfeatures(with:options:completion:)","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Cancelable":{"title":"Cancelable","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"Cancelable","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Cancelable","url":"\/documentation\/mapboxcommon\/cancelable","abstract":[{"type":"text","text":"Allows to cancel the associated asynchronous operation"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Cancelable"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MBMQueriedSourceFeature","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedSourceFeature\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MBMQueriedSourceFeature"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedSourceFeature\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedSourceFeature\/navigatorTitle","value":[{"kind":"identifier","text":"MBMQueriedSourceFeature"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/title","value":"MBXCancelable"},{"value":[{"kind":"identifier","text":"MBXCancelable"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/fragments"},{"value":[{"kind":"identifier","text":"MBXCancelable"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/navigatorTitle","op":"replace"}]}]}