{"abstract":[{"text":"Describes whether to constrain the map in both axes or only vertically e.g. while panning.","type":"text"}],"seeAlsoSections":[{"generated":true,"anchor":"MapView","title":"MapView","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapView","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapInitOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapInitOptionsProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AttributionURLOpener","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/NorthOrientation","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PresentationTransactionMode"]}],"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"symbolKind":"enum","externalID":"c:@E@MBMConstrainMode","roleHeading":"Enumeration","navigatorTitle":[{"kind":"identifier","text":"ConstrainMode"}],"modules":[{"name":"MapboxMaps"}],"title":"ConstrainMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConstrainMode"}],"role":"symbol"},"variants":[{"paths":["\/documentation\/mapboxmaps\/constrainmode"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/constrainmode"]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-View"]]},"relationshipsSections":[{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/s15BitwiseCopyableP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH","doc:\/\/com.mapbox.MapboxMaps\/SY","doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ConstrainMode","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"topicSections":[{"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ConstrainMode\/heightOnly","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ConstrainMode\/none","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ConstrainMode\/widthAndHeight"]},{"title":"Initializers","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ConstrainMode\/init(rawValue:)"],"anchor":"Initializers","generated":true},{"generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ConstrainMode\/Equatable-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ConstrainMode\/RawRepresentable-Implementations"],"anchor":"Default-Implementations","title":"Default Implementations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ConstrainMode"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapInitOptionsProvider":{"abstract":[{"type":"text","text":"A protocol used to provide "},{"isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapInitOptions","type":"reference"},{"text":" when initializing a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapView","isActive":true},{"type":"text","text":" with a Storyboard or"},{"type":"text","text":" "},{"type":"text","text":"a nib."}],"url":"\/documentation\/mapboxmaps\/mapinitoptionsprovider","kind":"symbol","title":"MapInitOptionsProvider","navigatorTitle":[{"kind":"identifier","text":"MapInitOptionsProvider"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapInitOptionsProvider","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapInitOptionsProvider"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapInitOptions":{"url":"\/documentation\/mapboxmaps\/mapinitoptions","abstract":[{"text":"Options used when initializing ","type":"text"},{"code":"MapView","type":"codeVoice"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapInitOptions","navigatorTitle":[{"kind":"identifier","text":"MapInitOptions"}],"kind":"symbol","title":"MapInitOptions","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapInitOptions"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","role":"collection","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","title":"MapboxMaps Documentation","url":"\/documentation\/overview","type":"topic","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewportMode":{"abstract":[{"type":"text","text":"Satisfies embedding platforms that requires the viewport coordinate systems to be set according to its standards."}],"url":"\/documentation\/mapboxmaps\/viewportmode","kind":"symbol","title":"ViewportMode","navigatorTitle":[{"text":"ViewportMode","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ViewportMode"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GlyphsRasterizationMode":{"url":"\/documentation\/mapboxmaps\/glyphsrasterizationmode","abstract":[{"type":"text","text":"Describes glyphs rasterization modes."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode","navigatorTitle":[{"kind":"identifier","text":"GlyphsRasterizationMode"}],"kind":"symbol","title":"GlyphsRasterizationMode","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"GlyphsRasterizationMode","kind":"identifier"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapView":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MapView"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapView","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapView"}],"url":"\/documentation\/mapboxmaps\/mapview","kind":"symbol","title":"MapView"},"doc://com.mapbox.MapboxMaps/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/NorthOrientation":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NorthOrientation"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/NorthOrientation","abstract":[{"type":"text","text":"Describes the map orientation."}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NorthOrientation"}],"url":"\/documentation\/mapboxmaps\/northorientation","kind":"symbol","title":"NorthOrientation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ConstrainMode/none":{"url":"\/documentation\/mapboxmaps\/constrainmode\/none","abstract":[{"type":"text","text":"No constrains."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ConstrainMode\/none","navigatorTitle":[{"kind":"identifier","text":"MBMConstrainModeNone"}],"kind":"symbol","title":"ConstrainMode.none","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ConstrainMode":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ConstrainMode"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ConstrainMode","abstract":[{"type":"text","text":"Describes whether to constrain the map in both axes or only vertically e.g. while panning."}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConstrainMode"}],"url":"\/documentation\/mapboxmaps\/constrainmode","kind":"symbol","title":"ConstrainMode"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapOptions":{"url":"\/documentation\/mapboxmaps\/mapoptions","abstract":[{"type":"text","text":"Describes the map option values."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapOptions","navigatorTitle":[{"kind":"identifier","text":"MapOptions"}],"kind":"symbol","title":"MapOptions","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapOptions"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/s15BitwiseCopyableP":{"type":"unresolvable","title":"Swift.BitwiseCopyable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s15BitwiseCopyableP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map-View":{"title":"MapView","url":"\/documentation\/mapboxmaps\/map-view","kind":"article","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-View","abstract":[],"type":"topic"},"doc://com.mapbox.MapboxMaps/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SY"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ConstrainMode/RawRepresentable-Implementations":{"type":"topic","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ConstrainMode\/RawRepresentable-Implementations","abstract":[],"url":"\/documentation\/mapboxmaps\/constrainmode\/rawrepresentable-implementations","kind":"article","title":"RawRepresentable Implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GlyphsRasterizationOptions":{"url":"\/documentation\/mapboxmaps\/glyphsrasterizationoptions","abstract":[{"type":"text","text":"Describes the glyphs rasterization option values."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationOptions","navigatorTitle":[{"kind":"identifier","text":"GlyphsRasterizationOptions"}],"kind":"symbol","title":"GlyphsRasterizationOptions","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GlyphsRasterizationOptions"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PresentationTransactionMode":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PresentationTransactionMode"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PresentationTransactionMode","abstract":[{"type":"text","text":"Determines if the underlying "},{"code":"CAMetalLayer","type":"codeVoice"},{"type":"text","text":" rendering output should synchronize with the Core Animation transactions."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PresentationTransactionMode"}],"url":"\/documentation\/mapboxmaps\/presentationtransactionmode","kind":"symbol","title":"PresentationTransactionMode"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ConstrainMode/heightOnly":{"url":"\/documentation\/mapboxmaps\/constrainmode\/heightonly","abstract":[{"type":"text","text":"Constrain to height only"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ConstrainMode\/heightOnly","navigatorTitle":[{"text":"MBMConstrainModeHeightOnly","kind":"identifier"}],"kind":"symbol","title":"ConstrainMode.heightOnly","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"heightOnly"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ConstrainMode/widthAndHeight":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBMConstrainModeWidthAndHeight"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ConstrainMode\/widthAndHeight","abstract":[{"type":"text","text":"Constrain both width and height axes."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"widthAndHeight","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/constrainmode\/widthandheight","kind":"symbol","title":"ConstrainMode.widthAndHeight"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ConstrainMode/init(rawValue:)":{"url":"\/documentation\/mapboxmaps\/constrainmode\/init(rawvalue:)","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ConstrainMode\/init(rawValue:)","kind":"symbol","title":"init(rawValue:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AttributionURLOpener":{"abstract":[{"text":"A protocol to open attribution URLs.","type":"text"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AttributionURLOpener","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AttributionURLOpener"}],"url":"\/documentation\/mapboxmaps\/attributionurlopener","kind":"symbol","title":"AttributionURLOpener","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AttributionURLOpener"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ConstrainMode/Equatable-Implementations":{"url":"\/documentation\/mapboxmaps\/constrainmode\/equatable-implementations","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ConstrainMode\/Equatable-Implementations","kind":"article","title":"Equatable Implementations","type":"topic","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"path":"\/metadata\/title","value":"MBMConstrainMode","op":"replace"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MBMConstrainMode","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"MBMConstrainMode","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"title":"Enumeration Cases","anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ConstrainMode\/heightOnly","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ConstrainMode\/none","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ConstrainMode\/widthAndHeight"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/NorthOrientation","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportMode"],"title":"MapView","anchor":"MapView"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBMConstrainMode","kind":"identifier"},{"kind":"text","text":": "},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":"MBMViewportMode","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewportMode\/title"},{"op":"replace","value":[{"text":"MBMViewportMode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewportMode\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewportMode\/navigatorTitle","value":[{"text":"MBMViewportMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/title","value":"MBMGlyphsRasterizationMode","op":"replace"},{"value":[{"kind":"identifier","text":"MBMGlyphsRasterizationMode"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMGlyphsRasterizationMode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1NorthOrientation\/title","value":"MBMNorthOrientation"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1NorthOrientation\/fragments","op":"replace","value":[{"text":"MBMNorthOrientation","kind":"identifier"}]},{"op":"replace","value":[{"text":"MBMNorthOrientation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1NorthOrientation\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ConstrainMode~1none\/title","value":"MBMConstrainModeNone"},{"value":[{"kind":"identifier","text":"MBMConstrainModeNone"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ConstrainMode~1none\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ConstrainMode\/title","value":"MBMConstrainMode","op":"replace"},{"op":"replace","value":[{"text":"MBMConstrainMode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ConstrainMode\/fragments"},{"value":[{"text":"MBMConstrainMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ConstrainMode\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapOptions\/title","value":"MBMMapOptions"},{"value":[{"kind":"identifier","text":"MBMMapOptions"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapOptions\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapOptions\/navigatorTitle","value":[{"text":"MBMMapOptions","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationOptions\/title","value":"MBMGlyphsRasterizationOptions"},{"value":[{"text":"MBMGlyphsRasterizationOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationOptions\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationOptions\/navigatorTitle","value":[{"text":"MBMGlyphsRasterizationOptions","kind":"identifier"}],"op":"replace"},{"value":"MBMConstrainModeHeightOnly","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ConstrainMode~1heightOnly\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ConstrainMode~1heightOnly\/fragments","op":"replace","value":[{"text":"MBMConstrainModeHeightOnly","kind":"identifier"}]},{"value":"MBMConstrainModeWidthAndHeight","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ConstrainMode~1widthAndHeight\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ConstrainMode~1widthAndHeight\/fragments","value":[{"kind":"identifier","text":"MBMConstrainModeWidthAndHeight"}],"op":"replace"}]}]}