{"sections":[],"abstract":[{"text":"Associated ","type":"text"},{"code":"MapOptions","type":"codeVoice"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapInitOptions\/mapOptions","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/mapboxmaps\/mapinitoptions\/mapoptions"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"mapOptions"},{"kind":"text","text":": "},{"text":"MapOptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapOptions","preciseIdentifier":"c:objc(cs)MBMMapOptions","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-View","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapInitOptions"]]},"kind":"symbol","metadata":{"role":"symbol","symbolKind":"property","modules":[{"name":"MapboxMaps"}],"title":"mapOptions","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"mapOptions","kind":"identifier"},{"kind":"text","text":": "},{"text":"MapOptions","preciseIdentifier":"c:objc(cs)MBMMapOptions","kind":"typeIdentifier"}],"externalID":"s:10MapboxMaps14MapInitOptionsC03mapE0So06MBMMapE0Cvp","roleHeading":"Instance Property"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map-View":{"role":"collectionGroup","kind":"article","title":"MapView","abstract":[],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-View","url":"\/documentation\/mapboxmaps\/map-view"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapInitOptions":{"abstract":[{"text":"Options used when initializing ","type":"text"},{"type":"codeVoice","code":"MapView"},{"type":"text","text":"."}],"title":"MapInitOptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapInitOptions","url":"\/documentation\/mapboxmaps\/mapinitoptions","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapInitOptions"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MapInitOptions"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"role":"collection","url":"\/documentation\/mapboxmaps","title":"MapboxMaps","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","abstract":[],"type":"topic","kind":"article","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapInitOptions/mapOptions":{"url":"\/documentation\/mapboxmaps\/mapinitoptions\/mapoptions","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"mapOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMMapOptions","text":"MapOptions"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapInitOptions\/mapOptions","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Associated "},{"code":"MapOptions","type":"codeVoice"}],"title":"mapOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapOptions":{"title":"MapOptions","abstract":[{"type":"text","text":"Describes the map option values."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapOptions"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapOptions","type":"topic","navigatorTitle":[{"text":"MapOptions","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/mapboxmaps\/mapoptions"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapOptions\/title","value":"MBMMapOptions","op":"replace"},{"value":[{"text":"MBMMapOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapOptions\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapOptions\/navigatorTitle","value":[{"kind":"identifier","text":"MBMMapOptions"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}