{"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedType\/tile","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedType"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"type":"text","text":"The tile data of a source."}],"variants":[{"paths":["\/documentation\/mapboxmaps\/sourcedataloadedtype\/tile"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/sourcedataloadedtype\/tile"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tile"}],"externalID":"c:@E@MBMSourceDataLoadedType@MBMSourceDataLoadedTypeTile","modules":[{"name":"MapboxMaps"}],"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"MBMSourceDataLoadedTypeTile"}],"roleHeading":"Case","title":"SourceDataLoadedType.tile","role":"symbol"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tile"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"abstract":[{"type":"text","text":"The simplified diagram of the events emitted by the map is displayed below."}],"title":"Map events","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","kind":"article","url":"\/documentation\/mapboxmaps\/events","role":"collectionGroup","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"url":"\/documentation\/mapboxmaps","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","title":"MapboxMaps","kind":"symbol","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceDataLoadedType/tile":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBMSourceDataLoadedTypeTile"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tile"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedType\/tile","kind":"symbol","abstract":[{"text":"The tile data of a source.","type":"text"}],"url":"\/documentation\/mapboxmaps\/sourcedataloadedtype\/tile","type":"topic","title":"SourceDataLoadedType.tile"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"url":"\/documentation\/overview","kind":"article","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceDataLoadedType":{"abstract":[{"text":"The enumeration defines the type of loaded source data.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceDataLoadedType"}],"type":"topic","title":"SourceDataLoadedType","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SourceDataLoadedType"}],"url":"\/documentation\/mapboxmaps\/sourcedataloadedtype","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"MBMSourceDataLoadedTypeTile","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"MBMSourceDataLoadedTypeTile","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"MBMSourceDataLoadedTypeTile","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"MBMSourceDataLoadedTypeTile","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedType~1tile\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBMSourceDataLoadedTypeTile"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedType~1tile\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedType\/title","op":"replace","value":"MBMSourceDataLoadedType"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedType\/fragments","op":"replace","value":[{"text":"MBMSourceDataLoadedType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMSourceDataLoadedType"}]}]}]}