{"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/snapshotter\/coordinatebounds(for:)"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"coordinateBounds"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"camera"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraOptions","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps13CameraOptionsV","text":"CameraOptions"},{"kind":"text","text":") -> "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMCoordinateBounds","text":"CoordinateBounds"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The camera for which the coordinate bounds will be returned.","type":"text"}],"type":"paragraph"}],"name":"camera"}]},{"content":[{"text":"Return Value","anchor":"return-value","type":"heading","level":2},{"inlineContent":[{"type":"text","text":""},{"code":"CoordinateBounds","type":"codeVoice"},{"type":"text","text":" for the given "},{"code":"CameraOptions","type":"codeVoice"}],"type":"paragraph"}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter\/coordinateBounds(for:)"},"abstract":[{"text":"Returns the coordinate bounds corresponding to a given ","type":"text"},{"code":"CameraOptions","type":"codeVoice"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"externalID":"s:10MapboxMaps11SnapshotterC16coordinateBounds3forSo013MBMCoordinateE0CAA13CameraOptionsV_tF","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"coordinateBounds","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CameraOptions","preciseIdentifier":"s:10MapboxMaps13CameraOptionsV","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"CoordinateBounds","preciseIdentifier":"c:objc(cs)MBMCoordinateBounds","kind":"typeIdentifier"}],"roleHeading":"Instance Method","modules":[{"name":"MapboxMaps"}],"role":"symbol","title":"coordinateBounds(for:)"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateBounds":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoordinateBounds"}],"abstract":[{"type":"text","text":"A rectangular area as measured on a two-dimensional map projection."}],"url":"\/documentation\/mapboxmaps\/coordinatebounds","role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds","navigatorTitle":[{"kind":"identifier","text":"CoordinateBounds"}],"title":"CoordinateBounds","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Snapshotter/coordinateBounds(for:)":{"url":"\/documentation\/mapboxmaps\/snapshotter\/coordinatebounds(for:)","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter\/coordinateBounds(for:)","title":"coordinateBounds(for:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"coordinateBounds","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CameraOptions","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps13CameraOptionsV"},{"text":") -> ","kind":"text"},{"text":"CoordinateBounds","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMCoordinateBounds"}],"abstract":[{"type":"text","text":"Returns the coordinate bounds corresponding to a given "},{"type":"codeVoice","code":"CameraOptions"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","url":"\/documentation\/mapboxmaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","kind":"article","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Snapshotter-APIs":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter-APIs","abstract":[],"title":"Snapshotter","role":"collectionGroup","kind":"article","url":"\/documentation\/mapboxmaps\/snapshotter-apis"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraOptions":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraOptions","role":"symbol","title":"CameraOptions","url":"\/documentation\/mapboxmaps\/cameraoptions","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraOptions"}],"navigatorTitle":[{"kind":"identifier","text":"CameraOptions"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Snapshotter":{"abstract":[{"type":"text","text":"A utility class for capturing styled map snapshots."}],"navigatorTitle":[{"text":"Snapshotter","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Snapshotter","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter","title":"Snapshotter","url":"\/documentation\/mapboxmaps\/snapshotter"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MBMCoordinateBounds","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds\/title"},{"value":[{"text":"MBMCoordinateBounds","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds\/fragments"},{"value":[{"kind":"identifier","text":"MBMCoordinateBounds"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds\/navigatorTitle"}]}]}