{"abstract":[{"text":"Show a wireframe for 2d layers. Currently supported for GL backend only.","type":"text"}],"metadata":{"navigatorTitle":[{"text":"MBMMapDebugOptionsLayers2DWireframe","kind":"identifier"}],"externalID":"c:@E@MBMMapDebugOptions@MBMMapDebugOptionsLayers2DWireframe","symbolKind":"case","modules":[{"name":"MapboxMaps"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"layers2DWireframe"}],"role":"symbol","roleHeading":"Case","title":"MapDebugOptions.layers2DWireframe"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/mapdebugoptions\/layers2dwireframe"]},{"paths":["\/documentation\/mapboxmaps\/mapdebugoptions\/layers2dwireframe"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"layers2DWireframe"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/layers2DWireframe","interfaceLanguage":"swift"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapDebugOptions/layers2DWireframe":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/layers2DWireframe","navigatorTitle":[{"kind":"identifier","text":"MBMMapDebugOptionsLayers2DWireframe"}],"url":"\/documentation\/mapboxmaps\/mapdebugoptions\/layers2dwireframe","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"layers2DWireframe","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Show a wireframe for 2d layers. Currently supported for GL backend only.","type":"text"}],"kind":"symbol","type":"topic","title":"MapDebugOptions.layers2DWireframe"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Performance":{"title":"Performance and investigations","url":"\/documentation\/mapboxmaps\/performance","kind":"article","role":"collectionGroup","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","role":"collection","abstract":[],"type":"topic","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapDebugOptions":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MapDebugOptions"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapDebugOptions"}],"title":"MapDebugOptions","role":"symbol","kind":"symbol","url":"\/documentation\/mapboxmaps\/mapdebugoptions","abstract":[{"text":"Options for enabling debugging features in a map.","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"MBMMapDebugOptionsLayers2DWireframe","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"text":"MBMMapDebugOptionsLayers2DWireframe","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"MBMMapDebugOptionsLayers2DWireframe","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":"MBMMapDebugOptionsLayers2DWireframe","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions~1layers2DWireframe\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions~1layers2DWireframe\/fragments","value":[{"text":"MBMMapDebugOptionsLayers2DWireframe","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions\/title","op":"replace","value":"MBMMapDebugOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions\/fragments","value":[{"text":"MBMMapDebugOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMMapDebugOptions"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}