{"sections":[],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/RawRepresentable-Implementations","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions"]]},"kind":"article","schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"collectionGroup","title":"RawRepresentable Implementations","modules":[{"name":"MapboxMaps"}],"roleHeading":"API Collection"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/hashValue"],"anchor":"Instance-Properties","generated":true},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/hash(into:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapDebugOptions":{"title":"MapDebugOptions","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"MapDebugOptions","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MapDebugOptions"}],"abstract":[{"type":"text","text":"Options for enabling debugging features in a map."}],"role":"symbol","url":"\/documentation\/mapboxmaps\/mapdebugoptions","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapDebugOptions/hash(into:)":{"conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":"."}]},"title":"hash(into:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"keyword","text":"inout"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:s6HasherV","text":"Hasher","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/hash(into:)","role":"symbol","kind":"symbol","url":"\/documentation\/mapboxmaps\/mapdebugoptions\/hash(into:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapDebugOptions/hashValue":{"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/hashValue","role":"symbol","url":"\/documentation\/mapboxmaps\/mapdebugoptions\/hashvalue","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"text":".","type":"text"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"availabilityPrefix":[{"type":"text","text":"Available when"}]},"title":"hashValue","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","title":"MapboxMaps Documentation","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Performance":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","abstract":[],"title":"Performance and investigations","role":"collectionGroup","kind":"article","type":"topic","url":"\/documentation\/mapboxmaps\/performance"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","role":"collection","url":"\/documentation\/mapboxmaps","kind":"symbol","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"MBMMapDebugOptions","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions\/title"},{"value":[{"text":"MBMMapDebugOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions\/navigatorTitle","value":[{"kind":"identifier","text":"MBMMapDebugOptions"}],"op":"replace"}]}]}