{"kind":"symbol","abstract":[{"text":"Show a wireframe for terrain. Currently supported for GL backend only.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/mapdebugoptions\/terrainwireframe"]},{"paths":["\/documentation\/mapboxmaps\/mapdebugoptions\/terrainwireframe"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions"]]},"metadata":{"roleHeading":"Case","symbolKind":"case","externalID":"c:@E@MBMMapDebugOptions@MBMMapDebugOptionsTerrainWireframe","title":"MapDebugOptions.terrainWireframe","modules":[{"name":"MapboxMaps"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"terrainWireframe"}],"navigatorTitle":[{"text":"MBMMapDebugOptionsTerrainWireframe","kind":"identifier"}],"role":"symbol"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/terrainWireframe","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"terrainWireframe"}]}],"kind":"declarations"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","kind":"symbol","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Performance":{"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","title":"Performance and investigations","kind":"article","role":"collectionGroup","type":"topic","url":"\/documentation\/mapboxmaps\/performance"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapDebugOptions":{"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/mapdebugoptions","title":"MapDebugOptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions","abstract":[{"type":"text","text":"Options for enabling debugging features in a map."}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MapDebugOptions","kind":"identifier"}],"navigatorTitle":[{"text":"MapDebugOptions","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","role":"collection","title":"MapboxMaps Documentation","abstract":[],"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapDebugOptions/terrainWireframe":{"role":"symbol","title":"MapDebugOptions.terrainWireframe","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/terrainWireframe","kind":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"terrainWireframe"}],"navigatorTitle":[{"text":"MBMMapDebugOptionsTerrainWireframe","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/mapdebugoptions\/terrainwireframe","abstract":[{"type":"text","text":"Show a wireframe for terrain. Currently supported for GL backend only."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"MBMMapDebugOptionsTerrainWireframe"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"MBMMapDebugOptionsTerrainWireframe"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"MBMMapDebugOptionsTerrainWireframe","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"MBMMapDebugOptions","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions\/title"},{"value":[{"text":"MBMMapDebugOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions\/navigatorTitle","value":[{"kind":"identifier","text":"MBMMapDebugOptions"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions~1terrainWireframe\/title","value":"MBMMapDebugOptionsTerrainWireframe"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions~1terrainWireframe\/fragments","value":[{"text":"MBMMapDebugOptionsTerrainWireframe","kind":"identifier"}]}]}]}