{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Style","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Image"]]},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Image\/data"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"data","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/DataRef","text":"DataRef","preciseIdentifier":"c:@M@MapboxCommon@objc(cs)MBXDataRef"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/image\/data"]}],"kind":"symbol","metadata":{"externalID":"s:14MapboxMaps5ImageV4data0A6Common7DataRefCvp","title":"data","symbolKind":"property","tags":[{"type":"spi","text":"SPI"}],"role":"symbol","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"data"},{"kind":"text","text":": "},{"text":"DataRef","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapboxCommon@objc(cs)MBXDataRef"}],"modules":[{"name":"MapboxMaps"}]},"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","url":"\/documentation\/overview","role":"collection","kind":"article","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"role":"collection","title":"MapboxMaps","type":"topic","url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Style":{"role":"collectionGroup","url":"\/documentation\/mapboxmaps\/style","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Style","abstract":[],"title":"Style","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Image/data":{"kind":"symbol","title":"data","tags":[{"type":"spi","text":"SPI"}],"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Image\/data","type":"topic","url":"\/documentation\/mapboxmaps\/image\/data","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"data"},{"kind":"text","text":": "},{"text":"DataRef","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapboxCommon@objc(cs)MBXDataRef"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Image":{"tags":[{"type":"spi","text":"SPI"}],"title":"Image","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Image"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Image","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Image"}],"abstract":[],"url":"\/documentation\/mapboxmaps\/image","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/DataRef":{"title":"DataRef","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DataRef","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/dataref","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/DataRef","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DataRef","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"MBXDataRef","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1DataRef\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MBXDataRef"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1DataRef\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1DataRef\/navigatorTitle","op":"replace","value":[{"text":"MBXDataRef","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}