{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionStatus"]]},"metadata":{"roleHeading":"Initializer","navigatorTitle":[{"kind":"identifier","text":"initWithDownloadState:completedResourceCount:completedResourceSize:completedTileCount:requiredTileCount:completedTileSize:requiredResourceCount:requiredResourceCountIsPrecise:"}],"title":"init(downloadState:completedResourceCount:completedResourceSize:completedTileCount:requiredTileCount:completedTileSize:requiredResourceCount:requiredResourceCountIsPrecise:)","modules":[{"name":"MapboxMaps"}],"externalID":"c:objc(cs)MBMOfflineRegionStatus(im)initWithDownloadState:completedResourceCount:completedResourceSize:completedTileCount:requiredTileCount:completedTileSize:requiredResourceCount:requiredResourceCountIsPrecise:","symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"downloadState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMOfflineRegionDownloadState","text":"OfflineRegionDownloadState"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completedResourceCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V","text":"UInt64"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completedResourceSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V","text":"UInt64"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completedTileCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V","text":"UInt64"},{"kind":"text","text":", "},{"kind":"externalParam","text":"requiredTileCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V","text":"UInt64"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completedTileSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V","text":"UInt64"},{"kind":"text","text":", "},{"kind":"externalParam","text":"requiredResourceCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V","text":"UInt64"},{"kind":"text","text":", "},{"kind":"externalParam","text":"requiredResourceCountIsPrecise"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"role":"symbol","platforms":[]},"variants":[{"paths":["\/documentation\/mapboxmaps\/offlineregionstatus\/init(downloadstate:completedresourcecount:completedresourcesize:completedtilecount:requiredtilecount:completedtilesize:requiredresourcecount:requiredresourcecountisprecise:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/offlineregionstatus\/init(downloadstate:completedresourcecount:completedresourcesize:completedtilecount:requiredtilecount:completedtilesize:requiredresourcecount:requiredresourcecountisprecise:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionStatus\/init(downloadState:completedResourceCount:completedResourceSize:completedTileCount:requiredTileCount:completedTileSize:requiredResourceCount:requiredResourceCountIsPrecise:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"downloadState","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"OfflineRegionDownloadState","preciseIdentifier":"c:@E@MBMOfflineRegionDownloadState","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionDownloadState","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completedResourceCount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt64","preciseIdentifier":"s:s6UInt64V","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completedResourceSize","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt64","preciseIdentifier":"s:s6UInt64V","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completedTileCount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt64","preciseIdentifier":"s:s6UInt64V","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"requiredTileCount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt64","preciseIdentifier":"s:s6UInt64V","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completedTileSize","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt64","preciseIdentifier":"s:s6UInt64V","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"requiredResourceCount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt64","preciseIdentifier":"s:s6UInt64V","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"requiredResourceCountIsPrecise","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Offline":{"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","abstract":[],"role":"collectionGroup","type":"topic","title":"Offline Support","url":"\/documentation\/mapboxmaps\/offline"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMaps":{"role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","type":"topic","url":"\/documentation\/mapboxmaps\/coremaps","title":"Core Maps API","abstract":[{"text":"Maps rendering SDK also known as GL-Native","type":"text"}],"kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionStatus":{"deprecated":true,"kind":"symbol","type":"topic","title":"OfflineRegionStatus","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionStatus","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OfflineRegionStatus","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"OfflineRegionStatus","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/offlineregionstatus","abstract":[{"type":"text","text":"A region’s status includes its active\/inactive state as well as counts"},{"type":"text","text":" "},{"type":"text","text":"of the number of resources that have completed downloading, their total"},{"type":"text","text":" "},{"type":"text","text":"size in bytes, and the total number of resources that are required."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionStatus/init(downloadState:completedResourceCount:completedResourceSize:completedTileCount:requiredTileCount:completedTileSize:requiredResourceCount:requiredResourceCountIsPrecise:)":{"type":"topic","deprecated":true,"kind":"symbol","navigatorTitle":[{"text":"initWithDownloadState:completedResourceCount:completedResourceSize:completedTileCount:requiredTileCount:completedTileSize:requiredResourceCount:requiredResourceCountIsPrecise:","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionStatus\/init(downloadState:completedResourceCount:completedResourceSize:completedTileCount:requiredTileCount:completedTileSize:requiredResourceCount:requiredResourceCountIsPrecise:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"downloadState","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"OfflineRegionDownloadState","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMOfflineRegionDownloadState"},{"text":", ","kind":"text"},{"text":"completedResourceCount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt64","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V"},{"text":", ","kind":"text"},{"text":"completedResourceSize","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt64","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V"},{"text":", ","kind":"text"},{"text":"completedTileCount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt64","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V"},{"text":", ","kind":"text"},{"text":"requiredTileCount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt64","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V"},{"text":", ","kind":"text"},{"text":"completedTileSize","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt64","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V"},{"text":", ","kind":"text"},{"text":"requiredResourceCount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt64","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V"},{"text":", ","kind":"text"},{"text":"requiredResourceCountIsPrecise","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"abstract":[],"url":"\/documentation\/mapboxmaps\/offlineregionstatus\/init(downloadstate:completedresourcecount:completedresourcesize:completedtilecount:requiredtilecount:completedtilesize:requiredresourcecount:requiredresourcecountisprecise:)","role":"symbol","title":"init(downloadState:completedResourceCount:completedResourceSize:completedTileCount:requiredTileCount:completedTileSize:requiredResourceCount:requiredResourceCountIsPrecise:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","url":"\/documentation\/mapboxmaps","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","role":"collection","title":"MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","url":"\/documentation\/overview","kind":"article","abstract":[],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionDownloadState":{"url":"\/documentation\/mapboxmaps\/offlineregiondownloadstate","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OfflineRegionDownloadState"}],"title":"OfflineRegionDownloadState","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OfflineRegionDownloadState"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionDownloadState","deprecated":true,"abstract":[{"text":"Describes the download state of a region.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithDownloadState:completedResourceCount:completedResourceSize:completedTileCount:requiredTileCount:completedTileSize:requiredResourceCount:requiredResourceCountIsPrecise:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithDownloadState:completedResourceCount:completedResourceSize:completedTileCount:requiredTileCount:completedTileSize:requiredResourceCount:requiredResourceCountIsPrecise:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithDownloadState:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MBMOfflineRegionDownloadState","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionDownloadState","preciseIdentifier":"c:@E@MBMOfflineRegionDownloadState"},{"text":") ","kind":"text"},{"text":"downloadState","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completedResourceCount:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@uint64_t","text":"uint64_t","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"completedResourceCount","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completedResourceSize:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@uint64_t","text":"uint64_t","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"completedResourceSize","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completedTileCount:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"uint64_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@uint64_t"},{"text":") ","kind":"text"},{"text":"completedTileCount","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"requiredTileCount:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"uint64_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@uint64_t"},{"text":") ","kind":"text"},{"text":"requiredTileCount","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completedTileSize:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"uint64_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@uint64_t"},{"text":") ","kind":"text"},{"text":"completedTileSize","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"requiredResourceCount:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"uint64_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@uint64_t"},{"text":") ","kind":"text"},{"text":"requiredResourceCount","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"requiredResourceCountIsPrecise:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"requiredResourceCountIsPrecise","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MBMOfflineRegionStatus","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionStatus\/title"},{"value":[{"kind":"identifier","text":"MBMOfflineRegionStatus"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionStatus\/fragments"},{"op":"replace","value":[{"text":"MBMOfflineRegionStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionStatus\/navigatorTitle"},{"op":"replace","value":"initWithDownloadState:completedResourceCount:completedResourceSize:completedTileCount:requiredTileCount:completedTileSize:requiredResourceCount:requiredResourceCountIsPrecise:","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionStatus~1init(downloadState:completedResourceCount:completedResourceSize:completedTileCount:requiredTileCount:completedTileSize:requiredResourceCount:requiredResourceCountIsPrecise:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDownloadState:completedResourceCount:completedResourceSize:completedTileCount:requiredTileCount:completedTileSize:requiredResourceCount:requiredResourceCountIsPrecise:"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionStatus~1init(downloadState:completedResourceCount:completedResourceSize:completedTileCount:requiredTileCount:completedTileSize:requiredResourceCount:requiredResourceCountIsPrecise:)\/fragments"},{"op":"replace","value":"MBMOfflineRegionDownloadState","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionDownloadState\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBMOfflineRegionDownloadState"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionDownloadState\/fragments"},{"op":"replace","value":[{"text":"MBMOfflineRegionDownloadState","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionDownloadState\/navigatorTitle"}]}]}