{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationServiceObserver"}]}],"kind":"declarations"}],"metadata":{"externalID":"c:objc(pl)MBXLocationServiceObserver","role":"symbol","modules":[{"name":"MapboxCommon"}],"roleHeading":"Protocol","symbolKind":"protocol","title":"LocationServiceObserver","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"LocationServiceObserver","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"LocationServiceObserver"}]},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"Observers for getting updates from LocationService."}],"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver\/onAccuracyAuthorizationChanged(for:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver\/onAvailabilityChanged(forIsAvailable:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver\/onPermissionStatusChanged(forPermission:)"],"anchor":"Instance-Methods","title":"Instance Methods"}],"seeAlsoSections":[{"generated":true,"title":"Location","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationManager","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck2DConfiguration","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Model","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckBearing","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProviderDelegate","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Coordinate2D","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationExtraKeys","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProviderRequest","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceFactory","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/DeviceLocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Heading","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckRenderingData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/IntervalSettings"],"anchor":"Location"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/locationserviceobserver"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/locationserviceobserver"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationErrorCode":{"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LocationErrorCode"}],"abstract":[{"text":"Codes of location errors.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"LocationErrorCode"}],"kind":"symbol","url":"\/documentation\/mapboxcommon\/locationerrorcode","title":"LocationErrorCode","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LocationManager":{"role":"symbol","navigatorTitle":[{"text":"LocationManager","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationManager","url":"\/documentation\/mapboxmaps\/locationmanager","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"LocationManager","kind":"identifier"}],"type":"topic","title":"LocationManager","abstract":[{"type":"text","text":"An object responsible for managing user location Puck."}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationExtraKeys":{"navigatorTitle":[{"text":"LocationExtraKeys","kind":"identifier"}],"title":"LocationExtraKeys","url":"\/documentation\/mapboxcommon\/locationextrakeys","role":"symbol","abstract":[{"type":"text","text":"Keys for additional information (extra) in Location."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LocationExtraKeys"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationExtraKeys","kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationServiceObserver/onPermissionStatusChanged(forPermission:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onPermissionStatusChanged"},{"text":"(","kind":"text"},{"text":"forPermission","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBXPermissionStatus","text":"PermissionStatus"},{"kind":"text","text":")"}],"url":"\/documentation\/mapboxcommon\/locationserviceobserver\/onpermissionstatuschanged(forpermission:)","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver\/onPermissionStatusChanged(forPermission:)","title":"onPermissionStatusChanged(forPermission:)","role":"symbol","required":true,"type":"topic","navigatorTitle":[{"text":"onPermissionStatusChangedForPermission:","kind":"identifier"}],"abstract":[{"type":"text","text":"Called when a user has granted or revoked location permission to the app."},{"text":" ","type":"text"},{"type":"text","text":"Note that this does not work on Android because, in case of permission"},{"type":"text","text":" "},{"type":"text","text":"changes, the system will kill all running processes of the app."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationObserver":{"navigatorTitle":[{"text":"LocationObserver","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LocationObserver"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationObserver","type":"topic","kind":"symbol","url":"\/documentation\/mapboxcommon\/locationobserver","abstract":[{"text":"Observer for getting updates from a LocationProvider.","type":"text"}],"role":"symbol","title":"LocationObserver"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LocationOptions":{"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"LocationOptions","kind":"identifier"}],"navigatorTitle":[{"text":"LocationOptions","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationOptions","title":"LocationOptions","role":"symbol","url":"\/documentation\/mapboxmaps\/locationoptions","abstract":[{"text":"A struct to configure a ","type":"text"},{"type":"codeVoice","code":"LocationManager"}],"kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationServiceObserver":{"role":"symbol","navigatorTitle":[{"text":"LocationServiceObserver","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver","url":"\/documentation\/mapboxcommon\/locationserviceobserver","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LocationServiceObserver"}],"type":"topic","title":"LocationServiceObserver","abstract":[{"type":"text","text":"Observers for getting updates from LocationService."}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationProviderRequest":{"url":"\/documentation\/mapboxcommon\/locationproviderrequest","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"LocationProviderRequest"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProviderRequest","abstract":[{"type":"text","text":"Data model that contains parameters for location requests."}],"kind":"symbol","type":"topic","title":"LocationProviderRequest","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"LocationProviderRequest","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/DeviceLocationProvider":{"navigatorTitle":[{"text":"DeviceLocationProvider","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"DeviceLocationProvider","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/DeviceLocationProvider","type":"topic","kind":"symbol","url":"\/documentation\/mapboxcommon\/devicelocationprovider","abstract":[{"type":"text","text":"Location provider specialisation that provides real-time locations generated from the device"}],"role":"symbol","title":"DeviceLocationProvider"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PuckRenderingData":{"url":"\/documentation\/mapboxmaps\/puckrenderingdata","role":"symbol","navigatorTitle":[{"text":"PuckRenderingData","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckRenderingData","abstract":[{"type":"text","text":"Represents the interpolated data ready to render the user location puck."}],"kind":"symbol","type":"topic","title":"PuckRenderingData","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PuckRenderingData"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Location":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Location","kind":"identifier"}],"abstract":[{"text":"Location information.","type":"text"}],"title":"Location","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Location"}],"url":"\/documentation\/mapboxcommon\/location","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/AccuracyLevel":{"navigatorTitle":[{"kind":"identifier","text":"AccuracyLevel"}],"abstract":[{"text":"The accuracy of the observed location","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel","title":"AccuracyLevel","type":"topic","url":"\/documentation\/mapboxcommon\/accuracylevel","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"AccuracyLevel","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationServiceObserver/onAccuracyAuthorizationChanged(for:)":{"role":"symbol","title":"onAccuracyAuthorizationChanged(for:)","url":"\/documentation\/mapboxcommon\/locationserviceobserver\/onaccuracyauthorizationchanged(for:)","type":"topic","abstract":[{"type":"text","text":"Called when a user has changed accuracy authorization for the app."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver\/onAccuracyAuthorizationChanged(for:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onAccuracyAuthorizationChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@MBXAccuracyAuthorization","text":"AccuracyAuthorization","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"onAccuracyAuthorizationChangedForAuthorization:","kind":"identifier"}],"required":true,"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Puck3DConfiguration":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Puck3DConfiguration"}],"role":"symbol","abstract":[],"type":"topic","kind":"symbol","title":"Puck3DConfiguration","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration","navigatorTitle":[{"kind":"identifier","text":"Puck3DConfiguration"}],"url":"\/documentation\/mapboxmaps\/puck3dconfiguration"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AppleLocationProviderDelegate":{"navigatorTitle":[{"kind":"identifier","text":"AppleLocationProviderDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AppleLocationProviderDelegate"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProviderDelegate","type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/applelocationproviderdelegate","abstract":[{"type":"text","text":"The "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProviderDelegate"},{"type":"text","text":" protocol defines a set of optional methods that you"},{"text":" ","type":"text"},{"text":"can use to receive events from an associated location provider object.","type":"text"}],"role":"symbol","title":"AppleLocationProviderDelegate"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeadingProvider":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"HeadingProvider","kind":"identifier"}],"title":"HeadingProvider","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"HeadingProvider","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/headingprovider","abstract":[{"text":"Provides heading data to drive the location puck.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingProvider"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationError":{"url":"\/documentation\/mapboxcommon\/locationerror","role":"symbol","navigatorTitle":[{"text":"LocationError","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationError","abstract":[{"type":"text","text":"Error code with brief explanation."}],"kind":"symbol","type":"topic","title":"LocationError","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationError"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationServiceFactory":{"navigatorTitle":[{"text":"LocationServiceFactory","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"LocationServiceFactory","kind":"identifier"}],"type":"topic","title":"LocationServiceFactory","abstract":[{"type":"text","text":"Location service factory."}],"url":"\/documentation\/mapboxcommon\/locationservicefactory","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceFactory","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PermissionStatus":{"title":"PermissionStatus","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PermissionStatus","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus","navigatorTitle":[{"text":"PermissionStatus","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapboxcommon\/permissionstatus","abstract":[{"type":"text","text":"Location permissions granted by user to the app."}],"kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Model":{"abstract":[{"type":"text","text":"A structure represeting a Model"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"Model","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"Model","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/model","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Model","role":"symbol","title":"Model","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationServiceObserver/onAvailabilityChanged(forIsAvailable:)":{"type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onAvailabilityChanged"},{"text":"(","kind":"text"},{"text":"forIsAvailable","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"onAvailabilityChangedForIsAvailable:","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/locationserviceobserver\/onavailabilitychanged(forisavailable:)","required":true,"role":"symbol","title":"onAvailabilityChanged(forIsAvailable:)","abstract":[{"type":"text","text":"Called when an availability of location-based service on"},{"type":"text","text":" "},{"text":"the device has been changed. This happens when, for example,","type":"text"},{"text":" ","type":"text"},{"text":"a user disables geolocation on the device.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver\/onAvailabilityChanged(forIsAvailable:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PuckBearing":{"url":"\/documentation\/mapboxmaps\/puckbearing","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckBearing","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PuckBearing"}],"title":"PuckBearing","abstract":[{"type":"text","text":"Controls how the puck is oriented"}],"navigatorTitle":[{"text":"PuckBearing","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PuckType":{"role":"symbol","navigatorTitle":[{"text":"PuckType","kind":"identifier"}],"abstract":[{"type":"text","text":"Represents the different types of pucks"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PuckType","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckType","title":"PuckType","kind":"symbol","url":"\/documentation\/mapboxmaps\/pucktype"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Location-APIs":{"kind":"article","url":"\/documentation\/mapboxmaps\/location-apis","role":"collectionGroup","title":"Location","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Puck2DConfiguration":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck2DConfiguration","type":"topic","title":"Puck2DConfiguration","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Puck2DConfiguration"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Puck2DConfiguration"}],"url":"\/documentation\/mapboxmaps\/puck2dconfiguration","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Heading":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Heading"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Heading","url":"\/documentation\/mapboxmaps\/heading","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"Heading","kind":"identifier"}],"title":"Heading","type":"topic","abstract":[{"type":"text","text":"The azimuth (orientation) of the user’s device, relative to true or magnetic north."}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationProvider":{"url":"\/documentation\/mapboxcommon\/locationprovider","role":"symbol","navigatorTitle":[{"text":"LocationProvider","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider","abstract":[{"text":"Location provider that provides locations","type":"text"}],"kind":"symbol","type":"topic","title":"LocationProvider","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"LocationProvider","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/IntervalSettings":{"title":"IntervalSettings","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntervalSettings"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"IntervalSettings"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/IntervalSettings","abstract":[{"type":"text","text":"The interval for active location updates"}],"url":"\/documentation\/mapboxcommon\/intervalsettings"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/AccuracyAuthorization":{"navigatorTitle":[{"kind":"identifier","text":"AccuracyAuthorization"}],"abstract":[{"type":"text","text":"Accuracy authorization granted by user to the app."}],"url":"\/documentation\/mapboxcommon\/accuracyauthorization","type":"topic","title":"AccuracyAuthorization","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AccuracyAuthorization","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeadingObserver":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"HeadingObserver","kind":"identifier"}],"title":"HeadingObserver","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"HeadingObserver","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/headingobserver","abstract":[{"text":"Listens to ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingProvider"},{"type":"text","text":"’s updates."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingObserver"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Coordinate2D":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Coordinate2D"}],"abstract":[{"type":"text","text":"Boxed version of CLLocationCoordinate2D"}],"navigatorTitle":[{"text":"Coordinate2D","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapboxcommon\/coordinate2d","title":"Coordinate2D","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Coordinate2D","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AppleLocationProvider":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProvider","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppleLocationProvider"}],"url":"\/documentation\/mapboxmaps\/applelocationprovider","type":"topic","abstract":[{"text":"A location provider based on CoreLocation’s ","type":"text"},{"code":"CLLocationManager","type":"codeVoice"},{"type":"text","text":"."}],"title":"AppleLocationProvider","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AppleLocationProvider"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","abstract":[],"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","kind":"article","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"path":"\/metadata\/title","value":"MBXLocationServiceObserver","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"value":[{"text":"MBXLocationServiceObserver","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBXLocationServiceObserver"}],"path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver\/onAccuracyAuthorizationChanged(for:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver\/onAvailabilityChanged(forIsAvailable:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver\/onPermissionStatusChanged(forPermission:)"],"anchor":"Instance-Methods","title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Coordinate2D","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationExtraKeys","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProviderRequest","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceFactory","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/DeviceLocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/IntervalSettings"],"generated":true,"title":"Location","anchor":"Location"}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MBXLocationServiceObserver","kind":"identifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"MBXLocationErrorCode","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/fragments","value":[{"text":"MBXLocationErrorCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/navigatorTitle","value":[{"kind":"identifier","text":"MBXLocationErrorCode"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationExtraKeys\/title","value":"MBXLocationExtraKeys","op":"replace"},{"value":[{"text":"MBXLocationExtraKeys","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationExtraKeys\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationExtraKeys\/navigatorTitle","value":[{"text":"MBXLocationExtraKeys","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver~1onPermissionStatusChanged(forPermission:)\/title","op":"replace","value":"onPermissionStatusChangedForPermission:"},{"value":[{"text":"- ","kind":"text"},{"text":"onPermissionStatusChangedForPermission:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver~1onPermissionStatusChanged(forPermission:)\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/title","op":"replace","value":"MBXLocationObserver"},{"op":"replace","value":[{"text":"MBXLocationObserver","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/fragments"},{"value":[{"text":"MBXLocationObserver","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver\/title","value":"MBXLocationServiceObserver","op":"replace"},{"op":"replace","value":[{"text":"MBXLocationServiceObserver","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver\/navigatorTitle","value":[{"text":"MBXLocationServiceObserver","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProviderRequest\/title","value":"MBXLocationProviderRequest"},{"op":"replace","value":[{"text":"MBXLocationProviderRequest","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProviderRequest\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProviderRequest\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBXLocationProviderRequest"}]},{"value":"MBXDeviceLocationProvider","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1DeviceLocationProvider\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1DeviceLocationProvider\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXDeviceLocationProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1DeviceLocationProvider\/navigatorTitle","value":[{"text":"MBXDeviceLocationProvider","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/title","value":"MBXLocation","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/fragments","value":[{"text":"MBXLocation","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/navigatorTitle","op":"replace","value":[{"text":"MBXLocation","kind":"identifier"}]},{"op":"replace","value":"MBXAccuracyLevel","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBXAccuracyLevel"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel\/fragments"},{"value":[{"text":"MBXAccuracyLevel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver~1onAccuracyAuthorizationChanged(for:)\/title","value":"onAccuracyAuthorizationChangedForAuthorization:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"onAccuracyAuthorizationChangedForAuthorization:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver~1onAccuracyAuthorizationChanged(for:)\/fragments","op":"replace"},{"op":"replace","value":"MBXLocationError","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationError\/title"},{"value":[{"kind":"identifier","text":"MBXLocationError"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationError\/fragments"},{"op":"replace","value":[{"text":"MBXLocationError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationError\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceFactory\/title","value":"MBXLocationServiceFactory"},{"op":"replace","value":[{"text":"MBXLocationServiceFactory","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceFactory\/fragments"},{"value":[{"text":"MBXLocationServiceFactory","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceFactory\/navigatorTitle"},{"value":"MBXPermissionStatus","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXPermissionStatus"}]},{"value":[{"text":"MBXPermissionStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/navigatorTitle","op":"replace"},{"value":"onAvailabilityChangedForIsAvailable:","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver~1onAvailabilityChanged(forIsAvailable:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver~1onAvailabilityChanged(forIsAvailable:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onAvailabilityChangedForIsAvailable:"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/title","value":"MBXLocationProvider","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/fragments","value":[{"kind":"identifier","text":"MBXLocationProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/navigatorTitle","value":[{"kind":"identifier","text":"MBXLocationProvider"}]},{"value":"MBXIntervalSettings","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1IntervalSettings\/title"},{"op":"replace","value":[{"text":"MBXIntervalSettings","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1IntervalSettings\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1IntervalSettings\/navigatorTitle","value":[{"kind":"identifier","text":"MBXIntervalSettings"}],"op":"replace"},{"op":"replace","value":"MBXAccuracyAuthorization","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization\/fragments","value":[{"kind":"identifier","text":"MBXAccuracyAuthorization"}]},{"value":[{"kind":"identifier","text":"MBXAccuracyAuthorization"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Coordinate2D\/title","value":"MBXCoordinate2D"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Coordinate2D\/fragments","value":[{"kind":"identifier","text":"MBXCoordinate2D"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBXCoordinate2D"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Coordinate2D\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}