{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"y","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/mapboxmaps\/vec2\/y"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/vec2\/y"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"property","externalID":"c:objc(cs)MBMVec2(py)y","roleHeading":"Instance Property","modules":[{"name":"MapboxMaps"}],"navigatorTitle":[{"text":"y","kind":"identifier"}],"title":"y","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"y","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"abstract":[{"type":"text","text":"The y component of the vector."}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Vec2\/y"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Free-Camera","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Vec2"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Vec2/y":{"type":"topic","title":"y","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"y"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Vec2\/y","url":"\/documentation\/mapboxmaps\/vec2\/y","abstract":[{"type":"text","text":"The y component of the vector."}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"y","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Vec2":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Vec2","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Vec2","kind":"identifier"}],"title":"Vec2","url":"\/documentation\/mapboxmaps\/vec2","navigatorTitle":[{"kind":"identifier","text":"Vec2"}],"abstract":[{"type":"text","text":"2 component vector."}],"kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"kind":"article","role":"collection","url":"\/documentation\/overview","title":"MapboxMaps Documentation","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","title":"MapboxMaps","role":"collection","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMaps":{"abstract":[{"type":"text","text":"Maps rendering SDK also known as GL-Native"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","kind":"article","type":"topic","url":"\/documentation\/mapboxmaps\/coremaps","role":"collectionGroup","title":"Core Maps API"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Free-Camera":{"title":"Free Camera","type":"topic","kind":"article","role":"collectionGroup","abstract":[],"url":"\/documentation\/mapboxmaps\/free-camera","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Free-Camera"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"y"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"y","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"text":" ","kind":"text"},{"kind":"identifier","text":"y"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Vec2~1y\/title","value":"y"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Vec2~1y\/fragments","value":[{"text":"y","kind":"identifier"}]},{"value":"MBMVec2","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Vec2\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Vec2\/fragments","op":"replace","value":[{"text":"MBMVec2","kind":"identifier"}]},{"value":[{"text":"MBMVec2","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Vec2\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}