{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver"]]},"sections":[],"metadata":{"modules":[{"name":"MapboxCommon"}],"roleHeading":"Instance Method","externalID":"c:objc(pl)MBXLocationServiceObserver(im)onAccuracyAuthorizationChangedForAuthorization:","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onAccuracyAuthorizationChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@MBXAccuracyAuthorization","text":"AccuracyAuthorization","kind":"typeIdentifier"},{"kind":"text","text":")"}],"symbolKind":"method","title":"onAccuracyAuthorizationChanged(for:)","required":true,"navigatorTitle":[{"kind":"identifier","text":"onAccuracyAuthorizationChangedForAuthorization:"}]},"abstract":[{"type":"text","text":"Called when a user has changed accuracy authorization for the app."}],"kind":"symbol","identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver\/onAccuracyAuthorizationChanged(for:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/mapboxcommon\/locationserviceobserver\/onaccuracyauthorizationchanged(for:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxcommon\/locationserviceobserver\/onaccuracyauthorizationchanged(for:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onAccuracyAuthorizationChanged","kind":"identifier"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"authorization"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization","text":"AccuracyAuthorization","preciseIdentifier":"c:@E@MBXAccuracyAuthorization","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"authorization","content":[{"inlineContent":[{"text":"Updated accuracy authorization of the app.","type":"text"}],"type":"paragraph"}]}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Location-APIs":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","url":"\/documentation\/mapboxmaps\/location-apis","abstract":[],"kind":"article","type":"topic","role":"collectionGroup","title":"Location"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","role":"collection","title":"MapboxMaps Documentation","abstract":[],"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/AccuracyAuthorization":{"type":"topic","navigatorTitle":[{"text":"AccuracyAuthorization","kind":"identifier"}],"title":"AccuracyAuthorization","url":"\/documentation\/mapboxcommon\/accuracyauthorization","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AccuracyAuthorization"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization","role":"symbol","abstract":[{"text":"Accuracy authorization granted by user to the app.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationServiceObserver":{"type":"topic","navigatorTitle":[{"text":"LocationServiceObserver","kind":"identifier"}],"title":"LocationServiceObserver","url":"\/documentation\/mapboxcommon\/locationserviceobserver","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationServiceObserver"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver","role":"symbol","abstract":[{"type":"text","text":"Observers for getting updates from LocationService."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationServiceObserver/onAccuracyAuthorizationChanged(for:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onAccuracyAuthorizationChanged","kind":"identifier"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AccuracyAuthorization","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBXAccuracyAuthorization"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when a user has changed accuracy authorization for the app."}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver\/onAccuracyAuthorizationChanged(for:)","type":"topic","url":"\/documentation\/mapboxcommon\/locationserviceobserver\/onaccuracyauthorizationchanged(for:)","role":"symbol","navigatorTitle":[{"text":"onAccuracyAuthorizationChangedForAuthorization:","kind":"identifier"}],"title":"onAccuracyAuthorizationChanged(for:)","required":true},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","kind":"symbol","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"title":"MapboxMaps"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"onAccuracyAuthorizationChangedForAuthorization:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onAccuracyAuthorizationChangedForAuthorization:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"onAccuracyAuthorizationChangedForAuthorization:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization","text":"MBXAccuracyAuthorization","preciseIdentifier":"c:@E@MBXAccuracyAuthorization"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"authorization"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"authorization","content":[{"inlineContent":[{"type":"text","text":"Updated accuracy authorization of the app."}],"type":"paragraph"}]}]}},{"value":"MBXAccuracyAuthorization","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization\/fragments","value":[{"text":"MBXAccuracyAuthorization","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization\/navigatorTitle","value":[{"text":"MBXAccuracyAuthorization","kind":"identifier"}]},{"value":"MBXLocationServiceObserver","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver\/title"},{"op":"replace","value":[{"text":"MBXLocationServiceObserver","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver\/navigatorTitle","value":[{"kind":"identifier","text":"MBXLocationServiceObserver"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver~1onAccuracyAuthorizationChanged(for:)\/title","value":"onAccuracyAuthorizationChangedForAuthorization:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"onAccuracyAuthorizationChangedForAuthorization:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver~1onAccuracyAuthorizationChanged(for:)\/fragments"}]}]}