{"abstract":[{"text":"Called when a user has granted or revoked location permission to the app.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Note that this does not work on Android because, in case of permission"},{"text":" ","type":"text"},{"text":"changes, the system will kill all running processes of the app.","type":"text"}],"variants":[{"paths":["\/documentation\/mapboxcommon\/locationserviceobserver\/onpermissionstatuschanged(forpermission:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxcommon\/locationserviceobserver\/onpermissionstatuschanged(forpermission:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver\/onPermissionStatusChanged(forPermission:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onPermissionStatusChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forPermission"},{"kind":"text","text":" "},{"text":"permission","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@MBXPermissionStatus","kind":"typeIdentifier","text":"PermissionStatus","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"permission","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Updated permission of the app."}]}]}]}],"metadata":{"roleHeading":"Instance Method","modules":[{"name":"MapboxCommon"}],"title":"onPermissionStatusChanged(forPermission:)","navigatorTitle":[{"kind":"identifier","text":"onPermissionStatusChangedForPermission:"}],"symbolKind":"method","required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onPermissionStatusChanged"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forPermission"},{"text":": ","kind":"text"},{"text":"PermissionStatus","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBXPermissionStatus"},{"text":")","kind":"text"}],"externalID":"c:objc(pl)MBXLocationServiceObserver(im)onPermissionStatusChangedForPermission:"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver"]]},"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Location-APIs":{"type":"topic","abstract":[],"role":"collectionGroup","url":"\/documentation\/mapboxmaps\/location-apis","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","title":"Location"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationServiceObserver":{"title":"LocationServiceObserver","abstract":[{"text":"Observers for getting updates from LocationService.","type":"text"}],"role":"symbol","url":"\/documentation\/mapboxcommon\/locationserviceobserver","navigatorTitle":[{"text":"LocationServiceObserver","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationServiceObserver"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationServiceObserver/onPermissionStatusChanged(forPermission:)":{"role":"symbol","type":"topic","required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onPermissionStatusChanged","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forPermission"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBXPermissionStatus","text":"PermissionStatus"},{"text":")","kind":"text"}],"title":"onPermissionStatusChanged(forPermission:)","kind":"symbol","url":"\/documentation\/mapboxcommon\/locationserviceobserver\/onpermissionstatuschanged(forpermission:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver\/onPermissionStatusChanged(forPermission:)","navigatorTitle":[{"kind":"identifier","text":"onPermissionStatusChangedForPermission:"}],"abstract":[{"text":"Called when a user has granted or revoked location permission to the app.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Note that this does not work on Android because, in case of permission"},{"type":"text","text":" "},{"type":"text","text":"changes, the system will kill all running processes of the app."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","kind":"symbol","title":"MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PermissionStatus":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus","type":"topic","abstract":[{"text":"Location permissions granted by user to the app.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PermissionStatus","kind":"identifier"}],"navigatorTitle":[{"text":"PermissionStatus","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/permissionstatus","title":"PermissionStatus"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","url":"\/documentation\/overview","abstract":[],"kind":"article","title":"MapboxMaps Documentation","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"onPermissionStatusChangedForPermission:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"onPermissionStatusChangedForPermission:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"onPermissionStatusChangedForPermission:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@MBXPermissionStatus","kind":"typeIdentifier","text":"MBXPermissionStatus","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus"},{"kind":"text","text":") "},{"text":"permission","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":{"kind":"parameters","parameters":[{"name":"permission","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Updated permission of the app."}]}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver\/title","op":"replace","value":"MBXLocationServiceObserver"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver\/fragments","value":[{"kind":"identifier","text":"MBXLocationServiceObserver"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBXLocationServiceObserver"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver~1onPermissionStatusChanged(forPermission:)\/title","value":"onPermissionStatusChangedForPermission:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver~1onPermissionStatusChanged(forPermission:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onPermissionStatusChangedForPermission:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/title","value":"MBXPermissionStatus","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/fragments","value":[{"text":"MBXPermissionStatus","kind":"identifier"}]},{"op":"replace","value":[{"text":"MBXPermissionStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/navigatorTitle"}]}]}