{"metadata":{"roleHeading":"Instance Property","role":"symbol","modules":[{"name":"MapboxCommon"}],"navigatorTitle":[{"text":"requestId","kind":"identifier"}],"symbolKind":"property","externalID":"c:objc(cs)MBXHttpResponse(py)requestId","title":"requestId","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt64","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V"}]},"abstract":[{"text":"The id of the request that resulted in this response. Matches the return value of HttpServiceInterface::request.","type":"text"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpResponse\/requestId"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpResponse"]]},"variants":[{"paths":["\/documentation\/mapboxcommon\/httpresponse\/requestid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxcommon\/httpresponse\/requestid"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s6UInt64V","text":"UInt64","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpResponse/requestId":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpResponse\/requestId","navigatorTitle":[{"text":"requestId","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt64","preciseIdentifier":"s:s6UInt64V","kind":"typeIdentifier"}],"url":"\/documentation\/mapboxcommon\/httpresponse\/requestid","abstract":[{"text":"The id of the request that resulted in this response. Matches the return value of HttpServiceInterface::request.","type":"text"}],"type":"topic","title":"requestId","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article","type":"topic","title":"MapboxMaps Documentation","abstract":[],"url":"\/documentation\/overview","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"type":"topic","role":"collection","url":"\/documentation\/mapboxcommon","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","abstract":[],"kind":"symbol","title":"MapboxCommon"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpResponse":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HttpResponse"}],"type":"topic","title":"HttpResponse","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpResponse","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HttpResponse"}],"url":"\/documentation\/mapboxcommon\/httpresponse","abstract":[{"type":"text","text":"Record which is used to report HTTP response to the caller."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"requestId","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"requestId","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"uint64_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@uint64_t"},{"text":" ","kind":"text"},{"text":"requestId","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpResponse~1requestId\/title","value":"requestId","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpResponse~1requestId\/fragments","value":[{"kind":"identifier","text":"requestId"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpResponse\/title","value":"MBXHttpResponse","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpResponse\/fragments","value":[{"kind":"identifier","text":"MBXHttpResponse"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpResponse\/navigatorTitle","value":[{"kind":"identifier","text":"MBXHttpResponse"}],"op":"replace"}]}]}