{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/settingsservice\/get(key:type:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsService\/get(key:type:)"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Settings-and-Constants","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsService"]]},"kind":"symbol","sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"get"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"T"},{"kind":"text","text":">("},{"kind":"externalParam","text":"key"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"T","kind":"typeIdentifier"},{"text":".Type) -> ","kind":"text"},{"text":"Result","preciseIdentifier":"s:s6ResultO","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"T","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"SettingsServiceError","preciseIdentifier":"s:12MapboxCommon20SettingsServiceErrorV","kind":"typeIdentifier"},{"text":">","kind":"text"}],"roleHeading":"Instance Method","modules":[{"name":"MapboxCommon"}],"extendedModule":"MapboxCommon","externalID":"s:So18MBXSettingsServiceC12MapboxCommonE3get3key4types6ResultOyxAC08SettingsB5ErrorVGSS_xmtlF","role":"symbol","title":"get(key:type:)","symbolKind":"method"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"get","kind":"identifier"},{"text":"<","kind":"text"},{"text":"T","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"key","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"T","kind":"typeIdentifier"},{"text":".Type) -> ","kind":"text"},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"text":"<","kind":"text"},{"text":"T","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"SettingsServiceError","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceError","preciseIdentifier":"s:12MapboxCommon20SettingsServiceErrorV"},{"text":">","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","url":"\/documentation\/mapboxmaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsServiceError":{"kind":"symbol","title":"SettingsServiceError","url":"\/documentation\/mapboxcommon\/settingsserviceerror","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceError","role":"symbol","navigatorTitle":[{"text":"SettingsServiceError","kind":"identifier"}],"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SettingsServiceError","kind":"identifier"}],"abstract":[{"type":"text","text":"Structure for keeping an information about errors that can happen when using Settings service"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","kind":"article","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsService":{"kind":"symbol","url":"\/documentation\/mapboxcommon\/settingsservice","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SettingsService","kind":"identifier"}],"navigatorTitle":[{"text":"SettingsService","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsService","abstract":[{"type":"text","text":"Platform independent settings service. Settings service is a key\/value storage (persistent or non"},{"type":"text","text":" "},{"type":"text","text":"persistent), that also allows to register observers to get notifications when values are updated."}],"title":"SettingsService"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsService/get(key:type:)":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsService\/get(key:type:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"get"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"T"},{"kind":"text","text":">("},{"kind":"externalParam","text":"key"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"T"},{"kind":"text","text":".Type) -> "},{"preciseIdentifier":"s:s6ResultO","kind":"typeIdentifier","text":"Result"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"T"},{"kind":"text","text":", "},{"preciseIdentifier":"s:12MapboxCommon20SettingsServiceErrorV","kind":"typeIdentifier","text":"SettingsServiceError"},{"kind":"text","text":">"}],"url":"\/documentation\/mapboxcommon\/settingsservice\/get(key:type:)","type":"topic","abstract":[],"title":"get(key:type:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Settings-and-Constants":{"title":"Settings and Constants","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/settings-and-constants","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Settings-and-Constants","abstract":[],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsService\/title","value":"MBXSettingsService"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsService\/fragments","value":[{"text":"MBXSettingsService","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsService\/navigatorTitle","value":[{"text":"MBXSettingsService","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}