{"metadata":{"role":"symbol","externalID":"s:10MapboxMaps0A3MapC21queryRenderedFeatures4with7targets10completionSo13MBXCancelable_px_SayAA21FeaturesetQueryTargetVGys6ResultOySaySo010MBMQueriedE7FeatureCGs5Error_pGctAA0eL19GeometryConvertibleRzlF","roleHeading":"Instance Method","title":"queryRenderedFeatures(with:targets:completion:)","extendedModule":"MapboxMaps","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"queryRenderedFeatures","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"kind":"text","text":": some "},{"preciseIdentifier":"s:10MapboxMaps32RenderedQueryGeometryConvertibleP","text":"RenderedQueryGeometryConvertible","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"targets","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps21FeaturesetQueryTargetV","text":"FeaturesetQueryTarget","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMQueriedRenderedFeature","text":"QueriedRenderedFeature"},{"text":"], any ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":") -> any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MBXCancelable","text":"Cancelable"}],"modules":[{"name":"MapboxMaps"}],"tags":[{"type":"spi","text":"SPI"}]},"sections":[],"abstract":[{"text":"Queries the map for rendered features using featureset descriptors.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap"]]},"seeAlsoSections":[{"title":"Quering map features","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/queryRenderedFeatures(with:options:completion:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/querySourceFeatures(for:options:completion:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/querySourceFeatures(for:completion:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/getGeoJsonClusterLeaves(forSourceId:feature:limit:offset:completion:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/getGeoJsonClusterChildren(forSourceId:feature:completion:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/getGeoJsonClusterExpansionZoom(forSourceId:feature:completion:)"],"generated":true,"anchor":"Quering-map-features"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@discardableResult","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"queryRenderedFeatures","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"geometry"},{"kind":"text","text":": some "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometryConvertible","text":"RenderedQueryGeometryConvertible","preciseIdentifier":"s:10MapboxMaps32RenderedQueryGeometryConvertibleP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"targets"},{"kind":"text","text":": ["},{"text":"FeaturesetQueryTarget","preciseIdentifier":"s:10MapboxMaps21FeaturesetQueryTargetV","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeaturesetQueryTarget","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"keyword"},{"text":" (","kind":"text"},{"preciseIdentifier":"s:s6ResultO","text":"Result","kind":"typeIdentifier"},{"text":"<[","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMQueriedRenderedFeature","text":"QueriedRenderedFeature","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedRenderedFeature"},{"kind":"text","text":"], any "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":">) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":") -> any ","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Cancelable","kind":"typeIdentifier","text":"Cancelable","preciseIdentifier":"c:objc(pl)MBXCancelable"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"A screen geometry to query. Can be a "},{"type":"codeVoice","code":"CGPoint"},{"text":", ","type":"text"},{"code":"CGRect","type":"codeVoice"},{"type":"text","text":", or an array of "},{"code":"CGPoint","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}],"name":"geometry"},{"name":"targets","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An array of targets to query with."}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Callback called when the query completes."}]}]}],"kind":"parameters"},{"content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"inlineContent":[{"text":"This method allows to query both featureset from imported styles and user layers in the root style.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The results can be additionally filtered per-featureset."}],"type":"paragraph"},{"type":"codeListing","syntax":"swift","code":["let targets = [","    FeaturesetQueryTarget(","        featureset: .layer(\"my-layer\"),","        filter: Exp(.eq) {","            Exp(.get) { \"type\" }","            \"hotel\"","        }","    ),","    FeaturesetQueryTarget(featureset: .featureset(\"poi\", importId: \"basemap\"))","]","mapView.mapboxMap.queryRenderedFeatures(with: CGPoint(x: 0, y: 0),","                           targets: targets) { result in","    \/\/ handle features in result","}"]},{"content":[{"inlineContent":[{"text":"This is a low-level method. If you need to handle basic gestures on map content, please prefer to use Interactions API (see ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/addInteraction(_:)"},{"text":") or  ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/queryRenderedFeatures(with:featureset:filter:completion:)","type":"reference"},{"text":".","type":"text"}],"type":"paragraph"}],"name":"Important","style":"important","type":"aside"}],"kind":"content"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/mapboxmaps\/mapboxmap\/queryrenderedfeatures(with:targets:completion:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/queryRenderedFeatures(with:targets:completion:)","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FeaturesetQueryTarget":{"tags":[{"text":"SPI","type":"spi"}],"url":"\/documentation\/mapboxmaps\/featuresetquerytarget","navigatorTitle":[{"text":"FeaturesetQueryTarget","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeaturesetQueryTarget","role":"symbol","title":"FeaturesetQueryTarget","abstract":[{"type":"text","text":"Defines the parameters for querying features from a Featureset with an optional filter and id."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"FeaturesetQueryTarget","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/getGeoJsonClusterLeaves(forSourceId:feature:limit:offset:completion:)":{"type":"topic","abstract":[{"text":"Returns all the leaves (original points) of a cluster (given its cluster_id) from a GeoJSON source, with pagination support: limit is the number of leaves","type":"text"},{"type":"text","text":" "},{"type":"text","text":"to return (set to Infinity for all points), and offset is the amount of points to skip (for pagination)."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getGeoJsonClusterLeaves","kind":"identifier"},{"kind":"text","text":"("},{"text":"forSourceId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"feature"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps7Featurea","text":"Feature"},{"text":", ","kind":"text"},{"text":"limit","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V","text":"UInt64"},{"kind":"text","text":", "},{"kind":"externalParam","text":"offset"},{"text":": ","kind":"text"},{"text":"UInt64","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO","text":"Result"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMFeatureExtensionValue","text":"FeatureExtensionValue","kind":"typeIdentifier"},{"text":", any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":") -> any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)MBXCancelable","text":"Cancelable","kind":"typeIdentifier"}],"url":"\/documentation\/mapboxmaps\/mapboxmap\/getgeojsonclusterleaves(forsourceid:feature:limit:offset:completion:)","title":"getGeoJsonClusterLeaves(forSourceId:feature:limit:offset:completion:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/getGeoJsonClusterLeaves(forSourceId:feature:limit:offset:completion:)","role":"symbol","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderedQueryGeometryConvertible":{"role":"symbol","title":"RenderedQueryGeometryConvertible","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RenderedQueryGeometryConvertible"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/renderedquerygeometryconvertible","type":"topic","abstract":[{"text":"A convenience protocol for automatic conversion to ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometry","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometryConvertible","navigatorTitle":[{"text":"RenderedQueryGeometryConvertible","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/queryRenderedFeatures(with:featureset:filter:completion:)":{"tags":[{"text":"SPI","type":"spi"}],"url":"\/documentation\/mapboxmaps\/mapboxmap\/queryrenderedfeatures(with:featureset:filter:completion:)","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/queryRenderedFeatures(with:featureset:filter:completion:)","role":"symbol","title":"queryRenderedFeatures(with:featureset:filter:completion:)","abstract":[{"text":"Queries the map for rendered features with one typed featureset.","type":"text"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"queryRenderedFeatures","kind":"identifier"},{"text":"<","kind":"text"},{"text":"G","kind":"genericParameter"},{"text":", ","kind":"text"},{"text":"T","kind":"genericParameter"},{"kind":"text","text":">("},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"text":"G","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"featureset","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10MapboxMaps20FeaturesetDescriptorV","kind":"typeIdentifier","text":"FeaturesetDescriptor"},{"kind":"text","text":"<"},{"text":"T","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"text":"filter","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Exp","preciseIdentifier":"s:10MapboxMaps3ExpV","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:s6ResultO","kind":"typeIdentifier","text":"Result"},{"text":"<[","kind":"text"},{"kind":"typeIdentifier","text":"T"},{"text":"], any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":") -> any "},{"text":"Cancelable","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MBXCancelable"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"title":"MapboxMap","type":"topic","role":"collectionGroup","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","url":"\/documentation\/mapboxmaps\/mapboxmap-apis","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/addInteraction(_:)":{"type":"topic","abstract":[{"text":"Adds interaction to the map.","type":"text"}],"tags":[{"type":"spi","text":"SPI"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"addInteraction","kind":"identifier"},{"text":"(some ","kind":"text"},{"text":"Interaction","preciseIdentifier":"s:10MapboxMaps11InteractionP","kind":"typeIdentifier"},{"kind":"text","text":") -> any "},{"text":"Cancelable","preciseIdentifier":"c:objc(pl)MBXCancelable","kind":"typeIdentifier"}],"url":"\/documentation\/mapboxmaps\/mapboxmap\/addinteraction(_:)","title":"addInteraction(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/addInteraction(_:)","role":"symbol","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Cancelable":{"url":"\/documentation\/mapboxcommon\/cancelable","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Cancelable","navigatorTitle":[{"kind":"identifier","text":"Cancelable"}],"abstract":[{"type":"text","text":"Allows to cancel the associated asynchronous operation"}],"kind":"symbol","title":"Cancelable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Cancelable","kind":"identifier"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/getGeoJsonClusterChildren(forSourceId:feature:completion:)":{"url":"\/documentation\/mapboxmaps\/mapboxmap\/getgeojsonclusterchildren(forsourceid:feature:completion:)","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/getGeoJsonClusterChildren(forSourceId:feature:completion:)","role":"symbol","title":"getGeoJsonClusterChildren(forSourceId:feature:completion:)","abstract":[{"text":"Returns the children (original points or clusters) of a cluster (on the next zoom level)","type":"text"},{"type":"text","text":" "},{"text":"given its id (cluster_id value from feature properties) from a GeoJSON source.","type":"text"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getGeoJsonClusterChildren"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forSourceId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"feature"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps7Featurea","text":"Feature"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO","text":"Result"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"FeatureExtensionValue","preciseIdentifier":"c:objc(cs)MBMFeatureExtensionValue"},{"text":", any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":">) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":") -> any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MBXCancelable","text":"Cancelable"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","abstract":[],"url":"\/documentation\/overview","role":"collection","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/queryRenderedFeatures(with:targets:completion:)":{"type":"topic","abstract":[{"text":"Queries the map for rendered features using featureset descriptors.","type":"text"}],"tags":[{"type":"spi","text":"SPI"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"queryRenderedFeatures","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":": some "},{"preciseIdentifier":"s:10MapboxMaps32RenderedQueryGeometryConvertibleP","kind":"typeIdentifier","text":"RenderedQueryGeometryConvertible"},{"kind":"text","text":", "},{"text":"targets","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"FeaturesetQueryTarget","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps21FeaturesetQueryTargetV"},{"kind":"text","text":"], "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"text":"<[","kind":"text"},{"text":"QueriedRenderedFeature","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMQueriedRenderedFeature"},{"kind":"text","text":"], any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":">) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":") -> any ","kind":"text"},{"text":"Cancelable","preciseIdentifier":"c:objc(pl)MBXCancelable","kind":"typeIdentifier"}],"url":"\/documentation\/mapboxmaps\/mapboxmap\/queryrenderedfeatures(with:targets:completion:)","title":"queryRenderedFeatures(with:targets:completion:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/queryRenderedFeatures(with:targets:completion:)","role":"symbol","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/QueriedRenderedFeature":{"url":"\/documentation\/mapboxmaps\/queriedrenderedfeature","navigatorTitle":[{"kind":"identifier","text":"QueriedRenderedFeature"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedRenderedFeature","role":"symbol","title":"QueriedRenderedFeature","abstract":[{"text":"Represents query result that is returned in QueryRenderedFeaturesCallback.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"QueriedRenderedFeature"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/getGeoJsonClusterExpansionZoom(forSourceId:feature:completion:)":{"type":"topic","abstract":[{"type":"text","text":"Returns the zoom on which the cluster expands into several children (useful for “click to zoom” feature)"},{"type":"text","text":" "},{"text":"given the cluster’s cluster_id (cluster_id value from feature properties) from a GeoJSON source.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"getGeoJsonClusterExpansionZoom"},{"text":"(","kind":"text"},{"text":"forSourceId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"feature"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps7Featurea","text":"Feature","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"text":"<","kind":"text"},{"text":"FeatureExtensionValue","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMFeatureExtensionValue"},{"text":", any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":">) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":") -> any "},{"text":"Cancelable","preciseIdentifier":"c:objc(pl)MBXCancelable","kind":"typeIdentifier"}],"url":"\/documentation\/mapboxmaps\/mapboxmap\/getgeojsonclusterexpansionzoom(forsourceid:feature:completion:)","title":"getGeoJsonClusterExpansionZoom(forSourceId:feature:completion:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/getGeoJsonClusterExpansionZoom(forSourceId:feature:completion:)","role":"symbol","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderedQueryGeometry":{"title":"RenderedQueryGeometry","navigatorTitle":[{"kind":"identifier","text":"RenderedQueryGeometry"}],"abstract":[{"type":"text","text":"A geometry to define a portion of screen that should be queried for rendered features."}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/renderedquerygeometry","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometry","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RenderedQueryGeometry"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/querySourceFeatures(for:completion:)":{"tags":[{"type":"spi","text":"SPI"}],"url":"\/documentation\/mapboxmaps\/mapboxmap\/querysourcefeatures(for:completion:)","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/querySourceFeatures(for:completion:)","role":"symbol","title":"querySourceFeatures(for:completion:)","abstract":[{"text":"Queries  the source features for a given featureset.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"querySourceFeatures","kind":"identifier"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FeaturesetQueryTarget","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps21FeaturesetQueryTargetV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"text":"<[","kind":"text"},{"text":"QueriedSourceFeature","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMQueriedSourceFeature"},{"kind":"text","text":"], any "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":">) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":") -> any ","kind":"text"},{"text":"Cancelable","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MBXCancelable"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/queryRenderedFeatures(with:options:completion:)":{"type":"topic","abstract":[{"text":"Queries the map for rendered features.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"queryRenderedFeatures"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"text":": some ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps32RenderedQueryGeometryConvertibleP","text":"RenderedQueryGeometryConvertible","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RenderedQueryOptions","preciseIdentifier":"c:objc(cs)MBMRenderedQueryOptions"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO","text":"Result"},{"text":"<[","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMQueriedRenderedFeature","text":"QueriedRenderedFeature"},{"kind":"text","text":"], any "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":") -> any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)MBXCancelable","text":"Cancelable","kind":"typeIdentifier"}],"url":"\/documentation\/mapboxmaps\/mapboxmap\/queryrenderedfeatures(with:options:completion:)","title":"queryRenderedFeatures(with:options:completion:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/queryRenderedFeatures(with:options:completion:)","role":"symbol","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","role":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapboxMap"}],"navigatorTitle":[{"text":"MapboxMap","kind":"identifier"}],"title":"MapboxMap","type":"topic","abstract":[{"text":"Provides access to the map model, including the camera, style, observable map events,","type":"text"},{"text":" ","type":"text"},{"text":"and querying rendered features.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/querySourceFeatures(for:options:completion:)":{"url":"\/documentation\/mapboxmaps\/mapboxmap\/querysourcefeatures(for:options:completion:)","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/querySourceFeatures(for:options:completion:)","role":"symbol","title":"querySourceFeatures(for:options:completion:)","abstract":[{"text":"Queries the map for source features.","type":"text"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"querySourceFeatures"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SourceQueryOptions","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMSourceQueryOptions"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"text":"<[","kind":"text"},{"text":"QueriedSourceFeature","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMQueriedSourceFeature"},{"kind":"text","text":"], any "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":">) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":") -> any ","kind":"text"},{"text":"Cancelable","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MBXCancelable"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MBXCancelable","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/fragments","value":[{"text":"MBXCancelable","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/navigatorTitle","value":[{"text":"MBXCancelable","kind":"identifier"}]},{"value":"MBMQueriedRenderedFeature","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedRenderedFeature\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedRenderedFeature\/fragments","op":"replace","value":[{"text":"MBMQueriedRenderedFeature","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"MBMQueriedRenderedFeature"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedRenderedFeature\/navigatorTitle"}]}]}