{"kind":"article","metadata":{"role":"collectionGroup","roleHeading":"API Collection","title":"Offline Support","modules":[{"name":"MapboxMaps"}]},"topicSections":[{"title":"Offline","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineManager"],"anchor":"Offline"},{"title":"Deprecated","anchor":"Deprecated","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegion","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionGeometryDefinition","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionManager","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionTilePyramidDefinition","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionStatus","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadProgressCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionDownloadState","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionErrorType"]},{"anchor":"Control-network","title":"Control network","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineSwitch"]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionError":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionError","url":"\/documentation\/mapboxmaps\/offlineregionerror","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OfflineRegionError"}],"kind":"symbol","abstract":[{"text":"Describes an offline request response error.","type":"text"}],"navigatorTitle":[{"text":"OfflineRegionError","kind":"identifier"}],"title":"OfflineRegionError","role":"symbol","deprecated":true,"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","abstract":[],"title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","kind":"article","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionDownloadState":{"url":"\/documentation\/mapboxmaps\/offlineregiondownloadstate","abstract":[{"text":"Describes the download state of a region.","type":"text"}],"navigatorTitle":[{"text":"OfflineRegionDownloadState","kind":"identifier"}],"deprecated":true,"role":"symbol","title":"OfflineRegionDownloadState","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"OfflineRegionDownloadState","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionDownloadState"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","title":"MapboxMaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"role":"collection","url":"\/documentation\/mapboxmaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionErrorType":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OfflineRegionErrorType"}],"type":"topic","title":"OfflineRegionErrorType","kind":"symbol","deprecated":true,"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"OfflineRegionErrorType","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/offlineregionerrortype","abstract":[{"text":"Describes the reason for an offline request response error.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionErrorType"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePackLoadProgressCallback":{"navigatorTitle":[{"kind":"identifier","text":"StylePackLoadProgressCallback"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadProgressCallback","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StylePackLoadProgressCallback","kind":"identifier"}],"type":"topic","title":"StylePackLoadProgressCallback","url":"\/documentation\/mapboxmaps\/stylepackloadprogresscallback","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Callback Invoked to report the progess of the style package loading operation."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionStatus":{"abstract":[{"type":"text","text":"A region’s status includes its active\/inactive state as well as counts"},{"type":"text","text":" "},{"text":"of the number of resources that have completed downloading, their total","type":"text"},{"text":" ","type":"text"},{"text":"size in bytes, and the total number of resources that are required.","type":"text"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/offlineregionstatus","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OfflineRegionStatus"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionStatus","type":"topic","title":"OfflineRegionStatus","navigatorTitle":[{"kind":"identifier","text":"OfflineRegionStatus"}],"deprecated":true},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegion":{"type":"topic","abstract":[{"type":"text","text":"An offline region represents an identifiable geographic region with optional metadata."}],"role":"symbol","title":"OfflineRegion","kind":"symbol","navigatorTitle":[{"text":"OfflineRegion","kind":"identifier"}],"deprecated":true,"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"OfflineRegion","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/offlineregion","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegion"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineManager":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineManager","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"OfflineManager","kind":"identifier"}],"title":"OfflineManager","role":"symbol","navigatorTitle":[{"text":"OfflineManager","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxmaps\/offlinemanager","abstract":[{"text":"An ","type":"text"},{"type":"codeVoice","code":"offline manager"},{"text":" manages downloads and storage for style packages and also produces tileset descriptors for the ","type":"text"},{"type":"codeVoice","code":"tile store"},{"type":"text","text":"."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionTilePyramidDefinition":{"url":"\/documentation\/mapboxmaps\/offlineregiontilepyramiddefinition","abstract":[{"text":"An offline region definition is a geographic region defined by a style URL,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"geographic bounding box, zoom range, and device pixel ratio. Both "},{"code":"minZoom","type":"codeVoice"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"maxZoom"},{"type":"text","text":" must be ≥ 0,"},{"text":" ","type":"text"},{"text":"and ","type":"text"},{"type":"codeVoice","code":"maxZoom"},{"text":" must be ≥ ","type":"text"},{"type":"codeVoice","code":"minZoom"},{"text":". The ","type":"text"},{"type":"codeVoice","code":"maxZoom"},{"type":"text","text":" may be ∞, in which case for each tile source,"},{"text":" ","type":"text"},{"text":"the region will include tiles from ","type":"text"},{"type":"codeVoice","code":"minZoom"},{"type":"text","text":" up to the maximum zoom level provided by that source."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"pixelRatio"},{"text":" must be ≥ 0 and should typically be 1.0 or 2.0.","type":"text"}],"navigatorTitle":[{"text":"OfflineRegionTilePyramidDefinition","kind":"identifier"}],"deprecated":true,"role":"symbol","title":"OfflineRegionTilePyramidDefinition","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OfflineRegionTilePyramidDefinition"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionTilePyramidDefinition"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineSwitch":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineSwitch","title":"OfflineSwitch","navigatorTitle":[{"kind":"identifier","text":"OfflineSwitch"}],"url":"\/documentation\/mapboxmaps\/offlineswitch","abstract":[{"text":"Instance that allows connecting or disconnecting the Mapbox stack to the network.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OfflineSwitch"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionGeometryDefinition":{"title":"OfflineRegionGeometryDefinition","deprecated":true,"abstract":[{"type":"text","text":"An offline region definition is a geographic region defined by a style URL,"},{"type":"text","text":" "},{"type":"text","text":"a geometry, zoom range, and device pixel ratio. Both "},{"code":"minZoom","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"maxZoom","type":"codeVoice"},{"type":"text","text":" must be ≥ 0,"},{"type":"text","text":" "},{"text":"and ","type":"text"},{"code":"maxZoom","type":"codeVoice"},{"type":"text","text":" must be ≥ "},{"type":"codeVoice","code":"minZoom"},{"text":". The ","type":"text"},{"type":"codeVoice","code":"maxZoom"},{"text":" may be ∞, in which case for each tile source,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"the region will include tiles from "},{"code":"minZoom","type":"codeVoice"},{"text":" up to the maximum zoom level provided by that source.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The "},{"type":"codeVoice","code":"pixelRatio"},{"type":"text","text":" must be ≥ 0 and should typically be 1.0 or 2.0."}],"type":"topic","url":"\/documentation\/mapboxmaps\/offlineregiongeometrydefinition","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionGeometryDefinition","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OfflineRegionGeometryDefinition"}],"navigatorTitle":[{"text":"OfflineRegionGeometryDefinition","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionManager":{"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"offline region manager"},{"type":"text","text":" that manages offline packs. All of the class’s instance methods are asynchronous"},{"type":"text","text":" "},{"text":"reflecting the fact that offline resources are stored in a database. The offline manager maintains a canonical","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"collection of offline packs."}],"type":"topic","role":"symbol","title":"OfflineRegionManager","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"OfflineRegionManager"}],"deprecated":true,"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"OfflineRegionManager"}],"url":"\/documentation\/mapboxmaps\/offlineregionmanager","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionManager"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionObserver":{"abstract":[{"type":"text","text":"A region can have a single observer, which gets notified whenever a change"},{"type":"text","text":" "},{"text":"to the region’s status occurs.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionObserver","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"OfflineRegionObserver","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"OfflineRegionObserver"}],"url":"\/documentation\/mapboxmaps\/offlineregionobserver","deprecated":true,"type":"topic","title":"OfflineRegionObserver"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMaps":{"role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","kind":"article","url":"\/documentation\/mapboxmaps\/coremaps","title":"Core Maps API","abstract":[{"text":"Maps rendering SDK also known as GL-Native","type":"text"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionError\/title","value":"MBMOfflineRegionError"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionError\/fragments","value":[{"kind":"identifier","text":"MBMOfflineRegionError"}]},{"value":[{"kind":"identifier","text":"MBMOfflineRegionError"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionError\/navigatorTitle"},{"value":"MBMOfflineRegionDownloadState","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionDownloadState\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionDownloadState\/fragments","value":[{"kind":"identifier","text":"MBMOfflineRegionDownloadState"}]},{"value":[{"text":"MBMOfflineRegionDownloadState","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionDownloadState\/navigatorTitle"},{"op":"replace","value":"MBMOfflineRegionErrorType","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionErrorType\/title"},{"value":[{"text":"MBMOfflineRegionErrorType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionErrorType\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionErrorType\/navigatorTitle","value":[{"text":"MBMOfflineRegionErrorType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadProgressCallback\/title","op":"replace","value":"MBMStylePackLoadProgressCallback"},{"value":[{"kind":"identifier","text":"MBMStylePackLoadProgressCallback"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadProgressCallback\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadProgressCallback\/navigatorTitle","value":[{"kind":"identifier","text":"MBMStylePackLoadProgressCallback"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionStatus\/title","value":"MBMOfflineRegionStatus","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionStatus\/fragments","op":"replace","value":[{"text":"MBMOfflineRegionStatus","kind":"identifier"}]},{"op":"replace","value":[{"text":"MBMOfflineRegionStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionStatus\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegion\/title","value":"MBMOfflineRegion","op":"replace"},{"value":[{"text":"MBMOfflineRegion","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegion\/fragments","op":"replace"},{"value":[{"text":"MBMOfflineRegion","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegion\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineManager\/title","op":"replace","value":"MBMOfflineManager"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineManager\/fragments","value":[{"kind":"identifier","text":"MBMOfflineManager"}],"op":"replace"},{"value":[{"text":"MBMOfflineManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineManager\/navigatorTitle"},{"value":"MBMOfflineRegionTilePyramidDefinition","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionTilePyramidDefinition\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MBMOfflineRegionTilePyramidDefinition"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionTilePyramidDefinition\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionTilePyramidDefinition\/navigatorTitle","op":"replace","value":[{"text":"MBMOfflineRegionTilePyramidDefinition","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionGeometryDefinition\/title","value":"MBMOfflineRegionGeometryDefinition"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionGeometryDefinition\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMOfflineRegionGeometryDefinition"}]},{"value":[{"kind":"identifier","text":"MBMOfflineRegionGeometryDefinition"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionGeometryDefinition\/navigatorTitle","op":"replace"},{"op":"replace","value":"MBMOfflineRegionManager","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionManager\/title"},{"value":[{"kind":"identifier","text":"MBMOfflineRegionManager"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionManager\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionManager\/navigatorTitle","value":[{"text":"MBMOfflineRegionManager","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionObserver\/title","value":"MBMOfflineRegionObserver","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionObserver\/fragments","value":[{"kind":"identifier","text":"MBMOfflineRegionObserver"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionObserver\/navigatorTitle","value":[{"text":"MBMOfflineRegionObserver","kind":"identifier"}]}]}]}