{"abstract":[{"text":"The enumeration defines the source type that provides the requested resource.","type":"text"}],"seeAlsoSections":[{"generated":true,"title":"Event payload","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderModeType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestLoadingMethodType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestPriorityType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestDataSourceType"],"anchor":"Event-payload"}],"metadata":{"externalID":"c:@E@MBMResponseSourceType","title":"ResponseSourceType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ResponseSourceType","kind":"identifier"}],"role":"symbol","symbolKind":"enum","modules":[{"name":"MapboxMaps"}],"navigatorTitle":[{"kind":"identifier","text":"ResponseSourceType"}],"roleHeading":"Enumeration"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events"]]},"topicSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResponseSourceType\/cache","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResponseSourceType\/localFile","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResponseSourceType\/network","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResponseSourceType\/tileStore"],"title":"Enumeration Cases","anchor":"Enumeration-Cases","generated":true},{"anchor":"Initializers","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResponseSourceType\/init(rawValue:)"],"title":"Initializers"},{"title":"Default Implementations","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResponseSourceType\/Equatable-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResponseSourceType\/RawRepresentable-Implementations"],"anchor":"Default-Implementations","generated":true}],"relationshipsSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/s15BitwiseCopyableP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH","doc:\/\/com.mapbox.MapboxMaps\/SY","doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/mapboxmaps\/responsesourcetype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/responsesourcetype"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResponseSourceType"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResponseSourceType","interfaceLanguage":"swift"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestResourceType":{"title":"RequestResourceType","role":"symbol","kind":"symbol","url":"\/documentation\/mapboxmaps\/requestresourcetype","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType","type":"topic","navigatorTitle":[{"text":"RequestResourceType","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"RequestResourceType","kind":"identifier"}],"abstract":[{"text":"The enumeration defines the type of resource requested by the ","type":"text"},{"code":"map","type":"codeVoice"},{"type":"text","text":"."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleDataLoadedType":{"title":"StyleDataLoadedType","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedType","url":"\/documentation\/mapboxmaps\/styledataloadedtype","type":"topic","navigatorTitle":[{"text":"StyleDataLoadedType","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"StyleDataLoadedType","kind":"identifier"}],"abstract":[{"text":"The enumeration defines the type of loaded style data.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResponseSourceType/Equatable-Implementations":{"url":"\/documentation\/mapboxmaps\/responsesourcetype\/equatable-implementations","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResponseSourceType\/Equatable-Implementations","role":"collectionGroup","abstract":[],"kind":"article","type":"topic","title":"Equatable Implementations"},"doc://com.mapbox.MapboxMaps/s15BitwiseCopyableP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s15BitwiseCopyableP","type":"unresolvable","title":"Swift.BitwiseCopyable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestPriorityType":{"role":"symbol","abstract":[{"type":"text","text":"The enumeration defines the priority of a resource request."}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestPriorityType","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RequestPriorityType"}],"url":"\/documentation\/mapboxmaps\/requestprioritytype","kind":"symbol","title":"RequestPriorityType","navigatorTitle":[{"text":"RequestPriorityType","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/SH":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","title":"MapboxMaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"role":"collection","url":"\/documentation\/mapboxmaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResponseSourceType/tileStore":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tileStore"}],"title":"ResponseSourceType.tileStore","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResponseSourceType\/tileStore","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The source of the response is the TileStore."}],"url":"\/documentation\/mapboxmaps\/responsesourcetype\/tilestore","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBMResponseSourceTypeTileStore"}]},"doc://com.mapbox.MapboxMaps/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResponseSourceType/init(rawValue:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"init(rawValue:)","abstract":[],"kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/responsesourcetype\/init(rawvalue:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResponseSourceType\/init(rawValue:)","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResponseSourceType/localFile":{"url":"\/documentation\/mapboxmaps\/responsesourcetype\/localfile","abstract":[{"text":"The source of the response is the local filesystem. This type is used for","type":"text"},{"type":"text","text":" "},{"text":"responses from the ","type":"text"},{"type":"codeVoice","code":"Asset"},{"type":"text","text":" and "},{"type":"codeVoice","code":"FileSystem"},{"type":"text","text":" data source types."}],"navigatorTitle":[{"text":"MBMResponseSourceTypeLocalFile","kind":"identifier"}],"role":"symbol","title":"ResponseSourceType.localFile","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"localFile","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResponseSourceType\/localFile"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResponseSourceType/cache":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResponseSourceType\/cache","title":"ResponseSourceType.cache","navigatorTitle":[{"text":"MBMResponseSourceTypeCache","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/responsesourcetype\/cache","abstract":[{"text":"The source of the response is a cache (database, in-memory caches).","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cache","kind":"identifier"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoadingErrorType":{"url":"\/documentation\/mapboxmaps\/maploadingerrortype","kind":"symbol","title":"MapLoadingErrorType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapLoadingErrorType"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorType","navigatorTitle":[{"text":"MapLoadingErrorType","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"text":"The enumeration defines map loading errors.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestDataSourceType":{"title":"RequestDataSourceType","role":"symbol","navigatorTitle":[{"text":"RequestDataSourceType","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxmaps\/requestdatasourcetype","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"RequestDataSourceType","kind":"identifier"}],"abstract":[{"text":"The enumeration defines the type of data source.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestDataSourceType"},"doc://com.mapbox.MapboxMaps/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SY"},"doc://com.mapbox.MapboxMaps/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"url":"\/documentation\/mapboxmaps\/events","type":"topic","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","title":"Map events","abstract":[{"text":"The simplified diagram of the events emitted by the map is displayed below.","type":"text"}],"role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceDataLoadedType":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SourceDataLoadedType","kind":"identifier"}],"navigatorTitle":[{"text":"SourceDataLoadedType","kind":"identifier"}],"abstract":[{"text":"The enumeration defines the type of loaded source data.","type":"text"}],"kind":"symbol","title":"SourceDataLoadedType","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedType","url":"\/documentation\/mapboxmaps\/sourcedataloadedtype"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResponseSourceType":{"navigatorTitle":[{"kind":"identifier","text":"ResponseSourceType"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ResponseSourceType","kind":"identifier"}],"title":"ResponseSourceType","url":"\/documentation\/mapboxmaps\/responsesourcetype","kind":"symbol","abstract":[{"text":"The enumeration defines the source type that provides the requested resource.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResponseSourceType"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResponseSourceType/RawRepresentable-Implementations":{"kind":"article","title":"RawRepresentable Implementations","role":"collectionGroup","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResponseSourceType\/RawRepresentable-Implementations","url":"\/documentation\/mapboxmaps\/responsesourcetype\/rawrepresentable-implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResponseSourceType/network":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"network","kind":"identifier"}],"title":"ResponseSourceType.network","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResponseSourceType\/network","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The source of the response is a network."}],"url":"\/documentation\/mapboxmaps\/responsesourcetype\/network","role":"symbol","navigatorTitle":[{"text":"MBMResponseSourceTypeNetwork","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","abstract":[],"title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","kind":"article","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderModeType":{"title":"RenderModeType","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderModeType","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RenderModeType"}],"navigatorTitle":[{"text":"RenderModeType","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/rendermodetype","kind":"symbol","type":"topic","abstract":[{"text":"The enumeration defines the rendering mode for the rendered frame.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestLoadingMethodType":{"role":"symbol","type":"topic","abstract":[{"text":"The enumeration defines the method used to make a resource request.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestLoadingMethodType","kind":"symbol","navigatorTitle":[{"text":"RequestLoadingMethodType","kind":"identifier"}],"title":"RequestLoadingMethodType","url":"\/documentation\/mapboxmaps\/requestloadingmethodtype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RequestLoadingMethodType","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"value":"MBMResponseSourceType","op":"replace","path":"\/metadata\/title"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"MBMResponseSourceType","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MBMResponseSourceType"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"title":"Enumeration Cases","anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResponseSourceType\/cache","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResponseSourceType\/localFile","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResponseSourceType\/network","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResponseSourceType\/tileStore"]}]},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"op":"replace","value":[{"generated":true,"title":"Event payload","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderModeType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestLoadingMethodType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestPriorityType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestDataSourceType"],"anchor":"Event-payload"}],"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBMResponseSourceType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"value":"MBMRequestResourceType","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestResourceType\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestResourceType\/fragments","op":"replace","value":[{"text":"MBMRequestResourceType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestResourceType\/navigatorTitle","value":[{"kind":"identifier","text":"MBMRequestResourceType"}]},{"value":"MBMStyleDataLoadedType","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedType\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedType\/fragments","value":[{"text":"MBMStyleDataLoadedType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedType\/navigatorTitle","op":"replace","value":[{"text":"MBMStyleDataLoadedType","kind":"identifier"}]},{"value":"MBMRequestPriorityType","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestPriorityType\/title"},{"op":"replace","value":[{"text":"MBMRequestPriorityType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestPriorityType\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestPriorityType\/navigatorTitle","value":[{"text":"MBMRequestPriorityType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResponseSourceType~1tileStore\/title","value":"MBMResponseSourceTypeTileStore","op":"replace"},{"value":[{"kind":"identifier","text":"MBMResponseSourceTypeTileStore"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResponseSourceType~1tileStore\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResponseSourceType~1localFile\/title","op":"replace","value":"MBMResponseSourceTypeLocalFile"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResponseSourceType~1localFile\/fragments","value":[{"kind":"identifier","text":"MBMResponseSourceTypeLocalFile"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResponseSourceType~1cache\/title","value":"MBMResponseSourceTypeCache","op":"replace"},{"value":[{"text":"MBMResponseSourceTypeCache","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResponseSourceType~1cache\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorType\/title","value":"MBMMapLoadingErrorType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorType\/fragments","value":[{"kind":"identifier","text":"MBMMapLoadingErrorType"}]},{"op":"replace","value":[{"text":"MBMMapLoadingErrorType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorType\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestDataSourceType\/title","value":"MBMRequestDataSourceType"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestDataSourceType\/fragments","value":[{"kind":"identifier","text":"MBMRequestDataSourceType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestDataSourceType\/navigatorTitle","value":[{"text":"MBMRequestDataSourceType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedType\/title","value":"MBMSourceDataLoadedType"},{"op":"replace","value":[{"text":"MBMSourceDataLoadedType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedType\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedType\/navigatorTitle","op":"replace","value":[{"text":"MBMSourceDataLoadedType","kind":"identifier"}]},{"value":"MBMResponseSourceType","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResponseSourceType\/title","op":"replace"},{"value":[{"text":"MBMResponseSourceType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResponseSourceType\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResponseSourceType\/navigatorTitle","value":[{"kind":"identifier","text":"MBMResponseSourceType"}],"op":"replace"},{"value":"MBMResponseSourceTypeNetwork","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResponseSourceType~1network\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResponseSourceType~1network\/fragments","value":[{"kind":"identifier","text":"MBMResponseSourceTypeNetwork"}],"op":"replace"},{"value":"MBMRenderModeType","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderModeType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBMRenderModeType"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderModeType\/fragments"},{"value":[{"kind":"identifier","text":"MBMRenderModeType"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderModeType\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestLoadingMethodType\/title","op":"replace","value":"MBMRequestLoadingMethodType"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestLoadingMethodType\/fragments","value":[{"text":"MBMRequestLoadingMethodType","kind":"identifier"}]},{"value":[{"text":"MBMRequestLoadingMethodType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestLoadingMethodType\/navigatorTitle"}]}]}