{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Vec2","kind":"identifier"}]}]}],"variants":[{"paths":["\/documentation\/mapboxmaps\/vec2"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/vec2"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"title":"Symbols","generated":true,"anchor":"Symbols","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Vec3","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Vec4"]}],"kind":"symbol","metadata":{"modules":[{"name":"MapboxMaps"}],"roleHeading":"Class","title":"Vec2","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Vec2"}],"role":"symbol","externalID":"c:objc(cs)MBMVec2","symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"Vec2"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"topicSections":[{"generated":true,"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Vec2\/init(x:y:)"]},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Vec2\/x","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Vec2\/y"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Vec2\/isEqual(to:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"sections":[],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH"]}],"abstract":[{"type":"text","text":"2 component vector."}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Free-Camera"]]},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Vec2","interfaceLanguage":"swift"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Vec2":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Vec2","type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/vec2","abstract":[{"text":"2 component vector.","type":"text"}],"navigatorTitle":[{"text":"Vec2","kind":"identifier"}],"title":"Vec2","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Vec2","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Vec4":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Vec4","type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/vec4","abstract":[{"text":"4 component vector.","type":"text"}],"navigatorTitle":[{"text":"Vec4","kind":"identifier"}],"title":"Vec4","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Vec4","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Free-Camera":{"type":"topic","role":"collectionGroup","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Free-Camera","title":"Free Camera","abstract":[],"url":"\/documentation\/mapboxmaps\/free-camera"},"doc://com.mapbox.MapboxMaps/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Vec2/init(x:y:)":{"type":"topic","abstract":[],"url":"\/documentation\/mapboxmaps\/vec2\/init(x:y:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"x","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"y"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":")","kind":"text"}],"kind":"symbol","title":"init(x:y:)","navigatorTitle":[{"kind":"identifier","text":"initWithX:y:"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Vec2\/init(x:y:)","role":"symbol"},"doc://com.mapbox.MapboxMaps/objc(cs)NSObject":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/SQ":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMaps":{"role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","kind":"article","url":"\/documentation\/mapboxmaps\/coremaps","title":"Core Maps API","abstract":[{"text":"Maps rendering SDK also known as GL-Native","type":"text"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Vec2/x":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Vec2\/x","abstract":[{"type":"text","text":"The x component of the vector."}],"type":"topic","url":"\/documentation\/mapboxmaps\/vec2\/x","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"x"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"kind":"symbol","title":"x","navigatorTitle":[{"kind":"identifier","text":"x"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","title":"MapboxMaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"role":"collection","url":"\/documentation\/mapboxmaps"},"doc://com.mapbox.MapboxMaps/objc(pl)NSObject":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Vec2/y":{"role":"symbol","kind":"symbol","url":"\/documentation\/mapboxmaps\/vec2\/y","abstract":[{"type":"text","text":"The y component of the vector."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Vec2\/y","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"y","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"y","kind":"identifier"}],"title":"y"},"doc://com.mapbox.MapboxMaps/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Vec2/isEqual(to:)":{"abstract":[],"url":"\/documentation\/mapboxmaps\/vec2\/isequal(to:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Vec2\/isEqual(to:)","navigatorTitle":[{"kind":"identifier","text":"isEqualToVec2:"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MBMVec2","text":"Vec2","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"isEqual(to:)","kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/SH":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","abstract":[],"title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","kind":"article","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Vec3":{"role":"symbol","navigatorTitle":[{"text":"Vec3","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Vec3","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Vec3","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/vec3","title":"Vec3","abstract":[{"type":"text","text":"3 component vector."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"value":"MBMVec2","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MBMVec2","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MBMVec2"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Vec2\/x","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Vec2\/y"],"generated":true},{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Vec2\/init(x:y:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Vec2\/isEqual(to:)"]}]},{"value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"}],"path":"\/relationshipsSections","op":"replace"},{"value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Vec3","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Vec4"],"generated":true,"anchor":"Symbols","title":"Symbols"}],"op":"replace","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBMVec2"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}]},"op":"replace"},{"value":"MBMVec2","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Vec2\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Vec2\/fragments","value":[{"kind":"identifier","text":"MBMVec2"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Vec2\/navigatorTitle","value":[{"kind":"identifier","text":"MBMVec2"}],"op":"replace"},{"value":"MBMVec4","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Vec4\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBMVec4"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Vec4\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Vec4\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMVec4"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Vec2~1init(x:y:)\/title","value":"initWithX:y:","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Vec2~1init(x:y:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithX:y:"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Vec2~1x\/title","value":"x","op":"replace"},{"op":"replace","value":[{"text":"x","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Vec2~1x\/fragments"},{"value":"y","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Vec2~1y\/title","op":"replace"},{"op":"replace","value":[{"text":"y","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Vec2~1y\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Vec2~1isEqual(to:)\/title","value":"isEqualToVec2:"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Vec2~1isEqual(to:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"isEqualToVec2:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Vec3\/title","value":"MBMVec3","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Vec3\/fragments","value":[{"text":"MBMVec3","kind":"identifier"}]},{"value":[{"text":"MBMVec3","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Vec3\/navigatorTitle"}]}]}