{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapEventType"]]},"metadata":{"externalID":"s:10MapboxMaps12MapEventTypeV11sourceAddedACySo09MBMSourceG0CGvpZ","platforms":[],"role":"symbol","title":"sourceAdded","modules":[{"name":"MapboxMaps"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sourceAdded"},{"kind":"text","text":": "},{"text":"MapEventType","preciseIdentifier":"s:10MapboxMaps12MapEventTypeV","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"text":"SourceAdded","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMSourceAdded"},{"text":">","kind":"text"}],"roleHeading":"Type Property","symbolKind":"property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sourceAdded"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps12MapEventTypeV","kind":"typeIdentifier","text":"MapEventType","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapEventType"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMSourceAdded","text":"SourceAdded","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceAdded"},{"text":"> { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/mapeventtype\/sourceadded"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapEventType\/sourceAdded"},"kind":"symbol","abstract":[{"type":"text","text":"The source has been added."}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"kind":"article","role":"collectionGroup","title":"Map events","type":"topic","abstract":[{"text":"The simplified diagram of the events emitted by the map is displayed below.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","url":"\/documentation\/mapboxmaps\/events"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceAdded":{"type":"topic","abstract":[{"text":"The source has been added with ","type":"text"},{"type":"codeVoice","code":"addStyleSource"},{"type":"text","text":" method."}],"navigatorTitle":[{"text":"SourceAdded","kind":"identifier"}],"title":"SourceAdded","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SourceAdded"}],"url":"\/documentation\/mapboxmaps\/sourceadded","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceAdded","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap":{"abstract":[{"type":"text","text":"Provides access to the map model, including the camera, style, observable map events,"},{"type":"text","text":" "},{"type":"text","text":"and querying rendered features."}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MapboxMap","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MapboxMap"}],"title":"MapboxMap","role":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Snapshotter":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Snapshotter","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter","kind":"symbol","url":"\/documentation\/mapboxmaps\/snapshotter","navigatorTitle":[{"kind":"identifier","text":"Snapshotter"}],"abstract":[{"text":"A utility class for capturing styled map snapshots.","type":"text"}],"type":"topic","title":"Snapshotter","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapEventType":{"url":"\/documentation\/mapboxmaps\/mapeventtype","navigatorTitle":[{"kind":"identifier","text":"MapEventType"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapEventType","title":"MapEventType","type":"topic","role":"symbol","abstract":[{"text":"A shim that makes it possible to subscribe to ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","isActive":true},{"type":"text","text":" and "},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter","isActive":true},{"text":" events via the old ","type":"text"},{"type":"codeVoice","code":"onNext"},{"text":" and  ","type":"text"},{"code":"onEvery","type":"codeVoice"},{"type":"text","text":" methods."},{"text":" ","type":"text"},{"text":"It is here to simplify migration from v10 to v11, but will be removed in v12.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"MapEventType","kind":"identifier"}],"deprecated":true,"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapEventType/sourceAdded":{"abstract":[{"type":"text","text":"The source has been added."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"sourceAdded","kind":"identifier"},{"kind":"text","text":": "},{"text":"MapEventType","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps12MapEventTypeV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"SourceAdded","preciseIdentifier":"c:objc(cs)MBMSourceAdded"},{"text":">","kind":"text"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/mapeventtype\/sourceadded","type":"topic","title":"sourceAdded","deprecated":true,"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapEventType\/sourceAdded"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"url":"\/documentation\/overview","role":"collection","type":"topic","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","title":"MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"url":"\/documentation\/mapboxmaps","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"MBMSourceAdded","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAdded\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAdded\/fragments","value":[{"text":"MBMSourceAdded","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAdded\/navigatorTitle","value":[{"text":"MBMSourceAdded","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}