{"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"text":"LocationProvider","kind":"identifier"}],"externalID":"c:objc(pl)MBXLocationProvider","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationProvider","kind":"identifier"}],"symbolKind":"protocol","title":"LocationProvider","modules":[{"name":"MapboxCommon"}],"roleHeading":"Protocol","role":"symbol"},"abstract":[{"type":"text","text":"Location provider that provides locations"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationProvider"}]}],"kind":"declarations"}],"seeAlsoSections":[{"anchor":"Location","title":"Location","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationManager","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck2DConfiguration","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Model","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckBearing","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProviderDelegate","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Coordinate2D","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationExtraKeys","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProviderRequest","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceFactory","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/DeviceLocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Heading","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckRenderingData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/IntervalSettings"]}],"topicSections":[{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider\/addLocationObserver(for:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider\/getLastObservedLocation()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider\/removeLocationObserver(for:)"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","relationshipsSections":[{"type":"inheritedBy","title":"Inherited By","kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/DeviceLocationProvider"]},{"type":"conformingTypes","title":"Conforming Types","kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProvider"]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/locationprovider"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/locationprovider"]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationExtraKeys":{"kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Keys for additional information (extra) in Location."}],"url":"\/documentation\/mapboxcommon\/locationextrakeys","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationExtraKeys","kind":"identifier"}],"navigatorTitle":[{"text":"LocationExtraKeys","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationExtraKeys","title":"LocationExtraKeys"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PermissionStatus":{"navigatorTitle":[{"text":"PermissionStatus","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus","title":"PermissionStatus","url":"\/documentation\/mapboxcommon\/permissionstatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PermissionStatus","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Location permissions granted by user to the app."}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PuckRenderingData":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckRenderingData","url":"\/documentation\/mapboxmaps\/puckrenderingdata","role":"symbol","type":"topic","title":"PuckRenderingData","abstract":[{"type":"text","text":"Represents the interpolated data ready to render the user location puck."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PuckRenderingData","kind":"identifier"}],"navigatorTitle":[{"text":"PuckRenderingData","kind":"identifier"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PuckType":{"url":"\/documentation\/mapboxmaps\/pucktype","kind":"symbol","navigatorTitle":[{"text":"PuckType","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PuckType","kind":"identifier"}],"title":"PuckType","abstract":[{"text":"Represents the different types of pucks","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckType","role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Puck3DConfiguration":{"title":"Puck3DConfiguration","type":"topic","url":"\/documentation\/mapboxmaps\/puck3dconfiguration","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Puck3DConfiguration","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"Puck3DConfiguration","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PuckBearing":{"type":"topic","abstract":[{"text":"Controls how the puck is oriented","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckBearing","navigatorTitle":[{"text":"PuckBearing","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PuckBearing","kind":"identifier"}],"title":"PuckBearing","role":"symbol","url":"\/documentation\/mapboxmaps\/puckbearing"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AppleLocationProvider":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProvider","title":"AppleLocationProvider","url":"\/documentation\/mapboxmaps\/applelocationprovider","role":"symbol","kind":"symbol","type":"topic","abstract":[{"text":"A location provider based on CoreLocation’s ","type":"text"},{"code":"CLLocationManager","type":"codeVoice"},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppleLocationProvider"}],"navigatorTitle":[{"kind":"identifier","text":"AppleLocationProvider"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/DeviceLocationProvider":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DeviceLocationProvider","kind":"identifier"}],"navigatorTitle":[{"text":"DeviceLocationProvider","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/devicelocationprovider","abstract":[{"type":"text","text":"Location provider specialisation that provides real-time locations generated from the device"}],"type":"topic","kind":"symbol","title":"DeviceLocationProvider","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/DeviceLocationProvider","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationServiceObserver":{"title":"LocationServiceObserver","kind":"symbol","type":"topic","url":"\/documentation\/mapboxcommon\/locationserviceobserver","abstract":[{"type":"text","text":"Observers for getting updates from LocationService."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationServiceObserver","kind":"identifier"}],"navigatorTitle":[{"text":"LocationServiceObserver","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationProvider/getLastObservedLocation()":{"abstract":[{"type":"text","text":"Gets the last observed location."}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/mapboxcommon\/locationprovider\/getlastobservedlocation()","title":"getLastObservedLocation()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getLastObservedLocation","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBXLocation","text":"Location","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider\/getLastObservedLocation()","required":true,"navigatorTitle":[{"text":"getLastObservedLocation","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationProviderRequest":{"abstract":[{"type":"text","text":"Data model that contains parameters for location requests."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationProviderRequest"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProviderRequest","url":"\/documentation\/mapboxcommon\/locationproviderrequest","navigatorTitle":[{"kind":"identifier","text":"LocationProviderRequest"}],"role":"symbol","kind":"symbol","type":"topic","title":"LocationProviderRequest"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/AccuracyAuthorization":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AccuracyAuthorization","kind":"identifier"}],"title":"AccuracyAuthorization","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization","navigatorTitle":[{"text":"AccuracyAuthorization","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/mapboxcommon\/accuracyauthorization","abstract":[{"type":"text","text":"Accuracy authorization granted by user to the app."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationProvider/addLocationObserver(for:)":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"addLocationObserverForObserver:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addLocationObserver","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)MBXLocationObserver","text":"LocationObserver","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider\/addLocationObserver(for:)","required":true,"url":"\/documentation\/mapboxcommon\/locationprovider\/addlocationobserver(for:)","abstract":[{"text":"Registers an observer in this instance of LocationProvider.","type":"text"},{"text":" ","type":"text"},{"text":"One instance of LocationProvider can have more than one observer.","type":"text"},{"text":" ","type":"text"},{"text":"It is expected that LocationProvider will not start until an","type":"text"},{"text":" ","type":"text"},{"text":"observer is added.","type":"text"}],"title":"addLocationObserver(for:)","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/IntervalSettings":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/IntervalSettings","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntervalSettings"}],"navigatorTitle":[{"kind":"identifier","text":"IntervalSettings"}],"title":"IntervalSettings","type":"topic","abstract":[{"text":"The interval for active location updates","type":"text"}],"url":"\/documentation\/mapboxcommon\/intervalsettings","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationProvider":{"title":"LocationProvider","url":"\/documentation\/mapboxcommon\/locationprovider","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationProvider","kind":"identifier"}],"abstract":[{"type":"text","text":"Location provider that provides locations"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider","navigatorTitle":[{"text":"LocationProvider","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Puck2DConfiguration":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Puck2DConfiguration","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"Puck2DConfiguration","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck2DConfiguration","type":"topic","title":"Puck2DConfiguration","abstract":[],"url":"\/documentation\/mapboxmaps\/puck2dconfiguration"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Heading":{"type":"topic","title":"Heading","url":"\/documentation\/mapboxmaps\/heading","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Heading","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The azimuth (orientation) of the user’s device, relative to true or magnetic north."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Heading","navigatorTitle":[{"text":"Heading","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationServiceFactory":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceFactory","abstract":[{"text":"Location service factory.","type":"text"}],"role":"symbol","type":"topic","title":"LocationServiceFactory","navigatorTitle":[{"text":"LocationServiceFactory","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/locationservicefactory","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationServiceFactory","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"role":"collection","kind":"symbol","url":"\/documentation\/mapboxmaps","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationErrorCode":{"kind":"symbol","type":"topic","title":"LocationErrorCode","navigatorTitle":[{"text":"LocationErrorCode","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode","abstract":[{"text":"Codes of location errors.","type":"text"}],"role":"symbol","url":"\/documentation\/mapboxcommon\/locationerrorcode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationErrorCode","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LocationOptions":{"role":"symbol","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationOptions","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"LocationOptions","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/locationoptions","abstract":[{"type":"text","text":"A struct to configure a "},{"type":"codeVoice","code":"LocationManager"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationOptions","title":"LocationOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationProvider/removeLocationObserver(for:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeLocationObserver","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)MBXLocationObserver","text":"LocationObserver","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/mapboxcommon\/locationprovider\/removelocationobserver(for:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider\/removeLocationObserver(for:)","type":"topic","title":"removeLocationObserver(for:)","required":true,"role":"symbol","abstract":[{"type":"text","text":"Removes the observer from this instance of LocationProvider. If the observer"},{"type":"text","text":" "},{"type":"text","text":"is not registered, this is no-op."},{"type":"text","text":" "},{"type":"text","text":"It is expected that if there are no observers, the LocationProvider"},{"type":"text","text":" "},{"type":"text","text":"will stop automatically."}],"navigatorTitle":[{"text":"removeLocationObserverForObserver:","kind":"identifier"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Location":{"kind":"symbol","title":"Location","url":"\/documentation\/mapboxcommon\/location","abstract":[{"type":"text","text":"Location information."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Location"}],"navigatorTitle":[{"kind":"identifier","text":"Location"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AppleLocationProviderDelegate":{"url":"\/documentation\/mapboxmaps\/applelocationproviderdelegate","navigatorTitle":[{"text":"AppleLocationProviderDelegate","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProviderDelegate"},{"type":"text","text":" protocol defines a set of optional methods that you"},{"type":"text","text":" "},{"type":"text","text":"can use to receive events from an associated location provider object."}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AppleLocationProviderDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProviderDelegate","role":"symbol","title":"AppleLocationProviderDelegate"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Location-APIs":{"kind":"article","title":"Location","type":"topic","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/location-apis","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationObserver":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationObserver","navigatorTitle":[{"text":"LocationObserver","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationObserver","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Observer for getting updates from a LocationProvider."}],"url":"\/documentation\/mapboxcommon\/locationobserver","title":"LocationObserver"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeadingProvider":{"title":"HeadingProvider","abstract":[{"type":"text","text":"Provides heading data to drive the location puck."}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeadingProvider"}],"navigatorTitle":[{"kind":"identifier","text":"HeadingProvider"}],"url":"\/documentation\/mapboxmaps\/headingprovider","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingProvider","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationError":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationError","role":"symbol","url":"\/documentation\/mapboxcommon\/locationerror","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationError","kind":"identifier"}],"title":"LocationError","type":"topic","abstract":[{"type":"text","text":"Error code with brief explanation."}],"navigatorTitle":[{"text":"LocationError","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/AccuracyLevel":{"title":"AccuracyLevel","url":"\/documentation\/mapboxcommon\/accuracylevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AccuracyLevel"}],"abstract":[{"text":"The accuracy of the observed location","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AccuracyLevel"}],"type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LocationManager":{"abstract":[{"text":"An object responsible for managing user location Puck.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationManager"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocationManager"}],"title":"LocationManager","url":"\/documentation\/mapboxmaps\/locationmanager","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationManager"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","kind":"article","title":"MapboxMaps Documentation","url":"\/documentation\/overview","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeadingObserver":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeadingObserver"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HeadingObserver"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingObserver","type":"topic","title":"HeadingObserver","abstract":[{"type":"text","text":"Listens to "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingProvider","isActive":true,"type":"reference"},{"type":"text","text":"’s updates."}],"url":"\/documentation\/mapboxmaps\/headingobserver"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Model":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Model","url":"\/documentation\/mapboxmaps\/model","role":"symbol","navigatorTitle":[{"text":"Model","kind":"identifier"}],"abstract":[{"text":"A structure represeting a Model","type":"text"}],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Model","kind":"identifier"}],"title":"Model"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Coordinate2D":{"abstract":[{"type":"text","text":"Boxed version of CLLocationCoordinate2D"}],"type":"topic","title":"Coordinate2D","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Coordinate2D","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Coordinate2D"}],"navigatorTitle":[{"kind":"identifier","text":"Coordinate2D"}],"url":"\/documentation\/mapboxcommon\/coordinate2d"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","value":"MBXLocationProvider","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MBXLocationProvider"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"MBXLocationProvider","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider\/addLocationObserver(for:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider\/getLastObservedLocation()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider\/removeLocationObserver(for:)"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/DeviceLocationProvider"],"kind":"relationships","type":"inheritedBy","title":"Inherited By"}],"op":"replace"},{"path":"\/seeAlsoSections","value":[{"anchor":"Location","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Coordinate2D","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationExtraKeys","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProviderRequest","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceFactory","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/DeviceLocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/IntervalSettings"],"generated":true,"title":"Location"}],"op":"replace"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBXLocationProvider","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationExtraKeys\/title","value":"MBXLocationExtraKeys","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationExtraKeys\/fragments","value":[{"text":"MBXLocationExtraKeys","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationExtraKeys\/navigatorTitle","value":[{"text":"MBXLocationExtraKeys","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/title","value":"MBXPermissionStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/fragments","value":[{"text":"MBXPermissionStatus","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/navigatorTitle","value":[{"text":"MBXPermissionStatus","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1DeviceLocationProvider\/title","value":"MBXDeviceLocationProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1DeviceLocationProvider\/fragments","value":[{"kind":"identifier","text":"MBXDeviceLocationProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1DeviceLocationProvider\/navigatorTitle","value":[{"text":"MBXDeviceLocationProvider","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver\/title","value":"MBXLocationServiceObserver"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver\/fragments","value":[{"kind":"identifier","text":"MBXLocationServiceObserver"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver\/navigatorTitle","value":[{"kind":"identifier","text":"MBXLocationServiceObserver"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider~1getLastObservedLocation()\/title","value":"getLastObservedLocation"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider~1getLastObservedLocation()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getLastObservedLocation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProviderRequest\/title","value":"MBXLocationProviderRequest"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProviderRequest\/fragments","value":[{"kind":"identifier","text":"MBXLocationProviderRequest"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProviderRequest\/navigatorTitle","value":[{"text":"MBXLocationProviderRequest","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization\/title","value":"MBXAccuracyAuthorization"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization\/fragments","value":[{"kind":"identifier","text":"MBXAccuracyAuthorization"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization\/navigatorTitle","value":[{"kind":"identifier","text":"MBXAccuracyAuthorization"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider~1addLocationObserver(for:)\/title","value":"addLocationObserverForObserver:"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider~1addLocationObserver(for:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"addLocationObserverForObserver:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1IntervalSettings\/title","value":"MBXIntervalSettings"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1IntervalSettings\/fragments","value":[{"kind":"identifier","text":"MBXIntervalSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1IntervalSettings\/navigatorTitle","value":[{"kind":"identifier","text":"MBXIntervalSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/title","value":"MBXLocationProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/fragments","value":[{"text":"MBXLocationProvider","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/navigatorTitle","value":[{"kind":"identifier","text":"MBXLocationProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceFactory\/title","value":"MBXLocationServiceFactory"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceFactory\/fragments","value":[{"text":"MBXLocationServiceFactory","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceFactory\/navigatorTitle","value":[{"kind":"identifier","text":"MBXLocationServiceFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/title","value":"MBXLocationErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/fragments","value":[{"text":"MBXLocationErrorCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/navigatorTitle","value":[{"kind":"identifier","text":"MBXLocationErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider~1removeLocationObserver(for:)\/title","value":"removeLocationObserverForObserver:"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider~1removeLocationObserver(for:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeLocationObserverForObserver:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/title","value":"MBXLocation"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/fragments","value":[{"text":"MBXLocation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/navigatorTitle","value":[{"kind":"identifier","text":"MBXLocation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/title","value":"MBXLocationObserver"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/fragments","value":[{"kind":"identifier","text":"MBXLocationObserver"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/navigatorTitle","value":[{"kind":"identifier","text":"MBXLocationObserver"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationError\/title","value":"MBXLocationError"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationError\/fragments","value":[{"kind":"identifier","text":"MBXLocationError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationError\/navigatorTitle","value":[{"kind":"identifier","text":"MBXLocationError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel\/title","value":"MBXAccuracyLevel"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel\/fragments","value":[{"kind":"identifier","text":"MBXAccuracyLevel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel\/navigatorTitle","value":[{"text":"MBXAccuracyLevel","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Coordinate2D\/title","value":"MBXCoordinate2D"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Coordinate2D\/fragments","value":[{"kind":"identifier","text":"MBXCoordinate2D"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Coordinate2D\/navigatorTitle","value":[{"text":"MBXCoordinate2D","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}