{"metadata":{"role":"symbol","symbolKind":"func","title":"MBXHttpMethodToString(_:)","navigatorTitle":[{"text":"MBXHttpMethodToString","kind":"identifier"}],"roleHeading":"Function","externalID":"c:@F@MBXHttpMethodToString","modules":[{"name":"MapboxCommon"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBXHttpMethodToString","kind":"identifier"},{"text":"(","kind":"text"},{"text":"HttpMethod","preciseIdentifier":"c:@E@MBXHttpMethod","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"!"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXHttpMethodToString(_:)"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBXHttpMethodToString"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"http_method"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@MBXHttpMethod","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpMethod","text":"HttpMethod"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"!"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/mbxhttpmethodtostring(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/mbxhttpmethodtostring(_:)"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXHttpMethodToString(_:)":{"type":"topic","role":"symbol","title":"MBXHttpMethodToString(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXHttpMethodToString(_:)","navigatorTitle":[{"text":"MBXHttpMethodToString","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/mbxhttpmethodtostring(_:)","kind":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBXHttpMethodToString","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@MBXHttpMethod","text":"HttpMethod","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","url":"\/documentation\/overview","kind":"article","type":"topic","role":"collection","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpMethod":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpMethod","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HttpMethod","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/httpmethod","abstract":[{"type":"text","text":"HTTP defines a set of request methods to indicate the desired action to be performed for a given resource."}],"kind":"symbol","role":"symbol","type":"topic","title":"HttpMethod","navigatorTitle":[{"text":"HttpMethod","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","type":"topic","title":"MapboxCommon","kind":"symbol","abstract":[],"role":"collection","url":"\/documentation\/mapboxcommon"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Function","op":"replace","path":"\/metadata\/roleHeading"},{"value":"MBXHttpMethodToString","op":"replace","path":"\/metadata\/title"},{"value":"func","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"MBXHttpMethodToString","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"MBXHttpMethodToString"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpMethod","preciseIdentifier":"c:@E@MBXHttpMethod","text":"MBXHttpMethod"},{"kind":"text","text":" "},{"kind":"internalParam","text":"http_method"},{"kind":"text","text":");"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MBXHttpMethodToString","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MBXHttpMethodToString(_:)\/title"},{"value":[{"text":"MBXHttpMethodToString","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MBXHttpMethodToString(_:)\/fragments"},{"value":"MBXHttpMethod","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpMethod\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpMethod\/fragments","value":[{"text":"MBXHttpMethod","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpMethod\/navigatorTitle","value":[{"text":"MBXHttpMethod","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}