{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"MBMMapDebugOptionsTimestamps"}],"symbolKind":"case","role":"symbol","title":"MapDebugOptions.timestamps","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"timestamps","kind":"identifier"}],"modules":[{"name":"MapboxMaps"}],"externalID":"c:@E@MBMMapDebugOptions@MBMMapDebugOptionsTimestamps"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"timestamps","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/mapdebugoptions\/timestamps"]},{"paths":["\/documentation\/mapboxmaps\/mapdebugoptions\/timestamps"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions"]]},"abstract":[{"type":"text","text":"Each tile shows a timestamps with modified and expires dates or n\/a if"},{"type":"text","text":" "},{"type":"text","text":"timestamp is not available."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/timestamps"},"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","abstract":[],"kind":"article","role":"collection","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Performance":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","type":"topic","url":"\/documentation\/mapboxmaps\/performance","title":"Performance and investigations","kind":"article","role":"collectionGroup","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapDebugOptions/timestamps":{"title":"MapDebugOptions.timestamps","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"timestamps"}],"url":"\/documentation\/mapboxmaps\/mapdebugoptions\/timestamps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/timestamps","abstract":[{"text":"Each tile shows a timestamps with modified and expires dates or n\/a if","type":"text"},{"text":" ","type":"text"},{"text":"timestamp is not available.","type":"text"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MBMMapDebugOptionsTimestamps"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapDebugOptions":{"type":"topic","title":"MapDebugOptions","role":"symbol","url":"\/documentation\/mapboxmaps\/mapdebugoptions","abstract":[{"text":"Options for enabling debugging features in a map.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MapDebugOptions"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapDebugOptions"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"value":"MBMMapDebugOptionsTimestamps","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"MBMMapDebugOptionsTimestamps","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"MBMMapDebugOptionsTimestamps","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"MBMMapDebugOptionsTimestamps","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions~1timestamps\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions~1timestamps\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMMapDebugOptionsTimestamps"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions\/title","value":"MBMMapDebugOptions"},{"op":"replace","value":[{"kind":"identifier","text":"MBMMapDebugOptions"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MBMMapDebugOptions"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions\/navigatorTitle"}]}]}