{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GeometryType_MultiLine"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@EA@MBXGeometryType","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType","kind":"typeIdentifier","text":"GeometryType"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon"],["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TurfAPI","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"modules":[{"name":"MapboxCommon"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GeometryType_MultiLine"},{"kind":"text","text":": "},{"text":"GeometryType","kind":"typeIdentifier","preciseIdentifier":"c:@EA@MBXGeometryType"}],"externalID":"c:@EA@MBXGeometryType@MBXGeometryType_MultiLine","role":"symbol","roleHeading":"Global Variable","navigatorTitle":[{"kind":"identifier","text":"MBXGeometryType_MultiLine"}],"title":"GeometryType_MultiLine","symbolKind":"var"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/geometrytype_multiline"]},{"paths":["\/documentation\/mapboxcommon\/geometrytype_multiline"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType_MultiLine"},"kind":"symbol","references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","kind":"article","url":"\/documentation\/overview","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"abstract":[],"kind":"symbol","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","title":"MapboxCommon","type":"topic","url":"\/documentation\/mapboxcommon"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/GeometryType_MultiLine":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GeometryType_MultiLine","kind":"identifier"},{"kind":"text","text":": "},{"text":"GeometryType","kind":"typeIdentifier","preciseIdentifier":"c:@EA@MBXGeometryType"}],"kind":"symbol","role":"symbol","url":"\/documentation\/mapboxcommon\/geometrytype_multiline","type":"topic","title":"GeometryType_MultiLine","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"MBXGeometryType_MultiLine"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType_MultiLine"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/GeometryType":{"kind":"symbol","type":"topic","url":"\/documentation\/mapboxcommon\/geometrytype","role":"symbol","title":"GeometryType","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GeometryType","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"GeometryType"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TurfAPI":{"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TurfAPI","abstract":[{"text":"Describes ","type":"text"},{"code":"turf-swift","type":"codeVoice"},{"text":" dependency objects","type":"text"}],"title":"Turf","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/turfapi","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"url":"\/documentation\/mapboxmaps","kind":"symbol","title":"MapboxMaps","role":"collection","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"MBXGeometryType_MultiLine","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"text":"MBXGeometryType_MultiLine","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"MBXGeometryType_MultiLine","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType_MultiLine\/title","value":"MBXGeometryType_MultiLine"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType_MultiLine\/fragments","op":"replace","value":[{"text":"MBXGeometryType_MultiLine","kind":"identifier"}]},{"op":"replace","value":"MBXGeometryType","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType\/fragments","op":"replace","value":[{"kind":"identifier","text":""}]},{"value":[{"text":"MBXGeometryType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType\/navigatorTitle","op":"replace"}]}]}