{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStoreOptions"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStoreOptions\/tileURLTemplate"},"abstract":[{"text":"Sets the URL template for making tile requests. Defaults to the Mapbox API endpoints.","type":"text"},{"type":"text","text":" "},{"text":"Accepts a string, or null for resetting to the default value.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"tileURLTemplate"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"! { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The template string for the URL, which may contain the following placeholders:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"{mapbox_api_url}: The globally set Mapbox API URL, or the default endpoint if none is set."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"{mapbox_access_token}: The access token, or an empty string if none is set."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"{mapbox_sku_token}: The Mapbox SKU token for the tile."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"{domain}: A lowercase string representing the data domain, e.g. ‘maps’, or ‘navigation’.","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"{dataset}: The dataset of the tile to be loaded, e.g. ‘mapbox.mapbox-streets-v8’."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"{version}: The dataset version of the tile to be loaded, if applicable."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"{level}: The level of the Navigation tile to be loaded."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"{graph_id}: The graph ID suffix of the Navigation tile to be loaded. E.g. ‘002\/958\/221’"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"{z}: The zoom level of the Map tile to be loaded."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"{x}: The x coordinate of the Map tile to be loaded."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"{y}: The y coordinate of the Map tile to be loaded.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"{z_min}: The zoom range minimum of the Map tile to be loaded."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"{z_max}: The zoom range maximum of the Map tile to be loaded.","type":"text"}]}]}]}],"kind":"content"}],"metadata":{"title":"tileURLTemplate","modules":[{"name":"MapboxCommon"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tileURLTemplate"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"!"}],"externalID":"c:objc(cs)MBXTileStoreOptions(cpy)TileURLTemplate","roleHeading":"Type Property","navigatorTitle":[{"text":"TileURLTemplate","kind":"identifier"}],"symbolKind":"property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/tilestoreoptions\/tileurltemplate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/tilestoreoptions\/tileurltemplate"]}],"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileStoreOptions/tileURLTemplate":{"abstract":[{"text":"Sets the URL template for making tile requests. Defaults to the Mapbox API endpoints.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Accepts a string, or null for resetting to the default value."}],"navigatorTitle":[{"text":"TileURLTemplate","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxcommon\/tilestoreoptions\/tileurltemplate","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStoreOptions\/tileURLTemplate","title":"tileURLTemplate","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"tileURLTemplate","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"url":"\/documentation\/mapboxmaps","kind":"symbol","title":"MapboxMaps","role":"collection","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileStoreOptions":{"url":"\/documentation\/mapboxcommon\/tilestoreoptions","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TileStoreOptions"}],"navigatorTitle":[{"text":"TileStoreOptions","kind":"identifier"}],"abstract":[{"text":"These constants can be used as keys for TileStore::setOption to configure further aspects of a TileStore instance.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStoreOptions","role":"symbol","kind":"symbol","title":"TileStoreOptions","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","kind":"article","url":"\/documentation\/overview","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"type":"topic","kind":"article","abstract":[],"title":"TileStore APIs","url":"\/documentation\/mapboxmaps\/tilestore-apis","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","role":"collectionGroup"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Property","op":"replace"},{"path":"\/metadata\/title","value":"TileURLTemplate","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"TileURLTemplate","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"TileURLTemplate"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStoreOptions~1tileURLTemplate\/title","value":"TileURLTemplate","op":"replace"},{"value":[{"text":"TileURLTemplate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStoreOptions~1tileURLTemplate\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStoreOptions\/title","value":"MBXTileStoreOptions","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBXTileStoreOptions"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStoreOptions\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MBXTileStoreOptions"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStoreOptions\/navigatorTitle"}]}]}