{"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onStyleDataLoaded","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"action"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"keyword"},{"kind":"text","text":" ("},{"text":"StyleDataLoaded","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoaded","preciseIdentifier":"c:objc(cs)MBMStyleDataLoaded"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Map","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map","preciseIdentifier":"s:10MapboxMaps3MapV"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onStyleDataLoaded(action:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Adds an action to perform when the requested style data is loaded."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/map\/onstyledataloaded(action:)"]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SwiftUI","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map"]]},"metadata":{"roleHeading":"Instance Method","externalID":"s:10MapboxMaps3MapV17onStyleDataLoaded6actionACySo08MBMStylefG0Cc_tF","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onStyleDataLoaded","kind":"identifier"},{"kind":"text","text":"("},{"text":"action","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"StyleDataLoaded","preciseIdentifier":"c:objc(cs)MBMStyleDataLoaded","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps3MapV","text":"Map"}],"title":"onStyleDataLoaded(action:)","modules":[{"name":"MapboxMaps"}],"role":"symbol","symbolKind":"method","extendedModule":"MapboxMaps"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SwiftUI":{"title":"SwiftUI","type":"topic","url":"\/documentation\/mapboxmaps\/swiftui","role":"collectionGroup","abstract":[],"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SwiftUI"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","title":"MapboxMaps","role":"collection","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/onStyleDataLoaded(action:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onStyleDataLoaded","kind":"identifier"},{"text":"(","kind":"text"},{"text":"action","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMStyleDataLoaded","text":"StyleDataLoaded","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Map","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps3MapV"}],"kind":"symbol","abstract":[{"type":"text","text":"Adds an action to perform when the requested style data is loaded."}],"title":"onStyleDataLoaded(action:)","url":"\/documentation\/mapboxmaps\/map\/onstyledataloaded(action:)","role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onStyleDataLoaded(action:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map":{"url":"\/documentation\/mapboxmaps\/map","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"Map","kind":"identifier"}],"title":"Map","type":"topic","abstract":[{"type":"text","text":"A SwiftUI view that displays a Mapbox Map."}],"role":"symbol","navigatorTitle":[{"text":"Map","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleDataLoaded":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoaded","url":"\/documentation\/mapboxmaps\/styledataloaded","role":"symbol","kind":"symbol","title":"StyleDataLoaded","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StyleDataLoaded"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"StyleDataLoaded","kind":"identifier"}],"abstract":[{"text":"The style data has been loaded. The event will be emitted once for each ","type":"text"},{"code":"StyleDataLoadedType","type":"codeVoice"},{"text":" ","type":"text"},{"text":"type during style loading. If a new style is set, events will be emitted again for the newly set style.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article","role":"collection","abstract":[],"type":"topic","title":"MapboxMaps Documentation"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MBMStyleDataLoaded","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoaded\/title","op":"replace"},{"op":"replace","value":[{"text":"MBMStyleDataLoaded","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoaded\/fragments"},{"value":[{"text":"MBMStyleDataLoaded","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoaded\/navigatorTitle"}]}]}