{"variants":[{"paths":["\/documentation\/mapboxmaps\/mbmrequestinfo\/loadingmethod"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"The loading methods for the resource request."}],"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestInfo\/loadingMethod"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<NSNumber *>"},{"kind":"text","text":" * "},{"text":"loadingMethod","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"loadingMethod"}],"symbolKind":"property","role":"symbol","title":"loadingMethod","externalID":"c:objc(cs)MBMRequestInfo(py)loadingMethod","fragments":[{"text":"loadingMethod","kind":"identifier"}],"roleHeading":"Instance Property","modules":[{"name":"MapboxMaps"}]},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestInfo"]]},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"title":"Map events","role":"collectionGroup","kind":"article","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","url":"\/documentation\/mapboxmaps\/events","abstract":[{"text":"The simplified diagram of the events emitted by the map is displayed below.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","type":"topic","title":"MapboxMaps Documentation","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","title":"MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","role":"collection","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRequestInfo/loadingMethod":{"title":"loadingMethod","kind":"symbol","abstract":[{"type":"text","text":"The loading methods for the resource request."}],"url":"\/documentation\/mapboxmaps\/mbmrequestinfo\/loadingmethod","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestInfo\/loadingMethod","type":"topic","fragments":[{"text":"loadingMethod","kind":"identifier"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestInfo":{"navigatorTitle":[{"text":"RequestInfo","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RequestInfo","kind":"identifier"}],"title":"RequestInfo","abstract":[{"type":"text","text":"The structure defines the information about the resource request."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestInfo","kind":"symbol","url":"\/documentation\/mapboxmaps\/requestinfo","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestInfo\/title","value":"MBMRequestInfo","op":"replace"},{"value":[{"kind":"identifier","text":"MBMRequestInfo"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestInfo\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBMRequestInfo"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestInfo\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}