{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedFeature"]]},"kind":"symbol","abstract":[{"type":"text","text":"Feature returned by the query."}],"metadata":{"modules":[{"name":"MapboxMaps"}],"symbolKind":"property","externalID":"c:objc(cs)MBMQueriedFeature(py)feature","fragments":[{"text":"feature","kind":"identifier"}],"navigatorTitle":[{"text":"feature","kind":"identifier"}],"roleHeading":"Instance Property","title":"feature","role":"symbol"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/mbmqueriedfeature\/feature"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBXFeature","text":"MBXFeature","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Feature"},{"kind":"text","text":" * "},{"kind":"identifier","text":"feature"},{"kind":"text","text":";"}],"languages":["occ"]}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMQueriedFeature\/feature"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMQueriedFeature/feature":{"url":"\/documentation\/mapboxmaps\/mbmqueriedfeature\/feature","kind":"symbol","fragments":[{"kind":"identifier","text":"feature"}],"title":"feature","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMQueriedFeature\/feature","role":"symbol","abstract":[{"type":"text","text":"Feature returned by the query."}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"kind":"article","abstract":[],"url":"\/documentation\/mapboxmaps\/mapboxmap-apis","type":"topic","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","title":"MapboxMap"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","kind":"article","title":"MapboxMaps Documentation","abstract":[],"role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Feature":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Feature","title":"Feature","abstract":[],"url":"\/documentation\/mapboxcommon\/feature","navigatorTitle":[{"text":"Feature","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Feature","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/QueriedFeature":{"url":"\/documentation\/mapboxmaps\/queriedfeature","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedFeature","title":"QueriedFeature","abstract":[{"type":"text","text":"Represents queried feature that is returned through "},{"type":"codeVoice","code":"QueriedRenderedFeature"},{"text":" or ","type":"text"},{"type":"codeVoice","code":"QueriedSourceFeature"}],"kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"QueriedFeature","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"QueriedFeature","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"MBXFeature","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Feature\/title"},{"op":"replace","value":[{"text":"MBXFeature","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Feature\/fragments"},{"value":[{"kind":"identifier","text":"MBXFeature"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Feature\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedFeature\/title","value":"MBMQueriedFeature"},{"value":[{"text":"MBMQueriedFeature","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedFeature\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedFeature\/navigatorTitle","value":[{"text":"MBMQueriedFeature","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}