{"sections":[],"variants":[{"paths":["\/documentation\/mapboxmaps\/mapeventtype\/maploaded"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapEventType"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapEventType\/mapLoaded"},"abstract":[{"type":"text","text":"The style has been fully loaded, and the map has rendered all visible tiles."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mapLoaded"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapEventType","text":"MapEventType","preciseIdentifier":"s:10MapboxMaps12MapEventTypeV"},{"kind":"text","text":"<"},{"text":"MapLoaded","preciseIdentifier":"c:objc(cs)MBMMapLoaded","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoaded"},{"kind":"text","text":"> { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"mapLoaded","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MapEventType","preciseIdentifier":"s:10MapboxMaps12MapEventTypeV"},{"text":"<","kind":"text"},{"text":"MapLoaded","preciseIdentifier":"c:objc(cs)MBMMapLoaded","kind":"typeIdentifier"},{"kind":"text","text":">"}],"externalID":"s:10MapboxMaps12MapEventTypeV9mapLoadedACySo06MBMMapG0CGvpZ","platforms":[],"title":"mapLoaded","symbolKind":"property","role":"symbol","modules":[{"name":"MapboxMaps"}],"roleHeading":"Type Property"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap":{"url":"\/documentation\/mapboxmaps\/mapboxmap","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MapboxMap","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MapboxMap"}],"type":"topic","abstract":[{"type":"text","text":"Provides access to the map model, including the camera, style, observable map events,"},{"type":"text","text":" "},{"type":"text","text":"and querying rendered features."}],"title":"MapboxMap","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"title":"Map events","role":"collectionGroup","kind":"article","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","url":"\/documentation\/mapboxmaps\/events","abstract":[{"text":"The simplified diagram of the events emitted by the map is displayed below.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapEventType/mapLoaded":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mapLoaded","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MapEventType","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps12MapEventTypeV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMMapLoaded","text":"MapLoaded"},{"kind":"text","text":">"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapEventType\/mapLoaded","abstract":[{"type":"text","text":"The style has been fully loaded, and the map has rendered all visible tiles."}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/mapeventtype\/maploaded","type":"topic","title":"mapLoaded","role":"symbol","deprecated":true},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","title":"MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","role":"collection","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","type":"topic","title":"MapboxMaps Documentation","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Snapshotter":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Snapshotter","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/snapshotter","abstract":[{"type":"text","text":"A utility class for capturing styled map snapshots."}],"title":"Snapshotter","navigatorTitle":[{"kind":"identifier","text":"Snapshotter"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoaded":{"abstract":[{"type":"text","text":"The style has been fully loaded, and the "},{"type":"codeVoice","code":"map"},{"text":" has rendered all visible tiles.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The event will be emitted only once for the current style. If it is required to"},{"text":" ","type":"text"},{"text":"observe an event where all required resources are loaded or rendered, please","type":"text"},{"type":"text","text":" "},{"type":"text","text":"check the following events: "},{"code":"MapIdle","type":"codeVoice"},{"text":", ","type":"text"},{"type":"codeVoice","code":"StyleDataLoaded"},{"type":"text","text":", and "},{"type":"codeVoice","code":"RenderFrameFinished"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoaded","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapLoaded","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MapLoaded"}],"title":"MapLoaded","url":"\/documentation\/mapboxmaps\/maploaded","kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapEventType":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapEventType","title":"MapEventType","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapEventType"}],"navigatorTitle":[{"kind":"identifier","text":"MapEventType"}],"deprecated":true,"abstract":[{"text":"A shim that makes it possible to subscribe to ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","isActive":true,"type":"reference"},{"type":"text","text":" and "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter"},{"type":"text","text":" events via the old "},{"code":"onNext","type":"codeVoice"},{"text":" and  ","type":"text"},{"code":"onEvery","type":"codeVoice"},{"type":"text","text":" methods."},{"text":" ","type":"text"},{"text":"It is here to simplify migration from v10 to v11, but will be removed in v12.","type":"text"}],"url":"\/documentation\/mapboxmaps\/mapeventtype","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoaded\/title","op":"replace","value":"MBMMapLoaded"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoaded\/fragments","value":[{"kind":"identifier","text":"MBMMapLoaded"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoaded\/navigatorTitle","op":"replace","value":[{"text":"MBMMapLoaded","kind":"identifier"}]}]}]}