{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapEventType\/styleImageMissing"},"metadata":{"role":"symbol","symbolKind":"property","title":"styleImageMissing","modules":[{"name":"MapboxMaps"}],"externalID":"s:10MapboxMaps12MapEventTypeV17styleImageMissingACySo08MBMStylegH0CGvpZ","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"styleImageMissing","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MapEventType","preciseIdentifier":"s:10MapboxMaps12MapEventTypeV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMStyleImageMissing","text":"StyleImageMissing"},{"kind":"text","text":">"}],"roleHeading":"Type Property","platforms":[]},"abstract":[{"type":"text","text":"A style has a missing image."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"styleImageMissing"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10MapboxMaps12MapEventTypeV","text":"MapEventType","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapEventType"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageMissing","preciseIdentifier":"c:objc(cs)MBMStyleImageMissing","text":"StyleImageMissing"},{"text":"> { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapEventType"]]},"variants":[{"paths":["\/documentation\/mapboxmaps\/mapeventtype\/styleimagemissing"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"url":"\/documentation\/mapboxmaps\/events","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","type":"topic","title":"Map events","abstract":[{"text":"The simplified diagram of the events emitted by the map is displayed below.","type":"text"}],"role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Snapshotter":{"role":"symbol","url":"\/documentation\/mapboxmaps\/snapshotter","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Snapshotter"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Snapshotter"}],"type":"topic","abstract":[{"text":"A utility class for capturing styled map snapshots.","type":"text"}],"title":"Snapshotter"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/mapboxmaps","title":"MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleImageMissing":{"abstract":[{"text":"A style needs an image that is missing from the sprite sheet. This event is","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"emitted when the "},{"type":"codeVoice","code":"map"},{"text":" renders visible tiles, and one of the required images","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"is missing in the sprite sheet. The event observer has to provide the missing"},{"text":" ","type":"text"},{"text":"image by calling the ","type":"text"},{"code":"addStyleImage","type":"codeVoice"},{"text":" method.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"StyleImageMissing"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageMissing","kind":"symbol","title":"StyleImageMissing","url":"\/documentation\/mapboxmaps\/styleimagemissing","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"StyleImageMissing","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap":{"title":"MapboxMap","navigatorTitle":[{"text":"MapboxMap","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapboxMap"}],"url":"\/documentation\/mapboxmaps\/mapboxmap","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","abstract":[{"text":"Provides access to the map model, including the camera, style, observable map events,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"and querying rendered features."}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","abstract":[],"kind":"article","role":"collection","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapEventType":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapEventType","abstract":[{"type":"text","text":"A shim that makes it possible to subscribe to "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap"},{"type":"text","text":" and "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter","isActive":true,"type":"reference"},{"type":"text","text":" events via the old "},{"code":"onNext","type":"codeVoice"},{"type":"text","text":" and  "},{"code":"onEvery","type":"codeVoice"},{"type":"text","text":" methods."},{"text":" ","type":"text"},{"type":"text","text":"It is here to simplify migration from v10 to v11, but will be removed in v12."}],"deprecated":true,"role":"symbol","navigatorTitle":[{"text":"MapEventType","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapEventType"}],"type":"topic","title":"MapEventType","url":"\/documentation\/mapboxmaps\/mapeventtype"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapEventType/styleImageMissing":{"title":"styleImageMissing","kind":"symbol","url":"\/documentation\/mapboxmaps\/mapeventtype\/styleimagemissing","type":"topic","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"styleImageMissing","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps12MapEventTypeV","text":"MapEventType"},{"kind":"text","text":"<"},{"text":"StyleImageMissing","preciseIdentifier":"c:objc(cs)MBMStyleImageMissing","kind":"typeIdentifier"},{"kind":"text","text":">"}],"deprecated":true,"abstract":[{"text":"A style has a missing image.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapEventType\/styleImageMissing"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"MBMStyleImageMissing","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageMissing\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageMissing\/fragments","value":[{"kind":"identifier","text":"MBMStyleImageMissing"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageMissing\/navigatorTitle","value":[{"text":"MBMStyleImageMissing","kind":"identifier"}]}]}]}