{"sections":[],"abstract":[{"text":"The requested style data has been loaded.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"styleDataLoaded","kind":"identifier"},{"kind":"text","text":": "},{"text":"MapEventType","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapEventType","preciseIdentifier":"s:10MapboxMaps12MapEventTypeV","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoaded","preciseIdentifier":"c:objc(cs)MBMStyleDataLoaded","text":"StyleDataLoaded"},{"kind":"text","text":"> { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/mapboxmaps\/mapeventtype\/styledataloaded"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","metadata":{"title":"styleDataLoaded","role":"symbol","modules":[{"name":"MapboxMaps"}],"platforms":[],"externalID":"s:10MapboxMaps12MapEventTypeV15styleDataLoadedACySo08MBMStylegH0CGvpZ","roleHeading":"Type Property","symbolKind":"property","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"styleDataLoaded"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps12MapEventTypeV","text":"MapEventType"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"StyleDataLoaded","preciseIdentifier":"c:objc(cs)MBMStyleDataLoaded"},{"kind":"text","text":">"}]},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapEventType"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapEventType\/styleDataLoaded"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapEventType/styleDataLoaded":{"role":"symbol","deprecated":true,"kind":"symbol","abstract":[{"text":"The requested style data has been loaded.","type":"text"}],"title":"styleDataLoaded","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapEventType\/styleDataLoaded","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"styleDataLoaded","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MapEventType","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps12MapEventTypeV"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)MBMStyleDataLoaded","kind":"typeIdentifier","text":"StyleDataLoaded"},{"kind":"text","text":">"}],"url":"\/documentation\/mapboxmaps\/mapeventtype\/styledataloaded"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","title":"MapboxMaps","type":"topic","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapEventType":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MapEventType"}],"url":"\/documentation\/mapboxmaps\/mapeventtype","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"MapEventType","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapEventType","deprecated":true,"type":"topic","abstract":[{"text":"A shim that makes it possible to subscribe to ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","type":"reference","isActive":true},{"type":"text","text":" and "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter","isActive":true,"type":"reference"},{"type":"text","text":" events via the old "},{"type":"codeVoice","code":"onNext"},{"type":"text","text":" and  "},{"type":"codeVoice","code":"onEvery"},{"text":" methods.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"It is here to simplify migration from v10 to v11, but will be removed in v12."}],"title":"MapEventType"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article","title":"MapboxMaps Documentation","abstract":[],"url":"\/documentation\/overview","role":"collection","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Snapshotter":{"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Snapshotter"}],"navigatorTitle":[{"kind":"identifier","text":"Snapshotter"}],"role":"symbol","title":"Snapshotter","url":"\/documentation\/mapboxmaps\/snapshotter","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter","abstract":[{"type":"text","text":"A utility class for capturing styled map snapshots."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap":{"kind":"symbol","navigatorTitle":[{"text":"MapboxMap","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapboxMap","kind":"identifier"}],"title":"MapboxMap","url":"\/documentation\/mapboxmaps\/mapboxmap","abstract":[{"type":"text","text":"Provides access to the map model, including the camera, style, observable map events,"},{"type":"text","text":" "},{"text":"and querying rendered features.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"type":"topic","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","url":"\/documentation\/mapboxmaps\/events","title":"Map events","kind":"article","abstract":[{"type":"text","text":"The simplified diagram of the events emitted by the map is displayed below."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleDataLoaded":{"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StyleDataLoaded","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"StyleDataLoaded"}],"role":"symbol","title":"StyleDataLoaded","url":"\/documentation\/mapboxmaps\/styledataloaded","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoaded","abstract":[{"type":"text","text":"The style data has been loaded. The event will be emitted once for each "},{"type":"codeVoice","code":"StyleDataLoadedType"},{"type":"text","text":" "},{"type":"text","text":"type during style loading. If a new style is set, events will be emitted again for the newly set style."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MBMStyleDataLoaded","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoaded\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoaded\/fragments","value":[{"text":"MBMStyleDataLoaded","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoaded\/navigatorTitle","value":[{"text":"MBMStyleDataLoaded","kind":"identifier"}]}]}]}