{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/freecameraoptions\/lookatpoint(forlocation:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/freecameraoptions\/lookatpoint(forlocation:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions\/lookAtPoint(forLocation:)"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"lookAtPoint","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forLocation","kind":"externalParam"},{"kind":"text","text":" "},{"text":"location","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"location","content":[{"inlineContent":[{"text":"The ","type":"text"},{"code":"coordinate","type":"codeVoice"},{"text":" representing focal point.","type":"text"}],"type":"paragraph"}]}]},{"kind":"content","content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"Note: Orientation can be invalid after this call, if the input leads to the camera being upside down or the quaternion has zero length.","type":"text"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"lookAtPoint(forLocation:)","navigatorTitle":[{"kind":"identifier","text":"lookAtPointForLocation:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"lookAtPoint"},{"kind":"text","text":"("},{"text":"forLocation","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D"},{"text":")","kind":"text"}],"modules":[{"name":"MapboxMaps"}],"externalID":"c:objc(cs)MBMFreeCameraOptions(im)lookAtPointForLocation:","role":"symbol","roleHeading":"Instance Method","symbolKind":"method"},"kind":"symbol","abstract":[{"type":"text","text":"Helper function for setting orientation of the camera by defining a focus point."},{"text":" ","type":"text"},{"text":"Elevation of 0.0 is used and no up vector.","type":"text"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FreeCameraOptions":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions","kind":"symbol","role":"symbol","title":"FreeCameraOptions","type":"topic","url":"\/documentation\/mapboxmaps\/freecameraoptions","abstract":[{"type":"text","text":"Various options for accessing physical properties of the underlying camera entity."},{"type":"text","text":" "},{"type":"text","text":"A direct access to these properties allows more flexible and precise controlling"},{"text":" ","type":"text"},{"text":"of the camera while also being fully compatible and interchangeable with CameraOptions.","type":"text"},{"text":" ","type":"text"},{"text":"All fields are optional.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FreeCameraOptions","kind":"identifier"}],"navigatorTitle":[{"text":"FreeCameraOptions","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FreeCameraOptions/lookAtPoint(forLocation:)":{"title":"lookAtPoint(forLocation:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"lookAtPointForLocation:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"lookAtPoint","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forLocation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D"},{"kind":"text","text":")"}],"url":"\/documentation\/mapboxmaps\/freecameraoptions\/lookatpoint(forlocation:)","abstract":[{"text":"Helper function for setting orientation of the camera by defining a focus point.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Elevation of 0.0 is used and no up vector."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions\/lookAtPoint(forLocation:)","role":"symbol","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","url":"\/documentation\/mapboxmaps\/mapboxmap-apis","kind":"article","title":"MapboxMap","role":"collectionGroup","type":"topic","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"lookAtPointForLocation:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"lookAtPointForLocation:"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"lookAtPointForLocation:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D"},{"text":") ","kind":"text"},{"text":"location","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"value":"MBMFreeCameraOptions","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions\/title","op":"replace"},{"value":[{"text":"MBMFreeCameraOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions~1lookAtPoint(forLocation:)\/title","value":"lookAtPointForLocation:"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions~1lookAtPoint(forLocation:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"lookAtPointForLocation:","kind":"identifier"}]}]}]}