{"sections":[],"variants":[{"paths":["\/documentation\/mapboxmaps\/stylemanager\/addpersistentcustomlayer(withid:layerhost:layerposition:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Style","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addPersistentCustomLayer(withId:layerHost:layerPosition:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"addPersistentCustomLayer"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withId"},{"text":" ","kind":"text"},{"text":"id","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"layerHost","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"CustomLayerHost","preciseIdentifier":"c:objc(pl)MBMCustomLayerHost","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerHost","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"layerPosition","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10MapboxMaps13LayerPositionO","text":"LayerPosition","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerPosition"},{"text":"?) ","kind":"text"},{"kind":"keyword","text":"throws"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"id","content":[{"inlineContent":[{"type":"text","text":"Style layer id."}],"type":"paragraph"}]},{"name":"layerHost","content":[{"type":"paragraph","inlineContent":[{"text":"Style custom layer host.","type":"text"}]}]},{"name":"layerPosition","content":[{"inlineContent":[{"type":"text","text":"Position to add the layer in the stack of layers on the map. Defaults to the top layer."}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Persistent style layers are valid across style reloads."}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"See Also: https:\/\/docs.mapbox.com\/mapbox-gl-js\/style-spec\/#layers"}]}]}]}]}],"metadata":{"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"addPersistentCustomLayer"},{"text":"(","kind":"text"},{"text":"withId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"layerHost","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"CustomLayerHost","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MBMCustomLayerHost"},{"text":", ","kind":"text"},{"text":"layerPosition","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LayerPosition","preciseIdentifier":"s:10MapboxMaps13LayerPositionO"},{"text":"?) ","kind":"text"},{"kind":"keyword","text":"throws"}],"title":"addPersistentCustomLayer(withId:layerHost:layerPosition:)","role":"symbol","modules":[{"name":"MapboxMaps"}],"roleHeading":"Instance Method","externalID":"s:10MapboxMaps12StyleManagerC24addPersistentCustomLayer6withId9layerHost0K8PositionySS_So09MBMCustomhL0_pAA0hM0OSgtKF"},"abstract":[{"type":"text","text":"Adds a new persistent style custom layer."}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","url":"\/documentation\/mapboxmaps\/mapboxmap","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapboxMap"}],"abstract":[{"text":"Provides access to the map model, including the camera, style, observable map events,","type":"text"},{"type":"text","text":" "},{"text":"and querying rendered features.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"MapboxMap","kind":"identifier"}],"title":"MapboxMap"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"type":"topic","role":"collection","kind":"article","title":"MapboxMaps Documentation","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"type":"topic","role":"collection","kind":"symbol","title":"MapboxMaps","url":"\/documentation\/mapboxmaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Snapshotter":{"abstract":[{"text":"A utility class for capturing styled map snapshots.","type":"text"}],"title":"Snapshotter","role":"symbol","url":"\/documentation\/mapboxmaps\/snapshotter","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Snapshotter","kind":"identifier"}],"navigatorTitle":[{"text":"Snapshotter","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter","type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerHost":{"type":"topic","title":"CustomLayerHost","navigatorTitle":[{"text":"CustomLayerHost","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomLayerHost","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/customlayerhost","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerHost","abstract":[{"text":"Interface for hosting a custom map style layer.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Style":{"kind":"article","type":"topic","title":"Style","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Style","url":"\/documentation\/mapboxmaps\/style","role":"collectionGroup","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager":{"abstract":[{"text":"Style manager is a base class for ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap"},{"text":" and ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter"},{"text":" that provides provides methods to manipulate Map Style at runtime.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager","role":"symbol","type":"topic","title":"StyleManager","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StyleManager"}],"navigatorTitle":[{"text":"StyleManager","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/stylemanager"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerPosition":{"url":"\/documentation\/mapboxmaps\/layerposition","title":"LayerPosition","navigatorTitle":[{"text":"LayerPosition","kind":"identifier"}],"abstract":[{"type":"text","text":"Specifies the position at which a layer will be added when using "},{"type":"codeVoice","code":"Style.addLayer"},{"text":".","type":"text"}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LayerPosition","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerPosition"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/addPersistentCustomLayer(withId:layerHost:layerPosition:)":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"addPersistentCustomLayer","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"layerHost","kind":"externalParam"},{"kind":"text","text":": any "},{"text":"CustomLayerHost","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MBMCustomLayerHost"},{"text":", ","kind":"text"},{"text":"layerPosition","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps13LayerPositionO","text":"LayerPosition","kind":"typeIdentifier"},{"text":"?) ","kind":"text"},{"kind":"keyword","text":"throws"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addPersistentCustomLayer(withId:layerHost:layerPosition:)","abstract":[{"text":"Adds a new persistent style custom layer.","type":"text"}],"title":"addPersistentCustomLayer(withId:layerHost:layerPosition:)","url":"\/documentation\/mapboxmaps\/stylemanager\/addpersistentcustomlayer(withid:layerhost:layerposition:)","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost\/title","op":"replace","value":"MBMCustomLayerHost"},{"value":[{"text":"MBMCustomLayerHost","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost\/navigatorTitle","value":[{"kind":"identifier","text":"MBMCustomLayerHost"}]}]}]}