{"variants":[{"paths":["\/documentation\/mapboxmaps\/stylemanager\/atmosphereproperty(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"atmosphereProperty","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"property","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValue","text":"StylePropertyValue","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMStylePropertyValue"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"property","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Style atmosphere property name."}]}]}],"kind":"parameters"},{"content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"inlineContent":[{"text":"Style atmosphere property value.","type":"text"}],"type":"paragraph"}],"kind":"content"},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"See Also: https:\/\/docs.mapbox.com\/mapbox-gl-js\/style-spec\/fog\/"}],"type":"paragraph"}]}],"type":"unorderedList"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","metadata":{"modules":[{"name":"MapboxMaps"}],"title":"atmosphereProperty(_:)","roleHeading":"Instance Method","role":"symbol","externalID":"s:10MapboxMaps12StyleManagerC18atmospherePropertyySo08MBMStyleF5ValueCSSF","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"atmosphereProperty","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":") -> ","kind":"text"},{"text":"StylePropertyValue","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMStylePropertyValue"}]},"abstract":[{"type":"text","text":"Gets the value of a style atmosphere property."}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Style","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager"]]},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/atmosphereProperty(_:)","interfaceLanguage":"swift"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","role":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapboxMap"}],"navigatorTitle":[{"text":"MapboxMap","kind":"identifier"}],"title":"MapboxMap","type":"topic","abstract":[{"text":"Provides access to the map model, including the camera, style, observable map events,","type":"text"},{"text":" ","type":"text"},{"text":"and querying rendered features.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Snapshotter":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter","role":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/snapshotter","abstract":[{"text":"A utility class for capturing styled map snapshots.","type":"text"}],"title":"Snapshotter","navigatorTitle":[{"text":"Snapshotter","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Snapshotter"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Style":{"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Style","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/style","title":"Style","type":"topic","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","abstract":[],"url":"\/documentation\/overview","role":"collection","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/atmosphereProperty(_:)":{"url":"\/documentation\/mapboxmaps\/stylemanager\/atmosphereproperty(_:)","abstract":[{"text":"Gets the value of a style atmosphere property.","type":"text"}],"title":"atmosphereProperty(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/atmosphereProperty(_:)","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"atmosphereProperty"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMStylePropertyValue","kind":"typeIdentifier","text":"StylePropertyValue"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePropertyValue":{"title":"StylePropertyValue","role":"symbol","navigatorTitle":[{"text":"StylePropertyValue","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValue","url":"\/documentation\/mapboxmaps\/stylepropertyvalue","abstract":[{"text":"Holds a style property value with meta data.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"StylePropertyValue","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager","role":"symbol","url":"\/documentation\/mapboxmaps\/stylemanager","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"StyleManager","kind":"identifier"}],"navigatorTitle":[{"text":"StyleManager","kind":"identifier"}],"title":"StyleManager","type":"topic","abstract":[{"type":"text","text":"Style manager is a base class for "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","type":"reference","isActive":true},{"text":" and ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter"},{"type":"text","text":" that provides provides methods to manipulate Map Style at runtime."}]}},"variantOverrides":[{"patch":[{"value":"MBMStylePropertyValue","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValue\/title"},{"op":"replace","value":[{"text":"MBMStylePropertyValue","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValue\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValue\/navigatorTitle","value":[{"kind":"identifier","text":"MBMStylePropertyValue"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}