{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXLocation\/monotonicTimestamp"},"sections":[],"abstract":[{"type":"text","text":"The monotonic timestamp, in nanoseconds."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"monotonicTimestamp"},{"text":";","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/mbxlocation\/monotonictimestamp"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"symbolKind":"property","title":"monotonicTimestamp","role":"symbol","externalID":"c:objc(cs)MBXLocation(py)monotonicTimestamp","modules":[{"name":"MapboxCommon"}],"roleHeading":"Instance Property","fragments":[{"kind":"identifier","text":"monotonicTimestamp"}],"navigatorTitle":[{"text":"monotonicTimestamp","kind":"identifier"}]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Location-APIs":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","type":"topic","kind":"article","abstract":[],"url":"\/documentation\/mapboxmaps\/location-apis","title":"Location","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXLocation/monotonicTimestamp":{"kind":"symbol","url":"\/documentation\/mapboxcommon\/mbxlocation\/monotonictimestamp","fragments":[{"kind":"identifier","text":"monotonicTimestamp"}],"role":"symbol","title":"monotonicTimestamp","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXLocation\/monotonicTimestamp","type":"topic","abstract":[{"type":"text","text":"The monotonic timestamp, in nanoseconds."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Location":{"title":"Location","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Location"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Location","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxcommon\/location","abstract":[{"type":"text","text":"Location information."}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"title":"MapboxMaps","kind":"symbol","role":"collection","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","role":"collection","url":"\/documentation\/overview","kind":"article","abstract":[],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/title","value":"MBXLocation","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/fragments","value":[{"kind":"identifier","text":"MBXLocation"}]},{"value":[{"kind":"identifier","text":"MBXLocation"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/navigatorTitle"}]}]}