{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ContextMode"]]},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ContextMode\/Equatable-Implementations","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"article","sections":[],"topicSections":[{"generated":true,"title":"Operators","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ContextMode\/!=(_:_:)"],"anchor":"Operators"}],"metadata":{"modules":[{"name":"MapboxMaps"}],"role":"collectionGroup","title":"Equatable Implementations","roleHeading":"API Collection"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/mapboxmaps","title":"MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"abstract":[],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","role":"collectionGroup","title":"MapboxMap","url":"\/documentation\/mapboxmaps\/mapboxmap-apis","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ContextMode":{"abstract":[{"type":"text","text":"Describes the map context mode."},{"text":" ","type":"text"},{"text":"We can make some optimizations if we know that the drawing context is not shared with other code.","type":"text"}],"navigatorTitle":[{"text":"ContextMode","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ContextMode","role":"symbol","kind":"symbol","type":"topic","title":"ContextMode","url":"\/documentation\/mapboxmaps\/contextmode","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ContextMode","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ContextMode/!=(_:_:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ContextMode\/!=(_:_:)","url":"\/documentation\/mapboxmaps\/contextmode\/!=(_:_:)","role":"symbol","title":"!=(_:_:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"!="},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","type":"topic","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","abstract":[],"kind":"article","role":"collection","url":"\/documentation\/overview"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ContextMode\/title","op":"replace","value":"MBMContextMode"},{"value":[{"kind":"identifier","text":"MBMContextMode"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ContextMode\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ContextMode\/navigatorTitle","value":[{"text":"MBMContextMode","kind":"identifier"}],"op":"replace"}]}]}