{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ContextMode\/unique"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ContextMode"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unique"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/contextmode\/unique"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/contextmode\/unique"]}],"abstract":[{"type":"text","text":"Unique context mode: in OpenGL, the GL context is not shared, thus we can retain knowledge about the GL state"},{"type":"text","text":" "},{"text":"from a previous render pass. It also enables clearing the screen using glClear for the bottommost background","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"layer when no pattern is applied to that layer."}],"metadata":{"navigatorTitle":[{"text":"MBMContextModeUnique","kind":"identifier"}],"role":"symbol","modules":[{"name":"MapboxMaps"}],"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unique","kind":"identifier"}],"title":"ContextMode.unique","symbolKind":"case","externalID":"c:@E@MBMContextMode@MBMContextModeUnique"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ContextMode":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ContextMode","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/contextmode","abstract":[{"type":"text","text":"Describes the map context mode."},{"type":"text","text":" "},{"text":"We can make some optimizations if we know that the drawing context is not shared with other code.","type":"text"}],"role":"symbol","title":"ContextMode","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ContextMode","type":"topic","kind":"symbol","navigatorTitle":[{"text":"ContextMode","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"role":"collectionGroup","abstract":[],"url":"\/documentation\/mapboxmaps\/mapboxmap-apis","title":"MapboxMap","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","role":"collection","abstract":[],"type":"topic","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ContextMode/unique":{"navigatorTitle":[{"text":"MBMContextModeUnique","kind":"identifier"}],"abstract":[{"text":"Unique context mode: in OpenGL, the GL context is not shared, thus we can retain knowledge about the GL state","type":"text"},{"type":"text","text":" "},{"type":"text","text":"from a previous render pass. It also enables clearing the screen using glClear for the bottommost background"},{"type":"text","text":" "},{"text":"layer when no pattern is applied to that layer.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ContextMode\/unique","role":"symbol","url":"\/documentation\/mapboxmaps\/contextmode\/unique","type":"topic","title":"ContextMode.unique","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"unique","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"MBMContextModeUnique","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"MBMContextModeUnique","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"MBMContextModeUnique"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ContextMode\/title","value":"MBMContextMode"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ContextMode\/fragments","value":[{"kind":"identifier","text":"MBMContextMode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ContextMode\/navigatorTitle","value":[{"kind":"identifier","text":"MBMContextMode"}]},{"value":"MBMContextModeUnique","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ContextMode~1unique\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ContextMode~1unique\/fragments","value":[{"text":"MBMContextModeUnique","kind":"identifier"}],"op":"replace"}]}]}