{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest\/init(url:headers:sdkInformation:body:)","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"url","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"headers","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"sdkInformation"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SdkInformation","text":"SdkInformation","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXSdkInformation"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"body"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"kind":"text","text":"?)"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest"]]},"variants":[{"paths":["\/documentation\/mapboxcommon\/httprequest\/init(url:headers:sdkinformation:body:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxcommon\/httprequest\/init(url:headers:sdkinformation:body:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:objc(cs)MBXHttpRequest(im)initWithUrl:headers:sdkInformation:body:","title":"init(url:headers:sdkInformation:body:)","roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"url","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"headers","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"sdkInformation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SdkInformation","preciseIdentifier":"c:objc(cs)MBXSdkInformation"},{"text":", ","kind":"text"},{"text":"body","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"text":"?)","kind":"text"}],"symbolKind":"init","modules":[{"name":"MapboxCommon"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithUrl:headers:sdkInformation:body:"}]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"title":"MapboxCommon","abstract":[],"type":"topic","url":"\/documentation\/mapboxcommon","role":"collection","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequest/init(url:headers:sdkInformation:body:)":{"url":"\/documentation\/mapboxcommon\/httprequest\/init(url:headers:sdkinformation:body:)","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest\/init(url:headers:sdkInformation:body:)","title":"init(url:headers:sdkInformation:body:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"url"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"headers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"sdkInformation"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBXSdkInformation","text":"SdkInformation","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"body","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"initWithUrl:headers:sdkInformation:body:","kind":"identifier"}],"type":"topic","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SdkInformation":{"abstract":[{"type":"text","text":"Provides information about a given Mapbox SDK. This information is then used to populate the “User-Agent” HTTP header"},{"text":" ","type":"text"},{"text":"of HTTP requests generated from within Mapbox SDKs. Mapbox SDKs include Maps, Navigation, Search, and others.","type":"text"}],"title":"SdkInformation","url":"\/documentation\/mapboxcommon\/sdkinformation","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SdkInformation","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SdkInformation","role":"symbol","navigatorTitle":[{"text":"SdkInformation","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequest":{"kind":"symbol","abstract":[{"text":"HttpRequest holds basic information for construction of an HTTP request","type":"text"}],"role":"symbol","url":"\/documentation\/mapboxcommon\/httprequest","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"HttpRequest"}],"type":"topic","title":"HttpRequest","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest","navigatorTitle":[{"kind":"identifier","text":"HttpRequest"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"initWithUrl:headers:sdkInformation:body:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"initWithUrl:headers:sdkInformation:body:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithUrl:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"url","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"headers:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSDictionary<NSString *,NSString *>","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"headers"},{"kind":"text","text":" "},{"kind":"identifier","text":"sdkInformation:"},{"text":"(","kind":"text"},{"text":"MBXSdkInformation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SdkInformation","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXSdkInformation"},{"text":" *) ","kind":"text"},{"text":"sdkInformation","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"body:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSData","text":"NSData","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"body","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest~1init(url:headers:sdkInformation:body:)\/title","value":"initWithUrl:headers:sdkInformation:body:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithUrl:headers:sdkInformation:body:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest~1init(url:headers:sdkInformation:body:)\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SdkInformation\/title","op":"replace","value":"MBXSdkInformation"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SdkInformation\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXSdkInformation"}]},{"value":[{"kind":"identifier","text":"MBXSdkInformation"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SdkInformation\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest\/title","value":"MBXHttpRequest","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest\/fragments","op":"replace","value":[{"text":"MBXHttpRequest","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest\/navigatorTitle","value":[{"kind":"identifier","text":"MBXHttpRequest"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}