{"metadata":{"platforms":[],"roleHeading":"Type Property","symbolKind":"property","title":"mapLoadingError","modules":[{"name":"MapboxMaps"}],"role":"symbol","externalID":"s:10MapboxMaps12MapEventTypeV15mapLoadingErrorACySo06MBMMapgH0CGvpZ","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"mapLoadingError","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MapEventType","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps12MapEventTypeV"},{"text":"<","kind":"text"},{"text":"MapLoadingError","preciseIdentifier":"c:objc(cs)MBMMapLoadingError","kind":"typeIdentifier"},{"kind":"text","text":">"}]},"kind":"symbol","abstract":[{"type":"text","text":"An error that has occurred while loading the Map."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"mapLoadingError","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps12MapEventTypeV","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapEventType","text":"MapEventType","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingError","text":"MapLoadingError","preciseIdentifier":"c:objc(cs)MBMMapLoadingError","kind":"typeIdentifier"},{"kind":"text","text":"> { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/mapeventtype\/maploadingerror"]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapEventType"]]},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapEventType\/mapLoadingError","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapEventType":{"url":"\/documentation\/mapboxmaps\/mapeventtype","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapEventType","abstract":[{"type":"text","text":"A shim that makes it possible to subscribe to "},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","isActive":true},{"text":" and ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter","isActive":true,"type":"reference"},{"text":" events via the old ","type":"text"},{"code":"onNext","type":"codeVoice"},{"text":" and  ","type":"text"},{"type":"codeVoice","code":"onEvery"},{"type":"text","text":" methods."},{"text":" ","type":"text"},{"type":"text","text":"It is here to simplify migration from v10 to v11, but will be removed in v12."}],"deprecated":true,"type":"topic","title":"MapEventType","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapEventType"}],"navigatorTitle":[{"kind":"identifier","text":"MapEventType"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","url":"\/documentation\/mapboxmaps\/events","kind":"article","role":"collectionGroup","type":"topic","title":"Map events","abstract":[{"type":"text","text":"The simplified diagram of the events emitted by the map is displayed below."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoadingError":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingError","navigatorTitle":[{"text":"MapLoadingError","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MapLoadingError","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/maploadingerror","title":"MapLoadingError","abstract":[{"text":"Describes an error that has occurred while loading the ","type":"text"},{"code":"map","type":"codeVoice"},{"text":". The ","type":"text"},{"code":"type","type":"codeVoice"},{"text":" property","type":"text"},{"type":"text","text":" "},{"type":"text","text":"defines what resource could not be loaded, and the "},{"type":"codeVoice","code":"message"},{"type":"text","text":" property will contain"},{"type":"text","text":" "},{"type":"text","text":"a descriptive error message."}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"type":"topic","role":"collection","kind":"article","title":"MapboxMaps Documentation","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Snapshotter":{"abstract":[{"text":"A utility class for capturing styled map snapshots.","type":"text"}],"title":"Snapshotter","role":"symbol","url":"\/documentation\/mapboxmaps\/snapshotter","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Snapshotter","kind":"identifier"}],"navigatorTitle":[{"text":"Snapshotter","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter","type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapEventType/mapLoadingError":{"title":"mapLoadingError","abstract":[{"type":"text","text":"An error that has occurred while loading the Map."}],"url":"\/documentation\/mapboxmaps\/mapeventtype\/maploadingerror","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapEventType\/mapLoadingError","kind":"symbol","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"mapLoadingError","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MapEventType","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps12MapEventTypeV"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)MBMMapLoadingError","text":"MapLoadingError","kind":"typeIdentifier"},{"kind":"text","text":">"}],"deprecated":true},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","url":"\/documentation\/mapboxmaps\/mapboxmap","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapboxMap"}],"abstract":[{"text":"Provides access to the map model, including the camera, style, observable map events,","type":"text"},{"type":"text","text":" "},{"text":"and querying rendered features.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"MapboxMap","kind":"identifier"}],"title":"MapboxMap"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"type":"topic","role":"collection","kind":"symbol","title":"MapboxMaps","url":"\/documentation\/mapboxmaps"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingError\/title","value":"MBMMapLoadingError","op":"replace"},{"op":"replace","value":[{"text":"MBMMapLoadingError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingError\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingError\/navigatorTitle","value":[{"text":"MBMMapLoadingError","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}