{"kind":"symbol","metadata":{"modules":[{"name":"MapboxMaps"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"statusChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"OfflineRegionStatus","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMOfflineRegionStatus"},{"text":")","kind":"text"}],"externalID":"c:objc(pl)MBMOfflineRegionObserver(im)statusChangedForStatus:","navigatorTitle":[{"text":"statusChangedForStatus:","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Method","platforms":[],"title":"statusChanged(for:)","required":true},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionObserver"]]},"variants":[{"paths":["\/documentation\/mapboxmaps\/offlineregionobserver\/statuschanged(for:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/offlineregionobserver\/statuschanged(for:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"type":"text","text":"Implement this method to be notified of a change in the status of an"},{"type":"text","text":" "},{"type":"text","text":"offline region. Status changes include any change in state of the members"},{"type":"text","text":" "},{"type":"text","text":"of "},{"type":"codeVoice","code":"offline region status"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"statusChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"status","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionStatus","preciseIdentifier":"c:objc(cs)MBMOfflineRegionStatus","text":"OfflineRegionStatus","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionObserver\/statusChanged(for:)","interfaceLanguage":"swift"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionObserver":{"kind":"symbol","abstract":[{"type":"text","text":"A region can have a single observer, which gets notified whenever a change"},{"type":"text","text":" "},{"type":"text","text":"to the region’s status occurs."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionObserver","title":"OfflineRegionObserver","navigatorTitle":[{"text":"OfflineRegionObserver","kind":"identifier"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OfflineRegionObserver","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/offlineregionobserver","type":"topic","deprecated":true},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionStatus":{"role":"symbol","deprecated":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionStatus","abstract":[{"type":"text","text":"A region’s status includes its active\/inactive state as well as counts"},{"type":"text","text":" "},{"type":"text","text":"of the number of resources that have completed downloading, their total"},{"type":"text","text":" "},{"type":"text","text":"size in bytes, and the total number of resources that are required."}],"url":"\/documentation\/mapboxmaps\/offlineregionstatus","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OfflineRegionStatus"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"OfflineRegionStatus"}],"kind":"symbol","title":"OfflineRegionStatus"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMaps":{"kind":"article","url":"\/documentation\/mapboxmaps\/coremaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","type":"topic","abstract":[{"text":"Maps rendering SDK also known as GL-Native","type":"text"}],"role":"collectionGroup","title":"Core Maps API"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Offline":{"kind":"article","title":"Offline Support","abstract":[],"role":"collectionGroup","url":"\/documentation\/mapboxmaps\/offline","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","url":"\/documentation\/mapboxmaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","kind":"article","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionObserver/statusChanged(for:)":{"abstract":[{"text":"Implement this method to be notified of a change in the status of an","type":"text"},{"text":" ","type":"text"},{"text":"offline region. Status changes include any change in state of the members","type":"text"},{"text":" ","type":"text"},{"text":"of ","type":"text"},{"type":"codeVoice","code":"offline region status"},{"text":".","type":"text"}],"deprecated":true,"url":"\/documentation\/mapboxmaps\/offlineregionobserver\/statuschanged(for:)","required":true,"navigatorTitle":[{"text":"statusChangedForStatus:","kind":"identifier"}],"type":"topic","title":"statusChanged(for:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"statusChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"OfflineRegionStatus","preciseIdentifier":"c:objc(cs)MBMOfflineRegionStatus","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionObserver\/statusChanged(for:)","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"statusChangedForStatus:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"statusChangedForStatus:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"statusChangedForStatus:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MBMOfflineRegionStatus","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionStatus","preciseIdentifier":"c:objc(cs)MBMOfflineRegionStatus"},{"text":" *) ","kind":"text"},{"text":"status","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionObserver\/title","value":"MBMOfflineRegionObserver"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionObserver\/fragments","value":[{"text":"MBMOfflineRegionObserver","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionObserver\/navigatorTitle","value":[{"kind":"identifier","text":"MBMOfflineRegionObserver"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionStatus\/title","value":"MBMOfflineRegionStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionStatus\/fragments","value":[{"kind":"identifier","text":"MBMOfflineRegionStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionStatus\/navigatorTitle","value":[{"kind":"identifier","text":"MBMOfflineRegionStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionObserver~1statusChanged(for:)\/title","value":"statusChangedForStatus:"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionObserver~1statusChanged(for:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"statusChangedForStatus:"}]}]}]}