{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GenericEvent\/init(name:data:timeInterval:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":", ","kind":"text"},{"text":"timeInterval","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"EventTimeInterval","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/EventTimeInterval","preciseIdentifier":"c:objc(cs)MBMEventTimeInterval"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GenericEvent"]]},"metadata":{"externalID":"c:objc(cs)MBMGenericEvent(im)initWithName:data:timeInterval:","title":"init(name:data:timeInterval:)","role":"symbol","symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timeInterval"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MBMEventTimeInterval","kind":"typeIdentifier","text":"EventTimeInterval"},{"kind":"text","text":")"}],"modules":[{"name":"MapboxMaps"}],"roleHeading":"Initializer","navigatorTitle":[{"kind":"identifier","text":"initWithName:data:timeInterval:"}]},"variants":[{"paths":["\/documentation\/mapboxmaps\/genericevent\/init(name:data:timeinterval:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/genericevent\/init(name:data:timeinterval:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GenericEvent/init(name:data:timeInterval:)":{"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithName:data:timeInterval:"}],"abstract":[],"title":"init(name:data:timeInterval:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timeInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EventTimeInterval","preciseIdentifier":"c:objc(cs)MBMEventTimeInterval"},{"kind":"text","text":")"}],"url":"\/documentation\/mapboxmaps\/genericevent\/init(name:data:timeinterval:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GenericEvent\/init(name:data:timeInterval:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GenericEvent":{"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GenericEvent"}],"abstract":[{"type":"text","text":"The generic event type."}],"title":"GenericEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GenericEvent"}],"url":"\/documentation\/mapboxmaps\/genericevent","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GenericEvent"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"role":"collectionGroup","kind":"article","type":"topic","abstract":[{"text":"The simplified diagram of the events emitted by the map is displayed below.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","url":"\/documentation\/mapboxmaps\/events","title":"Map events"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/EventTimeInterval":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EventTimeInterval","kind":"identifier"}],"title":"EventTimeInterval","url":"\/documentation\/mapboxmaps\/eventtimeinterval","type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/EventTimeInterval","abstract":[{"text":"The time interval of an event. The ","type":"text"},{"code":"begin","type":"codeVoice"},{"text":" property represents the time","type":"text"},{"text":" ","type":"text"},{"text":"origin of an event, and the ","type":"text"},{"code":"end","type":"codeVoice"},{"text":" property represents the time when the particular","type":"text"},{"text":" ","type":"text"},{"text":"operation is complete. The timestamps are sampled at the origin and do not include","type":"text"},{"text":" ","type":"text"},{"text":"the time required to dispatch an event.","type":"text"}],"navigatorTitle":[{"text":"EventTimeInterval","kind":"identifier"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","url":"\/documentation\/mapboxmaps","title":"MapboxMaps","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","role":"collection","type":"topic","abstract":[],"title":"MapboxMaps Documentation","kind":"article"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"initWithName:data:timeInterval:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithName:data:timeInterval:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithName:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"name"},{"kind":"text","text":" "},{"kind":"identifier","text":"data:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"internalParam","text":"data"},{"kind":"text","text":" "},{"kind":"identifier","text":"timeInterval:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/EventTimeInterval","preciseIdentifier":"c:objc(cs)MBMEventTimeInterval","text":"MBMEventTimeInterval"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"timeInterval"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"initWithName:data:timeInterval:","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEvent~1init(name:data:timeInterval:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithName:data:timeInterval:"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEvent~1init(name:data:timeInterval:)\/fragments"},{"op":"replace","value":"MBMGenericEvent","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEvent\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBMGenericEvent"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEvent\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MBMGenericEvent"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEvent\/navigatorTitle"},{"op":"replace","value":"MBMEventTimeInterval","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1EventTimeInterval\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBMEventTimeInterval"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1EventTimeInterval\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MBMEventTimeInterval"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1EventTimeInterval\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}