{"sections":[],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestPriorityType\/Equatable-Implementations","interfaceLanguage":"swift"},"topicSections":[{"generated":true,"anchor":"Operators","title":"Operators","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestPriorityType\/!=(_:_:)"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"modules":[{"name":"MapboxMaps"}],"role":"collectionGroup","roleHeading":"API Collection","title":"Equatable Implementations"},"kind":"article","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestPriorityType"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestPriorityType":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestPriorityType","role":"symbol","title":"RequestPriorityType","abstract":[{"text":"The enumeration defines the priority of a resource request.","type":"text"}],"url":"\/documentation\/mapboxmaps\/requestprioritytype","navigatorTitle":[{"text":"RequestPriorityType","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RequestPriorityType"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"kind":"article","url":"\/documentation\/overview","role":"collection","title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestPriorityType/!=(_:_:)":{"url":"\/documentation\/mapboxmaps\/requestprioritytype\/!=(_:_:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[],"title":"!=(_:_:)","kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestPriorityType\/!=(_:_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","title":"MapboxMaps","type":"topic","url":"\/documentation\/mapboxmaps","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"title":"Map events","url":"\/documentation\/mapboxmaps\/events","type":"topic","abstract":[{"text":"The simplified diagram of the events emitted by the map is displayed below.","type":"text"}],"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","role":"collectionGroup"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestPriorityType\/title","op":"replace","value":"MBMRequestPriorityType"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestPriorityType\/fragments","value":[{"text":"MBMRequestPriorityType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestPriorityType\/navigatorTitle","value":[{"kind":"identifier","text":"MBMRequestPriorityType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}