{"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedType"]]},"variants":[{"paths":["\/documentation\/mapboxmaps\/styledataloadedtype\/sources"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/styledataloadedtype\/sources"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"All sources defined by the style are loaded, and their properties can be read and updated if needed.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sources","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"metadata":{"title":"StyleDataLoadedType.sources","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sources","kind":"identifier"}],"role":"symbol","roleHeading":"Case","modules":[{"name":"MapboxMaps"}],"externalID":"c:@E@MBMStyleDataLoadedType@MBMStyleDataLoadedTypeSources","navigatorTitle":[{"text":"MBMStyleDataLoadedTypeSources","kind":"identifier"}],"symbolKind":"case"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedType\/sources"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleDataLoadedType":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StyleDataLoadedType","kind":"identifier"}],"abstract":[{"type":"text","text":"The enumeration defines the type of loaded style data."}],"navigatorTitle":[{"text":"StyleDataLoadedType","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedType","url":"\/documentation\/mapboxmaps\/styledataloadedtype","role":"symbol","title":"StyleDataLoadedType"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleDataLoadedType/sources":{"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sources","kind":"identifier"}],"abstract":[{"type":"text","text":"All sources defined by the style are loaded, and their properties can be read and updated if needed."}],"role":"symbol","kind":"symbol","url":"\/documentation\/mapboxmaps\/styledataloadedtype\/sources","navigatorTitle":[{"text":"MBMStyleDataLoadedTypeSources","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedType\/sources","title":"StyleDataLoadedType.sources"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"role":"collectionGroup","kind":"article","type":"topic","url":"\/documentation\/mapboxmaps\/events","title":"Map events","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","abstract":[{"text":"The simplified diagram of the events emitted by the map is displayed below.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"kind":"article","role":"collection","title":"MapboxMaps Documentation"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MBMStyleDataLoadedTypeSources"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MBMStyleDataLoadedTypeSources"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"MBMStyleDataLoadedTypeSources"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedType\/title","value":"MBMStyleDataLoadedType"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedType\/fragments","value":[{"text":"MBMStyleDataLoadedType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedType\/navigatorTitle","value":[{"kind":"identifier","text":"MBMStyleDataLoadedType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedType~1sources\/title","value":"MBMStyleDataLoadedTypeSources"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedType~1sources\/fragments","value":[{"text":"MBMStyleDataLoadedTypeSources","kind":"identifier"}]}]}]}