{"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"acceptExpired","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"text":"This flag should be set to true to accept expired responses. When a tile is already loaded but expired, no","type":"text"},{"type":"text","text":" "},{"text":"attempt will be made to refresh the data. This may lead to outdated data. Set to false to ensure that data","type":"text"},{"type":"text","text":" "},{"type":"text","text":"for a tile is up-to-date. Set to true to continue loading a group without updating expired data for tiles that"},{"type":"text","text":" "},{"text":"are already downloaded.","type":"text"}]}]}],"variants":[{"paths":["\/documentation\/mapboxcommon\/tileregionloadoptions\/acceptexpired"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/tileregionloadoptions\/acceptexpired"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions\/acceptExpired"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions"]]},"metadata":{"symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"text":"acceptExpired","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"acceptExpired","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"title":"acceptExpired","externalID":"c:objc(cs)MBXTileRegionLoadOptions(py)acceptExpired","modules":[{"name":"MapboxCommon"}],"role":"symbol"},"abstract":[{"type":"text","text":"Accepts expired data when loading tiles."}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadOptions/acceptExpired":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions\/acceptExpired","kind":"symbol","abstract":[{"text":"Accepts expired data when loading tiles.","type":"text"}],"title":"acceptExpired","url":"\/documentation\/mapboxcommon\/tileregionloadoptions\/acceptexpired","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"acceptExpired","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"acceptExpired","kind":"identifier"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadOptions":{"abstract":[{"type":"text","text":"Describes the tile region load option values."}],"kind":"symbol","role":"symbol","type":"topic","title":"TileRegionLoadOptions","url":"\/documentation\/mapboxcommon\/tileregionloadoptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions","navigatorTitle":[{"text":"TileRegionLoadOptions","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileRegionLoadOptions"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","url":"\/documentation\/mapboxmaps\/tilestore-apis","kind":"article","title":"TileStore APIs","abstract":[],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"url":"\/documentation\/mapboxmaps","title":"MapboxMaps","type":"topic","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"acceptExpired"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"acceptExpired","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":" ","kind":"text"},{"kind":"identifier","text":"acceptExpired"},{"text":";","kind":"text"}]}]}},{"value":"acceptExpired","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions~1acceptExpired\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions~1acceptExpired\/fragments","value":[{"kind":"identifier","text":"acceptExpired"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/title","value":"MBXTileRegionLoadOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/fragments","value":[{"text":"MBXTileRegionLoadOptions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/navigatorTitle","value":[{"kind":"identifier","text":"MBXTileRegionLoadOptions"}]}]}]}