{"kind":"symbol","abstract":[{"text":"Get file flush buffer size setting.","type":"text"}],"metadata":{"roleHeading":"Type Method","externalID":"c:objc(cs)MBXExperimentalPersistentLogConfiguration(cm)getFileFlushBufferSize","title":"getFileFlushBufferSize()","navigatorTitle":[{"text":"getFileFlushBufferSize","kind":"identifier"}],"modules":[{"name":"MapboxCommon"}],"symbolKind":"method","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getFileFlushBufferSize","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration"]]},"variants":[{"paths":["\/documentation\/mapboxcommon\/persistentlogconfiguration\/getfileflushbuffersize()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxcommon\/persistentlogconfiguration\/getfileflushbuffersize()"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/getFileFlushBufferSize()"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getFileFlushBufferSize","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"text":"Return Value","type":"heading","anchor":"return-value","level":2},{"inlineContent":[{"text":"Optional. Size in bytes buffer can reach before writing or nullopt if not set.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"title":"MapboxMaps Documentation","type":"topic","kind":"article","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"url":"\/documentation\/mapboxcommon","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","title":"MapboxCommon","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PersistentLogConfiguration/getFileFlushBufferSize()":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getFileFlushBufferSize","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?","kind":"text"}],"url":"\/documentation\/mapboxcommon\/persistentlogconfiguration\/getfileflushbuffersize()","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/getFileFlushBufferSize()","abstract":[{"text":"Get file flush buffer size setting.","type":"text"}],"role":"symbol","title":"getFileFlushBufferSize()","type":"topic","navigatorTitle":[{"text":"getFileFlushBufferSize","kind":"identifier"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PersistentLogConfiguration":{"title":"PersistentLogConfiguration","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PersistentLogConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"PersistentLogConfiguration","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/persistentlogconfiguration","type":"topic","kind":"symbol","abstract":[{"text":"Settings to configure behavior of persistent log","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"getFileFlushBufferSize"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"getFileFlushBufferSize","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"getFileFlushBufferSize","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"content","content":[{"anchor":"return-value","text":"Return Value","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Optional. Size in bytes buffer can reach before writing or nullopt if not set."}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1getFileFlushBufferSize()\/title","value":"getFileFlushBufferSize"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1getFileFlushBufferSize()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"getFileFlushBufferSize","kind":"identifier"}]},{"value":"MBXExperimentalPersistentLogConfiguration","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration\/title"},{"value":[{"text":"MBXExperimentalPersistentLogConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"MBXExperimentalPersistentLogConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}