{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getFileFlushSeconds"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Optional. Amount of seconds to wait before writing logs to file or nullopt if not set."}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/persistentlogconfiguration\/getfileflushseconds()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/persistentlogconfiguration\/getfileflushseconds()"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/getFileFlushSeconds()"},"metadata":{"modules":[{"name":"MapboxCommon"}],"symbolKind":"method","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getFileFlushSeconds","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"externalID":"c:objc(cs)MBXExperimentalPersistentLogConfiguration(cm)getFileFlushSeconds","navigatorTitle":[{"text":"getFileFlushSeconds","kind":"identifier"}],"title":"getFileFlushSeconds()","roleHeading":"Type Method"},"abstract":[{"text":"Get file flush configuration.","type":"text"}],"kind":"symbol","sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"kind":"article","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","url":"\/documentation\/overview","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"title":"MapboxCommon","abstract":[],"kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","url":"\/documentation\/mapboxcommon"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PersistentLogConfiguration/getFileFlushSeconds()":{"abstract":[{"type":"text","text":"Get file flush configuration."}],"navigatorTitle":[{"text":"getFileFlushSeconds","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/getFileFlushSeconds()","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getFileFlushSeconds","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?","kind":"text"}],"url":"\/documentation\/mapboxcommon\/persistentlogconfiguration\/getfileflushseconds()","title":"getFileFlushSeconds()","kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PersistentLogConfiguration":{"kind":"symbol","url":"\/documentation\/mapboxcommon\/persistentlogconfiguration","navigatorTitle":[{"kind":"identifier","text":"PersistentLogConfiguration"}],"title":"PersistentLogConfiguration","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PersistentLogConfiguration"}],"abstract":[{"type":"text","text":"Settings to configure behavior of persistent log"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"getFileFlushSeconds","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getFileFlushSeconds"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"getFileFlushSeconds","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"content","content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Optional. Amount of seconds to wait before writing logs to file or nullopt if not set."}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"getFileFlushSeconds","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1getFileFlushSeconds()\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getFileFlushSeconds"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1getFileFlushSeconds()\/fragments"},{"value":"MBXExperimentalPersistentLogConfiguration","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration\/title"},{"value":[{"kind":"identifier","text":"MBXExperimentalPersistentLogConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration\/fragments"},{"value":[{"text":"MBXExperimentalPersistentLogConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration\/navigatorTitle"}]}]}