{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setFileMaxSizeForMaxSize","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:s6UInt64V","text":"UInt64","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"setFileMaxSizeForMaxSize:","kind":"identifier"}],"role":"symbol","externalID":"c:objc(cs)MBXExperimentalPersistentLogConfiguration(cm)setFileMaxSizeForMaxSize:","roleHeading":"Type Method","title":"setFileMaxSizeForMaxSize(_:)","symbolKind":"method","modules":[{"name":"MapboxCommon"}]},"variants":[{"paths":["\/documentation\/mapboxcommon\/persistentlogconfiguration\/setfilemaxsizeformaxsize(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxcommon\/persistentlogconfiguration\/setfilemaxsizeformaxsize(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setFileMaxSizeForMaxSize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"maxSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt64","preciseIdentifier":"s:s6UInt64V"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"maxSize","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Maximum file size in bytes."},{"type":"text","text":" "},{"type":"text","text":"Default is 10 MB"}]}]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration"]]},"abstract":[{"text":"Set maximum file size for stored logs.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/setFileMaxSizeForMaxSize(_:)"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"url":"\/documentation\/mapboxcommon","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","title":"MapboxCommon","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"title":"MapboxMaps Documentation","type":"topic","kind":"article","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PersistentLogConfiguration":{"title":"PersistentLogConfiguration","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PersistentLogConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"PersistentLogConfiguration","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/persistentlogconfiguration","type":"topic","kind":"symbol","abstract":[{"text":"Settings to configure behavior of persistent log","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PersistentLogConfiguration/setFileMaxSizeForMaxSize(_:)":{"url":"\/documentation\/mapboxcommon\/persistentlogconfiguration\/setfilemaxsizeformaxsize(_:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setFileMaxSizeForMaxSize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UInt64","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V"},{"text":")","kind":"text"}],"role":"symbol","abstract":[{"type":"text","text":"Set maximum file size for stored logs."}],"kind":"symbol","navigatorTitle":[{"text":"setFileMaxSizeForMaxSize:","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/setFileMaxSizeForMaxSize(_:)","title":"setFileMaxSizeForMaxSize(_:)","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"setFileMaxSizeForMaxSize:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"+ ","kind":"text"},{"text":"setFileMaxSizeForMaxSize:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"setFileMaxSizeForMaxSize:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"uint64_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@uint64_t"},{"text":") ","kind":"text"},{"text":"maxSize","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Maximum file size in bytes.","type":"text"},{"text":" ","type":"text"},{"text":"Default is 10 MB","type":"text"}]}],"name":"maxSize"}]},"path":"\/primaryContentSections\/1","op":"replace"},{"value":"MBXExperimentalPersistentLogConfiguration","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MBXExperimentalPersistentLogConfiguration"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration\/fragments","op":"replace"},{"value":[{"text":"MBXExperimentalPersistentLogConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration\/navigatorTitle","op":"replace"},{"value":"setFileMaxSizeForMaxSize:","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1setFileMaxSizeForMaxSize(_:)\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"setFileMaxSizeForMaxSize:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1setFileMaxSizeForMaxSize(_:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}