{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration"]]},"metadata":{"title":"setFileFlushConfigForLogLines(_:seconds:bufferSize:immediateFlushFromLogLevel:)","navigatorTitle":[{"kind":"identifier","text":"setFileFlushConfigForLogLines:seconds:bufferSize:immediateFlushFromLogLevel:"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setFileFlushConfigForLogLines","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"seconds"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"bufferSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"immediateFlushFromLogLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?)"}],"roleHeading":"Type Method","symbolKind":"method","modules":[{"name":"MapboxCommon"}],"externalID":"c:objc(cs)MBXExperimentalPersistentLogConfiguration(cm)setFileFlushConfigForLogLines:seconds:bufferSize:immediateFlushFromLogLevel:","role":"symbol"},"abstract":[{"text":"Set file flush configuration.","type":"text"}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/setFileFlushConfigForLogLines(_:seconds:bufferSize:immediateFlushFromLogLevel:)","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setFileFlushConfigForLogLines"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"logLines"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"seconds"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"bufferSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"immediateFlushFromLogLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?)"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"logLines","content":[{"inlineContent":[{"type":"text","text":"Optional. Amount of lines to store in memory before writing."}],"type":"paragraph"}]},{"name":"seconds","content":[{"inlineContent":[{"type":"text","text":"Optional. Seconds between writing to file."}],"type":"paragraph"}]},{"name":"bufferSize","content":[{"inlineContent":[{"type":"text","text":"Optional. Size of buffer before writing to file."}],"type":"paragraph"}]},{"name":"immediateFlushFromLogLevel","content":[{"inlineContent":[{"type":"text","text":"Optional. Log level that should be flushed to file immediately."},{"type":"text","text":" "},{"type":"text","text":"Default for all of these is unset, meaning immediate writing to logfile"}],"type":"paragraph"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/persistentlogconfiguration\/setfileflushconfigforloglines(_:seconds:buffersize:immediateflushfromloglevel:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/persistentlogconfiguration\/setfileflushconfigforloglines(_:seconds:buffersize:immediateflushfromloglevel:)"]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PersistentLogConfiguration":{"title":"PersistentLogConfiguration","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PersistentLogConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"PersistentLogConfiguration","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/persistentlogconfiguration","type":"topic","kind":"symbol","abstract":[{"text":"Settings to configure behavior of persistent log","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"title":"MapboxMaps Documentation","type":"topic","kind":"article","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"url":"\/documentation\/mapboxcommon","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","title":"MapboxCommon","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PersistentLogConfiguration/setFileFlushConfigForLogLines(_:seconds:bufferSize:immediateFlushFromLogLevel:)":{"navigatorTitle":[{"text":"setFileFlushConfigForLogLines:seconds:bufferSize:immediateFlushFromLogLevel:","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setFileFlushConfigForLogLines","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"seconds","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"bufferSize","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"immediateFlushFromLogLevel","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"title":"setFileFlushConfigForLogLines(_:seconds:bufferSize:immediateFlushFromLogLevel:)","abstract":[{"text":"Set file flush configuration.","type":"text"}],"url":"\/documentation\/mapboxcommon\/persistentlogconfiguration\/setfileflushconfigforloglines(_:seconds:buffersize:immediateflushfromloglevel:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/setFileFlushConfigForLogLines(_:seconds:bufferSize:immediateFlushFromLogLevel:)","type":"topic","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"setFileFlushConfigForLogLines:seconds:bufferSize:immediateFlushFromLogLevel:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"setFileFlushConfigForLogLines:seconds:bufferSize:immediateFlushFromLogLevel:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"setFileFlushConfigForLogLines:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"logLines","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"seconds:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"seconds"},{"kind":"text","text":" "},{"kind":"identifier","text":"bufferSize:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"bufferSize"},{"kind":"text","text":" "},{"text":"immediateFlushFromLogLevel:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"immediateFlushFromLogLevel","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Optional. Amount of lines to store in memory before writing."}]}],"name":"logLines"},{"content":[{"inlineContent":[{"text":"Optional. Seconds between writing to file.","type":"text"}],"type":"paragraph"}],"name":"seconds"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Optional. Size of buffer before writing to file."}]}],"name":"bufferSize"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Optional. Log level that should be flushed to file immediately."},{"type":"text","text":" "},{"type":"text","text":"Default for all of these is unset, meaning immediate writing to logfile"}]}],"name":"immediateFlushFromLogLevel"}]}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration\/title","value":"MBXExperimentalPersistentLogConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration\/fragments","value":[{"kind":"identifier","text":"MBXExperimentalPersistentLogConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration\/navigatorTitle","value":[{"text":"MBXExperimentalPersistentLogConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1setFileFlushConfigForLogLines(_:seconds:bufferSize:immediateFlushFromLogLevel:)\/title","value":"setFileFlushConfigForLogLines:seconds:bufferSize:immediateFlushFromLogLevel:"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1setFileFlushConfigForLogLines(_:seconds:bufferSize:immediateFlushFromLogLevel:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setFileFlushConfigForLogLines:seconds:bufferSize:immediateFlushFromLogLevel:"}]}]}]}