{"metadata":{"externalID":"c:objc(cs)MBMTileCacheBudget(im)getTileCacheBudgetInTiles","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getInTiles","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"TileCacheBudgetInTiles","preciseIdentifier":"c:objc(cs)MBMTileCacheBudgetInTiles","kind":"typeIdentifier"}],"symbolKind":"method","navigatorTitle":[{"text":"getTileCacheBudgetInTiles","kind":"identifier"}],"roleHeading":"Instance Method","modules":[{"name":"MapboxMaps"}],"role":"symbol","title":"getInTiles()"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getInTiles","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"TileCacheBudgetInTiles","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInTiles","preciseIdentifier":"c:objc(cs)MBMTileCacheBudgetInTiles"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudget\/getInTiles()"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudget"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/mapboxmaps\/tilecachebudget\/getintiles()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/tilecachebudget\/getintiles()"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","type":"topic","abstract":[],"title":"MapboxMaps Documentation","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","title":"TileStore APIs","url":"\/documentation\/mapboxmaps\/tilestore-apis","kind":"article","type":"topic","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudget/getInTiles()":{"url":"\/documentation\/mapboxmaps\/tilecachebudget\/getintiles()","abstract":[],"role":"symbol","kind":"symbol","type":"topic","title":"getInTiles()","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudget\/getInTiles()","navigatorTitle":[{"kind":"identifier","text":"getTileCacheBudgetInTiles"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getInTiles"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"TileCacheBudgetInTiles","preciseIdentifier":"c:objc(cs)MBMTileCacheBudgetInTiles"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudgetInTiles":{"navigatorTitle":[{"text":"TileCacheBudgetInTiles","kind":"identifier"}],"title":"TileCacheBudgetInTiles","abstract":[{"text":"Tile cache budget in tiles.","type":"text"}],"url":"\/documentation\/mapboxmaps\/tilecachebudgetintiles","type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInTiles","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileCacheBudgetInTiles","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudget":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudget","navigatorTitle":[{"text":"TileCacheBudget","kind":"identifier"}],"role":"symbol","type":"topic","title":"TileCacheBudget","url":"\/documentation\/mapboxmaps\/tilecachebudget","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileCacheBudget"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","role":"collection","title":"MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"getTileCacheBudgetInTiles","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getTileCacheBudgetInTiles"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInTiles","text":"MBMTileCacheBudgetInTiles","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMTileCacheBudgetInTiles"},{"text":" *) ","kind":"text"},{"text":"getTileCacheBudgetInTiles","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"getTileCacheBudgetInTiles","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudget~1getInTiles()\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getTileCacheBudgetInTiles"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudget~1getInTiles()\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInTiles\/title","op":"replace","value":"MBMTileCacheBudgetInTiles"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInTiles\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMTileCacheBudgetInTiles"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInTiles\/navigatorTitle","op":"replace","value":[{"text":"MBMTileCacheBudgetInTiles","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudget\/title","op":"replace","value":"MBMTileCacheBudget"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudget\/fragments","op":"replace","value":[{"text":"MBMTileCacheBudget","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudget\/navigatorTitle","op":"replace","value":[{"text":"MBMTileCacheBudget","kind":"identifier"}]}]}]}