{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapEventType\/styleImageRemoveUnused"},"metadata":{"title":"styleImageRemoveUnused","externalID":"s:10MapboxMaps12MapEventTypeV22styleImageRemoveUnusedACySo08MBMStyleghI0CGvpZ","roleHeading":"Type Property","platforms":[],"symbolKind":"property","role":"symbol","modules":[{"name":"MapboxMaps"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"styleImageRemoveUnused"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10MapboxMaps12MapEventTypeV","text":"MapEventType","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"text":"StyleImageRemoveUnused","preciseIdentifier":"c:objc(cs)MBMStyleImageRemoveUnused","kind":"typeIdentifier"},{"text":">","kind":"text"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapEventType"]]},"variants":[{"paths":["\/documentation\/mapboxmaps\/mapeventtype\/styleimageremoveunused"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"styleImageRemoveUnused"},{"text":": ","kind":"text"},{"text":"MapEventType","preciseIdentifier":"s:10MapboxMaps12MapEventTypeV","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapEventType","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnused","preciseIdentifier":"c:objc(cs)MBMStyleImageRemoveUnused","text":"StyleImageRemoveUnused","kind":"typeIdentifier"},{"text":"> { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"text":"An image added to the style is no longer needed and can be removed.","type":"text"}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapEventType":{"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"MapEventType","kind":"identifier"}],"deprecated":true,"kind":"symbol","type":"topic","title":"MapEventType","role":"symbol","navigatorTitle":[{"text":"MapEventType","kind":"identifier"}],"abstract":[{"type":"text","text":"A shim that makes it possible to subscribe to "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","isActive":true,"type":"reference"},{"text":" and ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter"},{"text":" events via the old ","type":"text"},{"code":"onNext","type":"codeVoice"},{"type":"text","text":" and  "},{"type":"codeVoice","code":"onEvery"},{"type":"text","text":" methods."},{"text":" ","type":"text"},{"type":"text","text":"It is here to simplify migration from v10 to v11, but will be removed in v12."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapEventType","url":"\/documentation\/mapboxmaps\/mapeventtype"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Snapshotter":{"navigatorTitle":[{"kind":"identifier","text":"Snapshotter"}],"title":"Snapshotter","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Snapshotter","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/snapshotter","kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter","abstract":[{"type":"text","text":"A utility class for capturing styled map snapshots."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapEventType/styleImageRemoveUnused":{"url":"\/documentation\/mapboxmaps\/mapeventtype\/styleimageremoveunused","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"styleImageRemoveUnused"},{"kind":"text","text":": "},{"text":"MapEventType","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps12MapEventTypeV"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMStyleImageRemoveUnused","text":"StyleImageRemoveUnused","kind":"typeIdentifier"},{"text":">","kind":"text"}],"kind":"symbol","role":"symbol","deprecated":true,"abstract":[{"text":"An image added to the style is no longer needed and can be removed.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapEventType\/styleImageRemoveUnused","type":"topic","title":"styleImageRemoveUnused"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","url":"\/documentation\/overview","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap":{"abstract":[{"text":"Provides access to the map model, including the camera, style, observable map events,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"and querying rendered features."}],"navigatorTitle":[{"text":"MapboxMap","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapboxMap"}],"title":"MapboxMap"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleImageRemoveUnused":{"title":"StyleImageRemoveUnused","url":"\/documentation\/mapboxmaps\/styleimageremoveunused","navigatorTitle":[{"kind":"identifier","text":"StyleImageRemoveUnused"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnused","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"An image requested by the "},{"code":"map","type":"codeVoice"},{"text":" through the ","type":"text"},{"code":"StyleImageMissing","type":"codeVoice"},{"type":"text","text":" event is no longer"},{"type":"text","text":" "},{"text":"needed and can be removed using the ","type":"text"},{"type":"codeVoice","code":"removeStyleImage"},{"text":" method. The application can","type":"text"},{"text":" ","type":"text"},{"text":"decide whether the image should be kept or removed.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"StyleImageRemoveUnused","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"kind":"article","title":"Map events","role":"collectionGroup","type":"topic","abstract":[{"type":"text","text":"The simplified diagram of the events emitted by the map is displayed below."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","url":"\/documentation\/mapboxmaps\/events"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"title":"MapboxMaps","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnused\/title","value":"MBMStyleImageRemoveUnused","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnused\/fragments","value":[{"kind":"identifier","text":"MBMStyleImageRemoveUnused"}]},{"value":[{"text":"MBMStyleImageRemoveUnused","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnused\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}