{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"HttpServiceInterceptorInterface","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/mapboxcommon\/httpserviceinterceptorinterface"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/httpserviceinterceptorinterface"]}],"kind":"symbol","topicSections":[{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceInterceptorInterface\/onRequest(for:continuation:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceInterceptorInterface\/onResponse(for:continuation:)"]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceInterceptorInterface"},"abstract":[{"type":"text","text":"Interface for intercepting and modifying HttpService function calls."}],"sections":[],"metadata":{"symbolKind":"protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HttpServiceInterceptorInterface","kind":"identifier"}],"roleHeading":"Protocol","modules":[{"name":"MapboxCommon"}],"title":"HttpServiceInterceptorInterface","role":"symbol","externalID":"c:objc(pl)MBXHttpServiceInterceptorInterface","navigatorTitle":[{"text":"HttpServiceInterceptorInterface","kind":"identifier"}]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpServiceInterceptorInterface":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HttpServiceInterceptorInterface","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/httpserviceinterceptorinterface","navigatorTitle":[{"text":"HttpServiceInterceptorInterface","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceInterceptorInterface","type":"topic","role":"symbol","abstract":[{"text":"Interface for intercepting and modifying HttpService function calls.","type":"text"}],"kind":"symbol","title":"HttpServiceInterceptorInterface"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","kind":"symbol","url":"\/documentation\/mapboxcommon","type":"topic","role":"collection","abstract":[],"title":"MapboxCommon"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpServiceInterceptorInterface/onRequest(for:continuation:)":{"kind":"symbol","navigatorTitle":[{"text":"onRequestForRequest:continuation:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onRequest","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"text":"HttpRequest","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXHttpRequest"},{"text":", ","kind":"text"},{"text":"continuation","kind":"externalParam"},{"kind":"text","text":": "},{"text":"HttpServiceInterceptorRequestContinuation","kind":"typeIdentifier","preciseIdentifier":"c:MBXHttpServiceInterceptorRequestContinuation.h@T@MBXHttpServiceInterceptorRequestContinuation"},{"kind":"text","text":")"}],"title":"onRequest(for:continuation:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceInterceptorInterface\/onRequest(for:continuation:)","type":"topic","abstract":[{"text":"The function to intercept HTTP requests with.","type":"text"}],"role":"symbol","required":true,"url":"\/documentation\/mapboxcommon\/httpserviceinterceptorinterface\/onrequest(for:continuation:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpServiceInterceptorInterface/onResponse(for:continuation:)":{"required":true,"kind":"symbol","type":"topic","url":"\/documentation\/mapboxcommon\/httpserviceinterceptorinterface\/onresponse(for:continuation:)","abstract":[{"text":"The function to intercept HTTP responses with.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceInterceptorInterface\/onResponse(for:continuation:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onResponse"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBXHttpResponse","text":"HttpResponse","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"continuation"},{"text":": ","kind":"text"},{"text":"HttpServiceInterceptorResponseContinuation","preciseIdentifier":"c:MBXHttpServiceInterceptorResponseContinuation.h@T@MBXHttpServiceInterceptorResponseContinuation","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"onResponse(for:continuation:)","navigatorTitle":[{"text":"onResponseForResponse:continuation:","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","url":"\/documentation\/overview","kind":"article","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"MBXHttpServiceInterceptorInterface","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MBXHttpServiceInterceptorInterface"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"MBXHttpServiceInterceptorInterface","kind":"identifier"}]},{"value":[{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceInterceptorInterface\/onRequest(for:continuation:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceInterceptorInterface\/onResponse(for:continuation:)"]}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBXHttpServiceInterceptorInterface"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceInterceptorInterface\/title","value":"MBXHttpServiceInterceptorInterface"},{"op":"replace","value":[{"text":"MBXHttpServiceInterceptorInterface","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceInterceptorInterface\/fragments"},{"value":[{"text":"MBXHttpServiceInterceptorInterface","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceInterceptorInterface\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceInterceptorInterface~1onRequest(for:continuation:)\/title","value":"onRequestForRequest:continuation:","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceInterceptorInterface~1onRequest(for:continuation:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onRequestForRequest:continuation:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceInterceptorInterface~1onResponse(for:continuation:)\/title","value":"onResponseForResponse:continuation:","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceInterceptorInterface~1onResponse(for:continuation:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onResponseForResponse:continuation:","kind":"identifier"}]}]}]}