{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SwiftUI","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onResourceRequest"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"action"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"keyword"},{"kind":"text","text":" ("},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequest","text":"ResourceRequest","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMResourceRequest"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Map","preciseIdentifier":"s:10MapboxMaps3MapV","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"role":"symbol","externalID":"s:10MapboxMaps3MapV17onResourceRequest6actionACySo011MBMResourceF0Cc_tF","title":"onResourceRequest(action:)","symbolKind":"method","modules":[{"name":"MapboxMaps"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onResourceRequest","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"text":": (","kind":"text"},{"text":"ResourceRequest","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMResourceRequest"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps3MapV","text":"Map","kind":"typeIdentifier"}],"roleHeading":"Instance Method","extendedModule":"MapboxMaps"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onResourceRequest(action:)"},"abstract":[{"type":"text","text":"Adds an action to perform when a resource request is performed."}],"variants":[{"paths":["\/documentation\/mapboxmaps\/map\/onresourcerequest(action:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/onResourceRequest(action:)":{"abstract":[{"type":"text","text":"Adds an action to perform when a resource request is performed."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onResourceRequest"},{"kind":"text","text":"("},{"text":"action","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMResourceRequest","text":"ResourceRequest","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":") -> "},{"text":"Map","preciseIdentifier":"s:10MapboxMaps3MapV","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/map\/onresourcerequest(action:)","title":"onResourceRequest(action:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onResourceRequest(action:)","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","kind":"article","abstract":[],"title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","role":"collection","title":"MapboxMaps","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map":{"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Map"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"Map","kind":"identifier"}],"abstract":[{"text":"A SwiftUI view that displays a Mapbox Map.","type":"text"}],"url":"\/documentation\/mapboxmaps\/map","title":"Map","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SwiftUI":{"title":"SwiftUI","abstract":[],"type":"topic","kind":"article","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SwiftUI","url":"\/documentation\/mapboxmaps\/swiftui"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResourceRequest":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResourceRequest"}],"abstract":[{"text":"The ","type":"text"},{"code":"ResourceRequest","type":"codeVoice"},{"type":"text","text":" event allows the application to observe resource requests made by a "},{"type":"codeVoice","code":"map"},{"text":" or ","type":"text"},{"code":"map snapshotter","type":"codeVoice"},{"type":"text","text":" object."}],"navigatorTitle":[{"text":"ResourceRequest","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/resourcerequest","role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequest","title":"ResourceRequest"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MBMResourceRequest","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequest\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequest\/fragments","op":"replace","value":[{"text":"MBMResourceRequest","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequest\/navigatorTitle","value":[{"text":"MBMResourceRequest","kind":"identifier"}]}]}]}