{"metadata":{"title":"onSourceRemoved(action:)","roleHeading":"Instance Method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onSourceRemoved","kind":"identifier"},{"text":"(","kind":"text"},{"text":"action","kind":"externalParam"},{"kind":"text","text":": ("},{"preciseIdentifier":"c:objc(cs)MBMSourceRemoved","text":"SourceRemoved","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"text":"Map","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps3MapV"}],"externalID":"s:10MapboxMaps3MapV15onSourceRemoved6actionACySo09MBMSourceF0Cc_tF","symbolKind":"method","modules":[{"name":"MapboxMaps"}],"extendedModule":"MapboxMaps","platforms":[{"introducedAt":"13.0","name":"iOS","beta":false,"deprecated":false,"unavailable":false},{"beta":false,"introducedAt":"13.0","name":"iPadOS","unavailable":false,"deprecated":false},{"name":"Mac Catalyst","unavailable":false,"beta":false,"introducedAt":"13.0","deprecated":false}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onSourceRemoved(action:)"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onSourceRemoved","kind":"identifier"},{"text":"(","kind":"text"},{"text":"action","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"keyword","text":"@escaping"},{"text":" (","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceRemoved","text":"SourceRemoved","preciseIdentifier":"c:objc(cs)MBMSourceRemoved"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map","preciseIdentifier":"s:10MapboxMaps3MapV","text":"Map"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SwiftUI","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/map\/onsourceremoved(action:)"]}],"abstract":[{"type":"text","text":"Adds an action to perform when a source is removed."}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceRemoved":{"abstract":[{"text":"The source has been removed with ","type":"text"},{"type":"codeVoice","code":"removeStyleSource"},{"type":"text","text":" method."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceRemoved","url":"\/documentation\/mapboxmaps\/sourceremoved","kind":"symbol","type":"topic","role":"symbol","title":"SourceRemoved","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SourceRemoved","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SourceRemoved"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","role":"collection","abstract":[],"type":"topic","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map":{"url":"\/documentation\/mapboxmaps\/map","navigatorTitle":[{"text":"Map","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map","abstract":[{"text":"A SwiftUI view that displays a Mapbox Map.","type":"text"}],"title":"Map","role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"Map","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/onSourceRemoved(action:)":{"role":"symbol","title":"onSourceRemoved(action:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onSourceRemoved"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"text":": (","kind":"text"},{"text":"SourceRemoved","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMSourceRemoved"},{"kind":"text","text":") -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:10MapboxMaps3MapV","text":"Map","kind":"typeIdentifier"}],"url":"\/documentation\/mapboxmaps\/map\/onsourceremoved(action:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onSourceRemoved(action:)","type":"topic","kind":"symbol","abstract":[{"text":"Adds an action to perform when a source is removed.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SwiftUI":{"abstract":[],"title":"SwiftUI","kind":"article","url":"\/documentation\/mapboxmaps\/swiftui","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SwiftUI","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceRemoved\/title","value":"MBMSourceRemoved"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceRemoved\/fragments","value":[{"kind":"identifier","text":"MBMSourceRemoved"}],"op":"replace"},{"op":"replace","value":[{"text":"MBMSourceRemoved","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceRemoved\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}