{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/tileregionestimateoptions\/isequal(to:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/tileregionestimateoptions\/isequal(to:)"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":" "},{"kind":"internalParam","text":"other"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateOptions","text":"TileRegionEstimateOptions","preciseIdentifier":"c:objc(cs)MBXTileRegionEstimateOptions"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateOptions\/isEqual(to:)","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Method","externalID":"c:objc(cs)MBXTileRegionEstimateOptions(im)isEqualToTileRegionEstimateOptions:","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TileRegionEstimateOptions","preciseIdentifier":"c:objc(cs)MBXTileRegionEstimateOptions","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"title":"isEqual(to:)","role":"symbol","modules":[{"name":"MapboxCommon"}],"navigatorTitle":[{"text":"isEqualToTileRegionEstimateOptions:","kind":"identifier"}]},"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateOptions"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","type":"topic","abstract":[],"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","kind":"symbol","type":"topic","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","role":"collectionGroup","abstract":[],"kind":"article","url":"\/documentation\/mapboxmaps\/tilestore-apis","type":"topic","title":"TileStore APIs"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateOptions/isEqual(to:)":{"title":"isEqual(to:)","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateOptions\/isEqual(to:)","url":"\/documentation\/mapboxcommon\/tileregionestimateoptions\/isequal(to:)","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBXTileRegionEstimateOptions","text":"TileRegionEstimateOptions","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"isEqualToTileRegionEstimateOptions:","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateOptions":{"abstract":[{"type":"text","text":"Holds options for the tile region estimation operation."}],"role":"symbol","navigatorTitle":[{"text":"TileRegionEstimateOptions","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateOptions","kind":"symbol","title":"TileRegionEstimateOptions","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileRegionEstimateOptions","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxcommon\/tileregionestimateoptions"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"isEqualToTileRegionEstimateOptions:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqualToTileRegionEstimateOptions:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isEqualToTileRegionEstimateOptions:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MBXTileRegionEstimateOptions","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateOptions","preciseIdentifier":"c:objc(cs)MBXTileRegionEstimateOptions"},{"text":" *) ","kind":"text"},{"text":"other","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"isEqualToTileRegionEstimateOptions:","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateOptions~1isEqual(to:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"isEqualToTileRegionEstimateOptions:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateOptions~1isEqual(to:)\/fragments","op":"replace"},{"value":"MBXTileRegionEstimateOptions","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateOptions\/title","op":"replace"},{"value":[{"text":"MBXTileRegionEstimateOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateOptions\/fragments","op":"replace"},{"value":[{"text":"MBXTileRegionEstimateOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateOptions\/navigatorTitle","op":"replace"}]}]}