{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/accuracyauthorization\/inexact"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/accuracyauthorization\/inexact"]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization"]]},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization\/inexact","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"text":"MBXAccuracyAuthorizationInexact","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"inexact","kind":"identifier"}],"title":"AccuracyAuthorization.inexact","externalID":"c:@E@MBXAccuracyAuthorization@MBXAccuracyAuthorizationInexact","role":"symbol","symbolKind":"case","roleHeading":"Case","modules":[{"name":"MapboxCommon"}]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"An app is authorized to receive rough location only."}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"inexact","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"inlineContent":[{"type":"text","text":"Depends on a platform the accuracy is within a city block."}],"type":"paragraph"}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/AccuracyAuthorization/inexact":{"navigatorTitle":[{"kind":"identifier","text":"MBXAccuracyAuthorizationInexact"}],"role":"symbol","abstract":[{"text":"An app is authorized to receive rough location only.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization\/inexact","title":"AccuracyAuthorization.inexact","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"inexact"}],"kind":"symbol","url":"\/documentation\/mapboxcommon\/accuracyauthorization\/inexact"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"kind":"article","role":"collection","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/AccuracyAuthorization":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization","role":"symbol","url":"\/documentation\/mapboxcommon\/accuracyauthorization","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AccuracyAuthorization"}],"abstract":[{"type":"text","text":"Accuracy authorization granted by user to the app."}],"navigatorTitle":[{"kind":"identifier","text":"AccuracyAuthorization"}],"title":"AccuracyAuthorization"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Location-APIs":{"abstract":[],"kind":"article","role":"collectionGroup","title":"Location","type":"topic","url":"\/documentation\/mapboxmaps\/location-apis","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"MBXAccuracyAuthorizationInexact","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"MBXAccuracyAuthorizationInexact"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"MBXAccuracyAuthorizationInexact","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MBXAccuracyAuthorizationInexact","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization~1inexact\/title"},{"value":[{"text":"MBXAccuracyAuthorizationInexact","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization~1inexact\/fragments"},{"value":"MBXAccuracyAuthorization","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization\/title"},{"value":[{"kind":"identifier","text":"MBXAccuracyAuthorization"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization\/fragments"},{"value":[{"kind":"identifier","text":"MBXAccuracyAuthorization"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization\/navigatorTitle"}]}]}