{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-View","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapOptions"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" * "},{"kind":"identifier","text":"contextMode"},{"text":";","kind":"text"}]}]}],"kind":"symbol","metadata":{"modules":[{"name":"MapboxMaps"}],"title":"contextMode","externalID":"c:objc(cs)MBMMapOptions(py)contextMode","role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"contextMode"}],"symbolKind":"property","fragments":[{"text":"contextMode","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/mbmmapoptions\/contextmode"]}],"abstract":[{"text":"The map context mode. This can be used to optimizations","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"if we know that the drawing context is not shared with other code."}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapOptions\/contextMode"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapOptions":{"url":"\/documentation\/mapboxmaps\/mapoptions","abstract":[{"type":"text","text":"Describes the map option values."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapOptions","navigatorTitle":[{"kind":"identifier","text":"MapOptions"}],"kind":"symbol","title":"MapOptions","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapOptions"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map-View":{"title":"MapView","url":"\/documentation\/mapboxmaps\/map-view","kind":"article","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-View","abstract":[],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","title":"MapboxMaps Documentation","url":"\/documentation\/overview","type":"topic","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","role":"collection","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMMapOptions/contextMode":{"abstract":[{"text":"The map context mode. This can be used to optimizations","type":"text"},{"type":"text","text":" "},{"text":"if we know that the drawing context is not shared with other code.","type":"text"}],"url":"\/documentation\/mapboxmaps\/mbmmapoptions\/contextmode","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapOptions\/contextMode","fragments":[{"text":"contextMode","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"contextMode"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapOptions\/title","value":"MBMMapOptions"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapOptions\/fragments","value":[{"kind":"identifier","text":"MBMMapOptions"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapOptions\/navigatorTitle","value":[{"text":"MBMMapOptions","kind":"identifier"}],"op":"replace"}]}]}