{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerMapProjection"]]},"metadata":{"required":true,"role":"symbol","title":"getTransitionPhase()","roleHeading":"Instance Method","modules":[{"name":"MapboxMaps"}],"externalID":"c:objc(pl)MBMCustomLayerMapProjection(im)getTransitionPhase","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"getTransitionPhase"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getTransitionPhase","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"}]},"variants":[{"paths":["\/documentation\/mapboxmaps\/customlayermapprojection\/gettransitionphase()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/customlayermapprojection\/gettransitionphase()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerMapProjection\/getTransitionPhase()","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"Returns normalized value [0, 1] describing phase of the transition between the currently active projection and"},{"type":"text","text":" "},{"type":"text","text":"mercator projection. This value is 1 when the projection is active and transitions towards the value 0 (mercator projection)"},{"type":"text","text":" "},{"type":"text","text":"as the map is zoomed."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getTransitionPhase"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"}],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Phase value describing transition between active projection and mercator projection."}]}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerMapProjection":{"abstract":[],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/customlayermapprojection","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomLayerMapProjection"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerMapProjection","title":"CustomLayerMapProjection","navigatorTitle":[{"kind":"identifier","text":"CustomLayerMapProjection"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","url":"\/documentation\/overview","role":"collection","abstract":[],"kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"type":"topic","url":"\/documentation\/mapboxmaps","role":"collection","kind":"symbol","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layers":{"title":"Layers","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers","abstract":[],"role":"collectionGroup","kind":"article","url":"\/documentation\/mapboxmaps\/layers"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerMapProjection/getTransitionPhase()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getTransitionPhase","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerMapProjection\/getTransitionPhase()","title":"getTransitionPhase()","kind":"symbol","type":"topic","required":true,"url":"\/documentation\/mapboxmaps\/customlayermapprojection\/gettransitionphase()","navigatorTitle":[{"text":"getTransitionPhase","kind":"identifier"}],"abstract":[{"text":"Returns normalized value [0, 1] describing phase of the transition between the currently active projection and","type":"text"},{"text":" ","type":"text"},{"text":"mercator projection. This value is 1 when the projection is active and transitions towards the value 0 (mercator projection)","type":"text"},{"text":" ","type":"text"},{"text":"as the map is zoomed.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"getTransitionPhase","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"getTransitionPhase","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"float","preciseIdentifier":"c:f"},{"kind":"text","text":") "},{"kind":"identifier","text":"getTransitionPhase"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"content","content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"Phase value describing transition between active projection and mercator projection.","type":"text"}]}]},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"MBMCustomLayerMapProjection","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerMapProjection\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBMCustomLayerMapProjection"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerMapProjection\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MBMCustomLayerMapProjection"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerMapProjection\/navigatorTitle"},{"op":"replace","value":"getTransitionPhase","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerMapProjection~1getTransitionPhase()\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getTransitionPhase"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerMapProjection~1getTransitionPhase()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}