{"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Returns a specialized model matrix for supporting rendering of custom geometry during transition between"},{"type":"text","text":" "},{"type":"text","text":"the active projection and mercator projection. Transition matrix prepares points on web mercator coordinate space"},{"type":"text","text":" "},{"type":"text","text":"to be used as destination points of the interpolation operation towards mercator projection."}],"variants":[{"paths":["\/documentation\/mapboxmaps\/customlayermapprojection\/gettransitionmatrix()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/customlayermapprojection\/gettransitionmatrix()"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getTransitionMatrix","kind":"identifier"},{"text":"() -> [","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"]","kind":"text"}]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","type":"heading","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Example:"},{"type":"text","text":" "},{"type":"text","text":"ecefPoint = latLngToEcef(60.1699, 24.9384)"},{"type":"text","text":" "},{"type":"text","text":"mercPoint = latLngToMercator(60.1699, 24.9384)"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"clipPoint = projectionMatrix * lerp(getTransitionMatrix() * mercPoint, getModelMatrix() * ecefPoint, getTransitionPhase())"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerMapProjection"]]},"sections":[],"metadata":{"externalID":"c:objc(pl)MBMCustomLayerMapProjection(im)getTransitionMatrix","symbolKind":"method","title":"getTransitionMatrix()","roleHeading":"Instance Method","role":"symbol","modules":[{"name":"MapboxMaps"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getTransitionMatrix"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"]"}],"navigatorTitle":[{"kind":"identifier","text":"getTransitionMatrix"}],"required":true},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerMapProjection\/getTransitionMatrix()"},"kind":"symbol","references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","url":"\/documentation\/overview","role":"collection","abstract":[],"kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layers":{"title":"Layers","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers","abstract":[],"role":"collectionGroup","kind":"article","url":"\/documentation\/mapboxmaps\/layers"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerMapProjection/getTransitionMatrix()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getTransitionMatrix"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"]"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerMapProjection\/getTransitionMatrix()","title":"getTransitionMatrix()","kind":"symbol","type":"topic","required":true,"url":"\/documentation\/mapboxmaps\/customlayermapprojection\/gettransitionmatrix()","navigatorTitle":[{"kind":"identifier","text":"getTransitionMatrix"}],"abstract":[{"type":"text","text":"Returns a specialized model matrix for supporting rendering of custom geometry during transition between"},{"type":"text","text":" "},{"type":"text","text":"the active projection and mercator projection. Transition matrix prepares points on web mercator coordinate space"},{"type":"text","text":" "},{"type":"text","text":"to be used as destination points of the interpolation operation towards mercator projection."}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerMapProjection":{"abstract":[],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/customlayermapprojection","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomLayerMapProjection"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerMapProjection","title":"CustomLayerMapProjection","navigatorTitle":[{"kind":"identifier","text":"CustomLayerMapProjection"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"type":"topic","url":"\/documentation\/mapboxmaps","role":"collection","kind":"symbol","title":"MapboxMaps"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"getTransitionMatrix","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getTransitionMatrix"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<NSNumber *>"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"getTransitionMatrix"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"getTransitionMatrix","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerMapProjection~1getTransitionMatrix()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"getTransitionMatrix","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerMapProjection~1getTransitionMatrix()\/fragments"},{"op":"replace","value":"MBMCustomLayerMapProjection","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerMapProjection\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBMCustomLayerMapProjection"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerMapProjection\/fragments"},{"op":"replace","value":[{"text":"MBMCustomLayerMapProjection","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerMapProjection\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}