{"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"required"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"externalID":"c:@E@MBMCustomRasterSourceTileStatus@MBMCustomRasterSourceTileStatusRequired","roleHeading":"Case","title":"CustomRasterSourceTileStatus.required","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"MBMCustomRasterSourceTileStatusRequired"}],"role":"symbol","modules":[{"name":"MapboxMaps"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"required","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatus"]]},"sections":[],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatus\/required","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/customrastersourcetilestatus\/required"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/customrastersourcetilestatus\/required"]}],"abstract":[{"type":"text","text":"Tile best suited for current camera position."},{"type":"text","text":" "},{"type":"text","text":"Should be loaded if possible."}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileStatus/required":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"required","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/customrastersourcetilestatus\/required","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatus\/required","title":"CustomRasterSourceTileStatus.required","abstract":[{"text":"Tile best suited for current camera position.","type":"text"},{"type":"text","text":" "},{"text":"Should be loaded if possible.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBMCustomRasterSourceTileStatusRequired"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","role":"collection","abstract":[],"kind":"article","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Sources":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources","abstract":[],"url":"\/documentation\/mapboxmaps\/sources","title":"Sources","kind":"article","type":"topic","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","url":"\/documentation\/mapboxmaps","type":"topic","role":"collection","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileStatus":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatus","role":"symbol","title":"CustomRasterSourceTileStatus","kind":"symbol","navigatorTitle":[{"text":"CustomRasterSourceTileStatus","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/customrastersourcetilestatus","abstract":[{"type":"text","text":"CustomRasterSource tile status."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomRasterSourceTileStatus"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"MBMCustomRasterSourceTileStatusRequired","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileStatusRequired"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"MBMCustomRasterSourceTileStatusRequired"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatus~1required\/title","value":"MBMCustomRasterSourceTileStatusRequired"},{"value":[{"text":"MBMCustomRasterSourceTileStatusRequired","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatus~1required\/fragments","op":"replace"},{"op":"replace","value":"MBMCustomRasterSourceTileStatus","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatus\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatus\/fragments","op":"replace","value":[{"text":"MBMCustomRasterSourceTileStatus","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatus\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileStatus"}]}]}]}