{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"undefined"}]}]}],"kind":"symbol","metadata":{"role":"symbol","symbolKind":"case","title":"StylePropertyValueKind.undefined","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"undefined","kind":"identifier"}],"externalID":"c:@E@MBMStylePropertyValueKind@MBMStylePropertyValueKindUndefined","modules":[{"name":"MapboxMaps"}],"navigatorTitle":[{"kind":"identifier","text":"MBMStylePropertyValueKindUndefined"}],"roleHeading":"Case"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/mapboxmaps\/stylepropertyvaluekind\/undefined"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/stylepropertyvaluekind\/undefined"]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer-Property-Values","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValueKind"]]},"sections":[],"abstract":[{"text":"The property value is not defined.","type":"text"}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValueKind\/undefined","interfaceLanguage":"swift"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePropertyValueKind":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"StylePropertyValueKind","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Describes the kind of a style property value.","type":"text"}],"type":"topic","kind":"symbol","title":"StylePropertyValueKind","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValueKind","navigatorTitle":[{"text":"StylePropertyValueKind","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/stylepropertyvaluekind"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePropertyValueKind/undefined":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"undefined"}],"type":"topic","abstract":[{"text":"The property value is not defined.","type":"text"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/stylepropertyvaluekind\/undefined","title":"StylePropertyValueKind.undefined","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBMStylePropertyValueKindUndefined"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValueKind\/undefined"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","abstract":[],"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","kind":"article","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layer-Property-Values":{"abstract":[],"type":"topic","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/layer-property-values","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer-Property-Values","title":"Layer Property Values"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","title":"MapboxMaps"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"MBMStylePropertyValueKindUndefined","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"MBMStylePropertyValueKindUndefined"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"MBMStylePropertyValueKindUndefined"}]}]},"op":"replace"},{"value":"MBMStylePropertyValueKind","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValueKind\/title"},{"value":[{"text":"MBMStylePropertyValueKind","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValueKind\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValueKind\/navigatorTitle","value":[{"kind":"identifier","text":"MBMStylePropertyValueKind"}],"op":"replace"},{"value":"MBMStylePropertyValueKindUndefined","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValueKind~1undefined\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValueKind~1undefined\/fragments","value":[{"kind":"identifier","text":"MBMStylePropertyValueKindUndefined"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}