{"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CumulativeRenderingStatistics"]]},"variants":[{"paths":["\/documentation\/mapboxmaps\/mbmcumulativerenderingstatistics\/texturebytes"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"property","modules":[{"name":"MapboxMaps"}],"externalID":"c:objc(cs)MBMCumulativeRenderingStatistics(py)textureBytes","role":"symbol","title":"textureBytes","fragments":[{"text":"textureBytes","kind":"identifier"}],"navigatorTitle":[{"text":"textureBytes","kind":"identifier"}],"roleHeading":"Instance Property"},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCumulativeRenderingStatistics\/textureBytes"},"abstract":[{"text":"The amount of texture memory in use at the end of the collection window.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"textureBytes","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMCumulativeRenderingStatistics/textureBytes":{"role":"symbol","fragments":[{"text":"textureBytes","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCumulativeRenderingStatistics\/textureBytes","title":"textureBytes","url":"\/documentation\/mapboxmaps\/mbmcumulativerenderingstatistics\/texturebytes","kind":"symbol","abstract":[{"text":"The amount of texture memory in use at the end of the collection window.","type":"text"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","kind":"article","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Performance":{"abstract":[],"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","url":"\/documentation\/mapboxmaps\/performance","type":"topic","title":"Performance and investigations","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CumulativeRenderingStatistics":{"type":"topic","abstract":[],"url":"\/documentation\/mapboxmaps\/cumulativerenderingstatistics","title":"CumulativeRenderingStatistics","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CumulativeRenderingStatistics","navigatorTitle":[{"text":"CumulativeRenderingStatistics","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CumulativeRenderingStatistics","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","url":"\/documentation\/mapboxmaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","title":"MapboxMaps"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CumulativeRenderingStatistics\/title","op":"replace","value":"MBMCumulativeRenderingStatistics"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CumulativeRenderingStatistics\/fragments","op":"replace","value":[{"text":"MBMCumulativeRenderingStatistics","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CumulativeRenderingStatistics\/navigatorTitle","op":"replace","value":[{"text":"MBMCumulativeRenderingStatistics","kind":"identifier"}]}]}]}