{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestDataSourceType"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"MBMRequestDataSourceTypeFileSystem"}],"role":"symbol","modules":[{"name":"MapboxMaps"}],"externalID":"c:@E@MBMRequestDataSourceType@MBMRequestDataSourceTypeFileSystem","title":"RequestDataSourceType.fileSystem","symbolKind":"case","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"fileSystem","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fileSystem","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestDataSourceType\/fileSystem"},"abstract":[{"type":"text","text":"The resource is requested from the file system."}],"variants":[{"paths":["\/documentation\/mapboxmaps\/requestdatasourcetype\/filesystem"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/requestdatasourcetype\/filesystem"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"abstract":[{"type":"text","text":"The simplified diagram of the events emitted by the map is displayed below."}],"type":"topic","kind":"article","role":"collectionGroup","title":"Map events","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","url":"\/documentation\/mapboxmaps\/events"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestDataSourceType":{"abstract":[{"text":"The enumeration defines the type of data source.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"RequestDataSourceType","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/requestdatasourcetype","kind":"symbol","title":"RequestDataSourceType","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestDataSourceType","type":"topic","navigatorTitle":[{"text":"RequestDataSourceType","kind":"identifier"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article","role":"collection","title":"MapboxMaps Documentation","type":"topic","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","title":"MapboxMaps","kind":"symbol","role":"collection","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestDataSourceType/fileSystem":{"navigatorTitle":[{"text":"MBMRequestDataSourceTypeFileSystem","kind":"identifier"}],"abstract":[{"type":"text","text":"The resource is requested from the file system."}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestDataSourceType\/fileSystem","role":"symbol","title":"RequestDataSourceType.fileSystem","url":"\/documentation\/mapboxmaps\/requestdatasourcetype\/filesystem","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileSystem"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"MBMRequestDataSourceTypeFileSystem"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"value":[{"text":"MBMRequestDataSourceTypeFileSystem","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"MBMRequestDataSourceTypeFileSystem","kind":"identifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestDataSourceType\/title","value":"MBMRequestDataSourceType"},{"value":[{"kind":"identifier","text":"MBMRequestDataSourceType"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestDataSourceType\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestDataSourceType\/navigatorTitle","value":[{"text":"MBMRequestDataSourceType","kind":"identifier"}],"op":"replace"},{"value":"MBMRequestDataSourceTypeFileSystem","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestDataSourceType~1fileSystem\/title","op":"replace"},{"op":"replace","value":[{"text":"MBMRequestDataSourceTypeFileSystem","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestDataSourceType~1fileSystem\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}