{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestDataSourceType"]]},"metadata":{"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"resourceLoader"}],"navigatorTitle":[{"kind":"identifier","text":"MBMRequestDataSourceTypeResourceLoader"}],"externalID":"c:@E@MBMRequestDataSourceType@MBMRequestDataSourceTypeResourceLoader","modules":[{"name":"MapboxMaps"}],"symbolKind":"case","title":"RequestDataSourceType.resourceLoader","role":"symbol"},"abstract":[{"text":"The resource is requested from the main resource loader.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The main resource loader will delegate the request to the best-matched data source."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"resourceLoader","kind":"identifier"}]}]}],"sections":[],"variants":[{"paths":["\/documentation\/mapboxmaps\/requestdatasourcetype\/resourceloader"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/requestdatasourcetype\/resourceloader"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestDataSourceType\/resourceLoader"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestDataSourceType/resourceLoader":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"resourceLoader"}],"navigatorTitle":[{"text":"MBMRequestDataSourceTypeResourceLoader","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The resource is requested from the main resource loader."},{"text":" ","type":"text"},{"type":"text","text":"The main resource loader will delegate the request to the best-matched data source."}],"title":"RequestDataSourceType.resourceLoader","url":"\/documentation\/mapboxmaps\/requestdatasourcetype\/resourceloader","type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestDataSourceType\/resourceLoader"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"role":"collectionGroup","title":"Map events","url":"\/documentation\/mapboxmaps\/events","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","kind":"article","abstract":[{"text":"The simplified diagram of the events emitted by the map is displayed below.","type":"text"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","role":"collection","abstract":[],"type":"topic","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestDataSourceType":{"abstract":[{"text":"The enumeration defines the type of data source.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestDataSourceType","title":"RequestDataSourceType","url":"\/documentation\/mapboxmaps\/requestdatasourcetype","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RequestDataSourceType"}],"type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"RequestDataSourceType","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"MBMRequestDataSourceTypeResourceLoader","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MBMRequestDataSourceTypeResourceLoader","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"MBMRequestDataSourceTypeResourceLoader","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestDataSourceType~1resourceLoader\/title","op":"replace","value":"MBMRequestDataSourceTypeResourceLoader"},{"value":[{"text":"MBMRequestDataSourceTypeResourceLoader","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestDataSourceType~1resourceLoader\/fragments","op":"replace"},{"value":"MBMRequestDataSourceType","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestDataSourceType\/title","op":"replace"},{"value":[{"text":"MBMRequestDataSourceType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestDataSourceType\/fragments"},{"op":"replace","value":[{"text":"MBMRequestDataSourceType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestDataSourceType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}