{"metadata":{"role":"symbol","modules":[{"name":"MapboxMaps"}],"externalID":"c:objc(cs)MBMRenderFrameFinished(py)renderMode","navigatorTitle":[{"kind":"identifier","text":"renderMode"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"renderMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"RenderModeType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMRenderModeType"}],"roleHeading":"Instance Property","title":"renderMode"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinished"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"renderMode"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@MBMRenderModeType","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderModeType","text":"RenderModeType","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"The property tells whether the "},{"code":"map","type":"codeVoice"},{"text":" rendered the frame with all required","type":"text"},{"text":" ","type":"text"},{"text":"or partially available data.","type":"text"}],"variants":[{"paths":["\/documentation\/mapboxmaps\/renderframefinished\/rendermode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/renderframefinished\/rendermode"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinished\/renderMode","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderModeType":{"role":"symbol","abstract":[{"text":"The enumeration defines the rendering mode for the rendered frame.","type":"text"}],"url":"\/documentation\/mapboxmaps\/rendermodetype","navigatorTitle":[{"text":"RenderModeType","kind":"identifier"}],"title":"RenderModeType","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"RenderModeType","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderModeType"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"url":"\/documentation\/mapboxmaps\/events","role":"collectionGroup","kind":"article","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","abstract":[{"type":"text","text":"The simplified diagram of the events emitted by the map is displayed below."}],"title":"Map events"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","role":"collection","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderFrameFinished/renderMode":{"title":"renderMode","role":"symbol","abstract":[{"type":"text","text":"The property tells whether the "},{"code":"map","type":"codeVoice"},{"text":" rendered the frame with all required","type":"text"},{"text":" ","type":"text"},{"text":"or partially available data.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinished\/renderMode","navigatorTitle":[{"kind":"identifier","text":"renderMode"}],"url":"\/documentation\/mapboxmaps\/renderframefinished\/rendermode","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"renderMode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@MBMRenderModeType","kind":"typeIdentifier","text":"RenderModeType"}],"kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderFrameFinished":{"title":"RenderFrameFinished","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"RenderFrameFinished","kind":"identifier"}],"navigatorTitle":[{"text":"RenderFrameFinished","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinished","url":"\/documentation\/mapboxmaps\/renderframefinished","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"map"},{"text":" finished rendering a frame.","type":"text"}],"role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","title":"MapboxMaps Documentation","url":"\/documentation\/overview","type":"topic","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"renderMode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"renderMode"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"MBMRenderModeType","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderModeType","preciseIdentifier":"c:@E@MBMRenderModeType"},{"kind":"text","text":" "},{"text":"renderMode","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MBMRenderModeType","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderModeType\/title"},{"value":[{"kind":"identifier","text":"MBMRenderModeType"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderModeType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderModeType\/navigatorTitle","value":[{"kind":"identifier","text":"MBMRenderModeType"}]},{"op":"replace","value":"renderMode","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinished~1renderMode\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinished~1renderMode\/fragments","op":"replace","value":[{"text":"renderMode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinished\/title","value":"MBMRenderFrameFinished"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinished\/fragments","value":[{"kind":"identifier","text":"MBMRenderFrameFinished"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinished\/navigatorTitle","value":[{"kind":"identifier","text":"MBMRenderFrameFinished"}],"op":"replace"}]}]}