{"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/resetFileLoggingLevelForCategory(forCategory:)","interfaceLanguage":"swift"},"metadata":{"role":"symbol","navigatorTitle":[{"text":"resetFileLoggingLevelForCategoryForCategory:","kind":"identifier"}],"modules":[{"name":"MapboxCommon"}],"symbolKind":"method","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resetFileLoggingLevelForCategory","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forCategory","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Type Method","externalID":"c:objc(cs)MBXExperimentalPersistentLogConfiguration(cm)resetFileLoggingLevelForCategoryForCategory:","title":"resetFileLoggingLevelForCategory(forCategory:)"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration"]]},"abstract":[{"type":"text","text":"Reset file logging level for a category of logs."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resetFileLoggingLevelForCategory","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forCategory","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"category","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Category for which to reset the logging level"}]}],"name":"category"}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/persistentlogconfiguration\/resetfilelogginglevelforcategory(forcategory:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/persistentlogconfiguration\/resetfilelogginglevelforcategory(forcategory:)"]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","type":"topic","abstract":[],"role":"collection","kind":"symbol","url":"\/documentation\/mapboxcommon","title":"MapboxCommon"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"type":"topic","url":"\/documentation\/overview","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PersistentLogConfiguration":{"navigatorTitle":[{"text":"PersistentLogConfiguration","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PersistentLogConfiguration","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/mapboxcommon\/persistentlogconfiguration","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration","abstract":[{"text":"Settings to configure behavior of persistent log","type":"text"}],"title":"PersistentLogConfiguration"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PersistentLogConfiguration/resetFileLoggingLevelForCategory(forCategory:)":{"url":"\/documentation\/mapboxcommon\/persistentlogconfiguration\/resetfilelogginglevelforcategory(forcategory:)","title":"resetFileLoggingLevelForCategory(forCategory:)","kind":"symbol","abstract":[{"type":"text","text":"Reset file logging level for a category of logs."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resetFileLoggingLevelForCategory","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forCategory","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/resetFileLoggingLevelForCategory(forCategory:)","navigatorTitle":[{"text":"resetFileLoggingLevelForCategoryForCategory:","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","value":"resetFileLoggingLevelForCategoryForCategory:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"resetFileLoggingLevelForCategoryForCategory:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"resetFileLoggingLevelForCategoryForCategory:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"category","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"category","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Category for which to reset the logging level"}]}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration\/title","value":"MBXExperimentalPersistentLogConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration\/fragments","value":[{"kind":"identifier","text":"MBXExperimentalPersistentLogConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"MBXExperimentalPersistentLogConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1resetFileLoggingLevelForCategory(forCategory:)\/title","value":"resetFileLoggingLevelForCategoryForCategory:","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"resetFileLoggingLevelForCategoryForCategory:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1resetFileLoggingLevelForCategory(forCategory:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}