{"variants":[{"paths":["\/documentation\/mapboxcommon\/persistentlogconfiguration\/setfilelogginglevelforupto(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxcommon\/persistentlogconfiguration\/setfilelogginglevelforupto(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setFileLoggingLevelForUpTo","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"setFileLoggingLevelForUpTo:","kind":"identifier"}],"symbolKind":"method","externalID":"c:objc(cs)MBXExperimentalPersistentLogConfiguration(cm)setFileLoggingLevelForUpTo:","title":"setFileLoggingLevelForUpTo(_:)","role":"symbol","modules":[{"name":"MapboxCommon"}],"roleHeading":"Type Method"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration"]]},"kind":"symbol","abstract":[{"type":"text","text":"Set file logging level."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/setFileLoggingLevelForUpTo(_:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setFileLoggingLevelForUpTo","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"upTo","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"upTo","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Log messages with lower severity than this parameter will be filtered out. If"},{"type":"text","text":" "},{"type":"text","text":"the parameter is empty, all log messages are filtered out, i.e., logging to file is disabled."},{"type":"text","text":" "},{"type":"text","text":"Default is unset, meaning logging to file is disabled."}]}]}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PersistentLogConfiguration/setFileLoggingLevelForUpTo(_:)":{"kind":"symbol","type":"topic","title":"setFileLoggingLevelForUpTo(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setFileLoggingLevelForUpTo"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?)"}],"abstract":[{"text":"Set file logging level.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"setFileLoggingLevelForUpTo:"}],"url":"\/documentation\/mapboxcommon\/persistentlogconfiguration\/setfilelogginglevelforupto(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/setFileLoggingLevelForUpTo(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PersistentLogConfiguration":{"navigatorTitle":[{"text":"PersistentLogConfiguration","kind":"identifier"}],"title":"PersistentLogConfiguration","url":"\/documentation\/mapboxcommon\/persistentlogconfiguration","role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration","abstract":[{"type":"text","text":"Settings to configure behavior of persistent log"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PersistentLogConfiguration","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"type":"topic","title":"MapboxCommon","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","role":"collection","kind":"symbol","url":"\/documentation\/mapboxcommon","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","role":"collection","type":"topic","abstract":[],"title":"MapboxMaps Documentation","kind":"article"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","value":"setFileLoggingLevelForUpTo:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"setFileLoggingLevelForUpTo:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"setFileLoggingLevelForUpTo:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"upTo"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"upTo","content":[{"inlineContent":[{"type":"text","text":"Log messages with lower severity than this parameter will be filtered out. If"},{"type":"text","text":" "},{"type":"text","text":"the parameter is empty, all log messages are filtered out, i.e., logging to file is disabled."},{"type":"text","text":" "},{"type":"text","text":"Default is unset, meaning logging to file is disabled."}],"type":"paragraph"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1setFileLoggingLevelForUpTo(_:)\/title","value":"setFileLoggingLevelForUpTo:","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1setFileLoggingLevelForUpTo(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setFileLoggingLevelForUpTo:"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration\/title","op":"replace","value":"MBXExperimentalPersistentLogConfiguration"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration\/fragments","op":"replace","value":[{"text":"MBXExperimentalPersistentLogConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration\/navigatorTitle","op":"replace","value":[{"text":"MBXExperimentalPersistentLogConfiguration","kind":"identifier"}]}]}]}