{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration"]]},"metadata":{"roleHeading":"Type Method","navigatorTitle":[{"text":"setFileLoggingLevelForCategoryForCategory:upTo:","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"MapboxCommon"}],"externalID":"c:objc(cs)MBXExperimentalPersistentLogConfiguration(cm)setFileLoggingLevelForCategoryForCategory:upTo:","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setFileLoggingLevelForCategoryForCategory","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"upTo","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?)","kind":"text"}],"title":"setFileLoggingLevelForCategoryForCategory(_:upTo:)"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/setFileLoggingLevelForCategoryForCategory(_:upTo:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setFileLoggingLevelForCategoryForCategory"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"category"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"upTo","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?)","kind":"text"}]}]},{"parameters":[{"content":[{"inlineContent":[{"text":"Log category to be logged to disk","type":"text"}],"type":"paragraph"}],"name":"category"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Log messages with lower severity than this parameter will be filtered out. If"},{"type":"text","text":" "},{"type":"text","text":"the parameter is empty, all log messages are filtered out, i.e., logging to file is disabled."},{"type":"text","text":" "},{"type":"text","text":"Default is unset, meaning it follows the general FileLoggingLevel setting"}]}],"name":"upTo"}],"kind":"parameters"}],"abstract":[{"text":"Set file logging level for a category of logs.","type":"text"}],"variants":[{"paths":["\/documentation\/mapboxcommon\/persistentlogconfiguration\/setfilelogginglevelforcategoryforcategory(_:upto:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxcommon\/persistentlogconfiguration\/setfilelogginglevelforcategoryforcategory(_:upto:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PersistentLogConfiguration/setFileLoggingLevelForCategoryForCategory(_:upTo:)":{"title":"setFileLoggingLevelForCategoryForCategory(_:upTo:)","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/setFileLoggingLevelForCategoryForCategory(_:upTo:)","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setFileLoggingLevelForCategoryForCategory","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"upTo","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?)","kind":"text"}],"url":"\/documentation\/mapboxcommon\/persistentlogconfiguration\/setfilelogginglevelforcategoryforcategory(_:upto:)","navigatorTitle":[{"text":"setFileLoggingLevelForCategoryForCategory:upTo:","kind":"identifier"}],"abstract":[{"type":"text","text":"Set file logging level for a category of logs."}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PersistentLogConfiguration":{"navigatorTitle":[{"text":"PersistentLogConfiguration","kind":"identifier"}],"title":"PersistentLogConfiguration","url":"\/documentation\/mapboxcommon\/persistentlogconfiguration","role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration","abstract":[{"type":"text","text":"Settings to configure behavior of persistent log"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PersistentLogConfiguration","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","role":"collection","type":"topic","abstract":[],"title":"MapboxMaps Documentation","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"type":"topic","title":"MapboxCommon","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","role":"collection","kind":"symbol","url":"\/documentation\/mapboxcommon","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"setFileLoggingLevelForCategoryForCategory:upTo:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"setFileLoggingLevelForCategoryForCategory:upTo:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"setFileLoggingLevelForCategoryForCategory:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"category"},{"kind":"text","text":" "},{"kind":"identifier","text":"upTo:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"upTo"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"category","content":[{"inlineContent":[{"type":"text","text":"Log category to be logged to disk"}],"type":"paragraph"}]},{"name":"upTo","content":[{"inlineContent":[{"type":"text","text":"Log messages with lower severity than this parameter will be filtered out. If"},{"type":"text","text":" "},{"type":"text","text":"the parameter is empty, all log messages are filtered out, i.e., logging to file is disabled."},{"type":"text","text":" "},{"type":"text","text":"Default is unset, meaning it follows the general FileLoggingLevel setting"}],"type":"paragraph"}]}],"kind":"parameters"}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1setFileLoggingLevelForCategoryForCategory(_:upTo:)\/title","value":"setFileLoggingLevelForCategoryForCategory:upTo:"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1setFileLoggingLevelForCategoryForCategory(_:upTo:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"setFileLoggingLevelForCategoryForCategory:upTo:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration\/title","value":"MBXExperimentalPersistentLogConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration\/fragments","value":[{"kind":"identifier","text":"MBXExperimentalPersistentLogConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"MBXExperimentalPersistentLogConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}