{"topicSections":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedRenderedFeature\/layers","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedRenderedFeature\/queriedFeature"],"title":"Instance Properties"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"QueriedRenderedFeature","kind":"identifier"}],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedRenderedFeature","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/mapboxmaps\/queriedrenderedfeature"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/queriedrenderedfeature"]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs"]]},"kind":"symbol","sections":[],"abstract":[{"text":"Represents query result that is returned in QueryRenderedFeaturesCallback.","type":"text"}],"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"QueriedRenderedFeature","kind":"identifier"}],"title":"QueriedRenderedFeature","roleHeading":"Class","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"QueriedRenderedFeature"}],"symbolKind":"class","modules":[{"name":"MapboxMaps"}],"externalID":"c:objc(cs)MBMQueriedRenderedFeature"},"seeAlsoSections":[{"generated":true,"title":"Query features on the map","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceQueryOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedFeature","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedSourceFeature","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AnnotatedFeature"],"anchor":"Query-features-on-the-map"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","kind":"symbol","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/QueriedRenderedFeature":{"kind":"symbol","abstract":[{"type":"text","text":"Represents query result that is returned in QueryRenderedFeaturesCallback."}],"url":"\/documentation\/mapboxmaps\/queriedrenderedfeature","type":"topic","title":"QueriedRenderedFeature","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedRenderedFeature","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"QueriedRenderedFeature","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"QueriedRenderedFeature"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/QueriedRenderedFeature/queriedFeature":{"abstract":[{"type":"text","text":"Feature returned by the query."}],"navigatorTitle":[{"text":"queriedFeature","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedRenderedFeature\/queriedFeature","kind":"symbol","title":"queriedFeature","type":"topic","url":"\/documentation\/mapboxmaps\/queriedrenderedfeature\/queriedfeature","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"queriedFeature","kind":"identifier"},{"kind":"text","text":": "},{"text":"QueriedFeature","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMQueriedFeature"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceQueryOptions":{"abstract":[{"type":"text","text":"Options for querying source features."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SourceQueryOptions","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/sourcequeryoptions","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceQueryOptions","kind":"symbol","role":"symbol","title":"SourceQueryOptions","navigatorTitle":[{"kind":"identifier","text":"SourceQueryOptions"}]},"doc://com.mapbox.MapboxMaps/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP"},"doc://com.mapbox.MapboxMaps/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH"},"doc://com.mapbox.MapboxMaps/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/QueriedSourceFeature":{"abstract":[{"text":"Represents query result that is returned in QuerySourceFeaturesCallback.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"QueriedSourceFeature"}],"url":"\/documentation\/mapboxmaps\/queriedsourcefeature","type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedSourceFeature","role":"symbol","title":"QueriedSourceFeature","navigatorTitle":[{"text":"QueriedSourceFeature","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP"},"doc://com.mapbox.MapboxMaps/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"kind":"article","type":"topic","title":"MapboxMap","abstract":[],"url":"\/documentation\/mapboxmaps\/mapboxmap-apis","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/QueriedRenderedFeature/layers":{"url":"\/documentation\/mapboxmaps\/queriedrenderedfeature\/layers","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"layers"}],"title":"layers","abstract":[{"text":"An array of layer Ids for the queried feature.","type":"text"},{"text":" ","type":"text"},{"text":"If the feature has been rendered in multiple layers, multiple Ids will be provided.","type":"text"},{"text":" ","type":"text"},{"text":"If the feature is only rendered in one layer, a single Id will be provided.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"layers"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedRenderedFeature\/layers"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderedQueryOptions":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryOptions","url":"\/documentation\/mapboxmaps\/renderedqueryoptions","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"RenderedQueryOptions","kind":"identifier"}],"navigatorTitle":[{"text":"RenderedQueryOptions","kind":"identifier"}],"title":"RenderedQueryOptions","kind":"symbol","abstract":[{"text":"Options for querying rendered features.","type":"text"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AnnotatedFeature":{"kind":"symbol","abstract":[{"type":"text","text":"Represents either a GeoJSON geometry or an annotated layer feature."}],"url":"\/documentation\/mapboxmaps\/annotatedfeature","type":"topic","title":"AnnotatedFeature","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AnnotatedFeature","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AnnotatedFeature","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AnnotatedFeature"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/QueriedFeature":{"abstract":[{"type":"text","text":"Represents queried feature that is returned through "},{"type":"codeVoice","code":"QueriedRenderedFeature"},{"text":" or ","type":"text"},{"type":"codeVoice","code":"QueriedSourceFeature"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"QueriedFeature","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/queriedfeature","type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedFeature","role":"symbol","title":"QueriedFeature","navigatorTitle":[{"text":"QueriedFeature","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","url":"\/documentation\/overview","kind":"article","abstract":[]},"doc://com.mapbox.MapboxMaps/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"MBMQueriedRenderedFeature","path":"\/metadata\/title","op":"replace"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"MBMQueriedRenderedFeature","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":[{"text":"MBMQueriedRenderedFeature","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedRenderedFeature\/layers","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedRenderedFeature\/queriedFeature"]}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"}],"op":"replace"},{"op":"replace","path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceQueryOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedFeature","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedSourceFeature","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryOptions"],"generated":true,"title":"Query features on the map","anchor":"Query-features-on-the-map"}]},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBMQueriedRenderedFeature"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedRenderedFeature\/title","value":"MBMQueriedRenderedFeature","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedRenderedFeature\/fragments","value":[{"text":"MBMQueriedRenderedFeature","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"MBMQueriedRenderedFeature","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedRenderedFeature\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedRenderedFeature~1queriedFeature\/title","value":"queriedFeature"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedRenderedFeature~1queriedFeature\/fragments","value":[{"kind":"identifier","text":"queriedFeature"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceQueryOptions\/title","value":"MBMSourceQueryOptions","op":"replace"},{"op":"replace","value":[{"text":"MBMSourceQueryOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceQueryOptions\/fragments"},{"value":[{"text":"MBMSourceQueryOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceQueryOptions\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedSourceFeature\/title","value":"MBMQueriedSourceFeature","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedSourceFeature\/fragments","value":[{"text":"MBMQueriedSourceFeature","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"MBMQueriedSourceFeature"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedSourceFeature\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedRenderedFeature~1layers\/title","value":"layers","op":"replace"},{"value":[{"kind":"identifier","text":"layers"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedRenderedFeature~1layers\/fragments"},{"op":"replace","value":"MBMRenderedQueryOptions","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderedQueryOptions\/title"},{"value":[{"text":"MBMRenderedQueryOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderedQueryOptions\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderedQueryOptions\/navigatorTitle","value":[{"text":"MBMRenderedQueryOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedFeature\/title","op":"replace","value":"MBMQueriedFeature"},{"op":"replace","value":[{"kind":"identifier","text":"MBMQueriedFeature"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedFeature\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedFeature\/navigatorTitle","value":[{"text":"MBMQueriedFeature","kind":"identifier"}],"op":"replace"}]}]}