{"schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CircleElevationReference\/init(rawValue:)"],"generated":true,"anchor":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CircleElevationReference\/rawValue"],"generated":true,"anchor":"Instance-Properties"},{"title":"Type Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CircleElevationReference\/hdRoadMarkup","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CircleElevationReference\/none"],"generated":true,"anchor":"Type-Properties"},{"title":"Default Implementations","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CircleElevationReference\/Equatable-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CircleElevationReference\/RawRepresentable-Implementations"],"generated":true,"anchor":"Default-Implementations"}],"relationshipsSections":[{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/Se","doc:\/\/com.mapbox.MapboxMaps\/SE","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH","doc:\/\/com.mapbox.MapboxMaps\/SY","doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"],"kind":"relationships"}],"seeAlsoSections":[{"title":"Layer Property Values","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Value","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Anchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CirclePitchAlignment","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CirclePitchScale","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CircleTranslateAnchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillExtrusionTranslateAnchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillTranslateAnchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeIlluminationAnchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconAnchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconPitchAlignment","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconRotationAlignment","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconTextFit","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconTranslateAnchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineCap","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineJoin","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineTranslateAnchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterResampling","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResolvedImage","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResolvedImageData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValue","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValueKind","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SkyType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleColor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleTransition","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolPlacement","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolZOrder","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextAnchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextJustify","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextPitchAlignment","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextRotationAlignment","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextTransform","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextTranslateAnchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextWritingMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Visibility","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TransitionOptions-swift.struct","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelScaleMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolElevationReference","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/BackgroundPitchAlignment","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillExtrusionBaseAlignment","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillExtrusionHeightAlignment","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillElevationReference","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineElevationReference","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineWidthUnit","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelElevationReference","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageContent","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageStretches"],"generated":true,"anchor":"Layer-Property-Values"}],"sections":[],"metadata":{"roleHeading":"Structure","title":"CircleElevationReference","navigatorTitle":[{"text":"CircleElevationReference","kind":"identifier"}],"symbolKind":"struct","externalID":"s:10MapboxMaps24CircleElevationReferenceV","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CircleElevationReference","kind":"identifier"}],"role":"symbol","modules":[{"name":"MapboxMaps"}],"tags":[{"type":"spi","text":"SPI"}]},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CircleElevationReference"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CircleElevationReference"},"abstract":[{"type":"text","text":"Selects the base of circle-elevation. Some modes might require precomputed elevation data in the tileset."}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer-Property-Values"]]},"variants":[{"paths":["\/documentation\/mapboxmaps\/circleelevationreference"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Visibility":{"url":"\/documentation\/mapboxmaps\/visibility","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Visibility"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Visibility","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Visibility"}],"title":"Visibility"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","abstract":[],"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","type":"topic","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CirclePitchAlignment":{"url":"\/documentation\/mapboxmaps\/circlepitchalignment","title":"CirclePitchAlignment","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CirclePitchAlignment","navigatorTitle":[{"text":"CirclePitchAlignment","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CirclePitchAlignment","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Orientation of circle when map is pitched."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LineJoin":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LineJoin"}],"url":"\/documentation\/mapboxmaps\/linejoin","abstract":[{"type":"text","text":"The display of lines when joining."}],"role":"symbol","title":"LineJoin","kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineJoin","navigatorTitle":[{"kind":"identifier","text":"LineJoin"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CircleElevationReference/none":{"abstract":[{"type":"text","text":"Elevated rendering is disabled."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CircleElevationReference","preciseIdentifier":"s:10MapboxMaps24CircleElevationReferenceV","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CircleElevationReference\/none","tags":[{"text":"SPI","type":"spi"}],"url":"\/documentation\/mapboxmaps\/circleelevationreference\/none","type":"topic","role":"symbol","title":"none"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/BackgroundPitchAlignment":{"kind":"symbol","navigatorTitle":[{"text":"BackgroundPitchAlignment","kind":"identifier"}],"tags":[{"type":"spi","text":"SPI"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/BackgroundPitchAlignment","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BackgroundPitchAlignment","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/backgroundpitchalignment","title":"BackgroundPitchAlignment","abstract":[{"type":"text","text":"Orientation of background layer."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelScaleMode":{"url":"\/documentation\/mapboxmaps\/modelscalemode","type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelScaleMode","kind":"symbol","abstract":[{"type":"text","text":"Defines scaling mode. Only applies to location-indicator type layers."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ModelScaleMode","kind":"identifier"}],"navigatorTitle":[{"text":"ModelScaleMode","kind":"identifier"}],"tags":[{"type":"spi","text":"SPI"}],"title":"ModelScaleMode"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelType":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ModelType"}],"url":"\/documentation\/mapboxmaps\/modeltype","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelType","role":"symbol","title":"ModelType","abstract":[{"text":"Defines rendering behavior of model in respect to other 3D scene objects.","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ModelType"}],"kind":"symbol","tags":[{"text":"SPI","type":"spi"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/IconRotationAlignment":{"abstract":[{"type":"text","text":"In combination with "},{"code":"symbol-placement","type":"codeVoice"},{"type":"text","text":", determines the rotation behavior of icons."}],"url":"\/documentation\/mapboxmaps\/iconrotationalignment","role":"symbol","title":"IconRotationAlignment","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconRotationAlignment","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IconRotationAlignment"}],"navigatorTitle":[{"kind":"identifier","text":"IconRotationAlignment"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layer-Property-Values":{"kind":"article","url":"\/documentation\/mapboxmaps\/layer-property-values","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer-Property-Values","type":"topic","abstract":[],"title":"Layer Property Values","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LineCap":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineCap","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LineCap"}],"url":"\/documentation\/mapboxmaps\/linecap","role":"symbol","abstract":[{"type":"text","text":"The display of line endings."}],"title":"LineCap","navigatorTitle":[{"kind":"identifier","text":"LineCap"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePropertyValueKind":{"kind":"symbol","navigatorTitle":[{"text":"StylePropertyValueKind","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValueKind","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StylePropertyValueKind","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/stylepropertyvaluekind","title":"StylePropertyValueKind","abstract":[{"text":"Describes the kind of a style property value.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ImageStretches":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageStretches","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageStretches","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/imagestretches","role":"symbol","abstract":[{"type":"text","text":"Describes the image stretch areas."}],"title":"ImageStretches","navigatorTitle":[{"text":"ImageStretches","kind":"identifier"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleColor":{"type":"topic","title":"StyleColor","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleColor","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"StyleColor"}],"abstract":[{"type":"text","text":"Represents a color as defined by the "},{"isActive":true,"type":"reference","identifier":"https:\/\/docs.mapbox.com\/style-spec\/reference\/types\/#color"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/stylecolor","navigatorTitle":[{"kind":"identifier","text":"StyleColor"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CircleElevationReference":{"type":"topic","title":"CircleElevationReference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CircleElevationReference","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CircleElevationReference"}],"abstract":[{"type":"text","text":"Selects the base of circle-elevation. Some modes might require precomputed elevation data in the tileset."}],"role":"symbol","url":"\/documentation\/mapboxmaps\/circleelevationreference","tags":[{"type":"spi","text":"SPI"}],"navigatorTitle":[{"kind":"identifier","text":"CircleElevationReference"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TextJustify":{"kind":"symbol","abstract":[{"text":"Text justification options.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextJustify","url":"\/documentation\/mapboxmaps\/textjustify","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TextJustify"}],"role":"symbol","type":"topic","title":"TextJustify","navigatorTitle":[{"kind":"identifier","text":"TextJustify"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CircleElevationReference/hdRoadMarkup":{"abstract":[{"text":"Elevated rendering is enabled. Use this mode to describe additive and stackable features that should exist only on top of road polygons.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CircleElevationReference\/hdRoadMarkup","url":"\/documentation\/mapboxmaps\/circleelevationreference\/hdroadmarkup","kind":"symbol","title":"hdRoadMarkup","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"hdRoadMarkup"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps24CircleElevationReferenceV","text":"CircleElevationReference"}],"tags":[{"text":"SPI","type":"spi"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CircleElevationReference/init(rawValue:)":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/circleelevationreference\/init(rawvalue:)","type":"topic","abstract":[],"tags":[{"type":"spi","text":"SPI"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"init(rawValue:)","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CircleElevationReference\/init(rawValue:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePropertyValue":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValue","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StylePropertyValue"}],"navigatorTitle":[{"kind":"identifier","text":"StylePropertyValue"}],"title":"StylePropertyValue","url":"\/documentation\/mapboxmaps\/stylepropertyvalue","abstract":[{"type":"text","text":"Holds a style property value with meta data."}],"type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SymbolElevationReference":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/symbolelevationreference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolElevationReference","abstract":[{"text":"Selects the base of symbol-elevation.","type":"text"}],"title":"SymbolElevationReference","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SymbolElevationReference"}],"navigatorTitle":[{"kind":"identifier","text":"SymbolElevationReference"}],"type":"topic","role":"symbol","tags":[{"text":"SPI","type":"spi"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LineTranslateAnchor":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineTranslateAnchor","url":"\/documentation\/mapboxmaps\/linetranslateanchor","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"LineTranslateAnchor"}],"abstract":[{"type":"text","text":"Controls the frame of reference for "},{"type":"codeVoice","code":"line-translate"},{"type":"text","text":"."}],"title":"LineTranslateAnchor","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LineTranslateAnchor"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FillTranslateAnchor":{"navigatorTitle":[{"kind":"identifier","text":"FillTranslateAnchor"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FillTranslateAnchor"}],"title":"FillTranslateAnchor","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillTranslateAnchor","type":"topic","abstract":[{"type":"text","text":"Controls the frame of reference for "},{"code":"fill-translate","type":"codeVoice"},{"type":"text","text":"."}],"url":"\/documentation\/mapboxmaps\/filltranslateanchor","role":"symbol","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TextWritingMode":{"url":"\/documentation\/mapboxmaps\/textwritingmode","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"TextWritingMode","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextWritingMode","navigatorTitle":[{"text":"TextWritingMode","kind":"identifier"}],"role":"symbol","abstract":[{"text":"The property allows control over a symbol’s orientation. Note that the property values act as a hint, so that a symbol whose language doesn’t support the provided orientation will be laid out in its natural orientation. Example: English point symbol will be rendered horizontally even if array value contains single ‘vertical’ enum value. For symbol with point placement, the order of elements in an array define priority order for the placement of an orientation variant. For symbol with line placement, the default text writing mode is either [‘horizontal’, ‘vertical’] or [‘vertical’, ‘horizontal’], the order doesn’t affect the placement.","type":"text"}],"title":"TextWritingMode"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TransitionOptions-swift.struct":{"role":"symbol","abstract":[{"type":"text","text":"The "},{"code":"TransitionOptions","type":"codeVoice"},{"type":"text","text":" control timing for the interpolation between a transitionable style"},{"type":"text","text":" "},{"type":"text","text":"property’s previous value and new value. These can be used to define the style default property"},{"type":"text","text":" "},{"type":"text","text":"transition behavior. Also, any transitionable style property may also have its own "},{"code":"-transition","type":"codeVoice"},{"type":"text","text":" "},{"type":"text","text":"property that defines specific transition timing for that specific layer property, overriding"},{"type":"text","text":" "},{"type":"text","text":"the global transition values."}],"title":"TransitionOptions","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TransitionOptions-swift.struct","url":"\/documentation\/mapboxmaps\/transitionoptions-swift.struct","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TransitionOptions"}],"navigatorTitle":[{"kind":"identifier","text":"TransitionOptions"}]},"doc://com.mapbox.MapboxMaps/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SY"},"doc://com.mapbox.MapboxMaps/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s8SendableP","title":"Swift.Sendable"},"doc://com.mapbox.MapboxMaps/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterResampling":{"abstract":[{"type":"text","text":"The resampling\/interpolation method to use for overscaling, also known as texture magnification filter"}],"title":"RasterResampling","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"RasterResampling"}],"navigatorTitle":[{"kind":"identifier","text":"RasterResampling"}],"url":"\/documentation\/mapboxmaps\/rasterresampling","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterResampling","kind":"symbol","type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/IconAnchor":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconAnchor","abstract":[{"type":"text","text":"Part of the icon placed closest to the anchor."}],"kind":"symbol","title":"IconAnchor","navigatorTitle":[{"kind":"identifier","text":"IconAnchor"}],"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IconAnchor"}],"url":"\/documentation\/mapboxmaps\/iconanchor","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TextRotationAlignment":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextRotationAlignment","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TextRotationAlignment"}],"title":"TextRotationAlignment","role":"symbol","abstract":[{"text":"In combination with ","type":"text"},{"code":"symbol-placement","type":"codeVoice"},{"text":", determines the rotation behavior of the individual glyphs forming the text.","type":"text"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/textrotationalignment","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TextRotationAlignment"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/IconPitchAlignment":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconPitchAlignment","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IconPitchAlignment"}],"role":"symbol","abstract":[{"text":"Orientation of icon when map is pitched.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"IconPitchAlignment"}],"title":"IconPitchAlignment","url":"\/documentation\/mapboxmaps\/iconpitchalignment","type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CircleElevationReference/rawValue":{"role":"symbol","type":"topic","abstract":[],"title":"rawValue","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CircleElevationReference\/rawValue","tags":[{"text":"SPI","type":"spi"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rawValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"url":"\/documentation\/mapboxmaps\/circleelevationreference\/rawvalue","kind":"symbol"},"doc://com.mapbox.MapboxMaps/SE":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SE","title":"Swift.Encodable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResolvedImageData":{"abstract":[],"type":"topic","url":"\/documentation\/mapboxmaps\/resolvedimagedata","kind":"symbol","title":"ResolvedImageData","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResolvedImageData"}],"navigatorTitle":[{"kind":"identifier","text":"ResolvedImageData"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResolvedImageData"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LineWidthUnit":{"navigatorTitle":[{"kind":"identifier","text":"LineWidthUnit"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineWidthUnit","title":"LineWidthUnit","url":"\/documentation\/mapboxmaps\/linewidthunit","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LineWidthUnit"}],"tags":[{"type":"spi","text":"SPI"}],"type":"topic","abstract":[{"type":"text","text":"Selects the unit of line-width. The same unit is automatically used for line-blur and line-offset. Note: This is an experimental property and might be removed in a future release."}]},"doc://com.mapbox.MapboxMaps/Se":{"title":"Swift.Decodable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/Se"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelElevationReference":{"abstract":[{"text":"Selects the base of the model. Some modes might require precomputed elevation data in the tileset.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelElevationReference","url":"\/documentation\/mapboxmaps\/modelelevationreference","role":"symbol","title":"ModelElevationReference","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ModelElevationReference"}],"navigatorTitle":[{"kind":"identifier","text":"ModelElevationReference"}],"tags":[{"type":"spi","text":"SPI"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LineElevationReference":{"title":"LineElevationReference","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineElevationReference","role":"symbol","url":"\/documentation\/mapboxmaps\/lineelevationreference","kind":"symbol","abstract":[{"type":"text","text":"Selects the base of line-elevation. Some modes might require precomputed elevation data in the tileset."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LineElevationReference"}],"tags":[{"type":"spi","text":"SPI"}],"navigatorTitle":[{"kind":"identifier","text":"LineElevationReference"}]},"https://docs.mapbox.com/style-spec/reference/types/#color":{"type":"link","titleInlineContent":[{"text":"Mapbox Style Spec","type":"text"}],"url":"https:\/\/docs.mapbox.com\/style-spec\/reference\/types\/#color","identifier":"https:\/\/docs.mapbox.com\/style-spec\/reference\/types\/#color","title":"Mapbox Style Spec"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/IconTranslateAnchor":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconTranslateAnchor","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"IconTranslateAnchor"}],"url":"\/documentation\/mapboxmaps\/icontranslateanchor","abstract":[{"type":"text","text":"Controls the frame of reference for "},{"type":"codeVoice","code":"icon-translate"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IconTranslateAnchor"}],"kind":"symbol","type":"topic","title":"IconTranslateAnchor"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TextPitchAlignment":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TextPitchAlignment"}],"abstract":[{"type":"text","text":"Orientation of text when map is pitched."}],"type":"topic","role":"symbol","kind":"symbol","title":"TextPitchAlignment","navigatorTitle":[{"kind":"identifier","text":"TextPitchAlignment"}],"url":"\/documentation\/mapboxmaps\/textpitchalignment","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextPitchAlignment"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TextAnchor":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextAnchor","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TextAnchor"}],"url":"\/documentation\/mapboxmaps\/textanchor","abstract":[{"type":"text","text":"Part of the text placed closest to the anchor."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TextAnchor"}],"kind":"symbol","type":"topic","title":"TextAnchor"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/IconTextFit":{"kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/icontextfit","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IconTextFit"}],"navigatorTitle":[{"kind":"identifier","text":"IconTextFit"}],"abstract":[{"type":"text","text":"Scales the icon to fit around the associated text."}],"title":"IconTextFit","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconTextFit"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ImageContent":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageContent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageContent"}],"url":"\/documentation\/mapboxmaps\/imagecontent","navigatorTitle":[{"kind":"identifier","text":"ImageContent"}],"abstract":[{"type":"text","text":"Describes the image content, e.g. where text can be fit into an image."}],"role":"symbol","kind":"symbol","title":"ImageContent","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FillExtrusionBaseAlignment":{"type":"topic","abstract":[{"text":"Controls the behavior of fill extrusion base over terrain","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillExtrusionBaseAlignment","url":"\/documentation\/mapboxmaps\/fillextrusionbasealignment","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FillExtrusionBaseAlignment","kind":"identifier"}],"navigatorTitle":[{"text":"FillExtrusionBaseAlignment","kind":"identifier"}],"role":"symbol","tags":[{"text":"SPI","type":"spi"}],"title":"FillExtrusionBaseAlignment","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CircleTranslateAnchor":{"navigatorTitle":[{"kind":"identifier","text":"CircleTranslateAnchor"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CircleTranslateAnchor","role":"symbol","url":"\/documentation\/mapboxmaps\/circletranslateanchor","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CircleTranslateAnchor"}],"abstract":[{"type":"text","text":"Controls the frame of reference for "},{"type":"codeVoice","code":"circle-translate"},{"type":"text","text":"."}],"title":"CircleTranslateAnchor"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleTransition":{"type":"topic","url":"\/documentation\/mapboxmaps\/styletransition","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"StyleTransition"}],"abstract":[{"text":"The transition property for a layer.","type":"text"},{"text":" ","type":"text"},{"text":"A transition property controls timing for the interpolation between a","type":"text"},{"text":" ","type":"text"},{"text":"transitionable style property’s previous value and new value.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"StyleTransition"}],"kind":"symbol","role":"symbol","title":"StyleTransition","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleTransition"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TextTranslateAnchor":{"type":"topic","url":"\/documentation\/mapboxmaps\/texttranslateanchor","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextTranslateAnchor","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TextTranslateAnchor"}],"navigatorTitle":[{"kind":"identifier","text":"TextTranslateAnchor"}],"title":"TextTranslateAnchor","abstract":[{"type":"text","text":"Controls the frame of reference for "},{"type":"codeVoice","code":"text-translate"},{"type":"text","text":"."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CircleElevationReference/RawRepresentable-Implementations":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CircleElevationReference\/RawRepresentable-Implementations","kind":"article","title":"RawRepresentable Implementations","url":"\/documentation\/mapboxmaps\/circleelevationreference\/rawrepresentable-implementations","abstract":[],"type":"topic","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FillExtrusionHeightAlignment":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillExtrusionHeightAlignment","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FillExtrusionHeightAlignment"}],"type":"topic","tags":[{"type":"spi","text":"SPI"}],"abstract":[{"type":"text","text":"Controls the behavior of fill extrusion height over terrain"}],"title":"FillExtrusionHeightAlignment","navigatorTitle":[{"kind":"identifier","text":"FillExtrusionHeightAlignment"}],"url":"\/documentation\/mapboxmaps\/fillextrusionheightalignment"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CircleElevationReference/Equatable-Implementations":{"type":"topic","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/circleelevationreference\/equatable-implementations","kind":"article","title":"Equatable Implementations","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CircleElevationReference\/Equatable-Implementations","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Value":{"navigatorTitle":[{"text":"Value","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Value","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/value","title":"Value","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Value","abstract":[],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeIlluminationAnchor":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/hillshadeilluminationanchor","title":"HillshadeIlluminationAnchor","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"HillshadeIlluminationAnchor"}],"abstract":[{"type":"text","text":"Direction of light source when map is rotated."}],"navigatorTitle":[{"kind":"identifier","text":"HillshadeIlluminationAnchor"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeIlluminationAnchor"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResolvedImage":{"navigatorTitle":[{"kind":"identifier","text":"ResolvedImage"}],"url":"\/documentation\/mapboxmaps\/resolvedimage","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResolvedImage","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResolvedImage"}],"type":"topic","abstract":[],"kind":"symbol","role":"symbol","title":"ResolvedImage"},"doc://com.mapbox.MapboxMaps/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FillExtrusionTranslateAnchor":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FillExtrusionTranslateAnchor","kind":"identifier"}],"role":"symbol","title":"FillExtrusionTranslateAnchor","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillExtrusionTranslateAnchor","url":"\/documentation\/mapboxmaps\/fillextrusiontranslateanchor","abstract":[{"text":"Controls the frame of reference for ","type":"text"},{"type":"codeVoice","code":"fill-extrusion-translate"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"FillExtrusionTranslateAnchor","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FillElevationReference":{"navigatorTitle":[{"kind":"identifier","text":"FillElevationReference"}],"tags":[{"type":"spi","text":"SPI"}],"url":"\/documentation\/mapboxmaps\/fillelevationreference","title":"FillElevationReference","kind":"symbol","abstract":[{"type":"text","text":"Selects the base of fill-elevation. Some modes might require precomputed elevation data in the tileset."}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillElevationReference","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FillElevationReference"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","role":"collection","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Anchor":{"navigatorTitle":[{"text":"Anchor","kind":"identifier"}],"role":"symbol","title":"Anchor","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Anchor","url":"\/documentation\/mapboxmaps\/anchor","kind":"symbol","type":"topic","abstract":[{"text":"Whether extruded geometries are lit relative to the map or viewport.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Anchor","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TextTransform":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextTransform","kind":"symbol","abstract":[{"type":"text","text":"Specifies how to capitalize text, similar to the CSS "},{"type":"codeVoice","code":"text-transform"},{"type":"text","text":" property."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"TextTransform"}],"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TextTransform"}],"title":"TextTransform","url":"\/documentation\/mapboxmaps\/texttransform"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SymbolZOrder":{"role":"symbol","type":"topic","title":"SymbolZOrder","abstract":[{"text":"Determines whether overlapping symbols in the same layer are rendered in the order that they appear in the data source or by their y-position relative to the viewport. To control the order and prioritization of symbols otherwise, use ","type":"text"},{"type":"codeVoice","code":"symbol-sort-key"},{"text":".","type":"text"}],"url":"\/documentation\/mapboxmaps\/symbolzorder","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolZOrder","navigatorTitle":[{"text":"SymbolZOrder","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SymbolZOrder","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CirclePitchScale":{"abstract":[{"text":"Controls the scaling behavior of the circle when the map is pitched.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"CirclePitchScale","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CirclePitchScale","kind":"identifier"}],"title":"CirclePitchScale","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CirclePitchScale","url":"\/documentation\/mapboxmaps\/circlepitchscale"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SkyType":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/skytype","role":"symbol","abstract":[{"type":"text","text":"The type of the sky"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SkyType"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SkyType","title":"SkyType","navigatorTitle":[{"kind":"identifier","text":"SkyType"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SymbolPlacement":{"abstract":[{"text":"Label placement relative to its geometry.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolPlacement","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SymbolPlacement","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/symbolplacement","title":"SymbolPlacement","navigatorTitle":[{"text":"SymbolPlacement","kind":"identifier"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"MBMStylePropertyValueKind","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValueKind\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MBMStylePropertyValueKind"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValueKind\/fragments","op":"replace"},{"value":[{"text":"MBMStylePropertyValueKind","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValueKind\/navigatorTitle","op":"replace"},{"value":"MBMImageStretches","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ImageStretches\/title","op":"replace"},{"value":[{"text":"MBMImageStretches","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ImageStretches\/fragments","op":"replace"},{"value":[{"text":"MBMImageStretches","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ImageStretches\/navigatorTitle","op":"replace"},{"value":"MBMStylePropertyValue","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValue\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MBMStylePropertyValue"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValue\/fragments","op":"replace"},{"value":[{"text":"MBMStylePropertyValue","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValue\/navigatorTitle","op":"replace"},{"value":"MBMImageContent","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ImageContent\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MBMImageContent"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ImageContent\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ImageContent\/navigatorTitle","value":[{"text":"MBMImageContent","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}