{"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","sections":[],"topicSections":[{"generated":true,"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatistics\/init(collectionDurationMillis:mapRenderDurationStatistics:cumulativeStatistics:perFrameStatistics:)"]},{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatistics\/collectionDurationMillis","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatistics\/cumulativeStatistics","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatistics\/mapRenderDurationStatistics","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatistics\/perFrameStatistics"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatistics"},"abstract":[{"text":"The performance statistics collected at the end of the sampling duration.","type":"text"}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH"],"type":"conformsTo"}],"seeAlsoSections":[{"generated":true,"title":"Performance recording","anchor":"Performance-recording","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CumulativeRenderingStatistics","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/DurationStatistics","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GroupPerformanceStatistics","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerFrameRenderingStatistics","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatisticsOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatisticsCallback"]}],"metadata":{"modules":[{"name":"MapboxMaps"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PerformanceStatistics"}],"role":"symbol","roleHeading":"Class","externalID":"c:objc(cs)MBMPerformanceStatistics","symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"PerformanceStatistics"}],"title":"PerformanceStatistics"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PerformanceStatistics","kind":"identifier"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/mapboxmaps\/performancestatistics"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/performancestatistics"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PerformanceStatistics/collectionDurationMillis":{"navigatorTitle":[{"kind":"identifier","text":"collectionDurationMillis"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatistics\/collectionDurationMillis","kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/performancestatistics\/collectiondurationmillis","title":"collectionDurationMillis","abstract":[{"type":"text","text":"The actual amount of time elapsed during statistics collection. Note that this duration is always a little bit larger"},{"type":"text","text":" "},{"text":"than the configured duration, as collection happens at a fixed point during the map render call.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionDurationMillis"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PerformanceStatistics/cumulativeStatistics":{"url":"\/documentation\/mapboxmaps\/performancestatistics\/cumulativestatistics","abstract":[{"type":"text","text":"Cumulative, continuously tracked, resource stats. Enable using the "},{"type":"codeVoice","code":"CumulativeRenderingStats"},{"type":"text","text":" performance sampler option."}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cumulativeStatistics","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMCumulativeRenderingStatistics","text":"CumulativeRenderingStatistics","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatistics\/cumulativeStatistics","role":"symbol","navigatorTitle":[{"text":"cumulativeStatistics","kind":"identifier"}],"title":"cumulativeStatistics","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","role":"collection","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","abstract":[],"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","type":"topic","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PerformanceStatistics/mapRenderDurationStatistics":{"title":"mapRenderDurationStatistics","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"mapRenderDurationStatistics"}],"abstract":[{"type":"text","text":"The CPU timeline duration statistics of the map render call."}],"url":"\/documentation\/mapboxmaps\/performancestatistics\/maprenderdurationstatistics","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatistics\/mapRenderDurationStatistics","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mapRenderDurationStatistics"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DurationStatistics","preciseIdentifier":"c:objc(cs)MBMDurationStatistics"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PerformanceStatisticsCallback":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatisticsCallback","title":"PerformanceStatisticsCallback","type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Use this callback to observe the collected statistics. The callback is invoked at regular intervals determined by"},{"type":"text","text":" "},{"type":"text","text":"the sampling duration specified in the "},{"code":"PerformanceStatisticsOptions","type":"codeVoice"},{"type":"text","text":". The callback is invoked from the main thread."}],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"PerformanceStatisticsCallback"}],"navigatorTitle":[{"kind":"identifier","text":"PerformanceStatisticsCallback"}],"url":"\/documentation\/mapboxmaps\/performancestatisticscallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CumulativeRenderingStatistics":{"url":"\/documentation\/mapboxmaps\/cumulativerenderingstatistics","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CumulativeRenderingStatistics","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CumulativeRenderingStatistics"}],"abstract":[],"role":"symbol","title":"CumulativeRenderingStatistics","navigatorTitle":[{"kind":"identifier","text":"CumulativeRenderingStatistics"}],"type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Performance":{"url":"\/documentation\/mapboxmaps\/performance","kind":"article","title":"Performance and investigations","abstract":[],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PerFrameRenderingStatistics":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerFrameRenderingStatistics","abstract":[],"title":"PerFrameRenderingStatistics","url":"\/documentation\/mapboxmaps\/perframerenderingstatistics","navigatorTitle":[{"kind":"identifier","text":"PerFrameRenderingStatistics"}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PerFrameRenderingStatistics"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PerformanceStatisticsOptions":{"navigatorTitle":[{"text":"PerformanceStatisticsOptions","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatisticsOptions","abstract":[{"text":"Options for the following statistics collection behaviors:","type":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/performancestatisticsoptions","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PerformanceStatisticsOptions","kind":"identifier"}],"title":"PerformanceStatisticsOptions"},"doc://com.mapbox.MapboxMaps/objc(cs)NSObject":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PerformanceStatistics/perFrameStatistics":{"abstract":[{"type":"text","text":"Aggregated, per-frame, timings. Enable using the  "},{"code":"PerFrameRenderingStats","type":"codeVoice"},{"type":"text","text":" performance sampler option."}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatistics\/perFrameStatistics","kind":"symbol","url":"\/documentation\/mapboxmaps\/performancestatistics\/perframestatistics","navigatorTitle":[{"text":"perFrameStatistics","kind":"identifier"}],"title":"perFrameStatistics","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"perFrameStatistics","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMPerFrameRenderingStatistics","text":"PerFrameRenderingStatistics","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.mapbox.MapboxMaps/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.mapbox.MapboxMaps/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.mapbox.MapboxMaps/s7CVarArgP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.mapbox.MapboxMaps/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/DurationStatistics":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/DurationStatistics","abstract":[],"title":"DurationStatistics","url":"\/documentation\/mapboxmaps\/durationstatistics","navigatorTitle":[{"text":"DurationStatistics","kind":"identifier"}],"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DurationStatistics","kind":"identifier"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GroupPerformanceStatistics":{"url":"\/documentation\/mapboxmaps\/groupperformancestatistics","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GroupPerformanceStatistics","title":"GroupPerformanceStatistics","navigatorTitle":[{"kind":"identifier","text":"GroupPerformanceStatistics"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupPerformanceStatistics"}],"type":"topic","abstract":[]},"doc://com.mapbox.MapboxMaps/SQ":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PerformanceStatistics":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatistics","kind":"symbol","title":"PerformanceStatistics","url":"\/documentation\/mapboxmaps\/performancestatistics","role":"symbol","navigatorTitle":[{"text":"PerformanceStatistics","kind":"identifier"}],"abstract":[{"text":"The performance statistics collected at the end of the sampling duration.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PerformanceStatistics","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PerformanceStatistics/init(collectionDurationMillis:mapRenderDurationStatistics:cumulativeStatistics:perFrameStatistics:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatistics\/init(collectionDurationMillis:mapRenderDurationStatistics:cumulativeStatistics:perFrameStatistics:)","kind":"symbol","type":"topic","title":"init(collectionDurationMillis:mapRenderDurationStatistics:cumulativeStatistics:perFrameStatistics:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"collectionDurationMillis","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"mapRenderDurationStatistics","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMDurationStatistics","text":"DurationStatistics","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"cumulativeStatistics","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CumulativeRenderingStatistics","preciseIdentifier":"c:objc(cs)MBMCumulativeRenderingStatistics","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"perFrameStatistics","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PerFrameRenderingStatistics","preciseIdentifier":"c:objc(cs)MBMPerFrameRenderingStatistics","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"initWithCollectionDurationMillis:mapRenderDurationStatistics:cumulativeStatistics:perFrameStatistics:","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/performancestatistics\/init(collectiondurationmillis:maprenderdurationstatistics:cumulativestatistics:perframestatistics:)","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"MBMPerformanceStatistics","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MBMPerformanceStatistics"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"MBMPerformanceStatistics","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatistics\/collectionDurationMillis","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatistics\/cumulativeStatistics","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatistics\/mapRenderDurationStatistics","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatistics\/perFrameStatistics"],"title":"Instance Properties"},{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatistics\/init(collectionDurationMillis:mapRenderDurationStatistics:cumulativeStatistics:perFrameStatistics:)"],"title":"Instance Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"]}],"op":"replace"},{"path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CumulativeRenderingStatistics","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/DurationStatistics","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GroupPerformanceStatistics","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerFrameRenderingStatistics","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatisticsOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatisticsCallback"],"title":"Performance recording","generated":true,"anchor":"Performance-recording"}],"op":"replace"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBMPerformanceStatistics"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatistics~1collectionDurationMillis\/title","value":"collectionDurationMillis","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatistics~1collectionDurationMillis\/fragments","value":[{"text":"collectionDurationMillis","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatistics~1cumulativeStatistics\/title","value":"cumulativeStatistics","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatistics~1cumulativeStatistics\/fragments","value":[{"text":"cumulativeStatistics","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatistics~1mapRenderDurationStatistics\/title","value":"mapRenderDurationStatistics","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatistics~1mapRenderDurationStatistics\/fragments","value":[{"kind":"identifier","text":"mapRenderDurationStatistics"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatisticsCallback\/title","value":"MBMPerformanceStatisticsCallback","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatisticsCallback\/fragments","value":[{"kind":"identifier","text":"MBMPerformanceStatisticsCallback"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatisticsCallback\/navigatorTitle","value":[{"kind":"identifier","text":"MBMPerformanceStatisticsCallback"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CumulativeRenderingStatistics\/title","value":"MBMCumulativeRenderingStatistics","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CumulativeRenderingStatistics\/fragments","value":[{"kind":"identifier","text":"MBMCumulativeRenderingStatistics"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CumulativeRenderingStatistics\/navigatorTitle","value":[{"kind":"identifier","text":"MBMCumulativeRenderingStatistics"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerFrameRenderingStatistics\/title","value":"MBMPerFrameRenderingStatistics","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerFrameRenderingStatistics\/fragments","value":[{"kind":"identifier","text":"MBMPerFrameRenderingStatistics"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerFrameRenderingStatistics\/navigatorTitle","value":[{"text":"MBMPerFrameRenderingStatistics","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatisticsOptions\/title","value":"MBMPerformanceStatisticsOptions","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatisticsOptions\/fragments","value":[{"kind":"identifier","text":"MBMPerformanceStatisticsOptions"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatisticsOptions\/navigatorTitle","value":[{"text":"MBMPerformanceStatisticsOptions","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatistics~1perFrameStatistics\/title","value":"perFrameStatistics","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatistics~1perFrameStatistics\/fragments","value":[{"text":"perFrameStatistics","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1DurationStatistics\/title","value":"MBMDurationStatistics","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1DurationStatistics\/fragments","value":[{"text":"MBMDurationStatistics","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1DurationStatistics\/navigatorTitle","value":[{"text":"MBMDurationStatistics","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GroupPerformanceStatistics\/title","value":"MBMGroupPerformanceStatistics","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GroupPerformanceStatistics\/fragments","value":[{"kind":"identifier","text":"MBMGroupPerformanceStatistics"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GroupPerformanceStatistics\/navigatorTitle","value":[{"kind":"identifier","text":"MBMGroupPerformanceStatistics"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatistics\/title","value":"MBMPerformanceStatistics","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatistics\/fragments","value":[{"text":"MBMPerformanceStatistics","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatistics\/navigatorTitle","value":[{"text":"MBMPerformanceStatistics","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatistics~1init(collectionDurationMillis:mapRenderDurationStatistics:cumulativeStatistics:perFrameStatistics:)\/title","value":"initWithCollectionDurationMillis:mapRenderDurationStatistics:cumulativeStatistics:perFrameStatistics:","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatistics~1init(collectionDurationMillis:mapRenderDurationStatistics:cumulativeStatistics:perFrameStatistics:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithCollectionDurationMillis:mapRenderDurationStatistics:cumulativeStatistics:perFrameStatistics:","kind":"identifier"}],"op":"replace"}]}]}