{"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoaded\/init(timeInterval:)","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"MapboxMaps"}],"externalID":"c:objc(cs)MBMMapLoaded(im)initWithTimeInterval:","symbolKind":"init","navigatorTitle":[{"text":"initWithTimeInterval:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"timeInterval","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"EventTimeInterval","preciseIdentifier":"c:objc(cs)MBMEventTimeInterval","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(timeInterval:)","roleHeading":"Initializer"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/maploaded\/init(timeinterval:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/maploaded\/init(timeinterval:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"timeInterval","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/EventTimeInterval","text":"EventTimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMEventTimeInterval"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoaded"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoaded":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapLoaded"}],"title":"MapLoaded","abstract":[{"type":"text","text":"The style has been fully loaded, and the "},{"type":"codeVoice","code":"map"},{"type":"text","text":" has rendered all visible tiles."},{"type":"text","text":" "},{"type":"text","text":"The event will be emitted only once for the current style. If it is required to"},{"type":"text","text":" "},{"type":"text","text":"observe an event where all required resources are loaded or rendered, please"},{"type":"text","text":" "},{"type":"text","text":"check the following events: "},{"type":"codeVoice","code":"MapIdle"},{"type":"text","text":", "},{"type":"codeVoice","code":"StyleDataLoaded"},{"type":"text","text":", and "},{"type":"codeVoice","code":"RenderFrameFinished"},{"type":"text","text":"."}],"navigatorTitle":[{"kind":"identifier","text":"MapLoaded"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoaded","role":"symbol","url":"\/documentation\/mapboxmaps\/maploaded","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article","url":"\/documentation\/overview","role":"collection","abstract":[],"title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","role":"collectionGroup","title":"Map events","kind":"article","type":"topic","abstract":[{"type":"text","text":"The simplified diagram of the events emitted by the map is displayed below."}],"url":"\/documentation\/mapboxmaps\/events"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoaded/init(timeInterval:)":{"type":"topic","url":"\/documentation\/mapboxmaps\/maploaded\/init(timeinterval:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"timeInterval","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMEventTimeInterval","text":"EventTimeInterval","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoaded\/init(timeInterval:)","title":"init(timeInterval:)","role":"symbol","abstract":[],"navigatorTitle":[{"text":"initWithTimeInterval:","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/EventTimeInterval":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/EventTimeInterval","kind":"symbol","url":"\/documentation\/mapboxmaps\/eventtimeinterval","type":"topic","title":"EventTimeInterval","abstract":[{"type":"text","text":"The time interval of an event. The "},{"code":"begin","type":"codeVoice"},{"type":"text","text":" property represents the time"},{"type":"text","text":" "},{"type":"text","text":"origin of an event, and the "},{"code":"end","type":"codeVoice"},{"type":"text","text":" property represents the time when the particular"},{"type":"text","text":" "},{"type":"text","text":"operation is complete. The timestamps are sampled at the origin and do not include"},{"type":"text","text":" "},{"type":"text","text":"the time required to dispatch an event."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EventTimeInterval","kind":"identifier"}],"navigatorTitle":[{"text":"EventTimeInterval","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithTimeInterval:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTimeInterval:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithTimeInterval:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)MBMEventTimeInterval","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/EventTimeInterval","kind":"typeIdentifier","text":"MBMEventTimeInterval"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"timeInterval"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MBMMapLoaded","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoaded\/title"},{"value":[{"kind":"identifier","text":"MBMMapLoaded"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoaded\/fragments"},{"value":[{"kind":"identifier","text":"MBMMapLoaded"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoaded\/navigatorTitle"},{"value":"initWithTimeInterval:","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoaded~1init(timeInterval:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTimeInterval:"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoaded~1init(timeInterval:)\/fragments"},{"value":"MBMEventTimeInterval","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1EventTimeInterval\/title"},{"value":[{"text":"MBMEventTimeInterval","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1EventTimeInterval\/fragments"},{"value":[{"kind":"identifier","text":"MBMEventTimeInterval"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1EventTimeInterval\/navigatorTitle"}]}]}