{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/stylepackloadoptions\/extraoptions"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/stylepackloadoptions\/extraoptions"]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadOptions"]]},"abstract":[{"text":"Extra style package load options.","type":"text"}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadOptions\/extraOptions"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"extraOptions"}],"title":"extraOptions","role":"symbol","modules":[{"name":"MapboxMaps"}],"symbolKind":"property","externalID":"c:objc(cs)MBMStylePackLoadOptions(py)extraOptions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"extraOptions","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"extraOptions"},{"kind":"text","text":": "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"level":2,"anchor":"discussion","text":"Discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"Accepts the dictionary value with keys of string type."},{"text":" ","type":"text"},{"type":"text","text":"Supported options:"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"“keep-legacy-style-pack” -> boolean (false by default)."},{"type":"text","text":" "},{"text":"Prior to Maps v11 the style packages were stored in the Disk cache, and starting from v11 they are stored in the Tile Store.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"By default, the implementation removes the style package from the legacy storage after the first successful loadStylePack()"},{"type":"text","text":" "},{"type":"text","text":"call when all the data gets into the Tile Store."},{"text":" ","type":"text"},{"text":"Setting this flag prevents from the style package removal from the legacy storage after the loadStylePack() call.","type":"text"}]}]}],"type":"unorderedList"}]}],"kind":"symbol","references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePackLoadOptions/extraOptions":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"extraOptions","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadOptions\/extraOptions","navigatorTitle":[{"kind":"identifier","text":"extraOptions"}],"url":"\/documentation\/mapboxmaps\/stylepackloadoptions\/extraoptions","title":"extraOptions","kind":"symbol","abstract":[{"text":"Extra style package load options.","type":"text"}],"type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePackLoadOptions":{"type":"topic","navigatorTitle":[{"text":"StylePackLoadOptions","kind":"identifier"}],"abstract":[{"text":"Describes the style package load option values.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadOptions","url":"\/documentation\/mapboxmaps\/stylepackloadoptions","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StylePackLoadOptions"}],"title":"StylePackLoadOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"title":"TileStore APIs","kind":"article","type":"topic","url":"\/documentation\/mapboxmaps\/tilestore-apis","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","abstract":[],"kind":"article","url":"\/documentation\/overview","type":"topic","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","url":"\/documentation\/mapboxmaps","role":"collection","title":"MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"extraOptions","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"extraOptions","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":" ","kind":"text"},{"kind":"identifier","text":"extraOptions"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadOptions~1extraOptions\/title","value":"extraOptions"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadOptions~1extraOptions\/fragments","op":"replace","value":[{"kind":"identifier","text":"extraOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadOptions\/title","value":"MBMStylePackLoadOptions"},{"value":[{"text":"MBMStylePackLoadOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadOptions\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadOptions\/navigatorTitle","value":[{"kind":"identifier","text":"MBMStylePackLoadOptions"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}