{"abstract":[{"text":"Settings to configure behavior of persistent log","type":"text"}],"kind":"symbol","sections":[],"metadata":{"roleHeading":"Class","externalID":"c:objc(cs)MBXExperimentalPersistentLogConfiguration","role":"symbol","symbolKind":"class","title":"PersistentLogConfiguration","navigatorTitle":[{"text":"PersistentLogConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PersistentLogConfiguration","kind":"identifier"}],"modules":[{"name":"MapboxCommon"}]},"topicSections":[{"generated":true,"anchor":"Type-Methods","title":"Type Methods","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/getFileAllowHeader()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/getFileFlushBufferSize()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/getFileFlushImmediateFromLogLevel()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/getFileFlushLines()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/getFileFlushSeconds()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/getFileLoggingLevel()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/getFileLoggingLevelForCategory(forCategory:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/getFileMaxSize()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/getFilePath()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/getFilePerCategory()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/getFileRotateCount()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/resetFileLoggingLevelForCategory(forCategory:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/setFileAllowHeaderForAllow(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/setFileFlushConfigForLogLines(_:seconds:bufferSize:immediateFlushFromLogLevel:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/setFileLoggingLevelForCategoryForCategory(_:upTo:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/setFileLoggingLevelForUpTo(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/setFileMaxSizeForMaxSize(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/setFilePathForPath(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/setFilePerCategoryForAllow(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/setFileRotateCountForRotateCount(_:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PersistentLogConfiguration"}],"languages":["swift"],"platforms":["iOS"]}]}],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"]},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH"]}],"variants":[{"paths":["\/documentation\/mapboxcommon\/persistentlogconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxcommon\/persistentlogconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon"]]},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration","interfaceLanguage":"swift"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PersistentLogConfiguration/setFileAllowHeaderForAllow(_:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setFileAllowHeaderForAllow"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"abstract":[{"text":"Set file allow header.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"setFileAllowHeaderForAllow:"}],"title":"setFileAllowHeaderForAllow(_:)","kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/setFileAllowHeaderForAllow(_:)","url":"\/documentation\/mapboxcommon\/persistentlogconfiguration\/setfileallowheaderforallow(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PersistentLogConfiguration/getFileFlushSeconds()":{"navigatorTitle":[{"kind":"identifier","text":"getFileFlushSeconds"}],"role":"symbol","type":"topic","title":"getFileFlushSeconds()","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/getFileFlushSeconds()","abstract":[{"type":"text","text":"Get file flush configuration."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getFileFlushSeconds"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":"?"}],"url":"\/documentation\/mapboxcommon\/persistentlogconfiguration\/getfileflushseconds()"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PersistentLogConfiguration/setFileRotateCountForRotateCount(_:)":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setFileRotateCountForRotateCount","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UInt64","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/setFileRotateCountForRotateCount(_:)","kind":"symbol","url":"\/documentation\/mapboxcommon\/persistentlogconfiguration\/setfilerotatecountforrotatecount(_:)","role":"symbol","abstract":[{"type":"text","text":"Set file rotation count."}],"navigatorTitle":[{"text":"setFileRotateCountForRotateCount:","kind":"identifier"}],"title":"setFileRotateCountForRotateCount(_:)"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","abstract":[],"type":"topic","title":"MapboxMaps Documentation","kind":"article","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PersistentLogConfiguration/getFileMaxSize()":{"title":"getFileMaxSize()","url":"\/documentation\/mapboxcommon\/persistentlogconfiguration\/getfilemaxsize()","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getFileMaxSize","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"UInt64","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V"}],"navigatorTitle":[{"text":"getFileMaxSize","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/getFileMaxSize()","kind":"symbol","abstract":[{"type":"text","text":"Get maximum file size for stored logs."}],"type":"topic"},"doc://com.mapbox.MapboxMaps/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"},"doc://com.mapbox.MapboxMaps/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH"},"doc://com.mapbox.MapboxMaps/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PersistentLogConfiguration/setFileFlushConfigForLogLines(_:seconds:bufferSize:immediateFlushFromLogLevel:)":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setFileFlushConfigForLogLines","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"seconds","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"bufferSize","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"immediateFlushFromLogLevel","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"setFileFlushConfigForLogLines:seconds:bufferSize:immediateFlushFromLogLevel:","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/persistentlogconfiguration\/setfileflushconfigforloglines(_:seconds:buffersize:immediateflushfromloglevel:)","abstract":[{"text":"Set file flush configuration.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/setFileFlushConfigForLogLines(_:seconds:bufferSize:immediateFlushFromLogLevel:)","title":"setFileFlushConfigForLogLines(_:seconds:bufferSize:immediateFlushFromLogLevel:)","kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PersistentLogConfiguration/getFileFlushBufferSize()":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Get file flush buffer size setting."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/getFileFlushBufferSize()","title":"getFileFlushBufferSize()","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getFileFlushBufferSize","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"getFileFlushBufferSize","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/persistentlogconfiguration\/getfileflushbuffersize()","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PersistentLogConfiguration/getFileLoggingLevelForCategory(forCategory:)":{"title":"getFileLoggingLevelForCategory(forCategory:)","url":"\/documentation\/mapboxcommon\/persistentlogconfiguration\/getfilelogginglevelforcategory(forcategory:)","navigatorTitle":[{"text":"getFileLoggingLevelForCategoryForCategory:","kind":"identifier"}],"abstract":[{"type":"text","text":"Get file logging level for a category of logs."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/getFileLoggingLevelForCategory(forCategory:)","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getFileLoggingLevelForCategory","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forCategory","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PersistentLogConfiguration/getFileRotateCount()":{"url":"\/documentation\/mapboxcommon\/persistentlogconfiguration\/getfilerotatecount()","navigatorTitle":[{"text":"getFileRotateCount","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/getFileRotateCount()","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getFileRotateCount","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"UInt64","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V"}],"title":"getFileRotateCount()","role":"symbol","type":"topic","abstract":[{"text":"Get file rotation count.","type":"text"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PersistentLogConfiguration/getFileFlushImmediateFromLogLevel()":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/getFileFlushImmediateFromLogLevel()","title":"getFileFlushImmediateFromLogLevel()","url":"\/documentation\/mapboxcommon\/persistentlogconfiguration\/getfileflushimmediatefromloglevel()","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getFileFlushImmediateFromLogLevel","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"getFileFlushImmediateFromLogLevel","kind":"identifier"}],"abstract":[{"type":"text","text":"Get immediate flush from log level configuration."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PersistentLogConfiguration/getFileAllowHeader()":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/getFileAllowHeader()","role":"symbol","url":"\/documentation\/mapboxcommon\/persistentlogconfiguration\/getfileallowheader()","navigatorTitle":[{"kind":"identifier","text":"getFileAllowHeader"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getFileAllowHeader"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"type":"topic","title":"getFileAllowHeader()","abstract":[{"text":"Get file allow header.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PersistentLogConfiguration/setFilePathForPath(_:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/setFilePathForPath(_:)","type":"topic","title":"setFilePathForPath(_:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setFilePathForPath","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Set the folder path for file logs."}],"navigatorTitle":[{"text":"setFilePathForPath:","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/persistentlogconfiguration\/setfilepathforpath(_:)","role":"symbol","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PersistentLogConfiguration/getFileFlushLines()":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"getFileFlushLines"}],"url":"\/documentation\/mapboxcommon\/persistentlogconfiguration\/getfileflushlines()","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/getFileFlushLines()","role":"symbol","title":"getFileFlushLines()","abstract":[{"text":"Get file flush log lines setting.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getFileFlushLines"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}]},"doc://com.mapbox.MapboxMaps/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject"},"doc://com.mapbox.MapboxMaps/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PersistentLogConfiguration/setFilePerCategoryForAllow(_:)":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setFilePerCategoryForAllow"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"kind":"symbol","url":"\/documentation\/mapboxcommon\/persistentlogconfiguration\/setfilepercategoryforallow(_:)","navigatorTitle":[{"kind":"identifier","text":"setFilePerCategoryForAllow:"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/setFilePerCategoryForAllow(_:)","abstract":[{"type":"text","text":"Enable an individual file per log category."}],"title":"setFilePerCategoryForAllow(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"url":"\/documentation\/mapboxcommon","role":"collection","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","type":"topic","abstract":[],"title":"MapboxCommon"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PersistentLogConfiguration/resetFileLoggingLevelForCategory(forCategory:)":{"role":"symbol","type":"topic","abstract":[{"text":"Reset file logging level for a category of logs.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resetFileLoggingLevelForCategory"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forCategory"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"resetFileLoggingLevelForCategoryForCategory:"}],"url":"\/documentation\/mapboxcommon\/persistentlogconfiguration\/resetfilelogginglevelforcategory(forcategory:)","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/resetFileLoggingLevelForCategory(forCategory:)","title":"resetFileLoggingLevelForCategory(forCategory:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PersistentLogConfiguration/getFilePath()":{"abstract":[{"type":"text","text":"Get the folder path for file logs."}],"url":"\/documentation\/mapboxcommon\/persistentlogconfiguration\/getfilepath()","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/getFilePath()","title":"getFilePath()","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"getFilePath"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"getFilePath"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PersistentLogConfiguration/setFileLoggingLevelForUpTo(_:)":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/setFileLoggingLevelForUpTo(_:)","abstract":[{"type":"text","text":"Set file logging level."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setFileLoggingLevelForUpTo"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"kind":"identifier","text":"setFileLoggingLevelForUpTo:"}],"url":"\/documentation\/mapboxcommon\/persistentlogconfiguration\/setfilelogginglevelforupto(_:)","title":"setFileLoggingLevelForUpTo(_:)","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PersistentLogConfiguration/getFileLoggingLevel()":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getFileLoggingLevel","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/getFileLoggingLevel()","navigatorTitle":[{"text":"getFileLoggingLevel","kind":"identifier"}],"kind":"symbol","type":"topic","title":"getFileLoggingLevel()","abstract":[{"type":"text","text":"Get file logging level."}],"url":"\/documentation\/mapboxcommon\/persistentlogconfiguration\/getfilelogginglevel()","role":"symbol"},"doc://com.mapbox.MapboxMaps/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PersistentLogConfiguration/getFilePerCategory()":{"type":"topic","url":"\/documentation\/mapboxcommon\/persistentlogconfiguration\/getfilepercategory()","navigatorTitle":[{"text":"getFilePerCategory","kind":"identifier"}],"abstract":[{"text":"Get whether individual file per log category is enabled.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getFilePerCategory","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"getFilePerCategory()","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/getFilePerCategory()","kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PersistentLogConfiguration":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PersistentLogConfiguration"}],"url":"\/documentation\/mapboxcommon\/persistentlogconfiguration","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration","abstract":[{"type":"text","text":"Settings to configure behavior of persistent log"}],"role":"symbol","title":"PersistentLogConfiguration","navigatorTitle":[{"kind":"identifier","text":"PersistentLogConfiguration"}]},"doc://com.mapbox.MapboxMaps/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PersistentLogConfiguration/setFileMaxSizeForMaxSize(_:)":{"role":"symbol","abstract":[{"type":"text","text":"Set maximum file size for stored logs."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setFileMaxSizeForMaxSize"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V","text":"UInt64"},{"kind":"text","text":")"}],"type":"topic","title":"setFileMaxSizeForMaxSize(_:)","navigatorTitle":[{"kind":"identifier","text":"setFileMaxSizeForMaxSize:"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/setFileMaxSizeForMaxSize(_:)","url":"\/documentation\/mapboxcommon\/persistentlogconfiguration\/setfilemaxsizeformaxsize(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PersistentLogConfiguration/setFileLoggingLevelForCategoryForCategory(_:upTo:)":{"kind":"symbol","abstract":[{"type":"text","text":"Set file logging level for a category of logs."}],"role":"symbol","url":"\/documentation\/mapboxcommon\/persistentlogconfiguration\/setfilelogginglevelforcategoryforcategory(_:upto:)","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setFileLoggingLevelForCategoryForCategory","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"upTo","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"setFileLoggingLevelForCategoryForCategory:upTo:","kind":"identifier"}],"title":"setFileLoggingLevelForCategoryForCategory(_:upTo:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/setFileLoggingLevelForCategoryForCategory(_:upTo:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"MBXExperimentalPersistentLogConfiguration","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"MBXExperimentalPersistentLogConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"MBXExperimentalPersistentLogConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"generated":true,"anchor":"Type-Methods","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/getFileAllowHeader()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/getFileFlushBufferSize()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/getFileFlushImmediateFromLogLevel()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/getFileFlushLines()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/getFileFlushSeconds()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/getFileLoggingLevel()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/getFileLoggingLevelForCategory(forCategory:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/getFileMaxSize()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/getFilePath()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/getFilePerCategory()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/getFileRotateCount()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/resetFileLoggingLevelForCategory(forCategory:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/setFileAllowHeaderForAllow(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/setFileFlushConfigForLogLines(_:seconds:bufferSize:immediateFlushFromLogLevel:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/setFileLoggingLevelForCategoryForCategory(_:upTo:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/setFileLoggingLevelForUpTo(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/setFileMaxSizeForMaxSize(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/setFilePathForPath(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/setFilePerCategoryForAllow(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/setFileRotateCountForRotateCount(_:)"],"title":"Type Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"title":"Inherits From"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBXExperimentalPersistentLogConfiguration","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1setFileAllowHeaderForAllow(_:)\/title","value":"setFileAllowHeaderForAllow:","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1setFileAllowHeaderForAllow(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"setFileAllowHeaderForAllow:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1getFileFlushSeconds()\/title","value":"getFileFlushSeconds","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1getFileFlushSeconds()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"getFileFlushSeconds","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1setFileRotateCountForRotateCount(_:)\/title","value":"setFileRotateCountForRotateCount:","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1setFileRotateCountForRotateCount(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"setFileRotateCountForRotateCount:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1getFileMaxSize()\/title","value":"getFileMaxSize","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1getFileMaxSize()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getFileMaxSize"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1setFileFlushConfigForLogLines(_:seconds:bufferSize:immediateFlushFromLogLevel:)\/title","value":"setFileFlushConfigForLogLines:seconds:bufferSize:immediateFlushFromLogLevel:","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1setFileFlushConfigForLogLines(_:seconds:bufferSize:immediateFlushFromLogLevel:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setFileFlushConfigForLogLines:seconds:bufferSize:immediateFlushFromLogLevel:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1getFileFlushBufferSize()\/title","value":"getFileFlushBufferSize","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1getFileFlushBufferSize()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"getFileFlushBufferSize","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1getFileLoggingLevelForCategory(forCategory:)\/title","value":"getFileLoggingLevelForCategoryForCategory:","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1getFileLoggingLevelForCategory(forCategory:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"getFileLoggingLevelForCategoryForCategory:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1getFileRotateCount()\/title","value":"getFileRotateCount","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1getFileRotateCount()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"getFileRotateCount","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1getFileFlushImmediateFromLogLevel()\/title","value":"getFileFlushImmediateFromLogLevel","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1getFileFlushImmediateFromLogLevel()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"getFileFlushImmediateFromLogLevel","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1getFileAllowHeader()\/title","value":"getFileAllowHeader","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1getFileAllowHeader()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"getFileAllowHeader","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1setFilePathForPath(_:)\/title","value":"setFilePathForPath:","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1setFilePathForPath(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"setFilePathForPath:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1getFileFlushLines()\/title","value":"getFileFlushLines","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1getFileFlushLines()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"getFileFlushLines","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1setFilePerCategoryForAllow(_:)\/title","value":"setFilePerCategoryForAllow:","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1setFilePerCategoryForAllow(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"setFilePerCategoryForAllow:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1resetFileLoggingLevelForCategory(forCategory:)\/title","value":"resetFileLoggingLevelForCategoryForCategory:","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1resetFileLoggingLevelForCategory(forCategory:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"resetFileLoggingLevelForCategoryForCategory:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1getFilePath()\/title","value":"getFilePath","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1getFilePath()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getFilePath"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1setFileLoggingLevelForUpTo(_:)\/title","value":"setFileLoggingLevelForUpTo:","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1setFileLoggingLevelForUpTo(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setFileLoggingLevelForUpTo:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1getFileLoggingLevel()\/title","value":"getFileLoggingLevel","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1getFileLoggingLevel()\/fragments","value":[{"kind":"text","text":"+ "},{"text":"getFileLoggingLevel","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1getFilePerCategory()\/title","value":"getFilePerCategory","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1getFilePerCategory()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"getFilePerCategory","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration\/title","value":"MBXExperimentalPersistentLogConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration\/fragments","value":[{"text":"MBXExperimentalPersistentLogConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"MBXExperimentalPersistentLogConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1setFileMaxSizeForMaxSize(_:)\/title","value":"setFileMaxSizeForMaxSize:","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1setFileMaxSizeForMaxSize(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setFileMaxSizeForMaxSize:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1setFileLoggingLevelForCategoryForCategory(_:upTo:)\/title","value":"setFileLoggingLevelForCategoryForCategory:upTo:","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1setFileLoggingLevelForCategoryForCategory(_:upTo:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"setFileLoggingLevelForCategoryForCategory:upTo:","kind":"identifier"}],"op":"replace"}]}]}