{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TilesetDescriptorOptions\/init(styleURI:minZoom:maxZoom:pixelRatio:tilesets:stylePack:extraOptions:)"},"kind":"symbol","metadata":{"externalID":"c:objc(cs)MBMTilesetDescriptorOptions(im)initWithStyleURI:minZoom:maxZoom:pixelRatio:tilesets:stylePackOptions:extraOptions:","title":"init(styleURI:minZoom:maxZoom:pixelRatio:tilesets:stylePack:extraOptions:)","role":"symbol","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"styleURI"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"minZoom","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V","text":"UInt8"},{"kind":"text","text":", "},{"kind":"externalParam","text":"maxZoom"},{"kind":"text","text":": "},{"text":"UInt8","kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V"},{"kind":"text","text":", "},{"text":"pixelRatio","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tilesets"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"text":"stylePack","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"StylePackLoadOptions","preciseIdentifier":"c:objc(cs)MBMStylePackLoadOptions"},{"text":"?, ","kind":"text"},{"text":"extraOptions","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithStyleURI:minZoom:maxZoom:pixelRatio:tilesets:stylePackOptions:extraOptions:"}],"symbolKind":"init","modules":[{"name":"MapboxMaps"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"styleURI","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"minZoom","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5UInt8V","text":"UInt8","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"maxZoom","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UInt8","kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"pixelRatio"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"tilesets","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"stylePack"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"stylePackOptions"},{"text":": ","kind":"text"},{"text":"StylePackLoadOptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadOptions","preciseIdentifier":"c:objc(cs)MBMStylePackLoadOptions","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"extraOptions"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TilesetDescriptorOptions"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/tilesetdescriptoroptions\/init(styleuri:minzoom:maxzoom:pixelratio:tilesets:stylepack:extraoptions:)"]},{"paths":["\/documentation\/mapboxmaps\/tilesetdescriptoroptions\/init(styleuri:minzoom:maxzoom:pixelratio:tilesets:stylepack:extraoptions:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePackLoadOptions":{"type":"topic","kind":"symbol","title":"StylePackLoadOptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadOptions","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"StylePackLoadOptions","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"StylePackLoadOptions"}],"abstract":[{"type":"text","text":"Describes the style package load option values."}],"url":"\/documentation\/mapboxmaps\/stylepackloadoptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","url":"\/documentation\/mapboxmaps\/tilestore-apis","kind":"article","role":"collectionGroup","title":"TileStore APIs","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TilesetDescriptorOptions/init(styleURI:minZoom:maxZoom:pixelRatio:tilesets:stylePack:extraOptions:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"styleURI","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"minZoom","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UInt8","kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"maxZoom"},{"text":": ","kind":"text"},{"text":"UInt8","kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V"},{"text":", ","kind":"text"},{"text":"pixelRatio","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":", ","kind":"text"},{"text":"tilesets","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"]?, ","kind":"text"},{"text":"stylePack","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"StylePackLoadOptions","preciseIdentifier":"c:objc(cs)MBMStylePackLoadOptions"},{"text":"?, ","kind":"text"},{"text":"extraOptions","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"title":"init(styleURI:minZoom:maxZoom:pixelRatio:tilesets:stylePack:extraOptions:)","role":"symbol","url":"\/documentation\/mapboxmaps\/tilesetdescriptoroptions\/init(styleuri:minzoom:maxzoom:pixelratio:tilesets:stylepack:extraoptions:)","navigatorTitle":[{"kind":"identifier","text":"initWithStyleURI:minZoom:maxZoom:pixelRatio:tilesets:stylePackOptions:extraOptions:"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TilesetDescriptorOptions\/init(styleURI:minZoom:maxZoom:pixelRatio:tilesets:stylePack:extraOptions:)","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"role":"collection","url":"\/documentation\/mapboxmaps","title":"MapboxMaps","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TilesetDescriptorOptions":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TilesetDescriptorOptions","type":"topic","url":"\/documentation\/mapboxmaps\/tilesetdescriptoroptions","title":"TilesetDescriptorOptions","abstract":[{"type":"text","text":"Describes the tileset descriptor option values."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TilesetDescriptorOptions"}],"navigatorTitle":[{"kind":"identifier","text":"TilesetDescriptorOptions"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","abstract":[],"type":"topic","kind":"article","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"initWithStyleURI:minZoom:maxZoom:pixelRatio:tilesets:stylePackOptions:extraOptions:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithStyleURI:minZoom:maxZoom:pixelRatio:tilesets:stylePackOptions:extraOptions:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithStyleURI:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"styleURI","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"minZoom:"},{"text":"(","kind":"text"},{"text":"uint8_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@uint8_t"},{"kind":"text","text":") "},{"text":"minZoom","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maxZoom:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@uint8_t","text":"uint8_t","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"maxZoom","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pixelRatio:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:f","text":"float"},{"kind":"text","text":") "},{"text":"pixelRatio","kind":"internalParam"},{"kind":"text","text":" "},{"text":"tilesets:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSString *>","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"tilesets","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stylePackOptions:"},{"kind":"text","text":"("},{"text":"MBMStylePackLoadOptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadOptions","preciseIdentifier":"c:objc(cs)MBMStylePackLoadOptions","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"stylePackOptions"},{"kind":"text","text":" "},{"kind":"identifier","text":"extraOptions:"},{"text":"(","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"extraOptions"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadOptions\/title","op":"replace","value":"MBMStylePackLoadOptions"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadOptions\/fragments","op":"replace","value":[{"text":"MBMStylePackLoadOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadOptions\/navigatorTitle","op":"replace","value":[{"text":"MBMStylePackLoadOptions","kind":"identifier"}]},{"value":"initWithStyleURI:minZoom:maxZoom:pixelRatio:tilesets:stylePackOptions:extraOptions:","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions~1init(styleURI:minZoom:maxZoom:pixelRatio:tilesets:stylePack:extraOptions:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions~1init(styleURI:minZoom:maxZoom:pixelRatio:tilesets:stylePack:extraOptions:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithStyleURI:minZoom:maxZoom:pixelRatio:tilesets:stylePackOptions:extraOptions:","kind":"identifier"}],"op":"replace"},{"value":"MBMTilesetDescriptorOptions","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions\/fragments","value":[{"text":"MBMTilesetDescriptorOptions","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions\/navigatorTitle","value":[{"kind":"identifier","text":"MBMTilesetDescriptorOptions"}]}]}]}