{"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":" * "},{"kind":"identifier","text":"viewportMode"},{"kind":"text","text":";"}]}]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapOptions\/viewportMode","interfaceLanguage":"occ"},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"externalID":"c:objc(cs)MBMMapOptions(py)viewportMode","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"viewportMode"}],"title":"viewportMode","modules":[{"name":"MapboxMaps"}],"symbolKind":"property","role":"symbol","fragments":[{"kind":"identifier","text":"viewportMode"}]},"abstract":[{"type":"text","text":"The viewport mode. This can be used to flip the vertical"},{"type":"text","text":" "},{"type":"text","text":"orientation of the map as some devices may use inverted orientation."}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-View","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapOptions"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/mbmmapoptions\/viewportmode"]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map-View":{"title":"MapView","abstract":[],"kind":"article","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-View","url":"\/documentation\/mapboxmaps\/map-view","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMMapOptions/viewportMode":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapOptions\/viewportMode","url":"\/documentation\/mapboxmaps\/mbmmapoptions\/viewportmode","title":"viewportMode","fragments":[{"text":"viewportMode","kind":"identifier"}],"abstract":[{"type":"text","text":"The viewport mode. This can be used to flip the vertical"},{"type":"text","text":" "},{"type":"text","text":"orientation of the map as some devices may use inverted orientation."}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","abstract":[],"url":"\/documentation\/overview","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"url":"\/documentation\/mapboxmaps","role":"collection","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapOptions":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapOptions","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Describes the map option values."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapOptions"}],"url":"\/documentation\/mapboxmaps\/mapoptions","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MapOptions"}],"title":"MapOptions"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapOptions\/title","op":"replace","value":"MBMMapOptions"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapOptions\/fragments","op":"replace","value":[{"text":"MBMMapOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapOptions\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMMapOptions"}]}]}]}