{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoaded"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":" * ","kind":"text"},{"text":"loaded","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"inlineContent":[{"text":"Note: The property will be null for the ","type":"text"},{"type":"codeVoice","code":"type"},{"text":" other than ","type":"text"},{"type":"codeVoice","code":"SourceDataLoadedType.Tile"},{"text":".","type":"text"}],"type":"paragraph"}]}],"sections":[],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMSourceDataLoaded\/loaded","interfaceLanguage":"occ"},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/mapboxmaps\/mbmsourcedataloaded\/loaded"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:objc(cs)MBMSourceDataLoaded(py)loaded","title":"loaded","navigatorTitle":[{"text":"loaded","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"loaded","kind":"identifier"}],"modules":[{"name":"MapboxMaps"}]},"abstract":[{"text":"When the ","type":"text"},{"code":"type","type":"codeVoice"},{"text":" of an event is ","type":"text"},{"code":"SourceDataLoadedType.Tile","type":"codeVoice"},{"text":", the ","type":"text"},{"code":"loaded","type":"codeVoice"},{"text":" ","type":"text"},{"text":"property will be set to ","type":"text"},{"code":"true","type":"codeVoice"},{"text":" if all source data required for the visible","type":"text"},{"text":" ","type":"text"},{"text":"viewport of the ","type":"text"},{"code":"map","type":"codeVoice"},{"text":" are loaded.","type":"text"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"abstract":[{"type":"text","text":"The simplified diagram of the events emitted by the map is displayed below."}],"title":"Map events","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","kind":"article","url":"\/documentation\/mapboxmaps\/events","role":"collectionGroup","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"url":"\/documentation\/mapboxmaps","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","title":"MapboxMaps","kind":"symbol","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMSourceDataLoaded/loaded":{"type":"topic","fragments":[{"text":"loaded","kind":"identifier"}],"kind":"symbol","title":"loaded","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMSourceDataLoaded\/loaded","url":"\/documentation\/mapboxmaps\/mbmsourcedataloaded\/loaded","abstract":[{"text":"When the ","type":"text"},{"code":"type","type":"codeVoice"},{"text":" of an event is ","type":"text"},{"code":"SourceDataLoadedType.Tile","type":"codeVoice"},{"text":", the ","type":"text"},{"code":"loaded","type":"codeVoice"},{"text":" ","type":"text"},{"text":"property will be set to ","type":"text"},{"code":"true","type":"codeVoice"},{"text":" if all source data required for the visible","type":"text"},{"text":" ","type":"text"},{"text":"viewport of the ","type":"text"},{"code":"map","type":"codeVoice"},{"text":" are loaded.","type":"text"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceDataLoaded":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SourceDataLoaded"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoaded","url":"\/documentation\/mapboxmaps\/sourcedataloaded","kind":"symbol","abstract":[{"text":"The ","type":"text"},{"code":"SourceDataLoaded","type":"codeVoice"},{"text":" event is emitted when source data is loaded.","type":"text"}],"type":"topic","title":"SourceDataLoaded","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceDataLoaded"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"url":"\/documentation\/overview","kind":"article","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","type":"topic"}},"variantOverrides":[{"patch":[{"value":"MBMSourceDataLoaded","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoaded\/title","op":"replace"},{"value":[{"text":"MBMSourceDataLoaded","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoaded\/fragments","op":"replace"},{"value":[{"text":"MBMSourceDataLoaded","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoaded\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}