{"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions\/lookAtPoint(forLocation:altitude:upVector:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions"]]},"abstract":[{"text":"Helper function for setting orientation of the camera by defining a focus point.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/freecameraoptions\/lookatpoint(forlocation:altitude:upvector:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/freecameraoptions\/lookatpoint(forlocation:altitude:upvector:)"]}],"metadata":{"title":"lookAtPoint(forLocation:altitude:upVector:)","navigatorTitle":[{"text":"lookAtPointForLocation:altitude:upVector:","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"MapboxMaps"}],"role":"symbol","externalID":"c:objc(cs)MBMFreeCameraOptions(im)lookAtPointForLocation:altitude:upVector:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lookAtPoint","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forLocation","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"altitude","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"text":"upVector","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Vec3","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMVec3"},{"text":")","kind":"text"}],"roleHeading":"Instance Method"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lookAtPoint","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forLocation","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"location","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"text":", ","kind":"text"},{"text":"altitude","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"text":"upVector","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Vec3","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Vec3","preciseIdentifier":"c:objc(cs)MBMVec3"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"location","content":[{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"coordinate"},{"text":" representing focal point.","type":"text"}]}]},{"name":"altitude","content":[{"inlineContent":[{"type":"text","text":"The altitude in meters of the focal point."}],"type":"paragraph"}]},{"name":"upVector","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The up vector."}]}]}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Up vector is required in certain scenarios where bearing can’t be deduced from"},{"type":"text","text":" "},{"type":"text","text":"the viewing direction."}]},{"type":"paragraph","inlineContent":[{"text":"Note: Orientation can be invalid after this call, if the input leads to the camera being upside down or the quaternion has zero length.","type":"text"}]}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","type":"topic","abstract":[],"title":"MapboxMaps Documentation","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","role":"collection","title":"MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FreeCameraOptions/lookAtPoint(forLocation:altitude:upVector:)":{"role":"symbol","kind":"symbol","title":"lookAtPoint(forLocation:altitude:upVector:)","url":"\/documentation\/mapboxmaps\/freecameraoptions\/lookatpoint(forlocation:altitude:upvector:)","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions\/lookAtPoint(forLocation:altitude:upVector:)","abstract":[{"text":"Helper function for setting orientation of the camera by defining a focus point.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"lookAtPoint"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forLocation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D"},{"kind":"text","text":", "},{"kind":"externalParam","text":"altitude"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"upVector"},{"text":": ","kind":"text"},{"text":"Vec3","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMVec3"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"lookAtPointForLocation:altitude:upVector:","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Vec3":{"navigatorTitle":[{"text":"Vec3","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Vec3","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/vec3","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Vec3","kind":"symbol","abstract":[{"type":"text","text":"3 component vector."}],"title":"Vec3","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"title":"MapboxMap","url":"\/documentation\/mapboxmaps\/mapboxmap-apis","type":"topic","kind":"article","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FreeCameraOptions":{"abstract":[{"type":"text","text":"Various options for accessing physical properties of the underlying camera entity."},{"type":"text","text":" "},{"type":"text","text":"A direct access to these properties allows more flexible and precise controlling"},{"type":"text","text":" "},{"type":"text","text":"of the camera while also being fully compatible and interchangeable with CameraOptions."},{"type":"text","text":" "},{"type":"text","text":"All fields are optional."}],"type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/freecameraoptions","title":"FreeCameraOptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FreeCameraOptions","kind":"identifier"}],"navigatorTitle":[{"text":"FreeCameraOptions","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"lookAtPointForLocation:altitude:upVector:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"lookAtPointForLocation:altitude:upVector:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"lookAtPointForLocation:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"location","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"altitude:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","preciseIdentifier":"c:d","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"altitude","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"upVector:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Vec3","text":"MBMVec3","preciseIdentifier":"c:objc(cs)MBMVec3","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"upVector","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"parameters":[{"name":"location","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"code":"coordinate","type":"codeVoice"},{"type":"text","text":" representing focal point."}]}]},{"name":"altitude","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The altitude in meters of the focal point."}]}]},{"name":"upVector","content":[{"inlineContent":[{"type":"text","text":"The up vector."}],"type":"paragraph"}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"value":"lookAtPointForLocation:altitude:upVector:","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions~1lookAtPoint(forLocation:altitude:upVector:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"lookAtPointForLocation:altitude:upVector:"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions~1lookAtPoint(forLocation:altitude:upVector:)\/fragments","op":"replace"},{"value":"MBMVec3","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Vec3\/title","op":"replace"},{"value":[{"text":"MBMVec3","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Vec3\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MBMVec3"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Vec3\/navigatorTitle","op":"replace"},{"value":"MBMFreeCameraOptions","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions\/title","op":"replace"},{"value":[{"text":"MBMFreeCameraOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions\/fragments","op":"replace"},{"value":[{"text":"MBMFreeCameraOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions\/navigatorTitle","op":"replace"}]}]}