{"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","metadata":{"modules":[{"name":"MapboxMaps"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"inOfflineMode","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MBMRequestErrorTypeInOfflineMode"}],"roleHeading":"Case","title":"RequestErrorType.inOfflineMode","symbolKind":"case","role":"symbol","externalID":"c:@E@MBMRequestErrorType@MBMRequestErrorTypeInOfflineMode"},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestErrorType\/inOfflineMode","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The resource cannot be loaded because the device is in offline mode."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"inOfflineMode","kind":"identifier"}]}]}],"variants":[{"paths":["\/documentation\/mapboxmaps\/requesterrortype\/inofflinemode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/requesterrortype\/inofflinemode"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMapsInternal","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestErrorType"]]},"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestErrorType":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestErrorType","title":"RequestErrorType","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"RequestErrorType"}],"url":"\/documentation\/mapboxmaps\/requesterrortype","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RequestErrorType","kind":"identifier"}],"abstract":[{"type":"text","text":"The enumeration defines the error type that may occur during a resource request."}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestErrorType/inOfflineMode":{"kind":"symbol","title":"RequestErrorType.inOfflineMode","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestErrorType\/inOfflineMode","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"inOfflineMode"}],"navigatorTitle":[{"text":"MBMRequestErrorTypeInOfflineMode","kind":"identifier"}],"abstract":[{"text":"The resource cannot be loaded because the device is in offline mode.","type":"text"}],"role":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/requesterrortype\/inofflinemode"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMapsInternal":{"title":"CoreMaps - Internal","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMapsInternal","kind":"article","url":"\/documentation\/mapboxmaps\/coremapsinternal","type":"topic","abstract":[{"type":"text","text":"Maps rendering SDK also known as GL-Native. These are for internal use only."}],"role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"MBMRequestErrorTypeInOfflineMode","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MBMRequestErrorTypeInOfflineMode"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"MBMRequestErrorTypeInOfflineMode","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestErrorType\/title","value":"MBMRequestErrorType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestErrorType\/fragments","value":[{"kind":"identifier","text":"MBMRequestErrorType"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestErrorType~1inOfflineMode\/title","value":"MBMRequestErrorTypeInOfflineMode","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestErrorType~1inOfflineMode\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMRequestErrorTypeInOfflineMode"}]}]}]}