{"kind":"symbol","abstract":[{"type":"text","text":"Initializes a "},{"type":"codeVoice","code":"ViewAnnotationOptions"},{"text":" with geometry.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"geometry"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Turf\/GeometryConvertible","preciseIdentifier":"s:4Turf19GeometryConvertibleP","text":"GeometryConvertible"},{"kind":"text","text":")? = nil, "},{"kind":"externalParam","text":"width"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"text":"? = nil, ","kind":"text"},{"text":"height","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"associatedFeatureId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"? = nil, "},{"text":"allowOverlap","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"visible"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":"? = nil, "},{"text":"anchor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ViewAnnotationAnchor","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchor","preciseIdentifier":"c:@E@MBMViewAnnotationAnchor"},{"text":"? = nil, ","kind":"text"},{"text":"offsetX","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":"? = nil, ","kind":"text"},{"text":"offsetY","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"selected"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":"? = nil)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"s:10MapboxMaps21ViewAnnotationOptionsV8geometry5width6height19associatedFeatureId12allowOverlap7visible6anchor7offsetX0P1Y8selectedAC4Turf19GeometryConvertible_pSg_14CoreFoundation7CGFloatVSgATSSSgSbSgAVSo07MBMViewD6AnchorVSgA2tVtcfc","platforms":[],"roleHeading":"Initializer","modules":[{"name":"MapboxMaps"}],"role":"symbol","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"geometry"},{"text":": (any ","kind":"text"},{"text":"GeometryConvertible","kind":"typeIdentifier","preciseIdentifier":"s:4Turf19GeometryConvertibleP"},{"kind":"text","text":")?, "},{"text":"width","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":"?, "},{"text":"height","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"kind":"text","text":"?, "},{"text":"associatedFeatureId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"allowOverlap"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"visible"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":"?, ","kind":"text"},{"text":"anchor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@MBMViewAnnotationAnchor","kind":"typeIdentifier","text":"ViewAnnotationAnchor"},{"text":"?, ","kind":"text"},{"text":"offsetX","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"offsetY"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"kind":"text","text":"?, "},{"text":"selected","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"title":"init(geometry:width:height:associatedFeatureId:allowOverlap:visible:anchor:offsetX:offsetY:selected:)"},"sections":[],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use ViewAnnotation to create view annotations."}]}],"variants":[{"paths":["\/documentation\/mapboxmaps\/viewannotationoptions\/init(geometry:width:height:associatedfeatureid:allowoverlap:visible:anchor:offsetx:offsety:selected:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationOptions\/init(geometry:width:height:associatedFeatureId:allowOverlap:visible:anchor:offsetX:offsetY:selected:)"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/View-Annotations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationOptions"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationOptions/init(geometry:width:height:associatedFeatureId:allowOverlap:visible:anchor:offsetX:offsetY:selected:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"geometry"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","text":"GeometryConvertible","preciseIdentifier":"s:4Turf19GeometryConvertibleP"},{"kind":"text","text":")?, "},{"text":"width","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"height"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":"?, "},{"text":"associatedFeatureId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"text":"allowOverlap","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"visible"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"anchor","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@MBMViewAnnotationAnchor","kind":"typeIdentifier","text":"ViewAnnotationAnchor"},{"text":"?, ","kind":"text"},{"text":"offsetX","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"offsetY"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":"?, ","kind":"text"},{"text":"selected","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":"?)","kind":"text"}],"deprecated":true,"abstract":[{"type":"text","text":"Initializes a "},{"type":"codeVoice","code":"ViewAnnotationOptions"},{"type":"text","text":" with geometry."}],"url":"\/documentation\/mapboxmaps\/viewannotationoptions\/init(geometry:width:height:associatedfeatureid:allowoverlap:visible:anchor:offsetx:offsety:selected:)","role":"symbol","title":"init(geometry:width:height:associatedFeatureId:allowOverlap:visible:anchor:offsetX:offsetY:selected:)","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationOptions\/init(geometry:width:height:associatedFeatureId:allowOverlap:visible:anchor:offsetX:offsetY:selected:)","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"title":"MapboxMaps","role":"collection","url":"\/documentation\/mapboxmaps","type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationOptions":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationOptions","type":"topic","title":"ViewAnnotationOptions","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"ViewAnnotationOptions","kind":"identifier"}],"abstract":[{"text":"Stores layout and visibility settings for a view annotation.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ViewAnnotationOptions"}],"url":"\/documentation\/mapboxmaps\/viewannotationoptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationAnchor":{"navigatorTitle":[{"text":"ViewAnnotationAnchor","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ViewAnnotationAnchor"}],"abstract":[{"text":"Enum describing how to place view annotation relatively to geometry.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchor","url":"\/documentation\/mapboxmaps\/viewannotationanchor","title":"ViewAnnotationAnchor","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/View-Annotations":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/View-Annotations","role":"collectionGroup","type":"topic","kind":"article","title":"View Annotations","abstract":[],"url":"\/documentation\/mapboxmaps\/view-annotations"},"doc://com.mapbox.MapboxMaps/documentation/Turf/GeometryConvertible":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"GeometryConvertible","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Turf\/GeometryConvertible","navigatorTitle":[{"kind":"identifier","text":"GeometryConvertible"}],"url":"\/documentation\/turf\/geometryconvertible","abstract":[{"type":"text","text":"A type that can be represented as a "},{"type":"codeVoice","code":"Geometry"},{"type":"text","text":" instance."}],"title":"GeometryConvertible","type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"title":"MapboxMaps Documentation","role":"collection","url":"\/documentation\/overview","type":"topic","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchor\/title","value":"MBMViewAnnotationAnchor","op":"replace"},{"value":[{"text":"MBMViewAnnotationAnchor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchor\/fragments"},{"value":[{"kind":"identifier","text":"MBMViewAnnotationAnchor"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchor\/navigatorTitle","op":"replace"}]}]}