{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Settings-and-Constants","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceStorageType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceStorageType\/RawRepresentable-Implementations"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceStorageType\/hashValue"},"sections":[],"metadata":{"title":"hashValue","modules":[{"relatedModules":["Swift"],"name":"MapboxCommon"}],"extendedModule":"Swift","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"symbolKind":"property","conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"externalID":"s:SYsSHRzSH8RawValueSYRpzrlE04hashB0Sivp::SYNTHESIZED::c:@E@MBXSettingsServiceStorageType","role":"symbol"},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"RawRepresentable.hashValue","type":"codeVoice"},{"text":".","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/settingsservicestoragetype\/hashvalue"]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"type":"topic","url":"\/documentation\/mapboxmaps","role":"collection","kind":"symbol","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsServiceStorageType/RawRepresentable-Implementations":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceStorageType\/RawRepresentable-Implementations","role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"type":"topic","kind":"article","url":"\/documentation\/mapboxcommon\/settingsservicestoragetype\/rawrepresentable-implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Settings-and-Constants":{"url":"\/documentation\/mapboxmaps\/settings-and-constants","type":"topic","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Settings-and-Constants","title":"Settings and Constants","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsServiceStorageType":{"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SettingsServiceStorageType"}],"navigatorTitle":[{"kind":"identifier","text":"SettingsServiceStorageType"}],"url":"\/documentation\/mapboxcommon\/settingsservicestoragetype","title":"SettingsServiceStorageType","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceStorageType","abstract":[{"type":"text","text":"Enum that contains possible storage types that can be used for settings service."}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsServiceStorageType/hashValue":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceStorageType\/hashValue","url":"\/documentation\/mapboxcommon\/settingsservicestoragetype\/hashvalue","abstract":[],"type":"topic","conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}]},"title":"hashValue","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","url":"\/documentation\/overview","role":"collection","abstract":[],"kind":"article"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceStorageType\/title","value":"MBXSettingsServiceStorageType"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceStorageType\/fragments","value":[{"kind":"identifier","text":"MBXSettingsServiceStorageType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceStorageType\/navigatorTitle","value":[{"kind":"identifier","text":"MBXSettingsServiceStorageType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}