{"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/mapboxcommon\/mbxlocationproviderrequest\/accuracy"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxcommon\/mbxlocationproviderrequest\/accuracy"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXLocationProviderRequest\/accuracy","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"accuracy"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProviderRequest"]]},"metadata":{"symbolKind":"property","role":"symbol","modules":[{"name":"MapboxCommon"}],"navigatorTitle":[{"kind":"identifier","text":"accuracy"}],"externalID":"c:objc(cs)MBXLocationProviderRequest(py)accuracy","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accuracy"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"title":"accuracy"},"abstract":[{"text":"The accuracy of the observed location","type":"text"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationProviderRequest":{"url":"\/documentation\/mapboxcommon\/locationproviderrequest","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"LocationProviderRequest","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"LocationProviderRequest"}],"type":"topic","role":"symbol","title":"LocationProviderRequest","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProviderRequest","abstract":[{"text":"Data model that contains parameters for location requests.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Location-APIs":{"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","role":"collectionGroup","title":"Location","url":"\/documentation\/mapboxmaps\/location-apis","type":"topic","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXLocationProviderRequest/accuracy":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"accuracy"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXLocationProviderRequest\/accuracy","abstract":[{"text":"The accuracy of the observed location","type":"text"}],"url":"\/documentation\/mapboxcommon\/mbxlocationproviderrequest\/accuracy","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accuracy"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"accuracy"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"accuracy"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"accuracy"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":" * ","kind":"text"},{"text":"accuracy","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProviderRequest\/title","value":"MBXLocationProviderRequest","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProviderRequest\/fragments","value":[{"text":"MBXLocationProviderRequest","kind":"identifier"}]},{"value":"accuracy","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MBXLocationProviderRequest~1accuracy\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MBXLocationProviderRequest~1accuracy\/fragments","op":"replace","value":[{"kind":"identifier","text":"accuracy"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}