{"abstract":[{"text":"Interval for active location updates.","type":"text"}],"variants":[{"paths":["\/documentation\/mapboxcommon\/mbxlocationproviderrequest\/interval"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/mbxlocationproviderrequest\/interval"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"interval","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/IntervalSettings","text":"IntervalSettings","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXIntervalSettings"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","navigatorTitle":[{"text":"interval","kind":"identifier"}],"modules":[{"name":"MapboxCommon"}],"roleHeading":"Instance Property","title":"interval","externalID":"c:objc(cs)MBXLocationProviderRequest(py)interval","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"interval","kind":"identifier"},{"text":": ","kind":"text"},{"text":"IntervalSettings","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXIntervalSettings"},{"text":"?","kind":"text"}],"symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProviderRequest"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXLocationProviderRequest\/interval"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/IntervalSettings":{"url":"\/documentation\/mapboxcommon\/intervalsettings","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntervalSettings"}],"navigatorTitle":[{"text":"IntervalSettings","kind":"identifier"}],"type":"topic","role":"symbol","title":"IntervalSettings","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/IntervalSettings","abstract":[{"type":"text","text":"The interval for active location updates"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationProviderRequest":{"url":"\/documentation\/mapboxcommon\/locationproviderrequest","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"LocationProviderRequest","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"LocationProviderRequest"}],"type":"topic","role":"symbol","title":"LocationProviderRequest","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProviderRequest","abstract":[{"text":"Data model that contains parameters for location requests.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXLocationProviderRequest/interval":{"role":"symbol","abstract":[{"type":"text","text":"Interval for active location updates."}],"navigatorTitle":[{"text":"interval","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXLocationProviderRequest\/interval","type":"topic","url":"\/documentation\/mapboxcommon\/mbxlocationproviderrequest\/interval","title":"interval","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"interval","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBXIntervalSettings","text":"IntervalSettings","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Location-APIs":{"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","role":"collectionGroup","title":"Location","url":"\/documentation\/mapboxmaps\/location-apis","type":"topic","kind":"article"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"interval"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","value":[{"text":"interval","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"MBXIntervalSettings","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/IntervalSettings","preciseIdentifier":"c:objc(cs)MBXIntervalSettings","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"interval"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1IntervalSettings\/title","op":"replace","value":"MBXIntervalSettings"},{"value":[{"text":"MBXIntervalSettings","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1IntervalSettings\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProviderRequest\/title","value":"MBXLocationProviderRequest","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProviderRequest\/fragments","value":[{"text":"MBXLocationProviderRequest","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"interval","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MBXLocationProviderRequest~1interval\/title"},{"value":[{"kind":"identifier","text":"interval"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MBXLocationProviderRequest~1interval\/fragments"}]}]}