{"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mapRenderDurationStatistics"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DurationStatistics","preciseIdentifier":"c:objc(cs)MBMDurationStatistics"}],"navigatorTitle":[{"kind":"identifier","text":"mapRenderDurationStatistics"}],"role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MBMPerformanceStatistics(py)mapRenderDurationStatistics","modules":[{"name":"MapboxMaps"}],"roleHeading":"Instance Property","title":"mapRenderDurationStatistics"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatistics"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"The CPU timeline duration statistics of the map render call."}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatistics\/mapRenderDurationStatistics","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/performancestatistics\/maprenderdurationstatistics"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/performancestatistics\/maprenderdurationstatistics"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mapRenderDurationStatistics"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/DurationStatistics","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMDurationStatistics","text":"DurationStatistics"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Performance":{"abstract":[],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","role":"collectionGroup","title":"Performance and investigations","url":"\/documentation\/mapboxmaps\/performance","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","role":"collection","type":"topic","abstract":[],"title":"MapboxMaps Documentation","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","url":"\/documentation\/mapboxmaps","title":"MapboxMaps","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PerformanceStatistics/mapRenderDurationStatistics":{"title":"mapRenderDurationStatistics","navigatorTitle":[{"text":"mapRenderDurationStatistics","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatistics\/mapRenderDurationStatistics","type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/performancestatistics\/maprenderdurationstatistics","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mapRenderDurationStatistics","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DurationStatistics","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMDurationStatistics"}],"role":"symbol","abstract":[{"text":"The CPU timeline duration statistics of the map render call.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/DurationStatistics":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DurationStatistics","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/DurationStatistics","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DurationStatistics","kind":"identifier"}],"title":"DurationStatistics","url":"\/documentation\/mapboxmaps\/durationstatistics"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PerformanceStatistics":{"abstract":[{"text":"The performance statistics collected at the end of the sampling duration.","type":"text"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/performancestatistics","type":"topic","role":"symbol","navigatorTitle":[{"text":"PerformanceStatistics","kind":"identifier"}],"title":"PerformanceStatistics","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatistics","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PerformanceStatistics","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"mapRenderDurationStatistics","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"mapRenderDurationStatistics","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/DurationStatistics","text":"MBMDurationStatistics","preciseIdentifier":"c:objc(cs)MBMDurationStatistics","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"mapRenderDurationStatistics","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatistics~1mapRenderDurationStatistics\/title","value":"mapRenderDurationStatistics","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatistics~1mapRenderDurationStatistics\/fragments","value":[{"kind":"identifier","text":"mapRenderDurationStatistics"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1DurationStatistics\/title","op":"replace","value":"MBMDurationStatistics"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1DurationStatistics\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMDurationStatistics"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1DurationStatistics\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMDurationStatistics"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatistics\/title","op":"replace","value":"MBMPerformanceStatistics"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatistics\/fragments","op":"replace","value":[{"text":"MBMPerformanceStatistics","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatistics\/navigatorTitle","op":"replace","value":[{"text":"MBMPerformanceStatistics","kind":"identifier"}]}]}]}