{"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hasher","preciseIdentifier":"s:s6HasherV","kind":"typeIdentifier"},{"kind":"text","text":")"}],"modules":[{"relatedModules":["Swift"],"name":"MapboxCommon"}],"role":"symbol","externalID":"s:SYsSHRzSH8RawValueSYRpzrlE4hash4intoys6HasherVz_tF::SYNTHESIZED::c:@E@MBXTileRegionErrorType","symbolKind":"method","roleHeading":"Instance Method","extendedModule":"Swift","title":"hash(into:)","conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]}},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"text":" ","kind":"text"},{"text":"hasher","kind":"internalParam"},{"kind":"text","text":": "},{"text":"inout","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV","text":"Hasher"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType\/RawRepresentable-Implementations"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType\/hash(into:)"},"sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.hash(into:)"},{"type":"text","text":"."}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/tileregionerrortype\/hash(into:)"]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","abstract":[],"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","kind":"article","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"title":"MapboxCommon","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/mapboxcommon","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionErrorType/hash(into:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"kind":"text","text":": "},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:s6HasherV","text":"Hasher","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol","kind":"symbol","url":"\/documentation\/mapboxcommon\/tileregionerrortype\/hash(into:)","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType\/hash(into:)","title":"hash(into:)","conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"text":".","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}]}},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionErrorType/RawRepresentable-Implementations":{"role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType\/RawRepresentable-Implementations","url":"\/documentation\/mapboxcommon\/tileregionerrortype\/rawrepresentable-implementations","title":"RawRepresentable Implementations","type":"topic","abstract":[],"kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionErrorType":{"role":"symbol","url":"\/documentation\/mapboxcommon\/tileregionerrortype","type":"topic","title":"TileRegionErrorType","kind":"symbol","abstract":[{"type":"text","text":"Describes the reason for a tile region download request failure."}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileRegionErrorType"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType","navigatorTitle":[{"kind":"identifier","text":"TileRegionErrorType"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionErrorType\/title","op":"replace","value":"MBXTileRegionErrorType"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionErrorType\/fragments","value":[{"kind":"identifier","text":"MBXTileRegionErrorType"}]},{"op":"replace","value":[{"kind":"identifier","text":"MBXTileRegionErrorType"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionErrorType\/navigatorTitle"}]}]}