{"metadata":{"symbolKind":"enum","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"CustomRasterSourceClientType","kind":"identifier"}],"roleHeading":"Enumeration","externalID":"c:@E@MBMCustomRasterSourceClientType","title":"CustomRasterSourceClientType","role":"symbol","modules":[{"name":"MapboxMaps"}],"navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceClientType"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources"]]},"topicSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType\/customRasterSourceTileRenderer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType\/customRasterSourceTileStatusChangedCallback"],"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases"},{"title":"Initializers","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType\/init(rawValue:)"],"anchor":"Initializers","generated":true},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType\/Equatable-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations","anchor":"Default-Implementations"}],"variants":[{"paths":["\/documentation\/mapboxmaps\/customrastersourceclienttype"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/customrastersourceclienttype"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CustomRasterSourceClientType"}]}],"kind":"declarations"}],"seeAlsoSections":[{"anchor":"Sources","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Source","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceInfo","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSourceData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterArraySource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/VectorSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PromoteId","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Scheme","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Encoding","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatusChangedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatus","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileFunctionCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetSize"],"generated":true,"title":"Sources"}],"sections":[],"relationshipsSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/s15BitwiseCopyableP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH","doc:\/\/com.mapbox.MapboxMaps\/SY","doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileData":{"abstract":[{"type":"text","text":"Data for a specific CustomRasterSource tile."}],"kind":"symbol","title":"CustomRasterSourceTileData","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CustomRasterSourceTileData","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/customrastersourcetiledata","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileData","navigatorTitle":[{"text":"CustomRasterSourceTileData","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ImageSource":{"abstract":[{"type":"text","text":"An image data source."}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/imagesource","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"ImageSource","kind":"identifier"}],"navigatorTitle":[{"text":"ImageSource","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageSource","title":"ImageSource"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","type":"topic","title":"MapboxMaps","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterSource":{"role":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/rastersource","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RasterSource"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterSource","navigatorTitle":[{"kind":"identifier","text":"RasterSource"}],"kind":"symbol","abstract":[{"type":"text","text":"A raster tile source."}],"title":"RasterSource"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GeoJSONSource":{"type":"topic","url":"\/documentation\/mapboxmaps\/geojsonsource","abstract":[{"text":"A GeoJSON data source.","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"GeoJSONSource","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSource","title":"GeoJSONSource","navigatorTitle":[{"text":"GeoJSONSource","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceClientType/RawRepresentable-Implementations":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/customrastersourceclienttype\/rawrepresentable-implementations","kind":"article","abstract":[]},"doc://com.mapbox.MapboxMaps/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Source":{"navigatorTitle":[{"text":"Source","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Source"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Source","title":"Source","role":"symbol","url":"\/documentation\/mapboxmaps\/source","kind":"symbol","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudgetSize":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetSize","title":"TileCacheBudgetSize","kind":"symbol","url":"\/documentation\/mapboxmaps\/tilecachebudgetsize","abstract":[{"type":"text","text":"Defines a TileCacheBudgetSize, which can be set as either a megabyte or tile count limit."},{"text":" ","type":"text"},{"type":"text","text":"Whenever tile cache goes over the defined limit"},{"text":" ","type":"text"},{"type":"text","text":"the least recently used tile will be evicted from the in-memory cache"}],"navigatorTitle":[{"text":"TileCacheBudgetSize","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TileCacheBudgetSize","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GeoJSONSourceData":{"type":"topic","url":"\/documentation\/mapboxmaps\/geojsonsourcedata","abstract":[{"type":"text","text":"Captures potential values of the "},{"type":"codeVoice","code":"data"},{"text":" property of a GeoJSONSource.","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GeoJSONSourceData","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSourceData","title":"GeoJSONSourceData","navigatorTitle":[{"text":"GeoJSONSourceData","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceClientType":{"abstract":[],"kind":"symbol","title":"CustomRasterSourceClientType","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"CustomRasterSourceClientType","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/customrastersourceclienttype","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType","navigatorTitle":[{"text":"CustomRasterSourceClientType","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceClient":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient","type":"topic","abstract":[],"kind":"symbol","url":"\/documentation\/mapboxmaps\/customrastersourceclient","title":"CustomRasterSourceClient","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CustomRasterSourceClient","kind":"identifier"}],"navigatorTitle":[{"text":"CustomRasterSourceClient","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PromoteId":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PromoteId","title":"PromoteId","kind":"symbol","url":"\/documentation\/mapboxmaps\/promoteid","abstract":[],"navigatorTitle":[{"text":"PromoteId","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PromoteId","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileStatus":{"navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceTileStatus"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CustomRasterSourceTileStatus"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatus","title":"CustomRasterSourceTileStatus","role":"symbol","url":"\/documentation\/mapboxmaps\/customrastersourcetilestatus","kind":"symbol","abstract":[{"type":"text","text":"CustomRasterSource tile status."}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","abstract":[],"url":"\/documentation\/overview","role":"collection","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceInfo":{"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SourceInfo","kind":"identifier"}],"title":"SourceInfo","url":"\/documentation\/mapboxmaps\/sourceinfo","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SourceInfo"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceInfo","kind":"symbol","abstract":[{"type":"text","text":"Information about a Source"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Encoding":{"role":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/encoding","title":"Encoding","abstract":[{"type":"text","text":"The encoding used by this source. Mapbox Terrain RGB is used by default"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"Encoding","kind":"identifier"}],"navigatorTitle":[{"text":"Encoding","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Encoding"},"doc://com.mapbox.MapboxMaps/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"},"doc://com.mapbox.MapboxMaps/s15BitwiseCopyableP":{"title":"Swift.BitwiseCopyable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s15BitwiseCopyableP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceClientType/Equatable-Implementations":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType\/Equatable-Implementations","title":"Equatable Implementations","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/customrastersourceclienttype\/equatable-implementations","kind":"article","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/VectorSource":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/VectorSource","type":"topic","abstract":[{"type":"text","text":"A vector tile source."}],"kind":"symbol","title":"VectorSource","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VectorSource","kind":"identifier"}],"navigatorTitle":[{"text":"VectorSource","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/vectorsource"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterArraySource":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterArraySource","type":"topic","abstract":[{"type":"text","text":"A raster array source"}],"kind":"symbol","title":"RasterArraySource","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RasterArraySource","kind":"identifier"}],"navigatorTitle":[{"text":"RasterArraySource","kind":"identifier"}],"tags":[{"type":"spi","text":"SPI"}],"url":"\/documentation\/mapboxmaps\/rasterarraysource"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSource":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomRasterSource","kind":"identifier"}],"abstract":[{"type":"text","text":"Describes a Custom Raster Source to be used in the style."}],"title":"CustomRasterSource","url":"\/documentation\/mapboxmaps\/customrastersource","navigatorTitle":[{"text":"CustomRasterSource","kind":"identifier"}],"kind":"symbol","type":"topic","tags":[{"text":"SPI","type":"spi"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSource"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileStatusChangedCallback":{"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"CustomRasterSourceTileStatusChangedCallback","kind":"identifier"}],"title":"CustomRasterSourceTileStatusChangedCallback","url":"\/documentation\/mapboxmaps\/customrastersourcetilestatuschangedcallback","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceTileStatusChangedCallback"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatusChangedCallback","kind":"symbol","abstract":[{"type":"text","text":"Callback for changing a CustomRasterSource tile status."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomGeometrySourceOptions":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomGeometrySourceOptions"}],"abstract":[{"type":"text","text":"Options for custom geometry source."}],"title":"CustomGeometrySourceOptions","url":"\/documentation\/mapboxmaps\/customgeometrysourceoptions","navigatorTitle":[{"kind":"identifier","text":"CustomGeometrySourceOptions"}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceClientType/customRasterSourceTileRenderer":{"navigatorTitle":[{"text":"MBMCustomRasterSourceClientTypeCustomRasterSourceTileRenderer","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"customRasterSourceTileRenderer","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType\/customRasterSourceTileRenderer","title":"CustomRasterSourceClientType.customRasterSourceTileRenderer","role":"symbol","url":"\/documentation\/mapboxmaps\/customrastersourceclienttype\/customrastersourcetilerenderer","kind":"symbol","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Sources":{"role":"collectionGroup","url":"\/documentation\/mapboxmaps\/sources","title":"Sources","type":"topic","abstract":[],"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceType":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SourceType"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/sourcetype","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceType","abstract":[{"type":"text","text":"Struct of supported Source Types"},{"type":"text","text":" "},{"type":"text","text":"Docs : https:\/\/docs.mapbox.com\/mapbox-gl-js\/style-spec\/sources\/"}],"title":"SourceType","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceType"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileFunctionCallback":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileFunctionCallback","kind":"symbol","title":"TileFunctionCallback","url":"\/documentation\/mapboxmaps\/tilefunctioncallback","abstract":[{"text":"Callback to do various operations for tile.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"For example, fetching a tile or cancelling a tile request."}],"navigatorTitle":[{"kind":"identifier","text":"TileFunctionCallback"}],"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TileFunctionCallback"}],"type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceClientType/init(rawValue:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}],"title":"init(rawValue:)","url":"\/documentation\/mapboxmaps\/customrastersourceclienttype\/init(rawvalue:)","role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType\/init(rawValue:)","kind":"symbol","abstract":[]},"doc://com.mapbox.MapboxMaps/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SY"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceClientType/customRasterSourceTileStatusChangedCallback":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"customRasterSourceTileStatusChangedCallback","kind":"identifier"}],"title":"CustomRasterSourceClientType.customRasterSourceTileStatusChangedCallback","url":"\/documentation\/mapboxmaps\/customrastersourceclienttype\/customrastersourcetilestatuschangedcallback","role":"symbol","navigatorTitle":[{"text":"MBMCustomRasterSourceClientTypeCustomRasterSourceTileStatusChangedCallback","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType\/customRasterSourceTileStatusChangedCallback","kind":"symbol","abstract":[]},"doc://com.mapbox.MapboxMaps/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Scheme":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Scheme","kind":"identifier"}],"title":"Scheme","url":"\/documentation\/mapboxmaps\/scheme","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Scheme"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Scheme","kind":"symbol","abstract":[{"type":"text","text":"Influences the y direction of the tile coordinates. The global-mercator (aka Spherical Mercator) profile is assumed."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomGeometrySource":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySource","type":"topic","abstract":[{"type":"text","text":"Describes a Custom Geometry Source to be used in the style"}],"kind":"symbol","title":"CustomGeometrySource","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomGeometrySource","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CustomGeometrySource"}],"url":"\/documentation\/mapboxmaps\/customgeometrysource"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceOptions":{"abstract":[{"type":"text","text":"Options for custom raster source."}],"navigatorTitle":[{"text":"CustomRasterSourceOptions","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxmaps\/customrastersourceoptions","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions","title":"CustomRasterSourceOptions","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomRasterSourceOptions"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterDemSource":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RasterDemSource","kind":"identifier"}],"abstract":[{"type":"text","text":"A RGB-encoded raster DEM source"}],"role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"text":"RasterDemSource","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource","url":"\/documentation\/mapboxmaps\/rasterdemsource","title":"RasterDemSource"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileRenderer":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer","abstract":[{"text":"Interface for the direct rendering into the custom raster tiles.","type":"text"}],"role":"symbol","title":"CustomRasterSourceTileRenderer","type":"topic","url":"\/documentation\/mapboxmaps\/customrastersourcetilerenderer","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CustomRasterSourceTileRenderer"}],"navigatorTitle":[{"text":"CustomRasterSourceTileRenderer","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"value":"MBMCustomRasterSourceClientType","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","value":[{"text":"MBMCustomRasterSourceClientType","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MBMCustomRasterSourceClientType"}],"op":"replace"},{"value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType\/customRasterSourceTileRenderer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType\/customRasterSourceTileStatusChangedCallback"],"anchor":"Enumeration-Cases","title":"Enumeration Cases","generated":true}],"path":"\/topicSections","op":"replace"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatusChangedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatus","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileFunctionCallback"],"generated":true,"anchor":"Sources","title":"Sources"}],"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBMCustomRasterSourceClientType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileData\/title","op":"replace","value":"MBMCustomRasterSourceTileData"},{"op":"replace","value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileData"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileData\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileData\/navigatorTitle","value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileData"}]},{"value":"MBMCustomRasterSourceClientType","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBMCustomRasterSourceClientType"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType\/fragments"},{"value":[{"kind":"identifier","text":"MBMCustomRasterSourceClientType"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType\/navigatorTitle","op":"replace"},{"value":"MBMCustomRasterSourceClient","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient\/title"},{"value":[{"text":"MBMCustomRasterSourceClient","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient\/navigatorTitle","value":[{"text":"MBMCustomRasterSourceClient","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatus\/title","value":"MBMCustomRasterSourceTileStatus"},{"value":[{"text":"MBMCustomRasterSourceTileStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatus\/fragments"},{"value":[{"text":"MBMCustomRasterSourceTileStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatus\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatusChangedCallback\/title","op":"replace","value":"MBMCustomRasterSourceTileStatusChangedCallback"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatusChangedCallback\/fragments","value":[{"text":"MBMCustomRasterSourceTileStatusChangedCallback","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileStatusChangedCallback"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatusChangedCallback\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions\/title","value":"MBMCustomGeometrySourceOptions"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions\/fragments","value":[{"kind":"identifier","text":"MBMCustomGeometrySourceOptions"}],"op":"replace"},{"value":[{"kind":"identifier","text":"MBMCustomGeometrySourceOptions"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType~1customRasterSourceTileRenderer\/title","value":"MBMCustomRasterSourceClientTypeCustomRasterSourceTileRenderer","op":"replace"},{"value":[{"text":"MBMCustomRasterSourceClientTypeCustomRasterSourceTileRenderer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType~1customRasterSourceTileRenderer\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileFunctionCallback\/title","value":"MBMTileFunctionCallback"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileFunctionCallback\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMTileFunctionCallback"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileFunctionCallback\/navigatorTitle","op":"replace","value":[{"text":"MBMTileFunctionCallback","kind":"identifier"}]},{"value":"MBMCustomRasterSourceClientTypeCustomRasterSourceTileStatusChangedCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType~1customRasterSourceTileStatusChangedCallback\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBMCustomRasterSourceClientTypeCustomRasterSourceTileStatusChangedCallback"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType~1customRasterSourceTileStatusChangedCallback\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/title","op":"replace","value":"MBMCustomRasterSourceOptions"},{"value":[{"kind":"identifier","text":"MBMCustomRasterSourceOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/navigatorTitle","value":[{"kind":"identifier","text":"MBMCustomRasterSourceOptions"}],"op":"replace"},{"value":"MBMCustomRasterSourceTileRenderer","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileRenderer"}]},{"value":[{"text":"MBMCustomRasterSourceTileRenderer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}