{"variants":[{"paths":["\/documentation\/mapboxmaps\/offlineregionstatus\/downloadstate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/offlineregionstatus\/downloadstate"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionStatus"]]},"kind":"symbol","metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"downloadState","kind":"identifier"},{"text":": ","kind":"text"},{"text":"OfflineRegionDownloadState","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMOfflineRegionDownloadState"}],"roleHeading":"Instance Property","role":"symbol","platforms":[],"title":"downloadState","externalID":"c:objc(cs)MBMOfflineRegionStatus(py)downloadState","navigatorTitle":[{"text":"downloadState","kind":"identifier"}],"modules":[{"name":"MapboxMaps"}],"symbolKind":"property"},"sections":[],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionStatus\/downloadState","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Describes the download state."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"downloadState","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionDownloadState","text":"OfflineRegionDownloadState","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMOfflineRegionDownloadState"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Offline":{"url":"\/documentation\/mapboxmaps\/offline","title":"Offline Support","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","type":"topic","role":"collectionGroup","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMaps":{"abstract":[{"text":"Maps rendering SDK also known as GL-Native","type":"text"}],"url":"\/documentation\/mapboxmaps\/coremaps","title":"Core Maps API","role":"collectionGroup","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionStatus/downloadState":{"navigatorTitle":[{"kind":"identifier","text":"downloadState"}],"url":"\/documentation\/mapboxmaps\/offlineregionstatus\/downloadstate","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionStatus\/downloadState","abstract":[{"type":"text","text":"Describes the download state."}],"type":"topic","kind":"symbol","title":"downloadState","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"downloadState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMOfflineRegionDownloadState","text":"OfflineRegionDownloadState"}],"deprecated":true},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionStatus":{"type":"topic","title":"OfflineRegionStatus","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"OfflineRegionStatus","kind":"identifier"}],"deprecated":true,"abstract":[{"type":"text","text":"A region’s status includes its active\/inactive state as well as counts"},{"type":"text","text":" "},{"type":"text","text":"of the number of resources that have completed downloading, their total"},{"type":"text","text":" "},{"type":"text","text":"size in bytes, and the total number of resources that are required."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionStatus","url":"\/documentation\/mapboxmaps\/offlineregionstatus","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OfflineRegionStatus","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"role":"collection","kind":"symbol","url":"\/documentation\/mapboxmaps","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionDownloadState":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionDownloadState","type":"topic","deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"OfflineRegionDownloadState"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/offlineregiondownloadstate","abstract":[{"type":"text","text":"Describes the download state of a region."}],"title":"OfflineRegionDownloadState","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OfflineRegionDownloadState"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","kind":"article","title":"MapboxMaps Documentation","url":"\/documentation\/overview","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"downloadState"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"downloadState"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionDownloadState","preciseIdentifier":"c:@E@MBMOfflineRegionDownloadState","text":"MBMOfflineRegionDownloadState"},{"kind":"text","text":" "},{"kind":"identifier","text":"downloadState"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionStatus~1downloadState\/title","value":"downloadState"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionStatus~1downloadState\/fragments","value":[{"kind":"identifier","text":"downloadState"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionStatus\/title","value":"MBMOfflineRegionStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionStatus\/fragments","value":[{"kind":"identifier","text":"MBMOfflineRegionStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionStatus\/navigatorTitle","value":[{"text":"MBMOfflineRegionStatus","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionDownloadState\/title","value":"MBMOfflineRegionDownloadState"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionDownloadState\/fragments","value":[{"text":"MBMOfflineRegionDownloadState","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionDownloadState\/navigatorTitle","value":[{"text":"MBMOfflineRegionDownloadState","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}