{"kind":"symbol","seeAlsoSections":[{"anchor":"Sources","generated":true,"title":"Sources","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Source","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceInfo","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSourceData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterArraySource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/VectorSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PromoteId","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Scheme","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Encoding","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatusChangedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatus","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileFunctionCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetSize"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"CustomGeometrySource","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"type":"heading","text":"Overview","anchor":"overview","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"A CustomGeometrySource uses a coalescing model for frequent data updates targeting the same tile id."},{"type":"text","text":" "},{"type":"text","text":"This means that the in-progress request as well as the last scheduled request are guaranteed to finish."}]}],"kind":"content"}],"abstract":[{"type":"text","text":"Describes a Custom Geometry Source to be used in the style"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/mapboxmaps\/customgeometrysource"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources"]]},"sections":[],"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySource\/init(id:options:)"],"anchor":"Initializers","title":"Initializers"},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySource\/id","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySource\/options","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySource\/tileCacheBudget","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySource\/type"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"title":"Default Implementations","anchor":"Default-Implementations","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySource\/Decodable-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySource\/Encodable-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySource\/Source-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySource\/StyleEncodable-Implementations"]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySource","interfaceLanguage":"swift"},"relationshipsSections":[{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapStyleContent","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Source","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDecodable","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleEncodable","doc:\/\/com.mapbox.MapboxMaps\/s8CopyableP","doc:\/\/com.mapbox.MapboxMaps\/Se","doc:\/\/com.mapbox.MapboxMaps\/SE"]}],"metadata":{"navigatorTitle":[{"text":"CustomGeometrySource","kind":"identifier"}],"symbolKind":"struct","roleHeading":"Structure","modules":[{"name":"MapboxMaps"}],"externalID":"s:10MapboxMaps20CustomGeometrySourceV","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomGeometrySource","kind":"identifier"}],"title":"CustomGeometrySource"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ImageSource":{"type":"topic","abstract":[{"text":"An image data source.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageSource","role":"symbol","kind":"symbol","url":"\/documentation\/mapboxmaps\/imagesource","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageSource","kind":"identifier"}],"navigatorTitle":[{"text":"ImageSource","kind":"identifier"}],"title":"ImageSource"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomGeometrySource/Decodable-Implementations":{"role":"collectionGroup","abstract":[],"title":"Decodable Implementations","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySource\/Decodable-Implementations","kind":"article","type":"topic","url":"\/documentation\/mapboxmaps\/customgeometrysource\/decodable-implementations"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"role":"collection","type":"topic","title":"MapboxMaps Documentation","url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomGeometrySource/options":{"type":"topic","role":"symbol","title":"options","abstract":[{"text":"Settings for the custom geometry, including a fetchTileFunction callback","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySource\/options","kind":"symbol","url":"\/documentation\/mapboxmaps\/customgeometrysource\/options","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"options","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MBMCustomGeometrySourceOptions","kind":"typeIdentifier","text":"CustomGeometrySourceOptions"},{"kind":"text","text":"?"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileStatusChangedCallback":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatusChangedCallback","url":"\/documentation\/mapboxmaps\/customrastersourcetilestatuschangedcallback","type":"topic","title":"CustomRasterSourceTileStatusChangedCallback","abstract":[{"text":"Callback for changing a CustomRasterSource tile status.","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomRasterSourceTileStatusChangedCallback"}],"navigatorTitle":[{"text":"CustomRasterSourceTileStatusChangedCallback","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleEncodable":{"navigatorTitle":[{"text":"StyleEncodable","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"A protocol describing a style-related entity that can be encoded."}],"type":"topic","url":"\/documentation\/mapboxmaps\/styleencodable","role":"symbol","title":"StyleEncodable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleEncodable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StyleEncodable","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapStyleContent":{"abstract":[{"text":"A protocol used to create any type of  map style content, such as layers, sources, lighting and others.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapStyleContent","type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/mapstylecontent","title":"MapStyleContent","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MapStyleContent","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MapStyleContent"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceType":{"role":"symbol","navigatorTitle":[{"text":"SourceType","kind":"identifier"}],"type":"topic","title":"SourceType","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceType","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"SourceType","kind":"identifier"}],"abstract":[{"type":"text","text":"Struct of supported Source Types"},{"text":" ","type":"text"},{"text":"Docs : https:\/\/docs.mapbox.com\/mapbox-gl-js\/style-spec\/sources\/","type":"text"}],"url":"\/documentation\/mapboxmaps\/sourcetype","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Scheme":{"role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Scheme","title":"Scheme","abstract":[{"text":"Influences the y direction of the tile coordinates. The global-mercator (aka Spherical Mercator) profile is assumed.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Scheme"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/scheme","navigatorTitle":[{"text":"Scheme","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomGeometrySource/id":{"abstract":[{"type":"text","text":"Style source identifier."}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySource\/id","type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/mapboxmaps\/customgeometrysource\/id","title":"id"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PromoteId":{"role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PromoteId","title":"PromoteId","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PromoteId"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/promoteid","navigatorTitle":[{"kind":"identifier","text":"PromoteId"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomGeometrySource/tileCacheBudget":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tileCacheBudget"},{"text":": ","kind":"text"},{"text":"TileCacheBudgetSize","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps19TileCacheBudgetSizeO"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"This property defines a source-specific resource budget, either in tile units or in megabytes. Whenever the tile cache goes over the defined limit, the least recently used tile will be evicted from the in-memory cache."}],"kind":"symbol","title":"tileCacheBudget","type":"topic","url":"\/documentation\/mapboxmaps\/customgeometrysource\/tilecachebudget","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySource\/tileCacheBudget"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileRenderer":{"role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer","title":"CustomRasterSourceTileRenderer","abstract":[{"type":"text","text":"Interface for the direct rendering into the custom raster tiles."}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CustomRasterSourceTileRenderer"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/customrastersourcetilerenderer","navigatorTitle":[{"text":"CustomRasterSourceTileRenderer","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/Se":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/Se","type":"unresolvable","title":"Swift.Decodable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomGeometrySource/StyleEncodable-Implementations":{"role":"collectionGroup","abstract":[],"title":"StyleEncodable Implementations","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySource\/StyleEncodable-Implementations","kind":"article","type":"topic","url":"\/documentation\/mapboxmaps\/customgeometrysource\/styleencodable-implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomGeometrySourceOptions":{"abstract":[{"text":"Options for custom geometry source.","type":"text"}],"title":"CustomGeometrySourceOptions","url":"\/documentation\/mapboxmaps\/customgeometrysourceoptions","kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CustomGeometrySourceOptions"}],"navigatorTitle":[{"kind":"identifier","text":"CustomGeometrySourceOptions"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileFunctionCallback":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileFunctionCallback","url":"\/documentation\/mapboxmaps\/tilefunctioncallback","type":"topic","title":"TileFunctionCallback","abstract":[{"type":"text","text":"Callback to do various operations for tile."},{"text":" ","type":"text"},{"text":"For example, fetching a tile or cancelling a tile request.","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileFunctionCallback","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"TileFunctionCallback"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/VectorSource":{"role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/VectorSource","title":"VectorSource","abstract":[{"type":"text","text":"A vector tile source."}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"VectorSource","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/vectorsource","navigatorTitle":[{"text":"VectorSource","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceOptions":{"role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions","title":"CustomRasterSourceOptions","abstract":[{"type":"text","text":"Options for custom raster source."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"CustomRasterSourceOptions","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/customrastersourceoptions","navigatorTitle":[{"text":"CustomRasterSourceOptions","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GeoJSONSourceData":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSourceData","url":"\/documentation\/mapboxmaps\/geojsonsourcedata","type":"topic","title":"GeoJSONSourceData","abstract":[{"text":"Captures potential values of the ","type":"text"},{"type":"codeVoice","code":"data"},{"text":" property of a GeoJSONSource.","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GeoJSONSourceData"}],"navigatorTitle":[{"kind":"identifier","text":"GeoJSONSourceData"}]},"doc://com.mapbox.MapboxMaps/SE":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SE","type":"unresolvable","title":"Swift.Encodable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileStatus":{"role":"symbol","abstract":[{"type":"text","text":"CustomRasterSource tile status."}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"CustomRasterSourceTileStatus","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatus","navigatorTitle":[{"text":"CustomRasterSourceTileStatus","kind":"identifier"}],"type":"topic","title":"CustomRasterSourceTileStatus","url":"\/documentation\/mapboxmaps\/customrastersourcetilestatus","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceClient":{"role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient","title":"CustomRasterSourceClient","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"CustomRasterSourceClient","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/customrastersourceclient","navigatorTitle":[{"text":"CustomRasterSourceClient","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileData":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileData","url":"\/documentation\/mapboxmaps\/customrastersourcetiledata","type":"topic","title":"CustomRasterSourceTileData","abstract":[{"type":"text","text":"Data for a specific CustomRasterSource tile."}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CustomRasterSourceTileData","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceTileData"}]},"doc://com.mapbox.MapboxMaps/s8CopyableP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s8CopyableP","type":"unresolvable","title":"Swift.Copyable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterDemSource":{"role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource","title":"RasterDemSource","abstract":[{"text":"A RGB-encoded raster DEM source","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RasterDemSource"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/rasterdemsource","navigatorTitle":[{"kind":"identifier","text":"RasterDemSource"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomGeometrySource/Source-Implementations":{"type":"topic","title":"Source Implementations","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySource\/Source-Implementations","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/customgeometrysource\/source-implementations","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomGeometrySource/type":{"kind":"symbol","type":"topic","title":"type","url":"\/documentation\/mapboxmaps\/customgeometrysource\/type","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SourceType","preciseIdentifier":"s:10MapboxMaps10SourceTypeV"}],"abstract":[{"type":"text","text":"The Source type"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySource\/type"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomGeometrySource/Encodable-Implementations":{"title":"Encodable Implementations","kind":"article","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySource\/Encodable-Implementations","type":"topic","url":"\/documentation\/mapboxmaps\/customgeometrysource\/encodable-implementations","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterSource":{"abstract":[{"text":"A raster tile source.","type":"text"}],"title":"RasterSource","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RasterSource","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterSource","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"RasterSource"}],"type":"topic","url":"\/documentation\/mapboxmaps\/rastersource"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleDecodable":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StyleDecodable"}],"navigatorTitle":[{"text":"StyleDecodable","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/styledecodable","type":"topic","title":"StyleDecodable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDecodable","abstract":[{"type":"text","text":"A protocol describing a style-related entity that can be decoded."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomGeometrySource/init(id:options:)":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"id","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CustomGeometrySourceOptions","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMCustomGeometrySourceOptions"},{"kind":"text","text":")"}],"role":"symbol","abstract":[],"title":"init(id:options:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySource\/init(id:options:)","kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/customgeometrysource\/init(id:options:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Encoding":{"role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Encoding","title":"Encoding","abstract":[{"type":"text","text":"The encoding used by this source. Mapbox Terrain RGB is used by default"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"Encoding","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/encoding","navigatorTitle":[{"text":"Encoding","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","role":"collection","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","kind":"symbol","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceClientType":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType","url":"\/documentation\/mapboxmaps\/customrastersourceclienttype","type":"topic","title":"CustomRasterSourceClientType","abstract":[],"role":"symbol","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomRasterSourceClientType"}],"navigatorTitle":[{"text":"CustomRasterSourceClientType","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSource":{"abstract":[{"type":"text","text":"Describes a Custom Raster Source to be used in the style."}],"url":"\/documentation\/mapboxmaps\/customrastersource","role":"symbol","type":"topic","title":"CustomRasterSource","kind":"symbol","navigatorTitle":[{"text":"CustomRasterSource","kind":"identifier"}],"tags":[{"type":"spi","text":"SPI"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"CustomRasterSource","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSource"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomGeometrySource":{"title":"CustomGeometrySource","kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySource","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"CustomGeometrySource","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"CustomGeometrySource","kind":"identifier"}],"abstract":[{"text":"Describes a Custom Geometry Source to be used in the style","type":"text"}],"url":"\/documentation\/mapboxmaps\/customgeometrysource"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudgetSize":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetSize","url":"\/documentation\/mapboxmaps\/tilecachebudgetsize","type":"topic","title":"TileCacheBudgetSize","abstract":[{"type":"text","text":"Defines a TileCacheBudgetSize, which can be set as either a megabyte or tile count limit."},{"text":" ","type":"text"},{"type":"text","text":"Whenever tile cache goes over the defined limit"},{"type":"text","text":" "},{"text":"the least recently used tile will be evicted from the in-memory cache","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TileCacheBudgetSize","kind":"identifier"}],"navigatorTitle":[{"text":"TileCacheBudgetSize","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceInfo":{"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"SourceInfo","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Information about a Source"}],"title":"SourceInfo","url":"\/documentation\/mapboxmaps\/sourceinfo","navigatorTitle":[{"text":"SourceInfo","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceInfo"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GeoJSONSource":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSource","url":"\/documentation\/mapboxmaps\/geojsonsource","type":"topic","title":"GeoJSONSource","abstract":[{"text":"A GeoJSON data source.","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GeoJSONSource"}],"navigatorTitle":[{"kind":"identifier","text":"GeoJSONSource"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterArraySource":{"url":"\/documentation\/mapboxmaps\/rasterarraysource","abstract":[{"text":"A raster array source","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterArraySource","role":"symbol","navigatorTitle":[{"text":"RasterArraySource","kind":"identifier"}],"type":"topic","tags":[{"text":"SPI","type":"spi"}],"title":"RasterArraySource","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"RasterArraySource","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Source":{"role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Source","title":"Source","abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"Source","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/source","navigatorTitle":[{"kind":"identifier","text":"Source"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Sources":{"type":"topic","url":"\/documentation\/mapboxmaps\/sources","abstract":[],"role":"collectionGroup","kind":"article","title":"Sources","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatusChangedCallback\/title","value":"MBMCustomRasterSourceTileStatusChangedCallback"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatusChangedCallback\/fragments","value":[{"text":"MBMCustomRasterSourceTileStatusChangedCallback","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatusChangedCallback\/navigatorTitle","value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileStatusChangedCallback"}]},{"value":"MBMCustomRasterSourceTileRenderer","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer\/fragments","op":"replace","value":[{"text":"MBMCustomRasterSourceTileRenderer","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer\/navigatorTitle","op":"replace","value":[{"text":"MBMCustomRasterSourceTileRenderer","kind":"identifier"}]},{"value":"MBMCustomGeometrySourceOptions","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions\/title"},{"value":[{"text":"MBMCustomGeometrySourceOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions\/navigatorTitle","value":[{"text":"MBMCustomGeometrySourceOptions","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileFunctionCallback\/title","value":"MBMTileFunctionCallback"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileFunctionCallback\/fragments","value":[{"text":"MBMTileFunctionCallback","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileFunctionCallback\/navigatorTitle","value":[{"text":"MBMTileFunctionCallback","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/title","value":"MBMCustomRasterSourceOptions","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/fragments","op":"replace","value":[{"text":"MBMCustomRasterSourceOptions","kind":"identifier"}]},{"value":[{"text":"MBMCustomRasterSourceOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/navigatorTitle"},{"value":"MBMCustomRasterSourceTileStatus","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatus\/title"},{"value":[{"text":"MBMCustomRasterSourceTileStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatus\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatus\/navigatorTitle","value":[{"text":"MBMCustomRasterSourceTileStatus","kind":"identifier"}],"op":"replace"},{"value":"MBMCustomRasterSourceClient","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient\/title"},{"value":[{"text":"MBMCustomRasterSourceClient","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient\/navigatorTitle","op":"replace","value":[{"text":"MBMCustomRasterSourceClient","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileData\/title","value":"MBMCustomRasterSourceTileData","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileData\/fragments","value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileData"}]},{"value":[{"text":"MBMCustomRasterSourceTileData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileData\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType\/title","value":"MBMCustomRasterSourceClientType"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType\/fragments","value":[{"kind":"identifier","text":"MBMCustomRasterSourceClientType"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType\/navigatorTitle","value":[{"kind":"identifier","text":"MBMCustomRasterSourceClientType"}],"op":"replace"}]}]}