{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FeaturesetDescriptor","kind":"identifier"}]}],"kind":"declarations"}],"metadata":{"externalID":"c:objc(cs)MBMFeaturesetDescriptor","symbolKind":"class","roleHeading":"Class","role":"symbol","modules":[{"name":"MapboxMaps"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FeaturesetDescriptor","kind":"identifier"}],"title":"FeaturesetDescriptor","navigatorTitle":[{"kind":"identifier","text":"FeaturesetDescriptor"}]},"sections":[],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"]},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH"],"type":"conformsTo"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/featuresetdescriptor-swift.class"]},{"paths":["\/documentation\/mapboxmaps\/featuresetdescriptor-swift.class"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeaturesetDescriptor-swift.class\/featuresetId","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeaturesetDescriptor-swift.class\/importId","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeaturesetDescriptor-swift.class\/layerId"],"generated":true,"title":"Instance Properties"},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeaturesetDescriptor-swift.class\/isEqual(to:)"],"anchor":"Instance-Methods"}],"abstract":[{"type":"text","text":"Represents an identifier for a single exported featureset or a layer."}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeaturesetDescriptor-swift.class"},"seeAlsoSections":[{"anchor":"Query-features-on-the-map","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceQueryOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedFeature","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedRenderedFeature","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedSourceFeature","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AnnotatedFeature"],"generated":true,"title":"Query features on the map"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FeaturesetDescriptor-swift.class/layerId":{"type":"topic","title":"layerId","url":"\/documentation\/mapboxmaps\/featuresetdescriptor-swift.class\/layerid","abstract":[{"type":"text","text":"An optional unique identifier for the layer within the current style."}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeaturesetDescriptor-swift.class\/layerId","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"layerId","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"layerId","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceQueryOptions":{"title":"SourceQueryOptions","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SourceQueryOptions"}],"navigatorTitle":[{"text":"SourceQueryOptions","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceQueryOptions","type":"topic","url":"\/documentation\/mapboxmaps\/sourcequeryoptions","abstract":[{"text":"Options for querying source features.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/QueriedSourceFeature":{"type":"topic","title":"QueriedSourceFeature","url":"\/documentation\/mapboxmaps\/queriedsourcefeature","abstract":[{"text":"Represents query result that is returned in QuerySourceFeaturesCallback.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedSourceFeature","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"QueriedSourceFeature","kind":"identifier"}],"navigatorTitle":[{"text":"QueriedSourceFeature","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMFeaturesetDescriptor/initWithFeaturesetId:importId:layerId:":{"title":"initWithFeaturesetId:importId:layerId:","kind":"symbol","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithFeaturesetId:importId:layerId:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"initWithFeaturesetId:importId:layerId:"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMFeaturesetDescriptor\/initWithFeaturesetId:importId:layerId:","type":"topic","url":"\/documentation\/mapboxmaps\/mbmfeaturesetdescriptor\/initwithfeaturesetid:importid:layerid:","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FeaturesetDescriptor-swift.class":{"type":"topic","title":"FeaturesetDescriptor","url":"\/documentation\/mapboxmaps\/featuresetdescriptor-swift.class","abstract":[{"text":"Represents an identifier for a single exported featureset or a layer.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeaturesetDescriptor-swift.class","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FeaturesetDescriptor","kind":"identifier"}],"navigatorTitle":[{"text":"FeaturesetDescriptor","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FeaturesetDescriptor-swift.class/featuresetId":{"title":"featuresetId","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"featuresetId","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"featuresetId","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeaturesetDescriptor-swift.class\/featuresetId","type":"topic","url":"\/documentation\/mapboxmaps\/featuresetdescriptor-swift.class\/featuresetid","abstract":[{"text":"An optional unique identifier for the featureset within the style.","type":"text"},{"text":" ","type":"text"},{"text":"This id is used to reference a specific featureset.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FeaturesetDescriptor-swift.class/importId":{"type":"topic","title":"importId","url":"\/documentation\/mapboxmaps\/featuresetdescriptor-swift.class\/importid","abstract":[{"text":"An optional import id that is required if the featureset is defined within an imported style.","type":"text"},{"text":" ","type":"text"},{"text":"If the featureset belongs to the current style, this field should be set to a null string.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeaturesetDescriptor-swift.class\/importId","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"importId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"importId","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"abstract":[],"kind":"article","type":"topic","title":"MapboxMap","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/mapboxmap-apis","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AnnotatedFeature":{"type":"topic","title":"AnnotatedFeature","url":"\/documentation\/mapboxmaps\/annotatedfeature","abstract":[{"type":"text","text":"Represents either a GeoJSON geometry or an annotated layer feature."}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AnnotatedFeature","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"AnnotatedFeature","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AnnotatedFeature"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/QueriedFeature":{"title":"QueriedFeature","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"QueriedFeature","kind":"identifier"}],"navigatorTitle":[{"text":"QueriedFeature","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedFeature","type":"topic","url":"\/documentation\/mapboxmaps\/queriedfeature","abstract":[{"type":"text","text":"Represents queried feature that is returned through "},{"type":"codeVoice","code":"QueriedRenderedFeature"},{"text":" or ","type":"text"},{"code":"QueriedSourceFeature","type":"codeVoice"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"role":"collection","type":"topic","title":"MapboxMaps Documentation","url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FeaturesetDescriptor-swift.class/isEqual(to:)":{"type":"topic","title":"isEqual(to:)","url":"\/documentation\/mapboxmaps\/featuresetdescriptor-swift.class\/isequal(to:)","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeaturesetDescriptor-swift.class\/isEqual(to:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"kind":"text","text":"("},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMFeaturesetDescriptor","text":"FeaturesetDescriptor"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"isEqualToFeaturesetDescriptor:","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/QueriedRenderedFeature":{"title":"QueriedRenderedFeature","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"QueriedRenderedFeature"}],"navigatorTitle":[{"text":"QueriedRenderedFeature","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedRenderedFeature","type":"topic","url":"\/documentation\/mapboxmaps\/queriedrenderedfeature","abstract":[{"text":"Represents query result that is returned in QueryRenderedFeaturesCallback.","type":"text"}]},"doc://com.mapbox.MapboxMaps/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderedQueryOptions":{"title":"RenderedQueryOptions","type":"topic","url":"\/documentation\/mapboxmaps\/renderedqueryoptions","abstract":[{"text":"Options for querying rendered features.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryOptions","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"RenderedQueryOptions","kind":"identifier"}],"navigatorTitle":[{"text":"RenderedQueryOptions","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","role":"collection","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","kind":"symbol","title":"MapboxMaps"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MBMFeaturesetDescriptor"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"MBMFeaturesetDescriptor","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"MBMFeaturesetDescriptor","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeaturesetDescriptor-swift.class\/featuresetId","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeaturesetDescriptor-swift.class\/importId","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeaturesetDescriptor-swift.class\/layerId"],"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeaturesetDescriptor-swift.class\/isEqual(to:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMFeaturesetDescriptor\/initWithFeaturesetId:importId:layerId:"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true}],"op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"]}]},{"path":"\/seeAlsoSections","op":"replace","value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceQueryOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedFeature","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedRenderedFeature","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedSourceFeature","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryOptions"],"anchor":"Query-features-on-the-map","title":"Query features on the map","generated":true}]},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBMFeaturesetDescriptor"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeaturesetDescriptor-swift.class~1layerId\/title","value":"layerId","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"layerId"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeaturesetDescriptor-swift.class~1layerId\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceQueryOptions\/title","value":"MBMSourceQueryOptions","op":"replace"},{"op":"replace","value":[{"text":"MBMSourceQueryOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceQueryOptions\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceQueryOptions\/navigatorTitle","value":[{"text":"MBMSourceQueryOptions","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedSourceFeature\/title","value":"MBMQueriedSourceFeature"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedSourceFeature\/fragments","op":"replace","value":[{"text":"MBMQueriedSourceFeature","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedSourceFeature\/navigatorTitle","value":[{"kind":"identifier","text":"MBMQueriedSourceFeature"}],"op":"replace"},{"op":"replace","value":"MBMFeaturesetDescriptor","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeaturesetDescriptor-swift.class\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeaturesetDescriptor-swift.class\/fragments","value":[{"kind":"identifier","text":"MBMFeaturesetDescriptor"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeaturesetDescriptor-swift.class\/navigatorTitle","op":"replace","value":[{"text":"MBMFeaturesetDescriptor","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeaturesetDescriptor-swift.class~1featuresetId\/title","value":"featuresetId"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeaturesetDescriptor-swift.class~1featuresetId\/fragments","value":[{"text":"featuresetId","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeaturesetDescriptor-swift.class~1importId\/title","value":"importId"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeaturesetDescriptor-swift.class~1importId\/fragments","value":[{"text":"importId","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedFeature\/title","value":"MBMQueriedFeature"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedFeature\/fragments","value":[{"text":"MBMQueriedFeature","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"MBMQueriedFeature"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedFeature\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeaturesetDescriptor-swift.class~1isEqual(to:)\/title","value":"isEqualToFeaturesetDescriptor:"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeaturesetDescriptor-swift.class~1isEqual(to:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"isEqualToFeaturesetDescriptor:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedRenderedFeature\/title","op":"replace","value":"MBMQueriedRenderedFeature"},{"value":[{"kind":"identifier","text":"MBMQueriedRenderedFeature"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedRenderedFeature\/fragments","op":"replace"},{"value":[{"text":"MBMQueriedRenderedFeature","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedRenderedFeature\/navigatorTitle"},{"value":"MBMRenderedQueryOptions","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderedQueryOptions\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBMRenderedQueryOptions"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderedQueryOptions\/fragments"},{"value":[{"text":"MBMRenderedQueryOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderedQueryOptions\/navigatorTitle"}]}]}