{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/maploadingerrortype"]},{"paths":["\/documentation\/mapboxmaps\/maploadingerrortype"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorType\/glyphs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorType\/source","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorType\/sprite","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorType\/style","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorType\/tile"]},{"title":"Initializers","generated":true,"anchor":"Initializers","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorType\/init(rawValue:)"]},{"title":"Default Implementations","anchor":"Default-Implementations","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorType\/Equatable-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorType\/RawRepresentable-Implementations"],"generated":true}],"abstract":[{"type":"text","text":"The enumeration defines map loading errors."}],"metadata":{"roleHeading":"Enumeration","role":"symbol","externalID":"c:@E@MBMMapLoadingErrorType","navigatorTitle":[{"text":"MapLoadingErrorType","kind":"identifier"}],"modules":[{"name":"MapboxMaps"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MapLoadingErrorType","kind":"identifier"}],"title":"MapLoadingErrorType","symbolKind":"enum"},"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/s15BitwiseCopyableP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH","doc:\/\/com.mapbox.MapboxMaps\/SY","doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events"]]},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorType","interfaceLanguage":"swift"},"seeAlsoSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderModeType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestLoadingMethodType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestPriorityType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestDataSourceType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResponseSourceType"],"generated":true,"anchor":"Event-payload","title":"Event payload"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MapLoadingErrorType","kind":"identifier"}]}]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoadingErrorType/source":{"title":"MapLoadingErrorType.source","url":"\/documentation\/mapboxmaps\/maploadingerrortype\/source","role":"symbol","navigatorTitle":[{"text":"MBMMapLoadingErrorTypeSource","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The style resource failed to load."}],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"source","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorType\/source"},"doc://com.mapbox.MapboxMaps/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"role":"collection","type":"topic","title":"MapboxMaps Documentation","url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoadingErrorType/Equatable-Implementations":{"title":"Equatable Implementations","url":"\/documentation\/mapboxmaps\/maploadingerrortype\/equatable-implementations","role":"collectionGroup","type":"topic","abstract":[],"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorType\/Equatable-Implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoadingErrorType/glyphs":{"abstract":[{"type":"text","text":"The glyph resource failed to load."}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorType\/glyphs","url":"\/documentation\/mapboxmaps\/maploadingerrortype\/glyphs","navigatorTitle":[{"kind":"identifier","text":"MBMMapLoadingErrorTypeGlyphs"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"glyphs"}],"title":"MapLoadingErrorType.glyphs"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoadingErrorType/RawRepresentable-Implementations":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorType\/RawRepresentable-Implementations","role":"collectionGroup","kind":"article","title":"RawRepresentable Implementations","type":"topic","abstract":[],"url":"\/documentation\/mapboxmaps\/maploadingerrortype\/rawrepresentable-implementations"},"doc://com.mapbox.MapboxMaps/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ"},"doc://com.mapbox.MapboxMaps/s15BitwiseCopyableP":{"type":"unresolvable","title":"Swift.BitwiseCopyable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s15BitwiseCopyableP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoadingErrorType/sprite":{"title":"MapLoadingErrorType.sprite","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorType\/sprite","url":"\/documentation\/mapboxmaps\/maploadingerrortype\/sprite","navigatorTitle":[{"text":"MBMMapLoadingErrorTypeSprite","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sprite"}],"abstract":[{"type":"text","text":"The style resource failed to load."}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoadingErrorType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","url":"\/documentation\/mapboxmaps\/maploadingerrortype\/init(rawvalue:)","abstract":[],"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorType\/init(rawValue:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"role":"collectionGroup","type":"topic","url":"\/documentation\/mapboxmaps\/events","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","title":"Map events","kind":"article","abstract":[{"text":"The simplified diagram of the events emitted by the map is displayed below.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResponseSourceType":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ResponseSourceType","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResponseSourceType","abstract":[{"text":"The enumeration defines the source type that provides the requested resource.","type":"text"}],"url":"\/documentation\/mapboxmaps\/responsesourcetype","title":"ResponseSourceType","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ResponseSourceType"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestResourceType":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"RequestResourceType"}],"type":"topic","title":"RequestResourceType","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RequestResourceType","kind":"identifier"}],"abstract":[{"text":"The enumeration defines the type of resource requested by the ","type":"text"},{"code":"map","type":"codeVoice"},{"type":"text","text":"."}],"url":"\/documentation\/mapboxmaps\/requestresourcetype"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderModeType":{"title":"RenderModeType","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"RenderModeType","kind":"identifier"}],"navigatorTitle":[{"text":"RenderModeType","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderModeType","type":"topic","url":"\/documentation\/mapboxmaps\/rendermodetype","abstract":[{"type":"text","text":"The enumeration defines the rendering mode for the rendered frame."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestLoadingMethodType":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestLoadingMethodType","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RequestLoadingMethodType","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/requestloadingmethodtype","navigatorTitle":[{"kind":"identifier","text":"RequestLoadingMethodType"}],"kind":"symbol","type":"topic","abstract":[{"text":"The enumeration defines the method used to make a resource request.","type":"text"}],"title":"RequestLoadingMethodType"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceDataLoadedType":{"title":"SourceDataLoadedType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SourceDataLoadedType","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"SourceDataLoadedType","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/sourcedataloadedtype","abstract":[{"type":"text","text":"The enumeration defines the type of loaded source data."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedType","kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestDataSourceType":{"kind":"symbol","abstract":[{"text":"The enumeration defines the type of data source.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"RequestDataSourceType","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestDataSourceType","title":"RequestDataSourceType","url":"\/documentation\/mapboxmaps\/requestdatasourcetype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RequestDataSourceType","kind":"identifier"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestPriorityType":{"url":"\/documentation\/mapboxmaps\/requestprioritytype","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestPriorityType","abstract":[{"text":"The enumeration defines the priority of a resource request.","type":"text"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RequestPriorityType"}],"title":"RequestPriorityType","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"RequestPriorityType"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SY"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoadingErrorType":{"url":"\/documentation\/mapboxmaps\/maploadingerrortype","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MapLoadingErrorType","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorType","title":"MapLoadingErrorType","abstract":[{"type":"text","text":"The enumeration defines map loading errors."}],"kind":"symbol","navigatorTitle":[{"text":"MapLoadingErrorType","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleDataLoadedType":{"abstract":[{"type":"text","text":"The enumeration defines the type of loaded style data."}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StyleDataLoadedType","kind":"identifier"}],"title":"StyleDataLoadedType","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedType","navigatorTitle":[{"text":"StyleDataLoadedType","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/styledataloadedtype"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","role":"collection","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","kind":"symbol","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoadingErrorType/tile":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"tile","kind":"identifier"}],"title":"MapLoadingErrorType.tile","type":"topic","abstract":[{"type":"text","text":"The tile resource failed to load."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorType\/tile","kind":"symbol","url":"\/documentation\/mapboxmaps\/maploadingerrortype\/tile","navigatorTitle":[{"text":"MBMMapLoadingErrorTypeTile","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoadingErrorType/style":{"navigatorTitle":[{"kind":"identifier","text":"MBMMapLoadingErrorTypeStyle"}],"role":"symbol","abstract":[{"text":"The style resource failed to load.","type":"text"}],"kind":"symbol","title":"MapLoadingErrorType.style","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"style"}],"type":"topic","url":"\/documentation\/mapboxmaps\/maploadingerrortype\/style","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorType\/style"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"MBMMapLoadingErrorType"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MBMMapLoadingErrorType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"MBMMapLoadingErrorType","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorType\/glyphs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorType\/source","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorType\/sprite","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorType\/style","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorType\/tile"],"title":"Enumeration Cases"}]},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Event payload","generated":true,"anchor":"Event-payload","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderModeType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestLoadingMethodType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestPriorityType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestDataSourceType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResponseSourceType"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBMMapLoadingErrorType"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"value":"MBMMapLoadingErrorTypeSource","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorType~1source\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorType~1source\/fragments","value":[{"kind":"identifier","text":"MBMMapLoadingErrorTypeSource"}]},{"value":"MBMMapLoadingErrorTypeGlyphs","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorType~1glyphs\/title"},{"value":[{"text":"MBMMapLoadingErrorTypeGlyphs","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorType~1glyphs\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorType~1sprite\/title","value":"MBMMapLoadingErrorTypeSprite"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorType~1sprite\/fragments","value":[{"text":"MBMMapLoadingErrorTypeSprite","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResponseSourceType\/title","value":"MBMResponseSourceType","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResponseSourceType\/fragments","op":"replace","value":[{"text":"MBMResponseSourceType","kind":"identifier"}]},{"op":"replace","value":[{"text":"MBMResponseSourceType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResponseSourceType\/navigatorTitle"},{"op":"replace","value":"MBMRequestResourceType","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestResourceType\/title"},{"value":[{"text":"MBMRequestResourceType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestResourceType\/fragments"},{"value":[{"text":"MBMRequestResourceType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestResourceType\/navigatorTitle","op":"replace"},{"value":"MBMRenderModeType","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderModeType\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderModeType\/fragments","value":[{"kind":"identifier","text":"MBMRenderModeType"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderModeType\/navigatorTitle","value":[{"text":"MBMRenderModeType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestLoadingMethodType\/title","value":"MBMRequestLoadingMethodType"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestLoadingMethodType\/fragments","value":[{"text":"MBMRequestLoadingMethodType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestLoadingMethodType\/navigatorTitle","op":"replace","value":[{"text":"MBMRequestLoadingMethodType","kind":"identifier"}]},{"value":"MBMSourceDataLoadedType","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedType\/title"},{"value":[{"text":"MBMSourceDataLoadedType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedType\/fragments"},{"value":[{"kind":"identifier","text":"MBMSourceDataLoadedType"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedType\/navigatorTitle"},{"op":"replace","value":"MBMRequestDataSourceType","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestDataSourceType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestDataSourceType\/fragments","value":[{"text":"MBMRequestDataSourceType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestDataSourceType\/navigatorTitle","value":[{"kind":"identifier","text":"MBMRequestDataSourceType"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestPriorityType\/title","value":"MBMRequestPriorityType"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestPriorityType\/fragments","value":[{"text":"MBMRequestPriorityType","kind":"identifier"}]},{"op":"replace","value":[{"text":"MBMRequestPriorityType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestPriorityType\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorType\/title","value":"MBMMapLoadingErrorType"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorType\/fragments","value":[{"kind":"identifier","text":"MBMMapLoadingErrorType"}]},{"op":"replace","value":[{"text":"MBMMapLoadingErrorType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorType\/navigatorTitle"},{"value":"MBMStyleDataLoadedType","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedType\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedType\/fragments","value":[{"kind":"identifier","text":"MBMStyleDataLoadedType"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedType\/navigatorTitle","value":[{"kind":"identifier","text":"MBMStyleDataLoadedType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorType~1tile\/title","value":"MBMMapLoadingErrorTypeTile","op":"replace"},{"value":[{"text":"MBMMapLoadingErrorTypeTile","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorType~1tile\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorType~1style\/title","value":"MBMMapLoadingErrorTypeStyle","op":"replace"},{"value":[{"text":"MBMMapLoadingErrorTypeStyle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorType~1style\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}