{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileDataDomain\/navigationHD"},"variants":[{"paths":["\/documentation\/mapboxcommon\/tiledatadomain\/navigationhd"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/tiledatadomain\/navigationhd"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigationHD"}],"languages":["swift"]}]}],"sections":[],"kind":"symbol","metadata":{"title":"TileDataDomain.navigationHD","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"navigationHD","kind":"identifier"}],"externalID":"c:@E@MBXTileDataDomain@MBXTileDataDomainNavigationHD","symbolKind":"case","role":"symbol","navigatorTitle":[{"text":"MBXTileDataDomainNavigationHD","kind":"identifier"}],"roleHeading":"Case","modules":[{"name":"MapboxCommon"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Data for Navigation HD.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileDataDomain"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileDataDomain":{"title":"TileDataDomain","kind":"symbol","url":"\/documentation\/mapboxcommon\/tiledatadomain","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TileDataDomain"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileDataDomain","abstract":[{"type":"text","text":"Describes the tiles data domain."}],"type":"topic","navigatorTitle":[{"text":"TileDataDomain","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"kind":"article","role":"collection","url":"\/documentation\/overview","title":"MapboxMaps Documentation","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileDataDomain/navigationHD":{"url":"\/documentation\/mapboxcommon\/tiledatadomain\/navigationhd","kind":"symbol","type":"topic","title":"TileDataDomain.navigationHD","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigationHD"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileDataDomain\/navigationHD","navigatorTitle":[{"kind":"identifier","text":"MBXTileDataDomainNavigationHD"}],"abstract":[{"text":"Data for Navigation HD.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"type":"topic","abstract":[],"title":"TileStore APIs","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","url":"\/documentation\/mapboxmaps\/tilestore-apis","role":"collectionGroup","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","title":"MapboxMaps","role":"collection","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"MBXTileDataDomainNavigationHD","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"MBXTileDataDomainNavigationHD"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"MBXTileDataDomainNavigationHD","kind":"identifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileDataDomain\/title","value":"MBXTileDataDomain"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileDataDomain\/fragments","value":[{"text":"MBXTileDataDomain","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileDataDomain\/navigatorTitle","value":[{"text":"MBXTileDataDomain","kind":"identifier"}]},{"op":"replace","value":"MBXTileDataDomainNavigationHD","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileDataDomain~1navigationHD\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileDataDomain~1navigationHD\/fragments","value":[{"text":"MBXTileDataDomainNavigationHD","kind":"identifier"}]}]}]}