{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType\/diskFull"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/tileregionerrortype\/diskfull"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/tileregionerrortype\/diskfull"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"diskFull","kind":"identifier"}],"platforms":["iOS"]}]}],"sections":[],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"title":"TileRegionErrorType.diskFull","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"diskFull","kind":"identifier"}],"externalID":"c:@E@MBXTileRegionErrorType@MBXTileRegionErrorTypeDiskFull","symbolKind":"case","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBXTileRegionErrorTypeDiskFull"}],"roleHeading":"Case","modules":[{"name":"MapboxCommon"}]},"abstract":[{"type":"text","text":"There is no available space to store the resources"}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionErrorType":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"TileRegionErrorType","kind":"identifier"}],"abstract":[{"text":"Describes the reason for a tile region download request failure.","type":"text"}],"url":"\/documentation\/mapboxcommon\/tileregionerrortype","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType","title":"TileRegionErrorType","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"TileRegionErrorType","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionErrorType/diskFull":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"diskFull","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MBXTileRegionErrorTypeDiskFull"}],"type":"topic","title":"TileRegionErrorType.diskFull","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType\/diskFull","url":"\/documentation\/mapboxcommon\/tileregionerrortype\/diskfull","role":"symbol","abstract":[{"text":"There is no available space to store the resources","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"abstract":[],"url":"\/documentation\/mapboxcommon","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","type":"topic","role":"collection","title":"MapboxCommon","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"kind":"article","role":"collection","url":"\/documentation\/overview","title":"MapboxMaps Documentation","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"MBXTileRegionErrorTypeDiskFull","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MBXTileRegionErrorTypeDiskFull"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"MBXTileRegionErrorTypeDiskFull"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionErrorType\/title","value":"MBXTileRegionErrorType"},{"op":"replace","value":[{"kind":"identifier","text":"MBXTileRegionErrorType"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionErrorType\/fragments"},{"op":"replace","value":[{"text":"MBXTileRegionErrorType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionErrorType\/navigatorTitle"},{"op":"replace","value":"MBXTileRegionErrorTypeDiskFull","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionErrorType~1diskFull\/title"},{"value":[{"kind":"identifier","text":"MBXTileRegionErrorTypeDiskFull"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionErrorType~1diskFull\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}