{"abstract":[{"text":"Construct a new ","type":"text"},{"type":"codeVoice","code":"offline manager"},{"type":"text","text":"."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineManager\/init()"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineManager"]]},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"()","kind":"text"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/mapboxmaps\/offlinemanager\/init()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/offlinemanager\/init()"]}],"metadata":{"role":"symbol","symbolKind":"init","title":"init()","roleHeading":"Initializer","externalID":"c:objc(cs)MBMOfflineManager(im)init","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"modules":[{"name":"MapboxMaps"}]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineManager":{"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineManager","url":"\/documentation\/mapboxmaps\/offlinemanager","title":"OfflineManager","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OfflineManager"}],"navigatorTitle":[{"text":"OfflineManager","kind":"identifier"}],"abstract":[{"text":"An ","type":"text"},{"code":"offline manager","type":"codeVoice"},{"type":"text","text":" manages downloads and storage for style packages and also produces tileset descriptors for the "},{"code":"tile store","type":"codeVoice"},{"text":".","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","kind":"article","url":"\/documentation\/overview","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Offline":{"type":"topic","url":"\/documentation\/mapboxmaps\/offline","title":"Offline Support","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","abstract":[],"kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineManager/init()":{"type":"topic","title":"init()","abstract":[{"text":"Construct a new ","type":"text"},{"type":"codeVoice","code":"offline manager"},{"type":"text","text":"."}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/offlinemanager\/init()","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineManager\/init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"init","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"url":"\/documentation\/mapboxmaps","kind":"symbol","title":"MapboxMaps","role":"collection","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMaps":{"abstract":[{"text":"Maps rendering SDK also known as GL-Native","type":"text"}],"kind":"article","type":"topic","url":"\/documentation\/mapboxmaps\/coremaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","title":"Core Maps API","role":"collectionGroup"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"init"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineManager\/title","op":"replace","value":"MBMOfflineManager"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineManager\/fragments","value":[{"text":"MBMOfflineManager","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineManager\/navigatorTitle","value":[{"text":"MBMOfflineManager","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineManager~1init()\/title","op":"replace","value":"init"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineManager~1init()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}]}]}]}