{"sections":[],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode\/noGlyphsRasterizedLocally","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"GlyphsRasterizationMode.noGlyphsRasterizedLocally","navigatorTitle":[{"text":"MBMGlyphsRasterizationModeNoGlyphsRasterizedLocally","kind":"identifier"}],"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"noGlyphsRasterizedLocally","kind":"identifier"}],"externalID":"c:@E@MBMGlyphsRasterizationMode@MBMGlyphsRasterizationModeNoGlyphsRasterizedLocally","symbolKind":"case","modules":[{"name":"MapboxMaps"}],"role":"symbol"},"kind":"symbol","variants":[{"paths":["\/documentation\/mapboxmaps\/glyphsrasterizationmode\/noglyphsrasterizedlocally"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/glyphsrasterizationmode\/noglyphsrasterizedlocally"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-View","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode"],["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode"]]},"abstract":[{"text":"No glyphs are rasterized locally. All glyphs are loaded from the server.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noGlyphsRasterizedLocally"}]}],"kind":"declarations"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GlyphsRasterizationMode/noGlyphsRasterizedLocally":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/glyphsrasterizationmode\/noglyphsrasterizedlocally","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode\/noGlyphsRasterizedLocally","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noGlyphsRasterizedLocally"}],"title":"GlyphsRasterizationMode.noGlyphsRasterizedLocally","abstract":[{"text":"No glyphs are rasterized locally. All glyphs are loaded from the server.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"MBMGlyphsRasterizationModeNoGlyphsRasterizedLocally"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GlyphsRasterizationMode":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode","type":"topic","url":"\/documentation\/mapboxmaps\/glyphsrasterizationmode","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GlyphsRasterizationMode"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GlyphsRasterizationMode"}],"abstract":[{"type":"text","text":"Describes glyphs rasterization modes."}],"title":"GlyphsRasterizationMode","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map-View":{"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-View","url":"\/documentation\/mapboxmaps\/map-view","role":"collectionGroup","title":"MapView","kind":"article","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"type":"topic","url":"\/documentation\/overview","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"kind":"article","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","type":"topic","title":"MapboxMap","abstract":[],"url":"\/documentation\/mapboxmaps\/mapboxmap-apis"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","type":"topic","title":"MapboxMaps","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MBMGlyphsRasterizationModeNoGlyphsRasterizedLocally"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MBMGlyphsRasterizationModeNoGlyphsRasterizedLocally","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"MBMGlyphsRasterizationModeNoGlyphsRasterizedLocally"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode~1noGlyphsRasterizedLocally\/title","value":"MBMGlyphsRasterizationModeNoGlyphsRasterizedLocally","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode~1noGlyphsRasterizedLocally\/fragments","value":[{"text":"MBMGlyphsRasterizationModeNoGlyphsRasterizedLocally","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"MBMGlyphsRasterizationMode","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBMGlyphsRasterizationMode"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/fragments"},{"op":"replace","value":[{"text":"MBMGlyphsRasterizationMode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/navigatorTitle"}]}]}