{"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/tilecachebudget\/fromtilecachebudget(_:)-8jmbb"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/tilecachebudget\/fromtilecachebudget(_:)-8jmbb"]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudget"]]},"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fromTileCacheBudget"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMTileCacheBudgetInMegabytes","kind":"typeIdentifier","text":"TileCacheBudgetInMegabytes"},{"kind":"text","text":") -> "},{"text":"Self","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"fromTileCacheBudgetInMegabytes:"}],"symbolKind":"method","title":"fromTileCacheBudget(_:)","externalID":"c:objc(cs)MBMTileCacheBudget(cm)fromTileCacheBudgetInMegabytes:","roleHeading":"Type Method","role":"symbol","modules":[{"name":"MapboxMaps"}]},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fromTileCacheBudget"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"value","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMTileCacheBudgetInMegabytes","text":"TileCacheBudgetInMegabytes","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInMegabytes"},{"kind":"text","text":") -> "},{"text":"Self","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudget\/fromTileCacheBudget(_:)-8jmbb","interfaceLanguage":"swift"},"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article","role":"collection","title":"MapboxMaps Documentation","type":"topic","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudget/fromTileCacheBudget(_:)-8jmbb":{"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fromTileCacheBudget"},{"text":"(","kind":"text"},{"text":"TileCacheBudgetInMegabytes","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMTileCacheBudgetInMegabytes"},{"kind":"text","text":") -> "},{"text":"Self","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"fromTileCacheBudgetInMegabytes:","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudget\/fromTileCacheBudget(_:)-8jmbb","role":"symbol","url":"\/documentation\/mapboxmaps\/tilecachebudget\/fromtilecachebudget(_:)-8jmbb","title":"fromTileCacheBudget(_:)","kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","title":"TileStore APIs","type":"topic","role":"collectionGroup","abstract":[],"kind":"article","url":"\/documentation\/mapboxmaps\/tilestore-apis"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","title":"MapboxMaps","kind":"symbol","role":"collection","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudget":{"abstract":[],"kind":"symbol","title":"TileCacheBudget","url":"\/documentation\/mapboxmaps\/tilecachebudget","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileCacheBudget"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudget","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TileCacheBudget"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudgetInMegabytes":{"abstract":[{"type":"text","text":"Tile cache budget in megabytes."}],"kind":"symbol","title":"TileCacheBudgetInMegabytes","url":"\/documentation\/mapboxmaps\/tilecachebudgetinmegabytes","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileCacheBudgetInMegabytes"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInMegabytes","type":"topic","role":"symbol","navigatorTitle":[{"text":"TileCacheBudgetInMegabytes","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"fromTileCacheBudgetInMegabytes:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"fromTileCacheBudgetInMegabytes:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"kind":"identifier","text":"fromTileCacheBudgetInMegabytes:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMTileCacheBudgetInMegabytes","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInMegabytes","text":"MBMTileCacheBudgetInMegabytes","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"value","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"fromTileCacheBudgetInMegabytes:","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudget~1fromTileCacheBudget(_:)-8jmbb\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"fromTileCacheBudgetInMegabytes:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudget~1fromTileCacheBudget(_:)-8jmbb\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudget\/title","value":"MBMTileCacheBudget"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudget\/fragments","value":[{"text":"MBMTileCacheBudget","kind":"identifier"}]},{"op":"replace","value":[{"text":"MBMTileCacheBudget","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudget\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInMegabytes\/title","value":"MBMTileCacheBudgetInMegabytes"},{"op":"replace","value":[{"kind":"identifier","text":"MBMTileCacheBudgetInMegabytes"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInMegabytes\/fragments"},{"op":"replace","value":[{"text":"MBMTileCacheBudgetInMegabytes","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInMegabytes\/navigatorTitle"}]}]}