{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMapsInternal","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestErrorType"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"server"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/mapboxmaps\/requesterrortype\/server"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/requesterrortype\/server"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"The server error has occured."}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestErrorType\/server","interfaceLanguage":"swift"},"sections":[],"metadata":{"externalID":"c:@E@MBMRequestErrorType@MBMRequestErrorTypeServer","symbolKind":"case","navigatorTitle":[{"text":"MBMRequestErrorTypeServer","kind":"identifier"}],"title":"RequestErrorType.server","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"server","kind":"identifier"}],"modules":[{"name":"MapboxMaps"}],"role":"symbol","roleHeading":"Case"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestErrorType/server":{"abstract":[{"type":"text","text":"The server error has occured."}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestErrorType\/server","url":"\/documentation\/mapboxmaps\/requesterrortype\/server","title":"RequestErrorType.server","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"server"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"MBMRequestErrorTypeServer"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","title":"MapboxMaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"url":"\/documentation\/mapboxmaps","kind":"symbol","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"title":"MapboxMaps Documentation","type":"topic","kind":"article","role":"collection","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestErrorType":{"navigatorTitle":[{"kind":"identifier","text":"RequestErrorType"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/requesterrortype","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"RequestErrorType"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestErrorType","title":"RequestErrorType","abstract":[{"text":"The enumeration defines the error type that may occur during a resource request.","type":"text"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMapsInternal":{"type":"topic","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/coremapsinternal","abstract":[{"text":"Maps rendering SDK also known as GL-Native. These are for internal use only.","type":"text"}],"title":"CoreMaps - Internal","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMapsInternal"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"MBMRequestErrorTypeServer","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MBMRequestErrorTypeServer"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"MBMRequestErrorTypeServer"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestErrorType~1server\/title","value":"MBMRequestErrorTypeServer","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestErrorType~1server\/fragments","value":[{"text":"MBMRequestErrorTypeServer","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestErrorType\/title","value":"MBMRequestErrorType","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestErrorType\/fragments","value":[{"text":"MBMRequestErrorType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestErrorType\/navigatorTitle","value":[{"text":"MBMRequestErrorType","kind":"identifier"}],"op":"replace"}]}]}