{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"anchorCoordinate","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"abstract":[{"type":"text","text":"The actual geometric position used for positioning this annotation."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/View-Annotations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationPositionDescriptor"]]},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMViewAnnotationPositionDescriptor\/anchorCoordinate","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"modules":[{"name":"MapboxMaps"}],"roleHeading":"Instance Property","externalID":"c:objc(cs)MBMViewAnnotationPositionDescriptor(py)anchorCoordinate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"anchorCoordinate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D","kind":"typeIdentifier"}],"title":"anchorCoordinate","navigatorTitle":[{"text":"anchorCoordinate","kind":"identifier"}],"role":"symbol","symbolKind":"property"},"variants":[{"paths":["\/documentation\/mapboxmaps\/mbmviewannotationpositiondescriptor\/anchorcoordinate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/mbmviewannotationpositiondescriptor\/anchorcoordinate"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMViewAnnotationPositionDescriptor/anchorCoordinate":{"url":"\/documentation\/mapboxmaps\/mbmviewannotationpositiondescriptor\/anchorcoordinate","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMViewAnnotationPositionDescriptor\/anchorCoordinate","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"anchorCoordinate","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"}],"kind":"symbol","title":"anchorCoordinate","navigatorTitle":[{"text":"anchorCoordinate","kind":"identifier"}],"abstract":[{"text":"The actual geometric position used for positioning this annotation.","type":"text"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationPositionDescriptor":{"type":"topic","url":"\/documentation\/mapboxmaps\/viewannotationpositiondescriptor","role":"symbol","navigatorTitle":[{"text":"ViewAnnotationPositionDescriptor","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Read-only data that is needed to correctly position the single view annotation on screen.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Used inside ViewAnnotationPositionsUpdateListener callback to notify the listener about the visible view annotations’ position updates."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ViewAnnotationPositionDescriptor"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationPositionDescriptor","title":"ViewAnnotationPositionDescriptor"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/View-Annotations":{"title":"View Annotations","type":"topic","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/View-Annotations","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/view-annotations","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"anchorCoordinate","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"anchorCoordinate","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":" "},{"kind":"identifier","text":"anchorCoordinate"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMViewAnnotationPositionDescriptor~1anchorCoordinate\/title","value":"anchorCoordinate","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"anchorCoordinate"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMViewAnnotationPositionDescriptor~1anchorCoordinate\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationPositionDescriptor\/title","op":"replace","value":"MBMViewAnnotationPositionDescriptor"},{"value":[{"kind":"identifier","text":"MBMViewAnnotationPositionDescriptor"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationPositionDescriptor\/fragments"}]}]}