{"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"fboSwitchCount"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCumulativeRenderingStatistics\/fboSwitchCount"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/mbmcumulativerenderingstatistics\/fboswitchcount"]}],"abstract":[{"type":"text","text":"The number of FBO switches."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CumulativeRenderingStatistics"]]},"metadata":{"modules":[{"name":"MapboxMaps"}],"roleHeading":"Instance Property","externalID":"c:objc(cs)MBMCumulativeRenderingStatistics(py)fboSwitchCount","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"fboSwitchCount"}],"role":"symbol","fragments":[{"kind":"identifier","text":"fboSwitchCount"}],"title":"fboSwitchCount"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMCumulativeRenderingStatistics/fboSwitchCount":{"abstract":[{"type":"text","text":"The number of FBO switches."}],"url":"\/documentation\/mapboxmaps\/mbmcumulativerenderingstatistics\/fboswitchcount","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCumulativeRenderingStatistics\/fboSwitchCount","kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"fboSwitchCount"}],"type":"topic","title":"fboSwitchCount"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article","title":"MapboxMaps Documentation","abstract":[],"url":"\/documentation\/overview","role":"collection","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CumulativeRenderingStatistics":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CumulativeRenderingStatistics","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CumulativeRenderingStatistics","kind":"identifier"}],"title":"CumulativeRenderingStatistics","abstract":[],"url":"\/documentation\/mapboxmaps\/cumulativerenderingstatistics","navigatorTitle":[{"text":"CumulativeRenderingStatistics","kind":"identifier"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","title":"MapboxMaps","type":"topic","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Performance":{"abstract":[],"kind":"article","title":"Performance and investigations","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","role":"collectionGroup","type":"topic","url":"\/documentation\/mapboxmaps\/performance"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"MBMCumulativeRenderingStatistics","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CumulativeRenderingStatistics\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CumulativeRenderingStatistics\/fragments","op":"replace","value":[{"text":"MBMCumulativeRenderingStatistics","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CumulativeRenderingStatistics\/navigatorTitle","value":[{"kind":"identifier","text":"MBMCumulativeRenderingStatistics"}]}]}]}