{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiredResourceCount"},{"text":": ","kind":"text"},{"text":"UInt64","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/mapboxmaps\/stylepack\/requiredresourcecount"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/stylepack\/requiredresourcecount"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePack\/requiredResourceCount"},"sections":[],"abstract":[{"type":"text","text":"The number of resources that are known to be required for this style package."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"requiredResourceCount","externalID":"c:objc(cs)MBMStylePack(py)requiredResourceCount","roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"MapboxMaps"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requiredResourceCount"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt64","preciseIdentifier":"s:s6UInt64V"}],"navigatorTitle":[{"text":"requiredResourceCount","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePack"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","url":"\/documentation\/overview","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePack/requiredResourceCount":{"kind":"symbol","title":"requiredResourceCount","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePack\/requiredResourceCount","abstract":[{"type":"text","text":"The number of resources that are known to be required for this style package."}],"type":"topic","url":"\/documentation\/mapboxmaps\/stylepack\/requiredresourcecount","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requiredResourceCount","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt64","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V"}],"navigatorTitle":[{"text":"requiredResourceCount","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePack":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"StylePack"}],"url":"\/documentation\/mapboxmaps\/stylepack","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePack","title":"StylePack","type":"topic","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"style pack"},{"text":" represents a stored style package.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"StylePack","kind":"identifier"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"title":"TileStore APIs","abstract":[],"kind":"article","url":"\/documentation\/mapboxmaps\/tilestore-apis","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"title":"MapboxMaps","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"requiredResourceCount","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"kind":"identifier","text":"requiredResourceCount"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"uint64_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@uint64_t"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requiredResourceCount"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"requiredResourceCount","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePack~1requiredResourceCount\/title"},{"value":[{"text":"requiredResourceCount","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePack~1requiredResourceCount\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePack\/title","value":"MBMStylePack"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePack\/fragments","value":[{"text":"MBMStylePack","kind":"identifier"}],"op":"replace"},{"value":[{"text":"MBMStylePack","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePack\/navigatorTitle"}]}]}