{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers"]]},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Struct of supported Layer rendering types"}],"topicSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType\/init(rawValue:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType\/init(stringLiteral:)"],"generated":true,"title":"Initializers","anchor":"Initializers"},{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType\/layerType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType\/rawValue"],"generated":true},{"title":"Type Properties","generated":true,"anchor":"Type-Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType\/background","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType\/circle","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType\/clip","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType\/custom","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType\/fill","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType\/fillExtrusion","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType\/heatmap","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType\/hillshade","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType\/line","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType\/locationIndicator","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType\/model","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType\/raster","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType\/rasterParticle","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType\/sky","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType\/slot","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType\/symbol"]},{"title":"Default Implementations","generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType\/Equatable-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType\/ExpressibleByExtendedGraphemeClusterLiteral-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType\/ExpressibleByUnicodeScalarLiteral-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType\/RawRepresentable-Implementations"]}],"relationshipsSections":[{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/Se","doc:\/\/com.mapbox.MapboxMaps\/SE","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/s43ExpressibleByExtendedGraphemeClusterLiteralP","doc:\/\/com.mapbox.MapboxMaps\/s26ExpressibleByStringLiteralP","doc:\/\/com.mapbox.MapboxMaps\/s33ExpressibleByUnicodeScalarLiteralP","doc:\/\/com.mapbox.MapboxMaps\/SH","doc:\/\/com.mapbox.MapboxMaps\/SY","doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"],"type":"conformsTo"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType","interfaceLanguage":"swift"},"seeAlsoSections":[{"anchor":"Layers","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerInfo","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/BackgroundLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CircleLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillExtrusionLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationIndicatorLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterParticleLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SkyLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderConfiguration","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerHost","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ElevationData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Slot","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SlotLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerAtPosition","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClipLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClipLayerTypes"],"generated":true,"title":"Layers"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"LayerType","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/layertype"]}],"metadata":{"modules":[{"name":"MapboxMaps"}],"externalID":"s:10MapboxMaps9LayerTypeV","title":"LayerType","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LayerType"}],"role":"symbol","symbolKind":"struct","roleHeading":"Structure","navigatorTitle":[{"text":"LayerType","kind":"identifier"}]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ClipLayer":{"title":"ClipLayer","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"ClipLayer","kind":"identifier"}],"navigatorTitle":[{"text":"ClipLayer","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/cliplayer","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClipLayer","tags":[{"type":"spi","text":"SPI"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Layer that removes 3D content from map."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerType/clip":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType\/clip","url":"\/documentation\/mapboxmaps\/layertype\/clip","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"clip","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10MapboxMaps9LayerTypeV","text":"LayerType","kind":"typeIdentifier"}],"abstract":[{"text":"A clip layer.","type":"text"}],"role":"symbol","title":"clip","type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerType/init(rawValue:)":{"type":"topic","url":"\/documentation\/mapboxmaps\/layertype\/init(rawvalue:)","kind":"symbol","abstract":[],"title":"init(rawValue:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType\/init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerType/layerType":{"abstract":[{"type":"text","text":"The associated Swift struct type"}],"kind":"symbol","type":"topic","title":"layerType","url":"\/documentation\/mapboxmaps\/layertype\/layertype","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType\/layerType","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"layerType","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"Layer","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps5LayerP"},{"kind":"text","text":".Type)?"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerType/hillshade":{"url":"\/documentation\/mapboxmaps\/layertype\/hillshade","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hillshade"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"LayerType","preciseIdentifier":"s:10MapboxMaps9LayerTypeV"}],"abstract":[{"type":"text","text":"Client-side hillshading visualization based on DEM data."},{"text":" ","type":"text"},{"text":"Currently, the implementation only supports Mapbox Terrain RGB and Mapzen Terrarium tiles.","type":"text"}],"title":"hillshade","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType\/hillshade","role":"symbol","type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FillLayer":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillLayer","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"FillLayer","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/filllayer","abstract":[{"type":"text","text":"A filled polygon with an optional stroked border."}],"navigatorTitle":[{"kind":"identifier","text":"FillLayer"}],"kind":"symbol","title":"FillLayer","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SkyLayer":{"url":"\/documentation\/mapboxmaps\/skylayer","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SkyLayer","navigatorTitle":[{"text":"SkyLayer","kind":"identifier"}],"kind":"symbol","title":"SkyLayer","role":"symbol","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SkyLayer","kind":"identifier"}],"abstract":[{"type":"text","text":"A spherical dome around the map that is always rendered behind all other layers."},{"type":"text","text":" "},{"text":"Warning: As of v10.6.0, ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Atmosphere","isActive":true},{"type":"text","text":" is the preferred method for atmospheric styling. Sky layer is not supported by the globe projection, and will be phased out in future major release."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerType/background":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType\/background","kind":"symbol","type":"topic","title":"background","url":"\/documentation\/mapboxmaps\/layertype\/background","abstract":[{"text":"The background color or pattern of the map.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"background"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LayerType","preciseIdentifier":"s:10MapboxMaps9LayerTypeV"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerType/rasterParticle":{"role":"symbol","abstract":[{"text":"Layer repsenting particles on the map.","type":"text"}],"url":"\/documentation\/mapboxmaps\/layertype\/rasterparticle","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"rasterParticle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"LayerType","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps9LayerTypeV"}],"type":"topic","title":"rasterParticle","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType\/rasterParticle"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerType/Equatable-Implementations":{"title":"Equatable Implementations","url":"\/documentation\/mapboxmaps\/layertype\/equatable-implementations","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType\/Equatable-Implementations","abstract":[],"kind":"article","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerType/symbol":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType\/symbol","title":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/layertype\/symbol","kind":"symbol","abstract":[{"text":"An icon or a text label.","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"symbol"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps9LayerTypeV","text":"LayerType"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerType/ExpressibleByExtendedGraphemeClusterLiteral-Implementations":{"kind":"article","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/layertype\/expressiblebyextendedgraphemeclusterliteral-implementations","abstract":[],"title":"ExpressibleByExtendedGraphemeClusterLiteral Implementations","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType\/ExpressibleByExtendedGraphemeClusterLiteral-Implementations","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerType/raster":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType\/raster","title":"raster","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"raster"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps9LayerTypeV","text":"LayerType","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Raster map textures such as satellite imagery."}],"url":"\/documentation\/mapboxmaps\/layertype\/raster","kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelLayer":{"type":"topic","navigatorTitle":[{"text":"ModelLayer","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ModelLayer"}],"title":"ModelLayer","kind":"symbol","url":"\/documentation\/mapboxmaps\/modellayer","abstract":[{"text":"A layer to render 3D Models.","type":"text"}],"role":"symbol","tags":[{"type":"spi","text":"SPI"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerType/slot":{"title":"slot","abstract":[{"text":"Layer representing a place for other layers.","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"slot","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10MapboxMaps9LayerTypeV","text":"LayerType","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType\/slot","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/layertype\/slot"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ClipLayerTypes":{"url":"\/documentation\/mapboxmaps\/cliplayertypes","kind":"symbol","abstract":[{"type":"text","text":"Layer types that will also be removed if fallen below this clip layer."}],"navigatorTitle":[{"text":"ClipLayerTypes","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClipLayerTypes","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClipLayerTypes"}],"title":"ClipLayerTypes","role":"symbol"},"doc://com.mapbox.MapboxMaps/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerType":{"abstract":[{"text":"Struct of supported Layer rendering types","type":"text"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"LayerType","kind":"identifier"}],"kind":"symbol","title":"LayerType","url":"\/documentation\/mapboxmaps\/layertype","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType","navigatorTitle":[{"kind":"identifier","text":"LayerType"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerType/line":{"role":"symbol","title":"line","type":"topic","url":"\/documentation\/mapboxmaps\/layertype\/line","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"line","kind":"identifier"},{"kind":"text","text":": "},{"text":"LayerType","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps9LayerTypeV"}],"abstract":[{"text":"A stroked line.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType\/line","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerType/sky":{"type":"topic","role":"symbol","title":"sky","url":"\/documentation\/mapboxmaps\/layertype\/sky","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"sky"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps9LayerTypeV","text":"LayerType"}],"abstract":[{"text":"Layer representing the sky","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType\/sky"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/BackgroundLayer":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BackgroundLayer","kind":"identifier"}],"kind":"symbol","title":"BackgroundLayer","abstract":[{"type":"text","text":"The background color or pattern of the map."}],"url":"\/documentation\/mapboxmaps\/backgroundlayer","type":"topic","navigatorTitle":[{"text":"BackgroundLayer","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/BackgroundLayer","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerRenderParameters":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters","url":"\/documentation\/mapboxmaps\/customlayerrenderparameters","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CustomLayerRenderParameters","kind":"identifier"}],"abstract":[{"text":"Parameters that define the current camera position for a ","type":"text"},{"type":"codeVoice","code":"CustomLayerHost::render()"},{"type":"text","text":" function."}],"title":"CustomLayerRenderParameters","kind":"symbol","type":"topic","navigatorTitle":[{"text":"CustomLayerRenderParameters","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Atmosphere":{"url":"\/documentation\/mapboxmaps\/atmosphere","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Atmosphere","kind":"identifier"}],"type":"topic","abstract":[{"text":"A style’s fog property is a global effect that improves depth perception by fading out distant objects.","type":"text"}],"title":"Atmosphere","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Atmosphere","kind":"symbol","navigatorTitle":[{"text":"Atmosphere","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerRenderConfiguration":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderConfiguration","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CustomLayerRenderConfiguration"}],"title":"CustomLayerRenderConfiguration","abstract":[{"text":"Note! This is an experimental feature. It can be changed or removed in future versions.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CustomLayerRenderConfiguration"}],"url":"\/documentation\/mapboxmaps\/customlayerrenderconfiguration"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeatmapLayer":{"abstract":[{"text":"A heatmap.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"HeatmapLayer"}],"title":"HeatmapLayer","kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/heatmaplayer","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"HeatmapLayer","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layer":{"title":"Layer","type":"topic","url":"\/documentation\/mapboxmaps\/layer","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"Layer","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"Layer","kind":"identifier"}],"abstract":[],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FillExtrusionLayer":{"role":"symbol","title":"FillExtrusionLayer","kind":"symbol","url":"\/documentation\/mapboxmaps\/fillextrusionlayer","abstract":[{"text":"An extruded (3D) polygon.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FillExtrusionLayer"}],"navigatorTitle":[{"kind":"identifier","text":"FillExtrusionLayer"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillExtrusionLayer"},"doc://com.mapbox.MapboxMaps/s43ExpressibleByExtendedGraphemeClusterLiteralP":{"type":"unresolvable","title":"Swift.ExpressibleByExtendedGraphemeClusterLiteral","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s43ExpressibleByExtendedGraphemeClusterLiteralP"},"doc://com.mapbox.MapboxMaps/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SY"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LocationIndicatorLayer":{"url":"\/documentation\/mapboxmaps\/locationindicatorlayer","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"LocationIndicatorLayer","kind":"identifier"}],"abstract":[{"text":"Location Indicator layer.","type":"text"}],"navigatorTitle":[{"text":"LocationIndicatorLayer","kind":"identifier"}],"title":"LocationIndicatorLayer","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationIndicatorLayer","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerType/circle":{"kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/layertype\/circle","abstract":[{"text":"A filled circle.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType\/circle","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"circle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"LayerType","preciseIdentifier":"s:10MapboxMaps9LayerTypeV"}],"title":"circle"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerInfo":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/layerinfo","role":"symbol","abstract":[{"type":"text","text":"Information about a layer"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerInfo","type":"topic","title":"LayerInfo","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LayerInfo","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"LayerInfo"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterLayer":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"RasterLayer"}],"url":"\/documentation\/mapboxmaps\/rasterlayer","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterLayer","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RasterLayer"}],"title":"RasterLayer","abstract":[{"type":"text","text":"Raster map textures such as satellite imagery."}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","title":"MapboxMaps Documentation","kind":"article","url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","abstract":[]},"doc://com.mapbox.MapboxMaps/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SE"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerType/heatmap":{"kind":"symbol","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"heatmap","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LayerType","preciseIdentifier":"s:10MapboxMaps9LayerTypeV"}],"type":"topic","title":"heatmap","abstract":[{"text":"A heatmap.","type":"text"}],"url":"\/documentation\/mapboxmaps\/layertype\/heatmap","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType\/heatmap"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LineLayer":{"role":"symbol","title":"LineLayer","kind":"symbol","url":"\/documentation\/mapboxmaps\/linelayer","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineLayer","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LineLayer"}],"type":"topic","navigatorTitle":[{"text":"LineLayer","kind":"identifier"}],"abstract":[{"text":"A stroked line.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer":{"abstract":[{"text":"Client-side hillshading visualization based on DEM data. Currently, the implementation only supports Mapbox Terrain RGB and Mapzen Terrarium tiles.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer","navigatorTitle":[{"kind":"identifier","text":"HillshadeLayer"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"HillshadeLayer"}],"role":"symbol","title":"HillshadeLayer","url":"\/documentation\/mapboxmaps\/hillshadelayer"},"doc://com.mapbox.MapboxMaps/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerType/rawValue":{"title":"rawValue","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType\/rawValue","role":"symbol","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"rawValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The raw value of the layer type."}],"url":"\/documentation\/mapboxmaps\/layertype\/rawvalue","kind":"symbol"},"doc://com.mapbox.MapboxMaps/s26ExpressibleByStringLiteralP":{"type":"unresolvable","title":"Swift.ExpressibleByStringLiteral","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s26ExpressibleByStringLiteralP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayer":{"url":"\/documentation\/mapboxmaps\/customlayer","kind":"symbol","abstract":[{"text":"Layer with custom rendering implementation","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"CustomLayer"}],"tags":[{"text":"SPI","type":"spi"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayer","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"CustomLayer","kind":"identifier"}],"title":"CustomLayer","role":"symbol"},"doc://com.mapbox.MapboxMaps/s33ExpressibleByUnicodeScalarLiteralP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s33ExpressibleByUnicodeScalarLiteralP","title":"Swift.ExpressibleByUnicodeScalarLiteral","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerAtPosition":{"url":"\/documentation\/mapboxmaps\/layeratposition","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"LayerAtPosition"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerAtPosition","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LayerAtPosition"}],"title":"LayerAtPosition","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ElevationData":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ElevationData","type":"topic","role":"symbol","navigatorTitle":[{"text":"ElevationData","kind":"identifier"}],"title":"ElevationData","abstract":[{"text":"Interface that provides access to elevation data.","type":"text"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ElevationData"}],"url":"\/documentation\/mapboxmaps\/elevationdata"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","title":"MapboxMaps","kind":"symbol","url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerType/init(stringLiteral:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType\/init(stringLiteral:)","type":"topic","title":"init(stringLiteral:)","abstract":[],"role":"symbol","url":"\/documentation\/mapboxmaps\/layertype\/init(stringliteral:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"stringLiteral","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/Se":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/Se","title":"Swift.Decodable","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerType/ExpressibleByUnicodeScalarLiteral-Implementations":{"type":"topic","title":"ExpressibleByUnicodeScalarLiteral Implementations","url":"\/documentation\/mapboxmaps\/layertype\/expressiblebyunicodescalarliteral-implementations","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType\/ExpressibleByUnicodeScalarLiteral-Implementations","abstract":[],"role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SlotLayer":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SlotLayer","type":"topic","role":"symbol","navigatorTitle":[{"text":"SlotLayer","kind":"identifier"}],"title":"SlotLayer","abstract":[{"type":"text","text":"Marks the position of a slot."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SlotLayer"}],"url":"\/documentation\/mapboxmaps\/slotlayer"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SymbolLayer":{"navigatorTitle":[{"kind":"identifier","text":"SymbolLayer"}],"url":"\/documentation\/mapboxmaps\/symbollayer","title":"SymbolLayer","role":"symbol","type":"topic","kind":"symbol","abstract":[{"text":"An icon or a text label.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolLayer","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SymbolLayer","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerType/model":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType\/model","type":"topic","title":"model","abstract":[{"text":"Layer used for a 3D model","type":"text"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/layertype\/model","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"model"},{"text":": ","kind":"text"},{"text":"LayerType","preciseIdentifier":"s:10MapboxMaps9LayerTypeV","kind":"typeIdentifier"}],"tags":[{"type":"spi","text":"SPI"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CircleLayer":{"role":"symbol","navigatorTitle":[{"text":"CircleLayer","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CircleLayer","kind":"symbol","title":"CircleLayer","url":"\/documentation\/mapboxmaps\/circlelayer","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CircleLayer"}],"abstract":[{"text":"A filled circle.","type":"text"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerType/RawRepresentable-Implementations":{"role":"collectionGroup","type":"topic","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType\/RawRepresentable-Implementations","abstract":[],"title":"RawRepresentable Implementations","url":"\/documentation\/mapboxmaps\/layertype\/rawrepresentable-implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layers":{"type":"topic","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers","url":"\/documentation\/mapboxmaps\/layers","abstract":[],"title":"Layers","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerType/locationIndicator":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Layer representing the location indicator"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType\/locationIndicator","url":"\/documentation\/mapboxmaps\/layertype\/locationindicator","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"locationIndicator","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"LayerType","preciseIdentifier":"s:10MapboxMaps9LayerTypeV"}],"type":"topic","title":"locationIndicator"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterParticleLayer":{"tags":[{"type":"spi","text":"SPI"}],"url":"\/documentation\/mapboxmaps\/rasterparticlelayer","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"RasterParticleLayer"}],"title":"RasterParticleLayer","abstract":[{"type":"text","text":"Particle animation driven by textures such as wind maps."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"RasterParticleLayer"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterParticleLayer","role":"symbol"},"doc://com.mapbox.MapboxMaps/SH":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerType/fill":{"url":"\/documentation\/mapboxmaps\/layertype\/fill","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType\/fill","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fill"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps9LayerTypeV","text":"LayerType","kind":"typeIdentifier"}],"kind":"symbol","title":"fill","role":"symbol","abstract":[{"type":"text","text":"A filled polygon with an optional stroked border."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerType/fillExtrusion":{"url":"\/documentation\/mapboxmaps\/layertype\/fillextrusion","type":"topic","abstract":[{"text":"An extruded (3D) polygon.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType\/fillExtrusion","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fillExtrusion"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps9LayerTypeV","kind":"typeIdentifier","text":"LayerType"}],"title":"fillExtrusion","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Slot":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/slot","role":"symbol","abstract":[{"text":"A pre-specified location in the style where layer will be added to","type":"text"},{"text":" ","type":"text"},{"text":"(such as on top of existing land layers, but below all labels).","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Slot","title":"Slot","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"Slot","kind":"identifier"}],"navigatorTitle":[{"text":"Slot","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerHost":{"url":"\/documentation\/mapboxmaps\/customlayerhost","kind":"symbol","abstract":[{"text":"Interface for hosting a custom map style layer.","type":"text"}],"navigatorTitle":[{"text":"CustomLayerHost","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerHost","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"CustomLayerHost","kind":"identifier"}],"title":"CustomLayerHost","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerType/custom":{"role":"symbol","abstract":[{"type":"text","text":"Layer with custom rendering implementation ("},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerHost"},{"type":"text","text":")"}],"url":"\/documentation\/mapboxmaps\/layertype\/custom","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"custom","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps9LayerTypeV","text":"LayerType"}],"type":"topic","title":"custom","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType\/custom"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/title","value":"MBMCustomLayerRenderParameters","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/fragments","value":[{"text":"MBMCustomLayerRenderParameters","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MBMCustomLayerRenderParameters"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderConfiguration\/title","value":"MBMCustomLayerRenderConfiguration"},{"value":[{"text":"MBMCustomLayerRenderConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderConfiguration\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"MBMCustomLayerRenderConfiguration"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ElevationData\/title","value":"MBMElevationData"},{"value":[{"text":"MBMElevationData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ElevationData\/fragments"},{"value":[{"text":"MBMElevationData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ElevationData\/navigatorTitle"},{"value":"MBMCustomLayerHost","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost\/fragments","value":[{"text":"MBMCustomLayerHost","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMCustomLayerHost"}]}]}]}