{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/performancestatisticscallback"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/performancestatisticscallback"]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatisticsCallback","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","seeAlsoSections":[{"generated":true,"anchor":"Performance-recording","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatistics","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CumulativeRenderingStatistics","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/DurationStatistics","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GroupPerformanceStatistics","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerFrameRenderingStatistics","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatisticsOptions"],"title":"Performance recording"}],"abstract":[{"text":"Use this callback to observe the collected statistics. The callback is invoked at regular intervals determined by","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"the sampling duration specified in the "},{"type":"codeVoice","code":"PerformanceStatisticsOptions"},{"text":". The callback is invoked from the main thread.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"PerformanceStatisticsCallback","kind":"identifier"},{"text":" = (","kind":"text"},{"text":"PerformanceStatistics","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatistics","preciseIdentifier":"c:objc(cs)MBMPerformanceStatistics"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"}]}]}],"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"PerformanceStatisticsCallback","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PerformanceStatisticsCallback"}],"roleHeading":"Type Alias","title":"PerformanceStatisticsCallback","externalID":"c:MBMPerformanceStatisticsCallback.h@T@MBMPerformanceStatisticsCallback","symbolKind":"typealias","modules":[{"name":"MapboxMaps"}]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PerformanceStatisticsCallback":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PerformanceStatisticsCallback"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatisticsCallback","kind":"symbol","title":"PerformanceStatisticsCallback","url":"\/documentation\/mapboxmaps\/performancestatisticscallback","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PerformanceStatisticsCallback"}],"abstract":[{"text":"Use this callback to observe the collected statistics. The callback is invoked at regular intervals determined by","type":"text"},{"type":"text","text":" "},{"text":"the sampling duration specified in the ","type":"text"},{"type":"codeVoice","code":"PerformanceStatisticsOptions"},{"text":". The callback is invoked from the main thread.","type":"text"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PerFrameRenderingStatistics":{"title":"PerFrameRenderingStatistics","navigatorTitle":[{"kind":"identifier","text":"PerFrameRenderingStatistics"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerFrameRenderingStatistics","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PerFrameRenderingStatistics"}],"url":"\/documentation\/mapboxmaps\/perframerenderingstatistics","type":"topic","kind":"symbol","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/DurationStatistics":{"abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DurationStatistics"}],"navigatorTitle":[{"kind":"identifier","text":"DurationStatistics"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/DurationStatistics","url":"\/documentation\/mapboxmaps\/durationstatistics","title":"DurationStatistics","kind":"symbol","type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PerformanceStatistics":{"role":"symbol","navigatorTitle":[{"text":"PerformanceStatistics","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatistics","kind":"symbol","title":"PerformanceStatistics","url":"\/documentation\/mapboxmaps\/performancestatistics","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PerformanceStatistics","kind":"identifier"}],"abstract":[{"text":"The performance statistics collected at the end of the sampling duration.","type":"text"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GroupPerformanceStatistics":{"role":"symbol","navigatorTitle":[{"text":"GroupPerformanceStatistics","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GroupPerformanceStatistics","kind":"symbol","title":"GroupPerformanceStatistics","url":"\/documentation\/mapboxmaps\/groupperformancestatistics","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GroupPerformanceStatistics","kind":"identifier"}],"abstract":[],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","title":"MapboxMaps Documentation","kind":"article","url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PerformanceStatisticsOptions":{"url":"\/documentation\/mapboxmaps\/performancestatisticsoptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatisticsOptions","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PerformanceStatisticsOptions"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"PerformanceStatisticsOptions","kind":"identifier"}],"abstract":[{"text":"Options for the following statistics collection behaviors:","type":"text"}],"kind":"symbol","title":"PerformanceStatisticsOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CumulativeRenderingStatistics":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CumulativeRenderingStatistics"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CumulativeRenderingStatistics","kind":"symbol","title":"CumulativeRenderingStatistics","url":"\/documentation\/mapboxmaps\/cumulativerenderingstatistics","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CumulativeRenderingStatistics","kind":"identifier"}],"abstract":[],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Performance":{"role":"collectionGroup","kind":"article","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","title":"Performance and investigations","type":"topic","url":"\/documentation\/mapboxmaps\/performance"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","title":"MapboxMaps","kind":"symbol","url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Alias","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"MBMPerformanceStatisticsCallback"},{"path":"\/metadata\/symbolKind","value":"typealias","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"MBMPerformanceStatisticsCallback","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"MBMPerformanceStatisticsCallback","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":[{"generated":true,"anchor":"Performance-recording","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatistics","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CumulativeRenderingStatistics","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/DurationStatistics","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GroupPerformanceStatistics","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerFrameRenderingStatistics","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatisticsOptions"],"title":"Performance recording"}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"typedef"},{"text":" ","kind":"text"},{"text":"void (^)(MBMPerformanceStatistics *)","kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$objc(cs)MBMPerformanceStatistics)"},{"kind":"text","text":" "},{"text":"MBMPerformanceStatisticsCallback","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatisticsCallback\/title","value":"MBMPerformanceStatisticsCallback"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatisticsCallback\/fragments","value":[{"text":"MBMPerformanceStatisticsCallback","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatisticsCallback\/navigatorTitle","value":[{"text":"MBMPerformanceStatisticsCallback","kind":"identifier"}],"op":"replace"},{"value":"MBMPerFrameRenderingStatistics","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerFrameRenderingStatistics\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerFrameRenderingStatistics\/fragments","value":[{"text":"MBMPerFrameRenderingStatistics","kind":"identifier"}]},{"value":[{"text":"MBMPerFrameRenderingStatistics","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerFrameRenderingStatistics\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1DurationStatistics\/title","value":"MBMDurationStatistics","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1DurationStatistics\/fragments","value":[{"kind":"identifier","text":"MBMDurationStatistics"}]},{"value":[{"kind":"identifier","text":"MBMDurationStatistics"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1DurationStatistics\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatistics\/title","value":"MBMPerformanceStatistics"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatistics\/fragments","value":[{"text":"MBMPerformanceStatistics","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MBMPerformanceStatistics"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatistics\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GroupPerformanceStatistics\/title","value":"MBMGroupPerformanceStatistics","op":"replace"},{"value":[{"kind":"identifier","text":"MBMGroupPerformanceStatistics"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GroupPerformanceStatistics\/fragments"},{"value":[{"kind":"identifier","text":"MBMGroupPerformanceStatistics"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GroupPerformanceStatistics\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatisticsOptions\/title","value":"MBMPerformanceStatisticsOptions"},{"value":[{"kind":"identifier","text":"MBMPerformanceStatisticsOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatisticsOptions\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatisticsOptions\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMPerformanceStatisticsOptions"}]},{"value":"MBMCumulativeRenderingStatistics","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CumulativeRenderingStatistics\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBMCumulativeRenderingStatistics"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CumulativeRenderingStatistics\/fragments"},{"value":[{"text":"MBMCumulativeRenderingStatistics","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CumulativeRenderingStatistics\/navigatorTitle","op":"replace"}]}]}