{"seeAlsoSections":[{"title":"Dependencies","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps"],"anchor":"Dependencies","generated":true}],"metadata":{"modules":[{"name":"MapboxMaps"}],"title":"Turf","roleHeading":"API Collection","role":"collectionGroup"},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TurfAPI","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"article","topicSections":[{"title":"GeoJSON","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Feature","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Geometry","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/Turf"],"anchor":"GeoJSON"}],"abstract":[{"type":"text","text":"Describes "},{"code":"turf-swift","type":"codeVoice"},{"type":"text","text":" dependency objects"}],"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMaps":{"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","role":"collectionGroup","type":"topic","abstract":[{"type":"text","text":"Maps rendering SDK also known as GL-Native"}],"url":"\/documentation\/mapboxmaps\/coremaps","title":"Core Maps API"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/GeometryType":{"url":"\/documentation\/mapboxcommon\/geometrytype","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GeometryType","kind":"identifier"}],"abstract":[],"title":"GeometryType","navigatorTitle":[{"kind":"identifier","text":"GeometryType"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType","role":"symbol","type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Turf":{"role":"collection","type":"topic","url":"\/documentation\/turf","title":"Turf","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Turf","kind":"symbol","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Geometry":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Geometry","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/geometry","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Geometry"}],"abstract":[{"text":"An object representing points, curves, and surfaces in coordinate space. Use an instance of this enumeration whenever a value could be any kind of Geometry object.","type":"text"}],"title":"Geometry","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Geometry","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","title":"MapboxMaps","kind":"symbol","url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","title":"MapboxMaps Documentation","kind":"article","url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Feature":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Feature","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"An object representing a spatially bounded geometry.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Feature","title":"Feature","role":"symbol","url":"\/documentation\/mapboxmaps\/feature","navigatorTitle":[{"text":"Feature","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType\/title","value":"MBXGeometryType"},{"value":[{"kind":"identifier","text":""}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType\/navigatorTitle","value":[{"kind":"identifier","text":"MBXGeometryType"}]}]}]}