{"abstract":[{"text":"Creates a view annotation.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ViewAnnotation","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"level":2,"anchor":"overview","type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"text":"Use view annotations if you need to display interactive UIView bound to","type":"text"},{"type":"text","text":" "},{"type":"text","text":"a geographical coordinate or map feature."}]},{"inlineContent":[{"text":"The view annotations are great for displaying unique interactive features. However, they may be suboptimal for large amounts of data and don’t support clustering. For those cases use ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PointAnnotation"},{"type":"text","text":" or Runtime Styling API, for example, "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolLayer"},{"type":"text","text":" with "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSource"},{"text":".","type":"text"}],"type":"paragraph"},{"type":"aside","style":"note","content":[{"inlineContent":[{"text":"View Annotations appear above all content of MapView (e.g. layers, annotations, puck). If you need to display annotation between layers or below puck, use ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PointAnnotation","type":"reference","isActive":true},{"text":".","type":"text"}],"type":"paragraph"}],"name":"Note"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To display a view annotation configure a UIView, create "},{"type":"codeVoice","code":"ViewAnnotation"},{"type":"text","text":", and add it to the view annotation manager:"}]},{"syntax":"swift","type":"codeListing","code":["let view = CustomView()","view.icon = UIImage(named: \"traffic-icon\")","let annotation = ViewAnnotation(","  coordinate: CLLocationCoordinate(latitude: 10, longitude: 10),","  view: view)","mapView.viewAnnotations.add(annotation)"]},{"type":"paragraph","inlineContent":[{"text":"The annotation can be displayed on a layer feature referenced by it’s ","type":"text"},{"type":"codeVoice","code":"layerId"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"featureId"},{"type":"text","text":":"}]},{"type":"codeListing","syntax":"swift","code":["annotation.annotatedFeature = .layerFeature(layerId: \"route-line\", featureId: \"sf-la\")"]},{"inlineContent":[{"type":"text","text":"The view annotation automatically inserts and removes it’s view into the view hierarchy and updates its "},{"code":"isHidden","type":"codeVoice"},{"type":"text","text":" property."}],"type":"paragraph"},{"name":"Important","content":[{"type":"paragraph","inlineContent":[{"text":"Don’t set ","type":"text"},{"code":"UIView.isHidden","type":"codeVoice"},{"type":"text","text":" property to hide the annotation. Instead, use "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/visible"},{"type":"text","text":" property."}]}],"style":"important","type":"aside"},{"inlineContent":[{"type":"text","text":"When view content or layout is updated, use "},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/setNeedsUpdateSize()","isActive":true},{"text":" to update the the annotation size. It’s safe to use it multiple times, only one update will be performed.","type":"text"}],"type":"paragraph"},{"type":"codeListing","syntax":"swift","code":["view.hintText = \"Less Traffic\"","annotation.setNeedsUpdateSize() \/\/ Updates the annotation size."]},{"type":"aside","name":"Note","style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ViewAnnotation"},{"type":"text","text":" uses "},{"type":"codeVoice","code":"UIView.systemLayoutSizeFitting(_:)"},{"text":" to measure the view size. Make sure that your view returns the correct size (e.g. implemented using AutoLayout, or returns correct size from ","type":"text"},{"code":"UIView.sizeThatFits(_:)","type":"codeVoice"},{"type":"text","text":" when layout is manual)."}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"To remove annotation when it’s no longer needed, use "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/remove()","isActive":true,"type":"reference"},{"text":" method.","type":"text"}]}],"kind":"content"}],"topicSections":[{"title":"Initializers","anchor":"Initializers","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/init(annotatedFeature:view:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/init(coordinate:view:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/init(layerId:featureId:view:)"]},{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/allowOverlap","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/allowOverlapWithPuck","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/allowZElevate","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/anchorConfig","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/anchorCoordinate","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/annotatedFeature","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/ignoreCameraPadding","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/onAnchorChanged","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/onAnchorCoordinateChanged","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/onFrameChanged","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/onVisibilityChanged","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/selected","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/variableAnchors","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/view","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/visible"],"title":"Instance Properties"},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/remove()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/setNeedsUpdateSize()"]}],"seeAlsoSections":[{"title":"View Annotations","anchor":"View-Annotations","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManager","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManagerError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchorConfig","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationPositionDescriptor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationUpdateObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchor"]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/mapboxmaps\/viewannotation"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/View-Annotations"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"metadata":{"navigatorTitle":[{"text":"ViewAnnotation","kind":"identifier"}],"externalID":"s:10MapboxMaps14ViewAnnotationC","symbolKind":"class","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ViewAnnotation","kind":"identifier"}],"title":"ViewAnnotation","roleHeading":"Class","modules":[{"name":"MapboxMaps"}]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotation/onVisibilityChanged":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"onVisibilityChanged","kind":"identifier"},{"text":": ((","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")?"}],"type":"topic","title":"onVisibilityChanged","url":"\/documentation\/mapboxmaps\/viewannotation\/onvisibilitychanged","abstract":[{"text":"Called when visibility of annotation is changed.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/onVisibilityChanged"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","title":"MapboxMaps","kind":"symbol","url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationManagerError":{"title":"ViewAnnotationManagerError","kind":"symbol","url":"\/documentation\/mapboxmaps\/viewannotationmanagererror","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ViewAnnotationManagerError","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"ViewAnnotationManagerError","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManagerError","role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotation/onAnchorCoordinateChanged":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onAnchorCoordinateChanged"},{"text":": ((","kind":"text"},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/onAnchorCoordinateChanged","abstract":[{"text":"Called when ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/anchorCoordinate"},{"type":"text","text":" is changed."}],"title":"onAnchorCoordinateChanged","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/viewannotation\/onanchorcoordinatechanged"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotation/setNeedsUpdateSize()":{"title":"setNeedsUpdateSize()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setNeedsUpdateSize","kind":"identifier"},{"kind":"text","text":"()"}],"url":"\/documentation\/mapboxmaps\/viewannotation\/setneedsupdatesize()","abstract":[{"type":"text","text":"Invalidates the current size of view annotation."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/setNeedsUpdateSize()","type":"topic","role":"symbol","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotation":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ViewAnnotation"}],"abstract":[{"type":"text","text":"Creates a view annotation."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation","navigatorTitle":[{"kind":"identifier","text":"ViewAnnotation"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/viewannotation","type":"topic","title":"ViewAnnotation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SymbolLayer":{"navigatorTitle":[{"kind":"identifier","text":"SymbolLayer"}],"url":"\/documentation\/mapboxmaps\/symbollayer","title":"SymbolLayer","role":"symbol","type":"topic","kind":"symbol","abstract":[{"text":"An icon or a text label.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolLayer","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SymbolLayer","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotation/variableAnchors":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/variableAnchors","kind":"symbol","type":"topic","title":"variableAnchors","url":"\/documentation\/mapboxmaps\/viewannotation\/variableanchors","abstract":[{"text":"A list of anchor configurations available.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"variableAnchors","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"ViewAnnotationAnchorConfig","preciseIdentifier":"c:objc(cs)MBMViewAnnotationAnchorConfig"},{"text":"]","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotation/anchorConfig":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"anchorConfig","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ViewAnnotationAnchorConfig","preciseIdentifier":"c:objc(cs)MBMViewAnnotationAnchorConfig"},{"text":"?","kind":"text"}],"type":"topic","abstract":[{"type":"text","text":"Currently selected anchor configuration."}],"url":"\/documentation\/mapboxmaps\/viewannotation\/anchorconfig","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/anchorConfig","kind":"symbol","title":"anchorConfig"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotation/init(coordinate:view:)":{"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/viewannotation\/init(coordinate:view:)","title":"init(coordinate:view:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/init(coordinate:view:)","abstract":[{"text":"Creates an annotation at specified coordinate.","type":"text"}],"fragments":[{"kind":"keyword","text":"convenience"},{"text":" ","kind":"text"},{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"coordinate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"view"},{"text":": ","kind":"text"},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotation/annotatedFeature":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"annotatedFeature"},{"text":": ","kind":"text"},{"text":"AnnotatedFeature","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps16AnnotatedFeatureV"}],"title":"annotatedFeature","url":"\/documentation\/mapboxmaps\/viewannotation\/annotatedfeature","abstract":[{"text":"Associates the view annotation with the feature geometry.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/annotatedFeature"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotation/init(layerId:featureId:view:)":{"url":"\/documentation\/mapboxmaps\/viewannotation\/init(layerid:featureid:view:)","abstract":[{"text":"Creates a view annotation on feature rendered on a layer.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/init(layerId:featureId:view:)","fragments":[{"text":"convenience","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"layerId"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"featureId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"view","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","title":"init(layerId:featureId:view:)","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotation/onFrameChanged":{"type":"topic","abstract":[{"text":"Called when view frame is changed.","type":"text"}],"title":"onFrameChanged","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/onFrameChanged","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onFrameChanged"},{"text":": ((","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")?"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/viewannotation\/onframechanged"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotation/allowOverlapWithPuck":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/allowOverlapWithPuck","role":"symbol","abstract":[{"type":"text","text":"When "},{"type":"codeVoice","code":"false"},{"type":"text","text":", the annotation won’t be shown on top of Puck."}],"type":"topic","kind":"symbol","title":"allowOverlapWithPuck","url":"\/documentation\/mapboxmaps\/viewannotation\/allowoverlapwithpuck","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"allowOverlapWithPuck","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotation/ignoreCameraPadding":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ignoreCameraPadding"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"ignoreCameraPadding","url":"\/documentation\/mapboxmaps\/viewannotation\/ignorecamerapadding","abstract":[{"text":"When ","type":"text"},{"code":"false","type":"codeVoice"},{"type":"text","text":", the annotation will be displayed even if it go beyond camera padding."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/ignoreCameraPadding"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationPositionDescriptor":{"url":"\/documentation\/mapboxmaps\/viewannotationpositiondescriptor","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ViewAnnotationPositionDescriptor"}],"abstract":[{"text":"Read-only data that is needed to correctly position the single view annotation on screen.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Used inside ViewAnnotationPositionsUpdateListener callback to notify the listener about the visible view annotations’ position updates."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationPositionDescriptor","title":"ViewAnnotationPositionDescriptor","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ViewAnnotationPositionDescriptor"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotation/selected":{"abstract":[{"type":"text","text":"Specifies if this view annotation is selected meaning it should be placed on top of others."}],"url":"\/documentation\/mapboxmaps\/viewannotation\/selected","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selected"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/selected","kind":"symbol","title":"selected","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotation/remove()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"remove","kind":"identifier"},{"kind":"text","text":"()"}],"kind":"symbol","type":"topic","title":"remove()","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/remove()","abstract":[{"type":"text","text":"Removes view annotation."}],"url":"\/documentation\/mapboxmaps\/viewannotation\/remove()"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotation/allowOverlap":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/allowOverlap","role":"symbol","url":"\/documentation\/mapboxmaps\/viewannotation\/allowoverlap","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"allowOverlap","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"type":"topic","abstract":[{"type":"text","text":"If true, the annotation will be visible even if it collides with other previously drawn annotations."}],"title":"allowOverlap"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationAnchorConfig":{"type":"topic","url":"\/documentation\/mapboxmaps\/viewannotationanchorconfig","navigatorTitle":[{"kind":"identifier","text":"ViewAnnotationAnchorConfig"}],"kind":"symbol","abstract":[{"text":"Represents a specific setting for a view annotation anchor.","type":"text"}],"title":"ViewAnnotationAnchorConfig","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchorConfig","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ViewAnnotationAnchorConfig","kind":"identifier"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PointAnnotation":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PointAnnotation"}],"kind":"symbol","type":"topic","title":"PointAnnotation","url":"\/documentation\/mapboxmaps\/pointannotation","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PointAnnotation"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PointAnnotation"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","title":"MapboxMaps Documentation","kind":"article","url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotation/onAnchorChanged":{"type":"topic","url":"\/documentation\/mapboxmaps\/viewannotation\/onanchorchanged","kind":"symbol","abstract":[{"type":"text","text":"Called when "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/anchorConfig","type":"reference","isActive":true},{"type":"text","text":" is changed."}],"title":"onAnchorChanged","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/onAnchorChanged","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"onAnchorChanged","kind":"identifier"},{"text":": ((","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMViewAnnotationAnchorConfig","kind":"typeIdentifier","text":"ViewAnnotationAnchorConfig"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?","kind":"text"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotation/init(annotatedFeature:view:)":{"kind":"symbol","abstract":[{"text":"Creates an annotation.","type":"text"}],"title":"init(annotatedFeature:view:)","url":"\/documentation\/mapboxmaps\/viewannotation\/init(annotatedfeature:view:)","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/init(annotatedFeature:view:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"annotatedFeature","kind":"externalParam"},{"kind":"text","text":": "},{"text":"AnnotatedFeature","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps16AnnotatedFeatureV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"view"},{"text":": ","kind":"text"},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/View-Annotations":{"title":"View Annotations","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/View-Annotations","role":"collectionGroup","kind":"article","url":"\/documentation\/mapboxmaps\/view-annotations","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotation/view":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"view"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"kind":"symbol","type":"topic","title":"view","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/view","abstract":[{"type":"text","text":"Annotation view."}],"url":"\/documentation\/mapboxmaps\/viewannotation\/view"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationAnchor":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/viewannotationanchor","navigatorTitle":[{"kind":"identifier","text":"ViewAnnotationAnchor"}],"role":"symbol","title":"ViewAnnotationAnchor","abstract":[{"type":"text","text":"Enum describing how to place view annotation relatively to geometry."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ViewAnnotationAnchor","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchor","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotation/anchorCoordinate":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/anchorCoordinate","kind":"symbol","url":"\/documentation\/mapboxmaps\/viewannotation\/anchorcoordinate","type":"topic","role":"symbol","title":"anchorCoordinate","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"anchorCoordinate","kind":"identifier"},{"kind":"text","text":": "},{"text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"The actual geographical coordinate used for positioning this annotation."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotation/visible":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"visible","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"visible","url":"\/documentation\/mapboxmaps\/viewannotation\/visible","abstract":[{"type":"text","text":"Specifies if this view annotation is visible or not."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/visible"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GeoJSONSource":{"url":"\/documentation\/mapboxmaps\/geojsonsource","title":"GeoJSONSource","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"GeoJSONSource","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"A GeoJSON data source.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSource","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GeoJSONSource"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationManager":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ViewAnnotationManager","kind":"identifier"}],"abstract":[{"text":"Manager API to control View Annotations.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManager","navigatorTitle":[{"kind":"identifier","text":"ViewAnnotationManager"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/viewannotationmanager","type":"topic","title":"ViewAnnotationManager"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationUpdateObserver":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationUpdateObserver","abstract":[{"text":"An interface you use to detect when the map view lays out or updates visibility of annotation views.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ViewAnnotationUpdateObserver","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"ViewAnnotationUpdateObserver","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/viewannotationupdateobserver","role":"symbol","title":"ViewAnnotationUpdateObserver"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationOptions":{"navigatorTitle":[{"text":"ViewAnnotationOptions","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationOptions","type":"topic","title":"ViewAnnotationOptions","url":"\/documentation\/mapboxmaps\/viewannotationoptions","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Stores layout and visibility settings for a view annotation."}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ViewAnnotationOptions"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotation/allowZElevate":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/allowZElevate","title":"allowZElevate","url":"\/documentation\/mapboxmaps\/viewannotation\/allowzelevate","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"allowZElevate","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?"}],"type":"topic","abstract":[{"type":"text","text":"When true, position annotation on buildings’ (both fill extrusions and models) rooftops."}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationPositionDescriptor\/title","op":"replace","value":"MBMViewAnnotationPositionDescriptor"},{"value":[{"kind":"identifier","text":"MBMViewAnnotationPositionDescriptor"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationPositionDescriptor\/fragments","op":"replace"},{"value":[{"text":"MBMViewAnnotationPositionDescriptor","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationPositionDescriptor\/navigatorTitle","op":"replace"},{"value":"MBMViewAnnotationAnchorConfig","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchorConfig\/title"},{"op":"replace","value":[{"text":"MBMViewAnnotationAnchorConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchorConfig\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchorConfig\/navigatorTitle","value":[{"text":"MBMViewAnnotationAnchorConfig","kind":"identifier"}]},{"value":"MBMViewAnnotationAnchor","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchor\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchor\/fragments","value":[{"text":"MBMViewAnnotationAnchor","kind":"identifier"}]},{"op":"replace","value":[{"text":"MBMViewAnnotationAnchor","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchor\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}