{"metadata":{"navigatorTitle":[{"text":"getMetadata","kind":"identifier"}],"title":"getMetadata()","modules":[{"name":"MapboxMaps"}],"roleHeading":"Instance Method","externalID":"c:objc(cs)MBMOfflineRegion(im)getMetadata","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getMetadata","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"}],"platforms":[],"role":"symbol"},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegion\/getMetadata()","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getMetadata"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"}]}]},{"content":[{"level":2,"type":"heading","anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The metadata associated with the region."}]}],"kind":"content"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/offlineregion\/getmetadata()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/offlineregion\/getmetadata()"]}],"abstract":[{"type":"text","text":"Arbitrary binary region metadata."}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegion"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMaps":{"type":"topic","title":"Core Maps API","abstract":[{"type":"text","text":"Maps rendering SDK also known as GL-Native"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","kind":"article","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/coremaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Offline":{"role":"collectionGroup","title":"Offline Support","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","url":"\/documentation\/mapboxmaps\/offline","abstract":[],"kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"type":"topic","url":"\/documentation\/mapboxmaps","role":"collection","kind":"symbol","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","url":"\/documentation\/overview","role":"collection","abstract":[],"kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegion/getMetadata()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getMetadata","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/offlineregion\/getmetadata()","deprecated":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegion\/getMetadata()","title":"getMetadata()","navigatorTitle":[{"text":"getMetadata","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"text":"Arbitrary binary region metadata.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegion":{"title":"OfflineRegion","navigatorTitle":[{"text":"OfflineRegion","kind":"identifier"}],"kind":"symbol","role":"symbol","deprecated":true,"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OfflineRegion","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/offlineregion","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegion","abstract":[{"text":"An offline region represents an identifiable geographic region with optional metadata.","type":"text"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"getMetadata","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getMetadata"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"NSData","preciseIdentifier":"c:objc(cs)NSData","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"getMetadata","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"content","content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"The metadata associated with the region.","type":"text"}]}]},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"getMetadata","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegion~1getMetadata()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"getMetadata","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegion~1getMetadata()\/fragments"},{"op":"replace","value":"MBMOfflineRegion","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegion\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBMOfflineRegion"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegion\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MBMOfflineRegion"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegion\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}