{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onCameraChanged","kind":"identifier"},{"kind":"text","text":"("},{"text":"action","kind":"externalParam"},{"kind":"text","text":": "},{"text":"@escaping","kind":"keyword"},{"text":" (","kind":"text"},{"text":"CameraChanged","preciseIdentifier":"c:objc(cs)MBMCameraChanged","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraChanged"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":") -> ","kind":"text"},{"text":"Map","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps3MapV","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"text":"Discussion","type":"heading","anchor":"discussion","level":2},{"type":"aside","name":"Important","style":"important","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This callback is called on every rendering frame. Don’t use it to modify "},{"code":"@State","type":"codeVoice"},{"type":"text","text":" variables, it will lead to excessive "},{"code":"body","type":"codeVoice"},{"text":" execution and higher CPU consumption.","type":"text"}]}]},{"inlineContent":[{"text":"For example:","type":"text"}],"type":"paragraph"},{"syntax":"swift","code":["struct BadExample: View {","    @State var zoom: Double = 0","    var body: some View {","        Map {","            if zoom > 5 {","                CircleAnnotation(centerCoordinate: coordinate)","            }","        }","        .onCameraChanged {","            \/\/ DON'T DO THIS","            zoom = $0.cameraState.zoom","        }","    }","}"],"type":"codeListing"},{"inlineContent":[{"text":"Instead update the state only when the actual value is changed:","type":"text"}],"type":"paragraph"},{"type":"codeListing","code":["struct GoodExample: View {","    private class Model: ObservableObject {","        @Published var showAnnotation = false","        func setZoom(_ zoom: Double) {","            var showAnnotation = zoom < 5","            if showAnnotation != self.showAnnotation {","                \/\/ OK, the showAnnotation updates only when actual value changed.","                \/\/ The `body` will be executed once per update.","                self.showAnnotation = showAnnotation","            }","        }","    }","","    @StateObject var model = Model()","    var body: some View {","        Map {","            if model.showAnnotation {","                CircleAnnotation(centerCoordinate: coordinate)","            }","        }","        .onCameraChanged {","            model.setZoom($0.cameraState.zoom)","        }","    }","}"],"syntax":"swift"}],"kind":"content"}],"abstract":[{"text":"Adds an action to perform when the camera is changed.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SwiftUI","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map"]]},"metadata":{"modules":[{"name":"MapboxMaps"}],"symbolKind":"method","extendedModule":"MapboxMaps","externalID":"s:10MapboxMaps3MapV15onCameraChanged6actionACySo09MBMCameraF0Cc_tF","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onCameraChanged"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"action"},{"text":": (","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMCameraChanged","text":"CameraChanged","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":") -> ","kind":"text"},{"text":"Map","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps3MapV"}],"title":"onCameraChanged(action:)","role":"symbol","roleHeading":"Instance Method"},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onCameraChanged(action:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"variants":[{"paths":["\/documentation\/mapboxmaps\/map\/oncamerachanged(action:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SwiftUI":{"title":"SwiftUI","url":"\/documentation\/mapboxmaps\/swiftui","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SwiftUI","role":"collectionGroup","kind":"article","type":"topic","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"type":"topic","title":"MapboxMaps Documentation","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/onCameraChanged(action:)":{"abstract":[{"text":"Adds an action to perform when the camera is changed.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onCameraChanged","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMCameraChanged","text":"CameraChanged"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":") -> "},{"text":"Map","preciseIdentifier":"s:10MapboxMaps3MapV","kind":"typeIdentifier"}],"title":"onCameraChanged(action:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onCameraChanged(action:)","url":"\/documentation\/mapboxmaps\/map\/oncamerachanged(action:)","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","url":"\/documentation\/mapboxmaps","type":"topic","kind":"symbol","title":"MapboxMaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map","kind":"symbol","navigatorTitle":[{"text":"Map","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Map"}],"type":"topic","role":"symbol","abstract":[{"text":"A SwiftUI view that displays a Mapbox Map.","type":"text"}],"url":"\/documentation\/mapboxmaps\/map","title":"Map"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraChanged":{"title":"CameraChanged","abstract":[{"text":"This event is emitted whenever the visible viewport changes its size","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"due to the invocation of the "},{"type":"codeVoice","code":"setSize"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"setBounds"},{"text":" methods or when","type":"text"},{"type":"text","text":" "},{"text":"the camera is modified by calling camera methods. The event is emitted","type":"text"},{"type":"text","text":" "},{"text":"synchronously so that an updated camera state can be read immediately.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraChanged","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CameraChanged","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"CameraChanged","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/camerachanged","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChanged\/title","value":"MBMCameraChanged"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChanged\/fragments","value":[{"text":"MBMCameraChanged","kind":"identifier"}]},{"value":[{"text":"MBMCameraChanged","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChanged\/navigatorTitle"}]}]}