{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"writeLog","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"level"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBXLoggingLevel","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LoggingLevel","text":"LoggingLevel"},{"text":", ","kind":"text"},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"level","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Severity of the message."}]}]},{"name":"message","content":[{"inlineContent":[{"text":"Log message","type":"text"}],"type":"paragraph"}]}]}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"writeLog"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBXLoggingLevel","text":"LoggingLevel"},{"text":", ","kind":"text"},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"title":"writeLog(for:message:)","navigatorTitle":[{"text":"writeLogForLevel:message:","kind":"identifier"}],"externalID":"c:objc(pl)MBXLogWriterBackend(im)writeLogForLevel:message:","modules":[{"name":"MapboxCommon"}],"symbolKind":"method","roleHeading":"Instance Method","role":"symbol","required":true},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/logwriterbackend\/writelog(for:message:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/logwriterbackend\/writelog(for:message:)"]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogWriterBackend\/writeLog(for:message:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogWriterBackend"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Writes a log message with a given level.","type":"text"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","url":"\/documentation\/overview","role":"collection","kind":"article","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LogWriterBackend/writeLog(for:message:)":{"kind":"symbol","required":true,"navigatorTitle":[{"text":"writeLogForLevel:message:","kind":"identifier"}],"title":"writeLog(for:message:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogWriterBackend\/writeLog(for:message:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"writeLog","kind":"identifier"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@MBXLoggingLevel","text":"LoggingLevel","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"type":"topic","role":"symbol","url":"\/documentation\/mapboxcommon\/logwriterbackend\/writelog(for:message:)","abstract":[{"type":"text","text":"Writes a log message with a given level."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Performance":{"abstract":[],"role":"collectionGroup","kind":"article","title":"Performance and investigations","url":"\/documentation\/mapboxmaps\/performance","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LoggingLevel":{"title":"LoggingLevel","abstract":[{"type":"text","text":"State level of a log message."}],"url":"\/documentation\/mapboxcommon\/logginglevel","role":"symbol","navigatorTitle":[{"text":"LoggingLevel","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LoggingLevel","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoggingLevel"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LogWriterBackend":{"kind":"symbol","title":"LogWriterBackend","abstract":[{"text":"Interface for implementing log writing backends, e.g. for using platform specific log backends or logging to a notification service.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogWriterBackend","type":"topic","url":"\/documentation\/mapboxcommon\/logwriterbackend","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"LogWriterBackend","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"LogWriterBackend"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"role":"collection","title":"MapboxMaps","type":"topic","url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"writeLogForLevel:message:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"writeLogForLevel:message:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"writeLogForLevel:"},{"kind":"text","text":"("},{"text":"MBXLoggingLevel","preciseIdentifier":"c:@E@MBXLoggingLevel","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LoggingLevel","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"level"},{"text":" ","kind":"text"},{"text":"message:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"message"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Severity of the message."}]}],"name":"level"},{"name":"message","content":[{"inlineContent":[{"text":"Log message","type":"text"}],"type":"paragraph"}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"writeLogForLevel:message:","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogWriterBackend~1writeLog(for:message:)\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogWriterBackend~1writeLog(for:message:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"writeLogForLevel:message:","kind":"identifier"}]},{"op":"replace","value":"MBXLoggingLevel","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LoggingLevel\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LoggingLevel\/fragments","value":[{"kind":"identifier","text":"MBXLoggingLevel"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LoggingLevel\/navigatorTitle","value":[{"text":"MBXLoggingLevel","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogWriterBackend\/title","value":"MBXLogWriterBackend"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogWriterBackend\/fragments","value":[{"text":"MBXLogWriterBackend","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogWriterBackend\/navigatorTitle","value":[{"text":"MBXLogWriterBackend","kind":"identifier"}],"op":"replace"}]}]}