{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"View annotation height in "},{"code":"platform pixels","type":"codeVoice"},{"type":"text","text":" for drawing the annotation."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"height","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"sections":[],"metadata":{"roleHeading":"Instance Property","role":"symbol","modules":[{"name":"MapboxMaps"}],"navigatorTitle":[{"text":"height","kind":"identifier"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"height"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"title":"height","externalID":"c:objc(cs)MBMViewAnnotationPositionDescriptor(py)height"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/View-Annotations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationPositionDescriptor"]]},"variants":[{"paths":["\/documentation\/mapboxmaps\/viewannotationpositiondescriptor\/height"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/viewannotationpositiondescriptor\/height"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationPositionDescriptor\/height","interfaceLanguage":"swift"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","title":"MapboxMaps","kind":"symbol","url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationPositionDescriptor":{"url":"\/documentation\/mapboxmaps\/viewannotationpositiondescriptor","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ViewAnnotationPositionDescriptor"}],"abstract":[{"text":"Read-only data that is needed to correctly position the single view annotation on screen.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Used inside ViewAnnotationPositionsUpdateListener callback to notify the listener about the visible view annotations’ position updates."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationPositionDescriptor","title":"ViewAnnotationPositionDescriptor","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ViewAnnotationPositionDescriptor"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/View-Annotations":{"title":"View Annotations","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/View-Annotations","role":"collectionGroup","kind":"article","url":"\/documentation\/mapboxmaps\/view-annotations","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationPositionDescriptor/height":{"role":"symbol","title":"height","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationPositionDescriptor\/height","navigatorTitle":[{"text":"height","kind":"identifier"}],"type":"topic","abstract":[{"text":"View annotation height in ","type":"text"},{"code":"platform pixels","type":"codeVoice"},{"type":"text","text":" for drawing the annotation."}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/viewannotationpositiondescriptor\/height","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"height","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","title":"MapboxMaps Documentation","kind":"article","url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"height"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"kind":"identifier","text":"height"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"height","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationPositionDescriptor\/title","op":"replace","value":"MBMViewAnnotationPositionDescriptor"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationPositionDescriptor\/fragments","value":[{"kind":"identifier","text":"MBMViewAnnotationPositionDescriptor"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationPositionDescriptor\/navigatorTitle","op":"replace","value":[{"text":"MBMViewAnnotationPositionDescriptor","kind":"identifier"}]},{"value":"height","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationPositionDescriptor~1height\/title","op":"replace"},{"op":"replace","value":[{"text":"height","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationPositionDescriptor~1height\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}