{"metadata":{"externalID":"c:objc(cs)MBXHttpRequestFlags(cpy)PauseInBackground","modules":[{"name":"MapboxCommon"}],"symbolKind":"property","title":"pauseInBackground","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pauseInBackground"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt32","preciseIdentifier":"s:s6UInt32V"}],"navigatorTitle":[{"text":"PauseInBackground","kind":"identifier"}],"roleHeading":"Type Property","role":"symbol"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestFlags\/pauseInBackground","interfaceLanguage":"swift"},"abstract":[{"text":"Supported for Android only.","type":"text"},{"text":" ","type":"text"},{"text":"If set and application also has “com.mapbox.common.http.pause_requests_on_demand” setting in manifest","type":"text"},{"text":" ","type":"text"},{"text":"the request will be performed in the foreground only. In case application is in the background request will","type":"text"},{"text":" ","type":"text"},{"text":"be queued.","type":"text"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pauseInBackground","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s6UInt32V","text":"UInt32","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/mapboxcommon\/httprequestflags\/pauseinbackground"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxcommon\/httprequestflags\/pauseinbackground"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestFlags"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestFlags":{"title":"HttpRequestFlags","url":"\/documentation\/mapboxcommon\/httprequestflags","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HttpRequestFlags"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestFlags","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HttpRequestFlags"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","type":"topic","abstract":[],"role":"collection","kind":"symbol","url":"\/documentation\/mapboxcommon","title":"MapboxCommon"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestFlags/pauseInBackground":{"title":"pauseInBackground","kind":"symbol","url":"\/documentation\/mapboxcommon\/httprequestflags\/pauseinbackground","navigatorTitle":[{"kind":"identifier","text":"PauseInBackground"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pauseInBackground"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt32V","text":"UInt32"}],"type":"topic","abstract":[{"type":"text","text":"Supported for Android only."},{"type":"text","text":" "},{"type":"text","text":"If set and application also has “com.mapbox.common.http.pause_requests_on_demand” setting in manifest"},{"type":"text","text":" "},{"type":"text","text":"the request will be performed in the foreground only. In case application is in the background request will"},{"type":"text","text":" "},{"type":"text","text":"be queued."}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestFlags\/pauseInBackground"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"type":"topic","url":"\/documentation\/overview","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"PauseInBackground","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"PauseInBackground","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@uint32_t","kind":"typeIdentifier","text":"uint32_t"},{"kind":"text","text":" "},{"kind":"identifier","text":"PauseInBackground"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MBXHttpRequestFlags","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestFlags\/title"},{"value":[{"text":"MBXHttpRequestFlags","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestFlags\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestFlags\/navigatorTitle","op":"replace","value":[{"text":"MBXHttpRequestFlags","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestFlags~1pauseInBackground\/title","op":"replace","value":"PauseInBackground"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestFlags~1pauseInBackground\/fragments","op":"replace","value":[{"text":"PauseInBackground","kind":"identifier"}]}]}]}