{"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionTilePyramidDefinition\/pixelRatio"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionTilePyramidDefinition"]]},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pixelRatio","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/mapboxmaps\/offlineregiontilepyramiddefinition\/pixelratio"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/offlineregiontilepyramiddefinition\/pixelratio"]}],"abstract":[{"text":"Pixel ratio to be accounted for when downloading assets.","type":"text"}],"metadata":{"navigatorTitle":[{"text":"pixelRatio","kind":"identifier"}],"platforms":[],"role":"symbol","roleHeading":"Instance Property","modules":[{"name":"MapboxMaps"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pixelRatio","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"title":"pixelRatio","symbolKind":"property","externalID":"c:objc(cs)MBMOfflineRegionTilePyramidDefinition(py)pixelRatio"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionTilePyramidDefinition/pixelRatio":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"pixelRatio","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionTilePyramidDefinition\/pixelRatio","navigatorTitle":[{"kind":"identifier","text":"pixelRatio"}],"url":"\/documentation\/mapboxmaps\/offlineregiontilepyramiddefinition\/pixelratio","title":"pixelRatio","abstract":[{"type":"text","text":"Pixel ratio to be accounted for when downloading assets."}],"deprecated":true},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionTilePyramidDefinition":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"OfflineRegionTilePyramidDefinition","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/offlineregiontilepyramiddefinition","deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"OfflineRegionTilePyramidDefinition"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"An offline region definition is a geographic region defined by a style URL,"},{"type":"text","text":" "},{"type":"text","text":"geographic bounding box, zoom range, and device pixel ratio. Both "},{"code":"minZoom","type":"codeVoice"},{"type":"text","text":" and "},{"type":"codeVoice","code":"maxZoom"},{"text":" must be ≥ 0,","type":"text"},{"type":"text","text":" "},{"text":"and ","type":"text"},{"type":"codeVoice","code":"maxZoom"},{"text":" must be ≥ ","type":"text"},{"type":"codeVoice","code":"minZoom"},{"type":"text","text":". The "},{"type":"codeVoice","code":"maxZoom"},{"type":"text","text":" may be ∞, in which case for each tile source,"},{"type":"text","text":" "},{"text":"the region will include tiles from ","type":"text"},{"code":"minZoom","type":"codeVoice"},{"text":" up to the maximum zoom level provided by that source.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The "},{"type":"codeVoice","code":"pixelRatio"},{"type":"text","text":" must be ≥ 0 and should typically be 1.0 or 2.0."}],"title":"OfflineRegionTilePyramidDefinition","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionTilePyramidDefinition","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Offline":{"url":"\/documentation\/mapboxmaps\/offline","kind":"article","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","abstract":[],"role":"collectionGroup","title":"Offline Support"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMaps":{"kind":"article","abstract":[{"text":"Maps rendering SDK also known as GL-Native","type":"text"}],"url":"\/documentation\/mapboxmaps\/coremaps","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","type":"topic","title":"Core Maps API"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","role":"collection","abstract":[],"type":"topic","kind":"article"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"pixelRatio"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"pixelRatio","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"float","kind":"typeIdentifier","preciseIdentifier":"c:f"},{"text":" ","kind":"text"},{"text":"pixelRatio","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionTilePyramidDefinition~1pixelRatio\/title","value":"pixelRatio","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionTilePyramidDefinition~1pixelRatio\/fragments","value":[{"kind":"identifier","text":"pixelRatio"}],"op":"replace"},{"value":"MBMOfflineRegionTilePyramidDefinition","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionTilePyramidDefinition\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionTilePyramidDefinition\/fragments","value":[{"kind":"identifier","text":"MBMOfflineRegionTilePyramidDefinition"}],"op":"replace"},{"op":"replace","value":[{"text":"MBMOfflineRegionTilePyramidDefinition","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionTilePyramidDefinition\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}