{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions"]]},"sections":[],"abstract":[{"type":"text","text":"The callback that cancels a tile."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelTileFunction"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileFunctionCallback","preciseIdentifier":"c:MBMTileFunctionCallback.h@T@MBMTileFunctionCallback","text":"TileFunctionCallback","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"navigatorTitle":[{"text":"cancelTileFunction","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"MapboxMaps"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cancelTileFunction"},{"kind":"text","text":": "},{"text":"TileFunctionCallback","preciseIdentifier":"c:MBMTileFunctionCallback.h@T@MBMTileFunctionCallback","kind":"typeIdentifier"}],"title":"cancelTileFunction","externalID":"c:objc(cs)MBMCustomGeometrySourceOptions(py)cancelTileFunction"},"variants":[{"paths":["\/documentation\/mapboxmaps\/customgeometrysourceoptions\/canceltilefunction"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/customgeometrysourceoptions\/canceltilefunction"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions\/cancelTileFunction","interfaceLanguage":"swift"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomGeometrySourceOptions/cancelTileFunction":{"abstract":[{"type":"text","text":"The callback that cancels a tile."}],"title":"cancelTileFunction","url":"\/documentation\/mapboxmaps\/customgeometrysourceoptions\/canceltilefunction","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cancelTileFunction","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:MBMTileFunctionCallback.h@T@MBMTileFunctionCallback","text":"TileFunctionCallback","kind":"typeIdentifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cancelTileFunction"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions\/cancelTileFunction"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Sources":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources","url":"\/documentation\/mapboxmaps\/sources","abstract":[],"type":"topic","role":"collectionGroup","title":"Sources","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","url":"\/documentation\/mapboxmaps","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"title":"MapboxMaps","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","abstract":[],"type":"topic","kind":"article","title":"MapboxMaps Documentation","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomGeometrySourceOptions":{"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Options for custom geometry source."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CustomGeometrySourceOptions","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/customgeometrysourceoptions","type":"topic","title":"CustomGeometrySourceOptions","navigatorTitle":[{"kind":"identifier","text":"CustomGeometrySourceOptions"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileFunctionCallback":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileFunctionCallback"}],"kind":"symbol","title":"TileFunctionCallback","abstract":[{"text":"Callback to do various operations for tile.","type":"text"},{"text":" ","type":"text"},{"text":"For example, fetching a tile or cancelling a tile request.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"TileFunctionCallback"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileFunctionCallback","role":"symbol","url":"\/documentation\/mapboxmaps\/tilefunctioncallback","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"cancelTileFunction","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"text":"cancelTileFunction","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$objc(cs)MBMCanonicalTileID)","text":"void (^)(MBMCanonicalTileID *)"},{"text":" ","kind":"text"},{"text":"cancelTileFunction","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"op":"replace","value":"cancelTileFunction","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions~1cancelTileFunction\/title"},{"op":"replace","value":[{"text":"cancelTileFunction","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions~1cancelTileFunction\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions\/title","value":"MBMCustomGeometrySourceOptions","op":"replace"},{"value":[{"text":"MBMCustomGeometrySourceOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions\/fragments"},{"value":[{"text":"MBMCustomGeometrySourceOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileFunctionCallback\/title","value":"MBMTileFunctionCallback","op":"replace"},{"value":[{"text":"MBMTileFunctionCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileFunctionCallback\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileFunctionCallback\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMTileFunctionCallback"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}