{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tileOptions"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MBMTileOptions","text":"TileOptions","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileOptions"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions"]]},"kind":"symbol","metadata":{"navigatorTitle":[{"text":"tileOptions","kind":"identifier"}],"symbolKind":"property","roleHeading":"Instance Property","role":"symbol","modules":[{"name":"MapboxMaps"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"tileOptions","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TileOptions","preciseIdentifier":"c:objc(cs)MBMTileOptions","kind":"typeIdentifier"}],"externalID":"c:objc(cs)MBMCustomGeometrySourceOptions(py)tileOptions","title":"tileOptions"},"abstract":[{"text":"Tile options.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions\/tileOptions"},"variants":[{"paths":["\/documentation\/mapboxmaps\/customgeometrysourceoptions\/tileoptions"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/customgeometrysourceoptions\/tileoptions"]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomGeometrySourceOptions/tileOptions":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions\/tileOptions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"tileOptions","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TileOptions","preciseIdentifier":"c:objc(cs)MBMTileOptions"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/customgeometrysourceoptions\/tileoptions","title":"tileOptions","type":"topic","navigatorTitle":[{"text":"tileOptions","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Tile options.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","role":"collection","url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"title":"MapboxMaps","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomGeometrySourceOptions":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomGeometrySourceOptions"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions","navigatorTitle":[{"text":"CustomGeometrySourceOptions","kind":"identifier"}],"title":"CustomGeometrySourceOptions","url":"\/documentation\/mapboxmaps\/customgeometrysourceoptions","abstract":[{"type":"text","text":"Options for custom geometry source."}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileOptions":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileOptions","kind":"symbol","abstract":[{"type":"text","text":"Options for custom geometry tiles."}],"title":"TileOptions","url":"\/documentation\/mapboxmaps\/tileoptions","navigatorTitle":[{"text":"TileOptions","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TileOptions","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"tileOptions","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"tileOptions","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)MBMTileOptions","text":"MBMTileOptions","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileOptions"},{"text":" * ","kind":"text"},{"text":"tileOptions","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","value":"tileOptions","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions~1tileOptions\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions~1tileOptions\/fragments","value":[{"kind":"identifier","text":"tileOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions\/title","value":"MBMCustomGeometrySourceOptions"},{"value":[{"text":"MBMCustomGeometrySourceOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBMCustomGeometrySourceOptions"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileOptions\/title","value":"MBMTileOptions","op":"replace"},{"value":[{"text":"MBMTileOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileOptions\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileOptions\/navigatorTitle","value":[{"text":"MBMTileOptions","kind":"identifier"}],"op":"replace"}]}]}