{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/ValueConverter"]]},"variants":[{"paths":["\/documentation\/mapboxcommon\/valueconverter\/tojson(forvalue:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxcommon\/valueconverter\/tojson(forvalue:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Converts value to a JSON string."},{"type":"text","text":" "},{"text":"The method is intended to be used when ","type":"text"},{"code":"machine-readable","type":"codeVoice"},{"text":" string is needed.","type":"text"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/ValueConverter\/toJson(forValue:)"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"toJson"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forValue"},{"text":" ","kind":"text"},{"text":"value","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The value to be converted."}]}],"name":"value"}],"kind":"parameters"},{"kind":"content","content":[{"text":"Return Value","level":2,"anchor":"return-value","type":"heading"},{"inlineContent":[{"type":"text","text":"String The value converted to a JSON string."}],"type":"paragraph"}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"toJsonForValue:"}],"externalID":"c:objc(cs)MBXValueConverter(cm)toJsonForValue:","title":"toJson(forValue:)","roleHeading":"Type Method","symbolKind":"method","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"toJson"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forValue"},{"kind":"text","text":": "},{"text":"Any","kind":"keyword"},{"kind":"text","text":") -> "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"modules":[{"name":"MapboxCommon"}]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","role":"collection","kind":"symbol","title":"MapboxCommon","type":"topic","url":"\/documentation\/mapboxcommon"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/ValueConverter":{"kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"ValueConverter"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ValueConverter"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/ValueConverter","type":"topic","role":"symbol","url":"\/documentation\/mapboxcommon\/valueconverter","title":"ValueConverter"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/ValueConverter/toJson(forValue:)":{"kind":"symbol","abstract":[{"text":"Converts value to a JSON string.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The method is intended to be used when "},{"code":"machine-readable","type":"codeVoice"},{"type":"text","text":" string is needed."}],"navigatorTitle":[{"text":"toJsonForValue:","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"toJson","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forValue"},{"kind":"text","text":": "},{"text":"Any","kind":"keyword"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/ValueConverter\/toJson(forValue:)","type":"topic","role":"symbol","url":"\/documentation\/mapboxcommon\/valueconverter\/tojson(forvalue:)","title":"toJson(forValue:)"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","url":"\/documentation\/overview","title":"MapboxMaps Documentation"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"value":"toJsonForValue:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"toJsonForValue:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"toJsonForValue:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"text":"value","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"value","content":[{"inlineContent":[{"text":"The value to be converted.","type":"text"}],"type":"paragraph"}]}]}},{"value":{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"String The value converted to a JSON string."}]}]},"path":"\/primaryContentSections\/2","op":"replace"},{"value":"MBXValueConverter","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1ValueConverter\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1ValueConverter\/fragments","value":[{"text":"MBXValueConverter","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"MBXValueConverter"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1ValueConverter\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1ValueConverter~1toJson(forValue:)\/title","op":"replace","value":"toJsonForValue:"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1ValueConverter~1toJson(forValue:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"toJsonForValue:","kind":"identifier"}],"op":"replace"}]}]}