{"sections":[],"abstract":[{"text":"The minimum elapsed time required before performance statistics become available. It’s important to note that the actual","type":"text"},{"text":" ","type":"text"},{"text":"collection interval may exceed this duration since statistics are aggregated during render calls. The effective collection","type":"text"},{"text":" ","type":"text"},{"text":"interval can be observed through the ","type":"text"},{"code":"PerformanceStatistics","type":"codeVoice"},{"text":" instance.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"samplingDurationMillis","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Setting ","type":"text"},{"type":"codeVoice","code":"samplingDurationMillis"},{"text":" to 0 forces the collection of performance statistics every frame.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"A negative sampling duration is an error and results in no operation.","type":"text"}]}]}],"variants":[{"paths":["\/documentation\/mapboxmaps\/performancestatisticsoptions\/samplingdurationmillis"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/performancestatisticsoptions\/samplingdurationmillis"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatisticsOptions\/samplingDurationMillis"},"metadata":{"title":"samplingDurationMillis","modules":[{"name":"MapboxMaps"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"samplingDurationMillis"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"symbolKind":"property","externalID":"c:objc(cs)MBMPerformanceStatisticsOptions(py)samplingDurationMillis","role":"symbol","navigatorTitle":[{"text":"samplingDurationMillis","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatisticsOptions"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PerformanceStatisticsOptions":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatisticsOptions","abstract":[{"text":"Options for the following statistics collection behaviors:","type":"text"}],"url":"\/documentation\/mapboxmaps\/performancestatisticsoptions","navigatorTitle":[{"text":"PerformanceStatisticsOptions","kind":"identifier"}],"title":"PerformanceStatisticsOptions","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PerformanceStatisticsOptions","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Performance":{"type":"topic","abstract":[],"title":"Performance and investigations","url":"\/documentation\/mapboxmaps\/performance","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PerformanceStatisticsOptions/samplingDurationMillis":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatisticsOptions\/samplingDurationMillis","abstract":[{"type":"text","text":"The minimum elapsed time required before performance statistics become available. It’s important to note that the actual"},{"text":" ","type":"text"},{"text":"collection interval may exceed this duration since statistics are aggregated during render calls. The effective collection","type":"text"},{"text":" ","type":"text"},{"text":"interval can be observed through the ","type":"text"},{"type":"codeVoice","code":"PerformanceStatistics"},{"text":" instance.","type":"text"}],"title":"samplingDurationMillis","kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/performancestatisticsoptions\/samplingdurationmillis","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"samplingDurationMillis","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"samplingDurationMillis","kind":"identifier"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"url":"\/documentation\/overview","kind":"article","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"url":"\/documentation\/mapboxmaps","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","title":"MapboxMaps","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"samplingDurationMillis"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"samplingDurationMillis"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"samplingDurationMillis","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatisticsOptions\/title","value":"MBMPerformanceStatisticsOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatisticsOptions\/fragments","value":[{"text":"MBMPerformanceStatisticsOptions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatisticsOptions\/navigatorTitle","value":[{"text":"MBMPerformanceStatisticsOptions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatisticsOptions~1samplingDurationMillis\/title","value":"samplingDurationMillis"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatisticsOptions~1samplingDurationMillis\/fragments","value":[{"kind":"identifier","text":"samplingDurationMillis"}]}]}]}