{"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance"]]},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogConfiguration","interfaceLanguage":"swift"},"metadata":{"title":"LogConfiguration","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LogConfiguration","kind":"identifier"}],"externalID":"c:objc(cs)MBXLogConfiguration","modules":[{"name":"MapboxCommon"}],"navigatorTitle":[{"text":"LogConfiguration","kind":"identifier"}],"role":"symbol","symbolKind":"class"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LogConfiguration","kind":"identifier"}]}],"kind":"declarations"}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"kind":"relationships"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH"],"kind":"relationships"}],"topicSections":[{"title":"Type Methods","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogConfiguration\/getLoggingLevel()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogConfiguration\/getLoggingLevel(forCategory:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogConfiguration\/registerLogWriterBackend(forLogWriter:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogConfiguration\/resetLoggingLevel(forCategory:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogConfiguration\/setLoggingLevelForCategory(_:upTo:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogConfiguration\/setLoggingLevelForUpTo(_:)"],"generated":true,"anchor":"Type-Methods"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Class that allows to configure Mapbox SDKs logging per application."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/logconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/logconfiguration"]}],"seeAlsoSections":[{"title":"Logs","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogWriterBackend","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LoggingLevel"],"generated":true,"anchor":"Logs"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Performance":{"kind":"article","url":"\/documentation\/mapboxmaps\/performance","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","abstract":[],"title":"Performance and investigations","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LogConfiguration/setLoggingLevelForCategory(_:upTo:)":{"kind":"symbol","type":"topic","abstract":[{"text":"Sets the logging level for provided category.","type":"text"},{"text":" ","type":"text"},{"text":"If set, takes precedence over the default logging level.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLoggingLevelForCategory"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"upTo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?)"}],"title":"setLoggingLevelForCategory(_:upTo:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogConfiguration\/setLoggingLevelForCategory(_:upTo:)","navigatorTitle":[{"kind":"identifier","text":"setLoggingLevelForCategory:upTo:"}],"url":"\/documentation\/mapboxcommon\/logconfiguration\/setlogginglevelforcategory(_:upto:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","role":"collection","title":"MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LogConfiguration/registerLogWriterBackend(forLogWriter:)":{"title":"registerLogWriterBackend(forLogWriter:)","navigatorTitle":[{"kind":"identifier","text":"registerLogWriterBackendForLogWriter:"}],"kind":"symbol","abstract":[{"type":"text","text":"Sets the backend which writes the log."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogConfiguration\/registerLogWriterBackend(forLogWriter:)","role":"symbol","url":"\/documentation\/mapboxcommon\/logconfiguration\/registerlogwriterbackend(forlogwriter:)","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerLogWriterBackend"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forLogWriter"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:objc(pl)MBXLogWriterBackend","kind":"typeIdentifier","text":"LogWriterBackend"},{"kind":"text","text":")?)"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LogConfiguration/resetLoggingLevel(forCategory:)":{"title":"resetLoggingLevel(forCategory:)","navigatorTitle":[{"text":"resetLoggingLevelForCategory:","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogConfiguration\/resetLoggingLevel(forCategory:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resetLoggingLevel","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forCategory","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/mapboxcommon\/logconfiguration\/resetlogginglevel(forcategory:)","abstract":[{"type":"text","text":"Reset logging level for category to default logging level."}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LogConfiguration/getLoggingLevel()":{"abstract":[{"text":"Return current default logging level.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getLoggingLevel"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"getLoggingLevel"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogConfiguration\/getLoggingLevel()","title":"getLoggingLevel()","type":"topic","url":"\/documentation\/mapboxcommon\/logconfiguration\/getlogginglevel()","kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","url":"\/documentation\/overview","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","kind":"article","abstract":[]},"doc://com.mapbox.MapboxMaps/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.mapbox.MapboxMaps/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.mapbox.MapboxMaps/SH":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","title":"Swift.Hashable"},"doc://com.mapbox.MapboxMaps/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","title":"Swift.Equatable"},"doc://com.mapbox.MapboxMaps/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.mapbox.MapboxMaps/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject","title":"NSObject"},"doc://com.mapbox.MapboxMaps/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LogConfiguration/getLoggingLevel(forCategory:)":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogConfiguration\/getLoggingLevel(forCategory:)","title":"getLoggingLevel(forCategory:)","url":"\/documentation\/mapboxcommon\/logconfiguration\/getlogginglevel(forcategory:)","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getLoggingLevel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forCategory"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Return current logging level for category."}],"navigatorTitle":[{"kind":"identifier","text":"getLoggingLevelForCategory:"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LogConfiguration/setLoggingLevelForUpTo(_:)":{"abstract":[{"text":"Sets the default logging level.","type":"text"}],"url":"\/documentation\/mapboxcommon\/logconfiguration\/setlogginglevelforupto(_:)","role":"symbol","title":"setLoggingLevelForUpTo(_:)","kind":"symbol","navigatorTitle":[{"text":"setLoggingLevelForUpTo:","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setLoggingLevelForUpTo","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogConfiguration\/setLoggingLevelForUpTo(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LogWriterBackend":{"navigatorTitle":[{"text":"LogWriterBackend","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LogWriterBackend","kind":"identifier"}],"abstract":[{"text":"Interface for implementing log writing backends, e.g. for using platform specific log backends or logging to a notification service.","type":"text"}],"type":"topic","title":"LogWriterBackend","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogWriterBackend","role":"symbol","url":"\/documentation\/mapboxcommon\/logwriterbackend"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LogConfiguration":{"title":"LogConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogConfiguration"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogConfiguration","navigatorTitle":[{"text":"LogConfiguration","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"text":"Class that allows to configure Mapbox SDKs logging per application.","type":"text"}],"url":"\/documentation\/mapboxcommon\/logconfiguration"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LoggingLevel":{"title":"LoggingLevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoggingLevel"}],"abstract":[{"type":"text","text":"State level of a log message."}],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/mapboxcommon\/logginglevel","navigatorTitle":[{"kind":"identifier","text":"LoggingLevel"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LoggingLevel"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"MBXLogConfiguration","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"MBXLogConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"MBXLogConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Type Methods","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogConfiguration\/getLoggingLevel()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogConfiguration\/getLoggingLevel(forCategory:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogConfiguration\/registerLogWriterBackend(forLogWriter:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogConfiguration\/resetLoggingLevel(forCategory:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogConfiguration\/setLoggingLevelForCategory(_:upTo:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogConfiguration\/setLoggingLevelForUpTo(_:)"],"generated":true,"anchor":"Type-Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"type":"inheritsFrom"}],"op":"replace"},{"path":"\/seeAlsoSections","value":[{"anchor":"Logs","title":"Logs","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogWriterBackend","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LoggingLevel"],"generated":true}],"op":"replace"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBXLogConfiguration"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogConfiguration~1setLoggingLevelForCategory(_:upTo:)\/title","value":"setLoggingLevelForCategory:upTo:","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogConfiguration~1setLoggingLevelForCategory(_:upTo:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setLoggingLevelForCategory:upTo:"}],"op":"replace"},{"value":"registerLogWriterBackendForLogWriter:","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogConfiguration~1registerLogWriterBackend(forLogWriter:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"registerLogWriterBackendForLogWriter:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogConfiguration~1registerLogWriterBackend(forLogWriter:)\/fragments"},{"value":"resetLoggingLevelForCategory:","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogConfiguration~1resetLoggingLevel(forCategory:)\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"resetLoggingLevelForCategory:"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogConfiguration~1resetLoggingLevel(forCategory:)\/fragments"},{"op":"replace","value":"getLoggingLevel","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogConfiguration~1getLoggingLevel()\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getLoggingLevel"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogConfiguration~1getLoggingLevel()\/fragments"},{"op":"replace","value":"getLoggingLevelForCategory:","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogConfiguration~1getLoggingLevel(forCategory:)\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getLoggingLevelForCategory:"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogConfiguration~1getLoggingLevel(forCategory:)\/fragments"},{"op":"replace","value":"setLoggingLevelForUpTo:","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogConfiguration~1setLoggingLevelForUpTo(_:)\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"setLoggingLevelForUpTo:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogConfiguration~1setLoggingLevelForUpTo(_:)\/fragments"},{"op":"replace","value":"MBXLogWriterBackend","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogWriterBackend\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBXLogWriterBackend"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogWriterBackend\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MBXLogWriterBackend"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogWriterBackend\/navigatorTitle"},{"op":"replace","value":"MBXLogConfiguration","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogConfiguration\/title"},{"op":"replace","value":[{"text":"MBXLogConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MBXLogConfiguration"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogConfiguration\/navigatorTitle"},{"op":"replace","value":"MBXLoggingLevel","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LoggingLevel\/title"},{"op":"replace","value":[{"text":"MBXLoggingLevel","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LoggingLevel\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MBXLoggingLevel"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LoggingLevel\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}