{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationObserver"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/locationobserver\/onlocationupdatereceived(for:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/locationobserver\/onlocationupdatereceived(for:)"]}],"metadata":{"modules":[{"name":"MapboxCommon"}],"roleHeading":"Instance Method","symbolKind":"method","externalID":"c:objc(pl)MBXLocationObserver(im)onLocationUpdateReceivedForLocations:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onLocationUpdateReceived","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBXLocation","text":"Location","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"required":true,"role":"symbol","title":"onLocationUpdateReceived(for:)","navigatorTitle":[{"text":"onLocationUpdateReceivedForLocations:","kind":"identifier"}]},"kind":"symbol","abstract":[{"text":"Report when location has changed.","type":"text"}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationObserver\/onLocationUpdateReceived(for:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onLocationUpdateReceived"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"locations"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXLocation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location","text":"Location"},{"kind":"text","text":"])"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"A batch of locations, ordered from oldest to newest, generated during the location updates interval."}],"type":"paragraph"}],"name":"locations"}],"kind":"parameters"}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationObserver/onLocationUpdateReceived(for:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationObserver\/onLocationUpdateReceived(for:)","url":"\/documentation\/mapboxcommon\/locationobserver\/onlocationupdatereceived(for:)","role":"symbol","kind":"symbol","title":"onLocationUpdateReceived(for:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onLocationUpdateReceived","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBXLocation","text":"Location","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"abstract":[{"type":"text","text":"Report when location has changed."}],"navigatorTitle":[{"text":"onLocationUpdateReceivedForLocations:","kind":"identifier"}],"required":true},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","role":"collection","title":"MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Location-APIs":{"url":"\/documentation\/mapboxmaps\/location-apis","role":"collectionGroup","abstract":[],"kind":"article","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","title":"Location"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Location":{"kind":"symbol","title":"Location","type":"topic","abstract":[{"type":"text","text":"Location information."}],"url":"\/documentation\/mapboxcommon\/location","navigatorTitle":[{"text":"Location","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Location","kind":"identifier"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","abstract":[],"type":"topic","title":"MapboxMaps Documentation","kind":"article","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationObserver":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationObserver","navigatorTitle":[{"kind":"identifier","text":"LocationObserver"}],"kind":"symbol","abstract":[{"type":"text","text":"Observer for getting updates from a LocationProvider."}],"role":"symbol","title":"LocationObserver","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationObserver"}],"url":"\/documentation\/mapboxcommon\/locationobserver"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"onLocationUpdateReceivedForLocations:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"onLocationUpdateReceivedForLocations:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onLocationUpdateReceivedForLocations:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<MBXLocation *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"locations"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"name":"locations","content":[{"inlineContent":[{"type":"text","text":"A batch of locations, ordered from oldest to newest, generated during the location updates interval."}],"type":"paragraph"}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"onLocationUpdateReceivedForLocations:","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver~1onLocationUpdateReceived(for:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onLocationUpdateReceivedForLocations:"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver~1onLocationUpdateReceived(for:)\/fragments"},{"value":"MBXLocation","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/title"},{"value":[{"kind":"identifier","text":"MBXLocation"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/fragments"},{"value":[{"text":"MBXLocation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/navigatorTitle"},{"value":"MBXLocationObserver","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/title"},{"value":[{"kind":"identifier","text":"MBXLocationObserver"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/fragments"},{"value":[{"kind":"identifier","text":"MBXLocationObserver"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/navigatorTitle"}]}]}