{"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OverviewViewportState\/observeDataSource(with:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"observeDataSource"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"handler"},{"kind":"text","text":": "},{"kind":"keyword","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","text":"CameraOptions","preciseIdentifier":"s:10MapboxMaps13CameraOptionsV","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraOptions"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> any "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Cancelable","kind":"typeIdentifier","text":"Cancelable","preciseIdentifier":"c:objc(pl)MBXCancelable"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"roleHeading":"Instance Method","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"observeDataSource"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps13CameraOptionsV","text":"CameraOptions"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":") -> any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MBXCancelable","text":"Cancelable"}],"modules":[{"name":"MapboxMaps"}],"extendedModule":"MapboxMaps","externalID":"s:10MapboxMaps21OverviewViewportStateC17observeDataSource4withSo13MBXCancelable_pSbAA13CameraOptionsVc_tF","title":"observeDataSource(with:)","symbolKind":"method"},"abstract":[{"text":":nodoc:","type":"text"},{"text":" ","type":"text"},{"text":"See ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportState\/observeDataSource(with:)","isActive":true,"type":"reference"},{"text":".","type":"text"}],"variants":[{"paths":["\/documentation\/mapboxmaps\/overviewviewportstate\/observedatasource(with:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Camera-and-coordinates","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OverviewViewportState","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OverviewViewportState\/ViewportState-Implementations"],["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Camera-and-coordinates","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OverviewViewportState","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OverviewViewportState\/ViewportState-Implementations"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"role":"collection","kind":"symbol","url":"\/documentation\/mapboxmaps","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraOptions":{"navigatorTitle":[{"text":"CameraOptions","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraOptions","abstract":[],"title":"CameraOptions","type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraOptions","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/cameraoptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OverviewViewportStateOptions/geometry":{"title":"geometry","url":"\/documentation\/mapboxmaps\/overviewviewportstateoptions\/geometry","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OverviewViewportStateOptions\/geometry","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"geometry"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10MapboxMaps8Geometrya","kind":"typeIdentifier","text":"Geometry"}],"abstract":[{"text":"The geometry that the ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OverviewViewportState","isActive":true,"type":"reference"},{"text":" should use when calculating its camera.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"abstract":[],"role":"collectionGroup","title":"MapboxMap","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","kind":"article","url":"\/documentation\/mapboxmaps\/mapboxmap-apis","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OverviewViewportState/ViewportState-Implementations":{"url":"\/documentation\/mapboxmaps\/overviewviewportstate\/viewportstate-implementations","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OverviewViewportState\/ViewportState-Implementations","kind":"article","title":"ViewportState Implementations","type":"topic","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OverviewViewportState/observeDataSource(with:)":{"kind":"symbol","title":"observeDataSource(with:)","abstract":[{"text":":nodoc:","type":"text"},{"text":" ","type":"text"},{"text":"See ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportState\/observeDataSource(with:)","type":"reference","isActive":true},{"text":".","type":"text"}],"url":"\/documentation\/mapboxmaps\/overviewviewportstate\/observedatasource(with:)","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OverviewViewportState\/observeDataSource(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"observeDataSource"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"CameraOptions","preciseIdentifier":"s:10MapboxMaps13CameraOptionsV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> any "},{"kind":"typeIdentifier","text":"Cancelable","preciseIdentifier":"c:objc(pl)MBXCancelable"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OverviewViewportState":{"navigatorTitle":[{"text":"OverviewViewportState","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OverviewViewportState","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OverviewViewportState","kind":"symbol","url":"\/documentation\/mapboxmaps\/overviewviewportstate","type":"topic","abstract":[{"type":"text","text":"A "},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportState","isActive":true},{"type":"text","text":" implementation that shows an overview of the geometry specified by its"},{"type":"text","text":" "},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OverviewViewportStateOptions\/geometry","isActive":true},{"type":"text","text":"."}],"title":"OverviewViewportState","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewportState/observeDataSource(with:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"observeDataSource","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"CameraOptions","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps13CameraOptionsV"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":") -> any ","kind":"text"},{"text":"Cancelable","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MBXCancelable"}],"required":true,"role":"symbol","abstract":[{"text":"Registers a ","type":"text"},{"code":"handler","type":"codeVoice"},{"text":" to receive the cameras being generated by this ","type":"text"},{"code":"ViewportState","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportState\/observeDataSource(with:)","url":"\/documentation\/mapboxmaps\/viewportstate\/observedatasource(with:)","title":"observeDataSource(with:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewportState":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ViewportState","kind":"identifier"}],"role":"symbol","abstract":[{"type":"codeVoice","code":"ViewportState"},{"type":"text","text":" is a protocol that "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportManager"},{"type":"text","text":" depends on as it orchestrates transitions to and"},{"type":"text","text":" "},{"type":"text","text":"from different states."}],"url":"\/documentation\/mapboxmaps\/viewportstate","kind":"symbol","title":"ViewportState","navigatorTitle":[{"text":"ViewportState","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportState","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Camera-and-coordinates":{"url":"\/documentation\/mapboxmaps\/camera-and-coordinates","title":"Camera and coordinates","role":"collectionGroup","type":"topic","abstract":[],"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Camera-and-coordinates"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","kind":"article","title":"MapboxMaps Documentation","url":"\/documentation\/overview","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Cancelable":{"title":"Cancelable","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Cancelable"}],"kind":"symbol","url":"\/documentation\/mapboxcommon\/cancelable","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Cancelable"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Cancelable","abstract":[{"type":"text","text":"Allows to cancel the associated asynchronous operation"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"MBXCancelable","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/title"},{"op":"replace","value":[{"text":"MBXCancelable","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/fragments"},{"op":"replace","value":[{"text":"MBXCancelable","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}