{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions"]]},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions\/setPositionForPosition(_:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/mapboxmaps\/freecameraoptions\/setpositionforposition(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/freecameraoptions\/setpositionforposition(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPositionForPosition"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"position"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Vec3","text":"Vec3","preciseIdentifier":"c:objc(cs)MBMVec3"},{"kind":"text","text":"?)"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"position","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The position to be set."}]}]}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"The size of 1 unit is the width of the projected world instead of the “mercator meter”."},{"type":"text","text":" "},{"type":"text","text":"Coordinate [0, 0, 0] is the north-west corner and [1, 1, 0] is the south-east corner."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Z coordinate is conformal and must respect minimum and maximum zoom values."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Zoom is automatically computed from the altitude (z)","type":"text"}],"type":"paragraph"}]}]}]}],"metadata":{"symbolKind":"method","role":"symbol","roleHeading":"Instance Method","title":"setPositionForPosition(_:)","navigatorTitle":[{"text":"setPositionForPosition:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setPositionForPosition","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMVec3","text":"Vec3","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"externalID":"c:objc(cs)MBMFreeCameraOptions(im)setPositionForPosition:","modules":[{"name":"MapboxMaps"}]},"kind":"symbol","abstract":[{"type":"text","text":"Set the position of the camera in slightly modified web mercator coordinates"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FreeCameraOptions/setPositionForPosition(_:)":{"role":"symbol","abstract":[{"text":"Set the position of the camera in slightly modified web mercator coordinates","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions\/setPositionForPosition(_:)","url":"\/documentation\/mapboxmaps\/freecameraoptions\/setpositionforposition(_:)","navigatorTitle":[{"text":"setPositionForPosition:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setPositionForPosition","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Vec3","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMVec3"},{"text":"?)","kind":"text"}],"title":"setPositionForPosition(_:)","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","role":"collection","title":"MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FreeCameraOptions":{"abstract":[{"text":"Various options for accessing physical properties of the underlying camera entity.","type":"text"},{"text":" ","type":"text"},{"text":"A direct access to these properties allows more flexible and precise controlling","type":"text"},{"text":" ","type":"text"},{"text":"of the camera while also being fully compatible and interchangeable with CameraOptions.","type":"text"},{"text":" ","type":"text"},{"text":"All fields are optional.","type":"text"}],"url":"\/documentation\/mapboxmaps\/freecameraoptions","title":"FreeCameraOptions","kind":"symbol","navigatorTitle":[{"text":"FreeCameraOptions","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FreeCameraOptions","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"type":"topic","title":"MapboxMap","kind":"article","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","url":"\/documentation\/mapboxmaps\/mapboxmap-apis"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Vec3":{"role":"symbol","navigatorTitle":[{"text":"Vec3","kind":"identifier"}],"abstract":[{"type":"text","text":"3 component vector."}],"url":"\/documentation\/mapboxmaps\/vec3","type":"topic","title":"Vec3","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Vec3","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Vec3","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","abstract":[],"type":"topic","title":"MapboxMaps Documentation","kind":"article","url":"\/documentation\/overview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setPositionForPosition:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setPositionForPosition:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"setPositionForPosition:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Vec3","preciseIdentifier":"c:objc(cs)MBMVec3","text":"MBMVec3"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"position"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"position","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The position to be set."}]}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions~1setPositionForPosition(_:)\/title","value":"setPositionForPosition:"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions~1setPositionForPosition(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setPositionForPosition:"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions\/title","op":"replace","value":"MBMFreeCameraOptions"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMFreeCameraOptions"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions\/navigatorTitle","op":"replace","value":[{"text":"MBMFreeCameraOptions","kind":"identifier"}]},{"op":"replace","value":"MBMVec3","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Vec3\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBMVec3"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Vec3\/fragments"},{"op":"replace","value":[{"text":"MBMVec3","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Vec3\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}