{"variants":[{"paths":["\/documentation\/mapboxmaps\/coordinatebounds\/contains(forarea:wrappedcoordinates:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/coordinatebounds\/contains(forarea:wrappedcoordinates:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:objc(cs)MBMCoordinateBounds(im)containsForArea:wrappedCoordinates:","title":"contains(forArea:wrappedCoordinates:)","symbolKind":"method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contains","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forArea","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMCoordinateBounds","text":"CoordinateBounds","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"wrappedCoordinates","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"roleHeading":"Instance Method","modules":[{"name":"MapboxMaps"}],"navigatorTitle":[{"text":"containsForArea:wrappedCoordinates:","kind":"identifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds"]]},"kind":"symbol","abstract":[{"text":"Returns whether the bounds contains ","type":"text"},{"code":"area","type":"codeVoice"},{"text":" or not.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"contains"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forArea"},{"kind":"text","text":" "},{"kind":"internalParam","text":"area"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MBMCoordinateBounds","kind":"typeIdentifier","text":"CoordinateBounds","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds"},{"kind":"text","text":", "},{"kind":"externalParam","text":"wrappedCoordinates"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"area","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The area to be checked against the bounds."}]}]},{"name":"wrappedCoordinates","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Whether to wrap the coordinate or not."}]}]}],"kind":"parameters"},{"content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"inlineContent":[{"code":"true","type":"codeVoice"},{"type":"text","text":" if the bounds contains "},{"code":"area","type":"codeVoice"},{"type":"text","text":", "},{"code":"false","type":"codeVoice"},{"type":"text","text":" otherwise."}],"type":"paragraph"}],"kind":"content"}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds\/contains(forArea:wrappedCoordinates:)","interfaceLanguage":"swift"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateBounds":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoordinateBounds"}],"abstract":[{"type":"text","text":"A rectangular area as measured on a two-dimensional map projection."}],"url":"\/documentation\/mapboxmaps\/coordinatebounds","role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds","navigatorTitle":[{"kind":"identifier","text":"CoordinateBounds"}],"title":"CoordinateBounds","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","url":"\/documentation\/mapboxmaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateBounds/contains(forArea:wrappedCoordinates:)":{"abstract":[{"text":"Returns whether the bounds contains ","type":"text"},{"code":"area","type":"codeVoice"},{"text":" or not.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"containsForArea:wrappedCoordinates:","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds\/contains(forArea:wrappedCoordinates:)","url":"\/documentation\/mapboxmaps\/coordinatebounds\/contains(forarea:wrappedcoordinates:)","title":"contains(forArea:wrappedCoordinates:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contains","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forArea","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CoordinateBounds","preciseIdentifier":"c:objc(cs)MBMCoordinateBounds","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"wrappedCoordinates","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","role":"collectionGroup","title":"MapboxMap","type":"topic","kind":"article","abstract":[],"url":"\/documentation\/mapboxmaps\/mapboxmap-apis"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","kind":"article","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"containsForArea:wrappedCoordinates:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"containsForArea:wrappedCoordinates:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"containsForArea:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MBMCoordinateBounds","preciseIdentifier":"c:objc(cs)MBMCoordinateBounds","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"area"},{"kind":"text","text":" "},{"kind":"identifier","text":"wrappedCoordinates:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"wrappedCoordinates"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The area to be checked against the bounds."}],"type":"paragraph"}],"name":"area"},{"content":[{"inlineContent":[{"text":"Whether to wrap the coordinate or not.","type":"text"}],"type":"paragraph"}],"name":"wrappedCoordinates"}]}},{"path":"\/primaryContentSections\/2","op":"replace","value":{"content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"inlineContent":[{"type":"codeVoice","code":"true"},{"type":"text","text":" if the bounds contains "},{"type":"codeVoice","code":"area"},{"type":"text","text":", "},{"type":"codeVoice","code":"false"},{"type":"text","text":" otherwise."}],"type":"paragraph"}],"kind":"content"}},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds\/title","value":"MBMCoordinateBounds","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds\/fragments","value":[{"text":"MBMCoordinateBounds","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds\/navigatorTitle","value":[{"kind":"identifier","text":"MBMCoordinateBounds"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds~1contains(forArea:wrappedCoordinates:)\/title","value":"containsForArea:wrappedCoordinates:","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds~1contains(forArea:wrappedCoordinates:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"containsForArea:wrappedCoordinates:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}