{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType\/rangeError"},"kind":"symbol","sections":[],"abstract":[{"text":"Range request failed.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/httprequesterrortype\/rangeerror"]},{"paths":["\/documentation\/mapboxcommon\/httprequesterrortype\/rangeerror"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"rangeError","kind":"identifier"}],"navigatorTitle":[{"text":"MBXHttpRequestErrorTypeRangeError","kind":"identifier"}],"roleHeading":"Case","role":"symbol","symbolKind":"case","title":"HttpRequestErrorType.rangeError","externalID":"c:@E@MBXHttpRequestErrorType@MBXHttpRequestErrorTypeRangeError","modules":[{"name":"MapboxCommon"}]},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rangeError"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","kind":"article","abstract":[],"title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestErrorType/rangeError":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType\/rangeError","kind":"symbol","url":"\/documentation\/mapboxcommon\/httprequesterrortype\/rangeerror","navigatorTitle":[{"kind":"identifier","text":"MBXHttpRequestErrorTypeRangeError"}],"abstract":[{"text":"Range request failed.","type":"text"}],"type":"topic","role":"symbol","title":"HttpRequestErrorType.rangeError","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rangeError","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","title":"MapboxCommon","url":"\/documentation\/mapboxcommon","role":"collection","kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestErrorType":{"kind":"symbol","role":"symbol","url":"\/documentation\/mapboxcommon\/httprequesterrortype","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType","abstract":[{"text":"Enum which describes possible error types which could happen during HTTP request\/download calls.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HttpRequestErrorType"}],"navigatorTitle":[{"kind":"identifier","text":"HttpRequestErrorType"}],"type":"topic","title":"HttpRequestErrorType"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"MBXHttpRequestErrorTypeRangeError","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MBXHttpRequestErrorTypeRangeError"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"MBXHttpRequestErrorTypeRangeError","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestErrorType~1rangeError\/title","value":"MBXHttpRequestErrorTypeRangeError","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestErrorType~1rangeError\/fragments","value":[{"kind":"identifier","text":"MBXHttpRequestErrorTypeRangeError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestErrorType\/title","value":"MBXHttpRequestErrorType"},{"value":[{"text":"MBXHttpRequestErrorType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestErrorType\/fragments"},{"value":[{"kind":"identifier","text":"MBXHttpRequestErrorType"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestErrorType\/navigatorTitle","op":"replace"}]}]}