{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/httprequesterrortype\/requestcancelled"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/httprequesterrortype\/requestcancelled"]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType\/requestCancelled","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Request was cancelled by the user."}],"metadata":{"role":"symbol","roleHeading":"Case","title":"HttpRequestErrorType.requestCancelled","modules":[{"name":"MapboxCommon"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"requestCancelled","kind":"identifier"}],"externalID":"c:@E@MBXHttpRequestErrorType@MBXHttpRequestErrorTypeRequestCancelled","navigatorTitle":[{"text":"MBXHttpRequestErrorTypeRequestCancelled","kind":"identifier"}],"symbolKind":"case"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestCancelled","kind":"identifier"}]}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","url":"\/documentation\/mapboxcommon","kind":"symbol","abstract":[],"title":"MapboxCommon","role":"collection","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","role":"collection","abstract":[],"type":"topic","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestErrorType/requestCancelled":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType\/requestCancelled","url":"\/documentation\/mapboxcommon\/httprequesterrortype\/requestcancelled","kind":"symbol","role":"symbol","title":"HttpRequestErrorType.requestCancelled","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestCancelled","kind":"identifier"}],"abstract":[{"text":"Request was cancelled by the user.","type":"text"}],"navigatorTitle":[{"text":"MBXHttpRequestErrorTypeRequestCancelled","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestErrorType":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"HttpRequestErrorType"}],"url":"\/documentation\/mapboxcommon\/httprequesterrortype","abstract":[{"type":"text","text":"Enum which describes possible error types which could happen during HTTP request\/download calls."}],"role":"symbol","title":"HttpRequestErrorType","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"HttpRequestErrorType"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"MBXHttpRequestErrorTypeRequestCancelled","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"MBXHttpRequestErrorTypeRequestCancelled","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"MBXHttpRequestErrorTypeRequestCancelled"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"MBXHttpRequestErrorTypeRequestCancelled","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestErrorType~1requestCancelled\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestErrorType~1requestCancelled\/fragments","value":[{"kind":"identifier","text":"MBXHttpRequestErrorTypeRequestCancelled"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestErrorType\/title","value":"MBXHttpRequestErrorType"},{"value":[{"text":"MBXHttpRequestErrorType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestErrorType\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestErrorType\/navigatorTitle","value":[{"text":"MBXHttpRequestErrorType","kind":"identifier"}],"op":"replace"}]}]}