{"kind":"symbol","sections":[],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"source","kind":"identifier"},{"kind":"text","text":": "},{"text":"RequestDataSourceType","preciseIdentifier":"c:@E@MBMRequestDataSourceType","kind":"typeIdentifier"}],"symbolKind":"property","role":"symbol","title":"source","roleHeading":"Instance Property","navigatorTitle":[{"text":"source","kind":"identifier"}],"externalID":"c:objc(cs)MBMResourceRequest(py)source","modules":[{"name":"MapboxMaps"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequest\/source"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequest"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"source"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestDataSourceType","preciseIdentifier":"c:@E@MBMRequestDataSourceType","kind":"typeIdentifier","text":"RequestDataSourceType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/resourcerequest\/source"]},{"paths":["\/documentation\/mapboxmaps\/resourcerequest\/source"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"The type of data source from which the resource is requested."}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestDataSourceType":{"type":"topic","navigatorTitle":[{"text":"RequestDataSourceType","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestDataSourceType","role":"symbol","title":"RequestDataSourceType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"RequestDataSourceType"}],"abstract":[{"text":"The enumeration defines the type of data source.","type":"text"}],"url":"\/documentation\/mapboxmaps\/requestdatasourcetype"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResourceRequest/source":{"kind":"symbol","title":"source","role":"symbol","abstract":[{"type":"text","text":"The type of data source from which the resource is requested."}],"url":"\/documentation\/mapboxmaps\/resourcerequest\/source","type":"topic","navigatorTitle":[{"kind":"identifier","text":"source"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequest\/source","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"source","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@MBMRequestDataSourceType","kind":"typeIdentifier","text":"RequestDataSourceType"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","abstract":[],"type":"topic","kind":"article","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResourceRequest":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ResourceRequest"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequest","navigatorTitle":[{"text":"ResourceRequest","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxmaps\/resourcerequest","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The "},{"code":"ResourceRequest","type":"codeVoice"},{"type":"text","text":" event allows the application to observe resource requests made by a "},{"code":"map","type":"codeVoice"},{"type":"text","text":" or "},{"code":"map snapshotter","type":"codeVoice"},{"text":" object.","type":"text"}],"title":"ResourceRequest"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","type":"topic","url":"\/documentation\/mapboxmaps\/events","kind":"article","role":"collectionGroup","abstract":[{"text":"The simplified diagram of the events emitted by the map is displayed below.","type":"text"}],"title":"Map events"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"role":"collection","url":"\/documentation\/mapboxmaps","title":"MapboxMaps","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"source","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"source"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestDataSourceType","preciseIdentifier":"c:@E@MBMRequestDataSourceType","kind":"typeIdentifier","text":"MBMRequestDataSourceType"},{"kind":"text","text":" "},{"text":"source","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"op":"replace","value":"MBMRequestDataSourceType","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestDataSourceType\/title"},{"value":[{"text":"MBMRequestDataSourceType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestDataSourceType\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestDataSourceType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMRequestDataSourceType"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequest~1source\/title","value":"source","op":"replace"},{"value":[{"kind":"identifier","text":"source"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequest~1source\/fragments","op":"replace"},{"value":"MBMResourceRequest","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequest\/title","op":"replace"},{"value":[{"text":"MBMResourceRequest","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequest\/fragments"},{"value":[{"text":"MBMResourceRequest","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequest\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}