{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/mapdebugoptions\/light"]},{"paths":["\/documentation\/mapboxmaps\/mapdebugoptions\/light"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"abstract":[{"text":"Each tile shows its local lighting conditions in the upper-left corner. (If ","type":"text"},{"type":"codeVoice","code":"lights"},{"text":" properties are used, otherwise they show zero.)","type":"text"}],"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBMMapDebugOptionsLight"}],"modules":[{"name":"MapboxMaps"}],"symbolKind":"case","externalID":"c:@E@MBMMapDebugOptions@MBMMapDebugOptionsLight","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"light"}],"title":"MapDebugOptions.light"},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/light","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"light","kind":"identifier"}]}],"kind":"declarations"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapDebugOptions/light":{"navigatorTitle":[{"kind":"identifier","text":"MBMMapDebugOptionsLight"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions\/light","type":"topic","abstract":[{"text":"Each tile shows its local lighting conditions in the upper-left corner. (If ","type":"text"},{"code":"lights","type":"codeVoice"},{"text":" properties are used, otherwise they show zero.)","type":"text"}],"title":"MapDebugOptions.light","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"light"}],"url":"\/documentation\/mapboxmaps\/mapdebugoptions\/light","kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Performance":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","abstract":[],"type":"topic","kind":"article","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/performance","title":"Performance and investigations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","title":"MapboxMaps","role":"collection","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapDebugOptions":{"title":"MapDebugOptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MapDebugOptions","kind":"identifier"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"MapDebugOptions","kind":"identifier"}],"abstract":[{"type":"text","text":"Options for enabling debugging features in a map."}],"url":"\/documentation\/mapboxmaps\/mapdebugoptions","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"kind":"article","role":"collection","url":"\/documentation\/overview","title":"MapboxMaps Documentation","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"MBMMapDebugOptionsLight","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"MBMMapDebugOptionsLight","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"MBMMapDebugOptionsLight"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions~1light\/title","op":"replace","value":"MBMMapDebugOptionsLight"},{"value":[{"kind":"identifier","text":"MBMMapDebugOptionsLight"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions~1light\/fragments","op":"replace"},{"op":"replace","value":"MBMMapDebugOptions","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions\/title"},{"value":[{"kind":"identifier","text":"MBMMapDebugOptions"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions\/navigatorTitle","value":[{"kind":"identifier","text":"MBMMapDebugOptions"}]}]}]}