{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestOrResponse"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestOrResponse\/getHttpResponse()"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/httprequestorresponse\/gethttpresponse()"]},{"paths":["\/documentation\/mapboxcommon\/httprequestorresponse\/gethttpresponse()"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Method","externalID":"c:objc(cs)MBXHttpRequestOrResponse(im)getHttpResponse","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getHttpResponse","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"HttpResponse","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXHttpResponse"}],"role":"symbol","symbolKind":"method","navigatorTitle":[{"text":"getHttpResponse","kind":"identifier"}],"title":"getHttpResponse()","modules":[{"name":"MapboxCommon"}]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"getHttpResponse","kind":"identifier"},{"text":"() -> ","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpResponse","text":"HttpResponse","preciseIdentifier":"c:objc(cs)MBXHttpResponse","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestOrResponse/getHttpResponse()":{"abstract":[],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"getHttpResponse","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getHttpResponse"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBXHttpResponse","text":"HttpResponse","kind":"typeIdentifier"}],"url":"\/documentation\/mapboxcommon\/httprequestorresponse\/gethttpresponse()","title":"getHttpResponse()","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestOrResponse\/getHttpResponse()"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"title":"MapboxCommon","kind":"symbol","url":"\/documentation\/mapboxcommon","abstract":[],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpResponse":{"abstract":[{"type":"text","text":"Record which is used to report HTTP response to the caller."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpResponse","type":"topic","url":"\/documentation\/mapboxcommon\/httpresponse","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HttpResponse","kind":"identifier"}],"kind":"symbol","title":"HttpResponse","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HttpResponse"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestOrResponse":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestOrResponse","kind":"symbol","navigatorTitle":[{"text":"HttpRequestOrResponse","kind":"identifier"}],"type":"topic","title":"HttpRequestOrResponse","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"HttpRequestOrResponse","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/httprequestorresponse","abstract":[{"type":"text","text":"Contains either an HttpRequest or an HttpResponse."}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article","title":"MapboxMaps Documentation","url":"\/documentation\/overview","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"getHttpResponse","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"getHttpResponse","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBXHttpResponse","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpResponse","text":"MBXHttpResponse"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"getHttpResponse"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"getHttpResponse","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestOrResponse~1getHttpResponse()\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestOrResponse~1getHttpResponse()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getHttpResponse"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpResponse\/title","op":"replace","value":"MBXHttpResponse"},{"value":[{"text":"MBXHttpResponse","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpResponse\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpResponse\/navigatorTitle","op":"replace","value":[{"text":"MBXHttpResponse","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestOrResponse\/title","value":"MBXHttpRequestOrResponse"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestOrResponse\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXHttpRequestOrResponse"}]},{"value":[{"text":"MBXHttpRequestOrResponse","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestOrResponse\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}