{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomGeometrySourceOptions"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/mapboxmaps\/customgeometrysourceoptions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/customgeometrysourceoptions"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH"],"type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources"]]},"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomGeometrySourceOptions"}],"modules":[{"name":"MapboxMaps"}],"title":"CustomGeometrySourceOptions","navigatorTitle":[{"kind":"identifier","text":"CustomGeometrySourceOptions"}],"symbolKind":"class","externalID":"c:objc(cs)MBMCustomGeometrySourceOptions","roleHeading":"Class"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"abstract":[{"text":"Options for custom geometry source.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions"},"topicSections":[{"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions\/init(fetchTileFunction:cancelTileFunction:minZoom:maxZoom:tileOptions:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions\/init(fetchTileFunction:cancelTileFunction:tileOptions:)"],"generated":true},{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions\/cancelTileFunction","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions\/fetchTileFunction","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions\/maxZoom","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions\/minZoom","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions\/tileOptions"],"generated":true}],"kind":"symbol","seeAlsoSections":[{"anchor":"Sources","title":"Sources","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Source","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceInfo","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSourceData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterArraySource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/VectorSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PromoteId","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Scheme","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Encoding","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatusChangedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatus","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileFunctionCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetSize"],"generated":true}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomGeometrySourceOptions/tileOptions":{"title":"tileOptions","role":"symbol","navigatorTitle":[{"text":"tileOptions","kind":"identifier"}],"abstract":[{"type":"text","text":"Tile options."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions\/tileOptions","kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/customgeometrysourceoptions\/tileoptions","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tileOptions","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMTileOptions","text":"TileOptions","kind":"typeIdentifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomGeometrySourceOptions/init(fetchTileFunction:cancelTileFunction:tileOptions:)":{"url":"\/documentation\/mapboxmaps\/customgeometrysourceoptions\/init(fetchtilefunction:canceltilefunction:tileoptions:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions\/init(fetchTileFunction:cancelTileFunction:tileOptions:)","title":"init(fetchTileFunction:cancelTileFunction:tileOptions:)","role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFetchTileFunction:cancelTileFunction:tileOptions:"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fetchTileFunction","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TileFunctionCallback","preciseIdentifier":"c:MBMTileFunctionCallback.h@T@MBMTileFunctionCallback","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"cancelTileFunction","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TileFunctionCallback","preciseIdentifier":"c:MBMTileFunctionCallback.h@T@MBMTileFunctionCallback","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"tileOptions","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TileOptions","preciseIdentifier":"c:objc(cs)MBMTileOptions","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GeoJSONSource":{"navigatorTitle":[{"kind":"identifier","text":"GeoJSONSource"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/geojsonsource","title":"GeoJSONSource","type":"topic","abstract":[{"type":"text","text":"A GeoJSON data source."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"GeoJSONSource"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSource","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","title":"MapboxMaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"url":"\/documentation\/mapboxmaps","kind":"symbol","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/VectorSource":{"type":"topic","url":"\/documentation\/mapboxmaps\/vectorsource","kind":"symbol","role":"symbol","title":"VectorSource","abstract":[{"text":"A vector tile source.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VectorSource","kind":"identifier"}],"navigatorTitle":[{"text":"VectorSource","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/VectorSource"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterArraySource":{"abstract":[{"type":"text","text":"A raster array source"}],"role":"symbol","kind":"symbol","tags":[{"type":"spi","text":"SPI"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RasterArraySource"}],"url":"\/documentation\/mapboxmaps\/rasterarraysource","navigatorTitle":[{"kind":"identifier","text":"RasterArraySource"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterArraySource","type":"topic","title":"RasterArraySource"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Encoding":{"kind":"symbol","navigatorTitle":[{"text":"Encoding","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Encoding","type":"topic","title":"Encoding","abstract":[{"text":"The encoding used by this source. Mapbox Terrain RGB is used by default","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Encoding","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/encoding"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Sources":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources","abstract":[],"role":"collectionGroup","type":"topic","kind":"article","title":"Sources","url":"\/documentation\/mapboxmaps\/sources"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceType":{"title":"SourceType","url":"\/documentation\/mapboxmaps\/sourcetype","kind":"symbol","abstract":[{"type":"text","text":"Struct of supported Source Types"},{"type":"text","text":" "},{"type":"text","text":"Docs : https:\/\/docs.mapbox.com\/mapbox-gl-js\/style-spec\/sources\/"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceType","navigatorTitle":[{"text":"SourceType","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceType"}]},"doc://com.mapbox.MapboxMaps/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceOptions":{"role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomRasterSourceOptions"}],"abstract":[{"type":"text","text":"Options for custom raster source."}],"navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceOptions"}],"title":"CustomRasterSourceOptions","url":"\/documentation\/mapboxmaps\/customrastersourceoptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileRenderer":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomRasterSourceTileRenderer","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/customrastersourcetilerenderer","role":"symbol","title":"CustomRasterSourceTileRenderer","navigatorTitle":[{"text":"CustomRasterSourceTileRenderer","kind":"identifier"}],"abstract":[{"text":"Interface for the direct rendering into the custom raster tiles.","type":"text"}]},"doc://com.mapbox.MapboxMaps/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileData":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceTileData"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomRasterSourceTileData"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileData","abstract":[{"type":"text","text":"Data for a specific CustomRasterSource tile."}],"kind":"symbol","type":"topic","title":"CustomRasterSourceTileData","url":"\/documentation\/mapboxmaps\/customrastersourcetiledata"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomGeometrySourceOptions/fetchTileFunction":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions\/fetchTileFunction","abstract":[{"type":"text","text":"The callback that provides data for a tile."}],"url":"\/documentation\/mapboxmaps\/customgeometrysourceoptions\/fetchtilefunction","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchTileFunction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:MBMTileFunctionCallback.h@T@MBMTileFunctionCallback","text":"TileFunctionCallback"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"fetchTileFunction"}],"title":"fetchTileFunction"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSource":{"type":"topic","url":"\/documentation\/mapboxmaps\/customrastersource","kind":"symbol","role":"symbol","tags":[{"type":"spi","text":"SPI"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomRasterSource","kind":"identifier"}],"title":"CustomRasterSource","abstract":[{"text":"Describes a Custom Raster Source to be used in the style.","type":"text"}],"navigatorTitle":[{"text":"CustomRasterSource","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSource"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ImageSource":{"url":"\/documentation\/mapboxmaps\/imagesource","role":"symbol","kind":"symbol","type":"topic","title":"ImageSource","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageSource","abstract":[{"text":"An image data source.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageSource","kind":"identifier"}],"navigatorTitle":[{"text":"ImageSource","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceClientType":{"abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomRasterSourceClientType","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType","title":"CustomRasterSourceClientType","url":"\/documentation\/mapboxmaps\/customrastersourceclienttype","navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceClientType"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceInfo":{"kind":"symbol","title":"SourceInfo","url":"\/documentation\/mapboxmaps\/sourceinfo","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceInfo","navigatorTitle":[{"kind":"identifier","text":"SourceInfo"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceInfo"}],"abstract":[{"text":"Information about a Source","type":"text"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomGeometrySourceOptions/init(fetchTileFunction:cancelTileFunction:minZoom:maxZoom:tileOptions:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fetchTileFunction","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TileFunctionCallback","preciseIdentifier":"c:MBMTileFunctionCallback.h@T@MBMTileFunctionCallback","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"cancelTileFunction","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TileFunctionCallback","preciseIdentifier":"c:MBMTileFunctionCallback.h@T@MBMTileFunctionCallback","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"minZoom","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt8","preciseIdentifier":"s:s5UInt8V","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"maxZoom","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt8","preciseIdentifier":"s:s5UInt8V","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"tileOptions","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TileOptions","preciseIdentifier":"c:objc(cs)MBMTileOptions","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/mapboxmaps\/customgeometrysourceoptions\/init(fetchtilefunction:canceltilefunction:minzoom:maxzoom:tileoptions:)","navigatorTitle":[{"text":"initWithFetchTileFunction:cancelTileFunction:minZoom:maxZoom:tileOptions:","kind":"identifier"}],"title":"init(fetchTileFunction:cancelTileFunction:minZoom:maxZoom:tileOptions:)","abstract":[],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions\/init(fetchTileFunction:cancelTileFunction:minZoom:maxZoom:tileOptions:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Scheme":{"title":"Scheme","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/scheme","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Scheme","kind":"identifier"}],"abstract":[{"type":"text","text":"Influences the y direction of the tile coordinates. The global-mercator (aka Spherical Mercator) profile is assumed."}],"navigatorTitle":[{"kind":"identifier","text":"Scheme"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Scheme"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomGeometrySourceOptions/cancelTileFunction":{"navigatorTitle":[{"kind":"identifier","text":"cancelTileFunction"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions\/cancelTileFunction","url":"\/documentation\/mapboxmaps\/customgeometrysourceoptions\/canceltilefunction","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelTileFunction"},{"kind":"text","text":": "},{"preciseIdentifier":"c:MBMTileFunctionCallback.h@T@MBMTileFunctionCallback","kind":"typeIdentifier","text":"TileFunctionCallback"}],"abstract":[{"text":"The callback that cancels a tile.","type":"text"}],"title":"cancelTileFunction","role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Source":{"url":"\/documentation\/mapboxmaps\/source","role":"symbol","kind":"symbol","type":"topic","title":"Source","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Source","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Source"}],"navigatorTitle":[{"kind":"identifier","text":"Source"}]},"doc://com.mapbox.MapboxMaps/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP"},"doc://com.mapbox.MapboxMaps/s7CVarArgP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterDemSource":{"title":"RasterDemSource","kind":"symbol","url":"\/documentation\/mapboxmaps\/rasterdemsource","type":"topic","abstract":[{"type":"text","text":"A RGB-encoded raster DEM source"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RasterDemSource","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource","navigatorTitle":[{"text":"RasterDemSource","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterSource":{"type":"topic","abstract":[{"text":"A raster tile source.","type":"text"}],"kind":"symbol","title":"RasterSource","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"RasterSource"}],"navigatorTitle":[{"kind":"identifier","text":"RasterSource"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/rastersource","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterSource"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudgetSize":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileCacheBudgetSize","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/tilecachebudgetsize","role":"symbol","abstract":[{"type":"text","text":"Defines a TileCacheBudgetSize, which can be set as either a megabyte or tile count limit."},{"type":"text","text":" "},{"type":"text","text":"Whenever tile cache goes over the defined limit"},{"type":"text","text":" "},{"type":"text","text":"the least recently used tile will be evicted from the in-memory cache"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetSize","kind":"symbol","type":"topic","navigatorTitle":[{"text":"TileCacheBudgetSize","kind":"identifier"}],"title":"TileCacheBudgetSize"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileStatusChangedCallback":{"title":"CustomRasterSourceTileStatusChangedCallback","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatusChangedCallback","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomRasterSourceTileStatusChangedCallback","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"CustomRasterSourceTileStatusChangedCallback","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/customrastersourcetilestatuschangedcallback","abstract":[{"type":"text","text":"Callback for changing a CustomRasterSource tile status."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GeoJSONSourceData":{"abstract":[{"type":"text","text":"Captures potential values of the "},{"type":"codeVoice","code":"data"},{"type":"text","text":" property of a GeoJSONSource."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GeoJSONSourceData"}],"url":"\/documentation\/mapboxmaps\/geojsonsourcedata","type":"topic","title":"GeoJSONSourceData","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSourceData","navigatorTitle":[{"kind":"identifier","text":"GeoJSONSourceData"}]},"doc://com.mapbox.MapboxMaps/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomGeometrySourceOptions":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomGeometrySourceOptions","kind":"identifier"}],"navigatorTitle":[{"text":"CustomGeometrySourceOptions","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/customgeometrysourceoptions","title":"CustomGeometrySourceOptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions","kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Options for custom geometry source."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileStatus":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomRasterSourceTileStatus","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatus","kind":"symbol","type":"topic","role":"symbol","title":"CustomRasterSourceTileStatus","abstract":[{"text":"CustomRasterSource tile status.","type":"text"}],"navigatorTitle":[{"text":"CustomRasterSourceTileStatus","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/customrastersourcetilestatus"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PromoteId":{"url":"\/documentation\/mapboxmaps\/promoteid","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PromoteId","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"PromoteId","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PromoteId","title":"PromoteId","abstract":[],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceClient":{"navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceClient"}],"abstract":[],"url":"\/documentation\/mapboxmaps\/customrastersourceclient","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomRasterSourceClient"}],"type":"topic","role":"symbol","title":"CustomRasterSourceClient"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileFunctionCallback":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileFunctionCallback"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileFunctionCallback","kind":"symbol","type":"topic","role":"symbol","title":"TileFunctionCallback","abstract":[{"text":"Callback to do various operations for tile.","type":"text"},{"text":" ","type":"text"},{"text":"For example, fetching a tile or cancelling a tile request.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"TileFunctionCallback"}],"url":"\/documentation\/mapboxmaps\/tilefunctioncallback"},"doc://com.mapbox.MapboxMaps/SQ":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomGeometrySourceOptions/minZoom":{"title":"minZoom","url":"\/documentation\/mapboxmaps\/customgeometrysourceoptions\/minzoom","abstract":[{"text":"A minimum zoom level, at which to create vector tiles.","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions\/minZoom","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minZoom","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt8","kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V"}],"type":"topic","navigatorTitle":[{"text":"minZoom","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"title":"MapboxMaps Documentation","type":"topic","kind":"article","role":"collection","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomGeometrySourceOptions/maxZoom":{"kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/customgeometrysourceoptions\/maxzoom","navigatorTitle":[{"text":"maxZoom","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions\/maxZoom","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxZoom","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt8","preciseIdentifier":"s:s5UInt8V","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"A maximum zoom level, at which to create vector tiles."}],"title":"maxZoom"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomGeometrySource":{"type":"topic","title":"CustomGeometrySource","navigatorTitle":[{"kind":"identifier","text":"CustomGeometrySource"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySource","abstract":[{"text":"Describes a Custom Geometry Source to be used in the style","type":"text"}],"url":"\/documentation\/mapboxmaps\/customgeometrysource","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomGeometrySource"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"MBMCustomGeometrySourceOptions","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MBMCustomGeometrySourceOptions"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"MBMCustomGeometrySourceOptions","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions\/cancelTileFunction","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions\/fetchTileFunction","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions\/maxZoom","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions\/minZoom","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions\/tileOptions"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions\/init(fetchTileFunction:cancelTileFunction:minZoom:maxZoom:tileOptions:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions\/init(fetchTileFunction:cancelTileFunction:tileOptions:)"],"generated":true,"anchor":"Instance-Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"type":"inheritsFrom"}],"op":"replace"},{"path":"\/seeAlsoSections","value":[{"anchor":"Sources","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatusChangedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatus","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileFunctionCallback"],"title":"Sources","generated":true}],"op":"replace"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBMCustomGeometrySourceOptions"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions~1tileOptions\/title","value":"tileOptions","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions~1tileOptions\/fragments","value":[{"kind":"identifier","text":"tileOptions"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions~1init(fetchTileFunction:cancelTileFunction:tileOptions:)\/title","value":"initWithFetchTileFunction:cancelTileFunction:tileOptions:","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions~1init(fetchTileFunction:cancelTileFunction:tileOptions:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithFetchTileFunction:cancelTileFunction:tileOptions:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/title","value":"MBMCustomRasterSourceOptions","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/fragments","value":[{"text":"MBMCustomRasterSourceOptions","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/navigatorTitle","value":[{"text":"MBMCustomRasterSourceOptions","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer\/title","value":"MBMCustomRasterSourceTileRenderer","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer\/fragments","value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileRenderer"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer\/navigatorTitle","value":[{"text":"MBMCustomRasterSourceTileRenderer","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileData\/title","value":"MBMCustomRasterSourceTileData","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileData\/fragments","op":"replace","value":[{"text":"MBMCustomRasterSourceTileData","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileData\/navigatorTitle","op":"replace","value":[{"text":"MBMCustomRasterSourceTileData","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions~1fetchTileFunction\/title","op":"replace","value":"fetchTileFunction"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions~1fetchTileFunction\/fragments","op":"replace","value":[{"text":"fetchTileFunction","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType\/title","op":"replace","value":"MBMCustomRasterSourceClientType"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType\/fragments","op":"replace","value":[{"text":"MBMCustomRasterSourceClientType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMCustomRasterSourceClientType"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions~1init(fetchTileFunction:cancelTileFunction:minZoom:maxZoom:tileOptions:)\/title","op":"replace","value":"initWithFetchTileFunction:cancelTileFunction:minZoom:maxZoom:tileOptions:"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions~1init(fetchTileFunction:cancelTileFunction:minZoom:maxZoom:tileOptions:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFetchTileFunction:cancelTileFunction:minZoom:maxZoom:tileOptions:"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions~1cancelTileFunction\/title","op":"replace","value":"cancelTileFunction"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions~1cancelTileFunction\/fragments","op":"replace","value":[{"text":"cancelTileFunction","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatusChangedCallback\/title","op":"replace","value":"MBMCustomRasterSourceTileStatusChangedCallback"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatusChangedCallback\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileStatusChangedCallback"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatusChangedCallback\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileStatusChangedCallback"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions\/title","op":"replace","value":"MBMCustomGeometrySourceOptions"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMCustomGeometrySourceOptions"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions\/navigatorTitle","op":"replace","value":[{"text":"MBMCustomGeometrySourceOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatus\/title","op":"replace","value":"MBMCustomRasterSourceTileStatus"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatus\/fragments","op":"replace","value":[{"text":"MBMCustomRasterSourceTileStatus","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatus\/navigatorTitle","op":"replace","value":[{"text":"MBMCustomRasterSourceTileStatus","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient\/title","op":"replace","value":"MBMCustomRasterSourceClient"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMCustomRasterSourceClient"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMCustomRasterSourceClient"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileFunctionCallback\/title","op":"replace","value":"MBMTileFunctionCallback"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileFunctionCallback\/fragments","op":"replace","value":[{"text":"MBMTileFunctionCallback","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileFunctionCallback\/navigatorTitle","op":"replace","value":[{"text":"MBMTileFunctionCallback","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions~1minZoom\/title","op":"replace","value":"minZoom"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions~1minZoom\/fragments","op":"replace","value":[{"kind":"identifier","text":"minZoom"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions~1maxZoom\/title","op":"replace","value":"maxZoom"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions~1maxZoom\/fragments","op":"replace","value":[{"text":"maxZoom","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}