{"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/puck3dconfiguration"]}],"sections":[],"topicSections":[{"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration\/init(model:modelScale:modelRotation:modelOpacity:layerPosition:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration\/init(model:modelScale:modelRotation:modelOpacity:modelCastShadows:modelReceiveShadows:modelScaleMode:modelEmissiveStrength:modelColorUseTheme:layerPosition:)"],"generated":true},{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration\/layerPosition","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration\/model","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration\/modelCastShadows","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration\/modelColorUseTheme","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration\/modelElevationReference","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration\/modelEmissiveStrength","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration\/modelOpacity","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration\/modelReceiveShadows","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration\/modelRotation","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration\/modelScale","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration\/modelScaleMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration\/slot"],"generated":true},{"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration\/Equatable-Implementations"],"generated":true}],"relationshipsSections":[{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"],"type":"conformsTo"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Puck3DConfiguration"}],"languages":["swift"]}],"kind":"declarations"}],"seeAlsoSections":[{"anchor":"Location","title":"Location","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationManager","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck2DConfiguration","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Model","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckBearing","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProviderDelegate","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Coordinate2D","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationExtraKeys","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProviderRequest","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceFactory","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/DeviceLocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Heading","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckRenderingData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/IntervalSettings"],"generated":true}],"metadata":{"externalID":"s:10MapboxMaps19Puck3DConfigurationV","navigatorTitle":[{"kind":"identifier","text":"Puck3DConfiguration"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Puck3DConfiguration"}],"roleHeading":"Structure","modules":[{"name":"MapboxMaps"}],"role":"symbol","title":"Puck3DConfiguration","symbolKind":"struct"},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PermissionStatus":{"url":"\/documentation\/mapboxcommon\/permissionstatus","kind":"symbol","abstract":[{"text":"Location permissions granted by user to the app.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PermissionStatus","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"PermissionStatus","kind":"identifier"}],"title":"PermissionStatus","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Puck3DConfiguration/Equatable-Implementations":{"role":"collectionGroup","kind":"article","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration\/Equatable-Implementations","title":"Equatable Implementations","url":"\/documentation\/mapboxmaps\/puck3dconfiguration\/equatable-implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Puck3DConfiguration/model":{"type":"topic","title":"model","role":"symbol","abstract":[{"text":"The model to use as the locaiton puck","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration\/model","url":"\/documentation\/mapboxmaps\/puck3dconfiguration\/model","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"model","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps5ModelV","kind":"typeIdentifier","text":"Model"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/AccuracyLevel":{"type":"topic","title":"AccuracyLevel","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AccuracyLevel","kind":"identifier"}],"navigatorTitle":[{"text":"AccuracyLevel","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/accuracylevel","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel","abstract":[{"text":"The accuracy of the observed location","type":"text"}],"kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Puck3DConfiguration/layerPosition":{"url":"\/documentation\/mapboxmaps\/puck3dconfiguration\/layerposition","abstract":[{"type":"text","text":"Defines relative position of the puck layer."}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration\/layerPosition","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"layerPosition","kind":"identifier"},{"text":": ","kind":"text"},{"text":"LayerPosition","preciseIdentifier":"s:14MapboxCoreMaps13LayerPositionO","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"layerPosition"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Model":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Model","type":"topic","url":"\/documentation\/mapboxmaps\/model","kind":"symbol","abstract":[{"type":"text","text":"A structure represeting a Model"}],"navigatorTitle":[{"kind":"identifier","text":"Model"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Model"}],"role":"symbol","title":"Model"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Puck3DConfiguration/modelOpacity":{"abstract":[{"text":"The opacity of the model used as the location puck","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration\/modelOpacity","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"modelOpacity","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Value","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps5ValueO"},{"text":"<","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":">?","kind":"text"}],"kind":"symbol","type":"topic","title":"modelOpacity","role":"symbol","url":"\/documentation\/mapboxmaps\/puck3dconfiguration\/modelopacity"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Puck3DConfiguration/slot":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"slot","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps4SlotV","text":"Slot","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration\/slot","abstract":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Slot"},{"type":"text","text":" where to put puck layers."}],"url":"\/documentation\/mapboxmaps\/puck3dconfiguration\/slot","title":"slot"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeadingObserver":{"navigatorTitle":[{"kind":"identifier","text":"HeadingObserver"}],"url":"\/documentation\/mapboxmaps\/headingobserver","title":"HeadingObserver","abstract":[{"type":"text","text":"Listens to "},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingProvider","isActive":true},{"type":"text","text":"’s updates."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeadingObserver"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingObserver"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/AccuracyAuthorization":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization","abstract":[{"type":"text","text":"Accuracy authorization granted by user to the app."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AccuracyAuthorization"}],"navigatorTitle":[{"kind":"identifier","text":"AccuracyAuthorization"}],"kind":"symbol","role":"symbol","title":"AccuracyAuthorization","type":"topic","url":"\/documentation\/mapboxcommon\/accuracyauthorization"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PuckBearing":{"url":"\/documentation\/mapboxmaps\/puckbearing","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckBearing","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PuckBearing"}],"type":"topic","title":"PuckBearing","abstract":[{"text":"Controls how the puck is oriented","type":"text"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PuckBearing"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Puck3DConfiguration/modelRotation":{"url":"\/documentation\/mapboxmaps\/puck3dconfiguration\/modelrotation","type":"topic","title":"modelRotation","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"modelRotation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Value","preciseIdentifier":"s:10MapboxMaps5ValueO"},{"kind":"text","text":"<["},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":"]>?"}],"abstract":[{"type":"text","text":"The rotation of the model in euler angles [lon, lat, z]."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration\/modelRotation"},"doc://com.mapbox.MapboxMaps/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"title":"MapboxMaps Documentation","type":"topic","kind":"article","role":"collection","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Puck3DConfiguration/modelReceiveShadows":{"url":"\/documentation\/mapboxmaps\/puck3dconfiguration\/modelreceiveshadows","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration\/modelReceiveShadows","abstract":[{"type":"text","text":"Enable\/disable shadow receiving for the puck model"}],"tags":[{"type":"spi","text":"SPI"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"modelReceiveShadows"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps5ValueO","text":"Value"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":">?"}],"kind":"symbol","title":"modelReceiveShadows","type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationExtraKeys":{"kind":"symbol","url":"\/documentation\/mapboxcommon\/locationextrakeys","abstract":[{"text":"Keys for additional information (extra) in Location.","type":"text"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationExtraKeys","title":"LocationExtraKeys","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationExtraKeys","kind":"identifier"}],"navigatorTitle":[{"text":"LocationExtraKeys","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeadingProvider":{"kind":"symbol","title":"HeadingProvider","navigatorTitle":[{"text":"HeadingProvider","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingProvider","type":"topic","url":"\/documentation\/mapboxmaps\/headingprovider","abstract":[{"text":"Provides heading data to drive the location puck.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HeadingProvider","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Puck3DConfiguration/modelScale":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"modelScale","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Value","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps5ValueO"},{"text":"<[","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":"]>?","kind":"text"}],"abstract":[{"type":"text","text":"The scale of the model."}],"kind":"symbol","type":"topic","title":"modelScale","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration\/modelScale","url":"\/documentation\/mapboxmaps\/puck3dconfiguration\/modelscale"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/DeviceLocationProvider":{"kind":"symbol","abstract":[{"type":"text","text":"Location provider specialisation that provides real-time locations generated from the device"}],"url":"\/documentation\/mapboxcommon\/devicelocationprovider","role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/DeviceLocationProvider","navigatorTitle":[{"kind":"identifier","text":"DeviceLocationProvider"}],"title":"DeviceLocationProvider","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeviceLocationProvider"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LocationManager":{"url":"\/documentation\/mapboxmaps\/locationmanager","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"An object responsible for managing user location Puck."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationManager","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationManager"}],"title":"LocationManager","navigatorTitle":[{"kind":"identifier","text":"LocationManager"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Location":{"abstract":[{"type":"text","text":"Location information."}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"Location","kind":"identifier"}],"title":"Location","url":"\/documentation\/mapboxcommon\/location","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Location","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Coordinate2D":{"title":"Coordinate2D","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Coordinate2D"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Coordinate2D"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Coordinate2D","url":"\/documentation\/mapboxcommon\/coordinate2d","abstract":[{"text":"Boxed version of CLLocationCoordinate2D","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Location-APIs":{"url":"\/documentation\/mapboxmaps\/location-apis","title":"Location","kind":"article","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","role":"collectionGroup","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationServiceObserver":{"url":"\/documentation\/mapboxcommon\/locationserviceobserver","title":"LocationServiceObserver","kind":"symbol","type":"topic","navigatorTitle":[{"text":"LocationServiceObserver","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver","role":"symbol","abstract":[{"text":"Observers for getting updates from LocationService.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationServiceObserver","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PuckRenderingData":{"title":"PuckRenderingData","role":"symbol","abstract":[{"type":"text","text":"Represents the interpolated data ready to render the user location puck."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckRenderingData","url":"\/documentation\/mapboxmaps\/puckrenderingdata","kind":"symbol","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PuckRenderingData","kind":"identifier"}],"navigatorTitle":[{"text":"PuckRenderingData","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationObserver":{"title":"LocationObserver","abstract":[{"type":"text","text":"Observer for getting updates from a LocationProvider."}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationObserver","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationObserver"}],"navigatorTitle":[{"kind":"identifier","text":"LocationObserver"}],"url":"\/documentation\/mapboxcommon\/locationobserver"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationErrorCode":{"url":"\/documentation\/mapboxcommon\/locationerrorcode","type":"topic","title":"LocationErrorCode","kind":"symbol","abstract":[{"type":"text","text":"Codes of location errors."}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationErrorCode","kind":"identifier"}],"navigatorTitle":[{"text":"LocationErrorCode","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Heading":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Heading"}],"navigatorTitle":[{"kind":"identifier","text":"Heading"}],"abstract":[{"type":"text","text":"The azimuth (orientation) of the user’s device, relative to true or magnetic north."}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Heading","type":"topic","title":"Heading","kind":"symbol","url":"\/documentation\/mapboxmaps\/heading"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationServiceFactory":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceFactory","navigatorTitle":[{"kind":"identifier","text":"LocationServiceFactory"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationServiceFactory"}],"title":"LocationServiceFactory","url":"\/documentation\/mapboxcommon\/locationservicefactory","type":"topic","abstract":[{"type":"text","text":"Location service factory."}],"role":"symbol","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LocationOptions":{"url":"\/documentation\/mapboxmaps\/locationoptions","role":"symbol","kind":"symbol","title":"LocationOptions","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationOptions","kind":"identifier"}],"abstract":[{"type":"text","text":"A struct to configure a "},{"type":"codeVoice","code":"LocationManager"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationOptions","navigatorTitle":[{"text":"LocationOptions","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PuckType":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckType","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PuckType"}],"title":"PuckType","url":"\/documentation\/mapboxmaps\/pucktype","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PuckType"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Represents the different types of pucks"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Puck3DConfiguration/modelEmissiveStrength":{"type":"topic","url":"\/documentation\/mapboxmaps\/puck3dconfiguration\/modelemissivestrength","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration\/modelEmissiveStrength","role":"symbol","title":"modelEmissiveStrength","abstract":[{"text":"Strength of the emission.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"modelEmissiveStrength"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps5ValueO","text":"Value"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":">?"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Puck3DConfiguration/modelCastShadows":{"abstract":[{"text":"Enable\/disable shadow casting for the puck model","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration\/modelCastShadows","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"modelCastShadows","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Value","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps5ValueO"},{"text":"<","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":">?","kind":"text"}],"tags":[{"text":"SPI","type":"spi"}],"type":"topic","kind":"symbol","role":"symbol","title":"modelCastShadows","url":"\/documentation\/mapboxmaps\/puck3dconfiguration\/modelcastshadows"},"doc://com.mapbox.MapboxMaps/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Puck3DConfiguration/modelScaleMode":{"tags":[{"type":"spi","text":"SPI"}],"url":"\/documentation\/mapboxmaps\/puck3dconfiguration\/modelscalemode","title":"modelScaleMode","role":"symbol","abstract":[{"text":"Defines scaling mode. Only applies to location-indicator type layers. Default to ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelScaleMode\/viewport","type":"reference","isActive":true},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"modelScaleMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps5ValueO","text":"Value"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps14ModelScaleModeV","text":"ModelScaleMode"},{"kind":"text","text":">?"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration\/modelScaleMode","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/IntervalSettings":{"url":"\/documentation\/mapboxcommon\/intervalsettings","type":"topic","title":"IntervalSettings","kind":"symbol","navigatorTitle":[{"text":"IntervalSettings","kind":"identifier"}],"abstract":[{"text":"The interval for active location updates","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/IntervalSettings","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IntervalSettings","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Puck3DConfiguration/init(model:modelScale:modelRotation:modelOpacity:modelCastShadows:modelReceiveShadows:modelScaleMode:modelEmissiveStrength:modelColorUseTheme:layerPosition:)":{"title":"init(model:modelScale:modelRotation:modelOpacity:modelCastShadows:modelReceiveShadows:modelScaleMode:modelEmissiveStrength:modelColorUseTheme:layerPosition:)","abstract":[{"text":"Initialize a ","type":"text"},{"code":"Puck3DConfiguration","type":"codeVoice"},{"text":" with a model, scale, rotation and an parameter to control shadow casting.","type":"text"}],"type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"model"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Model","preciseIdentifier":"s:10MapboxMaps5ModelV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"modelScale"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Value","preciseIdentifier":"s:10MapboxMaps5ValueO"},{"kind":"text","text":"<["},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":"]>?, "},{"kind":"externalParam","text":"modelRotation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Value","preciseIdentifier":"s:10MapboxMaps5ValueO"},{"kind":"text","text":"<["},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":"]>?, "},{"kind":"externalParam","text":"modelOpacity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Value","preciseIdentifier":"s:10MapboxMaps5ValueO"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":">?, "},{"kind":"externalParam","text":"modelCastShadows"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Value","preciseIdentifier":"s:10MapboxMaps5ValueO"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":">?, "},{"kind":"externalParam","text":"modelReceiveShadows"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Value","preciseIdentifier":"s:10MapboxMaps5ValueO"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":">?, "},{"kind":"externalParam","text":"modelScaleMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Value","preciseIdentifier":"s:10MapboxMaps5ValueO"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"ModelScaleMode","preciseIdentifier":"s:10MapboxMaps14ModelScaleModeV"},{"kind":"text","text":">?, "},{"kind":"externalParam","text":"modelEmissiveStrength"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Value","preciseIdentifier":"s:10MapboxMaps5ValueO"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"modelColorUseTheme"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Value","preciseIdentifier":"s:10MapboxMaps5ValueO"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"ColorUseTheme","preciseIdentifier":"s:10MapboxMaps13ColorUseThemeV"},{"kind":"text","text":">?, "},{"kind":"externalParam","text":"layerPosition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LayerPosition","preciseIdentifier":"s:14MapboxCoreMaps13LayerPositionO"},{"kind":"text","text":"?)"}],"tags":[{"text":"SPI","type":"spi"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration\/init(model:modelScale:modelRotation:modelOpacity:modelCastShadows:modelReceiveShadows:modelScaleMode:modelEmissiveStrength:modelColorUseTheme:layerPosition:)","role":"symbol","url":"\/documentation\/mapboxmaps\/puck3dconfiguration\/init(model:modelscale:modelrotation:modelopacity:modelcastshadows:modelreceiveshadows:modelscalemode:modelemissivestrength:modelcolorusetheme:layerposition:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationProviderRequest":{"url":"\/documentation\/mapboxcommon\/locationproviderrequest","kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProviderRequest","abstract":[{"text":"Data model that contains parameters for location requests.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationProviderRequest","kind":"identifier"}],"title":"LocationProviderRequest","navigatorTitle":[{"text":"LocationProviderRequest","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Puck3DConfiguration/init(model:modelScale:modelRotation:modelOpacity:layerPosition:)":{"kind":"symbol","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"model","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Model","preciseIdentifier":"s:10MapboxMaps5ModelV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"modelScale","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Value","preciseIdentifier":"s:10MapboxMaps5ValueO","kind":"typeIdentifier"},{"text":"<[","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":"]>?, ","kind":"text"},{"text":"modelRotation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Value","preciseIdentifier":"s:10MapboxMaps5ValueO","kind":"typeIdentifier"},{"text":"<[","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":"]>?, ","kind":"text"},{"text":"modelOpacity","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Value","preciseIdentifier":"s:10MapboxMaps5ValueO","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":">?, ","kind":"text"},{"text":"layerPosition","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"LayerPosition","preciseIdentifier":"s:14MapboxCoreMaps13LayerPositionO","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"abstract":[{"type":"text","text":"Initialize a "},{"type":"codeVoice","code":"Puck3DConfiguration"},{"type":"text","text":" with a model, scale and rotation."}],"url":"\/documentation\/mapboxmaps\/puck3dconfiguration\/init(model:modelscale:modelrotation:modelopacity:layerposition:)","type":"topic","title":"init(model:modelScale:modelRotation:modelOpacity:layerPosition:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration\/init(model:modelScale:modelRotation:modelOpacity:layerPosition:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Slot":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"Slot","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Slot","title":"Slot","url":"\/documentation\/mapboxmaps\/slot","abstract":[{"type":"text","text":"A pre-specified location in the style where layer will be added to"},{"type":"text","text":" "},{"type":"text","text":"(such as on top of existing land layers, but below all labels)."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Slot","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","title":"MapboxMaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"url":"\/documentation\/mapboxmaps","kind":"symbol","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AppleLocationProvider":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProvider","navigatorTitle":[{"text":"AppleLocationProvider","kind":"identifier"}],"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AppleLocationProvider","kind":"identifier"}],"title":"AppleLocationProvider","role":"symbol","abstract":[{"text":"A location provider based on CoreLocation’s ","type":"text"},{"code":"CLLocationManager","type":"codeVoice"},{"text":".","type":"text"}],"url":"\/documentation\/mapboxmaps\/applelocationprovider"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AppleLocationProviderDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AppleLocationProviderDelegate","kind":"identifier"}],"title":"AppleLocationProviderDelegate","abstract":[{"text":"The ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProviderDelegate","type":"reference","isActive":true},{"text":" protocol defines a set of optional methods that you","type":"text"},{"text":" ","type":"text"},{"text":"can use to receive events from an associated location provider object.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProviderDelegate","type":"topic","url":"\/documentation\/mapboxmaps\/applelocationproviderdelegate","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"AppleLocationProviderDelegate","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationProvider":{"abstract":[{"text":"Location provider that provides locations","type":"text"}],"title":"LocationProvider","role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"text":"LocationProvider","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/locationprovider","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationProvider","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelScaleMode/viewport":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/modelscalemode\/viewport","role":"symbol","abstract":[{"type":"text","text":"Model is scaled so that it’s always the same size on the screen. The property model-scale specifies how many pixels each unit in model file should cover."}],"tags":[{"type":"spi","text":"SPI"}],"title":"viewport","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelScaleMode\/viewport","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewport","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps14ModelScaleModeV","text":"ModelScaleMode","kind":"typeIdentifier"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Puck3DConfiguration/modelColorUseTheme":{"tags":[{"type":"spi","text":"SPI"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration\/modelColorUseTheme","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"modelColorUseTheme","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Value","preciseIdentifier":"s:10MapboxMaps5ValueO","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"ColorUseTheme","preciseIdentifier":"s:10MapboxMaps13ColorUseThemeV","kind":"typeIdentifier"},{"text":">?","kind":"text"}],"title":"modelColorUseTheme","abstract":[{"text":"This property defines whether to use colorTheme defined color or not.","type":"text"},{"text":" ","type":"text"},{"text":"By default it will use color defined by the root theme in the style.","type":"text"},{"text":" ","type":"text"},{"text":"NOTE: - Expressions set to this property currently don’t work.","type":"text"}],"url":"\/documentation\/mapboxmaps\/puck3dconfiguration\/modelcolorusetheme","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Puck3DConfiguration/modelElevationReference":{"title":"modelElevationReference","role":"symbol","tags":[{"text":"SPI","type":"spi"}],"abstract":[{"type":"text","text":"Selects the base of the model. Some modes might require precomputed elevation data in the tileset."},{"type":"text","text":" "},{"type":"text","text":"Default value: “ground”."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration\/modelElevationReference","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"modelElevationReference","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Value","preciseIdentifier":"s:10MapboxMaps5ValueO","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"ModelElevationReference","preciseIdentifier":"s:10MapboxMaps23ModelElevationReferenceV","kind":"typeIdentifier"},{"text":">?","kind":"text"}],"type":"topic","url":"\/documentation\/mapboxmaps\/puck3dconfiguration\/modelelevationreference"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Puck3DConfiguration":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Puck3DConfiguration"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Puck3DConfiguration"}],"title":"Puck3DConfiguration","role":"symbol","kind":"symbol","url":"\/documentation\/mapboxmaps\/puck3dconfiguration"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Puck2DConfiguration":{"navigatorTitle":[{"text":"Puck2DConfiguration","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck2DConfiguration","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Puck2DConfiguration","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/puck2dconfiguration","title":"Puck2DConfiguration"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationError":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationError"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"LocationError"}],"abstract":[{"type":"text","text":"Error code with brief explanation."}],"url":"\/documentation\/mapboxcommon\/locationerror","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationError","title":"LocationError"}},"variantOverrides":[{"patch":[{"value":"MBXPermissionStatus","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/title"},{"value":[{"text":"MBXPermissionStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/fragments"},{"value":[{"text":"MBXPermissionStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/navigatorTitle"},{"value":"MBXAccuracyLevel","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel\/title"},{"value":[{"kind":"identifier","text":"MBXAccuracyLevel"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel\/fragments"},{"value":[{"text":"MBXAccuracyLevel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel\/navigatorTitle"},{"value":"MBXAccuracyAuthorization","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization\/title"},{"value":[{"text":"MBXAccuracyAuthorization","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization\/fragments"},{"value":[{"kind":"identifier","text":"MBXAccuracyAuthorization"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization\/navigatorTitle"},{"value":"MBXLocationExtraKeys","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationExtraKeys\/title"},{"value":[{"kind":"identifier","text":"MBXLocationExtraKeys"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationExtraKeys\/fragments"},{"value":[{"kind":"identifier","text":"MBXLocationExtraKeys"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationExtraKeys\/navigatorTitle","op":"replace"},{"value":"MBXDeviceLocationProvider","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1DeviceLocationProvider\/title","op":"replace"},{"value":[{"text":"MBXDeviceLocationProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1DeviceLocationProvider\/fragments","op":"replace"},{"value":[{"text":"MBXDeviceLocationProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1DeviceLocationProvider\/navigatorTitle","op":"replace"},{"value":"MBXLocation","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/title","op":"replace"},{"value":[{"text":"MBXLocation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/fragments","op":"replace"},{"value":[{"text":"MBXLocation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/navigatorTitle","op":"replace"},{"value":"MBXCoordinate2D","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Coordinate2D\/title","op":"replace"},{"value":[{"text":"MBXCoordinate2D","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Coordinate2D\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MBXCoordinate2D"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Coordinate2D\/navigatorTitle","op":"replace"},{"value":"MBXLocationServiceObserver","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MBXLocationServiceObserver"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MBXLocationServiceObserver"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver\/navigatorTitle","op":"replace"},{"value":"MBXLocationObserver","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MBXLocationObserver"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/fragments","op":"replace"},{"value":[{"text":"MBXLocationObserver","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/navigatorTitle","op":"replace"},{"value":"MBXLocationErrorCode","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MBXLocationErrorCode"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/fragments","op":"replace"},{"value":[{"text":"MBXLocationErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/navigatorTitle","op":"replace"},{"value":"MBXLocationServiceFactory","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceFactory\/title","op":"replace"},{"value":[{"text":"MBXLocationServiceFactory","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceFactory\/fragments","op":"replace"},{"value":[{"text":"MBXLocationServiceFactory","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceFactory\/navigatorTitle","op":"replace"},{"value":"MBXIntervalSettings","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1IntervalSettings\/title","op":"replace"},{"value":[{"text":"MBXIntervalSettings","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1IntervalSettings\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MBXIntervalSettings"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1IntervalSettings\/navigatorTitle","op":"replace"},{"value":"MBXLocationProviderRequest","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProviderRequest\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MBXLocationProviderRequest"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProviderRequest\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MBXLocationProviderRequest"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProviderRequest\/navigatorTitle","op":"replace"},{"value":"MBXLocationProvider","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MBXLocationProvider"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MBXLocationProvider"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/navigatorTitle","op":"replace"},{"value":"MBXLocationError","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationError\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MBXLocationError"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationError\/fragments","op":"replace"},{"value":[{"text":"MBXLocationError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationError\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}