{"abstract":[{"text":"Estimates the storage and transfer size of a tile region.","type":"text"}],"variants":[{"paths":["\/documentation\/mapboxcommon\/mbxtilestore\/estimatetileregion(forid:loadoptions:estimateoptions:progress:completion:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@discardableResult","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"estimateTileRegion"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forId"},{"text":" ","kind":"text"},{"text":"id","kind":"internalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"loadOptions","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions","text":"TileRegionLoadOptions","preciseIdentifier":"c:objc(cs)MBXTileRegionLoadOptions"},{"kind":"text","text":", "},{"kind":"externalParam","text":"estimateOptions"},{"kind":"text","text":": "},{"text":"TileRegionEstimateOptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateOptions","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXTileRegionEstimateOptions"},{"text":"? = nil, ","kind":"text"},{"text":"progress","kind":"externalParam"},{"kind":"text","text":": "},{"text":"@escaping","kind":"keyword"},{"kind":"text","text":" "},{"text":"TileRegionEstimateProgressCallback","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgressCallback","preciseIdentifier":"c:MBXTileRegionEstimateProgressCallback.h@T@MBXTileRegionEstimateProgressCallback","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO","text":"Result"},{"kind":"text","text":"<"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateResult","text":"TileRegionEstimateResult","preciseIdentifier":"c:objc(cs)MBXTileRegionEstimateResult","kind":"typeIdentifier"},{"text":", any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> any "},{"preciseIdentifier":"c:objc(pl)MBXCancelable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Cancelable","kind":"typeIdentifier","text":"Cancelable"}]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"a ","type":"text"},{"code":"Cancelable","type":"codeVoice"},{"type":"text","text":" object to cancel the estimate request"}]}]},{"kind":"content","content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"id The tile region identifier."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"loadOptions The tile region load options.","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"estimateOptions The options for the estimate operation. Optional, default values will be aplied if nil."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"onProgress Invoked multiple times to report progess of the estimate operation.","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"onFinished Invoked only once upon success, failure, or cancelation of the estimate operation."}],"type":"paragraph"}]}],"type":"unorderedList"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This can be used for estimating existing or new tile regions. For new tile"},{"type":"text","text":" "},{"text":"regions, both geometry and tileset descriptors need to be provided to the","type":"text"},{"text":" ","type":"text"},{"text":"given load options.  If a tile region with the given id already exists, its","type":"text"},{"text":" ","type":"text"},{"text":"geometry and tileset descriptors are reused unless a different value is","type":"text"},{"type":"text","text":" "},{"text":"provided in the region load options.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"Estimating a tile region does not mutate exising tile regions on the tile store.","type":"text"}]}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"estimateTileRegion"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"loadOptions"},{"text":": ","kind":"text"},{"text":"TileRegionLoadOptions","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXTileRegionLoadOptions"},{"text":", ","kind":"text"},{"text":"estimateOptions","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TileRegionEstimateOptions","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXTileRegionEstimateOptions"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"progress"},{"kind":"text","text":": "},{"text":"TileRegionEstimateProgressCallback","kind":"typeIdentifier","preciseIdentifier":"c:MBXTileRegionEstimateProgressCallback.h@T@MBXTileRegionEstimateProgressCallback"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBXTileRegionEstimateResult","text":"TileRegionEstimateResult","kind":"typeIdentifier"},{"kind":"text","text":", any "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":">) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":") -> any "},{"text":"Cancelable","preciseIdentifier":"c:objc(pl)MBXCancelable","kind":"typeIdentifier"}],"modules":[{"name":"MapboxCommon"}],"roleHeading":"Instance Method","title":"estimateTileRegion(forId:loadOptions:estimateOptions:progress:completion:)","extendedModule":"MapboxCommon","externalID":"s:So12MBXTileStoreC10MapboxMapsE18estimateTileRegion5forId11loadOptions0eK08progress10completionSo13MBXCancelable_pSS_So0ag4LoadK0CSo0ag8EstimateK0CSgySo0agP8ProgressCcys6ResultOySo0agpR0Cs5Error_pGctF","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXTileStore\/estimateTileRegion(forId:loadOptions:estimateOptions:progress:completion:)"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileStore":{"role":"symbol","url":"\/documentation\/mapboxcommon\/tilestore","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileStore","kind":"identifier"}],"abstract":[{"text":"TileStore manages downloads and storage for requests to tile-related API endpoints, enforcing a disk usage","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"quota: tiles available on disk may be deleted to make room for a new download. This interface can be used by an"},{"type":"text","text":" "},{"text":"app developer to set the disk quota. The rest of TileStore API is intended for native SDK consumption only.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore","title":"TileStore","type":"topic","navigatorTitle":[{"text":"TileStore","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXTileStore/estimateTileRegion(forId:loadOptions:estimateOptions:progress:completion:)":{"kind":"symbol","title":"estimateTileRegion(forId:loadOptions:estimateOptions:progress:completion:)","abstract":[{"text":"Estimates the storage and transfer size of a tile region.","type":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXTileStore\/estimateTileRegion(forId:loadOptions:estimateOptions:progress:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"estimateTileRegion","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"loadOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TileRegionLoadOptions","preciseIdentifier":"c:objc(cs)MBXTileRegionLoadOptions"},{"kind":"text","text":", "},{"text":"estimateOptions","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXTileRegionEstimateOptions","text":"TileRegionEstimateOptions"},{"text":"?, ","kind":"text"},{"text":"progress","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:MBXTileRegionEstimateProgressCallback.h@T@MBXTileRegionEstimateProgressCallback","kind":"typeIdentifier","text":"TileRegionEstimateProgressCallback"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)MBXTileRegionEstimateResult","kind":"typeIdentifier","text":"TileRegionEstimateResult"},{"kind":"text","text":", any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":") -> any ","kind":"text"},{"text":"Cancelable","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MBXCancelable"}],"url":"\/documentation\/mapboxcommon\/mbxtilestore\/estimatetileregion(forid:loadoptions:estimateoptions:progress:completion:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadOptions":{"role":"symbol","abstract":[{"text":"Describes the tile region load option values.","type":"text"}],"title":"TileRegionLoadOptions","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileRegionLoadOptions","kind":"identifier"}],"navigatorTitle":[{"text":"TileRegionLoadOptions","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions","url":"\/documentation\/mapboxcommon\/tileregionloadoptions","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateResult":{"role":"symbol","kind":"symbol","url":"\/documentation\/mapboxcommon\/tileregionestimateresult","type":"topic","abstract":[{"type":"text","text":"The result of tile region estim"}],"title":"TileRegionEstimateResult","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileRegionEstimateResult","kind":"identifier"}],"navigatorTitle":[{"text":"TileRegionEstimateResult","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateResult"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"url":"\/documentation\/mapboxmaps\/tilestore-apis","kind":"article","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","type":"topic","title":"TileStore APIs"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateOptions":{"role":"symbol","kind":"symbol","url":"\/documentation\/mapboxcommon\/tileregionestimateoptions","type":"topic","abstract":[{"type":"text","text":"Holds options for the tile region estimation operation."}],"title":"TileRegionEstimateOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TileRegionEstimateOptions","kind":"identifier"}],"navigatorTitle":[{"text":"TileRegionEstimateOptions","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateProgressCallback":{"role":"symbol","kind":"symbol","url":"\/documentation\/mapboxcommon\/tileregionestimateprogresscallback","type":"topic","abstract":[],"title":"TileRegionEstimateProgressCallback","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileRegionEstimateProgressCallback","kind":"identifier"}],"navigatorTitle":[{"text":"TileRegionEstimateProgressCallback","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgressCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Cancelable":{"title":"Cancelable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Cancelable","kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Cancelable","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/cancelable","abstract":[{"text":"Allows to cancel the associated asynchronous operation","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"Cancelable"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"MBXTileStore","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/title"},{"value":[{"kind":"identifier","text":"MBXTileStore"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/title","value":"MBXTileRegionLoadOptions","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/fragments","value":[{"kind":"identifier","text":"MBXTileRegionLoadOptions"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateResult\/title","op":"replace","value":"MBXTileRegionEstimateResult"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateResult\/fragments","value":[{"text":"MBXTileRegionEstimateResult","kind":"identifier"}]},{"value":"MBXTileRegionEstimateOptions","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateOptions\/title","op":"replace"},{"value":[{"text":"MBXTileRegionEstimateOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateOptions\/fragments","op":"replace"},{"op":"replace","value":"MBXTileRegionEstimateProgressCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgressCallback\/title"},{"op":"replace","value":[{"text":"MBXTileRegionEstimateProgressCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgressCallback\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/title","op":"replace","value":"MBXCancelable"},{"op":"replace","value":[{"text":"MBXCancelable","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}