{"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"metadata":{"extendedModule":"MapboxCommon","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadTileRegion"},{"text":"(","kind":"text"},{"text":"forId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"loadOptions"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MBXTileRegionLoadOptions","kind":"typeIdentifier","text":"TileRegionLoadOptions"},{"text":", ","kind":"text"},{"text":"progress","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TileRegionLoadProgressCallback","kind":"typeIdentifier","preciseIdentifier":"c:MBXTileRegionLoadProgressCallback.h@T@MBXTileRegionLoadProgressCallback"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:s6ResultO","kind":"typeIdentifier","text":"Result"},{"kind":"text","text":"<"},{"text":"TileRegion","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXTileRegion"},{"text":", any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":">) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> any "},{"kind":"typeIdentifier","text":"Cancelable","preciseIdentifier":"c:objc(pl)MBXCancelable"}],"modules":[{"name":"MapboxCommon"}],"externalID":"s:So12MBXTileStoreC10MapboxMapsE14loadTileRegion5forId0E7Options8progress10completionSo13MBXCancelable_pSS_So0ag4LoadJ0CySo0agN8ProgressCcSgys6ResultOySo0aG0Cs5Error_pGctF","title":"loadTileRegion(forId:loadOptions:progress:completion:)","roleHeading":"Instance Method","role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXTileStore\/loadTileRegion(forId:loadOptions:progress:completion:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@discardableResult","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadTileRegion"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forId"},{"text":" ","kind":"text"},{"text":"id","kind":"internalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"loadOptions","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TileRegionLoadOptions","preciseIdentifier":"c:objc(cs)MBXTileRegionLoadOptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"progress"},{"text":": ","kind":"text"},{"text":"TileRegionLoadProgressCallback","kind":"typeIdentifier","preciseIdentifier":"c:MBXTileRegionLoadProgressCallback.h@T@MBXTileRegionLoadProgressCallback","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgressCallback"},{"text":"? = nil, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"keyword"},{"kind":"text","text":" ("},{"preciseIdentifier":"s:s6ResultO","text":"Result","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXTileRegion","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegion","text":"TileRegion"},{"kind":"text","text":", any "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":">) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":") -> any ","kind":"text"},{"kind":"typeIdentifier","text":"Cancelable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Cancelable","preciseIdentifier":"c:objc(pl)MBXCancelable"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"id","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The tile region identifier."}]}]},{"name":"loadOptions","content":[{"type":"paragraph","inlineContent":[{"text":"The tile region load options.","type":"text"}]}]},{"name":"progress","content":[{"inlineContent":[{"text":"Invoked multiple times to report progress of the loading","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"operation. Optional, default is nil."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Invoked only once upon success, failure, or cancelation","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"of the loading operation. Any "},{"type":"codeVoice","code":"Result"},{"text":" error could be of type","type":"text"},{"type":"text","text":" "},{"type":"codeVoice","code":"TileRegionError"},{"text":".","type":"text"}]}],"name":"completion"}],"kind":"parameters"},{"kind":"content","content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"A "},{"type":"codeVoice","code":"Cancelable"},{"text":" object to cancel the load request","type":"text"}],"type":"paragraph"}]},{"content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"inlineContent":[{"type":"text","text":"Creating of a new region requires providing both geometry and tileset"},{"text":" ","type":"text"},{"type":"text","text":"descriptors to the given load options, otherwise the load request fails"},{"type":"text","text":" "},{"text":"with ","type":"text"},{"type":"codeVoice","code":"RegionNotFound"},{"text":" error.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"If a tile region with the given id already exists, it gets updated with","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"the values provided to the given load options. The missing resources get"},{"type":"text","text":" "},{"text":"loaded and the expired resources get updated.","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"If there are no values provided to the given load options, the existing tile","type":"text"},{"text":" ","type":"text"},{"text":"region gets refreshed: the missing resources get loaded and the expired","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"resources get updated."}]},{"inlineContent":[{"text":"A failed load request can be reattempted with another ","type":"text"},{"type":"codeVoice","code":"loadTileRegion()"},{"text":" call.","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"If there is already a pending loading operation for the tile region with"},{"type":"text","text":" "},{"text":"the given id, the pending loading operation will fail with an error of","type":"text"},{"text":" ","type":"text"},{"code":"Canceled","type":"codeVoice"},{"type":"text","text":" type."}]}],"kind":"content"}],"abstract":[{"type":"text","text":"Loads a new tile region or updates the existing one."}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/mbxtilestore\/loadtileregion(forid:loadoptions:progress:completion:)"]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadOptions":{"role":"symbol","abstract":[{"text":"Describes the tile region load option values.","type":"text"}],"title":"TileRegionLoadOptions","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileRegionLoadOptions","kind":"identifier"}],"navigatorTitle":[{"text":"TileRegionLoadOptions","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions","url":"\/documentation\/mapboxcommon\/tileregionloadoptions","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileStore":{"role":"symbol","url":"\/documentation\/mapboxcommon\/tilestore","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileStore","kind":"identifier"}],"abstract":[{"text":"TileStore manages downloads and storage for requests to tile-related API endpoints, enforcing a disk usage","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"quota: tiles available on disk may be deleted to make room for a new download. This interface can be used by an"},{"type":"text","text":" "},{"text":"app developer to set the disk quota. The rest of TileStore API is intended for native SDK consumption only.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore","title":"TileStore","type":"topic","navigatorTitle":[{"text":"TileStore","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadProgressCallback":{"role":"symbol","kind":"symbol","url":"\/documentation\/mapboxcommon\/tileregionloadprogresscallback","type":"topic","abstract":[{"text":"Callback Invoked to report the progess of the tile region loading operation.","type":"text"}],"title":"TileRegionLoadProgressCallback","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"TileRegionLoadProgressCallback","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"TileRegionLoadProgressCallback"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgressCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Cancelable":{"title":"Cancelable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Cancelable","kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Cancelable","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/cancelable","abstract":[{"text":"Allows to cancel the associated asynchronous operation","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"Cancelable"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"url":"\/documentation\/mapboxmaps\/tilestore-apis","kind":"article","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","type":"topic","title":"TileStore APIs"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegion":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegion","title":"TileRegion","kind":"symbol","navigatorTitle":[{"text":"TileRegion","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/tileregion","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileRegion","kind":"identifier"}],"abstract":[{"text":"TileRegion represents an identifiable geographic tile region with metadata","type":"text"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXTileStore/loadTileRegion(forId:loadOptions:progress:completion:)":{"url":"\/documentation\/mapboxcommon\/mbxtilestore\/loadtileregion(forid:loadoptions:progress:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadTileRegion","kind":"identifier"},{"kind":"text","text":"("},{"text":"forId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"loadOptions"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBXTileRegionLoadOptions","kind":"typeIdentifier","text":"TileRegionLoadOptions"},{"kind":"text","text":", "},{"text":"progress","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TileRegionLoadProgressCallback","preciseIdentifier":"c:MBXTileRegionLoadProgressCallback.h@T@MBXTileRegionLoadProgressCallback"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)MBXTileRegion","kind":"typeIdentifier","text":"TileRegion"},{"text":", any ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":">) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> any "},{"text":"Cancelable","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MBXCancelable"}],"type":"topic","abstract":[{"text":"Loads a new tile region or updates the existing one.","type":"text"}],"title":"loadTileRegion(forId:loadOptions:progress:completion:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXTileStore\/loadTileRegion(forId:loadOptions:progress:completion:)","kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/title","value":"MBXTileRegionLoadOptions"},{"op":"replace","value":[{"text":"MBXTileRegionLoadOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/title","value":"MBXTileStore"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/fragments","value":[{"kind":"identifier","text":"MBXTileStore"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgressCallback\/title","value":"MBXTileRegionLoadProgressCallback","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgressCallback\/fragments","value":[{"kind":"identifier","text":"MBXTileRegionLoadProgressCallback"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/title","op":"replace","value":"MBXCancelable"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/fragments","op":"replace","value":[{"text":"MBXCancelable","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegion\/title","value":"MBXTileRegion"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegion\/fragments","op":"replace","value":[{"text":"MBXTileRegion","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}