{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeRegion"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forId"},{"kind":"text","text":" "},{"text":"id","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"keyword","text":"@escaping"},{"text":" (","kind":"text"},{"preciseIdentifier":"s:s6ResultO","text":"Result","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegion","text":"TileRegion","preciseIdentifier":"c:objc(cs)MBXTileRegion"},{"kind":"text","text":", any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The tile region identifier.","type":"text"}]}],"name":"id"},{"name":"completion","content":[{"inlineContent":[{"type":"text","text":"A callback to be invoked when a tile region was removed."}],"type":"paragraph"}]}],"kind":"parameters"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXTileStore\/removeRegion(forId:completion:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"MapboxCommon"}],"extendedModule":"MapboxCommon","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"removeRegion","kind":"identifier"},{"kind":"text","text":"("},{"text":"forId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXTileRegion","text":"TileRegion"},{"kind":"text","text":", any "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"title":"removeRegion(forId:completion:)","role":"symbol","externalID":"s:So12MBXTileStoreC10MapboxMapsE12removeRegion5forId10completionySS_ys6ResultOySo0aF0Cs5Error_pGctF"},"sections":[],"abstract":[{"type":"text","text":"An overloaded version of "},{"type":"codeVoice","code":"removeTileRegion(forId:)"},{"text":" with a callback for feedback.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"On successful tile region removal, the given callback is invoked with the removed tile region."},{"text":" ","type":"text"},{"type":"text","text":"Otherwise, the given callback is invoked with an error."}],"variants":[{"paths":["\/documentation\/mapboxcommon\/mbxtilestore\/removeregion(forid:completion:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"url":"\/documentation\/mapboxmaps\/tilestore-apis","kind":"article","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","type":"topic","title":"TileStore APIs"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileStore":{"role":"symbol","url":"\/documentation\/mapboxcommon\/tilestore","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileStore","kind":"identifier"}],"abstract":[{"text":"TileStore manages downloads and storage for requests to tile-related API endpoints, enforcing a disk usage","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"quota: tiles available on disk may be deleted to make room for a new download. This interface can be used by an"},{"type":"text","text":" "},{"text":"app developer to set the disk quota. The rest of TileStore API is intended for native SDK consumption only.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore","title":"TileStore","type":"topic","navigatorTitle":[{"text":"TileStore","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXTileStore/removeRegion(forId:completion:)":{"type":"topic","abstract":[{"text":"An overloaded version of ","type":"text"},{"code":"removeTileRegion(forId:)","type":"codeVoice"},{"text":" with a callback for feedback.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"On successful tile region removal, the given callback is invoked with the removed tile region."},{"type":"text","text":" "},{"type":"text","text":"Otherwise, the given callback is invoked with an error."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXTileStore\/removeRegion(forId:completion:)","url":"\/documentation\/mapboxcommon\/mbxtilestore\/removeregion(forid:completion:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"removeRegion"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"Result","preciseIdentifier":"s:s6ResultO","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBXTileRegion","text":"TileRegion","kind":"typeIdentifier"},{"text":", any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"removeRegion(forId:completion:)","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegion":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegion","title":"TileRegion","kind":"symbol","navigatorTitle":[{"text":"TileRegion","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/tileregion","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileRegion","kind":"identifier"}],"abstract":[{"text":"TileRegion represents an identifiable geographic tile region with metadata","type":"text"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MBXTileStore","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/fragments","value":[{"kind":"identifier","text":"MBXTileStore"}],"op":"replace"},{"op":"replace","value":"MBXTileRegion","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegion\/title"},{"value":[{"text":"MBXTileRegion","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegion\/fragments"}]}]}