{"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"subscribe","kind":"identifier"},{"kind":"text","text":"(any "},{"text":"TileStoreObserver","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps17TileStoreObserverP"},{"text":") -> any ","kind":"text"},{"text":"Cancelable","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MBXCancelable"}],"modules":[{"name":"MapboxCommon"}],"roleHeading":"Instance Method","title":"subscribe(_:)","extendedModule":"MapboxCommon","externalID":"s:So12MBXTileStoreC10MapboxMapsE9subscribeySo13MBXCancelable_pAC04TileB8Observer_pF","symbolKind":"method"},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXTileStore\/subscribe(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Allows observing a tile store’s activity"}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"subscribe"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"observer","kind":"internalParam"},{"kind":"text","text":": any "},{"text":"TileStoreObserver","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreObserver","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps17TileStoreObserverP"},{"text":") -> any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)MBXCancelable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Cancelable","kind":"typeIdentifier","text":"Cancelable"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"name":"observer","content":[{"type":"paragraph","inlineContent":[{"text":"The object to be notified when events occur. TileStore holds a strong reference to this object until the subscription is canceled.","type":"text"}]}]}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An object that can be used to cancel the subscription."}]}]}],"variants":[{"paths":["\/documentation\/mapboxcommon\/mbxtilestore\/subscribe(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStoreObserver":{"role":"symbol","kind":"symbol","url":"\/documentation\/mapboxmaps\/tilestoreobserver","type":"topic","abstract":[],"title":"TileStoreObserver","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TileStoreObserver"}],"navigatorTitle":[{"kind":"identifier","text":"TileStoreObserver"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreObserver"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Cancelable":{"title":"Cancelable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Cancelable","kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Cancelable","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/cancelable","abstract":[{"text":"Allows to cancel the associated asynchronous operation","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"Cancelable"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"url":"\/documentation\/mapboxmaps\/tilestore-apis","kind":"article","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","type":"topic","title":"TileStore APIs"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXTileStore/subscribe(_:)":{"role":"symbol","url":"\/documentation\/mapboxcommon\/mbxtilestore\/subscribe(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"subscribe","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"TileStoreObserver","preciseIdentifier":"s:10MapboxMaps17TileStoreObserverP","kind":"typeIdentifier"},{"kind":"text","text":") -> any "},{"text":"Cancelable","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MBXCancelable"}],"abstract":[{"type":"text","text":"Allows observing a tile store’s activity"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXTileStore\/subscribe(_:)","title":"subscribe(_:)","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileStore":{"role":"symbol","url":"\/documentation\/mapboxcommon\/tilestore","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileStore","kind":"identifier"}],"abstract":[{"text":"TileStore manages downloads and storage for requests to tile-related API endpoints, enforcing a disk usage","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"quota: tiles available on disk may be deleted to make room for a new download. This interface can be used by an"},{"type":"text","text":" "},{"text":"app developer to set the disk quota. The rest of TileStore API is intended for native SDK consumption only.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore","title":"TileStore","type":"topic","navigatorTitle":[{"text":"TileStore","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/title","value":"MBXCancelable","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXCancelable"}]},{"value":"MBXTileStore","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/title"},{"op":"replace","value":[{"text":"MBXTileStore","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}