{"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Returns a tile region given its id."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tileRegion"},{"text":"(","kind":"text"},{"text":"forId","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"id","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"keyword","text":"@escaping"},{"text":" (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO","text":"Result"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"TileRegion","preciseIdentifier":"c:objc(cs)MBXTileRegion","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegion"},{"kind":"text","text":", any "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]},{"parameters":[{"content":[{"inlineContent":[{"text":"The tile region id.","type":"text"}],"type":"paragraph"}],"name":"id"},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"text":"The Result callback. Any ","type":"text"},{"type":"codeVoice","code":"Result"},{"type":"text","text":" error could be of type"},{"type":"text","text":" "},{"type":"codeVoice","code":"TileRegionError"},{"text":".","type":"text"}]}]}],"kind":"parameters"}],"metadata":{"modules":[{"name":"MapboxCommon"}],"extendedModule":"MapboxCommon","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"tileRegion","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"TileRegion","preciseIdentifier":"c:objc(cs)MBXTileRegion"},{"text":", any ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":">) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol","externalID":"s:So12MBXTileStoreC10MapboxMapsE10tileRegion5forId10completionySS_ys6ResultOySo0aF0Cs5Error_pGctF","roleHeading":"Instance Method","title":"tileRegion(forId:completion:)"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXTileStore\/tileRegion(forId:completion:)"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore"]]},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/mbxtilestore\/tileregion(forid:completion:)"]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"url":"\/documentation\/mapboxmaps\/tilestore-apis","kind":"article","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","type":"topic","title":"TileStore APIs"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileStore":{"role":"symbol","url":"\/documentation\/mapboxcommon\/tilestore","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileStore","kind":"identifier"}],"abstract":[{"text":"TileStore manages downloads and storage for requests to tile-related API endpoints, enforcing a disk usage","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"quota: tiles available on disk may be deleted to make room for a new download. This interface can be used by an"},{"type":"text","text":" "},{"text":"app developer to set the disk quota. The rest of TileStore API is intended for native SDK consumption only.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore","title":"TileStore","type":"topic","navigatorTitle":[{"text":"TileStore","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegion":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegion","title":"TileRegion","kind":"symbol","navigatorTitle":[{"text":"TileRegion","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/tileregion","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileRegion","kind":"identifier"}],"abstract":[{"text":"TileRegion represents an identifiable geographic tile region with metadata","type":"text"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXTileStore/tileRegion(forId:completion:)":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"tileRegion","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"preciseIdentifier":"s:s6ResultO","kind":"typeIdentifier","text":"Result"},{"kind":"text","text":"<"},{"text":"TileRegion","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXTileRegion"},{"text":", any ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":">) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXTileStore\/tileRegion(forId:completion:)","url":"\/documentation\/mapboxcommon\/mbxtilestore\/tileregion(forid:completion:)","role":"symbol","abstract":[{"text":"Returns a tile region given its id.","type":"text"}],"title":"tileRegion(forId:completion:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/title","op":"replace","value":"MBXTileStore"},{"op":"replace","value":[{"text":"MBXTileStore","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegion\/title","op":"replace","value":"MBXTileRegion"},{"op":"replace","value":[{"kind":"identifier","text":"MBXTileRegion"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegion\/fragments"}]}]}