{"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXTileStore\/tileRegionContainsDescriptors(forId:descriptors:completion:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"title":"tileRegionContainsDescriptors(forId:descriptors:completion:)","modules":[{"name":"MapboxCommon"}],"extendedModule":"MapboxCommon","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"tileRegionContainsDescriptors","kind":"identifier"},{"kind":"text","text":"("},{"text":"forId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"descriptors","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"TilesetDescriptor","preciseIdentifier":"c:objc(cs)MBXTilesetDescriptor","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":">) -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol","externalID":"s:So12MBXTileStoreC10MapboxMapsE29tileRegionContainsDescriptors5forId11descriptors10completionySS_SaySo20MBXTilesetDescriptorCGys6ResultOySbs5Error_pGctF"},"variants":[{"paths":["\/documentation\/mapboxcommon\/mbxtilestore\/tileregioncontainsdescriptors(forid:descriptors:completion:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore"]]},"abstract":[{"text":"Checks if a tile region with the given id contains all tilesets from all","type":"text"},{"type":"text","text":" "},{"text":"of the given tileset descriptors.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"tileRegionContainsDescriptors","kind":"identifier"},{"kind":"text","text":"("},{"text":"forId","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"descriptors"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TilesetDescriptor","preciseIdentifier":"c:objc(cs)MBXTilesetDescriptor","kind":"typeIdentifier","text":"TilesetDescriptor"},{"text":"], ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"keyword","text":"@escaping"},{"text":" (","kind":"text"},{"preciseIdentifier":"s:s6ResultO","kind":"typeIdentifier","text":"Result"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"id","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The tile region identifier."}]}]},{"name":"descriptors","content":[{"inlineContent":[{"type":"text","text":"The array of tileset descriptors."}],"type":"paragraph"}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The result callback. Any "},{"type":"codeVoice","code":"Result"},{"text":" error could be of type","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"TileRegionError"},{"type":"text","text":"."}]}]}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXTileStore/tileRegionContainsDescriptors(forId:descriptors:completion:)":{"kind":"symbol","title":"tileRegionContainsDescriptors(forId:descriptors:completion:)","abstract":[{"type":"text","text":"Checks if a tile region with the given id contains all tilesets from all"},{"type":"text","text":" "},{"type":"text","text":"of the given tileset descriptors."}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXTileStore\/tileRegionContainsDescriptors(forId:descriptors:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tileRegionContainsDescriptors"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"descriptors","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXTilesetDescriptor","text":"TilesetDescriptor"},{"kind":"text","text":"], "},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:s6ResultO","text":"Result","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", any "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"url":"\/documentation\/mapboxcommon\/mbxtilestore\/tileregioncontainsdescriptors(forid:descriptors:completion:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"url":"\/documentation\/mapboxmaps\/tilestore-apis","kind":"article","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","type":"topic","title":"TileStore APIs"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileStore":{"role":"symbol","url":"\/documentation\/mapboxcommon\/tilestore","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileStore","kind":"identifier"}],"abstract":[{"text":"TileStore manages downloads and storage for requests to tile-related API endpoints, enforcing a disk usage","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"quota: tiles available on disk may be deleted to make room for a new download. This interface can be used by an"},{"type":"text","text":" "},{"text":"app developer to set the disk quota. The rest of TileStore API is intended for native SDK consumption only.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore","title":"TileStore","type":"topic","navigatorTitle":[{"text":"TileStore","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TilesetDescriptor":{"role":"symbol","kind":"symbol","url":"\/documentation\/mapboxcommon\/tilesetdescriptor","type":"topic","abstract":[{"type":"text","text":"A bundle that encapsulates tilesets creation for the tile store implementation."}],"title":"TilesetDescriptor","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TilesetDescriptor"}],"navigatorTitle":[{"kind":"identifier","text":"TilesetDescriptor"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TilesetDescriptor"}},"variantOverrides":[{"patch":[{"value":"MBXTileStore","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/title"},{"value":[{"kind":"identifier","text":"MBXTileStore"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/fragments","op":"replace"},{"value":"MBXTilesetDescriptor","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TilesetDescriptor\/title"},{"value":[{"kind":"identifier","text":"MBXTilesetDescriptor"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TilesetDescriptor\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}