{"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore\/loadTileRegion(forId:loadOptions:progress:completion:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/tilestore\/loadtileregion(forid:loadoptions:progress:completion:)"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@discardableResult"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadTileRegion"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forId"},{"kind":"text","text":" "},{"kind":"internalParam","text":"id"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"loadOptions"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MBXTileRegionLoadOptions","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions","text":"TileRegionLoadOptions"},{"kind":"text","text":", "},{"kind":"externalParam","text":"progress"},{"kind":"text","text":": "},{"preciseIdentifier":"c:MBXTileRegionLoadProgressCallback.h@T@MBXTileRegionLoadProgressCallback","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgressCallback","text":"TileRegionLoadProgressCallback"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"keyword"},{"text":" (","kind":"text"},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"text":"<","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegion","text":"TileRegion","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXTileRegion"},{"text":", any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":">) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":") -> any ","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Cancelable","text":"Cancelable","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MBXCancelable"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"name":"id","content":[{"inlineContent":[{"type":"text","text":"The tile region identifier."}],"type":"paragraph"}]},{"name":"loadOptions","content":[{"inlineContent":[{"text":"The tile region load options.","type":"text"}],"type":"paragraph"}]},{"name":"progress","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Invoked multiple times to report progress of the loading"},{"type":"text","text":" "},{"type":"text","text":"operation. Optional, default is nil."}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Invoked only once upon success, failure, or cancelation"},{"type":"text","text":" "},{"type":"text","text":"of the loading operation. Any "},{"code":"Result","type":"codeVoice"},{"type":"text","text":" error could be of type"},{"type":"text","text":" "},{"code":"TileRegionError","type":"codeVoice"},{"type":"text","text":"."}]}]}],"kind":"parameters"},{"content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"Cancelable"},{"text":" object to cancel the load request","type":"text"}]}],"kind":"content"},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"inlineContent":[{"text":"Creating of a new region requires providing both geometry and tileset","type":"text"},{"text":" ","type":"text"},{"text":"descriptors to the given load options, otherwise the load request fails","type":"text"},{"text":" ","type":"text"},{"text":"with ","type":"text"},{"code":"RegionNotFound","type":"codeVoice"},{"text":" error.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"If a tile region with the given id already exists, it gets updated with","type":"text"},{"text":" ","type":"text"},{"text":"the values provided to the given load options. The missing resources get","type":"text"},{"text":" ","type":"text"},{"text":"loaded and the expired resources get updated.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"If there are no values provided to the given load options, the existing tile"},{"type":"text","text":" "},{"type":"text","text":"region gets refreshed: the missing resources get loaded and the expired"},{"type":"text","text":" "},{"type":"text","text":"resources get updated."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"A failed load request can be reattempted with another "},{"type":"codeVoice","code":"loadTileRegion()"},{"type":"text","text":" call."}],"type":"paragraph"},{"inlineContent":[{"text":"If there is already a pending loading operation for the tile region with","type":"text"},{"text":" ","type":"text"},{"text":"the given id, the pending loading operation will fail with an error of","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"Canceled"},{"text":" type.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Loads a new tile region or updates the existing one."}],"metadata":{"symbolKind":"method","externalID":"s:So12MBXTileStoreC10MapboxMapsE14loadTileRegion5forId0E7Options8progress10completionSo13MBXCancelable_pSS_So0ag4LoadJ0CySo0agN8ProgressCcSgys6ResultOySo0aG0Cs5Error_pGctF","title":"loadTileRegion(forId:loadOptions:progress:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadTileRegion","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"loadOptions","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBXTileRegionLoadOptions","text":"TileRegionLoadOptions","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"progress","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:MBXTileRegionLoadProgressCallback.h@T@MBXTileRegionLoadProgressCallback","text":"TileRegionLoadProgressCallback","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:s6ResultO","text":"Result","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBXTileRegion","text":"TileRegion","kind":"typeIdentifier"},{"text":", any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":") -> any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)MBXCancelable","text":"Cancelable","kind":"typeIdentifier"}],"modules":[{"name":"MapboxCommon"}],"extendedModule":"MapboxCommon","roleHeading":"Instance Method","role":"symbol"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadOptions":{"url":"\/documentation\/mapboxcommon\/tileregionloadoptions","role":"symbol","abstract":[{"text":"Describes the tile region load option values.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions","type":"topic","navigatorTitle":[{"text":"TileRegionLoadOptions","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileRegionLoadOptions","kind":"identifier"}],"kind":"symbol","title":"TileRegionLoadOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Cancelable":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"Cancelable","kind":"identifier"}],"title":"Cancelable","kind":"symbol","abstract":[{"text":"Allows to cancel the associated asynchronous operation","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Cancelable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Cancelable","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/cancelable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileStore/loadTileRegion(forId:loadOptions:progress:completion:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore\/loadTileRegion(forId:loadOptions:progress:completion:)","url":"\/documentation\/mapboxcommon\/tilestore\/loadtileregion(forid:loadoptions:progress:completion:)","kind":"symbol","abstract":[{"type":"text","text":"Loads a new tile region or updates the existing one."}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadTileRegion"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"loadOptions"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MBXTileRegionLoadOptions","kind":"typeIdentifier","text":"TileRegionLoadOptions"},{"kind":"text","text":", "},{"kind":"externalParam","text":"progress"},{"kind":"text","text":": "},{"preciseIdentifier":"c:MBXTileRegionLoadProgressCallback.h@T@MBXTileRegionLoadProgressCallback","kind":"typeIdentifier","text":"TileRegionLoadProgressCallback"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"preciseIdentifier":"s:s6ResultO","kind":"typeIdentifier","text":"Result"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)MBXTileRegion","kind":"typeIdentifier","text":"TileRegion"},{"kind":"text","text":", any "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":">) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":") -> any "},{"preciseIdentifier":"c:objc(pl)MBXCancelable","kind":"typeIdentifier","text":"Cancelable"}],"title":"loadTileRegion(forId:loadOptions:progress:completion:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"type":"topic","url":"\/documentation\/mapboxmaps","role":"collection","kind":"symbol","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileStore":{"kind":"symbol","abstract":[{"text":"TileStore manages downloads and storage for requests to tile-related API endpoints, enforcing a disk usage","type":"text"},{"text":" ","type":"text"},{"text":"quota: tiles available on disk may be deleted to make room for a new download. This interface can be used by an","type":"text"},{"text":" ","type":"text"},{"text":"app developer to set the disk quota. The rest of TileStore API is intended for native SDK consumption only.","type":"text"}],"navigatorTitle":[{"text":"TileStore","kind":"identifier"}],"title":"TileStore","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileStore","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapboxcommon\/tilestore","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegion":{"role":"symbol","title":"TileRegion","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileRegion","kind":"identifier"}],"abstract":[{"text":"TileRegion represents an identifiable geographic tile region with metadata","type":"text"}],"navigatorTitle":[{"text":"TileRegion","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxcommon\/tileregion","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegion","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","url":"\/documentation\/overview","role":"collection","abstract":[],"kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"abstract":[],"url":"\/documentation\/mapboxmaps\/tilestore-apis","title":"TileStore APIs","kind":"article","type":"topic","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadProgressCallback":{"url":"\/documentation\/mapboxcommon\/tileregionloadprogresscallback","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileRegionLoadProgressCallback"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgressCallback","navigatorTitle":[{"kind":"identifier","text":"TileRegionLoadProgressCallback"}],"abstract":[{"type":"text","text":"Callback Invoked to report the progess of the tile region loading operation."}],"title":"TileRegionLoadProgressCallback","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/title","value":"MBXTileRegionLoadOptions","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/fragments","value":[{"kind":"identifier","text":"MBXTileRegionLoadOptions"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/navigatorTitle","value":[{"kind":"identifier","text":"MBXTileRegionLoadOptions"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/title","value":"MBXCancelable","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/fragments","value":[{"kind":"identifier","text":"MBXCancelable"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/navigatorTitle","value":[{"kind":"identifier","text":"MBXCancelable"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/title","value":"MBXTileStore","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/fragments","value":[{"kind":"identifier","text":"MBXTileStore"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/navigatorTitle","value":[{"kind":"identifier","text":"MBXTileStore"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegion\/title","value":"MBXTileRegion","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegion\/fragments","value":[{"kind":"identifier","text":"MBXTileRegion"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegion\/navigatorTitle","value":[{"kind":"identifier","text":"MBXTileRegion"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgressCallback\/title","value":"MBXTileRegionLoadProgressCallback","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgressCallback\/fragments","value":[{"text":"MBXTileRegionLoadProgressCallback","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgressCallback\/navigatorTitle","value":[{"kind":"identifier","text":"MBXTileRegionLoadProgressCallback"}],"op":"replace"}]}]}