{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore\/setOptionForKey(_:domain:value:)"},"abstract":[{"type":"text","text":"Sets additional options for this instance that are specific to a data type."}],"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/tilestore\/setoptionforkey(_:domain:value:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/tilestore\/setoptionforkey(_:domain:value:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setOptionForKey"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"key"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"domain"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@MBXTileDataDomain","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileDataDomain","text":"TileDataDomain"},{"kind":"text","text":", "},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":")"}]}]},{"kind":"parameters","parameters":[{"name":"key","content":[{"type":"paragraph","inlineContent":[{"text":"The configuration option that should be changed. Valid keys are listed in \\c TileStoreOptions.","type":"text"}]}]},{"name":"domain","content":[{"inlineContent":[{"type":"text","text":"The data type this setting should be applied for."}],"type":"paragraph"}]},{"name":"value","content":[{"inlineContent":[{"type":"text","text":"The value for the configuration option, or null if it should be reset."}],"type":"paragraph"}]}]}],"metadata":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setOptionForKey","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"domain","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@MBXTileDataDomain","kind":"typeIdentifier","text":"TileDataDomain"},{"kind":"text","text":", "},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":")"}],"symbolKind":"method","title":"setOptionForKey(_:domain:value:)","navigatorTitle":[{"kind":"identifier","text":"setOptionForKey:domain:value:"}],"externalID":"c:objc(cs)MBXTileStore(im)setOptionForKey:domain:value:","modules":[{"name":"MapboxCommon"}],"roleHeading":"Instance Method"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","url":"\/documentation\/mapboxmaps","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"title":"MapboxMaps Documentation","type":"topic","kind":"article","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileStore/setOptionForKey(_:domain:value:)":{"url":"\/documentation\/mapboxcommon\/tilestore\/setoptionforkey(_:domain:value:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setOptionForKey"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"domain"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@MBXTileDataDomain","kind":"typeIdentifier","text":"TileDataDomain"},{"kind":"text","text":", "},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":")"}],"type":"topic","title":"setOptionForKey(_:domain:value:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore\/setOptionForKey(_:domain:value:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setOptionForKey:domain:value:"}],"kind":"symbol","abstract":[{"text":"Sets additional options for this instance that are specific to a data type.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileStore":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileStore"}],"kind":"symbol","url":"\/documentation\/mapboxcommon\/tilestore","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore","title":"TileStore","abstract":[{"text":"TileStore manages downloads and storage for requests to tile-related API endpoints, enforcing a disk usage","type":"text"},{"text":" ","type":"text"},{"text":"quota: tiles available on disk may be deleted to make room for a new download. This interface can be used by an","type":"text"},{"text":" ","type":"text"},{"text":"app developer to set the disk quota. The rest of TileStore API is intended for native SDK consumption only.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TileStore"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileDataDomain":{"abstract":[{"type":"text","text":"Describes the tiles data domain."}],"title":"TileDataDomain","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileDataDomain"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"TileDataDomain"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileDataDomain","kind":"symbol","url":"\/documentation\/mapboxcommon\/tiledatadomain"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"abstract":[],"kind":"article","type":"topic","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","title":"TileStore APIs","url":"\/documentation\/mapboxmaps\/tilestore-apis"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"setOptionForKey:domain:value:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setOptionForKey:domain:value:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"setOptionForKey:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"key"},{"kind":"text","text":" "},{"kind":"identifier","text":"domain:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileDataDomain","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBXTileDataDomain","text":"MBXTileDataDomain"},{"kind":"text","text":") "},{"kind":"internalParam","text":"domain"},{"kind":"text","text":" "},{"kind":"identifier","text":"value:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"internalParam","text":"value"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The configuration option that should be changed. Valid keys are listed in \\c TileStoreOptions."}],"type":"paragraph"}],"name":"key"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The data type this setting should be applied for.","type":"text"}]}],"name":"domain"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The value for the configuration option, or null if it should be reset.","type":"text"}]}],"name":"value"}]},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"setOptionForKey:domain:value:","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore~1setOptionForKey(_:domain:value:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setOptionForKey:domain:value:"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore~1setOptionForKey(_:domain:value:)\/fragments"},{"op":"replace","value":"MBXTileStore","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBXTileStore"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/fragments"},{"op":"replace","value":[{"text":"MBXTileStore","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/navigatorTitle"},{"op":"replace","value":"MBXTileDataDomain","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileDataDomain\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBXTileDataDomain"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileDataDomain\/fragments"},{"op":"replace","value":[{"text":"MBXTileDataDomain","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileDataDomain\/navigatorTitle"}]}]}