{"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/logconfiguration\/registerlogwriterbackend(forlogwriter:)"]},{"paths":["\/documentation\/mapboxcommon\/logconfiguration\/registerlogwriterbackend(forlogwriter:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Sets the backend which writes the log.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogConfiguration\/registerLogWriterBackend(forLogWriter:)"},"metadata":{"role":"symbol","modules":[{"name":"MapboxCommon"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"registerLogWriterBackend","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forLogWriter"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","text":"LogWriterBackend","preciseIdentifier":"c:objc(pl)MBXLogWriterBackend"},{"kind":"text","text":")?)"}],"externalID":"c:objc(cs)MBXLogConfiguration(cm)registerLogWriterBackendForLogWriter:","navigatorTitle":[{"kind":"identifier","text":"registerLogWriterBackendForLogWriter:"}],"symbolKind":"method","title":"registerLogWriterBackend(forLogWriter:)","roleHeading":"Type Method"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"registerLogWriterBackend","kind":"identifier"},{"kind":"text","text":"("},{"text":"forLogWriter","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"logWriter","kind":"internalParam"},{"text":": (any ","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogWriterBackend","kind":"typeIdentifier","text":"LogWriterBackend","preciseIdentifier":"c:objc(pl)MBXLogWriterBackend"},{"kind":"text","text":")?)"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Backend which writes logs, if you provide null for this parameter then previously","type":"text"},{"type":"text","text":" "},{"text":"used logger backend will be replaced with Mapbox default implementation.","type":"text"}]}],"name":"logWriter"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogConfiguration"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LogConfiguration/registerLogWriterBackend(forLogWriter:)":{"navigatorTitle":[{"text":"registerLogWriterBackendForLogWriter:","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"registerLogWriterBackend","kind":"identifier"},{"kind":"text","text":"("},{"text":"forLogWriter","kind":"externalParam"},{"kind":"text","text":": (any "},{"text":"LogWriterBackend","preciseIdentifier":"c:objc(pl)MBXLogWriterBackend","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"abstract":[{"type":"text","text":"Sets the backend which writes the log."}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogConfiguration\/registerLogWriterBackend(forLogWriter:)","title":"registerLogWriterBackend(forLogWriter:)","kind":"symbol","url":"\/documentation\/mapboxcommon\/logconfiguration\/registerlogwriterbackend(forlogwriter:)","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"title":"MapboxMaps Documentation","role":"collection","url":"\/documentation\/overview","type":"topic","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Performance":{"url":"\/documentation\/mapboxmaps\/performance","title":"Performance and investigations","type":"topic","abstract":[],"kind":"article","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"title":"MapboxMaps","role":"collection","url":"\/documentation\/mapboxmaps","type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LogWriterBackend":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LogWriterBackend"}],"abstract":[{"type":"text","text":"Interface for implementing log writing backends, e.g. for using platform specific log backends or logging to a notification service."}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogWriterBackend","navigatorTitle":[{"text":"LogWriterBackend","kind":"identifier"}],"kind":"symbol","title":"LogWriterBackend","url":"\/documentation\/mapboxcommon\/logwriterbackend"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LogConfiguration":{"navigatorTitle":[{"text":"LogConfiguration","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogConfiguration","url":"\/documentation\/mapboxcommon\/logconfiguration","role":"symbol","abstract":[{"text":"Class that allows to configure Mapbox SDKs logging per application.","type":"text"}],"title":"LogConfiguration","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"LogConfiguration","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"registerLogWriterBackendForLogWriter:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"registerLogWriterBackendForLogWriter:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"registerLogWriterBackendForLogWriter:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<MBXLogWriterBackend>","preciseIdentifier":"c:Qoobjc(pl)MBXLogWriterBackend"},{"kind":"text","text":") "},{"text":"logWriter","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"logWriter","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Backend which writes logs, if you provide null for this parameter then previously"},{"type":"text","text":" "},{"text":"used logger backend will be replaced with Mapbox default implementation.","type":"text"}]}]}],"kind":"parameters"}},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogConfiguration~1registerLogWriterBackend(forLogWriter:)\/title","op":"replace","value":"registerLogWriterBackendForLogWriter:"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"registerLogWriterBackendForLogWriter:"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogConfiguration~1registerLogWriterBackend(forLogWriter:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogWriterBackend\/title","value":"MBXLogWriterBackend"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogWriterBackend\/fragments","value":[{"text":"MBXLogWriterBackend","kind":"identifier"}]},{"op":"replace","value":[{"text":"MBXLogWriterBackend","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogWriterBackend\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogConfiguration\/title","op":"replace","value":"MBXLogConfiguration"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogConfiguration\/fragments","value":[{"kind":"identifier","text":"MBXLogConfiguration"}],"op":"replace"},{"value":[{"text":"MBXLogConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}