{"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/mapboxmaps\/offlineregionerror\/init(type:message:isfatal:retryafter:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/offlineregionerror\/init(type:message:isfatal:retryafter:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionError"]]},"metadata":{"roleHeading":"Initializer","modules":[{"name":"MapboxMaps"}],"role":"symbol","navigatorTitle":[{"text":"initWithType:message:isFatal:retryAfter:","kind":"identifier"}],"platforms":[],"symbolKind":"init","title":"init(type:message:isFatal:retryAfter:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@MBMOfflineRegionErrorType","text":"OfflineRegionErrorType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"message"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"isFatal","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"retryAfter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"text":"?)","kind":"text"}],"externalID":"c:objc(cs)MBMOfflineRegionError(im)initWithType:message:isFatal:retryAfter:"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"type"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionErrorType","preciseIdentifier":"c:@E@MBMOfflineRegionErrorType","text":"OfflineRegionErrorType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"isFatal","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"text":"retryAfter","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"kind":"text","text":"?)"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionError\/init(type:message:isFatal:retryAfter:)"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionError":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionError","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OfflineRegionError","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OfflineRegionError"}],"type":"topic","deprecated":true,"abstract":[{"text":"Describes an offline request response error.","type":"text"}],"url":"\/documentation\/mapboxmaps\/offlineregionerror","title":"OfflineRegionError"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","title":"MapboxMaps","kind":"symbol","url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionError/init(type:message:isFatal:retryAfter:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionError\/init(type:message:isFatal:retryAfter:)","deprecated":true,"navigatorTitle":[{"text":"initWithType:message:isFatal:retryAfter:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"text":"OfflineRegionErrorType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMOfflineRegionErrorType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"isFatal"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"retryAfter"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"text":"?)","kind":"text"}],"abstract":[],"title":"init(type:message:isFatal:retryAfter:)","kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/offlineregionerror\/init(type:message:isfatal:retryafter:)","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","title":"MapboxMaps Documentation","kind":"article","url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMaps":{"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","role":"collectionGroup","type":"topic","abstract":[{"type":"text","text":"Maps rendering SDK also known as GL-Native"}],"url":"\/documentation\/mapboxmaps\/coremaps","title":"Core Maps API"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Offline":{"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","role":"collectionGroup","type":"topic","abstract":[],"url":"\/documentation\/mapboxmaps\/offline","title":"Offline Support"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionErrorType":{"title":"OfflineRegionErrorType","url":"\/documentation\/mapboxmaps\/offlineregionerrortype","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"OfflineRegionErrorType","kind":"identifier"}],"abstract":[{"text":"Describes the reason for an offline request response error.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionErrorType","deprecated":true,"type":"topic","navigatorTitle":[{"text":"OfflineRegionErrorType","kind":"identifier"}],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"initWithType:message:isFatal:retryAfter:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithType:message:isFatal:retryAfter:"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithType:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionErrorType","preciseIdentifier":"c:@E@MBMOfflineRegionErrorType","text":"MBMOfflineRegionErrorType","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"type","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"message:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"message"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isFatal:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"text":"isFatal","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"retryAfter:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSDate","preciseIdentifier":"c:objc(cs)NSDate"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"retryAfter"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MBMOfflineRegionError","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionError\/title","op":"replace"},{"value":[{"text":"MBMOfflineRegionError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionError\/fragments"},{"value":[{"kind":"identifier","text":"MBMOfflineRegionError"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionError\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionError~1init(type:message:isFatal:retryAfter:)\/title","value":"initWithType:message:isFatal:retryAfter:"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionError~1init(type:message:isFatal:retryAfter:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithType:message:isFatal:retryAfter:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionErrorType\/title","value":"MBMOfflineRegionErrorType"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionErrorType\/fragments","value":[{"kind":"identifier","text":"MBMOfflineRegionErrorType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionErrorType\/navigatorTitle","value":[{"text":"MBMOfflineRegionErrorType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}