{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMapsInternal"]]},"topicSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackError-swift.class\/message"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"seeAlsoSections":[{"anchor":"Symbols","title":"Symbols","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapRecorder","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeatureExtensionValue","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Size","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestErrorType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapLoadingErrorTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRenderModeTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestDataSourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestErrorTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestLoadingMethodTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestPriorityTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestPriorityTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestResourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMResponseSourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMSourceDataLoadedTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStyleDataLoadedTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMTileStoreUsageModeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraChangedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GenericEventCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinishedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameStartedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequestCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceAddedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceRemovedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageMissingCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapIdleCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnusedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TransitionOptions-swift.class"]}],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"StylePackError","kind":"identifier"}],"symbolKind":"class","roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"StylePackError"}],"role":"symbol","externalID":"c:objc(cs)MBMStylePackError","modules":[{"name":"MapboxMaps"}],"title":"StylePackError"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StylePackError","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/stylepackerror-swift.class"]},{"paths":["\/documentation\/mapboxmaps\/stylepackerror-swift.class"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackError-swift.class","interfaceLanguage":"swift"},"abstract":[{"text":"Describes a style package load request error.","type":"text"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleImageMissingCallback":{"navigatorTitle":[{"kind":"identifier","text":"StyleImageMissingCallback"}],"title":"StyleImageMissingCallback","url":"\/documentation\/mapboxmaps\/styleimagemissingcallback","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StyleImageMissingCallback","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"A style needs an image that is missing from the sprite sheet. This event is"},{"type":"text","text":" "},{"type":"text","text":"emitted when the "},{"type":"codeVoice","code":"map"},{"text":" renders visible tiles, and one of the required images","type":"text"},{"type":"text","text":" "},{"type":"text","text":"is missing in the sprite sheet. The event observer has to provide the missing"},{"type":"text","text":" "},{"text":"image by calling the ","type":"text"},{"type":"codeVoice","code":"addStyleImage"},{"type":"text","text":" method."}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageMissingCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleDataLoadedCallback":{"type":"topic","title":"StyleDataLoadedCallback","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedCallback","kind":"symbol","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StyleDataLoadedCallback","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/styledataloadedcallback","abstract":[{"text":"The style data has been loaded.","type":"text"}],"navigatorTitle":[{"text":"StyleDataLoadedCallback","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMapsInternal":{"role":"collectionGroup","title":"CoreMaps - Internal","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMapsInternal","abstract":[{"type":"text","text":"Maps rendering SDK also known as GL-Native. These are for internal use only."}],"url":"\/documentation\/mapboxmaps\/coremapsinternal","kind":"article","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapRecorder":{"title":"MapRecorder","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MapRecorder","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"MapRecorder provides functions to record and replay API calls of a Map instance."},{"text":" ","type":"text"},{"type":"text","text":"These recordings can be used to debug issues which requie multiple steps to reproduce."},{"text":" ","type":"text"},{"text":"Additionaly, playbacks can be used for performance testing custom scenarios.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapRecorder","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MapRecorder"}],"url":"\/documentation\/mapboxmaps\/maprecorder"},"doc://com.mapbox.MapboxMaps/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceDataLoadedCallback":{"navigatorTitle":[{"text":"SourceDataLoadedCallback","kind":"identifier"}],"title":"SourceDataLoadedCallback","url":"\/documentation\/mapboxmaps\/sourcedataloadedcallback","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"SourceDataLoadedCallback","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The "},{"code":"SourceDataLoaded","type":"codeVoice"},{"type":"text","text":" event is emitted when source data is loaded."}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapIdleCallback":{"navigatorTitle":[{"kind":"identifier","text":"MapIdleCallback"}],"title":"MapIdleCallback","url":"\/documentation\/mapboxmaps\/mapidlecallback","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"MapIdleCallback","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"The ","type":"text"},{"code":"map","type":"codeVoice"},{"text":" has entered the idle state. The ","type":"text"},{"code":"map","type":"codeVoice"},{"text":" is idle when there are no ongoing","type":"text"},{"type":"text","text":" "},{"text":"animations, transitions and the ","type":"text"},{"type":"codeVoice","code":"map"},{"type":"text","text":" has rendered all requested non-volatile tiles"},{"type":"text","text":" "},{"type":"text","text":"(e.g., live traffic tiles). The event will not be emitted if "},{"code":"setUserAnimationInProgress","type":"codeVoice"},{"type":"text","text":" "},{"type":"text","text":"and \/ or "},{"code":"setGestureInProgress","type":"codeVoice"},{"type":"text","text":" is set to "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapIdleCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePackError-swift.class/message":{"type":"topic","title":"message","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackError-swift.class\/message","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"message","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol","abstract":[{"type":"text","text":"An error message."}],"navigatorTitle":[{"text":"message","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/stylepackerror-swift.class\/message"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GenericEventCallback":{"type":"topic","title":"GenericEventCallback","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GenericEventCallback","kind":"symbol","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GenericEventCallback"}],"url":"\/documentation\/mapboxmaps\/genericeventcallback","abstract":[{"text":"Generic event for experimental events.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"GenericEventCallback"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderFrameStartedCallback":{"navigatorTitle":[{"text":"RenderFrameStartedCallback","kind":"identifier"}],"title":"RenderFrameStartedCallback","url":"\/documentation\/mapboxmaps\/renderframestartedcallback","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RenderFrameStartedCallback"}],"kind":"symbol","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"map"},{"type":"text","text":" started rendering a frame."}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameStartedCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResourceRequestCallback":{"navigatorTitle":[{"text":"ResourceRequestCallback","kind":"identifier"}],"title":"ResourceRequestCallback","url":"\/documentation\/mapboxmaps\/resourcerequestcallback","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ResourceRequestCallback","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"ResourceRequest"},{"type":"text","text":" event allows the application to observe resourcerequests"},{"text":" ","type":"text"},{"type":"text","text":"made by a "},{"code":"map","type":"codeVoice"},{"text":" or ","type":"text"},{"code":"map snapshotter","type":"codeVoice"},{"text":" object.","type":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequestCallback"},"doc://com.mapbox.MapboxMaps/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.mapbox.MapboxMaps/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","title":"Swift.Equatable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderFrameFinishedCallback":{"type":"topic","title":"RenderFrameFinishedCallback","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinishedCallback","kind":"symbol","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RenderFrameFinishedCallback","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/renderframefinishedcallback","abstract":[{"type":"text","text":"The "},{"code":"map","type":"codeVoice"},{"type":"text","text":" finished rendering a frame."}],"navigatorTitle":[{"text":"RenderFrameFinishedCallback","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceRemovedCallback":{"type":"topic","title":"SourceRemovedCallback","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceRemovedCallback","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"SourceRemovedCallback","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/sourceremovedcallback","abstract":[{"type":"text","text":"The source has been removed with "},{"type":"codeVoice","code":"removeStyleSource"},{"type":"text","text":" method."}],"navigatorTitle":[{"text":"SourceRemovedCallback","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRequestDataSourceTypeToString(_:)":{"navigatorTitle":[{"text":"MBMRequestDataSourceTypeToString","kind":"identifier"}],"title":"MBMRequestDataSourceTypeToString(_:)","url":"\/documentation\/mapboxmaps\/mbmrequestdatasourcetypetostring(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"MBMRequestDataSourceTypeToString","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@MBMRequestDataSourceType","text":"RequestDataSourceType","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"abstract":[],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestDataSourceTypeToString(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMMapLoadingErrorTypeToString(_:)":{"navigatorTitle":[{"text":"MBMMapLoadingErrorTypeToString","kind":"identifier"}],"title":"MBMMapLoadingErrorTypeToString(_:)","url":"\/documentation\/mapboxmaps\/mbmmaploadingerrortypetostring(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"MBMMapLoadingErrorTypeToString","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@MBMMapLoadingErrorType","text":"MapLoadingErrorType","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"kind":"symbol","abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapLoadingErrorTypeToString(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleLoadedCallback":{"navigatorTitle":[{"text":"StyleLoadedCallback","kind":"identifier"}],"title":"StyleLoadedCallback","url":"\/documentation\/mapboxmaps\/styleloadedcallback","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"StyleLoadedCallback","kind":"identifier"}],"abstract":[{"type":"text","text":"The requested style has been fully loaded, including specified sprite, and sources’ metadata."}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleLoadedCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRequestLoadingMethodTypeToString(_:)":{"navigatorTitle":[{"text":"MBMRequestLoadingMethodTypeToString","kind":"identifier"}],"title":"MBMRequestLoadingMethodTypeToString(_:)","url":"\/documentation\/mapboxmaps\/mbmrequestloadingmethodtypetostring(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBMRequestLoadingMethodTypeToString"},{"text":"(","kind":"text"},{"text":"RequestLoadingMethodType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMRequestLoadingMethodType"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"kind":"symbol","abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestLoadingMethodTypeToString(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleImageRemoveUnusedCallback":{"type":"topic","title":"StyleImageRemoveUnusedCallback","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnusedCallback","kind":"symbol","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StyleImageRemoveUnusedCallback"}],"url":"\/documentation\/mapboxmaps\/styleimageremoveunusedcallback","abstract":[{"type":"text","text":"An image requested by the "},{"type":"codeVoice","code":"map"},{"type":"text","text":" through the "},{"code":"StyleImageMissing","type":"codeVoice"},{"type":"text","text":" event is no longer"},{"type":"text","text":" "},{"type":"text","text":"needed and can be removed using the "},{"code":"removeStyleImage","type":"codeVoice"},{"type":"text","text":" method. The application can"},{"type":"text","text":" "},{"type":"text","text":"decide whether the image should be kept or removed."}],"navigatorTitle":[{"text":"StyleImageRemoveUnusedCallback","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject","title":"NSObject"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","abstract":[],"kind":"article","role":"collection","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceAddedCallback":{"navigatorTitle":[{"text":"SourceAddedCallback","kind":"identifier"}],"title":"SourceAddedCallback","url":"\/documentation\/mapboxmaps\/sourceaddedcallback","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"SourceAddedCallback","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The source has been added with "},{"type":"codeVoice","code":"addStyleSource"},{"text":" method.","type":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceAddedCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraChangedCallback":{"type":"topic","title":"CameraChangedCallback","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraChangedCallback","kind":"symbol","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"CameraChangedCallback","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/camerachangedcallback","abstract":[{"type":"text","text":"This event is emitted whenever the visible viewport changes its size"},{"type":"text","text":" "},{"type":"text","text":"due to the invocation of the "},{"type":"codeVoice","code":"setSize"},{"type":"text","text":" and "},{"code":"setBounds","type":"codeVoice"},{"type":"text","text":" methods or when"},{"type":"text","text":" "},{"type":"text","text":"the camera is modified by calling camera methods. The event is emitted"},{"type":"text","text":" "},{"type":"text","text":"synchronously so that an updated camera state can be fetched immediately."}],"navigatorTitle":[{"text":"CameraChangedCallback","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMTileStoreUsageModeToString(_:)":{"type":"topic","title":"MBMTileStoreUsageModeToString(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMTileStoreUsageModeToString(_:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBMTileStoreUsageModeToString","kind":"identifier"},{"text":"(","kind":"text"},{"text":"TileStoreUsageMode","preciseIdentifier":"c:@E@MBMTileStoreUsageMode","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"!","kind":"text"}],"url":"\/documentation\/mapboxmaps\/mbmtilestoreusagemodetostring(_:)","abstract":[],"navigatorTitle":[{"text":"MBMTileStoreUsageModeToString","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoadingErrorCallback":{"navigatorTitle":[{"kind":"identifier","text":"MapLoadingErrorCallback"}],"title":"MapLoadingErrorCallback","url":"\/documentation\/mapboxmaps\/maploadingerrorcallback","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapLoadingErrorCallback","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Describes an error that has occurred while loading the "},{"type":"codeVoice","code":"map"},{"type":"text","text":"."}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRequestErrorTypeToString(_:)":{"type":"topic","title":"MBMRequestErrorTypeToString(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestErrorTypeToString(_:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"MBMRequestErrorTypeToString","kind":"identifier"},{"kind":"text","text":"("},{"text":"RequestErrorType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMRequestErrorType"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"url":"\/documentation\/mapboxmaps\/mbmrequesterrortypetostring(_:)","abstract":[],"navigatorTitle":[{"text":"MBMRequestErrorTypeToString","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestErrorType":{"url":"\/documentation\/mapboxmaps\/requesterrortype","title":"RequestErrorType","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RequestErrorType"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"RequestErrorType","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The enumeration defines the error type that may occur during a resource request."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestErrorType"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMStyleDataLoadedTypeToString(_:)":{"navigatorTitle":[{"text":"MBMStyleDataLoadedTypeToString","kind":"identifier"}],"title":"MBMStyleDataLoadedTypeToString(_:)","url":"\/documentation\/mapboxmaps\/mbmstyledataloadedtypetostring(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"MBMStyleDataLoadedTypeToString","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"StyleDataLoadedType","preciseIdentifier":"c:@E@MBMStyleDataLoadedType"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"kind":"symbol","abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStyleDataLoadedTypeToString(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoadedCallback":{"type":"topic","title":"MapLoadedCallback","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadedCallback","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapLoadedCallback"}],"url":"\/documentation\/mapboxmaps\/maploadedcallback","abstract":[{"type":"text","text":"The style has been fully loaded, and the "},{"code":"map","type":"codeVoice"},{"type":"text","text":" has rendered all visible tiles."},{"type":"text","text":" "},{"type":"text","text":"The event will be emitted only once for the current style. If it is required to"},{"type":"text","text":" "},{"type":"text","text":"continuously observe an event where all the necessary resources are loaded or rendered,"},{"text":" ","type":"text"},{"text":"please check the following events: ","type":"text"},{"code":"MapIdle","type":"codeVoice"},{"text":", ","type":"text"},{"code":"StyleDataLoaded","type":"codeVoice"},{"type":"text","text":", and "},{"code":"RenderFrameFinished","type":"codeVoice"},{"type":"text","text":"."}],"navigatorTitle":[{"text":"MapLoadedCallback","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Size":{"type":"topic","title":"Size","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Size","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Size","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/size","abstract":[{"type":"text","text":"Size type."}],"navigatorTitle":[{"text":"Size","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePackError-swift.class":{"type":"topic","title":"StylePackError","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackError-swift.class","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StylePackError","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/stylepackerror-swift.class","abstract":[{"type":"text","text":"Describes a style package load request error."}],"navigatorTitle":[{"text":"StylePackError","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRequestPriorityTypeToString(_:)":{"type":"topic","title":"MBMRequestPriorityTypeToString(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestPriorityTypeToString(_:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBMRequestPriorityTypeToString","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMRequestPriorityType","text":"RequestPriorityType"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"url":"\/documentation\/mapboxmaps\/mbmrequestprioritytypetostring(_:)","abstract":[],"navigatorTitle":[{"text":"MBMRequestPriorityTypeToString","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRenderModeTypeToString(_:)":{"type":"topic","title":"MBMRenderModeTypeToString(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRenderModeTypeToString(_:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBMRenderModeTypeToString","kind":"identifier"},{"kind":"text","text":"("},{"text":"RenderModeType","preciseIdentifier":"c:@E@MBMRenderModeType","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"!"}],"url":"\/documentation\/mapboxmaps\/mbmrendermodetypetostring(_:)","abstract":[],"navigatorTitle":[{"text":"MBMRenderModeTypeToString","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FeatureExtensionValue":{"type":"topic","title":"FeatureExtensionValue","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeatureExtensionValue","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FeatureExtensionValue","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/featureextensionvalue","abstract":[{"type":"text","text":"A value or a collection of a feature extension."}],"navigatorTitle":[{"kind":"identifier","text":"FeatureExtensionValue"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMSourceDataLoadedTypeToString(_:)":{"type":"topic","title":"MBMSourceDataLoadedTypeToString(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMSourceDataLoadedTypeToString(_:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBMSourceDataLoadedTypeToString"},{"text":"(","kind":"text"},{"text":"SourceDataLoadedType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMSourceDataLoadedType"},{"kind":"text","text":") -> "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"url":"\/documentation\/mapboxmaps\/mbmsourcedataloadedtypetostring(_:)","abstract":[],"navigatorTitle":[{"text":"MBMSourceDataLoadedTypeToString","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMResponseSourceTypeToString(_:)":{"navigatorTitle":[{"text":"MBMResponseSourceTypeToString","kind":"identifier"}],"title":"MBMResponseSourceTypeToString(_:)","url":"\/documentation\/mapboxmaps\/mbmresponsesourcetypetostring(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBMResponseSourceTypeToString","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@MBMResponseSourceType","kind":"typeIdentifier","text":"ResponseSourceType"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}],"abstract":[],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMResponseSourceTypeToString(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TransitionOptions-swift.class":{"navigatorTitle":[{"text":"TransitionOptions","kind":"identifier"}],"title":"TransitionOptions","url":"\/documentation\/mapboxmaps\/transitionoptions-swift.class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TransitionOptions","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"transition options"},{"type":"text","text":" controls timing for the interpolation between a transitionable style"},{"type":"text","text":" "},{"type":"text","text":"property’s previous value and new value. These can be used to define the style default property"},{"type":"text","text":" "},{"text":"transition behavior. Also, any transitionable style property may also have its own ","type":"text"},{"type":"codeVoice","code":"-transition"},{"text":" ","type":"text"},{"type":"text","text":"property that defines specific transition timing for that specific layer property, overriding"},{"type":"text","text":" "},{"type":"text","text":"the global transition values."}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TransitionOptions-swift.class"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRequestResourceTypeToString(_:)":{"navigatorTitle":[{"kind":"identifier","text":"MBMRequestResourceTypeToString"}],"title":"MBMRequestResourceTypeToString(_:)","url":"\/documentation\/mapboxmaps\/mbmrequestresourcetypetostring(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBMRequestResourceTypeToString","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@MBMRequestResourceType","kind":"typeIdentifier","text":"RequestResourceType"},{"kind":"text","text":") -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}],"kind":"symbol","abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestResourceTypeToString(_:)"},"doc://com.mapbox.MapboxMaps/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.mapbox.MapboxMaps/SH":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","title":"Swift.Hashable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"MBMStylePackError","op":"replace","path":"\/metadata\/title"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MBMStylePackError"}],"op":"replace"},{"value":[{"kind":"identifier","text":"MBMStylePackError"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackError-swift.class\/message"],"generated":true,"anchor":"Instance-Properties"}],"op":"replace"},{"value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"title":"Inherits From"}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":[{"generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapRecorder","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeatureExtensionValue","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Size","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestErrorType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapLoadingErrorTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRenderModeTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestDataSourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestErrorTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestLoadingMethodTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestPriorityTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestPriorityTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestResourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMResponseSourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMSourceDataLoadedTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStyleDataLoadedTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMTileStoreUsageModeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraChangedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GenericEventCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinishedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameStartedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequestCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceAddedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceRemovedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageMissingCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapIdleCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnusedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TransitionOptions-swift.class"],"anchor":"Symbols","title":"Symbols"}],"op":"replace"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"MBMStylePackError","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageMissingCallback\/title","value":"MBMStyleImageMissingCallback","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageMissingCallback\/fragments","value":[{"kind":"identifier","text":"MBMStyleImageMissingCallback"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageMissingCallback\/navigatorTitle","value":[{"kind":"identifier","text":"MBMStyleImageMissingCallback"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedCallback\/title","value":"MBMStyleDataLoadedCallback"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedCallback\/fragments","value":[{"text":"MBMStyleDataLoadedCallback","kind":"identifier"}]},{"op":"replace","value":[{"text":"MBMStyleDataLoadedCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedCallback\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapRecorder\/title","value":"MBMMapRecorder","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapRecorder\/fragments","value":[{"kind":"identifier","text":"MBMMapRecorder"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapRecorder\/navigatorTitle","op":"replace","value":[{"text":"MBMMapRecorder","kind":"identifier"}]},{"op":"replace","value":"MBMSourceDataLoadedCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedCallback\/title"},{"value":[{"kind":"identifier","text":"MBMSourceDataLoadedCallback"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedCallback\/fragments"},{"op":"replace","value":[{"text":"MBMSourceDataLoadedCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedCallback\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdleCallback\/title","value":"MBMMapIdleCallback","op":"replace"},{"value":[{"text":"MBMMapIdleCallback","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdleCallback\/fragments"},{"value":[{"text":"MBMMapIdleCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdleCallback\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackError-swift.class~1message\/title","value":"message","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackError-swift.class~1message\/fragments","value":[{"kind":"identifier","text":"message"}],"op":"replace"},{"value":"MBMGenericEventCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEventCallback\/title","op":"replace"},{"value":[{"text":"MBMGenericEventCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEventCallback\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBMGenericEventCallback"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEventCallback\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameStartedCallback\/title","value":"MBMRenderFrameStartedCallback","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBMRenderFrameStartedCallback"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameStartedCallback\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MBMRenderFrameStartedCallback"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameStartedCallback\/navigatorTitle"},{"value":"MBMResourceRequestCallback","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequestCallback\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequestCallback\/fragments","value":[{"text":"MBMResourceRequestCallback","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequestCallback\/navigatorTitle","value":[{"kind":"identifier","text":"MBMResourceRequestCallback"}]},{"value":"MBMRenderFrameFinishedCallback","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinishedCallback\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinishedCallback\/fragments","value":[{"text":"MBMRenderFrameFinishedCallback","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinishedCallback\/navigatorTitle","value":[{"text":"MBMRenderFrameFinishedCallback","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceRemovedCallback\/title","value":"MBMSourceRemovedCallback","op":"replace"},{"op":"replace","value":[{"text":"MBMSourceRemovedCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceRemovedCallback\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceRemovedCallback\/navigatorTitle","op":"replace","value":[{"text":"MBMSourceRemovedCallback","kind":"identifier"}]},{"value":"MBMRequestDataSourceTypeToString","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestDataSourceTypeToString(_:)\/title"},{"value":[{"kind":"identifier","text":"MBMRequestDataSourceTypeToString"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestDataSourceTypeToString(_:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMMapLoadingErrorTypeToString(_:)\/title","value":"MBMMapLoadingErrorTypeToString","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMMapLoadingErrorTypeToString(_:)\/fragments","value":[{"kind":"identifier","text":"MBMMapLoadingErrorTypeToString"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoadedCallback\/title","value":"MBMStyleLoadedCallback","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoadedCallback\/fragments","value":[{"text":"MBMStyleLoadedCallback","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoadedCallback\/navigatorTitle","value":[{"text":"MBMStyleLoadedCallback","kind":"identifier"}],"op":"replace"},{"value":"MBMRequestLoadingMethodTypeToString","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestLoadingMethodTypeToString(_:)\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestLoadingMethodTypeToString(_:)\/fragments","value":[{"text":"MBMRequestLoadingMethodTypeToString","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnusedCallback\/title","value":"MBMStyleImageRemoveUnusedCallback","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnusedCallback\/fragments","value":[{"text":"MBMStyleImageRemoveUnusedCallback","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnusedCallback\/navigatorTitle","value":[{"text":"MBMStyleImageRemoveUnusedCallback","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAddedCallback\/title","value":"MBMSourceAddedCallback"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAddedCallback\/fragments","value":[{"text":"MBMSourceAddedCallback","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"MBMSourceAddedCallback"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAddedCallback\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChangedCallback\/title","value":"MBMCameraChangedCallback","op":"replace"},{"value":[{"kind":"identifier","text":"MBMCameraChangedCallback"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChangedCallback\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBMCameraChangedCallback"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChangedCallback\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMTileStoreUsageModeToString(_:)\/title","value":"MBMTileStoreUsageModeToString","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMTileStoreUsageModeToString(_:)\/fragments","value":[{"kind":"identifier","text":"MBMTileStoreUsageModeToString"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorCallback\/title","value":"MBMMapLoadingErrorCallback","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorCallback\/fragments","value":[{"kind":"identifier","text":"MBMMapLoadingErrorCallback"}]},{"value":[{"text":"MBMMapLoadingErrorCallback","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorCallback\/navigatorTitle"},{"value":"MBMRequestErrorTypeToString","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestErrorTypeToString(_:)\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestErrorTypeToString(_:)\/fragments","op":"replace","value":[{"text":"MBMRequestErrorTypeToString","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestErrorType\/title","value":"MBMRequestErrorType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestErrorType\/fragments","value":[{"text":"MBMRequestErrorType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestErrorType\/navigatorTitle","value":[{"text":"MBMRequestErrorType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMStyleDataLoadedTypeToString(_:)\/title","value":"MBMStyleDataLoadedTypeToString","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBMStyleDataLoadedTypeToString"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMStyleDataLoadedTypeToString(_:)\/fragments"},{"value":"MBMMapLoadedCallback","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadedCallback\/title"},{"op":"replace","value":[{"text":"MBMMapLoadedCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadedCallback\/fragments"},{"op":"replace","value":[{"text":"MBMMapLoadedCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadedCallback\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Size\/title","value":"MBMSize","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Size\/fragments","op":"replace","value":[{"text":"MBMSize","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Size\/navigatorTitle","value":[{"kind":"identifier","text":"MBMSize"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackError-swift.class\/title","value":"MBMStylePackError","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackError-swift.class\/fragments","value":[{"text":"MBMStylePackError","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackError-swift.class\/navigatorTitle","value":[{"text":"MBMStylePackError","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"MBMRequestPriorityTypeToString","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestPriorityTypeToString(_:)\/title"},{"value":[{"text":"MBMRequestPriorityTypeToString","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestPriorityTypeToString(_:)\/fragments"},{"value":"MBMRenderModeTypeToString","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRenderModeTypeToString(_:)\/title"},{"value":[{"text":"MBMRenderModeTypeToString","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRenderModeTypeToString(_:)\/fragments"},{"op":"replace","value":"MBMFeatureExtensionValue","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeatureExtensionValue\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeatureExtensionValue\/fragments","value":[{"text":"MBMFeatureExtensionValue","kind":"identifier"}],"op":"replace"},{"value":[{"text":"MBMFeatureExtensionValue","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeatureExtensionValue\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMSourceDataLoadedTypeToString(_:)\/title","value":"MBMSourceDataLoadedTypeToString"},{"op":"replace","value":[{"text":"MBMSourceDataLoadedTypeToString","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMSourceDataLoadedTypeToString(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMResponseSourceTypeToString(_:)\/title","op":"replace","value":"MBMResponseSourceTypeToString"},{"op":"replace","value":[{"text":"MBMResponseSourceTypeToString","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMResponseSourceTypeToString(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TransitionOptions-swift.class\/title","value":"MBMTransitionOptions"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TransitionOptions-swift.class\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMTransitionOptions"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TransitionOptions-swift.class\/navigatorTitle","op":"replace","value":[{"text":"MBMTransitionOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestResourceTypeToString(_:)\/title","op":"replace","value":"MBMRequestResourceTypeToString"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestResourceTypeToString(_:)\/fragments","value":[{"kind":"identifier","text":"MBMRequestResourceTypeToString"}],"op":"replace"}]}]}