{"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"The limit on the number of Mapbox tiles stored for offline regions has been reached."}],"sections":[],"metadata":{"platforms":[],"role":"symbol","modules":[{"name":"MapboxMaps"}],"externalID":"c:@E@MBMOfflineRegionErrorType@MBMOfflineRegionErrorTypeTileCountLimitExceeded","roleHeading":"Case","symbolKind":"case","title":"OfflineRegionErrorType.tileCountLimitExceeded","navigatorTitle":[{"text":"MBMOfflineRegionErrorTypeTileCountLimitExceeded","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tileCountLimitExceeded","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/offlineregionerrortype\/tilecountlimitexceeded"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/offlineregionerrortype\/tilecountlimitexceeded"]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionErrorType\/tileCountLimitExceeded","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionErrorType"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"tileCountLimitExceeded","kind":"identifier"}]}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","abstract":[],"kind":"article","url":"\/documentation\/overview","type":"topic","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Offline":{"url":"\/documentation\/mapboxmaps\/offline","kind":"article","role":"collectionGroup","title":"Offline Support","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","abstract":[],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionErrorType/tileCountLimitExceeded":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionErrorType\/tileCountLimitExceeded","navigatorTitle":[{"text":"MBMOfflineRegionErrorTypeTileCountLimitExceeded","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxmaps\/offlineregionerrortype\/tilecountlimitexceeded","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tileCountLimitExceeded","kind":"identifier"}],"role":"symbol","deprecated":true,"title":"OfflineRegionErrorType.tileCountLimitExceeded","abstract":[{"type":"text","text":"The limit on the number of Mapbox tiles stored for offline regions has been reached."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionErrorType":{"url":"\/documentation\/mapboxmaps\/offlineregionerrortype","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionErrorType","role":"symbol","deprecated":true,"abstract":[{"type":"text","text":"Describes the reason for an offline request response error."}],"title":"OfflineRegionErrorType","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OfflineRegionErrorType","kind":"identifier"}],"navigatorTitle":[{"text":"OfflineRegionErrorType","kind":"identifier"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMaps":{"title":"Core Maps API","abstract":[{"text":"Maps rendering SDK also known as GL-Native","type":"text"}],"kind":"article","type":"topic","url":"\/documentation\/mapboxmaps\/coremaps","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","url":"\/documentation\/mapboxmaps","role":"collection","title":"MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"MBMOfflineRegionErrorTypeTileCountLimitExceeded"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMOfflineRegionErrorTypeTileCountLimitExceeded"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"MBMOfflineRegionErrorTypeTileCountLimitExceeded","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionErrorType~1tileCountLimitExceeded\/title","op":"replace","value":"MBMOfflineRegionErrorTypeTileCountLimitExceeded"},{"value":[{"text":"MBMOfflineRegionErrorTypeTileCountLimitExceeded","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionErrorType~1tileCountLimitExceeded\/fragments","op":"replace"},{"value":"MBMOfflineRegionErrorType","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionErrorType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBMOfflineRegionErrorType"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionErrorType\/fragments"},{"value":[{"text":"MBMOfflineRegionErrorType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionErrorType\/navigatorTitle","op":"replace"}]}]}