{"variants":[{"paths":["\/documentation\/mapboxmaps\/mapviewannotation\/variableanchors(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapViewAnnotation\/variableAnchors(_:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SwiftUI","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapViewAnnotation"]]},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"variableAnchors","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"variableAnchors","kind":"internalParam"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchorConfig","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMViewAnnotationAnchorConfig","text":"ViewAnnotationAnchorConfig"},{"kind":"text","text":"]) -> "},{"text":"MapViewAnnotation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapViewAnnotation","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps17MapViewAnnotationV"}]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"inlineContent":[{"type":"text","text":"The annotation will automatically pick the first best anchor position depending on position"},{"text":" ","type":"text"},{"type":"text","text":"relative to other elements on the map."}],"type":"paragraph"},{"inlineContent":[{"text":"The ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/onAnchorChanged"},{"type":"text","text":" is called when the"},{"type":"text","text":" "},{"text":"effective position is updated.","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"If not specified, the annotation will be placed in center.","type":"text"}]}],"kind":"content"}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"variableAnchors"},{"kind":"text","text":"(["},{"preciseIdentifier":"c:objc(cs)MBMViewAnnotationAnchorConfig","kind":"typeIdentifier","text":"ViewAnnotationAnchorConfig"},{"text":"]) -> ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps17MapViewAnnotationV","text":"MapViewAnnotation","kind":"typeIdentifier"}],"title":"variableAnchors(_:)","roleHeading":"Instance Method","externalID":"s:10MapboxMaps17MapViewAnnotationV15variableAnchorsyACSaySo07MBMViewE12AnchorConfigCGF","symbolKind":"method","role":"symbol","modules":[{"name":"MapboxMaps"}]},"abstract":[{"type":"text","text":"A list of anchor configurations available."}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SwiftUI":{"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SwiftUI","role":"collectionGroup","abstract":[],"title":"SwiftUI","url":"\/documentation\/mapboxmaps\/swiftui","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotation/onAnchorChanged":{"url":"\/documentation\/mapboxmaps\/viewannotation\/onanchorchanged","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onAnchorChanged","kind":"identifier"},{"kind":"text","text":": (("},{"preciseIdentifier":"c:objc(cs)MBMViewAnnotationAnchorConfig","text":"ViewAnnotationAnchorConfig","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"Called when "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/anchorConfig","isActive":true,"type":"reference"},{"text":" is changed.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/onAnchorChanged","title":"onAnchorChanged"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationAnchorConfig":{"kind":"symbol","abstract":[{"type":"text","text":"Represents a specific setting for a view annotation anchor."}],"role":"symbol","url":"\/documentation\/mapboxmaps\/viewannotationanchorconfig","navigatorTitle":[{"text":"ViewAnnotationAnchorConfig","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ViewAnnotationAnchorConfig","kind":"identifier"}],"type":"topic","title":"ViewAnnotationAnchorConfig","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchorConfig"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapViewAnnotation":{"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"MapViewAnnotation","kind":"identifier"}],"title":"MapViewAnnotation","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapViewAnnotation","navigatorTitle":[{"text":"MapViewAnnotation","kind":"identifier"}],"abstract":[{"text":"Displays a view annotation.","type":"text"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/mapviewannotation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapViewAnnotation/variableAnchors(_:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapViewAnnotation\/variableAnchors(_:)","abstract":[{"text":"A list of anchor configurations available.","type":"text"}],"type":"topic","url":"\/documentation\/mapboxmaps\/mapviewannotation\/variableanchors(_:)","title":"variableAnchors(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"variableAnchors","kind":"identifier"},{"text":"([","kind":"text"},{"text":"ViewAnnotationAnchorConfig","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMViewAnnotationAnchorConfig"},{"text":"]) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps17MapViewAnnotationV","text":"MapViewAnnotation"}],"role":"symbol","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","type":"topic","title":"MapboxMaps Documentation","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotation/anchorConfig":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"anchorConfig","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ViewAnnotationAnchorConfig","preciseIdentifier":"c:objc(cs)MBMViewAnnotationAnchorConfig"},{"kind":"text","text":"?"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/viewannotation\/anchorconfig","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation\/anchorConfig","title":"anchorConfig","abstract":[{"type":"text","text":"Currently selected anchor configuration."}],"role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","title":"MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","role":"collection","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchorConfig\/title","value":"MBMViewAnnotationAnchorConfig","op":"replace"},{"value":[{"text":"MBMViewAnnotationAnchorConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchorConfig\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchorConfig\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMViewAnnotationAnchorConfig"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}