{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestPriorityType\/hashValue"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/mapboxmaps\/requestprioritytype\/hashvalue"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestPriorityType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestPriorityType\/RawRepresentable-Implementations"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"modules":[{"name":"MapboxMaps","relatedModules":["Swift"]}],"extendedModule":"Swift","externalID":"s:SYsSHRzSH8RawValueSYRpzrlE04hashB0Sivp::SYNTHESIZED::c:@E@MBMRequestPriorityType","conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":"."}]},"title":"hashValue","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"symbolKind":"property","role":"symbol"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.hashValue"},{"type":"text","text":"."}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"abstract":[{"type":"text","text":"The simplified diagram of the events emitted by the map is displayed below."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","title":"Map events","role":"collectionGroup","kind":"article","url":"\/documentation\/mapboxmaps\/events","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","type":"topic","abstract":[],"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestPriorityType/hashValue":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestPriorityType\/hashValue","kind":"symbol","url":"\/documentation\/mapboxmaps\/requestprioritytype\/hashvalue","conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}]},"title":"hashValue","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestPriorityType":{"kind":"symbol","title":"RequestPriorityType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RequestPriorityType","kind":"identifier"}],"abstract":[{"text":"The enumeration defines the priority of a resource request.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"RequestPriorityType","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/requestprioritytype","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestPriorityType","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestPriorityType/RawRepresentable-Implementations":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestPriorityType\/RawRepresentable-Implementations","kind":"article","url":"\/documentation\/mapboxmaps\/requestprioritytype\/rawrepresentable-implementations","title":"RawRepresentable Implementations","role":"collectionGroup","type":"topic","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","kind":"symbol","type":"topic","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestPriorityType\/title","value":"MBMRequestPriorityType"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestPriorityType\/fragments","value":[{"kind":"identifier","text":"MBMRequestPriorityType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestPriorityType\/navigatorTitle","value":[{"kind":"identifier","text":"MBMRequestPriorityType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}