{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"customRasterSourceTileRenderer"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customRasterSourceTileRenderer","kind":"identifier"}],"externalID":"c:@E@MBMCustomRasterSourceClientType@MBMCustomRasterSourceClientTypeCustomRasterSourceTileRenderer","roleHeading":"Case","role":"symbol","modules":[{"name":"MapboxMaps"}],"title":"CustomRasterSourceClientType.customRasterSourceTileRenderer","symbolKind":"case","navigatorTitle":[{"text":"MBMCustomRasterSourceClientTypeCustomRasterSourceTileRenderer","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/mapboxmaps\/customrastersourceclienttype\/customrastersourcetilerenderer"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/customrastersourceclienttype\/customrastersourcetilerenderer"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType\/customRasterSourceTileRenderer","interfaceLanguage":"swift"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceClientType/customRasterSourceTileRenderer":{"navigatorTitle":[{"text":"MBMCustomRasterSourceClientTypeCustomRasterSourceTileRenderer","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType\/customRasterSourceTileRenderer","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"customRasterSourceTileRenderer","kind":"identifier"}],"title":"CustomRasterSourceClientType.customRasterSourceTileRenderer","type":"topic","url":"\/documentation\/mapboxmaps\/customrastersourceclienttype\/customrastersourcetilerenderer","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"url":"\/documentation\/mapboxmaps","role":"collection","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","abstract":[],"url":"\/documentation\/overview","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Sources":{"abstract":[],"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources","type":"topic","title":"Sources","url":"\/documentation\/mapboxmaps\/sources","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceClientType":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomRasterSourceClientType"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/customrastersourceclienttype","navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceClientType"}],"title":"CustomRasterSourceClientType","type":"topic","abstract":[],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MBMCustomRasterSourceClientTypeCustomRasterSourceTileRenderer"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"kind":"identifier","text":"MBMCustomRasterSourceClientTypeCustomRasterSourceTileRenderer"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"identifier","text":"MBMCustomRasterSourceClientTypeCustomRasterSourceTileRenderer"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MBMCustomRasterSourceClientTypeCustomRasterSourceTileRenderer","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType~1customRasterSourceTileRenderer\/title"},{"value":[{"text":"MBMCustomRasterSourceClientTypeCustomRasterSourceTileRenderer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType~1customRasterSourceTileRenderer\/fragments"},{"value":"MBMCustomRasterSourceClientType","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType\/title"},{"value":[{"kind":"identifier","text":"MBMCustomRasterSourceClientType"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType\/fragments"},{"value":[{"text":"MBMCustomRasterSourceClientType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}