{"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location\/bearing","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"s:So11MBXLocationC12MapboxCommonE7bearingSdSgvp","symbolKind":"property","role":"symbol","title":"bearing","extendedModule":"MapboxCommon","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bearing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationDirection","preciseIdentifier":"c:@T@CLLocationDirection"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property","modules":[{"name":"MapboxCommon"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bearing","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CLLocationDirection","kind":"typeIdentifier","preciseIdentifier":"c:@T@CLLocationDirection"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"aside","style":"note","name":"Note","content":[{"inlineContent":[{"text":"This is also known as ","type":"text"},{"code":"course","type":"codeVoice"},{"text":" in CLLocation.","type":"text"}],"type":"paragraph"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/location\/bearing"]}],"sections":[],"abstract":[{"text":"The GNSS bearing, in degrees.","type":"text"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Location-APIs":{"role":"collectionGroup","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","url":"\/documentation\/mapboxmaps\/location-apis","type":"topic","title":"Location","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","url":"\/documentation\/mapboxmaps","title":"MapboxMaps","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Location":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Location information."}],"title":"Location","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Location"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location","url":"\/documentation\/mapboxcommon\/location","navigatorTitle":[{"kind":"identifier","text":"Location"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Location/bearing":{"title":"bearing","url":"\/documentation\/mapboxcommon\/location\/bearing","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location\/bearing","abstract":[{"type":"text","text":"The GNSS bearing, in degrees."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bearing","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CLLocationDirection","kind":"typeIdentifier","preciseIdentifier":"c:@T@CLLocationDirection"},{"text":"?","kind":"text"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","role":"collection","type":"topic","abstract":[],"title":"MapboxMaps Documentation","kind":"article"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/title","value":"MBXLocation"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/fragments","value":[{"text":"MBXLocation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/navigatorTitle","value":[{"text":"MBXLocation","kind":"identifier"}]}]}]}