{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestDataSourceType"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"roleHeading":"Case","externalID":"c:@E@MBMRequestDataSourceType@MBMRequestDataSourceTypeDatabase","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"database","kind":"identifier"}],"title":"RequestDataSourceType.database","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"MBMRequestDataSourceTypeDatabase"}],"modules":[{"name":"MapboxMaps"}],"role":"symbol"},"sections":[],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestDataSourceType\/database","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"database","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/mapboxmaps\/requestdatasourcetype\/database"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/requestdatasourcetype\/database"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"The resource is requested from the database."}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestDataSourceType/database":{"title":"RequestDataSourceType.database","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"database"}],"abstract":[{"text":"The resource is requested from the database.","type":"text"}],"type":"topic","url":"\/documentation\/mapboxmaps\/requestdatasourcetype\/database","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestDataSourceType\/database","navigatorTitle":[{"kind":"identifier","text":"MBMRequestDataSourceTypeDatabase"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"kind":"article","url":"\/documentation\/mapboxmaps\/events","abstract":[{"type":"text","text":"The simplified diagram of the events emitted by the map is displayed below."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","type":"topic","title":"Map events","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"title":"MapboxMaps Documentation","type":"topic","kind":"article","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestDataSourceType":{"abstract":[{"type":"text","text":"The enumeration defines the type of data source."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestDataSourceType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"RequestDataSourceType"}],"navigatorTitle":[{"kind":"identifier","text":"RequestDataSourceType"}],"role":"symbol","type":"topic","kind":"symbol","title":"RequestDataSourceType","url":"\/documentation\/mapboxmaps\/requestdatasourcetype"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","url":"\/documentation\/mapboxmaps","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"MBMRequestDataSourceTypeDatabase","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"MBMRequestDataSourceTypeDatabase"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"MBMRequestDataSourceTypeDatabase"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"MBMRequestDataSourceTypeDatabase","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestDataSourceType~1database\/title","op":"replace"},{"value":[{"text":"MBMRequestDataSourceTypeDatabase","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestDataSourceType~1database\/fragments","op":"replace"},{"value":"MBMRequestDataSourceType","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestDataSourceType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MBMRequestDataSourceType"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestDataSourceType\/fragments","op":"replace"},{"value":[{"text":"MBMRequestDataSourceType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestDataSourceType\/navigatorTitle","op":"replace"}]}]}