{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onSourceDataLoaded"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap"],["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/MapboxMapProtocol-Implementations"]]},"sections":[],"metadata":{"modules":[{"name":"MapboxMaps"}],"roleHeading":"Instance Property","title":"onSourceDataLoaded","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSourceDataLoaded"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Signal","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"SourceDataLoaded","preciseIdentifier":"c:objc(cs)MBMSourceDataLoaded"},{"kind":"text","text":">"}],"extendedModule":"MapboxMaps","role":"symbol","symbolKind":"property","externalID":"s:10MapboxMaps0A3MapC18onSourceDataLoadedAA6SignalVySo09MBMSourcefG0CGvp"},"abstract":[{"type":"text","text":"A source data has been loaded."},{"type":"text","text":" "},{"type":"text","text":"Event may be emitted synchronously in cases when source’s metadata is available when source is added to the style."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"seeAlsoSections":[{"title":"Map events","generated":true,"anchor":"Map-events","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onMapLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onMapLoadingError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleDataLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onCameraChanged","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onMapIdle","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onSourceAdded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onSourceRemoved","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleImageMissing","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleImageRemoveUnused","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onRenderFrameStarted","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onRenderFrameFinished","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onResourceRequest"]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/mapboxmap\/onsourcedataloaded"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onSourceDataLoaded","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Signal","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Signal","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"text":"<","kind":"text"},{"text":"SourceDataLoaded","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoaded","preciseIdentifier":"c:objc(cs)MBMSourceDataLoaded"},{"text":"> { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"inlineContent":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"dataID"},{"text":" property defines the source id.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"The ","type":"text"},{"code":"type","type":"codeVoice"},{"text":" property defines if source’s metadata (e.g., TileJSON) or tile has been loaded. The property of ","type":"text"},{"code":"metadata","type":"codeVoice"},{"text":" ","type":"text"},{"text":"value might be useful to identify when particular source’s metadata is loaded, thus all source’s properties are","type":"text"},{"text":" ","type":"text"},{"text":"readable and can be updated before map will start requesting data to be rendered.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"loaded"},{"type":"text","text":" property will be set to "},{"type":"codeVoice","code":"true"},{"type":"text","text":" if all source’s data required for visible viewport of the map, are loaded."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"tileID"},{"type":"text","text":" property defines the tile id if the "},{"type":"codeVoice","code":"type"},{"type":"text","text":" field equals "},{"type":"codeVoice","code":"tile"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"dataID"},{"type":"text","text":" property will be returned if it has been set for this source."}],"type":"paragraph"}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/addImage(_:id:sdf:contentInsets:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addImage(_:id:sdf:contentInsets:)","title":"addImage(_:id:sdf:contentInsets:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"id","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"sdf","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"contentInsets","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIEdgeInsets","preciseIdentifier":"c:@S@UIEdgeInsets","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"url":"\/documentation\/mapboxmaps\/stylemanager\/addimage(_:id:sdf:contentinsets:)","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Adds an image to be used in the style."}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/MapboxMapProtocol-Implementations":{"url":"\/documentation\/mapboxmaps\/mapboxmap\/mapboxmapprotocol-implementations","role":"collectionGroup","type":"topic","title":"MapboxMapProtocol Implementations","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/MapboxMapProtocol-Implementations","abstract":[],"kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onRenderFrameFinished":{"type":"topic","title":"onRenderFrameFinished","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onRenderFrameFinished","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Signal","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"text":"<","kind":"text"},{"text":"RenderFrameFinished","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMRenderFrameFinished"},{"text":">","kind":"text"}],"abstract":[{"type":"text","text":"The map finished rendering a frame."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"renderMode"},{"type":"text","text":" property tells whether the map has all data ("},{"type":"codeVoice","code":"full"},{"type":"text","text":") required to render the visible viewport."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"needsRepaint"},{"type":"text","text":" property provides information about ongoing transitions that trigger map repaint."},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"type":"codeVoice","code":"placementChanged"},{"text":" property tells if the symbol placement has been changed in the visible viewport.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onRenderFrameFinished","kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/onrenderframefinished"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"abstract":[],"type":"topic","kind":"article","title":"MapboxMap","url":"\/documentation\/mapboxmaps\/mapboxmap-apis","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onResourceRequest":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onResourceRequest","url":"\/documentation\/mapboxmaps\/mapboxmap\/onresourcerequest","role":"symbol","abstract":[{"text":"The ","type":"text"},{"code":"ResourceRequest","type":"codeVoice"},{"text":" event allows client to observe resource requests made by a","type":"text"},{"text":" ","type":"text"},{"text":"map or snapshotter.","type":"text"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onResourceRequest","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Signal","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"text":"<","kind":"text"},{"text":"ResourceRequest","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMResourceRequest"},{"text":">","kind":"text"}],"type":"topic","title":"onResourceRequest"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/endGesture()":{"abstract":[{"text":"If implementing a custom gesture, call this method when the gesture ends.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/endGesture()","type":"topic","url":"\/documentation\/mapboxmaps\/mapboxmap\/endgesture()","title":"endGesture()","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"endGesture"},{"kind":"text","text":"()"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/addSource(_:dataId:)":{"kind":"symbol","abstract":[{"type":"text","text":"Adds a "},{"type":"codeVoice","code":"source"},{"type":"text","text":" to the map"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addSource(_:dataId:)","url":"\/documentation\/mapboxmaps\/stylemanager\/addsource(_:dataid:)","role":"symbol","title":"addSource(_:dataId:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addSource","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"Source","preciseIdentifier":"s:10MapboxMaps6SourceP","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"dataId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onMapLoadingError":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMapLoadingError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV","text":"Signal"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMMapLoadingError","text":"MapLoadingError"},{"kind":"text","text":">"}],"abstract":[{"text":"An error that has occurred while loading the Map. The ","type":"text"},{"code":"type","type":"codeVoice"},{"text":" property defines what resource could","type":"text"},{"text":" ","type":"text"},{"text":"not be loaded and the ","type":"text"},{"code":"message","type":"codeVoice"},{"text":" property will contain a descriptive error message.","type":"text"},{"text":" ","type":"text"},{"text":"In case of ","type":"text"},{"code":"source","type":"codeVoice"},{"text":" or ","type":"text"},{"code":"tile","type":"codeVoice"},{"text":" loading errors, ","type":"text"},{"code":"sourceID","type":"codeVoice"},{"text":" or ","type":"text"},{"code":"tileID","type":"codeVoice"},{"text":" will contain the identifier of the source failing.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onMapLoadingError","url":"\/documentation\/mapboxmaps\/mapboxmap\/onmaploadingerror","title":"onMapLoadingError","role":"symbol","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Signal":{"kind":"symbol","abstract":[{"type":"text","text":"Signal is a typed interface for observing arbitrary values over time."}],"title":"Signal","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Signal","url":"\/documentation\/mapboxmaps\/signal","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Signal"}],"navigatorTitle":[{"kind":"identifier","text":"Signal"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onSourceDataLoaded":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onSourceDataLoaded","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onSourceDataLoaded","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Signal","preciseIdentifier":"s:10MapboxMaps6SignalV","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"SourceDataLoaded","preciseIdentifier":"c:objc(cs)MBMSourceDataLoaded","kind":"typeIdentifier"},{"text":">","kind":"text"}],"abstract":[{"type":"text","text":"A source data has been loaded."},{"type":"text","text":" "},{"type":"text","text":"Event may be emitted synchronously in cases when source’s metadata is available when source is added to the style."}],"url":"\/documentation\/mapboxmaps\/mapboxmap\/onsourcedataloaded","type":"topic","title":"onSourceDataLoaded"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onStyleDataLoaded":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/onstyledataloaded","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleDataLoaded","abstract":[{"type":"text","text":"The requested style data has been loaded. The "},{"code":"type","type":"codeVoice"},{"type":"text","text":" property defines what kind of style data has been loaded."},{"type":"text","text":" "},{"type":"text","text":"Event may be emitted synchronously, for example, when "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/loadStyle(_:transition:completion:)-1ilz1","type":"reference","isActive":true},{"type":"text","text":" is used to load style."}],"type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onStyleDataLoaded","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Signal","preciseIdentifier":"s:10MapboxMaps6SignalV","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"StyleDataLoaded","preciseIdentifier":"c:objc(cs)MBMStyleDataLoaded","kind":"typeIdentifier"},{"text":">","kind":"text"}],"title":"onStyleDataLoaded"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/beginAnimation()":{"role":"symbol","kind":"symbol","abstract":[{"text":"If implementing a custom animation mechanism, call this method when the animation begins.","type":"text"}],"title":"beginAnimation()","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/beginAnimation()","url":"\/documentation\/mapboxmaps\/mapboxmap\/beginanimation()","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"beginAnimation"},{"kind":"text","text":"()"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onMapIdle":{"role":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/onmapidle","abstract":[{"type":"text","text":"The map has entered the idle state. The map is in the idle state when there are no ongoing transitions"},{"type":"text","text":" "},{"type":"text","text":"and the map has rendered all requested non-volatile tiles. The event will not be emitted if animation is in progress (see "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/beginAnimation()"},{"type":"text","text":", "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/endAnimation()"},{"type":"text","text":")"},{"type":"text","text":" "},{"type":"text","text":"and \/ or gesture is in progress (see "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/beginGesture()"},{"type":"text","text":", "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/endGesture()"},{"type":"text","text":")."}],"kind":"symbol","title":"onMapIdle","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onMapIdle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMapIdle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV","text":"Signal"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMMapIdle","text":"MapIdle"},{"kind":"text","text":">"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onStyleLoaded":{"type":"topic","title":"onStyleLoaded","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onStyleLoaded","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Signal","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"text":"<","kind":"text"},{"text":"StyleLoaded","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMStyleLoaded"},{"text":">","kind":"text"}],"abstract":[{"type":"text","text":"The requested style has been fully loaded, including the style, specified sprite and sources’ metadata."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleLoaded","kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/onstyleloaded"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","title":"MapboxMap","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapboxMap","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"text":"Provides access to the map model, including the camera, style, observable map events,","type":"text"},{"text":" ","type":"text"},{"text":"and querying rendered features.","type":"text"}],"url":"\/documentation\/mapboxmaps\/mapboxmap","navigatorTitle":[{"text":"MapboxMap","kind":"identifier"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/removeSource(withId:)":{"type":"topic","title":"removeSource(withId:)","url":"\/documentation\/mapboxmaps\/stylemanager\/removesource(withid:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeSource"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/removeSource(withId:)","abstract":[{"text":"Removes an existing style source.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onStyleImageRemoveUnused":{"title":"onStyleImageRemoveUnused","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onStyleImageRemoveUnused","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps6SignalV","text":"Signal","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMStyleImageRemoveUnused","text":"StyleImageRemoveUnused","kind":"typeIdentifier"},{"text":">","kind":"text"}],"url":"\/documentation\/mapboxmaps\/mapboxmap\/onstyleimageremoveunused","abstract":[{"type":"text","text":"An image added to the style is no longer needed and can be removed using "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/removeImage(withId:)"},{"type":"text","text":"."}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleImageRemoveUnused"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceDataLoaded":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SourceDataLoaded"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoaded","url":"\/documentation\/mapboxmaps\/sourcedataloaded","kind":"symbol","abstract":[{"text":"The ","type":"text"},{"code":"SourceDataLoaded","type":"codeVoice"},{"text":" event is emitted when source data is loaded.","type":"text"}],"type":"topic","title":"SourceDataLoaded","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceDataLoaded"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/endAnimation()":{"abstract":[{"text":"If implementing a custom animation mechanism, call this method when the animation ends.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"endAnimation"},{"kind":"text","text":"()"}],"url":"\/documentation\/mapboxmaps\/mapboxmap\/endanimation()","kind":"symbol","title":"endAnimation()","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/endAnimation()"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onCameraChanged":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onCameraChanged"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV","text":"Signal"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMCameraChanged","text":"CameraChanged"},{"kind":"text","text":">"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onCameraChanged","url":"\/documentation\/mapboxmaps\/mapboxmap\/oncamerachanged","title":"onCameraChanged","type":"topic","abstract":[{"text":"The camera has changed. This event is emitted whenever the visible viewport","type":"text"},{"text":" ","type":"text"},{"text":"changes due to the MapView’s size changing or when the camera","type":"text"},{"text":" ","type":"text"},{"text":"is modified by calling camera methods. The event is emitted synchronously,","type":"text"},{"text":" ","type":"text"},{"text":"so that an updated camera state can be fetched immediately.","type":"text"}],"kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onSourceRemoved":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSourceRemoved"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV","text":"Signal"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMSourceRemoved","text":"SourceRemoved"},{"kind":"text","text":">"}],"title":"onSourceRemoved","abstract":[{"text":"The source has been removed with ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/removeSource(withId:)","type":"reference"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"The event is emitted synchronously, thus, ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/allSourceIdentifiers","type":"reference"},{"text":" will be","type":"text"},{"text":" ","type":"text"},{"text":"in sync when the observer receives the notification.","type":"text"}],"url":"\/documentation\/mapboxmaps\/mapboxmap\/onsourceremoved","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onSourceRemoved","kind":"symbol","type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/removeImage(withId:)":{"title":"removeImage(withId:)","url":"\/documentation\/mapboxmaps\/stylemanager\/removeimage(withid:)","type":"topic","abstract":[{"type":"text","text":"Removes an image from the style."}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/removeImage(withId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/loadStyle(_:transition:completion:)-1ilz1":{"title":"loadStyle(_:transition:completion:)","url":"\/documentation\/mapboxmaps\/mapboxmap\/loadstyle(_:transition:completion:)-1ilz1","type":"topic","abstract":[{"type":"text","text":"Loads a "},{"type":"codeVoice","code":"style"},{"type":"text","text":" from a StyleURI, calling a completion closure when the"},{"type":"text","text":" "},{"type":"text","text":"style is fully loaded or there has been an error during load."}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/loadStyle(_:transition:completion:)-1ilz1","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadStyle","kind":"identifier"},{"text":"(","kind":"text"},{"text":"StyleURI","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps8StyleURIV"},{"text":", ","kind":"text"},{"text":"transition","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TransitionOptions","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps17TransitionOptionsV"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onMapLoaded":{"kind":"symbol","abstract":[{"type":"text","text":"The style has been fully loaded, and the map has rendered all visible tiles."}],"title":"onMapLoaded","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onMapLoaded","url":"\/documentation\/mapboxmaps\/mapboxmap\/onmaploaded","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMapLoaded"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV","text":"Signal"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMMapLoaded","text":"MapLoaded"},{"kind":"text","text":">"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onSourceAdded":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onSourceAdded","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Signal","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"text":"<","kind":"text"},{"text":"SourceAdded","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMSourceAdded"},{"text":">","kind":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onSourceAdded","abstract":[{"text":"The source has been added with ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addSource(_:dataId:)","isActive":true,"type":"reference"},{"text":"  or ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addSource(withId:properties:)","isActive":true,"type":"reference"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"The event is emitted synchronously, therefore, it is possible to immediately","type":"text"},{"text":" ","type":"text"},{"text":"read added source’s properties.","type":"text"}],"title":"onSourceAdded","kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/onsourceadded"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onStyleImageMissing":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/onstyleimagemissing","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleImageMissing","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onStyleImageMissing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV","text":"Signal"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMStyleImageMissing","text":"StyleImageMissing"},{"kind":"text","text":">"}],"title":"onStyleImageMissing","abstract":[{"type":"text","text":"A style has a missing image. This event is emitted when the map renders visible tiles and"},{"type":"text","text":" "},{"type":"text","text":"one of the required images is missing in the sprite sheet. Subscriber has to provide the missing image"},{"type":"text","text":" "},{"type":"text","text":"by calling "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addImage(_:id:sdf:contentInsets:)","type":"reference","isActive":true},{"type":"text","text":"."}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/addSource(withId:properties:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addSource"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"properties"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]) "},{"kind":"keyword","text":"throws"}],"abstract":[{"text":"Adds a new style source.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addSource(withId:properties:)","role":"symbol","type":"topic","title":"addSource(withId:properties:)","url":"\/documentation\/mapboxmaps\/stylemanager\/addsource(withid:properties:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"url":"\/documentation\/mapboxmaps","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","title":"MapboxMaps","kind":"symbol","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"url":"\/documentation\/overview","kind":"article","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onRenderFrameStarted":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/onrenderframestarted","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onRenderFrameStarted","abstract":[{"text":"The map started rendering a frame.","type":"text"}],"type":"topic","title":"onRenderFrameStarted","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onRenderFrameStarted"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV","text":"Signal"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMRenderFrameStarted","text":"RenderFrameStarted"},{"kind":"text","text":">"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/allSourceIdentifiers":{"abstract":[{"type":"text","text":"The ordered list of the current style sources’ identifiers and types."}],"title":"allSourceIdentifiers","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/allSourceIdentifiers","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allSourceIdentifiers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SourceInfo","preciseIdentifier":"s:10MapboxMaps10SourceInfoV"},{"kind":"text","text":"]"}],"kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/stylemanager\/allsourceidentifiers","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/beginGesture()":{"type":"topic","title":"beginGesture()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"beginGesture"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"If implementing a custom gesture, call this method when the gesture begins."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/beginGesture()","kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/begingesture()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MBMSourceDataLoaded","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoaded\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MBMSourceDataLoaded"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoaded\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MBMSourceDataLoaded"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoaded\/navigatorTitle","op":"replace"}]}]}