{"topicSections":[{"title":"Operators","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBounds\/==(_:_:)"],"anchor":"Operators","generated":true},{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBounds\/bounds","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBounds\/maxPitch","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBounds\/maxZoom","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBounds\/minPitch","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBounds\/minZoom"]},{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBounds\/hash(into:)"]},{"anchor":"Default-Implementations","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBounds\/Equatable-Implementations"],"generated":true,"title":"Default Implementations"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"CameraBounds","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"CameraBounds","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CameraBounds"}],"modules":[{"name":"MapboxMaps"}],"symbolKind":"struct","title":"CameraBounds","role":"symbol","roleHeading":"Structure","externalID":"s:10MapboxMaps12CameraBoundsV"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs"]]},"relationshipsSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBounds","interfaceLanguage":"swift"},"seeAlsoSections":[{"title":"MapboxMap","generated":true,"anchor":"MapboxMap","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraState","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBoundsOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Projection","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBoundsZoom","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateInfo","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ContextMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapCenterAltitudeMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometry","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometryConvertible"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Holds information about camera bounds."}],"variants":[{"paths":["\/documentation\/mapboxmaps\/camerabounds"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraBounds":{"title":"CameraBounds","url":"\/documentation\/mapboxmaps\/camerabounds","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CameraBounds"}],"abstract":[{"text":"Holds information about camera bounds.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"CameraBounds","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBounds"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraOptions":{"title":"CameraOptions","url":"\/documentation\/mapboxmaps\/cameraoptions","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CameraOptions"}],"abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"CameraOptions","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraBoundsOptions":{"type":"topic","abstract":[{"type":"text","text":"Holds options to be used for setting camera bounds."}],"title":"CameraBoundsOptions","role":"symbol","navigatorTitle":[{"text":"CameraBoundsOptions","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBoundsOptions","url":"\/documentation\/mapboxmaps\/cameraboundsoptions","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CameraBoundsOptions"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateBoundsZoom":{"type":"topic","abstract":[{"text":"A coordinate bounds and zoom.","type":"text"}],"title":"CoordinateBoundsZoom","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CoordinateBoundsZoom"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBoundsZoom","url":"\/documentation\/mapboxmaps\/coordinateboundszoom","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CoordinateBoundsZoom","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraBounds/minPitch":{"title":"minPitch","type":"topic","abstract":[{"text":"The minimum allowed pitch value degrees.","type":"text"},{"text":" ","type":"text"},{"text":"Defaults to 0.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"minPitch"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBounds\/minPitch","url":"\/documentation\/mapboxmaps\/camerabounds\/minpitch"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GlyphsRasterizationMode":{"title":"GlyphsRasterizationMode","url":"\/documentation\/mapboxmaps\/glyphsrasterizationmode","type":"topic","role":"symbol","navigatorTitle":[{"text":"GlyphsRasterizationMode","kind":"identifier"}],"abstract":[{"text":"Describes glyphs rasterization modes.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GlyphsRasterizationMode"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","title":"MapboxMaps Documentation","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","role":"collection"},"doc://com.mapbox.MapboxMaps/SH":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap":{"title":"MapboxMap","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","role":"symbol","abstract":[{"text":"Provides access to the map model, including the camera, style, observable map events,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"and querying rendered features."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MapboxMap","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"MapboxMap","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/mapboxmap"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraBounds/bounds":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bounds"},{"kind":"text","text":": "},{"text":"CoordinateBounds","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMCoordinateBounds"}],"type":"topic","url":"\/documentation\/mapboxmaps\/camerabounds\/bounds","kind":"symbol","abstract":[{"text":"The latitude and longitude bounds to which the camera center are constrained.","type":"text"},{"text":" ","type":"text"},{"text":"Defaults to: Southwest: (-90, -180) and Northeast: (90, 180).","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBounds\/bounds","title":"bounds","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraBounds/==(_:_:)":{"type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBounds\/==(_:_:)","url":"\/documentation\/mapboxmaps\/camerabounds\/==(_:_:)","kind":"symbol","title":"==(_:_:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"==","kind":"identifier"},{"kind":"text","text":" "},{"text":"(","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps12CameraBoundsV","text":"CameraBounds","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps12CameraBoundsV","kind":"typeIdentifier","text":"CameraBounds"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraBounds/maxPitch":{"title":"maxPitch","abstract":[{"text":"The maximum allowed pitch value in degrees.","type":"text"},{"text":" ","type":"text"},{"text":"Defaults to 85.","type":"text"}],"url":"\/documentation\/mapboxmaps\/camerabounds\/maxpitch","type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxPitch"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBounds\/maxPitch"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateInfo":{"type":"topic","abstract":[{"text":"Represents the coordinate information returned by the ","type":"text"},{"code":"coordinateInfoForPixel","type":"codeVoice"},{"text":" or ","type":"text"},{"type":"codeVoice","code":"coordinatesInfoForPixels"},{"text":" methods.","type":"text"}],"title":"CoordinateInfo","role":"symbol","navigatorTitle":[{"text":"CoordinateInfo","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateInfo","url":"\/documentation\/mapboxmaps\/coordinateinfo","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CoordinateInfo","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraBounds/minZoom":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"minZoom"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"}],"type":"topic","url":"\/documentation\/mapboxmaps\/camerabounds\/minzoom","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBounds\/minZoom","abstract":[{"text":"The minimum zoom level, in mapbox zoom levels 0-25.5.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Defaults to 0."}],"title":"minZoom","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateBounds":{"type":"topic","abstract":[{"type":"text","text":"A rectangular area as measured on a two-dimensional map projection."}],"title":"CoordinateBounds","role":"symbol","navigatorTitle":[{"text":"CoordinateBounds","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds","url":"\/documentation\/mapboxmaps\/coordinatebounds","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CoordinateBounds","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ContextMode":{"url":"\/documentation\/mapboxmaps\/contextmode","type":"topic","title":"ContextMode","role":"symbol","navigatorTitle":[{"text":"ContextMode","kind":"identifier"}],"abstract":[{"text":"Describes the map context mode.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"We can make some optimizations if we know that the drawing context is not shared with other code."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ContextMode"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ContextMode"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Projection":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Projection","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Projection"}],"url":"\/documentation\/mapboxmaps\/projection","abstract":[{"text":"A collection of ","type":"text"},{"type":"reference","identifier":"https:\/\/en.wikipedia.org\/wiki\/Web_Mercator_projection","isActive":true},{"text":" projection methods.","type":"text"}],"type":"topic","title":"Projection","role":"symbol","navigatorTitle":[{"text":"Projection","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderedQueryGeometryConvertible":{"url":"\/documentation\/mapboxmaps\/renderedquerygeometryconvertible","type":"topic","title":"RenderedQueryGeometryConvertible","role":"symbol","navigatorTitle":[{"text":"RenderedQueryGeometryConvertible","kind":"identifier"}],"abstract":[{"text":"A convenience protocol for automatic conversion to ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometry","isActive":true},{"text":".","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"RenderedQueryGeometryConvertible","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometryConvertible"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraBounds/hash(into:)":{"title":"hash(into:)","kind":"symbol","url":"\/documentation\/mapboxmaps\/camerabounds\/hash(into:)","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBounds\/hash(into:)","abstract":[],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"into"},{"kind":"text","text":": "},{"text":"inout","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV","text":"Hasher"},{"kind":"text","text":")"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraState":{"type":"topic","abstract":[],"title":"CameraState","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CameraState"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraState","url":"\/documentation\/mapboxmaps\/camerastate","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"CameraState","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraBounds/Equatable-Implementations":{"type":"topic","url":"\/documentation\/mapboxmaps\/camerabounds\/equatable-implementations","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBounds\/Equatable-Implementations","abstract":[],"title":"Equatable Implementations","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapError":{"title":"MapError","url":"\/documentation\/mapboxmaps\/maperror","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MapError"}],"abstract":[{"text":"Type of errors thrown by the ","type":"text"},{"type":"codeVoice","code":"MapboxMap"},{"type":"text","text":" APIs."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapError"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapError"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","role":"collection","url":"\/documentation\/mapboxmaps","kind":"symbol","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapCenterAltitudeMode":{"title":"MapCenterAltitudeMode","url":"\/documentation\/mapboxmaps\/mapcenteraltitudemode","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MapCenterAltitudeMode"}],"abstract":[{"type":"text","text":"Defines how the map center point should react to terrain elevation changes."}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MapCenterAltitudeMode","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapCenterAltitudeMode"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderedQueryGeometry":{"title":"RenderedQueryGeometry","url":"\/documentation\/mapboxmaps\/renderedquerygeometry","type":"topic","role":"symbol","navigatorTitle":[{"text":"RenderedQueryGeometry","kind":"identifier"}],"abstract":[{"text":"A geometry to define a portion of screen that should be queried for rendered features.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RenderedQueryGeometry"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometry"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraBounds/maxZoom":{"title":"maxZoom","abstract":[{"type":"text","text":"The maximum zoom level, in mapbox zoom levels 0-25.5. At low zoom levels,"},{"text":" ","type":"text"},{"text":"a small set of map tiles covers a large geographical area. At higher zoom","type":"text"},{"text":" ","type":"text"},{"text":"levels, a larger number of tiles cover a smaller geographical area.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Defaults to 22."}],"url":"\/documentation\/mapboxmaps\/camerabounds\/maxzoom","type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxZoom"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBounds\/maxZoom"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"type":"topic","kind":"article","title":"MapboxMap","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","url":"\/documentation\/mapboxmaps\/mapboxmap-apis"},"https://en.wikipedia.org/wiki/Web_Mercator_projection":{"url":"https:\/\/en.wikipedia.org\/wiki\/Web_Mercator_projection","titleInlineContent":[{"type":"text","text":"Spherical Mercator"}],"identifier":"https:\/\/en.wikipedia.org\/wiki\/Web_Mercator_projection","title":"Spherical Mercator","type":"link"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBoundsZoom\/title","value":"MBMCoordinateBoundsZoom","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBoundsZoom\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMCoordinateBoundsZoom"}]},{"value":[{"kind":"identifier","text":"MBMCoordinateBoundsZoom"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBoundsZoom\/navigatorTitle","op":"replace"},{"value":"MBMGlyphsRasterizationMode","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/fragments","value":[{"text":"MBMGlyphsRasterizationMode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/navigatorTitle","value":[{"text":"MBMGlyphsRasterizationMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateInfo\/title","value":"MBMCoordinateInfo","op":"replace"},{"value":[{"text":"MBMCoordinateInfo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateInfo\/fragments"},{"op":"replace","value":[{"text":"MBMCoordinateInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateInfo\/navigatorTitle"},{"op":"replace","value":"MBMCoordinateBounds","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBMCoordinateBounds"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds\/fragments"},{"op":"replace","value":[{"text":"MBMCoordinateBounds","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds\/navigatorTitle"},{"value":"MBMContextMode","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ContextMode\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ContextMode\/fragments","op":"replace","value":[{"text":"MBMContextMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ContextMode\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMContextMode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapCenterAltitudeMode\/title","value":"MBMMapCenterAltitudeMode"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapCenterAltitudeMode\/fragments","value":[{"text":"MBMMapCenterAltitudeMode","kind":"identifier"}]},{"value":[{"text":"MBMMapCenterAltitudeMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapCenterAltitudeMode\/navigatorTitle"}]}]}