{"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClipLayerTypes\/init(rawValue:)"],"anchor":"Initializers","generated":true},{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClipLayerTypes\/rawValue"]},{"title":"Type Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClipLayerTypes\/model","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClipLayerTypes\/symbol"],"anchor":"Type-Properties","generated":true},{"generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClipLayerTypes\/Equatable-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClipLayerTypes\/RawRepresentable-Implementations"],"title":"Default Implementations","anchor":"Default-Implementations"}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Layer types that will also be removed if fallen below this clip layer."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ClipLayerTypes","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","metadata":{"navigatorTitle":[{"text":"ClipLayerTypes","kind":"identifier"}],"symbolKind":"struct","role":"symbol","roleHeading":"Structure","title":"ClipLayerTypes","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"ClipLayerTypes","kind":"identifier"}],"externalID":"s:10MapboxMaps14ClipLayerTypesV","modules":[{"name":"MapboxMaps"}]},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers"]]},"relationshipsSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/Se","doc:\/\/com.mapbox.MapboxMaps\/SE","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH","doc:\/\/com.mapbox.MapboxMaps\/SY","doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"variants":[{"paths":["\/documentation\/mapboxmaps\/cliplayertypes"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClipLayerTypes","interfaceLanguage":"swift"},"seeAlsoSections":[{"title":"Layers","anchor":"Layers","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerInfo","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/BackgroundLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CircleLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillExtrusionLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationIndicatorLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterParticleLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SkyLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderConfiguration","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerHost","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ElevationData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Slot","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SlotLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerAtPosition","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClipLayer"],"generated":true}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","role":"collection","title":"MapboxMaps","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CircleLayer":{"abstract":[{"text":"A filled circle.","type":"text"}],"type":"topic","title":"CircleLayer","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CircleLayer","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CircleLayer","url":"\/documentation\/mapboxmaps\/circlelayer","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CircleLayer"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelLayer":{"url":"\/documentation\/mapboxmaps\/modellayer","kind":"symbol","role":"symbol","tags":[{"text":"SPI","type":"spi"}],"navigatorTitle":[{"text":"ModelLayer","kind":"identifier"}],"abstract":[{"text":"A layer to render 3D Models.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"ModelLayer","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer","title":"ModelLayer","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ClipLayerTypes/model":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/cliplayertypes\/model","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"model","kind":"identifier"},{"kind":"text","text":": "},{"text":"ClipLayerTypes","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps14ClipLayerTypesV"}],"title":"model","type":"topic","abstract":[{"text":"If present the clip layer would remove all 3d model layers below it. Currently only instanced models (e.g. trees) are removed.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClipLayerTypes\/model"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerAtPosition":{"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LayerAtPosition","kind":"identifier"}],"navigatorTitle":[{"text":"LayerAtPosition","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/layeratposition","abstract":[],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerAtPosition","title":"LayerAtPosition"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SymbolLayer":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SymbolLayer"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/symbollayer","navigatorTitle":[{"kind":"identifier","text":"SymbolLayer"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolLayer","abstract":[{"text":"An icon or a text label.","type":"text"}],"title":"SymbolLayer","kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterParticleLayer":{"role":"symbol","kind":"symbol","title":"RasterParticleLayer","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterParticleLayer","url":"\/documentation\/mapboxmaps\/rasterparticlelayer","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RasterParticleLayer","kind":"identifier"}],"abstract":[{"text":"Particle animation driven by textures such as wind maps.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"RasterParticleLayer","kind":"identifier"}],"tags":[{"text":"SPI","type":"spi"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FillExtrusionLayer":{"url":"\/documentation\/mapboxmaps\/fillextrusionlayer","role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillExtrusionLayer","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FillExtrusionLayer"}],"navigatorTitle":[{"kind":"identifier","text":"FillExtrusionLayer"}],"abstract":[{"type":"text","text":"An extruded (3D) polygon."}],"title":"FillExtrusionLayer","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ElevationData":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ElevationData","kind":"identifier"}],"navigatorTitle":[{"text":"ElevationData","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/elevationdata","abstract":[{"type":"text","text":"Interface that provides access to elevation data."}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ElevationData","title":"ElevationData"},"doc://com.mapbox.MapboxMaps/Se":{"title":"Swift.Decodable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/Se"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ClipLayer":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClipLayer","abstract":[{"type":"text","text":"Layer that removes 3D content from map."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ClipLayer","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ClipLayer"}],"type":"topic","kind":"symbol","tags":[{"type":"spi","text":"SPI"}],"role":"symbol","title":"ClipLayer","url":"\/documentation\/mapboxmaps\/cliplayer"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ClipLayerTypes/rawValue":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClipLayerTypes\/rawValue","type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/cliplayertypes\/rawvalue","title":"rawValue","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rawValue","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"role":"symbol","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerRenderParameters":{"title":"CustomLayerRenderParameters","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CustomLayerRenderParameters"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters","navigatorTitle":[{"kind":"identifier","text":"CustomLayerRenderParameters"}],"kind":"symbol","abstract":[{"type":"text","text":"Parameters that define the current camera position for a "},{"code":"CustomLayerHost::render()","type":"codeVoice"},{"type":"text","text":" function."}],"url":"\/documentation\/mapboxmaps\/customlayerrenderparameters","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SlotLayer":{"navigatorTitle":[{"text":"SlotLayer","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SlotLayer","type":"topic","title":"SlotLayer","url":"\/documentation\/mapboxmaps\/slotlayer","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SlotLayer"}],"abstract":[{"type":"text","text":"Marks the position of a slot."}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ClipLayerTypes/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClipLayerTypes\/RawRepresentable-Implementations","role":"collectionGroup","abstract":[],"type":"topic","url":"\/documentation\/mapboxmaps\/cliplayertypes\/rawrepresentable-implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ClipLayerTypes/init(rawValue:)":{"type":"topic","title":"init(rawValue:)","abstract":[],"kind":"symbol","url":"\/documentation\/mapboxmaps\/cliplayertypes\/init(rawvalue:)","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClipLayerTypes\/init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ClipLayerTypes":{"title":"ClipLayerTypes","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClipLayerTypes","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ClipLayerTypes"}],"abstract":[{"text":"Layer types that will also be removed if fallen below this clip layer.","type":"text"}],"type":"topic","url":"\/documentation\/mapboxmaps\/cliplayertypes","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"ClipLayerTypes","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ClipLayerTypes/Equatable-Implementations":{"role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClipLayerTypes\/Equatable-Implementations","type":"topic","abstract":[],"title":"Equatable Implementations","kind":"article","url":"\/documentation\/mapboxmaps\/cliplayertypes\/equatable-implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Slot":{"type":"topic","url":"\/documentation\/mapboxmaps\/slot","role":"symbol","title":"Slot","navigatorTitle":[{"kind":"identifier","text":"Slot"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Slot","abstract":[{"text":"A pre-specified location in the style where layer will be added to","type":"text"},{"type":"text","text":" "},{"text":"(such as on top of existing land layers, but below all labels).","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"Slot","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LocationIndicatorLayer":{"navigatorTitle":[{"kind":"identifier","text":"LocationIndicatorLayer"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationIndicatorLayer","type":"topic","title":"LocationIndicatorLayer","url":"\/documentation\/mapboxmaps\/locationindicatorlayer","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LocationIndicatorLayer"}],"abstract":[{"type":"text","text":"Location Indicator layer."}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayer":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"CustomLayer","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/customlayer","navigatorTitle":[{"text":"CustomLayer","kind":"identifier"}],"title":"CustomLayer","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayer","tags":[{"type":"spi","text":"SPI"}],"abstract":[{"type":"text","text":"Layer with custom rendering implementation"}]},"doc://com.mapbox.MapboxMaps/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SY"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeatmapLayer":{"abstract":[{"text":"A heatmap.","type":"text"}],"url":"\/documentation\/mapboxmaps\/heatmaplayer","role":"symbol","title":"HeatmapLayer","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeatmapLayer"}],"navigatorTitle":[{"kind":"identifier","text":"HeatmapLayer"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerHost":{"navigatorTitle":[{"text":"CustomLayerHost","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxmaps\/customlayerhost","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerHost","kind":"symbol","abstract":[{"type":"text","text":"Interface for hosting a custom map style layer."}],"title":"CustomLayerHost","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomLayerHost","kind":"identifier"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SkyLayer":{"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"SkyLayer","kind":"identifier"}],"title":"SkyLayer","navigatorTitle":[{"text":"SkyLayer","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SkyLayer","abstract":[{"type":"text","text":"A spherical dome around the map that is always rendered behind all other layers."},{"text":" ","type":"text"},{"text":"Warning: As of v10.6.0, ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Atmosphere","type":"reference","isActive":true},{"type":"text","text":" is the preferred method for atmospheric styling. Sky layer is not supported by the globe projection, and will be phased out in future major release."}],"url":"\/documentation\/mapboxmaps\/skylayer","type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerType":{"abstract":[{"text":"Struct of supported Layer rendering types","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"LayerType"}],"role":"symbol","type":"topic","title":"LayerType","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LayerType","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/layertype"},"doc://com.mapbox.MapboxMaps/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"},"doc://com.mapbox.MapboxMaps/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer":{"title":"HillshadeLayer","role":"symbol","abstract":[{"text":"Client-side hillshading visualization based on DEM data. Currently, the implementation only supports Mapbox Terrain RGB and Mapzen Terrarium tiles.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer","url":"\/documentation\/mapboxmaps\/hillshadelayer","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HillshadeLayer"}],"navigatorTitle":[{"kind":"identifier","text":"HillshadeLayer"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FillLayer":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillLayer","url":"\/documentation\/mapboxmaps\/filllayer","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"FillLayer","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"FillLayer","kind":"identifier"}],"type":"topic","abstract":[{"text":"A filled polygon with an optional stroked border.","type":"text"}],"title":"FillLayer","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Atmosphere":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Atmosphere","abstract":[{"text":"A style’s fog property is a global effect that improves depth perception by fading out distant objects.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"Atmosphere","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/atmosphere","kind":"symbol","title":"Atmosphere","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Atmosphere"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerRenderConfiguration":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderConfiguration","kind":"symbol","abstract":[{"type":"text","text":"Note! This is an experimental feature. It can be changed or removed in future versions."}],"url":"\/documentation\/mapboxmaps\/customlayerrenderconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"CustomLayerRenderConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"CustomLayerRenderConfiguration","kind":"identifier"}],"role":"symbol","title":"CustomLayerRenderConfiguration"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterLayer":{"url":"\/documentation\/mapboxmaps\/rasterlayer","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterLayer","kind":"symbol","abstract":[{"type":"text","text":"Raster map textures such as satellite imagery."}],"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RasterLayer"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"RasterLayer"}],"title":"RasterLayer"},"doc://com.mapbox.MapboxMaps/SE":{"title":"Swift.Encodable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SE"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","type":"topic","kind":"article","abstract":[],"role":"collection","title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerInfo":{"navigatorTitle":[{"text":"LayerInfo","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxmaps\/layerinfo","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerInfo","kind":"symbol","abstract":[{"type":"text","text":"Information about a layer"}],"title":"LayerInfo","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LayerInfo","kind":"identifier"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ClipLayerTypes/symbol":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClipLayerTypes\/symbol","url":"\/documentation\/mapboxmaps\/cliplayertypes\/symbol","title":"symbol","type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"symbol","kind":"identifier"},{"kind":"text","text":": "},{"text":"ClipLayerTypes","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps14ClipLayerTypesV"}],"abstract":[{"type":"text","text":"If present the clip layer would remove all symbol layers below it."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LineLayer":{"kind":"symbol","abstract":[{"type":"text","text":"A stroked line."}],"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LineLayer"}],"role":"symbol","title":"LineLayer","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineLayer","navigatorTitle":[{"kind":"identifier","text":"LineLayer"}],"url":"\/documentation\/mapboxmaps\/linelayer"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layer":{"navigatorTitle":[{"text":"Layer","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxmaps\/layer","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer","kind":"symbol","abstract":[],"title":"Layer","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Layer","kind":"identifier"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layers":{"type":"topic","abstract":[],"title":"Layers","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers","url":"\/documentation\/mapboxmaps\/layers","kind":"article","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/BackgroundLayer":{"role":"symbol","abstract":[{"type":"text","text":"The background color or pattern of the map."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/BackgroundLayer","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"BackgroundLayer","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/backgroundlayer","type":"topic","navigatorTitle":[{"text":"BackgroundLayer","kind":"identifier"}],"title":"BackgroundLayer"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ElevationData\/title","value":"MBMElevationData","op":"replace"},{"value":[{"text":"MBMElevationData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ElevationData\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ElevationData\/navigatorTitle","value":[{"text":"MBMElevationData","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/title","value":"MBMCustomLayerRenderParameters","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/fragments","op":"replace","value":[{"text":"MBMCustomLayerRenderParameters","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/navigatorTitle","op":"replace","value":[{"text":"MBMCustomLayerRenderParameters","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost\/title","value":"MBMCustomLayerHost","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost\/fragments","value":[{"text":"MBMCustomLayerHost","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"MBMCustomLayerHost","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost\/navigatorTitle"},{"op":"replace","value":"MBMCustomLayerRenderConfiguration","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBMCustomLayerRenderConfiguration"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderConfiguration\/fragments"},{"value":[{"text":"MBMCustomLayerRenderConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}