{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"]]},"sections":[],"kind":"article","identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMapsInternal","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Maps rendering SDK also known as GL-Native. These are for internal use only."}],"schemaVersion":{"patch":0,"minor":3,"major":0},"topicSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapRecorder","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeatureExtensionValue","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Size","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackError-swift.class","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestErrorType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapLoadingErrorTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRenderModeTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestDataSourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestErrorTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestLoadingMethodTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestPriorityTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestPriorityTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestResourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMResponseSourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMSourceDataLoadedTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStyleDataLoadedTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMTileStoreUsageModeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraChangedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GenericEventCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinishedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameStartedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequestCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceAddedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceRemovedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageMissingCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapIdleCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnusedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TransitionOptions-swift.class"],"anchor":"Symbols","title":"Symbols"}],"metadata":{"roleHeading":"API Collection","modules":[{"name":"MapboxMaps"}],"role":"collectionGroup","title":"CoreMaps - Internal"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMMapLoadingErrorTypeToString(_:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapLoadingErrorTypeToString(_:)","kind":"symbol","title":"MBMMapLoadingErrorTypeToString(_:)","type":"topic","url":"\/documentation\/mapboxmaps\/mbmmaploadingerrortypetostring(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"MBMMapLoadingErrorTypeToString","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MapLoadingErrorType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMMapLoadingErrorType"},{"text":") -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"abstract":[],"role":"symbol","navigatorTitle":[{"text":"MBMMapLoadingErrorTypeToString","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleLoadedCallback":{"url":"\/documentation\/mapboxmaps\/styleloadedcallback","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"StyleLoadedCallback","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleLoadedCallback","abstract":[{"text":"The requested style has been fully loaded, including specified sprite, and sources’ metadata.","type":"text"}],"title":"StyleLoadedCallback","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"StyleLoadedCallback"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceRemovedCallback":{"abstract":[{"type":"text","text":"The source has been removed with "},{"type":"codeVoice","code":"removeStyleSource"},{"type":"text","text":" method."}],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"SourceRemovedCallback","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/sourceremovedcallback","role":"symbol","type":"topic","title":"SourceRemovedCallback","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceRemovedCallback","navigatorTitle":[{"kind":"identifier","text":"SourceRemovedCallback"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePackError-swift.class":{"url":"\/documentation\/mapboxmaps\/stylepackerror-swift.class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"StylePackError","kind":"identifier"}],"navigatorTitle":[{"text":"StylePackError","kind":"identifier"}],"abstract":[{"type":"text","text":"Describes a style package load request error."}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackError-swift.class","title":"StylePackError","type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceAddedCallback":{"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceAddedCallback","url":"\/documentation\/mapboxmaps\/sourceaddedcallback","title":"SourceAddedCallback","navigatorTitle":[{"text":"SourceAddedCallback","kind":"identifier"}],"abstract":[{"type":"text","text":"The source has been added with "},{"type":"codeVoice","code":"addStyleSource"},{"text":" method.","type":"text"}],"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"SourceAddedCallback","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","role":"collection","url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"title":"MapboxMaps","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMStyleDataLoadedTypeToString(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"MBMStyleDataLoadedTypeToString","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@MBMStyleDataLoadedType","kind":"typeIdentifier","text":"StyleDataLoadedType"},{"text":") -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"role":"symbol","abstract":[],"title":"MBMStyleDataLoadedTypeToString(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStyleDataLoadedTypeToString(_:)","url":"\/documentation\/mapboxmaps\/mbmstyledataloadedtypetostring(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"text":"MBMStyleDataLoadedTypeToString","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleDataLoadedCallback":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedCallback","url":"\/documentation\/mapboxmaps\/styledataloadedcallback","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"StyleDataLoadedCallback","kind":"identifier"}],"kind":"symbol","title":"StyleDataLoadedCallback","abstract":[{"type":"text","text":"The style data has been loaded."}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"StyleDataLoadedCallback","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceDataLoadedCallback":{"url":"\/documentation\/mapboxmaps\/sourcedataloadedcallback","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SourceDataLoadedCallback","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedCallback","abstract":[{"type":"text","text":"The "},{"code":"SourceDataLoaded","type":"codeVoice"},{"text":" event is emitted when source data is loaded.","type":"text"}],"title":"SourceDataLoadedCallback","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceDataLoadedCallback"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleImageMissingCallback":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageMissingCallback","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"StyleImageMissingCallback","kind":"identifier"}],"navigatorTitle":[{"text":"StyleImageMissingCallback","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"A style needs an image that is missing from the sprite sheet. This event is"},{"type":"text","text":" "},{"text":"emitted when the ","type":"text"},{"type":"codeVoice","code":"map"},{"type":"text","text":" renders visible tiles, and one of the required images"},{"text":" ","type":"text"},{"text":"is missing in the sprite sheet. The event observer has to provide the missing","type":"text"},{"type":"text","text":" "},{"type":"text","text":"image by calling the "},{"code":"addStyleImage","type":"codeVoice"},{"type":"text","text":" method."}],"url":"\/documentation\/mapboxmaps\/styleimagemissingcallback","role":"symbol","title":"StyleImageMissingCallback","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapRecorder":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapRecorder","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"MapRecorder provides functions to record and replay API calls of a Map instance."},{"type":"text","text":" "},{"text":"These recordings can be used to debug issues which requie multiple steps to reproduce.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Additionaly, playbacks can be used for performance testing custom scenarios."}],"title":"MapRecorder","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapRecorder","url":"\/documentation\/mapboxmaps\/maprecorder","kind":"symbol","type":"topic","navigatorTitle":[{"text":"MapRecorder","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMSourceDataLoadedTypeToString(_:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMSourceDataLoadedTypeToString(_:)","kind":"symbol","title":"MBMSourceDataLoadedTypeToString(_:)","type":"topic","url":"\/documentation\/mapboxmaps\/mbmsourcedataloadedtypetostring(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBMSourceDataLoadedTypeToString","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SourceDataLoadedType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMSourceDataLoadedType"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}],"abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBMSourceDataLoadedTypeToString"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRequestDataSourceTypeToString(_:)":{"url":"\/documentation\/mapboxmaps\/mbmrequestdatasourcetypetostring(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"MBMRequestDataSourceTypeToString","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@MBMRequestDataSourceType","text":"RequestDataSourceType","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"navigatorTitle":[{"text":"MBMRequestDataSourceTypeToString","kind":"identifier"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestDataSourceTypeToString(_:)","title":"MBMRequestDataSourceTypeToString(_:)","type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRequestErrorTypeToString(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBMRequestErrorTypeToString","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@MBMRequestErrorType","text":"RequestErrorType","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"role":"symbol","abstract":[],"title":"MBMRequestErrorTypeToString(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestErrorTypeToString(_:)","url":"\/documentation\/mapboxmaps\/mbmrequesterrortypetostring(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"text":"MBMRequestErrorTypeToString","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GenericEventCallback":{"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GenericEventCallback","url":"\/documentation\/mapboxmaps\/genericeventcallback","title":"GenericEventCallback","navigatorTitle":[{"text":"GenericEventCallback","kind":"identifier"}],"abstract":[{"type":"text","text":"Generic event for experimental events."}],"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GenericEventCallback"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapIdleCallback":{"navigatorTitle":[{"kind":"identifier","text":"MapIdleCallback"}],"url":"\/documentation\/mapboxmaps\/mapidlecallback","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"MapIdleCallback","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapIdleCallback","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"map"},{"type":"text","text":" has entered the idle state. The "},{"type":"codeVoice","code":"map"},{"type":"text","text":" is idle when there are no ongoing"},{"text":" ","type":"text"},{"type":"text","text":"animations, transitions and the "},{"code":"map","type":"codeVoice"},{"type":"text","text":" has rendered all requested non-volatile tiles"},{"type":"text","text":" "},{"text":"(e.g., live traffic tiles). The event will not be emitted if ","type":"text"},{"code":"setUserAnimationInProgress","type":"codeVoice"},{"text":" ","type":"text"},{"type":"text","text":"and \/ or "},{"type":"codeVoice","code":"setGestureInProgress"},{"type":"text","text":" is set to "},{"type":"codeVoice","code":"true"},{"text":".","type":"text"}],"type":"topic","role":"symbol","kind":"symbol","title":"MapIdleCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderFrameFinishedCallback":{"url":"\/documentation\/mapboxmaps\/renderframefinishedcallback","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"RenderFrameFinishedCallback","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinishedCallback","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"map"},{"type":"text","text":" finished rendering a frame."}],"title":"RenderFrameFinishedCallback","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"RenderFrameFinishedCallback","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Size":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Size","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Size type."}],"title":"Size","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Size","url":"\/documentation\/mapboxmaps\/size","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Size"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoadedCallback":{"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadedCallback","url":"\/documentation\/mapboxmaps\/maploadedcallback","title":"MapLoadedCallback","navigatorTitle":[{"text":"MapLoadedCallback","kind":"identifier"}],"abstract":[{"type":"text","text":"The style has been fully loaded, and the "},{"code":"map","type":"codeVoice"},{"type":"text","text":" has rendered all visible tiles."},{"type":"text","text":" "},{"text":"The event will be emitted only once for the current style. If it is required to","type":"text"},{"text":" ","type":"text"},{"text":"continuously observe an event where all the necessary resources are loaded or rendered,","type":"text"},{"text":" ","type":"text"},{"text":"please check the following events: ","type":"text"},{"code":"MapIdle","type":"codeVoice"},{"text":", ","type":"text"},{"code":"StyleDataLoaded","type":"codeVoice"},{"text":", and ","type":"text"},{"type":"codeVoice","code":"RenderFrameFinished"},{"type":"text","text":"."}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapLoadedCallback","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TransitionOptions-swift.class":{"url":"\/documentation\/mapboxmaps\/transitionoptions-swift.class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TransitionOptions"}],"navigatorTitle":[{"text":"TransitionOptions","kind":"identifier"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"transition options"},{"type":"text","text":" controls timing for the interpolation between a transitionable style"},{"text":" ","type":"text"},{"text":"property’s previous value and new value. These can be used to define the style default property","type":"text"},{"type":"text","text":" "},{"text":"transition behavior. Also, any transitionable style property may also have its own ","type":"text"},{"type":"codeVoice","code":"-transition"},{"text":" ","type":"text"},{"text":"property that defines specific transition timing for that specific layer property, overriding","type":"text"},{"type":"text","text":" "},{"type":"text","text":"the global transition values."}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TransitionOptions-swift.class","title":"TransitionOptions","type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRequestPriorityTypeToString(_:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestPriorityTypeToString(_:)","kind":"symbol","title":"MBMRequestPriorityTypeToString(_:)","type":"topic","url":"\/documentation\/mapboxmaps\/mbmrequestprioritytypetostring(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"MBMRequestPriorityTypeToString","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@MBMRequestPriorityType","text":"RequestPriorityType","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}],"abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBMRequestPriorityTypeToString"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMResponseSourceTypeToString(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"MBMResponseSourceTypeToString","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@MBMResponseSourceType","text":"ResponseSourceType","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}],"role":"symbol","abstract":[],"title":"MBMResponseSourceTypeToString(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMResponseSourceTypeToString(_:)","url":"\/documentation\/mapboxmaps\/mbmresponsesourcetypetostring(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MBMResponseSourceTypeToString"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRequestResourceTypeToString(_:)":{"url":"\/documentation\/mapboxmaps\/mbmrequestresourcetypetostring(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"MBMRequestResourceTypeToString","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@MBMRequestResourceType","text":"RequestResourceType","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"navigatorTitle":[{"text":"MBMRequestResourceTypeToString","kind":"identifier"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestResourceTypeToString(_:)","title":"MBMRequestResourceTypeToString(_:)","type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FeatureExtensionValue":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FeatureExtensionValue","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"A value or a collection of a feature extension."}],"title":"FeatureExtensionValue","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeatureExtensionValue","url":"\/documentation\/mapboxmaps\/featureextensionvalue","kind":"symbol","type":"topic","navigatorTitle":[{"text":"FeatureExtensionValue","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRequestLoadingMethodTypeToString(_:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestLoadingMethodTypeToString(_:)","kind":"symbol","title":"MBMRequestLoadingMethodTypeToString(_:)","type":"topic","url":"\/documentation\/mapboxmaps\/mbmrequestloadingmethodtypetostring(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBMRequestLoadingMethodTypeToString","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@MBMRequestLoadingMethodType","kind":"typeIdentifier","text":"RequestLoadingMethodType"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}],"abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBMRequestLoadingMethodTypeToString"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRenderModeTypeToString(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBMRenderModeTypeToString","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@MBMRenderModeType","text":"RenderModeType","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"role":"symbol","abstract":[],"title":"MBMRenderModeTypeToString(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRenderModeTypeToString(_:)","url":"\/documentation\/mapboxmaps\/mbmrendermodetypetostring(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"text":"MBMRenderModeTypeToString","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoadingErrorCallback":{"title":"MapLoadingErrorCallback","abstract":[{"type":"text","text":"Describes an error that has occurred while loading the "},{"type":"codeVoice","code":"map"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorCallback","navigatorTitle":[{"kind":"identifier","text":"MapLoadingErrorCallback"}],"kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/maploadingerrorcallback","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapLoadingErrorCallback","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestErrorType":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RequestErrorType","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"The enumeration defines the error type that may occur during a resource request."}],"title":"RequestErrorType","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestErrorType","url":"\/documentation\/mapboxmaps\/requesterrortype","kind":"symbol","type":"topic","navigatorTitle":[{"text":"RequestErrorType","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMTileStoreUsageModeToString(_:)":{"kind":"symbol","title":"MBMTileStoreUsageModeToString(_:)","navigatorTitle":[{"kind":"identifier","text":"MBMTileStoreUsageModeToString"}],"url":"\/documentation\/mapboxmaps\/mbmtilestoreusagemodetostring(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMTileStoreUsageModeToString(_:)","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBMTileStoreUsageModeToString"},{"kind":"text","text":"("},{"text":"TileStoreUsageMode","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMTileStoreUsageMode"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResourceRequestCallback":{"type":"topic","url":"\/documentation\/mapboxmaps\/resourcerequestcallback","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ResourceRequest"},{"type":"text","text":" event allows the application to observe resourcerequests"},{"type":"text","text":" "},{"text":"made by a ","type":"text"},{"code":"map","type":"codeVoice"},{"type":"text","text":" or "},{"code":"map snapshotter","type":"codeVoice"},{"type":"text","text":" object."}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequestCallback","navigatorTitle":[{"kind":"identifier","text":"ResourceRequestCallback"}],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"ResourceRequestCallback","kind":"identifier"}],"title":"ResourceRequestCallback","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","abstract":[],"kind":"article","url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleImageRemoveUnusedCallback":{"kind":"symbol","title":"StyleImageRemoveUnusedCallback","url":"\/documentation\/mapboxmaps\/styleimageremoveunusedcallback","abstract":[{"text":"An image requested by the ","type":"text"},{"code":"map","type":"codeVoice"},{"text":" through the ","type":"text"},{"code":"StyleImageMissing","type":"codeVoice"},{"text":" event is no longer","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"needed and can be removed using the "},{"code":"removeStyleImage","type":"codeVoice"},{"text":" method. The application can","type":"text"},{"type":"text","text":" "},{"text":"decide whether the image should be kept or removed.","type":"text"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StyleImageRemoveUnusedCallback"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnusedCallback","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StyleImageRemoveUnusedCallback","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderFrameStartedCallback":{"url":"\/documentation\/mapboxmaps\/renderframestartedcallback","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"RenderFrameStartedCallback"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameStartedCallback","abstract":[{"text":"The ","type":"text"},{"code":"map","type":"codeVoice"},{"text":" started rendering a frame.","type":"text"}],"title":"RenderFrameStartedCallback","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RenderFrameStartedCallback"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraChangedCallback":{"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraChangedCallback","url":"\/documentation\/mapboxmaps\/camerachangedcallback","title":"CameraChangedCallback","navigatorTitle":[{"kind":"identifier","text":"CameraChangedCallback"}],"abstract":[{"text":"This event is emitted whenever the visible viewport changes its size","type":"text"},{"type":"text","text":" "},{"type":"text","text":"due to the invocation of the "},{"type":"codeVoice","code":"setSize"},{"text":" and ","type":"text"},{"code":"setBounds","type":"codeVoice"},{"text":" methods or when","type":"text"},{"text":" ","type":"text"},{"text":"the camera is modified by calling camera methods. The event is emitted","type":"text"},{"text":" ","type":"text"},{"text":"synchronously so that an updated camera state can be fetched immediately.","type":"text"}],"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"CameraChangedCallback","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMMapLoadingErrorTypeToString(_:)\/title","op":"replace","value":"MBMMapLoadingErrorTypeToString"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMMapLoadingErrorTypeToString(_:)\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMMapLoadingErrorTypeToString"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoadedCallback\/title","value":"MBMStyleLoadedCallback"},{"value":[{"kind":"identifier","text":"MBMStyleLoadedCallback"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoadedCallback\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoadedCallback\/navigatorTitle","value":[{"text":"MBMStyleLoadedCallback","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceRemovedCallback\/title","op":"replace","value":"MBMSourceRemovedCallback"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceRemovedCallback\/fragments","op":"replace","value":[{"text":"MBMSourceRemovedCallback","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceRemovedCallback\/navigatorTitle","value":[{"kind":"identifier","text":"MBMSourceRemovedCallback"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackError-swift.class\/title","value":"MBMStylePackError","op":"replace"},{"value":[{"text":"MBMStylePackError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackError-swift.class\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackError-swift.class\/navigatorTitle","value":[{"text":"MBMStylePackError","kind":"identifier"}]},{"value":"MBMSourceAddedCallback","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAddedCallback\/title"},{"value":[{"text":"MBMSourceAddedCallback","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAddedCallback\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAddedCallback\/navigatorTitle","value":[{"text":"MBMSourceAddedCallback","kind":"identifier"}],"op":"replace"},{"value":"MBMStyleDataLoadedTypeToString","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMStyleDataLoadedTypeToString(_:)\/title","op":"replace"},{"value":[{"text":"MBMStyleDataLoadedTypeToString","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMStyleDataLoadedTypeToString(_:)\/fragments"},{"value":"MBMStyleDataLoadedCallback","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedCallback\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedCallback\/fragments","op":"replace","value":[{"text":"MBMStyleDataLoadedCallback","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedCallback\/navigatorTitle","value":[{"kind":"identifier","text":"MBMStyleDataLoadedCallback"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedCallback\/title","value":"MBMSourceDataLoadedCallback"},{"value":[{"kind":"identifier","text":"MBMSourceDataLoadedCallback"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedCallback\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MBMSourceDataLoadedCallback"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedCallback\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageMissingCallback\/title","value":"MBMStyleImageMissingCallback","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageMissingCallback\/fragments","value":[{"text":"MBMStyleImageMissingCallback","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageMissingCallback\/navigatorTitle","value":[{"text":"MBMStyleImageMissingCallback","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapRecorder\/title","value":"MBMMapRecorder","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapRecorder\/fragments","value":[{"kind":"identifier","text":"MBMMapRecorder"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapRecorder\/navigatorTitle","value":[{"text":"MBMMapRecorder","kind":"identifier"}]},{"op":"replace","value":"MBMSourceDataLoadedTypeToString","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMSourceDataLoadedTypeToString(_:)\/title"},{"op":"replace","value":[{"text":"MBMSourceDataLoadedTypeToString","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMSourceDataLoadedTypeToString(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestDataSourceTypeToString(_:)\/title","value":"MBMRequestDataSourceTypeToString"},{"value":[{"text":"MBMRequestDataSourceTypeToString","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestDataSourceTypeToString(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestErrorTypeToString(_:)\/title","op":"replace","value":"MBMRequestErrorTypeToString"},{"value":[{"kind":"identifier","text":"MBMRequestErrorTypeToString"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestErrorTypeToString(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEventCallback\/title","value":"MBMGenericEventCallback","op":"replace"},{"op":"replace","value":[{"text":"MBMGenericEventCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEventCallback\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEventCallback\/navigatorTitle","value":[{"kind":"identifier","text":"MBMGenericEventCallback"}],"op":"replace"},{"value":"MBMMapIdleCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdleCallback\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdleCallback\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMMapIdleCallback"}]},{"value":[{"kind":"identifier","text":"MBMMapIdleCallback"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdleCallback\/navigatorTitle"},{"op":"replace","value":"MBMRenderFrameFinishedCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinishedCallback\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinishedCallback\/fragments","value":[{"kind":"identifier","text":"MBMRenderFrameFinishedCallback"}],"op":"replace"},{"value":[{"kind":"identifier","text":"MBMRenderFrameFinishedCallback"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinishedCallback\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Size\/title","value":"MBMSize"},{"op":"replace","value":[{"text":"MBMSize","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Size\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MBMSize"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Size\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadedCallback\/title","value":"MBMMapLoadedCallback"},{"value":[{"text":"MBMMapLoadedCallback","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadedCallback\/fragments"},{"value":[{"kind":"identifier","text":"MBMMapLoadedCallback"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadedCallback\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TransitionOptions-swift.class\/title","op":"replace","value":"MBMTransitionOptions"},{"op":"replace","value":[{"text":"MBMTransitionOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TransitionOptions-swift.class\/fragments"},{"op":"replace","value":[{"text":"MBMTransitionOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TransitionOptions-swift.class\/navigatorTitle"},{"op":"replace","value":"MBMRequestPriorityTypeToString","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestPriorityTypeToString(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestPriorityTypeToString(_:)\/fragments","value":[{"text":"MBMRequestPriorityTypeToString","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMResponseSourceTypeToString(_:)\/title","op":"replace","value":"MBMResponseSourceTypeToString"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMResponseSourceTypeToString(_:)\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMResponseSourceTypeToString"}]},{"value":"MBMRequestResourceTypeToString","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestResourceTypeToString(_:)\/title"},{"value":[{"text":"MBMRequestResourceTypeToString","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestResourceTypeToString(_:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeatureExtensionValue\/title","value":"MBMFeatureExtensionValue"},{"value":[{"kind":"identifier","text":"MBMFeatureExtensionValue"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeatureExtensionValue\/fragments"},{"value":[{"kind":"identifier","text":"MBMFeatureExtensionValue"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeatureExtensionValue\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestLoadingMethodTypeToString(_:)\/title","value":"MBMRequestLoadingMethodTypeToString"},{"value":[{"text":"MBMRequestLoadingMethodTypeToString","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestLoadingMethodTypeToString(_:)\/fragments"},{"op":"replace","value":"MBMRenderModeTypeToString","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRenderModeTypeToString(_:)\/title"},{"value":[{"text":"MBMRenderModeTypeToString","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRenderModeTypeToString(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorCallback\/title","value":"MBMMapLoadingErrorCallback","op":"replace"},{"value":[{"text":"MBMMapLoadingErrorCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorCallback\/fragments","op":"replace"},{"op":"replace","value":[{"text":"MBMMapLoadingErrorCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorCallback\/navigatorTitle"},{"op":"replace","value":"MBMRequestErrorType","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestErrorType\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestErrorType\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMRequestErrorType"}]},{"value":[{"kind":"identifier","text":"MBMRequestErrorType"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestErrorType\/navigatorTitle"},{"value":"MBMTileStoreUsageModeToString","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMTileStoreUsageModeToString(_:)\/title"},{"value":[{"kind":"identifier","text":"MBMTileStoreUsageModeToString"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMTileStoreUsageModeToString(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequestCallback\/title","value":"MBMResourceRequestCallback"},{"op":"replace","value":[{"kind":"identifier","text":"MBMResourceRequestCallback"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequestCallback\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequestCallback\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMResourceRequestCallback"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnusedCallback\/title","value":"MBMStyleImageRemoveUnusedCallback"},{"value":[{"text":"MBMStyleImageRemoveUnusedCallback","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnusedCallback\/fragments"},{"value":[{"kind":"identifier","text":"MBMStyleImageRemoveUnusedCallback"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnusedCallback\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameStartedCallback\/title","value":"MBMRenderFrameStartedCallback","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameStartedCallback\/fragments","value":[{"kind":"identifier","text":"MBMRenderFrameStartedCallback"}]},{"op":"replace","value":[{"kind":"identifier","text":"MBMRenderFrameStartedCallback"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameStartedCallback\/navigatorTitle"},{"value":"MBMCameraChangedCallback","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChangedCallback\/title"},{"value":[{"kind":"identifier","text":"MBMCameraChangedCallback"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChangedCallback\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MBMCameraChangedCallback"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChangedCallback\/navigatorTitle"}]}]}