{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/customrastersourceclient"]},{"paths":["\/documentation\/mapboxmaps\/customrastersourceclient"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CustomRasterSourceClient"}]}],"kind":"declarations"}],"seeAlsoSections":[{"title":"Sources","anchor":"Sources","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Source","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceInfo","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSourceData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterArraySource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/VectorSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PromoteId","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Scheme","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Encoding","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatusChangedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatus","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileFunctionCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetSize"]}],"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CustomRasterSourceClient","kind":"identifier"}],"title":"CustomRasterSourceClient","externalID":"c:objc(cs)MBMCustomRasterSourceClient","navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceClient"}],"symbolKind":"class","modules":[{"name":"MapboxMaps"}],"role":"symbol","roleHeading":"Class"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","topicSections":[{"generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient\/type"],"anchor":"Instance-Properties","title":"Instance Properties"},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient\/getCustomRasterSourceTileRenderer()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient\/getCustomRasterSourceTileStatusChangedCallback()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient\/isCustomRasterSourceTileRenderer()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient\/isCustomRasterSourceTileStatusChangedCallback()"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient\/fromCustomRasterSourceTileRenderer(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient\/fromCustomRasterSourceTileStatusChangedCallback(_:)"],"generated":true,"anchor":"Type-Methods","title":"Type Methods"}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH"]}],"references":{"doc://com.mapbox.MapboxMaps/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileStatusChangedCallback":{"abstract":[{"text":"Callback for changing a CustomRasterSource tile status.","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatusChangedCallback","navigatorTitle":[{"text":"CustomRasterSourceTileStatusChangedCallback","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxmaps\/customrastersourcetilestatuschangedcallback","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomRasterSourceTileStatusChangedCallback"}],"title":"CustomRasterSourceTileStatusChangedCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterArraySource":{"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"RasterArraySource","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"RasterArraySource"}],"type":"topic","title":"RasterArraySource","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterArraySource","tags":[{"text":"SPI","type":"spi"}],"abstract":[{"type":"text","text":"A raster array source"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/rasterarraysource"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Sources":{"title":"Sources","role":"collectionGroup","kind":"article","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources","abstract":[],"url":"\/documentation\/mapboxmaps\/sources"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceClient/fromCustomRasterSourceTileStatusChangedCallback(_:)":{"title":"fromCustomRasterSourceTileStatusChangedCallback(_:)","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient\/fromCustomRasterSourceTileStatusChangedCallback(_:)","url":"\/documentation\/mapboxmaps\/customrastersourceclient\/fromcustomrastersourcetilestatuschangedcallback(_:)","type":"topic","role":"symbol","navigatorTitle":[{"text":"fromCustomRasterSourceTileStatusChangedCallback:","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"fromCustomRasterSourceTileStatusChangedCallback","kind":"identifier"},{"kind":"text","text":"("},{"text":"CustomRasterSourceTileStatusChangedCallback","preciseIdentifier":"c:MBMCustomRasterSourceTileStatusChangedCallback.h@T@MBMCustomRasterSourceTileStatusChangedCallback","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Self"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceOptions":{"type":"topic","url":"\/documentation\/mapboxmaps\/customrastersourceoptions","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CustomRasterSourceOptions","kind":"identifier"}],"abstract":[{"type":"text","text":"Options for custom raster source."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions","role":"symbol","title":"CustomRasterSourceOptions","navigatorTitle":[{"text":"CustomRasterSourceOptions","kind":"identifier"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomGeometrySourceOptions":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CustomGeometrySourceOptions"}],"navigatorTitle":[{"text":"CustomGeometrySourceOptions","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions","title":"CustomGeometrySourceOptions","abstract":[{"type":"text","text":"Options for custom geometry source."}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/customgeometrysourceoptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileRenderer":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer","type":"topic","navigatorTitle":[{"text":"CustomRasterSourceTileRenderer","kind":"identifier"}],"abstract":[{"text":"Interface for the direct rendering into the custom raster tiles.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"CustomRasterSourceTileRenderer","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/customrastersourcetilerenderer","kind":"symbol","title":"CustomRasterSourceTileRenderer"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/VectorSource":{"url":"\/documentation\/mapboxmaps\/vectorsource","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"VectorSource","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/VectorSource","abstract":[{"text":"A vector tile source.","type":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"VectorSource","kind":"identifier"}],"title":"VectorSource","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceInfo":{"abstract":[{"type":"text","text":"Information about a Source"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceInfo","navigatorTitle":[{"kind":"identifier","text":"SourceInfo"}],"type":"topic","url":"\/documentation\/mapboxmaps\/sourceinfo","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SourceInfo"}],"title":"SourceInfo"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","role":"collection","kind":"article","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileFunctionCallback":{"type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/tilefunctioncallback","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"TileFunctionCallback","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"TileFunctionCallback"}],"title":"TileFunctionCallback","abstract":[{"text":"Callback to do various operations for tile.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"For example, fetching a tile or cancelling a tile request."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileFunctionCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSource":{"type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/customrastersource","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"CustomRasterSource","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CustomRasterSource"}],"title":"CustomRasterSource","abstract":[{"type":"text","text":"Describes a Custom Raster Source to be used in the style."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSource","tags":[{"type":"spi","text":"SPI"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceClient/isCustomRasterSourceTileRenderer()":{"kind":"symbol","role":"symbol","title":"isCustomRasterSourceTileRenderer()","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient\/isCustomRasterSourceTileRenderer()","abstract":[],"type":"topic","url":"\/documentation\/mapboxmaps\/customrastersourceclient\/iscustomrastersourcetilerenderer()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isCustomRasterSourceTileRenderer"},{"text":"() -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"isCustomRasterSourceTileRenderer","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Source":{"title":"Source","role":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Source","kind":"symbol","navigatorTitle":[{"text":"Source","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/source","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"Source","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceClient/type":{"title":"type","role":"symbol","url":"\/documentation\/mapboxmaps\/customrastersourceclient\/type","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient\/type","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"kind":"text","text":": "},{"text":"CustomRasterSourceClientType","preciseIdentifier":"c:@E@MBMCustomRasterSourceClientType","kind":"typeIdentifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"type"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterDemSource":{"title":"RasterDemSource","url":"\/documentation\/mapboxmaps\/rasterdemsource","abstract":[{"type":"text","text":"A RGB-encoded raster DEM source"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"RasterDemSource","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"RasterDemSource"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceClient/getCustomRasterSourceTileStatusChangedCallback()":{"navigatorTitle":[{"kind":"identifier","text":"getCustomRasterSourceTileStatusChangedCallback"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient\/getCustomRasterSourceTileStatusChangedCallback()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getCustomRasterSourceTileStatusChangedCallback"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"CustomRasterSourceTileStatusChangedCallback","preciseIdentifier":"c:MBMCustomRasterSourceTileStatusChangedCallback.h@T@MBMCustomRasterSourceTileStatusChangedCallback"}],"abstract":[],"type":"topic","title":"getCustomRasterSourceTileStatusChangedCallback()","kind":"symbol","url":"\/documentation\/mapboxmaps\/customrastersourceclient\/getcustomrastersourcetilestatuschangedcallback()"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomGeometrySource":{"type":"topic","url":"\/documentation\/mapboxmaps\/customgeometrysource","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomGeometrySource"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySource","abstract":[{"text":"Describes a Custom Geometry Source to be used in the style","type":"text"}],"role":"symbol","title":"CustomGeometrySource","navigatorTitle":[{"text":"CustomGeometrySource","kind":"identifier"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileData":{"type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/customrastersourcetiledata","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CustomRasterSourceTileData","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceTileData"}],"title":"CustomRasterSourceTileData","abstract":[{"type":"text","text":"Data for a specific CustomRasterSource tile."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileData"},"doc://com.mapbox.MapboxMaps/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterSource":{"abstract":[{"text":"A raster tile source.","type":"text"}],"type":"topic","kind":"symbol","title":"RasterSource","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"RasterSource","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"RasterSource"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterSource","role":"symbol","url":"\/documentation\/mapboxmaps\/rastersource"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"type":"topic","role":"collection","url":"\/documentation\/mapboxmaps","title":"MapboxMaps","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject","title":"NSObject"},"doc://com.mapbox.MapboxMaps/SH":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","title":"Swift.Hashable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceClientType":{"kind":"symbol","title":"CustomRasterSourceClientType","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomRasterSourceClientType"}],"navigatorTitle":[{"text":"CustomRasterSourceClientType","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/customrastersourceclienttype","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType","type":"topic","role":"symbol","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GeoJSONSourceData":{"navigatorTitle":[{"text":"GeoJSONSourceData","kind":"identifier"}],"title":"GeoJSONSourceData","abstract":[{"text":"Captures potential values of the ","type":"text"},{"type":"codeVoice","code":"data"},{"text":" property of a GeoJSONSource.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSourceData","url":"\/documentation\/mapboxmaps\/geojsonsourcedata","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"GeoJSONSourceData","kind":"identifier"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceClient/getCustomRasterSourceTileRenderer()":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"getCustomRasterSourceTileRenderer"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient\/getCustomRasterSourceTileRenderer()","url":"\/documentation\/mapboxmaps\/customrastersourceclient\/getcustomrastersourcetilerenderer()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getCustomRasterSourceTileRenderer"},{"kind":"text","text":"() -> any "},{"preciseIdentifier":"c:objc(pl)MBMCustomRasterSourceTileRenderer","text":"CustomRasterSourceTileRenderer","kind":"typeIdentifier"}],"abstract":[],"title":"getCustomRasterSourceTileRenderer()","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceType":{"type":"topic","url":"\/documentation\/mapboxmaps\/sourcetype","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"SourceType","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Struct of supported Source Types","type":"text"},{"text":" ","type":"text"},{"text":"Docs : https:\/\/docs.mapbox.com\/mapbox-gl-js\/style-spec\/sources\/","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceType","title":"SourceType","navigatorTitle":[{"kind":"identifier","text":"SourceType"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Encoding":{"role":"symbol","url":"\/documentation\/mapboxmaps\/encoding","kind":"symbol","navigatorTitle":[{"text":"Encoding","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Encoding","title":"Encoding","abstract":[{"text":"The encoding used by this source. Mapbox Terrain RGB is used by default","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"Encoding","kind":"identifier"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ImageSource":{"abstract":[{"text":"An image data source.","type":"text"}],"title":"ImageSource","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageSource","url":"\/documentation\/mapboxmaps\/imagesource","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageSource"}],"navigatorTitle":[{"text":"ImageSource","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudgetSize":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetSize","title":"TileCacheBudgetSize","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"TileCacheBudgetSize","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/tilecachebudgetsize","abstract":[{"type":"text","text":"Defines a TileCacheBudgetSize, which can be set as either a megabyte or tile count limit."},{"text":" ","type":"text"},{"type":"text","text":"Whenever tile cache goes over the defined limit"},{"type":"text","text":" "},{"type":"text","text":"the least recently used tile will be evicted from the in-memory cache"}],"navigatorTitle":[{"text":"TileCacheBudgetSize","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GeoJSONSource":{"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GeoJSONSource"}],"navigatorTitle":[{"text":"GeoJSONSource","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSource","title":"GeoJSONSource","abstract":[{"type":"text","text":"A GeoJSON data source."}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/geojsonsource"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PromoteId":{"title":"PromoteId","role":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PromoteId","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PromoteId"}],"url":"\/documentation\/mapboxmaps\/promoteid","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PromoteId","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceClient/fromCustomRasterSourceTileRenderer(_:)":{"title":"fromCustomRasterSourceTileRenderer(_:)","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient\/fromCustomRasterSourceTileRenderer(_:)","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fromCustomRasterSourceTileRenderer"},{"text":"(any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)MBMCustomRasterSourceTileRenderer","text":"CustomRasterSourceTileRenderer","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Self"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"fromCustomRasterSourceTileRenderer:","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/customrastersourceclient\/fromcustomrastersourcetilerenderer(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileStatus":{"type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/customrastersourcetilestatus","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"CustomRasterSourceTileStatus","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceTileStatus"}],"title":"CustomRasterSourceTileStatus","abstract":[{"type":"text","text":"CustomRasterSource tile status."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatus"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Scheme":{"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"Scheme","kind":"identifier"}],"navigatorTitle":[{"text":"Scheme","kind":"identifier"}],"type":"topic","title":"Scheme","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Scheme","abstract":[{"type":"text","text":"Influences the y direction of the tile coordinates. The global-mercator (aka Spherical Mercator) profile is assumed."}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/scheme"},"doc://com.mapbox.MapboxMaps/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceClient/isCustomRasterSourceTileStatusChangedCallback()":{"title":"isCustomRasterSourceTileStatusChangedCallback()","role":"symbol","abstract":[],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isCustomRasterSourceTileStatusChangedCallback","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient\/isCustomRasterSourceTileStatusChangedCallback()","url":"\/documentation\/mapboxmaps\/customrastersourceclient\/iscustomrastersourcetilestatuschangedcallback()","type":"topic","navigatorTitle":[{"text":"isCustomRasterSourceTileStatusChangedCallback","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceClient":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"CustomRasterSourceClient","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient","url":"\/documentation\/mapboxmaps\/customrastersourceclient","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomRasterSourceClient"}],"abstract":[],"title":"CustomRasterSourceClient","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"MBMCustomRasterSourceClient"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"MBMCustomRasterSourceClient","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MBMCustomRasterSourceClient"}]},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient\/type"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient\/getCustomRasterSourceTileRenderer()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient\/getCustomRasterSourceTileStatusChangedCallback()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient\/isCustomRasterSourceTileRenderer()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient\/isCustomRasterSourceTileStatusChangedCallback()"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient\/fromCustomRasterSourceTileRenderer(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient\/fromCustomRasterSourceTileStatusChangedCallback(_:)"],"generated":true,"title":"Type Methods","anchor":"Type-Methods"}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"]}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatusChangedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatus","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileFunctionCallback"],"title":"Sources","generated":true,"anchor":"Sources"}]},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"MBMCustomRasterSourceClient","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatusChangedCallback\/title","op":"replace","value":"MBMCustomRasterSourceTileStatusChangedCallback"},{"value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileStatusChangedCallback"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatusChangedCallback\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatusChangedCallback\/navigatorTitle","value":[{"text":"MBMCustomRasterSourceTileStatusChangedCallback","kind":"identifier"}]},{"value":"fromCustomRasterSourceTileStatusChangedCallback:","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient~1fromCustomRasterSourceTileStatusChangedCallback(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient~1fromCustomRasterSourceTileStatusChangedCallback(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"fromCustomRasterSourceTileStatusChangedCallback:","kind":"identifier"}]},{"op":"replace","value":"MBMCustomRasterSourceOptions","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/fragments","value":[{"kind":"identifier","text":"MBMCustomRasterSourceOptions"}],"op":"replace"},{"op":"replace","value":[{"text":"MBMCustomRasterSourceOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions\/title","value":"MBMCustomGeometrySourceOptions"},{"op":"replace","value":[{"text":"MBMCustomGeometrySourceOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions\/navigatorTitle","value":[{"kind":"identifier","text":"MBMCustomGeometrySourceOptions"}],"op":"replace"},{"value":"MBMCustomRasterSourceTileRenderer","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer\/title","op":"replace"},{"value":[{"text":"MBMCustomRasterSourceTileRenderer","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer\/fragments","op":"replace"},{"op":"replace","value":[{"text":"MBMCustomRasterSourceTileRenderer","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer\/navigatorTitle"},{"op":"replace","value":"MBMTileFunctionCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileFunctionCallback\/title"},{"value":[{"kind":"identifier","text":"MBMTileFunctionCallback"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileFunctionCallback\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MBMTileFunctionCallback"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileFunctionCallback\/navigatorTitle"},{"op":"replace","value":"isCustomRasterSourceTileRenderer","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient~1isCustomRasterSourceTileRenderer()\/title"},{"value":[{"kind":"text","text":"- "},{"text":"isCustomRasterSourceTileRenderer","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient~1isCustomRasterSourceTileRenderer()\/fragments","op":"replace"},{"value":"type","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient~1type\/title","op":"replace"},{"value":[{"kind":"identifier","text":"type"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient~1type\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient~1getCustomRasterSourceTileStatusChangedCallback()\/title","op":"replace","value":"getCustomRasterSourceTileStatusChangedCallback"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getCustomRasterSourceTileStatusChangedCallback"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient~1getCustomRasterSourceTileStatusChangedCallback()\/fragments"},{"value":"MBMCustomRasterSourceTileData","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileData\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileData"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileData\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileData\/navigatorTitle","value":[{"text":"MBMCustomRasterSourceTileData","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType\/title","value":"MBMCustomRasterSourceClientType"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType\/fragments","op":"replace","value":[{"text":"MBMCustomRasterSourceClientType","kind":"identifier"}]},{"value":[{"text":"MBMCustomRasterSourceClientType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient~1getCustomRasterSourceTileRenderer()\/title","value":"getCustomRasterSourceTileRenderer"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"getCustomRasterSourceTileRenderer","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient~1getCustomRasterSourceTileRenderer()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient~1fromCustomRasterSourceTileRenderer(_:)\/title","value":"fromCustomRasterSourceTileRenderer:"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromCustomRasterSourceTileRenderer:"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient~1fromCustomRasterSourceTileRenderer(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatus\/title","value":"MBMCustomRasterSourceTileStatus"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatus\/fragments","value":[{"text":"MBMCustomRasterSourceTileStatus","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatus\/navigatorTitle","value":[{"text":"MBMCustomRasterSourceTileStatus","kind":"identifier"}]},{"value":"isCustomRasterSourceTileStatusChangedCallback","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient~1isCustomRasterSourceTileStatusChangedCallback()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient~1isCustomRasterSourceTileStatusChangedCallback()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"isCustomRasterSourceTileStatusChangedCallback","kind":"identifier"}]},{"op":"replace","value":"MBMCustomRasterSourceClient","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient\/fragments","value":[{"kind":"identifier","text":"MBMCustomRasterSourceClient"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMCustomRasterSourceClient"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}