{"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Source","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceInfo","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSourceData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterArraySource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/VectorSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PromoteId","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Scheme","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Encoding","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatusChangedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileFunctionCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetSize"],"anchor":"Sources","title":"Sources"}],"metadata":{"role":"symbol","externalID":"c:@E@MBMCustomRasterSourceTileStatus","modules":[{"name":"MapboxMaps"}],"symbolKind":"enum","title":"CustomRasterSourceTileStatus","navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceTileStatus"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CustomRasterSourceTileStatus"}],"roleHeading":"Enumeration"},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatus","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatus\/notNeeded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatus\/optional","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatus\/required"],"anchor":"Enumeration-Cases","generated":true},{"anchor":"Initializers","generated":true,"title":"Initializers","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatus\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatus\/Equatable-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatus\/RawRepresentable-Implementations"],"generated":true,"anchor":"Default-Implementations"}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","abstract":[{"text":"CustomRasterSource tile status.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CustomRasterSourceTileStatus"}]}]}],"relationshipsSections":[{"type":"conformsTo","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/s15BitwiseCopyableP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH","doc:\/\/com.mapbox.MapboxMaps\/SY","doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"],"kind":"relationships","title":"Conforms To"}],"variants":[{"paths":["\/documentation\/mapboxmaps\/customrastersourcetilestatus"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/customrastersourcetilestatus"]}],"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ImageSource":{"title":"ImageSource","url":"\/documentation\/mapboxmaps\/imagesource","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ImageSource"}],"abstract":[{"text":"An image data source.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageSource"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomGeometrySource":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySource","title":"CustomGeometrySource","abstract":[{"type":"text","text":"Describes a Custom Geometry Source to be used in the style"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"CustomGeometrySource","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxmaps\/customgeometrysource","navigatorTitle":[{"text":"CustomGeometrySource","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceInfo":{"url":"\/documentation\/mapboxmaps\/sourceinfo","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceInfo","type":"topic","abstract":[{"type":"text","text":"Information about a Source"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SourceInfo"}],"title":"SourceInfo","role":"symbol","navigatorTitle":[{"text":"SourceInfo","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceClientType":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/customrastersourceclienttype","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType","type":"topic","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"CustomRasterSourceClientType","kind":"identifier"}],"title":"CustomRasterSourceClientType","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceClientType"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileStatus/notNeeded":{"abstract":[{"type":"text","text":"Tile is not visible and no more needed."}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"notNeeded","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"MBMCustomRasterSourceTileStatusNotNeeded","kind":"identifier"}],"type":"topic","title":"CustomRasterSourceTileStatus.notNeeded","url":"\/documentation\/mapboxmaps\/customrastersourcetilestatus\/notneeded","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatus\/notNeeded"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","kind":"article","type":"topic","url":"\/documentation\/overview","title":"MapboxMaps Documentation","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/VectorSource":{"url":"\/documentation\/mapboxmaps\/vectorsource","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/VectorSource","type":"topic","abstract":[{"type":"text","text":"A vector tile source."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VectorSource","kind":"identifier"}],"title":"VectorSource","role":"symbol","navigatorTitle":[{"text":"VectorSource","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PromoteId":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PromoteId","abstract":[],"url":"\/documentation\/mapboxmaps\/promoteid","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PromoteId","kind":"identifier"}],"navigatorTitle":[{"text":"PromoteId","kind":"identifier"}],"title":"PromoteId","role":"symbol","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterSource":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"RasterSource"}],"abstract":[{"type":"text","text":"A raster tile source."}],"kind":"symbol","title":"RasterSource","url":"\/documentation\/mapboxmaps\/rastersource","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterSource","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"RasterSource","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GeoJSONSourceData":{"kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/geojsonsourcedata","abstract":[{"type":"text","text":"Captures potential values of the "},{"type":"codeVoice","code":"data"},{"type":"text","text":" property of a GeoJSONSource."}],"navigatorTitle":[{"kind":"identifier","text":"GeoJSONSourceData"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSourceData","title":"GeoJSONSourceData","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GeoJSONSourceData"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Source":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/source","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Source","type":"topic","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Source","kind":"identifier"}],"title":"Source","role":"symbol","navigatorTitle":[{"text":"Source","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceClient":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/customrastersourceclient","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient","type":"topic","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomRasterSourceClient","kind":"identifier"}],"title":"CustomRasterSourceClient","role":"symbol","navigatorTitle":[{"text":"CustomRasterSourceClient","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Sources":{"abstract":[],"title":"Sources","role":"collectionGroup","type":"topic","url":"\/documentation\/mapboxmaps\/sources","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources","kind":"article"},"doc://com.mapbox.MapboxMaps/s8SendableP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomGeometrySourceOptions":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions","kind":"symbol","title":"CustomGeometrySourceOptions","type":"topic","role":"symbol","navigatorTitle":[{"text":"CustomGeometrySourceOptions","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"CustomGeometrySourceOptions","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/customgeometrysourceoptions","abstract":[{"text":"Options for custom geometry source.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterDemSource":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/rasterdemsource","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource","type":"topic","abstract":[{"text":"A RGB-encoded raster DEM source","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RasterDemSource","kind":"identifier"}],"title":"RasterDemSource","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"RasterDemSource"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileStatus/required":{"abstract":[{"type":"text","text":"Tile best suited for current camera position."},{"type":"text","text":" "},{"text":"Should be loaded if possible.","type":"text"}],"url":"\/documentation\/mapboxmaps\/customrastersourcetilestatus\/required","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"required"}],"title":"CustomRasterSourceTileStatus.required","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatus\/required","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"MBMCustomRasterSourceTileStatusRequired","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","role":"collection","title":"MapboxMaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps"},"doc://com.mapbox.MapboxMaps/SY":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileStatusChangedCallback":{"url":"\/documentation\/mapboxmaps\/customrastersourcetilestatuschangedcallback","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatusChangedCallback","type":"topic","abstract":[{"type":"text","text":"Callback for changing a CustomRasterSource tile status."}],"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"CustomRasterSourceTileStatusChangedCallback","kind":"identifier"}],"title":"CustomRasterSourceTileStatusChangedCallback","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceTileStatusChangedCallback"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Encoding":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/encoding","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Encoding","type":"topic","abstract":[{"type":"text","text":"The encoding used by this source. Mapbox Terrain RGB is used by default"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"Encoding","kind":"identifier"}],"title":"Encoding","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Encoding"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileFunctionCallback":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/tilefunctioncallback","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileFunctionCallback","type":"topic","abstract":[{"type":"text","text":"Callback to do various operations for tile."},{"text":" ","type":"text"},{"type":"text","text":"For example, fetching a tile or cancelling a tile request."}],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"TileFunctionCallback","kind":"identifier"}],"title":"TileFunctionCallback","role":"symbol","navigatorTitle":[{"text":"TileFunctionCallback","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSource":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/customrastersource","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSource","type":"topic","tags":[{"type":"spi","text":"SPI"}],"abstract":[{"type":"text","text":"Describes a Custom Raster Source to be used in the style."}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"CustomRasterSource","kind":"identifier"}],"title":"CustomRasterSource","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CustomRasterSource"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileStatus":{"abstract":[{"type":"text","text":"CustomRasterSource tile status."}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatus","url":"\/documentation\/mapboxmaps\/customrastersourcetilestatus","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CustomRasterSourceTileStatus"}],"navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceTileStatus"}],"title":"CustomRasterSourceTileStatus"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileStatus/init(rawValue:)":{"url":"\/documentation\/mapboxmaps\/customrastersourcetilestatus\/init(rawvalue:)","title":"init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}],"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatus\/init(rawValue:)","role":"symbol","type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/SH":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceType":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/sourcetype","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceType","type":"topic","abstract":[{"type":"text","text":"Struct of supported Source Types"},{"type":"text","text":" "},{"type":"text","text":"Docs : https:\/\/docs.mapbox.com\/mapbox-gl-js\/style-spec\/sources\/"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"SourceType","kind":"identifier"}],"title":"SourceType","role":"symbol","navigatorTitle":[{"text":"SourceType","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/s15BitwiseCopyableP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s15BitwiseCopyableP","title":"Swift.BitwiseCopyable","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudgetSize":{"url":"\/documentation\/mapboxmaps\/tilecachebudgetsize","abstract":[{"type":"text","text":"Defines a TileCacheBudgetSize, which can be set as either a megabyte or tile count limit."},{"type":"text","text":" "},{"type":"text","text":"Whenever tile cache goes over the defined limit"},{"text":" ","type":"text"},{"text":"the least recently used tile will be evicted from the in-memory cache","type":"text"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TileCacheBudgetSize"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetSize","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TileCacheBudgetSize"}],"type":"topic","title":"TileCacheBudgetSize"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileData":{"navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceTileData"}],"type":"topic","url":"\/documentation\/mapboxmaps\/customrastersourcetiledata","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileData","kind":"symbol","title":"CustomRasterSourceTileData","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomRasterSourceTileData","kind":"identifier"}],"abstract":[{"text":"Data for a specific CustomRasterSource tile.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GeoJSONSource":{"abstract":[{"text":"A GeoJSON data source.","type":"text"}],"type":"topic","url":"\/documentation\/mapboxmaps\/geojsonsource","title":"GeoJSONSource","kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GeoJSONSource","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSource","navigatorTitle":[{"text":"GeoJSONSource","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceOptions":{"url":"\/documentation\/mapboxmaps\/customrastersourceoptions","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions","type":"topic","abstract":[{"type":"text","text":"Options for custom raster source."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CustomRasterSourceOptions"}],"title":"CustomRasterSourceOptions","role":"symbol","navigatorTitle":[{"text":"CustomRasterSourceOptions","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileStatus/Equatable-Implementations":{"url":"\/documentation\/mapboxmaps\/customrastersourcetilestatus\/equatable-implementations","role":"collectionGroup","kind":"article","abstract":[],"type":"topic","title":"Equatable Implementations","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatus\/Equatable-Implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterArraySource":{"abstract":[{"type":"text","text":"A raster array source"}],"title":"RasterArraySource","role":"symbol","tags":[{"text":"SPI","type":"spi"}],"navigatorTitle":[{"text":"RasterArraySource","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"RasterArraySource"}],"url":"\/documentation\/mapboxmaps\/rasterarraysource","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterArraySource","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileRenderer":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer","role":"symbol","abstract":[{"type":"text","text":"Interface for the direct rendering into the custom raster tiles."}],"navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceTileRenderer"}],"type":"topic","title":"CustomRasterSourceTileRenderer","url":"\/documentation\/mapboxmaps\/customrastersourcetilerenderer","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"CustomRasterSourceTileRenderer","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/SQ":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Scheme":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/scheme","navigatorTitle":[{"kind":"identifier","text":"Scheme"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Scheme","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Scheme"}],"title":"Scheme","type":"topic","abstract":[{"text":"Influences the y direction of the tile coordinates. The global-mercator (aka Spherical Mercator) profile is assumed.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileStatus/RawRepresentable-Implementations":{"url":"\/documentation\/mapboxmaps\/customrastersourcetilestatus\/rawrepresentable-implementations","abstract":[],"title":"RawRepresentable Implementations","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatus\/RawRepresentable-Implementations","kind":"article","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileStatus/optional":{"url":"\/documentation\/mapboxmaps\/customrastersourcetilestatus\/optional","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"optional"}],"role":"symbol","title":"CustomRasterSourceTileStatus.optional","abstract":[{"type":"text","text":"Tile can be used if required tile is missing."},{"text":" ","type":"text"},{"type":"text","text":"Can be provided if already present in a cache."}],"navigatorTitle":[{"kind":"identifier","text":"MBMCustomRasterSourceTileStatusOptional"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatus\/optional"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"MBMCustomRasterSourceTileStatus"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MBMCustomRasterSourceTileStatus","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileStatus"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatus\/notNeeded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatus\/optional","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatus\/required"],"anchor":"Enumeration-Cases","generated":true}],"path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":null},{"value":[{"anchor":"Sources","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatusChangedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileFunctionCallback"],"title":"Sources","generated":true}],"op":"replace","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MBMCustomRasterSourceTileStatus","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType\/title","value":"MBMCustomRasterSourceClientType"},{"op":"replace","value":[{"kind":"identifier","text":"MBMCustomRasterSourceClientType"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType\/navigatorTitle","value":[{"text":"MBMCustomRasterSourceClientType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatus~1notNeeded\/title","value":"MBMCustomRasterSourceTileStatusNotNeeded","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatus~1notNeeded\/fragments","value":[{"text":"MBMCustomRasterSourceTileStatusNotNeeded","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient\/title","value":"MBMCustomRasterSourceClient"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient\/fragments","value":[{"text":"MBMCustomRasterSourceClient","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMCustomRasterSourceClient"}]},{"value":"MBMCustomGeometrySourceOptions","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions\/fragments","value":[{"kind":"identifier","text":"MBMCustomGeometrySourceOptions"}]},{"op":"replace","value":[{"text":"MBMCustomGeometrySourceOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions\/navigatorTitle"},{"op":"replace","value":"MBMCustomRasterSourceTileStatusRequired","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatus~1required\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatus~1required\/fragments","value":[{"text":"MBMCustomRasterSourceTileStatusRequired","kind":"identifier"}],"op":"replace"},{"value":"MBMCustomRasterSourceTileStatusChangedCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatusChangedCallback\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatusChangedCallback\/fragments","value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileStatusChangedCallback"}]},{"op":"replace","value":[{"text":"MBMCustomRasterSourceTileStatusChangedCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatusChangedCallback\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileFunctionCallback\/title","value":"MBMTileFunctionCallback"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileFunctionCallback\/fragments","value":[{"text":"MBMTileFunctionCallback","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileFunctionCallback\/navigatorTitle","value":[{"kind":"identifier","text":"MBMTileFunctionCallback"}]},{"value":"MBMCustomRasterSourceTileStatus","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatus\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatus\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatus\/navigatorTitle","value":[{"text":"MBMCustomRasterSourceTileStatus","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileData\/title","op":"replace","value":"MBMCustomRasterSourceTileData"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileData\/fragments","op":"replace","value":[{"text":"MBMCustomRasterSourceTileData","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileData\/navigatorTitle","value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileData"}],"op":"replace"},{"value":"MBMCustomRasterSourceOptions","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/fragments","op":"replace","value":[{"text":"MBMCustomRasterSourceOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/navigatorTitle","value":[{"text":"MBMCustomRasterSourceOptions","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"MBMCustomRasterSourceTileRenderer","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer\/fragments","value":[{"text":"MBMCustomRasterSourceTileRenderer","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer\/navigatorTitle","value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileRenderer"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatus~1optional\/title","value":"MBMCustomRasterSourceTileStatusOptional"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatus~1optional\/fragments","value":[{"text":"MBMCustomRasterSourceTileStatusOptional","kind":"identifier"}],"op":"replace"}]}]}