{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"]]},"seeAlsoSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Source","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceInfo","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSourceData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterArraySource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/VectorSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PromoteId","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Scheme","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Encoding","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions"],"generated":true,"anchor":"Sources","title":"Sources"}],"kind":"symbol","metadata":{"navigatorTitle":[{"text":"CustomRasterSourceTileRenderer","kind":"identifier"}],"symbolKind":"protocol","externalID":"c:objc(pl)MBMCustomRasterSourceTileRenderer","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomRasterSourceTileRenderer"}],"modules":[{"name":"MapboxMaps"}],"roleHeading":"Protocol","title":"CustomRasterSourceTileRenderer"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer"},"topicSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer\/deinitialize()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer\/initialize(forDevice:colorPixelFormat:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer\/isTileRenderable(for:status:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer\/prerender(for:commandBuffer:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer\/renderToTile(for:commandEncoder:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CustomRasterSourceTileRenderer"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"level":2,"type":"heading","text":"Overview","anchor":"overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The client should implement this interface for the direct rendering into the custom raster tiles."},{"type":"text","text":" "},{"text":"The layers that use the corresponding custom raster source will have the rendered content as the input tile data.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"All methods of this interface are invoked from the renderer thread."}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/customrastersourcetilerenderer"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/customrastersourcetilerenderer"]}],"sections":[],"abstract":[{"type":"text","text":"Interface for the direct rendering into the custom raster tiles."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceType":{"url":"\/documentation\/mapboxmaps\/sourcetype","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceType","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceType"}],"navigatorTitle":[{"kind":"identifier","text":"SourceType"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Struct of supported Source Types"},{"text":" ","type":"text"},{"text":"Docs : https:\/\/docs.mapbox.com\/mapbox-gl-js\/style-spec\/sources\/","type":"text"}],"role":"symbol","title":"SourceType"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileData":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileData","url":"\/documentation\/mapboxmaps\/customrastersourcetiledata","role":"symbol","title":"CustomRasterSourceTileData","navigatorTitle":[{"text":"CustomRasterSourceTileData","kind":"identifier"}],"abstract":[{"type":"text","text":"Data for a specific CustomRasterSource tile."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomRasterSourceTileData","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GeoJSONSource":{"role":"symbol","type":"topic","title":"GeoJSONSource","kind":"symbol","url":"\/documentation\/mapboxmaps\/geojsonsource","abstract":[{"type":"text","text":"A GeoJSON data source."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSource","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GeoJSONSource"}],"navigatorTitle":[{"text":"GeoJSONSource","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GeoJSONSourceData":{"abstract":[{"type":"text","text":"Captures potential values of the "},{"code":"data","type":"codeVoice"},{"text":" property of a GeoJSONSource.","type":"text"}],"navigatorTitle":[{"text":"GeoJSONSourceData","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","title":"GeoJSONSourceData","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GeoJSONSourceData","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSourceData","url":"\/documentation\/mapboxmaps\/geojsonsourcedata"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceInfo":{"url":"\/documentation\/mapboxmaps\/sourceinfo","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SourceInfo"}],"navigatorTitle":[{"kind":"identifier","text":"SourceInfo"}],"abstract":[{"type":"text","text":"Information about a Source"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceInfo","title":"SourceInfo","type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileRenderer/initialize(forDevice:colorPixelFormat:)":{"title":"initialize(forDevice:colorPixelFormat:)","type":"topic","required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forDevice"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt64","preciseIdentifier":"s:s6UInt64V"},{"text":", ","kind":"text"},{"text":"colorPixelFormat","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V","text":"UInt64"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initializeForDevice:colorPixelFormat:","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer\/initialize(forDevice:colorPixelFormat:)","abstract":[{"type":"text","text":"Initialize any Metal state needed by the tile renderer. This method is called once,"},{"text":" ","type":"text"},{"type":"text","text":"before rendering for the first time."},{"type":"text","text":" "},{"type":"text","text":"The client should obtain the "},{"code":"MTLDevice","type":"codeVoice"},{"text":" instance from the ","type":"text"},{"type":"codeVoice","code":"device"},{"type":"text","text":" argument, using the"},{"text":" ","type":"text"},{"type":"text","text":"following code:"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/customrastersourcetilerenderer\/initialize(fordevice:colorpixelformat:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterDemSource":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource","title":"RasterDemSource","abstract":[{"type":"text","text":"A RGB-encoded raster DEM source"}],"navigatorTitle":[{"text":"RasterDemSource","kind":"identifier"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RasterDemSource"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/rasterdemsource","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","role":"collection","url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"title":"MapboxMaps","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Encoding":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Encoding","kind":"symbol","url":"\/documentation\/mapboxmaps\/encoding","navigatorTitle":[{"kind":"identifier","text":"Encoding"}],"abstract":[{"type":"text","text":"The encoding used by this source. Mapbox Terrain RGB is used by default"}],"role":"symbol","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Encoding","kind":"identifier"}],"title":"Encoding"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileStatus":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatus","url":"\/documentation\/mapboxmaps\/customrastersourcetilestatus","role":"symbol","title":"CustomRasterSourceTileStatus","navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceTileStatus"}],"abstract":[{"text":"CustomRasterSource tile status.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"CustomRasterSourceTileStatus","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomGeometrySource":{"url":"\/documentation\/mapboxmaps\/customgeometrysource","title":"CustomGeometrySource","type":"topic","abstract":[{"text":"Describes a Custom Geometry Source to be used in the style","type":"text"}],"navigatorTitle":[{"text":"CustomGeometrySource","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CustomGeometrySource"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySource","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileStatusChangedCallback":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatusChangedCallback","url":"\/documentation\/mapboxmaps\/customrastersourcetilestatuschangedcallback","role":"symbol","title":"CustomRasterSourceTileStatusChangedCallback","navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceTileStatusChangedCallback"}],"abstract":[{"text":"Callback for changing a CustomRasterSource tile status.","type":"text"}],"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"CustomRasterSourceTileStatusChangedCallback","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceOptions":{"url":"\/documentation\/mapboxmaps\/customrastersourceoptions","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CustomRasterSourceOptions"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions","type":"topic","title":"CustomRasterSourceOptions","role":"symbol","navigatorTitle":[{"text":"CustomRasterSourceOptions","kind":"identifier"}],"abstract":[{"text":"Options for custom raster source.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceClientType":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType","kind":"symbol","url":"\/documentation\/mapboxmaps\/customrastersourceclienttype","navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceClientType"}],"abstract":[],"role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomRasterSourceClientType","kind":"identifier"}],"title":"CustomRasterSourceClientType"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileRenderer/prerender(for:commandBuffer:)":{"role":"symbol","type":"topic","required":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer\/prerender(for:commandBuffer:)","title":"prerender(for:commandBuffer:)","abstract":[{"type":"text","text":"This method is called once per frame, before any layer is rendered."},{"type":"text","text":" "},{"type":"text","text":"It is to be used to allow to prepare resources or render into a texture for the client"},{"type":"text","text":" "},{"type":"text","text":"or initialize some varaibles and states shared across the tiles."}],"navigatorTitle":[{"text":"prerenderForParameters:commandBuffer:","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"prerender"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MBMCustomLayerRenderParameters","text":"CustomLayerRenderParameters","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"commandBuffer","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt64","preciseIdentifier":"s:s6UInt64V"},{"text":")","kind":"text"}],"url":"\/documentation\/mapboxmaps\/customrastersourcetilerenderer\/prerender(for:commandbuffer:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PromoteId":{"url":"\/documentation\/mapboxmaps\/promoteid","title":"PromoteId","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"PromoteId"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PromoteId","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PromoteId","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomGeometrySourceOptions":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomGeometrySourceOptions"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions","navigatorTitle":[{"text":"CustomGeometrySourceOptions","kind":"identifier"}],"title":"CustomGeometrySourceOptions","url":"\/documentation\/mapboxmaps\/customgeometrysourceoptions","abstract":[{"type":"text","text":"Options for custom geometry source."}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Scheme":{"url":"\/documentation\/mapboxmaps\/scheme","abstract":[{"type":"text","text":"Influences the y direction of the tile coordinates. The global-mercator (aka Spherical Mercator) profile is assumed."}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Scheme"}],"title":"Scheme","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"Scheme","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Scheme","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ImageSource":{"title":"ImageSource","url":"\/documentation\/mapboxmaps\/imagesource","abstract":[{"type":"text","text":"An image data source."}],"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"ImageSource","kind":"identifier"}],"navigatorTitle":[{"text":"ImageSource","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageSource"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterArraySource":{"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RasterArraySource","kind":"identifier"}],"kind":"symbol","title":"RasterArraySource","url":"\/documentation\/mapboxmaps\/rasterarraysource","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"RasterArraySource"}],"tags":[{"type":"spi","text":"SPI"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterArraySource","abstract":[{"text":"A raster array source","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceClient":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient","kind":"symbol","title":"CustomRasterSourceClient","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CustomRasterSourceClient"}],"abstract":[],"role":"symbol","url":"\/documentation\/mapboxmaps\/customrastersourceclient","navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceClient"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileRenderer/deinitialize()":{"required":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"deinitialize"}],"type":"topic","abstract":[{"type":"text","text":"Destroy any GL state needed by the custom renderer, and deallocate context, if necessary. This"},{"type":"text","text":" "},{"type":"text","text":"method is called once, at a point when the GL context is active."}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"deinitialize"},{"text":"()","kind":"text"}],"title":"deinitialize()","url":"\/documentation\/mapboxmaps\/customrastersourcetilerenderer\/deinitialize()","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer\/deinitialize()"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileRenderer/isTileRenderable(for:status:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer\/isTileRenderable(for:status:)","navigatorTitle":[{"kind":"identifier","text":"isTileRenderableForTileID:status:"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/customrastersourcetilerenderer\/istilerenderable(for:status:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isTileRenderable"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MBMCanonicalTileID","text":"CanonicalTileID","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"status"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@MBMCustomRasterSourceTileStatus","text":"CustomRasterSourceTileStatus","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"isTileRenderable(for:status:)","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Checks whether the tile should be rendered in the current frame."}],"required":true},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/VectorSource":{"kind":"symbol","title":"VectorSource","role":"symbol","navigatorTitle":[{"text":"VectorSource","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/vectorsource","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/VectorSource","abstract":[{"type":"text","text":"A vector tile source."}],"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VectorSource","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterSource":{"title":"RasterSource","type":"topic","url":"\/documentation\/mapboxmaps\/rastersource","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterSource","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"RasterSource","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"RasterSource"}],"abstract":[{"type":"text","text":"A raster tile source."}],"role":"symbol","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileRenderer":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer","kind":"symbol","title":"CustomRasterSourceTileRenderer","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"CustomRasterSourceTileRenderer","kind":"identifier"}],"abstract":[{"type":"text","text":"Interface for the direct rendering into the custom raster tiles."}],"role":"symbol","url":"\/documentation\/mapboxmaps\/customrastersourcetilerenderer","navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceTileRenderer"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileFunctionCallback":{"url":"\/documentation\/mapboxmaps\/tilefunctioncallback","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TileFunctionCallback"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileFunctionCallback","type":"topic","title":"TileFunctionCallback","role":"symbol","navigatorTitle":[{"text":"TileFunctionCallback","kind":"identifier"}],"abstract":[{"type":"text","text":"Callback to do various operations for tile."},{"type":"text","text":" "},{"type":"text","text":"For example, fetching a tile or cancelling a tile request."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileRenderer/renderToTile(for:commandEncoder:)":{"required":true,"url":"\/documentation\/mapboxmaps\/customrastersourcetilerenderer\/rendertotile(for:commandencoder:)","role":"symbol","abstract":[{"type":"text","text":"Orthographic mode render to the tile. This method is called once for each tile"},{"text":" ","type":"text"},{"type":"text","text":"in every frame."},{"text":" ","type":"text"},{"text":"This method is called only if client code returns ","type":"text"},{"code":"true","type":"codeVoice"},{"text":" from the corresponding isTileRenderable() method.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Implementation should not change target framebuffer (as the render target is the tile texture)."},{"type":"text","text":" "},{"type":"text","text":"The reason is performance hit that would stem from such practice. If there’s a need for switching"},{"text":" ","type":"text"},{"type":"text","text":"rendering targets, implementation should use prerender() method."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"renderToTile"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CanonicalTileID","preciseIdentifier":"c:objc(cs)MBMCanonicalTileID"},{"kind":"text","text":", "},{"text":"commandEncoder","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s6UInt64V","kind":"typeIdentifier","text":"UInt64"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"renderToTileForTileID:commandEncoder:"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer\/renderToTile(for:commandEncoder:)","title":"renderToTile(for:commandEncoder:)","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Source":{"abstract":[],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Source"}],"title":"Source","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Source","navigatorTitle":[{"text":"Source","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/source","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/platforms","op":"add","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"MBMCustomRasterSourceTileRenderer"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileRenderer"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileRenderer"}]},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer\/deinitialize()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer\/initialize(forDevice:colorPixelFormat:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer\/isTileRenderable(for:status:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer\/prerender(for:commandBuffer:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer\/renderToTile(for:commandEncoder:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"op":"replace"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatusChangedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatus","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileFunctionCallback"],"anchor":"Sources","generated":true,"title":"Sources"}],"op":"replace"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MBMCustomRasterSourceTileRenderer","kind":"identifier"}],"languages":["occ"]}]}},{"value":"MBMCustomRasterSourceTileData","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileData\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileData"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileData\/fragments"},{"value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileData"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileData\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer~1initialize(forDevice:colorPixelFormat:)\/title","value":"initializeForDevice:colorPixelFormat:","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer~1initialize(forDevice:colorPixelFormat:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initializeForDevice:colorPixelFormat:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatus\/title","value":"MBMCustomRasterSourceTileStatus","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatus\/fragments","value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileStatus"}]},{"value":[{"text":"MBMCustomRasterSourceTileStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatus\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatusChangedCallback\/title","value":"MBMCustomRasterSourceTileStatusChangedCallback","op":"replace"},{"value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileStatusChangedCallback"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatusChangedCallback\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatusChangedCallback\/navigatorTitle","op":"replace","value":[{"text":"MBMCustomRasterSourceTileStatusChangedCallback","kind":"identifier"}]},{"value":"MBMCustomRasterSourceOptions","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/fragments","value":[{"text":"MBMCustomRasterSourceOptions","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"MBMCustomRasterSourceOptions"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/navigatorTitle","op":"replace"},{"value":"MBMCustomRasterSourceClientType","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MBMCustomRasterSourceClientType"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType\/navigatorTitle","value":[{"text":"MBMCustomRasterSourceClientType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer~1prerender(for:commandBuffer:)\/title","value":"prerenderForParameters:commandBuffer:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer~1prerender(for:commandBuffer:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"prerenderForParameters:commandBuffer:","kind":"identifier"}]},{"op":"replace","value":"MBMCustomGeometrySourceOptions","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions\/title"},{"op":"replace","value":[{"text":"MBMCustomGeometrySourceOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions\/navigatorTitle","value":[{"kind":"identifier","text":"MBMCustomGeometrySourceOptions"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient\/title","value":"MBMCustomRasterSourceClient"},{"value":[{"kind":"identifier","text":"MBMCustomRasterSourceClient"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient\/navigatorTitle","value":[{"kind":"identifier","text":"MBMCustomRasterSourceClient"}],"op":"replace"},{"value":"deinitialize","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer~1deinitialize()\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer~1deinitialize()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deinitialize"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer~1isTileRenderable(for:status:)\/title","value":"isTileRenderableForTileID:status:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"isTileRenderableForTileID:status:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer~1isTileRenderable(for:status:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer\/title","value":"MBMCustomRasterSourceTileRenderer"},{"op":"replace","value":[{"text":"MBMCustomRasterSourceTileRenderer","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer\/fragments"},{"value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileRenderer"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileFunctionCallback\/title","value":"MBMTileFunctionCallback","op":"replace"},{"value":[{"text":"MBMTileFunctionCallback","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileFunctionCallback\/fragments"},{"value":[{"text":"MBMTileFunctionCallback","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileFunctionCallback\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer~1renderToTile(for:commandEncoder:)\/title","value":"renderToTileForTileID:commandEncoder:"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer~1renderToTile(for:commandEncoder:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"renderToTileForTileID:commandEncoder:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}