{"metadata":{"modules":[{"name":"MapboxMaps"}],"externalID":"c:objc(cs)MBMDurationStatistics","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DurationStatistics","kind":"identifier"}],"navigatorTitle":[{"text":"DurationStatistics","kind":"identifier"}],"symbolKind":"class","title":"DurationStatistics","role":"symbol"},"seeAlsoSections":[{"anchor":"Performance-recording","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatistics","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CumulativeRenderingStatistics","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GroupPerformanceStatistics","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerFrameRenderingStatistics","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatisticsOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatisticsCallback"],"generated":true,"title":"Performance recording"}],"topicSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/DurationStatistics\/init(maxMillis:medianMillis:)"],"anchor":"Initializers","generated":true,"title":"Initializers"},{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/DurationStatistics\/maxMillis","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/DurationStatistics\/medianMillis"],"anchor":"Instance-Properties"}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DurationStatistics","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/DurationStatistics"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/durationstatistics"]},{"paths":["\/documentation\/mapboxmaps\/durationstatistics"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/DurationStatistics/maxMillis":{"role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxMillis"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"title":"maxMillis","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/DurationStatistics\/maxMillis","url":"\/documentation\/mapboxmaps\/durationstatistics\/maxmillis","kind":"symbol","navigatorTitle":[{"text":"maxMillis","kind":"identifier"}],"abstract":[{"type":"text","text":"The largest measured duration over the sampling window."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/DurationStatistics/medianMillis":{"navigatorTitle":[{"text":"medianMillis","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxmaps\/durationstatistics\/medianmillis","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"medianMillis","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"abstract":[{"type":"text","text":"The median duration over the sampling window."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/DurationStatistics\/medianMillis","title":"medianMillis","kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PerformanceStatisticsCallback":{"title":"PerformanceStatisticsCallback","navigatorTitle":[{"kind":"identifier","text":"PerformanceStatisticsCallback"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatisticsCallback","type":"topic","abstract":[{"text":"Use this callback to observe the collected statistics. The callback is invoked at regular intervals determined by","type":"text"},{"type":"text","text":" "},{"type":"text","text":"the sampling duration specified in the "},{"code":"PerformanceStatisticsOptions","type":"codeVoice"},{"type":"text","text":". The callback is invoked from the main thread."}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PerformanceStatisticsCallback","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/performancestatisticscallback"},"doc://com.mapbox.MapboxMaps/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PerformanceStatisticsOptions":{"abstract":[{"type":"text","text":"Options for the following statistics collection behaviors:"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PerformanceStatisticsOptions","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","title":"PerformanceStatisticsOptions","navigatorTitle":[{"kind":"identifier","text":"PerformanceStatisticsOptions"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatisticsOptions","url":"\/documentation\/mapboxmaps\/performancestatisticsoptions"},"doc://com.mapbox.MapboxMaps/SH":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","title":"Swift.Hashable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/DurationStatistics":{"title":"DurationStatistics","navigatorTitle":[{"text":"DurationStatistics","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/DurationStatistics","type":"topic","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DurationStatistics"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/durationstatistics"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Performance":{"title":"Performance and investigations","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","type":"topic","abstract":[],"role":"collectionGroup","url":"\/documentation\/mapboxmaps\/performance"},"doc://com.mapbox.MapboxMaps/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CumulativeRenderingStatistics":{"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CumulativeRenderingStatistics"}],"kind":"symbol","role":"symbol","type":"topic","title":"CumulativeRenderingStatistics","navigatorTitle":[{"kind":"identifier","text":"CumulativeRenderingStatistics"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CumulativeRenderingStatistics","url":"\/documentation\/mapboxmaps\/cumulativerenderingstatistics"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PerFrameRenderingStatistics":{"abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PerFrameRenderingStatistics","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","title":"PerFrameRenderingStatistics","navigatorTitle":[{"text":"PerFrameRenderingStatistics","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerFrameRenderingStatistics","url":"\/documentation\/mapboxmaps\/perframerenderingstatistics"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","kind":"symbol","title":"MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","role":"collection"},"doc://com.mapbox.MapboxMaps/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","title":"Swift.Equatable"},"doc://com.mapbox.MapboxMaps/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/DurationStatistics/init(maxMillis:medianMillis:)":{"navigatorTitle":[{"text":"initWithMaxMillis:medianMillis:","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxmaps\/durationstatistics\/init(maxmillis:medianmillis:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"maxMillis"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":", ","kind":"text"},{"text":"medianMillis","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":")","kind":"text"}],"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/DurationStatistics\/init(maxMillis:medianMillis:)","title":"init(maxMillis:medianMillis:)","kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GroupPerformanceStatistics":{"title":"GroupPerformanceStatistics","navigatorTitle":[{"kind":"identifier","text":"GroupPerformanceStatistics"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GroupPerformanceStatistics","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GroupPerformanceStatistics","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/groupperformancestatistics"},"doc://com.mapbox.MapboxMaps/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject","title":"NSObject"},"doc://com.mapbox.MapboxMaps/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","url":"\/documentation\/overview","abstract":[],"kind":"article","title":"MapboxMaps Documentation","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PerformanceStatistics":{"url":"\/documentation\/mapboxmaps\/performancestatistics","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PerformanceStatistics","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"PerformanceStatistics","navigatorTitle":[{"text":"PerformanceStatistics","kind":"identifier"}],"abstract":[{"text":"The performance statistics collected at the end of the sampling duration.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatistics","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"MBMDurationStatistics"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMDurationStatistics"}]},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MBMDurationStatistics"}],"op":"replace"},{"value":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/DurationStatistics\/maxMillis","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/DurationStatistics\/medianMillis"],"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/DurationStatistics\/init(maxMillis:medianMillis:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"kind":"relationships"}]},{"value":[{"anchor":"Performance-recording","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatistics","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CumulativeRenderingStatistics","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GroupPerformanceStatistics","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerFrameRenderingStatistics","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatisticsOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatisticsCallback"],"generated":true,"title":"Performance recording"}],"op":"replace","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBMDurationStatistics"},{"kind":"text","text":" : "},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}]}],"kind":"declarations"}},{"value":"maxMillis","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1DurationStatistics~1maxMillis\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1DurationStatistics~1maxMillis\/fragments","value":[{"text":"maxMillis","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"medianMillis","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1DurationStatistics~1medianMillis\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1DurationStatistics~1medianMillis\/fragments","op":"replace","value":[{"kind":"identifier","text":"medianMillis"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatisticsCallback\/title","value":"MBMPerformanceStatisticsCallback"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatisticsCallback\/fragments","value":[{"text":"MBMPerformanceStatisticsCallback","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatisticsCallback\/navigatorTitle","value":[{"text":"MBMPerformanceStatisticsCallback","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatisticsOptions\/title","value":"MBMPerformanceStatisticsOptions","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatisticsOptions\/fragments","value":[{"kind":"identifier","text":"MBMPerformanceStatisticsOptions"}]},{"value":[{"kind":"identifier","text":"MBMPerformanceStatisticsOptions"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatisticsOptions\/navigatorTitle","op":"replace"},{"op":"replace","value":"MBMDurationStatistics","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1DurationStatistics\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1DurationStatistics\/fragments","value":[{"text":"MBMDurationStatistics","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1DurationStatistics\/navigatorTitle","value":[{"text":"MBMDurationStatistics","kind":"identifier"}]},{"value":"MBMCumulativeRenderingStatistics","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CumulativeRenderingStatistics\/title"},{"value":[{"text":"MBMCumulativeRenderingStatistics","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CumulativeRenderingStatistics\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CumulativeRenderingStatistics\/navigatorTitle","value":[{"kind":"identifier","text":"MBMCumulativeRenderingStatistics"}],"op":"replace"},{"value":"MBMPerFrameRenderingStatistics","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerFrameRenderingStatistics\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerFrameRenderingStatistics\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMPerFrameRenderingStatistics"}]},{"value":[{"text":"MBMPerFrameRenderingStatistics","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerFrameRenderingStatistics\/navigatorTitle"},{"op":"replace","value":"initWithMaxMillis:medianMillis:","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1DurationStatistics~1init(maxMillis:medianMillis:)\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1DurationStatistics~1init(maxMillis:medianMillis:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithMaxMillis:medianMillis:","kind":"identifier"}]},{"value":"MBMGroupPerformanceStatistics","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GroupPerformanceStatistics\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GroupPerformanceStatistics\/fragments","value":[{"text":"MBMGroupPerformanceStatistics","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"MBMGroupPerformanceStatistics"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GroupPerformanceStatistics\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatistics\/title","value":"MBMPerformanceStatistics"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatistics\/fragments","op":"replace","value":[{"text":"MBMPerformanceStatistics","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatistics\/navigatorTitle","value":[{"kind":"identifier","text":"MBMPerformanceStatistics"}],"op":"replace"}]}]}