{"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/init(from:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/init(id:source:)"],"anchor":"Initializers","generated":true},{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/filter","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/heatmapColor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/heatmapIntensity","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/heatmapIntensityTransition","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/heatmapOpacity","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/heatmapOpacityTransition","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/heatmapRadius","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/heatmapRadiusTransition","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/heatmapWeight","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/id","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/maxZoom","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/minZoom","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/slot","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/source","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/sourceLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/type","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/visibility"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/encode(to:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/filter(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/heatmapColor(_:)-2l9xn","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/heatmapColor(_:)-9xgym","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/heatmapColor(_:)-vh6b","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/heatmapIntensity(_:)-3q4gs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/heatmapIntensity(_:)-8nqpc","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/heatmapIntensityTransition(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/heatmapOpacity(_:)-34y65","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/heatmapOpacity(_:)-7mlaj","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/heatmapOpacityTransition(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/heatmapRadius(_:)-1jo2n","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/heatmapRadius(_:)-5kvbp","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/heatmapRadiusTransition(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/heatmapWeight(_:)-9rlcb","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/heatmapWeight(_:)-gan","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/maxZoom(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/minZoom(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/slot(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/source(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/sourceLayer(_:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"},{"anchor":"Default-Implementations","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/Equatable-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/Layer-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/StyleEncodable-Implementations"],"title":"Default Implementations","generated":true}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers"]]},"metadata":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeatmapLayer"}],"roleHeading":"Structure","externalID":"s:10MapboxMaps12HeatmapLayerV","navigatorTitle":[{"text":"HeatmapLayer","kind":"identifier"}],"role":"symbol","title":"HeatmapLayer","symbolKind":"struct","modules":[{"name":"MapboxMaps"}]},"relationshipsSections":[{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapStyleContent","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDecodable","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleEncodable","doc:\/\/com.mapbox.MapboxMaps\/s8CopyableP","doc:\/\/com.mapbox.MapboxMaps\/Se","doc:\/\/com.mapbox.MapboxMaps\/SE","doc:\/\/com.mapbox.MapboxMaps\/SQ"]}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerInfo","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/BackgroundLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CircleLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillExtrusionLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationIndicatorLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterParticleLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SkyLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderConfiguration","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerHost","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ElevationData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Slot","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SlotLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerAtPosition","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClipLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClipLayerTypes"],"generated":true,"title":"Layers","anchor":"Layers"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"HeatmapLayer","kind":"identifier"}]}]},{"content":[{"text":"Overview","anchor":"overview","level":2,"type":"heading"},{"content":[{"inlineContent":[{"text":"","type":"text"},{"isActive":true,"type":"reference","identifier":"https:\/\/www.mapbox.com\/mapbox-gl-style-spec\/#layers-heatmap"}],"type":"paragraph"}],"type":"aside","name":"See Also","style":"note"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/heatmaplayer"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer"},"kind":"symbol","abstract":[{"type":"text","text":"A heatmap."}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeatmapLayer/init(id:source:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"id","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"source"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"url":"\/documentation\/mapboxmaps\/heatmaplayer\/init(id:source:)","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/init(id:source:)","title":"init(id:source:)","kind":"symbol","type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeatmapLayer/heatmapOpacity(_:)-7mlaj":{"url":"\/documentation\/mapboxmaps\/heatmaplayer\/heatmapopacity(_:)-7mlaj","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/heatmapOpacity(_:)-7mlaj","abstract":[{"type":"text","text":"The global opacity at which the heatmap layer will be drawn."},{"text":" ","type":"text"},{"text":"Default value: 1. Value range: [0, 1]","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"heatmapOpacity","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps3ExpV","text":"Exp","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"HeatmapLayer","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps12HeatmapLayerV"}],"title":"heatmapOpacity(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeatmapLayer/Layer-Implementations":{"url":"\/documentation\/mapboxmaps\/heatmaplayer\/layer-implementations","title":"Layer Implementations","type":"topic","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/Layer-Implementations","abstract":[],"role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LocationIndicatorLayer":{"url":"\/documentation\/mapboxmaps\/locationindicatorlayer","abstract":[{"type":"text","text":"Location Indicator layer."}],"role":"symbol","title":"LocationIndicatorLayer","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationIndicatorLayer"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationIndicatorLayer","kind":"symbol","navigatorTitle":[{"text":"LocationIndicatorLayer","kind":"identifier"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SlotLayer":{"url":"\/documentation\/mapboxmaps\/slotlayer","abstract":[{"text":"Marks the position of a slot.","type":"text"}],"role":"symbol","title":"SlotLayer","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SlotLayer"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SlotLayer","kind":"symbol","navigatorTitle":[{"text":"SlotLayer","kind":"identifier"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SymbolLayer":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"SymbolLayer","kind":"identifier"}],"abstract":[{"text":"An icon or a text label.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolLayer","title":"SymbolLayer","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SymbolLayer"}],"url":"\/documentation\/mapboxmaps\/symbollayer","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeatmapLayer":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer","type":"topic","role":"symbol","title":"HeatmapLayer","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HeatmapLayer","kind":"identifier"}],"navigatorTitle":[{"text":"HeatmapLayer","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/heatmaplayer","abstract":[{"text":"A heatmap.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeatmapLayer/StyleEncodable-Implementations":{"url":"\/documentation\/mapboxmaps\/heatmaplayer\/styleencodable-implementations","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/StyleEncodable-Implementations","role":"collectionGroup","type":"topic","title":"StyleEncodable Implementations","kind":"article","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeatmapLayer/minZoom(_:)":{"abstract":[{"type":"text","text":"The minimum zoom level for the layer. At zoom levels less than the minzoom, the layer will be hidden."}],"role":"symbol","url":"\/documentation\/mapboxmaps\/heatmaplayer\/minzoom(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"minZoom"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"HeatmapLayer","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps12HeatmapLayerV"}],"title":"minZoom(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/minZoom(_:)","kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeatmapLayer/heatmapWeight":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"heatmapWeight","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps5ValueO","text":"Value"},{"kind":"text","text":"<"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":">?"}],"abstract":[{"type":"text","text":"A measure of how much an individual point contributes to the heatmap. A value of 10 would be equivalent to having 10 points of weight 1 in the same spot. Especially useful when combined with clustering."},{"text":" ","type":"text"},{"text":"Default value: 1. Minimum value: 0.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/heatmapWeight","role":"symbol","kind":"symbol","title":"heatmapWeight","url":"\/documentation\/mapboxmaps\/heatmaplayer\/heatmapweight"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/BackgroundLayer":{"navigatorTitle":[{"text":"BackgroundLayer","kind":"identifier"}],"role":"symbol","title":"BackgroundLayer","abstract":[{"text":"The background color or pattern of the map.","type":"text"}],"url":"\/documentation\/mapboxmaps\/backgroundlayer","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/BackgroundLayer","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"BackgroundLayer","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerAtPosition":{"url":"\/documentation\/mapboxmaps\/layeratposition","abstract":[],"role":"symbol","title":"LayerAtPosition","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"LayerAtPosition","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerAtPosition","kind":"symbol","navigatorTitle":[{"text":"LayerAtPosition","kind":"identifier"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layer":{"navigatorTitle":[{"text":"Layer","kind":"identifier"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Layer"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer","title":"Layer","role":"symbol","url":"\/documentation\/mapboxmaps\/layer"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FillLayer":{"kind":"symbol","abstract":[{"text":"A filled polygon with an optional stroked border.","type":"text"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FillLayer","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/filllayer","navigatorTitle":[{"text":"FillLayer","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillLayer","type":"topic","title":"FillLayer"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapStyleContent":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapStyleContent","type":"topic","title":"MapStyleContent","kind":"symbol","navigatorTitle":[{"text":"MapStyleContent","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/mapstylecontent","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapStyleContent","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol used to create any type of  map style content, such as layers, sources, lighting and others."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layers":{"title":"Layers","url":"\/documentation\/mapboxmaps\/layers","kind":"article","role":"collectionGroup","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeatmapLayer/heatmapWeight(_:)-gan":{"title":"heatmapWeight(_:)","url":"\/documentation\/mapboxmaps\/heatmaplayer\/heatmapweight(_:)-gan","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/heatmapWeight(_:)-gan","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"heatmapWeight"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps3ExpV","text":"Exp","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps12HeatmapLayerV","kind":"typeIdentifier","text":"HeatmapLayer"}],"abstract":[{"type":"text","text":"A measure of how much an individual point contributes to the heatmap. A value of 10 would be equivalent to having 10 points of weight 1 in the same spot. Especially useful when combined with clustering."},{"type":"text","text":" "},{"type":"text","text":"Default value: 1. Minimum value: 0."}],"type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeatmapLayer/filter":{"type":"topic","kind":"symbol","abstract":[{"text":"An expression specifying conditions on source features.","type":"text"},{"text":" ","type":"text"},{"text":"Only features that match the filter are displayed.","type":"text"}],"url":"\/documentation\/mapboxmaps\/heatmaplayer\/filter","title":"filter","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"filter"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps3ExpV","text":"Exp"},{"text":"?","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/filter"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LineLayer":{"abstract":[{"text":"A stroked line.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"LineLayer","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineLayer","url":"\/documentation\/mapboxmaps\/linelayer","title":"LineLayer","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LineLayer"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterLayer":{"title":"RasterLayer","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RasterLayer","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"RasterLayer"}],"url":"\/documentation\/mapboxmaps\/rasterlayer","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterLayer","abstract":[{"type":"text","text":"Raster map textures such as satellite imagery."}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeatmapLayer/heatmapIntensity":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"heatmapIntensity"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps5ValueO","text":"Value"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":">?"}],"title":"heatmapIntensity","type":"topic","url":"\/documentation\/mapboxmaps\/heatmaplayer\/heatmapintensity","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/heatmapIntensity","abstract":[{"type":"text","text":"Similar to "},{"code":"heatmap-weight","type":"codeVoice"},{"text":" but controls the intensity of the heatmap globally. Primarily used for adjusting the heatmap based on zoom level.","type":"text"},{"type":"text","text":" "},{"text":"Default value: 1. Minimum value: 0.","type":"text"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeatmapLayer/sourceLayer(_:)":{"url":"\/documentation\/mapboxmaps\/heatmaplayer\/sourcelayer(_:)","type":"topic","title":"sourceLayer(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"sourceLayer","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps12HeatmapLayerV","kind":"typeIdentifier","text":"HeatmapLayer"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/sourceLayer(_:)","abstract":[{"type":"text","text":"Layer to use from a vector tile source."}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeatmapLayer/heatmapIntensity(_:)-3q4gs":{"type":"topic","title":"heatmapIntensity(_:)","abstract":[{"text":"Similar to ","type":"text"},{"code":"heatmap-weight","type":"codeVoice"},{"text":" but controls the intensity of the heatmap globally. Primarily used for adjusting the heatmap based on zoom level.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Default value: 1. Minimum value: 0."}],"url":"\/documentation\/mapboxmaps\/heatmaplayer\/heatmapintensity(_:)-3q4gs","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/heatmapIntensity(_:)-3q4gs","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"heatmapIntensity","kind":"identifier"},{"kind":"text","text":"("},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:10MapboxMaps12HeatmapLayerV","text":"HeatmapLayer","kind":"typeIdentifier"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeatmapLayer/heatmapOpacity":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"heatmapOpacity"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10MapboxMaps5ValueO","text":"Value","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":">?"}],"title":"heatmapOpacity","type":"topic","url":"\/documentation\/mapboxmaps\/heatmaplayer\/heatmapopacity","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/heatmapOpacity","abstract":[{"text":"The global opacity at which the heatmap layer will be drawn.","type":"text"},{"text":" ","type":"text"},{"text":"Default value: 1. Value range: [0, 1]","type":"text"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeatmapLayer/maxZoom":{"role":"symbol","title":"maxZoom","url":"\/documentation\/mapboxmaps\/heatmaplayer\/maxzoom","type":"topic","abstract":[{"text":"The maximum zoom level for the layer. At zoom levels equal to or greater than the maxzoom, the layer will be hidden.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maxZoom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/maxZoom","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Atmosphere":{"url":"\/documentation\/mapboxmaps\/atmosphere","title":"Atmosphere","type":"topic","kind":"symbol","navigatorTitle":[{"text":"Atmosphere","kind":"identifier"}],"abstract":[{"text":"A style’s fog property is a global effect that improves depth perception by fading out distant objects.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Atmosphere","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Atmosphere"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeatmapLayer/minZoom":{"url":"\/documentation\/mapboxmaps\/heatmaplayer\/minzoom","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/minZoom","role":"symbol","type":"topic","title":"minZoom","kind":"symbol","abstract":[{"text":"The minimum zoom level for the layer. At zoom levels less than the minzoom, the layer will be hidden.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"minZoom","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"text":"?","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeatmapLayer/heatmapRadius(_:)-5kvbp":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/heatmapRadius(_:)-5kvbp","url":"\/documentation\/mapboxmaps\/heatmaplayer\/heatmapradius(_:)-5kvbp","role":"symbol","kind":"symbol","title":"heatmapRadius(_:)","abstract":[{"type":"text","text":"Radius of influence of one heatmap point in pixels. Increasing the value makes the heatmap smoother, but less detailed. "},{"code":"queryRenderedFeatures","type":"codeVoice"},{"type":"text","text":" on heatmap layers will return points within this radius."},{"text":" ","type":"text"},{"type":"text","text":"Default value: 30. Minimum value: 1."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"heatmapRadius","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:10MapboxMaps3ExpV","kind":"typeIdentifier","text":"Exp"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps12HeatmapLayerV","kind":"typeIdentifier","text":"HeatmapLayer"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeatmapLayer/heatmapIntensityTransition(_:)":{"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"heatmapIntensityTransition"},{"kind":"text","text":"("},{"text":"StyleTransition","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps15StyleTransitionV"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"HeatmapLayer","preciseIdentifier":"s:10MapboxMaps12HeatmapLayerV"}],"url":"\/documentation\/mapboxmaps\/heatmaplayer\/heatmapintensitytransition(_:)","type":"topic","abstract":[{"text":"Transition property for ","type":"text"},{"type":"codeVoice","code":"heatmapIntensity"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/heatmapIntensityTransition(_:)","title":"heatmapIntensityTransition(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeatmapLayer/visibility":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"visibility"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps5ValueO","text":"Value"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps10VisibilityO","kind":"typeIdentifier","text":"Visibility"},{"kind":"text","text":">"}],"title":"visibility","type":"topic","url":"\/documentation\/mapboxmaps\/heatmaplayer\/visibility","role":"symbol","kind":"symbol","abstract":[{"text":"Whether this layer is displayed.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/visibility"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerHost":{"url":"\/documentation\/mapboxmaps\/customlayerhost","abstract":[{"text":"Interface for hosting a custom map style layer.","type":"text"}],"role":"symbol","title":"CustomLayerHost","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomLayerHost","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerHost","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CustomLayerHost"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeatmapLayer/slot":{"title":"slot","url":"\/documentation\/mapboxmaps\/heatmaplayer\/slot","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/slot","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"slot","kind":"identifier"},{"kind":"text","text":": "},{"text":"Slot","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps4SlotV"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The slot this layer is assigned to. If specified, and a slot with that name exists, it will be placed at that position in the layer order."}],"type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeatmapLayer/slot(_:)":{"type":"topic","title":"slot(_:)","abstract":[{"text":"The slot this layer is assigned to.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If specified, and a slot with that name exists, it will be placed at that position in the layer order."}],"url":"\/documentation\/mapboxmaps\/heatmaplayer\/slot(_:)","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/slot(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"slot","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:10MapboxMaps4SlotV","text":"Slot","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"text":"HeatmapLayer","preciseIdentifier":"s:10MapboxMaps12HeatmapLayerV","kind":"typeIdentifier"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerInfo":{"url":"\/documentation\/mapboxmaps\/layerinfo","abstract":[{"type":"text","text":"Information about a layer"}],"role":"symbol","title":"LayerInfo","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LayerInfo"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerInfo","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"LayerInfo"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ClipLayer":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClipLayer","title":"ClipLayer","url":"\/documentation\/mapboxmaps\/cliplayer","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"ClipLayer","kind":"identifier"}],"tags":[{"text":"SPI","type":"spi"}],"role":"symbol","abstract":[{"type":"text","text":"Layer that removes 3D content from map."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ClipLayer"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerRenderParameters":{"url":"\/documentation\/mapboxmaps\/customlayerrenderparameters","abstract":[{"text":"Parameters that define the current camera position for a ","type":"text"},{"type":"codeVoice","code":"CustomLayerHost::render()"},{"type":"text","text":" function."}],"role":"symbol","title":"CustomLayerRenderParameters","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CustomLayerRenderParameters","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters","kind":"symbol","navigatorTitle":[{"text":"CustomLayerRenderParameters","kind":"identifier"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","role":"collection","title":"MapboxMaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps"},"doc://com.mapbox.MapboxMaps/s8CopyableP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s8CopyableP","title":"Swift.Copyable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleEncodable":{"title":"StyleEncodable","url":"\/documentation\/mapboxmaps\/styleencodable","type":"topic","kind":"symbol","navigatorTitle":[{"text":"StyleEncodable","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol describing a style-related entity that can be encoded."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleEncodable","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"StyleEncodable"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CircleLayer":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CircleLayer","abstract":[{"text":"A filled circle.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CircleLayer","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"CircleLayer","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/circlelayer","title":"CircleLayer","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeatmapLayer/heatmapOpacityTransition":{"type":"topic","title":"heatmapOpacityTransition","abstract":[{"text":"Transition options for ","type":"text"},{"code":"heatmapOpacity","type":"codeVoice"},{"text":".","type":"text"}],"url":"\/documentation\/mapboxmaps\/heatmaplayer\/heatmapopacitytransition","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/heatmapOpacityTransition","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"heatmapOpacityTransition"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps15StyleTransitionV","kind":"typeIdentifier","text":"StyleTransition"},{"kind":"text","text":"?"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeatmapLayer/heatmapColor":{"title":"heatmapColor","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/heatmapColor","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Defines the color of each pixel based on its density value in a heatmap. Should be an expression that uses "},{"type":"codeVoice","code":"[\"heatmap-density\"]"},{"type":"text","text":" as input."},{"type":"text","text":" "},{"text":"Default value: [“interpolate”,[“linear”],[“heatmap-density”],0,“rgba(0, 0, 255, 0)”,0.1,“royalblue”,0.3,“cyan”,0.5,“lime”,0.7,“yellow”,1,“red”].","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"heatmapColor"},{"text":": ","kind":"text"},{"text":"Value","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps5ValueO"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:10MapboxMaps10StyleColorV","kind":"typeIdentifier","text":"StyleColor"},{"text":">?","kind":"text"}],"url":"\/documentation\/mapboxmaps\/heatmaplayer\/heatmapcolor"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeatmapLayer/heatmapColor(_:)-vh6b":{"url":"\/documentation\/mapboxmaps\/heatmaplayer\/heatmapcolor(_:)-vh6b","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/heatmapColor(_:)-vh6b","type":"topic","abstract":[{"text":"Defines the color of each pixel based on its density value in a heatmap. Should be an expression that uses ","type":"text"},{"code":"[\"heatmap-density\"]","type":"codeVoice"},{"type":"text","text":" as input."},{"text":" ","type":"text"},{"text":"Default value: [“interpolate”,[“linear”],[“heatmap-density”],0,“rgba(0, 0, 255, 0)”,0.1,“royalblue”,0.3,“cyan”,0.5,“lime”,0.7,“yellow”,1,“red”].","type":"text"}],"title":"heatmapColor(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"heatmapColor"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps12HeatmapLayerV","kind":"typeIdentifier","text":"HeatmapLayer"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FillExtrusionLayer":{"abstract":[{"type":"text","text":"An extruded (3D) polygon."}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillExtrusionLayer","title":"FillExtrusionLayer","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FillExtrusionLayer","kind":"identifier"}],"navigatorTitle":[{"text":"FillExtrusionLayer","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/fillextrusionlayer"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayer":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayer","title":"CustomLayer","url":"\/documentation\/mapboxmaps\/customlayer","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"CustomLayer","kind":"identifier"}],"tags":[{"type":"spi","text":"SPI"}],"role":"symbol","abstract":[{"type":"text","text":"Layer with custom rendering implementation"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"CustomLayer"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeatmapLayer/heatmapRadiusTransition":{"role":"symbol","type":"topic","title":"heatmapRadiusTransition","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"heatmapRadiusTransition","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"StyleTransition","preciseIdentifier":"s:10MapboxMaps15StyleTransitionV"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Transition options for "},{"type":"codeVoice","code":"heatmapRadius"},{"type":"text","text":"."}],"url":"\/documentation\/mapboxmaps\/heatmaplayer\/heatmapradiustransition","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/heatmapRadiusTransition"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeatmapLayer/heatmapRadiusTransition(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"heatmapRadiusTransition"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"StyleTransition","preciseIdentifier":"s:10MapboxMaps15StyleTransitionV"},{"text":") -> ","kind":"text"},{"text":"HeatmapLayer","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps12HeatmapLayerV"}],"title":"heatmapRadiusTransition(_:)","type":"topic","url":"\/documentation\/mapboxmaps\/heatmaplayer\/heatmapradiustransition(_:)","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/heatmapRadiusTransition(_:)","abstract":[{"type":"text","text":"Transition property for "},{"code":"heatmapRadius","type":"codeVoice"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ClipLayerTypes":{"url":"\/documentation\/mapboxmaps\/cliplayertypes","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClipLayerTypes","title":"ClipLayerTypes","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ClipLayerTypes"}],"type":"topic","role":"symbol","abstract":[{"text":"Layer types that will also be removed if fallen below this clip layer.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ClipLayerTypes"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeatmapLayer/sourceLayer":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/sourceLayer","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sourceLayer","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"abstract":[{"text":"Layer to use from a vector tile source.","type":"text"}],"type":"topic","url":"\/documentation\/mapboxmaps\/heatmaplayer\/sourcelayer","title":"sourceLayer"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ElevationData":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ElevationData","title":"ElevationData","url":"\/documentation\/mapboxmaps\/elevationdata","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ElevationData"}],"role":"symbol","abstract":[{"text":"Interface that provides access to elevation data.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ElevationData"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeatmapLayer/heatmapWeight(_:)-9rlcb":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/heatmapWeight(_:)-9rlcb","title":"heatmapWeight(_:)","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"heatmapWeight","kind":"identifier"},{"kind":"text","text":"("},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"HeatmapLayer","preciseIdentifier":"s:10MapboxMaps12HeatmapLayerV","kind":"typeIdentifier"}],"url":"\/documentation\/mapboxmaps\/heatmaplayer\/heatmapweight(_:)-9rlcb","abstract":[{"text":"A measure of how much an individual point contributes to the heatmap. A value of 10 would be equivalent to having 10 points of weight 1 in the same spot. Especially useful when combined with clustering.","type":"text"},{"text":" ","type":"text"},{"text":"Default value: 1. Minimum value: 0.","type":"text"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeatmapLayer/heatmapColor(_:)-2l9xn":{"url":"\/documentation\/mapboxmaps\/heatmaplayer\/heatmapcolor(_:)-2l9xn","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/heatmapColor(_:)-2l9xn","type":"topic","abstract":[{"type":"text","text":"Defines the color of each pixel based on its density value in a heatmap. Should be an expression that uses "},{"type":"codeVoice","code":"[\"heatmap-density\"]"},{"text":" as input.","type":"text"},{"text":" ","type":"text"},{"text":"Default value: [“interpolate”,[“linear”],[“heatmap-density”],0,“rgba(0, 0, 255, 0)”,0.1,“royalblue”,0.3,“cyan”,0.5,“lime”,0.7,“yellow”,1,“red”].","type":"text"}],"title":"heatmapColor(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"heatmapColor","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps10StyleColorV","text":"StyleColor"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:10MapboxMaps12HeatmapLayerV","text":"HeatmapLayer","kind":"typeIdentifier"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeatmapLayer/filter(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"filter"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Exp","preciseIdentifier":"s:10MapboxMaps3ExpV"},{"text":") -> ","kind":"text"},{"text":"HeatmapLayer","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps12HeatmapLayerV"}],"title":"filter(_:)","type":"topic","url":"\/documentation\/mapboxmaps\/heatmaplayer\/filter(_:)","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/filter(_:)","abstract":[{"text":"An expression specifying conditions on source features.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Only features that match the filter are displayed."}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterParticleLayer":{"url":"\/documentation\/mapboxmaps\/rasterparticlelayer","abstract":[{"type":"text","text":"Particle animation driven by textures such as wind maps."}],"role":"symbol","title":"RasterParticleLayer","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"RasterParticleLayer"}],"tags":[{"type":"spi","text":"SPI"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterParticleLayer","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"RasterParticleLayer"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeatmapLayer/type":{"url":"\/documentation\/mapboxmaps\/heatmaplayer\/type","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/type","type":"topic","abstract":[{"type":"text","text":"Rendering type of this layer."}],"title":"type","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"LayerType","preciseIdentifier":"s:10MapboxMaps9LayerTypeV"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeatmapLayer/id":{"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"id"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"url":"\/documentation\/mapboxmaps\/heatmaplayer\/id","type":"topic","abstract":[{"type":"text","text":"Unique layer name"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/id","title":"id"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SkyLayer":{"url":"\/documentation\/mapboxmaps\/skylayer","abstract":[{"type":"text","text":"A spherical dome around the map that is always rendered behind all other layers."},{"text":" ","type":"text"},{"type":"text","text":"Warning: As of v10.6.0, "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Atmosphere"},{"text":" is the preferred method for atmospheric styling. Sky layer is not supported by the globe projection, and will be phased out in future major release.","type":"text"}],"role":"symbol","title":"SkyLayer","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"SkyLayer","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SkyLayer","kind":"symbol","navigatorTitle":[{"text":"SkyLayer","kind":"identifier"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeatmapLayer/heatmapIntensityTransition":{"role":"symbol","title":"heatmapIntensityTransition","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"heatmapIntensityTransition","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10MapboxMaps15StyleTransitionV","text":"StyleTransition","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/heatmaplayer\/heatmapintensitytransition","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/heatmapIntensityTransition","abstract":[{"text":"Transition options for ","type":"text"},{"type":"codeVoice","code":"heatmapIntensity"},{"text":".","type":"text"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/SE":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SE","title":"Swift.Encodable","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeatmapLayer/source(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"source","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:10MapboxMaps12HeatmapLayerV","text":"HeatmapLayer","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/source(_:)","kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/heatmaplayer\/source(_:)","abstract":[{"type":"text","text":"Name of a source description to be used for this layer."},{"text":" ","type":"text"},{"type":"text","text":"Required for all layer types except "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/BackgroundLayer","isActive":true,"type":"reference"},{"text":", ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SkyLayer"},{"text":", and ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationIndicatorLayer","isActive":true},{"type":"text","text":"."}],"title":"source(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerRenderConfiguration":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderConfiguration","title":"CustomLayerRenderConfiguration","url":"\/documentation\/mapboxmaps\/customlayerrenderconfiguration","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CustomLayerRenderConfiguration"}],"role":"symbol","abstract":[{"type":"text","text":"Note! This is an experimental feature. It can be changed or removed in future versions."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"CustomLayerRenderConfiguration"}]},"https://www.mapbox.com/mapbox-gl-style-spec/#layers-heatmap":{"titleInlineContent":[{"text":"Mapbox Style Specification","type":"text"}],"url":"https:\/\/www.mapbox.com\/mapbox-gl-style-spec\/#layers-heatmap","identifier":"https:\/\/www.mapbox.com\/mapbox-gl-style-spec\/#layers-heatmap","title":"Mapbox Style Specification","type":"link"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeatmapLayer/heatmapRadius(_:)-1jo2n":{"role":"symbol","url":"\/documentation\/mapboxmaps\/heatmaplayer\/heatmapradius(_:)-1jo2n","abstract":[{"type":"text","text":"Radius of influence of one heatmap point in pixels. Increasing the value makes the heatmap smoother, but less detailed. "},{"type":"codeVoice","code":"queryRenderedFeatures"},{"type":"text","text":" on heatmap layers will return points within this radius."},{"text":" ","type":"text"},{"text":"Default value: 30. Minimum value: 1.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/heatmapRadius(_:)-1jo2n","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"heatmapRadius","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HeatmapLayer","preciseIdentifier":"s:10MapboxMaps12HeatmapLayerV"}],"kind":"symbol","type":"topic","title":"heatmapRadius(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeatmapLayer/Equatable-Implementations":{"title":"Equatable Implementations","type":"topic","url":"\/documentation\/mapboxmaps\/heatmaplayer\/equatable-implementations","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/Equatable-Implementations","abstract":[],"kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleDecodable":{"url":"\/documentation\/mapboxmaps\/styledecodable","title":"StyleDecodable","type":"topic","kind":"symbol","navigatorTitle":[{"text":"StyleDecodable","kind":"identifier"}],"abstract":[{"text":"A protocol describing a style-related entity that can be decoded.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDecodable","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"StyleDecodable"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeatmapLayer/heatmapIntensity(_:)-8nqpc":{"title":"heatmapIntensity(_:)","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/heatmapIntensity(_:)-8nqpc","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"heatmapIntensity"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps3ExpV","text":"Exp"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:10MapboxMaps12HeatmapLayerV","text":"HeatmapLayer","kind":"typeIdentifier"}],"abstract":[{"text":"Similar to ","type":"text"},{"code":"heatmap-weight","type":"codeVoice"},{"text":" but controls the intensity of the heatmap globally. Primarily used for adjusting the heatmap based on zoom level.","type":"text"},{"text":" ","type":"text"},{"text":"Default value: 1. Minimum value: 0.","type":"text"}],"url":"\/documentation\/mapboxmaps\/heatmaplayer\/heatmapintensity(_:)-8nqpc"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeatmapLayer/source":{"title":"source","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/source","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"source"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"abstract":[{"text":"Name of a source description to be used for this layer.","type":"text"},{"text":" ","type":"text"},{"text":"Required for all layer types except ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/BackgroundLayer","type":"reference"},{"text":", ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SkyLayer","isActive":true},{"type":"text","text":", and "},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationIndicatorLayer","isActive":true},{"text":".","type":"text"}],"url":"\/documentation\/mapboxmaps\/heatmaplayer\/source"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeatmapLayer/heatmapOpacityTransition(_:)":{"title":"heatmapOpacityTransition(_:)","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/heatmapOpacityTransition(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"heatmapOpacityTransition","kind":"identifier"},{"kind":"text","text":"("},{"text":"StyleTransition","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps15StyleTransitionV"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps12HeatmapLayerV","kind":"typeIdentifier","text":"HeatmapLayer"}],"abstract":[{"text":"Transition property for ","type":"text"},{"code":"heatmapOpacity","type":"codeVoice"}],"url":"\/documentation\/mapboxmaps\/heatmaplayer\/heatmapopacitytransition(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeatmapLayer/encode(to:)":{"title":"encode(to:)","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/encode(to:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"encode"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"kind":"text","text":": any "},{"text":"Encoder","preciseIdentifier":"s:s7EncoderP","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"abstract":[],"url":"\/documentation\/mapboxmaps\/heatmaplayer\/encode(to:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeatmapLayer/heatmapOpacity(_:)-34y65":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"heatmapOpacity","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HeatmapLayer","preciseIdentifier":"s:10MapboxMaps12HeatmapLayerV"}],"title":"heatmapOpacity(_:)","type":"topic","url":"\/documentation\/mapboxmaps\/heatmaplayer\/heatmapopacity(_:)-34y65","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The global opacity at which the heatmap layer will be drawn."},{"type":"text","text":" "},{"text":"Default value: 1. Value range: [0, 1]","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/heatmapOpacity(_:)-34y65"},"doc://com.mapbox.MapboxMaps/Se":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/Se","title":"Swift.Decodable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeatmapLayer/maxZoom(_:)":{"title":"maxZoom(_:)","abstract":[{"text":"The maximum zoom level for the layer. At zoom levels equal to or greater than the maxzoom, the layer will be hidden.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxZoom"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:10MapboxMaps12HeatmapLayerV","text":"HeatmapLayer","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/maxZoom(_:)","url":"\/documentation\/mapboxmaps\/heatmaplayer\/maxzoom(_:)","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer","abstract":[{"type":"text","text":"Client-side hillshading visualization based on DEM data. Currently, the implementation only supports Mapbox Terrain RGB and Mapzen Terrarium tiles."}],"url":"\/documentation\/mapboxmaps\/hillshadelayer","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"HillshadeLayer","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"HillshadeLayer"}],"title":"HillshadeLayer","role":"symbol","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","kind":"article","type":"topic","url":"\/documentation\/overview","title":"MapboxMaps Documentation","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeatmapLayer/init(from:)":{"kind":"symbol","role":"symbol","type":"topic","title":"init(from:)","url":"\/documentation\/mapboxmaps\/heatmaplayer\/init(from:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"s:s7DecoderP","kind":"typeIdentifier","text":"Decoder"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/init(from:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerType":{"abstract":[{"type":"text","text":"Struct of supported Layer rendering types"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LayerType"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType","title":"LayerType","navigatorTitle":[{"text":"LayerType","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/layertype"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeatmapLayer/heatmapColor(_:)-9xgym":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Defines the color of each pixel based on its density value in a heatmap. Should be an expression that uses "},{"type":"codeVoice","code":"[\"heatmap-density\"]"},{"type":"text","text":" as input."},{"text":" ","type":"text"},{"type":"text","text":"Default value: [“interpolate”,[“linear”],[“heatmap-density”],0,“rgba(0, 0, 255, 0)”,0.1,“royalblue”,0.3,“cyan”,0.5,“lime”,0.7,“yellow”,1,“red”]."}],"type":"topic","url":"\/documentation\/mapboxmaps\/heatmaplayer\/heatmapcolor(_:)-9xgym","title":"heatmapColor(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"heatmapColor"},{"kind":"text","text":"("},{"text":"Exp","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps3ExpV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HeatmapLayer","preciseIdentifier":"s:10MapboxMaps12HeatmapLayerV"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/heatmapColor(_:)-9xgym"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Slot":{"navigatorTitle":[{"kind":"identifier","text":"Slot"}],"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Slot","kind":"identifier"}],"abstract":[{"type":"text","text":"A pre-specified location in the style where layer will be added to"},{"text":" ","type":"text"},{"text":"(such as on top of existing land layers, but below all labels).","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Slot","title":"Slot","role":"symbol","url":"\/documentation\/mapboxmaps\/slot"},"doc://com.mapbox.MapboxMaps/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeatmapLayer/heatmapRadius":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"heatmapRadius","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Value","preciseIdentifier":"s:10MapboxMaps5ValueO"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":">?"}],"title":"heatmapRadius","type":"topic","url":"\/documentation\/mapboxmaps\/heatmaplayer\/heatmapradius","role":"symbol","kind":"symbol","abstract":[{"text":"Radius of influence of one heatmap point in pixels. Increasing the value makes the heatmap smoother, but less detailed. ","type":"text"},{"code":"queryRenderedFeatures","type":"codeVoice"},{"text":" on heatmap layers will return points within this radius.","type":"text"},{"type":"text","text":" "},{"text":"Default value: 30. Minimum value: 1.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer\/heatmapRadius"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelLayer":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer","title":"ModelLayer","url":"\/documentation\/mapboxmaps\/modellayer","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ModelLayer"}],"tags":[{"type":"spi","text":"SPI"}],"role":"symbol","abstract":[{"text":"A layer to render 3D Models.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ModelLayer"}]}},"variantOverrides":[{"patch":[{"value":"MBMCustomLayerHost","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost\/fragments","value":[{"text":"MBMCustomLayerHost","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost\/navigatorTitle","value":[{"text":"MBMCustomLayerHost","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/title","value":"MBMCustomLayerRenderParameters"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/fragments","value":[{"kind":"identifier","text":"MBMCustomLayerRenderParameters"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/navigatorTitle","value":[{"text":"MBMCustomLayerRenderParameters","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ElevationData\/title","value":"MBMElevationData"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ElevationData\/fragments","value":[{"kind":"identifier","text":"MBMElevationData"}]},{"op":"replace","value":[{"kind":"identifier","text":"MBMElevationData"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ElevationData\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderConfiguration\/title","value":"MBMCustomLayerRenderConfiguration"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderConfiguration\/fragments","value":[{"kind":"identifier","text":"MBMCustomLayerRenderConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMCustomLayerRenderConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}