{"seeAlsoSections":[{"title":"Other","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Camera-and-coordinates","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Ornaments","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Gestures","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Settings-and-Constants"],"anchor":"Other"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"article","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"]]},"metadata":{"modules":[{"name":"MapboxMaps"}],"role":"collectionGroup","title":"Location","roleHeading":"API Collection"},"sections":[],"topicSections":[{"anchor":"Location","title":"Location","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationManager","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck2DConfiguration","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Model","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckBearing","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProviderDelegate","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Coordinate2D","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationExtraKeys","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProviderRequest","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceFactory","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/DeviceLocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Heading","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckRenderingData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/IntervalSettings"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PermissionStatus":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus","type":"topic","abstract":[{"text":"Location permissions granted by user to the app.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PermissionStatus","kind":"identifier"}],"navigatorTitle":[{"text":"PermissionStatus","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/permissionstatus","title":"PermissionStatus"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Model":{"navigatorTitle":[{"kind":"identifier","text":"Model"}],"title":"Model","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Model"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Model","url":"\/documentation\/mapboxmaps\/model","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"A structure represeting a Model"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationProvider":{"type":"topic","abstract":[{"type":"text","text":"Location provider that provides locations"}],"role":"symbol","url":"\/documentation\/mapboxcommon\/locationprovider","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"LocationProvider","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"LocationProvider"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider","title":"LocationProvider"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LocationManager":{"abstract":[{"type":"text","text":"An object responsible for managing user location Puck."}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationManager","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LocationManager"}],"navigatorTitle":[{"text":"LocationManager","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/locationmanager","title":"LocationManager"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationProviderRequest":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProviderRequest","type":"topic","abstract":[{"text":"Data model that contains parameters for location requests.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationProviderRequest"}],"navigatorTitle":[{"text":"LocationProviderRequest","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/locationproviderrequest","title":"LocationProviderRequest"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/DeviceLocationProvider":{"abstract":[{"text":"Location provider specialisation that provides real-time locations generated from the device","type":"text"}],"title":"DeviceLocationProvider","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeviceLocationProvider"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/DeviceLocationProvider","navigatorTitle":[{"kind":"identifier","text":"DeviceLocationProvider"}],"url":"\/documentation\/mapboxcommon\/devicelocationprovider"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PuckRenderingData":{"abstract":[{"type":"text","text":"Represents the interpolated data ready to render the user location puck."}],"title":"PuckRenderingData","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"PuckRenderingData"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckRenderingData","navigatorTitle":[{"text":"PuckRenderingData","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/puckrenderingdata"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Settings-and-Constants":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Settings-and-Constants","url":"\/documentation\/mapboxmaps\/settings-and-constants","abstract":[],"title":"Settings and Constants","kind":"article","type":"topic","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Heading":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Heading","type":"topic","abstract":[{"text":"The azimuth (orientation) of the user’s device, relative to true or magnetic north.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"Heading","kind":"identifier"}],"navigatorTitle":[{"text":"Heading","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/heading","title":"Heading"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeadingObserver":{"title":"HeadingObserver","abstract":[{"text":"Listens to ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingProvider"},{"text":"’s updates.","type":"text"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/headingobserver","navigatorTitle":[{"kind":"identifier","text":"HeadingObserver"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingObserver","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeadingObserver"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationServiceObserver":{"title":"LocationServiceObserver","abstract":[{"text":"Observers for getting updates from LocationService.","type":"text"}],"role":"symbol","url":"\/documentation\/mapboxcommon\/locationserviceobserver","navigatorTitle":[{"text":"LocationServiceObserver","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationServiceObserver"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Puck3DConfiguration":{"url":"\/documentation\/mapboxmaps\/puck3dconfiguration","kind":"symbol","type":"topic","title":"Puck3DConfiguration","role":"symbol","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"Puck3DConfiguration","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Puck3DConfiguration"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationExtraKeys":{"abstract":[{"type":"text","text":"Keys for additional information (extra) in Location."}],"title":"LocationExtraKeys","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"LocationExtraKeys","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationExtraKeys","navigatorTitle":[{"kind":"identifier","text":"LocationExtraKeys"}],"url":"\/documentation\/mapboxcommon\/locationextrakeys"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/IntervalSettings":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/IntervalSettings","type":"topic","abstract":[{"text":"The interval for active location updates","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntervalSettings"}],"navigatorTitle":[{"kind":"identifier","text":"IntervalSettings"}],"url":"\/documentation\/mapboxcommon\/intervalsettings","title":"IntervalSettings"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Location":{"title":"Location","abstract":[{"text":"Location information.","type":"text"}],"role":"symbol","url":"\/documentation\/mapboxcommon\/location","navigatorTitle":[{"text":"Location","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Location","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","kind":"symbol","title":"MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationObserver":{"abstract":[{"type":"text","text":"Observer for getting updates from a LocationProvider."}],"title":"LocationObserver","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationObserver"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationObserver","navigatorTitle":[{"text":"LocationObserver","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/locationobserver"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Ornaments":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Ornaments","role":"collectionGroup","kind":"article","url":"\/documentation\/mapboxmaps\/ornaments","type":"topic","title":"Ornaments","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Gestures":{"url":"\/documentation\/mapboxmaps\/gestures","kind":"article","title":"Gestures","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Gestures","type":"topic","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationError":{"abstract":[{"type":"text","text":"Error code with brief explanation."}],"title":"LocationError","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationError"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationError","navigatorTitle":[{"kind":"identifier","text":"LocationError"}],"url":"\/documentation\/mapboxcommon\/locationerror"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationErrorCode":{"abstract":[{"text":"Codes of location errors.","type":"text"}],"title":"LocationErrorCode","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationErrorCode"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode","navigatorTitle":[{"kind":"identifier","text":"LocationErrorCode"}],"url":"\/documentation\/mapboxcommon\/locationerrorcode"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AppleLocationProviderDelegate":{"abstract":[{"type":"text","text":"The "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProviderDelegate","isActive":true,"type":"reference"},{"type":"text","text":" protocol defines a set of optional methods that you"},{"text":" ","type":"text"},{"text":"can use to receive events from an associated location provider object.","type":"text"}],"title":"AppleLocationProviderDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppleLocationProviderDelegate"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProviderDelegate","navigatorTitle":[{"kind":"identifier","text":"AppleLocationProviderDelegate"}],"url":"\/documentation\/mapboxmaps\/applelocationproviderdelegate"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AppleLocationProvider":{"abstract":[{"type":"text","text":"A location provider based on CoreLocation’s "},{"type":"codeVoice","code":"CLLocationManager"},{"type":"text","text":"."}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProvider","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AppleLocationProvider","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AppleLocationProvider"}],"url":"\/documentation\/mapboxmaps\/applelocationprovider","title":"AppleLocationProvider"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","url":"\/documentation\/overview","abstract":[],"kind":"article","title":"MapboxMaps Documentation","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LocationOptions":{"abstract":[{"type":"text","text":"A struct to configure a "},{"code":"LocationManager","type":"codeVoice"}],"title":"LocationOptions","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationOptions"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationOptions","navigatorTitle":[{"text":"LocationOptions","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/locationoptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/AccuracyAuthorization":{"type":"topic","title":"AccuracyAuthorization","navigatorTitle":[{"text":"AccuracyAuthorization","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization","kind":"symbol","abstract":[{"text":"Accuracy authorization granted by user to the app.","type":"text"}],"role":"symbol","url":"\/documentation\/mapboxcommon\/accuracyauthorization","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AccuracyAuthorization"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/AccuracyLevel":{"abstract":[{"text":"The accuracy of the observed location","type":"text"}],"title":"AccuracyLevel","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"AccuracyLevel","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel","navigatorTitle":[{"kind":"identifier","text":"AccuracyLevel"}],"url":"\/documentation\/mapboxcommon\/accuracylevel"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeadingProvider":{"abstract":[{"type":"text","text":"Provides heading data to drive the location puck."}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingProvider","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"HeadingProvider","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"HeadingProvider"}],"url":"\/documentation\/mapboxmaps\/headingprovider","title":"HeadingProvider"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationServiceFactory":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceFactory","type":"topic","abstract":[{"text":"Location service factory.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"LocationServiceFactory","kind":"identifier"}],"navigatorTitle":[{"text":"LocationServiceFactory","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/locationservicefactory","title":"LocationServiceFactory"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Coordinate2D":{"abstract":[{"text":"Boxed version of CLLocationCoordinate2D","type":"text"}],"title":"Coordinate2D","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Coordinate2D"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Coordinate2D","navigatorTitle":[{"kind":"identifier","text":"Coordinate2D"}],"url":"\/documentation\/mapboxcommon\/coordinate2d"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Puck2DConfiguration":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck2DConfiguration","abstract":[],"url":"\/documentation\/mapboxmaps\/puck2dconfiguration","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Puck2DConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"Puck2DConfiguration","kind":"identifier"}],"title":"Puck2DConfiguration","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PuckBearing":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PuckBearing"}],"abstract":[{"type":"text","text":"Controls how the puck is oriented"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckBearing","url":"\/documentation\/mapboxmaps\/puckbearing","kind":"symbol","title":"PuckBearing","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PuckBearing","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PuckType":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckType","type":"topic","abstract":[{"text":"Represents the different types of pucks","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PuckType"}],"navigatorTitle":[{"kind":"identifier","text":"PuckType"}],"url":"\/documentation\/mapboxmaps\/pucktype","title":"PuckType"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Camera-and-coordinates":{"title":"Camera and coordinates","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Camera-and-coordinates","role":"collectionGroup","kind":"article","type":"topic","abstract":[],"url":"\/documentation\/mapboxmaps\/camera-and-coordinates"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/title","op":"replace","value":"MBXPermissionStatus"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/fragments","op":"replace","value":[{"text":"MBXPermissionStatus","kind":"identifier"}]},{"op":"replace","value":[{"text":"MBXPermissionStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/title","op":"replace","value":"MBXLocationProvider"},{"value":[{"kind":"identifier","text":"MBXLocationProvider"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/fragments"},{"value":[{"kind":"identifier","text":"MBXLocationProvider"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/navigatorTitle"},{"op":"replace","value":"MBXLocationProviderRequest","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProviderRequest\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProviderRequest\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXLocationProviderRequest"}]},{"op":"replace","value":[{"text":"MBXLocationProviderRequest","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProviderRequest\/navigatorTitle"},{"value":"MBXDeviceLocationProvider","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1DeviceLocationProvider\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1DeviceLocationProvider\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXDeviceLocationProvider"}]},{"value":[{"text":"MBXDeviceLocationProvider","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1DeviceLocationProvider\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver\/title","value":"MBXLocationServiceObserver","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver\/fragments","value":[{"kind":"identifier","text":"MBXLocationServiceObserver"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver\/navigatorTitle","value":[{"kind":"identifier","text":"MBXLocationServiceObserver"}]},{"value":"MBXLocationExtraKeys","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationExtraKeys\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationExtraKeys\/fragments","value":[{"text":"MBXLocationExtraKeys","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationExtraKeys\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBXLocationExtraKeys"}]},{"value":"MBXIntervalSettings","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1IntervalSettings\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MBXIntervalSettings"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1IntervalSettings\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1IntervalSettings\/navigatorTitle","value":[{"kind":"identifier","text":"MBXIntervalSettings"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/title","value":"MBXLocation","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBXLocation"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MBXLocation"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/navigatorTitle"},{"value":"MBXLocationObserver","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/fragments","value":[{"kind":"identifier","text":"MBXLocationObserver"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/navigatorTitle","value":[{"text":"MBXLocationObserver","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationError\/title","value":"MBXLocationError"},{"op":"replace","value":[{"kind":"identifier","text":"MBXLocationError"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationError\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationError\/navigatorTitle","value":[{"kind":"identifier","text":"MBXLocationError"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/title","value":"MBXLocationErrorCode"},{"op":"replace","value":[{"text":"MBXLocationErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/navigatorTitle","value":[{"text":"MBXLocationErrorCode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization\/title","value":"MBXAccuracyAuthorization","op":"replace"},{"value":[{"kind":"identifier","text":"MBXAccuracyAuthorization"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization\/navigatorTitle","value":[{"text":"MBXAccuracyAuthorization","kind":"identifier"}]},{"op":"replace","value":"MBXAccuracyLevel","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel\/fragments","value":[{"kind":"identifier","text":"MBXAccuracyLevel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel\/navigatorTitle","value":[{"text":"MBXAccuracyLevel","kind":"identifier"}]},{"op":"replace","value":"MBXLocationServiceFactory","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceFactory\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceFactory\/fragments","value":[{"text":"MBXLocationServiceFactory","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MBXLocationServiceFactory"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceFactory\/navigatorTitle"},{"value":"MBXCoordinate2D","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Coordinate2D\/title","op":"replace"},{"op":"replace","value":[{"text":"MBXCoordinate2D","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Coordinate2D\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Coordinate2D\/navigatorTitle","op":"replace","value":[{"text":"MBXCoordinate2D","kind":"identifier"}]}]}]}