{"sections":[],"metadata":{"modules":[{"name":"MapboxMaps"}],"symbolKind":"struct","title":"LocationOptions","navigatorTitle":[{"kind":"identifier","text":"LocationOptions"}],"role":"symbol","externalID":"s:10MapboxMaps15LocationOptionsV","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"LocationOptions","kind":"identifier"}],"roleHeading":"Structure"},"seeAlsoSections":[{"title":"Location","anchor":"Location","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationManager","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck2DConfiguration","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Model","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckBearing","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProviderDelegate","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Coordinate2D","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationExtraKeys","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProviderRequest","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceFactory"],"generated":true}],"relationshipsSections":[{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/SQ"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"LocationOptions","kind":"identifier"}],"platforms":["iOS"]}]}],"kind":"symbol","abstract":[{"type":"text","text":"A struct to configure a "},{"type":"codeVoice","code":"LocationManager"}],"variants":[{"paths":["\/documentation\/mapboxmaps\/locationoptions"],"traits":[{"interfaceLanguage":"swift"}]}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationOptions\/init(puckType:puckBearing:puckBearingEnabled:)"],"generated":true,"anchor":"Initializers"},{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationOptions\/puckBearing","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationOptions\/puckBearingEnabled","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationOptions\/puckType"],"title":"Instance Properties"},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationOptions\/Equatable-Implementations"],"anchor":"Default-Implementations"}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationOptions","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LocationOptions/Equatable-Implementations":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationOptions\/Equatable-Implementations","title":"Equatable Implementations","abstract":[],"role":"collectionGroup","kind":"article","url":"\/documentation\/mapboxmaps\/locationoptions\/equatable-implementations","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationServiceFactory":{"navigatorTitle":[{"kind":"identifier","text":"LocationServiceFactory"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"LocationServiceFactory","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/mapboxcommon\/locationservicefactory","abstract":[{"type":"text","text":"Location service factory."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceFactory","title":"LocationServiceFactory","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationExtraKeys":{"abstract":[{"type":"text","text":"Keys for additional information (extra) in Location."}],"role":"symbol","navigatorTitle":[{"text":"LocationExtraKeys","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/mapboxcommon\/locationextrakeys","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationExtraKeys","kind":"identifier"}],"title":"LocationExtraKeys","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationExtraKeys"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Puck3DConfiguration":{"navigatorTitle":[{"text":"Puck3DConfiguration","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Puck3DConfiguration"}],"role":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/puck3dconfiguration","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration","title":"Puck3DConfiguration","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LocationOptions/puckType":{"type":"topic","abstract":[{"type":"text","text":"Sets the type of puck that should be used"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationOptions\/puckType","kind":"symbol","title":"puckType","url":"\/documentation\/mapboxmaps\/locationoptions\/pucktype","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"puckType","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10MapboxMaps8PuckTypeO","text":"PuckType","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AppleLocationProvider":{"type":"topic","abstract":[{"type":"text","text":"A location provider based on CoreLocation’s "},{"type":"codeVoice","code":"CLLocationManager"},{"type":"text","text":"."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AppleLocationProvider"}],"url":"\/documentation\/mapboxmaps\/applelocationprovider","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProvider","navigatorTitle":[{"text":"AppleLocationProvider","kind":"identifier"}],"title":"AppleLocationProvider","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Coordinate2D":{"navigatorTitle":[{"kind":"identifier","text":"Coordinate2D"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Coordinate2D","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/mapboxcommon\/coordinate2d","abstract":[{"type":"text","text":"Boxed version of CLLocationCoordinate2D"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Coordinate2D","title":"Coordinate2D","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LocationOptions/puckBearing":{"url":"\/documentation\/mapboxmaps\/locationoptions\/puckbearing","abstract":[{"text":"Specifies if a ","type":"text"},{"code":"Puck","type":"codeVoice"},{"type":"text","text":" should use "},{"code":"Heading","type":"codeVoice"},{"type":"text","text":" or "},{"type":"codeVoice","code":"Course"},{"type":"text","text":" for the bearing."}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationOptions\/puckBearing","title":"puckBearing","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"puckBearing"},{"kind":"text","text":": "},{"text":"PuckBearing","preciseIdentifier":"s:10MapboxMaps11PuckBearingO","kind":"typeIdentifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PuckType":{"navigatorTitle":[{"kind":"identifier","text":"PuckType"}],"title":"PuckType","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckType","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PuckType","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/pucktype","abstract":[{"type":"text","text":"Represents the different types of pucks"}],"kind":"symbol","type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Model":{"navigatorTitle":[{"kind":"identifier","text":"Model"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Model","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/model","abstract":[{"type":"text","text":"A structure represeting a Model"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Model","title":"Model","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Location":{"abstract":[{"type":"text","text":"Location information."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Location"}],"kind":"symbol","type":"topic","url":"\/documentation\/mapboxcommon\/location","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Location","kind":"identifier"}],"title":"Location","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LocationOptions/puckBearingEnabled":{"type":"topic","title":"puckBearingEnabled","kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/locationoptions\/puckbearingenabled","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationOptions\/puckBearingEnabled","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"puckBearingEnabled","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Whether the puck rotates to track the bearing source."}]},"doc://com.mapbox.MapboxMaps/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationError":{"navigatorTitle":[{"kind":"identifier","text":"LocationError"}],"title":"LocationError","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationError","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"LocationError","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/locationerror","abstract":[{"type":"text","text":"Error code with brief explanation."}],"kind":"symbol","type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Puck2DConfiguration":{"abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Puck2DConfiguration"}],"kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/puck2dconfiguration","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Puck2DConfiguration","kind":"identifier"}],"title":"Puck2DConfiguration","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck2DConfiguration"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationProviderRequest":{"type":"topic","abstract":[{"type":"text","text":"Data model that contains parameters for location requests."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LocationProviderRequest"}],"url":"\/documentation\/mapboxcommon\/locationproviderrequest","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProviderRequest","navigatorTitle":[{"text":"LocationProviderRequest","kind":"identifier"}],"title":"LocationProviderRequest","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","role":"collection","url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"title":"MapboxMaps","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LocationOptions/init(puckType:puckBearing:puckBearingEnabled:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationOptions\/init(puckType:puckBearing:puckBearingEnabled:)","title":"init(puckType:puckBearing:puckBearingEnabled:)","abstract":[{"text":"Initializes a ","type":"text"},{"type":"codeVoice","code":"LocationOptions"},{"text":".","type":"text"}],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"puckType"},{"text":": ","kind":"text"},{"text":"PuckType","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps8PuckTypeO"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"puckBearing"},{"kind":"text","text":": "},{"text":"PuckBearing","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps11PuckBearingO"},{"kind":"text","text":", "},{"text":"puckBearingEnabled","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/locationoptions\/init(pucktype:puckbearing:puckbearingenabled:)","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LocationManager":{"abstract":[{"text":"An object responsible for managing user location Puck.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"LocationManager","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/locationmanager","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"LocationManager","kind":"identifier"}],"title":"LocationManager","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationManager"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PuckBearing":{"type":"topic","abstract":[{"type":"text","text":"Controls how the puck is oriented"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PuckBearing","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/puckbearing","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckBearing","navigatorTitle":[{"text":"PuckBearing","kind":"identifier"}],"title":"PuckBearing","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LocationOptions":{"type":"topic","abstract":[{"type":"text","text":"A struct to configure a "},{"code":"LocationManager","type":"codeVoice"}],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationOptions","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/locationoptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationOptions","navigatorTitle":[{"text":"LocationOptions","kind":"identifier"}],"title":"LocationOptions","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AppleLocationProviderDelegate":{"type":"topic","abstract":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProviderDelegate"},{"type":"text","text":" protocol defines a set of optional methods that you"},{"type":"text","text":" "},{"type":"text","text":"can use to receive events from an associated location provider object."}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AppleLocationProviderDelegate"}],"url":"\/documentation\/mapboxmaps\/applelocationproviderdelegate","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProviderDelegate","navigatorTitle":[{"text":"AppleLocationProviderDelegate","kind":"identifier"}],"title":"AppleLocationProviderDelegate","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationProvider":{"type":"topic","abstract":[{"text":"Location provider that provides locations","type":"text"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"LocationProvider","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/locationprovider","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider","navigatorTitle":[{"text":"LocationProvider","kind":"identifier"}],"title":"LocationProvider","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MBXLocationServiceFactory","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceFactory\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBXLocationServiceFactory"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceFactory\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceFactory\/navigatorTitle","value":[{"kind":"identifier","text":"MBXLocationServiceFactory"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationExtraKeys\/title","value":"MBXLocationExtraKeys"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationExtraKeys\/fragments","value":[{"kind":"identifier","text":"MBXLocationExtraKeys"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationExtraKeys\/navigatorTitle","value":[{"text":"MBXLocationExtraKeys","kind":"identifier"}],"op":"replace"},{"value":"MBXCoordinate2D","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Coordinate2D\/title"},{"value":[{"kind":"identifier","text":"MBXCoordinate2D"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Coordinate2D\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Coordinate2D\/navigatorTitle","value":[{"text":"MBXCoordinate2D","kind":"identifier"}],"op":"replace"},{"value":"MBXLocation","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/title","op":"replace"},{"op":"replace","value":[{"text":"MBXLocation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/navigatorTitle","value":[{"kind":"identifier","text":"MBXLocation"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationError\/title","value":"MBXLocationError","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationError\/fragments","value":[{"text":"MBXLocationError","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationError\/navigatorTitle","value":[{"text":"MBXLocationError","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProviderRequest\/title","value":"MBXLocationProviderRequest"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProviderRequest\/fragments","value":[{"text":"MBXLocationProviderRequest","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProviderRequest\/navigatorTitle","op":"replace","value":[{"text":"MBXLocationProviderRequest","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/title","value":"MBXLocationProvider","op":"replace"},{"value":[{"text":"MBXLocationProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/navigatorTitle","value":[{"text":"MBXLocationProvider","kind":"identifier"}]}]}]}