{"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"article","seeAlsoSections":[{"anchor":"Advanced","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs"],"title":"Advanced"}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"]]},"metadata":{"modules":[{"name":"MapboxMaps"}],"roleHeading":"API Collection","role":"collectionGroup","title":"MapboxMap"},"topicSections":[{"anchor":"MapboxMap","title":"MapboxMap","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraState","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBounds","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBoundsOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Projection","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBoundsZoom","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateInfo","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ContextMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapCenterAltitudeMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometry","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometryConvertible"]},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/freeCameraOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Camera-and-coordinates"],"anchor":"Camera","title":"Camera"},{"anchor":"Query-features-on-the-map","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceQueryOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedFeature","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedRenderedFeature","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedSourceFeature","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AnnotatedFeature"],"title":"Query features on the map"}],"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceQueryOptions":{"title":"SourceQueryOptions","url":"\/documentation\/mapboxmaps\/sourcequeryoptions","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SourceQueryOptions","kind":"identifier"}],"abstract":[{"text":"Options for querying source features.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceQueryOptions","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SourceQueryOptions"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Performance":{"type":"topic","url":"\/documentation\/mapboxmaps\/performance","role":"collectionGroup","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","abstract":[],"title":"Performance and investigations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateBounds":{"url":"\/documentation\/mapboxmaps\/coordinatebounds","abstract":[{"type":"text","text":"A rectangular area as measured on a two-dimensional map projection."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds","title":"CoordinateBounds","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CoordinateBounds"}],"type":"topic","navigatorTitle":[{"text":"CoordinateBounds","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraOptions":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraOptions","abstract":[],"kind":"symbol","title":"CameraOptions","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraOptions","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxmaps\/cameraoptions","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CameraOptions"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"type":"topic","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","url":"\/documentation\/mapboxmaps\/tilestore-apis","kind":"article","title":"TileStore APIs"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapError":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapError"}],"type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/maperror","navigatorTitle":[{"kind":"identifier","text":"MapError"}],"abstract":[{"type":"text","text":"Type of errors thrown by the "},{"code":"MapboxMap","type":"codeVoice"},{"type":"text","text":" APIs."}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapError","title":"MapError"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapboxMap","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap","title":"MapboxMap","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","type":"topic","abstract":[{"type":"text","text":"Provides access to the map model, including the camera, style, observable map events,"},{"text":" ","type":"text"},{"text":"and querying rendered features.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"MapboxMap","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/QueriedRenderedFeature":{"title":"QueriedRenderedFeature","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedRenderedFeature","url":"\/documentation\/mapboxmaps\/queriedrenderedfeature","role":"symbol","type":"topic","abstract":[{"text":"Represents query result that is returned in QueryRenderedFeaturesCallback.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"QueriedRenderedFeature"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"QueriedRenderedFeature","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GlyphsRasterizationMode":{"type":"topic","url":"\/documentation\/mapboxmaps\/glyphsrasterizationmode","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GlyphsRasterizationMode"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode","navigatorTitle":[{"kind":"identifier","text":"GlyphsRasterizationMode"}],"title":"GlyphsRasterizationMode","abstract":[{"text":"Describes glyphs rasterization modes.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Camera-and-coordinates":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Camera-and-coordinates","title":"Camera and coordinates","kind":"article","url":"\/documentation\/mapboxmaps\/camera-and-coordinates","abstract":[],"role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraBoundsOptions":{"type":"topic","abstract":[{"type":"text","text":"Holds options to be used for setting camera bounds."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CameraBoundsOptions"}],"url":"\/documentation\/mapboxmaps\/cameraboundsoptions","title":"CameraBoundsOptions","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraBoundsOptions"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBoundsOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderedQueryGeometryConvertible":{"type":"topic","abstract":[{"type":"text","text":"A convenience protocol for automatic conversion to "},{"isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometry","type":"reference"},{"type":"text","text":"."}],"role":"symbol","navigatorTitle":[{"text":"RenderedQueryGeometryConvertible","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/renderedquerygeometryconvertible","title":"RenderedQueryGeometryConvertible","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RenderedQueryGeometryConvertible"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometryConvertible"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateBoundsZoom":{"type":"topic","abstract":[{"type":"text","text":"A coordinate bounds and zoom."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CoordinateBoundsZoom"}],"url":"\/documentation\/mapboxmaps\/coordinateboundszoom","title":"CoordinateBoundsZoom","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoordinateBoundsZoom"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBoundsZoom"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraBounds":{"type":"topic","abstract":[{"type":"text","text":"Holds information about camera bounds."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CameraBounds"}],"url":"\/documentation\/mapboxmaps\/camerabounds","title":"CameraBounds","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CameraBounds"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBounds"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ContextMode":{"type":"topic","abstract":[{"text":"Describes the map context mode.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"We can make some optimizations if we know that the drawing context is not shared with other code."}],"role":"symbol","navigatorTitle":[{"text":"ContextMode","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/contextmode","title":"ContextMode","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ContextMode"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ContextMode"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","kind":"article","abstract":[],"title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/QueriedFeature":{"abstract":[{"text":"Represents queried feature that is returned through ","type":"text"},{"type":"codeVoice","code":"QueriedRenderedFeature"},{"type":"text","text":" or "},{"type":"codeVoice","code":"QueriedSourceFeature"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedFeature","type":"topic","role":"symbol","title":"QueriedFeature","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"QueriedFeature"}],"navigatorTitle":[{"text":"QueriedFeature","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/queriedfeature"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/freeCameraOptions":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/freeCameraOptions","url":"\/documentation\/mapboxmaps\/mapboxmap\/freecameraoptions","type":"topic","kind":"symbol","title":"freeCameraOptions","abstract":[{"text":"Sets\/get the map view with the free camera options.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"freeCameraOptions","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"FreeCameraOptions","preciseIdentifier":"c:objc(cs)MBMFreeCameraOptions"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapCenterAltitudeMode":{"type":"topic","abstract":[{"type":"text","text":"Defines how the map center point should react to terrain elevation changes."}],"role":"symbol","navigatorTitle":[{"text":"MapCenterAltitudeMode","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/mapcenteraltitudemode","title":"MapCenterAltitudeMode","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapCenterAltitudeMode"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapCenterAltitudeMode"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/QueriedSourceFeature":{"title":"QueriedSourceFeature","abstract":[{"text":"Represents query result that is returned in QuerySourceFeaturesCallback.","type":"text"}],"url":"\/documentation\/mapboxmaps\/queriedsourcefeature","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"QueriedSourceFeature","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedSourceFeature","navigatorTitle":[{"text":"QueriedSourceFeature","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraState":{"abstract":[],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraState","navigatorTitle":[{"kind":"identifier","text":"CameraState"}],"title":"CameraState","type":"topic","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraState","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/camerastate"},"https://en.wikipedia.org/wiki/Web_Mercator_projection":{"titleInlineContent":[{"type":"text","text":"Spherical Mercator"}],"type":"link","title":"Spherical Mercator","identifier":"https:\/\/en.wikipedia.org\/wiki\/Web_Mercator_projection","url":"https:\/\/en.wikipedia.org\/wiki\/Web_Mercator_projection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateInfo":{"role":"symbol","url":"\/documentation\/mapboxmaps\/coordinateinfo","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateInfo","title":"CoordinateInfo","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CoordinateInfo","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"CoordinateInfo"}],"kind":"symbol","abstract":[{"type":"text","text":"Represents the coordinate information returned by the "},{"code":"coordinateInfoForPixel","type":"codeVoice"},{"type":"text","text":" or "},{"type":"codeVoice","code":"coordinatesInfoForPixels"},{"type":"text","text":" methods."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Projection":{"url":"\/documentation\/mapboxmaps\/projection","title":"Projection","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Projection"}],"abstract":[{"type":"text","text":"A collection of "},{"identifier":"https:\/\/en.wikipedia.org\/wiki\/Web_Mercator_projection","isActive":true,"type":"reference"},{"text":" projection methods.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Projection","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Projection"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AnnotatedFeature":{"navigatorTitle":[{"kind":"identifier","text":"AnnotatedFeature"}],"kind":"symbol","role":"symbol","title":"AnnotatedFeature","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AnnotatedFeature","type":"topic","abstract":[{"type":"text","text":"Represents either a GeoJSON geometry or an annotated layer feature."}],"url":"\/documentation\/mapboxmaps\/annotatedfeature","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnnotatedFeature"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderedQueryGeometry":{"title":"RenderedQueryGeometry","url":"\/documentation\/mapboxmaps\/renderedquerygeometry","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RenderedQueryGeometry"}],"abstract":[{"text":"A geometry to define a portion of screen that should be queried for rendered features.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometry","type":"topic","navigatorTitle":[{"text":"RenderedQueryGeometry","kind":"identifier"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","role":"collection","title":"MapboxMaps","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderedQueryOptions":{"navigatorTitle":[{"kind":"identifier","text":"RenderedQueryOptions"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryOptions","abstract":[{"type":"text","text":"Options for querying rendered features."}],"type":"topic","url":"\/documentation\/mapboxmaps\/renderedqueryoptions","title":"RenderedQueryOptions","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"RenderedQueryOptions","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FreeCameraOptions":{"navigatorTitle":[{"text":"FreeCameraOptions","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions","kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/freecameraoptions","abstract":[{"text":"Various options for accessing physical properties of the underlying camera entity.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"A direct access to these properties allows more flexible and precise controlling"},{"type":"text","text":" "},{"text":"of the camera while also being fully compatible and interchangeable with CameraOptions.","type":"text"},{"type":"text","text":" "},{"text":"All fields are optional.","type":"text"}],"title":"FreeCameraOptions","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FreeCameraOptions","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceQueryOptions\/title","value":"MBMSourceQueryOptions"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceQueryOptions\/fragments","value":[{"kind":"identifier","text":"MBMSourceQueryOptions"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceQueryOptions\/navigatorTitle","value":[{"text":"MBMSourceQueryOptions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds\/title","value":"MBMCoordinateBounds"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds\/fragments","value":[{"kind":"identifier","text":"MBMCoordinateBounds"}]},{"op":"replace","value":[{"text":"MBMCoordinateBounds","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedRenderedFeature\/title","value":"MBMQueriedRenderedFeature"},{"value":[{"kind":"identifier","text":"MBMQueriedRenderedFeature"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedRenderedFeature\/fragments"},{"value":[{"kind":"identifier","text":"MBMQueriedRenderedFeature"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedRenderedFeature\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/title","value":"MBMGlyphsRasterizationMode"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/fragments","value":[{"kind":"identifier","text":"MBMGlyphsRasterizationMode"}],"op":"replace"},{"value":[{"text":"MBMGlyphsRasterizationMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/navigatorTitle"},{"op":"replace","value":"MBMCoordinateBoundsZoom","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBoundsZoom\/title"},{"value":[{"text":"MBMCoordinateBoundsZoom","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBoundsZoom\/fragments","op":"replace"},{"value":[{"text":"MBMCoordinateBoundsZoom","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBoundsZoom\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ContextMode\/title","value":"MBMContextMode"},{"op":"replace","value":[{"text":"MBMContextMode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ContextMode\/fragments"},{"op":"replace","value":[{"text":"MBMContextMode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ContextMode\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedFeature\/title","value":"MBMQueriedFeature","op":"replace"},{"value":[{"kind":"identifier","text":"MBMQueriedFeature"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedFeature\/fragments"},{"value":[{"kind":"identifier","text":"MBMQueriedFeature"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedFeature\/navigatorTitle"},{"value":"MBMMapCenterAltitudeMode","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapCenterAltitudeMode\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapCenterAltitudeMode\/fragments","value":[{"text":"MBMMapCenterAltitudeMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapCenterAltitudeMode\/navigatorTitle","op":"replace","value":[{"text":"MBMMapCenterAltitudeMode","kind":"identifier"}]},{"value":"MBMQueriedSourceFeature","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedSourceFeature\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBMQueriedSourceFeature"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedSourceFeature\/fragments"},{"value":[{"kind":"identifier","text":"MBMQueriedSourceFeature"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedSourceFeature\/navigatorTitle","op":"replace"},{"op":"replace","value":"MBMCoordinateInfo","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateInfo\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBMCoordinateInfo"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateInfo\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateInfo\/navigatorTitle","value":[{"text":"MBMCoordinateInfo","kind":"identifier"}]},{"value":"MBMRenderedQueryOptions","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderedQueryOptions\/title","op":"replace"},{"op":"replace","value":[{"text":"MBMRenderedQueryOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderedQueryOptions\/fragments"},{"value":[{"kind":"identifier","text":"MBMRenderedQueryOptions"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderedQueryOptions\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions\/title","value":"MBMFreeCameraOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions\/fragments","value":[{"text":"MBMFreeCameraOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions\/navigatorTitle","op":"replace","value":[{"text":"MBMFreeCameraOptions","kind":"identifier"}]}]}]}