{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MapInitOptionsProvider","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","sections":[],"metadata":{"title":"MapInitOptionsProvider","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MapInitOptionsProvider","kind":"identifier"}],"role":"symbol","externalID":"c:@M@MapboxMaps@objc(pl)MapInitOptionsProvider","roleHeading":"Protocol","symbolKind":"protocol","modules":[{"name":"MapboxMaps"}],"navigatorTitle":[{"kind":"identifier","text":"MapInitOptionsProvider"}]},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-View"]]},"abstract":[{"text":"A protocol used to provide ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapInitOptions","type":"reference","isActive":true},{"type":"text","text":" when initializing a "},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapView","isActive":true},{"text":" with a Storyboard or","type":"text"},{"type":"text","text":" "},{"type":"text","text":"a nib."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapInitOptionsProvider\/mapInitOptions()"],"title":"Instance Methods","generated":true}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapView","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapInitOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AttributionURLOpener","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ConstrainMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/NorthOrientation","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PresentationTransactionMode"],"title":"MapView","generated":true,"anchor":"MapView"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/mapinitoptionsprovider"]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapInitOptionsProvider","interfaceLanguage":"swift"},"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","kind":"article","abstract":[],"title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapInitOptions":{"navigatorTitle":[{"text":"MapInitOptions","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapInitOptions","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapInitOptions"}],"abstract":[{"text":"Options used when initializing ","type":"text"},{"type":"codeVoice","code":"MapView"},{"type":"text","text":"."}],"title":"MapInitOptions","type":"topic","url":"\/documentation\/mapboxmaps\/mapinitoptions","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GlyphsRasterizationOptions":{"title":"GlyphsRasterizationOptions","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GlyphsRasterizationOptions","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationOptions","type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/glyphsrasterizationoptions","navigatorTitle":[{"text":"GlyphsRasterizationOptions","kind":"identifier"}],"abstract":[{"type":"text","text":"Describes the glyphs rasterization option values."}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","role":"collection","title":"MapboxMaps","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapInitOptionsProvider/mapInitOptions()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mapInitOptions","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@MapboxMaps@objc(cs)MapInitOptions","text":"MapInitOptions","kind":"typeIdentifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapInitOptionsProvider\/mapInitOptions()","role":"symbol","title":"mapInitOptions()","url":"\/documentation\/mapboxmaps\/mapinitoptionsprovider\/mapinitoptions()","required":true,"abstract":[{"type":"text","text":"A method to be called when "},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapView","isActive":true},{"text":" needs initialization options","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapOptions":{"role":"symbol","kind":"symbol","title":"MapOptions","url":"\/documentation\/mapboxmaps\/mapoptions","type":"topic","abstract":[{"text":"Describes the map option values.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapOptions","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MapOptions","kind":"identifier"}],"navigatorTitle":[{"text":"MapOptions","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/NorthOrientation":{"title":"NorthOrientation","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NorthOrientation"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/NorthOrientation","type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/northorientation","navigatorTitle":[{"text":"NorthOrientation","kind":"identifier"}],"abstract":[{"type":"text","text":"Describes the map orientation."}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PresentationTransactionMode":{"url":"\/documentation\/mapboxmaps\/presentationtransactionmode","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PresentationTransactionMode"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PresentationTransactionMode","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PresentationTransactionMode"}],"title":"PresentationTransactionMode","abstract":[{"type":"text","text":"Determines if the underlying "},{"code":"CAMetalLayer","type":"codeVoice"},{"type":"text","text":" rendering output should synchronize with the Core Animation transactions."}],"type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewportMode":{"title":"ViewportMode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ViewportMode","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportMode","type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/viewportmode","navigatorTitle":[{"kind":"identifier","text":"ViewportMode"}],"abstract":[{"type":"text","text":"Satisfies embedding platforms that requires the viewport coordinate systems to be set according to its standards."}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GlyphsRasterizationMode":{"type":"topic","url":"\/documentation\/mapboxmaps\/glyphsrasterizationmode","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GlyphsRasterizationMode"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode","navigatorTitle":[{"kind":"identifier","text":"GlyphsRasterizationMode"}],"title":"GlyphsRasterizationMode","abstract":[{"text":"Describes glyphs rasterization modes.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map-View":{"kind":"article","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/map-view","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-View","abstract":[],"type":"topic","title":"MapView"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapView":{"navigatorTitle":[{"text":"MapView","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapView","type":"topic","abstract":[],"title":"MapView","url":"\/documentation\/mapboxmaps\/mapview","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapView"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AttributionURLOpener":{"url":"\/documentation\/mapboxmaps\/attributionurlopener","navigatorTitle":[{"text":"AttributionURLOpener","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol to open attribution URLs."}],"title":"AttributionURLOpener","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"AttributionURLOpener","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AttributionURLOpener"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ConstrainMode":{"title":"ConstrainMode","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConstrainMode"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ConstrainMode","type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/constrainmode","navigatorTitle":[{"text":"ConstrainMode","kind":"identifier"}],"abstract":[{"type":"text","text":"Describes whether to constrain the map in both axes or only vertically e.g. while panning."}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapInitOptionsProvider":{"title":"MapInitOptionsProvider","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MapInitOptionsProvider","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapInitOptionsProvider","type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/mapinitoptionsprovider","navigatorTitle":[{"kind":"identifier","text":"MapInitOptionsProvider"}],"abstract":[{"type":"text","text":"A protocol used to provide "},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapInitOptions","isActive":true},{"type":"text","text":" when initializing a "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapView","isActive":true,"type":"reference"},{"type":"text","text":" with a Storyboard or"},{"type":"text","text":" "},{"type":"text","text":"a nib."}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationOptions\/title","value":"MBMGlyphsRasterizationOptions","op":"replace"},{"value":[{"kind":"identifier","text":"MBMGlyphsRasterizationOptions"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationOptions\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationOptions\/navigatorTitle","value":[{"text":"MBMGlyphsRasterizationOptions","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapOptions\/title","value":"MBMMapOptions"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapOptions\/fragments","value":[{"kind":"identifier","text":"MBMMapOptions"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBMMapOptions"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapOptions\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1NorthOrientation\/title","value":"MBMNorthOrientation"},{"value":[{"text":"MBMNorthOrientation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1NorthOrientation\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1NorthOrientation\/navigatorTitle","value":[{"text":"MBMNorthOrientation","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewportMode\/title","value":"MBMViewportMode","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBMViewportMode"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewportMode\/fragments"},{"value":[{"kind":"identifier","text":"MBMViewportMode"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewportMode\/navigatorTitle","op":"replace"},{"op":"replace","value":"MBMGlyphsRasterizationMode","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMGlyphsRasterizationMode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/navigatorTitle","value":[{"text":"MBMGlyphsRasterizationMode","kind":"identifier"}]},{"value":"MBMConstrainMode","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ConstrainMode\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ConstrainMode\/fragments","op":"replace","value":[{"text":"MBMConstrainMode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ConstrainMode\/navigatorTitle","value":[{"text":"MBMConstrainMode","kind":"identifier"}]}]}]}