{"metadata":{"modules":[{"name":"MapboxMaps"}],"externalID":"c:objc(cs)MBMMapOptions","role":"symbol","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapOptions"}],"symbolKind":"class","title":"MapOptions","navigatorTitle":[{"text":"MapOptions","kind":"identifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-View"]]},"sections":[],"abstract":[{"type":"text","text":"Describes the map option values."}],"topicSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapOptions\/glyphsRasterizationOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapOptions\/pixelRatio"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"}],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"]},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH"],"type":"conformsTo"}],"seeAlsoSections":[{"title":"MapView","generated":true,"anchor":"MapView","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapView","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapInitOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapInitOptionsProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AttributionURLOpener","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ConstrainMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/NorthOrientation","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PresentationTransactionMode"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapOptions","kind":"identifier"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/mapoptions"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/mapoptions"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapOptions"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMMapOptions/initWithContextMode:constrainMode:viewportMode:orientation:crossSourceCollisions:size:glyphsRasterizationOptions:":{"type":"topic","navigatorTitle":[{"text":"initWithContextMode:constrainMode:viewportMode:orientation:crossSourceCollisions:size:glyphsRasterizationOptions:","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"initWithContextMode:constrainMode:viewportMode:orientation:crossSourceCollisions:size:glyphsRasterizationOptions:","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapOptions\/initWithContextMode:constrainMode:viewportMode:orientation:crossSourceCollisions:size:glyphsRasterizationOptions:","abstract":[],"fragments":[{"kind":"text","text":"- "},{"text":"initWithContextMode:constrainMode:viewportMode:orientation:crossSourceCollisions:size:glyphsRasterizationOptions:","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/mbmmapoptions\/initwithcontextmode:constrainmode:viewportmode:orientation:crosssourcecollisions:size:glyphsrasterizationoptions:"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMMapOptions/contextMode":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapOptions\/contextMode","fragments":[{"kind":"identifier","text":"contextMode"}],"kind":"symbol","role":"symbol","abstract":[{"text":"The map context mode. This can be used to optimizations","type":"text"},{"type":"text","text":" "},{"type":"text","text":"if we know that the drawing context is not shared with other code."}],"title":"contextMode","url":"\/documentation\/mapboxmaps\/mbmmapoptions\/contextmode","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/NorthOrientation":{"title":"NorthOrientation","role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/NorthOrientation","abstract":[{"text":"Describes the map orientation.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"NorthOrientation","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/northorientation","navigatorTitle":[{"kind":"identifier","text":"NorthOrientation"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapOptions":{"abstract":[{"type":"text","text":"Describes the map option values."}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapOptions","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MapOptions","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/mapoptions","title":"MapOptions","navigatorTitle":[{"kind":"identifier","text":"MapOptions"}],"kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","title":"MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","role":"collection","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","type":"topic","title":"MapboxMaps Documentation","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMMapOptions/initWithContextMode:constrainMode:viewportMode:orientation:crossSourceCollisions:size:pixelRatio:glyphsRasterizationOptions:":{"type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithContextMode:constrainMode:viewportMode:orientation:crossSourceCollisions:size:pixelRatio:glyphsRasterizationOptions:"}],"navigatorTitle":[{"kind":"identifier","text":"initWithContextMode:constrainMode:viewportMode:orientation:crossSourceCollisions:size:pixelRatio:glyphsRasterizationOptions:"}],"url":"\/documentation\/mapboxmaps\/mbmmapoptions\/initwithcontextmode:constrainmode:viewportmode:orientation:crosssourcecollisions:size:pixelratio:glyphsrasterizationoptions:","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapOptions\/initWithContextMode:constrainMode:viewportMode:orientation:crossSourceCollisions:size:pixelRatio:glyphsRasterizationOptions:","title":"initWithContextMode:constrainMode:viewportMode:orientation:crossSourceCollisions:size:pixelRatio:glyphsRasterizationOptions:","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMMapOptions/constrainMode":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapOptions\/constrainMode","fragments":[{"text":"constrainMode","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The map constrain mode. This can be used to limit the map"},{"type":"text","text":" "},{"text":"to wrap around the globe horizontally. By default, it is set to","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"HeightOnly"},{"text":".","type":"text"}],"title":"constrainMode","url":"\/documentation\/mapboxmaps\/mbmmapoptions\/constrainmode","type":"topic"},"doc://com.mapbox.MapboxMaps/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMMapOptions/size":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapOptions\/size","fragments":[{"text":"size","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"text":"The size to resize the map object and renderer backend.","type":"text"},{"type":"text","text":" "},{"text":"The size is given in ","type":"text"},{"code":"platform pixel","type":"codeVoice"},{"type":"text","text":" units. macOS and iOS platforms use"},{"type":"text","text":" "},{"type":"text","text":"device-independent pixel units, while other platforms, such as Android,"},{"type":"text","text":" "},{"type":"text","text":"use screen pixel units."}],"url":"\/documentation\/mapboxmaps\/mbmmapoptions\/size","title":"size","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AttributionURLOpener":{"abstract":[{"type":"text","text":"A protocol to open attribution URLs."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AttributionURLOpener","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AttributionURLOpener"}],"navigatorTitle":[{"kind":"identifier","text":"AttributionURLOpener"}],"title":"AttributionURLOpener","url":"\/documentation\/mapboxmaps\/attributionurlopener","kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMMapOptions/viewportMode":{"type":"topic","kind":"symbol","role":"symbol","title":"viewportMode","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapOptions\/viewportMode","abstract":[{"type":"text","text":"The viewport mode. This can be used to flip the vertical"},{"type":"text","text":" "},{"type":"text","text":"orientation of the map as some devices may use inverted orientation."}],"fragments":[{"text":"viewportMode","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/mbmmapoptions\/viewportmode"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map-View":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-View","title":"MapView","role":"collectionGroup","abstract":[],"url":"\/documentation\/mapboxmaps\/map-view","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMMapOptions/crossSourceCollisions":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapOptions\/crossSourceCollisions","fragments":[{"text":"crossSourceCollisions","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Specify whether to enable cross-source symbol collision detection"},{"type":"text","text":" "},{"type":"text","text":"or not. By default, it is set to "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"url":"\/documentation\/mapboxmaps\/mbmmapoptions\/crosssourcecollisions","title":"crossSourceCollisions","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapOptions/glyphsRasterizationOptions":{"title":"glyphsRasterizationOptions","role":"symbol","abstract":[{"text":"Glyphs rasterization options to use for client-side text rendering.","type":"text"}],"url":"\/documentation\/mapboxmaps\/mapoptions\/glyphsrasterizationoptions","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapOptions\/glyphsRasterizationOptions","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"glyphsRasterizationOptions"},{"text":": ","kind":"text"},{"text":"GlyphsRasterizationOptions","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMGlyphsRasterizationOptions"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"glyphsRasterizationOptions","kind":"identifier"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject"},"doc://com.mapbox.MapboxMaps/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GlyphsRasterizationOptions":{"abstract":[{"type":"text","text":"Describes the glyphs rasterization option values."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationOptions","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GlyphsRasterizationOptions","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GlyphsRasterizationOptions"}],"title":"GlyphsRasterizationOptions","url":"\/documentation\/mapboxmaps\/glyphsrasterizationoptions","kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewportMode":{"abstract":[{"type":"text","text":"Satisfies embedding platforms that requires the viewport coordinate systems to be set according to its standards."}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportMode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ViewportMode"}],"url":"\/documentation\/mapboxmaps\/viewportmode","title":"ViewportMode","navigatorTitle":[{"kind":"identifier","text":"ViewportMode"}],"kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapInitOptions":{"abstract":[{"type":"text","text":"Options used when initializing "},{"code":"MapView","type":"codeVoice"},{"type":"text","text":"."}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapInitOptions","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MapInitOptions","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/mapinitoptions","title":"MapInitOptions","navigatorTitle":[{"kind":"identifier","text":"MapInitOptions"}],"kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PresentationTransactionMode":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PresentationTransactionMode","title":"PresentationTransactionMode","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PresentationTransactionMode","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PresentationTransactionMode"}],"role":"symbol","abstract":[{"text":"Determines if the underlying ","type":"text"},{"code":"CAMetalLayer","type":"codeVoice"},{"text":" rendering output should synchronize with the Core Animation transactions.","type":"text"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/presentationtransactionmode"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GlyphsRasterizationMode":{"title":"GlyphsRasterizationMode","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode","type":"topic","abstract":[{"type":"text","text":"Describes glyphs rasterization modes."}],"url":"\/documentation\/mapboxmaps\/glyphsrasterizationmode","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GlyphsRasterizationMode","kind":"identifier"}],"navigatorTitle":[{"text":"GlyphsRasterizationMode","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMMapOptions/orientation":{"abstract":[{"text":"The orientation of the Map. By default, it is set to","type":"text"},{"type":"text","text":" "},{"code":"Upwards","type":"codeVoice"},{"type":"text","text":"."}],"role":"symbol","type":"topic","fragments":[{"text":"orientation","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/mbmmapoptions\/orientation","title":"orientation","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapOptions\/orientation"},"doc://com.mapbox.MapboxMaps/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapInitOptionsProvider":{"abstract":[{"type":"text","text":"A protocol used to provide "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapInitOptions"},{"type":"text","text":" when initializing a "},{"isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapView","type":"reference"},{"type":"text","text":" with a Storyboard or"},{"type":"text","text":" "},{"type":"text","text":"a nib."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapInitOptionsProvider","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MapInitOptionsProvider","kind":"identifier"}],"navigatorTitle":[{"text":"MapInitOptionsProvider","kind":"identifier"}],"title":"MapInitOptionsProvider","url":"\/documentation\/mapboxmaps\/mapinitoptionsprovider","kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ConstrainMode":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ConstrainMode","navigatorTitle":[{"text":"ConstrainMode","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/constrainmode","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConstrainMode"}],"title":"ConstrainMode","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Describes whether to constrain the map in both axes or only vertically e.g. while panning."}]},"doc://com.mapbox.MapboxMaps/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapView":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapView","role":"symbol","navigatorTitle":[{"text":"MapView","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MapView","kind":"identifier"}],"title":"MapView","url":"\/documentation\/mapboxmaps\/mapview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapOptions/pixelRatio":{"url":"\/documentation\/mapboxmaps\/mapoptions\/pixelratio","navigatorTitle":[{"kind":"identifier","text":"pixelRatio"}],"abstract":[{"text":"The custom pixel ratio. By default, it is set to 1.0","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapOptions\/pixelRatio","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"pixelRatio","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"}],"kind":"symbol","type":"topic","title":"pixelRatio","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"value":"MBMMapOptions","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"MBMMapOptions","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"MBMMapOptions"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapOptions\/constrainMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapOptions\/contextMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapOptions\/crossSourceCollisions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapOptions\/orientation","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapOptions\/size","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapOptions\/viewportMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapOptions\/glyphsRasterizationOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapOptions\/pixelRatio"],"title":"Instance Properties","generated":true},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapOptions\/initWithContextMode:constrainMode:viewportMode:orientation:crossSourceCollisions:size:glyphsRasterizationOptions:","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapOptions\/initWithContextMode:constrainMode:viewportMode:orientation:crossSourceCollisions:size:pixelRatio:glyphsRasterizationOptions:"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"]}]},{"value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ConstrainMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/NorthOrientation","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportMode"],"generated":true,"title":"MapView","anchor":"MapView"}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBMMapOptions"},{"kind":"text","text":" : "},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1NorthOrientation\/title","op":"replace","value":"MBMNorthOrientation"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1NorthOrientation\/fragments","value":[{"text":"MBMNorthOrientation","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"MBMNorthOrientation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1NorthOrientation\/navigatorTitle"},{"value":"MBMMapOptions","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapOptions\/title","op":"replace"},{"value":[{"text":"MBMMapOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapOptions\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapOptions\/navigatorTitle","value":[{"kind":"identifier","text":"MBMMapOptions"}],"op":"replace"},{"op":"replace","value":"glyphsRasterizationOptions","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapOptions~1glyphsRasterizationOptions\/title"},{"op":"replace","value":[{"kind":"identifier","text":"glyphsRasterizationOptions"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapOptions~1glyphsRasterizationOptions\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationOptions\/title","value":"MBMGlyphsRasterizationOptions"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationOptions\/fragments","op":"replace","value":[{"text":"MBMGlyphsRasterizationOptions","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MBMGlyphsRasterizationOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationOptions\/navigatorTitle"},{"op":"replace","value":"MBMViewportMode","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewportMode\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewportMode\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMViewportMode"}]},{"op":"replace","value":[{"text":"MBMViewportMode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewportMode\/navigatorTitle"},{"value":"MBMGlyphsRasterizationMode","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/fragments","value":[{"kind":"identifier","text":"MBMGlyphsRasterizationMode"}]},{"op":"replace","value":[{"text":"MBMGlyphsRasterizationMode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ConstrainMode\/title","value":"MBMConstrainMode"},{"value":[{"text":"MBMConstrainMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ConstrainMode\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ConstrainMode\/navigatorTitle","value":[{"text":"MBMConstrainMode","kind":"identifier"}]},{"op":"replace","value":"pixelRatio","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapOptions~1pixelRatio\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapOptions~1pixelRatio\/fragments","value":[{"text":"pixelRatio","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}