{"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapRecorderOptions","interfaceLanguage":"swift"},"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"],"kind":"relationships","type":"conformsTo"}],"abstract":[{"type":"text","text":"Options for recording the map when using "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapRecorder"}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapPlayerOptions"],"generated":true,"title":"Map Recording","anchor":"Map-Recording"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/maprecorderoptions"]}],"topicSections":[{"title":"Initializers","generated":true,"anchor":"Initializers","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapRecorderOptions\/init(timeWindow:loggingEnabled:compressed:)"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapRecorderOptions","kind":"identifier"}]}],"kind":"declarations"}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"s:10MapboxMaps18MapRecorderOptionsV","modules":[{"name":"MapboxMaps"}],"title":"MapRecorderOptions","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapRecorderOptions","kind":"identifier"}],"role":"symbol","roleHeading":"Structure","symbolKind":"struct","navigatorTitle":[{"kind":"identifier","text":"MapRecorderOptions"}]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapRecorderOptions":{"kind":"symbol","type":"topic","navigatorTitle":[{"text":"MapRecorderOptions","kind":"identifier"}],"abstract":[{"text":"Options for recording the map when using ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapRecorder","isActive":true}],"role":"symbol","title":"MapRecorderOptions","url":"\/documentation\/mapboxmaps\/maprecorderoptions","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapRecorderOptions"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapRecorderOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Performance":{"abstract":[],"role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","title":"Performance and investigations","url":"\/documentation\/mapboxmaps\/performance","kind":"article","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","url":"\/documentation\/mapboxmaps","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"title":"MapboxMaps","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapRecorderOptions/init(timeWindow:loggingEnabled:compressed:)":{"abstract":[{"type":"text","text":"Initializes a set of options to control the recording of a map recording"}],"title":"init(timeWindow:loggingEnabled:compressed:)","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapRecorderOptions\/init(timeWindow:loggingEnabled:compressed:)","url":"\/documentation\/mapboxmaps\/maprecorderoptions\/init(timewindow:loggingenabled:compressed:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"timeWindow","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"loggingEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"compressed"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":")","kind":"text"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","abstract":[],"type":"topic","kind":"article","title":"MapboxMaps Documentation","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapPlayerOptions":{"url":"\/documentation\/mapboxmaps\/mapplayeroptions","title":"MapPlayerOptions","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"MapPlayerOptions","kind":"identifier"}],"navigatorTitle":[{"text":"MapPlayerOptions","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Options for playback when using "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapRecorder","isActive":true,"type":"reference"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapPlayerOptions"},"doc://com.mapbox.MapboxMaps/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s8SendableP","title":"Swift.Sendable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapRecorder":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapRecorder","url":"\/documentation\/mapboxmaps\/maprecorder","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapRecorder"}],"abstract":[{"text":"MapRecorder provides functions to record and replay API calls of a Map instance.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"These recordings can be used to debug issues which requie multiple steps to reproduce."},{"text":" ","type":"text"},{"type":"text","text":"Additionaly, playbacks can be used for performance testing custom scenarios."}],"title":"MapRecorder","navigatorTitle":[{"kind":"identifier","text":"MapRecorder"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MBMMapRecorder","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapRecorder\/title"},{"value":[{"text":"MBMMapRecorder","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapRecorder\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapRecorder\/navigatorTitle","value":[{"text":"MBMMapRecorder","kind":"identifier"}],"op":"replace"}]}]}