{"metadata":{"role":"symbol","roleHeading":"Function","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"MBMSourceDataLoadedTypeToString","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@MBMSourceDataLoadedType","text":"SourceDataLoadedType","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"modules":[{"name":"MapboxMaps"}],"externalID":"c:@F@MBMSourceDataLoadedTypeToString","title":"MBMSourceDataLoadedTypeToString(_:)","symbolKind":"func","navigatorTitle":[{"text":"MBMSourceDataLoadedTypeToString","kind":"identifier"}]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMSourceDataLoadedTypeToString(_:)"},"seeAlsoSections":[{"anchor":"Symbols","title":"Symbols","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapRecorder","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeatureExtensionValue","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Size","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackError-swift.class","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestErrorType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapLoadingErrorTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRenderModeTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestDataSourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestErrorTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestLoadingMethodTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestPriorityTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestPriorityTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestResourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMResponseSourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStyleDataLoadedTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMTileStoreUsageModeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraChangedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GenericEventCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinishedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameStartedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequestCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceAddedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceRemovedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageMissingCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapIdleCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnusedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TransitionOptions-swift.class"]}],"variants":[{"paths":["\/documentation\/mapboxmaps\/mbmsourcedataloadedtypetostring(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/mbmsourcedataloadedtypetostring(_:)"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBMSourceDataLoadedTypeToString"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"source_data_loaded_type","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@MBMSourceDataLoadedType","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedType","text":"SourceDataLoadedType"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMapsInternal"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMapsInternal":{"url":"\/documentation\/mapboxmaps\/coremapsinternal","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMapsInternal","type":"topic","kind":"article","title":"CoreMaps - Internal","abstract":[{"type":"text","text":"Maps rendering SDK also known as GL-Native. These are for internal use only."}],"role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceRemovedCallback":{"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceRemovedCallback"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceRemovedCallback","abstract":[{"type":"text","text":"The source has been removed with "},{"type":"codeVoice","code":"removeStyleSource"},{"type":"text","text":" method."}],"url":"\/documentation\/mapboxmaps\/sourceremovedcallback","role":"symbol","kind":"symbol","type":"topic","title":"SourceRemovedCallback","navigatorTitle":[{"text":"SourceRemovedCallback","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderFrameFinishedCallback":{"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"map"},{"text":" finished rendering a frame.","type":"text"}],"url":"\/documentation\/mapboxmaps\/renderframefinishedcallback","kind":"symbol","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RenderFrameFinishedCallback"}],"type":"topic","navigatorTitle":[{"text":"RenderFrameFinishedCallback","kind":"identifier"}],"title":"RenderFrameFinishedCallback","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinishedCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRequestDataSourceTypeToString(_:)":{"kind":"symbol","title":"MBMRequestDataSourceTypeToString(_:)","type":"topic","navigatorTitle":[{"text":"MBMRequestDataSourceTypeToString","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/mbmrequestdatasourcetypetostring(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestDataSourceTypeToString(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBMRequestDataSourceTypeToString"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"RequestDataSourceType","preciseIdentifier":"c:@E@MBMRequestDataSourceType"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"!"}],"abstract":[],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResourceRequestCallback":{"kind":"symbol","title":"ResourceRequestCallback","type":"topic","navigatorTitle":[{"text":"ResourceRequestCallback","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/resourcerequestcallback","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequestCallback","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResourceRequestCallback"}],"abstract":[{"type":"text","text":"The "},{"code":"ResourceRequest","type":"codeVoice"},{"type":"text","text":" event allows the application to observe resourcerequests"},{"type":"text","text":" "},{"type":"text","text":"made by a "},{"code":"map","type":"codeVoice"},{"type":"text","text":" or "},{"type":"codeVoice","code":"map snapshotter"},{"text":" object.","type":"text"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoadingErrorCallback":{"type":"topic","url":"\/documentation\/mapboxmaps\/maploadingerrorcallback","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"MapLoadingErrorCallback","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Describes an error that has occurred while loading the ","type":"text"},{"code":"map","type":"codeVoice"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorCallback","title":"MapLoadingErrorCallback","navigatorTitle":[{"text":"MapLoadingErrorCallback","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleImageRemoveUnusedCallback":{"type":"topic","url":"\/documentation\/mapboxmaps\/styleimageremoveunusedcallback","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StyleImageRemoveUnusedCallback","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"An image requested by the "},{"type":"codeVoice","code":"map"},{"type":"text","text":" through the "},{"type":"codeVoice","code":"StyleImageMissing"},{"type":"text","text":" event is no longer"},{"type":"text","text":" "},{"text":"needed and can be removed using the ","type":"text"},{"type":"codeVoice","code":"removeStyleImage"},{"type":"text","text":" method. The application can"},{"text":" ","type":"text"},{"type":"text","text":"decide whether the image should be kept or removed."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnusedCallback","title":"StyleImageRemoveUnusedCallback","navigatorTitle":[{"kind":"identifier","text":"StyleImageRemoveUnusedCallback"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleImageMissingCallback":{"type":"topic","url":"\/documentation\/mapboxmaps\/styleimagemissingcallback","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StyleImageMissingCallback","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"A style needs an image that is missing from the sprite sheet. This event is"},{"text":" ","type":"text"},{"type":"text","text":"emitted when the "},{"type":"codeVoice","code":"map"},{"type":"text","text":" renders visible tiles, and one of the required images"},{"text":" ","type":"text"},{"type":"text","text":"is missing in the sprite sheet. The event observer has to provide the missing"},{"type":"text","text":" "},{"text":"image by calling the ","type":"text"},{"type":"codeVoice","code":"addStyleImage"},{"type":"text","text":" method."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageMissingCallback","title":"StyleImageMissingCallback","navigatorTitle":[{"text":"StyleImageMissingCallback","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMTileStoreUsageModeToString(_:)":{"type":"topic","url":"\/documentation\/mapboxmaps\/mbmtilestoreusagemodetostring(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"MBMTileStoreUsageModeToString","kind":"identifier"},{"text":"(","kind":"text"},{"text":"TileStoreUsageMode","preciseIdentifier":"c:@E@MBMTileStoreUsageMode","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"!"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMTileStoreUsageModeToString(_:)","title":"MBMTileStoreUsageModeToString(_:)","navigatorTitle":[{"kind":"identifier","text":"MBMTileStoreUsageModeToString"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GenericEventCallback":{"title":"GenericEventCallback","type":"topic","url":"\/documentation\/mapboxmaps\/genericeventcallback","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"GenericEventCallback","kind":"identifier"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GenericEventCallback"}],"abstract":[{"text":"Generic event for experimental events.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GenericEventCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRenderModeTypeToString(_:)":{"kind":"symbol","title":"MBMRenderModeTypeToString(_:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MBMRenderModeTypeToString"}],"url":"\/documentation\/mapboxmaps\/mbmrendermodetypetostring(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRenderModeTypeToString(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBMRenderModeTypeToString","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@MBMRenderModeType","text":"RenderModeType","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"abstract":[],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMSourceDataLoadedTypeToString(_:)":{"kind":"symbol","title":"MBMSourceDataLoadedTypeToString(_:)","type":"topic","navigatorTitle":[{"text":"MBMSourceDataLoadedTypeToString","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/mbmsourcedataloadedtypetostring(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMSourceDataLoadedTypeToString(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBMSourceDataLoadedTypeToString","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SourceDataLoadedType","preciseIdentifier":"c:@E@MBMSourceDataLoadedType"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}],"abstract":[],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePackError-swift.class":{"type":"topic","url":"\/documentation\/mapboxmaps\/stylepackerror-swift.class","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StylePackError","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Describes a style package load request error."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackError-swift.class","title":"StylePackError","navigatorTitle":[{"kind":"identifier","text":"StylePackError"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapIdleCallback":{"kind":"symbol","title":"MapIdleCallback","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MapIdleCallback"}],"url":"\/documentation\/mapboxmaps\/mapidlecallback","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapIdleCallback","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"MapIdleCallback","kind":"identifier"}],"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"map"},{"type":"text","text":" has entered the idle state. The "},{"code":"map","type":"codeVoice"},{"text":" is idle when there are no ongoing","type":"text"},{"type":"text","text":" "},{"type":"text","text":"animations, transitions and the "},{"type":"codeVoice","code":"map"},{"type":"text","text":" has rendered all requested non-volatile tiles"},{"type":"text","text":" "},{"text":"(e.g., live traffic tiles). The event will not be emitted if ","type":"text"},{"type":"codeVoice","code":"setUserAnimationInProgress"},{"type":"text","text":" "},{"type":"text","text":"and \/ or "},{"code":"setGestureInProgress","type":"codeVoice"},{"type":"text","text":" is set to "},{"type":"codeVoice","code":"true"},{"text":".","type":"text"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","role":"collection","kind":"article","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"type":"topic","role":"collection","url":"\/documentation\/mapboxmaps","title":"MapboxMaps","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TransitionOptions-swift.class":{"kind":"symbol","title":"TransitionOptions","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TransitionOptions"}],"url":"\/documentation\/mapboxmaps\/transitionoptions-swift.class","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TransitionOptions-swift.class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TransitionOptions","kind":"identifier"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"transition options"},{"type":"text","text":" controls timing for the interpolation between a transitionable style"},{"text":" ","type":"text"},{"type":"text","text":"property’s previous value and new value. These can be used to define the style default property"},{"type":"text","text":" "},{"text":"transition behavior. Also, any transitionable style property may also have its own ","type":"text"},{"type":"codeVoice","code":"-transition"},{"type":"text","text":" "},{"type":"text","text":"property that defines specific transition timing for that specific layer property, overriding"},{"text":" ","type":"text"},{"type":"text","text":"the global transition values."}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMStyleDataLoadedTypeToString(_:)":{"kind":"symbol","title":"MBMStyleDataLoadedTypeToString(_:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MBMStyleDataLoadedTypeToString"}],"url":"\/documentation\/mapboxmaps\/mbmstyledataloadedtypetostring(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStyleDataLoadedTypeToString(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBMStyleDataLoadedTypeToString","kind":"identifier"},{"kind":"text","text":"("},{"text":"StyleDataLoadedType","preciseIdentifier":"c:@E@MBMStyleDataLoadedType","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"!"}],"abstract":[],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMResponseSourceTypeToString(_:)":{"kind":"symbol","title":"MBMResponseSourceTypeToString(_:)","type":"topic","navigatorTitle":[{"text":"MBMResponseSourceTypeToString","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/mbmresponsesourcetypetostring(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMResponseSourceTypeToString(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"MBMResponseSourceTypeToString","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"ResponseSourceType","preciseIdentifier":"c:@E@MBMResponseSourceType"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}],"abstract":[],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceAddedCallback":{"type":"topic","url":"\/documentation\/mapboxmaps\/sourceaddedcallback","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SourceAddedCallback"}],"role":"symbol","abstract":[{"type":"text","text":"The source has been added with "},{"type":"codeVoice","code":"addStyleSource"},{"type":"text","text":" method."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceAddedCallback","title":"SourceAddedCallback","navigatorTitle":[{"text":"SourceAddedCallback","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleLoadedCallback":{"title":"StyleLoadedCallback","type":"topic","url":"\/documentation\/mapboxmaps\/styleloadedcallback","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"StyleLoadedCallback","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"StyleLoadedCallback","kind":"identifier"}],"abstract":[{"type":"text","text":"The requested style has been fully loaded, including specified sprite, and sources’ metadata."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleLoadedCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestErrorType":{"title":"RequestErrorType","abstract":[{"type":"text","text":"The enumeration defines the error type that may occur during a resource request."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RequestErrorType","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/requesterrortype","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestErrorType","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"RequestErrorType"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FeatureExtensionValue":{"kind":"symbol","title":"FeatureExtensionValue","type":"topic","navigatorTitle":[{"text":"FeatureExtensionValue","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/featureextensionvalue","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeatureExtensionValue","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FeatureExtensionValue","kind":"identifier"}],"abstract":[{"type":"text","text":"A value or a collection of a feature extension."}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceDataLoadedCallback":{"type":"topic","url":"\/documentation\/mapboxmaps\/sourcedataloadedcallback","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SourceDataLoadedCallback","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedCallback","abstract":[{"type":"text","text":"The "},{"code":"SourceDataLoaded","type":"codeVoice"},{"type":"text","text":" event is emitted when source data is loaded."}],"title":"SourceDataLoadedCallback","navigatorTitle":[{"text":"SourceDataLoadedCallback","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMMapLoadingErrorTypeToString(_:)":{"type":"topic","url":"\/documentation\/mapboxmaps\/mbmmaploadingerrortypetostring(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBMMapLoadingErrorTypeToString"},{"text":"(","kind":"text"},{"text":"MapLoadingErrorType","preciseIdentifier":"c:@E@MBMMapLoadingErrorType","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapLoadingErrorTypeToString(_:)","title":"MBMMapLoadingErrorTypeToString(_:)","navigatorTitle":[{"text":"MBMMapLoadingErrorTypeToString","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRequestResourceTypeToString(_:)":{"type":"topic","url":"\/documentation\/mapboxmaps\/mbmrequestresourcetypetostring(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBMRequestResourceTypeToString"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"RequestResourceType","preciseIdentifier":"c:@E@MBMRequestResourceType"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestResourceTypeToString(_:)","title":"MBMRequestResourceTypeToString(_:)","navigatorTitle":[{"kind":"identifier","text":"MBMRequestResourceTypeToString"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraChangedCallback":{"title":"CameraChangedCallback","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"CameraChangedCallback","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraChangedCallback","url":"\/documentation\/mapboxmaps\/camerachangedcallback","navigatorTitle":[{"kind":"identifier","text":"CameraChangedCallback"}],"type":"topic","abstract":[{"text":"This event is emitted whenever the visible viewport changes its size","type":"text"},{"type":"text","text":" "},{"text":"due to the invocation of the ","type":"text"},{"code":"setSize","type":"codeVoice"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"setBounds"},{"text":" methods or when","type":"text"},{"type":"text","text":" "},{"type":"text","text":"the camera is modified by calling camera methods. The event is emitted"},{"type":"text","text":" "},{"text":"synchronously so that an updated camera state can be fetched immediately.","type":"text"}],"role":"symbol","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceDataLoadedType":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SourceDataLoadedType"}],"url":"\/documentation\/mapboxmaps\/sourcedataloadedtype","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedType","title":"SourceDataLoadedType","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The enumeration defines the type of loaded source data."}],"navigatorTitle":[{"kind":"identifier","text":"SourceDataLoadedType"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRequestPriorityTypeToString(_:)":{"kind":"symbol","title":"MBMRequestPriorityTypeToString(_:)","type":"topic","navigatorTitle":[{"text":"MBMRequestPriorityTypeToString","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/mbmrequestprioritytypetostring(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestPriorityTypeToString(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBMRequestPriorityTypeToString"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@MBMRequestPriorityType","text":"RequestPriorityType","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}],"abstract":[],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Size":{"url":"\/documentation\/mapboxmaps\/size","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Size","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Size","kind":"identifier"}],"abstract":[{"type":"text","text":"Size type."}],"title":"Size","navigatorTitle":[{"text":"Size","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleDataLoadedCallback":{"type":"topic","url":"\/documentation\/mapboxmaps\/styledataloadedcallback","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"StyleDataLoadedCallback","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedCallback","abstract":[{"type":"text","text":"The style data has been loaded."}],"title":"StyleDataLoadedCallback","navigatorTitle":[{"text":"StyleDataLoadedCallback","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRequestErrorTypeToString(_:)":{"type":"topic","url":"\/documentation\/mapboxmaps\/mbmrequesterrortypetostring(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBMRequestErrorTypeToString"},{"text":"(","kind":"text"},{"text":"RequestErrorType","preciseIdentifier":"c:@E@MBMRequestErrorType","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"!"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestErrorTypeToString(_:)","title":"MBMRequestErrorTypeToString(_:)","navigatorTitle":[{"text":"MBMRequestErrorTypeToString","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoadedCallback":{"type":"topic","url":"\/documentation\/mapboxmaps\/maploadedcallback","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapLoadedCallback"}],"role":"symbol","abstract":[{"type":"text","text":"The style has been fully loaded, and the "},{"code":"map","type":"codeVoice"},{"type":"text","text":" has rendered all visible tiles."},{"type":"text","text":" "},{"type":"text","text":"The event will be emitted only once for the current style. If it is required to"},{"type":"text","text":" "},{"text":"continuously observe an event where all the necessary resources are loaded or rendered,","type":"text"},{"type":"text","text":" "},{"text":"please check the following events: ","type":"text"},{"type":"codeVoice","code":"MapIdle"},{"type":"text","text":", "},{"type":"codeVoice","code":"StyleDataLoaded"},{"type":"text","text":", and "},{"code":"RenderFrameFinished","type":"codeVoice"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadedCallback","title":"MapLoadedCallback","navigatorTitle":[{"text":"MapLoadedCallback","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRequestLoadingMethodTypeToString(_:)":{"title":"MBMRequestLoadingMethodTypeToString(_:)","type":"topic","url":"\/documentation\/mapboxmaps\/mbmrequestloadingmethodtypetostring(_:)","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBMRequestLoadingMethodTypeToString"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"MBMRequestLoadingMethodTypeToString","kind":"identifier"},{"text":"(","kind":"text"},{"text":"RequestLoadingMethodType","preciseIdentifier":"c:@E@MBMRequestLoadingMethodType","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}],"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestLoadingMethodTypeToString(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapRecorder":{"title":"MapRecorder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MapRecorder","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapRecorder","url":"\/documentation\/mapboxmaps\/maprecorder","navigatorTitle":[{"kind":"identifier","text":"MapRecorder"}],"type":"topic","abstract":[{"text":"MapRecorder provides functions to record and replay API calls of a Map instance.","type":"text"},{"type":"text","text":" "},{"text":"These recordings can be used to debug issues which requie multiple steps to reproduce.","type":"text"},{"type":"text","text":" "},{"text":"Additionaly, playbacks can be used for performance testing custom scenarios.","type":"text"}],"role":"symbol","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderFrameStartedCallback":{"type":"topic","url":"\/documentation\/mapboxmaps\/renderframestartedcallback","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"RenderFrameStartedCallback","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"map"},{"type":"text","text":" started rendering a frame."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameStartedCallback","title":"RenderFrameStartedCallback","navigatorTitle":[{"text":"RenderFrameStartedCallback","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Function","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"MBMSourceDataLoadedTypeToString","op":"replace"},{"path":"\/metadata\/symbolKind","value":"func","op":"replace"},{"op":"replace","value":[{"text":"MBMSourceDataLoadedTypeToString","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":[{"title":"Symbols","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapRecorder","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeatureExtensionValue","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Size","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackError-swift.class","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestErrorType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapLoadingErrorTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRenderModeTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestDataSourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestErrorTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestLoadingMethodTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestPriorityTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestPriorityTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestResourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMResponseSourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStyleDataLoadedTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMTileStoreUsageModeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraChangedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GenericEventCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinishedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameStartedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequestCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceAddedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceRemovedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageMissingCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapIdleCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnusedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TransitionOptions-swift.class"],"anchor":"Symbols","generated":true}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"text":"MBMSourceDataLoadedTypeToString","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedType","text":"MBMSourceDataLoadedType","preciseIdentifier":"c:@E@MBMSourceDataLoadedType"},{"kind":"text","text":" "},{"text":"source_data_loaded_type","kind":"internalParam"},{"kind":"text","text":");"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceRemovedCallback\/title","value":"MBMSourceRemovedCallback"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceRemovedCallback\/fragments","value":[{"text":"MBMSourceRemovedCallback","kind":"identifier"}]},{"value":[{"text":"MBMSourceRemovedCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceRemovedCallback\/navigatorTitle","op":"replace"},{"op":"replace","value":"MBMRenderFrameFinishedCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinishedCallback\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinishedCallback\/fragments","value":[{"kind":"identifier","text":"MBMRenderFrameFinishedCallback"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinishedCallback\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMRenderFrameFinishedCallback"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestDataSourceTypeToString(_:)\/title","value":"MBMRequestDataSourceTypeToString"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestDataSourceTypeToString(_:)\/fragments","value":[{"kind":"identifier","text":"MBMRequestDataSourceTypeToString"}]},{"op":"replace","value":"MBMResourceRequestCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequestCallback\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequestCallback\/fragments","op":"replace","value":[{"text":"MBMResourceRequestCallback","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MBMResourceRequestCallback"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequestCallback\/navigatorTitle"},{"op":"replace","value":"MBMMapLoadingErrorCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorCallback\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorCallback\/fragments","value":[{"kind":"identifier","text":"MBMMapLoadingErrorCallback"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorCallback\/navigatorTitle","value":[{"kind":"identifier","text":"MBMMapLoadingErrorCallback"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnusedCallback\/title","value":"MBMStyleImageRemoveUnusedCallback","op":"replace"},{"value":[{"kind":"identifier","text":"MBMStyleImageRemoveUnusedCallback"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnusedCallback\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnusedCallback\/navigatorTitle","value":[{"text":"MBMStyleImageRemoveUnusedCallback","kind":"identifier"}]},{"op":"replace","value":"MBMStyleImageMissingCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageMissingCallback\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageMissingCallback\/fragments","value":[{"kind":"identifier","text":"MBMStyleImageMissingCallback"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageMissingCallback\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMStyleImageMissingCallback"}]},{"op":"replace","value":"MBMTileStoreUsageModeToString","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMTileStoreUsageModeToString(_:)\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMTileStoreUsageModeToString(_:)\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMTileStoreUsageModeToString"}]},{"value":"MBMGenericEventCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEventCallback\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEventCallback\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMGenericEventCallback"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEventCallback\/navigatorTitle","value":[{"kind":"identifier","text":"MBMGenericEventCallback"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRenderModeTypeToString(_:)\/title","value":"MBMRenderModeTypeToString","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRenderModeTypeToString(_:)\/fragments","op":"replace","value":[{"text":"MBMRenderModeTypeToString","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMSourceDataLoadedTypeToString(_:)\/title","value":"MBMSourceDataLoadedTypeToString","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMSourceDataLoadedTypeToString(_:)\/fragments","value":[{"kind":"identifier","text":"MBMSourceDataLoadedTypeToString"}]},{"op":"replace","value":"MBMStylePackError","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackError-swift.class\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackError-swift.class\/fragments","value":[{"kind":"identifier","text":"MBMStylePackError"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackError-swift.class\/navigatorTitle","value":[{"text":"MBMStylePackError","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdleCallback\/title","value":"MBMMapIdleCallback"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdleCallback\/fragments","value":[{"text":"MBMMapIdleCallback","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdleCallback\/navigatorTitle","value":[{"text":"MBMMapIdleCallback","kind":"identifier"}]},{"op":"replace","value":"MBMTransitionOptions","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TransitionOptions-swift.class\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TransitionOptions-swift.class\/fragments","value":[{"kind":"identifier","text":"MBMTransitionOptions"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TransitionOptions-swift.class\/navigatorTitle","op":"replace","value":[{"text":"MBMTransitionOptions","kind":"identifier"}]},{"value":"MBMStyleDataLoadedTypeToString","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMStyleDataLoadedTypeToString(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMStyleDataLoadedTypeToString(_:)\/fragments","value":[{"text":"MBMStyleDataLoadedTypeToString","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMResponseSourceTypeToString(_:)\/title","op":"replace","value":"MBMResponseSourceTypeToString"},{"value":[{"kind":"identifier","text":"MBMResponseSourceTypeToString"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMResponseSourceTypeToString(_:)\/fragments"},{"value":"MBMSourceAddedCallback","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAddedCallback\/title"},{"value":[{"kind":"identifier","text":"MBMSourceAddedCallback"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAddedCallback\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAddedCallback\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMSourceAddedCallback"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoadedCallback\/title","value":"MBMStyleLoadedCallback","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoadedCallback\/fragments","value":[{"kind":"identifier","text":"MBMStyleLoadedCallback"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoadedCallback\/navigatorTitle","value":[{"text":"MBMStyleLoadedCallback","kind":"identifier"}],"op":"replace"},{"value":"MBMRequestErrorType","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestErrorType\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestErrorType\/fragments","op":"replace","value":[{"text":"MBMRequestErrorType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestErrorType\/navigatorTitle","value":[{"kind":"identifier","text":"MBMRequestErrorType"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeatureExtensionValue\/title","value":"MBMFeatureExtensionValue","op":"replace"},{"op":"replace","value":[{"text":"MBMFeatureExtensionValue","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeatureExtensionValue\/fragments"},{"value":[{"kind":"identifier","text":"MBMFeatureExtensionValue"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeatureExtensionValue\/navigatorTitle","op":"replace"},{"op":"replace","value":"MBMSourceDataLoadedCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedCallback\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedCallback\/fragments","value":[{"text":"MBMSourceDataLoadedCallback","kind":"identifier"}],"op":"replace"},{"value":[{"text":"MBMSourceDataLoadedCallback","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedCallback\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMMapLoadingErrorTypeToString(_:)\/title","value":"MBMMapLoadingErrorTypeToString"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMMapLoadingErrorTypeToString(_:)\/fragments","value":[{"text":"MBMMapLoadingErrorTypeToString","kind":"identifier"}]},{"value":"MBMRequestResourceTypeToString","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestResourceTypeToString(_:)\/title"},{"value":[{"text":"MBMRequestResourceTypeToString","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestResourceTypeToString(_:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChangedCallback\/title","value":"MBMCameraChangedCallback"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChangedCallback\/fragments","value":[{"text":"MBMCameraChangedCallback","kind":"identifier"}]},{"value":[{"text":"MBMCameraChangedCallback","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChangedCallback\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedType\/title","op":"replace","value":"MBMSourceDataLoadedType"},{"op":"replace","value":[{"text":"MBMSourceDataLoadedType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedType\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedType\/navigatorTitle","value":[{"text":"MBMSourceDataLoadedType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestPriorityTypeToString(_:)\/title","op":"replace","value":"MBMRequestPriorityTypeToString"},{"op":"replace","value":[{"kind":"identifier","text":"MBMRequestPriorityTypeToString"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestPriorityTypeToString(_:)\/fragments"},{"op":"replace","value":"MBMSize","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Size\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Size\/fragments","value":[{"text":"MBMSize","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Size\/navigatorTitle","value":[{"kind":"identifier","text":"MBMSize"}],"op":"replace"},{"value":"MBMStyleDataLoadedCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedCallback\/title","op":"replace"},{"value":[{"text":"MBMStyleDataLoadedCallback","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedCallback\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedCallback\/navigatorTitle","value":[{"kind":"identifier","text":"MBMStyleDataLoadedCallback"}],"op":"replace"},{"value":"MBMRequestErrorTypeToString","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestErrorTypeToString(_:)\/title"},{"op":"replace","value":[{"text":"MBMRequestErrorTypeToString","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestErrorTypeToString(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadedCallback\/title","value":"MBMMapLoadedCallback","op":"replace"},{"value":[{"kind":"identifier","text":"MBMMapLoadedCallback"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadedCallback\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadedCallback\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMMapLoadedCallback"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestLoadingMethodTypeToString(_:)\/title","value":"MBMRequestLoadingMethodTypeToString","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestLoadingMethodTypeToString(_:)\/fragments","value":[{"text":"MBMRequestLoadingMethodTypeToString","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapRecorder\/title","value":"MBMMapRecorder","op":"replace"},{"value":[{"kind":"identifier","text":"MBMMapRecorder"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapRecorder\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MBMMapRecorder"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapRecorder\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameStartedCallback\/title","op":"replace","value":"MBMRenderFrameStartedCallback"},{"value":[{"kind":"identifier","text":"MBMRenderFrameStartedCallback"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameStartedCallback\/fragments"},{"value":[{"text":"MBMRenderFrameStartedCallback","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameStartedCallback\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}