{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"PuckRenderingData","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PuckRenderingData"}],"externalID":"s:10MapboxMaps17PuckRenderingDataV","title":"PuckRenderingData","symbolKind":"struct","modules":[{"name":"MapboxMaps"}],"roleHeading":"Structure"},"abstract":[{"text":"Represents the interpolated data ready to render the user location puck.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckRenderingData"},"topicSections":[{"title":"Initializers","anchor":"Initializers","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckRenderingData\/init(location:heading:)"]},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckRenderingData\/heading","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckRenderingData\/location"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckRenderingData\/Equatable-Implementations"],"generated":true,"title":"Default Implementations","anchor":"Default-Implementations"}],"seeAlsoSections":[{"title":"Location","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationManager","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck2DConfiguration","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Model","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckBearing","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProviderDelegate","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Coordinate2D","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationExtraKeys","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProviderRequest","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceFactory","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/DeviceLocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Heading","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/IntervalSettings"],"anchor":"Location"}],"kind":"symbol","variants":[{"paths":["\/documentation\/mapboxmaps\/puckrenderingdata"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/SQ"],"type":"conformsTo","title":"Conforms To"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PuckRenderingData"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PermissionStatus":{"abstract":[{"text":"Location permissions granted by user to the app.","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus","url":"\/documentation\/mapboxcommon\/permissionstatus","type":"topic","title":"PermissionStatus","navigatorTitle":[{"text":"PermissionStatus","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PermissionStatus"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/IntervalSettings":{"abstract":[{"type":"text","text":"The interval for active location updates"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/IntervalSettings","url":"\/documentation\/mapboxcommon\/intervalsettings","type":"topic","title":"IntervalSettings","navigatorTitle":[{"text":"IntervalSettings","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IntervalSettings"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Puck3DConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"Puck3DConfiguration"}],"kind":"symbol","title":"Puck3DConfiguration","role":"symbol","abstract":[],"url":"\/documentation\/mapboxmaps\/puck3dconfiguration","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Puck3DConfiguration"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Coordinate2D":{"navigatorTitle":[{"text":"Coordinate2D","kind":"identifier"}],"kind":"symbol","title":"Coordinate2D","role":"symbol","abstract":[{"type":"text","text":"Boxed version of CLLocationCoordinate2D"}],"url":"\/documentation\/mapboxcommon\/coordinate2d","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Coordinate2D","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Coordinate2D","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationProviderRequest":{"abstract":[{"text":"Data model that contains parameters for location requests.","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProviderRequest","url":"\/documentation\/mapboxcommon\/locationproviderrequest","type":"topic","title":"LocationProviderRequest","navigatorTitle":[{"text":"LocationProviderRequest","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"LocationProviderRequest","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationServiceFactory":{"navigatorTitle":[{"text":"LocationServiceFactory","kind":"identifier"}],"kind":"symbol","title":"LocationServiceFactory","role":"symbol","abstract":[{"type":"text","text":"Location service factory."}],"url":"\/documentation\/mapboxcommon\/locationservicefactory","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceFactory","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"LocationServiceFactory","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeadingObserver":{"navigatorTitle":[{"text":"HeadingObserver","kind":"identifier"}],"kind":"symbol","title":"HeadingObserver","role":"symbol","abstract":[{"type":"text","text":"Listens to "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingProvider"},{"type":"text","text":"’s updates."}],"url":"\/documentation\/mapboxmaps\/headingobserver","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingObserver","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"HeadingObserver","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LocationManager":{"navigatorTitle":[{"text":"LocationManager","kind":"identifier"}],"kind":"symbol","title":"LocationManager","role":"symbol","abstract":[{"type":"text","text":"An object responsible for managing user location Puck."}],"url":"\/documentation\/mapboxmaps\/locationmanager","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationManager","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"LocationManager","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PuckRenderingData/heading":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Puck’s heading."}],"url":"\/documentation\/mapboxmaps\/puckrenderingdata\/heading","title":"heading","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckRenderingData\/heading","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"heading","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10MapboxMaps7HeadingV","kind":"typeIdentifier","text":"Heading"},{"kind":"text","text":"?"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PuckRenderingData/init(location:heading:)":{"url":"\/documentation\/mapboxmaps\/puckrenderingdata\/init(location:heading:)","title":"init(location:heading:)","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Creates a puck rendering data."}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckRenderingData\/init(location:heading:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"location"},{"text":": ","kind":"text"},{"text":"Location","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXLocation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"heading"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps7HeadingV","text":"Heading","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Model":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Model","type":"topic","url":"\/documentation\/mapboxmaps\/model","kind":"symbol","abstract":[{"type":"text","text":"A structure represeting a Model"}],"title":"Model","role":"symbol","navigatorTitle":[{"text":"Model","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Model","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationExtraKeys":{"title":"LocationExtraKeys","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationExtraKeys"}],"abstract":[{"type":"text","text":"Keys for additional information (extra) in Location."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationExtraKeys","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocationExtraKeys"}],"url":"\/documentation\/mapboxcommon\/locationextrakeys","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Location-APIs":{"abstract":[],"title":"Location","kind":"article","url":"\/documentation\/mapboxmaps\/location-apis","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","type":"topic","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PuckRenderingData/Equatable-Implementations":{"type":"topic","kind":"article","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckRenderingData\/Equatable-Implementations","url":"\/documentation\/mapboxmaps\/puckrenderingdata\/equatable-implementations","title":"Equatable Implementations","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AppleLocationProvider":{"abstract":[{"text":"A location provider based on CoreLocation’s ","type":"text"},{"type":"codeVoice","code":"CLLocationManager"},{"text":".","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProvider","url":"\/documentation\/mapboxmaps\/applelocationprovider","type":"topic","title":"AppleLocationProvider","navigatorTitle":[{"text":"AppleLocationProvider","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AppleLocationProvider","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationServiceObserver":{"navigatorTitle":[{"text":"LocationServiceObserver","kind":"identifier"}],"kind":"symbol","title":"LocationServiceObserver","role":"symbol","abstract":[{"type":"text","text":"Observers for getting updates from LocationService."}],"url":"\/documentation\/mapboxcommon\/locationserviceobserver","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"LocationServiceObserver","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationErrorCode":{"abstract":[{"text":"Codes of location errors.","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode","url":"\/documentation\/mapboxcommon\/locationerrorcode","type":"topic","title":"LocationErrorCode","navigatorTitle":[{"kind":"identifier","text":"LocationErrorCode"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationErrorCode","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Puck2DConfiguration":{"title":"Puck2DConfiguration","url":"\/documentation\/mapboxmaps\/puck2dconfiguration","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck2DConfiguration","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"Puck2DConfiguration","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"Puck2DConfiguration","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/AccuracyAuthorization":{"navigatorTitle":[{"text":"AccuracyAuthorization","kind":"identifier"}],"kind":"symbol","title":"AccuracyAuthorization","role":"symbol","abstract":[{"type":"text","text":"Accuracy authorization granted by user to the app."}],"url":"\/documentation\/mapboxcommon\/accuracyauthorization","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AccuracyAuthorization","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationProvider":{"navigatorTitle":[{"text":"LocationProvider","kind":"identifier"}],"kind":"symbol","title":"LocationProvider","role":"symbol","abstract":[{"type":"text","text":"Location provider that provides locations"}],"url":"\/documentation\/mapboxcommon\/locationprovider","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"LocationProvider","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PuckRenderingData/location":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Puck’s location."}],"url":"\/documentation\/mapboxmaps\/puckrenderingdata\/location","title":"location","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckRenderingData\/location","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"location","kind":"identifier"},{"kind":"text","text":": "},{"text":"Location","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXLocation"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Heading":{"abstract":[{"text":"The azimuth (orientation) of the user’s device, relative to true or magnetic north.","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Heading","url":"\/documentation\/mapboxmaps\/heading","type":"topic","title":"Heading","navigatorTitle":[{"text":"Heading","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"Heading","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/DeviceLocationProvider":{"abstract":[{"type":"text","text":"Location provider specialisation that provides real-time locations generated from the device"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/DeviceLocationProvider","url":"\/documentation\/mapboxcommon\/devicelocationprovider","type":"topic","title":"DeviceLocationProvider","navigatorTitle":[{"text":"DeviceLocationProvider","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DeviceLocationProvider"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AppleLocationProviderDelegate":{"abstract":[{"type":"text","text":"The "},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProviderDelegate","isActive":true},{"text":" protocol defines a set of optional methods that you","type":"text"},{"type":"text","text":" "},{"text":"can use to receive events from an associated location provider object.","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProviderDelegate","url":"\/documentation\/mapboxmaps\/applelocationproviderdelegate","type":"topic","title":"AppleLocationProviderDelegate","navigatorTitle":[{"text":"AppleLocationProviderDelegate","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AppleLocationProviderDelegate"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/AccuracyLevel":{"abstract":[{"type":"text","text":"The accuracy of the observed location"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel","url":"\/documentation\/mapboxcommon\/accuracylevel","type":"topic","title":"AccuracyLevel","navigatorTitle":[{"kind":"identifier","text":"AccuracyLevel"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AccuracyLevel","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationObserver":{"abstract":[{"type":"text","text":"Observer for getting updates from a LocationProvider."}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationObserver","url":"\/documentation\/mapboxcommon\/locationobserver","type":"topic","title":"LocationObserver","navigatorTitle":[{"text":"LocationObserver","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationObserver","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LocationOptions":{"navigatorTitle":[{"text":"LocationOptions","kind":"identifier"}],"kind":"symbol","title":"LocationOptions","role":"symbol","abstract":[{"text":"A struct to configure a ","type":"text"},{"type":"codeVoice","code":"LocationManager"}],"url":"\/documentation\/mapboxmaps\/locationoptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationOptions","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"LocationOptions","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PuckRenderingData":{"abstract":[{"type":"text","text":"Represents the interpolated data ready to render the user location puck."}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckRenderingData","url":"\/documentation\/mapboxmaps\/puckrenderingdata","type":"topic","title":"PuckRenderingData","navigatorTitle":[{"text":"PuckRenderingData","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PuckRenderingData"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PuckType":{"navigatorTitle":[{"text":"PuckType","kind":"identifier"}],"kind":"symbol","title":"PuckType","role":"symbol","abstract":[{"type":"text","text":"Represents the different types of pucks"}],"url":"\/documentation\/mapboxmaps\/pucktype","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckType","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PuckType","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/mapboxmaps","title":"MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeadingProvider":{"navigatorTitle":[{"text":"HeadingProvider","kind":"identifier"}],"kind":"symbol","title":"HeadingProvider","role":"symbol","abstract":[{"type":"text","text":"Provides heading data to drive the location puck."}],"url":"\/documentation\/mapboxmaps\/headingprovider","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingProvider","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HeadingProvider"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","abstract":[],"kind":"article","role":"collection","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationError":{"navigatorTitle":[{"kind":"identifier","text":"LocationError"}],"kind":"symbol","title":"LocationError","role":"symbol","abstract":[{"type":"text","text":"Error code with brief explanation."}],"url":"\/documentation\/mapboxcommon\/locationerror","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationError","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationError","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Location":{"abstract":[{"text":"Location information.","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location","url":"\/documentation\/mapboxcommon\/location","type":"topic","title":"Location","navigatorTitle":[{"text":"Location","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Location"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PuckBearing":{"navigatorTitle":[{"kind":"identifier","text":"PuckBearing"}],"kind":"symbol","title":"PuckBearing","role":"symbol","abstract":[{"text":"Controls how the puck is oriented","type":"text"}],"url":"\/documentation\/mapboxmaps\/puckbearing","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckBearing","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PuckBearing","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/title","value":"MBXPermissionStatus","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/fragments","value":[{"text":"MBXPermissionStatus","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/navigatorTitle","value":[{"kind":"identifier","text":"MBXPermissionStatus"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1IntervalSettings\/title","value":"MBXIntervalSettings","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1IntervalSettings\/fragments","value":[{"kind":"identifier","text":"MBXIntervalSettings"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1IntervalSettings\/navigatorTitle","value":[{"text":"MBXIntervalSettings","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Coordinate2D\/title","value":"MBXCoordinate2D","op":"replace"},{"value":[{"kind":"identifier","text":"MBXCoordinate2D"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Coordinate2D\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Coordinate2D\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBXCoordinate2D"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProviderRequest\/title","op":"replace","value":"MBXLocationProviderRequest"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProviderRequest\/fragments","value":[{"text":"MBXLocationProviderRequest","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProviderRequest\/navigatorTitle","value":[{"kind":"identifier","text":"MBXLocationProviderRequest"}]},{"value":"MBXLocationServiceFactory","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceFactory\/title"},{"value":[{"kind":"identifier","text":"MBXLocationServiceFactory"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceFactory\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceFactory\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBXLocationServiceFactory"}]},{"value":"MBXLocationExtraKeys","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationExtraKeys\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationExtraKeys\/fragments","value":[{"text":"MBXLocationExtraKeys","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationExtraKeys\/navigatorTitle","op":"replace","value":[{"text":"MBXLocationExtraKeys","kind":"identifier"}]},{"value":"MBXLocationServiceObserver","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver\/title"},{"value":[{"kind":"identifier","text":"MBXLocationServiceObserver"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver\/fragments"},{"op":"replace","value":[{"text":"MBXLocationServiceObserver","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/title","value":"MBXLocationErrorCode","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/fragments","op":"replace","value":[{"text":"MBXLocationErrorCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/navigatorTitle","value":[{"kind":"identifier","text":"MBXLocationErrorCode"}]},{"op":"replace","value":"MBXAccuracyAuthorization","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization\/fragments","value":[{"kind":"identifier","text":"MBXAccuracyAuthorization"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization\/navigatorTitle","value":[{"kind":"identifier","text":"MBXAccuracyAuthorization"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/title","value":"MBXLocationProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/fragments","value":[{"kind":"identifier","text":"MBXLocationProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/navigatorTitle","value":[{"text":"MBXLocationProvider","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1DeviceLocationProvider\/title","value":"MBXDeviceLocationProvider"},{"op":"replace","value":[{"text":"MBXDeviceLocationProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1DeviceLocationProvider\/fragments"},{"op":"replace","value":[{"text":"MBXDeviceLocationProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1DeviceLocationProvider\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel\/title","op":"replace","value":"MBXAccuracyLevel"},{"value":[{"kind":"identifier","text":"MBXAccuracyLevel"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel\/navigatorTitle","value":[{"text":"MBXAccuracyLevel","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/title","value":"MBXLocationObserver"},{"value":[{"kind":"identifier","text":"MBXLocationObserver"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/fragments","op":"replace"},{"value":[{"text":"MBXLocationObserver","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/navigatorTitle","op":"replace"},{"value":"MBXLocationError","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationError\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationError\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXLocationError"}]},{"value":[{"text":"MBXLocationError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationError\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/title","value":"MBXLocation","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/fragments","value":[{"text":"MBXLocation","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBXLocation"}]}]}]}