{"metadata":{"externalID":"s:10MapboxMaps15RasterDemSourceV","modules":[{"name":"MapboxMaps"}],"roleHeading":"Structure","role":"symbol","navigatorTitle":[{"text":"RasterDemSource","kind":"identifier"}],"symbolKind":"struct","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"RasterDemSource","kind":"identifier"}],"title":"RasterDemSource"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"abstract":[{"type":"text","text":"A RGB-encoded raster DEM source"}],"relationshipsSections":[{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapStyleContent","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Source","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDecodable","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleEncodable","doc:\/\/com.mapbox.MapboxMaps\/Se","doc:\/\/com.mapbox.MapboxMaps\/SE"]}],"variants":[{"paths":["\/documentation\/mapboxmaps\/rasterdemsource"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource"},"seeAlsoSections":[{"title":"Sources","anchor":"Sources","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Source","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceInfo","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSourceData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterArraySource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/VectorSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PromoteId","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Scheme","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Encoding","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatusChangedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatus","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileFunctionCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetSize"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"RasterDemSource","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"anchor":"overview","text":"Overview","level":2,"type":"heading"},{"type":"aside","name":"See Also","style":"note","content":[{"inlineContent":[{"text":"","type":"text"},{"type":"reference","identifier":"https:\/\/docs.mapbox.com\/mapbox-gl-js\/style-spec\/sources\/#raster_dem","isActive":true}],"type":"paragraph"}]}],"kind":"content"}],"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/init(from:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/init(id:)"],"title":"Initializers","anchor":"Initializers"},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/attribution","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/bounds","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/encoding","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/id","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/maxOverscaleFactorForParentTiles","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/maxzoom","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/minimumTileUpdateInterval","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/minzoom","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/prefetchZoomDelta","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/tileCacheBudget","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/tileNetworkRequestsDelay","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/tileRequestsDelay","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/tileSize","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/tiles","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/type","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/url","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/volatile"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/maxOverscaleFactorForParentTiles(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/maxzoom(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/minimumTileUpdateInterval(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/minzoom(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/prefetchZoomDelta(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/tileCacheBudget(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/tileNetworkRequestsDelay(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/tileRequestsDelay(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/tiles(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/url(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/volatile(_:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/Encodable-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/Source-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/StyleEncodable-Implementations"],"title":"Default Implementations","generated":true,"anchor":"Default-Implementations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterArraySource":{"role":"symbol","tags":[{"type":"spi","text":"SPI"}],"abstract":[{"text":"A raster array source","type":"text"}],"title":"RasterArraySource","navigatorTitle":[{"text":"RasterArraySource","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterArraySource","url":"\/documentation\/mapboxmaps\/rasterarraysource","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RasterArraySource"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterDemSource/minzoom":{"url":"\/documentation\/mapboxmaps\/rasterdemsource\/minzoom","type":"topic","title":"minzoom","kind":"symbol","abstract":[{"type":"text","text":"Minimum zoom level for which tiles are available, as in the TileJSON spec."},{"text":" ","type":"text"},{"type":"text","text":"Default value: 0."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"minzoom","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/minzoom","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileStatusChangedCallback":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatusChangedCallback","kind":"symbol","url":"\/documentation\/mapboxmaps\/customrastersourcetilestatuschangedcallback","title":"CustomRasterSourceTileStatusChangedCallback","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomRasterSourceTileStatusChangedCallback","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceTileStatusChangedCallback"}],"type":"topic","abstract":[{"text":"Callback for changing a CustomRasterSource tile status.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterDemSource/tileCacheBudget(_:)":{"kind":"symbol","title":"tileCacheBudget(_:)","url":"\/documentation\/mapboxmaps\/rasterdemsource\/tilecachebudget(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/tileCacheBudget(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"tileCacheBudget","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"TileCacheBudgetSize","preciseIdentifier":"s:10MapboxMaps19TileCacheBudgetSizeO"},{"text":") -> ","kind":"text"},{"text":"RasterDemSource","preciseIdentifier":"s:10MapboxMaps15RasterDemSourceV","kind":"typeIdentifier"}],"type":"topic","role":"symbol","abstract":[{"text":"This property defines a source-specific resource budget, either in tile units or in megabytes. Whenever the tile cache goes over the defined limit, the least recently used tile will be evicted from the in-memory cache. Note that the current implementation does not take into account resources allocated by the visible tiles.","type":"text"}]},"doc://com.mapbox.MapboxMaps/Se":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/Se","title":"Swift.Decodable","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ImageSource":{"title":"ImageSource","navigatorTitle":[{"text":"ImageSource","kind":"identifier"}],"abstract":[{"type":"text","text":"An image data source."}],"url":"\/documentation\/mapboxmaps\/imagesource","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageSource","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ImageSource"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapStyleContent":{"url":"\/documentation\/mapboxmaps\/mapstylecontent","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapStyleContent","kind":"identifier"}],"navigatorTitle":[{"text":"MapStyleContent","kind":"identifier"}],"title":"MapStyleContent","abstract":[{"type":"text","text":"A protocol used to create any type of  map style content, such as layers, sources, lighting and others."}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapStyleContent"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceType":{"url":"\/documentation\/mapboxmaps\/sourcetype","abstract":[{"type":"text","text":"Struct of supported Source Types"},{"type":"text","text":" "},{"text":"Docs : https:\/\/docs.mapbox.com\/mapbox-gl-js\/style-spec\/sources\/","type":"text"}],"title":"SourceType","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SourceType"}],"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SourceType","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceType"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/VectorSource":{"navigatorTitle":[{"text":"VectorSource","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/VectorSource","title":"VectorSource","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"VectorSource","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/vectorsource","type":"topic","abstract":[{"text":"A vector tile source.","type":"text"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterDemSource/volatile(_:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"volatile"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"RasterDemSource","preciseIdentifier":"s:10MapboxMaps15RasterDemSourceV","kind":"typeIdentifier"}],"title":"volatile(_:)","abstract":[{"type":"text","text":"A setting to determine whether a source’s tiles are cached locally."},{"type":"text","text":" "},{"text":"Default value: false.","type":"text"}],"url":"\/documentation\/mapboxmaps\/rasterdemsource\/volatile(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/volatile(_:)","type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterDemSource/tileNetworkRequestsDelay(_:)":{"abstract":[{"type":"text","text":"For the tiled sources, this property sets the tile network requests delay. The given delay comes in action only during an ongoing animation or gestures. It helps to avoid loading the transient tiles from the network and thus to avoid redundant network requests. Note that tile-network-requests-delay value is superseded with tile-requests-delay property value, if both are provided."},{"type":"text","text":" "},{"text":"Default value: 0.","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/tileNetworkRequestsDelay(_:)","url":"\/documentation\/mapboxmaps\/rasterdemsource\/tilenetworkrequestsdelay(_:)","title":"tileNetworkRequestsDelay(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tileNetworkRequestsDelay"},{"kind":"text","text":"("},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":") -> ","kind":"text"},{"text":"RasterDemSource","preciseIdentifier":"s:10MapboxMaps15RasterDemSourceV","kind":"typeIdentifier"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GeoJSONSourceData":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSourceData","url":"\/documentation\/mapboxmaps\/geojsonsourcedata","abstract":[{"type":"text","text":"Captures potential values of the "},{"type":"codeVoice","code":"data"},{"text":" property of a GeoJSONSource.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GeoJSONSourceData"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GeoJSONSourceData","kind":"identifier"}],"kind":"symbol","title":"GeoJSONSourceData"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterDemSource/type":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/type","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SourceType","preciseIdentifier":"s:10MapboxMaps10SourceTypeV","kind":"typeIdentifier"}],"role":"symbol","abstract":[],"url":"\/documentation\/mapboxmaps\/rasterdemsource\/type","title":"type","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Sources":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources","title":"Sources","kind":"article","url":"\/documentation\/mapboxmaps\/sources","type":"topic","abstract":[],"role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomGeometrySource":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySource","url":"\/documentation\/mapboxmaps\/customgeometrysource","kind":"symbol","title":"CustomGeometrySource","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomGeometrySource","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CustomGeometrySource"}],"abstract":[{"text":"Describes a Custom Geometry Source to be used in the style","type":"text"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GeoJSONSource":{"abstract":[{"type":"text","text":"A GeoJSON data source."}],"kind":"symbol","navigatorTitle":[{"text":"GeoJSONSource","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSource","url":"\/documentation\/mapboxmaps\/geojsonsource","type":"topic","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GeoJSONSource"}],"title":"GeoJSONSource"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Scheme":{"abstract":[{"text":"Influences the y direction of the tile coordinates. The global-mercator (aka Spherical Mercator) profile is assumed.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Scheme","title":"Scheme","kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Scheme","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Scheme"}],"type":"topic","url":"\/documentation\/mapboxmaps\/scheme"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PromoteId":{"kind":"symbol","abstract":[],"navigatorTitle":[{"text":"PromoteId","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PromoteId","type":"topic","url":"\/documentation\/mapboxmaps\/promoteid","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PromoteId","kind":"identifier"}],"title":"PromoteId"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterDemSource/tileRequestsDelay":{"abstract":[{"type":"text","text":"For the tiled sources, this property sets the tile requests delay. The given delay comes in action only during an ongoing animation or gestures. It helps to avoid loading, parsing and rendering of the transient tiles and thus to improve the rendering performance, especially on low-end devices."},{"type":"text","text":" "},{"text":"Default value: 0.","type":"text"}],"type":"topic","title":"tileRequestsDelay","url":"\/documentation\/mapboxmaps\/rasterdemsource\/tilerequestsdelay","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tileRequestsDelay"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"text":"?","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/tileRequestsDelay"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterDemSource/bounds":{"title":"bounds","kind":"symbol","url":"\/documentation\/mapboxmaps\/rasterdemsource\/bounds","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/bounds","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bounds","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":"]?","kind":"text"}],"type":"topic","role":"symbol","abstract":[{"text":"An array containing the longitude and latitude of the southwest and northeast corners of the source’s bounding box in the following order: ","type":"text"},{"code":"[sw.lng, sw.lat, ne.lng, ne.lat]","type":"codeVoice"},{"text":". When this property is included in a source, no tiles outside of the given bounds are requested by Mapbox GL.","type":"text"},{"type":"text","text":" "},{"text":"Default value: [-180,-85.051129,180,85.051129].","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSource":{"abstract":[{"text":"Describes a Custom Raster Source to be used in the style.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"CustomRasterSource","kind":"identifier"}],"tags":[{"text":"SPI","type":"spi"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSource","url":"\/documentation\/mapboxmaps\/customrastersource","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"CustomRasterSource","kind":"identifier"}],"title":"CustomRasterSource"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterDemSource/StyleEncodable-Implementations":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/StyleEncodable-Implementations","url":"\/documentation\/mapboxmaps\/rasterdemsource\/styleencodable-implementations","kind":"article","role":"collectionGroup","abstract":[],"title":"StyleEncodable Implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterDemSource/id":{"title":"id","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/id","abstract":[],"role":"symbol","url":"\/documentation\/mapboxmaps\/rasterdemsource\/id","type":"topic","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterDemSource/tileSize":{"abstract":[{"type":"text","text":"The minimum visual size to display tiles for this layer. Only configurable for raster layers."},{"type":"text","text":" "},{"type":"text","text":"Default value: 512. The unit of tileSize is in pixels."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/tileSize","url":"\/documentation\/mapboxmaps\/rasterdemsource\/tilesize","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"tileSize","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"tileSize","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudgetSize":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetSize","url":"\/documentation\/mapboxmaps\/tilecachebudgetsize","kind":"symbol","title":"TileCacheBudgetSize","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TileCacheBudgetSize"}],"navigatorTitle":[{"text":"TileCacheBudgetSize","kind":"identifier"}],"abstract":[{"text":"Defines a TileCacheBudgetSize, which can be set as either a megabyte or tile count limit.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Whenever tile cache goes over the defined limit"},{"text":" ","type":"text"},{"text":"the least recently used tile will be evicted from the in-memory cache","type":"text"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterDemSource/maxOverscaleFactorForParentTiles(_:)":{"role":"symbol","abstract":[{"type":"text","text":"When a set of tiles for a current zoom level is being rendered and some of the ideal tiles that cover the screen are not yet loaded, parent tile could be used instead. This might introduce unwanted rendering side-effects, especially for raster tiles that are overscaled multiple times. This property sets the maximum limit for how much a parent tile can be overscaled."}],"url":"\/documentation\/mapboxmaps\/rasterdemsource\/maxoverscalefactorforparenttiles(_:)","title":"maxOverscaleFactorForParentTiles(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxOverscaleFactorForParentTiles","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps15RasterDemSourceV","text":"RasterDemSource","kind":"typeIdentifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/maxOverscaleFactorForParentTiles(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterDemSource/volatile":{"title":"volatile","url":"\/documentation\/mapboxmaps\/rasterdemsource\/volatile","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"volatile","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/volatile","abstract":[{"type":"text","text":"A setting to determine whether a source’s tiles are cached locally."},{"text":" ","type":"text"},{"text":"Default value: false.","type":"text"}],"type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Source":{"abstract":[],"kind":"symbol","navigatorTitle":[{"text":"Source","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Source","url":"\/documentation\/mapboxmaps\/source","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"Source","kind":"identifier"}],"title":"Source"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article","title":"MapboxMaps Documentation","abstract":[],"url":"\/documentation\/overview","role":"collection","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterDemSource/tileRequestsDelay(_:)":{"abstract":[{"type":"text","text":"For the tiled sources, this property sets the tile requests delay. The given delay comes in action only during an ongoing animation or gestures. It helps to avoid loading, parsing and rendering of the transient tiles and thus to improve the rendering performance, especially on low-end devices."},{"text":" ","type":"text"},{"type":"text","text":"Default value: 0."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/tileRequestsDelay(_:)","type":"topic","kind":"symbol","title":"tileRequestsDelay(_:)","url":"\/documentation\/mapboxmaps\/rasterdemsource\/tilerequestsdelay(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tileRequestsDelay"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"RasterDemSource","preciseIdentifier":"s:10MapboxMaps15RasterDemSourceV"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterDemSource/prefetchZoomDelta":{"url":"\/documentation\/mapboxmaps\/rasterdemsource\/prefetchzoomdelta","abstract":[{"type":"text","text":"When loading a map, if PrefetchZoomDelta is set to any number greater than 0, the map will first request a tile at zoom level lower than zoom - delta, but so that the zoom level is multiple of delta, in an attempt to display a full map at lower resolution as quick as possible. It will get clamped at the tile source minimum zoom."},{"type":"text","text":" "},{"type":"text","text":"Default value: 4."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"prefetchZoomDelta"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/prefetchZoomDelta","title":"prefetchZoomDelta"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceClient":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient","url":"\/documentation\/mapboxmaps\/customrastersourceclient","kind":"symbol","title":"CustomRasterSourceClient","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CustomRasterSourceClient"}],"navigatorTitle":[{"text":"CustomRasterSourceClient","kind":"identifier"}],"abstract":[],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterDemSource/encoding":{"abstract":[{"type":"text","text":"The encoding used by this source. Mapbox Terrain RGB is used by default"},{"type":"text","text":" "},{"text":"Default value: “mapbox”.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/encoding","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"encoding"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps8EncodingV","text":"Encoding","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/rasterdemsource\/encoding","title":"encoding"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileFunctionCallback":{"abstract":[{"text":"Callback to do various operations for tile.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"For example, fetching a tile or cancelling a tile request."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TileFunctionCallback"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileFunctionCallback","url":"\/documentation\/mapboxmaps\/tilefunctioncallback","type":"topic","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileFunctionCallback","kind":"identifier"}],"title":"TileFunctionCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterDemSource/minimumTileUpdateInterval":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/minimumTileUpdateInterval","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimumTileUpdateInterval"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":"?","kind":"text"}],"type":"topic","abstract":[{"type":"text","text":"Minimum tile update interval in seconds, which is used to throttle the tile update network requests. If the given source supports loading tiles from a server, sets the minimum tile update interval. Update network requests that are more frequent than the minimum tile update interval are suppressed."},{"type":"text","text":" "},{"text":"Default value: 0.","type":"text"}],"title":"minimumTileUpdateInterval","url":"\/documentation\/mapboxmaps\/rasterdemsource\/minimumtileupdateinterval","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceClientType":{"kind":"symbol","abstract":[],"navigatorTitle":[{"text":"CustomRasterSourceClientType","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType","type":"topic","url":"\/documentation\/mapboxmaps\/customrastersourceclienttype","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomRasterSourceClientType","kind":"identifier"}],"title":"CustomRasterSourceClientType"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterDemSource/tileCacheBudget":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/tileCacheBudget","url":"\/documentation\/mapboxmaps\/rasterdemsource\/tilecachebudget","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"tileCacheBudget","kind":"identifier"},{"kind":"text","text":": "},{"text":"TileCacheBudgetSize","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps19TileCacheBudgetSizeO"},{"text":"?","kind":"text"}],"abstract":[{"text":"This property defines a source-specific resource budget, either in tile units or in megabytes. Whenever the tile cache goes over the defined limit, the least recently used tile will be evicted from the in-memory cache. Note that the current implementation does not take into account resources allocated by the visible tiles.","type":"text"}],"role":"symbol","title":"tileCacheBudget"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterDemSource/url":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/url","kind":"symbol","type":"topic","abstract":[{"text":"A URL to a TileJSON resource. Supported protocols are ","type":"text"},{"type":"codeVoice","code":"http:"},{"text":", ","type":"text"},{"type":"codeVoice","code":"https:"},{"type":"text","text":", and "},{"code":"mapbox:\/\/<Tileset ID>","type":"codeVoice"},{"text":". Required if ","type":"text"},{"code":"tiles","type":"codeVoice"},{"type":"text","text":" is not provided."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"title":"url","role":"symbol","url":"\/documentation\/mapboxmaps\/rasterdemsource\/url"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileStatus":{"abstract":[{"type":"text","text":"CustomRasterSource tile status."}],"kind":"symbol","navigatorTitle":[{"text":"CustomRasterSourceTileStatus","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatus","url":"\/documentation\/mapboxmaps\/customrastersourcetilestatus","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomRasterSourceTileStatus","kind":"identifier"}],"title":"CustomRasterSourceTileStatus"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterDemSource/minimumTileUpdateInterval(_:)":{"abstract":[{"text":"Minimum tile update interval in seconds, which is used to throttle the tile update network requests. If the given source supports loading tiles from a server, sets the minimum tile update interval. Update network requests that are more frequent than the minimum tile update interval are suppressed.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Default value: 0."}],"title":"minimumTileUpdateInterval(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minimumTileUpdateInterval","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:10MapboxMaps15RasterDemSourceV","text":"RasterDemSource","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/minimumTileUpdateInterval(_:)","url":"\/documentation\/mapboxmaps\/rasterdemsource\/minimumtileupdateinterval(_:)"},"https://docs.mapbox.com/mapbox-gl-js/style-spec/sources/#raster_dem":{"url":"https:\/\/docs.mapbox.com\/mapbox-gl-js\/style-spec\/sources\/#raster_dem","type":"link","identifier":"https:\/\/docs.mapbox.com\/mapbox-gl-js\/style-spec\/sources\/#raster_dem","title":"Mapbox Style Specification","titleInlineContent":[{"text":"Mapbox Style Specification","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterDemSource/tiles":{"title":"tiles","role":"symbol","url":"\/documentation\/mapboxmaps\/rasterdemsource\/tiles","type":"topic","abstract":[{"text":"An array of one or more tile source URLs, as in the TileJSON spec. Required if ","type":"text"},{"type":"codeVoice","code":"url"},{"type":"text","text":" is not provided."}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/tiles","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tiles"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"]?","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterDemSource/init(id:)":{"title":"init(id:)","role":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/init(id:)","kind":"symbol","url":"\/documentation\/mapboxmaps\/rasterdemsource\/init(id:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}]},"doc://com.mapbox.MapboxMaps/SE":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SE","title":"Swift.Encodable","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterDemSource":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource","url":"\/documentation\/mapboxmaps\/rasterdemsource","kind":"symbol","title":"RasterDemSource","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"RasterDemSource","kind":"identifier"}],"navigatorTitle":[{"text":"RasterDemSource","kind":"identifier"}],"abstract":[{"type":"text","text":"A RGB-encoded raster DEM source"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterDemSource/url(_:)":{"url":"\/documentation\/mapboxmaps\/rasterdemsource\/url(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/url(_:)","type":"topic","kind":"symbol","title":"url(_:)","abstract":[{"type":"text","text":"A URL to a TileJSON resource. Supported protocols are "},{"type":"codeVoice","code":"http:"},{"type":"text","text":", "},{"code":"https:","type":"codeVoice"},{"text":", and ","type":"text"},{"type":"codeVoice","code":"mapbox:\/\/<Tileset ID>"},{"type":"text","text":". Required if "},{"type":"codeVoice","code":"tiles"},{"text":" is not provided.","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"url","kind":"identifier"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:10MapboxMaps15RasterDemSourceV","text":"RasterDemSource","kind":"typeIdentifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceInfo":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceInfo","kind":"symbol","url":"\/documentation\/mapboxmaps\/sourceinfo","title":"SourceInfo","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"SourceInfo","kind":"identifier"}],"navigatorTitle":[{"text":"SourceInfo","kind":"identifier"}],"type":"topic","abstract":[{"text":"Information about a Source","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterDemSource/maxOverscaleFactorForParentTiles":{"abstract":[{"type":"text","text":"When a set of tiles for a current zoom level is being rendered and some of the ideal tiles that cover the screen are not yet loaded, parent tile could be used instead. This might introduce unwanted rendering side-effects, especially for raster tiles that are overscaled multiple times. This property sets the maximum limit for how much a parent tile can be overscaled."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/maxOverscaleFactorForParentTiles","type":"topic","kind":"symbol","title":"maxOverscaleFactorForParentTiles","url":"\/documentation\/mapboxmaps\/rasterdemsource\/maxoverscalefactorforparenttiles","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxOverscaleFactorForParentTiles","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":"?","kind":"text"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterDemSource/maxzoom(_:)":{"url":"\/documentation\/mapboxmaps\/rasterdemsource\/maxzoom(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/maxzoom(_:)","kind":"symbol","type":"topic","title":"maxzoom(_:)","abstract":[{"text":"Maximum zoom level for which tiles are available, as in the TileJSON spec. Data from tiles at the maxzoom are used when displaying the map at higher zoom levels.","type":"text"},{"text":" ","type":"text"},{"text":"Default value: 22.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxzoom"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps15RasterDemSourceV","text":"RasterDemSource"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomGeometrySourceOptions":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomGeometrySourceOptions"}],"navigatorTitle":[{"kind":"identifier","text":"CustomGeometrySourceOptions"}],"kind":"symbol","abstract":[{"text":"Options for custom geometry source.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions","role":"symbol","title":"CustomGeometrySourceOptions","type":"topic","url":"\/documentation\/mapboxmaps\/customgeometrysourceoptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterDemSource/tileNetworkRequestsDelay":{"abstract":[{"text":"For the tiled sources, this property sets the tile network requests delay. The given delay comes in action only during an ongoing animation or gestures. It helps to avoid loading the transient tiles from the network and thus to avoid redundant network requests. Note that tile-network-requests-delay value is superseded with tile-requests-delay property value, if both are provided.","type":"text"},{"text":" ","type":"text"},{"text":"Default value: 0.","type":"text"}],"type":"topic","url":"\/documentation\/mapboxmaps\/rasterdemsource\/tilenetworkrequestsdelay","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tileNetworkRequestsDelay"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/tileNetworkRequestsDelay","kind":"symbol","title":"tileNetworkRequestsDelay","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Encoding":{"navigatorTitle":[{"text":"Encoding","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"Encoding","kind":"identifier"}],"abstract":[{"text":"The encoding used by this source. Mapbox Terrain RGB is used by default","type":"text"}],"url":"\/documentation\/mapboxmaps\/encoding","title":"Encoding","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Encoding","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterSource":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterSource","url":"\/documentation\/mapboxmaps\/rastersource","kind":"symbol","title":"RasterSource","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RasterSource","kind":"identifier"}],"navigatorTitle":[{"text":"RasterSource","kind":"identifier"}],"abstract":[{"type":"text","text":"A raster tile source."}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceOptions":{"abstract":[{"text":"Options for custom raster source.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"CustomRasterSourceOptions","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions","url":"\/documentation\/mapboxmaps\/customrastersourceoptions","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CustomRasterSourceOptions","kind":"identifier"}],"title":"CustomRasterSourceOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterDemSource/init(from:)":{"type":"topic","url":"\/documentation\/mapboxmaps\/rasterdemsource\/init(from:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"kind":"symbol","title":"init(from:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/init(from:)","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterDemSource/Source-Implementations":{"type":"topic","url":"\/documentation\/mapboxmaps\/rasterdemsource\/source-implementations","role":"collectionGroup","kind":"article","title":"Source Implementations","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/Source-Implementations","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterDemSource/attribution":{"abstract":[{"text":"Contains an attribution to be displayed when the map is shown to a user.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"attribution","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"kind":"symbol","title":"attribution","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/attribution","role":"symbol","url":"\/documentation\/mapboxmaps\/rasterdemsource\/attribution","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterDemSource/Encodable-Implementations":{"type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/Encodable-Implementations","kind":"article","role":"collectionGroup","title":"Encodable Implementations","url":"\/documentation\/mapboxmaps\/rasterdemsource\/encodable-implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterDemSource/maxzoom":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/maxzoom","abstract":[{"type":"text","text":"Maximum zoom level for which tiles are available, as in the TileJSON spec. Data from tiles at the maxzoom are used when displaying the map at higher zoom levels."},{"text":" ","type":"text"},{"type":"text","text":"Default value: 22."}],"kind":"symbol","title":"maxzoom","url":"\/documentation\/mapboxmaps\/rasterdemsource\/maxzoom","role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"maxzoom","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterDemSource/tiles(_:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/tiles(_:)","url":"\/documentation\/mapboxmaps\/rasterdemsource\/tiles(_:)","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tiles"},{"text":"([","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]) -> ","kind":"text"},{"text":"RasterDemSource","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps15RasterDemSourceV"}],"abstract":[{"type":"text","text":"An array of one or more tile source URLs, as in the TileJSON spec. Required if "},{"type":"codeVoice","code":"url"},{"text":" is not provided.","type":"text"}],"role":"symbol","title":"tiles(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleDecodable":{"role":"symbol","abstract":[{"type":"text","text":"A protocol describing a style-related entity that can be decoded."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StyleDecodable","kind":"identifier"}],"navigatorTitle":[{"text":"StyleDecodable","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/styledecodable","title":"StyleDecodable","type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDecodable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterDemSource/prefetchZoomDelta(_:)":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/prefetchZoomDelta(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prefetchZoomDelta"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps15RasterDemSourceV","kind":"typeIdentifier","text":"RasterDemSource"}],"url":"\/documentation\/mapboxmaps\/rasterdemsource\/prefetchzoomdelta(_:)","type":"topic","abstract":[{"type":"text","text":"When loading a map, if PrefetchZoomDelta is set to any number greater than 0, the map will first request a tile at zoom level lower than zoom - delta, but so that the zoom level is multiple of delta, in an attempt to display a full map at lower resolution as quick as possible. It will get clamped at the tile source minimum zoom."},{"type":"text","text":" "},{"text":"Default value: 4.","type":"text"}],"title":"prefetchZoomDelta(_:)","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileRenderer":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer","url":"\/documentation\/mapboxmaps\/customrastersourcetilerenderer","kind":"symbol","title":"CustomRasterSourceTileRenderer","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomRasterSourceTileRenderer","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceTileRenderer"}],"abstract":[{"text":"Interface for the direct rendering into the custom raster tiles.","type":"text"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterDemSource/minzoom(_:)":{"kind":"symbol","abstract":[{"type":"text","text":"Minimum zoom level for which tiles are available, as in the TileJSON spec."},{"text":" ","type":"text"},{"type":"text","text":"Default value: 0."}],"type":"topic","title":"minzoom(_:)","url":"\/documentation\/mapboxmaps\/rasterdemsource\/minzoom(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource\/minzoom(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"minzoom"},{"kind":"text","text":"("},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":") -> ","kind":"text"},{"text":"RasterDemSource","preciseIdentifier":"s:10MapboxMaps15RasterDemSourceV","kind":"typeIdentifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleEncodable":{"kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StyleEncodable","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol describing a style-related entity that can be encoded."}],"url":"\/documentation\/mapboxmaps\/styleencodable","type":"topic","title":"StyleEncodable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleEncodable","navigatorTitle":[{"text":"StyleEncodable","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","title":"MapboxMaps","type":"topic","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileData":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileData","kind":"symbol","url":"\/documentation\/mapboxmaps\/customrastersourcetiledata","title":"CustomRasterSourceTileData","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomRasterSourceTileData","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceTileData"}],"type":"topic","abstract":[{"type":"text","text":"Data for a specific CustomRasterSource tile."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatusChangedCallback\/title","value":"MBMCustomRasterSourceTileStatusChangedCallback"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatusChangedCallback\/fragments","value":[{"text":"MBMCustomRasterSourceTileStatusChangedCallback","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatusChangedCallback\/navigatorTitle","value":[{"text":"MBMCustomRasterSourceTileStatusChangedCallback","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient\/title","value":"MBMCustomRasterSourceClient"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMCustomRasterSourceClient"}]},{"value":[{"text":"MBMCustomRasterSourceClient","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient\/navigatorTitle","op":"replace"},{"op":"replace","value":"MBMTileFunctionCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileFunctionCallback\/title"},{"op":"replace","value":[{"text":"MBMTileFunctionCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileFunctionCallback\/fragments"},{"value":[{"text":"MBMTileFunctionCallback","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileFunctionCallback\/navigatorTitle"},{"value":"MBMCustomRasterSourceClientType","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBMCustomRasterSourceClientType"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType\/navigatorTitle","value":[{"kind":"identifier","text":"MBMCustomRasterSourceClientType"}],"op":"replace"},{"value":"MBMCustomRasterSourceTileStatus","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatus\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileStatus"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatus\/fragments"},{"value":[{"text":"MBMCustomRasterSourceTileStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatus\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions\/title","value":"MBMCustomGeometrySourceOptions"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMCustomGeometrySourceOptions"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMCustomGeometrySourceOptions"}]},{"op":"replace","value":"MBMCustomRasterSourceOptions","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/title"},{"value":[{"text":"MBMCustomRasterSourceOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/navigatorTitle","value":[{"text":"MBMCustomRasterSourceOptions","kind":"identifier"}]},{"op":"replace","value":"MBMCustomRasterSourceTileRenderer","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer\/fragments","value":[{"text":"MBMCustomRasterSourceTileRenderer","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileRenderer"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileData\/title","value":"MBMCustomRasterSourceTileData"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileData\/fragments","op":"replace","value":[{"text":"MBMCustomRasterSourceTileData","kind":"identifier"}]},{"value":[{"text":"MBMCustomRasterSourceTileData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileData\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}