{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"RenderFrameStarted","kind":"identifier"}]}]},{"content":[{"text":"Overview","anchor":"overview","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"Note: The "},{"type":"codeVoice","code":"map"},{"type":"text","text":" will emit the event asynchronously so the user-provided callback"},{"type":"text","text":" "},{"type":"text","text":"does not stall the rendering pipeline."}],"type":"paragraph"}],"kind":"content"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraChanged","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapIdle","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceAdded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceRemoved","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageMissing","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnused","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinished","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequest","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GenericEvent"],"anchor":"Events","title":"Events"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameStarted"},"variants":[{"paths":["\/documentation\/mapboxmaps\/renderframestarted"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/renderframestarted"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"RenderFrameStarted"}],"modules":[{"name":"MapboxMaps"}],"symbolKind":"class","roleHeading":"Class","title":"RenderFrameStarted","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"RenderFrameStarted","kind":"identifier"}],"externalID":"c:objc(cs)MBMRenderFrameStarted"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events"]]},"abstract":[{"type":"text","text":"The "},{"code":"map","type":"codeVoice"},{"type":"text","text":" started rendering a frame."}],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"title":"Inherits From"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH"],"kind":"relationships"}],"topicSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameStarted\/init(timestamp:)"],"anchor":"Initializers","title":"Initializers","generated":true},{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameStarted\/timestamp"]}],"references":{"doc://com.mapbox.MapboxMaps/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceAdded":{"type":"topic","url":"\/documentation\/mapboxmaps\/sourceadded","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SourceAdded","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SourceAdded"}],"title":"SourceAdded","abstract":[{"type":"text","text":"The source has been added with "},{"code":"addStyleSource","type":"codeVoice"},{"text":" method.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceAdded"},"doc://com.mapbox.MapboxMaps/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderFrameStarted":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameStarted","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"map"},{"type":"text","text":" started rendering a frame."}],"type":"topic","url":"\/documentation\/mapboxmaps\/renderframestarted","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"RenderFrameStarted","kind":"identifier"}],"navigatorTitle":[{"text":"RenderFrameStarted","kind":"identifier"}],"title":"RenderFrameStarted","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceRemoved":{"type":"topic","navigatorTitle":[{"text":"SourceRemoved","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SourceRemoved","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/sourceremoved","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceRemoved","abstract":[{"text":"The source has been removed with ","type":"text"},{"type":"codeVoice","code":"removeStyleSource"},{"text":" method.","type":"text"}],"title":"SourceRemoved"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraChanged":{"title":"CameraChanged","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraChanged","type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/camerachanged","abstract":[{"text":"This event is emitted whenever the visible viewport changes its size","type":"text"},{"type":"text","text":" "},{"text":"due to the invocation of the ","type":"text"},{"type":"codeVoice","code":"setSize"},{"text":" and ","type":"text"},{"code":"setBounds","type":"codeVoice"},{"type":"text","text":" methods or when"},{"type":"text","text":" "},{"text":"the camera is modified by calling camera methods. The event is emitted","type":"text"},{"type":"text","text":" "},{"text":"synchronously so that an updated camera state can be read immediately.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CameraChanged"}],"navigatorTitle":[{"text":"CameraChanged","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoadingError":{"title":"MapLoadingError","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingError","abstract":[{"type":"text","text":"Describes an error that has occurred while loading the "},{"code":"map","type":"codeVoice"},{"type":"text","text":". The "},{"code":"type","type":"codeVoice"},{"type":"text","text":" property"},{"type":"text","text":" "},{"type":"text","text":"defines what resource could not be loaded, and the "},{"code":"message","type":"codeVoice"},{"text":" property will contain","type":"text"},{"type":"text","text":" "},{"type":"text","text":"a descriptive error message."}],"role":"symbol","url":"\/documentation\/mapboxmaps\/maploadingerror","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapLoadingError"}],"navigatorTitle":[{"text":"MapLoadingError","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleImageMissing":{"type":"topic","navigatorTitle":[{"text":"StyleImageMissing","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/styleimagemissing","kind":"symbol","title":"StyleImageMissing","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"StyleImageMissing","kind":"identifier"}],"abstract":[{"text":"A style needs an image that is missing from the sprite sheet. This event is","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"emitted when the "},{"code":"map","type":"codeVoice"},{"type":"text","text":" renders visible tiles, and one of the required images"},{"type":"text","text":" "},{"type":"text","text":"is missing in the sprite sheet. The event observer has to provide the missing"},{"type":"text","text":" "},{"type":"text","text":"image by calling the "},{"type":"codeVoice","code":"addStyleImage"},{"type":"text","text":" method."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageMissing"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article","title":"MapboxMaps Documentation","abstract":[],"url":"\/documentation\/overview","role":"collection","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoaded":{"navigatorTitle":[{"kind":"identifier","text":"MapLoaded"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoaded","type":"topic","abstract":[{"type":"text","text":"The style has been fully loaded, and the "},{"type":"codeVoice","code":"map"},{"type":"text","text":" has rendered all visible tiles."},{"type":"text","text":" "},{"type":"text","text":"The event will be emitted only once for the current style. If it is required to"},{"type":"text","text":" "},{"type":"text","text":"observe an event where all required resources are loaded or rendered, please"},{"type":"text","text":" "},{"type":"text","text":"check the following events: "},{"code":"MapIdle","type":"codeVoice"},{"text":", ","type":"text"},{"type":"codeVoice","code":"StyleDataLoaded"},{"text":", and ","type":"text"},{"code":"RenderFrameFinished","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/maploaded","title":"MapLoaded","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapLoaded"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleLoaded":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"StyleLoaded"}],"role":"symbol","title":"StyleLoaded","kind":"symbol","url":"\/documentation\/mapboxmaps\/styleloaded","abstract":[{"text":"The requested style has been fully loaded, including specified sprite, and sources’ metadata.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleLoaded","navigatorTitle":[{"text":"StyleLoaded","kind":"identifier"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderFrameStarted/init(timestamp:)":{"url":"\/documentation\/mapboxmaps\/renderframestarted\/init(timestamp:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameStarted\/init(timestamp:)","navigatorTitle":[{"kind":"identifier","text":"initWithTimestamp:"}],"title":"init(timestamp:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"timestamp"},{"text":": ","kind":"text"},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic","kind":"symbol","abstract":[]},"doc://com.mapbox.MapboxMaps/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleDataLoaded":{"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StyleDataLoaded","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"StyleDataLoaded"}],"role":"symbol","title":"StyleDataLoaded","url":"\/documentation\/mapboxmaps\/styledataloaded","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoaded","abstract":[{"type":"text","text":"The style data has been loaded. The event will be emitted once for each "},{"type":"codeVoice","code":"StyleDataLoadedType"},{"type":"text","text":" "},{"type":"text","text":"type during style loading. If a new style is set, events will be emitted again for the newly set style."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceDataLoaded":{"navigatorTitle":[{"kind":"identifier","text":"SourceDataLoaded"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoaded","type":"topic","kind":"symbol","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"SourceDataLoaded"},{"text":" event is emitted when source data is loaded.","type":"text"}],"title":"SourceDataLoaded","url":"\/documentation\/mapboxmaps\/sourcedataloaded","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SourceDataLoaded","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GenericEvent":{"abstract":[{"type":"text","text":"The generic event type."}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/genericevent","navigatorTitle":[{"text":"GenericEvent","kind":"identifier"}],"title":"GenericEvent","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GenericEvent","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GenericEvent","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResourceRequest":{"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"ResourceRequest"},{"text":" event allows the application to observe resource requests made by a ","type":"text"},{"type":"codeVoice","code":"map"},{"type":"text","text":" or "},{"code":"map snapshotter","type":"codeVoice"},{"text":" object.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ResourceRequest"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ResourceRequest","kind":"identifier"}],"type":"topic","title":"ResourceRequest","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequest","kind":"symbol","url":"\/documentation\/mapboxmaps\/resourcerequest","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderFrameFinished":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"RenderFrameFinished","kind":"identifier"}],"role":"symbol","title":"RenderFrameFinished","kind":"symbol","url":"\/documentation\/mapboxmaps\/renderframefinished","abstract":[{"text":"The ","type":"text"},{"code":"map","type":"codeVoice"},{"type":"text","text":" finished rendering a frame."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinished","navigatorTitle":[{"kind":"identifier","text":"RenderFrameFinished"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderFrameStarted/timestamp":{"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/renderframestarted\/timestamp","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timestamp","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"}],"title":"timestamp","navigatorTitle":[{"text":"timestamp","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameStarted\/timestamp","abstract":[{"text":"The timestamp of an event when the ","type":"text"},{"type":"codeVoice","code":"map"},{"type":"text","text":" started rendering the frame."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleImageRemoveUnused":{"type":"topic","navigatorTitle":[{"text":"StyleImageRemoveUnused","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/styleimageremoveunused","kind":"symbol","title":"StyleImageRemoveUnused","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"StyleImageRemoveUnused"}],"abstract":[{"text":"An image requested by the ","type":"text"},{"code":"map","type":"codeVoice"},{"text":" through the ","type":"text"},{"type":"codeVoice","code":"StyleImageMissing"},{"type":"text","text":" event is no longer"},{"text":" ","type":"text"},{"type":"text","text":"needed and can be removed using the "},{"code":"removeStyleImage","type":"codeVoice"},{"text":" method. The application can","type":"text"},{"type":"text","text":" "},{"type":"text","text":"decide whether the image should be kept or removed."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnused"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapIdle":{"role":"symbol","kind":"symbol","url":"\/documentation\/mapboxmaps\/mapidle","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapIdle","type":"topic","title":"MapIdle","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"map"},{"type":"text","text":" has entered the idle state. The "},{"type":"codeVoice","code":"map"},{"type":"text","text":" is idle when there are no ongoing"},{"type":"text","text":" "},{"type":"text","text":"animations, transitions and the "},{"code":"map","type":"codeVoice"},{"text":" has rendered all requested non-volatile tiles","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"(e.g., live traffic tiles). The event will not be emitted if "},{"code":"setUserAnimationInProgress","type":"codeVoice"},{"type":"text","text":" "},{"type":"text","text":"and \/ or "},{"code":"setGestureInProgress","type":"codeVoice"},{"text":" is set to ","type":"text"},{"type":"codeVoice","code":"true"},{"text":".","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MapIdle"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapIdle"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","title":"MapboxMaps","type":"topic","role":"collection"},"doc://com.mapbox.MapboxMaps/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP"},"doc://com.mapbox.MapboxMaps/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"type":"topic","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","url":"\/documentation\/mapboxmaps\/events","title":"Map events","kind":"article","abstract":[{"type":"text","text":"The simplified diagram of the events emitted by the map is displayed below."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"MBMRenderFrameStarted","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBMRenderFrameStarted"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"MBMRenderFrameStarted","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameStarted\/timestamp"]},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameStarted\/init(timestamp:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"op":"replace","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"}],"path":"\/relationshipsSections"},{"value":[{"title":"Events","generated":true,"anchor":"Events","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraChanged","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapIdle","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceAdded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceRemoved","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageMissing","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnused","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinished","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequest","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GenericEvent"]}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"MBMRenderFrameStarted","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"MBMSourceAdded","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAdded\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBMSourceAdded"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAdded\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAdded\/navigatorTitle","value":[{"text":"MBMSourceAdded","kind":"identifier"}]},{"value":"MBMRenderFrameStarted","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameStarted\/title"},{"value":[{"kind":"identifier","text":"MBMRenderFrameStarted"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameStarted\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameStarted\/navigatorTitle","value":[{"text":"MBMRenderFrameStarted","kind":"identifier"}]},{"value":"MBMSourceRemoved","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceRemoved\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceRemoved\/fragments","value":[{"text":"MBMSourceRemoved","kind":"identifier"}]},{"value":[{"text":"MBMSourceRemoved","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceRemoved\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChanged\/title","value":"MBMCameraChanged"},{"value":[{"text":"MBMCameraChanged","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChanged\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChanged\/navigatorTitle","value":[{"text":"MBMCameraChanged","kind":"identifier"}]},{"value":"MBMMapLoadingError","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingError\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingError\/fragments","value":[{"text":"MBMMapLoadingError","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingError\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMMapLoadingError"}]},{"value":"MBMStyleImageMissing","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageMissing\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageMissing\/fragments","value":[{"kind":"identifier","text":"MBMStyleImageMissing"}]},{"value":[{"text":"MBMStyleImageMissing","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageMissing\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoaded\/title","op":"replace","value":"MBMMapLoaded"},{"op":"replace","value":[{"text":"MBMMapLoaded","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoaded\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoaded\/navigatorTitle","op":"replace","value":[{"text":"MBMMapLoaded","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoaded\/title","value":"MBMStyleLoaded","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoaded\/fragments","value":[{"kind":"identifier","text":"MBMStyleLoaded"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoaded\/navigatorTitle","value":[{"text":"MBMStyleLoaded","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameStarted~1init(timestamp:)\/title","value":"initWithTimestamp:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithTimestamp:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameStarted~1init(timestamp:)\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoaded\/title","value":"MBMStyleDataLoaded","op":"replace"},{"value":[{"text":"MBMStyleDataLoaded","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoaded\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoaded\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMStyleDataLoaded"}]},{"op":"replace","value":"MBMSourceDataLoaded","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoaded\/title"},{"value":[{"kind":"identifier","text":"MBMSourceDataLoaded"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoaded\/fragments"},{"value":[{"text":"MBMSourceDataLoaded","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoaded\/navigatorTitle"},{"value":"MBMGenericEvent","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEvent\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MBMGenericEvent"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEvent\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEvent\/navigatorTitle","value":[{"kind":"identifier","text":"MBMGenericEvent"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequest\/title","op":"replace","value":"MBMResourceRequest"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequest\/fragments","value":[{"text":"MBMResourceRequest","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"MBMResourceRequest","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequest\/navigatorTitle"},{"op":"replace","value":"MBMRenderFrameFinished","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinished\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinished\/fragments","value":[{"text":"MBMRenderFrameFinished","kind":"identifier"}],"op":"replace"},{"value":[{"text":"MBMRenderFrameFinished","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinished\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameStarted~1timestamp\/title","value":"timestamp"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameStarted~1timestamp\/fragments","value":[{"kind":"identifier","text":"timestamp"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnused\/title","value":"MBMStyleImageRemoveUnused"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnused\/fragments","value":[{"kind":"identifier","text":"MBMStyleImageRemoveUnused"}]},{"op":"replace","value":[{"text":"MBMStyleImageRemoveUnused","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnused\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdle\/title","value":"MBMMapIdle"},{"value":[{"kind":"identifier","text":"MBMMapIdle"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdle\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdle\/navigatorTitle","value":[{"kind":"identifier","text":"MBMMapIdle"}],"op":"replace"}]}]}