{"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/resourcerequest"]},{"paths":["\/documentation\/mapboxmaps\/resourcerequest"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","seeAlsoSections":[{"anchor":"Events","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraChanged","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapIdle","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceAdded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceRemoved","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageMissing","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnused","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameStarted","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinished","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GenericEvent"],"title":"Events"}],"topicSections":[{"generated":true,"title":"Initializers","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequest\/init(source:request:response:cancelled:timeInterval:)"],"anchor":"Initializers"},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequest\/cancelled","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequest\/request","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequest\/response","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequest\/source","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequest\/timeInterval"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ResourceRequest"},{"type":"text","text":" event allows the application to observe resource requests made by a "},{"type":"codeVoice","code":"map"},{"type":"text","text":" or "},{"type":"codeVoice","code":"map snapshotter"},{"type":"text","text":" object."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ResourceRequest","kind":"identifier"}]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"MapboxMaps"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ResourceRequest"}],"symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ResourceRequest"}],"roleHeading":"Class","externalID":"c:objc(cs)MBMResourceRequest","title":"ResourceRequest"},"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH"],"title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequest","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleImageMissing":{"navigatorTitle":[{"kind":"identifier","text":"StyleImageMissing"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"StyleImageMissing","kind":"identifier"}],"abstract":[{"type":"text","text":"A style needs an image that is missing from the sprite sheet. This event is"},{"text":" ","type":"text"},{"type":"text","text":"emitted when the "},{"type":"codeVoice","code":"map"},{"type":"text","text":" renders visible tiles, and one of the required images"},{"type":"text","text":" "},{"type":"text","text":"is missing in the sprite sheet. The event observer has to provide the missing"},{"type":"text","text":" "},{"type":"text","text":"image by calling the "},{"type":"codeVoice","code":"addStyleImage"},{"text":" method.","type":"text"}],"title":"StyleImageMissing","url":"\/documentation\/mapboxmaps\/styleimagemissing","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageMissing","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","role":"collection","url":"\/documentation\/mapboxmaps","kind":"symbol","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic"},"doc://com.mapbox.MapboxMaps/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject","title":"NSObject"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResourceRequest/request":{"type":"topic","url":"\/documentation\/mapboxmaps\/resourcerequest\/request","title":"request","kind":"symbol","navigatorTitle":[{"text":"request","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"request","kind":"identifier"},{"text":": ","kind":"text"},{"text":"RequestInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMRequestInfo"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequest\/request","abstract":[{"text":"The structure describes information about the resource request.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResourceRequest":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The "},{"code":"ResourceRequest","type":"codeVoice"},{"type":"text","text":" event allows the application to observe resource requests made by a "},{"code":"map","type":"codeVoice"},{"text":" or ","type":"text"},{"type":"codeVoice","code":"map snapshotter"},{"text":" object.","type":"text"}],"type":"topic","title":"ResourceRequest","url":"\/documentation\/mapboxmaps\/resourcerequest","navigatorTitle":[{"text":"ResourceRequest","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ResourceRequest","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequest"},"doc://com.mapbox.MapboxMaps/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResourceRequest/timeInterval":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"timeInterval","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EventTimeInterval","preciseIdentifier":"c:objc(cs)MBMEventTimeInterval"}],"navigatorTitle":[{"kind":"identifier","text":"timeInterval"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequest\/timeInterval","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/resourcerequest\/timeinterval","abstract":[{"type":"text","text":"The timestamps of the resource request event. The "},{"code":"timeInterval.begin","type":"codeVoice"},{"type":"text","text":" is when"},{"text":" ","type":"text"},{"type":"text","text":"the resource request is made, and the "},{"type":"codeVoice","code":"timeInterval.end"},{"type":"text","text":" is when the request is completed."}],"title":"timeInterval"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceRemoved":{"url":"\/documentation\/mapboxmaps\/sourceremoved","navigatorTitle":[{"kind":"identifier","text":"SourceRemoved"}],"abstract":[{"type":"text","text":"The source has been removed with "},{"type":"codeVoice","code":"removeStyleSource"},{"type":"text","text":" method."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SourceRemoved","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceRemoved","type":"topic","title":"SourceRemoved","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoadingError":{"url":"\/documentation\/mapboxmaps\/maploadingerror","navigatorTitle":[{"kind":"identifier","text":"MapLoadingError"}],"abstract":[{"text":"Describes an error that has occurred while loading the ","type":"text"},{"type":"codeVoice","code":"map"},{"text":". The ","type":"text"},{"type":"codeVoice","code":"type"},{"text":" property","type":"text"},{"type":"text","text":" "},{"type":"text","text":"defines what resource could not be loaded, and the "},{"type":"codeVoice","code":"message"},{"type":"text","text":" property will contain"},{"text":" ","type":"text"},{"type":"text","text":"a descriptive error message."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapLoadingError"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingError","type":"topic","title":"MapLoadingError","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraChanged":{"navigatorTitle":[{"kind":"identifier","text":"CameraChanged"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"CameraChanged","kind":"identifier"}],"abstract":[{"type":"text","text":"This event is emitted whenever the visible viewport changes its size"},{"text":" ","type":"text"},{"type":"text","text":"due to the invocation of the "},{"code":"setSize","type":"codeVoice"},{"type":"text","text":" and "},{"type":"codeVoice","code":"setBounds"},{"type":"text","text":" methods or when"},{"type":"text","text":" "},{"type":"text","text":"the camera is modified by calling camera methods. The event is emitted"},{"text":" ","type":"text"},{"text":"synchronously so that an updated camera state can be read immediately.","type":"text"}],"title":"CameraChanged","url":"\/documentation\/mapboxmaps\/camerachanged","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraChanged","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapIdle":{"kind":"symbol","title":"MapIdle","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapIdle","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MapIdle","kind":"identifier"}],"navigatorTitle":[{"text":"MapIdle","kind":"identifier"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"map"},{"text":" has entered the idle state. The ","type":"text"},{"type":"codeVoice","code":"map"},{"type":"text","text":" is idle when there are no ongoing"},{"type":"text","text":" "},{"text":"animations, transitions and the ","type":"text"},{"code":"map","type":"codeVoice"},{"type":"text","text":" has rendered all requested non-volatile tiles"},{"type":"text","text":" "},{"type":"text","text":"(e.g., live traffic tiles). The event will not be emitted if "},{"type":"codeVoice","code":"setUserAnimationInProgress"},{"type":"text","text":" "},{"type":"text","text":"and \/ or "},{"type":"codeVoice","code":"setGestureInProgress"},{"text":" is set to ","type":"text"},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/mapidle"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","title":"MapboxMaps Documentation","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderFrameFinished":{"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"map"},{"type":"text","text":" finished rendering a frame."}],"navigatorTitle":[{"text":"RenderFrameFinished","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/renderframefinished","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"RenderFrameFinished","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinished","role":"symbol","kind":"symbol","title":"RenderFrameFinished","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResourceRequest/source":{"abstract":[{"type":"text","text":"The type of data source from which the resource is requested."}],"title":"source","navigatorTitle":[{"kind":"identifier","text":"source"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequest\/source","url":"\/documentation\/mapboxmaps\/resourcerequest\/source","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"source"},{"text":": ","kind":"text"},{"text":"RequestDataSourceType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMRequestDataSourceType"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GenericEvent":{"url":"\/documentation\/mapboxmaps\/genericevent","navigatorTitle":[{"text":"GenericEvent","kind":"identifier"}],"abstract":[{"type":"text","text":"The generic event type."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GenericEvent"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GenericEvent","type":"topic","title":"GenericEvent","role":"symbol"},"doc://com.mapbox.MapboxMaps/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.mapbox.MapboxMaps/SH":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","title":"Swift.Hashable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceDataLoaded":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"SourceDataLoaded"},{"type":"text","text":" event is emitted when source data is loaded."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SourceDataLoaded","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/sourcedataloaded","navigatorTitle":[{"kind":"identifier","text":"SourceDataLoaded"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoaded","title":"SourceDataLoaded"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceAdded":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SourceAdded"}],"kind":"symbol","title":"SourceAdded","type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/sourceadded","navigatorTitle":[{"kind":"identifier","text":"SourceAdded"}],"abstract":[{"type":"text","text":"The source has been added with "},{"code":"addStyleSource","type":"codeVoice"},{"type":"text","text":" method."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceAdded"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoaded":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MapLoaded","kind":"identifier"}],"kind":"symbol","title":"MapLoaded","type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/maploaded","navigatorTitle":[{"text":"MapLoaded","kind":"identifier"}],"abstract":[{"type":"text","text":"The style has been fully loaded, and the "},{"type":"codeVoice","code":"map"},{"type":"text","text":" has rendered all visible tiles."},{"type":"text","text":" "},{"type":"text","text":"The event will be emitted only once for the current style. If it is required to"},{"text":" ","type":"text"},{"type":"text","text":"observe an event where all required resources are loaded or rendered, please"},{"type":"text","text":" "},{"type":"text","text":"check the following events: "},{"type":"codeVoice","code":"MapIdle"},{"text":", ","type":"text"},{"type":"codeVoice","code":"StyleDataLoaded"},{"text":", and ","type":"text"},{"type":"codeVoice","code":"RenderFrameFinished"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoaded"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"kind":"article","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","url":"\/documentation\/mapboxmaps\/events","abstract":[{"type":"text","text":"The simplified diagram of the events emitted by the map is displayed below."}],"title":"Map events","type":"topic"},"doc://com.mapbox.MapboxMaps/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","title":"Swift.Equatable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderFrameStarted":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RenderFrameStarted"}],"kind":"symbol","title":"RenderFrameStarted","type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/renderframestarted","navigatorTitle":[{"text":"RenderFrameStarted","kind":"identifier"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"map"},{"type":"text","text":" started rendering a frame."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameStarted"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResourceRequest/response":{"abstract":[{"type":"text","text":"The structure describes information about the response to the resource request."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequest\/response","role":"symbol","url":"\/documentation\/mapboxmaps\/resourcerequest\/response","kind":"symbol","navigatorTitle":[{"text":"response","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"response"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MBMResponseInfo","text":"ResponseInfo","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"response","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleImageRemoveUnused":{"navigatorTitle":[{"kind":"identifier","text":"StyleImageRemoveUnused"}],"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"StyleImageRemoveUnused"}],"abstract":[{"text":"An image requested by the ","type":"text"},{"type":"codeVoice","code":"map"},{"type":"text","text":" through the "},{"code":"StyleImageMissing","type":"codeVoice"},{"type":"text","text":" event is no longer"},{"type":"text","text":" "},{"type":"text","text":"needed and can be removed using the "},{"code":"removeStyleImage","type":"codeVoice"},{"type":"text","text":" method. The application can"},{"text":" ","type":"text"},{"type":"text","text":"decide whether the image should be kept or removed."}],"title":"StyleImageRemoveUnused","url":"\/documentation\/mapboxmaps\/styleimageremoveunused","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnused","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResourceRequest/cancelled":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"cancelled","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequest\/cancelled","type":"topic","url":"\/documentation\/mapboxmaps\/resourcerequest\/cancelled","role":"symbol","kind":"symbol","title":"cancelled","abstract":[{"type":"text","text":"The property indicates whether the request was canceled. For instance, the"},{"type":"text","text":" "},{"type":"codeVoice","code":"map"},{"text":" requests a tile, and the location quickly changes so that the requested","type":"text"},{"type":"text","text":" "},{"type":"text","text":"tile is no longer needed."}],"navigatorTitle":[{"kind":"identifier","text":"cancelled"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleLoaded":{"url":"\/documentation\/mapboxmaps\/styleloaded","navigatorTitle":[{"kind":"identifier","text":"StyleLoaded"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleLoaded","kind":"symbol","title":"StyleLoaded","role":"symbol","type":"topic","abstract":[{"type":"text","text":"The requested style has been fully loaded, including specified sprite, and sources’ metadata."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StyleLoaded","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleDataLoaded":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"StyleDataLoaded","kind":"identifier"}],"kind":"symbol","title":"StyleDataLoaded","type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/styledataloaded","navigatorTitle":[{"text":"StyleDataLoaded","kind":"identifier"}],"abstract":[{"type":"text","text":"The style data has been loaded. The event will be emitted once for each "},{"type":"codeVoice","code":"StyleDataLoadedType"},{"type":"text","text":" "},{"type":"text","text":"type during style loading. If a new style is set, events will be emitted again for the newly set style."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoaded"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResourceRequest/init(source:request:response:cancelled:timeInterval:)":{"url":"\/documentation\/mapboxmaps\/resourcerequest\/init(source:request:response:cancelled:timeinterval:)","role":"symbol","title":"init(source:request:response:cancelled:timeInterval:)","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequest\/init(source:request:response:cancelled:timeInterval:)","type":"topic","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"source"},{"text":": ","kind":"text"},{"text":"RequestDataSourceType","preciseIdentifier":"c:@E@MBMRequestDataSourceType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"request"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMRequestInfo","kind":"typeIdentifier","text":"RequestInfo"},{"text":", ","kind":"text"},{"text":"response","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ResponseInfo","preciseIdentifier":"c:objc(cs)MBMResponseInfo"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"cancelled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"text":"timeInterval","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMEventTimeInterval","kind":"typeIdentifier","text":"EventTimeInterval"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithSource:request:response:cancelled:timeInterval:"}]},"doc://com.mapbox.MapboxMaps/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"MBMResourceRequest","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MBMResourceRequest"}],"op":"replace"},{"value":[{"kind":"identifier","text":"MBMResourceRequest"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequest\/cancelled","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequest\/request","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequest\/response","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequest\/source","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequest\/timeInterval"],"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequest\/init(source:request:response:cancelled:timeInterval:)"],"anchor":"Instance-Methods","generated":true}]},{"op":"replace","value":[{"kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"}],"path":"\/relationshipsSections"},{"value":[{"generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraChanged","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapIdle","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceAdded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceRemoved","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageMissing","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnused","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameStarted","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinished","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GenericEvent"],"title":"Events","anchor":"Events"}],"path":"\/seeAlsoSections","op":"replace"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBMResourceRequest","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}]}},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageMissing\/title","op":"replace","value":"MBMStyleImageMissing"},{"op":"replace","value":[{"kind":"identifier","text":"MBMStyleImageMissing"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageMissing\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageMissing\/navigatorTitle","value":[{"kind":"identifier","text":"MBMStyleImageMissing"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequest~1request\/title","op":"replace","value":"request"},{"value":[{"text":"request","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequest~1request\/fragments"},{"value":"MBMResourceRequest","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequest\/title"},{"op":"replace","value":[{"text":"MBMResourceRequest","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequest\/fragments"},{"value":[{"text":"MBMResourceRequest","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequest\/navigatorTitle"},{"op":"replace","value":"timeInterval","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequest~1timeInterval\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequest~1timeInterval\/fragments","op":"replace","value":[{"kind":"identifier","text":"timeInterval"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceRemoved\/title","value":"MBMSourceRemoved","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceRemoved\/fragments","value":[{"text":"MBMSourceRemoved","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceRemoved\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMSourceRemoved"}]},{"op":"replace","value":"MBMMapLoadingError","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingError\/title"},{"value":[{"text":"MBMMapLoadingError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingError\/fragments"},{"value":[{"text":"MBMMapLoadingError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingError\/navigatorTitle"},{"op":"replace","value":"MBMCameraChanged","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChanged\/title"},{"value":[{"text":"MBMCameraChanged","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChanged\/fragments"},{"value":[{"kind":"identifier","text":"MBMCameraChanged"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChanged\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdle\/title","value":"MBMMapIdle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdle\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMMapIdle"}]},{"value":[{"text":"MBMMapIdle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdle\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinished\/title","value":"MBMRenderFrameFinished","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinished\/fragments","value":[{"text":"MBMRenderFrameFinished","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinished\/navigatorTitle","value":[{"text":"MBMRenderFrameFinished","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequest~1source\/title","value":"source"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequest~1source\/fragments","value":[{"kind":"identifier","text":"source"}],"op":"replace"},{"value":"MBMGenericEvent","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEvent\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEvent\/fragments","value":[{"text":"MBMGenericEvent","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MBMGenericEvent"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEvent\/navigatorTitle","op":"replace"},{"value":"MBMSourceDataLoaded","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoaded\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoaded\/fragments","value":[{"text":"MBMSourceDataLoaded","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoaded\/navigatorTitle","value":[{"text":"MBMSourceDataLoaded","kind":"identifier"}]},{"op":"replace","value":"MBMSourceAdded","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAdded\/title"},{"op":"replace","value":[{"text":"MBMSourceAdded","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAdded\/fragments"},{"value":[{"kind":"identifier","text":"MBMSourceAdded"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAdded\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoaded\/title","value":"MBMMapLoaded","op":"replace"},{"value":[{"text":"MBMMapLoaded","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoaded\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoaded\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMMapLoaded"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameStarted\/title","value":"MBMRenderFrameStarted"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameStarted\/fragments","value":[{"kind":"identifier","text":"MBMRenderFrameStarted"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameStarted\/navigatorTitle","value":[{"text":"MBMRenderFrameStarted","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"response","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequest~1response\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequest~1response\/fragments","op":"replace","value":[{"text":"response","kind":"identifier"}]},{"op":"replace","value":"MBMStyleImageRemoveUnused","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnused\/title"},{"value":[{"text":"MBMStyleImageRemoveUnused","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnused\/fragments"},{"op":"replace","value":[{"text":"MBMStyleImageRemoveUnused","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnused\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequest~1cancelled\/title","value":"cancelled"},{"op":"replace","value":[{"kind":"identifier","text":"cancelled"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequest~1cancelled\/fragments"},{"value":"MBMStyleLoaded","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoaded\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MBMStyleLoaded"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoaded\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoaded\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMStyleLoaded"}]},{"op":"replace","value":"MBMStyleDataLoaded","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoaded\/title"},{"value":[{"text":"MBMStyleDataLoaded","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoaded\/fragments"},{"value":[{"kind":"identifier","text":"MBMStyleDataLoaded"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoaded\/navigatorTitle"},{"value":"initWithSource:request:response:cancelled:timeInterval:","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequest~1init(source:request:response:cancelled:timeInterval:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithSource:request:response:cancelled:timeInterval:"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequest~1init(source:request:response:cancelled:timeInterval:)\/fragments"}]}]}