{"metadata":{"title":"ResourceRequestCallback","modules":[{"name":"MapboxMaps"}],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResourceRequestCallback"}],"externalID":"c:MBMResourceRequestCallback.h@T@MBMResourceRequestCallback","navigatorTitle":[{"text":"ResourceRequestCallback","kind":"identifier"}],"roleHeading":"Type Alias","role":"symbol","symbolKind":"typealias"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequestCallback"},"schemaVersion":{"minor":3,"major":0,"patch":0},"seeAlsoSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapRecorder","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeatureExtensionValue","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Size","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackError-swift.class","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestErrorType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapLoadingErrorTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRenderModeTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestDataSourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestErrorTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestLoadingMethodTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestPriorityTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestPriorityTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestResourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMResponseSourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMSourceDataLoadedTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStyleDataLoadedTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMTileStoreUsageModeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraChangedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GenericEventCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinishedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameStartedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceAddedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceRemovedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageMissingCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapIdleCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnusedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TransitionOptions-swift.class"],"generated":true,"title":"Symbols","anchor":"Symbols"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResourceRequestCallback"},{"text":" = (","kind":"text"},{"text":"ResourceRequest","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequest","preciseIdentifier":"c:objc(cs)MBMResourceRequest"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMapsInternal"]]},"variants":[{"paths":["\/documentation\/mapboxmaps\/resourcerequestcallback"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/resourcerequestcallback"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"ResourceRequest"},{"type":"text","text":" event allows the application to observe resourcerequests"},{"text":" ","type":"text"},{"type":"text","text":"made by a "},{"type":"codeVoice","code":"map"},{"type":"text","text":" or "},{"code":"map snapshotter","type":"codeVoice"},{"type":"text","text":" object."}],"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRenderModeTypeToString(_:)":{"url":"\/documentation\/mapboxmaps\/mbmrendermodetypetostring(_:)","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRenderModeTypeToString(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBMRenderModeTypeToString"}],"abstract":[],"title":"MBMRenderModeTypeToString(_:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBMRenderModeTypeToString"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"RenderModeType","preciseIdentifier":"c:@E@MBMRenderModeType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"!"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleImageRemoveUnusedCallback":{"url":"\/documentation\/mapboxmaps\/styleimageremoveunusedcallback","type":"topic","abstract":[{"type":"text","text":"An image requested by the "},{"code":"map","type":"codeVoice"},{"text":" through the ","type":"text"},{"code":"StyleImageMissing","type":"codeVoice"},{"text":" event is no longer","type":"text"},{"type":"text","text":" "},{"type":"text","text":"needed and can be removed using the "},{"code":"removeStyleImage","type":"codeVoice"},{"type":"text","text":" method. The application can"},{"type":"text","text":" "},{"type":"text","text":"decide whether the image should be kept or removed."}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnusedCallback","title":"StyleImageRemoveUnusedCallback","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StyleImageRemoveUnusedCallback"}],"navigatorTitle":[{"kind":"identifier","text":"StyleImageRemoveUnusedCallback"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRequestDataSourceTypeToString(_:)":{"url":"\/documentation\/mapboxmaps\/mbmrequestdatasourcetypetostring(_:)","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestDataSourceTypeToString(_:)","title":"MBMRequestDataSourceTypeToString(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"MBMRequestDataSourceTypeToString","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"RequestDataSourceType","preciseIdentifier":"c:@E@MBMRequestDataSourceType"},{"kind":"text","text":") -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"navigatorTitle":[{"kind":"identifier","text":"MBMRequestDataSourceTypeToString"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResourceRequest":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ResourceRequest"}],"type":"topic","url":"\/documentation\/mapboxmaps\/resourcerequest","title":"ResourceRequest","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ResourceRequest"},{"text":" event allows the application to observe resource requests made by a ","type":"text"},{"type":"codeVoice","code":"map"},{"type":"text","text":" or "},{"code":"map snapshotter","type":"codeVoice"},{"type":"text","text":" object."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequest","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ResourceRequest"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRequestResourceTypeToString(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBMRequestResourceTypeToString"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@MBMRequestResourceType","kind":"typeIdentifier","text":"RequestResourceType"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"!"}],"navigatorTitle":[{"text":"MBMRequestResourceTypeToString","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/mbmrequestresourcetypetostring(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestResourceTypeToString(_:)","kind":"symbol","abstract":[],"title":"MBMRequestResourceTypeToString(_:)","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRequestErrorTypeToString(_:)":{"url":"\/documentation\/mapboxmaps\/mbmrequesterrortypetostring(_:)","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestErrorTypeToString(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBMRequestErrorTypeToString"}],"abstract":[],"title":"MBMRequestErrorTypeToString(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBMRequestErrorTypeToString","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@MBMRequestErrorType","text":"RequestErrorType","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"!"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMResponseSourceTypeToString(_:)":{"url":"\/documentation\/mapboxmaps\/mbmresponsesourcetypetostring(_:)","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMResponseSourceTypeToString(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBMResponseSourceTypeToString"}],"abstract":[],"title":"MBMResponseSourceTypeToString(_:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBMResponseSourceTypeToString"},{"kind":"text","text":"("},{"text":"ResponseSourceType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMResponseSourceType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapIdleCallback":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapIdleCallback"}],"navigatorTitle":[{"kind":"identifier","text":"MapIdleCallback"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/mapidlecallback","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The "},{"code":"map","type":"codeVoice"},{"text":" has entered the idle state. The ","type":"text"},{"code":"map","type":"codeVoice"},{"type":"text","text":" is idle when there are no ongoing"},{"type":"text","text":" "},{"type":"text","text":"animations, transitions and the "},{"code":"map","type":"codeVoice"},{"type":"text","text":" has rendered all requested non-volatile tiles"},{"type":"text","text":" "},{"text":"(e.g., live traffic tiles). The event will not be emitted if ","type":"text"},{"code":"setUserAnimationInProgress","type":"codeVoice"},{"text":" ","type":"text"},{"text":"and \/ or ","type":"text"},{"type":"codeVoice","code":"setGestureInProgress"},{"text":" is set to ","type":"text"},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapIdleCallback","title":"MapIdleCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceDataLoadedCallback":{"url":"\/documentation\/mapboxmaps\/sourcedataloadedcallback","type":"topic","abstract":[{"text":"The ","type":"text"},{"code":"SourceDataLoaded","type":"codeVoice"},{"type":"text","text":" event is emitted when source data is loaded."}],"kind":"symbol","title":"SourceDataLoadedCallback","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedCallback","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceDataLoadedCallback"}],"navigatorTitle":[{"kind":"identifier","text":"SourceDataLoadedCallback"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TransitionOptions-swift.class":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TransitionOptions"}],"navigatorTitle":[{"text":"TransitionOptions","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/transitionoptions-swift.class","type":"topic","kind":"symbol","abstract":[{"text":"The ","type":"text"},{"code":"transition options","type":"codeVoice"},{"type":"text","text":" controls timing for the interpolation between a transitionable style"},{"type":"text","text":" "},{"text":"property’s previous value and new value. These can be used to define the style default property","type":"text"},{"text":" ","type":"text"},{"text":"transition behavior. Also, any transitionable style property may also have its own ","type":"text"},{"type":"codeVoice","code":"-transition"},{"type":"text","text":" "},{"type":"text","text":"property that defines specific transition timing for that specific layer property, overriding"},{"text":" ","type":"text"},{"text":"the global transition values.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TransitionOptions-swift.class","title":"TransitionOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Size":{"url":"\/documentation\/mapboxmaps\/size","type":"topic","abstract":[{"type":"text","text":"Size type."}],"kind":"symbol","title":"Size","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Size","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Size"}],"navigatorTitle":[{"kind":"identifier","text":"Size"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleImageMissingCallback":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"StyleImageMissingCallback","kind":"identifier"}],"navigatorTitle":[{"text":"StyleImageMissingCallback","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/styleimagemissingcallback","type":"topic","kind":"symbol","abstract":[{"text":"A style needs an image that is missing from the sprite sheet. This event is","type":"text"},{"type":"text","text":" "},{"text":"emitted when the ","type":"text"},{"type":"codeVoice","code":"map"},{"type":"text","text":" renders visible tiles, and one of the required images"},{"text":" ","type":"text"},{"text":"is missing in the sprite sheet. The event observer has to provide the missing","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"image by calling the "},{"type":"codeVoice","code":"addStyleImage"},{"text":" method.","type":"text"}],"title":"StyleImageMissingCallback","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageMissingCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderFrameStartedCallback":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"RenderFrameStartedCallback","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"RenderFrameStartedCallback"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/renderframestartedcallback","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameStartedCallback","kind":"symbol","abstract":[{"type":"text","text":"The "},{"code":"map","type":"codeVoice"},{"text":" started rendering a frame.","type":"text"}],"type":"topic","title":"RenderFrameStartedCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoadedCallback":{"url":"\/documentation\/mapboxmaps\/maploadedcallback","type":"topic","abstract":[{"type":"text","text":"The style has been fully loaded, and the "},{"type":"codeVoice","code":"map"},{"type":"text","text":" has rendered all visible tiles."},{"text":" ","type":"text"},{"text":"The event will be emitted only once for the current style. If it is required to","type":"text"},{"type":"text","text":" "},{"text":"continuously observe an event where all the necessary resources are loaded or rendered,","type":"text"},{"type":"text","text":" "},{"text":"please check the following events: ","type":"text"},{"code":"MapIdle","type":"codeVoice"},{"type":"text","text":", "},{"code":"StyleDataLoaded","type":"codeVoice"},{"text":", and ","type":"text"},{"code":"RenderFrameFinished","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadedCallback","title":"MapLoadedCallback","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapLoadedCallback"}],"navigatorTitle":[{"text":"MapLoadedCallback","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleLoadedCallback":{"url":"\/documentation\/mapboxmaps\/styleloadedcallback","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleLoadedCallback","role":"symbol","navigatorTitle":[{"text":"StyleLoadedCallback","kind":"identifier"}],"abstract":[{"type":"text","text":"The requested style has been fully loaded, including specified sprite, and sources’ metadata."}],"title":"StyleLoadedCallback","type":"topic","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"StyleLoadedCallback"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePackError-swift.class":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"StylePackError","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"StylePackError"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/stylepackerror-swift.class","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackError-swift.class","kind":"symbol","abstract":[{"text":"Describes a style package load request error.","type":"text"}],"title":"StylePackError","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoadingErrorCallback":{"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapLoadingErrorCallback"}],"navigatorTitle":[{"kind":"identifier","text":"MapLoadingErrorCallback"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/maploadingerrorcallback","type":"topic","kind":"symbol","abstract":[{"text":"Describes an error that has occurred while loading the ","type":"text"},{"code":"map","type":"codeVoice"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorCallback","title":"MapLoadingErrorCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraChangedCallback":{"url":"\/documentation\/mapboxmaps\/camerachangedcallback","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraChangedCallback","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CameraChangedCallback"}],"abstract":[{"type":"text","text":"This event is emitted whenever the visible viewport changes its size"},{"text":" ","type":"text"},{"text":"due to the invocation of the ","type":"text"},{"code":"setSize","type":"codeVoice"},{"type":"text","text":" and "},{"type":"codeVoice","code":"setBounds"},{"type":"text","text":" methods or when"},{"type":"text","text":" "},{"text":"the camera is modified by calling camera methods. The event is emitted","type":"text"},{"text":" ","type":"text"},{"text":"synchronously so that an updated camera state can be fetched immediately.","type":"text"}],"title":"CameraChangedCallback","type":"topic","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraChangedCallback"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMStyleDataLoadedTypeToString(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBMStyleDataLoadedTypeToString"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"StyleDataLoadedType","preciseIdentifier":"c:@E@MBMStyleDataLoadedType"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"navigatorTitle":[{"kind":"identifier","text":"MBMStyleDataLoadedTypeToString"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/mbmstyledataloadedtypetostring(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStyleDataLoadedTypeToString(_:)","kind":"symbol","abstract":[],"type":"topic","title":"MBMStyleDataLoadedTypeToString(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderFrameFinishedCallback":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"RenderFrameFinishedCallback"}],"navigatorTitle":[{"text":"RenderFrameFinishedCallback","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/renderframefinishedcallback","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinishedCallback","kind":"symbol","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"map"},{"type":"text","text":" finished rendering a frame."}],"title":"RenderFrameFinishedCallback","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRequestLoadingMethodTypeToString(_:)":{"url":"\/documentation\/mapboxmaps\/mbmrequestloadingmethodtypetostring(_:)","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestLoadingMethodTypeToString(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBMRequestLoadingMethodTypeToString"}],"abstract":[],"title":"MBMRequestLoadingMethodTypeToString(_:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBMRequestLoadingMethodTypeToString"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMRequestLoadingMethodType","text":"RequestLoadingMethodType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","type":"topic","title":"MapboxMaps Documentation","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResourceRequestCallback":{"url":"\/documentation\/mapboxmaps\/resourcerequestcallback","type":"topic","abstract":[{"text":"The ","type":"text"},{"code":"ResourceRequest","type":"codeVoice"},{"type":"text","text":" event allows the application to observe resourcerequests"},{"type":"text","text":" "},{"type":"text","text":"made by a "},{"code":"map","type":"codeVoice"},{"text":" or ","type":"text"},{"code":"map snapshotter","type":"codeVoice"},{"type":"text","text":" object."}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequestCallback","title":"ResourceRequestCallback","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResourceRequestCallback"}],"navigatorTitle":[{"text":"ResourceRequestCallback","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","title":"MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","role":"collection","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestErrorType":{"url":"\/documentation\/mapboxmaps\/requesterrortype","type":"topic","abstract":[{"text":"The enumeration defines the error type that may occur during a resource request.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestErrorType","title":"RequestErrorType","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"RequestErrorType"}],"navigatorTitle":[{"text":"RequestErrorType","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMapsInternal":{"role":"collectionGroup","url":"\/documentation\/mapboxmaps\/coremapsinternal","kind":"article","type":"topic","title":"CoreMaps - Internal","abstract":[{"text":"Maps rendering SDK also known as GL-Native. These are for internal use only.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMapsInternal"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMMapLoadingErrorTypeToString(_:)":{"url":"\/documentation\/mapboxmaps\/mbmmaploadingerrortypetostring(_:)","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapLoadingErrorTypeToString(_:)","title":"MBMMapLoadingErrorTypeToString(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBMMapLoadingErrorTypeToString"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@MBMMapLoadingErrorType","kind":"typeIdentifier","text":"MapLoadingErrorType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"navigatorTitle":[{"text":"MBMMapLoadingErrorTypeToString","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleDataLoadedCallback":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"StyleDataLoadedCallback"}],"navigatorTitle":[{"kind":"identifier","text":"StyleDataLoadedCallback"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/styledataloadedcallback","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedCallback","kind":"symbol","abstract":[{"text":"The style data has been loaded.","type":"text"}],"title":"StyleDataLoadedCallback","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMTileStoreUsageModeToString(_:)":{"url":"\/documentation\/mapboxmaps\/mbmtilestoreusagemodetostring(_:)","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMTileStoreUsageModeToString(_:)","title":"MBMTileStoreUsageModeToString(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBMTileStoreUsageModeToString"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@MBMTileStoreUsageMode","text":"TileStoreUsageMode","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}],"navigatorTitle":[{"text":"MBMTileStoreUsageModeToString","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GenericEventCallback":{"url":"\/documentation\/mapboxmaps\/genericeventcallback","type":"topic","abstract":[{"text":"Generic event for experimental events.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GenericEventCallback","title":"GenericEventCallback","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"GenericEventCallback"}],"navigatorTitle":[{"text":"GenericEventCallback","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceAddedCallback":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceAddedCallback"}],"navigatorTitle":[{"text":"SourceAddedCallback","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/sourceaddedcallback","type":"topic","kind":"symbol","abstract":[{"text":"The source has been added with ","type":"text"},{"code":"addStyleSource","type":"codeVoice"},{"type":"text","text":" method."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceAddedCallback","title":"SourceAddedCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceRemovedCallback":{"url":"\/documentation\/mapboxmaps\/sourceremovedcallback","type":"topic","abstract":[{"text":"The source has been removed with ","type":"text"},{"code":"removeStyleSource","type":"codeVoice"},{"text":" method.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceRemovedCallback","title":"SourceRemovedCallback","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceRemovedCallback"}],"navigatorTitle":[{"kind":"identifier","text":"SourceRemovedCallback"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FeatureExtensionValue":{"url":"\/documentation\/mapboxmaps\/featureextensionvalue","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeatureExtensionValue","role":"symbol","navigatorTitle":[{"text":"FeatureExtensionValue","kind":"identifier"}],"abstract":[{"text":"A value or a collection of a feature extension.","type":"text"}],"title":"FeatureExtensionValue","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FeatureExtensionValue"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMSourceDataLoadedTypeToString(_:)":{"url":"\/documentation\/mapboxmaps\/mbmsourcedataloadedtypetostring(_:)","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMSourceDataLoadedTypeToString(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBMSourceDataLoadedTypeToString"}],"abstract":[],"title":"MBMSourceDataLoadedTypeToString(_:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBMSourceDataLoadedTypeToString"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMSourceDataLoadedType","text":"SourceDataLoadedType"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRequestPriorityTypeToString(_:)":{"url":"\/documentation\/mapboxmaps\/mbmrequestprioritytypetostring(_:)","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestPriorityTypeToString(_:)","title":"MBMRequestPriorityTypeToString(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBMRequestPriorityTypeToString"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"RequestPriorityType","preciseIdentifier":"c:@E@MBMRequestPriorityType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"!","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MBMRequestPriorityTypeToString"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapRecorder":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapRecorder","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MapRecorder"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/maprecorder","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapRecorder","kind":"symbol","abstract":[{"type":"text","text":"MapRecorder provides functions to record and replay API calls of a Map instance."},{"type":"text","text":" "},{"type":"text","text":"These recordings can be used to debug issues which requie multiple steps to reproduce."},{"type":"text","text":" "},{"text":"Additionaly, playbacks can be used for performance testing custom scenarios.","type":"text"}],"type":"topic","title":"MapRecorder"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Type Alias","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"MBMResourceRequestCallback","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"typealias"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MBMResourceRequestCallback","kind":"identifier"}]},{"value":[{"text":"MBMResourceRequestCallback","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"replace","path":"\/seeAlsoSections","value":[{"anchor":"Symbols","title":"Symbols","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapRecorder","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeatureExtensionValue","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Size","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackError-swift.class","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestErrorType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapLoadingErrorTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRenderModeTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestDataSourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestErrorTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestLoadingMethodTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestPriorityTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestPriorityTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestResourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMResponseSourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMSourceDataLoadedTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStyleDataLoadedTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMTileStoreUsageModeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraChangedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GenericEventCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinishedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameStartedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceAddedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceRemovedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageMissingCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapIdleCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnusedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TransitionOptions-swift.class"],"generated":true}]},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"typedef","kind":"keyword"},{"kind":"text","text":" "},{"text":"void (^)(MBMResourceRequest *)","preciseIdentifier":"c:BFv(#*$objc(cs)MBMResourceRequest)","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"MBMResourceRequestCallback","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"value":"MBMRenderModeTypeToString","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRenderModeTypeToString(_:)\/title"},{"op":"replace","value":[{"text":"MBMRenderModeTypeToString","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRenderModeTypeToString(_:)\/fragments"},{"op":"replace","value":"MBMStyleImageRemoveUnusedCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnusedCallback\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBMStyleImageRemoveUnusedCallback"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnusedCallback\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnusedCallback\/navigatorTitle","value":[{"text":"MBMStyleImageRemoveUnusedCallback","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestDataSourceTypeToString(_:)\/title","value":"MBMRequestDataSourceTypeToString"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestDataSourceTypeToString(_:)\/fragments","value":[{"text":"MBMRequestDataSourceTypeToString","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequest\/title","value":"MBMResourceRequest"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequest\/fragments","op":"replace","value":[{"text":"MBMResourceRequest","kind":"identifier"}]},{"value":[{"text":"MBMResourceRequest","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequest\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestResourceTypeToString(_:)\/title","value":"MBMRequestResourceTypeToString"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestResourceTypeToString(_:)\/fragments","value":[{"kind":"identifier","text":"MBMRequestResourceTypeToString"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestErrorTypeToString(_:)\/title","op":"replace","value":"MBMRequestErrorTypeToString"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestErrorTypeToString(_:)\/fragments","value":[{"text":"MBMRequestErrorTypeToString","kind":"identifier"}],"op":"replace"},{"value":"MBMResponseSourceTypeToString","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMResponseSourceTypeToString(_:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMResponseSourceTypeToString(_:)\/fragments","value":[{"kind":"identifier","text":"MBMResponseSourceTypeToString"}],"op":"replace"},{"op":"replace","value":"MBMMapIdleCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdleCallback\/title"},{"value":[{"text":"MBMMapIdleCallback","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdleCallback\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdleCallback\/navigatorTitle","value":[{"kind":"identifier","text":"MBMMapIdleCallback"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedCallback\/title","op":"replace","value":"MBMSourceDataLoadedCallback"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedCallback\/fragments","value":[{"kind":"identifier","text":"MBMSourceDataLoadedCallback"}],"op":"replace"},{"value":[{"text":"MBMSourceDataLoadedCallback","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedCallback\/navigatorTitle"},{"value":"MBMTransitionOptions","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TransitionOptions-swift.class\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TransitionOptions-swift.class\/fragments","value":[{"text":"MBMTransitionOptions","kind":"identifier"}],"op":"replace"},{"value":[{"text":"MBMTransitionOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TransitionOptions-swift.class\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Size\/title","value":"MBMSize"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Size\/fragments","value":[{"text":"MBMSize","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"MBMSize"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Size\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageMissingCallback\/title","value":"MBMStyleImageMissingCallback","op":"replace"},{"value":[{"kind":"identifier","text":"MBMStyleImageMissingCallback"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageMissingCallback\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MBMStyleImageMissingCallback"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageMissingCallback\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameStartedCallback\/title","value":"MBMRenderFrameStartedCallback","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameStartedCallback\/fragments","value":[{"text":"MBMRenderFrameStartedCallback","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameStartedCallback\/navigatorTitle","value":[{"kind":"identifier","text":"MBMRenderFrameStartedCallback"}],"op":"replace"},{"value":"MBMMapLoadedCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadedCallback\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadedCallback\/fragments","value":[{"text":"MBMMapLoadedCallback","kind":"identifier"}],"op":"replace"},{"value":[{"text":"MBMMapLoadedCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadedCallback\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoadedCallback\/title","value":"MBMStyleLoadedCallback"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoadedCallback\/fragments","value":[{"kind":"identifier","text":"MBMStyleLoadedCallback"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoadedCallback\/navigatorTitle","value":[{"text":"MBMStyleLoadedCallback","kind":"identifier"}]},{"value":"MBMStylePackError","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackError-swift.class\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackError-swift.class\/fragments","value":[{"text":"MBMStylePackError","kind":"identifier"}]},{"value":[{"text":"MBMStylePackError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackError-swift.class\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorCallback\/title","op":"replace","value":"MBMMapLoadingErrorCallback"},{"value":[{"text":"MBMMapLoadingErrorCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorCallback\/fragments","op":"replace"},{"value":[{"text":"MBMMapLoadingErrorCallback","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorCallback\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChangedCallback\/title","value":"MBMCameraChangedCallback"},{"value":[{"text":"MBMCameraChangedCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChangedCallback\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChangedCallback\/navigatorTitle","value":[{"text":"MBMCameraChangedCallback","kind":"identifier"}]},{"value":"MBMStyleDataLoadedTypeToString","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMStyleDataLoadedTypeToString(_:)\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBMStyleDataLoadedTypeToString"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMStyleDataLoadedTypeToString(_:)\/fragments"},{"op":"replace","value":"MBMRenderFrameFinishedCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinishedCallback\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinishedCallback\/fragments","op":"replace","value":[{"text":"MBMRenderFrameFinishedCallback","kind":"identifier"}]},{"op":"replace","value":[{"text":"MBMRenderFrameFinishedCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinishedCallback\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestLoadingMethodTypeToString(_:)\/title","value":"MBMRequestLoadingMethodTypeToString"},{"value":[{"text":"MBMRequestLoadingMethodTypeToString","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestLoadingMethodTypeToString(_:)\/fragments","op":"replace"},{"value":"MBMResourceRequestCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequestCallback\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MBMResourceRequestCallback"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequestCallback\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequestCallback\/navigatorTitle","op":"replace","value":[{"text":"MBMResourceRequestCallback","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestErrorType\/title","value":"MBMRequestErrorType","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestErrorType\/fragments","value":[{"kind":"identifier","text":"MBMRequestErrorType"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestErrorType\/navigatorTitle","value":[{"text":"MBMRequestErrorType","kind":"identifier"}]},{"value":"MBMMapLoadingErrorTypeToString","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMMapLoadingErrorTypeToString(_:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMMapLoadingErrorTypeToString(_:)\/fragments","op":"replace","value":[{"text":"MBMMapLoadingErrorTypeToString","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedCallback\/title","value":"MBMStyleDataLoadedCallback","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedCallback\/fragments","value":[{"text":"MBMStyleDataLoadedCallback","kind":"identifier"}],"op":"replace"},{"value":[{"text":"MBMStyleDataLoadedCallback","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedCallback\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMTileStoreUsageModeToString(_:)\/title","op":"replace","value":"MBMTileStoreUsageModeToString"},{"op":"replace","value":[{"kind":"identifier","text":"MBMTileStoreUsageModeToString"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMTileStoreUsageModeToString(_:)\/fragments"},{"op":"replace","value":"MBMGenericEventCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEventCallback\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEventCallback\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMGenericEventCallback"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEventCallback\/navigatorTitle","value":[{"text":"MBMGenericEventCallback","kind":"identifier"}]},{"op":"replace","value":"MBMSourceAddedCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAddedCallback\/title"},{"value":[{"kind":"identifier","text":"MBMSourceAddedCallback"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAddedCallback\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAddedCallback\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMSourceAddedCallback"}]},{"value":"MBMSourceRemovedCallback","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceRemovedCallback\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceRemovedCallback\/fragments","value":[{"kind":"identifier","text":"MBMSourceRemovedCallback"}]},{"value":[{"text":"MBMSourceRemovedCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceRemovedCallback\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeatureExtensionValue\/title","value":"MBMFeatureExtensionValue"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeatureExtensionValue\/fragments","value":[{"kind":"identifier","text":"MBMFeatureExtensionValue"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeatureExtensionValue\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMFeatureExtensionValue"}]},{"value":"MBMSourceDataLoadedTypeToString","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMSourceDataLoadedTypeToString(_:)\/title","op":"replace"},{"value":[{"text":"MBMSourceDataLoadedTypeToString","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMSourceDataLoadedTypeToString(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestPriorityTypeToString(_:)\/title","value":"MBMRequestPriorityTypeToString","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestPriorityTypeToString(_:)\/fragments","value":[{"text":"MBMRequestPriorityTypeToString","kind":"identifier"}]},{"value":"MBMMapRecorder","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapRecorder\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapRecorder\/fragments","value":[{"text":"MBMMapRecorder","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapRecorder\/navigatorTitle","value":[{"text":"MBMMapRecorder","kind":"identifier"}],"op":"replace"}]}]}