{"seeAlsoSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerInfo","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/BackgroundLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CircleLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillExtrusionLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationIndicatorLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterParticleLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SkyLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderConfiguration","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerHost","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ElevationData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Slot","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerAtPosition","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClipLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClipLayerTypes"],"generated":true,"title":"Layers","anchor":"Layers"}],"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SlotLayer"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"level":2,"anchor":"overview","text":"Overview","type":"heading"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"type":"reference","identifier":"https:\/\/www.mapbox.com\/mapbox-gl-style-spec\/#layers-slot","isActive":true}]}],"type":"aside","name":"See Also"}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/slotlayer"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SlotLayer"},"kind":"symbol","relationshipsSections":[{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapStyleContent","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDecodable","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleEncodable","doc:\/\/com.mapbox.MapboxMaps\/s8CopyableP","doc:\/\/com.mapbox.MapboxMaps\/Se","doc:\/\/com.mapbox.MapboxMaps\/SE","doc:\/\/com.mapbox.MapboxMaps\/SQ"]}],"topicSections":[{"generated":true,"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SlotLayer\/init(from:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SlotLayer\/init(id:)"]},{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SlotLayer\/id","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SlotLayer\/maxZoom","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SlotLayer\/minZoom","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SlotLayer\/slot","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SlotLayer\/type","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SlotLayer\/visibility"],"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SlotLayer\/encode(to:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SlotLayer\/position(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SlotLayer\/slot(_:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"},{"generated":true,"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SlotLayer\/Equatable-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SlotLayer\/Layer-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SlotLayer\/StyleEncodable-Implementations"]}],"abstract":[{"type":"text","text":"Marks the position of a slot."}],"metadata":{"roleHeading":"Structure","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SlotLayer"}],"navigatorTitle":[{"kind":"identifier","text":"SlotLayer"}],"modules":[{"name":"MapboxMaps"}],"role":"symbol","symbolKind":"struct","externalID":"s:10MapboxMaps9SlotLayerV","title":"SlotLayer"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.mapbox.MapboxMaps/Se":{"title":"Swift.Decodable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/Se"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SlotLayer/minZoom":{"type":"topic","abstract":[{"type":"text","text":"No-op for slot layer."}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"minZoom","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"minZoom","url":"\/documentation\/mapboxmaps\/slotlayer\/minzoom","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SlotLayer\/minZoom"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ClipLayer":{"navigatorTitle":[{"kind":"identifier","text":"ClipLayer"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClipLayer","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClipLayer"}],"url":"\/documentation\/mapboxmaps\/cliplayer","title":"ClipLayer","role":"symbol","abstract":[{"type":"text","text":"Layer that removes 3D content from map."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SlotLayer/Equatable-Implementations":{"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SlotLayer\/Equatable-Implementations","role":"collectionGroup","kind":"article","url":"\/documentation\/mapboxmaps\/slotlayer\/equatable-implementations","type":"topic","title":"Equatable Implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SlotLayer/StyleEncodable-Implementations":{"abstract":[],"url":"\/documentation\/mapboxmaps\/slotlayer\/styleencodable-implementations","role":"collectionGroup","type":"topic","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SlotLayer\/StyleEncodable-Implementations","title":"StyleEncodable Implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterLayer":{"abstract":[{"text":"Raster map textures such as satellite imagery.","type":"text"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterLayer","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"RasterLayer","kind":"identifier"}],"navigatorTitle":[{"text":"RasterLayer","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/rasterlayer","title":"RasterLayer"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleDecodable":{"abstract":[{"text":"A protocol describing a style-related entity that can be decoded.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StyleDecodable","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","title":"StyleDecodable","navigatorTitle":[{"text":"StyleDecodable","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDecodable","url":"\/documentation\/mapboxmaps\/styledecodable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SlotLayer/position(_:)":{"kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/slotlayer\/position(_:)","abstract":[{"type":"text","text":"Positions this layer at a specified position."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SlotLayer\/position(_:)","title":"position(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"position","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:10MapboxMaps13LayerPositionO","text":"LayerPosition","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"LayerAtPosition","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps15LayerAtPositionV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps9SlotLayerV","text":"SlotLayer"},{"kind":"text","text":">"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/s8CopyableP":{"title":"Swift.Copyable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s8CopyableP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayer":{"navigatorTitle":[{"text":"CustomLayer","kind":"identifier"}],"title":"CustomLayer","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomLayer","kind":"identifier"}],"tags":[{"type":"spi","text":"SPI"}],"url":"\/documentation\/mapboxmaps\/customlayer","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayer","role":"symbol","abstract":[{"type":"text","text":"Layer with custom rendering implementation"}],"type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelLayer":{"abstract":[{"text":"A layer to render 3D Models.","type":"text"}],"url":"\/documentation\/mapboxmaps\/modellayer","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ModelLayer"}],"navigatorTitle":[{"kind":"identifier","text":"ModelLayer"}],"tags":[{"text":"SPI","type":"spi"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer","title":"ModelLayer"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layer":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer","type":"topic","title":"Layer","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Layer"}],"navigatorTitle":[{"text":"Layer","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/layer","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerHost":{"navigatorTitle":[{"kind":"identifier","text":"CustomLayerHost"}],"role":"symbol","abstract":[{"type":"text","text":"Interface for hosting a custom map style layer."}],"title":"CustomLayerHost","type":"topic","url":"\/documentation\/mapboxmaps\/customlayerhost","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerHost","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomLayerHost","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","url":"\/documentation\/overview","abstract":[],"kind":"article","title":"MapboxMaps Documentation","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerAtPosition":{"navigatorTitle":[{"kind":"identifier","text":"LayerAtPosition"}],"type":"topic","url":"\/documentation\/mapboxmaps\/layeratposition","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"LayerAtPosition","kind":"identifier"}],"abstract":[],"title":"LayerAtPosition","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerAtPosition","kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FillExtrusionLayer":{"abstract":[{"type":"text","text":"An extruded (3D) polygon."}],"title":"FillExtrusionLayer","url":"\/documentation\/mapboxmaps\/fillextrusionlayer","role":"symbol","navigatorTitle":[{"text":"FillExtrusionLayer","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"FillExtrusionLayer","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillExtrusionLayer"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","kind":"symbol","title":"MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SlotLayer/init(id:)":{"title":"init(id:)","url":"\/documentation\/mapboxmaps\/slotlayer\/init(id:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SlotLayer\/init(id:)","kind":"symbol","type":"topic","abstract":[],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SlotLayer/slot(_:)":{"kind":"symbol","abstract":[{"type":"text","text":"The slot this layer is assigned to."},{"text":" ","type":"text"},{"type":"text","text":"If specified, and a slot with that name exists, it will be placed at that position in the layer order."}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SlotLayer\/slot(_:)","title":"slot(_:)","url":"\/documentation\/mapboxmaps\/slotlayer\/slot(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"slot"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps4SlotV","kind":"typeIdentifier","text":"Slot"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:10MapboxMaps9SlotLayerV","text":"SlotLayer","kind":"typeIdentifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ElevationData":{"type":"topic","title":"ElevationData","kind":"symbol","abstract":[{"text":"Interface that provides access to elevation data.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ElevationData","role":"symbol","url":"\/documentation\/mapboxmaps\/elevationdata","navigatorTitle":[{"kind":"identifier","text":"ElevationData"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ElevationData","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerInfo":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerInfo","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"LayerInfo","kind":"identifier"}],"abstract":[{"type":"text","text":"Information about a layer"}],"title":"LayerInfo","url":"\/documentation\/mapboxmaps\/layerinfo","kind":"symbol","navigatorTitle":[{"text":"LayerInfo","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer":{"title":"HillshadeLayer","url":"\/documentation\/mapboxmaps\/hillshadelayer","abstract":[{"text":"Client-side hillshading visualization based on DEM data. Currently, the implementation only supports Mapbox Terrain RGB and Mapzen Terrarium tiles.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"HillshadeLayer","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HillshadeLayer"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer"},"doc://com.mapbox.MapboxMaps/SE":{"title":"Swift.Encodable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SE"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SlotLayer/type":{"kind":"symbol","abstract":[{"type":"text","text":"Rendering type of this layer."}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps9LayerTypeV","text":"LayerType","kind":"typeIdentifier"}],"url":"\/documentation\/mapboxmaps\/slotlayer\/type","role":"symbol","title":"type","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SlotLayer\/type"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Atmosphere":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"Atmosphere"}],"abstract":[{"type":"text","text":"A style’s fog property is a global effect that improves depth perception by fading out distant objects."}],"role":"symbol","kind":"symbol","title":"Atmosphere","url":"\/documentation\/mapboxmaps\/atmosphere","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Atmosphere","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Atmosphere","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/BackgroundLayer":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/BackgroundLayer","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BackgroundLayer","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/backgroundlayer","navigatorTitle":[{"text":"BackgroundLayer","kind":"identifier"}],"type":"topic","abstract":[{"text":"The background color or pattern of the map.","type":"text"}],"title":"BackgroundLayer"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LocationIndicatorLayer":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationIndicatorLayer","kind":"identifier"}],"abstract":[{"type":"text","text":"Location Indicator layer."}],"navigatorTitle":[{"kind":"identifier","text":"LocationIndicatorLayer"}],"url":"\/documentation\/mapboxmaps\/locationindicatorlayer","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationIndicatorLayer","kind":"symbol","type":"topic","role":"symbol","title":"LocationIndicatorLayer"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerRenderParameters":{"type":"topic","kind":"symbol","abstract":[{"text":"Parameters that define the current camera position for a ","type":"text"},{"code":"CustomLayerHost::render()","type":"codeVoice"},{"type":"text","text":" function."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters","title":"CustomLayerRenderParameters","role":"symbol","url":"\/documentation\/mapboxmaps\/customlayerrenderparameters","navigatorTitle":[{"text":"CustomLayerRenderParameters","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CustomLayerRenderParameters","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SlotLayer/encode(to:)":{"kind":"symbol","title":"encode(to:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SlotLayer\/encode(to:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"encode"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","text":"Encoder","preciseIdentifier":"s:s7EncoderP"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"abstract":[],"url":"\/documentation\/mapboxmaps\/slotlayer\/encode(to:)","type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SlotLayer":{"abstract":[{"text":"Marks the position of a slot.","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SlotLayer"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SlotLayer","title":"SlotLayer","kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/slotlayer","navigatorTitle":[{"text":"SlotLayer","kind":"identifier"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerType":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/layertype","title":"LayerType","abstract":[{"type":"text","text":"Struct of supported Layer rendering types"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LayerType"}],"navigatorTitle":[{"text":"LayerType","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FillLayer":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillLayer","kind":"symbol","title":"FillLayer","abstract":[{"type":"text","text":"A filled polygon with an optional stroked border."}],"url":"\/documentation\/mapboxmaps\/filllayer","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"FillLayer","kind":"identifier"}],"navigatorTitle":[{"text":"FillLayer","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layers":{"url":"\/documentation\/mapboxmaps\/layers","abstract":[],"role":"collectionGroup","kind":"article","type":"topic","title":"Layers","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SlotLayer/maxZoom":{"type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/slotlayer\/maxzoom","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"maxZoom","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SlotLayer\/maxZoom","abstract":[{"type":"text","text":"No-op for slot layer."}],"role":"symbol","title":"maxZoom"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeatmapLayer":{"kind":"symbol","navigatorTitle":[{"text":"HeatmapLayer","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer","title":"HeatmapLayer","type":"topic","role":"symbol","abstract":[{"text":"A heatmap.","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"HeatmapLayer","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/heatmaplayer"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SlotLayer/id":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SlotLayer\/id","title":"id","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"id"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"url":"\/documentation\/mapboxmaps\/slotlayer\/id","abstract":[{"type":"text","text":"Unique layer name"}],"type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Slot":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Slot","type":"topic","url":"\/documentation\/mapboxmaps\/slot","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Slot","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Slot"}],"role":"symbol","abstract":[{"text":"A pre-specified location in the style where layer will be added to","type":"text"},{"type":"text","text":" "},{"text":"(such as on top of existing land layers, but below all labels).","type":"text"}],"title":"Slot"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SlotLayer/visibility":{"title":"visibility","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"visibility"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Value","preciseIdentifier":"s:10MapboxMaps5ValueO"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"Visibility","preciseIdentifier":"s:10MapboxMaps10VisibilityO"},{"text":">","kind":"text"}],"url":"\/documentation\/mapboxmaps\/slotlayer\/visibility","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SlotLayer\/visibility","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"No-op for slot layer."}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SkyLayer":{"url":"\/documentation\/mapboxmaps\/skylayer","role":"symbol","navigatorTitle":[{"text":"SkyLayer","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SkyLayer","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SkyLayer","kind":"identifier"}],"type":"topic","title":"SkyLayer","abstract":[{"type":"text","text":"A spherical dome around the map that is always rendered behind all other layers."},{"text":" ","type":"text"},{"text":"Warning: As of v10.6.0, ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Atmosphere","isActive":true,"type":"reference"},{"type":"text","text":" is the preferred method for atmospheric styling. Sky layer is not supported by the globe projection, and will be phased out in future major release."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SlotLayer/init(from:)":{"role":"symbol","abstract":[],"title":"init(from:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": any "},{"preciseIdentifier":"s:s7DecoderP","text":"Decoder","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SlotLayer\/init(from:)","type":"topic","url":"\/documentation\/mapboxmaps\/slotlayer\/init(from:)","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SlotLayer/Layer-Implementations":{"title":"Layer Implementations","type":"topic","kind":"article","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SlotLayer\/Layer-Implementations","url":"\/documentation\/mapboxmaps\/slotlayer\/layer-implementations","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SlotLayer/slot":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/slotlayer\/slot","role":"symbol","type":"topic","abstract":[{"type":"text","text":"The slot this layer is assigned to. If specified, and a slot with that name exists, it will be placed at that position in the layer order."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SlotLayer\/slot","title":"slot","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"slot","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10MapboxMaps4SlotV","text":"Slot","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleEncodable":{"title":"StyleEncodable","navigatorTitle":[{"kind":"identifier","text":"StyleEncodable"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleEncodable","type":"topic","abstract":[{"type":"text","text":"A protocol describing a style-related entity that can be encoded."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StyleEncodable","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/styleencodable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LineLayer":{"abstract":[{"text":"A stroked line.","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineLayer","title":"LineLayer","navigatorTitle":[{"text":"LineLayer","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LineLayer"}],"url":"\/documentation\/mapboxmaps\/linelayer"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapStyleContent":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MapStyleContent"}],"kind":"symbol","type":"topic","title":"MapStyleContent","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MapStyleContent","kind":"identifier"}],"abstract":[{"text":"A protocol used to create any type of  map style content, such as layers, sources, lighting and others.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapStyleContent","url":"\/documentation\/mapboxmaps\/mapstylecontent"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SymbolLayer":{"type":"topic","url":"\/documentation\/mapboxmaps\/symbollayer","abstract":[{"type":"text","text":"An icon or a text label."}],"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SymbolLayer"}],"navigatorTitle":[{"kind":"identifier","text":"SymbolLayer"}],"title":"SymbolLayer","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolLayer"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ClipLayerTypes":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClipLayerTypes","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClipLayerTypes"}],"abstract":[{"type":"text","text":"Layer types that will also be removed if fallen below this clip layer."}],"title":"ClipLayerTypes","url":"\/documentation\/mapboxmaps\/cliplayertypes","kind":"symbol","navigatorTitle":[{"text":"ClipLayerTypes","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CircleLayer":{"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"CircleLayer","kind":"identifier"}],"title":"CircleLayer","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CircleLayer","url":"\/documentation\/mapboxmaps\/circlelayer","navigatorTitle":[{"text":"CircleLayer","kind":"identifier"}],"abstract":[{"type":"text","text":"A filled circle."}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerRenderConfiguration":{"navigatorTitle":[{"text":"CustomLayerRenderConfiguration","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Note! This is an experimental feature. It can be changed or removed in future versions.","type":"text"}],"title":"CustomLayerRenderConfiguration","type":"topic","url":"\/documentation\/mapboxmaps\/customlayerrenderconfiguration","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderConfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CustomLayerRenderConfiguration","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterParticleLayer":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"RasterParticleLayer"}],"url":"\/documentation\/mapboxmaps\/rasterparticlelayer","abstract":[{"text":"Particle animation driven by textures such as wind maps.","type":"text"}],"kind":"symbol","tags":[{"text":"SPI","type":"spi"}],"title":"RasterParticleLayer","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"RasterParticleLayer"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterParticleLayer"},"https://www.mapbox.com/mapbox-gl-style-spec/#layers-slot":{"titleInlineContent":[{"type":"text","text":"Mapbox Style Specification"}],"identifier":"https:\/\/www.mapbox.com\/mapbox-gl-style-spec\/#layers-slot","title":"Mapbox Style Specification","url":"https:\/\/www.mapbox.com\/mapbox-gl-style-spec\/#layers-slot","type":"link"}},"variantOverrides":[{"patch":[{"op":"replace","value":"MBMCustomLayerHost","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost\/title"},{"value":[{"kind":"identifier","text":"MBMCustomLayerHost"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost\/fragments","op":"replace"},{"value":[{"text":"MBMCustomLayerHost","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ElevationData\/title","value":"MBMElevationData"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ElevationData\/fragments","value":[{"text":"MBMElevationData","kind":"identifier"}]},{"op":"replace","value":[{"text":"MBMElevationData","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ElevationData\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/title","value":"MBMCustomLayerRenderParameters"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/fragments","value":[{"text":"MBMCustomLayerRenderParameters","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMCustomLayerRenderParameters"}]},{"value":"MBMCustomLayerRenderConfiguration","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderConfiguration\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderConfiguration\/fragments","op":"replace","value":[{"text":"MBMCustomLayerRenderConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderConfiguration\/navigatorTitle","value":[{"text":"MBMCustomLayerRenderConfiguration","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}