{"variants":[{"paths":["\/documentation\/mapboxmaps\/sourceremovedcallback"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/sourceremovedcallback"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceRemovedCallback"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SourceRemovedCallback"}],"roleHeading":"Type Alias","role":"symbol","externalID":"c:MBMSourceRemovedCallback.h@T@MBMSourceRemovedCallback","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceRemovedCallback"}],"title":"SourceRemovedCallback","modules":[{"name":"MapboxMaps"}],"symbolKind":"typealias"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"The source has been removed with ","type":"text"},{"type":"codeVoice","code":"removeStyleSource"},{"type":"text","text":" method."}],"seeAlsoSections":[{"title":"Symbols","anchor":"Symbols","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapRecorder","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeatureExtensionValue","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Size","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackError-swift.class","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestErrorType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapLoadingErrorTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRenderModeTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestDataSourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestErrorTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestLoadingMethodTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestPriorityTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestPriorityTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestResourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMResponseSourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMSourceDataLoadedTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStyleDataLoadedTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMTileStoreUsageModeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraChangedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GenericEventCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinishedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameStartedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequestCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceAddedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageMissingCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapIdleCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnusedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TransitionOptions-swift.class"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMapsInternal"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SourceRemovedCallback"},{"text":" = (","kind":"text"},{"text":"SourceRemoved","preciseIdentifier":"c:objc(cs)MBMSourceRemoved","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceRemoved","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMSourceDataLoadedTypeToString(_:)":{"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMSourceDataLoadedTypeToString(_:)","title":"MBMSourceDataLoadedTypeToString(_:)","url":"\/documentation\/mapboxmaps\/mbmsourcedataloadedtypetostring(_:)","type":"topic","navigatorTitle":[{"text":"MBMSourceDataLoadedTypeToString","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"MBMSourceDataLoadedTypeToString","kind":"identifier"},{"kind":"text","text":"("},{"text":"SourceDataLoadedType","preciseIdentifier":"c:@E@MBMSourceDataLoadedType","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMMapLoadingErrorTypeToString(_:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapLoadingErrorTypeToString(_:)","kind":"symbol","abstract":[],"role":"symbol","url":"\/documentation\/mapboxmaps\/mbmmaploadingerrortypetostring(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBMMapLoadingErrorTypeToString"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@MBMMapLoadingErrorType","kind":"typeIdentifier","text":"MapLoadingErrorType"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"!","kind":"text"}],"navigatorTitle":[{"text":"MBMMapLoadingErrorTypeToString","kind":"identifier"}],"title":"MBMMapLoadingErrorTypeToString(_:)","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceDataLoadedCallback":{"role":"symbol","abstract":[{"text":"The ","type":"text"},{"code":"SourceDataLoaded","type":"codeVoice"},{"type":"text","text":" event is emitted when source data is loaded."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedCallback","url":"\/documentation\/mapboxmaps\/sourcedataloadedcallback","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"SourceDataLoadedCallback","kind":"identifier"}],"kind":"symbol","type":"topic","title":"SourceDataLoadedCallback","navigatorTitle":[{"kind":"identifier","text":"SourceDataLoadedCallback"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMStyleDataLoadedTypeToString(_:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStyleDataLoadedTypeToString(_:)","kind":"symbol","abstract":[],"role":"symbol","url":"\/documentation\/mapboxmaps\/mbmstyledataloadedtypetostring(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBMStyleDataLoadedTypeToString","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMStyleDataLoadedType","text":"StyleDataLoadedType"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MBMStyleDataLoadedTypeToString"}],"title":"MBMStyleDataLoadedTypeToString(_:)","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Size":{"role":"symbol","title":"Size","kind":"symbol","url":"\/documentation\/mapboxmaps\/size","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Size"}],"navigatorTitle":[{"kind":"identifier","text":"Size"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Size","abstract":[{"text":"Size type.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapIdleCallback":{"kind":"symbol","title":"MapIdleCallback","navigatorTitle":[{"text":"MapIdleCallback","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/mapidlecallback","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"map"},{"text":" has entered the idle state. The ","type":"text"},{"code":"map","type":"codeVoice"},{"text":" is idle when there are no ongoing","type":"text"},{"text":" ","type":"text"},{"text":"animations, transitions and the ","type":"text"},{"type":"codeVoice","code":"map"},{"text":" has rendered all requested non-volatile tiles","type":"text"},{"type":"text","text":" "},{"type":"text","text":"(e.g., live traffic tiles). The event will not be emitted if "},{"type":"codeVoice","code":"setUserAnimationInProgress"},{"text":" ","type":"text"},{"type":"text","text":"and \/ or "},{"code":"setGestureInProgress","type":"codeVoice"},{"type":"text","text":" is set to "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapIdleCallback","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapIdleCallback","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article","role":"collection","title":"MapboxMaps Documentation","type":"topic","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoadingErrorCallback":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorCallback","navigatorTitle":[{"text":"MapLoadingErrorCallback","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxmaps\/maploadingerrorcallback","abstract":[{"type":"text","text":"Describes an error that has occurred while loading the "},{"code":"map","type":"codeVoice"},{"type":"text","text":"."}],"title":"MapLoadingErrorCallback","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapLoadingErrorCallback"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FeatureExtensionValue":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeatureExtensionValue","kind":"symbol","abstract":[{"text":"A value or a collection of a feature extension.","type":"text"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/featureextensionvalue","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FeatureExtensionValue","kind":"identifier"}],"navigatorTitle":[{"text":"FeatureExtensionValue","kind":"identifier"}],"title":"FeatureExtensionValue","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRequestPriorityTypeToString(_:)":{"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestPriorityTypeToString(_:)","title":"MBMRequestPriorityTypeToString(_:)","url":"\/documentation\/mapboxmaps\/mbmrequestprioritytypetostring(_:)","type":"topic","navigatorTitle":[{"text":"MBMRequestPriorityTypeToString","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBMRequestPriorityTypeToString"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMRequestPriorityType","text":"RequestPriorityType"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRequestErrorTypeToString(_:)":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestErrorTypeToString(_:)","navigatorTitle":[{"kind":"identifier","text":"MBMRequestErrorTypeToString"}],"type":"topic","url":"\/documentation\/mapboxmaps\/mbmrequesterrortypetostring(_:)","title":"MBMRequestErrorTypeToString(_:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBMRequestErrorTypeToString"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@MBMRequestErrorType","text":"RequestErrorType","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TransitionOptions-swift.class":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TransitionOptions-swift.class","kind":"symbol","abstract":[{"type":"text","text":"The "},{"code":"transition options","type":"codeVoice"},{"type":"text","text":" controls timing for the interpolation between a transitionable style"},{"text":" ","type":"text"},{"type":"text","text":"property’s previous value and new value. These can be used to define the style default property"},{"type":"text","text":" "},{"type":"text","text":"transition behavior. Also, any transitionable style property may also have its own "},{"type":"codeVoice","code":"-transition"},{"text":" ","type":"text"},{"text":"property that defines specific transition timing for that specific layer property, overriding","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"the global transition values."}],"role":"symbol","url":"\/documentation\/mapboxmaps\/transitionoptions-swift.class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TransitionOptions","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"TransitionOptions"}],"title":"TransitionOptions","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleImageRemoveUnusedCallback":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnusedCallback","kind":"symbol","abstract":[{"text":"An image requested by the ","type":"text"},{"code":"map","type":"codeVoice"},{"type":"text","text":" through the "},{"type":"codeVoice","code":"StyleImageMissing"},{"type":"text","text":" event is no longer"},{"type":"text","text":" "},{"text":"needed and can be removed using the ","type":"text"},{"type":"codeVoice","code":"removeStyleImage"},{"text":" method. The application can","type":"text"},{"type":"text","text":" "},{"type":"text","text":"decide whether the image should be kept or removed."}],"role":"symbol","url":"\/documentation\/mapboxmaps\/styleimageremoveunusedcallback","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StyleImageRemoveUnusedCallback"}],"navigatorTitle":[{"text":"StyleImageRemoveUnusedCallback","kind":"identifier"}],"title":"StyleImageRemoveUnusedCallback","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceAddedCallback":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceAddedCallback","abstract":[{"text":"The source has been added with ","type":"text"},{"type":"codeVoice","code":"addStyleSource"},{"text":" method.","type":"text"}],"url":"\/documentation\/mapboxmaps\/sourceaddedcallback","type":"topic","role":"symbol","title":"SourceAddedCallback","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"SourceAddedCallback","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SourceAddedCallback"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","title":"MapboxMaps","kind":"symbol","role":"collection","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestErrorType":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RequestErrorType"}],"url":"\/documentation\/mapboxmaps\/requesterrortype","role":"symbol","title":"RequestErrorType","abstract":[{"type":"text","text":"The enumeration defines the error type that may occur during a resource request."}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestErrorType","navigatorTitle":[{"text":"RequestErrorType","kind":"identifier"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMapsInternal":{"kind":"article","url":"\/documentation\/mapboxmaps\/coremapsinternal","abstract":[{"type":"text","text":"Maps rendering SDK also known as GL-Native. These are for internal use only."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMapsInternal","role":"collectionGroup","type":"topic","title":"CoreMaps - Internal"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleImageMissingCallback":{"role":"symbol","abstract":[{"type":"text","text":"A style needs an image that is missing from the sprite sheet. This event is"},{"text":" ","type":"text"},{"text":"emitted when the ","type":"text"},{"code":"map","type":"codeVoice"},{"type":"text","text":" renders visible tiles, and one of the required images"},{"text":" ","type":"text"},{"type":"text","text":"is missing in the sprite sheet. The event observer has to provide the missing"},{"type":"text","text":" "},{"type":"text","text":"image by calling the "},{"type":"codeVoice","code":"addStyleImage"},{"type":"text","text":" method."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageMissingCallback","url":"\/documentation\/mapboxmaps\/styleimagemissingcallback","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StyleImageMissingCallback","kind":"identifier"}],"kind":"symbol","type":"topic","title":"StyleImageMissingCallback","navigatorTitle":[{"text":"StyleImageMissingCallback","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMTileStoreUsageModeToString(_:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMTileStoreUsageModeToString(_:)","abstract":[],"type":"topic","url":"\/documentation\/mapboxmaps\/mbmtilestoreusagemodetostring(_:)","role":"symbol","title":"MBMTileStoreUsageModeToString(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"MBMTileStoreUsageModeToString","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMTileStoreUsageMode","text":"TileStoreUsageMode"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"navigatorTitle":[{"text":"MBMTileStoreUsageModeToString","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoadedCallback":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadedCallback","abstract":[{"text":"The style has been fully loaded, and the ","type":"text"},{"code":"map","type":"codeVoice"},{"type":"text","text":" has rendered all visible tiles."},{"text":" ","type":"text"},{"type":"text","text":"The event will be emitted only once for the current style. If it is required to"},{"type":"text","text":" "},{"type":"text","text":"continuously observe an event where all the necessary resources are loaded or rendered,"},{"type":"text","text":" "},{"text":"please check the following events: ","type":"text"},{"type":"codeVoice","code":"MapIdle"},{"text":", ","type":"text"},{"type":"codeVoice","code":"StyleDataLoaded"},{"text":", and ","type":"text"},{"type":"codeVoice","code":"RenderFrameFinished"},{"type":"text","text":"."}],"url":"\/documentation\/mapboxmaps\/maploadedcallback","type":"topic","role":"symbol","title":"MapLoadedCallback","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapLoadedCallback","kind":"identifier"}],"navigatorTitle":[{"text":"MapLoadedCallback","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRequestResourceTypeToString(_:)":{"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestResourceTypeToString(_:)","title":"MBMRequestResourceTypeToString(_:)","url":"\/documentation\/mapboxmaps\/mbmrequestresourcetypetostring(_:)","type":"topic","navigatorTitle":[{"text":"MBMRequestResourceTypeToString","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBMRequestResourceTypeToString"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@MBMRequestResourceType","text":"RequestResourceType","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRequestDataSourceTypeToString(_:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestDataSourceTypeToString(_:)","kind":"symbol","abstract":[],"role":"symbol","url":"\/documentation\/mapboxmaps\/mbmrequestdatasourcetypetostring(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBMRequestDataSourceTypeToString","kind":"identifier"},{"text":"(","kind":"text"},{"text":"RequestDataSourceType","preciseIdentifier":"c:@E@MBMRequestDataSourceType","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"!"}],"navigatorTitle":[{"kind":"identifier","text":"MBMRequestDataSourceTypeToString"}],"title":"MBMRequestDataSourceTypeToString(_:)","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderFrameStartedCallback":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameStartedCallback","navigatorTitle":[{"kind":"identifier","text":"RenderFrameStartedCallback"}],"type":"topic","url":"\/documentation\/mapboxmaps\/renderframestartedcallback","title":"RenderFrameStartedCallback","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"map"},{"type":"text","text":" started rendering a frame."}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RenderFrameStartedCallback","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleDataLoadedCallback":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedCallback","abstract":[{"text":"The style data has been loaded.","type":"text"}],"type":"topic","url":"\/documentation\/mapboxmaps\/styledataloadedcallback","role":"symbol","title":"StyleDataLoadedCallback","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StyleDataLoadedCallback"}],"navigatorTitle":[{"kind":"identifier","text":"StyleDataLoadedCallback"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleLoadedCallback":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleLoadedCallback","navigatorTitle":[{"text":"StyleLoadedCallback","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxmaps\/styleloadedcallback","title":"StyleLoadedCallback","abstract":[{"type":"text","text":"The requested style has been fully loaded, including specified sprite, and sources’ metadata."}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StyleLoadedCallback","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRequestLoadingMethodTypeToString(_:)":{"type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/mbmrequestloadingmethodtypetostring(_:)","navigatorTitle":[{"text":"MBMRequestLoadingMethodTypeToString","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestLoadingMethodTypeToString(_:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"MBMRequestLoadingMethodTypeToString","kind":"identifier"},{"kind":"text","text":"("},{"text":"RequestLoadingMethodType","preciseIdentifier":"c:@E@MBMRequestLoadingMethodType","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"title":"MBMRequestLoadingMethodTypeToString(_:)","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMResponseSourceTypeToString(_:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMResponseSourceTypeToString(_:)","kind":"symbol","abstract":[],"role":"symbol","url":"\/documentation\/mapboxmaps\/mbmresponsesourcetypetostring(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBMResponseSourceTypeToString","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@MBMResponseSourceType","text":"ResponseSourceType","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"!","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MBMResponseSourceTypeToString"}],"title":"MBMResponseSourceTypeToString(_:)","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderFrameFinishedCallback":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinishedCallback","navigatorTitle":[{"kind":"identifier","text":"RenderFrameFinishedCallback"}],"type":"topic","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"map"},{"text":" finished rendering a frame.","type":"text"}],"title":"RenderFrameFinishedCallback","url":"\/documentation\/mapboxmaps\/renderframefinishedcallback","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"RenderFrameFinishedCallback","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRenderModeTypeToString(_:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRenderModeTypeToString(_:)","kind":"symbol","abstract":[],"role":"symbol","url":"\/documentation\/mapboxmaps\/mbmrendermodetypetostring(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBMRenderModeTypeToString"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMRenderModeType","text":"RenderModeType"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"navigatorTitle":[{"text":"MBMRenderModeTypeToString","kind":"identifier"}],"title":"MBMRenderModeTypeToString(_:)","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceRemovedCallback":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceRemovedCallback","kind":"symbol","abstract":[{"text":"The source has been removed with ","type":"text"},{"type":"codeVoice","code":"removeStyleSource"},{"text":" method.","type":"text"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/sourceremovedcallback","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SourceRemovedCallback","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SourceRemovedCallback"}],"title":"SourceRemovedCallback","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraChangedCallback":{"abstract":[{"type":"text","text":"This event is emitted whenever the visible viewport changes its size"},{"type":"text","text":" "},{"type":"text","text":"due to the invocation of the "},{"type":"codeVoice","code":"setSize"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"setBounds"},{"type":"text","text":" methods or when"},{"type":"text","text":" "},{"text":"the camera is modified by calling camera methods. The event is emitted","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"synchronously so that an updated camera state can be fetched immediately."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraChangedCallback","title":"CameraChangedCallback","url":"\/documentation\/mapboxmaps\/camerachangedcallback","type":"topic","navigatorTitle":[{"text":"CameraChangedCallback","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraChangedCallback","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GenericEventCallback":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GenericEventCallback","kind":"symbol","abstract":[{"text":"Generic event for experimental events.","type":"text"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/genericeventcallback","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GenericEventCallback"}],"navigatorTitle":[{"text":"GenericEventCallback","kind":"identifier"}],"title":"GenericEventCallback","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePackError-swift.class":{"abstract":[{"type":"text","text":"Describes a style package load request error."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackError-swift.class","title":"StylePackError","url":"\/documentation\/mapboxmaps\/stylepackerror-swift.class","type":"topic","navigatorTitle":[{"text":"StylePackError","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StylePackError","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResourceRequestCallback":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequestCallback","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"ResourceRequest"},{"text":" event allows the application to observe resourcerequests","type":"text"},{"type":"text","text":" "},{"text":"made by a ","type":"text"},{"code":"map","type":"codeVoice"},{"type":"text","text":" or "},{"code":"map snapshotter","type":"codeVoice"},{"type":"text","text":" object."}],"type":"topic","url":"\/documentation\/mapboxmaps\/resourcerequestcallback","role":"symbol","title":"ResourceRequestCallback","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ResourceRequestCallback"}],"navigatorTitle":[{"text":"ResourceRequestCallback","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceRemoved":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SourceRemoved"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/sourceremoved","abstract":[{"text":"The source has been removed with ","type":"text"},{"type":"codeVoice","code":"removeStyleSource"},{"text":" method.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SourceRemoved"}],"type":"topic","kind":"symbol","title":"SourceRemoved","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceRemoved"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapRecorder":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapRecorder","navigatorTitle":[{"text":"MapRecorder","kind":"identifier"}],"type":"topic","abstract":[{"text":"MapRecorder provides functions to record and replay API calls of a Map instance.","type":"text"},{"type":"text","text":" "},{"text":"These recordings can be used to debug issues which requie multiple steps to reproduce.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Additionaly, playbacks can be used for performance testing custom scenarios."}],"title":"MapRecorder","url":"\/documentation\/mapboxmaps\/maprecorder","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapRecorder"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Type Alias","op":"replace","path":"\/metadata\/roleHeading"},{"value":"MBMSourceRemovedCallback","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"typealias","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MBMSourceRemovedCallback"}],"op":"replace"},{"op":"replace","value":[{"text":"MBMSourceRemovedCallback","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":[{"title":"Symbols","anchor":"Symbols","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapRecorder","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeatureExtensionValue","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Size","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackError-swift.class","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestErrorType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapLoadingErrorTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRenderModeTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestDataSourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestErrorTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestLoadingMethodTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestPriorityTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestPriorityTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestResourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMResponseSourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMSourceDataLoadedTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStyleDataLoadedTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMTileStoreUsageModeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraChangedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GenericEventCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinishedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameStartedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequestCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceAddedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageMissingCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapIdleCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnusedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TransitionOptions-swift.class"]}],"path":"\/seeAlsoSections","op":"replace"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"text":"void (^)(MBMSourceRemoved *)","preciseIdentifier":"c:BFv(#*$objc(cs)MBMSourceRemoved)","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBMSourceRemovedCallback"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMSourceDataLoadedTypeToString(_:)\/title","value":"MBMSourceDataLoadedTypeToString"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMSourceDataLoadedTypeToString(_:)\/fragments","value":[{"text":"MBMSourceDataLoadedTypeToString","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMMapLoadingErrorTypeToString(_:)\/title","op":"replace","value":"MBMMapLoadingErrorTypeToString"},{"value":[{"kind":"identifier","text":"MBMMapLoadingErrorTypeToString"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMMapLoadingErrorTypeToString(_:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedCallback\/title","value":"MBMSourceDataLoadedCallback","op":"replace"},{"value":[{"kind":"identifier","text":"MBMSourceDataLoadedCallback"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedCallback\/fragments","op":"replace"},{"value":[{"text":"MBMSourceDataLoadedCallback","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedCallback\/navigatorTitle"},{"op":"replace","value":"MBMStyleDataLoadedTypeToString","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMStyleDataLoadedTypeToString(_:)\/title"},{"value":[{"text":"MBMStyleDataLoadedTypeToString","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMStyleDataLoadedTypeToString(_:)\/fragments"},{"value":"MBMSize","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Size\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Size\/fragments","value":[{"kind":"identifier","text":"MBMSize"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Size\/navigatorTitle","value":[{"kind":"identifier","text":"MBMSize"}]},{"op":"replace","value":"MBMMapIdleCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdleCallback\/title"},{"value":[{"text":"MBMMapIdleCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdleCallback\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdleCallback\/navigatorTitle","value":[{"kind":"identifier","text":"MBMMapIdleCallback"}],"op":"replace"},{"value":"MBMMapLoadingErrorCallback","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorCallback\/title"},{"value":[{"text":"MBMMapLoadingErrorCallback","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorCallback\/fragments"},{"value":[{"kind":"identifier","text":"MBMMapLoadingErrorCallback"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorCallback\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeatureExtensionValue\/title","value":"MBMFeatureExtensionValue","op":"replace"},{"value":[{"kind":"identifier","text":"MBMFeatureExtensionValue"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeatureExtensionValue\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeatureExtensionValue\/navigatorTitle","value":[{"text":"MBMFeatureExtensionValue","kind":"identifier"}]},{"value":"MBMRequestPriorityTypeToString","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestPriorityTypeToString(_:)\/title"},{"op":"replace","value":[{"text":"MBMRequestPriorityTypeToString","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestPriorityTypeToString(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestErrorTypeToString(_:)\/title","value":"MBMRequestErrorTypeToString","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestErrorTypeToString(_:)\/fragments","value":[{"text":"MBMRequestErrorTypeToString","kind":"identifier"}],"op":"replace"},{"value":"MBMTransitionOptions","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TransitionOptions-swift.class\/title"},{"value":[{"text":"MBMTransitionOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TransitionOptions-swift.class\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TransitionOptions-swift.class\/navigatorTitle","value":[{"kind":"identifier","text":"MBMTransitionOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnusedCallback\/title","value":"MBMStyleImageRemoveUnusedCallback"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnusedCallback\/fragments","op":"replace","value":[{"text":"MBMStyleImageRemoveUnusedCallback","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnusedCallback\/navigatorTitle","value":[{"kind":"identifier","text":"MBMStyleImageRemoveUnusedCallback"}]},{"value":"MBMSourceAddedCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAddedCallback\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAddedCallback\/fragments","op":"replace","value":[{"text":"MBMSourceAddedCallback","kind":"identifier"}]},{"value":[{"text":"MBMSourceAddedCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAddedCallback\/navigatorTitle","op":"replace"},{"value":"MBMRequestErrorType","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestErrorType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBMRequestErrorType"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestErrorType\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestErrorType\/navigatorTitle","value":[{"text":"MBMRequestErrorType","kind":"identifier"}],"op":"replace"},{"value":"MBMStyleImageMissingCallback","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageMissingCallback\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageMissingCallback\/fragments","value":[{"text":"MBMStyleImageMissingCallback","kind":"identifier"}],"op":"replace"},{"value":[{"text":"MBMStyleImageMissingCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageMissingCallback\/navigatorTitle","op":"replace"},{"op":"replace","value":"MBMTileStoreUsageModeToString","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMTileStoreUsageModeToString(_:)\/title"},{"value":[{"text":"MBMTileStoreUsageModeToString","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMTileStoreUsageModeToString(_:)\/fragments"},{"value":"MBMMapLoadedCallback","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadedCallback\/title"},{"value":[{"kind":"identifier","text":"MBMMapLoadedCallback"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadedCallback\/fragments"},{"op":"replace","value":[{"text":"MBMMapLoadedCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadedCallback\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestResourceTypeToString(_:)\/title","op":"replace","value":"MBMRequestResourceTypeToString"},{"value":[{"text":"MBMRequestResourceTypeToString","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestResourceTypeToString(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestDataSourceTypeToString(_:)\/title","value":"MBMRequestDataSourceTypeToString"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestDataSourceTypeToString(_:)\/fragments","value":[{"kind":"identifier","text":"MBMRequestDataSourceTypeToString"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameStartedCallback\/title","value":"MBMRenderFrameStartedCallback","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBMRenderFrameStartedCallback"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameStartedCallback\/fragments"},{"value":[{"text":"MBMRenderFrameStartedCallback","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameStartedCallback\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedCallback\/title","value":"MBMStyleDataLoadedCallback"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedCallback\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMStyleDataLoadedCallback"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedCallback\/navigatorTitle","value":[{"kind":"identifier","text":"MBMStyleDataLoadedCallback"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoadedCallback\/title","op":"replace","value":"MBMStyleLoadedCallback"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoadedCallback\/fragments","value":[{"text":"MBMStyleLoadedCallback","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MBMStyleLoadedCallback"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoadedCallback\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestLoadingMethodTypeToString(_:)\/title","value":"MBMRequestLoadingMethodTypeToString"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestLoadingMethodTypeToString(_:)\/fragments","op":"replace","value":[{"text":"MBMRequestLoadingMethodTypeToString","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMResponseSourceTypeToString(_:)\/title","value":"MBMResponseSourceTypeToString"},{"value":[{"text":"MBMResponseSourceTypeToString","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMResponseSourceTypeToString(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinishedCallback\/title","op":"replace","value":"MBMRenderFrameFinishedCallback"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinishedCallback\/fragments","value":[{"kind":"identifier","text":"MBMRenderFrameFinishedCallback"}]},{"value":[{"kind":"identifier","text":"MBMRenderFrameFinishedCallback"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinishedCallback\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRenderModeTypeToString(_:)\/title","value":"MBMRenderModeTypeToString","op":"replace"},{"value":[{"kind":"identifier","text":"MBMRenderModeTypeToString"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRenderModeTypeToString(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceRemovedCallback\/title","op":"replace","value":"MBMSourceRemovedCallback"},{"value":[{"text":"MBMSourceRemovedCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceRemovedCallback\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceRemovedCallback\/navigatorTitle","op":"replace","value":[{"text":"MBMSourceRemovedCallback","kind":"identifier"}]},{"op":"replace","value":"MBMCameraChangedCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChangedCallback\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChangedCallback\/fragments","value":[{"text":"MBMCameraChangedCallback","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChangedCallback\/navigatorTitle","value":[{"text":"MBMCameraChangedCallback","kind":"identifier"}]},{"op":"replace","value":"MBMGenericEventCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEventCallback\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEventCallback\/fragments","op":"replace","value":[{"text":"MBMGenericEventCallback","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEventCallback\/navigatorTitle","value":[{"text":"MBMGenericEventCallback","kind":"identifier"}],"op":"replace"},{"value":"MBMStylePackError","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackError-swift.class\/title"},{"value":[{"kind":"identifier","text":"MBMStylePackError"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackError-swift.class\/fragments","op":"replace"},{"op":"replace","value":[{"text":"MBMStylePackError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackError-swift.class\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequestCallback\/title","value":"MBMResourceRequestCallback"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequestCallback\/fragments","value":[{"text":"MBMResourceRequestCallback","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequestCallback\/navigatorTitle","op":"replace","value":[{"text":"MBMResourceRequestCallback","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceRemoved\/title","op":"replace","value":"MBMSourceRemoved"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceRemoved\/fragments","value":[{"text":"MBMSourceRemoved","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceRemoved\/navigatorTitle","value":[{"text":"MBMSourceRemoved","kind":"identifier"}]},{"op":"replace","value":"MBMMapRecorder","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapRecorder\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapRecorder\/fragments","value":[{"text":"MBMMapRecorder","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"MBMMapRecorder"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapRecorder\/navigatorTitle","op":"replace"}]}]}