{"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnusedCallback","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"StyleImageRemoveUnusedCallback"},{"text":" = (","kind":"text"},{"text":"StyleImageRemoveUnused","preciseIdentifier":"c:objc(cs)MBMStyleImageRemoveUnused","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnused"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/styleimageremoveunusedcallback"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/styleimageremoveunusedcallback"]}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapRecorder","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeatureExtensionValue","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Size","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackError-swift.class","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestErrorType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapLoadingErrorTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRenderModeTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestDataSourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestErrorTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestLoadingMethodTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestPriorityTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestPriorityTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestResourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMResponseSourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMSourceDataLoadedTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStyleDataLoadedTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMTileStoreUsageModeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraChangedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GenericEventCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinishedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameStartedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequestCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceAddedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceRemovedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageMissingCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapIdleCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TransitionOptions-swift.class"],"title":"Symbols","generated":true,"anchor":"Symbols"}],"metadata":{"role":"symbol","externalID":"c:MBMStyleImageRemoveUnusedCallback.h@T@MBMStyleImageRemoveUnusedCallback","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StyleImageRemoveUnusedCallback","kind":"identifier"}],"symbolKind":"typealias","navigatorTitle":[{"kind":"identifier","text":"StyleImageRemoveUnusedCallback"}],"roleHeading":"Type Alias","modules":[{"name":"MapboxMaps"}],"title":"StyleImageRemoveUnusedCallback"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"An image requested by the "},{"code":"map","type":"codeVoice"},{"text":" through the ","type":"text"},{"type":"codeVoice","code":"StyleImageMissing"},{"type":"text","text":" event is no longer"},{"text":" ","type":"text"},{"text":"needed and can be removed using the ","type":"text"},{"code":"removeStyleImage","type":"codeVoice"},{"text":" method. The application can","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"decide whether the image should be kept or removed."}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMapsInternal"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleImageRemoveUnusedCallback":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StyleImageRemoveUnusedCallback"}],"abstract":[{"text":"An image requested by the ","type":"text"},{"type":"codeVoice","code":"map"},{"text":" through the ","type":"text"},{"type":"codeVoice","code":"StyleImageMissing"},{"text":" event is no longer","type":"text"},{"type":"text","text":" "},{"text":"needed and can be removed using the ","type":"text"},{"type":"codeVoice","code":"removeStyleImage"},{"text":" method. The application can","type":"text"},{"type":"text","text":" "},{"type":"text","text":"decide whether the image should be kept or removed."}],"title":"StyleImageRemoveUnusedCallback","role":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/styleimageremoveunusedcallback","navigatorTitle":[{"text":"StyleImageRemoveUnusedCallback","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnusedCallback","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoadedCallback":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"MapLoadedCallback","kind":"identifier"}],"abstract":[{"type":"text","text":"The style has been fully loaded, and the "},{"type":"codeVoice","code":"map"},{"text":" has rendered all visible tiles.","type":"text"},{"type":"text","text":" "},{"text":"The event will be emitted only once for the current style. If it is required to","type":"text"},{"type":"text","text":" "},{"type":"text","text":"continuously observe an event where all the necessary resources are loaded or rendered,"},{"type":"text","text":" "},{"text":"please check the following events: ","type":"text"},{"code":"MapIdle","type":"codeVoice"},{"text":", ","type":"text"},{"code":"StyleDataLoaded","type":"codeVoice"},{"type":"text","text":", and "},{"type":"codeVoice","code":"RenderFrameFinished"},{"type":"text","text":"."}],"title":"MapLoadedCallback","role":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/maploadedcallback","navigatorTitle":[{"text":"MapLoadedCallback","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadedCallback","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleImageMissingCallback":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StyleImageMissingCallback"}],"abstract":[{"type":"text","text":"A style needs an image that is missing from the sprite sheet. This event is"},{"type":"text","text":" "},{"text":"emitted when the ","type":"text"},{"type":"codeVoice","code":"map"},{"type":"text","text":" renders visible tiles, and one of the required images"},{"text":" ","type":"text"},{"text":"is missing in the sprite sheet. The event observer has to provide the missing","type":"text"},{"type":"text","text":" "},{"text":"image by calling the ","type":"text"},{"type":"codeVoice","code":"addStyleImage"},{"type":"text","text":" method."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"StyleImageMissingCallback"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageMissingCallback","title":"StyleImageMissingCallback","url":"\/documentation\/mapboxmaps\/styleimagemissingcallback","type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRequestDataSourceTypeToString(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBMRequestDataSourceTypeToString"},{"text":"(","kind":"text"},{"text":"RequestDataSourceType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMRequestDataSourceType"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"navigatorTitle":[{"text":"MBMRequestDataSourceTypeToString","kind":"identifier"}],"abstract":[],"title":"MBMRequestDataSourceTypeToString(_:)","role":"symbol","url":"\/documentation\/mapboxmaps\/mbmrequestdatasourcetypetostring(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestDataSourceTypeToString(_:)","type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","kind":"symbol","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMSourceDataLoadedTypeToString(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBMSourceDataLoadedTypeToString"},{"text":"(","kind":"text"},{"text":"SourceDataLoadedType","preciseIdentifier":"c:@E@MBMSourceDataLoadedType","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"navigatorTitle":[{"text":"MBMSourceDataLoadedTypeToString","kind":"identifier"}],"abstract":[],"title":"MBMSourceDataLoadedTypeToString(_:)","role":"symbol","url":"\/documentation\/mapboxmaps\/mbmsourcedataloadedtypetostring(_:)","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMSourceDataLoadedTypeToString(_:)","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePackError-swift.class":{"kind":"symbol","abstract":[{"type":"text","text":"Describes a style package load request error."}],"title":"StylePackError","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackError-swift.class","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StylePackError"}],"url":"\/documentation\/mapboxmaps\/stylepackerror-swift.class","role":"symbol","navigatorTitle":[{"text":"StylePackError","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","role":"collection","title":"MapboxMaps Documentation","abstract":[],"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceAddedCallback":{"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceAddedCallback"}],"navigatorTitle":[{"text":"SourceAddedCallback","kind":"identifier"}],"abstract":[{"text":"The source has been added with ","type":"text"},{"code":"addStyleSource","type":"codeVoice"},{"type":"text","text":" method."}],"title":"SourceAddedCallback","role":"symbol","url":"\/documentation\/mapboxmaps\/sourceaddedcallback","kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceAddedCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMStyleDataLoadedTypeToString(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBMStyleDataLoadedTypeToString"},{"text":"(","kind":"text"},{"text":"StyleDataLoadedType","preciseIdentifier":"c:@E@MBMStyleDataLoadedType","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"title":"MBMStyleDataLoadedTypeToString(_:)","role":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/mbmstyledataloadedtypetostring(_:)","navigatorTitle":[{"text":"MBMStyleDataLoadedTypeToString","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStyleDataLoadedTypeToString(_:)","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRequestResourceTypeToString(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"MBMRequestResourceTypeToString","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMRequestResourceType","text":"RequestResourceType"},{"kind":"text","text":") -> "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"abstract":[],"title":"MBMRequestResourceTypeToString(_:)","role":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/mbmrequestresourcetypetostring(_:)","navigatorTitle":[{"text":"MBMRequestResourceTypeToString","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestResourceTypeToString(_:)","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRequestErrorTypeToString(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBMRequestErrorTypeToString","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMRequestErrorType","text":"RequestErrorType"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"!","kind":"text"}],"abstract":[],"title":"MBMRequestErrorTypeToString(_:)","role":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/mbmrequesterrortypetostring(_:)","navigatorTitle":[{"text":"MBMRequestErrorTypeToString","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestErrorTypeToString(_:)","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TransitionOptions-swift.class":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TransitionOptions","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"TransitionOptions"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"transition options"},{"text":" controls timing for the interpolation between a transitionable style","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"property’s previous value and new value. These can be used to define the style default property"},{"text":" ","type":"text"},{"type":"text","text":"transition behavior. Also, any transitionable style property may also have its own "},{"type":"codeVoice","code":"-transition"},{"type":"text","text":" "},{"text":"property that defines specific transition timing for that specific layer property, overriding","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"the global transition values."}],"title":"TransitionOptions","role":"symbol","url":"\/documentation\/mapboxmaps\/transitionoptions-swift.class","kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TransitionOptions-swift.class"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapIdleCallback":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapIdleCallback"}],"navigatorTitle":[{"text":"MapIdleCallback","kind":"identifier"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"map"},{"text":" has entered the idle state. The ","type":"text"},{"type":"codeVoice","code":"map"},{"type":"text","text":" is idle when there are no ongoing"},{"text":" ","type":"text"},{"type":"text","text":"animations, transitions and the "},{"code":"map","type":"codeVoice"},{"text":" has rendered all requested non-volatile tiles","type":"text"},{"type":"text","text":" "},{"type":"text","text":"(e.g., live traffic tiles). The event will not be emitted if "},{"type":"codeVoice","code":"setUserAnimationInProgress"},{"text":" ","type":"text"},{"type":"text","text":"and \/ or "},{"type":"codeVoice","code":"setGestureInProgress"},{"type":"text","text":" is set to "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"title":"MapIdleCallback","role":"symbol","url":"\/documentation\/mapboxmaps\/mapidlecallback","kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapIdleCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMResponseSourceTypeToString(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"MBMResponseSourceTypeToString","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"ResponseSourceType","preciseIdentifier":"c:@E@MBMResponseSourceType"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"!"}],"abstract":[],"title":"MBMResponseSourceTypeToString(_:)","role":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/mbmresponsesourcetypetostring(_:)","navigatorTitle":[{"text":"MBMResponseSourceTypeToString","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMResponseSourceTypeToString(_:)","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FeatureExtensionValue":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FeatureExtensionValue","kind":"identifier"}],"abstract":[{"text":"A value or a collection of a feature extension.","type":"text"}],"title":"FeatureExtensionValue","role":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/featureextensionvalue","navigatorTitle":[{"text":"FeatureExtensionValue","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeatureExtensionValue","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMapsInternal":{"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMapsInternal","role":"collectionGroup","abstract":[{"type":"text","text":"Maps rendering SDK also known as GL-Native. These are for internal use only."}],"url":"\/documentation\/mapboxmaps\/coremapsinternal","type":"topic","title":"CoreMaps - Internal"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResourceRequestCallback":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ResourceRequestCallback","kind":"identifier"}],"navigatorTitle":[{"text":"ResourceRequestCallback","kind":"identifier"}],"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"ResourceRequest"},{"text":" event allows the application to observe resourcerequests","type":"text"},{"type":"text","text":" "},{"text":"made by a ","type":"text"},{"type":"codeVoice","code":"map"},{"text":" or ","type":"text"},{"type":"codeVoice","code":"map snapshotter"},{"text":" object.","type":"text"}],"title":"ResourceRequestCallback","role":"symbol","url":"\/documentation\/mapboxmaps\/resourcerequestcallback","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequestCallback","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleDataLoadedCallback":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StyleDataLoadedCallback","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"StyleDataLoadedCallback"}],"abstract":[{"text":"The style data has been loaded.","type":"text"}],"title":"StyleDataLoadedCallback","role":"symbol","url":"\/documentation\/mapboxmaps\/styledataloadedcallback","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedCallback","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderFrameStartedCallback":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RenderFrameStartedCallback","kind":"identifier"}],"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"map"},{"text":" started rendering a frame.","type":"text"}],"title":"RenderFrameStartedCallback","role":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/renderframestartedcallback","navigatorTitle":[{"kind":"identifier","text":"RenderFrameStartedCallback"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameStartedCallback","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceDataLoadedCallback":{"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"SourceDataLoadedCallback","kind":"identifier"}],"navigatorTitle":[{"text":"SourceDataLoadedCallback","kind":"identifier"}],"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"SourceDataLoaded"},{"text":" event is emitted when source data is loaded.","type":"text"}],"title":"SourceDataLoadedCallback","role":"symbol","url":"\/documentation\/mapboxmaps\/sourcedataloadedcallback","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedCallback","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Size":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Size","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Size","kind":"symbol","url":"\/documentation\/mapboxmaps\/size","abstract":[{"type":"text","text":"Size type."}],"navigatorTitle":[{"text":"Size","kind":"identifier"}],"title":"Size","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GenericEventCallback":{"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GenericEventCallback"}],"abstract":[{"type":"text","text":"Generic event for experimental events."}],"title":"GenericEventCallback","role":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/genericeventcallback","navigatorTitle":[{"text":"GenericEventCallback","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GenericEventCallback","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapRecorder":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MapRecorder","kind":"identifier"}],"abstract":[{"text":"MapRecorder provides functions to record and replay API calls of a Map instance.","type":"text"},{"type":"text","text":" "},{"text":"These recordings can be used to debug issues which requie multiple steps to reproduce.","type":"text"},{"text":" ","type":"text"},{"text":"Additionaly, playbacks can be used for performance testing custom scenarios.","type":"text"}],"title":"MapRecorder","role":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/maprecorder","navigatorTitle":[{"kind":"identifier","text":"MapRecorder"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapRecorder","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceRemovedCallback":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SourceRemovedCallback","kind":"identifier"}],"abstract":[{"type":"text","text":"The source has been removed with "},{"code":"removeStyleSource","type":"codeVoice"},{"type":"text","text":" method."}],"title":"SourceRemovedCallback","role":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/sourceremovedcallback","navigatorTitle":[{"kind":"identifier","text":"SourceRemovedCallback"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceRemovedCallback","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestErrorType":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RequestErrorType"}],"abstract":[{"type":"text","text":"The enumeration defines the error type that may occur during a resource request."}],"title":"RequestErrorType","role":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/requesterrortype","navigatorTitle":[{"kind":"identifier","text":"RequestErrorType"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestErrorType","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRequestLoadingMethodTypeToString(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBMRequestLoadingMethodTypeToString","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMRequestLoadingMethodType","text":"RequestLoadingMethodType"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MBMRequestLoadingMethodTypeToString"}],"abstract":[],"title":"MBMRequestLoadingMethodTypeToString(_:)","role":"symbol","url":"\/documentation\/mapboxmaps\/mbmrequestloadingmethodtypetostring(_:)","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestLoadingMethodTypeToString(_:)","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoadingErrorCallback":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapLoadingErrorCallback","kind":"identifier"}],"navigatorTitle":[{"text":"MapLoadingErrorCallback","kind":"identifier"}],"abstract":[{"type":"text","text":"Describes an error that has occurred while loading the "},{"code":"map","type":"codeVoice"},{"text":".","type":"text"}],"title":"MapLoadingErrorCallback","role":"symbol","url":"\/documentation\/mapboxmaps\/maploadingerrorcallback","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorCallback","type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraChangedCallback":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraChangedCallback","kind":"identifier"}],"navigatorTitle":[{"text":"CameraChangedCallback","kind":"identifier"}],"abstract":[{"type":"text","text":"This event is emitted whenever the visible viewport changes its size"},{"type":"text","text":" "},{"text":"due to the invocation of the ","type":"text"},{"type":"codeVoice","code":"setSize"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"setBounds"},{"text":" methods or when","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"the camera is modified by calling camera methods. The event is emitted"},{"type":"text","text":" "},{"type":"text","text":"synchronously so that an updated camera state can be fetched immediately."}],"title":"CameraChangedCallback","role":"symbol","url":"\/documentation\/mapboxmaps\/camerachangedcallback","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraChangedCallback","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleLoadedCallback":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StyleLoadedCallback","kind":"identifier"}],"navigatorTitle":[{"text":"StyleLoadedCallback","kind":"identifier"}],"abstract":[{"type":"text","text":"The requested style has been fully loaded, including specified sprite, and sources’ metadata."}],"title":"StyleLoadedCallback","role":"symbol","url":"\/documentation\/mapboxmaps\/styleloadedcallback","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleLoadedCallback","type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderFrameFinishedCallback":{"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"RenderFrameFinishedCallback","kind":"identifier"}],"navigatorTitle":[{"text":"RenderFrameFinishedCallback","kind":"identifier"}],"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"map"},{"text":" finished rendering a frame.","type":"text"}],"title":"RenderFrameFinishedCallback","role":"symbol","url":"\/documentation\/mapboxmaps\/renderframefinishedcallback","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinishedCallback","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleImageRemoveUnused":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"StyleImageRemoveUnused"}],"abstract":[{"text":"An image requested by the ","type":"text"},{"type":"codeVoice","code":"map"},{"type":"text","text":" through the "},{"code":"StyleImageMissing","type":"codeVoice"},{"type":"text","text":" event is no longer"},{"type":"text","text":" "},{"text":"needed and can be removed using the ","type":"text"},{"type":"codeVoice","code":"removeStyleImage"},{"text":" method. The application can","type":"text"},{"type":"text","text":" "},{"type":"text","text":"decide whether the image should be kept or removed."}],"kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/styleimageremoveunused","title":"StyleImageRemoveUnused","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnused","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"StyleImageRemoveUnused","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRequestPriorityTypeToString(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBMRequestPriorityTypeToString"},{"text":"(","kind":"text"},{"text":"RequestPriorityType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMRequestPriorityType"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}],"abstract":[],"title":"MBMRequestPriorityTypeToString(_:)","role":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/mbmrequestprioritytypetostring(_:)","navigatorTitle":[{"kind":"identifier","text":"MBMRequestPriorityTypeToString"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestPriorityTypeToString(_:)","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRenderModeTypeToString(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBMRenderModeTypeToString"},{"text":"(","kind":"text"},{"text":"RenderModeType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMRenderModeType"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}],"abstract":[],"title":"MBMRenderModeTypeToString(_:)","role":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/mbmrendermodetypetostring(_:)","navigatorTitle":[{"text":"MBMRenderModeTypeToString","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRenderModeTypeToString(_:)","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMMapLoadingErrorTypeToString(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"MBMMapLoadingErrorTypeToString","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@MBMMapLoadingErrorType","kind":"typeIdentifier","text":"MapLoadingErrorType"},{"kind":"text","text":") -> "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"!"}],"navigatorTitle":[{"text":"MBMMapLoadingErrorTypeToString","kind":"identifier"}],"abstract":[],"title":"MBMMapLoadingErrorTypeToString(_:)","role":"symbol","url":"\/documentation\/mapboxmaps\/mbmmaploadingerrortypetostring(_:)","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapLoadingErrorTypeToString(_:)","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMTileStoreUsageModeToString(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBMTileStoreUsageModeToString"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMTileStoreUsageMode","text":"TileStoreUsageMode"},{"kind":"text","text":") -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}],"navigatorTitle":[{"text":"MBMTileStoreUsageModeToString","kind":"identifier"}],"abstract":[],"title":"MBMTileStoreUsageModeToString(_:)","role":"symbol","url":"\/documentation\/mapboxmaps\/mbmtilestoreusagemodetostring(_:)","kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMTileStoreUsageModeToString(_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Type Alias","path":"\/metadata\/roleHeading","op":"replace"},{"value":"MBMStyleImageRemoveUnusedCallback","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"typealias"},{"value":[{"kind":"identifier","text":"MBMStyleImageRemoveUnusedCallback"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"MBMStyleImageRemoveUnusedCallback","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapRecorder","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeatureExtensionValue","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Size","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackError-swift.class","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestErrorType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapLoadingErrorTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRenderModeTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestDataSourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestErrorTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestLoadingMethodTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestPriorityTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestPriorityTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestResourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMResponseSourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMSourceDataLoadedTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStyleDataLoadedTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMTileStoreUsageModeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraChangedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GenericEventCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinishedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameStartedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequestCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceAddedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceRemovedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageMissingCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapIdleCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TransitionOptions-swift.class"],"title":"Symbols","generated":true,"anchor":"Symbols"}],"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"typedef"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:BFv(#*$objc(cs)MBMStyleImageRemoveUnused)","text":"void (^)(MBMStyleImageRemoveUnused *)","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"MBMStyleImageRemoveUnusedCallback","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnusedCallback\/title","value":"MBMStyleImageRemoveUnusedCallback"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnusedCallback\/fragments","value":[{"text":"MBMStyleImageRemoveUnusedCallback","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnusedCallback\/navigatorTitle","value":[{"kind":"identifier","text":"MBMStyleImageRemoveUnusedCallback"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadedCallback\/title","value":"MBMMapLoadedCallback","op":"replace"},{"op":"replace","value":[{"text":"MBMMapLoadedCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadedCallback\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadedCallback\/navigatorTitle","value":[{"kind":"identifier","text":"MBMMapLoadedCallback"}]},{"value":"MBMStyleImageMissingCallback","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageMissingCallback\/title"},{"value":[{"text":"MBMStyleImageMissingCallback","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageMissingCallback\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageMissingCallback\/navigatorTitle","value":[{"text":"MBMStyleImageMissingCallback","kind":"identifier"}]},{"value":"MBMRequestDataSourceTypeToString","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestDataSourceTypeToString(_:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestDataSourceTypeToString(_:)\/fragments","value":[{"kind":"identifier","text":"MBMRequestDataSourceTypeToString"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMSourceDataLoadedTypeToString(_:)\/title","value":"MBMSourceDataLoadedTypeToString","op":"replace"},{"value":[{"text":"MBMSourceDataLoadedTypeToString","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMSourceDataLoadedTypeToString(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackError-swift.class\/title","value":"MBMStylePackError","op":"replace"},{"value":[{"text":"MBMStylePackError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackError-swift.class\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackError-swift.class\/navigatorTitle","value":[{"text":"MBMStylePackError","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAddedCallback\/title","op":"replace","value":"MBMSourceAddedCallback"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAddedCallback\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMSourceAddedCallback"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAddedCallback\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMSourceAddedCallback"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMStyleDataLoadedTypeToString(_:)\/title","value":"MBMStyleDataLoadedTypeToString"},{"op":"replace","value":[{"text":"MBMStyleDataLoadedTypeToString","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMStyleDataLoadedTypeToString(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestResourceTypeToString(_:)\/title","op":"replace","value":"MBMRequestResourceTypeToString"},{"value":[{"text":"MBMRequestResourceTypeToString","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestResourceTypeToString(_:)\/fragments"},{"value":"MBMRequestErrorTypeToString","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestErrorTypeToString(_:)\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestErrorTypeToString(_:)\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMRequestErrorTypeToString"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TransitionOptions-swift.class\/title","value":"MBMTransitionOptions","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TransitionOptions-swift.class\/fragments","value":[{"kind":"identifier","text":"MBMTransitionOptions"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TransitionOptions-swift.class\/navigatorTitle","op":"replace","value":[{"text":"MBMTransitionOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdleCallback\/title","value":"MBMMapIdleCallback","op":"replace"},{"value":[{"kind":"identifier","text":"MBMMapIdleCallback"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdleCallback\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdleCallback\/navigatorTitle","value":[{"kind":"identifier","text":"MBMMapIdleCallback"}],"op":"replace"},{"value":"MBMResponseSourceTypeToString","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMResponseSourceTypeToString(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMResponseSourceTypeToString(_:)\/fragments","value":[{"text":"MBMResponseSourceTypeToString","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeatureExtensionValue\/title","value":"MBMFeatureExtensionValue"},{"op":"replace","value":[{"kind":"identifier","text":"MBMFeatureExtensionValue"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeatureExtensionValue\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeatureExtensionValue\/navigatorTitle","value":[{"text":"MBMFeatureExtensionValue","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequestCallback\/title","op":"replace","value":"MBMResourceRequestCallback"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequestCallback\/fragments","value":[{"kind":"identifier","text":"MBMResourceRequestCallback"}],"op":"replace"},{"value":[{"text":"MBMResourceRequestCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequestCallback\/navigatorTitle","op":"replace"},{"value":"MBMStyleDataLoadedCallback","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedCallback\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBMStyleDataLoadedCallback"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedCallback\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MBMStyleDataLoadedCallback"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedCallback\/navigatorTitle"},{"value":"MBMRenderFrameStartedCallback","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameStartedCallback\/title"},{"value":[{"text":"MBMRenderFrameStartedCallback","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameStartedCallback\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameStartedCallback\/navigatorTitle","op":"replace","value":[{"text":"MBMRenderFrameStartedCallback","kind":"identifier"}]},{"op":"replace","value":"MBMSourceDataLoadedCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedCallback\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedCallback\/fragments","value":[{"kind":"identifier","text":"MBMSourceDataLoadedCallback"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedCallback\/navigatorTitle","value":[{"text":"MBMSourceDataLoadedCallback","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Size\/title","op":"replace","value":"MBMSize"},{"value":[{"kind":"identifier","text":"MBMSize"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Size\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Size\/navigatorTitle","value":[{"kind":"identifier","text":"MBMSize"}],"op":"replace"},{"value":"MBMGenericEventCallback","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEventCallback\/title"},{"value":[{"text":"MBMGenericEventCallback","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEventCallback\/fragments"},{"value":[{"text":"MBMGenericEventCallback","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEventCallback\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapRecorder\/title","value":"MBMMapRecorder","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapRecorder\/fragments","value":[{"kind":"identifier","text":"MBMMapRecorder"}],"op":"replace"},{"value":[{"text":"MBMMapRecorder","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapRecorder\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceRemovedCallback\/title","op":"replace","value":"MBMSourceRemovedCallback"},{"value":[{"text":"MBMSourceRemovedCallback","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceRemovedCallback\/fragments"},{"value":[{"kind":"identifier","text":"MBMSourceRemovedCallback"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceRemovedCallback\/navigatorTitle"},{"value":"MBMRequestErrorType","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestErrorType\/title"},{"op":"replace","value":[{"text":"MBMRequestErrorType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestErrorType\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestErrorType\/navigatorTitle","op":"replace","value":[{"text":"MBMRequestErrorType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestLoadingMethodTypeToString(_:)\/title","value":"MBMRequestLoadingMethodTypeToString","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestLoadingMethodTypeToString(_:)\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMRequestLoadingMethodTypeToString"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorCallback\/title","op":"replace","value":"MBMMapLoadingErrorCallback"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorCallback\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMMapLoadingErrorCallback"}]},{"value":[{"text":"MBMMapLoadingErrorCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorCallback\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChangedCallback\/title","value":"MBMCameraChangedCallback","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChangedCallback\/fragments","value":[{"text":"MBMCameraChangedCallback","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChangedCallback\/navigatorTitle","value":[{"kind":"identifier","text":"MBMCameraChangedCallback"}]},{"value":"MBMStyleLoadedCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoadedCallback\/title","op":"replace"},{"value":[{"text":"MBMStyleLoadedCallback","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoadedCallback\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoadedCallback\/navigatorTitle","value":[{"kind":"identifier","text":"MBMStyleLoadedCallback"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinishedCallback\/title","value":"MBMRenderFrameFinishedCallback","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinishedCallback\/fragments","value":[{"text":"MBMRenderFrameFinishedCallback","kind":"identifier"}]},{"op":"replace","value":[{"text":"MBMRenderFrameFinishedCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinishedCallback\/navigatorTitle"},{"value":"MBMStyleImageRemoveUnused","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnused\/title"},{"value":[{"kind":"identifier","text":"MBMStyleImageRemoveUnused"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnused\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnused\/navigatorTitle","value":[{"text":"MBMStyleImageRemoveUnused","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestPriorityTypeToString(_:)\/title","value":"MBMRequestPriorityTypeToString"},{"op":"replace","value":[{"text":"MBMRequestPriorityTypeToString","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestPriorityTypeToString(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRenderModeTypeToString(_:)\/title","op":"replace","value":"MBMRenderModeTypeToString"},{"value":[{"text":"MBMRenderModeTypeToString","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRenderModeTypeToString(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMMapLoadingErrorTypeToString(_:)\/title","value":"MBMMapLoadingErrorTypeToString"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMMapLoadingErrorTypeToString(_:)\/fragments","value":[{"text":"MBMMapLoadingErrorTypeToString","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMTileStoreUsageModeToString(_:)\/title","value":"MBMTileStoreUsageModeToString","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMTileStoreUsageModeToString(_:)\/fragments","value":[{"text":"MBMTileStoreUsageModeToString","kind":"identifier"}],"op":"replace"}]}]}