{"seeAlsoSections":[{"title":"Layer Property Values","anchor":"Layer-Property-Values","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Value","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Anchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CirclePitchAlignment","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CirclePitchScale","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CircleTranslateAnchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillExtrusionTranslateAnchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillTranslateAnchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeIlluminationAnchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconAnchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconPitchAlignment","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconRotationAlignment","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconTextFit","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconTranslateAnchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineCap","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineJoin","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineTranslateAnchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterResampling","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResolvedImage","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResolvedImageData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValue","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValueKind","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SkyType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleTransition","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolPlacement","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolZOrder","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextAnchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextJustify","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextPitchAlignment","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextRotationAlignment","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextTransform","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextTranslateAnchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextWritingMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Visibility","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TransitionOptions-swift.struct","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelScaleMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolElevationReference","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageContent","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageStretches"]}],"abstract":[{"text":"Represents a color as defined by the ","type":"text"},{"isActive":true,"type":"reference","identifier":"https:\/\/docs.mapbox.com\/style-spec\/reference\/types\/#color"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer-Property-Values"]]},"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/Se","doc:\/\/com.mapbox.MapboxMaps\/SE","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/s43ExpressibleByExtendedGraphemeClusterLiteralP","doc:\/\/com.mapbox.MapboxMaps\/s32ExpressibleByStringInterpolationP","doc:\/\/com.mapbox.MapboxMaps\/s26ExpressibleByStringLiteralP","doc:\/\/com.mapbox.MapboxMaps\/s33ExpressibleByUnicodeScalarLiteralP","doc:\/\/com.mapbox.MapboxMaps\/SY","doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"],"type":"conformsTo","kind":"relationships"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StyleColor"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/stylecolor"]}],"kind":"symbol","topicSections":[{"title":"Initializers","anchor":"Initializers","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleColor\/init(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleColor\/init(from:)-8khx","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleColor\/init(hue:saturation:lightness:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleColor\/init(hue:saturation:lightness:alpha:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleColor\/init(rawValue:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleColor\/init(red:green:blue:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleColor\/init(red:green:blue:alpha:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleColor\/init(stringLiteral:)"]},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleColor\/rawValue"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true},{"generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleColor\/encode(to:)"],"title":"Instance Methods","anchor":"Instance-Methods"},{"anchor":"Default-Implementations","generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleColor\/Equatable-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleColor\/ExpressibleByExtendedGraphemeClusterLiteral-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleColor\/ExpressibleByStringInterpolation-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleColor\/ExpressibleByUnicodeScalarLiteral-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleColor\/RawRepresentable-Implementations"]}],"metadata":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StyleColor","kind":"identifier"}],"roleHeading":"Structure","externalID":"s:10MapboxMaps10StyleColorV","symbolKind":"struct","title":"StyleColor","navigatorTitle":[{"text":"StyleColor","kind":"identifier"}],"modules":[{"name":"MapboxMaps"}],"role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleColor"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TextAnchor":{"abstract":[{"text":"Part of the text placed closest to the anchor.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextAnchor","url":"\/documentation\/mapboxmaps\/textanchor","navigatorTitle":[{"kind":"identifier","text":"TextAnchor"}],"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"TextAnchor","kind":"identifier"}],"title":"TextAnchor","type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layer-Property-Values":{"role":"collectionGroup","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer-Property-Values","type":"topic","url":"\/documentation\/mapboxmaps\/layer-property-values","kind":"article","title":"Layer Property Values"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TextJustify":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"TextJustify","kind":"identifier"}],"title":"TextJustify","navigatorTitle":[{"text":"TextJustify","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextJustify","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Text justification options."}],"role":"symbol","url":"\/documentation\/mapboxmaps\/textjustify"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SymbolZOrder":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SymbolZOrder"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolZOrder","type":"topic","navigatorTitle":[{"text":"SymbolZOrder","kind":"identifier"}],"abstract":[{"text":"Determines whether overlapping symbols in the same layer are rendered in the order that they appear in the data source or by their y-position relative to the viewport. To control the order and prioritization of symbols otherwise, use ","type":"text"},{"type":"codeVoice","code":"symbol-sort-key"},{"text":".","type":"text"}],"role":"symbol","kind":"symbol","title":"SymbolZOrder","url":"\/documentation\/mapboxmaps\/symbolzorder"},"https://docs.mapbox.com/style-spec/reference/types/#color":{"identifier":"https:\/\/docs.mapbox.com\/style-spec\/reference\/types\/#color","type":"link","title":"Mapbox Style Spec","titleInlineContent":[{"type":"text","text":"Mapbox Style Spec"}],"url":"https:\/\/docs.mapbox.com\/style-spec\/reference\/types\/#color"},"doc://com.mapbox.MapboxMaps/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SY"},"doc://com.mapbox.MapboxMaps/s43ExpressibleByExtendedGraphemeClusterLiteralP":{"type":"unresolvable","title":"Swift.ExpressibleByExtendedGraphemeClusterLiteral","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s43ExpressibleByExtendedGraphemeClusterLiteralP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePropertyValue":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StylePropertyValue"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValue","type":"topic","navigatorTitle":[{"text":"StylePropertyValue","kind":"identifier"}],"abstract":[{"type":"text","text":"Holds a style property value with meta data."}],"role":"symbol","kind":"symbol","title":"StylePropertyValue","url":"\/documentation\/mapboxmaps\/stylepropertyvalue"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Value":{"abstract":[],"navigatorTitle":[{"text":"Value","kind":"identifier"}],"title":"Value","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Value","kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/value","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Value"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResolvedImageData":{"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResolvedImageData","url":"\/documentation\/mapboxmaps\/resolvedimagedata","navigatorTitle":[{"kind":"identifier","text":"ResolvedImageData"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ResolvedImageData"}],"title":"ResolvedImageData","type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TextTranslateAnchor":{"url":"\/documentation\/mapboxmaps\/texttranslateanchor","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"TextTranslateAnchor","kind":"identifier"}],"role":"symbol","title":"TextTranslateAnchor","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TextTranslateAnchor"}],"kind":"symbol","abstract":[{"type":"text","text":"Controls the frame of reference for "},{"code":"text-translate","type":"codeVoice"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextTranslateAnchor"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CirclePitchAlignment":{"title":"CirclePitchAlignment","abstract":[{"text":"Orientation of circle when map is pitched.","type":"text"}],"navigatorTitle":[{"text":"CirclePitchAlignment","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/circlepitchalignment","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"CirclePitchAlignment","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CirclePitchAlignment","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleColor/ExpressibleByStringInterpolation-Implementations":{"abstract":[],"url":"\/documentation\/mapboxmaps\/stylecolor\/expressiblebystringinterpolation-implementations","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleColor\/ExpressibleByStringInterpolation-Implementations","type":"topic","kind":"article","title":"ExpressibleByStringInterpolation Implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleColor/init(_:)":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleColor\/init(_:)","url":"\/documentation\/mapboxmaps\/stylecolor\/init(_:)","abstract":[{"text":"Creates a ","type":"text"},{"code":"StyleColor","type":"codeVoice"},{"text":" from a ","type":"text"},{"type":"codeVoice","code":"UIColor"}],"role":"symbol","title":"init(_:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"text":")","kind":"text"}]},"doc://com.mapbox.MapboxMaps/s32ExpressibleByStringInterpolationP":{"type":"unresolvable","title":"Swift.ExpressibleByStringInterpolation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s32ExpressibleByStringInterpolationP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleColor/rawValue":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleColor\/rawValue","url":"\/documentation\/mapboxmaps\/stylecolor\/rawvalue","abstract":[{"type":"text","text":"A color string as defined by the "},{"isActive":true,"type":"reference","identifier":"https:\/\/docs.mapbox.com\/style-spec\/reference\/types\/#color"},{"type":"text","text":"."}],"role":"symbol","kind":"symbol","title":"rawValue","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FillTranslateAnchor":{"abstract":[{"type":"text","text":"Controls the frame of reference for "},{"code":"fill-translate","type":"codeVoice"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillTranslateAnchor","url":"\/documentation\/mapboxmaps\/filltranslateanchor","navigatorTitle":[{"kind":"identifier","text":"FillTranslateAnchor"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FillTranslateAnchor"}],"title":"FillTranslateAnchor","type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/s33ExpressibleByUnicodeScalarLiteralP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s33ExpressibleByUnicodeScalarLiteralP","title":"Swift.ExpressibleByUnicodeScalarLiteral"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeIlluminationAnchor":{"abstract":[{"type":"text","text":"Direction of light source when map is rotated."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeIlluminationAnchor","url":"\/documentation\/mapboxmaps\/hillshadeilluminationanchor","navigatorTitle":[{"kind":"identifier","text":"HillshadeIlluminationAnchor"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"HillshadeIlluminationAnchor"}],"title":"HillshadeIlluminationAnchor","type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LineJoin":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LineJoin"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineJoin","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LineJoin"}],"abstract":[{"text":"The display of lines when joining.","type":"text"}],"role":"symbol","kind":"symbol","title":"LineJoin","url":"\/documentation\/mapboxmaps\/linejoin"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FillExtrusionTranslateAnchor":{"abstract":[{"type":"text","text":"Controls the frame of reference for "},{"type":"codeVoice","code":"fill-extrusion-translate"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillExtrusionTranslateAnchor","url":"\/documentation\/mapboxmaps\/fillextrusiontranslateanchor","navigatorTitle":[{"kind":"identifier","text":"FillExtrusionTranslateAnchor"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FillExtrusionTranslateAnchor"}],"title":"FillExtrusionTranslateAnchor","type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/IconAnchor":{"abstract":[{"type":"text","text":"Part of the icon placed closest to the anchor."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconAnchor","url":"\/documentation\/mapboxmaps\/iconanchor","navigatorTitle":[{"kind":"identifier","text":"IconAnchor"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"IconAnchor"}],"title":"IconAnchor","type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelScaleMode":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ModelScaleMode"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelScaleMode","type":"topic","navigatorTitle":[{"text":"ModelScaleMode","kind":"identifier"}],"abstract":[{"type":"text","text":"Defines scaling mode. Only applies to location-indicator type layers."}],"role":"symbol","kind":"symbol","title":"ModelScaleMode","url":"\/documentation\/mapboxmaps\/modelscalemode"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleColor/init(red:green:blue:alpha:)":{"fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"red","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"green"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"blue","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"text":", ","kind":"text"},{"text":"alpha","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"url":"\/documentation\/mapboxmaps\/stylecolor\/init(red:green:blue:alpha:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleColor\/init(red:green:blue:alpha:)","abstract":[{"type":"text","text":"Creates a "},{"type":"codeVoice","code":"StyleColor"},{"text":" from individually-provided color components. Returns nil","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"if any of the channel values are out of the supported ranges."}],"title":"init(red:green:blue:alpha:)","type":"topic","role":"symbol","kind":"symbol"},"doc://com.mapbox.MapboxMaps/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleColor/encode(to:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"encode","kind":"identifier"},{"kind":"text","text":"("},{"text":"to","kind":"externalParam"},{"kind":"text","text":": any "},{"text":"Encoder","kind":"typeIdentifier","preciseIdentifier":"s:s7EncoderP"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"url":"\/documentation\/mapboxmaps\/stylecolor\/encode(to:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleColor\/encode(to:)","abstract":[{"type":"codeVoice","code":"StyleColor"},{"text":" is always encoded to an rgba color string","type":"text"}],"title":"encode(to:)","type":"topic","role":"symbol","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ImageStretches":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ImageStretches","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageStretches","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageStretches"}],"abstract":[{"text":"Describes the image stretch areas.","type":"text"}],"role":"symbol","kind":"symbol","title":"ImageStretches","url":"\/documentation\/mapboxmaps\/imagestretches"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterResampling":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RasterResampling"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterResampling","type":"topic","navigatorTitle":[{"text":"RasterResampling","kind":"identifier"}],"abstract":[{"type":"text","text":"The resampling\/interpolation method to use for overscaling, also known as texture magnification filter"}],"role":"symbol","kind":"symbol","title":"RasterResampling","url":"\/documentation\/mapboxmaps\/rasterresampling"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TextPitchAlignment":{"abstract":[{"text":"Orientation of text when map is pitched.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextPitchAlignment","url":"\/documentation\/mapboxmaps\/textpitchalignment","navigatorTitle":[{"kind":"identifier","text":"TextPitchAlignment"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"TextPitchAlignment","kind":"identifier"}],"title":"TextPitchAlignment","type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/Se":{"title":"Swift.Decodable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/Se","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePropertyValueKind":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StylePropertyValueKind"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValueKind","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StylePropertyValueKind"}],"abstract":[{"type":"text","text":"Describes the kind of a style property value."}],"role":"symbol","kind":"symbol","title":"StylePropertyValueKind","url":"\/documentation\/mapboxmaps\/stylepropertyvaluekind"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Visibility":{"navigatorTitle":[{"kind":"identifier","text":"Visibility"}],"title":"Visibility","url":"\/documentation\/mapboxmaps\/visibility","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Visibility","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"Visibility","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TextRotationAlignment":{"abstract":[{"type":"text","text":"In combination with "},{"type":"codeVoice","code":"symbol-placement"},{"type":"text","text":", determines the rotation behavior of the individual glyphs forming the text."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextRotationAlignment","url":"\/documentation\/mapboxmaps\/textrotationalignment","navigatorTitle":[{"kind":"identifier","text":"TextRotationAlignment"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TextRotationAlignment"}],"title":"TextRotationAlignment","type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SkyType":{"navigatorTitle":[{"text":"SkyType","kind":"identifier"}],"type":"topic","abstract":[{"text":"The type of the sky","type":"text"}],"role":"symbol","title":"SkyType","url":"\/documentation\/mapboxmaps\/skytype","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SkyType","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"SkyType","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleColor/Equatable-Implementations":{"url":"\/documentation\/mapboxmaps\/stylecolor\/equatable-implementations","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleColor\/Equatable-Implementations","abstract":[],"title":"Equatable Implementations","type":"topic","role":"collectionGroup","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/IconTranslateAnchor":{"abstract":[{"type":"text","text":"Controls the frame of reference for "},{"code":"icon-translate","type":"codeVoice"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconTranslateAnchor","url":"\/documentation\/mapboxmaps\/icontranslateanchor","navigatorTitle":[{"text":"IconTranslateAnchor","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IconTranslateAnchor"}],"title":"IconTranslateAnchor","type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TextTransform":{"abstract":[{"type":"text","text":"Specifies how to capitalize text, similar to the CSS "},{"code":"text-transform","type":"codeVoice"},{"text":" property.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextTransform","url":"\/documentation\/mapboxmaps\/texttransform","navigatorTitle":[{"kind":"identifier","text":"TextTransform"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"TextTransform","kind":"identifier"}],"title":"TextTransform","type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleColor/init(red:green:blue:)":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleColor\/init(red:green:blue:)","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"red"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"green"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"blue","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"url":"\/documentation\/mapboxmaps\/stylecolor\/init(red:green:blue:)","abstract":[{"text":"Creates a ","type":"text"},{"code":"StyleColor","type":"codeVoice"},{"type":"text","text":" from individually-provided color components. Returns nil"},{"type":"text","text":" "},{"type":"text","text":"if any of the channel values are out of the supported ranges."}],"title":"init(red:green:blue:)","role":"symbol","kind":"symbol"},"doc://com.mapbox.MapboxMaps/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ImageContent":{"abstract":[{"text":"Describes the image content, e.g. where text can be fit into an image.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ImageContent","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ImageContent"}],"role":"symbol","kind":"symbol","title":"ImageContent","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageContent","url":"\/documentation\/mapboxmaps\/imagecontent"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleColor/init(hue:saturation:lightness:alpha:)":{"title":"init(hue:saturation:lightness:alpha:)","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleColor\/init(hue:saturation:lightness:alpha:)","url":"\/documentation\/mapboxmaps\/stylecolor\/init(hue:saturation:lightness:alpha:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"hue","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"text":"saturation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"lightness"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"alpha"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":")"}],"abstract":[{"text":"Creates a ","type":"text"},{"type":"codeVoice","code":"StyleColor"},{"type":"text","text":" from individually-provided color components. Returns nil"},{"type":"text","text":" "},{"type":"text","text":"if any of the channel values are out of the supported ranges."}],"type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SymbolElevationReference":{"title":"SymbolElevationReference","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SymbolElevationReference","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SymbolElevationReference"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolElevationReference","kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/symbolelevationreference","abstract":[{"type":"text","text":"Selects the base of symbol-elevation."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleColor/init(rawValue:)":{"type":"topic","role":"symbol","title":"init(rawValue:)","abstract":[{"type":"text","text":"Creates a "},{"type":"codeVoice","code":"StyleColor"},{"text":" from a color string as defined in the ","type":"text"},{"isActive":true,"type":"reference","identifier":"https:\/\/docs.mapbox.com\/style-spec\/reference\/types\/#color"},{"text":".","type":"text"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/stylecolor\/init(rawvalue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleColor\/init(rawValue:)"},"doc://com.mapbox.MapboxMaps/s26ExpressibleByStringLiteralP":{"title":"Swift.ExpressibleByStringLiteral","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s26ExpressibleByStringLiteralP","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","role":"collection","abstract":[],"type":"topic","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CircleTranslateAnchor":{"abstract":[{"type":"text","text":"Controls the frame of reference for "},{"type":"codeVoice","code":"circle-translate"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CircleTranslateAnchor","url":"\/documentation\/mapboxmaps\/circletranslateanchor","navigatorTitle":[{"kind":"identifier","text":"CircleTranslateAnchor"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"CircleTranslateAnchor","kind":"identifier"}],"title":"CircleTranslateAnchor","type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelType":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ModelType"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelType","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ModelType"}],"abstract":[{"type":"text","text":"Defines rendering behavior of model in respect to other 3D scene objects."}],"role":"symbol","kind":"symbol","title":"ModelType","url":"\/documentation\/mapboxmaps\/modeltype"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleTransition":{"title":"StyleTransition","url":"\/documentation\/mapboxmaps\/styletransition","abstract":[{"type":"text","text":"The transition property for a layer."},{"text":" ","type":"text"},{"text":"A transition property controls timing for the interpolation between a","type":"text"},{"type":"text","text":" "},{"type":"text","text":"transitionable style property’s previous value and new value."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleTransition","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"StyleTransition","kind":"identifier"}],"navigatorTitle":[{"text":"StyleTransition","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LineCap":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LineCap"}],"url":"\/documentation\/mapboxmaps\/linecap","abstract":[{"text":"The display of line endings.","type":"text"}],"role":"symbol","title":"LineCap","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineCap","kind":"symbol","type":"topic","navigatorTitle":[{"text":"LineCap","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/IconRotationAlignment":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IconRotationAlignment"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconRotationAlignment","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IconRotationAlignment"}],"abstract":[{"text":"In combination with ","type":"text"},{"type":"codeVoice","code":"symbol-placement"},{"text":", determines the rotation behavior of icons.","type":"text"}],"role":"symbol","kind":"symbol","title":"IconRotationAlignment","url":"\/documentation\/mapboxmaps\/iconrotationalignment"},"doc://com.mapbox.MapboxMaps/SE":{"title":"Swift.Encodable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SE","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleColor/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleColor\/RawRepresentable-Implementations","type":"topic","kind":"article","abstract":[],"role":"collectionGroup","url":"\/documentation\/mapboxmaps\/stylecolor\/rawrepresentable-implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/IconTextFit":{"abstract":[{"text":"Scales the icon to fit around the associated text.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconTextFit","url":"\/documentation\/mapboxmaps\/icontextfit","navigatorTitle":[{"text":"IconTextFit","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IconTextFit"}],"title":"IconTextFit","type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CirclePitchScale":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"CirclePitchScale","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CirclePitchScale","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CirclePitchScale"}],"abstract":[{"text":"Controls the scaling behavior of the circle when the map is pitched.","type":"text"}],"role":"symbol","kind":"symbol","title":"CirclePitchScale","url":"\/documentation\/mapboxmaps\/circlepitchscale"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleColor":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleColor","kind":"symbol","type":"topic","title":"StyleColor","role":"symbol","url":"\/documentation\/mapboxmaps\/stylecolor","navigatorTitle":[{"text":"StyleColor","kind":"identifier"}],"abstract":[{"type":"text","text":"Represents a color as defined by the "},{"type":"reference","isActive":true,"identifier":"https:\/\/docs.mapbox.com\/style-spec\/reference\/types\/#color"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StyleColor"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Anchor":{"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Anchor"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Anchor","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Anchor"}],"abstract":[{"type":"text","text":"Whether extruded geometries are lit relative to the map or viewport."}],"role":"symbol","kind":"symbol","title":"Anchor","url":"\/documentation\/mapboxmaps\/anchor"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleColor/ExpressibleByExtendedGraphemeClusterLiteral-Implementations":{"url":"\/documentation\/mapboxmaps\/stylecolor\/expressiblebyextendedgraphemeclusterliteral-implementations","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleColor\/ExpressibleByExtendedGraphemeClusterLiteral-Implementations","abstract":[],"title":"ExpressibleByExtendedGraphemeClusterLiteral Implementations","type":"topic","role":"collectionGroup","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleColor/init(stringLiteral:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"stringLiteral"},{"text":": ","kind":"text"},{"text":"StringLiteralType","kind":"typeIdentifier","preciseIdentifier":"s:s17StringLiteralTypea"},{"kind":"text","text":")"}],"type":"topic","title":"init(stringLiteral:)","role":"symbol","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleColor\/init(stringLiteral:)","url":"\/documentation\/mapboxmaps\/stylecolor\/init(stringliteral:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleColor/init(from:)-8khx":{"title":"init(from:)","kind":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":": any "},{"preciseIdentifier":"s:s7DecoderP","text":"Decoder","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"abstract":[{"type":"codeVoice","code":"StyleColor"},{"type":"text","text":" can be decoded from an rgba expression or from an rgba color string"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleColor\/init(from:)-8khx","role":"symbol","url":"\/documentation\/mapboxmaps\/stylecolor\/init(from:)-8khx"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleColor/init(hue:saturation:lightness:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"hue"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"saturation"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"text":"lightness","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/mapboxmaps\/stylecolor\/init(hue:saturation:lightness:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleColor\/init(hue:saturation:lightness:)","abstract":[{"type":"text","text":"Creates a "},{"code":"StyleColor","type":"codeVoice"},{"text":" from individually-provided color components. Returns nil","type":"text"},{"type":"text","text":" "},{"type":"text","text":"if any of the channel values are out of the supported ranges."}],"title":"init(hue:saturation:lightness:)","type":"topic","role":"symbol","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LineTranslateAnchor":{"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"LineTranslateAnchor","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/linetranslateanchor","abstract":[{"type":"text","text":"Controls the frame of reference for "},{"code":"line-translate","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","title":"LineTranslateAnchor","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineTranslateAnchor","type":"topic","kind":"symbol","navigatorTitle":[{"text":"LineTranslateAnchor","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/IconPitchAlignment":{"url":"\/documentation\/mapboxmaps\/iconpitchalignment","abstract":[{"type":"text","text":"Orientation of icon when map is pitched."}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"IconPitchAlignment"}],"type":"topic","navigatorTitle":[{"text":"IconPitchAlignment","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconPitchAlignment","title":"IconPitchAlignment","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResolvedImage":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ResolvedImage","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResolvedImage","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResolvedImage"}],"abstract":[],"role":"symbol","kind":"symbol","title":"ResolvedImage","url":"\/documentation\/mapboxmaps\/resolvedimage"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TextWritingMode":{"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TextWritingMode"}],"url":"\/documentation\/mapboxmaps\/textwritingmode","title":"TextWritingMode","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextWritingMode","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TextWritingMode"}],"abstract":[{"text":"The property allows control over a symbol’s orientation. Note that the property values act as a hint, so that a symbol whose language doesn’t support the provided orientation will be laid out in its natural orientation. Example: English point symbol will be rendered horizontally even if array value contains single ‘vertical’ enum value. For symbol with point placement, the order of elements in an array define priority order for the placement of an orientation variant. For symbol with line placement, the default text writing mode is either [‘horizontal’, ‘vertical’] or [‘vertical’, ‘horizontal’], the order doesn’t affect the placement.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SymbolPlacement":{"abstract":[{"text":"Label placement relative to its geometry.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolPlacement","url":"\/documentation\/mapboxmaps\/symbolplacement","navigatorTitle":[{"kind":"identifier","text":"SymbolPlacement"}],"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SymbolPlacement","kind":"identifier"}],"title":"SymbolPlacement","type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TransitionOptions-swift.struct":{"url":"\/documentation\/mapboxmaps\/transitionoptions-swift.struct","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TransitionOptions-swift.struct","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TransitionOptions","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"TransitionOptions"}],"title":"TransitionOptions","abstract":[{"type":"text","text":"The "},{"code":"TransitionOptions","type":"codeVoice"},{"type":"text","text":" control timing for the interpolation between a transitionable style"},{"type":"text","text":" "},{"type":"text","text":"property’s previous value and new value. These can be used to define the style default property"},{"text":" ","type":"text"},{"text":"transition behavior. Also, any transitionable style property may also have its own ","type":"text"},{"code":"-transition","type":"codeVoice"},{"type":"text","text":" "},{"type":"text","text":"property that defines specific transition timing for that specific layer property, overriding"},{"text":" ","type":"text"},{"type":"text","text":"the global transition values."}],"kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleColor/ExpressibleByUnicodeScalarLiteral-Implementations":{"url":"\/documentation\/mapboxmaps\/stylecolor\/expressiblebyunicodescalarliteral-implementations","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleColor\/ExpressibleByUnicodeScalarLiteral-Implementations","title":"ExpressibleByUnicodeScalarLiteral Implementations","kind":"article","role":"collectionGroup","type":"topic","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValue\/title","value":"MBMStylePropertyValue"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValue\/fragments","value":[{"text":"MBMStylePropertyValue","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValue\/navigatorTitle","value":[{"kind":"identifier","text":"MBMStylePropertyValue"}],"op":"replace"},{"op":"replace","value":"MBMImageStretches","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ImageStretches\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ImageStretches\/fragments","value":[{"kind":"identifier","text":"MBMImageStretches"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ImageStretches\/navigatorTitle","value":[{"text":"MBMImageStretches","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"MBMStylePropertyValueKind","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValueKind\/title"},{"value":[{"kind":"identifier","text":"MBMStylePropertyValueKind"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValueKind\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValueKind\/navigatorTitle","value":[{"text":"MBMStylePropertyValueKind","kind":"identifier"}],"op":"replace"},{"value":"MBMImageContent","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ImageContent\/title","op":"replace"},{"op":"replace","value":[{"text":"MBMImageContent","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ImageContent\/fragments"},{"value":[{"text":"MBMImageContent","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ImageContent\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}