{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer-Property-Values"]]},"topicSections":[{"title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValueKind\/constant","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValueKind\/expression","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValueKind\/transition","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValueKind\/undefined"],"anchor":"Enumeration-Cases"},{"title":"Initializers","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValueKind\/init(rawValue:)"],"anchor":"Initializers"},{"anchor":"Default-Implementations","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValueKind\/Equatable-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValueKind\/RawRepresentable-Implementations"],"title":"Default Implementations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/stylepropertyvaluekind"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/stylepropertyvaluekind"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValueKind"},"sections":[],"kind":"symbol","relationshipsSections":[{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/s15BitwiseCopyableP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH","doc:\/\/com.mapbox.MapboxMaps\/SY","doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:@E@MBMStylePropertyValueKind","title":"StylePropertyValueKind","roleHeading":"Enumeration","navigatorTitle":[{"kind":"identifier","text":"StylePropertyValueKind"}],"symbolKind":"enum","modules":[{"name":"MapboxMaps"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StylePropertyValueKind","kind":"identifier"}],"role":"symbol"},"seeAlsoSections":[{"title":"Layer Property Values","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Value","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Anchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CirclePitchAlignment","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CirclePitchScale","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CircleTranslateAnchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillExtrusionTranslateAnchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillTranslateAnchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeIlluminationAnchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconAnchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconPitchAlignment","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconRotationAlignment","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconTextFit","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconTranslateAnchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineCap","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineJoin","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineTranslateAnchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterResampling","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResolvedImage","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResolvedImageData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValue","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SkyType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleColor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleTransition","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolPlacement","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolZOrder","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextAnchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextJustify","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextPitchAlignment","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextRotationAlignment","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextTransform","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextTranslateAnchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextWritingMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Visibility","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TransitionOptions-swift.struct","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelScaleMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolElevationReference","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/BackgroundPitchAlignment","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillExtrusionBaseAlignment","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillExtrusionHeightAlignment","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillElevationReference","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineElevationReference","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineWidthUnit","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelElevationReference","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageContent","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageStretches"],"anchor":"Layer-Property-Values","generated":true}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StylePropertyValueKind","kind":"identifier"}]}],"kind":"declarations"}],"abstract":[{"text":"Describes the kind of a style property value.","type":"text"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelElevationReference":{"kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/modelelevationreference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelElevationReference","abstract":[{"text":"Selects the base of the model. Some modes might require precomputed elevation data in the tileset.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ModelElevationReference"}],"navigatorTitle":[{"kind":"identifier","text":"ModelElevationReference"}],"type":"topic","tags":[{"type":"spi","text":"SPI"}],"title":"ModelElevationReference"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePropertyValueKind/RawRepresentable-Implementations":{"kind":"article","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/stylepropertyvaluekind\/rawrepresentable-implementations","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValueKind\/RawRepresentable-Implementations","abstract":[],"type":"topic","title":"RawRepresentable Implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/IconTextFit":{"abstract":[{"type":"text","text":"Scales the icon to fit around the associated text."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconTextFit","kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/icontextfit","type":"topic","title":"IconTextFit","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IconTextFit"}],"navigatorTitle":[{"text":"IconTextFit","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","role":"collection","title":"MapboxMaps","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FillTranslateAnchor":{"kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/filltranslateanchor","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillTranslateAnchor","abstract":[{"text":"Controls the frame of reference for ","type":"text"},{"type":"codeVoice","code":"fill-translate"},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"FillTranslateAnchor","kind":"identifier"}],"navigatorTitle":[{"text":"FillTranslateAnchor","kind":"identifier"}],"type":"topic","title":"FillTranslateAnchor"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LineWidthUnit":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineWidthUnit","title":"LineWidthUnit","type":"topic","navigatorTitle":[{"text":"LineWidthUnit","kind":"identifier"}],"tags":[{"type":"spi","text":"SPI"}],"abstract":[{"text":"Selects the unit of line-width. The same unit is automatically used for line-blur and line-offset. Note: This is an experimental property and might be removed in a future release.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LineWidthUnit"}],"url":"\/documentation\/mapboxmaps\/linewidthunit"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelScaleMode":{"url":"\/documentation\/mapboxmaps\/modelscalemode","title":"ModelScaleMode","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelScaleMode","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ModelScaleMode","kind":"identifier"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ModelScaleMode"}],"abstract":[{"text":"Defines scaling mode. Only applies to location-indicator type layers.","type":"text"}],"tags":[{"type":"spi","text":"SPI"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePropertyValueKind/undefined":{"kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/stylepropertyvaluekind\/undefined","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValueKind\/undefined","abstract":[{"type":"text","text":"The property value is not defined."}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"undefined","kind":"identifier"}],"navigatorTitle":[{"text":"MBMStylePropertyValueKindUndefined","kind":"identifier"}],"type":"topic","title":"StylePropertyValueKind.undefined"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TextPitchAlignment":{"kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/textpitchalignment","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextPitchAlignment","abstract":[{"type":"text","text":"Orientation of text when map is pitched."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TextPitchAlignment","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"TextPitchAlignment"}],"type":"topic","title":"TextPitchAlignment"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Anchor":{"kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/anchor","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Anchor","abstract":[{"type":"text","text":"Whether extruded geometries are lit relative to the map or viewport."}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Anchor","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Anchor"}],"type":"topic","title":"Anchor"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/BackgroundPitchAlignment":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/BackgroundPitchAlignment","title":"BackgroundPitchAlignment","type":"topic","navigatorTitle":[{"text":"BackgroundPitchAlignment","kind":"identifier"}],"tags":[{"text":"SPI","type":"spi"}],"abstract":[{"type":"text","text":"Orientation of background layer."}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"BackgroundPitchAlignment","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/backgroundpitchalignment"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResolvedImage":{"type":"topic","abstract":[],"navigatorTitle":[{"text":"ResolvedImage","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResolvedImage","role":"symbol","title":"ResolvedImage","url":"\/documentation\/mapboxmaps\/resolvedimage","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ResolvedImage"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TextWritingMode":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextWritingMode","title":"TextWritingMode","navigatorTitle":[{"text":"TextWritingMode","kind":"identifier"}],"abstract":[{"type":"text","text":"The property allows control over a symbol’s orientation. Note that the property values act as a hint, so that a symbol whose language doesn’t support the provided orientation will be laid out in its natural orientation. Example: English point symbol will be rendered horizontally even if array value contains single ‘vertical’ enum value. For symbol with point placement, the order of elements in an array define priority order for the placement of an orientation variant. For symbol with line placement, the default text writing mode is either [‘horizontal’, ‘vertical’] or [‘vertical’, ‘horizontal’], the order doesn’t affect the placement."}],"kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"TextWritingMode","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/textwritingmode"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","kind":"article","abstract":[],"title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Visibility":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Visibility","type":"topic","title":"Visibility","navigatorTitle":[{"kind":"identifier","text":"Visibility"}],"abstract":[],"kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Visibility","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/visibility"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SkyType":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SkyType","title":"SkyType","type":"topic","navigatorTitle":[{"text":"SkyType","kind":"identifier"}],"abstract":[{"type":"text","text":"The type of the sky"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SkyType","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/skytype"},"https://docs.mapbox.com/style-spec/reference/types/#color":{"identifier":"https:\/\/docs.mapbox.com\/style-spec\/reference\/types\/#color","title":"Mapbox Style Spec","type":"link","titleInlineContent":[{"type":"text","text":"Mapbox Style Spec"}],"url":"https:\/\/docs.mapbox.com\/style-spec\/reference\/types\/#color"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CircleTranslateAnchor":{"url":"\/documentation\/mapboxmaps\/circletranslateanchor","title":"CircleTranslateAnchor","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CircleTranslateAnchor","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CircleTranslateAnchor"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CircleTranslateAnchor"}],"abstract":[{"text":"Controls the frame of reference for ","type":"text"},{"type":"codeVoice","code":"circle-translate"},{"type":"text","text":"."}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/IconTranslateAnchor":{"kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/icontranslateanchor","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconTranslateAnchor","abstract":[{"text":"Controls the frame of reference for ","type":"text"},{"code":"icon-translate","type":"codeVoice"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"IconTranslateAnchor","kind":"identifier"}],"navigatorTitle":[{"text":"IconTranslateAnchor","kind":"identifier"}],"type":"topic","title":"IconTranslateAnchor"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/IconPitchAlignment":{"kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/iconpitchalignment","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconPitchAlignment","abstract":[{"type":"text","text":"Orientation of icon when map is pitched."}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"IconPitchAlignment","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"IconPitchAlignment"}],"type":"topic","title":"IconPitchAlignment"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePropertyValueKind/Equatable-Implementations":{"abstract":[],"type":"topic","role":"collectionGroup","kind":"article","title":"Equatable Implementations","url":"\/documentation\/mapboxmaps\/stylepropertyvaluekind\/equatable-implementations","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValueKind\/Equatable-Implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LineElevationReference":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineElevationReference","title":"LineElevationReference","type":"topic","navigatorTitle":[{"text":"LineElevationReference","kind":"identifier"}],"tags":[{"type":"spi","text":"SPI"}],"abstract":[{"type":"text","text":"Selects the base of line-elevation. Some modes might require precomputed elevation data in the tileset."}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"LineElevationReference","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/lineelevationreference"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FillExtrusionTranslateAnchor":{"url":"\/documentation\/mapboxmaps\/fillextrusiontranslateanchor","title":"FillExtrusionTranslateAnchor","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillExtrusionTranslateAnchor","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"FillExtrusionTranslateAnchor","kind":"identifier"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"FillExtrusionTranslateAnchor","kind":"identifier"}],"abstract":[{"text":"Controls the frame of reference for ","type":"text"},{"type":"codeVoice","code":"fill-extrusion-translate"},{"text":".","type":"text"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResolvedImageData":{"kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/resolvedimagedata","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResolvedImageData","abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ResolvedImageData"}],"navigatorTitle":[{"text":"ResolvedImageData","kind":"identifier"}],"type":"topic","title":"ResolvedImageData"},"doc://com.mapbox.MapboxMaps/SH":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FillExtrusionHeightAlignment":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillExtrusionHeightAlignment","title":"FillExtrusionHeightAlignment","type":"topic","navigatorTitle":[{"text":"FillExtrusionHeightAlignment","kind":"identifier"}],"tags":[{"type":"spi","text":"SPI"}],"abstract":[{"text":"Controls the behavior of fill extrusion height over terrain","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FillExtrusionHeightAlignment"}],"url":"\/documentation\/mapboxmaps\/fillextrusionheightalignment"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TransitionOptions-swift.struct":{"abstract":[{"type":"text","text":"The "},{"code":"TransitionOptions","type":"codeVoice"},{"type":"text","text":" control timing for the interpolation between a transitionable style"},{"type":"text","text":" "},{"text":"property’s previous value and new value. These can be used to define the style default property","type":"text"},{"type":"text","text":" "},{"text":"transition behavior. Also, any transitionable style property may also have its own ","type":"text"},{"type":"codeVoice","code":"-transition"},{"text":" ","type":"text"},{"type":"text","text":"property that defines specific transition timing for that specific layer property, overriding"},{"text":" ","type":"text"},{"type":"text","text":"the global transition values."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TransitionOptions-swift.struct","kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/transitionoptions-swift.struct","type":"topic","title":"TransitionOptions","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"TransitionOptions","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"TransitionOptions"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layer-Property-Values":{"kind":"article","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/layer-property-values","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer-Property-Values","abstract":[],"type":"topic","title":"Layer Property Values"},"https://docs.mapbox.com/mapbox-gl-js/style-spec/#transition":{"identifier":"https:\/\/docs.mapbox.com\/mapbox-gl-js\/style-spec\/#transition","type":"link","title":"transition","titleInlineContent":[{"text":"transition","type":"text"}],"url":"https:\/\/docs.mapbox.com\/mapbox-gl-js\/style-spec\/#transition"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TextTransform":{"kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/texttransform","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextTransform","abstract":[{"type":"text","text":"Specifies how to capitalize text, similar to the CSS "},{"code":"text-transform","type":"codeVoice"},{"type":"text","text":" property."}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"TextTransform","kind":"identifier"}],"navigatorTitle":[{"text":"TextTransform","kind":"identifier"}],"type":"topic","title":"TextTransform"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleColor":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleColor","title":"StyleColor","type":"topic","navigatorTitle":[{"text":"StyleColor","kind":"identifier"}],"abstract":[{"text":"Represents a color as defined by the ","type":"text"},{"type":"reference","identifier":"https:\/\/docs.mapbox.com\/style-spec\/reference\/types\/#color","isActive":true}],"kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"StyleColor","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/stylecolor"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TextRotationAlignment":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextRotationAlignment","title":"TextRotationAlignment","type":"topic","navigatorTitle":[{"text":"TextRotationAlignment","kind":"identifier"}],"abstract":[{"text":"In combination with ","type":"text"},{"code":"symbol-placement","type":"codeVoice"},{"type":"text","text":", determines the rotation behavior of the individual glyphs forming the text."}],"kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"TextRotationAlignment","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/textrotationalignment"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CirclePitchAlignment":{"kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/circlepitchalignment","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CirclePitchAlignment","abstract":[{"text":"Orientation of circle when map is pitched.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CirclePitchAlignment"}],"navigatorTitle":[{"kind":"identifier","text":"CirclePitchAlignment"}],"type":"topic","title":"CirclePitchAlignment"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Value":{"role":"symbol","type":"topic","title":"Value","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"Value","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Value"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Value","url":"\/documentation\/mapboxmaps\/value","abstract":[],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/s8SendableP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelType":{"kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/modeltype","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelType","abstract":[{"type":"text","text":"Defines rendering behavior of model in respect to other 3D scene objects."}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ModelType"}],"navigatorTitle":[{"text":"ModelType","kind":"identifier"}],"type":"topic","tags":[{"type":"spi","text":"SPI"}],"title":"ModelType"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeIlluminationAnchor":{"kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/hillshadeilluminationanchor","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeIlluminationAnchor","abstract":[{"type":"text","text":"Direction of light source when map is rotated."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HillshadeIlluminationAnchor"}],"navigatorTitle":[{"text":"HillshadeIlluminationAnchor","kind":"identifier"}],"type":"topic","title":"HillshadeIlluminationAnchor"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FillElevationReference":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillElevationReference","type":"topic","title":"FillElevationReference","navigatorTitle":[{"text":"FillElevationReference","kind":"identifier"}],"tags":[{"type":"spi","text":"SPI"}],"abstract":[{"text":"Selects the base of fill-elevation. Some modes might require precomputed elevation data in the tileset.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FillElevationReference","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/fillelevationreference"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePropertyValueKind/expression":{"url":"\/documentation\/mapboxmaps\/stylepropertyvaluekind\/expression","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"expression","kind":"identifier"}],"title":"StylePropertyValueKind.expression","role":"symbol","navigatorTitle":[{"text":"MBMStylePropertyValueKindExpression","kind":"identifier"}],"abstract":[{"text":"The property value is a style ","type":"text"},{"identifier":"https:\/\/docs.mapbox.com\/mapbox-gl-js\/style-spec\/#expressions","type":"reference","isActive":true},{"text":".","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValueKind\/expression","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TextTranslateAnchor":{"kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/texttranslateanchor","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextTranslateAnchor","abstract":[{"text":"Controls the frame of reference for ","type":"text"},{"type":"codeVoice","code":"text-translate"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"TextTranslateAnchor","kind":"identifier"}],"navigatorTitle":[{"text":"TextTranslateAnchor","kind":"identifier"}],"type":"topic","title":"TextTranslateAnchor"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CirclePitchScale":{"url":"\/documentation\/mapboxmaps\/circlepitchscale","title":"CirclePitchScale","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CirclePitchScale","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"CirclePitchScale","kind":"identifier"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"CirclePitchScale","kind":"identifier"}],"abstract":[{"text":"Controls the scaling behavior of the circle when the map is pitched.","type":"text"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePropertyValueKind":{"kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/stylepropertyvaluekind","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValueKind","abstract":[{"type":"text","text":"Describes the kind of a style property value."}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"StylePropertyValueKind","kind":"identifier"}],"navigatorTitle":[{"text":"StylePropertyValueKind","kind":"identifier"}],"type":"topic","title":"StylePropertyValueKind"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/IconAnchor":{"kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/iconanchor","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconAnchor","abstract":[{"text":"Part of the icon placed closest to the anchor.","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"IconAnchor","kind":"identifier"}],"navigatorTitle":[{"text":"IconAnchor","kind":"identifier"}],"type":"topic","title":"IconAnchor"},"doc://com.mapbox.MapboxMaps/SY":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePropertyValue":{"kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/stylepropertyvalue","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValue","abstract":[{"type":"text","text":"Holds a style property value with meta data."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StylePropertyValue"}],"navigatorTitle":[{"kind":"identifier","text":"StylePropertyValue"}],"type":"topic","title":"StylePropertyValue"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ImageContent":{"kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/imagecontent","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageContent","abstract":[{"type":"text","text":"Describes the image content, e.g. where text can be fit into an image."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ImageContent","kind":"identifier"}],"navigatorTitle":[{"text":"ImageContent","kind":"identifier"}],"type":"topic","title":"ImageContent"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleTransition":{"kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/styletransition","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleTransition","abstract":[{"type":"text","text":"The transition property for a layer."},{"type":"text","text":" "},{"text":"A transition property controls timing for the interpolation between a","type":"text"},{"type":"text","text":" "},{"type":"text","text":"transitionable style property’s previous value and new value."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StyleTransition"}],"navigatorTitle":[{"text":"StyleTransition","kind":"identifier"}],"type":"topic","title":"StyleTransition"},"https://docs.mapbox.com/mapbox-gl-js/style-spec/#expressions":{"identifier":"https:\/\/docs.mapbox.com\/mapbox-gl-js\/style-spec\/#expressions","title":"expression","type":"link","titleInlineContent":[{"type":"text","text":"expression"}],"url":"https:\/\/docs.mapbox.com\/mapbox-gl-js\/style-spec\/#expressions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LineCap":{"kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/linecap","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineCap","abstract":[{"text":"The display of line endings.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LineCap"}],"navigatorTitle":[{"text":"LineCap","kind":"identifier"}],"type":"topic","title":"LineCap"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TextJustify":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextJustify","title":"TextJustify","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TextJustify"}],"abstract":[{"type":"text","text":"Text justification options."}],"kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TextJustify","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/textjustify"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LineTranslateAnchor":{"kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/linetranslateanchor","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineTranslateAnchor","abstract":[{"type":"text","text":"Controls the frame of reference for "},{"type":"codeVoice","code":"line-translate"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"LineTranslateAnchor","kind":"identifier"}],"navigatorTitle":[{"text":"LineTranslateAnchor","kind":"identifier"}],"type":"topic","title":"LineTranslateAnchor"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ImageStretches":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageStretches","type":"topic","title":"ImageStretches","navigatorTitle":[{"text":"ImageStretches","kind":"identifier"}],"abstract":[{"type":"text","text":"Describes the image stretch areas."}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageStretches","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/imagestretches"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/IconRotationAlignment":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconRotationAlignment","title":"IconRotationAlignment","type":"topic","navigatorTitle":[{"text":"IconRotationAlignment","kind":"identifier"}],"abstract":[{"type":"text","text":"In combination with "},{"code":"symbol-placement","type":"codeVoice"},{"type":"text","text":", determines the rotation behavior of icons."}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"IconRotationAlignment","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/iconrotationalignment"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePropertyValueKind/constant":{"title":"StylePropertyValueKind.constant","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValueKind\/constant","type":"topic","url":"\/documentation\/mapboxmaps\/stylepropertyvaluekind\/constant","navigatorTitle":[{"kind":"identifier","text":"MBMStylePropertyValueKindConstant"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"constant"}],"abstract":[{"type":"text","text":"The property value is a constant."}],"role":"symbol","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePropertyValueKind/init(rawValue:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValueKind\/init(rawValue:)","abstract":[],"title":"init(rawValue:)","role":"symbol","kind":"symbol","url":"\/documentation\/mapboxmaps\/stylepropertyvaluekind\/init(rawvalue:)","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FillExtrusionBaseAlignment":{"kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/fillextrusionbasealignment","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillExtrusionBaseAlignment","abstract":[{"text":"Controls the behavior of fill extrusion base over terrain","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FillExtrusionBaseAlignment"}],"navigatorTitle":[{"text":"FillExtrusionBaseAlignment","kind":"identifier"}],"type":"topic","tags":[{"type":"spi","text":"SPI"}],"title":"FillExtrusionBaseAlignment"},"doc://com.mapbox.MapboxMaps/s15BitwiseCopyableP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s15BitwiseCopyableP","type":"unresolvable","title":"Swift.BitwiseCopyable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SymbolPlacement":{"kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/symbolplacement","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolPlacement","abstract":[{"type":"text","text":"Label placement relative to its geometry."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SymbolPlacement","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SymbolPlacement"}],"type":"topic","title":"SymbolPlacement"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SymbolElevationReference":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolElevationReference","title":"SymbolElevationReference","type":"topic","navigatorTitle":[{"text":"SymbolElevationReference","kind":"identifier"}],"tags":[{"type":"spi","text":"SPI"}],"abstract":[{"type":"text","text":"Selects the base of symbol-elevation."}],"kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SymbolElevationReference"}],"url":"\/documentation\/mapboxmaps\/symbolelevationreference"},"doc://com.mapbox.MapboxMaps/SQ":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LineJoin":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineJoin","title":"LineJoin","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LineJoin"}],"abstract":[{"type":"text","text":"The display of lines when joining."}],"kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LineJoin"}],"url":"\/documentation\/mapboxmaps\/linejoin"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TextAnchor":{"kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/textanchor","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextAnchor","abstract":[{"text":"Part of the text placed closest to the anchor.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"TextAnchor","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"TextAnchor"}],"type":"topic","title":"TextAnchor"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePropertyValueKind/transition":{"type":"topic","abstract":[{"type":"text","text":"Property value is a style "},{"type":"reference","isActive":true,"identifier":"https:\/\/docs.mapbox.com\/mapbox-gl-js\/style-spec\/#transition"},{"text":".","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValueKind\/transition","kind":"symbol","url":"\/documentation\/mapboxmaps\/stylepropertyvaluekind\/transition","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"transition"}],"navigatorTitle":[{"kind":"identifier","text":"MBMStylePropertyValueKindTransition"}],"title":"StylePropertyValueKind.transition"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterResampling":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterResampling","title":"RasterResampling","navigatorTitle":[{"kind":"identifier","text":"RasterResampling"}],"abstract":[{"text":"The resampling\/interpolation method to use for overscaling, also known as texture magnification filter","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"RasterResampling","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/rasterresampling"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SymbolZOrder":{"abstract":[{"text":"Determines whether overlapping symbols in the same layer are rendered in the order that they appear in the data source or by their y-position relative to the viewport. To control the order and prioritization of symbols otherwise, use ","type":"text"},{"type":"codeVoice","code":"symbol-sort-key"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolZOrder","kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/symbolzorder","type":"topic","title":"SymbolZOrder","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SymbolZOrder","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SymbolZOrder"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"MBMStylePropertyValueKind"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"MBMStylePropertyValueKind","kind":"identifier"}]},{"value":[{"text":"MBMStylePropertyValueKind","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValueKind\/constant","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValueKind\/expression","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValueKind\/transition","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValueKind\/undefined"],"anchor":"Enumeration-Cases"}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"value":[{"generated":true,"title":"Layer Property Values","anchor":"Layer-Property-Values","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValue","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageContent","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageStretches"]}],"op":"replace","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBMStylePropertyValueKind"},{"kind":"text","text":": "},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}]}]}},{"value":"MBMStylePropertyValueKindUndefined","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValueKind~1undefined\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValueKind~1undefined\/fragments","op":"replace","value":[{"text":"MBMStylePropertyValueKindUndefined","kind":"identifier"}]},{"value":"MBMStylePropertyValueKindExpression","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValueKind~1expression\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValueKind~1expression\/fragments","op":"replace","value":[{"text":"MBMStylePropertyValueKindExpression","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValueKind\/title","value":"MBMStylePropertyValueKind"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValueKind\/fragments","value":[{"kind":"identifier","text":"MBMStylePropertyValueKind"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValueKind\/navigatorTitle","value":[{"text":"MBMStylePropertyValueKind","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValue\/title","value":"MBMStylePropertyValue","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValue\/fragments","value":[{"text":"MBMStylePropertyValue","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MBMStylePropertyValue"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValue\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ImageContent\/title","value":"MBMImageContent"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ImageContent\/fragments","value":[{"text":"MBMImageContent","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ImageContent\/navigatorTitle","op":"replace","value":[{"text":"MBMImageContent","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ImageStretches\/title","value":"MBMImageStretches"},{"op":"replace","value":[{"text":"MBMImageStretches","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ImageStretches\/fragments"},{"value":[{"text":"MBMImageStretches","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ImageStretches\/navigatorTitle","op":"replace"},{"op":"replace","value":"MBMStylePropertyValueKindConstant","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValueKind~1constant\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValueKind~1constant\/fragments","op":"replace","value":[{"text":"MBMStylePropertyValueKindConstant","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValueKind~1transition\/title","value":"MBMStylePropertyValueKindTransition","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValueKind~1transition\/fragments","op":"replace","value":[{"text":"MBMStylePropertyValueKindTransition","kind":"identifier"}]}]}]}