{"seeAlsoSections":[{"generated":true,"anchor":"TileStore","title":"TileStore","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStoreOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudget","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInMegabytes","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInTiles","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCoverOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegion","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileRegionError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgress","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TilesetDescriptor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TilesetDescriptorOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgressCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreUsageMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileRegionError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileDataDomain","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgress","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateResult","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgressCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingErrorType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClearCacheError"]}],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreObserver\/onRegionGeometryChanged(forId:geometry:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreObserver\/onRegionLoadFinished(forId:region:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreObserver\/onRegionLoadProgress(forId:progress:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreObserver\/onRegionMetadataChanged(forId:value:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreObserver\/onRegionRemoved(forId:)"],"anchor":"Instance-Methods","generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileStoreObserver","kind":"identifier"},{"text":" : AnyObject","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/mapboxmaps\/tilestoreobserver"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs"]]},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreObserver","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"TileStoreObserver","navigatorTitle":[{"kind":"identifier","text":"TileStoreObserver"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileStoreObserver","kind":"identifier"}],"roleHeading":"Protocol","role":"symbol","modules":[{"name":"MapboxMaps"}],"symbolKind":"protocol","externalID":"s:10MapboxMaps17TileStoreObserverP"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","kind":"article","url":"\/documentation\/mapboxmaps\/tilestore-apis","title":"TileStore APIs","role":"collectionGroup","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","role":"collection","url":"\/documentation\/mapboxmaps","kind":"symbol","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudgetInMegabytes":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInMegabytes","role":"symbol","abstract":[{"text":"Tile cache budget in megabytes.","type":"text"}],"type":"topic","url":"\/documentation\/mapboxmaps\/tilecachebudgetinmegabytes","kind":"symbol","title":"TileCacheBudgetInMegabytes","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TileCacheBudgetInMegabytes"}],"navigatorTitle":[{"kind":"identifier","text":"TileCacheBudgetInMegabytes"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStoreObserver/onRegionLoadProgress(forId:progress:)":{"title":"onRegionLoadProgress(forId:progress:)","abstract":[{"type":"text","text":"Called whenever the load progress of a "},{"type":"codeVoice","code":"TileRegion"},{"text":" changes.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onRegionLoadProgress"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"progress"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MBXTileRegionLoadProgress","text":"TileRegionLoadProgress","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreObserver\/onRegionLoadProgress(forId:progress:)","role":"symbol","kind":"symbol","url":"\/documentation\/mapboxmaps\/tilestoreobserver\/onregionloadprogress(forid:progress:)","required":true},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileStoreOptions":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileStoreOptions","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/tilestoreoptions","navigatorTitle":[{"text":"TileStoreOptions","kind":"identifier"}],"abstract":[{"text":"These constants can be used as keys for TileStore::setOption to configure further aspects of a TileStore instance.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStoreOptions","kind":"symbol","type":"topic","title":"TileStoreOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStoreObserver/onRegionRemoved(forId:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onRegionRemoved"},{"kind":"text","text":"("},{"text":"forId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"required":true,"role":"symbol","url":"\/documentation\/mapboxmaps\/tilestoreobserver\/onregionremoved(forid:)","kind":"symbol","abstract":[{"type":"text","text":"Called when a "},{"code":"TileRegion","type":"codeVoice"},{"text":" was removed.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreObserver\/onRegionRemoved(forId:)","title":"onRegionRemoved(forId:)","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateProgressCallback":{"role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileRegionEstimateProgressCallback","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/tileregionestimateprogresscallback","navigatorTitle":[{"text":"TileRegionEstimateProgressCallback","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgressCallback","kind":"symbol","type":"topic","title":"TileRegionEstimateProgressCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudgetType":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetType","role":"symbol","abstract":[],"type":"topic","url":"\/documentation\/mapboxmaps\/tilecachebudgettype","kind":"symbol","title":"TileCacheBudgetType","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TileCacheBudgetType"}],"navigatorTitle":[{"text":"TileCacheBudgetType","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateOptions":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TileRegionEstimateOptions","kind":"identifier"}],"title":"TileRegionEstimateOptions","navigatorTitle":[{"text":"TileRegionEstimateOptions","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateOptions","url":"\/documentation\/mapboxcommon\/tileregionestimateoptions","kind":"symbol","abstract":[{"text":"Holds options for the tile region estimation operation.","type":"text"}],"role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileStore":{"abstract":[{"text":"TileStore manages downloads and storage for requests to tile-related API endpoints, enforcing a disk usage","type":"text"},{"type":"text","text":" "},{"type":"text","text":"quota: tiles available on disk may be deleted to make room for a new download. This interface can be used by an"},{"type":"text","text":" "},{"type":"text","text":"app developer to set the disk quota. The rest of TileStore API is intended for native SDK consumption only."}],"kind":"symbol","title":"TileStore","navigatorTitle":[{"kind":"identifier","text":"TileStore"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TileStore"}],"url":"\/documentation\/mapboxcommon\/tilestore","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","title":"MapboxMaps Documentation","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TilesetDescriptorOptions":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TilesetDescriptorOptions","navigatorTitle":[{"text":"TilesetDescriptorOptions","kind":"identifier"}],"abstract":[{"text":"Describes the tileset descriptor option values.","type":"text"}],"title":"TilesetDescriptorOptions","type":"topic","url":"\/documentation\/mapboxmaps\/tilesetdescriptoroptions","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TilesetDescriptorOptions"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStoreObserver":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"TileStoreObserver","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/tilestoreobserver","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TileStoreObserver"}],"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreObserver","title":"TileStoreObserver","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadProgress":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TileRegionLoadProgress"}],"title":"TileRegionLoadProgress","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgress","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TileRegionLoadProgress"}],"abstract":[{"type":"text","text":"A tile region’s load progress includes counts"},{"text":" ","type":"text"},{"type":"text","text":"of the number of resources that have completed downloading"},{"text":" ","type":"text"},{"type":"text","text":"and the total number of resources that are required."}],"url":"\/documentation\/mapboxcommon\/tileregionloadprogress","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStoreObserver/onRegionMetadataChanged(forId:value:)":{"abstract":[{"type":"text","text":"Called when the user-provided metadata associated with a "},{"type":"codeVoice","code":"TileRegion"},{"text":" was changed.","type":"text"}],"required":true,"title":"onRegionMetadataChanged(forId:value:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreObserver\/onRegionMetadataChanged(forId:value:)","kind":"symbol","url":"\/documentation\/mapboxmaps\/tilestoreobserver\/onregionmetadatachanged(forid:value:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onRegionMetadataChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"value","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Any","kind":"keyword"},{"text":")","kind":"text"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStoreObserver/onRegionLoadFinished(forId:region:)":{"type":"topic","abstract":[{"text":"Called when a ","type":"text"},{"type":"codeVoice","code":"TileRegion"},{"type":"text","text":" load finishes."}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreObserver\/onRegionLoadFinished(forId:region:)","url":"\/documentation\/mapboxmaps\/tilestoreobserver\/onregionloadfinished(forid:region:)","kind":"symbol","title":"onRegionLoadFinished(forId:region:)","required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onRegionLoadFinished"},{"kind":"text","text":"("},{"text":"forId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"region"},{"text":": ","kind":"text"},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"text":"<","kind":"text"},{"text":"TileRegion","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXTileRegion"},{"kind":"text","text":", any "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":">)"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStoreUsageMode":{"role":"symbol","title":"TileStoreUsageMode","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileStoreUsageMode"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreUsageMode","abstract":[{"text":"Describes tile store usage modes.","type":"text"}],"url":"\/documentation\/mapboxmaps\/tilestoreusagemode","navigatorTitle":[{"kind":"identifier","text":"TileStoreUsageMode"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStoreObserver/onRegionGeometryChanged(forId:geometry:)":{"title":"onRegionGeometryChanged(forId:geometry:)","required":true,"url":"\/documentation\/mapboxmaps\/tilestoreobserver\/onregiongeometrychanged(forid:geometry:)","abstract":[{"text":"Called when the geometry of a ","type":"text"},{"code":"TileRegion","type":"codeVoice"},{"text":" was modified.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreObserver\/onRegionGeometryChanged(forId:geometry:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onRegionGeometryChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"geometry","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10MapboxMaps8Geometrya","kind":"typeIdentifier","text":"Geometry"},{"text":"?)","kind":"text"}],"role":"symbol","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ClearCacheError":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ClearCacheError"}],"url":"\/documentation\/mapboxmaps\/clearcacheerror","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClearCacheError","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Describes the reason for a cache clearing failure."}],"title":"ClearCacheError","navigatorTitle":[{"text":"ClearCacheError","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateProgress":{"abstract":[{"type":"text","text":"A tile region’s estimate progress includes counts of the number of resources that have"},{"text":" ","type":"text"},{"type":"text","text":"been estimated and the total number of resources as well as a partial result with the"},{"text":" ","type":"text"},{"text":"current estimate, calculated using the data available at the moment.","type":"text"}],"type":"topic","title":"TileRegionEstimateProgress","url":"\/documentation\/mapboxcommon\/tileregionestimateprogress","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgress","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TileRegionEstimateProgress"}],"role":"symbol","navigatorTitle":[{"text":"TileRegionEstimateProgress","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCoverOptions":{"title":"TileCoverOptions","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"TileCoverOptions","kind":"identifier"}],"abstract":[{"text":"Various options needed for tile cover.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"TileCoverOptions","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCoverOptions","kind":"symbol","url":"\/documentation\/mapboxmaps\/tilecoveroptions","tags":[{"text":"SPI","type":"spi"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileDataDomain":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileDataDomain","kind":"identifier"}],"title":"TileDataDomain","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileDataDomain","role":"symbol","type":"topic","kind":"symbol","abstract":[{"text":"Describes the tiles data domain.","type":"text"}],"navigatorTitle":[{"text":"TileDataDomain","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/tiledatadomain"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/CacheClearingError":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CacheClearingError","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapboxcommon\/cacheclearingerror","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CacheClearingError"}],"abstract":[{"text":"Describes a cache clearing error.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingError","title":"CacheClearingError","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileOptions":{"title":"TileOptions","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TileOptions","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileOptions","abstract":[{"text":"Options for custom geometry tiles.","type":"text"}],"url":"\/documentation\/mapboxmaps\/tileoptions","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TileOptions"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadOptions":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TileRegionLoadOptions","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions","navigatorTitle":[{"kind":"identifier","text":"TileRegionLoadOptions"}],"abstract":[{"type":"text","text":"Describes the tile region load option values."}],"url":"\/documentation\/mapboxcommon\/tileregionloadoptions","title":"TileRegionLoadOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudgetInTiles":{"kind":"symbol","role":"symbol","abstract":[{"text":"Tile cache budget in tiles.","type":"text"}],"type":"topic","url":"\/documentation\/mapboxmaps\/tilecachebudgetintiles","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInTiles","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileCacheBudgetInTiles","kind":"identifier"}],"title":"TileCacheBudgetInTiles","navigatorTitle":[{"text":"TileCacheBudgetInTiles","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadProgressCallback":{"role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileRegionLoadProgressCallback","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/tileregionloadprogresscallback","navigatorTitle":[{"text":"TileRegionLoadProgressCallback","kind":"identifier"}],"abstract":[{"type":"text","text":"Callback Invoked to report the progess of the tile region loading operation."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgressCallback","kind":"symbol","type":"topic","title":"TileRegionLoadProgressCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateResult":{"navigatorTitle":[{"text":"TileRegionEstimateResult","kind":"identifier"}],"abstract":[{"type":"text","text":"The result of tile region estim"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileRegionEstimateResult"}],"title":"TileRegionEstimateResult","role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/mapboxcommon\/tileregionestimateresult","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateResult"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/CacheClearingErrorType":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"CacheClearingErrorType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CacheClearingErrorType"}],"abstract":[{"type":"text","text":"Describes the reason for a cache clearing failure."}],"url":"\/documentation\/mapboxcommon\/cacheclearingerrortype","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingErrorType","type":"topic","title":"CacheClearingErrorType","role":"symbol","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileRegionError":{"url":"\/documentation\/mapboxmaps\/tileregionerror","kind":"symbol","title":"TileRegionError","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileRegionError","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TileRegionError"}],"navigatorTitle":[{"kind":"identifier","text":"TileRegionError"}],"abstract":[{"type":"text","text":"Describes the reason for a tile region download request failure."}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TilesetDescriptor":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TilesetDescriptor","navigatorTitle":[{"text":"TilesetDescriptor","kind":"identifier"}],"abstract":[{"type":"text","text":"A bundle that encapsulates tilesets creation for the tile store implementation."}],"url":"\/documentation\/mapboxcommon\/tilesetdescriptor","type":"topic","title":"TilesetDescriptor","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TilesetDescriptor","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegion":{"type":"topic","abstract":[{"type":"text","text":"TileRegion represents an identifiable geographic tile region with metadata"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegion","url":"\/documentation\/mapboxcommon\/tileregion","kind":"symbol","title":"TileRegion","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileRegion","kind":"identifier"}],"navigatorTitle":[{"text":"TileRegion","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CanonicalTileID":{"navigatorTitle":[{"text":"CanonicalTileID","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Represents a tile coordinate."}],"url":"\/documentation\/mapboxmaps\/canonicaltileid","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CanonicalTileID"}],"title":"CanonicalTileID"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudget":{"role":"symbol","url":"\/documentation\/mapboxmaps\/tilecachebudget","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudget","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TileCacheBudget","kind":"identifier"}],"abstract":[],"title":"TileCacheBudget","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TileCacheBudget"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MBMTileCacheBudgetInMegabytes","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInMegabytes\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInMegabytes\/fragments","value":[{"kind":"identifier","text":"MBMTileCacheBudgetInMegabytes"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInMegabytes\/navigatorTitle","value":[{"text":"MBMTileCacheBudgetInMegabytes","kind":"identifier"}]},{"op":"replace","value":"MBXTileStoreOptions","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStoreOptions\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStoreOptions\/fragments","op":"replace","value":[{"text":"MBXTileStoreOptions","kind":"identifier"}]},{"op":"replace","value":[{"text":"MBXTileStoreOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStoreOptions\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgressCallback\/title","value":"MBXTileRegionEstimateProgressCallback","op":"replace"},{"op":"replace","value":[{"text":"MBXTileRegionEstimateProgressCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgressCallback\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgressCallback\/navigatorTitle","value":[{"text":"MBXTileRegionEstimateProgressCallback","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetType\/title","value":"MBMTileCacheBudgetType"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetType\/fragments","value":[{"text":"MBMTileCacheBudgetType","kind":"identifier"}],"op":"replace"},{"value":[{"text":"MBMTileCacheBudgetType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetType\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateOptions\/title","value":"MBXTileRegionEstimateOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateOptions\/fragments","value":[{"text":"MBXTileRegionEstimateOptions","kind":"identifier"}]},{"value":[{"text":"MBXTileRegionEstimateOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateOptions\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/title","value":"MBXTileStore"},{"value":[{"kind":"identifier","text":"MBXTileStore"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MBXTileStore"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions\/title","value":"MBMTilesetDescriptorOptions","op":"replace"},{"op":"replace","value":[{"text":"MBMTilesetDescriptorOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions\/navigatorTitle","value":[{"kind":"identifier","text":"MBMTilesetDescriptorOptions"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgress\/title","value":"MBXTileRegionLoadProgress","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgress\/fragments","value":[{"text":"MBXTileRegionLoadProgress","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MBXTileRegionLoadProgress"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgress\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileStoreUsageMode\/title","value":"MBMTileStoreUsageMode","op":"replace"},{"value":[{"kind":"identifier","text":"MBMTileStoreUsageMode"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileStoreUsageMode\/fragments","op":"replace"},{"op":"replace","value":[{"text":"MBMTileStoreUsageMode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileStoreUsageMode\/navigatorTitle"},{"op":"replace","value":"MBXTileRegionEstimateProgress","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgress\/title"},{"op":"replace","value":[{"text":"MBXTileRegionEstimateProgress","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgress\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgress\/navigatorTitle","value":[{"text":"MBXTileRegionEstimateProgress","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileDataDomain\/title","value":"MBXTileDataDomain"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileDataDomain\/fragments","value":[{"text":"MBXTileDataDomain","kind":"identifier"}],"op":"replace"},{"value":[{"text":"MBXTileDataDomain","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileDataDomain\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingError\/title","value":"MBXCacheClearingError","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingError\/fragments","value":[{"text":"MBXCacheClearingError","kind":"identifier"}],"op":"replace"},{"value":[{"text":"MBXCacheClearingError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingError\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileOptions\/title","value":"MBMTileOptions"},{"value":[{"kind":"identifier","text":"MBMTileOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileOptions\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MBMTileOptions"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileOptions\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/title","op":"replace","value":"MBXTileRegionLoadOptions"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/fragments","op":"replace","value":[{"text":"MBXTileRegionLoadOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/navigatorTitle","op":"replace","value":[{"text":"MBXTileRegionLoadOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInTiles\/title","value":"MBMTileCacheBudgetInTiles","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInTiles\/fragments","value":[{"kind":"identifier","text":"MBMTileCacheBudgetInTiles"}]},{"value":[{"text":"MBMTileCacheBudgetInTiles","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInTiles\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgressCallback\/title","op":"replace","value":"MBXTileRegionLoadProgressCallback"},{"value":[{"kind":"identifier","text":"MBXTileRegionLoadProgressCallback"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgressCallback\/fragments","op":"replace"},{"value":[{"text":"MBXTileRegionLoadProgressCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgressCallback\/navigatorTitle","op":"replace"},{"value":"MBXTileRegionEstimateResult","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateResult\/title"},{"op":"replace","value":[{"text":"MBXTileRegionEstimateResult","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateResult\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateResult\/navigatorTitle","value":[{"text":"MBXTileRegionEstimateResult","kind":"identifier"}]},{"value":"MBXCacheClearingErrorType","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingErrorType\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingErrorType\/fragments","value":[{"text":"MBXCacheClearingErrorType","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBXCacheClearingErrorType"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingErrorType\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TilesetDescriptor\/title","op":"replace","value":"MBXTilesetDescriptor"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TilesetDescriptor\/fragments","value":[{"text":"MBXTilesetDescriptor","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TilesetDescriptor\/navigatorTitle","op":"replace","value":[{"text":"MBXTilesetDescriptor","kind":"identifier"}]},{"op":"replace","value":"MBXTileRegion","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegion\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegion\/fragments","op":"replace","value":[{"text":"MBXTileRegion","kind":"identifier"}]},{"value":[{"text":"MBXTileRegion","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegion\/navigatorTitle"},{"op":"replace","value":"MBMCanonicalTileID","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/title"},{"value":[{"kind":"identifier","text":"MBMCanonicalTileID"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMCanonicalTileID"}]},{"value":"MBMTileCacheBudget","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudget\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudget\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMTileCacheBudget"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudget\/navigatorTitle","value":[{"kind":"identifier","text":"MBMTileCacheBudget"}],"op":"replace"}]}]}