{"abstract":[{"text":"Stores layout and visibility settings for a view annotation.","type":"text"}],"relationshipsSections":[{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/SQ"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"ViewAnnotationOptions","kind":"identifier"}],"platforms":["iOS"]}]},{"content":[{"text":"Overview","type":"heading","level":2,"anchor":"overview"},{"name":"Important","content":[{"inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"ViewAnnotationOptions"},{"type":"text","text":" is deprecated and will be removed in future releases. Use "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation"},{"type":"text","text":" instead."}],"type":"paragraph"}],"type":"aside","style":"important"}],"kind":"content"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/View-Annotations"]]},"metadata":{"navigatorTitle":[{"text":"ViewAnnotationOptions","kind":"identifier"}],"title":"ViewAnnotationOptions","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"ViewAnnotationOptions","kind":"identifier"}],"symbolKind":"struct","role":"symbol","externalID":"s:10MapboxMaps21ViewAnnotationOptionsV","modules":[{"name":"MapboxMaps"}],"roleHeading":"Structure"},"seeAlsoSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManager","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManagerError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchorConfig","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationPositionDescriptor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationUpdateObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchor"],"generated":true,"anchor":"View-Annotations","title":"View Annotations"}],"sections":[],"variants":[{"paths":["\/documentation\/mapboxmaps\/viewannotationoptions"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationOptions"},"kind":"symbol","topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationOptions\/init(annotatedFeature:width:height:allowOverlap:allowOverlapWithPuck:visible:selected:variableAnchors:ignoreCameraPadding:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationOptions\/init(geometry:width:height:associatedFeatureId:allowOverlap:visible:anchor:offsetX:offsetY:selected:)"],"anchor":"Initializers","generated":true},{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationOptions\/allowOverlap","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationOptions\/allowOverlapWithPuck","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationOptions\/allowZElevate","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationOptions\/annotatedFeature","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationOptions\/height","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationOptions\/ignoreCameraPadding","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationOptions\/selected","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationOptions\/variableAnchors","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationOptions\/visible","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationOptions\/width"]},{"anchor":"Default-Implementations","generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationOptions\/Equatable-Implementations"]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationPositionDescriptor":{"kind":"symbol","abstract":[{"text":"Read-only data that is needed to correctly position the single view annotation on screen.","type":"text"},{"type":"text","text":" "},{"text":"Used inside ViewAnnotationPositionsUpdateListener callback to notify the listener about the visible view annotations’ position updates.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ViewAnnotationPositionDescriptor"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/viewannotationpositiondescriptor","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationPositionDescriptor","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ViewAnnotationPositionDescriptor"}],"title":"ViewAnnotationPositionDescriptor"},"doc://com.mapbox.MapboxMaps/SQ":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationOptions/Equatable-Implementations":{"abstract":[],"type":"topic","url":"\/documentation\/mapboxmaps\/viewannotationoptions\/equatable-implementations","kind":"article","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationOptions\/Equatable-Implementations","title":"Equatable Implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationManager":{"url":"\/documentation\/mapboxmaps\/viewannotationmanager","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManager","type":"topic","abstract":[{"text":"Manager API to control View Annotations.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ViewAnnotationManager"}],"navigatorTitle":[{"kind":"identifier","text":"ViewAnnotationManager"}],"role":"symbol","kind":"symbol","title":"ViewAnnotationManager"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationOptions/ignoreCameraPadding":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ignoreCameraPadding"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"url":"\/documentation\/mapboxmaps\/viewannotationoptions\/ignorecamerapadding","abstract":[{"text":"When ","type":"text"},{"type":"codeVoice","code":"false"},{"type":"text","text":", the annotation will be displayed even if it go beyond camera padding."}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationOptions\/ignoreCameraPadding","role":"symbol","title":"ignoreCameraPadding"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationOptions":{"navigatorTitle":[{"text":"ViewAnnotationOptions","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/viewannotationoptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationOptions","title":"ViewAnnotationOptions","abstract":[{"text":"Stores layout and visibility settings for a view annotation.","type":"text"}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ViewAnnotationOptions"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationOptions/allowZElevate":{"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/viewannotationoptions\/allowzelevate","abstract":[{"text":"When ","type":"text"},{"code":"true","type":"codeVoice"},{"type":"text","text":", the annotation will respect Z-axis elevation and be rendered on top of elevated objects."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationOptions\/allowZElevate","title":"allowZElevate","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowZElevate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":"?","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationUpdateObserver":{"url":"\/documentation\/mapboxmaps\/viewannotationupdateobserver","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationUpdateObserver","type":"topic","abstract":[{"text":"An interface you use to detect when the map view lays out or updates visibility of annotation views.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ViewAnnotationUpdateObserver","kind":"identifier"}],"navigatorTitle":[{"text":"ViewAnnotationUpdateObserver","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"ViewAnnotationUpdateObserver"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationOptions/height":{"url":"\/documentation\/mapboxmaps\/viewannotationoptions\/height","role":"symbol","abstract":[{"type":"text","text":"View annotation height in pixels."}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"height"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationOptions\/height","title":"height"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationOptions/init(annotatedFeature:width:height:allowOverlap:allowOverlapWithPuck:visible:selected:variableAnchors:ignoreCameraPadding:)":{"type":"topic","abstract":[{"type":"text","text":"Initializes a "},{"type":"codeVoice","code":"ViewAnnotationOptions"}],"url":"\/documentation\/mapboxmaps\/viewannotationoptions\/init(annotatedfeature:width:height:allowoverlap:allowoverlapwithpuck:visible:selected:variableanchors:ignorecamerapadding:)","kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"annotatedFeature"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps16AnnotatedFeatureV","text":"AnnotatedFeature"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"width"},{"kind":"text","text":": "},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"height","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"allowOverlap"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":"?, "},{"text":"allowOverlapWithPuck","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?, "},{"text":"visible","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":"?, ","kind":"text"},{"text":"selected","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"variableAnchors","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMViewAnnotationAnchorConfig","text":"ViewAnnotationAnchorConfig"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"ignoreCameraPadding"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":"?)"}],"title":"init(annotatedFeature:width:height:allowOverlap:allowOverlapWithPuck:visible:selected:variableAnchors:ignoreCameraPadding:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationOptions\/init(annotatedFeature:width:height:allowOverlap:allowOverlapWithPuck:visible:selected:variableAnchors:ignoreCameraPadding:)"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","role":"collection","title":"MapboxMaps Documentation","abstract":[],"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationOptions/selected":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationOptions\/selected","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"selected"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?"}],"type":"topic","title":"selected","role":"symbol","kind":"symbol","url":"\/documentation\/mapboxmaps\/viewannotationoptions\/selected","abstract":[{"text":"Specifies if this view annotation is selected meaning it should be placed on top of others.","type":"text"},{"text":" ","type":"text"},{"text":"If selected in null, default value ","type":"text"},{"code":"false","type":"codeVoice"},{"text":" will be applied.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotation":{"kind":"symbol","abstract":[{"type":"text","text":"Creates a view annotation."}],"title":"ViewAnnotation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ViewAnnotation","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/viewannotation","role":"symbol","navigatorTitle":[{"text":"ViewAnnotation","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationOptions/annotatedFeature":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationOptions\/annotatedFeature","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/viewannotationoptions\/annotatedfeature","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"annotatedFeature","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps16AnnotatedFeatureV","text":"AnnotatedFeature","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[],"title":"annotatedFeature"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationOptions/visible":{"role":"symbol","abstract":[{"type":"text","text":"Specifies if this view annotation is visible or not."}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationOptions\/visible","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"visible","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":"?","kind":"text"}],"title":"visible","url":"\/documentation\/mapboxmaps\/viewannotationoptions\/visible"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationOptions/variableAnchors":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"variableAnchors","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)MBMViewAnnotationAnchorConfig","kind":"typeIdentifier","text":"ViewAnnotationAnchorConfig"},{"text":"]?","kind":"text"}],"url":"\/documentation\/mapboxmaps\/viewannotationoptions\/variableanchors","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationOptions\/variableAnchors","role":"symbol","type":"topic","abstract":[],"title":"variableAnchors","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationOptions/allowOverlapWithPuck":{"title":"allowOverlapWithPuck","abstract":[{"type":"text","text":"When "},{"code":"false","type":"codeVoice"},{"type":"text","text":", the annotation won’t be shown on top of the Puck."}],"url":"\/documentation\/mapboxmaps\/viewannotationoptions\/allowoverlapwithpuck","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationOptions\/allowOverlapWithPuck","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowOverlapWithPuck"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":"?"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/View-Annotations":{"title":"View Annotations","kind":"article","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/View-Annotations","abstract":[],"type":"topic","url":"\/documentation\/mapboxmaps\/view-annotations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationAnchor":{"navigatorTitle":[{"text":"ViewAnnotationAnchor","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/viewannotationanchor","abstract":[{"type":"text","text":"Enum describing how to place view annotation relatively to geometry."}],"title":"ViewAnnotationAnchor","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchor","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ViewAnnotationAnchor","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationOptions/allowOverlap":{"url":"\/documentation\/mapboxmaps\/viewannotationoptions\/allowoverlap","kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationOptions\/allowOverlap","title":"allowOverlap","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowOverlap"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"If true, the annotation will be visible even if it collides with other previously drawn annotations."},{"text":" ","type":"text"},{"text":"If allowOverlap is null, default value ","type":"text"},{"code":"false","type":"codeVoice"},{"type":"text","text":" will be applied."},{"type":"text","text":" "},{"text":"Note: When the value is true, the ordering of the views are determined by the order of their addition.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","kind":"symbol","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationAnchorConfig":{"abstract":[{"text":"Represents a specific setting for a view annotation anchor.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ViewAnnotationAnchorConfig","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/viewannotationanchorconfig","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchorConfig","navigatorTitle":[{"text":"ViewAnnotationAnchorConfig","kind":"identifier"}],"role":"symbol","title":"ViewAnnotationAnchorConfig"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationManagerError":{"title":"ViewAnnotationManagerError","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ViewAnnotationManagerError","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManagerError","abstract":[],"navigatorTitle":[{"text":"ViewAnnotationManagerError","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxmaps\/viewannotationmanagererror"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationOptions/width":{"url":"\/documentation\/mapboxmaps\/viewannotationoptions\/width","type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationOptions\/width","title":"width","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"width"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"View annotation width in pixels."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationOptions/init(geometry:width:height:associatedFeatureId:allowOverlap:visible:anchor:offsetX:offsetY:selected:)":{"kind":"symbol","role":"symbol","deprecated":true,"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationOptions\/init(geometry:width:height:associatedFeatureId:allowOverlap:visible:anchor:offsetX:offsetY:selected:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"geometry","kind":"externalParam"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","preciseIdentifier":"s:4Turf19GeometryConvertibleP","text":"GeometryConvertible"},{"text":")?, ","kind":"text"},{"kind":"externalParam","text":"width"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"height"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"associatedFeatureId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"allowOverlap","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?, "},{"text":"visible","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"anchor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ViewAnnotationAnchor","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMViewAnnotationAnchor"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"offsetX"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"offsetY"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"kind":"text","text":"?, "},{"text":"selected","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"title":"init(geometry:width:height:associatedFeatureId:allowOverlap:visible:anchor:offsetX:offsetY:selected:)","url":"\/documentation\/mapboxmaps\/viewannotationoptions\/init(geometry:width:height:associatedfeatureid:allowoverlap:visible:anchor:offsetx:offsety:selected:)","abstract":[{"text":"Initializes a ","type":"text"},{"type":"codeVoice","code":"ViewAnnotationOptions"},{"type":"text","text":" with geometry."}]}},"variantOverrides":[{"patch":[{"value":"MBMViewAnnotationPositionDescriptor","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationPositionDescriptor\/title"},{"value":[{"kind":"identifier","text":"MBMViewAnnotationPositionDescriptor"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationPositionDescriptor\/fragments","op":"replace"},{"value":[{"text":"MBMViewAnnotationPositionDescriptor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationPositionDescriptor\/navigatorTitle"},{"op":"replace","value":"MBMViewAnnotationAnchor","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchor\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchor\/fragments","value":[{"text":"MBMViewAnnotationAnchor","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchor\/navigatorTitle","value":[{"kind":"identifier","text":"MBMViewAnnotationAnchor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchorConfig\/title","value":"MBMViewAnnotationAnchorConfig"},{"op":"replace","value":[{"kind":"identifier","text":"MBMViewAnnotationAnchorConfig"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchorConfig\/fragments"},{"op":"replace","value":[{"text":"MBMViewAnnotationAnchorConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchorConfig\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}