{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ViewAnnotationPositionDescriptor","kind":"identifier"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/viewannotationpositiondescriptor"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/viewannotationpositiondescriptor"]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/View-Annotations"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationPositionDescriptor","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"modules":[{"name":"MapboxMaps"}],"symbolKind":"class","title":"ViewAnnotationPositionDescriptor","navigatorTitle":[{"text":"ViewAnnotationPositionDescriptor","kind":"identifier"}],"roleHeading":"Class","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ViewAnnotationPositionDescriptor","kind":"identifier"}],"externalID":"c:objc(cs)MBMViewAnnotationPositionDescriptor"},"abstract":[{"type":"text","text":"Read-only data that is needed to correctly position the single view annotation on screen."},{"text":" ","type":"text"},{"type":"text","text":"Used inside ViewAnnotationPositionsUpdateListener callback to notify the listener about the visible view annotations’ position updates."}],"seeAlsoSections":[{"title":"View Annotations","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManager","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManagerError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchorConfig","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationUpdateObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchor"],"anchor":"View-Annotations","generated":true}],"sections":[],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"topicSections":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationPositionDescriptor\/anchorConfig","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationPositionDescriptor\/anchorCoordinate","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationPositionDescriptor\/height","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationPositionDescriptor\/identifier","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationPositionDescriptor\/width"]}],"references":{"doc://com.mapbox.MapboxMaps/SH":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.mapbox.MapboxMaps/objc(pl)NSObject":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","role":"collection","title":"MapboxMaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationPositionDescriptor/identifier":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationPositionDescriptor\/identifier","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"identifier","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"text":"identifier","kind":"identifier"}],"kind":"symbol","title":"identifier","url":"\/documentation\/mapboxmaps\/viewannotationpositiondescriptor\/identifier","type":"topic","abstract":[{"type":"text","text":"Unique id in order to lookup an actual view in platform SDKs."}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationPositionDescriptor/height":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationPositionDescriptor\/height","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"height"},{"kind":"text","text":": "},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"height","kind":"identifier"}],"kind":"symbol","title":"height","url":"\/documentation\/mapboxmaps\/viewannotationpositiondescriptor\/height","type":"topic","abstract":[{"type":"text","text":"View annotation height in "},{"type":"codeVoice","code":"platform pixels"},{"type":"text","text":" for drawing the annotation."}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationPositionDescriptor":{"url":"\/documentation\/mapboxmaps\/viewannotationpositiondescriptor","abstract":[{"text":"Read-only data that is needed to correctly position the single view annotation on screen.","type":"text"},{"text":" ","type":"text"},{"text":"Used inside ViewAnnotationPositionsUpdateListener callback to notify the listener about the visible view annotations’ position updates.","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ViewAnnotationPositionDescriptor","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationPositionDescriptor","navigatorTitle":[{"text":"ViewAnnotationPositionDescriptor","kind":"identifier"}],"title":"ViewAnnotationPositionDescriptor"},"doc://com.mapbox.MapboxMaps/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationManager":{"abstract":[{"type":"text","text":"Manager API to control View Annotations."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ViewAnnotationManager","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"ViewAnnotationManager","kind":"identifier"}],"type":"topic","title":"ViewAnnotationManager","url":"\/documentation\/mapboxmaps\/viewannotationmanager","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManager"},"doc://com.mapbox.MapboxMaps/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationUpdateObserver":{"url":"\/documentation\/mapboxmaps\/viewannotationupdateobserver","abstract":[{"type":"text","text":"An interface you use to detect when the map view lays out or updates visibility of annotation views."}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ViewAnnotationUpdateObserver","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationUpdateObserver","navigatorTitle":[{"text":"ViewAnnotationUpdateObserver","kind":"identifier"}],"title":"ViewAnnotationUpdateObserver"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/View-Annotations":{"kind":"article","url":"\/documentation\/mapboxmaps\/view-annotations","title":"View Annotations","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/View-Annotations","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","kind":"article","type":"topic","url":"\/documentation\/overview","title":"MapboxMaps Documentation","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationAnchorConfig":{"title":"ViewAnnotationAnchorConfig","type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/viewannotationanchorconfig","role":"symbol","navigatorTitle":[{"text":"ViewAnnotationAnchorConfig","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchorConfig","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ViewAnnotationAnchorConfig","kind":"identifier"}],"abstract":[{"type":"text","text":"Represents a specific setting for a view annotation anchor."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotation":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation","abstract":[{"text":"Creates a view annotation.","type":"text"}],"navigatorTitle":[{"text":"ViewAnnotation","kind":"identifier"}],"title":"ViewAnnotation","url":"\/documentation\/mapboxmaps\/viewannotation","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ViewAnnotation"}],"role":"symbol","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationPositionDescriptor/anchorConfig":{"url":"\/documentation\/mapboxmaps\/viewannotationpositiondescriptor\/anchorconfig","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"anchorConfig","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ViewAnnotationAnchorConfig","preciseIdentifier":"c:objc(cs)MBMViewAnnotationAnchorConfig"}],"navigatorTitle":[{"kind":"identifier","text":"anchorConfig"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationPositionDescriptor\/anchorConfig","type":"topic","kind":"symbol","role":"symbol","title":"anchorConfig","abstract":[{"type":"text","text":"The chosen anchor option for view annotation."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationPositionDescriptor/anchorCoordinate":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationPositionDescriptor\/anchorCoordinate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"anchorCoordinate","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"}],"navigatorTitle":[{"text":"anchorCoordinate","kind":"identifier"}],"kind":"symbol","title":"anchorCoordinate","url":"\/documentation\/mapboxmaps\/viewannotationpositiondescriptor\/anchorcoordinate","type":"topic","abstract":[{"type":"text","text":"The actual geometric position used for positioning this annotation."}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationManagerError":{"url":"\/documentation\/mapboxmaps\/viewannotationmanagererror","abstract":[],"role":"symbol","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ViewAnnotationManagerError"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ViewAnnotationManagerError"}],"title":"ViewAnnotationManagerError","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManagerError"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationOptions":{"abstract":[{"text":"Stores layout and visibility settings for a view annotation.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"ViewAnnotationOptions","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ViewAnnotationOptions"}],"type":"topic","title":"ViewAnnotationOptions","url":"\/documentation\/mapboxmaps\/viewannotationoptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationPositionDescriptor/width":{"type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/viewannotationpositiondescriptor\/width","abstract":[{"type":"text","text":"View annotation width in "},{"type":"codeVoice","code":"platform pixels"},{"text":" for drawing the annotation.","type":"text"}],"title":"width","navigatorTitle":[{"kind":"identifier","text":"width"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationPositionDescriptor\/width","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"width","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationAnchor":{"type":"topic","url":"\/documentation\/mapboxmaps\/viewannotationanchor","abstract":[{"type":"text","text":"Enum describing how to place view annotation relatively to geometry."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchor","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ViewAnnotationAnchor"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ViewAnnotationAnchor","kind":"identifier"}],"title":"ViewAnnotationAnchor"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","value":"MBMViewAnnotationPositionDescriptor","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MBMViewAnnotationPositionDescriptor"}]},{"value":[{"text":"MBMViewAnnotationPositionDescriptor","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationPositionDescriptor\/anchorConfig","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationPositionDescriptor\/anchorCoordinate","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationPositionDescriptor\/height","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationPositionDescriptor\/identifier","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationPositionDescriptor\/width"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchorConfig","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchor"],"anchor":"View-Annotations","title":"View Annotations"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBMViewAnnotationPositionDescriptor"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"identifier","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationPositionDescriptor~1identifier\/title","op":"replace"},{"value":[{"kind":"identifier","text":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationPositionDescriptor~1identifier\/fragments"},{"value":"height","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationPositionDescriptor~1height\/title","op":"replace"},{"value":[{"text":"height","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationPositionDescriptor~1height\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationPositionDescriptor\/title","value":"MBMViewAnnotationPositionDescriptor"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationPositionDescriptor\/fragments","value":[{"text":"MBMViewAnnotationPositionDescriptor","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationPositionDescriptor\/navigatorTitle","value":[{"text":"MBMViewAnnotationPositionDescriptor","kind":"identifier"}]},{"value":"MBMViewAnnotationAnchorConfig","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchorConfig\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchorConfig\/fragments","value":[{"text":"MBMViewAnnotationAnchorConfig","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchorConfig\/navigatorTitle","value":[{"kind":"identifier","text":"MBMViewAnnotationAnchorConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationPositionDescriptor~1anchorConfig\/title","value":"anchorConfig"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationPositionDescriptor~1anchorConfig\/fragments","value":[{"kind":"identifier","text":"anchorConfig"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationPositionDescriptor~1anchorCoordinate\/title","value":"anchorCoordinate"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationPositionDescriptor~1anchorCoordinate\/fragments","value":[{"text":"anchorCoordinate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationPositionDescriptor~1width\/title","value":"width","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationPositionDescriptor~1width\/fragments","value":[{"text":"width","kind":"identifier"}],"op":"replace"},{"value":"MBMViewAnnotationAnchor","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchor\/title","op":"replace"},{"op":"replace","value":[{"text":"MBMViewAnnotationAnchor","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchor\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchor\/navigatorTitle","value":[{"kind":"identifier","text":"MBMViewAnnotationAnchor"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}