{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegion\/getTilePyramidDefinition()"},"abstract":[{"text":"The tile pyramid defining the region. Tile pyramid and geometry definitions are","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"mutually exclusive."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/offlineregion\/gettilepyramiddefinition()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/offlineregion\/gettilepyramiddefinition()"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getTilePyramidDefinition","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"OfflineRegionTilePyramidDefinition","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionTilePyramidDefinition","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMOfflineRegionTilePyramidDefinition"},{"kind":"text","text":"?"}]}]},{"content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"inlineContent":[{"text":"A definition describing the tile pyramid including attributes, otherwise empty.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"title":"getTilePyramidDefinition()","symbolKind":"method","navigatorTitle":[{"text":"getTilePyramidDefinition","kind":"identifier"}],"externalID":"c:objc(cs)MBMOfflineRegion(im)getTilePyramidDefinition","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getTilePyramidDefinition"},{"text":"() -> ","kind":"text"},{"text":"OfflineRegionTilePyramidDefinition","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMOfflineRegionTilePyramidDefinition"},{"kind":"text","text":"?"}],"roleHeading":"Instance Method","modules":[{"name":"MapboxMaps"}],"platforms":[]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegion"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"title":"MapboxMaps","kind":"symbol","role":"collection","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegion/getTilePyramidDefinition()":{"role":"symbol","navigatorTitle":[{"text":"getTilePyramidDefinition","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/offlineregion\/gettilepyramiddefinition()","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegion\/getTilePyramidDefinition()","abstract":[{"type":"text","text":"The tile pyramid defining the region. Tile pyramid and geometry definitions are"},{"text":" ","type":"text"},{"type":"text","text":"mutually exclusive."}],"kind":"symbol","type":"topic","title":"getTilePyramidDefinition()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getTilePyramidDefinition"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:objc(cs)MBMOfflineRegionTilePyramidDefinition","text":"OfflineRegionTilePyramidDefinition","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"deprecated":true},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Offline":{"title":"Offline Support","abstract":[],"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","url":"\/documentation\/mapboxmaps\/offline","role":"collectionGroup","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMaps":{"url":"\/documentation\/mapboxmaps\/coremaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","kind":"article","abstract":[{"type":"text","text":"Maps rendering SDK also known as GL-Native"}],"title":"Core Maps API","role":"collectionGroup","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","role":"collection","url":"\/documentation\/overview","kind":"article","abstract":[],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegion":{"deprecated":true,"navigatorTitle":[{"text":"OfflineRegion","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"An offline region represents an identifiable geographic region with optional metadata.","type":"text"}],"url":"\/documentation\/mapboxmaps\/offlineregion","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegion","title":"OfflineRegion","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"OfflineRegion"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionTilePyramidDefinition":{"role":"symbol","url":"\/documentation\/mapboxmaps\/offlineregiontilepyramiddefinition","navigatorTitle":[{"text":"OfflineRegionTilePyramidDefinition","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"OfflineRegionTilePyramidDefinition","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionTilePyramidDefinition","kind":"symbol","deprecated":true,"title":"OfflineRegionTilePyramidDefinition","abstract":[{"type":"text","text":"An offline region definition is a geographic region defined by a style URL,"},{"text":" ","type":"text"},{"type":"text","text":"geographic bounding box, zoom range, and device pixel ratio. Both "},{"type":"codeVoice","code":"minZoom"},{"type":"text","text":" and "},{"code":"maxZoom","type":"codeVoice"},{"type":"text","text":" must be ≥ 0,"},{"text":" ","type":"text"},{"type":"text","text":"and "},{"type":"codeVoice","code":"maxZoom"},{"text":" must be ≥ ","type":"text"},{"code":"minZoom","type":"codeVoice"},{"type":"text","text":". The "},{"code":"maxZoom","type":"codeVoice"},{"type":"text","text":" may be ∞, in which case for each tile source,"},{"type":"text","text":" "},{"type":"text","text":"the region will include tiles from "},{"type":"codeVoice","code":"minZoom"},{"text":" up to the maximum zoom level provided by that source.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The "},{"code":"pixelRatio","type":"codeVoice"},{"type":"text","text":" must be ≥ 0 and should typically be 1.0 or 2.0."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"getTilePyramidDefinition","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"getTilePyramidDefinition","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionTilePyramidDefinition","preciseIdentifier":"c:objc(cs)MBMOfflineRegionTilePyramidDefinition","text":"MBMOfflineRegionTilePyramidDefinition"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"getTilePyramidDefinition"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"value":{"kind":"content","content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"inlineContent":[{"type":"text","text":"A definition describing the tile pyramid including attributes, otherwise empty."}],"type":"paragraph"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"getTilePyramidDefinition","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegion~1getTilePyramidDefinition()\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegion~1getTilePyramidDefinition()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"getTilePyramidDefinition","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegion\/title","value":"MBMOfflineRegion","op":"replace"},{"op":"replace","value":[{"text":"MBMOfflineRegion","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegion\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegion\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMOfflineRegion"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionTilePyramidDefinition\/title","value":"MBMOfflineRegionTilePyramidDefinition","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionTilePyramidDefinition\/fragments","value":[{"kind":"identifier","text":"MBMOfflineRegionTilePyramidDefinition"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionTilePyramidDefinition\/navigatorTitle","value":[{"text":"MBMOfflineRegionTilePyramidDefinition","kind":"identifier"}],"op":"replace"}]}]}