{"relationshipsSections":[{"kind":"relationships","title":"Conforming Types","type":"conformingTypes","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProvider"]}],"metadata":{"symbolKind":"protocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeadingProvider"}],"title":"HeadingProvider","navigatorTitle":[{"kind":"identifier","text":"HeadingProvider"}],"modules":[{"name":"MapboxMaps"}],"roleHeading":"Protocol","role":"symbol","externalID":"s:10MapboxMaps15HeadingProviderP"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs"]]},"kind":"symbol","abstract":[{"type":"text","text":"Provides heading data to drive the location puck."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"topicSections":[{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingProvider\/latestHeading"]},{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingProvider\/add(headingObserver:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingProvider\/remove(headingObserver:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingProvider"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/headingprovider"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeadingProvider"}]}]}],"seeAlsoSections":[{"anchor":"Location","title":"Location","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationManager","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck2DConfiguration","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Model","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckBearing","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProviderDelegate","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Coordinate2D","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationExtraKeys","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProviderRequest","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceFactory","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/DeviceLocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Heading","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckRenderingData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/IntervalSettings"]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PuckType":{"title":"PuckType","kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/pucktype","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PuckType","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckType","abstract":[{"type":"text","text":"Represents the different types of pucks"}],"navigatorTitle":[{"text":"PuckType","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeadingProvider/latestHeading":{"abstract":[{"type":"text","text":"Latest observed heading."}],"type":"topic","role":"symbol","title":"latestHeading","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"latestHeading","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Heading","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps7HeadingV"},{"text":"?","kind":"text"}],"url":"\/documentation\/mapboxmaps\/headingprovider\/latestheading","required":true,"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingProvider\/latestHeading"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/AccuracyAuthorization":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AccuracyAuthorization","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"AccuracyAuthorization","kind":"identifier"}],"abstract":[{"type":"text","text":"Accuracy authorization granted by user to the app."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization","url":"\/documentation\/mapboxcommon\/accuracyauthorization","kind":"symbol","title":"AccuracyAuthorization"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Coordinate2D":{"title":"Coordinate2D","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Coordinate2D","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Boxed version of CLLocationCoordinate2D"}],"type":"topic","url":"\/documentation\/mapboxcommon\/coordinate2d","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Coordinate2D","navigatorTitle":[{"text":"Coordinate2D","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationError":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationError"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationError","title":"LocationError","navigatorTitle":[{"kind":"identifier","text":"LocationError"}],"type":"topic","url":"\/documentation\/mapboxcommon\/locationerror","abstract":[{"text":"Error code with brief explanation.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AppleLocationProvider":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AppleLocationProvider"}],"abstract":[{"text":"A location provider based on CoreLocation’s ","type":"text"},{"type":"codeVoice","code":"CLLocationManager"},{"text":".","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppleLocationProvider"}],"type":"topic","title":"AppleLocationProvider","url":"\/documentation\/mapboxmaps\/applelocationprovider"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeadingProvider/add(headingObserver:)":{"abstract":[{"text":"Adds heading observer.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":"("},{"kind":"externalParam","text":"headingObserver"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","text":"HeadingObserver","preciseIdentifier":"s:10MapboxMaps15HeadingObserverP"},{"kind":"text","text":")"}],"required":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingProvider\/add(headingObserver:)","role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/headingprovider\/add(headingobserver:)","title":"add(headingObserver:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PermissionStatus":{"title":"PermissionStatus","role":"symbol","navigatorTitle":[{"text":"PermissionStatus","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus","kind":"symbol","abstract":[{"type":"text","text":"Location permissions granted by user to the app."}],"url":"\/documentation\/mapboxcommon\/permissionstatus","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PermissionStatus","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/IntervalSettings":{"title":"IntervalSettings","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntervalSettings"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/IntervalSettings","url":"\/documentation\/mapboxcommon\/intervalsettings","abstract":[{"text":"The interval for active location updates","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"IntervalSettings"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Location":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Location"}],"title":"Location","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location","url":"\/documentation\/mapboxcommon\/location","abstract":[{"type":"text","text":"Location information."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"Location"}],"role":"symbol","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PuckBearing":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PuckBearing"}],"title":"PuckBearing","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckBearing","type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/mapboxmaps\/puckbearing","navigatorTitle":[{"kind":"identifier","text":"PuckBearing"}],"abstract":[{"type":"text","text":"Controls how the puck is oriented"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/DeviceLocationProvider":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DeviceLocationProvider","kind":"identifier"}],"navigatorTitle":[{"text":"DeviceLocationProvider","kind":"identifier"}],"abstract":[{"text":"Location provider specialisation that provides real-time locations generated from the device","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/DeviceLocationProvider","role":"symbol","type":"topic","title":"DeviceLocationProvider","url":"\/documentation\/mapboxcommon\/devicelocationprovider"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeadingProvider/remove(headingObserver:)":{"role":"symbol","required":true,"title":"remove(headingObserver:)","abstract":[{"text":"Removes heading observer.","type":"text"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"remove","kind":"identifier"},{"text":"(","kind":"text"},{"text":"headingObserver","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"HeadingObserver","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps15HeadingObserverP"},{"text":")","kind":"text"}],"url":"\/documentation\/mapboxmaps\/headingprovider\/remove(headingobserver:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingProvider\/remove(headingObserver:)","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"url":"\/documentation\/mapboxmaps","title":"MapboxMaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationServiceFactory":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationServiceFactory","kind":"identifier"}],"navigatorTitle":[{"text":"LocationServiceFactory","kind":"identifier"}],"abstract":[{"text":"Location service factory.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceFactory","role":"symbol","type":"topic","title":"LocationServiceFactory","url":"\/documentation\/mapboxcommon\/locationservicefactory"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LocationManager":{"abstract":[{"text":"An object responsible for managing user location Puck.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"LocationManager"}],"url":"\/documentation\/mapboxmaps\/locationmanager","title":"LocationManager","role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationManager"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Puck3DConfiguration":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration","role":"symbol","abstract":[],"url":"\/documentation\/mapboxmaps\/puck3dconfiguration","type":"topic","title":"Puck3DConfiguration","navigatorTitle":[{"text":"Puck3DConfiguration","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Puck3DConfiguration","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationProvider":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationProvider"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider","kind":"symbol","title":"LocationProvider","navigatorTitle":[{"kind":"identifier","text":"LocationProvider"}],"role":"symbol","url":"\/documentation\/mapboxcommon\/locationprovider","type":"topic","abstract":[{"text":"Location provider that provides locations","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationObserver":{"url":"\/documentation\/mapboxcommon\/locationobserver","abstract":[{"text":"Observer for getting updates from a LocationProvider.","type":"text"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationObserver","kind":"symbol","title":"LocationObserver","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationObserver","kind":"identifier"}],"navigatorTitle":[{"text":"LocationObserver","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LocationOptions":{"title":"LocationOptions","url":"\/documentation\/mapboxmaps\/locationoptions","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationOptions","kind":"identifier"}],"navigatorTitle":[{"text":"LocationOptions","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationOptions","abstract":[{"type":"text","text":"A struct to configure a "},{"type":"codeVoice","code":"LocationManager"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Model":{"type":"topic","navigatorTitle":[{"text":"Model","kind":"identifier"}],"title":"Model","role":"symbol","url":"\/documentation\/mapboxmaps\/model","kind":"symbol","abstract":[{"type":"text","text":"A structure represeting a Model"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Model","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Model","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationErrorCode":{"type":"topic","url":"\/documentation\/mapboxcommon\/locationerrorcode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationErrorCode","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"LocationErrorCode","kind":"identifier"}],"abstract":[{"type":"text","text":"Codes of location errors."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode","title":"LocationErrorCode","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Puck2DConfiguration":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Puck2DConfiguration"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Puck2DConfiguration"}],"kind":"symbol","title":"Puck2DConfiguration","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck2DConfiguration","url":"\/documentation\/mapboxmaps\/puck2dconfiguration"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationServiceObserver":{"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Observers for getting updates from LocationService."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationServiceObserver","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver","title":"LocationServiceObserver","role":"symbol","url":"\/documentation\/mapboxcommon\/locationserviceobserver","navigatorTitle":[{"text":"LocationServiceObserver","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationProviderRequest":{"abstract":[{"type":"text","text":"Data model that contains parameters for location requests."}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProviderRequest","role":"symbol","url":"\/documentation\/mapboxcommon\/locationproviderrequest","title":"LocationProviderRequest","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationProviderRequest"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"LocationProviderRequest"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/AccuracyLevel":{"url":"\/documentation\/mapboxcommon\/accuracylevel","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AccuracyLevel","kind":"identifier"}],"navigatorTitle":[{"text":"AccuracyLevel","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel","type":"topic","abstract":[{"text":"The accuracy of the observed location","type":"text"}],"title":"AccuracyLevel"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeadingObserver":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HeadingObserver","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/headingobserver","type":"topic","navigatorTitle":[{"text":"HeadingObserver","kind":"identifier"}],"title":"HeadingObserver","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingObserver","abstract":[{"type":"text","text":"Listens to "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingProvider"},{"type":"text","text":"’s updates."}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationExtraKeys":{"role":"symbol","url":"\/documentation\/mapboxcommon\/locationextrakeys","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationExtraKeys","navigatorTitle":[{"kind":"identifier","text":"LocationExtraKeys"}],"title":"LocationExtraKeys","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationExtraKeys"}],"kind":"symbol","abstract":[{"text":"Keys for additional information (extra) in Location.","type":"text"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Location-APIs":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","role":"collectionGroup","abstract":[],"kind":"article","title":"Location","url":"\/documentation\/mapboxmaps\/location-apis"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AppleLocationProviderDelegate":{"navigatorTitle":[{"text":"AppleLocationProviderDelegate","kind":"identifier"}],"abstract":[{"text":"The ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProviderDelegate","type":"reference"},{"text":" protocol defines a set of optional methods that you","type":"text"},{"text":" ","type":"text"},{"text":"can use to receive events from an associated location provider object.","type":"text"}],"role":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/applelocationproviderdelegate","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProviderDelegate","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AppleLocationProviderDelegate","kind":"identifier"}],"title":"AppleLocationProviderDelegate"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PuckRenderingData":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PuckRenderingData","kind":"identifier"}],"role":"symbol","title":"PuckRenderingData","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckRenderingData","url":"\/documentation\/mapboxmaps\/puckrenderingdata","type":"topic","abstract":[{"type":"text","text":"Represents the interpolated data ready to render the user location puck."}],"kind":"symbol","navigatorTitle":[{"text":"PuckRenderingData","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Heading":{"url":"\/documentation\/mapboxmaps\/heading","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Heading","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"Heading","kind":"identifier"}],"type":"topic","kind":"symbol","title":"Heading","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Heading","abstract":[{"type":"text","text":"The azimuth (orientation) of the user’s device, relative to true or magnetic north."}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article","type":"topic","title":"MapboxMaps Documentation","abstract":[],"url":"\/documentation\/overview","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeadingProvider":{"url":"\/documentation\/mapboxmaps\/headingprovider","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeadingProvider"}],"navigatorTitle":[{"kind":"identifier","text":"HeadingProvider"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingProvider","abstract":[{"type":"text","text":"Provides heading data to drive the location puck."}],"role":"symbol","type":"topic","title":"HeadingProvider"}},"variantOverrides":[{"patch":[{"value":"MBXAccuracyAuthorization","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization\/title"},{"value":[{"text":"MBXAccuracyAuthorization","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization\/fragments"},{"value":[{"kind":"identifier","text":"MBXAccuracyAuthorization"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization\/navigatorTitle"},{"value":"MBXCoordinate2D","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Coordinate2D\/title"},{"value":[{"kind":"identifier","text":"MBXCoordinate2D"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Coordinate2D\/fragments"},{"value":[{"kind":"identifier","text":"MBXCoordinate2D"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Coordinate2D\/navigatorTitle"},{"value":"MBXLocationError","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationError\/title"},{"value":[{"text":"MBXLocationError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationError\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationError\/navigatorTitle","value":[{"text":"MBXLocationError","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/title","value":"MBXPermissionStatus","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/fragments","value":[{"text":"MBXPermissionStatus","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/navigatorTitle","value":[{"kind":"identifier","text":"MBXPermissionStatus"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1IntervalSettings\/title","value":"MBXIntervalSettings","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1IntervalSettings\/fragments","value":[{"text":"MBXIntervalSettings","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1IntervalSettings\/navigatorTitle","value":[{"text":"MBXIntervalSettings","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/title","value":"MBXLocation","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/fragments","value":[{"text":"MBXLocation","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/navigatorTitle","value":[{"kind":"identifier","text":"MBXLocation"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1DeviceLocationProvider\/title","value":"MBXDeviceLocationProvider","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1DeviceLocationProvider\/fragments","value":[{"text":"MBXDeviceLocationProvider","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1DeviceLocationProvider\/navigatorTitle","value":[{"text":"MBXDeviceLocationProvider","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceFactory\/title","value":"MBXLocationServiceFactory","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceFactory\/fragments","value":[{"kind":"identifier","text":"MBXLocationServiceFactory"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceFactory\/navigatorTitle","value":[{"kind":"identifier","text":"MBXLocationServiceFactory"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/title","value":"MBXLocationProvider","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/fragments","value":[{"kind":"identifier","text":"MBXLocationProvider"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/navigatorTitle","value":[{"text":"MBXLocationProvider","kind":"identifier"}],"op":"replace"},{"value":"MBXLocationObserver","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MBXLocationObserver"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/fragments","op":"replace"},{"value":[{"text":"MBXLocationObserver","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/navigatorTitle","op":"replace"},{"value":"MBXLocationErrorCode","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MBXLocationErrorCode"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/fragments","op":"replace"},{"value":[{"text":"MBXLocationErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/navigatorTitle","op":"replace"},{"value":"MBXLocationServiceObserver","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MBXLocationServiceObserver"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver\/fragments","op":"replace"},{"value":[{"text":"MBXLocationServiceObserver","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver\/navigatorTitle","op":"replace"},{"value":"MBXLocationProviderRequest","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProviderRequest\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MBXLocationProviderRequest"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProviderRequest\/fragments","op":"replace"},{"value":[{"text":"MBXLocationProviderRequest","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProviderRequest\/navigatorTitle","op":"replace"},{"value":"MBXAccuracyLevel","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel\/title","op":"replace"},{"value":[{"text":"MBXAccuracyLevel","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel\/fragments","op":"replace"},{"value":[{"text":"MBXAccuracyLevel","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel\/navigatorTitle","op":"replace"},{"value":"MBXLocationExtraKeys","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationExtraKeys\/title","op":"replace"},{"value":[{"text":"MBXLocationExtraKeys","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationExtraKeys\/fragments","op":"replace"},{"value":[{"text":"MBXLocationExtraKeys","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationExtraKeys\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}