{"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/View-Annotations","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"title":"View Annotations","anchor":"View-Annotations","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManager","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManagerError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchorConfig","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationPositionDescriptor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationUpdateObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchor"]}],"seeAlsoSections":[{"generated":true,"title":"Annotations","anchor":"Annotations","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer-Annotations"]}],"kind":"article","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"]]},"metadata":{"modules":[{"name":"MapboxMaps"}],"title":"View Annotations","role":"collectionGroup","roleHeading":"API Collection"},"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"url":"\/documentation\/mapboxmaps","title":"MapboxMaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationOptions":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ViewAnnotationOptions","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationOptions","navigatorTitle":[{"text":"ViewAnnotationOptions","kind":"identifier"}],"title":"ViewAnnotationOptions","abstract":[{"text":"Stores layout and visibility settings for a view annotation.","type":"text"}],"url":"\/documentation\/mapboxmaps\/viewannotationoptions","kind":"symbol","type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationUpdateObserver":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ViewAnnotationUpdateObserver"}],"navigatorTitle":[{"kind":"identifier","text":"ViewAnnotationUpdateObserver"}],"abstract":[{"text":"An interface you use to detect when the map view lays out or updates visibility of annotation views.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationUpdateObserver","type":"topic","title":"ViewAnnotationUpdateObserver","kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/viewannotationupdateobserver"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article","type":"topic","title":"MapboxMaps Documentation","abstract":[],"url":"\/documentation\/overview","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationAnchorConfig":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchorConfig","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ViewAnnotationAnchorConfig","kind":"identifier"}],"abstract":[{"type":"text","text":"Represents a specific setting for a view annotation anchor."}],"type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/viewannotationanchorconfig","navigatorTitle":[{"text":"ViewAnnotationAnchorConfig","kind":"identifier"}],"title":"ViewAnnotationAnchorConfig","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationPositionDescriptor":{"url":"\/documentation\/mapboxmaps\/viewannotationpositiondescriptor","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ViewAnnotationPositionDescriptor"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationPositionDescriptor","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ViewAnnotationPositionDescriptor"}],"abstract":[{"type":"text","text":"Read-only data that is needed to correctly position the single view annotation on screen."},{"type":"text","text":" "},{"type":"text","text":"Used inside ViewAnnotationPositionsUpdateListener callback to notify the listener about the visible view annotations’ position updates."}],"title":"ViewAnnotationPositionDescriptor"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationAnchor":{"kind":"symbol","navigatorTitle":[{"text":"ViewAnnotationAnchor","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchor","abstract":[{"type":"text","text":"Enum describing how to place view annotation relatively to geometry."}],"url":"\/documentation\/mapboxmaps\/viewannotationanchor","title":"ViewAnnotationAnchor","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ViewAnnotationAnchor","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layer-Annotations":{"title":"Layer Annotations","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer-Annotations","type":"topic","url":"\/documentation\/mapboxmaps\/layer-annotations","kind":"article","role":"collectionGroup","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotation":{"url":"\/documentation\/mapboxmaps\/viewannotation","navigatorTitle":[{"kind":"identifier","text":"ViewAnnotation"}],"abstract":[{"type":"text","text":"Creates a view annotation."}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ViewAnnotation"}],"role":"symbol","title":"ViewAnnotation","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationManager":{"navigatorTitle":[{"kind":"identifier","text":"ViewAnnotationManager"}],"role":"symbol","abstract":[{"text":"Manager API to control View Annotations.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManager","kind":"symbol","url":"\/documentation\/mapboxmaps\/viewannotationmanager","type":"topic","title":"ViewAnnotationManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ViewAnnotationManager"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationManagerError":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ViewAnnotationManagerError","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/viewannotationmanagererror","abstract":[],"navigatorTitle":[{"text":"ViewAnnotationManagerError","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationManagerError","role":"symbol","kind":"symbol","type":"topic","title":"ViewAnnotationManagerError"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchorConfig\/title","value":"MBMViewAnnotationAnchorConfig","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchorConfig\/fragments","value":[{"kind":"identifier","text":"MBMViewAnnotationAnchorConfig"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchorConfig\/navigatorTitle","value":[{"text":"MBMViewAnnotationAnchorConfig","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationPositionDescriptor\/title","value":"MBMViewAnnotationPositionDescriptor","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationPositionDescriptor\/fragments","value":[{"text":"MBMViewAnnotationPositionDescriptor","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationPositionDescriptor\/navigatorTitle","value":[{"kind":"identifier","text":"MBMViewAnnotationPositionDescriptor"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchor\/title","value":"MBMViewAnnotationAnchor","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchor\/fragments","value":[{"kind":"identifier","text":"MBMViewAnnotationAnchor"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchor\/navigatorTitle","value":[{"text":"MBMViewAnnotationAnchor","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}