{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers"]]},"metadata":{"externalID":"s:10MapboxMaps10ModelLayerV","modules":[{"name":"MapboxMaps"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ModelLayer","kind":"identifier"}],"title":"ModelLayer","tags":[{"type":"spi","text":"SPI"}],"role":"symbol","roleHeading":"Structure","symbolKind":"struct","navigatorTitle":[{"kind":"identifier","text":"ModelLayer"}]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/init(id:source:)"],"generated":true,"anchor":"Initializers"},{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/filter","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/id","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/maxZoom","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/minZoom","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/modelAmbientOcclusionIntensity","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/modelAmbientOcclusionIntensityTransition","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/modelCastShadows","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/modelColor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/modelColorMixIntensity","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/modelColorMixIntensityTransition","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/modelColorTransition","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/modelCutoffFadeRange","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/modelEmissiveStrength","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/modelEmissiveStrengthTransition","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/modelHeightBasedEmissiveStrengthMultiplier","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/modelHeightBasedEmissiveStrengthMultiplierTransition","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/modelId","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/modelOpacity","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/modelOpacityTransition","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/modelReceiveShadows","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/modelRotation","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/modelRotationTransition","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/modelRoughness","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/modelRoughnessTransition","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/modelScale","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/modelScaleMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/modelScaleTransition","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/modelTranslation","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/modelTranslationTransition","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/modelType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/slot","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/source","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/sourceLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/type","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/visibility"]},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/Equatable-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/Layer-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/StyleEncodable-Implementations"],"anchor":"Default-Implementations","title":"Default Implementations","generated":true}],"abstract":[{"type":"text","text":"A layer to render 3D Models."}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerInfo","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/BackgroundLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CircleLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillExtrusionLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationIndicatorLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterParticleLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SkyLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderConfiguration","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerHost","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ElevationData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Slot","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SlotLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerAtPosition","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClipLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClipLayerTypes"],"anchor":"Layers","title":"Layers","generated":true}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/modellayer"]}],"sections":[],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapStyleContent","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDecodable","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleEncodable","doc:\/\/com.mapbox.MapboxMaps\/Se","doc:\/\/com.mapbox.MapboxMaps\/SE","doc:\/\/com.mapbox.MapboxMaps\/SQ"],"title":"Conforms To","type":"conformsTo"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ModelLayer","kind":"identifier"}]}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeatmapLayer":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer","abstract":[{"type":"text","text":"A heatmap."}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HeatmapLayer"}],"title":"HeatmapLayer","url":"\/documentation\/mapboxmaps\/heatmaplayer","navigatorTitle":[{"kind":"identifier","text":"HeatmapLayer"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelLayer/modelCutoffFadeRange":{"title":"modelCutoffFadeRange","type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/modellayer\/modelcutofffaderange","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/modelCutoffFadeRange","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"modelCutoffFadeRange"},{"kind":"text","text":": "},{"text":"Value","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps5ValueO"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":">?","kind":"text"}],"abstract":[{"text":"This parameter defines the range for the fade-out effect before an automatic content cutoff  on pitched map views. The automatic cutoff range is calculated according to the minimum required zoom level of the source and layer. The fade range is expressed in relation to the height of the map view. A value of 1.0 indicates that the content is faded to the same extent as the map’s height in pixels, while a value close to zero represents a sharp cutoff. When the value is set to 0.0, the cutoff is completely disabled. Note: The property has no effect on the map if terrain is enabled.","type":"text"},{"text":" ","type":"text"},{"text":"Default value: 0. Value range: [0, 1]","type":"text"}],"tags":[{"text":"SPI","type":"spi"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FillLayer":{"abstract":[{"type":"text","text":"A filled polygon with an optional stroked border."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FillLayer"}],"url":"\/documentation\/mapboxmaps\/filllayer","role":"symbol","type":"topic","title":"FillLayer","navigatorTitle":[{"text":"FillLayer","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillLayer","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelLayer/slot":{"title":"slot","type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/modellayer\/slot","abstract":[{"text":"The slot this layer is assigned to. If specified, and a slot with that name exists, it will be placed at that position in the layer order.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"slot"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps4SlotV","text":"Slot"},{"kind":"text","text":"?"}],"tags":[{"text":"SPI","type":"spi"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/slot"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Slot":{"url":"\/documentation\/mapboxmaps\/slot","title":"Slot","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Slot","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"Slot","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Slot"}],"abstract":[{"type":"text","text":"A pre-specified location in the style where layer will be added to"},{"type":"text","text":" "},{"type":"text","text":"(such as on top of existing land layers, but below all labels)."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layers":{"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers","abstract":[],"url":"\/documentation\/mapboxmaps\/layers","title":"Layers","role":"collectionGroup","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelLayer/modelRotation":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/modelRotation","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"modelRotation","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps5ValueO","text":"Value","kind":"typeIdentifier"},{"kind":"text","text":"<["},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":"]>?","kind":"text"}],"type":"topic","title":"modelRotation","url":"\/documentation\/mapboxmaps\/modellayer\/modelrotation","abstract":[{"text":"The rotation of the model in euler angles [lon, lat, z].","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Default value: [0,0,0]."}],"kind":"symbol","tags":[{"text":"SPI","type":"spi"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelLayer/modelRoughnessTransition":{"title":"modelRoughnessTransition","kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/modellayer\/modelroughnesstransition","abstract":[{"text":"Transition options for ","type":"text"},{"type":"codeVoice","code":"modelRoughness"},{"type":"text","text":"."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"modelRoughnessTransition"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10MapboxMaps15StyleTransitionV","text":"StyleTransition","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"tags":[{"text":"SPI","type":"spi"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/modelRoughnessTransition"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelLayer/modelCastShadows":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/modelCastShadows","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"modelCastShadows","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps5ValueO","text":"Value"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":">?"}],"type":"topic","title":"modelCastShadows","url":"\/documentation\/mapboxmaps\/modellayer\/modelcastshadows","abstract":[{"text":"Enable\/Disable shadow casting for this layer","type":"text"},{"text":" ","type":"text"},{"text":"Default value: true.","type":"text"}],"kind":"symbol","tags":[{"type":"spi","text":"SPI"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapStyleContent":{"abstract":[{"type":"text","text":"A protocol used to create any type of  map style content, such as layers, sources, lighting and others."}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapStyleContent"}],"url":"\/documentation\/mapboxmaps\/mapstylecontent","role":"symbol","type":"topic","title":"MapStyleContent","navigatorTitle":[{"kind":"identifier","text":"MapStyleContent"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapStyleContent","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelLayer/modelColor":{"title":"modelColor","kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/modellayer\/modelcolor","abstract":[{"type":"text","text":"The tint color of the model layer. model-color-mix-intensity (defaults to 0) defines tint(mix) intensity - this means that, this color is not used unless model-color-mix-intensity gets value greater than 0."},{"text":" ","type":"text"},{"text":"Default value: “#ffffff”.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"modelColor","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps5ValueO","text":"Value"},{"text":"<","kind":"text"},{"text":"StyleColor","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps10StyleColorV"},{"kind":"text","text":">?"}],"tags":[{"text":"SPI","type":"spi"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/modelColor"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer":{"abstract":[{"type":"text","text":"Client-side hillshading visualization based on DEM data. Currently, the implementation only supports Mapbox Terrain RGB and Mapzen Terrarium tiles."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"HillshadeLayer"}],"url":"\/documentation\/mapboxmaps\/hillshadelayer","role":"symbol","type":"topic","title":"HillshadeLayer","navigatorTitle":[{"text":"HillshadeLayer","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelLayer/modelId":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/modelId","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"modelId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Value","preciseIdentifier":"s:10MapboxMaps5ValueO"},{"text":"<","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":">?","kind":"text"}],"type":"topic","title":"modelId","url":"\/documentation\/mapboxmaps\/modellayer\/modelid","abstract":[{"text":"Model to render. It can be either a string referencing an element to the models root property or an internal or external URL","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Default value: “”."}],"kind":"symbol","tags":[{"type":"spi","text":"SPI"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelLayer/sourceLayer":{"title":"sourceLayer","kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/modellayer\/sourcelayer","abstract":[{"type":"text","text":"Layer to use from a vector tile source."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sourceLayer"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"tags":[{"text":"SPI","type":"spi"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/sourceLayer"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelLayer":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer","abstract":[{"type":"text","text":"A layer to render 3D Models."}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ModelLayer"}],"title":"ModelLayer","url":"\/documentation\/mapboxmaps\/modellayer","navigatorTitle":[{"kind":"identifier","text":"ModelLayer"}],"tags":[{"type":"spi","text":"SPI"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelLayer/maxZoom":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/maxZoom","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxZoom","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":"?","kind":"text"}],"type":"topic","title":"maxZoom","url":"\/documentation\/mapboxmaps\/modellayer\/maxzoom","abstract":[{"text":"The maximum zoom level for the layer. At zoom levels equal to or greater than the maxzoom, the layer will be hidden.","type":"text"}],"kind":"symbol","tags":[{"type":"spi","text":"SPI"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layer":{"url":"\/documentation\/mapboxmaps\/layer","title":"Layer","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Layer"}],"role":"symbol","navigatorTitle":[{"text":"Layer","kind":"identifier"}],"abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayer":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayer","abstract":[{"type":"text","text":"Layer with custom rendering implementation"}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"CustomLayer","kind":"identifier"}],"title":"CustomLayer","url":"\/documentation\/mapboxmaps\/customlayer","navigatorTitle":[{"text":"CustomLayer","kind":"identifier"}],"tags":[{"text":"SPI","type":"spi"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelLayer/modelReceiveShadows":{"title":"modelReceiveShadows","kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/modellayer\/modelreceiveshadows","abstract":[{"type":"text","text":"Enable\/Disable shadow receiving for this layer"},{"text":" ","type":"text"},{"type":"text","text":"Default value: true."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"modelReceiveShadows","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Value","preciseIdentifier":"s:10MapboxMaps5ValueO","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":">?"}],"tags":[{"text":"SPI","type":"spi"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/modelReceiveShadows"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelLayer/minZoom":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/minZoom","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"minZoom","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","title":"minZoom","url":"\/documentation\/mapboxmaps\/modellayer\/minzoom","abstract":[{"text":"The minimum zoom level for the layer. At zoom levels less than the minzoom, the layer will be hidden.","type":"text"}],"kind":"symbol","tags":[{"text":"SPI","type":"spi"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelLayer/modelScaleTransition":{"title":"modelScaleTransition","kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/modellayer\/modelscaletransition","abstract":[{"text":"Transition options for ","type":"text"},{"type":"codeVoice","code":"modelScale"},{"text":".","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"modelScaleTransition","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps15StyleTransitionV","text":"StyleTransition"},{"kind":"text","text":"?"}],"tags":[{"type":"spi","text":"SPI"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/modelScaleTransition"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelLayer/modelAmbientOcclusionIntensity":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/modelAmbientOcclusionIntensity","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"modelAmbientOcclusionIntensity","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps5ValueO","text":"Value","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":">?"}],"type":"topic","title":"modelAmbientOcclusionIntensity","url":"\/documentation\/mapboxmaps\/modellayer\/modelambientocclusionintensity","abstract":[{"type":"text","text":"Intensity of the ambient occlusion if present in the 3D model."},{"type":"text","text":" "},{"type":"text","text":"Default value: 1. Value range: [0, 1]"}],"kind":"symbol","tags":[{"type":"spi","text":"SPI"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerRenderParameters":{"abstract":[{"text":"Parameters that define the current camera position for a ","type":"text"},{"type":"codeVoice","code":"CustomLayerHost::render()"},{"type":"text","text":" function."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CustomLayerRenderParameters"}],"url":"\/documentation\/mapboxmaps\/customlayerrenderparameters","role":"symbol","type":"topic","title":"CustomLayerRenderParameters","navigatorTitle":[{"kind":"identifier","text":"CustomLayerRenderParameters"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleDecodable":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDecodable","kind":"symbol","url":"\/documentation\/mapboxmaps\/styledecodable","abstract":[{"type":"text","text":"A protocol describing a style-related entity that can be decoded."}],"title":"StyleDecodable","navigatorTitle":[{"kind":"identifier","text":"StyleDecodable"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"StyleDecodable"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerHost":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerHost","kind":"symbol","url":"\/documentation\/mapboxmaps\/customlayerhost","abstract":[{"type":"text","text":"Interface for hosting a custom map style layer."}],"title":"CustomLayerHost","navigatorTitle":[{"kind":"identifier","text":"CustomLayerHost"}],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"CustomLayerHost","kind":"identifier"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelLayer/modelTranslation":{"title":"modelTranslation","kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/modellayer\/modeltranslation","abstract":[{"type":"text","text":"The translation of the model in meters in form of [longitudal, latitudal, altitude] offsets."},{"type":"text","text":" "},{"type":"text","text":"Default value: [0,0,0]."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"modelTranslation"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps5ValueO","text":"Value","kind":"typeIdentifier"},{"text":"<[","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":"]>?","kind":"text"}],"tags":[{"type":"spi","text":"SPI"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/modelTranslation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelLayer/modelTranslationTransition":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/modelTranslationTransition","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"modelTranslationTransition","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"StyleTransition","preciseIdentifier":"s:10MapboxMaps15StyleTransitionV"},{"text":"?","kind":"text"}],"type":"topic","title":"modelTranslationTransition","url":"\/documentation\/mapboxmaps\/modellayer\/modeltranslationtransition","abstract":[{"type":"text","text":"Transition options for "},{"code":"modelTranslation","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","tags":[{"type":"spi","text":"SPI"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelLayer/StyleEncodable-Implementations":{"title":"StyleEncodable Implementations","kind":"article","type":"topic","url":"\/documentation\/mapboxmaps\/modellayer\/styleencodable-implementations","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/StyleEncodable-Implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/BackgroundLayer":{"abstract":[{"type":"text","text":"The background color or pattern of the map."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BackgroundLayer","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/backgroundlayer","role":"symbol","type":"topic","title":"BackgroundLayer","navigatorTitle":[{"text":"BackgroundLayer","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/BackgroundLayer","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelLayer/modelRoughness":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/modelRoughness","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"modelRoughness"},{"kind":"text","text":": "},{"text":"Value","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps5ValueO"},{"text":"<","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"kind":"text","text":">?"}],"type":"topic","title":"modelRoughness","url":"\/documentation\/mapboxmaps\/modellayer\/modelroughness","abstract":[{"type":"text","text":"Material roughness. Material is fully smooth for value 0, and fully rough for value 1. Affects only layers using batched-model source."},{"text":" ","type":"text"},{"text":"Default value: 1. Value range: [0, 1]","type":"text"}],"kind":"symbol","tags":[{"type":"spi","text":"SPI"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelLayer/modelColorMixIntensity":{"title":"modelColorMixIntensity","kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/modellayer\/modelcolormixintensity","abstract":[{"type":"text","text":"Intensity of model-color (on a scale from 0 to 1) in color mix with original 3D model’s colors. Higher number will present a higher model-color contribution in mix."},{"text":" ","type":"text"},{"text":"Default value: 0. Value range: [0, 1]","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"modelColorMixIntensity","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Value","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps5ValueO"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":">?","kind":"text"}],"tags":[{"type":"spi","text":"SPI"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/modelColorMixIntensity"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelLayer/type":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/type","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps9LayerTypeV","text":"LayerType","kind":"typeIdentifier"}],"type":"topic","title":"type","url":"\/documentation\/mapboxmaps\/modellayer\/type","abstract":[{"type":"text","text":"Rendering type of this layer."}],"kind":"symbol","tags":[{"text":"SPI","type":"spi"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SymbolLayer":{"type":"topic","abstract":[{"text":"An icon or a text label.","type":"text"}],"navigatorTitle":[{"text":"SymbolLayer","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SymbolLayer"}],"kind":"symbol","title":"SymbolLayer","role":"symbol","url":"\/documentation\/mapboxmaps\/symbollayer","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolLayer"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerRenderConfiguration":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderConfiguration","kind":"symbol","url":"\/documentation\/mapboxmaps\/customlayerrenderconfiguration","abstract":[{"text":"Note! This is an experimental feature. It can be changed or removed in future versions.","type":"text"}],"title":"CustomLayerRenderConfiguration","navigatorTitle":[{"text":"CustomLayerRenderConfiguration","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CustomLayerRenderConfiguration","kind":"identifier"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FillExtrusionLayer":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillExtrusionLayer","kind":"symbol","url":"\/documentation\/mapboxmaps\/fillextrusionlayer","abstract":[{"type":"text","text":"An extruded (3D) polygon."}],"title":"FillExtrusionLayer","navigatorTitle":[{"text":"FillExtrusionLayer","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FillExtrusionLayer"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelLayer/modelAmbientOcclusionIntensityTransition":{"title":"modelAmbientOcclusionIntensityTransition","kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/modellayer\/modelambientocclusionintensitytransition","abstract":[{"text":"Transition options for ","type":"text"},{"type":"codeVoice","code":"modelAmbientOcclusionIntensity"},{"text":".","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"modelAmbientOcclusionIntensityTransition"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps15StyleTransitionV","text":"StyleTransition"},{"kind":"text","text":"?"}],"tags":[{"text":"SPI","type":"spi"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/modelAmbientOcclusionIntensityTransition"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelLayer/modelScale":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/modelScale","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"modelScale"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps5ValueO","text":"Value","kind":"typeIdentifier"},{"kind":"text","text":"<["},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":"]>?","kind":"text"}],"type":"topic","title":"modelScale","url":"\/documentation\/mapboxmaps\/modellayer\/modelscale","abstract":[{"text":"The scale of the model.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Default value: [1,1,1]."}],"kind":"symbol","tags":[{"type":"spi","text":"SPI"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterLayer":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterLayer","navigatorTitle":[{"text":"RasterLayer","kind":"identifier"}],"abstract":[{"text":"Raster map textures such as satellite imagery.","type":"text"}],"url":"\/documentation\/mapboxmaps\/rasterlayer","title":"RasterLayer","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RasterLayer","kind":"identifier"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ClipLayer":{"tags":[{"type":"spi","text":"SPI"}],"title":"ClipLayer","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ClipLayer"}],"abstract":[{"type":"text","text":"Layer that removes 3D content from map."}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClipLayer","navigatorTitle":[{"text":"ClipLayer","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/cliplayer","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","abstract":[],"type":"topic","kind":"article","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SlotLayer":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SlotLayer","kind":"symbol","url":"\/documentation\/mapboxmaps\/slotlayer","abstract":[{"text":"Marks the position of a slot.","type":"text"}],"title":"SlotLayer","navigatorTitle":[{"text":"SlotLayer","kind":"identifier"}],"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SlotLayer"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelLayer/modelOpacityTransition":{"title":"modelOpacityTransition","kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/modellayer\/modelopacitytransition","abstract":[{"type":"text","text":"Transition options for "},{"code":"modelOpacity","type":"codeVoice"},{"type":"text","text":"."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"modelOpacityTransition","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10MapboxMaps15StyleTransitionV","text":"StyleTransition","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"tags":[{"text":"SPI","type":"spi"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/modelOpacityTransition"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelLayer/Equatable-Implementations":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/Equatable-Implementations","kind":"article","type":"topic","title":"Equatable Implementations","abstract":[],"url":"\/documentation\/mapboxmaps\/modellayer\/equatable-implementations","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/SQ":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelLayer/init(id:source:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/init(id:source:)","kind":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"id","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"source","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"title":"init(id:source:)","abstract":[],"url":"\/documentation\/mapboxmaps\/modellayer\/init(id:source:)","tags":[{"text":"SPI","type":"spi"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelLayer/Layer-Implementations":{"title":"Layer Implementations","type":"topic","kind":"article","url":"\/documentation\/mapboxmaps\/modellayer\/layer-implementations","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/Layer-Implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerInfo":{"url":"\/documentation\/mapboxmaps\/layerinfo","title":"LayerInfo","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerInfo","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LayerInfo"}],"role":"symbol","navigatorTitle":[{"text":"LayerInfo","kind":"identifier"}],"abstract":[{"type":"text","text":"Information about a layer"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SkyLayer":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SkyLayer","kind":"symbol","url":"\/documentation\/mapboxmaps\/skylayer","abstract":[{"type":"text","text":"A spherical dome around the map that is always rendered behind all other layers."},{"type":"text","text":" "},{"type":"text","text":"Warning: As of v10.6.0, "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Atmosphere"},{"text":" is the preferred method for atmospheric styling. Sky layer is not supported by the globe projection, and will be phased out in future major release.","type":"text"}],"title":"SkyLayer","navigatorTitle":[{"text":"SkyLayer","kind":"identifier"}],"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SkyLayer","kind":"identifier"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerAtPosition":{"abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"LayerAtPosition","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/layeratposition","role":"symbol","type":"topic","title":"LayerAtPosition","navigatorTitle":[{"text":"LayerAtPosition","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerAtPosition","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"role":"collection","url":"\/documentation\/mapboxmaps","title":"MapboxMaps","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelLayer/modelColorMixIntensityTransition":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/modelColorMixIntensityTransition","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"modelColorMixIntensityTransition","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps15StyleTransitionV","text":"StyleTransition"},{"text":"?","kind":"text"}],"title":"modelColorMixIntensityTransition","abstract":[{"text":"Transition options for ","type":"text"},{"type":"codeVoice","code":"modelColorMixIntensity"},{"type":"text","text":"."}],"url":"\/documentation\/mapboxmaps\/modellayer\/modelcolormixintensitytransition","tags":[{"text":"SPI","type":"spi"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CircleLayer":{"role":"symbol","navigatorTitle":[{"text":"CircleLayer","kind":"identifier"}],"type":"topic","kind":"symbol","title":"CircleLayer","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CircleLayer","abstract":[{"text":"A filled circle.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CircleLayer"}],"url":"\/documentation\/mapboxmaps\/circlelayer"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ElevationData":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ElevationData","kind":"symbol","url":"\/documentation\/mapboxmaps\/elevationdata","abstract":[{"type":"text","text":"Interface that provides access to elevation data."}],"title":"ElevationData","navigatorTitle":[{"kind":"identifier","text":"ElevationData"}],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ElevationData"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleEncodable":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleEncodable","kind":"symbol","url":"\/documentation\/mapboxmaps\/styleencodable","abstract":[{"type":"text","text":"A protocol describing a style-related entity that can be encoded."}],"title":"StyleEncodable","navigatorTitle":[{"kind":"identifier","text":"StyleEncodable"}],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"StyleEncodable"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelLayer/modelType":{"title":"modelType","type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/modellayer\/modeltype","abstract":[{"text":"Defines rendering behavior of model in respect to other 3D scene objects.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Default value: “common-3d”."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"modelType"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps5ValueO","text":"Value","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps9ModelTypeV","text":"ModelType"},{"kind":"text","text":">?"}],"tags":[{"type":"spi","text":"SPI"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/modelType"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ClipLayerTypes":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClipLayerTypes","kind":"symbol","url":"\/documentation\/mapboxmaps\/cliplayertypes","abstract":[{"type":"text","text":"Layer types that will also be removed if fallen below this clip layer."}],"title":"ClipLayerTypes","navigatorTitle":[{"kind":"identifier","text":"ClipLayerTypes"}],"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ClipLayerTypes"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelLayer/modelHeightBasedEmissiveStrengthMultiplierTransition":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/modelHeightBasedEmissiveStrengthMultiplierTransition","kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"modelHeightBasedEmissiveStrengthMultiplierTransition","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10MapboxMaps15StyleTransitionV","text":"StyleTransition","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"modelHeightBasedEmissiveStrengthMultiplierTransition","abstract":[{"type":"text","text":"Transition options for "},{"code":"modelHeightBasedEmissiveStrengthMultiplier","type":"codeVoice"},{"type":"text","text":"."}],"url":"\/documentation\/mapboxmaps\/modellayer\/modelheightbasedemissivestrengthmultipliertransition","tags":[{"type":"spi","text":"SPI"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelLayer/modelOpacity":{"title":"modelOpacity","type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/modellayer\/modelopacity","abstract":[{"type":"text","text":"The opacity of the model layer."},{"type":"text","text":" "},{"text":"Default value: 1. Value range: [0, 1]","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"modelOpacity","kind":"identifier"},{"kind":"text","text":": "},{"text":"Value","preciseIdentifier":"s:10MapboxMaps5ValueO","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"kind":"text","text":">?"}],"tags":[{"text":"SPI","type":"spi"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/modelOpacity"},"doc://com.mapbox.MapboxMaps/Se":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/Se","title":"Swift.Decodable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelLayer/visibility":{"title":"visibility","type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/modellayer\/visibility","abstract":[{"text":"Whether this layer is displayed.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"visibility","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps5ValueO","text":"Value"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"Visibility","preciseIdentifier":"s:10MapboxMaps10VisibilityO"},{"text":">","kind":"text"}],"tags":[{"text":"SPI","type":"spi"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/visibility"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelLayer/modelScaleMode":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/modelScaleMode","kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"modelScaleMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Value","preciseIdentifier":"s:10MapboxMaps5ValueO","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"text":"ModelScaleMode","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps14ModelScaleModeV"},{"kind":"text","text":">?"}],"title":"modelScaleMode","abstract":[{"text":"Defines scaling mode. Only applies to location-indicator type layers.","type":"text"},{"type":"text","text":" "},{"text":"Default value: “map”.","type":"text"}],"url":"\/documentation\/mapboxmaps\/modellayer\/modelscalemode","tags":[{"type":"spi","text":"SPI"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelLayer/modelRotationTransition":{"title":"modelRotationTransition","type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/modellayer\/modelrotationtransition","abstract":[{"type":"text","text":"Transition options for "},{"code":"modelRotation","type":"codeVoice"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"modelRotationTransition","kind":"identifier"},{"kind":"text","text":": "},{"text":"StyleTransition","preciseIdentifier":"s:10MapboxMaps15StyleTransitionV","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"tags":[{"text":"SPI","type":"spi"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/modelRotationTransition"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LineLayer":{"navigatorTitle":[{"text":"LineLayer","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"A stroked line."}],"url":"\/documentation\/mapboxmaps\/linelayer","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineLayer","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LineLayer"}],"title":"LineLayer"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelLayer/filter":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/filter","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"filter"},{"kind":"text","text":": "},{"text":"Exp","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps3ExpV"},{"kind":"text","text":"?"}],"title":"filter","abstract":[{"text":"An expression specifying conditions on source features.","type":"text"},{"text":" ","type":"text"},{"text":"Only features that match the filter are displayed.","type":"text"}],"url":"\/documentation\/mapboxmaps\/modellayer\/filter","tags":[{"type":"spi","text":"SPI"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/SE":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SE","title":"Swift.Encodable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelLayer/source":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/source","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"source","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"source","abstract":[{"type":"text","text":"Name of a source description to be used for this layer."},{"text":" ","type":"text"},{"text":"Required for all layer types except ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/BackgroundLayer","isActive":true},{"text":", ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SkyLayer","isActive":true},{"text":", and ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationIndicatorLayer"},{"text":".","type":"text"}],"url":"\/documentation\/mapboxmaps\/modellayer\/source","tags":[{"type":"spi","text":"SPI"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelLayer/modelEmissiveStrengthTransition":{"title":"modelEmissiveStrengthTransition","type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/modellayer\/modelemissivestrengthtransition","abstract":[{"type":"text","text":"Transition options for "},{"type":"codeVoice","code":"modelEmissiveStrength"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"modelEmissiveStrengthTransition"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps15StyleTransitionV","text":"StyleTransition","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"tags":[{"type":"spi","text":"SPI"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/modelEmissiveStrengthTransition"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Atmosphere":{"url":"\/documentation\/mapboxmaps\/atmosphere","title":"Atmosphere","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Atmosphere","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Atmosphere"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Atmosphere"}],"abstract":[{"type":"text","text":"A style’s fog property is a global effect that improves depth perception by fading out distant objects."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LocationIndicatorLayer":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationIndicatorLayer","abstract":[{"text":"Location Indicator layer.","type":"text"}],"url":"\/documentation\/mapboxmaps\/locationindicatorlayer","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"LocationIndicatorLayer","kind":"identifier"}],"title":"LocationIndicatorLayer","navigatorTitle":[{"text":"LocationIndicatorLayer","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelLayer/modelHeightBasedEmissiveStrengthMultiplier":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/modelHeightBasedEmissiveStrengthMultiplier","kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"modelHeightBasedEmissiveStrengthMultiplier","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps5ValueO","text":"Value"},{"text":"<[","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":"]>?","kind":"text"}],"title":"modelHeightBasedEmissiveStrengthMultiplier","abstract":[{"type":"text","text":"Emissive strength multiplier along model height (gradient begin, gradient end, value at begin, value at end, gradient curve power (logarithmic scale, curve power = pow(10, val))."},{"text":" ","type":"text"},{"text":"Default value: [1,1,1,1,0].","type":"text"}],"url":"\/documentation\/mapboxmaps\/modellayer\/modelheightbasedemissivestrengthmultiplier","tags":[{"type":"spi","text":"SPI"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelLayer/id":{"title":"id","type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/modellayer\/id","abstract":[{"type":"text","text":"Unique layer name"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"tags":[{"text":"SPI","type":"spi"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/id"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterParticleLayer":{"type":"topic","role":"symbol","abstract":[{"text":"Particle animation driven by textures such as wind maps.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterParticleLayer","navigatorTitle":[{"text":"RasterParticleLayer","kind":"identifier"}],"title":"RasterParticleLayer","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RasterParticleLayer","kind":"identifier"}],"tags":[{"text":"SPI","type":"spi"}],"url":"\/documentation\/mapboxmaps\/rasterparticlelayer"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerType":{"url":"\/documentation\/mapboxmaps\/layertype","title":"LayerType","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LayerType"}],"role":"symbol","navigatorTitle":[{"text":"LayerType","kind":"identifier"}],"abstract":[{"type":"text","text":"Struct of supported Layer rendering types"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelLayer/modelEmissiveStrength":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/modelEmissiveStrength","kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"modelEmissiveStrength","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps5ValueO","text":"Value"},{"kind":"text","text":"<"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":">?"}],"title":"modelEmissiveStrength","abstract":[{"text":"Strength of the emission. There is no emission for value 0. For value 1.0, only emissive component (no shading) is displayed and values above 1.0 produce light contribution to surrounding area, for some of the parts (e.g. doors). Expressions that depend on measure-light are not supported when using GeoJSON or vector tile as the model layer source.","type":"text"},{"type":"text","text":" "},{"text":"Default value: 0. Value range: [0, 5]","type":"text"}],"url":"\/documentation\/mapboxmaps\/modellayer\/modelemissivestrength","tags":[{"text":"SPI","type":"spi"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelLayer/modelColorTransition":{"title":"modelColorTransition","type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/modellayer\/modelcolortransition","abstract":[{"text":"Transition options for ","type":"text"},{"type":"codeVoice","code":"modelColor"},{"type":"text","text":"."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"modelColorTransition","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps15StyleTransitionV","text":"StyleTransition"},{"text":"?","kind":"text"}],"tags":[{"text":"SPI","type":"spi"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer\/modelColorTransition"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MBMCustomLayerRenderParameters","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMCustomLayerRenderParameters"}]},{"value":[{"text":"MBMCustomLayerRenderParameters","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost\/title","value":"MBMCustomLayerHost","op":"replace"},{"value":[{"kind":"identifier","text":"MBMCustomLayerHost"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost\/fragments"},{"value":[{"text":"MBMCustomLayerHost","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost\/navigatorTitle"},{"value":"MBMCustomLayerRenderConfiguration","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderConfiguration\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderConfiguration\/fragments","op":"replace","value":[{"text":"MBMCustomLayerRenderConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMCustomLayerRenderConfiguration"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ElevationData\/title","op":"replace","value":"MBMElevationData"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ElevationData\/fragments","value":[{"text":"MBMElevationData","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ElevationData\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMElevationData"}]}]}]}