{"kind":"symbol","abstract":[{"type":"text","text":"Feature returned by the query."}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedSourceFeature"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"queriedFeature"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedFeature","text":"QueriedFeature","preciseIdentifier":"c:objc(cs)MBMQueriedFeature"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/mapboxmaps\/queriedsourcefeature\/queriedfeature"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/queriedsourcefeature\/queriedfeature"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"queriedFeature","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"MapboxMaps"}],"externalID":"c:objc(cs)MBMQueriedSourceFeature(py)queriedFeature","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"queriedFeature","kind":"identifier"},{"text":": ","kind":"text"},{"text":"QueriedFeature","preciseIdentifier":"c:objc(cs)MBMQueriedFeature","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"queriedFeature","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedSourceFeature\/queriedFeature"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/QueriedSourceFeature/queriedFeature":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedSourceFeature\/queriedFeature","navigatorTitle":[{"text":"queriedFeature","kind":"identifier"}],"title":"queriedFeature","abstract":[{"text":"Feature returned by the query.","type":"text"}],"url":"\/documentation\/mapboxmaps\/queriedsourcefeature\/queriedfeature","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"queriedFeature","kind":"identifier"},{"text":": ","kind":"text"},{"text":"QueriedFeature","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMQueriedFeature"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article","type":"topic","title":"MapboxMaps Documentation","abstract":[],"url":"\/documentation\/overview","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"url":"\/documentation\/mapboxmaps","title":"MapboxMaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/QueriedSourceFeature":{"abstract":[{"type":"text","text":"Represents query result that is returned in QuerySourceFeaturesCallback."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedSourceFeature","kind":"symbol","type":"topic","title":"QueriedSourceFeature","role":"symbol","url":"\/documentation\/mapboxmaps\/queriedsourcefeature","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"QueriedSourceFeature","kind":"identifier"}],"navigatorTitle":[{"text":"QueriedSourceFeature","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"url":"\/documentation\/mapboxmaps\/mapboxmap-apis","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","abstract":[],"type":"topic","title":"MapboxMap","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/QueriedFeature":{"title":"QueriedFeature","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedFeature","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"QueriedFeature","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"QueriedFeature","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Represents queried feature that is returned through ","type":"text"},{"type":"codeVoice","code":"QueriedRenderedFeature"},{"text":" or ","type":"text"},{"type":"codeVoice","code":"QueriedSourceFeature"}],"url":"\/documentation\/mapboxmaps\/queriedfeature"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"queriedFeature"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"queriedFeature"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"MBMQueriedFeature","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedFeature","preciseIdentifier":"c:objc(cs)MBMQueriedFeature","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"queriedFeature","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedSourceFeature~1queriedFeature\/title","value":"queriedFeature"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedSourceFeature~1queriedFeature\/fragments","value":[{"text":"queriedFeature","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedSourceFeature\/title","value":"MBMQueriedSourceFeature"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedSourceFeature\/fragments","value":[{"kind":"identifier","text":"MBMQueriedSourceFeature"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedSourceFeature\/navigatorTitle","value":[{"kind":"identifier","text":"MBMQueriedSourceFeature"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedFeature\/title","value":"MBMQueriedFeature"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedFeature\/fragments","value":[{"text":"MBMQueriedFeature","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedFeature\/navigatorTitle","value":[{"kind":"identifier","text":"MBMQueriedFeature"}]}]}]}