{"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapOptions\/size"},"metadata":{"roleHeading":"Instance Property","fragments":[{"text":"size","kind":"identifier"}],"title":"size","role":"symbol","externalID":"c:objc(cs)MBMMapOptions(py)size","symbolKind":"property","modules":[{"name":"MapboxMaps"}],"navigatorTitle":[{"kind":"identifier","text":"size"}]},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-View","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapOptions"]]},"variants":[{"paths":["\/documentation\/mapboxmaps\/mbmmapoptions\/size"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"The size to resize the map object and renderer backend.","type":"text"},{"text":" ","type":"text"},{"text":"The size is given in ","type":"text"},{"code":"platform pixel","type":"codeVoice"},{"text":" units. macOS and iOS platforms use","type":"text"},{"text":" ","type":"text"},{"text":"device-independent pixel units, while other platforms, such as Android,","type":"text"},{"text":" ","type":"text"},{"text":"use screen pixel units.","type":"text"}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"MBMSize","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Size","preciseIdentifier":"c:objc(cs)MBMSize"},{"text":" * ","kind":"text"},{"text":"size","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","abstract":[],"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","type":"topic","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMMapOptions/size":{"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The size to resize the map object and renderer backend."},{"type":"text","text":" "},{"type":"text","text":"The size is given in "},{"type":"codeVoice","code":"platform pixel"},{"type":"text","text":" units. macOS and iOS platforms use"},{"type":"text","text":" "},{"type":"text","text":"device-independent pixel units, while other platforms, such as Android,"},{"type":"text","text":" "},{"type":"text","text":"use screen pixel units."}],"fragments":[{"kind":"identifier","text":"size"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapOptions\/size","type":"topic","url":"\/documentation\/mapboxmaps\/mbmmapoptions\/size","title":"size"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","role":"collection","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map-View":{"title":"MapView","abstract":[],"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-View","url":"\/documentation\/mapboxmaps\/map-view","role":"collectionGroup","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapOptions":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapOptions","title":"MapOptions","url":"\/documentation\/mapboxmaps\/mapoptions","role":"symbol","abstract":[{"text":"Describes the map option values.","type":"text"}],"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapOptions","kind":"identifier"}],"navigatorTitle":[{"text":"MapOptions","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Size":{"abstract":[{"text":"Size type.","type":"text"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/size","title":"Size","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Size","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Size","navigatorTitle":[{"text":"Size","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapOptions\/title","value":"MBMMapOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapOptions\/fragments","value":[{"text":"MBMMapOptions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapOptions\/navigatorTitle","value":[{"text":"MBMMapOptions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Size\/title","value":"MBMSize"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Size\/fragments","value":[{"kind":"identifier","text":"MBMSize"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Size\/navigatorTitle","value":[{"text":"MBMSize","kind":"identifier"}]}]}]}