{"kind":"symbol","sections":[],"metadata":{"title":"clientCallback","role":"symbol","externalID":"c:objc(cs)MBMCustomRasterSourceOptions(py)clientCallback","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clientCallback"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MBMCustomRasterSourceClient","text":"CustomRasterSourceClient","kind":"typeIdentifier"}],"roleHeading":"Instance Property","modules":[{"name":"MapboxMaps"}],"symbolKind":"property","navigatorTitle":[{"text":"clientCallback","kind":"identifier"}]},"abstract":[{"text":"The client callback.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"clientCallback","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMCustomRasterSourceClient","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient","text":"CustomRasterSourceClient","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"inlineContent":[{"text":"Custom raster sourtce can be configured for either direct or asynchronous rendering:","type":"text"},{"type":"text","text":" "},{"type":"text","text":"When "},{"type":"codeVoice","code":"CustomRasterSourceTileStatusChangedCallback"},{"type":"text","text":" instance is provided, rendering is asynchronous, and"},{"type":"text","text":" "},{"type":"text","text":"the client should use setStyleCustomRasterSourceTileData() API to provide the tile data."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"When ","type":"text"},{"type":"codeVoice","code":"CustomRasterSourceTileRenderer"},{"text":" instance is provided, rendering is direct, and the client should","type":"text"},{"type":"text","text":" "},{"text":"render to the tile from within the ","type":"text"},{"code":"CustomRasterSourceTileRenderer.renderToTile()","type":"codeVoice"},{"type":"text","text":" method."}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/mapboxmaps\/mbmcustomrastersourceoptions\/clientcallback"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/mbmcustomrastersourceoptions\/clientcallback"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCustomRasterSourceOptions\/clientCallback","interfaceLanguage":"swift"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceOptions":{"role":"symbol","url":"\/documentation\/mapboxmaps\/customrastersourceoptions","title":"CustomRasterSourceOptions","navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceOptions"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomRasterSourceOptions","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions","abstract":[{"text":"Options for custom raster source.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceClient":{"title":"CustomRasterSourceClient","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomRasterSourceClient"}],"url":"\/documentation\/mapboxmaps\/customrastersourceclient","abstract":[],"type":"topic","navigatorTitle":[{"text":"CustomRasterSourceClient","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Sources":{"role":"collectionGroup","url":"\/documentation\/mapboxmaps\/sources","title":"Sources","kind":"article","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMCustomRasterSourceOptions/clientCallback":{"title":"clientCallback","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCustomRasterSourceOptions\/clientCallback","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientCallback"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMCustomRasterSourceClient","text":"CustomRasterSourceClient","kind":"typeIdentifier"}],"url":"\/documentation\/mapboxmaps\/mbmcustomrastersourceoptions\/clientcallback","abstract":[{"text":"The client callback.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"clientCallback"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"clientCallback"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"clientCallback"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"MBMCustomRasterSourceClient","preciseIdentifier":"c:objc(cs)MBMCustomRasterSourceClient","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient"},{"kind":"text","text":" * "},{"text":"clientCallback","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"value":"MBMCustomRasterSourceOptions","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBMCustomRasterSourceOptions"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/fragments"},{"op":"replace","value":"MBMCustomRasterSourceClient","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient\/title"},{"value":[{"text":"MBMCustomRasterSourceClient","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMCustomRasterSourceOptions~1clientCallback\/title","value":"clientCallback","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"clientCallback"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMCustomRasterSourceOptions~1clientCallback\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}