{"abstract":[{"type":"text","text":"Size of the tiles. Tile size must be a power of 2. Default is "},{"code":"512","type":"codeVoice"},{"type":"text","text":"."}],"metadata":{"externalID":"c:objc(cs)MBMCustomRasterSourceOptions(py)tileSize","title":"tileSize","navigatorTitle":[{"text":"tileSize","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"tileSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt16","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt16V"}],"roleHeading":"Instance Property","symbolKind":"property","role":"symbol","modules":[{"name":"MapboxMaps"}]},"sections":[],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCustomRasterSourceOptions\/tileSize","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"tileSize","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt16","preciseIdentifier":"s:s6UInt16V"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/mapboxmaps\/mbmcustomrastersourceoptions\/tilesize"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/mbmcustomrastersourceoptions\/tilesize"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMCustomRasterSourceOptions/tileSize":{"title":"tileSize","navigatorTitle":[{"text":"tileSize","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tileSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt16V","text":"UInt16"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCustomRasterSourceOptions\/tileSize","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Size of the tiles. Tile size must be a power of 2. Default is "},{"code":"512","type":"codeVoice"},{"type":"text","text":"."}],"type":"topic","url":"\/documentation\/mapboxmaps\/mbmcustomrastersourceoptions\/tilesize"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceOptions":{"role":"symbol","url":"\/documentation\/mapboxmaps\/customrastersourceoptions","title":"CustomRasterSourceOptions","navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceOptions"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomRasterSourceOptions","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions","abstract":[{"text":"Options for custom raster source.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Sources":{"role":"collectionGroup","url":"\/documentation\/mapboxmaps\/sources","title":"Sources","kind":"article","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"tileSize","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"tileSize"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@uint16_t","text":"uint16_t","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"tileSize","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMCustomRasterSourceOptions~1tileSize\/title","value":"tileSize","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMCustomRasterSourceOptions~1tileSize\/fragments","value":[{"kind":"identifier","text":"tileSize"}],"op":"replace"},{"op":"replace","value":"MBMCustomRasterSourceOptions","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/fragments","value":[{"kind":"identifier","text":"MBMCustomRasterSourceOptions"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}