{"metadata":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"collectPerformanceStatistics","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMPerformanceStatisticsOptions","text":"PerformanceStatisticsOptions","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"callback","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMPerformanceStatistics","text":"PerformanceStatistics","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps3MapV","text":"Map","kind":"typeIdentifier"}],"symbolKind":"method","modules":[{"name":"MapboxMaps"}],"externalID":"s:10MapboxMaps3MapV28collectPerformanceStatistics_8callbackACSo014MBMPerformanceF7OptionsCSg_ySo0hF0CctF","extendedModule":"MapboxMaps","title":"collectPerformanceStatistics(_:callback:)","roleHeading":"Instance Method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"collectPerformanceStatistics","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"options","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"PerformanceStatisticsOptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatisticsOptions","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMPerformanceStatisticsOptions"},{"text":"?, ","kind":"text"},{"text":"callback","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"keyword"},{"text":" (","kind":"text"},{"text":"PerformanceStatistics","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatistics","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMPerformanceStatistics"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":") -> ","kind":"text"},{"text":"Map","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps3MapV"}],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An "},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AnyCancelable","isActive":true},{"type":"text","text":" object that can be used to cancel performance statistics collection."}]}]},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"Use ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatisticsOptions","isActive":true,"type":"reference"},{"text":" to configure the following collection behaviours:","type":"text"},{"text":" ","type":"text"},{"text":"- Which types of sampling to perform, whether cumulative, per-frame, or both.","type":"text"},{"text":" ","type":"text"},{"text":"- Duration of sampling in milliseconds. Value 0 forces the collection of performance statistics every frame.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Utilize "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatisticsCallback"},{"type":"text","text":" to observe the collected performance statistics. The callback function is invoked"},{"type":"text","text":" "},{"type":"text","text":"after the configured sampling duration has elapsed. The callback is invoked on the main thread. The collection process is"},{"type":"text","text":" "},{"type":"text","text":"continuous; without user-input, it restarts after each callback invocation."}]},{"type":"aside","style":"note","content":[{"inlineContent":[{"type":"text","text":"Specifying a negative sampling duration or omitting the callback function will result in no operation, which will be logged for visibility."}],"type":"paragraph"}],"name":"Note"},{"type":"aside","style":"note","content":[{"inlineContent":[{"text":"The statistics collection can be canceled by setting ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" to the options parameter.","type":"text"},{"text":" ","type":"text"},{"text":"The callback function will be called every time the configured sampling duration ``PerformanceStatisticsOptions\/sasamplingDurationMillis has elapsed.","type":"text"}],"type":"paragraph"}],"name":"Note"}]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Collects CPU, GPU resource usage and timings of layers and rendering groups over a user-configurable sampling duration."},{"type":"text","text":" "},{"type":"text","text":"Use the collected information to find which layers or rendering groups might be performing poorly."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/map\/collectperformancestatistics(_:callback:)"]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/collectPerformanceStatistics(_:callback:)","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SwiftUI","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map":{"abstract":[{"type":"text","text":"A SwiftUI view that displays a Mapbox Map."}],"url":"\/documentation\/mapboxmaps\/map","role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Map","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map","navigatorTitle":[{"text":"Map","kind":"identifier"}],"title":"Map"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/collectPerformanceStatistics(_:callback:)":{"title":"collectPerformanceStatistics(_:callback:)","kind":"symbol","url":"\/documentation\/mapboxmaps\/map\/collectperformancestatistics(_:callback:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/collectPerformanceStatistics(_:callback:)","abstract":[{"text":"Collects CPU, GPU resource usage and timings of layers and rendering groups over a user-configurable sampling duration.","type":"text"},{"text":" ","type":"text"},{"text":"Use the collected information to find which layers or rendering groups might be performing poorly.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectPerformanceStatistics"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)MBMPerformanceStatisticsOptions","kind":"typeIdentifier","text":"PerformanceStatisticsOptions"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": ("},{"preciseIdentifier":"c:objc(cs)MBMPerformanceStatistics","kind":"typeIdentifier","text":"PerformanceStatistics"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:10MapboxMaps3MapV","kind":"typeIdentifier","text":"Map"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PerformanceStatisticsOptions":{"kind":"symbol","abstract":[{"type":"text","text":"Options for the following statistics collection behaviors:"}],"navigatorTitle":[{"text":"PerformanceStatisticsOptions","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatisticsOptions","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PerformanceStatisticsOptions","kind":"identifier"}],"role":"symbol","title":"PerformanceStatisticsOptions","url":"\/documentation\/mapboxmaps\/performancestatisticsoptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SwiftUI":{"role":"collectionGroup","type":"topic","title":"SwiftUI","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SwiftUI","abstract":[],"url":"\/documentation\/mapboxmaps\/swiftui"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","kind":"symbol","title":"MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PerformanceStatistics":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatistics","url":"\/documentation\/mapboxmaps\/performancestatistics","role":"symbol","title":"PerformanceStatistics","navigatorTitle":[{"text":"PerformanceStatistics","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PerformanceStatistics","kind":"identifier"}],"abstract":[{"text":"The performance statistics collected at the end of the sampling duration.","type":"text"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AnyCancelable":{"role":"symbol","title":"AnyCancelable","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnyCancelable"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AnyCancelable","url":"\/documentation\/mapboxmaps\/anycancelable","navigatorTitle":[{"kind":"identifier","text":"AnyCancelable"}],"type":"topic","abstract":[{"text":"A Cancellable object that automatically cancels on deinit.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PerformanceStatisticsCallback":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatisticsCallback","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Use this callback to observe the collected statistics. The callback is invoked at regular intervals determined by"},{"type":"text","text":" "},{"type":"text","text":"the sampling duration specified in the "},{"type":"codeVoice","code":"PerformanceStatisticsOptions"},{"type":"text","text":". The callback is invoked from the main thread."}],"url":"\/documentation\/mapboxmaps\/performancestatisticscallback","navigatorTitle":[{"kind":"identifier","text":"PerformanceStatisticsCallback"}],"title":"PerformanceStatisticsCallback","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"PerformanceStatisticsCallback"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"kind":"article","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","url":"\/documentation\/overview","title":"MapboxMaps Documentation"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatisticsOptions\/title","value":"MBMPerformanceStatisticsOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatisticsOptions\/fragments","value":[{"kind":"identifier","text":"MBMPerformanceStatisticsOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatisticsOptions\/navigatorTitle","value":[{"kind":"identifier","text":"MBMPerformanceStatisticsOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatistics\/title","value":"MBMPerformanceStatistics"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatistics\/fragments","value":[{"text":"MBMPerformanceStatistics","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatistics\/navigatorTitle","value":[{"kind":"identifier","text":"MBMPerformanceStatistics"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatisticsCallback\/title","value":"MBMPerformanceStatisticsCallback"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatisticsCallback\/fragments","value":[{"kind":"identifier","text":"MBMPerformanceStatisticsCallback"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatisticsCallback\/navigatorTitle","value":[{"text":"MBMPerformanceStatisticsCallback","kind":"identifier"}]}]}]}