{"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/mapboxmaps\/mbmgenericevent\/timeinterval"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/mbmgenericevent\/timeinterval"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMGenericEvent\/timeInterval"},"metadata":{"modules":[{"name":"MapboxMaps"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"timeInterval","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"EventTimeInterval","preciseIdentifier":"c:objc(cs)MBMEventTimeInterval"}],"role":"symbol","externalID":"c:objc(cs)MBMGenericEvent(py)timeInterval","roleHeading":"Instance Property","navigatorTitle":[{"text":"timeInterval","kind":"identifier"}],"title":"timeInterval"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GenericEvent"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"timeInterval"},{"text":": ","kind":"text"},{"text":"EventTimeInterval","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/EventTimeInterval","preciseIdentifier":"c:objc(cs)MBMEventTimeInterval","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","title":"Map events","role":"collectionGroup","type":"topic","abstract":[{"type":"text","text":"The simplified diagram of the events emitted by the map is displayed below."}],"url":"\/documentation\/mapboxmaps\/events","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMGenericEvent/timeInterval":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timeInterval","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMEventTimeInterval","text":"EventTimeInterval"}],"navigatorTitle":[{"text":"timeInterval","kind":"identifier"}],"kind":"symbol","abstract":[],"url":"\/documentation\/mapboxmaps\/mbmgenericevent\/timeinterval","title":"timeInterval","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMGenericEvent\/timeInterval"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GenericEvent":{"abstract":[{"text":"The generic event type.","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GenericEvent","kind":"identifier"}],"title":"GenericEvent","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GenericEvent","role":"symbol","navigatorTitle":[{"text":"GenericEvent","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/genericevent"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/EventTimeInterval":{"navigatorTitle":[{"kind":"identifier","text":"EventTimeInterval"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"EventTimeInterval"}],"type":"topic","title":"EventTimeInterval","abstract":[{"text":"The time interval of an event. The ","type":"text"},{"type":"codeVoice","code":"begin"},{"type":"text","text":" property represents the time"},{"type":"text","text":" "},{"type":"text","text":"origin of an event, and the "},{"type":"codeVoice","code":"end"},{"text":" property represents the time when the particular","type":"text"},{"text":" ","type":"text"},{"text":"operation is complete. The timestamps are sampled at the origin and do not include","type":"text"},{"type":"text","text":" "},{"type":"text","text":"the time required to dispatch an event."}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/EventTimeInterval","url":"\/documentation\/mapboxmaps\/eventtimeinterval","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"timeInterval"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"timeInterval","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"MBMEventTimeInterval","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/EventTimeInterval","preciseIdentifier":"c:objc(cs)MBMEventTimeInterval","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"timeInterval","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMGenericEvent~1timeInterval\/title","value":"timeInterval"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMGenericEvent~1timeInterval\/fragments","value":[{"kind":"identifier","text":"timeInterval"}]},{"value":"MBMGenericEvent","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEvent\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEvent\/fragments","value":[{"text":"MBMGenericEvent","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1EventTimeInterval\/title","value":"MBMEventTimeInterval"},{"value":[{"text":"MBMEventTimeInterval","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1EventTimeInterval\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}