{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"c:objc(pl)MBMCustomRasterSourceTileRenderer(im)renderToTileForTileID:commandEncoder:","roleHeading":"Instance Method","role":"symbol","title":"renderToTile(for:commandEncoder:)","required":true,"navigatorTitle":[{"text":"renderToTileForTileID:commandEncoder:","kind":"identifier"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"renderToTile","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMCanonicalTileID","kind":"typeIdentifier","text":"CanonicalTileID"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"commandEncoder"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s6UInt64V","kind":"typeIdentifier","text":"UInt64"},{"text":")","kind":"text"}],"modules":[{"name":"MapboxMaps"}]},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer\/renderToTile(for:commandEncoder:)","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/customrastersourcetilerenderer\/rendertotile(for:commandencoder:)"]},{"paths":["\/documentation\/mapboxmaps\/customrastersourcetilerenderer\/rendertotile(for:commandencoder:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Orthographic mode render to the tile. This method is called once for each tile"},{"type":"text","text":" "},{"type":"text","text":"in every frame."},{"type":"text","text":" "},{"type":"text","text":"This method is called only if client code returns "},{"code":"true","type":"codeVoice"},{"text":" from the corresponding isTileRenderable() method.","type":"text"},{"text":" ","type":"text"},{"text":"Implementation should not change target framebuffer (as the render target is the tile texture).","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The reason is performance hit that would stem from such practice. If there’s a need for switching"},{"type":"text","text":" "},{"text":"rendering targets, implementation should use prerender() method.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"renderToTile","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"tileID"},{"kind":"text","text":": "},{"text":"CanonicalTileID","preciseIdentifier":"c:objc(cs)MBMCanonicalTileID","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"commandEncoder"},{"text":": ","kind":"text"},{"text":"UInt64","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"name":"tileId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Tile ID of the target tile that we are rendering to."}]}]},{"name":"commandEncoder","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"the command encoder for the tile texture render pass"}]}]}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The client should obtain the "},{"code":"MTLRenderCommandEncoder","type":"codeVoice"},{"text":" instance from the ","type":"text"},{"type":"codeVoice","code":"commandEncoder"},{"type":"text","text":" argument, using the"},{"text":" ","type":"text"},{"type":"text","text":"following code:"}]},{"syntax":null,"code":["mtlCommandEncoder = (__bridge id<MTLRenderCommandEncoder>)(void*)commandEncoder;"],"type":"codeListing"}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileRenderer":{"role":"symbol","type":"topic","title":"CustomRasterSourceTileRenderer","navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceTileRenderer"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer","url":"\/documentation\/mapboxmaps\/customrastersourcetilerenderer","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomRasterSourceTileRenderer"}],"abstract":[{"type":"text","text":"Interface for the direct rendering into the custom raster tiles."}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CanonicalTileID":{"type":"topic","role":"symbol","kind":"symbol","title":"CanonicalTileID","navigatorTitle":[{"text":"CanonicalTileID","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID","url":"\/documentation\/mapboxmaps\/canonicaltileid","abstract":[{"text":"Represents a tile coordinate.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CanonicalTileID","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Sources":{"role":"collectionGroup","url":"\/documentation\/mapboxmaps\/sources","title":"Sources","kind":"article","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileRenderer/renderToTile(for:commandEncoder:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer\/renderToTile(for:commandEncoder:)","url":"\/documentation\/mapboxmaps\/customrastersourcetilerenderer\/rendertotile(for:commandencoder:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"renderToTile","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"text":"CanonicalTileID","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMCanonicalTileID"},{"text":", ","kind":"text"},{"text":"commandEncoder","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt64","preciseIdentifier":"s:s6UInt64V","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Orthographic mode render to the tile. This method is called once for each tile"},{"type":"text","text":" "},{"type":"text","text":"in every frame."},{"text":" ","type":"text"},{"text":"This method is called only if client code returns ","type":"text"},{"type":"codeVoice","code":"true"},{"text":" from the corresponding isTileRenderable() method.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Implementation should not change target framebuffer (as the render target is the tile texture)."},{"type":"text","text":" "},{"type":"text","text":"The reason is performance hit that would stem from such practice. If there’s a need for switching"},{"type":"text","text":" "},{"text":"rendering targets, implementation should use prerender() method.","type":"text"}],"required":true,"title":"renderToTile(for:commandEncoder:)","navigatorTitle":[{"text":"renderToTileForTileID:commandEncoder:","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"renderToTileForTileID:commandEncoder:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"renderToTileForTileID:commandEncoder:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"renderToTileForTileID:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MBMCanonicalTileID","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMCanonicalTileID","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"tileID"},{"text":" ","kind":"text"},{"text":"commandEncoder:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@uint64_t","text":"uint64_t","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"commandEncoder"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer\/title","value":"MBMCustomRasterSourceTileRenderer"},{"value":[{"text":"MBMCustomRasterSourceTileRenderer","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/title","value":"MBMCanonicalTileID","op":"replace"},{"value":[{"kind":"identifier","text":"MBMCanonicalTileID"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/fragments","op":"replace"},{"value":"renderToTileForTileID:commandEncoder:","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer~1renderToTile(for:commandEncoder:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"renderToTileForTileID:commandEncoder:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer~1renderToTile(for:commandEncoder:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}