{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapRecorder","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeatureExtensionValue","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Size","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackError-swift.class","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestErrorType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapLoadingErrorTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRenderModeTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestErrorTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestLoadingMethodTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestPriorityTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestPriorityTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestResourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMResponseSourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMSourceDataLoadedTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStyleDataLoadedTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMTileStoreUsageModeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraChangedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GenericEventCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinishedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameStartedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequestCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceAddedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceRemovedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageMissingCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapIdleCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnusedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TransitionOptions-swift.class"],"anchor":"Symbols","title":"Symbols","generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBMRequestDataSourceTypeToString"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"request_data_source_type","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestDataSourceType","text":"RequestDataSourceType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMRequestDataSourceType"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"!"}],"languages":["swift"]}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/mbmrequestdatasourcetypetostring(_:)"]},{"paths":["\/documentation\/mapboxmaps\/mbmrequestdatasourcetypetostring(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestDataSourceTypeToString(_:)","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"text":"MBMRequestDataSourceTypeToString","kind":"identifier"}],"role":"symbol","symbolKind":"func","roleHeading":"Function","title":"MBMRequestDataSourceTypeToString(_:)","externalID":"c:@F@MBMRequestDataSourceTypeToString","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"MBMRequestDataSourceTypeToString","kind":"identifier"},{"kind":"text","text":"("},{"text":"RequestDataSourceType","preciseIdentifier":"c:@E@MBMRequestDataSourceType","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"!"}],"modules":[{"name":"MapboxMaps"}]},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMapsInternal"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRequestErrorTypeToString(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBMRequestErrorTypeToString"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@MBMRequestErrorType","kind":"typeIdentifier","text":"RequestErrorType"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBMRequestErrorTypeToString"}],"url":"\/documentation\/mapboxmaps\/mbmrequesterrortypetostring(_:)","title":"MBMRequestErrorTypeToString(_:)","type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestErrorTypeToString(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMResponseSourceTypeToString(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBMResponseSourceTypeToString"},{"text":"(","kind":"text"},{"text":"ResponseSourceType","preciseIdentifier":"c:@E@MBMResponseSourceType","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"MBMResponseSourceTypeToString","kind":"identifier"}],"title":"MBMResponseSourceTypeToString(_:)","abstract":[],"type":"topic","url":"\/documentation\/mapboxmaps\/mbmresponsesourcetypetostring(_:)","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMResponseSourceTypeToString(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePackError-swift.class":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"StylePackError","kind":"identifier"}],"abstract":[{"type":"text","text":"Describes a style package load request error."}],"kind":"symbol","role":"symbol","type":"topic","title":"StylePackError","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackError-swift.class","url":"\/documentation\/mapboxmaps\/stylepackerror-swift.class","navigatorTitle":[{"text":"StylePackError","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRequestPriorityTypeToString(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBMRequestPriorityTypeToString"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMRequestPriorityType","text":"RequestPriorityType"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBMRequestPriorityTypeToString"}],"title":"MBMRequestPriorityTypeToString(_:)","abstract":[],"type":"topic","url":"\/documentation\/mapboxmaps\/mbmrequestprioritytypetostring(_:)","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestPriorityTypeToString(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderFrameFinishedCallback":{"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"RenderFrameFinishedCallback","kind":"identifier"}],"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"map"},{"type":"text","text":" finished rendering a frame."}],"kind":"symbol","role":"symbol","type":"topic","title":"RenderFrameFinishedCallback","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinishedCallback","url":"\/documentation\/mapboxmaps\/renderframefinishedcallback","navigatorTitle":[{"text":"RenderFrameFinishedCallback","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoadingErrorCallback":{"title":"MapLoadingErrorCallback","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorCallback","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapLoadingErrorCallback"}],"url":"\/documentation\/mapboxmaps\/maploadingerrorcallback","navigatorTitle":[{"text":"MapLoadingErrorCallback","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Describes an error that has occurred while loading the "},{"type":"codeVoice","code":"map"},{"type":"text","text":"."}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GenericEventCallback":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GenericEventCallback","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GenericEventCallback","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/genericeventcallback","navigatorTitle":[{"kind":"identifier","text":"GenericEventCallback"}],"kind":"symbol","abstract":[{"type":"text","text":"Generic event for experimental events."}],"title":"GenericEventCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRenderModeTypeToString(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBMRenderModeTypeToString"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@MBMRenderModeType","kind":"typeIdentifier","text":"RenderModeType"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBMRenderModeTypeToString"}],"title":"MBMRenderModeTypeToString(_:)","abstract":[],"type":"topic","url":"\/documentation\/mapboxmaps\/mbmrendermodetypetostring(_:)","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRenderModeTypeToString(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRequestDataSourceTypeToString(_:)":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestDataSourceTypeToString(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"MBMRequestDataSourceTypeToString","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMRequestDataSourceType","text":"RequestDataSourceType"},{"kind":"text","text":") -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}],"url":"\/documentation\/mapboxmaps\/mbmrequestdatasourcetypetostring(_:)","navigatorTitle":[{"text":"MBMRequestDataSourceTypeToString","kind":"identifier"}],"kind":"symbol","abstract":[],"title":"MBMRequestDataSourceTypeToString(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceAddedCallback":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceAddedCallback"}],"kind":"symbol","navigatorTitle":[{"text":"SourceAddedCallback","kind":"identifier"}],"title":"SourceAddedCallback","abstract":[{"type":"text","text":"The source has been added with "},{"type":"codeVoice","code":"addStyleSource"},{"type":"text","text":" method."}],"type":"topic","url":"\/documentation\/mapboxmaps\/sourceaddedcallback","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceAddedCallback"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"type":"topic","title":"MapboxMaps Documentation","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleImageMissingCallback":{"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"StyleImageMissingCallback"}],"abstract":[{"text":"A style needs an image that is missing from the sprite sheet. This event is","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"emitted when the "},{"type":"codeVoice","code":"map"},{"type":"text","text":" renders visible tiles, and one of the required images"},{"type":"text","text":" "},{"type":"text","text":"is missing in the sprite sheet. The event observer has to provide the missing"},{"text":" ","type":"text"},{"type":"text","text":"image by calling the "},{"code":"addStyleImage","type":"codeVoice"},{"text":" method.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic","title":"StyleImageMissingCallback","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageMissingCallback","url":"\/documentation\/mapboxmaps\/styleimagemissingcallback","navigatorTitle":[{"kind":"identifier","text":"StyleImageMissingCallback"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceDataLoadedCallback":{"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"SourceDataLoadedCallback","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"SourceDataLoadedCallback","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/sourcedataloadedcallback","title":"SourceDataLoadedCallback","type":"topic","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"SourceDataLoaded"},{"type":"text","text":" event is emitted when source data is loaded."}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleLoadedCallback":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleLoadedCallback","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StyleLoadedCallback"}],"url":"\/documentation\/mapboxmaps\/styleloadedcallback","navigatorTitle":[{"text":"StyleLoadedCallback","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"The requested style has been fully loaded, including specified sprite, and sources’ metadata.","type":"text"}],"title":"StyleLoadedCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMSourceDataLoadedTypeToString(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBMSourceDataLoadedTypeToString"},{"kind":"text","text":"("},{"text":"SourceDataLoadedType","preciseIdentifier":"c:@E@MBMSourceDataLoadedType","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"!"}],"abstract":[],"kind":"symbol","role":"symbol","type":"topic","title":"MBMSourceDataLoadedTypeToString(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMSourceDataLoadedTypeToString(_:)","url":"\/documentation\/mapboxmaps\/mbmsourcedataloadedtypetostring(_:)","navigatorTitle":[{"text":"MBMSourceDataLoadedTypeToString","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Size":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Size","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Size"}],"url":"\/documentation\/mapboxmaps\/size","title":"Size","type":"topic","abstract":[{"type":"text","text":"Size type."}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Size"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMStyleDataLoadedTypeToString(_:)":{"title":"MBMStyleDataLoadedTypeToString(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStyleDataLoadedTypeToString(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"MBMStyleDataLoadedTypeToString","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@MBMStyleDataLoadedType","kind":"typeIdentifier","text":"StyleDataLoadedType"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"!"}],"url":"\/documentation\/mapboxmaps\/mbmstyledataloadedtypetostring(_:)","navigatorTitle":[{"text":"MBMStyleDataLoadedTypeToString","kind":"identifier"}],"kind":"symbol","abstract":[],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestDataSourceType":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestDataSourceType","title":"RequestDataSourceType","url":"\/documentation\/mapboxmaps\/requestdatasourcetype","abstract":[{"type":"text","text":"The enumeration defines the type of data source."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"RequestDataSourceType"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RequestDataSourceType"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMapsInternal":{"abstract":[{"text":"Maps rendering SDK also known as GL-Native. These are for internal use only.","type":"text"}],"kind":"article","role":"collectionGroup","type":"topic","title":"CoreMaps - Internal","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMapsInternal","url":"\/documentation\/mapboxmaps\/coremapsinternal"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoadedCallback":{"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapLoadedCallback"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MapLoadedCallback"}],"title":"MapLoadedCallback","abstract":[{"type":"text","text":"The style has been fully loaded, and the "},{"type":"codeVoice","code":"map"},{"type":"text","text":" has rendered all visible tiles."},{"type":"text","text":" "},{"text":"The event will be emitted only once for the current style. If it is required to","type":"text"},{"type":"text","text":" "},{"type":"text","text":"continuously observe an event where all the necessary resources are loaded or rendered,"},{"type":"text","text":" "},{"type":"text","text":"please check the following events: "},{"type":"codeVoice","code":"MapIdle"},{"text":", ","type":"text"},{"code":"StyleDataLoaded","type":"codeVoice"},{"type":"text","text":", and "},{"type":"codeVoice","code":"RenderFrameFinished"},{"text":".","type":"text"}],"type":"topic","url":"\/documentation\/mapboxmaps\/maploadedcallback","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadedCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMTileStoreUsageModeToString(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBMTileStoreUsageModeToString"},{"kind":"text","text":"("},{"text":"TileStoreUsageMode","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMTileStoreUsageMode"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"!"}],"kind":"symbol","navigatorTitle":[{"text":"MBMTileStoreUsageModeToString","kind":"identifier"}],"title":"MBMTileStoreUsageModeToString(_:)","abstract":[],"type":"topic","url":"\/documentation\/mapboxmaps\/mbmtilestoreusagemodetostring(_:)","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMTileStoreUsageModeToString(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRequestLoadingMethodTypeToString(_:)":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestLoadingMethodTypeToString(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBMRequestLoadingMethodTypeToString"},{"kind":"text","text":"("},{"text":"RequestLoadingMethodType","preciseIdentifier":"c:@E@MBMRequestLoadingMethodType","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"url":"\/documentation\/mapboxmaps\/mbmrequestloadingmethodtypetostring(_:)","navigatorTitle":[{"text":"MBMRequestLoadingMethodTypeToString","kind":"identifier"}],"kind":"symbol","abstract":[],"title":"MBMRequestLoadingMethodTypeToString(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapIdleCallback":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapIdleCallback","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapIdleCallback"}],"url":"\/documentation\/mapboxmaps\/mapidlecallback","navigatorTitle":[{"kind":"identifier","text":"MapIdleCallback"}],"kind":"symbol","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"map"},{"type":"text","text":" has entered the idle state. The "},{"code":"map","type":"codeVoice"},{"type":"text","text":" is idle when there are no ongoing"},{"text":" ","type":"text"},{"type":"text","text":"animations, transitions and the "},{"code":"map","type":"codeVoice"},{"type":"text","text":" has rendered all requested non-volatile tiles"},{"type":"text","text":" "},{"text":"(e.g., live traffic tiles). The event will not be emitted if ","type":"text"},{"type":"codeVoice","code":"setUserAnimationInProgress"},{"text":" ","type":"text"},{"type":"text","text":"and \/ or "},{"type":"codeVoice","code":"setGestureInProgress"},{"type":"text","text":" is set to "},{"code":"true","type":"codeVoice"},{"text":".","type":"text"}],"title":"MapIdleCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleImageRemoveUnusedCallback":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"StyleImageRemoveUnusedCallback"}],"kind":"symbol","navigatorTitle":[{"text":"StyleImageRemoveUnusedCallback","kind":"identifier"}],"title":"StyleImageRemoveUnusedCallback","abstract":[{"type":"text","text":"An image requested by the "},{"code":"map","type":"codeVoice"},{"text":" through the ","type":"text"},{"type":"codeVoice","code":"StyleImageMissing"},{"text":" event is no longer","type":"text"},{"type":"text","text":" "},{"type":"text","text":"needed and can be removed using the "},{"code":"removeStyleImage","type":"codeVoice"},{"text":" method. The application can","type":"text"},{"type":"text","text":" "},{"text":"decide whether the image should be kept or removed.","type":"text"}],"type":"topic","url":"\/documentation\/mapboxmaps\/styleimageremoveunusedcallback","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnusedCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapRecorder":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapRecorder"}],"kind":"symbol","navigatorTitle":[{"text":"MapRecorder","kind":"identifier"}],"title":"MapRecorder","abstract":[{"type":"text","text":"MapRecorder provides functions to record and replay API calls of a Map instance."},{"type":"text","text":" "},{"type":"text","text":"These recordings can be used to debug issues which requie multiple steps to reproduce."},{"text":" ","type":"text"},{"type":"text","text":"Additionaly, playbacks can be used for performance testing custom scenarios."}],"type":"topic","url":"\/documentation\/mapboxmaps\/maprecorder","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapRecorder"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TransitionOptions-swift.class":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TransitionOptions-swift.class","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TransitionOptions"}],"url":"\/documentation\/mapboxmaps\/transitionoptions-swift.class","navigatorTitle":[{"kind":"identifier","text":"TransitionOptions"}],"kind":"symbol","abstract":[{"text":"The ","type":"text"},{"code":"transition options","type":"codeVoice"},{"type":"text","text":" controls timing for the interpolation between a transitionable style"},{"type":"text","text":" "},{"text":"property’s previous value and new value. These can be used to define the style default property","type":"text"},{"type":"text","text":" "},{"type":"text","text":"transition behavior. Also, any transitionable style property may also have its own "},{"type":"codeVoice","code":"-transition"},{"type":"text","text":" "},{"text":"property that defines specific transition timing for that specific layer property, overriding","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"the global transition values."}],"title":"TransitionOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestErrorType":{"title":"RequestErrorType","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestErrorType","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"RequestErrorType","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/requesterrortype","navigatorTitle":[{"kind":"identifier","text":"RequestErrorType"}],"kind":"symbol","abstract":[{"type":"text","text":"The enumeration defines the error type that may occur during a resource request."}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMMapLoadingErrorTypeToString(_:)":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapLoadingErrorTypeToString(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"MBMMapLoadingErrorTypeToString","kind":"identifier"},{"kind":"text","text":"("},{"text":"MapLoadingErrorType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMMapLoadingErrorType"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"!"}],"url":"\/documentation\/mapboxmaps\/mbmmaploadingerrortypetostring(_:)","navigatorTitle":[{"text":"MBMMapLoadingErrorTypeToString","kind":"identifier"}],"kind":"symbol","abstract":[],"title":"MBMMapLoadingErrorTypeToString(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","url":"\/documentation\/mapboxmaps","type":"topic","kind":"symbol","title":"MapboxMaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderFrameStartedCallback":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RenderFrameStartedCallback"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"map"},{"text":" started rendering a frame.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic","title":"RenderFrameStartedCallback","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameStartedCallback","url":"\/documentation\/mapboxmaps\/renderframestartedcallback","navigatorTitle":[{"kind":"identifier","text":"RenderFrameStartedCallback"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleDataLoadedCallback":{"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"StyleDataLoadedCallback","kind":"identifier"}],"abstract":[{"type":"text","text":"The style data has been loaded."}],"kind":"symbol","role":"symbol","type":"topic","title":"StyleDataLoadedCallback","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedCallback","url":"\/documentation\/mapboxmaps\/styledataloadedcallback","navigatorTitle":[{"kind":"identifier","text":"StyleDataLoadedCallback"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRequestResourceTypeToString(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"MBMRequestResourceTypeToString","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"RequestResourceType","preciseIdentifier":"c:@E@MBMRequestResourceType"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"abstract":[],"kind":"symbol","role":"symbol","type":"topic","title":"MBMRequestResourceTypeToString(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestResourceTypeToString(_:)","url":"\/documentation\/mapboxmaps\/mbmrequestresourcetypetostring(_:)","navigatorTitle":[{"kind":"identifier","text":"MBMRequestResourceTypeToString"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResourceRequestCallback":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequestCallback","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"ResourceRequestCallback","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/resourcerequestcallback","navigatorTitle":[{"kind":"identifier","text":"ResourceRequestCallback"}],"kind":"symbol","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ResourceRequest"},{"type":"text","text":" event allows the application to observe resourcerequests"},{"text":" ","type":"text"},{"text":"made by a ","type":"text"},{"type":"codeVoice","code":"map"},{"type":"text","text":" or "},{"type":"codeVoice","code":"map snapshotter"},{"type":"text","text":" object."}],"title":"ResourceRequestCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceRemovedCallback":{"title":"SourceRemovedCallback","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceRemovedCallback","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"SourceRemovedCallback","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/sourceremovedcallback","navigatorTitle":[{"kind":"identifier","text":"SourceRemovedCallback"}],"kind":"symbol","abstract":[{"type":"text","text":"The source has been removed with "},{"code":"removeStyleSource","type":"codeVoice"},{"text":" method.","type":"text"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FeatureExtensionValue":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FeatureExtensionValue","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FeatureExtensionValue"}],"title":"FeatureExtensionValue","abstract":[{"type":"text","text":"A value or a collection of a feature extension."}],"type":"topic","url":"\/documentation\/mapboxmaps\/featureextensionvalue","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeatureExtensionValue"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraChangedCallback":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraChangedCallback"}],"abstract":[{"text":"This event is emitted whenever the visible viewport changes its size","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"due to the invocation of the "},{"type":"codeVoice","code":"setSize"},{"type":"text","text":" and "},{"code":"setBounds","type":"codeVoice"},{"type":"text","text":" methods or when"},{"type":"text","text":" "},{"type":"text","text":"the camera is modified by calling camera methods. The event is emitted"},{"type":"text","text":" "},{"text":"synchronously so that an updated camera state can be fetched immediately.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic","title":"CameraChangedCallback","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraChangedCallback","url":"\/documentation\/mapboxmaps\/camerachangedcallback","navigatorTitle":[{"kind":"identifier","text":"CameraChangedCallback"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Function","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"MBMRequestDataSourceTypeToString","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"func"},{"value":[{"text":"MBMRequestDataSourceTypeToString","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapRecorder","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeatureExtensionValue","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Size","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackError-swift.class","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestErrorType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapLoadingErrorTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRenderModeTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestErrorTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestLoadingMethodTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestPriorityTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestPriorityTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRequestResourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMResponseSourceTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMSourceDataLoadedTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStyleDataLoadedTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMTileStoreUsageModeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraChangedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GenericEventCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinishedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameStartedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequestCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceAddedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceRemovedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageMissingCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapIdleCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnusedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleLoadedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TransitionOptions-swift.class"],"generated":true,"anchor":"Symbols","title":"Symbols"}],"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"MBMRequestDataSourceTypeToString"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@MBMRequestDataSourceType","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestDataSourceType","text":"MBMRequestDataSourceType"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"request_data_source_type"},{"text":");","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestErrorTypeToString(_:)\/title","value":"MBMRequestErrorTypeToString"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestErrorTypeToString(_:)\/fragments","op":"replace","value":[{"text":"MBMRequestErrorTypeToString","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMResponseSourceTypeToString(_:)\/title","op":"replace","value":"MBMResponseSourceTypeToString"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMResponseSourceTypeToString(_:)\/fragments","op":"replace","value":[{"text":"MBMResponseSourceTypeToString","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackError-swift.class\/title","value":"MBMStylePackError"},{"value":[{"text":"MBMStylePackError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackError-swift.class\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackError-swift.class\/navigatorTitle","value":[{"kind":"identifier","text":"MBMStylePackError"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestPriorityTypeToString(_:)\/title","op":"replace","value":"MBMRequestPriorityTypeToString"},{"op":"replace","value":[{"text":"MBMRequestPriorityTypeToString","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestPriorityTypeToString(_:)\/fragments"},{"value":"MBMRenderFrameFinishedCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinishedCallback\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinishedCallback\/fragments","value":[{"text":"MBMRenderFrameFinishedCallback","kind":"identifier"}]},{"value":[{"text":"MBMRenderFrameFinishedCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinishedCallback\/navigatorTitle","op":"replace"},{"value":"MBMMapLoadingErrorCallback","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorCallback\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorCallback\/fragments","op":"replace","value":[{"text":"MBMMapLoadingErrorCallback","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"MBMMapLoadingErrorCallback"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorCallback\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEventCallback\/title","value":"MBMGenericEventCallback","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEventCallback\/fragments","value":[{"kind":"identifier","text":"MBMGenericEventCallback"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GenericEventCallback\/navigatorTitle","op":"replace","value":[{"text":"MBMGenericEventCallback","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRenderModeTypeToString(_:)\/title","op":"replace","value":"MBMRenderModeTypeToString"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRenderModeTypeToString(_:)\/fragments","value":[{"text":"MBMRenderModeTypeToString","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestDataSourceTypeToString(_:)\/title","op":"replace","value":"MBMRequestDataSourceTypeToString"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestDataSourceTypeToString(_:)\/fragments","value":[{"text":"MBMRequestDataSourceTypeToString","kind":"identifier"}]},{"op":"replace","value":"MBMSourceAddedCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAddedCallback\/title"},{"value":[{"text":"MBMSourceAddedCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAddedCallback\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAddedCallback\/navigatorTitle","value":[{"text":"MBMSourceAddedCallback","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"MBMStyleImageMissingCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageMissingCallback\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageMissingCallback\/fragments","value":[{"kind":"identifier","text":"MBMStyleImageMissingCallback"}],"op":"replace"},{"op":"replace","value":[{"text":"MBMStyleImageMissingCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageMissingCallback\/navigatorTitle"},{"value":"MBMSourceDataLoadedCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedCallback\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedCallback\/fragments","value":[{"kind":"identifier","text":"MBMSourceDataLoadedCallback"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedCallback\/navigatorTitle","value":[{"kind":"identifier","text":"MBMSourceDataLoadedCallback"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoadedCallback\/title","value":"MBMStyleLoadedCallback"},{"value":[{"kind":"identifier","text":"MBMStyleLoadedCallback"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoadedCallback\/fragments"},{"value":[{"kind":"identifier","text":"MBMStyleLoadedCallback"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoadedCallback\/navigatorTitle"},{"value":"MBMSourceDataLoadedTypeToString","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMSourceDataLoadedTypeToString(_:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMSourceDataLoadedTypeToString(_:)\/fragments","op":"replace","value":[{"text":"MBMSourceDataLoadedTypeToString","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Size\/title","value":"MBMSize","op":"replace"},{"value":[{"text":"MBMSize","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Size\/fragments"},{"value":[{"text":"MBMSize","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Size\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMStyleDataLoadedTypeToString(_:)\/title","value":"MBMStyleDataLoadedTypeToString"},{"value":[{"text":"MBMStyleDataLoadedTypeToString","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMStyleDataLoadedTypeToString(_:)\/fragments","op":"replace"},{"value":"MBMRequestDataSourceType","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestDataSourceType\/title","op":"replace"},{"op":"replace","value":[{"text":"MBMRequestDataSourceType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestDataSourceType\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestDataSourceType\/navigatorTitle","value":[{"text":"MBMRequestDataSourceType","kind":"identifier"}],"op":"replace"},{"value":"MBMMapLoadedCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadedCallback\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadedCallback\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMMapLoadedCallback"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadedCallback\/navigatorTitle","value":[{"kind":"identifier","text":"MBMMapLoadedCallback"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMTileStoreUsageModeToString(_:)\/title","value":"MBMTileStoreUsageModeToString"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMTileStoreUsageModeToString(_:)\/fragments","value":[{"text":"MBMTileStoreUsageModeToString","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"MBMRequestLoadingMethodTypeToString","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestLoadingMethodTypeToString(_:)\/title"},{"value":[{"text":"MBMRequestLoadingMethodTypeToString","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestLoadingMethodTypeToString(_:)\/fragments","op":"replace"},{"value":"MBMMapIdleCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdleCallback\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdleCallback\/fragments","value":[{"text":"MBMMapIdleCallback","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdleCallback\/navigatorTitle","value":[{"kind":"identifier","text":"MBMMapIdleCallback"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnusedCallback\/title","value":"MBMStyleImageRemoveUnusedCallback"},{"op":"replace","value":[{"text":"MBMStyleImageRemoveUnusedCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnusedCallback\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnusedCallback\/navigatorTitle","value":[{"text":"MBMStyleImageRemoveUnusedCallback","kind":"identifier"}]},{"value":"MBMMapRecorder","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapRecorder\/title"},{"value":[{"text":"MBMMapRecorder","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapRecorder\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapRecorder\/navigatorTitle","value":[{"text":"MBMMapRecorder","kind":"identifier"}]},{"value":"MBMTransitionOptions","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TransitionOptions-swift.class\/title"},{"value":[{"text":"MBMTransitionOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TransitionOptions-swift.class\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TransitionOptions-swift.class\/navigatorTitle","op":"replace","value":[{"text":"MBMTransitionOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestErrorType\/title","value":"MBMRequestErrorType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestErrorType\/fragments","value":[{"text":"MBMRequestErrorType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestErrorType\/navigatorTitle","value":[{"text":"MBMRequestErrorType","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"MBMMapLoadingErrorTypeToString","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMMapLoadingErrorTypeToString(_:)\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBMMapLoadingErrorTypeToString"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMMapLoadingErrorTypeToString(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameStartedCallback\/title","op":"replace","value":"MBMRenderFrameStartedCallback"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameStartedCallback\/fragments","value":[{"kind":"identifier","text":"MBMRenderFrameStartedCallback"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameStartedCallback\/navigatorTitle","value":[{"kind":"identifier","text":"MBMRenderFrameStartedCallback"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedCallback\/title","value":"MBMStyleDataLoadedCallback","op":"replace"},{"value":[{"text":"MBMStyleDataLoadedCallback","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedCallback\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedCallback\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMStyleDataLoadedCallback"}]},{"op":"replace","value":"MBMRequestResourceTypeToString","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestResourceTypeToString(_:)\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBMRequestResourceTypeToString"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMRequestResourceTypeToString(_:)\/fragments"},{"value":"MBMResourceRequestCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequestCallback\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequestCallback\/fragments","value":[{"kind":"identifier","text":"MBMResourceRequestCallback"}]},{"op":"replace","value":[{"kind":"identifier","text":"MBMResourceRequestCallback"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequestCallback\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceRemovedCallback\/title","value":"MBMSourceRemovedCallback","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceRemovedCallback\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMSourceRemovedCallback"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceRemovedCallback\/navigatorTitle","value":[{"kind":"identifier","text":"MBMSourceRemovedCallback"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeatureExtensionValue\/title","value":"MBMFeatureExtensionValue"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeatureExtensionValue\/fragments","value":[{"text":"MBMFeatureExtensionValue","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeatureExtensionValue\/navigatorTitle","value":[{"kind":"identifier","text":"MBMFeatureExtensionValue"}]},{"value":"MBMCameraChangedCallback","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChangedCallback\/title"},{"value":[{"kind":"identifier","text":"MBMCameraChangedCallback"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChangedCallback\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChangedCallback\/navigatorTitle","value":[{"kind":"identifier","text":"MBMCameraChangedCallback"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}