{"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMCustomRasterSourceOptions","text":"CustomRasterSourceOptions"},{"kind":"text","text":", "},{"text":"maxOverscaleFactorForParentTiles","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt8","kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V"},{"text":"?)","kind":"text"}],"role":"symbol","tags":[{"text":"SPI","type":"spi"}],"modules":[{"name":"MapboxMaps"}],"title":"init(id:options:maxOverscaleFactorForParentTiles:)","symbolKind":"init","externalID":"s:10MapboxMaps18CustomRasterSourceV2id7options32maxOverscaleFactorForParentTilesACSS_So09MBMCustomdE7OptionsCs5UInt8VSgtcfc","roleHeading":"Initializer"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSource"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"id","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MBMCustomRasterSourceOptions","text":"CustomRasterSourceOptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"maxOverscaleFactorForParentTiles"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt8","preciseIdentifier":"s:s5UInt8V"},{"text":"? = nil)","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/customrastersource\/init(id:options:maxoverscalefactorforparenttiles:)"]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSource\/init(id:options:maxOverscaleFactorForParentTiles:)","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","abstract":[],"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","kind":"article","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Sources":{"title":"Sources","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources","kind":"article","abstract":[],"url":"\/documentation\/mapboxmaps\/sources","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceOptions":{"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/customrastersourceoptions","abstract":[{"text":"Options for custom raster source.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomRasterSourceOptions","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions","navigatorTitle":[{"text":"CustomRasterSourceOptions","kind":"identifier"}],"title":"CustomRasterSourceOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSource":{"kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CustomRasterSource"}],"tags":[{"type":"spi","text":"SPI"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSource","url":"\/documentation\/mapboxmaps\/customrastersource","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"CustomRasterSource","kind":"identifier"}],"title":"CustomRasterSource","abstract":[{"type":"text","text":"Describes a Custom Raster Source to be used in the style."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSource/init(id:options:maxOverscaleFactorForParentTiles:)":{"type":"topic","url":"\/documentation\/mapboxmaps\/customrastersource\/init(id:options:maxoverscalefactorforparenttiles:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSource\/init(id:options:maxOverscaleFactorForParentTiles:)","role":"symbol","tags":[{"type":"spi","text":"SPI"}],"abstract":[],"title":"init(id:options:maxOverscaleFactorForParentTiles:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"id"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMCustomRasterSourceOptions","text":"CustomRasterSourceOptions"},{"kind":"text","text":", "},{"kind":"externalParam","text":"maxOverscaleFactorForParentTiles"},{"text":": ","kind":"text"},{"text":"UInt8","kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V"},{"text":"?)","kind":"text"}]}},"variantOverrides":[{"patch":[{"value":"MBMCustomRasterSourceOptions","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/title","op":"replace"},{"op":"replace","value":[{"text":"MBMCustomRasterSourceOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/navigatorTitle","value":[{"kind":"identifier","text":"MBMCustomRasterSourceOptions"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}