{"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.hash(into:)"},{"type":"text","text":"."}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"Hasher","preciseIdentifier":"s:s6HasherV"},{"kind":"text","text":")"}],"title":"hash(into:)","modules":[{"name":"MapboxCommon","relatedModules":["Swift"]}],"conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}]},"roleHeading":"Instance Method","extendedModule":"Swift","symbolKind":"method","role":"symbol","externalID":"s:SYsSHRzSH8RawValueSYRpzrlE4hash4intoys6HasherVz_tF::SYNTHESIZED::c:@E@MBXLocationErrorCode"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode\/RawRepresentable-Implementations"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"hasher","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hasher","preciseIdentifier":"s:s6HasherV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/mapboxcommon\/locationerrorcode\/hash(into:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode\/hash(into:)"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationErrorCode/hash(into:)":{"type":"topic","title":"hash(into:)","kind":"symbol","conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}]},"url":"\/documentation\/mapboxcommon\/locationerrorcode\/hash(into:)","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV","text":"Hasher"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode\/hash(into:)"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","role":"collection","url":"\/documentation\/overview","title":"MapboxMaps Documentation","kind":"article","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","title":"MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationErrorCode":{"type":"topic","title":"LocationErrorCode","navigatorTitle":[{"text":"LocationErrorCode","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapboxcommon\/locationerrorcode","abstract":[{"text":"Codes of location errors.","type":"text"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationErrorCode","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationErrorCode/RawRepresentable-Implementations":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode\/RawRepresentable-Implementations","type":"topic","role":"collectionGroup","abstract":[],"kind":"article","url":"\/documentation\/mapboxcommon\/locationerrorcode\/rawrepresentable-implementations","title":"RawRepresentable Implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Location-APIs":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","title":"Location","abstract":[],"url":"\/documentation\/mapboxmaps\/location-apis","type":"topic","role":"collectionGroup","kind":"article"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/title","op":"replace","value":"MBXLocationErrorCode"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXLocationErrorCode"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/navigatorTitle","op":"replace","value":[{"text":"MBXLocationErrorCode","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}