{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions"]]},"metadata":{"title":"getLocation","fragments":[{"kind":"text","text":"- "},{"text":"getLocation","kind":"identifier"}],"navigatorTitle":[{"text":"getLocation","kind":"identifier"}],"externalID":"c:objc(cs)MBMFreeCameraOptions(im)getLocation","modules":[{"name":"MapboxMaps"}],"roleHeading":"Instance Method","role":"symbol","symbolKind":"method"},"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMFreeCameraOptions\/getLocation"},"variants":[{"paths":["\/documentation\/mapboxmaps\/mbmfreecameraoptions\/getlocation"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"abstract":[{"type":"text","text":"Helper function for getting current mercator position as Lat&Lng coordinate."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Coordinate2D","preciseIdentifier":"c:objc(cs)MBXCoordinate2D","text":"MBXCoordinate2D"},{"kind":"text","text":" *) "},{"text":"getLocation","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"The longitude, latitude for mercator position."}]}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","kind":"article","url":"\/documentation\/mapboxmaps\/mapboxmap-apis","title":"MapboxMap","type":"topic","abstract":[],"role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Coordinate2D":{"url":"\/documentation\/mapboxcommon\/coordinate2d","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Coordinate2D","kind":"identifier"}],"title":"Coordinate2D","navigatorTitle":[{"kind":"identifier","text":"Coordinate2D"}],"abstract":[{"type":"text","text":"Boxed version of CLLocationCoordinate2D"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Coordinate2D"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","abstract":[],"title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","kind":"article","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FreeCameraOptions":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FreeCameraOptions"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FreeCameraOptions"}],"abstract":[{"type":"text","text":"Various options for accessing physical properties of the underlying camera entity."},{"type":"text","text":" "},{"type":"text","text":"A direct access to these properties allows more flexible and precise controlling"},{"text":" ","type":"text"},{"text":"of the camera while also being fully compatible and interchangeable with CameraOptions.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"All fields are optional."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions","title":"FreeCameraOptions","url":"\/documentation\/mapboxmaps\/freecameraoptions","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","title":"MapboxMaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"role":"collection","url":"\/documentation\/mapboxmaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMFreeCameraOptions/getLocation":{"url":"\/documentation\/mapboxmaps\/mbmfreecameraoptions\/getlocation","title":"getLocation","type":"topic","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"getLocation","kind":"identifier"}],"navigatorTitle":[{"text":"getLocation","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMFreeCameraOptions\/getLocation","abstract":[{"type":"text","text":"Helper function for getting current mercator position as Lat&Lng coordinate."}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"MBXCoordinate2D","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Coordinate2D\/title"},{"value":[{"text":"MBXCoordinate2D","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Coordinate2D\/fragments"},{"value":[{"kind":"identifier","text":"MBXCoordinate2D"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Coordinate2D\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions\/title","value":"MBMFreeCameraOptions"},{"op":"replace","value":[{"kind":"identifier","text":"MBMFreeCameraOptions"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions\/fragments"},{"value":[{"kind":"identifier","text":"MBMFreeCameraOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}