{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isExternal"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"! { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"inlineContent":[{"type":"text","text":"Value: Boolean"}],"type":"paragraph"}],"kind":"content"}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/locationextrakeys\/isexternal"]},{"paths":["\/documentation\/mapboxcommon\/locationextrakeys\/isexternal"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationExtraKeys"]]},"metadata":{"role":"symbol","roleHeading":"Type Property","title":"isExternal","symbolKind":"property","externalID":"c:objc(cs)MBXLocationExtraKeys(cpy)IsExternal","navigatorTitle":[{"kind":"identifier","text":"IsExternal"}],"modules":[{"name":"MapboxCommon"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isExternal","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationExtraKeys\/isExternal"},"sections":[],"abstract":[{"text":"The key to indicate if this location fix is retrieved from an external","type":"text"},{"type":"text","text":" "},{"text":"accessory attached to the device such as GNSS dongle, CarPlay, etc.","type":"text"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","kind":"article","abstract":[],"url":"\/documentation\/overview","type":"topic","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"role":"collection","url":"\/documentation\/mapboxmaps","title":"MapboxMaps","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationExtraKeys/isExternal":{"abstract":[{"type":"text","text":"The key to indicate if this location fix is retrieved from an external"},{"text":" ","type":"text"},{"text":"accessory attached to the device such as GNSS dongle, CarPlay, etc.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isExternal","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"url":"\/documentation\/mapboxcommon\/locationextrakeys\/isexternal","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationExtraKeys\/isExternal","kind":"symbol","navigatorTitle":[{"text":"IsExternal","kind":"identifier"}],"type":"topic","role":"symbol","title":"isExternal"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationExtraKeys":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationExtraKeys","abstract":[{"text":"Keys for additional information (extra) in Location.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LocationExtraKeys"}],"navigatorTitle":[{"kind":"identifier","text":"LocationExtraKeys"}],"type":"topic","url":"\/documentation\/mapboxcommon\/locationextrakeys","role":"symbol","title":"LocationExtraKeys","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Location-APIs":{"abstract":[],"kind":"article","type":"topic","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","url":"\/documentation\/mapboxmaps\/location-apis","title":"Location"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"IsExternal"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"kind":"identifier","text":"IsExternal"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"IsExternal"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"IsExternal","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationExtraKeys~1isExternal\/title"},{"value":[{"kind":"identifier","text":"IsExternal"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationExtraKeys~1isExternal\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationExtraKeys\/title","value":"MBXLocationExtraKeys","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationExtraKeys\/fragments","value":[{"kind":"identifier","text":"MBXLocationExtraKeys"}]},{"value":[{"kind":"identifier","text":"MBXLocationExtraKeys"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationExtraKeys\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}