{"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequest\/init(source:request:response:cancelled:timeInterval:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/mapboxmaps\/resourcerequest\/init(source:request:response:cancelled:timeinterval:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/resourcerequest\/init(source:request:response:cancelled:timeinterval:)"]}],"sections":[],"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"source","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"RequestDataSourceType","preciseIdentifier":"c:@E@MBMRequestDataSourceType"},{"kind":"text","text":", "},{"text":"request","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"RequestInfo","preciseIdentifier":"c:objc(cs)MBMRequestInfo","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"response"},{"text":": ","kind":"text"},{"text":"ResponseInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMResponseInfo"},{"text":"?, ","kind":"text"},{"text":"cancelled","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"timeInterval"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMEventTimeInterval","text":"EventTimeInterval","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"initWithSource:request:response:cancelled:timeInterval:","kind":"identifier"}],"role":"symbol","title":"init(source:request:response:cancelled:timeInterval:)","roleHeading":"Initializer","modules":[{"name":"MapboxMaps"}],"symbolKind":"init","externalID":"c:objc(cs)MBMResourceRequest(im)initWithSource:request:response:cancelled:timeInterval:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"source"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@MBMRequestDataSourceType","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestDataSourceType","text":"RequestDataSourceType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"request","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestInfo","preciseIdentifier":"c:objc(cs)MBMRequestInfo","text":"RequestInfo"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"response"},{"text":": ","kind":"text"},{"text":"ResponseInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMResponseInfo","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResponseInfo"},{"text":"?, ","kind":"text"},{"text":"cancelled","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"timeInterval","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"EventTimeInterval","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/EventTimeInterval","preciseIdentifier":"c:objc(cs)MBMEventTimeInterval"},{"kind":"text","text":")"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequest"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResourceRequest":{"type":"topic","title":"ResourceRequest","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"ResourceRequest"},{"type":"text","text":" event allows the application to observe resource requests made by a "},{"type":"codeVoice","code":"map"},{"text":" or ","type":"text"},{"code":"map snapshotter","type":"codeVoice"},{"type":"text","text":" object."}],"role":"symbol","kind":"symbol","url":"\/documentation\/mapboxmaps\/resourcerequest","navigatorTitle":[{"text":"ResourceRequest","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequest","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResourceRequest"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"title":"Map events","kind":"article","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","abstract":[{"type":"text","text":"The simplified diagram of the events emitted by the map is displayed below."}],"url":"\/documentation\/mapboxmaps\/events","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestInfo":{"type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/requestinfo","title":"RequestInfo","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RequestInfo"}],"abstract":[{"type":"text","text":"The structure defines the information about the resource request."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestInfo","kind":"symbol","navigatorTitle":[{"text":"RequestInfo","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResourceRequest/init(source:request:response:cancelled:timeInterval:)":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"source"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@MBMRequestDataSourceType","kind":"typeIdentifier","text":"RequestDataSourceType"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"request"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMRequestInfo","text":"RequestInfo"},{"text":", ","kind":"text"},{"text":"response","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ResponseInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMResponseInfo"},{"text":"?, ","kind":"text"},{"text":"cancelled","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"text":"timeInterval","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"EventTimeInterval","preciseIdentifier":"c:objc(cs)MBMEventTimeInterval","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequest\/init(source:request:response:cancelled:timeInterval:)","role":"symbol","navigatorTitle":[{"text":"initWithSource:request:response:cancelled:timeInterval:","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[],"title":"init(source:request:response:cancelled:timeInterval:)","url":"\/documentation\/mapboxmaps\/resourcerequest\/init(source:request:response:cancelled:timeinterval:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/EventTimeInterval":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/EventTimeInterval","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"EventTimeInterval","kind":"identifier"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"EventTimeInterval","kind":"identifier"}],"abstract":[{"text":"The time interval of an event. The ","type":"text"},{"type":"codeVoice","code":"begin"},{"type":"text","text":" property represents the time"},{"text":" ","type":"text"},{"type":"text","text":"origin of an event, and the "},{"code":"end","type":"codeVoice"},{"type":"text","text":" property represents the time when the particular"},{"type":"text","text":" "},{"type":"text","text":"operation is complete. The timestamps are sampled at the origin and do not include"},{"text":" ","type":"text"},{"type":"text","text":"the time required to dispatch an event."}],"url":"\/documentation\/mapboxmaps\/eventtimeinterval","title":"EventTimeInterval","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","kind":"article","role":"collection","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"title":"MapboxMaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResponseInfo":{"type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/responseinfo","title":"ResponseInfo","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ResponseInfo"}],"abstract":[{"type":"text","text":"The structure defines the information about the response for the resource request."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResponseInfo","kind":"symbol","navigatorTitle":[{"text":"ResponseInfo","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestDataSourceType":{"url":"\/documentation\/mapboxmaps\/requestdatasourcetype","kind":"symbol","abstract":[{"type":"text","text":"The enumeration defines the type of data source."}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"RequestDataSourceType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"RequestDataSourceType"}],"title":"RequestDataSourceType","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestDataSourceType"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithSource:request:response:cancelled:timeInterval:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithSource:request:response:cancelled:timeInterval:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithSource:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestDataSourceType","preciseIdentifier":"c:@E@MBMRequestDataSourceType","text":"MBMRequestDataSourceType"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"source"},{"kind":"text","text":" "},{"text":"request:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMRequestInfo","text":"MBMRequestInfo","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestInfo"},{"kind":"text","text":" *) "},{"text":"request","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"response:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMResponseInfo","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResponseInfo","text":"MBMResponseInfo"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"response"},{"text":" ","kind":"text"},{"text":"cancelled:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"cancelled","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"timeInterval:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"MBMEventTimeInterval","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/EventTimeInterval","preciseIdentifier":"c:objc(cs)MBMEventTimeInterval"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"timeInterval"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"value":"MBMResourceRequest","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequest\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequest\/fragments","value":[{"kind":"identifier","text":"MBMResourceRequest"}]},{"value":[{"text":"MBMResourceRequest","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequest\/navigatorTitle","op":"replace"},{"op":"replace","value":"MBMRequestInfo","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestInfo\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestInfo\/fragments","value":[{"text":"MBMRequestInfo","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestInfo\/navigatorTitle","value":[{"text":"MBMRequestInfo","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequest~1init(source:request:response:cancelled:timeInterval:)\/title","value":"initWithSource:request:response:cancelled:timeInterval:"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequest~1init(source:request:response:cancelled:timeInterval:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSource:request:response:cancelled:timeInterval:"}],"op":"replace"},{"op":"replace","value":"MBMEventTimeInterval","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1EventTimeInterval\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1EventTimeInterval\/fragments","value":[{"text":"MBMEventTimeInterval","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1EventTimeInterval\/navigatorTitle","value":[{"text":"MBMEventTimeInterval","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"MBMResponseInfo","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResponseInfo\/title"},{"value":[{"text":"MBMResponseInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResponseInfo\/fragments","op":"replace"},{"value":[{"text":"MBMResponseInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResponseInfo\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestDataSourceType\/title","value":"MBMRequestDataSourceType"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestDataSourceType\/fragments","value":[{"text":"MBMRequestDataSourceType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestDataSourceType\/navigatorTitle","value":[{"text":"MBMRequestDataSourceType","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}