{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/mbxloggingleveltostring(_:)"]},{"paths":["\/documentation\/mapboxcommon\/mbxloggingleveltostring(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"roleHeading":"Function","title":"MBXLoggingLevelToString(_:)","symbolKind":"func","navigatorTitle":[{"text":"MBXLoggingLevelToString","kind":"identifier"}],"externalID":"c:@F@MBXLoggingLevelToString","role":"symbol","modules":[{"name":"MapboxCommon"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBXLoggingLevelToString"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBXLoggingLevel","text":"LoggingLevel"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBXLoggingLevelToString"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"logging_level","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"LoggingLevel","preciseIdentifier":"c:@E@MBXLoggingLevel","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LoggingLevel"},{"kind":"text","text":") -> "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"!"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXLoggingLevelToString(_:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"url":"\/documentation\/mapboxcommon","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","type":"topic","kind":"symbol","title":"MapboxCommon","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXLoggingLevelToString(_:)":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXLoggingLevelToString(_:)","title":"MBXLoggingLevelToString(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBXLoggingLevelToString"},{"kind":"text","text":"("},{"text":"LoggingLevel","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBXLoggingLevel"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"MBXLoggingLevelToString","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapboxcommon\/mbxloggingleveltostring(_:)","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LoggingLevel":{"abstract":[{"text":"State level of a log message.","type":"text"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LoggingLevel","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/logginglevel","navigatorTitle":[{"kind":"identifier","text":"LoggingLevel"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LoggingLevel","kind":"symbol","title":"LoggingLevel","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","url":"\/documentation\/overview","title":"MapboxMaps Documentation","abstract":[],"kind":"article","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Function"},{"value":"MBXLoggingLevelToString","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"func","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MBXLoggingLevelToString"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"text":"MBXLoggingLevelToString","kind":"identifier"},{"kind":"text","text":"("},{"text":"MBXLoggingLevel","preciseIdentifier":"c:@E@MBXLoggingLevel","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LoggingLevel"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"logging_level"},{"kind":"text","text":");"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MBXLoggingLevelToString(_:)\/title","op":"replace","value":"MBXLoggingLevelToString"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MBXLoggingLevelToString(_:)\/fragments","value":[{"kind":"identifier","text":"MBXLoggingLevelToString"}]},{"value":"MBXLoggingLevel","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LoggingLevel\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LoggingLevel\/fragments","value":[{"text":"MBXLoggingLevel","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LoggingLevel\/navigatorTitle","value":[{"text":"MBXLoggingLevel","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}