{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions"]]},"sections":[],"metadata":{"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fetchTileFunction"},{"kind":"text","text":": "},{"preciseIdentifier":"c:MBMTileFunctionCallback.h@T@MBMTileFunctionCallback","kind":"typeIdentifier","text":"TileFunctionCallback"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cancelTileFunction"},{"kind":"text","text":": "},{"preciseIdentifier":"c:MBMTileFunctionCallback.h@T@MBMTileFunctionCallback","kind":"typeIdentifier","text":"TileFunctionCallback"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tileOptions"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MBMTileOptions","kind":"typeIdentifier","text":"TileOptions"},{"kind":"text","text":")"}],"symbolKind":"init","title":"init(fetchTileFunction:cancelTileFunction:tileOptions:)","modules":[{"name":"MapboxMaps"}],"roleHeading":"Initializer","externalID":"c:objc(cs)MBMCustomGeometrySourceOptions(im)initWithFetchTileFunction:cancelTileFunction:tileOptions:","navigatorTitle":[{"kind":"identifier","text":"initWithFetchTileFunction:cancelTileFunction:tileOptions:"}]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions\/init(fetchTileFunction:cancelTileFunction:tileOptions:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"fetchTileFunction","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileFunctionCallback","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileFunctionCallback","preciseIdentifier":"c:MBMTileFunctionCallback.h@T@MBMTileFunctionCallback","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"cancelTileFunction","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileFunctionCallback","preciseIdentifier":"c:MBMTileFunctionCallback.h@T@MBMTileFunctionCallback","text":"TileFunctionCallback","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"tileOptions","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileOptions","preciseIdentifier":"c:objc(cs)MBMTileOptions","text":"TileOptions","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/customgeometrysourceoptions\/init(fetchtilefunction:canceltilefunction:tileoptions:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/customgeometrysourceoptions\/init(fetchtilefunction:canceltilefunction:tileoptions:)"]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomGeometrySourceOptions":{"url":"\/documentation\/mapboxmaps\/customgeometrysourceoptions","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomGeometrySourceOptions"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions","navigatorTitle":[{"kind":"identifier","text":"CustomGeometrySourceOptions"}],"title":"CustomGeometrySourceOptions","abstract":[{"type":"text","text":"Options for custom geometry source."}],"type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileFunctionCallback":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileFunctionCallback","type":"topic","title":"TileFunctionCallback","abstract":[{"text":"Callback to do various operations for tile.","type":"text"},{"text":" ","type":"text"},{"text":"For example, fetching a tile or cancelling a tile request.","type":"text"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileFunctionCallback","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/tilefunctioncallback","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"TileFunctionCallback","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","abstract":[],"url":"\/documentation\/overview","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Sources":{"abstract":[],"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources","type":"topic","title":"Sources","url":"\/documentation\/mapboxmaps\/sources","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"url":"\/documentation\/mapboxmaps","role":"collection","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomGeometrySourceOptions/init(fetchTileFunction:cancelTileFunction:tileOptions:)":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions\/init(fetchTileFunction:cancelTileFunction:tileOptions:)","type":"topic","kind":"symbol","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fetchTileFunction","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TileFunctionCallback","kind":"typeIdentifier","preciseIdentifier":"c:MBMTileFunctionCallback.h@T@MBMTileFunctionCallback"},{"text":", ","kind":"text"},{"text":"cancelTileFunction","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TileFunctionCallback","kind":"typeIdentifier","preciseIdentifier":"c:MBMTileFunctionCallback.h@T@MBMTileFunctionCallback"},{"text":", ","kind":"text"},{"text":"tileOptions","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TileOptions","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMTileOptions"},{"text":")","kind":"text"}],"title":"init(fetchTileFunction:cancelTileFunction:tileOptions:)","navigatorTitle":[{"text":"initWithFetchTileFunction:cancelTileFunction:tileOptions:","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/customgeometrysourceoptions\/init(fetchtilefunction:canceltilefunction:tileoptions:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileOptions":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileOptions","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileOptions","kind":"identifier"}],"abstract":[{"text":"Options for custom geometry tiles.","type":"text"}],"url":"\/documentation\/mapboxmaps\/tileoptions","navigatorTitle":[{"text":"TileOptions","kind":"identifier"}],"title":"TileOptions","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithFetchTileFunction:cancelTileFunction:tileOptions:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithFetchTileFunction:cancelTileFunction:tileOptions:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithFetchTileFunction:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(MBMCanonicalTileID *)","preciseIdentifier":"c:BFv(#*$objc(cs)MBMCanonicalTileID)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"fetchTileFunction"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelTileFunction:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:BFv(#*$objc(cs)MBMCanonicalTileID)","text":"void (^)(MBMCanonicalTileID *)","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"cancelTileFunction","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"tileOptions:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMTileOptions","text":"MBMTileOptions","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileOptions"},{"text":" *) ","kind":"text"},{"text":"tileOptions","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions\/title","value":"MBMCustomGeometrySourceOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions\/fragments","value":[{"text":"MBMCustomGeometrySourceOptions","kind":"identifier"}]},{"op":"replace","value":[{"text":"MBMCustomGeometrySourceOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions\/navigatorTitle"},{"op":"replace","value":"MBMTileFunctionCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileFunctionCallback\/title"},{"op":"replace","value":[{"text":"MBMTileFunctionCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileFunctionCallback\/fragments"},{"op":"replace","value":[{"text":"MBMTileFunctionCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileFunctionCallback\/navigatorTitle"},{"op":"replace","value":"initWithFetchTileFunction:cancelTileFunction:tileOptions:","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions~1init(fetchTileFunction:cancelTileFunction:tileOptions:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFetchTileFunction:cancelTileFunction:tileOptions:"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions~1init(fetchTileFunction:cancelTileFunction:tileOptions:)\/fragments"},{"op":"replace","value":"MBMTileOptions","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileOptions\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBMTileOptions"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileOptions\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MBMTileOptions"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileOptions\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}