{"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoaded\/init(type:timeInterval:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/mapboxmaps\/styledataloaded\/init(type:timeinterval:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/styledataloaded\/init(type:timeinterval:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"type"},{"text":": ","kind":"text"},{"text":"StyleDataLoadedType","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedType","preciseIdentifier":"c:@E@MBMStyleDataLoadedType"},{"text":", ","kind":"text"},{"text":"timeInterval","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MBMEventTimeInterval","text":"EventTimeInterval","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/EventTimeInterval","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"role":"symbol","title":"init(type:timeInterval:)","navigatorTitle":[{"text":"initWithType:timeInterval:","kind":"identifier"}],"modules":[{"name":"MapboxMaps"}],"roleHeading":"Initializer","externalID":"c:objc(cs)MBMStyleDataLoaded(im)initWithType:timeInterval:","symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"text":"StyleDataLoadedType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMStyleDataLoadedType"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"timeInterval"},{"kind":"text","text":": "},{"text":"EventTimeInterval","preciseIdentifier":"c:objc(cs)MBMEventTimeInterval","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoaded"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleDataLoaded/init(type:timeInterval:)":{"kind":"symbol","navigatorTitle":[{"text":"initWithType:timeInterval:","kind":"identifier"}],"title":"init(type:timeInterval:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoaded\/init(type:timeInterval:)","type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"text":"StyleDataLoadedType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMStyleDataLoadedType"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"timeInterval"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MBMEventTimeInterval","text":"EventTimeInterval","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/mapboxmaps\/styledataloaded\/init(type:timeinterval:)","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleDataLoaded":{"type":"topic","navigatorTitle":[{"text":"StyleDataLoaded","kind":"identifier"}],"abstract":[{"text":"The style data has been loaded. The event will be emitted once for each ","type":"text"},{"code":"StyleDataLoadedType","type":"codeVoice"},{"type":"text","text":" "},{"text":"type during style loading. If a new style is set, events will be emitted again for the newly set style.","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/styledataloaded","title":"StyleDataLoaded","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoaded","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StyleDataLoaded"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleDataLoadedType":{"title":"StyleDataLoadedType","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedType","type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/styledataloadedtype","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"StyleDataLoadedType"}],"abstract":[{"text":"The enumeration defines the type of loaded style data.","type":"text"}],"navigatorTitle":[{"text":"StyleDataLoadedType","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/EventTimeInterval":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"EventTimeInterval"}],"title":"EventTimeInterval","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/EventTimeInterval","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EventTimeInterval"}],"abstract":[{"text":"The time interval of an event. The ","type":"text"},{"code":"begin","type":"codeVoice"},{"type":"text","text":" property represents the time"},{"type":"text","text":" "},{"type":"text","text":"origin of an event, and the "},{"type":"codeVoice","code":"end"},{"type":"text","text":" property represents the time when the particular"},{"type":"text","text":" "},{"type":"text","text":"operation is complete. The timestamps are sampled at the origin and do not include"},{"type":"text","text":" "},{"text":"the time required to dispatch an event.","type":"text"}],"url":"\/documentation\/mapboxmaps\/eventtimeinterval"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","role":"collection","title":"MapboxMaps Documentation","abstract":[],"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","kind":"symbol","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"type":"topic","abstract":[{"type":"text","text":"The simplified diagram of the events emitted by the map is displayed below."}],"kind":"article","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/events","title":"Map events","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initWithType:timeInterval:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithType:timeInterval:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithType:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedType","text":"MBMStyleDataLoadedType","preciseIdentifier":"c:@E@MBMStyleDataLoadedType","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"type","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"timeInterval:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/EventTimeInterval","preciseIdentifier":"c:objc(cs)MBMEventTimeInterval","text":"MBMEventTimeInterval","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"timeInterval","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"initWithType:timeInterval:","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoaded~1init(type:timeInterval:)\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoaded~1init(type:timeInterval:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithType:timeInterval:"}]},{"value":"MBMStyleDataLoaded","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoaded\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoaded\/fragments","value":[{"text":"MBMStyleDataLoaded","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoaded\/navigatorTitle","op":"replace","value":[{"text":"MBMStyleDataLoaded","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedType\/title","value":"MBMStyleDataLoadedType","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedType\/fragments","value":[{"text":"MBMStyleDataLoadedType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedType\/navigatorTitle","op":"replace","value":[{"text":"MBMStyleDataLoadedType","kind":"identifier"}]},{"value":"MBMEventTimeInterval","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1EventTimeInterval\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1EventTimeInterval\/fragments","value":[{"kind":"identifier","text":"MBMEventTimeInterval"}]},{"value":[{"text":"MBMEventTimeInterval","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1EventTimeInterval\/navigatorTitle"}]}]}