{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"averageBytesPerSecond","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"role":"symbol","title":"averageBytesPerSecond","modules":[{"name":"MapboxCommon"}],"symbolKind":"property","extendedModule":"MapboxCommon","externalID":"s:So24MBXTileRegionLoadOptionsC10MapboxMapsE21averageBytesPerSecondSiSgvp","roleHeading":"Instance Property"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions\/averageBytesPerSecond"},"abstract":[{"type":"text","text":"Limits the download speed of the tile region."}],"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/tileregionloadoptions\/averagebytespersecond"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"averageBytesPerSecond","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"Note that this is not a strict bandwidth limit, but only limits the","type":"text"},{"type":"text","text":" "},{"type":"text","text":"average download speed. Tile regions may be temporarily downloaded with"},{"text":" ","type":"text"},{"text":"higher speed, then downloading will pause until the rolling average has","type":"text"},{"type":"text","text":" "},{"type":"text","text":"dropped below this value."}]},{"inlineContent":[{"type":"text","text":"If unspecified, the download speed will not be restricted."}],"type":"paragraph"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadOptions":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions","abstract":[{"text":"Describes the tile region load option values.","type":"text"}],"url":"\/documentation\/mapboxcommon\/tileregionloadoptions","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TileRegionLoadOptions"}],"type":"topic","kind":"symbol","title":"TileRegionLoadOptions","role":"symbol","navigatorTitle":[{"text":"TileRegionLoadOptions","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","abstract":[],"type":"topic","title":"TileStore APIs","url":"\/documentation\/mapboxmaps\/tilestore-apis","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","type":"topic","title":"MapboxMaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","role":"collection","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadOptions/averageBytesPerSecond":{"abstract":[{"type":"text","text":"Limits the download speed of the tile region."}],"url":"\/documentation\/mapboxcommon\/tileregionloadoptions\/averagebytespersecond","title":"averageBytesPerSecond","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions\/averageBytesPerSecond","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"averageBytesPerSecond","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":"?"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","type":"topic","title":"MapboxMaps Documentation","url":"\/documentation\/overview","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/title","op":"replace","value":"MBXTileRegionLoadOptions"},{"value":[{"kind":"identifier","text":"MBXTileRegionLoadOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/fragments"},{"value":[{"text":"MBXTileRegionLoadOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/navigatorTitle","op":"replace"}]}]}