{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"text":"descriptors","kind":"identifier"}],"modules":[{"name":"MapboxCommon"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"descriptors","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)MBXTilesetDescriptor","text":"TilesetDescriptor","kind":"typeIdentifier"},{"kind":"text","text":"]?"}],"title":"descriptors","symbolKind":"property","externalID":"c:objc(cs)MBXTileRegionLoadOptions(py)descriptors"},"sections":[],"abstract":[{"type":"text","text":"The tile region’s tileset descriptors."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"descriptors","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)MBXTilesetDescriptor","text":"TilesetDescriptor","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TilesetDescriptor"},{"text":"]? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"If provided, updates the tile region’s tileset descriptors that define"},{"text":" ","type":"text"},{"text":"the tilesets and zoom ranges of the tiles for the tile region.","type":"text"}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions"]]},"variants":[{"paths":["\/documentation\/mapboxcommon\/tileregionloadoptions\/descriptors"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/tileregionloadoptions\/descriptors"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions\/descriptors"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadOptions/descriptors":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"descriptors"},{"text":": [","kind":"text"},{"text":"TilesetDescriptor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXTilesetDescriptor"},{"kind":"text","text":"]?"}],"role":"symbol","url":"\/documentation\/mapboxcommon\/tileregionloadoptions\/descriptors","kind":"symbol","navigatorTitle":[{"text":"descriptors","kind":"identifier"}],"abstract":[{"text":"The tile region’s tileset descriptors.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions\/descriptors","title":"descriptors","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TilesetDescriptor":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TilesetDescriptor","navigatorTitle":[{"text":"TilesetDescriptor","kind":"identifier"}],"abstract":[{"type":"text","text":"A bundle that encapsulates tilesets creation for the tile store implementation."}],"url":"\/documentation\/mapboxcommon\/tilesetdescriptor","type":"topic","title":"TilesetDescriptor","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TilesetDescriptor","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","title":"MapboxMaps Documentation","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadOptions":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TileRegionLoadOptions","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions","navigatorTitle":[{"kind":"identifier","text":"TileRegionLoadOptions"}],"abstract":[{"type":"text","text":"Describes the tile region load option values."}],"url":"\/documentation\/mapboxcommon\/tileregionloadoptions","title":"TileRegionLoadOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","kind":"article","url":"\/documentation\/mapboxmaps\/tilestore-apis","title":"TileStore APIs","role":"collectionGroup","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","role":"collection","url":"\/documentation\/mapboxmaps","kind":"symbol","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"descriptors","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"descriptors","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSArray<MBXTilesetDescriptor *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"descriptors"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"descriptors","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions~1descriptors\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions~1descriptors\/fragments","value":[{"text":"descriptors","kind":"identifier"}],"op":"replace"},{"value":"MBXTilesetDescriptor","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TilesetDescriptor\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TilesetDescriptor\/fragments","op":"replace","value":[{"text":"MBXTilesetDescriptor","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TilesetDescriptor\/navigatorTitle","op":"replace","value":[{"text":"MBXTilesetDescriptor","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/title","value":"MBXTileRegionLoadOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/fragments","value":[{"kind":"identifier","text":"MBXTileRegionLoadOptions"}]},{"value":[{"text":"MBXTileRegionLoadOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}