{"abstract":[{"type":"text","text":"Initializes a "},{"code":"TileRegionLoadOptions","type":"codeVoice"},{"type":"text","text":", required for"},{"text":" ","type":"text"},{"type":"codeVoice","code":"TileStore.loadTileRegion(forId:loadOptions:)"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"convenience"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"text":"geometry","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps8Geometrya","kind":"typeIdentifier","text":"Geometry","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Geometry"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"descriptors"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TilesetDescriptor","preciseIdentifier":"c:objc(cs)MBXTilesetDescriptor","kind":"typeIdentifier","text":"TilesetDescriptor"},{"text":"]? = nil, ","kind":"text"},{"kind":"externalParam","text":"metadata"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"acceptExpired"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" = false, ","kind":"text"},{"text":"networkRestriction","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NetworkRestriction","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NetworkRestriction","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBXNetworkRestriction"},{"kind":"text","text":" = .none, "},{"text":"averageBytesPerSecond","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"extraOptions"},{"text":": ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"? = nil)","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"geometry","content":[{"inlineContent":[{"text":"The tile region’s associated geometry (optional).","type":"text"}],"type":"paragraph"}]},{"name":"descriptors","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The tile region’s tileset descriptors. If presented, will update the region"},{"type":"text","text":" "},{"type":"text","text":"with new descriptor."}]}]},{"name":"metadata","content":[{"type":"paragraph","inlineContent":[{"text":"A custom JSON value to be associated with this tile region.","type":"text"}]}]},{"name":"acceptExpired","content":[{"inlineContent":[{"type":"text","text":"Is not a strict bandwidth limit, but only"},{"type":"text","text":" "},{"text":"limits the average download speed. Tile regions may be temporarily","type":"text"},{"type":"text","text":" "},{"type":"text","text":"downloaded with higher speed, then downloading will pause until the rolling"},{"text":" ","type":"text"},{"type":"text","text":"average has dropped below this value."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Classify network types based on cost.","type":"text"}]}],"name":"networkRestriction"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Limits the download speed of the tile region."}]}],"name":"averageBytesPerSecond"},{"content":[{"inlineContent":[{"type":"text","text":"Restrict the tile region load request to the"},{"text":" ","type":"text"},{"type":"text","text":"specified network types. If none of the specified network types"},{"type":"text","text":" "},{"type":"text","text":"is available, the load request fails with an error. Must be a valid JSON object."}],"type":"paragraph"}],"name":"extraOptions"}]},{"kind":"content","content":[{"text":"Discussion","level":2,"anchor":"discussion","type":"heading"},{"content":[{"type":"paragraph","inlineContent":[{"text":"If ","type":"text"},{"code":"metadata","type":"codeVoice"},{"type":"text","text":" is not a valid JSON object, then this initializer returns "},{"type":"codeVoice","code":"nil"},{"text":".","type":"text"}]}],"type":"aside","style":"note","name":"Note"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/tileregionloadoptions\/init(geometry:descriptors:metadata:acceptexpired:networkrestriction:averagebytespersecond:extraoptions:)"]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions\/init(geometry:descriptors:metadata:acceptExpired:networkRestriction:averageBytesPerSecond:extraOptions:)","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","roleHeading":"Initializer","modules":[{"name":"MapboxCommon"}],"fragments":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"geometry"},{"text":": ","kind":"text"},{"text":"Geometry","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps8Geometrya"},{"kind":"text","text":"?, "},{"text":"descriptors","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"TilesetDescriptor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXTilesetDescriptor"},{"kind":"text","text":"]?, "},{"text":"metadata","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?, ","kind":"text"},{"text":"acceptExpired","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"networkRestriction","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBXNetworkRestriction","text":"NetworkRestriction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"averageBytesPerSecond"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"extraOptions","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?)"}],"title":"init(geometry:descriptors:metadata:acceptExpired:networkRestriction:averageBytesPerSecond:extraOptions:)","externalID":"s:So24MBXTileRegionLoadOptionsC10MapboxMapsE8geometry11descriptors8metadata13acceptExpired18networkRestriction21averageBytesPerSecond05extraD0ABSg4Turf8GeometryOSg_SaySo20MBXTilesetDescriptorCGSgypSgSbSo010MBXNetworkM0VSiSgATtcfc","extendedModule":"MapboxCommon","symbolKind":"init"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadOptions":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TileRegionLoadOptions","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions","navigatorTitle":[{"kind":"identifier","text":"TileRegionLoadOptions"}],"abstract":[{"type":"text","text":"Describes the tile region load option values."}],"url":"\/documentation\/mapboxcommon\/tileregionloadoptions","title":"TileRegionLoadOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","kind":"article","url":"\/documentation\/mapboxmaps\/tilestore-apis","title":"TileStore APIs","role":"collectionGroup","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/NetworkRestriction":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NetworkRestriction"}],"title":"NetworkRestriction","abstract":[{"text":"Classify network types based on cost.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NetworkRestriction","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NetworkRestriction"}],"role":"symbol","url":"\/documentation\/mapboxcommon\/networkrestriction"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TilesetDescriptor":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TilesetDescriptor","navigatorTitle":[{"text":"TilesetDescriptor","kind":"identifier"}],"abstract":[{"type":"text","text":"A bundle that encapsulates tilesets creation for the tile store implementation."}],"url":"\/documentation\/mapboxcommon\/tilesetdescriptor","type":"topic","title":"TilesetDescriptor","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TilesetDescriptor","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadOptions/init(geometry:descriptors:metadata:acceptExpired:networkRestriction:averageBytesPerSecond:extraOptions:)":{"fragments":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"geometry"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps8Geometrya","kind":"typeIdentifier","text":"Geometry"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"descriptors"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXTilesetDescriptor","text":"TilesetDescriptor"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"metadata"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"acceptExpired"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"networkRestriction"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBXNetworkRestriction","text":"NetworkRestriction"},{"text":", ","kind":"text"},{"text":"averageBytesPerSecond","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"extraOptions"},{"text":": ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"?)","kind":"text"}],"role":"symbol","url":"\/documentation\/mapboxcommon\/tileregionloadoptions\/init(geometry:descriptors:metadata:acceptexpired:networkrestriction:averagebytespersecond:extraoptions:)","kind":"symbol","abstract":[{"text":"Initializes a ","type":"text"},{"code":"TileRegionLoadOptions","type":"codeVoice"},{"type":"text","text":", required for"},{"text":" ","type":"text"},{"type":"codeVoice","code":"TileStore.loadTileRegion(forId:loadOptions:)"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions\/init(geometry:descriptors:metadata:acceptExpired:networkRestriction:averageBytesPerSecond:extraOptions:)","title":"init(geometry:descriptors:metadata:acceptExpired:networkRestriction:averageBytesPerSecond:extraOptions:)","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Geometry":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Geometry"}],"abstract":[{"type":"text","text":"An object representing points, curves, and surfaces in coordinate space. Use an instance of this enumeration whenever a value could be any kind of Geometry object."}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Geometry","navigatorTitle":[{"kind":"identifier","text":"Geometry"}],"title":"Geometry","url":"\/documentation\/mapboxmaps\/geometry","kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","role":"collection","url":"\/documentation\/mapboxmaps","kind":"symbol","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","title":"MapboxMaps Documentation","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MBXTileRegionLoadOptions","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/fragments","op":"replace","value":[{"text":"MBXTileRegionLoadOptions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/navigatorTitle","value":[{"text":"MBXTileRegionLoadOptions","kind":"identifier"}]},{"value":"MBXNetworkRestriction","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1NetworkRestriction\/title"},{"value":[{"kind":"identifier","text":"MBXNetworkRestriction"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1NetworkRestriction\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MBXNetworkRestriction"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1NetworkRestriction\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TilesetDescriptor\/title","op":"replace","value":"MBXTilesetDescriptor"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TilesetDescriptor\/fragments","value":[{"kind":"identifier","text":"MBXTilesetDescriptor"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TilesetDescriptor\/navigatorTitle","op":"replace","value":[{"text":"MBXTilesetDescriptor","kind":"identifier"}]}]}]}