{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXTileRegionLoadOptions\/geometry-1b5t1"},"sections":[],"metadata":{"symbolKind":"property","fragments":[{"text":"geometry","kind":"identifier"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"geometry","kind":"identifier"}],"title":"geometry","modules":[{"name":"MapboxCommon"}],"role":"symbol","externalID":"c:objc(cs)MBXTileRegionLoadOptions(py)geometry"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"The tile region’s associated geometry.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBXGeometry","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry","kind":"typeIdentifier","text":"MBXGeometry"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"geometry"},{"text":";","kind":"text"}],"languages":["occ"]}]},{"content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"inlineContent":[{"text":"If provided, updates the tile region’s associated geometry i.e. geometry,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"which is used in the tile cover algorithm to find out a set of tiles to be loaded"},{"text":" ","type":"text"},{"type":"text","text":"for the tile region."}],"type":"paragraph"}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions"]]},"variants":[{"paths":["\/documentation\/mapboxcommon\/mbxtileregionloadoptions\/geometry-1b5t1"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXTileRegionLoadOptions/geometry-1b5t1":{"kind":"symbol","type":"topic","fragments":[{"text":"geometry","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/mbxtileregionloadoptions\/geometry-1b5t1","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXTileRegionLoadOptions\/geometry-1b5t1","title":"geometry","abstract":[{"text":"The tile region’s associated geometry.","type":"text"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"url":"\/documentation\/mapboxmaps\/tilestore-apis","kind":"article","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","type":"topic","title":"TileStore APIs"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Geometry":{"title":"Geometry","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Geometry"}],"url":"\/documentation\/mapboxcommon\/geometry","abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Geometry"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadOptions":{"role":"symbol","abstract":[{"text":"Describes the tile region load option values.","type":"text"}],"title":"TileRegionLoadOptions","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileRegionLoadOptions","kind":"identifier"}],"navigatorTitle":[{"text":"TileRegionLoadOptions","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions","url":"\/documentation\/mapboxcommon\/tileregionloadoptions","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry\/title","value":"MBXGeometry"},{"value":[{"kind":"identifier","text":"MBXGeometry"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/title","value":"MBXTileRegionLoadOptions"},{"op":"replace","value":[{"text":"MBXTileRegionLoadOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/fragments"}]}]}