{"variants":[{"paths":["\/documentation\/mapboxcommon\/mbxtileregionloadoptions\/init(geometry:descriptors:metadata:acceptexpired:networkrestriction:averagebytespersecond:extraoptions:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"fragments":[{"text":"convenience","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"geometry","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps8Geometrya","text":"Geometry"},{"text":"?, ","kind":"text"},{"text":"descriptors","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXTilesetDescriptor","text":"TilesetDescriptor"},{"text":"]?, ","kind":"text"},{"text":"metadata","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"acceptExpired"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"networkRestriction","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NetworkRestriction","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBXNetworkRestriction"},{"text":", ","kind":"text"},{"text":"averageBytesPerSecond","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":"?, ","kind":"text"},{"text":"extraOptions","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"roleHeading":"Initializer","modules":[{"name":"MapboxCommon"}],"role":"symbol","symbolKind":"init","externalID":"s:So24MBXTileRegionLoadOptionsC10MapboxMapsE8geometry11descriptors8metadata13acceptExpired18networkRestriction21averageBytesPerSecond05extraD0ABSg4Turf8GeometryOSg_SaySo20MBXTilesetDescriptorCGSgypSgSbSo010MBXNetworkM0VSiSgATtcfc","extendedModule":"MapboxCommon","title":"init(geometry:descriptors:metadata:acceptExpired:networkRestriction:averageBytesPerSecond:extraOptions:)"},"sections":[],"abstract":[{"type":"text","text":"Initializes a "},{"code":"TileRegionLoadOptions","type":"codeVoice"},{"text":", required for","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"TileStore.loadTileRegion(forId:loadOptions:)"}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXTileRegionLoadOptions\/init(geometry:descriptors:metadata:acceptExpired:networkRestriction:averageBytesPerSecond:extraOptions:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"text":"geometry","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Geometry","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Geometry","preciseIdentifier":"s:10MapboxMaps8Geometrya","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"descriptors","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"TilesetDescriptor","preciseIdentifier":"c:objc(cs)MBXTilesetDescriptor","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TilesetDescriptor"},{"kind":"text","text":"]? = nil, "},{"text":"metadata","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"acceptExpired"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":" = false, ","kind":"text"},{"kind":"externalParam","text":"networkRestriction"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@MBXNetworkRestriction","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NetworkRestriction","text":"NetworkRestriction"},{"text":" = .none, ","kind":"text"},{"kind":"externalParam","text":"averageBytesPerSecond"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"extraOptions","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Any","kind":"keyword"},{"text":"? = nil)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"geometry","content":[{"inlineContent":[{"type":"text","text":"The tile region’s associated geometry (optional)."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"The tile region’s tileset descriptors. If presented, will update the region","type":"text"},{"type":"text","text":" "},{"text":"with new descriptor.","type":"text"}],"type":"paragraph"}],"name":"descriptors"},{"name":"metadata","content":[{"inlineContent":[{"type":"text","text":"A custom JSON value to be associated with this tile region."}],"type":"paragraph"}]},{"name":"extraOptions","content":[{"inlineContent":[{"text":"Restrict the tile region load request to the","type":"text"},{"type":"text","text":" "},{"type":"text","text":"specified network types. If none of the specified network types"},{"text":" ","type":"text"},{"type":"text","text":"is available, the load request fails with an error. Must be a valid JSON object."}],"type":"paragraph"}]},{"name":"acceptExpired","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"is not a strict bandwidth limit, but only"},{"type":"text","text":" "},{"type":"text","text":"limits the average download speed. Tile regions may be temporarily"},{"type":"text","text":" "},{"text":"downloaded with higher speed, then downloading will pause until the rolling","type":"text"},{"type":"text","text":" "},{"type":"text","text":"average has dropped below this value."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Classify network types based on cost.","type":"text"}]}],"name":"networkRestriction"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Limits the download speed of the tile region.","type":"text"}]}],"name":"averageBytesPerSecond"}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"name":"Note","type":"aside","content":[{"inlineContent":[{"text":"If ","type":"text"},{"type":"codeVoice","code":"metadata"},{"type":"text","text":" is not a valid JSON object, then this initializer returns "},{"code":"nil","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}],"style":"note"}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"url":"\/documentation\/mapboxmaps\/tilestore-apis","kind":"article","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","type":"topic","title":"TileStore APIs"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadOptions":{"role":"symbol","abstract":[{"text":"Describes the tile region load option values.","type":"text"}],"title":"TileRegionLoadOptions","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileRegionLoadOptions","kind":"identifier"}],"navigatorTitle":[{"text":"TileRegionLoadOptions","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions","url":"\/documentation\/mapboxcommon\/tileregionloadoptions","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TilesetDescriptor":{"role":"symbol","kind":"symbol","url":"\/documentation\/mapboxcommon\/tilesetdescriptor","type":"topic","abstract":[{"type":"text","text":"A bundle that encapsulates tilesets creation for the tile store implementation."}],"title":"TilesetDescriptor","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TilesetDescriptor"}],"navigatorTitle":[{"kind":"identifier","text":"TilesetDescriptor"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TilesetDescriptor"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXTileRegionLoadOptions/init(geometry:descriptors:metadata:acceptExpired:networkRestriction:averageBytesPerSecond:extraOptions:)":{"kind":"symbol","type":"topic","fragments":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"geometry","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Geometry","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps8Geometrya"},{"text":"?, ","kind":"text"},{"text":"descriptors","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"TilesetDescriptor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXTilesetDescriptor"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"metadata"},{"kind":"text","text":": "},{"text":"Any","kind":"keyword"},{"text":"?, ","kind":"text"},{"text":"acceptExpired","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"networkRestriction"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@MBXNetworkRestriction","kind":"typeIdentifier","text":"NetworkRestriction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"averageBytesPerSecond"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"extraOptions","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"url":"\/documentation\/mapboxcommon\/mbxtileregionloadoptions\/init(geometry:descriptors:metadata:acceptexpired:networkrestriction:averagebytespersecond:extraoptions:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXTileRegionLoadOptions\/init(geometry:descriptors:metadata:acceptExpired:networkRestriction:averageBytesPerSecond:extraOptions:)","title":"init(geometry:descriptors:metadata:acceptExpired:networkRestriction:averageBytesPerSecond:extraOptions:)","abstract":[{"type":"text","text":"Initializes a "},{"type":"codeVoice","code":"TileRegionLoadOptions"},{"text":", required for","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"TileStore.loadTileRegion(forId:loadOptions:)"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Geometry":{"title":"Geometry","navigatorTitle":[{"kind":"identifier","text":"Geometry"}],"url":"\/documentation\/mapboxmaps\/geometry","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Geometry"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Geometry","role":"symbol","abstract":[{"type":"text","text":"An object representing points, curves, and surfaces in coordinate space. Use an instance of this enumeration whenever a value could be any kind of Geometry object."}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/NetworkRestriction":{"abstract":[{"type":"text","text":"Classify network types based on cost."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NetworkRestriction","role":"symbol","url":"\/documentation\/mapboxcommon\/networkrestriction","navigatorTitle":[{"text":"NetworkRestriction","kind":"identifier"}],"type":"topic","title":"NetworkRestriction","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"NetworkRestriction","kind":"identifier"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/title","value":"MBXTileRegionLoadOptions"},{"value":[{"kind":"identifier","text":"MBXTileRegionLoadOptions"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TilesetDescriptor\/title","value":"MBXTilesetDescriptor"},{"value":[{"text":"MBXTilesetDescriptor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TilesetDescriptor\/fragments"},{"value":"MBXNetworkRestriction","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1NetworkRestriction\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1NetworkRestriction\/fragments","value":[{"kind":"identifier","text":"MBXNetworkRestriction"}]}]}]}