{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MapboxSupport"]]},"metadata":{"role":"symbol","modules":[{"name":"MapboxCommon"}],"tags":[{"type":"spi","text":"SPI"}],"title":"getSupportPackageData()","symbolKind":"method","externalID":"s:12MapboxCommon0A7SupportC03getC11PackageDatas6ResultOyAA0F3RefCs5Error_pGyFZ","roleHeading":"Type Method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getSupportPackageData","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Result","preciseIdentifier":"s:s6ResultO","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"DataRef","preciseIdentifier":"c:@M@MapboxCommon@objc(cs)MBXDataRef","kind":"typeIdentifier"},{"text":", any ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":">","kind":"text"}]},"sections":[],"variants":[{"paths":["\/documentation\/mapboxcommon\/mapboxsupport\/getsupportpackagedata()"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getSupportPackageData"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:s6ResultO","kind":"typeIdentifier","text":"Result"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@M@MapboxCommon@objc(cs)MBXDataRef","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/DataRef","kind":"typeIdentifier","text":"DataRef"},{"kind":"text","text":", any "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":">"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MapboxSupport\/getSupportPackageData()"},"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","type":"topic","abstract":[],"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/DataRef":{"url":"\/documentation\/mapboxcommon\/dataref","kind":"symbol","type":"topic","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DataRef","kind":"identifier"}],"title":"DataRef","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/DataRef","role":"symbol","navigatorTitle":[{"text":"DataRef","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"url":"\/documentation\/mapboxcommon","role":"collection","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","title":"MapboxCommon","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MapboxSupport/getSupportPackageData()":{"url":"\/documentation\/mapboxcommon\/mapboxsupport\/getsupportpackagedata()","kind":"symbol","abstract":[],"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getSupportPackageData","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Result","preciseIdentifier":"s:s6ResultO","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"DataRef","preciseIdentifier":"c:@M@MapboxCommon@objc(cs)MBXDataRef","kind":"typeIdentifier"},{"text":", any ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":">","kind":"text"}],"title":"getSupportPackageData()","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MapboxSupport\/getSupportPackageData()","role":"symbol","tags":[{"text":"SPI","type":"spi"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MapboxSupport":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapboxSupport","kind":"identifier"}],"tags":[{"text":"SPI","type":"spi"}],"kind":"symbol","url":"\/documentation\/mapboxcommon\/mapboxsupport","abstract":[],"type":"topic","title":"MapboxSupport","navigatorTitle":[{"text":"MapboxSupport","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MapboxSupport","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1DataRef\/title","value":"MBXDataRef"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1DataRef\/fragments","value":[{"text":"MBXDataRef","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1DataRef\/navigatorTitle","value":[{"kind":"identifier","text":"MBXDataRef"}]}]}]}