{"sections":[],"topicSections":[{"title":"Coordinates","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MercatorCoordinate"],"anchor":"Coordinates"},{"title":"Projection","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ProjectedMeters","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Projection\/projectedMeters(for:)"],"anchor":"Projection"},{"title":"Camera Animations","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraAnimationsManager","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraAnimator","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/BasicCameraAnimator","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraTransition","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FlyToCameraAnimator","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AnimationCompletion","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AnimationOwner","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TimingCurve"],"anchor":"Camera-Animations"},{"title":"Viewport","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportManager","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportStatus","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportStatusObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportStatusChangeReason","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportState","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FollowPuckViewportState","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FollowPuckViewportStateOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FollowPuckViewportStateBearing","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OverviewViewportState","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OverviewViewportStateOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportTransition","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/DefaultViewportTransition","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/DefaultViewportTransitionOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImmediateViewportTransition"],"anchor":"Viewport"}],"seeAlsoSections":[{"generated":true,"anchor":"Other","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Ornaments","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Gestures","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Settings-and-Constants"],"title":"Other"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"article","metadata":{"roleHeading":"API Collection","title":"Camera and coordinates","modules":[{"name":"MapboxMaps"}],"role":"collectionGroup"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"],["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs"]]},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Camera-and-coordinates","interfaceLanguage":"swift"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TimingCurve":{"title":"TimingCurve","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TimingCurve"}],"url":"\/documentation\/mapboxmaps\/timingcurve","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TimingCurve","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TimingCurve"}],"kind":"symbol","role":"symbol","abstract":[{"text":"Timing curve to use in animator.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewportStatusChangeReason":{"title":"ViewportStatusChangeReason","url":"\/documentation\/mapboxmaps\/viewportstatuschangereason","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ViewportStatusChangeReason","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportStatusChangeReason","navigatorTitle":[{"text":"ViewportStatusChangeReason","kind":"identifier"}],"abstract":[{"type":"text","text":"Constants that describe why "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportManager\/status"},{"type":"text","text":" changed."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FollowPuckViewportStateBearing":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/followpuckviewportstatebearing","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FollowPuckViewportStateBearing"}],"title":"FollowPuckViewportStateBearing","abstract":[{"text":"Expresses the different ways that ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FollowPuckViewportState","type":"reference","isActive":true},{"text":" can obtain values to use when","type":"text"},{"text":" ","type":"text"},{"text":"setting ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraOptions\/bearing","type":"reference","isActive":true},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FollowPuckViewportStateBearing"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FollowPuckViewportStateBearing","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FollowPuckViewportState":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FollowPuckViewportState"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FollowPuckViewportState","abstract":[{"type":"text","text":"A "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportState"},{"type":"text","text":" implementation that tracks the location puck (to show a puck, use"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationOptions\/puckType"},{"type":"text","text":")"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FollowPuckViewportState"}],"type":"topic","url":"\/documentation\/mapboxmaps\/followpuckviewportstate","title":"FollowPuckViewportState","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewportTransition":{"abstract":[{"code":"ViewportTransition","type":"codeVoice"},{"text":" is a protocol that ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportManager","isActive":true,"type":"reference"},{"text":" depends on as it orchestrates transitions","type":"text"},{"text":" ","type":"text"},{"text":"to and from different ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportState","isActive":true,"type":"reference"},{"text":"s.","type":"text"}],"url":"\/documentation\/mapboxmaps\/viewporttransition","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ViewportTransition","kind":"identifier"}],"navigatorTitle":[{"text":"ViewportTransition","kind":"identifier"}],"title":"ViewportTransition","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportTransition"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewportState":{"title":"ViewportState","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ViewportState"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ViewportState"}],"abstract":[{"type":"codeVoice","code":"ViewportState"},{"type":"text","text":" is a protocol that "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportManager"},{"type":"text","text":" depends on as it orchestrates transitions to and"},{"type":"text","text":" "},{"type":"text","text":"from different states."}],"role":"symbol","url":"\/documentation\/mapboxmaps\/viewportstate"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraOptions/bearing":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bearing","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CLLocationDirection","kind":"typeIdentifier","preciseIdentifier":"c:@T@CLLocationDirection"},{"text":"?","kind":"text"}],"type":"topic","url":"\/documentation\/mapboxmaps\/cameraoptions\/bearing","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraOptions\/bearing","title":"bearing","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The bearing of the map, measured in degrees clockwise from true north. Defaults to 0."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraTransition":{"type":"topic","abstract":[{"text":"Structure used to represent a desired change to the map’s camera","type":"text"}],"title":"CameraTransition","kind":"symbol","navigatorTitle":[{"text":"CameraTransition","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraTransition","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraTransition","url":"\/documentation\/mapboxmaps\/cameratransition","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ImmediateViewportTransition":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImmediateViewportTransition"}],"abstract":[{"type":"text","text":"A "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportTransition"},{"type":"text","text":" implementation that transitions immediately without any animation."}],"title":"ImmediateViewportTransition","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ImmediateViewportTransition"}],"url":"\/documentation\/mapboxmaps\/immediateviewporttransition","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImmediateViewportTransition","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MercatorCoordinate":{"kind":"symbol","type":"topic","role":"symbol","title":"MercatorCoordinate","navigatorTitle":[{"text":"MercatorCoordinate","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/mercatorcoordinate","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MercatorCoordinate","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MercatorCoordinate","kind":"identifier"}],"abstract":[{"type":"text","text":"Describes a point on the map in Mercator projection."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OverviewViewportStateOptions":{"navigatorTitle":[{"text":"OverviewViewportStateOptions","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxmaps\/overviewviewportstateoptions","abstract":[{"type":"text","text":"Configuration options for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OverviewViewportState"},{"type":"text","text":"."}],"title":"OverviewViewportStateOptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OverviewViewportStateOptions","role":"symbol","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OverviewViewportStateOptions","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AnimationOwner":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AnimationOwner"}],"abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnimationOwner"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AnimationOwner","title":"AnimationOwner","role":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/animationowner"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Ornaments":{"type":"topic","abstract":[],"kind":"article","role":"collectionGroup","title":"Ornaments","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Ornaments","url":"\/documentation\/mapboxmaps\/ornaments"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Settings-and-Constants":{"url":"\/documentation\/mapboxmaps\/settings-and-constants","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Settings-and-Constants","type":"topic","kind":"article","abstract":[],"title":"Settings and Constants","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AnimationCompletion":{"title":"AnimationCompletion","navigatorTitle":[{"text":"AnimationCompletion","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/animationcompletion","type":"topic","abstract":[{"text":"A block object to be executed when the animation sequence ends.","type":"text"}],"role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AnimationCompletion","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AnimationCompletion","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FlyToCameraAnimator":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FlyToCameraAnimator","role":"symbol","url":"\/documentation\/mapboxmaps\/flytocameraanimator","abstract":[{"type":"text","text":"An animator that evokes powered flight and an optional transition duration and timing function."},{"type":"text","text":" "},{"type":"text","text":"It seamlessly incorporates zooming and panning to help the user find their bearings even after"},{"type":"text","text":" "},{"type":"text","text":"traversing a great distance."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FlyToCameraAnimator"}],"navigatorTitle":[{"kind":"identifier","text":"FlyToCameraAnimator"}],"type":"topic","title":"FlyToCameraAnimator","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewportManager/addStatusObserver(_:)":{"kind":"symbol","title":"addStatusObserver(_:)","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addStatusObserver"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps22ViewportStatusObserverP","text":"ViewportStatusObserver"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Subscribes a "},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportStatusObserver","isActive":true},{"type":"text","text":" to "},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportManager\/status","isActive":true},{"type":"text","text":" changes."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportManager\/addStatusObserver(_:)","url":"\/documentation\/mapboxmaps\/viewportmanager\/addstatusobserver(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraAnimator":{"title":"CameraAnimator","abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraAnimator","kind":"identifier"}],"navigatorTitle":[{"text":"CameraAnimator","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/cameraanimator","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraAnimator","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/DefaultViewportTransition":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DefaultViewportTransition","kind":"identifier"}],"abstract":[{"text":"A default ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportTransition","isActive":true,"type":"reference"},{"text":" implementation.","type":"text"}],"url":"\/documentation\/mapboxmaps\/defaultviewporttransition","navigatorTitle":[{"text":"DefaultViewportTransition","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/DefaultViewportTransition","title":"DefaultViewportTransition","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OverviewViewportStateOptions/geometry":{"url":"\/documentation\/mapboxmaps\/overviewviewportstateoptions\/geometry","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OverviewViewportStateOptions\/geometry","abstract":[{"type":"text","text":"The geometry that the "},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OverviewViewportState","isActive":true},{"type":"text","text":" should use when calculating its camera."}],"type":"topic","title":"geometry","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"geometry","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps8Geometrya","text":"Geometry","kind":"typeIdentifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Location-APIs":{"title":"Location","role":"collectionGroup","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","kind":"article","abstract":[],"url":"\/documentation\/mapboxmaps\/location-apis"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"abstract":[],"type":"topic","kind":"article","title":"MapboxMap","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/mapboxmap-apis"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Projection/projectedMeters(for:)":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Projection\/projectedMeters(for:)","title":"projectedMeters(for:)","url":"\/documentation\/mapboxmaps\/projection\/projectedmeters(for:)","type":"topic","abstract":[{"type":"text","text":"Calculate Spherical Mercator ProjectedMeters coordinates."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"projectedMeters","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"text":") -> ","kind":"text"},{"text":"ProjectedMeters","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMProjectedMeters"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OverviewViewportState":{"role":"symbol","navigatorTitle":[{"text":"OverviewViewportState","kind":"identifier"}],"title":"OverviewViewportState","type":"topic","abstract":[{"text":"A ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportState","type":"reference"},{"type":"text","text":" implementation that shows an overview of the geometry specified by its"},{"type":"text","text":" "},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OverviewViewportStateOptions\/geometry","isActive":true},{"type":"text","text":"."}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/overviewviewportstate","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OverviewViewportState","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OverviewViewportState"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewportStatus":{"title":"ViewportStatus","kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/viewportstatus","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportStatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ViewportStatus","kind":"identifier"}],"abstract":[{"code":"ViewportStatus","type":"codeVoice"},{"text":" contains 3 cases that express what the ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportManager","isActive":true,"type":"reference"},{"text":" is doing at any given time.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"ViewportStatus","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewportOptions":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ViewportOptions","kind":"identifier"}],"navigatorTitle":[{"text":"ViewportOptions","kind":"identifier"}],"kind":"symbol","title":"ViewportOptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportOptions","role":"symbol","url":"\/documentation\/mapboxmaps\/viewportoptions","abstract":[{"text":"Configuration options for ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportManager","isActive":true,"type":"reference"},{"text":".","type":"text"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LocationOptions/puckType":{"title":"puckType","kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/locationoptions\/pucktype","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationOptions\/puckType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"puckType"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10MapboxMaps8PuckTypeO","kind":"typeIdentifier","text":"PuckType"},{"kind":"text","text":"?"}],"abstract":[{"text":"Sets the type of puck that should be used","type":"text"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraAnimationsManager":{"title":"CameraAnimationsManager","abstract":[{"type":"text","text":"APIs for animating the camera."}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraAnimationsManager","kind":"identifier"}],"navigatorTitle":[{"text":"CameraAnimationsManager","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/cameraanimationsmanager","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraAnimationsManager"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewportManager":{"url":"\/documentation\/mapboxmaps\/viewportmanager","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ViewportManager","kind":"identifier"}],"role":"symbol","title":"ViewportManager","type":"topic","navigatorTitle":[{"text":"ViewportManager","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportManager","abstract":[{"type":"codeVoice","code":"Viewport"},{"text":" provides a structured approach to organizing camera management logic into states and","type":"text"},{"text":" ","type":"text"},{"text":"transitions between them.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewportManager/status":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportManager\/status","kind":"symbol","url":"\/documentation\/mapboxmaps\/viewportmanager\/status","abstract":[{"type":"text","text":"The current "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportStatus"},{"type":"text","text":"."}],"title":"status","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps14ViewportStatusO","text":"ViewportStatus"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Gestures":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Gestures","role":"collectionGroup","type":"topic","title":"Gestures","abstract":[],"kind":"article","url":"\/documentation\/mapboxmaps\/gestures"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/DefaultViewportTransitionOptions":{"abstract":[{"type":"text","text":"Configuration options for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/DefaultViewportTransition"},{"type":"text","text":"."}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/DefaultViewportTransitionOptions","title":"DefaultViewportTransitionOptions","url":"\/documentation\/mapboxmaps\/defaultviewporttransitionoptions","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DefaultViewportTransitionOptions","kind":"identifier"}],"navigatorTitle":[{"text":"DefaultViewportTransitionOptions","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FollowPuckViewportStateOptions":{"abstract":[{"text":"Configuration options for ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FollowPuckViewportState","isActive":true},{"text":".","type":"text"}],"url":"\/documentation\/mapboxmaps\/followpuckviewportstateoptions","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FollowPuckViewportStateOptions","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"FollowPuckViewportStateOptions","kind":"identifier"}],"title":"FollowPuckViewportStateOptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FollowPuckViewportStateOptions","kind":"symbol"},"http://docs.openlayers.org/library/spherical_mercator.html":{"titleInlineContent":[{"type":"text","text":"Spherical Mercator"}],"identifier":"http:\/\/docs.openlayers.org\/library\/spherical_mercator.html","type":"link","title":"Spherical Mercator","url":"http:\/\/docs.openlayers.org\/library\/spherical_mercator.html"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewportStatusObserver":{"title":"ViewportStatusObserver","url":"\/documentation\/mapboxmaps\/viewportstatusobserver","navigatorTitle":[{"text":"ViewportStatusObserver","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"codeVoice","code":"ViewportStatusObserver"},{"type":"text","text":" must be implemented by objects that wish to register"},{"type":"text","text":" "},{"type":"text","text":"themselves using "},{"isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportManager\/addStatusObserver(_:)","type":"reference"},{"type":"text","text":" so that they can observe"},{"type":"text","text":" "},{"isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportManager\/status","type":"reference"},{"type":"text","text":" changes."}],"type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ViewportStatusObserver","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportStatusObserver"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/BasicCameraAnimator":{"title":"BasicCameraAnimator","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/BasicCameraAnimator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BasicCameraAnimator"}],"url":"\/documentation\/mapboxmaps\/basiccameraanimator","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BasicCameraAnimator"}],"abstract":[],"kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","abstract":[],"url":"\/documentation\/overview","type":"topic","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ProjectedMeters":{"url":"\/documentation\/mapboxmaps\/projectedmeters","abstract":[{"type":"text","text":"ProjectedMeters is a coordinate in a specific"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"http:\/\/docs.openlayers.org\/library\/spherical_mercator.html"},{"type":"text","text":" projection."}],"role":"symbol","title":"ProjectedMeters","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ProjectedMeters","navigatorTitle":[{"text":"ProjectedMeters","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ProjectedMeters","kind":"identifier"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","title":"MapboxMaps","type":"topic","url":"\/documentation\/mapboxmaps","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MercatorCoordinate\/title","value":"MBMMercatorCoordinate"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MercatorCoordinate\/fragments","value":[{"text":"MBMMercatorCoordinate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MercatorCoordinate\/navigatorTitle","value":[{"text":"MBMMercatorCoordinate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ProjectedMeters\/title","value":"MBMProjectedMeters"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ProjectedMeters\/fragments","value":[{"text":"MBMProjectedMeters","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ProjectedMeters\/navigatorTitle","value":[{"kind":"identifier","text":"MBMProjectedMeters"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}