{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"SSL related error."}],"variants":[{"paths":["\/documentation\/mapboxcommon\/httprequesterrortype\/sslerror"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxcommon\/httprequesterrortype\/sslerror"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@E@MBXHttpRequestErrorType@MBXHttpRequestErrorTypeSSLError","title":"HttpRequestErrorType.sslError","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"sslError"}],"roleHeading":"Case","symbolKind":"case","modules":[{"name":"MapboxCommon"}],"navigatorTitle":[{"kind":"identifier","text":"MBXHttpRequestErrorTypeSSLError"}],"role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType\/sslError"},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sslError","kind":"identifier"}],"platforms":["iOS"]}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestErrorType/sslError":{"url":"\/documentation\/mapboxcommon\/httprequesterrortype\/sslerror","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"sslError"}],"title":"HttpRequestErrorType.sslError","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType\/sslError","kind":"symbol","abstract":[{"type":"text","text":"SSL related error."}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MBXHttpRequestErrorTypeSSLError"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"url":"\/documentation\/mapboxcommon","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","role":"collection","title":"MapboxCommon","type":"topic","kind":"symbol","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestErrorType":{"kind":"symbol","title":"HttpRequestErrorType","role":"symbol","navigatorTitle":[{"text":"HttpRequestErrorType","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType","url":"\/documentation\/mapboxcommon\/httprequesterrortype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HttpRequestErrorType","kind":"identifier"}],"abstract":[{"type":"text","text":"Enum which describes possible error types which could happen during HTTP request\/download calls."}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","role":"collection","type":"topic","abstract":[],"title":"MapboxMaps Documentation","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"MBXHttpRequestErrorTypeSSLError"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"MBXHttpRequestErrorTypeSSLError","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"MBXHttpRequestErrorTypeSSLError","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestErrorType~1sslError\/title","op":"replace","value":"MBXHttpRequestErrorTypeSSLError"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestErrorType~1sslError\/fragments","op":"replace","value":[{"text":"MBXHttpRequestErrorTypeSSLError","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestErrorType\/title","op":"replace","value":"MBXHttpRequestErrorType"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestErrorType\/fragments","op":"replace","value":[{"text":"MBXHttpRequestErrorType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestErrorType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBXHttpRequestErrorType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}