{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode\/communicationFailure"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"communicationFailure"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Failed to communicate with the platform service.","type":"text"}],"variants":[{"paths":["\/documentation\/mapboxcommon\/locationerrorcode\/communicationfailure"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxcommon\/locationerrorcode\/communicationfailure"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"communicationFailure","kind":"identifier"}],"externalID":"c:@E@MBXLocationErrorCode@MBXLocationErrorCodeCommunicationFailure","modules":[{"name":"MapboxCommon"}],"navigatorTitle":[{"kind":"identifier","text":"MBXLocationErrorCodeCommunicationFailure"}],"roleHeading":"Case","symbolKind":"case","title":"LocationErrorCode.communicationFailure","role":"symbol"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","url":"\/documentation\/mapboxmaps","title":"MapboxMaps","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationErrorCode":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode","type":"topic","abstract":[{"type":"text","text":"Codes of location errors."}],"role":"symbol","navigatorTitle":[{"text":"LocationErrorCode","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/locationerrorcode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationErrorCode","kind":"identifier"}],"title":"LocationErrorCode","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","role":"collection","type":"topic","abstract":[],"title":"MapboxMaps Documentation","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationErrorCode/communicationFailure":{"navigatorTitle":[{"kind":"identifier","text":"MBXLocationErrorCodeCommunicationFailure"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode\/communicationFailure","kind":"symbol","abstract":[{"text":"Failed to communicate with the platform service.","type":"text"}],"url":"\/documentation\/mapboxcommon\/locationerrorcode\/communicationfailure","title":"LocationErrorCode.communicationFailure","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"communicationFailure"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Location-APIs":{"role":"collectionGroup","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","url":"\/documentation\/mapboxmaps\/location-apis","type":"topic","title":"Location","kind":"article"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"MBXLocationErrorCodeCommunicationFailure","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"MBXLocationErrorCodeCommunicationFailure","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"MBXLocationErrorCodeCommunicationFailure"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"MBXLocationErrorCode","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/title"},{"op":"replace","value":[{"text":"MBXLocationErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MBXLocationErrorCode"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/navigatorTitle"},{"op":"replace","value":"MBXLocationErrorCodeCommunicationFailure","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode~1communicationFailure\/title"},{"op":"replace","value":[{"text":"MBXLocationErrorCodeCommunicationFailure","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode~1communicationFailure\/fragments"}]}]}