{"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePack\/expires","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"expires"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"expires"}],"externalID":"c:objc(cs)MBMStylePack(py)expires","modules":[{"name":"MapboxMaps"}],"roleHeading":"Instance Property","title":"expires","role":"symbol","symbolKind":"property"},"variants":[{"paths":["\/documentation\/mapboxmaps\/stylepack\/expires"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/stylepack\/expires"]}],"kind":"symbol","abstract":[{"type":"text","text":"The earliest point in time when any of the style package resources gets expired."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePack"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"expires","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"Unitialized for incomplete style packages or for complete style packages with all immutable resources.","type":"text"}]}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"kind":"article","role":"collection","url":"\/documentation\/overview","title":"MapboxMaps Documentation","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"type":"topic","abstract":[],"title":"TileStore APIs","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","url":"\/documentation\/mapboxmaps\/tilestore-apis","role":"collectionGroup","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","title":"MapboxMaps","role":"collection","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePack":{"title":"StylePack","url":"\/documentation\/mapboxmaps\/stylepack","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"StylePack","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePack","kind":"symbol","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"style pack"},{"type":"text","text":" represents a stored style package."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"StylePack"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePack/expires":{"url":"\/documentation\/mapboxmaps\/stylepack\/expires","abstract":[{"type":"text","text":"The earliest point in time when any of the style package resources gets expired."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"expires"},{"kind":"text","text":": "},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"expires","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePack\/expires","title":"expires"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"expires"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"expires","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"NSDate","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDate"},{"kind":"text","text":" * "},{"text":"expires","kind":"identifier"},{"kind":"text","text":";"}]}]},"op":"replace"},{"value":"MBMStylePack","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePack\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePack\/fragments","value":[{"kind":"identifier","text":"MBMStylePack"}],"op":"replace"},{"value":[{"text":"MBMStylePack","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePack\/navigatorTitle","op":"replace"},{"value":"expires","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePack~1expires\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePack~1expires\/fragments","value":[{"text":"expires","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}