{"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LoggingLevel"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/mapboxcommon\/logginglevel\/warning"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxcommon\/logginglevel\/warning"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"type":"text","text":"To log a situation that might be a problem, or an unusual situation."}],"metadata":{"navigatorTitle":[{"text":"MBXLoggingLevelWarning","kind":"identifier"}],"modules":[{"name":"MapboxCommon"}],"role":"symbol","roleHeading":"Case","symbolKind":"case","externalID":"c:@E@MBXLoggingLevel@MBXLoggingLevelWarning","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"warning","kind":"identifier"}],"title":"LoggingLevel.warning"},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LoggingLevel\/warning","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"warning"}],"platforms":["iOS"]}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","type":"topic","title":"MapboxMaps","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"type":"topic","url":"\/documentation\/overview","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LoggingLevel/warning":{"url":"\/documentation\/mapboxcommon\/logginglevel\/warning","navigatorTitle":[{"kind":"identifier","text":"MBXLoggingLevelWarning"}],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"warning"}],"abstract":[{"type":"text","text":"To log a situation that might be a problem, or an unusual situation."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LoggingLevel\/warning","kind":"symbol","role":"symbol","title":"LoggingLevel.warning"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LoggingLevel":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LoggingLevel","title":"LoggingLevel","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoggingLevel"}],"abstract":[{"type":"text","text":"State level of a log message."}],"navigatorTitle":[{"kind":"identifier","text":"LoggingLevel"}],"url":"\/documentation\/mapboxcommon\/logginglevel","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Performance":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","role":"collectionGroup","abstract":[],"title":"Performance and investigations","kind":"article","type":"topic","url":"\/documentation\/mapboxmaps\/performance"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MBXLoggingLevelWarning"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MBXLoggingLevelWarning","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"MBXLoggingLevelWarning","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LoggingLevel~1warning\/title","value":"MBXLoggingLevelWarning"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LoggingLevel~1warning\/fragments","value":[{"text":"MBXLoggingLevelWarning","kind":"identifier"}]},{"value":"MBXLoggingLevel","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LoggingLevel\/title"},{"value":[{"text":"MBXLoggingLevel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LoggingLevel\/fragments"},{"value":[{"text":"MBXLoggingLevel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LoggingLevel\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}