{"abstract":[{"type":"text","text":"The map view’s maximum pitch in degrees."}],"sections":[],"metadata":{"roleHeading":"Type Property","role":"symbol","externalID":"c:objc(cs)MBMMapConstants(cpy)MaxPitch","modules":[{"name":"MapboxMaps"}],"navigatorTitle":[{"text":"MaxPitch","kind":"identifier"}],"title":"maxPitch","symbolKind":"property","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"maxPitch","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maxPitch"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/mapconstants\/maxpitch"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/mapconstants\/maxpitch"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Settings-and-Constants","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapConstants"]]},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapConstants\/maxPitch","interfaceLanguage":"swift"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Settings-and-Constants":{"role":"collectionGroup","title":"Settings and Constants","url":"\/documentation\/mapboxmaps\/settings-and-constants","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Settings-and-Constants","kind":"article","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","abstract":[],"kind":"article","url":"\/documentation\/overview","type":"topic","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapConstants/maxPitch":{"abstract":[{"text":"The map view’s maximum pitch in degrees.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapConstants\/maxPitch","type":"topic","navigatorTitle":[{"text":"MaxPitch","kind":"identifier"}],"title":"maxPitch","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"maxPitch","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"url":"\/documentation\/mapboxmaps\/mapconstants\/maxpitch","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","url":"\/documentation\/mapboxmaps","role":"collection","title":"MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapConstants":{"url":"\/documentation\/mapboxmaps\/mapconstants","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapConstants","role":"symbol","abstract":[{"text":"Collection of useful constants.","type":"text"}],"title":"MapConstants","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MapConstants","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MapConstants"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"value":"MaxPitch","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"MaxPitch","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"double","preciseIdentifier":"c:d","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"MaxPitch","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapConstants~1maxPitch\/title","value":"MaxPitch","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapConstants~1maxPitch\/fragments","op":"replace","value":[{"kind":"identifier","text":"MaxPitch"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapConstants\/title","op":"replace","value":"MBMMapConstants"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapConstants\/fragments","value":[{"text":"MBMMapConstants","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MBMMapConstants"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapConstants\/navigatorTitle"}]}]}