{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completedResourceCount"},{"text":": ","kind":"text"},{"text":"UInt64","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"The number of resources that have been fully downloaded and are ready for"},{"type":"text","text":" "},{"type":"text","text":"offline access."}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionStatus"]]},"variants":[{"paths":["\/documentation\/mapboxmaps\/offlineregionstatus\/completedresourcecount"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/offlineregionstatus\/completedresourcecount"]}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionStatus\/completedResourceCount","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"MapboxMaps"}],"navigatorTitle":[{"text":"completedResourceCount","kind":"identifier"}],"role":"symbol","title":"completedResourceCount","platforms":[],"symbolKind":"property","roleHeading":"Instance Property","externalID":"c:objc(cs)MBMOfflineRegionStatus(py)completedResourceCount","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"completedResourceCount","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V","text":"UInt64"}]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionStatus":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionStatus","title":"OfflineRegionStatus","navigatorTitle":[{"text":"OfflineRegionStatus","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/offlineregionstatus","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OfflineRegionStatus"}],"deprecated":true,"abstract":[{"type":"text","text":"A region’s status includes its active\/inactive state as well as counts"},{"text":" ","type":"text"},{"type":"text","text":"of the number of resources that have completed downloading, their total"},{"type":"text","text":" "},{"type":"text","text":"size in bytes, and the total number of resources that are required."}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/mapboxmaps","title":"MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionStatus/completedResourceCount":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionStatus\/completedResourceCount","deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"completedResourceCount"}],"url":"\/documentation\/mapboxmaps\/offlineregionstatus\/completedresourcecount","role":"symbol","title":"completedResourceCount","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"completedResourceCount","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V","text":"UInt64"}],"kind":"symbol","type":"topic","abstract":[{"text":"The number of resources that have been fully downloaded and are ready for","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"offline access."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Offline":{"role":"collectionGroup","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","title":"Offline Support","url":"\/documentation\/mapboxmaps\/offline","type":"topic","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","abstract":[],"kind":"article","role":"collection","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMaps":{"title":"Core Maps API","kind":"article","type":"topic","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/coremaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","abstract":[{"type":"text","text":"Maps rendering SDK also known as GL-Native"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"completedResourceCount","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"completedResourceCount","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@uint64_t","text":"uint64_t","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"completedResourceCount","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionStatus\/title","op":"replace","value":"MBMOfflineRegionStatus"},{"value":[{"text":"MBMOfflineRegionStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionStatus\/fragments"},{"value":[{"text":"MBMOfflineRegionStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionStatus\/navigatorTitle"},{"value":"completedResourceCount","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionStatus~1completedResourceCount\/title"},{"value":[{"kind":"identifier","text":"completedResourceCount"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionStatus~1completedResourceCount\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}