{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"geometryCollection"},{"kind":"text","text":" "},{"text":"geometries","kind":"internalParam"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry","text":"Geometry","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXGeometry"},{"kind":"text","text":"])"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry\/init(geometryCollection:)","interfaceLanguage":"swift"},"sections":[],"metadata":{"modules":[{"name":"MapboxCommon"}],"role":"symbol","roleHeading":"Initializer","symbolKind":"init","externalID":"c:objc(cs)MBXGeometry(im)initWithGeometryCollection:","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"geometryCollection","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"Geometry","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXGeometry"},{"text":"])","kind":"text"}],"title":"init(geometryCollection:)","navigatorTitle":[{"kind":"identifier","text":"initWithGeometryCollection:"}]},"kind":"symbol","variants":[{"paths":["\/documentation\/mapboxcommon\/geometry\/init(geometrycollection:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxcommon\/geometry\/init(geometrycollection:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Geometry/init(geometryCollection:)":{"role":"symbol","url":"\/documentation\/mapboxcommon\/geometry\/init(geometrycollection:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"geometryCollection"},{"kind":"text","text":": ["},{"text":"Geometry","preciseIdentifier":"c:objc(cs)MBXGeometry","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry\/init(geometryCollection:)","title":"init(geometryCollection:)","type":"topic","navigatorTitle":[{"text":"initWithGeometryCollection:","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Geometry":{"title":"Geometry","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Geometry"}],"url":"\/documentation\/mapboxcommon\/geometry","abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Geometry"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"title":"MapboxCommon","role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","abstract":[],"url":"\/documentation\/mapboxcommon"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"initWithGeometryCollection:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithGeometryCollection:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithGeometryCollection:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<MBXGeometry *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"geometries"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"initWithGeometryCollection:","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry~1init(geometryCollection:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithGeometryCollection:"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry~1init(geometryCollection:)\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry\/title","value":"MBXGeometry","op":"replace"},{"value":[{"kind":"identifier","text":"MBXGeometry"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}