{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/mbmrenderedqueryoptions\/initwithlayerids:filter:"]}],"kind":"symbol","metadata":{"fragments":[{"text":"- ","kind":"text"},{"text":"initWithLayerIds:filter:","kind":"identifier"}],"externalID":"c:objc(cs)MBMRenderedQueryOptions(im)initWithLayerIds:filter:","modules":[{"name":"MapboxMaps"}],"navigatorTitle":[{"text":"initWithLayerIds:filter:","kind":"identifier"}],"title":"initWithLayerIds:filter:","role":"symbol","roleHeading":"Instance Method","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryOptions"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithLayerIds:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"layerIds"},{"kind":"text","text":" "},{"kind":"identifier","text":"filter:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"internalParam","text":"filter"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRenderedQueryOptions\/initWithLayerIds:filter:"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderedQueryOptions":{"kind":"symbol","role":"symbol","abstract":[{"text":"Options for querying rendered features.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryOptions","navigatorTitle":[{"kind":"identifier","text":"RenderedQueryOptions"}],"title":"RenderedQueryOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RenderedQueryOptions"}],"url":"\/documentation\/mapboxmaps\/renderedqueryoptions","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMRenderedQueryOptions/initWithLayerIds:filter:":{"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithLayerIds:filter:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithLayerIds:filter:","kind":"identifier"}],"abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMRenderedQueryOptions\/initWithLayerIds:filter:","url":"\/documentation\/mapboxmaps\/mbmrenderedqueryoptions\/initwithlayerids:filter:","title":"initWithLayerIds:filter:"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article","url":"\/documentation\/overview","role":"collection","abstract":[],"title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"kind":"article","abstract":[],"title":"MapboxMap","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","url":"\/documentation\/mapboxmaps\/mapboxmap-apis","role":"collectionGroup"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderedQueryOptions\/title","value":"MBMRenderedQueryOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderedQueryOptions\/fragments","value":[{"kind":"identifier","text":"MBMRenderedQueryOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderedQueryOptions\/navigatorTitle","value":[{"text":"MBMRenderedQueryOptions","kind":"identifier"}]}]}]}