{"variants":[{"paths":["\/documentation\/mapboxmaps\/mapboxmap\/setconstrainmode(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/setConstrainMode(_:)","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Set the map constrain mode","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setConstrainMode","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"constrainMode"},{"text":": ","kind":"text"},{"text":"ConstrainMode","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ConstrainMode","preciseIdentifier":"c:@E@MBMConstrainMode","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The map constraint mode to set"}],"type":"paragraph"}],"name":"constrainMode"}],"kind":"parameters"}],"metadata":{"title":"setConstrainMode(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setConstrainMode"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ConstrainMode","preciseIdentifier":"c:@E@MBMConstrainMode"},{"text":")","kind":"text"}],"externalID":"s:10MapboxMaps0A3MapC16setConstrainModeyySo012MBMConstrainF0VF","modules":[{"name":"MapboxMaps"}]},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap"]]},"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"title":"MapboxMap","url":"\/documentation\/mapboxmaps\/mapboxmap-apis","kind":"article","type":"topic","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap":{"url":"\/documentation\/mapboxmaps\/mapboxmap","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MapboxMap"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapboxMap"}],"title":"MapboxMap","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","kind":"symbol","abstract":[{"type":"text","text":"Provides access to the map model, including the camera, style, observable map events,"},{"type":"text","text":" "},{"type":"text","text":"and querying rendered features."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ConstrainMode":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConstrainMode"}],"url":"\/documentation\/mapboxmaps\/constrainmode","type":"topic","kind":"symbol","role":"symbol","title":"ConstrainMode","abstract":[{"type":"text","text":"Describes whether to constrain the map in both axes or only vertically e.g. while panning."}],"navigatorTitle":[{"text":"ConstrainMode","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ConstrainMode"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/setConstrainMode(_:)":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/setConstrainMode(_:)","abstract":[{"text":"Set the map constrain mode","type":"text"}],"url":"\/documentation\/mapboxmaps\/mapboxmap\/setconstrainmode(_:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setConstrainMode"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@MBMConstrainMode","kind":"typeIdentifier","text":"ConstrainMode"},{"kind":"text","text":")"}],"title":"setConstrainMode(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"role":"collection","url":"\/documentation\/mapboxmaps","title":"MapboxMaps","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","abstract":[],"type":"topic","kind":"article","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ConstrainMode\/title","value":"MBMConstrainMode","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ConstrainMode\/fragments","value":[{"kind":"identifier","text":"MBMConstrainMode"}],"op":"replace"},{"value":[{"kind":"identifier","text":"MBMConstrainMode"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ConstrainMode\/navigatorTitle"}]}]}