{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType"]]},"kind":"symbol","abstract":[{"type":"text","text":"The operation was canceled."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"canceled","kind":"identifier"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"canceled"}],"modules":[{"name":"MapboxCommon"}],"symbolKind":"case","roleHeading":"Case","title":"TileRegionErrorType.canceled","navigatorTitle":[{"text":"MBXTileRegionErrorTypeCanceled","kind":"identifier"}],"role":"symbol","externalID":"c:@E@MBXTileRegionErrorType@MBXTileRegionErrorTypeCanceled"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/tileregionerrortype\/canceled"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/tileregionerrortype\/canceled"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType\/canceled"},"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionErrorType":{"role":"symbol","navigatorTitle":[{"text":"TileRegionErrorType","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TileRegionErrorType","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/tileregionerrortype","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType","title":"TileRegionErrorType","kind":"symbol","abstract":[{"type":"text","text":"Describes the reason for a tile region download request failure."}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"kind":"symbol","url":"\/documentation\/mapboxcommon","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","title":"MapboxCommon","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","url":"\/documentation\/overview","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"role":"collection","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionErrorType/canceled":{"abstract":[{"type":"text","text":"The operation was canceled."}],"title":"TileRegionErrorType.canceled","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"canceled"}],"type":"topic","url":"\/documentation\/mapboxcommon\/tileregionerrortype\/canceled","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBXTileRegionErrorTypeCanceled"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType\/canceled"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"MBXTileRegionErrorTypeCanceled","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"MBXTileRegionErrorTypeCanceled"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"MBXTileRegionErrorTypeCanceled","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionErrorType\/title","op":"replace","value":"MBXTileRegionErrorType"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionErrorType\/fragments","value":[{"text":"MBXTileRegionErrorType","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MBXTileRegionErrorType"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionErrorType\/navigatorTitle"},{"value":"MBXTileRegionErrorTypeCanceled","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionErrorType~1canceled\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBXTileRegionErrorTypeCanceled"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionErrorType~1canceled\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}