{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapCenterAltitudeMode"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapCenterAltitudeMode\/sea"},"variants":[{"paths":["\/documentation\/mapboxmaps\/mapcenteraltitudemode\/sea"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/mapcenteraltitudemode\/sea"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Center altitude should disregard the underlying terrain elevation","type":"text"}],"metadata":{"navigatorTitle":[{"text":"MBMMapCenterAltitudeModeSea","kind":"identifier"}],"modules":[{"name":"MapboxMaps"}],"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sea"}],"role":"symbol","roleHeading":"Case","title":"MapCenterAltitudeMode.sea","externalID":"c:@E@MBMMapCenterAltitudeMode@MBMMapCenterAltitudeModeSea"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"sea","kind":"identifier"}],"languages":["swift"]}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"url":"\/documentation\/mapboxmaps\/mapboxmap-apis","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","abstract":[],"title":"MapboxMap","kind":"article","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapCenterAltitudeMode":{"role":"symbol","url":"\/documentation\/mapboxmaps\/mapcenteraltitudemode","title":"MapCenterAltitudeMode","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapCenterAltitudeMode"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapCenterAltitudeMode","abstract":[{"type":"text","text":"Defines how the map center point should react to terrain elevation changes."}],"navigatorTitle":[{"text":"MapCenterAltitudeMode","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapCenterAltitudeMode/sea":{"navigatorTitle":[{"kind":"identifier","text":"MBMMapCenterAltitudeModeSea"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"sea","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"MapCenterAltitudeMode.sea","type":"topic","url":"\/documentation\/mapboxmaps\/mapcenteraltitudemode\/sea","abstract":[{"text":"Center altitude should disregard the underlying terrain elevation","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapCenterAltitudeMode\/sea"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"url":"\/documentation\/mapboxmaps","title":"MapboxMaps","type":"topic","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"MBMMapCenterAltitudeModeSea"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"MBMMapCenterAltitudeModeSea","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"MBMMapCenterAltitudeModeSea","kind":"identifier"}]}]},"op":"replace"},{"op":"replace","value":"MBMMapCenterAltitudeMode","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapCenterAltitudeMode\/title"},{"value":[{"kind":"identifier","text":"MBMMapCenterAltitudeMode"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapCenterAltitudeMode\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapCenterAltitudeMode\/navigatorTitle","value":[{"kind":"identifier","text":"MBMMapCenterAltitudeMode"}],"op":"replace"},{"value":"MBMMapCenterAltitudeModeSea","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapCenterAltitudeMode~1sea\/title"},{"value":[{"text":"MBMMapCenterAltitudeModeSea","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapCenterAltitudeMode~1sea\/fragments"}]}]}