{"variants":[{"paths":["\/documentation\/mapboxcommon\/tileregionloadprogress\/completedresourcesize"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxcommon\/tileregionloadprogress\/completedresourcesize"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgress\/completedResourceSize"},"sections":[],"metadata":{"title":"completedResourceSize","roleHeading":"Instance Property","role":"symbol","externalID":"c:objc(cs)MBXTileRegionLoadProgress(py)completedResourceSize","symbolKind":"property","modules":[{"name":"MapboxCommon"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"completedResourceSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt64","preciseIdentifier":"s:s6UInt64V","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"completedResourceSize"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgress"]]},"abstract":[{"type":"text","text":"The cumulative size, in bytes, of all resources (inclusive of tiles) that"},{"type":"text","text":" "},{"type":"text","text":"are ready for offline access."}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"completedResourceSize","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s6UInt64V","text":"UInt64","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadProgress":{"url":"\/documentation\/mapboxcommon\/tileregionloadprogress","abstract":[{"text":"A tile region’s load progress includes counts","type":"text"},{"text":" ","type":"text"},{"text":"of the number of resources that have completed downloading","type":"text"},{"text":" ","type":"text"},{"text":"and the total number of resources that are required.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileRegionLoadProgress","kind":"identifier"}],"role":"symbol","title":"TileRegionLoadProgress","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgress","kind":"symbol","type":"topic","navigatorTitle":[{"text":"TileRegionLoadProgress","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","url":"\/documentation\/mapboxmaps","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"abstract":[],"kind":"article","type":"topic","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","title":"TileStore APIs","url":"\/documentation\/mapboxmaps\/tilestore-apis"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"title":"MapboxMaps Documentation","type":"topic","kind":"article","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadProgress/completedResourceSize":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"completedResourceSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt64","preciseIdentifier":"s:s6UInt64V"}],"navigatorTitle":[{"kind":"identifier","text":"completedResourceSize"}],"abstract":[{"text":"The cumulative size, in bytes, of all resources (inclusive of tiles) that","type":"text"},{"text":" ","type":"text"},{"text":"are ready for offline access.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgress\/completedResourceSize","title":"completedResourceSize","url":"\/documentation\/mapboxcommon\/tileregionloadprogress\/completedresourcesize","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"completedResourceSize"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"completedResourceSize","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"uint64_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@uint64_t"},{"text":" ","kind":"text"},{"text":"completedResourceSize","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgress\/title","op":"replace","value":"MBXTileRegionLoadProgress"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgress\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXTileRegionLoadProgress"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgress\/navigatorTitle","value":[{"kind":"identifier","text":"MBXTileRegionLoadProgress"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgress~1completedResourceSize\/title","value":"completedResourceSize","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgress~1completedResourceSize\/fragments","value":[{"kind":"identifier","text":"completedResourceSize"}],"op":"replace"}]}]}