{"abstract":[{"text":"The geometry that defines the boundary of the offline region","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/mbmofflineregiongeometrydefinition\/geometry"]}],"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMOfflineRegionGeometryDefinition\/geometry"},"metadata":{"modules":[{"name":"MapboxMaps"}],"roleHeading":"Instance Property","fragments":[{"text":"geometry","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"geometry"}],"symbolKind":"property","role":"symbol","title":"geometry","externalID":"c:objc(cs)MBMOfflineRegionGeometryDefinition(py)geometry"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)MBXGeometry","kind":"typeIdentifier","text":"MBXGeometry","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry"},{"kind":"text","text":" * "},{"text":"geometry","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionGeometryDefinition"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/mapboxmaps","title":"MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionGeometryDefinition":{"abstract":[{"type":"text","text":"An offline region definition is a geographic region defined by a style URL,"},{"type":"text","text":" "},{"type":"text","text":"a geometry, zoom range, and device pixel ratio. Both "},{"code":"minZoom","type":"codeVoice"},{"type":"text","text":" and "},{"type":"codeVoice","code":"maxZoom"},{"text":" must be ≥ 0,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"and "},{"code":"maxZoom","type":"codeVoice"},{"text":" must be ≥ ","type":"text"},{"type":"codeVoice","code":"minZoom"},{"text":". The ","type":"text"},{"code":"maxZoom","type":"codeVoice"},{"type":"text","text":" may be ∞, in which case for each tile source,"},{"text":" ","type":"text"},{"type":"text","text":"the region will include tiles from "},{"code":"minZoom","type":"codeVoice"},{"text":" up to the maximum zoom level provided by that source.","type":"text"},{"type":"text","text":" "},{"text":"The ","type":"text"},{"type":"codeVoice","code":"pixelRatio"},{"type":"text","text":" must be ≥ 0 and should typically be 1.0 or 2.0."}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OfflineRegionGeometryDefinition","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"OfflineRegionGeometryDefinition"}],"title":"OfflineRegionGeometryDefinition","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionGeometryDefinition","type":"topic","deprecated":true,"url":"\/documentation\/mapboxmaps\/offlineregiongeometrydefinition"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Offline":{"role":"collectionGroup","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","title":"Offline Support","url":"\/documentation\/mapboxmaps\/offline","type":"topic","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMaps":{"title":"Core Maps API","kind":"article","type":"topic","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/coremaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","abstract":[{"type":"text","text":"Maps rendering SDK also known as GL-Native"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","abstract":[],"kind":"article","role":"collection","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Geometry":{"role":"symbol","url":"\/documentation\/mapboxcommon\/geometry","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Geometry"}],"kind":"symbol","navigatorTitle":[{"text":"Geometry","kind":"identifier"}],"type":"topic","title":"Geometry","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMOfflineRegionGeometryDefinition/geometry":{"url":"\/documentation\/mapboxmaps\/mbmofflineregiongeometrydefinition\/geometry","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMOfflineRegionGeometryDefinition\/geometry","fragments":[{"text":"geometry","kind":"identifier"}],"abstract":[{"type":"text","text":"The geometry that defines the boundary of the offline region"}],"kind":"symbol","type":"topic","role":"symbol","title":"geometry"}},"variantOverrides":[{"patch":[{"op":"replace","value":"MBMOfflineRegionGeometryDefinition","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionGeometryDefinition\/title"},{"value":[{"text":"MBMOfflineRegionGeometryDefinition","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionGeometryDefinition\/fragments","op":"replace"},{"value":[{"text":"MBMOfflineRegionGeometryDefinition","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionGeometryDefinition\/navigatorTitle"},{"op":"replace","value":"MBXGeometry","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry\/title"},{"op":"replace","value":[{"text":"MBXGeometry","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry\/fragments"},{"value":[{"kind":"identifier","text":"MBXGeometry"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}