{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LoggingLevel"]]},"abstract":[{"type":"text","text":"A log message providing information when a significant error occurred."}],"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"error","kind":"identifier"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LoggingLevel\/error","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@E@MBXLoggingLevel@MBXLoggingLevelError","title":"LoggingLevel.error","navigatorTitle":[{"kind":"identifier","text":"MBXLoggingLevelError"}],"modules":[{"name":"MapboxCommon"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"}],"symbolKind":"case","role":"symbol","roleHeading":"Case"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/logginglevel\/error"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/logginglevel\/error"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","abstract":[],"url":"\/documentation\/overview","role":"collection","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Performance":{"title":"Performance and investigations","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","url":"\/documentation\/mapboxmaps\/performance","kind":"article","type":"topic","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LoggingLevel/error":{"title":"LoggingLevel.error","navigatorTitle":[{"kind":"identifier","text":"MBXLoggingLevelError"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LoggingLevel\/error","kind":"symbol","abstract":[{"type":"text","text":"A log message providing information when a significant error occurred."}],"url":"\/documentation\/mapboxcommon\/logginglevel\/error","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LoggingLevel":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LoggingLevel","title":"LoggingLevel","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LoggingLevel"}],"abstract":[{"text":"State level of a log message.","type":"text"}],"navigatorTitle":[{"text":"LoggingLevel","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxcommon\/logginglevel"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"MBXLoggingLevelError"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MBXLoggingLevelError","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"MBXLoggingLevelError","kind":"identifier"}],"languages":["occ"]}]}},{"value":"MBXLoggingLevelError","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LoggingLevel~1error\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LoggingLevel~1error\/fragments","value":[{"kind":"identifier","text":"MBXLoggingLevelError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LoggingLevel\/title","value":"MBXLoggingLevel"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LoggingLevel\/fragments","value":[{"text":"MBXLoggingLevel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LoggingLevel\/navigatorTitle","value":[{"kind":"identifier","text":"MBXLoggingLevel"}],"op":"replace"}]}]}