{"sections":[],"metadata":{"externalID":"s:10MapboxMaps20CustomGeometrySourceV2id7options32maxOverscaleFactorForParentTilesACSS_So09MBMCustomdE7OptionsCs5UInt8VSgtcfc","title":"init(id:options:maxOverscaleFactorForParentTiles:)","role":"symbol","symbolKind":"init","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MBMCustomGeometrySourceOptions","kind":"typeIdentifier","text":"CustomGeometrySourceOptions"},{"kind":"text","text":", "},{"kind":"externalParam","text":"maxOverscaleFactorForParentTiles"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5UInt8V","kind":"typeIdentifier","text":"UInt8"},{"kind":"text","text":"?)"}],"modules":[{"name":"MapboxMaps"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySource"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/customgeometrysource\/init(id:options:maxoverscalefactorforparenttiles:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySource\/init(id:options:maxOverscaleFactorForParentTiles:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"id","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions","text":"CustomGeometrySourceOptions","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMCustomGeometrySourceOptions"},{"text":", ","kind":"text"},{"text":"maxOverscaleFactorForParentTiles","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V","text":"UInt8"},{"kind":"text","text":"? = nil)"}],"languages":["swift"]}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomGeometrySourceOptions":{"url":"\/documentation\/mapboxmaps\/customgeometrysourceoptions","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomGeometrySourceOptions"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions","navigatorTitle":[{"kind":"identifier","text":"CustomGeometrySourceOptions"}],"title":"CustomGeometrySourceOptions","abstract":[{"type":"text","text":"Options for custom geometry source."}],"type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Sources":{"abstract":[],"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources","type":"topic","title":"Sources","url":"\/documentation\/mapboxmaps\/sources","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","abstract":[],"url":"\/documentation\/overview","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomGeometrySource/init(id:options:maxOverscaleFactorForParentTiles:)":{"url":"\/documentation\/mapboxmaps\/customgeometrysource\/init(id:options:maxoverscalefactorforparenttiles:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CustomGeometrySourceOptions","preciseIdentifier":"c:objc(cs)MBMCustomGeometrySourceOptions"},{"kind":"text","text":", "},{"kind":"externalParam","text":"maxOverscaleFactorForParentTiles"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt8","preciseIdentifier":"s:s5UInt8V"},{"kind":"text","text":"?)"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySource\/init(id:options:maxOverscaleFactorForParentTiles:)","abstract":[],"type":"topic","kind":"symbol","role":"symbol","title":"init(id:options:maxOverscaleFactorForParentTiles:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"url":"\/documentation\/mapboxmaps","role":"collection","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomGeometrySource":{"abstract":[{"type":"text","text":"Describes a Custom Geometry Source to be used in the style"}],"kind":"symbol","title":"CustomGeometrySource","role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySource","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomGeometrySource"}],"navigatorTitle":[{"kind":"identifier","text":"CustomGeometrySource"}],"url":"\/documentation\/mapboxmaps\/customgeometrysource"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions\/title","value":"MBMCustomGeometrySourceOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions\/fragments","value":[{"text":"MBMCustomGeometrySourceOptions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions\/navigatorTitle","value":[{"kind":"identifier","text":"MBMCustomGeometrySourceOptions"}]}]}]}