{"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorType\/style","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","abstract":[{"text":"The style resource failed to load.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorType"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"style","kind":"identifier"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/maploadingerrortype\/style"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/maploadingerrortype\/style"]}],"metadata":{"modules":[{"name":"MapboxMaps"}],"role":"symbol","externalID":"c:@E@MBMMapLoadingErrorType@MBMMapLoadingErrorTypeStyle","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"style","kind":"identifier"}],"title":"MapLoadingErrorType.style","symbolKind":"case","navigatorTitle":[{"text":"MBMMapLoadingErrorTypeStyle","kind":"identifier"}]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoadingErrorType":{"url":"\/documentation\/mapboxmaps\/maploadingerrortype","kind":"symbol","title":"MapLoadingErrorType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapLoadingErrorType"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorType","navigatorTitle":[{"text":"MapLoadingErrorType","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"text":"The enumeration defines map loading errors.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoadingErrorType/style":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorType\/style","abstract":[{"type":"text","text":"The style resource failed to load."}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBMMapLoadingErrorTypeStyle"}],"title":"MapLoadingErrorType.style","url":"\/documentation\/mapboxmaps\/maploadingerrortype\/style","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"style"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","abstract":[],"title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","kind":"article","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","title":"MapboxMaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"role":"collection","url":"\/documentation\/mapboxmaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"url":"\/documentation\/mapboxmaps\/events","type":"topic","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","title":"Map events","abstract":[{"text":"The simplified diagram of the events emitted by the map is displayed below.","type":"text"}],"role":"collectionGroup"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","value":"MBMMapLoadingErrorTypeStyle","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MBMMapLoadingErrorTypeStyle","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"MBMMapLoadingErrorTypeStyle","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"MBMMapLoadingErrorType","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorType\/title"},{"value":[{"text":"MBMMapLoadingErrorType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorType\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorType\/navigatorTitle","value":[{"text":"MBMMapLoadingErrorType","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"MBMMapLoadingErrorTypeStyle","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorType~1style\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorType~1style\/fragments","value":[{"kind":"identifier","text":"MBMMapLoadingErrorTypeStyle"}]}]}]}