{"variants":[{"paths":["\/documentation\/mapboxmaps\/offlineregionstatus\/requiredtilecount"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/offlineregionstatus\/requiredtilecount"]}],"kind":"symbol","abstract":[{"type":"text","text":"The number of tiles that are known to be required for this region."}],"metadata":{"externalID":"c:objc(cs)MBMOfflineRegionStatus(py)requiredTileCount","modules":[{"name":"MapboxMaps"}],"role":"symbol","symbolKind":"property","roleHeading":"Instance Property","title":"requiredTileCount","navigatorTitle":[{"text":"requiredTileCount","kind":"identifier"}],"platforms":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requiredTileCount"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt64","preciseIdentifier":"s:s6UInt64V"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiredTileCount"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt64","preciseIdentifier":"s:s6UInt64V"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionStatus\/requiredTileCount","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionStatus"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionStatus":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"OfflineRegionStatus","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"OfflineRegionStatus"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionStatus","url":"\/documentation\/mapboxmaps\/offlineregionstatus","role":"symbol","abstract":[{"type":"text","text":"A region’s status includes its active\/inactive state as well as counts"},{"text":" ","type":"text"},{"text":"of the number of resources that have completed downloading, their total","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"size in bytes, and the total number of resources that are required."}],"deprecated":true,"title":"OfflineRegionStatus","kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionStatus/requiredTileCount":{"navigatorTitle":[{"kind":"identifier","text":"requiredTileCount"}],"role":"symbol","type":"topic","deprecated":true,"kind":"symbol","url":"\/documentation\/mapboxmaps\/offlineregionstatus\/requiredtilecount","title":"requiredTileCount","abstract":[{"type":"text","text":"The number of tiles that are known to be required for this region."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionStatus\/requiredTileCount","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requiredTileCount","kind":"identifier"},{"kind":"text","text":": "},{"text":"UInt64","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","kind":"article","abstract":[],"url":"\/documentation\/overview","type":"topic","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Offline":{"kind":"article","url":"\/documentation\/mapboxmaps\/offline","abstract":[],"role":"collectionGroup","type":"topic","title":"Offline Support","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMaps":{"kind":"article","url":"\/documentation\/mapboxmaps\/coremaps","abstract":[{"type":"text","text":"Maps rendering SDK also known as GL-Native"}],"role":"collectionGroup","type":"topic","title":"Core Maps API","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"role":"collection","url":"\/documentation\/mapboxmaps","title":"MapboxMaps","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"requiredTileCount"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"requiredTileCount"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"uint64_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@uint64_t"},{"kind":"text","text":" "},{"text":"requiredTileCount","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"MBMOfflineRegionStatus","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionStatus\/title"},{"op":"replace","value":[{"text":"MBMOfflineRegionStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionStatus\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionStatus\/navigatorTitle","value":[{"kind":"identifier","text":"MBMOfflineRegionStatus"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionStatus~1requiredTileCount\/title","value":"requiredTileCount","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionStatus~1requiredTileCount\/fragments","value":[{"text":"requiredTileCount","kind":"identifier"}],"op":"replace"}]}]}