{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/IntervalSettings"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/intervalsettings\/isequal(to:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/intervalsettings\/isequal(to:)"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"other","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"IntervalSettings","preciseIdentifier":"c:objc(cs)MBXIntervalSettings","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/IntervalSettings"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/IntervalSettings\/isEqual(to:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"modules":[{"name":"MapboxCommon"}],"title":"isEqual(to:)","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"IntervalSettings","preciseIdentifier":"c:objc(cs)MBXIntervalSettings","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"isEqualToIntervalSettings:","kind":"identifier"}],"role":"symbol","externalID":"c:objc(cs)MBXIntervalSettings(im)isEqualToIntervalSettings:"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/IntervalSettings":{"title":"IntervalSettings","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntervalSettings"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/IntervalSettings","url":"\/documentation\/mapboxcommon\/intervalsettings","abstract":[{"text":"The interval for active location updates","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"IntervalSettings"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/IntervalSettings/isEqual(to:)":{"type":"topic","title":"isEqual(to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXIntervalSettings","text":"IntervalSettings"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/IntervalSettings\/isEqual(to:)","navigatorTitle":[{"kind":"identifier","text":"isEqualToIntervalSettings:"}],"abstract":[],"role":"symbol","url":"\/documentation\/mapboxcommon\/intervalsettings\/isequal(to:)"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article","type":"topic","title":"MapboxMaps Documentation","abstract":[],"url":"\/documentation\/overview","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"url":"\/documentation\/mapboxmaps","title":"MapboxMaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Location-APIs":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","role":"collectionGroup","abstract":[],"kind":"article","title":"Location","url":"\/documentation\/mapboxmaps\/location-apis"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"isEqualToIntervalSettings:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqualToIntervalSettings:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"isEqualToIntervalSettings:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MBXIntervalSettings","preciseIdentifier":"c:objc(cs)MBXIntervalSettings","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/IntervalSettings","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"other","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MBXIntervalSettings","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1IntervalSettings\/title"},{"value":[{"text":"MBXIntervalSettings","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1IntervalSettings\/fragments"},{"value":[{"text":"MBXIntervalSettings","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1IntervalSettings\/navigatorTitle"},{"value":"isEqualToIntervalSettings:","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1IntervalSettings~1isEqual(to:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"isEqualToIntervalSettings:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1IntervalSettings~1isEqual(to:)\/fragments"}]}]}