{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionErrorType\/notFound"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notFound","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/mapboxmaps\/offlineregionerrortype\/notfound"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/offlineregionerrortype\/notfound"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"The resource is not found.","type":"text"}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionErrorType"]]},"sections":[],"metadata":{"title":"OfflineRegionErrorType.notFound","platforms":[],"externalID":"c:@E@MBMOfflineRegionErrorType@MBMOfflineRegionErrorTypeNotFound","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notFound","kind":"identifier"}],"symbolKind":"case","navigatorTitle":[{"text":"MBMOfflineRegionErrorTypeNotFound","kind":"identifier"}],"roleHeading":"Case","modules":[{"name":"MapboxMaps"}],"role":"symbol"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionErrorType/notFound":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/offlineregionerrortype\/notfound","navigatorTitle":[{"kind":"identifier","text":"MBMOfflineRegionErrorTypeNotFound"}],"abstract":[{"type":"text","text":"The resource is not found."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notFound"}],"deprecated":true,"title":"OfflineRegionErrorType.notFound","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionErrorType\/notFound","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"title":"MapboxMaps Documentation","type":"topic","kind":"article","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","abstract":[{"type":"text","text":"Maps rendering SDK also known as GL-Native"}],"type":"topic","title":"Core Maps API","role":"collectionGroup","kind":"article","url":"\/documentation\/mapboxmaps\/coremaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Offline":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","abstract":[],"type":"topic","title":"Offline Support","role":"collectionGroup","kind":"article","url":"\/documentation\/mapboxmaps\/offline"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionErrorType":{"deprecated":true,"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OfflineRegionErrorType"}],"abstract":[{"type":"text","text":"Describes the reason for an offline request response error."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionErrorType","title":"OfflineRegionErrorType","kind":"symbol","url":"\/documentation\/mapboxmaps\/offlineregionerrortype","navigatorTitle":[{"kind":"identifier","text":"OfflineRegionErrorType"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","url":"\/documentation\/mapboxmaps","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"MBMOfflineRegionErrorTypeNotFound","path":"\/metadata\/title","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"MBMOfflineRegionErrorTypeNotFound","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"MBMOfflineRegionErrorTypeNotFound"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MBMOfflineRegionErrorTypeNotFound","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionErrorType~1notFound\/title"},{"value":[{"kind":"identifier","text":"MBMOfflineRegionErrorTypeNotFound"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionErrorType~1notFound\/fragments"},{"value":"MBMOfflineRegionErrorType","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionErrorType\/title"},{"value":[{"kind":"identifier","text":"MBMOfflineRegionErrorType"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionErrorType\/fragments"},{"value":[{"text":"MBMOfflineRegionErrorType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionErrorType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}