{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapEventType\/styleLoaded"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapEventType"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"symbolKind":"property","modules":[{"name":"MapboxMaps"}],"externalID":"s:10MapboxMaps12MapEventTypeV11styleLoadedACySo08MBMStyleG0CGvpZ","roleHeading":"Type Property","role":"symbol","platforms":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"styleLoaded"},{"kind":"text","text":": "},{"text":"MapEventType","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps12MapEventTypeV"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMStyleLoaded","text":"StyleLoaded"},{"text":">","kind":"text"}],"title":"styleLoaded"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"styleLoaded"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10MapboxMaps12MapEventTypeV","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapEventType","kind":"typeIdentifier","text":"MapEventType"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleLoaded","text":"StyleLoaded","preciseIdentifier":"c:objc(cs)MBMStyleLoaded"},{"kind":"text","text":"> { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/mapeventtype\/styleloaded"]}],"abstract":[{"type":"text","text":"The requested style has been fully loaded."}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapEventType/styleLoaded":{"deprecated":true,"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The requested style has been fully loaded."}],"url":"\/documentation\/mapboxmaps\/mapeventtype\/styleloaded","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapEventType\/styleLoaded","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"styleLoaded","kind":"identifier"},{"kind":"text","text":": "},{"text":"MapEventType","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps12MapEventTypeV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"StyleLoaded","preciseIdentifier":"c:objc(cs)MBMStyleLoaded"},{"kind":"text","text":">"}],"title":"styleLoaded"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","url":"\/documentation\/mapboxmaps","role":"collection","title":"MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleLoaded":{"abstract":[{"text":"The requested style has been fully loaded, including specified sprite, and sources’ metadata.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleLoaded","type":"topic","role":"symbol","title":"StyleLoaded","url":"\/documentation\/mapboxmaps\/styleloaded","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StyleLoaded"}],"kind":"symbol","navigatorTitle":[{"text":"StyleLoaded","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"title":"Map events","role":"collectionGroup","abstract":[{"type":"text","text":"The simplified diagram of the events emitted by the map is displayed below."}],"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","type":"topic","url":"\/documentation\/mapboxmaps\/events"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapEventType":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapEventType","role":"symbol","title":"MapEventType","type":"topic","kind":"symbol","abstract":[{"text":"A shim that makes it possible to subscribe to ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","isActive":true},{"type":"text","text":" and "},{"isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter","type":"reference"},{"type":"text","text":" events via the old "},{"type":"codeVoice","code":"onNext"},{"text":" and  ","type":"text"},{"type":"codeVoice","code":"onEvery"},{"type":"text","text":" methods."},{"text":" ","type":"text"},{"text":"It is here to simplify migration from v10 to v11, but will be removed in v12.","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"MapEventType","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/mapeventtype","navigatorTitle":[{"text":"MapEventType","kind":"identifier"}],"deprecated":true},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","abstract":[],"kind":"article","url":"\/documentation\/overview","type":"topic","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Snapshotter":{"title":"Snapshotter","kind":"symbol","url":"\/documentation\/mapboxmaps\/snapshotter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Snapshotter"}],"abstract":[{"text":"A utility class for capturing styled map snapshots.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Snapshotter"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap":{"kind":"symbol","role":"symbol","title":"MapboxMap","url":"\/documentation\/mapboxmaps\/mapboxmap","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapboxMap"}],"navigatorTitle":[{"text":"MapboxMap","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Provides access to the map model, including the camera, style, observable map events,"},{"text":" ","type":"text"},{"text":"and querying rendered features.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoaded\/title","value":"MBMStyleLoaded"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoaded\/fragments","value":[{"kind":"identifier","text":"MBMStyleLoaded"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoaded\/navigatorTitle","value":[{"kind":"identifier","text":"MBMStyleLoaded"}]}]}]}