{"metadata":{"symbolKind":"method","modules":[{"name":"MapboxCommon"}],"title":"extractLocations()","role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"extractLocations"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"extractLocations"},{"text":"() -> ","kind":"text"},{"text":"NSValue","preciseIdentifier":"c:objc(cs)NSValue","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"externalID":"c:objc(cs)MBXGeometry(im)extractLocations"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry\/extractLocations()"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"extractLocations","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"NSValue","preciseIdentifier":"c:objc(cs)NSValue","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/geometry\/extractlocations()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/geometry\/extractlocations()"]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"kind":"symbol","url":"\/documentation\/mapboxcommon","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","title":"MapboxCommon","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Geometry":{"kind":"symbol","url":"\/documentation\/mapboxcommon\/geometry","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Geometry","kind":"identifier"}],"navigatorTitle":[{"text":"Geometry","kind":"identifier"}],"title":"Geometry","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Geometry/extractLocations()":{"title":"extractLocations()","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"extractLocations","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"NSValue","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSValue"},{"text":"?","kind":"text"}],"kind":"symbol","abstract":[],"url":"\/documentation\/mapboxcommon\/geometry\/extractlocations()","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry\/extractLocations()","navigatorTitle":[{"kind":"identifier","text":"extractLocations"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","url":"\/documentation\/overview","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"role":"collection","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"extractLocations","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"extractLocations"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"NSValue","preciseIdentifier":"c:objc(cs)NSValue"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"extractLocations"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry\/title","value":"MBXGeometry"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXGeometry"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry\/navigatorTitle","value":[{"kind":"identifier","text":"MBXGeometry"}]},{"op":"replace","value":"extractLocations","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry~1extractLocations()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry~1extractLocations()\/fragments","value":[{"kind":"text","text":"- "},{"text":"extractLocations","kind":"identifier"}]}]}]}