{"abstract":[{"type":"text","text":"Set the orientation of the camera represented as a unit quaternion [x, y, z, w]."},{"type":"text","text":" "},{"type":"text","text":"The default pose of the camera is such that the forward vector is looking up the -Z axis and"},{"type":"text","text":" "},{"type":"text","text":"the up vector is aligned with north orientation of the map:"},{"type":"text","text":" "},{"type":"text","text":"forward: [0, 0, -1]"},{"type":"text","text":" "},{"type":"text","text":"up:      [0, -1, 0]"},{"type":"text","text":" "},{"type":"text","text":"right    [1, 0, 0]"}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setOrientationForOrientation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"orientation","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMVec4","text":"Vec4","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Vec4"},{"text":"?)","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The orientation to be set."}]}],"name":"orientation"}],"kind":"parameters"},{"kind":"content","content":[{"text":"Discussion","type":"heading","anchor":"discussion","level":2},{"type":"codeListing","syntax":null,"code":[" With the w value as the real part of the complex number"]},{"type":"paragraph","inlineContent":[{"text":"Orientation can be set freely but certain constraints still apply","type":"text"},{"text":" ","type":"text"},{"text":"- Orientation must be representable with only pitch and bearing.","type":"text"},{"text":" ","type":"text"},{"text":"- Pitch has an upper limit","type":"text"}]}]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions\/setOrientationForOrientation(_:)","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","metadata":{"role":"symbol","symbolKind":"method","modules":[{"name":"MapboxMaps"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setOrientationForOrientation"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMVec4","text":"Vec4"},{"kind":"text","text":"?)"}],"roleHeading":"Instance Method","title":"setOrientationForOrientation(_:)","externalID":"c:objc(cs)MBMFreeCameraOptions(im)setOrientationForOrientation:","navigatorTitle":[{"text":"setOrientationForOrientation:","kind":"identifier"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/mapboxmaps\/freecameraoptions\/setorientationfororientation(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/freecameraoptions\/setorientationfororientation(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FreeCameraOptions/setOrientationForOrientation(_:)":{"abstract":[{"type":"text","text":"Set the orientation of the camera represented as a unit quaternion [x, y, z, w]."},{"type":"text","text":" "},{"type":"text","text":"The default pose of the camera is such that the forward vector is looking up the -Z axis and"},{"type":"text","text":" "},{"type":"text","text":"the up vector is aligned with north orientation of the map:"},{"type":"text","text":" "},{"type":"text","text":"forward: [0, 0, -1]"},{"type":"text","text":" "},{"type":"text","text":"up:      [0, -1, 0]"},{"type":"text","text":" "},{"type":"text","text":"right    [1, 0, 0]"}],"url":"\/documentation\/mapboxmaps\/freecameraoptions\/setorientationfororientation(_:)","title":"setOrientationForOrientation(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setOrientationForOrientation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Vec4","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMVec4"},{"text":"?)","kind":"text"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"setOrientationForOrientation:","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions\/setOrientationForOrientation(_:)","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FreeCameraOptions":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FreeCameraOptions","kind":"identifier"}],"abstract":[{"type":"text","text":"Various options for accessing physical properties of the underlying camera entity."},{"type":"text","text":" "},{"type":"text","text":"A direct access to these properties allows more flexible and precise controlling"},{"type":"text","text":" "},{"type":"text","text":"of the camera while also being fully compatible and interchangeable with CameraOptions."},{"type":"text","text":" "},{"type":"text","text":"All fields are optional."}],"title":"FreeCameraOptions","type":"topic","navigatorTitle":[{"text":"FreeCameraOptions","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions","role":"symbol","url":"\/documentation\/mapboxmaps\/freecameraoptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"type":"topic","url":"\/documentation\/mapboxmaps\/mapboxmap-apis","abstract":[],"kind":"article","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","title":"MapboxMap"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Vec4":{"abstract":[{"type":"text","text":"4 component vector."}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Vec4","url":"\/documentation\/mapboxmaps\/vec4","type":"topic","title":"Vec4","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Vec4","kind":"identifier"}],"navigatorTitle":[{"text":"Vec4","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","role":"collection","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","type":"topic","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","role":"collection","type":"topic","abstract":[],"title":"MapboxMaps Documentation","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"setOrientationForOrientation:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setOrientationForOrientation:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"setOrientationForOrientation:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Vec4","preciseIdentifier":"c:objc(cs)MBMVec4","text":"MBMVec4","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"orientation","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The orientation to be set."}],"type":"paragraph"}],"name":"orientation"}],"kind":"parameters"},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions~1setOrientationForOrientation(_:)\/title","value":"setOrientationForOrientation:","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions~1setOrientationForOrientation(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setOrientationForOrientation:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions\/title","value":"MBMFreeCameraOptions","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions\/fragments","value":[{"kind":"identifier","text":"MBMFreeCameraOptions"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions\/navigatorTitle","value":[{"kind":"identifier","text":"MBMFreeCameraOptions"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Vec4\/title","value":"MBMVec4","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Vec4\/fragments","value":[{"text":"MBMVec4","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Vec4\/navigatorTitle","value":[{"kind":"identifier","text":"MBMVec4"}],"op":"replace"}]}]}