{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"metadata","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"metadata"}],"role":"symbol","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"MBMSourceDataLoadedTypeMetadata"}],"title":"SourceDataLoadedType.metadata","externalID":"c:@E@MBMSourceDataLoadedType@MBMSourceDataLoadedTypeMetadata","symbolKind":"case","modules":[{"name":"MapboxMaps"}]},"variants":[{"paths":["\/documentation\/mapboxmaps\/sourcedataloadedtype\/metadata"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/sourcedataloadedtype\/metadata"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedType\/metadata","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedType"]]},"abstract":[{"text":"The metadata of a source. For example, TileJSON for a vector source or a","type":"text"},{"type":"text","text":" "},{"type":"text","text":"GeoJSON document for a GeoJSON source."}],"kind":"symbol","references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","type":"topic","title":"MapboxMaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","role":"collection","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceDataLoadedType/metadata":{"kind":"symbol","abstract":[{"type":"text","text":"The metadata of a source. For example, TileJSON for a vector source or a"},{"type":"text","text":" "},{"text":"GeoJSON document for a GeoJSON source.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedType\/metadata","url":"\/documentation\/mapboxmaps\/sourcedataloadedtype\/metadata","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"metadata"}],"navigatorTitle":[{"text":"MBMSourceDataLoadedTypeMetadata","kind":"identifier"}],"title":"SourceDataLoadedType.metadata","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceDataLoadedType":{"type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SourceDataLoadedType","kind":"identifier"}],"abstract":[{"type":"text","text":"The enumeration defines the type of loaded source data."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedType","kind":"symbol","title":"SourceDataLoadedType","navigatorTitle":[{"kind":"identifier","text":"SourceDataLoadedType"}],"url":"\/documentation\/mapboxmaps\/sourcedataloadedtype"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"title":"Map events","abstract":[{"text":"The simplified diagram of the events emitted by the map is displayed below.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","url":"\/documentation\/mapboxmaps\/events","kind":"article","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","type":"topic","title":"MapboxMaps Documentation","url":"\/documentation\/overview","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","value":"MBMSourceDataLoadedTypeMetadata","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"kind":"identifier","text":"MBMSourceDataLoadedTypeMetadata"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"MBMSourceDataLoadedTypeMetadata","kind":"identifier"}],"platforms":["iOS"]}]}},{"value":"MBMSourceDataLoadedTypeMetadata","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedType~1metadata\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedType~1metadata\/fragments","value":[{"kind":"identifier","text":"MBMSourceDataLoadedTypeMetadata"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedType\/title","value":"MBMSourceDataLoadedType","op":"replace"},{"value":[{"text":"MBMSourceDataLoadedType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedType\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBMSourceDataLoadedType"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedType\/navigatorTitle"}]}]}