{"sections":[],"metadata":{"symbolKind":"op","roleHeading":"Operator","extendedModule":"Swift","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"!="},{"text":" ","kind":"text"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::c:@E@MBMViewAnnotationAnchor","title":"!=(_:_:)","modules":[{"relatedModules":["Swift"],"name":"MapboxMaps"}]},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/View-Annotations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchor\/Equatable-Implementations"]]},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchor\/!=(_:_:)"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"Equatable.!=(_:_:)"},{"text":".","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"!=","kind":"identifier"},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"internalParam","text":"lhs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"internalParam","text":"rhs"},{"kind":"text","text":": "},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/mapboxmaps\/viewannotationanchor\/!=(_:_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationAnchor/!=(_:_:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchor\/!=(_:_:)","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/viewannotationanchor\/!=(_:_:)","title":"!=(_:_:)","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"!="},{"text":" ","kind":"text"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationAnchor/Equatable-Implementations":{"role":"collectionGroup","type":"topic","url":"\/documentation\/mapboxmaps\/viewannotationanchor\/equatable-implementations","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchor\/Equatable-Implementations","title":"Equatable Implementations","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/View-Annotations":{"title":"View Annotations","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/View-Annotations","kind":"article","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/view-annotations","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationAnchor":{"type":"topic","navigatorTitle":[{"text":"ViewAnnotationAnchor","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/viewannotationanchor","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ViewAnnotationAnchor"}],"abstract":[{"type":"text","text":"Enum describing how to place view annotation relatively to geometry."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchor","title":"ViewAnnotationAnchor"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","title":"MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"url":"\/documentation\/mapboxmaps","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"title":"MapboxMaps Documentation","role":"collection","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article","url":"\/documentation\/overview"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MBMViewAnnotationAnchor","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchor\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MBMViewAnnotationAnchor"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchor\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchor\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMViewAnnotationAnchor"}]}]}]}