{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/OfflineSwitch\/setMapboxStackConnectedForConnected(_:)"},"metadata":{"modules":[{"name":"MapboxCommon"}],"role":"symbol","title":"setMapboxStackConnectedForConnected(_:)","externalID":"c:objc(cs)MBXOfflineSwitch(im)setMapboxStackConnectedForConnected:","navigatorTitle":[{"text":"setMapboxStackConnectedForConnected:","kind":"identifier"}],"symbolKind":"method","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setMapboxStackConnectedForConnected","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/OfflineSwitch"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setMapboxStackConnectedForConnected","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"connected","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"connected","content":[{"type":"paragraph","inlineContent":[{"text":"Set false to disconnect the Mapbox stack","type":"text"}]}]}]}],"variants":[{"paths":["\/documentation\/mapboxcommon\/offlineswitch\/setmapboxstackconnectedforconnected(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/offlineswitch\/setmapboxstackconnectedforconnected(_:)"]}],"abstract":[{"text":"Connects or disconnects the Mapbox stack. If set to false, current and new HTTP requests will fail","type":"text"},{"text":" ","type":"text"},{"text":"with HttpRequestErrorType#ConnectionError.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/OfflineSwitch":{"role":"symbol","title":"OfflineSwitch","abstract":[{"type":"text","text":"Instance that allows connecting or disconnecting the Mapbox stack to the network."}],"url":"\/documentation\/mapboxcommon\/offlineswitch","navigatorTitle":[{"text":"OfflineSwitch","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/OfflineSwitch","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OfflineSwitch"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","url":"\/documentation\/overview","abstract":[],"type":"topic","role":"collection","title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/OfflineSwitch/setMapboxStackConnectedForConnected(_:)":{"url":"\/documentation\/mapboxcommon\/offlineswitch\/setmapboxstackconnectedforconnected(_:)","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Connects or disconnects the Mapbox stack. If set to false, current and new HTTP requests will fail"},{"type":"text","text":" "},{"type":"text","text":"with HttpRequestErrorType#ConnectionError."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"setMapboxStackConnectedForConnected:"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/OfflineSwitch\/setMapboxStackConnectedForConnected(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setMapboxStackConnectedForConnected"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"setMapboxStackConnectedForConnected(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"type":"topic","role":"collection","title":"MapboxCommon","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","abstract":[],"url":"\/documentation\/mapboxcommon","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"setMapboxStackConnectedForConnected:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setMapboxStackConnectedForConnected:"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"setMapboxStackConnectedForConnected:"},{"kind":"text","text":"("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"connected","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Set false to disconnect the Mapbox stack"}],"type":"paragraph"}],"name":"connected"}],"kind":"parameters"},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1OfflineSwitch\/title","value":"MBXOfflineSwitch","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1OfflineSwitch\/fragments","value":[{"text":"MBXOfflineSwitch","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1OfflineSwitch\/navigatorTitle","value":[{"kind":"identifier","text":"MBXOfflineSwitch"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1OfflineSwitch~1setMapboxStackConnectedForConnected(_:)\/title","value":"setMapboxStackConnectedForConnected:"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1OfflineSwitch~1setMapboxStackConnectedForConnected(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setMapboxStackConnectedForConnected:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}