{"abstract":[{"text":"The source has been added with ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addSource(_:dataId:)","isActive":true,"type":"reference"},{"text":"  or ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addSource(withId:properties:)","isActive":true,"type":"reference"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"The event is emitted synchronously, therefore, it is possible to immediately","type":"text"},{"text":" ","type":"text"},{"text":"read added source’s properties.","type":"text"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/mapboxmap\/onsourceadded"]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap"],["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/MapboxMapProtocol-Implementations"]]},"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSourceAdded"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Signal","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"SourceAdded","preciseIdentifier":"c:objc(cs)MBMSourceAdded"},{"kind":"text","text":">"}],"externalID":"s:10MapboxMaps0A3MapC13onSourceAddedAA6SignalVySo09MBMSourceF0CGvp","modules":[{"name":"MapboxMaps"}],"role":"symbol","extendedModule":"MapboxMaps","symbolKind":"property","roleHeading":"Instance Property","title":"onSourceAdded"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onSourceAdded"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onSourceAdded","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Signal","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Signal","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"text":"<","kind":"text"},{"text":"SourceAdded","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceAdded","preciseIdentifier":"c:objc(cs)MBMSourceAdded"},{"text":"> { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onMapLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onMapLoadingError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleDataLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onCameraChanged","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onMapIdle","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onSourceRemoved","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onSourceDataLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleImageMissing","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleImageRemoveUnused","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onRenderFrameStarted","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onRenderFrameFinished","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onResourceRequest"],"title":"Map events","generated":true,"anchor":"Map-events"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onMapIdle":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onMapIdle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps6SignalV","text":"Signal","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMMapIdle","text":"MapIdle","kind":"typeIdentifier"},{"text":">","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onMapIdle","type":"topic","url":"\/documentation\/mapboxmaps\/mapboxmap\/onmapidle","kind":"symbol","role":"symbol","title":"onMapIdle","abstract":[{"type":"text","text":"The map has entered the idle state. The map is in the idle state when there are no ongoing transitions"},{"type":"text","text":" "},{"type":"text","text":"and the map has rendered all requested non-volatile tiles. The event will not be emitted if animation is in progress (see "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/beginAnimation()","type":"reference","isActive":true},{"type":"text","text":", "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/endAnimation()","type":"reference","isActive":true},{"type":"text","text":")"},{"type":"text","text":" "},{"type":"text","text":"and \/ or gesture is in progress (see "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/beginGesture()","type":"reference","isActive":true},{"type":"text","text":", "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/endGesture()","type":"reference","isActive":true},{"type":"text","text":")."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/addSource(withId:properties:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addSource","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"properties","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]) ","kind":"text"},{"text":"throws","kind":"keyword"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/stylemanager\/addsource(withid:properties:)","abstract":[{"text":"Adds a new style source.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addSource(withId:properties:)","kind":"symbol","title":"addSource(withId:properties:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/removeSource(withId:)":{"kind":"symbol","title":"removeSource(withId:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeSource","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"abstract":[{"text":"Removes an existing style source.","type":"text"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/stylemanager\/removesource(withid:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/removeSource(withId:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/endAnimation()":{"type":"topic","url":"\/documentation\/mapboxmaps\/mapboxmap\/endanimation()","title":"endAnimation()","role":"symbol","abstract":[{"text":"If implementing a custom animation mechanism, call this method when the animation ends.","type":"text"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"endAnimation","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/endAnimation()"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onSourceDataLoaded":{"type":"topic","title":"onSourceDataLoaded","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onSourceDataLoaded","kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/onsourcedataloaded","role":"symbol","abstract":[{"type":"text","text":"A source data has been loaded."},{"type":"text","text":" "},{"type":"text","text":"Event may be emitted synchronously in cases when source’s metadata is available when source is added to the style."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onSourceDataLoaded","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps6SignalV","text":"Signal","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMSourceDataLoaded","text":"SourceDataLoaded","kind":"typeIdentifier"},{"text":">","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapboxMap"}],"type":"topic","kind":"symbol","abstract":[{"text":"Provides access to the map model, including the camera, style, observable map events,","type":"text"},{"text":" ","type":"text"},{"text":"and querying rendered features.","type":"text"}],"title":"MapboxMap","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MapboxMap"}],"url":"\/documentation\/mapboxmaps\/mapboxmap"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onResourceRequest":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onResourceRequest"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Signal","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"ResourceRequest","preciseIdentifier":"c:objc(cs)MBMResourceRequest"},{"kind":"text","text":">"}],"kind":"symbol","abstract":[{"type":"text","text":"The "},{"code":"ResourceRequest","type":"codeVoice"},{"type":"text","text":" event allows client to observe resource requests made by a"},{"type":"text","text":" "},{"type":"text","text":"map or snapshotter."}],"type":"topic","url":"\/documentation\/mapboxmaps\/mapboxmap\/onresourcerequest","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onResourceRequest","title":"onResourceRequest"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onSourceRemoved":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onSourceRemoved","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps6SignalV","text":"Signal","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMSourceRemoved","text":"SourceRemoved","kind":"typeIdentifier"},{"text":">","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onSourceRemoved","type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/onsourceremoved","title":"onSourceRemoved","kind":"symbol","abstract":[{"type":"text","text":"The source has been removed with "},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/removeSource(withId:)","isActive":true},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The event is emitted synchronously, thus, "},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/allSourceIdentifiers","isActive":true},{"type":"text","text":" will be"},{"type":"text","text":" "},{"type":"text","text":"in sync when the observer receives the notification."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Signal":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Signal","kind":"symbol","url":"\/documentation\/mapboxmaps\/signal","type":"topic","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Signal","kind":"identifier"}],"title":"Signal","navigatorTitle":[{"text":"Signal","kind":"identifier"}],"abstract":[{"type":"text","text":"Signal is a typed interface for observing arbitrary values over time."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/MapboxMapProtocol-Implementations":{"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/MapboxMapProtocol-Implementations","url":"\/documentation\/mapboxmaps\/mapboxmap\/mapboxmapprotocol-implementations","kind":"article","type":"topic","title":"MapboxMapProtocol Implementations","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onStyleImageMissing":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleImageMissing","kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/onstyleimagemissing","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onStyleImageMissing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV","text":"Signal"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMStyleImageMissing","text":"StyleImageMissing"},{"kind":"text","text":">"}],"title":"onStyleImageMissing","abstract":[{"text":"A style has a missing image. This event is emitted when the map renders visible tiles and","type":"text"},{"text":" ","type":"text"},{"text":"one of the required images is missing in the sprite sheet. Subscriber has to provide the missing image","type":"text"},{"text":" ","type":"text"},{"text":"by calling ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addImage(_:id:sdf:contentInsets:)","isActive":true,"type":"reference"},{"text":".","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/beginAnimation()":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/beginAnimation()","kind":"symbol","abstract":[{"text":"If implementing a custom animation mechanism, call this method when the animation begins.","type":"text"}],"url":"\/documentation\/mapboxmaps\/mapboxmap\/beginanimation()","role":"symbol","title":"beginAnimation()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"beginAnimation","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/beginGesture()":{"title":"beginGesture()","abstract":[{"type":"text","text":"If implementing a custom gesture, call this method when the gesture begins."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"beginGesture"},{"kind":"text","text":"()"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/beginGesture()","role":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/mapboxmap\/begingesture()"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","kind":"article","role":"collectionGroup","title":"MapboxMap","abstract":[],"url":"\/documentation\/mapboxmaps\/mapboxmap-apis","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceAdded":{"kind":"symbol","abstract":[{"text":"The source has been added with ","type":"text"},{"code":"addStyleSource","type":"codeVoice"},{"text":" method.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceAdded"}],"navigatorTitle":[{"kind":"identifier","text":"SourceAdded"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceAdded","type":"topic","url":"\/documentation\/mapboxmaps\/sourceadded","role":"symbol","title":"SourceAdded"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","abstract":[],"url":"\/documentation\/overview","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/allSourceIdentifiers":{"title":"allSourceIdentifiers","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/allSourceIdentifiers","type":"topic","abstract":[{"text":"The ordered list of the current style sources’ identifiers and types.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allSourceIdentifiers","kind":"identifier"},{"text":": [","kind":"text"},{"text":"SourceInfo","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps10SourceInfoV"},{"text":"]","kind":"text"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/stylemanager\/allsourceidentifiers","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"url":"\/documentation\/mapboxmaps","role":"collection","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onStyleImageRemoveUnused":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onStyleImageRemoveUnused","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps6SignalV","text":"Signal","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMStyleImageRemoveUnused","text":"StyleImageRemoveUnused","kind":"typeIdentifier"},{"text":">","kind":"text"}],"type":"topic","abstract":[{"text":"An image added to the style is no longer needed and can be removed using ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/removeImage(withId:)","isActive":true,"type":"reference"},{"text":".","type":"text"}],"url":"\/documentation\/mapboxmaps\/mapboxmap\/onstyleimageremoveunused","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleImageRemoveUnused","title":"onStyleImageRemoveUnused"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onCameraChanged":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/oncamerachanged","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onCameraChanged","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps6SignalV","text":"Signal","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMCameraChanged","text":"CameraChanged","kind":"typeIdentifier"},{"text":">","kind":"text"}],"role":"symbol","type":"topic","title":"onCameraChanged","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onCameraChanged","abstract":[{"text":"The camera has changed. This event is emitted whenever the visible viewport","type":"text"},{"text":" ","type":"text"},{"text":"changes due to the MapView’s size changing or when the camera","type":"text"},{"text":" ","type":"text"},{"text":"is modified by calling camera methods. The event is emitted synchronously,","type":"text"},{"text":" ","type":"text"},{"text":"so that an updated camera state can be fetched immediately.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/endGesture()":{"url":"\/documentation\/mapboxmaps\/mapboxmap\/endgesture()","title":"endGesture()","role":"symbol","abstract":[{"type":"text","text":"If implementing a custom gesture, call this method when the gesture ends."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"endGesture","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/endGesture()","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onStyleLoaded":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onStyleLoaded","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Signal","preciseIdentifier":"s:10MapboxMaps6SignalV","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"StyleLoaded","preciseIdentifier":"c:objc(cs)MBMStyleLoaded","kind":"typeIdentifier"},{"text":">","kind":"text"}],"url":"\/documentation\/mapboxmaps\/mapboxmap\/onstyleloaded","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleLoaded","kind":"symbol","title":"onStyleLoaded","abstract":[{"text":"The requested style has been fully loaded, including the style, specified sprite and sources’ metadata.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onRenderFrameStarted":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onRenderFrameStarted","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps6SignalV","text":"Signal","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMRenderFrameStarted","text":"RenderFrameStarted","kind":"typeIdentifier"},{"text":">","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onRenderFrameStarted","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/onrenderframestarted","abstract":[{"type":"text","text":"The map started rendering a frame."}],"title":"onRenderFrameStarted"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onStyleDataLoaded":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleDataLoaded","url":"\/documentation\/mapboxmaps\/mapboxmap\/onstyledataloaded","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The requested style data has been loaded. The "},{"type":"codeVoice","code":"type"},{"type":"text","text":" property defines what kind of style data has been loaded."},{"type":"text","text":" "},{"type":"text","text":"Event may be emitted synchronously, for example, when "},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/loadStyle(_:transition:completion:)-1ilz1","isActive":true},{"type":"text","text":" is used to load style."}],"role":"symbol","title":"onStyleDataLoaded","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onStyleDataLoaded","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps6SignalV","text":"Signal","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMStyleDataLoaded","text":"StyleDataLoaded","kind":"typeIdentifier"},{"text":">","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/loadStyle(_:transition:completion:)-1ilz1":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Loads a "},{"type":"codeVoice","code":"style"},{"type":"text","text":" from a StyleURI, calling a completion closure when the"},{"type":"text","text":" "},{"type":"text","text":"style is fully loaded or there has been an error during load."}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/loadStyle(_:transition:completion:)-1ilz1","url":"\/documentation\/mapboxmaps\/mapboxmap\/loadstyle(_:transition:completion:)-1ilz1","title":"loadStyle(_:transition:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadStyle","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps8StyleURIV","text":"StyleURI","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"transition","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps17TransitionOptionsV","text":"TransitionOptions","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/removeImage(withId:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/removeImage(withId:)","type":"topic","role":"symbol","title":"removeImage(withId:)","url":"\/documentation\/mapboxmaps\/stylemanager\/removeimage(withid:)","kind":"symbol","abstract":[{"text":"Removes an image from the style.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/addSource(_:dataId:)":{"url":"\/documentation\/mapboxmaps\/stylemanager\/addsource(_:dataid:)","kind":"symbol","type":"topic","title":"addSource(_:dataId:)","abstract":[{"text":"Adds a ","type":"text"},{"code":"source","type":"codeVoice"},{"text":" to the map","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addSource","kind":"identifier"},{"text":"(any ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps6SourceP","text":"Source","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"dataId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addSource(_:dataId:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onSourceAdded":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/onsourceadded","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onSourceAdded","abstract":[{"type":"text","text":"The source has been added with "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addSource(_:dataId:)","type":"reference","isActive":true},{"type":"text","text":"  or "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addSource(withId:properties:)","type":"reference","isActive":true},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The event is emitted synchronously, therefore, it is possible to immediately"},{"type":"text","text":" "},{"type":"text","text":"read added source’s properties."}],"type":"topic","title":"onSourceAdded","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSourceAdded"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Signal","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"SourceAdded","preciseIdentifier":"c:objc(cs)MBMSourceAdded"},{"kind":"text","text":">"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onMapLoadingError":{"title":"onMapLoadingError","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onMapLoadingError","kind":"symbol","abstract":[{"text":"An error that has occurred while loading the Map. The ","type":"text"},{"type":"codeVoice","code":"type"},{"text":" property defines what resource could","type":"text"},{"text":" ","type":"text"},{"text":"not be loaded and the ","type":"text"},{"type":"codeVoice","code":"message"},{"text":" property will contain a descriptive error message.","type":"text"},{"text":" ","type":"text"},{"text":"In case of ","type":"text"},{"type":"codeVoice","code":"source"},{"text":" or ","type":"text"},{"type":"codeVoice","code":"tile"},{"text":" loading errors, ","type":"text"},{"type":"codeVoice","code":"sourceID"},{"text":" or ","type":"text"},{"type":"codeVoice","code":"tileID"},{"text":" will contain the identifier of the source failing.","type":"text"}],"url":"\/documentation\/mapboxmaps\/mapboxmap\/onmaploadingerror","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onMapLoadingError","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps6SignalV","text":"Signal","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMMapLoadingError","text":"MapLoadingError","kind":"typeIdentifier"},{"text":">","kind":"text"}],"role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/addImage(_:id:sdf:contentInsets:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addImage(_:id:sdf:contentInsets:)","title":"addImage(_:id:sdf:contentInsets:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addImage","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"id","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"sdf","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"contentInsets","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIEdgeInsets","kind":"typeIdentifier","preciseIdentifier":"c:@S@UIEdgeInsets"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"abstract":[{"text":"Adds an image to be used in the style.","type":"text"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/stylemanager\/addimage(_:id:sdf:contentinsets:)","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onMapLoaded":{"type":"topic","kind":"symbol","abstract":[{"text":"The style has been fully loaded, and the map has rendered all visible tiles.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMapLoaded"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV","text":"Signal"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMMapLoaded","text":"MapLoaded"},{"kind":"text","text":">"}],"url":"\/documentation\/mapboxmaps\/mapboxmap\/onmaploaded","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onMapLoaded","title":"onMapLoaded","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onRenderFrameFinished":{"url":"\/documentation\/mapboxmaps\/mapboxmap\/onrenderframefinished","title":"onRenderFrameFinished","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onRenderFrameFinished","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps6SignalV","text":"Signal","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMRenderFrameFinished","text":"RenderFrameFinished","kind":"typeIdentifier"},{"text":">","kind":"text"}],"role":"symbol","abstract":[{"text":"The map finished rendering a frame.","type":"text"},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"code":"renderMode","type":"codeVoice"},{"text":" property tells whether the map has all data (","type":"text"},{"code":"full","type":"codeVoice"},{"text":") required to render the visible viewport.","type":"text"},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"code":"needsRepaint","type":"codeVoice"},{"text":" property provides information about ongoing transitions that trigger map repaint.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"placementChanged"},{"type":"text","text":" property tells if the symbol placement has been changed in the visible viewport."}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onRenderFrameFinished"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAdded\/title","value":"MBMSourceAdded"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAdded\/fragments","value":[{"text":"MBMSourceAdded","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAdded\/navigatorTitle","value":[{"text":"MBMSourceAdded","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}