{"metadata":{"title":"onEvery(event:handler:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onEvery","kind":"identifier"},{"text":"<","kind":"text"},{"text":"Payload","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"event","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MapEventType","preciseIdentifier":"s:10MapboxMaps12MapEventTypeV","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Payload"},{"text":">, ","kind":"text"},{"text":"handler","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","text":"Payload"},{"kind":"text","text":") -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MBXCancelable","text":"Cancelable"}],"role":"symbol","externalID":"s:10MapboxMaps0A3MapC7onEvery5event7handlerSo13MBXCancelable_pAA0C9EventTypeVyxG_yxctlF","extendedModule":"MapboxMaps","modules":[{"name":"MapboxMaps"}],"symbolKind":"method","platforms":[]},"deprecationSummary":[{"inlineContent":[{"text":"Use mapboxMap.on<eventType>.observe instead.","type":"text"}],"type":"paragraph"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@discardableResult"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onEvery","kind":"identifier"},{"text":"<","kind":"text"},{"kind":"genericParameter","text":"Payload"},{"text":">(","kind":"text"},{"kind":"externalParam","text":"event"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapEventType","kind":"typeIdentifier","text":"MapEventType","preciseIdentifier":"s:10MapboxMaps12MapEventTypeV"},{"kind":"text","text":"<"},{"text":"Payload","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"text":"handler","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"keyword","text":"@escaping"},{"text":" (","kind":"text"},{"kind":"typeIdentifier","text":"Payload"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":") -> any "},{"text":"Cancelable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Cancelable","preciseIdentifier":"c:objc(pl)MBXCancelable","kind":"typeIdentifier"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The event type to listen to.","type":"text"}]}],"name":"event"},{"name":"handler","content":[{"inlineContent":[{"type":"text","text":"The closure to execute when the event occurs."}],"type":"paragraph"}]}]},{"content":[{"text":"Return Value","anchor":"return-value","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"A "},{"type":"codeVoice","code":"Cancelable"},{"text":" object that you can use to stop listening for","type":"text"},{"type":"text","text":" "},{"type":"text","text":"events. This is especially important if you have a retain cycle in"},{"type":"text","text":" "},{"text":"the handler.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"variants":[{"paths":["\/documentation\/mapboxmaps\/mapboxmap\/onevery(event:handler:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"kind":"symbol","abstract":[{"text":"Listen to multiple occurrences of a Map event.","type":"text"}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onEvery(event:handler:)","interfaceLanguage":"swift"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Snapshotter":{"abstract":[{"text":"A utility class for capturing styled map snapshots.","type":"text"}],"title":"Snapshotter","role":"symbol","url":"\/documentation\/mapboxmaps\/snapshotter","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Snapshotter","kind":"identifier"}],"navigatorTitle":[{"text":"Snapshotter","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter","type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","url":"\/documentation\/mapboxmaps\/mapboxmap","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapboxMap"}],"abstract":[{"text":"Provides access to the map model, including the camera, style, observable map events,","type":"text"},{"type":"text","text":" "},{"text":"and querying rendered features.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"MapboxMap","kind":"identifier"}],"title":"MapboxMap"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"type":"topic","role":"collection","kind":"article","title":"MapboxMaps Documentation","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"type":"topic","role":"collection","kind":"symbol","title":"MapboxMaps","url":"\/documentation\/mapboxmaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Cancelable":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Cancelable","url":"\/documentation\/mapboxcommon\/cancelable","title":"Cancelable","kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"Cancelable","kind":"identifier"}],"abstract":[{"text":"Allows to cancel the associated asynchronous operation","type":"text"}],"navigatorTitle":[{"text":"Cancelable","kind":"identifier"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapEventType":{"url":"\/documentation\/mapboxmaps\/mapeventtype","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapEventType","abstract":[{"type":"text","text":"A shim that makes it possible to subscribe to "},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","isActive":true},{"text":" and ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter","isActive":true,"type":"reference"},{"text":" events via the old ","type":"text"},{"code":"onNext","type":"codeVoice"},{"text":" and  ","type":"text"},{"type":"codeVoice","code":"onEvery"},{"type":"text","text":" methods."},{"text":" ","type":"text"},{"type":"text","text":"It is here to simplify migration from v10 to v11, but will be removed in v12."}],"deprecated":true,"type":"topic","title":"MapEventType","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapEventType"}],"navigatorTitle":[{"kind":"identifier","text":"MapEventType"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onEvery(event:handler:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onEvery(event:handler:)","abstract":[{"text":"Listen to multiple occurrences of a Map event.","type":"text"}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onEvery","kind":"identifier"},{"text":"<","kind":"text"},{"kind":"genericParameter","text":"Payload"},{"kind":"text","text":">("},{"kind":"externalParam","text":"event"},{"kind":"text","text":": "},{"text":"MapEventType","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps12MapEventTypeV"},{"text":"<","kind":"text"},{"text":"Payload","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"text":"handler","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","text":"Payload"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":") -> any ","kind":"text"},{"text":"Cancelable","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MBXCancelable"}],"deprecated":true,"url":"\/documentation\/mapboxmaps\/mapboxmap\/onevery(event:handler:)","title":"onEvery(event:handler:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"role":"collectionGroup","url":"\/documentation\/mapboxmaps\/mapboxmap-apis","type":"topic","title":"MapboxMap","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MBXCancelable","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/fragments","value":[{"text":"MBXCancelable","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/navigatorTitle","value":[{"text":"MBXCancelable","kind":"identifier"}]}]}]}