{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap"],["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/MapboxMapProtocol-Implementations"]]},"kind":"symbol","abstract":[{"text":"The requested style has been fully loaded, including the style, specified sprite and sources’ metadata.","type":"text"}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleLoaded","interfaceLanguage":"swift"},"metadata":{"externalID":"s:10MapboxMaps0A3MapC13onStyleLoadedAA6SignalVySo08MBMStyleF0CGvp","role":"symbol","title":"onStyleLoaded","extendedModule":"MapboxMaps","modules":[{"name":"MapboxMaps"}],"roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"onStyleLoaded","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Signal","preciseIdentifier":"s:10MapboxMaps6SignalV","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMStyleLoaded","text":"StyleLoaded"},{"text":">","kind":"text"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onStyleLoaded","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Signal","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Signal","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"kind":"text","text":"<"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleLoaded","kind":"typeIdentifier","text":"StyleLoaded","preciseIdentifier":"c:objc(cs)MBMStyleLoaded"},{"kind":"text","text":"> { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}]}]},{"content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"inlineContent":[{"type":"text","text":"The style specified sprite would be marked as loaded even with sprite loading error (an error will be emitted via "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onMapLoadingError"},{"type":"text","text":")."},{"text":" ","type":"text"},{"type":"text","text":"Sprite loading error is not fatal and we don’t want it to block the map rendering, thus this event will still be emitted if style and sources are fully loaded."}],"type":"paragraph"}],"kind":"content"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/mapboxmap\/onstyleloaded"]}],"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onMapLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onMapLoadingError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleDataLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onCameraChanged","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onMapIdle","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onSourceAdded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onSourceRemoved","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onSourceDataLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleImageMissing","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleImageRemoveUnused","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onRenderFrameStarted","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onRenderFrameFinished","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onResourceRequest"],"anchor":"Map-events","title":"Map events"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onMapIdle":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onMapIdle","title":"onMapIdle","abstract":[{"type":"text","text":"The map has entered the idle state. The map is in the idle state when there are no ongoing transitions"},{"text":" ","type":"text"},{"type":"text","text":"and the map has rendered all requested non-volatile tiles. The event will not be emitted if animation is in progress (see "},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/beginAnimation()","isActive":true},{"text":", ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/endAnimation()"},{"text":")","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"and \/ or gesture is in progress (see "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/beginGesture()"},{"text":", ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/endGesture()","isActive":true},{"text":").","type":"text"}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/onmapidle","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"onMapIdle","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Signal","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMMapIdle","text":"MapIdle"},{"kind":"text","text":">"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/beginAnimation()":{"kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"If implementing a custom animation mechanism, call this method when the animation begins.","type":"text"}],"url":"\/documentation\/mapboxmaps\/mapboxmap\/beginanimation()","title":"beginAnimation()","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/beginAnimation()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"beginAnimation","kind":"identifier"},{"kind":"text","text":"()"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/removeSource(withId:)":{"kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"Removes an existing style source.","type":"text"}],"url":"\/documentation\/mapboxmaps\/stylemanager\/removesource(withid:)","title":"removeSource(withId:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/removeSource(withId:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"removeSource"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","url":"\/documentation\/mapboxmaps\/mapboxmap","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapboxMap"}],"abstract":[{"text":"Provides access to the map model, including the camera, style, observable map events,","type":"text"},{"type":"text","text":" "},{"text":"and querying rendered features.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"MapboxMap","kind":"identifier"}],"title":"MapboxMap"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/MapboxMapProtocol-Implementations":{"kind":"article","role":"collectionGroup","type":"topic","abstract":[],"url":"\/documentation\/mapboxmaps\/mapboxmap\/mapboxmapprotocol-implementations","title":"MapboxMapProtocol Implementations","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/MapboxMapProtocol-Implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onStyleLoaded":{"kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"text","text":"The requested style has been fully loaded, including the style, specified sprite and sources’ metadata."}],"url":"\/documentation\/mapboxmaps\/mapboxmap\/onstyleloaded","title":"onStyleLoaded","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleLoaded","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onStyleLoaded"},{"text":": ","kind":"text"},{"text":"Signal","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMStyleLoaded","text":"StyleLoaded"},{"kind":"text","text":">"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"type":"topic","role":"collection","kind":"article","title":"MapboxMaps Documentation","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onRenderFrameStarted":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onRenderFrameStarted","title":"onRenderFrameStarted","abstract":[{"type":"text","text":"The map started rendering a frame."}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/onrenderframestarted","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onRenderFrameStarted"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps6SignalV","kind":"typeIdentifier","text":"Signal"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"RenderFrameStarted","preciseIdentifier":"c:objc(cs)MBMRenderFrameStarted"},{"kind":"text","text":">"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onRenderFrameFinished":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onRenderFrameFinished","title":"onRenderFrameFinished","abstract":[{"text":"The map finished rendering a frame.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The "},{"type":"codeVoice","code":"renderMode"},{"type":"text","text":" property tells whether the map has all data ("},{"code":"full","type":"codeVoice"},{"type":"text","text":") required to render the visible viewport."},{"type":"text","text":" "},{"text":"The ","type":"text"},{"type":"codeVoice","code":"needsRepaint"},{"text":" property provides information about ongoing transitions that trigger map repaint.","type":"text"},{"type":"text","text":" "},{"text":"The ","type":"text"},{"type":"codeVoice","code":"placementChanged"},{"text":" property tells if the symbol placement has been changed in the visible viewport.","type":"text"}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/onrenderframefinished","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onRenderFrameFinished"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV","text":"Signal"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"RenderFrameFinished","preciseIdentifier":"c:objc(cs)MBMRenderFrameFinished"},{"text":">","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/endAnimation()":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/endAnimation()","title":"endAnimation()","abstract":[{"type":"text","text":"If implementing a custom animation mechanism, call this method when the animation ends."}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/endanimation()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"endAnimation"},{"text":"()","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onResourceRequest":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onResourceRequest","title":"onResourceRequest","abstract":[{"text":"The ","type":"text"},{"code":"ResourceRequest","type":"codeVoice"},{"type":"text","text":" event allows client to observe resource requests made by a"},{"text":" ","type":"text"},{"text":"map or snapshotter.","type":"text"}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/onresourcerequest","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onResourceRequest"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV","text":"Signal"},{"kind":"text","text":"<"},{"text":"ResourceRequest","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMResourceRequest"},{"text":">","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/endGesture()":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/endGesture()","title":"endGesture()","abstract":[{"type":"text","text":"If implementing a custom gesture, call this method when the gesture ends."}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/endgesture()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"endGesture","kind":"identifier"},{"kind":"text","text":"()"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/allSourceIdentifiers":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/allSourceIdentifiers","title":"allSourceIdentifiers","abstract":[{"type":"text","text":"The ordered list of the current style sources’ identifiers and types."}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/stylemanager\/allsourceidentifiers","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allSourceIdentifiers"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"SourceInfo","preciseIdentifier":"s:10MapboxMaps10SourceInfoV"},{"kind":"text","text":"]"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/addSource(withId:properties:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addSource(withId:properties:)","title":"addSource(withId:properties:)","abstract":[{"type":"text","text":"Adds a new style source."}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/stylemanager\/addsource(withid:properties:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addSource"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"properties"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]) "},{"text":"throws","kind":"keyword"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onMapLoaded":{"kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"The style has been fully loaded, and the map has rendered all visible tiles.","type":"text"}],"url":"\/documentation\/mapboxmaps\/mapboxmap\/onmaploaded","title":"onMapLoaded","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onMapLoaded","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onMapLoaded","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Signal","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"kind":"text","text":"<"},{"text":"MapLoaded","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMMapLoaded"},{"text":">","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/removeImage(withId:)":{"kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"Removes an image from the style.","type":"text"}],"url":"\/documentation\/mapboxmaps\/stylemanager\/removeimage(withid:)","title":"removeImage(withId:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/removeImage(withId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/loadStyle(_:transition:completion:)-1ilz1":{"kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"Loads a ","type":"text"},{"type":"codeVoice","code":"style"},{"type":"text","text":" from a StyleURI, calling a completion closure when the"},{"type":"text","text":" "},{"text":"style is fully loaded or there has been an error during load.","type":"text"}],"url":"\/documentation\/mapboxmaps\/mapboxmap\/loadstyle(_:transition:completion:)-1ilz1","title":"loadStyle(_:transition:completion:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/loadStyle(_:transition:completion:)-1ilz1","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"loadStyle","kind":"identifier"},{"text":"(","kind":"text"},{"text":"StyleURI","preciseIdentifier":"s:10MapboxMaps8StyleURIV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"transition","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10MapboxMaps17TransitionOptionsV","text":"TransitionOptions","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"text":": (((any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onSourceAdded":{"kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"text","text":"The source has been added with "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addSource(_:dataId:)","type":"reference","isActive":true},{"type":"text","text":"  or "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addSource(withId:properties:)"},{"type":"text","text":"."},{"text":" ","type":"text"},{"type":"text","text":"The event is emitted synchronously, therefore, it is possible to immediately"},{"text":" ","type":"text"},{"text":"read added source’s properties.","type":"text"}],"url":"\/documentation\/mapboxmaps\/mapboxmap\/onsourceadded","title":"onSourceAdded","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onSourceAdded","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSourceAdded"},{"kind":"text","text":": "},{"text":"Signal","preciseIdentifier":"s:10MapboxMaps6SignalV","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMSourceAdded","text":"SourceAdded","kind":"typeIdentifier"},{"kind":"text","text":">"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"type":"topic","role":"collection","kind":"symbol","title":"MapboxMaps","url":"\/documentation\/mapboxmaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleLoaded":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StyleLoaded"}],"abstract":[{"type":"text","text":"The requested style has been fully loaded, including specified sprite, and sources’ metadata."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleLoaded","navigatorTitle":[{"text":"StyleLoaded","kind":"identifier"}],"title":"StyleLoaded","role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/styleloaded"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/addImage(_:id:sdf:contentInsets:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addImage(_:id:sdf:contentInsets:)","title":"addImage(_:id:sdf:contentInsets:)","abstract":[{"type":"text","text":"Adds an image to be used in the style."}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/stylemanager\/addimage(_:id:sdf:contentinsets:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"addImage","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sdf"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"contentInsets","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIEdgeInsets","preciseIdentifier":"c:@S@UIEdgeInsets"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Signal":{"url":"\/documentation\/mapboxmaps\/signal","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Signal","kind":"identifier"}],"abstract":[{"type":"text","text":"Signal is a typed interface for observing arbitrary values over time."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Signal","type":"topic","role":"symbol","title":"Signal","navigatorTitle":[{"text":"Signal","kind":"identifier"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"role":"collectionGroup","url":"\/documentation\/mapboxmaps\/mapboxmap-apis","type":"topic","title":"MapboxMap","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onStyleImageRemoveUnused":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleImageRemoveUnused","title":"onStyleImageRemoveUnused","abstract":[{"text":"An image added to the style is no longer needed and can be removed using ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/removeImage(withId:)","isActive":true,"type":"reference"},{"type":"text","text":"."}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/onstyleimageremoveunused","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"onStyleImageRemoveUnused","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Signal","preciseIdentifier":"s:10MapboxMaps6SignalV","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)MBMStyleImageRemoveUnused","text":"StyleImageRemoveUnused","kind":"typeIdentifier"},{"kind":"text","text":">"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onMapLoadingError":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onMapLoadingError","title":"onMapLoadingError","abstract":[{"type":"text","text":"An error that has occurred while loading the Map. The "},{"code":"type","type":"codeVoice"},{"text":" property defines what resource could","type":"text"},{"text":" ","type":"text"},{"text":"not be loaded and the ","type":"text"},{"type":"codeVoice","code":"message"},{"type":"text","text":" property will contain a descriptive error message."},{"type":"text","text":" "},{"text":"In case of ","type":"text"},{"code":"source","type":"codeVoice"},{"text":" or ","type":"text"},{"type":"codeVoice","code":"tile"},{"text":" loading errors, ","type":"text"},{"type":"codeVoice","code":"sourceID"},{"text":" or ","type":"text"},{"type":"codeVoice","code":"tileID"},{"type":"text","text":" will contain the identifier of the source failing."}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/onmaploadingerror","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMapLoadingError"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10MapboxMaps6SignalV","text":"Signal","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"MapLoadingError","preciseIdentifier":"c:objc(cs)MBMMapLoadingError"},{"text":">","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onCameraChanged":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onCameraChanged","title":"onCameraChanged","abstract":[{"type":"text","text":"The camera has changed. This event is emitted whenever the visible viewport"},{"text":" ","type":"text"},{"type":"text","text":"changes due to the MapView’s size changing or when the camera"},{"type":"text","text":" "},{"text":"is modified by calling camera methods. The event is emitted synchronously,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"so that an updated camera state can be fetched immediately."}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/oncamerachanged","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"onCameraChanged","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Signal","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMCameraChanged","text":"CameraChanged"},{"kind":"text","text":">"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onStyleImageMissing":{"kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"A style has a missing image. This event is emitted when the map renders visible tiles and","type":"text"},{"type":"text","text":" "},{"text":"one of the required images is missing in the sprite sheet. Subscriber has to provide the missing image","type":"text"},{"type":"text","text":" "},{"text":"by calling ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addImage(_:id:sdf:contentInsets:)","isActive":true},{"text":".","type":"text"}],"url":"\/documentation\/mapboxmaps\/mapboxmap\/onstyleimagemissing","title":"onStyleImageMissing","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleImageMissing","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onStyleImageMissing"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10MapboxMaps6SignalV","kind":"typeIdentifier","text":"Signal"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)MBMStyleImageMissing","text":"StyleImageMissing","kind":"typeIdentifier"},{"kind":"text","text":">"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/addSource(_:dataId:)":{"kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Adds a "},{"code":"source","type":"codeVoice"},{"text":" to the map","type":"text"}],"url":"\/documentation\/mapboxmaps\/stylemanager\/addsource(_:dataid:)","title":"addSource(_:dataId:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addSource(_:dataId:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addSource","kind":"identifier"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","text":"Source","preciseIdentifier":"s:10MapboxMaps6SourceP"},{"kind":"text","text":", "},{"text":"dataId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onSourceDataLoaded":{"kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"A source data has been loaded.","type":"text"},{"text":" ","type":"text"},{"text":"Event may be emitted synchronously in cases when source’s metadata is available when source is added to the style.","type":"text"}],"url":"\/documentation\/mapboxmaps\/mapboxmap\/onsourcedataloaded","title":"onSourceDataLoaded","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onSourceDataLoaded","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSourceDataLoaded"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10MapboxMaps6SignalV","kind":"typeIdentifier","text":"Signal"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMSourceDataLoaded","text":"SourceDataLoaded","kind":"typeIdentifier"},{"text":">","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onSourceRemoved":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onSourceRemoved","title":"onSourceRemoved","abstract":[{"type":"text","text":"The source has been removed with "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/removeSource(withId:)","isActive":true,"type":"reference"},{"type":"text","text":"."},{"text":" ","type":"text"},{"type":"text","text":"The event is emitted synchronously, thus, "},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/allSourceIdentifiers","isActive":true},{"text":" will be","type":"text"},{"text":" ","type":"text"},{"text":"in sync when the observer receives the notification.","type":"text"}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/onsourceremoved","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onSourceRemoved","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Signal","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMSourceRemoved","text":"SourceRemoved","kind":"typeIdentifier"},{"kind":"text","text":">"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onStyleDataLoaded":{"kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"The requested style data has been loaded. The ","type":"text"},{"type":"codeVoice","code":"type"},{"text":" property defines what kind of style data has been loaded.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Event may be emitted synchronously, for example, when "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/loadStyle(_:transition:completion:)-1ilz1","type":"reference","isActive":true},{"type":"text","text":" is used to load style."}],"url":"\/documentation\/mapboxmaps\/mapboxmap\/onstyledataloaded","title":"onStyleDataLoaded","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleDataLoaded","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onStyleDataLoaded"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps6SignalV","kind":"typeIdentifier","text":"Signal"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"StyleDataLoaded","preciseIdentifier":"c:objc(cs)MBMStyleDataLoaded"},{"kind":"text","text":">"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/beginGesture()":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/beginGesture()","title":"beginGesture()","abstract":[{"type":"text","text":"If implementing a custom gesture, call this method when the gesture begins."}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/begingesture()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"beginGesture","kind":"identifier"},{"text":"()","kind":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoaded\/title","op":"replace","value":"MBMStyleLoaded"},{"value":[{"text":"MBMStyleLoaded","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoaded\/fragments"},{"value":[{"kind":"identifier","text":"MBMStyleLoaded"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleLoaded\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}