{"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSource\/init(id:options:)","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"id","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions","kind":"typeIdentifier","text":"CustomRasterSourceOptions","preciseIdentifier":"c:objc(cs)MBMCustomRasterSourceOptions"},{"kind":"text","text":")"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSource"]]},"metadata":{"roleHeading":"Initializer","externalID":"s:10MapboxMaps18CustomRasterSourceV2id7optionsACSS_So09MBMCustomdE7OptionsCtcfc","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"id","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CustomRasterSourceOptions","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMCustomRasterSourceOptions"},{"kind":"text","text":")"}],"tags":[{"type":"spi","text":"SPI"}],"role":"symbol","modules":[{"name":"MapboxMaps"}],"title":"init(id:options:)","symbolKind":"init"},"variants":[{"paths":["\/documentation\/mapboxmaps\/customrastersource\/init(id:options:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Sources":{"kind":"article","title":"Sources","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources","type":"topic","abstract":[],"role":"collectionGroup","url":"\/documentation\/mapboxmaps\/sources"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSource/init(id:options:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"id"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CustomRasterSourceOptions","preciseIdentifier":"c:objc(cs)MBMCustomRasterSourceOptions"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/customrastersource\/init(id:options:)","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSource\/init(id:options:)","role":"symbol","tags":[{"text":"SPI","type":"spi"}],"title":"init(id:options:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSource":{"role":"symbol","tags":[{"text":"SPI","type":"spi"}],"url":"\/documentation\/mapboxmaps\/customrastersource","title":"CustomRasterSource","type":"topic","navigatorTitle":[{"text":"CustomRasterSource","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSource","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomRasterSource"}],"abstract":[{"text":"Describes a Custom Raster Source to be used in the style.","type":"text"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","url":"\/documentation\/overview","kind":"article","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","kind":"symbol","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceOptions":{"role":"symbol","url":"\/documentation\/mapboxmaps\/customrastersourceoptions","title":"CustomRasterSourceOptions","type":"topic","navigatorTitle":[{"text":"CustomRasterSourceOptions","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CustomRasterSourceOptions","kind":"identifier"}],"abstract":[{"text":"Options for custom raster source.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/title","value":"MBMCustomRasterSourceOptions"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/fragments","value":[{"kind":"identifier","text":"MBMCustomRasterSourceOptions"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/navigatorTitle","value":[{"kind":"identifier","text":"MBMCustomRasterSourceOptions"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}