{"metadata":{"title":"RawRepresentable Implementations","role":"collectionGroup","roleHeading":"API Collection","modules":[{"name":"MapboxCommon"},{"name":"MapboxMaps"}]},"sections":[],"topicSections":[{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LoggingLevel\/hashValue"],"title":"Instance Properties"},{"anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LoggingLevel\/hash(into:)"],"title":"Instance Methods"}],"kind":"article","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LoggingLevel"]]},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LoggingLevel\/RawRepresentable-Implementations","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","type":"topic","abstract":[],"title":"MapboxMaps Documentation","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","role":"collection","title":"MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LoggingLevel/hash(into:)":{"url":"\/documentation\/mapboxcommon\/logginglevel\/hash(into:)","conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}]},"title":"hash(into:)","abstract":[],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LoggingLevel\/hash(into:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hasher","kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV"},{"text":")","kind":"text"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LoggingLevel":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LoggingLevel","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LoggingLevel","kind":"identifier"}],"title":"LoggingLevel","kind":"symbol","role":"symbol","url":"\/documentation\/mapboxcommon\/logginglevel","navigatorTitle":[{"text":"LoggingLevel","kind":"identifier"}],"abstract":[{"text":"State level of a log message.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LoggingLevel/hashValue":{"url":"\/documentation\/mapboxcommon\/logginglevel\/hashvalue","conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":"."}]},"title":"hashValue","abstract":[],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LoggingLevel\/hashValue","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Performance":{"url":"\/documentation\/mapboxmaps\/performance","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","type":"topic","kind":"article","title":"Performance and investigations"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"MBXLoggingLevel","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LoggingLevel\/title"},{"op":"replace","value":[{"text":"MBXLoggingLevel","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LoggingLevel\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MBXLoggingLevel"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LoggingLevel\/navigatorTitle"}]}]}