{"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"An image added to the style is no longer needed and can be removed using ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/removeImage(withId:)","isActive":true,"type":"reference"},{"text":".","type":"text"}],"seeAlsoSections":[{"anchor":"Map-events","title":"Map events","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onMapLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onMapLoadingError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleDataLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onCameraChanged","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onMapIdle","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onSourceAdded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onSourceRemoved","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onSourceDataLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleImageMissing","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onRenderFrameStarted","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onRenderFrameFinished","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onResourceRequest"],"generated":true}],"sections":[],"variants":[{"paths":["\/documentation\/mapboxmaps\/mapboxmap\/onstyleimageremoveunused"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onStyleImageRemoveUnused"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10MapboxMaps6SignalV","kind":"typeIdentifier","text":"Signal","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Signal"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)MBMStyleImageRemoveUnused","kind":"typeIdentifier","text":"StyleImageRemoveUnused","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnused"},{"kind":"text","text":"> { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"role":"symbol","roleHeading":"Instance Property","extendedModule":"MapboxMaps","title":"onStyleImageRemoveUnused","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onStyleImageRemoveUnused","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps6SignalV","text":"Signal","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMStyleImageRemoveUnused","text":"StyleImageRemoveUnused","kind":"typeIdentifier"},{"text":">","kind":"text"}],"externalID":"s:10MapboxMaps0A3MapC24onStyleImageRemoveUnusedAA6SignalVySo08MBMStylefgH0CGvp","modules":[{"name":"MapboxMaps"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleImageRemoveUnused"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap"],["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/MapboxMapProtocol-Implementations"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onStyleImageMissing":{"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleImageMissing","abstract":[{"text":"A style has a missing image. This event is emitted when the map renders visible tiles and","type":"text"},{"text":" ","type":"text"},{"text":"one of the required images is missing in the sprite sheet. Subscriber has to provide the missing image","type":"text"},{"text":" ","type":"text"},{"text":"by calling ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addImage(_:id:sdf:contentInsets:)","isActive":true,"type":"reference"},{"text":".","type":"text"}],"title":"onStyleImageMissing","url":"\/documentation\/mapboxmaps\/mapboxmap\/onstyleimagemissing","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onStyleImageMissing","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV","text":"Signal"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMStyleImageMissing","text":"StyleImageMissing"},{"kind":"text","text":">"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onRenderFrameStarted":{"title":"onRenderFrameStarted","kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onRenderFrameStarted","abstract":[{"text":"The map started rendering a frame.","type":"text"}],"url":"\/documentation\/mapboxmaps\/mapboxmap\/onrenderframestarted","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onRenderFrameStarted"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV","text":"Signal"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMRenderFrameStarted","text":"RenderFrameStarted"},{"kind":"text","text":">"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","url":"\/documentation\/overview","kind":"article","type":"topic","role":"collection","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/removeImage(withId:)":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/removeImage(withId:)","title":"removeImage(withId:)","type":"topic","url":"\/documentation\/mapboxmaps\/stylemanager\/removeimage(withid:)","role":"symbol","abstract":[{"type":"text","text":"Removes an image from the style."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/endGesture()":{"kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/endgesture()","abstract":[{"type":"text","text":"If implementing a custom gesture, call this method when the gesture ends."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/endGesture()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"endGesture"},{"kind":"text","text":"()"}],"title":"endGesture()","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","url":"\/documentation\/mapboxmaps","title":"MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onSourceDataLoaded":{"abstract":[{"text":"A source data has been loaded.","type":"text"},{"text":" ","type":"text"},{"text":"Event may be emitted synchronously in cases when source’s metadata is available when source is added to the style.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onSourceDataLoaded","url":"\/documentation\/mapboxmaps\/mapboxmap\/onsourcedataloaded","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSourceDataLoaded"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV","text":"Signal"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMSourceDataLoaded","text":"SourceDataLoaded"},{"kind":"text","text":">"}],"role":"symbol","type":"topic","title":"onSourceDataLoaded","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap":{"title":"MapboxMap","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapboxMap"}],"navigatorTitle":[{"kind":"identifier","text":"MapboxMap"}],"abstract":[{"text":"Provides access to the map model, including the camera, style, observable map events,","type":"text"},{"text":" ","type":"text"},{"text":"and querying rendered features.","type":"text"}],"url":"\/documentation\/mapboxmaps\/mapboxmap","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/removeSource(withId:)":{"title":"removeSource(withId:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/removeSource(withId:)","abstract":[{"type":"text","text":"Removes an existing style source."}],"type":"topic","url":"\/documentation\/mapboxmaps\/stylemanager\/removesource(withid:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeSource","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onStyleImageRemoveUnused":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleImageRemoveUnused","type":"topic","url":"\/documentation\/mapboxmaps\/mapboxmap\/onstyleimageremoveunused","title":"onStyleImageRemoveUnused","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onStyleImageRemoveUnused"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Signal","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"StyleImageRemoveUnused","preciseIdentifier":"c:objc(cs)MBMStyleImageRemoveUnused"},{"kind":"text","text":">"}],"abstract":[{"type":"text","text":"An image added to the style is no longer needed and can be removed using "},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/removeImage(withId:)","isActive":true},{"type":"text","text":"."}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onStyleDataLoaded":{"url":"\/documentation\/mapboxmaps\/mapboxmap\/onstyledataloaded","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onStyleDataLoaded"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV","text":"Signal"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMStyleDataLoaded","text":"StyleDataLoaded"},{"kind":"text","text":">"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleDataLoaded","title":"onStyleDataLoaded","abstract":[{"text":"The requested style data has been loaded. The ","type":"text"},{"type":"codeVoice","code":"type"},{"text":" property defines what kind of style data has been loaded.","type":"text"},{"text":" ","type":"text"},{"text":"Event may be emitted synchronously, for example, when ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/loadStyle(_:transition:completion:)-1ilz1"},{"text":" is used to load style.","type":"text"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onSourceRemoved":{"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onSourceRemoved","abstract":[{"text":"The source has been removed with ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/removeSource(withId:)"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"The event is emitted synchronously, thus, ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/allSourceIdentifiers"},{"text":" will be","type":"text"},{"text":" ","type":"text"},{"text":"in sync when the observer receives the notification.","type":"text"}],"title":"onSourceRemoved","url":"\/documentation\/mapboxmaps\/mapboxmap\/onsourceremoved","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSourceRemoved"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV","text":"Signal"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMSourceRemoved","text":"SourceRemoved"},{"kind":"text","text":">"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onCameraChanged":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onCameraChanged","kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/oncamerachanged","type":"topic","title":"onCameraChanged","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onCameraChanged"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV","text":"Signal"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMCameraChanged","text":"CameraChanged"},{"kind":"text","text":">"}],"abstract":[{"text":"The camera has changed. This event is emitted whenever the visible viewport","type":"text"},{"text":" ","type":"text"},{"text":"changes due to the MapView’s size changing or when the camera","type":"text"},{"text":" ","type":"text"},{"text":"is modified by calling camera methods. The event is emitted synchronously,","type":"text"},{"text":" ","type":"text"},{"text":"so that an updated camera state can be fetched immediately.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onStyleLoaded":{"role":"symbol","kind":"symbol","title":"onStyleLoaded","url":"\/documentation\/mapboxmaps\/mapboxmap\/onstyleloaded","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onStyleLoaded","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Signal","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"text":"<","kind":"text"},{"text":"StyleLoaded","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMStyleLoaded"},{"text":">","kind":"text"}],"type":"topic","abstract":[{"text":"The requested style has been fully loaded, including the style, specified sprite and sources’ metadata.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleLoaded"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleImageRemoveUnused":{"url":"\/documentation\/mapboxmaps\/styleimageremoveunused","abstract":[{"text":"An image requested by the ","type":"text"},{"code":"map","type":"codeVoice"},{"text":" through the ","type":"text"},{"code":"StyleImageMissing","type":"codeVoice"},{"text":" event is no longer","type":"text"},{"text":" ","type":"text"},{"text":"needed and can be removed using the ","type":"text"},{"code":"removeStyleImage","type":"codeVoice"},{"text":" method. The application can","type":"text"},{"text":" ","type":"text"},{"text":"decide whether the image should be kept or removed.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StyleImageRemoveUnused","kind":"identifier"}],"navigatorTitle":[{"text":"StyleImageRemoveUnused","kind":"identifier"}],"kind":"symbol","title":"StyleImageRemoveUnused","type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageRemoveUnused"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onSourceAdded":{"type":"topic","kind":"symbol","title":"onSourceAdded","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onSourceAdded","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Signal","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"text":"<","kind":"text"},{"text":"SourceAdded","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMSourceAdded"},{"text":">","kind":"text"}],"abstract":[{"type":"text","text":"The source has been added with "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addSource(_:dataId:)"},{"type":"text","text":"  or "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addSource(withId:properties:)"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The event is emitted synchronously, therefore, it is possible to immediately"},{"type":"text","text":" "},{"type":"text","text":"read added source’s properties."}],"url":"\/documentation\/mapboxmaps\/mapboxmap\/onsourceadded","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onSourceAdded"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onRenderFrameFinished":{"url":"\/documentation\/mapboxmaps\/mapboxmap\/onrenderframefinished","kind":"symbol","title":"onRenderFrameFinished","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onRenderFrameFinished","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Signal","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"text":"<","kind":"text"},{"text":"RenderFrameFinished","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMRenderFrameFinished"},{"text":">","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onRenderFrameFinished","abstract":[{"type":"text","text":"The map finished rendering a frame."},{"type":"text","text":" "},{"type":"text","text":"The "},{"code":"renderMode","type":"codeVoice"},{"type":"text","text":" property tells whether the map has all data ("},{"code":"full","type":"codeVoice"},{"type":"text","text":") required to render the visible viewport."},{"type":"text","text":" "},{"type":"text","text":"The "},{"code":"needsRepaint","type":"codeVoice"},{"type":"text","text":" property provides information about ongoing transitions that trigger map repaint."},{"type":"text","text":" "},{"type":"text","text":"The "},{"code":"placementChanged","type":"codeVoice"},{"type":"text","text":" property tells if the symbol placement has been changed in the visible viewport."}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/beginGesture()":{"type":"topic","title":"beginGesture()","url":"\/documentation\/mapboxmaps\/mapboxmap\/begingesture()","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/beginGesture()","abstract":[{"type":"text","text":"If implementing a custom gesture, call this method when the gesture begins."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"beginGesture","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onMapIdle":{"type":"topic","abstract":[{"text":"The map has entered the idle state. The map is in the idle state when there are no ongoing transitions","type":"text"},{"text":" ","type":"text"},{"text":"and the map has rendered all requested non-volatile tiles. The event will not be emitted if animation is in progress (see ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/beginAnimation()","isActive":true,"type":"reference"},{"text":", ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/endAnimation()","isActive":true,"type":"reference"},{"text":")","type":"text"},{"text":" ","type":"text"},{"text":"and \/ or gesture is in progress (see ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/beginGesture()","isActive":true,"type":"reference"},{"text":", ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/endGesture()","isActive":true,"type":"reference"},{"text":").","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onMapIdle","title":"onMapIdle","url":"\/documentation\/mapboxmaps\/mapboxmap\/onmapidle","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onMapIdle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Signal","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"text":"<","kind":"text"},{"text":"MapIdle","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMMapIdle"},{"text":">","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/addSource(_:dataId:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addSource(_:dataId:)","url":"\/documentation\/mapboxmaps\/stylemanager\/addsource(_:dataid:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addSource","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"Source","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SourceP"},{"text":", ","kind":"text"},{"text":"dataId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"}],"kind":"symbol","title":"addSource(_:dataId:)","abstract":[{"text":"Adds a ","type":"text"},{"code":"source","type":"codeVoice"},{"text":" to the map","type":"text"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","kind":"article","title":"MapboxMap","url":"\/documentation\/mapboxmaps\/mapboxmap-apis","abstract":[],"role":"collectionGroup","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/addImage(_:id:sdf:contentInsets:)":{"title":"addImage(_:id:sdf:contentInsets:)","type":"topic","url":"\/documentation\/mapboxmaps\/stylemanager\/addimage(_:id:sdf:contentinsets:)","role":"symbol","abstract":[{"text":"Adds an image to be used in the style.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addImage(_:id:sdf:contentInsets:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"id","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"sdf","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"contentInsets","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIEdgeInsets","preciseIdentifier":"c:@S@UIEdgeInsets","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onResourceRequest":{"title":"onResourceRequest","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"ResourceRequest"},{"text":" event allows client to observe resource requests made by a","type":"text"},{"text":" ","type":"text"},{"text":"map or snapshotter.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onResourceRequest","url":"\/documentation\/mapboxmaps\/mapboxmap\/onresourcerequest","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onResourceRequest","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Signal","preciseIdentifier":"s:10MapboxMaps6SignalV","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"ResourceRequest","preciseIdentifier":"c:objc(cs)MBMResourceRequest","kind":"typeIdentifier"},{"text":">","kind":"text"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Signal":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Signal"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"Signal"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Signal","title":"Signal","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Signal is a typed interface for observing arbitrary values over time."}],"url":"\/documentation\/mapboxmaps\/signal"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/endAnimation()":{"title":"endAnimation()","role":"symbol","abstract":[{"text":"If implementing a custom animation mechanism, call this method when the animation ends.","type":"text"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/endanimation()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"endAnimation","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/endAnimation()","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/beginAnimation()":{"kind":"symbol","abstract":[{"text":"If implementing a custom animation mechanism, call this method when the animation begins.","type":"text"}],"title":"beginAnimation()","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/beginAnimation()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"beginAnimation"},{"kind":"text","text":"()"}],"type":"topic","url":"\/documentation\/mapboxmaps\/mapboxmap\/beginanimation()","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/MapboxMapProtocol-Implementations":{"url":"\/documentation\/mapboxmaps\/mapboxmap\/mapboxmapprotocol-implementations","type":"topic","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/MapboxMapProtocol-Implementations","kind":"article","title":"MapboxMapProtocol Implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onMapLoadingError":{"title":"onMapLoadingError","url":"\/documentation\/mapboxmaps\/mapboxmap\/onmaploadingerror","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMapLoadingError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV","text":"Signal"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMMapLoadingError","text":"MapLoadingError"},{"kind":"text","text":">"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onMapLoadingError","abstract":[{"type":"text","text":"An error that has occurred while loading the Map. The "},{"type":"codeVoice","code":"type"},{"type":"text","text":" property defines what resource could"},{"type":"text","text":" "},{"type":"text","text":"not be loaded and the "},{"type":"codeVoice","code":"message"},{"type":"text","text":" property will contain a descriptive error message."},{"type":"text","text":" "},{"type":"text","text":"In case of "},{"type":"codeVoice","code":"source"},{"type":"text","text":" or "},{"type":"codeVoice","code":"tile"},{"type":"text","text":" loading errors, "},{"type":"codeVoice","code":"sourceID"},{"type":"text","text":" or "},{"type":"codeVoice","code":"tileID"},{"type":"text","text":" will contain the identifier of the source failing."}],"kind":"symbol","type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/addSource(withId:properties:)":{"url":"\/documentation\/mapboxmaps\/stylemanager\/addsource(withid:properties:)","kind":"symbol","title":"addSource(withId:properties:)","type":"topic","abstract":[{"type":"text","text":"Adds a new style source."}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addSource"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"properties"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]) "},{"kind":"keyword","text":"throws"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addSource(withId:properties:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/allSourceIdentifiers":{"title":"allSourceIdentifiers","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/allSourceIdentifiers","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allSourceIdentifiers","kind":"identifier"},{"text":": [","kind":"text"},{"text":"SourceInfo","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps10SourceInfoV"},{"text":"]","kind":"text"}],"role":"symbol","abstract":[{"text":"The ordered list of the current style sources’ identifiers and types.","type":"text"}],"type":"topic","url":"\/documentation\/mapboxmaps\/stylemanager\/allsourceidentifiers"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onMapLoaded":{"type":"topic","role":"symbol","abstract":[{"text":"The style has been fully loaded, and the map has rendered all visible tiles.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onMapLoaded","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Signal","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"text":"<","kind":"text"},{"text":"MapLoaded","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMMapLoaded"},{"text":">","kind":"text"}],"kind":"symbol","title":"onMapLoaded","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onMapLoaded","url":"\/documentation\/mapboxmaps\/mapboxmap\/onmaploaded"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/loadStyle(_:transition:completion:)-1ilz1":{"url":"\/documentation\/mapboxmaps\/mapboxmap\/loadstyle(_:transition:completion:)-1ilz1","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadStyle","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps8StyleURIV","text":"StyleURI","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"transition","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps17TransitionOptionsV","text":"TransitionOptions","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"role":"symbol","title":"loadStyle(_:transition:completion:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/loadStyle(_:transition:completion:)-1ilz1","type":"topic","abstract":[{"type":"text","text":"Loads a "},{"code":"style","type":"codeVoice"},{"type":"text","text":" from a StyleURI, calling a completion closure when the"},{"type":"text","text":" "},{"type":"text","text":"style is fully loaded or there has been an error during load."}]}},"variantOverrides":[{"patch":[{"value":"MBMStyleImageRemoveUnused","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnused\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnused\/fragments","value":[{"kind":"identifier","text":"MBMStyleImageRemoveUnused"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageRemoveUnused\/navigatorTitle","value":[{"text":"MBMStyleImageRemoveUnused","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}