{"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/queryRenderedFeatures(with:options:completion:)","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap"],["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/MapboxMapProtocol-Implementations"]]},"abstract":[{"type":"text","text":"Queries the map for rendered features."}],"sections":[],"metadata":{"extendedModule":"MapboxMaps","title":"queryRenderedFeatures(with:options:completion:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"queryRenderedFeatures"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": some "},{"kind":"typeIdentifier","text":"RenderedQueryGeometryConvertible","preciseIdentifier":"s:10MapboxMaps32RenderedQueryGeometryConvertibleP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RenderedQueryOptions","preciseIdentifier":"c:objc(cs)MBMRenderedQueryOptions"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<["},{"kind":"typeIdentifier","text":"QueriedRenderedFeature","preciseIdentifier":"c:objc(cs)MBMQueriedRenderedFeature"},{"kind":"text","text":"], any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> any "},{"kind":"typeIdentifier","text":"Cancelable","preciseIdentifier":"c:objc(pl)MBXCancelable"}],"roleHeading":"Instance Method","modules":[{"name":"MapboxMaps"}],"symbolKind":"method","externalID":"s:10MapboxMaps0A3MapC21queryRenderedFeatures4with7options10completionSo13MBXCancelable_px_So23MBMRenderedQueryOptionsCSgys6ResultOySaySo010MBMQueriedE7FeatureCGs5Error_pGctAA0eL19GeometryConvertibleRzlF"},"seeAlsoSections":[{"generated":true,"title":"Querying map features","anchor":"Querying-map-features","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/getGeoJsonClusterLeaves(forSourceId:feature:limit:offset:completion:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/getGeoJsonClusterChildren(forSourceId:feature:completion:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/getGeoJsonClusterExpansionZoom(forSourceId:feature:completion:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@discardableResult","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"queryRenderedFeatures","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"geometry","kind":"internalParam"},{"text":": some ","kind":"text"},{"text":"RenderedQueryGeometryConvertible","preciseIdentifier":"s:10MapboxMaps32RenderedQueryGeometryConvertibleP","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometryConvertible"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MBMRenderedQueryOptions","kind":"typeIdentifier","text":"RenderedQueryOptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryOptions"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"keyword","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"text":"<[","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedRenderedFeature","text":"QueriedRenderedFeature","preciseIdentifier":"c:objc(cs)MBMQueriedRenderedFeature","kind":"typeIdentifier"},{"text":"], any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":") -> any ","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Cancelable","text":"Cancelable","preciseIdentifier":"c:objc(pl)MBXCancelable","kind":"typeIdentifier"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"geometry","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A screen geometry to query. Can be a "},{"type":"codeVoice","code":"CGPoint"},{"type":"text","text":", "},{"type":"codeVoice","code":"CGRect"},{"type":"text","text":", or an array of "},{"type":"codeVoice","code":"CGPoint"},{"type":"text","text":"."}]}]},{"name":"options","content":[{"inlineContent":[{"type":"text","text":"Options for querying rendered features."}],"type":"paragraph"}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Callback called when the query completes."}]}]}]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"inlineContent":[{"text":"The feature must be visible on screen to be queried. The ","type":"text"},{"type":"codeVoice","code":"geometry"},{"text":" defines a portion of the screen that should be queried. Thus, it must be a screen coordinate.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"If the "},{"type":"codeVoice","code":"geometry"},{"type":"text","text":" parameter is CGPoint, only that point is queried. When it’s a "},{"type":"codeVoice","code":"CGRect"},{"type":"text","text":" or an array of "},{"type":"codeVoice","code":"CGPoint"},{"type":"text","text":", the shape is queried."}],"type":"paragraph"},{"content":[{"inlineContent":[{"text":"If you need to handle basic gestures on map content, please prefer to use Interactions API (see ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/addInteraction(_:)","isActive":true,"type":"reference"},{"text":"). If you need to query a featureset from an imported style, use ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/queryRenderedFeatures(with:featureset:filter:completion:)","isActive":true,"type":"reference"},{"text":" instead.","type":"text"}],"type":"paragraph"}],"type":"aside","style":"important","name":"Important"}]}],"variants":[{"paths":["\/documentation\/mapboxmaps\/mapboxmap\/queryrenderedfeatures(with:options:completion:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/queryRenderedFeatures(with:options:completion:)":{"url":"\/documentation\/mapboxmaps\/mapboxmap\/queryrenderedfeatures(with:options:completion:)","title":"queryRenderedFeatures(with:options:completion:)","kind":"symbol","abstract":[{"text":"Queries the map for rendered features.","type":"text"}],"role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"queryRenderedFeatures","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": some ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps32RenderedQueryGeometryConvertibleP","text":"RenderedQueryGeometryConvertible","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMRenderedQueryOptions","text":"RenderedQueryOptions","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:s6ResultO","text":"Result","kind":"typeIdentifier"},{"text":"<[","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMQueriedRenderedFeature","text":"QueriedRenderedFeature","kind":"typeIdentifier"},{"text":"], any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":") -> any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)MBXCancelable","text":"Cancelable","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/queryRenderedFeatures(with:options:completion:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderedQueryGeometry":{"navigatorTitle":[{"text":"RenderedQueryGeometry","kind":"identifier"}],"type":"topic","title":"RenderedQueryGeometry","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RenderedQueryGeometry","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/renderedquerygeometry","kind":"symbol","abstract":[{"type":"text","text":"A geometry to define a portion of screen that should be queried for rendered features."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometry","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap":{"navigatorTitle":[{"kind":"identifier","text":"MapboxMap"}],"title":"MapboxMap","url":"\/documentation\/mapboxmaps\/mapboxmap","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","abstract":[{"type":"text","text":"Provides access to the map model, including the camera, style, observable map events,"},{"type":"text","text":" "},{"type":"text","text":"and querying rendered features."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapboxMap"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","kind":"article","title":"MapboxMaps Documentation","url":"\/documentation\/overview","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/addInteraction(_:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/addInteraction(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addInteraction","kind":"identifier"},{"text":"(some ","kind":"text"},{"text":"Interaction","preciseIdentifier":"s:10MapboxMaps11InteractionP","kind":"typeIdentifier"},{"text":") -> any ","kind":"text"},{"text":"Cancelable","preciseIdentifier":"c:objc(pl)MBXCancelable","kind":"typeIdentifier"}],"abstract":[{"text":"Adds interaction to the map.","type":"text"}],"url":"\/documentation\/mapboxmaps\/mapboxmap\/addinteraction(_:)","title":"addInteraction(_:)","role":"symbol","tags":[{"text":"SPI","type":"spi"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/QueriedRenderedFeature":{"role":"symbol","abstract":[{"text":"Represents query result that is returned in QueryRenderedFeaturesCallback.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedRenderedFeature","url":"\/documentation\/mapboxmaps\/queriedrenderedfeature","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"QueriedRenderedFeature","kind":"identifier"}],"title":"QueriedRenderedFeature","kind":"symbol","navigatorTitle":[{"text":"QueriedRenderedFeature","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/getGeoJsonClusterLeaves(forSourceId:feature:limit:offset:completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getGeoJsonClusterLeaves"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forSourceId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"feature"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10MapboxMaps7Featurea","kind":"typeIdentifier","text":"Feature"},{"kind":"text","text":", "},{"kind":"externalParam","text":"limit"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s6UInt64V","kind":"typeIdentifier","text":"UInt64"},{"kind":"text","text":", "},{"kind":"externalParam","text":"offset"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s6UInt64V","kind":"typeIdentifier","text":"UInt64"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"preciseIdentifier":"s:s6ResultO","kind":"typeIdentifier","text":"Result"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)MBMFeatureExtensionValue","kind":"typeIdentifier","text":"FeatureExtensionValue"},{"kind":"text","text":", any "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":">) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":") -> any "},{"preciseIdentifier":"c:objc(pl)MBXCancelable","kind":"typeIdentifier","text":"Cancelable"}],"abstract":[{"text":"Returns all the leaves (original points) of a cluster (given its cluster_id) from a GeoJSON source, with pagination support: limit is the number of leaves","type":"text"},{"text":" ","type":"text"},{"text":"to return (set to Infinity for all points), and offset is the amount of points to skip (for pagination).","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/getGeoJsonClusterLeaves(forSourceId:feature:limit:offset:completion:)","url":"\/documentation\/mapboxmaps\/mapboxmap\/getgeojsonclusterleaves(forsourceid:feature:limit:offset:completion:)","role":"symbol","title":"getGeoJsonClusterLeaves(forSourceId:feature:limit:offset:completion:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/getGeoJsonClusterChildren(forSourceId:feature:completion:)":{"type":"topic","title":"getGeoJsonClusterChildren(forSourceId:feature:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getGeoJsonClusterChildren","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forSourceId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"feature","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps7Featurea","text":"Feature","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:s6ResultO","text":"Result","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMFeatureExtensionValue","text":"FeatureExtensionValue","kind":"typeIdentifier"},{"text":", any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":") -> any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)MBXCancelable","text":"Cancelable","kind":"typeIdentifier"}],"url":"\/documentation\/mapboxmaps\/mapboxmap\/getgeojsonclusterchildren(forsourceid:feature:completion:)","kind":"symbol","abstract":[{"text":"Returns the children (original points or clusters) of a cluster (on the next zoom level)","type":"text"},{"text":" ","type":"text"},{"text":"given its id (cluster_id value from feature properties) from a GeoJSON source.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/getGeoJsonClusterChildren(forSourceId:feature:completion:)","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"role":"collection","kind":"symbol","url":"\/documentation\/mapboxmaps","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderedQueryGeometryConvertible":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RenderedQueryGeometryConvertible"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometryConvertible","navigatorTitle":[{"kind":"identifier","text":"RenderedQueryGeometryConvertible"}],"url":"\/documentation\/mapboxmaps\/renderedquerygeometryconvertible","title":"RenderedQueryGeometryConvertible","abstract":[{"text":"A convenience protocol for automatic conversion to ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometry","isActive":true,"type":"reference"},{"text":".","type":"text"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/queryRenderedFeatures(with:featureset:filter:completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"queryRenderedFeatures"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"G"},{"kind":"text","text":", "},{"kind":"genericParameter","text":"T"},{"kind":"text","text":">("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"G"},{"kind":"text","text":", "},{"kind":"externalParam","text":"featureset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FeaturesetDescriptor","preciseIdentifier":"s:10MapboxMaps20FeaturesetDescriptorV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"T"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"filter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Exp","preciseIdentifier":"s:10MapboxMaps3ExpV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<["},{"kind":"typeIdentifier","text":"T"},{"kind":"text","text":"], any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> any "},{"kind":"typeIdentifier","text":"Cancelable","preciseIdentifier":"c:objc(pl)MBXCancelable"}],"abstract":[{"type":"text","text":"Queries the map for rendered features with one typed featureset."}],"kind":"symbol","tags":[{"text":"SPI","type":"spi"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/queryRenderedFeatures(with:featureset:filter:completion:)","url":"\/documentation\/mapboxmaps\/mapboxmap\/queryrenderedfeatures(with:featureset:filter:completion:)","role":"symbol","title":"queryRenderedFeatures(with:featureset:filter:completion:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Cancelable":{"title":"Cancelable","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Cancelable"}],"kind":"symbol","url":"\/documentation\/mapboxcommon\/cancelable","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Cancelable"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Cancelable","abstract":[{"type":"text","text":"Allows to cancel the associated asynchronous operation"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"abstract":[],"role":"collectionGroup","title":"MapboxMap","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","kind":"article","url":"\/documentation\/mapboxmaps\/mapboxmap-apis","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderedQueryOptions":{"navigatorTitle":[{"text":"RenderedQueryOptions","kind":"identifier"}],"title":"RenderedQueryOptions","type":"topic","url":"\/documentation\/mapboxmaps\/renderedqueryoptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryOptions","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RenderedQueryOptions","kind":"identifier"}],"abstract":[{"type":"text","text":"Options for querying rendered features."}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/getGeoJsonClusterExpansionZoom(forSourceId:feature:completion:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/getGeoJsonClusterExpansionZoom(forSourceId:feature:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getGeoJsonClusterExpansionZoom"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forSourceId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"feature"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10MapboxMaps7Featurea","kind":"typeIdentifier","text":"Feature"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"preciseIdentifier":"s:s6ResultO","kind":"typeIdentifier","text":"Result"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)MBMFeatureExtensionValue","kind":"typeIdentifier","text":"FeatureExtensionValue"},{"kind":"text","text":", any "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":">) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":") -> any "},{"preciseIdentifier":"c:objc(pl)MBXCancelable","kind":"typeIdentifier","text":"Cancelable"}],"url":"\/documentation\/mapboxmaps\/mapboxmap\/getgeojsonclusterexpansionzoom(forsourceid:feature:completion:)","type":"topic","abstract":[{"text":"Returns the zoom on which the cluster expands into several children (useful for “click to zoom” feature)","type":"text"},{"text":" ","type":"text"},{"text":"given the cluster’s cluster_id (cluster_id value from feature properties) from a GeoJSON source.","type":"text"}],"title":"getGeoJsonClusterExpansionZoom(forSourceId:feature:completion:)","role":"symbol","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/MapboxMapProtocol-Implementations":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/MapboxMapProtocol-Implementations","abstract":[],"role":"collectionGroup","title":"MapboxMapProtocol Implementations","url":"\/documentation\/mapboxmaps\/mapboxmap\/mapboxmapprotocol-implementations","kind":"article"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedRenderedFeature\/title","value":"MBMQueriedRenderedFeature","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedRenderedFeature\/fragments","value":[{"text":"MBMQueriedRenderedFeature","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedRenderedFeature\/navigatorTitle","value":[{"kind":"identifier","text":"MBMQueriedRenderedFeature"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/title","value":"MBXCancelable","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/fragments","value":[{"text":"MBXCancelable","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/navigatorTitle","value":[{"text":"MBXCancelable","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderedQueryOptions\/title","value":"MBMRenderedQueryOptions","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderedQueryOptions\/fragments","value":[{"text":"MBMRenderedQueryOptions","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderedQueryOptions\/navigatorTitle","value":[{"text":"MBMRenderedQueryOptions","kind":"identifier"}],"op":"replace"}]}]}