{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionTilePyramidDefinition"]]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","abstract":[{"text":"The style associated with the offline region.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"styleURL"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/offlineregiontilepyramiddefinition\/styleurl"]},{"paths":["\/documentation\/mapboxmaps\/offlineregiontilepyramiddefinition\/styleurl"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"styleURL","roleHeading":"Instance Property","modules":[{"name":"MapboxMaps"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"styleURL"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"platforms":[],"role":"symbol","externalID":"c:objc(cs)MBMOfflineRegionTilePyramidDefinition(py)styleURL","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"styleURL"}]},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionTilePyramidDefinition\/styleURL","interfaceLanguage":"swift"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Offline":{"role":"collectionGroup","type":"topic","title":"Offline Support","kind":"article","url":"\/documentation\/mapboxmaps\/offline","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMaps":{"role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","kind":"article","url":"\/documentation\/mapboxmaps\/coremaps","title":"Core Maps API","abstract":[{"text":"Maps rendering SDK also known as GL-Native","type":"text"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionTilePyramidDefinition":{"url":"\/documentation\/mapboxmaps\/offlineregiontilepyramiddefinition","abstract":[{"text":"An offline region definition is a geographic region defined by a style URL,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"geographic bounding box, zoom range, and device pixel ratio. Both "},{"code":"minZoom","type":"codeVoice"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"maxZoom"},{"type":"text","text":" must be ≥ 0,"},{"text":" ","type":"text"},{"text":"and ","type":"text"},{"type":"codeVoice","code":"maxZoom"},{"text":" must be ≥ ","type":"text"},{"type":"codeVoice","code":"minZoom"},{"text":". The ","type":"text"},{"type":"codeVoice","code":"maxZoom"},{"type":"text","text":" may be ∞, in which case for each tile source,"},{"text":" ","type":"text"},{"text":"the region will include tiles from ","type":"text"},{"type":"codeVoice","code":"minZoom"},{"type":"text","text":" up to the maximum zoom level provided by that source."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"pixelRatio"},{"text":" must be ≥ 0 and should typically be 1.0 or 2.0.","type":"text"}],"navigatorTitle":[{"text":"OfflineRegionTilePyramidDefinition","kind":"identifier"}],"deprecated":true,"role":"symbol","title":"OfflineRegionTilePyramidDefinition","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OfflineRegionTilePyramidDefinition"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionTilePyramidDefinition"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","abstract":[],"title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","kind":"article","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","title":"MapboxMaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"role":"collection","url":"\/documentation\/mapboxmaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionTilePyramidDefinition/styleURL":{"url":"\/documentation\/mapboxmaps\/offlineregiontilepyramiddefinition\/styleurl","abstract":[{"text":"The style associated with the offline region.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"styleURL"}],"deprecated":true,"role":"symbol","title":"styleURL","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"styleURL","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionTilePyramidDefinition\/styleURL"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"styleURL","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"styleURL"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"styleURL"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"MBMOfflineRegionTilePyramidDefinition","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionTilePyramidDefinition\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBMOfflineRegionTilePyramidDefinition"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionTilePyramidDefinition\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionTilePyramidDefinition\/navigatorTitle","value":[{"kind":"identifier","text":"MBMOfflineRegionTilePyramidDefinition"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionTilePyramidDefinition~1styleURL\/title","op":"replace","value":"styleURL"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionTilePyramidDefinition~1styleURL\/fragments","value":[{"kind":"identifier","text":"styleURL"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}