{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderModeType"]]},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"full","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MBMRenderModeTypeFull"}],"symbolKind":"case","title":"RenderModeType.full","externalID":"c:@E@MBMRenderModeType@MBMRenderModeTypeFull","roleHeading":"Case","role":"symbol","modules":[{"name":"MapboxMaps"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderModeType\/full","interfaceLanguage":"swift"},"abstract":[{"text":"The ","type":"text"},{"code":"map","type":"codeVoice"},{"type":"text","text":" rendered the frame with all the required data."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/rendermodetype\/full"]},{"paths":["\/documentation\/mapboxmaps\/rendermodetype\/full"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"full","kind":"identifier"}],"platforms":["iOS"]}]}],"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","title":"MapboxMaps","kind":"symbol","role":"collection","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderModeType":{"title":"RenderModeType","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RenderModeType"}],"navigatorTitle":[{"text":"RenderModeType","kind":"identifier"}],"type":"topic","abstract":[{"text":"The enumeration defines the rendering mode for the rendered frame.","type":"text"}],"url":"\/documentation\/mapboxmaps\/rendermodetype","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderModeType"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderModeType/full":{"kind":"symbol","abstract":[{"type":"text","text":"The "},{"code":"map","type":"codeVoice"},{"text":" rendered the frame with all the required data.","type":"text"}],"title":"RenderModeType.full","url":"\/documentation\/mapboxmaps\/rendermodetype\/full","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderModeType\/full","navigatorTitle":[{"kind":"identifier","text":"MBMRenderModeTypeFull"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"full","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article","role":"collection","title":"MapboxMaps Documentation","type":"topic","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"abstract":[{"type":"text","text":"The simplified diagram of the events emitted by the map is displayed below."}],"type":"topic","kind":"article","role":"collectionGroup","title":"Map events","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","url":"\/documentation\/mapboxmaps\/events"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"MBMRenderModeTypeFull"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MBMRenderModeTypeFull","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"MBMRenderModeTypeFull","kind":"identifier"}]}]}},{"value":"MBMRenderModeType","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderModeType\/title"},{"value":[{"text":"MBMRenderModeType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderModeType\/fragments","op":"replace"},{"value":[{"text":"MBMRenderModeType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderModeType\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderModeType~1full\/title","value":"MBMRenderModeTypeFull","op":"replace"},{"op":"replace","value":[{"text":"MBMRenderModeTypeFull","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderModeType~1full\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}