{"metadata":{"title":"perFrameStatistics","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"perFrameStatistics"},{"kind":"text","text":": "},{"text":"PerFrameRenderingStatistics","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMPerFrameRenderingStatistics"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property","symbolKind":"property","role":"symbol","modules":[{"name":"MapboxMaps"}],"navigatorTitle":[{"kind":"identifier","text":"perFrameStatistics"}],"externalID":"c:objc(cs)MBMPerformanceStatistics(py)perFrameStatistics"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatistics"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Aggregated, per-frame, timings. Enable using the  ","type":"text"},{"type":"codeVoice","code":"PerFrameRenderingStats"},{"text":" performance sampler option.","type":"text"}],"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatistics\/perFrameStatistics","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/performancestatistics\/perframestatistics"]},{"paths":["\/documentation\/mapboxmaps\/performancestatistics\/perframestatistics"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"perFrameStatistics","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PerFrameRenderingStatistics","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMPerFrameRenderingStatistics","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerFrameRenderingStatistics"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PerformanceStatistics":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"The performance statistics collected at the end of the sampling duration."}],"title":"PerformanceStatistics","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatistics","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PerformanceStatistics"}],"navigatorTitle":[{"text":"PerformanceStatistics","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/performancestatistics","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PerformanceStatistics/perFrameStatistics":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatistics\/perFrameStatistics","title":"perFrameStatistics","type":"topic","abstract":[{"type":"text","text":"Aggregated, per-frame, timings. Enable using the  "},{"type":"codeVoice","code":"PerFrameRenderingStats"},{"type":"text","text":" performance sampler option."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"perFrameStatistics","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMPerFrameRenderingStatistics","text":"PerFrameRenderingStatistics"},{"kind":"text","text":"?"}],"url":"\/documentation\/mapboxmaps\/performancestatistics\/perframestatistics","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"perFrameStatistics","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","abstract":[],"type":"topic","kind":"article","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PerFrameRenderingStatistics":{"role":"symbol","type":"topic","abstract":[],"title":"PerFrameRenderingStatistics","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerFrameRenderingStatistics","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PerFrameRenderingStatistics"}],"navigatorTitle":[{"kind":"identifier","text":"PerFrameRenderingStatistics"}],"url":"\/documentation\/mapboxmaps\/perframerenderingstatistics","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"role":"collection","url":"\/documentation\/mapboxmaps","title":"MapboxMaps","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Performance":{"url":"\/documentation\/mapboxmaps\/performance","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","type":"topic","title":"Performance and investigations","abstract":[],"kind":"article"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"perFrameStatistics"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"perFrameStatistics"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerFrameRenderingStatistics","kind":"typeIdentifier","text":"MBMPerFrameRenderingStatistics","preciseIdentifier":"c:objc(cs)MBMPerFrameRenderingStatistics"},{"kind":"text","text":" * "},{"text":"perFrameStatistics","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"MBMPerformanceStatistics","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatistics\/title"},{"value":[{"text":"MBMPerformanceStatistics","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatistics\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MBMPerformanceStatistics"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatistics\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatistics~1perFrameStatistics\/title","value":"perFrameStatistics"},{"value":[{"text":"perFrameStatistics","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatistics~1perFrameStatistics\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerFrameRenderingStatistics\/title","op":"replace","value":"MBMPerFrameRenderingStatistics"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerFrameRenderingStatistics\/fragments","op":"replace","value":[{"text":"MBMPerFrameRenderingStatistics","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerFrameRenderingStatistics\/navigatorTitle","value":[{"text":"MBMPerFrameRenderingStatistics","kind":"identifier"}],"op":"replace"}]}]}