{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SwiftUI","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map"]]},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onSourceAdded(action:)","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"MapboxMaps"}],"extendedModule":"MapboxMaps","title":"onSourceAdded(action:)","role":"symbol","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSourceAdded"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMSourceAdded","text":"SourceAdded"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:10MapboxMaps3MapV","kind":"typeIdentifier","text":"Map"}],"externalID":"s:10MapboxMaps3MapV13onSourceAdded6actionACySo09MBMSourceF0Cc_tF"},"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Adds an action to perform when a source is added.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onSourceAdded","kind":"identifier"},{"text":"(","kind":"text"},{"text":"action","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"keyword"},{"text":" (","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceAdded","preciseIdentifier":"c:objc(cs)MBMSourceAdded","text":"SourceAdded","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map","preciseIdentifier":"s:10MapboxMaps3MapV","text":"Map","kind":"typeIdentifier"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/mapboxmaps\/map\/onsourceadded(action:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceAdded":{"navigatorTitle":[{"kind":"identifier","text":"SourceAdded"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceAdded"}],"title":"SourceAdded","abstract":[{"text":"The source has been added with ","type":"text"},{"code":"addStyleSource","type":"codeVoice"},{"text":" method.","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceAdded","type":"topic","url":"\/documentation\/mapboxmaps\/sourceadded"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/onSourceAdded(action:)":{"title":"onSourceAdded(action:)","type":"topic","url":"\/documentation\/mapboxmaps\/map\/onsourceadded(action:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onSourceAdded","kind":"identifier"},{"text":"(","kind":"text"},{"text":"action","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"SourceAdded","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMSourceAdded"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":") -> ","kind":"text"},{"text":"Map","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps3MapV"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Adds an action to perform when a source is added."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onSourceAdded(action:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SwiftUI":{"title":"SwiftUI","url":"\/documentation\/mapboxmaps\/swiftui","kind":"article","type":"topic","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SwiftUI"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map":{"url":"\/documentation\/mapboxmaps\/map","title":"Map","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Map","kind":"identifier"}],"navigatorTitle":[{"text":"Map","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map","abstract":[{"type":"text","text":"A SwiftUI view that displays a Mapbox Map."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","kind":"symbol","type":"topic","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","type":"topic","abstract":[],"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","url":"\/documentation\/overview"}},"variantOverrides":[{"patch":[{"op":"replace","value":"MBMSourceAdded","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAdded\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBMSourceAdded"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAdded\/fragments"},{"op":"replace","value":[{"text":"MBMSourceAdded","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceAdded\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}