{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore"]]},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore\/allTileRegions(completion:)","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Fetch the array of the existing tile regions."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/tilestore\/alltileregions(completion:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"allTileRegions"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"text":"@escaping","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"text":"<[","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBXTileRegion","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegion","text":"TileRegion","kind":"typeIdentifier"},{"kind":"text","text":"], any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"platforms":["iOS"]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The result callback. Any "},{"type":"codeVoice","code":"Result"},{"type":"text","text":" error should be"},{"type":"text","text":" "},{"type":"text","text":"of type "},{"type":"codeVoice","code":"TileRegionError"},{"type":"text","text":"."}],"type":"paragraph"}],"name":"completion"}],"kind":"parameters"}],"metadata":{"extendedModule":"MapboxCommon","modules":[{"name":"MapboxCommon"}],"title":"allTileRegions(completion:)","symbolKind":"method","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"allTileRegions"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO","text":"Result"},{"kind":"text","text":"<["},{"text":"TileRegion","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXTileRegion"},{"kind":"text","text":"], any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":">) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"externalID":"s:So12MBXTileStoreC10MapboxMapsE14allTileRegions10completionyys6ResultOySaySo0A6RegionCGs5Error_pGc_tF","role":"symbol"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileStore/allTileRegions(completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"allTileRegions"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO","text":"Result"},{"kind":"text","text":"<["},{"kind":"typeIdentifier","text":"TileRegion","preciseIdentifier":"c:objc(cs)MBXTileRegion"},{"text":"], any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":">) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore\/allTileRegions(completion:)","url":"\/documentation\/mapboxcommon\/tilestore\/alltileregions(completion:)","abstract":[{"type":"text","text":"Fetch the array of the existing tile regions."}],"kind":"symbol","title":"allTileRegions(completion:)","type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileStore":{"navigatorTitle":[{"kind":"identifier","text":"TileStore"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore","type":"topic","kind":"symbol","url":"\/documentation\/mapboxcommon\/tilestore","abstract":[{"text":"TileStore manages downloads and storage for requests to tile-related API endpoints, enforcing a disk usage","type":"text"},{"text":" ","type":"text"},{"text":"quota: tiles available on disk may be deleted to make room for a new download. This interface can be used by an","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"app developer to set the disk quota. The rest of TileStore API is intended for native SDK consumption only."}],"title":"TileStore","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileStore"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"kind":"article","type":"topic","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","abstract":[],"url":"\/documentation\/mapboxmaps\/tilestore-apis","title":"TileStore APIs"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","role":"collection","title":"MapboxMaps Documentation","abstract":[],"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","kind":"symbol","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegion":{"type":"topic","abstract":[{"type":"text","text":"TileRegion represents an identifiable geographic tile region with metadata"}],"url":"\/documentation\/mapboxcommon\/tileregion","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegion","title":"TileRegion","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileRegion","kind":"identifier"}],"navigatorTitle":[{"text":"TileRegion","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MBXTileStore","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/fragments","value":[{"text":"MBXTileStore","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MBXTileStore"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/navigatorTitle","op":"replace"},{"value":"MBXTileRegion","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegion\/title"},{"value":[{"kind":"identifier","text":"MBXTileRegion"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegion\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MBXTileRegion"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegion\/navigatorTitle"}]}]}