{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"requiredResourceCount"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s6UInt64V","kind":"typeIdentifier","text":"UInt64"},{"text":", ","kind":"text"},{"text":"erroredResourceCount","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V","text":"UInt64"},{"kind":"text","text":", "},{"text":"completedResourceCount","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s6UInt64V","text":"UInt64","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"partialResult"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateResult","text":"TileRegionEstimateResult","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXTileRegionEstimateResult"},{"kind":"text","text":")"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/tileregionestimateprogress\/init(requiredresourcecount:erroredresourcecount:completedresourcecount:partialresult:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/tileregionestimateprogress\/init(requiredresourcecount:erroredresourcecount:completedresourcecount:partialresult:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgress\/init(requiredResourceCount:erroredResourceCount:completedResourceCount:partialResult:)"},"sections":[],"metadata":{"modules":[{"name":"MapboxCommon"}],"navigatorTitle":[{"kind":"identifier","text":"initWithRequiredResourceCount:erroredResourceCount:completedResourceCount:partialResult:"}],"externalID":"c:objc(cs)MBXTileRegionEstimateProgress(im)initWithRequiredResourceCount:erroredResourceCount:completedResourceCount:partialResult:","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"requiredResourceCount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt64","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"erroredResourceCount"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s6UInt64V","text":"UInt64","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completedResourceCount","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s6UInt64V","kind":"typeIdentifier","text":"UInt64"},{"kind":"text","text":", "},{"text":"partialResult","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBXTileRegionEstimateResult","text":"TileRegionEstimateResult","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"init(requiredResourceCount:erroredResourceCount:completedResourceCount:partialResult:)","symbolKind":"init","roleHeading":"Initializer"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgress"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","kind":"article","title":"MapboxMaps Documentation","abstract":[],"role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"abstract":[],"url":"\/documentation\/mapboxmaps\/tilestore-apis","type":"topic","title":"TileStore APIs","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateResult":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileRegionEstimateResult","kind":"identifier"}],"abstract":[{"type":"text","text":"The result of tile region estim"}],"title":"TileRegionEstimateResult","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateResult","url":"\/documentation\/mapboxcommon\/tileregionestimateresult","role":"symbol","navigatorTitle":[{"text":"TileRegionEstimateResult","kind":"identifier"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateProgress":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TileRegionEstimateProgress","kind":"identifier"}],"abstract":[{"type":"text","text":"A tile region’s estimate progress includes counts of the number of resources that have"},{"type":"text","text":" "},{"type":"text","text":"been estimated and the total number of resources as well as a partial result with the"},{"type":"text","text":" "},{"text":"current estimate, calculated using the data available at the moment.","type":"text"}],"title":"TileRegionEstimateProgress","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgress","url":"\/documentation\/mapboxcommon\/tileregionestimateprogress","role":"symbol","navigatorTitle":[{"text":"TileRegionEstimateProgress","kind":"identifier"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateProgress/init(requiredResourceCount:erroredResourceCount:completedResourceCount:partialResult:)":{"abstract":[],"navigatorTitle":[{"text":"initWithRequiredResourceCount:erroredResourceCount:completedResourceCount:partialResult:","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/tileregionestimateprogress\/init(requiredresourcecount:erroredresourcecount:completedresourcecount:partialresult:)","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgress\/init(requiredResourceCount:erroredResourceCount:completedResourceCount:partialResult:)","role":"symbol","kind":"symbol","title":"init(requiredResourceCount:erroredResourceCount:completedResourceCount:partialResult:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"requiredResourceCount","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt64","preciseIdentifier":"s:s6UInt64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"erroredResourceCount"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s6UInt64V","text":"UInt64","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completedResourceCount"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s6UInt64V","kind":"typeIdentifier","text":"UInt64"},{"kind":"text","text":", "},{"kind":"externalParam","text":"partialResult"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TileRegionEstimateResult","preciseIdentifier":"c:objc(cs)MBXTileRegionEstimateResult"},{"kind":"text","text":")"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithRequiredResourceCount:erroredResourceCount:completedResourceCount:partialResult:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithRequiredResourceCount:erroredResourceCount:completedResourceCount:partialResult:"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithRequiredResourceCount:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"uint64_t","preciseIdentifier":"c:@T@uint64_t"},{"text":") ","kind":"text"},{"text":"requiredResourceCount","kind":"internalParam"},{"kind":"text","text":" "},{"text":"erroredResourceCount:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"uint64_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@uint64_t"},{"kind":"text","text":") "},{"kind":"internalParam","text":"erroredResourceCount"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completedResourceCount:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@uint64_t","kind":"typeIdentifier","text":"uint64_t"},{"text":") ","kind":"text"},{"text":"completedResourceCount","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"partialResult:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateResult","preciseIdentifier":"c:objc(cs)MBXTileRegionEstimateResult","text":"MBXTileRegionEstimateResult"},{"text":" *) ","kind":"text"},{"text":"partialResult","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"MBXTileRegionEstimateResult","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateResult\/title","op":"replace"},{"value":[{"text":"MBXTileRegionEstimateResult","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateResult\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateResult\/navigatorTitle","value":[{"text":"MBXTileRegionEstimateResult","kind":"identifier"}]},{"op":"replace","value":"MBXTileRegionEstimateProgress","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgress\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgress\/fragments","value":[{"text":"MBXTileRegionEstimateProgress","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgress\/navigatorTitle","op":"replace","value":[{"text":"MBXTileRegionEstimateProgress","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgress~1init(requiredResourceCount:erroredResourceCount:completedResourceCount:partialResult:)\/title","op":"replace","value":"initWithRequiredResourceCount:erroredResourceCount:completedResourceCount:partialResult:"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgress~1init(requiredResourceCount:erroredResourceCount:completedResourceCount:partialResult:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithRequiredResourceCount:erroredResourceCount:completedResourceCount:partialResult:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}