{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"subscribe","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"observer","kind":"internalParam"},{"kind":"text","text":": any "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreObserver","preciseIdentifier":"s:10MapboxMaps17TileStoreObserverP","kind":"typeIdentifier","text":"TileStoreObserver"},{"kind":"text","text":") -> any "},{"kind":"typeIdentifier","text":"Cancelable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Cancelable","preciseIdentifier":"c:objc(pl)MBXCancelable"}]}]},{"kind":"parameters","parameters":[{"name":"observer","content":[{"type":"paragraph","inlineContent":[{"text":"The object to be notified when events occur. TileStore holds a strong reference to this object until the subscription is canceled.","type":"text"}]}]}]},{"content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"inlineContent":[{"type":"text","text":"An object that can be used to cancel the subscription."}],"type":"paragraph"}],"kind":"content"}],"abstract":[{"text":"Allows observing a tile store’s activity","type":"text"}],"metadata":{"role":"symbol","modules":[{"name":"MapboxCommon"}],"roleHeading":"Instance Method","extendedModule":"MapboxCommon","externalID":"s:So12MBXTileStoreC10MapboxMapsE9subscribeySo13MBXCancelable_pAC04TileB8Observer_pF","title":"subscribe(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"subscribe"},{"kind":"text","text":"(any "},{"text":"TileStoreObserver","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps17TileStoreObserverP"},{"text":") -> any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)MBXCancelable","text":"Cancelable","kind":"typeIdentifier"}],"symbolKind":"method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore\/subscribe(_:)"},"variants":[{"paths":["\/documentation\/mapboxcommon\/tilestore\/subscribe(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore"]]},"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileStore/subscribe(_:)":{"kind":"symbol","abstract":[{"text":"Allows observing a tile store’s activity","type":"text"}],"role":"symbol","type":"topic","url":"\/documentation\/mapboxcommon\/tilestore\/subscribe(_:)","title":"subscribe(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"subscribe","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"TileStoreObserver","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps17TileStoreObserverP"},{"kind":"text","text":") -> any "},{"preciseIdentifier":"c:objc(pl)MBXCancelable","kind":"typeIdentifier","text":"Cancelable"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore\/subscribe(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","title":"MapboxMaps","kind":"symbol","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","type":"topic","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","abstract":[],"role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStoreObserver":{"navigatorTitle":[{"text":"TileStoreObserver","kind":"identifier"}],"kind":"symbol","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"TileStoreObserver","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxmaps\/tilestoreobserver","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreObserver","role":"symbol","title":"TileStoreObserver"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"url":"\/documentation\/mapboxmaps\/tilestore-apis","title":"TileStore APIs","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","kind":"article","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileStore":{"navigatorTitle":[{"text":"TileStore","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"TileStore manages downloads and storage for requests to tile-related API endpoints, enforcing a disk usage"},{"text":" ","type":"text"},{"type":"text","text":"quota: tiles available on disk may be deleted to make room for a new download. This interface can be used by an"},{"type":"text","text":" "},{"text":"app developer to set the disk quota. The rest of TileStore API is intended for native SDK consumption only.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileStore","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxcommon\/tilestore","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore","role":"symbol","title":"TileStore"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Cancelable":{"abstract":[{"text":"Allows to cancel the associated asynchronous operation","type":"text"}],"navigatorTitle":[{"text":"Cancelable","kind":"identifier"}],"title":"Cancelable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Cancelable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Cancelable","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapboxcommon\/cancelable","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"MBXTileStore","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/fragments","value":[{"text":"MBXTileStore","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/navigatorTitle","value":[{"text":"MBXTileStore","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/title","value":"MBXCancelable"},{"value":[{"text":"MBXCancelable","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/navigatorTitle","op":"replace","value":[{"text":"MBXCancelable","kind":"identifier"}]}]}]}