{"metadata":{"modules":[{"name":"MapboxMaps"}],"role":"symbol","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"allGlyphsRasterizedLocally","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MBMGlyphsRasterizationModeAllGlyphsRasterizedLocally"}],"title":"GlyphsRasterizationMode.allGlyphsRasterizedLocally","symbolKind":"case","externalID":"c:@E@MBMGlyphsRasterizationMode@MBMGlyphsRasterizationModeAllGlyphsRasterizedLocally"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-View","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode"],["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode\/allGlyphsRasterizedLocally"},"abstract":[{"type":"text","text":"All glyphs are rasterized locally. No glyphs are loaded from the server."}],"kind":"symbol","variants":[{"paths":["\/documentation\/mapboxmaps\/glyphsrasterizationmode\/allglyphsrasterizedlocally"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/glyphsrasterizationmode\/allglyphsrasterizedlocally"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"allGlyphsRasterizedLocally"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","title":"MapboxMaps","type":"topic","url":"\/documentation\/mapboxmaps","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map-View":{"title":"MapView","kind":"article","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/map-view","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-View","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"kind":"article","url":"\/documentation\/overview","role":"collection","title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GlyphsRasterizationMode":{"type":"topic","role":"symbol","kind":"symbol","title":"GlyphsRasterizationMode","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode","abstract":[{"type":"text","text":"Describes glyphs rasterization modes."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"GlyphsRasterizationMode","kind":"identifier"}],"navigatorTitle":[{"text":"GlyphsRasterizationMode","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/glyphsrasterizationmode"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GlyphsRasterizationMode/allGlyphsRasterizedLocally":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode\/allGlyphsRasterizedLocally","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"allGlyphsRasterizedLocally"}],"navigatorTitle":[{"text":"MBMGlyphsRasterizationModeAllGlyphsRasterizedLocally","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxmaps\/glyphsrasterizationmode\/allglyphsrasterizedlocally","title":"GlyphsRasterizationMode.allGlyphsRasterizedLocally","abstract":[{"type":"text","text":"All glyphs are rasterized locally. No glyphs are loaded from the server."}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"kind":"article","title":"MapboxMap","role":"collectionGroup","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","url":"\/documentation\/mapboxmaps\/mapboxmap-apis"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"value":"MBMGlyphsRasterizationModeAllGlyphsRasterizedLocally","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"text":"MBMGlyphsRasterizationModeAllGlyphsRasterizedLocally","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"MBMGlyphsRasterizationModeAllGlyphsRasterizedLocally"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"MBMGlyphsRasterizationMode","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/fragments","value":[{"kind":"identifier","text":"MBMGlyphsRasterizationMode"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/navigatorTitle","op":"replace","value":[{"text":"MBMGlyphsRasterizationMode","kind":"identifier"}]},{"op":"replace","value":"MBMGlyphsRasterizationModeAllGlyphsRasterizedLocally","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode~1allGlyphsRasterizedLocally\/title"},{"op":"replace","value":[{"text":"MBMGlyphsRasterizationModeAllGlyphsRasterizedLocally","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode~1allGlyphsRasterizedLocally\/fragments"}]}]}