{"abstract":[{"type":"text","text":"Size of the tiles. Tile size must be a power of 2. Default is "},{"type":"codeVoice","code":"512"},{"type":"text","text":"."}],"sections":[],"variants":[{"paths":["\/documentation\/mapboxmaps\/customrastersourceoptions\/tilesize"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/customrastersourceoptions\/tilesize"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tileSize","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s6UInt16V","text":"UInt16","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tileSize"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s6UInt16V","kind":"typeIdentifier","text":"UInt16"}],"navigatorTitle":[{"kind":"identifier","text":"tileSize"}],"title":"tileSize","symbolKind":"property","modules":[{"name":"MapboxMaps"}],"externalID":"c:objc(cs)MBMCustomRasterSourceOptions(py)tileSize","roleHeading":"Instance Property"},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions\/tileSize","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Sources":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources","abstract":[],"role":"collectionGroup","type":"topic","kind":"article","title":"Sources","url":"\/documentation\/mapboxmaps\/sources"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"title":"MapboxMaps Documentation","type":"topic","kind":"article","role":"collection","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceOptions/tileSize":{"kind":"symbol","role":"symbol","title":"tileSize","type":"topic","url":"\/documentation\/mapboxmaps\/customrastersourceoptions\/tilesize","abstract":[{"text":"Size of the tiles. Tile size must be a power of 2. Default is ","type":"text"},{"code":"512","type":"codeVoice"},{"text":".","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tileSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt16","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt16V"}],"navigatorTitle":[{"text":"tileSize","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions\/tileSize"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","title":"MapboxMaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"url":"\/documentation\/mapboxmaps","kind":"symbol","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceOptions":{"role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomRasterSourceOptions"}],"abstract":[{"type":"text","text":"Options for custom raster source."}],"navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceOptions"}],"title":"CustomRasterSourceOptions","url":"\/documentation\/mapboxmaps\/customrastersourceoptions"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"tileSize"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"tileSize","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"uint16_t","preciseIdentifier":"c:@T@uint16_t"},{"kind":"text","text":" "},{"kind":"identifier","text":"tileSize"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions~1tileSize\/title","op":"replace","value":"tileSize"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions~1tileSize\/fragments","op":"replace","value":[{"kind":"identifier","text":"tileSize"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/title","op":"replace","value":"MBMCustomRasterSourceOptions"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/fragments","op":"replace","value":[{"text":"MBMCustomRasterSourceOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/navigatorTitle","op":"replace","value":[{"text":"MBMCustomRasterSourceOptions","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}