{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"rateLimit","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/offlineregionerrortype\/ratelimit"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/offlineregionerrortype\/ratelimit"]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionErrorType\/rateLimit","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The error happened because of a rate limit."}],"metadata":{"symbolKind":"case","roleHeading":"Case","modules":[{"name":"MapboxMaps"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rateLimit","kind":"identifier"}],"platforms":[],"role":"symbol","title":"OfflineRegionErrorType.rateLimit","externalID":"c:@E@MBMOfflineRegionErrorType@MBMOfflineRegionErrorTypeRateLimit","navigatorTitle":[{"text":"MBMOfflineRegionErrorTypeRateLimit","kind":"identifier"}]},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionErrorType"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Offline":{"kind":"article","abstract":[],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","title":"Offline Support","url":"\/documentation\/mapboxmaps\/offline","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","type":"topic","title":"MapboxMaps Documentation","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionErrorType":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OfflineRegionErrorType","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionErrorType","role":"symbol","abstract":[{"text":"Describes the reason for an offline request response error.","type":"text"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/offlineregionerrortype","type":"topic","deprecated":true,"title":"OfflineRegionErrorType","navigatorTitle":[{"kind":"identifier","text":"OfflineRegionErrorType"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMaps":{"title":"Core Maps API","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","type":"topic","abstract":[{"text":"Maps rendering SDK also known as GL-Native","type":"text"}],"url":"\/documentation\/mapboxmaps\/coremaps","kind":"article","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","title":"MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","role":"collection","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionErrorType/rateLimit":{"url":"\/documentation\/mapboxmaps\/offlineregionerrortype\/ratelimit","title":"OfflineRegionErrorType.rateLimit","type":"topic","abstract":[{"type":"text","text":"The error happened because of a rate limit."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionErrorType\/rateLimit","navigatorTitle":[{"text":"MBMOfflineRegionErrorTypeRateLimit","kind":"identifier"}],"deprecated":true,"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"rateLimit","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"MBMOfflineRegionErrorTypeRateLimit","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"MBMOfflineRegionErrorTypeRateLimit","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"MBMOfflineRegionErrorTypeRateLimit"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionErrorType\/title","value":"MBMOfflineRegionErrorType"},{"op":"replace","value":[{"text":"MBMOfflineRegionErrorType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionErrorType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionErrorType\/navigatorTitle","value":[{"kind":"identifier","text":"MBMOfflineRegionErrorType"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionErrorType~1rateLimit\/title","value":"MBMOfflineRegionErrorTypeRateLimit","op":"replace"},{"value":[{"text":"MBMOfflineRegionErrorTypeRateLimit","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionErrorType~1rateLimit\/fragments"}]}]}