{"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"server"}]}],"kind":"declarations"}],"kind":"symbol","abstract":[{"type":"text","text":"The server error."}],"variants":[{"paths":["\/documentation\/mapboxmaps\/offlineregionerrortype\/server"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/offlineregionerrortype\/server"]}],"metadata":{"title":"OfflineRegionErrorType.server","modules":[{"name":"MapboxMaps"}],"platforms":[],"symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"server","kind":"identifier"}],"role":"symbol","externalID":"c:@E@MBMOfflineRegionErrorType@MBMOfflineRegionErrorTypeServer","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"MBMOfflineRegionErrorTypeServer"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionErrorType"]]},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionErrorType\/server","interfaceLanguage":"swift"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Offline":{"url":"\/documentation\/mapboxmaps\/offline","type":"topic","kind":"article","title":"Offline Support","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","abstract":[],"role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionErrorType":{"url":"\/documentation\/mapboxmaps\/offlineregionerrortype","kind":"symbol","type":"topic","abstract":[{"text":"Describes the reason for an offline request response error.","type":"text"}],"deprecated":true,"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OfflineRegionErrorType"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionErrorType","navigatorTitle":[{"kind":"identifier","text":"OfflineRegionErrorType"}],"title":"OfflineRegionErrorType"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionErrorType/server":{"url":"\/documentation\/mapboxmaps\/offlineregionerrortype\/server","title":"OfflineRegionErrorType.server","deprecated":true,"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"server","kind":"identifier"}],"abstract":[{"type":"text","text":"The server error."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionErrorType\/server","role":"symbol","type":"topic","navigatorTitle":[{"text":"MBMOfflineRegionErrorTypeServer","kind":"identifier"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","kind":"article","type":"topic","url":"\/documentation\/overview","title":"MapboxMaps Documentation","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","type":"topic","title":"Core Maps API","role":"collectionGroup","abstract":[{"type":"text","text":"Maps rendering SDK also known as GL-Native"}],"url":"\/documentation\/mapboxmaps\/coremaps","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","role":"collection","title":"MapboxMaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"MBMOfflineRegionErrorTypeServer","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MBMOfflineRegionErrorTypeServer"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"MBMOfflineRegionErrorTypeServer"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"value":"MBMOfflineRegionErrorType","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionErrorType\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionErrorType\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMOfflineRegionErrorType"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionErrorType\/navigatorTitle","value":[{"text":"MBMOfflineRegionErrorType","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionErrorType~1server\/title","value":"MBMOfflineRegionErrorTypeServer"},{"op":"replace","value":[{"kind":"identifier","text":"MBMOfflineRegionErrorTypeServer"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionErrorType~1server\/fragments"}]}]}