{"abstract":[{"type":"text","text":"Keep compression flag. If set, responses will not be automatically decompressed."},{"type":"text","text":" "},{"text":"Currently this mechanism is deprecated, for mapbox servers use custom X-Accept-Encoding.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestFlags"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keepCompression","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s6UInt32V","text":"UInt32","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"metadata":{"title":"keepCompression","externalID":"c:objc(cs)MBXHttpRequestFlags(cpy)KeepCompression","symbolKind":"property","modules":[{"name":"MapboxCommon"}],"roleHeading":"Type Property","navigatorTitle":[{"kind":"identifier","text":"KeepCompression"}],"platforms":[],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"keepCompression"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s6UInt32V","kind":"typeIdentifier","text":"UInt32"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestFlags\/keepCompression"},"variants":[{"paths":["\/documentation\/mapboxcommon\/httprequestflags\/keepcompression"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/httprequestflags\/keepcompression"]}],"kind":"symbol","sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestFlags/keepCompression":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestFlags\/keepCompression","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"keepCompression"},{"kind":"text","text":": "},{"text":"UInt32","preciseIdentifier":"s:s6UInt32V","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"KeepCompression"}],"url":"\/documentation\/mapboxcommon\/httprequestflags\/keepcompression","title":"keepCompression","abstract":[{"text":"Keep compression flag. If set, responses will not be automatically decompressed.","type":"text"},{"type":"text","text":" "},{"text":"Currently this mechanism is deprecated, for mapbox servers use custom X-Accept-Encoding.","type":"text"}],"role":"symbol","deprecated":true},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","type":"topic","url":"\/documentation\/mapboxcommon","title":"MapboxCommon","role":"collection","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestFlags":{"abstract":[],"url":"\/documentation\/mapboxcommon\/httprequestflags","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"HttpRequestFlags","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"HttpRequestFlags"}],"type":"topic","role":"symbol","title":"HttpRequestFlags","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestFlags","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","title":"MapboxMaps Documentation","type":"topic","kind":"article","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/platforms","value":[],"op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Property","op":"replace"},{"op":"replace","value":"KeepCompression","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"KeepCompression"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@uint32_t","kind":"typeIdentifier","text":"uint32_t"},{"text":" ","kind":"text"},{"kind":"identifier","text":"KeepCompression"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"KeepCompression","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestFlags~1keepCompression\/title"},{"value":[{"text":"KeepCompression","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestFlags~1keepCompression\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestFlags\/title","op":"replace","value":"MBXHttpRequestFlags"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestFlags\/fragments","value":[{"text":"MBXHttpRequestFlags","kind":"identifier"}],"op":"replace"},{"value":[{"text":"MBXHttpRequestFlags","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestFlags\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}