{"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"metadata":{"title":"depthRange","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"depthRange"}],"externalID":"c:objc(cs)MBMCustomLayerRenderParameters(py)depthRange","modules":[{"name":"MapboxMaps"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"depthRange"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MBMDepthRange","kind":"typeIdentifier","text":"DepthRange"}],"roleHeading":"Instance Property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"depthRange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/DepthRange","text":"DepthRange","preciseIdentifier":"c:objc(cs)MBMDepthRange"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters\/depthRange","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters"]]},"abstract":[{"type":"text","text":"Depth range used to render 3D content. The default range is [0, 1] but it might vary based on the active features such as terrain and map projection."}],"variants":[{"paths":["\/documentation\/mapboxmaps\/customlayerrenderparameters\/depthrange"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/customlayerrenderparameters\/depthrange"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerRenderParameters":{"abstract":[{"type":"text","text":"Parameters that define the current camera position for a "},{"type":"codeVoice","code":"CustomLayerHost::render()"},{"type":"text","text":" function."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CustomLayerRenderParameters"}],"title":"CustomLayerRenderParameters","url":"\/documentation\/mapboxmaps\/customlayerrenderparameters","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomLayerRenderParameters"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","role":"collection","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","type":"topic","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layers":{"role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers","type":"topic","abstract":[],"title":"Layers","url":"\/documentation\/mapboxmaps\/layers","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","role":"collection","type":"topic","abstract":[],"title":"MapboxMaps Documentation","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/DepthRange":{"navigatorTitle":[{"text":"DepthRange","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DepthRange","kind":"identifier"}],"title":"DepthRange","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/depthrange","abstract":[{"text":"Represents depth range (min & max) used to render 3D content.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/DepthRange"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerRenderParameters/depthRange":{"url":"\/documentation\/mapboxmaps\/customlayerrenderparameters\/depthrange","abstract":[{"type":"text","text":"Depth range used to render 3D content. The default range is [0, 1] but it might vary based on the active features such as terrain and map projection."}],"title":"depthRange","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"depthRange"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"depthRange"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MBMDepthRange","kind":"typeIdentifier","text":"DepthRange"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters\/depthRange"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"depthRange"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"depthRange","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"MBMDepthRange","preciseIdentifier":"c:objc(cs)MBMDepthRange","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/DepthRange"},{"text":" * ","kind":"text"},{"text":"depthRange","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"MBMCustomLayerRenderParameters","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/title"},{"value":[{"kind":"identifier","text":"MBMCustomLayerRenderParameters"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/fragments"},{"value":[{"text":"MBMCustomLayerRenderParameters","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/navigatorTitle"},{"value":"MBMDepthRange","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1DepthRange\/title"},{"value":[{"text":"MBMDepthRange","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1DepthRange\/fragments"},{"value":[{"text":"MBMDepthRange","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1DepthRange\/navigatorTitle"},{"value":"depthRange","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters~1depthRange\/title"},{"value":[{"text":"depthRange","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters~1depthRange\/fragments"}]}]}