{"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"This constructor is internal and to be used from within Mapbox SDK only.","type":"text"}]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/customlayerrenderparameters\/init(width:height:latitude:longitude:zoom:bearing:pitch:fieldofview:projectionmatrix:depthrange:elevationdata:rendertotilesids:projection:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/customlayerrenderparameters\/init(width:height:latitude:longitude:zoom:bearing:pitch:fieldofview:projectionmatrix:depthrange:elevationdata:rendertotilesids:projection:)"]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters"]]},"sections":[],"metadata":{"modules":[{"name":"MapboxMaps"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"width","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"height","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"latitude","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"longitude","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"zoom","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"bearing","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"pitch","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"fieldOfView","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"projectionMatrix","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"depthRange","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMDepthRange","text":"DepthRange","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"elevationData","kind":"externalParam"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)MBMElevationData","text":"ElevationData","kind":"typeIdentifier"},{"text":")?, ","kind":"text"},{"text":"renderToTilesIDs","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMCanonicalTileID","text":"CanonicalTileID","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"text":"projection","kind":"externalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)MBMCustomLayerMapProjection","text":"CustomLayerMapProjection","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","title":"init(width:height:latitude:longitude:zoom:bearing:pitch:fieldOfView:projectionMatrix:depthRange:elevationData:renderToTilesIDs:projection:)","navigatorTitle":[{"text":"initWithWidth:height:latitude:longitude:zoom:bearing:pitch:fieldOfView:projectionMatrix:depthRange:elevationData:renderToTilesIDs:projection:","kind":"identifier"}],"roleHeading":"Initializer","symbolKind":"init","platforms":[],"externalID":"c:objc(cs)MBMCustomLayerRenderParameters(im)initWithWidth:height:latitude:longitude:zoom:bearing:pitch:fieldOfView:projectionMatrix:depthRange:elevationData:renderToTilesIDs:projection:"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"width"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"height"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"latitude"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"longitude"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":", ","kind":"text"},{"text":"zoom","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"text":"bearing","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"text":"pitch","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"text":"fieldOfView","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"text":"projectionMatrix","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"], ","kind":"text"},{"text":"depthRange","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DepthRange","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/DepthRange","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMDepthRange"},{"text":", ","kind":"text"},{"text":"elevationData","kind":"externalParam"},{"text":": (any ","kind":"text"},{"text":"ElevationData","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ElevationData","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MBMElevationData"},{"text":")?, ","kind":"text"},{"text":"renderToTilesIDs","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"CanonicalTileID","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMCanonicalTileID"},{"text":"]?, ","kind":"text"},{"text":"projection","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"CustomLayerMapProjection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerMapProjection","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MBMCustomLayerMapProjection"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters\/init(width:height:latitude:longitude:zoom:bearing:pitch:fieldOfView:projectionMatrix:depthRange:elevationData:renderToTilesIDs:projection:)"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layers":{"role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers","type":"topic","abstract":[],"title":"Layers","url":"\/documentation\/mapboxmaps\/layers","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ElevationData":{"title":"ElevationData","abstract":[{"text":"Interface that provides access to elevation data.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ElevationData","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"ElevationData","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/elevationdata","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ElevationData","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerRenderParameters":{"abstract":[{"type":"text","text":"Parameters that define the current camera position for a "},{"type":"codeVoice","code":"CustomLayerHost::render()"},{"type":"text","text":" function."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CustomLayerRenderParameters"}],"title":"CustomLayerRenderParameters","url":"\/documentation\/mapboxmaps\/customlayerrenderparameters","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomLayerRenderParameters"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","role":"collection","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","type":"topic","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/DepthRange":{"navigatorTitle":[{"text":"DepthRange","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DepthRange","kind":"identifier"}],"title":"DepthRange","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/depthrange","abstract":[{"text":"Represents depth range (min & max) used to render 3D content.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/DepthRange"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerRenderParameters/init(width:height:latitude:longitude:zoom:bearing:pitch:fieldOfView:projectionMatrix:depthRange:elevationData:renderToTilesIDs:projection:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters\/init(width:height:latitude:longitude:zoom:bearing:pitch:fieldOfView:projectionMatrix:depthRange:elevationData:renderToTilesIDs:projection:)","deprecated":true,"title":"init(width:height:latitude:longitude:zoom:bearing:pitch:fieldOfView:projectionMatrix:depthRange:elevationData:renderToTilesIDs:projection:)","url":"\/documentation\/mapboxmaps\/customlayerrenderparameters\/init(width:height:latitude:longitude:zoom:bearing:pitch:fieldofview:projectionmatrix:depthrange:elevationdata:rendertotilesids:projection:)","kind":"symbol","type":"topic","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"width","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"height","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"latitude","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"longitude","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"zoom","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"bearing","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"pitch","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"fieldOfView","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"projectionMatrix","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"depthRange","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMDepthRange","text":"DepthRange","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"elevationData","kind":"externalParam"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)MBMElevationData","text":"ElevationData","kind":"typeIdentifier"},{"text":")?, ","kind":"text"},{"text":"renderToTilesIDs","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMCanonicalTileID","text":"CanonicalTileID","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"text":"projection","kind":"externalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)MBMCustomLayerMapProjection","text":"CustomLayerMapProjection","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"initWithWidth:height:latitude:longitude:zoom:bearing:pitch:fieldOfView:projectionMatrix:depthRange:elevationData:renderToTilesIDs:projection:","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CanonicalTileID":{"type":"topic","abstract":[{"text":"Represents a tile coordinate.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID","kind":"symbol","url":"\/documentation\/mapboxmaps\/canonicaltileid","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CanonicalTileID"}],"navigatorTitle":[{"kind":"identifier","text":"CanonicalTileID"}],"title":"CanonicalTileID"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerMapProjection":{"title":"CustomLayerMapProjection","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomLayerMapProjection"}],"navigatorTitle":[{"kind":"identifier","text":"CustomLayerMapProjection"}],"kind":"symbol","role":"symbol","abstract":[],"url":"\/documentation\/mapboxmaps\/customlayermapprojection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerMapProjection"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","role":"collection","type":"topic","abstract":[],"title":"MapboxMaps Documentation","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":[],"op":"replace","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithWidth:height:latitude:longitude:zoom:bearing:pitch:fieldOfView:projectionMatrix:depthRange:elevationData:renderToTilesIDs:projection:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithWidth:height:latitude:longitude:zoom:bearing:pitch:fieldOfView:projectionMatrix:depthRange:elevationData:renderToTilesIDs:projection:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithWidth:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"kind":"text","text":") "},{"kind":"internalParam","text":"width"},{"kind":"text","text":" "},{"kind":"identifier","text":"height:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"kind":"internalParam","text":"height"},{"kind":"text","text":" "},{"kind":"identifier","text":"latitude:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"kind":"internalParam","text":"latitude"},{"kind":"text","text":" "},{"text":"longitude:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"longitude","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"zoom:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"zoom","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"bearing:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"bearing","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"pitch:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"pitch","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"fieldOfView:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"fieldOfView","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"projectionMatrix:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSNumber *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"projectionMatrix","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"depthRange:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/DepthRange","preciseIdentifier":"c:objc(cs)MBMDepthRange","text":"MBMDepthRange","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"depthRange","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"elevationData:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)MBMElevationData","text":"id<MBMElevationData>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"elevationData"},{"kind":"text","text":" "},{"kind":"identifier","text":"renderToTilesIDs:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<MBMCanonicalTileID *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"renderToTilesIDs"},{"kind":"text","text":" "},{"kind":"identifier","text":"projection:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)MBMCustomLayerMapProjection","text":"id<MBMCustomLayerMapProjection>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"projection"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ElevationData\/title","value":"MBMElevationData","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ElevationData\/fragments","value":[{"text":"MBMElevationData","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ElevationData\/navigatorTitle","value":[{"kind":"identifier","text":"MBMElevationData"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/title","value":"MBMCustomLayerRenderParameters","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/fragments","value":[{"text":"MBMCustomLayerRenderParameters","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/navigatorTitle","value":[{"text":"MBMCustomLayerRenderParameters","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1DepthRange\/title","value":"MBMDepthRange","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1DepthRange\/fragments","value":[{"text":"MBMDepthRange","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1DepthRange\/navigatorTitle","value":[{"text":"MBMDepthRange","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters~1init(width:height:latitude:longitude:zoom:bearing:pitch:fieldOfView:projectionMatrix:depthRange:elevationData:renderToTilesIDs:projection:)\/title","value":"initWithWidth:height:latitude:longitude:zoom:bearing:pitch:fieldOfView:projectionMatrix:depthRange:elevationData:renderToTilesIDs:projection:","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters~1init(width:height:latitude:longitude:zoom:bearing:pitch:fieldOfView:projectionMatrix:depthRange:elevationData:renderToTilesIDs:projection:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithWidth:height:latitude:longitude:zoom:bearing:pitch:fieldOfView:projectionMatrix:depthRange:elevationData:renderToTilesIDs:projection:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/title","value":"MBMCanonicalTileID","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/fragments","value":[{"kind":"identifier","text":"MBMCanonicalTileID"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/navigatorTitle","value":[{"kind":"identifier","text":"MBMCanonicalTileID"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerMapProjection\/title","value":"MBMCustomLayerMapProjection","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerMapProjection\/fragments","value":[{"text":"MBMCustomLayerMapProjection","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerMapProjection\/navigatorTitle","value":[{"text":"MBMCustomLayerMapProjection","kind":"identifier"}],"op":"replace"}]}]}