{"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXTileRegionLoadOptions\/initWithGeometry:descriptors:metadata:startLocation:averageBytesPerSecond:extraOptions:","interfaceLanguage":"occ"},"metadata":{"role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"text":"initWithGeometry:descriptors:metadata:startLocation:averageBytesPerSecond:extraOptions:","kind":"identifier"}],"modules":[{"name":"MapboxCommon"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithGeometry:descriptors:metadata:startLocation:averageBytesPerSecond:extraOptions:"}],"title":"initWithGeometry:descriptors:metadata:startLocation:averageBytesPerSecond:extraOptions:","symbolKind":"method","externalID":"c:objc(cs)MBXTileRegionLoadOptions(im)initWithGeometry:descriptors:metadata:startLocation:averageBytesPerSecond:extraOptions:"},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithGeometry:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXGeometry","text":"MBXGeometry"},{"kind":"text","text":" *) "},{"text":"geometry","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"descriptors:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<MBXTilesetDescriptor *>"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"descriptors"},{"text":" ","kind":"text"},{"text":"metadata:","kind":"identifier"},{"kind":"text","text":"("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"metadata","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"startLocation:"},{"kind":"text","text":"("},{"text":"MBXCoordinate2D","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Coordinate2D","preciseIdentifier":"c:objc(cs)MBXCoordinate2D","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"startLocation"},{"text":" ","kind":"text"},{"kind":"identifier","text":"averageBytesPerSecond:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"averageBytesPerSecond","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"extraOptions:","kind":"identifier"},{"kind":"text","text":"("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"extraOptions","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/mbxtileregionloadoptions\/initwithgeometry:descriptors:metadata:startlocation:averagebytespersecond:extraoptions:"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadOptions":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TileRegionLoadOptions","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions","navigatorTitle":[{"kind":"identifier","text":"TileRegionLoadOptions"}],"abstract":[{"type":"text","text":"Describes the tile region load option values."}],"url":"\/documentation\/mapboxcommon\/tileregionloadoptions","title":"TileRegionLoadOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Geometry":{"type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry","url":"\/documentation\/mapboxcommon\/geometry","kind":"symbol","title":"Geometry","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Geometry"}],"navigatorTitle":[{"kind":"identifier","text":"Geometry"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","kind":"article","url":"\/documentation\/mapboxmaps\/tilestore-apis","title":"TileStore APIs","role":"collectionGroup","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXTileRegionLoadOptions/initWithGeometry:descriptors:metadata:startLocation:averageBytesPerSecond:extraOptions:":{"fragments":[{"text":"- ","kind":"text"},{"text":"initWithGeometry:descriptors:metadata:startLocation:averageBytesPerSecond:extraOptions:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapboxcommon\/mbxtileregionloadoptions\/initwithgeometry:descriptors:metadata:startlocation:averagebytespersecond:extraoptions:","kind":"symbol","navigatorTitle":[{"text":"initWithGeometry:descriptors:metadata:startLocation:averageBytesPerSecond:extraOptions:","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXTileRegionLoadOptions\/initWithGeometry:descriptors:metadata:startLocation:averageBytesPerSecond:extraOptions:","title":"initWithGeometry:descriptors:metadata:startLocation:averageBytesPerSecond:extraOptions:","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Coordinate2D":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Coordinate2D"}],"title":"Coordinate2D","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Coordinate2D","type":"topic","abstract":[{"type":"text","text":"Boxed version of CLLocationCoordinate2D"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Coordinate2D"}],"url":"\/documentation\/mapboxcommon\/coordinate2d"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","title":"MapboxMaps Documentation","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","role":"collection","url":"\/documentation\/mapboxmaps","kind":"symbol","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MBXTileRegionLoadOptions","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/title"},{"value":[{"text":"MBXTileRegionLoadOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBXTileRegionLoadOptions"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry\/title","op":"replace","value":"MBXGeometry"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry\/fragments","value":[{"text":"MBXGeometry","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry\/navigatorTitle","op":"replace","value":[{"text":"MBXGeometry","kind":"identifier"}]},{"value":"MBXCoordinate2D","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Coordinate2D\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Coordinate2D\/fragments","value":[{"text":"MBXCoordinate2D","kind":"identifier"}]},{"value":[{"text":"MBXCoordinate2D","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Coordinate2D\/navigatorTitle","op":"replace"}]}]}