{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"freeCameraOptions","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMFreeCameraOptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions","text":"FreeCameraOptions"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The free camera options to set.","type":"text"}],"type":"paragraph"}],"name":"freeCameraOptions"}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"FreeCameraOptions provides more direct access to the underlying camera entity."},{"type":"text","text":" "},{"text":"For backwards compatibility the state set using this API must be representable","type":"text"},{"type":"text","text":" "},{"text":"with ","type":"text"},{"type":"codeVoice","code":"CameraOptions"},{"text":" as well. Parameters are clamped to a valid range or","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"discarded as invalid if the conversion to the pitch and bearing presentation"},{"text":" ","type":"text"},{"text":"is ambiguous. For example orientation can be invalid if it leads to the","type":"text"},{"type":"text","text":" "},{"text":"camera being upside down or the quaternion has zero length.","type":"text"}],"type":"paragraph"}]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/freeCameraOptions","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/mapboxmaps\/mapboxmap\/freecameraoptions"],"traits":[{"interfaceLanguage":"swift"}]}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Camera-and-coordinates"],"title":"Camera","generated":true,"anchor":"Camera"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","abstract":[{"type":"text","text":"Sets\/get the map view with the free camera options."}],"metadata":{"modules":[{"name":"MapboxMaps"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"freeCameraOptions"},{"text":": ","kind":"text"},{"text":"FreeCameraOptions","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMFreeCameraOptions"}],"title":"freeCameraOptions","roleHeading":"Instance Property","role":"symbol","externalID":"s:10MapboxMaps0A3MapC17freeCameraOptionsSo07MBMFreeeF0Cvp","symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs"],["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapboxMap"}],"navigatorTitle":[{"kind":"identifier","text":"MapboxMap"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","url":"\/documentation\/mapboxmaps\/mapboxmap","type":"topic","abstract":[{"type":"text","text":"Provides access to the map model, including the camera, style, observable map events,"},{"type":"text","text":" "},{"type":"text","text":"and querying rendered features."}],"role":"symbol","kind":"symbol","title":"MapboxMap"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/freeCameraOptions":{"url":"\/documentation\/mapboxmaps\/mapboxmap\/freecameraoptions","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"freeCameraOptions"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMFreeCameraOptions","kind":"typeIdentifier","text":"FreeCameraOptions"}],"title":"freeCameraOptions","type":"topic","abstract":[{"text":"Sets\/get the map view with the free camera options.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/freeCameraOptions","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","role":"collection","kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","abstract":[],"kind":"article","url":"\/documentation\/overview","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FreeCameraOptions":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions","type":"topic","title":"FreeCameraOptions","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FreeCameraOptions","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/freecameraoptions","abstract":[{"text":"Various options for accessing physical properties of the underlying camera entity.","type":"text"},{"text":" ","type":"text"},{"text":"A direct access to these properties allows more flexible and precise controlling","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"of the camera while also being fully compatible and interchangeable with CameraOptions."},{"type":"text","text":" "},{"type":"text","text":"All fields are optional."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FreeCameraOptions"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Camera-and-coordinates":{"role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Camera-and-coordinates","kind":"article","url":"\/documentation\/mapboxmaps\/camera-and-coordinates","title":"Camera and coordinates","type":"topic","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"type":"topic","abstract":[],"title":"MapboxMap","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","url":"\/documentation\/mapboxmaps\/mapboxmap-apis","role":"collectionGroup"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions\/title","value":"MBMFreeCameraOptions"},{"value":[{"kind":"identifier","text":"MBMFreeCameraOptions"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBMFreeCameraOptions"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}