{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/mbmstyleimagemissing\/timestamp"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/mbmstyleimagemissing\/timestamp"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"timestamp","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStyleImageMissing\/timestamp","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageMissing"]]},"kind":"symbol","abstract":[{"text":"The timestamp of an event when the ","type":"text"},{"type":"codeVoice","code":"map"},{"text":" requested a missing image.","type":"text"}],"metadata":{"roleHeading":"Instance Property","externalID":"c:objc(cs)MBMStyleImageMissing(py)timestamp","title":"timestamp","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"}],"navigatorTitle":[{"text":"timestamp","kind":"identifier"}],"modules":[{"name":"MapboxMaps"}],"symbolKind":"property","role":"symbol"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMStyleImageMissing/timestamp":{"role":"symbol","abstract":[{"type":"text","text":"The timestamp of an event when the "},{"code":"map","type":"codeVoice"},{"type":"text","text":" requested a missing image."}],"title":"timestamp","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"}],"navigatorTitle":[{"kind":"identifier","text":"timestamp"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMStyleImageMissing\/timestamp","url":"\/documentation\/mapboxmaps\/mbmstyleimagemissing\/timestamp","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","title":"Map events","role":"collectionGroup","type":"topic","abstract":[{"type":"text","text":"The simplified diagram of the events emitted by the map is displayed below."}],"url":"\/documentation\/mapboxmaps\/events","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleImageMissing":{"title":"StyleImageMissing","role":"symbol","navigatorTitle":[{"text":"StyleImageMissing","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageMissing","abstract":[{"text":"A style needs an image that is missing from the sprite sheet. This event is","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"emitted when the "},{"type":"codeVoice","code":"map"},{"type":"text","text":" renders visible tiles, and one of the required images"},{"type":"text","text":" "},{"text":"is missing in the sprite sheet. The event observer has to provide the missing","type":"text"},{"type":"text","text":" "},{"text":"image by calling the ","type":"text"},{"code":"addStyleImage","type":"codeVoice"},{"text":" method.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"StyleImageMissing","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/styleimagemissing","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"timestamp","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"timestamp"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDate","text":"NSDate"},{"kind":"text","text":" * "},{"text":"timestamp","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMStyleImageMissing~1timestamp\/title","op":"replace","value":"timestamp"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMStyleImageMissing~1timestamp\/fragments","value":[{"text":"timestamp","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageMissing\/title","value":"MBMStyleImageMissing"},{"op":"replace","value":[{"kind":"identifier","text":"MBMStyleImageMissing"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageMissing\/fragments"}]}]}