{"metadata":{"modules":[{"name":"MapboxMaps"}],"role":"symbol","roleHeading":"Instance Property","title":"minZoom","externalID":"c:objc(cs)MBMTilesetDescriptorOptions(py)minZoom","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"minZoom"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt8","preciseIdentifier":"s:s5UInt8V"}],"navigatorTitle":[{"kind":"identifier","text":"minZoom"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/tilesetdescriptoroptions\/minzoom"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/tilesetdescriptoroptions\/minzoom"]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TilesetDescriptorOptions"]]},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TilesetDescriptorOptions\/minZoom","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"minZoom"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5UInt8V","text":"UInt8","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Note: the implementation loads and stores the loaded tiles","type":"text"},{"type":"text","text":" "},{"text":"in batches, each batch has a pre-defined zoom range and it contains","type":"text"},{"type":"text","text":" "},{"type":"text","text":"all child tiles within the range. The zoom leveling scheme for the tile"},{"text":" ","type":"text"},{"type":"text","text":"batches can be defined in Tile JSON, otherwise the default scheme is used:"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Global coverage: 0 - 5"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Regional information: 6 - 10"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Local information: 11 - 14","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Streets detail: 15 - 16"}]}]}]},{"type":"paragraph","inlineContent":[{"text":"Internally, the implementation maps the given tile pack zoom range","type":"text"},{"type":"text","text":" "},{"type":"text","text":"and geometry to a set of pre-defined batches to load, therefore"},{"type":"text","text":" "},{"type":"text","text":"it is highly recommended to choose the "},{"code":"minZoom","type":"codeVoice"},{"type":"text","text":" and "},{"type":"codeVoice","code":"maxZoom"},{"type":"text","text":" values"},{"text":" ","type":"text"},{"type":"text","text":"in accordance with the tile batches zoom ranges (see the list above)."}]}],"kind":"content"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","abstract":[{"type":"text","text":"Minimum zoom level for the tile package."}],"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"type":"topic","title":"TileStore APIs","abstract":[],"role":"collectionGroup","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","url":"\/documentation\/mapboxmaps\/tilestore-apis"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","url":"\/documentation\/overview","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"role":"collection","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TilesetDescriptorOptions/minZoom":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"minZoom","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V","text":"UInt8"}],"type":"topic","abstract":[{"type":"text","text":"Minimum zoom level for the tile package."}],"role":"symbol","navigatorTitle":[{"text":"minZoom","kind":"identifier"}],"title":"minZoom","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TilesetDescriptorOptions\/minZoom","url":"\/documentation\/mapboxmaps\/tilesetdescriptoroptions\/minzoom"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TilesetDescriptorOptions":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TilesetDescriptorOptions","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TilesetDescriptorOptions"}],"url":"\/documentation\/mapboxmaps\/tilesetdescriptoroptions","kind":"symbol","abstract":[{"type":"text","text":"Describes the tileset descriptor option values."}],"title":"TilesetDescriptorOptions","navigatorTitle":[{"kind":"identifier","text":"TilesetDescriptorOptions"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"minZoom"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"minZoom","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@uint8_t","text":"uint8_t"},{"kind":"text","text":" "},{"kind":"identifier","text":"minZoom"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions~1minZoom\/title","value":"minZoom","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions~1minZoom\/fragments","value":[{"text":"minZoom","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions\/title","value":"MBMTilesetDescriptorOptions","op":"replace"},{"value":[{"kind":"identifier","text":"MBMTilesetDescriptorOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MBMTilesetDescriptorOptions"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}