{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/mbmimagestretches\/first"]},{"paths":["\/documentation\/mapboxmaps\/mbmimagestretches\/first"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"first","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","metadata":{"modules":[{"name":"MapboxMaps"}],"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","externalID":"c:objc(cs)MBMImageStretches(py)first","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"first"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"title":"first","navigatorTitle":[{"kind":"identifier","text":"first"}]},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMImageStretches\/first","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The first stretchable part in screen pixel units."}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer-Property-Values","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageStretches"]]},"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMImageStretches/first":{"role":"symbol","url":"\/documentation\/mapboxmaps\/mbmimagestretches\/first","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"first"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"abstract":[{"text":"The first stretchable part in screen pixel units.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMImageStretches\/first","title":"first","type":"topic","navigatorTitle":[{"kind":"identifier","text":"first"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layer-Property-Values":{"type":"topic","url":"\/documentation\/mapboxmaps\/layer-property-values","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer-Property-Values","kind":"article","title":"Layer Property Values","role":"collectionGroup","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ImageStretches":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ImageStretches"}],"abstract":[{"type":"text","text":"Describes the image stretch areas."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageStretches","navigatorTitle":[{"kind":"identifier","text":"ImageStretches"}],"url":"\/documentation\/mapboxmaps\/imagestretches","type":"topic","title":"ImageStretches","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"first"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"kind":"identifier","text":"first"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"float","kind":"typeIdentifier","preciseIdentifier":"c:f"},{"kind":"text","text":" "},{"text":"first","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMImageStretches~1first\/title","value":"first","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"first"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMImageStretches~1first\/fragments"},{"value":"MBMImageStretches","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ImageStretches\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ImageStretches\/fragments","value":[{"kind":"identifier","text":"MBMImageStretches"}]}]}]}