{"metadata":{"title":"getInMegabytes()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","navigatorTitle":[{"text":"getTileCacheBudgetInMegabytes","kind":"identifier"}],"modules":[{"name":"MapboxMaps"}],"externalID":"c:objc(cs)MBMTileCacheBudget(im)getTileCacheBudgetInMegabytes","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getInMegabytes","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMTileCacheBudgetInMegabytes","text":"TileCacheBudgetInMegabytes","kind":"typeIdentifier"}]},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudget"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudget\/getInMegabytes()"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/mapboxmaps\/tilecachebudget\/getinmegabytes()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/tilecachebudget\/getinmegabytes()"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getInMegabytes","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMTileCacheBudgetInMegabytes","text":"TileCacheBudgetInMegabytes","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInMegabytes"}],"languages":["swift"]}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudgetInMegabytes":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInMegabytes","abstract":[{"type":"text","text":"Tile cache budget in megabytes."}],"type":"topic","title":"TileCacheBudgetInMegabytes","url":"\/documentation\/mapboxmaps\/tilecachebudgetinmegabytes","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileCacheBudgetInMegabytes"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TileCacheBudgetInMegabytes"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"role":"collectionGroup","url":"\/documentation\/mapboxmaps\/tilestore-apis","kind":"article","title":"TileStore APIs","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudget":{"role":"symbol","navigatorTitle":[{"text":"TileCacheBudget","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudget","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileCacheBudget","kind":"identifier"}],"title":"TileCacheBudget","url":"\/documentation\/mapboxmaps\/tilecachebudget","type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","kind":"article","title":"MapboxMaps Documentation","url":"\/documentation\/overview","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudget/getInMegabytes()":{"type":"topic","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getInMegabytes","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"TileCacheBudgetInMegabytes","preciseIdentifier":"c:objc(cs)MBMTileCacheBudgetInMegabytes","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"getTileCacheBudgetInMegabytes","kind":"identifier"}],"role":"symbol","title":"getInMegabytes()","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudget\/getInMegabytes()","url":"\/documentation\/mapboxmaps\/tilecachebudget\/getinmegabytes()","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"role":"collection","kind":"symbol","url":"\/documentation\/mapboxmaps","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"getTileCacheBudgetInMegabytes"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"getTileCacheBudgetInMegabytes","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInMegabytes","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMTileCacheBudgetInMegabytes","text":"MBMTileCacheBudgetInMegabytes"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"getTileCacheBudgetInMegabytes"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInMegabytes\/title","value":"MBMTileCacheBudgetInMegabytes"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInMegabytes\/fragments","value":[{"kind":"identifier","text":"MBMTileCacheBudgetInMegabytes"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInMegabytes\/navigatorTitle","value":[{"text":"MBMTileCacheBudgetInMegabytes","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudget\/title","value":"MBMTileCacheBudget"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudget\/fragments","value":[{"kind":"identifier","text":"MBMTileCacheBudget"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudget\/navigatorTitle","value":[{"text":"MBMTileCacheBudget","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudget~1getInMegabytes()\/title","value":"getTileCacheBudgetInMegabytes"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudget~1getInMegabytes()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getTileCacheBudgetInMegabytes"}]}]}]}