name: MapboxMapsPackager
targets:
  MapboxMaps:
    type: framework
    platform: iOS
    configFiles: 
      Debug: "../../../Mapbox/Configurations/Mapbox.xcconfig"
      Release: "../../../Mapbox/Configurations/Mapbox.xcconfig"
    sources: 
      - path: "../../../Sources/MapboxMaps/"
        excludes: 
          - "**/*.plist"
          - "**/*.h"
          - "*.xcodeproj"
          - "/Configurations"
        includes: "*.swift"
      - path: "../../../Sources/MapboxMaps/MapView/Info.plist"
      - path: "../../../Sources/MapboxMaps/MapView/MapboxMaps.h"
    dependencies:
      - framework: "Core/MapboxCoreMaps.xcframework"
      - framework: "Turf/Turf.xcframework"
      - framework: "Common/MapboxCommon.xcframework"
      - framework: "Telemetry/MapboxMobileEvents.xcframework"