---
name: MapboxMaps
targets:
  MapboxMaps:
    type: framework
    platform: iOS
    settings:
      base:
        INFOPLIST_FILE: "Sources/MapboxMaps/Info.plist"
        PRODUCT_BUNDLE_IDENTIFIER: com.mapbox.MapboxMaps
        INSTALL_PATH: $(LOCAL_LIBRARY_DIR)/Frameworks
        SKIP_INSTALL: "NO"
        TARGETED_DEVICE_FAMILY: 1,2
        DYLIB_COMPATIBILITY_VERSION: 1
        DYLIB_CURRENT_VERSION: 3
        LD_RUNPATH_SEARCH_PATHS: $(inherited) @executable_path/Frameworks @loader_path/Frameworks
        MACH_O_TYPE: mh_dylib
        DEFINES_MODULE: "YES"
        PRODUCT_NAME: $(TARGET_NAME:c99extidentifier)
        CODE_SIGN_STYLE: Automatic
        BUILD_DIR: .build
    configFiles:
      Debug: "Configurations/Mapbox.xcconfig"
      Release: "Configurations/Mapbox.xcconfig"
    sources:
      - path: "Sources/MapboxMaps/"
        includes: "*.swift"
        excludes:
          - "**/*.plist"
          - "**/*.h"
      - path: "Sources/MapboxMaps/Info.plist"
      - path: "Sources/MapboxMaps/MapboxMaps.h"
    dependencies:
      - framework: "../MapboxCoreMaps.xcframework"
      - framework: "../Turf.xcframework"
      - framework: "../MapboxCommon.xcframework"
      - framework: "../MapboxMobileEvents.xcframework"
