---
name: MapboxMaps
options:
  xcodeVersion: 1250
targets:
  MapboxMaps:
    type: framework
    platform: iOS
    settings:
      base:
        INFOPLIST_FILE: "Sources/MapboxMaps/Info.plist"
        PRODUCT_BUNDLE_IDENTIFIER: com.mapbox.MapboxMaps
        INSTALL_PATH: $(LOCAL_LIBRARY_DIR)/Frameworks
        SKIP_INSTALL: "NO"
        TARGETED_DEVICE_FAMILY: 1,2
        LD_RUNPATH_SEARCH_PATHS: $(inherited) @executable_path/Frameworks @loader_path/Frameworks
        MACH_O_TYPE: mh_dylib
        DEFINES_MODULE: "YES"
        PRODUCT_NAME: $(TARGET_NAME:c99extidentifier)
        CODE_SIGN_STYLE: Automatic
        SWIFT_TREAT_WARNINGS_AS_ERRORS: "NO"
        SWIFT_EMIT_PRIVATE_MODULE_INTERFACE: "YES"
      configs:
        Debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: $(inherited) USING_TURF_WITH_LIBRARY_EVOLUTION
        Release:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: $(inherited) RELEASE USING_TURF_WITH_LIBRARY_EVOLUTION
    configFiles:
      Debug: "Configurations/base.xcconfig"
      Release: "Configurations/base.xcconfig"
    sources:
      - path: "Sources/MapboxMaps/"
        includes: "*.swift"
        excludes:
          - "**/*.plist"
          - "**/*.h"
          - "**/.swiftlint.yml"
      - path: "Sources/MapboxMaps/Info.plist"
      - path: "Sources/MapboxMaps/MapboxMaps.h"
    dependencies:
      - framework: "../MapboxCoreMaps.xcframework"
      - framework: "../Turf.xcframework"
      - framework: "../MapboxCommon.xcframework"
      - framework: "../MapboxMobileEvents.xcframework"
