{"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"]},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH"]}],"topicSections":[{"title":"Type Methods","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SdkInformationQuery\/getSdkInformation()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SdkInformationQuery\/getSdkInformationByName(forName:)"],"anchor":"Type-Methods"}],"metadata":{"modules":[{"name":"MapboxCommon"}],"role":"symbol","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SdkInformationQuery"}],"title":"SdkInformationQuery","symbolKind":"class","externalID":"c:objc(cs)MBXSdkInformationQuery","navigatorTitle":[{"kind":"identifier","text":"SdkInformationQuery"}]},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SdkInformationQuery","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Provides an interface to query registered Mapbox SDKs. Mapbox SDKs include Maps, Navigation, Search, and others."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/sdkinformationquery"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/sdkinformationquery"]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SdkInformationQuery","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SdkInformationQuery/getSdkInformation()":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getSdkInformation"},{"kind":"text","text":"() -> ["},{"preciseIdentifier":"c:objc(cs)MBXSdkInformation","kind":"typeIdentifier","text":"SdkInformation"},{"kind":"text","text":"]"}],"abstract":[],"title":"getSdkInformation()","navigatorTitle":[{"kind":"identifier","text":"getSdkInformation"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SdkInformationQuery\/getSdkInformation()","url":"\/documentation\/mapboxcommon\/sdkinformationquery\/getsdkinformation()","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SdkInformationQuery":{"type":"topic","url":"\/documentation\/mapboxcommon\/sdkinformationquery","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SdkInformationQuery","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SdkInformationQuery","kind":"identifier"}],"role":"symbol","title":"SdkInformationQuery","navigatorTitle":[{"text":"SdkInformationQuery","kind":"identifier"}],"abstract":[{"type":"text","text":"Provides an interface to query registered Mapbox SDKs. Mapbox SDKs include Maps, Navigation, Search, and others."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SdkInformationQuery/getSdkInformationByName(forName:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SdkInformationQuery\/getSdkInformationByName(forName:)","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getSdkInformationByName"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)MBXSdkInformation","kind":"typeIdentifier","text":"SdkInformation"},{"kind":"text","text":"?"}],"title":"getSdkInformationByName(forName:)","abstract":[],"kind":"symbol","url":"\/documentation\/mapboxcommon\/sdkinformationquery\/getsdkinformationbyname(forname:)","navigatorTitle":[{"kind":"identifier","text":"getSdkInformationByNameForName:"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/SH":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.mapbox.MapboxMaps/objc(cs)NSObject":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.mapbox.MapboxMaps/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.mapbox.MapboxMaps/SQ":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.mapbox.MapboxMaps/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.mapbox.MapboxMaps/objc(pl)NSObject":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","abstract":[],"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","type":"topic","kind":"article"},"doc://com.mapbox.MapboxMaps/s7CVarArgP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"type":"topic","title":"MapboxCommon","role":"collection","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","url":"\/documentation\/mapboxcommon","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"MBXSdkInformationQuery"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXSdkInformationQuery"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"MBXSdkInformationQuery","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Type Methods","anchor":"Type-Methods","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SdkInformationQuery\/getSdkInformation()","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SdkInformationQuery\/getSdkInformationByName(forName:)"],"generated":true}]},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBXSdkInformationQuery"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SdkInformationQuery~1getSdkInformation()\/title","op":"replace","value":"getSdkInformation"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SdkInformationQuery~1getSdkInformation()\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"getSdkInformation","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SdkInformationQuery\/title","op":"replace","value":"MBXSdkInformationQuery"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SdkInformationQuery\/fragments","op":"replace","value":[{"text":"MBXSdkInformationQuery","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SdkInformationQuery\/navigatorTitle","op":"replace","value":[{"text":"MBXSdkInformationQuery","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SdkInformationQuery~1getSdkInformationByName(forName:)\/title","op":"replace","value":"getSdkInformationByNameForName:"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SdkInformationQuery~1getSdkInformationByName(forName:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"getSdkInformationByNameForName:","kind":"identifier"}]}]}]}