{"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getTerrainExaggeration","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"title":"getTerrainExaggeration()","symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"text":"getTerrainExaggeration","kind":"identifier"}],"required":true,"role":"symbol","modules":[{"name":"MapboxMaps"}],"externalID":"c:objc(pl)MBMElevationData(im)getTerrainExaggeration"},"abstract":[{"type":"text","text":"Current value of terrain exaggeration."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getTerrainExaggeration"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"text":"Return Value","anchor":"return-value","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Current value of terrain exaggeration."}]}],"kind":"content"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ElevationData"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ElevationData\/getTerrainExaggeration()"},"variants":[{"paths":["\/documentation\/mapboxmaps\/elevationdata\/getterrainexaggeration()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/elevationdata\/getterrainexaggeration()"]}],"kind":"symbol","references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","title":"MapboxMaps","kind":"symbol","role":"collection","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layers":{"abstract":[],"role":"collectionGroup","type":"topic","title":"Layers","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers","url":"\/documentation\/mapboxmaps\/layers","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ElevationData":{"url":"\/documentation\/mapboxmaps\/elevationdata","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ElevationData"}],"navigatorTitle":[{"text":"ElevationData","kind":"identifier"}],"type":"topic","kind":"symbol","title":"ElevationData","abstract":[{"text":"Interface that provides access to elevation data.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ElevationData"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ElevationData/getTerrainExaggeration()":{"required":true,"kind":"symbol","title":"getTerrainExaggeration()","type":"topic","abstract":[{"text":"Current value of terrain exaggeration.","type":"text"}],"url":"\/documentation\/mapboxmaps\/elevationdata\/getterrainexaggeration()","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ElevationData\/getTerrainExaggeration()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getTerrainExaggeration"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"getTerrainExaggeration","kind":"identifier"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article","role":"collection","title":"MapboxMaps Documentation","type":"topic","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"getTerrainExaggeration"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getTerrainExaggeration"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"double","preciseIdentifier":"c:d","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"getTerrainExaggeration","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"Current value of terrain exaggeration."}],"type":"paragraph"}]}},{"value":"MBMElevationData","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ElevationData\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ElevationData\/fragments","value":[{"text":"MBMElevationData","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ElevationData\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMElevationData"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ElevationData~1getTerrainExaggeration()\/title","op":"replace","value":"getTerrainExaggeration"},{"value":[{"text":"- ","kind":"text"},{"text":"getTerrainExaggeration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ElevationData~1getTerrainExaggeration()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}