{"metadata":{"modules":[{"name":"MapboxCommon"}],"symbolKind":"method","role":"symbol","fragments":[{"text":"+ ","kind":"text"},{"text":"create","kind":"identifier"}],"roleHeading":"Type Method","title":"create","navigatorTitle":[{"kind":"identifier","text":"create"}],"externalID":"c:objc(cs)MBXTileStore(cm)create"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:objc(cs)MBXTileStore","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore","kind":"typeIdentifier","text":"MBXTileStore"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"create"},{"kind":"text","text":";"}]}]},{"content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"Returns a TileStore instance."}],"type":"paragraph"}],"kind":"content"},{"content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"If the tile store instance already exists for the default location this method will return it without creating","type":"text"},{"text":" ","type":"text"},{"text":"a new instance, thus making sure that there is only one tile store instance for a path at a time.","type":"text"}]}],"kind":"content"}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXTileStore\/create"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/mbxtilestore\/create"]}],"sections":[],"kind":"symbol","abstract":[{"text":"Creates a TileStore instance at the default location.","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXTileStore/create":{"abstract":[{"type":"text","text":"Creates a TileStore instance at the default location."}],"title":"create","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXTileStore\/create","role":"symbol","url":"\/documentation\/mapboxcommon\/mbxtilestore\/create","type":"topic","fragments":[{"text":"+ ","kind":"text"},{"text":"create","kind":"identifier"}],"navigatorTitle":[{"text":"create","kind":"identifier"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","title":"TileStore APIs","url":"\/documentation\/mapboxmaps\/tilestore-apis","kind":"article","type":"topic","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileStore":{"title":"TileStore","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileStore","kind":"identifier"}],"navigatorTitle":[{"text":"TileStore","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore","kind":"symbol","type":"topic","abstract":[{"text":"TileStore manages downloads and storage for requests to tile-related API endpoints, enforcing a disk usage","type":"text"},{"text":" ","type":"text"},{"text":"quota: tiles available on disk may be deleted to make room for a new download. This interface can be used by an","type":"text"},{"text":" ","type":"text"},{"text":"app developer to set the disk quota. The rest of TileStore API is intended for native SDK consumption only.","type":"text"}],"url":"\/documentation\/mapboxcommon\/tilestore"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","type":"topic","abstract":[],"title":"MapboxMaps Documentation","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","role":"collection","title":"MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"MBXTileStore","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/title"},{"op":"replace","value":[{"text":"MBXTileStore","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MBXTileStore"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}