{"topicSections":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedSourceFeature\/queriedFeature"],"generated":true,"title":"Instance Properties"}],"seeAlsoSections":[{"anchor":"Query-features-on-the-map","title":"Query features on the map","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceQueryOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedFeature","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedRenderedFeature","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AnnotatedFeature","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeaturesetDescriptor-swift.class"],"generated":true}],"variants":[{"paths":["\/documentation\/mapboxmaps\/queriedsourcefeature"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/queriedsourcefeature"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH"],"title":"Conforms To"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"QueriedSourceFeature"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","abstract":[{"text":"Represents query result that is returned in QuerySourceFeaturesCallback.","type":"text"}],"metadata":{"role":"symbol","modules":[{"name":"MapboxMaps"}],"symbolKind":"class","roleHeading":"Class","title":"QueriedSourceFeature","navigatorTitle":[{"text":"QueriedSourceFeature","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"QueriedSourceFeature"}],"externalID":"c:objc(cs)MBMQueriedSourceFeature"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs"]]},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedSourceFeature","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.mapbox.MapboxMaps/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FeaturesetDescriptor-swift.class":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeaturesetDescriptor-swift.class","url":"\/documentation\/mapboxmaps\/featuresetdescriptor-swift.class","kind":"symbol","title":"FeaturesetDescriptor","type":"topic","abstract":[{"text":"Represents an identifier for a single exported featureset or a layer.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FeaturesetDescriptor"}],"navigatorTitle":[{"text":"FeaturesetDescriptor","kind":"identifier"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","abstract":[],"url":"\/documentation\/overview","role":"collection","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderedQueryOptions":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryOptions","title":"RenderedQueryOptions","type":"topic","url":"\/documentation\/mapboxmaps\/renderedqueryoptions","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RenderedQueryOptions","kind":"identifier"}],"abstract":[{"text":"Options for querying rendered features.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"RenderedQueryOptions","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/QueriedFeature":{"title":"QueriedFeature","navigatorTitle":[{"kind":"identifier","text":"QueriedFeature"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedFeature","kind":"symbol","abstract":[{"text":"Represents queried feature that is returned through ","type":"text"},{"code":"QueriedRenderedFeature","type":"codeVoice"},{"type":"text","text":" or "},{"code":"QueriedSourceFeature","type":"codeVoice"}],"url":"\/documentation\/mapboxmaps\/queriedfeature","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"QueriedFeature","kind":"identifier"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","title":"Swift.Equatable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceQueryOptions":{"title":"SourceQueryOptions","navigatorTitle":[{"text":"SourceQueryOptions","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceQueryOptions","kind":"symbol","abstract":[{"text":"Options for querying source features.","type":"text"}],"url":"\/documentation\/mapboxmaps\/sourcequeryoptions","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceQueryOptions"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/QueriedSourceFeature":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedSourceFeature","title":"QueriedSourceFeature","type":"topic","url":"\/documentation\/mapboxmaps\/queriedsourcefeature","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"QueriedSourceFeature"}],"abstract":[{"type":"text","text":"Represents query result that is returned in QuerySourceFeaturesCallback."}],"kind":"symbol","navigatorTitle":[{"text":"QueriedSourceFeature","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/SH":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","title":"Swift.Hashable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/QueriedSourceFeature/queriedFeature":{"abstract":[{"text":"Feature returned by the query.","type":"text"}],"navigatorTitle":[{"text":"queriedFeature","kind":"identifier"}],"title":"queriedFeature","type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/queriedsourcefeature\/queriedfeature","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"queriedFeature","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMQueriedFeature","text":"QueriedFeature"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedSourceFeature\/queriedFeature"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"title":"MapboxMap","type":"topic","role":"collectionGroup","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","url":"\/documentation\/mapboxmaps\/mapboxmap-apis","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AnnotatedFeature":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AnnotatedFeature"}],"title":"AnnotatedFeature","url":"\/documentation\/mapboxmaps\/annotatedfeature","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AnnotatedFeature","abstract":[{"text":"Represents either a GeoJSON geometry or an annotated layer feature.","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"AnnotatedFeature","kind":"identifier"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/QueriedRenderedFeature":{"url":"\/documentation\/mapboxmaps\/queriedrenderedfeature","navigatorTitle":[{"kind":"identifier","text":"QueriedRenderedFeature"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedRenderedFeature","role":"symbol","title":"QueriedRenderedFeature","abstract":[{"text":"Represents query result that is returned in QueryRenderedFeaturesCallback.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"QueriedRenderedFeature"}]},"doc://com.mapbox.MapboxMaps/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.mapbox.MapboxMaps/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject","title":"NSObject"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","value":"MBMQueriedSourceFeature","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"value":[{"kind":"identifier","text":"MBMQueriedSourceFeature"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"MBMQueriedSourceFeature","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedSourceFeature\/queriedFeature"],"generated":true,"title":"Instance Properties"}]},{"value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"}],"op":"replace","path":"\/relationshipsSections"},{"value":[{"generated":true,"title":"Query features on the map","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceQueryOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedFeature","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedRenderedFeature","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeaturesetDescriptor-swift.class"],"anchor":"Query-features-on-the-map"}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"MBMQueriedSourceFeature","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeaturesetDescriptor-swift.class\/title","op":"replace","value":"MBMFeaturesetDescriptor"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeaturesetDescriptor-swift.class\/fragments","op":"replace","value":[{"text":"MBMFeaturesetDescriptor","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeaturesetDescriptor-swift.class\/navigatorTitle","value":[{"text":"MBMFeaturesetDescriptor","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderedQueryOptions\/title","value":"MBMRenderedQueryOptions","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderedQueryOptions\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMRenderedQueryOptions"}]},{"value":[{"text":"MBMRenderedQueryOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderedQueryOptions\/navigatorTitle"},{"op":"replace","value":"MBMQueriedFeature","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedFeature\/title"},{"op":"replace","value":[{"text":"MBMQueriedFeature","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedFeature\/fragments"},{"value":[{"text":"MBMQueriedFeature","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedFeature\/navigatorTitle"},{"value":"MBMSourceQueryOptions","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceQueryOptions\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceQueryOptions\/fragments","value":[{"kind":"identifier","text":"MBMSourceQueryOptions"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceQueryOptions\/navigatorTitle","value":[{"text":"MBMSourceQueryOptions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedSourceFeature\/title","value":"MBMQueriedSourceFeature"},{"value":[{"kind":"identifier","text":"MBMQueriedSourceFeature"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedSourceFeature\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedSourceFeature\/navigatorTitle","op":"replace","value":[{"text":"MBMQueriedSourceFeature","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedSourceFeature~1queriedFeature\/title","value":"queriedFeature","op":"replace"},{"value":[{"kind":"identifier","text":"queriedFeature"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedSourceFeature~1queriedFeature\/fragments","op":"replace"},{"value":"MBMQueriedRenderedFeature","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedRenderedFeature\/title","op":"replace"},{"op":"replace","value":[{"text":"MBMQueriedRenderedFeature","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedRenderedFeature\/fragments"},{"value":[{"text":"MBMQueriedRenderedFeature","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedRenderedFeature\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}