{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs"]]},"seeAlsoSections":[{"title":"Location","anchor":"Location","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationManager","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck2DConfiguration","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckBearing","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProviderDelegate","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Coordinate2D","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationExtraKeys","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProviderRequest","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceFactory","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/DeviceLocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Heading","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckRenderingData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/IntervalSettings"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Model"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Model","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Model\/init(from:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Model\/init(id:uri:position:orientation:)"],"generated":true},{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Model\/id","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Model\/orientation","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Model\/position","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Model\/uri"]},{"anchor":"Default-Implementations","title":"Default Implementations","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Model\/Equatable-Implementations"]}],"variants":[{"paths":["\/documentation\/mapboxmaps\/model"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapStyleContent","doc:\/\/com.mapbox.MapboxMaps\/Se","doc:\/\/com.mapbox.MapboxMaps\/SE","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"],"title":"Conforms To","type":"conformsTo"}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"A structure represeting a Model"}],"metadata":{"symbolKind":"struct","modules":[{"name":"MapboxMaps"}],"navigatorTitle":[{"text":"Model","kind":"identifier"}],"role":"symbol","roleHeading":"Structure","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"Model","kind":"identifier"}],"externalID":"s:10MapboxMaps5ModelV","title":"Model"},"kind":"symbol","references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationProviderRequest":{"url":"\/documentation\/mapboxcommon\/locationproviderrequest","role":"symbol","abstract":[{"type":"text","text":"Data model that contains parameters for location requests."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProviderRequest","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"LocationProviderRequest"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"LocationProviderRequest","kind":"identifier"}],"title":"LocationProviderRequest","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PuckBearing":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckBearing","title":"PuckBearing","url":"\/documentation\/mapboxmaps\/puckbearing","abstract":[{"text":"Controls how the puck is oriented","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PuckBearing","kind":"identifier"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"PuckBearing","kind":"identifier"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Puck3DConfiguration":{"navigatorTitle":[{"text":"Puck3DConfiguration","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck3DConfiguration","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Puck3DConfiguration"}],"role":"symbol","abstract":[],"title":"Puck3DConfiguration","url":"\/documentation\/mapboxmaps\/puck3dconfiguration"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PermissionStatus":{"title":"PermissionStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PermissionStatus","kind":"identifier"}],"abstract":[{"type":"text","text":"Location permissions granted by user to the app."}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus","navigatorTitle":[{"kind":"identifier","text":"PermissionStatus"}],"kind":"symbol","url":"\/documentation\/mapboxcommon\/permissionstatus"},"doc://com.mapbox.MapboxMaps/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","title":"Swift.Equatable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Model/orientation":{"type":"topic","abstract":[{"type":"text","text":"Orientation of the model"}],"url":"\/documentation\/mapboxmaps\/model\/orientation","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"orientation","kind":"identifier"},{"kind":"text","text":": ["},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":"]?"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Model\/orientation","title":"orientation","kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationServiceObserver":{"url":"\/documentation\/mapboxcommon\/locationserviceobserver","title":"LocationServiceObserver","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceObserver","kind":"symbol","navigatorTitle":[{"text":"LocationServiceObserver","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Observers for getting updates from LocationService."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationServiceObserver","kind":"identifier"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeadingProvider":{"url":"\/documentation\/mapboxmaps\/headingprovider","title":"HeadingProvider","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingProvider","kind":"symbol","navigatorTitle":[{"text":"HeadingProvider","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Provides heading data to drive the location puck."}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"HeadingProvider","kind":"identifier"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Puck2DConfiguration":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Puck2DConfiguration","title":"Puck2DConfiguration","url":"\/documentation\/mapboxmaps\/puck2dconfiguration","navigatorTitle":[{"kind":"identifier","text":"Puck2DConfiguration"}],"abstract":[],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Puck2DConfiguration","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapStyleContent":{"url":"\/documentation\/mapboxmaps\/mapstylecontent","type":"topic","abstract":[{"type":"text","text":"A protocol used to create any type of  map style content, such as layers, sources, lighting and others."}],"kind":"symbol","navigatorTitle":[{"text":"MapStyleContent","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapStyleContent","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MapStyleContent","kind":"identifier"}],"title":"MapStyleContent"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/AccuracyLevel":{"url":"\/documentation\/mapboxcommon\/accuracylevel","title":"AccuracyLevel","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AccuracyLevel"}],"type":"topic","abstract":[{"text":"The accuracy of the observed location","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AccuracyLevel","kind":"identifier"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationErrorCode":{"navigatorTitle":[{"text":"LocationErrorCode","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationErrorCode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LocationErrorCode"}],"role":"symbol","abstract":[{"text":"Codes of location errors.","type":"text"}],"title":"LocationErrorCode","url":"\/documentation\/mapboxcommon\/locationerrorcode"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AppleLocationProviderDelegate":{"title":"AppleLocationProviderDelegate","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProviderDelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AppleLocationProviderDelegate","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/applelocationproviderdelegate","navigatorTitle":[{"kind":"identifier","text":"AppleLocationProviderDelegate"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProviderDelegate","type":"reference","isActive":true},{"text":" protocol defines a set of optional methods that you","type":"text"},{"text":" ","type":"text"},{"text":"can use to receive events from an associated location provider object.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PuckType":{"navigatorTitle":[{"text":"PuckType","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PuckType"}],"role":"symbol","abstract":[{"text":"Represents the different types of pucks","type":"text"}],"title":"PuckType","url":"\/documentation\/mapboxmaps\/pucktype"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Model/init(id:uri:position:orientation:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Model\/init(id:uri:position:orientation:)","title":"init(id:uri:position:orientation:)","abstract":[],"type":"topic","url":"\/documentation\/mapboxmaps\/model\/init(id:uri:position:orientation:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"id"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"uri","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"position"},{"text":": [","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"orientation"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":"]?)","kind":"text"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/DeviceLocationProvider":{"url":"\/documentation\/mapboxcommon\/devicelocationprovider","title":"DeviceLocationProvider","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/DeviceLocationProvider","kind":"symbol","navigatorTitle":[{"text":"DeviceLocationProvider","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Location provider specialisation that provides real-time locations generated from the device"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"DeviceLocationProvider","kind":"identifier"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Heading":{"navigatorTitle":[{"text":"Heading","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Heading","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"Heading","kind":"identifier"}],"role":"symbol","abstract":[{"text":"The azimuth (orientation) of the user’s device, relative to true or magnetic north.","type":"text"}],"title":"Heading","url":"\/documentation\/mapboxmaps\/heading"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Location-APIs":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","title":"Location","kind":"article","url":"\/documentation\/mapboxmaps\/location-apis","type":"topic","role":"collectionGroup","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","abstract":[],"kind":"article","url":"\/documentation\/overview","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/IntervalSettings":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IntervalSettings","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxcommon\/intervalsettings","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/IntervalSettings","role":"symbol","navigatorTitle":[{"text":"IntervalSettings","kind":"identifier"}],"title":"IntervalSettings","abstract":[{"text":"The interval for active location updates","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AppleLocationProvider":{"navigatorTitle":[{"text":"AppleLocationProvider","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/applelocationprovider","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AppleLocationProvider","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProvider","kind":"symbol","title":"AppleLocationProvider","abstract":[{"type":"text","text":"A location provider based on CoreLocation’s "},{"type":"codeVoice","code":"CLLocationManager"},{"type":"text","text":"."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Model":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Model","navigatorTitle":[{"kind":"identifier","text":"Model"}],"title":"Model","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Model"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/model","type":"topic","role":"symbol","abstract":[{"text":"A structure represeting a Model","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PuckRenderingData":{"navigatorTitle":[{"text":"PuckRenderingData","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckRenderingData","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"PuckRenderingData","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Represents the interpolated data ready to render the user location puck."}],"title":"PuckRenderingData","url":"\/documentation\/mapboxmaps\/puckrenderingdata"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Coordinate2D":{"title":"Coordinate2D","abstract":[{"text":"Boxed version of CLLocationCoordinate2D","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Coordinate2D","navigatorTitle":[{"text":"Coordinate2D","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/mapboxcommon\/coordinate2d","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Coordinate2D"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/SE":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SE","title":"Swift.Encodable"},"doc://com.mapbox.MapboxMaps/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s8SendableP","title":"Swift.Sendable"},"doc://com.mapbox.MapboxMaps/Se":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/Se","title":"Swift.Decodable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Model/id":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Model\/id","title":"id","abstract":[{"type":"text","text":"The model’s identifier"}],"type":"topic","url":"\/documentation\/mapboxmaps\/model\/id","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"id"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LocationOptions":{"url":"\/documentation\/mapboxmaps\/locationoptions","title":"LocationOptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationOptions","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"LocationOptions"}],"type":"topic","abstract":[{"type":"text","text":"A struct to configure a "},{"type":"codeVoice","code":"LocationManager"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationOptions","kind":"identifier"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationObserver":{"url":"\/documentation\/mapboxcommon\/locationobserver","role":"symbol","abstract":[{"text":"Observer for getting updates from a LocationProvider.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationObserver","kind":"symbol","navigatorTitle":[{"text":"LocationObserver","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"LocationObserver","kind":"identifier"}],"title":"LocationObserver","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Model/position":{"url":"\/documentation\/mapboxmaps\/model\/position","title":"position","abstract":[{"type":"text","text":"Coordinates of the model in "},{"code":"[longitude, latitude]","type":"codeVoice"},{"text":"format","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"position"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Model\/position","type":"topic","kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeadingObserver":{"url":"\/documentation\/mapboxmaps\/headingobserver","title":"HeadingObserver","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingObserver","kind":"symbol","navigatorTitle":[{"text":"HeadingObserver","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Listens to "},{"isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeadingProvider","type":"reference"},{"type":"text","text":"’s updates."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HeadingObserver"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationError":{"url":"\/documentation\/mapboxcommon\/locationerror","title":"LocationError","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationError","kind":"symbol","navigatorTitle":[{"text":"LocationError","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Error code with brief explanation."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationError","kind":"identifier"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/AccuracyAuthorization":{"navigatorTitle":[{"text":"AccuracyAuthorization","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyAuthorization","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AccuracyAuthorization","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Accuracy authorization granted by user to the app."}],"title":"AccuracyAuthorization","url":"\/documentation\/mapboxcommon\/accuracyauthorization"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Location":{"url":"\/documentation\/mapboxcommon\/location","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location","title":"Location","abstract":[{"type":"text","text":"Location information."}],"kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Location","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Location"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Model/Equatable-Implementations":{"abstract":[],"url":"\/documentation\/mapboxmaps\/model\/equatable-implementations","kind":"article","title":"Equatable Implementations","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Model\/Equatable-Implementations","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LocationManager":{"url":"\/documentation\/mapboxmaps\/locationmanager","title":"LocationManager","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationManager","kind":"symbol","navigatorTitle":[{"text":"LocationManager","kind":"identifier"}],"type":"topic","abstract":[{"text":"An object responsible for managing user location Puck.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LocationManager"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","role":"collection","kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationProvider":{"navigatorTitle":[{"text":"LocationProvider","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationProvider","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Location provider that provides locations"}],"title":"LocationProvider","url":"\/documentation\/mapboxcommon\/locationprovider"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationExtraKeys":{"navigatorTitle":[{"text":"LocationExtraKeys","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationExtraKeys","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationExtraKeys","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Keys for additional information (extra) in Location."}],"title":"LocationExtraKeys","url":"\/documentation\/mapboxcommon\/locationextrakeys"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationServiceFactory":{"url":"\/documentation\/mapboxcommon\/locationservicefactory","title":"LocationServiceFactory","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationServiceFactory","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"LocationServiceFactory"}],"type":"topic","abstract":[{"text":"Location service factory.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"LocationServiceFactory","kind":"identifier"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Model/uri":{"type":"topic","title":"uri","abstract":[{"type":"text","text":"URL to a "},{"code":"gltf","type":"codeVoice"},{"type":"text","text":" 3D asset in the application bundle"}],"url":"\/documentation\/mapboxmaps\/model\/uri","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Model\/uri","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"uri"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Model/init(from:)":{"abstract":[],"url":"\/documentation\/mapboxmaps\/model\/init(from:)","role":"symbol","kind":"symbol","type":"topic","title":"init(from:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Model\/init(from:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}]}},"variantOverrides":[{"patch":[{"value":"MBXLocationProviderRequest","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProviderRequest\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProviderRequest\/fragments","value":[{"text":"MBXLocationProviderRequest","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProviderRequest\/navigatorTitle","value":[{"text":"MBXLocationProviderRequest","kind":"identifier"}],"op":"replace"},{"value":"MBXPermissionStatus","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/fragments","value":[{"kind":"identifier","text":"MBXPermissionStatus"}]},{"op":"replace","value":[{"kind":"identifier","text":"MBXPermissionStatus"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/navigatorTitle"},{"value":"MBXLocationServiceObserver","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBXLocationServiceObserver"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver\/fragments"},{"value":[{"text":"MBXLocationServiceObserver","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceObserver\/navigatorTitle","op":"replace"},{"op":"replace","value":"MBXAccuracyLevel","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel\/fragments","value":[{"text":"MBXAccuracyLevel","kind":"identifier"}]},{"value":[{"text":"MBXAccuracyLevel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/title","value":"MBXLocationErrorCode"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/fragments","value":[{"kind":"identifier","text":"MBXLocationErrorCode"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationErrorCode\/navigatorTitle","value":[{"text":"MBXLocationErrorCode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1DeviceLocationProvider\/title","value":"MBXDeviceLocationProvider","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1DeviceLocationProvider\/fragments","value":[{"kind":"identifier","text":"MBXDeviceLocationProvider"}]},{"value":[{"text":"MBXDeviceLocationProvider","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1DeviceLocationProvider\/navigatorTitle"},{"op":"replace","value":"MBXIntervalSettings","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1IntervalSettings\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1IntervalSettings\/fragments","op":"replace","value":[{"text":"MBXIntervalSettings","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1IntervalSettings\/navigatorTitle","value":[{"kind":"identifier","text":"MBXIntervalSettings"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Coordinate2D\/title","op":"replace","value":"MBXCoordinate2D"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Coordinate2D\/fragments","value":[{"kind":"identifier","text":"MBXCoordinate2D"}]},{"value":[{"text":"MBXCoordinate2D","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Coordinate2D\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/title","value":"MBXLocationObserver"},{"value":[{"text":"MBXLocationObserver","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBXLocationObserver"}]},{"value":"MBXLocationError","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationError\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationError\/fragments","op":"replace","value":[{"text":"MBXLocationError","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationError\/navigatorTitle","value":[{"kind":"identifier","text":"MBXLocationError"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization\/title","value":"MBXAccuracyAuthorization","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization\/fragments","value":[{"kind":"identifier","text":"MBXAccuracyAuthorization"}]},{"op":"replace","value":[{"text":"MBXAccuracyAuthorization","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyAuthorization\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/title","value":"MBXLocation"},{"value":[{"text":"MBXLocation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/fragments"},{"value":[{"text":"MBXLocation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/title","value":"MBXLocationProvider","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/fragments","value":[{"kind":"identifier","text":"MBXLocationProvider"}]},{"value":[{"text":"MBXLocationProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/navigatorTitle","op":"replace"},{"op":"replace","value":"MBXLocationExtraKeys","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationExtraKeys\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationExtraKeys\/fragments","value":[{"kind":"identifier","text":"MBXLocationExtraKeys"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationExtraKeys\/navigatorTitle","value":[{"kind":"identifier","text":"MBXLocationExtraKeys"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceFactory\/title","value":"MBXLocationServiceFactory","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceFactory\/fragments","value":[{"text":"MBXLocationServiceFactory","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationServiceFactory\/navigatorTitle","op":"replace","value":[{"text":"MBXLocationServiceFactory","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}