{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events"]]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"navigatorTitle":[{"text":"RequestPriorityType","kind":"identifier"}],"roleHeading":"Enumeration","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RequestPriorityType"}],"modules":[{"name":"MapboxMaps"}],"externalID":"c:@E@MBMRequestPriorityType","role":"symbol","title":"RequestPriorityType","symbolKind":"enum"},"topicSections":[{"generated":true,"title":"Enumeration Cases","anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestPriorityType\/low","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestPriorityType\/regular"]},{"title":"Initializers","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestPriorityType\/init(rawValue:)"],"anchor":"Initializers"},{"generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestPriorityType\/Equatable-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestPriorityType\/RawRepresentable-Implementations"],"anchor":"Default-Implementations","title":"Default Implementations"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RequestPriorityType"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/requestprioritytype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/requestprioritytype"]}],"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/s15BitwiseCopyableP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH","doc:\/\/com.mapbox.MapboxMaps\/SY","doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"]}],"abstract":[{"text":"The enumeration defines the priority of a resource request.","type":"text"}],"seeAlsoSections":[{"generated":true,"title":"Event payload","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderModeType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestLoadingMethodType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestDataSourceType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResponseSourceType"],"anchor":"Event-payload"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestPriorityType"},"references":{"doc://com.mapbox.MapboxMaps/SQ":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestPriorityType/Equatable-Implementations":{"kind":"article","url":"\/documentation\/mapboxmaps\/requestprioritytype\/equatable-implementations","title":"Equatable Implementations","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestPriorityType\/Equatable-Implementations","abstract":[],"role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestPriorityType/regular":{"navigatorTitle":[{"kind":"identifier","text":"MBMRequestPriorityTypeRegular"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/requestprioritytype\/regular","type":"topic","abstract":[{"type":"text","text":"The request priority is regular."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestPriorityType\/regular","title":"RequestPriorityType.regular","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"regular","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoadingErrorType":{"role":"symbol","kind":"symbol","url":"\/documentation\/mapboxmaps\/maploadingerrortype","type":"topic","title":"MapLoadingErrorType","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapLoadingErrorType","kind":"identifier"}],"navigatorTitle":[{"text":"MapLoadingErrorType","kind":"identifier"}],"abstract":[{"type":"text","text":"The enumeration defines map loading errors."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestLoadingMethodType":{"abstract":[{"type":"text","text":"The enumeration defines the method used to make a resource request."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestLoadingMethodType","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RequestLoadingMethodType","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/requestloadingmethodtype","title":"RequestLoadingMethodType","kind":"symbol","type":"topic","navigatorTitle":[{"text":"RequestLoadingMethodType","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceDataLoadedType":{"role":"symbol","kind":"symbol","url":"\/documentation\/mapboxmaps\/sourcedataloadedtype","type":"topic","title":"SourceDataLoadedType","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SourceDataLoadedType","kind":"identifier"}],"navigatorTitle":[{"text":"SourceDataLoadedType","kind":"identifier"}],"abstract":[{"type":"text","text":"The enumeration defines the type of loaded source data."}]},"doc://com.mapbox.MapboxMaps/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestPriorityType/init(rawValue:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestPriorityType\/init(rawValue:)","role":"symbol","title":"init(rawValue:)","url":"\/documentation\/mapboxmaps\/requestprioritytype\/init(rawvalue:)","abstract":[],"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleDataLoadedType":{"role":"symbol","kind":"symbol","url":"\/documentation\/mapboxmaps\/styledataloadedtype","type":"topic","title":"StyleDataLoadedType","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StyleDataLoadedType","kind":"identifier"}],"navigatorTitle":[{"text":"StyleDataLoadedType","kind":"identifier"}],"abstract":[{"type":"text","text":"The enumeration defines the type of loaded style data."}]},"doc://com.mapbox.MapboxMaps/SY":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/s15BitwiseCopyableP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s15BitwiseCopyableP","title":"Swift.BitwiseCopyable","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestDataSourceType":{"role":"symbol","kind":"symbol","url":"\/documentation\/mapboxmaps\/requestdatasourcetype","type":"topic","title":"RequestDataSourceType","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestDataSourceType","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"RequestDataSourceType","kind":"identifier"}],"navigatorTitle":[{"text":"RequestDataSourceType","kind":"identifier"}],"abstract":[{"type":"text","text":"The enumeration defines the type of data source."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","role":"collection","kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","abstract":[],"kind":"article","url":"\/documentation\/overview","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestResourceType":{"url":"\/documentation\/mapboxmaps\/requestresourcetype","title":"RequestResourceType","kind":"symbol","navigatorTitle":[{"text":"RequestResourceType","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"The enumeration defines the type of resource requested by the "},{"type":"codeVoice","code":"map"},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"RequestResourceType","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"url":"\/documentation\/mapboxmaps\/events","role":"collectionGroup","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","abstract":[{"type":"text","text":"The simplified diagram of the events emitted by the map is displayed below."}],"type":"topic","title":"Map events"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestPriorityType":{"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestPriorityType","title":"RequestPriorityType","url":"\/documentation\/mapboxmaps\/requestprioritytype","abstract":[{"text":"The enumeration defines the priority of a resource request.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RequestPriorityType"}],"navigatorTitle":[{"text":"RequestPriorityType","kind":"identifier"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResponseSourceType":{"role":"symbol","kind":"symbol","url":"\/documentation\/mapboxmaps\/responsesourcetype","type":"topic","title":"ResponseSourceType","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResponseSourceType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ResponseSourceType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ResponseSourceType"}],"abstract":[{"type":"text","text":"The enumeration defines the source type that provides the requested resource."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderModeType":{"type":"topic","navigatorTitle":[{"text":"RenderModeType","kind":"identifier"}],"kind":"symbol","title":"RenderModeType","abstract":[{"text":"The enumeration defines the rendering mode for the rendered frame.","type":"text"}],"url":"\/documentation\/mapboxmaps\/rendermodetype","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderModeType","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"RenderModeType"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestPriorityType/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","url":"\/documentation\/mapboxmaps\/requestprioritytype\/rawrepresentable-implementations","type":"topic","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestPriorityType\/RawRepresentable-Implementations","abstract":[],"kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestPriorityType/low":{"navigatorTitle":[{"kind":"identifier","text":"MBMRequestPriorityTypeLow"}],"url":"\/documentation\/mapboxmaps\/requestprioritytype\/low","abstract":[{"text":"The request priority is low, and the regular requests are of higher priority","type":"text"},{"type":"text","text":" "},{"text":"than the low-priority requests.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestPriorityType\/low","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"low","kind":"identifier"}],"role":"symbol","type":"topic","title":"RequestPriorityType.low"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"MBMRequestPriorityType"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"MBMRequestPriorityType","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBMRequestPriorityType"}],"path":"\/metadata\/navigatorTitle"},{"value":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestPriorityType\/low","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestPriorityType\/regular"],"generated":true}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDataLoadedType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingErrorType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderModeType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestLoadingMethodType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestResourceType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestDataSourceType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResponseSourceType"],"generated":true,"anchor":"Event-payload","title":"Event payload"}],"path":"\/seeAlsoSections","op":"replace"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"MBMRequestPriorityType","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestPriorityType~1regular\/title","op":"replace","value":"MBMRequestPriorityTypeRegular"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestPriorityType~1regular\/fragments","value":[{"text":"MBMRequestPriorityTypeRegular","kind":"identifier"}],"op":"replace"},{"value":"MBMMapLoadingErrorType","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorType\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorType\/fragments","value":[{"text":"MBMMapLoadingErrorType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingErrorType\/navigatorTitle","op":"replace","value":[{"text":"MBMMapLoadingErrorType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestLoadingMethodType\/title","value":"MBMRequestLoadingMethodType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestLoadingMethodType\/fragments","value":[{"kind":"identifier","text":"MBMRequestLoadingMethodType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestLoadingMethodType\/navigatorTitle","value":[{"kind":"identifier","text":"MBMRequestLoadingMethodType"}]},{"value":"MBMSourceDataLoadedType","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedType\/title"},{"value":[{"text":"MBMSourceDataLoadedType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedType\/fragments"},{"value":[{"text":"MBMSourceDataLoadedType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedType\/navigatorTitle","op":"replace"},{"value":"MBMStyleDataLoadedType","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedType\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedType\/fragments","op":"replace","value":[{"text":"MBMStyleDataLoadedType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleDataLoadedType\/navigatorTitle","value":[{"kind":"identifier","text":"MBMStyleDataLoadedType"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestDataSourceType\/title","value":"MBMRequestDataSourceType"},{"value":[{"kind":"identifier","text":"MBMRequestDataSourceType"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestDataSourceType\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestDataSourceType\/navigatorTitle","value":[{"text":"MBMRequestDataSourceType","kind":"identifier"}],"op":"replace"},{"value":"MBMRequestResourceType","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestResourceType\/title","op":"replace"},{"op":"replace","value":[{"text":"MBMRequestResourceType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestResourceType\/fragments"},{"value":[{"kind":"identifier","text":"MBMRequestResourceType"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestResourceType\/navigatorTitle","op":"replace"},{"op":"replace","value":"MBMRequestPriorityType","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestPriorityType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestPriorityType\/fragments","value":[{"kind":"identifier","text":"MBMRequestPriorityType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestPriorityType\/navigatorTitle","value":[{"text":"MBMRequestPriorityType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResponseSourceType\/title","value":"MBMResponseSourceType"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResponseSourceType\/fragments","value":[{"kind":"identifier","text":"MBMResponseSourceType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResponseSourceType\/navigatorTitle","op":"replace","value":[{"text":"MBMResponseSourceType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderModeType\/title","value":"MBMRenderModeType"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderModeType\/fragments","value":[{"kind":"identifier","text":"MBMRenderModeType"}]},{"op":"replace","value":[{"kind":"identifier","text":"MBMRenderModeType"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderModeType\/navigatorTitle"},{"value":"MBMRequestPriorityTypeLow","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestPriorityType~1low\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestPriorityType~1low\/fragments","value":[{"kind":"identifier","text":"MBMRequestPriorityTypeLow"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}