{"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"localFile","kind":"identifier"}],"platforms":["iOS"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResponseSourceType"]]},"kind":"symbol","metadata":{"modules":[{"name":"MapboxMaps"}],"symbolKind":"case","title":"ResponseSourceType.localFile","navigatorTitle":[{"text":"MBMResponseSourceTypeLocalFile","kind":"identifier"}],"roleHeading":"Case","role":"symbol","externalID":"c:@E@MBMResponseSourceType@MBMResponseSourceTypeLocalFile","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"localFile"}]},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResponseSourceType\/localFile","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The source of the response is the local filesystem. This type is used for"},{"text":" ","type":"text"},{"text":"responses from the ","type":"text"},{"type":"codeVoice","code":"Asset"},{"text":" and ","type":"text"},{"code":"FileSystem","type":"codeVoice"},{"type":"text","text":" data source types."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/responsesourcetype\/localfile"]},{"paths":["\/documentation\/mapboxmaps\/responsesourcetype\/localfile"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"role":"collection","url":"\/documentation\/mapboxmaps","title":"MapboxMaps","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResponseSourceType/localFile":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/responsesourcetype\/localfile","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResponseSourceType\/localFile","type":"topic","title":"ResponseSourceType.localFile","navigatorTitle":[{"text":"MBMResponseSourceTypeLocalFile","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"localFile","kind":"identifier"}],"abstract":[{"type":"text","text":"The source of the response is the local filesystem. This type is used for"},{"type":"text","text":" "},{"type":"text","text":"responses from the "},{"code":"Asset","type":"codeVoice"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"FileSystem"},{"type":"text","text":" data source types."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","url":"\/documentation\/mapboxmaps\/events","kind":"article","abstract":[{"type":"text","text":"The simplified diagram of the events emitted by the map is displayed below."}],"role":"collectionGroup","title":"Map events"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","kind":"article","abstract":[],"url":"\/documentation\/overview","type":"topic","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResponseSourceType":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ResponseSourceType","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/responsesourcetype","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResponseSourceType","navigatorTitle":[{"text":"ResponseSourceType","kind":"identifier"}],"abstract":[{"type":"text","text":"The enumeration defines the source type that provides the requested resource."}],"type":"topic","kind":"symbol","title":"ResponseSourceType","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"MBMResponseSourceTypeLocalFile","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MBMResponseSourceTypeLocalFile","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"MBMResponseSourceTypeLocalFile"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"MBMResponseSourceTypeLocalFile","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResponseSourceType~1localFile\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResponseSourceType~1localFile\/fragments","op":"replace","value":[{"text":"MBMResponseSourceTypeLocalFile","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResponseSourceType\/title","value":"MBMResponseSourceType"},{"op":"replace","value":[{"kind":"identifier","text":"MBMResponseSourceType"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResponseSourceType\/fragments"},{"op":"replace","value":[{"text":"MBMResponseSourceType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResponseSourceType\/navigatorTitle"}]}]}