{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SwiftUI","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onRenderFrameFinished"},{"text":"(","kind":"text"},{"text":"action","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"keyword","text":"@escaping"},{"text":" (","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinished","preciseIdentifier":"c:objc(cs)MBMRenderFrameFinished","text":"RenderFrameFinished"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map","preciseIdentifier":"s:10MapboxMaps3MapV","kind":"typeIdentifier","text":"Map"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"style":"important","content":[{"type":"paragraph","inlineContent":[{"text":"This callback is called on every rendering frame, don’t modify ","type":"text"},{"type":"codeVoice","code":"@State"},{"text":" in it. Consult ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onCameraChanged(action:)","type":"reference"},{"type":"text","text":" for more information."}]}],"name":"Important","type":"aside"}]}],"variants":[{"paths":["\/documentation\/mapboxmaps\/map\/onrenderframefinished(action:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Adds an action to perform when the map finished rendering a frame.","type":"text"}],"metadata":{"externalID":"s:10MapboxMaps3MapV21onRenderFrameFinished6actionACySo09MBMRenderfG0Cc_tF","roleHeading":"Instance Method","title":"onRenderFrameFinished(action:)","modules":[{"name":"MapboxMaps"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onRenderFrameFinished"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"text":": (","kind":"text"},{"text":"RenderFrameFinished","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMRenderFrameFinished"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps3MapV","text":"Map","kind":"typeIdentifier"}],"extendedModule":"MapboxMaps","role":"symbol","platforms":[{"deprecated":false,"unavailable":false,"introducedAt":"13.0","name":"iOS","beta":false},{"beta":false,"introducedAt":"13.0","name":"iPadOS","deprecated":false,"unavailable":false},{"deprecated":false,"introducedAt":"13.0","name":"Mac Catalyst","beta":false,"unavailable":false}],"symbolKind":"method"},"kind":"symbol","identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onRenderFrameFinished(action:)","interfaceLanguage":"swift"},"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","title":"MapboxMaps Documentation","kind":"article","url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/onRenderFrameFinished(action:)":{"url":"\/documentation\/mapboxmaps\/map\/onrenderframefinished(action:)","title":"onRenderFrameFinished(action:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onRenderFrameFinished"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"text":": (","kind":"text"},{"text":"RenderFrameFinished","preciseIdentifier":"c:objc(cs)MBMRenderFrameFinished","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps3MapV","text":"Map","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onRenderFrameFinished(action:)","abstract":[{"type":"text","text":"Adds an action to perform when the map finished rendering a frame."}],"role":"symbol","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","title":"MapboxMaps","kind":"symbol","url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SwiftUI":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SwiftUI","kind":"article","role":"collectionGroup","type":"topic","url":"\/documentation\/mapboxmaps\/swiftui","abstract":[],"title":"SwiftUI"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderFrameFinished":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"RenderFrameFinished","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The "},{"code":"map","type":"codeVoice"},{"type":"text","text":" finished rendering a frame."}],"url":"\/documentation\/mapboxmaps\/renderframefinished","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinished","navigatorTitle":[{"text":"RenderFrameFinished","kind":"identifier"}],"title":"RenderFrameFinished","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map":{"url":"\/documentation\/mapboxmaps\/map","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map","abstract":[{"text":"A SwiftUI view that displays a Mapbox Map.","type":"text"}],"type":"topic","title":"Map","navigatorTitle":[{"kind":"identifier","text":"Map"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Map"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map/onCameraChanged(action:)":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map\/onCameraChanged(action:)","url":"\/documentation\/mapboxmaps\/map\/oncamerachanged(action:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onCameraChanged"},{"kind":"text","text":"("},{"text":"action","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"CameraChanged","preciseIdentifier":"c:objc(cs)MBMCameraChanged","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps3MapV","text":"Map"}],"type":"topic","title":"onCameraChanged(action:)","abstract":[{"type":"text","text":"Adds an action to perform when the camera is changed."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinished\/title","value":"MBMRenderFrameFinished"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinished\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMRenderFrameFinished"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinished\/navigatorTitle","op":"replace","value":[{"text":"MBMRenderFrameFinished","kind":"identifier"}]}]}]}