{"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"If set to "},{"code":"true","type":"codeVoice"},{"type":"text","text":", an infinite (unconstrained) bounds covering the world coordinates would be used."},{"text":" ","type":"text"},{"text":"Coordinates provided in ","type":"text"},{"code":"southwest","type":"codeVoice"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"northeast"},{"type":"text","text":" fields would be omitted and have no effect."}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"infiniteBounds"}],"title":"infiniteBounds","role":"symbol","externalID":"c:objc(cs)MBMCoordinateBounds(py)infiniteBounds","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"infiniteBounds","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"MapboxMaps"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds\/infiniteBounds"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"infiniteBounds","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/coordinatebounds\/infinitebounds"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/coordinatebounds\/infinitebounds"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","kind":"article","abstract":[],"url":"\/documentation\/overview","type":"topic","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"role":"collection","url":"\/documentation\/mapboxmaps","title":"MapboxMaps","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","kind":"article","url":"\/documentation\/mapboxmaps\/mapboxmap-apis","title":"MapboxMap","type":"topic","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateBounds":{"navigatorTitle":[{"kind":"identifier","text":"CoordinateBounds"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"CoordinateBounds","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/coordinatebounds","kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"A rectangular area as measured on a two-dimensional map projection.","type":"text"}],"title":"CoordinateBounds","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateBounds/infiniteBounds":{"role":"symbol","navigatorTitle":[{"text":"infiniteBounds","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds\/infiniteBounds","title":"infiniteBounds","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"infiniteBounds","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"url":"\/documentation\/mapboxmaps\/coordinatebounds\/infinitebounds","kind":"symbol","type":"topic","abstract":[{"text":"If set to ","type":"text"},{"type":"codeVoice","code":"true"},{"type":"text","text":", an infinite (unconstrained) bounds covering the world coordinates would be used."},{"type":"text","text":" "},{"type":"text","text":"Coordinates provided in "},{"code":"southwest","type":"codeVoice"},{"type":"text","text":" and "},{"code":"northeast","type":"codeVoice"},{"type":"text","text":" fields would be omitted and have no effect."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"infiniteBounds"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"infiniteBounds"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"infiniteBounds","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds\/title","op":"replace","value":"MBMCoordinateBounds"},{"value":[{"text":"MBMCoordinateBounds","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds\/fragments"},{"value":[{"kind":"identifier","text":"MBMCoordinateBounds"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds~1infiniteBounds\/title","op":"replace","value":"infiniteBounds"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds~1infiniteBounds\/fragments","value":[{"kind":"identifier","text":"infiniteBounds"}],"op":"replace"}]}]}