{"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResponseSourceType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResponseSourceType\/Equatable-Implementations"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"internalParam","text":"lhs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"internalParam","text":"rhs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]}],"kind":"declarations"}],"sections":[],"metadata":{"symbolKind":"op","extendedModule":"Swift","roleHeading":"Operator","title":"!=(_:_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::c:@E@MBMResponseSourceType","role":"symbol","modules":[{"name":"MapboxMaps","relatedModules":["Swift"]}]},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResponseSourceType\/!=(_:_:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/mapboxmaps\/responsesourcetype\/!=(_:_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"code":"Equatable.!=(_:_:)","type":"codeVoice"},{"type":"text","text":"."}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","role":"collection","title":"MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","type":"topic","abstract":[],"title":"MapboxMaps Documentation","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResponseSourceType":{"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResponseSourceType"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResponseSourceType"}],"title":"ResponseSourceType","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResponseSourceType","url":"\/documentation\/mapboxmaps\/responsesourcetype","abstract":[{"type":"text","text":"The enumeration defines the source type that provides the requested resource."}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResponseSourceType/Equatable-Implementations":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResponseSourceType\/Equatable-Implementations","kind":"article","url":"\/documentation\/mapboxmaps\/responsesourcetype\/equatable-implementations","title":"Equatable Implementations","role":"collectionGroup","type":"topic","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","title":"Map events","kind":"article","abstract":[{"text":"The simplified diagram of the events emitted by the map is displayed below.","type":"text"}],"role":"collectionGroup","type":"topic","url":"\/documentation\/mapboxmaps\/events"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResponseSourceType/!=(_:_:)":{"abstract":[],"kind":"symbol","title":"!=(_:_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResponseSourceType\/!=(_:_:)","type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/responsesourcetype\/!=(_:_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResponseSourceType\/title","value":"MBMResponseSourceType","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResponseSourceType\/fragments","value":[{"kind":"identifier","text":"MBMResponseSourceType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResponseSourceType\/navigatorTitle","value":[{"kind":"identifier","text":"MBMResponseSourceType"}],"op":"replace"}]}]}