{"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NetworkRestriction\/disallowExpensive","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"MapboxCommon"}],"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"disallowExpensive"}],"externalID":"c:@E@MBXNetworkRestriction@MBXNetworkRestrictionDisallowExpensive","roleHeading":"Case","navigatorTitle":[{"text":"MBXNetworkRestrictionDisallowExpensive","kind":"identifier"}],"role":"symbol","title":"NetworkRestriction.disallowExpensive"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/networkrestriction\/disallowexpensive"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/networkrestriction\/disallowexpensive"]}],"kind":"symbol","abstract":[{"text":"Forbid network access to expensive networks, such as cellular.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disallowExpensive","kind":"identifier"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NetworkRestriction"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"url":"\/documentation\/mapboxcommon","type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","title":"MapboxCommon","abstract":[],"role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/NetworkRestriction":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NetworkRestriction","title":"NetworkRestriction","abstract":[{"type":"text","text":"Classify network types based on cost."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"NetworkRestriction","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxcommon\/networkrestriction","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NetworkRestriction"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/NetworkRestriction/disallowExpensive":{"abstract":[{"type":"text","text":"Forbid network access to expensive networks, such as cellular."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"disallowExpensive","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NetworkRestriction\/disallowExpensive","title":"NetworkRestriction.disallowExpensive","url":"\/documentation\/mapboxcommon\/networkrestriction\/disallowexpensive","role":"symbol","navigatorTitle":[{"text":"MBXNetworkRestrictionDisallowExpensive","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","type":"topic","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","abstract":[],"role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"MBXNetworkRestrictionDisallowExpensive","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MBXNetworkRestrictionDisallowExpensive","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"MBXNetworkRestrictionDisallowExpensive"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"MBXNetworkRestriction","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1NetworkRestriction\/title","op":"replace"},{"value":[{"text":"MBXNetworkRestriction","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1NetworkRestriction\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1NetworkRestriction\/navigatorTitle","value":[{"kind":"identifier","text":"MBXNetworkRestriction"}]},{"op":"replace","value":"MBXNetworkRestrictionDisallowExpensive","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1NetworkRestriction~1disallowExpensive\/title"},{"value":[{"kind":"identifier","text":"MBXNetworkRestrictionDisallowExpensive"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1NetworkRestriction~1disallowExpensive\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}