{"abstract":[{"text":"Helper function for setting the mercator position as Lat&Lng coordinate.","type":"text"}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMFreeCameraOptions\/setLocationForLocation:","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/mbmfreecameraoptions\/setlocationforlocation:"]}],"metadata":{"roleHeading":"Instance Method","role":"symbol","title":"setLocationForLocation:","symbolKind":"method","modules":[{"name":"MapboxMaps"}],"navigatorTitle":[{"text":"setLocationForLocation:","kind":"identifier"}],"fragments":[{"kind":"text","text":"- "},{"text":"setLocationForLocation:","kind":"identifier"}],"externalID":"c:objc(cs)MBMFreeCameraOptions(im)setLocationForLocation:"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"setLocationForLocation:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"location","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},{"parameters":[{"name":"location","content":[{"type":"paragraph","inlineContent":[{"text":"The mercator ","type":"text"},{"type":"codeVoice","code":"coordinate"},{"text":".","type":"text"}]}]}],"kind":"parameters"}],"sections":[],"kind":"symbol","references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMFreeCameraOptions/setLocationForLocation:":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setLocationForLocation:"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMFreeCameraOptions\/setLocationForLocation:","navigatorTitle":[{"kind":"identifier","text":"setLocationForLocation:"}],"kind":"symbol","title":"setLocationForLocation:","abstract":[{"type":"text","text":"Helper function for setting the mercator position as Lat&Lng coordinate."}],"role":"symbol","url":"\/documentation\/mapboxmaps\/mbmfreecameraoptions\/setlocationforlocation:"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","type":"topic","abstract":[],"kind":"article","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/mapboxmap-apis","title":"MapboxMap"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","type":"topic","title":"MapboxMaps","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FreeCameraOptions":{"title":"FreeCameraOptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions","url":"\/documentation\/mapboxmaps\/freecameraoptions","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FreeCameraOptions","kind":"identifier"}],"abstract":[{"text":"Various options for accessing physical properties of the underlying camera entity.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"A direct access to these properties allows more flexible and precise controlling"},{"text":" ","type":"text"},{"type":"text","text":"of the camera while also being fully compatible and interchangeable with CameraOptions."},{"type":"text","text":" "},{"text":"All fields are optional.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"FreeCameraOptions","kind":"identifier"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","abstract":[],"url":"\/documentation\/overview","role":"collection","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions\/title","value":"MBMFreeCameraOptions","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions\/fragments","value":[{"text":"MBMFreeCameraOptions","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"MBMFreeCameraOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions\/navigatorTitle"}]}]}