{"sections":[],"kind":"symbol","abstract":[{"text":"Source layer id for a queried feature. May be null if source does not support layers, e.g., ‘geojson’ source,","type":"text"},{"text":" ","type":"text"},{"text":"or when data provided by the source is not layered.","type":"text"}],"metadata":{"title":"sourceLayer","navigatorTitle":[{"kind":"identifier","text":"sourceLayer"}],"externalID":"c:objc(cs)MBMQueriedFeature(py)sourceLayer","modules":[{"name":"MapboxMaps"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"sourceLayer","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property","role":"symbol","symbolKind":"property"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"sourceLayer","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedFeature"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMQueriedFeature\/sourceLayer"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/mbmqueriedfeature\/sourcelayer"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/mbmqueriedfeature\/sourcelayer"]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/QueriedFeature":{"abstract":[{"text":"Represents queried feature that is returned through ","type":"text"},{"type":"codeVoice","code":"QueriedRenderedFeature"},{"text":" or ","type":"text"},{"type":"codeVoice","code":"QueriedSourceFeature"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"QueriedFeature"}],"title":"QueriedFeature","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"QueriedFeature"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedFeature","url":"\/documentation\/mapboxmaps\/queriedfeature"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","url":"\/documentation\/mapboxmaps\/mapboxmap-apis","kind":"article","title":"MapboxMap","role":"collectionGroup","type":"topic","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMQueriedFeature/sourceLayer":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMQueriedFeature\/sourceLayer","url":"\/documentation\/mapboxmaps\/mbmqueriedfeature\/sourcelayer","abstract":[{"text":"Source layer id for a queried feature. May be null if source does not support layers, e.g., ‘geojson’ source,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"or when data provided by the source is not layered."}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"sourceLayer","kind":"identifier"}],"title":"sourceLayer","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sourceLayer","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"sourceLayer"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"sourceLayer","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"sourceLayer"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedFeature\/title","value":"MBMQueriedFeature"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedFeature\/fragments","op":"replace","value":[{"text":"MBMQueriedFeature","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMQueriedFeature~1sourceLayer\/title","value":"sourceLayer"},{"value":[{"kind":"identifier","text":"sourceLayer"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMQueriedFeature~1sourceLayer\/fragments","op":"replace"}]}]}