{"abstract":[{"text":"Helper function for getting current altitude in meters","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"getAltitude"},{"kind":"text","text":";"}]}],"kind":"declarations"},{"content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"inlineContent":[{"type":"text","text":"The altitude in meters."}],"type":"paragraph"}],"kind":"content"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/mbmfreecameraoptions\/getaltitude"]}],"sections":[],"metadata":{"title":"getAltitude","modules":[{"name":"MapboxMaps"}],"symbolKind":"method","role":"symbol","navigatorTitle":[{"text":"getAltitude","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"getAltitude","kind":"identifier"}],"roleHeading":"Instance Method","externalID":"c:objc(cs)MBMFreeCameraOptions(im)getAltitude"},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMFreeCameraOptions\/getAltitude","interfaceLanguage":"occ"},"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","kind":"article","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMFreeCameraOptions/getAltitude":{"role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getAltitude"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"getAltitude"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMFreeCameraOptions\/getAltitude","abstract":[{"text":"Helper function for getting current altitude in meters","type":"text"}],"url":"\/documentation\/mapboxmaps\/mbmfreecameraoptions\/getaltitude","title":"getAltitude"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","role":"collectionGroup","title":"MapboxMap","type":"topic","kind":"article","abstract":[],"url":"\/documentation\/mapboxmaps\/mapboxmap-apis"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","url":"\/documentation\/mapboxmaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FreeCameraOptions":{"role":"symbol","abstract":[{"type":"text","text":"Various options for accessing physical properties of the underlying camera entity."},{"type":"text","text":" "},{"type":"text","text":"A direct access to these properties allows more flexible and precise controlling"},{"type":"text","text":" "},{"type":"text","text":"of the camera while also being fully compatible and interchangeable with CameraOptions."},{"type":"text","text":" "},{"type":"text","text":"All fields are optional."}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FreeCameraOptions","title":"FreeCameraOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FreeCameraOptions"}],"navigatorTitle":[{"kind":"identifier","text":"FreeCameraOptions"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/freecameraoptions"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions\/title","value":"MBMFreeCameraOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions\/fragments","value":[{"kind":"identifier","text":"MBMFreeCameraOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FreeCameraOptions\/navigatorTitle","value":[{"kind":"identifier","text":"MBMFreeCameraOptions"}]}]}]}