{"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/mapboxmaps\/mbmprojectedmeters\/northing"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/mbmprojectedmeters\/northing"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Camera-and-coordinates","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ProjectedMeters"],["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Camera-and-coordinates","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ProjectedMeters"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"northing","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"Projected meters in north direction."}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMProjectedMeters\/northing","interfaceLanguage":"swift"},"metadata":{"role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MBMProjectedMeters(py)northing","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"northing","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"modules":[{"name":"MapboxMaps"}],"navigatorTitle":[{"kind":"identifier","text":"northing"}],"title":"northing","roleHeading":"Instance Property"},"kind":"symbol","sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMProjectedMeters/northing":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMProjectedMeters\/northing","kind":"symbol","type":"topic","navigatorTitle":[{"text":"northing","kind":"identifier"}],"abstract":[{"text":"Projected meters in north direction.","type":"text"}],"url":"\/documentation\/mapboxmaps\/mbmprojectedmeters\/northing","title":"northing","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"northing","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","url":"\/documentation\/mapboxmaps\/mapboxmap-apis","kind":"article","title":"MapboxMap","role":"collectionGroup","type":"topic","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Camera-and-coordinates":{"url":"\/documentation\/mapboxmaps\/camera-and-coordinates","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Camera-and-coordinates","type":"topic","title":"Camera and coordinates","abstract":[],"role":"collectionGroup","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"http://docs.openlayers.org/library/spherical_mercator.html":{"title":"Spherical Mercator","identifier":"http:\/\/docs.openlayers.org\/library\/spherical_mercator.html","titleInlineContent":[{"text":"Spherical Mercator","type":"text"}],"type":"link","url":"http:\/\/docs.openlayers.org\/library\/spherical_mercator.html"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ProjectedMeters":{"role":"symbol","abstract":[{"type":"text","text":"ProjectedMeters is a coordinate in a specific"},{"type":"text","text":" "},{"identifier":"http:\/\/docs.openlayers.org\/library\/spherical_mercator.html","isActive":true,"type":"reference"},{"type":"text","text":" projection."}],"title":"ProjectedMeters","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ProjectedMeters","kind":"identifier"}],"navigatorTitle":[{"text":"ProjectedMeters","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ProjectedMeters","url":"\/documentation\/mapboxmaps\/projectedmeters","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"northing"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"northing"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"kind":"text","text":" "},{"text":"northing","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"value":"northing","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMProjectedMeters~1northing\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMProjectedMeters~1northing\/fragments","op":"replace","value":[{"text":"northing","kind":"identifier"}]},{"value":"MBMProjectedMeters","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ProjectedMeters\/title"},{"value":[{"kind":"identifier","text":"MBMProjectedMeters"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ProjectedMeters\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}