{"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXTileStore\/loadTileRegionForId:loadOptions:","interfaceLanguage":"occ"},"metadata":{"modules":[{"name":"MapboxCommon"}],"role":"symbol","navigatorTitle":[{"text":"loadTileRegionForId:loadOptions:","kind":"identifier"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadTileRegionForId:loadOptions:"}],"title":"loadTileRegionForId:loadOptions:","roleHeading":"Instance Method","symbolKind":"method","externalID":"c:objc(cs)MBXTileStore(im)loadTileRegionForId:loadOptions:"},"abstract":[{"text":"An overloaded version that does not report progess or finished status of the loading operation.","type":"text"}],"variants":[{"paths":["\/documentation\/mapboxcommon\/mbxtilestore\/loadtileregionforid:loadoptions:"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)MBXCancelable","text":"id<MBXCancelable>"},{"text":") ","kind":"text"},{"kind":"identifier","text":"loadTileRegionForId:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"id_","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loadOptions:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBXTileRegionLoadOptions","text":"MBXTileRegionLoadOptions","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"loadOptions"},{"kind":"text","text":";"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The tile region load options."}]}],"name":"loadOptions"}]},{"kind":"content","content":[{"text":"Return Value","level":2,"anchor":"return-value","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Returns a Cancelable object to cancel the load request"}]}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileStore":{"url":"\/documentation\/mapboxcommon\/tilestore","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TileStore","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"TileStore","kind":"identifier"}],"title":"TileStore","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore","abstract":[{"type":"text","text":"TileStore manages downloads and storage for requests to tile-related API endpoints, enforcing a disk usage"},{"type":"text","text":" "},{"text":"quota: tiles available on disk may be deleted to make room for a new download. This interface can be used by an","type":"text"},{"type":"text","text":" "},{"text":"app developer to set the disk quota. The rest of TileStore API is intended for native SDK consumption only.","type":"text"}],"type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"title":"TileStore APIs","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","url":"\/documentation\/mapboxmaps\/tilestore-apis","kind":"article","abstract":[],"role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXTileStore/loadTileRegionForId:loadOptions:":{"navigatorTitle":[{"text":"loadTileRegionForId:loadOptions:","kind":"identifier"}],"title":"loadTileRegionForId:loadOptions:","kind":"symbol","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"loadTileRegionForId:loadOptions:","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/mbxtilestore\/loadtileregionforid:loadoptions:","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXTileStore\/loadTileRegionForId:loadOptions:","abstract":[{"type":"text","text":"An overloaded version that does not report progess or finished status of the loading operation."}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadOptions":{"url":"\/documentation\/mapboxcommon\/tileregionloadoptions","type":"topic","navigatorTitle":[{"text":"TileRegionLoadOptions","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TileRegionLoadOptions"}],"role":"symbol","abstract":[{"type":"text","text":"Describes the tile region load option values."}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions","title":"TileRegionLoadOptions"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","abstract":[],"kind":"article","role":"collection","url":"\/documentation\/overview"}},"variantOverrides":[{"patch":[{"value":"MBXTileStore","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/fragments","value":[{"kind":"identifier","text":"MBXTileStore"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/navigatorTitle","value":[{"text":"MBXTileStore","kind":"identifier"}],"op":"replace"},{"value":"MBXTileRegionLoadOptions","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBXTileRegionLoadOptions"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBXTileRegionLoadOptions"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}