{"sections":[],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ConstrainMode\/RawRepresentable-Implementations","interfaceLanguage":"swift"},"topicSections":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ConstrainMode\/hashValue"],"title":"Instance Properties"},{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ConstrainMode\/hash(into:)"],"title":"Instance Methods"}],"kind":"article","metadata":{"modules":[{"name":"MapboxMaps"}],"roleHeading":"API Collection","title":"RawRepresentable Implementations","role":"collectionGroup"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-View","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ConstrainMode"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map-View":{"type":"topic","title":"MapView","url":"\/documentation\/mapboxmaps\/map-view","abstract":[],"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-View","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ConstrainMode/hashValue":{"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"url":"\/documentation\/mapboxmaps\/constrainmode\/hashvalue","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ConstrainMode\/hashValue","type":"topic","title":"hashValue","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ConstrainMode/hash(into:)":{"title":"hash(into:)","role":"symbol","url":"\/documentation\/mapboxmaps\/constrainmode\/hash(into:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ConstrainMode\/hash(into:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:s6HasherV","text":"Hasher","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","abstract":[],"conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"availabilityPrefix":[{"type":"text","text":"Available when"}]}},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","role":"collection","title":"MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ConstrainMode":{"url":"\/documentation\/mapboxmaps\/constrainmode","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConstrainMode","kind":"identifier"}],"abstract":[{"type":"text","text":"Describes whether to constrain the map in both axes or only vertically e.g. while panning."}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"ConstrainMode","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ConstrainMode","title":"ConstrainMode"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","url":"\/documentation\/overview","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","kind":"article","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ConstrainMode\/title","op":"replace","value":"MBMConstrainMode"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ConstrainMode\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMConstrainMode"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ConstrainMode\/navigatorTitle","op":"replace","value":[{"text":"MBMConstrainMode","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}