{"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Constrain both width and height axes."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"widthAndHeight","kind":"identifier"}]}]}],"variants":[{"paths":["\/documentation\/mapboxmaps\/constrainmode\/widthandheight"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/constrainmode\/widthandheight"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"role":"symbol","title":"ConstrainMode.widthAndHeight","navigatorTitle":[{"kind":"identifier","text":"MBMConstrainModeWidthAndHeight"}],"roleHeading":"Case","modules":[{"name":"MapboxMaps"}],"symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"widthAndHeight"}],"externalID":"c:@E@MBMConstrainMode@MBMConstrainModeWidthAndHeight"},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ConstrainMode\/widthAndHeight","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-View","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ConstrainMode"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ConstrainMode/widthAndHeight":{"abstract":[{"text":"Constrain both width and height axes.","type":"text"}],"url":"\/documentation\/mapboxmaps\/constrainmode\/widthandheight","navigatorTitle":[{"text":"MBMConstrainModeWidthAndHeight","kind":"identifier"}],"type":"topic","title":"ConstrainMode.widthAndHeight","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ConstrainMode\/widthAndHeight","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"widthAndHeight","kind":"identifier"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","url":"\/documentation\/overview","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","kind":"article","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map-View":{"type":"topic","title":"MapView","url":"\/documentation\/mapboxmaps\/map-view","abstract":[],"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-View","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ConstrainMode":{"url":"\/documentation\/mapboxmaps\/constrainmode","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConstrainMode","kind":"identifier"}],"abstract":[{"type":"text","text":"Describes whether to constrain the map in both axes or only vertically e.g. while panning."}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"ConstrainMode","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ConstrainMode","title":"ConstrainMode"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","role":"collection","title":"MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"MBMConstrainModeWidthAndHeight"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMConstrainModeWidthAndHeight"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"MBMConstrainModeWidthAndHeight"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ConstrainMode~1widthAndHeight\/title","op":"replace","value":"MBMConstrainModeWidthAndHeight"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ConstrainMode~1widthAndHeight\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMConstrainModeWidthAndHeight"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ConstrainMode\/title","op":"replace","value":"MBMConstrainMode"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ConstrainMode\/fragments","op":"replace","value":[{"text":"MBMConstrainMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ConstrainMode\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMConstrainMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}