{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"Equatable Implementations","role":"collectionGroup","roleHeading":"API Collection","modules":[{"name":"MapboxCommon"},{"name":"MapboxMaps"}]},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel"]]},"topicSections":[{"title":"Operators","anchor":"Operators","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel\/!=(_:_:)"],"generated":true}],"kind":"article","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel\/Equatable-Implementations"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/AccuracyLevel":{"title":"AccuracyLevel","url":"\/documentation\/mapboxcommon\/accuracylevel","kind":"symbol","navigatorTitle":[{"text":"AccuracyLevel","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AccuracyLevel","kind":"identifier"}],"abstract":[{"text":"The accuracy of the observed location","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/AccuracyLevel/!=(_:_:)":{"title":"!=(_:_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/AccuracyLevel\/!=(_:_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"url":"\/documentation\/mapboxcommon\/accuracylevel\/!=(_:_:)","type":"topic","kind":"symbol","role":"symbol","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Location-APIs":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","title":"Location","abstract":[],"url":"\/documentation\/mapboxmaps\/location-apis","type":"topic","role":"collectionGroup","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","title":"MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","role":"collection","url":"\/documentation\/overview","title":"MapboxMaps Documentation","kind":"article","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"}},"variantOverrides":[{"patch":[{"value":"MBXAccuracyLevel","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel\/title","op":"replace"},{"value":[{"text":"MBXAccuracyLevel","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel\/fragments","op":"replace"},{"value":[{"text":"MBXAccuracyLevel","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1AccuracyLevel\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}