{"variants":[{"paths":["\/documentation\/mapboxmaps\/stylepropertyvalue\/init(value:kind:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/stylepropertyvalue\/init(value:kind:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer-Property-Values","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValue"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"metadata":{"navigatorTitle":[{"text":"initWithValue:kind:","kind":"identifier"}],"modules":[{"name":"MapboxMaps"}],"roleHeading":"Initializer","role":"symbol","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"value"},{"text":": ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":", ","kind":"text"},{"text":"kind","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMStylePropertyValueKind","text":"StylePropertyValueKind"},{"text":")","kind":"text"}],"title":"init(value:kind:)","externalID":"c:objc(cs)MBMStylePropertyValue(im)initWithValue:kind:"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"text":"Any","kind":"keyword"},{"kind":"text","text":", "},{"text":"kind","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@MBMStylePropertyValueKind","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValueKind","kind":"typeIdentifier","text":"StylePropertyValueKind"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValue\/init(value:kind:)","interfaceLanguage":"swift"},"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","role":"collection","abstract":[],"kind":"article","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePropertyValue":{"navigatorTitle":[{"kind":"identifier","text":"StylePropertyValue"}],"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"StylePropertyValue","kind":"identifier"}],"abstract":[{"type":"text","text":"Holds a style property value with meta data."}],"title":"StylePropertyValue","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValue","url":"\/documentation\/mapboxmaps\/stylepropertyvalue","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePropertyValue/init(value:kind:)":{"role":"symbol","abstract":[],"kind":"symbol","url":"\/documentation\/mapboxmaps\/stylepropertyvalue\/init(value:kind:)","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"value","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Any","kind":"keyword"},{"text":", ","kind":"text"},{"text":"kind","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@MBMStylePropertyValueKind","text":"StylePropertyValueKind","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithValue:kind:"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValue\/init(value:kind:)","title":"init(value:kind:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","url":"\/documentation\/mapboxmaps","type":"topic","role":"collection","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePropertyValueKind":{"title":"StylePropertyValueKind","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValueKind","abstract":[{"type":"text","text":"Describes the kind of a style property value."}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StylePropertyValueKind"}],"navigatorTitle":[{"text":"StylePropertyValueKind","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/stylepropertyvaluekind","kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layer-Property-Values":{"url":"\/documentation\/mapboxmaps\/layer-property-values","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer-Property-Values","kind":"article","title":"Layer Property Values","abstract":[],"type":"topic","role":"collectionGroup"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"initWithValue:kind:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"initWithValue:kind:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithValue:","kind":"identifier"},{"kind":"text","text":"("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"value","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"kind:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@MBMStylePropertyValueKind","text":"MBMStylePropertyValueKind","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValueKind","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"kind"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"MBMStylePropertyValue","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValue\/title","op":"replace"},{"value":[{"text":"MBMStylePropertyValue","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValue\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValue\/navigatorTitle","value":[{"kind":"identifier","text":"MBMStylePropertyValue"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValue~1init(value:kind:)\/title","value":"initWithValue:kind:"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValue~1init(value:kind:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithValue:kind:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValueKind\/title","value":"MBMStylePropertyValueKind","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBMStylePropertyValueKind"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValueKind\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValueKind\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMStylePropertyValueKind"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}