{"metadata":{"modules":[{"name":"MapboxMaps"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"timeInterval"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMEventTimeInterval","text":"EventTimeInterval","kind":"typeIdentifier"}],"externalID":"c:objc(cs)MBMResourceRequest(py)timeInterval","title":"timeInterval","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"timeInterval"}],"symbolKind":"property","roleHeading":"Instance Property"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequest\/timeInterval"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequest"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"The timestamps of the resource request event. The ","type":"text"},{"type":"codeVoice","code":"timeInterval.begin"},{"type":"text","text":" is when"},{"type":"text","text":" "},{"type":"text","text":"the resource request is made, and the "},{"code":"timeInterval.end","type":"codeVoice"},{"type":"text","text":" is when the request is completed."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"timeInterval","kind":"identifier"},{"kind":"text","text":": "},{"text":"EventTimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMEventTimeInterval","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/EventTimeInterval"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/resourcerequest\/timeinterval"]},{"paths":["\/documentation\/mapboxmaps\/resourcerequest\/timeinterval"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResourceRequest/timeInterval":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequest\/timeInterval","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"timeInterval"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MBMEventTimeInterval","text":"EventTimeInterval","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"timeInterval"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/resourcerequest\/timeinterval","title":"timeInterval","abstract":[{"type":"text","text":"The timestamps of the resource request event. The "},{"type":"codeVoice","code":"timeInterval.begin"},{"text":" is when","type":"text"},{"type":"text","text":" "},{"text":"the resource request is made, and the ","type":"text"},{"type":"codeVoice","code":"timeInterval.end"},{"type":"text","text":" is when the request is completed."}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","title":"MapboxMaps","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResourceRequest":{"title":"ResourceRequest","type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ResourceRequest"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResourceRequest","url":"\/documentation\/mapboxmaps\/resourcerequest","navigatorTitle":[{"kind":"identifier","text":"ResourceRequest"}],"abstract":[{"type":"text","text":"The "},{"code":"ResourceRequest","type":"codeVoice"},{"text":" event allows the application to observe resource requests made by a ","type":"text"},{"code":"map","type":"codeVoice"},{"type":"text","text":" or "},{"type":"codeVoice","code":"map snapshotter"},{"text":" object.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","url":"\/documentation\/overview","title":"MapboxMaps Documentation","abstract":[],"kind":"article","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/EventTimeInterval":{"title":"EventTimeInterval","url":"\/documentation\/mapboxmaps\/eventtimeinterval","navigatorTitle":[{"kind":"identifier","text":"EventTimeInterval"}],"abstract":[{"type":"text","text":"The time interval of an event. The "},{"type":"codeVoice","code":"begin"},{"type":"text","text":" property represents the time"},{"type":"text","text":" "},{"type":"text","text":"origin of an event, and the "},{"code":"end","type":"codeVoice"},{"type":"text","text":" property represents the time when the particular"},{"type":"text","text":" "},{"text":"operation is complete. The timestamps are sampled at the origin and do not include","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"the time required to dispatch an event."}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/EventTimeInterval","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"EventTimeInterval","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"abstract":[{"type":"text","text":"The simplified diagram of the events emitted by the map is displayed below."}],"type":"topic","title":"Map events","url":"\/documentation\/mapboxmaps\/events","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","role":"collectionGroup","kind":"article"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"timeInterval"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","value":[{"text":"timeInterval","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/EventTimeInterval","kind":"typeIdentifier","text":"MBMEventTimeInterval","preciseIdentifier":"c:objc(cs)MBMEventTimeInterval"},{"text":" * ","kind":"text"},{"text":"timeInterval","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"timeInterval","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequest~1timeInterval\/title"},{"value":[{"text":"timeInterval","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequest~1timeInterval\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequest\/title","value":"MBMResourceRequest"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequest\/fragments","value":[{"kind":"identifier","text":"MBMResourceRequest"}]},{"value":[{"kind":"identifier","text":"MBMResourceRequest"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ResourceRequest\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1EventTimeInterval\/title","value":"MBMEventTimeInterval"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1EventTimeInterval\/fragments","value":[{"text":"MBMEventTimeInterval","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1EventTimeInterval\/navigatorTitle","value":[{"kind":"identifier","text":"MBMEventTimeInterval"}]}]}]}