{"metadata":{"modules":[{"name":"MapboxMaps"}],"symbolKind":"property","title":"cameraChanged","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraChanged","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MapEventType","preciseIdentifier":"s:10MapboxMaps12MapEventTypeV","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"CameraChanged","preciseIdentifier":"c:objc(cs)MBMCameraChanged","kind":"typeIdentifier"},{"text":">","kind":"text"}],"platforms":[],"role":"symbol","roleHeading":"Type Property","externalID":"s:10MapboxMaps12MapEventTypeV13cameraChangedACySo09MBMCameraG0CGvpZ"},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapEventType\/cameraChanged","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"The camera has changed."}],"variants":[{"paths":["\/documentation\/mapboxmaps\/mapeventtype\/camerachanged"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapEventType"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraChanged"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10MapboxMaps12MapEventTypeV","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapEventType","kind":"typeIdentifier","text":"MapEventType"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)MBMCameraChanged","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraChanged","kind":"typeIdentifier","text":"CameraChanged"},{"kind":"text","text":"> { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapboxMap","kind":"identifier"}],"title":"MapboxMap","abstract":[{"type":"text","text":"Provides access to the map model, including the camera, style, observable map events,"},{"type":"text","text":" "},{"type":"text","text":"and querying rendered features."}],"url":"\/documentation\/mapboxmaps\/mapboxmap","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","kind":"symbol","type":"topic","navigatorTitle":[{"text":"MapboxMap","kind":"identifier"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraChanged":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraChanged","kind":"symbol","title":"CameraChanged","navigatorTitle":[{"kind":"identifier","text":"CameraChanged"}],"url":"\/documentation\/mapboxmaps\/camerachanged","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraChanged"}],"type":"topic","abstract":[{"type":"text","text":"This event is emitted whenever the visible viewport changes its size"},{"type":"text","text":" "},{"type":"text","text":"due to the invocation of the "},{"type":"codeVoice","code":"setSize"},{"type":"text","text":" and "},{"type":"codeVoice","code":"setBounds"},{"type":"text","text":" methods or when"},{"type":"text","text":" "},{"type":"text","text":"the camera is modified by calling camera methods. The event is emitted"},{"type":"text","text":" "},{"type":"text","text":"synchronously so that an updated camera state can be read immediately."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapEventType":{"deprecated":true,"navigatorTitle":[{"text":"MapEventType","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapEventType","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapEventType","kind":"identifier"}],"abstract":[{"type":"text","text":"A shim that makes it possible to subscribe to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap"},{"type":"text","text":" and "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter"},{"type":"text","text":" events via the old "},{"type":"codeVoice","code":"onNext"},{"type":"text","text":" and  "},{"type":"codeVoice","code":"onEvery"},{"type":"text","text":" methods."},{"type":"text","text":" "},{"type":"text","text":"It is here to simplify migration from v10 to v11, but will be removed in v12."}],"title":"MapEventType","type":"topic","url":"\/documentation\/mapboxmaps\/mapeventtype"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Snapshotter":{"kind":"symbol","role":"symbol","title":"Snapshotter","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter","type":"topic","url":"\/documentation\/mapboxmaps\/snapshotter","abstract":[{"type":"text","text":"A utility class for capturing styled map snapshots."}],"navigatorTitle":[{"text":"Snapshotter","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Snapshotter","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article","url":"\/documentation\/overview","role":"collection","abstract":[],"title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","role":"collectionGroup","title":"Map events","kind":"article","type":"topic","abstract":[{"type":"text","text":"The simplified diagram of the events emitted by the map is displayed below."}],"url":"\/documentation\/mapboxmaps\/events"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapEventType/cameraChanged":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapEventType\/cameraChanged","abstract":[{"type":"text","text":"The camera has changed."}],"url":"\/documentation\/mapboxmaps\/mapeventtype\/camerachanged","type":"topic","title":"cameraChanged","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraChanged"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MapEventType","preciseIdentifier":"s:10MapboxMaps12MapEventTypeV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"CameraChanged","preciseIdentifier":"c:objc(cs)MBMCameraChanged"},{"kind":"text","text":">"}],"deprecated":true,"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChanged\/title","value":"MBMCameraChanged"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChanged\/fragments","value":[{"kind":"identifier","text":"MBMCameraChanged"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChanged\/navigatorTitle","value":[{"kind":"identifier","text":"MBMCameraChanged"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}