{"metadata":{"navigatorTitle":[{"text":"networkRestriction","kind":"identifier"}],"title":"networkRestriction","modules":[{"name":"MapboxCommon"}],"roleHeading":"Instance Property","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"networkRestriction","kind":"identifier"},{"kind":"text","text":": "},{"text":"NetworkRestriction","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBXNetworkRestriction"}],"role":"symbol","externalID":"c:objc(cs)MBXTileRegionLoadOptions(py)networkRestriction"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions\/networkRestriction"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"abstract":[{"type":"text","text":"Controls which networks may be used to load the tile."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkRestriction"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NetworkRestriction","kind":"typeIdentifier","text":"NetworkRestriction","preciseIdentifier":"c:@E@MBXNetworkRestriction"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Discussion","level":2,"anchor":"discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"By default, all networks are allowed. However, in some situations, it’s useful to limit the kind of networks"},{"type":"text","text":" "},{"type":"text","text":"that are allowed, e.g. to ensure that data is only transferred over a connection that doesn’t incur cost to"},{"text":" ","type":"text"},{"type":"text","text":"the user, like a WiFi connection, and prohibit data transfer over expensive connections like cellular."}],"type":"paragraph"}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/tileregionloadoptions\/networkrestriction"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/tileregionloadoptions\/networkrestriction"]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadOptions/networkRestriction":{"navigatorTitle":[{"kind":"identifier","text":"networkRestriction"}],"title":"networkRestriction","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions\/networkRestriction","kind":"symbol","abstract":[{"type":"text","text":"Controls which networks may be used to load the tile."}],"type":"topic","url":"\/documentation\/mapboxcommon\/tileregionloadoptions\/networkrestriction","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"networkRestriction","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NetworkRestriction","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBXNetworkRestriction"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadOptions":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TileRegionLoadOptions","kind":"identifier"}],"kind":"symbol","title":"TileRegionLoadOptions","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions","url":"\/documentation\/mapboxcommon\/tileregionloadoptions","navigatorTitle":[{"text":"TileRegionLoadOptions","kind":"identifier"}],"abstract":[{"text":"Describes the tile region load option values.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","title":"MapboxMaps Documentation","url":"\/documentation\/overview","type":"topic","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","role":"collection","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/NetworkRestriction":{"kind":"symbol","abstract":[{"type":"text","text":"Classify network types based on cost."}],"type":"topic","url":"\/documentation\/mapboxcommon\/networkrestriction","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"NetworkRestriction","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"NetworkRestriction","kind":"identifier"}],"title":"NetworkRestriction","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NetworkRestriction"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"url":"\/documentation\/mapboxmaps\/tilestore-apis","title":"TileStore APIs","kind":"article","abstract":[],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","role":"collectionGroup"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"networkRestriction","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"networkRestriction"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NetworkRestriction","kind":"typeIdentifier","text":"MBXNetworkRestriction","preciseIdentifier":"c:@E@MBXNetworkRestriction"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkRestriction"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions~1networkRestriction\/title","value":"networkRestriction","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions~1networkRestriction\/fragments","value":[{"text":"networkRestriction","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/title","value":"MBXTileRegionLoadOptions","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/fragments","op":"replace","value":[{"text":"MBXTileRegionLoadOptions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/navigatorTitle","value":[{"text":"MBXTileRegionLoadOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1NetworkRestriction\/title","value":"MBXNetworkRestriction","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1NetworkRestriction\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXNetworkRestriction"}]},{"value":[{"text":"MBXNetworkRestriction","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1NetworkRestriction\/navigatorTitle","op":"replace"}]}]}