{"kind":"symbol","metadata":{"modules":[{"name":"MapboxCommon"}],"roleHeading":"Type Method","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getFilePath","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"getFilePath()","navigatorTitle":[{"text":"getFilePath","kind":"identifier"}],"role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MBXExperimentalPersistentLogConfiguration(cm)getFilePath"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/persistentlogconfiguration\/getfilepath()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/persistentlogconfiguration\/getfilepath()"]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/getFilePath()","interfaceLanguage":"swift"},"sections":[],"abstract":[{"text":"Get the folder path for file logs.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getFilePath","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]}]},{"kind":"content","content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"String  path to the folder for the stored logs."}]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"url":"\/documentation\/mapboxcommon","role":"collection","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","type":"topic","abstract":[],"title":"MapboxCommon"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PersistentLogConfiguration/getFilePath()":{"abstract":[{"type":"text","text":"Get the folder path for file logs."}],"url":"\/documentation\/mapboxcommon\/persistentlogconfiguration\/getfilepath()","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/getFilePath()","title":"getFilePath()","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"getFilePath"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"getFilePath"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PersistentLogConfiguration":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PersistentLogConfiguration"}],"url":"\/documentation\/mapboxcommon\/persistentlogconfiguration","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration","abstract":[{"type":"text","text":"Settings to configure behavior of persistent log"}],"role":"symbol","title":"PersistentLogConfiguration","navigatorTitle":[{"kind":"identifier","text":"PersistentLogConfiguration"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","abstract":[],"type":"topic","title":"MapboxMaps Documentation","kind":"article","url":"\/documentation\/overview"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"getFilePath","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getFilePath"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"getFilePath"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","value":{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"String  path to the folder for the stored logs.","type":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1getFilePath()\/title","value":"getFilePath","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1getFilePath()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getFilePath"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration\/title","value":"MBXExperimentalPersistentLogConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration\/fragments","value":[{"kind":"identifier","text":"MBXExperimentalPersistentLogConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration\/navigatorTitle","value":[{"text":"MBXExperimentalPersistentLogConfiguration","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}