{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timestamp","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"metadata":{"navigatorTitle":[{"text":"timestamp","kind":"identifier"}],"modules":[{"name":"MapboxMaps"}],"symbolKind":"property","title":"timestamp","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"timestamp","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"}],"role":"symbol","roleHeading":"Instance Property","externalID":"c:objc(cs)MBMCameraChanged(py)timestamp"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/mbmcamerachanged\/timestamp"]},{"paths":["\/documentation\/mapboxmaps\/mbmcamerachanged\/timestamp"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCameraChanged\/timestamp"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraChanged"]]},"sections":[],"abstract":[{"type":"text","text":"The time when the camera was changed."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","title":"Map events","role":"collectionGroup","type":"topic","abstract":[{"type":"text","text":"The simplified diagram of the events emitted by the map is displayed below."}],"url":"\/documentation\/mapboxmaps\/events","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMCameraChanged/timestamp":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"timestamp"}],"abstract":[{"text":"The time when the camera was changed.","type":"text"}],"title":"timestamp","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timestamp","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCameraChanged\/timestamp","role":"symbol","url":"\/documentation\/mapboxmaps\/mbmcamerachanged\/timestamp"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraChanged":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraChanged"}],"abstract":[{"text":"This event is emitted whenever the visible viewport changes its size","type":"text"},{"text":" ","type":"text"},{"text":"due to the invocation of the ","type":"text"},{"code":"setSize","type":"codeVoice"},{"type":"text","text":" and "},{"code":"setBounds","type":"codeVoice"},{"text":" methods or when","type":"text"},{"type":"text","text":" "},{"text":"the camera is modified by calling camera methods. The event is emitted","type":"text"},{"type":"text","text":" "},{"type":"text","text":"synchronously so that an updated camera state can be read immediately."}],"title":"CameraChanged","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraChanged"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraChanged","role":"symbol","url":"\/documentation\/mapboxmaps\/camerachanged"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"timestamp"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"timestamp"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSDate","kind":"typeIdentifier","text":"NSDate"},{"text":" * ","kind":"text"},{"text":"timestamp","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMCameraChanged~1timestamp\/title","value":"timestamp","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMCameraChanged~1timestamp\/fragments","value":[{"text":"timestamp","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChanged\/title","value":"MBMCameraChanged"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CameraChanged\/fragments","value":[{"text":"MBMCameraChanged","kind":"identifier"}],"op":"replace"}]}]}