{"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"title":"init(fetchTileFunction:cancelTileFunction:minZoom:maxZoom:tileOptions:)","modules":[{"name":"MapboxMaps"}],"roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"fetchTileFunction","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:MBMTileFunctionCallback.h@T@MBMTileFunctionCallback","text":"TileFunctionCallback"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cancelTileFunction"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TileFunctionCallback","preciseIdentifier":"c:MBMTileFunctionCallback.h@T@MBMTileFunctionCallback"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"minZoom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V","text":"UInt8"},{"text":", ","kind":"text"},{"text":"maxZoom","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt8","preciseIdentifier":"s:s5UInt8V"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"tileOptions"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMTileOptions","kind":"typeIdentifier","text":"TileOptions"},{"text":")","kind":"text"}],"role":"symbol","externalID":"c:objc(cs)MBMCustomGeometrySourceOptions(im)initWithFetchTileFunction:cancelTileFunction:minZoom:maxZoom:tileOptions:","navigatorTitle":[{"text":"initWithFetchTileFunction:cancelTileFunction:minZoom:maxZoom:tileOptions:","kind":"identifier"}],"symbolKind":"init"},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions\/init(fetchTileFunction:cancelTileFunction:minZoom:maxZoom:tileOptions:)","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fetchTileFunction"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"TileFunctionCallback","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileFunctionCallback","preciseIdentifier":"c:MBMTileFunctionCallback.h@T@MBMTileFunctionCallback"},{"kind":"text","text":", "},{"text":"cancelTileFunction","kind":"externalParam"},{"kind":"text","text":": "},{"text":"@escaping","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:MBMTileFunctionCallback.h@T@MBMTileFunctionCallback","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileFunctionCallback","kind":"typeIdentifier","text":"TileFunctionCallback"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"minZoom"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V","text":"UInt8"},{"text":", ","kind":"text"},{"text":"maxZoom","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt8","preciseIdentifier":"s:s5UInt8V"},{"kind":"text","text":", "},{"text":"tileOptions","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileOptions","preciseIdentifier":"c:objc(cs)MBMTileOptions","text":"TileOptions"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/customgeometrysourceoptions\/init(fetchtilefunction:canceltilefunction:minzoom:maxzoom:tileoptions:)"]},{"paths":["\/documentation\/mapboxmaps\/customgeometrysourceoptions\/init(fetchtilefunction:canceltilefunction:minzoom:maxzoom:tileoptions:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileOptions":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TileOptions"}],"type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/tileoptions","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TileOptions","kind":"identifier"}],"title":"TileOptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileOptions","abstract":[{"text":"Options for custom geometry tiles.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","url":"\/documentation\/overview","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Sources":{"title":"Sources","url":"\/documentation\/mapboxmaps\/sources","type":"topic","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources","role":"collectionGroup","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomGeometrySourceOptions":{"title":"CustomGeometrySourceOptions","abstract":[{"text":"Options for custom geometry source.","type":"text"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/customgeometrysourceoptions","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomGeometrySourceOptions"}],"navigatorTitle":[{"kind":"identifier","text":"CustomGeometrySourceOptions"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"title":"MapboxMaps","kind":"symbol","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileFunctionCallback":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileFunctionCallback","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"TileFunctionCallback","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"TileFunctionCallback","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/tilefunctioncallback","kind":"symbol","abstract":[{"type":"text","text":"Callback to do various operations for tile."},{"type":"text","text":" "},{"text":"For example, fetching a tile or cancelling a tile request.","type":"text"}],"title":"TileFunctionCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomGeometrySourceOptions/init(fetchTileFunction:cancelTileFunction:minZoom:maxZoom:tileOptions:)":{"title":"init(fetchTileFunction:cancelTileFunction:minZoom:maxZoom:tileOptions:)","url":"\/documentation\/mapboxmaps\/customgeometrysourceoptions\/init(fetchtilefunction:canceltilefunction:minzoom:maxzoom:tileoptions:)","abstract":[],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"fetchTileFunction","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TileFunctionCallback","preciseIdentifier":"c:MBMTileFunctionCallback.h@T@MBMTileFunctionCallback"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cancelTileFunction"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TileFunctionCallback","preciseIdentifier":"c:MBMTileFunctionCallback.h@T@MBMTileFunctionCallback"},{"text":", ","kind":"text"},{"text":"minZoom","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt8","kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V"},{"kind":"text","text":", "},{"text":"maxZoom","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt8","kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"tileOptions"},{"text":": ","kind":"text"},{"text":"TileOptions","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMTileOptions"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithFetchTileFunction:cancelTileFunction:minZoom:maxZoom:tileOptions:"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions\/init(fetchTileFunction:cancelTileFunction:minZoom:maxZoom:tileOptions:)","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"initWithFetchTileFunction:cancelTileFunction:minZoom:maxZoom:tileOptions:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithFetchTileFunction:cancelTileFunction:minZoom:maxZoom:tileOptions:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithFetchTileFunction:"},{"text":"(","kind":"text"},{"text":"void (^)(MBMCanonicalTileID *)","preciseIdentifier":"c:BFv(#*$objc(cs)MBMCanonicalTileID)","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"fetchTileFunction","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cancelTileFunction:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$objc(cs)MBMCanonicalTileID)","text":"void (^)(MBMCanonicalTileID *)"},{"kind":"text","text":") "},{"text":"cancelTileFunction","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"minZoom:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@uint8_t","text":"uint8_t","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"minZoom","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"maxZoom:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@uint8_t","kind":"typeIdentifier","text":"uint8_t"},{"kind":"text","text":") "},{"text":"maxZoom","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"tileOptions:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MBMTileOptions","preciseIdentifier":"c:objc(cs)MBMTileOptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileOptions","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"tileOptions","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","value":"MBMTileOptions","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileOptions\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileOptions\/fragments","value":[{"kind":"identifier","text":"MBMTileOptions"}]},{"op":"replace","value":[{"kind":"identifier","text":"MBMTileOptions"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileOptions\/navigatorTitle"},{"value":"MBMCustomGeometrySourceOptions","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions\/title"},{"value":[{"text":"MBMCustomGeometrySourceOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MBMCustomGeometrySourceOptions"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions\/navigatorTitle","op":"replace"},{"value":"MBMTileFunctionCallback","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileFunctionCallback\/title"},{"op":"replace","value":[{"text":"MBMTileFunctionCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileFunctionCallback\/fragments"},{"value":[{"kind":"identifier","text":"MBMTileFunctionCallback"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileFunctionCallback\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions~1init(fetchTileFunction:cancelTileFunction:minZoom:maxZoom:tileOptions:)\/title","value":"initWithFetchTileFunction:cancelTileFunction:minZoom:maxZoom:tileOptions:"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions~1init(fetchTileFunction:cancelTileFunction:minZoom:maxZoom:tileOptions:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithFetchTileFunction:cancelTileFunction:minZoom:maxZoom:tileOptions:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}