{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatistics\/cumulativeStatistics"},"kind":"symbol","metadata":{"externalID":"c:objc(cs)MBMPerformanceStatistics(py)cumulativeStatistics","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"cumulativeStatistics"}],"roleHeading":"Instance Property","modules":[{"name":"MapboxMaps"}],"role":"symbol","title":"cumulativeStatistics","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cumulativeStatistics"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MBMCumulativeRenderingStatistics","kind":"typeIdentifier","text":"CumulativeRenderingStatistics"},{"kind":"text","text":"?"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/mapboxmaps\/performancestatistics\/cumulativestatistics"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/performancestatistics\/cumulativestatistics"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatistics"]]},"abstract":[{"text":"Cumulative, continuously tracked, resource stats. Enable using the ","type":"text"},{"code":"CumulativeRenderingStats","type":"codeVoice"},{"text":" performance sampler option.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cumulativeStatistics"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMCumulativeRenderingStatistics","text":"CumulativeRenderingStatistics","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CumulativeRenderingStatistics"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"url":"\/documentation\/mapboxmaps","role":"collection","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PerformanceStatistics":{"url":"\/documentation\/mapboxmaps\/performancestatistics","abstract":[{"text":"The performance statistics collected at the end of the sampling duration.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatistics","title":"PerformanceStatistics","navigatorTitle":[{"kind":"identifier","text":"PerformanceStatistics"}],"kind":"symbol","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PerformanceStatistics"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","abstract":[],"url":"\/documentation\/overview","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Performance":{"title":"Performance and investigations","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","role":"collectionGroup","kind":"article","abstract":[],"url":"\/documentation\/mapboxmaps\/performance"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CumulativeRenderingStatistics":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CumulativeRenderingStatistics","navigatorTitle":[{"kind":"identifier","text":"CumulativeRenderingStatistics"}],"kind":"symbol","title":"CumulativeRenderingStatistics","url":"\/documentation\/mapboxmaps\/cumulativerenderingstatistics","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CumulativeRenderingStatistics"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PerformanceStatistics/cumulativeStatistics":{"title":"cumulativeStatistics","abstract":[{"type":"text","text":"Cumulative, continuously tracked, resource stats. Enable using the "},{"type":"codeVoice","code":"CumulativeRenderingStats"},{"type":"text","text":" performance sampler option."}],"url":"\/documentation\/mapboxmaps\/performancestatistics\/cumulativestatistics","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cumulativeStatistics"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MBMCumulativeRenderingStatistics","kind":"typeIdentifier","text":"CumulativeRenderingStatistics"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"cumulativeStatistics"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatistics\/cumulativeStatistics"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"cumulativeStatistics"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"cumulativeStatistics"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CumulativeRenderingStatistics","preciseIdentifier":"c:objc(cs)MBMCumulativeRenderingStatistics","text":"MBMCumulativeRenderingStatistics","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"cumulativeStatistics","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatistics\/title","op":"replace","value":"MBMPerformanceStatistics"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatistics\/fragments","op":"replace","value":[{"text":"MBMPerformanceStatistics","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatistics\/navigatorTitle","op":"replace","value":[{"text":"MBMPerformanceStatistics","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CumulativeRenderingStatistics\/title","op":"replace","value":"MBMCumulativeRenderingStatistics"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CumulativeRenderingStatistics\/fragments","op":"replace","value":[{"text":"MBMCumulativeRenderingStatistics","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CumulativeRenderingStatistics\/navigatorTitle","op":"replace","value":[{"text":"MBMCumulativeRenderingStatistics","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatistics~1cumulativeStatistics\/title","op":"replace","value":"cumulativeStatistics"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatistics~1cumulativeStatistics\/fragments","op":"replace","value":[{"text":"cumulativeStatistics","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}