{"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"The bounds covering the region."}],"variants":[{"paths":["\/documentation\/mapboxmaps\/offlineregiontilepyramiddefinition\/bounds"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/offlineregiontilepyramiddefinition\/bounds"]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionTilePyramidDefinition\/bounds","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionTilePyramidDefinition"]]},"metadata":{"roleHeading":"Instance Property","modules":[{"name":"MapboxMaps"}],"platforms":[],"symbolKind":"property","role":"symbol","title":"bounds","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bounds"},{"text":": ","kind":"text"},{"text":"CoordinateBounds","preciseIdentifier":"c:objc(cs)MBMCoordinateBounds","kind":"typeIdentifier"}],"externalID":"c:objc(cs)MBMOfflineRegionTilePyramidDefinition(py)bounds","navigatorTitle":[{"text":"bounds","kind":"identifier"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"bounds","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CoordinateBounds","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMCoordinateBounds","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMaps":{"abstract":[{"text":"Maps rendering SDK also known as GL-Native","type":"text"}],"url":"\/documentation\/mapboxmaps\/coremaps","title":"Core Maps API","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","type":"topic","role":"collectionGroup","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article","role":"collection","type":"topic","abstract":[],"url":"\/documentation\/overview","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Offline":{"abstract":[],"title":"Offline Support","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","url":"\/documentation\/mapboxmaps\/offline","role":"collectionGroup","type":"topic","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateBounds":{"role":"symbol","abstract":[{"text":"A rectangular area as measured on a two-dimensional map projection.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"CoordinateBounds"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds","url":"\/documentation\/mapboxmaps\/coordinatebounds","title":"CoordinateBounds","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CoordinateBounds","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionTilePyramidDefinition/bounds":{"navigatorTitle":[{"kind":"identifier","text":"bounds"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/offlineregiontilepyramiddefinition\/bounds","role":"symbol","title":"bounds","deprecated":true,"abstract":[{"text":"The bounds covering the region.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bounds"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MBMCoordinateBounds","kind":"typeIdentifier","text":"CoordinateBounds"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionTilePyramidDefinition\/bounds","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","title":"MapboxMaps","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionTilePyramidDefinition":{"deprecated":true,"abstract":[{"type":"text","text":"An offline region definition is a geographic region defined by a style URL,"},{"type":"text","text":" "},{"text":"geographic bounding box, zoom range, and device pixel ratio. Both ","type":"text"},{"code":"minZoom","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"maxZoom","type":"codeVoice"},{"text":" must be ≥ 0,","type":"text"},{"type":"text","text":" "},{"text":"and ","type":"text"},{"type":"codeVoice","code":"maxZoom"},{"type":"text","text":" must be ≥ "},{"code":"minZoom","type":"codeVoice"},{"text":". The ","type":"text"},{"code":"maxZoom","type":"codeVoice"},{"text":" may be ∞, in which case for each tile source,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"the region will include tiles from "},{"type":"codeVoice","code":"minZoom"},{"type":"text","text":" up to the maximum zoom level provided by that source."},{"type":"text","text":" "},{"text":"The ","type":"text"},{"code":"pixelRatio","type":"codeVoice"},{"type":"text","text":" must be ≥ 0 and should typically be 1.0 or 2.0."}],"title":"OfflineRegionTilePyramidDefinition","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OfflineRegionTilePyramidDefinition"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionTilePyramidDefinition","navigatorTitle":[{"text":"OfflineRegionTilePyramidDefinition","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/offlineregiontilepyramiddefinition","role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"bounds","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"bounds","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMCoordinateBounds","kind":"typeIdentifier","text":"MBMCoordinateBounds","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds"},{"text":" * ","kind":"text"},{"text":"bounds","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds\/title","value":"MBMCoordinateBounds"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds\/fragments","value":[{"text":"MBMCoordinateBounds","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"MBMCoordinateBounds"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionTilePyramidDefinition~1bounds\/title","value":"bounds","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionTilePyramidDefinition~1bounds\/fragments","op":"replace","value":[{"text":"bounds","kind":"identifier"}]},{"value":"MBMOfflineRegionTilePyramidDefinition","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionTilePyramidDefinition\/title"},{"value":[{"kind":"identifier","text":"MBMOfflineRegionTilePyramidDefinition"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionTilePyramidDefinition\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MBMOfflineRegionTilePyramidDefinition"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionTilePyramidDefinition\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}