{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/tileregionestimateprogress\/completedresourcecount"]},{"paths":["\/documentation\/mapboxcommon\/tileregionestimateprogress\/completedresourcecount"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgress\/completedResourceCount"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completedResourceCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V","text":"UInt64"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgress"]]},"abstract":[{"type":"text","text":"The number of resources that have been estimated."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"roleHeading":"Instance Property","title":"completedResourceCount","modules":[{"name":"MapboxCommon"}],"externalID":"c:objc(cs)MBXTileRegionEstimateProgress(py)completedResourceCount","role":"symbol","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"completedResourceCount"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"completedResourceCount","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V","text":"UInt64"}]},"sections":[],"kind":"symbol","references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","url":"\/documentation\/mapboxmaps","type":"topic","role":"collection","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","role":"collection","abstract":[],"kind":"article","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"title":"TileStore APIs","type":"topic","abstract":[],"role":"collectionGroup","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","url":"\/documentation\/mapboxmaps\/tilestore-apis"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateProgress":{"role":"symbol","navigatorTitle":[{"text":"TileRegionEstimateProgress","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/tileregionestimateprogress","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgress","abstract":[{"type":"text","text":"A tile region’s estimate progress includes counts of the number of resources that have"},{"text":" ","type":"text"},{"text":"been estimated and the total number of resources as well as a partial result with the","type":"text"},{"type":"text","text":" "},{"text":"current estimate, calculated using the data available at the moment.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TileRegionEstimateProgress","kind":"identifier"}],"type":"topic","kind":"symbol","title":"TileRegionEstimateProgress"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateProgress/completedResourceCount":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completedResourceCount"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s6UInt64V","kind":"typeIdentifier","text":"UInt64"}],"title":"completedResourceCount","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgress\/completedResourceCount","type":"topic","abstract":[{"text":"The number of resources that have been estimated.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"completedResourceCount","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapboxcommon\/tileregionestimateprogress\/completedresourcecount"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"completedResourceCount","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"text":"completedResourceCount","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@uint64_t","text":"uint64_t","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"completedResourceCount","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"value":"MBXTileRegionEstimateProgress","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgress\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgress\/fragments","op":"replace","value":[{"text":"MBXTileRegionEstimateProgress","kind":"identifier"}]},{"value":[{"text":"MBXTileRegionEstimateProgress","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgress\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgress~1completedResourceCount\/title","value":"completedResourceCount","op":"replace"},{"value":[{"kind":"identifier","text":"completedResourceCount"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgress~1completedResourceCount\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}