{"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapOptions\/size-5ujit","interfaceLanguage":"occ"},"kind":"symbol","metadata":{"roleHeading":"Instance Property","modules":[{"name":"MapboxMaps"}],"role":"symbol","symbolKind":"property","navigatorTitle":[{"text":"size","kind":"identifier"}],"externalID":"c:objc(cs)MBMMapOptions(py)size","title":"size","fragments":[{"text":"size","kind":"identifier"}]},"abstract":[{"text":"The size to resize the map object and renderer backend.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The size is given in "},{"code":"platform pixel","type":"codeVoice"},{"text":" units. macOS and iOS platforms use","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"device-independent pixel units, while other platforms, such as Android,"},{"text":" ","type":"text"},{"type":"text","text":"use screen pixel units."}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/mbmmapoptions\/size-5ujit"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)MBMSize","kind":"typeIdentifier","text":"MBMSize","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Size"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"size"},{"kind":"text","text":";"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-View","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapOptions"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapOptions":{"role":"symbol","type":"topic","title":"MapOptions","navigatorTitle":[{"text":"MapOptions","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapOptions","url":"\/documentation\/mapboxmaps\/mapoptions","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MapOptions","kind":"identifier"}],"abstract":[{"text":"Describes the map option values.","type":"text"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMMapOptions/size-5ujit":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapOptions\/size-5ujit","abstract":[{"text":"The size to resize the map object and renderer backend.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The size is given in "},{"type":"codeVoice","code":"platform pixel"},{"type":"text","text":" units. macOS and iOS platforms use"},{"type":"text","text":" "},{"text":"device-independent pixel units, while other platforms, such as Android,","type":"text"},{"type":"text","text":" "},{"text":"use screen pixel units.","type":"text"}],"title":"size","url":"\/documentation\/mapboxmaps\/mbmmapoptions\/size-5ujit","role":"symbol","fragments":[{"text":"size","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map-View":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-View","kind":"article","title":"MapView","url":"\/documentation\/mapboxmaps\/map-view","abstract":[],"type":"topic","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Size":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Size","title":"Size","kind":"symbol","navigatorTitle":[{"text":"Size","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/size","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Size","kind":"identifier"}],"abstract":[{"type":"text","text":"Size type."}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapOptions\/title","value":"MBMMapOptions","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapOptions\/fragments","value":[{"kind":"identifier","text":"MBMMapOptions"}],"op":"replace"},{"value":"MBMSize","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Size\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Size\/fragments","value":[{"kind":"identifier","text":"MBMSize"}]}]}]}