{"abstract":[{"text":"Inherited from ","type":"text"},{"code":"LocalizedError.helpAnchor","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestError\/helpAnchor"},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"platforms":[{"name":"iOS","deprecated":false,"beta":false,"introducedAt":"8.0","unavailable":false},{"introducedAt":"8.0","unavailable":false,"beta":false,"deprecated":false,"name":"iPadOS"},{"deprecated":false,"beta":false,"introducedAt":"8.0","name":"Mac Catalyst","unavailable":false},{"name":"macOS","beta":false,"deprecated":false,"introducedAt":"10.10","unavailable":false},{"name":"tvOS","introducedAt":"9.0","deprecated":false,"unavailable":false,"beta":false},{"deprecated":false,"introducedAt":"2.0","name":"watchOS","unavailable":false,"beta":false}],"role":"symbol","externalID":"s:10Foundation14LocalizedErrorPAAE10helpAnchorSSSgvp::SYNTHESIZED::c:objc(cs)MBXHttpRequestError","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"helpAnchor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}],"extendedModule":"Foundation","roleHeading":"Instance Property","modules":[{"relatedModules":["Foundation"],"name":"MapboxCommon"}],"title":"helpAnchor","symbolKind":"property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/httprequesterror\/helpanchor"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"helpAnchor","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestError\/LocalizedError-Implementations"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestError/helpAnchor":{"abstract":[],"url":"\/documentation\/mapboxcommon\/httprequesterror\/helpanchor","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestError\/helpAnchor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"helpAnchor"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"kind":"symbol","type":"topic","title":"helpAnchor"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestError/LocalizedError-Implementations":{"type":"topic","title":"LocalizedError Implementations","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestError\/LocalizedError-Implementations","abstract":[],"kind":"article","role":"collectionGroup","url":"\/documentation\/mapboxcommon\/httprequesterror\/localizederror-implementations"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","kind":"article","title":"MapboxMaps Documentation","abstract":[],"role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"url":"\/documentation\/mapboxcommon","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","type":"topic","title":"MapboxCommon","role":"collection","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestError":{"type":"topic","title":"HttpRequestError","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestError","abstract":[{"text":"Record which contains detailed information about HTTP error happened during request\/download call.","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/mapboxcommon\/httprequesterror","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HttpRequestError","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"HttpRequestError"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MBXHttpRequestError","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestError\/title"},{"value":[{"kind":"identifier","text":"MBXHttpRequestError"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestError\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestError\/navigatorTitle","value":[{"kind":"identifier","text":"MBXHttpRequestError"}],"op":"replace"}]}]}