{"kind":"symbol","metadata":{"role":"symbol","navigatorTitle":[{"text":"MBMCustomRasterSourceClientTypeCustomRasterSourceTileStatusChangedCallback","kind":"identifier"}],"externalID":"c:@E@MBMCustomRasterSourceClientType@MBMCustomRasterSourceClientTypeCustomRasterSourceTileStatusChangedCallback","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customRasterSourceTileStatusChangedCallback","kind":"identifier"}],"title":"CustomRasterSourceClientType.customRasterSourceTileStatusChangedCallback","roleHeading":"Case","modules":[{"name":"MapboxMaps"}],"symbolKind":"case"},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"customRasterSourceTileStatusChangedCallback"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/customrastersourceclienttype\/customrastersourcetilestatuschangedcallback"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/customrastersourceclienttype\/customrastersourcetilestatuschangedcallback"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType\/customRasterSourceTileStatusChangedCallback"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType"]]},"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","role":"collection","title":"MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceClientType":{"type":"topic","url":"\/documentation\/mapboxmaps\/customrastersourceclienttype","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"CustomRasterSourceClientType","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomRasterSourceClientType","kind":"identifier"}],"title":"CustomRasterSourceClientType"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceClientType/customRasterSourceTileStatusChangedCallback":{"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType\/customRasterSourceTileStatusChangedCallback","kind":"symbol","url":"\/documentation\/mapboxmaps\/customrastersourceclienttype\/customrastersourcetilestatuschangedcallback","navigatorTitle":[{"text":"MBMCustomRasterSourceClientTypeCustomRasterSourceTileStatusChangedCallback","kind":"identifier"}],"title":"CustomRasterSourceClientType.customRasterSourceTileStatusChangedCallback","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customRasterSourceTileStatusChangedCallback","kind":"identifier"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Sources":{"title":"Sources","type":"topic","url":"\/documentation\/mapboxmaps\/sources","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources","role":"collectionGroup","kind":"article","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","url":"\/documentation\/overview","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","kind":"article","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"MBMCustomRasterSourceClientTypeCustomRasterSourceTileStatusChangedCallback"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"MBMCustomRasterSourceClientTypeCustomRasterSourceTileStatusChangedCallback","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"MBMCustomRasterSourceClientTypeCustomRasterSourceTileStatusChangedCallback"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType\/title","op":"replace","value":"MBMCustomRasterSourceClientType"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType\/fragments","op":"replace","value":[{"text":"MBMCustomRasterSourceClientType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType\/navigatorTitle","op":"replace","value":[{"text":"MBMCustomRasterSourceClientType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType~1customRasterSourceTileStatusChangedCallback\/title","op":"replace","value":"MBMCustomRasterSourceClientTypeCustomRasterSourceTileStatusChangedCallback"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType~1customRasterSourceTileStatusChangedCallback\/fragments","op":"replace","value":[{"text":"MBMCustomRasterSourceClientTypeCustomRasterSourceTileStatusChangedCallback","kind":"identifier"}]}]}]}