{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/tilecachebudgettype\/tilecachebudgetinmegabytes"]},{"paths":["\/documentation\/mapboxmaps\/tilecachebudgettype\/tilecachebudgetinmegabytes"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"tileCacheBudgetInMegabytes","kind":"identifier"}]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetType"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetType\/tileCacheBudgetInMegabytes"},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tileCacheBudgetInMegabytes"}],"role":"symbol","navigatorTitle":[{"text":"MBMTileCacheBudgetTypeTileCacheBudgetInMegabytes","kind":"identifier"}],"modules":[{"name":"MapboxMaps"}],"roleHeading":"Case","externalID":"c:@E@MBMTileCacheBudgetType@MBMTileCacheBudgetTypeTileCacheBudgetInMegabytes","symbolKind":"case","title":"TileCacheBudgetType.tileCacheBudgetInMegabytes"},"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","type":"topic","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","abstract":[],"role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","title":"MapboxMaps","kind":"symbol","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudgetType":{"role":"symbol","navigatorTitle":[{"text":"TileCacheBudgetType","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetType","kind":"symbol","title":"TileCacheBudgetType","url":"\/documentation\/mapboxmaps\/tilecachebudgettype","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TileCacheBudgetType","kind":"identifier"}],"abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"url":"\/documentation\/mapboxmaps\/tilestore-apis","title":"TileStore APIs","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","kind":"article","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudgetType/tileCacheBudgetInMegabytes":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"tileCacheBudgetInMegabytes","kind":"identifier"}],"navigatorTitle":[{"text":"MBMTileCacheBudgetTypeTileCacheBudgetInMegabytes","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetType\/tileCacheBudgetInMegabytes","url":"\/documentation\/mapboxmaps\/tilecachebudgettype\/tilecachebudgetinmegabytes","kind":"symbol","type":"topic","title":"TileCacheBudgetType.tileCacheBudgetInMegabytes","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MBMTileCacheBudgetTypeTileCacheBudgetInMegabytes"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"MBMTileCacheBudgetTypeTileCacheBudgetInMegabytes"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"MBMTileCacheBudgetTypeTileCacheBudgetInMegabytes","kind":"identifier"}],"platforms":["iOS"]}]}},{"value":"MBMTileCacheBudgetType","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetType\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetType\/fragments","op":"replace","value":[{"text":"MBMTileCacheBudgetType","kind":"identifier"}]},{"op":"replace","value":[{"text":"MBMTileCacheBudgetType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetType\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetType~1tileCacheBudgetInMegabytes\/title","value":"MBMTileCacheBudgetTypeTileCacheBudgetInMegabytes"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetType~1tileCacheBudgetInMegabytes\/fragments","value":[{"text":"MBMTileCacheBudgetTypeTileCacheBudgetInMegabytes","kind":"identifier"}]}]}]}