{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/coordinateBoundsZoomUnwrapped(for:)"},"abstract":[{"text":"Returns the unwrapped coordinate bounds and zoom for a given ","type":"text"},{"code":"CameraOptions","type":"codeVoice"},{"text":".","type":"text"}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"modules":[{"name":"MapboxMaps"}],"roleHeading":"Instance Method","symbolKind":"method","title":"coordinateBoundsZoomUnwrapped(for:)","role":"symbol","externalID":"s:10MapboxMaps0A3MapC29coordinateBoundsZoomUnwrapped3forSo013MBMCoordinateeF0CAA13CameraOptionsV_tF","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"coordinateBoundsZoomUnwrapped","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CameraOptions","preciseIdentifier":"s:10MapboxMaps13CameraOptionsV","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"CoordinateBoundsZoom","preciseIdentifier":"c:objc(cs)MBMCoordinateBoundsZoom","kind":"typeIdentifier"}]},"seeAlsoSections":[{"title":"CameraOptions to CoordinateBounds","anchor":"CameraOptions-to-CoordinateBounds","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/coordinateBounds(for:)-gs8h","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/coordinateBoundsUnwrapped(for:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/coordinateBoundsZoom(for:)"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"coordinateBoundsZoomUnwrapped","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"camera","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"CameraOptions","preciseIdentifier":"s:10MapboxMaps13CameraOptionsV","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraOptions","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"CoordinateBoundsZoom","preciseIdentifier":"c:objc(cs)MBMCoordinateBoundsZoom","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBoundsZoom","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The camera for which the ","type":"text"},{"code":"CoordinateBoundsZoom","type":"codeVoice"},{"text":" will","type":"text"},{"text":" ","type":"text"},{"text":"be returned.","type":"text"}]}],"name":"camera"}],"kind":"parameters"},{"content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"type":"codeVoice","code":"CoordinateBoundsZoom"},{"text":" for the given ","type":"text"},{"type":"codeVoice","code":"CameraOptions"}]}],"kind":"content"},{"content":[{"text":"Discussion","level":2,"anchor":"discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"This function is particularly useful, if the camera shows the antimeridian."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"This API isn’t supported by Globe projection."}],"type":"paragraph"}],"kind":"content"}],"variants":[{"paths":["\/documentation\/mapboxmaps\/mapboxmap\/coordinateboundszoomunwrapped(for:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap"]]},"kind":"symbol","references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/coordinateBoundsZoom(for:)":{"type":"topic","abstract":[{"text":"Returns the coordinate bounds and zoom for a given ","type":"text"},{"type":"codeVoice","code":"CameraOptions"},{"text":".","type":"text"}],"role":"symbol","kind":"symbol","title":"coordinateBoundsZoom(for:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/coordinateBoundsZoom(for:)","url":"\/documentation\/mapboxmaps\/mapboxmap\/coordinateboundszoom(for:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"coordinateBoundsZoom","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CameraOptions","preciseIdentifier":"s:10MapboxMaps13CameraOptionsV","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"CoordinateBoundsZoom","preciseIdentifier":"c:objc(cs)MBMCoordinateBoundsZoom","kind":"typeIdentifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/coordinateBounds(for:)-gs8h":{"role":"symbol","abstract":[{"text":"Returns the coordinate bounds corresponding to a given ","type":"text"},{"code":"CameraOptions","type":"codeVoice"}],"url":"\/documentation\/mapboxmaps\/mapboxmap\/coordinatebounds(for:)-gs8h","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"coordinateBounds"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraOptions","preciseIdentifier":"s:10MapboxMaps13CameraOptionsV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CoordinateBounds","preciseIdentifier":"c:objc(cs)MBMCoordinateBounds"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/coordinateBounds(for:)-gs8h","title":"coordinateBounds(for:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/coordinateBoundsUnwrapped(for:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/coordinateBoundsUnwrapped(for:)","abstract":[{"type":"text","text":"Returns the unwrapped coordinate bounds to a given "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraOptions","type":"reference","isActive":true},{"type":"text","text":"."}],"type":"topic","url":"\/documentation\/mapboxmaps\/mapboxmap\/coordinateboundsunwrapped(for:)","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"coordinateBoundsUnwrapped","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CameraOptions","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps13CameraOptionsV"},{"text":") -> ","kind":"text"},{"text":"CoordinateBounds","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMCoordinateBounds"}],"title":"coordinateBoundsUnwrapped(for:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"abstract":[],"url":"\/documentation\/mapboxmaps\/mapboxmap-apis","title":"MapboxMap","role":"collectionGroup","kind":"article","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/coordinateBoundsZoomUnwrapped(for:)":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"coordinateBoundsZoomUnwrapped"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10MapboxMaps13CameraOptionsV","kind":"typeIdentifier","text":"CameraOptions"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)MBMCoordinateBoundsZoom","kind":"typeIdentifier","text":"CoordinateBoundsZoom"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/coordinateBoundsZoomUnwrapped(for:)","url":"\/documentation\/mapboxmaps\/mapboxmap\/coordinateboundszoomunwrapped(for:)","abstract":[{"type":"text","text":"Returns the unwrapped coordinate bounds and zoom for a given "},{"type":"codeVoice","code":"CameraOptions"},{"type":"text","text":"."}],"kind":"symbol","role":"symbol","title":"coordinateBoundsZoomUnwrapped(for:)"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"kind":"article","role":"collection","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraOptions":{"abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraOptions"}],"url":"\/documentation\/mapboxmaps\/cameraoptions","title":"CameraOptions","role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraOptions"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateBoundsZoom":{"role":"symbol","type":"topic","title":"CoordinateBoundsZoom","url":"\/documentation\/mapboxmaps\/coordinateboundszoom","abstract":[{"text":"A coordinate bounds and zoom.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoordinateBoundsZoom","kind":"identifier"}],"navigatorTitle":[{"text":"CoordinateBoundsZoom","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBoundsZoom"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","type":"topic","title":"MapboxMap","url":"\/documentation\/mapboxmaps\/mapboxmap","abstract":[{"text":"Provides access to the map model, including the camera, style, observable map events,","type":"text"},{"text":" ","type":"text"},{"text":"and querying rendered features.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapboxMap","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"MapboxMap","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBoundsZoom\/title","op":"replace","value":"MBMCoordinateBoundsZoom"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBoundsZoom\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMCoordinateBoundsZoom"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBoundsZoom\/navigatorTitle","op":"replace","value":[{"text":"MBMCoordinateBoundsZoom","kind":"identifier"}]}]}]}