{"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateInfo\/coordinate","interfaceLanguage":"swift"},"abstract":[{"text":"The geographical coordinate corresponding to the given screen coordinate.","type":"text"},{"type":"text","text":" "},{"text":"This will be the closest position projected onto the map surface,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"in case the screen coordinate does not intersect with the map surface."}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"roleHeading":"Instance Property","modules":[{"name":"MapboxMaps"}],"title":"coordinate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"coordinate","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"}],"navigatorTitle":[{"kind":"identifier","text":"coordinate"}],"symbolKind":"property","role":"symbol","externalID":"c:objc(cs)MBMCoordinateInfo(py)coordinate"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"coordinate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/coordinateinfo\/coordinate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/coordinateinfo\/coordinate"]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateInfo"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","kind":"article","url":"\/documentation\/mapboxmaps\/mapboxmap-apis","title":"MapboxMap","type":"topic","abstract":[],"role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateInfo":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateInfo","abstract":[{"text":"Represents the coordinate information returned by the ","type":"text"},{"type":"codeVoice","code":"coordinateInfoForPixel"},{"type":"text","text":" or "},{"code":"coordinatesInfoForPixels","type":"codeVoice"},{"text":" methods.","type":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"CoordinateInfo","kind":"identifier"}],"title":"CoordinateInfo","url":"\/documentation\/mapboxmaps\/coordinateinfo","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CoordinateInfo"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateInfo/coordinate":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateInfo\/coordinate","url":"\/documentation\/mapboxmaps\/coordinateinfo\/coordinate","type":"topic","kind":"symbol","title":"coordinate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"coordinate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"coordinate","kind":"identifier"}],"role":"symbol","abstract":[{"text":"The geographical coordinate corresponding to the given screen coordinate.","type":"text"},{"text":" ","type":"text"},{"text":"This will be the closest position projected onto the map surface,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"in case the screen coordinate does not intersect with the map surface."}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","abstract":[],"title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","kind":"article","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","title":"MapboxMaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"role":"collection","url":"\/documentation\/mapboxmaps"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"coordinate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"coordinate","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D"},{"kind":"text","text":" "},{"text":"coordinate","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateInfo\/title","value":"MBMCoordinateInfo"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateInfo\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMCoordinateInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateInfo\/navigatorTitle","value":[{"text":"MBMCoordinateInfo","kind":"identifier"}]},{"op":"replace","value":"coordinate","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateInfo~1coordinate\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateInfo~1coordinate\/fragments","value":[{"kind":"identifier","text":"coordinate"}]}]}]}