{"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter\/onMapLoadingError","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/snapshotter\/onmaploadingerror"]}],"abstract":[{"text":"An error that has occurred while loading the Map. The ","type":"text"},{"code":"type","type":"codeVoice"},{"type":"text","text":" property defines what resource could"},{"type":"text","text":" "},{"text":"not be loaded and the ","type":"text"},{"code":"message","type":"codeVoice"},{"type":"text","text":" property will contain a descriptive error message."},{"text":" ","type":"text"},{"type":"text","text":"In case of "},{"type":"codeVoice","code":"source"},{"text":" or ","type":"text"},{"code":"tile","type":"codeVoice"},{"text":" loading errors, ","type":"text"},{"type":"codeVoice","code":"sourceID"},{"type":"text","text":" or "},{"code":"tileID","type":"codeVoice"},{"type":"text","text":" will contain the identifier of the source failing."}],"kind":"symbol","metadata":{"role":"symbol","symbolKind":"property","title":"onMapLoadingError","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"onMapLoadingError","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Signal","preciseIdentifier":"s:10MapboxMaps6SignalV","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"text":"MapLoadingError","preciseIdentifier":"c:objc(cs)MBMMapLoadingError","kind":"typeIdentifier"},{"text":">","kind":"text"}],"modules":[{"name":"MapboxMaps"}],"extendedModule":"MapboxMaps","externalID":"s:10MapboxMaps11SnapshotterC17onMapLoadingErrorAA6SignalVySo06MBMMapfG0CGvp"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"onMapLoadingError","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10MapboxMaps6SignalV","kind":"typeIdentifier","text":"Signal","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Signal"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)MBMMapLoadingError","text":"MapLoadingError","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingError","kind":"typeIdentifier"},{"text":"> { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Signal":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Signal","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/signal","title":"Signal","navigatorTitle":[{"text":"Signal","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Signal","type":"topic","abstract":[{"type":"text","text":"Signal is a typed interface for observing arbitrary values over time."}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","url":"\/documentation\/overview","kind":"article","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoadingError":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingError","kind":"symbol","role":"symbol","title":"MapLoadingError","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MapLoadingError"}],"url":"\/documentation\/mapboxmaps\/maploadingerror","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapLoadingError"}],"abstract":[{"text":"Describes an error that has occurred while loading the ","type":"text"},{"code":"map","type":"codeVoice"},{"text":". The ","type":"text"},{"type":"codeVoice","code":"type"},{"type":"text","text":" property"},{"type":"text","text":" "},{"text":"defines what resource could not be loaded, and the ","type":"text"},{"type":"codeVoice","code":"message"},{"text":" property will contain","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"a descriptive error message."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","kind":"symbol","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Snapshotter":{"type":"topic","title":"Snapshotter","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Snapshotter"}],"navigatorTitle":[{"text":"Snapshotter","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter","url":"\/documentation\/mapboxmaps\/snapshotter","kind":"symbol","abstract":[{"type":"text","text":"A utility class for capturing styled map snapshots."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Snapshotter-APIs":{"role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter-APIs","title":"Snapshotter","type":"topic","url":"\/documentation\/mapboxmaps\/snapshotter-apis","abstract":[],"kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Snapshotter/onMapLoadingError":{"title":"onMapLoadingError","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter\/onMapLoadingError","type":"topic","url":"\/documentation\/mapboxmaps\/snapshotter\/onmaploadingerror","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onMapLoadingError","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Signal","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"kind":"text","text":"<"},{"text":"MapLoadingError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMMapLoadingError"},{"kind":"text","text":">"}],"abstract":[{"type":"text","text":"An error that has occurred while loading the Map. The "},{"code":"type","type":"codeVoice"},{"text":" property defines what resource could","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"not be loaded and the "},{"type":"codeVoice","code":"message"},{"type":"text","text":" property will contain a descriptive error message."},{"type":"text","text":" "},{"type":"text","text":"In case of "},{"code":"source","type":"codeVoice"},{"text":" or ","type":"text"},{"type":"codeVoice","code":"tile"},{"type":"text","text":" loading errors, "},{"code":"sourceID","type":"codeVoice"},{"text":" or ","type":"text"},{"type":"codeVoice","code":"tileID"},{"text":" will contain the identifier of the source failing.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"MBMMapLoadingError","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingError\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingError\/fragments","value":[{"text":"MBMMapLoadingError","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingError\/navigatorTitle","value":[{"text":"MBMMapLoadingError","kind":"identifier"}],"op":"replace"}]}]}