{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"delay"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMapsInternal","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TransitionOptions-swift.class"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/mbmtransitionoptions\/delay"]}],"metadata":{"externalID":"c:objc(cs)MBMTransitionOptions(py)delay","modules":[{"name":"MapboxMaps"}],"fragments":[{"text":"delay","kind":"identifier"}],"roleHeading":"Instance Property","title":"delay","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"delay"}],"role":"symbol"},"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMTransitionOptions\/delay"},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Length of time before a transition begins. Units in milliseconds. Defaults to "},{"code":"0.0","type":"codeVoice"},{"text":".","type":"text"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMTransitionOptions/delay":{"abstract":[{"text":"Length of time before a transition begins. Units in milliseconds. Defaults to ","type":"text"},{"code":"0.0","type":"codeVoice"},{"type":"text","text":"."}],"title":"delay","kind":"symbol","type":"topic","fragments":[{"text":"delay","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/mbmtransitionoptions\/delay","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMTransitionOptions\/delay","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","kind":"symbol","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMapsInternal":{"abstract":[{"type":"text","text":"Maps rendering SDK also known as GL-Native. These are for internal use only."}],"role":"collectionGroup","kind":"article","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMapsInternal","url":"\/documentation\/mapboxmaps\/coremapsinternal","title":"CoreMaps - Internal"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","url":"\/documentation\/overview","kind":"article","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TransitionOptions-swift.class":{"role":"symbol","title":"TransitionOptions","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TransitionOptions","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TransitionOptions-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"text":"TransitionOptions","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/transitionoptions-swift.class","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"transition options"},{"text":" controls timing for the interpolation between a transitionable style","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"property’s previous value and new value. These can be used to define the style default property"},{"type":"text","text":" "},{"type":"text","text":"transition behavior. Also, any transitionable style property may also have its own "},{"code":"-transition","type":"codeVoice"},{"text":" ","type":"text"},{"type":"text","text":"property that defines specific transition timing for that specific layer property, overriding"},{"type":"text","text":" "},{"type":"text","text":"the global transition values."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TransitionOptions-swift.class\/title","value":"MBMTransitionOptions"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TransitionOptions-swift.class\/fragments","value":[{"kind":"identifier","text":"MBMTransitionOptions"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TransitionOptions-swift.class\/navigatorTitle","value":[{"text":"MBMTransitionOptions","kind":"identifier"}]}]}]}