{"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"modules":[{"name":"MapboxMaps"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"begin"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"begin","kind":"identifier"}],"symbolKind":"property","title":"begin","role":"symbol","roleHeading":"Instance Property","externalID":"c:objc(cs)MBMEventTimeInterval(py)begin"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/EventTimeInterval"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"begin"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"The timestamp at which the event begins."}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMEventTimeInterval\/begin"},"variants":[{"paths":["\/documentation\/mapboxmaps\/mbmeventtimeinterval\/begin"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/mbmeventtimeinterval\/begin"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMEventTimeInterval/begin":{"title":"begin","abstract":[{"text":"The timestamp at which the event begins.","type":"text"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"begin"}],"url":"\/documentation\/mapboxmaps\/mbmeventtimeinterval\/begin","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMEventTimeInterval\/begin","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"begin","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","title":"Map events","role":"collectionGroup","type":"topic","abstract":[{"type":"text","text":"The simplified diagram of the events emitted by the map is displayed below."}],"url":"\/documentation\/mapboxmaps\/events","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/EventTimeInterval":{"navigatorTitle":[{"kind":"identifier","text":"EventTimeInterval"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"EventTimeInterval"}],"type":"topic","title":"EventTimeInterval","abstract":[{"text":"The time interval of an event. The ","type":"text"},{"type":"codeVoice","code":"begin"},{"type":"text","text":" property represents the time"},{"type":"text","text":" "},{"type":"text","text":"origin of an event, and the "},{"type":"codeVoice","code":"end"},{"text":" property represents the time when the particular","type":"text"},{"text":" ","type":"text"},{"text":"operation is complete. The timestamps are sampled at the origin and do not include","type":"text"},{"type":"text","text":" "},{"type":"text","text":"the time required to dispatch an event."}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/EventTimeInterval","url":"\/documentation\/mapboxmaps\/eventtimeinterval","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"begin","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"begin"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSDate","preciseIdentifier":"c:objc(cs)NSDate"},{"kind":"text","text":" * "},{"kind":"identifier","text":"begin"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMEventTimeInterval~1begin\/title","op":"replace","value":"begin"},{"value":[{"text":"begin","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMEventTimeInterval~1begin\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1EventTimeInterval\/title","value":"MBMEventTimeInterval","op":"replace"},{"value":[{"kind":"identifier","text":"MBMEventTimeInterval"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1EventTimeInterval\/fragments"}]}]}