{"kind":"symbol","metadata":{"modules":[{"name":"MapboxCommon"}],"navigatorTitle":[{"text":"setLoggingLevelForUpTo:","kind":"identifier"}],"symbolKind":"method","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setLoggingLevelForUpTo"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"text":"?)","kind":"text"}],"role":"symbol","title":"setLoggingLevelForUpTo(_:)","externalID":"c:objc(cs)MBXLogConfiguration(cm)setLoggingLevelForUpTo:","roleHeading":"Type Method"},"abstract":[{"text":"Sets the default logging level.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogConfiguration\/setLoggingLevelForUpTo(_:)"},"variants":[{"paths":["\/documentation\/mapboxcommon\/logconfiguration\/setlogginglevelforupto(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/logconfiguration\/setlogginglevelforupto(_:)"]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogConfiguration"]]},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLoggingLevelForUpTo"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"upTo","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?)","kind":"text"}]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Log messages with lower severity than this parameter will be filtered out. If"},{"type":"text","text":" "},{"text":"the parameter is empty, all log messages are filtered out, i.e., logging is disabled.","type":"text"}],"type":"paragraph"}],"name":"upTo"}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"inlineContent":[{"text":"The logging level for a specific category can be overridden","type":"text"},{"type":"text","text":" "},{"text":"using the setLoggingLevel(category, upTo) overload.","type":"text"}],"type":"paragraph"}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LogConfiguration":{"url":"\/documentation\/mapboxcommon\/logconfiguration","kind":"symbol","type":"topic","title":"LogConfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"LogConfiguration","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"LogConfiguration"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogConfiguration","abstract":[{"type":"text","text":"Class that allows to configure Mapbox SDKs logging per application."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Performance":{"role":"collectionGroup","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","abstract":[],"kind":"article","title":"Performance and investigations","url":"\/documentation\/mapboxmaps\/performance"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LogConfiguration/setLoggingLevelForUpTo(_:)":{"url":"\/documentation\/mapboxcommon\/logconfiguration\/setlogginglevelforupto(_:)","navigatorTitle":[{"text":"setLoggingLevelForUpTo:","kind":"identifier"}],"abstract":[{"type":"text","text":"Sets the default logging level."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setLoggingLevelForUpTo","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogConfiguration\/setLoggingLevelForUpTo(_:)","title":"setLoggingLevelForUpTo(_:)","type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"url":"\/documentation\/mapboxmaps","title":"MapboxMaps","type":"topic","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"op":"replace","value":"setLoggingLevelForUpTo:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"setLoggingLevelForUpTo:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"setLoggingLevelForUpTo:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":" *) "},{"text":"upTo","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"Log messages with lower severity than this parameter will be filtered out. If","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"the parameter is empty, all log messages are filtered out, i.e., logging is disabled."}],"type":"paragraph"}],"name":"upTo"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogConfiguration\/title","value":"MBXLogConfiguration","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogConfiguration\/fragments","value":[{"kind":"identifier","text":"MBXLogConfiguration"}]},{"value":[{"text":"MBXLogConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogConfiguration\/navigatorTitle","op":"replace"},{"op":"replace","value":"setLoggingLevelForUpTo:","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogConfiguration~1setLoggingLevelForUpTo(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogConfiguration~1setLoggingLevelForUpTo(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"setLoggingLevelForUpTo:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}