{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Callback which is used to report result of HTTP request.","type":"text"}],"kind":"symbol","identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpResponseCallback","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"text":"HttpResponseCallback","kind":"identifier"}],"modules":[{"name":"MapboxCommon"}],"symbolKind":"typealias","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"HttpResponseCallback","kind":"identifier"}],"role":"symbol","title":"HttpResponseCallback","externalID":"c:MBXHttpResponseCallback.h@T@MBXHttpResponseCallback","roleHeading":"Type Alias"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HttpResponseCallback","kind":"identifier"},{"kind":"text","text":" = ("},{"text":"HttpResponse","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpResponse","preciseIdentifier":"c:objc(cs)MBXHttpResponse"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/httpresponsecallback"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/httpresponsecallback"]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpResponseCallback":{"kind":"symbol","navigatorTitle":[{"text":"HttpResponseCallback","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/httpresponsecallback","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpResponseCallback","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"HttpResponseCallback","kind":"identifier"}],"type":"topic","title":"HttpResponseCallback","role":"symbol","abstract":[{"type":"text","text":"Callback which is used to report result of HTTP request."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","kind":"symbol","role":"collection","type":"topic","abstract":[],"url":"\/documentation\/mapboxcommon","title":"MapboxCommon"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article","role":"collection","type":"topic","abstract":[],"url":"\/documentation\/overview","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpResponse":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"HttpResponse","kind":"identifier"}],"title":"HttpResponse","url":"\/documentation\/mapboxcommon\/httpresponse","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpResponse","navigatorTitle":[{"kind":"identifier","text":"HttpResponse"}],"type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Record which is used to report HTTP response to the caller."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Type Alias","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"MBXHttpResponseCallback","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"typealias"},{"value":[{"text":"MBXHttpResponseCallback","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"MBXHttpResponseCallback","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"typedef"},{"text":" ","kind":"text"},{"text":"void (^)(MBXHttpResponse *)","kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$objc(cs)MBXHttpResponse)"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBXHttpResponseCallback"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpResponseCallback\/title","value":"MBXHttpResponseCallback","op":"replace"},{"value":[{"text":"MBXHttpResponseCallback","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpResponseCallback\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpResponseCallback\/navigatorTitle","value":[{"text":"MBXHttpResponseCallback","kind":"identifier"}]},{"value":"MBXHttpResponse","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpResponse\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpResponse\/fragments","value":[{"text":"MBXHttpResponse","kind":"identifier"}]},{"op":"replace","value":[{"text":"MBXHttpResponse","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpResponse\/navigatorTitle"}]}]}