{"sections":[],"abstract":[{"text":"TileRegion represents an identifiable geographic tile region with metadata","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs"]]},"seeAlsoSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStoreOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudget","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInMegabytes","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInTiles","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCoverOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileRegionError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgress","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TilesetDescriptor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TilesetDescriptorOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgressCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreUsageMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileRegionError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileDataDomain","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgress","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateResult","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgressCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingErrorType"],"generated":true,"anchor":"TileStore","title":"TileStore"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileRegion","kind":"identifier"}]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"topicSections":[{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegion\/completedResourceCount","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegion\/completedResourceSize","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegion\/expires","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegion\/id","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegion\/requiredResourceCount"]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH"],"kind":"relationships"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/tileregion"]},{"paths":["\/documentation\/mapboxcommon\/tileregion"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"TileRegion","navigatorTitle":[{"text":"TileRegion","kind":"identifier"}],"roleHeading":"Class","externalID":"c:objc(cs)MBXTileRegion","modules":[{"name":"MapboxCommon"}],"symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileRegion"}],"role":"symbol"},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegion","interfaceLanguage":"swift"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CanonicalTileID":{"url":"\/documentation\/mapboxmaps\/canonicaltileid","navigatorTitle":[{"kind":"identifier","text":"CanonicalTileID"}],"title":"CanonicalTileID","abstract":[{"text":"Represents a tile coordinate.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CanonicalTileID"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID","type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateResult":{"title":"TileRegionEstimateResult","navigatorTitle":[{"text":"TileRegionEstimateResult","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/tileregionestimateresult","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileRegionEstimateResult"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateResult","type":"topic","role":"symbol","abstract":[{"type":"text","text":"The result of tile region estim"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStoreObserver":{"url":"\/documentation\/mapboxmaps\/tilestoreobserver","title":"TileStoreObserver","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileStoreObserver"}],"navigatorTitle":[{"kind":"identifier","text":"TileStoreObserver"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreObserver"},"doc://com.mapbox.MapboxMaps/s7CVarArgP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.mapbox.MapboxMaps/objc(cs)NSObject":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","title":"MapboxMaps","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegion/id":{"title":"id","navigatorTitle":[{"text":"id","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/tileregion\/id","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"id"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegion\/id","type":"topic","role":"symbol","abstract":[{"type":"text","text":"The id of the tile region"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadProgress":{"url":"\/documentation\/mapboxcommon\/tileregionloadprogress","title":"TileRegionLoadProgress","type":"topic","abstract":[{"type":"text","text":"A tile region’s load progress includes counts"},{"type":"text","text":" "},{"text":"of the number of resources that have completed downloading","type":"text"},{"type":"text","text":" "},{"text":"and the total number of resources that are required.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TileRegionLoadProgress"}],"navigatorTitle":[{"text":"TileRegionLoadProgress","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgress"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegion/completedResourceCount":{"title":"completedResourceCount","navigatorTitle":[{"kind":"identifier","text":"completedResourceCount"}],"url":"\/documentation\/mapboxcommon\/tileregion\/completedresourcecount","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"completedResourceCount"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V","text":"UInt64"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegion\/completedResourceCount","type":"topic","role":"symbol","abstract":[{"text":"The number of resources that have been fully downloaded and are ready for","type":"text"},{"type":"text","text":" "},{"type":"text","text":"offline access."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TilesetDescriptor":{"url":"\/documentation\/mapboxcommon\/tilesetdescriptor","title":"TilesetDescriptor","type":"topic","abstract":[{"type":"text","text":"A bundle that encapsulates tilesets creation for the tile store implementation."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TilesetDescriptor"}],"navigatorTitle":[{"text":"TilesetDescriptor","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TilesetDescriptor"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileStore":{"title":"TileStore","navigatorTitle":[{"kind":"identifier","text":"TileStore"}],"url":"\/documentation\/mapboxcommon\/tilestore","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileStore"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore","type":"topic","role":"symbol","abstract":[{"text":"TileStore manages downloads and storage for requests to tile-related API endpoints, enforcing a disk usage","type":"text"},{"type":"text","text":" "},{"text":"quota: tiles available on disk may be deleted to make room for a new download. This interface can be used by an","type":"text"},{"type":"text","text":" "},{"type":"text","text":"app developer to set the disk quota. The rest of TileStore API is intended for native SDK consumption only."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileOptions":{"url":"\/documentation\/mapboxmaps\/tileoptions","title":"TileOptions","type":"topic","abstract":[{"type":"text","text":"Options for custom geometry tiles."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TileOptions"}],"navigatorTitle":[{"text":"TileOptions","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileOptions"},"doc://com.mapbox.MapboxMaps/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateProgress":{"url":"\/documentation\/mapboxcommon\/tileregionestimateprogress","type":"topic","abstract":[{"text":"A tile region’s estimate progress includes counts of the number of resources that have","type":"text"},{"type":"text","text":" "},{"text":"been estimated and the total number of resources as well as a partial result with the","type":"text"},{"type":"text","text":" "},{"type":"text","text":"current estimate, calculated using the data available at the moment."}],"title":"TileRegionEstimateProgress","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileRegionEstimateProgress"}],"navigatorTitle":[{"kind":"identifier","text":"TileRegionEstimateProgress"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgress"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegion/requiredResourceCount":{"title":"requiredResourceCount","navigatorTitle":[{"text":"requiredResourceCount","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/tileregion\/requiredresourcecount","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiredResourceCount"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V","text":"UInt64"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegion\/requiredResourceCount","role":"symbol","abstract":[{"type":"text","text":"The number of resources that are known to be required for this tile region."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/CacheClearingErrorType":{"url":"\/documentation\/mapboxcommon\/cacheclearingerrortype","type":"topic","abstract":[{"type":"text","text":"Describes the reason for a cache clearing failure."}],"title":"CacheClearingErrorType","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CacheClearingErrorType"}],"navigatorTitle":[{"kind":"identifier","text":"CacheClearingErrorType"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingErrorType"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegion/completedResourceSize":{"title":"completedResourceSize","navigatorTitle":[{"text":"completedResourceSize","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/tileregion\/completedresourcesize","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"completedResourceSize"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V","text":"UInt64"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegion\/completedResourceSize","role":"symbol","abstract":[{"text":"The cumulative size, in bytes, of all resources (inclusive of tiles) that have","type":"text"},{"type":"text","text":" "},{"type":"text","text":"been fully downloaded."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateProgressCallback":{"url":"\/documentation\/mapboxcommon\/tileregionestimateprogresscallback","type":"topic","abstract":[],"title":"TileRegionEstimateProgressCallback","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileRegionEstimateProgressCallback"}],"navigatorTitle":[{"kind":"identifier","text":"TileRegionEstimateProgressCallback"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgressCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegion/expires":{"title":"expires","navigatorTitle":[{"kind":"identifier","text":"expires"}],"url":"\/documentation\/mapboxcommon\/tileregion\/expires","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"expires","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"kind":"text","text":"?"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegion\/expires","role":"symbol","abstract":[{"type":"text","text":"The earliest point in time when any of the region resources gets expired."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileStoreOptions":{"url":"\/documentation\/mapboxcommon\/tilestoreoptions","type":"topic","abstract":[{"type":"text","text":"These constants can be used as keys for TileStore::setOption to configure further aspects of a TileStore instance."}],"title":"TileStoreOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TileStoreOptions","kind":"identifier"}],"navigatorTitle":[{"text":"TileStoreOptions","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStoreOptions"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article","role":"collection","type":"topic","abstract":[],"url":"\/documentation\/overview","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudgetType":{"title":"TileCacheBudgetType","navigatorTitle":[{"kind":"identifier","text":"TileCacheBudgetType"}],"url":"\/documentation\/mapboxmaps\/tilecachebudgettype","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TileCacheBudgetType"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetType","role":"symbol","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadOptions":{"url":"\/documentation\/mapboxcommon\/tileregionloadoptions","title":"TileRegionLoadOptions","type":"topic","abstract":[{"type":"text","text":"Describes the tile region load option values."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TileRegionLoadOptions"}],"navigatorTitle":[{"kind":"identifier","text":"TileRegionLoadOptions"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegion":{"title":"TileRegion","navigatorTitle":[{"kind":"identifier","text":"TileRegion"}],"url":"\/documentation\/mapboxcommon\/tileregion","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TileRegion","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegion","type":"topic","role":"symbol","abstract":[{"type":"text","text":"TileRegion represents an identifiable geographic tile region with metadata"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/CacheClearingError":{"url":"\/documentation\/mapboxcommon\/cacheclearingerror","title":"CacheClearingError","type":"topic","abstract":[{"type":"text","text":"Describes a cache clearing error."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CacheClearingError"}],"navigatorTitle":[{"kind":"identifier","text":"CacheClearingError"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingError"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadProgressCallback":{"title":"TileRegionLoadProgressCallback","navigatorTitle":[{"kind":"identifier","text":"TileRegionLoadProgressCallback"}],"url":"\/documentation\/mapboxcommon\/tileregionloadprogresscallback","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"TileRegionLoadProgressCallback","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgressCallback","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Callback Invoked to report the progess of the tile region loading operation."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","kind":"article","role":"collectionGroup","type":"topic","abstract":[],"url":"\/documentation\/mapboxmaps\/tilestore-apis","title":"TileStore APIs"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudgetInTiles":{"url":"\/documentation\/mapboxmaps\/tilecachebudgetintiles","title":"TileCacheBudgetInTiles","type":"topic","abstract":[{"type":"text","text":"Tile cache budget in tiles."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TileCacheBudgetInTiles"}],"navigatorTitle":[{"kind":"identifier","text":"TileCacheBudgetInTiles"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInTiles"},"doc://com.mapbox.MapboxMaps/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileDataDomain":{"url":"\/documentation\/mapboxcommon\/tiledatadomain","title":"TileDataDomain","type":"topic","abstract":[{"type":"text","text":"Describes the tiles data domain."}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"TileDataDomain","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"TileDataDomain"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileDataDomain"},"doc://com.mapbox.MapboxMaps/SH":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","title":"Swift.Hashable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileRegionError":{"title":"TileRegionError","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileRegionError","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileRegionError","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxmaps\/tileregionerror","abstract":[{"type":"text","text":"Describes the reason for a tile region download request failure."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TileRegionError"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCoverOptions":{"url":"\/documentation\/mapboxmaps\/tilecoveroptions","title":"TileCoverOptions","type":"topic","abstract":[{"type":"text","text":"Various options needed for tile cover."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TileCoverOptions"}],"navigatorTitle":[{"kind":"identifier","text":"TileCoverOptions"}],"kind":"symbol","tags":[{"type":"spi","text":"SPI"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCoverOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudget":{"title":"TileCacheBudget","navigatorTitle":[{"text":"TileCacheBudget","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/tilecachebudget","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileCacheBudget"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudget","type":"topic","role":"symbol","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TilesetDescriptorOptions":{"url":"\/documentation\/mapboxmaps\/tilesetdescriptoroptions","title":"TilesetDescriptorOptions","type":"topic","abstract":[{"type":"text","text":"Describes the tileset descriptor option values."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TilesetDescriptorOptions","kind":"identifier"}],"navigatorTitle":[{"text":"TilesetDescriptorOptions","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TilesetDescriptorOptions"},"doc://com.mapbox.MapboxMaps/SQ":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.mapbox.MapboxMaps/objc(pl)NSObject":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudgetInMegabytes":{"title":"TileCacheBudgetInMegabytes","navigatorTitle":[{"kind":"identifier","text":"TileCacheBudgetInMegabytes"}],"url":"\/documentation\/mapboxmaps\/tilecachebudgetinmegabytes","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileCacheBudgetInMegabytes"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInMegabytes","type":"topic","role":"symbol","abstract":[{"text":"Tile cache budget in megabytes.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateOptions":{"url":"\/documentation\/mapboxcommon\/tileregionestimateoptions","title":"TileRegionEstimateOptions","type":"topic","abstract":[{"text":"Holds options for the tile region estimation operation.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TileRegionEstimateOptions","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"TileRegionEstimateOptions"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStoreUsageMode":{"title":"TileStoreUsageMode","navigatorTitle":[{"text":"TileStoreUsageMode","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/tilestoreusagemode","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileStoreUsageMode"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreUsageMode","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Describes tile store usage modes."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"value":"MBXTileRegion","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MBXTileRegion"}]},{"op":"replace","value":[{"kind":"identifier","text":"MBXTileRegion"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegion\/completedResourceCount","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegion\/completedResourceSize","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegion\/expires","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegion\/id","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegion\/requiredResourceCount"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}]},{"path":"\/seeAlsoSections","value":[{"generated":true,"title":"TileStore","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStoreOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudget","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInMegabytes","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInTiles","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgress","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TilesetDescriptor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TilesetDescriptorOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgressCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreUsageMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileDataDomain","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgress","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateResult","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgressCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingErrorType"],"anchor":"TileStore"}],"op":"replace"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBXTileRegion"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/title","op":"replace","value":"MBMCanonicalTileID"},{"value":[{"kind":"identifier","text":"MBMCanonicalTileID"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/fragments","op":"replace"},{"value":[{"text":"MBMCanonicalTileID","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateResult\/title","value":"MBXTileRegionEstimateResult"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateResult\/fragments","value":[{"kind":"identifier","text":"MBXTileRegionEstimateResult"}]},{"value":[{"text":"MBXTileRegionEstimateResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateResult\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegion~1id\/title","value":"id"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegion~1id\/fragments","op":"replace","value":[{"kind":"identifier","text":"id"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgress\/title","value":"MBXTileRegionLoadProgress","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgress\/fragments","value":[{"kind":"identifier","text":"MBXTileRegionLoadProgress"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgress\/navigatorTitle","value":[{"text":"MBXTileRegionLoadProgress","kind":"identifier"}]},{"value":"completedResourceCount","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegion~1completedResourceCount\/title","op":"replace"},{"value":[{"kind":"identifier","text":"completedResourceCount"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegion~1completedResourceCount\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TilesetDescriptor\/title","value":"MBXTilesetDescriptor"},{"value":[{"text":"MBXTilesetDescriptor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TilesetDescriptor\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TilesetDescriptor\/navigatorTitle","value":[{"kind":"identifier","text":"MBXTilesetDescriptor"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/title","value":"MBXTileStore","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/fragments","value":[{"text":"MBXTileStore","kind":"identifier"}]},{"value":[{"text":"MBXTileStore","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/navigatorTitle","op":"replace"},{"value":"MBMTileOptions","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileOptions\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileOptions\/fragments","value":[{"text":"MBMTileOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileOptions\/navigatorTitle","value":[{"text":"MBMTileOptions","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"MBXTileRegionEstimateProgress","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgress\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgress\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXTileRegionEstimateProgress"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgress\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBXTileRegionEstimateProgress"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegion~1requiredResourceCount\/title","op":"replace","value":"requiredResourceCount"},{"op":"replace","value":[{"text":"requiredResourceCount","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegion~1requiredResourceCount\/fragments"},{"value":"MBXCacheClearingErrorType","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingErrorType\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingErrorType\/fragments","value":[{"text":"MBXCacheClearingErrorType","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingErrorType\/navigatorTitle","value":[{"kind":"identifier","text":"MBXCacheClearingErrorType"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegion~1completedResourceSize\/title","value":"completedResourceSize","op":"replace"},{"value":[{"text":"completedResourceSize","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegion~1completedResourceSize\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgressCallback\/title","value":"MBXTileRegionEstimateProgressCallback"},{"op":"replace","value":[{"text":"MBXTileRegionEstimateProgressCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgressCallback\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgressCallback\/navigatorTitle","value":[{"kind":"identifier","text":"MBXTileRegionEstimateProgressCallback"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegion~1expires\/title","op":"replace","value":"expires"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegion~1expires\/fragments","value":[{"text":"expires","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStoreOptions\/title","value":"MBXTileStoreOptions"},{"value":[{"text":"MBXTileStoreOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStoreOptions\/fragments","op":"replace"},{"value":[{"text":"MBXTileStoreOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStoreOptions\/navigatorTitle"},{"value":"MBMTileCacheBudgetType","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetType\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetType\/fragments","value":[{"text":"MBMTileCacheBudgetType","kind":"identifier"}]},{"op":"replace","value":[{"text":"MBMTileCacheBudgetType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetType\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/title","value":"MBXTileRegionLoadOptions"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/fragments","value":[{"text":"MBXTileRegionLoadOptions","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"MBXTileRegionLoadOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegion\/title","value":"MBXTileRegion","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegion\/fragments","value":[{"kind":"identifier","text":"MBXTileRegion"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegion\/navigatorTitle","value":[{"kind":"identifier","text":"MBXTileRegion"}],"op":"replace"},{"value":"MBXCacheClearingError","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingError\/title","op":"replace"},{"value":[{"text":"MBXCacheClearingError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingError\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingError\/navigatorTitle","value":[{"text":"MBXCacheClearingError","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgressCallback\/title","value":"MBXTileRegionLoadProgressCallback"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgressCallback\/fragments","value":[{"kind":"identifier","text":"MBXTileRegionLoadProgressCallback"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgressCallback\/navigatorTitle","op":"replace","value":[{"text":"MBXTileRegionLoadProgressCallback","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInTiles\/title","value":"MBMTileCacheBudgetInTiles","op":"replace"},{"value":[{"text":"MBMTileCacheBudgetInTiles","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInTiles\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInTiles\/navigatorTitle","value":[{"text":"MBMTileCacheBudgetInTiles","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileDataDomain\/title","value":"MBXTileDataDomain"},{"value":[{"text":"MBXTileDataDomain","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileDataDomain\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileDataDomain\/navigatorTitle","value":[{"text":"MBXTileDataDomain","kind":"identifier"}]},{"value":"MBMTileCacheBudget","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudget\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudget\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMTileCacheBudget"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudget\/navigatorTitle","value":[{"kind":"identifier","text":"MBMTileCacheBudget"}]},{"value":"MBMTilesetDescriptorOptions","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions\/fragments","value":[{"kind":"identifier","text":"MBMTilesetDescriptorOptions"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions\/navigatorTitle","value":[{"kind":"identifier","text":"MBMTilesetDescriptorOptions"}]},{"op":"replace","value":"MBMTileCacheBudgetInMegabytes","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInMegabytes\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInMegabytes\/fragments","value":[{"kind":"identifier","text":"MBMTileCacheBudgetInMegabytes"}]},{"value":[{"kind":"identifier","text":"MBMTileCacheBudgetInMegabytes"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInMegabytes\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateOptions\/title","value":"MBXTileRegionEstimateOptions"},{"value":[{"kind":"identifier","text":"MBXTileRegionEstimateOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateOptions\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateOptions\/navigatorTitle","value":[{"text":"MBXTileRegionEstimateOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileStoreUsageMode\/title","value":"MBMTileStoreUsageMode","op":"replace"},{"value":[{"text":"MBMTileStoreUsageMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileStoreUsageMode\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileStoreUsageMode\/navigatorTitle","value":[{"kind":"identifier","text":"MBMTileStoreUsageMode"}]}]}]}