{"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry\/extractGeometriesArray()","interfaceLanguage":"swift"},"sections":[],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"extractGeometriesArray"},{"text":"() -> [","kind":"text"},{"text":"Geometry","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXGeometry"},{"kind":"text","text":"]?"}],"modules":[{"name":"MapboxCommon"}],"navigatorTitle":[{"kind":"identifier","text":"extractGeometriesArray"}],"title":"extractGeometriesArray()","symbolKind":"method","role":"symbol","roleHeading":"Instance Method","externalID":"c:objc(cs)MBXGeometry(im)extractGeometriesArray"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/geometry\/extractgeometriesarray()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/geometry\/extractgeometriesarray()"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"extractGeometriesArray"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry","text":"Geometry","preciseIdentifier":"c:objc(cs)MBXGeometry"},{"kind":"text","text":"]?"}],"languages":["swift"]}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"url":"\/documentation\/mapboxcommon","kind":"symbol","abstract":[],"title":"MapboxCommon","type":"topic","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Geometry/extractGeometriesArray()":{"navigatorTitle":[{"text":"extractGeometriesArray","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry\/extractGeometriesArray()","role":"symbol","kind":"symbol","title":"extractGeometriesArray()","url":"\/documentation\/mapboxcommon\/geometry\/extractgeometriesarray()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"extractGeometriesArray"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXGeometry","text":"Geometry"},{"text":"]?","kind":"text"}],"type":"topic","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"type":"topic","title":"MapboxMaps Documentation","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Geometry":{"type":"topic","title":"Geometry","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Geometry"}],"url":"\/documentation\/mapboxcommon\/geometry","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Geometry","kind":"identifier"}],"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"extractGeometriesArray"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"extractGeometriesArray","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"NSArray<MBXGeometry *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"extractGeometriesArray"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry~1extractGeometriesArray()\/title","op":"replace","value":"extractGeometriesArray"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry~1extractGeometriesArray()\/fragments","value":[{"kind":"text","text":"- "},{"text":"extractGeometriesArray","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry\/title","value":"MBXGeometry","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBXGeometry"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry\/navigatorTitle","value":[{"text":"MBXGeometry","kind":"identifier"}],"op":"replace"}]}]}