{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/OfflineSwitch"]]},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/OfflineSwitch\/getInstance()","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","abstract":[{"type":"text","text":"Returns the OfflineSwitch singleton instance."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getInstance"},{"text":"() -> ","kind":"text"},{"text":"OfflineSwitch","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXOfflineSwitch","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/OfflineSwitch"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"variants":[{"paths":["\/documentation\/mapboxcommon\/offlineswitch\/getinstance()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/offlineswitch\/getinstance()"]}],"metadata":{"title":"getInstance()","symbolKind":"method","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getInstance","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"OfflineSwitch","preciseIdentifier":"c:objc(cs)MBXOfflineSwitch","kind":"typeIdentifier"}],"role":"symbol","roleHeading":"Type Method","navigatorTitle":[{"kind":"identifier","text":"getInstance"}],"externalID":"c:objc(cs)MBXOfflineSwitch(cm)getInstance","modules":[{"name":"MapboxCommon"}]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/OfflineSwitch":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/OfflineSwitch","url":"\/documentation\/mapboxcommon\/offlineswitch","kind":"symbol","title":"OfflineSwitch","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OfflineSwitch"}],"type":"topic","abstract":[{"type":"text","text":"Instance that allows connecting or disconnecting the Mapbox stack to the network."}],"navigatorTitle":[{"text":"OfflineSwitch","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","kind":"article","abstract":[],"url":"\/documentation\/overview","type":"topic","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/OfflineSwitch/getInstance()":{"title":"getInstance()","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/OfflineSwitch\/getInstance()","abstract":[{"type":"text","text":"Returns the OfflineSwitch singleton instance."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getInstance"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:objc(cs)MBXOfflineSwitch","text":"OfflineSwitch","kind":"typeIdentifier"}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"getInstance"}],"url":"\/documentation\/mapboxcommon\/offlineswitch\/getinstance()"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","kind":"symbol","url":"\/documentation\/mapboxcommon","title":"MapboxCommon"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","value":"getInstance","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"+ ","kind":"text"},{"text":"getInstance","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/OfflineSwitch","kind":"typeIdentifier","text":"MBXOfflineSwitch","preciseIdentifier":"c:objc(cs)MBXOfflineSwitch"},{"kind":"text","text":" *) "},{"text":"getInstance","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1OfflineSwitch\/title","value":"MBXOfflineSwitch"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1OfflineSwitch\/fragments","value":[{"kind":"identifier","text":"MBXOfflineSwitch"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1OfflineSwitch\/navigatorTitle","value":[{"text":"MBXOfflineSwitch","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1OfflineSwitch~1getInstance()\/title","value":"getInstance"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getInstance"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1OfflineSwitch~1getInstance()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}