{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Style","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager"]]},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Gets the value of style source property."}],"metadata":{"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sourceProperty","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"property"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMStylePropertyValue","text":"StylePropertyValue"}],"title":"sourceProperty(for:property:)","modules":[{"name":"MapboxMaps"}],"externalID":"s:10MapboxMaps12StyleManagerC14sourceProperty3for8propertySo08MBMStyleF5ValueCSS_SStF","roleHeading":"Instance Method","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sourceProperty","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"for"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"sourceId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"property","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMStylePropertyValue","text":"StylePropertyValue","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValue","kind":"typeIdentifier"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"sourceId","content":[{"inlineContent":[{"type":"text","text":"Style source identifier."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Style source property name.","type":"text"}],"type":"paragraph"}],"name":"property"}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The value of the property in the source with sourceId."}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/stylemanager\/sourceproperty(for:property:)"]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/sourceProperty(for:property:)","interfaceLanguage":"swift"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Style":{"type":"topic","title":"Style","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Style","url":"\/documentation\/mapboxmaps\/style","kind":"article","abstract":[],"role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","url":"\/documentation\/overview","kind":"article","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap":{"type":"topic","title":"MapboxMap","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapboxMap"}],"navigatorTitle":[{"kind":"identifier","text":"MapboxMap"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","url":"\/documentation\/mapboxmaps\/mapboxmap","kind":"symbol","abstract":[{"type":"text","text":"Provides access to the map model, including the camera, style, observable map events,"},{"text":" ","type":"text"},{"text":"and querying rendered features.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager":{"navigatorTitle":[{"text":"StyleManager","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"StyleManager"}],"title":"StyleManager","url":"\/documentation\/mapboxmaps\/stylemanager","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager","abstract":[{"text":"Style manager is a base class for ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","type":"reference"},{"type":"text","text":" and "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter"},{"type":"text","text":" that provides provides methods to manipulate Map Style at runtime."}],"role":"symbol","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/sourceProperty(for:property:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"sourceProperty","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"property","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"text":"StylePropertyValue","preciseIdentifier":"c:objc(cs)MBMStylePropertyValue","kind":"typeIdentifier"}],"title":"sourceProperty(for:property:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/sourceProperty(for:property:)","type":"topic","abstract":[{"type":"text","text":"Gets the value of style source property."}],"role":"symbol","url":"\/documentation\/mapboxmaps\/stylemanager\/sourceproperty(for:property:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","kind":"symbol","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePropertyValue":{"url":"\/documentation\/mapboxmaps\/stylepropertyvalue","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValue","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StylePropertyValue"}],"abstract":[{"text":"Holds a style property value with meta data.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"StylePropertyValue"}],"title":"StylePropertyValue","type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Snapshotter":{"type":"topic","title":"Snapshotter","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Snapshotter"}],"navigatorTitle":[{"text":"Snapshotter","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter","url":"\/documentation\/mapboxmaps\/snapshotter","kind":"symbol","abstract":[{"type":"text","text":"A utility class for capturing styled map snapshots."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MBMStylePropertyValue","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValue\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValue\/fragments","value":[{"text":"MBMStylePropertyValue","kind":"identifier"}]},{"value":[{"text":"MBMStylePropertyValue","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValue\/navigatorTitle"}]}]}