{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/InteractiveFeature\/featureset"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Featuresets-and-Interactions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/InteractiveFeature"]]},"variants":[{"paths":["\/documentation\/mapboxmaps\/interactivefeature\/featureset"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"A featureset descriptor denoting a featureset this feature belongs to."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"featureset","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MBMFeaturesetDescriptor","kind":"typeIdentifier","text":"FeaturesetDescriptor","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeaturesetDescriptor"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"featureset","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMFeaturesetDescriptor","text":"FeaturesetDescriptor","kind":"typeIdentifier"}],"title":"featureset","tags":[{"type":"spi","text":"SPI"}],"externalID":"s:10MapboxMaps18InteractiveFeatureC10featuresetSo23MBMFeaturesetDescriptorCvp","modules":[{"name":"MapboxMaps"}],"roleHeading":"Instance Property","role":"symbol"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FeaturesetDescriptor":{"navigatorTitle":[{"kind":"identifier","text":"FeaturesetDescriptor"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FeaturesetDescriptor","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeaturesetDescriptor","url":"\/documentation\/mapboxmaps\/featuresetdescriptor","title":"FeaturesetDescriptor","abstract":[{"type":"text","text":"Represents an identifier for a single exported featureset or a layer."}],"type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"title":"MapboxMaps","role":"collection","url":"\/documentation\/mapboxmaps","type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Featuresets-and-Interactions":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Featuresets-and-Interactions","abstract":[{"type":"text","text":"The experimental Interactions API."}],"title":"Featuresets and Interactions","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/featuresets-and-interactions","kind":"article","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/InteractiveFeature/featureset":{"url":"\/documentation\/mapboxmaps\/interactivefeature\/featureset","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/InteractiveFeature\/featureset","title":"featureset","type":"topic","tags":[{"text":"SPI","type":"spi"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"featureset"},{"kind":"text","text":": "},{"text":"FeaturesetDescriptor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMFeaturesetDescriptor"}],"abstract":[{"type":"text","text":"A featureset descriptor denoting a featureset this feature belongs to."}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"title":"MapboxMaps Documentation","role":"collection","url":"\/documentation\/overview","type":"topic","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/InteractiveFeature":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InteractiveFeature","kind":"identifier"}],"navigatorTitle":[{"text":"InteractiveFeature","kind":"identifier"}],"tags":[{"text":"SPI","type":"spi"}],"title":"InteractiveFeature","abstract":[{"text":"An interactive feature.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/InteractiveFeature","kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/interactivefeature"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"MBMFeaturesetDescriptor","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeaturesetDescriptor\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeaturesetDescriptor\/fragments","value":[{"kind":"identifier","text":"MBMFeaturesetDescriptor"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeaturesetDescriptor\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMFeaturesetDescriptor"}]}]}]}