{"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completedTileCount"},{"kind":"text","text":": "},{"text":"UInt64","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/offlineregionstatus\/completedtilecount"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/offlineregionstatus\/completedtilecount"]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionStatus"]]},"kind":"symbol","metadata":{"role":"symbol","externalID":"c:objc(cs)MBMOfflineRegionStatus(py)completedTileCount","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"completedTileCount"}],"title":"completedTileCount","roleHeading":"Instance Property","modules":[{"name":"MapboxMaps"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"completedTileCount","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s6UInt64V","text":"UInt64","kind":"typeIdentifier"}],"platforms":[]},"abstract":[{"text":"The number of tiles that are known to be required for this region. This is a","type":"text"},{"type":"text","text":" "},{"type":"text","text":"subset of "},{"code":"completedResourceCount","type":"codeVoice"},{"text":".","type":"text"}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionStatus\/completedTileCount","interfaceLanguage":"swift"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Offline":{"kind":"article","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","type":"topic","url":"\/documentation\/mapboxmaps\/offline","role":"collectionGroup","title":"Offline Support"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","role":"collection","abstract":[],"kind":"article","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMaps":{"kind":"article","abstract":[{"text":"Maps rendering SDK also known as GL-Native","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","type":"topic","url":"\/documentation\/mapboxmaps\/coremaps","role":"collectionGroup","title":"Core Maps API"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionStatus/completedTileCount":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionStatus\/completedTileCount","deprecated":true,"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The number of tiles that are known to be required for this region. This is a"},{"text":" ","type":"text"},{"text":"subset of ","type":"text"},{"type":"codeVoice","code":"completedResourceCount"},{"type":"text","text":"."}],"navigatorTitle":[{"kind":"identifier","text":"completedTileCount"}],"title":"completedTileCount","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completedTileCount"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt64","preciseIdentifier":"s:s6UInt64V"}],"url":"\/documentation\/mapboxmaps\/offlineregionstatus\/completedtilecount"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","url":"\/documentation\/mapboxmaps","type":"topic","role":"collection","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionStatus":{"navigatorTitle":[{"text":"OfflineRegionStatus","kind":"identifier"}],"title":"OfflineRegionStatus","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionStatus","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OfflineRegionStatus"}],"kind":"symbol","type":"topic","abstract":[{"text":"A region’s status includes its active\/inactive state as well as counts","type":"text"},{"text":" ","type":"text"},{"text":"of the number of resources that have completed downloading, their total","type":"text"},{"text":" ","type":"text"},{"text":"size in bytes, and the total number of resources that are required.","type":"text"}],"deprecated":true,"url":"\/documentation\/mapboxmaps\/offlineregionstatus"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"completedTileCount","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"kind":"identifier","text":"completedTileCount"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"uint64_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@uint64_t"},{"text":" ","kind":"text"},{"text":"completedTileCount","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionStatus~1completedTileCount\/title","value":"completedTileCount"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionStatus~1completedTileCount\/fragments","value":[{"kind":"identifier","text":"completedTileCount"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionStatus\/title","op":"replace","value":"MBMOfflineRegionStatus"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionStatus\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMOfflineRegionStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionStatus\/navigatorTitle","value":[{"text":"MBMOfflineRegionStatus","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}