{"sections":[],"metadata":{"symbolKind":"protocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"AttributionURLOpener","kind":"identifier"}],"navigatorTitle":[{"text":"AttributionURLOpener","kind":"identifier"}],"title":"AttributionURLOpener","externalID":"s:10MapboxMaps20AttributionURLOpenerP","role":"symbol","modules":[{"name":"MapboxMaps"}],"roleHeading":"Protocol"},"kind":"symbol","seeAlsoSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapView","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapInitOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapInitOptionsProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ConstrainMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/NorthOrientation","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PresentationTransactionMode"],"generated":true,"anchor":"MapView","title":"MapView"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AttributionURLOpener","kind":"identifier"}],"platforms":["iOS"]}]},{"content":[{"text":"Overview","anchor":"overview","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"Use this protocol when the map view is used in non-application target(e.g. application extension target).","type":"text"}]}],"kind":"content"}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AttributionURLOpener","interfaceLanguage":"swift"},"topicSections":[{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AttributionURLOpener\/openAttributionURL(_:)"],"generated":true}],"variants":[{"paths":["\/documentation\/mapboxmaps\/attributionurlopener"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-View"]]},"abstract":[{"type":"text","text":"A protocol to open attribution URLs."}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ConstrainMode":{"title":"ConstrainMode","navigatorTitle":[{"text":"ConstrainMode","kind":"identifier"}],"abstract":[{"text":"Describes whether to constrain the map in both axes or only vertically e.g. while panning.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ConstrainMode","url":"\/documentation\/mapboxmaps\/constrainmode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConstrainMode"}],"kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"title":"MapboxMaps","kind":"symbol","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PresentationTransactionMode":{"title":"PresentationTransactionMode","navigatorTitle":[{"text":"PresentationTransactionMode","kind":"identifier"}],"abstract":[{"text":"Determines if the underlying ","type":"text"},{"type":"codeVoice","code":"CAMetalLayer"},{"type":"text","text":" rendering output should synchronize with the Core Animation transactions."}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PresentationTransactionMode","url":"\/documentation\/mapboxmaps\/presentationtransactionmode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PresentationTransactionMode","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapInitOptions":{"kind":"symbol","title":"MapInitOptions","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapInitOptions"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapInitOptions","navigatorTitle":[{"text":"MapInitOptions","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Options used when initializing "},{"code":"MapView","type":"codeVoice"},{"text":".","type":"text"}],"url":"\/documentation\/mapboxmaps\/mapinitoptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapOptions":{"title":"MapOptions","type":"topic","url":"\/documentation\/mapboxmaps\/mapoptions","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapOptions","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapOptions","navigatorTitle":[{"text":"MapOptions","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Describes the map option values."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapView":{"navigatorTitle":[{"text":"MapView","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MapView","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapView","abstract":[],"title":"MapView","url":"\/documentation\/mapboxmaps\/mapview","type":"topic","kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map-View":{"abstract":[],"title":"MapView","kind":"article","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-View","url":"\/documentation\/mapboxmaps\/map-view","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/NorthOrientation":{"type":"topic","title":"NorthOrientation","url":"\/documentation\/mapboxmaps\/northorientation","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NorthOrientation","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/NorthOrientation","navigatorTitle":[{"kind":"identifier","text":"NorthOrientation"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Describes the map orientation.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","url":"\/documentation\/overview","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AttributionURLOpener/openAttributionURL(_:)":{"title":"openAttributionURL(_:)","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AttributionURLOpener\/openAttributionURL(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"openAttributionURL","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Asks the opener to open the provided URL."}],"required":true,"type":"topic","url":"\/documentation\/mapboxmaps\/attributionurlopener\/openattributionurl(_:)","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GlyphsRasterizationOptions":{"type":"topic","title":"GlyphsRasterizationOptions","url":"\/documentation\/mapboxmaps\/glyphsrasterizationoptions","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GlyphsRasterizationOptions","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationOptions","navigatorTitle":[{"text":"GlyphsRasterizationOptions","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Describes the glyphs rasterization option values.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AttributionURLOpener":{"title":"AttributionURLOpener","navigatorTitle":[{"text":"AttributionURLOpener","kind":"identifier"}],"abstract":[{"text":"A protocol to open attribution URLs.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AttributionURLOpener","url":"\/documentation\/mapboxmaps\/attributionurlopener","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"AttributionURLOpener","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapInitOptionsProvider":{"type":"topic","title":"MapInitOptionsProvider","url":"\/documentation\/mapboxmaps\/mapinitoptionsprovider","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MapInitOptionsProvider","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapInitOptionsProvider","navigatorTitle":[{"text":"MapInitOptionsProvider","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"A protocol used to provide "},{"isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapInitOptions","type":"reference"},{"text":" when initializing a ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapView","type":"reference"},{"type":"text","text":" with a Storyboard or"},{"text":" ","type":"text"},{"type":"text","text":"a nib."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewportMode":{"title":"ViewportMode","navigatorTitle":[{"kind":"identifier","text":"ViewportMode"}],"abstract":[{"type":"text","text":"Satisfies embedding platforms that requires the viewport coordinate systems to be set according to its standards."}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewportMode","url":"\/documentation\/mapboxmaps\/viewportmode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ViewportMode","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GlyphsRasterizationMode":{"type":"topic","title":"GlyphsRasterizationMode","url":"\/documentation\/mapboxmaps\/glyphsrasterizationmode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GlyphsRasterizationMode","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode","navigatorTitle":[{"kind":"identifier","text":"GlyphsRasterizationMode"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Describes glyphs rasterization modes.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ConstrainMode\/title","op":"replace","value":"MBMConstrainMode"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ConstrainMode\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMConstrainMode"}]},{"op":"replace","value":[{"text":"MBMConstrainMode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ConstrainMode\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapOptions\/title","value":"MBMMapOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapOptions\/fragments","value":[{"kind":"identifier","text":"MBMMapOptions"}]},{"value":[{"text":"MBMMapOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapOptions\/navigatorTitle"},{"value":"MBMNorthOrientation","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1NorthOrientation\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1NorthOrientation\/fragments","value":[{"text":"MBMNorthOrientation","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1NorthOrientation\/navigatorTitle","value":[{"kind":"identifier","text":"MBMNorthOrientation"}]},{"value":"MBMGlyphsRasterizationOptions","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationOptions\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBMGlyphsRasterizationOptions"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationOptions\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationOptions\/navigatorTitle","value":[{"kind":"identifier","text":"MBMGlyphsRasterizationOptions"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewportMode\/title","value":"MBMViewportMode"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewportMode\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMViewportMode"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewportMode\/navigatorTitle","op":"replace","value":[{"text":"MBMViewportMode","kind":"identifier"}]},{"op":"replace","value":"MBMGlyphsRasterizationMode","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/title"},{"value":[{"text":"MBMGlyphsRasterizationMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/navigatorTitle","op":"replace","value":[{"text":"MBMGlyphsRasterizationMode","kind":"identifier"}]}]}]}