{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBoundsZoom"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs"]]},"topicSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBoundsZoom\/init(bounds:zoom:)"],"title":"Initializers","generated":true,"anchor":"Initializers"},{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBoundsZoom\/bounds","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBoundsZoom\/zoom"],"title":"Instance Properties"}],"metadata":{"symbolKind":"class","externalID":"c:objc(cs)MBMCoordinateBoundsZoom","title":"CoordinateBoundsZoom","roleHeading":"Class","navigatorTitle":[{"text":"CoordinateBoundsZoom","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CoordinateBoundsZoom"}],"modules":[{"name":"MapboxMaps"}],"role":"symbol"},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"abstract":[{"type":"text","text":"A coordinate bounds and zoom."}],"kind":"symbol","seeAlsoSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraState","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBounds","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBoundsOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Projection","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateInfo","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ContextMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapCenterAltitudeMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometry","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometryConvertible"],"anchor":"MapboxMap","title":"MapboxMap","generated":true}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CoordinateBoundsZoom","kind":"identifier"}],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/mapboxmaps\/coordinateboundszoom"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/coordinateboundszoom"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapCenterAltitudeMode":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapCenterAltitudeMode","title":"MapCenterAltitudeMode","navigatorTitle":[{"kind":"identifier","text":"MapCenterAltitudeMode"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"MapCenterAltitudeMode","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/mapcenteraltitudemode","abstract":[{"type":"text","text":"Defines how the map center point should react to terrain elevation changes."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderedQueryGeometry":{"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"A geometry to define a portion of screen that should be queried for rendered features."}],"url":"\/documentation\/mapboxmaps\/renderedquerygeometry","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RenderedQueryGeometry"}],"navigatorTitle":[{"kind":"identifier","text":"RenderedQueryGeometry"}],"type":"topic","title":"RenderedQueryGeometry","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometry"},"doc://com.mapbox.MapboxMaps/SQ":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"url":"\/documentation\/mapboxmaps\/mapboxmap-apis","abstract":[],"title":"MapboxMap","kind":"article","type":"topic","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraBoundsOptions":{"kind":"symbol","abstract":[{"type":"text","text":"Holds options to be used for setting camera bounds."}],"role":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/cameraboundsoptions","navigatorTitle":[{"kind":"identifier","text":"CameraBoundsOptions"}],"title":"CameraBoundsOptions","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CameraBoundsOptions"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBoundsOptions"},"doc://com.mapbox.MapboxMaps/objc(cs)NSObject":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraBounds":{"abstract":[{"type":"text","text":"Holds information about camera bounds."}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraBounds"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CameraBounds"}],"url":"\/documentation\/mapboxmaps\/camerabounds","title":"CameraBounds","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBounds"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateInfo":{"abstract":[{"type":"text","text":"Represents the coordinate information returned by the "},{"type":"codeVoice","code":"coordinateInfoForPixel"},{"type":"text","text":" or "},{"code":"coordinatesInfoForPixels","type":"codeVoice"},{"type":"text","text":" methods."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateInfo","kind":"symbol","role":"symbol","title":"CoordinateInfo","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CoordinateInfo"}],"url":"\/documentation\/mapboxmaps\/coordinateinfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"CoordinateInfo","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateBoundsZoom/zoom":{"role":"symbol","abstract":[{"text":"Zoom.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"zoom"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"zoom"}],"title":"zoom","url":"\/documentation\/mapboxmaps\/coordinateboundszoom\/zoom","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBoundsZoom\/zoom"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateBoundsZoom":{"kind":"symbol","abstract":[{"type":"text","text":"A coordinate bounds and zoom."}],"role":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/coordinateboundszoom","navigatorTitle":[{"kind":"identifier","text":"CoordinateBoundsZoom"}],"title":"CoordinateBoundsZoom","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"CoordinateBoundsZoom","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBoundsZoom"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateBounds":{"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"A rectangular area as measured on a two-dimensional map projection."}],"url":"\/documentation\/mapboxmaps\/coordinatebounds","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CoordinateBounds"}],"navigatorTitle":[{"kind":"identifier","text":"CoordinateBounds"}],"type":"topic","title":"CoordinateBounds","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateBoundsZoom/init(bounds:zoom:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bounds"},{"text":": ","kind":"text"},{"text":"CoordinateBounds","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMCoordinateBounds"},{"kind":"text","text":", "},{"kind":"externalParam","text":"zoom"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBoundsZoom\/init(bounds:zoom:)","kind":"symbol","title":"init(bounds:zoom:)","url":"\/documentation\/mapboxmaps\/coordinateboundszoom\/init(bounds:zoom:)","type":"topic","navigatorTitle":[{"text":"initWithBounds:zoom:","kind":"identifier"}]},"https://en.wikipedia.org/wiki/Web_Mercator_projection":{"title":"Spherical Mercator","titleInlineContent":[{"text":"Spherical Mercator","type":"text"}],"identifier":"https:\/\/en.wikipedia.org\/wiki\/Web_Mercator_projection","url":"https:\/\/en.wikipedia.org\/wiki\/Web_Mercator_projection","type":"link"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap":{"abstract":[{"text":"Provides access to the map model, including the camera, style, observable map events,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"and querying rendered features."}],"navigatorTitle":[{"text":"MapboxMap","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapboxMap"}],"title":"MapboxMap"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateBoundsZoom/bounds":{"role":"symbol","abstract":[{"text":"The latitude and longitude bounds.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bounds"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMCoordinateBounds","text":"CoordinateBounds","kind":"typeIdentifier"}],"type":"topic","navigatorTitle":[{"text":"bounds","kind":"identifier"}],"title":"bounds","url":"\/documentation\/mapboxmaps\/coordinateboundszoom\/bounds","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBoundsZoom\/bounds"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderedQueryGeometryConvertible":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometryConvertible","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RenderedQueryGeometryConvertible","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"RenderedQueryGeometryConvertible"}],"url":"\/documentation\/mapboxmaps\/renderedquerygeometryconvertible","kind":"symbol","title":"RenderedQueryGeometryConvertible","abstract":[{"type":"text","text":"A convenience protocol for automatic conversion to "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometry","isActive":true,"type":"reference"},{"text":".","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ContextMode":{"role":"symbol","kind":"symbol","abstract":[{"text":"Describes the map context mode.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"We can make some optimizations if we know that the drawing context is not shared with other code."}],"url":"\/documentation\/mapboxmaps\/contextmode","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ContextMode","kind":"identifier"}],"navigatorTitle":[{"text":"ContextMode","kind":"identifier"}],"type":"topic","title":"ContextMode","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ContextMode"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GlyphsRasterizationMode":{"type":"topic","title":"GlyphsRasterizationMode","url":"\/documentation\/mapboxmaps\/glyphsrasterizationmode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GlyphsRasterizationMode","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode","navigatorTitle":[{"kind":"identifier","text":"GlyphsRasterizationMode"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Describes glyphs rasterization modes.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","url":"\/documentation\/overview","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapError":{"role":"symbol","kind":"symbol","abstract":[{"text":"Type of errors thrown by the ","type":"text"},{"type":"codeVoice","code":"MapboxMap"},{"type":"text","text":" APIs."}],"url":"\/documentation\/mapboxmaps\/maperror","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"MapError","kind":"identifier"}],"navigatorTitle":[{"text":"MapError","kind":"identifier"}],"type":"topic","title":"MapError","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapError"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraOptions":{"role":"symbol","kind":"symbol","abstract":[],"url":"\/documentation\/mapboxmaps\/cameraoptions","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraOptions"}],"navigatorTitle":[{"text":"CameraOptions","kind":"identifier"}],"type":"topic","title":"CameraOptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraOptions"},"doc://com.mapbox.MapboxMaps/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.mapbox.MapboxMaps/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.mapbox.MapboxMaps/s7CVarArgP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.mapbox.MapboxMaps/objc(pl)NSObject":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Projection":{"role":"symbol","kind":"symbol","abstract":[{"text":"A collection of ","type":"text"},{"isActive":true,"type":"reference","identifier":"https:\/\/en.wikipedia.org\/wiki\/Web_Mercator_projection"},{"text":" projection methods.","type":"text"}],"url":"\/documentation\/mapboxmaps\/projection","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Projection","kind":"identifier"}],"navigatorTitle":[{"text":"Projection","kind":"identifier"}],"type":"topic","title":"Projection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Projection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"title":"MapboxMaps","kind":"symbol","role":"collection"},"doc://com.mapbox.MapboxMaps/SH":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraState":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraState","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraState"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CameraState"}],"url":"\/documentation\/mapboxmaps\/camerastate","kind":"symbol","title":"CameraState","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"MBMCoordinateBoundsZoom","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMCoordinateBoundsZoom"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"MBMCoordinateBoundsZoom","kind":"identifier"}]},{"op":"replace","value":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBoundsZoom\/bounds","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBoundsZoom\/zoom"],"anchor":"Instance-Properties"},{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBoundsZoom\/init(bounds:zoom:)"],"title":"Instance Methods"}],"path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"}],"op":"replace"},{"op":"replace","path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateInfo","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ContextMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapCenterAltitudeMode"],"title":"MapboxMap","generated":true,"anchor":"MapboxMap"}]},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBMCoordinateBoundsZoom"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"MBMMapCenterAltitudeMode","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapCenterAltitudeMode\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapCenterAltitudeMode\/fragments","value":[{"kind":"identifier","text":"MBMMapCenterAltitudeMode"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapCenterAltitudeMode\/navigatorTitle","value":[{"kind":"identifier","text":"MBMMapCenterAltitudeMode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateInfo\/title","value":"MBMCoordinateInfo"},{"value":[{"text":"MBMCoordinateInfo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateInfo\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateInfo\/navigatorTitle","value":[{"text":"MBMCoordinateInfo","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"zoom","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBoundsZoom~1zoom\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBoundsZoom~1zoom\/fragments","op":"replace","value":[{"kind":"identifier","text":"zoom"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBoundsZoom\/title","value":"MBMCoordinateBoundsZoom"},{"value":[{"text":"MBMCoordinateBoundsZoom","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBoundsZoom\/fragments","op":"replace"},{"value":[{"text":"MBMCoordinateBoundsZoom","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBoundsZoom\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds\/title","value":"MBMCoordinateBounds","op":"replace"},{"value":[{"text":"MBMCoordinateBounds","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds\/navigatorTitle","value":[{"text":"MBMCoordinateBounds","kind":"identifier"}]},{"value":"initWithBounds:zoom:","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBoundsZoom~1init(bounds:zoom:)\/title","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithBounds:zoom:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBoundsZoom~1init(bounds:zoom:)\/fragments"},{"value":"bounds","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBoundsZoom~1bounds\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBoundsZoom~1bounds\/fragments","value":[{"text":"bounds","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ContextMode\/title","value":"MBMContextMode"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ContextMode\/fragments","value":[{"kind":"identifier","text":"MBMContextMode"}],"op":"replace"},{"value":[{"kind":"identifier","text":"MBMContextMode"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ContextMode\/navigatorTitle"},{"value":"MBMGlyphsRasterizationMode","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/fragments","value":[{"text":"MBMGlyphsRasterizationMode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/navigatorTitle","value":[{"kind":"identifier","text":"MBMGlyphsRasterizationMode"}]}]}]}