{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"persistent","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceStorageType\/persistent"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Settings-and-Constants","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceStorageType"]]},"sections":[],"metadata":{"role":"symbol","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"MBXSettingsServiceStorageTypePersistent"}],"title":"SettingsServiceStorageType.persistent","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"persistent","kind":"identifier"}],"externalID":"c:@E@MBXSettingsServiceStorageType@MBXSettingsServiceStorageTypePersistent","modules":[{"name":"MapboxCommon"}],"symbolKind":"case"},"variants":[{"paths":["\/documentation\/mapboxcommon\/settingsservicestoragetype\/persistent"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/settingsservicestoragetype\/persistent"]}],"abstract":[{"text":"Persistent storage type means that all the settings key\/value pairs, that are set during application lifetime,","type":"text"},{"type":"text","text":" "},{"text":"will be available also after application gets terminated on the next run. On mobile platforms since we are","type":"text"},{"type":"text","text":" "},{"type":"text","text":"using system APIs all the settings will be also migrated to other user’s device with the same application"},{"text":" ","type":"text"},{"text":"install.","type":"text"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","title":"MapboxMaps","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsServiceStorageType":{"kind":"symbol","url":"\/documentation\/mapboxcommon\/settingsservicestoragetype","abstract":[{"type":"text","text":"Enum that contains possible storage types that can be used for settings service."}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SettingsServiceStorageType","kind":"identifier"}],"title":"SettingsServiceStorageType","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceStorageType","navigatorTitle":[{"kind":"identifier","text":"SettingsServiceStorageType"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article","role":"collection","type":"topic","abstract":[],"url":"\/documentation\/overview","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Settings-and-Constants":{"kind":"article","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/settings-and-constants","title":"Settings and Constants","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Settings-and-Constants","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsServiceStorageType/persistent":{"role":"symbol","type":"topic","navigatorTitle":[{"text":"MBXSettingsServiceStorageTypePersistent","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/settingsservicestoragetype\/persistent","abstract":[{"text":"Persistent storage type means that all the settings key\/value pairs, that are set during application lifetime,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"will be available also after application gets terminated on the next run. On mobile platforms since we are"},{"type":"text","text":" "},{"text":"using system APIs all the settings will be also migrated to other user’s device with the same application","type":"text"},{"type":"text","text":" "},{"text":"install.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceStorageType\/persistent","title":"SettingsServiceStorageType.persistent","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"persistent","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"MBXSettingsServiceStorageTypePersistent","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"MBXSettingsServiceStorageTypePersistent","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"MBXSettingsServiceStorageTypePersistent","kind":"identifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceStorageType\/title","value":"MBXSettingsServiceStorageType"},{"value":[{"text":"MBXSettingsServiceStorageType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceStorageType\/fragments","op":"replace"},{"op":"replace","value":[{"text":"MBXSettingsServiceStorageType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceStorageType\/navigatorTitle"},{"op":"replace","value":"MBXSettingsServiceStorageTypePersistent","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceStorageType~1persistent\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceStorageType~1persistent\/fragments","value":[{"text":"MBXSettingsServiceStorageTypePersistent","kind":"identifier"}]}]}]}