{"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","modules":[{"name":"MapboxMaps"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"init","title":"init(rawValue:)","roleHeading":"Initializer","externalID":"s:So22MBMTileCacheBudgetTypeV8rawValueABSgSi_tcfc"},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetType\/init(rawValue:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetType"]]},"variants":[{"paths":["\/documentation\/mapboxmaps\/tilecachebudgettype\/init(rawvalue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","url":"\/documentation\/mapboxmaps","title":"MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudgetType":{"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileCacheBudgetType","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"TileCacheBudgetType","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/tilecachebudgettype","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetType","kind":"symbol","role":"symbol","title":"TileCacheBudgetType"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudgetType/init(rawValue:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetType\/init(rawValue:)","url":"\/documentation\/mapboxmaps\/tilecachebudgettype\/init(rawvalue:)","type":"topic","kind":"symbol","role":"symbol","title":"init(rawValue:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","url":"\/documentation\/overview","kind":"article","type":"topic","role":"collection","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"kind":"article","role":"collectionGroup","type":"topic","abstract":[],"url":"\/documentation\/mapboxmaps\/tilestore-apis","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","title":"TileStore APIs"}},"variantOverrides":[{"patch":[{"op":"replace","value":"MBMTileCacheBudgetType","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBMTileCacheBudgetType"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetType\/fragments"},{"op":"replace","value":[{"text":"MBMTileCacheBudgetType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}