{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetType"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/tilecachebudgettype\/tilecachebudgetintiles"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/tilecachebudgettype\/tilecachebudgetintiles"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tileCacheBudgetInTiles","kind":"identifier"}],"platforms":["iOS"]}]}],"sections":[],"kind":"symbol","metadata":{"role":"symbol","externalID":"c:@E@MBMTileCacheBudgetType@MBMTileCacheBudgetTypeTileCacheBudgetInTiles","modules":[{"name":"MapboxMaps"}],"symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tileCacheBudgetInTiles"}],"roleHeading":"Case","title":"TileCacheBudgetType.tileCacheBudgetInTiles","navigatorTitle":[{"text":"MBMTileCacheBudgetTypeTileCacheBudgetInTiles","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetType\/tileCacheBudgetInTiles"},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"role":"collectionGroup","url":"\/documentation\/mapboxmaps\/tilestore-apis","kind":"article","title":"TileStore APIs","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"role":"collection","kind":"symbol","url":"\/documentation\/mapboxmaps","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudgetType/tileCacheBudgetInTiles":{"navigatorTitle":[{"kind":"identifier","text":"MBMTileCacheBudgetTypeTileCacheBudgetInTiles"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetType\/tileCacheBudgetInTiles","title":"TileCacheBudgetType.tileCacheBudgetInTiles","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tileCacheBudgetInTiles"}],"type":"topic","url":"\/documentation\/mapboxmaps\/tilecachebudgettype\/tilecachebudgetintiles","kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","kind":"article","title":"MapboxMaps Documentation","url":"\/documentation\/overview","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudgetType":{"role":"symbol","navigatorTitle":[{"text":"TileCacheBudgetType","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/tilecachebudgettype","kind":"symbol","title":"TileCacheBudgetType","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetType","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileCacheBudgetType","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"MBMTileCacheBudgetTypeTileCacheBudgetInTiles","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"MBMTileCacheBudgetTypeTileCacheBudgetInTiles"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"MBMTileCacheBudgetTypeTileCacheBudgetInTiles","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MBMTileCacheBudgetTypeTileCacheBudgetInTiles","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetType~1tileCacheBudgetInTiles\/title"},{"value":[{"text":"MBMTileCacheBudgetTypeTileCacheBudgetInTiles","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetType~1tileCacheBudgetInTiles\/fragments"},{"value":"MBMTileCacheBudgetType","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetType\/title","op":"replace"},{"value":[{"text":"MBMTileCacheBudgetType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetType\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MBMTileCacheBudgetType"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetType\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}