{"metadata":{"symbolKind":"method","title":"setFileRotateCountForRotateCount(_:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setFileRotateCountForRotateCount","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UInt64","preciseIdentifier":"s:s6UInt64V","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"setFileRotateCountForRotateCount:","kind":"identifier"}],"role":"symbol","externalID":"c:objc(cs)MBXPersistentLogConfiguration(cm)setFileRotateCountForRotateCount:","modules":[{"name":"MapboxCommon"}],"roleHeading":"Type Method"},"abstract":[{"text":"Set file rotation count.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/setFileRotateCountForRotateCount(_:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setFileRotateCountForRotateCount"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"rotateCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt64","preciseIdentifier":"s:s6UInt64V"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The amount of files to rotate through.","type":"text"},{"text":" ","type":"text"},{"text":"Note: each file will have a max size set by setFileMaxSize","type":"text"},{"text":" ","type":"text"},{"text":"Default is 2","type":"text"}]}],"name":"rotateCount"}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/persistentlogconfiguration\/setfilerotatecountforrotatecount(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/persistentlogconfiguration\/setfilerotatecountforrotatecount(_:)"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration"]]},"kind":"symbol","references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PersistentLogConfiguration":{"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PersistentLogConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"PersistentLogConfiguration"}],"kind":"symbol","type":"topic","url":"\/documentation\/mapboxcommon\/persistentlogconfiguration","title":"PersistentLogConfiguration"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","title":"MapboxCommon","url":"\/documentation\/mapboxcommon","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","abstract":[],"url":"\/documentation\/overview","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PersistentLogConfiguration/setFileRotateCountForRotateCount(_:)":{"title":"setFileRotateCountForRotateCount(_:)","url":"\/documentation\/mapboxcommon\/persistentlogconfiguration\/setfilerotatecountforrotatecount(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setFileRotateCountForRotateCount"},{"kind":"text","text":"("},{"preciseIdentifier":"s:s6UInt64V","kind":"typeIdentifier","text":"UInt64"},{"kind":"text","text":")"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/setFileRotateCountForRotateCount(_:)","abstract":[{"text":"Set file rotation count.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"setFileRotateCountForRotateCount:"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"setFileRotateCountForRotateCount:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"+ ","kind":"text"},{"text":"setFileRotateCountForRotateCount:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"setFileRotateCountForRotateCount:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"uint64_t","preciseIdentifier":"c:@T@uint64_t","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"rotateCount","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The amount of files to rotate through.","type":"text"},{"text":" ","type":"text"},{"text":"Note: each file will have a max size set by setFileMaxSize","type":"text"},{"text":" ","type":"text"},{"text":"Default is 2","type":"text"}],"type":"paragraph"}],"name":"rotateCount"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"MBXPersistentLogConfiguration","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration\/title"},{"value":[{"kind":"identifier","text":"MBXPersistentLogConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"MBXPersistentLogConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration\/navigatorTitle"},{"value":"setFileRotateCountForRotateCount:","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1setFileRotateCountForRotateCount(_:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"setFileRotateCountForRotateCount:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1setFileRotateCountForRotateCount(_:)\/fragments"}]}]}