{"abstract":[{"text":"Convert a model matrix to be usable with the currently active projection.","type":"text"},{"text":" ","type":"text"},{"text":"The input matrix is expected to transform coordinates from a local coordinate space","type":"text"},{"text":" ","type":"text"},{"text":"into web mercator coordinate space where x & y axes are defined in pixels and z in meters.","type":"text"},{"text":" ","type":"text"},{"text":"The output matrix will transform local coordinates and align them correctly","type":"text"},{"text":" ","type":"text"},{"text":"on the world coordinate space.","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerMapProjection\/convertMercatorModelMatrix(forMatrix:ignoreDistortion:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerMapProjection"]]},"variants":[{"paths":["\/documentation\/mapboxmaps\/customlayermapprojection\/convertmercatormodelmatrix(formatrix:ignoredistortion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/customlayermapprojection\/convertmercatormodelmatrix(formatrix:ignoredistortion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"convertMercatorModelMatrix"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forMatrix"},{"kind":"text","text":" "},{"kind":"internalParam","text":"matrix"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"ignoreDistortion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"]?"}]}]},{"parameters":[{"name":"matrix","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Model matrix for rendering primitives on web mercator projection"}]}]},{"name":"ignoreDistortion","content":[{"inlineContent":[{"text":"Determine whether the output matrix should keep metric size of the model fixed or not.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"Model matrix for rendering primitives on the active projection. Size of the input matrix needs to be 16 or no value is returned.","type":"text"}]}],"kind":"content"}],"metadata":{"externalID":"c:objc(pl)MBMCustomLayerMapProjection(im)convertMercatorModelMatrixForMatrix:ignoreDistortion:","required":true,"title":"convertMercatorModelMatrix(forMatrix:ignoreDistortion:)","role":"symbol","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"convertMercatorModelMatrix"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forMatrix"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"ignoreDistortion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"]?"}],"navigatorTitle":[{"text":"convertMercatorModelMatrixForMatrix:ignoreDistortion:","kind":"identifier"}],"modules":[{"name":"MapboxMaps"}],"roleHeading":"Instance Method"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layers":{"type":"topic","url":"\/documentation\/mapboxmaps\/layers","kind":"article","title":"Layers","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerMapProjection":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerMapProjection","title":"CustomLayerMapProjection","url":"\/documentation\/mapboxmaps\/customlayermapprojection","kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomLayerMapProjection","kind":"identifier"}],"navigatorTitle":[{"text":"CustomLayerMapProjection","kind":"identifier"}],"abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","url":"\/documentation\/mapboxmaps","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","role":"collection","title":"MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerMapProjection/convertMercatorModelMatrix(forMatrix:ignoreDistortion:)":{"url":"\/documentation\/mapboxmaps\/customlayermapprojection\/convertmercatormodelmatrix(formatrix:ignoredistortion:)","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"convertMercatorModelMatrix"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forMatrix"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"ignoreDistortion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"]?"}],"navigatorTitle":[{"text":"convertMercatorModelMatrixForMatrix:ignoreDistortion:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerMapProjection\/convertMercatorModelMatrix(forMatrix:ignoreDistortion:)","type":"topic","abstract":[{"type":"text","text":"Convert a model matrix to be usable with the currently active projection."},{"type":"text","text":" "},{"type":"text","text":"The input matrix is expected to transform coordinates from a local coordinate space"},{"type":"text","text":" "},{"type":"text","text":"into web mercator coordinate space where x & y axes are defined in pixels and z in meters."},{"type":"text","text":" "},{"type":"text","text":"The output matrix will transform local coordinates and align them correctly"},{"type":"text","text":" "},{"type":"text","text":"on the world coordinate space."}],"title":"convertMercatorModelMatrix(forMatrix:ignoreDistortion:)"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","url":"\/documentation\/overview","kind":"article","abstract":[],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"convertMercatorModelMatrixForMatrix:ignoreDistortion:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"convertMercatorModelMatrixForMatrix:ignoreDistortion:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"NSArray<NSNumber *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"convertMercatorModelMatrixForMatrix:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<NSNumber *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"matrix","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"ignoreDistortion:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"ignoreDistortion","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Model matrix for rendering primitives on web mercator projection"}],"type":"paragraph"}],"name":"matrix"},{"content":[{"inlineContent":[{"type":"text","text":"Determine whether the output matrix should keep metric size of the model fixed or not."}],"type":"paragraph"}],"name":"ignoreDistortion"}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"op":"replace","value":{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"inlineContent":[{"type":"text","text":"Model matrix for rendering primitives on the active projection. Size of the input matrix needs to be 16 or no value is returned."}],"type":"paragraph"}]},"path":"\/primaryContentSections\/2"},{"op":"replace","value":"MBMCustomLayerMapProjection","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerMapProjection\/title"},{"op":"replace","value":[{"text":"MBMCustomLayerMapProjection","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerMapProjection\/fragments"},{"op":"replace","value":[{"text":"MBMCustomLayerMapProjection","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerMapProjection\/navigatorTitle"},{"op":"replace","value":"convertMercatorModelMatrixForMatrix:ignoreDistortion:","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerMapProjection~1convertMercatorModelMatrix(forMatrix:ignoreDistortion:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"convertMercatorModelMatrixForMatrix:ignoreDistortion:"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerMapProjection~1convertMercatorModelMatrix(forMatrix:ignoreDistortion:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}