{"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isEqual","kind":"identifier"},{"kind":"text","text":"("},{"text":"to","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"other","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MercatorCoordinate","text":"MercatorCoordinate","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMMercatorCoordinate"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"kind":"text","text":"("},{"text":"to","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MercatorCoordinate","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMMercatorCoordinate"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"modules":[{"name":"MapboxMaps"}],"symbolKind":"method","title":"isEqual(to:)","externalID":"c:objc(cs)MBMMercatorCoordinate(im)isEqualToMercatorCoordinate:","navigatorTitle":[{"kind":"identifier","text":"isEqualToMercatorCoordinate:"}],"role":"symbol","roleHeading":"Instance Method"},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MercatorCoordinate\/isEqual(to:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Camera-and-coordinates","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MercatorCoordinate"],["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Camera-and-coordinates","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MercatorCoordinate"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/mercatorcoordinate\/isequal(to:)"]},{"paths":["\/documentation\/mapboxmaps\/mercatorcoordinate\/isequal(to:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"role":"collection","url":"\/documentation\/mapboxmaps","title":"MapboxMaps","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Camera-and-coordinates":{"title":"Camera and coordinates","kind":"article","role":"collectionGroup","type":"topic","url":"\/documentation\/mapboxmaps\/camera-and-coordinates","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Camera-and-coordinates","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","kind":"article","url":"\/documentation\/mapboxmaps\/mapboxmap-apis","title":"MapboxMap","type":"topic","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MercatorCoordinate":{"abstract":[{"type":"text","text":"Describes a point on the map in Mercator projection."}],"role":"symbol","kind":"symbol","title":"MercatorCoordinate","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MercatorCoordinate","navigatorTitle":[{"kind":"identifier","text":"MercatorCoordinate"}],"type":"topic","url":"\/documentation\/mapboxmaps\/mercatorcoordinate","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MercatorCoordinate"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","kind":"article","abstract":[],"url":"\/documentation\/overview","type":"topic","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MercatorCoordinate/isEqual(to:)":{"url":"\/documentation\/mapboxmaps\/mercatorcoordinate\/isequal(to:)","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MercatorCoordinate\/isEqual(to:)","title":"isEqual(to:)","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"isEqualToMercatorCoordinate:"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"text":"to","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MercatorCoordinate","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMMercatorCoordinate"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"isEqualToMercatorCoordinate:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqualToMercatorCoordinate:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isEqualToMercatorCoordinate:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MercatorCoordinate","preciseIdentifier":"c:objc(cs)MBMMercatorCoordinate","text":"MBMMercatorCoordinate","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"other"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MercatorCoordinate\/title","value":"MBMMercatorCoordinate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MercatorCoordinate\/fragments","value":[{"text":"MBMMercatorCoordinate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MercatorCoordinate\/navigatorTitle","op":"replace","value":[{"text":"MBMMercatorCoordinate","kind":"identifier"}]},{"op":"replace","value":"isEqualToMercatorCoordinate:","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MercatorCoordinate~1isEqual(to:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"isEqualToMercatorCoordinate:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MercatorCoordinate~1isEqual(to:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}