{"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter"]]},"kind":"symbol","abstract":[{"type":"text","text":"A style has a missing image. This event is emitted when the map renders visible tiles and"},{"type":"text","text":" "},{"type":"text","text":"one of the required images is missing in the sprite sheet. Subscriber has to provide the missing image"},{"type":"text","text":" "},{"type":"text","text":"by calling "},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addImage(_:id:sdf:contentInsets:)","isActive":true},{"type":"text","text":"."}],"metadata":{"symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"MapboxMaps"}],"extendedModule":"MapboxMaps","title":"onStyleImageMissing","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onStyleImageMissing","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps6SignalV","text":"Signal","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMStyleImageMissing","text":"StyleImageMissing","kind":"typeIdentifier"},{"text":">","kind":"text"}],"role":"symbol","externalID":"s:10MapboxMaps11SnapshotterC19onStyleImageMissingAA6SignalVySo08MBMStylefG0CGvp"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onStyleImageMissing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Signal","preciseIdentifier":"s:10MapboxMaps6SignalV","text":"Signal"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageMissing","preciseIdentifier":"c:objc(cs)MBMStyleImageMissing","text":"StyleImageMissing"},{"kind":"text","text":"> { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter\/onStyleImageMissing"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/snapshotter\/onstyleimagemissing"]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","url":"\/documentation\/overview","kind":"article","abstract":[],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/addImage(_:id:sdf:contentInsets:)":{"kind":"symbol","title":"addImage(_:id:sdf:contentInsets:)","abstract":[{"type":"text","text":"Adds an image to be used in the style."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addImage(_:id:sdf:contentInsets:)","url":"\/documentation\/mapboxmaps\/stylemanager\/addimage(_:id:sdf:contentinsets:)","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addImage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sdf"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"contentInsets"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIEdgeInsets","preciseIdentifier":"c:@S@UIEdgeInsets"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Snapshotter-APIs":{"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter-APIs","role":"collectionGroup","type":"topic","abstract":[],"title":"Snapshotter","url":"\/documentation\/mapboxmaps\/snapshotter-apis"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","url":"\/documentation\/mapboxmaps","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","role":"collection","title":"MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleImageMissing":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleImageMissing","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StyleImageMissing"}],"title":"StyleImageMissing","navigatorTitle":[{"kind":"identifier","text":"StyleImageMissing"}],"url":"\/documentation\/mapboxmaps\/styleimagemissing","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A style needs an image that is missing from the sprite sheet. This event is"},{"type":"text","text":" "},{"type":"text","text":"emitted when the "},{"type":"codeVoice","code":"map"},{"type":"text","text":" renders visible tiles, and one of the required images"},{"type":"text","text":" "},{"type":"text","text":"is missing in the sprite sheet. The event observer has to provide the missing"},{"type":"text","text":" "},{"type":"text","text":"image by calling the "},{"type":"codeVoice","code":"addStyleImage"},{"type":"text","text":" method."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Snapshotter/onStyleImageMissing":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter\/onStyleImageMissing","type":"topic","role":"symbol","abstract":[{"text":"A style has a missing image. This event is emitted when the map renders visible tiles and","type":"text"},{"text":" ","type":"text"},{"text":"one of the required images is missing in the sprite sheet. Subscriber has to provide the missing image","type":"text"},{"text":" ","type":"text"},{"text":"by calling ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addImage(_:id:sdf:contentInsets:)"},{"text":".","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onStyleImageMissing","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps6SignalV","text":"Signal","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMStyleImageMissing","text":"StyleImageMissing","kind":"typeIdentifier"},{"text":">","kind":"text"}],"url":"\/documentation\/mapboxmaps\/snapshotter\/onstyleimagemissing","title":"onStyleImageMissing","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Snapshotter":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Snapshotter"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Snapshotter"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter","url":"\/documentation\/mapboxmaps\/snapshotter","title":"Snapshotter","abstract":[{"text":"A utility class for capturing styled map snapshots.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Signal":{"title":"Signal","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Signal"}],"url":"\/documentation\/mapboxmaps\/signal","abstract":[{"type":"text","text":"Signal is a typed interface for observing arbitrary values over time."}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Signal","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Signal"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageMissing\/title","op":"replace","value":"MBMStyleImageMissing"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageMissing\/fragments","op":"replace","value":[{"text":"MBMStyleImageMissing","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StyleImageMissing\/navigatorTitle","op":"replace","value":[{"text":"MBMStyleImageMissing","kind":"identifier"}]}]}]}