{"metadata":{"title":"HttpRequestErrorType.connectionError","symbolKind":"case","externalID":"c:@E@MBXHttpRequestErrorType@MBXHttpRequestErrorTypeConnectionError","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connectionError","kind":"identifier"}],"navigatorTitle":[{"text":"MBXHttpRequestErrorTypeConnectionError","kind":"identifier"}],"role":"symbol","roleHeading":"Case","modules":[{"name":"MapboxCommon"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType\/connectionError"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connectionError","kind":"identifier"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/httprequesterrortype\/connectionerror"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/httprequesterrortype\/connectionerror"]}],"abstract":[{"type":"text","text":"Establishing connection related error."}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestErrorType/connectionError":{"title":"HttpRequestErrorType.connectionError","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType\/connectionError","abstract":[{"type":"text","text":"Establishing connection related error."}],"kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connectionError","kind":"identifier"}],"navigatorTitle":[{"text":"MBXHttpRequestErrorTypeConnectionError","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxcommon\/httprequesterrortype\/connectionerror"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"url":"\/documentation\/mapboxcommon","role":"collection","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","title":"MapboxCommon","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","type":"topic","abstract":[],"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestErrorType":{"url":"\/documentation\/mapboxcommon\/httprequesterrortype","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Enum which describes possible error types which could happen during HTTP request\/download calls."}],"navigatorTitle":[{"text":"HttpRequestErrorType","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HttpRequestErrorType","kind":"identifier"}],"title":"HttpRequestErrorType","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"MBXHttpRequestErrorTypeConnectionError","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"MBXHttpRequestErrorTypeConnectionError","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"MBXHttpRequestErrorTypeConnectionError","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"MBXHttpRequestErrorTypeConnectionError","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestErrorType~1connectionError\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBXHttpRequestErrorTypeConnectionError"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestErrorType~1connectionError\/fragments"},{"op":"replace","value":"MBXHttpRequestErrorType","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestErrorType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBXHttpRequestErrorType"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestErrorType\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MBXHttpRequestErrorType"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestErrorType\/navigatorTitle"}]}]}