{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/httprequesterrortype\/othererror"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/httprequesterrortype\/othererror"]}],"kind":"symbol","abstract":[{"text":"Other than above error.","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"otherError"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"metadata":{"title":"HttpRequestErrorType.otherError","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"otherError","kind":"identifier"}],"symbolKind":"case","externalID":"c:@E@MBXHttpRequestErrorType@MBXHttpRequestErrorTypeOtherError","role":"symbol","modules":[{"name":"MapboxCommon"}],"navigatorTitle":[{"text":"MBXHttpRequestErrorTypeOtherError","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType\/otherError"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestErrorType/otherError":{"title":"HttpRequestErrorType.otherError","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType\/otherError","url":"\/documentation\/mapboxcommon\/httprequesterrortype\/othererror","abstract":[{"text":"Other than above error.","type":"text"}],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"otherError","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"MBXHttpRequestErrorTypeOtherError","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","type":"topic","abstract":[],"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestErrorType":{"url":"\/documentation\/mapboxcommon\/httprequesterrortype","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Enum which describes possible error types which could happen during HTTP request\/download calls."}],"navigatorTitle":[{"text":"HttpRequestErrorType","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HttpRequestErrorType","kind":"identifier"}],"title":"HttpRequestErrorType","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"url":"\/documentation\/mapboxcommon","role":"collection","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","title":"MapboxCommon","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MBXHttpRequestErrorTypeOtherError"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MBXHttpRequestErrorTypeOtherError","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"MBXHttpRequestErrorTypeOtherError"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestErrorType~1otherError\/title","value":"MBXHttpRequestErrorTypeOtherError"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestErrorType~1otherError\/fragments","value":[{"text":"MBXHttpRequestErrorTypeOtherError","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestErrorType\/title","value":"MBXHttpRequestErrorType"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestErrorType\/fragments","value":[{"kind":"identifier","text":"MBXHttpRequestErrorType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestErrorType\/navigatorTitle","value":[{"kind":"identifier","text":"MBXHttpRequestErrorType"}]}]}]}