{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TilesetDescriptorOptions"]]},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TilesetDescriptorOptions\/maxZoom","interfaceLanguage":"swift"},"sections":[],"abstract":[{"text":"Maximum zoom level for the tile package.","type":"text"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxZoom","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt8","preciseIdentifier":"s:s5UInt8V"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"maxZoom value cannot exceed the maximum allowed tile batch zoom value,","type":"text"}]}]}],"metadata":{"roleHeading":"Instance Property","externalID":"c:objc(cs)MBMTilesetDescriptorOptions(py)maxZoom","role":"symbol","modules":[{"name":"MapboxMaps"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"maxZoom"}],"title":"maxZoom","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maxZoom"},{"text":": ","kind":"text"},{"text":"UInt8","kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V"}]},"variants":[{"paths":["\/documentation\/mapboxmaps\/tilesetdescriptoroptions\/maxzoom"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/tilesetdescriptoroptions\/maxzoom"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TilesetDescriptorOptions/maxZoom":{"type":"topic","abstract":[{"type":"text","text":"Maximum zoom level for the tile package."}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TilesetDescriptorOptions\/maxZoom","url":"\/documentation\/mapboxmaps\/tilesetdescriptoroptions\/maxzoom","kind":"symbol","navigatorTitle":[{"text":"maxZoom","kind":"identifier"}],"title":"maxZoom","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxZoom","kind":"identifier"},{"kind":"text","text":": "},{"text":"UInt8","kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","kind":"article","url":"\/documentation\/mapboxmaps\/tilestore-apis","title":"TileStore APIs","role":"collectionGroup","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TilesetDescriptorOptions":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TilesetDescriptorOptions","navigatorTitle":[{"text":"TilesetDescriptorOptions","kind":"identifier"}],"abstract":[{"text":"Describes the tileset descriptor option values.","type":"text"}],"title":"TilesetDescriptorOptions","type":"topic","url":"\/documentation\/mapboxmaps\/tilesetdescriptoroptions","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TilesetDescriptorOptions"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","title":"MapboxMaps Documentation","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","role":"collection","url":"\/documentation\/mapboxmaps","kind":"symbol","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"maxZoom","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"maxZoom","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"uint8_t","preciseIdentifier":"c:@T@uint8_t"},{"text":" ","kind":"text"},{"text":"maxZoom","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"value":"maxZoom","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions~1maxZoom\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions~1maxZoom\/fragments","value":[{"text":"maxZoom","kind":"identifier"}]},{"op":"replace","value":"MBMTilesetDescriptorOptions","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions\/fragments","value":[{"kind":"identifier","text":"MBMTilesetDescriptorOptions"}],"op":"replace"},{"value":[{"kind":"identifier","text":"MBMTilesetDescriptorOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions\/navigatorTitle"}]}]}