{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GetLocationCallback"},"abstract":[{"type":"text","text":"Callback involved to get the location."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"GetLocationCallback"},{"kind":"text","text":" = ("},{"kind":"typeIdentifier","text":"Location","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location","preciseIdentifier":"c:objc(cs)MBXLocation"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"name":"location","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A single location update."}]}]}],"kind":"parameters"}],"kind":"symbol","metadata":{"title":"GetLocationCallback","externalID":"c:MBXGetLocationCallback.h@T@MBXGetLocationCallback","symbolKind":"typealias","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GetLocationCallback","kind":"identifier"}],"navigatorTitle":[{"text":"GetLocationCallback","kind":"identifier"}],"role":"symbol","modules":[{"name":"MapboxCommon"}],"roleHeading":"Type Alias"},"variants":[{"paths":["\/documentation\/mapboxcommon\/getlocationcallback"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxcommon\/getlocationcallback"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","type":"topic","abstract":[],"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"url":"\/documentation\/mapboxcommon","role":"collection","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","title":"MapboxCommon","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Location":{"navigatorTitle":[{"text":"Location","kind":"identifier"}],"type":"topic","title":"Location","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location","url":"\/documentation\/mapboxcommon\/location","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Location","kind":"identifier"}],"abstract":[{"type":"text","text":"Location information."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/GetLocationCallback":{"url":"\/documentation\/mapboxcommon\/getlocationcallback","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GetLocationCallback","navigatorTitle":[{"text":"GetLocationCallback","kind":"identifier"}],"abstract":[{"type":"text","text":"Callback involved to get the location."}],"role":"symbol","type":"topic","title":"GetLocationCallback","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GetLocationCallback","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Alias","op":"replace"},{"path":"\/metadata\/title","value":"MBXGetLocationCallback","op":"replace"},{"path":"\/metadata\/symbolKind","value":"typealias","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"MBXGetLocationCallback","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"MBXGetLocationCallback","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:BFv(#*$objc(cs)MBXLocation)","text":"void (^)(MBXLocation *)","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"MBXGetLocationCallback","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/title","value":"MBXLocation","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/fragments","value":[{"kind":"identifier","text":"MBXLocation"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/navigatorTitle","value":[{"kind":"identifier","text":"MBXLocation"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GetLocationCallback\/title","value":"MBXGetLocationCallback","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GetLocationCallback\/fragments","value":[{"kind":"identifier","text":"MBXGetLocationCallback"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GetLocationCallback\/navigatorTitle","value":[{"kind":"identifier","text":"MBXGetLocationCallback"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}