{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraState"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraState"}],"platforms":["iOS"]}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/camerastate"]}],"topicSections":[{"title":"Initializers","anchor":"Initializers","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraState\/init(center:padding:zoom:bearing:pitch:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraState\/init(from:)"]},{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraState\/bearing","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraState\/center","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraState\/padding","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraState\/pitch","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraState\/zoom"]},{"title":"Default Implementations","anchor":"Default-Implementations","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraState\/Equatable-Implementations"]}],"metadata":{"symbolKind":"struct","role":"symbol","modules":[{"name":"MapboxMaps"}],"roleHeading":"Structure","navigatorTitle":[{"text":"CameraState","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraState","kind":"identifier"}],"title":"CameraState","externalID":"s:10MapboxMaps11CameraStateV"},"seeAlsoSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBounds","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBoundsOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Projection","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBoundsZoom","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateInfo","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ContextMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapCenterAltitudeMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometry","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometryConvertible"],"anchor":"MapboxMap","generated":true,"title":"MapboxMap"}],"relationshipsSections":[{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/Se","doc:\/\/com.mapbox.MapboxMaps\/SE","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH","doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"],"title":"Conforms To"}],"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ContextMode":{"url":"\/documentation\/mapboxmaps\/contextmode","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ContextMode","role":"symbol","abstract":[{"text":"Describes the map context mode.","type":"text"},{"text":" ","type":"text"},{"text":"We can make some optimizations if we know that the drawing context is not shared with other code.","type":"text"}],"type":"topic","kind":"symbol","title":"ContextMode","navigatorTitle":[{"text":"ContextMode","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContextMode","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"title":"MapboxMap","type":"topic","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","abstract":[],"url":"\/documentation\/mapboxmaps\/mapboxmap-apis","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GlyphsRasterizationMode":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GlyphsRasterizationMode"}],"url":"\/documentation\/mapboxmaps\/glyphsrasterizationmode","abstract":[{"text":"Describes glyphs rasterization modes.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"GlyphsRasterizationMode"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode","type":"topic","title":"GlyphsRasterizationMode"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraState":{"abstract":[],"type":"topic","kind":"symbol","title":"CameraState","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraState","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraState","url":"\/documentation\/mapboxmaps\/camerastate","navigatorTitle":[{"text":"CameraState","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","url":"\/documentation\/overview","role":"collection","abstract":[],"kind":"article"},"doc://com.mapbox.MapboxMaps/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","title":"Swift.Equatable"},"https://en.wikipedia.org/wiki/Web_Mercator_projection":{"type":"link","identifier":"https:\/\/en.wikipedia.org\/wiki\/Web_Mercator_projection","title":"Spherical Mercator","titleInlineContent":[{"type":"text","text":"Spherical Mercator"}],"url":"https:\/\/en.wikipedia.org\/wiki\/Web_Mercator_projection"},"doc://com.mapbox.MapboxMaps/SE":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SE","title":"Swift.Encodable"},"doc://com.mapbox.MapboxMaps/Se":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/Se","title":"Swift.Decodable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraState/zoom":{"role":"symbol","kind":"symbol","title":"zoom","abstract":[{"text":"The zoom level of the map.","type":"text"}],"type":"topic","url":"\/documentation\/mapboxmaps\/camerastate\/zoom","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"zoom","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraState\/zoom"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap":{"navigatorTitle":[{"text":"MapboxMap","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Provides access to the map model, including the camera, style, observable map events,"},{"type":"text","text":" "},{"type":"text","text":"and querying rendered features."}],"title":"MapboxMap","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapboxMap","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraState/Equatable-Implementations":{"type":"topic","abstract":[],"url":"\/documentation\/mapboxmaps\/camerastate\/equatable-implementations","kind":"article","role":"collectionGroup","title":"Equatable Implementations","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraState\/Equatable-Implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraState/init(center:padding:zoom:bearing:pitch:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"center","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"text":", ","kind":"text"},{"text":"padding","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIEdgeInsets","kind":"typeIdentifier","preciseIdentifier":"c:@S@UIEdgeInsets"},{"text":", ","kind":"text"},{"text":"zoom","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bearing"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@CLLocationDirection","kind":"typeIdentifier","text":"CLLocationDirection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pitch"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"kind":"text","text":")"}],"url":"\/documentation\/mapboxmaps\/camerastate\/init(center:padding:zoom:bearing:pitch:)","abstract":[],"role":"symbol","kind":"symbol","title":"init(center:padding:zoom:bearing:pitch:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraState\/init(center:padding:zoom:bearing:pitch:)","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraOptions":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"CameraOptions","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/cameraoptions","type":"topic","title":"CameraOptions","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraOptions","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Projection":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/projection","type":"topic","title":"Projection","abstract":[{"type":"text","text":"A collection of "},{"type":"reference","identifier":"https:\/\/en.wikipedia.org\/wiki\/Web_Mercator_projection","isActive":true},{"type":"text","text":" projection methods."}],"role":"symbol","navigatorTitle":[{"text":"Projection","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Projection","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Projection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapError":{"abstract":[{"type":"text","text":"Type of errors thrown by the "},{"type":"codeVoice","code":"MapboxMap"},{"type":"text","text":" APIs."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapError"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapError","type":"topic","url":"\/documentation\/mapboxmaps\/maperror","role":"symbol","kind":"symbol","title":"MapError","navigatorTitle":[{"kind":"identifier","text":"MapError"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderedQueryGeometry":{"abstract":[{"type":"text","text":"A geometry to define a portion of screen that should be queried for rendered features."}],"url":"\/documentation\/mapboxmaps\/renderedquerygeometry","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometry","title":"RenderedQueryGeometry","navigatorTitle":[{"text":"RenderedQueryGeometry","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RenderedQueryGeometry","kind":"identifier"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraBounds":{"abstract":[{"text":"Holds information about camera bounds.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBounds","role":"symbol","navigatorTitle":[{"text":"CameraBounds","kind":"identifier"}],"title":"CameraBounds","kind":"symbol","url":"\/documentation\/mapboxmaps\/camerabounds","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraBounds","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateBounds":{"url":"\/documentation\/mapboxmaps\/coordinatebounds","title":"CoordinateBounds","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoordinateBounds","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds","kind":"symbol","navigatorTitle":[{"text":"CoordinateBounds","kind":"identifier"}],"abstract":[{"type":"text","text":"A rectangular area as measured on a two-dimensional map projection."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraState/pitch":{"url":"\/documentation\/mapboxmaps\/camerastate\/pitch","abstract":[{"type":"text","text":"Pitch toward the horizon measured in degrees, with 0 degrees resulting in a top-down view for a two-dimensional map."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraState\/pitch","title":"pitch","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pitch","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraBoundsOptions":{"type":"topic","title":"CameraBoundsOptions","role":"symbol","url":"\/documentation\/mapboxmaps\/cameraboundsoptions","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBoundsOptions","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraBoundsOptions","kind":"identifier"}],"abstract":[{"text":"Holds options to be used for setting camera bounds.","type":"text"}],"navigatorTitle":[{"text":"CameraBoundsOptions","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapCenterAltitudeMode":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapCenterAltitudeMode","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapCenterAltitudeMode"}],"abstract":[{"text":"Defines how the map center point should react to terrain elevation changes.","type":"text"}],"url":"\/documentation\/mapboxmaps\/mapcenteraltitudemode","navigatorTitle":[{"kind":"identifier","text":"MapCenterAltitudeMode"}],"title":"MapCenterAltitudeMode"},"doc://com.mapbox.MapboxMaps/SH":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","title":"Swift.Hashable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraState/padding":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"padding"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIEdgeInsets","preciseIdentifier":"c:@S@UIEdgeInsets"}],"url":"\/documentation\/mapboxmaps\/camerastate\/padding","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraState\/padding","abstract":[{"text":"Insets from each edge of the map. Impacts the “principal point” of the graphical projection and the location at which ","type":"text"},{"type":"codeVoice","code":"center"},{"text":" is rendered.","type":"text"}],"title":"padding","kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateInfo":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"CoordinateInfo"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateInfo","abstract":[{"text":"Represents the coordinate information returned by the ","type":"text"},{"code":"coordinateInfoForPixel","type":"codeVoice"},{"text":" or ","type":"text"},{"code":"coordinatesInfoForPixels","type":"codeVoice"},{"text":" methods.","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/mapboxmaps\/coordinateinfo","title":"CoordinateInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoordinateInfo"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateBoundsZoom":{"type":"topic","navigatorTitle":[{"text":"CoordinateBoundsZoom","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBoundsZoom","abstract":[{"type":"text","text":"A coordinate bounds and zoom."}],"role":"symbol","kind":"symbol","url":"\/documentation\/mapboxmaps\/coordinateboundszoom","title":"CoordinateBoundsZoom","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoordinateBoundsZoom","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraState/bearing":{"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraState\/bearing","kind":"symbol","url":"\/documentation\/mapboxmaps\/camerastate\/bearing","title":"bearing","abstract":[{"text":"The bearing of the map, measured in degrees clockwise from true north.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bearing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CLLocationDirection","text":"CLLocationDirection"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraState/center":{"abstract":[{"text":"The geographic coordinate that will be rendered at the midpoint of the area defined by ","type":"text"},{"code":"padding","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"center","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D","kind":"typeIdentifier"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraState\/center","url":"\/documentation\/mapboxmaps\/camerastate\/center","title":"center"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderedQueryGeometryConvertible":{"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RenderedQueryGeometryConvertible"}],"navigatorTitle":[{"kind":"identifier","text":"RenderedQueryGeometryConvertible"}],"title":"RenderedQueryGeometryConvertible","abstract":[{"text":"A convenience protocol for automatic conversion to ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometry","isActive":true,"type":"reference"},{"text":".","type":"text"}],"url":"\/documentation\/mapboxmaps\/renderedquerygeometryconvertible","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometryConvertible","type":"topic"},"doc://com.mapbox.MapboxMaps/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s8SendableP","title":"Swift.Sendable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraState/init(from:)":{"url":"\/documentation\/mapboxmaps\/camerastate\/init(from:)","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraState\/init(from:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP","text":"Decoder"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"type":"topic","title":"init(from:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"type":"topic","url":"\/documentation\/mapboxmaps","role":"collection","kind":"symbol","title":"MapboxMaps"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ContextMode\/title","op":"replace","value":"MBMContextMode"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ContextMode\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMContextMode"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ContextMode\/navigatorTitle","op":"replace","value":[{"text":"MBMContextMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/title","op":"replace","value":"MBMGlyphsRasterizationMode"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMGlyphsRasterizationMode"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMGlyphsRasterizationMode"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds\/title","op":"replace","value":"MBMCoordinateBounds"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds\/fragments","op":"replace","value":[{"text":"MBMCoordinateBounds","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMCoordinateBounds"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapCenterAltitudeMode\/title","op":"replace","value":"MBMMapCenterAltitudeMode"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapCenterAltitudeMode\/fragments","op":"replace","value":[{"text":"MBMMapCenterAltitudeMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapCenterAltitudeMode\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMMapCenterAltitudeMode"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateInfo\/title","op":"replace","value":"MBMCoordinateInfo"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateInfo\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMCoordinateInfo"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateInfo\/navigatorTitle","op":"replace","value":[{"text":"MBMCoordinateInfo","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBoundsZoom\/title","op":"replace","value":"MBMCoordinateBoundsZoom"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBoundsZoom\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMCoordinateBoundsZoom"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBoundsZoom\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMCoordinateBoundsZoom"}]}]}]}