{"metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClearCacheError"}],"externalID":"s:10MapboxMaps15ClearCacheErrorO","role":"symbol","roleHeading":"Enumeration","navigatorTitle":[{"text":"ClearCacheError","kind":"identifier"}],"modules":[{"name":"MapboxMaps"}],"symbolKind":"enum","title":"ClearCacheError"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Describes the reason for a cache clearing failure."}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClearCacheError\/database(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClearCacheError\/other(_:)"],"generated":true,"anchor":"Enumeration-Cases"},{"title":"Default Implementations","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClearCacheError\/Equatable-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClearCacheError\/Error-Implementations"],"generated":true,"anchor":"Default-Implementations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClearCacheError"},"seeAlsoSections":[{"title":"TileStore","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStoreOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudget","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInMegabytes","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInTiles","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCoverOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegion","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileRegionError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgress","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TilesetDescriptor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TilesetDescriptorOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgressCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreUsageMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileRegionError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileDataDomain","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgress","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateResult","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgressCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingErrorType"],"generated":true,"anchor":"TileStore"}],"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/s5ErrorP","doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"],"kind":"relationships"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ClearCacheError","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/clearcacheerror"]}],"kind":"symbol","sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","url":"\/documentation\/overview","role":"collection","abstract":[],"kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileStore":{"kind":"symbol","abstract":[{"text":"TileStore manages downloads and storage for requests to tile-related API endpoints, enforcing a disk usage","type":"text"},{"text":" ","type":"text"},{"text":"quota: tiles available on disk may be deleted to make room for a new download. This interface can be used by an","type":"text"},{"text":" ","type":"text"},{"text":"app developer to set the disk quota. The rest of TileStore API is intended for native SDK consumption only.","type":"text"}],"navigatorTitle":[{"text":"TileStore","kind":"identifier"}],"title":"TileStore","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileStore","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapboxcommon\/tilestore","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateResult":{"abstract":[{"type":"text","text":"The result of tile region estim"}],"role":"symbol","navigatorTitle":[{"text":"TileRegionEstimateResult","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateResult","title":"TileRegionEstimateResult","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileRegionEstimateResult","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/tileregionestimateresult"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TilesetDescriptor":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TilesetDescriptor"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TilesetDescriptor","url":"\/documentation\/mapboxcommon\/tilesetdescriptor","title":"TilesetDescriptor","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TilesetDescriptor"}],"abstract":[{"text":"A bundle that encapsulates tilesets creation for the tile store implementation.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TilesetDescriptorOptions":{"url":"\/documentation\/mapboxmaps\/tilesetdescriptoroptions","kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TilesetDescriptorOptions","title":"TilesetDescriptorOptions","abstract":[{"text":"Describes the tileset descriptor option values.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TilesetDescriptorOptions","kind":"identifier"}],"navigatorTitle":[{"text":"TilesetDescriptorOptions","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileRegionError":{"abstract":[{"text":"Describes the reason for a tile region download request failure.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileRegionError","kind":"identifier"}],"kind":"symbol","title":"TileRegionError","url":"\/documentation\/mapboxmaps\/tileregionerror","type":"topic","role":"symbol","navigatorTitle":[{"text":"TileRegionError","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileRegionError"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileDataDomain":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileDataDomain","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileDataDomain","kind":"identifier"}],"navigatorTitle":[{"text":"TileDataDomain","kind":"identifier"}],"kind":"symbol","title":"TileDataDomain","abstract":[{"type":"text","text":"Describes the tiles data domain."}],"role":"symbol","url":"\/documentation\/mapboxcommon\/tiledatadomain","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CanonicalTileID":{"url":"\/documentation\/mapboxmaps\/canonicaltileid","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CanonicalTileID","kind":"identifier"}],"abstract":[{"type":"text","text":"Represents a tile coordinate."}],"navigatorTitle":[{"text":"CanonicalTileID","kind":"identifier"}],"title":"CanonicalTileID","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateProgressCallback":{"abstract":[],"kind":"symbol","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileRegionEstimateProgressCallback","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/tileregionestimateprogresscallback","title":"TileRegionEstimateProgressCallback","navigatorTitle":[{"text":"TileRegionEstimateProgressCallback","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgressCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileStoreOptions":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileStoreOptions"}],"navigatorTitle":[{"kind":"identifier","text":"TileStoreOptions"}],"type":"topic","title":"TileStoreOptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStoreOptions","url":"\/documentation\/mapboxcommon\/tilestoreoptions","kind":"symbol","abstract":[{"type":"text","text":"These constants can be used as keys for TileStore::setOption to configure further aspects of a TileStore instance."}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ClearCacheError/Equatable-Implementations":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClearCacheError\/Equatable-Implementations","kind":"article","role":"collectionGroup","type":"topic","title":"Equatable Implementations","url":"\/documentation\/mapboxmaps\/clearcacheerror\/equatable-implementations","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadProgress":{"url":"\/documentation\/mapboxcommon\/tileregionloadprogress","title":"TileRegionLoadProgress","abstract":[{"type":"text","text":"A tile region’s load progress includes counts"},{"type":"text","text":" "},{"type":"text","text":"of the number of resources that have completed downloading"},{"type":"text","text":" "},{"type":"text","text":"and the total number of resources that are required."}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileRegionLoadProgress"}],"navigatorTitle":[{"kind":"identifier","text":"TileRegionLoadProgress"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgress"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStoreUsageMode":{"role":"symbol","url":"\/documentation\/mapboxmaps\/tilestoreusagemode","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreUsageMode","type":"topic","title":"TileStoreUsageMode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileStoreUsageMode","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"TileStoreUsageMode","kind":"identifier"}],"abstract":[{"text":"Describes tile store usage modes.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ClearCacheError/Error-Implementations":{"url":"\/documentation\/mapboxmaps\/clearcacheerror\/error-implementations","kind":"article","type":"topic","abstract":[],"title":"Error Implementations","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClearCacheError\/Error-Implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"abstract":[],"url":"\/documentation\/mapboxmaps\/tilestore-apis","title":"TileStore APIs","kind":"article","type":"topic","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs"},"doc://com.mapbox.MapboxMaps/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCoverOptions":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileCoverOptions"}],"navigatorTitle":[{"kind":"identifier","text":"TileCoverOptions"}],"title":"TileCoverOptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCoverOptions","type":"topic","url":"\/documentation\/mapboxmaps\/tilecoveroptions","role":"symbol","kind":"symbol","tags":[{"type":"spi","text":"SPI"}],"abstract":[{"type":"text","text":"Various options needed for tile cover."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateOptions":{"title":"TileRegionEstimateOptions","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileRegionEstimateOptions","kind":"identifier"}],"navigatorTitle":[{"text":"TileRegionEstimateOptions","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Holds options for the tile region estimation operation.","type":"text"}],"kind":"symbol","url":"\/documentation\/mapboxcommon\/tileregionestimateoptions","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudgetInMegabytes":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Tile cache budget in megabytes."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileCacheBudgetInMegabytes"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInMegabytes","title":"TileCacheBudgetInMegabytes","url":"\/documentation\/mapboxmaps\/tilecachebudgetinmegabytes","navigatorTitle":[{"kind":"identifier","text":"TileCacheBudgetInMegabytes"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudget":{"title":"TileCacheBudget","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudget","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileCacheBudget"}],"url":"\/documentation\/mapboxmaps\/tilecachebudget","abstract":[],"role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TileCacheBudget"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateProgress":{"url":"\/documentation\/mapboxcommon\/tileregionestimateprogress","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgress","navigatorTitle":[{"text":"TileRegionEstimateProgress","kind":"identifier"}],"title":"TileRegionEstimateProgress","abstract":[{"text":"A tile region’s estimate progress includes counts of the number of resources that have","type":"text"},{"text":" ","type":"text"},{"text":"been estimated and the total number of resources as well as a partial result with the","type":"text"},{"text":" ","type":"text"},{"text":"current estimate, calculated using the data available at the moment.","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileRegionEstimateProgress","kind":"identifier"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStoreObserver":{"url":"\/documentation\/mapboxmaps\/tilestoreobserver","abstract":[],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileStoreObserver","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"TileStoreObserver","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreObserver","type":"topic","title":"TileStoreObserver"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegion":{"role":"symbol","title":"TileRegion","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileRegion","kind":"identifier"}],"abstract":[{"text":"TileRegion represents an identifiable geographic tile region with metadata","type":"text"}],"navigatorTitle":[{"text":"TileRegion","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxcommon\/tileregion","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegion","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadOptions":{"url":"\/documentation\/mapboxcommon\/tileregionloadoptions","role":"symbol","abstract":[{"text":"Describes the tile region load option values.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions","type":"topic","navigatorTitle":[{"text":"TileRegionLoadOptions","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileRegionLoadOptions","kind":"identifier"}],"kind":"symbol","title":"TileRegionLoadOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ClearCacheError/database(_:)":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"database","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"url":"\/documentation\/mapboxmaps\/clearcacheerror\/database(_:)","abstract":[{"text":"There was an issue accessing the database","type":"text"}],"title":"ClearCacheError.database(_:)","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClearCacheError\/database(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileOptions":{"type":"topic","url":"\/documentation\/mapboxmaps\/tileoptions","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TileOptions"}],"title":"TileOptions","abstract":[{"type":"text","text":"Options for custom geometry tiles."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileOptions","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileOptions"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ClearCacheError":{"navigatorTitle":[{"text":"ClearCacheError","kind":"identifier"}],"title":"ClearCacheError","abstract":[{"text":"Describes the reason for a cache clearing failure.","type":"text"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClearCacheError","url":"\/documentation\/mapboxmaps\/clearcacheerror","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ClearCacheError","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"type":"topic","url":"\/documentation\/mapboxmaps","role":"collection","kind":"symbol","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadProgressCallback":{"url":"\/documentation\/mapboxcommon\/tileregionloadprogresscallback","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileRegionLoadProgressCallback"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgressCallback","navigatorTitle":[{"kind":"identifier","text":"TileRegionLoadProgressCallback"}],"abstract":[{"type":"text","text":"Callback Invoked to report the progess of the tile region loading operation."}],"title":"TileRegionLoadProgressCallback","kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/CacheClearingError":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CacheClearingError","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapboxcommon\/cacheclearingerror","abstract":[{"text":"Describes a cache clearing error.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingError","role":"symbol","navigatorTitle":[{"text":"CacheClearingError","kind":"identifier"}],"title":"CacheClearingError"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ClearCacheError/other(_:)":{"url":"\/documentation\/mapboxmaps\/clearcacheerror\/other(_:)","title":"ClearCacheError.other(_:)","kind":"symbol","abstract":[{"text":"There was an uncategorised error, check the associated message","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClearCacheError\/other(_:)","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"other","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudgetInTiles":{"abstract":[{"text":"Tile cache budget in tiles.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"TileCacheBudgetInTiles"}],"kind":"symbol","title":"TileCacheBudgetInTiles","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileCacheBudgetInTiles"}],"type":"topic","url":"\/documentation\/mapboxmaps\/tilecachebudgetintiles","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInTiles","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudgetType":{"navigatorTitle":[{"text":"TileCacheBudgetType","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/tilecachebudgettype","abstract":[],"title":"TileCacheBudgetType","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileCacheBudgetType"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/CacheClearingErrorType":{"navigatorTitle":[{"text":"CacheClearingErrorType","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingErrorType","abstract":[{"text":"Describes the reason for a cache clearing failure.","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/mapboxcommon\/cacheclearingerrortype","title":"CacheClearingErrorType","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CacheClearingErrorType","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/s5ErrorP":{"title":"Swift.Error","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s5ErrorP"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/title","op":"replace","value":"MBXTileStore"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/fragments","op":"replace","value":[{"text":"MBXTileStore","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/navigatorTitle","op":"replace","value":[{"text":"MBXTileStore","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateResult\/title","op":"replace","value":"MBXTileRegionEstimateResult"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateResult\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXTileRegionEstimateResult"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateResult\/navigatorTitle","op":"replace","value":[{"text":"MBXTileRegionEstimateResult","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TilesetDescriptor\/title","op":"replace","value":"MBXTilesetDescriptor"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TilesetDescriptor\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXTilesetDescriptor"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TilesetDescriptor\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBXTilesetDescriptor"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions\/title","op":"replace","value":"MBMTilesetDescriptorOptions"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions\/fragments","op":"replace","value":[{"text":"MBMTilesetDescriptorOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions\/navigatorTitle","op":"replace","value":[{"text":"MBMTilesetDescriptorOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileDataDomain\/title","op":"replace","value":"MBXTileDataDomain"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileDataDomain\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXTileDataDomain"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileDataDomain\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBXTileDataDomain"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/title","op":"replace","value":"MBMCanonicalTileID"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/fragments","op":"replace","value":[{"text":"MBMCanonicalTileID","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/navigatorTitle","op":"replace","value":[{"text":"MBMCanonicalTileID","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgressCallback\/title","op":"replace","value":"MBXTileRegionEstimateProgressCallback"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgressCallback\/fragments","op":"replace","value":[{"text":"MBXTileRegionEstimateProgressCallback","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgressCallback\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBXTileRegionEstimateProgressCallback"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStoreOptions\/title","op":"replace","value":"MBXTileStoreOptions"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStoreOptions\/fragments","op":"replace","value":[{"text":"MBXTileStoreOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStoreOptions\/navigatorTitle","op":"replace","value":[{"text":"MBXTileStoreOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgress\/title","op":"replace","value":"MBXTileRegionLoadProgress"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgress\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXTileRegionLoadProgress"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgress\/navigatorTitle","op":"replace","value":[{"text":"MBXTileRegionLoadProgress","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileStoreUsageMode\/title","op":"replace","value":"MBMTileStoreUsageMode"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileStoreUsageMode\/fragments","op":"replace","value":[{"text":"MBMTileStoreUsageMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileStoreUsageMode\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMTileStoreUsageMode"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateOptions\/title","op":"replace","value":"MBXTileRegionEstimateOptions"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateOptions\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXTileRegionEstimateOptions"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateOptions\/navigatorTitle","op":"replace","value":[{"text":"MBXTileRegionEstimateOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInMegabytes\/title","op":"replace","value":"MBMTileCacheBudgetInMegabytes"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInMegabytes\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMTileCacheBudgetInMegabytes"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInMegabytes\/navigatorTitle","op":"replace","value":[{"text":"MBMTileCacheBudgetInMegabytes","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudget\/title","op":"replace","value":"MBMTileCacheBudget"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudget\/fragments","op":"replace","value":[{"text":"MBMTileCacheBudget","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudget\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMTileCacheBudget"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgress\/title","op":"replace","value":"MBXTileRegionEstimateProgress"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgress\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXTileRegionEstimateProgress"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgress\/navigatorTitle","op":"replace","value":[{"text":"MBXTileRegionEstimateProgress","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegion\/title","op":"replace","value":"MBXTileRegion"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegion\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXTileRegion"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegion\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBXTileRegion"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/title","op":"replace","value":"MBXTileRegionLoadOptions"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/fragments","op":"replace","value":[{"text":"MBXTileRegionLoadOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/navigatorTitle","op":"replace","value":[{"text":"MBXTileRegionLoadOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileOptions\/title","op":"replace","value":"MBMTileOptions"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileOptions\/fragments","op":"replace","value":[{"text":"MBMTileOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileOptions\/navigatorTitle","op":"replace","value":[{"text":"MBMTileOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgressCallback\/title","op":"replace","value":"MBXTileRegionLoadProgressCallback"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgressCallback\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXTileRegionLoadProgressCallback"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgressCallback\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBXTileRegionLoadProgressCallback"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingError\/title","op":"replace","value":"MBXCacheClearingError"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingError\/fragments","op":"replace","value":[{"text":"MBXCacheClearingError","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingError\/navigatorTitle","op":"replace","value":[{"text":"MBXCacheClearingError","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInTiles\/title","op":"replace","value":"MBMTileCacheBudgetInTiles"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInTiles\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMTileCacheBudgetInTiles"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInTiles\/navigatorTitle","op":"replace","value":[{"text":"MBMTileCacheBudgetInTiles","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetType\/title","op":"replace","value":"MBMTileCacheBudgetType"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetType\/fragments","op":"replace","value":[{"text":"MBMTileCacheBudgetType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetType\/navigatorTitle","op":"replace","value":[{"text":"MBMTileCacheBudgetType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingErrorType\/title","op":"replace","value":"MBXCacheClearingErrorType"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingErrorType\/fragments","op":"replace","value":[{"text":"MBXCacheClearingErrorType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingErrorType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBXCacheClearingErrorType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}