{"variants":[{"paths":["\/documentation\/mapboxmaps\/contextmode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/contextmode"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"generated":true,"anchor":"MapboxMap","title":"MapboxMap","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraState","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBounds","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBoundsOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Projection","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBoundsZoom","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateInfo","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapCenterAltitudeMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometry","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometryConvertible"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"roleHeading":"Enumeration","externalID":"c:@E@MBMContextMode","title":"ContextMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContextMode"}],"navigatorTitle":[{"kind":"identifier","text":"ContextMode"}],"symbolKind":"enum","role":"symbol","modules":[{"name":"MapboxMaps"}]},"kind":"symbol","abstract":[{"text":"Describes the map context mode.","type":"text"},{"text":" ","type":"text"},{"text":"We can make some optimizations if we know that the drawing context is not shared with other code.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContextMode"}],"platforms":["iOS"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs"]]},"relationshipsSections":[{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/s15BitwiseCopyableP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH","doc:\/\/com.mapbox.MapboxMaps\/SY","doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"],"type":"conformsTo"}],"topicSections":[{"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ContextMode\/shared","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ContextMode\/unique"]},{"generated":true,"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ContextMode\/init(rawValue:)"]},{"generated":true,"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ContextMode\/Equatable-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ContextMode\/RawRepresentable-Implementations"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ContextMode"},"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"kind":"article","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","url":"\/documentation\/overview","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","title":"Swift.Equatable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ContextMode":{"type":"topic","title":"ContextMode","url":"\/documentation\/mapboxmaps\/contextmode","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ContextMode","abstract":[{"type":"text","text":"Describes the map context mode."},{"type":"text","text":" "},{"type":"text","text":"We can make some optimizations if we know that the drawing context is not shared with other code."}],"kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContextMode","kind":"identifier"}],"navigatorTitle":[{"text":"ContextMode","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraState":{"abstract":[],"type":"topic","url":"\/documentation\/mapboxmaps\/camerastate","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraState","role":"symbol","title":"CameraState","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraState"}],"navigatorTitle":[{"kind":"identifier","text":"CameraState"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ContextMode/init(rawValue:)":{"url":"\/documentation\/mapboxmaps\/contextmode\/init(rawvalue:)","kind":"symbol","type":"topic","title":"init(rawValue:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ContextMode\/init(rawValue:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ContextMode/RawRepresentable-Implementations":{"role":"collectionGroup","kind":"article","abstract":[],"type":"topic","url":"\/documentation\/mapboxmaps\/contextmode\/rawrepresentable-implementations","title":"RawRepresentable Implementations","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ContextMode\/RawRepresentable-Implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GlyphsRasterizationMode":{"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"GlyphsRasterizationMode","kind":"identifier"}],"abstract":[{"type":"text","text":"Describes glyphs rasterization modes."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode","title":"GlyphsRasterizationMode","url":"\/documentation\/mapboxmaps\/glyphsrasterizationmode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GlyphsRasterizationMode","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateBoundsZoom":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBoundsZoom","abstract":[{"type":"text","text":"A coordinate bounds and zoom."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoordinateBoundsZoom","kind":"identifier"}],"kind":"symbol","type":"topic","title":"CoordinateBoundsZoom","url":"\/documentation\/mapboxmaps\/coordinateboundszoom","navigatorTitle":[{"text":"CoordinateBoundsZoom","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap":{"title":"MapboxMap","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapboxMap"}],"navigatorTitle":[{"kind":"identifier","text":"MapboxMap"}],"abstract":[{"text":"Provides access to the map model, including the camera, style, observable map events,","type":"text"},{"text":" ","type":"text"},{"text":"and querying rendered features.","type":"text"}],"type":"topic","url":"\/documentation\/mapboxmaps\/mapboxmap"},"doc://com.mapbox.MapboxMaps/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SY"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ContextMode/unique":{"kind":"symbol","title":"ContextMode.unique","url":"\/documentation\/mapboxmaps\/contextmode\/unique","role":"symbol","navigatorTitle":[{"text":"MBMContextModeUnique","kind":"identifier"}],"abstract":[{"type":"text","text":"Unique context mode: in OpenGL, the GL context is not shared, thus we can retain knowledge about the GL state"},{"type":"text","text":" "},{"type":"text","text":"from a previous render pass. It also enables clearing the screen using glClear for the bottommost background"},{"type":"text","text":" "},{"type":"text","text":"layer when no pattern is applied to that layer."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unique","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ContextMode\/unique"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","title":"MapboxMap","kind":"article","type":"topic","abstract":[],"role":"collectionGroup","url":"\/documentation\/mapboxmaps\/mapboxmap-apis"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ContextMode/Equatable-Implementations":{"title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ContextMode\/Equatable-Implementations","kind":"article","url":"\/documentation\/mapboxmaps\/contextmode\/equatable-implementations","role":"collectionGroup","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderedQueryGeometryConvertible":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RenderedQueryGeometryConvertible"}],"url":"\/documentation\/mapboxmaps\/renderedquerygeometryconvertible","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometryConvertible","navigatorTitle":[{"kind":"identifier","text":"RenderedQueryGeometryConvertible"}],"abstract":[{"type":"text","text":"A convenience protocol for automatic conversion to "},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometry","isActive":true},{"type":"text","text":"."}],"title":"RenderedQueryGeometryConvertible"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraOptions":{"navigatorTitle":[{"kind":"identifier","text":"CameraOptions"}],"url":"\/documentation\/mapboxmaps\/cameraoptions","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraOptions"}],"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraOptions","role":"symbol","kind":"symbol","type":"topic","title":"CameraOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateBounds":{"navigatorTitle":[{"text":"CoordinateBounds","kind":"identifier"}],"title":"CoordinateBounds","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoordinateBounds","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds","url":"\/documentation\/mapboxmaps\/coordinatebounds","abstract":[{"text":"A rectangular area as measured on a two-dimensional map projection.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderedQueryGeometry":{"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"RenderedQueryGeometry"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometry","navigatorTitle":[{"kind":"identifier","text":"RenderedQueryGeometry"}],"url":"\/documentation\/mapboxmaps\/renderedquerygeometry","title":"RenderedQueryGeometry","abstract":[{"type":"text","text":"A geometry to define a portion of screen that should be queried for rendered features."}],"type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s8SendableP","title":"Swift.Sendable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","kind":"symbol","title":"MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ContextMode/shared":{"url":"\/documentation\/mapboxmaps\/contextmode\/shared","title":"ContextMode.shared","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"MBMContextModeShared","kind":"identifier"}],"abstract":[{"text":"Shared context mode: in OpenGL, the GL context is shared with other renderers, thus we cannot rely on the GL","type":"text"},{"text":" ","type":"text"},{"text":"state set from a previous render pass.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ContextMode\/shared"},"doc://com.mapbox.MapboxMaps/s15BitwiseCopyableP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s15BitwiseCopyableP","title":"Swift.BitwiseCopyable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateInfo":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateInfo","abstract":[{"type":"text","text":"Represents the coordinate information returned by the "},{"type":"codeVoice","code":"coordinateInfoForPixel"},{"type":"text","text":" or "},{"type":"codeVoice","code":"coordinatesInfoForPixels"},{"type":"text","text":" methods."}],"type":"topic","url":"\/documentation\/mapboxmaps\/coordinateinfo","kind":"symbol","title":"CoordinateInfo","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoordinateInfo","kind":"identifier"}],"navigatorTitle":[{"text":"CoordinateInfo","kind":"identifier"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraBoundsOptions":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBoundsOptions","abstract":[{"type":"text","text":"Holds options to be used for setting camera bounds."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraBoundsOptions","kind":"identifier"}],"kind":"symbol","type":"topic","title":"CameraBoundsOptions","url":"\/documentation\/mapboxmaps\/cameraboundsoptions","navigatorTitle":[{"text":"CameraBoundsOptions","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Projection":{"type":"topic","abstract":[{"type":"text","text":"A collection of "},{"type":"reference","identifier":"https:\/\/en.wikipedia.org\/wiki\/Web_Mercator_projection","isActive":true},{"type":"text","text":" projection methods."}],"title":"Projection","url":"\/documentation\/mapboxmaps\/projection","navigatorTitle":[{"kind":"identifier","text":"Projection"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Projection"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Projection"},"https://en.wikipedia.org/wiki/Web_Mercator_projection":{"titleInlineContent":[{"text":"Spherical Mercator","type":"text"}],"type":"link","identifier":"https:\/\/en.wikipedia.org\/wiki\/Web_Mercator_projection","title":"Spherical Mercator","url":"https:\/\/en.wikipedia.org\/wiki\/Web_Mercator_projection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraBounds":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraBounds"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraBounds"}],"title":"CameraBounds","abstract":[{"type":"text","text":"Holds information about camera bounds."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBounds","kind":"symbol","url":"\/documentation\/mapboxmaps\/camerabounds"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapCenterAltitudeMode":{"navigatorTitle":[{"text":"MapCenterAltitudeMode","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapCenterAltitudeMode","kind":"symbol","url":"\/documentation\/mapboxmaps\/mapcenteraltitudemode","abstract":[{"type":"text","text":"Defines how the map center point should react to terrain elevation changes."}],"role":"symbol","type":"topic","title":"MapCenterAltitudeMode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapCenterAltitudeMode","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapError":{"navigatorTitle":[{"kind":"identifier","text":"MapError"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapError","kind":"symbol","url":"\/documentation\/mapboxmaps\/maperror","abstract":[{"type":"text","text":"Type of errors thrown by the "},{"type":"codeVoice","code":"MapboxMap"},{"type":"text","text":" APIs."}],"role":"symbol","title":"MapError","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapError"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","value":"MBMContextMode","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"MBMContextMode","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MBMContextMode"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ContextMode\/shared","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ContextMode\/unique"],"anchor":"Enumeration-Cases","title":"Enumeration Cases","generated":true}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":[{"anchor":"MapboxMap","title":"MapboxMap","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBoundsZoom","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateInfo","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapCenterAltitudeMode"]}],"op":"replace"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBMContextMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ContextMode\/title","value":"MBMContextMode","op":"replace"},{"value":[{"text":"MBMContextMode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ContextMode\/fragments","op":"replace"},{"value":[{"text":"MBMContextMode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ContextMode\/navigatorTitle","op":"replace"},{"value":"MBMGlyphsRasterizationMode","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MBMGlyphsRasterizationMode"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MBMGlyphsRasterizationMode"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/navigatorTitle","op":"replace"},{"value":"MBMCoordinateBoundsZoom","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBoundsZoom\/title","op":"replace"},{"value":[{"text":"MBMCoordinateBoundsZoom","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBoundsZoom\/fragments","op":"replace"},{"value":[{"text":"MBMCoordinateBoundsZoom","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBoundsZoom\/navigatorTitle","op":"replace"},{"value":"MBMContextModeUnique","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ContextMode~1unique\/title","op":"replace"},{"value":[{"text":"MBMContextModeUnique","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ContextMode~1unique\/fragments","op":"replace"},{"value":"MBMCoordinateBounds","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds\/title"},{"value":[{"kind":"identifier","text":"MBMCoordinateBounds"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MBMCoordinateBounds"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds\/navigatorTitle"},{"op":"replace","value":"MBMContextModeShared","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ContextMode~1shared\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBMContextModeShared"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ContextMode~1shared\/fragments"},{"op":"replace","value":"MBMCoordinateInfo","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateInfo\/title"},{"op":"replace","value":[{"text":"MBMCoordinateInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateInfo\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MBMCoordinateInfo"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateInfo\/navigatorTitle"},{"op":"replace","value":"MBMMapCenterAltitudeMode","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapCenterAltitudeMode\/title"},{"op":"replace","value":[{"text":"MBMMapCenterAltitudeMode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapCenterAltitudeMode\/fragments"},{"op":"replace","value":[{"text":"MBMMapCenterAltitudeMode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapCenterAltitudeMode\/navigatorTitle"}]}]}