{"sections":[],"seeAlsoSections":[{"title":"Layers","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerInfo","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/BackgroundLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CircleLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillExtrusionLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationIndicatorLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterParticleLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SkyLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderConfiguration","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerHost","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerMapProjection","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ElevationData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Slot","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SlotLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerAtPosition","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClipLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClipLayerTypes"],"generated":true,"anchor":"Layers"}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HillshadeLayer","kind":"identifier"}],"externalID":"s:10MapboxMaps14HillshadeLayerV","symbolKind":"struct","roleHeading":"Structure","role":"symbol","title":"HillshadeLayer","modules":[{"name":"MapboxMaps"}],"navigatorTitle":[{"text":"HillshadeLayer","kind":"identifier"}]},"kind":"symbol","abstract":[{"text":"Client-side hillshading visualization based on DEM data. Currently, the implementation only supports Mapbox Terrain RGB and Mapzen Terrarium tiles.","type":"text"}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/init(from:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/init(id:source:)"],"generated":true,"anchor":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/filter","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeAccentColor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeAccentColorTransition","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeEmissiveStrength","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeEmissiveStrengthTransition","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeExaggeration","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeExaggerationTransition","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeHighlightColor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeHighlightColorTransition","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeIlluminationAnchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeIlluminationDirection","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeShadowColor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeShadowColorTransition","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/id","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/maxZoom","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/minZoom","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/slot","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/source","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/sourceLayer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/type","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/visibility"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/encode(to:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/filter(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeAccentColor(_:)-2b6md","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeAccentColor(_:)-58mi5","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeAccentColor(_:)-6c9l9","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeAccentColorTransition(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeAccentColorUseTheme(_:)-5sut","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeAccentColorUseTheme(_:)-6h2vo","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeEmissiveStrength(_:)-40tmf","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeEmissiveStrength(_:)-8nh0q","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeEmissiveStrengthTransition(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeExaggeration(_:)-274oz","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeExaggeration(_:)-90tin","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeExaggerationTransition(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeHighlightColor(_:)-1iz83","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeHighlightColor(_:)-6xzvs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeHighlightColor(_:)-84cah","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeHighlightColorTransition(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeHighlightColorUseTheme(_:)-3u4o6","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeHighlightColorUseTheme(_:)-8yp16","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeIlluminationAnchor(_:)-1z89n","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeIlluminationAnchor(_:)-42w4u","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeIlluminationDirection(_:)-5t2mg","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeIlluminationDirection(_:)-mdve","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeShadowColor(_:)-1han1","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeShadowColor(_:)-1jg80","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeShadowColor(_:)-8wrgz","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeShadowColorTransition(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeShadowColorUseTheme(_:)-5xagu","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeShadowColorUseTheme(_:)-81qir","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/maxZoom(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/minZoom(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/slot(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/source(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/sourceLayer(_:)"],"generated":true,"anchor":"Instance-Methods"},{"title":"Default Implementations","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/Equatable-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/Layer-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/StyleEncodable-Implementations"],"generated":true,"anchor":"Default-Implementations"}],"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapStyleContent","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDecodable","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleEncodable","doc:\/\/com.mapbox.MapboxMaps\/s8CopyableP","doc:\/\/com.mapbox.MapboxMaps\/Se","doc:\/\/com.mapbox.MapboxMaps\/SE","doc:\/\/com.mapbox.MapboxMaps\/SQ"],"type":"conformsTo","kind":"relationships"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HillshadeLayer","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"text":"Overview","type":"heading","anchor":"overview","level":2},{"type":"aside","name":"See Also","content":[{"inlineContent":[{"type":"text","text":""},{"type":"reference","identifier":"https:\/\/www.mapbox.com\/mapbox-gl-style-spec\/#layers-hillshade","isActive":true}],"type":"paragraph"}],"style":"note"}],"kind":"content"}],"variants":[{"paths":["\/documentation\/mapboxmaps\/hillshadelayer"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/type":{"abstract":[{"text":"Rendering type of this layer.","type":"text"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/hillshadelayer\/type","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps9LayerTypeV","text":"LayerType","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/type","kind":"symbol","title":"type"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerHost":{"title":"CustomLayerHost","navigatorTitle":[{"kind":"identifier","text":"CustomLayerHost"}],"type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/customlayerhost","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomLayerHost"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerHost","abstract":[{"type":"text","text":"Interface for hosting a custom map style layer."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/hillshadeAccentColorUseTheme(_:)-5sut":{"abstract":[{"type":"text","text":"This property defines whether the "},{"type":"codeVoice","code":"hillshadeAccentColor"},{"type":"text","text":" uses colorTheme from the style or not."},{"type":"text","text":" "},{"type":"text","text":"By default it will use color defined by the root theme in the style."}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeAccentColorUseTheme(_:)-5sut","role":"symbol","kind":"symbol","url":"\/documentation\/mapboxmaps\/hillshadelayer\/hillshadeaccentcolorusetheme(_:)-5sut","title":"hillshadeAccentColorUseTheme(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hillshadeAccentColorUseTheme"},{"kind":"text","text":"("},{"preciseIdentifier":"s:10MapboxMaps3ExpV","kind":"typeIdentifier","text":"Exp"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:10MapboxMaps14HillshadeLayerV","kind":"typeIdentifier","text":"HillshadeLayer"}],"tags":[{"type":"spi","text":"SPI"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/maxZoom":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxZoom","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/maxZoom","abstract":[{"type":"text","text":"The maximum zoom level for the layer. At zoom levels equal to or greater than the maxzoom, the layer will be hidden."}],"type":"topic","title":"maxZoom","url":"\/documentation\/mapboxmaps\/hillshadelayer\/maxzoom","kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterParticleLayer":{"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RasterParticleLayer","kind":"identifier"}],"title":"RasterParticleLayer","abstract":[{"type":"text","text":"Particle animation driven by textures such as wind maps."}],"type":"topic","url":"\/documentation\/mapboxmaps\/rasterparticlelayer","kind":"symbol","navigatorTitle":[{"text":"RasterParticleLayer","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterParticleLayer","tags":[{"type":"spi","text":"SPI"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleDecodable":{"navigatorTitle":[{"kind":"identifier","text":"StyleDecodable"}],"title":"StyleDecodable","kind":"symbol","abstract":[{"text":"A protocol describing a style-related entity that can be decoded.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDecodable","url":"\/documentation\/mapboxmaps\/styledecodable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"StyleDecodable"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/hillshadeAccentColorUseTheme(_:)-6h2vo":{"abstract":[{"type":"text","text":"This property defines whether the "},{"type":"codeVoice","code":"hillshadeAccentColor"},{"type":"text","text":" uses colorTheme from the style or not."},{"type":"text","text":" "},{"type":"text","text":"By default it will use color defined by the root theme in the style."}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeAccentColorUseTheme(_:)-6h2vo","role":"symbol","kind":"symbol","url":"\/documentation\/mapboxmaps\/hillshadelayer\/hillshadeaccentcolorusetheme(_:)-6h2vo","title":"hillshadeAccentColorUseTheme(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hillshadeAccentColorUseTheme"},{"kind":"text","text":"("},{"preciseIdentifier":"s:10MapboxMaps13ColorUseThemeV","kind":"typeIdentifier","text":"ColorUseTheme"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:10MapboxMaps14HillshadeLayerV","kind":"typeIdentifier","text":"HillshadeLayer"}],"tags":[{"type":"spi","text":"SPI"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FillLayer":{"role":"symbol","kind":"symbol","url":"\/documentation\/mapboxmaps\/filllayer","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FillLayer"}],"title":"FillLayer","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillLayer","abstract":[{"text":"A filled polygon with an optional stroked border.","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FillLayer"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer":{"navigatorTitle":[{"text":"HillshadeLayer","kind":"identifier"}],"title":"HillshadeLayer","abstract":[{"text":"Client-side hillshading visualization based on DEM data. Currently, the implementation only supports Mapbox Terrain RGB and Mapzen Terrarium tiles.","type":"text"}],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HillshadeLayer","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer","role":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/hillshadelayer"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/hillshadeEmissiveStrengthTransition(_:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hillshadeEmissiveStrengthTransition"},{"kind":"text","text":"("},{"preciseIdentifier":"s:10MapboxMaps15StyleTransitionV","kind":"typeIdentifier","text":"StyleTransition"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:10MapboxMaps14HillshadeLayerV","kind":"typeIdentifier","text":"HillshadeLayer"}],"title":"hillshadeEmissiveStrengthTransition(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeEmissiveStrengthTransition(_:)","url":"\/documentation\/mapboxmaps\/hillshadelayer\/hillshadeemissivestrengthtransition(_:)","type":"topic","abstract":[{"text":"Transition property for ","type":"text"},{"code":"hillshadeEmissiveStrength","type":"codeVoice"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/hillshadeIlluminationDirection(_:)-5t2mg":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeIlluminationDirection(_:)-5t2mg","title":"hillshadeIlluminationDirection(_:)","url":"\/documentation\/mapboxmaps\/hillshadelayer\/hillshadeilluminationdirection(_:)-5t2mg","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hillshadeIlluminationDirection","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Exp","preciseIdentifier":"s:10MapboxMaps3ExpV","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"HillshadeLayer","preciseIdentifier":"s:10MapboxMaps14HillshadeLayerV","kind":"typeIdentifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The direction of the light source used to generate the hillshading with 0 as the top of the viewport if "},{"code":"hillshade-illumination-anchor","type":"codeVoice"},{"type":"text","text":" is set to "},{"code":"viewport","type":"codeVoice"},{"type":"text","text":" and due north if "},{"code":"hillshade-illumination-anchor","type":"codeVoice"},{"type":"text","text":" is set to "},{"code":"map","type":"codeVoice"},{"text":" and no 3d lights enabled. If ","type":"text"},{"code":"hillshade-illumination-anchor","type":"codeVoice"},{"text":" is set to ","type":"text"},{"code":"map","type":"codeVoice"},{"text":" and 3d lights enabled, the direction from 3d lights is used instead.","type":"text"},{"text":" ","type":"text"},{"text":"Default value: 335. Value range: [0, 359]","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Atmosphere":{"abstract":[{"text":"A style’s fog property is a global effect that improves depth perception by fading out distant objects.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Atmosphere","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/atmosphere","navigatorTitle":[{"text":"Atmosphere","kind":"identifier"}],"kind":"symbol","title":"Atmosphere","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Atmosphere"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/hillshadeEmissiveStrength(_:)-40tmf":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Controls the intensity of light emitted on the source features."},{"type":"text","text":" "},{"type":"text","text":"Default value: 0. Minimum value: 0. The unit of hillshadeEmissiveStrength is in intensity."}],"title":"hillshadeEmissiveStrength(_:)","url":"\/documentation\/mapboxmaps\/hillshadelayer\/hillshadeemissivestrength(_:)-40tmf","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hillshadeEmissiveStrength"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps14HillshadeLayerV","text":"HillshadeLayer"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeEmissiveStrength(_:)-40tmf","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/slot(_:)":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/hillshadelayer\/slot(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/slot(_:)","title":"slot(_:)","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"slot"},{"kind":"text","text":"("},{"preciseIdentifier":"s:10MapboxMaps4SlotV","kind":"typeIdentifier","text":"Slot"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:10MapboxMaps14HillshadeLayerV","kind":"typeIdentifier","text":"HillshadeLayer"}],"abstract":[{"type":"text","text":"The slot this layer is assigned to."},{"type":"text","text":" "},{"type":"text","text":"If specified, and a slot with that name exists, it will be placed at that position in the layer order."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/hillshadeHighlightColorUseTheme(_:)-8yp16":{"type":"topic","url":"\/documentation\/mapboxmaps\/hillshadelayer\/hillshadehighlightcolorusetheme(_:)-8yp16","tags":[{"text":"SPI","type":"spi"}],"role":"symbol","abstract":[{"text":"This property defines whether the ","type":"text"},{"type":"codeVoice","code":"hillshadeHighlightColor"},{"text":" uses colorTheme from the style or not.","type":"text"},{"text":" ","type":"text"},{"text":"By default it will use color defined by the root theme in the style.","type":"text"}],"title":"hillshadeHighlightColorUseTheme(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeHighlightColorUseTheme(_:)-8yp16","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hillshadeHighlightColorUseTheme","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ColorUseTheme","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps13ColorUseThemeV"},{"text":") -> ","kind":"text"},{"text":"HillshadeLayer","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps14HillshadeLayerV"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/hillshadeIlluminationAnchor(_:)-1z89n":{"abstract":[{"type":"text","text":"Direction of light source when map is rotated."},{"type":"text","text":" "},{"type":"text","text":"Default value: “viewport”."}],"role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hillshadeIlluminationAnchor"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps3ExpV","text":"Exp"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps14HillshadeLayerV","text":"HillshadeLayer"}],"title":"hillshadeIlluminationAnchor(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeIlluminationAnchor(_:)-1z89n","url":"\/documentation\/mapboxmaps\/hillshadelayer\/hillshadeilluminationanchor(_:)-1z89n"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/hillshadeAccentColor(_:)-2b6md":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeAccentColor(_:)-2b6md","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hillshadeAccentColor"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"StyleColor","preciseIdentifier":"s:10MapboxMaps10StyleColorV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HillshadeLayer","preciseIdentifier":"s:10MapboxMaps14HillshadeLayerV"}],"abstract":[{"text":"The shading color used to accentuate rugged terrain like sharp cliffs and gorges.","type":"text"},{"text":" ","type":"text"},{"text":"Default value: “#000000”.","type":"text"}],"url":"\/documentation\/mapboxmaps\/hillshadelayer\/hillshadeaccentcolor(_:)-2b6md","title":"hillshadeAccentColor(_:)","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleEncodable":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleEncodable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StyleEncodable","kind":"identifier"}],"title":"StyleEncodable","type":"topic","abstract":[{"type":"text","text":"A protocol describing a style-related entity that can be encoded."}],"url":"\/documentation\/mapboxmaps\/styleencodable","navigatorTitle":[{"text":"StyleEncodable","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/minZoom(_:)":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/hillshadelayer\/minzoom(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/minZoom(_:)","title":"minZoom(_:)","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minZoom","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps14HillshadeLayerV","text":"HillshadeLayer","kind":"typeIdentifier"}],"abstract":[{"text":"The minimum zoom level for the layer. At zoom levels less than the minzoom, the layer will be hidden.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/slot":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/hillshadelayer\/slot","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/slot","title":"slot","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"slot","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps4SlotV","text":"Slot","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"text":"The slot this layer is assigned to. If specified, and a slot with that name exists, it will be placed at that position in the layer order.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/hillshadeHighlightColorUseTheme(_:)-3u4o6":{"tags":[{"type":"spi","text":"SPI"}],"kind":"symbol","role":"symbol","title":"hillshadeHighlightColorUseTheme(_:)","abstract":[{"text":"This property defines whether the ","type":"text"},{"type":"codeVoice","code":"hillshadeHighlightColor"},{"text":" uses colorTheme from the style or not.","type":"text"},{"text":" ","type":"text"},{"text":"By default it will use color defined by the root theme in the style.","type":"text"}],"url":"\/documentation\/mapboxmaps\/hillshadelayer\/hillshadehighlightcolorusetheme(_:)-3u4o6","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hillshadeHighlightColorUseTheme"},{"kind":"text","text":"("},{"preciseIdentifier":"s:10MapboxMaps3ExpV","kind":"typeIdentifier","text":"Exp"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:10MapboxMaps14HillshadeLayerV","kind":"typeIdentifier","text":"HillshadeLayer"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeHighlightColorUseTheme(_:)-3u4o6"},"doc://com.mapbox.MapboxMaps/SE":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SE","type":"unresolvable","title":"Swift.Encodable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ClipLayerTypes":{"title":"ClipLayerTypes","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ClipLayerTypes","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/cliplayertypes","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClipLayerTypes","navigatorTitle":[{"text":"ClipLayerTypes","kind":"identifier"}],"abstract":[{"type":"text","text":"Layer types that will also be removed if fallen below this clip layer."}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/hillshadeExaggeration":{"url":"\/documentation\/mapboxmaps\/hillshadelayer\/hillshadeexaggeration","role":"symbol","title":"hillshadeExaggeration","abstract":[{"text":"Intensity of the hillshade","type":"text"},{"text":" ","type":"text"},{"text":"Default value: 0.5. Value range: [0, 1]","type":"text"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hillshadeExaggeration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Value","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps5ValueO"},{"text":"<","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":">?","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeExaggeration"},"doc://com.mapbox.MapboxMaps/s8CopyableP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s8CopyableP","title":"Swift.Copyable","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/hillshadeEmissiveStrength(_:)-8nh0q":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeEmissiveStrength(_:)-8nh0q","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hillshadeEmissiveStrength","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Exp","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps3ExpV"},{"text":") -> ","kind":"text"},{"text":"HillshadeLayer","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps14HillshadeLayerV"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/hillshadelayer\/hillshadeemissivestrength(_:)-8nh0q","abstract":[{"text":"Controls the intensity of light emitted on the source features.","type":"text"},{"text":" ","type":"text"},{"text":"Default value: 0. Minimum value: 0. The unit of hillshadeEmissiveStrength is in intensity.","type":"text"}],"title":"hillshadeEmissiveStrength(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/hillshadeExaggerationTransition":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hillshadeExaggerationTransition","kind":"identifier"},{"text":": ","kind":"text"},{"text":"StyleTransition","preciseIdentifier":"s:10MapboxMaps15StyleTransitionV","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeExaggerationTransition","url":"\/documentation\/mapboxmaps\/hillshadelayer\/hillshadeexaggerationtransition","abstract":[{"text":"Transition options for ","type":"text"},{"type":"codeVoice","code":"hillshadeExaggeration"},{"text":".","type":"text"}],"type":"topic","title":"hillshadeExaggerationTransition","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LocationIndicatorLayer":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationIndicatorLayer","title":"LocationIndicatorLayer","role":"symbol","url":"\/documentation\/mapboxmaps\/locationindicatorlayer","abstract":[{"text":"Location Indicator layer.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationIndicatorLayer","kind":"identifier"}],"navigatorTitle":[{"text":"LocationIndicatorLayer","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/hillshadeShadowColorTransition":{"abstract":[{"type":"text","text":"Transition options for "},{"code":"hillshadeShadowColor","type":"codeVoice"},{"type":"text","text":"."}],"type":"topic","url":"\/documentation\/mapboxmaps\/hillshadelayer\/hillshadeshadowcolortransition","title":"hillshadeShadowColorTransition","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hillshadeShadowColorTransition","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps15StyleTransitionV","text":"StyleTransition","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeShadowColorTransition","role":"symbol","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/maxZoom(_:)":{"role":"symbol","title":"maxZoom(_:)","abstract":[{"text":"The maximum zoom level for the layer. At zoom levels equal to or greater than the maxzoom, the layer will be hidden.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxZoom"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HillshadeLayer","preciseIdentifier":"s:10MapboxMaps14HillshadeLayerV"}],"url":"\/documentation\/mapboxmaps\/hillshadelayer\/maxzoom(_:)","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/maxZoom(_:)","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"kind":"article","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","url":"\/documentation\/overview","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/source(_:)":{"abstract":[{"text":"Name of a source description to be used for this layer.","type":"text"},{"text":" ","type":"text"},{"text":"Required for all layer types except ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/BackgroundLayer","type":"reference","isActive":true},{"text":", ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SkyLayer","type":"reference","isActive":true},{"text":", and ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationIndicatorLayer","type":"reference","isActive":true},{"text":".","type":"text"}],"url":"\/documentation\/mapboxmaps\/hillshadelayer\/source(_:)","role":"symbol","kind":"symbol","title":"source(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/source(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"source","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps14HillshadeLayerV","text":"HillshadeLayer","kind":"typeIdentifier"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerType":{"kind":"symbol","role":"symbol","abstract":[{"text":"Struct of supported Layer rendering types","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LayerType"}],"url":"\/documentation\/mapboxmaps\/layertype","title":"LayerType","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType","navigatorTitle":[{"kind":"identifier","text":"LayerType"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/encode(to:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/encode(to:)","kind":"symbol","title":"encode(to:)","role":"symbol","abstract":[],"url":"\/documentation\/mapboxmaps\/hillshadelayer\/encode(to:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"encode","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"Encoder","preciseIdentifier":"s:s7EncoderP","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/hillshadeShadowColor(_:)-1han1":{"url":"\/documentation\/mapboxmaps\/hillshadelayer\/hillshadeshadowcolor(_:)-1han1","role":"symbol","title":"hillshadeShadowColor(_:)","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeShadowColor(_:)-1han1","abstract":[{"type":"text","text":"The shading color of areas that face away from the light source."},{"type":"text","text":" "},{"type":"text","text":"Default value: “#000000”."}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hillshadeShadowColor","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Exp","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps3ExpV"},{"text":") -> ","kind":"text"},{"text":"HillshadeLayer","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps14HillshadeLayerV"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ClipLayer":{"title":"ClipLayer","kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/cliplayer","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClipLayer"}],"abstract":[{"type":"text","text":"Layer that removes 3D content from map."}],"navigatorTitle":[{"kind":"identifier","text":"ClipLayer"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClipLayer"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/minZoom":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minZoom","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/minZoom","url":"\/documentation\/mapboxmaps\/hillshadelayer\/minzoom","title":"minZoom","abstract":[{"type":"text","text":"The minimum zoom level for the layer. At zoom levels less than the minzoom, the layer will be hidden."}],"kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/hillshadeShadowColorUseTheme(_:)-81qir":{"type":"topic","kind":"symbol","tags":[{"text":"SPI","type":"spi"}],"abstract":[{"text":"This property defines whether the ","type":"text"},{"type":"codeVoice","code":"hillshadeShadowColor"},{"text":" uses colorTheme from the style or not.","type":"text"},{"text":" ","type":"text"},{"text":"By default it will use color defined by the root theme in the style.","type":"text"}],"url":"\/documentation\/mapboxmaps\/hillshadelayer\/hillshadeshadowcolorusetheme(_:)-81qir","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeShadowColorUseTheme(_:)-81qir","title":"hillshadeShadowColorUseTheme(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hillshadeShadowColorUseTheme","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ColorUseTheme","preciseIdentifier":"s:10MapboxMaps13ColorUseThemeV","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"HillshadeLayer","preciseIdentifier":"s:10MapboxMaps14HillshadeLayerV","kind":"typeIdentifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/hillshadeAccentColorTransition":{"role":"symbol","kind":"symbol","url":"\/documentation\/mapboxmaps\/hillshadelayer\/hillshadeaccentcolortransition","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hillshadeAccentColorTransition","kind":"identifier"},{"text":": ","kind":"text"},{"text":"StyleTransition","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps15StyleTransitionV"},{"text":"?","kind":"text"}],"abstract":[{"text":"Transition options for ","type":"text"},{"code":"hillshadeAccentColor","type":"codeVoice"},{"text":".","type":"text"}],"title":"hillshadeAccentColorTransition","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeAccentColorTransition"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LineLayer":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineLayer","title":"LineLayer","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LineLayer","kind":"identifier"}],"navigatorTitle":[{"text":"LineLayer","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/linelayer","kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"A stroked line."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/id":{"url":"\/documentation\/mapboxmaps\/hillshadelayer\/id","role":"symbol","abstract":[{"type":"text","text":"Unique layer name"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/id","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"title":"id","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/hillshadeShadowColor(_:)-8wrgz":{"kind":"symbol","title":"hillshadeShadowColor(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hillshadeShadowColor","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps14HillshadeLayerV","text":"HillshadeLayer","kind":"typeIdentifier"}],"abstract":[{"text":"The shading color of areas that face away from the light source.","type":"text"},{"text":" ","type":"text"},{"text":"Default value: “#000000”.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeShadowColor(_:)-8wrgz","role":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/hillshadelayer\/hillshadeshadowcolor(_:)-8wrgz"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/hillshadeHighlightColorTransition(_:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeHighlightColorTransition(_:)","title":"hillshadeHighlightColorTransition(_:)","url":"\/documentation\/mapboxmaps\/hillshadelayer\/hillshadehighlightcolortransition(_:)","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hillshadeHighlightColorTransition"},{"kind":"text","text":"("},{"preciseIdentifier":"s:10MapboxMaps15StyleTransitionV","kind":"typeIdentifier","text":"StyleTransition"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:10MapboxMaps14HillshadeLayerV","kind":"typeIdentifier","text":"HillshadeLayer"}],"abstract":[{"type":"text","text":"Transition property for "},{"code":"hillshadeHighlightColor","type":"codeVoice"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/BackgroundLayer":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/BackgroundLayer","title":"BackgroundLayer","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"BackgroundLayer","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/backgroundlayer","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BackgroundLayer","kind":"identifier"}],"abstract":[{"text":"The background color or pattern of the map.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerMapProjection":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerMapProjection","kind":"symbol","abstract":[],"title":"CustomLayerMapProjection","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomLayerMapProjection","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/customlayermapprojection","navigatorTitle":[{"text":"CustomLayerMapProjection","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayer":{"title":"CustomLayer","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CustomLayer"}],"tags":[{"type":"spi","text":"SPI"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomLayer"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayer","url":"\/documentation\/mapboxmaps\/customlayer","type":"topic","kind":"symbol","abstract":[{"text":"Layer with custom rendering implementation","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CircleLayer":{"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CircleLayer"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CircleLayer","navigatorTitle":[{"kind":"identifier","text":"CircleLayer"}],"url":"\/documentation\/mapboxmaps\/circlelayer","kind":"symbol","abstract":[{"text":"A filled circle.","type":"text"}],"type":"topic","title":"CircleLayer"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/filter(_:)":{"url":"\/documentation\/mapboxmaps\/hillshadelayer\/filter(_:)","type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/filter(_:)","abstract":[{"text":"An expression specifying conditions on source features.","type":"text"},{"text":" ","type":"text"},{"text":"Only features that match the filter are displayed.","type":"text"}],"role":"symbol","title":"filter(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"filter","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Exp","preciseIdentifier":"s:10MapboxMaps3ExpV","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"HillshadeLayer","preciseIdentifier":"s:10MapboxMaps14HillshadeLayerV","kind":"typeIdentifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/hillshadeHighlightColor(_:)-84cah":{"abstract":[{"type":"text","text":"The shading color of areas that faces towards the light source."},{"type":"text","text":" "},{"type":"text","text":"Default value: “#FFFFFF”."}],"url":"\/documentation\/mapboxmaps\/hillshadelayer\/hillshadehighlightcolor(_:)-84cah","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hillshadeHighlightColor","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps10StyleColorV","text":"StyleColor","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps14HillshadeLayerV","text":"HillshadeLayer","kind":"typeIdentifier"}],"title":"hillshadeHighlightColor(_:)","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeHighlightColor(_:)-84cah"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerInfo":{"abstract":[{"type":"text","text":"Information about a layer"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerInfo","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LayerInfo"}],"navigatorTitle":[{"kind":"identifier","text":"LayerInfo"}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/layerinfo","title":"LayerInfo"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/hillshadeShadowColor(_:)-1jg80":{"url":"\/documentation\/mapboxmaps\/hillshadelayer\/hillshadeshadowcolor(_:)-1jg80","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hillshadeShadowColor","kind":"identifier"},{"text":"(","kind":"text"},{"text":"StyleColor","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps10StyleColorV"},{"text":") -> ","kind":"text"},{"text":"HillshadeLayer","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps14HillshadeLayerV"}],"title":"hillshadeShadowColor(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeShadowColor(_:)-1jg80","abstract":[{"text":"The shading color of areas that face away from the light source.","type":"text"},{"text":" ","type":"text"},{"text":"Default value: “#000000”.","type":"text"}],"type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerRenderParameters":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters","title":"CustomLayerRenderParameters","url":"\/documentation\/mapboxmaps\/customlayerrenderparameters","navigatorTitle":[{"text":"CustomLayerRenderParameters","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Parameters that define the current camera position for a "},{"type":"codeVoice","code":"CustomLayerHost::render()"},{"type":"text","text":" function."}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomLayerRenderParameters","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/hillshadeShadowColorTransition(_:)":{"title":"hillshadeShadowColorTransition(_:)","abstract":[{"text":"Transition property for ","type":"text"},{"type":"codeVoice","code":"hillshadeShadowColor"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hillshadeShadowColorTransition","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps15StyleTransitionV","text":"StyleTransition","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps14HillshadeLayerV","text":"HillshadeLayer","kind":"typeIdentifier"}],"url":"\/documentation\/mapboxmaps\/hillshadelayer\/hillshadeshadowcolortransition(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeShadowColorTransition(_:)","kind":"symbol","type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/hillshadeHighlightColor":{"url":"\/documentation\/mapboxmaps\/hillshadelayer\/hillshadehighlightcolor","type":"topic","kind":"symbol","abstract":[{"text":"The shading color of areas that faces towards the light source.","type":"text"},{"text":" ","type":"text"},{"text":"Default value: “#FFFFFF”.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeHighlightColor","title":"hillshadeHighlightColor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hillshadeHighlightColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Value","preciseIdentifier":"s:10MapboxMaps5ValueO","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"StyleColor","preciseIdentifier":"s:10MapboxMaps10StyleColorV","kind":"typeIdentifier"},{"text":">?","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerAtPosition":{"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LayerAtPosition"}],"title":"LayerAtPosition","abstract":[],"url":"\/documentation\/mapboxmaps\/layeratposition","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerAtPosition","navigatorTitle":[{"kind":"identifier","text":"LayerAtPosition"}]},"doc://com.mapbox.MapboxMaps/Se":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/Se","title":"Swift.Decodable","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerRenderConfiguration":{"type":"topic","title":"CustomLayerRenderConfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomLayerRenderConfiguration","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/customlayerrenderconfiguration","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderConfiguration","navigatorTitle":[{"text":"CustomLayerRenderConfiguration","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Note! This is an experimental feature. It can be changed or removed in future versions.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/hillshadeHighlightColor(_:)-6xzvs":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeHighlightColor(_:)-6xzvs","title":"hillshadeHighlightColor(_:)","abstract":[{"text":"The shading color of areas that faces towards the light source.","type":"text"},{"text":" ","type":"text"},{"text":"Default value: “#FFFFFF”.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hillshadeHighlightColor","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":") -> ","kind":"text"},{"text":"HillshadeLayer","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps14HillshadeLayerV"}],"role":"symbol","kind":"symbol","url":"\/documentation\/mapboxmaps\/hillshadelayer\/hillshadehighlightcolor(_:)-6xzvs"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/hillshadeHighlightColor(_:)-1iz83":{"role":"symbol","abstract":[{"text":"The shading color of areas that faces towards the light source.","type":"text"},{"text":" ","type":"text"},{"text":"Default value: “#FFFFFF”.","type":"text"}],"url":"\/documentation\/mapboxmaps\/hillshadelayer\/hillshadehighlightcolor(_:)-1iz83","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeHighlightColor(_:)-1iz83","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hillshadeHighlightColor","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Exp","preciseIdentifier":"s:10MapboxMaps3ExpV","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"HillshadeLayer","preciseIdentifier":"s:10MapboxMaps14HillshadeLayerV","kind":"typeIdentifier"}],"kind":"symbol","title":"hillshadeHighlightColor(_:)","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/hillshadeExaggeration(_:)-90tin":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeExaggeration(_:)-90tin","url":"\/documentation\/mapboxmaps\/hillshadelayer\/hillshadeexaggeration(_:)-90tin","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hillshadeExaggeration","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Exp","preciseIdentifier":"s:10MapboxMaps3ExpV","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"HillshadeLayer","preciseIdentifier":"s:10MapboxMaps14HillshadeLayerV","kind":"typeIdentifier"}],"title":"hillshadeExaggeration(_:)","abstract":[{"type":"text","text":"Intensity of the hillshade"},{"type":"text","text":" "},{"type":"text","text":"Default value: 0.5. Value range: [0, 1]"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/hillshadeHighlightColorTransition":{"abstract":[{"text":"Transition options for ","type":"text"},{"type":"codeVoice","code":"hillshadeHighlightColor"},{"text":".","type":"text"}],"title":"hillshadeHighlightColorTransition","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeHighlightColorTransition","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hillshadeHighlightColorTransition","kind":"identifier"},{"text":": ","kind":"text"},{"text":"StyleTransition","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps15StyleTransitionV"},{"text":"?","kind":"text"}],"url":"\/documentation\/mapboxmaps\/hillshadelayer\/hillshadehighlightcolortransition"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/Equatable-Implementations":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/Equatable-Implementations","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/hillshadelayer\/equatable-implementations","type":"topic","title":"Equatable Implementations","kind":"article","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Slot":{"abstract":[{"text":"A pre-specified location in the style where layer will be added to","type":"text"},{"text":" ","type":"text"},{"text":"(such as on top of existing land layers, but below all labels).","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"Slot","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Slot","url":"\/documentation\/mapboxmaps\/slot","title":"Slot","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Slot","kind":"identifier"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/source":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/source","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"source","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"abstract":[{"text":"Name of a source description to be used for this layer.","type":"text"},{"text":" ","type":"text"},{"text":"Required for all layer types except ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/BackgroundLayer","type":"reference","isActive":true},{"text":", ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SkyLayer","type":"reference","isActive":true},{"text":", and ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LocationIndicatorLayer","type":"reference","isActive":true},{"text":".","type":"text"}],"type":"topic","title":"source","kind":"symbol","url":"\/documentation\/mapboxmaps\/hillshadelayer\/source"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/hillshadeIlluminationDirection(_:)-mdve":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hillshadeIlluminationDirection","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"HillshadeLayer","preciseIdentifier":"s:10MapboxMaps14HillshadeLayerV","kind":"typeIdentifier"}],"title":"hillshadeIlluminationDirection(_:)","kind":"symbol","url":"\/documentation\/mapboxmaps\/hillshadelayer\/hillshadeilluminationdirection(_:)-mdve","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeIlluminationDirection(_:)-mdve","abstract":[{"type":"text","text":"The direction of the light source used to generate the hillshading with 0 as the top of the viewport if "},{"type":"codeVoice","code":"hillshade-illumination-anchor"},{"type":"text","text":" is set to "},{"type":"codeVoice","code":"viewport"},{"type":"text","text":" and due north if "},{"type":"codeVoice","code":"hillshade-illumination-anchor"},{"type":"text","text":" is set to "},{"type":"codeVoice","code":"map"},{"type":"text","text":" and no 3d lights enabled. If "},{"type":"codeVoice","code":"hillshade-illumination-anchor"},{"type":"text","text":" is set to "},{"type":"codeVoice","code":"map"},{"type":"text","text":" and 3d lights enabled, the direction from 3d lights is used instead."},{"type":"text","text":" "},{"type":"text","text":"Default value: 335. Value range: [0, 359]"}],"type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/SQ":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/hillshadeAccentColor(_:)-6c9l9":{"abstract":[{"type":"text","text":"The shading color used to accentuate rugged terrain like sharp cliffs and gorges."},{"text":" ","type":"text"},{"text":"Default value: “#000000”.","type":"text"}],"type":"topic","title":"hillshadeAccentColor(_:)","url":"\/documentation\/mapboxmaps\/hillshadelayer\/hillshadeaccentcolor(_:)-6c9l9","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeAccentColor(_:)-6c9l9","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hillshadeAccentColor"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HillshadeLayer","preciseIdentifier":"s:10MapboxMaps14HillshadeLayerV"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SymbolLayer":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolLayer","navigatorTitle":[{"kind":"identifier","text":"SymbolLayer"}],"kind":"symbol","title":"SymbolLayer","url":"\/documentation\/mapboxmaps\/symbollayer","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SymbolLayer","kind":"identifier"}],"abstract":[{"text":"An icon or a text label.","type":"text"}],"role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/hillshadeIlluminationAnchor(_:)-42w4u":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hillshadeIlluminationAnchor","kind":"identifier"},{"text":"(","kind":"text"},{"text":"HillshadeIlluminationAnchor","preciseIdentifier":"s:10MapboxMaps27HillshadeIlluminationAnchorV","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"HillshadeLayer","preciseIdentifier":"s:10MapboxMaps14HillshadeLayerV","kind":"typeIdentifier"}],"url":"\/documentation\/mapboxmaps\/hillshadelayer\/hillshadeilluminationanchor(_:)-42w4u","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeIlluminationAnchor(_:)-42w4u","role":"symbol","type":"topic","title":"hillshadeIlluminationAnchor(_:)","abstract":[{"text":"Direction of light source when map is rotated.","type":"text"},{"text":" ","type":"text"},{"text":"Default value: “viewport”.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/hillshadeIlluminationDirection":{"kind":"symbol","abstract":[{"text":"The direction of the light source used to generate the hillshading with 0 as the top of the viewport if ","type":"text"},{"type":"codeVoice","code":"hillshade-illumination-anchor"},{"text":" is set to ","type":"text"},{"type":"codeVoice","code":"viewport"},{"text":" and due north if ","type":"text"},{"type":"codeVoice","code":"hillshade-illumination-anchor"},{"text":" is set to ","type":"text"},{"type":"codeVoice","code":"map"},{"text":" and no 3d lights enabled. If ","type":"text"},{"type":"codeVoice","code":"hillshade-illumination-anchor"},{"text":" is set to ","type":"text"},{"type":"codeVoice","code":"map"},{"text":" and 3d lights enabled, the direction from 3d lights is used instead.","type":"text"},{"text":" ","type":"text"},{"text":"Default value: 335. Value range: [0, 359]","type":"text"}],"url":"\/documentation\/mapboxmaps\/hillshadelayer\/hillshadeilluminationdirection","title":"hillshadeIlluminationDirection","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeIlluminationDirection","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hillshadeIlluminationDirection","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps5ValueO","text":"Value","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":">?","kind":"text"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterLayer":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"RasterLayer","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/rasterlayer","abstract":[{"text":"Raster map textures such as satellite imagery.","type":"text"}],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RasterLayer","kind":"identifier"}],"title":"RasterLayer","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterLayer"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/sourceLayer":{"type":"topic","url":"\/documentation\/mapboxmaps\/hillshadelayer\/sourcelayer","title":"sourceLayer","abstract":[{"text":"Layer to use from a vector tile source.","type":"text"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sourceLayer","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/sourceLayer"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/hillshadeShadowColorUseTheme(_:)-5xagu":{"type":"topic","abstract":[{"type":"text","text":"This property defines whether the "},{"type":"codeVoice","code":"hillshadeShadowColor"},{"type":"text","text":" uses colorTheme from the style or not."},{"type":"text","text":" "},{"type":"text","text":"By default it will use color defined by the root theme in the style."}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeShadowColorUseTheme(_:)-5xagu","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hillshadeShadowColorUseTheme","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Exp","preciseIdentifier":"s:10MapboxMaps3ExpV","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"HillshadeLayer","preciseIdentifier":"s:10MapboxMaps14HillshadeLayerV","kind":"typeIdentifier"}],"title":"hillshadeShadowColorUseTheme(_:)","tags":[{"type":"spi","text":"SPI"}],"url":"\/documentation\/mapboxmaps\/hillshadelayer\/hillshadeshadowcolorusetheme(_:)-5xagu"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/hillshadeEmissiveStrength":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeEmissiveStrength","role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hillshadeEmissiveStrength","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Value","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps5ValueO"},{"text":"<","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":">?","kind":"text"}],"title":"hillshadeEmissiveStrength","abstract":[{"type":"text","text":"Controls the intensity of light emitted on the source features."},{"type":"text","text":" "},{"type":"text","text":"Default value: 0. Minimum value: 0. The unit of hillshadeEmissiveStrength is in intensity."}],"url":"\/documentation\/mapboxmaps\/hillshadelayer\/hillshadeemissivestrength"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HeatmapLayer":{"role":"symbol","title":"HeatmapLayer","kind":"symbol","url":"\/documentation\/mapboxmaps\/heatmaplayer","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeatmapLayer"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HeatmapLayer","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HeatmapLayer"}],"abstract":[{"type":"text","text":"A heatmap."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapStyleContent":{"url":"\/documentation\/mapboxmaps\/mapstylecontent","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapStyleContent","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapStyleContent","kind":"symbol","abstract":[{"type":"text","text":"A protocol used to create any type of  map style content, such as layers, sources, lighting and others."}],"type":"topic","title":"MapStyleContent","role":"symbol","navigatorTitle":[{"text":"MapStyleContent","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/init(from:)":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/init(from:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"Decoder","preciseIdentifier":"s:s7DecoderP","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"kind":"symbol","type":"topic","title":"init(from:)","abstract":[],"url":"\/documentation\/mapboxmaps\/hillshadelayer\/init(from:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SkyLayer":{"abstract":[{"text":"A spherical dome around the map that is always rendered behind all other layers.","type":"text"},{"text":" ","type":"text"},{"text":"Warning: As of v10.6.0, ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Atmosphere","type":"reference","isActive":true},{"text":" is the preferred method for atmospheric styling. Sky layer is not supported by the globe projection, and will be phased out in future major release.","type":"text"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SkyLayer","kind":"identifier"}],"navigatorTitle":[{"text":"SkyLayer","kind":"identifier"}],"kind":"symbol","type":"topic","title":"SkyLayer","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SkyLayer","url":"\/documentation\/mapboxmaps\/skylayer"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/hillshadeIlluminationAnchor":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hillshadeIlluminationAnchor"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10MapboxMaps5ValueO","kind":"typeIdentifier","text":"Value"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:10MapboxMaps27HillshadeIlluminationAnchorV","kind":"typeIdentifier","text":"HillshadeIlluminationAnchor"},{"kind":"text","text":">?"}],"title":"hillshadeIlluminationAnchor","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeIlluminationAnchor","url":"\/documentation\/mapboxmaps\/hillshadelayer\/hillshadeilluminationanchor","type":"topic","abstract":[{"type":"text","text":"Direction of light source when map is rotated."},{"type":"text","text":" "},{"type":"text","text":"Default value: “viewport”."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/hillshadeAccentColor":{"abstract":[{"text":"The shading color used to accentuate rugged terrain like sharp cliffs and gorges.","type":"text"},{"text":" ","type":"text"},{"text":"Default value: “#000000”.","type":"text"}],"role":"symbol","type":"topic","title":"hillshadeAccentColor","kind":"symbol","url":"\/documentation\/mapboxmaps\/hillshadelayer\/hillshadeaccentcolor","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeAccentColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hillshadeAccentColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Value","preciseIdentifier":"s:10MapboxMaps5ValueO"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"StyleColor","preciseIdentifier":"s:10MapboxMaps10StyleColorV"},{"kind":"text","text":">?"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/sourceLayer(_:)":{"title":"sourceLayer(_:)","url":"\/documentation\/mapboxmaps\/hillshadelayer\/sourcelayer(_:)","type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/sourceLayer(_:)","abstract":[{"text":"Layer to use from a vector tile source.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sourceLayer","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps14HillshadeLayerV","text":"HillshadeLayer","kind":"typeIdentifier"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/hillshadeExaggeration(_:)-274oz":{"url":"\/documentation\/mapboxmaps\/hillshadelayer\/hillshadeexaggeration(_:)-274oz","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeExaggeration(_:)-274oz","type":"topic","kind":"symbol","title":"hillshadeExaggeration(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hillshadeExaggeration","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps14HillshadeLayerV","text":"HillshadeLayer","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Intensity of the hillshade"},{"type":"text","text":" "},{"type":"text","text":"Default value: 0.5. Value range: [0, 1]"}],"role":"symbol"},"https://www.mapbox.com/mapbox-gl-style-spec/#layers-hillshade":{"url":"https:\/\/www.mapbox.com\/mapbox-gl-style-spec\/#layers-hillshade","identifier":"https:\/\/www.mapbox.com\/mapbox-gl-style-spec\/#layers-hillshade","type":"link","title":"Mapbox Style Specification","titleInlineContent":[{"type":"text","text":"Mapbox Style Specification"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layers":{"role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers","type":"topic","title":"Layers","kind":"article","url":"\/documentation\/mapboxmaps\/layers","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ElevationData":{"navigatorTitle":[{"kind":"identifier","text":"ElevationData"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ElevationData","url":"\/documentation\/mapboxmaps\/elevationdata","type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Interface that provides access to elevation data."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ElevationData"}],"title":"ElevationData"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/filter":{"url":"\/documentation\/mapboxmaps\/hillshadelayer\/filter","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/filter","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"filter","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Exp","preciseIdentifier":"s:10MapboxMaps3ExpV","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"An expression specifying conditions on source features."},{"type":"text","text":" "},{"type":"text","text":"Only features that match the filter are displayed."}],"role":"symbol","title":"filter"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/hillshadeEmissiveStrengthTransition":{"title":"hillshadeEmissiveStrengthTransition","abstract":[{"text":"Transition options for ","type":"text"},{"type":"codeVoice","code":"hillshadeEmissiveStrength"},{"text":".","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hillshadeEmissiveStrengthTransition","kind":"identifier"},{"text":": ","kind":"text"},{"text":"StyleTransition","preciseIdentifier":"s:10MapboxMaps15StyleTransitionV","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/mapboxmaps\/hillshadelayer\/hillshadeemissivestrengthtransition","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeEmissiveStrengthTransition","kind":"symbol","role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layer":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Layer"}],"url":"\/documentation\/mapboxmaps\/layer","title":"Layer","navigatorTitle":[{"kind":"identifier","text":"Layer"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FillExtrusionLayer":{"abstract":[{"text":"An extruded (3D) polygon.","type":"text"}],"type":"topic","url":"\/documentation\/mapboxmaps\/fillextrusionlayer","role":"symbol","navigatorTitle":[{"text":"FillExtrusionLayer","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FillExtrusionLayer","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillExtrusionLayer","kind":"symbol","title":"FillExtrusionLayer"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/init(id:source:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"source","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"kind":"symbol","url":"\/documentation\/mapboxmaps\/hillshadelayer\/init(id:source:)","title":"init(id:source:)","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/init(id:source:)","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SlotLayer":{"url":"\/documentation\/mapboxmaps\/slotlayer","title":"SlotLayer","role":"symbol","type":"topic","abstract":[{"text":"Marks the position of a slot.","type":"text"}],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SlotLayer","kind":"identifier"}],"navigatorTitle":[{"text":"SlotLayer","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SlotLayer"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/visibility":{"title":"visibility","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"visibility","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Value","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps5ValueO"},{"text":"<","kind":"text"},{"text":"Visibility","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps10VisibilityO"},{"text":">","kind":"text"}],"abstract":[{"text":"Whether this layer is displayed.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/visibility","url":"\/documentation\/mapboxmaps\/hillshadelayer\/visibility","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/hillshadeShadowColor":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeShadowColor","abstract":[{"type":"text","text":"The shading color of areas that face away from the light source."},{"type":"text","text":" "},{"type":"text","text":"Default value: “#000000”."}],"role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hillshadeShadowColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Value","preciseIdentifier":"s:10MapboxMaps5ValueO","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"StyleColor","preciseIdentifier":"s:10MapboxMaps10StyleColorV","kind":"typeIdentifier"},{"text":">?","kind":"text"}],"url":"\/documentation\/mapboxmaps\/hillshadelayer\/hillshadeshadowcolor","type":"topic","title":"hillshadeShadowColor"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/hillshadeExaggerationTransition(_:)":{"title":"hillshadeExaggerationTransition(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeExaggerationTransition(_:)","role":"symbol","url":"\/documentation\/mapboxmaps\/hillshadelayer\/hillshadeexaggerationtransition(_:)","abstract":[{"type":"text","text":"Transition property for "},{"type":"codeVoice","code":"hillshadeExaggeration"}],"kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hillshadeExaggerationTransition","kind":"identifier"},{"text":"(","kind":"text"},{"text":"StyleTransition","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps15StyleTransitionV"},{"text":") -> ","kind":"text"},{"text":"HillshadeLayer","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps14HillshadeLayerV"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/StyleEncodable-Implementations":{"url":"\/documentation\/mapboxmaps\/hillshadelayer\/styleencodable-implementations","role":"collectionGroup","title":"StyleEncodable Implementations","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/StyleEncodable-Implementations","abstract":[],"kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/hillshadeAccentColor(_:)-58mi5":{"title":"hillshadeAccentColor(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hillshadeAccentColor"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Exp","preciseIdentifier":"s:10MapboxMaps3ExpV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HillshadeLayer","preciseIdentifier":"s:10MapboxMaps14HillshadeLayerV"}],"type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/hillshadelayer\/hillshadeaccentcolor(_:)-58mi5","abstract":[{"text":"The shading color used to accentuate rugged terrain like sharp cliffs and gorges.","type":"text"},{"text":" ","type":"text"},{"text":"Default value: “#000000”.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeAccentColor(_:)-58mi5","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/Layer-Implementations":{"abstract":[],"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/Layer-Implementations","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/hillshadelayer\/layer-implementations","type":"topic","title":"Layer Implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","kind":"symbol","title":"MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelLayer":{"type":"topic","abstract":[{"text":"A layer to render 3D Models.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelLayer","kind":"symbol","tags":[{"type":"spi","text":"SPI"}],"navigatorTitle":[{"text":"ModelLayer","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/modellayer","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ModelLayer","kind":"identifier"}],"title":"ModelLayer","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeLayer/hillshadeAccentColorTransition(_:)":{"kind":"symbol","title":"hillshadeAccentColorTransition(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hillshadeAccentColorTransition"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps15StyleTransitionV","text":"StyleTransition"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps14HillshadeLayerV","text":"HillshadeLayer"}],"abstract":[{"type":"text","text":"Transition property for "},{"type":"codeVoice","code":"hillshadeAccentColor"}],"url":"\/documentation\/mapboxmaps\/hillshadelayer\/hillshadeaccentcolortransition(_:)","type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeLayer\/hillshadeAccentColorTransition(_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost\/title","op":"replace","value":"MBMCustomLayerHost"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost\/fragments","op":"replace","value":[{"text":"MBMCustomLayerHost","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost\/navigatorTitle","op":"replace","value":[{"text":"MBMCustomLayerHost","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerMapProjection\/title","op":"replace","value":"MBMCustomLayerMapProjection"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerMapProjection\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMCustomLayerMapProjection"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerMapProjection\/navigatorTitle","op":"replace","value":[{"text":"MBMCustomLayerMapProjection","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/title","op":"replace","value":"MBMCustomLayerRenderParameters"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMCustomLayerRenderParameters"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/navigatorTitle","op":"replace","value":[{"text":"MBMCustomLayerRenderParameters","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderConfiguration\/title","op":"replace","value":"MBMCustomLayerRenderConfiguration"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderConfiguration\/fragments","op":"replace","value":[{"text":"MBMCustomLayerRenderConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMCustomLayerRenderConfiguration"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ElevationData\/title","op":"replace","value":"MBMElevationData"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ElevationData\/fragments","op":"replace","value":[{"text":"MBMElevationData","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ElevationData\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMElevationData"}]}]}]}