{"metadata":{"title":"tileStoreUsageMode","symbolKind":"property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"tileStoreUsageMode","kind":"identifier"},{"kind":"text","text":": "},{"text":"TileStoreUsageMode","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMTileStoreUsageMode"}],"modules":[{"name":"MapboxMaps"}],"externalID":"s:10MapboxMaps0aB7OptionsO18tileStoreUsageModeSo07MBMTileefG0VvpZ","roleHeading":"Type Property","role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"tileStoreUsageMode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@MBMTileStoreUsageMode","kind":"typeIdentifier","text":"TileStoreUsageMode","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreUsageMode"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","abstract":[{"type":"text","text":"The tile store usage mode for the Maps API objects. Default is "},{"type":"codeVoice","code":"readOnly"},{"type":"text","text":"."}],"sections":[],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMapsOptions\/tileStoreUsageMode","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Settings-and-Constants","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMapsOptions"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/mapboxmapsoptions\/tilestoreusagemode"]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","abstract":[],"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","kind":"article","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMapsOptions/tileStoreUsageMode":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tileStoreUsageMode","kind":"identifier"},{"kind":"text","text":": "},{"text":"TileStoreUsageMode","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMTileStoreUsageMode"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMapsOptions\/tileStoreUsageMode","title":"tileStoreUsageMode","role":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmapsoptions\/tilestoreusagemode","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The tile store usage mode for the Maps API objects. Default is "},{"code":"readOnly","type":"codeVoice"},{"text":".","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMapsOptions":{"role":"symbol","navigatorTitle":[{"text":"MapboxMapsOptions","kind":"identifier"}],"type":"topic","abstract":[{"text":"Configurations for the external resources that are used by Maps API object,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"such as maps data directory and base URL."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMapsOptions","title":"MapboxMapsOptions","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapboxMapsOptions"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmapsoptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Settings-and-Constants":{"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Settings-and-Constants","title":"Settings and Constants","type":"topic","abstract":[],"url":"\/documentation\/mapboxmaps\/settings-and-constants","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStoreUsageMode":{"role":"symbol","navigatorTitle":[{"text":"TileStoreUsageMode","kind":"identifier"}],"abstract":[{"type":"text","text":"Describes tile store usage modes."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileStoreUsageMode","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreUsageMode","title":"TileStoreUsageMode","kind":"symbol","url":"\/documentation\/mapboxmaps\/tilestoreusagemode"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileStoreUsageMode\/title","value":"MBMTileStoreUsageMode"},{"value":[{"kind":"identifier","text":"MBMTileStoreUsageMode"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileStoreUsageMode\/fragments"},{"value":[{"kind":"identifier","text":"MBMTileStoreUsageMode"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileStoreUsageMode\/navigatorTitle"}]}]}