{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/sourcedataloaded\/tileid"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/sourcedataloaded\/tileid"]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoaded"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tileId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CanonicalTileID","preciseIdentifier":"c:objc(cs)MBMCanonicalTileID","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"When the "},{"code":"type","type":"codeVoice"},{"type":"text","text":" of an event is "},{"code":"SourceDataLoadedType.Tile","type":"codeVoice"},{"type":"text","text":" the "},{"code":"tileId","type":"codeVoice"},{"type":"text","text":" "},{"type":"text","text":"property defines the tile coordinate."}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoaded\/tileId"},"metadata":{"modules":[{"name":"MapboxMaps"}],"roleHeading":"Instance Property","title":"tileId","navigatorTitle":[{"text":"tileId","kind":"identifier"}],"role":"symbol","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tileId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CanonicalTileID","preciseIdentifier":"c:objc(cs)MBMCanonicalTileID"},{"kind":"text","text":"?"}],"externalID":"c:objc(cs)MBMSourceDataLoaded(py)tileId"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceDataLoaded":{"role":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/sourcedataloaded","title":"SourceDataLoaded","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoaded","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"SourceDataLoaded"},{"type":"text","text":" event is emitted when source data is loaded."}],"navigatorTitle":[{"kind":"identifier","text":"SourceDataLoaded"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceDataLoaded"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","kind":"symbol","title":"MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","title":"Map events","url":"\/documentation\/mapboxmaps\/events","role":"collectionGroup","kind":"article","type":"topic","abstract":[{"type":"text","text":"The simplified diagram of the events emitted by the map is displayed below."}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"kind":"article","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","url":"\/documentation\/overview","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceDataLoaded/tileId":{"role":"symbol","url":"\/documentation\/mapboxmaps\/sourcedataloaded\/tileid","title":"tileId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tileId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMCanonicalTileID","text":"CanonicalTileID"},{"kind":"text","text":"?"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tileId"}],"abstract":[{"text":"When the ","type":"text"},{"code":"type","type":"codeVoice"},{"type":"text","text":" of an event is "},{"code":"SourceDataLoadedType.Tile","type":"codeVoice"},{"type":"text","text":" the "},{"code":"tileId","type":"codeVoice"},{"type":"text","text":" "},{"type":"text","text":"property defines the tile coordinate."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoaded\/tileId"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CanonicalTileID":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID","navigatorTitle":[{"text":"CanonicalTileID","kind":"identifier"}],"title":"CanonicalTileID","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CanonicalTileID","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxmaps\/canonicaltileid","abstract":[{"type":"text","text":"Represents a tile coordinate."}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"tileId"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"tileId"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMCanonicalTileID","text":"MBMCanonicalTileID","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID"},{"kind":"text","text":" * "},{"kind":"identifier","text":"tileId"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoaded\/title","op":"replace","value":"MBMSourceDataLoaded"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoaded\/fragments","op":"replace","value":[{"text":"MBMSourceDataLoaded","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoaded\/navigatorTitle","op":"replace","value":[{"text":"MBMSourceDataLoaded","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoaded~1tileId\/title","op":"replace","value":"tileId"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoaded~1tileId\/fragments","op":"replace","value":[{"kind":"identifier","text":"tileId"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/title","op":"replace","value":"MBMCanonicalTileID"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/fragments","op":"replace","value":[{"text":"MBMCanonicalTileID","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/navigatorTitle","op":"replace","value":[{"text":"MBMCanonicalTileID","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}