{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/cameraoptions"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"metadata":{"externalID":"s:10MapboxMaps13CameraOptionsV","navigatorTitle":[{"text":"CameraOptions","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"CameraOptions","kind":"identifier"}],"roleHeading":"Structure","modules":[{"name":"MapboxMaps"}],"title":"CameraOptions","symbolKind":"struct"},"seeAlsoSections":[{"generated":true,"title":"MapboxMap","anchor":"MapboxMap","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraState","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBounds","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBoundsOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Projection","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBoundsZoom","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateInfo","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ContextMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapCenterAltitudeMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometry","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometryConvertible"]}],"relationshipsSections":[{"type":"conformsTo","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/Se","doc:\/\/com.mapbox.MapboxMaps\/SE","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH","doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"],"kind":"relationships","title":"Conforms To"}],"kind":"symbol","identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraOptions","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraOptions\/init(cameraState:anchor:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraOptions\/init(center:padding:anchor:zoom:bearing:pitch:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraOptions\/init(from:)"],"generated":true,"anchor":"Initializers"},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraOptions\/anchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraOptions\/bearing","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraOptions\/center","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraOptions\/padding","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraOptions\/pitch","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraOptions\/zoom"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraOptions\/Equatable-Implementations"],"anchor":"Default-Implementations","title":"Default Implementations"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraOptions"}],"platforms":["iOS"]}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateBounds":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoordinateBounds"}],"role":"symbol","navigatorTitle":[{"text":"CoordinateBounds","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/coordinatebounds","type":"topic","title":"CoordinateBounds","abstract":[{"type":"text","text":"A rectangular area as measured on a two-dimensional map projection."}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraOptions/anchor":{"url":"\/documentation\/mapboxmaps\/cameraoptions\/anchor","kind":"symbol","abstract":[{"type":"text","text":"Point in the map’s coordinate system about which "},{"type":"codeVoice","code":"zoom"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"bearing"},{"type":"text","text":" should be applied. Mutually exclusive with "},{"type":"codeVoice","code":"center"},{"type":"text","text":". Defaults to (0, 0)."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"anchor","kind":"identifier"},{"kind":"text","text":": "},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraOptions\/anchor","title":"anchor","type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraOptions":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"CameraOptions","kind":"identifier"}],"title":"CameraOptions","type":"topic","url":"\/documentation\/mapboxmaps\/cameraoptions","abstract":[],"role":"symbol","navigatorTitle":[{"text":"CameraOptions","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraOptions"},"doc://com.mapbox.MapboxMaps/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraBounds":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBounds","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"CameraBounds","kind":"identifier"}],"title":"CameraBounds","url":"\/documentation\/mapboxmaps\/camerabounds","abstract":[{"text":"Holds information about camera bounds.","type":"text"}],"navigatorTitle":[{"text":"CameraBounds","kind":"identifier"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraOptions/init(cameraState:anchor:)":{"title":"init(cameraState:anchor:)","abstract":[],"role":"symbol","url":"\/documentation\/mapboxmaps\/cameraoptions\/init(camerastate:anchor:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"cameraState","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraState","preciseIdentifier":"s:10MapboxMaps11CameraStateV"},{"kind":"text","text":", "},{"text":"anchor","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraOptions\/init(cameraState:anchor:)","type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ContextMode":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ContextMode","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ContextMode","kind":"identifier"}],"title":"ContextMode","url":"\/documentation\/mapboxmaps\/contextmode","abstract":[{"text":"Describes the map context mode.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"We can make some optimizations if we know that the drawing context is not shared with other code."}],"navigatorTitle":[{"kind":"identifier","text":"ContextMode"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraOptions/bearing":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bearing","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@CLLocationDirection","kind":"typeIdentifier","text":"CLLocationDirection"},{"text":"?","kind":"text"}],"title":"bearing","kind":"symbol","url":"\/documentation\/mapboxmaps\/cameraoptions\/bearing","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraOptions\/bearing","abstract":[{"type":"text","text":"The bearing of the map, measured in degrees clockwise from true north. Defaults to 0."}],"role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraOptions/center":{"abstract":[{"type":"text","text":"The geographic coordinate that will be rendered at the midpoint of the area defined by "},{"type":"codeVoice","code":"padding"},{"text":". Defaults to (0, 0).","type":"text"}],"url":"\/documentation\/mapboxmaps\/cameraoptions\/center","title":"center","role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"center"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraOptions\/center","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap":{"kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/mapboxmap","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapboxMap"}],"title":"MapboxMap","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MapboxMap"}],"abstract":[{"text":"Provides access to the map model, including the camera, style, observable map events,","type":"text"},{"text":" ","type":"text"},{"text":"and querying rendered features.","type":"text"}]},"doc://com.mapbox.MapboxMaps/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapCenterAltitudeMode":{"role":"symbol","url":"\/documentation\/mapboxmaps\/mapcenteraltitudemode","title":"MapCenterAltitudeMode","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapCenterAltitudeMode"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapCenterAltitudeMode","abstract":[{"type":"text","text":"Defines how the map center point should react to terrain elevation changes."}],"navigatorTitle":[{"text":"MapCenterAltitudeMode","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GlyphsRasterizationMode":{"navigatorTitle":[{"text":"GlyphsRasterizationMode","kind":"identifier"}],"type":"topic","title":"GlyphsRasterizationMode","url":"\/documentation\/mapboxmaps\/glyphsrasterizationmode","role":"symbol","abstract":[{"text":"Describes glyphs rasterization modes.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"GlyphsRasterizationMode","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode"},"https://en.wikipedia.org/wiki/Web_Mercator_projection":{"titleInlineContent":[{"type":"text","text":"Spherical Mercator"}],"title":"Spherical Mercator","identifier":"https:\/\/en.wikipedia.org\/wiki\/Web_Mercator_projection","url":"https:\/\/en.wikipedia.org\/wiki\/Web_Mercator_projection","type":"link"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Projection":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Projection","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Projection","kind":"identifier"}],"title":"Projection","url":"\/documentation\/mapboxmaps\/projection","abstract":[{"text":"A collection of ","type":"text"},{"isActive":true,"type":"reference","identifier":"https:\/\/en.wikipedia.org\/wiki\/Web_Mercator_projection"},{"text":" projection methods.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"Projection"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateInfo":{"type":"topic","navigatorTitle":[{"text":"CoordinateInfo","kind":"identifier"}],"title":"CoordinateInfo","kind":"symbol","abstract":[{"text":"Represents the coordinate information returned by the ","type":"text"},{"type":"codeVoice","code":"coordinateInfoForPixel"},{"text":" or ","type":"text"},{"type":"codeVoice","code":"coordinatesInfoForPixels"},{"text":" methods.","type":"text"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/coordinateinfo","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CoordinateInfo"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateInfo"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraState":{"navigatorTitle":[{"text":"CameraState","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraState","role":"symbol","kind":"symbol","abstract":[],"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CameraState"}],"title":"CameraState","url":"\/documentation\/mapboxmaps\/camerastate"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraOptions/Equatable-Implementations":{"title":"Equatable Implementations","type":"topic","url":"\/documentation\/mapboxmaps\/cameraoptions\/equatable-implementations","role":"collectionGroup","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraOptions\/Equatable-Implementations","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraBoundsOptions":{"title":"CameraBoundsOptions","abstract":[{"type":"text","text":"Holds options to be used for setting camera bounds."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraBoundsOptions","kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/cameraboundsoptions","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"CameraBoundsOptions","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CameraBoundsOptions"}]},"doc://com.mapbox.MapboxMaps/Se":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/Se","title":"Swift.Decodable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraOptions/pitch":{"role":"symbol","kind":"symbol","title":"pitch","url":"\/documentation\/mapboxmaps\/cameraoptions\/pitch","type":"topic","abstract":[{"type":"text","text":"Pitch toward the horizon measured in degrees, with 0 degrees resulting in a top-down view for a two-dimensional map. Defaults to 0."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pitch"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraOptions\/pitch"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapError":{"navigatorTitle":[{"kind":"identifier","text":"MapError"}],"url":"\/documentation\/mapboxmaps\/maperror","title":"MapError","abstract":[{"type":"text","text":"Type of errors thrown by the "},{"type":"codeVoice","code":"MapboxMap"},{"text":" APIs.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"MapError","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapError"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraOptions/padding":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"padding","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIEdgeInsets","kind":"typeIdentifier","preciseIdentifier":"c:@S@UIEdgeInsets"},{"text":"?","kind":"text"}],"title":"padding","kind":"symbol","url":"\/documentation\/mapboxmaps\/cameraoptions\/padding","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraOptions\/padding","abstract":[{"text":"Insets from each edge of the map. Impacts the “principal point” of the graphical projection and the location at which ","type":"text"},{"code":"center","type":"codeVoice"},{"type":"text","text":" is rendered. Defaults to 0."}],"role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateBoundsZoom":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CoordinateBoundsZoom","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBoundsZoom","navigatorTitle":[{"text":"CoordinateBoundsZoom","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/coordinateboundszoom","abstract":[{"text":"A coordinate bounds and zoom.","type":"text"}],"title":"CoordinateBoundsZoom","type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderedQueryGeometryConvertible":{"navigatorTitle":[{"text":"RenderedQueryGeometryConvertible","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/renderedquerygeometryconvertible","title":"RenderedQueryGeometryConvertible","abstract":[{"text":"A convenience protocol for automatic conversion to ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometry","type":"reference","isActive":true},{"type":"text","text":"."}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"RenderedQueryGeometryConvertible","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometryConvertible"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraOptions/init(from:)":{"kind":"symbol","abstract":[],"title":"init(from:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraOptions\/init(from:)","url":"\/documentation\/mapboxmaps\/cameraoptions\/init(from:)","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderedQueryGeometry":{"navigatorTitle":[{"text":"RenderedQueryGeometry","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/renderedquerygeometry","title":"RenderedQueryGeometry","abstract":[{"type":"text","text":"A geometry to define a portion of screen that should be queried for rendered features."}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"RenderedQueryGeometry","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderedQueryGeometry"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"url":"\/documentation\/mapboxmaps","title":"MapboxMaps","type":"topic","role":"collection"},"doc://com.mapbox.MapboxMaps/SE":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SE","title":"Swift.Encodable"},"doc://com.mapbox.MapboxMaps/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","title":"Swift.Equatable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraOptions/init(center:padding:anchor:zoom:bearing:pitch:)":{"abstract":[{"code":"CameraOptions","type":"codeVoice"},{"type":"text","text":" represents a set of updates to make to the camera."}],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"center"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"padding","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@UIEdgeInsets","text":"UIEdgeInsets"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"anchor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"zoom","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"bearing","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CLLocationDirection","text":"CLLocationDirection","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"pitch","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"text":"?)","kind":"text"}],"url":"\/documentation\/mapboxmaps\/cameraoptions\/init(center:padding:anchor:zoom:bearing:pitch:)","type":"topic","title":"init(center:padding:anchor:zoom:bearing:pitch:)","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraOptions\/init(center:padding:anchor:zoom:bearing:pitch:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"url":"\/documentation\/mapboxmaps\/mapboxmap-apis","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","abstract":[],"title":"MapboxMap","kind":"article","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraOptions/zoom":{"kind":"symbol","title":"zoom","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraOptions\/zoom","abstract":[{"type":"text","text":"The zoom level of the map. Defaults to 0."}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"zoom"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":"?"}],"url":"\/documentation\/mapboxmaps\/cameraoptions\/zoom"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MBMCoordinateBounds","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds\/fragments","value":[{"kind":"identifier","text":"MBMCoordinateBounds"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds\/navigatorTitle","value":[{"kind":"identifier","text":"MBMCoordinateBounds"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ContextMode\/title","value":"MBMContextMode"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ContextMode\/fragments","value":[{"text":"MBMContextMode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ContextMode\/navigatorTitle","value":[{"text":"MBMContextMode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapCenterAltitudeMode\/title","value":"MBMMapCenterAltitudeMode","op":"replace"},{"value":[{"text":"MBMMapCenterAltitudeMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapCenterAltitudeMode\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapCenterAltitudeMode\/navigatorTitle","value":[{"text":"MBMMapCenterAltitudeMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/title","value":"MBMGlyphsRasterizationMode","op":"replace"},{"value":[{"text":"MBMGlyphsRasterizationMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/navigatorTitle","value":[{"text":"MBMGlyphsRasterizationMode","kind":"identifier"}],"op":"replace"},{"value":"MBMCoordinateInfo","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateInfo\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateInfo\/fragments","value":[{"text":"MBMCoordinateInfo","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"MBMCoordinateInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateInfo\/navigatorTitle"},{"value":"MBMCoordinateBoundsZoom","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBoundsZoom\/title"},{"value":[{"text":"MBMCoordinateBoundsZoom","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBoundsZoom\/fragments","op":"replace"},{"value":[{"text":"MBMCoordinateBoundsZoom","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBoundsZoom\/navigatorTitle"}]}]}