{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXTileStore\/createForPath:"},"kind":"symbol","abstract":[{"type":"text","text":"Creates a TileStore instance for the given storage path."}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/mbxtilestore\/createforpath:"]}],"sections":[],"metadata":{"symbolKind":"method","roleHeading":"Type Method","role":"symbol","modules":[{"name":"MapboxCommon"}],"title":"createForPath:","fragments":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"createForPath:"}],"navigatorTitle":[{"kind":"identifier","text":"createForPath:"}],"externalID":"c:objc(cs)MBXTileStore(cm)createForPath:"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore","text":"MBXTileStore","preciseIdentifier":"c:objc(cs)MBXTileStore"},{"text":" *) ","kind":"text"},{"text":"createForPath:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"path","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The path on disk where tiles and metadata will be stored"}]}],"name":"path"}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Returns a TileStore instance."}]}]},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The returned instance exists as long as it is retained by the client."},{"type":"text","text":" "},{"text":"If the tile store instance already exists for the given path this method will return it without creating","type":"text"},{"type":"text","text":" "},{"type":"text","text":"a new instance, thus making sure that there is only one tile store instance for a path at a time."}]},{"inlineContent":[{"type":"text","text":"If the given path is empty, the tile store at the default location is returned."},{"type":"text","text":" "},{"text":"On iOS, this storage path is excluded from automatic cloud backup.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"On Android, please exclude the storage path in your Manifest."},{"text":" ","type":"text"},{"type":"text","text":"Please refer to the "},{"isActive":true,"identifier":"https:\/\/developer.android.com\/guide\/topics\/data\/autobackup.html#IncludingFiles","type":"reference"},{"text":" for detailed information.","type":"text"}],"type":"paragraph"}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"url":"\/documentation\/mapboxmaps\/tilestore-apis","title":"TileStore APIs","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","kind":"article","type":"topic"},"https://developer.android.com/guide/topics/data/autobackup.html#IncludingFiles":{"type":"link","titleInlineContent":[{"text":"Android Documentation","type":"text"}],"url":"https:\/\/developer.android.com\/guide\/topics\/data\/autobackup.html#IncludingFiles","title":"Android Documentation","identifier":"https:\/\/developer.android.com\/guide\/topics\/data\/autobackup.html#IncludingFiles"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileStore":{"navigatorTitle":[{"text":"TileStore","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"TileStore manages downloads and storage for requests to tile-related API endpoints, enforcing a disk usage"},{"text":" ","type":"text"},{"type":"text","text":"quota: tiles available on disk may be deleted to make room for a new download. This interface can be used by an"},{"type":"text","text":" "},{"text":"app developer to set the disk quota. The rest of TileStore API is intended for native SDK consumption only.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileStore","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxcommon\/tilestore","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore","role":"symbol","title":"TileStore"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXTileStore/createForPath:":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXTileStore\/createForPath:","kind":"symbol","abstract":[{"text":"Creates a TileStore instance for the given storage path.","type":"text"}],"title":"createForPath:","url":"\/documentation\/mapboxcommon\/mbxtilestore\/createforpath:","role":"symbol","fragments":[{"text":"+ ","kind":"text"},{"text":"createForPath:","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"createForPath:"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","title":"MapboxMaps","kind":"symbol","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","type":"topic","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","abstract":[],"role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"MBXTileStore","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/fragments","value":[{"text":"MBXTileStore","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"MBXTileStore"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}