{"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TilesetDescriptorOptions\/init(styleURI:minZoom:maxZoom:pixelRatio:tilesets:stylePackOptions:extraOptions:)","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"title":"init(styleURI:minZoom:maxZoom:pixelRatio:tilesets:stylePackOptions:extraOptions:)","roleHeading":"Initializer","externalID":"c:objc(cs)MBMTilesetDescriptorOptions(im)initWithStyleURI:minZoom:maxZoom:pixelRatio:tilesets:stylePackOptions:extraOptions:::SYNTHESIZED::c:objc(cs)MBMTilesetDescriptorOptions","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"styleURI","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"minZoom"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt8","preciseIdentifier":"s:s5UInt8V"},{"kind":"text","text":", "},{"text":"maxZoom","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5UInt8V","kind":"typeIdentifier","text":"UInt8"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"pixelRatio"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":", ","kind":"text"},{"text":"tilesets","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"]?, ","kind":"text"},{"text":"stylePackOptions","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMStylePackLoadOptions","kind":"typeIdentifier","text":"StylePackLoadOptions"},{"text":"?, ","kind":"text"},{"text":"extraOptions","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"role":"symbol","platforms":[],"modules":[{"name":"MapboxMaps"}]},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"TilesetDescriptorOptions.init(styleURI:minZoom:maxZoom:pixelRatio:tilesets:stylePackOptions:extraOptions:)","type":"codeVoice"},{"text":".","type":"text"}],"variants":[{"paths":["\/documentation\/mapboxmaps\/tilesetdescriptoroptions\/init(styleuri:minzoom:maxzoom:pixelratio:tilesets:stylepackoptions:extraoptions:)"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"styleURI","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"minZoom"},{"kind":"text","text":": "},{"text":"UInt8","kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V"},{"kind":"text","text":", "},{"text":"maxZoom","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V","text":"UInt8"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"pixelRatio"},{"kind":"text","text":": "},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tilesets"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]?, ","kind":"text"},{"text":"stylePackOptions","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMStylePackLoadOptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadOptions","text":"StylePackLoadOptions"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"extraOptions"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TilesetDescriptorOptions"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePackLoadOptions":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePackLoadOptions","type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/stylepackloadoptions","title":"StylePackLoadOptions","abstract":[{"text":"Describes the style package load option values.","type":"text"}],"navigatorTitle":[{"text":"StylePackLoadOptions","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"StylePackLoadOptions"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TilesetDescriptorOptions":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TilesetDescriptorOptions"}],"navigatorTitle":[{"kind":"identifier","text":"TilesetDescriptorOptions"}],"abstract":[{"type":"text","text":"Describes the tileset descriptor option values."}],"url":"\/documentation\/mapboxmaps\/tilesetdescriptoroptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TilesetDescriptorOptions","title":"TilesetDescriptorOptions","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article","role":"collection","abstract":[],"type":"topic","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TilesetDescriptorOptions/init(styleURI:minZoom:maxZoom:pixelRatio:tilesets:stylePackOptions:extraOptions:)":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TilesetDescriptorOptions\/init(styleURI:minZoom:maxZoom:pixelRatio:tilesets:stylePackOptions:extraOptions:)","abstract":[],"role":"symbol","title":"init(styleURI:minZoom:maxZoom:pixelRatio:tilesets:stylePackOptions:extraOptions:)","url":"\/documentation\/mapboxmaps\/tilesetdescriptoroptions\/init(styleuri:minzoom:maxzoom:pixelratio:tilesets:stylepackoptions:extraoptions:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"styleURI"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"minZoom"},{"text":": ","kind":"text"},{"text":"UInt8","kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V"},{"text":", ","kind":"text"},{"text":"maxZoom","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V","text":"UInt8"},{"kind":"text","text":", "},{"text":"pixelRatio","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"tilesets"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?, "},{"text":"stylePackOptions","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMStylePackLoadOptions","text":"StylePackLoadOptions","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"extraOptions","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?)"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","title":"MapboxMaps","role":"collection","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"role":"collectionGroup","type":"topic","title":"TileStore APIs","abstract":[],"url":"\/documentation\/mapboxmaps\/tilestore-apis","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","kind":"article"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MBMStylePackLoadOptions","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadOptions\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadOptions\/fragments","op":"replace","value":[{"text":"MBMStylePackLoadOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePackLoadOptions\/navigatorTitle","op":"replace","value":[{"text":"MBMStylePackLoadOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions\/title","op":"replace","value":"MBMTilesetDescriptorOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions\/fragments","value":[{"text":"MBMTilesetDescriptorOptions","kind":"identifier"}]},{"value":[{"text":"MBMTilesetDescriptorOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions\/navigatorTitle"}]}]}