{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest\/headers"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest"]]},"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"symbolKind":"property","externalID":"c:objc(cs)MBXHttpRequest(py)headers","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"headers"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":" : ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]","kind":"text"}],"title":"headers","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"headers"}],"modules":[{"name":"MapboxCommon"}],"role":"symbol"},"variants":[{"paths":["\/documentation\/mapboxcommon\/httprequest\/headers"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxcommon\/httprequest\/headers"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"HTTP headers to include.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If you provide "},{"code":"User-Agent","type":"codeVoice"},{"type":"text","text":" header using this "},{"type":"codeVoice","code":"headers"},{"type":"text","text":" field, then resulting "},{"code":"User-Agent","type":"codeVoice"},{"type":"text","text":" will also contain"},{"type":"text","text":" "},{"type":"text","text":"information about application, platform, device, and Common SDK’s version."},{"text":" ","type":"text"},{"type":"text","text":"If you provide duplicate headers then "},{"type":"codeVoice","code":"request"},{"text":" call will be immediately failed.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"headers","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"] { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequest/headers":{"type":"topic","url":"\/documentation\/mapboxcommon\/httprequest\/headers","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest\/headers","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"headers","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"title":"headers","navigatorTitle":[{"kind":"identifier","text":"headers"}],"abstract":[{"text":"HTTP headers to include.","type":"text"},{"text":" ","type":"text"},{"text":"If you provide ","type":"text"},{"code":"User-Agent","type":"codeVoice"},{"type":"text","text":" header using this "},{"code":"headers","type":"codeVoice"},{"type":"text","text":" field, then resulting "},{"type":"codeVoice","code":"User-Agent"},{"type":"text","text":" will also contain"},{"type":"text","text":" "},{"type":"text","text":"information about application, platform, device, and Common SDK’s version."},{"text":" ","type":"text"},{"type":"text","text":"If you provide duplicate headers then "},{"type":"codeVoice","code":"request"},{"text":" call will be immediately failed.","type":"text"}],"kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"title":"MapboxCommon","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/mapboxcommon","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","abstract":[],"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","kind":"article","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequest":{"kind":"symbol","url":"\/documentation\/mapboxcommon\/httprequest","type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HttpRequest","kind":"identifier"}],"abstract":[{"text":"HttpRequest holds basic information for construction of an HTTP request","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"HttpRequest"}],"title":"HttpRequest"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"headers"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"headers"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSDictionary","kind":"typeIdentifier","text":"NSDictionary<NSString *,NSString *>"},{"kind":"text","text":" * "},{"text":"headers","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"headers","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest~1headers\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest~1headers\/fragments","op":"replace","value":[{"kind":"identifier","text":"headers"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest\/title","value":"MBXHttpRequest"},{"value":[{"kind":"identifier","text":"MBXHttpRequest"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest\/fragments"},{"value":[{"kind":"identifier","text":"MBXHttpRequest"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}