{"kind":"symbol","abstract":[{"text":"Accepted error margin.","type":"text"}],"variants":[{"paths":["\/documentation\/mapboxcommon\/mbxtileregionestimateoptions\/errormargin"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/mbxtileregionestimateoptions\/errormargin"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"errorMargin","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXTileRegionEstimateOptions\/errorMargin"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateOptions"]]},"metadata":{"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"MapboxCommon"}],"externalID":"c:objc(cs)MBXTileRegionEstimateOptions(py)errorMargin","navigatorTitle":[{"text":"errorMargin","kind":"identifier"}],"title":"errorMargin","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"errorMargin"},{"text":": ","kind":"text"},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"}]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXTileRegionEstimateOptions/errorMargin":{"abstract":[{"text":"Accepted error margin.","type":"text"}],"navigatorTitle":[{"text":"errorMargin","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/mbxtileregionestimateoptions\/errormargin","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"errorMargin","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"}],"type":"topic","role":"symbol","title":"errorMargin","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXTileRegionEstimateOptions\/errorMargin","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"url":"\/documentation\/mapboxmaps\/tilestore-apis","kind":"article","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","type":"topic","title":"TileStore APIs"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateOptions":{"role":"symbol","kind":"symbol","url":"\/documentation\/mapboxcommon\/tileregionestimateoptions","type":"topic","abstract":[{"type":"text","text":"Holds options for the tile region estimation operation."}],"title":"TileRegionEstimateOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TileRegionEstimateOptions","kind":"identifier"}],"navigatorTitle":[{"text":"TileRegionEstimateOptions","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateOptions"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"errorMargin"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"errorMargin","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:f","text":"float","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorMargin"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MBXTileRegionEstimateOptions~1errorMargin\/title","value":"errorMargin"},{"op":"replace","value":[{"kind":"identifier","text":"errorMargin"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MBXTileRegionEstimateOptions~1errorMargin\/fragments"},{"value":"MBXTileRegionEstimateOptions","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateOptions\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateOptions\/fragments","value":[{"text":"MBXTileRegionEstimateOptions","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}