{"abstract":[{"text":"In combination with ","type":"text"},{"code":"symbol-placement","type":"codeVoice"},{"text":", determines the rotation behavior of icons.","type":"text"}],"topicSections":[{"generated":true,"anchor":"Initializers","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconRotationAlignment\/init(rawValue:)"],"title":"Initializers"},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconRotationAlignment\/rawValue"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true},{"title":"Type Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconRotationAlignment\/auto","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconRotationAlignment\/map","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconRotationAlignment\/viewport"],"generated":true,"anchor":"Type-Properties"},{"generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconRotationAlignment\/Equatable-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconRotationAlignment\/RawRepresentable-Implementations"],"anchor":"Default-Implementations","title":"Default Implementations"}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer-Property-Values"]]},"relationshipsSections":[{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/Se","doc:\/\/com.mapbox.MapboxMaps\/SE","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH","doc:\/\/com.mapbox.MapboxMaps\/SY","doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"IconRotationAlignment","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/iconrotationalignment"]}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Value","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Anchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CirclePitchAlignment","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CirclePitchScale","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CircleTranslateAnchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillExtrusionTranslateAnchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillTranslateAnchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeIlluminationAnchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconAnchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconPitchAlignment","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconTextFit","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconTranslateAnchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineCap","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineJoin","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineTranslateAnchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterResampling","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResolvedImage","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResolvedImageData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValue","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValueKind","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SkyType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleColor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleTransition","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolPlacement","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolZOrder","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextAnchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextJustify","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextPitchAlignment","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextRotationAlignment","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextTransform","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextTranslateAnchor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextWritingMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Visibility","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TransitionOptions-swift.struct","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelScaleMode","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolElevationReference","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageContent","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageStretches"],"title":"Layer Property Values","anchor":"Layer-Property-Values","generated":true}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconRotationAlignment"},"metadata":{"navigatorTitle":[{"text":"IconRotationAlignment","kind":"identifier"}],"symbolKind":"struct","roleHeading":"Structure","externalID":"s:10MapboxMaps21IconRotationAlignmentV","modules":[{"name":"MapboxMaps"}],"title":"IconRotationAlignment","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"IconRotationAlignment"}]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CirclePitchAlignment":{"title":"CirclePitchAlignment","abstract":[{"type":"text","text":"Orientation of circle when map is pitched."}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/circlepitchalignment","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CirclePitchAlignment","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CirclePitchAlignment","navigatorTitle":[{"text":"CirclePitchAlignment","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TextAnchor":{"role":"symbol","url":"\/documentation\/mapboxmaps\/textanchor","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"TextAnchor","kind":"identifier"}],"navigatorTitle":[{"text":"TextAnchor","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextAnchor","type":"topic","kind":"symbol","title":"TextAnchor","abstract":[{"type":"text","text":"Part of the text placed closest to the anchor."}]},"doc://com.mapbox.MapboxMaps/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Value":{"navigatorTitle":[{"text":"Value","kind":"identifier"}],"abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"Value","kind":"identifier"}],"title":"Value","url":"\/documentation\/mapboxmaps\/value","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Value"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FillExtrusionTranslateAnchor":{"role":"symbol","url":"\/documentation\/mapboxmaps\/fillextrusiontranslateanchor","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"FillExtrusionTranslateAnchor","kind":"identifier"}],"navigatorTitle":[{"text":"FillExtrusionTranslateAnchor","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillExtrusionTranslateAnchor","type":"topic","kind":"symbol","title":"FillExtrusionTranslateAnchor","abstract":[{"type":"text","text":"Controls the frame of reference for "},{"code":"fill-extrusion-translate","type":"codeVoice"},{"type":"text","text":"."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CirclePitchScale":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CirclePitchScale","type":"topic","title":"CirclePitchScale","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CirclePitchScale"}],"url":"\/documentation\/mapboxmaps\/circlepitchscale","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"CirclePitchScale","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Controls the scaling behavior of the circle when the map is pitched."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelType":{"role":"symbol","url":"\/documentation\/mapboxmaps\/modeltype","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ModelType","kind":"identifier"}],"navigatorTitle":[{"text":"ModelType","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelType","type":"topic","kind":"symbol","title":"ModelType","abstract":[{"type":"text","text":"Defines rendering behavior of model in respect to other 3D scene objects."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TransitionOptions-swift.struct":{"title":"TransitionOptions","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"TransitionOptions"},{"text":" control timing for the interpolation between a transitionable style","type":"text"},{"text":" ","type":"text"},{"text":"property’s previous value and new value. These can be used to define the style default property","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"transition behavior. Also, any transitionable style property may also have its own "},{"code":"-transition","type":"codeVoice"},{"type":"text","text":" "},{"type":"text","text":"property that defines specific transition timing for that specific layer property, overriding"},{"type":"text","text":" "},{"text":"the global transition values.","type":"text"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/transitionoptions-swift.struct","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TransitionOptions"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TransitionOptions-swift.struct","navigatorTitle":[{"text":"TransitionOptions","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/IconRotationAlignment":{"title":"IconRotationAlignment","abstract":[{"text":"In combination with ","type":"text"},{"type":"codeVoice","code":"symbol-placement"},{"type":"text","text":", determines the rotation behavior of icons."}],"role":"symbol","navigatorTitle":[{"text":"IconRotationAlignment","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"IconRotationAlignment"}],"url":"\/documentation\/mapboxmaps\/iconrotationalignment","kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconRotationAlignment"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterResampling":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterResampling","type":"topic","title":"RasterResampling","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"RasterResampling"}],"url":"\/documentation\/mapboxmaps\/rasterresampling","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RasterResampling"}],"role":"symbol","abstract":[{"type":"text","text":"The resampling\/interpolation method to use for overscaling, also known as texture magnification filter"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SymbolZOrder":{"role":"symbol","url":"\/documentation\/mapboxmaps\/symbolzorder","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SymbolZOrder","kind":"identifier"}],"navigatorTitle":[{"text":"SymbolZOrder","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolZOrder","type":"topic","kind":"symbol","title":"SymbolZOrder","abstract":[{"text":"Determines whether overlapping symbols in the same layer are rendered in the order that they appear in the data source or by their y-position relative to the viewport. To control the order and prioritization of symbols otherwise, use ","type":"text"},{"type":"codeVoice","code":"symbol-sort-key"},{"type":"text","text":"."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TextTranslateAnchor":{"url":"\/documentation\/mapboxmaps\/texttranslateanchor","abstract":[{"text":"Controls the frame of reference for ","type":"text"},{"type":"codeVoice","code":"text-translate"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TextTranslateAnchor"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"TextTranslateAnchor","kind":"identifier"}],"role":"symbol","title":"TextTranslateAnchor","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextTranslateAnchor"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SymbolPlacement":{"title":"SymbolPlacement","abstract":[{"text":"Label placement relative to its geometry.","type":"text"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/symbolplacement","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SymbolPlacement"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolPlacement","navigatorTitle":[{"text":"SymbolPlacement","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Anchor":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Anchor","navigatorTitle":[{"kind":"identifier","text":"Anchor"}],"title":"Anchor","kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Whether extruded geometries are lit relative to the map or viewport."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Anchor"}],"url":"\/documentation\/mapboxmaps\/anchor"},"doc://com.mapbox.MapboxMaps/SE":{"title":"Swift.Encodable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SE"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LineJoin":{"title":"LineJoin","abstract":[{"type":"text","text":"The display of lines when joining."}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/linejoin","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LineJoin","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineJoin","navigatorTitle":[{"kind":"identifier","text":"LineJoin"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/IconTextFit":{"role":"symbol","url":"\/documentation\/mapboxmaps\/icontextfit","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IconTextFit","kind":"identifier"}],"navigatorTitle":[{"text":"IconTextFit","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconTextFit","type":"topic","kind":"symbol","title":"IconTextFit","abstract":[{"text":"Scales the icon to fit around the associated text.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SkyType":{"role":"symbol","url":"\/documentation\/mapboxmaps\/skytype","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SkyType","kind":"identifier"}],"navigatorTitle":[{"text":"SkyType","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SkyType","type":"topic","kind":"symbol","title":"SkyType","abstract":[{"text":"The type of the sky","type":"text"}]},"doc://com.mapbox.MapboxMaps/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Visibility":{"title":"Visibility","abstract":[],"kind":"symbol","url":"\/documentation\/mapboxmaps\/visibility","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Visibility","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Visibility","navigatorTitle":[{"text":"Visibility","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layer-Property-Values":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layer-Property-Values","abstract":[],"role":"collectionGroup","url":"\/documentation\/mapboxmaps\/layer-property-values","kind":"article","title":"Layer Property Values","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePropertyValueKind":{"title":"StylePropertyValueKind","abstract":[{"type":"text","text":"Describes the kind of a style property value."}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/stylepropertyvaluekind","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StylePropertyValueKind","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValueKind","navigatorTitle":[{"text":"StylePropertyValueKind","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","kind":"article","abstract":[],"url":"\/documentation\/overview","type":"topic","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ImageStretches":{"navigatorTitle":[{"kind":"identifier","text":"ImageStretches"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageStretches","role":"symbol","abstract":[{"text":"Describes the image stretch areas.","type":"text"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/imagestretches","title":"ImageStretches","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageStretches","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TextJustify":{"abstract":[{"text":"Text justification options.","type":"text"}],"type":"topic","url":"\/documentation\/mapboxmaps\/textjustify","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextJustify","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TextJustify","kind":"identifier"}],"title":"TextJustify","navigatorTitle":[{"text":"TextJustify","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TextRotationAlignment":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextRotationAlignment","type":"topic","title":"TextRotationAlignment","kind":"symbol","navigatorTitle":[{"text":"TextRotationAlignment","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/textrotationalignment","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"TextRotationAlignment","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"In combination with "},{"code":"symbol-placement","type":"codeVoice"},{"type":"text","text":", determines the rotation behavior of the individual glyphs forming the text."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/HillshadeIlluminationAnchor":{"role":"symbol","url":"\/documentation\/mapboxmaps\/hillshadeilluminationanchor","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HillshadeIlluminationAnchor","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"HillshadeIlluminationAnchor"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/HillshadeIlluminationAnchor","type":"topic","kind":"symbol","title":"HillshadeIlluminationAnchor","abstract":[{"text":"Direction of light source when map is rotated.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/IconRotationAlignment/RawRepresentable-Implementations":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconRotationAlignment\/RawRepresentable-Implementations","url":"\/documentation\/mapboxmaps\/iconrotationalignment\/rawrepresentable-implementations","title":"RawRepresentable Implementations","role":"collectionGroup","type":"topic","abstract":[],"kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResolvedImage":{"role":"symbol","url":"\/documentation\/mapboxmaps\/resolvedimage","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ResolvedImage","kind":"identifier"}],"navigatorTitle":[{"text":"ResolvedImage","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResolvedImage","type":"topic","kind":"symbol","title":"ResolvedImage","abstract":[]},"doc://com.mapbox.MapboxMaps/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SY"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/IconRotationAlignment/rawValue":{"abstract":[],"role":"symbol","kind":"symbol","type":"topic","title":"rawValue","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"url":"\/documentation\/mapboxmaps\/iconrotationalignment\/rawvalue","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconRotationAlignment\/rawValue"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FillTranslateAnchor":{"title":"FillTranslateAnchor","abstract":[{"text":"Controls the frame of reference for ","type":"text"},{"code":"fill-translate","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/filltranslateanchor","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"FillTranslateAnchor","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FillTranslateAnchor","navigatorTitle":[{"text":"FillTranslateAnchor","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/IconRotationAlignment/Equatable-Implementations":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconRotationAlignment\/Equatable-Implementations","abstract":[],"role":"collectionGroup","kind":"article","title":"Equatable Implementations","type":"topic","url":"\/documentation\/mapboxmaps\/iconrotationalignment\/equatable-implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/IconRotationAlignment/viewport":{"title":"viewport","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconRotationAlignment\/viewport","abstract":[{"text":"Produces icons whose x-axes are aligned with the x-axis of the viewport, regardless of the value of {@link SYMBOL_PLACEMENT}.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewport"},{"kind":"text","text":": "},{"text":"IconRotationAlignment","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps21IconRotationAlignmentV"}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/iconrotationalignment\/viewport"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/IconRotationAlignment/map":{"url":"\/documentation\/mapboxmaps\/iconrotationalignment\/map","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"map","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps21IconRotationAlignmentV","text":"IconRotationAlignment"}],"kind":"symbol","abstract":[{"type":"text","text":"When {@link SYMBOL_PLACEMENT} is set to {@link Property#SYMBOL_PLACEMENT_POINT}, aligns icons east-west. When {@link SYMBOL_PLACEMENT} is set to {@link Property#SYMBOL_PLACEMENT_LINE} or {@link Property#SYMBOL_PLACEMENT_LINE_CENTER}, aligns icon x-axes with the line."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconRotationAlignment\/map","title":"map","type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleTransition":{"type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/styletransition","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleTransition","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"StyleTransition","kind":"identifier"}],"navigatorTitle":[{"text":"StyleTransition","kind":"identifier"}],"abstract":[{"text":"The transition property for a layer.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"A transition property controls timing for the interpolation between a"},{"type":"text","text":" "},{"type":"text","text":"transitionable style property’s previous value and new value."}],"title":"StyleTransition"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ModelScaleMode":{"title":"ModelScaleMode","abstract":[{"text":"Defines scaling mode. Only applies to location-indicator type layers.","type":"text"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/modelscalemode","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"ModelScaleMode","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ModelScaleMode","navigatorTitle":[{"text":"ModelScaleMode","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"role":"collection","url":"\/documentation\/mapboxmaps","title":"MapboxMaps","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleColor":{"role":"symbol","url":"\/documentation\/mapboxmaps\/stylecolor","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"StyleColor","kind":"identifier"}],"navigatorTitle":[{"text":"StyleColor","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleColor","type":"topic","kind":"symbol","title":"StyleColor","abstract":[{"text":"Represents a color as defined by the ","type":"text"},{"type":"reference","isActive":true,"identifier":"https:\/\/docs.mapbox.com\/style-spec\/reference\/types\/#color"}]},"doc://com.mapbox.MapboxMaps/Se":{"title":"Swift.Decodable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/Se"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LineTranslateAnchor":{"title":"LineTranslateAnchor","abstract":[{"text":"Controls the frame of reference for ","type":"text"},{"type":"codeVoice","code":"line-translate"},{"text":".","type":"text"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/linetranslateanchor","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LineTranslateAnchor","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineTranslateAnchor","navigatorTitle":[{"kind":"identifier","text":"LineTranslateAnchor"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TextTransform":{"title":"TextTransform","abstract":[{"type":"text","text":"Specifies how to capitalize text, similar to the CSS "},{"code":"text-transform","type":"codeVoice"},{"type":"text","text":" property."}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/texttransform","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TextTransform","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextTransform","navigatorTitle":[{"kind":"identifier","text":"TextTransform"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePropertyValue":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValue","navigatorTitle":[{"kind":"identifier","text":"StylePropertyValue"}],"title":"StylePropertyValue","kind":"symbol","type":"topic","role":"symbol","abstract":[{"text":"Holds a style property value with meta data.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"StylePropertyValue","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/stylepropertyvalue"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/IconPitchAlignment":{"role":"symbol","url":"\/documentation\/mapboxmaps\/iconpitchalignment","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IconPitchAlignment","kind":"identifier"}],"navigatorTitle":[{"text":"IconPitchAlignment","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconPitchAlignment","type":"topic","kind":"symbol","title":"IconPitchAlignment","abstract":[{"type":"text","text":"Orientation of icon when map is pitched."}]},"doc://com.mapbox.MapboxMaps/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ImageContent":{"role":"symbol","url":"\/documentation\/mapboxmaps\/imagecontent","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageContent","kind":"identifier"}],"navigatorTitle":[{"text":"ImageContent","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageContent","type":"topic","kind":"symbol","title":"ImageContent","abstract":[{"type":"text","text":"Describes the image content, e.g. where text can be fit into an image."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CircleTranslateAnchor":{"title":"CircleTranslateAnchor","abstract":[{"text":"Controls the frame of reference for ","type":"text"},{"type":"codeVoice","code":"circle-translate"},{"type":"text","text":"."}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/circletranslateanchor","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CircleTranslateAnchor","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CircleTranslateAnchor","navigatorTitle":[{"text":"CircleTranslateAnchor","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LineCap":{"role":"symbol","url":"\/documentation\/mapboxmaps\/linecap","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LineCap","kind":"identifier"}],"navigatorTitle":[{"text":"LineCap","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LineCap","type":"topic","kind":"symbol","title":"LineCap","abstract":[{"text":"The display of line endings.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/IconRotationAlignment/auto":{"type":"topic","abstract":[{"text":"When {@link SYMBOL_PLACEMENT} is set to {@link Property#SYMBOL_PLACEMENT_POINT}, this is equivalent to {@link Property#ICON_ROTATION_ALIGNMENT_VIEWPORT}. When {@link SYMBOL_PLACEMENT} is set to {@link Property#SYMBOL_PLACEMENT_LINE} or {@link Property#SYMBOL_PLACEMENT_LINE_CENTER}, this is equivalent to {@link Property#ICON_ROTATION_ALIGNMENT_MAP}.","type":"text"}],"kind":"symbol","title":"auto","url":"\/documentation\/mapboxmaps\/iconrotationalignment\/auto","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"auto","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps21IconRotationAlignmentV","text":"IconRotationAlignment","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconRotationAlignment\/auto"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/IconTranslateAnchor":{"title":"IconTranslateAnchor","abstract":[{"text":"Controls the frame of reference for ","type":"text"},{"type":"codeVoice","code":"icon-translate"},{"type":"text","text":"."}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/icontranslateanchor","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IconTranslateAnchor"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconTranslateAnchor","navigatorTitle":[{"text":"IconTranslateAnchor","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ResolvedImageData":{"title":"ResolvedImageData","abstract":[],"kind":"symbol","url":"\/documentation\/mapboxmaps\/resolvedimagedata","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ResolvedImageData","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ResolvedImageData","navigatorTitle":[{"text":"ResolvedImageData","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/IconAnchor":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconAnchor","type":"topic","title":"IconAnchor","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"IconAnchor"}],"url":"\/documentation\/mapboxmaps\/iconanchor","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IconAnchor"}],"role":"symbol","abstract":[{"text":"Part of the icon placed closest to the anchor.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/IconRotationAlignment/init(rawValue:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/IconRotationAlignment\/init(rawValue:)","title":"init(rawValue:)","abstract":[],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/iconrotationalignment\/init(rawvalue:)"},"https://docs.mapbox.com/style-spec/reference/types/#color":{"url":"https:\/\/docs.mapbox.com\/style-spec\/reference\/types\/#color","type":"link","titleInlineContent":[{"type":"text","text":"Mapbox Style Spec"}],"identifier":"https:\/\/docs.mapbox.com\/style-spec\/reference\/types\/#color","title":"Mapbox Style Spec"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SymbolElevationReference":{"title":"SymbolElevationReference","abstract":[{"text":"Selects the base of symbol-elevation.","type":"text"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/symbolelevationreference","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SymbolElevationReference","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SymbolElevationReference","navigatorTitle":[{"text":"SymbolElevationReference","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TextPitchAlignment":{"role":"symbol","url":"\/documentation\/mapboxmaps\/textpitchalignment","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TextPitchAlignment","kind":"identifier"}],"navigatorTitle":[{"text":"TextPitchAlignment","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextPitchAlignment","type":"topic","kind":"symbol","title":"TextPitchAlignment","abstract":[{"text":"Orientation of text when map is pitched.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TextWritingMode":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TextWritingMode","navigatorTitle":[{"kind":"identifier","text":"TextWritingMode"}],"title":"TextWritingMode","kind":"symbol","type":"topic","role":"symbol","abstract":[{"text":"The property allows control over a symbol’s orientation. Note that the property values act as a hint, so that a symbol whose language doesn’t support the provided orientation will be laid out in its natural orientation. Example: English point symbol will be rendered horizontally even if array value contains single ‘vertical’ enum value. For symbol with point placement, the order of elements in an array define priority order for the placement of an orientation variant. For symbol with line placement, the default text writing mode is either [‘horizontal’, ‘vertical’] or [‘vertical’, ‘horizontal’], the order doesn’t affect the placement.","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"TextWritingMode","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/textwritingmode"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MBMStylePropertyValueKind","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValueKind\/title"},{"op":"replace","value":[{"text":"MBMStylePropertyValueKind","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValueKind\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValueKind\/navigatorTitle","value":[{"kind":"identifier","text":"MBMStylePropertyValueKind"}]},{"value":"MBMImageStretches","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ImageStretches\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ImageStretches\/fragments","value":[{"kind":"identifier","text":"MBMImageStretches"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBMImageStretches"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ImageStretches\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValue\/title","value":"MBMStylePropertyValue"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValue\/fragments","value":[{"text":"MBMStylePropertyValue","kind":"identifier"}]},{"value":[{"text":"MBMStylePropertyValue","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValue\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ImageContent\/title","value":"MBMImageContent"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ImageContent\/fragments","value":[{"text":"MBMImageContent","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MBMImageContent"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ImageContent\/navigatorTitle","op":"replace"}]}]}