{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"worldview","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"! { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"roleHeading":"Type Property","symbolKind":"property","modules":[{"name":"MapboxCommon"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"worldview","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"navigatorTitle":[{"text":"Worldview","kind":"identifier"}],"title":"worldview","role":"symbol","externalID":"c:objc(cs)MBXMapboxCommonSettings(cpy)Worldview"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"The key that defines a worldview to be used by the Mapbox SDKs.","type":"text"},{"type":"text","text":" "},{"text":"The value of the key must be a string that is a valid ISO 3166-1 alpha-2 country code (eg. “US”).","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/mapboxcommonsettings\/worldview"]},{"paths":["\/documentation\/mapboxcommon\/mapboxcommonsettings\/worldview"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MapboxCommonSettings\/worldview","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Settings-and-Constants","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MapboxCommonSettings"]]},"kind":"symbol","references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MapboxCommonSettings":{"navigatorTitle":[{"text":"MapboxCommonSettings","kind":"identifier"}],"abstract":[{"type":"text","text":"Set of common keys that can be used to configure all Mapbox SDKs."}],"title":"MapboxCommonSettings","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MapboxCommonSettings","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/mapboxcommonsettings","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MapboxCommonSettings","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"title":"MapboxMaps","kind":"symbol","role":"collection","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","role":"collection","url":"\/documentation\/overview","kind":"article","abstract":[],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MapboxCommonSettings/worldview":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"worldview","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"type":"topic","kind":"symbol","title":"worldview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MapboxCommonSettings\/worldview","abstract":[{"type":"text","text":"The key that defines a worldview to be used by the Mapbox SDKs."},{"type":"text","text":" "},{"text":"The value of the key must be a string that is a valid ISO 3166-1 alpha-2 country code (eg. “US”).","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"Worldview","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/mapboxcommonsettings\/worldview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Settings-and-Constants":{"kind":"article","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Settings-and-Constants","role":"collectionGroup","title":"Settings and Constants","abstract":[],"url":"\/documentation\/mapboxmaps\/settings-and-constants"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Type Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"Worldview"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"Worldview","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"Worldview"},{"kind":"text","text":";"}]}]}},{"value":"MBXMapboxCommonSettings","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MapboxCommonSettings\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MapboxCommonSettings\/fragments","value":[{"text":"MBXMapboxCommonSettings","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MBXMapboxCommonSettings"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MapboxCommonSettings\/navigatorTitle","op":"replace"},{"value":"Worldview","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MapboxCommonSettings~1worldview\/title"},{"value":[{"text":"Worldview","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MapboxCommonSettings~1worldview\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}