{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/requestdatasourcetype\/network"]},{"paths":["\/documentation\/mapboxmaps\/requestdatasourcetype\/network"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestDataSourceType\/network","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestDataSourceType"]]},"metadata":{"modules":[{"name":"MapboxMaps"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"network"}],"externalID":"c:@E@MBMRequestDataSourceType@MBMRequestDataSourceTypeNetwork","title":"RequestDataSourceType.network","symbolKind":"case","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"MBMRequestDataSourceTypeNetwork"}],"role":"symbol"},"sections":[],"abstract":[{"text":"The resource is requested from the network.","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"network","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"url":"\/documentation\/mapboxmaps\/events","role":"collectionGroup","title":"Map events","kind":"article","abstract":[{"type":"text","text":"The simplified diagram of the events emitted by the map is displayed below."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"role":"collection","title":"MapboxMaps","type":"topic","url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestDataSourceType":{"title":"RequestDataSourceType","url":"\/documentation\/mapboxmaps\/requestdatasourcetype","type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"RequestDataSourceType","kind":"identifier"}],"navigatorTitle":[{"text":"RequestDataSourceType","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestDataSourceType","abstract":[{"type":"text","text":"The enumeration defines the type of data source."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RequestDataSourceType/network":{"role":"symbol","navigatorTitle":[{"text":"MBMRequestDataSourceTypeNetwork","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxmaps\/requestdatasourcetype\/network","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RequestDataSourceType\/network","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"network","kind":"identifier"}],"abstract":[{"type":"text","text":"The resource is requested from the network."}],"kind":"symbol","title":"RequestDataSourceType.network"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","url":"\/documentation\/overview","role":"collection","kind":"article","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"MBMRequestDataSourceTypeNetwork","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MBMRequestDataSourceTypeNetwork"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"MBMRequestDataSourceTypeNetwork","kind":"identifier"}]}]}},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestDataSourceType\/title","op":"replace","value":"MBMRequestDataSourceType"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestDataSourceType\/fragments","value":[{"kind":"identifier","text":"MBMRequestDataSourceType"}]},{"value":[{"text":"MBMRequestDataSourceType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestDataSourceType\/navigatorTitle"},{"op":"replace","value":"MBMRequestDataSourceTypeNetwork","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestDataSourceType~1network\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RequestDataSourceType~1network\/fragments","value":[{"text":"MBMRequestDataSourceTypeNetwork","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}