{"abstract":[{"type":"text","text":"Tileset descriptors resolving failed."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"tilesetDescriptor","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/tileregionerrortype\/tilesetdescriptor"]},{"paths":["\/documentation\/mapboxcommon\/tileregionerrortype\/tilesetdescriptor"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType\/tilesetDescriptor","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"tilesetDescriptor"}],"title":"TileRegionErrorType.tilesetDescriptor","externalID":"c:@E@MBXTileRegionErrorType@MBXTileRegionErrorTypeTilesetDescriptor","roleHeading":"Case","modules":[{"name":"MapboxCommon"}],"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"MBXTileRegionErrorTypeTilesetDescriptor"}],"role":"symbol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","title":"MapboxCommon","kind":"symbol","role":"collection","url":"\/documentation\/mapboxcommon","type":"topic","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"kind":"article","url":"\/documentation\/overview","role":"collection","title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionErrorType":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType","type":"topic","abstract":[{"type":"text","text":"Describes the reason for a tile region download request failure."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileRegionErrorType"}],"kind":"symbol","role":"symbol","title":"TileRegionErrorType","navigatorTitle":[{"kind":"identifier","text":"TileRegionErrorType"}],"url":"\/documentation\/mapboxcommon\/tileregionerrortype"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionErrorType/tilesetDescriptor":{"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tilesetDescriptor"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType\/tilesetDescriptor","abstract":[{"text":"Tileset descriptors resolving failed.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"MBXTileRegionErrorTypeTilesetDescriptor","kind":"identifier"}],"role":"symbol","title":"TileRegionErrorType.tilesetDescriptor","url":"\/documentation\/mapboxcommon\/tileregionerrortype\/tilesetdescriptor"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"MBXTileRegionErrorTypeTilesetDescriptor"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MBXTileRegionErrorTypeTilesetDescriptor","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"MBXTileRegionErrorTypeTilesetDescriptor","kind":"identifier"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionErrorType\/title","value":"MBXTileRegionErrorType"},{"op":"replace","value":[{"kind":"identifier","text":"MBXTileRegionErrorType"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionErrorType\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionErrorType\/navigatorTitle","value":[{"text":"MBXTileRegionErrorType","kind":"identifier"}],"op":"replace"},{"value":"MBXTileRegionErrorTypeTilesetDescriptor","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionErrorType~1tilesetDescriptor\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionErrorType~1tilesetDescriptor\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXTileRegionErrorTypeTilesetDescriptor"}]}]}]}