{"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileData\/tileId","interfaceLanguage":"swift"},"abstract":[{"text":"A ","type":"text"},{"code":"canonical tile id","type":"codeVoice"},{"type":"text","text":" of the tile."}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/customrastersourcetiledata\/tileid"]},{"paths":["\/documentation\/mapboxmaps\/customrastersourcetiledata\/tileid"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileData"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tileId","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CanonicalTileID","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID","preciseIdentifier":"c:objc(cs)MBMCanonicalTileID"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"title":"tileId","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tileId","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CanonicalTileID","preciseIdentifier":"c:objc(cs)MBMCanonicalTileID"}],"navigatorTitle":[{"kind":"identifier","text":"tileId"}],"role":"symbol","externalID":"c:objc(cs)MBMCustomRasterSourceTileData(py)tileId","modules":[{"name":"MapboxMaps"}],"roleHeading":"Instance Property"},"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","abstract":[],"type":"topic","kind":"article","title":"MapboxMaps Documentation","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileData":{"kind":"symbol","navigatorTitle":[{"text":"CustomRasterSourceTileData","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CustomRasterSourceTileData","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/customrastersourcetiledata","role":"symbol","abstract":[{"type":"text","text":"Data for a specific CustomRasterSource tile."}],"title":"CustomRasterSourceTileData","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileData","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Sources":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources","url":"\/documentation\/mapboxmaps\/sources","abstract":[],"type":"topic","role":"collectionGroup","title":"Sources","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CanonicalTileID":{"abstract":[{"type":"text","text":"Represents a tile coordinate."}],"role":"symbol","title":"CanonicalTileID","url":"\/documentation\/mapboxmaps\/canonicaltileid","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CanonicalTileID"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CanonicalTileID"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","url":"\/documentation\/mapboxmaps","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"title":"MapboxMaps","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileData/tileId":{"title":"tileId","url":"\/documentation\/mapboxmaps\/customrastersourcetiledata\/tileid","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"canonical tile id"},{"type":"text","text":" of the tile."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileData\/tileId","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tileId","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CanonicalTileID","preciseIdentifier":"c:objc(cs)MBMCanonicalTileID"}],"navigatorTitle":[{"text":"tileId","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"tileId","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"tileId","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"MBMCanonicalTileID","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID","preciseIdentifier":"c:objc(cs)MBMCanonicalTileID"},{"kind":"text","text":" * "},{"kind":"identifier","text":"tileId"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"value":"MBMCustomRasterSourceTileData","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileData\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileData\/fragments","value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileData"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileData\/navigatorTitle","value":[{"text":"MBMCustomRasterSourceTileData","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/title","value":"MBMCanonicalTileID","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/fragments","value":[{"text":"MBMCanonicalTileID","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMCanonicalTileID"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileData~1tileId\/title","value":"tileId","op":"replace"},{"value":[{"text":"tileId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileData~1tileId\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}