{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMViewAnnotationAnchorConfig\/initWithAnchor:offsetX:offsetY:"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/View-Annotations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchorConfig"]]},"metadata":{"title":"initWithAnchor:offsetX:offsetY:","modules":[{"name":"MapboxMaps"}],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithAnchor:offsetX:offsetY:"}],"navigatorTitle":[{"text":"initWithAnchor:offsetX:offsetY:","kind":"identifier"}],"roleHeading":"Instance Method","externalID":"c:objc(cs)MBMViewAnnotationAnchorConfig(im)initWithAnchor:offsetX:offsetY:","role":"symbol","symbolKind":"method"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"text":"initWithAnchor:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchor","preciseIdentifier":"c:@E@MBMViewAnnotationAnchor","text":"MBMViewAnnotationAnchor","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"anchor","kind":"internalParam"},{"kind":"text","text":" "},{"text":"offsetX:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","preciseIdentifier":"c:d","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"offsetX"},{"text":" ","kind":"text"},{"text":"offsetY:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"text":"offsetY","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/mapboxmaps\/mbmviewannotationanchorconfig\/initwithanchor:offsetx:offsety:"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","role":"collection","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationAnchor":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/viewannotationanchor","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchor","title":"ViewAnnotationAnchor","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ViewAnnotationAnchor"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ViewAnnotationAnchor"}],"abstract":[{"type":"text","text":"Enum describing how to place view annotation relatively to geometry."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMViewAnnotationAnchorConfig/initWithAnchor:offsetX:offsetY:":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMViewAnnotationAnchorConfig\/initWithAnchor:offsetX:offsetY:","url":"\/documentation\/mapboxmaps\/mbmviewannotationanchorconfig\/initwithanchor:offsetx:offsety:","role":"symbol","kind":"symbol","title":"initWithAnchor:offsetX:offsetY:","navigatorTitle":[{"kind":"identifier","text":"initWithAnchor:offsetX:offsetY:"}],"abstract":[],"type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAnchor:offsetX:offsetY:"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/View-Annotations":{"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/View-Annotations","type":"topic","role":"collectionGroup","title":"View Annotations","url":"\/documentation\/mapboxmaps\/view-annotations","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationAnchorConfig":{"type":"topic","title":"ViewAnnotationAnchorConfig","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchorConfig","abstract":[{"type":"text","text":"Represents a specific setting for a view annotation anchor."}],"kind":"symbol","navigatorTitle":[{"text":"ViewAnnotationAnchorConfig","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ViewAnnotationAnchorConfig","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/viewannotationanchorconfig"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","title":"MapboxMaps Documentation","url":"\/documentation\/overview","type":"topic","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"MBMViewAnnotationAnchor","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchor\/title"},{"value":[{"kind":"identifier","text":"MBMViewAnnotationAnchor"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchor\/fragments"},{"value":[{"kind":"identifier","text":"MBMViewAnnotationAnchor"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchor\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchorConfig\/title","value":"MBMViewAnnotationAnchorConfig"},{"value":[{"text":"MBMViewAnnotationAnchorConfig","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchorConfig\/fragments"},{"op":"replace","value":[{"text":"MBMViewAnnotationAnchorConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchorConfig\/navigatorTitle"}]}]}