{"metadata":{"externalID":"c:@EA@MBXGeometryType","navigatorTitle":[{"text":"GeometryType","kind":"identifier"}],"modules":[{"name":"MapboxCommon"}],"roleHeading":"Structure","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"GeometryType"}],"symbolKind":"struct","title":"GeometryType","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TurfAPI"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType\/init(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType\/init(rawValue:)"],"generated":true,"anchor":"Initializers"},{"anchor":"Instance-Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType\/rawValue"],"generated":true,"title":"Instance Properties"},{"generated":true,"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType\/Equatable-Implementations"]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/s15BitwiseCopyableP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SY","doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GeometryType"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/mapboxcommon\/geometrytype"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/geometrytype"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType"},"seeAlsoSections":[{"anchor":"GeoJSON","title":"GeoJSON","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Feature","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Geometry","doc:\/\/com.mapbox.MapboxMaps\/documentation\/Turf"]}],"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/GeometryType_Polygon":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType_Polygon","role":"symbol","abstract":[],"title":"GeometryType_Polygon","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"GeometryType_Polygon","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@EA@MBXGeometryType","kind":"typeIdentifier","text":"GeometryType"}],"navigatorTitle":[{"kind":"identifier","text":"MBXGeometryType_Polygon"}],"url":"\/documentation\/mapboxcommon\/geometrytype_polygon","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Geometry":{"type":"topic","url":"\/documentation\/mapboxmaps\/geometry","abstract":[{"text":"An object representing points, curves, and surfaces in coordinate space. Use an instance of this enumeration whenever a value could be any kind of Geometry object.","type":"text"}],"kind":"symbol","title":"Geometry","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Geometry","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Geometry","navigatorTitle":[{"kind":"identifier","text":"Geometry"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Feature":{"role":"symbol","abstract":[{"text":"An object representing a spatially bounded geometry.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Feature","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Feature","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/feature","title":"Feature","navigatorTitle":[{"kind":"identifier","text":"Feature"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/GeometryType_Point":{"role":"symbol","type":"topic","title":"GeometryType_Point","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType_Point","kind":"symbol","url":"\/documentation\/mapboxcommon\/geometrytype_point","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GeometryType_Point"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@EA@MBXGeometryType","kind":"typeIdentifier","text":"GeometryType"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"MBXGeometryType_Point"}]},"doc://com.mapbox.MapboxMaps/s8SendableP":{"title":"Swift.Sendable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s8SendableP","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","title":"MapboxMaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"role":"collection","url":"\/documentation\/mapboxmaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/GeometryType/init(_:)":{"role":"symbol","type":"topic","title":"init(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType\/init(_:)","kind":"symbol","url":"\/documentation\/mapboxcommon\/geometrytype\/init(_:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"UInt32","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt32V"},{"kind":"text","text":")"}],"abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/GeometryType_Empty":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType_Empty","role":"symbol","abstract":[],"title":"GeometryType_Empty","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GeometryType_Empty"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@EA@MBXGeometryType","kind":"typeIdentifier","text":"GeometryType"}],"navigatorTitle":[{"kind":"identifier","text":"MBXGeometryType_Empty"}],"url":"\/documentation\/mapboxcommon\/geometrytype_empty","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/GeometryType/rawValue":{"role":"symbol","type":"topic","title":"rawValue","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType\/rawValue","kind":"symbol","url":"\/documentation\/mapboxcommon\/geometrytype\/rawvalue","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawValue"},{"kind":"text","text":": "},{"text":"UInt32","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt32V"}],"abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TurfAPI":{"url":"\/documentation\/mapboxmaps\/turfapi","role":"collectionGroup","title":"Turf","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TurfAPI","abstract":[{"type":"text","text":"Describes "},{"code":"turf-swift","type":"codeVoice"},{"text":" dependency objects","type":"text"}],"kind":"article"},"doc://com.mapbox.MapboxMaps/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","title":"Swift.Equatable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/GeometryType_MultiLine":{"role":"symbol","type":"topic","title":"GeometryType_MultiLine","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType_MultiLine","kind":"symbol","url":"\/documentation\/mapboxcommon\/geometrytype_multiline","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GeometryType_MultiLine"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@EA@MBXGeometryType","text":"GeometryType"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"MBXGeometryType_MultiLine"}]},"doc://com.mapbox.MapboxMaps/s15BitwiseCopyableP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s15BitwiseCopyableP","title":"Swift.BitwiseCopyable","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/Turf":{"title":"Turf","url":"\/documentation\/turf","kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Turf","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/GeometryType/Equatable-Implementations":{"role":"collectionGroup","type":"topic","title":"Equatable Implementations","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType\/Equatable-Implementations","kind":"article","url":"\/documentation\/mapboxcommon\/geometrytype\/equatable-implementations","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/GeometryType_MultiPoint":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType_MultiPoint","type":"topic","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"MBXGeometryType_MultiPoint","kind":"identifier"}],"title":"GeometryType_MultiPoint","url":"\/documentation\/mapboxcommon\/geometrytype_multipoint","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GeometryType_MultiPoint"},{"kind":"text","text":": "},{"text":"GeometryType","kind":"typeIdentifier","preciseIdentifier":"c:@EA@MBXGeometryType"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/GeometryType_Line":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType_Line","role":"symbol","abstract":[],"title":"GeometryType_Line","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GeometryType_Line"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@EA@MBXGeometryType","kind":"typeIdentifier","text":"GeometryType"}],"navigatorTitle":[{"text":"MBXGeometryType_Line","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/geometrytype_line","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/GeometryType":{"navigatorTitle":[{"kind":"identifier","text":"GeometryType"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GeometryType"}],"abstract":[],"url":"\/documentation\/mapboxcommon\/geometrytype","kind":"symbol","title":"GeometryType","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType","type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","abstract":[],"title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","kind":"article","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/GeometryType/init(rawValue:)":{"role":"symbol","type":"topic","title":"init(rawValue:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType\/init(rawValue:)","kind":"symbol","url":"\/documentation\/mapboxcommon\/geometrytype\/init(rawvalue:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt32V","text":"UInt32"},{"kind":"text","text":")"}],"abstract":[]},"doc://com.mapbox.MapboxMaps/SY":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/GeometryType_MultiPolygon":{"role":"symbol","type":"topic","title":"GeometryType_MultiPolygon","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType_MultiPolygon","kind":"symbol","url":"\/documentation\/mapboxcommon\/geometrytype_multipolygon","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GeometryType_MultiPolygon"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@EA@MBXGeometryType","kind":"typeIdentifier","text":"GeometryType"}],"abstract":[],"navigatorTitle":[{"text":"MBXGeometryType_MultiPolygon","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/GeometryType_GeometryCollection":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType_GeometryCollection","title":"GeometryType_GeometryCollection","type":"topic","url":"\/documentation\/mapboxcommon\/geometrytype_geometrycollection","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"GeometryType_GeometryCollection","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GeometryType","kind":"typeIdentifier","preciseIdentifier":"c:@EA@MBXGeometryType"}],"navigatorTitle":[{"text":"MBXGeometryType_GeometryCollection","kind":"identifier"}],"role":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","value":"MBXGeometryType","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"value":[{"kind":"identifier","text":""}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MBXGeometryType"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType_Empty","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType_GeometryCollection","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType_Line","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType_MultiLine","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType_MultiPoint","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType_MultiPolygon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType_Point","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType_Polygon"],"anchor":"Enumeration-Cases","title":"Enumeration Cases","generated":true}]},{"path":"\/relationshipsSections","op":"replace","value":null},{"op":"replace","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBXGeometryType"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType_Polygon\/title","op":"replace","value":"MBXGeometryType_Polygon"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType_Polygon\/fragments","value":[{"text":"MBXGeometryType_Polygon","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType_Point\/title","value":"MBXGeometryType_Point"},{"value":[{"text":"MBXGeometryType_Point","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType_Point\/fragments","op":"replace"},{"op":"replace","value":"MBXGeometryType_Empty","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType_Empty\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType_Empty\/fragments","value":[{"text":"MBXGeometryType_Empty","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType_MultiLine\/title","op":"replace","value":"MBXGeometryType_MultiLine"},{"value":[{"text":"MBXGeometryType_MultiLine","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType_MultiLine\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType_MultiPoint\/title","value":"MBXGeometryType_MultiPoint","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType_MultiPoint\/fragments","value":[{"kind":"identifier","text":"MBXGeometryType_MultiPoint"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType_Line\/title","value":"MBXGeometryType_Line"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType_Line\/fragments","value":[{"text":"MBXGeometryType_Line","kind":"identifier"}]},{"value":"MBXGeometryType","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType\/fragments","op":"replace","value":[{"text":"","kind":"identifier"}]},{"value":[{"text":"MBXGeometryType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType_MultiPolygon\/title","op":"replace","value":"MBXGeometryType_MultiPolygon"},{"value":[{"kind":"identifier","text":"MBXGeometryType_MultiPolygon"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType_MultiPolygon\/fragments","op":"replace"},{"value":"MBXGeometryType_GeometryCollection","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType_GeometryCollection\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType_GeometryCollection\/fragments","value":[{"text":"MBXGeometryType_GeometryCollection","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}