{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProvider"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"onLocationUpdate","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Signal","kind":"typeIdentifier","text":"Signal","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"kind":"text","text":"<["},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location","text":"Location","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXLocation"},{"kind":"text","text":"]> { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"inlineContent":[{"type":"text","text":"An observer will receive a cached value (if any) upon subscription."}],"type":"paragraph"},{"style":"note","name":"Note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"When the first observer is added, the underlying "},{"code":"CLLocationManager","type":"codeVoice"},{"type":"text","text":" instance will"},{"text":" ","type":"text"},{"type":"text","text":"ask for permissions (if needed) and start to produce the location updates. When the last observer is gone it will stop."}]}],"type":"aside"}],"kind":"content"}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProvider\/onLocationUpdate","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/mapboxmaps\/applelocationprovider\/onlocationupdate"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","metadata":{"roleHeading":"Instance Property","externalID":"s:10MapboxMaps21AppleLocationProviderC02onD6UpdateAA6SignalVySaySo11MBXLocationCGGvp","symbolKind":"property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"onLocationUpdate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Signal","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"text":"<[","kind":"text"},{"kind":"typeIdentifier","text":"Location","preciseIdentifier":"c:objc(cs)MBXLocation"},{"kind":"text","text":"]>"}],"modules":[{"name":"MapboxMaps"}],"title":"onLocationUpdate"},"abstract":[{"type":"text","text":"A stream of location updates."}],"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Signal":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Signal","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Signal","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"Signal","abstract":[{"text":"Signal is a typed interface for observing arbitrary values over time.","type":"text"}],"url":"\/documentation\/mapboxmaps\/signal","navigatorTitle":[{"kind":"identifier","text":"Signal"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AppleLocationProvider/onLocationUpdate":{"url":"\/documentation\/mapboxmaps\/applelocationprovider\/onlocationupdate","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onLocationUpdate"},{"kind":"text","text":": "},{"text":"Signal","preciseIdentifier":"s:10MapboxMaps6SignalV","kind":"typeIdentifier"},{"text":"<[","kind":"text"},{"text":"Location","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXLocation"},{"text":"]>","kind":"text"}],"type":"topic","role":"symbol","title":"onLocationUpdate","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProvider\/onLocationUpdate","abstract":[{"text":"A stream of location updates.","type":"text"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","type":"topic","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"title":"MapboxMaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","url":"\/documentation\/overview","title":"MapboxMaps Documentation","type":"topic","role":"collection","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Location-APIs":{"url":"\/documentation\/mapboxmaps\/location-apis","type":"topic","role":"collectionGroup","kind":"article","title":"Location","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AppleLocationProvider":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProvider","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppleLocationProvider"}],"role":"symbol","navigatorTitle":[{"text":"AppleLocationProvider","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxmaps\/applelocationprovider","abstract":[{"type":"text","text":"A location provider based on CoreLocation’s "},{"type":"codeVoice","code":"CLLocationManager"},{"text":".","type":"text"}],"title":"AppleLocationProvider"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Location":{"abstract":[{"text":"Location information.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Location"}],"title":"Location","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location","url":"\/documentation\/mapboxcommon\/location","navigatorTitle":[{"kind":"identifier","text":"Location"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MBXLocation","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/fragments","value":[{"kind":"identifier","text":"MBXLocation"}],"op":"replace"},{"value":[{"text":"MBXLocation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/navigatorTitle"}]}]}