{"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/mbmcustomlayerrenderparameters\/elevationdata"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/mbmcustomlayerrenderparameters\/elevationdata"]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters"]]},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCustomLayerRenderParameters\/elevationData","interfaceLanguage":"swift"},"metadata":{"symbolKind":"property","title":"elevationData","roleHeading":"Instance Property","navigatorTitle":[{"text":"elevationData","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"elevationData","kind":"identifier"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:objc(pl)MBMElevationData","kind":"typeIdentifier","text":"ElevationData"},{"text":")?","kind":"text"}],"role":"symbol","externalID":"c:objc(cs)MBMCustomLayerRenderParameters(py)elevationData","modules":[{"name":"MapboxMaps"}]},"abstract":[{"text":"If terrain is enabled, provides value to elevation data from render thread. Empty if terrain is not enabled.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"elevationData","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"ElevationData","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ElevationData","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MBMElevationData"},{"text":")? { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ElevationData":{"navigatorTitle":[{"text":"ElevationData","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/elevationdata","type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Interface that provides access to elevation data."}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"ElevationData","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ElevationData","title":"ElevationData"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMCustomLayerRenderParameters/elevationData":{"navigatorTitle":[{"text":"elevationData","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCustomLayerRenderParameters\/elevationData","abstract":[{"type":"text","text":"If terrain is enabled, provides value to elevation data from render thread. Empty if terrain is not enabled."}],"role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"elevationData"},{"text":": (any ","kind":"text"},{"text":"ElevationData","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MBMElevationData"},{"text":")?","kind":"text"}],"title":"elevationData","type":"topic","url":"\/documentation\/mapboxmaps\/mbmcustomlayerrenderparameters\/elevationdata"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layers":{"title":"Layers","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers","abstract":[],"url":"\/documentation\/mapboxmaps\/layers","role":"collectionGroup","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerRenderParameters":{"role":"symbol","abstract":[{"type":"text","text":"Parameters that define the current camera position for a "},{"type":"codeVoice","code":"CustomLayerHost::render()"},{"type":"text","text":" function."}],"title":"CustomLayerRenderParameters","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomLayerRenderParameters","kind":"identifier"}],"navigatorTitle":[{"text":"CustomLayerRenderParameters","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters","url":"\/documentation\/mapboxmaps\/customlayerrenderparameters","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"elevationData","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"elevationData","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"id<MBMElevationData>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)MBMElevationData"},{"text":" ","kind":"text"},{"text":"elevationData","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"MBMElevationData","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ElevationData\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ElevationData\/fragments","value":[{"text":"MBMElevationData","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMCustomLayerRenderParameters~1elevationData\/title","value":"elevationData","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMCustomLayerRenderParameters~1elevationData\/fragments","value":[{"kind":"identifier","text":"elevationData"}]},{"op":"replace","value":"MBMCustomLayerRenderParameters","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/title"},{"value":[{"kind":"identifier","text":"MBMCustomLayerRenderParameters"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}