{"metadata":{"symbolKind":"property","title":"renderToTilesIDs","modules":[{"name":"MapboxMaps"}],"externalID":"c:objc(cs)MBMCustomLayerRenderParameters(py)renderToTilesIDs","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"renderToTilesIDs","kind":"identifier"},{"kind":"text","text":": ["},{"text":"CanonicalTileID","preciseIdentifier":"c:objc(cs)MBMCanonicalTileID","kind":"typeIdentifier"},{"kind":"text","text":"]?"}],"role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"text":"renderToTilesIDs","kind":"identifier"}]},"sections":[],"abstract":[{"type":"text","text":"Note! This property is an experimental feature. It can be changed or removed in future versions."}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"renderToTilesIDs","kind":"identifier"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID","text":"CanonicalTileID","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMCanonicalTileID"},{"text":"]? { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/mapboxmaps\/mbmcustomlayerrenderparameters\/rendertotilesids"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/mbmcustomlayerrenderparameters\/rendertotilesids"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCustomLayerRenderParameters\/renderToTilesIDs"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CanonicalTileID":{"type":"topic","role":"symbol","kind":"symbol","title":"CanonicalTileID","navigatorTitle":[{"text":"CanonicalTileID","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID","url":"\/documentation\/mapboxmaps\/canonicaltileid","abstract":[{"text":"Represents a tile coordinate.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CanonicalTileID","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layers":{"title":"Layers","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers","abstract":[],"url":"\/documentation\/mapboxmaps\/layers","role":"collectionGroup","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMCustomLayerRenderParameters/renderToTilesIDs":{"navigatorTitle":[{"text":"renderToTilesIDs","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCustomLayerRenderParameters\/renderToTilesIDs","abstract":[{"text":"Note! This property is an experimental feature. It can be changed or removed in future versions.","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"renderToTilesIDs"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)MBMCanonicalTileID","text":"CanonicalTileID","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"title":"renderToTilesIDs","type":"topic","url":"\/documentation\/mapboxmaps\/mbmcustomlayerrenderparameters\/rendertotilesids"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerRenderParameters":{"role":"symbol","abstract":[{"type":"text","text":"Parameters that define the current camera position for a "},{"type":"codeVoice","code":"CustomLayerHost::render()"},{"type":"text","text":" function."}],"title":"CustomLayerRenderParameters","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomLayerRenderParameters","kind":"identifier"}],"navigatorTitle":[{"text":"CustomLayerRenderParameters","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters","url":"\/documentation\/mapboxmaps\/customlayerrenderparameters","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"renderToTilesIDs","path":"\/metadata\/title","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"renderToTilesIDs"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSArray<MBMCanonicalTileID *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"renderToTilesIDs","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"value":"MBMCanonicalTileID","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/fragments","value":[{"text":"MBMCanonicalTileID","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"renderToTilesIDs","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMCustomLayerRenderParameters~1renderToTilesIDs\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMCustomLayerRenderParameters~1renderToTilesIDs\/fragments","op":"replace","value":[{"kind":"identifier","text":"renderToTilesIDs"}]},{"op":"replace","value":"MBMCustomLayerRenderParameters","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/title"},{"op":"replace","value":[{"text":"MBMCustomLayerRenderParameters","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/fragments"}]}]}