{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"zoom","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCustomLayerRenderParameters\/zoom","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"zoom"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"role":"symbol","title":"zoom","externalID":"c:objc(cs)MBMCustomLayerRenderParameters(py)zoom","symbolKind":"property","navigatorTitle":[{"text":"zoom","kind":"identifier"}],"roleHeading":"Instance Property","modules":[{"name":"MapboxMaps"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/mbmcustomlayerrenderparameters\/zoom"]},{"paths":["\/documentation\/mapboxmaps\/mbmcustomlayerrenderparameters\/zoom"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"type":"text","text":"The zoom of the camera."}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMCustomLayerRenderParameters/zoom":{"navigatorTitle":[{"text":"zoom","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCustomLayerRenderParameters\/zoom","abstract":[{"text":"The zoom of the camera.","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"zoom"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"title":"zoom","type":"topic","url":"\/documentation\/mapboxmaps\/mbmcustomlayerrenderparameters\/zoom"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","type":"topic","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layers":{"title":"Layers","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers","abstract":[],"url":"\/documentation\/mapboxmaps\/layers","role":"collectionGroup","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerRenderParameters":{"role":"symbol","abstract":[{"type":"text","text":"Parameters that define the current camera position for a "},{"type":"codeVoice","code":"CustomLayerHost::render()"},{"type":"text","text":" function."}],"title":"CustomLayerRenderParameters","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomLayerRenderParameters","kind":"identifier"}],"navigatorTitle":[{"text":"CustomLayerRenderParameters","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderParameters","url":"\/documentation\/mapboxmaps\/customlayerrenderparameters","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"zoom","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"zoom","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"double","preciseIdentifier":"c:d","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"zoom","kind":"identifier"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMCustomLayerRenderParameters~1zoom\/title","value":"zoom"},{"value":[{"text":"zoom","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MBMCustomLayerRenderParameters~1zoom\/fragments","op":"replace"},{"value":"MBMCustomLayerRenderParameters","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/title","op":"replace"},{"op":"replace","value":[{"text":"MBMCustomLayerRenderParameters","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderParameters\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}