{"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"LocalizedError.failureReason"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failureReason"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/mapboxcommon\/httprequesterror\/failurereason"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestError\/failureReason","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"modules":[{"name":"MapboxCommon","relatedModules":["Foundation"]}],"role":"symbol","externalID":"s:10Foundation14LocalizedErrorPAAE13failureReasonSSSgvp::SYNTHESIZED::c:objc(cs)MBXHttpRequestError","title":"failureReason","extendedModule":"Foundation","symbolKind":"property","roleHeading":"Instance Property","platforms":[{"introducedAt":"8.0","unavailable":false,"deprecated":false,"name":"iOS","beta":false},{"beta":false,"deprecated":false,"name":"iPadOS","introducedAt":"8.0","unavailable":false},{"deprecated":false,"introducedAt":"8.0","unavailable":false,"beta":false,"name":"Mac Catalyst"},{"beta":false,"name":"macOS","introducedAt":"10.10","deprecated":false,"unavailable":false},{"name":"tvOS","unavailable":false,"deprecated":false,"introducedAt":"9.0","beta":false},{"unavailable":false,"deprecated":false,"name":"watchOS","introducedAt":"2.0","beta":false}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"failureReason","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestError\/LocalizedError-Implementations"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestError/failureReason":{"kind":"symbol","abstract":[],"type":"topic","role":"symbol","title":"failureReason","url":"\/documentation\/mapboxcommon\/httprequesterror\/failurereason","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestError\/failureReason","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failureReason","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestError/LocalizedError-Implementations":{"role":"collectionGroup","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestError\/LocalizedError-Implementations","url":"\/documentation\/mapboxcommon\/httprequesterror\/localizederror-implementations","kind":"article","title":"LocalizedError Implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","type":"topic","url":"\/documentation\/mapboxcommon","abstract":[],"kind":"symbol","title":"MapboxCommon"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","abstract":[],"title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","kind":"article","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestError":{"role":"symbol","type":"topic","abstract":[{"text":"Record which contains detailed information about HTTP error happened during request\/download call.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestError","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"HttpRequestError"}],"url":"\/documentation\/mapboxcommon\/httprequesterror","kind":"symbol","title":"HttpRequestError","navigatorTitle":[{"text":"HttpRequestError","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestError\/title","op":"replace","value":"MBXHttpRequestError"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestError\/fragments","op":"replace","value":[{"text":"MBXHttpRequestError","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestError\/navigatorTitle","value":[{"text":"MBXHttpRequestError","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}