{"metadata":{"title":"initWithStyleURL:geometry:minZoom:maxZoom:pixelRatio:glyphsRasterizationMode:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithStyleURL:geometry:minZoom:maxZoom:pixelRatio:glyphsRasterizationMode:"}],"modules":[{"name":"MapboxMaps"}],"role":"symbol","externalID":"c:objc(cs)MBMOfflineRegionGeometryDefinition(im)initWithStyleURL:geometry:minZoom:maxZoom:pixelRatio:glyphsRasterizationMode:","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"initWithStyleURL:geometry:minZoom:maxZoom:pixelRatio:glyphsRasterizationMode:"}],"symbolKind":"method"},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","variants":[{"paths":["\/documentation\/mapboxmaps\/mbmofflineregiongeometrydefinition\/initwithstyleurl:geometry:minzoom:maxzoom:pixelratio:glyphsrasterizationmode:"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithStyleURL:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"styleURL"},{"kind":"text","text":" "},{"kind":"identifier","text":"geometry:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXGeometry","text":"MBXGeometry","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"geometry"},{"kind":"text","text":" "},{"kind":"identifier","text":"minZoom:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"kind":"internalParam","text":"minZoom"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxZoom:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"kind":"internalParam","text":"maxZoom"},{"kind":"text","text":" "},{"kind":"identifier","text":"pixelRatio:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"float","preciseIdentifier":"c:f"},{"kind":"text","text":") "},{"kind":"internalParam","text":"pixelRatio"},{"kind":"text","text":" "},{"kind":"identifier","text":"glyphsRasterizationMode:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MBMGlyphsRasterizationMode","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode","preciseIdentifier":"c:@E@MBMGlyphsRasterizationMode"},{"kind":"text","text":") "},{"kind":"internalParam","text":"glyphsRasterizationMode"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionGeometryDefinition"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMOfflineRegionGeometryDefinition\/initWithStyleURL:geometry:minZoom:maxZoom:pixelRatio:glyphsRasterizationMode:"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMaps":{"type":"topic","title":"Core Maps API","abstract":[{"type":"text","text":"Maps rendering SDK also known as GL-Native"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","kind":"article","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/coremaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"type":"topic","url":"\/documentation\/mapboxmaps","role":"collection","kind":"symbol","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMOfflineRegionGeometryDefinition/initWithStyleURL:geometry:minZoom:maxZoom:pixelRatio:glyphsRasterizationMode:":{"navigatorTitle":[{"kind":"identifier","text":"initWithStyleURL:geometry:minZoom:maxZoom:pixelRatio:glyphsRasterizationMode:"}],"type":"topic","title":"initWithStyleURL:geometry:minZoom:maxZoom:pixelRatio:glyphsRasterizationMode:","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMOfflineRegionGeometryDefinition\/initWithStyleURL:geometry:minZoom:maxZoom:pixelRatio:glyphsRasterizationMode:","kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/mbmofflineregiongeometrydefinition\/initwithstyleurl:geometry:minzoom:maxzoom:pixelratio:glyphsrasterizationmode:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithStyleURL:geometry:minZoom:maxZoom:pixelRatio:glyphsRasterizationMode:"}],"abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","url":"\/documentation\/overview","role":"collection","abstract":[],"kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionGeometryDefinition":{"role":"symbol","type":"topic","title":"OfflineRegionGeometryDefinition","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OfflineRegionGeometryDefinition"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/offlineregiongeometrydefinition","navigatorTitle":[{"kind":"identifier","text":"OfflineRegionGeometryDefinition"}],"abstract":[{"type":"text","text":"An offline region definition is a geographic region defined by a style URL,"},{"type":"text","text":" "},{"type":"text","text":"a geometry, zoom range, and device pixel ratio. Both "},{"type":"codeVoice","code":"minZoom"},{"type":"text","text":" and "},{"type":"codeVoice","code":"maxZoom"},{"type":"text","text":" must be ≥ 0,"},{"type":"text","text":" "},{"type":"text","text":"and "},{"type":"codeVoice","code":"maxZoom"},{"type":"text","text":" must be ≥ "},{"type":"codeVoice","code":"minZoom"},{"type":"text","text":". The "},{"type":"codeVoice","code":"maxZoom"},{"type":"text","text":" may be ∞, in which case for each tile source,"},{"type":"text","text":" "},{"type":"text","text":"the region will include tiles from "},{"type":"codeVoice","code":"minZoom"},{"type":"text","text":" up to the maximum zoom level provided by that source."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"pixelRatio"},{"type":"text","text":" must be ≥ 0 and should typically be 1.0 or 2.0."}],"deprecated":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionGeometryDefinition"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Offline":{"role":"collectionGroup","title":"Offline Support","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","url":"\/documentation\/mapboxmaps\/offline","abstract":[],"kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Geometry":{"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Geometry","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/geometry","abstract":[],"type":"topic","navigatorTitle":[{"text":"Geometry","kind":"identifier"}],"title":"Geometry","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GlyphsRasterizationMode":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GlyphsRasterizationMode"}],"url":"\/documentation\/mapboxmaps\/glyphsrasterizationmode","abstract":[{"text":"Describes glyphs rasterization modes.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"GlyphsRasterizationMode"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode","type":"topic","title":"GlyphsRasterizationMode"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionGeometryDefinition\/title","value":"MBMOfflineRegionGeometryDefinition"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionGeometryDefinition\/fragments","value":[{"text":"MBMOfflineRegionGeometryDefinition","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionGeometryDefinition\/navigatorTitle","value":[{"text":"MBMOfflineRegionGeometryDefinition","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry\/title","value":"MBXGeometry"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry\/fragments","value":[{"kind":"identifier","text":"MBXGeometry"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry\/navigatorTitle","value":[{"text":"MBXGeometry","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/title","value":"MBMGlyphsRasterizationMode"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/fragments","value":[{"kind":"identifier","text":"MBMGlyphsRasterizationMode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/navigatorTitle","value":[{"text":"MBMGlyphsRasterizationMode","kind":"identifier"}]}]}]}