{"abstract":[{"text":"Sets an interceptor for the current HTTP service instance.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceFactory\/setHttpServiceInterceptorForInterceptor(_:)"},"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/mapboxcommon\/httpservicefactory\/sethttpserviceinterceptorforinterceptor(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxcommon\/httpservicefactory\/sethttpserviceinterceptorforinterceptor(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setHttpServiceInterceptorForInterceptor","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"interceptor","kind":"internalParam"},{"text":": (any ","kind":"text"},{"text":"HttpServiceInterceptorInterface","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceInterceptorInterface","preciseIdentifier":"c:objc(pl)MBXHttpServiceInterceptorInterface"},{"kind":"text","text":")?)"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"interceptor","content":[{"inlineContent":[{"text":"The interceptor to be set.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}],"metadata":{"symbolKind":"method","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setHttpServiceInterceptorForInterceptor"},{"kind":"text","text":"((any "},{"kind":"typeIdentifier","text":"HttpServiceInterceptorInterface","preciseIdentifier":"c:objc(pl)MBXHttpServiceInterceptorInterface"},{"kind":"text","text":")?)"}],"roleHeading":"Type Method","modules":[{"name":"MapboxCommon"}],"externalID":"c:objc(cs)MBXHttpServiceFactory(cm)setHttpServiceInterceptorForInterceptor:","role":"symbol","title":"setHttpServiceInterceptorForInterceptor(_:)","navigatorTitle":[{"text":"setHttpServiceInterceptorForInterceptor:","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceFactory"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpServiceFactory":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceFactory","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HttpServiceFactory","kind":"identifier"}],"title":"HttpServiceFactory","navigatorTitle":[{"text":"HttpServiceFactory","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/httpservicefactory","abstract":[{"text":"HTTP service factory.","type":"text"}],"type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"kind":"article","role":"collection","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpServiceFactory/setHttpServiceInterceptorForInterceptor(_:)":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"setHttpServiceInterceptorForInterceptor:","kind":"identifier"}],"title":"setHttpServiceInterceptorForInterceptor(_:)","url":"\/documentation\/mapboxcommon\/httpservicefactory\/sethttpserviceinterceptorforinterceptor(_:)","abstract":[{"type":"text","text":"Sets an interceptor for the current HTTP service instance."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setHttpServiceInterceptorForInterceptor","kind":"identifier"},{"text":"((any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)MBXHttpServiceInterceptorInterface","text":"HttpServiceInterceptorInterface","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceFactory\/setHttpServiceInterceptorForInterceptor(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"kind":"symbol","title":"MapboxCommon","type":"topic","abstract":[],"role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","url":"\/documentation\/mapboxcommon"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpServiceInterceptorInterface":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceInterceptorInterface","abstract":[{"type":"text","text":"Interface for intercepting and modifying HttpService function calls."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HttpServiceInterceptorInterface"}],"role":"symbol","url":"\/documentation\/mapboxcommon\/httpserviceinterceptorinterface","title":"HttpServiceInterceptorInterface","navigatorTitle":[{"kind":"identifier","text":"HttpServiceInterceptorInterface"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"setHttpServiceInterceptorForInterceptor:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setHttpServiceInterceptorForInterceptor:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"setHttpServiceInterceptorForInterceptor:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qoobjc(pl)MBXHttpServiceInterceptorInterface","kind":"typeIdentifier","text":"id<MBXHttpServiceInterceptorInterface>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"interceptor"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"name":"interceptor","content":[{"inlineContent":[{"text":"The interceptor to be set.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceFactory\/title","op":"replace","value":"MBXHttpServiceFactory"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceFactory\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXHttpServiceFactory"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceFactory\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBXHttpServiceFactory"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceFactory~1setHttpServiceInterceptorForInterceptor(_:)\/title","op":"replace","value":"setHttpServiceInterceptorForInterceptor:"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceFactory~1setHttpServiceInterceptorForInterceptor(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setHttpServiceInterceptorForInterceptor:"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceInterceptorInterface\/title","op":"replace","value":"MBXHttpServiceInterceptorInterface"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceInterceptorInterface\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXHttpServiceInterceptorInterface"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceInterceptorInterface\/navigatorTitle","op":"replace","value":[{"text":"MBXHttpServiceInterceptorInterface","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}