{"sections":[],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider\/removeLocationObserver(for:)","interfaceLanguage":"swift"},"metadata":{"title":"removeLocationObserver(for:)","modules":[{"name":"MapboxCommon"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeLocationObserver","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"LocationObserver","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MBXLocationObserver"},{"text":")","kind":"text"}],"required":true,"navigatorTitle":[{"text":"removeLocationObserverForObserver:","kind":"identifier"}],"roleHeading":"Instance Method","role":"symbol","externalID":"c:objc(pl)MBXLocationProvider(im)removeLocationObserverForObserver:","symbolKind":"method"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Removes the observer from this instance of LocationProvider. If the observer","type":"text"},{"text":" ","type":"text"},{"text":"is not registered, this is no-op.","type":"text"},{"text":" ","type":"text"},{"text":"It is expected that if there are no observers, the LocationProvider","type":"text"},{"text":" ","type":"text"},{"text":"will stop automatically.","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/locationprovider\/removelocationobserver(for:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/locationprovider\/removelocationobserver(for:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeLocationObserver","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"observer","kind":"internalParam"},{"text":": any ","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationObserver","preciseIdentifier":"c:objc(pl)MBXLocationObserver","text":"LocationObserver","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"parameters":[{"name":"observer","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An observer to remove."}]}]}],"kind":"parameters"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationProvider":{"title":"LocationProvider","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationProvider","kind":"identifier"}],"navigatorTitle":[{"text":"LocationProvider","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapboxcommon\/locationprovider","kind":"symbol","abstract":[{"type":"text","text":"Location provider that provides locations"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Location-APIs":{"abstract":[],"type":"topic","url":"\/documentation\/mapboxmaps\/location-apis","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","role":"collectionGroup","kind":"article","title":"Location"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationObserver":{"title":"LocationObserver","type":"topic","abstract":[{"text":"Observer for getting updates from a LocationProvider.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationObserver"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationObserver","navigatorTitle":[{"kind":"identifier","text":"LocationObserver"}],"role":"symbol","url":"\/documentation\/mapboxcommon\/locationobserver"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"type":"topic","url":"\/documentation\/mapboxmaps","role":"collection","kind":"symbol","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","url":"\/documentation\/overview","role":"collection","abstract":[],"kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationProvider/removeLocationObserver(for:)":{"type":"topic","kind":"symbol","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeLocationObserver"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:objc(pl)MBXLocationObserver","kind":"typeIdentifier","text":"LocationObserver"},{"kind":"text","text":")"}],"abstract":[{"text":"Removes the observer from this instance of LocationProvider. If the observer","type":"text"},{"text":" ","type":"text"},{"text":"is not registered, this is no-op.","type":"text"},{"text":" ","type":"text"},{"text":"It is expected that if there are no observers, the LocationProvider","type":"text"},{"text":" ","type":"text"},{"text":"will stop automatically.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider\/removeLocationObserver(for:)","navigatorTitle":[{"kind":"identifier","text":"removeLocationObserverForObserver:"}],"url":"\/documentation\/mapboxcommon\/locationprovider\/removelocationobserver(for:)","title":"removeLocationObserver(for:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"removeLocationObserverForObserver:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"removeLocationObserverForObserver:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"removeLocationObserverForObserver:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)MBXLocationObserver","text":"id<MBXLocationObserver>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"observer"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"An observer to remove.","type":"text"}],"type":"paragraph"}],"name":"observer"}]}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/title","value":"MBXLocationProvider"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/fragments","op":"replace","value":[{"text":"MBXLocationProvider","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/navigatorTitle","op":"replace","value":[{"text":"MBXLocationProvider","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/title","op":"replace","value":"MBXLocationObserver"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXLocationObserver"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/navigatorTitle","op":"replace","value":[{"text":"MBXLocationObserver","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider~1removeLocationObserver(for:)\/title","value":"removeLocationObserverForObserver:","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider~1removeLocationObserver(for:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"removeLocationObserverForObserver:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}