{"variants":[{"paths":["\/documentation\/mapboxcommon\/httpservicecancellationcallback"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxcommon\/httpservicecancellationcallback"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"title":"HttpServiceCancellationCallback","roleHeading":"Type Alias","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"HttpServiceCancellationCallback","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"HttpServiceCancellationCallback"}],"modules":[{"name":"MapboxCommon"}],"externalID":"c:MBXHttpServiceCancellationCallback.h@T@MBXHttpServiceCancellationCallback","symbolKind":"typealias","role":"symbol"},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceCancellationCallback","interfaceLanguage":"swift"},"sections":[],"abstract":[{"text":"Callback for the HTTP request cancelled event.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"HttpServiceCancellationCallback","kind":"identifier"},{"text":" = (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V","text":"UInt64"},{"text":", ","kind":"text"},{"text":"HttpRequest","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest","preciseIdentifier":"c:objc(cs)MBXHttpRequest"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Handle given by the request() method."}],"type":"paragraph"}],"name":"id"},{"name":"request","content":[{"type":"paragraph","inlineContent":[{"text":"Original HttpRequest passed to the request() method.","type":"text"}]}]}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","url":"\/documentation\/overview","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"role":"collection","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"kind":"symbol","url":"\/documentation\/mapboxcommon","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","title":"MapboxCommon","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpServiceCancellationCallback":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"HttpServiceCancellationCallback"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"HttpServiceCancellationCallback","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceCancellationCallback","url":"\/documentation\/mapboxcommon\/httpservicecancellationcallback","abstract":[{"type":"text","text":"Callback for the HTTP request cancelled event."}],"title":"HttpServiceCancellationCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequest":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest","navigatorTitle":[{"text":"HttpRequest","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/httprequest","role":"symbol","abstract":[{"text":"HttpRequest holds basic information for construction of an HTTP request","type":"text"}],"title":"HttpRequest","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"HttpRequest","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Alias"},{"path":"\/metadata\/title","value":"MBXHttpServiceCancellationCallback","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"typealias"},{"value":[{"kind":"identifier","text":"MBXHttpServiceCancellationCallback"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MBXHttpServiceCancellationCallback"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"typedef"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:BFv(#k#*$objc(cs)MBXHttpRequest)","text":"void (^)(unsigned long long, MBXHttpRequest *)"},{"text":" ","kind":"text"},{"text":"MBXHttpServiceCancellationCallback","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceCancellationCallback\/title","value":"MBXHttpServiceCancellationCallback","op":"replace"},{"value":[{"kind":"identifier","text":"MBXHttpServiceCancellationCallback"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceCancellationCallback\/fragments"},{"value":[{"text":"MBXHttpServiceCancellationCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceCancellationCallback\/navigatorTitle","op":"replace"},{"value":"MBXHttpRequest","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest\/title"},{"value":[{"kind":"identifier","text":"MBXHttpRequest"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest\/navigatorTitle","value":[{"text":"MBXHttpRequest","kind":"identifier"}]}]}]}