{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon"]]},"topicSections":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType\/canceled","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType\/diskFull","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType\/doesNotExist","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType\/other","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType\/tileCountExceeded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType\/tilesetDescriptor"],"generated":true},{"anchor":"Initializers","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType\/init(rawValue:)"],"generated":true,"title":"Initializers"},{"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType\/Equatable-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType\/RawRepresentable-Implementations"],"generated":true}],"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/s15BitwiseCopyableP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH","doc:\/\/com.mapbox.MapboxMaps\/SY","doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"]}],"sections":[],"variants":[{"paths":["\/documentation\/mapboxcommon\/tileregionerrortype"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/tileregionerrortype"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType"},"kind":"symbol","metadata":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileRegionErrorType","kind":"identifier"}],"modules":[{"name":"MapboxCommon"}],"externalID":"c:@E@MBXTileRegionErrorType","roleHeading":"Enumeration","navigatorTitle":[{"text":"TileRegionErrorType","kind":"identifier"}],"role":"symbol","title":"TileRegionErrorType","symbolKind":"enum"},"abstract":[{"text":"Describes the reason for a tile region download request failure.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"TileRegionErrorType","kind":"identifier"}]}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionErrorType/RawRepresentable-Implementations":{"url":"\/documentation\/mapboxcommon\/tileregionerrortype\/rawrepresentable-implementations","title":"RawRepresentable Implementations","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType\/RawRepresentable-Implementations","abstract":[],"role":"collectionGroup","type":"topic","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionErrorType":{"role":"symbol","navigatorTitle":[{"text":"TileRegionErrorType","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TileRegionErrorType","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/tileregionerrortype","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType","title":"TileRegionErrorType","kind":"symbol","abstract":[{"type":"text","text":"Describes the reason for a tile region download request failure."}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionErrorType/tileCountExceeded":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType\/tileCountExceeded","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"tileCountExceeded","kind":"identifier"}],"title":"TileRegionErrorType.tileCountExceeded","navigatorTitle":[{"text":"MBXTileRegionErrorTypeTileCountExceeded","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/mapboxcommon\/tileregionerrortype\/tilecountexceeded","role":"symbol","abstract":[{"text":"The region contains more tiles than allowed.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","url":"\/documentation\/overview","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"role":"collection","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionErrorType/init(rawValue:)":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType\/init(rawValue:)","title":"init(rawValue:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}],"url":"\/documentation\/mapboxcommon\/tileregionerrortype\/init(rawvalue:)","type":"topic"},"doc://com.mapbox.MapboxMaps/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"},"doc://com.mapbox.MapboxMaps/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ"},"doc://com.mapbox.MapboxMaps/s15BitwiseCopyableP":{"title":"Swift.BitwiseCopyable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s15BitwiseCopyableP"},"doc://com.mapbox.MapboxMaps/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SY"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionErrorType/doesNotExist":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"doesNotExist"}],"abstract":[{"type":"text","text":"tile region does not exist."}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"MBXTileRegionErrorTypeDoesNotExist","kind":"identifier"}],"title":"TileRegionErrorType.doesNotExist","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType\/doesNotExist","url":"\/documentation\/mapboxcommon\/tileregionerrortype\/doesnotexist"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"kind":"symbol","url":"\/documentation\/mapboxcommon","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","title":"MapboxCommon","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionErrorType/Equatable-Implementations":{"title":"Equatable Implementations","url":"\/documentation\/mapboxcommon\/tileregionerrortype\/equatable-implementations","type":"topic","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType\/Equatable-Implementations","kind":"article","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionErrorType/tilesetDescriptor":{"abstract":[{"text":"Tileset descriptors resolving failed.","type":"text"}],"title":"TileRegionErrorType.tilesetDescriptor","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tilesetDescriptor"}],"type":"topic","url":"\/documentation\/mapboxcommon\/tileregionerrortype\/tilesetdescriptor","role":"symbol","navigatorTitle":[{"text":"MBXTileRegionErrorTypeTilesetDescriptor","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType\/tilesetDescriptor"},"doc://com.mapbox.MapboxMaps/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionErrorType/diskFull":{"url":"\/documentation\/mapboxcommon\/tileregionerrortype\/diskfull","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType\/diskFull","type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"diskFull","kind":"identifier"}],"abstract":[{"type":"text","text":"There is no available space to store the resources"}],"title":"TileRegionErrorType.diskFull","navigatorTitle":[{"text":"MBXTileRegionErrorTypeDiskFull","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionErrorType/canceled":{"abstract":[{"type":"text","text":"The operation was canceled."}],"title":"TileRegionErrorType.canceled","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"canceled"}],"type":"topic","url":"\/documentation\/mapboxcommon\/tileregionerrortype\/canceled","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBXTileRegionErrorTypeCanceled"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType\/canceled"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionErrorType/other":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType\/other","title":"TileRegionErrorType.other","abstract":[{"type":"text","text":"Other reason."}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"other","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/tileregionerrortype\/other","type":"topic","navigatorTitle":[{"text":"MBXTileRegionErrorTypeOther","kind":"identifier"}],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"value":"MBXTileRegionErrorType","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"value":[{"kind":"identifier","text":"MBXTileRegionErrorType"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"MBXTileRegionErrorType","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType\/canceled","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType\/diskFull","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType\/doesNotExist","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType\/other","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType\/tileCountExceeded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType\/tilesetDescriptor"],"anchor":"Enumeration-Cases","title":"Enumeration Cases","generated":true}],"op":"replace","path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBXTileRegionErrorType"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"MBXTileRegionErrorType","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionErrorType\/title","op":"replace"},{"value":[{"text":"MBXTileRegionErrorType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionErrorType\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionErrorType\/navigatorTitle","value":[{"text":"MBXTileRegionErrorType","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionErrorType~1tileCountExceeded\/title","value":"MBXTileRegionErrorTypeTileCountExceeded"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionErrorType~1tileCountExceeded\/fragments","value":[{"text":"MBXTileRegionErrorTypeTileCountExceeded","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionErrorType~1doesNotExist\/title","value":"MBXTileRegionErrorTypeDoesNotExist"},{"value":[{"kind":"identifier","text":"MBXTileRegionErrorTypeDoesNotExist"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionErrorType~1doesNotExist\/fragments"},{"value":"MBXTileRegionErrorTypeTilesetDescriptor","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionErrorType~1tilesetDescriptor\/title","op":"replace"},{"value":[{"text":"MBXTileRegionErrorTypeTilesetDescriptor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionErrorType~1tilesetDescriptor\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionErrorType~1diskFull\/title","value":"MBXTileRegionErrorTypeDiskFull","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionErrorType~1diskFull\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXTileRegionErrorTypeDiskFull"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionErrorType~1canceled\/title","value":"MBXTileRegionErrorTypeCanceled","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionErrorType~1canceled\/fragments","value":[{"kind":"identifier","text":"MBXTileRegionErrorTypeCanceled"}],"op":"replace"},{"op":"replace","value":"MBXTileRegionErrorTypeOther","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionErrorType~1other\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionErrorType~1other\/fragments","value":[{"text":"MBXTileRegionErrorTypeOther","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}