{"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/setFileAllowHeaderForAllow(_:)","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"Set file allow header."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setFileAllowHeaderForAllow","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"allow","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Boolean to allow or disallow setting a file header."},{"type":"text","text":" "},{"type":"text","text":"Default is true"}],"type":"paragraph"}],"name":"allow"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration"]]},"variants":[{"paths":["\/documentation\/mapboxcommon\/persistentlogconfiguration\/setfileallowheaderforallow(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxcommon\/persistentlogconfiguration\/setfileallowheaderforallow(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"MapboxCommon"}],"role":"symbol","title":"setFileAllowHeaderForAllow(_:)","roleHeading":"Type Method","externalID":"c:objc(cs)MBXPersistentLogConfiguration(cm)setFileAllowHeaderForAllow:","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setFileAllowHeaderForAllow"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"setFileAllowHeaderForAllow:"}],"symbolKind":"method"},"kind":"symbol","references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PersistentLogConfiguration/setFileAllowHeaderForAllow(_:)":{"navigatorTitle":[{"text":"setFileAllowHeaderForAllow:","kind":"identifier"}],"abstract":[{"text":"Set file allow header.","type":"text"}],"url":"\/documentation\/mapboxcommon\/persistentlogconfiguration\/setfileallowheaderforallow(_:)","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setFileAllowHeaderForAllow","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration\/setFileAllowHeaderForAllow(_:)","kind":"symbol","title":"setFileAllowHeaderForAllow(_:)"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","kind":"article","type":"topic","title":"MapboxMaps Documentation","abstract":[],"url":"\/documentation\/overview","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"type":"topic","role":"collection","url":"\/documentation\/mapboxcommon","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","abstract":[],"kind":"symbol","title":"MapboxCommon"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PersistentLogConfiguration":{"navigatorTitle":[{"text":"PersistentLogConfiguration","kind":"identifier"}],"kind":"symbol","abstract":[],"type":"topic","title":"PersistentLogConfiguration","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PersistentLogConfiguration","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/persistentlogconfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"setFileAllowHeaderForAllow:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setFileAllowHeaderForAllow:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"setFileAllowHeaderForAllow:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"allow"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"name":"allow","content":[{"inlineContent":[{"text":"Boolean to allow or disallow setting a file header.","type":"text"},{"text":" ","type":"text"},{"text":"Default is true","type":"text"}],"type":"paragraph"}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"setFileAllowHeaderForAllow:","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1setFileAllowHeaderForAllow(_:)\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration~1setFileAllowHeaderForAllow(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setFileAllowHeaderForAllow:"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration\/title","op":"replace","value":"MBXPersistentLogConfiguration"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration\/fragments","op":"replace","value":[{"text":"MBXPersistentLogConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration\/navigatorTitle","op":"replace","value":[{"text":"MBXPersistentLogConfiguration","kind":"identifier"}]}]}]}