{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Style","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/stylemanager\/setcustomgeometrysourcetiledata(forsourceid:tileid:features:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/setCustomGeometrySourceTileData(forSourceId:tileId:features:)"},"abstract":[{"type":"text","text":"Set tile data of a custom geometry."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setCustomGeometrySourceTileData"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forSourceId"},{"kind":"text","text":" "},{"text":"sourceId","kind":"internalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tileId"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MBMCanonicalTileID","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID","text":"CanonicalTileID","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"features","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps7Featurea","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Feature","text":"Feature"},{"kind":"text","text":"]) "},{"kind":"keyword","text":"throws"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"sourceId","content":[{"inlineContent":[{"text":"Style source identifier","type":"text"}],"type":"paragraph"}]},{"name":"tileId","content":[{"inlineContent":[{"type":"text","text":"Identifier of the tile"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"An array of features to add"}],"type":"paragraph"}],"name":"features"}],"kind":"parameters"}],"metadata":{"externalID":"s:10MapboxMaps12StyleManagerC31setCustomGeometrySourceTileData03forH2Id04tileL08featuresySS_So012MBMCanonicalI2IDCSay4Turf7FeatureVGtKF","role":"symbol","symbolKind":"method","modules":[{"name":"MapboxMaps"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setCustomGeometrySourceTileData","kind":"identifier"},{"kind":"text","text":"("},{"text":"forSourceId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"tileId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMCanonicalTileID","text":"CanonicalTileID"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"features"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps7Featurea","kind":"typeIdentifier","text":"Feature"},{"kind":"text","text":"]) "},{"text":"throws","kind":"keyword"}],"roleHeading":"Instance Method","title":"setCustomGeometrySourceTileData(forSourceId:tileId:features:)"},"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapboxMap"}],"url":"\/documentation\/mapboxmaps\/mapboxmap","navigatorTitle":[{"kind":"identifier","text":"MapboxMap"}],"role":"symbol","title":"MapboxMap","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Provides access to the map model, including the camera, style, observable map events,"},{"text":" ","type":"text"},{"text":"and querying rendered features.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/setCustomGeometrySourceTileData(forSourceId:tileId:features:)":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/stylemanager\/setcustomgeometrysourcetiledata(forsourceid:tileid:features:)","role":"symbol","type":"topic","abstract":[{"text":"Set tile data of a custom geometry.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setCustomGeometrySourceTileData"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forSourceId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"tileId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMCanonicalTileID","text":"CanonicalTileID","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"features","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps7Featurea","kind":"typeIdentifier","text":"Feature"},{"kind":"text","text":"]) "},{"text":"throws","kind":"keyword"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/setCustomGeometrySourceTileData(forSourceId:tileId:features:)","title":"setCustomGeometrySourceTileData(forSourceId:tileId:features:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Snapshotter":{"title":"Snapshotter","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Snapshotter","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter","url":"\/documentation\/mapboxmaps\/snapshotter","abstract":[{"text":"A utility class for capturing styled map snapshots.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"Snapshotter"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StyleManager"}],"type":"topic","title":"StyleManager","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager","kind":"symbol","navigatorTitle":[{"text":"StyleManager","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/stylemanager","abstract":[{"text":"Style manager is a base class for ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","isActive":true,"type":"reference"},{"type":"text","text":" and "},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter","isActive":true},{"text":" that provides provides methods to manipulate Map Style at runtime.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","kind":"article","title":"MapboxMaps Documentation","abstract":[],"role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Feature":{"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"Feature","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Feature","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Feature"}],"title":"Feature","abstract":[{"text":"An object representing a spatially bounded geometry.","type":"text"}],"url":"\/documentation\/mapboxmaps\/feature"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CanonicalTileID":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"CanonicalTileID","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID","url":"\/documentation\/mapboxmaps\/canonicaltileid","abstract":[{"text":"Represents a tile coordinate.","type":"text"}],"role":"symbol","title":"CanonicalTileID","type":"topic","navigatorTitle":[{"text":"CanonicalTileID","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Style":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Style","abstract":[],"url":"\/documentation\/mapboxmaps\/style","title":"Style","role":"collectionGroup","kind":"article"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/title","value":"MBMCanonicalTileID","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/fragments","value":[{"kind":"identifier","text":"MBMCanonicalTileID"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/navigatorTitle","op":"replace","value":[{"text":"MBMCanonicalTileID","kind":"identifier"}]}]}]}