{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Style","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/sourcePropertyDefaultValue(for:property:)"},"metadata":{"role":"symbol","symbolKind":"method","externalID":"s:10MapboxMaps12StyleManagerC26sourcePropertyDefaultValue3for8propertySo08MBMStylefH0CSS_SStFZ","title":"sourcePropertyDefaultValue(for:property:)","modules":[{"name":"MapboxMaps"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sourcePropertyDefaultValue","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"property"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMStylePropertyValue","kind":"typeIdentifier","text":"StylePropertyValue"}],"roleHeading":"Type Method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/stylemanager\/sourcepropertydefaultvalue(for:property:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"sourcePropertyDefaultValue","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"sourceType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"property"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)MBMStylePropertyValue","text":"StylePropertyValue","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValue","kind":"typeIdentifier"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Style source type."}]}],"name":"sourceType"},{"content":[{"inlineContent":[{"text":"Style source property name.","type":"text"}],"type":"paragraph"}],"name":"property"}]},{"content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"type":"text","text":"The default value for the named property for the sources with type sourceType."}],"type":"paragraph"}],"kind":"content"}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","abstract":[{"text":"Gets the default value of style source property.","type":"text"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Snapshotter":{"url":"\/documentation\/mapboxmaps\/snapshotter","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter","navigatorTitle":[{"text":"Snapshotter","kind":"identifier"}],"abstract":[{"type":"text","text":"A utility class for capturing styled map snapshots."}],"type":"topic","role":"symbol","title":"Snapshotter","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Snapshotter","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap":{"title":"MapboxMap","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MapboxMap","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MapboxMap"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","role":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap","abstract":[{"text":"Provides access to the map model, including the camera, style, observable map events,","type":"text"},{"text":" ","type":"text"},{"text":"and querying rendered features.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Style":{"url":"\/documentation\/mapboxmaps\/style","type":"topic","title":"Style","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Style","kind":"article","abstract":[],"role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/sourcePropertyDefaultValue(for:property:)":{"url":"\/documentation\/mapboxmaps\/stylemanager\/sourcepropertydefaultvalue(for:property:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/sourcePropertyDefaultValue(for:property:)","title":"sourcePropertyDefaultValue(for:property:)","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sourcePropertyDefaultValue"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"property"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"StylePropertyValue","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMStylePropertyValue"}],"role":"symbol","type":"topic","abstract":[{"text":"Gets the default value of style source property.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","url":"\/documentation\/overview","title":"MapboxMaps Documentation","type":"topic","role":"collection","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","type":"topic","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"title":"MapboxMaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager":{"title":"StyleManager","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StyleManager"}],"navigatorTitle":[{"text":"StyleManager","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager","role":"symbol","url":"\/documentation\/mapboxmaps\/stylemanager","abstract":[{"text":"Style manager is a base class for ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","isActive":true},{"text":" and ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Snapshotter","isActive":true},{"text":" that provides provides methods to manipulate Map Style at runtime.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StylePropertyValue":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StylePropertyValue","role":"symbol","title":"StylePropertyValue","navigatorTitle":[{"text":"StylePropertyValue","kind":"identifier"}],"abstract":[{"text":"Holds a style property value with meta data.","type":"text"}],"url":"\/documentation\/mapboxmaps\/stylepropertyvalue","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StylePropertyValue","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MBMStylePropertyValue","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValue\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValue\/fragments","value":[{"kind":"identifier","text":"MBMStylePropertyValue"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1StylePropertyValue\/navigatorTitle","value":[{"kind":"identifier","text":"MBMStylePropertyValue"}]}]}]}