{"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileStoreUsageMode"}],"languages":["swift"]}]}],"topicSections":[{"anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreUsageMode\/disabled","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreUsageMode\/readAndUpdate","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreUsageMode\/readOnly"],"generated":true,"title":"Enumeration Cases"},{"anchor":"Initializers","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreUsageMode\/init(rawValue:)"],"generated":true,"title":"Initializers"},{"anchor":"Default-Implementations","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreUsageMode\/Equatable-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreUsageMode\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"relationshipsSections":[{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/s15BitwiseCopyableP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH","doc:\/\/com.mapbox.MapboxMaps\/SY","doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"],"title":"Conforms To"}],"variants":[{"paths":["\/documentation\/mapboxmaps\/tilestoreusagemode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/tilestoreusagemode"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Describes tile store usage modes."}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreUsageMode","interfaceLanguage":"swift"},"sections":[],"seeAlsoSections":[{"anchor":"TileStore","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStoreOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudget","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInMegabytes","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInTiles","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCoverOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegion","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileRegionError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgress","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TilesetDescriptor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TilesetDescriptorOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgressCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileRegionError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileDataDomain","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgress","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateResult","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgressCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingErrorType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClearCacheError"],"generated":true,"title":"TileStore"}],"metadata":{"modules":[{"name":"MapboxMaps"}],"navigatorTitle":[{"kind":"identifier","text":"TileStoreUsageMode"}],"externalID":"c:@E@MBMTileStoreUsageMode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileStoreUsageMode","kind":"identifier"}],"roleHeading":"Enumeration","title":"TileStoreUsageMode","symbolKind":"enum","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/CacheClearingErrorType":{"abstract":[{"text":"Describes the reason for a cache clearing failure.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingErrorType","navigatorTitle":[{"text":"CacheClearingErrorType","kind":"identifier"}],"title":"CacheClearingErrorType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CacheClearingErrorType","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/mapboxcommon\/cacheclearingerrortype","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudgetInMegabytes":{"title":"TileCacheBudgetInMegabytes","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInMegabytes","type":"topic","url":"\/documentation\/mapboxmaps\/tilecachebudgetinmegabytes","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileCacheBudgetInMegabytes"}],"navigatorTitle":[{"kind":"identifier","text":"TileCacheBudgetInMegabytes"}],"abstract":[{"text":"Tile cache budget in megabytes.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStoreUsageMode/disabled":{"title":"TileStoreUsageMode.disabled","url":"\/documentation\/mapboxmaps\/tilestoreusagemode\/disabled","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreUsageMode\/disabled","abstract":[{"text":"Tile store usage is disabled.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disabled","kind":"identifier"}],"navigatorTitle":[{"text":"MBMTileStoreUsageModeDisabled","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileStore":{"title":"TileStore","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileStore"}],"navigatorTitle":[{"kind":"identifier","text":"TileStore"}],"type":"topic","url":"\/documentation\/mapboxcommon\/tilestore","role":"symbol","abstract":[{"text":"TileStore manages downloads and storage for requests to tile-related API endpoints, enforcing a disk usage","type":"text"},{"type":"text","text":" "},{"type":"text","text":"quota: tiles available on disk may be deleted to make room for a new download. This interface can be used by an"},{"type":"text","text":" "},{"type":"text","text":"app developer to set the disk quota. The rest of TileStore API is intended for native SDK consumption only."}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudgetType":{"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetType","role":"symbol","navigatorTitle":[{"text":"TileCacheBudgetType","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileCacheBudgetType","kind":"identifier"}],"type":"topic","kind":"symbol","title":"TileCacheBudgetType","url":"\/documentation\/mapboxmaps\/tilecachebudgettype"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStoreUsageMode/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","url":"\/documentation\/mapboxmaps\/tilestoreusagemode\/rawrepresentable-implementations","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreUsageMode\/RawRepresentable-Implementations","abstract":[],"role":"collectionGroup","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCoverOptions":{"url":"\/documentation\/mapboxmaps\/tilecoveroptions","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileCoverOptions"}],"role":"symbol","title":"TileCoverOptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCoverOptions","type":"topic","abstract":[{"text":"Various options needed for tile cover.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"TileCoverOptions"}],"kind":"symbol","tags":[{"type":"spi","text":"SPI"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadProgress":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileRegionLoadProgress","kind":"identifier"}],"type":"topic","title":"TileRegionLoadProgress","navigatorTitle":[{"text":"TileRegionLoadProgress","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgress","url":"\/documentation\/mapboxcommon\/tileregionloadprogress","abstract":[{"text":"A tile region’s load progress includes counts","type":"text"},{"text":" ","type":"text"},{"text":"of the number of resources that have completed downloading","type":"text"},{"text":" ","type":"text"},{"text":"and the total number of resources that are required.","type":"text"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudgetInTiles":{"title":"TileCacheBudgetInTiles","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInTiles","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileCacheBudgetInTiles"}],"navigatorTitle":[{"kind":"identifier","text":"TileCacheBudgetInTiles"}],"type":"topic","url":"\/documentation\/mapboxmaps\/tilecachebudgetintiles","role":"symbol","abstract":[{"type":"text","text":"Tile cache budget in tiles."}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"kind":"article","role":"collection","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileDataDomain":{"url":"\/documentation\/mapboxcommon\/tiledatadomain","title":"TileDataDomain","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileDataDomain"}],"abstract":[{"type":"text","text":"Describes the tiles data domain."}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileDataDomain","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TileDataDomain"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CanonicalTileID":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CanonicalTileID"}],"title":"CanonicalTileID","type":"topic","url":"\/documentation\/mapboxmaps\/canonicaltileid","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CanonicalTileID"}],"kind":"symbol","abstract":[{"type":"text","text":"Represents a tile coordinate."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadProgressCallback":{"title":"TileRegionLoadProgressCallback","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgressCallback","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileRegionLoadProgressCallback"}],"navigatorTitle":[{"kind":"identifier","text":"TileRegionLoadProgressCallback"}],"type":"topic","url":"\/documentation\/mapboxcommon\/tileregionloadprogresscallback","role":"symbol","abstract":[{"text":"Callback Invoked to report the progess of the tile region loading operation.","type":"text"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegion":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TileRegion"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegion","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileRegion"}],"url":"\/documentation\/mapboxcommon\/tileregion","title":"TileRegion","abstract":[{"type":"text","text":"TileRegion represents an identifiable geographic tile region with metadata"}]},"doc://com.mapbox.MapboxMaps/s8SendableP":{"title":"Swift.Sendable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s8SendableP","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/SQ":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStoreUsageMode/readOnly":{"type":"topic","url":"\/documentation\/mapboxmaps\/tilestoreusagemode\/readonly","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"readOnly","kind":"identifier"}],"navigatorTitle":[{"text":"MBMTileStoreUsageModeReadOnly","kind":"identifier"}],"abstract":[{"type":"text","text":"Tile store enabled for accessing loaded tile packs."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreUsageMode\/readOnly","kind":"symbol","role":"symbol","title":"TileStoreUsageMode.readOnly"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileStoreOptions":{"navigatorTitle":[{"kind":"identifier","text":"TileStoreOptions"}],"abstract":[{"text":"These constants can be used as keys for TileStore::setOption to configure further aspects of a TileStore instance.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileStoreOptions"}],"kind":"symbol","url":"\/documentation\/mapboxcommon\/tilestoreoptions","role":"symbol","type":"topic","title":"TileStoreOptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStoreOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateProgress":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileRegionEstimateProgress"}],"type":"topic","title":"TileRegionEstimateProgress","role":"symbol","url":"\/documentation\/mapboxcommon\/tileregionestimateprogress","navigatorTitle":[{"kind":"identifier","text":"TileRegionEstimateProgress"}],"kind":"symbol","abstract":[{"type":"text","text":"A tile region’s estimate progress includes counts of the number of resources that have"},{"type":"text","text":" "},{"type":"text","text":"been estimated and the total number of resources as well as a partial result with the"},{"type":"text","text":" "},{"type":"text","text":"current estimate, calculated using the data available at the moment."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgress"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStoreObserver":{"navigatorTitle":[{"kind":"identifier","text":"TileStoreObserver"}],"url":"\/documentation\/mapboxmaps\/tilestoreobserver","abstract":[],"kind":"symbol","title":"TileStoreObserver","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreObserver","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileStoreObserver"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStoreUsageMode/readAndUpdate":{"title":"TileStoreUsageMode.readAndUpdate","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"readAndUpdate"}],"abstract":[{"text":"Tile store enabled for accessing local tile packs and for loading new tile packs from server.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBMTileStoreUsageModeReadAndUpdate"}],"type":"topic","url":"\/documentation\/mapboxmaps\/tilestoreusagemode\/readandupdate","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreUsageMode\/readAndUpdate"},"doc://com.mapbox.MapboxMaps/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ClearCacheError":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ClearCacheError","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ClearCacheError"}],"title":"ClearCacheError","type":"topic","url":"\/documentation\/mapboxmaps\/clearcacheerror","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClearCacheError"}],"kind":"symbol","abstract":[{"type":"text","text":"Describes the reason for a cache clearing failure."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStoreUsageMode/Equatable-Implementations":{"url":"\/documentation\/mapboxmaps\/tilestoreusagemode\/equatable-implementations","abstract":[],"role":"collectionGroup","type":"topic","kind":"article","title":"Equatable Implementations","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreUsageMode\/Equatable-Implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TilesetDescriptorOptions":{"url":"\/documentation\/mapboxmaps\/tilesetdescriptoroptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TilesetDescriptorOptions"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TilesetDescriptorOptions","type":"topic","abstract":[{"text":"Describes the tileset descriptor option values.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"TilesetDescriptorOptions"}],"title":"TilesetDescriptorOptions","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStoreUsageMode":{"title":"TileStoreUsageMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileStoreUsageMode"}],"abstract":[{"text":"Describes tile store usage modes.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreUsageMode","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TileStoreUsageMode"}],"url":"\/documentation\/mapboxmaps\/tilestoreusagemode"},"doc://com.mapbox.MapboxMaps/s15BitwiseCopyableP":{"title":"Swift.BitwiseCopyable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s15BitwiseCopyableP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateProgressCallback":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgressCallback","kind":"symbol","url":"\/documentation\/mapboxcommon\/tileregionestimateprogresscallback","abstract":[],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileRegionEstimateProgressCallback","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"TileRegionEstimateProgressCallback","kind":"identifier"}],"title":"TileRegionEstimateProgressCallback","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"abstract":[],"kind":"article","type":"topic","role":"collectionGroup","title":"TileStore APIs","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","url":"\/documentation\/mapboxmaps\/tilestore-apis"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/CacheClearingError":{"abstract":[{"text":"Describes a cache clearing error.","type":"text"}],"title":"CacheClearingError","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CacheClearingError"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingError","role":"symbol","url":"\/documentation\/mapboxcommon\/cacheclearingerror","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CacheClearingError"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudget":{"title":"TileCacheBudget","type":"topic","url":"\/documentation\/mapboxmaps\/tilecachebudget","navigatorTitle":[{"text":"TileCacheBudget","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudget","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileCacheBudget","kind":"identifier"}],"abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStoreUsageMode/init(rawValue:)":{"abstract":[],"kind":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreUsageMode\/init(rawValue:)","url":"\/documentation\/mapboxmaps\/tilestoreusagemode\/init(rawvalue:)","role":"symbol","title":"init(rawValue:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileOptions":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileOptions","abstract":[{"type":"text","text":"Options for custom geometry tiles."}],"navigatorTitle":[{"text":"TileOptions","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileOptions","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","title":"TileOptions","url":"\/documentation\/mapboxmaps\/tileoptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateResult":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileRegionEstimateResult"}],"abstract":[{"type":"text","text":"The result of tile region estim"}],"url":"\/documentation\/mapboxcommon\/tileregionestimateresult","title":"TileRegionEstimateResult","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateResult","navigatorTitle":[{"kind":"identifier","text":"TileRegionEstimateResult"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileRegionError":{"url":"\/documentation\/mapboxmaps\/tileregionerror","abstract":[{"type":"text","text":"Describes the reason for a tile region download request failure."}],"navigatorTitle":[{"kind":"identifier","text":"TileRegionError"}],"type":"topic","title":"TileRegionError","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileRegionError","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileRegionError","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SY"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateOptions":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Holds options for the tile region estimation operation."}],"title":"TileRegionEstimateOptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileRegionEstimateOptions"}],"url":"\/documentation\/mapboxcommon\/tileregionestimateoptions","navigatorTitle":[{"kind":"identifier","text":"TileRegionEstimateOptions"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadOptions":{"title":"TileRegionLoadOptions","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions","navigatorTitle":[{"text":"TileRegionLoadOptions","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapboxcommon\/tileregionloadoptions","abstract":[{"text":"Describes the tile region load option values.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileRegionLoadOptions","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TilesetDescriptor":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TilesetDescriptor","abstract":[{"text":"A bundle that encapsulates tilesets creation for the tile store implementation.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"TilesetDescriptor"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TilesetDescriptor"}],"url":"\/documentation\/mapboxcommon\/tilesetdescriptor","type":"topic","title":"TilesetDescriptor"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","value":"MBMTileStoreUsageMode","path":"\/metadata\/title"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"MBMTileStoreUsageMode"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"MBMTileStoreUsageMode","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreUsageMode\/disabled","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreUsageMode\/readAndUpdate","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStoreUsageMode\/readOnly"]}],"path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"replace","value":[{"anchor":"TileStore","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStore","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileStoreOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudget","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInMegabytes","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetInTiles","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegion","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgress","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TilesetDescriptor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TilesetDescriptorOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgressCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileDataDomain","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgress","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateResult","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateProgressCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/CacheClearingErrorType"],"title":"TileStore"}],"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBMTileStoreUsageMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"MBXCacheClearingErrorType","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingErrorType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBXCacheClearingErrorType"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingErrorType\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MBXCacheClearingErrorType"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingErrorType\/navigatorTitle"},{"op":"replace","value":"MBMTileCacheBudgetInMegabytes","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInMegabytes\/title"},{"op":"replace","value":[{"text":"MBMTileCacheBudgetInMegabytes","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInMegabytes\/fragments"},{"op":"replace","value":[{"text":"MBMTileCacheBudgetInMegabytes","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInMegabytes\/navigatorTitle"},{"op":"replace","value":"MBMTileStoreUsageModeDisabled","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileStoreUsageMode~1disabled\/title"},{"op":"replace","value":[{"text":"MBMTileStoreUsageModeDisabled","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileStoreUsageMode~1disabled\/fragments"},{"op":"replace","value":"MBXTileStore","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBXTileStore"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/fragments"},{"op":"replace","value":[{"text":"MBXTileStore","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStore\/navigatorTitle"},{"op":"replace","value":"MBMTileCacheBudgetType","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBMTileCacheBudgetType"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetType\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MBMTileCacheBudgetType"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetType\/navigatorTitle"},{"op":"replace","value":"MBXTileRegionLoadProgress","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgress\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBXTileRegionLoadProgress"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgress\/fragments"},{"op":"replace","value":[{"text":"MBXTileRegionLoadProgress","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgress\/navigatorTitle"},{"op":"replace","value":"MBMTileCacheBudgetInTiles","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInTiles\/title"},{"op":"replace","value":[{"text":"MBMTileCacheBudgetInTiles","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInTiles\/fragments"},{"op":"replace","value":[{"text":"MBMTileCacheBudgetInTiles","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudgetInTiles\/navigatorTitle"},{"op":"replace","value":"MBXTileDataDomain","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileDataDomain\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBXTileDataDomain"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileDataDomain\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MBXTileDataDomain"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileDataDomain\/navigatorTitle"},{"op":"replace","value":"MBMCanonicalTileID","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBMCanonicalTileID"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/navigatorTitle","value":[{"text":"MBMCanonicalTileID","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgressCallback\/title","value":"MBXTileRegionLoadProgressCallback"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgressCallback\/fragments","value":[{"text":"MBXTileRegionLoadProgressCallback","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgressCallback\/navigatorTitle","value":[{"text":"MBXTileRegionLoadProgressCallback","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegion\/title","value":"MBXTileRegion"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegion\/fragments","value":[{"text":"MBXTileRegion","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegion\/navigatorTitle","value":[{"text":"MBXTileRegion","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileStoreUsageMode~1readOnly\/title","value":"MBMTileStoreUsageModeReadOnly"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileStoreUsageMode~1readOnly\/fragments","value":[{"kind":"identifier","text":"MBMTileStoreUsageModeReadOnly"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStoreOptions\/title","value":"MBXTileStoreOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStoreOptions\/fragments","value":[{"text":"MBXTileStoreOptions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileStoreOptions\/navigatorTitle","value":[{"kind":"identifier","text":"MBXTileStoreOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgress\/title","value":"MBXTileRegionEstimateProgress"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgress\/fragments","value":[{"text":"MBXTileRegionEstimateProgress","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgress\/navigatorTitle","value":[{"text":"MBXTileRegionEstimateProgress","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileStoreUsageMode~1readAndUpdate\/title","value":"MBMTileStoreUsageModeReadAndUpdate"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileStoreUsageMode~1readAndUpdate\/fragments","value":[{"text":"MBMTileStoreUsageModeReadAndUpdate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions\/title","value":"MBMTilesetDescriptorOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions\/fragments","value":[{"text":"MBMTilesetDescriptorOptions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions\/navigatorTitle","value":[{"text":"MBMTilesetDescriptorOptions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileStoreUsageMode\/title","value":"MBMTileStoreUsageMode"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileStoreUsageMode\/fragments","value":[{"kind":"identifier","text":"MBMTileStoreUsageMode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileStoreUsageMode\/navigatorTitle","value":[{"text":"MBMTileStoreUsageMode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgressCallback\/title","value":"MBXTileRegionEstimateProgressCallback"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgressCallback\/fragments","value":[{"text":"MBXTileRegionEstimateProgressCallback","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateProgressCallback\/navigatorTitle","value":[{"kind":"identifier","text":"MBXTileRegionEstimateProgressCallback"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingError\/title","value":"MBXCacheClearingError"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingError\/fragments","value":[{"kind":"identifier","text":"MBXCacheClearingError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1CacheClearingError\/navigatorTitle","value":[{"text":"MBXCacheClearingError","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudget\/title","value":"MBMTileCacheBudget"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudget\/fragments","value":[{"text":"MBMTileCacheBudget","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudget\/navigatorTitle","value":[{"text":"MBMTileCacheBudget","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileOptions\/title","value":"MBMTileOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileOptions\/fragments","value":[{"kind":"identifier","text":"MBMTileOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileOptions\/navigatorTitle","value":[{"kind":"identifier","text":"MBMTileOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateResult\/title","value":"MBXTileRegionEstimateResult"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateResult\/fragments","value":[{"kind":"identifier","text":"MBXTileRegionEstimateResult"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateResult\/navigatorTitle","value":[{"kind":"identifier","text":"MBXTileRegionEstimateResult"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateOptions\/title","value":"MBXTileRegionEstimateOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateOptions\/fragments","value":[{"text":"MBXTileRegionEstimateOptions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateOptions\/navigatorTitle","value":[{"text":"MBXTileRegionEstimateOptions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/title","value":"MBXTileRegionLoadOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/fragments","value":[{"text":"MBXTileRegionLoadOptions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/navigatorTitle","value":[{"text":"MBXTileRegionLoadOptions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TilesetDescriptor\/title","value":"MBXTilesetDescriptor"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TilesetDescriptor\/fragments","value":[{"kind":"identifier","text":"MBXTilesetDescriptor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TilesetDescriptor\/navigatorTitle","value":[{"kind":"identifier","text":"MBXTilesetDescriptor"}]}]}]}