{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderConfiguration\/isRenderToTileSupported"},"sections":[],"abstract":[{"type":"text","text":"If this value is true and there’s need for draping (globe or terrain are enabled), then renderToTile will be called to enable"},{"type":"text","text":" "},{"type":"text","text":"the rendering of the custom layer into the texture of a tile."},{"type":"text","text":" "},{"type":"text","text":"If this value is set, and terrain or globe are active, only render to tile render call for this layer is called,"},{"type":"text","text":" "},{"type":"text","text":"and “immediate mode” render is not called. A custom layer is, at one frame, either rendered to tile or rendered"},{"type":"text","text":" "},{"type":"text","text":"directly."}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderConfiguration"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isRenderToTileSupported","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/mapboxmaps\/customlayerrenderconfiguration\/isrendertotilesupported"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/customlayerrenderconfiguration\/isrendertotilesupported"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isRenderToTileSupported"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"symbolKind":"property","roleHeading":"Instance Property","externalID":"c:objc(cs)MBMCustomLayerRenderConfiguration(py)isRenderToTileSupported","modules":[{"name":"MapboxMaps"}],"title":"isRenderToTileSupported","navigatorTitle":[{"text":"isRenderToTileSupported","kind":"identifier"}],"role":"symbol"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerRenderConfiguration/isRenderToTileSupported":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isRenderToTileSupported"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"isRenderToTileSupported","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderConfiguration\/isRenderToTileSupported","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isRenderToTileSupported"}],"url":"\/documentation\/mapboxmaps\/customlayerrenderconfiguration\/isrendertotilesupported","abstract":[{"type":"text","text":"If this value is true and there’s need for draping (globe or terrain are enabled), then renderToTile will be called to enable"},{"type":"text","text":" "},{"type":"text","text":"the rendering of the custom layer into the texture of a tile."},{"type":"text","text":" "},{"type":"text","text":"If this value is set, and terrain or globe are active, only render to tile render call for this layer is called,"},{"type":"text","text":" "},{"type":"text","text":"and “immediate mode” render is not called. A custom layer is, at one frame, either rendered to tile or rendered"},{"type":"text","text":" "},{"type":"text","text":"directly."}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerRenderConfiguration":{"abstract":[{"type":"text","text":"Note! This is an experimental feature. It can be changed or removed in future versions."}],"title":"CustomLayerRenderConfiguration","navigatorTitle":[{"kind":"identifier","text":"CustomLayerRenderConfiguration"}],"url":"\/documentation\/mapboxmaps\/customlayerrenderconfiguration","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerRenderConfiguration","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomLayerRenderConfiguration"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layers":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers","kind":"article","url":"\/documentation\/mapboxmaps\/layers","role":"collectionGroup","type":"topic","abstract":[],"title":"Layers"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","kind":"article","title":"MapboxMaps Documentation","url":"\/documentation\/overview","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"role":"collection","kind":"symbol","url":"\/documentation\/mapboxmaps","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"isRenderToTileSupported","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"isRenderToTileSupported"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"isRenderToTileSupported","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"isRenderToTileSupported","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderConfiguration~1isRenderToTileSupported\/title"},{"value":[{"kind":"identifier","text":"isRenderToTileSupported"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderConfiguration~1isRenderToTileSupported\/fragments"},{"value":"MBMCustomLayerRenderConfiguration","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderConfiguration\/title"},{"value":[{"kind":"identifier","text":"MBMCustomLayerRenderConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderConfiguration\/fragments"},{"value":[{"text":"MBMCustomLayerRenderConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerRenderConfiguration\/navigatorTitle"}]}]}