{"kind":"symbol","identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer\/initialize(forDevice:colorPixelFormat:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/mapboxmaps\/customrastersourcetilerenderer\/initialize(fordevice:colorpixelformat:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/customrastersourcetilerenderer\/initialize(fordevice:colorpixelformat:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"initialize","kind":"identifier"},{"kind":"text","text":"("},{"text":"forDevice","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"device"},{"kind":"text","text":": "},{"text":"UInt64","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V"},{"text":", ","kind":"text"},{"text":"colorPixelFormat","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt64","preciseIdentifier":"s:s6UInt64V"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"device","content":[{"inlineContent":[{"text":"The pointer to MTLDevice.","type":"text"}],"type":"paragraph"}]},{"name":"colorPixelFormat","content":[{"type":"paragraph","inlineContent":[{"text":"The current color pixel format","type":"text"}]}]}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"syntax":null,"type":"codeListing","code":["metalDevice = (__bridge id<MTLDevice>)(void*)device;"]}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer"]]},"sections":[],"abstract":[{"type":"text","text":"Initialize any Metal state needed by the tile renderer. This method is called once,"},{"text":" ","type":"text"},{"type":"text","text":"before rendering for the first time."},{"text":" ","type":"text"},{"type":"text","text":"The client should obtain the "},{"type":"codeVoice","code":"MTLDevice"},{"type":"text","text":" instance from the "},{"code":"device","type":"codeVoice"},{"type":"text","text":" argument, using the"},{"type":"text","text":" "},{"text":"following code:","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"title":"initialize(forDevice:colorPixelFormat:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"initialize","kind":"identifier"},{"kind":"text","text":"("},{"text":"forDevice","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt64","preciseIdentifier":"s:s6UInt64V","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"colorPixelFormat","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V","text":"UInt64"},{"kind":"text","text":")"}],"role":"symbol","symbolKind":"method","required":true,"roleHeading":"Instance Method","externalID":"c:objc(pl)MBMCustomRasterSourceTileRenderer(im)initializeForDevice:colorPixelFormat:","navigatorTitle":[{"kind":"identifier","text":"initializeForDevice:colorPixelFormat:"}],"modules":[{"name":"MapboxMaps"}]},"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","url":"\/documentation\/overview","title":"MapboxMaps Documentation","type":"topic","role":"collection","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","type":"topic","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"title":"MapboxMaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileRenderer":{"title":"CustomRasterSourceTileRenderer","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer","navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceTileRenderer"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomRasterSourceTileRenderer","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/customrastersourcetilerenderer","abstract":[{"text":"Interface for the direct rendering into the custom raster tiles.","type":"text"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileRenderer/initialize(forDevice:colorPixelFormat:)":{"navigatorTitle":[{"text":"initializeForDevice:colorPixelFormat:","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/customrastersourcetilerenderer\/initialize(fordevice:colorpixelformat:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"initialize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forDevice","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s6UInt64V","kind":"typeIdentifier","text":"UInt64"},{"kind":"text","text":", "},{"text":"colorPixelFormat","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt64","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V"},{"kind":"text","text":")"}],"type":"topic","kind":"symbol","title":"initialize(forDevice:colorPixelFormat:)","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer\/initialize(forDevice:colorPixelFormat:)","abstract":[{"type":"text","text":"Initialize any Metal state needed by the tile renderer. This method is called once,"},{"text":" ","type":"text"},{"type":"text","text":"before rendering for the first time."},{"type":"text","text":" "},{"text":"The client should obtain the ","type":"text"},{"type":"codeVoice","code":"MTLDevice"},{"text":" instance from the ","type":"text"},{"type":"codeVoice","code":"device"},{"text":" argument, using the","type":"text"},{"type":"text","text":" "},{"text":"following code:","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Sources":{"type":"topic","role":"collectionGroup","abstract":[],"url":"\/documentation\/mapboxmaps\/sources","title":"Sources","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"initializeForDevice:colorPixelFormat:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"initializeForDevice:colorPixelFormat:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"initializeForDevice:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@uint64_t","kind":"typeIdentifier","text":"uint64_t"},{"kind":"text","text":") "},{"text":"device","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"colorPixelFormat:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@uint64_t","text":"uint64_t","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"colorPixelFormat","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"device","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The pointer to MTLDevice."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"The current color pixel format"}],"type":"paragraph"}],"name":"colorPixelFormat"}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer\/title","value":"MBMCustomRasterSourceTileRenderer","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer\/fragments","value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileRenderer"}]},{"op":"replace","value":[{"text":"MBMCustomRasterSourceTileRenderer","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer~1initialize(forDevice:colorPixelFormat:)\/title","value":"initializeForDevice:colorPixelFormat:","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer~1initialize(forDevice:colorPixelFormat:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"initializeForDevice:colorPixelFormat:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}