{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"graphicsPrograms"}],"modules":[{"name":"MapboxMaps"}],"title":"graphicsPrograms","symbolKind":"property","fragments":[{"text":"graphicsPrograms","kind":"identifier"}],"roleHeading":"Instance Property","role":"symbol","externalID":"c:objc(cs)MBMCumulativeRenderingStatistics(py)graphicsPrograms"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CumulativeRenderingStatistics"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCumulativeRenderingStatistics\/graphicsPrograms","interfaceLanguage":"occ"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"The number of graphics pipeline programs created."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"graphicsPrograms"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/mbmcumulativerenderingstatistics\/graphicsprograms"]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","url":"\/documentation\/overview","abstract":[],"role":"collection","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CumulativeRenderingStatistics":{"abstract":[],"title":"CumulativeRenderingStatistics","url":"\/documentation\/mapboxmaps\/cumulativerenderingstatistics","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CumulativeRenderingStatistics","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CumulativeRenderingStatistics"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CumulativeRenderingStatistics","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMCumulativeRenderingStatistics/graphicsPrograms":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCumulativeRenderingStatistics\/graphicsPrograms","kind":"symbol","url":"\/documentation\/mapboxmaps\/mbmcumulativerenderingstatistics\/graphicsprograms","role":"symbol","fragments":[{"kind":"identifier","text":"graphicsPrograms"}],"title":"graphicsPrograms","abstract":[{"type":"text","text":"The number of graphics pipeline programs created."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Performance":{"abstract":[],"title":"Performance and investigations","url":"\/documentation\/mapboxmaps\/performance","role":"collectionGroup","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","type":"topic","role":"collection","title":"MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CumulativeRenderingStatistics\/title","op":"replace","value":"MBMCumulativeRenderingStatistics"},{"op":"replace","value":[{"kind":"identifier","text":"MBMCumulativeRenderingStatistics"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CumulativeRenderingStatistics\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CumulativeRenderingStatistics\/navigatorTitle","value":[{"kind":"identifier","text":"MBMCumulativeRenderingStatistics"}]}]}]}