{"variants":[{"paths":["\/documentation\/mapboxcommon\/locationprovider\/getlastobservedlocation()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/locationprovider\/getlastobservedlocation()"]}],"abstract":[{"type":"text","text":"Gets the last observed location."}],"metadata":{"role":"symbol","title":"getLastObservedLocation()","modules":[{"name":"MapboxCommon"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getLastObservedLocation","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"Location","preciseIdentifier":"c:objc(cs)MBXLocation","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"getLastObservedLocation","kind":"identifier"}],"roleHeading":"Instance Method","required":true,"externalID":"c:objc(pl)MBXLocationProvider(im)getLastObservedLocation","symbolKind":"method"},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider\/getLastObservedLocation()","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getLastObservedLocation","kind":"identifier"},{"kind":"text","text":"() -> "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location","text":"Location","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXLocation"},{"kind":"text","text":"?"}]}],"kind":"declarations"},{"content":[{"level":2,"type":"heading","anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A single location or null if no location has been observed."}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider"]]},"kind":"symbol","sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","abstract":[],"kind":"article","role":"collection","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationProvider":{"navigatorTitle":[{"text":"LocationProvider","kind":"identifier"}],"title":"LocationProvider","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"LocationProvider","kind":"identifier"}],"abstract":[{"type":"text","text":"Location provider that provides locations"}],"kind":"symbol","type":"topic","url":"\/documentation\/mapboxcommon\/locationprovider"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Location":{"abstract":[{"type":"text","text":"Location information."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Location"}],"url":"\/documentation\/mapboxcommon\/location","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Location","kind":"identifier"}],"kind":"symbol","type":"topic","title":"Location","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationProvider/getLastObservedLocation()":{"role":"symbol","url":"\/documentation\/mapboxcommon\/locationprovider\/getlastobservedlocation()","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationProvider\/getLastObservedLocation()","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Gets the last observed location."}],"title":"getLastObservedLocation()","required":true,"navigatorTitle":[{"kind":"identifier","text":"getLastObservedLocation"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getLastObservedLocation","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBXLocation","text":"Location","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Location-APIs":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","url":"\/documentation\/mapboxmaps\/location-apis","type":"topic","kind":"article","role":"collectionGroup","abstract":[],"title":"Location"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"getLastObservedLocation"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getLastObservedLocation"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:objc(cs)MBXLocation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location","kind":"typeIdentifier","text":"MBXLocation"},{"text":" *) ","kind":"text"},{"text":"getLastObservedLocation","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/primaryContentSections\/1","value":{"kind":"content","content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"A single location or null if no location has been observed.","type":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/title","op":"replace","value":"MBXLocationProvider"},{"value":[{"text":"MBXLocationProvider","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider\/navigatorTitle","value":[{"text":"MBXLocationProvider","kind":"identifier"}],"op":"replace"},{"value":"MBXLocation","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/fragments","value":[{"text":"MBXLocation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/navigatorTitle","value":[{"text":"MBXLocation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider~1getLastObservedLocation()\/title","value":"getLastObservedLocation"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationProvider~1getLastObservedLocation()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getLastObservedLocation"}]}]}]}