{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NetworkRestriction"]]},"metadata":{"modules":[{"name":"MapboxCommon"}],"symbolKind":"case","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"none"}],"navigatorTitle":[{"text":"MBXNetworkRestrictionNone","kind":"identifier"}],"externalID":"c:@E@MBXNetworkRestriction@MBXNetworkRestrictionNone","title":"NetworkRestriction.none","role":"symbol"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Allow access to all network types.","type":"text"}],"variants":[{"paths":["\/documentation\/mapboxcommon\/networkrestriction\/none"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxcommon\/networkrestriction\/none"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NetworkRestriction\/none","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/NetworkRestriction/none":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NetworkRestriction\/none","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"abstract":[{"type":"text","text":"Allow access to all network types."}],"url":"\/documentation\/mapboxcommon\/networkrestriction\/none","kind":"symbol","navigatorTitle":[{"text":"MBXNetworkRestrictionNone","kind":"identifier"}],"title":"NetworkRestriction.none","type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/NetworkRestriction":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NetworkRestriction","title":"NetworkRestriction","url":"\/documentation\/mapboxcommon\/networkrestriction","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NetworkRestriction"}],"abstract":[{"text":"Classify network types based on cost.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"NetworkRestriction","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","abstract":[],"kind":"article","role":"collection","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","kind":"symbol","type":"topic","title":"MapboxCommon","url":"\/documentation\/mapboxcommon","role":"collection","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"MBXNetworkRestrictionNone"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","value":[{"text":"MBXNetworkRestrictionNone","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"MBXNetworkRestrictionNone","kind":"identifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1NetworkRestriction~1none\/title","value":"MBXNetworkRestrictionNone"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1NetworkRestriction~1none\/fragments","value":[{"kind":"identifier","text":"MBXNetworkRestrictionNone"}]},{"op":"replace","value":"MBXNetworkRestriction","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1NetworkRestriction\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1NetworkRestriction\/fragments","value":[{"kind":"identifier","text":"MBXNetworkRestriction"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1NetworkRestriction\/navigatorTitle","value":[{"text":"MBXNetworkRestriction","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}