{"kind":"symbol","seeAlsoSections":[{"generated":true,"title":"Map events","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onMapLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onMapLoadingError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleDataLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onCameraChanged","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onMapIdle","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onSourceAdded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onSourceRemoved","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onSourceDataLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleImageMissing","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleImageRemoveUnused","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onRenderFrameStarted","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onResourceRequest"],"anchor":"Map-events"}],"sections":[],"metadata":{"roleHeading":"Instance Property","title":"onRenderFrameFinished","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onRenderFrameFinished","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10MapboxMaps6SignalV","text":"Signal","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"RenderFrameFinished","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMRenderFrameFinished"},{"text":">","kind":"text"}],"symbolKind":"property","externalID":"s:10MapboxMaps0A3MapC21onRenderFrameFinishedAA6SignalVySo09MBMRenderfG0CGvp","role":"symbol","extendedModule":"MapboxMaps","modules":[{"name":"MapboxMaps"}]},"abstract":[{"type":"text","text":"The map finished rendering a frame."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"renderMode"},{"text":" property tells whether the map has all data (","type":"text"},{"type":"codeVoice","code":"full"},{"text":") required to render the visible viewport.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The "},{"code":"needsRepaint","type":"codeVoice"},{"text":" property provides information about ongoing transitions that trigger map repaint.","type":"text"},{"type":"text","text":" "},{"text":"The ","type":"text"},{"type":"codeVoice","code":"placementChanged"},{"text":" property tells if the symbol placement has been changed in the visible viewport.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onRenderFrameFinished"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Signal","text":"Signal","preciseIdentifier":"s:10MapboxMaps6SignalV","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"RenderFrameFinished","preciseIdentifier":"c:objc(cs)MBMRenderFrameFinished","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinished"},{"kind":"text","text":"> { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/mapboxmaps\/mapboxmap\/onrenderframefinished"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap"],["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/MapboxMapProtocol-Implementations"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onRenderFrameFinished"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/MapboxMapProtocol-Implementations":{"abstract":[],"role":"collectionGroup","type":"topic","kind":"article","url":"\/documentation\/mapboxmaps\/mapboxmap\/mapboxmapprotocol-implementations","title":"MapboxMapProtocol Implementations","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/MapboxMapProtocol-Implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onSourceAdded":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/onsourceadded","type":"topic","title":"onSourceAdded","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onSourceAdded","abstract":[{"text":"The source has been added with ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addSource(_:dataId:)","isActive":true},{"text":"  or ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addSource(withId:properties:)","type":"reference","isActive":true},{"type":"text","text":"."},{"text":" ","type":"text"},{"text":"The event is emitted synchronously, therefore, it is possible to immediately","type":"text"},{"type":"text","text":" "},{"text":"read added source’s properties.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onSourceAdded"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV","text":"Signal"},{"text":"<","kind":"text"},{"text":"SourceAdded","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMSourceAdded"},{"text":">","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Signal":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Signal","url":"\/documentation\/mapboxmaps\/signal","abstract":[{"type":"text","text":"Signal is a typed interface for observing arbitrary values over time."}],"title":"Signal","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"Signal","kind":"identifier"}],"navigatorTitle":[{"text":"Signal","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onMapLoaded":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/onmaploaded","type":"topic","title":"onMapLoaded","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onMapLoaded","abstract":[{"text":"The style has been fully loaded, and the map has rendered all visible tiles.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"onMapLoaded","kind":"identifier"},{"kind":"text","text":": "},{"text":"Signal","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"MapLoaded","preciseIdentifier":"c:objc(cs)MBMMapLoaded"},{"text":">","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/beginGesture()":{"url":"\/documentation\/mapboxmaps\/mapboxmap\/begingesture()","role":"symbol","abstract":[{"text":"If implementing a custom gesture, call this method when the gesture begins.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/beginGesture()","kind":"symbol","title":"beginGesture()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"beginGesture"},{"text":"()","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/beginAnimation()":{"abstract":[{"text":"If implementing a custom animation mechanism, call this method when the animation begins.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/beginAnimation()","title":"beginAnimation()","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"beginAnimation"},{"text":"()","kind":"text"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/beginanimation()"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onRenderFrameFinished":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"onRenderFrameFinished","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps6SignalV","kind":"typeIdentifier","text":"Signal"},{"text":"<","kind":"text"},{"text":"RenderFrameFinished","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMRenderFrameFinished"},{"text":">","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onRenderFrameFinished","url":"\/documentation\/mapboxmaps\/mapboxmap\/onrenderframefinished","kind":"symbol","title":"onRenderFrameFinished","abstract":[{"text":"The map finished rendering a frame.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The "},{"code":"renderMode","type":"codeVoice"},{"text":" property tells whether the map has all data (","type":"text"},{"code":"full","type":"codeVoice"},{"type":"text","text":") required to render the visible viewport."},{"type":"text","text":" "},{"text":"The ","type":"text"},{"type":"codeVoice","code":"needsRepaint"},{"text":" property provides information about ongoing transitions that trigger map repaint.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"placementChanged"},{"text":" property tells if the symbol placement has been changed in the visible viewport.","type":"text"}],"type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/endGesture()":{"type":"topic","url":"\/documentation\/mapboxmaps\/mapboxmap\/endgesture()","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/endGesture()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"endGesture"},{"text":"()","kind":"text"}],"title":"endGesture()","abstract":[{"type":"text","text":"If implementing a custom gesture, call this method when the gesture ends."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onMapIdle":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/onmapidle","type":"topic","title":"onMapIdle","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onMapIdle","abstract":[{"type":"text","text":"The map has entered the idle state. The map is in the idle state when there are no ongoing transitions"},{"type":"text","text":" "},{"text":"and the map has rendered all requested non-volatile tiles. The event will not be emitted if animation is in progress (see ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/beginAnimation()"},{"text":", ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/endAnimation()","type":"reference"},{"text":")","type":"text"},{"type":"text","text":" "},{"type":"text","text":"and \/ or gesture is in progress (see "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/beginGesture()","isActive":true,"type":"reference"},{"text":", ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/endGesture()","isActive":true},{"text":").","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"onMapIdle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps6SignalV","kind":"typeIdentifier","text":"Signal"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"MapIdle","preciseIdentifier":"c:objc(cs)MBMMapIdle"},{"text":">","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/loadStyle(_:transition:completion:)-1ilz1":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"loadStyle","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:10MapboxMaps8StyleURIV","text":"StyleURI","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"transition"},{"kind":"text","text":": "},{"text":"TransitionOptions","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps17TransitionOptionsV"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (((any "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":")?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/loadStyle(_:transition:completion:)-1ilz1","url":"\/documentation\/mapboxmaps\/mapboxmap\/loadstyle(_:transition:completion:)-1ilz1","kind":"symbol","title":"loadStyle(_:transition:completion:)","abstract":[{"text":"Loads a ","type":"text"},{"code":"style","type":"codeVoice"},{"text":" from a StyleURI, calling a completion closure when the","type":"text"},{"type":"text","text":" "},{"type":"text","text":"style is fully loaded or there has been an error during load."}],"type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/allSourceIdentifiers":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"allSourceIdentifiers"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps10SourceInfoV","text":"SourceInfo","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/allSourceIdentifiers","url":"\/documentation\/mapboxmaps\/stylemanager\/allsourceidentifiers","kind":"symbol","title":"allSourceIdentifiers","abstract":[{"text":"The ordered list of the current style sources’ identifiers and types.","type":"text"}],"type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/addSource(withId:properties:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"addSource","kind":"identifier"},{"kind":"text","text":"("},{"text":"withId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"properties","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]) ","kind":"text"},{"kind":"keyword","text":"throws"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addSource(withId:properties:)","url":"\/documentation\/mapboxmaps\/stylemanager\/addsource(withid:properties:)","kind":"symbol","title":"addSource(withId:properties:)","abstract":[{"type":"text","text":"Adds a new style source."}],"type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RenderFrameFinished":{"title":"RenderFrameFinished","abstract":[{"type":"text","text":"The "},{"code":"map","type":"codeVoice"},{"type":"text","text":" finished rendering a frame."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RenderFrameFinished","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"RenderFrameFinished","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"RenderFrameFinished","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/renderframefinished","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onStyleDataLoaded":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/onstyledataloaded","type":"topic","title":"onStyleDataLoaded","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleDataLoaded","abstract":[{"type":"text","text":"The requested style data has been loaded. The "},{"code":"type","type":"codeVoice"},{"type":"text","text":" property defines what kind of style data has been loaded."},{"type":"text","text":" "},{"text":"Event may be emitted synchronously, for example, when ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/loadStyle(_:transition:completion:)-1ilz1","type":"reference","isActive":true},{"type":"text","text":" is used to load style."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"onStyleDataLoaded","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Signal","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMStyleDataLoaded","text":"StyleDataLoaded"},{"text":">","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onSourceRemoved":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"onSourceRemoved","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Signal","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"kind":"text","text":"<"},{"text":"SourceRemoved","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMSourceRemoved"},{"text":">","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onSourceRemoved","url":"\/documentation\/mapboxmaps\/mapboxmap\/onsourceremoved","kind":"symbol","title":"onSourceRemoved","abstract":[{"type":"text","text":"The source has been removed with "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/removeSource(withId:)"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The event is emitted synchronously, thus, "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/allSourceIdentifiers","type":"reference","isActive":true},{"text":" will be","type":"text"},{"type":"text","text":" "},{"text":"in sync when the observer receives the notification.","type":"text"}],"type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/removeSource(withId:)":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/stylemanager\/removesource(withid:)","type":"topic","title":"removeSource(withId:)","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/removeSource(withId:)","abstract":[{"text":"Removes an existing style source.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"removeSource"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/addSource(_:dataId:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addSource"},{"text":"(any ","kind":"text"},{"text":"Source","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SourceP"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dataId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?) ","kind":"text"},{"kind":"keyword","text":"throws"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addSource(_:dataId:)","url":"\/documentation\/mapboxmaps\/stylemanager\/addsource(_:dataid:)","kind":"symbol","title":"addSource(_:dataId:)","abstract":[{"text":"Adds a ","type":"text"},{"code":"source","type":"codeVoice"},{"type":"text","text":" to the map"}],"type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onStyleImageMissing":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/onstyleimagemissing","type":"topic","title":"onStyleImageMissing","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleImageMissing","abstract":[{"type":"text","text":"A style has a missing image. This event is emitted when the map renders visible tiles and"},{"type":"text","text":" "},{"text":"one of the required images is missing in the sprite sheet. Subscriber has to provide the missing image","type":"text"},{"text":" ","type":"text"},{"text":"by calling ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addImage(_:id:sdf:contentInsets:)","isActive":true,"type":"reference"},{"type":"text","text":"."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onStyleImageMissing"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps6SignalV","text":"Signal","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"text":"StyleImageMissing","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMStyleImageMissing"},{"text":">","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onMapLoadingError":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"onMapLoadingError","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps6SignalV","text":"Signal","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)MBMMapLoadingError","text":"MapLoadingError","kind":"typeIdentifier"},{"text":">","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onMapLoadingError","url":"\/documentation\/mapboxmaps\/mapboxmap\/onmaploadingerror","kind":"symbol","title":"onMapLoadingError","abstract":[{"text":"An error that has occurred while loading the Map. The ","type":"text"},{"type":"codeVoice","code":"type"},{"text":" property defines what resource could","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"not be loaded and the "},{"type":"codeVoice","code":"message"},{"text":" property will contain a descriptive error message.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"In case of "},{"code":"source","type":"codeVoice"},{"text":" or ","type":"text"},{"code":"tile","type":"codeVoice"},{"type":"text","text":" loading errors, "},{"type":"codeVoice","code":"sourceID"},{"text":" or ","type":"text"},{"type":"codeVoice","code":"tileID"},{"text":" will contain the identifier of the source failing.","type":"text"}],"type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap","title":"MapboxMap","kind":"symbol","abstract":[{"type":"text","text":"Provides access to the map model, including the camera, style, observable map events,"},{"text":" ","type":"text"},{"text":"and querying rendered features.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapboxMap"}],"navigatorTitle":[{"text":"MapboxMap","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onStyleImageRemoveUnused":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/onstyleimageremoveunused","type":"topic","title":"onStyleImageRemoveUnused","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleImageRemoveUnused","abstract":[{"text":"An image added to the style is no longer needed and can be removed using ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/removeImage(withId:)","type":"reference","isActive":true},{"type":"text","text":"."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"onStyleImageRemoveUnused","kind":"identifier"},{"kind":"text","text":": "},{"text":"Signal","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMStyleImageRemoveUnused","text":"StyleImageRemoveUnused"},{"kind":"text","text":">"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onCameraChanged":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/oncamerachanged","type":"topic","title":"onCameraChanged","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onCameraChanged","abstract":[{"type":"text","text":"The camera has changed. This event is emitted whenever the visible viewport"},{"text":" ","type":"text"},{"text":"changes due to the MapView’s size changing or when the camera","type":"text"},{"type":"text","text":" "},{"text":"is modified by calling camera methods. The event is emitted synchronously,","type":"text"},{"text":" ","type":"text"},{"text":"so that an updated camera state can be fetched immediately.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"onCameraChanged","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV","text":"Signal"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMCameraChanged","text":"CameraChanged","kind":"typeIdentifier"},{"text":">","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/endAnimation()":{"abstract":[{"type":"text","text":"If implementing a custom animation mechanism, call this method when the animation ends."}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/endAnimation()","title":"endAnimation()","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"endAnimation"},{"text":"()","kind":"text"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/endanimation()"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"type":"topic","title":"MapboxMaps Documentation","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/addImage(_:id:sdf:contentInsets:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addImage"},{"text":"(","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"id"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"sdf"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"contentInsets"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@UIEdgeInsets","text":"UIEdgeInsets","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addImage(_:id:sdf:contentInsets:)","url":"\/documentation\/mapboxmaps\/stylemanager\/addimage(_:id:sdf:contentinsets:)","kind":"symbol","title":"addImage(_:id:sdf:contentInsets:)","abstract":[{"type":"text","text":"Adds an image to be used in the style."}],"type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onStyleLoaded":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"onStyleLoaded","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10MapboxMaps6SignalV","text":"Signal","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"text":"StyleLoaded","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMStyleLoaded"},{"text":">","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleLoaded","url":"\/documentation\/mapboxmaps\/mapboxmap\/onstyleloaded","kind":"symbol","title":"onStyleLoaded","abstract":[{"text":"The requested style has been fully loaded, including the style, specified sprite and sources’ metadata.","type":"text"}],"type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","url":"\/documentation\/mapboxmaps","type":"topic","kind":"symbol","title":"MapboxMaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"kind":"article","abstract":[],"url":"\/documentation\/mapboxmaps\/mapboxmap-apis","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","type":"topic","title":"MapboxMap"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/removeImage(withId:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"removeImage","kind":"identifier"},{"kind":"text","text":"("},{"text":"withId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/removeImage(withId:)","url":"\/documentation\/mapboxmaps\/stylemanager\/removeimage(withid:)","kind":"symbol","title":"removeImage(withId:)","abstract":[{"type":"text","text":"Removes an image from the style."}],"type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onSourceDataLoaded":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/onsourcedataloaded","type":"topic","title":"onSourceDataLoaded","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onSourceDataLoaded","abstract":[{"text":"A source data has been loaded.","type":"text"},{"type":"text","text":" "},{"text":"Event may be emitted synchronously in cases when source’s metadata is available when source is added to the style.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"onSourceDataLoaded","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Signal","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"text":"<","kind":"text"},{"text":"SourceDataLoaded","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMSourceDataLoaded"},{"kind":"text","text":">"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onRenderFrameStarted":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onRenderFrameStarted"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV","text":"Signal"},{"text":"<","kind":"text"},{"text":"RenderFrameStarted","preciseIdentifier":"c:objc(cs)MBMRenderFrameStarted","kind":"typeIdentifier"},{"text":">","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onRenderFrameStarted","url":"\/documentation\/mapboxmaps\/mapboxmap\/onrenderframestarted","kind":"symbol","title":"onRenderFrameStarted","abstract":[{"text":"The map started rendering a frame.","type":"text"}],"type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onResourceRequest":{"kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/onresourcerequest","type":"topic","title":"onResourceRequest","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onResourceRequest","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"ResourceRequest"},{"type":"text","text":" event allows client to observe resource requests made by a"},{"type":"text","text":" "},{"text":"map or snapshotter.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"onResourceRequest","kind":"identifier"},{"kind":"text","text":": "},{"text":"Signal","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"ResourceRequest","preciseIdentifier":"c:objc(cs)MBMResourceRequest"},{"text":">","kind":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinished\/title","op":"replace","value":"MBMRenderFrameFinished"},{"op":"replace","value":[{"kind":"identifier","text":"MBMRenderFrameFinished"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinished\/fragments"},{"value":[{"text":"MBMRenderFrameFinished","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1RenderFrameFinished\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}