{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setTileCacheBudget","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"tileCacheBudget","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MBMTileCacheBudget","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudget","text":"TileCacheBudget","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The MapboxCoreMaps tile cache budget hint to be used by the Map."}]}],"name":"tileCacheBudget"}]},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The budget can be given in tile units or in megabytes. A Map will do the best effort to keep memory"},{"text":" ","type":"text"},{"text":"allocations for a non essential resources within the budget.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"If tile cache budget in megabytes is set, the engine will try to use ETC1 texture compression"},{"type":"text","text":" "},{"text":"for raster layers, therefore, raster images with alpha channel will be rendered incorrectly.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"If null is set, the tile cache budget in tile units will be dynamically calculated based on"},{"text":" ","type":"text"},{"type":"text","text":"the current viewport size."}]}],"kind":"content"}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/setTileCacheBudget(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The MapboxCoreMaps tile cache budget hint to be used by the map."}],"kind":"symbol","deprecationSummary":[{"inlineContent":[{"type":"text","text":"Use .setTileCacheBudget(size: TileCacheBudgetSize?) instead."}],"type":"paragraph"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"symbolKind":"method","title":"setTileCacheBudget(_:)","role":"symbol","externalID":"s:10MapboxMaps0A3MapC18setTileCacheBudgetyySo07MBMTilefG0CSgF","platforms":[],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setTileCacheBudget"},{"text":"(","kind":"text"},{"text":"TileCacheBudget","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMTileCacheBudget"},{"text":"?)","kind":"text"}],"modules":[{"name":"MapboxMaps"}]},"variants":[{"paths":["\/documentation\/mapboxmaps\/mapboxmap\/settilecachebudget(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","url":"\/documentation\/mapboxmaps","type":"topic","kind":"symbol","title":"MapboxMaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/setTileCacheBudget(_:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/setTileCacheBudget(_:)","abstract":[{"type":"text","text":"The MapboxCoreMaps tile cache budget hint to be used by the map."}],"title":"setTileCacheBudget(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setTileCacheBudget"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMTileCacheBudget","text":"TileCacheBudget","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"deprecated":true,"url":"\/documentation\/mapboxmaps\/mapboxmap\/settilecachebudget(_:)","role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap","title":"MapboxMap","kind":"symbol","abstract":[{"type":"text","text":"Provides access to the map model, including the camera, style, observable map events,"},{"text":" ","type":"text"},{"text":"and querying rendered features.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapboxMap"}],"navigatorTitle":[{"text":"MapboxMap","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"kind":"article","abstract":[],"url":"\/documentation\/mapboxmaps\/mapboxmap-apis","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","type":"topic","title":"MapboxMap"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudget":{"kind":"symbol","role":"symbol","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudget","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileCacheBudget"}],"type":"topic","url":"\/documentation\/mapboxmaps\/tilecachebudget","navigatorTitle":[{"kind":"identifier","text":"TileCacheBudget"}],"title":"TileCacheBudget"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"type":"topic","title":"MapboxMaps Documentation","url":"\/documentation\/overview"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudget\/title","value":"MBMTileCacheBudget"},{"value":[{"text":"MBMTileCacheBudget","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudget\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileCacheBudget\/navigatorTitle","value":[{"kind":"identifier","text":"MBMTileCacheBudget"}]}]}]}