{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/puckrenderingdata\/init(location:heading:)"]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckRenderingData"]]},"kind":"symbol","metadata":{"modules":[{"name":"MapboxMaps"}],"externalID":"s:10MapboxMaps17PuckRenderingDataV8location7headingACSo11MBXLocationC_AA7HeadingVSgtcfc","symbolKind":"init","title":"init(location:heading:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"location","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXLocation","text":"Location"},{"kind":"text","text":", "},{"kind":"externalParam","text":"heading"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps7HeadingV","text":"Heading"},{"kind":"text","text":"?)"}],"roleHeading":"Initializer"},"abstract":[{"type":"text","text":"Creates a puck rendering data."}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckRenderingData\/init(location:heading:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"location","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBXLocation","text":"Location","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location"},{"text":", ","kind":"text"},{"text":"heading","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps7HeadingV","text":"Heading","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Heading"},{"text":"? = nil)","kind":"text"}]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","abstract":[],"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","type":"topic","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","role":"collection","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Location":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Location"}],"navigatorTitle":[{"kind":"identifier","text":"Location"}],"url":"\/documentation\/mapboxcommon\/location","abstract":[{"text":"Location information.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Location","title":"Location"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Location-APIs":{"abstract":[],"url":"\/documentation\/mapboxmaps\/location-apis","kind":"article","title":"Location","role":"collectionGroup","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PuckRenderingData/init(location:heading:)":{"abstract":[{"text":"Creates a puck rendering data.","type":"text"}],"type":"topic","title":"init(location:heading:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"location"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXLocation","text":"Location"},{"kind":"text","text":", "},{"kind":"externalParam","text":"heading"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps7HeadingV","text":"Heading"},{"kind":"text","text":"?)"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckRenderingData\/init(location:heading:)","url":"\/documentation\/mapboxmaps\/puckrenderingdata\/init(location:heading:)","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Heading":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Heading","title":"Heading","navigatorTitle":[{"text":"Heading","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Heading","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The azimuth (orientation) of the user’s device, relative to true or magnetic north."}],"type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/heading"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PuckRenderingData":{"abstract":[{"type":"text","text":"Represents the interpolated data ready to render the user location puck."}],"url":"\/documentation\/mapboxmaps\/puckrenderingdata","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PuckRenderingData","kind":"identifier"}],"navigatorTitle":[{"text":"PuckRenderingData","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PuckRenderingData","title":"PuckRenderingData","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/title","value":"MBXLocation"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/fragments","value":[{"text":"MBXLocation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Location\/navigatorTitle","value":[{"text":"MBXLocation","kind":"identifier"}]}]}]}