{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/coordinateBoundsZoom(for:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/mapboxmap\/coordinateboundszoom(for:)"]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap"]]},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"coordinateBoundsZoom","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps13CameraOptionsV","text":"CameraOptions","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMCoordinateBoundsZoom","text":"CoordinateBoundsZoom","kind":"typeIdentifier"}],"modules":[{"name":"MapboxMaps"}],"title":"coordinateBoundsZoom(for:)","symbolKind":"method","role":"symbol","externalID":"s:10MapboxMaps0A3MapC20coordinateBoundsZoom3forSo013MBMCoordinateeF0CAA13CameraOptionsV_tF","roleHeading":"Instance Method"},"abstract":[{"text":"Returns the coordinate bounds and zoom for a given ","type":"text"},{"code":"CameraOptions","type":"codeVoice"},{"type":"text","text":"."}],"sections":[],"kind":"symbol","seeAlsoSections":[{"anchor":"CameraOptions-to-CoordinateBounds","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/coordinateBounds(for:)-gs8h","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/coordinateBoundsUnwrapped(for:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/coordinateBoundsZoomUnwrapped(for:)"],"generated":true,"title":"CameraOptions to CoordinateBounds"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"coordinateBoundsZoom","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"text":"camera","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps13CameraOptionsV","text":"CameraOptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraOptions"},{"text":") -> ","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBoundsZoom","preciseIdentifier":"c:objc(cs)MBMCoordinateBoundsZoom","kind":"typeIdentifier","text":"CoordinateBoundsZoom"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"camera","content":[{"type":"paragraph","inlineContent":[{"text":"The camera for which the ","type":"text"},{"type":"codeVoice","code":"CoordinateBoundsZoom"},{"type":"text","text":" will be returned."}]}]}],"kind":"parameters"},{"content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"CoordinateBoundsZoom"},{"text":" for the given ","type":"text"},{"code":"CameraOptions","type":"codeVoice"}]}],"kind":"content"},{"content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"This API isn’t supported by Globe projection.","type":"text"}]}],"kind":"content"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/coordinateBounds(for:)-gs8h":{"abstract":[{"type":"text","text":"Returns the coordinate bounds corresponding to a given "},{"type":"codeVoice","code":"CameraOptions"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"coordinateBounds","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps13CameraOptionsV","text":"CameraOptions"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CoordinateBounds","preciseIdentifier":"c:objc(cs)MBMCoordinateBounds"}],"kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/coordinatebounds(for:)-gs8h","title":"coordinateBounds(for:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/coordinateBounds(for:)-gs8h","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/coordinateBoundsUnwrapped(for:)":{"abstract":[{"type":"text","text":"Returns the unwrapped coordinate bounds to a given "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraOptions","type":"reference","isActive":true},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"coordinateBoundsUnwrapped","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraOptions","preciseIdentifier":"s:10MapboxMaps13CameraOptionsV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CoordinateBounds","preciseIdentifier":"c:objc(cs)MBMCoordinateBounds"}],"kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/coordinateboundsunwrapped(for:)","title":"coordinateBoundsUnwrapped(for:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/coordinateBoundsUnwrapped(for:)","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CameraOptions":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CameraOptions","abstract":[],"kind":"symbol","title":"CameraOptions","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraOptions","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxmaps\/cameraoptions","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CameraOptions"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","kind":"article","abstract":[],"title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateBoundsZoom":{"type":"topic","abstract":[{"type":"text","text":"A coordinate bounds and zoom."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CoordinateBoundsZoom"}],"url":"\/documentation\/mapboxmaps\/coordinateboundszoom","title":"CoordinateBoundsZoom","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoordinateBoundsZoom"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBoundsZoom"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/coordinateBoundsZoom(for:)":{"url":"\/documentation\/mapboxmaps\/mapboxmap\/coordinateboundszoom(for:)","kind":"symbol","type":"topic","abstract":[{"text":"Returns the coordinate bounds and zoom for a given ","type":"text"},{"type":"codeVoice","code":"CameraOptions"},{"type":"text","text":"."}],"role":"symbol","title":"coordinateBoundsZoom(for:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/coordinateBoundsZoom(for:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"coordinateBoundsZoom","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10MapboxMaps13CameraOptionsV","text":"CameraOptions","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMCoordinateBoundsZoom","text":"CoordinateBoundsZoom"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/coordinateBoundsZoomUnwrapped(for:)":{"url":"\/documentation\/mapboxmaps\/mapboxmap\/coordinateboundszoomunwrapped(for:)","kind":"symbol","type":"topic","abstract":[{"text":"Returns the unwrapped coordinate bounds and zoom for a given ","type":"text"},{"type":"codeVoice","code":"CameraOptions"},{"type":"text","text":"."}],"role":"symbol","title":"coordinateBoundsZoomUnwrapped(for:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/coordinateBoundsZoomUnwrapped(for:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"coordinateBoundsZoomUnwrapped","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10MapboxMaps13CameraOptionsV","text":"CameraOptions","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMCoordinateBoundsZoom","text":"CoordinateBoundsZoom"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"kind":"article","type":"topic","abstract":[],"title":"MapboxMap","url":"\/documentation\/mapboxmaps\/mapboxmap-apis","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapboxMap","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap","title":"MapboxMap","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","type":"topic","abstract":[{"type":"text","text":"Provides access to the map model, including the camera, style, observable map events,"},{"text":" ","type":"text"},{"text":"and querying rendered features.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"MapboxMap","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","role":"collection","title":"MapboxMaps","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]}},"variantOverrides":[{"patch":[{"value":"MBMCoordinateBoundsZoom","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBoundsZoom\/title"},{"value":[{"text":"MBMCoordinateBoundsZoom","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBoundsZoom\/fragments"},{"value":[{"text":"MBMCoordinateBoundsZoom","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBoundsZoom\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}