{"sections":[],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/debugOptions","interfaceLanguage":"swift"},"metadata":{"platforms":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"debugOptions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMMapDebugOptions","text":"MapDebugOptions"},{"kind":"text","text":"]"}],"modules":[{"name":"MapboxMaps"}],"title":"debugOptions","externalID":"s:10MapboxMaps0A3MapC12debugOptionsSaySo011MBMMapDebugE0VGvp","roleHeading":"Instance Property","role":"symbol","symbolKind":"property"},"kind":"symbol","abstract":[{"text":"The array of ","type":"text"},{"code":"MapDebugOptions","type":"codeVoice"},{"type":"text","text":" for the native map. Setting this property to an empty array"},{"text":" ","type":"text"},{"text":"disables previously enabled ","type":"text"},{"type":"codeVoice","code":"MapDebugOptions"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The default value is an empty array."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use MapView.debugOptions instead.","type":"text"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/mapboxmap\/debugoptions"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"debugOptions","kind":"identifier"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions","preciseIdentifier":"c:@E@MBMMapDebugOptions","text":"MapDebugOptions","kind":"typeIdentifier"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/debugOptions":{"url":"\/documentation\/mapboxmaps\/mapboxmap\/debugoptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/debugOptions","title":"debugOptions","type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"debugOptions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMMapDebugOptions","text":"MapDebugOptions"},{"text":"]","kind":"text"}],"abstract":[{"type":"text","text":"The array of "},{"code":"MapDebugOptions","type":"codeVoice"},{"text":" for the native map. Setting this property to an empty array","type":"text"},{"type":"text","text":" "},{"text":"disables previously enabled ","type":"text"},{"code":"MapDebugOptions","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"text":"The default value is an empty array.","type":"text"}],"deprecated":true,"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","type":"topic","title":"MapboxMaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","role":"collection","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapDebugOptions":{"navigatorTitle":[{"kind":"identifier","text":"MapDebugOptions"}],"role":"symbol","type":"topic","title":"MapDebugOptions","url":"\/documentation\/mapboxmaps\/mapdebugoptions","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapDebugOptions","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MapDebugOptions","kind":"identifier"}],"abstract":[{"type":"text","text":"Options for enabling debugging features in a map."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap":{"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapboxMap"}],"title":"MapboxMap","abstract":[{"text":"Provides access to the map model, including the camera, style, observable map events,","type":"text"},{"type":"text","text":" "},{"text":"and querying rendered features.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","url":"\/documentation\/mapboxmaps\/mapboxmap","navigatorTitle":[{"text":"MapboxMap","kind":"identifier"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","type":"topic","title":"MapboxMaps Documentation","url":"\/documentation\/overview","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"kind":"article","title":"MapboxMap","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","url":"\/documentation\/mapboxmaps\/mapboxmap-apis","abstract":[],"role":"collectionGroup","type":"topic"}},"variantOverrides":[{"patch":[{"value":"MBMMapDebugOptions","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions\/fragments","value":[{"text":"MBMMapDebugOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapDebugOptions\/navigatorTitle","value":[{"kind":"identifier","text":"MBMMapDebugOptions"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}