{"variants":[{"paths":["\/documentation\/mapboxmaps\/mapboxmap\/onmapidle"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onMapIdle","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap"],["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/MapboxMapProtocol-Implementations"]]},"abstract":[{"text":"The map has entered the idle state. The map is in the idle state when there are no ongoing transitions","type":"text"},{"type":"text","text":" "},{"text":"and the map has rendered all requested non-volatile tiles. The event will not be emitted if animation is in progress (see ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/beginAnimation()","isActive":true},{"type":"text","text":", "},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/endAnimation()","isActive":true},{"text":")","type":"text"},{"type":"text","text":" "},{"text":"and \/ or gesture is in progress (see ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/beginGesture()","isActive":true},{"type":"text","text":", "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/endGesture()","type":"reference","isActive":true},{"type":"text","text":")."}],"metadata":{"symbolKind":"property","externalID":"s:10MapboxMaps0A3MapC02onC4IdleAA6SignalVySo06MBMMapE0CGvp","roleHeading":"Instance Property","extendedModule":"MapboxMaps","title":"onMapIdle","modules":[{"name":"MapboxMaps"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMapIdle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV","text":"Signal"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)MBMMapIdle","text":"MapIdle","kind":"typeIdentifier"},{"text":">","kind":"text"}]},"seeAlsoSections":[{"generated":true,"anchor":"Map-events","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onMapLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onMapLoadingError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleDataLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onCameraChanged","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onSourceAdded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onSourceRemoved","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onSourceDataLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleImageMissing","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleImageRemoveUnused","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onRenderFrameStarted","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onRenderFrameFinished","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onResourceRequest"],"title":"Map events"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMapIdle"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Signal","preciseIdentifier":"s:10MapboxMaps6SignalV","kind":"typeIdentifier","text":"Signal"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"MapIdle","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapIdle","preciseIdentifier":"c:objc(cs)MBMMapIdle"},{"text":"> { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Signal":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"Signal","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/signal","navigatorTitle":[{"text":"Signal","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Signal","abstract":[{"type":"text","text":"Signal is a typed interface for observing arbitrary values over time."}],"title":"Signal","kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/beginGesture()":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/beginGesture()","url":"\/documentation\/mapboxmaps\/mapboxmap\/begingesture()","title":"beginGesture()","abstract":[{"text":"If implementing a custom gesture, call this method when the gesture begins.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"beginGesture","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","type":"topic","kind":"article","abstract":[],"role":"collection","title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"type":"topic","url":"\/documentation\/mapboxmaps\/mapboxmap-apis","title":"MapboxMap","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","abstract":[],"role":"collectionGroup","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onMapLoadingError":{"url":"\/documentation\/mapboxmaps\/mapboxmap\/onmaploadingerror","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onMapLoadingError","abstract":[{"text":"An error that has occurred while loading the Map. The ","type":"text"},{"type":"codeVoice","code":"type"},{"type":"text","text":" property defines what resource could"},{"text":" ","type":"text"},{"type":"text","text":"not be loaded and the "},{"type":"codeVoice","code":"message"},{"type":"text","text":" property will contain a descriptive error message."},{"text":" ","type":"text"},{"type":"text","text":"In case of "},{"type":"codeVoice","code":"source"},{"text":" or ","type":"text"},{"code":"tile","type":"codeVoice"},{"type":"text","text":" loading errors, "},{"code":"sourceID","type":"codeVoice"},{"text":" or ","type":"text"},{"code":"tileID","type":"codeVoice"},{"type":"text","text":" will contain the identifier of the source failing."}],"kind":"symbol","title":"onMapLoadingError","role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"onMapLoadingError","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV","text":"Signal"},{"kind":"text","text":"<"},{"text":"MapLoadingError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMMapLoadingError"},{"text":">","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onStyleLoaded":{"url":"\/documentation\/mapboxmaps\/mapboxmap\/onstyleloaded","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleLoaded","abstract":[{"text":"The requested style has been fully loaded, including the style, specified sprite and sources’ metadata.","type":"text"}],"kind":"symbol","title":"onStyleLoaded","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"onStyleLoaded","kind":"identifier"},{"kind":"text","text":": "},{"text":"Signal","preciseIdentifier":"s:10MapboxMaps6SignalV","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"text":"StyleLoaded","preciseIdentifier":"c:objc(cs)MBMStyleLoaded","kind":"typeIdentifier"},{"text":">","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap":{"navigatorTitle":[{"text":"MapboxMap","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/mapboxmap","abstract":[{"text":"Provides access to the map model, including the camera, style, observable map events,","type":"text"},{"type":"text","text":" "},{"text":"and querying rendered features.","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","type":"topic","title":"MapboxMap","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapboxMap"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onRenderFrameFinished":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onRenderFrameFinished","url":"\/documentation\/mapboxmaps\/mapboxmap\/onrenderframefinished","title":"onRenderFrameFinished","abstract":[{"type":"text","text":"The map finished rendering a frame."},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"type":"codeVoice","code":"renderMode"},{"type":"text","text":" property tells whether the map has all data ("},{"type":"codeVoice","code":"full"},{"text":") required to render the visible viewport.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The "},{"code":"needsRepaint","type":"codeVoice"},{"text":" property provides information about ongoing transitions that trigger map repaint.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The "},{"code":"placementChanged","type":"codeVoice"},{"text":" property tells if the symbol placement has been changed in the visible viewport.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"onRenderFrameFinished","kind":"identifier"},{"kind":"text","text":": "},{"text":"Signal","preciseIdentifier":"s:10MapboxMaps6SignalV","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"text":"RenderFrameFinished","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMRenderFrameFinished"},{"text":">","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/endGesture()":{"url":"\/documentation\/mapboxmaps\/mapboxmap\/endgesture()","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/endGesture()","abstract":[{"type":"text","text":"If implementing a custom gesture, call this method when the gesture ends."}],"kind":"symbol","title":"endGesture()","role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"endGesture","kind":"identifier"},{"kind":"text","text":"()"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/removeImage(withId:)":{"url":"\/documentation\/mapboxmaps\/stylemanager\/removeimage(withid:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/removeImage(withId:)","abstract":[{"type":"text","text":"Removes an image from the style."}],"kind":"symbol","title":"removeImage(withId:)","role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"removeImage","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onStyleImageRemoveUnused":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleImageRemoveUnused","url":"\/documentation\/mapboxmaps\/mapboxmap\/onstyleimageremoveunused","title":"onStyleImageRemoveUnused","abstract":[{"type":"text","text":"An image added to the style is no longer needed and can be removed using "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/removeImage(withId:)"},{"text":".","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onStyleImageRemoveUnused"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps6SignalV","text":"Signal","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"StyleImageRemoveUnused","preciseIdentifier":"c:objc(cs)MBMStyleImageRemoveUnused"},{"text":">","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"kind":"symbol","role":"collection","title":"MapboxMaps","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/allSourceIdentifiers":{"url":"\/documentation\/mapboxmaps\/stylemanager\/allsourceidentifiers","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/allSourceIdentifiers","abstract":[{"type":"text","text":"The ordered list of the current style sources’ identifiers and types."}],"kind":"symbol","title":"allSourceIdentifiers","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"allSourceIdentifiers","kind":"identifier"},{"kind":"text","text":": ["},{"text":"SourceInfo","preciseIdentifier":"s:10MapboxMaps10SourceInfoV","kind":"typeIdentifier"},{"text":"]","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/beginAnimation()":{"url":"\/documentation\/mapboxmaps\/mapboxmap\/beginanimation()","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/beginAnimation()","abstract":[{"text":"If implementing a custom animation mechanism, call this method when the animation begins.","type":"text"}],"kind":"symbol","title":"beginAnimation()","role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"beginAnimation"},{"text":"()","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/addImage(_:id:sdf:contentInsets:)":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addImage(_:id:sdf:contentInsets:)","url":"\/documentation\/mapboxmaps\/stylemanager\/addimage(_:id:sdf:contentinsets:)","title":"addImage(_:id:sdf:contentInsets:)","abstract":[{"text":"Adds an image to be used in the style.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"addImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"id"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"sdf","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"contentInsets","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIEdgeInsets","preciseIdentifier":"c:@S@UIEdgeInsets","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onResourceRequest":{"url":"\/documentation\/mapboxmaps\/mapboxmap\/onresourcerequest","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onResourceRequest","abstract":[{"type":"text","text":"The "},{"code":"ResourceRequest","type":"codeVoice"},{"type":"text","text":" event allows client to observe resource requests made by a"},{"type":"text","text":" "},{"text":"map or snapshotter.","type":"text"}],"kind":"symbol","title":"onResourceRequest","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onResourceRequest"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV","text":"Signal"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)MBMResourceRequest","text":"ResourceRequest","kind":"typeIdentifier"},{"text":">","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onStyleDataLoaded":{"url":"\/documentation\/mapboxmaps\/mapboxmap\/onstyledataloaded","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleDataLoaded","abstract":[{"text":"The requested style data has been loaded. The ","type":"text"},{"type":"codeVoice","code":"type"},{"type":"text","text":" property defines what kind of style data has been loaded."},{"text":" ","type":"text"},{"type":"text","text":"Event may be emitted synchronously, for example, when "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/loadStyle(_:transition:completion:)-1ilz1"},{"type":"text","text":" is used to load style."}],"kind":"symbol","title":"onStyleDataLoaded","role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onStyleDataLoaded"},{"text":": ","kind":"text"},{"text":"Signal","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"text":"<","kind":"text"},{"text":"StyleDataLoaded","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMStyleDataLoaded"},{"kind":"text","text":">"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onRenderFrameStarted":{"url":"\/documentation\/mapboxmaps\/mapboxmap\/onrenderframestarted","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onRenderFrameStarted","abstract":[{"text":"The map started rendering a frame.","type":"text"}],"kind":"symbol","title":"onRenderFrameStarted","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"onRenderFrameStarted","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Signal","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMRenderFrameStarted","text":"RenderFrameStarted"},{"text":">","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/addSource(_:dataId:)":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addSource(_:dataId:)","url":"\/documentation\/mapboxmaps\/stylemanager\/addsource(_:dataid:)","title":"addSource(_:dataId:)","abstract":[{"text":"Adds a ","type":"text"},{"code":"source","type":"codeVoice"},{"type":"text","text":" to the map"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addSource"},{"text":"(any ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps6SourceP","kind":"typeIdentifier","text":"Source"},{"text":", ","kind":"text"},{"text":"dataId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?) "},{"text":"throws","kind":"keyword"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onStyleImageMissing":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleImageMissing","url":"\/documentation\/mapboxmaps\/mapboxmap\/onstyleimagemissing","title":"onStyleImageMissing","abstract":[{"text":"A style has a missing image. This event is emitted when the map renders visible tiles and","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"one of the required images is missing in the sprite sheet. Subscriber has to provide the missing image"},{"text":" ","type":"text"},{"text":"by calling ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addImage(_:id:sdf:contentInsets:)"},{"type":"text","text":"."}],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"onStyleImageMissing","kind":"identifier"},{"kind":"text","text":": "},{"text":"Signal","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"text":"<","kind":"text"},{"text":"StyleImageMissing","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMStyleImageMissing"},{"text":">","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/loadStyle(_:transition:completion:)-1ilz1":{"url":"\/documentation\/mapboxmaps\/mapboxmap\/loadstyle(_:transition:completion:)-1ilz1","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/loadStyle(_:transition:completion:)-1ilz1","abstract":[{"text":"Loads a ","type":"text"},{"code":"style","type":"codeVoice"},{"text":" from a StyleURI, calling a completion closure when the","type":"text"},{"type":"text","text":" "},{"type":"text","text":"style is fully loaded or there has been an error during load."}],"kind":"symbol","title":"loadStyle(_:transition:completion:)","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"loadStyle","kind":"identifier"},{"text":"(","kind":"text"},{"text":"StyleURI","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps8StyleURIV"},{"kind":"text","text":", "},{"text":"transition","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TransitionOptions","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps17TransitionOptionsV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"text":": (((any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/endAnimation()":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/endAnimation()","url":"\/documentation\/mapboxmaps\/mapboxmap\/endanimation()","title":"endAnimation()","abstract":[{"type":"text","text":"If implementing a custom animation mechanism, call this method when the animation ends."}],"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"endAnimation","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onMapLoaded":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onMapLoaded","url":"\/documentation\/mapboxmaps\/mapboxmap\/onmaploaded","title":"onMapLoaded","abstract":[{"text":"The style has been fully loaded, and the map has rendered all visible tiles.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMapLoaded"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps6SignalV","text":"Signal","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)MBMMapLoaded","text":"MapLoaded","kind":"typeIdentifier"},{"text":">","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/addSource(withId:properties:)":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addSource(withId:properties:)","url":"\/documentation\/mapboxmaps\/stylemanager\/addsource(withid:properties:)","title":"addSource(withId:properties:)","abstract":[{"text":"Adds a new style source.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addSource","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"properties","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]) ","kind":"text"},{"kind":"keyword","text":"throws"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onMapIdle":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onMapIdle","url":"\/documentation\/mapboxmaps\/mapboxmap\/onmapidle","title":"onMapIdle","abstract":[{"text":"The map has entered the idle state. The map is in the idle state when there are no ongoing transitions","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"and the map has rendered all requested non-volatile tiles. The event will not be emitted if animation is in progress (see "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/beginAnimation()","isActive":true,"type":"reference"},{"text":", ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/endAnimation()"},{"type":"text","text":")"},{"text":" ","type":"text"},{"type":"text","text":"and \/ or gesture is in progress (see "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/beginGesture()"},{"type":"text","text":", "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/endGesture()"},{"type":"text","text":")."}],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onMapIdle"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps6SignalV","text":"Signal","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)MBMMapIdle","text":"MapIdle","kind":"typeIdentifier"},{"text":">","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/MapboxMapProtocol-Implementations":{"type":"topic","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/MapboxMapProtocol-Implementations","url":"\/documentation\/mapboxmaps\/mapboxmap\/mapboxmapprotocol-implementations","kind":"article","title":"MapboxMapProtocol Implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onCameraChanged":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onCameraChanged","url":"\/documentation\/mapboxmaps\/mapboxmap\/oncamerachanged","title":"onCameraChanged","abstract":[{"text":"The camera has changed. This event is emitted whenever the visible viewport","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"changes due to the MapView’s size changing or when the camera"},{"text":" ","type":"text"},{"text":"is modified by calling camera methods. The event is emitted synchronously,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"so that an updated camera state can be fetched immediately."}],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"onCameraChanged","kind":"identifier"},{"kind":"text","text":": "},{"text":"Signal","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"text":"<","kind":"text"},{"text":"CameraChanged","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMCameraChanged"},{"text":">","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onSourceRemoved":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onSourceRemoved","url":"\/documentation\/mapboxmaps\/mapboxmap\/onsourceremoved","title":"onSourceRemoved","abstract":[{"text":"The source has been removed with ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/removeSource(withId:)","type":"reference","isActive":true},{"type":"text","text":"."},{"type":"text","text":" "},{"text":"The event is emitted synchronously, thus, ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/allSourceIdentifiers"},{"text":" will be","type":"text"},{"type":"text","text":" "},{"text":"in sync when the observer receives the notification.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onSourceRemoved","kind":"identifier"},{"kind":"text","text":": "},{"text":"Signal","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMSourceRemoved","text":"SourceRemoved"},{"text":">","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onSourceDataLoaded":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onSourceDataLoaded","url":"\/documentation\/mapboxmaps\/mapboxmap\/onsourcedataloaded","title":"onSourceDataLoaded","abstract":[{"text":"A source data has been loaded.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Event may be emitted synchronously in cases when source’s metadata is available when source is added to the style."}],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"onSourceDataLoaded","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10MapboxMaps6SignalV","kind":"typeIdentifier","text":"Signal"},{"text":"<","kind":"text"},{"text":"SourceDataLoaded","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMSourceDataLoaded"},{"text":">","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapIdle":{"navigatorTitle":[{"kind":"identifier","text":"MapIdle"}],"abstract":[{"type":"text","text":"The "},{"code":"map","type":"codeVoice"},{"type":"text","text":" has entered the idle state. The "},{"type":"codeVoice","code":"map"},{"type":"text","text":" is idle when there are no ongoing"},{"type":"text","text":" "},{"type":"text","text":"animations, transitions and the "},{"type":"codeVoice","code":"map"},{"type":"text","text":" has rendered all requested non-volatile tiles"},{"type":"text","text":" "},{"text":"(e.g., live traffic tiles). The event will not be emitted if ","type":"text"},{"code":"setUserAnimationInProgress","type":"codeVoice"},{"type":"text","text":" "},{"type":"text","text":"and \/ or "},{"code":"setGestureInProgress","type":"codeVoice"},{"type":"text","text":" is set to "},{"code":"true","type":"codeVoice"},{"type":"text","text":"."}],"title":"MapIdle","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MapIdle","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapIdle","type":"topic","url":"\/documentation\/mapboxmaps\/mapidle","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onSourceAdded":{"url":"\/documentation\/mapboxmaps\/mapboxmap\/onsourceadded","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onSourceAdded","abstract":[{"type":"text","text":"The source has been added with "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addSource(_:dataId:)"},{"text":"  or ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addSource(withId:properties:)","isActive":true},{"type":"text","text":"."},{"text":" ","type":"text"},{"type":"text","text":"The event is emitted synchronously, therefore, it is possible to immediately"},{"text":" ","type":"text"},{"type":"text","text":"read added source’s properties."}],"kind":"symbol","title":"onSourceAdded","role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSourceAdded"},{"text":": ","kind":"text"},{"text":"Signal","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"text":"<","kind":"text"},{"text":"SourceAdded","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMSourceAdded"},{"kind":"text","text":">"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/removeSource(withId:)":{"url":"\/documentation\/mapboxmaps\/stylemanager\/removesource(withid:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/removeSource(withId:)","abstract":[{"text":"Removes an existing style source.","type":"text"}],"kind":"symbol","title":"removeSource(withId:)","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"removeSource"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}]}},"variantOverrides":[{"patch":[{"value":"MBMMapIdle","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdle\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdle\/fragments","value":[{"text":"MBMMapIdle","kind":"identifier"}],"op":"replace"},{"value":[{"text":"MBMMapIdle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapIdle\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}