{"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onMapLoadingError","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Signal","kind":"typeIdentifier","text":"Signal","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)MBMMapLoadingError","text":"MapLoadingError","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingError"},{"text":"> { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"abstract":[{"type":"text","text":"An error that has occurred while loading the Map. The "},{"code":"type","type":"codeVoice"},{"type":"text","text":" property defines what resource could"},{"type":"text","text":" "},{"type":"text","text":"not be loaded and the "},{"type":"codeVoice","code":"message"},{"type":"text","text":" property will contain a descriptive error message."},{"text":" ","type":"text"},{"text":"In case of ","type":"text"},{"type":"codeVoice","code":"source"},{"type":"text","text":" or "},{"type":"codeVoice","code":"tile"},{"type":"text","text":" loading errors, "},{"type":"codeVoice","code":"sourceID"},{"text":" or ","type":"text"},{"code":"tileID","type":"codeVoice"},{"type":"text","text":" will contain the identifier of the source failing."}],"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onMapLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleDataLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onCameraChanged","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onMapIdle","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onSourceAdded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onSourceRemoved","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onSourceDataLoaded","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleImageMissing","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleImageRemoveUnused","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onRenderFrameStarted","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onRenderFrameFinished","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onResourceRequest"],"title":"Map events","anchor":"Map-events"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onMapLoadingError"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/mapboxmap\/onmaploadingerror"]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap"],["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/MapboxMapProtocol-Implementations"]]},"metadata":{"externalID":"s:10MapboxMaps0A3MapC02onC12LoadingErrorAA6SignalVySo06MBMMapeF0CGvp","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"onMapLoadingError","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps6SignalV","kind":"typeIdentifier","text":"Signal"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMMapLoadingError","kind":"typeIdentifier","text":"MapLoadingError"},{"kind":"text","text":">"}],"modules":[{"name":"MapboxMaps"}],"title":"onMapLoadingError","extendedModule":"MapboxMaps","role":"symbol","symbolKind":"property"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/beginGesture()":{"role":"symbol","type":"topic","title":"beginGesture()","abstract":[{"type":"text","text":"If implementing a custom gesture, call this method when the gesture begins."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"beginGesture","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/beginGesture()","url":"\/documentation\/mapboxmaps\/mapboxmap\/begingesture()"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/addSource(_:dataId:)":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addSource(_:dataId:)","url":"\/documentation\/mapboxmaps\/stylemanager\/addsource(_:dataid:)","abstract":[{"type":"text","text":"Adds a "},{"type":"codeVoice","code":"source"},{"type":"text","text":" to the map"}],"title":"addSource(_:dataId:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"addSource","kind":"identifier"},{"kind":"text","text":"(any "},{"preciseIdentifier":"s:10MapboxMaps6SourceP","text":"Source","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"dataId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?) "},{"text":"throws","kind":"keyword"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap":{"kind":"symbol","title":"MapboxMap","role":"symbol","navigatorTitle":[{"text":"MapboxMap","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapboxMap"}],"abstract":[{"text":"Provides access to the map model, including the camera, style, observable map events,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"and querying rendered features."}],"url":"\/documentation\/mapboxmaps\/mapboxmap"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"role":"collection","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/addImage(_:id:sdf:contentInsets:)":{"title":"addImage(_:id:sdf:contentInsets:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"addImage","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"id"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"sdf","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"contentInsets","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIEdgeInsets","kind":"typeIdentifier","preciseIdentifier":"c:@S@UIEdgeInsets"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addImage(_:id:sdf:contentInsets:)","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Adds an image to be used in the style."}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/stylemanager\/addimage(_:id:sdf:contentinsets:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/removeSource(withId:)":{"title":"removeSource(withId:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"removeSource","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/removeSource(withId:)","role":"symbol","type":"topic","abstract":[{"text":"Removes an existing style source.","type":"text"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/stylemanager\/removesource(withid:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onStyleDataLoaded":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleDataLoaded","role":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/onstyledataloaded","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"onStyleDataLoaded","kind":"identifier"},{"kind":"text","text":": "},{"text":"Signal","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMStyleDataLoaded","text":"StyleDataLoaded"},{"text":">","kind":"text"}],"type":"topic","title":"onStyleDataLoaded","kind":"symbol","abstract":[{"text":"The requested style data has been loaded. The ","type":"text"},{"code":"type","type":"codeVoice"},{"type":"text","text":" property defines what kind of style data has been loaded."},{"text":" ","type":"text"},{"text":"Event may be emitted synchronously, for example, when ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/loadStyle(_:transition:completion:)-1ilz1"},{"text":" is used to load style.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onRenderFrameFinished":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onRenderFrameFinished","role":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/onrenderframefinished","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onRenderFrameFinished","kind":"identifier"},{"kind":"text","text":": "},{"text":"Signal","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"RenderFrameFinished","preciseIdentifier":"c:objc(cs)MBMRenderFrameFinished"},{"text":">","kind":"text"}],"type":"topic","title":"onRenderFrameFinished","kind":"symbol","abstract":[{"text":"The map finished rendering a frame.","type":"text"},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"code":"renderMode","type":"codeVoice"},{"text":" property tells whether the map has all data (","type":"text"},{"type":"codeVoice","code":"full"},{"text":") required to render the visible viewport.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"needsRepaint"},{"text":" property provides information about ongoing transitions that trigger map repaint.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The "},{"code":"placementChanged","type":"codeVoice"},{"type":"text","text":" property tells if the symbol placement has been changed in the visible viewport."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onSourceAdded":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onSourceAdded","role":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/onsourceadded","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onSourceAdded"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps6SignalV","text":"Signal","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"SourceAdded","preciseIdentifier":"c:objc(cs)MBMSourceAdded","kind":"typeIdentifier"},{"kind":"text","text":">"}],"type":"topic","title":"onSourceAdded","kind":"symbol","abstract":[{"type":"text","text":"The source has been added with "},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addSource(_:dataId:)","isActive":true},{"text":"  or ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addSource(withId:properties:)","isActive":true},{"type":"text","text":"."},{"type":"text","text":" "},{"text":"The event is emitted synchronously, therefore, it is possible to immediately","type":"text"},{"type":"text","text":" "},{"text":"read added source’s properties.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onMapIdle":{"title":"onMapIdle","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onMapIdle","type":"topic","role":"symbol","abstract":[{"type":"text","text":"The map has entered the idle state. The map is in the idle state when there are no ongoing transitions"},{"text":" ","type":"text"},{"type":"text","text":"and the map has rendered all requested non-volatile tiles. The event will not be emitted if animation is in progress (see "},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/beginAnimation()","isActive":true},{"text":", ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/endAnimation()","type":"reference","isActive":true},{"type":"text","text":")"},{"text":" ","type":"text"},{"type":"text","text":"and \/ or gesture is in progress (see "},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/beginGesture()","isActive":true},{"text":", ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/endGesture()","isActive":true},{"type":"text","text":")."}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/onmapidle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMapIdle"},{"text":": ","kind":"text"},{"text":"Signal","preciseIdentifier":"s:10MapboxMaps6SignalV","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"MapIdle","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMMapIdle"},{"kind":"text","text":">"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onMapLoaded":{"title":"onMapLoaded","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onMapLoaded","type":"topic","role":"symbol","abstract":[{"text":"The style has been fully loaded, and the map has rendered all visible tiles.","type":"text"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/onmaploaded","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"onMapLoaded","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Signal","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)MBMMapLoaded","kind":"typeIdentifier","text":"MapLoaded"},{"kind":"text","text":">"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onStyleLoaded":{"title":"onStyleLoaded","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleLoaded","type":"topic","role":"symbol","abstract":[{"text":"The requested style has been fully loaded, including the style, specified sprite and sources’ metadata.","type":"text"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/onstyleloaded","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onStyleLoaded"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps6SignalV","text":"Signal","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"StyleLoaded","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMStyleLoaded"},{"kind":"text","text":">"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onSourceDataLoaded":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"onSourceDataLoaded","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Signal","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"text":"<","kind":"text"},{"text":"SourceDataLoaded","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMSourceDataLoaded"},{"kind":"text","text":">"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/onsourcedataloaded","abstract":[{"text":"A source data has been loaded.","type":"text"},{"type":"text","text":" "},{"text":"Event may be emitted synchronously in cases when source’s metadata is available when source is added to the style.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onSourceDataLoaded","title":"onSourceDataLoaded","kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/loadStyle(_:transition:completion:)-1ilz1":{"title":"loadStyle(_:transition:completion:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/loadStyle(_:transition:completion:)-1ilz1","type":"topic","role":"symbol","abstract":[{"text":"Loads a ","type":"text"},{"code":"style","type":"codeVoice"},{"text":" from a StyleURI, calling a completion closure when the","type":"text"},{"text":" ","type":"text"},{"text":"style is fully loaded or there has been an error during load.","type":"text"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/loadstyle(_:transition:completion:)-1ilz1","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadStyle","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps8StyleURIV","text":"StyleURI"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"transition"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TransitionOptions","preciseIdentifier":"s:10MapboxMaps17TransitionOptionsV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"text":": (((any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapLoadingError":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapLoadingError","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapLoadingError"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MapLoadingError"}],"abstract":[{"text":"Describes an error that has occurred while loading the ","type":"text"},{"type":"codeVoice","code":"map"},{"text":". The ","type":"text"},{"code":"type","type":"codeVoice"},{"type":"text","text":" property"},{"type":"text","text":" "},{"type":"text","text":"defines what resource could not be loaded, and the "},{"code":"message","type":"codeVoice"},{"type":"text","text":" property will contain"},{"text":" ","type":"text"},{"type":"text","text":"a descriptive error message."}],"title":"MapLoadingError","url":"\/documentation\/mapboxmaps\/maploadingerror","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/beginAnimation()":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"beginAnimation"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/beginAnimation()","url":"\/documentation\/mapboxmaps\/mapboxmap\/beginanimation()","kind":"symbol","abstract":[{"text":"If implementing a custom animation mechanism, call this method when the animation begins.","type":"text"}],"title":"beginAnimation()","role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/addSource(withId:properties:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addSource","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"properties","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]) "},{"text":"throws","kind":"keyword"}],"url":"\/documentation\/mapboxmaps\/stylemanager\/addsource(withid:properties:)","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Adds a new style source."}],"title":"addSource(withId:properties:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addSource(withId:properties:)","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onRenderFrameStarted":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onRenderFrameStarted","role":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/onrenderframestarted","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onRenderFrameStarted","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Signal","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMRenderFrameStarted","text":"RenderFrameStarted","kind":"typeIdentifier"},{"text":">","kind":"text"}],"type":"topic","title":"onRenderFrameStarted","kind":"symbol","abstract":[{"text":"The map started rendering a frame.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onResourceRequest":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onResourceRequest","role":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/onresourcerequest","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onResourceRequest","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Signal","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"ResourceRequest","preciseIdentifier":"c:objc(cs)MBMResourceRequest"},{"text":">","kind":"text"}],"type":"topic","title":"onResourceRequest","kind":"symbol","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ResourceRequest"},{"text":" event allows client to observe resource requests made by a","type":"text"},{"type":"text","text":" "},{"text":"map or snapshotter.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onMapLoadingError":{"title":"onMapLoadingError","abstract":[{"type":"text","text":"An error that has occurred while loading the Map. The "},{"code":"type","type":"codeVoice"},{"text":" property defines what resource could","type":"text"},{"type":"text","text":" "},{"type":"text","text":"not be loaded and the "},{"code":"message","type":"codeVoice"},{"text":" property will contain a descriptive error message.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"In case of "},{"code":"source","type":"codeVoice"},{"type":"text","text":" or "},{"code":"tile","type":"codeVoice"},{"type":"text","text":" loading errors, "},{"type":"codeVoice","code":"sourceID"},{"type":"text","text":" or "},{"code":"tileID","type":"codeVoice"},{"type":"text","text":" will contain the identifier of the source failing."}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onMapLoadingError","url":"\/documentation\/mapboxmaps\/mapboxmap\/onmaploadingerror","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"onMapLoadingError","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Signal","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMMapLoadingError","text":"MapLoadingError","kind":"typeIdentifier"},{"text":">","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","role":"collection","abstract":[],"type":"topic","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onStyleImageMissing":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleImageMissing","role":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/onstyleimagemissing","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"onStyleImageMissing","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10MapboxMaps6SignalV","text":"Signal","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"StyleImageMissing","preciseIdentifier":"c:objc(cs)MBMStyleImageMissing"},{"text":">","kind":"text"}],"type":"topic","title":"onStyleImageMissing","kind":"symbol","abstract":[{"text":"A style has a missing image. This event is emitted when the map renders visible tiles and","type":"text"},{"text":" ","type":"text"},{"text":"one of the required images is missing in the sprite sheet. Subscriber has to provide the missing image","type":"text"},{"text":" ","type":"text"},{"text":"by calling ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/addImage(_:id:sdf:contentInsets:)"},{"text":".","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/endAnimation()":{"role":"symbol","type":"topic","title":"endAnimation()","abstract":[{"type":"text","text":"If implementing a custom animation mechanism, call this method when the animation ends."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"endAnimation","kind":"identifier"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/endAnimation()","url":"\/documentation\/mapboxmaps\/mapboxmap\/endanimation()"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onCameraChanged":{"title":"onCameraChanged","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onCameraChanged","type":"topic","role":"symbol","abstract":[{"type":"text","text":"The camera has changed. This event is emitted whenever the visible viewport"},{"text":" ","type":"text"},{"type":"text","text":"changes due to the MapView’s size changing or when the camera"},{"type":"text","text":" "},{"text":"is modified by calling camera methods. The event is emitted synchronously,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"so that an updated camera state can be fetched immediately."}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/oncamerachanged","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onCameraChanged"},{"text":": ","kind":"text"},{"text":"Signal","preciseIdentifier":"s:10MapboxMaps6SignalV","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"CameraChanged","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMCameraChanged"},{"kind":"text","text":">"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onSourceRemoved":{"title":"onSourceRemoved","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onSourceRemoved","type":"topic","role":"symbol","abstract":[{"text":"The source has been removed with ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/removeSource(withId:)"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The event is emitted synchronously, thus, "},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/allSourceIdentifiers","isActive":true},{"text":" will be","type":"text"},{"type":"text","text":" "},{"type":"text","text":"in sync when the observer receives the notification."}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/onsourceremoved","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"onSourceRemoved","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Signal","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps6SignalV"},{"kind":"text","text":"<"},{"text":"SourceRemoved","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMSourceRemoved"},{"kind":"text","text":">"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"role":"collectionGroup","abstract":[],"url":"\/documentation\/mapboxmaps\/mapboxmap-apis","title":"MapboxMap","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Signal":{"title":"Signal","navigatorTitle":[{"kind":"identifier","text":"Signal"}],"role":"symbol","abstract":[{"text":"Signal is a typed interface for observing arbitrary values over time.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Signal","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"Signal","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/signal"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/endGesture()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"endGesture"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/endGesture()","url":"\/documentation\/mapboxmaps\/mapboxmap\/endgesture()","kind":"symbol","abstract":[{"type":"text","text":"If implementing a custom gesture, call this method when the gesture ends."}],"title":"endGesture()","role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/allSourceIdentifiers":{"title":"allSourceIdentifiers","abstract":[{"text":"The ordered list of the current style sources’ identifiers and types.","type":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/mapboxmaps\/stylemanager\/allsourceidentifiers","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"allSourceIdentifiers","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:10MapboxMaps10SourceInfoV","text":"SourceInfo","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/allSourceIdentifiers","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/onStyleImageRemoveUnused":{"title":"onStyleImageRemoveUnused","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/onStyleImageRemoveUnused","type":"topic","role":"symbol","abstract":[{"text":"An image added to the style is no longer needed and can be removed using ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/removeImage(withId:)"},{"text":".","type":"text"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/onstyleimageremoveunused","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onStyleImageRemoveUnused","kind":"identifier"},{"kind":"text","text":": "},{"text":"Signal","preciseIdentifier":"s:10MapboxMaps6SignalV","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"text":"StyleImageRemoveUnused","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMStyleImageRemoveUnused"},{"text":">","kind":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleManager/removeImage(withId:)":{"role":"symbol","title":"removeImage(withId:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"removeImage"},{"text":"(","kind":"text"},{"text":"withId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"url":"\/documentation\/mapboxmaps\/stylemanager\/removeimage(withid:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleManager\/removeImage(withId:)","type":"topic","kind":"symbol","abstract":[{"text":"Removes an image from the style.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/MapboxMapProtocol-Implementations":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/MapboxMapProtocol-Implementations","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/mapboxmap\/mapboxmapprotocol-implementations","type":"topic","title":"MapboxMapProtocol Implementations","kind":"article","abstract":[]}},"variantOverrides":[{"patch":[{"value":"MBMMapLoadingError","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingError\/title"},{"value":[{"kind":"identifier","text":"MBMMapLoadingError"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingError\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapLoadingError\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMMapLoadingError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}