{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@discardableResult","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"querySourceFeatures"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"sourceId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"options","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceQueryOptions","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMSourceQueryOptions","text":"SourceQueryOptions"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"keyword"},{"text":" (","kind":"text"},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"text":"<[","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedSourceFeature","text":"QueriedSourceFeature","preciseIdentifier":"c:objc(cs)MBMQueriedSourceFeature","kind":"typeIdentifier"},{"kind":"text","text":"], any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":") -> any ","kind":"text"},{"text":"Cancelable","preciseIdentifier":"c:objc(pl)MBXCancelable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Cancelable","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"sourceId","content":[{"inlineContent":[{"type":"text","text":"Style source identifier used to query for source features."}],"type":"paragraph"}]},{"name":"options","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Options for querying source features."}]}]},{"name":"completion","content":[{"inlineContent":[{"type":"text","text":"Callback called when the query completes."}],"type":"paragraph"}]}],"kind":"parameters"}],"kind":"symbol","metadata":{"title":"querySourceFeatures(for:options:completion:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"querySourceFeatures","kind":"identifier"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"text":"SourceQueryOptions","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMSourceQueryOptions"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:s6ResultO","kind":"typeIdentifier","text":"Result"},{"text":"<[","kind":"text"},{"text":"QueriedSourceFeature","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMQueriedSourceFeature"},{"text":"], any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":">) -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":") -> any ","kind":"text"},{"text":"Cancelable","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MBXCancelable"}],"externalID":"s:10MapboxMaps0A3MapC19querySourceFeatures3for7options10completionSo13MBXCancelable_pSS_So21MBMSourceQueryOptionsCys6ResultOySaySo010MBMQueriedE7FeatureCGs5Error_pGctF","roleHeading":"Instance Method","symbolKind":"method","extendedModule":"MapboxMaps","role":"symbol","modules":[{"name":"MapboxMaps"}]},"abstract":[{"type":"text","text":"Queries the map for source features."}],"sections":[],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/querySourceFeatures(for:options:completion:)","interfaceLanguage":"swift"},"seeAlsoSections":[{"generated":true,"anchor":"Quering-map-features","title":"Quering map features","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/queryRenderedFeatures(with:options:completion:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/queryRenderedFeatures(with:targets:completion:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/querySourceFeatures(for:completion:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/getGeoJsonClusterLeaves(forSourceId:feature:limit:offset:completion:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/getGeoJsonClusterChildren(forSourceId:feature:completion:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/getGeoJsonClusterExpansionZoom(forSourceId:feature:completion:)"]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap"],["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/MapFeatureQueryable-Implementations"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/mapboxmaps\/mapboxmap\/querysourcefeatures(for:options:completion:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Cancelable":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Cancelable","url":"\/documentation\/mapboxcommon\/cancelable","type":"topic","title":"Cancelable","navigatorTitle":[{"text":"Cancelable","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"Cancelable","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Allows to cancel the associated asynchronous operation"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/querySourceFeatures(for:completion:)":{"type":"topic","title":"querySourceFeatures(for:completion:)","tags":[{"type":"spi","text":"SPI"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/querySourceFeatures(for:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"querySourceFeatures"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"text":"FeaturesetQueryTarget","preciseIdentifier":"s:10MapboxMaps21FeaturesetQueryTargetV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"text":"Result","preciseIdentifier":"s:s6ResultO","kind":"typeIdentifier"},{"text":"<[","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMQueriedSourceFeature","text":"QueriedSourceFeature"},{"kind":"text","text":"], any "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":") -> any ","kind":"text"},{"kind":"typeIdentifier","text":"Cancelable","preciseIdentifier":"c:objc(pl)MBXCancelable"}],"kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/querysourcefeatures(for:completion:)","abstract":[{"type":"text","text":"Queries  the source features for a given featureset."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/MapFeatureQueryable-Implementations":{"abstract":[],"url":"\/documentation\/mapboxmaps\/mapboxmap\/mapfeaturequeryable-implementations","kind":"article","type":"topic","title":"MapFeatureQueryable Implementations","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/MapFeatureQueryable-Implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/queryRenderedFeatures(with:targets:completion:)":{"abstract":[{"type":"text","text":"Queries the map for rendered features using featureset descriptors."}],"url":"\/documentation\/mapboxmaps\/mapboxmap\/queryrenderedfeatures(with:targets:completion:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"queryRenderedFeatures"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"kind":"text","text":": some "},{"kind":"typeIdentifier","text":"RenderedQueryGeometryConvertible","preciseIdentifier":"s:10MapboxMaps32RenderedQueryGeometryConvertibleP"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"targets"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps21FeaturesetQueryTargetV","text":"FeaturesetQueryTarget","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<["},{"text":"QueriedRenderedFeature","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMQueriedRenderedFeature"},{"text":"], any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":">) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":") -> any ","kind":"text"},{"text":"Cancelable","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MBXCancelable"}],"kind":"symbol","tags":[{"text":"SPI","type":"spi"}],"type":"topic","title":"queryRenderedFeatures(with:targets:completion:)","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/queryRenderedFeatures(with:targets:completion:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/QueriedSourceFeature":{"url":"\/documentation\/mapboxmaps\/queriedsourcefeature","role":"symbol","navigatorTitle":[{"text":"QueriedSourceFeature","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"QueriedSourceFeature"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/QueriedSourceFeature","type":"topic","title":"QueriedSourceFeature","abstract":[{"type":"text","text":"Represents query result that is returned in QuerySourceFeaturesCallback."}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","role":"collection","title":"MapboxMaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/getGeoJsonClusterLeaves(forSourceId:feature:limit:offset:completion:)":{"type":"topic","title":"getGeoJsonClusterLeaves(forSourceId:feature:limit:offset:completion:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/getGeoJsonClusterLeaves(forSourceId:feature:limit:offset:completion:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getGeoJsonClusterLeaves","kind":"identifier"},{"kind":"text","text":"("},{"text":"forSourceId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"feature","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Feature","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps7Featurea"},{"text":", ","kind":"text"},{"text":"limit","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V","text":"UInt64"},{"text":", ","kind":"text"},{"text":"offset","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UInt64","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:s6ResultO","text":"Result","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"FeatureExtensionValue","preciseIdentifier":"c:objc(cs)MBMFeatureExtensionValue"},{"text":", any ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":">) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MBXCancelable","text":"Cancelable"}],"kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/getgeojsonclusterleaves(forsourceid:feature:limit:offset:completion:)","abstract":[{"text":"Returns all the leaves (original points) of a cluster (given its cluster_id) from a GeoJSON source, with pagination support: limit is the number of leaves","type":"text"},{"type":"text","text":" "},{"type":"text","text":"to return (set to Infinity for all points), and offset is the amount of points to skip (for pagination)."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","title":"MapboxMap","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MapboxMap"}],"type":"topic","abstract":[{"type":"text","text":"Provides access to the map model, including the camera, style, observable map events,"},{"type":"text","text":" "},{"type":"text","text":"and querying rendered features."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapboxMap","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/mapboxmap","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/getGeoJsonClusterExpansionZoom(forSourceId:feature:completion:)":{"type":"topic","title":"getGeoJsonClusterExpansionZoom(forSourceId:feature:completion:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/getGeoJsonClusterExpansionZoom(forSourceId:feature:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getGeoJsonClusterExpansionZoom"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forSourceId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"feature","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps7Featurea","text":"Feature"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"text":"FeatureExtensionValue","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMFeatureExtensionValue"},{"text":", any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":">) -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":") -> any "},{"text":"Cancelable","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MBXCancelable"}],"kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/getgeojsonclusterexpansionzoom(forsourceid:feature:completion:)","abstract":[{"text":"Returns the zoom on which the cluster expands into several children (useful for “click to zoom” feature)","type":"text"},{"text":" ","type":"text"},{"text":"given the cluster’s cluster_id (cluster_id value from feature properties) from a GeoJSON source.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceQueryOptions":{"role":"symbol","url":"\/documentation\/mapboxmaps\/sourcequeryoptions","abstract":[{"type":"text","text":"Options for querying source features."}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceQueryOptions","navigatorTitle":[{"kind":"identifier","text":"SourceQueryOptions"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceQueryOptions"}],"title":"SourceQueryOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","kind":"article","role":"collectionGroup","type":"topic","title":"MapboxMap","url":"\/documentation\/mapboxmaps\/mapboxmap-apis","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","kind":"article","type":"topic","url":"\/documentation\/overview","title":"MapboxMaps Documentation","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/querySourceFeatures(for:options:completion:)":{"type":"topic","title":"querySourceFeatures(for:options:completion:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/querySourceFeatures(for:options:completion:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"querySourceFeatures","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"options","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMSourceQueryOptions","text":"SourceQueryOptions"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:s6ResultO","kind":"typeIdentifier","text":"Result"},{"text":"<[","kind":"text"},{"text":"QueriedSourceFeature","preciseIdentifier":"c:objc(cs)MBMQueriedSourceFeature","kind":"typeIdentifier"},{"text":"], any ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":") -> any ","kind":"text"},{"text":"Cancelable","preciseIdentifier":"c:objc(pl)MBXCancelable","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/mapboxmap\/querysourcefeatures(for:options:completion:)","abstract":[{"type":"text","text":"Queries the map for source features."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/queryRenderedFeatures(with:options:completion:)":{"abstract":[{"type":"text","text":"Queries the map for rendered features."}],"url":"\/documentation\/mapboxmaps\/mapboxmap\/queryrenderedfeatures(with:options:completion:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"queryRenderedFeatures"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":": some "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps32RenderedQueryGeometryConvertibleP","text":"RenderedQueryGeometryConvertible"},{"text":", ","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMRenderedQueryOptions","kind":"typeIdentifier","text":"RenderedQueryOptions"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"text":"<[","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMQueriedRenderedFeature","kind":"typeIdentifier","text":"QueriedRenderedFeature"},{"text":"], any ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":">) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> any "},{"text":"Cancelable","preciseIdentifier":"c:objc(pl)MBXCancelable","kind":"typeIdentifier"}],"kind":"symbol","type":"topic","title":"queryRenderedFeatures(with:options:completion:)","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/queryRenderedFeatures(with:options:completion:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/getGeoJsonClusterChildren(forSourceId:feature:completion:)":{"abstract":[{"text":"Returns the children (original points or clusters) of a cluster (on the next zoom level)","type":"text"},{"text":" ","type":"text"},{"text":"given its id (cluster_id value from feature properties) from a GeoJSON source.","type":"text"}],"url":"\/documentation\/mapboxmaps\/mapboxmap\/getgeojsonclusterchildren(forsourceid:feature:completion:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getGeoJsonClusterChildren","kind":"identifier"},{"kind":"text","text":"("},{"text":"forSourceId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"feature","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps7Featurea","text":"Feature","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"text":"FeatureExtensionValue","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMFeatureExtensionValue"},{"kind":"text","text":", any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":">) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":") -> any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)MBXCancelable","text":"Cancelable","kind":"typeIdentifier"}],"kind":"symbol","type":"topic","title":"getGeoJsonClusterChildren(forSourceId:feature:completion:)","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/getGeoJsonClusterChildren(forSourceId:feature:completion:)"}},"variantOverrides":[{"patch":[{"value":"MBXCancelable","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/fragments","value":[{"text":"MBXCancelable","kind":"identifier"}]},{"op":"replace","value":[{"text":"MBXCancelable","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Cancelable\/navigatorTitle"},{"op":"replace","value":"MBMQueriedSourceFeature","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedSourceFeature\/title"},{"op":"replace","value":[{"text":"MBMQueriedSourceFeature","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedSourceFeature\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1QueriedSourceFeature\/navigatorTitle","value":[{"text":"MBMQueriedSourceFeature","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceQueryOptions\/title","value":"MBMSourceQueryOptions","op":"replace"},{"value":[{"kind":"identifier","text":"MBMSourceQueryOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceQueryOptions\/fragments"},{"op":"replace","value":[{"text":"MBMSourceQueryOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceQueryOptions\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}