{"metadata":{"roleHeading":"Instance Method","title":"tileCover(for:)","externalID":"s:10MapboxMaps0A3MapC9tileCover3forSaySo18MBMCanonicalTileIDCGAA0hE7OptionsV_tF","symbolKind":"method","extendedModule":"MapboxMaps","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tileCover"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps16TileCoverOptionsV","text":"TileCoverOptions","kind":"typeIdentifier"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMCanonicalTileID","text":"CanonicalTileID"},{"kind":"text","text":"]"}],"tags":[{"type":"spi","text":"SPI"}],"modules":[{"name":"MapboxMaps"}],"role":"symbol"},"variants":[{"paths":["\/documentation\/mapboxmaps\/mapboxmap\/tilecover(for:)"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"tileCover","kind":"identifier"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"options"},{"text":": ","kind":"text"},{"text":"TileCoverOptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCoverOptions","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps16TileCoverOptionsV"},{"kind":"text","text":") -> ["},{"preciseIdentifier":"c:objc(cs)MBMCanonicalTileID","text":"CanonicalTileID","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"options","content":[{"type":"paragraph","inlineContent":[{"text":"Options for the tile cover method.","type":"text"}]}]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/tileCover(for:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap"]]},"abstract":[{"type":"text","text":"Returns array of tile identifiers that cover current map camera."}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap","url":"\/documentation\/mapboxmaps\/mapboxmap","role":"symbol","type":"topic","abstract":[{"text":"Provides access to the map model, including the camera, style, observable map events,","type":"text"},{"type":"text","text":" "},{"text":"and querying rendered features.","type":"text"}],"title":"MapboxMap","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapboxMap"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MapboxMap"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","role":"collection","url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"title":"MapboxMaps","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCoverOptions":{"role":"symbol","abstract":[{"text":"Various options needed for tile cover.","type":"text"}],"url":"\/documentation\/mapboxmaps\/tilecoveroptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TileCoverOptions"}],"tags":[{"text":"SPI","type":"spi"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"TileCoverOptions","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCoverOptions","title":"TileCoverOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CanonicalTileID":{"kind":"symbol","type":"topic","navigatorTitle":[{"text":"CanonicalTileID","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CanonicalTileID"}],"title":"CanonicalTileID","role":"symbol","url":"\/documentation\/mapboxmaps\/canonicaltileid","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CanonicalTileID","abstract":[{"text":"Represents a tile coordinate.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap/tileCover(for:)":{"type":"topic","title":"tileCover(for:)","url":"\/documentation\/mapboxmaps\/mapboxmap\/tilecover(for:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tileCover"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps16TileCoverOptionsV","kind":"typeIdentifier","text":"TileCoverOptions"},{"text":") -> [","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMCanonicalTileID","kind":"typeIdentifier","text":"CanonicalTileID"},{"text":"]","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap\/tileCover(for:)","abstract":[{"text":"Returns array of tile identifiers that cover current map camera.","type":"text"}],"tags":[{"type":"spi","text":"SPI"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/title","op":"replace","value":"MBMCanonicalTileID"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/fragments","op":"replace","value":[{"text":"MBMCanonicalTileID","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CanonicalTileID\/navigatorTitle","value":[{"text":"MBMCanonicalTileID","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}