{"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Vec2\/isEqual(to:)","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/vec2\/isequal(to:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/vec2\/isequal(to:)"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Free-Camera","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Vec2"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"other","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Vec2","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Vec2","preciseIdentifier":"c:objc(cs)MBMVec2","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"modules":[{"name":"MapboxMaps"}],"externalID":"c:objc(cs)MBMVec2(im)isEqualToVec2:","role":"symbol","roleHeading":"Instance Method","title":"isEqual(to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MBMVec2","kind":"typeIdentifier","text":"Vec2"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"isEqualToVec2:"}],"symbolKind":"method"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMaps":{"type":"topic","title":"Core Maps API","abstract":[{"type":"text","text":"Maps rendering SDK also known as GL-Native"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","kind":"article","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/coremaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Vec2":{"title":"Vec2","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Vec2","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/vec2","navigatorTitle":[{"text":"Vec2","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Vec2","type":"topic","role":"symbol","abstract":[{"text":"2 component vector.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Vec2/isEqual(to:)":{"title":"isEqual(to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MBMVec2","kind":"typeIdentifier","text":"Vec2"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/vec2\/isequal(to:)","navigatorTitle":[{"kind":"identifier","text":"isEqualToVec2:"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Vec2\/isEqual(to:)","type":"topic","role":"symbol","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","url":"\/documentation\/overview","role":"collection","abstract":[],"kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Free-Camera":{"abstract":[],"kind":"article","url":"\/documentation\/mapboxmaps\/free-camera","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Free-Camera","title":"Free Camera","type":"topic","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"type":"topic","url":"\/documentation\/mapboxmaps","role":"collection","kind":"symbol","title":"MapboxMaps"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"isEqualToVec2:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqualToVec2:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isEqualToVec2:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Vec2","text":"MBMVec2","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMVec2"},{"text":" *) ","kind":"text"},{"text":"other","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Vec2\/title","value":"MBMVec2","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Vec2\/fragments","value":[{"text":"MBMVec2","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Vec2\/navigatorTitle","value":[{"kind":"identifier","text":"MBMVec2"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Vec2~1isEqual(to:)\/title","value":"isEqualToVec2:","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1Vec2~1isEqual(to:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqualToVec2:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}