{"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestOrResponseType\/Equatable-Implementations"},"kind":"article","metadata":{"modules":[{"name":"MapboxCommon"}],"role":"collectionGroup","title":"Equatable Implementations","roleHeading":"API Collection"},"topicSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestOrResponseType\/!=(_:_:)"],"title":"Operators","generated":true,"anchor":"Operators"}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestOrResponseType"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestOrResponseType/!=(_:_:)":{"abstract":[],"url":"\/documentation\/mapboxcommon\/httprequestorresponsetype\/!=(_:_:)","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestOrResponseType\/!=(_:_:)","title":"!=(_:_:)"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","abstract":[],"url":"\/documentation\/overview","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestOrResponseType":{"type":"topic","navigatorTitle":[{"text":"HttpRequestOrResponseType","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestOrResponseType","title":"HttpRequestOrResponseType","abstract":[],"url":"\/documentation\/mapboxcommon\/httprequestorresponsetype","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HttpRequestOrResponseType","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","title":"MapboxCommon","url":"\/documentation\/mapboxcommon","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"MBXHttpRequestOrResponseType","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestOrResponseType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBXHttpRequestOrResponseType"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestOrResponseType\/fragments"},{"op":"replace","value":[{"text":"MBXHttpRequestOrResponseType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestOrResponseType\/navigatorTitle"}]}]}