{"sections":[],"abstract":[{"type":"text","text":"Flag to prevent the HTTP request from being coalesced with other equivalent request(s) that are currently on"},{"text":" ","type":"text"},{"text":"the fly. Setting this flag will ensure that the request made through the HTTP service interface results in","type":"text"},{"text":" ","type":"text"},{"text":"its own network request.","type":"text"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"preventCoalescing"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt32","preciseIdentifier":"s:s6UInt32V"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestFlags\/preventCoalescing"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/httprequestflags\/preventcoalescing"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/httprequestflags\/preventcoalescing"]}],"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PreventCoalescing"}],"modules":[{"name":"MapboxCommon"}],"roleHeading":"Type Property","externalID":"c:objc(cs)MBXHttpRequestFlags(cpy)PreventCoalescing","symbolKind":"property","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"preventCoalescing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt32","preciseIdentifier":"s:s6UInt32V"}],"title":"preventCoalescing"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestFlags"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","role":"collection","url":"\/documentation\/overview","kind":"article","abstract":[],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"type":"topic","url":"\/documentation\/mapboxcommon","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","role":"collection","kind":"symbol","abstract":[],"title":"MapboxCommon"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestFlags/preventCoalescing":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestFlags\/preventCoalescing","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"preventCoalescing"},{"kind":"text","text":": "},{"text":"UInt32","preciseIdentifier":"s:s6UInt32V","kind":"typeIdentifier"}],"type":"topic","abstract":[{"text":"Flag to prevent the HTTP request from being coalesced with other equivalent request(s) that are currently on","type":"text"},{"type":"text","text":" "},{"type":"text","text":"the fly. Setting this flag will ensure that the request made through the HTTP service interface results in"},{"type":"text","text":" "},{"text":"its own network request.","type":"text"}],"url":"\/documentation\/mapboxcommon\/httprequestflags\/preventcoalescing","navigatorTitle":[{"text":"PreventCoalescing","kind":"identifier"}],"kind":"symbol","title":"preventCoalescing"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestFlags":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestFlags","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HttpRequestFlags"}],"type":"topic","abstract":[],"url":"\/documentation\/mapboxcommon\/httprequestflags","navigatorTitle":[{"kind":"identifier","text":"HttpRequestFlags"}],"kind":"symbol","title":"HttpRequestFlags"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Property"},{"path":"\/metadata\/title","value":"PreventCoalescing","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"PreventCoalescing"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"uint32_t","preciseIdentifier":"c:@T@uint32_t","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreventCoalescing"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"PreventCoalescing","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestFlags~1preventCoalescing\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestFlags~1preventCoalescing\/fragments","value":[{"kind":"identifier","text":"PreventCoalescing"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestFlags\/title","value":"MBXHttpRequestFlags"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestFlags\/fragments","value":[{"text":"MBXHttpRequestFlags","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestFlags\/navigatorTitle","value":[{"text":"MBXHttpRequestFlags","kind":"identifier"}]}]}]}