{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType\/custom"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType"]]},"abstract":[{"type":"text","text":"Layer with custom rendering implementation ("},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerHost","type":"reference","isActive":true},{"type":"text","text":")"}],"variants":[{"paths":["\/documentation\/mapboxmaps\/layertype\/custom"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"custom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps9LayerTypeV","text":"LayerType","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayer"}]}],"name":"See Also","style":"note"}],"kind":"content"}],"kind":"symbol","metadata":{"role":"symbol","externalID":"s:10MapboxMaps9LayerTypeV6customACvpZ","symbolKind":"property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"custom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps9LayerTypeV","text":"LayerType"}],"title":"custom","roleHeading":"Type Property","modules":[{"name":"MapboxMaps"}]},"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","url":"\/documentation\/overview","role":"collection","abstract":[],"kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerType/custom":{"kind":"symbol","abstract":[{"type":"text","text":"Layer with custom rendering implementation ("},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerHost","isActive":true},{"type":"text","text":")"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"custom","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps9LayerTypeV","text":"LayerType","kind":"typeIdentifier"}],"title":"custom","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType\/custom","url":"\/documentation\/mapboxmaps\/layertype\/custom","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LayerType":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LayerType"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LayerType","url":"\/documentation\/mapboxmaps\/layertype","navigatorTitle":[{"kind":"identifier","text":"LayerType"}],"title":"LayerType","abstract":[{"text":"Struct of supported Layer rendering types","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"type":"topic","url":"\/documentation\/mapboxmaps","role":"collection","kind":"symbol","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layers":{"title":"Layers","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers","abstract":[],"role":"collectionGroup","kind":"article","url":"\/documentation\/mapboxmaps\/layers"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerHost":{"abstract":[{"type":"text","text":"Interface for hosting a custom map style layer."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerHost","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CustomLayerHost"}],"title":"CustomLayerHost","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomLayerHost"}],"url":"\/documentation\/mapboxmaps\/customlayerhost"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayer":{"title":"CustomLayer","kind":"symbol","role":"symbol","tags":[{"type":"spi","text":"SPI"}],"abstract":[{"type":"text","text":"Layer with custom rendering implementation"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomLayer"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"CustomLayer"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayer","url":"\/documentation\/mapboxmaps\/customlayer"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MBMCustomLayerHost","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MBMCustomLayerHost"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MBMCustomLayerHost"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost\/navigatorTitle","op":"replace"}]}]}