{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapRecorderOptions\/init(timeWindow:loggingEnabled:compressed:)"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapRecorderOptions"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Initializes a set of options to control the recording of a map recording"}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"timeWindow","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"loggingEnabled","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"compressed","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"MapboxMaps"}],"externalID":"s:10MapboxMaps18MapRecorderOptionsV10timeWindow14loggingEnabled10compressedACSiSg_S2btcfc","role":"symbol","title":"init(timeWindow:loggingEnabled:compressed:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"timeWindow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":"?, ","kind":"text"},{"text":"loggingEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"compressed","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"roleHeading":"Initializer","symbolKind":"init"},"variants":[{"paths":["\/documentation\/mapboxmaps\/maprecorderoptions\/init(timewindow:loggingenabled:compressed:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapRecorder":{"type":"topic","role":"symbol","title":"MapRecorder","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapRecorder","url":"\/documentation\/mapboxmaps\/maprecorder","abstract":[{"type":"text","text":"MapRecorder provides functions to record and replay API calls of a Map instance."},{"text":" ","type":"text"},{"text":"These recordings can be used to debug issues which requie multiple steps to reproduce.","type":"text"},{"type":"text","text":" "},{"text":"Additionaly, playbacks can be used for performance testing custom scenarios.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MapRecorder","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MapRecorder"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapRecorderOptions":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapRecorderOptions","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"MapRecorderOptions","kind":"identifier"}],"title":"MapRecorderOptions","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/maprecorderoptions","abstract":[{"type":"text","text":"Options for recording the map when using "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapRecorder"}],"navigatorTitle":[{"text":"MapRecorderOptions","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapRecorderOptions/init(timeWindow:loggingEnabled:compressed:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapRecorderOptions\/init(timeWindow:loggingEnabled:compressed:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"timeWindow","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"loggingEnabled"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"compressed","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":")","kind":"text"}],"title":"init(timeWindow:loggingEnabled:compressed:)","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/maprecorderoptions\/init(timewindow:loggingenabled:compressed:)","abstract":[{"text":"Initializes a set of options to control the recording of a map recording","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Performance":{"title":"Performance and investigations","url":"\/documentation\/mapboxmaps\/performance","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","role":"collectionGroup","abstract":[],"type":"topic","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","abstract":[],"kind":"article","url":"\/documentation\/overview","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"url":"\/documentation\/mapboxmaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","role":"collection","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapRecorder\/title","value":"MBMMapRecorder"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapRecorder\/fragments","value":[{"kind":"identifier","text":"MBMMapRecorder"}]},{"value":[{"text":"MBMMapRecorder","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapRecorder\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}