{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"right","kind":"identifier"}],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/viewannotationanchor\/right"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/viewannotationanchor\/right"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchor\/right"},"abstract":[{"text":"The right side of the view annotation is placed closest to the geometry.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/View-Annotations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchor"]]},"metadata":{"externalID":"c:@E@MBMViewAnnotationAnchor@MBMViewAnnotationAnchorRight","roleHeading":"Case","role":"symbol","navigatorTitle":[{"text":"MBMViewAnnotationAnchorRight","kind":"identifier"}],"modules":[{"name":"MapboxMaps"}],"symbolKind":"case","title":"ViewAnnotationAnchor.right","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"right","kind":"identifier"}]},"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","url":"\/documentation\/overview","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"role":"collection","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationAnchor/right":{"role":"symbol","kind":"symbol","abstract":[{"text":"The right side of the view annotation is placed closest to the geometry.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchor\/right","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"right"}],"url":"\/documentation\/mapboxmaps\/viewannotationanchor\/right","navigatorTitle":[{"text":"MBMViewAnnotationAnchorRight","kind":"identifier"}],"title":"ViewAnnotationAnchor.right"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/View-Annotations":{"role":"collectionGroup","type":"topic","url":"\/documentation\/mapboxmaps\/view-annotations","kind":"article","title":"View Annotations","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/View-Annotations","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ViewAnnotationAnchor":{"role":"symbol","abstract":[{"type":"text","text":"Enum describing how to place view annotation relatively to geometry."}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ViewAnnotationAnchor","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ViewAnnotationAnchor","type":"topic","navigatorTitle":[{"text":"ViewAnnotationAnchor","kind":"identifier"}],"title":"ViewAnnotationAnchor","url":"\/documentation\/mapboxmaps\/viewannotationanchor"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"MBMViewAnnotationAnchorRight"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"MBMViewAnnotationAnchorRight","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"MBMViewAnnotationAnchorRight","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchor~1right\/title","value":"MBMViewAnnotationAnchorRight","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchor~1right\/fragments","op":"replace","value":[{"text":"MBMViewAnnotationAnchorRight","kind":"identifier"}]},{"value":"MBMViewAnnotationAnchor","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchor\/title"},{"value":[{"kind":"identifier","text":"MBMViewAnnotationAnchor"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchor\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ViewAnnotationAnchor\/navigatorTitle","value":[{"kind":"identifier","text":"MBMViewAnnotationAnchor"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}