{"metadata":{"externalID":"c:objc(cs)MBXMapboxCommonSettings","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapboxCommonSettings"}],"role":"symbol","title":"MapboxCommonSettings","roleHeading":"Class","navigatorTitle":[{"text":"MapboxCommonSettings","kind":"identifier"}],"modules":[{"name":"MapboxCommon"}]},"variants":[{"paths":["\/documentation\/mapboxcommon\/mapboxcommonsettings"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxcommon\/mapboxcommonsettings"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Set of common keys that can be used to configure all Mapbox SDKs."}],"seeAlsoSections":[{"anchor":"Settings","title":"Settings","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MapboxOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMapsOptions"],"generated":true}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapboxCommonSettings","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MapboxCommonSettings"},"sections":[],"topicSections":[{"anchor":"Type-Properties","title":"Type Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MapboxCommonSettings\/language","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MapboxCommonSettings\/worldview"],"generated":true}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH"],"kind":"relationships","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Settings-and-Constants"]]},"references":{"doc://com.mapbox.MapboxMaps/objc(cs)NSObject":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MapboxCommonSettings/language":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MapboxCommonSettings\/language","abstract":[{"type":"text","text":"The key that defines a language to be used by Mapbox SDKs."},{"type":"text","text":" "},{"type":"text","text":"The value of the key must be a string that is a valid IETF BCP-47 language tag (eg. “en-US”)."}],"url":"\/documentation\/mapboxcommon\/mapboxcommonsettings\/language","role":"symbol","title":"language","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"language","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}],"navigatorTitle":[{"text":"Language","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"url":"\/documentation\/overview","kind":"article","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","type":"topic"},"doc://com.mapbox.MapboxMaps/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MapboxCommonSettings/worldview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MapboxCommonSettings\/worldview","navigatorTitle":[{"kind":"identifier","text":"Worldview"}],"type":"topic","title":"worldview","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"worldview"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"!"}],"abstract":[{"text":"The key that defines a worldview to be used by the Mapbox SDKs.","type":"text"},{"text":" ","type":"text"},{"text":"The value of the key must be a string that is a valid ISO 3166-1 alpha-2 country code (eg. “US”).","type":"text"}],"url":"\/documentation\/mapboxcommon\/mapboxcommonsettings\/worldview","kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","title":"Swift.Equatable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MapboxCommonSettings":{"title":"MapboxCommonSettings","kind":"symbol","abstract":[{"type":"text","text":"Set of common keys that can be used to configure all Mapbox SDKs."}],"navigatorTitle":[{"kind":"identifier","text":"MapboxCommonSettings"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapboxCommonSettings"}],"role":"symbol","url":"\/documentation\/mapboxcommon\/mapboxcommonsettings","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MapboxCommonSettings","type":"topic"},"doc://com.mapbox.MapboxMaps/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"url":"\/documentation\/mapboxmaps","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","title":"MapboxMaps","kind":"symbol","role":"collection"},"doc://com.mapbox.MapboxMaps/s7CVarArgP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MapboxOptions":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapboxOptions"}],"type":"topic","url":"\/documentation\/mapboxcommon\/mapboxoptions","abstract":[{"type":"text","text":"Class for Mapbox SDK settings management"}],"title":"MapboxOptions","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MapboxOptions"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MapboxOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMapsOptions":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMapsOptions","url":"\/documentation\/mapboxmaps\/mapboxmapsoptions","kind":"symbol","role":"symbol","title":"MapboxMapsOptions","type":"topic","abstract":[{"type":"text","text":"Configurations for the external resources that are used by Maps API object,"},{"type":"text","text":" "},{"type":"text","text":"such as maps data directory and base URL."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapboxMapsOptions"}],"navigatorTitle":[{"kind":"identifier","text":"MapboxMapsOptions"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Settings-and-Constants":{"title":"Settings and Constants","kind":"article","url":"\/documentation\/mapboxmaps\/settings-and-constants","abstract":[],"role":"collectionGroup","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Settings-and-Constants"},"doc://com.mapbox.MapboxMaps/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/SH":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","title":"Swift.Hashable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"MBXMapboxCommonSettings","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MBXMapboxCommonSettings"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MBXMapboxCommonSettings"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MapboxCommonSettings\/language","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MapboxCommonSettings\/worldview"],"title":"Type Properties","generated":true,"anchor":"Type-Properties"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"}],"op":"replace"},{"path":"\/seeAlsoSections","value":[{"generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MapboxOptions"],"title":"Settings","anchor":"Settings"}],"op":"replace"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBXMapboxCommonSettings","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MapboxCommonSettings~1language\/title","value":"Language","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MapboxCommonSettings~1language\/fragments","value":[{"text":"Language","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MapboxCommonSettings~1worldview\/title","value":"Worldview","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MapboxCommonSettings~1worldview\/fragments","value":[{"text":"Worldview","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MapboxCommonSettings\/title","value":"MBXMapboxCommonSettings","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MapboxCommonSettings\/fragments","value":[{"kind":"identifier","text":"MBXMapboxCommonSettings"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MapboxCommonSettings\/navigatorTitle","value":[{"kind":"identifier","text":"MBXMapboxCommonSettings"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MapboxOptions\/title","value":"MBXMapboxOptions","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MapboxOptions\/fragments","value":[{"text":"MBXMapboxOptions","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MapboxOptions\/navigatorTitle","value":[{"kind":"identifier","text":"MBXMapboxOptions"}],"op":"replace"}]}]}