{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBXPermissionStatusToString","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"permission_status"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@MBXPermissionStatus","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus","text":"PermissionStatus"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"!"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/mapboxcommon\/mbxpermissionstatustostring(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxcommon\/mbxpermissionstatustostring(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXPermissionStatusToString(_:)"},"metadata":{"symbolKind":"func","roleHeading":"Function","modules":[{"name":"MapboxCommon"}],"externalID":"c:@F@MBXPermissionStatusToString","title":"MBXPermissionStatusToString(_:)","navigatorTitle":[{"text":"MBXPermissionStatusToString","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBXPermissionStatusToString","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PermissionStatus","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBXPermissionStatus"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXPermissionStatusToString(_:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXPermissionStatusToString(_:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBXPermissionStatusToString"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PermissionStatus","preciseIdentifier":"c:@E@MBXPermissionStatus"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"type":"topic","url":"\/documentation\/mapboxcommon\/mbxpermissionstatustostring(_:)","navigatorTitle":[{"kind":"identifier","text":"MBXPermissionStatusToString"}],"title":"MBXPermissionStatusToString(_:)","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PermissionStatus":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PermissionStatus","kind":"identifier"}],"navigatorTitle":[{"text":"PermissionStatus","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/permissionstatus","title":"PermissionStatus","abstract":[{"text":"Location permissions granted by user to the app.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"url":"\/documentation\/overview","kind":"article","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"title":"MapboxCommon","kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","url":"\/documentation\/mapboxcommon","role":"collection","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Function","op":"replace","path":"\/metadata\/roleHeading"},{"value":"MBXPermissionStatusToString","op":"replace","path":"\/metadata\/title"},{"value":"func","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"MBXPermissionStatusToString","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"MBXPermissionStatusToString"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PermissionStatus","kind":"typeIdentifier","text":"MBXPermissionStatus","preciseIdentifier":"c:@E@MBXPermissionStatus"},{"kind":"text","text":" "},{"kind":"internalParam","text":"permission_status"},{"kind":"text","text":");"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MBXPermissionStatusToString(_:)\/title","value":"MBXPermissionStatusToString"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MBXPermissionStatusToString(_:)\/fragments","value":[{"kind":"identifier","text":"MBXPermissionStatusToString"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/title","value":"MBXPermissionStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/fragments","value":[{"kind":"identifier","text":"MBXPermissionStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PermissionStatus\/navigatorTitle","value":[{"kind":"identifier","text":"MBXPermissionStatus"}]}]}]}