name: Deploy

on:
  push:
    branches: [publisher-staging, publisher-production]

env:
  bucket: '{ "staging": "docs.mapbox.com-staging/ios/api", "production": "docs.mapbox.com/ios/api" }'

jobs:
  deploy:
    name: Deploy to ${{ matrix.environment }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        environment: [staging, production]
        exclude:
          - environment: ${{ github.ref_name != 'publisher-staging' && 'staging' }}
          - environment: ${{ github.ref_name != 'publisher-production' && 'production' }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure AWS Credentials
        uses: mapbox/configure-aws-credentials-internal@v5
        with:
          target-account-id: ${{ vars.AWS_ACCOUNT_ID_DEFAULT }}

      - name: Sync non-html and json files to ${{ matrix.environment }}
        run: aws s3 sync . ${{ env.targetBucket }} --exclude "*" --include "*.*.*/*" --exclude "*.*.*/*.html" --exclude "*.*.*/*.json" --cache-control "max-age=31536000"
        env:
          targetBucket: s3://${{ fromJson(env.bucket)[matrix.environment] }}

      - name: Sync html and json files to ${{ matrix.environment }}
        run: aws s3 sync . ${{ env.targetBucket }} --exclude "*" --include "*.*.*/*.html" --include "*.*.*/*.json" --cache-control "max-age=10,stale-while-revalidate=60"
        env:
          targetBucket: s3://${{ fromJson(env.bucket)[matrix.environment] }}