{"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceFactory","interfaceLanguage":"swift"},"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsService","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceStorageType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SdkInformation"],"title":"Common Settings","anchor":"Common-Settings"}],"sections":[],"metadata":{"role":"symbol","symbolKind":"class","navigatorTitle":[{"text":"SettingsServiceFactory","kind":"identifier"}],"modules":[{"name":"MapboxCommon"}],"title":"SettingsServiceFactory","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SettingsServiceFactory","kind":"identifier"}],"externalID":"c:objc(cs)MBXSettingsServiceFactory","roleHeading":"Class"},"topicSections":[{"title":"Type Methods","anchor":"Type-Methods","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceFactory\/getInstance(storageType:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceFactory\/getInstanceFor(_:)"],"generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SettingsServiceFactory"}],"platforms":["iOS"]}]}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"]},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH"],"type":"conformsTo"}],"abstract":[{"type":"text","text":"Factory that allows to create settings service instance."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Settings-and-Constants"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/mapboxcommon\/settingsservicefactory"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/settingsservicefactory"]}],"references":{"doc://com.mapbox.MapboxMaps/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject"},"doc://com.mapbox.MapboxMaps/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ"},"doc://com.mapbox.MapboxMaps/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsServiceError":{"kind":"symbol","title":"SettingsServiceError","role":"symbol","abstract":[{"type":"text","text":"Structure for keeping an information about errors that can happen when using Settings service"}],"url":"\/documentation\/mapboxcommon\/settingsserviceerror","type":"topic","navigatorTitle":[{"text":"SettingsServiceError","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceError","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SettingsServiceError"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","abstract":[],"type":"topic","kind":"article","role":"collection"},"doc://com.mapbox.MapboxMaps/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Settings-and-Constants":{"title":"Settings and Constants","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Settings-and-Constants","abstract":[],"role":"collectionGroup","kind":"article","url":"\/documentation\/mapboxmaps\/settings-and-constants","type":"topic"},"doc://com.mapbox.MapboxMaps/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsServiceFactory":{"url":"\/documentation\/mapboxcommon\/settingsservicefactory","kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceFactory","title":"SettingsServiceFactory","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SettingsServiceFactory"}],"abstract":[{"type":"text","text":"Factory that allows to create settings service instance."}],"navigatorTitle":[{"text":"SettingsServiceFactory","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsServiceFactory/getInstanceFor(_:)":{"title":"getInstanceFor(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceFactory\/getInstanceFor(_:)","abstract":[{"text":"Create a new instance of the settings service if it doesn’t exist already, or returns already created instance.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getInstanceFor"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@MBXSettingsServiceStorageType","text":"SettingsServiceStorageType","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"SettingsService","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXSettingsService"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"getInstanceForStorageType:"}],"url":"\/documentation\/mapboxcommon\/settingsservicefactory\/getinstancefor(_:)","type":"topic"},"doc://com.mapbox.MapboxMaps/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SdkInformation":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SdkInformation","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SdkInformation"}],"type":"topic","kind":"symbol","url":"\/documentation\/mapboxcommon\/sdkinformation","navigatorTitle":[{"text":"SdkInformation","kind":"identifier"}],"abstract":[{"type":"text","text":"Provides information about a given Mapbox SDK. This information is then used to populate the “User-Agent” HTTP header"},{"text":" ","type":"text"},{"text":"of HTTP requests generated from within Mapbox SDKs. Mapbox SDKs include Maps, Navigation, Search, and others.","type":"text"}],"title":"SdkInformation","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"role":"collection","url":"\/documentation\/mapboxmaps","title":"MapboxMaps","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsServiceFactory/getInstance(storageType:)":{"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getInstance"},{"kind":"text","text":"("},{"kind":"externalParam","text":"storageType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SettingsServiceStorageType","preciseIdentifier":"c:@E@MBXSettingsServiceStorageType"},{"kind":"text","text":") -> "},{"text":"SettingsService","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXSettingsService"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceFactory\/getInstance(storageType:)","title":"getInstance(storageType:)","url":"\/documentation\/mapboxcommon\/settingsservicefactory\/getinstance(storagetype:)","type":"topic","kind":"symbol","abstract":[]},"doc://com.mapbox.MapboxMaps/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsServiceStorageType":{"url":"\/documentation\/mapboxcommon\/settingsservicestoragetype","kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceStorageType","title":"SettingsServiceStorageType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SettingsServiceStorageType","kind":"identifier"}],"abstract":[{"type":"text","text":"Enum that contains possible storage types that can be used for settings service."}],"navigatorTitle":[{"kind":"identifier","text":"SettingsServiceStorageType"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsService":{"title":"SettingsService","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsService","abstract":[{"text":"Platform independent settings service. Settings service is a key\/value storage (persistent or non","type":"text"},{"type":"text","text":" "},{"text":"persistent), that also allows to register observers to get notifications when values are updated.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SettingsService"}],"kind":"symbol","navigatorTitle":[{"text":"SettingsService","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/settingsservice","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","value":"MBXSettingsServiceFactory","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXSettingsServiceFactory"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBXSettingsServiceFactory"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Type Methods","anchor":"Type-Methods","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceFactory\/getInstanceFor(_:)"],"generated":true}]},{"value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"]}],"path":"\/relationshipsSections","op":"replace"},{"value":[{"title":"Common Settings","anchor":"Common-Settings","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsService","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceStorageType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SdkInformation"],"generated":true}],"op":"replace","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBXSettingsServiceFactory"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceFactory\/title","value":"MBXSettingsServiceFactory"},{"value":[{"text":"MBXSettingsServiceFactory","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceFactory\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceFactory\/navigatorTitle","value":[{"text":"MBXSettingsServiceFactory","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceFactory~1getInstanceFor(_:)\/title","value":"getInstanceForStorageType:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceFactory~1getInstanceFor(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getInstanceForStorageType:"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SdkInformation\/title","value":"MBXSdkInformation","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SdkInformation\/fragments","value":[{"text":"MBXSdkInformation","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SdkInformation\/navigatorTitle","value":[{"text":"MBXSdkInformation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceStorageType\/title","value":"MBXSettingsServiceStorageType"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceStorageType\/fragments","value":[{"text":"MBXSettingsServiceStorageType","kind":"identifier"}],"op":"replace"},{"value":[{"text":"MBXSettingsServiceStorageType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceStorageType\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsService\/title","value":"MBXSettingsService","op":"replace"},{"value":[{"text":"MBXSettingsService","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsService\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MBXSettingsService"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsService\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}