{"metadata":{"title":"CumulativeRenderingStatistics","externalID":"c:objc(cs)MBMCumulativeRenderingStatistics","modules":[{"name":"MapboxMaps"}],"symbolKind":"class","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CumulativeRenderingStatistics","kind":"identifier"}],"navigatorTitle":[{"text":"CumulativeRenderingStatistics","kind":"identifier"}],"role":"symbol"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance"]]},"topicSections":[{"anchor":"Initializers","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CumulativeRenderingStatistics\/init(drawCalls:textureBytes:vertexBytes:graphicsPrograms:graphicsProgramsCreationTimeMillis:)"],"title":"Initializers"}],"seeAlsoSections":[{"generated":true,"anchor":"Performance-recording","title":"Performance recording","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatistics","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/DurationStatistics","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GroupPerformanceStatistics","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerFrameRenderingStatistics","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatisticsOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatisticsCallback"]}],"variants":[{"paths":["\/documentation\/mapboxmaps\/cumulativerenderingstatistics"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/cumulativerenderingstatistics"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"kind":"relationships"},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CumulativeRenderingStatistics","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CumulativeRenderingStatistics","kind":"identifier"}],"platforms":["iOS"]}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CumulativeRenderingStatistics":{"type":"topic","title":"CumulativeRenderingStatistics","navigatorTitle":[{"text":"CumulativeRenderingStatistics","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CumulativeRenderingStatistics","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CumulativeRenderingStatistics","url":"\/documentation\/mapboxmaps\/cumulativerenderingstatistics","kind":"symbol","role":"symbol","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMCumulativeRenderingStatistics/graphicsPrograms":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCumulativeRenderingStatistics\/graphicsPrograms","title":"graphicsPrograms","abstract":[{"type":"text","text":"The number of graphics pipeline programs created."}],"kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/mbmcumulativerenderingstatistics\/graphicsprograms","fragments":[{"kind":"identifier","text":"graphicsPrograms"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PerFrameRenderingStatistics":{"navigatorTitle":[{"kind":"identifier","text":"PerFrameRenderingStatistics"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PerFrameRenderingStatistics"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerFrameRenderingStatistics","url":"\/documentation\/mapboxmaps\/perframerenderingstatistics","title":"PerFrameRenderingStatistics","abstract":[],"type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMCumulativeRenderingStatistics/drawCalls":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCumulativeRenderingStatistics\/drawCalls","title":"drawCalls","abstract":[{"type":"text","text":"The number of draw calls at the end of the collection window."}],"kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/mbmcumulativerenderingstatistics\/drawcalls","fragments":[{"text":"drawCalls","kind":"identifier"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PerformanceStatistics":{"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatistics","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PerformanceStatistics","kind":"identifier"}],"title":"PerformanceStatistics","url":"\/documentation\/mapboxmaps\/performancestatistics","navigatorTitle":[{"text":"PerformanceStatistics","kind":"identifier"}],"abstract":[{"text":"The performance statistics collected at the end of the sampling duration.","type":"text"}]},"doc://com.mapbox.MapboxMaps/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CumulativeRenderingStatistics/init(drawCalls:textureBytes:vertexBytes:graphicsPrograms:graphicsProgramsCreationTimeMillis:)":{"role":"symbol","title":"init(drawCalls:textureBytes:vertexBytes:graphicsPrograms:graphicsProgramsCreationTimeMillis:)","url":"\/documentation\/mapboxmaps\/cumulativerenderingstatistics\/init(drawcalls:texturebytes:vertexbytes:graphicsprograms:graphicsprogramscreationtimemillis:)","kind":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"drawCalls","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?, ","kind":"text"},{"text":"textureBytes","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?, ","kind":"text"},{"text":"vertexBytes","kind":"externalParam"},{"kind":"text","text":": "},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"graphicsPrograms"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"text":"?, ","kind":"text"},{"text":"graphicsProgramsCreationTimeMillis","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CumulativeRenderingStatistics\/init(drawCalls:textureBytes:vertexBytes:graphicsPrograms:graphicsProgramsCreationTimeMillis:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithDrawCalls:textureBytes:vertexBytes:graphicsPrograms:graphicsProgramsCreationTimeMillis:"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"title":"MapboxMaps Documentation","role":"collection","url":"\/documentation\/overview","type":"topic","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PerformanceStatisticsOptions":{"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatisticsOptions","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PerformanceStatisticsOptions","kind":"identifier"}],"title":"PerformanceStatisticsOptions","url":"\/documentation\/mapboxmaps\/performancestatisticsoptions","navigatorTitle":[{"text":"PerformanceStatisticsOptions","kind":"identifier"}],"abstract":[{"type":"text","text":"Options for the following statistics collection behaviors:"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PerformanceStatisticsCallback":{"url":"\/documentation\/mapboxmaps\/performancestatisticscallback","type":"topic","navigatorTitle":[{"text":"PerformanceStatisticsCallback","kind":"identifier"}],"title":"PerformanceStatisticsCallback","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatisticsCallback","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PerformanceStatisticsCallback","kind":"identifier"}],"abstract":[{"text":"Use this callback to observe the collected statistics. The callback is invoked at regular intervals determined by","type":"text"},{"type":"text","text":" "},{"type":"text","text":"the sampling duration specified in the "},{"type":"codeVoice","code":"PerformanceStatisticsOptions"},{"type":"text","text":". The callback is invoked from the main thread."}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMCumulativeRenderingStatistics/vertexBytes":{"role":"symbol","title":"vertexBytes","url":"\/documentation\/mapboxmaps\/mbmcumulativerenderingstatistics\/vertexbytes","kind":"symbol","type":"topic","fragments":[{"text":"vertexBytes","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCumulativeRenderingStatistics\/vertexBytes","abstract":[{"type":"text","text":"The amount of vertex memory (array and index buffer memory) in use at the end of the collection window."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GroupPerformanceStatistics":{"type":"topic","title":"GroupPerformanceStatistics","navigatorTitle":[{"kind":"identifier","text":"GroupPerformanceStatistics"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupPerformanceStatistics"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GroupPerformanceStatistics","url":"\/documentation\/mapboxmaps\/groupperformancestatistics","kind":"symbol","role":"symbol","abstract":[]},"doc://com.mapbox.MapboxMaps/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Performance":{"url":"\/documentation\/mapboxmaps\/performance","title":"Performance and investigations","type":"topic","abstract":[],"kind":"article","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMCumulativeRenderingStatistics/textureBytes":{"role":"symbol","title":"textureBytes","url":"\/documentation\/mapboxmaps\/mbmcumulativerenderingstatistics\/texturebytes","kind":"symbol","type":"topic","fragments":[{"text":"textureBytes","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCumulativeRenderingStatistics\/textureBytes","abstract":[{"type":"text","text":"The amount of texture memory in use at the end of the collection window."}]},"doc://com.mapbox.MapboxMaps/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"title":"MapboxMaps","role":"collection","url":"\/documentation\/mapboxmaps","type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMCumulativeRenderingStatistics/graphicsProgramsCreationTimeMillis":{"role":"symbol","title":"graphicsProgramsCreationTimeMillis","url":"\/documentation\/mapboxmaps\/mbmcumulativerenderingstatistics\/graphicsprogramscreationtimemillis","kind":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"graphicsProgramsCreationTimeMillis"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCumulativeRenderingStatistics\/graphicsProgramsCreationTimeMillis","abstract":[{"text":"The total amount of time spent on all graphics pipeline program creation, in milliseconds.","type":"text"}]},"doc://com.mapbox.MapboxMaps/SQ":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/DurationStatistics":{"title":"DurationStatistics","navigatorTitle":[{"text":"DurationStatistics","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DurationStatistics","kind":"identifier"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/DurationStatistics","url":"\/documentation\/mapboxmaps\/durationstatistics","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MBMCumulativeRenderingStatistics"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MBMCumulativeRenderingStatistics","kind":"identifier"}]},{"value":[{"text":"MBMCumulativeRenderingStatistics","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCumulativeRenderingStatistics\/drawCalls","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCumulativeRenderingStatistics\/graphicsPrograms","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCumulativeRenderingStatistics\/graphicsProgramsCreationTimeMillis","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCumulativeRenderingStatistics\/textureBytes","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMCumulativeRenderingStatistics\/vertexBytes"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"},{"anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CumulativeRenderingStatistics\/init(drawCalls:textureBytes:vertexBytes:graphicsPrograms:graphicsProgramsCreationTimeMillis:)"],"title":"Instance Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"]}],"op":"replace"},{"value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatistics","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/DurationStatistics","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GroupPerformanceStatistics","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerFrameRenderingStatistics","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatisticsOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerformanceStatisticsCallback"],"anchor":"Performance-recording","title":"Performance recording","generated":true}],"path":"\/seeAlsoSections","op":"replace"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBMCumulativeRenderingStatistics","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}]},"path":"\/primaryContentSections\/0"},{"value":"MBMCumulativeRenderingStatistics","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CumulativeRenderingStatistics\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CumulativeRenderingStatistics\/fragments","value":[{"kind":"identifier","text":"MBMCumulativeRenderingStatistics"}],"op":"replace"},{"value":[{"text":"MBMCumulativeRenderingStatistics","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CumulativeRenderingStatistics\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerFrameRenderingStatistics\/title","value":"MBMPerFrameRenderingStatistics"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerFrameRenderingStatistics\/fragments","value":[{"text":"MBMPerFrameRenderingStatistics","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerFrameRenderingStatistics\/navigatorTitle","value":[{"text":"MBMPerFrameRenderingStatistics","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatistics\/title","value":"MBMPerformanceStatistics","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatistics\/fragments","value":[{"text":"MBMPerformanceStatistics","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatistics\/navigatorTitle","value":[{"kind":"identifier","text":"MBMPerformanceStatistics"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CumulativeRenderingStatistics~1init(drawCalls:textureBytes:vertexBytes:graphicsPrograms:graphicsProgramsCreationTimeMillis:)\/title","value":"initWithDrawCalls:textureBytes:vertexBytes:graphicsPrograms:graphicsProgramsCreationTimeMillis:"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CumulativeRenderingStatistics~1init(drawCalls:textureBytes:vertexBytes:graphicsPrograms:graphicsProgramsCreationTimeMillis:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithDrawCalls:textureBytes:vertexBytes:graphicsPrograms:graphicsProgramsCreationTimeMillis:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatisticsOptions\/title","value":"MBMPerformanceStatisticsOptions"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatisticsOptions\/fragments","op":"replace","value":[{"text":"MBMPerformanceStatisticsOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatisticsOptions\/navigatorTitle","value":[{"text":"MBMPerformanceStatisticsOptions","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatisticsCallback\/title","op":"replace","value":"MBMPerformanceStatisticsCallback"},{"value":[{"kind":"identifier","text":"MBMPerformanceStatisticsCallback"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatisticsCallback\/fragments"},{"op":"replace","value":[{"text":"MBMPerformanceStatisticsCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerformanceStatisticsCallback\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GroupPerformanceStatistics\/title","value":"MBMGroupPerformanceStatistics","op":"replace"},{"value":[{"kind":"identifier","text":"MBMGroupPerformanceStatistics"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GroupPerformanceStatistics\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GroupPerformanceStatistics\/navigatorTitle","value":[{"text":"MBMGroupPerformanceStatistics","kind":"identifier"}]},{"value":"MBMDurationStatistics","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1DurationStatistics\/title"},{"value":[{"kind":"identifier","text":"MBMDurationStatistics"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1DurationStatistics\/fragments"},{"op":"replace","value":[{"text":"MBMDurationStatistics","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1DurationStatistics\/navigatorTitle"}]}]}