{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/InteractiveFeature"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InteractiveFeature","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Overview","anchor":"overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The interactive feature is in the interactions  handlers, see more in "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TapInteraction","isActive":true,"type":"reference"},{"text":" and ","type":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LongPressInteraction","type":"reference","isActive":true},{"type":"text","text":"."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The interactive feature is different from "},{"code":"Turf.Feature","type":"codeVoice"},{"type":"text","text":" as it contains more context about the featureset"},{"type":"text","text":" "},{"type":"text","text":"and provides easier access to the feature properties."}]}]}],"seeAlsoSections":[{"title":"Featuresets","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeaturesetDescriptor","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeaturesetFeatureId","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeaturesetQueryTarget"],"anchor":"Featuresets"}],"abstract":[{"type":"text","text":"An interactive feature."}],"topicSections":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/InteractiveFeature\/featureset","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/InteractiveFeature\/geometry","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/InteractiveFeature\/id","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/InteractiveFeature\/properties","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/InteractiveFeature\/state"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/interactivefeature"]}],"sections":[],"kind":"symbol","metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"InteractiveFeature"}],"role":"symbol","tags":[{"type":"spi","text":"SPI"}],"symbolKind":"class","title":"InteractiveFeature","navigatorTitle":[{"text":"InteractiveFeature","kind":"identifier"}],"modules":[{"name":"MapboxMaps"}],"externalID":"s:10MapboxMaps18InteractiveFeatureC","roleHeading":"Class"},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Featuresets-and-Interactions"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/LongPressInteraction":{"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"LongPressInteraction","kind":"identifier"}],"tags":[{"type":"spi","text":"SPI"}],"type":"topic","title":"LongPressInteraction","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"LongPressInteraction"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/LongPressInteraction","url":"\/documentation\/mapboxmaps\/longpressinteraction","abstract":[{"text":"Creates a Long Press interaction.","type":"text"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"title":"MapboxMaps Documentation","role":"collection","url":"\/documentation\/overview","type":"topic","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/InteractiveFeature/properties":{"type":"topic","role":"symbol","url":"\/documentation\/mapboxmaps\/interactivefeature\/properties","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"properties","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:4Turf10JSONObjecta","text":"JSONObject"},{"text":"?","kind":"text"}],"tags":[{"type":"spi","text":"SPI"}],"abstract":[{"type":"text","text":"Feature properties."}],"kind":"symbol","title":"properties","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/InteractiveFeature\/properties"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/InteractiveFeature/featureset":{"url":"\/documentation\/mapboxmaps\/interactivefeature\/featureset","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/InteractiveFeature\/featureset","title":"featureset","type":"topic","tags":[{"text":"SPI","type":"spi"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"featureset"},{"kind":"text","text":": "},{"text":"FeaturesetDescriptor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMFeaturesetDescriptor"}],"abstract":[{"type":"text","text":"A featureset descriptor denoting a featureset this feature belongs to."}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FeaturesetDescriptor":{"navigatorTitle":[{"kind":"identifier","text":"FeaturesetDescriptor"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FeaturesetDescriptor","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeaturesetDescriptor","url":"\/documentation\/mapboxmaps\/featuresetdescriptor","title":"FeaturesetDescriptor","abstract":[{"type":"text","text":"Represents an identifier for a single exported featureset or a layer."}],"type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Featuresets-and-Interactions":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Featuresets-and-Interactions","abstract":[{"type":"text","text":"The experimental Interactions API."}],"title":"Featuresets and Interactions","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/featuresets-and-interactions","kind":"article","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/InteractiveFeature/id":{"title":"id","role":"symbol","tags":[{"type":"spi","text":"SPI"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FeaturesetFeatureId","preciseIdentifier":"s:10MapboxMaps19FeaturesetFeatureIdV","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/InteractiveFeature\/id","abstract":[{"text":"An id of the feature","type":"text"}],"type":"topic","url":"\/documentation\/mapboxmaps\/interactivefeature\/id","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/InteractiveFeature/state":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"state","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:4Turf10JSONObjecta","text":"JSONObject"},{"kind":"text","text":"?"}],"tags":[{"type":"spi","text":"SPI"}],"type":"topic","title":"state","kind":"symbol","abstract":[{"type":"text","text":"Feature state."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/InteractiveFeature\/state","url":"\/documentation\/mapboxmaps\/interactivefeature\/state","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"title":"MapboxMaps","role":"collection","url":"\/documentation\/mapboxmaps","type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/InteractiveFeature":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InteractiveFeature","kind":"identifier"}],"navigatorTitle":[{"text":"InteractiveFeature","kind":"identifier"}],"tags":[{"text":"SPI","type":"spi"}],"title":"InteractiveFeature","abstract":[{"text":"An interactive feature.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/InteractiveFeature","kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/interactivefeature"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TapInteraction":{"abstract":[{"type":"text","text":"A single tap interaction."}],"title":"TapInteraction","role":"symbol","tags":[{"type":"spi","text":"SPI"}],"url":"\/documentation\/mapboxmaps\/tapinteraction","navigatorTitle":[{"text":"TapInteraction","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"TapInteraction","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TapInteraction"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/InteractiveFeature/geometry":{"tags":[{"type":"spi","text":"SPI"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/InteractiveFeature\/geometry","type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"A feature geometry."}],"title":"geometry","url":"\/documentation\/mapboxmaps\/interactivefeature\/geometry","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"geometry","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps8Geometrya","text":"Geometry"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FeaturesetQueryTarget":{"url":"\/documentation\/mapboxmaps\/featuresetquerytarget","role":"symbol","abstract":[{"type":"text","text":"Defines the parameters for querying features from a Featureset with an optional filter and id."}],"tags":[{"type":"spi","text":"SPI"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FeaturesetQueryTarget","kind":"identifier"}],"title":"FeaturesetQueryTarget","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FeaturesetQueryTarget"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeaturesetQueryTarget"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FeaturesetFeatureId":{"tags":[{"type":"spi","text":"SPI"}],"type":"topic","title":"FeaturesetFeatureId","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeaturesetFeatureId","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FeaturesetFeatureId"}],"navigatorTitle":[{"text":"FeaturesetFeatureId","kind":"identifier"}],"abstract":[{"type":"text","text":"Identifies a feature in a featureset."}],"role":"symbol","url":"\/documentation\/mapboxmaps\/featuresetfeatureid"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeaturesetDescriptor\/title","value":"MBMFeaturesetDescriptor"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeaturesetDescriptor\/fragments","op":"replace","value":[{"text":"MBMFeaturesetDescriptor","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeaturesetDescriptor\/navigatorTitle","op":"replace","value":[{"text":"MBMFeaturesetDescriptor","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}