{"metadata":{"symbolKind":"method","navigatorTitle":[{"text":"createTilesetDescriptorForTilesetDescriptorOptions:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createTilesetDescriptor","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMTilesetDescriptorOptions","text":"TilesetDescriptorOptions","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBXTilesetDescriptor","text":"TilesetDescriptor","kind":"typeIdentifier"}],"title":"createTilesetDescriptor(for:)","externalID":"c:objc(cs)MBMOfflineManager(im)createTilesetDescriptorForTilesetDescriptorOptions:","modules":[{"name":"MapboxMaps"}],"role":"symbol","roleHeading":"Instance Method"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createTilesetDescriptor"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"tilesetDescriptorOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TilesetDescriptorOptions","preciseIdentifier":"c:objc(cs)MBMTilesetDescriptorOptions","text":"TilesetDescriptorOptions"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TilesetDescriptor","preciseIdentifier":"c:objc(cs)MBXTilesetDescriptor","text":"TilesetDescriptor"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"tilesetDescriptorOptions","content":[{"inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"tileset descriptor options"},{"type":"text","text":" to manage."}],"type":"paragraph"}]}]},{"content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"inlineContent":[{"type":"text","text":"A new "},{"type":"codeVoice","code":"tileset descriptor"},{"type":"text","text":"."}],"type":"paragraph"}],"kind":"content"},{"content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Tileset descriptors are used by the "},{"type":"codeVoice","code":"tile store"},{"type":"text","text":" to create new offline regions."},{"type":"text","text":" "},{"type":"text","text":"Resolving the created tileset descriptor includes loading and parsing the style and might include"},{"type":"text","text":" "},{"type":"text","text":"creation or update of a style package - depending on the given options."}]}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Construct a new "},{"type":"codeVoice","code":"tileset descriptor"},{"type":"text","text":" for the "},{"type":"codeVoice","code":"tile store"},{"type":"text","text":"."}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineManager\/createTilesetDescriptor(for:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/mapboxmaps\/offlinemanager\/createtilesetdescriptor(for:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/offlinemanager\/createtilesetdescriptor(for:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineManager"]]},"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TilesetDescriptor":{"url":"\/documentation\/mapboxcommon\/tilesetdescriptor","abstract":[{"text":"A bundle that encapsulates tilesets creation for the tile store implementation.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TilesetDescriptor","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TilesetDescriptor","kind":"identifier"}],"title":"TilesetDescriptor","navigatorTitle":[{"text":"TilesetDescriptor","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","type":"topic","abstract":[],"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Offline":{"url":"\/documentation\/mapboxmaps\/offline","type":"topic","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","title":"Offline Support","kind":"article","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","title":"MapboxMaps","url":"\/documentation\/mapboxmaps","kind":"symbol","type":"topic","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TilesetDescriptorOptions":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TilesetDescriptorOptions","abstract":[{"type":"text","text":"Describes the tileset descriptor option values."}],"navigatorTitle":[{"text":"TilesetDescriptorOptions","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TilesetDescriptorOptions","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapboxmaps\/tilesetdescriptoroptions","type":"topic","title":"TilesetDescriptorOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineManager/createTilesetDescriptor(for:)":{"url":"\/documentation\/mapboxmaps\/offlinemanager\/createtilesetdescriptor(for:)","title":"createTilesetDescriptor(for:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createTilesetDescriptor","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TilesetDescriptorOptions","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMTilesetDescriptorOptions"},{"text":") -> ","kind":"text"},{"text":"TilesetDescriptor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXTilesetDescriptor"}],"navigatorTitle":[{"text":"createTilesetDescriptorForTilesetDescriptorOptions:","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineManager\/createTilesetDescriptor(for:)","type":"topic","abstract":[{"text":"Construct a new ","type":"text"},{"code":"tileset descriptor","type":"codeVoice"},{"text":" for the ","type":"text"},{"code":"tile store","type":"codeVoice"},{"text":".","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineManager":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineManager","abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"offline manager"},{"text":" manages downloads and storage for style packages and also produces tileset descriptors for the ","type":"text"},{"code":"tile store","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/offlinemanager","kind":"symbol","title":"OfflineManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OfflineManager","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"OfflineManager"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMaps":{"type":"topic","kind":"article","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","title":"Core Maps API","url":"\/documentation\/mapboxmaps\/coremaps","abstract":[{"type":"text","text":"Maps rendering SDK also known as GL-Native"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"createTilesetDescriptorForTilesetDescriptorOptions:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"createTilesetDescriptorForTilesetDescriptorOptions:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:objc(cs)MBXTilesetDescriptor","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TilesetDescriptor","text":"MBXTilesetDescriptor"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createTilesetDescriptorForTilesetDescriptorOptions:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)MBMTilesetDescriptorOptions","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TilesetDescriptorOptions","text":"MBMTilesetDescriptorOptions"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"tilesetDescriptorOptions"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"tileset descriptor options"},{"type":"text","text":" to manage."}],"type":"paragraph"}],"name":"tilesetDescriptorOptions"}],"kind":"parameters"},"op":"replace"},{"path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"inlineContent":[{"text":"A new ","type":"text"},{"code":"tileset descriptor","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TilesetDescriptor\/title","value":"MBXTilesetDescriptor","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TilesetDescriptor\/fragments","value":[{"text":"MBXTilesetDescriptor","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TilesetDescriptor\/navigatorTitle","value":[{"text":"MBXTilesetDescriptor","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions\/title","value":"MBMTilesetDescriptorOptions","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions\/fragments","value":[{"text":"MBMTilesetDescriptorOptions","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TilesetDescriptorOptions\/navigatorTitle","value":[{"text":"MBMTilesetDescriptorOptions","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineManager~1createTilesetDescriptor(for:)\/title","value":"createTilesetDescriptorForTilesetDescriptorOptions:","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineManager~1createTilesetDescriptor(for:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"createTilesetDescriptorForTilesetDescriptorOptions:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineManager\/title","value":"MBMOfflineManager","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineManager\/fragments","value":[{"text":"MBMOfflineManager","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineManager\/navigatorTitle","value":[{"kind":"identifier","text":"MBMOfflineManager"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}