{"abstract":[{"text":"Calculate a point on the map in Mercator Projection for a given","type":"text"},{"type":"text","text":" "},{"text":"coordinate at the specified zoom scale.","type":"text"}],"sections":[],"metadata":{"role":"symbol","modules":[{"name":"MapboxMaps"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"project"},{"text":"(","kind":"text"},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":", "},{"text":"zoomScale","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)MBMMercatorCoordinate","text":"MercatorCoordinate","kind":"typeIdentifier"}],"roleHeading":"Type Method","externalID":"s:10MapboxMaps10ProjectionC7project_9zoomScaleSo21MBMMercatorCoordinateCSo22CLLocationCoordinate2DV_14CoreFoundation7CGFloatVtFZ","title":"project(_:zoomScale:)","symbolKind":"method"},"kind":"symbol","identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Projection\/project(_:zoomScale:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/mapboxmaps\/projection\/project(_:zoomscale:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Projection"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"project","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"coordinate","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","kind":"typeIdentifier","text":"CLLocationCoordinate2D"},{"text":", ","kind":"text"},{"text":"zoomScale","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)MBMMercatorCoordinate","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MercatorCoordinate","text":"MercatorCoordinate"}]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The coordinate for which to return the value.","type":"text"}]}],"name":"coordinate"},{"name":"zoomScale","content":[{"inlineContent":[{"text":"The current zoom factor applied on the map, is used to","type":"text"},{"type":"text","text":" "},{"text":"calculate the world size as tileSize * zoomScale (i.e.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"512 * 2 ^ Zoom level) where tileSize is the width of a tile"},{"type":"text","text":" "},{"type":"text","text":"in points."}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","anchor":"return-value","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"text":"Mercator coordinate","type":"text"}]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"aside","name":"Note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Coordinate latitudes will be clamped to"},{"type":"text","text":" "},{"type":"text","text":"[Projection.latitudeMin, Projection.latitudeMax]"}]}],"style":"note"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"https://en.wikipedia.org/wiki/Web_Mercator_projection":{"identifier":"https:\/\/en.wikipedia.org\/wiki\/Web_Mercator_projection","type":"link","titleInlineContent":[{"type":"text","text":"Spherical Mercator"}],"url":"https:\/\/en.wikipedia.org\/wiki\/Web_Mercator_projection","title":"Spherical Mercator"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","kind":"article","role":"collectionGroup","type":"topic","title":"MapboxMap","url":"\/documentation\/mapboxmaps\/mapboxmap-apis","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","role":"collection","title":"MapboxMaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Projection":{"url":"\/documentation\/mapboxmaps\/projection","navigatorTitle":[{"kind":"identifier","text":"Projection"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Projection","abstract":[{"text":"A collection of ","type":"text"},{"type":"reference","identifier":"https:\/\/en.wikipedia.org\/wiki\/Web_Mercator_projection","isActive":true},{"text":" projection methods.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Projection","kind":"identifier"}],"title":"Projection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MercatorCoordinate":{"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MercatorCoordinate","kind":"identifier"}],"navigatorTitle":[{"text":"MercatorCoordinate","kind":"identifier"}],"abstract":[{"text":"Describes a point on the map in Mercator projection.","type":"text"}],"title":"MercatorCoordinate","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MercatorCoordinate","role":"symbol","url":"\/documentation\/mapboxmaps\/mercatorcoordinate"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Projection/project(_:zoomScale:)":{"title":"project(_:zoomScale:)","abstract":[{"type":"text","text":"Calculate a point on the map in Mercator Projection for a given"},{"type":"text","text":" "},{"type":"text","text":"coordinate at the specified zoom scale."}],"url":"\/documentation\/mapboxmaps\/projection\/project(_:zoomscale:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"project","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"zoomScale"},{"kind":"text","text":": "},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MercatorCoordinate","preciseIdentifier":"c:objc(cs)MBMMercatorCoordinate"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Projection\/project(_:zoomScale:)"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","kind":"article","type":"topic","url":"\/documentation\/overview","title":"MapboxMaps Documentation","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MercatorCoordinate\/title","op":"replace","value":"MBMMercatorCoordinate"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MercatorCoordinate\/fragments","op":"replace","value":[{"text":"MBMMercatorCoordinate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MercatorCoordinate\/navigatorTitle","value":[{"text":"MBMMercatorCoordinate","kind":"identifier"}]}]}]}