{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Projection"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unproject","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"mercatorCoordinate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MercatorCoordinate","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MercatorCoordinate","preciseIdentifier":"c:objc(cs)MBMMercatorCoordinate"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"zoomScale"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":") -> "},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"mercatorCoordinate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Point on the map in Mercator projection."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The current zoom factor applied on the map, is used to","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"calculate the world size as tileSize * zoomScale (i.e."},{"text":" ","type":"text"},{"text":"512 * 2 ^ Zoom level) where tileSize is the width of a tile in","type":"text"},{"text":" ","type":"text"},{"text":"points.","type":"text"}]}],"name":"zoomScale"}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"Unprojected coordinate","type":"text"}]}]}],"metadata":{"roleHeading":"Type Method","role":"symbol","modules":[{"name":"MapboxMaps"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unproject"},{"kind":"text","text":"("},{"text":"MercatorCoordinate","preciseIdentifier":"c:objc(cs)MBMMercatorCoordinate","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"zoomScale"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"text":") -> ","kind":"text"},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"}],"title":"unproject(_:zoomScale:)","symbolKind":"method","externalID":"s:10MapboxMaps10ProjectionC9unproject_9zoomScaleSo22CLLocationCoordinate2DVSo21MBMMercatorCoordinateC_14CoreFoundation7CGFloatVtFZ"},"abstract":[{"type":"text","text":"Calculate a coordinate for a given point on the map in Mercator Projection."}],"variants":[{"paths":["\/documentation\/mapboxmaps\/projection\/unproject(_:zoomscale:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Projection\/unproject(_:zoomScale:)"},"sections":[],"references":{"https://en.wikipedia.org/wiki/Web_Mercator_projection":{"url":"https:\/\/en.wikipedia.org\/wiki\/Web_Mercator_projection","titleInlineContent":[{"text":"Spherical Mercator","type":"text"}],"identifier":"https:\/\/en.wikipedia.org\/wiki\/Web_Mercator_projection","title":"Spherical Mercator","type":"link"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Projection/unproject(_:zoomScale:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Projection\/unproject(_:zoomScale:)","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unproject"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMMercatorCoordinate","text":"MercatorCoordinate","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"zoomScale"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","kind":"typeIdentifier","text":"CLLocationCoordinate2D"}],"role":"symbol","abstract":[{"type":"text","text":"Calculate a coordinate for a given point on the map in Mercator Projection."}],"title":"unproject(_:zoomScale:)","url":"\/documentation\/mapboxmaps\/projection\/unproject(_:zoomscale:)","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"title":"MapboxMaps","role":"collection","url":"\/documentation\/mapboxmaps","kind":"symbol","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","title":"MapboxMaps Documentation","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","url":"\/documentation\/overview","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MercatorCoordinate":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MercatorCoordinate","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/mercatorcoordinate","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MercatorCoordinate","role":"symbol","navigatorTitle":[{"text":"MercatorCoordinate","kind":"identifier"}],"abstract":[{"text":"Describes a point on the map in Mercator projection.","type":"text"}],"type":"topic","title":"MercatorCoordinate"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Projection":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Projection","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Projection"}],"url":"\/documentation\/mapboxmaps\/projection","abstract":[{"text":"A collection of ","type":"text"},{"type":"reference","identifier":"https:\/\/en.wikipedia.org\/wiki\/Web_Mercator_projection","isActive":true},{"text":" projection methods.","type":"text"}],"type":"topic","title":"Projection","role":"symbol","navigatorTitle":[{"text":"Projection","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"type":"topic","kind":"article","title":"MapboxMap","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","url":"\/documentation\/mapboxmaps\/mapboxmap-apis"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MBMMercatorCoordinate","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MercatorCoordinate\/title"},{"value":[{"text":"MBMMercatorCoordinate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MercatorCoordinate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MercatorCoordinate\/navigatorTitle","value":[{"text":"MBMMercatorCoordinate","kind":"identifier"}]}]}]}