{"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/OfflineSwitch\/isMapboxStackConnected()"},"metadata":{"externalID":"c:objc(cs)MBXOfflineSwitch(im)isMapboxStackConnected","symbolKind":"method","modules":[{"name":"MapboxCommon"}],"roleHeading":"Instance Method","title":"isMapboxStackConnected()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isMapboxStackConnected"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"role":"symbol","navigatorTitle":[{"text":"isMapboxStackConnected","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/OfflineSwitch"]]},"abstract":[{"type":"text","text":"Provides information if the Mapbox stack is connected or disconnected via OfflineSwitch."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isMapboxStackConnected","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"True if the Mapbox stack is disconnected via setMapboxStackConnected(), false otherwise.","type":"text"}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/offlineswitch\/ismapboxstackconnected()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/offlineswitch\/ismapboxstackconnected()"]}],"kind":"symbol","sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","abstract":[],"url":"\/documentation\/overview","role":"collection","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"title":"MapboxCommon","type":"topic","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","kind":"symbol","url":"\/documentation\/mapboxcommon","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/OfflineSwitch/isMapboxStackConnected()":{"title":"isMapboxStackConnected()","navigatorTitle":[{"kind":"identifier","text":"isMapboxStackConnected"}],"kind":"symbol","abstract":[{"text":"Provides information if the Mapbox stack is connected or disconnected via OfflineSwitch.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/OfflineSwitch\/isMapboxStackConnected()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isMapboxStackConnected","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/mapboxcommon\/offlineswitch\/ismapboxstackconnected()","type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/OfflineSwitch":{"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/OfflineSwitch","navigatorTitle":[{"kind":"identifier","text":"OfflineSwitch"}],"abstract":[{"text":"Instance that allows connecting or disconnecting the Mapbox stack to the network.","type":"text"}],"kind":"symbol","title":"OfflineSwitch","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OfflineSwitch"}],"url":"\/documentation\/mapboxcommon\/offlineswitch"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"isMapboxStackConnected","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isMapboxStackConnected"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"identifier","text":"isMapboxStackConnected"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"content","content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"inlineContent":[{"text":"True if the Mapbox stack is disconnected via setMapboxStackConnected(), false otherwise.","type":"text"}],"type":"paragraph"}]}},{"value":"isMapboxStackConnected","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1OfflineSwitch~1isMapboxStackConnected()\/title"},{"value":[{"kind":"text","text":"- "},{"text":"isMapboxStackConnected","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1OfflineSwitch~1isMapboxStackConnected()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1OfflineSwitch\/title","value":"MBXOfflineSwitch"},{"value":[{"text":"MBXOfflineSwitch","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1OfflineSwitch\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MBXOfflineSwitch"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1OfflineSwitch\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}