{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-View","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ConstrainMode"]]},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ConstrainMode\/init(rawValue:)","interfaceLanguage":"swift"},"metadata":{"title":"init(rawValue:)","modules":[{"name":"MapboxMaps"}],"role":"symbol","roleHeading":"Initializer","externalID":"s:So16MBMConstrainModeV8rawValueABSgSi_tcfc","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/mapboxmaps\/constrainmode\/init(rawvalue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ConstrainMode/init(rawValue:)":{"kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}],"abstract":[],"url":"\/documentation\/mapboxmaps\/constrainmode\/init(rawvalue:)","title":"init(rawValue:)","type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ConstrainMode\/init(rawValue:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"type":"topic","role":"collection","kind":"symbol","title":"MapboxMaps","url":"\/documentation\/mapboxmaps"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"type":"topic","role":"collection","kind":"article","title":"MapboxMaps Documentation","url":"\/documentation\/overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map-View":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-View","abstract":[],"url":"\/documentation\/mapboxmaps\/map-view","type":"topic","title":"MapView","role":"collectionGroup","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ConstrainMode":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ConstrainMode","abstract":[{"text":"Describes whether to constrain the map in both axes or only vertically e.g. while panning.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ConstrainMode","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ConstrainMode"}],"url":"\/documentation\/mapboxmaps\/constrainmode","type":"topic","title":"ConstrainMode","role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ConstrainMode\/title","value":"MBMConstrainMode","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ConstrainMode\/fragments","value":[{"text":"MBMConstrainMode","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"MBMConstrainMode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1ConstrainMode\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}