{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/perframerenderingstatistics\/toprenderlayers"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/perframerenderingstatistics\/toprenderlayers"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerFrameRenderingStatistics\/topRenderLayers"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","metadata":{"symbolKind":"property","title":"topRenderLayers","role":"symbol","navigatorTitle":[{"text":"topRenderLayers","kind":"identifier"}],"roleHeading":"Instance Property","externalID":"c:objc(cs)MBMPerFrameRenderingStatistics(py)topRenderLayers","modules":[{"name":"MapboxMaps"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topRenderLayers","kind":"identifier"},{"text":": [","kind":"text"},{"text":"GroupPerformanceStatistics","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMGroupPerformanceStatistics"},{"text":"]","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerFrameRenderingStatistics"]]},"abstract":[{"type":"text","text":"The CPU timeline duration statistics of each layer, in descending order by duration."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"topRenderLayers"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)MBMGroupPerformanceStatistics","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GroupPerformanceStatistics","text":"GroupPerformanceStatistics"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PerFrameRenderingStatistics/topRenderLayers":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerFrameRenderingStatistics\/topRenderLayers","title":"topRenderLayers","kind":"symbol","url":"\/documentation\/mapboxmaps\/perframerenderingstatistics\/toprenderlayers","role":"symbol","navigatorTitle":[{"text":"topRenderLayers","kind":"identifier"}],"abstract":[{"text":"The CPU timeline duration statistics of each layer, in descending order by duration.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topRenderLayers","kind":"identifier"},{"text":": [","kind":"text"},{"text":"GroupPerformanceStatistics","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMGroupPerformanceStatistics"},{"text":"]","kind":"text"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"role":"collection","abstract":[],"url":"\/documentation\/overview","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","title":"MapboxMaps Documentation","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PerFrameRenderingStatistics":{"type":"topic","title":"PerFrameRenderingStatistics","url":"\/documentation\/mapboxmaps\/perframerenderingstatistics","kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PerFrameRenderingStatistics"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PerFrameRenderingStatistics"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PerFrameRenderingStatistics"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GroupPerformanceStatistics":{"type":"topic","title":"GroupPerformanceStatistics","url":"\/documentation\/mapboxmaps\/groupperformancestatistics","kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GroupPerformanceStatistics"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupPerformanceStatistics"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GroupPerformanceStatistics"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"url":"\/documentation\/mapboxmaps","role":"collection","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Performance":{"title":"Performance and investigations","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","role":"collectionGroup","kind":"article","abstract":[],"url":"\/documentation\/mapboxmaps\/performance"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"topRenderLayers","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"topRenderLayers"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<MBMGroupPerformanceStatistics *>","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"topRenderLayers","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerFrameRenderingStatistics~1topRenderLayers\/title","op":"replace","value":"topRenderLayers"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerFrameRenderingStatistics~1topRenderLayers\/fragments","op":"replace","value":[{"kind":"identifier","text":"topRenderLayers"}]},{"value":"MBMPerFrameRenderingStatistics","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerFrameRenderingStatistics\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MBMPerFrameRenderingStatistics"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerFrameRenderingStatistics\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MBMPerFrameRenderingStatistics"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1PerFrameRenderingStatistics\/navigatorTitle","op":"replace"},{"value":"MBMGroupPerformanceStatistics","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GroupPerformanceStatistics\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MBMGroupPerformanceStatistics"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GroupPerformanceStatistics\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MBMGroupPerformanceStatistics"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GroupPerformanceStatistics\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}