{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"anchor":"Classes","generated":true,"title":"Classes","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/DataRef","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Feature","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeofencingFactory","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestFlags","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestOrResponse","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpResponse","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpResponseData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceFactory","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MapboxSupport","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/OfflineSwitch","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SdkInformationQuery","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/ValueConverter"]},{"anchor":"Protocols","generated":true,"title":"Protocols","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeofencingObserver","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeofencingService","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceInterceptorInterface"]},{"anchor":"Structures","generated":true,"title":"Structures","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeofenceState","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeofencingError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeofencingEvent","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeofencingOptions"]},{"anchor":"Variables","generated":true,"title":"Variables","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType_Empty","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType_GeometryCollection","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType_Line","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType_MultiLine","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType_MultiPoint","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType_MultiPolygon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType_Point","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType_Polygon"]},{"anchor":"Functions","generated":true,"title":"Functions","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXAccuracyAuthorizationToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXCacheClearingErrorTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXHttpMethodToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXHttpRequestErrorTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXLocationErrorCodeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXLoggingLevelToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXPermissionStatusToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXTileDataDomainToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXTileRegionErrorTypeToString(_:)"]},{"anchor":"Type-Aliases","generated":true,"title":"Type Aliases","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GetLocationCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpResponseCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceCancellationCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceInterceptorRequestContinuation","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceInterceptorResponseContinuation"]},{"anchor":"Enumerations","generated":true,"title":"Enumerations","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeofencingErrorType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeofencingPropertiesKeys","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpMethod","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestOrResponseType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NetworkRestriction","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon"]}],"sections":[],"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/Turf"]}],"kind":"symbol","metadata":{"modules":[{"name":"MapboxCommon"}],"symbolKind":"module","role":"collection","title":"MapboxCommon","roleHeading":"Framework","externalID":"MapboxCommon"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestFlags":{"type":"topic","url":"\/documentation\/mapboxcommon\/httprequestflags","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestFlags","navigatorTitle":[{"text":"HttpRequestFlags","kind":"identifier"}],"title":"HttpRequestFlags","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HttpRequestFlags","kind":"identifier"}],"kind":"symbol","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/swift_int2":{"url":"\/documentation\/mapboxcommon\/swift_int2","type":"topic","abstract":[],"fragments":[{"text":"swift_int2","kind":"identifier"}],"role":"symbol","title":"swift_int2","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/swift_int2","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/GeometryType_Point":{"kind":"symbol","url":"\/documentation\/mapboxcommon\/geometrytype_point","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType_Point","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GeometryType_Point","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GeometryType","preciseIdentifier":"c:@EA@MBXGeometryType"}],"navigatorTitle":[{"kind":"identifier","text":"MBXGeometryType_Point"}],"type":"topic","role":"symbol","title":"GeometryType_Point","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpResponse":{"abstract":[{"text":"Record which is used to report HTTP response to the caller.","type":"text"}],"url":"\/documentation\/mapboxcommon\/httpresponse","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HttpResponse","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpResponse","navigatorTitle":[{"text":"HttpResponse","kind":"identifier"}],"type":"topic","title":"HttpResponse","role":"symbol","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXAccuracyAuthorizationToString(_:)":{"navigatorTitle":[{"kind":"identifier","text":"MBXAccuracyAuthorizationToString"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXAccuracyAuthorizationToString(_:)","title":"MBXAccuracyAuthorizationToString(_:)","role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBXAccuracyAuthorizationToString"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AccuracyAuthorization","preciseIdentifier":"c:@E@MBXAccuracyAuthorization"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"url":"\/documentation\/mapboxcommon\/mbxaccuracyauthorizationtostring(_:)","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/GeometryType_Empty":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType_Empty","url":"\/documentation\/mapboxcommon\/geometrytype_empty","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GeometryType_Empty"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@EA@MBXGeometryType","kind":"typeIdentifier","text":"GeometryType"}],"type":"topic","title":"GeometryType_Empty","navigatorTitle":[{"kind":"identifier","text":"MBXGeometryType_Empty"}],"kind":"symbol","abstract":[],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/GeometryType_MultiPoint":{"url":"\/documentation\/mapboxcommon\/geometrytype_multipoint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MBXGeometryType_MultiPoint"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GeometryType_MultiPoint"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@EA@MBXGeometryType","kind":"typeIdentifier","text":"GeometryType"}],"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType_MultiPoint","title":"GeometryType_MultiPoint"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/swift_uint3":{"title":"swift_uint3","fragments":[{"text":"swift_uint3","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/swift_uint3","abstract":[],"role":"symbol","url":"\/documentation\/mapboxcommon\/swift_uint3","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpServiceFactory":{"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HttpServiceFactory","kind":"identifier"}],"type":"topic","title":"HttpServiceFactory","abstract":[{"type":"text","text":"HTTP service factory."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceFactory","url":"\/documentation\/mapboxcommon\/httpservicefactory","navigatorTitle":[{"text":"HttpServiceFactory","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SWIFT_CLASS_EXTRA":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_CLASS_EXTRA","abstract":[],"fragments":[{"kind":"identifier","text":"SWIFT_CLASS_EXTRA"}],"url":"\/documentation\/mapboxcommon\/swift_class_extra","title":"SWIFT_CLASS_EXTRA","role":"symbol","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/GetLocationCallback":{"abstract":[{"type":"text","text":"Callback involved to get the location."}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GetLocationCallback","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GetLocationCallback"}],"url":"\/documentation\/mapboxcommon\/getlocationcallback","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"GetLocationCallback"}],"role":"symbol","title":"GetLocationCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/GeofencingService":{"url":"\/documentation\/mapboxcommon\/geofencingservice","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GeofencingService","kind":"identifier"}],"kind":"symbol","tags":[{"text":"SPI","type":"spi"}],"abstract":[],"navigatorTitle":[{"text":"GeofencingService","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeofencingService","type":"topic","title":"GeofencingService","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","url":"\/documentation\/overview","role":"collection","abstract":[],"kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/swift_float4":{"type":"topic","title":"swift_float4","abstract":[],"url":"\/documentation\/mapboxcommon\/swift_float4","fragments":[{"text":"swift_float4","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/swift_float4","kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Geometry":{"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Geometry","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/geometry","abstract":[],"type":"topic","navigatorTitle":[{"text":"Geometry","kind":"identifier"}],"title":"Geometry","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SWIFT_ENUM_EXTRA":{"title":"SWIFT_ENUM_EXTRA","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_ENUM_EXTRA","abstract":[],"url":"\/documentation\/mapboxcommon\/swift_enum_extra","role":"symbol","kind":"symbol","fragments":[{"kind":"identifier","text":"SWIFT_ENUM_EXTRA"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXCacheClearingErrorTypeToString(_:)":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXCacheClearingErrorTypeToString(_:)","navigatorTitle":[{"text":"MBXCacheClearingErrorTypeToString","kind":"identifier"}],"abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBXCacheClearingErrorTypeToString","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@MBXCacheClearingErrorType","text":"CacheClearingErrorType","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"url":"\/documentation\/mapboxcommon\/mbxcacheclearingerrortypetostring(_:)","title":"MBXCacheClearingErrorTypeToString(_:)","role":"symbol","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SWIFT_RESILIENT_CLASS":{"url":"\/documentation\/mapboxcommon\/swift_resilient_class","kind":"symbol","title":"SWIFT_RESILIENT_CLASS","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_RESILIENT_CLASS","type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"SWIFT_RESILIENT_CLASS"}],"abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/swift_double2":{"role":"symbol","type":"topic","title":"swift_double2","url":"\/documentation\/mapboxcommon\/swift_double2","abstract":[],"fragments":[{"kind":"identifier","text":"swift_double2"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/swift_double2","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SWIFT_RELEASES_ARGUMENT":{"fragments":[{"kind":"identifier","text":"SWIFT_RELEASES_ARGUMENT"}],"title":"SWIFT_RELEASES_ARGUMENT","url":"\/documentation\/mapboxcommon\/swift_releases_argument","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_RELEASES_ARGUMENT","kind":"symbol","role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SWIFT_DEPRECATED_OBJC":{"role":"symbol","title":"SWIFT_DEPRECATED_OBJC","type":"topic","url":"\/documentation\/mapboxcommon\/swift_deprecated_objc","abstract":[],"fragments":[{"text":"SWIFT_DEPRECATED_OBJC","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_DEPRECATED_OBJC","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/GeometryType_GeometryCollection":{"navigatorTitle":[{"text":"MBXGeometryType_GeometryCollection","kind":"identifier"}],"role":"symbol","type":"topic","title":"GeometryType_GeometryCollection","url":"\/documentation\/mapboxcommon\/geometrytype_geometrycollection","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GeometryType_GeometryCollection","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GeometryType","kind":"typeIdentifier","preciseIdentifier":"c:@EA@MBXGeometryType"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType_GeometryCollection","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"type":"topic","url":"\/documentation\/mapboxmaps","role":"collection","kind":"symbol","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/GeofencingEvent":{"kind":"symbol","url":"\/documentation\/mapboxcommon\/geofencingevent","abstract":[],"title":"GeofencingEvent","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeofencingEvent","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GeofencingEvent","kind":"identifier"}],"tags":[{"text":"SPI","type":"spi"}],"navigatorTitle":[{"text":"GeofencingEvent","kind":"identifier"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpResponseCallback":{"title":"HttpResponseCallback","kind":"symbol","role":"symbol","abstract":[{"text":"Callback which is used to report result of HTTP request.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpResponseCallback","url":"\/documentation\/mapboxcommon\/httpresponsecallback","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HttpResponseCallback","kind":"identifier"}],"navigatorTitle":[{"text":"HttpResponseCallback","kind":"identifier"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/GeofencingErrorType":{"navigatorTitle":[{"text":"GeofencingErrorType","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeofencingErrorType","abstract":[],"tags":[{"text":"SPI","type":"spi"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GeofencingErrorType","kind":"identifier"}],"title":"GeofencingErrorType","kind":"symbol","url":"\/documentation\/mapboxcommon\/geofencingerrortype"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SWIFT_INDIRECT_RESULT":{"kind":"symbol","fragments":[{"text":"SWIFT_INDIRECT_RESULT","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/swift_indirect_result","role":"symbol","abstract":[],"title":"SWIFT_INDIRECT_RESULT","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_INDIRECT_RESULT","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SWIFT_CALL":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_CALL","fragments":[{"text":"SWIFT_CALL","kind":"identifier"}],"abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/mapboxcommon\/swift_call","role":"symbol","title":"SWIFT_CALL"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SWIFT_RESILIENT_CLASS_NAMED":{"role":"symbol","type":"topic","title":"SWIFT_RESILIENT_CLASS_NAMED","url":"\/documentation\/mapboxcommon\/swift_resilient_class_named","abstract":[],"fragments":[{"text":"SWIFT_RESILIENT_CLASS_NAMED","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_RESILIENT_CLASS_NAMED","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SWIFT_PROTOCOL_EXTRA":{"role":"symbol","title":"SWIFT_PROTOCOL_EXTRA","type":"topic","url":"\/documentation\/mapboxcommon\/swift_protocol_extra","abstract":[],"fragments":[{"text":"SWIFT_PROTOCOL_EXTRA","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_PROTOCOL_EXTRA","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SWIFT_NOEXCEPT":{"role":"symbol","abstract":[],"fragments":[{"text":"SWIFT_NOEXCEPT","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_NOEXCEPT","url":"\/documentation\/mapboxcommon\/swift_noexcept","title":"SWIFT_NOEXCEPT"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SWIFT_NORETURN":{"url":"\/documentation\/mapboxcommon\/swift_noreturn","title":"SWIFT_NORETURN","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_NORETURN","abstract":[],"fragments":[{"text":"SWIFT_NORETURN","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestOrResponseType":{"type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestOrResponseType","title":"HttpRequestOrResponseType","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HttpRequestOrResponseType"}],"url":"\/documentation\/mapboxcommon\/httprequestorresponsetype","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HttpRequestOrResponseType"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/GeofencingError":{"url":"\/documentation\/mapboxcommon\/geofencingerror","title":"GeofencingError","abstract":[],"role":"symbol","tags":[{"text":"SPI","type":"spi"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeofencingError","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GeofencingError","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"GeofencingError","kind":"identifier"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/GeofencingObserver":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GeofencingObserver","kind":"identifier"}],"tags":[{"text":"SPI","type":"spi"}],"title":"GeofencingObserver","navigatorTitle":[{"text":"GeofencingObserver","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/geofencingobserver","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeofencingObserver","kind":"symbol","type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/GeofenceState":{"kind":"symbol","title":"GeofenceState","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GeofenceState","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/geofencestate","tags":[{"type":"spi","text":"SPI"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeofenceState","navigatorTitle":[{"text":"GeofenceState","kind":"identifier"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SWIFT_DEPRECATED_MSG":{"role":"symbol","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_DEPRECATED_MSG","url":"\/documentation\/mapboxcommon\/swift_deprecated_msg","fragments":[{"kind":"identifier","text":"SWIFT_DEPRECATED_MSG"}],"title":"SWIFT_DEPRECATED_MSG"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/OBJC_DESIGNATED_INITIALIZER":{"fragments":[{"kind":"identifier","text":"OBJC_DESIGNATED_INITIALIZER"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/OBJC_DESIGNATED_INITIALIZER","abstract":[],"kind":"symbol","title":"OBJC_DESIGNATED_INITIALIZER","url":"\/documentation\/mapboxcommon\/objc_designated_initializer","type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestError":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HttpRequestError","kind":"identifier"}],"abstract":[{"text":"Record which contains detailed information about HTTP error happened during request\/download call.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestError","role":"symbol","title":"HttpRequestError","url":"\/documentation\/mapboxcommon\/httprequesterror","kind":"symbol","navigatorTitle":[{"text":"HttpRequestError","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestOrResponse":{"kind":"symbol","url":"\/documentation\/mapboxcommon\/httprequestorresponse","abstract":[{"text":"Contains either an HttpRequest or an HttpResponse.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HttpRequestOrResponse","kind":"identifier"}],"title":"HttpRequestOrResponse","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestOrResponse","navigatorTitle":[{"text":"HttpRequestOrResponse","kind":"identifier"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SWIFT_ERROR_RESULT":{"kind":"symbol","title":"SWIFT_ERROR_RESULT","role":"symbol","abstract":[],"fragments":[{"kind":"identifier","text":"SWIFT_ERROR_RESULT"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_ERROR_RESULT","url":"\/documentation\/mapboxcommon\/swift_error_result","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/swift_double3":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/swift_double3","title":"swift_double3","role":"symbol","fragments":[{"text":"swift_double3","kind":"identifier"}],"kind":"symbol","abstract":[],"type":"topic","url":"\/documentation\/mapboxcommon\/swift_double3"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/swift_uint4":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/swift_uint4","abstract":[],"title":"swift_uint4","type":"topic","fragments":[{"text":"swift_uint4","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/swift_uint4","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXHttpRequestErrorTypeToString(_:)":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"MBXHttpRequestErrorTypeToString"}],"type":"topic","role":"symbol","kind":"symbol","title":"MBXHttpRequestErrorTypeToString(_:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXHttpRequestErrorTypeToString(_:)","url":"\/documentation\/mapboxcommon\/mbxhttprequesterrortypetostring(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBXHttpRequestErrorTypeToString","kind":"identifier"},{"text":"(","kind":"text"},{"text":"HttpRequestErrorType","preciseIdentifier":"c:@E@MBXHttpRequestErrorType","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/DataRef":{"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DataRef"}],"title":"DataRef","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/DataRef","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DataRef"}],"type":"topic","url":"\/documentation\/mapboxcommon\/dataref"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SWIFT_CLASS_PROPERTY":{"kind":"symbol","url":"\/documentation\/mapboxcommon\/swift_class_property","type":"topic","title":"SWIFT_CLASS_PROPERTY","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_CLASS_PROPERTY","abstract":[],"role":"symbol","fragments":[{"kind":"identifier","text":"SWIFT_CLASS_PROPERTY"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/GeometryType_MultiPolygon":{"navigatorTitle":[{"kind":"identifier","text":"MBXGeometryType_MultiPolygon"}],"kind":"symbol","url":"\/documentation\/mapboxcommon\/geometrytype_multipolygon","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GeometryType_MultiPolygon"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@EA@MBXGeometryType","kind":"typeIdentifier","text":"GeometryType"}],"title":"GeometryType_MultiPolygon","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType_MultiPolygon","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/OfflineSwitch":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/OfflineSwitch","title":"OfflineSwitch","kind":"symbol","url":"\/documentation\/mapboxcommon\/offlineswitch","abstract":[{"text":"Instance that allows connecting or disconnecting the Mapbox stack to the network.","type":"text"}],"navigatorTitle":[{"text":"OfflineSwitch","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OfflineSwitch","kind":"identifier"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXPermissionStatusToString(_:)":{"url":"\/documentation\/mapboxcommon\/mbxpermissionstatustostring(_:)","type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXPermissionStatusToString(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBXPermissionStatusToString"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@MBXPermissionStatus","kind":"typeIdentifier","text":"PermissionStatus"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"!"}],"title":"MBXPermissionStatusToString(_:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBXPermissionStatusToString"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXLocationErrorCodeToString(_:)":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXLocationErrorCodeToString(_:)","url":"\/documentation\/mapboxcommon\/mbxlocationerrorcodetostring(_:)","navigatorTitle":[{"kind":"identifier","text":"MBXLocationErrorCodeToString"}],"abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBXLocationErrorCodeToString"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBXLocationErrorCode","text":"LocationErrorCode"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"!"}],"title":"MBXLocationErrorCodeToString(_:)","role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Turf":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Turf","title":"Turf","abstract":[],"role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/turf"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/GeometryType_Line":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GeometryType_Line"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@EA@MBXGeometryType","text":"GeometryType"}],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType_Line","type":"topic","url":"\/documentation\/mapboxcommon\/geometrytype_line","abstract":[],"kind":"symbol","title":"GeometryType_Line","navigatorTitle":[{"kind":"identifier","text":"MBXGeometryType_Line"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpServiceInterceptorRequestContinuation":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceInterceptorRequestContinuation","abstract":[{"text":"Continuation to be invoked once the interceptor is done processing a request. If invoked with a HttpRequest, the","type":"text"},{"text":" ","type":"text"},{"text":"HTTP service will proceed to make a request via the network. Invoking the continuation with a HttpResponse bypasses","type":"text"},{"text":" ","type":"text"},{"text":"the network and causes the request to complete immediately with the specified response. The ID of the HttpResponse","type":"text"},{"text":" ","type":"text"},{"text":"is irrelevant in this case.","type":"text"}],"title":"HttpServiceInterceptorRequestContinuation","type":"topic","role":"symbol","url":"\/documentation\/mapboxcommon\/httpserviceinterceptorrequestcontinuation","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HttpServiceInterceptorRequestContinuation","kind":"identifier"}],"navigatorTitle":[{"text":"HttpServiceInterceptorRequestContinuation","kind":"identifier"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/GeofencingPropertiesKeys":{"type":"topic","url":"\/documentation\/mapboxcommon\/geofencingpropertieskeys","kind":"symbol","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GeofencingPropertiesKeys","kind":"identifier"}],"tags":[{"text":"SPI","type":"spi"}],"role":"symbol","navigatorTitle":[{"text":"GeofencingPropertiesKeys","kind":"identifier"}],"title":"GeofencingPropertiesKeys","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeofencingPropertiesKeys"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/swift_double4":{"fragments":[{"kind":"identifier","text":"swift_double4"}],"title":"swift_double4","abstract":[],"url":"\/documentation\/mapboxcommon\/swift_double4","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/swift_double4","kind":"symbol","type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/PersistentLogConfiguration":{"abstract":[{"type":"text","text":"Settings to configure behavior of persistent log"}],"title":"PersistentLogConfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PersistentLogConfiguration"}],"url":"\/documentation\/mapboxcommon\/persistentlogconfiguration","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration","navigatorTitle":[{"kind":"identifier","text":"PersistentLogConfiguration"}],"type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpServiceInterceptorInterface":{"url":"\/documentation\/mapboxcommon\/httpserviceinterceptorinterface","abstract":[{"type":"text","text":"Interface for intercepting and modifying HttpService function calls."}],"role":"symbol","title":"HttpServiceInterceptorInterface","type":"topic","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HttpServiceInterceptorInterface","kind":"identifier"}],"navigatorTitle":[{"text":"HttpServiceInterceptorInterface","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceInterceptorInterface"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SWIFT_TYPEDEFS":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_TYPEDEFS","title":"SWIFT_TYPEDEFS","fragments":[{"text":"SWIFT_TYPEDEFS","kind":"identifier"}],"abstract":[],"url":"\/documentation\/mapboxcommon\/swift_typedefs","kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/GeofencingOptions":{"abstract":[],"tags":[{"type":"spi","text":"SPI"}],"url":"\/documentation\/mapboxcommon\/geofencingoptions","kind":"symbol","title":"GeofencingOptions","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeofencingOptions","navigatorTitle":[{"kind":"identifier","text":"GeofencingOptions"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"GeofencingOptions"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SWIFT_C_INLINE_THUNK":{"title":"SWIFT_C_INLINE_THUNK","abstract":[],"fragments":[{"kind":"identifier","text":"SWIFT_C_INLINE_THUNK"}],"kind":"symbol","url":"\/documentation\/mapboxcommon\/swift_c_inline_thunk","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_C_INLINE_THUNK","type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequest":{"url":"\/documentation\/mapboxcommon\/httprequest","abstract":[{"text":"HttpRequest holds basic information for construction of an HTTP request","type":"text"}],"role":"symbol","title":"HttpRequest","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HttpRequest","kind":"identifier"}],"navigatorTitle":[{"text":"HttpRequest","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SWIFT_PROTOCOL":{"kind":"symbol","url":"\/documentation\/mapboxcommon\/swift_protocol","type":"topic","role":"symbol","fragments":[{"text":"SWIFT_PROTOCOL","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_PROTOCOL","abstract":[],"title":"SWIFT_PROTOCOL"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SWIFT_AVAILABILITY":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_AVAILABILITY","fragments":[{"kind":"identifier","text":"SWIFT_AVAILABILITY"}],"role":"symbol","type":"topic","title":"SWIFT_AVAILABILITY","abstract":[],"kind":"symbol","url":"\/documentation\/mapboxcommon\/swift_availability"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/ValueConverter":{"abstract":[],"kind":"symbol","title":"ValueConverter","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/ValueConverter","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ValueConverter","kind":"identifier"}],"navigatorTitle":[{"text":"ValueConverter","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/valueconverter","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SWIFT_METATYPE":{"abstract":[],"url":"\/documentation\/mapboxcommon\/swift_metatype","fragments":[{"text":"SWIFT_METATYPE","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_METATYPE","title":"SWIFT_METATYPE","kind":"symbol","type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionError":{"title":"TileRegionError","abstract":[{"text":"Describes a tile region load request error.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileRegionError","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"TileRegionError","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionError","url":"\/documentation\/mapboxcommon\/tileregionerror","kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SWIFT_CLASS_NAMED":{"kind":"symbol","url":"\/documentation\/mapboxcommon\/swift_class_named","type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"SWIFT_CLASS_NAMED"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_CLASS_NAMED","abstract":[],"title":"SWIFT_CLASS_NAMED"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/IBSegueAction":{"url":"\/documentation\/mapboxcommon\/ibsegueaction","title":"IBSegueAction","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/IBSegueAction","type":"topic","fragments":[{"kind":"identifier","text":"IBSegueAction"}],"abstract":[],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestErrorType":{"title":"HttpRequestErrorType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HttpRequestErrorType","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/httprequesterrortype","abstract":[{"type":"text","text":"Enum which describes possible error types which could happen during HTTP request\/download calls."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType","role":"symbol","navigatorTitle":[{"text":"HttpRequestErrorType","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Feature":{"navigatorTitle":[{"kind":"identifier","text":"Feature"}],"role":"symbol","title":"Feature","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Feature","url":"\/documentation\/mapboxcommon\/feature","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Feature"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/GeofencingFactory":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GeofencingFactory"}],"title":"GeofencingFactory","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GeofencingFactory"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeofencingFactory","role":"symbol","abstract":[],"tags":[{"text":"SPI","type":"spi"}],"url":"\/documentation\/mapboxcommon\/geofencingfactory","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SWIFT_COMPILE_NAME":{"title":"SWIFT_COMPILE_NAME","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_COMPILE_NAME","abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"SWIFT_COMPILE_NAME","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/swift_compile_name","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SWIFT_UNAVAILABLE_MSG":{"fragments":[{"text":"SWIFT_UNAVAILABLE_MSG","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_UNAVAILABLE_MSG","abstract":[],"role":"symbol","kind":"symbol","title":"SWIFT_UNAVAILABLE_MSG","type":"topic","url":"\/documentation\/mapboxcommon\/swift_unavailable_msg"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SWIFT_WEAK_IMPORT":{"fragments":[{"text":"SWIFT_WEAK_IMPORT","kind":"identifier"}],"title":"SWIFT_WEAK_IMPORT","abstract":[],"url":"\/documentation\/mapboxcommon\/swift_weak_import","role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_WEAK_IMPORT","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/GeometryType_MultiLine":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"MBXGeometryType_MultiLine"}],"type":"topic","role":"symbol","kind":"symbol","title":"GeometryType_MultiLine","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType_MultiLine","url":"\/documentation\/mapboxcommon\/geometrytype_multiline","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GeometryType_MultiLine"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@EA@MBXGeometryType","text":"GeometryType"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpMethod":{"navigatorTitle":[{"kind":"identifier","text":"HttpMethod"}],"type":"topic","role":"symbol","abstract":[{"text":"HTTP defines a set of request methods to indicate the desired action to be performed for a given resource.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpMethod","kind":"symbol","title":"HttpMethod","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HttpMethod"}],"url":"\/documentation\/mapboxcommon\/httpmethod"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SWIFT_IMPORT_STDLIB_SYMBOL":{"fragments":[{"kind":"identifier","text":"SWIFT_IMPORT_STDLIB_SYMBOL"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_IMPORT_STDLIB_SYMBOL","url":"\/documentation\/mapboxcommon\/swift_import_stdlib_symbol","title":"SWIFT_IMPORT_STDLIB_SYMBOL","kind":"symbol","abstract":[],"role":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/swift_float3":{"abstract":[],"type":"topic","role":"symbol","kind":"symbol","title":"swift_float3","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/swift_float3","url":"\/documentation\/mapboxcommon\/swift_float3","fragments":[{"text":"swift_float3","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpServiceInterceptorResponseContinuation":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceInterceptorResponseContinuation","role":"symbol","navigatorTitle":[{"text":"HttpServiceInterceptorResponseContinuation","kind":"identifier"}],"type":"topic","title":"HttpServiceInterceptorResponseContinuation","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HttpServiceInterceptorResponseContinuation","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/httpserviceinterceptorresponsecontinuation","abstract":[{"text":"Continuation to be invoked once the interceptor is done processing a request’s response.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SWIFT_PASTE_HELPER":{"abstract":[],"type":"topic","role":"symbol","kind":"symbol","title":"SWIFT_PASTE_HELPER","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_PASTE_HELPER","url":"\/documentation\/mapboxcommon\/swift_paste_helper","fragments":[{"kind":"identifier","text":"SWIFT_PASTE_HELPER"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SWIFT_WARN_UNUSED_RESULT":{"url":"\/documentation\/mapboxcommon\/swift_warn_unused_result","kind":"symbol","title":"SWIFT_WARN_UNUSED_RESULT","abstract":[],"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_WARN_UNUSED_RESULT","type":"topic","fragments":[{"text":"SWIFT_WARN_UNUSED_RESULT","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SWIFT_NOESCAPE":{"fragments":[{"text":"SWIFT_NOESCAPE","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_NOESCAPE","kind":"symbol","title":"SWIFT_NOESCAPE","url":"\/documentation\/mapboxcommon\/swift_noescape","type":"topic","abstract":[],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SWIFT_EXTENSION":{"url":"\/documentation\/mapboxcommon\/swift_extension","kind":"symbol","abstract":[],"role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_EXTENSION","title":"SWIFT_EXTENSION","fragments":[{"kind":"identifier","text":"SWIFT_EXTENSION"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SWIFT_DEPRECATED":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_DEPRECATED","type":"topic","role":"symbol","url":"\/documentation\/mapboxcommon\/swift_deprecated","title":"SWIFT_DEPRECATED","abstract":[],"fragments":[{"kind":"identifier","text":"SWIFT_DEPRECATED"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXTileRegionErrorTypeToString(_:)":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXTileRegionErrorTypeToString(_:)","abstract":[],"title":"MBXTileRegionErrorTypeToString(_:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBXTileRegionErrorTypeToString"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@MBXTileRegionErrorType","kind":"typeIdentifier","text":"TileRegionErrorType"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"!"}],"navigatorTitle":[{"kind":"identifier","text":"MBXTileRegionErrorTypeToString"}],"url":"\/documentation\/mapboxcommon\/mbxtileregionerrortypetostring(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXTileDataDomainToString(_:)":{"title":"MBXTileDataDomainToString(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBXTileDataDomainToString","kind":"identifier"},{"text":"(","kind":"text"},{"text":"TileDataDomain","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBXTileDataDomain"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}],"navigatorTitle":[{"text":"MBXTileDataDomainToString","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/mbxtiledatadomaintostring(_:)","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXTileDataDomainToString(_:)","abstract":[],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/swift_int4":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/swift_int4","title":"swift_int4","role":"symbol","fragments":[{"kind":"identifier","text":"swift_int4"}],"type":"topic","abstract":[],"url":"\/documentation\/mapboxcommon\/swift_int4","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SWIFT_ENUM_ATTR":{"fragments":[{"kind":"identifier","text":"SWIFT_ENUM_ATTR"}],"role":"symbol","type":"topic","title":"SWIFT_ENUM_ATTR","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_ENUM_ATTR","url":"\/documentation\/mapboxcommon\/swift_enum_attr","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SWIFT_PASTE":{"fragments":[{"text":"SWIFT_PASTE","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[],"title":"SWIFT_PASTE","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_PASTE","url":"\/documentation\/mapboxcommon\/swift_paste","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SWIFT_RUNTIME_NAME":{"abstract":[],"title":"SWIFT_RUNTIME_NAME","role":"symbol","fragments":[{"text":"SWIFT_RUNTIME_NAME","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_RUNTIME_NAME","url":"\/documentation\/mapboxcommon\/swift_runtime_name","kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MapboxSupport":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapboxSupport"}],"navigatorTitle":[{"kind":"identifier","text":"MapboxSupport"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MapboxSupport","kind":"symbol","type":"topic","url":"\/documentation\/mapboxcommon\/mapboxsupport","tags":[{"type":"spi","text":"SPI"}],"abstract":[],"role":"symbol","title":"MapboxSupport"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/swift_int3":{"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/swift_int3","role":"symbol","fragments":[{"text":"swift_int3","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/mapboxcommon\/swift_int3","title":"swift_int3"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/swift_float2":{"url":"\/documentation\/mapboxcommon\/swift_float2","role":"symbol","title":"swift_float2","fragments":[{"text":"swift_float2","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/swift_float2","kind":"symbol","type":"topic","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SWIFT_UNAVAILABLE":{"fragments":[{"text":"SWIFT_UNAVAILABLE","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_UNAVAILABLE","type":"topic","url":"\/documentation\/mapboxcommon\/swift_unavailable","title":"SWIFT_UNAVAILABLE","abstract":[],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SdkInformationQuery":{"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SdkInformationQuery","kind":"identifier"}],"navigatorTitle":[{"text":"SdkInformationQuery","kind":"identifier"}],"abstract":[{"text":"Provides an interface to query registered Mapbox SDKs. Mapbox SDKs include Maps, Navigation, Search, and others.","type":"text"}],"title":"SdkInformationQuery","type":"topic","url":"\/documentation\/mapboxcommon\/sdkinformationquery","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SdkInformationQuery"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXLoggingLevelToString(_:)":{"title":"MBXLoggingLevelToString(_:)","kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MBXLoggingLevelToString"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXLoggingLevelToString(_:)","url":"\/documentation\/mapboxcommon\/mbxloggingleveltostring(_:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBXLoggingLevelToString","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBXLoggingLevel","text":"LoggingLevel"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"!"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXHttpMethodToString(_:)":{"kind":"symbol","role":"symbol","url":"\/documentation\/mapboxcommon\/mbxhttpmethodtostring(_:)","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXHttpMethodToString(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBXHttpMethodToString"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"HttpMethod","preciseIdentifier":"c:@E@MBXHttpMethod"},{"kind":"text","text":") -> "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"title":"MBXHttpMethodToString(_:)","navigatorTitle":[{"text":"MBXHttpMethodToString","kind":"identifier"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SWIFT_METHOD_FAMILY":{"type":"topic","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_METHOD_FAMILY","url":"\/documentation\/mapboxcommon\/swift_method_family","kind":"symbol","title":"SWIFT_METHOD_FAMILY","role":"symbol","fragments":[{"kind":"identifier","text":"SWIFT_METHOD_FAMILY"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpServiceCancellationCallback":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"HttpServiceCancellationCallback"}],"navigatorTitle":[{"kind":"identifier","text":"HttpServiceCancellationCallback"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceCancellationCallback","title":"HttpServiceCancellationCallback","url":"\/documentation\/mapboxcommon\/httpservicecancellationcallback","role":"symbol","abstract":[{"type":"text","text":"Callback for the HTTP request cancelled event."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionErrorType":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType","abstract":[{"type":"text","text":"Describes the reason for a tile region download request failure."}],"title":"TileRegionErrorType","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileRegionErrorType","kind":"identifier"}],"navigatorTitle":[{"text":"TileRegionErrorType","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/tileregionerrortype"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpResponseData":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpResponseData","title":"HttpResponseData","navigatorTitle":[{"kind":"identifier","text":"HttpResponseData"}],"role":"symbol","abstract":[{"type":"text","text":"Record which contains data received in HTTP response."}],"url":"\/documentation\/mapboxcommon\/httpresponsedata","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HttpResponseData"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"title":"MapboxCommon","role":"collection","url":"\/documentation\/mapboxcommon","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","abstract":[],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SWIFT_PROTOCOL_NAMED":{"url":"\/documentation\/mapboxcommon\/swift_protocol_named","title":"SWIFT_PROTOCOL_NAMED","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_PROTOCOL_NAMED","fragments":[{"text":"SWIFT_PROTOCOL_NAMED","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/GeometryType_Polygon":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType_Polygon","role":"symbol","url":"\/documentation\/mapboxcommon\/geometrytype_polygon","navigatorTitle":[{"kind":"identifier","text":"MBXGeometryType_Polygon"}],"type":"topic","abstract":[],"title":"GeometryType_Polygon","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GeometryType_Polygon"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@EA@MBXGeometryType","kind":"typeIdentifier","text":"GeometryType"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/swift_uint2":{"kind":"symbol","fragments":[{"text":"swift_uint2","kind":"identifier"}],"title":"swift_uint2","abstract":[],"url":"\/documentation\/mapboxcommon\/swift_uint2","type":"topic","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/swift_uint2"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SWIFT_CONTEXT":{"kind":"symbol","role":"symbol","url":"\/documentation\/mapboxcommon\/swift_context","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_CONTEXT","fragments":[{"kind":"identifier","text":"SWIFT_CONTEXT"}],"title":"SWIFT_CONTEXT","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SWIFT_EXTERN":{"title":"SWIFT_EXTERN","role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/mapboxcommon\/swift_extern","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_EXTERN","abstract":[],"fragments":[{"kind":"identifier","text":"SWIFT_EXTERN"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/NetworkRestriction":{"kind":"symbol","url":"\/documentation\/mapboxcommon\/networkrestriction","abstract":[{"text":"Classify network types based on cost.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NetworkRestriction","role":"symbol","navigatorTitle":[{"text":"NetworkRestriction","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NetworkRestriction","kind":"identifier"}],"title":"NetworkRestriction"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SWIFT_CLASS":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_CLASS","url":"\/documentation\/mapboxcommon\/swift_class","type":"topic","fragments":[{"text":"SWIFT_CLASS","kind":"identifier"}],"title":"SWIFT_CLASS","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SWIFT_ENUM":{"kind":"symbol","role":"symbol","url":"\/documentation\/mapboxcommon\/swift_enum","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_ENUM","fragments":[{"text":"SWIFT_ENUM","kind":"identifier"}],"title":"SWIFT_ENUM","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/DataRef","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Feature","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestFlags","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestOrResponse","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpResponse","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpResponseData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceFactory","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/OfflineSwitch","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/PersistentLogConfiguration","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SdkInformationQuery","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/ValueConverter"],"anchor":"Classes","title":"Classes","generated":true},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceInterceptorInterface"],"anchor":"Protocols","title":"Protocols","generated":true},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXAccuracyAuthorizationToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXCacheClearingErrorTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXHttpMethodToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXHttpRequestErrorTypeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXLocationErrorCodeToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXLoggingLevelToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXPermissionStatusToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXTileDataDomainToString(_:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXTileRegionErrorTypeToString(_:)"],"anchor":"Functions","title":"Functions","generated":true},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/IBSegueAction","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/OBJC_DESIGNATED_INITIALIZER","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_AVAILABILITY","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_CALL","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_CLASS","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_CLASS_EXTRA","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_CLASS_NAMED","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_CLASS_PROPERTY","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_COMPILE_NAME","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_CONTEXT","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_C_INLINE_THUNK","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_DEPRECATED","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_DEPRECATED_MSG","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_DEPRECATED_OBJC","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_ENUM","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_ENUM_ATTR","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_ENUM_EXTRA","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_ERROR_RESULT","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_EXTENSION","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_EXTERN","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_IMPORT_STDLIB_SYMBOL","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_INDIRECT_RESULT","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_METATYPE","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_METHOD_FAMILY","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_NOESCAPE","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_NOEXCEPT","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_NORETURN","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_PASTE","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_PASTE_HELPER","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_PROTOCOL","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_PROTOCOL_EXTRA","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_PROTOCOL_NAMED","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_RELEASES_ARGUMENT","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_RESILIENT_CLASS","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_RESILIENT_CLASS_NAMED","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_RUNTIME_NAME","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_TYPEDEFS","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_UNAVAILABLE","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_UNAVAILABLE_MSG","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_WARN_UNUSED_RESULT","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SWIFT_WEAK_IMPORT"],"anchor":"Macros","title":"Macros","generated":true},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GetLocationCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpResponseCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceCancellationCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceInterceptorRequestContinuation","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceInterceptorResponseContinuation","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/swift_double2","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/swift_double3","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/swift_double4","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/swift_float2","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/swift_float3","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/swift_float4","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/swift_int2","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/swift_int3","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/swift_int4","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/swift_uint2","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/swift_uint3","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/swift_uint4"],"anchor":"Type-Aliases","title":"Type Aliases","generated":true},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpMethod","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestOrResponseType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/NetworkRestriction","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType"],"anchor":"Enumerations","title":"Enumerations","generated":true}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps"],"generated":true}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestFlags\/title","value":"MBXHttpRequestFlags"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestFlags\/fragments","value":[{"kind":"identifier","text":"MBXHttpRequestFlags"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestFlags\/navigatorTitle","value":[{"text":"MBXHttpRequestFlags","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType_Point\/title","value":"MBXGeometryType_Point"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType_Point\/fragments","value":[{"text":"MBXGeometryType_Point","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpResponse\/title","value":"MBXHttpResponse"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpResponse\/fragments","value":[{"text":"MBXHttpResponse","kind":"identifier"}]},{"value":[{"text":"MBXHttpResponse","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpResponse\/navigatorTitle"},{"value":"MBXAccuracyAuthorizationToString","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MBXAccuracyAuthorizationToString(_:)\/title"},{"value":[{"text":"MBXAccuracyAuthorizationToString","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MBXAccuracyAuthorizationToString(_:)\/fragments"},{"value":"MBXGeometryType_Empty","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType_Empty\/title"},{"value":[{"text":"MBXGeometryType_Empty","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType_Empty\/fragments"},{"value":"MBXGeometryType_MultiPoint","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType_MultiPoint\/title"},{"value":[{"text":"MBXGeometryType_MultiPoint","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType_MultiPoint\/fragments"},{"value":"MBXHttpServiceFactory","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceFactory\/title"},{"value":[{"text":"MBXHttpServiceFactory","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceFactory\/fragments"},{"value":[{"kind":"identifier","text":"MBXHttpServiceFactory"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceFactory\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GetLocationCallback\/title","value":"MBXGetLocationCallback","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GetLocationCallback\/fragments","value":[{"kind":"identifier","text":"MBXGetLocationCallback"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GetLocationCallback\/navigatorTitle","value":[{"kind":"identifier","text":"MBXGetLocationCallback"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry\/title","value":"MBXGeometry","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry\/fragments","value":[{"kind":"identifier","text":"MBXGeometry"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry\/navigatorTitle","value":[{"kind":"identifier","text":"MBXGeometry"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MBXCacheClearingErrorTypeToString(_:)\/title","value":"MBXCacheClearingErrorTypeToString","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MBXCacheClearingErrorTypeToString(_:)\/fragments","value":[{"kind":"identifier","text":"MBXCacheClearingErrorTypeToString"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType_GeometryCollection\/title","value":"MBXGeometryType_GeometryCollection","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType_GeometryCollection\/fragments","value":[{"kind":"identifier","text":"MBXGeometryType_GeometryCollection"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpResponseCallback\/title","value":"MBXHttpResponseCallback","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpResponseCallback\/fragments","value":[{"kind":"identifier","text":"MBXHttpResponseCallback"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpResponseCallback\/navigatorTitle","value":[{"text":"MBXHttpResponseCallback","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestOrResponseType\/title","value":"MBXHttpRequestOrResponseType","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestOrResponseType\/fragments","value":[{"kind":"identifier","text":"MBXHttpRequestOrResponseType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestOrResponseType\/navigatorTitle","value":[{"kind":"identifier","text":"MBXHttpRequestOrResponseType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestError\/title","value":"MBXHttpRequestError","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestError\/fragments","value":[{"kind":"identifier","text":"MBXHttpRequestError"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestError\/navigatorTitle","value":[{"kind":"identifier","text":"MBXHttpRequestError"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestOrResponse\/title","value":"MBXHttpRequestOrResponse","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestOrResponse\/fragments","value":[{"kind":"identifier","text":"MBXHttpRequestOrResponse"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestOrResponse\/navigatorTitle","value":[{"kind":"identifier","text":"MBXHttpRequestOrResponse"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MBXHttpRequestErrorTypeToString(_:)\/title","value":"MBXHttpRequestErrorTypeToString","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MBXHttpRequestErrorTypeToString(_:)\/fragments","value":[{"kind":"identifier","text":"MBXHttpRequestErrorTypeToString"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1DataRef\/title","value":"MBXDataRef","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1DataRef\/fragments","value":[{"text":"MBXDataRef","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1DataRef\/navigatorTitle","value":[{"kind":"identifier","text":"MBXDataRef"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType_MultiPolygon\/title","value":"MBXGeometryType_MultiPolygon","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType_MultiPolygon\/fragments","value":[{"kind":"identifier","text":"MBXGeometryType_MultiPolygon"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1OfflineSwitch\/title","value":"MBXOfflineSwitch","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1OfflineSwitch\/fragments","value":[{"kind":"identifier","text":"MBXOfflineSwitch"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1OfflineSwitch\/navigatorTitle","value":[{"text":"MBXOfflineSwitch","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MBXPermissionStatusToString(_:)\/title","value":"MBXPermissionStatusToString","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MBXPermissionStatusToString(_:)\/fragments","value":[{"kind":"identifier","text":"MBXPermissionStatusToString"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MBXLocationErrorCodeToString(_:)\/title","value":"MBXLocationErrorCodeToString","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MBXLocationErrorCodeToString(_:)\/fragments","value":[{"text":"MBXLocationErrorCodeToString","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType_Line\/title","value":"MBXGeometryType_Line","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType_Line\/fragments","value":[{"text":"MBXGeometryType_Line","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceInterceptorRequestContinuation\/title","value":"MBXHttpServiceInterceptorRequestContinuation","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceInterceptorRequestContinuation\/fragments","value":[{"text":"MBXHttpServiceInterceptorRequestContinuation","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceInterceptorRequestContinuation\/navigatorTitle","value":[{"text":"MBXHttpServiceInterceptorRequestContinuation","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration\/title","value":"MBXExperimentalPersistentLogConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration\/fragments","value":[{"kind":"identifier","text":"MBXExperimentalPersistentLogConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1PersistentLogConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"MBXExperimentalPersistentLogConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceInterceptorInterface\/title","value":"MBXHttpServiceInterceptorInterface","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceInterceptorInterface\/fragments","value":[{"text":"MBXHttpServiceInterceptorInterface","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceInterceptorInterface\/navigatorTitle","value":[{"text":"MBXHttpServiceInterceptorInterface","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest\/title","value":"MBXHttpRequest","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest\/fragments","value":[{"text":"MBXHttpRequest","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest\/navigatorTitle","value":[{"text":"MBXHttpRequest","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1ValueConverter\/title","value":"MBXValueConverter","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1ValueConverter\/fragments","value":[{"kind":"identifier","text":"MBXValueConverter"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1ValueConverter\/navigatorTitle","value":[{"text":"MBXValueConverter","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionError\/title","value":"MBXTileRegionError","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionError\/fragments","value":[{"kind":"identifier","text":"MBXTileRegionError"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionError\/navigatorTitle","value":[{"kind":"identifier","text":"MBXTileRegionError"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestErrorType\/title","value":"MBXHttpRequestErrorType","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestErrorType\/fragments","value":[{"kind":"identifier","text":"MBXHttpRequestErrorType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestErrorType\/navigatorTitle","value":[{"text":"MBXHttpRequestErrorType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Feature\/title","value":"MBXFeature","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Feature\/fragments","value":[{"text":"MBXFeature","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Feature\/navigatorTitle","value":[{"text":"MBXFeature","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType_MultiLine\/title","value":"MBXGeometryType_MultiLine","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType_MultiLine\/fragments","value":[{"text":"MBXGeometryType_MultiLine","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpMethod\/title","value":"MBXHttpMethod","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpMethod\/fragments","value":[{"kind":"identifier","text":"MBXHttpMethod"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpMethod\/navigatorTitle","value":[{"text":"MBXHttpMethod","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceInterceptorResponseContinuation\/title","value":"MBXHttpServiceInterceptorResponseContinuation","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceInterceptorResponseContinuation\/fragments","value":[{"text":"MBXHttpServiceInterceptorResponseContinuation","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceInterceptorResponseContinuation\/navigatorTitle","value":[{"kind":"identifier","text":"MBXHttpServiceInterceptorResponseContinuation"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MBXTileRegionErrorTypeToString(_:)\/title","value":"MBXTileRegionErrorTypeToString","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MBXTileRegionErrorTypeToString(_:)\/fragments","value":[{"text":"MBXTileRegionErrorTypeToString","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MBXTileDataDomainToString(_:)\/title","value":"MBXTileDataDomainToString","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MBXTileDataDomainToString(_:)\/fragments","value":[{"text":"MBXTileDataDomainToString","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SdkInformationQuery\/title","value":"MBXSdkInformationQuery","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SdkInformationQuery\/fragments","value":[{"kind":"identifier","text":"MBXSdkInformationQuery"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SdkInformationQuery\/navigatorTitle","value":[{"kind":"identifier","text":"MBXSdkInformationQuery"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MBXLoggingLevelToString(_:)\/title","value":"MBXLoggingLevelToString","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MBXLoggingLevelToString(_:)\/fragments","value":[{"text":"MBXLoggingLevelToString","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MBXHttpMethodToString(_:)\/title","value":"MBXHttpMethodToString","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MBXHttpMethodToString(_:)\/fragments","value":[{"kind":"identifier","text":"MBXHttpMethodToString"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceCancellationCallback\/title","value":"MBXHttpServiceCancellationCallback","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceCancellationCallback\/fragments","value":[{"text":"MBXHttpServiceCancellationCallback","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceCancellationCallback\/navigatorTitle","value":[{"kind":"identifier","text":"MBXHttpServiceCancellationCallback"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionErrorType\/title","value":"MBXTileRegionErrorType","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionErrorType\/fragments","value":[{"text":"MBXTileRegionErrorType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionErrorType\/navigatorTitle","value":[{"text":"MBXTileRegionErrorType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpResponseData\/title","value":"MBXHttpResponseData","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpResponseData\/fragments","value":[{"kind":"identifier","text":"MBXHttpResponseData"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpResponseData\/navigatorTitle","value":[{"text":"MBXHttpResponseData","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType_Polygon\/title","value":"MBXGeometryType_Polygon","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType_Polygon\/fragments","value":[{"text":"MBXGeometryType_Polygon","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1NetworkRestriction\/title","value":"MBXNetworkRestriction","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1NetworkRestriction\/fragments","value":[{"kind":"identifier","text":"MBXNetworkRestriction"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1NetworkRestriction\/navigatorTitle","value":[{"kind":"identifier","text":"MBXNetworkRestriction"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}