{"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXTileRegionLoadOptions\/averageBytesPerSecond","interfaceLanguage":"occ"},"metadata":{"externalID":"c:objc(cs)MBXTileRegionLoadOptions(py)averageBytesPerSecond","fragments":[{"text":"averageBytesPerSecond","kind":"identifier"}],"navigatorTitle":[{"text":"averageBytesPerSecond","kind":"identifier"}],"title":"averageBytesPerSecond","role":"symbol","modules":[{"name":"MapboxCommon"}],"symbolKind":"property","roleHeading":"Instance Property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":" * ","kind":"text"},{"text":"averageBytesPerSecond","kind":"identifier"},{"text":";","kind":"text"}]}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Note that this is not a strict bandwidth limit, but only limits the average download speed. tile regions may"},{"type":"text","text":" "},{"type":"text","text":"be temporarily downloaded with higher speed, then pause downloading until the rolling average has dropped below"},{"type":"text","text":" "},{"type":"text","text":"this value."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"If unspecified, the download speed will not be restricted."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Note that this functionality is not currently implemented."}]}]}],"abstract":[{"type":"text","text":"Limits the download speed of the tile region."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/mapboxcommon\/mbxtileregionloadoptions\/averagebytespersecond"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"title":"TileStore APIs","url":"\/documentation\/mapboxmaps\/tilestore-apis","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","abstract":[],"kind":"article","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"type":"topic","role":"collection","url":"\/documentation\/overview","title":"MapboxMaps Documentation","kind":"article","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadOptions":{"kind":"symbol","abstract":[{"text":"Describes the tile region load option values.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadOptions","type":"topic","title":"TileRegionLoadOptions","url":"\/documentation\/mapboxcommon\/tileregionloadoptions","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileRegionLoadOptions","kind":"identifier"}],"navigatorTitle":[{"text":"TileRegionLoadOptions","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXTileRegionLoadOptions/averageBytesPerSecond":{"fragments":[{"kind":"identifier","text":"averageBytesPerSecond"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXTileRegionLoadOptions\/averageBytesPerSecond","title":"averageBytesPerSecond","url":"\/documentation\/mapboxcommon\/mbxtileregionloadoptions\/averagebytespersecond","role":"symbol","kind":"symbol","abstract":[{"text":"Limits the download speed of the tile region.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"url":"\/documentation\/mapboxmaps","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","title":"MapboxMaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"MBXTileRegionLoadOptions","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/title"},{"value":[{"text":"MBXTileRegionLoadOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/fragments"},{"value":[{"kind":"identifier","text":"MBXTileRegionLoadOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadOptions\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}