{"metadata":{"symbolKind":"property","title":"layerId","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"layerId","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"text":"layerId","kind":"identifier"}],"externalID":"c:objc(cs)MBMFeaturesetDescriptor(py)layerId","modules":[{"name":"MapboxMaps"}]},"abstract":[{"text":"An optional unique identifier for the layer within the current style.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/featuresetdescriptor-swift.class\/layerid"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/featuresetdescriptor-swift.class\/layerid"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"layerId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"Note: If ","type":"text"},{"type":"codeVoice","code":"featuresetId"},{"type":"text","text":" is valid, "},{"code":"layerId","type":"codeVoice"},{"type":"text","text":" will be ignored even if it has a valid value."},{"text":" ","type":"text"},{"type":"text","text":"Additionally, "},{"type":"codeVoice","code":"importId"},{"text":" does not apply when using ","type":"text"},{"code":"layerId","type":"codeVoice"},{"type":"text","text":"."}]}]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeaturesetDescriptor-swift.class\/layerId","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeaturesetDescriptor-swift.class"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","role":"collection","title":"MapboxMaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMap-APIs":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMap-APIs","kind":"article","role":"collectionGroup","type":"topic","title":"MapboxMap","url":"\/documentation\/mapboxmaps\/mapboxmap-apis","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FeaturesetDescriptor-swift.class":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeaturesetDescriptor-swift.class","abstract":[{"text":"Represents an identifier for a single exported featureset or a layer.","type":"text"}],"type":"topic","title":"FeaturesetDescriptor","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FeaturesetDescriptor","kind":"identifier"}],"navigatorTitle":[{"text":"FeaturesetDescriptor","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/featuresetdescriptor-swift.class","role":"symbol","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection","kind":"article","type":"topic","url":"\/documentation\/overview","title":"MapboxMaps Documentation","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FeaturesetDescriptor-swift.class/layerId":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"layerId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"layerId","navigatorTitle":[{"text":"layerId","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/featuresetdescriptor-swift.class\/layerid","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeaturesetDescriptor-swift.class\/layerId","abstract":[{"type":"text","text":"An optional unique identifier for the layer within the current style."}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"layerId","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"layerId"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"layerId"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"value":"MBMFeaturesetDescriptor","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeaturesetDescriptor-swift.class\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MBMFeaturesetDescriptor"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeaturesetDescriptor-swift.class\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeaturesetDescriptor-swift.class\/navigatorTitle","value":[{"text":"MBMFeaturesetDescriptor","kind":"identifier"}],"op":"replace"},{"value":"layerId","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeaturesetDescriptor-swift.class~1layerId\/title"},{"op":"replace","value":[{"kind":"identifier","text":"layerId"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeaturesetDescriptor-swift.class~1layerId\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}