{"metadata":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"HttpServiceInterceptorResponseContinuation","kind":"identifier"}],"title":"HttpServiceInterceptorResponseContinuation","roleHeading":"Type Alias","symbolKind":"typealias","modules":[{"name":"MapboxCommon"}],"externalID":"c:MBXHttpServiceInterceptorResponseContinuation.h@T@MBXHttpServiceInterceptorResponseContinuation","navigatorTitle":[{"text":"HttpServiceInterceptorResponseContinuation","kind":"identifier"}],"role":"symbol"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"HttpServiceInterceptorResponseContinuation","kind":"identifier"},{"text":" = (","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBXHttpResponse","text":"HttpResponse","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpResponse","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"}]}],"kind":"declarations"}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceInterceptorResponseContinuation"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/httpserviceinterceptorresponsecontinuation"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/httpserviceinterceptorresponsecontinuation"]}],"abstract":[{"type":"text","text":"Continuation to be invoked once the interceptor is done processing a request’s response."}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpServiceInterceptorResponseContinuation":{"kind":"symbol","title":"HttpServiceInterceptorResponseContinuation","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"HttpServiceInterceptorResponseContinuation"}],"abstract":[{"text":"Continuation to be invoked once the interceptor is done processing a request’s response.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"HttpServiceInterceptorResponseContinuation"}],"url":"\/documentation\/mapboxcommon\/httpserviceinterceptorresponsecontinuation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceInterceptorResponseContinuation","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"abstract":[],"kind":"article","url":"\/documentation\/overview","role":"collection","title":"MapboxMaps Documentation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","title":"MapboxCommon","kind":"symbol","role":"collection","url":"\/documentation\/mapboxcommon","type":"topic","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpResponse":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpResponse","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"HttpResponse"}],"navigatorTitle":[{"text":"HttpResponse","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/httpresponse","title":"HttpResponse","abstract":[{"type":"text","text":"Record which is used to report HTTP response to the caller."}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Type Alias","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"MBXHttpServiceInterceptorResponseContinuation"},{"value":"typealias","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"MBXHttpServiceInterceptorResponseContinuation","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"MBXHttpServiceInterceptorResponseContinuation","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"text":"void (^)(MBXHttpResponse *)","preciseIdentifier":"c:BFv(#*$objc(cs)MBXHttpResponse)","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBXHttpServiceInterceptorResponseContinuation"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceInterceptorResponseContinuation\/title","value":"MBXHttpServiceInterceptorResponseContinuation"},{"value":[{"text":"MBXHttpServiceInterceptorResponseContinuation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceInterceptorResponseContinuation\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MBXHttpServiceInterceptorResponseContinuation"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceInterceptorResponseContinuation\/navigatorTitle"},{"value":"MBXHttpResponse","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpResponse\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpResponse\/fragments","value":[{"text":"MBXHttpResponse","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpResponse\/navigatorTitle","op":"replace","value":[{"text":"MBXHttpResponse","kind":"identifier"}]}]}]}