{"sections":[],"metadata":{"externalID":"c:MBXHttpServiceInterceptorRequestContinuation.h@T@MBXHttpServiceInterceptorRequestContinuation","role":"symbol","roleHeading":"Type Alias","title":"HttpServiceInterceptorRequestContinuation","symbolKind":"typealias","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HttpServiceInterceptorRequestContinuation"}],"navigatorTitle":[{"text":"HttpServiceInterceptorRequestContinuation","kind":"identifier"}],"modules":[{"name":"MapboxCommon"}]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceInterceptorRequestContinuation","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Continuation to be invoked once the interceptor is done processing a request. If invoked with a HttpRequest, the"},{"text":" ","type":"text"},{"text":"HTTP service will proceed to make a request via the network. Invoking the continuation with a HttpResponse bypasses","type":"text"},{"text":" ","type":"text"},{"text":"the network and causes the request to complete immediately with the specified response. The ID of the HttpResponse","type":"text"},{"type":"text","text":" "},{"type":"text","text":"is irrelevant in this case."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HttpServiceInterceptorRequestContinuation"},{"text":" = (","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBXHttpRequestOrResponse","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestOrResponse","text":"HttpRequestOrResponse","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/httpserviceinterceptorrequestcontinuation"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/httpserviceinterceptorrequestcontinuation"]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpServiceInterceptorRequestContinuation":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"HttpServiceInterceptorRequestContinuation","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/httpserviceinterceptorrequestcontinuation","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpServiceInterceptorRequestContinuation","abstract":[{"type":"text","text":"Continuation to be invoked once the interceptor is done processing a request. If invoked with a HttpRequest, the"},{"text":" ","type":"text"},{"type":"text","text":"HTTP service will proceed to make a request via the network. Invoking the continuation with a HttpResponse bypasses"},{"type":"text","text":" "},{"text":"the network and causes the request to complete immediately with the specified response. The ID of the HttpResponse","type":"text"},{"type":"text","text":" "},{"type":"text","text":"is irrelevant in this case."}],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"HttpServiceInterceptorRequestContinuation","kind":"identifier"}],"title":"HttpServiceInterceptorRequestContinuation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestOrResponse":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HttpRequestOrResponse"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"HttpRequestOrResponse","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestOrResponse","url":"\/documentation\/mapboxcommon\/httprequestorresponse","type":"topic","kind":"symbol","title":"HttpRequestOrResponse","abstract":[{"type":"text","text":"Contains either an HttpRequest or an HttpResponse."}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"url":"\/documentation\/overview","role":"collection","type":"topic","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"role":"collection","kind":"symbol","abstract":[],"url":"\/documentation\/mapboxcommon","title":"MapboxCommon","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Alias"},{"op":"replace","path":"\/metadata\/title","value":"MBXHttpServiceInterceptorRequestContinuation"},{"value":"typealias","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"MBXHttpServiceInterceptorRequestContinuation","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MBXHttpServiceInterceptorRequestContinuation"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"void (^)(MBXHttpRequestOrResponse *)","preciseIdentifier":"c:BFv(#*$objc(cs)MBXHttpRequestOrResponse)"},{"kind":"text","text":" "},{"text":"MBXHttpServiceInterceptorRequestContinuation","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MBXHttpServiceInterceptorRequestContinuation","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceInterceptorRequestContinuation\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceInterceptorRequestContinuation\/fragments","value":[{"text":"MBXHttpServiceInterceptorRequestContinuation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpServiceInterceptorRequestContinuation\/navigatorTitle","value":[{"kind":"identifier","text":"MBXHttpServiceInterceptorRequestContinuation"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestOrResponse\/title","value":"MBXHttpRequestOrResponse","op":"replace"},{"value":[{"text":"MBXHttpRequestOrResponse","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestOrResponse\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestOrResponse\/navigatorTitle","value":[{"kind":"identifier","text":"MBXHttpRequestOrResponse"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}