{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/mbxtileregionerrortypetostring(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/mbxtileregionerrortypetostring(_:)"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBXTileRegionErrorTypeToString"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"tile_region_error_type","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@MBXTileRegionErrorType","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType","kind":"typeIdentifier","text":"TileRegionErrorType"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"!"}]}]}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBXTileRegionErrorTypeToString"},{"text":"(","kind":"text"},{"text":"TileRegionErrorType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBXTileRegionErrorType"},{"kind":"text","text":") -> "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"externalID":"c:@F@MBXTileRegionErrorTypeToString","symbolKind":"func","roleHeading":"Function","modules":[{"name":"MapboxCommon"}],"title":"MBXTileRegionErrorTypeToString(_:)","role":"symbol","navigatorTitle":[{"text":"MBXTileRegionErrorTypeToString","kind":"identifier"}]},"sections":[],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXTileRegionErrorTypeToString(_:)","interfaceLanguage":"swift"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"role":"collection","kind":"symbol","abstract":[],"url":"\/documentation\/mapboxcommon","title":"MapboxCommon","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","abstract":[],"url":"\/documentation\/overview","role":"collection","type":"topic","title":"MapboxMaps Documentation"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXTileRegionErrorTypeToString(_:)":{"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBXTileRegionErrorTypeToString"}],"url":"\/documentation\/mapboxcommon\/mbxtileregionerrortypetostring(_:)","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXTileRegionErrorTypeToString(_:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"MBXTileRegionErrorTypeToString","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBXTileRegionErrorType","text":"TileRegionErrorType"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"title":"MBXTileRegionErrorTypeToString(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionErrorType":{"url":"\/documentation\/mapboxcommon\/tileregionerrortype","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TileRegionErrorType","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Describes the reason for a tile region download request failure."}],"title":"TileRegionErrorType","navigatorTitle":[{"kind":"identifier","text":"TileRegionErrorType"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Function"},{"op":"replace","path":"\/metadata\/title","value":"MBXTileRegionErrorTypeToString"},{"path":"\/metadata\/symbolKind","value":"func","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MBXTileRegionErrorTypeToString","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"MBXTileRegionErrorTypeToString"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@MBXTileRegionErrorType","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType","kind":"typeIdentifier","text":"MBXTileRegionErrorType"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"tile_region_error_type"},{"text":");","kind":"text"}]}]}},{"value":"MBXTileRegionErrorTypeToString","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MBXTileRegionErrorTypeToString(_:)\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MBXTileRegionErrorTypeToString(_:)\/fragments","value":[{"kind":"identifier","text":"MBXTileRegionErrorTypeToString"}],"op":"replace"},{"value":"MBXTileRegionErrorType","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionErrorType\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionErrorType\/fragments","value":[{"text":"MBXTileRegionErrorType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionErrorType\/navigatorTitle","op":"replace","value":[{"text":"MBXTileRegionErrorType","kind":"identifier"}]}]}]}